### ISSUE TITLE
vue will create double watcher when this Situation

### ISSUE THREAD

**Issue by zhangenming** [vuejs/vue#10006]
### Version
2.6.10

### Reproduction link
[http://plnkr.co/edit/aKSqM1wLkSPmgip2p0gZ?p=preview](http://plnkr.co/edit/aKSqM1wLkSPmgip2p0gZ?p=preview)

### Steps to reproduce
http://plnkr.co/edit/aKSqM1wLkSPmgip2p0gZ?p=preview

### What is expected?
dont't call callHook(vm, 'beforeMount') again

### What is actually happening?
double call callHook(vm, 'beforeMount')

---
and will created double Watcher

**Comment by phiter** [comment]
I think this is happening because you're using both `el: '#app'` and `$mount('#app')`, binding the instance to that element twice.

**Comment by zhangenming** [comment]
so should we add some code on file lifecycle.js  mountComponent
such as
`if(vm._isMounted)return`?

**Comment by phiter** [comment]
I think you should just pick either `el: '#app'` or `$mount('#app')`.
I would go for `el` because it's simpler.

The docs explain what `$mount` is for:

> If a Vue instance didn’t receive the el option at instantiation, it will be in “unmounted” state, without an associated DOM element. vm.$mount() can be used to manually start the mounting of an unmounted Vue instance.

https://vuejs.org/v2/api/#vm-mount

**Comment by posva** [comment]
what @phiter said!

**Comment by zhangenming** [comment]
> what @phiter said!

but isn't this a bug?
When I accidentally have both

**Comment by posva** [comment]
no, you can only use one of them. As stated in the docs:

- no `el` -> unmounted state -> can call `$mount` to start mounting
- `el` -> mounts

**Comment by leopiccionia** [comment]
@posva Couldn't it be the case of raising an error or warning? If you try to mount an already mounted VM instance, I mean.

**Comment by phiter** [comment]
I agree that you should get a warning when you mount an instance twice or on the same element twice.

**Comment by posva** [comment]
Sure, feel free to create a PR 🙂
