### ISSUE TITLE
vue.js 组件 scoped样式打包之后会丢失

### ISSUE THREAD

**Issue by p354139076** [vuejs/vue#10008]
### Version
2.6.10

### Reproduction link
[https://github.com/p354139076/longlink-sass/settings](https://github.com/p354139076/longlink-sass/settings)

### Steps to reproduce
运行npm run build 将安装包部署在nginx上。会发现生产环境下的css部分样式丢失，与开发环境不一致。

### What is expected?
开发环境css与生产环境css一致

### What is actually happening?
开发环境css与生产环境css不一致

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
