### ISSUE TITLE
In VueJS 2.6.10 module export defaults only works on .vue files even with libraryExport: “default”

### ISSUE THREAD

**Issue by diazemiliano** [vuejs/vue#10005]
### Version
2.6.10

### Reproduction link
[https://forum.vuejs.org/t/in-vuejs-2-6-10-module-export-defaults-only-works-on-vue-files-even-with-libraryexport-default/63454](https://forum.vuejs.org/t/in-vuejs-2-6-10-module-export-defaults-only-works-on-vue-files-even-with-libraryexport-default/63454)

## Configs
```
// vue.config.js
...
	configureWebpack: {
		output: {
			libraryExport: "default",
		},
	},
...

// babel.config.js
...
  	presets: [["@vue/app"]],
...
```

## This Works
```
// main.js
import ComponentA from "./Components/ComponentA.vue";
```
## This Not
```
// main.js
import AllTheComponents from "./Components/index.js";

console.log(AllTheComponents );
// Outputs
// Forms: Module {
//   Symbol(Symbol.toStringTag): "Module"
// }

console.log(AllTheComponents.ComponentA );
// Outputs
// Can't read prop ComponentA of undefined
```

```
// ./Components/index.js
import ComponentA from "./Components/ComponentA.vue";
import ComponentB from "./Components/ComponentB.vue";


export default {
  ComponentA,
  ComponentB
}
```

### What is expected?
Access to the module props normally.

### What is actually happening?
Having can't read [propname] of undefined.

---
https://forum.vuejs.org/t/in-vuejs-2-6-10-module-export-defaults-only-works-on-vue-files-even-with-libraryexport-default/63454

**Comment by posva** [comment]
Please, keep the questions on the forum. This is a webpack configuration issue rather than a vue problem

**Comment by LinusBorg** [comment]
This is documented: https://cli.vuejs.org/guide/build-targets.html#vue-vs-js-ts-entry-files

**Comment by diazemiliano** [comment]
As you can read in the example. Im not using named exports. Im just exporting default. And as the docs says also I'm doing `libraryExport: "default"`.
