### ISSUE TITLE
Memory leak while simply changing routes

### ISSUE THREAD

**Issue by ricardo-lobo** [vuejs/vue#10002]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/o5znmm1lnq](https://codesandbox.io/s/o5znmm1lnq)

### Steps to reproduce
- Start a new vuejs project with vue-cli
- Add vue-router
- Add an input with v-model
- Type something in the input
- Change route

#### Chrome dev tools snapshots screens follows:

Base line snapshot
![Image of 1](https://i.postimg.cc/qvx7gzcF/Screenshot-2019-05-09-at-17-25-27.png)

Snapshot while just switching routes
![Image of 2](https://i.postimg.cc/rphFC3PC/Screenshot-2019-05-09-at-17-25-35.png)

Snapshot after typing in the input
![Image of 3](https://i.postimg.cc/KYc8TxJ8/Screenshot-2019-05-09-at-17-25-42.png)

Another snapshot after typing in the input
![Image of 4](https://i.postimg.cc/rwkm8S4W/Screenshot-2019-05-09-at-17-25-53.png)

Another snapshot after typing in the input
![Image of 5](https://i.postimg.cc/59DyrcNs/Screenshot-2019-05-09-at-17-26-01.png)

We can find all the old "about" components in the memory with the respective data along with it
![Image of 6](https://i.postimg.cc/qRSJWn0N/Screenshot-2019-05-09-at-17-24-12.png)
![Image of 7](https://i.postimg.cc/0jSkvQ2c/Screenshot-2019-05-09-at-17-24-26.png)
![Image of 8](https://i.postimg.cc/xCcjsgrr/Screenshot-2019-05-09-at-17-24-41.png)

The memory increase is noticeable when the component is "big"

### What is expected?
Its expected to have the vue components correctly garbage collected.

### What is actually happening?
Everytime we switch routes after typing something in the input, the vue components count increases by 2 (in the linked example) with the older components remaining in memory with the state attached.

Although this doesn't seem to have a big impact, with complex applications, this can blow up rapidly while increasing memory until the browser tab crashes.

---
In our internal app, every time we switch routes, the memory increase is about 20 megabytes. The components left in memory have big data attached.

**Comment by posva** [comment]
Closing in favour of https://github.com/vuejs/vue/issues/10004 with no router and an html repro
