### ISSUE TITLE
Keep-alive doesn't work with nested routes

### ISSUE THREAD

**Issue by CapitaineToinon** [vuejs/vue#10011]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/ypk7jx47rv](https://codesandbox.io/embed/ypk7jx47rv)

### Steps to reproduce
* Use vue-router and use keep-alive around your main router-view
* Cache a route that has childen routes (for example `/user/:id`)
* Add a 2nd router-view and also use keep-alive around it
* Cache only a sub part of the child routes (for example cache `/user/:id` but not `/user/:id/articles`)
* From the homepage, access directly a non-cached sub page (for example `/user/:id/articles`)

### What is expected?
The sub routes that aren't listed by the keep-alive around the nested routes shouldn't be cached.

### What is actually happening?
The sub routes are cached. (Can be seen by the activated hook being triggered)

---
I'm not sure if this really fits into bug, maybe this behavior is intended? The sub route won't be cached if accessed in this order :
`Home > Foo's profile > Foo's articles` but will if doing `Home > Foo's articles`.

**Comment by posva** [comment]
activated also triggers when a parent that is kept alive is activated, so they are triggering because of the parent route

**Comment by haiting** [comment]
> activated also triggers when a parent that is kept alive is activated, so they are triggering because of the parent route

so, If i have these code:

`firstLayer.vue` 
```
 <router-view #="{ Component }">
    <keep-alive>
      <component :is="Component" />
    </keep-alive>
  </router-view>
  ```
  
  `secondLayer.vue` 
  
  ```
  <router-view >
    </router-view>
    ```
    
    `child.vue`
    ```
    code....
    ```
  
 cache  is not working for the `child.vue` component?
