### ISSUE TITLE
mounted: does not guarantee that all child components have also been mounted？

### ISSUE THREAD

**Issue by jxZhangLi** [vuejs/vue#10017]
### What problem does this feature solve?
null

### What does the proposed API look like?
null

The documentation describes the mounted hook：Note that mounted does not guarantee that all child components have also been mounted. If you want to wait until the entire view has been rendered, you can use vm.$nextTick inside of mounted。

By the time of each mounted function, the component has executed _render _update. The element has been added to the page (the child component executes the hook first, and the parent component executes it) the entire view has been rendered。why add $nextTick？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you have an improvement point on vue docs, please check existing issues and PR in vuejs.org repo and open an issue or PR to improve them 🙂
