### ISSUE TITLE
chromeDriver installation failed,Error: EISDIR: illegal operation on a directory,read

### ISSUE THREAD

**Issue by Xavier0818** [vuejs/vue#10025]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1.git clone `https://github.com/vuejs/vue-router.git`;

2.run `npm install`;

3.error log：

D:\vue-router-dev>npm install

npm WARN deprecated rollup-watch@4.3.1: rollup-watch functionality is now included in Rollup itself

npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). 
Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). 
Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). 
Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

> chromedriver@2.46.0 install D:\vue-router-dev\node_modules\chromedriver

> node install.js

ChromeDriver binary exists. Validating...

ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)

ChromeDriver is already available at 'C:\Users\ADMINI~1\AppData\Local\Temp\2.46\chromedriver\chromedriver.exe'.

Copying to target path D:\vue-router-dev\node_modules\chromedriver\lib\chromedriver

events.js:167

      throw er; // Unhandled 'error' event

      ^

Error: EISDIR: illegal operation on a directory, read

Emitted 'error' event at:

    at lazyFs.read (internal/fs/streams.js:165:12)

    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! chromedriver@2.46.0 install: `node install.js`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the chromedriver@2.46.0 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-05-15T06_23_24_746Z-debug.log

### What is expected?
installation succeed

### What is actually happening?
installation failed

**Comment by posva** [comment]
you opened the issue twice. if you need help making the repo work, please ask questions in the forum. You should also use yarn for our repos
