### ISSUE TITLE
How can I start or run this project?

### ISSUE THREAD

**Issue by Anil-bohorya** [vuejs/vue#10023]

**Comment by LinusBorg** [comment]
Are you looking for this? 

https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md

**Comment by Anil-bohorya** [comment]
I already tried 'npm run dev'.

getting below results

rollup v1.10.1
bundles /Users/anil.kumar1/Downloads/vue-dev/src/platforms/web/entry-runtime-with-compiler.js → dist/vue.js...
created dist/vue.js in 3.4s

[2019-05-15 11:08:31] waiting for changes...


what is the port number?

**Comment by LinusBorg** [comment]
There's no dev Server, so there is no port. 

It only builds Vue and re-builds on changes.
