### ISSUE TITLE
MS Edge: v-if after v-else creates a duplicate element in DOM

### ISSUE THREAD

**Issue by gprl** [vuejs/vue#10020]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/d80c3p7s/](https://jsfiddle.net/d80c3p7s/)

### Steps to reproduce
Issue is only present in Microsoft Edge, reproduced on
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

To reproduce click on the initial text 'Tap to Open'
Then tap again to close it.

The element containing the text 'Subtitle' will be duplicated

### What is expected?
Elements with v-if="!opened" are not rendered when open is set to true and the v-else element gets rendered

### What is actually happening?
Element with v-if="!opened" after the element with the v-else is present in the DOM

---
In this example the issue seems harmless, but in our larger project, the duplicate element is causing the click event to be triggered twice. To the user it seems as if its not opening, while in reality it is opening and closing

**Comment by posva** [comment]
Tried on Edge 18 and Insider on Windows 10 and Edge canary on OSX and it works fine: no duplicated elements

**Comment by gprl** [comment]
![image](https://user-images.githubusercontent.com/48945588/57642224-11d2bf80-75b7-11e9-9fb0-4e9a731ab399.png)

Sorry for bothering you again, but the duplicated element is not visible in the UI. I ran it on Microsoft EdgeHTML 17.17134 and Microsoft EdgeHTML 18.17763 on Windows 10 and got the same result

**Comment by posva** [comment]
It looks like an Edge devtools bug as the node goes away when you close/reopen the panel. You should report it in their bug tracker (idk where it is)
