### ISSUE TITLE
如何使用编程式导航打开新窗口,拒绝window.open

### ISSUE THREAD

**Issue by Valar103769** [vuejs/vue#10033]
### Version
2.6.10

### Reproduction link
[https://juejin.im/post/5af55b296fb9a07ace58ecc6](https://juejin.im/post/5af55b296fb9a07ace58ecc6)

### Steps to reproduce
希望提供一个api,如果有

### What is expected?
no

### What is actually happening?
紧急

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。

---

PS. 你提的这个需求和 Vue 没有关系。
