### ISSUE TITLE
Watcher custom handler not returning correct values

### ISSUE THREAD

**Issue by DevArenaCN** [vuejs/vue#10032]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/devarenacn/fzwytpad/1/](https://jsfiddle.net/devarenacn/fzwytpad/1/)

### Steps to reproduce
Set watcher with deep true, when reordering the value (an array) under one of the keys inside the object, the new value and old value returns the same thing.

### What is expected?
Should return old value and new value

### What is actually happening?
Returning same value, both the updated one.

**Comment by posva** [comment]
This is expected, arrays and objects are the same reference, so old and new values are different variables pointing to the same object

**Comment by DevArenaCN** [comment]
@posva Is there a way to create a custom watcher handler to resolve this?

**Comment by posva** [comment]
not with a different watcher but you can create a new array and reassign the value, that way you do have two different values in new and old

**Comment by sirlancelot** [comment]
If you need to keep track of previous values of objects, you can add a watcher to the object that you expect to change:

```js
this.$watch("obj.section", (value, previous) => {
})
```

**Comment by DevArenaCN** [comment]
@posva @sirlancelot Thanks for answering! I think I got a hang of it now.
