### ISSUE TITLE
childOb.dep.depend() is not necessary for object

### ISSUE THREAD

**Issue by lingwenzhi** [vuejs/vue#10036]
### What problem does this feature solve?
In core/observer/index.js
if (childOb) {
  childOb.dep.depend()
  if (Array.isArray(value) {
    dependArray(value)
  }
}
can change to: ?
if (childOb && Array.isArray(value)) {
  childOb.dep.depend()
  dependArray(value)
}

### What does the proposed API look like?
no

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

---

if you are reporting a bug, include a repro. If you want to improve the code, you can create a PR. If the statement is indeed not necessary, tests should still pass. But you can directly test this locally, it will be faster to check for you :)
