### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Vcc1** [vuejs/vue#10034]
### Version
2.5.21

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
<template>
  <div>
    <input @focus="count  " type="text">
    {{count}}
  </div>
</template>
<script>
import Vue from "vue";
export default {
  name: "home",
  data: function() {
    return {
      count: 0
    };
  }
};
</script>

使用此页面 在IOS 中打开 点击10次input框观察数值变化 会有一次点击 2次的情况

### What is expected?
为啥会这样

### What is actually happening?
使用此页面 在IOS 中打开 点击10次input框观察数值变化 会有一次点击 2次的情况

**Comment by Justineo** [comment]
请不要随意填写 reproduction link，这对于 bug report 是必要条件，谢谢。

**Comment by Vcc1** [comment]
ok 问题找到了 IOS 最新版本 会触发多次焦点事件
