### ISSUE TITLE
In directives not work removeEventListener

### ISSUE THREAD

**Issue by Pinegin** [vuejs/vue#10038]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-gogqi](https://codesandbox.io/s/vue-template-gogqi)

### Steps to reproduce
type in input

### What is expected?
v-model should not work

### What is actually happening?
v-model works

---
in version 2.5.1 everything works as it should

**Comment by posva** [comment]
This is not supported, you either handle event listeners yourself (with addEventListener + removeEventListener) or handle it with Vue. Doing a mix is not going to yield expected results. Moreover, overriding event removal with a directive doesn't look like a good idea
