### ISSUE TITLE
Illegal invocation on Mobile Safari

### ISSUE THREAD

**Issue by mizunashi-mana** [vuejs/vue#10049]
### Version
2.6.10

### Reproduction link
[https://github.com/mizunashi-mana/blog](https://github.com/mizunashi-mana/blog)

### Steps to reproduce
I cannot reproduce it.  However, it appears that a viewer of my blog meets this error.  The viewer's environment:

* Stacktrace: https://sentry.io/share/issue/1dcf3400778f4e05a34fadf1c2ce1c73/
* URL: https://mizunashi-mana.github.io/blog/posts/2019/05/ghc-io-inside/?fbclid=IwAR1qI5IrgFg8ElCZ3_jtYYBv46nvjhy2uql6pov7T31Exu6XOOaDfPgD8QQ
* User-Agent: Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1
* Device: Apple iPad
* OS: iOS 12.2
* Browser: Mobile Safari 12.1

However, I don't have iPad, so I cannot debug it.

### What is expected?
no error

### What is actually happening?
threw illegal invocation error

---
The target of stack trace is here: https://github.com/vuejs/vue/blob/v2.6.10/src/core/observer/scheduler.js#L58

**Comment by posva** [comment]
Tested your blog on iPad with ios12 and there is no error

If the error appears on the line you specified, then it should be related to calling `document.createEvent('Event')`. However, it seems that there is something else causing it appear but I couldn't find what. Is it like an uncaught exception that breaks the website completely? If so, we will need a reproduction to check it
Maybe users are visiting the website through an embedded Webview with custom behaviour breaking it.

Closing until someone has a consistent reproduction of this. Please, ping me once you have it

**Comment by codinronan** [comment]
For anyone running across this, there is no mystery. Whenever someone shares a link on Facebook, FB immediately sends their crawler to crawl the page (that's what the fbclid param is in the url in the original post). That crawler uses a custom user agent that has this API disabled: https://github.com/aFarkas/lazysizes/issues/520

As this error occurs on FB's server side, and never to an actual user, you should be fine (obviously you want to check your error logs to verify this in each case).
