### ISSUE TITLE
Documentation not clear concerning directive "inserted" hooks

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#10042]
### Version
2.6.10

### Reproduction link
[https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions](https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions)

### Steps to reproduce
Read the documentation about custom directive's and the inserted hook.

### What is expected?
To know about the hook's moment in the directive's lifecycle.

### What is actually happening?
The documentation mentions : 
> "inserted: called when the bound element has been inserted into its parent node (this only guarantees parent node presence, not necessarily in-document)."

The current sentence doesn't provide reliable information about the conditions needed for the the directive to be or not to be attached to the current document at the time of inserted hook call.

---
My guess is that it depends on the context's vnode and the directive's vnode node being synchronously rendered (or not), but I've only clues.

If that's the case, it would be nice to have an actual "flatten" way to handle it, like an additional hook or a different lifecycle.

**Comment by posva** [comment]
Please, check vuejs.org repo for existing issues/PR about this topic and if there isn't any open an issue or PR with a proposal to start a discussion about how to improve it :)
