### ISSUE TITLE
Inclusivity Fix (New Contributor)

### ISSUE THREAD

**Issue by JonathanGrocott** [vuejs/vue#10040]
As part of an open source class assignment a group evaluated your project from the perspective of a novice/new contributor. This is part of an OSS gender inclusive initiative. There were several facets to this persona that led us to suggest a fix (please see persona attached). Before creating a PR i wanted to start the conversion on whether this fix is wanted/granted. The fix would require changes to the "Development Setup" section of the Contributing.md. We found that the lack of information provided in this section might halt a newcomers progress towards making a contribution. 
[Abi 464.pdf](https://github.com/vuejs/vue/files/3189422/Abi.464.pdf)

**Comment by posva** [comment]
Hey, contributions to make our guidelines more inclusive, welcoming and/or accessible are always welcome. It's okay to start a PR to start a discussion for this :)
