### ISSUE TITLE
Inclusivity Fix (New Contributor)

### ISSUE THREAD

**Issue by JonathanGrocott** [vuejs/vue#10046]
[Abi 464.pdf](https://github.com/vuejs/vue/files/3192343/Abi.464.pdf)
### What problem does this feature solve?
As part of an open source class assignment a group evaluated your project from the perspective of a novice/new contributor. This is part of an OSS gender inclusive initiative. There were several facets to this persona that led us to suggest a fix (please see persona attached). Before creating a PR i wanted to start the conversion on whether this fix is wanted/granted. 

### What does the proposed API look like?
The fix would require changes to the "Development Setup" section of the Contributing.md. We found that the lack of information provided in this section might halt a newcomers progress towards making a contribution.

**Comment by Justineo** [comment]
https://github.com/vuejs/vue/issues/10040#issuecomment-493340045

**Comment by posva** [comment]
Yes, please! But do a PR instead with your proposal instead, thanks!
