### ISSUE TITLE
Unexpected behaviour when using v-on:input and v-bind:value instead of v-model.

### ISSUE THREAD

**Issue by adjenks** [vuejs/vue#10047]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/9mj0nakc/2/](https://jsfiddle.net/9mj0nakc/2/)

### Steps to reproduce
Type in each input

### What is expected?
Input box 2 to be bound to variable test.b

### What is actually happening?
It doesn't behave like v-model

---
On this page:
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

It says that
`<input v-model="searchText">`

does the same thing as:
```
<input
  v-bind:value="searchText"
  v-on:input="searchText = $event.target.value"
>
```

But it appears this is not true when referencing a property of a variable, e.g. var['prop'].

If you do not think this is a problem, I would like to at least understand:
- what is special/different about v-model vs the second method that makes it work properly and listen to changes on the prop when the on&bind combination doesn't seem to listen to changes.
- and how I could make on&bind it work similarly to v-model.

**Comment by posva** [comment]
you must set the initial value of `b`. v-model gets around this by always using `$set`

---


Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by adjenks** [comment]
I have signed up to the discord server, thank you for the suggestion.

Perhaps the documentation should say something along the lines of:
>does the same thing as:
>
```html
<input
  v-bind:value="search.text"
  v-on:input="$set(search.'text',$event.target.value)"
>
```
instead of
>does the same thing as:
>
```html
<input
  v-bind:value="searchText"
  v-on:input="searchText = $event.target.value"
>
```

because it does not do 'the same thing as' currently described.
