### ISSUE TITLE
动态加载

### ISSUE THREAD

**Issue by huxiaozhong** [vuejs/vue#10053]
### What problem does this feature solve?
您好，目前vue所有代码都必须在前端完成，然后编译调用，我有项目，部分代码实在后台的，比如 我在vue方法里边写了一个ajax请求，请求返回了一段html和一段vue代码，能否把这段字符串 编译并渲染到当前页面，并让script中的代码也起作用，这是一种特殊场景，后端渲染太麻烦了

### What does the proposed API look like?
实现功能即可

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
