### ISSUE TITLE
ie11不兼容，页面白屏

### ISSUE THREAD

**Issue by StarryYang** [vuejs/vue#10058]
### Version
2.6.10

### Reproduction link
[http://59.110.233.137:88/web/#/](http://59.110.233.137:88/web/#/)

### Steps to reproduce
打开ie浏览器直接访问即可

### What is expected?
希望支持ie11,可以显示代码

### What is actually happening?
修改ie11的兼容性

**Comment by Harhao** [comment]
@StarryYang 装上babel-polyfill支持，IE10都可以使用

**Comment by StarryYang** [comment]
已经安装完了，
![image](https://user-images.githubusercontent.com/27389941/58150317-dca22d80-7c98-11e9-835d-e0573613f6ac.png)
![image](https://user-images.githubusercontent.com/27389941/58150344-ec217680-7c98-11e9-8191-a7ad498f6e2a.png)

但是还是不行，不知道什么原因，求大神们指点啊

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
