### ISSUE TITLE
Computed function does not re-compute when dependency change

### ISSUE THREAD

**Issue by rellect** [vuejs/vue#10054]
### Version
2.6.10

### Reproduction link
[https://codepen.io/rellect/pen/EzvrOz?editors=1011](https://codepen.io/rellect/pen/EzvrOz?editors=1011)

### Steps to reproduce
- Open the repro link
- Click the Toggle button
- See that the value changes but the dynamic component does not

### What is expected?
Dynamic component should change when the data property changes.

### What is actually happening?
The computed property does not react when the data property changes.

---
What I'm trying to do is a to import a component dynamically based on a reactive data property.
Something similar to the following:
```
<template>
  <div>
    <component :is="stepComp" :key="step"></component>
    <button type="button" @click="step++"></button>
  </div>
</template>

<script>
export default {
  data: () => ({
    step: 1,
  }),

  computed: {
    stepComp() {
      return () => import(`./steps/${this.step}`)
    }
  }
}
</script>
```

For some reason `stepComp` won't re-compute when `step` is changed.
It's not a big issue and I can workaround it, but still wonder if this is a bug or by design.

**Comment by posva** [comment]
you have to use the `this.val` outside of the callback function for it to be registered as a dependency of the computed property:

```js
dynamicComp() {
const { val } = this
      return (resolve) => resolve({ 
        template: `<div>Component val: ${val} << why it's not updating?</div>`
      })
    }
```

**Comment by rellect** [comment]
Yea this is the "workaround" I've been using, but I expected it to work AS IS since the dependency is used in an arrow function so it's within the same scope level.

**Comment by posva** [comment]
it's not a workaround. It's not about being in the same scope level, it's about the variable being read when the computed property is called, if you use it in a function returned, it won't be read and therefore not collected by Vue. Hope this helps 🙂

**Comment by rellect** [comment]
Oh that explains it, thanks!
