### ISSUE TITLE
Directive for both v-bind and v-on

### ISSUE THREAD

**Issue by Duarte-Dias** [vuejs/vue#10052]
### What problem does this feature solve?
I have several cases of components with different views, the children of these components are almost the same, but have some key differences, I want my code to be DRY and give the implementation in a base Component 

Imagine i have a component with this template:
```html
<template>
  <component is="myView" :textOptions="textOptions" />
</template>
```
Whatever view is chosen, there's always a text component inside that uses these textOptions like so:
```html
<TextComponent v-bind="textOptions.props" v-on="textOptions.listeners" :otherProps=" 'other' " />
```

### What does the proposed API look like?
I propose a new directive (which I'm calling v-all for now)
```html
 <TextComponent v-all="textOptions" />
```

**Comment by posva** [comment]
You already commented on the issue that was closed #9958 

You may be interested in https://github.com/vuejs/rfcs/pull/26 for v3
For v2, this doesn't happen often enough to introduce a new template syntax and can already be solved in a slightly more verbose way
