### ISSUE TITLE
The props item in the dynamic list is called repeatedly

### ISSUE THREAD

**Issue by falstack** [vuejs/vue#10063]
### Version
2.6.10

### Reproduction link
[https://github.com/falstack/oh-my-chat](https://github.com/falstack/oh-my-chat)

### Steps to reproduce
1. clone repo
2. yarn install & npm run dev
3. click button on page
4. open chrome console, there have logs

### What is expected?
Don't call method repeatedly

### What is actually happening?
Each item pushed into the array, method on the existing item props is called repeatedly

**Comment by falstack** [comment]
there [call console.log](https://github.com/falstack/oh-my-chat/blob/master/components/Room.vue#L99)

**Comment by posva** [comment]
Please, provide boiled down repros when reporting a bug. Not a full project

**Comment by falstack** [comment]
``` html
<!doctype html>
<html lang="zh-cmn-Hans">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>Document</title>
  <script src="http://cdn.bootcss.com/vue/2.6.10/vue.min.js"></script>
</head>
<body>
<div id="wrap">
  <ul>
    <li v-for="item in list">
      <v-display :text="computeProps(item)"></v-display>
    </li>
  </ul>
  <button @click="addItem">add</button>
</div>
<script>
  Vue.component('v-display', {
    props: ['text'],
    template: '<div>{{ text }}</div>'
  })
  new Vue({
    el: '#wrap',
    data() {
      return {
        list: []
      }
    },
    methods: {
      addItem() {
        this.list.push(Math.random().toString(10).substring(3, 6))
      },
      computeProps(text) {
        console.log('computeProps')
        return text
      }
    }
 });
</script>
</body>
</html>

```

@posva  please reopen this issue

**Comment by Justineo** [comment]
@falstack Since your case doesn't require a build step, please use JSFiddle/CodePen to host your reproduction. Then feel free to open a new issue with proper repro. Thanks.

**Comment by falstack** [comment]
@Justineo JSFiddle/CodePen is not accessible from our company's network environment

You copy my code, open in chrome, click button on page, will see the `computeProps ` method called repeatedly

Please don't complicate a simple thing

**Comment by posva** [comment]
This is working as expected because the method gets called everytime the template needs to re render. I think you may be interested in vue-local-scope to generate computed props in template

**Comment by falstack** [comment]
@posva 
I know it's not a bug, but it's a performance issue, and when my list is very large, calling method repeatedly is not a good thing

It might be possible to do some optimization here

**Comment by falstack** [comment]
By the way, this has nothing to do with `v-for:key`, the inserted item in the demo are not re-rendered

**Comment by posva** [comment]
It's by design, take a look at https://github.com/posva/vue-local-scopE, it solves the perf issue

**Comment by falstack** [comment]
thanks
