### ISSUE TITLE
Events dont fire inside child components

### ISSUE THREAD

**Issue by MarkCavalli** [vuejs/vue#10068]
### Version
2.6.10

### Reproduction link
[https://no.site](https://no.site)

### Steps to reproduce
You need to install RAGE multiplayer and GTA 5 to reproduce it. If you will be interested, i will provide more info and can help with it

### What is expected?
You have button with 2 div's inside (img and text)

Click fires on img or text click

### What is actually happening?
Sometimes click handler stop working inside child elements for some time (10 seconds or longer).
This issue reproducing inside chrome embedded framework (CEF) inside RAGE Multiplayer only. In ordinary browser all fine! 

---
Please write if you're interested. For reproducing you will need to install GTA 5 (Steam) and rage multiplayer. I can give you GTA 5 licence for debugging time

**Comment by KaelWD** [comment]
I'm gonna take a wild guess and say that's GTA being GTA. Does `el.addEventListener` stop working too?

**Comment by MarkCavalli** [comment]
@KaelWD nope, events successfully fired on root element (button). Got some feedback from other RAGE developers. Seems "^2.5.22" - last stable version in CEF without this bug

**Comment by posva** [comment]
This is probably related to the micro to macro task change in 2.6.
Please check release notes and other issues related to this.
BTW as you can imagine, a boiled down repro is necessary for us to be able to debug. We won't be able to debug in Gta and may not even have the computer to run it
