### ISSUE TITLE
development server hangs unexpectedly

### ISSUE THREAD

**Issue by shahzaibanwar009** [vuejs/vue#10069]
### Version
2.5.9

### Reproduction link
[https://google.com](https://google.com)

### Steps to reproduce
development server held unexpectedly.Running slowly not building completely

### What is expected?
Development server should be running or building fast not hang

### What is actually happening?
development server held unexpectedly.Running slowly not building completely

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
