### ISSUE TITLE
how can i pass global registered component as prop to a component

### ISSUE THREAD

**Issue by LycheeHe** [vuejs/vue#10062]
### What problem does this feature solve?
It doesn't be solved, I think vue should support the function of  passing component as prop while user is using a component to make reused component.

### What does the proposed API look like?
<dropdown :icon="UserIcon"></dropdown>

dropdown is my custom component , so as UserIcon. 
and I can't use UserIcon using icon element to show what it is in UserIcon

**Here's my code:**
**a.vue**
 html
`<dropdown :icon="UserIcon"></dropdown>`
js
`components: {'dropdown', Dropdown, 'icon-user': UserIcon}`

**dropdown.vue**
html
`<div class="dropdown">
  <icon />
</div>`
js
`props: ['icon']`

UserIcon.vue
html
`<i class="user-icon"></i>`

But I cannot load `<i class="user-icon"></i>` html.
Does any one pass component as prop to a component? I need help.

**Comment by LycheeHe** [comment]
**dropdown.vue**
**html**
`<div class="dropdown"><icon></icon></div>`

**Comment by posva** [comment]
You get access to a global component through `Vue.component('TheName')` or you could also directly pass the string asa a prop and let the child do the call

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by LycheeHe** [comment]
oh, I m sorry, i make a mistake , could you open this issue again?
I dont register UserIcon globally, I just register in **a.vue**
And I did what you ask.
main.js
`Vue.component('icon-user', UserIcon)`

and I pass this compponent as prop like: 
a.vue
`<dropdown :icon="'icon-play'"></dropdown>`
(I dont register on this vue)
and I use in dropdown like this:
dropdown.vue
html:
`<div class="dropdown"><icon></icon></div>`
js:
`prop: ['icon']`

and the browser reminds me <icon> is unknown custom element

**Comment by LycheeHe** [comment]
the browser reminds me icon is unknown custom element

**Comment by leopiccionia** [comment]
For dynamic binding a component, use `<component :is="icon"></component>` instead of `<icon></icon>`.

https://vuejs.org/v2/guide/components.html#Dynamic-Components
