### ISSUE TITLE
computed bug

### ISSUE THREAD

**Issue by CGQAQ** [vuejs/vue#10065]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-magic-computed-xv9qi](https://codesandbox.io/s/vue-magic-computed-xv9qi)

### Steps to reproduce
Just follow my comment [code](https://codesandbox.io/s/vue-magic-computed-xv9qi)

### What is expected?
works well

### What is actually happening?
won't work until I add a console.log to the computed method

**Comment by posva** [comment]
Didn't I answer a very similar issue recently with a function in a computed property? 🤔

You need to accès this value before the early return.

The actual problem here is that $refs are not reactive. There is already an open issue for that

**Comment by CGQAQ** [comment]
@posva but in the computed property,  I rely on "the this.value_" which is in data and definitely is reactive

**Comment by CGQAQ** [comment]
```js
computed: {
    thumbLeft: function() {
      // --------------------------------------------------
      // 注释和解除注释  试试拖动滑块的效果
      // 1. try to drag the slider then uncomment next line try again --->
      // console.log(this.value_);
      // well console.log random thing won't work as well
      // console.log('random thing');
      // --------------------------------------------------
      if (!this.$refs.wrapper) return "0px";
      return (
        (
this.value_  // <--------------- this is reactive  
/ (this.max_ - this.min_)) *
          this.$refs.wrapper.clientWidth +
        "px"
      );
    }
  },
```

**Comment by posva** [comment]
But it doesn't get executed in the first run because the ref is undefined

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by CGQAQ** [comment]
do you mean that if first time run fail(such as "if (!this.$refs.wrapper) return "0px";"), did't rely on reactive variable(s),  it won't run again!!!??????????????????????

**Comment by CGQAQ** [comment]
ok, I get it, thank you, sir

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/58248929-173ac180-7d90-11e9-8fa5-4a44fcf037eb.png)
![image](https://user-images.githubusercontent.com/15936231/58248947-21f55680-7d90-11e9-922b-9ddcd20564b5.png)
![image](https://user-images.githubusercontent.com/15936231/58248917-0be79600-7d90-11e9-9dad-3c8820c8d437.png)
@posva  but I change to this:  always relay on THREE REACTIVE VARIABLES, won't work as well

**Comment by CGQAQ** [comment]
I'm VERY SORRY TO BOTHER YOU, I appreciate you
