### ISSUE TITLE
Unable to set key for functional components

### ISSUE THREAD

**Issue by xg4** [vuejs/vue#10075]
### Version
2.6.10

### Steps to reproduce
- functional component

  HelloWorld.vue

  ```html
  <script>
    export default {
      functional: true,
      name: 'HelloWorld',
      render(h) {
        return h('div', 'hello world')
      }
    }
  </script>
  ```

- App component

  App.vue

  ```html
  <template>
    <div id="app">
      <transition-group>
        <HelloWorld v-for="item in 10" :key="item" />
      </transition-group>
    </div>
  </template>

  <script>
    import HelloWorld from './components/HelloWorld'
    export default {
      components: {
        HelloWorld
      }
    }
  </script>
  ```

### What is expected?
Unable to successfully render transition-group

### What is actually happening?
```
[Vue warn]: <transition-group> children must be keyed: <div>
```

**Comment by posva** [comment]
You need to pass down the key as shown in https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

**Comment by xg4** [comment]
@posva 
Thank you, I get it.
And I found the same issue #7777

**Comment by xg4** [comment]
@posva But I still have a question.
What to do if the functional components are provided by others.
Add wrapper?
