### ISSUE TITLE
Slot not available through $slots when providing props

### ISSUE THREAD

**Issue by ryandeba** [vuejs/vue#10079]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/z9wdpcjk/](https://jsfiddle.net/z9wdpcjk/)

### Steps to reproduce
See that the expected content is being displayed for each slot, and notice that $slots.b is not found.

### What is expected?
I would expect a slot to be available through $slots when props are passed to it.

### What is actually happening?
Slots are not available through $slots when props are passed to it.

---
This behavior seems to be the same when using the the old slot-scope syntax and the new v-slot syntax.

**Comment by jacekkarczmarczyk** [comment]
https://jsfiddle.net/x5sz81b2/

**Comment by ryandeba** [comment]
@jacekkarczmarczyk Thank you! I'm an idiot 😕
