### ISSUE TITLE
使用typescript eslint无法排除node_modules文件的错误

### ISSUE THREAD

**Issue by qtzheng** [vuejs/vue#10072]
### Version
2.6.10

### Reproduction link
[https://github.com/qtzheng/vue-demo.git](https://github.com/qtzheng/vue-demo.git)

### Steps to reproduce
1、使用cli创建项目。
2、添加pont-engine@0.2.1依赖,在main.ts中加入import {CodeGenerator} from 'pont-engine';
3、运行npm run build
4、编译失败，一堆的错误

### What is expected?
npm run build 能正常执行

### What is actually happening?
注：好像是tslint的校验不通过，但是又没法排除node_modules/pont-engine

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
