### ISSUE TITLE
:class binding doesn't work

### ISSUE THREAD

**Issue by angelsix** [vuejs/vue#10071]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/yjv1ohLk/](https://jsfiddle.net/yjv1ohLk/)

### Steps to reproduce
Click the 2 buttons in the JSFiddle and see it not working. Change script to point to older version (commented out in html) and works fine

### What is expected?
Text should change from red to black and from bold to regular (class list should change on button press)

### What is actually happening?
Class list is correct on first load but doesn't change with vue model changes

**Comment by vitaliy-k** [comment]
@angelsix https://vuejs.org/v2/api/#v-once

If you use the v-once directive, then your dom element is no longer dynamic for optimization. But you can use $refs and then implement something similar.

https://jsfiddle.net/mzpxg8ak/1/

**Comment by underfin** [comment]
remove `v-once` is ok.

**Comment by Justineo** [comment]
As @vitaliy-k said.
