### ISSUE TITLE
Render order [inconsistent compared to]/[not following] markup 

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#10070]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/y_nk/jwmu2oa0/](https://jsfiddle.net/y_nk/jwmu2oa0/)

### Steps to reproduce
1. open console for debug messages
2. type "1" in the input box => console displays : "render 1A" then "render 1B"
3. untick the first checkbox
4. tick back the first checkbox => console displays "render 1A"
5. type "2" in the input box => console displays : "render 12B" then "render 12A"

### What is expected?
order of render calls following markup

### What is actually happening?
order of rendered elements stacked according to history (?)
this is guessed bc if you tick/untick the 2nd checkbox after that, then the order is restored.

---
I understand this is probably normal behavior regarding current source code, but this is not natural/intuitive. I guess that most of people could follow the logic until step 4, but then the order should be restored in step 5.

**Comment by posva** [comment]
I think it makes sense as you toggled the element so it inserted afterwards. I don't think you should rely on order based on adjacency, only based on parent-child relationship

**Comment by y-nk** [comment]
@posva i found some (sketchy edge) cases where the rendering is actually not following the same logic. the codebase is significantly bigger, although it's the minimal reproduction case i can compute. if you don't mind having a look: https://jsfiddle.net/y_nk/8zdam9he/

**Comment by y-nk** [comment]
@posva as an additional comment, i fail to see why, when toggling "button 1" in this example https://jsfiddle.net/y_nk/8zdam9he/3/ the output will differ depending if components are encapsulated in an other or not.

**Comment by posva** [comment]
I appreciate that you put the time in boiling it down, but it's far too much for me to dive in and take a proper look
As I said, you shouldn't rely on order based on adjacency when it comes to rendering. The order only reflects in rendered HTML, not in order of operations

**Comment by y-nk** [comment]
@posva may i try to provide a more concise example ? https://jsfiddle.net/y_nk/bh5yapcw/
I've been trying to show that the latest added isn't always rendered. Indeed, the order is rather following the template, but what i can't explain is why the parts which shouldn't re-render actually do?

**Comment by y-nk** [comment]
@posva then what's the proper priorities for order of operations ?

**Comment by y-nk** [comment]
@posva then what are the priorities for order of operations ? Is it something fixed that I could rely on (because i actually need it 😅) ?

EDIT: I've been creating an example which illustrates what you said about order of operations being different than the markup order [here](https://jsfiddle.net/y_nk/bh5yapcw/1/). I keep wondering why it is this way, it doesn't make sense to me in that particular setup.

action | uids (ordered)
-------|---------------
Initial render | 2, 3, 5, 7
untick 2nd box | 2, 5
retick 2nd box | 8 (new), 2, 5, 9 (new)
untick 1st box | 8, 9
retick 1st box | 10 (new), 11 (new), 8, 9

You can notice that when you retick a box, depending on the markup, operation order differs. But how can we rely to build on something so unpredictable?

**Comment by LinusBorg** [comment]
The only "irregularity" seems to be that uid 8 renders before 2, even though 2 appears before 8, correct? Is that your issue?

It's because the component for uid 8 is a new component, and it's created during the diffing process after the main `Demo` component's render function has run. During creation, that new component renders for the first time as well.

After the diffing process, the render cycle for `Demo` has finished and now any child components that need to re-render do so.

* First, uid 2 re-renders. (because it received slot content that needs to be diffed against the component's current vdom)
* Then the first `Zone` re-renders (because it received slot content)
  * in that process, it in turn makes uid 5 re-render (because it received slot content)
* Then the second `Zone` re-renders
  * in that process, it creates a fresh `Test` component (uid 9) that renders

**Comment by y-nk** [comment]
@posva @LinusBorg thanks for taking the time to read and explain.

---

> The only "irregularity" seems to be that after ticking the second box again, uid 8 renders before 2, even though 2 appears before 8, correct? Is that your issue?

Indeed, i could understand instances are created before, but why render them at the same time rather than (roughly) iterate over all the children to render? I'm probably too rookie in Vue internals to understand why it's built this way.

> In short: new child components get created (and render) before existing child components re-render (if they have to)

In the table i created earlier, you can see : "8 (new), 2, 5, 9 (new)". If i understand what you say, uid 9 is created last because it's inside uid 8's slot, so it's "newly created first" within 8's render function because it's a slot and belongs to 8's ?

**Comment by LinusBorg** [comment]
> In the table i created earlier, you can see : "8 (new), 2, 5, 9 (new)". If i understand what you say, uid 9 is created last because it's inside uid 8's slot, so it's "newly created first" within 8's render function because it's a slot and belongs to 8's ?

Not entirely. 9 is not in 8's slot (which is second `Test` component, outside of any `Zone`).

It's in the second `Zone`'s slot (which doesn't have a uid). the second `Zone` component is the last child to update after `Demo` itself has re-rendered, and `Test` with uid 9 is only created during the second `Zone` component's update cycle.

**Comment by y-nk** [comment]
got it. thanks a lot ; this is fascinating :)
