### ISSUE TITLE
bug about keep-alive and @click.native caused repeated attach event handler?

### ISSUE THREAD

**Issue by action-hong** [vuejs/vue#10083]
### Version
2.6.10

### Reproduction link
[https://codepen.io/action-hong/pen/eaKmOy](https://codepen.io/action-hong/pen/eaKmOy)

### Steps to reproduce
1. click "show/hide button" to hide button "add 1"
2. click "show/hide button" to show button "add 1"
3. click "add 1"

### What is expected?
Repeat step 1 and step 2, Click the "add 1" to add 1 to the number

### What is actually happening?
Repeat step 1 and step 2 , Click the "add 1" to add n(repeat times) to the number

---
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by posva** [comment]
Seems like a bug indeed. As a workaround, you can pass a regular `@click` and handle it manually with `$listeners.click`

```vue
<button @click="$listeners.click">{{ text }}</button>
```

**Comment by super-Sun** [comment]
`<my-count text="add 1" @click.native="add" v-if="show"></my-count>`
Repeated execution of 'v-if' means repeating the 'add event' for <button>, using 'v-show' will not have this problem, or put 'add event' inside the subcomponent(my-count)

**Comment by populismeGitHub** [comment]
What?
