### ISSUE TITLE
slot="xxx" is still exist after functional parent render()

### ISSUE THREAD

**Issue by zhangshichun** [vuejs/vue#10084]
### Version
2.6.10

### Reproduction link
[https://github.com/zhangshichun/vue-bug-functional-slot](https://github.com/zhangshichun/vue-bug-functional-slot)

### Steps to reproduce
look at this codes.
outer.vue:
```
<template>
    <div>
        <slot></slot>
    </div>
</template>
```
test.vue:
```
<script>
export default {
    functional: true,
    render(createElement, context){
        const test_slot = context.scopedSlots['test_slot']()[0]
        return test_slot
    }
}
</script>
```
and Home.vue:
```
    <outer>
    <p>1、the name on 'template' tag
    </p>
    <test>
      <template slot="test_slot">
        <div>123</div>
      </template>
    </test>
    <p>2、the name on 'div' tag(should not '123' show)
    </p>
    <test>
      <div slot="test_slot">
        123
      </div>
    </test>
    </outer>
```

now,we can only see one '123' in page,because in the outer.vue , the div is still a Named Slots

### What is expected?
when functional render end, should the  slot name remove.

### What is actually happening?
 no

**Comment by posva** [comment]
Tried your repro and it is removed from the HTML as expected

**Comment by zhangshichun** [comment]
> Tried your repro and it is removed from the HTML as expected

I think it may be not expected。what I expecte is that it should not be removed;

because 
```
      <div slot="test_slot">
        123
      </div>
```
is just a slot of <test>,but now is both a slot of <test> and <outer>
