### ISSUE TITLE
Web Components with Functional child components throws "Cannot read property '$options' of undefined"

### ISSUE THREAD

**Issue by wpatter6** [vuejs/vue#10091]
### Version
2.6.10

### Reproduction link
[https://github.com/wpatter6/vue-wc-functional-bug](https://github.com/wpatter6/vue-wc-functional-bug)

### Steps to reproduce
1. Clone or fork repo at minimal reproduction link
2. Run `npm i` in console
3. Run `npm run build-wc` in console
4. Open `dist/demo.html` in browser

### What is expected?
Web component should render properly with no errors in browser console

### What is actually happening?
Component does not render, error message says 

```
[Vue warn]: Error in render: "TypeError: Cannot read property '$options' of undefined"

found in

---> <App> at src/App.vue
       <Root>
```

---
Here is the stack trace of the error in the console: 

```
TypeError: Cannot read property '$options' of undefined
    at FunctionalRenderContext.hook (v-app.js:704)
    at renderWithStyleInjection (v-app.js:716)
    at createFunctionalComponent (vue.js:3065)
    at createComponent (vue.js:3238)
    at _createElement (vue.js:3422)
    at createElement (vue.js:3360)
    at vm._c (vue.js:3491)
    at Proxy.render (v-app.js:735)
    at VueComponent.Vue._render (vue.js:3545)
    at VueComponent.updateComponent (vue.js:4061)
```

If I make the child component non-functional it will work properly.  Was really hoping to be able to use functional components to help improve performance of my web components.

Thanks in advance for any help!

**Comment by posva** [comment]
Functional components do not have a context (this) and therefore cannot access $options

**Comment by wpatter6** [comment]
I'm not accessing `$options` in my component -- see my repo.  The component works fine as a functional component when the app is not built as a web component.  Something in the WC back end is trying to access $options and throwing this error

**Comment by posva** [comment]
Ah right. This is not coming from vue but rather the cli and the service used to build a wc 
You should check in their repository

**Comment by wpatter6** [comment]
Ok thank you
