### ISSUE TITLE
Weird behavior of transition under a certain circumstance

### ISSUE THREAD

**Issue by simonmysun** [vuejs/vue#10090]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/simonmysun/4pta0x68/](https://jsfiddle.net/simonmysun/4pta0x68/)

### Steps to reproduce
There are three routes. Switching from A to B, the router links are animated.

### What is expected?
The router links should remain still. They are not in the transition tag. 

### What is actually happening?
The router links are animated in my browser. 

---
I have tried my best to minify the reproduction. Using other transition effects, removing the mounted hook or the focus operation, the bug doesn't show up. Switching between other route pairs also does not trigger the bug.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This seems to be a question about the CSS positioning and is not really related to Vue

**Comment by simonmysun** [comment]
Hi posva, it is related to CSS positioning indeed. But the elements outside the transition component shouldn't be applied with any transition effect. It's an extra effect with Vue.js which is not expected. 

I'll also post on StackOverFlow now.
