### ISSUE TITLE
该如何在render函数内，使用keep-alive？

### ISSUE THREAD

**Issue by AllenField** [vuejs/vue#10097]
### What problem does this feature solve?
我在创建一些组件，因为一些需求，这些组件都必须使用render函数来创建。

这些组件中有一个Tabpanel组件，Tabpanel内部有一个子页面集合，还有一个用于切换这些子页面的tabbar。

所有子页面都是懒实例化的，希望通过keep-alive来实现。

请问：该如何在render函数内，使用keep-alive？

### What does the proposed API look like?
```
render (h) {
  return h('div', [
    h('keep-alive', childPanels),
    h('div', tabbar)
  ])
}
```

**Comment by posva** [comment]
yeah, that's how you use keep-alive in a render function.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by AllenField** [comment]
But this does not work!

**Comment by AllenField** [comment]
@posva thank you, that's right, I did something wrong
