### ISSUE TITLE
setting property of object in data to false becomes undefined in Firefox 67

### ISSUE THREAD

**Issue by waspinator** [vuejs/vue#10106]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/waspinator/xqvfrtwL/2/](https://jsfiddle.net/waspinator/xqvfrtwL/2/)

### Steps to reproduce
assign false to a property of a data object in Firefox 67. 

### What is expected?
the property should be false

### What is actually happening?
the property becomes undefined 

---
it works as expected on Safari 12 and Chrome 74

**Comment by posva** [comment]
Tested on Firefox 67 and Nightly and the property is set to false

**Comment by waspinator** [comment]
Hmm, that's weird. I tried on a half dozen computers with macOS, ubuntu, and Windows with the same result. 

![Screen Shot 2019-06-05 at 07 54 28](https://user-images.githubusercontent.com/100416/58954672-d8c9dd00-8767-11e9-8750-7005675f833d.png)

**Comment by mxs42** [comment]
lol what???
How is this closed? I encountered the same issue, whenever I set data fields to something that casts to false, it becomes undefined.

**Comment by mxs42** [comment]
@posva care to explain that?
![image](https://user-images.githubusercontent.com/34000717/59553442-99886100-8f9d-11e9-864c-971f781bb35b.png)

**Comment by Justineo** [comment]
It looks like to be a problem of Firefox's devtools and unrelated to Vue. https://jsfiddle.net/09jzhm6o/

**Comment by waspinator** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1559717

**Comment by nchevobbe** [comment]
Hello, Firefox Console owner here. This is indeed a Firefox Console issue when evaluating a getter that returns `false`, `""` or `0`.
I'm working on a fix and will keep you updated. Thanks a lot for the report.

**Comment by nchevobbe** [comment]
Update: The bug is now fixed in Firefox 69 (Beta). Should be in release at the beginning of September
