### ISSUE TITLE
v-for绑定的key强制约束类型为string

### ISSUE THREAD

**Issue by minikey** [vuejs/vue#10109]
### What problem does this feature solve?
将key的值强制约束为string类型，可以更清晰明了

### What does the proposed API look like?
如果编译过程中发现key的类型不为字符串就抛出warning

**Comment by posva** [comment]
Yes, keys are constrained to literals. The warning is intended

**Comment by minikey** [comment]
这儿有一个特殊的值 NaN ，NaN !== NaN
