### ISSUE TITLE
Cannot pass slot object into a component

### ISSUE THREAD

**Issue by eakarpov** [vuejs/vue#10111]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-qwq83](https://codesandbox.io/embed/vue-template-qwq83)

### Steps to reproduce
Create a component, pass children via slots property.

### What is expected?
this.$slots property contains the passed children inside the component

### What is actually happening?
Passing via prop interface leads to empty object in this.$slots

---
Trying to use render function to pass blocks of template inside a component.

**Comment by posva** [comment]
That never worked
There was something similar dropped in the past https://github.com/vuejs/vue/pull/7765

**Comment by eakarpov** [comment]
@posva And how can I pass slot content into the component from somewhere outside? (Dynamically add slot content)

**Comment by Justineo** [comment]
@eakarpov You can use a render function where you can programmatically specify slot content.

**Comment by eakarpov** [comment]
@Justineo Please could you describe API for specifying this programmatically?

**Comment by Justineo** [comment]
https://codesandbox.io/s/vue-template-8744b

**Comment by eakarpov** [comment]
@Justineo Thanks! Is not $scopedSlots deprecated in vue 2.6 with slot/slot-scope?

**Comment by Justineo** [comment]
No it's not. We'll deprecate it in v3.

**Comment by eakarpov** [comment]
@Justineo Ok thanks. Will vue v3 be able to manage slots programmatically?
