### ISSUE TITLE
作用域插槽在mounted阶段, 在$slots上是不存在的, 如果不传值就没问题

### ISSUE THREAD

**Issue by 383514580** [vuejs/vue#10114]
### Version
2.6.10

### Reproduction link
[https://codepen.io/russell2015/pen/qGzjeY](https://codepen.io/russell2015/pen/qGzjeY)

### Steps to reproduce
看例子的第二个Com组件并没有渲染内容 , 因为当前$slot上并没有该插槽

### What is expected?
期待第二个Com组件渲染

### What is actually happening?
未知

**Comment by posva** [comment]
You have to look in `$scopedSlots`: `<h1 v-if="$scopedSlots.header">`
