### ISSUE TITLE
when a <transition> tag be used inside a component, the “v-enter-active” directive( or the "enter-active-class" attr ) can not work

### ISSUE THREAD

**Issue by yamybl** [vuejs/vue#10129]
### Version
2.6.10

### Reproduction link
[https://codepen.io/yamybl/project/editor/AjVMVR](https://codepen.io/yamybl/project/editor/AjVMVR)

### Steps to reproduce
click the "Welcome" anchor, and then click the "Test" anchor will see the issue.

### What is expected?
the "v-enter-active" directive will work correctly

### What is actually happening?
but it work incorrectly

**Comment by posva** [comment]
It works fine: the view transitions with a fade effect: https://jsfiddle.net/es130dga/
If you want it on appear, add the appear prop to transition. Also please always provide editable repros
