### ISSUE TITLE
v-model modifiers not implemented for components

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#10122]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/y_nk/Lnk709z5/3/](https://jsfiddle.net/y_nk/Lnk709z5/3/)

### Steps to reproduce
1. create a component (custom-input) implementing the basic v-model mechanism ( value prop, input event )
2. add support for change event
3. add .lazy modifier on the v-model directive

### What is expected?
value bound in v-model should update on change event due to the lazy modifier

### What is actually happening?
value is updated on input regardless of the lazy modifiers

---
it would be very useful to fix it to give opportunity to implement a _throttled-like_ alternative to @input

if `wont fix`, as for now documentation doesn't mention that it's limited to natural dom elements :
- https://vuejs.org/v2/guide/forms.html#Modifiers
- https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

**Comment by posva** [comment]
Please see https://github.com/vuejs/vue/issues/6914 and https://github.com/vuejs/vue/issues/7136

**Comment by y-nk** [comment]
@posva thanks for your quick answer. any progress on the PR ? it seems ready to merge for a while...

**Comment by wc-matteo** [comment]
@posva It would be awesome if this could be merged!
