### ISSUE TITLE
Is it possible to recycle elements in VNodes?

### ISSUE THREAD

**Issue by DominusVilicus** [vuejs/vue#10123]
### What problem does this feature solve?
Is it possible to render vnodes from existing document elements/nodes

eg:
```js
h(node)

vnode.elm = node
```

**Problem/Use Case**
Trying to build a contenteditable, which needs to recycle elements so that the selection API can work correctly (rerenders cause the cursor to reset at the beginning, because elements are rerendered, and the references are lost)

### What does the proposed API look like?
```js
h(node)
//or
vnode.elm = node
```

**Comment by DominusVilicus** [comment]
This is an issue because making the `contenteditable` reactive results in cursor issues when editing because the elements are not being recycled, and the `window.getSelection`/`selection API` break (they need references to the anchornodes

**Comment by posva** [comment]
The vnode should be treated as read only.

There is no need to go that complicated as to modify the vnode.elm, create a wrapper component that handles the events of the content editable. A google search yields many results, one of these is https://codepen.io/supraniti/pen/Lypobx?editors=1010

Closing as this is a question and it should go in the forum

**Comment by DominusVilicus** [comment]
I'd like to make a few points:
When a contenteditable recreates changes, it loses the css scoped data attribute, which prevents scoped css from being applied to any content in the contentediable.

I will be doing more research into this however, and figuring out a solution to the cursor change

It would be great if vue was able to directly recycle elements in the VNode, to avoid cursor issues with losing references to elements on rerender

**Comment by LinusBorg** [comment]
I'm nosure I understand the issue in absense of a demo.

Vnodes are re-recreated on each render, but the *HTML Elements* that they *reference* are re-used - whenever possible.

You seem to experience that the HTML Elements inside a `contenteditable` element are *not* re-used by re-created.

If that's what this issue is about, then consider opening a bug report about it with whatever you find while investigating further.
