### ISSUE TITLE
entities in attribute are unexpectedly encoded

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#10121]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/x725dcbu/2/](https://jsfiddle.net/x725dcbu/2/)

### What is expected?
html & template have the same behavior

### What is actually happening?
normal markup:
`<input value="&#102;&#111;&#111;">` gives `foo`

vue template
`<input value="&#102;&#111;&#111;">` gives `&#102;&#111;&#111;`

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/8805
