### ISSUE TITLE
[DOCS ]v-if v-else directive using keys clears input data after toggling in docs example

### ISSUE THREAD

**Issue by ahtee** [vuejs/vue#10128]
### Version
2.6.10

### Reproduction link
[https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key](https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key)

### Steps to reproduce
go to the second example with v-if v-else directive in the link using keys. enter some text, toggle, enter an email and toggle again. the username is gone.

### What is expected?
toggling may need to return each value

### What is actually happening?
the data in cleared and would  need to re-enter the username or email

**Comment by posva** [comment]
That part is exactly showing what is expected with a `key` attribute. BTW, docs repo are at vuejs/vuejs.org

**Comment by ahtee** [comment]
thanks @posva with more thought it made sense that this would happen as it is two different inputs but wasn't sure if the data entered should have stayed in each input. Just wanted to ask
