### ISSUE TITLE
TodoMVC Example: Proposal to revise code for filter links

### ISSUE THREAD

**Issue by FumioNonaka** [vuejs/vue#10124]
### Version
2.6.10

### Reproduction link
[Vue.js: TodoMVC revised](https://jsfiddle.net/FumioNonaka/38uvnawh/28/)

### Reason
For creating filter links you should type the same text three times, the method names, the conditions for class bindings and link names.

### Proposed code
```
<footer class="footer" v-show="todos.length" v-cloak>

    <ul class="filters">
      <li><a
        v-for="(value, name) in filters"
        :href="'#/' + name"
        :class="{selected: visibility === name}"
        >
        {{ name.charAt(0).toUpperCase()   name.substr(1) }}
      </a></li>
    </ul>

</footer>

var app = new Vue({
  // app initial state
  data: {

    filters
  },

}
```

### Current code
```
<footer class="footer" v-show="todos.length" v-cloak>

    <ul class="filters">
        <li><a href="#/all" :class="{ selected: visibility == 'all' }">All</a></li>
        <li><a href="#/active" :class="{ selected: visibility == 'active' }">Active</a></li>
        <li><a href="#/completed" :class="{ selected: visibility == 'completed' }">Completed</a></li>
    </ul>

</footer>
```

**Comment by posva** [comment]
Hey, thanks for the proposal. The TodoMVC is good to learn and adding another for loop for only 3 items when there is no need for generalization makes the code harder to understand.
The current code is easier to grasp and there is already a `v-for` for the loops, so let's keep it that way, it's cleaner and better for a learning resource
