### ISSUE TITLE
[with UMD reference] v-slot cannot use the named slot in component which name used camelcase to define  

### ISSUE THREAD

**Issue by nkdanfer** [vuejs/vue#10120]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/LowxXz?editors=1111](https://codepen.io/anon/pen/LowxXz?editors=1111)

### Steps to reproduce
1.define a component with two slot
Vue.component('top-bar', {
    template: `<div class="container">
    <div class="row bod-bottom-lighter h50 pt10">
        <div class="col-xs-2" onclick="javascript:window.history.back();">
            <slot name="canwork">left-for-back</slot>
        </div>
        <div class="col-xs-8 pl80">
            <span class="font-10pt"><slot></slot></span>
        </div>
        <div class="col-xs-2">
            <slot name="rightAction"></slot>
        </div>
    </div>
</div>`,
  mounted:function(){
     console.log('top-bar mounted');
  },
  updated:function(){
     console.log('top-bar updated');
  },actived:function(){
     console.log('top-bar actived');
  },
});
2.use template in parent
<top-bar>
        <template v-slot:canwork>
          this slot can work
        </template>
        center title
        <template v-slot:rightAction>
          camelCase slot do NOT work
        </template>
        <template v-slot:right-action>
          camelCase slot do NOT work
        </template>
     </top-bar>

### What is expected?
camelcase slot 'rightAction' can properly work

### What is actually happening?
camelcase slot 'rightAction' can not work,
lowercased named slot 'canwork' works.

**Comment by posva** [comment]
This is an HTML limitation that converts everything to lower case before Vue gets to read it
