### ISSUE TITLE
v-cloak directive to "replace" attribute instead of removing it

### ISSUE THREAD

**Issue by savehansson** [vuejs/vue#10131]
### What problem does this feature solve?
If you want to write CSS that comes in effect when the `v-cloak` attribute *disappears*, i.e. a transition, there's no easy way to do that because... well, there's no way to select the elements that *had* the attribute before. Would be much easier if the attribute was *replaced* with another attribute instead of just removed.

### What does the proposed API look like?
Additionally to removing the `v-cloak` attribute:
Add a new "special" attribute `v-cloak-removed` (named as you like, but for text search reasons I suggest `v-cloak-something`).

**Comment by posva** [comment]
Write your own directive that adds an attribute on inserted
