### ISSUE TITLE
Strange behavior vue’s transition tag with v-show in google chrome when element is hidden on start

### ISSUE THREAD

**Issue by tempfirstuser** [vuejs/vue#10134]
### Version
2.6.10

### Reproduction link
https://jsfiddle.net/7c94vmqt/8/ (It looks like I can not reproduce a bug on the fiddle.net because my real code is more complicated. I use vuex for communication between components.)

### Steps to reproduce
I have created forum topic earlier here https://forum.vuejs.org/t/strange-behavior-vues-transition-tag-with-v-show-in-google-chrome-when-element-is-hidden-on-start/65772 . 

### What is expected?
I expected appropriate behavior of the transition tag work as in the firefox. 

Is this a bug of the vue or the google chrome?

### What is actually happening?
When I click first time after refreshing the page on the "toggle" button in the google chrome in most cases hidden div tag will be appear immediately or will be shaken to the edge and back again to the start position. It depends of the duration of the transition. Some time it works few several times in a row but then it works with a bug.

---
Also I use vuex for stateSidebarLeft variable. When I replace v-show to v-if it looks like works in google chrome as expected.

**Comment by tempfirstuser** [comment]
I don't understand what is going on with my code, vue and google chrome. It start working normal at current moment. What can be the reason of such behavior? Maybe cache or something similar?

**Comment by tempfirstuser** [comment]
Transition is broken again. I have just resized the window of  "mobile" mode and div tag begin appear without transition or became "shaky" when slide from the left side to the right.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by tempfirstuser** [comment]
Hi! I asked question here because I thought that this was a vue bug. Thank you for answering.

**Comment by tempfirstuser** [comment]
It looks like that strange behavior begin only when opened developers panel in google chrome and transitioned div is selected in DOM-tree in panel "Elements". If I deselect transitioning div (I mean, if i click on another node of the DOM-tree or even close developers panel) transition will go smoothly as in the firefox and as I expected. I have write this here because of someone else can be confused of such "bug".
