### ISSUE TITLE
renderState() not work when used with nuxt

### ISSUE THREAD

**Issue by maunier** [vuejs/vue#10135]
### Version
2.6.10

### Reproduction link
[https://github.com/maunier/nuxt-learning.git](https://github.com/maunier/nuxt-learning.git)

### Steps to reproduce
1. npm install
2. npm run dev
3. check the source code of the page, you can find that there is no state

### What is expected?
when i use renderState() in my custom template, i wish the state is injected to the template

### What is actually happening?
there is no state info in the html

the code in `vue-server-renderer/build.dev.js` :
```

TemplateRenderer.prototype.renderState = function renderState (context, options) {
  console.log('state:', context.state); // undefined
  console.log('nuxt.state:', context.nuxt.state); // is ok
  var ref = options || {};
    var contextKey = ref.contextKey; if ( contextKey === void 0 ) contextKey = 'state';
    var windowKey = ref.windowKey; if ( windowKey === void 0 ) windowKey = '__INITIAL_STATE__';
  var state = this.serialize(context[contextKey]);
  var autoRemove = '';
  var nonceAttr = context.nonce ? (" nonce=\"" + (context.nonce) + "\"") : '';
  return context[contextKey]
    ? ("<script" + nonceAttr + ">window." + windowKey + "=" + state + autoRemove + "</script>")
    : ''
};
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

On a side note this doesn't seem to be directly related to Vue
