### ISSUE TITLE
Watch doesn't trigger on every $set

### ISSUE THREAD

**Issue by Kunoacc** [vuejs/vue#10143]
### Version
2.6.10

### Reproduction link
[https://codepen.io/kunoacc/pen/ZdGbEa](https://codepen.io/kunoacc/pen/ZdGbEa)

### Steps to reproduce
click any number then click an operator consecutively, twice. 

the code below runs
```javascript
this.updateOperation(operation)
 this.current = ''
 operation.push(val)
 this.updateOperation(operation)

updateOperation(newOperation){
   this.$set(this.$data,'operation', newOperation)
}
```

### What is expected?
The watcher set is supposed to be triggered on both operation updates

### What is actually happening?
The watcher is triggered only after the second operation update

---
Trying to implement some calculation logic and i needed to get the individual changes to be able to run calculations and process the results as the user types

**Comment by posva** [comment]
Check the immediate option in docs
Vue throttles updates to prevent unnecessary watchers triggers
