### ISSUE TITLE
Using v-on/v-bind for transparent component decrease the runtime performance

### ISSUE THREAD

**Issue by chenxeed** [vuejs/vue#10144]
### Version
2.6.10

### Reproduction link
[https://www.chenxeed.com/labs/transparent-wrapper-component](https://www.chenxeed.com/labs/transparent-wrapper-component)

### Steps to reproduce
1. Open the reproduction link and go to the bottom section that showcases the performance concern.

2. Click the radio button [Main] to showcase the performance of rendering [the main component](https://github.com/chenxeed/chenxeed/blob/master/src/views/Labs/TransparentWrapperComponent/component-main.vue). Try to scroll as fast as you can and inspect the runtime generated and see the average numbers. Screenshot: <img src="https://gyazo.com/0d2b9326bba0413e1acaab87966d3904.gif">

3. Click the radio button [Transparent (v-on & v-bind)] to showcase the performance of rendering [the transparent component with v-on/v-bind](https://github.com/chenxeed/chenxeed/blob/master/src/views/Labs/TransparentWrapperComponent/component-transparent.vue) to bypass the props and events of the parent. Try to scroll as fast as you can and inspect the runtime generated and see the average numbers. Screenshot:<img src="https://gyazo.com/868a65462147fd90c35a1d90f900af19.gif">

4. Click the radio button [Transparent (manual)] to showcase the performance of rendering the [transparent component with manual bypass props and events of the parent](https://github.com/chenxeed/chenxeed/blob/master/src/views/Labs/TransparentWrapperComponent/component-transparent-manual.vue). Try to scroll as fast as you can and inspect the runtime generated and see the average numbers. Screenshot: <img src="https://gyazo.com/f54a66b9d88d5c80a29f88e27cafe0e3.gif">

### What is expected?
Using transparent component with `v-on/v-bind` should not decrease the runtime performance.

### What is actually happening?
Using transparent component with `v-on/v-bind` does decrease the runtime performance.

---
I found out this issue of performance regression on my current application where I use `v-on/v-bind` to bypass the props from the parent to the child component directly. After some debugging process, I found out that using `v-on/v-bind` is the cause which is unexpected.

It was very convenient to use `v-on/v-bind` to bypass the parent props/events directly to the child as a transparent component, so I suppose the performance should not be decreased because of this.

*note: The app I used are already using Vue 2.6.10, while the reproduction app I showed above is using Vue 2.5*

**Comment by posva** [comment]
A wrapper comes with a cost, it's normal, you cannot expect it to be the same as not using it
BTW The link you  shared  is a website not an editable boiled down repro. If you have a boiled down repro showing the performance regression, open a new issue

**Comment by chenxeed** [comment]
Thanks for the feedback @posva .

> A wrapper comes with a cost, it's normal, you cannot expect it to be the same as not using it

Yes, I believe it makes sense if there's a performance difference between wrapper and non-wrapper.

However, the concern I see is that why is there a performance difference on the wrapper that's using `v-on / v-bind` (showcase number 3) versus manual props/event bypassing (showcase number 4).

My main concern is that, does `v-on / v-bind` for transparent component also expected to cost performance compared to manual props/emit event?
