### ISSUE TITLE
use scoped slot variable but warn "Property or method 'res.data.a.b' is not defined on the instance but referenced during render."

### ISSUE THREAD

**Issue by xialvjun** [vuejs/vue#10141]
### Version
2.6.10

### Reproduction link
[https://codepen.io/xialvjun/pen/PrwLNN](https://codepen.io/xialvjun/pen/PrwLNN)

### Steps to reproduce
https://codepen.io/xialvjun/pen/PrwLNN
click `exec` and see the console...
then remove line 86, and try again

### What is expected?
there is no warning

### What is actually happening?
warn "Property or method 'res.data.a.b' is not defined on the instance but referenced during render."

**Comment by posva** [comment]
Use `get(api.res, 'data.a.b')` instead, it makes more sense as the property you want to access is in `api.res`. I wouldn't recommend passing `this` to `$scopedSlots.default()`, pass what you need, it can be `this.$data` if you want to pass all data but do not pass the whole instance
