### ISSUE TITLE
Vue Single Component Loading Openlayers and Cessium Causes Memory Growth and Memory Leakage

### ISSUE THREAD

**Issue by a24576946** [vuejs/vue#10146]
### Version
2.5.22

### Reproduction link
[https://github.com/vuejs/vue/issues/10145](https://github.com/vuejs/vue/issues/10145)

### Steps to reproduce
In my project, I need to use Openlayers and Cessium to load a large amount of vector data and model data. In the single page component of vue, memory will increase continuously, and memory can not be released. I'm using keep-alive to keep the state of the component from being reloaded. I don't know why this memory growth is? Is it due to the closure environment of the Vue single component?

### What is expected?
How to Solve this Memory Leakage Problem

### What is actually happening?
How to Solve this Memory Leakage Problem

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I'm sorry this isn't a qualified bug report (without executable reproduction we can't do much about it).
