### ISSUE TITLE
Doesn't render next components if the previous self-terminates

### ISSUE THREAD

**Issue by leeandher** [vuejs/vue#10147]
### Version
2.6.10

### Reproduction link
[https://github.com/leeandher/Learning-Vue/tree/master/Vallery](https://github.com/leeandher/Learning-Vue/tree/master/Vallery)

### Steps to reproduce
Just try to render the application with all the custom components.

---

In `app.vue`, I have the following template code:
```
<div class="app-wrapper">
    <Header></Header>
    <Panel></Panel>
    <Showcase/>
    <Modal/>
    <Footer/>
  </div>
```
I was just trying to mock-up an app I'm building, so the parts aren't nested and don't contain anything meaningful.

Each of those Vue Components contains the following in their `.vue`:

```
<template>
  <div class="panel-wrapper">Panel</div>
</template>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  name: "Panel"
});
</script>


<style lang="scss">
.panel-wrapper {
  background: orange;
  font-size: 1.75rem;
}
</style>
```
and this is the same for `Header`, `Showcase`, `Modal` and `Footer`.

For some odd reason, with the above code, only the Header, Panel, and Showcase components render.

If I change `<Showcase/>` to `<Showcase></Showcase>` then the Modal also renders.

Shouldn't it render regardless of whether or not the component self terminates its JSX?

### What is expected?
All the components should render regardless of whether or not they self-terminate

### What is actually happening?
Components which DON'T self-terminate do render: `<Example></Example>` but any components after ones that DO self-terminate don't render: 
```
...
<Example1></Example1> <!--renders-->
<Example2/> <!--renders-->
<Example3/> <!--does not render-->
<Example4></Example4> <!--does not render-->
...
```

---
I tried to setup the project from scratch, with TS and Parcel so I might've missed something. I'm relatively new to Vue, so any help/tips would be awesome.

I x-posted to SO as well: https://stackoverflow.com/questions/56572975/vue-doesnt-render-second-component-if-the-previous-self-terminates

**Comment by posva** [comment]
Please, provide boiled down repros when reporting a bug (no typescript, no other libraries and minimal code to showcase the problem). What you posted looks more like a stackoverflow or forum question
