### ISSUE TITLE
can v-model bind dynamic key？

### ISSUE THREAD

**Issue by lameone1** [vuejs/vue#10150]
### What problem does this feature solve?
<el-input  v-if="col.valueType=='input'" :disabled="gpt.authFlag=='VIEW'" v-model="`formp.${col.type}`">
<template slot="append">{{col.valueUnit}}</template>
 </el-input>
data:function(){
col:{
   type:'open',
  valueUnit:'元'
}，
formp:{
 open:“”，
}
}

### What does the proposed API look like?
<el-input  v-if="col.valueType=='input'" :disabled="gpt.authFlag=='VIEW'" v-model="`formp.${col.type}`">
                   <template slot="append">{{col.valueUnit}}</template>
 </el-input>
data:function(){
col:{
   type:'open',
  valueUnit:'元'
}，
formp:{
 open:“”，
}
}

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Your question is unclear but maybe you are looking for `v-model="form[field]"
