### ISSUE TITLE
Vue Truthiness/Falsiness with v-bind:checked

### ISSUE THREAD

**Issue by starkovsky** [vuejs/vue#10159]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/starkovsky/27h8wg5n/2/](https://jsfiddle.net/starkovsky/27h8wg5n/2/)

### Steps to reproduce
1. Run example in jsfiddle

### What is expected?
`<input type="checkbox" v-bind:checked="''" />` it should be true

### What is actually happening?
`<input type="checkbox" v-bind:checked="''" />` rendered false

---

`<input type="checkbox" v-bind:disabled="''" />` rendered right, as true

**Comment by posva** [comment]
This is just how the attribute checked works, try it by yourself in the console by setting the `checked` property of the element to an empty string, it will uncheck the checkbox

**Comment by starkovsky** [comment]
When used with `v-bind`, the only falsy values are `null`, `undefined`, and `false`. This means `0` and empty strings will be rendered as truthy. For example, `v-bind:draggable="''"` will become `draggable="true"`.

From Migration guide https://vuejs.org/v2/guide/migration.html#Truthiness-Falsiness-with-v-bind-changed
