### ISSUE TITLE
Unexpected behaviour of v-else element after v-for with v-if

### ISSUE THREAD

**Issue by schtr4jh** [vuejs/vue#10156]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-i8oh4](https://codesandbox.io/embed/vue-template-i8oh4)

### Steps to reproduce
Switch between enabled and disabled for loop.

### What is expected?
Expected output when for loop is disabled is "One".

### What is actually happening?
Instead it's "OneOne".

---
When combining v-for and v-if on same element it's expected to encounter some issues since it's not clear at which point vue should execute if-statement (before or in loop) - and solution is in most cases simple by using a wrapper (which is probably also a correct approach).
However, it's really not expected to multiply or execute loop on element after.

**Comment by posva** [comment]
It's is clear what happens when combining them, there is even a point for it in the docs: https://vuejs.org/v2/guide/conditional.html#v-if-with-v-for

the v-else appears twice because there are two elements in the iteration. This is working as expected
