### ISSUE TITLE
Attribute inherited from sibling in a v-if/v-else structure

### ISSUE THREAD

**Issue by Llbe** [vuejs/vue#10155]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/YoygXR](https://codepen.io/anon/pen/YoygXR)

### Steps to reproduce
1. Keep the mouse out of the result iframe of Codepen. Initially "false" is printed and the `<progress>` is empty

2. Trigger mousemove on the result iframe. The text is changed to "true" since progress now is === null and the `<progress>` is still empty

### What is expected?
Since progress is === null (verified by the text) the `<progress>` should be rendered without a value attribute, i.e. in an indeterminate state. This is expected because the v-if `<progress>` doesn't have a value attribute in the template.

### What is actually happening?
The `<progress>` rendered when progress === null has a value attribute set. I assume this is inherited from the v-else `<progress>`.

---
Tested in Chrome ~74. Please ask any questions and I'll provide further details.

**Comment by Llbe** [comment]
I believe this might be related to 2.4.3.

With Vue 2.4.3 it doesn't work: https://codepen.io/anon/pen/zVvbWj

WIth Vue 2.4.2 it works as expected: https://codepen.io/anon/pen/dBYrer

**Comment by Justineo** [comment]
You need to use `key` to let Vue stop reusing the same element in this case. See the [docs](https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key).

If you do want to let Vue reuse the same element, just not put the logic in if/else branches, instead you should bind reactive values with `v-bind`.

**Comment by Llbe** [comment]
@Justineo: I still think there may be a issue here.

Please see this variation with a single element and `undefined` instead of null:

Works with 2.4.2: https://codepen.io/anon/pen/VJvRVJ

Doesn't work with 2.4.3: https://codepen.io/anon/pen/xowBMm

Doesn't work with 2.6.10: https://codepen.io/anon/pen/xowBMm

**Comment by Llbe** [comment]
Correct link to 2.4.3: https://codepen.io/anon/pen/MMaxRQ

It's also relevant that the behaviour changed between these versions. What caused that change?

**Comment by Justineo** [comment]
I believe it's due to https://github.com/vuejs/vue/commit/7116af4e07520040ed7328c39d0a456808bfe1e1

You can see the difference here: https://jsbin.com/zecezop/1/edit?html,js,output

**Comment by Llbe** [comment]
@Justineo: I'm not sure I follow.

Shouldn't this be considered a bug? Please see the new example here: https://codepen.io/anon/pen/pXjBQq

There are two `<progress>`

 1. The first has `:value="progress"` where progress === undefined

 2. The second has `:value="undefined"`

They are rendered differently, which seems counterintuitive.

**Comment by Justineo** [comment]
I agree. Could you please open a new issue with the minimal repro you just found? It’s already quite different from the original issue.
