### ISSUE TITLE
how to trigger svg marker events

### ISSUE THREAD

**Issue by umi-soft** [vuejs/vue#10160]
### Version
2.5.21

### Reproduction link
[https://codepen.io/umi-soft/pen/dBMVgR](https://codepen.io/umi-soft/pen/dBMVgR)

### Steps to reproduce
i can click element link, but how to trigger events on marker element  

### What is expected?
trigger events on marker

### What is actually happening?
can not trigger events on marker

**Comment by posva** [comment]
Not sure what isn't working as the click event works. It's refX with a capital X
