### ISSUE TITLE
.well-known folder not working correctly in GitHub-pages

### ISSUE THREAD

**Issue by Umar-M-Haroon** [vuejs/vue#10163]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-4wm30?fontsize=14](https://codesandbox.io/s/vue-template-4wm30?fontsize=14)

### Steps to reproduce
create a vue project
add a .well-known folder in public, src/assets/ or the root directory. 
Add a file in the .well-known folder
Build and confirm .well-known folder exists in dist/
push to GitHub pages
general site will work, but site/.well-known/file won't work and will 404

### What is expected?
The file will be shown

### What is actually happening?
no file is shown and a 404 is presented.

---
I'm trying to add sign in with apple support and they want to add a apple-developer=domain-association.txt file in the .well-known directory, but that isnt working with vue on github no matter where I place the .well-known folder.

**Comment by LinusBorg** [comment]
> Build and confirm .well-known folder exists in dist/
> push to GitHub pages
> general site will work, but site/.well-known/file won't work and will 404

So this is not related to Vue CLI, it's related to Github  Pages.

**Comment by Umar-M-Haroon** [comment]
Hi,

Yeah once I went to the vue issue creator I set it to vue as I thought it would be an issue with vue and the assets. It definitely isn’t a CLI problem, so sorry if I still selected that by mistake

**Comment by Umar-M-Haroon** [comment]
The GitHub contact us page recommended me to post an issue to this repo.

**Comment by Justineo** [comment]
It's definitely not related to Vue. You want site/.well-known/file to be accessible, you need to put the folder in the root directory of your site.

**Comment by Umar-M-Haroon** [comment]
Right, and I tried putting the folder in src/assets and public/ and when I run it locally it runs fine, but for some reason on the push to GitHub gh-pages it doesn't work. So I'm not sure if its a build issue.

**Comment by Justineo** [comment]
> Build and confirm .well-known folder exists in dist/

Apparently, you are not putting it in the root directory...

**Comment by Umar-M-Haroon** [comment]
It exists in my dist/ folder and its in the root directory as well. Not sure what I'm doing wrong here. I've tried changing the output path to docs/ as well so GitHub Pages uses the Master/docs method but the issue persisted. Confirmed it exists in docs/ as well.

**Comment by Justineo** [comment]
Anyway, it’s not related to Vue at all.

**Comment by Umar-M-Haroon** [comment]
I ended up fixing it by adding an empty .nojekyll file in the public path directory
