### ISSUE TITLE
vue如何支持虚拟目录？

### ISSUE THREAD

**Issue by 120011676** [vuejs/vue#10166]
### What problem does this feature solve?
如一个工程已经部署了，访问地址是http://www.a.com
现在有另一个项目做了nginx反向代理，访问路径是http://www.b.com/a
2个需要同时使用，如何才能2个能正常访问

### What does the proposed API look like?
正常部署http://www.a.com访问正确    且   另一个nginx反向代理http://www.b.com/a也正确

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。

**Comment by 120011676** [comment]
@Justineo 好像vue没有这个特性
