### ISSUE TITLE
export error and warn in Vue

### ISSUE THREAD

**Issue by Suven** [vuejs/vue#10162]
### What problem does this feature solve?
I would like to use the same methodoligy as vue, for custom error-messages: show them in dev, hide them on prod (except if there is a error-handler in place).

For that it would be useful if I could just use vues built-in warn-function instead of duplicating that logic.

### What does the proposed API look like?
import Vue from 'vue'

Vue.warn('My message')

**Comment by posva** [comment]
There is Vue.util.warn for that but creating your own helpers and activate them through an env variable like vue does seems like the right approach
