### ISSUE TITLE
vuejs：v-for director may result a duplicate key error  on native element iterator

### ISSUE THREAD

**Issue by a7270102** [vuejs/vue#10164]
### Version
2.6.7

### Reproduction link
[https://codepen.io/a7270102/pen/LKZMYm](https://codepen.io/a7270102/pen/LKZMYm)

### Steps to reproduce
直接运行就可以重现：
实验步骤：
1. 使用两个数组对象来渲染两个同层次的原生div元素，Key分别设置为v-for的index
2. 运行后，F12可以看到异常提示：duplicate keys detected

### What is expected?
不应该报错提示：
vue自身会对每一个vueComponent给一个唯一标识，该标识的应用可以在遍历时，区分不同的组件实例，同时对其defaultScopes下的children遍历的key值起到一个命名空间的作用

### What is actually happening?
无法在遍历时将相同tagName的原生dom元素当作不同的实例对待，造成key校验不通过，从而提示异常

**Comment by Justineo** [comment]
这不是一个 bug。`key` 并不只是给 `v-for` 用的，而是在同层级节点识别唯一节点的通用机制。不同的 `v-for` 输出的节点 Vue 也可以进行复用。

请不要用 `index` 直接作为 `key`，可以给一个前缀来进行区分。
