### ISSUE TITLE
Computed property is not watching changes on this.$scopedSlots.default

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue#10179]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-bwtfk?fontsize=14](https://codesandbox.io/s/vue-template-bwtfk?fontsize=14)

### Steps to reproduce
Please see the reproduction in codesandbox.

### What is expected?
The content should become visible, as soon as the data is changed.

### What is actually happening?
It is still not rendered.

**Comment by sqal** [comment]
You don't see any changes because `name` is not defined upfront in `partnerDetails2` object. That's common reactivity caveat, please read https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by plehnen** [comment]
No, it's the same if I do it by `this.$set(this.partnerDetails2, "name", "Hello2");`.

The `name` is not the problem. If I remove the wrapper, everything works. The problem seems to be, that `this.$scopedSlots.default` is changed but the change not noticed by the computed property.

But that is what I need to do: The wrapper (including the list headline) should not be visible, if no list entry is visible (e.g. no slot content available). That is working, but not updating as soon as the slot content is eventually available.

**Comment by sqal** [comment]
Missing name in still an issue here, but the second problem is your  `isVisible` computed property

```js
isVisible() {
  return !this.optional || this.$scopedSlots.default;
}
```

$scopedSlots/$slots are not reactive (never , so this value will re-evaluate only when the value of  `optional` changes and in your case and in your case it never changes and it's always `false`

Fixed example - https://codesandbox.io/s/vue-template-w7enx?fontsize=14

**Comment by posva** [comment]
`$scopedSlots` is not reactive, so you should use a method instead or directly reference it in the template
