### ISSUE TITLE
Form Input Bindings and v-for error

### ISSUE THREAD

**Issue by xiaohunsdt** [vuejs/vue#10173]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/xiaohunsdt/7rw89bjp/6/](https://jsfiddle.net/xiaohunsdt/7rw89bjp/6/)

### Steps to reproduce
I used vue-cli to create a brand new project. and the dependencies is 
"dependencies": {
    "core-js": "^2.6.5",
    "element-theme": "^2.0.1",
    "element-ui": "^2.9.1",
    "google-protobuf": "^3.8.0",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "vue": "^2.6.10",
    "vue-native-websocket": "^2.0.13",
    "vuex": "^3.0.1"
  },

### What is expected?
When i change the value of textarea every time, the v-for will be refreshed!

### What is actually happening?
In my project, I have a textarea and a list. and the textarea bind a v-model 'replyMsg' and the list is v-for and use a variable 'list'.
When I change the value of textarea every time(reminder: variable 'list' always unchanged) the v-for refreshed every time!
ps：you can see the test log at the consloe in i given  minimal reproduction

**Comment by Justineo** [comment]
This is expected. Vue rerenders the whole component if any dependency is changed. This will be optimized in Vue 3 with the upcoming ”block level“ updates.

**Comment by xiaohunsdt** [comment]
I don’t understand that they clearly have no dependencies.v-model is 'replyMsg', v-for is 'list',These two variables have nothing relationship
