### ISSUE TITLE
Props are getting update from the child to parent.

### ISSUE THREAD

**Issue by Anu1601CS** [vuejs/vue#10174]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-2x864?fontsize=14](https://codesandbox.io/s/vue-template-2x864?fontsize=14)

### Steps to reproduce
There are two types of  behaviors:

1. In child component, if we update the props ( Array types ) the value of array its gets updated in both child and parent, but not getting reflecting in the template.

2. In child component, if we update the props ( Objects types ) the value of object its gets updated in both child and parent, and also getting reflecting in the template

https://codesandbox.io/s/vue-template-2x864?fontsize=14

### What is expected?
According to the official document, it should not update in the parent component.

### What is actually happening?
Updating in parent components,

**Comment by posva** [comment]
I can't see you array example but you're probably not using splice and modifying the value with an index access. You should check array caveats in documentation 
As a side note avoid modifying a prop, they should be treated as read only but Vue cannot catch arrays and objects modifications without dropping ie support or causing a big perf drop (on dev)

**Comment by anurento** [comment]
Thanks
