### ISSUE TITLE
A method's name passed to v-on:click can't begin with "function" and a Capitalized word

### ISSUE THREAD

**Issue by PaulEdouardB** [vuejs/vue#10177]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/abn13gqy/](https://jsfiddle.net/abn13gqy/)

### Steps to reproduce
- Add a @click handler to a component
- Pass a function with parameter called with a name that begin with "function"   a Capitalized word
- Run

### What is expected?
The function should run only on click

### What is actually happening?
The function is run as soon as the component is loaded
A TypeError is thrown:  _vm.function in not a function or handler is undefined

---
I believe that the vue compiler parse "functionName(param)" as "function Name(param)" thus as the parsed string is evaluated, the function runs immediately when loaded

**Comment by jacekkarczmarczyk** [comment]
In fact in doesn't need to be capital letter, `functiontest` also fails

**Comment by regchiu** [comment]
Because your function name is wrong.

https://jsfiddle.net/hscd046x/

**Comment by Justineo** [comment]
It's already fixed in #9922. But it seems that the latest release is published before it.

/cc @yyx990803 Let's see if it's time for a new patch release.
