### ISSUE TITLE
Self-closing component tag renders incorrectly

### ISSUE THREAD

**Issue by JerryYuanJ** [vuejs/vue#10170]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/tnxjh6d0/1/](https://jsfiddle.net/tnxjh6d0/1/)

### Steps to reproduce
Please check the simple code sample which explains in detail.

### What is expected?
Self-closing component tag should render the message info.

### What is actually happening?
message is ignored after a self-closing component, the others two are correct.

---
I don't know why this is happening, maybe it's not a bug and I just use it in a wrong way ?

**Comment by posva** [comment]
This is an html caveat, you have to write the closing tag as well. On vue files and string templates, the limitation does not exist
