### ISSUE TITLE
await Vue.nextTick() returns undefined

### ISSUE THREAD

**Issue by pmgexpo17** [vuejs/vue#10182]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/5p6g2wxL/](https://jsfiddle.net/5p6g2wxL/)

### Steps to reproduce
Here is the sample code, which is a vuex test module sample :
import Vue from 'vue'
class UnitTest {
  get timestamp() {
    return this._timestamp();
  }
  
  async _timestamp() {
    // make sure each timestamp is unique
    let promise = await Vue.nextTick()
    console.log('timestamp ready : ', promise)
    return new Date().getTime().toString()
  }
}
let test1 = new UnitTest()
console.log('timestamp : ', test1.timestamp)

### What is expected?
According to the docs, calling Vue.nextTick() or this.$nextTick() returns a promise.
 https://vuejs.org/v2/api/#vm-nextTick

### What is actually happening?
My code shows that Vue.nextTick() doesn't return a promise

---
1. Is there a problem calling Vue.nextTick() in a custom vuex module?
2. Is there a problem with my async / await syntax?
I followed this related mozilla tutorial : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by posva** [comment]
It does return a promise, there may be something wrong in your project. Closing as the repro is invalid.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by pmgexpo17** [comment]
About the line : console.log('timestamp ready : ', promise)
In Chrome console, this shows : timestamp ready :  undefined
My jsfiddle sample doesn't handle console prints, but anyway it looks like a bug

**Comment by Justineo** [comment]
`$nextTick` does return a `Promise`. But `await`ing a `Promise` will return the fulfilled value of that `Promise`, in this case, `undefined`. It's just [how `await` works](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) instead of a bug.

**Comment by pmgexpo17** [comment]
Thanks, this version still returns a promise even though await is supposed to return the resolved value
async _timestamp() {
    // make sure each timestamp is unique
    await Vue.nextTick()
    return await new Promise((resolve) => { resolve(new Date().getTime().toString()) })
  }

**Comment by sirlancelot** [comment]
A function with the `async` signature will _always_ return a Promise. A function _call_ invoked with `await` will always resolve the promise and return the resolved value.

That is the standard interaction between Promises and async/await.

Your original Fiddle adheres to this. `Vue.nextTick()` returns a promise, which you are `await`ing. The `await`ed value is `undefined`, which is also correct.

**Comment by posva** [comment]
BTW you can and should do this:

```js
async _timestamp() {
  // make sure each timestamp is unique
  await Vue.nextTick()
  return new Date().getTime().toString()
}
```

because the function is async, return the value directly

**Comment by pmgexpo17** [comment]
I admit my bug claim was not sensible 🤯 ... pretty funny though in hindsight ! Lol ! I may need a holiday

**Comment by Enconnn** [comment]
You and me both. lol

On Jun 24, 2019 5:32 PM, Peter McGill <notifications@github.com> wrote:

I admit my bug claim was not sensible 🤯 ... pretty funny though in hindsight ! Lol ! I may need a holiday
