### ISSUE TITLE
Vue mutiple checkboxes can't  reset value to array

### ISSUE THREAD

**Issue by suozq1** [vuejs/vue#10189]
### Version
2.6.10

### Reproduction link
[https://github.com/suozq1/learning/tree/master/vue](https://github.com/suozq1/learning/tree/master/vue)

### Steps to reproduce
``` 
<div id="app">
        <input type="checkbox" v-model="gain" value="1" >A
	<input type="checkbox" v-model="gain" value="0" >B
	<input type="checkbox" v-model="gain" value="-1" >C
	<input type="text" v-model="gain">
	<hr>
	<select v-model="gain" multiple>
		<option value="1">A</option>
		<option value="0">B</option>
		<option value="-1">C</option>
	</select>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script type="text/javascript">
    var app = new Vue({
             el:"#app",
             data:{
                gain:[1]
            }
     });
</script>
```

---------------------------------
In console ,When I set app.gain=1,all checkboxes  will be checked, the select will throw error;  Then I click checkbox , app.gain toggle between true and false; I click select ,app.gain will be reset to array;  I feel so weird ; Why do they behave so differently?
I don't know whether this is a bug or not ,I just expect when I click checkbox ,it can reset app.gain  to array like select

### What is expected?
I don't know whether this is a bug or not ,I just expect when I click checkbox ,it can reset app.gain  to array like select

### What is actually happening?
Vue mutiple checkboxes can't  reset value to array

**Comment by suozq1** [comment]
`<div id ="app">
<input type="checkbox" v-model="gain" value="1" >A
<input type="checkbox" v-model="gain" value="0" >B
<input type="checkbox" v-model="gain" value="-1" >C
<input type="text" v-model="gain">
<hr>
<select v-model="gain" multiple>
	<option value="1">A</option>
	<option value="0">B</option>
	<option value="-1">C</option>
</select>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js">
</script> <script type="text/javascript"> var app = new Vue({ el:"#app", data:{ gain:[1] } }); </script>
`

**Comment by suozq1** [comment]
<pre>

**Comment by suozq1** [comment]
`<input type="checkbox" v-model="gain" value="1" >A
	<input type="checkbox" v-model="gain" value="0" >B
	<input type="checkbox" v-model="gain" value="-1" >C
	<input type="text" v-model="gain">
	<hr>
	<select v-model="gain" multiple>
		<option value="1">A</option>
		<option value="0">B</option>
		<option value="-1">C</option>
	</select>`

--------------
HTML code

**Comment by posva** [comment]
The thing is you cannot have the value as an array and a number as the same time:

- select with v-model generates a single value
- multiple checkboxes bound to the same value generates an array

You will need to ensure that the value bound to v-model is correct before allowing any interaction
