### ISSUE TITLE
click outside method prematurely fires the closing event

### ISSUE THREAD

**Issue by EvanBurbidge** [vuejs/vue#10180]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-ji7ml](https://codesandbox.io/s/vue-template-ji7ml)

### Steps to reproduce
Open the above link
Click on the button

### What is expected?
The text should show.

### What is actually happening?
The event that fires to call the "hideChild" method is called before the element is created, perhaps this is a premature call of the method. If you watch the console you will see hiding child element without click is logged to the console. 

---
I know we can use .stop on the click event handler, however in my current application there are too many call sites to try and find them all. This means that we need to try to stop the propagation of the event within the click outside directive. 

If we can call the stop inside the clickoutside.js  this would be a big help  as it would mean that one file has to be changed instead of 1 -> N files.

I have tried calling stop within the bind method, but so far have not been able to stop the event from propagating.

**Comment by posva** [comment]
In the repro the text does show.
You may want to look at https://github.com/vuejs/vue/issues/9340 and other issues related to a change introduced in 2.6

**Comment by EvanBurbidge** [comment]
@posva  thanks for the reply we fixed it by wrapping the event listeners inside set timeouts. 

```javascript
export default {
  bind(el, binding, vnode) {
    el.event = function f(event) {
      let stop = false;
      if (!(el === event.target || el.contains(event.target))) {
        stop = true;
        vnode.context[binding.expression](event);
      }
      if (stop) {
        event.stopPropagation();
      }
    };
    setTimeout(() => document.body.addEventListener("click", el.event), 0); // this line will close it straight away if not wrapped in a setTimeout
  },
  unbind(el) {
    document.body.removeEventListener("click", el.event);
  }
};

```
