### ISSUE TITLE
This reference is undefined in template's v-for loops

### ISSUE THREAD

**Issue by gewoonwoutje** [vuejs/vue#10190]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/caxzegtw/](https://jsfiddle.net/caxzegtw/)

### Steps to reproduce
- Look at the two this pointers; only one is working

### What is expected?
This pointer should refer to the Vue instance.

### What is actually happening?
In the fiddle; the this.message is not showing inside the v-for.
In our project; this is undefined and throws an error in the console.

**Comment by posva** [comment]
Never use `this` in templates

**Comment by gewoonwoutje** [comment]
> Never use `this` in templates
Where is that defined/ documented? If that is so important, why isn't it enforced?

**Comment by maj625** [comment]
if you still having the issue here is a workaround I'm using.
in your data add a variable like myRef: this and use myRef in the v-for loop instead of this

**Comment by WhereJuly** [comment]
@gewoonwoutje You could access the parent scope with either `$data` or `$props` ($methods do not work and I did not try to access a parent scope's computed).

```javascript
  <ul>
     <!-- Failing reference to this -->
     <li v-for="item in items">{{item}}:{{$data.message}}</li>
  </ul>
```
