### ISSUE TITLE
Add $forceCompute with ability to select components to compute.

### ISSUE THREAD

**Issue by ing200086** [vuejs/vue#10194]
### What problem does this feature solve?
There are times when data is updated but the computed properties are cached not allowing an update. The overhead added with watched variables (both to front end items to make data, watch setup, etc. and use end resources) does not always make sense. This makes users need to add their own way of doing it and hooking in computed items.

### What does the proposed API look like?
``` javascript
this.$forceCompute() // recompute all computed variables
this.$forceCompute(['computed1', 'computed2']) // recompute only computed1 and computed2 variables
this.$forceCompute(['computed1', 'computed2'], false) // recompute everything but computed1 and computed2 variables
```

**Comment by posva** [comment]
Computed are automatic and that’s the point of using them, they catch reactive properties being used and get reexecuted when necessary. If you want to recompute them, you might need a method instead. You can also use https://github.com/posva/vue-recomputed

**Comment by ing200086** [comment]
I agree, computed properties are automatic.... unless they aren't. 

I saw this issue come up multiple times (especially for arrays or objects), so I thought this would be a good solution for when it doesn't update automatically.

Thanks for the response.

**Comment by jacekkarczmarczyk** [comment]
> especially for arrays or objects

Do you mean this https://vuejs.org/v2/guide/list.html#Caveats and https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats?

**Comment by ing200086** [comment]
Already went there and tried that. Didn't work. :(

Going back for a second about the methods. Methods would be recalculated each time and not cached correct? If the objects or arrays which would be returned only need to be recomputed rarely, why is it a bad idea to allow the user to trigger that manually?

Just curious why instead of adding the feature the response would be an immediate no? This seems to be a question that comes up a lot.

**Comment by posva** [comment]
Check https://github.com/vuejs/vue/issues/214 out

> Going back for a second about the methods. Methods would be recalculated each time and not cached correct? If the objects or arrays which would be returned only need to be recomputed rarely, why is it a bad idea to allow the user to trigger that manually?

Because a computed property is automatic, having to call them again defeats the purpose. If they are not working, there is either something wrong with your code or a bug in reactivity but you didn't share any repo or piece of code to check, that's why @jacekkarczmarczyk tried to guess

**Comment by tony-wong-aurizon** [comment]
Im currently having the same issue with getting data from Vuex

`  computed: {
    someData() {
     return this.$store.getters.getSomeData();
    },`

That doesnt update when another component up the Vuex Store

**Comment by tonywong625** [comment]
Im currently having the same issue with getting data from Vuex

`  computed: {
    someData() {
     return this.$store.getters.getSomeData();
    },`

That doesnt update when another component update the Vuex Store

**Comment by mandeepsinghgill** [comment]
> Im currently having the same issue with getting data from Vuex
> 
> ` computed: { someData() { return this.$store.getters.getSomeData(); },`
> 
> That doesnt update when another component update the Vuex Store

Getters are properties so don't use like as a function
```
return this.$store.getters.getSomeData();
```

to 

```
return this.$store.getters.getSomeData;
```

**Comment by mandeepsinghgill** [comment]
Make sure you commit your changes after action execute, you don't need any forcefully actions.

Example :

actions.js
```
setData({commit}, payload) {
   // Some https requests or any other code
  // then commit
  commit(payload)
}
```

mutations.js

```
SET_DATA(state, payload) {
 state.someData = payload
}
```
