### ISSUE TITLE
Unexpected behavior of v-if

### ISSUE THREAD

**Issue by veah** [vuejs/vue#10192]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/veah07/Ls7cv8ph/12/](https://jsfiddle.net/veah07/Ls7cv8ph/12/)

### Steps to reproduce
Just run the JSFiddle and you'll see

### What is expected?
What is expected to be left is:
```html
<div class="second">
    2
    <div class="test-div">test</div>
</div>
```

### What is actually happening?
what is actually left is:
```html
<div class="second">
    2
</div>
```

---
when div.second has a childNode or a key, or removing the div.first or div.third,  the code works fine

**Comment by posva** [comment]
If you modify the dom manually, Vue cannot keep track of modifications and it ends up removing the wrong element
If you want to do that, you need to wrap that into a component and make sure all dom modifications happen inside that component (or other components) with no Vue interaction
