### ISSUE TITLE
vue3 function api使用中存在的问题，请问如何解决

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#10198]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-zlflg?fontsize=14](https://codesandbox.io/s/vue-template-zlflg?fontsize=14)

### Steps to reproduce
这个问题是在使用 https://github.com/vuejs/vue-function-api 的时候发现的，个人认为这个问题非常严重，不确定是否是在计划中的还是预计在更新来vue3之后会自然而然解决的，所以在这里提出。

社区应该是接受中文issue的，自己英语没有那么给力，就直接中文提问来。

这个问题很简单，考虑有如下组件：

```js
export default {
  setup(props) {
    const data = props.data
    const x = computed(() => data.num   1)

    return { x }
  }
}
```

这里的 `data` 是一个对象，在这种情况下，如果 `props.data` 改变成一个新的对象，那么 `x` 这个 `computed` 变量，是无法响应新的 `data` 变化的。以我对 vue 的理解，这是因为 `computed` 的属性是根据调用过程中触发来依赖的 `get` 来绑定依赖的。而这种情况下恰恰我们无法绑定依赖到 `props.data`，仅仅是绑定到了 `data.num`。

这是 `computed` 绑定依赖的问题，所以跟 reactive 实现的方式应该无关，也就是说即便改成来 `proxy` 的方式，这个问题可能依然存在。

不知道该问题应该如何解决？

### What is expected?
即便在写`setup`的时候先从 `props` 中读取来属性，依然应该能检测到 `props.xxx` 的变化

### What is actually happening?
在读取了`data`之后再依赖`data`，无法检测到 `props.data` 的变化

**Comment by DricHao** [comment]
改变成新的对象。难不成是Object.assign?

**Comment by Justineo** [comment]
See https://github.com/vuejs/rfcs/issues/63.

**Comment by Jokcy** [comment]
@DricHao 比如上层组件传入的是一个 `computed` 的属性，来自于 `cont data = computed(() => ({ num: xxx }))`，其中 `xxx` 是一个 `value(123)`，每次 `xxx` 改变会让data更新成一个新的对象。

@Justineo 可否更详细指出哪里提到了？我没在那边看到跟这个问题有关的描述

**Comment by yyx990803** [comment]
返回的 `data` 是一个 value wrapper，是不会变成新的对象的... 每次传下去的都是同一个对象

**Comment by Jokcy** [comment]
@yyx990803 哦～～～了解了。那现在使用 `vue-function-api` 出现这个问题是实现上的原因么？
