### ISSUE TITLE
Document watch immediate behavior

### ISSUE THREAD

**Issue by FelixVicis** [vuejs/vue#10196]
### What problem does this feature solve?
There is some confusion in the timing involved for `vm.$watch.immediate`

The first call to the provided callback happens before the teardown is created and therefore cannot be unwatched at the first call.
https://github.com/vuejs/vue/blob/0948d999f2fddf9f90991956493f976273c5da1f/src/core/instance/state.js#L346-L348

Several people have logged this thinking it's an undesired behavior.
https://github.com/vuejs/vue/issues/2276
https://github.com/vuejs/vue/issues/9134
https://github.com/vuejs/vue/issues/9501

It would help greatly to have this behavior documented so that future users don't encounter this error.

### What does the proposed API look like?
https://vuejs.org/v2/api/#vm-watch

```js
// Will cause an error, Undefined is not a function
// teardown is only available after first call.
const teardown = this.$watch('value', () => { teardown() }, { immediate: true });
```

Use a checking pattern instead.
```js
if (this.value)
   doTheThing();
else {
   const teardown = this.$watch('value', () => {
      doTheThing();
      teardown();
   });
}
```

**Comment by posva** [comment]
Some more information in docs would indeed help!
Could you open a PR to docs repo vuejs/vuejs.org ? Or an issue like this one?
