### ISSUE TITLE
V-bind error on ignored elements

### ISSUE THREAD

**Issue by delta1186** [vuejs/vue#10209]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/delta1186/2eLknsbc/12/](https://jsfiddle.net/delta1186/2eLknsbc/12/)

### Steps to reproduce
I have given additional information in the fiddle, but in the fiddle if you remove the html comment tag and run the fiddle the app with break with the [Vue warn]: Error compiling template:The value for a v-bind expression cannot be empty. Found in "v-bind:" error.

### What is expected?
The app should render since the tag is set to be ignored.

### What is actually happening?
Ignored tags via still throw v-bind errors in special cases.  Described in fiddle.

**Comment by Justineo** [comment]
`https://www.helloworld.com` isn't a syntactically allowed HTML tag name. This would break the HTML parser of both browser and Vue. You shouldn't use it as a tag name at the first place.

**Comment by delta1186** [comment]
I know it’s not, but if you read the fiddle I’m not using it on purpose. Use any custom tag combo and it will break if you have:

<name:/

Yes I know that tag doesn’t make sense. That’s why I gave the real life url example. FYI the <https://www.abc.com> technically doesn’t break in the browser. It’s just ignored and nothing is displayed. 

So if you ignore that fact Vue still has an issue. The ignore element global needs to run before the v-bind handler. I’m assuming that’s why the error occurs. 

If the global ignore elements does run first, then there is a bug because ignored elements are still getting processed by the v-bind handler. 

I think you were too quick in closing this issue.

**Comment by posva** [comment]
To be clear: `<name:/` doesn't work on plain HTML either. @Justineo's point is that valid HTML should be passed to Vue. If you have URLs as tag names, there should be some preprocessing there to make the tags valid.
The one tag that seems to fail is `<name:></name:>`, you can prevent Vue from parsing directives using a `v-pre`. `<name:hey>` seems to work properly. That being said, the HTML spec only seems to allow _alphanumeric ASCII characters_, which excludes `:`. in tag names

**Comment by delta1186** [comment]
@posva I understand it is not a valid tag. When you say the tag doesn't work do you just mean it doesn't do anything in the browser right?  If so, then I am fine with that.  In my test cases the browser just ignores it and doesn't show anything.  Also in my example there are no closure tags. 

Here is a real life example of an email body I get into my application after it is parsed.

> I need some help with my phone!  Stop what are doing and call me now.
> 
> John
> 
> John Doe, VP of Everything
> www.thecompany.com <http://www.thecompany.com>
> 222. 222. 2222 cell
> 333. 333. 3333 office

I have no clue why the email agent adds that tag after the url in the email signature.  The emails on imported via IMAP.  I have used POP3 too, but that added a weird tag to the email of phone numbers. 222. 222. 222 <tel:+2222222222>  No clue why.  

Unfortunately I cannot strip anything that looks like a html tag because there is often times valid html tags in the body of the emails too.  

Also, to reference your last comment on the : no being allowed in a tag please reference this article. [vue-ignore-custom-component-tag](https://stackoverflow.com/questions/45040689/vue-ignore-custom-component-tag)
This was the article I found the other day when I was trying to fix my issue and how I discovered the Vue.config.ignoreElements global setting which I figured would resolve my issue.

So yes <name:hey> will work if you add a RegEx to the ignoreElements like this /^name/. But that is because you have a value of some kind after the colon.  If you don't have a value like <name:> yes this breaks even though it is supposed to be ignored.  Again this is why the v-bind directive handler is being processed on an ignored tag.  Make sense?  So this <name:hey> works, but <name:/hey> doesn't work.  Even though there are values after the colon in this case I think Vue freaks out on / special character.  

So my whole point here is that ignoreElements does not work in all cases.  Two cases where it will break because it tries to evaluate what it thinks is the : colon for the v-bind directive, but technically is not.  
<name:> and <name:/hey> throws v-bind error 
<name:hey> is properly ignored by Vue and the browser unless you are using another 3rd tool to render it on the client in the case of the stackoverflow article referenced above for the google component. 

Also the <tel:+222 example above I think breaks too.  I think this would be the same reason as the <name:/hey> having to do with having the colon and followed by a special character like a / or +.

Well, that's a lot and I hope you all reconsider taking a look at this issue, because I still think it valid.  Thank you for your time and consideration.

**Comment by delta1186** [comment]
And a funny aside, after I posted the above article the email example signature block rendered the url twice. 🤷🏻‍♂️ I had to edit the post and include the code markdown. Example below:

www.thecompany.com <http://www.thecompany.com>
www.thecompany.com `<http://www.thecompany.com>`

**Comment by posva** [comment]
> When you say the tag doesn't work do you just mean it doesn't do anything in the browser right

No, I mean that the browser yields a different tag from what you wrote. In general, you cannot rely on browsers behavior when it comes to non-conformant tag names and any other thing. Passing valid HTML to Vue, should yield valid results, and it currently does

**Comment by delta1186** [comment]
So I realize this is an edge case type scenario and I am getting the feeling I am not going to get any traction with this issue.  Unfortunately I don't have a magic wand.  I cannot predict what garbage I might get from the email parsing client.  Might thought was that it would be easier to tackle these issues as they come up by building a array of "tags" to ignore using the built-in global Vue config ignoreElements option.  This would be faster to fix an app breaking issue on the fly then to try can create special parsing options for each condition that arises over time.  Maybe I am wrong in my thinking. Again ignoreElements works except when you add the special character after the colon or a blank space, then you get the v-bind error.

**Comment by delta1186** [comment]
It does appear that some special characters are considered after reviewing some of the core edge case tests: 🤔 https://github.com/vuejs/vue/blob/159f3d5bec96a4660bc67d339ac242b8f15ae29e/test/unit/modules/vdom/patch/edge-cases.spec.js

Of course the above test does not include the colon before the dash.

**Comment by Justineo** [comment]
> I understand it is not a valid tag. When you say the tag doesn't work do you just mean it doesn't do anything in the browser right?

The browser parses your HTML input and generates a DOM tree based on it. You just didn't see it on the screen. Open devtools to inspect the DOM and you'll see it's already generating malformed structure, before Vue has a chance to deal with the input.

> Unfortunately I cannot strip anything that looks like a html tag because there is often times valid html tags in the body of the emails too.

If you don't escape HTML properly there will probably security risks. If the user input is an HTML string, I think you'd better use a white-list of tags that are “allowed” thus are kept untouched and escape all of the rest.

**Comment by delta1186** [comment]
@Justineo thanks for the response.  Yeah I get it.  Malicious code, malformed code, etc.  This is more of an internal project so less concern about that, but I understand where you are coming from.  In the end I am probably just going to create a server-side parsing method to evaluate the email body and encode those weird tags that are being generated from the email client.

I just thought the Vue v-bind issue was worth pointing out in case it was something the community or @yyx990803 might want to address.  Especially if a browser decides it's going to render malformed code and in turn break the Vue app.  That's why I thought the ignoredElements would resolve my issue in this case, but I guess the colon directive followed by probably any special character is going to break Vue.

**Comment by delta1186** [comment]
Okay, I am not giving up on this just yet.  Despite all the chatter on the malformed tags and security risks I still think Vue's behavior is inconsistent and here is why.

https://jsfiddle.net/delta1186/2eLknsbc/13/

I have updated my fiddle and I include the v-pre attribute to the malformed tag ( **<https://www.helloworld.com v-pre>** ) and low and behold the app does not break.  So I did some digging to see why this would work and setting **Vue.config.ignoredElements = [/^test/, /^https/]**; does not work.  Seems to me these should work the same way.

**Vue.config.ignoredElements**
[https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js](https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js)
If you review line 107 inside the `isUnknownElement` method you see where `ignoredElements` is being evaluated.  You also see the `inVPre` on line 109.  Both `v-pre` and `ignoredElements` are being evaluated here. 

**V-bind** 
[https://github.com/vuejs/vue/blob/dev/src/compiler/parser/index.js](https://github.com/vuejs/vue/blob/dev/src/compiler/parser/index.js)
So here is were I believe we are wiring up the v-bind directives.  We see this in at least two vars that are defined on lines 25 and 34.  Both of these vars are then used in the `processAttrs` method on line 758.  `processAttrs` is called inside of `processElement` method.  Finally `processElement` is called on line 116.  Now if you look at line 115 you will find the inconsistent behavior.  There is the `inVPre` check.  Since in my fiddle I added the `v-pre` attribute it gets evaluated as true and so the entire element is skipped and the v-bind logic which is giving the error is never run.  

So what's the fix.  I believe if you just also included a check on line 115 for `ignoredElements` then problem solved!  

Let me know if I am missing something.

**Comment by Justineo** [comment]
Vue's `ignoredElements` is only used to differentiate Vue components with native web components. `v-bind` still works on web components, see [this fiddle](https://jsfiddle.net/Justineo/jsxr1tkn/). It's not used to skip certain elements like `v-pre` does.

**Comment by delta1186** [comment]
@Justineo yeah that makes sense.  So do you think there is a place in the code for setting v-pre elements globally instead of inline.  This might be nice option if you are always adding v-pre to a certain element.  Something like:

Vue.config.globalVPreElements = [/^http/, /^tel/, 'div'];

Something like this would also fix my issue.

**Comment by Justineo** [comment]
I can’t see a proper use case for it. In your case, it’s definitely not a “fix” but just bypassing the problem caused by malformed markups. Ps. You can skip an entire sub tree with a `v-pre` on its root. This may skip the whole email body for you.

**Comment by delta1186** [comment]
@Justineo fair enough.  Thanks for the information on putting the `v-pre` on the parent.  I am going to do that.  Just did not think about it being an option. :)

So I do have another thing that has come up now after adding the `v-pre` on the parent `div`.

![image](https://user-images.githubusercontent.com/421307/60526727-7e646380-9cb6-11e9-84c3-11302e13b5e5.png)

I am getting the above errror in the console because of text that is being rendered inside the `v-pre` parent `div`.  

`Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '\uncolder' is not a valid attribute name.`

`Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': ':\uncolder' is not a valid attribute name.`  tried removing the whitespace after the colon, but still get error.

The text that is inside the div has a malformed tag, but I thought is would be ignored because of `v-pre` on the parent `div`.  Here is an example of the data getting rendered:

\\unc\folder<file: \\unc\folder>

You can see from the image that Vue is escaping some of the backslashes from the file tag.  It is also now getting an error on the `setAttribute `method.  Just to be clear the <file: \\unc\folder> tag is not user generated.  The user just sent an email to the system with the original \\unc\folder and the email client/agent added the <file: \\unc\folder> tag.  This is the same for all the other malformed tags I have referenced in this thread.  None of them were user created.
