### ISSUE TITLE
IE11 - Promise is undefined

### ISSUE THREAD

**Issue by cliffordh** [vuejs/vue#10203]
### Version
2.6.10

### Reproduction link
[http://jspellsite2018-1.us-east-1.elasticbeanstalk.com](http://jspellsite2018-1.us-east-1.elasticbeanstalk.com)

### Steps to reproduce
I have specified in babel.config.js:

// babel.config.js
module.exports = {
  presets: [
    ['@vue/app', {
      polyfills: [
        'es6.promise',
        'es6.symbol',
        'es6.object.assign'
      ]
    }]
  ]
}

I have NOT imported anything in main.js.

I am using vue-cli-service build

However, when executing in IE11 I get the immediate error Promise is undefined.

If I try to import @babel/polyfill then I get an error saying I should use useBuiltIns: 'entry'. But that will include too many polyfills.

It appears that vue-cli-service build is not including the polyfills I've specfied above.

Any ideas?

### What is expected?
Polyfills are loaded

### What is actually happening?
Not loaded

**Comment by posva** [comment]
Polyfills for Promises are unrelated to Vue.

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
