### ISSUE TITLE
Checkbox state stuck

### ISSUE THREAD

**Issue by meyt** [vuejs/vue#10204]
### Version
2.6.0

### Reproduction link
[http://jsfiddle.net/meytighg/5etmnsuv/16/](http://jsfiddle.net/meytighg/5etmnsuv/16/)

### Steps to reproduce
There is a simple ToDo http://jsfiddle.net/meytighg/5etmnsuv/16/
with two list, `Tasks` and `Finished Tasks`.

Based on reproduction link:

- Click on item 1 checkbox from `Finished Tasks`

### What is expected?
Item 1 removed from `Finished Tasks`

### What is actually happening?
Item 1 removed from `Finished Tasks`, but item 2 is unchecked on `Finished List`.

---
This unexpected behavior is exist on Vue >= 2.6.0.

For example Vue 2.5.9 is fine. http://jsfiddle.net/meytighg/5etmnsuv/18/

**Comment by ilyaskarim** [comment]
I tried to solve but this is a bug, I tried also on this jsFiddle http://jsfiddle.net/d83etom2/9/.

**Comment by Justineo** [comment]
Please always use a proper `key` for `v-for` loops of there's a stateful element/component inside each item. See [the related docs](https://vuejs.org/v2/guide/list.html#Maintaining-State).

**Comment by Justineo** [comment]
http://jsfiddle.net/Justineo/gwz4r271/
