### ISSUE TITLE
New slot syntax not working with "is"

### ISSUE THREAD

**Issue by mavajee** [vuejs/vue#10201]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-7x6nl](https://codesandbox.io/s/vue-template-7x6nl)

### Steps to reproduce
Use `v-slot` directive with "is" attribute

### What is expected?
similar behavior with the old syntax of slots

### What is actually happening?
scoped slot not working with dynamic component

**Comment by mavajee** [comment]
it's not critical for me but maybe it can help You make it better

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/10152
