### ISSUE TITLE
Error from watchers not captured

### ISSUE THREAD

**Issue by tcastelly** [vuejs/vue#10215]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/shenron/kbuymoz0/](https://jsfiddle.net/shenron/kbuymoz0/)

### Steps to reproduce
Create a watcher, and reject a promise inside.

### What is expected?
Vue should capture the reject with `errorCaptured`

### What is actually happening?
The reject has not been captured

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/10009
