### ISSUE TITLE
Handling loading in local registered components is not working.

### ISSUE THREAD

**Issue by Mighty683** [vuejs/vue#10216]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-sejok](https://codesandbox.io/s/vue-template-sejok)

### Steps to reproduce
Try to lazy load local registered component the way described here:
https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State

Minimal repro:
https://codesandbox.io/s/vue-template-sejok

### What is expected?
Displaying loader component before rendering target component like described in:
https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State

### What is actually happening?
Component is displayed after promise resolving without displaying loader before.

---
I don't know if this is a bug if not I think this should be feature request because for creating PWA displaying loaders during preparing app to work is crucial.

**Comment by posva** [comment]
Your delay is bigger than the time the component takes to load, lower it down to 200 (ms) for example

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by Mighty683** [comment]
Shoudn't loader be displayed during delay? If not what is purpose of this delay?

For example to avoid jumping content in application I want delay displaying content by some value eg: one round of loader, 200ms. To deliver "smooth" feeling to user of loading component even if he has good internet connection and components will download in 50ms.

**Comment by posva** [comment]
No, the delay purpose is precisely that (as said in the doc link you mentioned)

> For example to avoid jumping content in application I want delay displaying content by some value eg: one round of loader, 200ms. To deliver "smooth" feeling to user of loading component even if he has good internet connection and components will download in 50ms.

That's something you will either have to:

- handle in a custom dynamic component
- creating a function that wraps your dynamic imports so they last for at least 200ms and set the delay to 0, so loaders are displayed at least for 200ms

**Comment by Mighty683** [comment]
I get it sorry I missunderstood documentation I thinked that this is delay for whole rendering not only loader

**Comment by Mighty683** [comment]
I created this second solution and now its working fine thank you for help.
