### ISSUE TITLE
this.$route.path incorrect when url have params

### ISSUE THREAD

**Issue by 18959263172** [vuejs/vue#10210]
### Version
2.6.9

### Reproduction link
[https://codepen.io/18959263172/pen/GbQOQy](https://codepen.io/18959263172/pen/GbQOQy)

### Steps to reproduce
when I visit with url '/article' 
this.$route.path is right and the value is '/article'
when I visit with url '/article/1'
but  the value of this.$route.path that console put out is '/'

### What is expected?
'/article/1'
this.$route.path is like '/article/1'

### What is actually happening?
this.$route.path is  '/'

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

If you are reporting a bug, make sure to provide a boiled down editable and runnable repro
