### ISSUE TITLE
Memory leak in PROD version

### ISSUE THREAD

**Issue by clopezcapo** [vuejs/vue#10214]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue/issues/10004](https://github.com/vuejs/vue/issues/10004)

### Steps to reproduce
Please follow the steps here: https://github.com/vuejs/vue/issues/10004

- go to the about page
- type in the input
- leave the page
- collect garbage and take a snapshot with devtools

### What is expected?
VueComponent count should be stable

### What is actually happening?
VueComponent count keeps increasing.

---
IMPORTANT:

Also happens in the PROD version. It looks like a crucial fix to do.

**Comment by posva** [comment]
Please, don't open duplicates
