### ISSUE TITLE
关于 v-if 指令的疑问

### ISSUE THREAD

**Issue by ronggang** [vuejs/vue#10212]
### Version
2.6.10

### Reproduction link
[https://codepen.io/ronggang/pen/PrQXVM](https://codepen.io/ronggang/pen/PrQXVM)

### Steps to reproduce
- 不停的点击 `type1` 和 `type2`；
- 在  `<input id="input1"/>` 后面会添加很多个 `div`；而不是预期的只会添加一个 `div`；
- 这样好像没有体现出 `v-if` 的作用？还是我对 `v-if` 的理解有误？或者 vue 缓存了一些东西？

### What is expected?
在使用 `v-if` 进行不同 `DOM` 切换时，希望可以删除所有后期动态添加的 `DOM`；

比如像这个
https://codepen.io/ronggang/pen/PrQXVM
给一个 `div` 添加 id，就可以删除动态添加的子 DOM；但如何给两个 `div` 都添加 id，就又不能清除由 renderUI 创建 `div` 子 DOM。

### What is actually happening?
未能正常清除动态创建子 DOM。

---
由于老项目中使用了一些 jQuery 组件，由于这些组件会动态渲染DOM，但最近在加入 vue 库时遇到一些问题；上面的问题是对实际项目的简化，但大概过程类似；由于 vue 初学，对于有些概念可能理解的不是很到位，请各位帮忙解答一下，谢谢！
由这些 jQuery 组件暂时无法全部转为 Vue 组件，所以只能混合使用。

**Comment by posva** [comment]
If you want to manipulate the DOM manually (outside of Vue templates), make sure to encapsulate that in components because when Vue renders, it's not aware of any manually added DOM and it can lead to unexpected behavior.
eg: encapsulate every jQuery plugin in a component

**Comment by ronggang** [comment]
如果给两个 `div` 设置了不同的 `key` 就可以解决问题了。

**Comment by ronggang** [comment]
> If you want to manipulate the DOM manually (outside of Vue templates), make sure to encapsulate that in components because when Vue renders, it's not aware of any manually added DOM and it can lead to unexpected behavior.
> eg: encapsulate every jQuery plugin in a component

Thanks Reply.
