### ISSUE TITLE
filters和三目结合出现的问题

### ISSUE THREAD

**Issue by mhxy13867806343** [vuejs/vue#10219]
### What problem does this feature solve?
实现如下的功能      
，展示 的效果是
界面上展示 的效果就展示  上架 ，并且加上（如果带样式了），就把相关样式加上 

### What does the proposed API look like?
    <span :class="row.rewardTf>-1?'':'nots'">{{(row.rewardTf || '未找到相关的奖励状态') | announcementRewardTf }}</span>
出现的问题是announcementRewardTf提示它没有定义，但我已经在filters:{}中定义过了，

**Comment by mhxy13867806343** [comment]
![TIM截图20190702150745](https://user-images.githubusercontent.com/4418166/60491375-3c014d80-9cdb-11e9-9062-e9d7aeac23ce.jpg)
![TIM截图20190702150756](https://user-images.githubusercontent.com/4418166/60491378-3c99e400-9cdb-11e9-9e57-e007b1523c08.jpg)
我项目中使用的结果

**Comment by Justineo** [comment]
Bug report 请带上可运行的复现，按对应的 issue 模板填写，不要选择 feature request 的模板，谢谢。
