### ISSUE TITLE
npm run serve command failed in a freshly made project created with @vue/cli. (Cannot find module '\node_modules\eslint\lib\api.js/package.json')

### ISSUE THREAD

**Issue by m-ahmadi** [vuejs/vue#10226]
Here's what happened:
Installed vue cli tool.
created a project using it.
tried to start the project with `npm run serve` according to docs.
compile process failed, right out of the bat!

![visuue](https://user-images.githubusercontent.com/16363767/60609534-21140380-9dd7-11e9-8f61-5c57e3f7aaf9.png)

### Version
2.6.10

### Reproduction link
[https://github.com/m-ahmadi/vue-issue](https://github.com/m-ahmadi/vue-issue)

### Steps to reproduce
npm install @vue/cli -g &&
 vue create test_app &&
default (babel, eslint) &&
cd test_app &&
npm run serve

### What is expected?
That the app will be served on a local URL.

### What is actually happening?
Compile process fails with 1 error: (Cannot find module '\node_modules\eslint\lib\api.js/package.json')

---
OS: Windows 7 Ultimate Service Pack 1

node -v: v8.11.3
npm -v:    6.9.0
vue -V:     3.9.0
---------------------------------------------------------------------------------------------------------

npm run serve

> testvue2@0.1.0 serve E:\xampp\htdocs\testvue2
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                 20:56:38

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'E:\xampp\htdocs\testvue2\node_modules\eslint\lib\api.js/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.module.exports (E:\xampp\htdocs\testvue2\node_modules\eslint-loader\index.js:170:23)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by posva** [comment]
Please, open this on vue-cli. From reading the error it seems to be a problem in one of the dev dependencies

**Comment by rvbarreto** [comment]
I have this exactly same problem on a project I've just started. My vue/cli was working well, I have created projects on in before but then suddenly it is not possible to create a new project anymore.

**Comment by luxwarp** [comment]
> I have this exactly same problem on a project I've just started. My vue/cli was working well, I have created projects on in before but then suddenly it is not possible to create a new project anymore.

see referenced above. for now this workaround fix the problem
`npm i eslint-loader@2.1.2`

**Comment by furqon** [comment]
im using this solution:
https://forum.vuejs.org/t/npm-run-serve-not-working-with-new-vue-cli-project/67939/11
and it works:

-----
Steps I fixed it via yarn:

remove node_modules and yarn.lock
add "resolutions": { "eslint-loader": "2.1.2" } to package.json
run yarn install
if it is still not working, try adding following to vue.config.js: module.exports = { lintOnSave: false, } as noted here 4
Hope it helps, it finally works for me. Good luck

**Comment by progsri** [comment]
@furqon : This worked fo me.
adding following to vue.config.js: module.exports = { lintOnSave: false, }
