### ISSUE TITLE
not necessary warning in computed setter?

### ISSUE THREAD

**Issue by NoobxzZhang** [vuejs/vue#10228]
### Version
2.6.6

### Reproduction link
[https://codesandbox.io/s/vue-template-rz1is](https://codesandbox.io/s/vue-template-rz1is)

### Steps to reproduce
1. set a computed property `foo` with setter;
2. setter use some property, like `this.flagFoo`, the property(`flagFoo`) is not defined on the data;
3. trigger the `foo` setter ;

### What is expected?
nothing happen

### What is actually happening?
console send a [Vue warn]:
Property or method "flagFoo" is not defined on the instance but referenced during render.

**Comment by posva** [comment]
as a workaround you can declare the proprerty in `created`:

```js
created() {
  this.flagFoo = undefined
},
```

that way, it won't be reactive but it won't trigger any warning.

After checking a bit more I realized, this behavior is actually a good thing. The thing triggering the warning is reading the non-existent flag `if (this.fooFlag)`, this warning helps you realize you are reading a non-existant variable and that could lead to bugs.

If you have dynamic properties that are added on the fly, you should check them like this instead:

```js
 if ('flagFoo' in this) {
  // ...
}
```
