### ISSUE TITLE
Transition js hooks beforeLeave and leave are not working with v-show

### ISSUE THREAD

**Issue by gerasimvol** [vuejs/vue#10220]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-zuj3y](https://codesandbox.io/embed/vue-template-zuj3y)

### Steps to reproduce
1. click `Toggle visibility` button
2. `console.log` in `leaveAnimation method` didn't fired

### What is expected?
`console.log` in `leaveAnimation` method fired

### What is actually happening?
`console.log` in `leaveAnimation` method didn't fired

---
works perfectly fine with v-if
but `v-if` is more performant operation while toggling visibility (modals, menus etc)

**Comment by posva** [comment]
it's because you are using a `key` that replaces the `iml` element at the same time you toggle visibility. Using the `v-show` in that specific case serves no purpose as you hide it at the same time you create a different one, that's why the beforeLeave never triggers

**Comment by gerasimvol** [comment]
@posva 
1. Why it is working with `v-if`?
2. How should I implement menus, modals etc (I need js hook onOpen, onClose for advanced animations)?

**Comment by posva** [comment]
because v-if becomes redundant with the key, so it's the same as not using a key at all
If you want to use v-show make sure to provide a key that doesn't change at the same time as the value passed to v-show
