### ISSUE TITLE
ability to choose when execute "immediate" watcher

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#10222]
### What problem does this feature solve?
a pretty common usecase for watchers is to react to value and update/mutate dom outside of the scope of the template. when doing so, we want watchers to be executed at the birth of the component

### What does the proposed API look like?
`immediate`  values should be : `true/false/"mounted"`

the consequence of setting `immediate: mounted` is that watcher immediate execution will be delegated to the mounted hook event `this.$once("hook:mounted", () => ...)`

### Notes
I understand that it could be done with a common method called once in `mounted` and once in the watcher, but it feels not right to write a (public) method for treating something reactive.

**Comment by posva** [comment]
There is also `this.$watch` which you can call in `mounted` with the `immediate` parameter if necessary:

```js
mounted () {
  this.$watch('list', () => {
    this._plugin.renderList(this.list)
  })
}
```
https://vuejs.org/v2/api/#vm-watch

That being said, having a method to refactor a watcher code is totally fine in other situations
