### ISSUE TITLE
how the vuejs compiler works

### ISSUE THREAD

**Issue by neutron92** [vuejs/vue#10239]
### What problem does this feature 
Hello i want to know how the vuejs compiler works

Step by step
Thanks

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
