### ISSUE TITLE
When the data A in data is object type, the getter method of A repeatedly collects unnecessary dependencies, and the subs in watcher saves unnecessary Deps.

### ISSUE THREAD

**Issue by ganbowengo** [vuejs/vue#10234]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/GbBbwJ](https://codepen.io/anon/pen/GbBbwJ)

### Steps to reproduce
jump link  https://codepen.io/anon/pen/GbBbwJ, Open the console to view _watcher in the Vue instance

### What is expected?

Remove Dep's unnecessary collection of Watchers

### What is actually happening?
...

**Comment by ganbowengo** [comment]
The subs in watcher should have only two Deps, and now the object type is collected twice

**Comment by posva** [comment]
Please be clear when reporting a bug, talk about expected behaviors in terms of public API. For example, you could say something rendered more than expected or didn't render when it should and provide the corresponding repro.

**Comment by zrh122** [comment]
> The subs in watcher should have only two Deps, and now the object type is collected twice

1. dep for message
2. dep for emptyObj, intend to detect changing when assign it (`this.emptyObj = anotherObject`)
3. dep for rerender when assigning attribute in the emptyObj and `emptyObj.a` is used in template (`Vue.set(this.emptyObj, 'a', 1)`)

so it works as expected. @ganbowengo

**Comment by ganbowengo** [comment]
EmptyObj is only used once in template, but Watcher will think that there are two getter calls, deps in watcher collect dep twice. If the dependency collection method of get method in defineReactive is modified to determine whether there is childOb first and then trigger the depend method of dep, the current unnecessary dep can be obtained. Remove dep from watcher without affecting emptyObj's set and attributes in template calls

Look at the code. You can try it. https://codepen.io/anon/pen/GbBbwJ
@zrh122
