### ISSUE TITLE
inconsistence about data initialization and error checks

### ISSUE THREAD

**Issue by CarterLi** [vuejs/vue#10246]
### Version
2.6.10

### Reproduction link
N/A

### Steps to reproduce
N/A

### What is actually happening?
We use [Object.keys](https://github.com/vuejs/vue/blob/3b8925bc7973bb71b33374281db10a945ca9854e/src/core/instance/state.js#L126) to enumerate data properties but use [operator `in`](https://github.com/vuejs/vue/blob/3b8925bc7973bb71b33374281db10a945ca9854e/src/core/instance/state.js#L202) to check their existence. Since operator `in` also checks for properties on objects' prototype chain, it results in inconsistence when handling special situations especially when the data object is created using [new class](https://github.com/CarterLi/vue-component-base/blob/master/index.ts#L154).

### What is expected?
To be consistent with `initData`, use `hasOwn(vm.$data, key)` [here](https://github.com/vuejs/vue/blob/3b8925bc7973bb71b33374281db10a945ca9854e/src/core/instance/state.js#L201)

**Comment by posva** [comment]
Since keys in data are enumerable and it's a plain js object it shouldn't be a problem. Instead of returning a class in the `data` function, return a plain object with a key to the class.

Please, do not open bug reports without a boiled down repro in the future
