### ISSUE TITLE
this.debouncedGetAnswer is not a function

### ISSUE THREAD

**Issue by milyyy** [vuejs/vue#10256]
### Version
2.6.10

### Reproduction link
[https://cn.vuejs.org/v2/guide/computed.html#%E4%BE%A6%E5%90%AC%E5%99%A8](https://cn.vuejs.org/v2/guide/computed.html#%E4%BE%A6%E5%90%AC%E5%99%A8)

### Steps to reproduce
no step.please check the data 

### What is expected?
the repro defined two data, maybe the word 'debouncedGetAnswer ' should be replaced by  'getAnswer'.

### What is actually happening?
this.debouncedGetAnswer is not a function

**Comment by milyyy** [comment]
it's be resolved.

**Comment by posva** [comment]
Heh if there is a mistake on the docs, could you please open an issue or a pull request on our doc repository? vuejs/vuejs.org

Im reopening and closing this to prevent further spam
