### ISSUE TITLE
Warn when Vue.set is used on a nested property such as propA.propB or probC[0]

### ISSUE THREAD

**Issue by pyskell** [vuejs/vue#10258]
### What problem does this feature solve?
I attempted to do `Vue.set(object, 'attribute.nestedAttribute', value) and rather than setting `object.attribute.nestedAttribute = value` I got an object that looked like: `{attribute.nestedAttribute = value}`.

I had no idea this was even possible within JavaScript and when debugging it in Vue devtools it first took a while to notice what had happened (I initially assumed Vue popped it to the root of my object just to highlight that it changed).

It would be very helpful if a warning could be added for certain reserved characters and keywords that have no business being used/set like this.

### What does the proposed API look like?
No changes to API, just a warning.

**Comment by posva** [comment]
Unfortunately this is valid usage as keys can have dots and brackets so having a warning wouldn't be consistent and it would warn for anybody already using such keys (eg dynamic forms)
