### ISSUE TITLE
Computed property bug

### ISSUE THREAD

**Issue by wenfangcn** [vuejs/vue#10263]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-nursj](https://codesandbox.io/embed/vue-template-nursj)

### Steps to reproduce
Please follow the comments in the code

### What is expected?
Two logs are the same

### What is actually happening?
Two logs aren't the same

**Comment by posva** [comment]
You need to use `$set` 

```js
set(v) {
        this.$set(this.obj, this.activeProp, v);
        console.log({ value: this.value });
      }
```

otherwise it enters in a reactivity caveat (you can look it up in docs for more info)
