### ISSUE TITLE
Entering consecutive decimal points or multiple decimal points in the input tag that using the v-model binding results in null values for the bound variable

### ISSUE THREAD

**Issue by lanzhou2333** [vuejs/vue#10261]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/qzwdLg](https://codepen.io/anon/pen/qzwdLg)

### Steps to reproduce
1.input number 1234 , the next line dispaly the value of rechargeValue = 1234
2.input number 1234. ,the next line dispaly the value of rechargeValue = 1234
3.intpu number 1234.4, the next line dispaly the value of rechargeValue = 1234.4
4.input 1234.. the next line dispaly the value of rechargeValue =
  no display here 
5 input 1234.123.321  no display,the value of recharegeValue is ""
all input above can ben input to the input tag like <input type="number" > correctly.

### What is expected?
the correct result or a exception

### What is actually happening?
when the value of the input tag can't be convert from string(may be) to the number. the variable will be a null value.

**Comment by posva** [comment]
That's how the browser works: when the value is invalid the input's element value is `''`. You can check that by adding

```js
mounted () {
    document.getElementById('input').addEventListener('input', event => {

  console.log('listener', event.target.value)
})
  }
```

If you want to coerce the value, you can use a computed setter to control what values are set

**Comment by lanzhou2333** [comment]
> That's how the browser works: when the value is invalid the input's element value is `''`. You can check that by adding
> 
> ```js
> mounted () {
>     document.getElementById('input').addEventListener('input', event => {
> 
>   console.log('listener', event.target.value)
> })
>   }
> ```
> 
> If you want to coerce the value, you can use a computed setter to control what values are set

thanks
