### ISSUE TITLE
Please let us change default behavior of v-bind!

### ISSUE THREAD

**Issue by Repugraf** [vuejs/vue#10262]
<p>I'm using vee-validate package (to validate forms) and I'm binding the value like this <i><strong>:value="someValue"</strong></i>. The problem is that vee-validate checks only changes of <i><strong>value</strong></i> attribute. The main issue is when <i><strong>someValue</strong></i> is empty then the attribute will not appear at all! That means that the first time user changes input the value sets and only after second change it will be checked by vee-validate.</p>
<p>To fix the issue I had to set the value without v-bind like this: </p>
<p><i><strong>&lt;input type=&quot;text&quot; :name=&quot;someName&quot; value=&quot;&quot; /&gt;</strong></i></p>
<p>And then change the value with pure js</p>

<hr/>
<h2>The behavior I'd like to see:</h2>

<p>
The code: <br>
<i><strong>&lt;input type=&quot;text&quot; :name=&quot;someName&quot; :value=&quot;someValue&quot; /&gt;</strong></i> - the <i><strong>someValue</strong></i> is empty</p>
<p>
The rendered code: <br>
<i><strong>&lt;input type=&quot;text&quot; name=&quot;name&quot; value=&quot;&quot; /&gt;</strong></i>
</p>
<hr/>
<h2>Ideas how to implement it:</h2>
<ul>
<li>Change the behavior of v-bind</li>
<li>Return removed syntax: <i>value="{{someVlaue}}"</i></li>
<li>Add options: <i>v-bind.force:value="someValue"</i></li>
</ul>

**Comment by smolinari** [comment]
Try using `v-model` instead of `value`. 

Scott

**Comment by Repugraf** [comment]
> Try using `v-model` instead of `value`.
> 
> Scott

Hello Scott, thank you for the reply. I've tried it but the result is the same. The value attribute is absent if it's bound to empty value

**Comment by smolinari** [comment]
Can you make a fiddle or a codepen of what you are looking at?

Scott
