### ISSUE TITLE
v-model used in a number input does not accept characters other than numbers

### ISSUE THREAD

**Issue by rellect** [vuejs/vue#10273]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/rellect/ta1mkpnc/](https://jsfiddle.net/rellect/ta1mkpnc/)

### Steps to reproduce
1. Open the repro link
2. Type '1E' in the input
3. See "foo" value is null instead of '1E'

### What is expected?
v-model should match the value in the input

### What is actually happening?
v-model saves the value as null if it contains characters other than numbers

---
 '1E' is a valid number by the html spec.

**Comment by sirlancelot** [comment]
It may be in the spec, and Vue.js may need some re-working, but the input of `1E` seems to be invalid in Chrome. Inspect element on the input box and run `$1.value` and you will see that it is `""` which means the browser rejected the input.

**Comment by posva** [comment]
You should open an issue on Chromium tracker

**Comment by posva** [comment]
Just checked the spec at https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number it does requires at least one number after the `e`, so it should be `1e1`

**Comment by rellect** [comment]
Oh I didn't the value is not changing, I'll do some more research

**Comment by sirlancelot** [comment]
It looks like Vue is working as expected there:
![image](https://user-images.githubusercontent.com/71916/61249620-91d9ea80-a70a-11e9-812b-bcdc1d5e7afa.png)

**Comment by rellect** [comment]
Thanks @posva, seems I didn't fully understood this part of the spec and using the correct format does work. The browser behavior here was unexpected that I was sure it's a v-model issue
