### ISSUE TITLE
The value is changed twice when two-way binding is used

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue#10278]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-3zzp2](https://codesandbox.io/s/vue-template-3zzp2)

### Steps to reproduce
A prepared an example. If you change the value of one component then you can see that computed value set twice (see console).
I know that the event is emitted. But why is the same value set?

### What is expected?
I expect that value set once.

### What is actually happening?
The computed value set twice

**Comment by posva** [comment]
When calling the updateValue method from the Text component and sending the event up, Vue does `valueComp = $event`, which trigger the setter as many times as that piece of code is executed, which is 2 because they are two components, each emitting one event triggering one set
