### ISSUE TITLE
Koeran input trigger keydown event twice

### ISSUE THREAD

**Issue by dl0312** [vuejs/vue#10277]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/0zj6narq/42/](https://jsfiddle.net/0zj6narq/42/)
![Jul-16-2019 19-21-53](https://user-images.githubusercontent.com/3915393/61287017-05f5ba80-a7ff-11e9-9589-adb631a4605a.gif)

### Steps to reproduce
1. type Korean input
2. keydown event like Arrow Up, Down, Left, Right, Enter, Tab ...

### What is expected?
keydown event just triggered once

### What is actually happening?
keydown event just triggered doubled

---
In addition to this bug, there's many bugs related to CJK language
I love Vue but these bugs make me hard to use Vue 😥

**Comment by posva** [comment]
I don't get composition in Korean but I do get it in latin languages and Japanese and I couldn't reproduce the bug. I tried different settings for Korean on OSX but there isn't any composition. It may be related to the software you use, triggering the keydown event twice.

If the problem also appears with plain JS (https://jsfiddle.net/posva/kyjfca39/), you should report the bug to the input software you are using

**Comment by brosbunbo** [comment]
@posva Having this issue as well, please have a more serious look in to it.

Thanks and Best Regards.

**Comment by ramachandran-p** [comment]
facing some issues..any update ?

**Comment by CAT6e** [comment]
Similar issue here, I've got a problem with <input @keydown.enter on Japanese typing. I just press enter to confirm the kana, turns out it triggers as I pressed enter, the value of v-model bound with the input is still empty at the moment.

**Comment by imtherealk** [comment]
I'm also facing the similar issues. 

If I input korean characters:
case 1. Keydown event callback is triggered for twice.
case 2. Keyup event callback is triggered both on keyup and keydown.

These are my codes to reproduce it. (It contains both cases).

```
<template>
  <div>
    <input type="text" 
           v-bind:value="newTodo" 
           v-on:input="updateInput" 
           v-on:keydown.enter="addTodo" <-------------- case 1
           v-on:keyup.enter="addTodo" <-------------- case 2 
    >
    <span class="addContainer" v-on:click="addTodo">
      <i class="fa fa-plus addBtn" aria-hidden="true"></i>
    </span>
  </div>
</template>

<script>

export default {
  data() {
    return {
      newTodo: ""
    }
  },
  methods: {
    addTodo() {
      // this method is called twice
      console.log("keydown event") // <-------------- case 1
      // console.log("keyup event") // <-------------- case 2
    },
    clearInput() {
      this.newTodo = "";
    },
    updateInput(event) {
      this.newTodo = event.target.value;
    }
  }
}
</script>
```
Look at the console log. (Ignore other things)

case 1.
I pressed the Enter key once. But the callback(addTodo) was called twice.
![vue-keydown](https://user-images.githubusercontent.com/16300509/99907732-c65bae80-2d21-11eb-86b9-9bcaf961815a.gif)

case 2.
For testing, I pressed and was holding the Enter key for a while, and then released it. You can see my addTodo function was called on both keydown & keyup.
![vue-keyup](https://user-images.githubusercontent.com/16300509/99908245-d5902b80-2d24-11eb-8155-6ac54f1ccc1b.gif)

fyi. 
You can enable 2-Set Korean input method.
https://macinfo.us/how-to-type-korean-characters-on-your-mac/

**Comment by mochapoke** [comment]
### how to fix:
```js
eventTarget.addEventListener("keydown", event => { 
  if (event.isComposing || event.keyCode === 229)  return; 
  //  ...code..
});
```
if `event.isComposing` is not defined and cause type error,

```js
eventTarget.addEventListener("keydown", event => { 
  if event.keyCode === 229)  return; 
  //  ...code..
});
```
this works fine.

if you can read Korean, here's an [article](https://minjung-jeon.github.io/IME-keyCode-229-issue/) describes why this happens and how to fix.
