### ISSUE TITLE
activated hook does not run in prod mode only dev mode.

### ISSUE THREAD

**Issue by e-lobo** [vuejs/vue#10276]
using typescript and caching with keep-alive..
in dev mode activated() works fine but in prod it doesnt run at all.

**Comment by vius** [comment]
> using typescript and caching with keep-alive..
> in dev mode activated() works fine but in prod it doesnt run at all.

hi i have the same problem，do you resolve the problem

**Comment by e-lobo** [comment]
yes.
in the component i want kept alive include a name in the component
decorator like so
-> @Component({
name:'MYALIVECOMPONENT'
})
then i just used the include prop provided by <keep-alive>
-> <keep-alive include='MYALIVECOMPONENT '></keep-alive>

thats it! =D
