### ISSUE TITLE
Deno support or Deno rewrite pilot program

### ISSUE THREAD

**Issue by inunotaisho26** [vuejs/vue#10274]
# 🚀 feature request
Would like [Deno](https://deno.land/) runtime support.

### Description
This is a new runtime that has was created by [Ryan Dahl](https://en.wikipedia.org/wiki/Ryan_Dahl), the original creator of [NodeJS](https://nodejs.org/en/). It has several new advantages:

- Use of Promises
- Uses TypeScript out of the box
- no need for node_modules
- uses urls to load dependencies (might be a plus or minus).

**Comment by sheecegardezi** [comment]
It would be great if this is considered

**Comment by Soremwar** [comment]
Tools for easing the process of transitioning from Node to Deno promise to greatly speed up this process if this were ever to be implemented
