### ISSUE TITLE
IE11, console print: [Vue warn]: Error in nextTick: "Error: Invalid argument." But work well with chrome

### ISSUE THREAD

**Issue by yasirrose** [vuejs/vue#10285]
### Version
2.6.0

### Reproduction link
[http://ec2-18-207-188-97.compute-1.amazonaws.com/#/garage](http://ec2-18-207-188-97.compute-1.amazonaws.com/#/garage)

### Steps to reproduce
You need to open this link in IE, after that move below the slider and click on add to garage button after that go to garage page in header and then click on remove to garage. When you click on remove to garage then console trigger an error.
 http://ec2-18-207-188-97.compute-1.amazonaws.com/#/

### What is expected?
nextTick is working fine on chrome and firefox but not working on IE 11.

### What is actually happening?
nextTick is not working in IE 11. When DOM is updated it triggered an error in console. Here is the screenshot: http://prntscr.com/ogdz4t

**Comment by posva** [comment]
A repro must be boiled down and editable. This is the URL of your project with a screenshot. The error seems to happen during Vue updating the DOM but I can't tell more.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yasirrose** [comment]
@posva Do you need to codepin or what? How i can share all the code with you?
