### ISSUE TITLE
vue cli3 有什么办法提取css,但是打包不生成css文件

### ISSUE THREAD

**Issue by ChinaMars** [vuejs/vue#10283]
### What problem does this feature solve?
我只想用到js文件，但是写在.vue里的样式会打包到js里，vue cli3有方法提取css，但是我用的是别的框架样式不需要再生成一遍。

### What does the proposed API look like?
extract: false，这样css文件是不生成了，但是会打包到js文件里，我想要的结果是js里的css和css文件都不需要

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
