### ISSUE TITLE
TypeError: undefined is not an object(evaluating 'vm.$scopedSlots')

### ISSUE THREAD

**Issue by yaoguoli** [vuejs/vue#10280]
### Version
2.6.10

### Reproduction link
[https://github.com/yaoguoli/vue-bug](https://github.com/yaoguoli/vue-bug)

### Steps to reproduce
1. find an iphone which ios software version > 12.2 .  My situation is ios 12.3.1 iphoneX

2.  vue-cli 3.9.2  &  clone https://github.com/yaoguoli/vue-bug & npm i & npm run serve

3. use charles to proxy your iphone and  open url http://local.m.immomo.com:8081/ in wechat or safari

4. you will get an alert with "TypeError: undefined is not an object(evaluating 'vm.$scopedSlots')"

### What is expected?
no error happens

### What is actually happening?
An error happens only in ios > 12.2

---
1. parent componet App changes data 'selected' which props to child componets Tab in created hook

2. componets Tab watch 'selected'  immediate: true

3. child componets Test create an iframe Element and append to body in in created hook.

4.  ios 12.3.1

An error will not happen if any of four conditions not set. I'm so confused ! .  It seems create iframe  will fire patch before Test componetInstance set up.

**Comment by posva** [comment]
Tested using https://codesandbox.io/s/vue-template-ehiko on iPhone XS and X 12.3.1 and 11 and cannot reproduce. Can you try reproduce it with a code sandbox?

**Comment by yaoguoli** [comment]
I have tried in codesandbox，but can not reproduce. So I put demo code in github.


Please attempt to reproduce by the steps I have put upstair.


Thank you. It really helpful 


| |
ygl4445
邮箱：ygl4445@163.com
|

Signature is customized by Netease Mail Master

On 07/17/2019 01:13, Eduardo San Martin Morote wrote:

Tested using https://codesandbox.io/s/vue-template-ehiko on iPhone XS and X 12.3.1 and 11 and cannot reproduce. Can you try reproduce it with a code sandbox?

**Comment by posva** [comment]
I cannot reproduce it locally either. Maybe creating the iframe in the specific situation you are triggers a security error on the browser during Vue render but I cannot see the error you should on the screenshot
You should put the code in mounted btw, because it affects only client side code

**Comment by zrh122** [comment]
maybe related to #10029, @yaoguoli

**Comment by rodrigopedra** [comment]
Hi @posva 

I am having the same problem. I'll try to create a fiddle to reproduce it, but I am out of time now.

From the error stack it seems it is triggered when there are multiple nested components, each with immediate watchers, receiving some value through props.

The error only started to appear after I updated to Vue 2.6.10.

Only happens to updated webkit browsers (in my app I could reproduce on the Gnome Web https://wiki.gnome.org/Apps/Web which is webkit based, I am running it in Ubuntu 18.04). But also in my iPad Pro (iPadOS 13 beta) and iPhone 8 (iOS 12.4). 

On my wife's iPhone which runs iOS 11 this error doesn't happen.

Below is the error stack (it might help somehow)

~~~
[Error] [Vue warn]: Error in nextTick: "TypeError: undefined is not an object (evaluating 'vm.$scopedSlots')"
	warn (vue.common.dev.js:630)
	logError (vue.common.dev.js:1889)
	globalHandleError (vue.common.dev.js:1884)
	handleError (vue.common.dev.js:1844)
	(anonymous function) (vue.common.dev.js:1987)
	flushCallbacks (vue.common.dev.js:1911)
	promiseReactionJob
	parseFromString
	sanitizeHtml (bootstrap.js:2702)
	_getConfig (bootstrap.js:3317)
	Tooltip (bootstrap.js:2846)
	(anonymous function) (bootstrap.js:3382)
	each (jquery.js:367)
	bind (tooltip.js:21)
	callHook$1 (vue.common.dev.js:6663)
	_update (vue.common.dev.js:6584)
	updateDirectives (vue.common.dev.js:6565)
	invokeCreateHooks (vue.common.dev.js:6054)
	createElm (vue.common.dev.js:5941)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	patch (vue.common.dev.js:6460)
	_update (vue.common.dev.js:3936)
	updateComponent (vue.common.dev.js:4057)
	get (vue.common.dev.js:4468)
	Watcher (vue.common.dev.js:4457)
	mountComponent (vue.common.dev.js:4064)
	init (vue.common.dev.js:3121)
	createComponent (vue.common.dev.js:5963)
	createElm (vue.common.dev.js:5910)
	patch (vue.common.dev.js:6460)
	_update (vue.common.dev.js:3936)
	updateComponent (vue.common.dev.js:4057)
	get (vue.common.dev.js:4468)
	Watcher (vue.common.dev.js:4457)
	mountComponent (vue.common.dev.js:4064)
	init (vue.common.dev.js:3121)
	createComponent (vue.common.dev.js:5963)
	createElm (vue.common.dev.js:5910)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	patch (vue.common.dev.js:6460)
	_update (vue.common.dev.js:3936)
	updateComponent (vue.common.dev.js:4057)
	get (vue.common.dev.js:4468)
	Watcher (vue.common.dev.js:4457)
	mountComponent (vue.common.dev.js:4064)
	init (vue.common.dev.js:3121)
	createComponent (vue.common.dev.js:5963)
	createElm (vue.common.dev.js:5910)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	createChildren (vue.common.dev.js:6038)
	createElm (vue.common.dev.js:5939)
	patch (vue.common.dev.js:6499)
	_update (vue.common.dev.js:3936)
	updateComponent (vue.common.dev.js:4057)
	get (vue.common.dev.js:4468)
	Watcher (vue.common.dev.js:4457)
	mountComponent (vue.common.dev.js:4064)
	init (app.js:133)
~~~

By the way, my app does not have any iframe as suggested in the #10029  and I tested in those browsers without any extensions.

When trying to debug this particular app I found that, in my case, if I remove a custom directive I wrote the error does not happer. This directive adds the Bootstrap's tooltip plugin to a label element in a component:

~~~js
import Vue from 'vue';
import jQuery from 'jquery';

Vue.directive('tooltip', {
    bind(element, {value = 0}) {
        const delay = Number.isSafeInteger(value) ? value : 0;

        jQuery(element).tooltip({trigger: 'hover', delay: {show: delay, hide: 0}});
    },

    update(element, {value = 0}) {
        const delay = Number.isSafeInteger(value) ? value : 0;

        const $element = jQuery(element);
        $element.tooltip('dispose');
        $element.tooltip({trigger: 'hover', delay: {show: delay, hide: 0}});
    },

    unbind(element) {
        jQuery(element).tooltip('dispose');
    },
});
~~~

I don't know if somehow a event listener is added that breaks the watchers.

I use the same very directive in other projects where I am not facing this problem.

Please let me know if I can help in anyform.

**Comment by posva** [comment]
@rodrigopedra if you manage to provide a boiled down repro with the browser and its version to reproduce, please open a new issue

**Comment by bradley-varol** [comment]
Also seeing in Sentry for Mobile Safari 15.0, iOS 15.0.1.
