### ISSUE TITLE
How to clean HTML code from extra spaces?

### ISSUE THREAD

**Issue by afuno** [vuejs/vue#10281]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/chrLg4uk/](https://jsfiddle.net/chrLg4uk/)

### Steps to reproduce
1. Write a simple component that I attached.
2. In the HTML code you will see that there are spaces before and after the text.

### What is expected?
I want to remove these spaces. I can not imagine how you can write an HTML tag and a variable on one line. Especially when a lot of classes and other attributes.

### What is actually happening?
Cannot remove extra spaces. Need to write a variable on a single line with an HTML tag.

**Comment by posva** [comment]
You probably want to write `<span>{{ message }}</span>`

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by afuno** [comment]
@posva That is, I need to wrap all the variables?

**Comment by posva** [comment]
If you don't want extra space, yes, that's how HTML work:

```html
<span>Some text</span>
```

is different from

```html
<span>
  Some Text
</span>
```

**Comment by afuno** [comment]
@posva Your way works. Thank.

**Comment by afuno** [comment]
@posva This problem can also be solved, for example, by going to pug?

**Comment by posva** [comment]
You could, I wouldn't use pug personally. Anyway, please ask questions in the forum or chats 🙂
