### ISSUE TITLE
Cannot read property '_isDestroyed' of undefined"

### ISSUE THREAD

**Issue by Ystr4** [vuejs/vue#10295]
### Version
2.6.10

### Reproduction link
[https://github.com/Ystr4/is_destroyed_error](https://github.com/Ystr4/is_destroyed_error)

### Steps to reproduce
To get the error, click on button: "doesn't work", a few times.

### What is expected?
To get an error if a component fails to render

### What is actually happening?
Trying to cleanup something that doesn't exist

---
Hi,
I'm rewriting an old barebones javascript frontend using Vue.js.
Allot of the content of the site is created with a custom tool which outputs an array of objects for the nodes. 
I'm using render functions to build the HTML templates out of that. Some of the components have allot of logic in them and are just container around simple html elements.

This seems to be working fine for most template, but on some of the templates I get this error in the destroy cycle when the :key gets updated (i.e load a different template). 

Depending where i put the :key i get different error messages but they are all duo to the instance being undefined.

Does this have something to do with how I create the parent/child hierarchy by assigning directly to children on the VNode, or mixing functional components with non functional? 

Any suggestions are welcome. Cheers.

**Comment by posva** [comment]
Hey, this is too much for a repro. Can you provide a boiled down without all the custom format data and showing only the part that creates the bug? You can also use https://codesandbox.io/s/vue to share it quicker

**Comment by Ystr4** [comment]
Hi, thanks for the quick response.
I boiled it down some more, I hope this version you can work with.
Changing where i put the :key seems to have an impact on the type of error message i get, but they are all duo to the instance being undefined.
Let me know if I can provide any more info.
Thanks

**Comment by posva** [comment]
I gave it another look, you are manually setting `children` on a vnode instead of providing it as a 3rd argument when calling `createElement`:

```js
    const child_L1 = createElement(
      context.props.tag,
      {
        key: context.props.createdAt, // L1 key
        props: {
          tag: "div"
        }
      },
      [
        createElement(context.props.tag, {
          // key: context.props.createdAt,     // L2 key
          props: {
            tag: "h1",
            text: context.props.value
          }
        })
      ]
    );
```

After doing that you also need to pass down the children in both components:

```js
// non functional
createElement(this.tag, data, this.$slots.default);
// functional
createElement(context.props.tag, data, context.children);
```

You can find more about the syntax at https://vuejs.org/v2/guide/render-function.html

**Comment by Ystr4** [comment]
Great, that works, 
I've been stuck on this for days. What was confusing to me was that the components actually showed up on the screen without any errors, only after an update cycle the error appeared.
I had to change some tings around. One component with a switch(functional without the context.children) decided which component to create, only returning a single VNode to add to the children[], don't really like that i have to map the children there as well, just to satisfy the API, but no errors now. Thanks for your time. Good day.
