### ISSUE TITLE
get $_lingWeChatSign_num is undefined

### ISSUE THREAD

**Issue by LingRen** [vuejs/vue#10293]
### Version
2.6.10

### Reproduction link
[https://jsbin.com/gesuzod/edit](https://jsbin.com/gesuzod/edit)

### Steps to reproduce
In the data, define a variable $_lingWeChatSign_num, but get is undefined, there is no question of using other variable name

### What is expected?
Normal display, can get to the value

### What is actually happening?
in console, ReferenceError: $_lingWeChatSign_num is not defined

**Comment by posva** [comment]
Please check https://vuejs.org/v2/api/#data

Because the variable starts with a `$`, you must reference it through `$data.$yourProperty`

**Comment by LingRen** [comment]
maybe i should sleep
