### ISSUE TITLE
Dynamic input with component doesn't update UI

### ISSUE THREAD

**Issue by Stegosource** [vuejs/vue#10290]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-hi3gb](https://codesandbox.io/s/vue-template-hi3gb)

### Steps to reproduce
Create an input component with the <component /> tag, and bind the value and input events for data updates:
<component :is="'input'" :value="text1" @input="text1 = $event.target.value"/>

Edit the input value manually and you can confirm the data is being updated.

Programatically change the data and everything depending on the data will update including the "value" of the input, but the visual UI for the input will still show the old data.

### What is expected?
If I clear the data programmatically, the input should also clear

### What is actually happening?
Clearing the data functionally works, but visually leaves the previous data as the input value.

**Comment by posva** [comment]
Use `value.prop` because it's a dynamic component

**Comment by Stegosource** [comment]
Thanks @posva. I might update the docs somewhere. Do you know where I should do that?
