### ISSUE TITLE
[SSR] SyntaxError: Unexpected token export， babel-loader 已经编译 node_modules 中的 es6 文件

### ISSUE THREAD

**Issue by JackFGreen** [vuejs/vue#10294]
### Version
2.6.10

### Reproduction link
[https://github.com/JackFGreen/vue-ssr-demo](https://github.com/JackFGreen/vue-ssr-demo)

### Steps to reproduce
1. yarn build && yarn prod
2. http://localhost:3000/
3. logs/app.log

### What is expected?
调用 vendors 中编译后的 demo-lib

### What is actually happening?
调用了 node_modules/demo-lib 中的 es6 源码

![image](https://user-images.githubusercontent.com/23187848/61522019-10ed5c80-aa44-11e9-845c-4505be16293d.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
