### ISSUE TITLE
与原生标签名称冲突时，如果组件存在，优先作为组件解析；至少 SVG 标签名检测不应该不区分大小写

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10291]
### What problem does this feature solve?

目前的 Vue 引擎的机制是，如果标签名和浏览器原生元素同名，那么无论是否存在这个组件，都作为原生元素对待。

这就意味着为组件起名字时，要记忆和回避所有已经存在的原生元素名。

Vue文档中建议，自定义组件中应当包含 `-`，这样就不会冲突了。但是实践中，刻意总是把一个直观的单词变成两个单词是非常难受的。

好在后来的 Vue 实现了大驼峰组件名，并推荐这种做法。这样就不用管黑名单了，可以根据语义自由设置最佳的组件名。

但是最近发现，一旦与 SVG 全家桶同名，那么无论是否大小写，都会无效：
```js
new Vue({
    template: '<LiNe />',// 这个不会被作为组件对待
    components: {
        LiNe: {
            template: '<div>LiNe</div>'
        },
    },
});
```

而这个清单很长，又没什么规律，还都是常用单词，而且 SVG 标签并不是常用标签，前端工程师对此不熟悉是很正常的，文档中也没有提醒，中间甚至还有包含 `-` 和大写字母（好在不是首字母）的标签名：
```
svg,animate,circle,clippath,cursor,defs,desc,ellipse,filter,font-face,
foreignObject,g,glyph,image,line,marker,mask,missing-glyph,path,pattern,
polygon,polyline,rect,switch,symbol,text,textpath,tspan,use,view
```

这就意味着写 Vue 时，要么面向黑名单编程，要么就要放弃无脑大驼峰的便利，一律用 `-` 写组件名（而且还要回避 `font-face` 和 `missing-glyph`）。

更糟糕的是，可以想见，一旦未来 MathML 全家桶外来元素清单生效，按照目前的机制，会打破很多已有的 Vue 组件兼容，对引擎开发者同样是个历史包袱。

### What does the proposed API look like?

将这里的第二个参数 `, true` 去掉，使得 SVG 内置标签名检测行为大小写敏感：

https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/platforms/web/util/element.js#L31

当然更期待的做法是，无论标签名是什么，都优先检查组件是否存在，不存在才作为浏览器原生元素对待。

**Comment by posva** [comment]
Not only this would be a breaking change but it goes against the guidelines defined in the style guide. The whole idea of using multiple words is to not have to deal with new elements introduced in the future. Having a component named `Line` is completely missing its context. You can also keep it short by using a one letter prefix like Vuetify does with `v`. For example, it could be `t-line` for a ThreeJS Line or `p-line` for Pixi
