### ISSUE TITLE
当component绑定key时，keep-alive的max存在问题

### ISSUE THREAD

**Issue by waldonUB** [vuejs/vue#10297]
### Version
2.6.10

### Reproduction link
[https://codepen.io/waldonUB/pen/PMqXdr](https://codepen.io/waldonUB/pen/PMqXdr)

### Steps to reproduce
1. 点击第二个tem1按钮，将key值切换到 b
2. 点击temp2，将key值切换到 c

### What is expected?
因为max设置为2，所以到第3个key值时，key值为a的temp1组件应该被销毁

### What is actually happening?
到了第三个key值的时候没有key值为a的temp1组件没有被销毁，而是到了第四个key值的时候才被销毁

---
#### 使用场景
- 我需要对话框来缓存数据，但是很多对话框是相同的组件，以不同的编码来查询不同的数据
- 以编码作为key值绑定在component上缓存组件，避免重新打开时再次查询
- 加上max属性，防止内存溢出

#### 绑定key时，max存在的问题
- 当同一个组件有多个key绑定时，当key的数量 >= max的值，max将会缓存相同的key，不会触发生命周期中的destroyed函数  
![image](https://github.com/waldonUB/imageSave/blob/master/maxTest.png)

#### 以往类似的issue
- https://github.com/vuejs/vue/issues/6509

**Comment by posva** [comment]
Please check https://github.com/vuejs/vue/issues/8028
Components are cached based on their name right now so temp1 with key a and temp1 with b will use the same cache spot and override each other

**Comment by waldonUB** [comment]
> Please check #8028
> Components are cached based on their name right now so temp1 with key a and temp1 with b will use the same cache spot and override each other

Thank you very much for your answer.I found in the implementation source code of ``max`` that ``cache[key] = null`` is used when components are cleared, and the cache's key is the key bound in component. I guess it should be a plan reserved at the beginning.
![](http://ww1.sinaimg.cn/large/00760Iw1gy1g58dn4iyinj30r80dbgnq.jpg)  
Here is my simple implementation:  
https://codepen.io/waldonUB/pen/PMqXdr  
It meets my expectations, but I don't know if there will be any unexpected mistakes.If there is any shortage, I hope it can be corrected
