### ISSUE TITLE
Can't reuse data object in createElement

### ISSUE THREAD

**Issue by Grovespaz** [vuejs/vue#10303]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/dxGVOg?editors=1010#0](https://codepen.io/anon/pen/dxGVOg?editors=1010#0)

### Steps to reproduce
In your render function, create two distinct elements (with two separate createElement calls), but with the same data object specifying an event listener.

### What is expected?
When the event is triggered from the *second* child component, it should fire the appropiate handler.

### What is actually happening?
Nothing

---
I am aware of the constraints section here: https://vuejs.org/v2/guide/render-function.html#Constraints but it doesn't seem to specifically mention re-use of just the data-object.

If this restriction is known and meant to be then this issue is about properly documenting this limitation.

**Comment by posva** [comment]
It makes sense not to duplicate the object internally to improve performance, so i would say it should be documented. Could you open a PR on the documentation repo please? vuejs/vuejs.org
