### ISSUE TITLE
Facilitate debugging in template

### ISSUE THREAD

**Issue by btoo** [vuejs/vue#10305]
### What problem does this feature solve?
Debugging from template code is frustratingly impractical because you lose access to the conventional tools available to you in plain javascript. The reference to the `console` is missing because it is not in the scope of the component instance. Yes, you can add it to the component instance or even the global Vue prototype, but to have to do this every time you need to debug, and then remove for the sake of keeping your code clean, is needlessly tedious. 

Additionally, the `debugger` keyword (for example within an in-template IIFE) is barely of any use because the compiled variables do not match those of the component instance.

This has been an issue for me for a while now, but I was more forgiving of it because how incredible Vue otherwise is. However, I recently noticed that [Svelte.js offers a pretty nifty OOTB feature for debugging in templates](https://svelte.dev/docs#debug).

From their docs:
> The {@debug ...} tag offers an alternative to console.log(...). It logs the values of specific variables whenever they change, and pauses code execution if you have devtools open.
> 
> It accepts a comma-separated list of variable names (not arbitrary expressions).
> 
> The {@debug} tag without any arguments will insert a debugger statement that gets triggered when any state changes, as opposed to the specified variables.

Is there any way we can bring this into Vue template syntax?

### What does the proposed API look like?
```
<template>
  <div>
    {{ @debug }}
    or
    {{ @debug var1, var2, ..., varN }}
  </div>
</template>
```

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/9333
