### ISSUE TITLE
windows上打包结果和linux上打包结果不一样

### ISSUE THREAD

**Issue by tonghao12** [vuejs/vue#10309]
### What problem does this feature solve?
1.路由懒加载在windows上打包的结果，根据组件分包
2.相同的环境下和相同的代码（通过npm install），在linux服务器上打包的结果，不会根据组件分包，全部都会打在一个js文件里
项目马上要上线，如果打的包过大，会导致首屏显示过慢，影响用户体验
这是为什么呢？

### What does the proposed API look like?
是否在linux下npm instal下来的包会跟windows不一样，导致这个问题？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
