### ISSUE TITLE
Click handlers do not work on all UXP applications

### ISSUE THREAD

**Issue by g4jc** [vuejs/vue#10306]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/pzumygcq/](https://jsfiddle.net/pzumygcq/)

### Steps to reproduce
* Download and install any UXP application (Pale Moon, Basilisk, and others).
* Click on show button (this is important, click handlers work if they are bound when currentFlushTimestamp is 0).
* This will show a second button, this button will increment the count variable every time it is clicked, except for UXP applications.

### What is expected?
count variable will increment

### What is actually happening?
Click handler is not firing.

---
Several sites in production are not working properly on [Pale Moon](https://www.palemoon.org/), and by extension, all other applications currently being built on the [Unified XUL Platform](http://thereisonlyxul.org/).

I was able to trace this issue back to #9446. Since the string hack only identifies the FireFox Useragent it does not properly send UXP applications down the correct path.

Short-term, `Goanna` could be used as an identifier which will work for Pale Moon and Basilisk. However, a better implementation would be to test if the `event.timeStamp` is returning the correct values, if yes proceed, if note continue down the FF52 path that was introduced as a bug fix in Issue #9446.

Since multiple applications are using UXP, Goanna is not a consistent identifier aside from Pale Moon and Basilisk.

**Comment by posva** [comment]
The reason we introduced that fix is because it was on an outdated version of FF that was in our range of supported browsers. Pale Moon isn't (this is also the first time I ever see this project) and the timeStamp bug should be fixed in the browser. That being said, if someone is up to contribute a fix by using the user agent for it, they can submit a PR

**Comment by posva** [comment]
Closing as this seems to be fixed in dev: https://github.com/gamejolt/issue-tracker/issues/1316#issue-473077524

**Comment by g4jc** [comment]
Yes, this issue was resolved in Vue.js. Thank you!
