### ISSUE TITLE
Setting 「include=""」 on keep-alive causes components to be cached

### ISSUE THREAD

**Issue by Pasoul** [vuejs/vue#10313]
### Version
2.5.20

### Reproduction link
[https://codepen.io/py419569317/pen/EqywvW](https://codepen.io/py419569317/pen/EqywvW)

### Steps to reproduce
1.  add 「include=""」to `keep-alive` like this:
```
<keep-alive include="">
      <router-view></router-view>
</keep-alive>
```
2. it will causes components caching by mistake，to that triggered `activate` function

### What is expected?
components won't be cached

### What is actually happening?
every components will be cached

**Comment by Pasoul** [comment]
i found the code in "src/core/components/keep-alive.js":

`(include && (!name || !matches(include, name)))` will always return `false`
```
if (
        // not included
        (include && (!name || !matches(include, name))) ||
        // excluded
        (exclude && name && matches(exclude, name))
      ) {
        return vnode
}
```

**Comment by posva** [comment]
This behavior makes sense, as an empty include is like not specifying an include, so everything gets cached
