### ISSUE TITLE
box-shadow style binding does not work in Safari

### ISSUE THREAD

**Issue by Flyrell** [vuejs/vue#10322]
It looks like the Vue.js is unable to bind the `box-shadow` property within the style attribute in Safari. I already mentioned this on the official [forum](https://forum.vuejs.org/t/binding-box-shadow-style-doesnt-work-on-safari-12/68942, but it didn't get much attention.

```javascript
<div :style="{ 'box-shadow': '0 -1px 0 inset #333333' }"></div>

// Chrome (v75.0.3770)
// <div style="box-shadow: rgb(51, 51, 51) 0px -1px 0px inset"></div>

// Safari (v12.1.1)
// <div></div>
```

Here's the working fiddle: https://jsfiddle.net/a16gnsmv/

**Comment by posva** [comment]
That syntax is not supported on Safari. You can add it manually on the devtools and you will see an error
