### ISSUE TITLE
box-shadow style binding does not work in Safari

### ISSUE THREAD

**Issue by Flyrell** [vuejs/vue#10323]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/a16gnsmv/](https://jsfiddle.net/a16gnsmv/)

### Steps to reproduce
Bind the style attribute on any HTML element with the `box-shadow` property. In Chrome & Firefox, it's bound correctly however in Safari it isn't bound at all.

```html
<div :style="{ 'box-shadow': '0 -1px 0 inset #333333' }"></div>

<!-- Chrome (v75.0.3770) -->
<div style="box-shadow: rgb(51, 51, 51) 0px -1px 0px inset"></div>

<!-- Safari (v12.1.1) -->
<div></div>
```

### What is expected?
The expected behaviour would be the `box-shadow` property bound in the style attribute to the HTML element in Safari.

### What is actually happening?
The box-shadow property is not taken into consideration while rendering the template.

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/10322#issuecomment-516292075
