### ISSUE TITLE
Vue.JS Cache Refresh if there's new update in production

### ISSUE THREAD

**Issue by ethlyseria** [vuejs/vue#10329]
### What problem does this feature solve?
Good day,

I'm trying to find a solution if there's a package or practice on implementing cache refresh whenever I release a new version in the production. Any help please?

### What does the proposed API look like?
Good day,

I'm trying to find a solution if there's a package or practice on implementing cache refresh whenever I release a new version in the production. Any help please?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
