### ISSUE TITLE
ios10.3.3 vue2.6.10 vue-router push方式跳转至页面b，b页面引用的自定义组件的slot内容无法触发外层容器绑定的touchstart事件

### ISSUE THREAD

**Issue by wxkcoder** [vuejs/vue#10336]
### Version
2.6.10

### Reproduction link
[https://github.com/wxkcoder/bugs_demo](https://github.com/wxkcoder/bugs_demo)

### Steps to reproduce
在ios10.3.3 浏览器safiri环境下运行 vue版本2.6.10 vue-router版本3.0.6
1.页面a通过this.$router.push 的方式跳转到页面b  
2.页面b引用的一个自定义组件c
 页面b代码
```
<style scoped>
.content{
  height: 2rem;
  background: #cccccc;
  font-size: 0.4rem;
}
</style>
<template>
  <bug1com>
    <div class="content">我是slot部分 无法触发父级的touchstart事件</div>
  </bug1com>
</template>
<script>
import bug1com from '../../components/bug1com'
export default {
  data () {
    return {
    }
  },
  components: {
    bug1com
  }
}
</script>

```
自定义组件c代码
```
<style>
  .box{
    padding: 0.2rem 0.2rem 2rem;
    background: #42b983;
    font-size: 0.4rem;
  }
</style>
<template>
  <div class="box" @touchstart="onTouchStart">
    我是组件盒子部分 绑定了touchstart事件 触发时间：{{txt}}

    <slot></slot>
  </div>
</template>
<script>
export default {
  data () {
    return {
      txt: ''
    }
  },
  methods: {
    onTouchStart (e) {
      this.txt = new Date().getTime()
    }
  }
}
</script>

```

点击 slot的内容 无法触发 外层盒子的touchstart事件

但是 直接访问该页面的话 可以触发

然后将vue版本 切到2.5.22后 无此问题

注：只在ios10.3.3版本 发现有这个问题 其他手机型号暂未发现

### What is expected?
点击 slot的内容可以触发 外层容器的touchstart事件

### What is actually happening?
不触发

---
ios 10.3.3版本

**Comment by posva** [comment]
Your repro doesn't even run and it's using old versions of Vue and Vue router...

The problem you are seeing is probably related to this: https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

**Comment by wxkcoder** [comment]
@yyx990803 帮忙看下这个bug 上面那哥们好像是看不懂中文

**Comment by posva** [comment]
You know I can use a translator and see what you write, don't you? 🙄🤦‍♂️
Anyway, this is a duplicate of https://github.com/vuejs/vue/issues/9340, you should be able to find even more info there. Cheers

**Comment by wxkcoder** [comment]
@posva 
The translated content may not be the same as what I want to express.
Let me describe it again in English.
vue version：2.6.10
ios version：10.3.3
use safiri mobile browser

page A use 'this.$router.push({name:B})' Jump to Page B
Page B import component C
Component C bind a touchstart event 
the problem is Component C use slot label Input content，click that content is dose not trigger C's touchstart event

chenage vue version to 2.5.22 It won't happen.

**Comment by wxkcoder** [comment]
I'm so sorry，I said it wrong，this bug is runing in wxchat webview not safiri
