### ISSUE TITLE
ios下，定义一个空对象{}，，输入框双向绑定这个对象，如果当前页面用了定时器，输入框输入的时候会被清空

### ISSUE THREAD

**Issue by pumpkindev** [vuejs/vue#10335]
### Version
2.6.10

### Reproduction link
[https://jsbin.com/wakinen/edit?html,css,output](https://jsbin.com/wakinen/edit?html,css,output)

### Steps to reproduce
代码如下
```
<template>
  <div class="hello">
    <div>
      <button @click="click">哈哈{{time}}</button>
      <br />
      <input v-model="data.a" />
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      data: {},
      time: 0
    };
  },
  mounted() {},
  methods: {
    click() {
      this.time = 100;
      const a = setInterval(() => {
        this.time--;
        if (this.time <= 0) clearInterval(a);
      }, 1000);
    }
  }
};
</script>


```
1.点击运行定时器
2.ios默认输入法，在输入框输入中文，输入的东西会被清空掉
###环境：微信浏览器，ios手机，只有第一次进入页面才会有这种情况

### What is expected?
定时器触发数据变化的时候不要清空输入框

### What is actually happening?
ios下，点击按钮之后在输入框输入中文会被清掉，只有第一次会出现这种情况

**Comment by posva** [comment]
I created the actual repro from the code and tested on IOS using a Chinese keyboard, it works properly https://jsbin.com/bumazivavi/edit?html,js,console,output, it doesn't reset while _composing_

Please, next time take the time to provide a runnable repro like the one I created

**Comment by pumpkindev** [comment]
悲伤，在这个在线工具上是好的，手动构建的vue项目，用微信浏览器100%会出现这个问题

**Comment by pumpkindev** [comment]
![y5qfl-c6ko7](https://user-images.githubusercontent.com/21173134/62288701-8bc86580-b48f-11e9-9994-80f1ae123fe1.gif)
