### ISSUE TITLE
v-model doesn't work for me

### ISSUE THREAD

**Issue by david27alves** [vuejs/vue#10333]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/mhy1oqed/2/](https://jsfiddle.net/mhy1oqed/2/)

### Steps to reproduce
Use v-model

### What is expected?
Use v-model

### What is actually happening?
I'm starting on vue

---
I don't know if I'm doing something wrong, I tested it using the site examples but it didn't work.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by david27alves** [comment]
All good thank you so much.
