### ISSUE TITLE
Shorthand component imports

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue#10334]
### What problem does this feature solve?
Reduces time consuming boilerplate when using/importing Vue components.

### What does the proposed API look like?
```vue
<script>
	export default {
		components: {
			Widget: '@/components/Widget.vue'
		}
	};
</script>
```
https://v2.svelte.dev/guide#shorthand-imports

**Comment by posva** [comment]
Thanks for the proposal but this is too much magic. It could be implemented as a custom loader for webpack or a plugin but this is something that should go in userland

**Comment by franciscolourenco** [comment]
Vue is full of magic. What is the criteria used to decide if something is too much magic or not?

**Comment by kinow** [comment]
I think what he meant is that that would be putting too much responsibility on Vue, and it would be better handled by users in their code (easier to maintain, and avoid adding too much features to Vue, which could make it harder to move forward).

**Comment by Justineo** [comment]
@franciscolourenco Svelte is a compiler and it actually transforms JavaScript code and modifies its original semantics. On the other hand, it has always been just plain JavaScript inside Vue components' `<script>` blocks. So I think your request would be better answered with a custom webpack loader, as @posva pointed out.

**Comment by franciscolourenco** [comment]
I didn't mean this should be implemented in Vue core. webpack-vue-loader or some plugin part of the vue-cli repository can be  be better places. The Vue org maintains some of these plugins but I don't have the best overview of all the projects and plugins. It still sounds like a useful API which reduces boilerplate and would be cool to see it as a standard option.
