### ISSUE TITLE
Clickjaking vulnrability

### ISSUE THREAD

**Issue by asiffarabi0000** [vuejs/vue#10347]
### Version
2.6.10

### Reproduction link
[https://vuejs.org](https://vuejs.org)

### Steps to reproduce
code :

```html
<html>
   <head>
     <title>Clickjack test page</title>
   </head>
   <body>
     <p>Website is vulnerable to clickjacking!</p>
     <iframe src="https://vuejs.org" width="500" height="500"></iframe>
   </body>
</html>
```

save it with html extension and open it with chrome. you can see website load with fram.

### What is expected?
fix this bug

### What is actually happening?
clickjaking can be dengerious.

**Comment by posva** [comment]
> you can see website load with fram.

Yeah, that's pretty much the point of the working behavior of an iframe.

You are not saying where the clickjacking vulnerability is and the information you are giving is not enough for use to do anything. BTW, the repository for docs is at vuejs/vuejs.org, but make sure to give enough information about the problem when opening the issue please
