### ISSUE TITLE
一个Vue关于slot的严重性能问题

### ISSUE THREAD

**Issue by karmiy** [vuejs/vue#10340]
### Version
2.6.6

### Reproduction link
[https://vue.ant.design/](https://vue.ant.design/)

### Steps to reproduce
例如：
父组件home，它有data如text，在template的随便一个地方{{text}}
子组件test是:
Vue.component('Test', {
    name: 'Test',
    render: function (createElement) {
        console.log(9);
        return createElement('h1', '1')
    }
})

这时我们在home这个组件里，使用<test></test>这个组件，在项目中会在控制台看到打印了9，没什么问题。
当尝试去改变home的text这个data时，控制台也没有任何输出，<test></test>没有重新去渲染render，很好。
但是接下来一个改变问题就来了：
将<test></test>改成<test>1111111</test>
再尝试去改变home的text这个data，奇怪的事情发生了，控制台随着text改变，也一直输出9，意味着<test>不断在重新渲染！！(可是人家text改变和它没有任何关系呀。。)
可是<test>没有 传任何props，slot位置也只是个普通字符串111111，没有改变，却因为毫不相关的text导致一直重新渲染
这在高频率text变化时，造成了很严重的性能问题。
这是在我用Vue开发Markdown编辑器，文本不断变化时发现的问题，组件里与文本无关的如<nz-button>按钮<nz-button>这种中间有slot内容的不断在重复渲染，在编辑器快速触发改变文本时任何带有slot内容的组件都在不断重新渲染导致页面性能问题非常严重
一直找不到合适的解决方案，因为在用antd的组件库，改组件是用jsx形式去写vue组件库的，学习了代码后发现有的组件render部分有的逻辑比较复杂，这样高频率的触发render对性能影响太大。。。。求指教，非常感谢！

### What is expected?
希望可以解决这个slot内容没有改变，却不断重新渲染的问题

### What is actually happening?
无用的无限高频率重新渲染

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. In this case, please provide a boiled reproduction when reporting a bug
Thanks!

**Comment by ChinaJoy025** [comment]
2025年了, 问题依然存在
