### ISSUE TITLE
$attrs引发的严重渲染性能问题？

### ISSUE THREAD

**Issue by karmiy** [vuejs/vue#10345]
### Version
2.6.6

### Reproduction link
[https://codepen.io/karmiy/pen/pMWVOX](https://codepen.io/karmiy/pen/pMWVOX)

### Steps to reproduce
例如：
父组件app，它有data如text，在template的随便一个地方&lt;input type='text' v-model='text'&gt;{{text}}

子组件logger是:
Vue.component('logger', {
  props: {
    type: {
      type: String,
      default: 'default',
    }
  },
  render(createElement) {
    console.log(9);
    return createElement('h1', '1');
  }
});
这时我们在app这个组件里，使用这个组件<logger type='primary'></logger>，在项目中会在控制台看到打印了9，没什么问题。

当尝试去改变input的值来驱动text这个data改变时，控制台也没有任何输出，没有重新去渲染render，很好。

但是接下来一个改变问题就来了：

将logger组件改为:
Vue.component('logger', {
  props: {
    type: {
      type: String,
      default: 'default',
    }
  },
  render(createElement) {
    console.log(9);
    const {$attrs} = this; // there!!!!!!!!!!!!!!!
    return createElement('h1', '1');
  }
});

再次重新去改成text的值，会发现控制台随着text的改变，一直在输出9,

可是text的改变与$attrs没什么关系，怎么会导致logger组件重新渲染呢？？

这样再与之无关的text高频率改变时，会知道logger组件高频率的render，造成性能问题

### What is expected?
$attrs不应该造成毫不相关的render

### What is actually happening?
$attrs造成毫不相关的render

**Comment by karmiy** [comment]
试了下,给logger组件绑定@click，render中接收$listeners也同样，在毫不相关的数据改变时组件不断render

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/10346#issuecomment-517993593
