### ISSUE TITLE
Custom Components slot content dose not trigger parent‘s touchstart event

### ISSUE THREAD

**Issue by wxkcoder** [vuejs/vue#10348]
### Version
2.6.10

### Reproduction link
[https://github.com/wxkcoder/bugs_demo](https://github.com/wxkcoder/bugs_demo)

### Steps to reproduce
vue version：2.6.10
ios version：10.3.3 or 11.4
use safiri mobile browser

page A use 'this.$router.push({name:B})' Jump to Page B
Page B import component C
Component C bind a touchstart event
the problem is Component C use slot label Input content，click that content is dose not trigger C's touchstart event

Direct access to page B  can trigger C‘s touchstart event
change ios version to 12.3.1 can trigger C‘s touchstart event
change vue version to 2.5.22 can trigger C‘s touchstart event

### What is expected?
trigger C's touchstart event

### What is actually happening?
 no trigger C's touchstart event

**Comment by posva** [comment]
As I already said, this is a consequence for the changes in 2.6 https://github.com/vuejs/vue/issues/9340

The current behavior makes more sense though, as touchstart would trigger after the click in most situations but the delay in Safari that allows them to know if it is a double tap may have this working for you in the past

**Comment by wxkcoder** [comment]
How to solve this problem? Can only use a low version of vue?

**Comment by posva** [comment]
I don't know what you were trying to do initially but maybe you could bind a `created` event. In any case, that would be a question in the forum or somewhere else but not in issues, thank you

**Comment by wxkcoder** [comment]
Reproduction link did you looked？

**Comment by wxkcoder** [comment]
https://github.com/wxkcoder/bugs_demo  Have you seen this example?

**Comment by sodatea** [comment]
I've checked your repository on an iPad with iOS 11.0.2 (that's the oldest iOS device I can found). It worked as expected.
And, Your reproduction repo used vue 2.5.22 and I have to manually install 2.6. Have you actually tried it yourself?

Please, next time, do provide a valid reproduction.

**Comment by wxkcoder** [comment]
> I've checked your repository on an iPad with iOS 11.0.2 (that's the oldest iOS device I can found). It worked as expected.
> And, Your reproduction repo used vue 2.5.22 and I have to manually install 2.6. Have you actually tried it yourself?
> 
> Please, next time, do provide a valid reproduction.

thanks for your test，I have changed the version number of the project.
I haven't run this project on the iPad
I run this project on the iPhone 6 plus，ios version 10.3.3

**Comment by sodatea** [comment]
Still can't reproduce on an iPhone 6 simulator with iOS 10.3

**Comment by wxkcoder** [comment]
> Still can't reproduce on an iPhone 6 simulator with iOS 10.3

Do you have a wxchat or email？i can send you a reproduce video

**Comment by wxkcoder** [comment]
I'm so sorry，I said it wrong，this bug is runing in wxchat webview

**Comment by sodatea** [comment]
So it's WeChat WebView on iOS 10.3? I'm sorry but I really can't find such a device to test.

My email's haoqunjiang#gmail.com (replace # with @).
My best guess at the moment is that it may be a viewport related bug of the WebView itself, and it can be very hard to locate and debug, so I can't help you much on this issue…

**Comment by wxkcoder** [comment]
Thank you so much, I will feed back this question to the Wechat team.
