### ISSUE TITLE
Vue插槽slot引发的严重性能问题 - 续？

### ISSUE THREAD

**Issue by karmiy** [vuejs/vue#10346]
### Version
2.6.6

### Reproduction link
[https://codepen.io/karmiy/pen/pMWVOX](https://codepen.io/karmiy/pen/pMWVOX)

### Steps to reproduce
接着https://github.com/vuejs/vue/issues/10342

v-slot可以解决一些场景

但是，在一些情况不行

如这种

依旧会造成logger组件一直重新render

### What is expected?
一个组件应该数据没有任何变化时，不应该有任何重新render的现象

### What is actually happening?
放入的是<slot></slot>依旧会render

**Comment by posva** [comment]
Hey please, stop opening the same issue again and again. Search existing issues as the problem with listeners and attrs has already been reported and please open issues in English. Thank you
