### ISSUE TITLE
Vue插槽slot引发的严重性能问题？

### ISSUE THREAD

**Issue by karmiy** [vuejs/vue#10342]
### Version
2.6.6

### Reproduction link
[https://codepen.io/karmiy/pen/pMWVOX](https://codepen.io/karmiy/pen/pMWVOX)

### Steps to reproduce
例如：
父组件app，它有data如text，在template的随便一个地方&lt;input type='text' v-model='text'&gt;{{text}}

子组件test是:
Vue.component('logger', {
  created() {
    console.log('created');
  },
  render(createElement) {
    console.log(9);
    return createElement('h1', '1');
  }
});

这时我们在app这个组件里，使用<logger></logger>这个组件，在项目中会在控制台看到打印了9，没什么问题。

当尝试去改变input的值来驱动text这个data改变时，控制台也没有任何输出，<logger></logger>没有重新去渲染render，很好。

但是接下来一个改变问题就来了：

将<logger></logger>改成<logger>333</logger>

再尝试去改变input的值来驱动text这个data，奇怪的事情发生了，控制台随着text改变，也一直输出9，意味着<logger>不断在重新渲染！！(可是text改变和它毫不相关，即不是它的插槽内容，也不是它的props)

<logger>没有传任何props，slot位置也只是个普通字符串333，没有改变，却因为毫不相关的text导致一直重新渲染
这在高频率text变化时，造成了很严重的性能问题。

这是在我用Vue开发Markdown编辑器，文本不断变化时发现的问题，组件里与文本无关的如<nz-button>普通按钮<nz-button>这种中间有slot内容的不断在重复渲染，在编辑器快速触发改变文本时任何带有slot内容的组件都在不断重新渲染导致页面性能问题非常严重

一直找不到合适的解决方案，因为在用antd的组件库，改组件是用jsx形式去写vue组件库的，学习了代码后发现有的组件render部分有的逻辑比较复杂，这样高频率的触发render对性能影响太大。。。。求指教，非常感谢！

### What is expected?
如何使<logger>333</logger>不随毫不相关的data去重复render

### What is actually happening?
毫不相关的data改变，使得拥有slot插槽内容的组件不断重复渲染

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/9756

Use a `v-slot` and it will not re render

**Comment by karmiy** [comment]
v-slot可以解决一些场景

但是，在一些情况不行

如<logger><template v-slot><slot><slot></template></logger>这种

依旧会造成logger组件一直重新render
