### ISSUE TITLE
Vue is homophone of view.

### ISSUE THREAD

**Issue by igreulich** [vuejs/vue#10343]
### Version
2.6.10

### Reproduction link
[https://codepen.io/igreulich/pen/EqwGKY](https://codepen.io/igreulich/pen/EqwGKY)

### Steps to reproduce
n/a

### What is expected?
I expect to be able to talk to people about your framework without confusion about whether am I referring to Vuejs or a view.

### What is actually happening?
I am unable to talk about your framework without confusion about whether I am referring to Vuejs or a view.

---
Did any one try and talk about Vue with someone unfamiliar with it? I have, and I spend more time clarifying that I mean Vue (or a view) than I do actually explaining Vue!

**Comment by posva** [comment]
Then say Vue.js

Please don't use issues for this.you can use the chat
