### ISSUE TITLE
The use of v-for in v-else results in undefined

### ISSUE THREAD

**Issue by njed** [vuejs/vue#10351]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/njed_ann/xLfzsjte/4/](https://jsfiddle.net/njed_ann/xLfzsjte/4/)

### Steps to reproduce
Open the link.

### What is expected?
1 2 1 2 3

### What is actually happening?
1 2 undefined

---
The children of the component's vnode instance is [vnode, vnode, [vnode, vnode, vnode]], that's right.but the update operation does not judge the array.

**Comment by posva** [comment]
Please see https://vuejs.org/v2/guide/conditional.html#v-if-with-v-for

You probably need to use a template element somewhere but I'm not sure of where you want the repetition
