### ISSUE TITLE
关于：v-html渲染router-link的问题

### ISSUE THREAD

**Issue by ddyh0826** [vuejs/vue#10357]
### What problem does this feature solve?
可以渲染`<a>`，但是无法解析`<router-link>`

### What does the proposed API look like?
如果正常解析会发生什么呢

**Comment by posva** [comment]
when you use v-html, it can only parse regular html. If you need to handle vue components and directives, you need to compile using Vue.

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
