### ISSUE TITLE
Error in v-on handler: "TypeError: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by MutelyMilo** [vuejs/vue#10362]
### Version
2.5.9

### Reproduction link
[https://github.com/lzmkony/x-one.git](https://github.com/lzmkony/x-one.git)

### Steps to reproduce
1、递归组件最后的list导出的时候是[__ob__observer]
2、该数组不能被 echarts G6树形图渲染 亲测
3、我认为可能数组不是一个 js数组 所以导致无法渲染
4、当我使用JSON.stringify([$PARAM$])处理的时候 一层数组还可以，如果数组内有多元素就会报错（title的错误） 

### What is expected?
我如何才能获得 可视化工具可以渲染的js数据呢？

### What is actually happening?
如题的报错。可视化工具无法正常渲染vue data

---
无

**Comment by posva** [comment]
The repository you put doesn't exist. The error is a javascript error so your array probably have a reference to itself or an object inside has. If you can reproduce it in a boiled down repro (a codepen could be enough), please open a new issue with the reproduction
