### ISSUE TITLE
First class web components support

### ISSUE THREAD

**Issue by petr001** [vuejs/vue#10360]
### What problem does this feature solve?
In Vue, we can bind any property with complex data type with v-bind directive:
```
<vue-component :prop-with-object="{ some: 'object' }" />
```

But for web components, we have to use `.prop` otherwise it's converted to string (=it's bound as attribute which supports only string)
```
<web-component :prop-with-object.prop="{ some: 'object' }" />
```

It would be nice if there is no difference between web components and vue components.

### What does the proposed API look like?
```
<web-component :prop-with-object="{ some: 'object' }" />
```

should set web component propWithObject property by default (no need for .prop)

**Comment by posva** [comment]
We can check if an element is a custom element but we cannot know which properties are props or which bound values are meant to be bound as attributes or props. It will mean we will have to keep a list of attributes and keep it updated which is error prone, even more considering cross browser support.

Are you using https://github.com/vuejs/vue-web-component-wrapper?
I think this kind of behavior should be in a plugin

Regarding the props being set to string. Best Practices for web components says to use primitive values for attributes and rich data for properties: https://developers.google.com/web/fundamentals/web-components/best-practices (search for _primitive_ or _rich data_, I couldn't find an anchor)
