### ISSUE TITLE
 Error in v-on handler: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by MutelyMilo** [vuejs/vue#10367]
### Version
2.6.10

### Reproduction link
[https://gitee.com/PhoenixMilo/study-vue.git](https://gitee.com/PhoenixMilo/study-vue.git)

### Steps to reproduce
通过递归组件添加一个节点之后再渲染echarts就会报错。相反如果你没有操作过这个需要被渲染的数据是没有什么问题的，个人觉得被vue加工过的数据再去渲染就会出问题。

### What is expected?
可以正常操作和渲染

### What is actually happening?
现在依旧报错，报错内容就是 title

---
如果你不增加新的item，一切都没问题，新加之后就会有问题。我对比过 E charts给的官方数据 我打印出来的递归vue数组和js原生数组不太一样。所以，问题是不是 vue 生层的数组 不能提供给echarts渲染呢？

**Comment by MutelyMilo** [comment]
运行起来以后 点击go reduce 然后在里面尝试操作就好了。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). If you are reporting a bug, report a boiled down repro with no dependencies, not your whole project
