### ISSUE TITLE
transition组件无法正确变更样式

### ISSUE THREAD

**Issue by githubwubicheng** [vuejs/vue#10363]
### Version
2.6.10

### Reproduction link
[http://git.1squan.com/taomaofan/taomaofan-frontend.git](http://git.1squan.com/taomaofan/taomaofan-frontend.git)

### Steps to reproduce
同一个页面定义两个transition
<transition :name="transitionName" >
			  <keep-alive>
			  		<router-view v-if="$route.meta.keepAlive" ></router-view>
			  </keep-alive>
    </transition>
			<transition :name="transitionName" >
			  <router-view v-if="!$route.meta.keepAlive"></router-view>
			</transition>
初始值是slide-right，页面进入的样式slide-right-enter-active，和离开为slide-right-leave-active，当变更transitionName的值为slide-left,页面进入的样式是slide-left-enter-active，离开的样式为slide-right-leave-active，没有正确变更为slide-left-leave-active

### What is expected?
希望能根据:name属性变更页面离开进入样式

### What is actually happening?
初始值是slide-right，页面进入的样式slide-right-enter-active，和离开为slide-right-leave-active，当变更transitionName的值为slide-left,页面进入的样式是slide-left-enter-active，离开的样式为slide-right-leave-active，没有正确变更为slide-left-leave-active

**Comment by posva** [comment]
Please provide a boiled down repro that is accessible when opening an issue. A codepen or [Codesandbox](https://codesandbox.io/s/vue) can help
