### ISSUE TITLE
Initialize the value if it is not found when building the proxy

### ISSUE THREAD

**Issue by M-Zuber** [vuejs/vue#10368]
### What problem does this feature solve?
In some situations, the proxy builder can run before the `sourceKey` field exists.
I would like to suggest adding in a fail-safe in the get/set that are built to initialize `sourceKey` as an object with a single key, namely the `key` that was passed into the proxy function.

### What does the proposed API look like?
There are no changes made to the API, it is an internal addition only.

The change involved would be to change [this function](https://github.com/vuejs/vue/blob/33e669b22f69a1f9c9147528360fe0bba85534f0/src/core/instance/state.js#L38) to include an inner `if` 
```diff
function proxy (target, sourceKey, key) {
  sharedPropertyDefinition.get = function proxyGetter () {
+    if(!this[sourceKey]) {
+      this[sourceKey] = {
+        [key] = {}
+      };
+    }
    return this[sourceKey][key]
  };
  sharedPropertyDefinition.set = function proxySetter (val) {
+    if(!this[sourceKey]) {
+      this[sourceKey] = {
+        [key] = {}
+      };
+    }
    this[sourceKey][key] = val;
  };
  Object.defineProperty(target, key, sharedPropertyDefinition);
}
```

**Comment by posva** [comment]
having a side effect in the getter is not something we want. Also some people would want a different initial value and this would be a breaking change
