### ISSUE TITLE
Checkbox/computer setter loss of sync

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#10374]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/wj1o6fbu/](https://jsfiddle.net/wj1o6fbu/)

### Steps to reproduce
1. Click on the checkbox once to turn it on
2. Click on the checkbox a second time to turn it off :
  - if you press 'OK', everything behaves perfectly
  - if you press 'CANCEL', even though the value and computed are true, the checkbox is unchecked

### What is expected?
checkbox should not be unchecked

### What is actually happening?
checkbox is unchecked

---
I know using a function is probably a good quick fix, but this is part of a bigger algorithm, streamlined structure generated by huge json documents with dozens of fields. I'd wish to understand why it fails.

**Comment by posva** [comment]
You will need some way to tell the browser to keep the old state:

```js
if (decision === false) {
              event.target.checked = this.value
              return
            }
```

This might be related to issues like https://github.com/vuejs/vue/issues/10282

**Comment by y-nk** [comment]
@posva so that mean you can't embed checkboxes in components ? how is your solution working with a case like https://jsfiddle.net/jr0Lxaun/ ?
