### ISSUE TITLE
How to use v-if directives inside custom directives？

### ISSUE THREAD

**Issue by jxZhangLi** [vuejs/vue#10384]
### What problem does this feature solve?
I want to implement such a directive, but I don't know how to do it ！
There is no introduction in the document. Help me！

```html
<template>
 <div class="orders">
    <div class="content"></div>
    
    <select-product-dialog v-if="showA" /> 
    
    <select-project-dialog v-if="showB"/> 
    
    <settlement-dialog v-if="showC"/>
  </div>
</template>
````

 ```javascript
 new Vue({
    data: {
        showA: false,
        showB: false,
        showC: false
    },
    created () {
        setTimeout(() => {
            this.showA = true;
            this.showB = true;
            this.showC = true;
        }, 0);
    }
});
 ```

### What does the proposed API look like?
```html
<template>
  <div class="delay">
    <h1 v-if="true" v-delay>delay title</h1>
    <delay-component v-delay="100" />
  </div>
</template>
```

```js
Vue.directive('delay', {
    bind: function (el, binding, vnode) {
      // ??? how use v-if
    },
    inserted: function (el, binding, vnode) {
      
    },
    update: function (el, binding, vnode) {
      
    },
    unbind: function (el, binding, vnode) {
     
    },
  })

```

**Comment by posva** [comment]
There is no such access in a directive. When the component is inserted, it means the v-if is true. if it triggers `unbind`, then it must have been removed by either the parent, a v-for or a v-if.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
