### ISSUE TITLE
Documentation should have a list of whitelisted globals available in template

### ISSUE THREAD

**Issue by thomas-betous-cbp** [vuejs/vue#10388]
### What problem does this feature solve?
Documentation should have a list of whitelisted globals available in template

Go in the documentation : https://vuejs.org/v2/guide/syntax.html#Using-JavaScript-Expressions

There is this disclaimer at the end : 
> Template expressions are sandboxed and only have access to a whitelist of globals such as Math and Date. You should not attempt to access user defined globals in template expressions.

A [stackoverflow](https://stackoverflow.com/questions/57479850/what-globals-are-available-in-template-expressions/57480432
) has been posted and made me think about that. It is true that there is a lake of accuracy here.

I think it would be nice to display the whole list.

### What does the proposed API look like?
It can be a simple [link to the open source code](https://github.com/vuejs/vue/blob/v2.6.10/src/core/instance/proxy.js#L9), or a simple list in the disclaimer.

I volunteer for this task if you are agree with that.

**Comment by posva** [comment]
Good point, could you open this on Vuejs documentation repo? vuejs/vuejs.org (make sure to check it hasn't been reported before or that there isn't a PR yet first)
