### ISSUE TITLE
Support nullish-coalescing-operator and optional-chaining in template

### ISSUE THREAD

**Issue by ppjjzz** [vuejs/vue#10386]
they are at stage 3 now. Can support them in template?

**Comment by posva** [comment]
Check https://github.com/vuejs/vue/issues/6307

**Comment by oliverzy** [comment]
Right now optional chaining has been officially part of ECMAScript 2020 (Chrome 80), therefore I think maybe we should reconsider this feature request again.

**Comment by emdahlstrom** [comment]
This would clean up template logic alot when working with nested fields from a cms like contentful

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue-next/commit/8449a9727c942b6049c9e577c7c15b43fdca2867

**Comment by nVitius** [comment]
Is this only available in Vue 3?
