### ISSUE TITLE
why not always create a now object of data for component?

### ISSUE THREAD

**Issue by jovenwang1212** [vuejs/vue#10385]
### What problem does this feature solve?
Now we register a Component, the data value must be a function, can not be an object. if we use an object, then we get console error. it is not allowed.

But if i want to put Vue component data an object, as the root Vue instance, how ? There is a solution, Vue.js always return a new object of component data? 

### What does the proposed API look like?
  Vue.component('Counter', {
    data: {
      num: 0
    }
  })

**Comment by posva** [comment]
See https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function
Having a function is the most natural way to create new objects. It also work with any kind of object
