### ISSUE TITLE
It's seems vue.js v2.6.9 or later have bug of transition with vue-router.

### ISSUE THREAD

**Issue by mutsuyuki** [vuejs/vue#10389]
### Version
2.6.9

### Reproduction link
[https://mutsuyuki.github.io/vue-transition-issue/vue_2.6.9.html](https://mutsuyuki.github.io/vue-transition-issue/vue_2.6.9.html)

##### correctly work with v2.6.8
[https://mutsuyuki.github.io/vue-transition-issue/vue_2.6.8.html](https://mutsuyuki.github.io/vue-transition-issue/vue_2.6.8.html)

### Steps to reproduce
I make same page using vue.js v2.6.8 and v2.6.9.

I make 2 pages with page change transition.
2 pages have different transition each other.

with v2.6.8, transition work correctly, but with v2.6.9, enter transition is not work. leave transition is work correctly.  

please check my repository

https://github.com/mutsuyuki/vue-transition-issue/tree/master/docs

### What is expected?
some transition bug was embeded at v2.6.9

### What is actually happening?
transition enter is not work.

**Comment by posva** [comment]
you need to use the appear prop for the transition to enter on trigger. This was a fix introduced on 2.6.9 for https://github.com/vuejs/vue/issues/9364

**Comment by mutsuyuki** [comment]
Thank you! Transition work correctly with "apeear" prop.
