### ISSUE TITLE
when use appendchild in vueComponent,and via v-if to control component, get "Failed to execute 'insertBefore' on 'Node' "

### ISSUE THREAD

**Issue by garfieldon757** [vuejs/vue#10399]
**Vue.js version**
2.6.3

`Modal.vue

<template>
  <div class="modal is-active has-text-centered">
    <div class="modal-background"></div>
    <div class="modal-card">
      <section class="modal-card-body">
        <slot></slot>
      </section>
    </div>
    <button class="modal-close" @click="$emit('close')"></button>
  </div>
</template>

<script>
export default {
  mounted () {
    document.getElementById('app').appendChild(this.$el)
  }
}
</script>
Something.vue

<template>
  <section class="section">
    <div class="container">
      <modal v-if="showModal" @close="showModal = false">
        <p>Some text here</p>
      </modal>
      <a class="button is-primary modal-button" @click="showModal = true">Show modal</a>
    </div>
  </section>
</template>

<script>
import Modal from './ui/Modal'

export default {
  data: function () {
    return {
      showModal: false
    }
  },
  components: {
    Modal
  }
}
</script>`

**What is Expected?**
When click on the close button, it should close the modal window.

**What is actually happening?**
Console shows me the error DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by Justineo** [comment]
You may need to move the root node back to its original position in the `beforeDestroy` lifecycle hook.
