### ISSUE TITLE
babel plugin "transform-remove-console" not working 

### ISSUE THREAD

**Issue by shmaram** [vuejs/vue#10395]
### Version
2.6.10

### Reproduction link
[https://codepen.io/shahar-shmaram/pen/zYOrbdq](https://codepen.io/shahar-shmaram/pen/zYOrbdq)

### Steps to reproduce
1. I added the plugin to the babel.config.js
2. run "vue-cli-service build" 
3. I still see console.log in my js files 

### What is expected?
not to see console.log in my js files 

### What is actually happening?
I still see console.log in my js files 

---
I tried both options you can see in the codepen example

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is not related to Vue

**Comment by shmaram** [comment]
Hi

How come this is not a bug?
