### ISSUE TITLE
lodash.template v4.5.0 version security issue

### ISSUE THREAD

**Issue by kkokey** [vuejs/vue#10393]
### Version
2.6.10

### Reproduction link
[https://github.com/marketplace/dependabot-preview](https://github.com/marketplace/dependabot-preview)

### Steps to reproduce
Check github plugin `Dependabot Preview`
this is free

### What is expected?
We think about security issue sensitively.
Please check and update lodash.template project.

### What is actually happening?
Vue project has weakness point.

---
This is not code bug, library.
I suggest using dependabot-preview.
https://github.com/marketplace/dependabot-preview

**Comment by posva** [comment]
Thank you, we are aware of this. We already updated the version https://github.com/vuejs/vue/pull/10257/files
