### ISSUE TITLE
Classes are being repeated in render function when using the parent property

### ISSUE THREAD

**Issue by KevinMallinson** [vuejs/vue#10407]
### Version
2.6.10

### Reproduction link
[https://codepen.io/CanuckAussieKev/pen/eYOzgOb](https://codepen.io/CanuckAussieKev/pen/eYOzgOb)

### Steps to reproduce
After opening, you can view the output. The output will show the bug.
The code (js and html) shows how to reproduce it.

### What is expected?
The first paragraph should have a font size of 150%.

The second paragraph should have a font size of 150% and 30 pixel padding left.

The third paragraph should have a font size of 150% and 30 pixel padding left and font color of red.

### What is actually happening?
The second paragraph has a font size of 300%, and third 450%.

The second paragraph contains a padding left of 30px, and third 60px.

This is because the classes are being repeated.

We can see the markup looks like...

```
<p class="one">
    <p class="two one">
        <p class="three two one">
        </p>
    </p>
</p>
```

Intended: 

```
<p class="one">
    <p class="two">
        <p class="three">
        </p>
    </p>
</p>
```

---
Each class is being repeated by its children, because it is assigned via `parent`. If we don't assign via `parent`, then the DOM is correct.
However, assigning via `parent` and `children` is useful, especially when doing things like creating a navmenu using a depth first search.

Is this working as intended, or is this a bug?

**Comment by posva** [comment]
You shouldn't assign via parent and children. Did you find any of that on the docs?

The correct way is using the third argument in createElement: 

```js
let first = createElement("p", { class: "one" }, [
      "This is one.",
      createElement("p", { class: "two" }, [
        "This is two.",
        createElement("p", { class: "three" }, ["This is three."])
      ])
    ]);

    return first;
```

vnodes should be considered read only

**Comment by KevinMallinson** [comment]
@posva I understand this, but it's not practical in my case. For example, I'm doing a depth first search on a tree and building an unordered list with various levels of nesting based on the tree.

I have got it working by pushing to the children - the reason I did this is because I can't form the entire tree in the 3rd parameter of the very first node.

How do you suggest I do that without using .children?

I can provide an example if you wish.

**Comment by KevinMallinson** [comment]
@posva 

Here's my code which I described above. As you can see, I'm pathfinding through a tree, and creating a menu structure using `<ul>` and `<li>`

As you suggested, I shouldn't use `.children` - However, I don't see any way to do what I'm trying to do without using it. It works fine, but I suppose it's not supported. Can you recommend a way that is supported? Specifically, I can't just use the third parameter and nest `createElements`, since this is dynamic.

I would appreciate if you could recommend a supported solution:

```
let nav = createElement('ul', { 
                    'class': [ 'nav', 'flex-column', 'left-navbar', 'sticky-top' ]
                }, []
            );

            let navbar = createElement('nav', { 'class': [ 'col-md-2', 'd-none', 'd-md-block', 'bg-light', 'sidebar' ] }, [ searchContainer, nav ]);
            
            //Depth First Search.
            let parent = null;
            let stack = [ ...Vue.prototype.NAV_ITEMS, null ];

            while(stack.length > 0) {
                let currentNode = stack.shift();

                //We use a null to indicate we've finished at this depth (i.e. this <ul>)
                if (currentNode == null) {
                    //now we're at the previous <ul>
                    nav = parent;
                    continue;
                }
                    
                let selectedItem = createElement('li', { 'class': ['nav-item'] }, [ 
                    createElement('router-link', { 'class': ['nav-link'], props: { to: currentNode.link }, } , [ currentNode.text ]) 
                ]);

                //add the <li> to the selected <ul>
                nav.children.push(selectedItem);

                //We use a single null to let us know when we need to reduce depth
                if (currentNode.children && currentNode.children.length > 0) {

                    //Since we have children, put the children first, separated by a null, then the existing stack.
                    //This essentially allows us to use a depth first search.
                    stack  = [...currentNode.children, null, ...stack];

                    //Because we have children, we need to assign what their parent is.
                    //This allows us to go back to the previous <ul> (as above) and continue where we left off.
                    parent = nav;

                    //Next, we need to add a new <ul>, and add it to the current <li>, in effect, making another nested list.
                    nav = createElement('ul', { 'class': [ 'nav', 'flex-column', 'ml-3' ] }, []);  
                    selectedItem.children.push(nav);
                }
            }

            return navbar;
        }
```

**Comment by posva** [comment]
> How do you suggest I do that without using .children?

I would delay the calls to `createElement` by creating the structure first and once everything is set, generate the vdom by calling `createElement`
