### ISSUE TITLE
vue项目里有个axios工具类，打包后想使用

### ISSUE THREAD

**Issue by tianxia0079** [vuejs/vue#10417]
### What problem does this feature solve?
vue项目里有个axios工具类，打包后，是在js里可以看到这个变量，如何使用这个变量。我试了下面方法都不行：
window._CONFIG['axiospost']=post
window.axiospost=post

### What does the proposed API look like?
window._CONFIG['axiospost']=post

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
