### ISSUE TITLE
function genHandler has problem

### ISSUE THREAD

**Issue by zwwill** [vuejs/vue#10418]
### Version
2.6.10

### Reproduction link
[https://codepen.io/zwwill/pen/eYOBGqV](https://codepen.io/zwwill/pen/eYOBGqV)

### Steps to reproduce
one line of function genHandler,
```
var isFunctionInvocation = simplePathRE.test(handler.value.replace(fnInvokeRE, ''));
```
sometime, `handler.value` could be an object like this,
```
{ value: [ '$stopPropagation', 'jump(\'/cart.html\', \'BUY\')' ],
  dynamic: false,
  modifiers: { stop: true } }
```
and then, compiler will throw an problem like,
```
Module build failed: TypeError: handler.value.replace is not a function
```

### What is expected?
no error

### What is actually happening?
error

**Comment by posva** [comment]
I cannot reproduce using the template explorer: https://template-explorer.vuejs.org/#%3Ca%20href%3D%22javascript%3Avoid(0)%22%20%40click.stop%3D%22jump('%2Fcart.html'%2C%20'BUY')%22%3E%3C%2Fa%3E

Please ping me if you manage to create a reproduction
