### ISSUE TITLE
v-model not update when I use macos keyboard for language different than English

### ISSUE THREAD

**Issue by bnqtoan** [vuejs/vue#10424]
### Version
2.6.10

### Reproduction link
[https://codepen.io/flexer/pen/abopNQq](https://codepen.io/flexer/pen/abopNQq)

### Steps to reproduce
I write a simple app as the codepen link above.

### What is expected?
Model update instantly on typing, when ever I type

### What is actually happening?
When I type on the textbox, the model "message" change normal.
But when I change my keyboard (to another language difference than English), the model just update when textbox has space.

I event try to force model update by catching keyup, keydown, keypress, input event but no luck

---
https://youtu.be/QsB_fty6cxI please take a look issue on this video

**Comment by posva** [comment]
This is expected, we wait for the _composition_ to be finish. If you don't want that, you can manually listen to the `@input` event on the input
