### ISSUE TITLE
Infinite loop when using dynamic import to lazy load component

### ISSUE THREAD

**Issue by hypervillain** [vuejs/vue#10423]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-bs7uj](https://codesandbox.io/s/vue-template-bs7uj)

### Steps to reproduce
Create a render function that uses dynamic imports (like `sliceZone.vue` in the sandbox)
then use it anywhere in your app (tested in a Nuxt project and a Vue Codesandbox).
You should notice an infinite loop that crashes your app.

### What is expected?
Dynamic import should work without the parent component to be re-rendered 

### What is actually happening?
Component calling a dynamic import should not re-render indefinitely

---
The problem probably comes from my lack of understanding of Vuejs / dynamic imports.
Any working example would be greatly appreciated!

**Comment by LinusBorg** [comment]
You are essentially re-creating a new dynamic component on each re-render. move the component function outside of the render function.

**Comment by hypervillain** [comment]
Thank you @LinusBorg

**Comment by WofWca** [comment]
Duplicate of #9943
