### ISSUE TITLE
MessageChannel and setTimeout execution order is unstable

### ISSUE THREAD

**Issue by XiaoDHuang** [vuejs/vue#10420]
### Version
2.5.13

### Reproduction link
[https://codepen.io/hddgithub02/pen/GRKNzjP?editors=1111](https://codepen.io/hddgithub02/pen/GRKNzjP?editors=1111)

### Steps to reproduce
chrome 49.0.2623.75 

### What is expected?
nextTick 早于 setTimeout 

### What is actually happening?
实际结果两个调用顺序不稳定

---
chrome 49.0.2623.75  此版本浏览器已经确认支持Promise API  测试一下跟 MessageChannel 与setTimeout 异步有关

**Comment by sodatea** [comment]
在 2.6 里我们已经不再使用 MessageChannel 实现 nextTick 了 https://github.com/vuejs/vue/pull/8450
