### ISSUE TITLE
Migration from Vue 1.x

### ISSUE THREAD

**Issue by rameshvishnoi90904** [vuejs/vue#10429]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/5bwkxvjt/](https://jsfiddle.net/5bwkxvjt/)

### Steps to reproduce
I am using VueJs 1.0.26 and now planning to move it to latest version. I am not able to find alternative of Vue.parsers.path.getPath function Can anyone help?

### What is expected?
Alternative of Vue.parsers.path.getPath  function

### What is actually happening?
Vue.parsers.path.getPath Function is missing

**Comment by posva** [comment]
We do not support v1 anymore (it has been a long time). That being said we have a migration at https://vuejs.org/v2/guide/migration.html

if you were using private APIs, it may need a bit more research and looking into the code. If you need help, I recommend you to check our the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
