### ISSUE TITLE
如何在vue中使用继承了Array的子类

### ISSUE THREAD

**Issue by Diry2017** [vuejs/vue#10427]
> 如果在VUE组件中使用继承了Array的子类
只要改对象赋值进入VUE组件中 VUE会把该对象改为VUE能够监听的对象
1. list类 继承 Array
`export class List extends Array {`
   `constructor(){`
    `super()`
  `}`
  `test()`
  `}`
`}`

2.某个VUE组件中
`import { List } from './list'`
`export default {`
  `data () {`
    `return {`
      `list: null`
   ` }`
  `},`
  `created () {`
    `this.list = new List()`
    `console.log(new List().test)  // => function....`
    `console.log(this.list.test)  // => undefined`
  `}`
`}`

**Comment by Justineo** [comment]
Duplicate of #9259
