### ISSUE TITLE
Vue resets INPUT field when setting it to disabled but not TEXTAREA

### ISSUE THREAD

**Issue by MSCAU** [vuejs/vue#10422]
### Version
2.5.17

### Reproduction link
[https://codepen.io/MSCAU/pen/jONVRRj](https://codepen.io/MSCAU/pen/jONVRRj)

### Steps to reproduce
1. Bind the 'disabled' attribute of a INPUT TYPE='text' to a Vue boolean with value 'false'.
2. Bind the value attribute of the same INPUT to a Vue string (not using v-model), ie. `<INPUT type="text" :value="myVal" :disabled="myBool"/>`
3. Type a new value in the rendered text field.
4. Via code or Vue DevTools, switch the boolean to false. The value of the input changes back to its original value.
5. Do the same with a TEXTAREA: `<TEXTAREA v-html="myText" :disabled="myBool"></TEXTAREA>`
6. See how the new TEXTAREA's content is *not* reset when the boolean is switched to 'true'.

### What is expected?
The INPUT and TEXTAREA should behave the same way, (preferably by not resetting when their disabled properties are toggled).

### What is actually happening?
The INPUT field resets to its original value. The TEXTAREA field does not.

---
If I want to disable form fields after submission (eg. during server-side validation or animation), it is incongruous (a) for them to reset to their original unmodified values, or (b) to have some of them reset and some not.

I don't want to use v-model here as my original data is a JS object tree with many associated dependencies. I want to validate the user's new values before committing the changes. I'm also allowing the user to lock a record, making it read-only, and I am using the 'disabled' property to indicate this visually and to preclude changes.

See also the same question on StackOverflow with unsatisfactory / incomplete answers: https://stackoverflow.com/questions/57604402/vue-resets-input-field-when-setting-it-to-disabled

**Comment by posva** [comment]
This is expected: the input re renders when disable changes and the `value` hasn't changed, so it's reset to its previous value. Using `v-model` will allow you to persist the value between renders

**Comment by MSCAU** [comment]
Why does textarea behave differently?
