### ISSUE TITLE
$nextTick still executes before the window.confirm interrupts the DOM update on chrome but not on mozilla

### ISSUE THREAD

**Issue by Abassion** [vuejs/vue#10440]
### Version
2.6.10

### Reproduction link
[https://codepen.io/Dadboz/pen/vYBxerr](https://codepen.io/Dadboz/pen/vYBxerr)

### Steps to reproduce
you have to test the demo on Mozilla and chrome by simply clicking the update button

### What is expected?
expected the value to be updated before the confirm dialog fires

### What is actually happening?
$nextTick still executes before the window.confirm dialog interrupts the DOM update on chrome but not on mozilla

**Comment by posva** [comment]
The browser rendering the DOM vs rendering messages and blocking the rendering thread is something we cannot control. We can only ensure the DOM is updated, that's when `nextTick` triggers, you can use a console.log to check it. To ensure the view is also updated, use this

```js
this.$nextTick(()=>{
          console.log(document.getElementById('app').textContent)
          requestAnimationFrame(() => {
             confirm('if you are using chrome notice that the value is not updated only after you resolve the dialog')   
          })
       }) 
```
