### ISSUE TITLE
After forceRefresh with new data, v-model doesn't bind - Update: With keyed-object data

### ISSUE THREAD

**Issue by HTMLGuyLLC** [vuejs/vue#10446]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/rkwgLzso/](https://jsfiddle.net/rkwgLzso/)

### Steps to reproduce
Create a component that contains a field with v-model.
Update your data object
Force refresh

### What is expected?
I'm new to VueJS as of today, but I believe the new row should display and data should bind.

### What is actually happening?
New row displays but data is not binding.

**Comment by posva** [comment]
Hey, please check https://vuejs.org/v2/guide/list.html#Caveats

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
