### ISSUE TITLE
Descendant scoped styles for pseudo classes are incorrectly postfixed

### ISSUE THREAD

**Issue by Hulkmaster** [vuejs/vue#10445]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-tftf1](https://codesandbox.io/embed/vue-template-tftf1)

### Steps to reproduce
- Have Outer component with classname (`container`)
- Have Child component with element with same classname (`container`), put inside that element another with different classname (`container__text`)
- Create a scoped style rule inside child component with a pseudoclass and descendant class (`.container:hover .container__text { something }`)

### What is expected?
except component with pseudoclass to be postfixed with `data`

```
.container[data-v-6163c154]:hover .container__text[data-v-6163c154] {
  background-color: blue;
}
```

### What is actually happening?
child scoped classname with pseudoclass is not postfixed with "data" attribute

```
.container:hover .container__text[data-v-6163c154] {
  background-color: blue;
}
```

so parent component styles with same classname are used

**Comment by posva** [comment]
This is consistent with

```css
.container .container__text {
  background-color: blue;
}
```

applying the data-v attribute to the latter class

If you use only

```css
.container:hover {
  background-color: blue;
}
```

you will see that the data-v attribute gets applied correctly before the `:hover`

At this state I think this could impact quite some people as changing it would be a breaking change.  Maybe there was some discussion about this on vue-loader repository (the scoped css feature lives there)

**Comment by Hulkmaster** [comment]
Okay, thank you, will try to find these discussions

**Comment by posva** [comment]
Feel free to post back if you find anything as it could help anybody coming from a search to find the actual discussion
