### ISSUE TITLE
when i  used v-if directive render component,How do i know the currently component is v-if render?

### ISSUE THREAD

**Issue by jonnyshao** [vuejs/vue#10449]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-t9tnq](https://codesandbox.io/s/vue-template-t9tnq)

### parent component
```javascript
<template>
	<div>
		<child v-if="childRender"></child>
	</div>
</template>
<script>
import child from './child'

export default {
	name: 'parent',
	data() {
		return {
		    childRender: false
		}
	},
	components: {
		child,
		grandSon
	}
}
</script>
```

### child component
```javascript
<template>
	<div>
		<grand-son></grand-son>
	</div>
</template>
<script>
import grandSon from './grandSon'
export default {
	name: 'Child',
	components: {
		grandSon
	}
}
</script>
```
### vue mixin

```
Vue.mixin({
    created() {
        // // current component is `v-if` direcitve render
        if (this.xxx){
            // do something
        }
    }
})
```

### What is expected?
when i change the `renderChild` status, how do i know the `child component` and `grandSon component` is use `v-if` directive render?
I want to use Vue.mixin method by injected something into Conditional(v-if) render component

### What is actually happening?
can not injected  something into the `v-if` render component 

---
I'm tried to custom property in $options,but i did't want to do that, because these component will be more and more, how do i to do that?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It renders when the v-if is true. You may find helpful using lifecycle hooks
