### ISSUE TITLE
new slot scope logic - this.$slots.default doesn't return value if slot content is present

### ISSUE THREAD

**Issue by Xayer** [vuejs/vue#10442]
### Version
2.6.10

### Reproduction link
[https://codepen.io/xayer/pen/wvwJjqr](https://codepen.io/xayer/pen/wvwJjqr)

### Steps to reproduce
1. check console logs.
2. slot called "prepend" works if no dynamic data is present.(<template v-slot:prepend">)
3.  slot called "append" doesn't work as intended if we add dynamic data to the slot. (<template v-slot:append="{ row }">).

### What is expected?
slots with dynamic data should show up in this.$slots even if dynamic content is present.
Eg. for my example code this.$slots.append should return something.

### What is actually happening?
this.$slots.append returns undefined, unlike this.$slots.prepend which returns data as intended.

**Comment by posva** [comment]
This is expected, you have to use `$scopedSlots`. It cannot show up, as it would be a function. It cannot render until the data is provided

**Comment by Xayer** [comment]
> This is expected, you have to use `$scopedSlots`. It cannot show up, as it would be a function. It cannot render until the data is provided

 `this.$scopedSlots` only gives empty normalized() functions, nothing useful, regardless if the slot is populated or not.
