### ISSUE TITLE
vue 3.0 或者后期版本会像 angular 7 那样在框架层加入大数据虚拟滚动吗

### ISSUE THREAD

**Issue by xiaogaofudao** [vuejs/vue#10456]
### What problem does this feature solve?
vue 3.0 或者后期版本会像 angular 7 那样在框架层加入大数据虚拟滚动吗，或者单独出一个支持虚拟滚动的分支版本，或者加入一个标签开启，或者增加一个虚拟滚动内置 组件

### What does the proposed API look like?
https://github.com/Akryum/vue-virtual-scroller 作者好像也是参与过 vue 开发

**Comment by posva** [comment]
I don't think we won't. It's the kind of solution that should live in user land as it is specific to use case and yeah Guillaume (Akryum) is a core team member
