### ISSUE TITLE
vnode.elm not set in vnode when using new v-slot syntax

### ISSUE THREAD

**Issue by sheijne** [vuejs/vue#10450]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-2610-v-slot-bug-1ulx9](https://codesandbox.io/s/vue-2610-v-slot-bug-1ulx9)

### Steps to reproduce
1. Create a component with a named slot in the template.
2. Render the component passing an element or component to the named slot using the `<template v-slot>` syntax.
3. Access the slot's VNode inside the component's `mounted` hook.

### What is expected?
The `elm` property on the `VNode` should contain the slot's root element, when accessing the VNode from the `mounted` hook.

### What is actually happening?
The element/component passed to the named slot renders as it should, however, the `elm` property on the available `VNode` has a value of `undefined`, and is never set.

---
I'm binding an `EventListener` to the slot from inside the component's `mounted` hook, after replacing the old slot syntax with the `v-slot` syntax errors are thrown since there is no element available on the VNode.

**Comment by posva** [comment]
This is consistent with how scopedSlots work, relying on the elm there is not a good idea because of this: https://github.com/vuejs/vue/issues/9580#issuecomment-467718522 and this https://github.com/vuejs/vue/issues/5427#issuecomment-294670724
