### ISSUE TITLE
can't get the data variable "_gridgap" value

### ISSUE THREAD

**Issue by ximijia** [vuejs/vue#10451]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1.name the Number variable "_gridgap"
data(){
   return {_gridgap:4}
}
2.get the variable undefined in mehtods
methods:{
   add(){this._gridgap}
}

### What is expected?
what are all the variable name who can't be used? why?

### What is actually happening?
I get the variable "_gridgap" whose value is undefined!

**Comment by kinow** [comment]
Variables starting with underscore are special and not recommended (though you can use them via `$data._gridgap`): https://github.com/vuejs/vue/issues/2098#issuecomment-168091787

**Comment by Justineo** [comment]
> Properties that start with `_` or `$` will **not** be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as `vm.$data._property`.

https://vuejs.org/v2/api/#data

**Comment by ximijia** [comment]
@kinow @Justineo thanks all of you.
