### ISSUE TITLE
Programatically trigger a custom event on a component

### ISSUE THREAD

**Issue by kayoderock** [vuejs/vue#10468]
### What problem does this feature solve?
I need to close a special drop-down if the user is not active on the drop-down parent for a few seconds. I need to fire the close event for that component.

### What does the proposed API look like?
`this.$refs.element.close()` or  `this.$refs.element.trigger('event-name')`

**Comment by Justineo** [comment]
I believe you should just update the reactive data to close it (eg. via `props`). This is how data-driven frameworks are supposed to work.

**Comment by kayoderock** [comment]
@Justineo The thing is the component is not mine, it's a third-party's, the only way I can close it is to fire that `close` event.

**Comment by Justineo** [comment]
Then you may need to use the native Event API: https://developer.mozilla.org/en-US/docs/Web/API/Event

**Comment by jaireina** [comment]
Technically you can do exactly what you were asking when you opened this issue of you assigned a ref to element (custom component)

**Comment by kayoderock** [comment]
@jaireina I did that, it just didn't work for a custom event.
