### ISSUE TITLE
vue什么时候支持微前端？

### ISSUE THREAD

**Issue by andyzhaozhao** [vuejs/vue#10462]
### What problem does this feature solve?
目前微前端处于概念阶段。自己实现微前端非常繁琐，能否在框架层面提供支持？

### What does the proposed API look like?
方便使用

**Comment by Justineo** [comment]
Feature request 请详细描述具体需求和建议的 API，不建议在这里讨论太笼统的话题。如果有具体的建议，可以提交 RFC 来进行详细描述，并在 [RFC 仓库](https://github.com/vuejs/rfcs)中进行讨论。谢谢。

**Comment by andyzhaozhao** [comment]
@Justineo 您这么回答我很不满意，因为针对这个话题，我没有具体的需求和建议，所以不适合提RFC。我只是想问下vue官方有没有微前端的计划。请问这种话题应该在哪里沟通？

**Comment by Justineo** [comment]
目前没有，重点是 Vue 3.0。

---

非具体的 issue 和 feature request 你可以前往[论坛](https://forum.vuejs.org/)或者 [Discord 聊天室](https://chat.vuejs.org/) 发起讨论，谢谢。

**Comment by lzxb** [comment]
楼主可以了解一下这个项目，基于Vue2的，可以实现微前端、微服务，讲大项目拆分成多个小项目。
https://github.com/fmfe/genesis
