### ISSUE TITLE
checkbox选中后change事件修改状态，checkbox的状态不会被改变

### ISSUE THREAD

**Issue by 965400059** [vuejs/vue#10469]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/weiwei123/q4m68ugk/4/](https://jsfiddle.net/weiwei123/q4m68ugk/4/)

### Steps to reproduce
点击a的复选框，值都是正常显示，复选框的状态不对

### What is expected?
希望能修复改

### What is actually happening?
复选框动态赋值状态不正常

**Comment by posva** [comment]
Please see https://github.com/vuejs/vue/issues/10374#issuecomment-519874823

In your specific case, awaiting a tick before setting the v-model value will work:

```js
async test1(item){
      if(item.name == 'a'){
      	await this.$nextTick()
        item.test = false
      }
    },
```

This is related to changes in micro/macro tasks in 2.6
