### ISSUE TITLE
Nested transition-group with component inside does not work as expected

### ISSUE THREAD

**Issue by WebbLin** [vuejs/vue#10461]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/webbLin/02y7wrL5/32/](https://jsfiddle.net/webbLin/02y7wrL5/32/)

### Steps to reproduce
Click the button 'add' or 'remove', you can see the transition is not smooth.

### What is expected?
As shown in the example below.

https://jsfiddle.net/webbLin/02y7wrL5/33/

The transition-group works fine without component.

### What is actually happening?
Nested transition-group with component inside does not work as expected.

**Comment by posva** [comment]
The examples are different, they work the same if they all share the same list: https://jsfiddle.net/Lrkg8qhe/
