### ISSUE TITLE
Can you provide the ability to compile components into webcomponents? 

### ISSUE THREAD

**Issue by masx200** [vuejs/vue#10479]
### What problem does this feature solve?
Can you provide the ability to compile components into webcomponents? Is cross-framework a future trend?
I hope that the component ecosystem can be shared in other front-end frameworks.能否提供把组件编译成webcomponents的功能？跨框架组件是未来的趋势吗？
希望可以在其他前端框架中共享组件生态。

### What does the proposed API look like?
```js

import {transformToWebcomponents} from "vue"

import myvuecomponent from "./mycomponent.vue"

const MyElement=transformToWebcomponents(myvuecomponent)

window.customElemnt.define('my-element', MyElement)
```

**Comment by posva** [comment]
https://github.com/vuejs/vue-web-component-wrapper
