### ISSUE TITLE
Need Option to Disable UpdateDomProps in Vue 

### ISSUE THREAD

**Issue by muthu32** [vuejs/vue#10471]
### What problem does this feature solve?
In order to avoid Jumping issue with contentEditable, I need an option to disable UpdateDomprops for vue. I also think this would not blot Vue for ContentEditable.

### What does the proposed API look like?
    if(elm.disableDomProps && elm.disableDomProps===1){return;}
    (or)  
    if(elm.dataset['disableDomProps']==='1'){return;}
    
to disable updateDOMProps

Please review below code for test case:
https://codepen.io/muthu32/pen/NZwKwz

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/10470#issuecomment-527874547

**Comment by muthu32** [comment]
@posva What about this https://codepen.io/muthu32/pen/qBWvaYq
Can I use it like this to prevent update props?
`this.$vnode.child._vnode.data.domProps['innerHTML'] = $event.target.innerHTML;`

**Comment by posva** [comment]
I wouldn't do that, it's a hack and it will break in future versions
