### ISSUE TITLE
regard an array as a plain object to make a[0] = 1 responsive

### ISSUE THREAD

**Issue by MrGoblet** [vuejs/vue#10478]
### Version
2.6.10

### Reproduction link
[https://codepen.io/dreamcarter/pen/ajoePd?editors=1111](https://codepen.io/dreamcarter/pen/ajoePd?editors=1111)

### Steps to reproduce
1. add an array to data like:
    data:{ arr : [1] }
2. binding arr[0] to template: <div>{{ arr[0] }}</div>
3. change arr with index: arr[0] = 2

### What is expected?
we should get <div>2</div>

### What is actually happening?
now we get <div>1</div>,the arr[0] is not responsive

---
In my opinion, we can regard arr as an plain object to make arr[0] = 2 responsive. 

In fact,we know that Object.keys(arr) => ["0"], and it means that arr is an object with a property "0".so if we execute this.walk(arr),arr[0]will be a responsive property now.In this case, we don't need function observeArray.We can make a change in constructor of Observer like this:

src/core/observer/index.js

if (Array.isArray(value)) {

      if (hasProto) {

        protoAugment(value, arrayMethods)

      } else {

        copyAugment(value, arrayMethods, arrayKeys)

      }

      this.observeArray(value)

    } else {

      this.walk(value)

    }

make a change:

if (Array.isArray(value)) {

      if (hasProto) {

        protoAugment(value, arrayMethods)

      } else {

        copyAugment(value, arrayMethods, arrayKeys)

      }

}

this.walk(value)

In this time,we regard arr = [1] as arr = { "0": 1 }.So, we don't need observeArray in the constructor of Observer and make all initial items of arr responsive.But if arr[0] doesn't exist initially, it is not responsive because it's a new property for arr.

**Comment by posva** [comment]
Please see https://vuejs.org/v2/guide/list.html#Caveats

**Comment by MrGoblet** [comment]
I know about that,however, if we use walk(arr) but not observeArray(arr),arr[0]=2 can also cause rerender.

**Comment by Justineo** [comment]
But you can always assign values at index larger than current length of the array. That would introduce new inconsistency. Though Mobx adopts a similar trick (observing 1000 array items in advance if I remember correctly), we are not introducing this into Vue for now.

**Comment by MrGoblet** [comment]
When we assign values at index larger than current length of array, we are adding properties to the array like we may do this on an object. This is certainly not allowed. But it may be useful for those items that are included in data initially, just like the properties we add to data directly. In my opinion, an array can be regarded as a plain object when initializing because Object.keys(arr) works well. Certainly we are not observing the items added to the array later.

**Comment by Justineo** [comment]
That introduces new caveats and there are a large number of users who are already familiar with the old caveats. I don't think it's worth the cost of education to do this at this moment. Anyway these caveats will be eliminated in Vue 3's Proxy implementation.

**Comment by MrGoblet** [comment]
Thanks for your answer, and I agree with you. Expecting for Vue 3.
