### ISSUE TITLE
Feature request: Need Option to Disable UpdateDomProps in Vue

### ISSUE THREAD

**Issue by muthu32** [vuejs/vue#10470]
### What problem does this feature solve?
In order to avoid Jumping issue with contentEditable, I need an option to disable UpdateDomprops for vue. I also think this would not blot Vue for ContentEditable.

Please review below code for test case:
https://codepen.io/muthu32/pen/NZwKwz

**Comment by posva** [comment]
Please see https://github.com/vuejs/vue/issues/4681#issuecomment-271450232 and https://github.com/vuejs/vue/issues/1670#issuecomment-153089559
