### ISSUE TITLE
v-bind directive is creating unnecessary attributes in DOM

### ISSUE THREAD

**Issue by lwxbr** [vuejs/vue#10481]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/vue-template-klp79?fontsize=14](https://codesandbox.io/s/vue-template-klp79?fontsize=14)

### Steps to reproduce
1. Create a dynamic component (```<component></component>```) or a normal component:
2. Bind a object with lots of properties.
3. Inspect the DOM and you see something like:
```
<div propA="propAValue" propB="propBValue ...></div> 
```

### What is expected?
Bind the properties properly in component without creating the attributes. I don't want the attributes in my component element, only the props.

### What is actually happening?
v-bind directive is creating attributes with the props of object binded to the component.

---
Can I disable this behavior?

**Comment by posva** [comment]
If you bind anything that isn't a prop, it will be bound as an attribute. That's intended. You should be able to disable automatic attribute inheritance with inheritAttrs: false in the component
