### ISSUE TITLE
async function prevent update on template

### ISSUE THREAD

**Issue by jfarellano** [vuejs/vue#10483]
### Version
2.6.4

### Reproduction link
[https://jsfiddle.net/uqogr6d4/7/](https://jsfiddle.net/uqogr6d4/7/)

### Steps to reproduce
<template>
    <div>
        <p v-if='loading'> loading </p>
        <p v-else> Done </p>
        <button @click="loaddata()">Load data</button>
    </div>
</template>

<script>
export default {
    data(){
        loading: false
    },
    methods: {
        async loaddata() {
            this.loading = true

            // Do async stuff ( encrypt text with openpgp.js )

            this.loading = false
        }
    }
}
</script>

### What is expected?
Shows loading while it encrypts the text

### What is actually happening?
Since it does not updates the template, all the componets get blocked and never shows loading

**Comment by posva** [comment]
This is normal, the js freezes the browser from rendering. You can offload the heavy work to a worker so the main thread remains fluid but this is just how the browser works

**Comment by sirlancelot** [comment]
Your demo isn't passing a callback to `setTimeout()`.
