### ISSUE TITLE
Filters in method arguments not recognised (pipe operator treated as bitwise-or)

### ISSUE THREAD

**Issue by ma7moudat** [vuejs/vue#10488]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/vue-template-n8fom](https://codesandbox.io/s/vue-template-n8fom)

### Steps to reproduce
The reproduction contains a filter `uppercase` and a component method `replace`

The template contains a working example of the filter: 
`{{ message | uppercase }}` correctly returns `TEST MESSAGE`

The template contains a working example of the method: 
`{{ replace('this message is: %msg%', '%msg%', message) }}` correctly returns `this message is: test message`

The template contains a BROKEN example of the combining the method with the filter: 
`{{ replace('this message is: %msg%', '%msg%', message | uppercase) }}` 
- Expected return: `this message is: TEST MESSAGE`
- Actual return: `this message is: 0` and the following warning is thrown
```
[Vue warn]: Property or method "uppercase" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

### What is expected?
Calling the filter on a method argument should return the output of the filter. 

### What is actually happening?
The pipe `|` is treated as a bitwise-or operator.

**Comment by posva** [comment]
That's normal, they are only supported at the end of the expression on `{{}}` and on v-bind
