### ISSUE TITLE
VueComponent instances retained after calling vm.$destroy

### ISSUE THREAD

**Issue by jukkakoskinen** [vuejs/vue#10480]
### Version
2.6.10

### Minimal reproduction

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script src="https://unpkg.com/vue"></script>

    <div id="app">
      <base-link>Link</base-link>
    </div>

    <button id="action">Load</button>

    <script>
      let vm
      const button = document.getElementById('action')
      button.addEventListener('click', () => {
        if (vm) {
          vm.$destroy()
          vm = null
          button.textContent = 'Load'
        } else {
          vm = new Vue({
            el: '#app',
            components: {
              BaseLink: {
                template: `<a href="#" @click="onClick"><slot /></a>`,
                methods: {
                  onClick(evt) {
                    evt.preventDefault()
                    console.log('clicked')
                  },
                },
              },
            },
          })
          button.textContent = 'Destroy'
        }
      })
    </script>
  </body>
</html>
```

### Steps to reproduce

- Load the app by clicking the button and take a heap snapshot
- Load/unload the app multiple times by clicking the button
- End in loaded stat and take a heap snapshot
- Search `Vue` in the memory snapshot viewer

I've personally tested this in Chrome.

### What is expected?

Vue retained size should not increase

![Screen Shot 2019-09-06 at 09 42 58](https://user-images.githubusercontent.com/664177/64410231-de96cd80-d08a-11e9-968c-fee7ae1815a7.png)
![Screen Shot 2019-09-06 at 09 43 03](https://user-images.githubusercontent.com/664177/64410232-de96cd80-d08a-11e9-85d8-5ee29bc0818e.png)

### What is actually happening?

Vue retained size increases

---
**Background:** I'm using Vue and Turbolinks together in a project where the backend serves HTML with Vue templates inlined. This means I have to create and destroy Vue instances when navigating between pages.

**Comment by posva** [comment]
I updated the issue @jukkakoskinen to be clear, I hope I didn't miss anything on the way, tell me if this is what you wanted to show in the first place

**Comment by jukkakoskinen** [comment]
Thanks @posva! Not only Vue instance count increases, but I also see a tangling VueComponent instance. It has something to do with the BaseLink components click handler, because without it the VueComponent instance gets collected.

![Screenshot 2019-09-06 at 11 40 56](https://user-images.githubusercontent.com/1039391/64414147-86b49280-d09b-11e9-88f8-1a683eaa7c34.png)

**Comment by kinow** [comment]
I think the `VueComponent` is indeed the issue. I think a `VueComponent` is a child of `Vue`? (at least looks like it is responsible for the extra instance [from this call in the code](https://github.com/vuejs/vue/blob/95d8afa07c4a84d6c178e220913cec4b1afcf21d/src/core/global-api/extend.js#L36))

So when the `BaseLink` component is added, we get two `Vue` instances. After you have a heap snapshot with the 2x `Vue` instances, try this in the browser console:

```
Object.create(Vue.prototype)
```

Then take another snapshot, and you should have three instances.

When the instance is destroyed, the `<base-link>Link</base-link>` does not exist any longer. It was replaced by a link. So the next time you create the `Vue` app again, the component is not found, so now you will have only 1 instance of `Vue`, as the `VueComponent` was not instantiated.

But if you re-create the `<base-link>Link</base-link>`, the heap snapshot should be consistent. Always 0 when destroyed, and always 2 when loaded (1 for `Vue` app, 1 for `VueComponent`).

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script src="vue.js"></script>

    <div id="app">
      <base-link>Link</base-link>
    </div>

    <button id="action">Load</button>

    <script>
      let vm
      const button = document.getElementById('action')
      button.addEventListener('click', () => {
        if (vm) {
          vm.$destroy()
          vm = null
          button.textContent = 'Load'
          // remove the dangling <a> element created by the VueComponent base-link...
          document.getElementById('app').children[0].remove()
          const baseLink = document.createElement('base-link')
          baseLink.innerHTML = 'Link'
          document.getElementById('app').appendChild(baseLink)
        } else {
          console.log('creating new instance!')
          vm = new Vue({
            el: '#app',
            components: {
              BaseLink: {
                template: `<a href="#" @click="onClick"><slot /></a>`,
                methods: {
                  onClick(evt) {
                    evt.preventDefault()
                    console.log('clicked')
                  },
                },
                beforeDestroy () {
                  console.log('ciao!')
                }
              },
            },
          })
          button.textContent = 'Destroy'
        }
      })
    </script>
  </body>
</html>

```

**Comment by jukkakoskinen** [comment]
Thanks for the comment @kinow! In your example, you remove the dangling <a> element, which seems to ensure that the VueComponent instance gets garbage collected. Seems like that after calling $destroy the link element is still bound to the `onClick` method, thus leading into that the instance is retained in memory. Possibly related: https://github.com/vuejs/vue/issues/7086
