### ISSUE TITLE
pls add api to purge cache of keepalive

### ISSUE THREAD

**Issue by ericwu-wish** [vuejs/vue#10487]
### What problem does this feature solve?
I don't want to add mixin to every route page, and I don't want to add global mixin to affect all components even with third parties

let's do this with one single code ok ?

### What does the proposed API look like?
    this.$keepalive[id].purge(Component)  // purge the cache of the Component's instance if exists

**Comment by posva** [comment]
To control what is cached by keep-alive, use `include` and `exclude` props. More at https://github.com/vuejs/vue/issues/8028

**Comment by ericwu-wish** [comment]
> To control what is cached by keep-alive, use `include` and `exclude` props. More at #8028

this is way more complex than a purge api

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/6259

**Comment by ericwu-wish** [comment]
I know there are ways to achieve what I want, but they all too complex. like I have to add dozens of name prop for the components which already existed.

I just find an ugly way to achieve this, one single line in the main component.

    maullyDelletedRoute.matched[maullyDelletedRoute.matched.length - 1].instances.default.$destroy()
