### ISSUE TITLE
And options.model.lazyEvent option

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10493]
### What problem does this feature solve?

`v-model.lazy` on component is ignored and wasted, while `.number` and `.trim` are effective.

### What does the proposed API look like?

```
options: {
    model: {
        prop?: string,// = 'value'
        event?: string,// = 'input'
        lazyEvent?: string,// = 'change'
    }
}
```

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/6914
