### ISSUE TITLE
Programmatically Create Slots

### ISSUE THREAD

**Issue by sercanparlak** [vuejs/vue#10492]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/dynamic-slot-two-level-sjsog](https://codesandbox.io/s/dynamic-slot-two-level-sjsog)

### Steps to reproduce
On the page click Create button. You will see a button and two textboxes. Then change the text of textboxes. After that click hi button. 

### What is expected?
The textboxes have to keep the entered new value.

### What is actually happening?
The textboxes loses the entered new value. They turn back to initial values. If you continue to change each the textbox value then the other textbox value returns to the previous entered value.

---
It's just a simple example to explain my problem. I'm trying to create programmatically components from an existing component framework. 
I tried to set slots vnode key value. It didn't solve too. Am i setting the slots.default in a wrong way?

**Comment by posva** [comment]
That usage in o Click is not really supported. Slots are read only and accessing the vnode like that will very probably break in future versions

Use a dynamic component to control what component is created. The while idea of slots is made around declarativity
