### ISSUE TITLE
Wrong version listed for script tag (CDN)

### ISSUE THREAD

**Issue by HTJin** [vuejs/vue#10498]
### Version
2.6.10

### Reproduction link
[https://vuejs.org/v2/guide/installation.html#CDN](https://vuejs.org/v2/guide/installation.html#CDN)

### Steps to reproduce
Installation > Direct script Include > CDN

### What is expected?
`<script src="https://cdn.jsdelivr.net/npm/vue@2.6.10"></script>`

### What is actually happening?
`<script src="https://cdn.jsdelivr.net/npm/vue@2.6.0"></script>`

The listed documentation is under the wrong version.

---
Was trying to create an SPA without node/webpack due to company restrictions. Copied the tag from documentation to wonder for hours why the app wasn't working.

**Comment by LinusBorg** [comment]
2.6.10 is the latest version and the link works as expected, serving Vue 2.6.10 UMD build.

I don't see why this should be the "wrong" version.
