### ISSUE TITLE
future version plan

### ISSUE THREAD

**Issue by jawharOmar** [vuejs/vue#10505]
like Angular 6 month major update , and lake of using typescript instate of javascript , our concern is we are searching a lot through internet for see do VueJS will make big migration and lack of back word compatibility like angularJS to angular

**Comment by posva** [comment]
> do VueJS will make big migration and lack of back word compatibility like angularJS to angular

You don;t have to worry about that, Vue.js will still mostly be what it is today. Breaking changes will not be a new framework
