### ISSUE TITLE
version in branch 2.6 is 2.5.21

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10502]
### Reproduction link

[2.6/dist/vue.js](https://github.com/vuejs/vue/blob/edf7df0c837557dd3ea8d7b42ad8d4b21858ade0/dist/vue.js#L2)

### Steps to reproduce

https://github.com/vuejs/vue/blob/edf7df0c837557dd3ea8d7b42ad8d4b21858ade0/dist/vue.js#L2

### What is expected?

Is branch `dev` the only correct way to get Vue 2.6?

### What is actually happening?

There is a lot feature of 2.6 not in 2.5, but both master and 2.6 branches are 2.5, especially the 2.6 branch name is misleading.

**Comment by Justineo** [comment]
Branch `2.6` is already merged into `dev` and no longer updated.

**Comment by LongTengDao** [comment]
@Justineo Thank you

Why not merge into `master`, is 2.6 still unstable?
