### ISSUE TITLE
`this` is set to `window` inside `v-model` (only when setting, not getting)

### ISSUE THREAD

**Issue by bandleader** [vuejs/vue#10508]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/69db10uh/4/](https://jsfiddle.net/69db10uh/4/)

### Steps to reproduce
`<input v-model="this.greeting" />`
On render, Vue correctly fills the textbox with `vueInstance.greeting`.
Type in the textbox, however and watch Vue happily update `window.greeting`.
Demo in the [fiddle](https://jsfiddle.net/69db10uh/4/).

### What is expected?
Vue should update `vueInstance.greeting`

### What is actually happening?
Vue updates `window.greeting`.

---
In the example above, I would obviously just use `v-model="greeting"`, which works fine.
But I discovered this as I was trying (inside `v-model`) to pass the Vue instance to a function:
`v-model="lens(this, 'greeting')"`
The function receives `window` as the first argument, and therefore does not work properly.

**Comment by posva** [comment]
Don't use `this` in templates. It's not supposed to be used

**Comment by bandleader** [comment]
@posva How do we get a reference to the Vue instance?

**Comment by bandleader** [comment]
@posva ?
