### ISSUE TITLE
Consider dropping support for older Chrome (<=55)

### ISSUE THREAD

**Issue by jodator** [vuejs/vue#10516]
### What problem does this feature solve?
We've encountered a bug where Vue was removing a single DOM element from an editor component.

Namely this code:

https://github.com/vuejs/vue/commit/0f2cb09444e8b2a5fa41aaf8c94e6f2f43e00c2f

It removes any content inside a Vue component - event if it is not a text node. This is potentially risky behavior for complex components like CKEditor where the component expects that DOM is not changed externally. More info here: https://github.com/ckeditor/ckeditor5/issues/2016#issuecomment-531158714.

### What does the proposed API look like?
After reading the original rationale behind this change (https://github.com/vuejs/vue/issues/6601#issuecomment-333656885) I'm not sure if Chrome 55 is still an issue as it was 2 years before.

Ideally, this code is not needed anymore but in a case that it is still needed then maybe an additional check for node type would be better.

**Comment by posva** [comment]
Some specific older versions of chrome are supported, dropping the support would be a breaking change, we cannot do it.
If you have a boiled down reproduction without ckeditor of the problem, please open a new issue with it

**Comment by Reinmar** [comment]
Hi! Thanks for the clarification. Where can we find information about which versions of Chrome are supported? I guess that at some point in the future you're going to finally drop support for some really old versions, as it happens with every project from time to time. I wonder if it's possible for us to somehow track this decision so we can remove the workaround from our code once you'll clean up Vue's implementation.
