### ISSUE TITLE
prop validator fails to generate validation error message when using Symbols

### ISSUE THREAD

**Issue by thomasleveil** [vuejs/vue#10519]
### Version
2.6.10

### Reproduction link

[https://jsfiddle.net/zs5dan7x/](https://jsfiddle.net/zs5dan7x/)

### Steps to reproduce
- pass a Symbol as the value of a component prop which expects another type

### What is expected?
the console should show the validation error message

### What is actually happening?
the prop validator tries to build an validation error message, it fails with :

    TypeError: Cannot convert a Symbol value to a string

**Comment by posva** [comment]
Marked as a bug because it crashes the application

**Comment by amumubuku** [comment]
Symbol('bad').toString()
