### ISSUE TITLE
v-model is extremely slow in big components

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue#10526]
### Version
2.6.10

### Reproduction link
[https://codepen.io/mikilll94/pen/RwbYrpz](https://codepen.io/mikilll94/pen/RwbYrpz)

### Steps to reproduce
Just run the code sample and type something in the input. As you can see there is a clear lag when you are typing.

### What is expected?
Everything should run smoothly.

### What is actually happening?
There is a clear lag when you are typing something in the input.

**Comment by posva** [comment]
It needs to re render the whole thing when you type. You can avoid this by wrapping either in a component: the input or the big list of divs

**Comment by highoncarbs** [comment]
@posva Hello , I'm facing a similar issue - though much got solved when using lazy, but still facing it on custom components . Are there any relevant docs/articles/patterns you'd recommend to follow when creating data heavy components? 

Thanks

**Comment by hkmsadek** [comment]
Facing same issue for a chat app :(
Anyone could solve?

**Comment by highoncarbs** [comment]
@hkmsadek hey , components is the way to go

**Comment by Kokleng-Dev** [comment]
> It needs to re render the whole thing when you type. You can avoid this by wrapping either in a component: the input or the big list of divs

Could you give sample of code? I am new to it, please 🙏🏻
