### ISSUE TITLE
当vue运行报错时,能够看到是用户写的哪行代码导致的报错

### ISSUE THREAD

**Issue by EggsBlue** [vuejs/vue#10520]
### What problem does this feature solve?
能够更快解决问题,极大提高用户体验

### What does the proposed API look like?
无

**Comment by Justineo** [comment]
使用 webpack 打包并且开启 sourcemap 功能即可。

**Comment by EggsBlue** [comment]
@Justineo  希望原生vue.js就可以支持,很多时候我们并不能使用webpack,而且好像sourcemap效果并不是很好?
