### ISSUE TITLE
Don't work ru-translation.

### ISSUE THREAD

**Issue by TheGreyCardinal** [vuejs/vue#10521]
### Version
2.6.10

### Reproduction link
[https://ru.vuejs.org](https://ru.vuejs.org)
![3](https://user-images.githubusercontent.com/46897110/64935193-77320800-d858-11e9-9b13-4670851cea1d.png)

### Steps to reproduce
Open https://ru.vuejs.org from Russia.

### What is expected?
Opening your site.

### What is actually happening?
ERR_CONNECTION_REFUSED

---
Not working ru-version of the site when accessing from Russia. Only via VPN.

**Comment by posva** [comment]
That's your VPN issue blocking the address, the site is up and running
