### ISSUE TITLE
How do you clear a number input with 'e' in it?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [vuejs/vue#10525]
### Version
2.6.10

### Reproduction link
[https://codepen.io/tillysinteriors/pen/PoYBrXv](https://codepen.io/tillysinteriors/pen/PoYBrXv)

### Steps to reproduce
 - Open the codepen link (or make something with a number `v-model` and a 'clear' button that sets the value to `''` or `null`).
 - Enter `e` on its own. This is acceptable (though invalid) for a number input.
 - Press clear, or somehow set the `v-model` variable to `''` or `null`.

### What is expected?
The input should clear, and have nothing in it.

### What is actually happening?
The input still has `e` left in it.

---
Since the input `value` according to javascript is `''` and therefore falsy/zero-length, maybe Vue is checking one of these conditions before setting the value. This is a quirk with javascript that should be accounted for. I suggest removing the check (if it exists).

**Comment by MarcelloTheArcane** [comment]
Related: https://github.com/vuejs/vue/issues/4742

**Comment by posva** [comment]
With the number modifier, anything non valid will stay like that. If you want to fully control it, you can use a regular v model and control the coerced value through a prop
