### ISSUE TITLE
SSR hydration issue with v-if false

### ISSUE THREAD

**Issue by CDNRocket** [vuejs/vue#10528]
### Version
2.6.10

### Reproduction link
[https://github.com/anthonygore/vue-js-laravel-ssr](https://github.com/anthonygore/vue-js-laravel-ssr)

### Steps to reproduce
These are the cases:
-App.vue

HYDRATION SUCCESS:
```
<template>
  <div id="app">
    <div v-if="1 === 2">show</div>
  </div>
</template>
```

HYDRATION FAIL:
```
<template>
  <div id="app">
    <div>Hello world</div>
    <div v-if="1 === 2">show</div>
  </div>
</template>
```

HYDRATION SUCCESS:
```
<template>
  <div id="app">
    <div>Hello world</div>
    <div v-show="1 === 2">show</div>
  </div>
</template>
```

### What is expected?
Hydration should work in all of these 3 cases.

### What is actually happening?
Hydration fails when v-if is false and in combination with other elements in the component template.
v-show works fine in any case.

---
Why does this happen? It's something related to `<!---->` comment that will appear when an element is hidden by v-if? (it is same in both server and client rendering).

I've followed Anthony Gore guide, then i've provided his github repo...with the only exception that I've used webpack.

**Comment by posva** [comment]
When reporting a bug we need a boiled down repro with no or minimal dependencies (eg: no Laravel). Here I suspect that comments are being removed causing the SSR mismatch.
If you manage to reproduce it in a boiled down environment, please open a new issue. You can check https://ssr.vuejs.org for more info.

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by CDNRocket** [comment]
Indeed, my issue was with webpack...nothing wrong with Vue or Anthony guide. Thanks.

**Comment by pricetula** [comment]
facing a similar issue

**Comment by prafulprajapati** [comment]
facing a similar issue when v-if is false

**Comment by Tofandel** [comment]
Same issue, pretty much if you use v-if and in SSR it evaluates to false after the render but on the front it evaluates to true for a blimp (eg: before mount) and then back to false on mount, then vue tries to append nodes to comments (which is not possible) maybe we should just catch this edge case and let it be without throwing error and then it will mount correctly, because right now the error happens beforemount and prevents the entire app from running
