### ISSUE TITLE
TypeScript can’t infer types for ESM build

### ISSUE THREAD

**Issue by dangodev** [vuejs/vue#10522]
### Version
2.6.10

### Reproduction link
[https://github.com/dangodev/vue-esm-types](https://github.com/dangodev/vue-esm-types)

### Steps to reproduce
In TypeScript specifying a specific build like so:

```
import Vue from 'vue/dist/vue.esm.browser';
```

Results in the following error:

```
Could not find a declaration file for module 'vue/dist/vue.esm.browser'. '/node_modules/vue/dist/vue.esm.browser.js' implicitly has an 'any' type.
  Try `npm install @types/vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue/dist/vue.esm.browser';`
```

### What is expected?
Similar to lodash, or other projects, importing submodules should infer types from the root module.

### What is actually happening?
TypeScript doesn’t have any definitions for any Vue builds other than the default (`pkg.main`). Vue should ship types for all builds in `dist/`.

**Comment by posva** [comment]
You have to import the package directly `import Vue from 'vue'` and alias the import when needed. I don't think duplicating the files in the dist folder is a good idea

This doesn't compare to lodash imports: `import debounce from 'lodash/debounce'` because in Vue there is only Vue to be imported

**Comment by dangodev** [comment]
I gotcha. This makes sense in a webpack sense, but I should have stated I’m not using webpack at all. I’m using @pika/web, and writing ESM import statements that the browser will understand.

I’m currently doing what you suggest, and running Babel afterward to rename the import. But it’d save some configuration not if any files were duplicated in `dist` like you said, but simply the types that Vue shipped applied to all the modules within `dist` and not just `pkg.main`. Maybe it could be a small configuration change?
