### ISSUE TITLE
Value of select element is not updated when options are changed

### ISSUE THREAD

**Issue by RoboBurned** [vuejs/vue#10527]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/rftv5zs4/](https://jsfiddle.net/rftv5zs4/)

### Steps to reproduce
Render a select element bound with v-model to some value. Options should be dynamically generated by iterating with v-for over a computed.
Select an item in the select.
Somehow trigger the computed to return new list of options.

### What is expected?
Value should be updated to undefined, watcher should be triggered if new options do not contain previously selected value.

### What is actually happening?
Previous selected value is kept in model even if updated list of options does not contain selected value.

---
This works fine in 2.0.2 and was broken in 2.0.3 and later up to the latest 2.6.10 version.

**Comment by RoboBurned** [comment]
Tested on 2.6.10 in Chrome 79 and Firefox 69. The issue is reproducible.
Dropdown does not contain a banana option but a value bound to the select element  has value "banana".
[See video](https://vimeo.com/360490916)

**Comment by posva** [comment]
Ah, sorry, I misunderstood: I thought you were saying the select still displayed a `banana` value.
Changing the option list does not change the bound value to v-model, that's intended. If you want to change the coerce the value, you will have to manually do it.

I don't recall the exactly what happened as that version is very old but it's probably a bugfix

**Comment by RoboBurned** [comment]
@posva  I don't think this is intended behavior.
First, it leads to the situation where DOM and vm become out of sync. This is not how it is supposed to be.
Second, there is a comment in the componentUpdated function in `vue\src\platforms\web\runtime\directives\model.js` file:
```
// trigger change event if
// no matching option found for at least one value
const needReset = el.multiple
  ? binding.value.some(v => hasNoMatchingOption(v, curOptions))
  : binding.value !== binding.oldValue && hasNoMatchingOption(binding.value, curOptions)
if (needReset) {
  trigger(el, 'change')
}
```
So it is supposed to call the `change` event if options were changed in a way when currently selected value is no longer there.
This does not happens because of additional check of binding value changes that was added when someone was fixing another bug  https://github.com/vuejs/vue/issues/3917

I think I can make a pull request with test to fix.
