### ISSUE TITLE
Vue enters an infinite update loop and hangs browser

### ISSUE THREAD

**Issue by ajdalshov** [vuejs/vue#10539]
### Version
2.5.18-beta.0

### Reproduction link
[https://privatebin.net/?d4fe4900af2cbe30#4ZgrDDZHqtheegjKWA73BvAMdkUbiRvuou9SrVjhoGgp](https://privatebin.net/?d4fe4900af2cbe30#4ZgrDDZHqtheegjKWA73BvAMdkUbiRvuou9SrVjhoGgp)

### Steps to reproduce
Run the code pasted in the minimal reproduction link or visit https://ajd2.rec.vc/vue_debug.html

Then:

1. Click the Show Dialog button
2. Close the dialog
3. Click the Show Dialog button again

### What is expected?
Dialog should show when opening it the second time.

### What is actually happening?
Vue enters an infinite update loop state and the browser hangs.

---
The code provided in the link is just some minimal example code put together in one file that is required to reproduce the issue, it's basically just pieces pulled out of a larger project. The bug was discovered when upgrading Vue from 2.5.17 to 2.6.10 (no other change was made to the project).

The specific Vue commit that causes it is commit 530ca1b2db315fbd0e360807b2031d26665c5d3d and the first Vue version to include this is v2.18-beta.0. The problem persists all the way up to latest v2.6.10.

It seems it's the flushSchedulerQueue function that keeps looping as the queue array is rapidly increasing.

This is probably a corner case and it's unclear for now specifically what causes it since there are several ways to make the infinite loop not occur.

Some minor tweaks to the example code can be made to make it run without crashing.

1. If removing content from the tabs, the infinite update loop does not occur. The content type inside the tabs does not matter, just having a simple <p>test</p> element inside any of the tabs is enough to reproduce.

2. Another way is to replace <ui-tab label="xxx" with <md-tab md-label="xxx" to use the Vue Material component directly instead of a wrapper component.

3. A third way is to add a property somewhere that changes on each opening of the dialog, eg:

<ui-dialog :timestamp="timestamp"

where timestamp is data property: new Date().getTime(); that is set in open function

4. A fourth way is to remove the v-if="showDialog" clause that is right after the transition, but this is there to act as a workaround for tab content initially not showing (I think it was). This may be bad design in the first place, but regardless, corner cases like this should be handled gracefully and not throw Vue into an infinite loop state.

This happens basically across all browsers, latest version of Chrome, Safari, FireFox, MS Edge.

**Comment by posva** [comment]
Hi, please provide a boiled down runnable repro when reporting a bug: no vue-material or external libraries minimum code possible (no transition if no necessary), and a code sandbox, jsfiddle, codepen or similar). Ping me when you have it and I will take a look

Note: Since the problem happens when upgrading to 2.6, [it may be related to micro/macro task changes](https://github.com/vuejs/vue/releases/tag/v2.6.0)

**Comment by ajdalshov** [comment]
Ok, I can try to do that, but it's a hard one to reproduce. It's not related to micro/macro tasks as the bug is narrowed down to commit 530ca1b2db315fbd0e360807b2031d26665c5d3d which was first released with v2.5.18-beta.0 and has been there since.

**Comment by ajdalshov** [comment]
I've stripped off what I could, but as I said, this is really difficult to reproduce without having Vue Material included, probably due to some corner case of nested slots. Instead of spending hours to figure out the exact composition that breaks things I hope you can live with having that there? The point is that it's the Vue commit mentioned that is causing things to break, nothing else.

Also the transition is needed there for this to break, so it's probably part of what causes the commit in question to fail. I hope at least you guys can have a look at it, run the JSFiddle, follow the 3 steps explained and watch the browser hang.

**Comment by posva** [comment]
It does hang. Could you open an issue in vue-material repo then? They will probably be able to know if it comes from their codebase or not and produce a boiled down repro if it comes from Vue. Thanks.

**Comment by ajdalshov** [comment]
Well, I've already narrowed it down to a specific Vue commit https://github.com/vuejs/vue/commit/530ca1b2db315fbd0e360807b2031d26665c5d3d by building Vue from source checking out the commit before this one and everything works fine, and then building Vue with this commit, and then it breaks. Also pausing execution in the debugger after it hangs will show that it's the queue array looped over in the Vue function flushSchedulerQueue that is rapidly increasing, most likely caused by the changes in the mentioned commit.

Vue Material is just used here indirectly to provoke the bug. However if you insist I can try to find the exact composition of nested slots and transition that will trigger this, it's just a bit tedious to try and debug this since I'm not familiar with Vue internals. But you guys should have a pretty good starting point to look at when it specifically boils down to this specific commit in Vue core.
