### ISSUE TITLE
v-slot question

### ISSUE THREAD

**Issue by yoonasy** [vuejs/vue#10537]
### Version
2.6.10

### Reproduction link
[http://vuejs.com](http://vuejs.com)

### Steps to reproduce
在for循环里面插入了一个`suffix`具名插槽，想通过`$slots`去判断外部是否传入，但是拿不到传入名为`suffix`的插槽

There is a slot named `suffix` inserted into the for loop, and you want to use the $slots to determine whether the external slot is passed in, but you can't get the slot named `suffix` passed in

![image](https://user-images.githubusercontent.com/24489180/65305840-aa58fc00-dbb6-11e9-8953-7adb5c6fed44.png)

### What is expected?
能够在`$slots`拿到，用作判断

### What is actually happening?
不会添加到$slots里面
Will not be added to `$slots`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
