### ISSUE TITLE
add a switch to the v-html directive so that it does not affect the global css

### ISSUE THREAD

**Issue by TheShineJames** [vuejs/vue#10532]
### What problem does this feature solve?
add a switch to the v-html directive so that it does not affect the global css
because css in v-html directives will affect the global

### What does the proposed API look like?
example :  v-html="html" v-html-css="false"

**Comment by posva** [comment]
You shouldn't put CSS there anyway but `v-html` is a simple setter for `innerHTML`. This feature would involve parsing and rewriting the CSS, which is quite heavy

**Comment by TheShineJames** [comment]
when i want to rendering email content, now the email do not accept my control. What should I do at this time?

**Comment by posva** [comment]
for email purposes using naming conventions in CSS would probably work.
Remember we have a [forum](http://forum.vuejs.org/) and a [Discord chat](https://vue-land.js.org/) for questions 🙂

**Comment by TheShineJames** [comment]
OK, thanks.
Let me try it out.
