### ISSUE TITLE
Give a way to use shadow root in template/render

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10548]
### What problem does this feature solve?

Shadow root can be used to make css scoped. But when I wrap all my components with shadow root, I must write two or more components every time for each component, and handly write props pass rule in outer shell component, handly create shadowRoot, and construct inner component(s) mount on it.

```js
const Inner1 = Vue.extend({
    props: [ 'x', 'y' ],
    template: '<div> {{ x }} {{ y }} </div>',
});

const Inner2 = Vue.extend({
    props: [ 'z' ],
    template: '<div> {{ z }} </div>',
});

const Outer = Vue.extend({
    props: [ 'x', 'y', 'z' ],
    template: '<div />',
    mounted () {
        const shadowRoot = this.$el.attachShadow();
        shadowRoot.appendChild(document.createElement('style')).textContent = 'css 1 ...';
        shadowRoot.appendChild(document.createElement('style')).textContent = 'css 2 ...';
        new Inner1({
            el: shadowRoot.appendChild(document.createElement('div')),
            propsData: { x, y },
        });
        new Inner2((
            el: shadowRoot.appendChild(document.createElement('div')),
            propsData: { z },
        });
    },
});
```

### What does the proposed API look like?

`<shadow></shadow>` is redundancy and will bring break change by increasing reserved tag name list. `v-shadow` won't serve all case, and hard to add prop in the furthur, and also bring break change with reserved directive list. So I suggest `<?shadow>`:

```html
<template>
    <div>
        <?shadow mode="closed" ?>
        <style> css 1 ... </style>
        <style> css 2 ... </style>
        <div> {{ x }} {{ y }} </div>
        <div> {{ z }} </div>
    </div>
</template>
```

Even support:

```html
<template>
    <?shadow mode="closed" ?>
    <style> css 1 ... </style>
    <style> css 2 ... </style>
    <div> {{ x }} {{ y }} </div>
    <div> {{ z }} </div>
</template>
```

Then the `options.el` can be `string | Element | ShadowRoot`, and `vm.$el` can be `Element | ShadowRoot`. And `vm.$createElement` in render will be extended to allow:

```js
function render (createElement) {
    return createElement('?shadow', { mode: 'closed' }, [ ... ]);
}
```

**Comment by posva** [comment]
Given that shadow DOM is not supported by every browser supported by Vue and that we already have scoped CSS when using vue files, it makes sense for this to exist as a user-land solution
