### ISSUE TITLE
Input autocomplete off does not work

### ISSUE THREAD

**Issue by IuriPires** [vuejs/vue#10545]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/nvo9x0ru/25/](https://jsfiddle.net/nvo9x0ru/25/)

### Steps to reproduce
We have a componet called SmartInput in our project and it's used all around the application, somehow autocomplete="off" does not work. Does not matter what we try to do, it does not work. For exemple, if you have a login page and Chromes ask you to save the email and password and you try to use this same component all way around the application, Chrome will auto fill the input for you, but we don't want it.  We got a form which is been filled with the login information just because we use that component.

### What is expected?
autocomplete="off" to work.

### What is actually happening?
autocomplete="off" is ignored.

---
If you guys want, I can show and send some evidence to make it easier to find a way to fix this bug

**Comment by leopiccionia** [comment]
This is most likely not Vue-related. Most modern browsers ignore `autocomplete="off"` for login fields (see [section on MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields)). The browser is probably considering, wrongly, that those other forms are login forms, too.

One way to avoid that is making inputs `name` attribute random (you can correct it before form submission, if needed).

**Comment by Justineo** [comment]
As @leopiccionia said, it’s not related to Vue.
