### ISSUE TITLE
Vue SSR not re-rendering parent component

### ISSUE THREAD

**Issue by allaud** [vuejs/vue#10540]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-bbyl6?fontsize=14](https://codesandbox.io/s/vue-template-bbyl6?fontsize=14)

### Steps to reproduce
Run server rendering for the provided application. For some reason the parent component (App.vue) does not change the value of `test` in  its template.

### What is expected?
Browser html to be the same with server html:

```
<div class="feed">
  ***initial!!!!!!!!!***
  <div class="feed-list">
  ***initial!!!!!!!!!***
</div></div>
```

### What is actually happening?
Server HTML doesn't contain change in parent component:

```
<div data-server-rendered="true" class="feed">
  ***initial***
  <div class="feed-list">
  ***initial!!!!!!!!!***
</div></div>
```

---
Works correct in browser, but something happens in server env. I'm using node v10.16.3

**Comment by allaud** [comment]
@posva I'm using serverPrefetch, see PostList:20

**Comment by allaud** [comment]
@posva what event/promise should I use on the parent? I was trying to resolve child's serverPrefetch promise a second later (using additional setTimeout), but the issue still exists:

```
        setTimeout(() => {
          this.updateTest();
          resolve();
        }, 1500);
```

**Comment by posva** [comment]
you need to wait for the same promise on both serverPrefetch, you can unify the action call so it only happens once with something like https://github.com/posva/p-singleton, but please use the forums to ask questions.
