### ISSUE TITLE
Renderless Component in Typescript

### ISSUE THREAD

**Issue by joeizang** [vuejs/vue#10543]
### Version
2.6.10

### Reproduction link
[https://codepen.io/ruth-izang/pen/GRKPKGp](https://codepen.io/ruth-izang/pen/GRKPKGp)

### Steps to reproduce
just create a new vue project with typescript support, create a renderless component as a typescript file so eg. ProcessUser.ts using the Vue.extend style and just put the render function inside

### What is expected?
I should be able to return anything via scopedSlots to a random parent and not show errors in vscode or during build

### What is actually happening?
shows red squiggles in vscode and shows errors during build of project

---
encountered this when migrating a js based renderless component to typescript at work and the typescript version of the component just spits these errors: 

(method) ComponentOptions<Vue, unknown, unknown, unknown, never[], Record<never, 
       any>>.render? 
       (createElement: CreateElement, hack: RenderContext<Record<never, any>>): VNode
     No overload matches this call.
    The last overload gave the following error.
    Argument of type '{ render(): void; }' is not assignable to parameter of type 
    'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, 
    PropsDefinition<Record<string, any>>, Record<string, any>>'.
      Types of property 'render' are incompatible.
        Type '() => void' is not assignable to type '(createElement: CreateElement, hack: 
    RenderContext<Record<string, any>>) => VNode'.
          Type 'void' is not assignable to type 'VNode'.ts(2769)
    vue.d.ts(90, 3): The last overload is declared here.

**Comment by posva** [comment]
both doing `return this.$scopedSlots.default({})` or `return h('div')` work. Don't add the explicit return type, that way TS will pick up the right overload.
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by joeizang** [comment]
didn't specify a return type and I actually asked the question on stackoverflow https://stackoverflow.com/questions/58002254/renderless-vue-component-in-typescript but didn't seem to be getting anywhere. I don't know much but this seems strange as even without returning anything from the method it errors out and returning this.$scopedSlots.default({}) still gives errors. Ok can clear instructions be given about this for typescript? cos everywhere I have checked its been js tutorials or guidelines. Thank you for your help

**Comment by joeizang** [comment]
got a solution to the problem, https://stackoverflow.com/questions/58002254/renderless-vue-component-in-typescript/58047657#58047657
