### ISSUE TITLE
Prop value empty string is cast to true

### ISSUE THREAD

**Issue by trickstival** [vuejs/vue#10555]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/trickstival/Ltpr2ysw/13/](https://jsfiddle.net/trickstival/Ltpr2ysw/13/)

### Steps to reproduce
Check out the output value in the dom. It's true.

### What is expected?
Since in JavaScript `''` is falsy, I think it would make more sense to output `''` itself or `false`.

### What is actually happening?
It outputs `true`.

---
If you switch the prop type option to `[String, Boolean]` it should work, as it prioritizes `String` values, even if the parent is actually passing a string, which I don't know if makes sense. 

It's probably related to this part of the code:
https://github.com/vuejs/vue/blob/33e669b22f69a1f9c9147528360fe0bba85534f0/src/core/util/props.js#L31

**Comment by posva** [comment]
This is because `Boolean` is placed first, place `String` first if you prefer the string casting

**Comment by trickstival** [comment]
This issue is about the cast value output. Why is it cast to `true` when `''` is falsy?
Wouldn't it make more sense to cast it to `false` since it's empty?

**Comment by posva** [comment]
Because a boolean attribute is true even when an empty string: `autoplay=""`, Boolean props reflect that behavior

**Comment by trickstival** [comment]
Oh, got it! Sorry
