### ISSUE TITLE
Method runs twice with v-for when a node loaded asynchronous

### ISSUE THREAD

**Issue by quangvision** [vuejs/vue#10559]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/quang_it/c1sm8dox/](https://jsfiddle.net/quang_it/c1sm8dox/)

### Steps to reproduce
Please check my jsfiddle https://jsfiddle.net/quang_it/c1sm8dox/

### What is expected?
The method "numbers()" should only run once

### What is actually happening?
The method "numbers()" seems run twice

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/10558#issuecomment-534967376
