### ISSUE TITLE
Swap out Old Image for Patreon Bronze Backer

### ISSUE THREAD

**Issue by PhilipJohnBasile** [vuejs/vue#10557]
![name](https://user-images.githubusercontent.com/1419847/65564381-b62c2180-df1a-11e9-8197-05fd73f86ad5.gif)
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/BACKERS.md](https://github.com/vuejs/vue/blob/dev/BACKERS.md)

### Steps to reproduce
Goto Patreon Bronze Backers section and swap out image.

### What is expected?
new image is needed and is attached to this ticket

### What is actually happening?
old image appears

**Comment by posva** [comment]
ping @yyx990803

**Comment by yyx990803** [comment]
Closed via 235064ebe
