### ISSUE TITLE
Weird Error: Method runs twice with v-for when a node loaded asynchronous

### ISSUE THREAD

**Issue by quangvision** [vuejs/vue#10558]
**Problem**
A method seems get called twice within v-for loop related to a node loaded with v-if async.
**Reproduced**
Please check my jsfiddle [https://jsfiddle.net/quang_it/c1sm8dox/](url)
**How to debug**
Open up chrome devtools, you will see "loaded" printed out twice

Thank :)

**Comment by posva** [comment]
This is expected, the whole template renders when something changes, calling the method again
