### ISSUE TITLE
vue.js with es5, modules, and dev conditionals

### ISSUE THREAD

**Issue by taralx** [vuejs/vue#10561]
### What problem does this feature solve?
Right now you can kind of get any two of these, but not all three:

vue.esm.browser.js - no dev conditionals
vue.esm.js - no es5
vue.js - no modules

### What does the proposed API look like?
vue.esm.es5.js or something similar, where classes have not been transpiled out. It is very useful for subsequent compiling with JSCompiler.

**Comment by posva** [comment]
the vue.esm.browser build does have dev conditionals and is using es5

**Comment by taralx** [comment]
I apologize for being unclear. By dev conditionals I mean that there are references to NODE_ENV in the file so that JSCompiler can conditionally remove dev code.

**Comment by taralx** [comment]
@posva

**Comment by posva** [comment]
what is JScompiler? I couldn't find a relevant result when searching

**Comment by sirlancelot** [comment]
Google Closure Compiler should handle Vue.js quite well. If you're having problems with it, I think you're best bet is to ask the Vue.js Discord or Forum.

**Comment by taralx** [comment]
It does, but I currently have two versions of Vue that I select from with build rules. I'd prefer to use just one by having conditionals.

It's useful to have es5 inputs because it can extract additional type information, and modules make integration with larger systems easier.

I'll look at how hard this is to do myself.
