### ISSUE TITLE
backdrop-filter inside <transition> not working when animation is runing on latest chrome

### ISSUE THREAD

**Issue by gaodeng** [vuejs/vue#10577]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/mLz06eu8/1/](https://jsfiddle.net/mLz06eu8/1/)

### Steps to reproduce
click the toogle button on this page  https://jsfiddle.net/eph3098z/5/
backdrop-filter inside transition not working when animation is runing on latest chrome

### What is expected?
backdrop-filter inside transition should working when animation is runing

### What is actually happening?
backdrop-filter inside transition not working when animation is runing on latest chrome

**Comment by posva** [comment]
This doesn't seem to be related to Vue as it happens with just CSS

**Comment by gaodeng** [comment]
Sorry, I just realized that this is a chrome bug.

**Comment by katsar0v** [comment]
@gaodeng did you find a solution?
