### ISSUE TITLE
Vue watch deep doesn't work on more then 1 level

### ISSUE THREAD

**Issue by terror2012** [vuejs/vue#10574]
Data structure example: 
`{cpu: 
     {itemID:
            {quantity: 1}}}`
As you can see in the data above, quantity is part of an object, that's part of an object within cpu (basically 2 levels of depth). A watcher with `deep: true` doesn't trigger an update in that case.
When the data structure is:
`{itemID: {quantity: 1}}`
it works fine, updating whenever quantity is updated. In vue docs, the description of deep is:

> the callback will be called whenever any of the watched object properties change regardless of their nested depth

Is there a workaround to force the watcher to trigger on the first data structure?
Using vue: 2.5.17 with vue cli 3.5.0

**Comment by posva** [comment]
I think you are missing the quotes around `quantity` in the second argument: `his.$set(variable['cpu'][itemID], 'quantity', variable['cpu'][itemID].quantity + 1)`
