### ISSUE TITLE
改变页面中的变量会触发html中调用的方法被执行

### ISSUE THREAD

**Issue by zbjy** [vuejs/vue#10571]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/2L0x65du/2/](https://jsfiddle.net/2L0x65du/2/)

### Steps to reproduce
1、在html中调用getSum方法实现合计功能
2、点击修改按钮改变visible变量的显示与隐藏，这个变量和getSum方法的变量完全没影响，但是改变visible变量的同时会触发getSum方法的执行，这是为什么

### What is expected?
希望改变visible变量，不会触发getSum方法的执行

### What is actually happening?
希望改变visible变量，不会触发getSum方法的执行

**Comment by posva** [comment]
This is expected, Vue renders the whole template when something changes, calling the method again. Use a computed property if you want things to be executed based on data, it's also  _ the Vue way_

**Comment by zbjy** [comment]
> This is expected, Vue renders the whole template when something changes, calling the method again. Use a computed property if you want things to be executed based on data, it's also _ the Vue way_
没办法用计算属性，我实际业务中是需要传递参数的，如果用计算属性传参的话，也是一样会被多次触发，复现连接：https://jsfiddle.net/uLg2pd3j/

**Comment by posva** [comment]
I see, maybe something like https://github.com/posva/vue-local-scope will help you.

Remember that we have the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by zhangzhonghe** [comment]
如果想不触发那个getSum方法，可以在外面声明个变量，用来控制getSum方法是否要运行。

**Comment by zbjy** [comment]
> 如果想不触发那个getSum方法，可以在外面声明个变量，用来控制getSum方法是否要运行

如果多个地方调用，那岂不是要定义多个变量？？

**Comment by zhangzhonghe** [comment]
你没明白，你把getSum放到那个位置，在触发更新的时候肯定会重新调用它的。不要跟事实过不去。
