### ISSUE TITLE
iphone11 ios13 webview click not work 

### ISSUE THREAD

**Issue by MarsCaiWORD** [vuejs/vue#10592]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/aruwk6sp/](https://jsfiddle.net/aruwk6sp/)

### Steps to reproduce
iphone11 ios13 webview click not work
but safari browser and other browser is ok

html:
<div @click="clickfun()"></div>

### What is expected?
iphone11 ios13 webview click work

### What is actually happening?
iphone11 ios13 webview click not work

**Comment by posva** [comment]
Tested on iOS 13 Safari iPad and iPhone and works
