### ISSUE TITLE
Russian doc subdomain IP is blocked by Roscomnadzor

### ISSUE THREAD

**Issue by Mihail0v** [vuejs/vue#10594]
### Version
2.6.10

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
-

---
;; ANSWER SECTION:
ru.vuejs.org.		237	IN	A	104.18.49.43
ru.vuejs.org.		237	IN	A	104.18.48.43

ip: 104.18.49.43
Запись 1661273 ip 104.18.49.43 решение № 27-31-2018/Ид2971-18 от 16.04.2018, Генпрокуратура; дата включения: 31.07.2019 15:12
Запись 1686897 ip 104.18.49.43 решение № 27-31-2018/Ид2971-18 от 16.04.2018, Генпрокуратура; дата включения: 13.08.2019 20:25

**Comment by posva** [comment]
They probably banned your VPN and in that case there is nothing we can do.
If it was the IP, we will need way more information about what to do, if we can do anything at all, to unblock the ip, but that should be said in the vuejs/vuejs.org repo

**Comment by bravik** [comment]
@posva Why did you close the issue? They banned your HOSTING IP as you use shared cloud hosting obviously. And all Russian community suffers from absence of the docs! There is nothing anybody but VUE mantainers could do - please change your server IPs

**Comment by posva** [comment]
> If it was the IP, we will need way more information about what to do, if we can do anything at all, to unblock the ip, but that should be said in the vuejs/vuejs.org repo

https://github.com/vuejs/vuejs.org/issues/2325
