### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by kooy** [vuejs/vue#10603]
### Version
2.6.10

### Reproduction link
[https://testnet.ruffchain.com/](https://testnet.ruffchain.com/)

### Steps to reproduce
chrome 浏览器
当 “超级节点列表”  位于页面中部附近时， 页面开始自动下移。 每次更新数据，都会下移。

### What is expected?
chrome 浏览器不要往下移动

### What is actually happening?
每次更新数据，都会移动。

---
火狐浏览器没有问题。 我感觉是 transition-group 导致的

这是源代码  https://github.com/ruffchain/explorer/blob/master/src/views/Home/Home.vue

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

When reporting a bug, a boiled down repro with concrete reproduction steps and actual information about the problem are also necessary
