### ISSUE TITLE
Bug of transition-group

### ISSUE THREAD

**Issue by kooy** [vuejs/vue#10605]
### Version
2.6.10

### Reproduction link
[https://testnet.ruffchain.com](https://testnet.ruffchain.com)

### Steps to reproduce
When the transition-group is updated, the page moves down. Only appear in Chrome.

### What is expected?
Don't move when transition-group is updated

### What is actually happening?
Move down every 10 seconds

---
Source code: 

```
<section class="card blocks latest-list">
    <span class="title">最新不可逆区块</span>
    <transition-group name="flip-list" tag="ul">
        <li v-for="block in blocks" :key="block.number" class="list-item">
            <div class="lf-box">
                <div>
                    区块#
                    <router-link :to="'/block/' + block.number">
                        {{ block.number }}
                    </router-link>
                </div>
                <div>包含 {{ block.txs }} 个交易</div>
            </div>
            <div class="time">{{ block.timeAgo }}</div>
        </li>
    </transition-group>
</section>
```

**Comment by posva** [comment]
Hey, as said in the other issues, we require a minimal runnable repro, not your whole project. You can take a look at other labeled issues for examples if that isn't clear for you. If you keep opening the same non-conformant issue, we will have to block you.

**Comment by Justineo** [comment]
@kooy https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro
