### ISSUE TITLE
Child instance events do not work when nesting vue instances

### ISSUE THREAD

**Issue by furukawatts** [vuejs/vue#10606]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/6keoty50/1/](https://jsfiddle.net/6keoty50/1/)

### Steps to reproduce
1. Load development version.
2. Nested vue instances.
3. Add `v-pre` to the child instance.
4. Add click event to child instance.
5. Click a child instance.

### What is expected?
I want the event of the child instance to work.

### What is actually happening?
If you are loading a development version, you will get an error.
There is no problem if you are loading the production version.

**Comment by posva** [comment]
Nesting `new Vue` is not supported. When doing `new Vue` on an element, you should only create Vue instances through components
