### ISSUE TITLE
Vue3 The props in step after the createComponent function is passed into Props should be read-only

### ISSUE THREAD

**Issue by dangaogit** [vuejs/vue#10619]
### What problem does this feature solve?
export function createComponent\<Props\>(
  setup: (props: Props , ctx: SetupContext) => object | (() => VNodeChild)
): (props: Props) => any

### What does the proposed API look like?
type Readonly\<T\> = { [K in keyof T]: T[K] };
export function createComponent\<Props\>(
  setup: (props: Readonly\<Props\> , ctx: SetupContext) => object | (() => VNodeChild)
): (props: Props) => any

**Comment by posva** [comment]
Please don't post Vue 3 issues on this repository. For the moment we only have the capacity to accept pull requests on vue-next repository, feel free to submit one if nobody has done it yet. Issues will be open later on
