### ISSUE TITLE
v-for over object's key and values does not relflect changes in the object when new keys are added, unless old keys are updated

### ISSUE THREAD

**Issue by raghavdasila** [vuejs/vue#10611]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/agentrsdg/xs635ndk/8/](https://jsfiddle.net/agentrsdg/xs635ndk/8/)

### Steps to reproduce
Click the first button, it will add a new key to the object, note that it doesn't get rendered.
Click the second button, which will update the old key. Now the new key gets rendered.

### What is expected?
The first button click should itself have been sufficient in rendering the new key.

### What is actually happening?
Newly added keys aren't rendering unless the old keys are updated.

**Comment by posva** [comment]
Please see https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

**Comment by raghavdasila** [comment]
> 
> 
> Please see https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

I see, thanks! If only someone had been this quick to respond with this in stackoverflow...
