### ISSUE TITLE
Unbound input value parameter containing non-breakable space gets changed when Vue initializes

### ISSUE THREAD

**Issue by avertes** [vuejs/vue#10613]
### Version
2.6.10

### Reproduction link
[https://codepen.io/avertes/pen/LYYpNRe](https://codepen.io/avertes/pen/LYYpNRe)

### Steps to reproduce
Insert &lt;input value="A &amp;nbsp; B" /&gt; inside Vue.js App html

### What is expected?
Value "A   B" is shown

### What is actually happening?
Value "A &amp;nbsp; B" is shown

---
Other escaped characters, for example &gt; ( &amp;gt; ) works as expected, but issue arises with any version of non-breakable space.

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/8895
