### ISSUE TITLE
why not add the feature that enable String  form filter,

### ISSUE THREAD

**Issue by MichaelPan24** [vuejs/vue#10637]
### What problem does this feature solve?
you know sometimes you cant always use variable form filter when you want to Extract the abstract logic on filter 
such like:
.item1
            .item-count {{(item.shouldFilterValue[0] || 0) | item.filterName[0]}}
.item2 
           .item-count {{item.shouldFilterValue[1] || 0 | item.filterName[1]}}
.item3
           .item-count {{item.shouldFilterValue[2] || 0 | item.filterName[2]}}
the code above is served as a basic child component,and its parent component will provide string form filter name like:
const normalRunItem = {
      title: ['Km', 'Speed', 'Time'],
      shouldFilterValue: [distance, pace, secondDuration],
      filterName: ['calRunningDistance', 'formatRunPace']
    }
    const cyclingItem = {
      title: ['Km', 'Km/h', 'Time'],
      shouldFilterValue: [distance, [secondDuration, distance], secondDuration],
      filterName: ['calCyclingDistance', 'calAverageSpeed']
    }
    const hikingItem = {
      title: ['Km', 'Pace', 'Duration'],
      shouldFilterValue: [distance, steps, secondDuration],
      filterName: ['calCyclingDistance', '']
    }

### What does the proposed API look like?
support string form filter gonna be ok

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by MichaelPan24** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

@posva , sorry that maybe i did not convey my meaning well , but i actually ask for a vue feature, now vue filter only work when passed a function after |(e.g., {{name | formatName}} works but {{name | 'formatName'}} not)

**Comment by posva** [comment]
I see, this is a duplicate of https://github.com/vuejs/vue/issues/4405

**Comment by MichaelPan24** [comment]
@posva ,thank you so mush
