### ISSUE TITLE
context argument undefined in functional component

### ISSUE THREAD

**Issue by iamriel** [vuejs/vue#10639]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/iamriel/g6a9ykdj/9/](https://jsfiddle.net/iamriel/g6a9ykdj/9/)

### Steps to reproduce
Run the fiddle and see that it prints undefined in the console which is the context in render function

### What is expected?
context should not be null and should contain, props, etc.

### What is actually happening?
context is undefined

**Comment by posva** [comment]
A functional component cannot be extended to be instantiated since it doesn't have an instance. You can however wrap it with a stateful component:

```js
Vue.extend({ render: h => h(FuncComp) })
```

**Comment by iamriel** [comment]
Thanks @posva , by the way, how do you pass props data from that wrapper to the functional component?  I wanted to use the render function with optional data and mount it without using the compiler.  Please let me know if I'm doing unnecessary things. Thanks!

**Comment by iamriel** [comment]
Nevermind, I found it. Thanks again.
