### ISSUE TITLE
template used as default slot 

### ISSUE THREAD

**Issue by hulkyhawk** [vuejs/vue#10724]
### Version
2.6.10

### Reproduction link
[https://codepen.io/hulkyhawk/pen/QWWKjyR](https://codepen.io/hulkyhawk/pen/QWWKjyR)

### Steps to reproduce
solution： 
-  replace 'template' with div to show 'should render'
- add slot="default" to template to show 'should render' 

### What is expected?

```html
should render
```

### What is actually happening?
render nothing

**Comment by posva** [comment]
The content is there, is not visible because of the meaning of a tag `template`. these are compiled a bit differently by Vue. Check: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%3Ctemplate%3E%0A%20%20%20%20%3Cspan%3Ehey%3C%2Fspan%3E%0A%20%20%3C%2Ftemplate%3E%0A%3C%2Fdiv%3E

You probably want to do

```js
new Vue({
  el: "#app",
  render(h) {
    return h(
      ComponentA,
      null,
     [h("span", null, ["should render"])]
    );
  }
});
```

Also, make sure that only one child is returned by the component render function. Otherwise it won't work

**Comment by hulkyhawk** [comment]
since it works well with `template syntax`, it should work with `jsx`;
and for my case i do not wanna add a non-used tag, like what `React` did with `Fragment`

you mean it is done intentionally to let jsx render template?

**Comment by posva** [comment]
I don't know what would be the way here in JSX. Maybe @sodatea or @nickmessing know

**Comment by hulkyhawk** [comment]
due to the original code, it does not check `template` when it is a `default slot`,
however, explictly adding `slot="deafult"` can make it work.
to make it go with `template syntax ` and still can make a user omit the `slot="default"`,
i suggest to solve it.

by the way, it bit me the first time.
@posva @sodatea @nickmessing 
```js
    if ((child.context === context || child.fnContext === context) &&
      data && data.slot != null
    ) {
      const name = data.slot
      const slot = (slots[name] || (slots[name] = []))
      if (child.tag === 'template') {
        slot.push.apply(slot, child.children || [])
      } else {
        slot.push(child)
      }
    } else {
      (slots.default || (slots.default = [])).push(child)
    }
```
