### ISSUE TITLE
Composition API inspired by React Hooks might not be the best solution. 

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue#10720]
### What problem does this feature solve?
I wanted this slides from Rich Harris considered while designing version 3. 

### What does the proposed API look like?
https://docs.google.com/presentation/d/1PUvpXMBEDS45rd0wHu6tF3j_8wmGC6cOLtOw2hzU-mw/edit#slide=id.g33fc23c0b5_0_0

**Comment by posva** [comment]
The whole discussion went into multiple issues and spanned over multiple months: https://github.com/vuejs/rfcs/pull/78
