### ISSUE TITLE
Use 'Tagged templates'  "Hyperscript Tagged Markup" instead of "Mustache" template

### ISSUE THREAD

**Issue by masx200** [vuejs/vue#10726]
### What problem does this feature solve?
Use 'Tagged templates' "Hyperscript Tagged Markup" instead of "Mustache" template

Comparing the "Mustache" template, the advantages of 'Tagged templates' are:

No need to write 'v-bind:' again

You can write functions and objects directly in the template, you can run directly in the browser, without using the compilation tool.

and More flexibility,

by using 'Hyperscript Tagged Markup' ,

The result after compilation is the same as the result of 'jsx' compilation

HTM is "JSX-like" syntax in plain JavaScript - no transpiler necessary.

https://github.com/developit/htm

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

### What does the proposed API look like?
```js
import { html } from '@vue/template';
const component = {
    setup() {
        const msg = 'hello world';
        function doSomething() {
        }
        return {
            doSomething,
            msg,
            activeColor: 'red',
            fontSize: 30
        };
    },
    render() {
        const {msg, doSomething, activeColor, fontSize} = this;
        return html`
<div style=${ {
            color: activeColor,
            fontSize: fontSize+  'px'
        } }></div>
<span>Message: ${ msg }</span>
<a @click=${ doSomething }></a>
`;
    }
};
export default component;
```

**Comment by posva** [comment]
The big important difference is that Vue templates are valid html.
This is not something we want to change or add to core, but community solutions are totally welcome!
