### ISSUE TITLE
Error in v-html if (?) there are self closing tags

### ISSUE THREAD

**Issue by 271ch** [vuejs/vue#10732]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-6vmpd](https://codesandbox.io/s/vue-template-6vmpd

### Steps to reproduce
Go in the link with minimal reproduction and compare the source html in the source property of the component HelloWorld with the html in the DevTools (F12) of the result.

### What is expected?
The two DOM-tree should be identical 

Here a picture of the html-string that is injected with `v-html`:
![image](https://user-images.githubusercontent.com/56249288/67124811-9fb07780-f1f3-11e9-8716-0724743fb2df.png)

### What is actually happening?
The tree structure is altered: for instance the tag `<i />` instead of being without child, contains a `<a></a>`.

Here a picture:
![image](https://user-images.githubusercontent.com/56249288/67124782-8f000180-f1f3-11e9-812d-bb7fa64ca106.png)

**Comment by posva** [comment]
v-html only sets `innerHTML`. What happens is that a self closing `i` element is not valid in html. You obtain the same result if you manually do `innerHTML='<i/><p>hey</p>'`
