### ISSUE TITLE
Suggestion for Vue 3.0 : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type For implicit type conversion to work properly.

### ISSUE THREAD

**Issue by masx200** [vuejs/vue#10737]
### What problem does this feature solve?
Suggestion for Vue 3.0 : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type
For implicit type conversion to work properly.

### What does the proposed API look like?
```js
const num=ref(8)
const xxx=ref(4)
const yyy=ref("hello")

num+ xxx
//expected  : 12
//[object Object][object Object]
//
num*xxx
//expected  : 32
//NaN
yyy+xxx
//expected  : "8hello"
//[object Object][object Object]
```

**Comment by posva** [comment]
Please don't create the issue twice
