### ISSUE TITLE
Spread operator on Set in template not working properly

### ISSUE THREAD

**Issue by LANGERGabriel** [vuejs/vue#10748]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-l3431?fontsize=14](https://codesandbox.io/s/vue-template-l3431?fontsize=14)

### Steps to reproduce
No interaction required

### What is expected?
The console shows the expected result: Spread operator behaves in the same way for a Set and for an Array. The resulting array contains every element from the set.

### What is actually happening?
The array is spread correctly, however the Set is not spread and is the single element in the resulting array.

---
The template seams to compile to [].concat(set), which should not work for any traversable.
Workaround: Use Array.from instead/before spreading

**Comment by posva** [comment]
It seems that https://github.com/vuejs/vue-template-es2015-compiler is applying some transformations with [buble](https://github.com/yyx990803/buble), which is doing the [transpiration into concat](https://buble.surge.sh/#let%20s%20%3D%20new%20Set(2%2C%203%2C%204)%0Alet%20a%20%3D%20%5B...s%5D)
This is not something that can be fixed here though. I only found `transforms.parameterDestructuring` that could maybe change the behavior but not much more. 

If the option doesn't exist, I think it will be better to stick to methods for that or use `Array.from` as you said
