### ISSUE TITLE
remove useless if condition judgement to the function markStatic

### ISSUE THREAD

**Issue by cutPicturesMan** [vuejs/vue#10747]
### What problem does this feature solve?
The if condition judgement in [src/compiler/optimizer.js#L62](https://github.com/vuejs/vue/blob/d7d8ff06b70cf1a2345e3839c503fdb08d75ba49/src/compiler/optimizer.js#L62) is useless.

As we know, the ASTNode which use `v-if` directive will always been marked `node.static = false` because of the function [isStatic](https://github.com/vuejs/vue/blob/d7d8ff06b70cf1a2345e3839c503fdb08d75ba49/src/compiler/optimizer.js#L109).It‘s unnecessary to remark `v-if` ASTNode.static false again.

### What does the proposed API look like?
remove L62~L64 code in optimizer.js

**Comment by posva** [comment]
Thank you for looking at it, but please create a PR instead. Testing locally can also help to see if it's completely unnecessary.

**Comment by cutPicturesMan** [comment]
[done](https://github.com/vuejs/vue/pull/10774)
