### ISSUE TITLE
Using this.$slots.default inside 'computed' will break the reactivity of slots

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#10749]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/q8az4n02/](https://jsfiddle.net/q8az4n02/)

### Steps to reproduce
Self-explaining

### What is expected?
newTitle is displayed

### What is actually happening?
initTitle is displayed

**Comment by kvdmolen** [comment]
It seems this is an issue after all: change the commented line in the example jsfiddle, and newTitle will appear

**Comment by posva** [comment]
`$slots` and `$scopedSlots` aren't reactive. Call them directly in your render function
