### ISSUE TITLE
Method in HTML called every time v-model changes

### ISSUE THREAD

**Issue by MatteoGabriele** [vuejs/vue#10755]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-prt6g](https://codesandbox.io/s/vue-template-prt6g)

### Steps to reproduce
- type something in the input field and press the 'Add' button.
- by rendering a new item in the page, a method to decorate the text is called. the method simply interpolates a string.
- once the first item is added, typing in the input field will trigger that function while typing and for all items inside the array. So if there are 5 items in the array, every key stroke will call the function 5 times.

### What is expected?
I am expecting to call that function only when an item is rendered the first time or if the content of that same item changes

### What is actually happening?
the function is called every time I use the input text, after the first item is rendered

---
I came across this issue and I couldn't explain it to myself, to be honest.
In the example we are only interpolating a string, but if more complex logic is applied, this could slow down the application quite a lot

**Comment by posva** [comment]
This is expected, the method is called every time the template renders.

**Comment by MatteoGabriele** [comment]
@posva so you expect to re-render the entire component every time i type on an input text? the array that is looping is not receiving any updates. 
I get the that the function triggers when I submit a new item, but not when I am just typing in a normal input field.

![ezgif-3-516d20e45c9d](https://user-images.githubusercontent.com/5337152/67496055-1c23da00-f67c-11e9-9ba7-8988fd20bd0d.gif)

**Comment by MatteoGabriele** [comment]
this can't be the only response about this issue. Feels like the problem has not been taken seriously. sorry
