### ISSUE TITLE
Server-side bundle should have one single entry file. Avoid using CommonsChunkPlugin in the server config.

### ISSUE THREAD

**Issue by lang1427** [vuejs/vue#10754]
### Version
2.6.10

### Reproduction link
[https://gitee.com/weiZhiXiang1219/vueSSR](https://gitee.com/weiZhiXiang1219/vueSSR)

### Steps to reproduce
1：download package ： npm install
2： npm run build

### What is expected?
vue-server-renderer/server-plugin   entryAssets.length!>1

### What is actually happening?
Building for server...(node:7044) UnhandledPromiseRejectionWarning: Error: Server-side bundle should have one single entry file. Avoid using CommonsChunkPlugin
in the server config.
    at C:\Users\Kinggz\Desktop\vueSSR\node_modules\_vue-server-renderer@2.6.10@vue-server-renderer\server-plugin.js:68:13
    at _next1 (eval at create (C:\Users\Kinggz\Desktop\vueSSR\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at _err1 (eval at create (C:\Users\Kinggz\Desktop\vueSSR\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Promise.all.catch.then (C:\Users\Kinggz\Desktop\vueSSR\node_modules\_copy-webpack-plugin@5.0.4@copy-webpack-plugin\dist\index.js:90:9)
(node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/  Building for server...

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Keep in mind there are also cli plugins for ssr like https://github.com/Akryum/vue-cli-plugin-ssr. If you found a recommendation for the SSR docs, the repo is here: https://github.com/vuejs/vue-ssr-docs
