### ISSUE TITLE
v-for will change objects key to string type

### ISSUE THREAD

**Issue by imic07** [vuejs/vue#10756]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/fav1bmwL/2/](https://jsfiddle.net/fav1bmwL/2/)

### Steps to reproduce
```
  <span v-for="(val, key) in { 1: '是', 0: '否' }" :key=key>
    {{ val }}-typeof val: {{typeof val}} -typeof key: {{typeof key}}<br>
  </span>

```

### What is expected?
typeof key is number

### What is actually happening?
typeof key is string

**Comment by imic07** [comment]
![image](https://user-images.githubusercontent.com/16321067/67473352-18e11c00-f685-11e9-8780-ea83d907948d.png)

![image](https://user-images.githubusercontent.com/16321067/67473314-0a930000-f685-11e9-862d-9c5eb16541de.png)

**Comment by posva** [comment]
This is not related to vuejs, that's how keys work in JS. You can try it yourself doing

```js
a = { 1: 'o' }
for (let k in a) {
    console.log(typeof k, k)
}
```
