### ISSUE TITLE
Dynamicly loaded WASM modules fail to execute properly

### ISSUE THREAD

**Issue by liona24** [vuejs/vue#10768]
### Version
2.6.10

### Reproduction link
[https://github.com/liona24/vue-dynamic-loaded-wasm](https://github.com/liona24/vue-dynamic-loaded-wasm)

### Steps to reproduce
Run the demo `yarn serve` and open the page in a browser.

Then click the *RUN* button.

### What is expected?
The text "It Works!" appears right above the button.

### What is actually happening?
A `TypeError: getObject(..) is undefined` is thrown, as visible in the console.

---
The `getObject` method gets called in the wrapper module *demo-project/src/wasm/myModule.js* and is definitely present in this module but for some reason it cannot be found when the module was dynamicly loaded inside a vue component. It works if it was loaded in the `main.js` entry point.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is not related to vue but rather configuring web pack (or the cli) so you can import those files
