### ISSUE TITLE
component props value empty string is Boolean

### ISSUE THREAD

**Issue by akebe** [vuejs/vue#10767]
### Version
2.6.10

### Reproduction link
[https://codepen.io/asseek/pen/mddwBZZ](https://codepen.io/asseek/pen/mddwBZZ)

### Steps to reproduce
see codepen result

### What is expected?
component should be string

### What is actually happening?
component show boolean

**Comment by posva** [comment]
This is expected as you declared the prop as Boolean and it comes before String
