### ISSUE TITLE
v-for : track items with the hint from Array methods

### ISSUE THREAD

**Issue by smalllong** [vuejs/vue#10772]
### What problem does this feature solve?
Currently, when using v-for and not providing a key, the default tracking method is using index. However, this can cause problems like component and DOM state not correct.

Actually, when mutating the array using Array.prototype methods (push, pop, shift, unshift, splice...), Vue could track the identity of items with the help of the definition of these Array methods. For example, when `.splice(0, 3)` is called, Vue could know that item4 becomes item1, and item5 becomes item2. Thus the component and DOM state could be correct.

The benefit of this feature is that we will not be tired of creating unique kies for objects. Sometimes creating such kies can be hacky and making code more complicated. On the contrary, using Array methods to mutate Arrays is much simpler.

### What does the proposed API look like?
Change the default behavior to use the hint from Array methods.

Turn off this behavior when explicitly set `v-for="(item, index) in items" :key="index"`

**Comment by posva** [comment]
This comes down to do the same as https://github.com/vuejs/vue/issues/6235 which is generating keys. Please see the thread for details and solutions
