### ISSUE TITLE
Components of the props attribute has a problem

### ISSUE THREAD

**Issue by changk99** [vuejs/vue#10775]
### Version
2.6.10

### Reproduction link
[https://codepen.io/changli/pen/jOOLKRb](https://codepen.io/changli/pen/jOOLKRb)

### Steps to reproduce
‘’Value‘ ’ the value of the render output

### What is expected?
nothing output

### What is actually happening?
The output of true

**Comment by barclaycc** [comment]
value: [String,Boolean]

**Comment by changk99** [comment]
But  the document did not say this order is important,and the '' is a string, but be converted to true,this is confusing. I think this is a bug

**Comment by changk99** [comment]
I know why do this, like <input disabled=''> <input disabled="disabled">
In this case, it is not a bug
