### ISSUE TITLE
Condition on template with v-if using v-slot prop

### ISSUE THREAD

**Issue by julaudo** [vuejs/vue#10784]
### Version
2.6.10

### Reproduction link
[https://codepen.io/jaudo/pen/MWWOeBp?&editable=true&editors=101#anon-signup](https://codepen.io/jaudo/pen/MWWOeBp?&editable=true&editors=101#anon-signup)

### Steps to reproduce
Launch the codepen

### What is expected?
No error should appear. The template should be active only for items having loading = true

### What is actually happening?
An error appears : item is undefined while evaluating item.loading

**Comment by Justineo** [comment]
Hi, please provide a **minimal** reproduction. That means no 3rd party libraries should be included, eg. Vuetify.

**Comment by posva** [comment]
`v-if` has a higher priority than the v-slot, so if you need to use the data passed by it, you will have to use it **inside** the slot:

```
<template v-slot:item="{ item }">
        <tr v-if="item.loading">
          Loading
        </tr>
      </template>
```

This is easier to see with the template explorer: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%3Cv-app%20id%3D%22inspire%22%3E%0A%20%20%20%20%3Cv-data-table%0A%20%20%20%20%20%20%3Aheaders%3D%22headers%22%0A%20%20%20%20%20%20%3Aitems%3D%22desserts%22%0A%20%20%20%20%20%20%3Aitems-per-page%3D%225%22%0A%20%20%20%20%20%20class%3D%22elevation-1%22%0A%20%20%20%20%3E%0A%20%20%20%20%20%20%3Ctemplate%20v-slot%3Aitem%3D%22%7B%20item%20%7D%22%20v-if%3D%22item.loading%22%3E%0A%20%20%20%20%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%20%20%20%20Loading%0A%20%20%20%20%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%20%20%3C%2Ftemplate%3E%0A%20%20%20%20%3C%2Fv-data-table%3E%0A%20%20%3C%2Fv-app%3E%0A%3C%2Fdiv%3E

**Comment by julaudo** [comment]
Thank you for your answer but this is not a good solution, because the component can have specific behaviour depending on the presence of the slot (as explained in my example with vuetify)
