### ISSUE TITLE
The slot content was not successfully mounted 

### ISSUE THREAD

**Issue by Veath** [vuejs/vue#10783]
### Version
2.6.10

### Reproduction link
[https://github.com/Veath/micro-frontend-qiankun](https://github.com/Veath/micro-frontend-qiankun)

### Steps to reproduce
* installation and startup  `portal` and `micro a` project
* click navigation in the browser ，click in order `home` 、 `micor-a`、 `about` links
* about page  show blank 

### What is expected?
about page display text

### What is actually happening?
about page display blank

**Comment by posva** [comment]
Hey, this is not clear enough for a reproduction: why two apps? which one to open.
The only things I could see are

- add a trailing slash to base: https://router.vuejs.org/api/#base
- Do not add a domain to the publicPath (https://github.com/Veath/micro-frontend-qiankun/blob/master/micro-a/vue.config.js). That cannot work
- To go to a different app under a different base, use a regular `a` with the proper url like `/other-base/about`

**Comment by Veath** [comment]
> Hey, this is not clear enough for a reproduction: why two apps? which one to open.
> The only things I could see are
> 
> * add a trailing slash to base: https://router.vuejs.org/api/#base
> * Do not add a domain to the publicPath (https://github.com/Veath/micro-frontend-qiankun/blob/master/micro-a/vue.config.js). That cannot work
> * To go to a different app under a different base, use a regular `a` with the proper url like `/other-base/about`

two apps because I want to integrate multiple projects, like a single page.

add domain to the publicPath because the micor-a project will be run in portal page when the route is`http://localhost:8080/vue/`.  portal page fetch (the absolute path) micor-a  content.e.g html and js and runing.

* startup portal (http://localhost:8080) and micor-a (http://localhost:8081)
* open  http://localhost:8080/ in  browser,
* click `home link`, page display content,  and than click `micro-a project Home link`also display content，and than click `micro-a project About link` **display blank**
