### ISSUE TITLE
Vue Cli 4.0.5 Mocha : Unable to run a test

### ISSUE THREAD

**Issue by nicolas15000** [vuejs/vue#10789]
### Version
2.6.10

### Reproduction link
[http://random.com](http://random.com)

### Steps to reproduce

This will be easy to resolve for some of you i guess .

Installed a vue app like this on windows 10:

`vue create hello-world`

I have chosen Mocha as a test system ,The "tests" directory is present, with an example unit test called example.spec.js

Then

`cd hello-world`

Then

`npm run test`

This is the error :

```

> hello-world@0.1.0 test C:\UwAmp\www\hello-world
> echo 'Error: no test specified'


'Error: no test specified'
```

This is my vue-cli version :
```

vue --version
@vue/cli 4.0.5
```

This is my package.json file , not modified :

```
{
  "name": "hello-world",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.3.2",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-plugin-router": "^4.0.0",
    "@vue/cli-plugin-unit-mocha": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.3",
    "chai": "^4.1.2",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "overrides": [
      {
        "files": [
          "**/__tests__/*.{j,t}s?(x)"
        ],
        "env": {
          "mocha": true
        }
      }
    ]
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

### What is expected?
testing

### What is actually happening?
nothing

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
This is also related to vue-cli (which has its own repository). If it ends up being a bug, you should open an issue there or the relevant repo causing the bug

**Comment by edreesjalili** [comment]
@nicolas15000 Looking at the package.json scripts, looks like you'll actually want to run 
```npm run test:unit```

**Comment by nicolas15000** [comment]
Hey !


I've used this command on win 10 64 and now, it is working :

`npx vue-cli-service test:unit`
