### ISSUE TITLE
Tree组件使用作用域插槽

### ISSUE THREAD

**Issue by Uluer** [vuejs/vue#10787]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/Ayers/w089unqx/2/](https://jsfiddle.net/Ayers/w089unqx/2/)

### Steps to reproduce
tree最下面一级渲染插槽的内容，并将最下面一级的数据通过作用域插槽的方式传递到插槽内。
现不知道为什么最下面一级应该传递的数据是整个第一级的数据

### What is expected?
tree最下面一级渲染插槽的内容，并将最下面一级的数据通过作用域插槽的方式传递到插槽内

### What is actually happening?
item

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
