### ISSUE TITLE
Unknown custom element error in nested functional components

### ISSUE THREAD

**Issue by cathrinevaage** [vuejs/vue#10781]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-gg2gj](https://codesandbox.io/s/vue-template-gg2gj)

### Steps to reproduce
Create two functional components, `OuterComponent` and `InnerComponent`.
Use `InnerComponent` in `OuterComponent`.
Use `OuterComponent` in your app somewhere.

### What is expected?
`InnerComponent` should be recognized, as it's registered in `OuterComponent`'s `component` option.
`InnerComponent` should render.

### What is actually happening?
A unknown custom element error is thrown, and `InnerComponent` isn't rendered.

---
It will work if all the functional components used are registered in `app.vue`, even though they aren't used in `app.vue`'s template.

**Comment by KaelWD** [comment]
Duplicate of #7492

**Comment by posva** [comment]
Duplicate of #7492
