### ISSUE TITLE
My customized 404 page will appear in a moment when Vue jumps the route

### ISSUE THREAD

**Issue by 996529748** [vuejs/vue#10797]
### Version
2.6.9

### Reproduction link
[https://www.pdf365.cn/help/573](https://www.pdf365.cn/help/573)

### Steps to reproduce
After configuring the dynamic route, you can jump to the dynamic route page

### What is expected?
Load the correct route directly without flashing other pages

### What is actually happening?
Recently, a project has been made with the pre render spa plugin. The dynamic routing page will flash 404 pages first, and then load them to the correct routing. How to solve this problem?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
When reporting a bug a boiled down editable and runnable repro must be provided

**Comment by QGB** [comment]
@996529748  “pdf365.cn/pdf-to-html/”  automation script needed
