### ISSUE TITLE
Update docs for render functions how to use v-slot

### ISSUE THREAD

**Issue by andtii** [vuejs/vue#10793]
### What problem does this feature solve?
At the moment the docs for Render Functions and JSX is missing how to work with the new v-slot introduced in 2.6 since the old way is depricated the docs should be updated to reflect how to use it https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

### What does the proposed API look like?
Docs should be updated

**Comment by posva** [comment]
Regarding render functions, the api hasn't changed. For JSX open this in the vuejs/vuejs.org repo where we have our docs please. Also make sure to check if there are any existing issues and pull request first :)

**Comment by andtii** [comment]
@posva Thnx for info, look at this discussion and you can see that there seems to be issues with render functions - https://github.com/vuejs/vuejs.org/issues/2110 
At the moment there is a lot of confusion how to do use it at all

**Comment by andtii** [comment]
https://github.com/vuejs/vuejs.org/issues/2373
