### ISSUE TITLE
一个关于原生JS scrollTop 的使用问题

### ISSUE THREAD

**Issue by Dangerous828** [vuejs/vue#10809]
### Version
2.6.10

### Reproduction link
[https://juejin.im/post/5dc4d8626fb9a04a624e2ead](https://juejin.im/post/5dc4d8626fb9a04a624e2ead)

### Steps to reproduce
这是我在中国的掘金论坛上面发布的一篇帖子，其实就是关于原生的一个ScrollTop属性，只是写法不同导致一个可以实现一个不可以实现

### What is expected?
想知道为什么会出现这个区别

### What is actually happening?
实际上无论怎么写效果应该是一样的

**Comment by Justineo** [comment]
请按要求提供[问题重现](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro)，你提供的链接并不是一个可以运行的重现。谢谢。
