### ISSUE TITLE
Use the custom directive "directives" error modifier value in the "input" component

### ISSUE THREAD

**Issue by CN-Yi** [vuejs/vue#10819]
### Version
2.6.10

### Reproduction link
[https://cn.vuejs.org/v2/api/#directives](https://cn.vuejs.org/v2/api/#directives)

### Steps to reproduce

 `<el-table-column label="score" width="60" align="center">
            <template slot-scope="scope">
              <input class="input-line" v-number style="width:100%" type="text" v-model="scope.row.score" />
            </template>
          </el-table-column>
`

`  directives: {
    number: {
      inserted: function(el, binding, vnode) {
        el.oninput = function(e) {
          let value = e.target.value;
          if (!/^\d{1,2}?$/gi.test(value)) {
            e.target.value = value.substr(0, 2);
          }
        };
      }
    }
  }
`

### What is expected?
I hope I can only enter two digits.

### What is actually happening?
After entering the integer, switch the focus to another 'input' and enter the number, which will cause the original value to be modified.
For example: I enter 11 in the first "input", then immediately switch to the second Input input 22, and finally switch to the first "input" input 3 will appear 223. If you switch to the second input again and Enter 4 then the value of the first input will be changed to 2234

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reproduction on jsfiddle.net or as a Github repository so we can debug this without trying to replicate this ourselves?

That would be very helpful, thanks!

**Comment by CN-Yi** [comment]
Hi
I wrote a simple case that highlights this problem and hopes to answer the questions I have encountered. Thanks.

`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <title>Document</title>
</head>

<body>
    <div id="app">
        <div v-for="(item, index) in list" :key="item.key">
            <span>Input your score</span>
            <input type="text" v-number v-model="item.score" placeholder="Please enter two digits" />
        </div>
    </div>
</body>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            list: [{
                key: 1,
                score: 0
            }, {
                key: 2,
                score: 0
            }]
        },
        directives: {
            number: {
                inserted: function(el, binding, vnode) {
                    el.oninput = function(e) {
                        let value = e.target.value;
                        if (!/^\d{1,2}?$/gi.test(value)) {
                            e.target.value = value.substr(0, 2);
                        }
                    };
                }
            }
        },
    })
</script>
</html>`

**Comment by CN-Yi** [comment]
Hi
I wrote a simple case that highlights this problem and hopes to answer the questions I have encountered. Thank you.

code:


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <title>Document</title>
</head>

<body>
    <div id="app">
        <div v-for="(item, index) in list" :key="item.key">
            <span>Input your score</span>
            <input type="text" v-number v-model="item.score" placeholder="Please enter two digits" />
        </div>
    </div>
</body>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            list: [{
                key: 1,
                score: 0
            }, {
                key: 2,
                score: 0
            }]
        },
        directives: {
            number: {
                inserted: function(el, binding, vnode) {
                    el.oninput = function(e) {
                        let value = e.target.value;
                        if (!/^\d{1,2}?$/gi.test(value)) {
                            e.target.value = value.substr(0, 2);
                        }
                    };
                }
            }
        },
    })
</script>
</html>

**Comment by CN-Yi** [comment]
Hi
I wrote a simple case that highlights this problem and hopes to answer the questions I have encountered. Thank you.

![image](https://user-images.githubusercontent.com/32233642/68660031-60b3de80-0573-11ea-9a32-28babc03f8f9.png)

`<script src="https://cdn.jsdelivr.net/npm/vue"></script>

<body>
    <div id="app">
        <div v-for="(item, index) in list" :key="item.key">
            <span>Input your score</span>
            <input type="text" v-number v-model="item.score" placeholder="Please enter two digits" />
        <div>
    </div>
</body>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            list: [{
                key: 1,
                score: 0
            }, {
                key: 2,
                score: 0
            }]
        },
        directives: {
            number: {
                inserted: function(el, binding, vnode) {
                    el.oninput = function(e) {
                        let value = e.target.value;
                        if (!/^\d{1,2}?$/gi.test(value)) {
                            e.target.value = value.substr(0, 2);
                        }
                    };
                }
            }
        },
    })
</script>`

**Comment by LinusBorg** [comment]
I can't run code from a screenshot.

**Comment by CN-Yi** [comment]
The git editor blocked my html code block, I can't upload the code, this is my error effect screenshot
![image](https://user-images.githubusercontent.com/32233642/68661139-68748280-0575-11ea-86b3-bdf40039ac69.png)

**Comment by CN-Yi** [comment]
https://codepen.io/cn-yi/pen/rNNZazE

**Comment by ZzqiZQute** [comment]
I __do not__ recommend that you directly modify the value of the input element while you are using `v-model`.

In fact, you can watch the change of `list` by using vue `watch`. 

Since you use the `v-model` , the value of the `input` element is two-way binded by `score`. When you inputing, you use the event registered by `v-directives` to modify the value of the `input` element ,the value of the `input` element changed. However the value of the `score` is not changed. So it'll render the value of the `score` in the next render process.

You can directly modify the value of the `score`. Perhaps.😂

**Comment by CN-Yi** [comment]
In fact, I only want to display the input of the score. In the official documentation, I can see that it can be implemented by the directive's custom command, but thank you for your answer.👍
