### ISSUE TITLE
如何实现没有.vue文件也能触发热更新

### ISSUE THREAD

**Issue by xmsz** [vuejs/vue#10816]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-8e021?fontsize=14](https://codesandbox.io/s/vue-template-8e021?fontsize=14)

### Steps to reproduce
-| view
  -| home
    -| index.js
```
// index.js
export default {
 render() {
   return(<div>abc</div>)
 }
}
```

如果这么写的，每次修改index.js文件都需要重新刷新页面，而不是热更新

必须要变成

-| view
  -| home
    -| index.vue

```
// index.vue
<script>
 export default {
  render() {
    return(<div>abc</div>)
  }
 }
</script>
```

或者
-| view
  -| home
    -| index.vue
    -| index.js

热更新才会生效

### What is expected?
单.js文件也能实现热更新，而不一定要有个.vue文件

### What is actually happening?
必须是vue文件才能触发热更新

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only, this is a question about webpack. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
