### ISSUE TITLE
Allow template slot option for purely text content

### ISSUE THREAD

**Issue by DominusVilicus** [vuejs/vue#10827]
### What problem does this feature solve?
Simpler to understand

### What does the proposed API look like?
```html
<template slot="description" text="content here"/>
```
Equivilant of:
```html
<template slot="description">content here</template>
```

**Comment by posva** [comment]
Thanks for the proposal but this brings very little benefit while being less flexible and adding an extra thing to learn. It can also be achieved through a string-based prop

**Comment by DominusVilicus** [comment]
Thanks for the feedback
