### ISSUE TITLE
Vue.config.errorHandler dosn't handle the error thrown by beforeRouteUpdate method

### ISSUE THREAD

**Issue by foyzhao** [vuejs/vue#10826]
### What problem does this feature solve?
I'm using a global error handler for process errors during component render function and watchers. 

But it does not catch the exception thrown in the list method below:
```
export default {
  async beforeRouteUpdate(to, from, next) {
    next();
    await this.list();
  },
  methods: {
    async list() {
      return axios.get('An invalid url');
    },
  },
};
```

### What does the proposed API look like?
No need to change API

**Comment by posva** [comment]
That is normal, they are different kind of errors so Vue Router doesn't relay them to Vue by default. Regarding async errors: https://github.com/vuejs/vue-router/issues/2833

**Comment by foyzhao** [comment]
If I want to refresh the page data when the route is updated, the error in `created` and the error in `beforeRouteUpdate` are the same type.

**Comment by foyzhao** [comment]
And if I want to catch all these exceptions in `Vue.config.errorHandler`, what is your suggestion?
