### ISSUE TITLE
Context is not passed to child component when the component is inserted into the DOM dynamically.

### ISSUE THREAD

**Issue by anipendakur** [vuejs/vue#10823]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-1fckn](https://codesandbox.io/s/vue-template-1fckn)

### Steps to reproduce
Please refer to the codesandbox link. I can't get the context to show up when I import the Button component dynamically (console.log says undefined).

### What is expected?
Context object to be available

### What is actually happening?
Context object in render(createElement, context) is undefined

---
I'd like to use it dynamically as shown in the code sandbox. If i use it with component registration it works! But I thought this one should work as well. Please correct me if otherwise.

Thank you! 
Ani

**Comment by posva** [comment]
A functional component must be rendered as part of something else, it cannot be instantiated, using extend with it doesn't really make sense because of that
But I really discourage you from doing manual Dom manipulation like that with Vue, instead use a declarative approach where you use `<Button/>` in the App's template

**Comment by anipendakur** [comment]
I tried with the `<template functional>` syntax and I get a console error - 
`TypeError: Cannot read property '_c' of undefined` with an error stack. (perhaps undefined here is context?)
https://codesandbox.io/s/vue-template-qll3k

**Comment by anipendakur** [comment]
Just a add-on question, if it's not a functional component, should it work?

**Comment by anipendakur** [comment]
Thank you for the quick response!!
