### ISSUE TITLE
Unexpected type coercion caused by prop definitions 

### ISSUE THREAD

**Issue by MiguelBamberino** [vuejs/vue#10838]
### Version
2.6.10

### Reproduction link
[https://github.com/FabricDigital/PPBootstrapVue/blob/PP-10499/src/components/controls/BaseToggle.vue](https://github.com/FabricDigital/PPBootstrapVue/blob/PP-10499/src/components/controls/BaseToggle.vue)

### Steps to reproduce
create any component with prop :
 value: {
                type: [Boolean,String,Number],
                default:false
            },

put the component somewhere in your code and specify the prop value as an empty string.

By the time you get to the data function, the value has been forced into boolean true.

I fixed this problem by re-ordering the prop type rules to type: [String,Boolean,Number],

If you want access to the file linked in reproduction, then email mike.bamber@procure-plus.com

### What is expected?
it should have stayed as type string

### What is actually happening?
it is forced into type boolean, with the value true

---
i ran into the bug because we have a toggle component which can be configured with different on/off values

**Comment by posva** [comment]
You need to use `PropType` from vue


```ts
import { PropType } from 'vue'

value: {
  type: [Boolean, String, Number] as PropType<boolean, string, number>
}
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
