### ISSUE TITLE
结点复用问题

### ISSUE THREAD

**Issue by yelloxing** [vuejs/vue#10835]
### Version
2.6.10

### Reproduction link
[https://github.com/yelloxing/abandon/issues/1](https://github.com/yelloxing/abandon/issues/1)

### Steps to reproduce

```html
         <div class="content" v-if='flag==1'>
            <div class="pciItem">
                <label for="aaaa">XXX1:</label>
                <input v-select='cardmodeList' v-model='param.aaaa'>
            </div>
        </div>
        
        <div class="content"  v-if='flag==2'>
            <div class="pciItem">
              <label for="bbbb">XXX2:</label>
              <input v-model='param.bbbb'>
          </div>
        </div>
```

### What is expected?
第一个显示为下拉，第二个应该是输入框

### What is actually happening?
二个都显示为下拉了

---
猜想是结点复用错误导致的，第二个输入框复用了第一个结点，只有加key属性的时候才可以正确解析。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by tear520** [comment]
ok
