### ISSUE TITLE
Uncaught TypeError: slots[name$1].every is not a function

### ISSUE THREAD

**Issue by marfrelen** [vuejs/vue#10839]
### Version
2.6.10

### Reproduction link
[https://stackoverflow.com/questions/56390672/vue-js-slotsname1-every-is-not-a-function](https://stackoverflow.com/questions/56390672/vue-js-slotsname1-every-is-not-a-function)

### Steps to reproduce
I created a new Laravel Project with a couple of single file vue Components.
My app.js looks like this:

```
if(typeof Object.prototype.clone !== 'undefined'){
    Object.prototype.clone = function() {return JSON.parse(JSON.stringify(this));}
}

import test from "./components/test";
Vue.component('vue-test', test);

new Vue({
    el: '#app',
});
```

I build my compiled app.js file with Laravel.mix.

### What is expected?
Something like this:

```
let foo = {test: 'foo'};
const bar = foo.clone();
bar.test = 'bar';

console.log(foo, bar);
```
> {test: foo}, {test: bar}

### What is actually happening?
Vue throws the following error:

```
Uncaught TypeError: slots[name$1].every is not a function
    at resolveSlots (app.js:82705)
    at initRender (app.js:83658)
    at VueComponent.Vue._init (app.js:85164)
    at new VueComponent (app.js:85314)
    at createComponentInstanceForVnode (app.js:83463)
    at init (app.js:83294)
    at createComponent (app.js:86140)
    at createElm (app.js:86087)
    at createChildren (app.js:86215)
    at createElm (app.js:86116)
```

If I remove the Object.prototype function, everything works fine.
But in the case I extended the Object.prototype object, I'll get the error above.

---
I hope my infomation helps you to reproduce this error.
If you need some deeper information, leave me a message at markus.lenz@ort-online.net.

Thanks and kind regards,
Markus

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

When reporting a bug, please provide a boiled down (a jsfiddle or code sandbox) runnable repro so we can check it 🙂

**Comment by marfrelen** [comment]
@posva 'cause is this a bug.

The behavior occurs in connection with Vue. 

I'm not able to precompile dot vue files in jsfiddle, so it's not possible to give you a sandbox.

Maybe I can prepare a testsystem for you on our public dev server tomorrow.

**Comment by posva** [comment]
I'm sorry but that's not how it works. Please take a minute to read what is said at https://new-issue.vuejs.org/?repo=vuejs/vue it's really important for us.
It also gives you links to repros templates. One of them, the codesandbox one allows you to use vue files. But if you manage to reproduce it, please, make sure to boil it down to the minimal repro before opening a bug report as the bug could come from your code.

**Comment by marfrelen** [comment]
Thanks a lot for the codesandbox. I'll try it out tomorrow and isolate this issue :)

Maybe I'll come back later if I can lacalize the cause of this error.

**Comment by ICEYSELF** [comment]
It's 2021 now and seems that this is still a problem.

**Comment by btquanto** [comment]
I'm encountering the same issue. I tried to add a `Object.prototype.toJsonString` function, and this same error occurred (vue 2). Removing the `Object.protype.toJsonString` definition works normally.

**Comment by z9fr** [comment]
2022 and still have the same problem.

**Comment by endrik-exe** [comment]
Same Here 2023

But i have the hack for this, so if we want to add function prototype to Object, we need to define property instead.

so from this code
```
Object.prototype.listify = function(mapFn) {
    if (mapFn === undefined) {
        mapFn = (k, v) => ({ k: k, v: v });
    }

    return Object.entries(this).reduce((acc, [key, value]) => {
        acc.push(mapFn(key, value));
        return acc;
    }, []);
};
```

to this code

```
function listify(obj, mapFn) {
    if (mapFn === undefined) {
        mapFn = (k, v) => ({ k: k, v: v })
    }

    return Object.entries(obj).reduce((acc, [key, value]) => {
        acc.push(mapFn(key, value))
        return acc
    }, []);
};

Object.defineProperty(Object.prototype, 'listify', {
    get: function () {
        return (mapFn) => {
            return listify(this, mapFn)
        };
    },
})
```

i know it's not solution, but rather a hack, but its works

**Comment by JaderCM** [comment]
2024 and still have the same problem.

**Comment by ultravires** [comment]
add `try {} catch (e) {}` to avoid the problem.

**Comment by ultravires** [comment]
May you changed `Object.prototype`.
