### ISSUE TITLE
Nginx多层代理指定路由，组件不更新

### ISSUE THREAD

**Issue by biraotian** [vuejs/vue#10831]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-1e6sf?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/vue-template-1e6sf?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
项目A是在nginx服务器下运行的vue项目（可以正常运行）。我在B项目的Nginx代理中，配置访问“/user/login/“ proxy_pass到A项目的 /be/home/#/login/（子路由），理想中会跳转到目标子路由。但，实际场景只会跳转到首页/be/home/#/。查看A服务器access.log其实是收到了/be/home/#/login/ 的HTTP请求。

改为history模式，会路由到404组件。

### What is expected?
B项目的/user/login/请求代理A项目的指定路由时，页面可以正常显示，而不是显示首页或404组件。

### What is actually happening?
改为history模式，会路由到404组件。
因为B代理时，浏览器地址没有变化，只是发了一个正确的请求到A服务器。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
