### ISSUE TITLE
Child component mounted twice in this situation.

### ISSUE THREAD

**Issue by joy-yu** [vuejs/vue#10836]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-wn53r](https://codesandbox.io/s/vue-template-wn53r)

### Steps to reproduce
Just see the code and the console info.

### What is expected?
Child component mounted once.

### What is actually happening?
Child component mounted twice.

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/4362

You can get around it by keying the div wrapping `Child`
