### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.$options')

### ISSUE THREAD

**Issue by devlee** [vuejs/vue#10842]
### Version
2.5.17

### Reproduction link
[https://codepen.io/devlee/pen/zYYeGwX](https://codepen.io/devlee/pen/zYYeGwX)

### Steps to reproduce
1. In a specific environment，ios 13.x，native app webview
2. There is a Tab Component:
```
// Tab.vue
<template>
  <div>
    <Item
      v-for="(item, idx) in bindingPropList_"
      v-bind:key="idx"
      :binding-prop="bindingPropList_[idx]"
    >
      <slot :name="idx"></slot>
    </Item>
  </div>
</template>
// Item.vue
<template>
  <section>
    <slot v-if="show"></slot>
  </section>
</template>
```
3. when there are three tabItem, and the second slot component do something with native app in created hook, then the third tabItem will throw exception when prepatch
4. prepatch function received two MountedComponentVNode，but actually the componentInstance of vnode/oldVnode(the third tabItem) is undefined when debug
5. It's hard to reproduce because it's not always repeatable，it's need in a specific environment，I just find this issue
6. Maybe it is necessary to check when patchVnode
```
    let i
    const data = vnode.data
    if (isDef(data) && isDef(i = data.hook) && isDef(i = i.prepatch)) {
      i(oldVnode, vnode) 
    }
```

### What is expected?
check the vnode/oldVnode is really MountedComponentVNode before prepatch

### What is actually happening?
the vnode/oldVnode is not MountedComponentVNode when prepatch

**Comment by posva** [comment]
Please provide a boiled down repro when reporting a bug so we can check it. Thank you.
