### ISSUE TITLE
Unexpected mustache behavior

### ISSUE THREAD

**Issue by rgex** [vuejs/vue#10844]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/r5bLk16p/](https://jsfiddle.net/r5bLk16p/)

### Steps to reproduce
Use 
{{ ' &lt;span&gt; ' }}

### What is expected?
The expected behavior would be to have it displayed like this:
&amp;lt;span&amp;gt;

### What is actually happening?
  Errors compiling template:

  tag <span> has no matching end tag.

---
Defining '&lt;span&gt;' in data() and including the variable in mustaches will produce the expected result.

**Comment by Seungwoo321** [comment]
Mustaches must use a variables.
'<span>' is String.

**Comment by rgex** [comment]
@Seungwoo321  the {{ ' ' }} syntax is also used in the documentation.

**Comment by posva** [comment]
Remember that vue templates must be valid html, if you put a span like that, it is not (jsfiddle even highlights it). You need to escape it:

```html
<p>{{ '&lt;span&gt;' }}</p>
```
