### ISSUE TITLE
Multi-page multi-route: When directly refresh in the sub-routing page, "Uncaught SyntaxError: Unexpected token <" error happened

### ISSUE THREAD

**Issue by kluslulu** [vuejs/vue#10859]
### Version
2.6.10

### Reproduction link
[https://github.com/kluslulu/multi-page-app](https://github.com/kluslulu/multi-page-app)
![image](https://user-images.githubusercontent.com/12146570/69475289-4f39c480-0e06-11ea-837d-16b6115a5a3c.png)
![image](https://user-images.githubusercontent.com/12146570/69475314-8a3bf800-0e06-11ea-9d2c-0f15dfc5bca4.png)

### Steps to reproduce
I created a multi-page app by vue-cli3.
when I in a sub-routing page,if I refresh this page by command R directly,it will be showing a white page

### What is expected?
I hope to  refresh success in a sub-routing page

### What is actually happening?
Showing a white page and some error in console: 
Uncaught SyntaxError: Unexpected token '<'
index.js:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by shadowings-zy** [comment]
I think your project will show a white page after refresh because your vue-router is using history mode in your project.
You can fix it by using hash mode or configure your server to redirect the correct route.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
