### ISSUE TITLE
Getter not reactive with a Vue.observable?

### ISSUE THREAD

**Issue by maximelebreton** [vuejs/vue#10857]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/getters-reactivity-with-observable-5gn6q](https://codesandbox.io/s/getters-reactivity-with-observable-5gn6q)

### Steps to reproduce
- Go to the input
- type something inside
- and you will see that the observable is reactive, but the getter is not...
- Why? and how can i make this getter reactive?

### What is expected?
The getter should be reactive

### What is actually happening?
The observable is reactive, but the getter (who returns the observable) is not reactive.

---
Because Vuex is not Typescript friendly, and outdated especially since vue composition-api, I try to recreate a kind of store, as native as possible.
My goal is to split my states / getters / actions in different files, and import them like classic javascript variables / functions, to limit the magic / boilerplates.

PS: I was very interested by Effector (https://effector.now.sh/), but Vue doesn't provide a way to share/interact reactivity with other reactive libraries (`symbol-observable`, `.subscribe`?), so I can't use it, too bad, you should take a look.

**Comment by posva** [comment]
`observable` needs objects to be able to detect changes: 

```js
export const $searchInput = observable({ value: 'Test me' });
```

> Because Vuex is not Typescript friendly, and outdated especially since vue composition-api, I try to recreate a kind of store, as native as possible.
My goal is to split my states / getters / actions in different files, and import them like classic javascript variables / functions, to limit the magic / boilerplates.

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
