### ISSUE TITLE
Using createBundleRenderer with custom plugin may lead to memory leak

### ISSUE THREAD

**Issue by uuau99999** [vuejs/vue#10853]
### Version
2.6.10

### Reproduction link
[https://codepen.io/uuau99999/project/editor/ZqnjQK](https://codepen.io/uuau99999/project/editor/ZqnjQK)

### Steps to reproduce
1. use createBundleRenderer to create a vue ssr app;
2. write a custom plugin and place it in your source folder;
3. use your custom plugin in entry vue file, eg: Vue.use(xxx);

### What is expected?
My custom plugin should only be added into installedPlugin once

### What is actually happening?
My custom plugin is added to installedPlugin every time I reload the page

---
It seems that function Vue.use can not avoid redundant plugin added into installedPlugin array because the following code:
```
    var installedPlugins = (this._installedPlugins || (this._installedPlugins = []));
    if (installedPlugins.indexOf(plugin) > -1) {
      return this
    }
```
will not work in ssr mode cause the plugin will not be the same object in memory for each reqeust. However, when the plugin is imported as a npm package, it works.

**Comment by posva** [comment]
The example you provided would not create multiple additions of the plugin. If you can please provide a boiled down repro in a repository following https://ssr.vuejs.org and displaying the plugin being added multiple times. Ping when you post the reproduction
