### ISSUE TITLE
"keep-alive" and "router-view" don't work properly when max="1"

### ISSUE THREAD

**Issue by unitree-czk** [vuejs/vue#10854]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-g669u](https://codesandbox.io/s/vue-template-g669u)

### Steps to reproduce
    <keep-alive max="1">
      <router-view v-if="$route.meta.largeCache"></router-view>
    </keep-alive>
    <keep-alive>
      <router-view v-if="!$route.meta.largeCache"></router-view>
    </keep-alive>

Assuming we have some pages that require much memory and some pages that require only a little memory.

Let's say:
Home, PricyA, PricyB are memory intensive pages, while CheapA and CheapB are not.
The use case is to keep all cheap pages in the cache while only keep one pricy one.

However, for "keep-alive" tag, when the prop "max" is set to 1, the "beforedestroy" hook doesn't work, and therefore I cannot properly do a garbage collection. 

### What is expected?
beforedestroy called

### What is actually happening?
beforedestroy is only called when max >=2

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/9972 regarding using max at 1. Also please, check keep-alive props documentation to control how to keep specific component alive but not others
