### ISSUE TITLE
SSR components with v-html is remounted when page is hydrated

### ISSUE THREAD

**Issue by weikinhuang** [vuejs/vue#10852]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-ssr-raw-iframe-rerender-l9xni](https://codesandbox.io/s/vue-ssr-raw-iframe-rerender-l9xni)

### Steps to reproduce
Create a minimal ssr app, with a component that uses `v-html`, and in the `v-html` content add an iframe.
Enable break on subtree modifications in chrome on the body element to see that the content is re-rendered.

### What is expected?
Iframe is loaded once in the network panel

### What is actually happening?
Iframe is loaded when the page loads and before hydration happens, and again after page is hydrated.

**Comment by posva** [comment]
Changing the text on mount triggers a rerender and sets the innerHTML again, triggering the new request (I only get two requests).

**Comment by weikinhuang** [comment]
@posva My suggestion is that if the data doesn't change between ssr render and page load's hydration, it should not re set the innerHTML of the bound element

**Comment by posva** [comment]
Isolate the `v-html` in a component so it doesn't re render

**Comment by mmase** [comment]
The component, in this case an iframe, re-renders when no changes to component data are made. This results in 2 requests for the same iframe url being made. One on SSR, one on mount.
