### ISSUE TITLE
Infinite update loop if changing vuex state property in render function

### ISSUE THREAD

**Issue by avele** [vuejs/vue#10856]
### Version
2.6.10

### Reproduction link
[https://github.com/avele/vue-infinite-update-loop-bug](https://github.com/avele/vue-infinite-update-loop-bug)

### Steps to reproduce
```
git clone git@github.com:avele/vue-infinite-update-loop-bug.git
npm i
npm run serve
```

Open http://localhost:8080/
Open debug console

### What is expected?
No "infinite update loop in a component render function." warn.

### What is actually happening?
"infinite update loop in a component render function." warn

---
Property is not used in rendering component itself or any other component, but its changing still triggers rerender.

Loop is reproduced only if new property value depends on it's previous value.

**Comment by posva** [comment]
> Property is not used in rendering component itself or any other component, but its changing still triggers rerender.

Anything used in the `render` function is considered used during render. What you are doing here is equivalent to doing the mutation in the template:

```vue
<div>{{ $store.commit('mutation') }}</div>
```

You need to use the hook `beforeUpdate` and `beforeMount` to trigger an action before rendering but changing any reactive data **during** render will create an infinite loop.
