### ISSUE TITLE
Multiple arguments in custom event with a modifier are not passed to handler

### ISSUE THREAD

**Issue by osasson** [vuejs/vue#10867]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/50wL7mdz/30115/](https://jsfiddle.net/50wL7mdz/30115/)

### Steps to reproduce
Add a modifier to one of the event listeners. e.g. @emission.once

### What is expected?
That all arguments will be passed to the function

### What is actually happening?
Only the first argument is passed

---
My guess is that it lies in the template compiler which creates a function($event){...}  and calling the handler with $event instead of ...arguments?

**Comment by posva** [comment]
As a workaround you can use this version

```js
  <component @emission.once="hearEmission('extra', ...arguments)">with extras, incomplete data</component>
```

The generated js code should be different: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%3Ccomponent%20%40emission.once%3D%22hearEmission%22%3Ecomplete%20data%2C%20without%20extras%3C%2Fcomponent%3E%0A%20%20%3Ccomponent%20%40emission.once%3D%22hearEmission('extra'%2C%20...arguments)%22%3Ewith%20extras%2C%20incomplete%20data%3C%2Fcomponent%3E%0A%20%20%3Ccomponent%20%40emission.once%3D%22function%20(a%2C%20b%2C%20c)%20%7B%20hearEmission('extra'%2C%20a%2C%20b%2C%20c)%20%7D%22%3Eexpected%2C%20overly%20explicit%3C%2Fcomponent%3E%0A%20%20%0A%3C%2Fdiv%3E

The first one should be:

```js
on: {
        "~emission": hearEmission
        }
```

The second one shouldn't change and the last one might be a bit more complicated as there should be quite a few edge cases but if we use an `apply` we should be able to keep a very similar version

**Comment by osasson** [comment]
Thanks for the quick response and for the link
