### ISSUE TITLE
v-show not working as expected in IE Browser

### ISSUE THREAD

**Issue by joemaramdocs** [vuejs/vue#10875]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/crsh7w1f/](https://jsfiddle.net/crsh7w1f/)

### Steps to reproduce
Created a div component modal that will show when you browse on IE browser. Used v-show to show the modal and change the value when clicking the icon to close the modal.

    <div class="dashboard-modal" v-show="isModalSearchShow">
      <div class="dashboard-modal__modal-mask">
        <div class="dashboard-modal__modal-wrapper">
          <div class="dashboard-modal__modal-container">
            <div class="dashboard-modal__close-container">
              <a class="acc-icon g1es-icon-close" @click="isModalSearchShow = false"></a>
            </div>
            <div class="dashboard-modal__title">
              <span>Incompatible Browser</span>
            </div>
            <div class="dashboard-modal__description">
              <span>Works best with Google Chrome and Mozilla Firefox. Please switch to either of these browsers to fully utilize the portal.</span>
            </div>
            <div class="dashboard-modal__CTA-container">
              <a class="btn btn--blue dashboard-modal__CTARefreshList" @click="loadUrl">Got it</a>
            </div>
          </div>
        </div>
      </div>
    </div> 

### What is expected?
It will close the modal because of change value in v-show

### What is actually happening?
nothing happens even the value is changing to false

**Comment by Justineo** [comment]
The link you provided isn't a runnable reproduction. But a minimal runnable reproduction is required. Thanks. See [*About Reproductions*](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro).
