### ISSUE TITLE
Memory leak with css animations

### ISSUE THREAD

**Issue by cleoo** [vuejs/vue#10872]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-ygme1](https://codesandbox.io/s/vue-template-ygme1)

### Steps to reproduce
The given code adds a component containing a text (animated with css), removes it and starts again at infinity.
make different memory snapshots running the code and you'll see the number "detached html element" growing continuously.
if you remove the "resize" animation clause in the dummy component, no more "detached html element" appears in the snapshoots

Tested on Chromium 78.0.3904.108 *

### What is expected?
Stable memory comsumption 

### What is actually happening?
Consumption of memory increases until the machine collapses

**Comment by posva** [comment]
Could someone make sure the leak doesn't happen when using vanilla js? It doubt this comes from Vue if simply removing the CSS animation removes the leak.
@cleoo did you make sure you garbage collected before doing snapshots? Did you try on a regular html file? A codesandbox is far from ideal for a memory leak report

**Comment by cleoo** [comment]
I am aware the test is not really formal. We develop applications for interactive kiosks. On some very limited configurations (equivalent raspberry pi 3) the machine freezes completely in a few hours. By removing all the animations css the problem seems to disappear. I also agree that the problem is not necessarily related to Vuejs, we simply find that memory leaks are located in the browser. 

I enclose some images, showing the evolution of the elements not released in time. I voluntarily did not trigger the garbage collector to simulate normal use

![Capture d'écran Deepin_20191129002756](https://user-images.githubusercontent.com/1513044/69893244-fe96ff80-130e-11ea-8ad5-9962dc5c6187.png)
![Capture d'écran Deepin_20191129002800](https://user-images.githubusercontent.com/1513044/69893246-00f95980-130f-11ea-844d-2eed5730a091.png)
![Capture d'écran Deepin_20191129002804](https://user-images.githubusercontent.com/1513044/69893249-0656a400-130f-11ea-9598-bcb43bca2819.png)
![Capture d'écran Deepin_20191129002809](https://user-images.githubusercontent.com/1513044/69893254-09519480-130f-11ea-8e84-1cf7a4a2afa6.png)

Quickly number of detached elements exceed 20000 without being deleted

**Comment by jeremy21212121** [comment]
I tested using https://ygme1.csb.app/ to avoid the whole editor, using chromium on linux. I saw memory increase gradually from ~30mb until around 100-120mb when it dropped back down. None of my snapshots had a large number of detached HTML Div Elements.

I created a [vanilla JS repro here](https://meowcats.fun/opwqeruiotrepoiuhjgfsdksgfdasdcvf/). It exhibits similar memory usage, gradually increasing until eventually dropping suddenly.

I'd be curious to know how much of the system memory was in use when the device froze. Do you have a swap partition configured? The out-of-memory killer should kill the process if it exhausts system memory, unless you have a swap partition configured. If it starts swapping it would likely become unresponsive.

What linux distro are you running? Any useful info in the system logs (journalctl on systemd-based distros)?

**Comment by posva** [comment]
Thanks @jeremy21212121 

>  I also agree that the problem is not necessarily related to Vuejs, we simply find that memory leaks are located in the browser.

@cleoo that's important as we can only fix the leak if the problem comes from Vue, not from the browser, which can also create leaks. In that case, the problem should be reported in chromium bug tracker using a vanilla repro like the above.
By garbage collection I mean clicking the garbage icon right under the _Elements_ panel. When doing that, you will see the heap snapshots do not increase in size

**Comment by cleoo** [comment]
> I'd be curious to know how much of the system memory was in use when the device froze. Do you have a swap partition configured? The out-of-memory killer should kill the process if it exhausts system memory, unless you have a swap partition configured. If it starts swapping it would likely become unresponsive.
> 
> What linux distro are you running? Any useful info in the system logs (journalctl on systemd-based distros)?

Thank you for the time devoted to our concern. The system (archlinux) freezes even with swap. I have been monitoring the behavior of a modified installation for two days and confirms that removing the animations only corrects the problem (the memory usage remains stable). The visual damage is not very important, only pictograms (font-awesome) were animated.
