### ISSUE TITLE
Render only first component in slot if render in browser

### ISSUE THREAD

**Issue by PNKBizz** [vuejs/vue#10887]
### Version
2.6.9

### Reproduction link
[https://codepen.io/PNKBizz/pen/zYxYQbr](https://codepen.io/PNKBizz/pen/zYxYQbr)

### Steps to reproduce
Just create component with slot and place inside two another components.

### What is expected?
Both components rendered

### What is actually happening?
Only first component rendered

**Comment by jacekkarczmarczyk** [comment]
Don't use self-closing tags in codepen

**Comment by PNKBizz** [comment]
Ooooh. Sorry )))
