### ISSUE TITLE
transition-group数据更新闪烁

### ISSUE THREAD

**Issue by No2015** [vuejs/vue#10885]
### What problem does this feature solve?
transition-group内部的数据更新，在不改变容器大小的时候，不触发列表重新排序。

### What does the proposed API look like?
不改变原API，只需要保存每次更新前后的节点状态用以计算。

**Comment by Justineo** [comment]
这显然不是一个新特性请求。如果你认为是一个 bug，请按照 bug report 的要求提供最小化复现，谢谢。
