### ISSUE TITLE
Memory related "jank" when updating components in realtime as an animation

### ISSUE THREAD

**Issue by wellcaffeinated** [vuejs/vue#10889]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/relaxed-taussig-q3cqz](https://codesandbox.io/s/relaxed-taussig-q3cqz)

### Steps to reproduce
Create a vue component that contains a lot of data in one property, and a simple "time" in another. Update the time property as part of an animation, but don't touch the other data. The animation will be janky due to garbage collection, even though the majority of the data is untouched.

### What is expected?
Smoother animation since only a single numeric property is being updated.

### What is actually happening?
As far as I can tell, the updating of reactive components is clogged up by the rest of the data, and even though a single number is being updated, the browser doesn't know to release the memory each time that property is updated. This leads to large garbage collections which cause jank in the animation.

---
I realize that the minimal reproduction i've linked to is a bit questionable. But i arrived at this problem with a more realistic scenario, where i was using a webworker to generate a lot of data, and storing it in a vuex instance. This data was not being updated at all during the animation, but was used to determine what the animation state was. However even without reading the bulky data, a simple update of a "time" property i was using to set the time of the animation was causing a huge amount of memory allocation. I will send screenshots of the _actual_ app I am developing so you can see.

**Comment by wellcaffeinated** [comment]
Here is an example of what I'm seeing in my realistic app. This is ONLY due to the update of a single time property, passed through a component attribute to a functional component that is basically the same as the one I linked to in the reproduction link. If i remove the passing of that "time" parameter, the problem goes away. If i use another method (inject, for example) to obtain the time, then again, there is no jank. 
<img width="1052" alt="Screen Shot 2019-12-03 at 7 01 38 PM" src="https://user-images.githubusercontent.com/1128935/70105885-6eeb9c80-15ff-11ea-8286-afde5b05e8fd.png">

**Comment by wellcaffeinated** [comment]
Even if this isn't a fixable bug, I'd love to figure out how to elegantly bypass this so I can continue to use vue for animations. Any suggestions?

**Comment by posva** [comment]
I'm unable to consistently get the animation junk which makes me think the garbage collection problem is not related to Vue.
If the data is very big but the inner properties of the object are not reactive (eg: the whole object is replaced), you can use `Object.freeze` to make some of the things faster.
Closing as this doesn't seem related to Vue. If you manage to dig it further and find information of where it could come from in Vue, please ping me or open a new issue
