### ISSUE TITLE
Provide warning when data/watch/computed etc. conflicts with existing Vue object properties

### ISSUE THREAD

**Issue by dz902** [vuejs/vue#10884]
### What problem does this feature solve?
I accidentally created a data attribute called `language`. It seems this attribute conflicts with some existing properties of Vue object.

There were no warnings, but the attribute won't be updated by `this.$data.language`, it stays as initial value. All other data attributes do work correctly. When `console.log(this.$data)`'d it shows 2 `language` properties, one with initial value, the other is dynamic as `(...)`. After changing this attribute to `lang` everything works.

Considering data/watch/computed etc. all ends up as properties of Vue object, it would be nice to have some warning or exception if there are conflicts.

### What does the proposed API look like?
`AttributeError: "language" is a reserved property name and should not be avoided.`

**Comment by posva** [comment]
the conflict doesn't come from Vue, it comes from a library adding it. The warning should be implemented there
