### ISSUE TITLE
一个组件就渲染了一次

### ISSUE THREAD

**Issue by chenmoand** [vuejs/vue#10883]
### Version
2.6.10

### Reproduction link
[https://codepen.io/chenmoand/pen/gObYZRw](https://codepen.io/chenmoand/pen/gObYZRw)

### Steps to reproduce
像这种闭合自定义标签<Score />就只能创建一次吗?还是bug?

### What is expected?
姓名语文数学英语总和平均值

lucy90959828394.33

tom89969828394.33

jack90959828394.33

### What is actually happening?
姓名语文数学英语总和平均值

lucy90959828394.33

**Comment by sodatea** [comment]
HTML 中没有自闭合标签的概念。
这种用法只能用于 .vue 文件或者 jsx 中。
你直接在 DOM 里这样用，解析会有问题。

参见
https://stackoverflow.com/q/3558119/2302258
https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended
