### ISSUE TITLE
I am having issues creating any new vue project

### ISSUE THREAD

**Issue by tycooperaow** [vuejs/vue#10880]
### Version
2.6.10

### Reproduction link
[https://cli.vuejs.org/guide/creating-a-project.html](https://cli.vuejs.org/guide/creating-a-project.html)

### Steps to reproduce
I use the Vue Ui to create the project. Upon creating the application I receive an 

 ERROR  command failed: npm install --loglevel error

and other Error messages on top

If I use Vue CLI v3.8.4 then run "vue create <my-project>" I receive this error
 ERROR  command failed: npm install --loglevel error

### What is expected?
I am supposed to have the entire app to be created. 

### What is actually happening?
I just get these two errors:
Vue CLI v3.8.4
✨  Creating project in C:\Users\Ty Cooper\Desktop\Coding\Apps\elevamark.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! Unexpected end of JSON input while parsing near '...l/template":"7.0.0-be'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ty Cooper\AppData\Roaming\npm-cache\_logs\2019-12-01T01_26_52_259Z-debug.log
 ERROR  command failed: npm install --loglevel error

C:\Users\Ty Cooper\Desktop\Coding\Apps>      

And for Vue UI
npm ERR! Unexpected end of JSON input while parsing near '...l/template":"7.0.0-be'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ty Cooper\AppData\Roaming\npm-cache\_logs\2019-12-01T01_18_17_639Z-debug.log
 ERROR  command failed: npm install --loglevel error
Error: Command failed: vue create elevamark-app --skipGetStarted --packageManager npm --inlinePreset {"router":false,"vuex":false,"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}}}
⚙  Installing CLI plugins. This might take a while...

    at makeError (C:\Users\Ty Cooper\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:174:9)
    at C:\Users\Ty Cooper\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\Ty Cooper\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\projects.js:345:5
    at async Object.wrap (C:\Users\Ty Cooper\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\progress.js:39:14) {
  code: 1,
  stdout: '⚙  Installing CLI plugins. This might take a while...\n\n',
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'vue create elevamark-app --skipGetStarted --packageManager npm --inlinePreset {"router":false,"vuex":false,"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}}}',  timedOut: false,
  killed: false
}

**Comment by jeremy21212121** [comment]
> npm ERR! Unexpected end of JSON input while parsing near '...l/template":"7.0.0-be'

This indicates that it encountered invalid JSON while parsing that file. A quick search of that error and "windows" turns up [this SO post](https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack#47896884) that appears to be relevant.

[The vue forums](https://forum.vuejs.org/) would be a better place to post for troubleshooting help in the future :smile:

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
