### ISSUE TITLE
If-wrapped component issue

### ISSUE THREAD

**Issue by peopleshit** [vuejs/vue#10897]
### Version
2.6.10

### Reproduction link
[https://codepen.io/peopleshit/pen/BayNQvY](https://codepen.io/peopleshit/pen/BayNQvY)

### Steps to reproduce
Add component several times with v-if and v-else statements for the same parent in template

### What is expected?
New component instance when condition changes

### What is actually happening?
The component instance remains the same, the properties passed to the component are changed

**Comment by posva** [comment]
This is expected behavior for performance. Check the key attribute to control how components are reused
