### ISSUE TITLE
can directive unbind hook be called  before component destroy ?

### ISSUE THREAD

**Issue by houfeng0923** [vuejs/vue#10893]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/withered-glitter-b6ewf](https://codesandbox.io/s/withered-glitter-b6ewf)

### Steps to reproduce
vue directive hooks is  : bind -> inserted -> update(componentUpdated) -> unbind .

`unbind` is called  after  host component  `destroyed` ; if i want to restore dom ( for example: transfer dom before  destroy)  ,  vue not support this case . when unbind ,  component is destroyed ,  $el is  isolated  , so can't get enough dom info 。

### What is expected?
unbind  called before component  destroy 
or  add a  `beforeDestroy` directive hook like ?

i guess if directive can run  before destroy, it can do more things.
or maybe i miss some consideration, please tell me and thanks .

### What is actually happening?
unbind  called after destroyed

**Comment by posva** [comment]
This is unlikely to change as it would be a breaking change but it shouldn't change anything since any Dom modification won't be rendered once the directive is unbond

**Comment by houfeng0923** [comment]
ok. i know unbind is unlikely change, but i still think some logic need be executed before destroy in directive .
