### ISSUE TITLE
vue-router Uncaught SyntaxError: Unexpected token '*'

### ISSUE THREAD

**Issue by skyunBoss** [vuejs/vue#10891]
### Version
2.6.10

### Reproduction link
[http://localhost:8000/course-chapter/1](http://localhost:8000/course-chapter/1)

### Steps to reproduce

```js
import Vue from 'vue'
import VueRouter from 'vue-router'
import App from '../App.vue';
import 'assets/css/common.scss'

Vue.use(VueRouter)

const User = {
  template: '<div>User</div>'
}

const routes = [
  {
    path: '/',
    component: App,
    children: [{
        path: '',
        component: () => import(/* webpackChunkName: "home" */ '../views/home/index.vue'),
        meta: {
          title: '首页'
        }
    }, {
      path: '/course-chapter/:id',
      component: () => import(/* webpackChunkName: "course-chapter" */ '../views/courseChapter/index.vue'),
      meta: {
        title: '课程章节'
      }
    }]
  }
]

const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes
})

export default router
```

### What is expected?
/course-chapter/1 Normal access

### What is actually happening?
/course-chapter/1 Page blank

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

> http://localhost:8000/course-chapter/1

Sorry but this is not a reproduction...
