### ISSUE TITLE
render called twice whit dynamic import

### ISSUE THREAD

**Issue by wowissu** [vuejs/vue#10902]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/rendercalledtwice-rfrbt](https://codesandbox.io/s/rendercalledtwice-rfrbt)

### Steps to reproduce
I want Vue can render the template by follow the json file which I defined.
so I start trying trough by render methods with dynamic import component, 
then seen this happen. it show the same template double times when I using the ssr mode
so I try to reproduction it at spa mode and it still called twice even thought it looks fine at spa mode

### What is expected?
render only called once even using dynamic import 

### What is actually happening?
it called twice 
trouble with double template in ssr mode

**Comment by posva** [comment]
This is expected, it renders once and then again once the dynamic component is loaded. This allows partially rendering a template, it's a feature.

**Comment by wowissu** [comment]
it render once on server side 
and then twice on client side 
total is three times

**Comment by wowissu** [comment]
> it render once on server side
> and then twice on client side
> total is three times



> This is expected, it renders once and then again once the dynamic component is loaded. This allows partially rendering a template, it's a feature.

oh ! I understand what you mean for now. but is any possible to discriminate twice render ?
