### ISSUE TITLE
默认路由跳转（路由重定向）问题

### ISSUE THREAD

**Issue by MikuBlog** [vuejs/vue#10909]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/currying-bush-zjhwz](https://codesandbox.io/s/currying-bush-zjhwz)

### Steps to reproduce
1. 在router核心文件内填写重定向配置，如{ path: "*", redirect: "/home" }，重定向至home.vue。
2. 在home.vue页面组件的created等初始化生命周期函数中写入window.location.href="指定网站"或window.open(指定网站)。
3. 在APP.vue中的created生命周期函数中写入window.location.href="指定网站"或window.open(指定网站)。
4. 在浏览器地址输入框输入http://localhost:8080并按下回车。
结果：先执行home.vue生命周期函数created中的重定向代码。而其他相关逻辑则是先执行APP.vue生命周期created中的代码再执行home.vue中的逻辑。

### What is expected?
执行APP.vue的重定向代码

### What is actually happening?
执行home.vue中的重定向代码

**Comment by posva** [comment]
home being mounted after App, its code gets executed later. This is normal

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by MikuBlog** [comment]
@posva But why is home code prior to app execution

**Comment by MikuBlog** [comment]
In this case, should jump to bilibili.com instead of baidu.com
