### ISSUE TITLE
Can vue support the syntax of handlebars?

### ISSUE THREAD

**Issue by 403605209** [vuejs/vue#10908]
### What problem does this feature solve?
我想要一个清晰的模版, 就像YoxJS做的那样, 
把if、 for写在element内真的不是一个好主意.

I want a clearer template, just like YoxJS does.
It's really not a good idea to write if and for inside element.

### What does the proposed API look like?
```javascript
<script id="template" type="text/plain">
	<div>
  	{{#each user:key}}
    	<p>
      	key: {{key}}<br>
      	value: {{this}}<br>
        type: {{formatType(this)}}
      </p>
      {{/each}}
  </div>
</script>
<script>
new vue({
  template: '#template',
  data: {
    user: {
      name: 'yox',
      age: 2
    }
  }
})
</script>
```

**Comment by Justineo** [comment]
We have not intention to change our template syntax at the moment. Thanks.
