### ISSUE TITLE
v-pre performance improvement with large DOM tree

### ISSUE THREAD

**Issue by mihalikv** [vuejs/vue#10913]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/0qLfkg3p/1/](https://jsfiddle.net/0qLfkg3p/1/)

### Steps to reproduce
When you open reproduction link you can see that execution of creating Vue instance take around 80ms. Reason for this is large number of DOM tree. Notice that ul tags have v-pre directive.

### What is expected?
I expect that Vue.js will skip elements that are marked with v-pre and execution time should be similar to template without these lists.(https://jsfiddle.net/sqyzd6f9/) 

### What is actually happening?
Vue.js skip evaluating of vue tags, but still somehow compile and parse this static content and execution time is similar to normal template without v-pre.(https://jsfiddle.net/58kguf39/1/)

**Comment by posva** [comment]
Vue still needs to render all those elements when rendering the template. You can use `v-once` to get some better performance and also put the whole template that doesn't change inside a different component to prevent extra renders. This won't be an issue with Vue 3

**Comment by mihalikv** [comment]
@jan-vodila I checked number 4 and it looks that you use the wrong unpkg it is still vue.js 2.6. When you try this example you can see performance improvements https://jsfiddle.net/0yq4aL26/

**Comment by jan-vodila** [comment]
Hi @mihalikv, you are right, it was still vue.js 2.6.
However, in your jsfiddle, you didn't mount the app to #app div, that's why it was "quick".
I have updated your code: https://jsfiddle.net/y0xpvemg/1/ it's still "pretty" slow as with vue v2.
