### ISSUE TITLE
vue-server-renderer using vulnerability from serialize-jabascript

### ISSUE THREAD

**Issue by staghouse** [vuejs/vue#10910]
### Version
vue-server-renderer: 2.6.10

### Reproduction link (PR on original package)
[https://github.com/yahoo/serialize-javascript/commit/16a68ab53d9626fc7c942b48a1163108fcd184c8](https://github.com/yahoo/serialize-javascript/commit/16a68ab53d9626fc7c942b48a1163108fcd184c8)

### Vulnerability reference
https://github.com/yahoo/serialize-javascript/security/advisories/GHSA-h9rv-jmmf-4pgx

### Steps to reproduce
GitHub alerts show the error

### What is expected?
No vulnerability

### What is actually happening?
Vulnerability

---
Related to the auto-build of vue-server-render

**Comment by posva** [comment]
Closing as there was already https://github.com/vuejs/vue/pull/10904
