### ISSUE TITLE
Allow named, nested slots

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#10919]
### What problem does this feature solve?
Consider the two components `tabs` and `tab`:
```html
<tabs :current="current">
    <tab tabname="tab1">
        <div>{{someContent}}</div>
    </tab>
    ...
</tabs>
```

The `tabs` component programmatically sets the contents of the current tab on an `onclick` event.
Currently, to display the active tab, we need to loop `this.$slots.default`

It would be more convenient to use a named-slot inside the `tabs` template like so:
```js
template: `<div class="tabs"><slot :name="current"></slot></div>`
```
However, this requires the `tab` components to return a template with the `<template>` tag:
```js
template: `<template v-slot=${tabid}><div class="tab"><slot></slot></div></template>`
```
But this is not allowed: "Cannot use <template> as component root element because it may contain multiple nodes"

### What does the proposed API look like?
1. Allow `template` tag as root element
2. Allow `div` as named slot
3. ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

to pass a nested slot, you need to pass it again on the middle component. Using a render function will probably make your case work.
