### ISSUE TITLE
vue ssr  refresh iframe on the client. 

### ISSUE THREAD

**Issue by firstsmarts** [vuejs/vue#10918]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0/](https://github.com/vuejs/vue-hackernews-2.0/)

## reproduce by vue-hackernews-2.0 (vue ssr official demo)

# edit ./App.js

add the code bottom:

```html
</transition>
<iframe v-if="src" :src="src" frameborder="0"></iframe>
</div>
```

```javascript
export default {
    computed:{
      src(){
        let items = this.$store.state.items
        return items[Object.keys(items)[1]].url
      }
    }
  }
```

### What is expected?
iframe load once 

### What is actually happening?
Iframe begin loading when the page is downloaded, but it will refresh the url when the client hydrated.

---
It certainly appear in Firefox.

**Comment by posva** [comment]
If it's refreshed, it's because the `src` attribute changed value.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by firstsmarts** [comment]
> If it's refreshed, it's because the `src` attribute changed value.
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

Actually i got the src from store, and the server store is the same as the client store. 

I tried to find the answer from forum and stackoverflow, but no answer helped, so i reproduced it by add that code to your official demo, and it refresh as well, i have no idea about it.

Thanks for your reply.
