### ISSUE TITLE
How can I exclude a js file?

### ISSUE THREAD

**Issue by mreorhan** [vuejs/vue#10921]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Im using a js file for config settings like apiurl. After the build, these files merging in a bundle file. I need to change this file after build.

### What is expected?
An excluded config file

### What is actually happening?
Bundled these files

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
