### ISSUE TITLE
Typescript npm library cannot access `this.$http` which defines in `main.ts`

### ISSUE THREAD

**Issue by wxs77577** [vuejs/vue#10925]
### Version
2.6.10

### Reproduction link
[https://github.com/topfullstack/v-crud](https://github.com/topfullstack/v-crud)

### Steps to reproduce
I've created a library called `test-com`, and then I created an ts vue app.
> main.ts
```ts
import Vue from "vue";
import axios from "axios";
Vue.prototype.$http = axios

import TestCom from "test-com";
Vue.use(TestCom)
```

> home.vue
```html
<template>
  <div><test-com/></div>
</template>
```

> TestCom.vue in `test-com` library
```html
<script lang="ts">
// Works if I use `export default {}`
export default {
  created(){
    console.log(this.$http) // an axios instance
  }
}

// Doesn't work if I use `export default Vue.extend({})`
export default Vue.extend({
  created(){
    console.log(this.$http) // an axios instance
  }
})

// Doesn't work if I use `export default class`
import Vue from 'vue'
import Component from 'vue-class-component'
import { Prop } from 'vue-property-decorator';
@Component({})
export default class TestCom extends Vue {

  created(){
    console.log(this.$http) // undefined
  }
}
</script>
```

> vue.config.js
```js
const path = require("path")

const isProd = process.env.NODE_ENV === 'production'

module.exports = {
  css: { extract: false },
  outputDir: "docs",
  configureWebpack: {
    output: {
      libraryExport: "default"
    },
    externals: isProd ? {
      'vue-class-component': 'vue-class-component',
      'vue-property-decorator': 'vue-property-decorator',
      'vue': 'vue'
    } : {},
    resolve: {
      alias: {
        "v-crud": path.resolve(__dirname, "./")
      }
    }
  }
};

```

### What is expected?
`this.$http` is an axios instance

### What is actually happening?
`this.$http` is undefined

---
clone `https://github.com/topfullstack/v-crud`
yarn && yarn lib && yarn link  v-crud
cd /path-to-another-vue-app
yarn link v-crud
`import VCrud form 'v-crud'`
`Vue.use(VCrud)`
`<v-crud-table resource="users"></v-crud-table>`

**Comment by ssimontis** [comment]
What happens if you try to access this.$parent.$http instead of this.$http?

**Comment by wxs77577** [comment]
@ssimontis Thanks for your reply, it works, `this.$parent.$http` is an axios instance.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Check how vue-router or Vuex add `$router` and `$store` everywhere
