### ISSUE TITLE
vue-server-renderer, npm audit reports vulnerability in serialize-javascript version

### ISSUE THREAD

**Issue by kwmx** [vuejs/vue#10923]
### Version
2.6.10

### Reproduction link
[https://www.npmjs.com/advisories/1426](https://www.npmjs.com/advisories/1426)

### Steps to reproduce
1- Install vue-server-renderer
2- Run npm audit

### What is expected?
Upgrading to a newer version would solve this issue.

### What is actually happening?
There is a 'Cross-Site Scripting'  vulnerability in dependency 'serialize-javascript'. Upgrade to version 2.1.1 or higher would solve the issue.

---
As reads on npm audit report

│ Moderate: Cross-Site Scripting                                         
│ Package: serialize-javascript                                         
│ Patched in: >=2.1.1                                                      
│ Dependency of: vue-server-renderer                                          
│ Path: vue-server-renderer > serialize-javascript                   
│ More info: https://npmjs.com/advisories/1426

**Comment by posva** [comment]
Thank you there is already an open pull request
