### ISSUE TITLE
if the default property in `inject` be a function it's calling on resolving

### ISSUE THREAD

**Issue by alirezavalizade** [vuejs/vue#10938]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/distracted-haze-f1r6e](https://codesandbox.io/s/distracted-haze-f1r6e)

### Steps to reproduce
Sometimes you use `inject` property to inject a method from parent or grand parents, but if you create a re-usable component it's better to add a default property to your injected key and you expect when the injection didn't resolve, the function in default key should be call instead of the main function which didn't resolve.

```js
new Vue({
  inject: {
    foo: {
      default: function() {
        return 1;
      }
    }
  },
  created() {
    this.foo();
  }
});
```

### What is expected?
I expect that default methods in inject get resolve without being called when it's resolving. it should return a function instead of calling them.

### What is actually happening?
I checked out the inject.js and I found that we are calling the default functions instead of returning them. this can cause issues.

**Comment by posva** [comment]
You need to use a function that returns a function because functions are used to return objects and a function is an object in js:

```js
inject: {
    test: {
      default: () => function() {
        return "alireza";
      }
    }
  }
```

**Comment by alirezavalizade** [comment]
yeah,  but isn't weird? what are the advantage of this approach which always need to create a function which return a function?

**Comment by posva** [comment]
Read the last part at https://vuejs.org/v2/api/#provide-inject and https://vuejs.org/v2/guide/components-props.html#Prop-Validation
This is to prevent from sharing the same object because objects are passed by reference in JS

**Comment by alirezavalizade** [comment]
ok, thanks for the reply.
