### ISSUE TITLE
unable to access Vue instance on Custom Methods

### ISSUE THREAD

**Issue by vksco** [vuejs/vue#10935]
### Version
2.6.10

### Reproduction link
[https://stackoverflow.com/questions/59171904/vue-optionmergestrategies-methods-has-no-access-to-this-keyword](https://stackoverflow.com/questions/59171904/vue-optionmergestrategies-methods-has-no-access-to-this-keyword)

I don't know if its a bug, feature or eventually I am doing it wrong.
please check the StackOverflow link I have given.

### What is expected?
I want to access current Vue instance by 'this' keyword under the customMethod

### What is actually happening?
returning 'undefined'

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
