### ISSUE TITLE
Custom directive update hook not triggered when using object literal expressions

### ISSUE THREAD

**Issue by dm4t2** [vuejs/vue#10933]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-directive-update-hook-bug-zelsx](https://codesandbox.io/s/vue-directive-update-hook-bug-zelsx)

### Steps to reproduce
Open the CodeSandbox and click on the "+" buttons to change the directive expression values.

### What is expected?
There should be a console log entry each time the value is updated for ONLY the respective element the directive is bound to.

### What is actually happening?
For case 3 (using data attribute) the update hook is not triggered. For case 1+2 the update hook is always triggered for all elements. Is this intended?

**Comment by posva** [comment]
If you don't happen to use that `number` property inside of the directive, the update doesn't trigger. Use it and it will.

> There should be a console log entry each time the value is updated for ONLY the respective element the directive is bound to.

`update` triggers when the component updates: https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions

**Comment by dm4t2** [comment]
@posva Thank you for explaining 👍
