### ISSUE TITLE
Uncaught TypeError: n.setAttribute is not a function when ssr client-side hydration

### ISSUE THREAD

**Issue by yinxin630** [vuejs/vue#10937]
### Version
2.6.10

### Reproduction link
[https://github.com/yinxin630/vue-issue-example](https://github.com/yinxin630/vue-issue-example)

### Steps to reproduce
1. clone and npm i
2. run `npm run build` and `npm run build:ssr`
3. run `node src/ssr.js`
4. render app.js with ssr get result
```html
<div id="app" data-server-rendered="true"><!----><h2>2222222222</h2></div>
```
5. open in browser. client-side hydration will throw error `Uncaught TypeError: n.setAttribute is not a function`

### What is expected?
client-side hydration success

### What is actually happening?
throw error `Uncaught TypeError: n.setAttribute is not a function`

---
I found this when debug. vue call `n.setAttribute('class', 'm-image-padding')` but n is a comment node.

In `app.js` I use `v-if`. It will be true when ssr but be false when csr.

I don't know if there is something wrong with my usage or the logic of vue client-side hydration.

**Comment by yinxin630** [comment]
#5919

**Comment by posva** [comment]
There as a division by `undefined` at 

```html
:style="{ paddingTop: `${(1 / aspectRatio) * 100}%` }"
```

Make sure `aspectRatio` is a number !== 0 and `NaN`. You can use `Infinity` to get 0: `20/Infinity -> 0`

**Comment by yinxin630** [comment]
> There as a division by `undefined` at
> 
> ```
> :style="{ paddingTop: `${(1 / aspectRatio) * 100}%` }"
> ```
> 
> Make sure `aspectRatio` is a number !== 0 and `NaN`. You can use `Infinity` to get 0: `20/Infinity -> 0`

Thanks for your reply. But it should not be for this reason.

The problem persisted after I changed it to `:style="{ backgroundColor: 'red' }"`

https://github.com/yinxin630/vue-issue-example/commit/8d183a7ec35cf86f56ccecde6d0d424e01c4db0a

**Comment by posva** [comment]
Right I didn't see that `v-if`
You have an hydration problem because on the server the `v-if` is falsy while on the client is truthy. It must be the same value upon initial rendering. So make sure the initial value is the same on data and change it in mounted (only runs on the client):

```js
export default {
  data() {
    return {
      aspectRatio: 0
    };
  },

  mounted() {
    this.aspectRatio = 2;
  }
};
```

**Comment by yinxin630** [comment]
@posva  Thanks, this is an effective solution.

I also found that I only need to change `v-if` to `v-show`, and the result is as expected

**Comment by kirkins** [comment]
Also getting this error but not when running with `npm run dev` only once I went to deploy I found there was problems related to said error.

**Comment by Sir-Deon** [comment]
@kirkins I have this same issue on production mode but not on dev mode

**Comment by jigs1996** [comment]
> 
> 
> @kirkins I have this same issue on production mode but not on dev mode

Yes i have same issue any suggestion

**Comment by sishenhei7** [comment]
> I have the exact same problem, a value is false on ssr, true on csr, I have a v-if to display or not a NuxtLink. Upon hydration, console displays `TypeError: el.setAttribute is not a function`.
> 
> Note :
> 
> * I'm running the project through `yarn dev`
> * I can simply fix the problem using `v-show` instead of `v-if`
> * I have to refresh the page to see the error : if I navigate through my app using the router, all is fine
> * And **MOST IMPORTANTLY**, i do not have the problem if the `v-if` has a corresponding `v-else`

I know why you do not have the problem if the `v-if` has a corresponding `v-else`.
It's because without `v-else`, at ssr vue will render the node to a comment node, however comment node don't have a `setAttribute ` method; but with `v-else`, vue will render the 'else' node, which is a vue node and has the `setAttribute` method。

**Comment by KiranJasvanee** [comment]
Any solution to this issue? I'm still facing the issue in production. In dev it's working fine.

**Comment by rahulmanas** [comment]
v-if was the issue. In SSR mode, i was using v-if in the layout. I removed the v-if with v-show and it worked like a charm.

**Comment by rrmesquita** [comment]
In my case, the main issue is that when this error happens, everything else is prevented to execute, so instead of just breaking one part of the page, the whole rest of the page doesn't work.

**Comment by truesteps** [comment]
Any updates on this issue?

**Comment by TabishAliMughal** [comment]
Any Update?
