### ISSUE TITLE
Vulnerability on vue-server-renderer

### ISSUE THREAD

**Issue by Berkmann18** [vuejs/vue#10930]
### Version
2.6.10

### Reproduction link
[https://github.com/meditatingdragon/starter-gridsome-vuetify](https://github.com/meditatingdragon/starter-gridsome-vuetify)

### Steps to reproduce
Have `gridsome` as a dependency (or whatever depends on `vue-server-renderer`) and observe GitHub and Snyk.

### What is expected?
No vulnerabilities

### What is actually happening?
XSS vulnerability caused by an outdated version of `serialize-javascript` (i.e. older than `v2.1.1`).

---
I tried highlighting this issue in the discord server but it didn't seem that people cared. 
https://npmjs.com/advisories/1426

**Comment by LinusBorg** [comment]
It seems this doesn't affect us since the advisory states:

> This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

... and vue-server-renderer runs in a Node.js environment.

I may be missing something, and of course this dependency should be updated - but there doesn'T seem to be any immediate risk for users of this package.

**Comment by Berkmann18** [comment]
There may be no immediate risk, however having GitHub, Snyk and NPM mention this vulnerability (which doesn't play nice with InfoSec folks who I work for) is kinda annoying.

I mentioned to others that if I didn't think it was going to affect the website I'm working on but I'll rather not have NPM+Snyk+GH being noisy you know.

**Comment by LinusBorg** [comment]
Of course, I understand that. It was just important to me that readers are aware of the low risk level.

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/pull/10914

**Comment by Berkmann18** [comment]
@posva How is the **issue** a duplicate of the **PR**?
