### ISSUE TITLE
svg sprite  bug  used in v-if or class switched

### ISSUE THREAD

**Issue by bimohxh** [vuejs/vue#10934]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/hxh1246996371/5r1xw78L/8/](https://jsfiddle.net/hxh1246996371/5r1xw78L/8/)

### Steps to reproduce
I  use svg sprite create a icon component named `icon.vue`

```js
<template>
  <span class="icon-box" :style="{width: (size || 24)   'px', height: (size || 24)   'px'}">
    <svg :class="'icon-'   (type || 'feather')">
      <use :xlink:href="'assets/svg/'    (type || 'feather')   '.svg#'   name"></use>
    </svg>
  </span>
</template>

<script>
export default {
  props: ['type', 'name', 'size']
}
</script>
```

so, when I use like this

```
<icon name="check" size="20" />
```
this will work ok, but when I use 

```
<icon name="check" size="20" v-if="isok"/>
<icon name="error" size="20"  v-else/>
```

or 

```
<icon :name="isok ? 'check' : 'error' " size="20" />
```

the above will raise error!

### What is expected?
switch svg sprite icon correctly!

### What is actually happening?
svg icon will  be empty when the `isok` data changed!

---
 but `v-show` will work.

**Comment by posva** [comment]
Please provide a runnable repro when reporting a bug.

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
