### ISSUE TITLE
Update vue-template-compiler to 2.6.11 problemVue packages version mismatch

### ISSUE THREAD

**Issue by huang-x-h** [vuejs/vue#10932]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/withered-wave-s5gel?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/withered-wave-s5gel?fontsize=14&hidenavigation=1&theme=dark)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.12.0 => 3.12.1
    @vue/cli-plugin-eslint: ^3.12.0 => 3.12.1
    @vue/cli-service: ^3.12.1 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.1.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: 2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-router: 3.0.7 => 3.0.7
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: 3.1.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
In our project, we lock the `vue` version to 2.6.10,  do not lock the `vue-template-compiler` version.

So when we reinstall package, `vue-template-compiler` install to 2.6.11

Then run the serve `npm run serve`, the console output error

![image](https://user-images.githubusercontent.com/381860/70847339-9152a500-1e9e-11ea-9189-639301c2defd.png)

So, `vue` and `vue-template-compile` should be same version?

### What is expected?
Should `vue-template-compile` high version support low version `vue`

### What is actually happening?
`vue` and `vue-template-compile` should be the same version

**Comment by posva** [comment]
> So, vue and vue-template-compile should be same version?

yes, they **must** be the same version

**Comment by huang-x-h** [comment]
OK，thanks

**Comment by DespertaWeb** [comment]
[SOLVED!!]

I went to the very same package.json file of the vue-template-compiler that is complaining, changed the version of the package in there and run yarn, like so:

_~/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/package.json_:

```
OLD:
  "name": "vue-template-compiler",
  "version": "2.6.11"
```

```
NEW:
  "name": "vue-template-compiler",
  "version": "2.6.10"
```

**Comment by rahulonsong** [comment]
That worked for me. Thank you

**Comment by ihrimech** [comment]
Thanks a lot ! worked for me too. Wouldn't it be better if it was done in _vue-template-compiler_?

**Comment by Huda303** [comment]
All you have to do is one thing, follow the path and change the vue-template-compiler to the version of the framework. It's work for me , hope that help someone
