### ISSUE TITLE
如何用pm2 管理vue项目

### ISSUE THREAD

**Issue by skypiaoyizhe** [vuejs/vue#10940]
### What problem does this feature solve?
pm2 启动和管理vue项目  没有找到启动的js文件

### What does the proposed API look like?
pm2 start xxx.js
pm2 start xxx.json
pm2 list

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
