### ISSUE TITLE
新建VUE工程，工程内的.vue文件有合适的语法提示，但是.js文件没有语法提示，这里很不友好

### ISSUE THREAD

**Issue by takhello** [vuejs/vue#10943]
### Version
2.6.10

### Reproduction link
[https://github.com/takhello/vue-project-main](https://github.com/takhello/vue-project-main)

### Steps to reproduce
01.新建项目，安装默认依赖
02.新建 .js文件 
03.书写javascript语法
04.没有语法提示
05.新建.vue文件
06.书写javascript语法, 有提示
07.删除node_module目录，.js文件恢复提示
08.参考文件 package.json里默认的依赖项目
  "dependencies": {
    "core-js": "^3.4.3",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.6.10"
  },

bug: 为什么安装默认依赖会导致 .js文件无语法提示？

### What is expected?
js文件出现语法提示

### What is actually happening?
目前.js文件无提示

---
参考随后提交的图片附件
 01.vue文件语法提示
 02..js文件无语法提示

**Comment by takhello** [comment]
.vue文件语法提示：
![8-1](https://user-images.githubusercontent.com/24371818/71240997-73c18780-2345-11ea-82ec-ef395f733165.png)
.js文件无语法提示:
![9-1](https://user-images.githubusercontent.com/24371818/71241030-86d45780-2345-11ea-824c-a981c512998d.png)

**Comment by takhello** [comment]
移除项目 重新clone，

**Comment by posva** [comment]
This is not related to Vue but to the editor you are using. With VSCode make sure to install Vetur

**Comment by takhello** [comment]
已安装Vetur 0.22.6版本

**Comment by takhello** [comment]
补充: 这个现象是在已安装Vetur 0.22.6版本前提下出现的，这里或许存在其它不稳定问题

**Comment by takhello** [comment]
找到了问题的大概原因，
FIX: 这个问题在vscode VSCodeUserSetup-x64-1.37.0.exe 上不出现，在VSCodeUserSetup-x64-1.41.1.exe出现 ，
