### ISSUE TITLE
Cypress E2E tests not running in CI mode on gitlab.com

### ISSUE THREAD

**Issue by usamahamed** [vuejs/vue#10944]
### Intro

I'm not 100% sure where to ask this question but we struggle to setup cypress in the CI runners of gitlab.com. We use the default blueprint from vue-cli to scaffold the project. We tried various of different gitlab.yml configurations. Currently we run out of CI minutes because we tried so many different combinations. 

We tried different docker images (from here: https://github.com/cypress-io/cypress-docker-images/) and also followed the best practices from Crypress which we found here: https://gitlab.com/cypress-io/cypress-example-docker-gitlab/

We just had no luck getting it running. After spending hours of hours we are not sure if it's even possible to get Cypress running with the default setup from vue-cli.

Since it's not a real "JavaScript" issue it's hard to fill out the default template properly but we tried to provide as much information as possible. In the code bin you find our results. The HTML column is the output and the JS column is the YML file. I hope you can use this information somehow

### Version
2.6.10

### Reproduction link
[https://codepen.io/usamahamed/pen/WNbpdPE](https://codepen.io/usamahamed/pen/WNbpdPE)

### Steps to reproduce
this this the gitlab CI pipeline result including in codepen 
it give this 
```
CypressError: cy.visit() failed trying to load:
We failed looking for this file at the path:
/builds/room/web/room-ui/ 
```
 

### What is expected?
Expected CI to run successfully 

### What is actually happening?
Pipeline is failed

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by usamahamed** [comment]
@posva since no one on Discord was able to help us we created a StackOverflow question: https://stackoverflow.com/questions/59424009/cypress-e2e-tests-not-running-in-ci-mode-on-gitlab-com

Probably someone can help us 🙂

**Comment by tschoartschi** [comment]
I know @posva closed this issue but we are still not able to get the vue-cli Cypress setup to work on Gitlab runners. Also we found no help in Discord and StockOverflow 🤔 we feel somehow lost, maybe there is someone out there who managed to setup `@vue/cli-plugin-e2e-cypress` to work on Gitlab.

**Comment by posva** [comment]
Maybe you could check the https://www.github.com/vuejs/vue-cli repository which is where the plugin is hosted. But this seems to be related to Cypress + Gitlab runners, so I would personally contact Gitlab support or check issues on cypress first and then check the cli plugin itself

**Comment by tschoartschi** [comment]
Just for reference if someone else has the same problems, we needed to use the correct image from: https://github.com/cypress-io/cypress-docker-images

For us it was `image: cypress/base:8` and now everything is just working. We didn't figure out why the other images are failing? But we are happy that it works now.
