### ISSUE TITLE
Keep-state Global Annotation

### ISSUE THREAD

**Issue by Galfour** [vuejs/vue#10953]
### What problem does this feature solve?
To maintain state in an element of a list, one can use `v-bind:key`, as explained [here](https://vuejs.org/v2/guide/list.html#Maintaining-State). This makes creating a todo-list while keeping the local state intact (selections, focus, input text, other things the browser / included plugins deal with for us) trivial.

However, if I happen to want more than a todo-list, like, a Kanban Board, and I want to be able to move elements across columns, well, it does not work any more.
There are some hacks that could work for this particular case (having the Kanban board be a single array, that simply looks like a Kanban board through bad CSS tricks). But they are bad, and can not be extended to more complex situations (like, a recursive todo-list, the kind that you can find on Workflowy, Dynalist, Notion, etc.).

### What does the proposed API look like?
How I could see it work is with a `global-key` attribute on vue elements. It would act exactly like `key` in `v-for`, but globally.

**Comment by posva** [comment]
I'm not sure to grasp how global-key would work since it's precisely supposed to be local to an element/component. Overall, the information here is not enough to understand the feature request and it makes me understand you need guidance in implementing a board more than anything else. For the purpose, please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Galfour** [comment]
@posva 

> I'm not sure to grasp how global-key would work
> you need guidance in implementing a board more than anything else

I tried to follow the form to make a ticket, and gave a fake example to illustrate my point. I don't need to write a Kanban board.

Perhaps I should have been more technical from the get-go? I'd like to give VueJS hints to its reconciliation algorithm to avoid re-renders. Alternatively, I'd like to be able to re-parent components. A similar issue on React is https://github.com/facebook/react/issues/3965 .
Those two comments might be clearer explanations of the need:
- https://github.com/facebook/react/issues/3965#issuecomment-361705968
- https://github.com/reactjs/rfcs/pull/34#issuecomment-372293861
