### ISSUE TITLE
Destructuring slot props don't work in ie11

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue#10959]
### Version
2.6.11

### Reproduction link
[https://github.com/dxvladislavvolkov/vue_systemjs](https://github.com/dxvladislavvolkov/vue_systemjs)

### Steps to reproduce
1. Clone repo
2. run npm i lite-server
3. run command lite-server

Open link http://localhost:3000/ in ie

### What is expected?
No errors in console

### What is actually happening?
I get the error

[Vue warn]: Failed to generate render function:

SyntaxError: Expected identifier in

with(this){return _c('Field',{scopedSlots:_u([{key:"first",fn:function({user}){return [_v("\n      " _s(user.firstName) "\n    ")]}}])})}```

**Comment by posva** [comment]
This is expected. It's necessary to transpile the generated code for it to work on any browser not supporting  restructuring. This should help: https://vue-loader.vuejs.org/options.html#transpileoptions
