### ISSUE TITLE
DOM doesn't sync with data in a rare case

### ISSUE THREAD

**Issue by 07akioni** [vuejs/vue#10952]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/adoring-framework-lx5k7](https://codesandbox.io/s/adoring-framework-lx5k7)

### Steps to reproduce
Following the link.

### What is expected?
I think dom should be updated when input something.

### What is actually happening?
DOM is not updated.

---
If you add v-if="true" on &lt;template v-slot:debugger&gt;, or simply remove &lt;template v-slot:debugger&gt;, or change { scopedSlots: this.$scopedSlots } to { scopedSlots: { ...this.$scopedSlots} }, the example will work well. I think it is related to some diff operations.

**Comment by posva** [comment]
The scopedSlots cannot be passed down to children just like that because it contains information that links it to the current component, creating a new object is necessary:

```js
scopedSlots: {
        default: this.$scopedSlots.default,
        debugger: this.$scopedSlots.debugger,
      }
// or as you mentioned
{ ...this.$scopedSlots }
```

Otherwise the slot isn't rendered when wrapper changes

**Comment by Patrick-Spiegel** [comment]
@posva is it possible to annotate in the docs that we cannot pass scoped slots directly to children?
