### ISSUE TITLE
Add caching configuration to computed properties

### ISSUE THREAD

**Issue by teh-mICON** [vuejs/vue#10956]
### What problem does this feature solve?
As it stands, computed properties are delivered from cache if the read property is not reactive.

Some values can't be made reactive however like when reading from localStorage. In such circumstances, a lot of work around this caching needs to be done to avoid the caching feature. For example, one would have to create a Vue.observable and proxy through it to avoid the caching.

I propose a new option for computed properties to turn caching off.

### What does the proposed API look like?
```
computed: {
  foo: {
    get() { return localStorage.foo },
    set(value) { localStorage.foo = value; },
    caching: false
  }
}
```

**Comment by posva** [comment]
This was removed in the past. Use a method instead if you always need to read the value.
For the specific usages of local storage, you can find plugins that handle that for you in a similar way

**Comment by teh-mICON** [comment]
Why was it removed?

And a method is not settable
