### ISSUE TITLE
js控制css或scss变量，方便用户设定主题色

### ISSUE THREAD

**Issue by Tron1234** [vuejs/vue#10950]
### What problem does this feature solve?
js控制css或scss变量，方便用户设定主题色

**Comment by Justineo** [comment]
SCSS variables only work at build time and you can't make them reactive with runtime JavaScript. But you can use reactive CSS custom properties at runtime, see https://github.com/vuejs/vue/issues/7346.

**Comment by Tron1234** [comment]
只有web端可以通过js修改css里的变量因为里面右dom元素，但是例如uniapp这样的就不能这样，因为里面没有dom元素



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GU Yiling"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 下午3:51
收件人: "vuejs/vue"<vue@noreply.github.com&gt;; 
抄送: "夜雨般的十年"<506980247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vuejs/vue] js控制css或scss变量，方便用户设定主题色 (#10950)




SCSS variables only work at build time and you can't make them reactive with runtime JavaScript. But you can use reactive CSS custom properties at runtime, see #7346.

**Comment by Tron1234** [comment]
谢谢，我知道Vue支持，但是uni-app不支持，QAQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GU Yiling"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 下午3:51
收件人: "vuejs/vue"<vue@noreply.github.com&gt;; 
抄送: "夜雨般的十年"<506980247@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vuejs/vue] js控制css或scss变量，方便用户设定主题色 (#10950)




Closed #10950.
