### ISSUE TITLE
in jsx use Use < component / >

### ISSUE THREAD

**Issue by webgzh907247189** [vuejs/vue#10957]
### What problem does this feature solve?
in jsx use
{
  render (){
    const xxx = () => import("./yyy");
    return <component is={xxx} />;
}
}
What shall I do?

### What does the proposed API look like?
in jsx use
{
  render (){
    const xxx = () => import("./yyy");
    return <component is={xxx} />;
}
}

**Comment by webgzh907247189** [comment]
{
render (){
const xxx = () => import("./yyy");
return < component is={xxx}/ >;
}
}
What shall I do?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
