### ISSUE TITLE
Use static data in Vue.js template

### ISSUE THREAD

**Issue by nicolidin** [vuejs/vue#10962]
### Version
2.6.11

### Reproduction link
[https://gist.github.com/nicolidin/52f1c7bca34e47b707bb2ca745968404](https://gist.github.com/nicolidin/52f1c7bca34e47b707bb2ca745968404)

### Steps to reproduce
Run this component or the corresponding gist (class based instead of enum based)

```vue
<template>
  <div class="home">
    <div v-if="Thing.FOO === yourData"> 
    <!-- same error message -->
      <p>tata</p>
    </div>
    <div v-else>
      <p>toto</p>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";

enum Thing {
  FOO,
  BAR,
  BAZ
}

@Component
export default class Home extends Vue {
  yourData: Thing = Thing.FOO;
}
</script>
```

### What is expected?
I expect to evaluate the condition in the template referencing an external static symbol.

### What is actually happening?
At runtime the condition produces a javascript exception : Property or method "Thing" is not defined on the instance 
     but referenced during render.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is also related to the package vue-property-decorator, not to Vue itself

**Comment by denis-pujdak-adm-it** [comment]
The answer is here: https://stackoverflow.com/questions/54055097/use-global-variable-in-vue-template
