### ISSUE TITLE
Allow defining order in v-for

### ISSUE THREAD

**Issue by ybasefinal** [vuejs/vue#10965]
### What problem does this feature solve?
Vue currently does not directly support reverse loops. Generally, it can be solved by using calculated attributes, but if you want to iterate over the objects in slotProps, the calculated attributes are not available (it is also possible that my usage is wrong). I hope there is a way that The method of traversing the array, so that you no longer need to create calculated properties for the array

### What does the proposed API look like?
Consider adding a property to v: for to specify the traversal direction

**Comment by posva** [comment]
Given a scoped slot variable, you can call `myArray.slice().reverse()` on it, although it will execute on every render. You can also use https://github.com/posva/vue-local-scope to generate local variables that are executed only once (like computed properties for scoped slots).

It's also possible to use a range, but it can become verbose:

```html
  <li v-for="i in todos.length">
      <label>
        {{ todos[todos.length - i] }}
      </label>
    </li>
```

Creating a computed property usually makes sense as the order difference usually means something and can be named.

**Comment by ybasefinal** [comment]
嗯，这几种方法都能够实现目的，我现在的做法是定义了一个方法，将数组做为参数然后输出一个反向copy（因为之前在v-for中直接为数组调用了reverse导致了死循环，又没有想到slice方法），计算属性对于反向遍历究竟是好是坏我也没太想明白，不过看起来来它和我提议的属性指定方式好像不冲突，我是刚开始接触vue，创建这个issue也是突如其来的想法，后面怎么处理，就交给作者菌了。（英语很差，就不做蹩脚翻译了【捂脸】）
