### ISSUE TITLE
在 template 模板内 新增可以直接呈现VNODE 的内置标签

### ISSUE THREAD

**Issue by xiachaoxulu** [vuejs/vue#10960]
### What problem does this feature solve?
考虑如下的场景：
$slot.default 数组有多个VNode 子元素
在 父组件内，需要在  每个VNode  下面加一行  div
template:
 .divider-wrapper
        template(v-for="(item,index) in $slots.default")
            VNodeDisplay(:content="item")
            .divider-item-border  {{ 给Vnode item 来个修饰 }}

### What does the proposed API look like?
类似这样的标签  <VNodeDisplay :content="VNode"> </VNodeDisplay>

**Comment by posva** [comment]
This advanced use case would be better off using a render function or JSX. You can also implement the component VNodeDisplay in user land
