### ISSUE TITLE
Can you embed seo solutions？

### ISSUE THREAD

**Issue by Chasen-Zhang** [vuejs/vue#10977]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs](https://github.com/vuejs)

### Steps to reproduce
Can you embed seo solutions？

### What is expected?
Can you embed seo solutions？

### What is actually happening?
Can you embed seo solutions？

---
Can you embed seo solutions？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Chasen-Zhang** [comment]
this problem is through out the structure！i think office shoud give us more friendly solutions ！not use this site[ https://ssr.vuejs.org/zh/](url)

**Comment by Justineo** [comment]
SSR is indeed the official solution. Feel free to implement your own if you do not want to use it.
