### ISSUE TITLE
blocked autofocusing on a form control error

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#10976]
### Version
2.6.11

### Reproduction link
[https://codepen.io/johnjleider/pen/oNgoYda](https://codepen.io/johnjleider/pen/oNgoYda)

### Steps to reproduce
Open devtools and refresh the pen. You will see warning messages in the console: "Blocked autofocusing on a form control in a cross-origin subframe.".

### What is expected?
No warnings

### What is actually happening?
Warnings about autofocus

---
This happens on the latest Chrome (79). The only changes I could find that referenced autofocus in Chrome were [here](https://www.chromestatus.com/feature/5654905853313024).

Since codepen is rendered in an iframe, the error message is slightly different than if you were to run it locally, but the end result is still the same.

**Comment by posva** [comment]
Unfortunately, there is nothing we can do about this, it happens before Vue is even there, even in vanilla JS: https://codepen.io/posva/pen/YzPEQQP?editors=1111
I would say the autofocus is blocked for security reasons and happens to fail in services like CodePen because they use an iframe

**Comment by posva** [comment]
Although maybe the error shouldn't happen in a template with `type="text"`. The error also appear on Safari btw

**Comment by webdevinci** [comment]
I put some code in to prevent this error on our application (so our customers would quit complaining that there was an error showing in the console)... but I am wondering, is this an actual 'error'? It doesn't seem to break anything, it simply doesn't focus on the element. Shouldn't it be a warning instead?
