### ISSUE TITLE
splice方法实现逻辑导致watch回调参数oldVal取不到正确的值

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#10972]
### Version
2.6.11

### Reproduction link
[https://codepen.io/yangdan8/pen/OJPxrYq](https://codepen.io/yangdan8/pen/OJPxrYq)

### Steps to reproduce
点击按钮
查看控制台
通过直接赋值和splice而触发watch回调得到的参数oldVal不相同

### What is expected?
针对直接赋值和splice不应该有两套API

### What is actually happening?
API不应该有二义性

---
在未来的即将发布的Vue3.0我猜这里的实现逻辑就是正确的了

**Comment by Justineo** [comment]
直接赋值和 `splice` 本来就是不同的操作，产生的副作用也不一样，输出不同的结果是符合预期的。

**Comment by yangdan8** [comment]
未来VUE3.0实现的API中splice也按这个API?

**Comment by yangdan8** [comment]
watch数组时还得考虑一定要使用直接赋值还是splice也可以,这样的API不人性化

**Comment by 9-lives** [comment]
这与 vue 无关。a、b 都是指针，b 通过直接赋值变成了新的指针。

**Comment by yangdan8** [comment]
> 这与 vue 无关。a、b 都是指针，b 通过直接赋值变成了新的指针。

Vue要做是可以做到的,没有这么设计而已
