### ISSUE TITLE
Add dynamic element

### ISSUE THREAD

**Issue by jonex2** [vuejs/vue#10989]
### What problem does this feature solve?
When you have an element similar to dynamic components in this way:
```html
<element :is="[expression evaluating to string]"></element>
```
you dont't need to use render functions for dynamic creating elements.
in this case  https://vuejs.org/v2/guide/render-function.html, it could be 
```html
<element :is="'h' + level">...
```

### What does the proposed API look like?
```html
<element :is="[expression evaluating to string]"></element>
```

**Comment by posva** [comment]
you can already do `<component :is="expression" />`

**Comment by jonex2** [comment]
I know that there exists dynamic components!
But i don't want to load a component dynamically but have the possibility to define an html element in the template dynamically (in order to avoid hard to read render functions). Please reopen the issue!

**Comment by jacekkarczmarczyk** [comment]
```
<component :is="`h` + level">
```

**Comment by jonex2** [comment]
> ```
> <component :is="`h` + level">
> ```
Yes, in this case you have to create 6 components with the name h1, h2, h3, h4, h5, h6 and thats inconvenient!

**Comment by posva** [comment]
You don't need to create 6 components, `is` allows specifying the name of an element or component, try it out before saying it doesn't work please.

Remember you can (and should) use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by jonex2** [comment]
You are right it works! The documentation doesn't mention this as far as i can see. There stands only you can use component name or component object (which has props for name and template). Also the example for render function is misleading in a way, it's not a practical use, in this case you would go better with the dynamic component.
