### ISSUE TITLE
`beforeUpdate` is not called if we explicitly state `v-slot:default`

### ISSUE THREAD

**Issue by WofWca** [vuejs/vue#10986]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/WofWca/da0v8nqc/23/](https://jsfiddle.net/WofWca/da0v8nqc/23/)

### Steps to reproduce
Click on the gray box under "With \`v-slot:default\`:"

### What is expected?
`beforeUpdate` of `WithVSlot` component is called.

### What is actually happening?
It is NOT called.

---
Under "No \`v-slot\`:" there is an identical component, except it lacks `v-slot:default`. It works as I expect it.

**Comment by despreston** [comment]
I can confirm this is broken for all named slots, regardless of the name.

**Comment by despreston** [comment]
maybe some more useful info: 

While testing the failing component in the original example, on this line, https://github.com/vuejs/vue/blob/dev/src/core/instance/lifecycle.js#L200, `vm` does not contain a `vm.$options.beforeUpdate` in the prototype chain. The working (aka second) component _does_ contain  `vm.$options.__proto__.beforeUpdate`.

I'm pretty new to the source code so I'm not exactly sure where we these components get extended. I'm guessing its happening in `/src/core/instance/init.js' but maybe someone more familiar can point me closer.

**Comment by despreston** [comment]
i looked into this a little more
none of the lifecycle hooks get triggered in that first failing component
e. g 'updated' is also not triggered

**Comment by KaelWD** [comment]
Is this actually a bug? `with-v-slot` doesn't have to re-render because scoped slots are rendered in the context of `my-component-with-slot`: https://jsfiddle.net/xg23ntc0/

Not calling these hooks is then correct following the lifecycle `beforeUpdate` -> `render` -> `updated`

**Comment by posva** [comment]
@KaelWD You are right, `update` and `beforeUpdate` not triggering makes sense as the only one updating is the inner component now (which is an improvement).
In order to know if the component content has changed we can listen to the hook: `<my-component-with-slot @hook:beforeUpdate="beforeUpdate">`

**Comment by WofWca** [comment]
Sounds confusing to me.
Check out this example: https://jsfiddle.net/WofWca/smyz0d9h/ (slightly modified reproduction example).
Here I have a component with a default scoped slot. Let's say I didn't need to use its props initially, so I omitted `v-slot`. Then I decided to use one in the template, so I put `v-slot="props"`.
I would not find intuitive that this would break my `beforeUpdate()` hook and that I also need to add `@hook:beforeUpdate="beforeUpdate"` to prevent this.

**Comment by posva** [comment]
It's because the implementation is different, like @KaelWD said, the point of https://github.com/vuejs/vue/issues/9756 is to make it consistent by making it both **lazily invoked**, which is more performant but also does not trigger the `beforeUptade`. And that aligns with how slots work in Vue 3
