### ISSUE TITLE
Incorrect rendering of slots in tables

### ISSUE THREAD

**Issue by ITrun90** [vuejs/vue#10983]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/small-waterfall-k6fit](https://codesandbox.io/s/small-waterfall-k6fit)

### Steps to reproduce
Look into the source code

### What is expected?
The slots are some ths for the tablehead of the table - so the ths should be rendered inside the thead of the table.

### What is actually happening?
The ths are rendered above the table.

---
Have a look at the following sample:
https://codesandbox.io/s/small-waterfall-k6fit

As you can see, the rendered "th"s are above the table (in source-code) - but in the template they are inside the thead of the table.

This only happens when I do it the way I did in the example mentioned above.

If I use template literals instead of single-file component it works fine.

**Comment by posva** [comment]
See https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats
There seems to be a problem with the loader you are using as it works without it: https://jsfiddle.net/5xe2mpzc/, you should open an issue there
