### ISSUE TITLE
Vue in ASP.NET Core w/ webpack: Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by Slimeyyyy** [vuejs/vue#10992]
### Version
2.6.11

### Reproduction link
[https://github.com/Slimeyyyy/M306](https://github.com/Slimeyyyy/M306)

### Steps to reproduce
1. Pull Code
2. Setup in Visual Studio (Install npm packages)
3. Run
4. Check Browser Console

### What is expected?
The component should be rendered on the index page. 

### What is actually happening?
Component cannot be rendered for unknown reasons

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
