### ISSUE TITLE
Why does 3.0 look so much like react? Have you considered the ideas of most Vue developers?

### ISSUE THREAD

**Issue by xixigege** [vuejs/vue#10999]
SB
！！！！！！！！！！！！！！！！！！

**Comment by cuongdevjs** [comment]
I think it's good :> Please see RFC know the detail more.
The feature so handy to development

**Comment by smolinari** [comment]
It looks nothing like React and it was asked for by devs for better code reusability and better TypeScript support. And, it's progressive, meaning, if you don't want to use it, you don't have to.

Scott

**Comment by cuongdevjs** [comment]
yeah, as Even say, you can continue using v2 if you like, it's not forced. v3 complete compatible with v2, v2 not deprecated
