### ISSUE TITLE
worker  Using worker in Vue and Typescript, Unable to use  web worker ???

### ISSUE THREAD

**Issue by wangzhiyao66** [vuejs/vue#10991]
### Version
2.6.10

### Reproduction link
[https://github.com/wangzhiyao66/my-worker.git](https://github.com/wangzhiyao66/my-worker.git)

### Steps to reproduce
An error occurred while using the following code in the script

let worker =  new Worker('../../static/webworker.js');

### What is expected?
Normal use web worker 

### What is actually happening?
Uncaught SyntaxError: Unexpected token '<'
Cause unexpected end

---
I need your help to solve this problem. Thank you very much

**Comment by LinusBorg** [comment]
The path that you pass to the Worker() function should be the absolute path to the file on the server, not a local path in you src folder.

Because of the wrong path, the HTTP server can't find the file and replies with a 404 error page - which starts with "`<`" (as in `<html>`)

Problem is not related to Vue.

**Comment by wangzhiyao66** [comment]
Thank you for your letter. I'm trying your way. Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Thorsten Lünborg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上6:29
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"简约范"<1217167460@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue] worker  Using worker in Vue and Typescript, Unable to use  web worker ??? (#10991)




The path that you pass to the Worker() function should be the absolute path to the file on the server, not a local path in you src folder.
 
Because of the wrong path, the HTTP server can't find the file and replies with a 404 error page - which starts with "<" (as in <html&gt;)
 
Problem is not related to Vue.

**Comment by wangzhiyao66** [comment]
Why can angular 2.0 and above use local files instead of server scripts??
The web worker document in HTML5 doesn't say that it can't be a local script, and angular can use the local script to create the worker process ？？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Thorsten Lünborg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上6:29
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"简约范"<1217167460@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue] worker  Using worker in Vue and Typescript, Unable to use  web worker ??? (#10991)




The path that you pass to the Worker() function should be the absolute path to the file on the server, not a local path in you src folder.
 
Because of the wrong path, the HTTP server can't find the file and replies with a 404 error page - which starts with "<" (as in <html&gt;)
 
Problem is not related to Vue.

**Comment by LinusBorg** [comment]
You can create workers "inline", without a script loaded from the server. But that is something for which you don't need specific support in your frontend framework of choice.

Angular, being a big framework incorporating lots of stuff like its own http fetchsolution etc, may have this built-in - Vue doesn't.

if you have a system set up with Vue CLI, you might be able to achieve your desired result by adding this loader: 

https://github.com/webpack-contrib/worker-loader

or a similar solution.

**Comment by wangzhiyao66** [comment]
Thank you very much for your help. The problem has been solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Thorsten Lünborg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上11:06
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"简约范"<1217167460@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题： &nbsp;Re：[vuejs / vue] worker在Vue和Typescript中使用worker，无法使用Web worker ??? （＃10991）




您可以“内联”创建工作程序，而无需从服务器加载脚本。但这就是您不需要的所选前端框架中的特定支持。
 
Angular是一个集成了很多东西（如自己的http fetchsolution等）的大型框架，可能具有此内置功能-Vue没有。
 
如果您使用Vue CLI设置了系统，则可以通过添加以下加载程序来实现所需的结果：
 
https://github.com/webpack-contrib/worker-loader
 
或类似的解决方案。
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by NadaAzzzam** [comment]
i tried to use webpack-loader and loaded the file but also added webpack code and minified my code  any suggestion to load my code only without doing anything else in my code ?

**Comment by lsdsjy** [comment]
@NadaAzzzam You can use file-loader which will give you an absolute URL of the file you a importing, and create a Worker from it.
