### ISSUE TITLE
尽快完成vue 3.0正式版发布（Complete the official release of Vue 3.0 as soon as possible）

### ISSUE THREAD

**Issue by 120011676** [vuejs/vue#11016]
### What problem does this feature solve?
我想使用vue3.0正式版了
I want to use the official version of Vue 3.0

### What does the proposed API look like?
vue3.0正式版现在就可以用
The official version of vue3.0 is now available

**Comment by Justineo** [comment]
Feel free to contribute to vue-next/vue-loader/vue-cli/eslint-plugin-vue or any project in the Vue ecosystem to help it release sooner.
