### ISSUE TITLE
vue实例data数据中对象属性里未定义的字段在模板里使用并改变，会被监听到，但是js使用就监听不到。

### ISSUE THREAD

**Issue by Jason2048** [vuejs/vue#11013]
### Version
2.6.11

### Reproduction link
[https://codepen.io/Jason6385/pen/xxbaVJB?editors=1111](https://codepen.io/Jason6385/pen/xxbaVJB?editors=1111)

### Steps to reproduce
1、进入页面，先在输入框里输入内容，输入框下面会动态更新值，console里也会打印监听内容，再点击按钮改变变量值也能监听到。
2、进入页面，先点击按钮改变同一个变量，监听不到改变，再在输入框里输入内容也监听不到。
3、将created中的注释代码打开，进入页面重复1和2操作，变量改变都监听不到。

### What is expected?
第1步应该也是监听不到

### What is actually happening?
第1步能监听到

**Comment by posva** [comment]
Things are working fine in this case. When adding properties to an object, you must use `Vue.set()` or `$this.set`

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by MISSQTW** [comment]
@Jason2048 
https://cn.vuejs.org/v2/guide/reactivity.html#%E6%A3%80%E6%B5%8B%E5%8F%98%E5%8C%96%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
