### ISSUE TITLE
Vue transition-group not working on single  element

### ISSUE THREAD

**Issue by Limuyang1013** [vuejs/vue#11018]
### Version
2.3.4

### Reproduction link
[https://forum.vuejs.org/t/vue-transition-group-not-working-on-1-element/1086](https://forum.vuejs.org/t/vue-transition-group-not-working-on-1-element/1086)

### Steps to reproduce
1. use transition-group to wrapper a list
2. add enter-active animation to this transition-group
3. just add one element to this list
4.then add another element to this list

### What is expected?
if there is only one element in this list , the enter-active animation is not working，if there are two or more element was added in the list the enter-active will worked

### What is actually happening?
the animation work well whenever the list is changed

---
i search the same question here https://forum.vuejs.org/t/vue-transition-group-not-working-on-1-element/1086   i want to know is the transition-group component designed with flaw or just i'm using it in a wrong way?

**Comment by posva** [comment]
Please provide a reproduction when reporting a bug, otherwise keep the question to the forum and the chat
