### ISSUE TITLE
Basic renderer not return error

### ISSUE THREAD

**Issue by uinit** [vuejs/vue#11011]
### Version
2.6.11

### Steps to reproduce
I use PHP v8js and basic renderer to ssr.
Example:
```

var vm = new Vue({
  template: `<div>{{ msg }}</div>`,
  data: {
    msg: 'hello',
  },
 serverPrefetch(){
    throw Error('Test Error');
 }
})

// предоставляется `vue-server-renderer/basic.js`
renderVueComponentToString(vm, (err, res) => {
    if (err) {
           print(err);
           return;
        }

        data.r();

        print(res);
})
```

### What is expected?
err = 'Test Error'

### What is actually happening?
err variable is null

**Comment by posva** [comment]
make the `serverPrefetch` function async so it returns a Promise

**Comment by uinit** [comment]
The problem is not at this moment. Even if you use Promis, the problem is reproduced.
I see, [source code](https://github.com/vuejs/vue/blob/85548310f19975745c83ac173f700f8b2f1e8e3e/packages/vue-server-renderer/basic.js#L8725), and if code has error, the error is not processed. But anonymus function in four argument is called, and if check her arguments, first will contain an error. This anonimus function send to waitForServerPrefetch function in [this line](https://github.com/vuejs/vue/blob/85548310f19975745c83ac173f700f8b2f1e8e3e/packages/vue-server-renderer/basic.js#L8460) as second parameter. But inside waitForServerPrefetch, this callback
called inside catch block.

And all this is strange.
