### ISSUE TITLE
Any Roadmap for 2020?

### ISSUE THREAD

**Issue by jiraguha** [vuejs/vue#11012]
### What problem does this feature solve?
Hello Vue ❤️,

I have 2 questions linked to your [raodmap](https://github.com/vuejs/vue/projects/6):

1. In the current roadmap ending in Q1-2020 is quite hard to see which milestone was completed. Is it possible to have somehow something like a level of completion?
2. More important: what is the roadmap for 2020? 

Currently, on Vue 2.x (with vue-router, vuex,...), I would want to plan a migration to Vue 3.x? Responses to those would help me a lot 😅!

Thanks,
JP

### What does the proposed API look like?
.

**Comment by tylik1** [comment]
I'm also interested. Seems that active development paused for a while.

**Comment by sirlancelot** [comment]
The second Alpha for Vue 3.x just came out a couple of days. On the official roadmap, it shows that Vue 3.x is planned for Q1 of this year (2020). Look around for it towards the end of March.

**Comment by yyx990803** [comment]
We are still focusing on 3.0 related work (there's still a lot left!). We are aiming for a feature-complete release by end of Q1 2020, but we expect a lot of 3.0 related work to extend into Q2 (documentation, migration tools and compatibility builds).

We will update plans for Q3 and Q4 when we have a better idea of the progress at the end of Q1.
