### ISSUE TITLE
Insert component after root instance initialized. php + ajax

### ISSUE THREAD

**Issue by jack-fdrv** [vuejs/vue#11028]
I have root instance with method "loadForm" which loads html of component and javascript with component object (which contains all methods, watched and filters)

If I just try append html 
`$('body').append(response);`
in to the DOM after ajax, it do not init vue and all braces print like a braces {{ someVar }}. 

I know that from official docs
> 
Remember that global registration must take place before the root Vue instance is created (with new Vue). Here’s an example of this pattern in a real project context.

So, some how I need to use local component dynamically. 

Also I would like to use html as html, and do not put it like a string in js variable.
It is not handy to write html like a string in js. Also as I use php i will need to use ob_start which cost a lot of server resources. 

So how to implement with php on backend dynamic components which I load on button click and mount them after ajax finish?

**Comment by raphjutras** [comment]
@jack-fdrv Did you manage to do it ? I would be interested to see how you did. Trying to achieve the same but can't figure out how..

**Comment by jack-fdrv** [comment]
@raphjutras Yes.

Some html prints here

```
<div class="sub">
	<span v-if="singleSurvey" v-html="singleSurveyJson.subTitle"></span>
	<span v-else>
		{{sub_title}}
	</span>
</div>
```
then we put it in variable $html

```
$html = ob_get_contents();
ob_end_clean();
ob_start();
```
then our vue component js goes

var survey_component = {
		props: [],
		data() {
			return {
				conf: {
				},
                          },
                  },
                  methods: {
			setupSurvey: function() {}
                  }
},
again put it in php variable $js

$js = ob_get_contents();
ob_end_clean();	
echo build_view_component($html, $js);

function build_view_component($html, $js) {
        $html = addcslashes(preg_replace('/(\v|\s)+/', ' ', $html), "'");
        $js = str_replace('<script>', '', $js);
        $js = str_replace('}</script>', ", template: '$html'}", $js);           
        return minify_js($js);
        exit;
}

function minify_js($input) {
        if (trim($input) === "") return $input;
        return preg_replace(
            array(
                '#\s*("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\')\s*|\s*\/\*(?!\!|@cc_on)(?>[\s\S]*?\*\/)\s*|\s*(?<![\:\=])\/\/.*(?=[\n\r]|$)|^\s*|\s*$#',
                '#("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\'|\/\*(?>.*?\*\/)|\/(?!\/)[^\n\r]*?\/(?=[\s.,;]|[gimuy]|$))|\s*([!%&*\(\)\-=+\[\]\{\}|;:,.<>?\/])\s*#s',
                '#;+\}#',
                '#([\{,])([\'])(\d+|[a-z_][a-z0-9_]*)\2(?=\:)#i',
                '#([a-z0-9_\)\]])\[([\'"])([a-z_][a-z0-9_]*)\2\]#i'
            ),
            array(
                '$1',
                '$1$2',
                '}',
                '$1$3',
                '$1.$3'
            ),
            $input
        );
    }

this is a single php file, which i then requests with ajax

```
var vueApp = new Vue({
	el: '#page',
	data: {},
    },
methods: {
		async mrj_prepare_survey() {
			var app = this;
			return new Promise(resolve => {						
				$.getScript('url to the php file with vue component'), function() {					
					app.comp.survey.html = survey_component;
					resolve();						
				});
			});
		},
		async mrj_run_survey(type) {	
			await this.mrj_prepare_survey();
			return 1;
		},
	}
});
```
