### ISSUE TITLE
Change prop value of parent, make children remount

### ISSUE THREAD

**Issue by MrJmpl3** [vuejs/vue#11022]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vuetify-2-e5hxl](https://codesandbox.io/s/vuetify-2-e5hxl)

### Steps to reproduce
Click in the button and see the console message: Child mount again ..

### What is expected?
The children don't remount

### What is actually happening?
The children was remounted

---
If you put a div (with nothing of classes or props) together to the children component, the children don't remounted

But if you but some classes in the div, the children start to remount again

```js
<v-card :loading="loading">
   <div />
    <v-col>
      <v-btn @click="loading = !loading">Click here for make the bug of remount</v-btn>
      <children />
    </v-col>
  </v-card>
```

PD: I ask in Vuetify Discord and them say is a problem of Vue.

https://images-ext-1.discordapp.net/external/GqwNyGU1hsSqIR-BmRBCVnO4CQHvC1pLnmAx4pjP630/%3Fwidth%3D525%26height%3D676/https/media.discordapp.net/attachments/340215499398840331/667616374566289444/unknown.png

**Comment by posva** [comment]
Please provide a boiled down repro when reporting a bug: no Vuetify, no web workers, no router no vuex (unless those two are necessary) to make sure it comes from Vue. Please, ping me when you have one or open a new issue!

**Comment by MrJmpl3** [comment]
@posva https://codesandbox.io/s/dark-sky-usrgj

**Comment by posva** [comment]
This is because every time the first child is removed or added, causing the whole list of children to update. See https://github.com/vuejs/vue/issues/4362

**Comment by MrJmpl3** [comment]
> This is because every time the first child is removed or added, causing the whole list of children to update. See #4362

Ok, but why don't remount when add another div in the children?
