### ISSUE TITLE
Http-server for E2E bug on Windows 10

### ISSUE THREAD

**Issue by Bixbite-Gem** [vuejs/vue#11027]
### Version
2.6.11

### Reproduction link
[https://github.com/Bixbite-Gem/vue-tests-bug-windows](https://github.com/Bixbite-Gem/vue-tests-bug-windows)

### Steps to reproduce
1. Copy runner.js from test repository to test/e2e/runner.js in Vue project
2. Execute node test/e2e/runner.js on environment with Windows 10 
3. Open http://localhost:8080/examples/svg/ in browser

### What is expected?
http://localhost:8080/examples/svg/index.html should be opened

### What is actually happening?
Error with code ERR_TOO_MANY_REDIRECTS happens
Url in browser: http://localhost:8080/examples/svg////////////////////

---
I've tried to run all tests on my local machine and noted that some tests fail without any changes in code base

Reason: https://github.com/http-party/http-server/issues/525

runner.js is a copy of test/e2e/runner.js where args processing is commented to prevent process.exit

runner.cmd contains command to run http-server

test-e2e.cmd contains command to run e2e tests only

**Comment by posva** [comment]
e2e tests should be running correctly under windows. I don't see how running your specific file that uses none of vue code is related to Vue.
If you find e2e tests not running correctly in our repository, a PR is welcome to fix it!
