### ISSUE TITLE
Insert component after root instance initialized. php + ajax

### ISSUE THREAD

**Issue by jack-fdrv** [vuejs/vue#11029]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/fdrv/kecuz5hf/5/](https://jsfiddle.net/fdrv/kecuz5hf/5/)

### Steps to reproduce
Hi there! I am new in the vue world. And I decide to move in my wordPress project to vue form jQuery step by step.

I have root instance with method "loadForm" which loads html of component and javascript with component object (which contains all methods, watched and filters)

If I just try append html
$('body').append(response);
in to the DOM after ajax, it do not init vue and all braces print like a braces {{ someVar }}.

I know that from official docs

Remember that global registration must take place before the root Vue instance is created (with new Vue). Here’s an example of this pattern in a real project context.

So, some how I need to use local component dynamically.

Also I would like to use html as html, and do not put it like a string in js variable.
It is not handy to write html like a string in js. Also as I use php i will need to use ob_start which cost a lot of server resources.

So how to implement with php on backend dynamic components which I load on button click and mount them after ajax finish?

### What is expected?
After ajax call insert html to dom.
Mount new component to the already initialized root instance.

### What is actually happening?
Doesnt work at all.
https://src.fdrv.guru/200118185805.png

**Comment by LinusBorg** [comment]
You can't insert a piece of template and script into the DOM like that, this is simply not how Vue works at all.

This is not a bug, it's a usage question for which we ask you to us forum.vuejs.org or chat.vuejs.org to ask for guidance.

But a word of warning/advice: loading template and script from the server like that and turning it into an actual component isn't something recommended and would require some hacking around to get to work.

So when asking for help in these places mentioned, I recommend to describe your specific need (why do you want to load a component this way? what problem does this solve for you) and how your system is set up - that enables people to come up with other ideas.

**Comment by jack-fdrv** [comment]
Thanks Linus.

> I recommend to describe your specific need
Okay.

> why do you want to load a component this way?
I have a large form, with a lot of html elements and also vue component has a lot of methods, which I dont want to load each time. As you know google has advice to limit html tags to 1500 or less. That why I need to load components dynamic and inject in to the root instance.

> what problem does this solve for you
Speed optimization. Better SEO. Better project structure.

> how your system is set up
Like I said, this is a php word press website.

[Here](https://jsfiddle.net/fdrv/exa96ogp/34/) I did some working example. But I dont know any other way to do it.

**Comment by jack-fdrv** [comment]
@LinusBorg I have  created new topic on forum [here](https://forum.vuejs.org/t/insert-vue-component-dynamically-after-ajax-call-when-user-click-button-after-root-instance-initialization/85189).
Could you please check and help me Linus?

**Comment by jack-fdrv** [comment]
@LinusBorg Like you see ur forum doesnt work at all...
After 3 days no answers.
