### ISSUE TITLE
Vue error handler not capturing async watcher handler

### ISSUE THREAD

**Issue by caiquecastro** [vuejs/vue#11036]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/shengslogar/f4kc5vq2/32/](https://jsfiddle.net/shengslogar/f4kc5vq2/32/)

### Steps to reproduce
Create a watcher with an async handler. Make it throw an error.

### What is expected?
It's captured by Vue error handler

### What is actually happening?
Not being captured by vue error handler

---
Shows an uncaught promise error

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/10009
