### ISSUE TITLE
Changing value of main Vue variable and writing it to HTML causes sending all props values into all components having props

### ISSUE THREAD

**Issue by step135** [vuejs/vue#11033]
### Version
2.6.11

### Reproduction link
[https://stackoverflow.com/questions/59787025/changing-value-of-outer-variable-used-in-props-after-emitted-listener-from-compo/59789074](https://stackoverflow.com/questions/59787025/changing-value-of-outer-variable-used-in-props-after-emitted-listener-from-compo/59789074)

### Steps to reproduce
Vue has data variables a and b. We place {{ a }} to the main code. The value of variable b is sent by props to component and matched to variable c. With the time we are changing that value of variable c inside the component. In one moment we decide to change value of a and having {{ a }} or {{ '',a }} or {{ '',console.log(a) }} in main code results "no-sense" resending value of variable b, so inside the component, related variable c is "forgetting" current state and is reset to initial state by invoked props.

### What is expected?
By props should be send only values of affected variables. In previous case, it shouldn't be invoke at all.

### What is actually happening?
Props reset all related template variables.

---
It looks like serious problem caused by bad architecture of Vue.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you are changing the value of a prop inside a component, you will see a warning (unless you are using the production mode) explaining what is going on
