### ISSUE TITLE
vue  单页面下如果使用了浏览器定位 则页面的  被动混合内容访问不了 

### ISSUE THREAD

**Issue by djkdeveloper** [vuejs/vue#11034]
### Version
2.9.4

### Reproduction link
[https://springboot.lecshop.cn/mobile/#/nearstorelist](https://springboot.lecshop.cn/mobile/#/nearstorelist)

### Steps to reproduce
在手机端打开这个地址https://springboot.lecshop.cn/mobile/#/nearstorelist你会发现弹出定位授权后 图片不展示 因为图片使用的是http的 定位发现被浏览器阻断了 但是你从https://springboot.lecshop.cn/mobile 首页进去然后点击附近门店 图片是可以展示的，没有被浏览器阻断。
我在以前不是vue的版本 jsp的版本中不是单页面的  是可以的，就是定位弹出授权后浏览器不会阻断被动混合内容

### What is expected?
https://springboot.lecshop.cn/mobile/#/nearstorelist 直接进去图片可以展示 不被浏览器阻断

### What is actually happening?
图片展示不了 被浏览器阻断了

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
When reporting a bug, please follow the instructions at https://new-issue.vuejs.org
