### ISSUE TITLE
Custom directives continually re-ran on text input

### ISSUE THREAD

**Issue by mikemand** [vuejs/vue#11037]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/inspiring-water-9jmdm](https://codesandbox.io/s/inspiring-water-9jmdm)

### Steps to reproduce
On the codesandbox, open the console then type in the text field.

### What is expected?
Custom directives should not be affected by text input.

### What is actually happening?
Every character typed is causing the directive to run again and in the wrong circumstances causes the entire page to freeze (and text does not appear in the text box for upwards of a second).

---
I have a custom directive that checks if my navigation links (in an admin panel sidebar) are to the current page or not. There could be upwards of 50 links if a user has all the permissions available, so input lag is huge. I would not have expected the directive to get re-run after the page has loaded. Maybe a directive is not the correct option for my use case? It seemed like it at the time, but now that we have this input lag problem I have disabled the directive. Users can suffer not "seeing" what page they are on (in the sidebar) as a tradeoff for speedy text input.

**Comment by posva** [comment]
Directives have different hooks, you are using both bind and update (https://vuejs.org/v2/guide/custom-directive.html#Function-Shorthand). `update` is in your case triggering the directive, but this is expected as described in the documentation

**Comment by mikemand** [comment]
Hi @posva,

Thank you for the information! It looks like what I really needed to pay attention to is right at the top of the docs:

```js
// Register a global custom directive called `v-focus`
Vue.directive('focus', {
  // When the bound element is inserted into the DOM...
  inserted: function (el) {
    // Focus the element
    el.focus()
  }
})
```

I skipped that section (or it wasn't there a year ago when I first created my directive) it seems. So I should be loading my directive like so:

```js
Vue.directive('test', {
    inserted: test,
}
```

Thank you!
