### ISSUE TITLE
keepalived 实现router-view缓存，当缓存的组件调用$destroy后再次打开，缓存无效了

### ISSUE THREAD

**Issue by zhangbo0921** [vuejs/vue#11038]
### Version
2.6.10

### Reproduction link
[https://4ic5v.csb.app/](https://4ic5v.csb.app/)

### Steps to reproduce
1.路由配置：
{
        path: 'order/editOrder',
        name: 'editOrder',
        meta: {
          keepAlive: true
        },
        component: () => import(/* webpackChunkName: "addorder" */"@/views/order/AddOrder")
}
2.keep-alive写法
<keep-alive >
            <router-view v-if="$route.meta.keepAlive" :key="$route.fullPath"></router-view>
</keep-alive>
<router-view v-if="!$route.meta.keepAlive" :key="$route.fullPath"></router-view>
3.缓存页面代码
beforeRouteLeave (to, from, next) {
    if(from.meta.keepAlive){
      if(this.$parent){
          this.$parent.tabComInstance[from.fullPath]=this ;
      }
    }
    next();
  }
4.主菜单核心代码
//销毁缓存的数据
let inst = this.tabComInstance[cacheKey]
console.log(inst);
inst.$destroy();
delete this.tabComInstance[cacheKeys];

### What is expected?
期望$destroy()不要影响缓存

### What is actually happening?
无法缓存了

---
补充1：业务场景
左侧菜单打开A页面，A页面会在内容显示去的tabs上添加一个tab，这个tab可以关闭，类似现在浏览器打开多标签一样，当在关闭tab时，希望可以销毁A页面的组件实例；在tab之间切换时，保留缓存页面。

补充2：需求
按照官网的说法，使用include 和exclude 可以解决，但是如果刚好这个组件是一个公共的页面呢？（比如：编辑工单，可以打开好多各工单进行编辑）而且可以打开很多标签，这个时候，如果单纯用name判断，就会让所有的这个name的标签失去缓存，这个也不是我想要的。希望能更精确到某个组件的ID或者唯一标识（比如：fullurl），精确处理。

**Comment by posva** [comment]
1. This is vue repository, not vue router
2. Make sure to check existing issues about keep-alive: https://github.com/vuejs/vue-router/issues?q=is%3Aopen+is%3Aissue+label%3Akeep-alive
3. Always provide a reproduction when reporting a bug so we can check it, it's really important for us
4. Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
