### ISSUE TITLE
希望能够通过VueRouter对象，获取当前缓存的页面实例，并可以销毁它，而且不影响下次缓存，目前$destroy调用后，无法缓存，我认为是bug

### ISSUE THREAD

**Issue by zhangbo0921** [vuejs/vue#11039]
### What problem does this feature solve?
keepalived 实现router-view缓存，当缓存的组件调用$destroy后再次打开，页面将无法再继续缓存了

### What does the proposed API look like?
this.$router.$caches获取被router缓存的页面实例，并且返回实例的信息和路由信息

**Comment by posva** [comment]
Same comment as https://github.com/vuejs/vue/issues/11038
