### ISSUE TITLE
vue and webpack compress

### ISSUE THREAD

**Issue by borodadada** [vuejs/vue#11043]
### What problem does this feature solve?
Hello. Vue + ssr + webpack. Why if i use option
```
deleteOriginalAssets: true,
```
site not working

webpack.base.js
```
plugins: isProd ? [ 
        new CompressionPlugin(
            { 
                filename: '[path].gz[query]',
                algorithm: 'gzip',
                test: /\.(js)$/,
                threshold: 0,
                deleteOriginalAssets: true,
            }
        ),
        new VueLoaderPlugin()
    ] : [ 
        new VueLoaderPlugin(), 
    ]
```
images

https://i.ibb.co/HHNLkvB/Snipaste.png
https://i.ibb.co/r30pbWF/Snipaste2.png

i dont understand , site can work only with gz files?

if
```
deleteOriginalAssets: false,
```
images

https://i.ibb.co/hK1JPWQ/Snipaste3.png
https://i.ibb.co/3hjZP3N/Snipaste4.png

### What does the proposed API look like?
vue ssr   webpack

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
