### ISSUE TITLE
Can’t make vue-axios or vue-request to work with https self signed certificate

### ISSUE THREAD

**Issue by xGuIInE** [vuejs/vue#11044]
I want to send a POST request from a VUE PWA web app to an esp32 iot device with a https server runing. I use a custom https agent:
```js
const agent = new https.Agent({
          rejectUnauthorized: false,
        });
this.axios.get('https://192.168.4.1/hello', {httpsAgent: agent}).then(() => {
          ...
        }).catch(...)
```

I´m having this problem since 6 months ago... I have tried 100000 different solutions and impossible... 
When someone ask something like me, no answers always... (ex: https://forum.vuejs.org/t/cant-make-vue-axios-or-vue-request-to-work-with-https-self-signed-certificate/17851)

Please help... I´m desesperated with this... my product is ready waiting for this fucking shit...

**Environment:**
 - Axios Version = 0.19.1
 - OS: Tried in IOS, Android, Windows, Mac...
 - Browser Chrome, Firefox, Safari

**Comment by wiiikiii** [comment]
https://stackoverflow.com/questions/47630791/ssl-certificate-disable-verification-in-axios-and-react

maybe this answers the question?
