### ISSUE TITLE
Can´t make POST request from vue-axios to ESP32 https server with self signed certificate

### ISSUE THREAD

**Issue by xGuIInE** [vuejs/vue#11045]
### Version
2.6.10

### Reproduction link
[https://github.com/xGuIInE/vue-post-test](https://github.com/xGuIInE/vue-post-test)

### Steps to reproduce
You only need a running https server with self signed certificates working, and use the vue app example to try to send POST request to "https://192.168.4.1/hello"

### What is expected?
The server should response "hello"

### What is actually happening?
Vue or the browser is blocking the request. In the browser says "BLOCKED BY CORS", but thats not true, if you enter manually "https://192.168.4.1/hello" and accept the insecure certificate, the request will done succesfully. 
In the server side says "SSL acept failed"

---
I´m using this library in the ESP32: https://github.com/fhessel/esp32_https_server
Please help!! I´m trying this silly thing for almost 6 months... I have tried everything what i found on the internet... 
Here someone ask the same question in 2017 and no response... (https://forum.vuejs.org/t/cant-make-vue-axios-or-vue-request-to-work-with-https-self-signed-certificate/17851)

**Comment by LinusBorg** [comment]
This is not direcly related to Vue.js core -it's certainly not a bug in Vue core,  therefore not a valid issue topic.

If you need help, try forum.vuejs.org or chat.vuejs.org
