### ISSUE TITLE
Blackboxing my own code because it comes from node_modules

### ISSUE THREAD

**Issue by amsterdamharu** [vuejs/vue#11041]
### Version
2.6.10

### Reproduction link
[http://notneeded.cn](http://notneeded.cn)

### Steps to reproduce
Any vue file comes from `webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/productoverview/VueComponent.vue?vue&type=script&lang=js&` 

Problem is that node_modules is the first thing developers will blackbox so now you can't debug your own code anymore.

### What is expected?
Do not serve own code from node_modules

### What is actually happening?
Own code comes from node_modules

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only and they must be directly related to Vue. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
