### ISSUE TITLE
Props with values that are the same as the prop name are cast to true when the prop type is [Boolean, String]

### ISSUE THREAD

**Issue by justin-schroeder** [vuejs/vue#11058]
### Version
2.6.11

### Reproduction link
[https://codepen.io/justin-schroeder/pen/wvBbKpO?editors=1010](https://codepen.io/justin-schroeder/pen/wvBbKpO?editors=1010)

### Steps to reproduce
If the value of a prop is set to the same name as the prop, and the `type` is [Boolean, String] it gets cast to `true`.

```vue
<my-component
  name="name"
/>
```

```vue
// mycomponent
{
 props: {
   name: {
     type: [Boolean, String]
   }
 }
}
```

In the above `my-component` the value of the the name prop will be Boolean `true` if the value is String "name"

### What is expected?
The value would be String "name"

### What is actually happening?
The value is cast to Boolean `true`

---
I'm not confident this is a bug as there is a comment describing this condition in core (https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L36). The "fix" once you know what is going on is quite simple, change:
```
[Boolean, String]
to
[String, Boolean]
```
However, stumbling upon this condition was quite unexpected in "user land".  If this is indeed a feature, perhaps it’s just a matter of documenting it?

**Comment by jaireina** [comment]
As you said, this is not a bug. If you expect a Boolean value in a property, you can pass anything and javascript will determine if it's falsey or truthy. I agree the documentation could be clearer regarding this.

**Comment by sirlancelot** [comment]
It is definitely NOT a bug, but strangely prop type order validation isn't described in the documentation here: https://vuejs.org/v2/guide/components-props.html#Prop-Validation

**Comment by posva** [comment]
This is intentional. One of the use cases was pug transforming boolean attributes into `boolean-attr="boolean-attr"`. It is possible that some browsers also do this.
It is indeed worth mentioning in the docs, at least in the API section. Maybe there is some discussion already started at vuejs/vuejs.org, if not, it would be nice if you started one over there or upvoted any existant one to give it more visibility

**Comment by justin-schroeder** [comment]
Thanks for the context @posva. Questions directly related to this:

1. Will this API remain in tact for Vue3 as well? 
2. Also would there be adverse affects if this behavior only happened if the prop type was `Boolean` and _only_ `Boolean`? That makes total sense. The confusing thing, as the [reproduction demo showed](https://codepen.io/justin-schroeder/pen/wvBbKpO?editors=1010), is you can end up with a hole in the data flow without understanding this pretty intricate internal mechanism, just because of the order of the type definition.
3. Are there other circumstances where the type order for prop validation matters? I'd be happy to help with any documentation concerns in that regard.

**Comment by sirlancelot** [comment]
I wonder if it would make more sense to do Boolean transformation ONLY when the type is strictly Boolean (not an array of types including Boolean). Technically, if the type is an array, I would expect the validation to pass if the type matched any type in the array therefore no transformation should take place.
