### ISSUE TITLE
Watch not picking up on state changes

### ISSUE THREAD

**Issue by google-mac** [vuejs/vue#11057]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-watcher-issue-z3zp0](https://codesandbox.io/s/vue-watcher-issue-z3zp0)

### Steps to reproduce
Create a local state variable "foobar" (boolean). Create another boolean called "changed". Bind a watcher to the first to detect when it changes to true, setting the "changed" state to true. In a function, set "foobar" to true and then to false. Bind this function to a button. (CodeSandbox link has all this set up.)

### What is expected?
The watcher should run when "foobar" is set to true, which would then set "changed" to true.

### What is actually happening?
Changed does not get set to true. The watcher is not called at all when the value is set to true.

---
If you remove the line that sets "foobar" back to false, the watcher on "foobar" is triggered and "changed" is set to true, which is weird behavior. Even weirder is that if the function is async and an await statement is placed, then things work as expected. The await can go anywhere (as shown in the CodeSandbox example).

We ran into this because we had to have a "changed" flag to avoid a race condition. We are using Google Maps autocomplete, which was binding to an input element, but our event listeners still needed to be on that input as well. By having the flag, we make sure to only run the proper functions once and in the correct order. We are setting the flag to true immediately and then setting it back to false after some synchronous data manipulation, but when the value is set back to false, the first switch to true is not picked up. Weird. Then somehow we tried using await this.$nextTick(), which solved it but we don't think that should be necessary.

**Comment by posva** [comment]
This is intended: Vue throttles the watchers (and computed) with `Vue.nextTick` for perf reasons.
You will have to call a method instead or using a different way. Waiting one tick is also a possibility depending on the scenario

Note: Steps to reproduce are supposed to be the actions to do on the reproduction in order to reproduce the bug. Describing how to set it up while you are already providing the code setup would be redundant 😄

**Comment by google-mac** [comment]
@posva  So the throttling is a feature (didn't know that). Isn't that against the paradigm of a watcher though? I could see most Vue developers being confused with this behavior, though I do realize it may not happen often.

Regarding the steps to reproduce, I was confused at having to spell it out again. 😄 My sandbox was straightforward enough, I hope.

**Comment by google-mac** [comment]
@posva Also, you mentioned 
> You will have to call a method instead

I tried wrapping the state changes in their own methods, but it did not work. Can you describe what you mean?

See my updated [CodeSandbox](https://codesandbox.io/s/vue-watcher-issue-z3zp0) for the 4th example.
