### ISSUE TITLE
slot template with scope value not working

### ISSUE THREAD

**Issue by malacca** [vuejs/vue#11063]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/L514wjxn/](https://jsfiddle.net/L514wjxn/)

### Steps to reproduce
@see reproduction link

### What is expected?
show slot

### What is actually happening?
not working

---
even `el-input` prepend slot not provide scope value, it should working .

ex: if i create a middle component, i don't know if sub component provide scope value

**Comment by Justineo** [comment]
Please provide a boiled down reproduction, which means without 3rd party components like Element. Or you can report the problem to Element itself.

**Comment by malacca** [comment]
@Justineo   it's so easy to reproduction

https://jsfiddle.net/7kfarwus/1/

**Comment by Justineo** [comment]
`$slots` does not include scoped slots. Please use `$scopedSlots` instead.

BTW notice that since 2.6 we also expose all normal slots in `$scopedSlots`.
