### ISSUE TITLE
Leak memory

### ISSUE THREAD

**Issue by polPintero** [vuejs/vue#11061]
### Version
2.6.11

### Reproduction link
[https://github.com/polPintero/vue-leak-memory](https://github.com/polPintero/vue-leak-memory)

### Steps to reproduce
run code: node index.js

### What is expected?
No memory leak expected

### What is actually happening?
leak memory

Chrome v.79.0.3945.130 

---

I have an application. At the set intervals, according to WebSoket, I get updated data from the server and put it in the store. I noticed a memory leak with the arrival of each new piece of data. The repository contains a demo code.

Note: there is a leak only if the index.html file is opened through the web server. If you open the index.html file in a direct path in the address bar of the browser, then there is no memory leak

**Comment by posva** [comment]
After upgrading vuex to its latest version, I tested locally and there was no leak

![Screen Shot 2020-01-29 at 16 31 01](https://user-images.githubusercontent.com/664177/73370590-bff0d780-42b4-11ea-891e-e8d45432a9b9.png)

![Screen Shot 2020-01-29 at 16 29 18](https://user-images.githubusercontent.com/664177/73370513-a2237280-42b4-11ea-82bc-eb92d95b9876.png)

> Note: there is a leak only if the index.html file is opened through the web server. If you open the index.html file in a direct path in the address bar of the browser, then there is no memory leak

If that's the case, you might have a chrome extension that is leaking: by default extensions are deactivated on `file:///` protocol. If not, you should probably report it to the Chromium team
