### ISSUE TITLE
Use emit to modify the data of the parent component, but other components that reference this data are not updated

### ISSUE THREAD

**Issue by zshuangyan** [vuejs/vue#11069]
### Version
2.6.11

### Reproduction link
[https://github.com/zshuangyan/vue-learning/tree/master/pomodoro](https://github.com/zshuangyan/vue-learning/tree/master/pomodoro)

#### parent component: 
src/App.vue

#### shared data
App.vue's state

#### child component of AppVue:
src/component/ControlsComponent.vue
src/component/StateTitleComponent.vue

### Steps to reproduce
- execute `npm install` and `npm run dev`, your webrowser will open a page like following:
![image](https://user-images.githubusercontent.com/3966367/73619943-93e5a580-466a-11ea-8414-84dbe5e472a6.png)
- click > button under pomodo 
- you will see state of  App.vue changed to started, but title of StateTitleComponent.vue stay to stopped
![image](https://user-images.githubusercontent.com/3966367/73620716-03a95f80-466e-11ea-89e0-b2946b4d6cc6.png)

### What is expected?
title of StateTitleComponent.vue changed to started

### What is actually happening?
 title of StateTitleComponent.vue stay to stopped

**Comment by LinusBorg** [comment]
```javascript
export default {
  props: ['state'],
  data () {
    return {
      title: this.state
    }
  }
}
```

you assign the prop's value to `title`. this only happens *once*, during mount. If `state` changes later, its changes will not be reflected in `title`.

Solution: use a `computed` instead.

Not a bug.

**Comment by zshuangyan** [comment]
@LinusBorg Thanks a lot! ^_^
I changed the code as you suggested, and it worked.
```
diff --git a/pomodoro/src/App.vue b/pomodoro/src/App.vue
index ed18db8..c2417dd 100644
--- a/pomodoro/src/App.vue
+++ b/pomodoro/src/App.vue
@@ -5,7 +5,7 @@
       <span>{{ state }}</span>
       <controls-component  :state="state" @update="onStateUpdate"></controls-component>
     </h2>
-    <state-title-component :state="state"></state-title-component>
+    <state-title-component :title="title"></state-title-component>
     <countdown-component></countdown-component>
     <kittens-component></kittens-component>
   </div>
@@ -28,6 +28,11 @@ export default {
     KittensComponent,
     StateTitleComponent
   },
+  computed: {
+    title: function () {
+      return this.state
+    }
+  },

diff --git a/pomodoro/src/components/StateTitleComponent.vue b/pomodoro/src/components/StateTitleComponent.vue
index 50fef12..8d5d730 100644
--- a/pomodoro/src/components/StateTitleComponent.vue
+++ b/pomodoro/src/components/StateTitleComponent.vue
@@ -7,11 +7,6 @@

 <script>
 export default {
-  props: ['state'],
-  data () {
-    return {
-      title: this.state
-    }
-  }
+  props: ['title']
 }
 </script>
```
