### ISSUE TITLE
Slots are not updating correctly when binding render function to this context

### ISSUE THREAD

**Issue by Patrick-Spiegel** [vuejs/vue#11071]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/musing-meitner-z5c5n](https://codesandbox.io/s/musing-meitner-z5c5n)

### Steps to reproduce
Change Text in TextBox.

### What is expected?
 It should update the text in the output too.

### What is actually happening?
The text of the scoped slot is not updating

---
Updating with h(Vue.compile) is updating the whole tree, but this causes to render larger pages completely new when a property is changed (Page is scrolling to top).

The advantage of this method is that only those parts are updated which are actually changed, but its not working with slots.

**Comment by posva** [comment]
Changing `$options` in a render function is not public api and should be avoided. A part from that, you are mixing the template syntax with js interpolation, use proper Vue template instead:

```js
const template = `<div>
    <div>{{ msg }}</div>
      <slotted>
        <template v-slot:myslot>
          <div>
            bla
            <hr/>
            {{ msg }}
          </div>
          </template>
      </slotted></div>
    `;
```

The compilation of the template should be done outside of the render function, otherwise, it will be done every time the component needs to be rendered.

**Comment by Patrick-Spiegel** [comment]
@posva Thanks for your answer. It might look like I have mixed those two syntaxes but it is mandatory for our use-case. The general idea is to use Vue as a canvas and update the controls on the canvas based on properties. 

The canvas draws a Vue-String and the attributes of the components are set with string operations. Therefore it is not possible to use mustache syntax in this case.  Imagine `msg` not being a static text but an attribute of the template.

**Comment by Patrick-Spiegel** [comment]
I have created another fiddle for this: https://jsfiddle.net/w0bgzohx/1/
