### ISSUE TITLE
i think there is a bug in  the function named 'classify' at 'vue/src/core/util/debug.js'

### ISSUE THREAD

**Issue by fengzi2016** [vuejs/vue#11070]
### Version
2.6.11

### Reproduction link
[https://codepen.io/fengzi2016/pen/LYEwdbp](https://codepen.io/fengzi2016/pen/LYEwdbp)

### Steps to reproduce
```js
const classifyRE = /(?:^|[-_])(\w)/g
const classify = str => str
    .replace(classifyRE, c => c.toUpperCase())
    .replace(/[-_]/g, '')
const demo = ['_guan', 'guan', '-guan']
demo.forEach((i) => {
    console.log(classify(i));
})
// guan Guan Guan
console.log('_guan'.match(classifyRE))
// _
```

### What is expected?
I think  the function named "classify" is used to making any 
variable to be an Initial capital word

### What is actually happening?
But this function does not work for "_guan"

---
I think the reason is that '\w' includes '_'

sorry for my poor English

**Comment by posva** [comment]
It's great you have an idea of the fix for a problem you have found, but please, provide a reproduction with Vue showcasing the problem or at least explain the practical case you are trying to fix

**Comment by fengzi2016** [comment]
I'm guessing  the meaning of the function named "classify" and found that did not capitalize the first letter of one of the demos, I did not apply it to any Vue applications, just a guess, also may be wrong. Sorry.

**Comment by posva** [comment]
I see, that's okay :)
Usually a bug report should include a reproduction about the failing scenario with Vue because the context in which the function is used is important: the scenario you thought about might never happen with Vue code
