### ISSUE TITLE
example needed of resizing panel div

### ISSUE THREAD

**Issue by Scnck** [vuejs/vue#11074]
### What problem does this feature solve?
I would like an example to have the elements automatic resize when resizing the pane for instance a table. Thank you.

<pane id="pane2-2" size="80" min-size="30">
    <table id="table"></table>
</pane>

### What does the proposed API look like?
N/A

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
