### ISSUE TITLE
Performance issue when scrolling through functional components 

### ISSUE THREAD

**Issue by briwa** [vuejs/vue#11087]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/kind-rosalind-o02ep](https://codesandbox.io/s/kind-rosalind-o02ep)

### Steps to reproduce
- By default, the SVGs and its container are rendered using a non-functional component
- Scroll through the list of items
- Click the button to simulate scrolling up and down, note the average time
- Increase the items to, say, 1000, and also note the average time
- Compare this to rendering with functional component by adding `?containerfunc` in the sandbox preview page URL
- Repeat the process and note the average time
- Also use `?containerfunc&svgfunc` in the sandbox preview page URL to use both functional components 
 

### What is expected?
By right, since functional components supposedly are cheaper to render, the average time to scroll given the same amount of items **should have been lower** when rendering with functional component than rendering with non-functional component, especially since the rendered components do not change at all when scrolling.

### What is actually happening?
The average time it takes to scroll when rendering with functional component is **higher** compared to rendering with non-functional component. It gets worse as the number of items increase.

#### With 100 items:
![100funcnonfunc](https://user-images.githubusercontent.com/8046636/74015859-6aab7900-49cc-11ea-9c41-13a8a7c0264c.png)

#### With 500 items:
![500funcnonfunc](https://user-images.githubusercontent.com/8046636/74015880-71d28700-49cc-11ea-9d12-78266fc54ab6.png)

#### With 1000 items:
![1000funcnonfunc](https://user-images.githubusercontent.com/8046636/74015896-7860fe80-49cc-11ea-87bb-3ad28a536294.png)

#### With 3000 items:
![3000funcnonfunc](https://user-images.githubusercontent.com/8046636/74015903-7e56df80-49cc-11ea-8222-0601eae00918.png)

P.S. Tested on an i7/24GB machine on Chrome, 40 times scrolling, ran separately not simultaneously.

---
A little context, I was refactoring the components in my project to use functional components, hoping that it would improve the performance. As it turns out, it is seemingly slower than before the refactor. I am not sure where the bottleneck is, which is why I created the sandbox with minimal repro.

The main components are the `SimpleSVG` component and the `Container` component. When the page loads, the query param toggles the component to either be rendered as functional or non-functional component. The component itself is simple, reading the props and rendering them using the render function. No lifecycle or other kinds of data involved. The `Items` component then would render a list of items using the two components. The `App` component renders everything, including the sidebar to print out the scroll value and simulate the scrolling then measure the average time.

There is [one similar issue on this](https://github.com/vuejs/vue/issues/5070#issuecomment-283778369) but in that issue, the components are being altered, while in my sandbox the rendered components do not change at all. It is still slower in functional components. It is also mentioned in that issue that by rendering a non-functional component inside a functional component, it would lose the perf benefit, but I did try with both and it seems like it has no effect in this case.

Granted, the scroll event itself is expensive, it should have been debounced to improve the performance, removing the printed-out `scrollTop` value from the template would also improve the performance, but this still doesn't explain the root cause of the slowness. Also, it might be a given that rendering that many items would cause slowness at some point, but this is done only to show the differences between the two types of component. In my project, there are loads of side effects that would in turn contribute to the overall performance of the app. Getting the performance benefit right at the rendering level is IMO important since it affects the rest of the process.

Some further questions:
- Maybe I made a mistake in implementing the functional component, in which the result is in fact a false positive. Any pointers?
- If there's no mistake, is this to be expected from functional component, or is this performance issue a bug?

Thank you for looking into this.

**Comment by posva** [comment]
When using a functional component in a template, it always renders. In your case, in App.vue, you display the `scrollTop` variable, triggering a render of the template (it's not related to the scroll itself but rather changing a variable used in the template so often), triggering a render of Items because it's functional (it would not render if it was stateful because no prop changed), which renders the container (when it's functional), which renders items (when it's functional)

Functional components are not a silver bullet when it comes to performance. Using stateful components to prevent rendering parts of your application can help a lot when combining with functional components because of their main difference being 

functional components: fast to render, renders more often
vs
Stateful components: quick to render, renders less often

I hope this helps you improving the perf issues you are seeing

**Comment by briwa** [comment]
@posva 
> When using a functional component in a template, it always renders. In your case, in App.vue, you display the scrollTop variable, triggering a render of the template (it's not related to the scroll itself but rather changing a variable used in the template so often),

Sure, this is what I mentioned in the second to last paragraph of the issue I just submitted. I already knew that this has some effect to the rest of the performance. My issue was more on the rendering itself. As you can see here (source code [here](https://codesandbox.io/s/gifted-lewin-711m0)): 

### With 100 items
![noscrolltop100](https://user-images.githubusercontent.com/8046636/74020798-46a06580-49d5-11ea-904e-25137909cc42.png)

### With 500 items
![noscrolltop500](https://user-images.githubusercontent.com/8046636/74020796-456f3880-49d5-11ea-9274-a89f71b4e15c.png)

### With 1000 items
![noscrolltop1000](https://user-images.githubusercontent.com/8046636/74020794-443e0b80-49d5-11ea-913c-37bfd28088b1.png)

### With 3000 items
![noscrolltop3000](https://user-images.githubusercontent.com/8046636/74020791-42744800-49d5-11ea-840c-ba04509227da.png)

The overall performance for non-functional components are still better compared to functional components as the items increase. But you're right, these are great takeaways. It makes sense to use functional and the non-functional component sparingly depending on the use case and how to optimize. Thank you for the explanation.
