### ISSUE TITLE
Optional chaining in templates does not seem to work

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue#11088]
### Version
15.8.3

### Reproduction link

https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%20v-if%3D%22obj%3F.a%22%3E%7B%7B%20msg%20%7D%7D%3C%2Fdiv%3E

### Steps to reproduce
Use a v-if that uses optional chaining w/ `@vue/cli version 4.2.0`:

`v-if="test?.length > 0"`

### What is expected?
no error is thrown

### What is actually happening?
following error is thrown:
```
  Errors compiling template:

  invalid expression: Unexpected token '.' in

    test?.length > 0

  Raw expression: v-if="test?.length > 0"
```

**Comment by sodatea** [comment]
As said in the release notes:
> // Note: scripts only, support in template expressions only available in Vue 3

https://vue-next-template-explorer.netlify.com/#%7B%22src%22%3A%22%3Cdiv%20id%3D%5C%22app%5C%22%20v-if%3D%5C%22obj%3F.a%5C%22%3E%7B%7B%20msg%20%7D%7D%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%7D%7D

**Comment by DRoet** [comment]
ah derp, totally read over that comment

**Comment by sodatea** [comment]
Technically, to support such syntaxes in Vue 2, we need to:
1. tweak the codegen to not modify such expressions (currently it converts `obj?.a` to `obj ? .a`)
2. vue-template-es2015-compiler needs to be able to parse such syntaxes (not necessarily to transpile, to parse is enough)
3. backport this commit to vue-loader 15 https://github.com/vuejs/vue-loader/commit/4cb447426ec19c4e07f22ce73fe134f8abaf007c#diff-c735bef98c9338c75a676df1903d2afc
4. get ready for the possible numerous bug reports

We don't have the capacity to implement it yet. But contributions are welcome.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue-next/commit/8449a9727c942b6049c9e577c7c15b43fdca2867#diff-1cb91d3fc9313f91590cd27606eade47R402

**Comment by McPo** [comment]
Potential workaround includes using lodash's get as stated in https://github.com/vuejs/vue/issues/4638#issuecomment-397770996

Another hack is to use `eval`.

As `$eval` was taken out in Vue 2, you'll have to create your own mixin so that it can be accessed in all components without having to import it into each one.

i.e.

``` This will allow $elvis to be accessed in all templates
Vue.mixin({
  methods: {
    $elvis: p => eval('this.'+p)
  }
});
```

Example template
```
<template>
<span>{{ $elvis('foo?.bar') }}</span>
</template>
```

**Comment by Edmund1645** [comment]
>Although its still no substitute for the real operator, especially if you have many occurrences of it
@McPo Just how safe do you think this is? I'm about to use it in production code because I do not want to set computed properties for the numerous nested fields that may be `undefined` or `null`

**Comment by McPo** [comment]
> > Although its still no substitute for the real operator, especially if you have many occurrences of it
> 
> @McPo Just how safe do you think this is? I'm about to use it in production code because I do not want to set computed properties for the numerous nested fields that may be `undefined` or `null`

As far as Im aware, it should be fine, as youre in control of the input. The only issues would be if the developer wasnt aware that its using eval and allows user input to it, but that doesn't really make sense in the case of the elvis operator.

It may have a performance impact though, in that Vue will probably recall the method on every update. I would also suspect theres some overhead in calling `eval` in the first place. Providing its not in a tight loop, realistically you're not likely to notice a difference.

**Comment by troxler** [comment]
Please do *not* use `eval` for that. It generally is bad practice and in this case specifically, it breaks in all browsers that do not support optional chaining. Whether or not you are using Babel or any other transpiler is irrelevant as they cannot transpile strings.

A better way to access properties in a fail-safe way (like with optional chaining) is the following:

```
<template><div>
  {{getSafe(() => obj.foo.bar)}} <!-- returns 'baz' -->
  {{getSafe(() => obj.foo.doesNotExist)}} <!-- returns undefined -->
</div></template>

<script>
export default {
    data() {
        return {obj: {foo: {bar: 'baz'}}};
    },
    methods: {getSafe},
};
function getSafe(fn) {
    try { return fn(); }
    catch (e) {}
}
</script>
```

The `getSafe` function catches any exceptions and implicitly returns `undefined` if the property access fails. You could also create a mixin (or use the new composition API) to reuse that function.

**Comment by McPo** [comment]
> Please do _not_ use `eval` for that. It generally is bad practice and in this case specifically, it breaks in all browsers that do not support optional chaining. Whether or not you are using Babel or any other transpiler is irrelevant as they cannot transpile strings.
> 
> A better way to access properties in a fail-safe way (like with optional chaining) is the following:
> 
> ```
> <template><div>
>   {{getSafe(() => obj.foo.bar)}} 
>   {{getSafe(() => obj.foo.doesNotExist)}} 
> </div></template>
> 
> <script>
> export default {
>     data() {
>         return {obj: {foo: {bar: 'baz'}}};
>     },
>     methods: {getSafe},
> };
> function getSafe(fn) {
>     try { return fn(); }
>     catch (e) {}
> }
> </script>
> ```
> 
> The `getSafe` function catches any exceptions and implicitly returns `undefined` if the property access fails. You could also create a mixin (or use the new composition API) to reuse that function.

True I forgot to highlight the issue that it requires optional chaining to be supported in the browser. (Which isn't a major issue in my case, although I probably will stop using it anyway)

**Comment by adjenks** [comment]
For a deeply nested complex objects, this seems really important. I have objects that are five layers deep. I like the getSafe() method described by troxler, but I would prefer that chaining just work.

**Comment by magistr4815** [comment]
@troxler Hey. Your way doesn't work for dynamic data (if internal keys will change over time). The method will work once and that's it.

**Comment by tvkit** [comment]
Using the following for a TS project:

```
  private s<T>(obj: T | undefined): T {
    return obj || ({} as T);
  }
```
with VUE expressions that look like:
```
<q-input 
  v-model="model.value"
  label="Eyeballs"
  type="number"
  :min="s(s(model).pirate).min"
  :max="s(model).max"
/>
```

Gets a bit nesty beyond the first property, but the linters are happy.

**Comment by Juraj-Masiar** [comment]
>   private s<T>(obj: T | undefined): T {
>     return obj || ({} as T);
>   }

@tvkit that's not exactly good implementation as it won't work with any other `falsy` values like empty string, zero, false. So `s('').length` will give me `undefined` instead of zero.

**Comment by Sceat** [comment]
Using a function is outside the scope of this issue and not a viable replacement. However if someone need this kind of hack, use this :point_down: 

```js
const reducer = source => (object, property) => object?.[property] ?? undefined
const optional_chain = (...parameters) => {
	const [source, ...properties] = parameters
	return properties.reduce(reducer(source))
}
```

**Comment by tvkit** [comment]
@Juraj-Masiar Good point.

**Comment by Baldrani** [comment]
@Sceat I actually really like the idea.

**Comment by edgarshurtado** [comment]
I guess the idea is to use optional chaining in Single File Components. But, funny enough, if you import the template from an HTML or PUG file, it works. I'd guess it shouldn't work either.

**Comment by MBearo** [comment]
> Using a function is outside the scope of this issue and not a viable replacement. However if someone need this kind of hack, use this 👇
> 
> ```js
> const reducer = source => (object, property) => object?.[property] ?? undefined
> const optional_chain = (...parameters) => {
> 	const [source, ...properties] = parameters
> 	return properties.reduce(reducer(source))
> }
> ```
> 
> ```
> <div :foo="optional_chain({}, 'foo', 'bar', 'baz')" />
> ```

It's not work.I fix it.
```javascript
const optional_chain = (...parameters) => {
  const [source, ...properties] = parameters
  return properties.reduce((object, property) => object?.[property] ?? undefined, source)
}
const a={b:{c:{d:1}}}
console.log(optional_chain(a,'b','c','d'))
```

**Comment by CMCDragonkai** [comment]
I'm on Vue 3.0.0, and it still doesn't work. Did it work on a later version?

**Comment by arielginsburg** [comment]
> I'm on Vue 3.0.0, and it still doesn't work. Did it work on a later version?

Same here. I thought this was getting fixed with the release of Vue 3. Guess not... 😔

**Comment by jacekkarczmarczyk** [comment]
> Same here. I thought this was getting fixed with the release of Vue 3. Guess not... 😔

It does work in Vue 3

**Comment by arielginsburg** [comment]
> > Same here. I thought this was getting fixed with the release of Vue 3. Guess not... 😔
> 
> It does work in Vue 3

Not for me! I'm using vue 3.0.4 and vue-loader 16.1.2 and I get the following compiler error:

```
Module parse failed: Unexpected token (27:70)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
|         _createVNode("tr", null, [
|           _hoisted_4,
>           _createVNode("td", null, _toDisplayString(_ctx.currentTime ?? 'null'), 1 /* TEXT */)
|         ]),
|         _createVNode("tr", null, [
```

The breaking code in my template is the following:
```
<tr>
    <td>current time</td>
    <td>{{ currentTime ?? 'null' }}</td>
</tr>
```

**Comment by LinusBorg** [comment]
As you can see in the error message, the template was correctly converted, containing the optional chaining character.

The error seems to come from webpack, as it states _"File was processed with these loaders:"_ 

maybe your babel setup doesn't contain support for transpiling optional chaining operators?

**Comment by LinusBorg** [comment]
Here's a codesandbox where it works fine: https://codesandbox.io/s/vigilant-bash-bjjvl?file=/src/App.vue

**Comment by arielginsburg** [comment]
Strange. My code compiles just fine using the nullish coalescing operator in Typescript. I only encounter the issue when using the operator in templates.

**Comment by LinusBorg** [comment]
Presumably because the Vue compiler generates JS and is never run through the TS compiler.

Anyways, thatbw9upe have to be discussed in the vue-next repo as that's about Vue 3

**Comment by BoBoooooo** [comment]
mark.
Have the same problem with using ?.  in template 2.x.
Wait for support

**Comment by douglasg14b** [comment]
This would definitely be great to have in Vue2! Will there be support added?

**Comment by baybal** [comment]
Same behaviour for me on the latest Chrome, loader 16, and vue@latest

**Comment by calevio** [comment]
optional chaining support for Vue2 please!
If I were to take a jab at this, is [this](https://github.com/vuejs/vue/issues/11088#issuecomment-583354390) still the right path?

**Comment by andriusign** [comment]
Optional chaining for Vue2 please!

**Comment by adjenks** [comment]
I think they just want you to migrate to Vue3 at this point.

**Comment by JuniorTour** [comment]
I'm working on this and made some progress to enable `Optional Chaining` syntax for SFC.

### Try this repo: https://github.com/JuniorTour/vue-template-babel-compiler

### DEMO: ![DEMO](https://user-images.githubusercontent.com/14243906/122681567-785f4880-d227-11eb-91e3-abc9ffc06524.png)

### Usage
``` js
# 1: In your Vue project directory
yarn add https://github.com/JuniorTour/vue-template-babel-compiler/tarball/main

# 2: Run a script to
# modify vue-template-es2015-compiler to this repo
# (If this repo got merged into the official repo, this step can be simplified.)
sh ./node_modules/vue-template-babel-compiler/updateVueTemplateBabelCompiler.sh

# Enjoy~
```

There are still many essential work to be done. I'll keep trying. 

You can watch the repo above to follow.

**Comment by xianghongai** [comment]
It is not correct to use the `?.` syntax. The Vue design is to view the data binding on the data already processed by Reactive. It is a stable data model.

**Comment by xianghongai** [comment]
But from the perspective of JavaScript grammar, such support should be provided. What is executed is an expression and does not depend on the data model. 😂

**Comment by calevio** [comment]
> But from the perspective of JavaScript grammar, such support should be provided. What is executed is an expression and does not depend on the data model. 😂

![image](https://media.giphy.com/media/cBt6S7dMjroHu/giphy.gif)

**Comment by smitpatelx** [comment]
/*
 * Where to use: Use in vue templates to determine deeply nested undefined/null values
 * How to use: Instead of writing parent?.child?.child2 you can write
 *            isAvailable(parent, 'child.child2')
 * @author    Smit Patel
 * @params    {Object} parent
 *            {String} child
 * @return    {Boolean}     True if all the nested properties exist
 */
export default function isAvailable(parent, child) {
  try {
    const childArray = String(child).split('.');
    let evaluted = parent;
    childArray.forEach((x) => {
      evaluted = evaluted[x];
    });
    return !!evaluted;
  } catch {
    return false;
  }
}

**Comment by nobiit** [comment]
> I'm on Vue 3.0.0, and it still doesn't work. Did it work on a later version?

I am currently using v2.6.14, the latest at the time of writing this comment. The problem still exists

**Comment by ankurk91** [comment]
https://github.com/developit/dlv

**Comment by Shinigami92** [comment]
> developit/dlv

This will neglect any typing and therefore not an acceptable option

**Comment by mohamadrezahedayati** [comment]
You can write a `method` that returns its value.
example in under 
### template : 
![image](https://user-images.githubusercontent.com/43079809/131971335-32fe3833-6534-4bee-ba31-de9aa7d526a8.png)
### methods : 
![image](https://user-images.githubusercontent.com/43079809/131971514-ff9bc8fd-ed6a-4fde-8bf6-792424aed5f7.png)

**Comment by adjenks** [comment]
@mohamadrezahedayati 
The point is that it's convenient and short, not just to use it for the sake of using it.
Writing a whole method doesn't make any sense. I'd rather just write inline `{{'name' in item ? item.name : null}}` instead of making a function, but I'd prefer to write `{{item?.name}}` inline.

**Comment by mohamadrezahedayati** [comment]
@adjenks 
I know that when you write a function, the amount of code written increases but each increase `not bad ` .
### why : 
1. because your application logic is inside script not `presentation` layer
2. because you **`can test`** it in the test unit.
3. because according to the [Clean Code Book](https://github.com/yiailake/book/blob/master/%5BPROGRAMMING%5D%5BClean%20Code%20by%20Robert%20C%20Martin%5D.pdf) , your application logic is **`inside`** a wrapper ( function ) , This helps to read the code and the others will understand the reason for this.

**Comment by calevio** [comment]
Checking property presence hardly constitutes as application logic.
Having the function as a workaround is one thing, but stating that it is the preferred approach for the sake of clean code is a bit absurd.

Bottom line is optional chaining is a

**Comment by joecampo** [comment]
@mohamadrezahedayati Clean Code isn't just a book of hard and fast rules. By your logic, Vue components in themselves violate SRP.

@calevio is 100% correct.

**Comment by tflori** [comment]
In my opinion that is not logic by the mean of "no logic in views". `v-if` and `v-for` etc. are the type of logic that is meant by this sentence. And to create a method or calculated property is hiding what properties are used. It is therefore rather not clean code.. There is a reason behind the clean code policy and there are exceptions. If you couldn't write conditionals or loops in views you are back to static HTML. So it is common in every template language to wire such logic in the view.

**Comment by Shinigami92** [comment]
Please stop :stop_sign: the discussion about whether this feature is wanted or not.
This is expected valid JS embedded in Vue templates and the JS/ECMA-version supported for embedded code in Vue template is just "outdated" and therefore doesn't support the optional chaining syntax.

I'm nut sure if we want to support it in Vue 2... I understand this. But in Vue 3 this is an essential need. _(if not already possible, I'm sadly a bit behind due to lacking support of `Vuetify`)_

**Comment by cwilby** [comment]
One more way to do this, didn't want to use lodash.

Add a mixin / function
```
  $get(obj, path) {
    let result = obj;
    for (let piece of path.split('.')) {
      result = result[piece];
      if (!result || typeof result !== 'object') {
        return result;
      }
    }
    return result;
  }
```

Use in templates
```
<p>{{ $get(company, 'representative.phones[2].number') }}</p>
```

**Comment by maximilliangeorge** [comment]
> babel-com



> Try [vue-template-babel-compiler](https://github.com/JuniorTour/vue-template-babel-compiler)
> 
> It will enable `Optional Chaining(?.)`, `Nullish Coalescing(??)` and many new ES syntax for `Vue.js SFC` based on `Babel`.
> 
> ## [Github Repo: vue-template-babel-compiler](https://github.com/JuniorTour/vue-template-babel-compiler)
> ## DEMO
> ![DEMO](https://user-images.githubusercontent.com/14243906/127761300-076db45a-cdce-4fda-bd02-1f4fa96de6d8.png)
> 
> ## Usage
> [Please refer to REAMDE for detail usage](https://github.com/JuniorTour/vue-template-babel-compiler#usage)
> 
> Support for `Vue-CLI, Nuxt.js, Webpack, vue-jest` , any environment use `vue-loader`.

This works, thanks a lot! The only reply that didn't suggest various hacks and workarounds.

**Comment by souljorje** [comment]
Let's support issue to implement it in vite & vue 2 https://github.com/underfin/vite-plugin-vue2/issues/161

**Comment by caocaoem** [comment]
> 

In the file node_modules\vue-template-babel-compiler\lib\index.js

184 line find `errors` edit `errors:[]` good job

**Comment by robert-niestroj** [comment]
The blog post on Vue 2.7 https://blog.vuejs.org/posts/vue-2-7-beta.html says: 

> 2.7 also supports using ESNext syntax in template expressions.

Will this release solve this?

**Comment by DRoet** [comment]
@robert-niestroj I tested this today and it seems to work in v2.7 (make sure you have vue-loader >=v15.10 installed)

**Comment by MartinX3** [comment]
Be aware that you can't use typescript there with Vue 2.7.
If you need it, use Vue 3.x.

**Comment by robert-niestroj** [comment]
I tested it today with Quasar Framework 1.19.4, based on Vue 2.7.1 and can confirm it works.

**Comment by DRoet** [comment]
I'm gunna go ahead and close this issue for now since there is a solid solution, upgrading to v2.7 should be pretty easy for most users.

**Comment by maxkopych** [comment]
@DRoet updating vue to `2.7.10` didn't fix problem for me.
My packages:
```
    "vue": "2.7.10",
    "vue-loader": "15.10.0",
    "vue-style-loader": "^4.1.3",
    "vue-template-compiler": "^2.7.10",
```
Did you configure something in webpack?

**Comment by Songoo7** [comment]
Sadly plugin above did not help at all for chaining. To update from 2.4 to 2.7 and webpack from 3 to 4 with babel to 7 seems like one month job alone on my project T.T .

I wish there would be some easy solution :( , like on vue 1 project it worked just like that with no changes needed :D .

For now using function above, tnx at least for that!

**Comment by Songoo7** [comment]
> 

Plugin did not work because it needs vue-loader 15, but jump from 14 to 15 has so many bcbreaks that after day I was lucky to even be able roll back to working solution :D .

For webpack 3 to 4 is much much worse, I have all minors at max, but when doing big jumps there are just too many bc-breaks, its old project and it show like hundreds of errors :) . At times like this, just miss vue 1, where chain work just like that :-) .

**Comment by TheJaredWilcurt** [comment]
Vue-CLI 4 + Vue 2.7

I am not able to get `{{ foo?.bar?.baz }}` or `v-if="foo?.bar?.baz"` to work.

Here is a simplified version of my deps:

```json
"dependencies": {
  "vue": "2.7.11",
  "vue-router": "3.6.5",
  "vuex": "3.6.2"
},
"devDependencies": {
  "@babel/core": "^7.19.3",
  "@babel/eslint-parser": "^7.19.1",
  "@babel/runtime": "^7.19.4",
  "@vue/cli-plugin-babel": "^4.5.19",
  "@vue/cli-plugin-eslint": "^5.0.0-rc.2",
  "@vue/cli-plugin-router": "^4.5.19",
  "@vue/cli-plugin-vuex": "^4.5.19",
  "@vue/cli-service": "^4.5.19",
  "@vue/test-utils": "^1.3.0",
  "core-js": "^3.25.5",
  "eslint": "^8.25.0"
}
```

I removed `vue-template-compiler` because the docs said it is no longer needed with Vue 2.7.

What do I need to change to allow Optional Chaining in the template?

**Comment by maxkopych** [comment]
> Vue-CLI 4 + Vue 2.7
> 
> I am not able to get `{{ foo?.bar?.baz }}` or `v-if="foo?.bar?.baz"` to work.
> 
> Here is a simplified version of my deps:
> 
> ```json
> "dependencies": {
>   "vue": "2.7.11",
>   "vue-router": "3.6.5",
>   "vuex": "3.6.2"
> },
> "devDependencies": {
>   "@babel/core": "^7.19.3",
>   "@babel/eslint-parser": "^7.19.1",
>   "@babel/runtime": "^7.19.4",
>   "@vue/cli-plugin-babel": "^4.5.19",
>   "@vue/cli-plugin-eslint": "^5.0.0-rc.2",
>   "@vue/cli-plugin-router": "^4.5.19",
>   "@vue/cli-plugin-vuex": "^4.5.19",
>   "@vue/cli-service": "^4.5.19",
>   "@vue/test-utils": "^1.3.0",
>   "core-js": "^3.25.5",
>   "eslint": "^8.25.0"
> }
> ```
> 
> I removed `vue-template-compiler` because the docs said it is no longer needed with Vue 2.7.
> 
> What do I need to change to allow Optional Chaining in the template?
> 
> Tagging @DRoet because they closed this in hopes of an answer or re-opening. As this seems like a very common situation (Vue-CLI).

I had similar problem. Fix for that was configure babel-loader in webpack for js files. Example for my rails app:
```
module.exports = {
    test: /\.(js)?(\.erb)?$/,
    exclude: /node_modules/,
    use: ['babel-loader']
};
```

**Comment by TheJaredWilcurt** [comment]
@maxkopych You showed code, but did not mention what file to put it in. To be clear, I am not using Webpack. I am using Vue-CLI (which in turn handles Webpack for me). So any Webpack tweaks need to be handled via the `vue.config.js` file, likely piggy-backing off of `chainWebpack`.

I'm asking if I need to change something there, and if so, what do I change?

**Comment by maxkopych** [comment]
> @maxkopych You showed code, but did not mention what file to put it in. To be clear, I am not using Webpack. I am using Vue-CLI (which in turn handles Webpack for me). So any Webpack tweaks need to be handled via the `vue.config.js` file, likely piggy-backing off of `chainWebpack`.
> 
> I'm asking if I need to change something there, and if so, what do I change?

I didn't work with vue-cli for awhile. But again if you gonna read this [article](https://blog.vuejs.org/posts/vue-2-7-naruto.html)
you will see line: 
`
2.7 also supports using ESNext syntax in template expressions. When using a build system, the compiled template render function will go through the same loaders / plugins configured for normal JavaScript. This means if you have configured Babel for .js files, it will also apply to the expressions in your SFC templates.
`

All you need is search how to add new rules to loaders in vue-cli. first I found: https://stackoverflow.com/questions/59960121/how-can-i-add-new-rules-to-loaders-while-using-vue-cli-3-x

**Comment by TheJaredWilcurt** [comment]
Here is my `package-lock.json`, slimmed down to just the parts relating to `vue-loader`:

```json
{
  "packages": {
    "node_modules/@vue/cli-service": {
      "version": "4.5.19",
      "dependencies": {
        "vue-loader": "^15.9.2"
      },
      "optionalDependencies": {
        "vue-loader-v16": "npm:vue-loader@^16.1.0"
      }
    },
    "node_modules/@vue/cli-service/node_modules/vue-loader-v16": {
      "name": "vue-loader",
      "version": "16.8.3"
    },
    "node_modules/vue-loader": {
      "version": "15.9.8"
    }
  },
  "dependencies": {
    "@vue/cli-service": {
      "version": "4.5.19",
      "requires": {
        "vue-loader": "^15.9.2",
        "vue-loader-v16": "npm:vue-loader@^16.1.0"
      },
      "dependencies": {
        "vue-loader-v16": {
          "version": "npm:vue-loader@16.8.3"
        }
      }
    },
    "vue-loader": {
      "version": "15.9.8"
    }
  }
}
```

**Comment by amc1999** [comment]
I had same problem and manage to solve it by adding babel plugins:
```
// babel.config.js
module.exports = {
  plugins: [
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-optional-chaining'
  ],
  presets: [
    .....did not change anything in presets....
```

Just for the info, versions from package-lock (as it is today) are:
```
"quasar": {
      "version": "1.22.2",
"vue": {
      "version": "2.7.14",
 "vue-loader": {
      "version": "15.10.1",
```
As you can see we are still on Quasar 1 and Vue 2, planning move to Vue 3, but not now.

**Comment by richard-d-vindico** [comment]
Can I just check, this wasn't working in the template before (only in script logic), but now it works in the template just fine. 

Did something change (i'm using v2.6.11)?

**Comment by cwilby** [comment]
@richard-d-vindico Vue 2.7 added support for using ESNext syntax in template expressions. (https://blog.vuejs.org/posts/vue-2-7-naruto.html)

Run `npm ls | grep vue@` to see what your specific version of Vue is.

**Comment by richard-d-vindico** [comment]
I'm on v2.6.11 and it's works just fine in the template.
