### ISSUE TITLE
Focusing on a recently visible element fails.

### ISSUE THREAD

**Issue by adjenks** [vuejs/vue#11091]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/bqurd5ts/1/](https://jsfiddle.net/bqurd5ts/1/)

### Steps to reproduce
1. Click the "Appear then focus." button.
2. Click the "Hide/Reset" button.
3. Click the "Appear using set then focus" button.

### What is expected?
Because assignment to a variable is intuitively synchronous, I expect that assigning a variable and then calling focus on an element to be able to focus on the element.

### What is actually happening?
The element does not exist yet when calling focus after being rendered conditionally based on the data, so the focus needs to be called in a delayed function to wait for the element to appear.

---
If setting a variable results in a series of asynchronous events, then perhaps Vue.$set() should return a promise so that you know when it's rendered.

**Comment by posva** [comment]
This is expected: when the variable changes, the Dom is not immediately rendered. Wait for a vue tick:

```js
this.vis = true
await this.$nextTick()
element.focus()
```

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by adjenks** [comment]
Thank you.
