### ISSUE TITLE
Vue drops elements from markup when using template elements

### ISSUE THREAD

**Issue by deathgaze** [vuejs/vue#11098]
### Version
2.6.11

### Reproduction link
[https://codepen.io/ksefchik/pen/xxGGRXq](https://codepen.io/ksefchik/pen/xxGGRXq)

### Steps to reproduce
1. Create two components and link their templates by using `template` element in HTML as `template` in script definition.
2. Create a third parent component and link it's template using `template` element in HTML as `template` in script definition.
3. Place the two components into the third parent component as siblings.

### What is expected?
Sibling components are both displayed.

### What is actually happening?
Only first sibling is displayed.

**Comment by deathgaze** [comment]
Also: I'm aware I am also using Materialize here, however removing references to Materialize still causes second sibling not to be displayed.

**Comment by posva** [comment]
When reporting a bug please provide a boiled down repro with no external dependencies (no vuex, no materialize) with clear instructions on what to do on the demo to see the bug.
Ping me or open a new issue once you have one
