### ISSUE TITLE
Error when return html character to japanese

### ISSUE THREAD

**Issue by gemtcn** [vuejs/vue#11096]
I have a string `&#20986;&#21253;&#29579;&#22899;&#32;&#26263;&#32;`. It will be auto convert to "出包王女 暗" when I use below code:
`<h2>&#20986;&#21253;&#29579;&#22899;&#32;&#26263;&#32;</h2>`

But when I use vuejs code as folowing:
`data = "&#20986;&#21253;&#29579;&#22899;&#32;&#26263;&#32;"`
`<h2>{{ data }}</h2>`
=> It can not display right text "出包王女 暗". 
It was displayed `&#20986;&#21253;&#29579;&#22899;&#32;&#26263;&#32;`

So, How to auto convert `&#20986;&#21253;&#29579;&#22899;&#32;&#26263;&#32;` to `出包王女 暗` ?
I don't want to convert by manual.
Thanks!

**Comment by Justineo** [comment]
Just use the original text in JavaScript. Or you have to use `<h2 v-html="data"></h2>`, which might introduce security risks.
