### ISSUE TITLE
Can a "custom event modifier" be provided for "vue plugin developer "?

### ISSUE THREAD

**Issue by any86** [vuejs/vue#11097]
### What problem does this feature solve?
For example, touch events actually have multiple targets in ev.touches, while vue's existing "event modifiers" are mostly for ev.target. Could you provide a more elegant opportunity for vue's plug-in developers to "customize event modifiers"?

I am developing [a gesture library](https://github.com/any86/any-touch/tree/feature/packages#%E5%85%BC%E5%AE%B9vue%E8%AF%AD%E6%B3%95) for basic touch events, simulating multi-pinch requires determining whether each target in touches is a child element of currentTarget, which is not very elegant now, but I like vue very much, I hope my plugin can make people use it more elegant in vue, I hope you can get help. Thanks.
now:
```vue
     <div
                @pinch="$event.xx() && onPinch"
                @rotate="$event.xx() && onRotate"
            >
```

### What does the proposed API look like?
```vue
     <div
                @pinch.xx="onPinch"
                @rotate.xx="onRotate"
            >
```
or:
```vue
     <div
                @pinch.from:xx="onPinch"
                @rotate.from.xx="onRotate"
            >
```

**Comment by posva** [comment]
This could be interesting but needs to go through the RFC process (https://github.com/vuejs/rfcs#vue-rfcs) to provide much clearer details like is it at runtime or at compilation time? And clearer examples about its usage, benefits, and drawbacks.
