### ISSUE TITLE
Syntax suggestion when passing props to components

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [vuejs/vue#11103]
Hello, I'd like to suggest the following syntax that you may add to future releases.
```
<my-component ::params @@myMethod />
```
Could be equivalent to 
```
<my-component :params="params" @myMethod="myMethod" />
```
That would make code much cleaner when we have to pass multiple props to a child component and those props have the same name as the variables in the parent component. The same thing can be said about events. 

I hope you take this into consideration and that my suggestion will help you improve VUE.

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/5835

**Comment by AndreSouzaAbreu** [comment]
Hello @posva. I can imagine how busy you probably were, so I have thank you for the attention. 

You marked my issue as a duplicate of #5835. They are really similiar indeed, but there are a few difference. Let's exam them.

 First, I'm proposing that ``::propName`` should be equal to ``:propName="propName"`` while the issue #5835 proposes something different. Not like the proposal of #5835, the syntax ``::propName`` would not cause a break change since it wouldn't generate conflict with `boolean` props because it uses two colons, not only one. 

 Moreover, I also suggested that ``@@myMethod`` should be equivalent to ``@myMethod="myMethod"``. This is not addressed in #5835, and the workaround for props (which is to use `v-bind`) doesn't work for methods and events.

Please, reconsider my question, and remove the Closed tag

**Comment by posva** [comment]
Please check the discussions, the arguments provided apply for both of your suggestions

**Comment by AndreSouzaAbreu** [comment]
I checked the discussion and I can't see where the arguments apply to my suggestions. Could you clarify that for me, please?

**Comment by AndreSouzaAbreu** [comment]
Hello. I'm still not convinced  that the arguments provided apply for my suggestions since they are different. For example, the workaround proposed doesn't work with methods and my proposal for `::propName` would not cause a break change or a conflict with Boolean values
