### ISSUE TITLE
For input checkboxes v-model with additional @input event handlers v-model is not set to true-value and false-value bindings

### ISSUE THREAD

**Issue by ventralnet** [vuejs/vue#11101]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/ventralnet/1ew78c93/2/](https://jsfiddle.net/ventralnet/1ew78c93/2/)

### Steps to reproduce
Open up the console, click the checkbox. You will see two console messages logged on @input event.  this.selectedValue is logged immediately and it is blank, then in the next event loop it properly has true-value

Is this a bug?

### What is expected?
this.selectedValue is set to true-value attribute

### What is actually happening?
this.selectedValue is blank until next event loop

**Comment by posva** [comment]
This is due to timing difference between the `input` and `change` (the one you should be listening to) events. This is something you should avoid relying on as browsers could behave differently. The event that should be used for a checkbox is `change` though. Using that events works fine
