### ISSUE TITLE
Global event bus sets listeners to null on bad code

### ISSUE THREAD

**Issue by hawkeye64** [vuejs/vue#11104]
### Version
2.6.11

### Reproduction link
[https://codepen.io/Hawkeye64/pen/bGdENZo?editors=1010](https://codepen.io/Hawkeye64/pen/bGdENZo?editors=1010)

### Steps to reproduce
The link has the steps. Basically, you need two components that are subsequently created and destroyed. The first component registers an event with the global event bus and de-registers it when destroyed. The second component, only has the de-registration in it's BeforeDestroy. When going from 1st component, to second component, then back to first component, the first component is created, the event is registered, the second component is destroyed and array of listeners for that event is set to null when the de-registration is done.
I know this is bad coding. But could happen to anyone. This took us two days to figure out. I wanted to learn more about the issue, so wrote the codepen to illustrate the issue and to test various versions of Vue.
This issue does not occur in v2.5.2 or earlier. It started with v2.5.3 and is present in latest (v2.6.11).

### What is expected?
Vue should keep track of $on/$off listeners and ignore $off if no corresponding $on - at least don't set the listeners array to null.
With the link to reproduce the bug, I have done the latest (2.6.11) and back to 2.5.3 - this is NOT a bug in 2.5.2 as the reproduction works in that version, so quite possibly something changed.

### What is actually happening?
The listeners array for the event is set to null. Therefore, no other listeners can receive the event messages from the global event bus.

---
Before a jr dev left our company, he was doing some clean up. In the mounted() he remove some code `this.$root.$on('alarms:new', this.myFunc)` but forgot to remove in the `BeforeDestroy` this `this.$root.$off('alarms:new', this.myFunc)`. Subsequently, we stopped getting this particular event with other components. 
What we found is that the innocuous code, when calling $root.$off does not have a matching $root.$on, so the event array for the listeners is set to null.

**Comment by jesusvilla** [comment]
This occurs because the event is deleted when there is no function declared in [vm.$off](https://github.com/vuejs/vue/blob/dev/src/core/instance/events.js#L101-L103) but it should not be taken into account when it is $root.
Look: https://codepen.io/jvillanueva/pen/ExjVdGg

**Comment by hawkeye64** [comment]
@jesusvilla Good fix! Hopefully the Vue folks incorporate that.

**Comment by hawkeye64** [comment]
Here is what happened in dev tools: 
![image](https://user-images.githubusercontent.com/10262924/74448323-ff343200-4e37-11ea-875a-89cb9f2b119a.png)

**Comment by posva** [comment]
The reason this happens is because QChild2 is destroyed before Qchild1 is created, removing all listeners added by Qchild1. This is not a bug.
Attaching the event on `mounted` instead of `created` allows you to get around this

**Comment by hawkeye64** [comment]
As I said in the title, this is bad code. But, Vue being oriented towards simplicity and new developers, don't you think @posva that incorporating the fix that @jesusvilla did would be a good thing?

**Comment by posva** [comment]
That fix breaks existing usage by not allowing removing all listeners attached to an event with `$off('event')` on root instances or simple buses `new Vue()`  (https://github.com/vuejs/vue/pull/11105#issuecomment-585822130)
Ordering matters when attaching events to a Bus and relying on component creation and removal don't play nicely, mounting and unmounting does though. Changing the order would also be a breaking change

**Comment by jesusvilla** [comment]
@posva  I believe that `vm.$off `should turn off listening only associated with that component, it has not the other components.
Look: https://codepen.io/jvillanueva/pen/ExjPKjq
