### ISSUE TITLE
prop 的值更新不及时

### ISSUE THREAD

**Issue by notomorow** [vuejs/vue#11106]
### Version
2.6.10

### Reproduction link
[https://codepen.io/notomorow/pen/abOdVPE?editors=1010。](https://codepen.io/notomorow/pen/abOdVPE?editors=1010。)

### Steps to reproduce
https://codepen.io/notomorow/pen/abOdVPE?editors=1010。当父组件里的key加1时，立即调用子组件的alert方法，按预想此时子组件alert里的val应该更新了，但是并没有。

### What is expected?
当父组件里的key加1时，立即调用子组件的alert方法，按预想此时子组件alert里的val应该更新了。

### What is actually happening?
子组件alert的this.val 还是老的

**Comment by zkwolf** [comment]
因为是异步更新的啊，你可以用$nextTick

**Comment by notomorow** [comment]
嗯，我疑惑的点是这里为什么要异步更新，因为按常规想法最好是同步更新。是因为同步更新实现上或者性能上会有问题吗

**Comment by posva** [comment]
This is expected because the value takes a tick to propagate to the children. You can wait one tick before calling `alert`:

```js
this.value += 1
await this.$nextTick()
this.$refs.child.alert()
```
