### ISSUE TITLE
Wanna see my hot pics?💋💋💋

### ISSUE THREAD

**Issue by akdnfbf** [vuejs/vue#11114]
Hi!😻😻😻 Wanna see my hot pics?💋💋💋 Go to this site and find me here. ❤️❤️❤️ My nick is sexygirl662 👇👇👇

https://tinyurl.com/sbmadwq

**Comment by VISWESWARAN1998** [comment]
This is a spam. Please close it.

Wrote a small script to automate the reporting, Just like the spammer did.

Script here: https://gist.github.com/VISWESWARAN1998/cf74dd0890534ad3e72f326e46460cd3

Regards,
Visweswaran N

**Comment by posva** [comment]
@VISWESWARAN1998 please, don't post comments on the spam, it just adds to the spam. You can instead report the user to Github, that could help banning them
