### ISSUE TITLE
 Impossible to select the child elements of the table when filled with function

### ISSUE THREAD

**Issue by lucasmsoares96** [vuejs/vue#11120]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/lucasmsoares96/2x0mpLt7/1/](https://jsfiddle.net/lucasmsoares96/2x0mpLt7/1/)

### Steps to reproduce
open the browser console

### What is expected?
the browser console is expected to show the childre elements of the selected table.

### What is actually happening?
Child elements are not selected.

---
child elements are selected when the items attribute is defined within data(), but not when items are returned from a function

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is related to bootstrap vue. Also, you are accessing table[1] but table has only one element
