### ISSUE TITLE
Allow BigInt usage in templates

### ISSUE THREAD

**Issue by YanDevDe** [vuejs/vue#11126]
### What problem does this feature solve?
It would allow us to use numbers which is larger than MAX_SAFE_INTEGER. 

### What does the proposed API look like?
In HTML, `{{BigInt("100")}}`, `{{100n}}`, `{{2n * 50n}}` or `{{50n + 50n}}` should show "100" (it can be just simply string by using .toString()) at frontend.
At the moment using BigInt in "Mustache" syntax just throw error.
Sure, backup solution would be using external functions or converted into string and save it to variable. But using BigInt directly in HTML would be nice to have.
More Information about BigInt -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by posva** [comment]
BigInt could be added to the other allowed variables like Number in templates. It will only be supported by browsers supporting it though

**Comment by YanDevDe** [comment]
BigInt has already good (still not large enough, Safari is still missing) cross browser support. 
https://caniuse.com/#search=bigint
So perhaps this feature should be implemented as experimental.

**Comment by pasDamola** [comment]
Hi @posva can i begin working on this? What steps could i take in working on this also

**Comment by parthjawale** [comment]
Hi @posva, I'd like to work on this issue if that's alright?

**Comment by shadowings-zy** [comment]
Hello, I have created a pull request for this feature!
If there are anything wrong in this pull request, I will fix them.

**Comment by parthjawale** [comment]
Oh, no problem. 
Sounds great!

**Comment by SuperMan-my** [comment]
果然还是高深莫测

**Comment by rohitrajvanhi** [comment]
Hy anyone hack hago dimond so plzz msg me whatapp 7901879279

**Comment by lesleh** [comment]
> BigInt has already good (still not large enough, Safari is still missing) cross browser support.

@YanDevDe Safari 14 beta now has BigInt support.

**Comment by Hardikanand1st** [comment]
https://github.com/disscussion-room join this organisation and you can discuss there.

**Comment by HBrowling** [comment]
Probably the problem is in some little things. It happens so often)

**Comment by Terence-art** [comment]
I would use a combination of parseFloat and parseInt

**Comment by mlys1315** [comment]
新百胜怎么联系13099612171www.xbs0518.com
