### ISSUE TITLE
Not able to perform action before user reload page or exit my application

### ISSUE THREAD

**Issue by mauroviniciussilva** [vuejs/vue#11125]
### What problem does this feature solve?
So, I'm using the version 2.6.11 and I'm facing some difficulties to perform an action before the user exit my application or reloads the page.

I'm doing a integration of a CRM with telephony. When the user access my application he needs to login (not in my application, but in a hub that I'm accessing with SignalR), so I can perform some action like make a call, receive a call, and handle the events that I receive from the hub. The problem is: if the user reloads the page or exit the page, I need to log him out of the hub connection. 

When using angular the solution was very simple, i just needed to call:
```JS
$scope.$on('$destroy', function () {
       // Log user out here
});
```
... but I can't do this with vue. I've been trying to use the <code>beforeDestroy</code>, <code>keep-alive</code>, <code>destroyed</code>, and other methods, but none of them are helping me to achieve my goal. I tried pure javascript like 
```JS
window.onbeforeunload = () => { 
       // Log user out here
}
```
... but for some reason not even this had helped me to solve the issue.

I really don't know if it is my mistake, or if this is not implemented on vue yet, but I haven't find similar issues on internet, so I decided to open one here. I hope you can help me, because I'm kinda new to vuejs and I've been liking a lot the flexibility of this framework.

I believe that a functionality like that can help in many environments, like showing a message before the user gets out of the website, perform some inherit logic of the application, and even more. If you guys know any other way to do this, I'll be very thankful to know as well.

### What does the proposed API look like?
So, this is what AngularJS documentation talks about the event that I've mentioned:

> $destroy()
>
> Removes the current scope (and all of its children) from the parent scope. Removal implies that calls to $digest() will no longer propagate to the current scope and its children. Removal also implies that the current scope is eligible for garbage collection.
>
> The $destroy() is usually used by directives such as ngRepeat for managing the unrolling of the loop.
>
> Just before a scope is destroyed a $destroy event is broadcasted on this scope. Application code can register a $destroy event handler that will give it chance to perform any necessary cleanup.

I don't think I have enough knowledge to suggest a simple solution for this issue, or to write some code that can be used in way to implement this kind of feature, but my idea is to have something similar to this in the vuejs framework.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
