### ISSUE TITLE
why my custom elements such as 'view', 'text' are not show?

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#11123]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/t9fyx82u/5/](https://jsfiddle.net/t9fyx82u/5/)

### Steps to reproduce
nothing to do.

### What is expected?
view and text will be shown, just like view2 and text2.

### What is actually happening?
view and text in the #app are not show，but they can be displayed outside of #app

**Comment by posva** [comment]
`text` and `view` are reserved tags for SVG. It has a special meaning and that's why it shouldn't be used as a component name

**Comment by aweiu** [comment]
> `text` and `view` are reserved tags for SVG. It has a special meaning and that's why it shouldn't be used as a component name

but they can be displayed outside of #app，i want to known why？I check it in chrome dev tool，they are all in the dom tree，but not display inside of #app

**Comment by posva** [comment]
Oops, didn't mean to close it but I also forgot to add the labels.

They are not HTML elements, they are for SVG, I think that's why they are not visible. Maybe we could detect if the element is inside of an SVG and change based on that. Either way, Using non-standard HTML elements is something that should be avoided.

**Comment by aweiu** [comment]
> Oops, didn't mean to close it but I also forgot to add the labels.
> 
> They are not HTML elements, they are for SVG, I think that's why they are not visible. Maybe we could detect if the element is inside of an SVG and change based on that. Either way, Using non-standard HTML elements is something that should be avoided.

so，I want to know how Vue makes them not show? They have been rendered into the dom。

**Comment by Justineo** [comment]
Currently Vue creates known SVG elements with [`document.createElementNS`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS).
