### ISSUE TITLE
No Inlining of Critical CSS by bundleRenderer

### ISSUE THREAD

**Issue by sns45** [vuejs/vue#11127]
### Version
2.6.11

### Reproduction link
[https://github.com/eddyerburgh/vue-hackernews](https://github.com/eddyerburgh/vue-hackernews)

### Steps to reproduce
1. Build and Start the project (npm run build && npm run start) 
2. View source the http://localhost:8080

### What is expected?
Inline styles in head section should appear like this:

```
<style data-vue-ssr-id="4e49db98:0 ba2f7d08:0">.news-view{padding-top:45px}.news-list,.news-list-nav{background-color:#fff;border-radius:2px}.news-list-nav{padding:15px 30px;position:fixed;text-align:center;top:55px;left:0;right:0;z-index:998;box-shadow:0 1px 2px rgba(0,0,0,.1)}.news-list-nav a{margin:0 1em}.news-list-nav .disabled{color:#ccc}.news-list{position:absolute;margin:30px 0;width:100%;transition:all .5s cubic-bezier(.55,0,.1,1)}.news-list ul{list-style-type:none;padding:0;margin:0}.slide-left-enter,.slide-right-leave-to{opacity:0;transform:translate(30px)}.slide-left-leave-to,.slide-right-enter{opacity:0;transform:translate(-30px)}.item-enter-active,.item-leave-active,.item-move{transition:all .5s cubic-bezier(.55,0,.1,1)}.item-enter,.item-leave-active{opacity:0;transform:translate(30px)}.item-leave-active{position:absolute}@media (max-width:600px){.news-list{margin:10px 0}}
.news-item{background-color:#fff;padding:20px 30px 20px 80px;border-bottom:1px solid #eee;position:relative;line-height:20px}.news-item .score{color:#f60;font-size:1.1em;font-weight:700;position:absolute;top:50%;left:0;width:80px;text-align:center;margin-top:-10px}.news-item .host,.news-item .meta{font-size:.85em;color:#828282}.news-item .host a,.news-item .meta a{color:#828282;text-decoration:underline}.news-item .host a:hover,.news-item .meta a:hover{color:#f60}</style>
```

There should be inline styles in head section like its on here:
https://vue-hn.herokuapp.com/top

### What is actually happening?
Only link tags are outputted by the server. 
No inlining of critical CSS.

---
I am using vue-cli to configure SSR build. 
Why is the bundle renderer not inlining the critical css? I want to reduce network calls so I am experimenting with inlining some critical css in order to improve the performance. 

Also as a side note, can we have an official vue-hackernews with SSR capabilities utilizing vue-cli.

**Comment by posva** [comment]
Critical CSS has to be configured: https://ssr.vuejs.org/guide/css.html
Maybe you can find CLI plugins like https://github.com/Akryum/vue-cli-plugin-ssr that do it for you. You also have Nuxt.js doing it automatically for you.

A remake of https://github.com/vuejs/vue-hackernews-2.0 using the CLI could be nice, indeed, we are open for pull requests there
