### ISSUE TITLE
v-model.lazy not working properly when mousedown event causes another part of the component to re-render

### ISSUE THREAD

**Issue by tcummin2** [vuejs/vue#11135]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/ynhzuacw/6/](https://jsfiddle.net/ynhzuacw/6/)

### Steps to reproduce
1. Change the input value to different text without unfocusing the input
1. Mousedown on the 'Toggle on/off' button

### What is expected?
The changed text value should be kept after the input is unfocused.

### What is actually happening?
The mousedown event changes the state of the component so that it renders the state of the button to 'on' or 'off' which overwrites anything that has changed in the lazy input field.

---
Any mousedown that doesn't re-render a different part of the component works fine. In the reproduction above, removing the div that shows the state of the button results in expected behavior.

Worked properly until 2.6.0.

**Comment by posva** [comment]
Please see https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd (from the release https://github.com/vuejs/vue/releases/tag/v2.6.0)
