### ISSUE TITLE
don't work ssr with esm build 

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue#11130]
### Version
2.6.11

### Reproduction link
no

### Steps to reproduce
use rollup esm build with rollup-plugin-vue
use components
use async components <-- error

### What is expected?
Ssr with async components

### What is actually happening?
error 
TypeError: Cannot add property _Ctor, object is not extensible

---
Don't work esm rollupjs build with ssr and async component, because

this code in 'vue-server-renderer'
```js
function renderAsyncComponent (node, isRoot, context) {
  var factory = node.asyncFactory;

  var resolve = function (comp) {
    if (comp.__esModule && comp.default) { // don't work with native esm in nodejs
      comp = comp.default;
    }
...
```
node 13.8

**Comment by ariran5** [comment]
one solution is to check Symbol (Symbol.toString Tag): "Module"

```js
if (comp.__esModule && comp.default || comp[Symbol.toStringTag] === 'Module') {
    comp = comp.default;
}
```

**Comment by posva** [comment]
Please, provide a reproduction when reporting a bug as well as reproduction steps. Open a new issue with a boiled down reproduction. It can be a GitHub repository, since it seems to be related to node with esm. To create a basic ssr reproduction (with no webpack or loader), you can use https://ssr.vuejs.org as a starting point

**Comment by ariran5** [comment]
@posva I already did all the work, found the bug and showed how to solve it

**Comment by ariran5** [comment]
@posva Next, please do it yourself

**Comment by posva** [comment]
Please read the indications given at https://new-issue.vuejs.org/?repo=vuejs/vue and be respectful when interacting with maintainers
