### ISSUE TITLE
Add support esm dynamic imports on ssr

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue#11134]
### What problem does this feature solve?
Today SSR not support esm async components, but I would like to use this opportunity

### What does the proposed API look like?
Vue API looks unchanged. You need to add support for this feature inside vue-server-renderer

**Comment by posva** [comment]
Please, as said in [the other issue](https://github.com/vuejs/vue/issues/11130#issuecomment-588989787), do the things properly and provide a boiled down sample repro of what you are trying to do instead of trying to get around the system because this is not as helpful as you might think it is
