### ISSUE TITLE
List Move Transitions sometimes never "finish"

### ISSUE THREAD

**Issue by hognevevle** [vuejs/vue#11144]
### Version
2.6.11

### Reproduction link
[https://codepen.io/hognevevle/pen/PoqbZrv](https://codepen.io/hognevevle/pen/PoqbZrv)

### Steps to reproduce
The issue manifests itself in conjunction with QIntersection component of Quasar. Said component is used to only load elements into the DOM that are actually visible in the viewport. 

When using List Move Transitions, when elements are rearranged and moved into the viewport, there are odd cases where the element is however _not_ inserted into the DOM.  According to the Quasar team, this is happening because v-move never finishes with the transition.

See https://github.com/quasarframework/quasar/issues/6463 for repro details

### What is expected?
The transition should always finish

### What is actually happening?
The transition doesn't finish under certain unknown conditions 

---
Issue described more in detail in https://github.com/quasarframework/quasar/issues/6463

**Comment by posva** [comment]
When reporting a bug, please provide a boiled down repro (no external dependencies like Quasar) to ensure the problem comes from Vue.
Open a new issue if you manage to boil down the issue to only Vue
