### ISSUE TITLE
The Vue.js does not execute the command despite the correct encoding

### ISSUE THREAD

**Issue by daniel-EG** [vuejs/vue#11148]
### Version
2.6.11

### Reproduction link
[https://danieleg.000webhostapp.com/vue/vue/slug.html](https://danieleg.000webhostapp.com/vue/vue/slug.html)

### Steps to reproduce
var app = new Vue({

el: '#daniel-app',

data: {

inPut: '',

outPut: '',

buttonText: 'fab fa-telegram-plane',

clarification: 'Convert the title to Slug'

},

methods: {

convertToSlug () {

var theSlug = this.inPut;

// [1] Convert the post title to lowercase

theSlug = theSlug.toLowerCase();

// [2] Replace spaces with a dash

theSlug = theSlug.replace(/\s /g, '-');

// [3] Replace ampersand with a dash

theSlug = theSlug.replace(/&/g, '-');

// [4] Replace 2 dashs with nothing

theSlug = theSlug.replace(/--/g, '');

// [5] Delete a dash in end and first post title

var firstDash = theSlug.charAt(0);

var endDash = theSlug.charAt(theSlug.length - 1);

if (firstDash === '-' && endDash === '-') {

theSlug = theSlug.replace(firstDash, '');

theSlug = theSlug.replace(endDash, '');

} else if (firstDash === '-') {

theSlug = theSlug.replace(firstDash, '');

} else if (endDash === '-') {

theSlug = theSlug.replace(endDash, '');

}

// Add result post title to output

if (this.outPut === theSlug) {

this.outPut = '';

this.buttonText = 'fab fa-telegram-plane';

this.clarification = 'Convert the title to Slug';

} else if (this.buttonText === 'fas fa-times') {

this.outPut = '';

this.buttonText = 'fab fa-telegram-plane';

this.clarification = 'Convert the title to Slug';

} else {

this.outPut = theSlug;

this.buttonText = 'fas fa-times';

this.clarification = 'Delete this slug';

console.log(endDash);

}

}

}

});

Preview: https://danieleg.000webhostapp.com/vue/vue/slug.html

### What is expected?
Convert a dash at the beginning of the title to nothing
And turn a dash at the end of the title to nothing

### What is actually happening?
When trying to replace a dash at the beginning of the title to nothing, this happens
But when converting a dash at the end of the address to nothing, this does not happen

---
The exact error here:

// [5] Delete a dash in end and first post title

var firstDash = theSlug.charAt(0);

var endDash = theSlug.charAt(theSlug.length - 1);

if (firstDash === '-' && endDash === '-') {

theSlug = theSlug.replace(firstDash, '');

theSlug = theSlug.replace(endDash, '');

} else if (firstDash === '-') {

theSlug = theSlug.replace(firstDash, '');

} else if (endDash === '-') {

theSlug = theSlug.replace(endDash, '');

}

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
