### ISSUE TITLE
Computed property not recomputed

### ISSUE THREAD

**Issue by tonai** [vuejs/vue#11154]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-computed-properties-hnwo9](https://codesandbox.io/s/vue-computed-properties-hnwo9)

### Steps to reproduce
Click on the Next/Prev buttons of the first component

### What is expected?
The offset value should update like for the second component

### What is actually happening?
Nothing, the computed value is not recomputed automaticaly when the data is updated.

**Comment by posva** [comment]
`$refs` are [not reactive](https://github.com/vuejs/vue/issues/3842#issuecomment-514981401) so in your _KO_ example, the computed property doesn't depend on anything because the first time it runs the `$refs` is not populated so it doesn't depend on the `current` variable. To workaround this, you can access the variable:

```js
vm.current
return vm.$refs["item"] ? vm.$refs["item"][vm.current].offsetLeft : 0
```

**Comment by tonai** [comment]
Thank @posva for your answer.
I also found my self that adding a reference to `vm.current` before the return statement seems to do the trick.

But it feels weird.
I don't really understand why this is happening.
How computed properties are linked with their dependencies ?
What properties are considered reactive or not ?
Is there some information somewhere ?

Thanks,

**Comment by sirlancelot** [comment]
Most properties in Vue.js are Reactive. All properties returned by the `data` configuration are traversed and watched, `props` and `computed` are watched as well. Have a look at [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html) in the documentation. In the API documentation you will notice that `$refs` and `provide`/`inject` are really the only non-reactive values that you'd encounter on the daily (just off the top of my head, I could be missing some).

**Comment by tonai** [comment]
Thanks for the explanations and the link @sirlancelot
