### ISSUE TITLE
Passing `this` to an event handler causes undefined behaviour

### ISSUE THREAD

**Issue by SilverRampart** [vuejs/vue#11150]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/7hf0eL4p/1/](https://jsfiddle.net/7hf0eL4p/1/)

### Steps to reproduce
Click the check button repeatedly

### What is expected?
The text toggles back and forth between `true` and `false`

### What is actually happening?
The text toggles to `false`, then stays there.

---
It seems that passing `this` to an event handler disrupts all subsequent Vue event handling. Please clarify what, if any, is the correct behaviour here, and maybe update the docs.

**Comment by posva** [comment]
You should not use `this` in the template because the value of it changes. In your case use `$event.target`
The behavior you are seeing changes based on Browsers (setting the value at the same time it is clicked). In other words, it's a browser quirk and it should be avoided
