### ISSUE TITLE
Changing an object/list also changes other objects/lists if those got their initial value from the same variable.

### ISSUE THREAD

**Issue by freddyys** [vuejs/vue#11155]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/bf0qo19m/](https://jsfiddle.net/bf0qo19m/)

### Steps to reproduce
I've added buttons in the jsfiddle to add a value to the first list and change the message of the first object.

### What is expected?
The value of the second list/object doesn't change when the first list/object changes.

### What is actually happening?
When changing the first list or object the second one changes as well.

---
The provided jsfiddle is a simplified version of a problem I've ran into quite a few times now. It functions the same so it should demonstrate the problem.

I ran into the problem when i tried to save the same info from axios request in two different objects. One to keep track of the state in the database and another for user to alter. This way the two can be compared if needed. However changing one of the two objects also changed the other. So there is no way to now what the original state was.

**Comment by posva** [comment]
Unfortunately, this is how JS works. You will need to create a copy of objects in order to make them different. Vue adds reactivity on top of them

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
