### ISSUE TITLE
vue throw unhandled error when update template

### ISSUE THREAD

**Issue by luoway** [vuejs/vue#11151]
### Version
2.6.11

### Reproduction link
[https://luoway.github.io/vue-bug-report/index.html](https://luoway.github.io/vue-bug-report/index.html)

### Steps to reproduce
0. **import vue from CDN**
1. set `@click=undefined` on any element in the template
2. update any data to fire render
3. see unhandled error in console

### What is expected?
The template is updated successfully.

### What is actually happening?
Vue throws unhandled error, and stops running.

---
View demo code: https://github.com/luoway/vue-bug-report/blob/master/index.html

When I updated the version of vue from 2.4.x to 2.6.x，this unhandled error happened, and the code stopped running.

**Comment by posva** [comment]
The dev version shows a warning about it. When using a template, the compiler is able to help a bit more but valid event handlers should be passed to event listeners and `undefined` is not one

**Comment by luoway** [comment]
@posva I know dev version warned, but the unhandled error is unexpected, and the old version (for example 2.4.4) works fine.
When I am developing, errors can be found. But I am updating vue version in the production, it's not ease to test everything.
I think vue can support **undefined** event handler, as vue used to do.

**Comment by luoway** [comment]
this issue is about the Error:
TypeError: Cannot read property '_wrapper' of undefined

maybe someone will search the keywords and find here in the future. Just like what happened to me.

**Comment by luoway** [comment]
Oh...
It's my first pull request. 
I've tried to make one commit to solve the problem.
