### ISSUE TITLE
function render cause component keep-alive

### ISSUE THREAD

**Issue by nowdothat** [vuejs/vue#11161]
Version
2.5.17

Reproduction link
https://codesandbox.io/s/stupefied-wind-hwnle?fontsize=14&hidenavigation=1&theme=dark

Steps to reproduce
1.switch other radio
2. Vue function render different components
3. select Data not reset

What is expected?
I want to each Render , give me a new Component . but now give me a old component When he did execute render methods

What is actually happening?
only render another one components . old component will reset show

**Comment by LinusBorg** [comment]
components are re-used where possible. to create new component instances, use a `key`

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

```javascript
export default {
  name: "functional-x",
  functional: true,
  render(createElement, context) {
    console.log(context.props.switchParams);
    switch (context.props.switchParams) {
      case "x1":
        return createElement("div", {}, "哈喽");
      default:
        return createElement(slectGroup, {
          key: context.props.switchParams
        });
    }
  }
};
```
