### ISSUE TITLE
e2e "modal" test fail

### ISSUE THREAD

**Issue by marcosvidolin** [vuejs/vue#11168]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/test/e2e/specs/modal.js](https://github.com/vuejs/vue/blob/dev/test/e2e/specs/modal.js)

### Steps to reproduce
npm run test:e2e -- --env phantomjs

### What is expected?
assert.cssClassPresent('.modal-mask', 'modal-enter-active')

### What is actually happening?
There is no "modal-enter-active" class at this moment.

---
Maybe the "waitFor" time it's wrong

**Comment by posva** [comment]
The test is working
