### ISSUE TITLE
[Enhancement] Allow events to be emitted to children

### ISSUE THREAD

**Issue by Garanaw** [vuejs/vue#11164]
### What problem does this feature solve?
Currently I'm working on a RPG Character Creator for an editorial. The character counts with several properties, among which there are a Social Position, a Monthly Incoming (based upon the Social Position) and, at last, the Character Traits. 
One of these relates on the mentioned Social Position, downgrading it by 1. This afects the Incomings, which will have to be recalculated based on the new Social Position. In order to achieve this, I emit an event from my CharacterTraits component to the App, then change a property binded into my Incomings component from false to true, and this fires a watcher that sends a request to the backend with the new situation, receives the new monthly incomings and recalculates them. Once this is done, I need to emit another event to make sure that the binded property goes back to false in case the same Character Trait is rolled, so it can be recalculated again (initially that was a bug I discovered).
In the meantime, the user is still allowed to keep rolling his character's traits, and in some cases (a very unlucky guy), it can happen that the same trait is rolled before the first one has finished, therefore, the "recalculate" property didn't have the time to be reset to false, leading to a bug in which the new Incomings value cannot be calculated due to the property being still false, as it relies on an async call.
With a parent-to-children event emitter, this can be avoided by just firing the event without the need of properties being changed so they can communicate freely. In this specific case, the async request can be just cancelled and re-sent with the new (third) situation.
This can potentially change the way that components communicate, I'm aware of that, but for some specific use cases (such as this one), it can avoid bugs and improve the user experience.
I have seen some ways to deal with this, relying on the child component having a $ref, and calling the child component's method from the parent though this $ref property, but it doesn't seem very clean to me, and also it's a bit confusing.

### What does the proposed API look like?
```
// Parent component
this.$emitToChildren('event', properties)

// Children
export default {
    on: {
        event: (properties) => {
            this.handleEvent(properties);
        }
    }
};
```

**Comment by posva** [comment]
Events are meant to go up while props are passed down. This pretty much goes against that principle.

You can indeed add a ref on a component and call a method if that matches more your use case

**Comment by Garanaw** [comment]
> You can indeed add a ref on a component and call a method if that matches more your use case

My concern about this workaround is the coupling between the components. Currently I'm using properties being passed to children, but I still support this feature because of that reason: coupling between components
