### ISSUE TITLE
v-model binding does not update with html form reset event

### ISSUE THREAD

**Issue by kodintaylor** [vuejs/vue#11175]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/4hp6fdqt/](https://jsfiddle.net/4hp6fdqt/)

### Steps to reproduce
create a custom input component inside a basic html form with a v-model binding for its value. input text into the field and reset the form with an html reset button. (as demonstrated in the jsfiddle)

### What is expected?
text is cleared in the input field, displayed text from the bound value is also cleared

### What is actually happening?
 text is cleared in the input field, but not cleared in the data binding. previous text is still visible

---
I saw some other bug reports with this issue that were all closed with various reasonings that mostly came down to "working as designed, keep the data model up to date yourself". I really think this is something vue should be taking care of.

**Comment by posva** [comment]
This is expected behavior because there is no way to reset everything used on the forms. So you need to manually listen to the reset event on the form to do it
