### ISSUE TITLE
Custom input: char is appended to input field if value didn't change

### ISSUE THREAD

**Issue by ByScripts** [vuejs/vue#11172]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-input-problem-u63jn](https://codesandbox.io/s/vue-input-problem-u63jn)

### Steps to reproduce
1. Enter a char in the input field.
2. Enter another (different) char. The char is replaced.
3. Enter the same char twice (or more)... The char is appended. But the model value is correct.

### What is expected?
When entering a same char again, the input field shouldn't change.

### What is actually happening?
When entering a same char again, the char is appended in the input field.

**Comment by douglas-pires** [comment]
This is not a bug. The method `handleInput` is emitting `$event.data`. The correct is to send `$event.target.value` if you change to that, it should work as expected, but not on the second input, where you are forcing to replace with an empty string.

**Comment by ByScripts** [comment]
The intention is to have an input field capturing the entered char. It's why I send `$event.data`.

If I type `A`, i want it to show `A`. Then in the same field, if I type `B`, i want the `A` to be replaced with `B`. And it works as is.

But if it shows `A` and I type `A` again, it will show `AA`... which seems to be a strange behavior.

**Comment by posva** [comment]
Since the prop doesn't change when repeating the entered value, Vue doesn't renders the input again, so it seems like the value is being appended.

You can either call `this.$forceUpdate()` or manually update the value of the input to constrain it.
