### ISSUE TITLE
Vue parent component not re-rendering when computed properties are changing

### ISSUE THREAD

**Issue by rachitpant** [vuejs/vue#11183]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/elastic-fast-t3pti?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/elastic-fast-t3pti?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1) click on the Vue Message link - A new bootstrap modal will show
2) then hit reply - Another bootstrap modal will show- This modal is wrapped inside component newMessage.vue
3) then type ‘Test’ in the To field and then select ‘Test User’ from the drop down. The selected user wont show until you click the checkbox - Schedule later.

### What is expected?
As soon as you select `Test User` and the computed property in parent component `newMessage` changes , the component should re-render and it should cause this property to be passed down to child Component.

### What is actually happening?
The components computed property changes , but the component does not re-render.
Interestingly , when I check/uncheck the "Schedule later" checkbox , the component's data changes and then it re-renders - which results in the new value of the computed value also being passed down and shown.

**Comment by posva** [comment]
Please, make sure to boil down reproductions when reporting a bug so they do not contain external dependencies apart from Vue (like bootstrap, date time and vuex)

---
Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by rachitpant** [comment]
If you take a look at the above codesandbox , you would see vuex store has just dummy hard coded data, and external dependencies dont make a difference here. The componen'ts computed property do change , just that its not reacting to the change , until its data also changes.  I spent more than an hour creating my first code sandbox repo.
