### ISSUE TITLE
Render vuejs in v-html

### ISSUE THREAD

**Issue by lboquan** [vuejs/vue#11186]
I'am developing a web app with golang, axios and vuejs. In my web pages, I have multiple menu items in the left. When user clicks in some menu item, an axios post will be called and render a page contains vuejs syntax and script to a div (bind with v-html) in the right part. However, the vuejs syntax is not rendered. Neither are the scripts being executed. Is there any way to render a vuejs syntax based page and display in div binded with v-html?

**Comment by Choy-Mutao** [comment]
> I'am developing a web app with golang, axios and vuejs. In my web pages, I have multiple menu items in the left. When user clicks in some menu item, an axios post will be called and render a page contains vuejs syntax and script to a div (bind with v-html) in the right part. However, the vuejs syntax is not rendered. Neither are the scripts being executed. Is there any way to render a vuejs syntax based page and display in div binded with v-html?

may be you could set <div style="width: 100px, height: 100px">  to have a try
