### ISSUE TITLE
change props data makes father and child component render

### ISSUE THREAD

**Issue by zhsonga** [vuejs/vue#11188]
### Version
2.5.2

### Reproduction link
[https://jsbin.com/xoqaras/edit?html,css,js,console,output](https://jsbin.com/xoqaras/edit?html,css,js,console,output)

### Steps to reproduce
click the changeArr 

### What is expected?
just  the child component render  or no one render

### What is actually happening?
child and father both render

---
use Array function make the watcher notify

**Comment by posva** [comment]
This is expected because any change in a variable used in a template requires the whole template to rerender

**Comment by zhsonga** [comment]
if the arr is sting,  and change it in child, the father component will not rerender and get the warn,
the array use = get new value get the same situation, use Array function or Vue.set() get different situation, the different between them is the watcher in deps, the props data arr get father and child watcher,the new [] just get child watcher and replace before,
[new eg](https://jsbin.com/mixased/edit?html,css,js,console,output)
i get the different result  so i commit this issue
and thank you
