### ISSUE TITLE
Ability to choose wich parent template v-slot reference

### ISSUE THREAD

**Issue by kevinrioupsq** [vuejs/vue#11187]
### What problem does this feature solve?
In case I have a component (A) with 3 slots and an other one (B) in one of the slot, I want to reference a slot of the A component in the default slot of the B component

Example:
```html
<template>
  <p-page
    title="My page"
  >
    <!-- Component that give function to call when using the favorite menu -->
    <functional-component v-slot="{apply, save}">
      <!-- Next slot is a slot of my p-page -->
      <template v-slot:header>
        <p-favorites-menu
          :on-apply="apply"
          :on-save="save"
        />
      </template>
    </functional-component>
    <!-- ... -->
  </p-page>
</template>
```
The problem is that the template with `v-slot:header` is searching a slot in my `functionnal component` not in the `p-page` component

### What does the proposed API look like?
My idea is that, change the v-slot like this `v-slot:[parent_ref]:[slot_name]="..."` and if it's the direct parent just omit the `[parent_ref]` 
The example look now like
```html
<template>
  <p-page
    title="My page"
    ref="page"
  >
    <!-- Component that give function to call when using the favorite menu -->
    <functional-component v-slot="{apply, save}">
      <!-- Next slot is a slot of my p-page -->
      <template v-slot:page:header>
        <p-favorites-menu
          :on-apply="apply"
          :on-save="save"
        />
      </template>
    </functional-component>
    <!-- ... -->
  </p-page>
</template>
```

I'm sorry if a solution already exist, I missed it, thanks to inform me ;)

**Comment by posva** [comment]
This is the kind of things that composition api solve by removing the need of having a component to encapsulate logic. The more components like `functional-component` that are used this way at the same time, the more the composition api makes sense and removes template boilerplate

Adding this logic with yet another syntax is rather complicating things more than simplifying them.

When using components that only encapsulate a bit of logic, you need to put them on the outside (here p-page):

```vue
<template>
  <!-- Component that give function to call when using the favorite menu -->
  <functional-component v-slot="{ apply, save }">
    <p-page title="My page" ref="page">
      <!-- Next slot is a slot of my p-page -->
      <template v-slot:header>
        <p-favorites-menu :on-apply="apply" :on-save="save" />
      </template>
      <!-- ... -->
    </p-page>
  </functional-component>
</template>
```

Given that this is solved with composition api and that this creates an inferior, yet more difficult to use syntax, I don't think this is worth pursuing.

**Comment by kevinrioupsq** [comment]
Oki, thank you, I have to practice composition API to see how ;)

Have a nice day and be happy
