### ISSUE TITLE
vue 概率性出现vue官方内部库报错，vnode tagName is img, but vnode.elm is TextNode, Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by h330894169** [vuejs/vue#11181]
### Version
2.6.11

### Reproduction link
[https://film.qq.com/x/credit_mall/?ptag=vue](https://film.qq.com/x/credit_mall/?ptag=vue)

### Steps to reproduce
打开页面，不停的刷新页面，概率性出现

### What is expected?
Cannot read property 'indexOf' of undefined

![image](https://user-images.githubusercontent.com/17446782/75957039-27252b80-5ef4-11ea-8086-590010db37ca.png)

![image](https://user-images.githubusercontent.com/17446782/75956994-1379c500-5ef4-11ea-9e2c-37bd449d8d7f.png)

![image](https://user-images.githubusercontent.com/17446782/75957019-1e345a00-5ef4-11ea-9ba4-26e49f0be2aa.png)

### What is actually happening?
应该正常显示

---
vnode tagName is img, but vnode.elm is textNode

**Comment by Justineo** [comment]
这不是一个合法的重现。参见[说明](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro)。

**Comment by jeromehan** [comment]
![Uploading image.png…]()
为什么我捕捉的是你们 https://wuji.video.qq.com/fcgi-bin/wuji?appid=1000530&appkey=aa8ff64a84bc475c8d26dec263e5010a&exclude=_id,_ctime,_mtime&size=100&_=1583393950140 这个接口报错了。。。
