### ISSUE TITLE
questions about accessing 'this' in asynchronous components is undefined

### ISSUE THREAD

**Issue by zhoutengshen** [vuejs/vue#11193]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/friendly-lake-s93kz](https://codesandbox.io/s/friendly-lake-s93kz)

### Steps to reproduce
my code like this;

```
<template>
	<DynamicHome class="HomeIndex"/>
</template>
<script>
	const isPc = document.body.clientWidth >= 700;
	const path = isPc ? './HomePc' : './HomeMobile';
	export default {
		name: 'Home',
		components: {
			// https://webpack.js.org/api/module-methods/#import
			'DynamicHome': () => {
				/* eslint-disable*/
				console.log('i am DynamicHome => "this" is =>'   this); // this is my question why 'this' is undefined;
				return import(`${path}`);
			}
		},
	};
</script>

```

### What is expected?
i wan 'this' is a instance of Vue

### What is actually happening?
this is undefined

**Comment by sirlancelot** [comment]
Arrow functions in JavaScript don't give you access to `this`. Use a normal function. An async component factory won't get anything useful passed as `this` though since nothing has been initialized yet when that function gets called.

**Comment by Justineo** [comment]
What @sirlancelot said.
