### ISSUE TITLE
conditional root template in .vue file

### ISSUE THREAD

**Issue by derMart** [vuejs/vue#11198]
### Version
2.6.11

### Reproduction link
https://github.com/vuejs/vue-issue-helper/issues/49

### Steps to reproduce
Not sure if this applies to vue or vue-loader. It seems v-if statements are not processed correctly when inside a root template tag.
Suppose you have the following .vue file:
```
<template v-if="true">
  <p>test</p>
</template>
<template v-else>
  <p>test2</p>
</template>
```

### What is expected?
The test2 paragraph should be rendered as v-if is true (also tested with other more complicated truthy conditions)

### What is actually happening?
The test paragraph is rendered.
It seems always the last template tag, having either v-else or any v-else-if statement is rendered, even if that v-else-if condition is false.

**Comment by posva** [comment]
This is not supported. You need to put the v-if on the p element and have one root template
Also note that template as the root:

```vue
<template>
  <template v-if="condition">
  ...
  </template>
</template>
```

Is not supported either (you get a warning about it)

This shouldn’t be a problem with vue 3 as the one single element as the root rule is not longer there

**Comment by derMart** [comment]
Could you please reopen this bug? It is not fixed, thank you very much!

**Comment by derMart** [comment]
Ok, thank you.
Could you please update the documentation of vue 2.x to include this limitation? I have not seen it anywhere documented.

**Comment by sirlancelot** [comment]
Documentation is here: https://vuejs.org/v2/guide/components.html#A-Single-Root-Element

Note that conditionals on the root *are* supported, the only caveat is that every branch of the conditional *must* resolve to a single element. An empty `<div v-else />` should do the trick if you don't want to render anything.

**Comment by derMart** [comment]
Thank you very much. I know of the single root requirement, but the problem above is exactly of the nature you describe. Every branch resolves to a single component, even to the same component (p tag), but still the conditions are not resolved correctly.
Here is finally the example above on codesandbox: https://codesandbox.io/s/sad-benz-d69xb
There, as stated above test2 is rendered instead of test

**Comment by sirlancelot** [comment]
```vue
<template v-if="true">
  <p>test</p>
</template>
<template v-else>
  <p>test2</p>
</template>
```

Should be:
```vue
<template>
  <p v-if="true">test</p>
  <p v-else</p>
</template>
```

Vue single file components should always have zero or one root `<template>` tag.
