### ISSUE TITLE
Problem with rendering content inside an SVG tag

### ISSUE THREAD

**Issue by wolandec** [vuejs/vue#11190]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/prod-violet-4f5be](https://codesandbox.io/s/prod-violet-4f5be)

### Steps to reproduce
Just use a link to minimal reproduction.

### What is expected?
"Text from Second.vue" to be appear.

### What is actually happening?
"Text from Second.vue" doesn't appear.

---
In this https://codesandbox.io/s/jovial-violet-qbok9 example I create SVG dynamically with no Vue use and the text "Hello" appears.

Even more weird content: if I add anything in body tag using Chrome devtools, then text shows up.
https://www.youtube.com/watch?v=TxL5olpWqT4

**Comment by posva** [comment]
`div` is not allowed inside of an svg. I'm not sure why you see them appearing when editing the HTML but that seems to be a browser bug. If you write a `div` inside of an `svg`:

```html
<svg
      width="200"
      height="200"
      xmlns="http://www.w3.org/2000/svg"
      version="1.1"
      xmlns:xlink="http://www.w3.org/1999/xlink"
    >
      <div>Hello from html</div>
    </svg>
```

in plain html, you will see the div content is not visible even if it is in the DOM

**Comment by wolandec** [comment]
Ok, that is right and I know it, but actually this case began here https://github.com/LinusBorg/portal-vue/issues/290 . So after all, content ported from svg into ordinarry DOM element, and doesn't show up either. Why?
