### ISSUE TITLE
Using namespace in component name, Vue reports: Component names should conform to valid custom element name in html5 specification.

### ISSUE THREAD

**Issue by wxiaoguang** [vuejs/vue#11204]
### Version
2.6.11

### Reproduction link
[http://jsfiddle.net/posva/9humt9c5/](http://jsfiddle.net/posva/9humt9c5/)

### Steps to reproduce
Open the sample

### What is expected?
Run without warning

### What is actually happening?
Warning in console:

```
[Vue warn]: Invalid component name: "foo:hey". Component names should conform to valid custom element name in html5 specification.
```

**Comment by wxiaoguang** [comment]
Related issue: https://github.com/vuejs/vue/issues/5582#issuecomment-570890979

**Comment by posva** [comment]
It's because the colon (`:`) is not a valid character per html spec and is excluded from the validation: https://www.w3.org/TR/html53/semantics-scripting.html#potentialcustomelementname
https://github.com/vuejs/vue/blob/dev/src/core/util/lang.js#L8
