### ISSUE TITLE
optimize: some code will never run

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue#11208]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/rezawekici/1/edit?js,console](https://jsbin.com/rezawekici/1/edit?js,console)

### Steps to reproduce
because for...in only get enumerable property and Object.prototype.watch's enumerable is false. so some code will never run. 

### What is expected?
delete the two line code

### What is actually happening?
they still there

---
please test the case in FireFox

**Comment by posva** [comment]
This is not a bug report. [`Object.watch` should not be used](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch)

**Comment by Cuixote** [comment]
I know it's not a bug, but I don't understand what you mean. I think you may take a closer look at my suggestions.
