### ISSUE TITLE
To do list not works fine for high version

### ISSUE THREAD

**Issue by MoonChaserChen** [vuejs/vue#11202]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/aq5npz42/](https://jsfiddle.net/aq5npz42/)

### Steps to reproduce
Just click the to do list(not the last one)

### What is expected?
finished or unfinished task filtered correctly

### What is actually happening?
checked status of tasks not right.

---
I want to make a to do list using computed   filter.

I use `<input type="checkbox" v-model="finishStatus"><span>Show finished</span>` to view finished or unfinished task.

when I use a low version of 2.0.3(which is commented in the code), it works fine. But when i change to `https://cdn.jsdelivr.net/npm/vue`(current version is v2.6.11), it does not act as expected(as for checked status of tasks).

**Comment by posva** [comment]
Please check https://github.com/vuejs/vue/releases/tag/v2.6.0 and the important changes concerning nextTick https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

Using a key attribute unique to the todo will fix the behavior in your case
