### ISSUE TITLE
Add stagger to transition-group

### ISSUE THREAD

**Issue by theArtechnology** [vuejs/vue#11210]
### What problem does this feature solve?
stagger props can be useful when using third party css libraries or own css. It will considerably helps when using 3rd party css libraries, as many do not include stagger animation.

### What does the proposed API look like?
`<transition-group appear stagger></transition-group>`.

This can include props like:

stagger : basic linear staggering from first child to last,

stagger-reverse: same as the first one but starting from the last

stagger-random: randomly apply animation to children.

stagger-duration: add a duration before applying a css to the child,

stagger-on-event: apply animation an emitted from a child first then apply stagger on the rest.

we add it with appear, when the list in show the css is applied.

`<transition-group appear  stagger-reverse name="slide-up"></transition-group>`

`<transition-group appear  stagger-reverse stagger-duration="500"  name="slide-up"></transition-group>`

`<transition-group stagger stagger-random stagger-duration="500"  name="slide-up "></transition-group>`

`<transition-group stagger stagger-on-event="selected" stagger-duration="500"  name="slide-up "></transition-group>`

**Comment by posva** [comment]
Staggering transitions can be implemented in user land (https://vuejs.org/v2/guide/transitions.html#Staggering-List-Transitions)
