### ISSUE TITLE
v-if not working with <tbody>

### ISSUE THREAD

**Issue by devatquarxps** [vuejs/vue#11218]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/devatquarxps/yp6n1hcx/](https://jsfiddle.net/devatquarxps/yp6n1hcx/)

### Steps to reproduce
open the js fiddle link,
uncomment `Case 1` and comment `Case 2`

### What is expected?
v-if should be working with `<tbody>` HTML element tag

### What is actually happening?
v-if not working with `<tbody>`

**Comment by devatquarxps** [comment]
> ### Version
> 2.5.21
> 
> ### Reproduction link
> https://jsfiddle.net/devatquarxps/yp6n1hcx/
> 
> ### Steps to reproduce
> open the js fiddle link,
> uncomment `Case 1` and comment `Case 2`
> 
> ### What is expected?
> v-if should be working with `<tbody>` HTML element tag
> 
> ### What is actually happening?
> v-if not working with `<tbody>`

**Comment by posva** [comment]
See https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats
The HTML that Vue uses is different to what you wrote because the browser modifies it before
