### ISSUE TITLE
How to dynamically set several vue.js directives?

### ISSUE THREAD

**Issue by Myziura** [vuejs/vue#11212]
### What does the proposed API look like?
I see this something like this maybe __v-directives="{ 'mask': '###.###', 'loading'='isLoading' }"__

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

--

This is not doable in template and given how often directives are used compared to v-on/v-bind, you will have to create this behavior through a component written in JS using render function which allows you to set multiple directives

**Comment by Myziura** [comment]
Ok, sorry and thank you!
