### ISSUE TITLE
Vue CLI Typescript Starter is not debuggable

### ISSUE THREAD

**Issue by jawil003** [vuejs/vue#11228]
### Reproduction link
[https://github.com/jawil003/WillhubFrontendVue.git](https://github.com/jawil003/WillhubFrontendVue.git)

### Steps to reproduce
1. Install Vue CLI 3
2. Create new Project with Typescript, Eslint and Babel
3. Launch Example App.
4. Open Firefox Debugger
5. Go to Webpack->src and Search for a Component
6. See that it is weird and not equals your ts File.

### What is expected?
I can debug my Components under Webpack->src etc. 

### What is actually happening?
All I get is weird exports in a single line.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You probably need to activate a source map option but it might also be a problem of the scaffolding coming out of the cli (https://github.com/vuejs/vue-cli)
