### ISSUE TITLE
Memory leak caused by binding native events

### ISSUE THREAD

**Issue by AleynHe** [vuejs/vue#11227]
### Version
2.5.22

### Reproduction link
[https://jsbin.com/nacadexudi/edit?html,output](https://jsbin.com/nacadexudi/edit?html,output)

### Steps to reproduce
1. IE11、Chrome 79 - 80

1. Please use browser to open the jsbin page, which will automatically render the Vue instance

2. Click return. The memory occupied by the Vue instance has not been recycled

3. If you execute the code in clickfn directly in the chrome console, the Vue instance can be recycled

### What is expected?
Memory is recycled

### What is actually happening?
Memory leak

**Comment by smolinari** [comment]
Just FYI, Vue is at version 2.6.11. 

Scott

**Comment by AleynHe** [comment]
> Just FYI, Vue is at version 2.6.11.
> 
> Scott

Vue version 2.6.11 also exists.

**Comment by smolinari** [comment]
You mean the problem is still in version 2.6.11? @AleynHe 

Scott

**Comment by posva** [comment]
You cannot destroy a Vue instance without the Vue instance, you have to do it outside, the same way it is created outside. Given that keep in mind Vue will keep some caches but, the size remains constant after destroying and creating multiple times

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>TEST</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <button id="toggle">Toggle</button>
    <div id="_rootDiv"></div>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.js"></script>
  <script>
    let root = document.getElementById('_rootDiv')
    let vm
    document.getElementById('toggle').addEventListener('click', function() {
      if (vm) {
        let el = vm.$el
        vm.$destroy()
        root.removeChild(el)
        vm = null
      } else {
        let el = document.createElement('div')
        root.appendChild(el)
        vm = new Vue({
          el,
          template: `
      <div id="test">
        <button @click="clickFn">click</button>
        <input v-for="item in 10000" :value="item" />
      </div>
      `,
          methods: {
            clickFn() {}
          }
        })
      }
    })
  </script>
</html>
```

**Comment by AleynHe** [comment]
> You cannot destroy a Vue instance without the Vue instance, you have to do it outside, the same way it is created outside. Given that keep in mind Vue will keep some caches but, the size remains constant after destroying and creating multiple times
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="UTF-8" />
>     <title>TEST</title>
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>   </head>
> 
>   <body>
>     <button id="toggle">Toggle</button>
>     <div id="_rootDiv"></div>
>   </body>
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.js"></script>
>   <script>
>     let root = document.getElementById('_rootDiv')
>     let vm
>     document.getElementById('toggle').addEventListener('click', function() {
>       if (vm) {
>         let el = vm.$el
>         vm.$destroy()
>         root.removeChild(el)
>         vm = null
>       } else {
>         let el = document.createElement('div')
>         root.appendChild(el)
>         vm = new Vue({
>           el,
>           template: `
>       <div id="test">
>         <button @click="clickFn">click</button>
>         <input v-for="item in 10000" :value="item" />
>       </div>
>       `,
>           methods: {
>             clickFn() {}
>           }
>         })
>       }
>     })
>   </script>
> </html>
> ```

Less than 1 / 3 of memory recovery effect on IE 11.
