### ISSUE TITLE
Broken events on parent DOM elements in Chromium 79.0.3945.117

### ISSUE THREAD

**Issue by theusersimons** [vuejs/vue#11224]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/theusersimons/k9smeL2o/16/](https://jsfiddle.net/theusersimons/k9smeL2o/16/)

### Steps to reproduce
This can 't be reproduced just in the browser. We are developing an interface in a project that uses the chromium 79.0.3945.117 source code to create an in-game browser.

### What is expected?
Events on the parent DOM element and on child elements are expected to work normally.

### What is actually happening?
CEF stops correctly calculating the target DOM element that events are set to. For example if a click hangs on the parent element during this problem it does not extend to the entire element and the click only occurs on the final child element of the DOM.

---
This problem is observed with absolutely all events in the context of parent and child interaction. This problem started after version 2.5.22 of Vue. On all subsequent versions this problem exists, previously and including version 2.5.22 everything works fine.

**Comment by posva** [comment]
Please check https://github.com/vuejs/vue/releases/tag/v2.6.0 _Important Internal Changes_ section, specifically the `nextTick` one and the linked document in _Details_

BTW, please be more specific when reporting a bug about what steps one must do to reproduce the problem (eg move the cursor over the element, then move it out) and the same goes with _what is expected_, 2 logs, 1 log, etc
