### ISSUE TITLE
SCRIPT1028 Error in Edge Browser

### ISSUE THREAD

**Issue by jakubstankowski** [vuejs/vue#11222]
### Version
2.6.11

### Reproduction link
[https://qsc-dev.quasiris.de/admin/#/dashboard](https://qsc-dev.quasiris.de/admin/#/dashboard)

### Steps to reproduce
1. Go to Edge Browser

2. Go to https://qsc-dev.quasiris.de/admin/

3. Go to console log

4. See error - SCRIPT1028: Expected identifier, string or number
chunk-vendors.ee23aca6.js (1,1449)

### What is expected?
Vue aplication should working correctly in Edge browser

### What is actually happening?
In console log show error  - SCRIPT1028: Expected identifier, string or number
chunk-vendors.ee23aca6.js (1,1449)

---
My browser -  Microsoft Edge 44.18362.449.0 (without chromium engine)

I do a big research i found the reason - rest operator, but i can't find the solution

I also try find solution with babel package - https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread.html
module.exports = {
    presets: [
        '@vue/app',

    ],

    plugins: [
        ["@babel/plugin-proposal-object-rest-spread", { "loose": true, "useBuiltIns": true }]
    ]
};

But it still the same problem, thanks for response!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
