### ISSUE TITLE
Can Vue.JS app run without index.html file?

### ISSUE THREAD

**Issue by juancampuzano** [vuejs/vue#11226]
### What problem does this feature solve?
I want to know if it is possible to work with vue.js only working with javasript files. 

### What does the proposed API look like?
Vue.js working without using a index.html file

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
