### ISSUE TITLE
How to make eslint support Vue typescript decorator

### ISSUE THREAD

**Issue by wuming123** [vuejs/vue#11232]
### What problem does this feature solve?
How to make eslint support Vue typescript decorator

### What does the proposed API look like?
How to make eslint support Vue typescript decorator

**Comment by LinusBorg** [comment]
1. Please ask question on forum.vuejs.org or chat.vuejs.org
2. If you want to request a feature, do so in the appropriate repository
3. One-Liners are not bug reports nor feature requests, and make for bad questions.
