### ISSUE TITLE
can not get $scopedSlots.xxx   before render

### ISSUE THREAD

**Issue by tangjinzhou** [vuejs/vue#11234]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-antd-template-gn71z](https://codesandbox.io/s/vue-antd-template-gn71z)

### Steps to reproduce
I can get `$scopedSlots.xxx`  `$slots.xxx` before render in v2.5.x.
But v.2.6 is not same.

### What is expected?
like 2.5.x

### What is actually happening?
can not get $scopedSlots.xxx   before render

**Comment by posva** [comment]
Why would you need them before rendering? They are only used during rendering

**Comment by tangjinzhou** [comment]
I need to set different states based on different slot content or number. 
So I expect to get the slots in data, beforeUpdate, etc.

**Comment by tangjinzhou** [comment]
I use other methods to achieve the same goal, but we have already used it in v2.5.
Our [component library](https://github.com/vueComponent/ant-design-vue) is used by many users, if it is not compatible, we will spend a lot of time to change.

**Comment by zhixinpeng** [comment]
I tried upgrading the vue version of [element](https://github.com/ElemeFE/element) from 2.5.17 to 2.6.11, but I  found that I can't  get $slots.xxx in mounted. The code in  [here](https://github.com/ElemeFE/element/blob/dev/packages/popover/src/main.vue). 
```
<template #reference>button</template> // can't get $slots.reference

<span slot="reference">button</span> // it's ok
```
