### ISSUE TITLE
when use a method call as template-interpolation e.g. {{ getNum() }},  if some event handler be bound to a element tag that change some state in "data" option,  this will cause the method ( here is "getNum" ) be called again and again.

### ISSUE THREAD

**Issue by yamybl** [vuejs/vue#11233]
### Version
2.6.10

### Reproduction link
[https://codepen.io/yamybl/project/editor/AjVMVR#](https://codepen.io/yamybl/project/editor/AjVMVR#)

### Steps to reproduce
mouseover or mouseout the button

### What is expected?
mouseover or mouseout event not cause the "getNum" method called

### What is actually happening?
every time mouseover or mouseout the button will cause the "getNum" method called

**Comment by posva** [comment]
This is expected and is described on the docs. You can wrap a behavior iba component to limit it

**Comment by yamybl** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eduardo San Martin Morote"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 晚上6:37
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"海带"<397760271@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue] when use a method call as template-interpolation e.g. {{ getNum() }},  if some event handler be bound to a element tag that change some state in "data" option,  this will cause the method ( here is "getNum" ) be called again and again. (#11233)





 
This is expected and is described on the docs. You can wrap a behavior iba component to limit it
