### ISSUE TITLE
custom directive's "unbind" is not called in v-if / v-else

### ISSUE THREAD

**Issue by borisovg** [vuejs/vue#11238]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/wukg1nbL/5/](https://jsfiddle.net/wukg1nbL/5/)

### Steps to reproduce
With both "v-if" and "v-else" elements present "this.text" is only ever set to "BIND", but if you delete the "v-else" element then "this.text" will switch between "BIND" and "UNBIND".

### What is expected?
Expected for bind and unbind hooks to be called repeatedly as the v-if / v-else should be destroying the element the directive is bound to.

### What is actually happening?
Unbind is not called if v-if and v-else are both present.

---
Sorry about the somewhat convoluted repro. :)

Real-life use-case is a directive that operates on an array of data (passed in via binding) and this array needs to be switched out for another array depending on some condition.

**Comment by sirlancelot** [comment]
Add a `key` to the tags with the directive. The unbind method isn't firing because technically the node still exists it's just the contents that are changing. Use the `update` directive method to listen for that.

https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions

**Comment by borisovg** [comment]
Interesting, but you are right. Could you point me to a link in the docs to understand why? Clearly I'm missing some understanding of Vue fundamentals.

**Comment by sirlancelot** [comment]
It's a bit difficult to explain. I think the [`key` documentation](https://vuejs.org/v2/api/#key) is as good as it gets. The important bit  to understand would be "Without keys, Vue uses an algorithm that minimizes element movement and tries to patch/reuse elements of the same type in-place as much as possible." This much is true of all Virtual DOM implementations today.
