### ISSUE TITLE
Memory leak on IE 11

### ISSUE THREAD

**Issue by AleynHe** [vuejs/vue#11230]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/goyuniyigu/edit?html,output](https://jsbin.com/goyuniyigu/edit?html,output)

#11227 

### Steps to reproduce
1. Open the above JSBin test page through IE 11.
2. Open IE11 F12 developer tools memory panel， Capture Memory snapshot 
3. Click the Toggle button. Rendering Vue instances.
4. Click the Toggle button. Destroy Vue instance.
5. Capture Memory snapshot . Memory is recycled. But windows task manager does not see less memory.

### What is expected?
Memory recovery over 90%

### What is actually happening?
Memory recycle less than 30%

---
The tags in the template do not use v-for, v-on, v-bind. You can copy more than 1000   basic tags (DIV or span) manually. You can also reproduce this problem .

**Comment by rickywu** [comment]
Have you solved?

**Comment by JinPengGeng** [comment]
@AleynHe  Have you solved? i have same issue here

**Comment by smilesman** [comment]
I had the same problem and my computer froze up
