### ISSUE TITLE
Functions imported in <script> section of single-file component are not available in <template> section

### ISSUE THREAD

**Issue by unikitty37** [vuejs/vue#11236]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/wild-rain-oi9th](https://codesandbox.io/s/wild-rain-oi9th)

### Steps to reproduce
1. Observe the component does not render
2. Delete the line `<HelloWorld msg="date-fns" :datetime="parseJSON('2012-03-01T05:20:10 00:00')"/>` from App.vue
3. Observe the component renders

### What is expected?
The imported `parseJSON` function is available to the template.

### What is actually happening?
The imported `parseJSON` function is not available to the template. When running standalone, the message

```
[Vue warn]: Property or method "parseJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

is logged to the console.

---
The component is being called from a Rails view, which needs to pass a date in.

https://vuejs.org/v2/guide/components-props.html#Passing-Static-or-Dynamic-Props documents how to pass in every supported data type *except* Date (if this could be added, that would be super-helpful). The `new Date('…')` method works, but documentation for Date says that this uses Date.parse, which should be avoided as it's highly browser-dependent.

Bypassing the type-checking by passing the dates as strings is ugly, as then other Vue components must convert *their* Dates into strings in order to pass them to this one.

I would like to avoid this by parsing the date with date-fns, but the documentation is unclear on how to import functions for use in the template section. Importing parseJSON in main.js (before importing Vue or App) doesn't work, either. It doesn't look like this is possible — but it really should be.

Either way, the documentation really needs to cover how to pass a Date in properly.

**Comment by LinusBorg** [comment]
> but the documentation is unclear on how to import functions for use in the template section. 

The document *should* be clear on the fact that only component properties and methods ar exposed to the template. Consequently, to make an imported function available in your template, add  it to the `methods` of your component
