### ISSUE TITLE
Call blocking will prevent re-render

### ISSUE THREAD

**Issue by kirillbunin** [vuejs/vue#11249]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/fw89qnoc/](https://jsfiddle.net/fw89qnoc/)

### Steps to reproduce
Let's start with simple call blocking function:
https://jsfiddle.net/yd6xr8ea/

The idea here is, that `counter` should update before `myVal `, so I thought `$forceUpdate` should do the trick:
https://jsfiddle.net/0jdhy41g/

But it doesn't.

So according to docs, https://vuejs.org/v2/api/#updated I've put the code in the `$nextTick` of the `updated` function.
https://jsfiddle.net/fw89qnoc/

But that still doesn't do the trick. Adding 1ms timeout works, but it feels hackish and doesn't really do justice the docs.
https://jsfiddle.net/bwd9j3sq/

### What is expected?
Both values should update a re-render independedly

### What is actually happening?
Unless timeout is involved, re-render is blocked, even when used recommendation from the docs.

**Comment by posva** [comment]
It's not the render of Vue that is blocked but rather the browser rendering. A PR to docs are welcome but there isn't anything to do on Vue's side

**Comment by kirillbunin** [comment]
@posva But shouldn't `$nextTick` ensure that `myVal` will change before call blocking code executes?
