### ISSUE TITLE
Functional components don't interpret empty boolean props as true

### ISSUE THREAD

**Issue by atomanyih** [vuejs/vue#11258]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/crazy-davinci-ckird](https://codesandbox.io/s/crazy-davinci-ckird)

### Steps to reproduce
Observe the rendered output in the repro

### What is expected?
Both components should show "true"

### What is actually happening?
Standard component shows "true", functional component shows nothing

---
https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean

There are obvious workarounds, but I would hope that a functional component would, from the outside, have the same interface as a non-functional component.

The number of undocumented caveats and limitations to functional components has, to me, made their usefulness fairly questionable

**Comment by posva** [comment]
You need to add the prop as mark it as Boolean for the cast to happen (same as with regular components):

```js
export default {
  name: "Functional",
  props: {
    isTrue: Boolean
  }
};
```
