### ISSUE TITLE
Lodash causes errors when cloning objects

### ISSUE THREAD

**Issue by filipbekic01** [vuejs/vue#11255]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Try to clone object with lodash library and reassign it to root data object. For example `this.car = _.cloneDeep(carModel)`.

### What is expected?
When you use binding say `v-model="car.color"` it should work.

### What is actually happening?
It throws error that car is not defined at all. Feels like root data object lose reference to car object.

---
Funny thing is that sometimes it works perfectly and sometimes it just breaks.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

----

When reporting a bug, always provide a boiled down reproduction
