### ISSUE TITLE
props are undefined and computed properties error during evaluation

### ISSUE THREAD

**Issue by PrismPrince** [vuejs/vue#11263]
### Version
2.6.11

### Reproduction link
![https://i.imgur.com/KvC0HPN.png](https://i.imgur.com/KvC0HPN.png)

### Steps to reproduce
\* I cannot provide **reproduction link** using sandbox because it went to an error but there is a [screenshot](https://i.imgur.com/KvC0HPN.png).

Computed property on a child component returns error when passing a value as props from parent

### What is expected?
the computed property must evaluate if the prop value is present

### What is actually happening?
the computed property that requires the prop value evaluate even it is not defined yet

**Comment by posva** [comment]
Always provide a boiled down and runnable repro when reporting a bug please

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
