### ISSUE TITLE
Unable to override environment variables regex

### ISSUE THREAD

**Issue by tahpot** [vuejs/vue#11260]
### What problem does this feature solve?
At the moment, only environment variables prefixed with `VUE_APP_` are loaded into `process.env`.

I have a third party library that configures itself using environment variables, however those variables can't load as they aren't Vue.js specific.

### What does the proposed API look like?
Modify resolveClientEnv so that prefixRE is configurable via the plugin options.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is also related to the CLI and not to Vue itself. Maybe there is something in the docs to help you: https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

**Comment by tahpot** [comment]
I can work around the issue in `vue.config.js`:

```
module.exports = {
    configureWebpack: config => {
        const prefixRE = /^VERIDA_/;
        Object.keys(process.env).forEach(key => {
            if (prefixRE.test(key)) {
                config.plugins[1].definitions['process.env'][key] = JSON.stringify(process.env[key]);
            }
        });
    }
}
```

This is a huge hack however. I'm suggesting a new configuration option be added to `@vue/cli-service/lib/util/resolveClientEnv.js`, so  that it's possible to provide a custom regex that defines the environment variables that should be made available to Vue.

**Comment by Justineo** [comment]
You can create a feature request for Vue CLI [here](https://new-issue.vuejs.org/?repo=vuejs/vue-cli&type=feature-request).

**Comment by tahpot** [comment]
@Justineo This ticket was created by filling out that feature request form...

**Comment by Justineo** [comment]
@tahpot Yes but you need to select vue-cli there so that the issue will be created in the correct repo.
