### ISSUE TITLE
data() method when component extended

### ISSUE THREAD

**Issue by surjit** [vuejs/vue#11277]
### Version
2.6.11

### Reproduction link
[https://github.com/surjit/vue-test/commit/e7d262d421106c05774bea5b5f96f94f68c3e2fb](https://github.com/surjit/vue-test/commit/e7d262d421106c05774bea5b5f96f94f68c3e2fb)

### Steps to reproduce
npm run server
and Look into console

### What is expected?
I'm expecting test_b should be object as test
CreateEdit.vue line 8,7

### What is actually happening?
Now, It undefined

---
I'm trying to get route resolve working as the way Angular does

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by surjit** [comment]
My forum account on hold, not sure why? username surjitsidhu
