### ISSUE TITLE
[vue-server-renderer] It is possible to use Component-level Caching with data that i got from serverPrefetch()?

### ISSUE THREAD

**Issue by cron13** [vuejs/vue#11275]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/modest-blackwell-uvtxt](https://codesandbox.io/s/modest-blackwell-uvtxt)

### Steps to reproduce
go to https://codesandbox.io/s/modest-blackwell-uvtxt and reload browser window - you've got Mismatching childNodes vs. VNodes error, because cached doesn't store data

### What is expected?
cache component with data

### What is actually happening?
Mismatching childNodes vs. VNodes 

---
Hi,
This issue related to https://github.com/nuxt/nuxt.js/issues/7161
I wanna cache component with data that i fetch from api
But component cache store only HTML so i got hydration error
May be it is possible to store html some data that i got from serverPrefetch() or nuxtjs fetch() hook?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
