### ISSUE TITLE
Cannot pass an initial value to dynamic textarea

### ISSUE THREAD

**Issue by MartinMalinda** [vuejs/vue#11289]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/vue-composition-api-example-b9qkq](https://codesandbox.io/s/vue-composition-api-example-b9qkq)

### Steps to reproduce
Take this piece of code: <component :is="txt" v-model="textareaInitialValue" :value="textareaInitialValue"/>. Txt is just bound to `textarea`. There's no way to pass an initial value because `<textarea>` requires `v-model` but `v-model` on `<component>` will be turned into `{ value }` 

### What is expected?
I expect the <component> to correctly pass the v-model to textarea or that textarea could data bind `value` just like `<input>`.

### What is actually happening?
Nothing displays in the dynamic textarea

**Comment by MartinMalinda** [comment]
Strangely enough

```vue
<component :is="txt">{{ someValue }}</component>
```

Seems to work despite the docs saying not to pass value inside textarea (`<textarea>{{ someValue }}</textarea>`)

**Comment by posva** [comment]
Do

```html
 <component :is="txt" v-model="textareaInitialValue" :value.prop="inputInitialValue"/>
    <component :is="input" v-model="inputInitialValue" :value="inputInitialValue"/>
```

`textarea` doesn't have a `value` attribute, it only has it as an element property

**Comment by MartinMalinda** [comment]
amazing, thanks!
