### ISSUE TITLE
Interesting bug / quirk computed property not updating correctly, but probably not fixable

### ISSUE THREAD

**Issue by derMart** [vuejs/vue#11294]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue?file=/src/App.vue](https://codesandbox.io/s/vue?file=/src/App.vue)
^^work in progress

### Steps to reproduce
Hi consider this snippet:
```
  ...
  computed: {
    someProp() {
      if(this.nonReactiveProperty) {
        return this.reactiveProperty;
      }
   }
  },
  ...
```
From the documentation I would assume (please show me if I missed something) that `someProp()` should get re-evaluated when `this.reactiveProperty` does change. Works as expected as long as `this.nonReactiveProprty` is true all time. However, if `this.nonReactiveProperty` is false the first time someProp() is read, then someProp() will never re-evaluate, even if `this.reactiveProperty` changes (after `this.nonReactiveProperty` gets true).
The problem is, I guess it is not fixable. Am I assuming correctly, that the dependencies of `someProp()` get calculated the first time it is executed? So code which does not get executed then, vue is just blind of....?
This is quite tricky and probably I've run into this quite some times before figuring out. It gets even harder to see when inside lazy conditions. E.g. this works all the time:
```
someProp() {
      if(this.reactiveProperty && this.nonReactiveProperty) {
        return this.reactiveProperty;
      }
   }
```
while this might not:
```
someProp() {
      if(this.nonReactiveProperty && this.reactiveProperty) {
        return this.reactiveProperty;
      }
   }
```

So if this is not fixable, and I didn't miss something, I would suggest to add this to the documentation.

best
Martin

### What is expected?
someProp() should re-evaluate after this.reactiveProperty changes and this.nonReactiveProperty is true

### What is actually happening?
someProp() does not re-evaluate after this.reactiveProperty changes and this.nonReactiveProperty is true, if this.nonReactiveProperty was false the first time someProp() get read.

**Comment by posva** [comment]
See my reply at #11293

**Comment by derMart** [comment]
see my reply https://github.com/vuejs/vue/issues/11293#issuecomment-610566655
