### ISSUE TITLE
Concerns regarding Dockerization of a VueJS application

### ISSUE THREAD

**Issue by linkdd** [vuejs/vue#11290]
### What problem does this feature solve?
Hello, not really a feature request but still, some help is wanted here :)

I have two very simple rules:

 - my Docker image must be exactly the same between my development environment and my production environment
 - configuration values must be passed at runtime and nowhere else

Why ? Simple:

 - if I validate (linting, non regression testing, functionnal testing, ...) my Docker image in my development environment, I don't want to do the same for my production environment. The image can be used as is since both are exactly the same.
 - when I build a Docker image, it must be able to run in different environment, thus passing configuration values at build time is not an option since it would result in different images across different environments

So, when serving a VueJS application in production, I will obviously build (`yarn run build`) and then serve the static content with nginx.
The problem here is that configuration must be passed at the build stage, which is not an option for me because of the reasons evoked above.

### What does the proposed API look like?
The only solution I see to this problem would be to generate a file at runtime that Nginx would inject in the `index.html`. But this is not trivial.

Does anyone has other recommendations regarding this issue ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
