### ISSUE TITLE
The email field is vulnerable to html injection which leads to xss

### ISSUE THREAD

**Issue by angudon** [vuejs/vue#11309]
### Version
2.5.13

### Reproduction link
[https://app.snov.io/login](https://app.snov.io/login)

### Steps to reproduce
I know that snov.io is not your website.I request you to see the framework vulnerability
1)The website https://app.snov.io/login uses the vue.js version 2.5.13 which is vulnerable. 
2)login and add new member/profile in the https://app.snov.io/prospects/new-profile/1841654#
3)there is a email field which is vulnerable to html injection 
4)Actually these codes execute when i finish the code which can able to produce generic xss  

### What is expected?
need to sanitize the email field

### What is actually happening?
Html injection ,Generic xss,click hijacking

---
The email field should  accept only the email address not any html codes

**Comment by sirlancelot** [comment]
This is not related to Vue.js. Please contact the team responsible for supporting that website.
