### ISSUE TITLE
val and oldVal passed to watchers are incorrect when watching an array

### ISSUE THREAD

**Issue by pSnehanshu** [vuejs/vue#11304]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/p_snehanshu/9g8m2bu1/10/](https://jsfiddle.net/p_snehanshu/9g8m2bu1/10/)

### Steps to reproduce
In a vue component, watch an array.
Then change the array, either push or splice or pop.
Inside the watcher, compare the `val` and the `oldVal`

### What is expected?
the `val` and the `oldVal` are expected to be different.
The `val` should have the current value, and `oldVal` should have the previous value.

### What is actually happening?
the `val` and the `oldVal` are exactly the same.
While `val` is correct in its place, the `oldVal` should have been different, but it's not.

**Comment by posva** [comment]
See the note https://vuejs.org/v2/api/#vm-watch
