### ISSUE TITLE
Improve error message when template tag is skipped

### ISSUE THREAD

**Issue by folmert** [vuejs/vue#11300]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/currying-shadow-inm2w?file=/src/App.vue](https://codesandbox.io/s/currying-shadow-inm2w?file=/src/App.vue)

### Steps to reproduce
1. Create a .vue file with template, with 2 elements inside and a script tag.
2. Remove the wrapping `<template></template>` tag.
3. It sparks a confusing error:
```
Module parse failed: Unexpected token (7:0)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|
> <v-layout wrap>
|     <v-flex xs4>
|         <v-select

```

### What is expected?
The error should say that template tag was skipped.

### What is actually happening?
Current error message isn't very helpful.

---
In such a case on codesandbox the error message is actually helpful:
`Failed to mount component: template or render function not defined.`
but it's different when compiled via `yarn serve`. 

I've wasted many minutes trying to figure out the reason behind this error, as my IDE (WebStorm) doesn't highlight lack of `template` as an error. With a more helpful error message developers could save time spent on debugging.

**Comment by posva** [comment]
Besides the fact that it doesn't make sense to remove the `template` tag once it has been added, this warning would conflict for users adding custom blocks and components with no `template` tag. If anything, this should be picked up at an IDE level not at Vue or vue-loader level

**Comment by folmert** [comment]
Of course it doesn't make sense to remove this tag, but mistakes happen. It doesn't have to literally say "template not defined", just make it more helpful - codesandbox is doing it right, vue-cli isn't.
