### ISSUE TITLE
What's the meaning of `wtf flow` ?

### ISSUE THREAD

**Issue by zhanyuzhang** [vuejs/vue#11312]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270](https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270)

### Steps to reproduce
I found `wtf flow` on the source code at line:

https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270

### What is expected?
https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270

### What is actually happening?
https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270

---
I found `wtf flow` on the source code at line:

https://github.com/vuejs/vue/blob/0551226f8bf0884e31bb686b7116b60f1eaf77e6/src/core/instance/lifecycle.js#L270

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
