### ISSUE TITLE
How to cache the same keep alive component

### ISSUE THREAD

**Issue by bosens-China** [vuejs/vue#11316]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/elastic-boyd-t4y6f?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/elastic-boyd-t4y6f?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

I have two pages, and their contents are very similar, so I'm going to use the factory mode to return them, but nesting `< keep alive / >` outside will cause the contents of the two pages to be exactly the same. What should I do to achieve the correct effect

---

我有两个页面，他的内容很相似，所以我准备用工厂模式给他返回，但是在外面嵌套使用`<keep-alive/>`会导致两个页面内容完全一致，我应该怎么做才能实现正确的效果

### What is expected?
The input does not affect at all. For example, the default component input 'demo' will not be repeated when clicking to switch to foo route

---

输入的内容完全不影响，例如默认组件输入'demo'点击切换到foo路由的时候不会是重复的

### What is actually happening?
Consistent switching content

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can use `include` and `exclude` to control what is kept alive: https://vuejs.org/v2/api/#keep-alive
