### ISSUE TITLE
Memory leak in Internet Explorer after creating and destroying component

### ISSUE THREAD

**Issue by Feofilakt** [vuejs/vue#11339]
### Version
2.6.11

### Reproduction link
[https://github.com/Feofilakt/vue-issue-repro](https://github.com/Feofilakt/vue-issue-repro)

### Steps to reproduce
1. Load reproduction project
2. Install cli-service-global (https://cli.vuejs.org/guide/prototyping.html) and run "vue serve"
3. Open site in Internet Explorer of latest version, open development tools and run memory profiler
6. Make heap snapshot
7. Check the checkbox
8. Uncheck the checkbox
9. Make heap snapshot

### What is expected?
Memory of two snapshots must be about equal

### What is actually happening?
Memory of two snapshots varies significantly

---
I'm afraid I didn't yet determine all the reproduction conditions for sure. If you cannot reproduce the bug, try increase the count in "for" loop, please.

**Comment by posva** [comment]
When reporting memory leaks, please make sure to boil it down to the bare minimum in an HTML file (no cli, it also makes it easy to switch between dev and prod). Also, make sure it hasn't been reported before by searching for the term `leak` in issues.

If the leak can only be reproduced in one browser, it might be a browser bug too.  In the case of IE, they are known cases of memory leaks that haven't been addressed. It's better to show the problem in a modern browser such as Chrome, Firefox or Edge

**Comment by Feofilakt** [comment]
Seems that Vue caches last created component so it still remains in memory after destroyed.

**Comment by superchangme** [comment]
@vue boss, do we should give up Internet Explorer?
