### ISSUE TITLE
Beginners start with vue3, too few documents.

### ISSUE THREAD

**Issue by SwankyTigerYY** [vuejs/vue#11334]
Thanks for your link.

**Comment by posva** [comment]
The documentation team is working hard on the documentation 🙂 
At the moment you can use https://github.com/vuejs/vue-next-webpack-preview or https://github.com/vuejs/vue-cli-plugin-vue-next to get started. You can also check https://composition-api.vuejs.org/#api-introduction if you want to use the new composition api
