### ISSUE TITLE
2.6.11 动态参数 无法大小写混合使用

### ISSUE THREAD

**Issue by fushengruomengzhang** [vuejs/vue#11337]
### Version
2.6.11

### Reproduction link
[https://codepen.io/fushengruomengzhang/pen/RwWKpzw](https://codepen.io/fushengruomengzhang/pen/RwWKpzw)

### Steps to reproduce
```
<div id='app'>
<a v-bind:[attributeName]="url">click</a>
</div>
var app = new Vue({
 el: '#app',
data:{
attributeName:'href',
url:'www.baidu.com'
}
})
```
```
Property or method "attributename" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property
```

### What is expected?
属性可以大小写混合使用

### What is actually happening?
大小写字母无法混合使用

**Comment by Jinjiang** [comment]
It doesn't work when you use template directly in html file. But for example in SFC it works properly. Also you could use the template as a string in JS. See:
- https://codepen.io/Jinjiang/pen/eYpgWdL
- https://codepen.io/Jinjiang/pen/PoPWmbb

**Comment by Justineo** [comment]
见文档：https://cn.vuejs.org/v2/guide/syntax.html#%E5%AF%B9%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0%E8%A1%A8%E8%BE%BE%E5%BC%8F%E7%9A%84%E7%BA%A6%E6%9D%9F
