### ISSUE TITLE
Class name are not finish binding after $nextTick on Vue 2.6.11.

### ISSUE THREAD

**Issue by SaekiRaku** [vuejs/vue#11338]
### Version
2.6.11

### Reproduction link
[https://github.com/SaekiRaku/issue-vue-nexttick](https://github.com/SaekiRaku/issue-vue-nexttick)

### Steps to reproduce
Clone the repository, and open the `vue2.5.html` and `vue2.6.html` in the browser directly.

These 2 HTML files based on the same JS code file (`app.js`), the difference between the HTML files is the version of Vue.

But the CSS transition reacts a different behaviour (the class of CSS transition is added by v-bind), by clicking `Toggle Expand` on the web, it should collapse or expand the list of random length with animation.

And it works fine on Vue 2.5.1, but failed on Vue 2.6.11 (Also tested on Vue 2.6.1 which is also failed). On Vue 2.6.11 the action of collapse didn't have animation and didn't trigger the transitionend event. But it can work when adding a `setTimeout` inside the `$nextTick` callback. So I assumed that is because the class didn't finish binding after the `$nextTick`.

### What is expected?
It should react in the same way between the different version of Vue.

### What is actually happening?
For this repo's example, Vue 2.5.1 is working fine, Vue 2.6.11 is not.

**Comment by posva** [comment]
Both trigger the same animation.

Please take a look at https://github.com/vuejs/vue/releases/tag/v2.6.0 _Important internal changes_ as well as https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

**Comment by SaekiRaku** [comment]
@posva Hi, please look back at the repo again, I have added a video(`show.mp4`) to the repo to describe my issue more clearly.

On Safari, the first click on `Toggle Expand` is working fine, then click it again, Vue 2.6.11 didn't trigger the closing animation and it needs to wait for the first click animation ended to reproduce this issue (A fast double click will be working fine).

On Chrome, this issue is reproduced randomly, it's weird.

**Comment by posva** [comment]
I took a look and the reason it doesn't work is because you have to wait for the browser to update the content so it can trigger a transition. That's why it worked with a setTimeout.

You can do this

```js
    toggleExpand: async function () {
      this.expand = !this.expand
      if (this.expand) {
        this.domHeight = '0px'
        this.useTransition = true
        await this.$nextTick()
        requestAnimationFrame(() => {
          vm.domHeight = vm.$refs['container'].scrollHeight + 'px'
        })
      } else {
        this.domHeight = this.$refs['container'].clientHeight + 'px'
        this.useTransition = true
        await this.$nextTick()
        requestAnimationFrame(() => {
          vm.domHeight = '0px'
        })
      }
    },
```

the `await this.$nextTick()` doesn't seem necessary but it's safer to wait for Vue's update and then browser's

**Comment by SaekiRaku** [comment]
I see, thanks a lot.
