### ISSUE TITLE
在浏览器切换到其他页面再切换回来时，使用了v-show的transition过渡异常

### ISSUE THREAD

**Issue by duanmw** [vuejs/vue#11348]
### Version
2.6.11

### Reproduction link
[https://codepen.io/duanmw/pen/mdemPwb](https://codepen.io/duanmw/pen/mdemPwb)

### Steps to reproduce
打开https://codepen.io/duanmw/pen/mdemPwb 页面，使用了v-show的transition过渡效果正常，然后切换其他浏览器页面，过一会再切换回来，transition过渡效果异常

### What is expected?
transition过渡效果不受浏览器页面切换的影响

### What is actually happening?
浏览器页面切换影响了transition过渡效果

**Comment by zhangzhonghe** [comment]
应该是浏览器的优化导致的，一般当页面在后台运行时，为了节约计算机资源，浏览器会停止渲染页面，但我不确定真正的原因是什么😅

**Comment by posva** [comment]
timetouts and intervals run in the background while CSS animations don't, that's why you see all the animations playing at the same time when coming back.

**Comment by duanmw** [comment]
> timetouts and intervals run in the background while CSS animations don't, that's why you see all the animations playing at the same time when coming back.

So is there a solution? I want to see the normal animation.

**Comment by zhangzhonghe** [comment]
> > timetouts and intervals run in the background while CSS animations don't, that's why you see all the animations playing at the same time when coming back.
> 
> So is there a solution? I want to see the normal animation.

当页面隐藏时，你可以停止动画，等到页面显示时，在开始动画。
