### ISSUE TITLE
Memory leak in Internet Explorer process after creating and destroying Vue component

### ISSUE THREAD

**Issue by Feofilakt** [vuejs/vue#11343]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/tepahezeqi/1/edit?html,js,output](https://jsbin.com/tepahezeqi/1/edit?html,js,output)

### Steps to reproduce
1. Open reproduction link in Internet Explorer of latest version
2. Open task manager and see how IE process memory increases until browser stops responding or crashes

### What is expected?
Memory usage not increases over time, browser works normal

### What is actually happening?
 IE process memory quickly increases until browser stops responding or crashes

---
I suspect it is issue with reactivity system of Vue.

**Comment by posva** [comment]
Please don't reopen the same issue without further information (https://github.com/vuejs/vue/issues/11340). I already checked the reproduction in multiple browsers and answered the questions. If you find places where tricks can be used to improve extreme cases of JS memory consumption specifically in IE to get around its bugs, please open a Pull Request.
