### ISSUE TITLE
ignoredElements option does not completely ignore elements.

### ISSUE THREAD

**Issue by guillaumebriday** [vuejs/vue#11342]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/patient-snow-6pyw9?file=/src/App.vue](https://codesandbox.io/s/patient-snow-6pyw9?file=/src/App.vue)

### Steps to reproduce
For instance, I defined my Vue option like that:

```
Vue.config.ignoredElements = [
  'password-toggle'
]
```

I have a CustomElement named `password-toggle` and I use it like so in my html:
```html
<input type="password" class="form-control" is="password-toggle" />
```

### What is expected?
I think, this input should be completely ignored by Vue and be handle by the browser. It should keep the eventListeners on this element too.

### What is actually happening?
Unfortunately, it's parsed by Vue and changed like that:

```html
<password-toggle class="form-toggle"></password-toggle>
```

All the eventListeners are gone too.

---
How can we use Vue with Custom Elements ?

Thank you

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by guillaumebriday** [comment]
Thanks @posva for the quick answer.

I think it's a bug as long as the doc does not explain this behavior.

I think if the option is named **ignored**`Elements`, it should ignore completely the element which is not the case here. The behavior is not the same with and without Vue.

**Comment by posva** [comment]
The repro is working as expected, leaving the element `password-toggle` as is. It's up to you how to use it as a web component or custom element and if you need help, please use the mentioned resources.
