### ISSUE TITLE
Memory leak in Internet Explorer process after creating and destroying Vue component

### ISSUE THREAD

**Issue by Feofilakt** [vuejs/vue#11340]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/tepahezeqi/1/edit?html,js,output](https://jsbin.com/tepahezeqi/1/edit?html,js,output)

### Steps to reproduce
1. Open reproduction link in Internet Explorer of latest version
2. Open task manager and see how IE process memory increases until browser stops responding or crashes

### What is expected?
Memory usage not increases over time, browser works normal

### What is actually happening?
 IE process memory quickly increases until browser stops responding or crashes

**Comment by posva** [comment]
Thanks for the boiled down reproduction. As said on the other issue, I tested on other browsers and the memory is properly collected so this is probably yet another memory leak on IE. It crashes with extreme amounts of data, but this would happen in plain JS too. I don't think we can do anything to fix it as we are properly releasing the memory

**Comment by Feofilakt** [comment]
@posva, thanks for answering at least here.
I really doubt it would happen in plain JS. Why do you think so? If you remove array from "data" or apply Object.freeze to elements it will solve problem. So it is for sure issue with reactivity system of Vue.
