### ISSUE TITLE
Insert content into iFrame content

### ISSUE THREAD

**Issue by anoopgcmz** [vuejs/vue#11358]
### Version
2.6.11

### Steps to reproduce
Create a text box outside iframe. when the title is updated in the text box the title inside the iframe should be changed. It can be done easily with jquery. But i cant find a solution to do the same in vue. please find the example jquery code below.

$('#preview_iframe').contents().find('#title_iframe').html( $('#textbox_title').val().replace (/ /g, "&nbsp;"));

### What is expected?
to change the iframe text realtime on textbox update

### What is actually happening?
in console the data is getting updated but in iframe it is no updating

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
