### ISSUE TITLE
Vue.nextTick event still called

### ISSUE THREAD

**Issue by stevenwr23** [vuejs/vue#11356]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/qsv4dw2p/3/](https://jsfiddle.net/qsv4dw2p/3/)

### Steps to reproduce
Click on show tooltip button

### What is expected?
The text should change to "Showing tooltip" until I click anywhere else

### What is actually happening?
The text changes to "Showing tooltip" and then immediatly changes back to "no tooltip"

---
Hi, I'm trying the following for showing and hiding a tooltip on a click event (https://jsfiddle.net/qsv4dw2p/3/ ):

  	showTooltip() {
    	this.text = 'showing tooltip'
      this.$nextTick(() => {
        document.addEventListener("click", this.hideTooltip)
      })
		},
    hideTooltip() {
    	this.text = 'no tooltip'
      document.removeEventListener('click', this.hideTooltip)
    }

This worked on a previous version of vue (2.15.16), but I updated to (2.6.11) and it stopped working, basically the hide is called even if the listener is added on the $nextTick, why has this behavior changed?

From my understanding, this should work in theory, since we are adding the hide listener on a next tick, so the current event should have already been handled.

There is a workaround, which is using click.stop instead of click (https://jsfiddle.net/qsv4dw2p/4/ ), however I'm curious on why it worked on previous versions but not in the latest.

**Comment by posva** [comment]
It's great you found the workaround. The explanation can be found in the release notes: https://github.com/vuejs/vue/releases/tag/v2.6.0 -> Important internal changes

**Comment by stevenwr23** [comment]
Thanks I see that the next tick implementation changed in 2.6.

However this behavior seems strange, shouldn't the next tick be called after the DOM is updated?
If that were the case, in the reproduction case the text should at least change for a fraction of a second, before changing back.
Am I missing something?
