### ISSUE TITLE
computed property setter not called when set in parent template

### ISSUE THREAD

**Issue by derMart** [vuejs/vue#11352]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/keen-smoke-dp17k?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/keen-smoke-dp17k?file=/src/components/HelloWorld.vue)

### Steps to reproduce
see the minimal example link which boiles down to this:

parent template:
```
 <HelloWorld msg="Hello Vue in CodeSandbox!"/>
```
hello world code:
```
  computed: {
    msg: {
      get() {
        return this._msg;
      },
      set: function(v) {
        this._msg = v;
        console.log("msg setter called");
      }
    }
  }
```

### What is expected?
the console should print 'msg setter called'

### What is actually happening?
the console does not print 'msg setter called' although the parent template sets the msg property

**Comment by posva** [comment]
The `msg` passed to `<HelloWorld>` should be declared as a prop instead of a computed property. Have you checked the guide: https://vuejs.org/v2/guide/?

---

Remember you should use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by derMart** [comment]
thnx, yes I have checked the guide, but haven't found this constraint there...can you point me to?
If I specify the computed property using 'prop' how to set it's setter?

**Comment by posva** [comment]
> If I specify the computed property using 'prop' how to set it's setter

You can't do that, it's either a prop or a computed property, but please use the appropriate channels to ask usage questions. The issues are for bug reports and feature requests only

**Comment by derMart** [comment]
This is a bug report as the behaviour is not documented, at least I have not found it in the docs. If it is could you please point me there?

**Comment by derMart** [comment]
And in this case if it is working as intended, I propose this as a feature request to be able to set computed properties from outside the component in the parent template, either by extending the 'prop' attribute to allow setters or to include computed (or just any) propery defined by the component to be set by the parent template
