### ISSUE TITLE
Dynamic slot names seem to fail with camelCase

### ISSUE THREAD

**Issue by smolinari** [vuejs/vue#11354]
### Version
2.6.11

### Reproduction link
[https://codepen.io/smolinari/pen/RwWgMoW?editors=1010](https://codepen.io/smolinari/pen/RwWgMoW?editors=1010)

### Steps to reproduce
This demo is using Quasar Framework, but the issue seems to be with Vue. 

Note there is a single slot with a dynamic slot name called "computedBodyCellName".  

1. As the codepen is, you get this error: 

[Vue warn]: Property or method "computedbodycellname" is not defined on the instance but referenced during render.

Notice how it is all small letters.

2. Now change the computed property name to all small letters and then the dynamic slot name works. 

### What is expected?
camelCase named computed property used as the dynamic slot name should work. 

### What is actually happening?
camelCase name in the dynamic slot is being reduced to all small letters for some reason.

---
Hope I could help.

Scott

**Comment by posva** [comment]
This is just an HTML limitation, the same as props using dashes but allowing camelCase in `vue` files.

**Comment by smolinari** [comment]
Shouldn't the error be different then? @posva 

The docs also show a camelCased dynamic slot name. https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names

And, if I hyphenate the slot name, it still doesn't work. 

Or am I missing something here?

Scott

**Comment by posva** [comment]
kebab case won't work as it's a like a v-bind, a js expression. It's a caveat when using dynamic directive arguments. It's mentioned in the link you shared 🙂

**Comment by smolinari** [comment]
Ah. Now I've got it. 

Ok. Thanks for the teaching and sorry I didn't read the docs more carefully. :)

Scott
