### ISSUE TITLE
vue spa application exits memory leak with using `$router.back()/$router.go(-1)` function

### ISSUE THREAD

**Issue by muzi131313** [vuejs/vue#11350]
### Version
2.6.11

### Reproduction link
[https://github.com/muzi131313/memory-leak/tree/master/vue-spa](https://github.com/muzi131313/memory-leak/tree/master/vue-spa)

### Steps to reproduce
Basic Info:
- 1.First, I have ensure this was not vue-router's question, there is  [related issues](https://github.com/vuejs/vue-router/issues/3181).
- 2.clone the repository: `git clone https://github.com/muzi131313/memory-leak/tree/master/vue-spa`
- 3.`npm install`
- 4.`npm run serve`
- 5.visit local page: `http://localhost:8080`

No problem step:
- 1.Open Chrome Dev Tool, choose【More tools】->【Performance monitor】, and select 【memory】 tab
- 2.click link 【About】
- 3.then click link 【Home】
- 4.click 【Collect garbage】
- 5.then 【Dom Nodes】、【JS heap size】will down

Problem step:
- 1.Open Chrome Dev Tool, choose【More tools】->【Performance monitor】, and select 【memory】 tab
- 2.click link 【About】
- 3.then click 【back】(**don't click 【home】link**)
- 4.click 【Collect garbage】
- 5.then 【Dom Nodes】、【JS heap size】stay high

### What is expected?
【Dom Nodes】、【JS heap size】will down

### What is actually happening?
【Dom Nodes】、【JS heap size】stay high

**Comment by posva** [comment]
The Same things  I told you on the other issue apply here... I it's a vue leak, don't include the router. And provide an html file go leak reports
