### ISSUE TITLE
支持渲染字符串为Vue组件

### ISSUE THREAD

**Issue by EthianWong** [vuejs/vue#11361]
### What problem does this feature solve?
服务端返回一个字符串例如
`'i miss u <x-emoji>[爱心]</x-emoji>'`

面对这个解析我主要想了下有3种比较好的方式？
第一种 Vue 中定义 x-emoji 组件，有点类似 v-html 支持渲染组件？

第二种是使用web-component

第三种是类似语法解析，将这个字符串变为类似createElement 的结构，但不清楚Vue是否有这方面的沉淀可以复用？

希望能给些建议

### What does the proposed API look like?
v-html支持渲染组件或给一些建议

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
