### ISSUE TITLE
Prop type declaration order changes the props value when it is an empty string

### ISSUE THREAD

**Issue by NotThatGregGuy** [vuejs/vue#11360]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/nz9qrjcb/](https://jsfiddle.net/nz9qrjcb/)

### Steps to reproduce
Click run and look at the generated html for the 4th row (array index 3).
Notice that it is sometimes empty and sometimes true

![image](https://user-images.githubusercontent.com/17282176/80613398-de28b980-8a02-11ea-9b9f-0cc01adb02e1.png)

### What is expected?
Prop type order should not change the value of the prop

### What is actually happening?
Prop type order is changing how empty strings are handled

**Comment by posva** [comment]
This is intended to automatically cast Boolean props
