### ISSUE TITLE
not re rendering view with v-model and computed value

### ISSUE THREAD

**Issue by roydouek** [vuejs/vue#11364]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/sc-xw0xf](https://codesandbox.io/s/sc-xw0xf)

### Steps to reproduce

1.select the selected date time on the second selection table , under "this doesn't works as expected"
2. select another date on the same hour(same row)
3. notice no change was made to the div

### What is expected?
div would change the text as the value recomputed ,
as the first selection table works 

### What is actually happening?
no change is made in div text

---
this is weird because you can see the correct value is send , and with my testing the data is indeed being changed correctly in the model.

**Comment by posva** [comment]
Hello, right now the code is more of a snippet to ask a question on StackOverflow or on the [Discord](https://chat.vuejs.org) server, so you might as well do that instead if you cannot boil it down to report a bug!

By looking at your code I would say the `computed` property you add is not being tracked by Vue, but it's difficult to tell with so much unrelated code.

If you manage to boil it down to the minimal with no Moment and really focus on showing the problem about v-model and computed, please open a new issue. Right now this is more of a question and should go through the appropriate channels.
