### ISSUE TITLE
Iframe immediately recreated in firefox

### ISSUE THREAD

**Issue by CzBiX** [vuejs/vue#11363]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/2rkotfpc/2/](https://jsfiddle.net/2rkotfpc/2/)

### Steps to reproduce
click the checkbox

### What is expected?
output `[true, true]`

### What is actually happening?
output `[true, false]` in Firefox

---
This demo works in Chrome, but failed on Firefox v75-76.
Any breakpoint also make the demo correct.(see `debugger` statement in demo)

I'm not sure this bug should belongs to Vue or Firefox (or myself?).

**Comment by posva** [comment]
Use a `nextTick` instead of a `setTimeout`

**Comment by katungi** [comment]
Hello @CzBiX I am trying it on chrome and i get  the output as [true, true], maybe it is a firefox problem.

**Comment by CzBiX** [comment]
@posva use `nextTick` doesn't help to this issue.

I write a pure JS demo to test, and it failed too in Firefox.
So it should be firefox issue.
https://jsfiddle.net/4cd3u0fL/1/
