### ISSUE TITLE
event bind name not support chinese characters

### ISSUE THREAD

**Issue by gxrsprite** [vuejs/vue#11362]
### Version
2.6.11

### Reproduction link
[https://stackblitz.com/edit/js-bafxzt](https://stackblitz.com/edit/js-bafxzt)

### Steps to reproduce
<a @click="点击">btn1</a>   
<a @click="点击($event)">btn2</a>  
<a @click="onClick">btn3</a>   

methods:{
   点击:function(e){

    },
    onClick:function(e){

    }
}

### What is expected?
btn1 event not work

### What is actually happening?
write $event in console

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/6975
