### ISSUE TITLE
vue js 2.x, Nested v-slot {scoped slot} not working with the childs

### ISSUE THREAD

**Issue by bnping** [vuejs/vue#11374]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/sweet-diffie-x3tq0?f](https://codesandbox.io/s/sweet-diffie-x3tq0?f)

### Steps to reproduce
we must created nested slots . The code example show the case.

### What is expected?
component-c  must be redered with getting the value "valueB"

### What is actually happening?
component-c  not getting the value "valueB"

**Comment by posva** [comment]
You had a few typos:

- In copmonents slot you were doing `:value="valueA"` but then in the parent you were doing `v-slot="{valueA}"`. You need to make that name match the attribute name on the slot: `:valueA="valueA"`
- You have an uppercase `C` on the parent but a lowercase `c` on the template, make sure to use either of those

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
