### ISSUE TITLE
Object.assign is not being polyfilled

### ISSUE THREAD

**Issue by Dev-Oli** [vuejs/vue#11382]
### Version
2.6.11

### Reproduction link
[https://github.com/Dev-Oli/vuetify-ie11-bug](https://github.com/Dev-Oli/vuetify-ie11-bug)

### Steps to reproduce
See README.md   Vuetify ticket

### What is expected?
The vuetify sample page is shown in IE11 too.

### What is actually happening?
A blank page is shown.

---
See discussion over at https://github.com/vuetifyjs/vuetify/issues/11008

**Comment by posva** [comment]
We don't use Object.assign in Vue codebase precisely to support IE. This is likely to be a configuration issue of some sort.

Maybe you wanted to create an issue on the vuejs/vue-cli repository. If you do, please provide a boiled down reproduction with no extra dependencies (no vuetify)

**Comment by Dev-Oli** [comment]
@posva Please take a look at the linked vuetify issue. There I've been told to create a ticket here because the object.assign polyfill seems to be there some time ago but now it stops working.

**Comment by sirlancelot** [comment]
https://github.com/vuejs/vue-cli/pull/5233

Adjust your `.browserslistrc` to include ie11.  Vue-CLI updated the default by adding `not dead` which now excludes IE, a "dead" browser.

**Comment by Dev-Oli** [comment]
@sirlancelot Thanks for the advice. But even after removing the "not dead" part from the browserslist at package.json I'm still getting the same error at the simple vue project.
Just calling 
`console.log(Object.assign({}));`
at main.js (without added vuetify).

`npx browserslist`
is listing IE11 and even IE10.
