### ISSUE TITLE
Displaying a random number when i used a wrong Directive syntax

### ISSUE THREAD

**Issue by vinayjoseph705** [vuejs/vue#11384]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/2zq0tabm/](https://jsfiddle.net/2zq0tabm/)

### Steps to reproduce
it is displaying random numbers on screen when i used a wrong syntax for directive
 
it shows warning i have used a wrong directive syntax but it is also displaying a number on screen.

the number keeps changing when i enter something to input field

I have used the wrong syntax for click event in Vue. But why is a random number displaying for absolute no reason?
Please use the code below to reproduce. 

     <div id="app">
            <input type="text" placeholder="enter here" v-model="name">
            <h1>{{name}}</h1>

            <button v-click="coun()">Click</button>
            <p>{{counter}}</p>
        </div>

    <script>
          var app = new Vue({
            el: '#app',
            data: {
             name: 'some',
             counter: 2

            },
            methods: {
                coun(){
                    this.counter  
                }
            }

          })

    </script>
   

### What is expected?
Only The warning message in the console.

showing a Number on screen is not accepted

### What is actually happening?
it is displaying random numbers on screen when i used a wrong syntax for directive
 
it shows warning i have used a wrong directive syntax but it is also displaying a number on screen.

the number keeps changing when i enter something to input field

---
was just learning VueJs Reacting to Changes

**Comment by posva** [comment]
The number isn't random, your directive has a function call that gets executed every time it renders, incrementing the counter. But since the counter is also displayed in the template, it renders again and increments again. Vue defends itself by limiting to ~100 calls, that's where the 100 is coming from
