### ISSUE TITLE
Intuitive access to the component's name property

### ISSUE THREAD

**Issue by jfbrennan** [vuejs/vue#11383]
### What problem does this feature solve?
Logging, debugging, etc. is made better with the `name` property, but accessing this property is non-intuitive:
```
export default {
  name: 'my-component',
  mounted() {
    console.log(`${this.$options._componentTag} mounted`)
  }
}
```

Mentally mapping `name` to `$options._componentTag` feels weird. `$options` is fine, but the use of an underscore implies private or not really meant for direct access. Why would the `name` property I define be considered private?

### What does the proposed API look like?
Some ideas in order of preference:

1) What I think matches most devs' expectations
```
export default {
  name: 'my-component',
  mounted() {
    console.log(`${this.$options.name} mounted`)
  }
}
```

2) Stay close to standards and use the `tagName` property name, which could get it out of `$options` too
```
export default {
  tagName: 'my-component',
  mounted() {
    console.log(`${this.tagName} mounted`)
  }
}
```

3) Get rid of the underscore and align these two property names, could also enable getting it out of `$options`
```
export default {
  componentTag: 'my-component',
  mounted() {
    console.log(`${this.$options.componentTag} mounted`)
  }
}
```

**Comment by rickyruiz** [comment]
You can access the `name` property value using `this.$options.name`.

**Comment by posva** [comment]
as @rickyruiz said, you can already access it through `this.$options.name`

**Comment by jfbrennan** [comment]
Vue 2.6.11:
```
    mounted() {
      console.log(`${this.$options.name} mounted`)
      console.log(`${this.$options._componentTag} mounted`)
    },
```

Chrome:
![Screen Shot 2020-05-08 at 11 07 43 AM](https://user-images.githubusercontent.com/1817868/81435138-30ad5880-911c-11ea-818a-f794aa037ca3.png)
