### ISSUE TITLE
Component is re-rendered when computed value stay same and its dep value changes.

### ISSUE THREAD

**Issue by 07akioni** [vuejs/vue#11399]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-computed-test-nc9s7?file=/src/App.vue](https://codesandbox.io/s/vue-computed-test-nc9s7?file=/src/App.vue)

### Steps to reproduce
Follow the link

### What is expected?
The render function shouldn't be called when its dependent computed value isn't changed.

### What is actually happening?
Every time the value changes, the component is re-rendered, even if the computed value is not changed.

**Comment by posva** [comment]
This is working as expected: the `render` happens because the computed property is marked as dirty because it depends on `value` which changed. Vue calls again the render function because it depends on the computed property and needs to reevaluate the value

**Comment by cinsanity** [comment]
> This is working as expected: the `render` happens because the computed property is marked as dirty because it depends on `value` which changed. Vue calls again the render function because it depends on the computed property and needs to reevaluate the value

So you can create another value value2 in data, then watch the value's change,  set the value2's value at the true time, use value2 in render function

**Comment by 07akioni** [comment]
> This is working as expected: the `render` happens because the computed property is marked as dirty because it depends on `value` which changed. Vue calls again the render function because it depends on the computed property and needs to reevaluate the value

I can understand it is by design. I wonder why if the value stays the same it still conceptually be treated as 'dirty'?

**Comment by rskvazh** [comment]
We got the same problem, this is not obvious and very strange behaviour that components rerenders when **computed** property was not changed.
And there is performance issues because of this. 
As a workaround we created watcher `prop2` on computed `prop1` and target `prop2` in component

**Comment by mnm1001** [comment]
is there any solution for this?

**Comment by joaopslins** [comment]
> We got the same problem, this is not obvious and very strange behaviour that components rerenders when computed property was not changed.

**Comment by joaopslins** [comment]
> We got the same problem, this is not obvious and very strange behaviour that components rerenders when computed property was not changed.

Encountered the same issue today, and it was very unexpected that, even if the computed property keeps the same value, the entire component is re rendered.

What is more frustrating is that, this is not easily accessible in the docs. The closest we have is a "When data changes" here: https://vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram
