### ISSUE TITLE
关于页面加载完毕监听

### ISSUE THREAD

**Issue by CrazyLevin** [vuejs/vue#11395]
### Version
2.6.11

### Reproduction link
[http://sitetest.seastad.com/trayton/#/](http://sitetest.seastad.com/trayton/#/)

### Steps to reproduce
我在项目中实现点击按钮跳转后想到页面的指定的标签位置（document.body.scrollTop = document.documentElement.scrollTop = this.$refs['ref'].$el.offsetTop）
不知道是不是我用法不对？

### What is expected?
希望可以在页面完全加载完后有这么一个钩子函数或方法

### What is actually happening?
但是这时页面还没加载完(mouted里执行)，跳转之后去的位置会不准确。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
