### ISSUE TITLE
Attribute inheritance broken for radio since 2.6.1

### ISSUE THREAD

**Issue by guidobouman** [vuejs/vue#11397]
### Version
2.6.11

### Reproduction link
[https://codepen.io/guidobouman/pen/OJyoGoZ?editors=1010](https://codepen.io/guidobouman/pen/OJyoGoZ?editors=1010)

### Steps to reproduce
1. Create a custom radio component that implements a native radio input
2. Use a model and a value, both on the same custom radio
3. Pass on the model & $attrs to the radio

### What is expected?
The value is passed on as default value, and the model is still working as intended. Just like with the default Vue setup.

### What is actually happening?
Since 2.6.1 the value attr is filtered out, or is assigned to the actual value of model. Depending wether or not you have the value prop defined on the custom radio component.

**Comment by posva** [comment]
This is working as expected: you need to declare the prop `value` . Here are the docs: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
You probably also want to set `inheritAttrs` to false (more on the docs)

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by guidobouman** [comment]
Hold on, I'm trying to tell you I tried that.

**Comment by guidobouman** [comment]
@posva: Check again, I've updated the repro with the value prop, it only break the repro further by preselecting all values.

I've used the docs at: https://vuejs.org/v2/guide/components-props.html#Disabling-Attribute-Inheritance

But this is now broken for radio inputs.

**Comment by posva** [comment]
I checked: you are using a prop `value` for two things: the v-model and the attribute of an input of type radio. You should name the prop that is used in v-model differently, then you could do `:value="$attrs.value"` (if no prop named `value` is added, otherwise do `:value="value"`). Note it's needed to explicitly add the binding of `value` to radio buttons (and checkboxes) so the value can be extracted by the compiler, even if you add `v-bind="$attrs"`

**Comment by guidobouman** [comment]
Yes, and then we're slowly landing on the workaround link:
https://codepen.io/guidobouman/pen/WNQgBMN?editors=1010

Which gives mutation errors.

**Comment by guidobouman** [comment]
I've taking en multi value bind from the docs as well:
https://vuejs.org/v2/guide/forms.html#Radio

**Comment by guidobouman** [comment]
And with the custom model implementation I would expect, it breaks again:
https://codepen.io/guidobouman/pen/rNOZEoq?editors=1010

**Comment by guidobouman** [comment]
@posva ☝️

**Comment by posva** [comment]
It's because you are emitting a string `@input="$emit('input', $event.target.value)"` but comparing to a number: `:checked="value === defaultValue"`. Do `@input="$emit('input', defaultValue)"` instead or use a computed with setter:


```js
Vue.extend({
    props: ["value", "defaultValue"],
    computed: {
      $value: {
        get: vm => vm.value,
        set(value) {
          this.$emit('input', value)
        }
      }
    },
    template: `
      <label>
        <input
          type="radio"
          v-model="$value"
          :value="defaultValue">
        {{ defaultValue || 'empty' }} / {{ value }} {{ typeof value }}
      </label>
  `
  })
```

**Comment by guidobouman** [comment]
Thanks. They were all copy & pastes from the documentation. Could've figured it out with common sense, though. Really thought this was a bug.
