### ISSUE TITLE
Component Created Having higher z index value does not gets destroyed

### ISSUE THREAD

**Issue by shivamguys** [vuejs/vue#11396]
### Version
2.6.11

### Reproduction link
[https://ibb.co/bWW5LS7  https://ibb.co/jWyrHQX](https://ibb.co/bWW5LS7  https://ibb.co/jWyrHQX)

### Steps to reproduce
try creating a div with higher z index from component and navigate another component

### What is expected?
To get destroyed

### What is actually happening?
it gets sticked

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
