### ISSUE TITLE
isBooleanAttr for the HTML attribute 'translate'

### ISSUE THREAD

**Issue by EtienneBruines** [vuejs/vue#11391]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/hgaL8t5n/](https://jsfiddle.net/hgaL8t5n/)

### Steps to reproduce
Use translate=no in a template

### What is expected?
template=no to be rendered in the HTML

### What is actually happening?
translate=translate is being rendered instead

You can use devtools to inspect the rendered HTML in the reproducible JSFiddle example. 

---
There is a isBooleanAttr-variable somewhere in the Vue code which marks `translate` as a boolean, probably to be used like the `disabled` attribute works. 

This is incorrect for two reasons:

1. "translate" is not a valid value for the attribute (only "", "yes" and "no" are valid). See the spec: https://html.spec.whatwg.org/multipage/dom.html#attr-translate
2. this translate-attribute is mostly used to indicate not to translate it, so when specifying "no", people actually mean "no"

**Comment by posva** [comment]
Maybe we should just remove it from the list. I don't know the reason it was initially added

**Comment by nowres** [comment]
Hi @EtienneBruines 
Can I take the issue?

**Comment by EtienneBruines** [comment]
Yes, please, go ahead.

**Comment by namett3** [comment]
uyguyg

**Comment by Jalkse** [comment]
Best<a href="https://apkinstallation.com/traffic-rider-mod-apk-free-download/"> solution f</a>or users

**Comment by quoctienlam2605** [comment]
Hello-word
