### ISSUE TITLE
How to quickly remove the watcher from an object while making a deep copy

### ISSUE THREAD

**Issue by zzcong** [vuejs/vue#11394]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/frosty-night-rlujg](https://codesandbox.io/s/frosty-night-rlujg)

### Steps to reproduce
Vuex USES strict patterns;
There is an array in Vuex that when I make a deep copy of 'slice()' and modify it, error will be reported when I submit it to 'mutation' change 'state' : 'error:Do not mutate vuex store state outside mutation handlers. ', looking at the error stack information, it was found that the error was reported when the callback function of 'watcher' was executed in the 'run()' method of 'watcher'. Finally, it was copied using 'json.parse () & json.stringify ()'.How to untag 'watcher' on this object without using 'json.stringify ()'
code: 
```
        // this.set_all_macuser === this.$store.commit('set_all_macuser')
        // error
        let macList = this.anchors.slice().map(v => {
          speaks.includes(v.uid * 1) ? v.isSpeak = true : v.isSpeak = false
          return v
        })
        this.set_all_macuser(macList)
        // right
        let list = JSON.parse(JSON.stringify(this.anchors))
        let macList = list.map(v => speaks.includes(v.uid * 1) ? v.isSpeak = true : v.isSpeak = false)
        this.set_all_macuser(macList)
```

### What is expected?
Provide a convenient way

### What is actually happening?
Console error

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
