### ISSUE TITLE
Please remove build dependency on rollup-plugin-flow-no-whitespace (depends on modules no longer maintained)

### ISSUE THREAD

**Issue by pravi** [vuejs/vue#11406]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/](https://github.com/vuejs/vue/)

### Steps to reproduce
One of the build dependencies is no longer maintained.

### What is expected?
Build dependencies should be maintained actively

### What is actually happening?
rollup-plugin-flow-no-whitespace depends on https://github.com/facebookarchive/flow-remove-types which is now an archived project. 

---
Babel 7 already includes plugin to remove flow annotations as @babel/plugin-transform-flow-strip-types. It is actually mentioned in .babelrc.js but it is not used. You could use rollup-plugin-babel to remove flow annotations instead.

**Comment by pravi** [comment]
flow-remove-types is still using babylon which is now @babel/parser.

**Comment by pravi** [comment]
vue-router is also in the same situation

**Comment by posva** [comment]
Thanks for the recommendation. We Wil remove whe e update babel and an replace it
