### ISSUE TITLE
Improving transition component through adding transition classes to the" transition wrapper" + trigger transition on custom prop  

### ISSUE THREAD

**Issue by Flothus** [vuejs/vue#11405]
### What problem does this feature solve?
It's complicated to get full control over transitions. Vue only targets changing elements. This leads to difficulties when unchanged items also need to be transitioned. 

**No simple way to trigger a transition component without a data change**
It is useful to have a way to trigger the transitions component via a custom-event-prop, not just when there is a data change. This is complicated for new users who might look for an easy way to transition components (e.g just on a click even if there is no data change -> to give visual feedback). To my knowledge, it's only possible via an if-condition or changing key workaround. 
Which seems not render efficient (but I don't know if Vue rebuilds the component entirely on key change or reuses it and just triggers the classes,  all the same), 

**No way to add transition classes to a component on component change**
To my knowledge, there is no easy way to control transitions before a component is updated and after. Users trying to add transitions to when only transitioning targeting elements is not enough might misunderstand Vue's lifecycle hooks for a way to update the real dom to trigger transitions.
And again group-transitions only handle enter/leaving elements.

### What does the proposed API look like?
**Have an option on the transition-group component to add transition classes similar to the enter/leave classes to the transition wrapper.**

Covers triggering transitions on elements that are not leaving/entering on rerender.
Maybe there could also be an option to target the wrapper of the page to allow for transitions on different elements when the transition component is triggered. But I haven't thought this through if this might cause unexpected/messy behavior /collisions with several transition components on the page.

```vue
<transition-group name="name" transitionWrapper/transitionAll/targetWrapper/target(transition)Component/targetPage> 
 ...
</transition> 
```

Will add classes to the transition wrapper to give more control over transitions e.g. `name-beforeOut`, `name-beforeIn`, `name-outActive`, `name-inActive`, `name-outTo`, `name-inTo`. Class naming might need more thought, though. Might also add `unchanged`class to remaining elements.

**Trigger transition on prop change**
Covers triggering transition on custom events. Only relevant if there is no change triggering the transition in the same lifecycle anyway.

```vue
<transition-group name="name" transitionTrigger> 
 ...
</transition-group> 
```

Triggers Out and In classes on the wrapper based on the mode (so mode on group transitions would need to work internally differently than on "single" transitions? It would be still be really great if there would be some kind of out-in mode for group-transition that handles all leaving elements at once and all entering once. There still could be a staggering option if needed?). 

```vue
<transition name="name" (targetPage) transitionTrigger mode="out-in"> 
 ...
</transition> 
```

Any ideas on this, or is there an easier Vueish way to do those things already?  I have to say that Vue's transition "blackbox" has been a bit frustrating to me. Especially on group-transitions and trying to remove leaving items from the dom, before new items enter. Which by default seems to be not possible. Or transition also unchanged items on a rerender. So at least with this we can get a bit more control and simplify some things hopefully without adding too much complexity?

**Comment by posva** [comment]
> No simple way to trigger a transition component without a data change

Use the `key` attribute on the element rendered by `transition` to force a transition. (this also works the same way as a prop`

> No way to add transition classes to a component on component change

You can use hooks and custom classes https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

The whole point of Transitions in Vue is to animate things entering and leaving the page (https://vuejs.org/v2/guide/transitions.html#Overview). You can apply animations to elements without Vue, by using CSS or libraries like Greensock and combine those tools with Vue to apply the transitions in a declarative way (eg a dynamic class)
