### ISSUE TITLE
Textareas are completelly cleared on form reset (IE/Edge)

### ISSUE THREAD

**Issue by STEREOH** [vuejs/vue#11404]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/xtha3pd6/](https://jsfiddle.net/xtha3pd6/)

### Steps to reproduce
- Use IE/Edge
- Make a form inside a vue instance.
- Add a textarea with some text in it.
- Add an input type reset

### What is expected?
The textarea, like the basic input, should be reseted to it's initial value on form reset. This works on all other browsers.

### What is actually happening?
The textarea content is completelly cleared.

---
Tested on IE11 and  Edge 42

**Comment by posva** [comment]
This is a browser specific behavior not related to Vue (removing Vue shows the same behavior). If it's not working on Edge Canary on Windows, you should report the bug to Edge

**Comment by STEREOH** [comment]
Hi @posva,

https://jsfiddle.net/oryv4u85/embedded/result,css,html,js   

in this example without vue, the textarea is correctly reseted to it's initial value.

**Comment by posva** [comment]
I mean it happens with raw JS as well: https://jsfiddle.net/2omagc75/
