### ISSUE TITLE
Unspecified error on IE 11

### ISSUE THREAD

**Issue by zl7261** [vuejs/vue#11414]
### Version
2.6.11

### Reproduction link
[https://github.com/zl7261/ytms-simple](https://github.com/zl7261/ytms-simple)

### Steps to reproduce
I use a computed variable to control the slide menu route open or off.
Pretty simple and works.

But on IE 11, it doesn't work.

### What is expected?
Slide Menu.

### What is actually happening?
Error log.

---
1. npm run serve access /login
2. the password component has a bug that will not accept init input, but when you blur and focus again, it will fix.
3. type any string to pass login.
4. click the left slide menu button.
5. here is error log on ie11
![image](https://user-images.githubusercontent.com/27967791/82998054-cc562880-a039-11ea-9f0b-07e66699548a.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

That's not a valid reproduction

**Comment by zl7261** [comment]
I put a debugger in vue.runtime.esm.js.
The result is that it is a calc style error cause by calc
```
   <slide-router class="layout-slide-menu"
                  :style="{ height: `calc(100% - ${menuFold ? '0' : '72px'})` }"
    />
```

which calc must have a space between ' - ' and  must have a 'px'.
