### ISSUE TITLE
createBundleRenderer throws an error: Cannot find module 'middleware.js'

### ISSUE THREAD

**Issue by StarkDevelopers** [vuejs/vue#11428]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
**I have provided an empty link to minimal reproduction because this requires Nuxt to build. I have provided reproduction steps using nuxt**

I have created Vue Application using: **npm create nuxt-app nuxt-ssr**

Then inside nuxt-ssr, I executed **npm run dev** which generates server.js inside .nuxt directory which is the server-side bundle.

Then I executed following NodeJS code to render the template using the above-generated **server.js**

    const vueRenderer = require('vue-server-renderer')

    try {
      const renderer = vueRenderer.createBundleRenderer('[ABSOLUTE_PATH]/nuxt-ssr/.nuxt/server.js', {
        runInNewContext: false
      });
      renderer.renderToString().then(x => console.log(x)).catch(e => console.error(e));
    } catch (e) {
      console.error(e);
    }

Which is not working. Because server.js is using ES6 Import syntax. I tried the following things to make it work.

1. I tried to use version < 13.0 with --experimental-modules flag while running node
2. version > 13.0 with type: module in package.json or with extension .mjs
3. I tried to convert server.js to ES5 using Babel and then used it
4. Also, tried to use dynamic import

None of them are working.

Can anyone please help me with this? Let me know if you need more information.

### What is expected?
The server-side bundle should get rendered without any errors.

### What is actually happening?
It is not able to find modules like: Cannot find module 'middleware.js' from '[ABSOLUTE_PATH]/nuxt-ssr/.nuxt'

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is also directly related to Nuxt, not Vue. You might want to open an issue there instead
