### ISSUE TITLE
:max parameter dosn't work when its value is 1 

### ISSUE THREAD

**Issue by thomaslwq** [vuejs/vue#11424]
### Version
2.6.11

### Reproduction link
[https://codepen.io/thomaslwq/pen/abdoZXM](https://codepen.io/thomaslwq/pen/abdoZXM)

### Steps to reproduce
            1. use the component keep-alive
            2. set the max(1) component for cache
            3. the max parameter dosen't work

### What is expected?
when the max parameter is 1,it works

### What is actually happening?
it doesn't work

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/9972

Please, search for existing issues first 🙂
