### ISSUE TITLE
Checkbox check state is incorrect

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#11429]
### Version
2.6.0~2.6.11

### Reproduction link
[https://codepen.io/yangdan8/pen/XWXrQGW](https://codepen.io/yangdan8/pen/XWXrQGW)

### Steps to reproduce
反复点击复选框,发现复选框选中状态和显示的选中状态值不一致
Click the checkbox repeatedly, and find that the checkbox selected state and the displayed selected state value are inconsistent

### What is expected?
复选框选中状态和显示的选中状态值相同
The check box selected state is the same as the displayed selected state value

### What is actually happening?
复选框选中状态和显示的选中状态值不一致
Check box selection status and displayed selection status value are inconsistent

---
由于2.6.0修复chebox的bug引起的新的问题
在2.0.x～2.5.x都没有这个问题
New problems caused by bug fixing chebox in 2.6.0
There is no such problem in 2.0.x~2.5.x

**Comment by yangdan8** [comment]
![image](https://user-images.githubusercontent.com/16515026/83519614-e3e85200-a50e-11ea-8eef-87fff303ee99.png)

**Comment by posva** [comment]
Please check existing issues https://github.com/vuejs/vue/issues?q=is%3Aissue+checkbox+state+is%3Aclosed and release notes (https://github.com/vuejs/vue/releases/tag/v2.6.0) before opening an issue
