### ISSUE TITLE
BeforeDestroy and Destroy hooks are not emitted once Web Component Vue component is out of DOM

### ISSUE THREAD

**Issue by kamilzielinskidev** [vuejs/vue#11430]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/reqfy064/](https://jsfiddle.net/reqfy064/)

### Steps to reproduce
1. Create Vue Web Component using Vue Cli with destroy and beforeDestroy hooks which console logs 123.
2. Use the component in Angular with angular-extension/elements.
3. Render the site with component
4. Switch to another route

### What is expected?
To console log 123

### What is actually happening?
Component still exists besides removing it from DOM/ no 123 logged.

---
Same implementation works with native solution and lit-element disconnectedCallback

**Comment by posva** [comment]
If the Dom is removed without calling `$destroy` like Vue would when it removes its content, `destroyed` won't be called. If the library you are using is manually removing the DOM, they need to call `$destroy` first

**Comment by f1nality** [comment]
Hi @posva How to call $destroy from outside? There is DOM element only

**Comment by f1nality** [comment]
@kamilzielinskidev did you manage to resolve this issue?

**Comment by yoyo837** [comment]
> If the Dom is removed without calling `$destroy` like Vue would when it removes its content, `destroyed` won't be called. If the library you are using is manually removing the DOM, they need to call `$destroy` first

I use `MutationObserver` to manually call $destroy after the custom component is removed. Now, I have a case which that a custom component contains a nother custom component. After the parent component is removed, which instance of `$destroy` should I call first? The parent's or the children's to make it respect Vue lifecycle behavior?
 (parent's `beforeDestroy` --> children's `beforeDestroy`--> children's `destroyed` --> parent's `destroyed`)
