### ISSUE TITLE
safari :   TypeError: null is not an object (evaluating 't.salt')

### ISSUE THREAD

**Issue by azhai2016** [vuejs/vue#11437]
### Version
2.6.11

### Reproduction link
[http://www.enhwa.com/home](http://www.enhwa.com/home)

### Steps to reproduce
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.2.3 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: ^4.2.0 => 4.2.3 
    @vue/cli-plugin-eslint: ^4.2.0 => 4.2.3 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ^4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.15.5 => 8.15.5 
    vue-infinite-scroll: ^2.0.2 => 2.0.2 
    vue-loader:  15.9.0 
    vue-qr: ^2.2.1 => 2.2.1 
    vue-route: ^1.5.1 => 1.5.1 
    vue-router: ^3.1.6 => 3.1.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.1.3 => 3.1.3 
  npmGlobalPackages:
    @vue/cli: 4.3.1

### What is expected?

safari : 
TypeError: null is not an object (evaluating 't.salt')

### What is actually happening?
... 

S = r.PasswordBasedCipher = _.extend({
                        cfg: _.cfg.extend({
                            kdf: x
                        }),
                        encrypt: function(e, t, n, r) {
                            r = this.cfg.extend(r);
                            var i = r.kdf.execute(n, e.keySize, e.ivSize);
                            r.iv = i.iv;
                            var a = _.encrypt.call(this, e, t, i.key, r);
                            return a.mixIn(i), a
                        },
                        decrypt: function(e, t, n, r) {
                            r = this.cfg.extend(r), t = this._parse(t, r.format);
                            var i = r.kdf.execute(n, e.keySize, e.ivSize, t.salt);  --there
                            r.iv = i.iv;
                            var a = _.decrypt.call(this, e, t, i.key, r);
                            return a
                        }
                    })

...

**Comment by posva** [comment]
Please, take the time to read what's said at https://new-issue.vuejs.org/?repo=vuejs/vue

That is not a valid reproduction
