### ISSUE TITLE
Detect modifiers order in custom directives

### ISSUE THREAD

**Issue by johlug** [vuejs/vue#11432]
### What problem does this feature solve?
The guide says that the order of the modifiers in event directive matters (https://vuejs.org/v2/guide/events.html).  

In custom directives I get the modifiers by the modifiers object (s. https://vuejs.org/v2/guide/custom-directive.html 1). So there it’s not possible to detect the order.  

I have already made an "Get help" issue (https://forum.vuejs.org/t/custom-directives-detect-modifiers-order/96587) and got no answer.  

With this feature I would have more control over modifiers in custom directives.

### What does the proposed API look like?
modifiers could be simply put in an array, like
['modifier1', 'modifier2']

**Comment by posva** [comment]
Don't you have the order with `Object.keys(modifiers)`?

**Comment by jacekkarczmarczyk** [comment]
https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/

> This also means that you have to be careful with this method, though, and shouldn't rely on a predictable order using Object.keys because the results may vary depending on the browser implementation

**Comment by johlug** [comment]
When order matters, you should always go with array. 
In a way an array is an indexed object like {1: val1, 2: val2} :)

**Comment by Nandiin** [comment]
You can get a `rawName` on the second argument in your directive hook functions.

```js
// say there's a snippet of template code <foo v-bar.a.b/>
Vue.directive('bar', {
    bind(el, binding, vnode, oldVnode) {
        assert(binding.rawName === 'v-bar.a.b')
    }
})
```

And FYI, the documentation of event modifiers you linked is quite different from a custom directive under the hood. Event handlers specified by `v-on` directive, with its possible modifiers, are compiled directly into event handling code, and special modifiers like `prevent`, `self` are handled case by case.

**Comment by johlug** [comment]
Thank you @Nandiin! 
Your answer works. 
I would prefer a better way to detect the order, but I can make a helper function based on the rawName to achieve this.

**Comment by Nandiin** [comment]
Directives in template code are handled by the compiler with following code, and unfortunately, there is no other preservation of the information about modifiers order:
https://github.com/vuejs/vue/blob/ef56410a2ca19641bd96bbc04056219fbc0bcb3e/src/compiler/parser/index.js#L906-L913

It's guaranteed that modifiers are added to the `modifiers` object in the order they are presented in template code, but whether `Object.keys(modifiers)` would return them in the same order is out of my knowledge. I suspect we cannot get a guarantee on that, at least in near future, as long as the browser on which the product is to be run is unpredictable.
