### ISSUE TITLE
安卓低版本 报错

### ISSUE THREAD

**Issue by yangzhaoguo** [vuejs/vue#11448]
### Version
2.6.11

### Reproduction link
[https://tmc.himyidea.com/m_hotel/#/HotelHome](https://tmc.himyidea.com/m_hotel/#/HotelHome)

### Steps to reproduce
Cannot call method 'call' of undefined  白屏网站打不卡， 已经使用过

### What is expected?
解决方法

### What is actually happening?
页面白屏不兼容 安卓4.4

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
