### ISSUE TITLE
src/compiler/codegen/index.js

### ISSUE THREAD

**Issue by clone-git** [vuejs/vue#11440]
### What problem does this feature solve?
function hash(str) {
  let hash = 5381
  let i = str.length
  while(i) {
    hash = (hash * 33) ^ str.charCodeAt(--i)
  }
  return hash >>> 0
}

### What does the proposed API look like?
function hash(str) {
  let hash = 5381
  let i = str.length
  while(i) {
    --i
    hash = (hash * 33) ^ str.charCodeAt(i)
  }
  return hash >>> 0
}
不建议在方法调用中或与其他算术运算符结合使用递增和递减运算符

**Comment by posva** [comment]
> 不建议在方法调用中或与其他算术运算符结合使用递增和递减运算符

You didn't even say why. Anyway, this is not a valid issue (https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn)

**Comment by clone-git** [comment]
代码写的不规范  这个不是bug  只是坏味道
