### ISSUE TITLE
Expose Props to Prop validation

### ISSUE THREAD

**Issue by panteparak** [vuejs/vue#11445]
### What problem does this feature solve?
Currently Prop Validation take a function that received the value of that specific prop. The problem with that, there is no way to cross validate other prop values and raised errors when they do not meet the condition. By passing in the entire component props, it would also allow the requested feature to be fulfilled. 

React also supports this out of the box (https://reactjs.org/docs/typechecking-with-proptypes.html)
Their api is as follows
```
  customProp: function(props, propName, componentName) {
    if (!/matchme/.test(props[propName])) {
      return new Error(
        'Invalid prop `'   propName   '` supplied to'  
        ' `'   componentName   '`. Validation failed.'
      );
    }
  },
```

### What does the proposed API look like?
Currently the api is as follows, 
```
validator: function (value) {
...
}
```

My proposed api
```
validator: function (value, props) {
}
```

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/6787 and https://github.com/vuejs/vue/issues/9467
