### ISSUE TITLE
keep-alive

### ISSUE THREAD

**Issue by PT-github** [vuejs/vue#11447]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/ecstatic-lumiere-mmr44](https://codesandbox.io/s/ecstatic-lumiere-mmr44)

### Steps to reproduce
多级路由嵌套缓存问题（keep-alive嵌套keep-alive）
1.假如这边有二级路由（Parent1（下有Child1和Child2）、Parent2（下有Child3和Child4））
  
2.除了Child2不缓存，其他界面都需要缓存。通过路由的meta中keepAlive来判断是否缓存，并且通过keep-alive中的exclude排除了Child2的组件name

页面在Child1和Child2进行切换时，Child2不会缓存
但是当从Child2跳转到Child3时，Child2会被缓存，当然原因是父组件Parent1被缓存了，render渲染时会获取cache中对应的vnode节点

### What is expected?
希望能够对上述这种情况处理，或者可以提供对应的API能够删除父组件中不需要缓存的子组件

### What is actually happening?
实际父组件缓存了 子组件无法清除缓存

**Comment by posva** [comment]
As you noted, this is expected because the parent is kept-alive and the child is never removed, so when you come back it's still there

**Comment by PT-github** [comment]
> As you noted, this is expected because the parent is kept-alive and the child is never removed, so when you come back it's still there

是的，的确是因为父级keep-alive缓存导致的，有没有什么方式能够让我手动的清除子节点的缓存呢，其实像我上述的这种场景在业务上是会存在的。

**Comment by wenzhaobing** [comment]
我也遇到这种情景了，请问有解决方案吗？
