### ISSUE TITLE
Snyk reports vue-server-renderer@2.6.11 > serialize-javascript@2.1.2 security issue

### ISSUE THREAD

**Issue by alfredriesen** [vuejs/vue#11442]
### What problem does this feature solve?
Please update a dependency serialize-javascript@2.1.2 from vue-server-renderer@2.6.11 for security reasons.

### What does the proposed API look like?
No API. Just an update.

**Comment by posva** [comment]
See https://github.com/vuejs/vue/pull/11434

Please check existing issues before creating a new one
