### ISSUE TITLE
®在 <slot> 上使用 v-if 没有效果不工作

### ISSUE THREAD

**Issue by CongAn** [vuejs/vue#11441]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/anker/27nwbr84/2/](https://jsfiddle.net/anker/27nwbr84/2/)

### Steps to reproduce
在`html`中使用`slot v-if`没有任何效果，但是在`js`中使用`template`的`slot v-if`是正常。

无法使用v-if的例子
```
<template>
  <div>
    <slot v-if="render"></slot>
  </div>
</template>
<script>
export default {
  data () {
    return {
      render: false,
    }
  },
</script>
```
可以使用 v-if 的例子
```
<script>
export default {
  template: '<div><slot v-if="render"/></div>',
  data () {
    return {
      render: false,
    }
  },
</script>
```

### What is expected?
v-if 正常的使用

### What is actually happening?
v-if 无法工作

**Comment by posva** [comment]
`v-if` does work. Make sure to use the latest version when reporting a bug and provide a proper reproduction: https://jsfiddle.net/8fqyx6aj/

The `template` tag you were using should be outside of `#app`

**Comment by CongAn** [comment]
@posva 
https://jsfiddle.net/anker/27nwbr84/3/
