### ISSUE TITLE
seed.js: TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by despire1119** [vuejs/vue#11444]
### Version
2.6.11

### Reproduction link
[http://agent.dejipay.com](http://agent.dejipay.com)

### Steps to reproduce
使用vue-cli创建项目并运行(使用yarn安装依赖和启动项目)

### What is expected?
不报错，正常启动。

### What is actually happening?
启动正常但报错

seed.js:2 TypeError: Cannot read property 'resolve' of undefined

seed.js:2 Uncaught TypeError: Cannot read property 'resolve' of undefined

Error handling response: TypeError: Cannot read property '1' of null

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by despire1119** [comment]
Thx for reply.But I supposed that the question is the bug in vue or vuecli.

**Comment by Justineo** [comment]
See: https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro
