### ISSUE TITLE
v-model freeze

### ISSUE THREAD

**Issue by crucifyer** [vuejs/vue#11458]
### Version
2.6.11

### Reproduction link
[https://framework.xenosi.de/exams/ovaisjdofasdjf.html](https://framework.xenosi.de/exams/ovaisjdofasdjf.html)

### Steps to reproduce
Input v-model may freeze when a system window such as confirm or alert is called and then closed with esc.
It is normalized when the system window is called again and then the close button is clicked, or it is returned after moving to another tab.

### What is expected?
don't freeze

### What is actually happening?
freeze

**Comment by posva** [comment]
This is how the browser works when it comes to alerts and confirms

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
