### ISSUE TITLE
Documentation points at a cdn link that contain different versions

### ISSUE THREAD

**Issue by asfaltboy** [vuejs/vue#11451]
### Version
2.6.11

### Reproduction link
[https://vuejs.org/v2/guide/](https://vuejs.org/v2/guide/)

### Steps to reproduce
Go to "getting started" docs , and copy one of the urls, they should match the stable version (2.6.11), however these are:

* https://cdn.jsdelivr.net/npm/vue/dist/vue.js - version v3.0.0-beta.14 (must ignore cache)
* https://cdn.jsdelivr.net/npm/vue - version v2.6.11

Ref: https://vuejs.org/v2/guide/

### What is expected?
Expected both to have version 2.6.11

### What is actually happening?
The dist version (which should be the stable 2.6 version) is not downloaded, and instead we get 3.0 beta 14

**Comment by posva** [comment]
Checked and it seems to be good now

**Comment by jacekkarczmarczyk** [comment]
Hmm i'm getting opposite (3.0 on https://cdn.jsdelivr.net/npm/vue and 2.6.11 on https://cdn.jsdelivr.net/npm/vue/dist/vue.js)

![image](https://user-images.githubusercontent.com/15625235/84374159-e6693c80-abdd-11ea-894f-5d8f87683e2b.png)
![image](https://user-images.githubusercontent.com/15625235/84374379-32b47c80-abde-11ea-99fd-80ec49e41c9d.png)

**Comment by asfaltboy** [comment]
@posva did you clear the cache, it still has the wrong version. Please look at te screenshot ^

Correct @jacekkarczmarczyk, got the links/versions mixed up sorry (edited ticket)... any reason one of these needs to be 3.0?

**Comment by MartinKolarik** [comment]
Hi, Martin from jsDelivr here. I purged the cache for that link and it should return v2.6.11 in all locations now. I suppose version v3.0.0-beta.14 was accidentally tagged as "latest" on npm for some time recently but now "latest" points to v2.6.11 again.
