### ISSUE TITLE
src/core/vdom/patch.js :509

### ISSUE THREAD

**Issue by Panamer** [vuejs/vue#11459]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js](https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js)

### Steps to reproduce
debugger

### What is expected?
Lines 509 through 511 are useless and should not appear

### What is actually happening?
Line 509 is always false. Because the types of oldVnode and VNode are object

---
I tried a number of scenarios, including keep-alive.oldvNode === vnode, which is always false.                                                                    
So I think the judgment here is redundant. If I'm wrong, please show me the proof
I'm curious what scenario is true
thanks.

**Comment by posva** [comment]
Thank you but that statement seems to be necessary unless done somewhere else. You could probably try to remove it and run tests to see the proof

**Comment by Panamer** [comment]
Can you tell me when the condition is true? I want to know, day and night.
Thank you very much

**Comment by sirlancelot** [comment]
> You could probably try to remove it and run tests to see the proof

**Comment by Panamer** [comment]
I know the answer. Thank you @sirlancelot @posva
