### ISSUE TITLE
Watching deep changes in Vuex causes: [Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Nastalgua** [vuejs/vue#11452]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1. Create a deep watch of a store state (In my case, a array of objects) and set options `deep: true` (Error does not show when `deep: false`, however it is need for my application)
2. Make some sort of change to that state.
3. Error appears:
```
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"
```
```
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at _traverse (vue.runtime.esm.js?2b0e:2121)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
    at _traverse (vue.runtime.esm.js?2b0e:2123)
```

### What is expected?
Error should not be appearing.

### What is actually happening?
Error is showing as well as the freezing of my entire Vue app.

---
This error was able to be fixed adding an addition conditional to a conditional in the _traverse method of vue.runtime.esm.js.
```
if ((!isA && !isObject(val)) || Object.isFrozen(val) || val instanceof VNode || val._isVue)
```
(val._isVue was added)

**Comment by posva** [comment]
That's not a valid reproduction.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
