### ISSUE TITLE
Can't get componentInstance property of vnode when using the v-slot directive on a <template>.

### ISSUE THREAD

**Issue by Xie-Jay** [vuejs/vue#11464]
### Version
2.6.11

### Reproduction link
[https://github.com/Xie-Jay/slot-issue](https://github.com/Xie-Jay/slot-issue)

### Steps to reproduce
I show issue by console.

### What is expected?
All vnode can get componentInstance property.

### What is actually happening?
ComponentInstance property is undefined when using the v-slot directive, but others not.

```html
<slot-test>
  <component-test slot="default" name="slot1"></component-test>
</slot-test>
<slot-test>
  <template slot="default">
    <component-test name="slot2"></component-test>
  </template>
</slot-test>
<slot-test>
  <template v-slot:default>
    <component-test name="slot3"></component-test>
  </template>
</slot-test>
```

![image](https://user-images.githubusercontent.com/64340763/84982701-d1eeec00-b169-11ea-921b-a3d0cb96184f.png)

---
When I use v-slot to replace slot, I get this diffrence which really confuse me.

**Comment by posva** [comment]
I'm not sure you are supposed to use `componentInstance` from the returned vnode. You can still get the component instance through `$children[0]`

**Comment by Xie-Jay** [comment]
> I'm not sure you are supposed to use `componentInstance` from the returned vnode. You can still get the component instance through `$children[0]`

It's useful for me to build component that need control components in slot by using `componentInstance`.

I tried to use `$children`, it's ok when just one slot.

But more than one, it will be difficult to separate these components in slot by using `$children`.

In fact, I have no idea except that provide extra `prop` to distinguish them, because there’s no order guarantee for `$children`.

**Comment by hanotao** [comment]
@rubys @rubys @rubys @rubys 666
