### ISSUE TITLE
Transition with async conditional render dont respect out-in mode

### ISSUE THREAD

**Issue by backbone87** [vuejs/vue#11467]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/an5kydfr/](https://jsfiddle.net/an5kydfr/)

### Steps to reproduce
1. In the fiddle switch from A to B

### What is expected?
B faded in only after A is fully faded out

### What is actually happening?
B starts fading in while A is still fading out

---
Switching from B to A in the fiddle, does not have this issue.

Using a dynamic component does not have this problem: https://jsfiddle.net/0w2nuL38/
Sadly, this workaround is not feasable for my actual use-case.

**Comment by posva** [comment]
The mode out-in is for elements that are switching but in your case, because of the else-if and the delay, one disappears without anything replacing it, so it starts disappearing and then the next one starts appearing. You can change the condition to make them properly swap:

```vue
<div v-if="content === 'content-a' || !loaded" key="content-a">
        Hello from A
      </div>
      <div v-else key="content-b">
        B says hello
      </div>
```

**Comment by backbone87** [comment]
@posva
your modification wastes time, by staying on A until B is fully loaded, while in reality i want ot start loading B immediately while A is fading out, and the condition to start fading in B is "a fully faded out && b loaded".

also no content is valid for transition:
```
transition(mode="out-in")
  div(v-if="display")
    | Toggle content
```
so the model of transition is: "one or no child" and my example satisfies this at all times.

besides all of that: what is the reason to not try to make it work for the presented use-case?
