### ISSUE TITLE
transition enter hook is Not working as expected

### ISSUE THREAD

**Issue by FeiFanLiang** [vuejs/vue#11462]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/comcdm/6Lbp43tm/18/](https://jsfiddle.net/comcdm/6Lbp43tm/18/)

### Steps to reproduce
if i dont use setTimeout,no entering animation,Whether it is used v-if or v-show,i dont know what happened.

### What is expected?
if i set element style in enter hook, should do entering animation

### What is actually happening?
but no animation in entering

**Comment by posva** [comment]
you need to wait for the browser to render the element before changing its opacity. Otherwise it won't be able to trigger a transition:

```js
requestAnimationFrame(() => {
        el.style.opacity = 1;
      })
```

**Comment by FeiFanLiang** [comment]
but use vue 2.5.9 it can work,so did you make any adjustments?

**Comment by FeiFanLiang** [comment]
> you need to wait for the browser to render the element before changing its opacity. Otherwise it won't be able to trigger a transition:
> 
> ```js
> requestAnimationFrame(() => {
>         el.style.opacity = 1;
>       })
> ```

is work thank you
