### ISSUE TITLE
File extension is .js but typescript is used in file

### ISSUE THREAD

**Issue by lopugit** [vuejs/vue#11461]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/src/core/observer/index.js](https://github.com/vuejs/vue/blob/dev/src/core/observer/index.js)

### Steps to reproduce
Open that link

### What is expected?
either a .js file with only javascript or a .ts file with either only javascript or typescript too

### What is actually happening?
Get typescript in a .js file

---
How are you meant to intellicode this file in vscode?

**Comment by Justineo** [comment]
We are using Flow in our codebase. This is expected.
