### ISSUE TITLE
Compiled CSS is incorrect (SCSS in single file component, using calc() with custom property)

### ISSUE THREAD

**Issue by AngusMacrae** [vuejs/vue#11466]
### Version
2.6.11

### Reproduction link
[https://github.com/AngusMacrae/solar-system-explorer](https://github.com/AngusMacrae/solar-system-explorer)

### Steps to reproduce
In the "client" folder, run "npm install" to install dependencies, then "npm run serve". Navigate to http://localhost:8080/ in your browser. Inspect one of the .planet-system elements and find the .orbit div within it. Note that in the style browser, the following line is applied:

    top: calc(var(--diameter-vw) / 2 - var(--orbit-diameter) / 2);

This is accurate to the scoped SCSS in the .vue Single File Component source file.

Now either run "npm run build" and spin up a local webserver, or you can just navigate to https://solar-system-explorer.netlify.app/ which is where I have deployed the site. The site is deployed directly from the /client/dist folder in the GitHub repo, the contents of which were generated by running "npm run build".

Inspect the same .orbit element as before. But now, you'll find that the following line is different:

    top: calc(var(--diameter-vw) - var(--orbit-diameter));

This line is not correct.

### What is expected?
I expect the two lines to be the same. The latter should be the same as the former because they are compiled from the same source .vue file.

### What is actually happening?
The CSS rule that is applied in my deployed app is not correct, resulting in breaking the visual appearance of the app.

**Comment by posva** [comment]
That's not a valid reproduction, it's a whole project. It could just be related to SCSS.

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
