### ISSUE TITLE
ref name and data name should not use the same namespace

### ISSUE THREAD

**Issue by xialvjun** [vuejs/vue#11460]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-namespace-4rxh5](https://codesandbox.io/s/vue-namespace-4rxh5)

### Steps to reproduce
Look the link console warning... 

ref name and data name shouldn't use the same namespace. Yeah, we shouldn't bind all things to this!!!

### What is expected?
there shouldn't be vue warning

### What is actually happening?
there is vue warning

**Comment by pikax** [comment]
This is not related to `vue` 

The warning is because you're trying to set a value to a `computed` on `<div id="app" ref="list">`

If you remove `ref="list"` is doesn't warn. 

Please read the [docs](https://composition-api.vuejs.org/api.html#template-refs).
