### ISSUE TITLE
<div v-bind:title="foo" >   doas not work on firefox

### ISSUE THREAD

**Issue by bashery** [vuejs/vue#11465]
### Version
2.6.11
### browser
firefox

### Steps to reproduce

\<div id="app-2"\>
  \<span v-bind:title="message"\>
    Hover your mouse over me for a few seconds
    to see my dynamically bound title!
  \<\/span\>
\<\/div\>

var app2 = new Vue({
  el: '#app-2',
  data: {
    message: 'You loaded this page on ' + new Date().toLocaleString()
  }
})

<div v-bind:title="foo" >   doas not work on firefox

### What is expected?
show title message when I hover mouse on element

### What is actually happening?
nothing on firefox
but it is working on chromium

**Comment by posva** [comment]
Yo might have deactivated something but it does work.

---

Remember we have a [forum](http://forum.vuejs.org/) and a [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by bashery** [comment]
oh! Sorry.
I discovered that the problem is not in Vue.
The problem is because some of the Firefox freezes.
After rebooting everything became good.
Thank you.
