### ISSUE TITLE
Access env variables from a prototype var

### ISSUE THREAD

**Issue by WendellAdriel** [vuejs/vue#11471]
### What problem does this feature solve?
It reduces the number of characters to type and also to use env variables in a "JS way" inside our applications.

### What does the proposed API look like?
Instead of calling `process.env.VUE_APP_MY_VAR` everywhere, it would be like this: `this.$env.myVar`.
I thought about two approaches to this:

```
// this.$env.myVar being a read-only property, just to get the value
const myVar = this.$env.myVar
// this.$env would return an object with all variables
const env = this.$env
```

```
// this.$env being a function
const myVar = this.$env('myVar')
const myVarWithDefault = this.$env('myVar', 'default')
const env = this.$env()
```

**Comment by posva** [comment]
This can be achieved in user land by setting `Vue.prototype.$env = process.env`
It does depend on how you setup the environment variables thought but this should still go in a plugin
