### ISSUE TITLE
When building library SCSS variables aren't being translated to CSS ones.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [vuejs/vue#11475]
### Version
2.6.11

### Reproduction link
[https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html.](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html.)

### Steps to reproduce
I just begin writing components library according to https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html.
When I finish writing and build I couldn't use library then I looked into js and css files. Unfortuantely, I see the SCSS variables in CSS file.

I have wrapper JS and imported components.
I use installing method of plugin.
Then exported.

I've src/components/component/component.vue and src/components/component.scss.
I imorted  SCSS file in the component like this:
<style lang="scss" scoped>
@import "./component.scss"
</style>

### What is expected?
Seeing SCSS variables as CSS variables.

### What is actually happening?
Seeing SCSS variables in CSS.

---
I think there is something small to do again. But what? I think answer should be simple and I am missing something in my opinion.
FYI: I add sass-loader, css-loader, svg-loader, node-sass .

**Comment by OtabekSadiridinov** [comment]
I found what's being here. I think this is because the component.scss file.
I imported another SCCS file into it to use some variables, mixins and styles.

I imported it like below
```scss
@import '../../assets/style-mixins/global-mixin.scss';
```
and used a mixin and variable from it like this:
```scss
.some-heading {
    @include no-heading-defaults;
    padding: 12px 25px;
    color: white;
}

.bg-primary {
    background:  $primary;
}
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
If the docs are outdated, please open an issue in the docs repository (vuejs/vuejs.org), please open an issue there
