### ISSUE TITLE
Vue.js is transferring click from one link <a> to another

### ISSUE THREAD

**Issue by hryanjones** [vuejs/vue#11474]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/buxojec/edit?html,js,output](https://jsbin.com/buxojec/edit?html,js,output)

### Steps to reproduce
1. create a Vue app with two links `<a>` in the template
2. one link ("external link") with an href that's hidden by a state variable in the app
3. another link ("flip the state") that's shown by the opposite state that has a `v-on:click` handler that flips the state
4, click the "flip the state" link

In case the repro link doesn't work, here's the code:
```html
<div id="container">
  <a 
     v-if="happened"
     href="https://duckduckgo.com/?q=weird&ia=definition"
     target="_blank"
     >
    external link
  </a>

  <a 
     href="#"
     v-on:click="makeItHappen"
     v-if="!happened"
     >
    flip the state
  </a>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
```

```js
  vueApp = new Vue({
    el: '#container',
    data: {
      happened: false,
    },
    methods: {
      makeItHappen(event) {
        // event.preventDefault(); // uncommenting this fixes it
        this.happened = true;
      }
    }
  });
```

### What is expected?
It's expected that the "external link" becomes visible, but no other action.

### What is actually happening?
The link is becoming visible and then is being triggered to open it in a new page.

---
Thanks for working on Vue! It's a very fun framework to use :D

**Comment by jacekkarczmarczyk** [comment]
You need `key`

```html
<div id="container">
  <a 
     v-if="happened"
     href="https://duckduckgo.com/?q=weird&ia=definition"
     target="_blank"
     key="1"
     >
    external link
  </a>

  <a 
     href="#"
     v-on:click="makeItHappen"
     v-if="!happened"
     key="2"
     >
    flip the state
  </a>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
```

**Comment by hryanjones** [comment]
Just curious, without the key is Vue determining that the <a> that's
roughly in the same place in the UI is the same one?

Thanks!

**Comment by posva** [comment]
By default Vue reuses the elements and in this case the a is reused in the middle of a click. Using a key is indeed the way to go.

See https://github.com/vuejs/vue/releases/tag/v2.6.0 and the important internal changes section

**Comment by hryanjones** [comment]
Ah, that makes sense. Thank you!
