### ISSUE TITLE
how could I use http2 protocol in vue

### ISSUE THREAD

**Issue by SRC-xiaojin** [vuejs/vue#11476]
### What problem does this feature solve?
As I know, I could use http2 protocol in node. how could u use it in vue?

### What does the proposed API look like?
like axios module

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
This question is also unrelated to Vue as the http protocol happens on the server
