### ISSUE TITLE
How to convert a dom object into a vue component

### ISSUE THREAD

**Issue by Vi-jay** [vuejs/vue#11477]
### What problem does this feature solve?
I now have many cached image dom objects, and I want to replace the root node of the component with the dom object after the component is loaded

### What does the proposed API look like?
please help me

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
