### ISSUE TITLE
slot will render  multiple times

### ISSUE THREAD

**Issue by pikadun** [vuejs/vue#11489]
### Version
2.6.11

### Reproduction link
[https://codepen.io/pikadun/pen/ExPoGjq?editors=1111](https://codepen.io/pikadun/pen/ExPoGjq?editors=1111)

### Steps to reproduce
Open console, it will print 0 to 101.

### What is expected?
print only one time.

### What is actually happening?
print multiple times

**Comment by posva** [comment]
By calling the method inside of the template every render, you are tracking the `count` value and changing at the same time, so it triggers a new render.
If `count` is not reactive, you can move it outside, in the `created`:


```js
created () {
this.count = 0
}
```

That way it won't trigger new renders
