### ISSUE TITLE
Spelling errors found with CodeSpell 1.17.1

### ISSUE THREAD

**Issue by warmsocks** [vuejs/vue#11480]
Edit: markdown formatting
### Version
2.6.11

### Reproduction link
[https://github.com/warmsocks/vue/commit/8b18bdca7c61da779d65b681de557e9e24c29a93](https://github.com/warmsocks/vue/commit/8b18bdca7c61da779d65b681de557e9e24c29a93)

### Steps to reproduce
1. Install codespell.  1.17.1 is current as of this writing.  Instructions and info here:  https://github.com/codespell-project/codespell
1. Clone vue repo, ensure you are on dev branch
1. Run codespell, ignoring generated objects, the .git dir and quiet warnings about binary files:
```vue (dev *=) $ codespell -q2 --skip  packages,node_modules,dist,.git,coverage```

### What is expected?
Codespell should not find any real spelling errors.

### What is actually happening?
Codespell finds a handful of misspellings.  Ignoring false hits from things like variable names, it finds these:
```
./src/compiler/parser/index.js:383: anyting ==> anything
./types/umd.d.ts:10: backword ==> backward
./test/unit/features/directives/on.spec.js:283: modifers ==> modifiers
./test/unit/features/directives/on.spec.js:408: build-in ==> built-in
./test/unit/features/directives/on.spec.js:423: build-in ==> built-in
./flow/weex.js:31: informations ==> information
```

---
I have a fix.  I will submit a PR.

You might consider adding codespell checking, with proper exclusions, to npm test to reduce the chance of additional spelling errors in the future.

**Comment by posva** [comment]
Thanks for finding the spelling errors but please submit pull requests instead? Issues are for big reports and feature requests only
