### ISSUE TITLE
How to dynamic import a Vue.use

### ISSUE THREAD

**Issue by vortechron** [vuejs/vue#11485]
### Version
2.6.11

### Steps to reproduce
```
import('vue-form-generator')
            .then(VueFormGenerator => {
                Vue.use(VueFormGenerator);
            })
```

above code will not work, I already googled but still not found. please help me

### What is expected?
the component is available on the page

### What is actually happening?
the component cannot be used because it will be called after `new Vue()`

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
