### ISSUE TITLE
Evaluating v-for in recursive component behaves differently in production and development mode

### ISSUE THREAD

**Issue by MoritzW3L** [vuejs/vue#11486]
### Version
2.6.11

### Reproduction link
[https://github.com/MoritzW3L/VueRecursiveIssue](https://github.com/MoritzW3L/VueRecursiveIssue)

### Steps to reproduce
1.) Clone the Repo
2.) Run `npm i`
3.) 
  a) run `npm run serve` and observe the output
  b) run `npm run serve_prod` and observe the outputs
4.) Compare the two outputs

### What is expected?
The Rendering should not change behaviour between the two modes.  
In case of the minimal Example, either all recursive elements should always be rendered (optimal) or they should not be rendered regardless of mode. (Would require my code/approach to change but consistency is the issue for me here.)

### What is actually happening?
In development-mode all recursive elements are rendered.
If started in production-mode. any recursive rendering is disabled.

---
- I used typescript and vue-property-decorator in my example but filed it under Vue. I hope this is acceptable as I dont think there should be too much impact those decisions should have.
- Repository was created using vue-cli selecting only Typescript and using class syntax.
- If there is a workaround, the edge-case section of the docs does not describe it.
- In my minimal reproduction I provided the scripts: 'serve' and 'serve_prod' for easy testing of the issue.

**Comment by posva** [comment]
You need to name recursive components:

```js
@Component({
  name: 'RecursiveControl',
})
export default class RecursiveControl extends Vue {
  @Prop({ required: true }) readonly data!: DataDTO
}
```
