### ISSUE TITLE
unescaped HTML in a for loop

### ISSUE THREAD

**Issue by sebalaini** [vuejs/vue#11491]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/xenodochial-villani-wdgfh?file=/src/App.vue](https://codesandbox.io/s/xenodochial-villani-wdgfh?file=/src/App.vue)

### Steps to reproduce
as you can see from the repo a component with slot accepts raw HTML but when used in a v-for loop the returned data it's escaped and the HTML element is not printed correctly, if the data contains HTML it printed in the DOM as a string.

### What is expected?
to print the given raw HTML data 

### What is actually happening?
it prints the data in the dom with escaped HTML and doesn't display correctly an anchor element for example

---
I don't remember the reason right now but seems we don't want to use v-html and we want to use a slot to pass the data.

**Comment by posva** [comment]
The escaping is intended when using text interpolation (`{{}`). You will have to use `v-html` pass raw HTML like that.

---

Remember there is the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
