### ISSUE TITLE
Incorrect warning "avoid using JavaScript keyword as property name: if"

### ISSUE THREAD

**Issue by lonesomebyte537** [vuejs/vue#11499]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/tintin77/b3voj7er/](https://jsfiddle.net/tintin77/b3voj7er/)

### Steps to reproduce
When using a javascript expression with an if statement inside an event handler, vue reports incorrectly not to use javascript keywords as property names. See jsfiddle console (beta)

### What is expected?
No warning

### What is actually happening?
A warning

**Comment by sirlancelot** [comment]
Inside templates, you are only allowed to type an expression. `if` is a statement. Create a method.

**Comment by posva** [comment]
The warning is correct. You should use a method instead or write it as a ternary

**Comment by lonesomebyte537** [comment]
Thanks... As a newbie, I was not aware of this limitation. A more appropriate warning would then be 'Inside templates, you are only allowed to use expressions, no statements'.
