### ISSUE TITLE
Potential XSS DOM attack code in updateDOMProps method

### ISSUE THREAD

**Issue by ng-aneesh** [vuejs/vue#11498]
### What problem does this feature solve?
```updateDOMProps()``` method contains the line  ```svgContainer.innerHTML = "<svg>"   cur   "</svg>";```  which can be a potential source for XSS DOM attacks, as the element's value is not being properly sanitized or validated

### What does the proposed API look like?
Use
```
svgContainer.textContent  = "<svg>"   cur   "</svg>";
```
Instend of
```
svgContainer.innerHTML = "<svg>"   cur   "</svg>";
```

**Comment by yyx990803** [comment]
This only happens when the developer explicitly binds `v-bind:innerHTML.prop="xxx"`, so it is the developer's responsibility to make sure they are only binding this to trusted content. This is same as `v-html` or `dangerouslySetInnerHTML` in React.
