### ISSUE TITLE
New version of Named Slots (v-slot) broke router-view

### ISSUE THREAD

**Issue by gilles-crealp** [vuejs/vue#11497]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/bug-router-view-in-named-slot-5i0m2?file=/src/App.vue](https://codesandbox.io/s/bug-router-view-in-named-slot-5i0m2?file=/src/App.vue)

### Steps to reproduce
In `App.vue` (in CodeSandbox) you can toggle commented lines 11 & 13.

`router-view` is correctly displayed in the slot `main` using `slot="main"` but not anymore with `v-slot:main`.

### What is expected?
`router-view` with `v-slot:main` should be displayed in the slot `main` (green background in CodeSandbox).

### What is actually happening?
`router-view` with `v-slot:main` is displayed in the slot `default` (red background in CodeSandbox).

**Comment by posva** [comment]
You need to put the `v-slot` on a template

```vue
 <template v-slot:nav>
      <router-view />
      </template>
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by gilles-crealp** [comment]
I'm dumb, thx!
