### ISSUE TITLE
State variables doesn't update changes

### ISSUE THREAD

**Issue by nicolanilomartinoph** [vuejs/vue#11496]
### Version
2.6.11

### Reproduction link
[https://github.com/nicolanilomartinoph/skillTree_nonSPA](https://github.com/nicolanilomartinoph/skillTree_nonSPA)

### Steps to reproduce
1. Create a state and add some variables
2. change one of the variable( delete, change spelling, add a variable)
3. Save file
4. npm run watch
5. CTRL   F5 your browser
3. Go to Chrome vue extension and click Switch to vuex
4. You'll notice that your changes doesn't reflect

Few things can happen:
1. delete variables still show
2. A change in spelling/letter case will result in 2 variable of both old and new spelling/case difference

### What is expected?
For all changes to reflect on chrome vue extension

### What is actually happening?
Changes to the state can result in old and changed variables names.

In the source file, the code is no longer there but if you go to the chrome extension, it still shows there. 

---
I was simply changing the variable in the state so it would make more sense then the bug stated to happen. I notice in the vuex chrome extension that I have duplicate of the old variable and new variable name.

I am also using plugins: [createPersistedState()] if that helps. 
I cannot debug properly because I'm not use if the new variable name takes effect or that old one is still out there. 

To be

**Comment by posva** [comment]
That's not a valid reproduction as asked for in https://new-issue.vuejs.org.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
