### ISSUE TITLE
Dynamic-and-async component works unless produced from a function call

### ISSUE THREAD

**Issue by Quelklef** [vuejs/vue#11492]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/9uj5nc8m/69/](https://jsfiddle.net/9uj5nc8m/69/)

### Steps to reproduce
- Define one component with `<component :is="asyncComponent"></component>` where `asyncComponent` is an async component constructor such as `() => Promise.resolve({ template: "<p>I've rendered!</p>" })`
- Define another component with `<component :is="makeAsyncComponent()"></component>` where `makeAsyncComponent` *returns* an async component constructor

### What is expected?
Both components properly render

### What is actually happening?
Only the first component properly renders. The second component falls into an infinite update loop without ever properly rendering.

---
The docs are unclear as to whether or not dynamic-and-async components are allowed.

[The docs say say](https://vuejs.org/v2/guide/components.html#Dynamic-Components) that for a dynamic component, the `:is` prop should evaluate to "either: [the] name of a registered component, [or] a component's option object".

This doesn't allow the possibility of `:is` returning an [async component constructor](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components), which is a function returning a promise. Despite this, my example shows that a dynamic-and-async component *does* work sometimes (but only sometimes).

Because the docs are unclear, I can't actually claim that this is certainly a bug. If dynamic-and-async components are intended to work, it is. If they are not, then Vue should disallow the case that happens to work and/or print a warning in the console.

**Comment by posva** [comment]
We need a function declared outside of the template (like asyncComponent) to cache the dynamic import. If you think docs are unclear, please open a pull request with your proposal at vuejs/vuejs.org

**Comment by Quelklef** [comment]
That makes sense. The docs are mostly clear, what I was missing is that async components are *specifically* for use with lazy imports.

My use-case has nothing to do with imports; in fact, it doesn't even make sense to cache the components I am loading. I'm just dynamically rendering a bunch of components whose construction happens to be async operation.

Sounds like async components aren't appropriate for this, which is somewhat disappointing. Oh well.
