### ISSUE TITLE
A not operator (!) in a template breaks hot reloading

### ISSUE THREAD

**Issue by dr-nyt** [vuejs/vue#11504]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/drnyt/sxj18w49/7/](https://jsfiddle.net/drnyt/sxj18w49/7/)

### Steps to reproduce
- NPM version 6.14.5
- vue create vue-todo

    ```
    <template>
      <div class="hello">
        {{name}}
        {{btnState ? "The button is disabled" : "The button is active"}}
        <button
          v-on:click="changeName"
          v-bind:disabled="btnState"
        >CHANGE NAME</button>
      </div>
    </template>

    <script>
    export default {
      name: "Skills",
      data() {
        return {
          name: "Coursetro",
          btnState: true
        };
      }
    };
    </script>
```

- Adding the not operator (!) to the following line:

    `{{btnState ? "The button is disabled" : "The button is active"}}`

    to

    `{{!btnState ? "The button is disabled" : "The button is active"}}`

    works and prints button is active, but removing the not operator (!) at this point would stop hot reloading.

- You can open the same link `http://localhost:8080/` in another tab without restarting and it will work again until you repeat the steps above.

### What is expected?
Hot reload stays active after removing a not operator (!) from the template.

### What is actually happening?
Hot reload stops working after removing the not operator (!) from the template.

---
- Works fine on JSFiddle

Tested on:
- Google Chrome | Version 83.0.4103.116 (Official Build) (64-bit)
- Microsoft Edge (Chromium) | Version 83.0.478.58 (Official Build) (64-bit)

**Comment by posva** [comment]
I tried locally with that example and it worked.

---

Remember there is a [forum](http://forum.vuejs.org/) and a [Discord chat](https://vue-land.js.org/) to ask questions!
