### ISSUE TITLE
Setting image src to '...' produces an unrelated error message

### ISSUE THREAD

**Issue by cioccarellia** [vuejs/vue#11500]
### Version
2.6.11

### Reproduction link
[https://github.com/cioccarellia/vue-isrc-mr](https://github.com/cioccarellia/vue-isrc-mr)

### Steps to reproduce
- Clone the given repository, and then serve the project.
- Alternatively, on any vuejs project, set the `<img>`  `src` property to be `...`

### What is expected?
A clean error message, saying that the developer set the image `src` property to `...` (Maybe copying some placeholder code),  which does not point to anything, and reporting the developer attention to the right file and right line number.

### What is actually happening?
A completely unrelated error message is printed out, regarding the `cache-loader` module, which was not even installed in my package.
I may suggest (though, my Vue knowledge is limited about how it works this deep down, so take it with a grain of salt) that Vue is actually trying to parse the `...` string as a module name or cache id, and it isn't finding any match.

---
I copied some code from https://getbootstrap.org because I needed to recreate a specific design for a project, but then caught up in something else, and assumed that the code I copied would have worked. (With placeholder text and without any image, but it would have worked.)
Instead of checking the web app, I went on working and coding other things and later I got the error you can check on the repository.
```
ERROR  Failed to compile with 1 errors                                                                                                                                                                     11:42:48 PM

This dependency was not found:

* ... in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"2deff992-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=template&id=7ba5bd90&

To install it, you can run: npm install --save ...
```

I tried nearly everything, from running `npm clean-install`, to removing my OS cache folder and rebooting, and then removing / downgrading modules, until I finally went back to older commits in my git history. Thankfully I could narrow it down and get why it wasn't working, but anyway I've thrown away a couple of hours and raised my stress level over the standard Monday average :)
I'd have never though that Vue would misbehave so much for such an html error, and it will be nice if it'd be fixed.

**Comment by posva** [comment]
This would be nice but it's not in Vue's hand. If it's added anywhere, it should be at the loader (file-loader maybe) level

**Comment by MRVDH** [comment]
Thanks for this. I had the same exact issue and wouldn't have figured it out otherwise. I reported it in the vue-loader repo now. https://github.com/vuejs/vue-loader/issues/1720
