### ISSUE TITLE
Vue Official documents bug

### ISSUE THREAD

**Issue by zhangs5** [vuejs/vue#11505]
### Version
2.6.11

### Reproduction link
[https://cn.vuejs.org/v2/guide/transitions.html](https://cn.vuejs.org/v2/guide/transitions.html)

### Steps to reproduce
new Vue({
  el: '#flip-list-demo',
  data: {
    items: [1,2,3,4,5,6,7,8,9]
  },
  methods: {
    shuffle: function () {
      this.items = _.shuffle(this.items)
    }
  }
})

### What is expected?
fix it

### What is actually happening?
过渡和动画部分的文档说明中，在列表排序过渡部分，展示的shuffle 功能不能正常运行

---
no

**Comment by posva** [comment]
It works correctly.
When reporting a problem of the docs do it on Vuejs/vuejs.org repository and be clear about what is expected vs what is happening
