### ISSUE TITLE
async event `this.` can't get the new data ,but this  can get the latest data（异步事件执行完后 无法通过this. 的方式获取data的最新数据）

### ISSUE THREAD

**Issue by jadepam** [vuejs/vue#11506]
### Version
2.6.11

### Reproduction link
[https://codepen.io/jadepam-the-bashful/pen/XWXqXoQ](https://codepen.io/jadepam-the-bashful/pen/XWXqXoQ)

### Steps to reproduce
页面初次加载执行fn1方法，fn异步方法未执行完，重新进入页面执行fn2，fn2执行完后，更新this数据（this.$set 更新数据任然无效，直接将数据挂载在window上f1可获取最新数据）；fn1执行完，在fn1方法中无法通过`this.`获取最新的数据，但是打印出this对象时，可以看到数据已经是最新。
1、mounted do fn1，the  fn1 unfinished ，
2、mounted do fn2，the fn2 finished，update this.url
3、fn1 finished , can't get the new data by this.url，consloe.log(this)  can get the latest data

### What is expected?
f1 can get the latest data

### What is actually happening?
f1 can’t get the latest data

**Comment by jadepam** [comment]
![image](https://user-images.githubusercontent.com/12556231/86932270-bb85f000-c16b-11ea-88ab-d582c19a706d.png)
![image](https://user-images.githubusercontent.com/12556231/86932298-c2acfe00-c16b-11ea-8afe-02d21178f4f9.png)

**Comment by posva** [comment]
Please provide a valid boiled down reproduction as described in the issue helper when opening a big report
