### ISSUE TITLE
hydrate router-view lazy-loaded component

### ISSUE THREAD

**Issue by zhouxianjun** [vuejs/vue#11514]
### Version
2.6.11

### Reproduction link
[https://github.com/zhouxianjun/vue-prerender-test](https://github.com/zhouxianjun/vue-prerender-test)

### Steps to reproduce
1. Use vue ui to create a new vue, vue-router project
2. Add the prerender-spa-plugin plugin in vue.config.js
3. Add data-server-rendered="true" on the pre-rendering page
4. Start the serve static server in the dist directory
5. Browse pre-rendered pages

### What is expected?
Use pre-rendered static element blending

### What is actually happening?
When there is a router view in app.vue and an asynchronous component is used, the hydrate will determine that the element does not match vue, so the current element will be deleted and the element rebuilt

![image](https://user-images.githubusercontent.com/5254523/87494599-016a1900-c682-11ea-986e-315691aea08e.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You repro doesn't run but it should be reported on the https://github.com/chrisvfritz/prerender-spa-plugin repository. I imagine you need to wait for the navigation to be finished and the view to be rendered

**Comment by zhouxianjun** [comment]
Ok, I have solved it. Use onReady of vue-router
