### ISSUE TITLE
Vue log warnings to console.warn instead of console.error

### ISSUE THREAD

**Issue by vegerot** [vuejs/vue#11513]
### Version
2.6.11

### Reproduction link
[https://github.com/vueschool/vuejs-components-fundamentals/commit/3a90eeace5d3f8c01b5c989bd47850a96510eb51](https://github.com/vueschool/vuejs-components-fundamentals/commit/3a90eeace5d3f8c01b5c989bd47850a96510eb51)

### Steps to reproduce
Currently, when I get a Vue "warn"ing like
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "groupBy"

found in

---> <OpsSidebarTab> at src/components/a/b/c.vue
```

### What is expected?
The warning should go to `console.warn`

### What is actually happening?
The warning goes to `console.error`

---
To duplicate the issue, check out the link, then mutate one of the props in the example.

Currently, when I get a Vue "warn"ing like
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "groupBy"

found in

---> <OpsSidebarTab> at src/components/a/b/c.vue
```
It actually logs it to console.error.

How can I instead make warnings log to console.warn instead?

I know I could do `Vue.config.warnHandler`, but I don't know how to get it be the same format as the regular Vue output.  For example, would I do something like

```ts
Vue.config.warnHandler = fucntion (msg, vm, trace) {
  console.warn(`[Vue warn]: ${msg}\nfound in\n--->${trace}`)
}
```
?

Are there ever other formats I have to worry about?  I wish I could just redirect these errors to `console.warn` without having to reformat them

**Comment by mehtaanshul** [comment]
Can i take this @posva @vegerot ?

**Comment by vegerot** [comment]
btw, it turns out if you want to make this change yourself, the way they implement this is [here](https://github.com/vuejs/vue/blob/38e967b8067441ff37cb3b923200023a6b842759/src/core/util/debug.js#L24).  So if you want to do this yourself just put in your `App.vue` something like

```typescript
if (process.env.NODE_ENV !== 'production' && typeof console !== 'undefined') {
  Vue.config.warnHandler = function (msg: string, vm: Vue, trace: string) {
         console.error(`[Vue warn]: ${msg}${trace}`)
  };
}
```

This resolves the worry I had with not accurately handling other format.  But has the problem that this may change in the future without me worrying about it.

I actually took this opportunity to add some more things to make my development experience easier:

```typescript
if (!process.env.production) {
  Vue.config.warnHandler = function (msg: string, vm: Vue, trace: string) {
    // `trace` is the component hierarchy trace
    console.warn(`[Vue warn]: ${msg}\n${trace}\n\nProps:\n\n--->\t${JSON.stringify(vm.$props)}`);
  };
}
```

Now, I can see the props that were related to a particular warning, which I've found very helpful!!

**Comment by ygj6** [comment]
I noticed that the warning goes to [console.warn](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/warning.ts#L68) in vue 3. I would like to add a PR for this little isuuse.

**Comment by posva** [comment]
This could break code relying on a specific std output, so it's better to keep it this way in Vue 2
