### ISSUE TITLE
npm run serve report the core-js error in muti page project when i import ant-design-vue

### ISSUE THREAD

**Issue by miniai** [vuejs/vue#11512]
### Version
2.6.11

### Reproduction link
[https://github.com/miniai/demo.git](https://github.com/miniai/demo.git)

### Steps to reproduce
git clone https://github.com/miniai/demo.git
npm install
npm run serve

### What is expected?
npm run serve success

### What is actually happening?
These dependencies were not found:

core-js/library/fn/array/from in ./node_modules/babel-runtime/core-js/array/from.js
core-js/library/fn/get-iterator in ./node_modules/babel-runtime/core-js/get-iterator.js
core-js/library/fn/is-iterable in ./node_modules/babel-runtime/core-js/is-iterable.js
core-js/library/fn/object/assign in ./node_modules/babel-runtime/core-js/object/assign.js
core-js/library/fn/object/define-property in ./node_modules/babel-runtime/core-js/object/define-property.js
core-js/library/fn/symbol in ./node_modules/babel-runtime/core-js/symbol.js
core-js/library/fn/symbol/iterator in ./node_modules/babel-runtime/core-js/symbol/iterator.js
To install them, you can run: npm install --save core-js/library/fn/array/from core-js/library/fn/get-iterator core-js/library/fn/is-iterable core-js/library/fn/object/assign core-js/library/fn/object/define-property core-js/library/fn/symbol core-js/library/fn/symbol
/iterator

---
https://github.com/vueComponent/ant-design-vue/issues/2554

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for vue bug reports and feature requests only. This is a project setup question. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by miniai** [comment]
em... i reduced some package's version, it works
