### ISSUE TITLE
$slots cannot print out the slots using Scoped Slots

### ISSUE THREAD

**Issue by hengshanMWC** [vuejs/vue#11511]
### Version
2.6.11
### Steps to reproduce
Using the slot of Scoped Slots, $slots will not print the slot

### What is expected?
Using Scoped Slots slots, $slots will not be affected

### What is actually happening?
Using the slot of Scoped Slots, $slots will not print the slot

---
If the transition component of vue3 is written with transition, the entry animation will be triggered immediately

![image](https://user-images.githubusercontent.com/45714422/87291587-218ac280-c532-11ea-9fce-8df904a1822f.png)

![image](https://user-images.githubusercontent.com/45714422/87291620-28b1d080-c532-11ea-88e6-f94747fb93a6.png)

![image](https://user-images.githubusercontent.com/45714422/87291622-2c455780-c532-11ea-9fec-ef238a04007e.png)

![image](https://user-images.githubusercontent.com/45714422/87291634-30717500-c532-11ea-8060-439e105334e9.png)

![image](https://user-images.githubusercontent.com/45714422/87291646-336c6580-c532-11ea-9678-6edcbbee0a6d.png)

**Comment by Justineo** [comment]
Please provide a [valid reproduction](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro). Thanks.

**Comment by mqhe2007** [comment]
我遇到了同样的问题。

**Comment by coderja** [comment]
我也遇到了同样的问题 请问如何结局
