### ISSUE TITLE
Infinite recursion when deep watching structure with mounted vue component instance

### ISSUE THREAD

**Issue by callumgare** [vuejs/vue#11515]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/callumgare/n5skd1tm/11/](https://jsfiddle.net/callumgare/n5skd1tm/11/)

### Steps to reproduce
See jsfiddle in minimal reproduction field. Bug can be reproduced by adding a vue component instance to a data object. Deep watching that data object then causes the recursion. 

### What is expected?
Don't traverse further if vue component instance.

### What is actually happening?
Traverse function recurses until crash.

---
I have a fix ready to submit as a pull request when/if this issue is approved.

**Comment by posva** [comment]
Your data should be a plain object, it shouldn't nest Vue instances.
You can add data as non enumerable to make Vue skip it:


```js
const data = {
    message: 'Hello Vue.js!',
    deepTree: {
    	a: {
      	b: DemoComponent // This causes the error because the traverse func loops between DemoComponent._
      }
    }
  }
  
Object.defineProperty(data.deepTree.a, 'b', {
value: DemoComponent,
enumerable: false

})
```

in Vue 3, there is also a `markRaw` function
