### ISSUE TITLE
v-if和自定义指令同时使用导致指令失效的问题。

### ISSUE THREAD

**Issue by yyjiugui** [vuejs/vue#11521]
### Version
2.6.11

### Reproduction link
[https://github.com/yyjiugui/commiterror](https://github.com/yyjiugui/commiterror)

### Steps to reproduce
```javascript
<template>
	<div class="home">
		<p v-if="auth">我是权限按钮 v-if实现</p>
		<p v-auth="auth">我是权限按钮 自定义指令实现</p>
		<!-- <p v-if="$has(auth)">Vue原型对象上$has权限方法</p>  加上这句代码 页面渲染的结果不一样 指令失效了？  -->
		<button type="button" @click="auth = !auth">按钮</button>
	</div>
</template>

<script>
// @ is an alias to /src

export default {
	name: 'Home',
	data() {
		return {
			auth: false
		}
	}
}
</script>



import Vue from 'vue'
Vue.directive('auth', {
	inserted(el, binding) {
		if (!Vue.prototype.$has(binding.value)) {
			el.parentNode.removeChild(el)
		}
	}
})

// 判断按钮是否有权限
Vue.prototype.$has = function(value) {
	return value
}


```

### What is expected?
通过指令移除的按钮,不会因为组件状态更新，导致指令失效。

### What is actually happening?
自定义指令不会正常工作。

---
复现代码：https://github.com/yyjiugui/commiterror

**Comment by posva** [comment]
You shouldn't manually change the DOM that is controlled by Vue. Otherwise Vue won't be able to correctly change it again

**Comment by yyjiugui** [comment]
thank you

**Comment by stanJ** [comment]
I met this question too when I use `v-if ` and `v-fixed` together. Then I use `<div></div>` to wrap my custom directive `v-fixed`. It works.
