### ISSUE TITLE
Define watcher directly when defining data property

### ISSUE THREAD

**Issue by tipputhynhean** [vuejs/vue#11525]
### What problem does this feature solve?
Imagine we have a function that build a form model for us base on some input.

```
data () {
    return {
      formErrors: formErrorsModel()
    }
}
```
If we want to watch those field, we need to define it separately from the function that generate the model. I think it would make sense to define it directly on the data itself.

### What does the proposed API look like?
```
data () {
    return {
      formErrors: {
         value: 'some value',
         watch: function () {}
      }
    }
}
```

**Comment by posva** [comment]
This would limit objects defined in `data`. If it's something you want to create in your own project you can still create a global mixin that checks the `data` properties in a `created` hook through `$data` and creates the watchers for you
