### ISSUE TITLE
Legacy code with typescript

### ISSUE THREAD

**Issue by devTeaa** [vuejs/vue#11526]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/laughing-mirzakhani-s6qho](https://codesandbox.io/s/laughing-mirzakhani-s6qho)

### Steps to reproduce
Sorry for the no reproduction link, but I only need an explanation or guidance. I'm trying to convert my company project into TS, unfortunately we manually use webpack with it's config to compile vue. I've installed typescript on the project with it's config, and upgrade vue to 2.6.11, we also use vue-template-compiler. I annotate my data variable with a type, but on method it didn't properly annotated, it converted to any. Is there something I missed? I have used Vue.extend({ ... })

### What is expected?
The data type annotated works as expected

### What is actually happening?
The type didn't get annotated properly

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by devTeaa** [comment]
if anyone faced this issue, the problem is on the tsconfig, try using the one on vue-cli and tinker it to fit your project needs
