### ISSUE TITLE
Dynamic Slot Names are converted to lowercase

### ISSUE THREAD

**Issue by grofzero** [vuejs/vue#11528]
### Version
2.6.11

### Reproduction link
[https://codepen.io/grofzero/pen/mdVQZXr](https://codepen.io/grofzero/pen/mdVQZXr)

### Steps to reproduce
Try to use the v-slot directive with a dynamic attribute that is in camelcase like: <template v-slot:[slotName]>  then slotName is converted to lowercase.

### What is expected?
To be able to use the v-slot directive with camelcased dynamic attributes

### What is actually happening?
Throws an error, that the lowercased variable is not defined on the instance but referenced during render.

**Comment by jacekkarczmarczyk** [comment]
This is html limitation
Use SFC files or https://codepen.io/jkarczm/pen/NWxEZOy?editors=1010
