### ISSUE TITLE
input.value don't change when I implement character filter logic in @input event

### ISSUE THREAD

**Issue by chiyanhui** [vuejs/vue#11529]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/chiyanhui/682edwqc/23/](https://jsfiddle.net/chiyanhui/682edwqc/23/)

### Steps to reproduce
Enter 1234dddxxx123 in first input
Enter 1234dddxxx123 in second input
Enter 1234dddxxx123 in third input

### What is expected?
input should only show digits

### What is actually happening?
the first input and third input show letters until a new digit entered

---
Filter user input(Restrict users to only enter numbers). I can set e.target.value, but what can I do when I use Component library like vuetify.

**Comment by posva** [comment]
This is expected: if nothing triggers a render (not actually changing the original value), the input will not apply the old value and let the user change it. Manually changing the `.value` of the input to force it is the way to go.
