### ISSUE TITLE
Mutating a prop directly check lost when I mutating props on a  mutable object like Arroy or Object.

### ISSUE THREAD

**Issue by HuberTRoy** [vuejs/vue#11530]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/embed/musing-kirch-ss507?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/musing-kirch-ss507?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
When I mutating a prop directly on children component the expect behavies are give an error `[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "test"`, but if the prop are mutable and I change it's value and not change it's 
reference the error was lost and the `computed set handler` was lost too.

### What is expected?
Throw an error.

### What is actually happening?
No error throwed.

---
Chilren components mutating the prop and I want to cache the old value but I cannot do it, beacuse the chilren components mutatiing the prop directly and bypass the checker.

**Comment by posva** [comment]
This is expected for objects because they are passed by reference in JS

**Comment by HuberTRoy** [comment]
@posva 
Thanks, I have another question. When I mutating it the computed set handler were not called too, this computed depened on this prop.  Would the computed set handler need to be called since Vue allow this behavior ?

**Comment by posva** [comment]
Please use the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to ask questions 🙂

**Comment by HuberTRoy** [comment]
@posva 

Thanks.
Post it on [StackOverflow](https://stackoverflow.com/questions/63010116/mutating-a-mutable-prop-directly-the-computed-set-handler-were-not-called).
