### ISSUE TITLE
Vue SSR v-html on dynamic-component hydration warning

### ISSUE THREAD

**Issue by privatenumber** [vuejs/vue#11532]
### Version
2.6.11

### Reproduction link
_This reproduction uses NUXT for convenience, but is reproducible outside of NUXT._

[https://github.com/privatenumber/vue-ssr-vhtml-dyncomp-bug](https://github.com/privatenumber/vue-ssr-vhtml-dyncomp-bug)

### Steps to reproduce
_Dynamic.vue_
```vue
<template>
  <component is="div">
    content necessary
  </component>
</template>
```

_App.vue_
```vue
<template>
  <dynamic v-html="'<div>trigger hydration warning</div>'" />
</template>
```

### What is expected?
The expected behavior is for there to be no hydration warning when the SSR and client markup are identical.

### What is actually happening?
Although there isn't a discrepancy in rendered HTML between client and SSR, it gives warnings that there is.

![warningD](https://user-images.githubusercontent.com/1075694/88136132-a28f2d00-cbb6-11ea-84db-f38d0bf3adf3.png)
![warningE](https://user-images.githubusercontent.com/1075694/88136136-a327c380-cbb6-11ea-81e6-b3830645de60.png)

### Work around
I used a [render function](https://vuejs.org/v2/guide/render-function.html) instead of a dynamic-component:
```
render(h) {
    return h(this.component, [this.$slots.default]);
}
```

**Comment by posva** [comment]
Couldn't reproduce with a plain vue js SSR:

```js
// Step 1: Create a Vue instance
const server = require('express')()
const renderer = require('vue-server-renderer').createRenderer()
const Vue = require('vue')

const DynamicCompWrapped = {
  template: `
  <div>
    <component
      is="div"
      class="dynamic-comp-wrapped"
    >
      Some content
    </component>
  </div>
`,
}

const DynamicCompContent = {
  template: `
  <component
    is="div"
    class="dynamic-comp-content"
  >
    Some content
  </component>
  `,
}

const DynamicCompEmpty = {
  template: `
   <component
    is="div"
    class="dynamic-comp-empty"
  />
  `,
}

server.get('*', (req, res) => {
  const app = new Vue({
    data: {
      url: req.url,
    },
    template: `
    <div>
    <dynamic-comp-empty v-html="'A. no warn'" />

    <dynamic-comp-empty v-html="'<div>B. no warn</div>'" />

    <dynamic-comp-content v-html="'C. no warn'" />

    <dynamic-comp-content v-html="'<div>D. warn</div>'" />

    <dynamic-comp-wrapped v-html="'E. warn'" />

    <dynamic-comp-wrapped v-html="'<div>F. no warn</div>'" />
  </div>
  `,
    components: { DynamicCompContent, DynamicCompEmpty, DynamicCompWrapped },
  })

  renderer.renderToString(app, (err, html) => {
    if (err) {
      res.status(500).end('Internal Server Error')
      return
    }
    res.end(`
      <!DOCTYPE html>
      <html lang="en">
        <head><title>Hello</title></head>
        <body>${html}</body>
      </html>
    `)
  })
})

server.listen(8080)
```

This could be related to Nuxt, if you manage to reproduce outside of it, please open a new issue with a reproduction.

**Comment by privatenumber** [comment]
@posva 

It's not a rendering error -- it's a client-side hydration warning.

This bug was discovered in a non-NUXT code-base, and reproduced in NUXT for convenience.
