### ISSUE TITLE
Element client dimensions reported wrongly.

### ISSUE THREAD

**Issue by AlastairGrowcott** [vuejs/vue#11539]
### Version
2.6.10

### Reproduction link

My code is too complicated to break down into a simple fiddle. I am really not experienced enough to create one. I am happy to work with you to debug the issue. If you ignore all issues from people who struggle with creating minimal reproduction examples in an environment they are unfamiliar with you will end up with lots of bugs. I have spent a lot of time to make this bug report as thorough as possible to compensate for the lack of a fiddle.

I even tried to create a fiddle, but could not figure out what to click to generate a link to paste here. Yes, I am a fiddle noob! I am sure it is one of those things that is REALLY obvious once you know how, but I was expecting to see a big button with "GENERATE LINK" in large letters. There isn't one.

### Steps to reproduce

I am creating a web app as a single non-scrollable page and am finding myself needing to exercise a lot of control on element sizes. There are tables within tables and some cells are explicitly pixel sized and some are percentage sized.

I am using Firefox.

One of these tables within a table (within a table) contains 6 identical Vue components (with different IDs so that they get fed with different data)  based on a canvas. The Firefox element inspector reports all the elements as having the same height as each other (as they are all in cells in the same row this is expected) and as the cells that contain them.

In the mounted() function of the component I do this:

        var el = this.$el;
        this.context = el.getContext("2d");
        this.context.canvas.width = el.clientWidth;
        this.context.canvas.height = el.clientHeight;

I have also tried putting the above code in a Resize() function and doing the following in mounted():

        setTimeout(this.Resize.bind(this), 1000);

I have also tried using $nextTick().

### What is expected?
The canvas is resized to the element size. Drawing, which is based on the size of the canvas is correct. The drawn content displays crisply and perfectly.

### What is actually happening?
el.clientHeight is being reported incorrectly and the canvas is being stretched to fit the element's real size. The display is fuzzy and poor.

Adding debug as follows:

        console.log("ID="   el.id   ", w="   el.clientWidth   ", h="   el.clientHeight   ", pw="   el.parentElement.clientWidth   ", ph="   el.parentElement.clientHeight);

outputs the following:

    ID=port_swivel, w=74, h=291, pw=82, ph=291
    ID=port_thrust, w=74, h=293, pw=82, ph=293
    ID=ballast, w=74, h=295, pw=82, ph=295
    ID=stbd_thrust, w=74, h=297, pw=82, ph=297
    ID=stbd_swivel, w=74, h=299, pw=82, ph=299
    ID=light_power, w=66, h=301, pw=74, ph=301

Firefox reports the real element size as 300.55.

---
I found this article which is where I got the idea of using a timeout - as reported it didn't help.

https://github.com/vuejs/Discussion/issues/394

If I add similar debug to my Redraw() function, I can see that:

1) The Redraw() is somehow being called before mounted(), and the element's width and height are correctly reported.

2) When Redraw( is called by Resize() (when called directly by mounted()) the height is reported as being 2 pixels bigger in Redraw(0 than in Resize().

 3) All subsequent calls to Redraw() get the height correct.

So whenever the execution path is NOT through mounted() the height is correct, but when the execution path is through mounted(), even when using setTimeout() or $nextTick(), the height is incorrect.

**Comment by posva** [comment]
> My code is too complicated to break down into a simple fiddle. I am really not experienced enough to create one. I am happy to work with you to debug the issue. If you ignore all issues from people who struggle with creating minimal reproduction examples in an environment they are unfamiliar with you will end up with lots of bugs. I have spent a lot of time to make this bug report as thorough as possible to compensate for the lack of a fiddle.

The reasons for a reproductions are described at https://new-issue.vuejs.org/?repo=vuejs/vue (https://new-issue.vuejs.org/?repo=vuejs/vue#why-strict)

You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
If you manage to create a boiled down reproduction, please open a new issue

**Comment by AlastairGrowcott** [comment]
I KNOW why you want a reproduction. I have been doing software engineering for over 20 years. But I CANNOT.

I am not a javascript developer. I am not experienced at it. I DO NOT KNOW HOW TO USE FIDDLE!

How do you expect people like me who find genuine bugs but are not experienced at using fiddle or similar sites to prepare a reproduction for you?

And how do you expect to maintain community support if you treat your users like this. I am not the only person having this problem. It is genuine and real and persuading people to use different frameworks.

But you know what? Sod it - it's your project so if you want to ignore bug reports from well-intentioned fellow developers feel free. I didn't raise this bug report for me. I am well aware that there is no way it will ever get fixed before my delivery date. I raised it so you could fix it and make Vue better. I spent the best part of an hour raising this bug report, adding detail, etc. etc. and you're just too lazy to even LOOK at it. Pathetic. I cannot believe I wasted so much time trying to help you. You make me sick!
