### ISSUE TITLE
模板中的中文事件名称无法触发

### ISSUE THREAD

**Issue by rookieKing** [vuejs/vue#11549]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/zebewujipu/edit?html,output](https://jsbin.com/zebewujipu/edit?html,output)

### Steps to reproduce
点击 `点我没反应 `

### What is expected?
弹出对话框并显示：点了我

### What is actually happening?
什么都没发生

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/6975
