### ISSUE TITLE
Chrome, Microsoft Edge will hang when start the vue

### ISSUE THREAD

**Issue by mathsgod** [vuejs/vue#11548]
### Version
2.6.11

### Reproduction link
[http://raymond3.hostlink.com.hk/vue-issue/chrome-error.html](http://raymond3.hostlink.com.hk/vue-issue/chrome-error.html)

### Steps to reproduce
Try the following code, when the html content has "style" tag and two ```&#13;``` character, chrome or edge browser will be keep loading during start the vue instance. But when I remove single ```&#13;```,  It run properly.

View source:  view-source:https://raymond3.hostlink.com.hk/vue-issue/chrome-error.html

```
<html>

<head>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>

<body>
    <div id="div1">
        <div>
            HELLO
            <style></style>
            &#13;
            &#13;
        </div>
    </div>
    <script>
        new Vue({
            el: "#div1"
        });
    </script>
</body>

</html>
```

### What is expected?
browser should not be hang

### What is actually happening?
chrome and edge keep loading

**Comment by posva** [comment]
I cannot reproduce in any browser. You might have an extension hanging up.
FYI you should remove the `style` tag as the error in the console suggests

**Comment by sodatea** [comment]
I reproduced the error.

It's caused by the same bug as https://github.com/vuejs/vue/issues/10547 (`&#13;` is decoded as `CR`)

**Comment by mathsgod** [comment]
I know that I shouldn't add ```style``` tag in the content, but in some cases I cannot control it happen.
Anyway, I think vue should have an ability to load the content completely and prompt me an error in console without infinite loading.
