### ISSUE TITLE
对 scopedSlots 设计的一点建议

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue#11552]
### What problem does this feature solve?
希望把 scopedSlots 设计成类似 prop 的机制，slot 组件可以响应来自外部的 scopedSlots，不可修改，也可以响应来自内部的 scopedSlots（虽然所有的scopedSlots实际都来自外部，本质上就是提供可以操作 scopedSlots 的手段，但不至于不可控），姑且叫 $scopedSlotsData 吧。可以解决需要jsx或者h函数才可以构建复杂组件的问题。

### What does the proposed API look like?
```vue
<template>
<div>
  <!-- aaa 实际会渲染 default -->
  <slot name="aaa"></slot>
  <slot name="bbb"></slot>
</div>
</template>
<script>
export default {
  name: 'MyComp',
  created() {
    // 通过以下api可以添加组件内部的 scopedSlots
    this.$set(this.$scopedSlotsData, 'aaa', this.$scopedSlots.default);
  },
};
</script>

<template>
<div>
  <my-comp>
    <template #default>
      <div>案说法而发到付</div>
    </template>
    <template #bbb>
      <div>热轧而阿斯蒂芬</div>
    </template>
  </my-comp>
</div>
</template>
<script>
import MyComp from './MyComp';
export default {
  components: {
    MyComp,
  },
};
</script>
```

**Comment by Justineo** [comment]
无法理解你给出的例子是怎样的使用场景。另外，此类设计上的建议，请到 https://github.com/vuejs/rfcs 项目中，提交一份 RFC 文档，尽量将场景、实现方式、可能带来的问题考虑得全面一些。谢谢。

**Comment by jiankafei** [comment]
@Justineo 实际的使用场景就是可以像react一样，对传入组件的子组件可以做到在任何地方渲染的机制，类似 ElementUI 里 Table Table-Column 组件，可以在 Table 里获取到Column的信息，然后把传递给 Table-Column 的 slot 渲染到 Table 里，这样就不需要使用 jsx 了。

**Comment by jiankafei** [comment]
@Justineo 提交 RFC 文档，中文可以吗？
