### ISSUE TITLE
ie11报错

### ISSUE THREAD

**Issue by 1870390731** [vuejs/vue#11557]
### Version
2.5.2

### Reproduction link
[https://www.baicu.com](https://www.baicu.com)

### Steps to reproduce
谷歌浏览器正常,切换到ie11就报错了,页面显示不出来,报错信息:
[Vue warn]: Failed to resolve async component: function (resolve) {
    return __webpack_require__.e/* require */(55).then(function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = [__webpack_require__("./src/components/nav.vue")]; ((resolve).apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}.bind(this)).catch(__webpack_require__.oe);
}

### What is expected?
期望ie11和谷歌一样不报错

### What is actually happening?
ie11报错了,页面显示不出来

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
