### ISSUE TITLE
Upgrade to the latest version (serialize-javascript)

### ISSUE THREAD

**Issue by neiljia** [vuejs/vue#11561]
### Version
2.6.11

### Reproduction link
[https://www.npmjs.com/package/serialize-javascript](https://www.npmjs.com/package/serialize-javascript)

### Steps to reproduce
serialize-javascript is a package to serialize JavaScript to a superset of JSON that includes regular expressions and functions. Affected versions of this package are vulnerable to Arbitrary Code Injection. An object like {"foo": /1"/, "bar": "a\"@__R-<UID>-0__@"} would be serialized as {"foo": /1"/, "bar": "a\/1"/}, meaning an attacker could escape out of bar if they controlled both foo and bar and were able to guess the value of <UID>. UID is generated once on startup, is chosen using Math.random() and has a keyspace of roughly 4 billion, so within the realm of an online attack. eval('('  serialize({"foo": /1"   console.log(1)/i, "bar": '"@__R-<UID>-0__@'})   ')');

### What is expected?
Upgrade to the latest version

### What is actually happening?
serialize-javascript is a package to serialize JavaScript to a superset of JSON that includes regular expressions and functions. Affected versions of this package are vulnerable to Arbitrary Code Injection. An object like {"foo": /1"/, "bar": "a\"@__R-<UID>-0__@"} would be serialized as {"foo": /1"/, "bar": "a\/1"/}, meaning an attacker could escape out of bar if they controlled both foo and bar and were able to guess the value of <UID>. UID is generated once on startup, is chosen using Math.random() and has a keyspace of roughly 4 billion, so within the realm of an online attack. eval('('  serialize({"foo": /1"   console.log(1)/i, "bar": '"@__R-<UID>-0__@'})   ')');

**Comment by posva** [comment]
There is already a PR. Please don't open issues for this
