### ISSUE TITLE
client-plugin generates a wrong client.manifest.json

### ISSUE THREAD

**Issue by maunier** [vuejs/vue#11560]
### Version
2.6.11

### Reproduction link
[https://github.com/maunier/test-vue-ssr.git](https://github.com/maunier/test-vue-ssr.git)

### Steps to reproduce
```
npm i
npm run build
npm run start
visit: http://127.0.0.1:3000/c2
```

### What is expected?
1. I expect  'pages/c2.xxx.js' is loaded by html, but it is loaded by runtime

2. I expect that ,   in .nuxt/dist/server/client.manifest.json , pages/c2.xx.js will be included by any module, but it's not

for example, I expect:
```
"all" [
  "0.xxx.js",
  "1.xxx.js",
  "pages/c2.xxx.js"
],
"modules": {
  "module1": [0], // 0.xxx.js
  "module2": [1], // 1.xxx.js
  "module3": [2] // "pages/c2.xxx.js"
}
```
I expect there should be one module(module3) that contains the 'pages/c2.xxx.js', so that when I visit /c2, pages.c2.xxx.js can be  loaded by html other than the runtime.js

### What is actually happening?
actually the json is like this:
```
"all" [
  "0.xxx.js",
  "1.xxx.js",
  "pages/c2.xxx.js"
],
"modules": {
  "module1": [0], // 0.xxx.js
  "module2": [1], // 1.xxx.js
}
```

there is no module that contains 'pages/c2.xxx.js'. 

---
when I remove 'import { fn } from '@@/utils/fn''  in src/pages/c2.vue, everything is ok, but I don't know why

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is Vue.js repository, not Nuxt.js
