### ISSUE TITLE
v-slot and v-if

### ISSUE THREAD

**Issue by bowencool** [vuejs/vue#11574]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/cool-tharp-i0rvt?file=/src/App.vue:138-178](https://codesandbox.io/s/cool-tharp-i0rvt?file=/src/App.vue:138-178)

### Steps to reproduce
``` html
 <template #default="{dataModel}" v-if="dataModel">{{dataModel.msg}}</template>
```

```
[Vue warn]: Property or method "dataModel" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

### What is expected?
v-if should  identify variables correctly when v-slot exist

### What is actually happening?
it didn't

**Comment by bowencool** [comment]
or provide `no-v-if-with-v-slot` eslint rule

**Comment by posva** [comment]
This is expected due to if having a higher priority. Put it inside the template. Eslint rules request go in the eslint plugin repository
