### ISSUE TITLE
We're sorry but Index Page doesn't work properly without JavaScript enabled. Please enable it to continue.

### ISSUE THREAD

**Issue by wangdexiao** [vuejs/vue#11577]
### Version
2.6.11

### Reproduction link
[https://github.com/wangdexiao/contennt-manage-vue.git](https://github.com/wangdexiao/contennt-manage-vue.git)

### Steps to reproduce
when add
import {
  userLogout
} from '../network/apis'
in HomeHeader.vue file
get a blank page

this is HomeHeader.vue 
<template>
    
    <el-header  style="text-align: right; font-size: 12px" >
      <el-dropdown @command="handleCommand">
        <el-button type="primary">
          <span v-text="$store.getters.userName"/><i class="el-icon-arrow-down el-icon--right"/>
        </el-button>
        <el-dropdown-menu slot="dropdown">
          <el-dropdown-item command="signout">退出账号</el-dropdown-item>
        </el-dropdown-menu>
      </el-dropdown>
    </el-header>
</template>

<script>
  // import { userLogout } from '../network/apis'
  export default {
    name: 'HomeHeader',
  }
</script>

this is Home.vue
<template>
    <el-container style="border: 1px solid #eee">
      <home-sider/>
      <el-main>
        <home-header/>
        <home-main/>
      </el-main>
    </el-container>
</template>
<script>
import HomeHeader from '../components/HomeHeader'
import HomeMain from '../components/HomeMain'
import HomeSider from '../components/HomeSider'
import { userLogout } from '../network/apis'
export default {
  name: 'Home',
  components: {
    HomeMain,
    HomeSider,
    HomeHeader,
  },
}
</script>
<style >
</style>

### What is expected?
get a normal page

### What is actually happening?
get a blank page

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
