### ISSUE TITLE
"Unknown custom element <v-checkbox>" on <component :is="'v-checkbox'" />

### ISSUE THREAD

**Issue by mcasto** [vuejs/vue#11571]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/adoring-golick-fin5k?file=/src/App.vue](https://codesandbox.io/s/adoring-golick-fin5k?file=/src/App.vue)

### Steps to reproduce
Create a default Vue project.
Enter code `<component :is="'v-checkbox'" />`

### What is expected?
I expect it to create a v-checkbox.

### What is actually happening?
I get an error:
> [Vue warn]: Unknown custom element: <v-checkbox> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

---
This also happens with v-select and v-combobox, maybe others, but those are the ones I've run into. This seems similar or related to Issue #8461, but I'm not sure it's the same root cause, so I decided to open a new issue.

I encountered this while trying to implement a custom component: https://github.com/wotamann/vuetify-form-base

At first, I assumed it was a bug in that component, but, as I dug into it, I couldn't find any problems, so I stripped down to the bare essentials and still got the error, which means it has to either be a bug in Vue or in my code, though with something as basic as this, I don't know how I got it wrong.

**Comment by posva** [comment]
The error is telling you there is no component named `v-checkbox`, you must register one with that name for it to work. This is an expected error.
I don't know the actual you are running this into, but if it's Vuetify and you are using on-demand components, you will have to make sure the component is registered: https://vuetifyjs.com/en/customization/a-la-carte/#limitations

---


Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by mcasto** [comment]
Ah. That's the info I needed. Thank you.
