### ISSUE TITLE
Template compiler: Optimizer removes attributes

### ISSUE THREAD

**Issue by bartim** [vuejs/vue#11579]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/x915yzkv/2/](https://jsfiddle.net/x915yzkv/2/)

### Steps to reproduce
Click on one of the two "Foo" buttons.

### What is expected?
There should now be four "Bar" buttons.

### What is actually happening?
The first two buttons have no text, only the third and fourth button are "Bar" buttons.

---
The number of buttons which are without text are always equal to the number of "Foo" buttons. If you add a third "Foo" button, there will be three buttons without text and only one with "Bar" after clicking.

I already bisected this problem, with the following result:

    9a659593c48d6e88058515bf407ba61a6d359f79 is the first bad commit
    commit 9a659593c48d6e88058515bf407ba61a6d359f79
    Author: Evan You <yyx990803@gmail.com>
    Date:   Thu Nov 17 18:08:08 2016 -0500
    
        adjust optimizer strategy and avoid marking simple elements as static root
    
     src/compiler/optimizer.js                    | 10          -
     test/unit/modules/compiler/codegen.spec.js   | 19         -----------
     test/unit/modules/compiler/optimizer.spec.js | 13           ---
     3 files changed, 27 insertions( ), 15 deletions(-)

**Comment by posva** [comment]
This is because the `div` with the 2 buttons get reused and `value` as an attribute only has an effect at creation.
You should add a `key` to your `div` or use `:value.prop="'Bar'"` to ensure the value is set as a prop and not as an attribute
