### ISSUE TITLE
Component's slot is selecting value from <select multiple>

### ISSUE THREAD

**Issue by Herz3h** [vuejs/vue#11587]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/sq589fnj/](https://jsfiddle.net/sq589fnj/)

### Steps to reproduce
Check jsfiddle for default select tag and custom select component

### What is expected?
It should not select any value by default as is the case for default: `<select multiple>`

### What is actually happening?
It selects first value by default after slot is being 'replaced'

**Comment by posva** [comment]
This is due to the `multiple` attribute being passed to the component. Give the `select` a `v-model` to display the correct option or pass `multiple` directly to the `select` element inside `select2` with a prop or using `inheritAttrs: false` + `v-bind="$attrs"` inside `select2`

**Comment by Herz3h** [comment]
thank you for the reply but I don't understand how you dont consider this a bug ?

I can't pass multiple as a prop in my whole application (using symfony forms, which generates form automatically and adds multiple when specified in server side).

**Comment by posva** [comment]
you need to give it to the `select`, the element, not the component.
This is a browser specific behavior but in practice you give the `select` a `v-model`

> I can't pass multiple as a prop in my whole application (using symfony forms, which generates form automatically and adds multiple when specified in server side).

You only need to change `select2` component and add it

**Comment by Herz3h** [comment]
Ok got it working for the multiple part, but v-model refuses to work: https://jsfiddle.net/g20mxdjf/1/

**Comment by posva** [comment]
it's 

```js
"vModel": { },
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
