### ISSUE TITLE
SFC CSS animations with start of 'e2*' are not builded correctly

### ISSUE THREAD

**Issue by MaxiMilli** [vuejs/vue#11584]
### Version
2.6.11

### Reproduction link
[https://github.com/MaxiMilli/bug-report.git](https://github.com/MaxiMilli/bug-report.git)

### Steps to reproduce
1. Clone my github repository at: https://github.com/MaxiMilli/bug-report.git
2. Main focus of this bugreport lies on `HelloWorld.vue` in the CSS animation with the name `e2***`
3. Build the project and open the `dist/css/app.xxxxx.css` in your editor/IDE
4. Serve the project and open the page

### What is expected?
I expect in both situations (build and serve) that the svg-animation with the name 'e2' works. The yellow square in the circle should move upwards when the mouse pointer is hovered (and starts again, when again hovered).

### What is actually happening?
The serve situation works perfectly fine. The hover and the animation is working.
The build situation on the other hand is not working. On hover is nothing happend. I found in the `dist/css/app.xxxxx.css` when I chose an animation name wich starts with `e2***` the build sequence replaces the `e2` in the `animation: e2 3s linear;` call with `NaN`. Even if the name is longer and starts with `e2***` (* = placeholder). If I scope the css nothing changes to the bug.

---
I ran into this bug, because i generated the svg-animations with a webtool. the tool generates random names for animations and two out of ten animations won't work. i (luckily) discovered, that both animation names starts with `e2*`. I fixed the bugs with a replacement of `e2` with `a2`.
Thank you for your work, vue is awesome!

**Comment by sodatea** [comment]
Bug in cssnano, not vue.
You can try the CSS declaration here https://cssnano.co/playground/

**Comment by Justineo** [comment]
See https://github.com/cssnano/cssnano/issues/909.

**Comment by MaxiMilli** [comment]
Ah, thank you! I didn't know that this is a bug in cssnano.
