### ISSUE TITLE
watch or v-model of child changing the parent data value

### ISSUE THREAD

**Issue by erwinant** [vuejs/vue#11586]
### Version
2.6.11

### Reproduction link
[https://codepen.io/erwin123/pen/qBZOqXj](https://codepen.io/erwin123/pen/qBZOqXj)

### Steps to reproduce
On codepen, I try to create parent and child, parent has own data dan child has a props and local-data. child also has watcher to watch props value which supplied from parent. but when I manipulate the child local data, the parent data value's also changed.

I was checked this problem since 2.5.0. Just change the version on codepen if want to back to old version

### What is expected?
data on parent should not change when child manipulate data by props.

### What is actually happening?
data on parent changed

**Comment by posva** [comment]
This is expected with objects because they're passed as references. See https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow
