### ISSUE TITLE
Reactivity not working on derived components

### ISSUE THREAD

**Issue by cit-gruenewald** [vuejs/vue#11590]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/condescending-kowalevski-f3vvz](https://codesandbox.io/s/condescending-kowalevski-f3vvz)

### Steps to reproduce
Create 2 Vue-Components, say `child` and `parent`. In `child` add `parent` both for `extends` as well as `components`. 

In `parent` add a (boolean)-flag, say `condition`, as `data` and initialize it with `true` (thus making it reactive). In the template of `parent` add some conditional content with `v-if` based on `condition`. For debugging purposes you could also add a `watch` on `condition`. Now add a button both to `child` and `parent` with a click-handler inverting the value of `condition`. In both cases `watch` in `parent` is invoked with the correct state but only the click-handler in `parent` actually causes the template to update accordingly.

Can also be reproduced using class-components and typescript.

### What is expected?
Changes to a reactive property in a parent-component should affect the parent-template regardless of whether the change has been triggered from the parent or the child component.

Or at least if changes from a child on a parent-property are not working the `watcher` on parent should not be invoked.

### What is actually happening?
Only changes caused by the parent itself are reflected on the template.

---
Since the changes are at least "visible" using a watcher you could of course handle the required ui-changes yourself by using this.$el.findElementBy... and the `remove()` the element (if it can be removed from the DOM) or add a class/style with `display: none;` or `display: inline|block;` respectively.

**Comment by posva** [comment]
When extending components, `templates` are dropped. The `conditionalFlag` does change as you can see in the log but it won't change the component instanced of hello parent inside hello world

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
