### ISSUE TITLE
After changing the method in the component, key ‘this’ in the method is window

### ISSUE THREAD

**Issue by HelloSYR** [vuejs/vue#11593]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/SYR12138/qw37kn2g/2/](https://jsfiddle.net/SYR12138/qw37kn2g/2/)

### Steps to reproduce
1.click button
2.see Console

### What is expected?
VueComponent

### What is actually happening?
window

**Comment by posva** [comment]
You shouldn't change methods but if you need to, make sure to bind them to the component instance

**Comment by HelloSYR** [comment]
> You shouldn't change methods but if you need to, make sure to bind them to the component instance

Is it design issue?

**Comment by Justineo** [comment]
> Is it design issue?

It is how `this` works in JavaScript.

**Comment by posva** [comment]
If a method changes, use a data property instead. In that case also using arrow functions will help to keep this to the component instance
