### ISSUE TITLE
Weird v-bind attribute merging

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vue#11594]
### Version
2.6.11

### Reproduction link
[https://codepen.io/wenfang/pen/VwaeOxW?editors=1111](https://codepen.io/wenfang/pen/VwaeOxW?editors=1111)

### Steps to reproduce
None

### What is expected?
Since `v-bind="{ foo: 'baz' }"` is written after `foo="bar"`, I expected the final DOM div has `foo="baz"`

### What is actually happening?
The DOM div has `foo="bar"`, is this intended?

**Comment by posva** [comment]
HTML attributes are not ordered. Besides, v-bind takes precedence over static attributes

**Comment by wenfangdu** [comment]
@posva In this case, `foo="bar"` is static attribute, v-bind="{ foo: 'baz' }" should take precedence, then how come the produced `foo` value is `bar`?

**Comment by Justineo** [comment]
I believe single attribute takes higher priority than the `v-bind` object binding. As it's more specific.

**Comment by posva** [comment]
Yes, my bad, editor the comment

**Comment by wenfangdu** [comment]
@posva 
But in this case
```
<div v-bind="{ style: { height: '100px' } }" style="height: 300px;"></div>
```
Specific attribute does not take precedence over v-bind="{}".

**Comment by posva** [comment]
Style and class have different behavior as the merge properties and dynamic ones have higher priority

**Comment by wenfangdu** [comment]
@posva You mean class is merging, style is dynamic ones have higher priority?

**Comment by wenfangdu** [comment]
@posva Eduardo, where find I the vue-template-compiler source code, I saw the README says
```
# vue-template-compiler

> This package is auto-generated. For pull requests please see [src/platforms/web/entry-compiler.js](https://github.com/vuejs/vue/tree/dev/src/platforms/web/entry-compiler.js).
```
