### ISSUE TITLE
在v-for里面使用$attrs会引发不必要的渲染

### ISSUE THREAD

**Issue by gongtiexin** [vuejs/vue#11592]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/kind-water-hqs5f?file=/src/App.vue](https://codesandbox.io/s/kind-water-hqs5f?file=/src/App.vue)

### Steps to reproduce
在任意输入框输入任意内容

### What is expected?
输入流畅

### What is actually happening?
输入卡顿

---
在v-for里面，绑定了$attrs的都会触发更新，引起不必要的渲染

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/10115
