### ISSUE TITLE
Child component lost custom property when put component in a slot

### ISSUE THREAD

**Issue by anranstl** [vuejs/vue#11608]
### Version
2.6.11

### Reproduction link
[https://github.com/anranstl/vue-slot-test](https://github.com/anranstl/vue-slot-test)

### Steps to reproduce
Please clone my repo first.

See, I have a LoginComponent and add "newprop" property to the first input element in LoginComponent, I can access "newprop" in the normal render case, but "newprop" lost when I put LoginComponent in slot. Not sure what happened.

````ruby
<div id="formC">
        <!--put logub-component into slot, then newprop lost -->
        <form-component>
            <div id="loginC">
                <login-component></login-component>
            </div>
        </form-component>
        <br>
        <!--I can get newprop in below typical use-->
        <login-component></login-component>
    </div>
````
Please use npm install & npm start then open index.html to check my upper issue.

### What is expected?
Child component should keep all props defined in the $el.
 
---

**Comment by posva** [comment]
You cannot (and don't need to) mount `new Vue` inside of other mounted ones. Just use the component directly:

```html
<div id="formC">
        <!---->
        <form-component>
                <login-component></login-component>
        </form-component>
        <br>
        <!---->
        <login-component></login-component>
    </div>
```

Also, if you globally register the components, you don't need to declare them to `components`

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
