### ISSUE TITLE
integrate Deepcode(deepcode.ai) into pipeline or fix at least the critical issues

### ISSUE THREAD

**Issue by Spoor2709** [vuejs/vue#11603]
### Version
2.6.11

### Reproduction link
[https://www.deepcode.ai/app/gh/vuejs/vue/5b399612d8323ad0bb8b3f6fa8b2982ab73c0e6e/_/dashboard](https://www.deepcode.ai/app/gh/vuejs/vue/5b399612d8323ad0bb8b3f6fa8b2982ab73c0e6e/_/dashboard)

### Steps to reproduce
Open the link in the description

### What is expected?
0 issues found

### What is actually happening?
26 issues found

---
After Running the code through deepcode.ai a static analysis tool that takes into account frameworks in javascript. 26 issues were found of which two were critical defects. And 1 was a security warning.

**Comment by posva** [comment]
Thanks, I will share this with the team. Feel free to open PR about specific issues

**Comment by sodatea** [comment]
Many of the reported issues do not make sense.

**Comment by sirlancelot** [comment]
Interesting service, but yeah the first 5 that I looked at make no sense, are not an issue, or are working as designed. Also kind of silly that it requires me to login when the repo is public. Don't forget to revoke its permissions!
