### ISSUE TITLE
Drag operation in layout with dynamically removed item fails with vue 2.6, but works with vue 2.5

### ISSUE THREAD

**Issue by akf** [vuejs/vue#11607]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/akfarrell/jd698qkz/93/](https://jsfiddle.net/akfarrell/jd698qkz/93/)

### Steps to reproduce
This is something that works with Vue 2.5, but not with Vue 2.6.11. So I've saved the jsfiddle example with a script tag for vue 2.5.22, and a commented-out tag for vue 2.6.11.  (I'm new to this, and probably there's a better way!) Please observe the desired functionality as it works with Vue 2.5: 
You can drag any of the "Item" headings onto the dotted div below another "Item" heading, and the item is moved when you drop it. 

Then change the script tag to call in vue 2.6, and attempt the same thing. 

(This is a stripped-down version of something I was working on last year and had to shelve. The interface makes a lot more sense in context.)

### What is expected?
User can drag headings in the example to drop targets, as in Vue 2.5

### What is actually happening?
Drag stops almost as soon as it starts when using Vue 2.6.

---
This example uses a v-if clause to hide the item that's being moved when the user starts dragging it (v-if="item_id != $root.movingItemId"). If I remove that clause, drag-and-drop works in vue 2.6. So something about removing that item is interfering with the drag operation.

**Comment by posva** [comment]
This is related to nextTick changes and has been discussed a large number of times. The problem is indeed the event that triggers to remove the element it was triggered on at the same time it triggers.

You can find more details in the release notes https://github.com/vuejs/vue/releases/tag/v2.6.0 and at  https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

**Comment by akf** [comment]
Thanks for the explanation. I had actually looked at the release notes, but I didn't make the connection with the nextTick change -- probably because I hadn't discovered that the v-if clause was involved yet.
