### ISSUE TITLE
404 on google cache 

### ISSUE THREAD

**Issue by Moncef12** [vuejs/vue#11604]
### Version
2.6.11

### Reproduction link
[https://webcache.googleusercontent.com/search?q=cache:pPucmdMXMtEJ:https://runrepeat.com/catalog/black-adidas-running-shoes &cd=14&hl=en&ct=clnk&gl=us](https://webcache.googleusercontent.com/search?q=cache:pPucmdMXMtEJ:https://runrepeat.com/catalog/black-adidas-running-shoes &cd=14&hl=en&ct=clnk&gl=us)

### Steps to reproduce
1- Using server side rendered app (nuxt on top)
2- Having route validation on a page.
4- Visit: 
https://webcache.googleusercontent.com/search?q=cache:pPucmdMXMtEJ:https://runrepeat.com/catalog/black-adidas-running-shoes &cd=14&hl=en&ct=clnk&gl=us
4- Or, simply save the page and open it using a browser. 

### What is expected?
Page loads without 404 at the end.

### What is actually happening?
Page loads and then it fails with 404 not found error.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
