### ISSUE TITLE
Multi layer nested slot cause unexpected rerender

### ISSUE THREAD

**Issue by cindyliu-tec** [vuejs/vue#11602]
### Version
2.6.11

### Reproduction link
[http://jsrun.net/dTLKp/edit](http://jsrun.net/dTLKp/edit)

![image](https://user-images.githubusercontent.com/56294517/90593636-fd9a5b00-e21a-11ea-9bdf-03f3ec7707ef.png)

### Steps to reproduce
a component with slot only use count1, but when an other variable count2 changed，this component rerender unexpected

### What is expected?
when uncorrelated variable changed，slot component not rerender

### What is actually happening?
when uncorrelated variable changed，slot component also rerender

---
confuse

**Comment by posva** [comment]
Because the slot still renders again since the root template changed, rendering the component compWithSlot2 with the new slot even though in this scenario is the same.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
