### ISSUE TITLE
Component with comments causesInternet Explorer crash

### ISSUE THREAD

**Issue by omarsy** [vuejs/vue#11619]
### Version
2.6.11

### Reproduction link
[https://ylmww.csb.app/](https://ylmww.csb.app/)

### Steps to reproduce
Open this sandbox code with Internet Explorer Browser: https://ylmww.csb.app/

### What is expected?
Component is rendered well

### What is actually happening?
We have syntax error then nothing is rendered

**Comment by posva** [comment]
Comments are stripped from templates. The app doesn't work because Codesandbox doesn't support Internet Explorer
