### ISSUE TITLE
.bubble modifier for v-model

### ISSUE THREAD

**Issue by martixy** [vuejs/vue#11611]
### What problem does this feature solve?
Mostly just a convenience.
It would allow the last example here: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components  
...to work without losing the syntactic sugar of v-model.

Makes it usable with props as well, which is one way `v-model` can trip you up sometimes (getting prop mutation warnings if `v-model`ing a prop).

### What does the proposed API look like?
`v-model.bubble="value"`

This would result in 
```
v-bind:value="value"
v-on:input="$emit('input', $event)"
```

**Comment by posva** [comment]
This is not possible without major refactoring in v2 because the template on the parent cannot change the render function on the children and it involves knowing the type of the child.

Some relevant conversations: https://github.com/vuejs/vue/issues/6216 https://github.com/vuejs/vue-next/issues/9
