### ISSUE TITLE
lazy v-models broken when used with @input, computed properties, vue-axios and vue-router

### ISSUE THREAD

**Issue by wisteso** [vuejs/vue#11618]
### Version
2.6.12

### Reproduction link
- https://codesandbox.io/s/vuejs-lazy-model-bug-qlolq

### Steps to reproduce
Issue occurrs in Vue 2.6.5, 2.6.11, and 2.6.12

1. try to add (or remove) additional text with the input box (e.g. "test" -> "testx")
2. observe that the first keystroke is ignored / reverted (not expected)
3. subsequent characters are allowed / persisted (as expected)
4. observe that despite ignoring letter entry / deletion, the input box is set to disabled, as expected, indicating all expected functions / handlers were called

Note that removing any of the other code from Test.vue causes bug to not reproduce (computed property, query parsing, input button, etc).  

It seems like this issue only happens in this very specific situation of using router query params, computed properties, an axios call, forms, etc...    I wasn't able to simplify the example any further without the problem no longer being reproducible

### What is expected?
Should be able to immediately change the input text upon first keystroke.

### What is actually happening?
First keystroke is always ignored upon page reload.  Normal behavior resumes after first keystroke.

---
All functions in Test.vue which should be called are being called.  Vue isn't ignoring the input exactly, it is just reverting the keystroke during patchVnode in a way that makes it look ignored (without debugging).

I noticed that it didnt matter if the axios call was successful or not (just that the function call was made), so its been simplified to do a GET from an empty URL.  

Call stack where vnode was being incorrectly reverted:
```
patchVnode (vue.runtime.esm.js?2b0e:6319)
updateChildren (vue.runtime.esm.js?2b0e:6193)
patchVnode (vue.runtime.esm.js?2b0e:6319)
updateChildren (vue.runtime.esm.js?2b0e:6193)
patchVnode (vue.runtime.esm.js?2b0e:6319)
updateChildren (vue.runtime.esm.js?2b0e:6193)
patchVnode (vue.runtime.esm.js?2b0e:6319)
patch (vue.runtime.esm.js?2b0e:6482)
Vue._update (vue.runtime.esm.js?2b0e:3948)
updateComponent (vue.runtime.esm.js?2b0e:4066)
get (vue.runtime.esm.js?2b0e:4479)
run (vue.runtime.esm.js?2b0e:4554)
flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
(anonymous) (vue.runtime.esm.js?2b0e:1980)
flushCallbacks (vue.runtime.esm.js?2b0e:1906)
Promise.then (async)
timerFunc (vue.runtime.esm.js?2b0e:1933)
nextTick (vue.runtime.esm.js?2b0e:1990)
queueWatcher (vue.runtime.esm.js?2b0e:4402)
update (vue.runtime.esm.js?2b0e:4544)
notify (vue.runtime.esm.js?2b0e:730)
reactiveSetter (vue.runtime.esm.js?2b0e:1055)
proxySetter (vue.runtime.esm.js?2b0e:4631)
reset (Tunnel.vue?a281:104)
invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
invoker (vue.runtime.esm.js?2b0e:2179)
original._wrapper (vue.runtime.esm.js?2b0e:6917)
```

**Comment by posva** [comment]
This is expected because changing `bar` re renders the whole template and because you are using `.lazy`, `foobar` is not updated, so the old value is used again to render.

You can avoid this be using a regular `v-model` and listening to blur/change events or by wrapping the input with foobar inside a component.

This happens without axios and vue-router

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
