### ISSUE TITLE
unwanted reference between objects is created when returned by axios or the like

### ISSUE THREAD

**Issue by Keztur** [vuejs/vue#11629]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/kriech/ft1u7wm0/120/](https://jsfiddle.net/kriech/ft1u7wm0/120/)

### Steps to reproduce
Click on button "Change array A".

### What is expected?
The name "Peter" in array A (arA) changes to "Paul".
Array b stays unchanged.

### What is actually happening?
The name "Peter" in BOTH arrays changes to "Paul".

---
It looks like by using an simple "=" a reference to the data object returned by axios is created.

But the really stunning fact comes now (for some reasons not reproduceable in fiddle):
I tried to created an independen clone. i.e. copying the array without creating a reference:

arA = [...arB]

arA = arB.slice()

None of this works!
Changing object properties in array A afterwards changes the same properties in array B.
The only workaround I found was using a "parsing/stringify" combination:

this.arB = JSON.parse(JSON.stringify(res.data))

I also tried to write the data in a variable first and then tried to clone it with spread operator or slice.
The reference between the arrays stays intact.

**Comment by maitysubhasis** [comment]
I believe this is normal behaviour.
Once you assign a value to vue observed variable, it will have kind off deep connection to the assigned variable.
Yes `JSON.parse(JSON.stringify(res.data))` is a way to severe the connection.

**Comment by posva** [comment]
This is expected are both `arA` and `arB` are holding the same reference to the same object, so modifying one modifies the other

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
