### ISSUE TITLE
Dom in wrong order after hide and show Functional component 

### ISSUE THREAD

**Issue by OldDream** [vuejs/vue#11622]
### Version
2.6.11

### Reproduction link
[https://github.com/OldDream/vue-bug-demo](https://github.com/OldDream/vue-bug-demo)

### Steps to reproduce
0. run :  npm i , npm run dev, to start a dev server.
1. click "Click Me First" btn on the top left of screen.
2. Then  Click 'functional Component Click To Trigger BUG !'
3. Now we can see the DOM in worng order.

### What is expected?
Dom in right place.....

### What is actually happening?
Hard to describe the bug in word.
Please open https://github.com/OldDream/vue-bug-demo,
There are pictures showing what happend.

---
Actiually I was useing 2.6.12 but there is no such a option, so I select 2.6.11.

After I downgrade to 2.6.11, the bug is still there.

Bug shows up in the dom with id="aMapContainer", if I add v-once or give it a key, the bug disappear. 

If I turn the functional component 'ExitAutoNaviBtn'  to a normal component, the bug also disappear.

So I think there might be a bug during diff and patch.

**Comment by posva** [comment]
When reporting a bug please boil it down to the minimal. There shouldn't be any vuex, vue router, axios, lodash, vant, day-js, etc. Open a new issue with a minimal reproduction so we can take a look
