### ISSUE TITLE
<br/> 也会被转义

### ISSUE THREAD

**Issue by Pettarn** [vuejs/vue#11623]
### What problem does this feature solve?
有的时候业务那边的文案会有换行的要求，而且是和RD没有沟通的情况下，这时候就需要紧急地支持换行。在不重新上线的情况下，br标签是一个很快捷的解决方法。

### What does the proposed API look like?
转义包裹 /script/i 的<>

**Comment by Justineo** [comment]
请按 issue 模板的要求填写，否则我们将直接关闭。谢谢。
