### ISSUE TITLE
Vue SSR Mismatching childNodes vs. VNodes when use v-text on custom component with slot

### ISSUE THREAD

**Issue by Mitch-i** [vuejs/vue#11625]
### Version
2.6.12

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0)

### Steps to reproduce
I get hacker news 2 and make it run with webpack 4.
I have a custom component (component 1):

`< template>< div  :class="classes"  :disabled="disabled"  :id="id" > < slot>< /slot> < /div>< /template>`

When use it in other component (component 2) like this:

`
<parent-component>
    <child-component
      v-text="'------------'"
    >
    </child-component>
</parent-component>
`

in SSR app based on hacker news 2 example I get error 

Parent: <div>------------------</div>
Mismatching childNodes vs. VNodes:  NodeList 
0: text
length: 1

NodeList []

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

If I remove slot from component 1 - no error.
No errors if I add some inner text when use component 1 in component 2 like:

`
<parent-compoenent>
    <child-component
      v-text="'------------'"
    >
some text or &nbsp;
    </child-component>
`
 

### What is expected?
Run without error

### What is actually happening?
Error

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

When reporting an bug, make sure to provide a valid repro (for ssr, you can use https://ssr.vuejs.org/)

**Comment by Mitch-i** [comment]
And this is not a bug?

**Comment by Mitch-i** [comment]
Also work if I attach name to slot

< template>< div :class="classes" :disabled="disabled" :id="id" > < slot name="default">< /slot> < /div>< /template>

**Comment by dovca** [comment]
@posva This looks like a bug to me. Any advice on how to use v-text with custom components and SSR?

**Comment by n4an** [comment]
@dovca :100
