### ISSUE TITLE
Adding a watch to a computed property will change life-cycle order of execution which can cause code to break.

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vue#11628]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-watch-alters-life-cycle-bjc6y](https://codesandbox.io/s/vue-watch-alters-life-cycle-bjc6y)

### Steps to reproduce
In the minimal reproduction there are no steps to take, the error is shown immediately. You can view the two components in the `/components` folder in order to see the differences. The only difference (aside from naming) in the two components is that one adds a watch onto the computed property.

The basic concept here is:
1. Have an empty data option
2. Add some data nodes in the `created` option
3. Have a `computed` property which derives from the values of these nodes
4. Echo or make use of the computed property in the created method after the nodes are created.
5. Add a watch on the computed property (causes the error).

### What is expected?
Adding a watch shouldn't significantly change the life-cycle of when computed properties are calculated. So adding the watch shouldn't cause the computed property to fail. 

I thought that was the point of the `immediate` flag on a watch, which is to say that the watch will not by default trigger before the component is created unless that flag is set.

### What is actually happening?
It seems that before the watch is added, the computed property is only calculated within the `created` method. However once the watch is added, the computed property attempts to calculate its value before the value exists, regardless of whether the `immediate` flag on the watch is set or not.

---
It may be that when a computed property is calculated is determined not by the lifecycle but rather by when that value is first used, in which case this is not essentially a bug but rather an edge-case. However I would submit that this is problematic for the Vue ecosystem and reputation because by adding a watch you can inadvertently fundamentally change the operating sequence of your component, which breaks things and makes it very hard to refactor or design resilient components.

There should be some way to control this so that you can create a watch on a computed property but have the same flexibility extended in the sense of being able to hydrate that computed property in a lifecycle hook before the watch kicks in. 

The way I ran into this bug is as follows. I started out with a component that needs a watch function on a computed property in order to add dynamic rows to a variety of other affected components. This was working fine while the `empty row` state was static. However, at a certain point I decided that those empty states needed to be fetched remotely, which meant that the data nodes used within the computed properties wouldn't exist immediately. Instead they would be added by the `created` hook. Once I did that my code immediately broke because the watch tries to access the computed properties before they are viable.

**Comment by posva** [comment]
When creating a watcher via the option api, it triggers before the `created` hook to detect changes done in `created`.
In your case, you will have to call `this.$watch` inside created because you depend on some variables being initialized.

BTW, a boiled down reproduction should only contain Vue (no quasar or any other external lib), something like this: https://jsfiddle.net/posva/jokte0m7/

**Comment by geoidesic** [comment]
Thanks for the reply and the work-around.

> BTW, a boiled down reproduction should only contain Vue (no quasar or any other external lib), something like this: https://jsfiddle.net/posva/jokte0m7/

I would suggest that better results may be obtained by providing starter links, which can be pinned to the vue discord server's #welcome channel, much like Quasar has cleverly done, or added to the boilerplate for new issues.

**Comment by posva** [comment]
That's already the case 😉
It's right there when providing a link to a reproduction https://new-issue.vuejs.org/
