### ISSUE TITLE
<br/>  shouldn't be encoded

### ISSUE THREAD

**Issue by Pettarn** [vuejs/vue#11630]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/sharp-mayer-3iliv?file=/src/App.vue](https://codesandbox.io/s/sharp-mayer-3iliv?file=/src/App.vue)

### Steps to reproduce
Look at the inline msg value.

### What is expected?
I wanna get a new line.

### What is actually happening?
It has been encoded to html entity.

---
You can match /script/i to encode instead of <>.
Because sometimes there are sudden copywriting changes, but we don't want to redeploy online.

**Comment by Shyam-Chen** [comment]
You need to use the `v-html` directive.

**Comment by Pettarn** [comment]
> You need to use the `v-html` directive.

Do you mean to use v-html wherever there is a copywriting?

**Comment by wushuangcoder** [comment]
<h1>{{ msg }}</h1> 
<h1 v-html="msg"></h1>

**Comment by wushuangcoder** [comment]
yes,
 `<h1>{{ msg }}</h1>`
revise
 `<h1 v-html="msg"></h1>`

**Comment by Pettarn** [comment]
OK, thanks ~

**Comment by posva** [comment]
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
