### ISSUE TITLE
<template> does not support v-html

### ISSUE THREAD

**Issue by Sebi2020** [vuejs/vue#11637]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/h9msxqv8/1/](https://jsfiddle.net/h9msxqv8/1/)

### Steps to reproduce
```vue
<template>
<p>Hello: <template v-html="value"></template></p>
</template>
<script>
export default {
data: function() {
  return {
    value: 'a <strong>html</strong> string!'
}
}
}
</script>
```

### What is expected?
The output should be: `<p>Hello: a <strong>html</strong> string!</p>`

### What is actually happening?
The output is:
`<p>Hello: </p>`

No warning is produced.

---
It should be possible to use v-html on template. Otherthise you are forced to spam your site with span elements or some other element, just for being able to render html. Sadly vuejs dropped support for element less html rendering like it was possible with the three curly braces {{{htmlString}}} notation.

**Comment by posva** [comment]
This is a limitation of Vue 2. Note `v-html` as it uses `innerHTML` (https://vuejs.org/v2/api/#v-html).

---


Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by Sebi2020** [comment]
It's sad that you directly closed the issue because VueJS does not produce any warning and the limitations still stays. At least it should be discussed as feature request..
