### ISSUE TITLE
Expose native event handler publicly when passing vnode data to directive.

### ISSUE THREAD

**Issue by brianpmaher** [vuejs/vue#11632]
### What problem does this feature solve?
I would like to access the native DOM event handler for a given click event so that I can remove it in a directive.  Currently the vnode parameter we pass to a directive includes a list of event listeners, but only exposes the reference to the event handler on an element via a private member `_wrapper`.  This is the event handler reference I will need in order to call `removeEventListener` from an element.

The use-case here is to build a reusable directive that allows gating certain features based on a condition.  Say for example you'd like to gate any component or element based on a user's permission.  You could add a `v-admin-only` directive that will disallow clicking and taking an action if the user is not an admin.  In order to accomplish that, we will need a reference to the event handler on the element in order to remove the event listener from the element.  I have found that the only location that handler is accessible is via (for a click event example) `vnode.data.on.click._wrapper` and `vnode.data.nativeOn.click._wrapper`.  The `_` implying a private member.  I'd like to be able to expose this publicly so as to be confident that this method of accessing the function would be officially supported.

The only other ways I've found for achieving a similar behavior would be to use Chrome's `getEventListeners` method, but that's only available for Chrome browser, or, overriding the native `addEventListener` method to track event listeners by element myself.

I think this would be a valuable feature for Vue to support as there isn't another way to achieve this that I've found and would make directives very powerful.

### What does the proposed API look like?
`vnode.data.on.<eventType>.wrapper`

**Comment by posva** [comment]
If you want to remove events with a directive, the directive should be responsible for adding such events as well, manually changing things added and tracked by Vue is in general a bad idea because it could break the application.

Directives are to have low-level dom access to plain elements but not to change things that were added via a component on Vue.

As for the gating, you can still add a global event listener that captures events and stop propagation/prevent default globally

**Comment by brianpmaher** [comment]
> As for the gating, you can still add a global event listener that captures events and stop propagation/prevent default globally

That would require not stopping the event at the specific component and allowing it to bubble up, which could have other side effects.

> manually changing things added and tracked by Vue is in general a bad idea because it could break the application

I understand this point, but this is possible in many other ways.  Especially given that directives already expose the element they're attached to.

**Comment by brianpmaher** [comment]
Also would a better proposal perhaps be to provide a way to remove the click handler from both Vue and natively instead?
