### ISSUE TITLE
I want to generate html, not to replace the content of #app, but to add to #app, how can I change it?

### ISSUE THREAD

**Issue by github1586** [vuejs/vue#11636]
### Version
2.6.11

### Reproduction link
[https://cn.vuejs.org/index.html](https://cn.vuejs.org/index.html)

### Steps to reproduce
I want to generate html, not to replace the content of #app, but to add to #app, how can I change it?

### What is expected?
I want to generate html, not to replace the content of #app, but to add to #app, how can I change it?

### What is actually happening?
I want to generate html, not to replace the content of #app, but to add to #app, how can I change it?

---
I want to generate html, not to replace the content of #app, but to add to #app, how can I change it?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You have to target a child of `#app`
