### ISSUE TITLE
Take the wrong Ref

### ISSUE THREAD

**Issue by genaller** [vuejs/vue#11641]
### Version
2.6.11

### Steps to reproduce
<template>
  <div class="test">
    <div class='test-header' ref='header' v-if="show">
      header
    </div>
    <div class="test-content" ref="content">
      content
    </div>
    <div class="test-footer" v-if="show">
      footer
    </div>
    <button @click='consoleRef'>asdf</button>
  </div>
</template>
<script>
export default {
  name: 'bug',
  data() {
    return {
      show: false
    }
  },
  mounted() {
    console.log( this.$refs.header, 'header')
    console.log(this.$refs.content, 'content')
    this.show= true
  },
  methods: {
    consoleRef() {
      console.log( this.$refs.header, 'header')
      console.log(this.$refs.content, 'content')
    }
  }
}
</script>

### What is expected?
when run mounted Function , can console.log  
header is undefined
content is who the div that class is "test-content"

### What is actually happening?
when run mounted Function , console.log  
header is undefined
content is who the div that class is "test-header"

**Comment by genaller** [comment]
@yyx990803

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Always provide a minimal repro when reporting a bug

**Comment by genaller** [comment]
@posva  I'm just reporting this bug

**Comment by genaller** [comment]
<template>
  <div class="test">
    <div class='test-header' ref='header' v-if="show">
      header
    </div>
    <div class="test-content" ref="content">
      content
    </div>
    <div class="test-footer" v-if="show">
      footer
    </div>
  </div>
</template>
<script>
export default {
  name: 'bug',
  data() {
    return {
      show: false
    }
  },
  mounted() {
    console.log( this.$refs.header, 'header') // undefined "header"
    console.log(this.$refs.content, 'content') // div class is test-header but not test-content
    this.show= true
  },
}
</script>

**Comment by genaller** [comment]
> `**<template>
  <div class="test">
    <div class='test-header' ref='header' v-if="show">
      header
    </div>
    <div class="test-content" ref="content">
      content
    </div>
    <div class="test-footer" v-if="show">
      footer
    </div>
  </div>
</template>
<script>
export default {
  name: 'bug',
  data() {
    return {
      show: false
    }
  },
  mounted() {
    console.log( this.$refs.header, 'header') // undefined "header"
    console.log(this.$refs.content, 'content') // div class is test-header but not test-content
    this.show= true
  },
}
</script>**`

**Comment by posva** [comment]
Please, read https://new-issue.vuejs.org/?repo=vuejs/vue#why-strict and also search existing issues before opening new ones, thank you
