### ISSUE TITLE
take the wrong Ref

### ISSUE THREAD

**Issue by genaller** [vuejs/vue#11642]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/huanghanzeng/pvndbycf/](https://jsfiddle.net/huanghanzeng/pvndbycf/)

### Steps to reproduce
just see the color of Dom , you can see that header is red but not content

### What is expected?
div that class is "test-content" is red

### What is actually happening?
div that class is "test-header" is red

**Comment by posva** [comment]
Because you are manually applying style, Vue reuses the node for the wrong element. Use a `key` attribute:

```html
<div id="app">
  <div class="test">
    <div class='test-header' ref='header' key="header" v-if="show">
      header
    </div>
    <div class="test-content" ref="content">
      content
    </div>
    <div class="test-footer" v-if="show">
      footer
    </div>
  </div>
</div>
```

**Comment by Nandiin** [comment]
Add different keys to those 3 adjacent divs
