### ISSUE TITLE
JavaScript Performance api not working correctly with vue js 

### ISSUE THREAD

**Issue by iambazzy** [vuejs/vue#11645]
### Version
2.6.11

### Reproduction link
[https://stackoverflow.com/questions/63753673/perfomance-api-in-javascript-not-working-as-expected-in-vue-js](https://stackoverflow.com/questions/63753673/perfomance-api-in-javascript-not-working-as-expected-in-vue-js)

### Steps to reproduce
Go to any vue website and open the console and run the below instruction on landing page / main page of the website.
For example [this website](http://frontenddeveloperlove.com/)

performance.getEntriesByName(window.location.href)

Now change the route and run the above instruction again on some route other than homepage and observe the behaviour.

### What is expected?
It should return performance metrics of each route

### What is actually happening?
it is not returning the performance metrics of each route. just the home or  landing page

---
Check this out for details 
https://stackoverflow.com/questions/63753673/perfomance-api-in-javascript-not-working-as-expected-in-vue-js

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
