### ISSUE TITLE
Cannot add property _Ctor, object is not extensible

### ISSUE THREAD

**Issue by mjmnagy** [vuejs/vue#11656]
### Version
2.6.11

### Reproduction link
[https://github.com/mjmnagy/error-sept-10-2020](https://github.com/mjmnagy/error-sept-10-2020)

### Steps to reproduce
1) `npm run rollup:inline`
2) Include the package into a nuxt project (I have been doing it internally by replacing the dist folder in node_modules)
3) `npm run dev`
4) Error `Cannot add property _Ctor, object is not extensible`

### What is expected?
1) Attempting to create a component library that has SSR support

### What is actually happening?
Cannot add property _Ctor, object is not extensible

---
The package has additional components and i have gone through one by one and tried to eliminate other factors. It seems that when l refresh the page, the error is present but when navigating the components it works.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

When reporting a bug make sure to remove any external dependencies. Unfortunately, there is too much there for us to check it.

**Comment by mjmnagy** [comment]
'Cannot add property _Ctor, object is not extensible ' is a `vue` error

The component library works on both `vue` and `nuxt` when the documents are natively added to the project. If you use `rollup` the error is shown. 

![image](https://user-images.githubusercontent.com/13066887/94317135-e1d55380-ff42-11ea-801d-2bdf976ebaf7.png)
![image](https://user-images.githubusercontent.com/13066887/94317274-2d87fd00-ff43-11ea-8d01-6fc3ec96e2c0.png)

**Comment by mjmnagy** [comment]
Due to lazy import of components

**Comment by dsvanidze** [comment]
@mjmnagy could you fix the error?

**Comment by mjmnagy** [comment]
> 
> 
> @mjmnagy could you fix the error?

Yes

changed:

```
components:{
  MyComp:() => import('...')
}
```
to
```
import MyComp from '....';

components:{
 MyComp
}
```

**Comment by dsvanidze** [comment]
@mjmnagy Thanks for the solution, but it would not works in my case. I need to use in the child component the parent component and without lazy loading errors occur.

**Comment by mjmnagy** [comment]
> 
> 
> @mjmnagy Thanks for the solution, but it would not works in my case. I need to use in the child component the parent component and without lazy loading errors occur.

I not 100% sure i understand you. 
" need to use in the child component the parent component and without lazy loading errors occur."

Need to use what? lazy loading? - if so i have way around making lazy-loading which sux

The only thing i can think of, is create a mixin(just to keep it a littler cleaner) and create function that conditionally imports and adds the component or make a .js map to the assets(svgs inlined as string etc)

**Comment by dsvanidze** [comment]
@mjmnagy sorry that it was not clearly explained. What I mean is [circular references between components](https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components).

I have e.g. three components A (parent), B (child) and C (grandchild). However, C uses also A. If I use your solution, circular reference problem will occur. However, I found a way how to solve it in Vue and Rollup bundle.

VeoForm: async () => (await import('@/components/VeoForm.vue')).default,

I change the code in C.vue component from 
```js
// C.vue
...
components:{
  A:() => import('@/components/A.vue')
},
...
```

to

```js
// C.vue
...
components:{
  A:() => async () => (await import('@/components/A.vue')).default,
},
...
```

I am not really sure, why it does work, but I think that in this way Rollup understand the reference between components easier. I hope it can help someone.

**Comment by mjmnagy** [comment]
components: {
  A:() => async () => (await import('@/components/A.vue')).default,
},

This works?

**Comment by dsvanidze** [comment]
@mjmnagy Yes! Have you tried if it works for you?

**Comment by mjmnagy** [comment]
> 
> 
> @mjmnagy Yes! Have you tried if it works for you?

```
components: {
A:() => async () => (await import('@/components/A.vue')).default,
},

```
Didnt work in my case

**Comment by dsvanidze** [comment]
@mjmnagy Interesting! Probably, it depends on the Rollup config.

**Comment by mjmnagy** [comment]
Quite annoying that such a massive project has such bad documentation

**Comment by mam-ijinus** [comment]
Hi,

Due to a circle dependancy that I need to break with inline import, I had been the same issue.

`A:() => async () => (await import('@/components/A.vue')).default,` doesn't work for me.

but I've resolve  it with:

` A: () => import('@/components/A.vue').then(d => d.default)`

HTH

**Comment by nattyluke** [comment]
Wonderful, was searching for days to find a solution....The Crypto error message "ctor not extensible" didnt help me a lot...
Since i like async /awyait i  like:
`A: async () => (await import('./A.vue')).default`
As far as I understand this is the real es2020 way of lazyloading, the "normal" without async/await just works with webpack. This version should go into vue doc page at https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components because it works for rollup guys an webpack guys

**Comment by MykhailoDev** [comment]
`A: () => import('@/components/A.vue').then(d => d.default)`

**Comment by MykhailoDev** [comment]
`A: () => import('@/components/A.vue').then(d => d.default)`
Great, it's really work for me

**Comment by morph85** [comment]
I had similar issue, but I found out the root cause was that, I declared files with same name: Sample.js and Sample.vue, while I imported it using import Sample from 'Sample'; causing the Vue _ctor error.

**Comment by Vacarov** [comment]
I had the same error in storybook after building components with rollup.

Thanks, for this. It works.
`A: () => import('@/components/A.vue').then(d => d.default)
`

**Comment by Dinert** [comment]
> `A: () => import('@/components/A.vue').then(d => d.default)` Great, it's really work for me
Thank, you are great
