### ISSUE TITLE
Accessing root DOM-element of current component by some selector

### ISSUE THREAD

**Issue by NMFES** [vuejs/vue#11657]
### What problem does this feature solve?
For example, we have many different components and we want to access the first div and assign some style to it. 
But now we have to specify some unique id (class) for every component.

```
<template>
    <div id="component-a">
        TEXT
    </div>
</template>

<style scoped lang="scss">
#component-a {// styles here ...}
</style>
```

We could use something like div:first-of-type but it will be passed to any nested components.

### What does the proposed API look like?
Can we have something like this:

```
<template>
    <div>
        TEXT
    </div>
</template>

<style scoped lang="scss">
:root {// styles here}
</style>
```

But currently :root is used for another functionality (variables). No matter which name it would be, just need some ability to access the first DOM node IN THIS component. So in new component we just put this alias and access the first node without id, class etc.

**Comment by posva** [comment]
Add a CSS class to the root element in the template to refer to it. There is no need to reinvent the wheel here 🙂
