### ISSUE TITLE
Vue v-on:click on the select box works slow(Works after 2nd Click)

### ISSUE THREAD

**Issue by dep12car** [vuejs/vue#11658]
### Version
2.6.11

### Reproduction link
[http://deepakcardoza.epizy.com/?i=1](http://deepakcardoza.epizy.com/?i=1)

### Steps to reproduce
I want my Vue js Function to run immediately after selecting each one of the select box option. It works fine on the PC.But in mobile devices "V-on:click-"function()" doesnt work fast. First time when option is selected it does not call the Function. It calls the function or V-on click works only after second click on the select box.

### What is expected?
Expected to call the function immediately on first click of select box/option value.(In mobile device)

### What is actually happening?
It calls the function after second click on the select box.

---
<select v-model="bank" name=bank id=bank class=select onclick="gototop();" v-on:click="updateInterest">

It must call or go to function on one click on the select box

Please note:
It works fine on the PC/Computer.On the mobile Devices i am getting issues.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
