### ISSUE TITLE
slot is reused with v-if/v-else

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue#11652]
### Version
2.6.12

### Reproduction link
[https://codepen.io/jiankafei/pen/jOqZdpG](https://codepen.io/jiankafei/pen/jOqZdpG)

### Steps to reproduce

Click the switch button, it will switch between two components with slots and without slots. The components without slots should not appear the slots passed to the components with slots

### What is expected?

Should display the fallback slot

### What is actually happening?

Displays the previous slot

---

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/WNwMmZy

**Comment by posva** [comment]
The workaround is to use a `key` on `alert-box` so Vue doesn't reuse it

**Comment by jiankafei** [comment]
@jacekkarczmarczyk @posva 三克油

**Comment by piotrzarycki** [comment]
hmm, this bug should be fixed, if yes, can i take this? :)

**Comment by posva** [comment]
as long as no PR has been submitted anybody can take any bug and give it a try 🙂
