### ISSUE TITLE
YOUR FUCKING VUE 2.3.3 BROKE MY FIVEM CHAT 

### ISSUE THREAD

**Issue by joshgangshi** [vuejs/vue#11659]
### Version
2.6.11

### Reproduction link
[https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.3/vue.min.js](https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.3/vue.min.js)

### Steps to reproduce
YOUR FUCKING VUE 2.3.3 BROKE MY FIVEM CHAT 

### What is expected?
YOUR FUCKING VUE 2.3.3 BROKE MY FIVEM CHAT 

### What is actually happening?
YOUR FUCKING VUE 2.3.3 BROKE MY FIVEM CHAT

**Comment by joshgangshi** [comment]
YOUR BLACK

**Comment by VottusCode** [comment]
Spam. Please close.

**Comment by VottusCode** [comment]
But before that, tell me how did you come to a realization that Vue is at fault.
