### ISSUE TITLE
document has bug?

### ISSUE THREAD

**Issue by startjava** [vuejs/vue#11661]
### Version
2.6.11

### Reproduction link
[https://cn.vuejs.org/v2/guide/events.html](https://cn.vuejs.org/v2/guide/events.html)

### Steps to reproduce
文档中说：
Vue 还对应 addEventListener 中的 passive 选项提供了 .passive 修饰符。
官网的VUE文档感觉有问题呢，查资料发现，passive只针对touchstart和touchend以及whell，并没有针对scroll事件进行优化，，而且在https://rbyers.github.io/scroll-latency.html地址中也正是针对这几个事件进行测试的

### What is expected?
在网址：https://www.cnblogs.com/ziyunfei/p/5545439.html
中有网友问CHROME开发人员，并没有对SCROLL进行优化

### What is actually happening?
无

---
为了严谨，请确定一下

**Comment by Justineo** [comment]
You should use the `passive` modifier only when you are fully aware of what it can do. How browsers choose to implement under the hood is outside the scope of Vue.
