### ISSUE TITLE
You may use this!

### ISSUE THREAD

**Issue by AbhigyanKumar** [vuejs/vue#11662]
### What problem does this feature solve?
Well, this is not a problem but I would like to contribute to the VueJS community with some of my art. I have created some good VueJS glitch art that you can use on your own website. The files are available at https://archive.org/details/vue-glitch under creative commons license.

### What does the proposed API look like?
Well, this is not a problem but I would like to contribute to the VueJS community with some of my art. I have created some good VueJS glitch art that you can use on your own website. The files are available at https://archive.org/details/vue-glitch under creative commons license.

**Comment by VottusCode** [comment]
It's nice, I'll give you that, but I'm not sure whether it should be in GitHub issues 🤔

**Comment by posva** [comment]
Thank you for sharing! I will close the issue as it doesn't fit the guidelines
