### ISSUE TITLE
Setter without getter in computed props

### ISSUE THREAD

**Issue by zatziky** [vuejs/vue#11667]
### What problem does this feature solve?
Sometimes you need a setter only. With the current implementation, you are forced to implement a getter too otherwise you receive this error:

> Getter is missing for computed property "interactions".

Omitting the getter would reduce some boilerplate code.

This is not allowed:

```
computed: {
   interactions: {
        set(interactions) {
          this.$store.commit('UI_INTERACTIONS_SET', interactions)
        }
      },

   ...
```

### What does the proposed API look like?
Option 1:
```
computed: {
   interactions: {
        set(interactions) {
          this.$store.commit('UI_INTERACTIONS_SET', interactions)
        }
      },

   ...
```

Option 2
```
computed: {
   interactions(interactions) {
          this.$store.commit('UI_INTERACTIONS_SET', interactions)     
   },

   ...
```

**Comment by posva** [comment]
If you only need a getter, use a method instead

**Comment by zatziky** [comment]
@posva I want only a **setter**.
