### ISSUE TITLE
Vue: Ability to detect v-show state from components

### ISSUE THREAD

**Issue by atyshka** [vuejs/vue#11663]
### What problem does this feature solve?
This problem has been mentioned before, but I thought I'd propose re-examining it as it's relevant to my particular use case. I am creating a vue wrapper for mapbox, a map library. I would like to modularize the map with vue components, but since mapbox is webgl based, these components have no DOM elements and simply abstract javascript logic. However, I have no way to implement v-show since it is not linked to the DOM. Instead I would like to be able to detect a state change, and then call the corresponding JS function to hide/show the relevant content from the map. I know that this can be easily done via a custom prop coupled with watch, but it's counterintuitive, especially in a public library, to not use the native vue hide/show methods.

### What does the proposed API look like?
Adding optional lifecycle hooks for hide/show would cover this use case.

**Comment by posva** [comment]
Unfortunately, it doesn't have any lifecycle or anything but using a prop to control visibility is totally fine and you should use that solution.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
