### ISSUE TITLE
Allow binding arrays to 'key' 

### ISSUE THREAD

**Issue by maritaria** [vuejs/vue#11677]
### What problem does this feature solve?
When rendering lists for which the items have multiple roots:

```html
<tbody>
  <template v-for="item in items">
    <tr :key="'main'   item.id"> ... </tr>
    <tr v-if="isExpanded(item.id)" :key="'expanded'   item.id"> ... </tr>
  </template>
</tbody>
```

You need to do string concatenation to build the keys, I would like the option to bind an array consisting of strings and numbers that key the element appropriately. Allowing tuples for keys allows me to not worry how the data in the tuple is serialized to a string and I don't have to use weird string formatting patterns to avoid potential collisions.

### What does the proposed API look like?
```html
<tbody>
  <template v-for="item in items">
    <tr :key="['main', item.id]"> ... </tr>
    <tr v-if="isExpanded(item.id)" :key="['expanded', item.id]"> ... </tr>
  </template>
</tbody>
```

```html
<ul>
  <li v-for="item in items" :key="['items', item.id]"> ... </li>
  <li key="end-of-list"> ... </li>
</ul>
```

When comparing two keys, they are the same when:
  - Both are string and value-equivalent
  - Both are arrays, have the same length and have the same value at every index for both arrays

With a quick look through the codebase, I suspect the change needs to occur at https://github.com/vuejs/vue/blob/0664cb01434f3d52efd076b6aafe54066a2a762a/src/core/vdom/patch.js#L35-L50

**Comment by posva** [comment]
Thanks for the proposal but there is not enough difference to justify an extra check on `sameVnode` which is critical for performance. On top of that `['word', key]` is longer than `'word' + key`
