### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "data". Expected Object, got Undefined 

### ISSUE THREAD

**Issue by nuochong** [vuejs/vue#11670]
### Version
2.6.10

### Reproduction link
[https://vuejs.org/v2/guide/components-props.html](https://vuejs.org/v2/guide/components-props.html)

### Steps to reproduce
```vue
Vue.component('my-component', {
  props: {
    // 基础的类型检查 (`null` 和 `undefined` 会通过任何类型验证)
    // Basic type check (`null` and `undefined` values will pass any type validation)
    propA: {
     type:Number,
     required:true
   },
    propB:  {
      type: Object,
      required: true
    },
    propC: {
      type: String,
      required: true
    },
  }
})
```

```html
<my-component :propA="null" :propB="undefined" :propC="undefined"></my-component>
```
// Basic type check (`null` and `undefined` values will pass any type validation)

 [Vue warn]: Invalid prop: type check failed for prop "propA". Expected Number, got Null
 [Vue warn]: Invalid prop: type check failed for prop "propB". Expected Object, got Undefined
 [Vue warn]: Invalid prop: type check failed for prop "propC". Expected String, got Undefined

(Related links)[https://cn.vuejs.org/v2/guide/components-props.html]

### What is expected?
`null` and `undefined` failed verification

### What is actually happening?
Through the verification, there is no error prompt！

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Can't really tell without a reproduction but the current behavior is working as intended
