### ISSUE TITLE
Building an App for a highly dynamic Setup - Assets Routing

### ISSUE THREAD

**Issue by Etone** [vuejs/vue#11676]
### What problem does this feature solve?
In a current project I have a problem understanding (and configuring) routing within my vue.js app.

## Our Setup

We have a setup, where for each Pull Request in our repos a new Snapshot Environment is created. This environment is one namespace within a kubernetes Cluster. All services in a current develop state are deployed with the new "snapshot" version of the service that triggered the CICD pipeline. To have a clear route for each snapshot environment, we use the namespace as part of the URL (https://HOST/NAMESPACE/APP/paths)

## Our Problem

As you can see, the URL is highly dynamic, but currently, we could just build the container with the path and be happy. Thats our current setup. Unfortunately, we want the possibility, to deploy each and every container image on every HOST as well as every NAMESPACE, those parts are only known at runtime, not in the CICD Pipeline.

Is there any way to handle such a scenario with vue.js. I have basically every freedom to edit the app as well as the container, but can't change the way we want to host our app. Currently we build the App on the cluster and inject the NAMESPACE, which was the "easiest" way to do this. But if there is any other way, I would love to not have the build and run step together.

### What does the proposed API look like?
No proposed API as this is more of an question, which was asked in Forum, Discord and Stackoverflow and didn't find an answer. If its not possible to do this, a proposed API would look like the current one, with
```js
publicPath :"./"
```
and no change in output dir. Maybe I'm missing something really big here

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
