### ISSUE TITLE
forum.vuejs.org is down

### ISSUE THREAD

**Issue by pxeger** [vuejs/vue#11671]
### Version
2.6.11 (irrelevant but left here because it's autogenerated)

### Reproduction link
[https://forum.vuejs.org/](https://forum.vuejs.org/)

### Steps to reproduce
Visit https://forum.vuejs.org/

### What is expected?
The forum works

### What is actually happening?
Cloudflare reports a HTTP 520 error (whatever that means - it's not a valid HTTP status code)

---
Sorry this is obviously not the perfect place to put this, but I want to ask a question and I can't because the forum's down. If it matters I'm in the UK.

**Comment by pxeger** [comment]
Now back up. No idea what happened there...

**Comment by valq7711** [comment]
It happens again
https://forum.vuejs.org/
is inaccessible

**Comment by JaeTLDR** [comment]
Its been down for a few days or weeks for me. I have resorted to google cached pages.
