### ISSUE TITLE
Select Binding has scope issue with `this.$root.$data`

### ISSUE THREAD

**Issue by tgraupmann** [vuejs/vue#11679]
### Version
2.6.11

### Reproduction link
[https://htmlpreview.github.io/?https://github.com/tgraupmann/vue-el-select/blob/master/index.html](https://htmlpreview.github.io/?https://github.com/tgraupmann/vue-el-select/blob/master/index.html)

### Steps to reproduce
The select has an index property. The index property is used in the binding. The component loads as expected, but the change event has a scope issue and can't resolve `this.$root.$data` resulting in a console log error.

### What is expected?
Should be able to bind using the property and change events should update the bound data.

v-model="this.$root.$data.selected[this.index]

### What is actually happening?
The change event can't resolve `this.$root.$data` and logs an error.

---
Repro project: https://github.com/tgraupmann/vue-el-select

Tested with older versions and v2.6.12

**Comment by posva** [comment]
You have to remove all `this.` usage from templates.

---


Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
