### ISSUE TITLE
about a components

### ISSUE THREAD

**Issue by marfino3028** [vuejs/vue#11680]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/dh1p3mvb/](https://jsfiddle.net/dh1p3mvb/)
https://jsfiddle.net/2f0tkhec/

### Steps to reproduce
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Unknown custom element: <data-view-sidebar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pelanggan> at src/views/pages/owner/Pelanggan.vue
       <Main> at src/layouts/main/Main.vue
         <App> at src/App.vue
           <Root>

### What is expected?
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Unknown custom element: <data-view-sidebar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pelanggan> at src/views/pages/owner/Pelanggan.vue
       <Main> at src/layouts/main/Main.vue
         <App> at src/App.vue
           <Root>

### What is actually happening?
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Unknown custom element: <data-view-sidebar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pelanggan> at src/views/pages/owner/Pelanggan.vue
       <Main> at src/layouts/main/Main.vue
         <App> at src/App.vue
           <Root>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
