### ISSUE TITLE
Censoring helpful comments in #8231 v-model on mobile not updating until a space is pressed

### ISSUE THREAD

**Issue by nolimitdev** [vuejs/vue#11681]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/issues/8231](https://github.com/vuejs/vue/issues/8231)

### Steps to reproduce
I do not understand why maintainer censored https://github.com/vuejs/vue/issues/8231 and locked it. My comment with tens of positive reactions and with helpful solution/workaround was deleted. Many users now can not see it. I think that it is not acceptable to do that by maintainer. Maintainer feels offended but he did not answer to my questions and to questions of other users. Here is a non-censored version from google cache https://gofile.io/d/V9pfeT (can be downloaded and viewed in chrome). My comment here https://i.ibb.co/MS85nnt/screen1.png (now deleted) another user was thanking for my comment here https://i.ibb.co/9GVS7nx/screen2.png (now deleted).

I have quoted maintainer and I present proofs that he is not right. Pasting again and I will be grateful for answer.

> it's because you're in composition mode (For accents, or languages like Japanese) (see the underline)

**It is not truth. This bug also happens for any language (including english) when I turn on text auto prediction. It has not to do with languages like Japanese but in global with text auto prediction enabled.**

> This is completely normal because until composition isn't finished, the browser doesn't inform about something being typed

**It is also not truth. Browser must be informed because of this two proofs:**

**1.) How it is possible that in VUE 1 v-model was working fine with text auto prediction enabled? I have tested it now.**

**2.) Replacing v-model="search" with v-bind:value="search" and v-on:input="search= $event.target.value" works.**

Please, why you did not react to it? Another user asked similar question here https://i.ibb.co/sFsvM19/screen3.png (now deleted).

### What is expected?
Helpful comments will be not deleted

### What is actually happening?
Helpful comments are deleted

**Comment by posva** [comment]
I already posted multiple times the answers, you have to do some research before posting this kind of complaints. I'm not your punching bag. I made sure that the comment with an actual solution https://github.com/vuejs/vue/issues/8231#issuecomment-547391171 was more visible to help any others looking for a workaround.
I also already answered everything else.

As a maintainer, I keep getting hateful replies like yours for problems I have answered [and searched solutions for](https://github.com/vuejs/vue/issues/8231#issuecomment-698154079) and it's simply not sustainable for my mental health. So please, refrain from posting a new issue like this or we will have to ban you. Thank you
