### ISSUE TITLE
False reactivity on input field when using a smart phone

### ISSUE THREAD

**Issue by osasson** [vuejs/vue#11685]
### Version
2.6.11

### Reproduction link
[https://codepen.io/odsasson/pen/LYNapLp](https://codepen.io/odsasson/pen/LYNapLp)

### Steps to reproduce
Type a letter in the input field

### What is expected?
val should be updated

### What is actually happening?
No reactivity although the input event is fired (actually value is set to an empty string) when using browser on a smartphone (FF and Chrome on a OnePlus smartphone)
Losing focus or typing a non alphanumeric character like  , space etc. sets the value. e.g. aaa 
Deleting it resets the value to empty e.g. aaa

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/9777#issuecomment-478831263

**Comment by osasson** [comment]
Thanks, although I think the answer from Evan is misleading. It leads to an inconsistent behavior among different devices and acts more like the change event than the expected input event which is still fired.
