### ISSUE TITLE
Bind child methods to slot to be accessible in parent scope

### ISSUE THREAD

**Issue by TuringJest** [vuejs/vue#11687]
### What problem does this feature solve?
I struggle to encapsulate functionality into components, because it's difficult to access methods in the slot rendered in the parent`s scope. 

Maybe we could add a possibility to bind the methods to the slot?

### What does the proposed API look like?
Would this be an anti-pattern?

Child-Component:
```...
<slot v-bind="this.methods" />
...
methods: {
  childMethod()
}
```

Usage:
```
<child-component v-slot:default="$" >
  {{  $.childMethod(someValue) }}>
<
```

**Comment by posva** [comment]
Tou can still bind the methods on the slot. You should do it per case and be explicit. It's better not to expose methods on a slot but it might solve some use cases

**Comment by TuringJest** [comment]
It seems useful when creating wrapper components that provide certain functionality.
What would be another approach here (if one wouldn't want to import every method explicitly and also avoid access through ref)... using mixins? 
Then the question would be, why import a mixin with the same component every time, if the functionality is coupled with the wrapper component (e.g. validation functions in a wrapper around a html form).

Or is that all just a wrong approach?
