### ISSUE TITLE
 use this.vm give undefined when use arrow function in computed  but method can

### ISSUE THREAD

**Issue by ggkong** [vuejs/vue#11690]
### Version
2.6.11

### Reproduction link
[https://codepen.io/ge12/pen/KKzYEgX](https://codepen.io/ge12/pen/KKzYEgX)

### Steps to reproduce
<div id="app">
  <button @click = "return_aaa">aaa</button>
  <button @click = "return_bbb">bbb</button>
  {{reversedMessage}}
</div>

<script>
var vm = new Vue({
  el: '#app',
  data: {
    message: 'hhh!',
    aaa:'aaa'
  },
  computed: {
    // 计算属性的 getter
    reversedMessage : () => {
        console.log(this.vm)
        return 'aaa'
    }
  },
  methods: {
    return_aaa: function () {
      console.log('aaa')
      console.log(this)
      
    },
    return_bbb: () => {
      console.log('bbb')
      console.log(this.vm)
      console.log(this.vm.message)
    }
  },
})
</script>

### What is expected?
is not undefined

### What is actually happening?
undefined

---
当我在 计算属性中使用 箭头函数 并且 使用this.vue实例的时候会出现 undefined 但是 在method中可以正常使用

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is native JS behavior
