### ISSUE TITLE
2.6.12 ~ vue.esm.browser.min.js does not provide an export named setBlockTracking

### ISSUE THREAD

**Issue by randyhoulahan** [vuejs/vue#11695]
### Version
2.6.12

### Reproduction link
[https://www.cbd.int/action-agenda/contributions/](https://www.cbd.int/action-agenda/contributions/)

### Steps to reproduce
I have not got that far yet. I will fix at 2.6.11 until resolved.  

"modern.js:52 Uncaught (in promise) SyntaxError: The requested module 'https://cdn.cbd.int/vue@~2.6/dist/vue.esm.browser.min.js' does not provide an export named 'setBlockTracking'"

### What is expected?
no breaking changes

### What is actually happening?
breaking changes

---
:-) ~ sorry Evan

Your issue form will not let me select 2.6.12

**Comment by posva** [comment]
`setBlockTracking` doesn't exist on Vue public's API, so this might come from somewhere else. I cannot give more without a reproduction, which is required to open a bug report.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
