### ISSUE TITLE
Why didn't v-leave work?

### ISSUE THREAD

**Issue by 332lfgb6** [vuejs/vue#11693]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/NMlV8C0ql98w/v8zL204y/1/](https://jsfiddle.net/NMlV8C0ql98w/v8zL204y/1/)

### Steps to reproduce
click the button to test it😄

### What is expected?
.v-leave work.

### What is actually happening?
.v-leave didn't work.

---
v-enter, v-enter-active, v-enter-to, v-leave-active and v-leave-to are normal, but v-leave is abnormal.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Your transition is triggering fine, the div is just too far away so it feels like it jumps, but I think you probably want to help on how to get the animation look the way you want
