### ISSUE TITLE
vue3迁移指南文档文字错误

### ISSUE THREAD

**Issue by 1939108122** [vuejs/vue#11716]
### Version
2.6.11

### Reproduction link
[https://v3.vuejs.org/guide/composition-api-introduction.html#reactive-variables-with-ref](https://v3.vuejs.org/guide/composition-api-introduction.html#reactive-variables-with-ref)

### Steps to reproduce
文档错误链接如下：
https://v3.vuejs.org/guide/composition-api-introduction.html#reactive-variables-with-ref

### What is expected?
文档中，“在整个Composition API中，经常会使用使用引用的概念。”，这句话中“使用”一词使用了两次，应当使用一次。

### What is actually happening?
文字赘余

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
