### ISSUE TITLE
Using (computed) getter to access `this.$refs.child`, `Child.$refs.xxx` will become `undefined` after second time of mounting of `Child` via v-if

### ISSUE THREAD

**Issue by kuanyui** [vuejs/vue#11720]
Using (computed) getter to access `this.$refs.child`, `Child.$refs.xxx` will become `undefined` after second time of mounting of `Child` via `v-if`.
### Version
Confirmed in:
- 2.6.11
- 2.6.12

### Reproduction link
[https://codesandbox.io/s/upbeat-jepsen-fhw1r?file=/src/App.vue](https://codesandbox.io/s/upbeat-jepsen-fhw1r?file=/src/App.vue)

### Steps to reproduce
# `Parent.vue`
```pug
.parentRoot
  div(v-if="showChild")
    Child(ref="child")
```
```js
{
  computed: {
     child () { return this.$refs.child },
  },
}
```

# `Child.vue`
```pug
div
  input(ref="inputEl")
```

```js
{
  methods: {
    /** call from App.vue */
    debug() {
      console.log("[Child] v-if => this.$el ===", this.$el);
      console.log("[Child] v-if => this.$refs.inputEl ===", this.$refs.inputEl);
    },
  },
}
```

### What is expected?
Can always get correct `Child.$el` and `Child.$refs.inputEl`

### What is actually happening?
At the first time of `Child.mounted()`, everything goes OK.

From the second time of `Child.mounted()`:
`Child.$el` is printed, but detached from DOM.
`Child.$refs.inputEl` becomes undefined.

#### Console output:
```
# First time mounting of Child.vue
v-if => this.$el === <DIV>…</DIV>
v-if => this.$refs.inputEl === <INPUT></INPUT>
# First time mounting of Child.vue
v-if => this.$el === <DIV>…</DIV>     ### ← this is printable in console, but not found in DOM.
v-if => this.$refs.inputEl === undefined    ### ← becomes undefined 
```
---
`v-show` also has some different strange behaviours under such context.

# Why on Earth make a getter instead of access this.$refs.XXX directly?
This is very useful for making DRY type-awared `this.$refs.XXX`  in TypeScript:
```ts
{
  computed: {
    child (): InstanceType<typeof Child> {
      // @ts-ignore
      return this.$refs.child
    }
  }
}
```

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/3842#issuecomment-514981401
