### ISSUE TITLE
Transition-group memory leak / optimization

### ISSUE THREAD

**Issue by badpunman** [vuejs/vue#11736]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/ng2r9q70/](https://jsfiddle.net/ng2r9q70/)

### Steps to reproduce
Create transition-group, 
remove items from under it in runtime.
Inspecting for memoryleaks, discover that the element holds references to removed components and doesn't let go of them until next render. 

### What is expected?
references to removed components should be cleaned up.

### What is actually happening?
this.removed stores references to removed components.

---
On line 72 of transition-group.js there's an assignment 
this.removed = removed
but this property is never apparently used after this from what I can tell.

**Comment by caodahui** [comment]
I also encountered this problem. On the page where the data is pushed quickly, the page will freeze in less than an hour, the transition-group animation is removed, and the page is normal. How can I solve it?

**Comment by AzronChan** [comment]
@badpunman How did you fix it?
