### ISSUE TITLE
Event handlers with .once only get the first parameter

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vuejs/vue#11732]
### Version
2.6.11

### Reproduction link
[https://codepen.io/foundryspatial-duncan/pen/VwjmNqY?editors=1010](https://codepen.io/foundryspatial-duncan/pen/VwjmNqY?editors=1010)

### Steps to reproduce
Any component event that emits more than one parameter, like `$emit('play', 'foo', 'bar', 'baz')` will only pass the first parameter ("foo") to the handler if you use the `.once` modifier.

### What is expected?
All parameters get passed to the event handler. Same behavior as normal v-on, but it only happens once.

### What is actually happening?
Only the first parameter gets passed, and the others are dropped.

---
Looks related to #10867 (which says it's any modifier and not just `.once`) but that one's from last year, and it's merged & closed... I'm still seeing it in the latest 2.6.11 & 2.6.12

**Comment by posva** [comment]
It hasn't been released yet
