### ISSUE TITLE
Named slot value in child component is undefined when one of child component's reactive props is changed by its parent component

### ISSUE THREAD

**Issue by yuchaosydney** [vuejs/vue#11738]
### Version
2.6.11

### Reproduction link
[https://codepen.io/yuchaosydney/pen/bGegLjM](https://codepen.io/yuchaosydney/pen/bGegLjM)

### Steps to reproduce
1. Open the codepen link and open console

2. Click "Child Button" (each click increases "child-component" internal "count" prop by one, and in watch function, it prints `!!this.$slots.header` as true, which is expected)

3. Click "Parent Button" (each click increases "count" prop by one in "Parent Component", this prop binds to "parentCount" prop in "child-component", and its watch function prints out the same reference `this.$slots.header` )

### What is expected?

1. Named "header" slot in "child-component" is rendered on the page (working)
2. Clicking "Child Button" prints out `!!this.$slots.header` as `true` (working)
3. Click "Parent Button" prints out the actual value of same reference `this.$slots.header` (not working)

### What is actually happening?
Regarding point 3, outcome is:
`"--parentCount-change---" undefined`

**Comment by posva** [comment]
In Vue 2, there are a few differences between scoped slots and regular slots. When using `v-slot`, you are using the scoped slots, so you should access them with `$scopedSlots`.

In Vue 3, both concepts are merged together, so only `slots` exist and this is not a problem

**Comment by yuchaosydney** [comment]
> In Vue 2, there are a few differences between scoped slots and regular slots. When using `v-slot`, you are using the scoped slots, so you should access them with `$scopedSlots`.
> 
> In Vue 3, both concepts are merged together, so only `slots` exist and this is not a problem

@posva Thank you!
