### ISSUE TITLE
How can I get the component code before compile in 2.x?

### ISSUE THREAD

**Issue by 546200350** [vuejs/vue#11734]
### What problem does this feature solve?
``` vue
<code-box title="基本" describe="button基本用法">
    <i-button>Default</i-button>
</code-box>
```
- I want to get default Slot String like **`<i-button>Default</i-button>`** in codeBox.
- I can find then api **_slotContents** in vue 1.x.
- Is there any way can get the same function in vue 2.x?

### What does the proposed API look like?
_slotContents in vue 1.x

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
