### ISSUE TITLE
Capture modifier not work in Chrome 86

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#11730]
### Version
2.6.11

### Reproduction link
[https://codepen.io/yangdan8/pen/oNLYWBL](https://codepen.io/yangdan8/pen/oNLYWBL)

### Steps to reproduce
Click on the green area to output "outer" in the console, ok!
Click on the pink area to output "inner", error!
Shouldn't it be "outer"?

### What is expected?
output "outer"
currentTarget and relatedTarget are both not null

### What is actually happening?
output "inner"
currentTarget and relatedTarget are both null

**Comment by posva** [comment]
Cannot reproduce. Make sure you don't have an extension breaking things

**Comment by Justineo** [comment]
> Shouldn't it be "outer"?

It shouldn't. The behavior is neither related to Vue nor Chrome. You code is equivalent to:

```html
<div id="app">
  <div id="outer">
    <div id="inner">
      dsddssdsdd
    </div>
  </div>
</div>

<script>
outer.addEventListener('click', e => { console.log(e.target.id) }, true)
</script>
```
