### ISSUE TITLE
vue ssr css没有在head生成style，初次加载时造成闪烁的问题

### ISSUE THREAD

**Issue by SunJianMing** [vuejs/vue#11743]
vue ssr css没有在head生成style，造成闪烁

build打包时， 先打包server端在打包client
//package.json
script:{
    "build:client":"vue-cli-service build",
    "build:server":"cross-env WEBPACK_TARGET=node vue-cli-serivce build",
    "build":"npm run build:server && npm run build:client"
}
如果  "build":"npm run build:client && npm run build:server"   则会造成css后加载，有闪烁问题

**Comment by sodatea** [comment]
请遵循 issue helper 的格式要求（目前的描述缺乏必要信息），发到正确的项目仓库中（这个问题应该提给 Vue CLI）。
