### ISSUE TITLE
Unexpected token '<

### ISSUE THREAD

**Issue by yazhouZhang** [vuejs/vue#11750]
### Version
2.6.11

### Reproduction link
[https://github.com/yazhouZhang/test-vue-error](https://github.com/yazhouZhang/test-vue-error)

### Steps to reproduce
node version  v15.0.1 
vue version 2.6.11
@vue/cli 4.5.8
webpack  version 5.3.2
1.vue create vue-cli3 (Create Vue project)
2.npm run serve
3.use WKWebView to Load http://0.0.0.0 :8080 with IOS app 
4.run iOS app  and Open safri developer mode
5.choose your device and click url to open page inspector
6.fist load  http://0.0.0.0 :8080 is ok
7.refresh WKWebView and see abnormal
<!DOCTYPE html>   Unexpected token '<'.  index.html   first line
No code changes have been made since the project was created

### What is expected?
There is no error in refresh

### What is actually happening?
Refresh error    Unexpected token '<'.  

---
no

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You are probably not configuring your server to properly serve the JS files and it's falling back to the HTML file (that's the < character)
