### ISSUE TITLE
Memory leak when async callback changes templating after component destroyed

### ISSUE THREAD

**Issue by badpunman** [vuejs/vue#11755]
### Version
2.6.11

### Reproduction link
// [https://jsfiddle.net/cbou8w63/](https://jsfiddle.net/cbou8w63/)
cleaned up:
[https://jsfiddle.net/pgtrqLd5/4/](https://jsfiddle.net/pgtrqLd5/4/)

### Steps to reproduce
Provided in fiddle is a button that leaks the component. Note that jsfiddle doesn't seem to expose in memory tab the context where actual script is being run? Observe chrome's memory usage instead.

### What is expected?
Component should release.

### What is actually happening?
Memory leak.

---
Async callback is called after component has been already destroyed. Memory usage increases as you keep pressing the button. Garbage collection will never release it. It seems like it is necessary for the callback to modify template v-if somehow for this to manifest. 
At first my initial hypothesis in our software's memory leak was that vuex computed values were being recalculated and that reregistered the dependencies and that itself kept the memory reserved, which might be the case, but it wasn't enough for the problem to reoccur in the minimal repro. After adding v-if template pattern, it started leaking.

**Comment by posva** [comment]
If you create any setTimeout, you will have to clear them out on destroyed with `clearTimeout`. You could also create a global mixin that automatically clears them up:

```js
{
  methods: {
    setTimeout(time, cb) {
       this._timeouts.push(setTimeout(...))
    }
  },
  beforeDestroy() {
    for (const timeout of this._timeouts) {
       clearTimeout(timeout)
    }
  },
  created() {
    this._timeouts = []
  }
}
```

**Comment by badpunman** [comment]
@posva 
This is not merely an issue with settimeout. Executed setTimeout cleans itself up after it is executed. It was merely for demonsteration purpose. The async callback could be a http request. Cleaning up a settimeout as you suggest does NOT fix this.

**Comment by badpunman** [comment]
This is a generic issue with vue. Not fixing this means we cant have any async functionality within vue components without memory leaks being a potential issue. 

Consider 
```
methods: {
  async foo () {
     await DoStuff()
     let a = this.referenceVuex
     this.loading = false
  }
}
```

**Comment by LinusBorg** [comment]
It would probably useful to provide this example as a github repo or at least on codessandbox as that would allow for some actual analysis with the devools

**Comment by badpunman** [comment]
@LinusBorg 
I'll work on that a bit later.

**Comment by LinusBorg** [comment]
thanks

**Comment by posva** [comment]
@badpunman In theory, the http request is the same: it's a side effect that should be cleaned up if it happens inside of a component. For example: cancelling the request so nothing after the await is executed.

I guess a proper reproduction without Vuex and without Axios (you can simulate it with a promisified setTimeout: `t => new Promise(resolve => setTimeout(resolve, t))`) could help. If you reproduce it, please open a new issue with an `index.html` content. But all side effects must be cleaned up if they happen during a component lifecycle

**Comment by badpunman** [comment]
@posva 
frankly this is somewhat unreasonable when it is not highlighted in vue documentation and would result in lot of boilerplate code everywhere. This is not only cancelling http requests but any possible source of asynchronity. 

What vue could instead do is check if component is being destroyed and not register watchers or process rendering on changes. Vue should disregard watcher dependency registerations if component is destroyed, if that is the problem here, like i assume.

![image](https://user-images.githubusercontent.com/937289/98525596-5826de80-2281-11eb-94bb-603f0014dd06.png)
I was unable to showcase blobs taking lots of memory, but vuecomponents remain uncleaned.

https://codesandbox.io/s/ecstatic-ride-tvw3f?file=/src/components/HelloWorld.vue

**Comment by badpunman** [comment]
@posva 
Well, if it is not a bug, follow up question: How do I get a cancellable $nextTick ?

**Comment by mozhs** [comment]
似乎有杞人忧天的嫌疑。只要你保证不会有对已销毁的 vue instance 的引用，并且异步相关的事件监听器、setTimeout 等手动清除，gc 会回收的吧。

Promise 就更无需你担心了，没有外部引用的 Promise 也会被 gc 回收。

你所提到的 async function、$nextTick 都是 Promise。

---
> Translate By Google

There seems to be a suspicion of unreasonable worries. As long as you guarantee that there will be no references to the destroyed vue instance, and the asynchronous related event listeners, setTimeout, etc. are manually cleared, gc will recycle it.

You don't need to worry about Promises. Promises without external references will also be recycled by gc.

The async function and $nextTick you mentioned are all Promises.

**Comment by mozhs** [comment]
> @posva
> Well, if it is not a bug, follow up question: How do I get a cancellable $nextTick ?

你所担心的无非是异步回掉中引用了已销毁的 vue 实例可能会造成内存泄露。实际上当所有引用都消除了，异步回掉是否能执行都还是个问题（取决于具体引擎 gc 实现）。

至于可撤销的 $nextTick，自行简单封装也能实现，这些都不是 Vue 这个框架该做的事，因为看起来毫无意义。

```js
// cancellable nextTick
Vue.prototype.$cancellableNextTick = function(callback) {
   let isCancelled = false;
   this.$nextTick(() => {
        if (isCancelled) return Promise.reject();
        callback.call(this);
   });
   return function cancel() {
        isCancelled = true;
   }
}
```

```js
// use case
const cancel = this.$cancellableNextTick(() => {
    console.log('inner $nextTick');
});
cancel();
```

**Comment by badpunman** [comment]
> 似乎有杞人忧天的嫌疑。只要你保证不会有对已销毁的 vue instance 的引用，并且异步相关的事件监听器、setTimeout 等手动清除，gc 会回收的吧。
> 
> Promise 就更无需你担心了，没有外部引用的 Promise 也会被 gc 回收。
> 
> 你所提到的 async function、$nextTick 都是 Promise。
> 
> > Translate By Google
> 
> There seems to be a suspicion of unreasonable worries. As long as you guarantee that there will be no references to the destroyed vue instance, and the asynchronous related event listeners, setTimeout, etc. are manually cleared, gc will recycle it.
> 
> You don't need to worry about Promises. Promises without external references will also be recycled by gc.
> 
> The async function and $nextTick you mentioned are all Promises.

Problem is, vue is encouraging to use patterns that enable memory leaks. Just because you provide a version of cancelable $nextTick wrapper does not mean issue is solved. All documentation encourages to use $nextTick with no worry, and vuex does not warn about these callback issues. Using vuex with callbacks, sets up observers and GC will not collect the whole bunch of interconnected vue nodes. This leak does happen in practice, and the leaks lead to this discovery in the first place.

**Comment by mozhs** [comment]
造成内存泄露的罪魁祸首不会是 `$nextTick`，也不会是任何其它 `Promise` 或异步回掉函数。

异步回掉延长了变量的生命周期，未被及时释放的这些变量引用才是内存泄露的源头。但这不是 Vue 的问题，是 JavaScript 作用域的问题，甚至不能算是问题，而是 feature。

你的例子中：

```html
<template>
  <div id="app">
    <button @click="createLeak()">Create leak $nextTick</button> 
    <br>
    <Leaker
      v-for="leak in leakComponents"
      @close="close(leak)"
      :key="leak"
    />
  </div>
</template>

<script>
// App.vue
export default {
  name: "App",
  data() {
    return {
      leakComponents: [],
      count: 0,
    };
  },
  methods: {
    close(leak) {
      this.leakComponents.splice(this.leakComponents.indexOf(leak));
    },
    createLeak() {
      this.leakComponents.push(this.count);      
      this.count++;
    }  
  },
  components: {
    Leaker: require("./Leaker.vue").default
  }
};
</script>
```

```js
// Leaker.vue
...
mounted() {
  this.$nextTick(() => {
    // Access a vuex property once
    // eslint-disable-next-line no-unused-vars
    let a = this.foo;
    // Store something big to demonstrate
    this.bigdata = generate_random_data(10000000).arrayBuffer();
    // Manipulate render template
    this.loading = false;
  });
  this.$emit("close");
},
...
```

`Leaker.vue` mounted 时触发 `close` 事件，并在父组件 `App.vue` 监听该事件。

`App.vue` 中的 `close` 事件监听器修改完 `leakComponents` 后，会触发 vue re-render，但 re-render 是在下一个渲染周期中进行，即 `close` 事件并不会中断上一次渲染，`Leaker.vue` 在 mounted 中注册的 `$nextTick` 回掉一定会在 re-render 之前执行，**一定会在 `destroy` 之前执行**。

这是预期行为，在我看来也是合理行为，更不能称之为“内存泄露”，因为回掉函数执行完毕后如果 vm 不存在外部引用，vm 和 `vm.bigdata` 会被回收。（尽管短期内 `vm.bigdata` 会占用一部分内存）

vue 实例 destroy 后，所有属性不再 reactive，你是在担心“回掉函数中修改已 destroy 实例的属性是不必要的”吗？你的 issue 标题：

> Memory leaking components on **asynchronous return calls after destruction** #11755

> Memory leak **when async callback changes templating after component destroyed** #11760

我认为已销毁的 vue 实例就相当于普通对象，vue 不应该做出限制，因为未必适用所有场景。

就你给出的 demo，并未看出 “vue 造成内存泄露”的问题。即使你把 `Leaker.vue` 中的 `$nextTick` 换成一个 HTTP 请求、`setTimeout` 导致回掉在 destroy 之后执行，这也应该算“预期行为”，修改已销毁的 vue 实例应该不会造成什么影响。
