### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mwasigala** [vuejs/vue#11751]
### Version
2.6.11

### Reproduction link
[https://github.com/mwasigala/memory-leak-sample](https://github.com/mwasigala/memory-leak-sample)

### Steps to reproduce
Clone the repository,
npm run serve,
Refresh the browser while viewing the javascript heap memory

### What is expected?
The memory to not increase rapidly and with a big difference (meaning large value)

### What is actually happening?
memory exceeds 60MB, its not good 

---
from 6.5 MB to more than 60MB... is a very big difference, my app is in production and this memory link is involved in making it crash.

and the version is 2.6.12

**Comment by LinusBorg** [comment]
You linked to a fresh default Vue CLI project.

This is not a reproduction. We can't possibly understand what kind of memory leak you might be experiencing without any actual code that demonstrates the problem.

**Comment by posva** [comment]
This is not a memory leak either. Also note the memory usage is very different in production and development mode to improve DX
