### ISSUE TITLE
Property '[...]' does not exist on type 'VueConstructor<Vue>'

### ISSUE THREAD

**Issue by Byloth** [vuejs/vue#11759]
### Version
2.6.12

### Reproduction link
[https://codepen.io/Byloth/pen/mdEzMGX](https://codepen.io/Byloth/pen/mdEzMGX)

**N.B.:** It works, here on CodePen... But it won't work inside a real Vue project.

### Steps to reproduce
1. Create a new TypeScript Vue Project using Vue CLI.
2. Copy & Paste this mixin inside `main.ts` file (right above Vue app initialization and mount).

```typescript
Vue.mixin({
    data: () => ({ aRandomMixinProperty: "John Doe" }),

    mounted()
    {
        this.aRandomMixinProperty = "John Snow";
    }
});
```

3. Try to build the project.

### What is expected?
It should compile correctly.

### What is actually happening?
It doesn't compile at all.

```
ERROR in /path/to/project/src/main.ts(15,14):
15:14 Property 'aRandomMixinProperty' does not exist on type 'VueConstructor<Vue> | ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
  Property 'aRandomMixinProperty' does not exist on type 'VueConstructor<Vue>'.
    13 |     mounted()
    14 |     {
  > 15 |         this.aRandomMixinProperty = "John Snow";
       |              ^
    16 |     }
    17 | });
    18 |
Version: typescript 4.0.5
Time: 2856ms
```

---
As workaround, you could use:

```typescript
/* main.ts */

Vue.mixin({
    data: () => ({ aRandomMixinProperty: "John Doe" }),

    mounted()
    {
        (this as Vue).aRandomMixinProperty = "John Snow";
    }
});
```

... and...

```typescript
/* mixins.d.ts */

declare module "vue/types/vue"
{
    interface Vue
    {
        aRandomMixinProperty: string;
    }
}
```

**Comment by posva** [comment]
The workaround you mentioned is the way to go: you need to tell TS that global properties have been added

**Comment by Byloth** [comment]
Oh... Ok, @posva!

But... Why doesn't the typings work like the `extend` method?
Why `data` is ignored?

Aren't the typings rules written correctly, is it by choice or is it simply impossible to define them correctly?
May I contribute to fix this problem? Could it be worth investing some time?

**Comment by seupedro** [comment]
For those coming from Google like me, check this thread instead. There are some workarounds like [this](https://github.com/vuejs/vue/issues/8721#issuecomment-428637121), [this](https://github.com/vuejs/vue/issues/8721#issuecomment-543182389), [this](https://github.com/vuejs/vue/issues/8721#issuecomment-545671348), and [this](https://github.com/vuejs/vue/issues/8721#issuecomment-640429661).

And for those who likes to take time read and understand, check [this reply](https://github.com/vuejs/vue/issues/8721#issuecomment-716848357) on same thread.
