### ISSUE TITLE
css中设置line-height: 0，导致 {{ }} 数据无法更新。

### ISSUE THREAD

**Issue by wangjianshuo** [vuejs/vue#11754]
### Version
2.6.10

### Reproduction link
[http://cdn.xinqiang.wang/test.html](http://cdn.xinqiang.wang/test.html)

### Steps to reproduce
vue：2.6.10
测试机器： ios （13.3.1）系统默认safari 浏览器
现象说明： 
css中设置了 div{
    line-height: 0;
}

使用{{ }} 数据无法更新。
使用v-text 可以更新。

实例：

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <style>
  div{
    line-height: 0;
}

  </style>

</head>
<body>

<div id="app">

<div id="example-1">
  <div style="padding:  100px 0">

        
        <p>{{ num }}我可以更新</p>
       
        <div style="height: 60px;">

        </div>
    
    	不更新 我是{{}}
        <p>{{ num }}</p>
    
    	<div style="height: 60px;">

        </div>
    
    	我是v-text
    	<p v-text="num"></p>
        
        <button style="margin: 40px" v-on:click="submitConfirm">button</button>

    </div>
  
  
</div>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js"/>
</script>
<script>
    
    var app = new Vue({
        el: '#app',
        
       data() {
        return {
            counter: 0,
            num: 0,

        };
    },
    
    methods: {

        submitConfirm() {

            this.num =1;

            this.counter  = 1;

        },  
    },
    });
</script>
</body> 

### What is expected?
{{}} 可以试试更新

### What is actually happening?
vue：2.6.10
测试机器： ios （13.3.1）系统默认safari 浏览器
现象说明： 
css中设置了 div{
    line-height: 0;
}

使用{{ }} 数据无法更新。
使用v-text 可以更新。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
