### ISSUE TITLE
Barrel Exporting Doesn't Work In Sibling Components

### ISSUE THREAD

**Issue by matsieftw** [vuejs/vue#11752]
### Version
2.6.11

### Reproduction link
[https://gist.github.com/matsieftw/5d14024723adbcb7361ad435f6ee354a](https://gist.github.com/matsieftw/5d14024723adbcb7361ad435f6ee354a)

### Steps to reproduce
1. Create a barrel export file.
2. Try to import components from the barrel.

### What is expected?
Components should import properly.

### What is actually happening?
Components import inconsistently. Some components will import from the barrel while others will not. Sibling components almost never successfully import from the barrel.

A component registration error is served to the user in the console.

---
Barrel exporting works consistently for methods in a Vuejs project, however, Vue components are not consistently exporting properly from the barrel.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

This is not related to Vue but to javascript modules

**Comment by matsieftw** [comment]
This is explicitly an issue with Vue components not exporting properly. This works fine in React and in JavaScript. This is a bug report.

**Comment by sodatea** [comment]
Circular dependencies in the modules will cause problems.
That's not a Vue issue.

Better eliminate the circular dependency, or you'll have to understand how ES modules deal with them, which, is quite complicated and error-prone.

**Comment by matsieftw** [comment]
Hm. I’m not sure what you mean by circular dependencies. I only see a one way dependency.

**Comment by sodatea** [comment]
In `ComponentC`:
```js
import { ComponentA, ComponentB } from '~/components'
```

'~/components' is an alias for `~/components/index.js`, which, includes:

```js
import ComponentC from './header/ComponentC.vue'
```

**Comment by matsieftw** [comment]
ComponentC isn’t being imported. There isn’t a circular dependency. I’m unaware of that being a concern for the barrel exporting design pattern.

**Comment by matsieftw** [comment]
That being said we were finally able to figure out what was happening and it wasn’t a Vue issue. A couple components had some relative path imports in them and that threw monkey wrenches into the build when importing some of the components from the barrel.
