### ISSUE TITLE
Memory leaking components on asynchronous return calls after destruction

### ISSUE THREAD

**Issue by badpunman** [vuejs/vue#11760]
### Version
2.6.11

### Reproduction link
[https://github.com/badpunman/vuememoryleak](https://github.com/badpunman/vuememoryleak)

### Steps to reproduce
Clone repository
npm install
npm run serve
open localhost:8080
Open chrome memory tab or other tool for analysis
Click button multiple times.

### What is expected?
Vue should release components and the memory.

### What is actually happening?
Components are not released.

---
Continuation to https://github.com/vuejs/vue/issues/11755 which was closed with too much haste. 

Now demonstrated with $nextTick so we dont have any nasty arguments about whether or not it's due to not cleaning up asynchronous HTTP calls or setTimeouts. $nextTick does not provide a cancellation method so either it's broken in this regard or this is a valid issue.

Vue should not depend its watchers on component if it has already been destroyed.

If this is still not a valid bug, all vue's documentation needs an overhaul as it encourages to write code in a way that allows for memory leaks. $nextTick should then also be removed from codebase.

**Comment by posva** [comment]
This got fixed in the latest release:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script src="https://unpkg.com/vue@2.6.14/dist/vue.min.js"></script>

    <div id="app">
      <button @click="createLeak()">Create leak $nextTick</button>
      <br />
      <Leaker v-for="leak in leakComponents" @close="close(leak)" :key="leak" />
    </div>

    <script>
      function generate_random_data(size) {
        return new Blob([new ArrayBuffer(size)], {
          type: 'application/octet-stream',
        })
      }

      const Leaker = {
        data() {
          return {
            loading: true,
            bigdata: null,
          }
        },

        template: `
<div v-if="loading">loading</div>
<div v-else>{{bigdata}}</div>`,

        mounted() {
          this.$nextTick(() => {
            // Access a vuex property once
            // eslint-disable-next-line no-unused-vars
            let a = this.foo
            // Store something big to demonstrate
            this.bigdata = generate_random_data(10000000).arrayBuffer()
            // Manipulate render template
            this.loading = false
          })
          this.$emit('close')
        },
      }

      new Vue({
        el: '#app',
        data() {
          return {
            leakComponents: [],
            count: 0,
          }
        },
        methods: {
          close(leak) {
            this.leakComponents.splice(this.leakComponents.indexOf(leak))
          },
          createLeak() {
            this.leakComponents.push(this.count)
            this.count++
          },
        },
        components: {
          Leaker,
        },
      })
    </script>
  </body>
</html>
```
