### ISSUE TITLE
simple render conditionals

### ISSUE THREAD

**Issue by SchmidtDawid** [vuejs/vue#11768]
### What problem does this feature solve?
Long structure using template elements. I know it could be hard to implement but for simple text element it will be so cool.

### What does the proposed API look like?
        {v-if="emptyTableInfo"{ emptyTableInfo }}
        {v-else{ $t('TABLE.EMPTY') }}

**Comment by posva** [comment]
Thank you but this wouldn't be HTML and be very different from the existing syntax
