### ISSUE TITLE
vue/vue-server-renderer  vue-ssr-client-manifest.json  The initial property is an empty array times the bug

### ISSUE THREAD

**Issue by wbbhacker** [vuejs/vue#11764]
### What problem does this feature solve?
1. When the initial attribute of the vUE - SSr-client-manifest.json file is an empty array

2. Start the Node service and access the IP in the browser

3. Build.dev. js file in the vue-server-renderer plugin reported a bug in line 9074sha

TypeError: Cannot read property 'file' of undefined
    at /Users/binbinwang/workspace/x-fe/vue-ssr/node_modules/vue-server-renderer/build.dev.js:9074:24

### What does the proposed API look like?
vue-ssr-client-manifest.json
```javascript
{
  "publicPath": "/dist/",
  "all": [
    "app.0178268b84efde12045b.js"
  ],
  "initial": [],
  "async": [
    "app.0178268b84efde12045b.js"
  ],
  "modules": {
    "239adfd4": [
      0
    ],
    "6fbc4fdc": [
      0
    ]
  }
}
```

**Comment by wbbhacker** [comment]
I solved it
```javascript
return needed.map(function (ref) {
      if(!ref) return   // Add this line
      var file = ref.file;

      return ("<script src=\""   (this$1.publicPath)   file   "\" defer></script>")
    }).join('')
```

**Comment by posva** [comment]
fixed in https://github.com/vuejs/vue/pull/11609
