### ISSUE TITLE
Web component in Vue: 'is' attribute doesn't work for web component

### ISSUE THREAD

**Issue by VorobiovKir** [vuejs/vue#11778]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/tender-wave-kcu39?file=/src/App.vue](https://codesandbox.io/s/tender-wave-kcu39?file=/src/App.vue)

### Steps to reproduce
1. Create webComponent which is extended from HTMLButtonElement
2. Try to use it in Vue project

### What is expected?
Vue Api provides for developers the opportunity to ignore some attribute like 'is'

### What is actually happening?
Vue renders element as a dynamic component.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Web Components work with Vue but you have to use a different approach than the `is` attribute. I don't have an article right now to give you.

**Comment by VorobiovKir** [comment]
sorry, got it, thank you. Will find the answer
