### ISSUE TITLE
vue SSR webfontloader = font cache

### ISSUE THREAD

**Issue by borodadada** [vuejs/vue#11779]
### What problem does this feature solve?
Hello, i don't can started webfontloader   vue ssr, any body know how it work? I need CACHE for fonts. 

### What does the proposed API look like?
error

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
