### ISSUE TITLE
vue with sass throws error

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue#11773]
### Version
2.6.11
"@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-eslint": "^4.5.0",
    "@vue/cli-service": "^4.5.0",

### Reproduction link
[https://flaviocopes.com/vue-cli/](https://flaviocopes.com/vue-cli/)

### Steps to reproduce

**Sample** - https://github.com/kumaresan-subramani/vue-sass

- create vue sample using below blog

    https://flaviocopes.com/vue-cli/

- then add required sass plugin by following below blog

   https://vinceumo.github.io/devNotes/Javascript/vue-scss-setup/

- Then start your application, i get below error:

```
 error  in ./src/components/HelloWorld.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (D:\today\example\node_modules\schema-utils\dist\validate.js:98:11)
    at Object.loader (D:\today\example\node_modules\sass-loader\dist\index.js:36:28)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=style&index=0&lang=scss& 4:14-441 14:3-18:5 15:22-449
 @ ./src/components/HelloWorld.vue?vue&type=style&index=0&lang=scss&
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ mult

```

### What is expected?
no error

### What is actually happening?
throws error

---
it will work when i add `includepaths` attribute but in latest `vue-cli` i dont know where to add this property

https://ej2.syncfusion.com/vue/documentation/getting-started/vue-sass/#adding-includepaths-option

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
If the blog post is outdated it would be nice to reach out to the author

**Comment by kumaresan-subramani** [comment]
There is no proper documentatoin regarding this so that i have created issue here.if it is possible can i get documentaiton link regarding where to add `includepaths` prop in latest `vue-cli`

Also i have created question in stack-overflow too
https://stackoverflow.com/questions/64868440/how-to-provide-includepaths-property-in-latest-vue-cli-with-sass

**Comment by kumaresan-subramani** [comment]
Resolved by changing `vue.config.js` like below

```
const path = require("path");
const globImporter = require('node-sass-glob-importer');

module.exports = {
  chainWebpack: config => {
    const types = ["vue-modules", "vue", "normal-modules", "normal"];
    types.forEach(type =>
      addStyleResource(config.module.rule("scss").oneOf(type))
    );
  }  
};

function addStyleResource(rule) {
  rule
    .use("sass-loader")
    .loader("sass-loader")
    .options({
      sassOptions: {
        importer: globImporter(),
        includePaths: ["node_modules/@syncfusion"]
    }
    });
}

```
