### ISSUE TITLE
DIRECTLY inject grandsons' slots to grand parent component

### ISSUE THREAD

**Issue by lchrennew** [vuejs/vue#11788]
### What problem does this feature solve?
slots in the grand son that need to be exposed in its grand parent component must be expose to its parent components and then be handed off to its grand parents components by its parent components.

### What does the proposed API look like?
in grandson component:
```
<slot provide name="slotOfGrandson"/>
```
in grandparent component:
```
<template inject #slotOfGrandson/>
```

**Comment by posva** [comment]
Given the state of Vue 2 this is unlikely to happen, but it should go through an RFC too
