### ISSUE TITLE
Binding to Bracket Attributes in AMP.

### ISSUE THREAD

**Issue by mixxor** [vuejs/vue#11792]
### What problem does this feature solve?
If i want to bind something to a bracket Attribute, used in AMP e.g.:

https://amp.dev/documentation/examples/components/amp-bind/#basic-usage

:[hidden]="'initalState.inputFieldCount > '   index"

it will not work. 

I am using Vue.js2    nuxt to render my AMP content. Any Ideas about this?

### What does the proposed API look like?
:[hidden]="'initalState.inputFieldCount > '   index"

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
