### ISSUE TITLE
Template props feature issue

### ISSUE THREAD

**Issue by VladFedotov** [vuejs/vue#11799]
### What problem does this feature solve?
Spreading of the same props between single-level components. Synchronization between components. One other way to set components properties default values.

### What does the proposed API look like?
My proposal is to add props to template tag:
```vue
<template
    :foo="foo"
    :bar="bar"
    :baz="baz">
    <one></one>
    <two></two>
    <three></three>
</template>
```
can be the same as
```vue
<template>
    <one :foo="foo" :bar="bar" :baz="baz"></one>
    <two :foo="foo" :bar="bar" :baz="baz"></two>
</template>     
```
The properties are assumed to be rewritable:
```vue
<template :prop="value">
    <one></one>              /* prop === value */
    <two :prop="null"></two> /* prop === null  */
</template>
```
This feature also allows developers set children 
components default values.

**Comment by posva** [comment]
I find this non intuitive and implicit but feel free to open an RFC on the rfcs repo to gather more feedback 🙂
