### ISSUE TITLE
Why is there something "global"?

### ISSUE THREAD

**Issue by Madyuskin** [vuejs/vue#11797]
Full story - https://medium.com/@madyuskin/flux-vuex-are-wrong-and-outdated-61438de7c512

### What problem does this feature solve?
Instead of global and non-global, there should be parent and child. And if a parent has no parent, you may call it global. Something like this can help:
<pre>
<code>
export default {
  passdown: ['bar', 'foobar2'],
  data: () => ({
    foo: null,
    bar: null
  }),
  methods: {
    foobar1() {},
    foobar2() {}
  }
}
</code>
</pre>
Now any child has direct access to bar and foobar2 — no need to pass through all its parents. But I am sure in many cases it is an overkill just like Vuex.

### What does the proposed API look like?
<pre>
<code>
export default {
  passdown: ['bar', 'foobar2'],
  data: () => ({
    foo: null,
    bar: null
  }),
  methods: {
    foobar1() {},
    foobar2() {}
  }
}
</code>
</pre>

**Comment by posva** [comment]
This sounds pretty much like `inject`/`provide`. FYI vuex is not necessary to build an application. If you think this deserves more discussion, you should give it a try on the RFC. I recommend you to also expose your points instead of only linking to an article
