### ISSUE TITLE
sameVNode无法区分emptyVNode和AsyncPlaceholder

### ISSUE THREAD

**Issue by pndllxzzy** [vuejs/vue#11805]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/wonderful-ardinghelli-5fi3f?file=/src/views/same-vnode.vue](https://codesandbox.io/s/wonderful-ardinghelli-5fi3f?file=/src/views/same-vnode.vue)

### Steps to reproduce
1. 打开页面https://5fi3f.sse.codesandbox.io/same-vnode
2. 打开devtools在console中发现报错信息

### What is expected?
无报错信息

### What is actually happening?
sameVnode方法判断emptyVNode与AsyncPlaceholder相等导致
patchVnode isDef(vnode.asyncFactory.resolved)报错

**Comment by extheor** [comment]
测试

**Comment by posva** [comment]
Async component syntax has changed: https://v3.vuejs.org/guide/migration/async-components.html#async-components.

Also regarding issues, please read https://new-issue.vuejs.org/?repo=vuejs/vue-next&lang=zh-cn#why-repro
