### ISSUE TITLE
about function sameVnode

### ISSUE THREAD

**Issue by pndllxzzy** [vuejs/vue#11801]
VNodeA: v-if="false"产生的emptyVNode
VNodeB: asyncComponentB在resolve前产生的AsyncPlaceholder
VNodeC: asyncComponentC在resolve前产生的AsyncPlaceholder

sameVnode(VNodeA, VNodeB) 返回的是true
sameVnode(VNodeB, VNodeC) 返回的是true

为什么返回true而不是false，返回true的话容易导致一些错误

期望sameVnode以上情况返回false

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.
