### ISSUE TITLE
Prop default value cannot be set correctly

### ISSUE THREAD

**Issue by Tzdy** [vuejs/vue#11806]
### Version
2.6.11

### Reproduction link
[https://codepen.io/Tsdy/pen/vYXGXEr](https://codepen.io/Tsdy/pen/vYXGXEr)

### Steps to reproduce
```
function fun() {}
        const vm = new Vue({
            el: '#App',
            components: {
                MyComponent: {
                    props: {
                        text: {
                            type: [Boolean, Function],
                            default: fun
                        }
                    },
                    template: `<div></div>`
                }
            }
        })
        console.log(vm.$children[0].text)
    // undefined

```

### What is expected?
I can find the text property in the vm.$children[0]

### What is actually happening?
vm.$children[0].text is undefined

**Comment by jacekkarczmarczyk** [comment]
`default: () => fun`

**Comment by posva** [comment]
You need to use a function for objects (any non primitive like objects, functions, arrays): https://vuejs.org/v2/guide/components-props.html#Prop-Validation
