### ISSUE TITLE
Show warning on console when developer names a component with the same name that a native HTML tag

### ISSUE THREAD

**Issue by FranciscoJavierMartin** [vuejs/vue#11808]
### What problem does this feature solve?
I try to create a component called "Map" that its name collide with the native HTML tag "map". I did not know this tag and did not see any warning or error on the console, simply the component is not showed on the page and I was wondering what was happening.

### What does the proposed API look like?
I want some warning on the console that show a message like "You 'Map' component name collide with a native HTML tag. Please rename it" to avoid these kind of errors. I think that it is useful specially for beginners developers.

**Comment by posva** [comment]
Follow https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential
