### ISSUE TITLE
Passing Boolean Prop With No value Without Type Validation on Child Component Is Interpreted as an Empty String Instead of True

### ISSUE THREAD

**Issue by ottonomous** [vuejs/vue#11804]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/tender-meitner-bpvvl](https://codesandbox.io/s/tender-meitner-bpvvl)

### Steps to reproduce
1. Create a child component
2. Pass a boolean prop `boolean-prop` with no value
3. Check the value of the prop in the child component

### What is expected?
The prop value should be `true` and the type should be a boolean

### What is actually happening?
the prop value is "" (an empty string) and the type is string

---
WORKAROUND: Adding type validation to the prop solves the issue.

**Comment by posva** [comment]
This is intended because it's the same as `boolean-prop=""`. Giving it the Boolean type is the way to go.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
