### ISSUE TITLE
a bug for cached page instance or the component(keep-alive) --- $destory

### ISSUE THREAD

**Issue by Jemory-git** [vuejs/vue#11816]
### Version
2.6.11

### Reproduction link
[http://thisIssueNeednotLink.com](http://thisIssueNeednotLink.com)

this is another same issue : https://github.com/vuejs/vue/issues/6509#issuecomment-347787474

### Steps to reproduce
1、use <keep-alive> cache pages 
2、click btn to close the page， and destory the instance
3、when reopen the page ，it will never be cached

### What is expected?
it is the most elegant method to cache pages with tab-tags。
but can not achieve cause this bug

### What is actually happening?
repair

---
repair

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You should also read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
