### ISSUE TITLE
Get same value on several items in a v-for loop

### ISSUE THREAD

**Issue by lynn-Chin** [vuejs/vue#11813]
### Version
2.6.11

### Reproduction link
[https://codepen.io/lynn-chin/pen/xxEEZgR](https://codepen.io/lynn-chin/pen/xxEEZgR)

### Steps to reproduce
I have an object array like this: [ { name: '01.jpg', id: 1234, url: '/example/01.jpg' }, { name: '02.jpg', id: 2345, url: '/example/02.jpg' } ];
When I use v-for to render HTML structure, items in the object got same value for item.id:

My HTML structure is:
           <div
                class="single_image"
                v-for="(item, index) in images"
                :key="index"
              >
                <img :src="item.url" alt="" />
                <div class="image_title">
                  <input
                    type="checkbox"
                    @change="checkboxChange($event, item)"
                    ref="imgCheckBox"
                  />
                  {{ item.name }}
                </div>
              </div>
The result of console.log(item.id, item.name) for each item:
          12345678987654324  "02.jpg"    (wrong id)
          12345678987654324  "03.jpg"    (wrong id)
          12345678987654324  "04.jpg"
          12345678987654326  "05.jpg"
          12345678987654328  "06.jpg"    (wrong id)
          12345678987654328  "07.jpg"    (wrong id)

If I change item.id's type from Number to String, this will not happen.
I wanna know what is happen and how can I avoid this situation.  Does that mean I cannot use Number values in a v-for loop?

### What is expected?
I expect each item got its right id value.

### What is actually happening?
Most values for item.id are wrong.

---
My Vue version is 2.6.12, but there's not such a choice.

**Comment by Justineo** [comment]
> https://codepen.io/lynn-chin/pen/xxEEZgR

This isn't a runnable reproduction. Please provide a valid one. Thank you.

**Comment by lynn-Chin** [comment]
> > https://codepen.io/lynn-chin/pen/xxEEZgR
> 
> This isn't a runnable reproduction. Please provide a valid one. Thank you.

Hi,  I rewrote my work, you can run it now: [https://codepen.io/lynn-chin/pen/xxEEZgR](url)

**Comment by posva** [comment]
You need `:key="item.id"`

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
