### ISSUE TITLE
Getting "Uncaught DOMException: Operation is not supported" when using Web Component inside Vue Component using ESM and Browser.

### ISSUE THREAD

**Issue by jrgleason** [vuejs/vue#11810]
### Version
2.6.11

### Reproduction link
[https://github.com/jrgleason/jrg/blob/EXAMPLES_FRAMEWORK_INT/jrg-ui/examples/vue/index.html](https://github.com/jrgleason/jrg/blob/EXAMPLES_FRAMEWORK_INT/jrg-ui/examples/vue/index.html)

### Steps to reproduce
This is a basic HTML page and should "just work". What would be expected is that the web component is embedded in the Vue Component, however, only the vue on renders. If I move the Web Component outside of the Vue component it renders as expected. 

### What is expected?
The custom element (web component) renders inside the Vue component.

### What is actually happening?
I get "Uncaught DOMException: Operation is not supported"

---
SO Available here https://stackoverflow.com/questions/65182891/how-do-i-use-a-non-vue-custom-web-component-in-a-vue-component-without-webpack. Answer does not solve the issues as can be seen by my updated version.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) if you need help integrating web components with Vue.
