### ISSUE TITLE
after cached page instance exec $destory,the page will never be cached; this bug existing many years??

### ISSUE THREAD

**Issue by Jemory-git** [vuejs/vue#11815]
看到$destroy这个方法，我觉得这就是正确的用法，通过组件里不同的用户行为决定离开页面时是否缓存组件。
（比如一个留言组件，留言提交成功后这个组件应该销毁，如果没有提交，则应该保留缓存，让用户下次进来继续。）
然而，destroy之后，再次重复进入这个组件会出现奇怪的结果，组件不能再被缓存了，我觉得这是bug吧。

_Originally posted by @wanyaxing in https://github.com/vuejs/vue/issues/6509#issuecomment-347787474_

**Comment by zero7u** [comment]
保持关注！！！！
