### ISSUE TITLE
In vue template lazy evaluation functions

### ISSUE THREAD

**Issue by kswizzlek** [vuejs/vue#11824]
### What problem does this feature solve?
in a vue template using {{removeCertainElemntsFrom(addElementTo(originalDataSource))}} vs. {{modifiedVersionOfOriginalDataSource}} allows a more pure way of modifying our data for our view. My request is to have Pure functions in the view that are only re-rendered when the parameters for the function are changed. This will lead to less code to maintain as well as allowing for test cases on the way our data gets parsed for the view and ultimately less bugs.

### What does the proposed API look like?
I use typescript with vue-property decorators so it would look like:
```
@Pure()
private combineFirstAndLastName(first: string, last: string) {
      // You will not be allowed to access outside variables from this function, if you do an error will be thrown("pure functions must be pure"))
   return `${first} ${last}`
}
```
When used in the html this function will only get called when the parameters passed into it change

**Comment by posva** [comment]
For this to work `first` and `last` would have to be reactive sources, so in practice, this would become a computed property. The only problem was scoped slots but with composition API, it's usually possible to move that information to the `setup` function and have functions that reuse `computed` to deal with the lazy evaluation. I don't think there is anything to add to vue core that could change anything (decorators would have to be added to the vue libraries), but you can always open an RFC on the rfcs repository
