### ISSUE TITLE
Throw error when props validation fails

### ISSUE THREAD

**Issue by yazfield** [vuejs/vue#11827]
### What problem does this feature solve?
Currently props validation only issues a warning in non production environment.

I was trying to create a component like react's error-boundary to handle invalid props and show fallback componentsusing `errorCaptured` but it is unfortunately not possible.

### What does the proposed API look like?
something like a callback to be called when validating props
```
Vue.config.assertPropsHandler: Function;
```

**Comment by posva** [comment]
prop validation is intentionally dev only to keep it out of production bundle. You can add a custom handling for errors to handle this: https://jsfiddle.net/7pawb8ou/. Note you could also throw the error during `render` if you use a wrapper component, allowing you to catch it in `errorCaptured`

**Comment by yazfield** [comment]
@posva  thank you 😄

**Comment by nicobao** [comment]
HAve this table:
```
export const participantTable = pgTable(
    "participant",
    {
        id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
        conversationId: integer("conversation_id")
            .references(() => conversationTable.id)
            .notNull(), // used to delete all opinionContent when deleting an opinion
        userId: uuid("user_id") // the user who owns this notification
            .references(() => userTable.id)
            .notNull(),
        polisClusterId: integer("polis_cluster_id").references(
            () => polisClusterTable.id,
        ), // cluster the participant belongs for the given conversation
        opinionCount: integer("opinion_count").notNull().default(0),
        voteCount: integer("vote_count").notNull().default(0),
        createdAt: timestamp("created_at", {
            mode: "date",
            precision: 0,
        })
            .defaultNow()
            .notNull(),
        updatedAt: timestamp("updated_at", {
            mode: "date",
            precision: 0,
        })
            .defaultNow()
            .notNull(),
    },
    (table) => [
        {
            unqClusterPerParticipant: unique(
                "unique_cluster_per_participant",
            ).on(table.conversationId, table.userId),
        },
    ],
);
```

    "drizzle-orm": "^0.39.1",
    "drizzle-kit": "^0.30.4",



but still doesn't work, it doesn't generate the `check` for postgres
