### ISSUE TITLE
new content are not getting loaded without hard reload and empty cache in the browser after new deployment

### ISSUE THREAD

**Issue by DebaPrasad14** [vuejs/vue#11822]
### Version
2.6.11

### Reproduction link
[https://Notavailable](https://Notavailable)

### Steps to reproduce
1. create an app
2. deploy that
3. check the content
4. make some changes
5. again deploy the app
6. now reload the page in the browser ( the new contents wouldn't be available)
7. do empty cache and hard reload in the browser then new contents will be available

### What is expected?
after the new deployment, the new contents should be available to the users once they reload the page in the browser.

### What is actually happening?
after the new deployment, we are telling users to do a hard reload and empty cache in the browser to get the new contents of our application which is not good, what I want is if a user reloads their page after deployment then they should see the new contents of our Vue app.

**Comment by posva** [comment]
Read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
