### ISSUE TITLE
In the following scenario，When the array data is changed responsively,  the view cannot be updated normally

### ISSUE THREAD

**Issue by linghuam** [vuejs/vue#11838]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/youthful-khayyam-4kid1?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/youthful-khayyam-4kid1?fontsize=14&hidenavigation=1&theme=dark)

## step1: I defined a contextMenu component，in this component，i append the `$el` element to body in `mounted` hook。
```vue
<template>
  <div>I am ContextMenu.</div>
</template>

<script>
export default {
  mounted() {
    document.body.appendChild(this.$el);
  },
};
</script>
```
## step2： In App.vue，i render a list，and the list data is obtained asynchronously。
```html
<template>
  <div id="app">
    <div v-for="item in list" :key="item.id">
      {{ item.id }}
    </div>
    <ContextMenu />
  </div>
</template>

<script>
import ContextMenu from "./components/ContextMenu";

export default {
  name: "App",
  components: {
    ContextMenu,
  },
  data() {
    return {
      list: [],
    };
  },
  mounted() {
    this.list = [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }];
  },
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
### What is expected?
I hope to see is:  When the list data is updated, the view is updated。

### What is actually happening?
the view is not update yet.

---
I try some methods to avoid this question, such as:
1. wrap  ContextMenu or list in a  div element.
2. init the list at least one data.

but I don't kown why,  and I really hope you can tell me why. 

thank you very much!

**Comment by posva** [comment]
You cannot manually manipulate the HTML that is being rendered by Vue because it wouldn't be able to keep the changes up to date. So you can't ` document.body.appendChild(this.$el);`. You should use https://portal-vue.linusb.org/ for that purpose
