### ISSUE TITLE
关于vue2 编写代码模式的的一些提案

### ISSUE THREAD

**Issue by justfn** [vuejs/vue#11834]
### What problem does this feature solve?
增加命名空间的形式以解决一个组件代码松散不好维护的情况  
```
// 一个单文件组件 
<template lang="html"> 
<section class="pageA">
  <div class="">
    {{ key01 }}
  </div>
  
  <div class="partOne">
    {{ PartOne.key11 }}
    <button @click="PartOne_aaaFn()">test1</button>
    <button @click="cccFn()">test2</button>
  </div> 
  
  <div class="partTwo">
    
  </div>
</section> 
</template> 

<script> 
import dealVueOptions from "./dealVueOptions.js";
const options = {
  components: {
    // 
  },
  data(){ 
    // let vm = this; // 不要这样使用, 目前使用 dealVueOptions 方法处理存在问题
    return {
      key01: 'a01',
      
    };
  },
  computed: { 
    // 
  },
  watch: {
    // 
  },
  created(){ 
    // this.PartOne.aaaFn();  // 设想的使用形式 
  },
  methods: {
    // 扩展使用对象形式，从而支持命名空间化 
    // aaa: {
    //   bbb: ()=>{
    //     console.log(this);
    //   },
    // },
    cccFn(){
      this.PartOne.key11 = 333;
    },
  },
  
  // 命名空间模式 
  PartOne: {
    // 自动合并到顶层 data 中, 
    // 设想：命名空间内 this.xx 访问，其他命名空间或上层 this.spaceName.xxx 访问  
    data: {
      key11: 111,
    },
    // 以下选项同 data 的处理逻辑 
    computed: { },
    watch: { },
    methods: { 
      aaaFn(){  // 注意此处不可使用箭头函数 
        this.PartOne.key11 = 222;
        // this.key11 // 设想的使用形式 
      }
    },
    // 生命周期函数则不需要，顶层中调用该命名空间内的方法即可 
  },
  
  PartTwo: {
    // ... 
  },
};
export default dealVueOptions(options);
</script> 

<style lang="less" scoped> 
</style> 
<style lang="less"> 
</style> 

// 处理函数   暂且为之 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/** 处理vue的选项配置，改造成按模块、命名空间划分的形式  
* @params  option  obj,待处理的vue配置选项
* @return  option  obj,标准vue可识别的配置选项 
* -----------------------------
* @author  fsl 
* @time    2020.12.20 
* -----------------------------
* @detail  
- 01 详细说明1 
* -----------------------------
* @todo  
- 1 代办事项1 
*/

export default function(option){
  let result = {}
  for (let key in option) {
    let val = option[key];
    // 不以大写字母开头则不处理  
    if (!/^[A-Z]/.test(key)) { 
      result[key] = val
      continue;
    }
    
    // 此处需要优化，暂且为之  
    result = {
      ...result,
      ...dealVal(key,option),
    }
  }
  
  return result;
}
function dealVal(key,opt){
  let res = {};
  let obj = opt[key];
  for(let k in obj){
    let v = obj[k];
    if (k==='data') {
      opt.data = opt.data || (()=>({}));
      res.data = ()=>{
        return {
          ...opt.data(),
          [key]: { ...v, },
        }
      }
    }
    else {
      let currentV = {};
      for(var _v in v){
        // 暂时的解决办法，使用： 命名空间_方法名 
        // 待其他选项支持对象模式后可改成 命名空间.方法名的形式 来进行访问调用 
        currentV[`${key}_${_v}`] = v[_v]; 
      };
      res[k] = {
        ...opt[k],
        // todo 
        ...currentV,
      }
    }
  };
  return res;
} 
```

### What does the proposed API look like?
类似于vuex的命名空间化

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by justfn** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

it`s not a question, just a feature requests

**Comment by justscripts** [comment]
> ### What problem does this feature solve?
> 增加命名空间的形式以解决一个组件代码松散不好维护的情况
> 
> ```
> // 一个单文件组件 
> <template lang="html"> 
> <section class="pageA">
>   <div class="">
>     {{ key01 }}
>   </div>
>   
>   <div class="partOne">
>     {{ PartOne.key11 }}
>     <button @click="PartOne_aaaFn()">test1</button>
>     <button @click="cccFn()">test2</button>
>   </div> 
>   
>   <div class="partTwo">
>     
>   </div>
> </section> 
> </template> 
> 
> <script> 
> import dealVueOptions from "./dealVueOptions.js";
> const options = {
>   components: {
>     // 
>   },
>   data(){ 
>     // let vm = this; // 不要这样使用, 目前使用 dealVueOptions 方法处理存在问题
>     return {
>       key01: 'a01',
>       
>     };
>   },
>   computed: { 
>     // 
>   },
>   watch: {
>     // 
>   },
>   created(){ 
>     // this.PartOne.aaaFn();  // 设想的使用形式 
>   },
>   methods: {
>     // 扩展使用对象形式，从而支持命名空间化 
>     // aaa: {
>     //   bbb: ()=>{
>     //     console.log(this);
>     //   },
>     // },
>     cccFn(){
>       this.PartOne.key11 = 333;
>     },
>   },
>   
>   // 命名空间模式 
>   PartOne: {
>     // 自动合并到顶层 data 中, 
>     // 设想：命名空间内 this.xx 访问，其他命名空间或上层 this.spaceName.xxx 访问  
>     data: {
>       key11: 111,
>     },
>     // 以下选项同 data 的处理逻辑 
>     computed: { },
>     watch: { },
>     methods: { 
>       aaaFn(){  // 注意此处不可使用箭头函数 
>         this.PartOne.key11 = 222;
>         // this.key11 // 设想的使用形式 
>       }
>     },
>     // 生命周期函数则不需要，顶层中调用该命名空间内的方法即可 
>   },
>   
>   PartTwo: {
>     // ... 
>   },
> };
> export default dealVueOptions(options);
> </script> 
> 
> <style lang="less" scoped> 
> </style> 
> <style lang="less"> 
> </style> 
> 
> // 处理函数   暂且为之 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> /** 处理vue的选项配置，改造成按模块、命名空间划分的形式  
> * @params  option  obj,待处理的vue配置选项
> * @return  option  obj,标准vue可识别的配置选项 
> * -----------------------------
> * @author  fsl 
> * @time    2020.12.20 
> * -----------------------------
> * @detail  
> - 01 详细说明1 
> * -----------------------------
> * @todo  
> - 1 代办事项1 
> */
> 
> export default function(option){
>   let result = {}
>   for (let key in option) {
>     let val = option[key];
>     // 不以大写字母开头则不处理  
>     if (!/^[A-Z]/.test(key)) { 
>       result[key] = val
>       continue;
>     }
>     
>     // 此处需要优化，暂且为之  
>     result = {
>       ...result,
>       ...dealVal(key,option),
>     }
>   }
>   
>   return result;
> }
> function dealVal(key,opt){
>   let res = {};
>   let obj = opt[key];
>   for(let k in obj){
>     let v = obj[k];
>     if (k==='data') {
>       opt.data = opt.data || (()=>({}));
>       res.data = ()=>{
>         return {
>           ...opt.data(),
>           [key]: { ...v, },
>         }
>       }
>     }
>     else {
>       let currentV = {};
>       for(var _v in v){
>         // 暂时的解决办法，使用： 命名空间_方法名 
>         // 待其他选项支持对象模式后可改成 命名空间.方法名的形式 来进行访问调用 
>         currentV[`${key}_${_v}`] = v[_v]; 
>       };
>       res[k] = {
>         ...opt[k],
>         // todo 
>         ...currentV,
>       }
>     }
>   };
>   return res;
> } 
> ```
> 
> ### What does the proposed API look like?
> 类似于vuex的命名空间化

it`s available  in react now, but it is harder in vue

**Comment by Justineo** [comment]
你直接使用局部的 mixin 就已经完美解决你的问题了。

**Comment by justfn** [comment]
> 你直接使用局部的 mixin 就已经完美解决你的问题了。

然鹅并没有啊， mix没有命名空间的隔离，逻辑还是混在一起了 【各种被诟病的地方，才有vue3吧】

**Comment by justfn** [comment]
> > 你直接使用局部的 mixin 就已经完美解决你的问题了。
> 
> 然鹅并没有啊， mix没有命名空间的隔离，逻辑还是混在一起了 【各种被诟病的地方，才有vue3吧】

拆成更细粒度的组件，可以有类似的效果，但是多了繁琐的组件通信

**Comment by Justineo** [comment]
你可以用一个工厂方法生成 mixin，也可以做到让命名不冲突。
