### ISSUE TITLE
Inconsistent Handling of slots.default and scopedSlots.default

### ISSUE THREAD

**Issue by nVitius** [vuejs/vue#11848]
### Version
2.6.11

### Reproduction link
[https://codepen.io/nVitius/pen/ZEpxXyW](https://codepen.io/nVitius/pen/ZEpxXyW)

### Steps to reproduce
The CodePen already has everything set up. The RenderScoped component only renders this.$scopedSlots.default. The RenderBoth component renders both the $scopedSlots.default and $slots.default

### What is expected?
The documentation for [$scopedSlots](https://vuejs.org/v2/api/#vm-scopedSlots) points that $slots will be exposed in $scopedSlots in 2.6.0 .

### What is actually happening?
In cases where un-named scoped and non-scoped slots are mixed in a component, the non-scoped slots are only available in $slots.default. However, when all the slots are non-scoped, they are available in both $slots.default and $scopedSlots.default.

---
un-named non-scoped slots behave a bit differently than un-named scoped slots.
https://vuejs.org/v2/api/#vm-slots
> The `default` property contains either nodes not included in a named slot or contents of `v-slot:default`

This doesn't happen for scoped slots. If you try to create two un-named (or with the same name) scoped slots, one will overwrite the other.

I don't think that this is necessarily bad (though I don't see why they couldn't be joined). The problem is that the `render` function is supposed to assume that all the slots are available in $scopedSlots. So then you might say that whoever is responsible for writing the slots should be aware that there is an issue. 

I think the compiler should either throw a warning when this might happen (it already warns you if you try to mix abbreviated default slots and named slots). Or scoped slots should allow for multiple slots with the same name (I'm not familiar enough with the internals to know if this makes sense).

**Comment by posva** [comment]
This is because you are using the deprecated syntax of slot-scope that was initially different from regular slots. The unified syntax is only available with v-slot
