### ISSUE TITLE
Unhandled error during execution of watcher callback

### ISSUE THREAD

**Issue by zss520** [vuejs/vue#11841]
### Version
3.0.4

### Reproduction link
[https://github.com/zss520/v3demo.git](https://github.com/zss520/v3demo.git)

### Steps to reproduce
点击菜单上的任意一级之后，再点击一级目录（无下级的），就会出现这个错误
![vue-bug](https://user-images.githubusercontent.com/40231571/103194765-92286e80-491b-11eb-9d69-e42a61b7a0df.png)
![2C45D4~1](https://user-images.githubusercontent.com/40231571/103194770-948ac880-491b-11eb-9957-121386487c8f.PNG)

### What is expected?
无报错，正常跳转

### What is actually happening?
点击任意菜单之后，再点击一级目录报错，无法跳转

---
vue版本号：3.0.4

**Comment by posva** [comment]
Read https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro and provide a boiled down repro with only Vue (no router, store, typescript, element ui etc) and if you stil face the issue open it in the correct repository (see link)
