### ISSUE TITLE
Can deep copy be used to realize component data reuse processing？

### ISSUE THREAD

**Issue by linktoword** [vuejs/vue#11851]
### What problem does this feature solve?
使用深拷贝能否实现组件data复用处理，data定义为一个函数返回一个对象，可以使复用的组件状态相互独立，那么假如内容使用深拷贝隔绝各个组件data对象的相互关系，是否可以达到目的？为什么？

### What does the proposed API look like?
none

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
