### ISSUE TITLE
"Attributes shorthand" in v-for cycles

### ISSUE THREAD

**Issue by vlado-l** [vuejs/vue#11859]
### What problem does this feature solve?
Vue is famous for its highly readable syntax and this can make it even more readable. 

### What does the proposed API look like?
Instead of writing duplicities in v-for cycles like this:

&lt;elm
  v-for="({ value, class, 'data-image' }, key) in elmprops"
  :value="value"
  :class="class"
  :data-image="data-image"
  :key="key"
/&gt;

Would by nice to have "attributes shorthand" like this:

&lt;elm
  v-for="({ value, class, 'data-image' }, key) in elmprops"
  :value
  :class
  :data-image
  :key
/&gt;

Like the object properties shorthand works in ES:

let routes = []
let router = { routes }

instead of unnecessary duplicities in older syntax:

let routes = []
let router = { routes: routes }

**Comment by sqal** [comment]
https://github.com/vuejs/vue/pull/2877
