### ISSUE TITLE
this.$slots contents differ at same lifecycle stage based on slot syntax

### ISSUE THREAD

**Issue by tehciolo** [vuejs/vue#11854]
### Version
2.6.11

### Reproduction link
[https://codepen.io/tehciolo/pen/zYKaRQK](https://codepen.io/tehciolo/pen/zYKaRQK)

### Steps to reproduce
Check console

### What is expected?
I would expect this.$slots to be populated at the same stage for both syntaxes (old and new).

### What is actually happening?
this.$slots is populated only starting with `mounted` when using `v-slot` syntax

---
This issue seems related to https://github.com/vuejs/vue/issues/9458

**Comment by posva** [comment]
This is expected because both syntaxes were different and they are unified only in Vue 3 to avoid breaking changes in Vue 2. More details have been given in similar issues
