### ISSUE TITLE
Please expose transition API?

### ISSUE THREAD

**Issue by milesingrams** [vuejs/vue#11852]
### What problem does this feature solve?
Many issues have requested the ability to add `.visible` modifiers to `v-show` or to implement something similar like `v-visible` in their own directives, but despite closing these issues, it has not been made possible. Exposing the transition api (`vue/src/platforms/web/runtime/modules/transition`) would make this possible.

### What does the proposed API look like?
Once upon a time the transitions API was exposed as `Vue.transition.applyTransition()`. Honestly any variant of this would be fine. I'm not sure why it was removed?

**Comment by posva** [comment]
If it was removed, the reasoning has been included in an issue, released notes or similar and is unlikely to be added back. I would say it is to keep things declarative. If you think this is worth pursuing, you should open an RFC at https://github.com/vuejs/rfcs
