### ISSUE TITLE
3.0 vue 的render函数（h）不支持 directive

### ISSUE THREAD

**Issue by openart** [vuejs/vue#11855]
### What problem does this feature solve?
2.0 时候 支持传入 directives 数组，但是3.0 之后扁平化了，也没办法自定义指令了

### What does the proposed API look like?
h() 参数

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
