### ISSUE TITLE
bug: ref with v-for

### ISSUE THREAD

**Issue by JackShell2020** [vuejs/vue#11869]
### Reproduction link
[https://codepen.io/nShell/pen/RwGqpoJ](https://codepen.io/nShell/pen/RwGqpoJ)

### Steps to reproduce
打开F12开发者工具，刷新页面，查看打印输出。切换vue版本后再次查看输出

### What is expected?
如文档所描述输出数组

### What is actually happening?
输出类型与文档描述不符

---
在文档中说明，ref 与 v-for 一起使用时的两种情况，和对应的结果

**Comment by posva** [comment]
See https://v3.vuejs.org/guide/migration/array-refs.html#frontmatter-title
Note the repo of Vue 3 is vue-next
