### ISSUE TITLE
 Content Security Policy directive after build to production 

### ISSUE THREAD

**Issue by huntz20** [vuejs/vue#11868]
### Version
2.6.11

### Reproduction link
[https://realsportindo.com/event/kejuaraan-kata-virtual-forki-jabar-2020/medals](https://realsportindo.com/event/kejuaraan-kata-virtual-forki-jabar-2020/medals)

### Steps to reproduce
1. npm run build with websocket 
2. deploy to server 

### What is expected?
web socket should work properly 

### What is actually happening?
```
Refused to connect to 'wss://example.com/socket//websocket?vsn=1.0.0' because it violates the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

---
nb: 
already check on development work fine
already add meta on head

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests about Vue only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
