### ISSUE TITLE
 Is it anti-pattern to create component 100% by composition api #822 

### ISSUE THREAD

**Issue by aStanleyLiang** [vuejs/vue#11875]
Recently I start my first vue3 project and I found the new feature Composition API. I wonders whether it is anti-pattern or not to 100% adopt Composition API to implement component? Because originally I think the purpose of Composition API is to encapsulate logic and can be imported by components. I searched a lot and cannot determine: lots of articles introduce the comparison between Composition API and Options API that looks like I even can implement through Composition API 100% without Options API.

I know it's working and many voices on internet suggest so. Just wondering is it anti-pattern or not? I don't wanna abuse Composition API if originally it's not design to implement a view component.

Appreciate in advance, stay safe🤙

**Comment by sirlancelot** [comment]
Certainly not an anti-pattern and in fact, probably ideal.

**Comment by aStanleyLiang** [comment]
> Certainly not an anti-pattern and in fact, probably ideal.

Sincerely appreciate your reply despite the issue is closed by the vue-bot that looks like I should not post a general discussion here instead of feature request or bug report
