### ISSUE TITLE
在html模板的正文中，对data里面的属性读取时，若有计算操作，结果是错误的

### ISSUE THREAD

**Issue by GeTOUO** [vuejs/vue#11879]
### Version
2.6.11

### Reproduction link
[https://codepen.io/team/Vue/pen/rNVqYvM](https://codepen.io/team/Vue/pen/rNVqYvM)

### Steps to reproduce
我正在学习vue，当我跟随教程打开组件部分的如下示例时：

[Component basics: reusing components](https://codepen.io/team/Vue/pen/rNVqYvM)

我修改了 template 部分的内容为： 
```
    <button v-on:click="count++">
      You clicked me {{ ++count }} times.
    </button>
```

然后 count 每次递增的值变成了102？

### What is expected?
期望计算是正确的 `++count === count+=1`

### What is actually happening?
`++count === count+=102`

---
目前我还不清楚vue解析模板的逻辑。但看起来这应该是一个bug

**Comment by Justineo** [comment]
因为你写了 `++count`，所以在每次渲染的时候 `count` 都自增了。

**Comment by GeTOUO** [comment]
> 因为你写了 `++count`，所以在每次渲染的时候 `count` 都自增了。

是的，正是因为我修改成了`++count`, 但是，我期望的是每次自增1，实际上每次自增了102.

**Comment by GeTOUO** [comment]
这到底算不算是一个bug呢
