### ISSUE TITLE
父组件条件渲染的时候加了class样式，导致子组件中无法接收到父组件传递的值

### ISSUE THREAD

**Issue by Duanzihuang** [vuejs/vue#11874]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1、在父组件渲染的时候，加了一个条件渲染，并且多加了一个class
2、父组件里面使用到了子组件，并且给子组件传值
3、在子组件中监听父组件传递过来的值
4、在子组件中监听父组件值的时候，无法获取传递过来的值

### What is expected?
期待能正常在子组件中，继续监听父组件传递过来的值。

### What is actually happening?
实际发生就是在子组件的watch中，无法获得父组件传递过来的值

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
