### ISSUE TITLE
Why can't filter be enclosed in brackets when combining with ternary expression.

### ISSUE THREAD

**Issue by cc147151** [vuejs/vue#11872]
### Version
2.6.11

### Reproduction link
[https://github.com/cc147151/filterTest](https://github.com/cc147151/filterTest)

### Steps to reproduce

{{info.status && info.status == '1' ? '进行中' : ( info.modified_time |getFormalTime ) }}  显示原数据内容即时间戳，过滤失败
{{info.status && info.status == '1' ? '进行中' : info.modified_time |getFormalTime }}  括号去掉， 可以成功过滤

### What is expected?
期望加上括号也应该过滤出所期待的时间

### What is actually happening?
结果是未过滤的结果

**Comment by Justineo** [comment]
Vue 的过滤器表达式是形如 `<expression> | <filters>` 的特殊语法，并不是 JavaScript 表达式。

**Comment by cc147151** [comment]
大佬，但是使用括号包裹一下，这样也算违反了语法吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs/vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 下午3:49
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"宋金洋"<1471517131@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue] Why can't filter be enclosed in brackets when combining with ternary expression. (#11872)





 
Vue 的过滤器表达式是形如 <expression&gt; | <filters&gt; 的特殊语法，并不是 JavaScript 表达式。

**Comment by infinnie** [comment]
> 大佬，但是使用括号包裹一下，这样也算违反了语法吗？

普通的 | 运算符是按位或运算

**Comment by cc147151** [comment]
谢谢大佬，好像有点头绪了。十分感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs/vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 下午5:13
收件人:&nbsp;"vuejs/vue"<vue@noreply.github.com&gt;;
抄送:&nbsp;"宋金洋"<1471517131@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue] Why can't filter be enclosed in brackets when combining with ternary expression. (#11872)





  
大佬，但是使用括号包裹一下，这样也算违反了语法吗？
  
普通的 | 运算符是按位或运算
