### ISSUE TITLE
Added compiler change to reduce lines of code / increase readability

### ISSUE THREAD

**Issue by FiniteRealityTech** [vuejs/vue#11871]
### What problem does this feature solve?
I was putting rows and columns on a grid layout and I thought it would be nice if we could add something to reduce the number of html tags. My thought is by adding a way to turn an end tag into a end and beginning tag would help reduce clutter on the Vue pages.

Example:
</b-row*>
When compiled into the dist folder or locally:

I figured making this change to html would likely not happen or take a long time. We do end tags with a /> to be self closing and reduce clutter, I was thinking it would be nice to do it the other way as well.

### What does the proposed API look like?
Not sure.

**Comment by posva** [comment]
Unfortunately Vue aims to be valid HTML so this won't be possible

**Comment by FiniteRealityTech** [comment]
Where is that stated? Not trying to be difficult, I would have never have asked the question if I had known that before I posted the issue. Also, not really a big deal, I believe I should be able to download the repo and change the Vue compiler myself, if I can even find it that is. Actually, it may be better as a plugin. So, maybe I should have started down the plugin route.
