### ISSUE TITLE
Vue3 migration not works as expected

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue#11878]
### Version
3.0.5

### Reproduction link
[https://github.com/kumaresan-subramani/vue3-suport](https://github.com/kumaresan-subramani/vue3-suport)

### Steps to reproduce

- clone above mentioned smple

- then `npm i`

- finally npm run serve

- browser throws script error, but the same working fine in `vue2`

### working sample

sample with `"vue": "^2.6.11` works fine without any error

**Working sample** - https://github.com/Saranya13/vue-sample/

### Environment info
```
"vue": "^3.0.5"
"@vue/cli-plugin-babel": "^4.5.10",
    "@vue/cli-plugin-eslint": "^4.5.10",
    "@vue/cli-service": "^4.5.10",
    "@vue/compiler-sfc": "^3.0.5",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-vue": "^7.4.1",
```

### What is expected?
component gets rendered without script error

### What is actually happening?
throws script error

```
component-base.js?5981:6 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (component-base.js?5981:6)
    at __extends (component-base.js?5981:9)
    at eval (component-base.js?5981:20)
    at eval (component-base.js?5981:195)
    at Module../node_modules/@syncfusion/ej2-vue-base/src/component-base.js (chunk-vendors.js:575)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (index.js?4867:1)
    at Module../node_modules/@syncfusion/ej2-vue-base/src/index.js (chunk-vendors.js:599)
```

**Comment by kumaresan-subramani** [comment]
## For more details refer below issue link

https://github.com/vuejs/vue-cli/issues/6217

**Comment by posva** [comment]
Well, you have to migrate your code to Vue 3: https://v3.vuejs.org/guide/migration/introduction.html, it's normal for it not to magically work out of the box.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
