### ISSUE TITLE
Scroll issue with navigation

### ISSUE THREAD

**Issue by aljabr** [vuejs/vue#11877]
### Version
2.6.11

### Reproduction link
[https://router.vuejs.org/guide/#html](https://router.vuejs.org/guide/#html)

### Steps to reproduce
Navigate after scrolling between pages  on ios

### What is expected?
While swiping between pages it should show the page not blank

### What is actually happening?
When the scroll position not matches between pages it will show blank page

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15986585/105281098-69af2f80-5bbc-11eb-98b8-2b92c34ad618.gif)

**Comment by posva** [comment]
This is a browser behavior, not related to Vue
