### ISSUE TITLE
Why v-bind="$attrs" cannot replace the declared same name props in front of itself?

### ISSUE THREAD

**Issue by wangziling** [vuejs/vue#11888]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/cocky-brahmagupta-ejn2z](https://codesandbox.io/s/cocky-brahmagupta-ejn2z)

### Steps to reproduce
See the codesandbox result~

### What is expected?
In my opinion and normal thoughts, if `v-bind="$attrs"` or `v-bind="$props"` is behind a declared and in same name property, it should replace the property value ahead.

```js
<a href="https://qq.com" v-bind="$attrs">Test</a>
```
if `$attrs` contain the property named 'href', In the normal thoughts, it should replace the data ahead.

### What is actually happening?
Cannot replace.

---
Am I wrong?
Or Hmmm... `v-bind="$attrs"` take the lower priority of the normal `v-bind:href="__"`?

**Comment by posva** [comment]
In Vue 3, the order of attributes matter but in Vue 2 they don't and a single attribute is more specific that a `v-bind`. See https://github.com/vuejs/vue/issues/7811

**Comment by wangziling** [comment]
OK. Thank you. @posva.

I left a version3 demo.
https://codesandbox.io/s/brave-rubin-gofp0
