### ISSUE TITLE
Using 'in mobile devices' window.orientation ' exception

### ISSUE THREAD

**Issue by songmengda** [vuejs/vue#11896]
### Version
2.6.10

### Reproduction link
[https://codepen.io/songmengda/pen/PobYxqJ](https://codepen.io/songmengda/pen/PobYxqJ)

### Steps to reproduce
1.1. Use the code in the recurrence link to start a Vue cli project through NPM, and use the mobile device to scan the code to access the page
2. When the mobile phone switches between horizontal screen and vertical screen, the 'onreset' function is triggered. At this time, the 'text' value on the mobile phone screen does not match the real scene，For example, the mobile phone is in horizontal screen mode, but the vertical screen mode is displayed on the screen
3.By printing the window object with vconsole, we find that its orientation value is correct, but through the window.orientation 'the value is wrong

### What is expected?
Using Vue judgment in mobile terminal window.orientation The correct result can be obtained with the value of

### What is actually happening?
Use in Vue window.orientation The value obtained is inconsistent with the real orientation in window

---
Using Vue to develop a need to switch the horizontal screen vertical screen state of the page, using the window.orientation Get the right results, not the wrong ones

`
<template>
  <div class="vue-template">
    {{text}}-{{orientation}}
  </div>
</template>

<script>
export default {
  data () {
    return {
      text: '默认',
      orientation: 0
    }
  },

  created () {
    this.orientation = window.orientation
    if(window.orientation === 180 || window.orientation === 0){ // 竖屏
      this.text = '竖屏'
    }

    if (window.orientation === 90 || window.orientation === -90) { //横屏
      this.text = '横屏'
    }

    let _this = this
    window.onresize = function (){
      _this.orientation = window.orientation
      if(window.orientation === 180 || window.orientation === 0){ // 竖屏
        _this.text = '竖屏'
      }

      if (window.orientation === 90 || window.orientation === -90) { //横屏
        _this.text = '横屏'
      }
      console.log(window)

    }
  }
}
</script>

After repeatedly rotating the phone：
`

![image](https://user-images.githubusercontent.com/35358253/106162768-6c64e280-61c3-11eb-8b09-6f27fa1ec9a1.png)

![image](https://user-images.githubusercontent.com/35358253/106162797-771f7780-61c3-11eb-8ac0-80532b91be36.png)

![image](https://user-images.githubusercontent.com/35358253/106162846-8272a300-61c3-11eb-8192-55469930a605.png)

**Comment by posva** [comment]
I couldn't reproduce but this shouldn't be related to Vue. Also `window.orientation` is deprecated

**Comment by songmengda** [comment]
```
<template>
  <div class="vue-template">
    {{text}}-{{orientation}}
  </div>
</template>

<script>
export default {
  data () {
    return {
      text: '默认',
      orientation: 0
    }
  },

  created () {
    this.orientation = window.orientation
    if(window.orientation === 180 || window.orientation === 0){ // 竖屏
      this.text = '竖屏'
    }

    if (window.orientation === 90 || window.orientation === -90) { //横屏
      this.text = '横屏'
    }

    let _this = this
    window.onresize = function (){
      _this.orientation = window.orientation
      if(window.orientation === 180 || window.orientation === 0){ // 竖屏
        _this.text = '竖屏'
      }

      if (window.orientation === 90 || window.orientation === -90) { //横屏
        _this.text = '横屏'
      }
      console.log(window)

    }
  }
}
</script>```

**Comment by songmengda** [comment]
If you only use HTML and native JS instead of Vue, you can get the screen direction of the mobile phone normally. Thank you for your answers

**Comment by songmengda** [comment]
Although it seems that this problem will not happen, it does appear in the real scene. For this reason, I specially watched the window.outerWidth The 'outerwidth' attribute is normal, so I'm worried about why the 'orientation' attribute can't be updated in time when the 'onreset' function is triggered in Vue environment.
