### ISSUE TITLE
errorHandler not catching exceptions in promises with .then() inside v-on

### ISSUE THREAD

**Issue by adamsol** [vuejs/vue#11893]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/adamsol/hj6q32v0/](https://jsfiddle.net/adamsol/hj6q32v0/)

### Steps to reproduce
Click the three buttons.

### What is expected?
Exceptions for all the buttons should be captured and displayed below.

### What is actually happening?
Exception for the second button isn't captured.

---
Related to #7653.

I'm using `@click="doAction().then(close)"` for closing modal windows after successfully finishing async actions. A workaround for exceptions in `doAction` to be captured by `errorHandler` is to add `() =>` in the event handler, but it's not obvious.

**Comment by posva** [comment]
It's not a workaround, it's the proper thing to do if you want to care about the returned value (here the promise)

See the generated code differences: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%3Cp%3EException%20in%20button2%20%40click%20is%20not%20captured%20by%20errorHandler.%3C%2Fp%3E%0A%20%20%3Cbutton%20%40click%3D%22click(1)%22%3E%0A%20%20%20%20button1%0A%20%20%3C%2Fbutton%3E%0A%20%20%3Cbutton%20%40click%3D%22click(2).then(a%20%3D%3E%20a)%22%3E%0A%20%20%20%20button2%0A%20%20%3C%2Fbutton%3E%0A%20%20%3Cbutton%20%40click%3D%22()%20%3D%3E%20click(3)%22%3E%0A%20%20%20%20button3%0A%20%20%3C%2Fbutton%3E%0A%20%20%3Cp%3E%7B%7B%20message%20%7D%7D%3C%2Fp%3E%0A%3C%2Fdiv%3E%0A

**Comment by adamsol** [comment]
So why exactly isn't there a `return` in the generated code in the second case, but there is one in the first case? Is this behaviour documented somewhere?
