### ISSUE TITLE
Walrus operator within v-if statement

### ISSUE THREAD

**Issue by 0x78f1935** [vuejs/vue#11892]
### What problem does this feature solve?
Allow us to use the value of an v-if statement to be used in children elements. Perhaps by [imitating the Python walrus operator](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions).

### What does the proposed API look like?
```
<div v-if="result in foo(bar)">
    <label :class="result">Test</label>
</div>
```

EDIT: I guess returning an array would work
EDIT2:

Perhaps more like
```
<div v-if="result in foo(bar) if result != 'foo'">
    <label :class="result">Test</label>
</div>
```

**Comment by posva** [comment]
Thanks for the proposal but Vue uses existing JS syntax only
