### ISSUE TITLE
lifetime of Vue JS 2

### ISSUE THREAD

**Issue by Alymbek** [vuejs/vue#11899]
### Version
2.6.11

### Reproduction link
[https://github.com/intlify/vue-i18n-next/issues/331](https://github.com/intlify/vue-i18n-next/issues/331)

### Steps to reproduce
can't find any info about life term and LTS version

### What is expected?
long life the King!

### What is actually happening?
I worried about the life term and  long term support after.

---
I just start project on VueJS 3, but facing more problems with some of the library.
Especially IE support for most of library(even **Vue JS version 3 not work in IE now and other library in Edge**).

So, my question is - how long time you'll support Vue JS version 2?
When you planned to close maintain version 2?

Is version 2 support IE? As well Edge?

Is version 2 still actual for modern web-development?
Do you have any benchmark to compare between version 2 and 3?

PS. My project is small now and I hope that I can easily migrate to version 3 if I start now with version 2.

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue/projects/6#card-34430029

**Comment by Alymbek** [comment]
thank you for your reply, dear @LinusBorg

**Comment by antfu** [comment]
Closing this for now if there are no further questions. Thanks.
