### ISSUE TITLE
Vue with Blazor

### ISSUE THREAD

**Issue by HashemGo** [vuejs/vue#11898]
### What problem does this feature solve?
I need to use Vue js with Blazor is there any steps, please

### What does the proposed API look like?
.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
