### ISSUE TITLE
v-model.number incorrectly handles of negative numbers between 0 and -1 when manually emit @input event

### ISSUE THREAD

**Issue by yuwu9145** [vuejs/vue#11897]
### Version
2.6.12

### Reproduction link
[https://codepen.io/yuchaosydney/pen/oNYNJad](https://codepen.io/yuchaosydney/pen/oNYNJad)

### Scenario
When making a custom input component (lets call it `customInput` & use it as `<customInput v-model.number="[a property]">`). When `customInput` manually does `this.$emit('input', value)`. Then `v-model.number` is not able to correctly handle a negative number between 0 and -1. But any other negative numbers (e.g. `-1.3`) are ok.

### Steps to reproduce
1. Load CodePen link
2. Try to input "-0.3"

### What is expected?
The input box should allow "-0.3"

### What is actually happening?
The input box displays "0.3"

**Comment by posva** [comment]
You need to cast it into Number (this.$emit('input', Number(value))) and only emit if the number is valid to avoid setting the value to NaN or an invalid cast. Note that `.number` only work on native v-model, not on custom components. This has raised and adressed in Vue 3

**Comment by yuwu9145** [comment]
Thank you @posva ! Probably this [doc](https://vuejs.org/v2/guide/forms.html#number) should provide this info? Or any other places mention this?
