### ISSUE TITLE
Keep-alive filter by slot's key.

### ISSUE THREAD

**Issue by ruojianll** [vuejs/vue#11901]
### What problem does this feature solve?
Keep-alive filter by slot instance.

I need to use it to filter my route component in `router-view` by `:key="$route.fullPath"`

### What does the proposed API look like?
```
<keep-alive :include-keys="function(keyOfSlot:string) or regex or string">
  <component :key="myKey"/>
</keep-alive>
```

**Comment by posva** [comment]
Duplicate of #8028
