### ISSUE TITLE
$refs might contain values in incorrect order when using with template

### ISSUE THREAD

**Issue by vbarbarosh** [vuejs/vue#11903]
### Version
2.6.11

### Reproduction link
[https://codepen.io/vb-bannernow/pen/LYbNrqL](https://codepen.io/vb-bannernow/pen/LYbNrqL)

### Steps to reproduce
Just open a codepen and click on a silver area.

### What is expected?
[ "1", "1.5", "2", "3" ]

### What is actually happening?
[ "1", "1.5", "3", "2" ]

**Comment by posva** [comment]
See https://github.com/vuejs/vue/issues/4952#issuecomment-280661367
