### ISSUE TITLE
Lifecycle hooks typings not showing

### ISSUE THREAD

**Issue by tbhaxor** [vuejs/vue#11900]
### Version
2.6.11

### Reproduction link
[https://null](https://null) 

_Its more of typing issue than functionality bug_

### Steps to reproduce
1. Setup a typescript project
2. Create class component using vue-property-decorator
3. In class enter `crea` and invoke completions in vscode (use the CTRL   SPACE)
4. Erase `crea` and again invoke completions

### What is expected?
It should list all the list of lifecycle hooks when requested completions like other functions `$forceUpdate`..

### What is actually happening?
No typings for lifecycle hooks

---
Here the typings of external package vue-toast is being shown in vue class but not of vue lifecycle hooks

![](https://i.imgur.com/ZIp2BUr.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).


---


This is not directly related to Vue but rather the plugins or the editor
