### ISSUE TITLE
[Bug] :class="false" causes class being rendered

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vue#11902]
### Version
2.6.11

### Steps to reproduce
```html
<template>
  <div :style="false" :class="false" :foo="false">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium modi
    repudiandae, illum sequi nemo est deleniti optio distinctio quaerat quasi
    dolores vitae aspernatur quisquam, voluptatibus quibusdam ullam, ipsum aut
    amet?
  </div>
</template>
```

### What is expected?
Per
> [... If isButtonDisabled has the value of null, undefined, or false, the disabled attribute will not even be included in the rendered <button> element.](https://vuejs.org/v2/guide/syntax.html#Attributes).

None of `foo`, `class`, `style` should be rendered.

### What is actually happening?
`class` is rendered.

**Comment by posva** [comment]
This is intended. Please search existing issues
