### ISSUE TITLE
camelCase properties are not converted to kebab-case when using `v-bind="{ }"` object syntax on a native element

### ISSUE THREAD

**Issue by sh0ber** [vuejs/vue#11913]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/sh0ber/cqo7yjex/](https://jsfiddle.net/sh0ber/cqo7yjex/)

### Steps to reproduce
1.  Use the `v-bind` object syntax on a _native element_ like `<div v-bind="{ camelCase: 'myvalue' }"></div>`
2.  Give the object a camelCase property
3.  Inspect the element to see that the attribute converts to lowercase, not kebab-case

### What is expected?
It should convert the camelCase property to a kebab-case attribute:  `<div camel-case="myvalue"></div>`

### What is actually happening?
It converts the camelCase to lowercase instead, with no hyphen:  `<div camelcase="myvalue"></div>`

---
Why is this an issue?  It causes a problem when using scoped slots with slot props.  Slots automatically create a slot props object for bindings which converts (correctly) any kebab-case properties to camelCase.  But if you then `v-bind` the slot props to a native element, like `<div v-bind="slotProps"></div>`, i.e. spreading the props back to attributes to reverse the conversion, it strips the hyphen.
 
For example, `<slot aria-haspopup="true"></slot>`.

The attribute gets converted (correctly) to camelCase in the resulting slotProps object: `{ ariaHaspopup: true }`.

Then if you `<div v-bind="slotProps"></div>` in the parent slotted content, expecting it to de-convert the slot prop from camelCase back to kebab-case, it actually only converts it to lowercase instead:  `<div ariahaspopup="true"></div>`, with no hyphen.

Here is a demo of that:  https://jsfiddle.net/sh0ber/wavLkd9f/

Notice the button's attribute is missing a hyphen.

**Comment by posva** [comment]
This is expected and changing it would be limiting because some properties are in camelCase. You have to write `{ 'aria-has-popup': 'true' }`

**Comment by sh0ber** [comment]
The problem is that slotProps converts it to camelCase and then it can't be converted back with `v-bind`.  Please check the second demo carefully, as what you suggested can't be done:  https://jsfiddle.net/sh0ber/wavLkd9f/

**Comment by sh0ber** [comment]
This is still a bug despite being ignored.

When camelCase properties are put directly onto an HTML element, it should convert them to kebab-case.  This is important because slotProps creates camelCase properties from attributes, but then messes them up when placing them back on.

**Comment by vincerubinetti** [comment]
> it would be limiting because some properties are in camelCase

What properties are in camelCase?
