### ISSUE TITLE
Cannot turn on production mode (webpack)

### ISSUE THREAD

**Issue by yellow1912** [vuejs/vue#11915]
### Version
2.6.11

### Reproduction link
[https://gist.github.com/yellow1912/c091cec5e35f6fefa56031aadf2c2758](https://gist.github.com/yellow1912/c091cec5e35f6fefa56031aadf2c2758)

### Steps to reproduce
I'm using npm build scripts and webpack (without vue cli) to build my package, the build script looks like this:

cross-env NODE_ENV=production webpack --mode=production

The webpack config file is attached in the link:
https://gist.github.com/yellow1912/c091cec5e35f6fefa56031aadf2c2758

My main.js file looks like this:
```
window.Vue = require('vue');
//.... some more code
```

### What is expected?
The build file to be in production mode

### What is actually happening?
I keep getting You are running Vue in development mode.

---
I'm using the following versions for webpack modules:

"webpack": "^4.46.0",
"webpack-cli": "^4.5.0"

**Comment by LinusBorg** [comment]
you have an alias set to the global build. it should be set to the esm build.

Builds:

https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

**Comment by yellow1912** [comment]
Thank you, I think I used the alias to specify full build (because I need to use inline-template). That was why the production mode did not work. Perhaps we can add a note on this particular page to make it clear for others?

https://vuejs.org/v2/guide/deployment.html#Turn-on-Production-Mode

I can submit a PR if necessary.
