### ISSUE TITLE
CSS infinite animation stops moving when the component is toggled

### ISSUE THREAD

**Issue by njh7799** [vuejs/vue#11916]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-animation-toggle-bug-quliq?file=/src/App.vue](https://codesandbox.io/s/vue-animation-toggle-bug-quliq?file=/src/App.vue)

### Steps to reproduce
1. Create simple component which contains CSS animation which has property "infinite" *ex) Loading Indicator
2. Import the component into the main page
3. Create toggle button on the main page which choose to render the component or not (<some-component v-if="showComponent"/>)
4. Run the Code and test on the IOS 13 device

### What is expected?
CSS animation works normally.

### What is actually happening?
CSS animation stops running when toggled.

---
- env: Iphone IOS13
- reproduction video  
![IOS13](https://user-images.githubusercontent.com/40619551/108187520-e7317580-7151-11eb-94a5-ec65fdd96f1e.gif)

**Comment by posva** [comment]
Tested on a real iPhone 11 with safari 13 and it works
