### ISSUE TITLE
Vue.prototype.$on should remove debupicate callback function

### ISSUE THREAD

**Issue by 412799755** [vuejs/vue#11919]
### What problem does this feature solve?
e.g.
function callback(){}
Vue.prototype.$on("test",callback)
Vue.prototype.$on("test",callback)
callback function should be triggered only once like the dom api EventTarget.addEventListener() does.

### What does the proposed API look like?
remove duplicate callback

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
