### ISSUE TITLE
IDE, Authoring Tool, Marketing

### ISSUE THREAD

**Issue by prezire** [vuejs/vue#11911]
### What problem does this feature solve?
Hi guys. Has anybody noticed this thing called Framer.com using React? Pardon the external link https://youtu.be/hAPxeoP8wn8. Don't get me wrong. I love Vue. What I'm suggesting is for the Vue community to create a similar app in partnership with Adobe for Adobe Animate.

### What does the proposed API look like?
I'm hoping Vue to leverage marketing through Adobe because of its famous experience in creating fluid authoring IDE. However Adobe converts those organic animations to the web via HTML Canvas reducing its responsiveness and SEO features. Vue can take leverage of that approach.

Of couse Adobe has its issues with Open Source but it would be very nice to have a PR genius to solve that roadblock!

**Comment by posva** [comment]
Thanks for the proposal. We will see.
