### ISSUE TITLE
@change event not working in <b-form-datepicker/>

### ISSUE THREAD

**Issue by baldvinbui** [vuejs/vue#11918]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
The template is.

```
<div class="d-flex flex-row flex-nowrap">
            <b-form-select v-model="region"
                           :options="regions"
                           class="select_box"
                           @change="get_data()"
            />
            <b-form-datepicker id="first_day_datepicker"
                               v-model="first_day"
                               :min="min_day"
                               :max="max_day"
                               class="mb-2"
                               @change="get_data()"
            />
            <b-form-datepicker id="last_day_datepicker"
                               v-model="last_day"
                               :min="min_day"
                               :max="max_day"
                               class="mb-2"
                               @on-change="get_data()"
            />
</div>
```

And the funtcion looks like this(simplified for example)

```javascript
methods: {
        get_data() {
            console.log("Change data")
        },
}
```

### What is expected?
The get_data() function to be called on @change of datepicker form

### What is actually happening?
get_data() is not called

---
The select works perfectly by using the "@change", but this does not have any effect on the datepicker.

**Comment by posva** [comment]
Open the issue in bootstrap vue please

**Comment by baldvinbui** [comment]
SOLUTION: <b-form-datepicker/> does not have @change in it´s event list but it has @input which works for this.
