### ISSUE TITLE
IE  `<img :src="javascript:alert(1);">` error

### ISSUE THREAD

**Issue by github-linong** [vuejs/vue#11924]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/pisakif/3/edit?html,output](https://jsbin.com/pisakif/3/edit?html,output)

### Steps to reproduce
*browser: IE11*

### What is expected?
![image](https://user-images.githubusercontent.com/30680461/109009752-e23c6b00-76e9-11eb-83d5-4bc5a37bd847.png)

### What is actually happening?
`{{1}}`

---
有个 xss 场景，因为 Vue 做了相关防护，所以没有针对性处理。
但是在 IE 浏览器中，给 `img` 的 `src` 赋值为 `javascript:alert(1);` 时，会出现一个 error。

`el.setAttribute(key, value);`  抛出了一个禁止访问的异常。在我捕获了错误之后，渲染正常。

```
function baseSetAttr (el, key, value) {
    if (isFalsyAttrValue(value)) {
      el.removeAttribute(key);
    } else {
      // #7138: IE10 & 11 fires input event when setting placeholder on
      // <textarea>... block the first input event and remove the blocker
      // immediately.
      /* istanbul ignore if */
      if (
        isIE && !isIE9 &&
        el.tagName === 'TEXTAREA' &&
        key === 'placeholder' && value !== '' && !el.__ieph
      ) {
        var blocker = function (e) {
          e.stopImmediatePropagation();
          el.removeEventListener('input', blocker);
        };
        el.addEventListener('input', blocker);
        // $flow-disable-line
        el.__ieph = true; /* IE placeholder patched */
      }
      try{
        el.setAttribute(key, value);
      }catch(e){
        window.console && console.error && console.error(e)
      }
    }
  }
```

**Comment by posva** [comment]
You're still responsible for sanitizing your use data
