### ISSUE TITLE
run npm run dev  How can the referenced JS not be compressed I want to debug vue.js code

### ISSUE THREAD

**Issue by a6965921** [vuejs/vue#11923]
### What problem does this feature solve?
run npm run dev  How can the referenced JS not be compressed I want to debug vue.js code

### What does the proposed API look like?
run npm run dev  How can the referenced JS not be compressed I want to debug vue.js code

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
