### ISSUE TITLE
Mount component in a Plugin

### ISSUE THREAD

**Issue by lgmf** [vuejs/vue#11929]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/damp-haze-pjj60?file=/src/main.js](https://codesandbox.io/s/damp-haze-pjj60?file=/src/main.js)

### Steps to reproduce
https://github.com/lgmf/v-modal/blob/master/README.md

### What is expected?
I want to mount a component programmatically inside the same App that will use my plugin

### What is actually happening?
The Component being mounted programmatically is creating a new Vue App and because of that other plugins are not working, like i18n, router, store, etc

---
I have created a Vuejs plugin to handle dialogs https://github.com/lgmf/v-modal

It works with basic examples, but when I try to use with other plugins its breaking because the ModalContainer is beeing moutend programmatically and for that it uses another vue instance

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You should take a look at https://github.com/LinusBorg/portal-vue

**Comment by lgmf** [comment]
Got it! I'm sorry! Thanks for the orientation I'll post there
