### ISSUE TITLE
A medium level way to use components

### ISSUE THREAD

**Issue by Dania99dev** [vuejs/vue#11926]
### What problem does this feature solve?
We are front-end developers and we don't need to be worried about data and stuff.
What about having a medium level and use components for development only and then build pure html, css and js?
Then our only concern is the front-end itself, not anything else
and if vue has this feature let me know please: dania99.dev@gmail.com

### What does the proposed API look like?
before build:

```
mainDir
|- Assets
|- Components
|    |_ .vue file 1
|    |_ .vue file 2
|    |_ .vue file 3
|
|- index.html
|- main.js
```

after build:

```
mainDir
|- dist
    |_ images
    |_ css
    |_ js
    |
    |-index.html (all the components are bundled here)
```
something like this

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
