### ISSUE TITLE
Vue2 - Using provide and inject in components from local file system

### ISSUE THREAD

**Issue by relief-melone** [vuejs/vue#11937]
### Version
2.6.12

### Reproduction link
[https://jsfiddle.net/egbhs3pt/](https://jsfiddle.net/egbhs3pt/)

### Steps to reproduce
Use a parent component and Child component from a folder in your local file system that is not in your current project folder.

This would be the case e.g. for testing reusable components located in their own project folder and wanting to debug them

### What is expected?
Injected should be filled properly

### What is actually happening?
While the provided function seems to run as it should inject in the child component will fail with "Injection "my_injection" not found"

so while the same component will work with

import { MyComponent } from "my-new-component"

will work (like in the fiddle)

import { MyComponent } from "../../my-new-component"

will fail

**Comment by LinusBorg** [comment]
you will have to provide a reproduction that actually demonstrates the version that doesn't work. can be in a Github repo.

My suspicion would be that this is actually a problem with the project/build setup, not Vue core.

**Comment by posva** [comment]
Plesae read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro and open a new issue if you manage to boil it down

**Comment by relief-melone** [comment]
Done! I made it as simple as possible. The only thing I had to do is to include the "external folder" in the repo as well, but that seems to have the same effect as long as it is an individual project.

[11938](https://github.com/vuejs/vue/issues/11938)
