### ISSUE TITLE
Multidimensional array update bug

### ISSUE THREAD

**Issue by justb** [vuejs/vue#11932]
### Version
2.6.10

### Reproduction link
[https://codepen.io/lewiswei/pen/rNWrVBe](https://codepen.io/lewiswei/pen/rNWrVBe)

### Steps to reproduce
click one button

### What is expected?
this button's background changed

### What is actually happening?
this row of the button's background changed

**Comment by LinusBorg** [comment]
you're using `.fill()` to add the initial objects to the array. but you essentially add the same object 3 times. By changing one of those, you change all 3, as they are the same object.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#using_fill
