### ISSUE TITLE
SSR run server  show Cannot read property 'file'

### ISSUE THREAD

**Issue by lylong93** [vuejs/vue#11930]
### Version
2.6.11

### Reproduction link
[https://github.com/lylong93/SSR-bulid-bug](https://github.com/lylong93/SSR-bulid-bug)

### Steps to reproduce
create vue-srr project  use 'vue-server-renderer/server-plugin' module build ,than run this server

### What is expected?
the server is correct run

### What is actually happening?
 throw error "Cannot read property 'file' of undefined"，
 i found the build create 'vue-ssr-client-manifest.json' is correct，but 'initial' is a empty array,  wirte the some value as 'async'，the server is ok

**Comment by lylong93** [comment]
before run this  project must look the #11718  , try fix server-plugin.js about 'entryName' problem

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is too much for a reproduction, it has too many dependencies and the error could come from so many places. Maybe https://ssr.vuejs.org/ or the chat helps you out

**Comment by lylong93** [comment]
thanks, I've tried some ways to fix it
