### ISSUE TITLE
v-for adding a range is not working anymore. how to do this?

### ISSUE THREAD

**Issue by BroJenuel** [vuejs/vue#11935]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/e3nyu4go/4/](https://jsfiddle.net/e3nyu4go/4/)

### Steps to reproduce
```vue
<template v-for="year in (2015, 2021)">
     <options>{{year}}</options>
</template>
```

### What is expected?
it should output options from 2015 to 2021.

### What is actually happening?
the loop started at 1 and ends in 2021

---
This is really helpful especially when ranging years, we don't have to put it in an array... especially if I want to get the year 2015 to the current year like this `v-for=" year in (2015, parseInt((new Date()).getFullYear()))"`

**Comment by posva** [comment]
Vue supports `v-for="n in 10"` syntax for repetition, so you can do:

```vue
<template v-for="year in new Date().getFullYear() - 2015">
      <option :value="2015 + year" :key="2015 + year">{{year + 2015}}</option>
    </template>
```

But this will repeat so you should create the array in the component.

There is no syntax for ranges in JS so Vue won't add more syntaxes for it
