### ISSUE TITLE
keep-alive is not keeping alive?

### ISSUE THREAD

**Issue by lzhoucs** [vuejs/vue#11936]
### Version
2.6.11

### Reproduction link
[https://codepen.io/lzhoucs/pen/oNYPXop](https://codepen.io/lzhoucs/pen/oNYPXop)

### Steps to reproduce
* Go to https://codepen.io/lzhoucs/pen/oNYPXop
* Click through 3 buttons to show 3 different foo components
* Observe in the console log that shows foo components are being destroyed

### What is expected?
components wrapped with `<keep-alive>` should not be destroyed

### What is actually happening?
components wrapped with `<keep-alive>` are destroyed

---
the foo components are intentionally wrapped inside `<foo-wrapper>` which conditionally wraps the default slot with a div which I believe is why it is not behaving the way I expected

**Comment by posva** [comment]
This is working as intended because it's as if you were doing the `v-if` on the `keep-alive`, completely destroying it. In this scenario you need to wrap the foo-wrapper with keep-alive

**Comment by lzhoucs** [comment]
wrapping the foo-wrapper with keep-alive doesn't seem to work as the foos are still being destroyed though. Do you have a modified working example please?
