### ISSUE TITLE
Vue js 2 memory heap jumping from 168MB to over 2GB

### ISSUE THREAD

**Issue by vadimt2** [vuejs/vue#11931]
### Version
2.6.11

### Reproduction link
* I can't provide full baseUrl path to API
[https://jsfiddle.net/gmvs6uc0/1/](https://jsfiddle.net/gmvs6uc0/1/)

### Steps to reproduce
```
this.structureTree = data; // when i use vuex i have the same issue, In this case i'm not using vuex.
```
```
<template>
  <div id="app">
     <button @click="showData">View data</button>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "App",
  anyData: [],
  data() {
    return {
    structureTree: []
    };
  },
  methods: {
    showData() {
      console.log("showData", this.anyData);
    }
  },
  created() {
    let httpClient = axios.create({ baseURL: "https://localhost:44384" + "/" });

    let headers = {headers: {
    'Authorization': `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXryyj5nL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImp0aSI6IjY3MDA1NTAxLTlkNjctNGRjMy1iM2M1LWFjNWNlZjI3YTRmYiIsImV4cCI6IjE2MTcyOTQ4MDciLCJuYmYiOiIxNjE0NzAyODA3tyhhXNzIjoiSldUIiwiYXVkIjoiSldUIn0.O6LR24MD7xFqnpxJjSJF6XQ9u8A1TL71-fR21rMqhL4` 
  }};

        httpClient.get("/structures/GetStructureItemTree?structureId=1020 ", headers).then(({data}) => {
          debugger
          // this.anyData = data;
          this.structureTree = data;
          console.log(data, "Data")
      }).catch(err => {
        debugger
                  console.log(err, "err")
      });
</script>
```

### What is expected?
Vue js 2:
When i'm making an API request i'm getting data with 168mb size.
Inside then when it executes this line:
this.structureTree = data;
Vue js 2 memory heap jumping from 168MB to over 2GB
And if i will comment this line and uncomment 
this.anyData = data;
then the memory heap will 168mb.

Vue js 3:
It doesn't matter if the array verbal inside or outside of data
it will be 168mb exactly how it should be.
This issue is only in Vue js 2.

### What is actually happening?
Heap should be 168mb and not 2GB.
like in this.anyData or vue js 3.

---
* I can't provide full baseUrl path to API
* Vue js 2 a brand new vue create project with axios.
https://stackoverflow.com/questions/66454042/vue-js-2-memory-heap-jumping-from-168mb-to-over-2gb

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by vadimt2** [comment]
I think this is a vue js 2 bug because it does working on vue js 3 like it should be.
