### ISSUE TITLE
Called without include/exclude when a kept-alive component is deactivated

### ISSUE THREAD

**Issue by codesyofo** [vuejs/vue#11934]
### What problem does this feature solve?

Scene:
There are two lists A and B in the menu O.

List A and List B should be cached, A and B are the same components, and key is used to distinguish caching.

List A goes to detail A, detail A does not need to be cached, list A and detail A use include/exclude to match(exclude: detail A component name).

From detail A to list B, now detail A and list A are cached, and detail A that do not need to be cached are cached together.

场景：
O菜单中有A、B两个列表，
A、B列表要缓存，A、B相同组件，用key区别缓存
A列表进入a详情，a详情不需要缓存，A列表、a详情使用include、exclude匹配过滤
此时从a详情进入B列表，A列表中的全被缓存了，把不需要缓存的a详情页一起缓存了

### What does the proposed API look like?
Called with include/exclude when a kept-alive component is deactivated

被 keep-alive 缓存的组件停用时调用匹配include/exclude

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by codesyofo** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

I think it's a bug not a question. without called include/exclude when a kept-alive component is deactivated.

**Comment by posva** [comment]
Read https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro
