### ISSUE TITLE
Mixin without template/render fn results in warning(s)

### ISSUE THREAD

**Issue by ndresx** [vuejs/vue#11944]
### Version
2.6.11

### Reproduction link
[https://github.com/ndresx/vuejs-mixin-no-template-warn](https://github.com/ndresx/vuejs-mixin-no-template-warn)

### Steps to reproduce
1. `npm run serve` (app starts normally without any warnings being shown)
2. Change `Mixin.vue` (e.g., change the console.log message)
3. Warning gets shown `"[Vue warn]: Failed to mount component: template or render function not defined."` on every change

### What is expected?
No warnings about failed mounting attempts as it seems to be workings without a template or render function. Also, the mixin-related examples in the official documentation don't use templates, so there shouldn't be a warning like this at all. Otherwise, it should be already shown when the app gets bootstrapped and not only on subsequent file changes.

### What is actually happening?
I'm not sure, but this behavior and warning logs seem to be inconsistent with this error message. It should be either shown all the time or never.

_Edit: Renaming the mixin's file extension to `.js/.ts` (instead of `.vue`) has solved the issue, and the warning doesn't get shown anymore. However, it's still confusing, in my opinion, that it doesn't get logged right away and only after a change since the mixin's functionality doesn't seem to be directly affected by this._

_It might be worth also adding a note about this to the documentation unless I have missed it._

**Comment by posva** [comment]
A mixin cannot have a template/render function nor have any style and therefore should not be a `.vue` file
