### ISSUE TITLE
Official Vue alternative for Deno

### ISSUE THREAD

**Issue by Dania99dev** [vuejs/vue#11940]
### What problem does this feature solve?
It's a relatively new project but It would be very nice to have a simple official alternative for Vue so people can contribute.
also results in a cleaner environment with no node_modules and stuff

### What does the proposed API look like?
```
|- public
|- src
```
(no node_modules)

**Comment by posva** [comment]
We currently don't have the bandwidth for this but it would be great if there was a community solution. To discuss this with other people interested in it, please open a discussion on the vuejs/rfcs repo
