### ISSUE TITLE
Passing dynamic values into subcomponents will not render correctly!

### ISSUE THREAD

**Issue by VitaminCtea** [vuejs/vue#11950]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/fervent-austin-9zre8?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/fervent-austin-9zre8?file=/src/components/HelloWorld.vue)

### Steps to reproduce
I tried to write it according to the official document example, but when the dynamic attribute value is passed in, it will be rendered to the tag attribute of the subcomponent. I don't know what's wrong?

This is the last example of the rendering list in the official document. The code is as follows:

@/components/HelloWorld.vue

```
<templete>
    <div class="hello">
        <form @submit.prevent="addNewTodo">
            <label for="new-todo">Add a todo</label>
            <input v-model="newTodoText" id="new-todo" placeholder="E.g. Feed the cat" />
            <button>Add</button>
        </form>
        <ul>
            <li is="todo-items" 
                 v-for="(todo, index) in todos" 
                 :key="todo.id" 
                 :text="todo.text" 
                 @remove="todos.splice(index, 1)" />
        </ul>
    </hello>
</templete>

<script lang="ts">
    import { Component, Model, Prop, Vue, Watch } from 'vue-property-decorator'
    import TodoItems from '@/components/TodoItems.vue'

    @Component({ components: { TodoItems }})
    export default class HelloWorld extends Vue {
        public newTodoText = ''
        public todos: { id: number; text: string }[] = [ 
            { id: 1, text: 'Daniel Keman: measuring the world' },
            { id: 2, text: 'White Deer Plain' },
            { id: 3, text: 'Worry free grocery store' }
        ]
    }
    
    addNewTodo() {
        if (!this.newTodoText) return
        this.todos.push({
            id: this.todos[this.todos.length - 1].id   1,
            text: this.newTodoText
        })
        this.newTodoText = ''
    }
</script>

```

@/components/TodoItems.vue

```
<template>
    <li>
        {{ text }}
        <button @click="$emit('remove')">Remove</button>
    </li>
</template>

<script lang="ts">
import { Prop, Vue } from 'vue-property-decorator'

export default class DoSomeThing extends Vue {
    @Prop({ type: String, default: '' }) public readonly text!: string
}
</script>

```

I review the DOM element and the rendering results are:

```
<ul data-v-469af010="">
    <li data-v-469af010="" text="Daniel Keman: measuring the world">  
        <button>Remove</button>
    </li>
    <li data-v-469af010="" text="White Deer Plain">  
         <button>Remove</button>
    </li>
    <li data-v-469af010="" text="Worry free grocery store">  
         <button>Remove</button>
    </li>
</ul>

```

As you can see, the is property will render the todoitems component correctly, but the incoming text property will display correctly in the Li tag, not in the text! 

And the following error occurred in the console: 

> Property or method "text" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties. found in
      ---> <TodoItems> at src/components/TodoItems.vue
       <HelloWorld> at src/components/HelloWorld.vue
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>

When I test passing in attributes to other child components in other parent components, it will render correctly! But in this case, I don't know why?

Miraculously, there is no problem in using JS. Please refer to the sandbox address I created

When writing with TS, it is not expected.

### What is expected?
The text attribute passed in can be correctly rendered under the Li tag

### What is actually happening?
In this example, the rendering is not correct, even if the component is used instead of the is attribute, the rendering result is the same

---
Looking forward to the solution

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If anything you should open an issue in vue-property-decorator. Maybe you need to check the `inheritAttrs` property in components.

**Comment by lk77** [comment]
hello,

an @Component() is missing
