### ISSUE TITLE
How get V-mode modifier type in source level

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue#11959]
### Version
2.6.11

### Reproduction link
[https://github.com/kumaresan-subramani/Vue-modifier](https://github.com/kumaresan-subramani/Vue-modifier)

### Steps to reproduce
1. clone below sample - https://github.com/kumaresan-subramani/Vue-modifier
2. Give `npm i` and `npm run dev`
3. sample gets loaded in browser
4. chnage vaues in both text box
5 `.lazy` modifier works fine for html etxt box but not working fine for our control

### What is expected?
Modifier need to work propery

### What is actually happening?
modifier functionality need to work properly for that i need to know modifier type

**Comment by kumaresan-subramani** [comment]
HI @sodatea ,

Any suggesiotn for this?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by kumaresan-subramani** [comment]
https://learnvue.co/2021/01/everything-you-need-to-know-about-vue-v-model/#What_is_Vue_v-model
