### ISSUE TITLE
Use CustomEvent instead of document.createEvent

### ISSUE THREAD

**Issue by answershuto** [vuejs/vue#11953]
### What problem does this feature solve?
Document.createEvent has been deprecated, it is recommended to use CustomEvent instead.

https://developer.mozilla.org/zh-CN/docs/Web/API/Document/createEvent

https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/directives/model.js#L141

**Comment by posva** [comment]
It's not supported by IE
