### ISSUE TITLE
v-text evaluates HTML entities hard-coded strings

### ISSUE THREAD

**Issue by vilbergs** [vuejs/vue#11969]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/m297ke3y/9/](https://jsfiddle.net/m297ke3y/9/)

### Steps to reproduce
1. Add a v-text directive to any tag
2. Hardcode a string into it (i.e `'&lt;h1&gt;This &amp; That&lt;/h1&gt;'`)

### What is expected?
HTML entities should not be evaluated in the hard-coded string, they should be written out as they are.

### What is actually happening?
HTML entities in the string are converted to their equivalent symbols.

---
I'm not sure if this is intended behaviour, but it seems odd that the two behaviours in my jsfiddle should differ.

**Comment by jacekkarczmarczyk** [comment]
> I'm not sure if this is intended behaviour

it's intended, html entities are replaced by the browser

![image](https://user-images.githubusercontent.com/15625235/111616645-70d07380-87e2-11eb-9373-5eafd49ba164.png)
 
https://jsfiddle.net/j936ezqh/

**Comment by vilbergs** [comment]
> > I'm not sure if this is intended behaviour
> 
> it's intended, html entities are replaced by the browser
> 
> [image]
> 
> https://jsfiddle.net/j936ezqh/

Hey @jacekkarczmarczyk! Thanks for the reply!

It makes that the browser renders the entities. I'm still a bit unsure as to why the raw string is evaluated differently from the variable in the example. Do you have any insights there?

**Comment by posva** [comment]
Closing as this is how the browser works. Characters are escaped differently in JS and in HTML Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
