### ISSUE TITLE
lack of git commit msg suggestion

### ISSUE THREAD

**Issue by CroMarmot** [vuejs/vue#11966]
### What problem does this feature solve?

`scripts/verify-commit-msg.js` & `.github/COMMIT_CONVENTION.md` are hard to use.

### What does the proposed API look like?

```
touch file
git add file
git commit -m "hey"

# display all avaliable git commit msg
```

**Comment by posva** [comment]
Thank you but we like our workflow

**Comment by CroMarmot** [comment]
So your workflow has already lead to inconsistent documentation and code, and no one knows that you can use `build: ` unless you read the code

check with commit `e98d12d232af49b8e127375b6237013e01b77dda` (Mar 8 2018), modified both file it's ok.

commit `a08feed8c410b89fa049fdbd6b9459e2d858e912`(Mar 9 2018) only `scripts/verify-commit-msg.js` changed.

After then, there are more than 100 commit submited with `build: `, check with `git log --oneline  | grep build`.

Your document says

> This is adapted from [Angular's commit convention](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

Their repo prompts users like this: `✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]`
