### ISSUE TITLE
Override of the renderStyle and renderResourcehints during manual asset injection

### ISSUE THREAD

**Issue by sns45** [vuejs/vue#11960]
### Version
2.6.11

### Reproduction link
[https://github.com/sns45/esm-issue](https://github.com/sns45/esm-issue)

### Steps to reproduce
Create SSR page using:
https://ssr.vuejs.org/guide/build-config.html#manual-asset-injection

or clone the repro:
npm install
npm run build
npm run start

### What is expected?
We should be allowed to override these `renderResourceHints()` and `renderStyles()` functions which is used in `index.template.html`.

### What is actually happening?
Cannot override or customize `renderResourceHints()` and `renderStyles()` functions. 

---
I am looking to override `renderResourceHints()` and `renderStyles()` functions so I can inline one of the critical css in the HTML using `<style></style>` tag. From `asyncData()`, I should be allowed to fine tune what resources should be preloaded or not preloaded based on the store data.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
