### ISSUE TITLE
Inline style grid-column-start/grid-column-end rounds any value greater than 1000 to 1000 (1021 will be 1000)

### ISSUE THREAD

**Issue by yevheniUnostella** [vuejs/vue#11973]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/y7af5dsu/](https://jsfiddle.net/y7af5dsu/)

### Steps to reproduce
1. Set inline style="grid-column-end: 1021".
2. Inspect element with inline style, will be style="grid-column-end: 1000;".

### What is expected?
style="grid-column-end: 1021;"

### What is actually happening?
style="grid-column-end: 1000;"

**Comment by posva** [comment]
This seems to be just the browser behavior: it happens without Vue `element.style = 'grid-column-end: 1021'`
