### ISSUE TITLE
在使用vue2.0 element-ui和Dplayer第三方视频插件的时候发生重大bug

### ISSUE THREAD

**Issue by jiawenguang** [vuejs/vue#11979]
### Version
2.6.11

### Reproduction link
[http://www.kehuowang.com/coursedetails?itemid=326705918479695872](http://www.kehuowang.com/coursedetails?itemid=326705918479695872)

### Steps to reproduce
通过列表页进入详情页，在详情页会进行Dplayer实例化new操作，来进行视频播放，造成全局的input v-mode事件，以及所有原生事件失效，无法输入，无法触发chang事件，input事件，刚开始以为ElementUI的input组件问题，但当我们尝试原生的input写法，发现还是出现那种无法输入的情况。

### What is expected?
我们期望进入这个页面技能播放视频也能，唤起我们的input输入内容

### What is actually happening?
进入页面播放了视频，造成input失效无法使用，只有在不实例化Dplayer组件的情况下input可以使用。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
