### ISSUE TITLE
Please add filters inVuejs 3

### ISSUE THREAD

**Issue by ayoubkhan558** [vuejs/vue#11971]
### What problem does this feature solve?
Filters arevery good to format text quickly

### What does the proposed API look like?
All other JavaScript frameworks (Angular reactjs) provide these kinds of filters. You have removed filter from Vuejs 3. I don't think this is a good idea.  I does not take much coding. But these are very useful.

**Comment by posva** [comment]
This was extensively discussed in the rfcs repository when discussing breaking changes.
