### ISSUE TITLE
VUE-COMPOSITION-API: why does ref not feel reactive on contenteditable, especially on this case

### ISSUE THREAD

**Issue by handhikadj** [vuejs/vue#11970]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/zealous-ardinghelli-b05ph](https://codesandbox.io/s/zealous-ardinghelli-b05ph)

### Steps to reproduce
1. Go to: https://codesandbox.io/s/zealous-ardinghelli-b05ph
2. Place cursor to text
3. Click the “INSERT IMAGE BETWEEN TEXT” button
4. Pay attention to the shown ref() below the button

### What is expected?
the ref() can “catch up” the inserted image to the text.

### What is actually happening?
the ref() can’t “catch up” the inserted image to the text.

---
Been asking on this: https://stackoverflow.com/questions/66708115/vue-composition-api-why-does-ref-not-feel-reactive-on-contenteditable and this: https://forum.vuejs.org/t/vue-composition-api-why-does-ref-not-feel-reactive-on-contenteditable/113409
but no answer.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The problem could be related to the library vue content editable you are using
