### ISSUE TITLE
I need to use both Vue2 and Vue3, Webpack how to alias configure

### ISSUE THREAD

**Issue by BlackCubeNo99** [vuejs/vue#11974]
### Version
2.6.11 & 3.0.7

### Reproduction link
[https://jsfiddle.net/1x2pL8em/1/](https://jsfiddle.net/1x2pL8em/1/)

### Steps to reproduce
I installed the dependencies of Vue2 & Vue3

Vue2: vue-loader 15.9.6   vue-template-compiler 2.6.12
Vue3: vue-loader 16.1.2   @vue/compiler-sfc 3.0.7

Webpack how to configure

### What is expected?
I have different entry, project A use Vue2, project B use Vue3

### What is actually happening?
Can not be used at the same time

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
