### ISSUE TITLE
Number Type Warnings in IE11, caused by Core JS

### ISSUE THREAD

**Issue by OktarinTentakel** [vuejs/vue#11986]
### Version
2.6.12

### Reproduction link
[https://4pujg.csb.app/](https://4pujg.csb.app/)
[https://vue-vfurgs.stackblitz.io]

### Steps to reproduce
DISCLAIMER: CodeSandbox as well as StackBlitz do not seem to support IE11, which makes it _really_ difficult to provide a link here and fulfill you requirements without me setting up a complete project for you. The gist of both examples: add ie11 to browserslist, let corejs add new es6 number constructor in ie11, see all number validations fail....

DESCRIPTION: Using Webpack 4 to transpile a Vue (2.6.12 in this case) bundle to ES5 like this:

{
	test : /\.js$/,
	include : config.JS_INCLUDES.concat(config.VUE_INCLUDES),
	use : [
		{
			loader : 'babel-loader',
			options : {
				plugins : ['@babel/plugin-transform-runtime'],
				presets : [
					['@babel/preset-env', {
						corejs : 3,
						targets : packageConfig.browserslist,
						useBuiltIns : 'usage'
					}]
				],
				cacheDirectory : true
			}
		}
	]
}

where browserslist includes IE11, results in a bundle in which the Core JS package adds "es.number.constructor", which replaces the constructor for Number in window/global to add ES6 features to the prototype (see here: https://caniuse.com/es6-number and https://github.com/zloirock/core-js/blob/v3.9.1/packages/core-js/modules/es.number.constructor.js#L79).

This causes all Number type prop validations in IE11 to fail, because the constructor is not the native one any more and the validation type handling fails to match a provided number for a property to the constructor installed by core js.

### What is expected?
Vue property validation can handle this case and does not rely on the constructor having a string-parsable name (or handle this special, but common case).

### What is actually happening?
All properties being numbers throw warnings, because the comparison of Number instances being handed to the components do not match the expected form of the replaced constructor.

---
You can circumvent this problem by adding

exclude : ['es.number.constructor']

to the babel preset, but this might break other things and libraries like vue-multiselect have this exact polyfill in their dist code, so this will not cover all cases.

**Comment by OktarinTentakel** [comment]
This function fails with a replaced constructor:

`var simpleCheckRE = /^(String|Number|Boolean|Function|Symbol)$/;

function assertType (value, type) {
  var valid;
  var expectedType = getType(type);
  if (simpleCheckRE.test(expectedType)) {
    var t = typeof value;
    valid = t === expectedType.toLowerCase();
    // for primitive wrapper objects
    if (!valid && t === 'object') {
      valid = value instanceof type;
    }
  } else if (expectedType === 'Object') {
    valid = isPlainObject(value);
  } else if (expectedType === 'Array') {
    valid = Array.isArray(value);
  } else {
    valid = value instanceof type;
  }
  return {
    valid: valid,
    expectedType: expectedType
  }
}`

The check falls through to the else branch, but even instanceof is false in this case.

This is the replacement code by corejs:
https://github.com/zloirock/core-js/blob/v3.9.1/packages/core-js/modules/es.number.constructor.js#L55
Where "NumberWrapper" is the new constructor causing the problem here.

**Comment by posva** [comment]
Replacing the whole `Number` object is in general a bad idea. If anything it should be monkey patched in older browsers. Closing as this is not a Vue issue per see but rather a polyfill misconfiguration. However, if you have a reasonable fix proposal, we are open to a PR!

**Comment by OktarinTentakel** [comment]
@posva I understand completely that this is not _really_ your problem, but this will happen to all people transpiling to ie11 by default in the future, so I guess this is worth handling, since everybody uses corejs and no one will see or understand the problem. Maybe at least a hint in the documentation somewhere handling ES5 targets?

**Comment by OktarinTentakel** [comment]
@posva I investigated a little more and came to the conclusion, that this is actually only a problem if there is more than one script on a page including the replacement, since in that case the second script will not find the native constructor anymore and work with a "wrong" native constructor and prototype. If the replacement is globally included only once, this works as expected.

So, you are right, in the end this is indeed a corejs problem, not detecting their own polyfills properly on a second run. :|

So closing this was indeed the right call.
