### ISSUE TITLE
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. 

### ISSUE THREAD

**Issue by IslamSakrak** [vuejs/vue#11983]
### Version
2.6.10

### Reproduction link
[https://pastebin.com/LaYt4H9D](https://pastebin.com/LaYt4H9D)

### Steps to reproduce
all my code that i think produces the error 
https://pastebin.com/LaYt4H9D

### What is expected?
Expected the login and the sign up component view

### What is actually happening?
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug.  http://localhost:52051/node_modules/.vite/common/vue.runtime.esm-bundler.32bf0c4e.js (vue.runtime.esm-bundler.32bf0c4e.js)
 at <Login onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

---
i was just replacing the $event with some random message and I got this error

**Comment by LinusBorg** [comment]
Hello @IslamSakrak,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an runnable example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
