### ISSUE TITLE
contribution vue form Validation Library

### ISSUE THREAD

**Issue by dev-zl** [vuejs/vue#11981]
### What problem does this feature solve?
my think vue.js  ecology  lack  form Validation Library
although exist  plenty of  form Validation Library ,yet  None of them are particularly good.

They can only do simple validation Complex and not for vue components support custom validation  fail style.

my contribution is VccValidate
docs (https://dev-zl.github.io/VccValidate/#/)
npm (https://www.npmjs.com/package/vcc-validate)

### What does the proposed API look like?
docs (https://dev-zl.github.io/VccValidate/#/)

**Comment by posva** [comment]
That's great 👍 
You could propose it to https://github.com/vuejs/awesome-vue
