### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by Guervyl** [vuejs/vue#11994]
### Version
3

### Reproduction link
[https://github.com/Guervyl/vuejs3-Failed-to-resolve-component](https://github.com/Guervyl/vuejs3-Failed-to-resolve-component)

### Steps to reproduce
Clone the repository, run the project and look at the JS console.

### What is expected?
I expected to see the inner component.

### What is actually happening?
Vue throw a warning "Failed to resolve component". And it does not show the inner component.

**Comment by Guervyl** [comment]
The problem is in the component `ApiBinding` line 8.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. This is a question regarding vue-class-component usage for Vue 3. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Also, the repository for Vue 3 is at https://github.com/vuejs/vue-next
