### ISSUE TITLE
Vue SSR performing bad over time

### ISSUE THREAD

**Issue by manash-ranjan-khamari** [vuejs/vue#11993]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
I am using Vue SSR for a decent sized application. The problem is the server response time(TTFB) or in this case time taken for the renderToString method is growing over time. Once I restart the server, the values comes back to normal level & then it continues again in an upward trend.

![image](https://user-images.githubusercontent.com/69390751/113185728-6f885780-9274-11eb-9737-ef75f164a230.png)

### What is expected?
Given load, I can understand that the performance could go bad, but it should come back to normal level once done

### What is actually happening?
The time taken to render should not increase linearly over time. 

---
There is not much CPU usage I can see & I tried taking CPU profile snapshot as well, but couldn't able to figure out what would be causing this.

I have been stuck at this problem for days now. Tried various things, nothing is helping out. Please help!!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only, not to ask for support. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
If you manage to provide a boiled down reproduction, please open a new issue. https://ssr.vuejs.org/ could help

**Comment by dimicdragan** [comment]
Try moving to Nuxt...
