### ISSUE TITLE
GitHub Release 2.6.12 unexciting

### ISSUE THREAD

**Issue by P0ppoff** [vuejs/vue#12009]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
* Create an issue with https://new-issue.vuejs.org/?repo=vuejs/vue, you can't select version `2.6.12`
<img width="445" alt="Capture d’écran 2021-04-08 à 20 04 12" src="https://user-images.githubusercontent.com/10043818/114076416-ecd04f80-98a6-11eb-8692-a785478ebe7e.png">
* Go to https://www.npmjs.com/package/vue and last version displayed: `2.6.12`, go to https://github.com/vuejs/vue last version is `2.6.11`
<img width="380" alt="Capture d’écran 2021-04-08 à 20 03 06" src="https://user-images.githubusercontent.com/10043818/114076449-f6f24e00-98a6-11eb-83ea-7a6e7a736e7b.png">
<img width="319" alt="Capture d’écran 2021-04-08 à 20 03 29" src="https://user-images.githubusercontent.com/10043818/114076440-f3f75d80-98a6-11eb-9359-2db9cb5498d8.png">

### What is expected?
I expect to see the changelog for version 2.6.12 on github page https://github.com/vuejs/vue/releases

### What is actually happening?
Git repo has tag 2.6.12 with no changelog associate
<img width="388" alt="Capture d’écran 2021-04-08 à 20 14 58" src="https://user-images.githubusercontent.com/10043818/114076583-1a1cfd80-98a7-11eb-91d9-98fbf856934b.png">

**Comment by posva** [comment]
we will do another releae on v2.6.13 😉
