### ISSUE TITLE
Failed to resolve SVG textpath tag

### ISSUE THREAD

**Issue by davidglezz** [vuejs/vue#12005]
### Version
2.6.11

(v2 and v3)

### Reproduction link
[https://codesandbox.io/s/vue-issue-nccy1?file=/src/App.vue:161-169](https://codesandbox.io/s/vue-issue-nccy1?file=/src/App.vue:161-169)

### Steps to reproduce
Try to render textpath element. Like in the demo.

### What is expected?
To render text

### What is actually happening?
Text is not rendered

![image](https://user-images.githubusercontent.com/194784/113586096-60ffbe80-962d-11eb-89e6-11ec31b65c54.png)

---
The same behaviour in v3, but I get a nice hint: Failed to resolve component: textpath

V3 repro:
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxzdmc+XG4gICAgPHBhdGhcbiAgICAgIGlkPVwibXlQYXRoXCJcbiAgICAgIGZpbGw9XCJub25lXCJcbiAgICAgIHN0cm9rZT1cImdyYXlcIlxuICAgICAgZD1cIk0gNzUsIDEyNSBhIDUwLDUwIDAgMSwxIC4wMSwwXCJcbiAgICAvPlxuICAgIDx0ZXh0IGZpbGw9XCJyZWRcIj5cbiAgICAgIDx0ZXh0cGF0aCBocmVmPVwiI215UGF0aFwiPi0gLSAtIFNPTUUgVEVYVCAtIC0gLTwvdGV4dHBhdGg+XG4gICAgPC90ZXh0PlxuICA8L3N2Zz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5cbjwvc2NyaXB0PiJ9

**Comment by davidglezz** [comment]
Solved:

use `textPath` instead `textpath`. The P must be capitalized.

**Comment by posva** [comment]
Somehow the browser seems to automatically fix it when parsing the HTML but yeah, yuo need `textPath`
