### ISSUE TITLE
vue在vscode中使用typescript开发如何支持链式判断？

### ISSUE THREAD

**Issue by keyiis** [vuejs/vue#12006]
### Version
2.6.11

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI XG5jb25zdCBtc2cgPSB7YTp7Yjpbe2M6MX1dfX07XG4gIGNvbnNvbGUubG9nKG1zZz8uYT8uYj8uWzBdPy5jKTtcbjwvc2NyaXB0PiJ9](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgbGFuZz1cInRzXCI XG5jb25zdCBtc2cgPSB7YTp7Yjpbe2M6MX1dfX07XG4gIGNvbnNvbGUubG9nKG1zZz8uYT8uYj8uWzBdPy5jKTtcbjwvc2NyaXB0PiJ9)

### Steps to reproduce
在vue文件的<script lang="ts">标签中使用链式判断语法
 `a?.b?.c`
编译可以通过，但是vscode提示语法错误，这个有解决方案吗？

### What is expected?
不要提示错误

### What is actually happening?
提示错误
![image](https://user-images.githubusercontent.com/7766085/113805983-1a78a400-9794-11eb-9c69-98e3332c35f3.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Note issues must be opened in English so more people can help
