### ISSUE TITLE
当我使用v-bind=“$attrs”传递symbol会报错

### ISSUE THREAD

**Issue by nanachiOwQ** [vuejs/vue#12019]
### Version
2.6.11

### Reproduction link
[https://codepen.io/dracarys26/pen/gOgdWwY?editors=1111](https://codepen.io/dracarys26/pen/gOgdWwY?editors=1111)

### Steps to reproduce
使用v-bind=“$attrs”传递symbol会报错 如果写一个prop再往下传递则不会 

### What is expected?
使用v-bind=“$attrs”不报错

### What is actually happening?
Uncaught TypeError: Cannot convert a Symbol value to a string

**Comment by posva** [comment]
You should do

```js
inheritAttrs: false,
  template:`<component-b v-bind="$props" />`,
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by nanachiOwQ** [comment]
> You should do
> 
> ```js
> inheritAttrs: false,
>   template:`<component-b v-bind="$props" />`,
> ```
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

thanks！
