### ISSUE TITLE
CSS minification error

### ISSUE THREAD

**Issue by Oluwa-Seun** [vuejs/vue#12012]
### Version
2.6.11

### Reproduction link
[https://github.com/Oluwa-Seun/weatherapp](https://github.com/Oluwa-Seun/weatherapp)

### Steps to reproduce
no steps to reproduce

### What is expected?
build complete

### What is actually happening?
 Cannot read property 'length' of undefined. File: css/app.f76b1c79.css

**Comment by Oluwa-Seun** [comment]
![Screenshot 2021-04-12 at 14 58 52](https://user-images.githubusercontent.com/61301594/114406658-9eb99580-9b9f-11eb-9b1b-3628359a4f72.png)
![Screenshot 2021-04-12 at 14 59 42](https://user-images.githubusercontent.com/61301594/114406806-bbee6400-9b9f-11eb-9c05-50a8fcd6b275.png)



im new to vuejs so im still trying to understand its enviroment.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
