### ISSUE TITLE
Move to vuejs organization

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#1201]
This is mostly logistics. Please comment with anything I am missing.

- [x] Links in docs
- [x] Links in README
- [x] Links in package.json
- [x] Links in source code comments
- [x] Links in examples
- [x] Links on forum.vuejs.org
- [x] Package manager: Bower
- [x] CDN: jsdelivr
- [x] CDN: cdnjs
- [x] Gitter room

**Comment by OEvgeny** [comment]
Links on vuejs.org. Including star and "Source on GitHub" buttons.

**Comment by nervgh** [comment]
> Package manager: Bower

vs

> **Package Ready**
> Install via NPM, Bower or Duo - leverage your favorite eco system!
> http://vuejs.org/

=)

**Comment by JosephSilber** [comment]
When is this happening?

**Comment by yyx990803** [comment]
@JosephSilber before the official 1.0 release, likely this week or next.

**Comment by suhaotian** [comment]
CDN: http://cdn.bootcss.com/

**Comment by matteocontrini** [comment]
@yyx990803 is the process actually a "move" with all the issues or will you create another repository?

**Comment by yyx990803** [comment]
@matteocontrini it's a move.

**Comment by yyx990803** [comment]
Done.

**Comment by azamat-sharapov** [comment]
:clap:

**Comment by kazupon** [comment]
🎉

**Comment by zjzcn** [comment]
:+1:

**Comment by fnlctrl** [comment]
:+1::+1::+1:

**Comment by simplesmiler** [comment]
:sparkles:
