### ISSUE TITLE
当{{}}和div不在一行的时候，渲染到页面上就会在文字前后各增加空格

### ISSUE THREAD

**Issue by Tsite2007** [vuejs/vue#12013]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/affectionate-chatelet-j9sfm?file=/src/App.vue](https://codesandbox.io/s/affectionate-chatelet-j9sfm?file=/src/App.vue)

### Steps to reproduce
这样写显示正常：
`<div>{{selectedLan}}</div>`
这样写就会导致文字前后都增加了一个空格
```
<div>
      {{selectedLan}}
</div>
```

### What is expected?
期望不带空格

### What is actually happening?
现在有空格

---
这样写显示正常：
`<div>{{selectedLan}}</div>`
这样写就会导致文字前后都增加了一个空格
```
<div>
      {{selectedLan}}
</div>
```

**Comment by Tsite2007** [comment]
codesandbox上没有很好的显示出来

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
