### ISSUE TITLE
createElement不应该删除传入的attrs属性，这会污染输入源

### ISSUE THREAD

**Issue by laydll** [vuejs/vue#12024]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/embed/determined-wind-bqrej?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/determined-wind-bqrej?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Vue.component('test_base', {
render(createElement) {
return createElement('p', null, 'test base!'   this.multiple);
},
props: {
multiple: false,
collapseTags: true
}
});

Vue.component('testnode', {
render(createElement) {
window.testdata = {
attrs: {
maxLength: 2,
className: 1,
multiple: true,
collapseTags: true
}
};
return createElement('test_base',
window.testdata,
'hello test!'
);
}
});

// console.log(window.testdata)时，attrs只有maxLength和className属性

### What is expected?
createElement函数不污染输入源，保留输入源原本的值

### What is actually happening?
ttrs属性被删除

---
在使用schema方式，通过js对象生成组件时，配置中attrs属性被删除（当属性值在调用组件的props中声明时），导致配置本身内容被修改，二次渲染时缺失属性

**Comment by posva** [comment]
You are not supposed to share the object passed to _createElement_ or use it outside.

**Comment by woshiguabi** [comment]
> You are not supposed to share the object passed to _createElement_ or use it outside.

https://codesandbox.io/s/optimistic-architecture-vrdvu?file=/src/App.vue

A simple codesandbox. I think this is a very common example when using render function.
