### ISSUE TITLE
Update the roadmap for vuejs

### ISSUE THREAD

**Issue by dennismetz** [vuejs/vue#12020]
### What problem does this feature solve?
The roadmap was last updated in 2019, maybe you can update it.
when would be the release of vue 2.7.x planned?

### What does the proposed API look like?
No api, just documentation.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You should find some information at https://blog.vuejs.org/
We plan a release of 2.6.13 very soon 1-2 weeks and we will give more visibility as soon as we can!
