### ISSUE TITLE
v-bind="$attrs" not override default attributes

### ISSUE THREAD

**Issue by VictorPullzz** [vuejs/vue#12036]
### Version
2.6.11

### Steps to reproduce
Just create nensted input:
Example component
```
<div>
      <input
         v-bind="$attrs"
         :value="value"
         type="text" 
      >
<div>
```

### What is expected?
type override default type

### What is actually happening?
If add add to this component attribute 
```
<input-component type="email" />
```
type="email" not override type="text" this really uncomfortable

**Comment by posva** [comment]
This is expected behavior for Vue 2 (see https://github.com/vuejs/vue/issues/7914). Please search existing issues before opening new ones and remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by KozakoPolako** [comment]
Try something like this: 
```
<div>
      <input
         v-bind="$attrs"
         :value="value"
         :type="'type' in $attrs ? $attrs.type : text" 
      />
<div>
```
