### ISSUE TITLE
Allow for <component> to be a conditional wrapper ie. only render children.

### ISSUE THREAD

**Issue by sugoidesune** [vuejs/vue#12033]
### What problem does this feature solve?
This use case is often called a **conditional wrapper** . 
There sometimes is a need to wrap an element in a link or other elements for styling.
But instead of making multiple similar components or providing a placeholder tag like `div` .
It would be great to be able to simply leave out the wrapping. This is important since sometimes a even simple 'div' wrapper can break styling as well/ would need extra consideration/ work/ moving parts.

### What does the proposed API look like?
I think the most clean and practical way for programmatic use would be to use the `is` prop.
Either by passing in a falsy value, or by passing in 'template', a tag that doesn't render in the html.

| Template  | Output |
| ------------- | ------------- |
| `<component :is="false"><span>Child</span></component>`      | `<span>Child</span>`  |
| OR |  |
| `<component :is="'template'"><span>Child</span></component>`      | `<span>Child</span>`  |

**Comment by posva** [comment]
This can be achieved through a render function. It should be a functional component in Vue 2 but can be anything in Vue 3.

If you think something like this is worth pursuing in vue core rather than an external library, you can open a PR on the vuejs/rfcs repository

**Comment by sugoidesune** [comment]
I tried and so have others but so far nobody has cracked it. All solutions are workarounds but none do it as cleanly.


What [i tried here:](https://forum.vuejs.org/t/conditionally-render-parent-element/9324/9) was:

```js
export default {
functional: true,

props: ['tag'],

render(h, context) {
const { children, props, data } = context

//  The wrapper element itself becomes the html element/component.
if (props.tag) {
  return h(props.tag, data, children)
} else {
// And if the tag is false than it only renders children
  return children
}
},
}
```

But I have difficulties making h(props.tag, data, children) as “transparent” as possible. And am getting errors when using components like <nuxt-link>

Any advice on what the best approach would be?

**Comment by Harrald** [comment]
I was suprised to find out this is not supported by Vue. We need this! 😄

**Comment by andrewsm80** [comment]
If something like this does eventually get implemented, I think it would make a lot more sense to use a directive, analogous to the `v-if` directive:

```
  <div v-wrap-if="someCondition">
    <span>
      This is a span that is sometimes wrapped up in a div.
    </span>
  </div>
```

**Comment by vincerubinetti** [comment]
Why was this closed, this is a good feature to have.

My (inconvenient) solution is to have a special `Wrapper.vue` component:

```vue
<template>
  <component :is="tag" v-if="wrap">
    <slot />
  </component>
  <slot v-else />
</template>

<script setup lang="ts">
interface Props {
  /** tag */
  tag: string;
  /** wrap */
  wrap: boolean;
}

defineProps<Props>();
</script>
```

Also, if this is built-in to vue, rather than a special `v-wrap-if` directive, perhaps it'd be better to use vue's already built-in fragment, `<template>`:

```vue
<template>
  <component :is="shouldWrap ? 'div' : 'template'">
     some content
  </component>
</template>
``` 

(The above doesn't currently work in Vue 3.

**Comment by robere2** [comment]
FYI, this has since been opened as an RFC: https://github.com/vuejs/rfcs/pull/449

**Comment by distor-sil3nt** [comment]
Is there any news on this? The conditional wrapper feature would be really useful and I'm wondering whether someone already found a solution for this. Either as a custom directive or over the `<compontent>`  tag.

**Comment by katerlouis** [comment]
Any status update? :)

**Comment by katerlouis** [comment]
I've said it somewhere else, but why not here again: 
I came up with a Vue 2 component to solve that use case

```vue
<script>
// inspired by a workaround for missing "optional wrapper" functionality in vue
// see: https://github.com/vuejs/rfcs/discussions/448#discussioncomment-5487435

export default {
  name: 'Fragment',

  render(h) {
    if (this.$slots && this.$slots.default) {
      return this.$slots.default;
    }

    return null;
  },
};
</script>
```

Usage:
```vue
<component
  :is="isLink ? 'a' : 'Fragment'"
  :href="someLinkComputed"
>
  I can even be plain text!
</component>
```

**Comment by janein** [comment]
> Why was this closed, this is a good feature to have.
> 
> My (annoying) solution is to have a special `Wrapper.vue` component:
> 
> ```
> <template>
>   <component :is="tag" v-if="wrap">
>     <slot />
>   </component>
>   <slot v-else />
> </template>
> 
> <script setup lang="ts">
> interface Props {
>   tag: string;
>   wrap: boolean;
> }
> 
> defineProps<Props>();
> </script>
> ```
> 
> Also, I'd lean towards OP's solution of using vue's existing fragment `<template>` tag, rather than implementing a new special `v-wrap-if` directive that people have to learn/remember.
> 
> ```
> <template>
>   <component :is="shouldWrap ? 'div' : 'template'">
>      some content
>   </component>
> </template>
> ```
> 
> (The above is a proposal, it doesn't currently work)

You can even shorten your code to this:
```
<template>
    <component :is="tag" v-if="tag">
        <slot/>
    </component>
    <slot v-else/>
</template>

<script setup lang="ts">
defineProps<{
    tag?: string;
}>();
</script>
```

With this, you can use it very similar to your prefered proposal:

```
<wrapper :tag="shouldWrap ? 'div' : undefined">
  some content
</wrapper>
```

**Comment by mojabyte** [comment]
A workaround is to use the `Transition` component:

```vue
<template>
    <component :is="condition ? Wrapper : Transition">
        <span>Child</span>
    </component>
</template>

<script setup>
import { Transition } from 'vue';
</script>
```

**Comment by slavco86** [comment]
Looks like a neat solution for Vue 3
https://dev.to/alexander-nenashev/conditional-wrap-component-in-vue-3-pt3-8dp

**Comment by Justineo** [comment]
I've created a new RFC to address this feature request. Please join the discussion [here](https://github.com/vuejs/rfcs/discussions/714) if you are interested.
