### ISSUE TITLE
watch object in deep oldValue and newValue is the same reference

### ISSUE THREAD

**Issue by Vgbire** [vuejs/vue#12037]
### Version
2.6.11

### Reproduction link
[https://codepen.io/vgbire/pen/WNGZbOQ](https://codepen.io/vgbire/pen/WNGZbOQ)

### Steps to reproduce
f12 open console to look its new value and old value

### What is expected?
old value and new value should not be the same reference

### What is actually happening?
old value and new value is the same reference

**Comment by posva** [comment]
This is expected and have been discussed in multiple issues as well in the official docs in the watcher sections or API

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by Vgbire** [comment]
> This is expected and have been discussed in multiple issues as well in the official docs in the watcher sections or API
I want to know why you know this problem but don't correct it. Is it because not correcting it makes Vue work better? Can you tell me more about it?
