### ISSUE TITLE
Cannot run npm install on macbook m1

### ISSUE THREAD

**Issue by serkanerip** [vuejs/vue#12031]
### Version
2.6.11

### Steps to reproduce
npm install

### What is expected?
Installing dependencies

### What is actually happening?
Getting npm error. 

```bash
npm ERR! code 1
npm ERR! path /Users/serkanerip/workspace/vue/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Only Mac 64 bits supported.
```
---
On new macbook m1, cannot run npm install because of **chromedriver** dependency. In newer versions this problem fixed and when i upgrade chromedriver version to 90.0 its now working.

**Comment by posva** [comment]
Thanks, there is an ongoing effort of upgrading the deps at #12001. For the moment, upgrade the dep locally.

**Comment by anjessen** [comment]
hello how upgrade that when I try same error message...
