### ISSUE TITLE
You may have an infinite update loop in a component render function.

### ISSUE THREAD

**Issue by NMFES** [vuejs/vue#12049]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/restless-river-v6r59?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/restless-river-v6r59?file=/src/components/HelloWorld.vue)

### Steps to reproduce
Just run the attached sandbox. Please pay attention to link() method.  If we comment "this.counter  ;" line then it works correctly.

### What is expected?
Console should output 'test' string only 10 times. Now it outputs hundreds of it.

### What is actually happening?
IDK

---
Here is an additional screenshot with the issue https://prnt.sc/12bttrd

**Comment by LinusBorg** [comment]
you are changing a reactive value *while the template is being rendered*, which means: now the template has to re-render, because a value it depends on just changed - and off you are into the infinite loop.

Rule: Never change reactive data during render.
