### ISSUE TITLE
Render components after specified amount of time

### ISSUE THREAD

**Issue by MathiasWP** [vuejs/vue#12040]
### What problem does this feature solve?
If you want to render a component after a specified amount of time has passed;

E.g: You have a loading screen, and if the loading takes more than X seconds then it would be nice to display some extra info.

The timeout should be triggered the moment the parent component is mounted.

### What does the proposed API look like?
```
<div id="parent">
<p v-after="3000">I am displayed after 3 seconds!</p>
</div>
```

**Comment by posva** [comment]
This is fully doable in userland with a directive or with a component.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
