### ISSUE TITLE
Watcher callback is not stable in IE browser

### ISSUE THREAD

**Issue by YanxinTang** [vuejs/vue#12041]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/detuloqena/1/edit?html,js,output](https://jsbin.com/detuloqena/1/edit?html,js,output)

### Steps to reproduce
1. Open reproduction link in IE browser
2. Click `Change Name With Timeout` button multiple times

### What is expected?
Watcher callback should always be called twice when click the button

### What is actually happening?
Watcher callback is not called sometimes. It's behavior is not stable and predictable.

---
Watcher callback is always called twice when click the button in Chrome and Firefox.

**Comment by posva** [comment]
Use a `nextTick()` to make it consistent:

```js
this.$nextTick(function() {
        that.name = 'tom';
      });
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
