### ISSUE TITLE
Render empty when HTML template is compress

### ISSUE THREAD

**Issue by frehaiku** [vuejs/vue#12043]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/frehk/uL5hbdwp/8/](https://jsfiddle.net/frehk/uL5hbdwp/8/)

### Steps to reproduce
Reproducing this bug requires:
1. render root element sibling is moved or removed in created hooks
2. sibling element not whitespace with render element（ with HTML compress ）

For example:
```
<!-- page render empty, when not whitespace -->
<div id="app"></div><div id="loading">loading...</div>
```

### What is expected?
render App template success

### What is actually happening?
render empty

**Comment by posva** [comment]
You should remove the element in `mounted` instead of `created()`
