### ISSUE TITLE
webpack v5 and vue 3.0.11

### ISSUE THREAD

**Issue by evenstensberg** [vuejs/vue#12050]
### Version
3.0.11

### Reproduction link
[https://github.com/evenstensberg/vue-react-module-federation/tree/master/lib/vue](https://github.com/evenstensberg/vue-react-module-federation/tree/master/lib/vue)

### Steps to reproduce
1. Clone the repository
2. Run npm install
3. Run npm run dev

### What is expected?
Sucessfully compiled build

### What is actually happening?
Errors in console

---
Hey! It would be awesome if you had webpack 5 compatibility with vue 3, even though vue 3 mainly is invoked through the vue cli. This would enable developers to try out new features such as Module Federation. Building a webpack project from scratch is very hard, but for some developers, this is the way to go to get a full overview of what is happening. Vue-tempate-compiler needs to be updated to vue 3, since one of the errors complains about that. Is there any way for me to help from a webpack stance of this? If so, please feel free to reach out! Thanks! Even

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by rowild** [comment]
Hmmm... I would actually understand this as a feature request...

**Comment by evenstensberg** [comment]
@posva could you reopen? It's a feature request.

**Comment by posva** [comment]
Then use the proper template next time, please. If this is about webpack 5 we already have an open issue #11718. For further questions/debugging, use the provided links.

**Comment by evenstensberg** [comment]
Resolved!
