### ISSUE TITLE
v-html directives has some bug

### ISSUE THREAD

**Issue by litterye** [vuejs/vue#12059]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/embed/unruffled-sea-tuvm3?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/unruffled-sea-tuvm3?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
<div class="box" v-html="'https://mps.hikvision.com/specialPriceApproval/specialPriceCreate?id=1212&spaNo=asdfasf&isThirdPart=0&page=04&currentActiveTabName=waitForApproval&recordSource=1'"></div>

### What is expected?
https://mps.hikvision.com/specialPriceApproval/specialPriceCreate?id=1212&spaNo=asdfasf&isThirdPart=0&page=04&currentActiveTabName=waitForApproval&recordSource=1

### What is actually happening?
https://mps.hikvision.com/specialPriceApproval/specialPriceCreate?id=1212&spaNo=asdfasf&isThirdPart=0&page=04¤tActiveTabName=waitForApproval&recordSource=1

---
<div class="box" v-html="<br"></div>
<div class="box" v-html="'<br/'"></div>
<div class="box" v-html="'<b'"></div>
<div class="box" v-html="'<ba'"></div>

**Comment by Justineo** [comment]
This is not a valid reproduction. Please read the rationale [here](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro).

**Comment by jacekkarczmarczyk** [comment]
this is how html works
https://codepen.io/jkarczm/pen/WNpNgRK?editors=1000

**Comment by litterye** [comment]
> This is not a valid reproduction. Please read the rationale [here](https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro).

why close?
you can open 'https://codesandbox.io/embed/unruffled-sea-tuvm3?fontsize=14&hidenavigation=1&theme=dark'  , this codesandbox link!
