### ISSUE TITLE
Is there any API to unreactive proxy instance to original object

### ISSUE THREAD

**Issue by sheepzh** [vuejs/vue#12057]
### What problem does this feature solve?
I'm a Firefox add-on developer.
It's not supported to save the reactive form data into chrome.storage.local, which is one kind of local storage provided by Firefox for add-ons.
So I want unreactive the form data before saving, and I don't find any API in reactivity.d.ts

### What does the proposed API look like?
``` javascript
const proxy = new Proxy({name:'123', no:'321'})
const data = unreactive(proxy)
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
