### ISSUE TITLE
v-show or v-if failed to process the data of sub component

### ISSUE THREAD

**Issue by scientistzjf** [vuejs/vue#12052]
### Version
2.6.11

### Reproduction link
[https://codepen.io/scientistzjf/pen/KKaOdrE](https://codepen.io/scientistzjf/pen/KKaOdrE)

### Steps to reproduce
===============================================================
FATHER CODE:
===============================================================
;(function(){
    window.mycomponent= {
            template: `<div v-if="switch">Some txt...</div>
    </div>`,
            components: {
                 SubComponent,
        },
        data() {
            return {
                switch: true
            }
        },
        created() {
            PubSub.subscribe('channel1',(event,status) => {
                this.switch= status
            })
        },
    }
})()

===============================================================
SUBCOMPONENT CODE:
===============================================================
;(function(){
    window.SubComponent= {
        template: `<div>
            <i-switch v-model="status" @on-change="change" size="large" true-value="true" false-value="false">
                <span slot="open">open</span>
                <span slot="close">close"</span>
            </i-switch>
        </div>`,
        data() {
            return {
                status: false
            }
        },
        methods: {
            change(status) {
                PubSub.publish('channel1',status);
            }
        },
    }
})()

### What is expected?
I hope the team can provide a temporary solution and fix this deficiency.

### What is actually happening?
Due to the lack of technology, the specific reasons are not clear, which may be some internal logic problems.

---
When PubSub is used to transfer data from the child component to the parent component, v-show or v-if can't continue to process the new data after the first processing of the child component's data, resulting in v-show or v-if failure.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
