### ISSUE TITLE
an input trigger keydown event with <Enter> will trigger other input focus event

### ISSUE THREAD

**Issue by zWingz** [vuejs/vue#12060]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/mystifying-golick-vu5wu?file=/src/App.vue](https://codesandbox.io/s/mystifying-golick-vu5wu?file=/src/App.vue)

### Steps to reproduce
the first input add 'focus' listeners
the other input trigger keydown event with \<Enter\> always trigger the first input focus event

### What is expected?
only trigger focus event when the first input focused

### What is actually happening?
the other input always trigger the first input focus event

### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/mystifying-golick-vu5wu?file=/src/App.vue](https://codesandbox.io/s/mystifying-golick-vu5wu?file=/src/App.vue)

### Steps to reproduce
the first input add <focus> listeners
the other input trigger keydown event with \<Enter\> always trigger the first input focus event

### What is expected?
only trigger focus event when the first input focused

### What is actually happening?
the other input always trigger the first input focus event

![image](https://user-images.githubusercontent.com/13031838/117412321-416af700-af47-11eb-9100-202610c58353.png)

**Comment by Hareis** [comment]
我没能重现这个错误
