### ISSUE TITLE
Value of input resets on blur if value of another variable is rendered

### ISSUE THREAD

**Issue by rationalthinker1** [vuejs/vue#12063]
### Version
2.6.11

### Reproduction link
[https://codepen.io/raza-farooq/pen/KKWwGep](https://codepen.io/raza-farooq/pen/KKWwGep)

### Steps to reproduce
1) On the view, type in `222` after `Hello` and click somewhere outside of input. You will see that `222` disappears and it reverts back to `Hello`.

2) Remove `{{ test }}` from the code and do the test again. You will see that the input value is still `Hello222`.

### What is expected?
Both cases should have the same value, which is `Hello222`.

### What is actually happening?
Two different values are being produced, simply because I'm displaying the value of `test`.

**Comment by JuniorTour** [comment]
try `v-model`：
``` js
  <input v-model="value"
         @focus="focusIn"
         @blur="focusOut"/>
```

**Comment by posva** [comment]
This is expected as changing test will render again and apply the value on the input which stayed `Hello`. Use v-model or set the value with js if you only want to set it once and not be reactive.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
