### ISSUE TITLE
[vue/.flowconfig] Failed to start flow Error: Flow version 0.61.0 doesn't support 'flow lsp'. Please upgrade flow to version >=0.75.

### ISSUE THREAD

**Issue by upupming** [vuejs/vue#12068]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
1. Clone the vuejs repo
2. yarn install and open VSCode, see the error:
    ![image](https://user-images.githubusercontent.com/24741764/117674037-eacb1a80-b1dd-11eb-9529-e57eb6fb866c.png)

Additional context: I am using the [Flow Language Support](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode&ssr=false#overview) for vscode

### What is expected?
Flow doesn't report an error

### What is actually happening?
Flow reported an error

**Comment by upupming** [comment]
But simply update `flow-cli` will got another error:

```cpp
[Info  - 10:46:21 PM - vue/.flowconfig] Found flow using option `useNPMPackagedFlow`
[Info  - 10:46:22 PM - vue/.flowconfig] Using flow '/Users/upupming/projects/vue/node_modules/flow-bin/flow-osx-v0.131.0/flow' (v0.131.0)
[Error - 10:46:22 PM] Connection to server got closed. Server will not be restarted.
.flowconfig:23 Unsupported option specified! (suppress_comment)
.flowconfig:14 Unsupported option specified! (unsafe.enable_getters_and_setters)

```

It seems `suppress_comment` and `unsafe.enable_getters_and_setters` [have been deprecated](https://github.com/facebook/flow/issues/5594).

So how can I enable the flow extension to work properly? Thanks for your kind help.

**Comment by upupming** [comment]
Sorry to bother, I solved this by created file `.vscode/settings.json` with the following content:

```json
{
  "flow.useLSP": false,
  "javascript.validate.enable": false
}

If anyone run into this problem, hope this will help.
```

**Comment by MarvinXu** [comment]
Hi, I used your config, but the syntax highlighting still not work.
![image](https://user-images.githubusercontent.com/7382357/139853324-a4c38b8e-98d3-4d8a-848d-64677772d00e.png)


> Sorry to bother, I solved this by created file `.vscode/settings.json` with the following content:
> 
> ```json
> {
>   "flow.useLSP": false,
>   "javascript.validate.enable": false
> }
> ```
> 
> If anyone runs into this problem, hope this will help.

**Comment by shinglove** [comment]
> Sorry to bother, I solved this by created file `.vscode/settings.json` with the following content:
> 
> ```json
> {
>   "flow.useLSP": false,
>   "javascript.validate.enable": false
> }
> ```
> 
> If anyone runs into this problem, hope this will help.

我按照这样无效～～～

**Comment by w2xi** [comment]
It works. Thank you.
