### ISSUE TITLE
Could I build a component in the structure (in chinese is  总-分 结构) just put structure above and the following is details?

### ISSUE THREAD

**Issue by radiorz** [vuejs/vue#12070]
### What problem does this feature solve?
https://stackoverflow.com/questions/67459619/why-the-v-slot-did-not-work-in-a-single-file/67461263#67461263
I am a new vue user and i dont know how to achive the goal:
Just build a component like using this structure but actually not use slot (slot will return errors.)
```
<v-row>
  <v-col cols="6"> this is first box: <slot name="first" /></v-col>
  <v-col cols="6"> this is second box: <slot name="second" /></v-col>
  <template v-slot:first> something first.... </template>
  <template v-slot:second> something second.... </template>
</v-row>
```

### What does the proposed API look like?
To make this work and maybe not use slot actually.
```
<v-row>
  <v-col cols="6"> this is first box: <slot name="first" /></v-col>
  <v-col cols="6"> this is second box: <slot name="second" /></v-col>
  <template v-slot:first> something first.... </template>
  <template v-slot:second> something second.... </template>
</v-row>
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
