### ISSUE TITLE
Vue.js allows invalid HTML to render 

### ISSUE THREAD

**Issue by ogdenstudios** [vuejs/vue#12076]
### Version
2.6.11

### Reproduction link
[https://codepen.io/ogdenstudios/pen/rNyePYo](https://codepen.io/ogdenstudios/pen/rNyePYo)

### Steps to reproduce
Nested anchor links are invalid HTML. If you write a nested anchor link in regular HTML, the browser will auto close the top-level anchor. Here is a codepen example demonstrating this: https://codepen.io/ogdenstudios/pen/KKWzJyo

The minimal reproduction I sent has the same markup (nested anchors), but renders them out as one top-level link: https://codepen.io/ogdenstudios/pen/rNyePYo

### What is expected?
Invalid HTML should be cleaned up, or Vue should allow the browser to clean it up in some way.

### What is actually happening?
Vue is allowing for invalid nested anchor links to exist as one single link.

---
We have a Vue.js component library, and we built a little card component that used top-level links. You can see that here: https://gitlab-com.gitlab.io/marketing/inbound-marketing/slippers-ui/iframe.html?id=components-event-cards--default&viewMode=story

We thought everything was good to go, and we began integrating into our production site, where we convert over from Vue.js to ERB and HTML. But then the anchor links got auto-closed, which initially confused us: https://gitlab.com/gitlab-com/www-gitlab-com/-/merge_requests/82067#note_575901115

It would have been ideal if Vue.js broke on the initial build so we caught it earlier during initial mockup, rather than as we were going into production with it.

Thanks for your hard work on Vue.js and any consideration you give to this report!

**Comment by posva** [comment]
> Invalid HTML should be cleaned up, or Vue should allow the browser to clean it up in some way.

This would be way too expensive.

You're still responsible of the HTML you write, it's not Vue responsibility to teach you HTML

**Comment by ogdenstudios** [comment]
Makes sense to me! Thanks for considering it.
