### ISSUE TITLE
Vue can't render big amount data

### ISSUE THREAD

**Issue by seuer** [vuejs/vue#12073]
### What problem does this feature solve?
I write html5 pages in mobile with Vue. A Page renders very slowly about 1 minute when I fetch 700 items from server.
How can I optimize the page for loading �fast. I have googled a component, say, vue-virtual-scroll-list , signaling a vue component that support big amount data list with high scroll performance. I, however, fail to optimize page when i follow the its steps in the url (https://vuejsexamples.com/a-vue-component-support-big-amount-data-list-with-high-scroll-performance/) .Do you have a good suggestion.

### What does the proposed API look like?
thanks to the security, i  can do paste my codes here.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
