### ISSUE TITLE
Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue

### ISSUE THREAD

**Issue by bellirodrigo2** [vuejs/vue#12075]
### Version
2.6.11

### Reproduction link
[https://github.com/bellirodrigo2/cta2](https://github.com/bellirodrigo2/cta2)

### Steps to reproduce
I'm opening this issue following instructions from [Vue warn] .
The link for minimal reproduction is a github project where I try to build a kind of input table (like excel).
when context menu is called and the option 'Delete Row' is selected, I see the following error in Firefox:
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at 
I'm using firefox, vue3 with composition API. The prop 

### What is expected?
One row removed from the table

### What is actually happening?
Bug report (vue warn)...

**Comment by posva** [comment]
You're in the wrong repo. It's vue next. But if you open a new issue make sure to provide a minimal boiled down reproduction (no ts,
Minsk code, only Vue). Otherwise you can use the Vue chat to ask questions
