### ISSUE TITLE
mixins namespaces

### ISSUE THREAD

**Issue by Igrokqq** [vuejs/vue#12085]
### What problem does this feature solve?
I've several components, parent,  parentSub1, parentSub2, parentSub3. I use a mixin for some important logic. But I forced to prefix each method of my mixin with his context like isCategoryEmpty (categoryMixin). I wanna have to call a mixin like this this.$mixins.categoryMixin.isEmpty(category). because this is more reachable

### What does the proposed API look like?
add all mixins to $mixins property which is a personal for every component. you should've an ability to call a mixin using an expression like this this.$mixins.myMixin.method(); instead this.method()

**Comment by posva** [comment]
This was proposed in the past and has been solved differently with the composition api.
With mixins, you need to create functions to pass that namespace as an argument

**Comment by Igrokqq** [comment]
@posva can you share an example please?
