### ISSUE TITLE
bug of Vnode memory leak

### ISSUE THREAD

**Issue by weidehai** [vuejs/vue#12081]
### Version
2.6.11

### Reproduction link
[https://codepen.io/weidehai/pen/mdWradp](https://codepen.io/weidehai/pen/mdWradp)

### Steps to reproduce
使用chrome的内存分析工具，对比隐藏前后的内存

### What is expected?
无论是子组件调用隐藏还是父组件调用隐藏都应该回收helloworld组件的vnode

### What is actually happening?
只有父组件调用隐藏才回收

---
如果修改子组件内button的click事件为@click.once，那么无论是子组件调用隐藏还是父组件调用隐藏都会回收helloworld组件的vnode

**Comment by weidehai** [comment]
![image](https://user-images.githubusercontent.com/25458528/118652025-baf0c800-b818-11eb-8f07-9b05b95f0425.png)
![image](https://user-images.githubusercontent.com/25458528/118652032-bdebb880-b818-11eb-92d3-e7182fe12563.png)
第一张的点击子组件调用隐藏按钮的内存分析，可以看到vnode没有回收，新加的那个是创建的comment节点
第一张的点击父组件调用隐藏按钮的内存分析，可以看到vnode回收了，新加的那个是创建的comment节点

**Comment by Alanscut** [comment]
It seems to have been fixed by #10085

**Comment by posva** [comment]
Thanks @Alanscut
