### ISSUE TITLE
Using //comment in a v:on event causes hard to debug error

### ISSUE THREAD

**Issue by lennycode** [vuejs/vue#12083]
### Version
2.6.11

### Reproduction link
[https://codepen.io/danichim/pen/KqRzKy/?editors=1111](https://codepen.io/danichim/pen/KqRzKy/?editors=1111)

### Steps to reproduce
change: `<button v-on:click="sayHello">Try me</button>`

to: `<button v-on:click="//sayHello">Try me</button>`

### What is expected?
Should report a better error message (e.g. // is forbidden). Or better yet process the comment. This is not caught in vuetur.

### What is actually happening?
Unexpected token referencing a line and column relative to the snippet (and could take time to find).

---
I was testing a snippet of Javascript in a v:on event.  This was in a 200 line component. 
Commenting there may not be the best practice, but it is valid JS.
I received an "Unexpected Token"  that did not give any guidance as to where there issue was.

**Comment by posva** [comment]
It's an unexpected token like many other tokens.
