### ISSUE TITLE
application's lifeCycle, state and data trace suggestion

### ISSUE THREAD

**Issue by 331000738** [vuejs/vue#12080]
### Version
2.6.11

我们用了三年的vue，因组件不易拆分，又转向用了差不多两年的react（hook），其间还有短暂尝试clojurescript+react/purescript，然后半年前，因为项目中要用uniapp，又回到vue，这次我们发现，vue的生命周期的状态管理包括最新的组合api，其实比react实现得更好，用得更舒服。只要细心管理状态和数据，vue更简洁和强大。

我们认为，无论前端还是后端，应用程序的核心都是对状态和数据管理，为了使整个应该程序的状态对开发者清晰可控，在生产阶段能跟踪每个用户的行为并解决异常（我们log所有前端日志到服务器），我们通过一次性加载全部pages组件，统一修改它们的所有的lifecycle, method, watch函数、改写了ref函数，并自己封装useGlobalState / usePersistState / emitter函数，实现了对应用程序状态的全面跟踪，有了这些，我们几乎不用再打什么日志了，并且应用程序应该变得更加健壮。效果如下图所示。

但有几个问题，第一，我们不得不为每个页面的data添加watch，这存在性能损耗，第二，uniapp的打包机制比较特殊，我们为改写每个页面组件，不得不先统一加载它们，但这样造成了页面组件的重复加载，导致打包体积过大。

因此，我们建议，是否可以考虑给vue全局增加状态跟踪配置，此配置可决定是否开启打印lifecycle变化, method调用（含调用时参数）, 页面data/ref/reactive的变化。

个人认为，vue成功的关键是是简单、创新和注重开发者体验，以上建议应与vue的思想是一致。望尤大考虑，谢谢！

### Reproduction link

![img](http://img.diandianys.com/Fgzma44uKPa5HRt-a8xUMHmZroDI)

![img](http://img.diandianys.com/FlHfP1S82DtB-vaTe36VOmbTzU-8)

### Steps to reproduce
统一改写每个pages组件的lifecycle, method, watch函数。

### What is expected?
优雅地跟踪应用程序的核心状态和数据

### What is actually happening?
[建议] vue全局增加配置，可配置是否开启log lifecycle变量, method调用及调用时参数, watch data/ref/reactive变化

**Comment by posva** [comment]
Please, follow the RFC process: https://github.com/vuejs/rfcs and open a discussion or PR in English
