### ISSUE TITLE
"Unknown custom element" Bug when importing with destructuring?

### ISSUE THREAD

**Issue by jordienr** [vuejs/vue#12084]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vibrant-wright-i13o6?file=/src/App.vue](https://codesandbox.io/s/vibrant-wright-i13o6?file=/src/App.vue)

### Steps to reproduce
1. Launch the project on codesandbox (https://codesandbox.io/s/vibrant-wright-i13o6?file=/src/App.vue)
2. Check the console

### What is expected?
It should render the components correctly

### What is actually happening?
Even tho the componets are in the `@/components` export they do not register properly.

It's showing 2 warnings and not rendering the components

```
Unknown custom element: <AppHeader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
Vue
Unknown custom element: <AppNavBar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
---
When you import the component directly 'import AppLayout from '@/components/layouts/AppLayout.vue'' it works

**Comment by stickpro** [comment]
try 
` import { AppLayout } from "@/components/layouts";`

**Comment by jordienr** [comment]
@stickpro Yes that would work but what I want it to be able to import always from '@/components'. The index in components is exporting everything from /layouts, so it should work. If you console.log everything from '@/components' it has the components.

**Comment by posva** [comment]
You have cyclic imports, you need to do what @stickpro suggested. This is not related to Vue.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by jordienr** [comment]
@posva I see, I thought when importing with destructuring It would only import the component I asked for. 

Thanks for clarifying and for your time Eduardo and @stickpro
