### ISSUE TITLE
Changing any data causes a component added in a v-for loop with a slot to rerender

### ISSUE THREAD

**Issue by nomve** [vuejs/vue#12082]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/n5o7k09L/](https://jsfiddle.net/n5o7k09L/)

### Steps to reproduce
1) add 1 or more child components with v-for
2) have the child component accept a slot and add some content to it
3) update some data that is unrelated to the child component

### What is expected?
I would expect the child component to not update. It is in fact not updating if there is slotted content or the component is added with a v-for loop, but if both of those things are true, it will update

### What is actually happening?
The component updates/rerenders.

---
I don't know if this is in fact a bug or just a limitation, but I could not find any reference to this behavior in the docs or anywhere else.

**Comment by posva** [comment]
This has been fixed but not released yet

**Comment by nomve** [comment]
thanks 👍

**Comment by VFertak** [comment]
@posva  thanks! which release will contain the fix?

**Comment by dodoto** [comment]
you can add functional to template in SFC, and it will not rerender.
