### ISSUE TITLE
$attrs received the no value prop will be an empty string, not a Boolean

### ISSUE THREAD

**Issue by zj9495** [vuejs/vue#12096]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/magical-thompson-i2jkt?file=/src/App.vue](https://codesandbox.io/s/magical-thompson-i2jkt?file=/src/App.vue)

### Steps to reproduce
1.create a Component and do not define any props
2.pass a no value prop like `<ComponentA isProp />`
3.use the `this.$attrs` to get the prop

### What is expected?
the prop with no value will imply `true`

### What is actually happening?
the prop is a empty string ''

**Comment by posva** [comment]
This is expected, like HTML attributes
