### ISSUE TITLE
Syntax Error: TypeError: this.getOptions is not a function with sass-loader v11

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/vue#12097]
### Version
2.6.11

### Reproduction link
[https://github.com/Oleksii14/vue-v2.6.12-sass-loader-v11](https://github.com/Oleksii14/vue-v2.6.12-sass-loader-v11)

### Steps to reproduce
run the project, see the error in the console

### What is expected?
Vue v2 supports new versions of sass-loader

### What is actually happening?
vue v2 does not work with sass-loader v11

**Comment by posva** [comment]
Check the vue-loader repo for similar issues and open a new one if there isn't any
