### ISSUE TITLE
Make events be propagated through the hierarchy all the way to the top unless handled somewhere on the way

### ISSUE THREAD

**Issue by jruchel** [vuejs/vue#12099]
### What problem does this feature solve?
This would remove the need to use an EventBus or manually reemit events untill they reach the desired component.
For example I would like to send an http request and have a component which handles that, I would be able to emit my event somewhere deep within the component hierarchy and have it handled all the way up in my component. I would not have to create an EvenBus between the components or have to reemit the same event again and again.
Another example would be I have a single component where all the snackbars in my application are shown, I would be able to emit a 'show-snackbar' event and give it the text as an argument, and the event would eventually be handled by the top component and a snackbar would be displayed, once again removing the need for an even bus or emitting events further and further up. This would also make components which make us of events more reusable since you can freely emit all the required events and have them handled by any of the parent components, no need to create an even bus when reusing the component or going through the entire component hierarchy to propagate the event.

### What does the proposed API look like?
When an event is emitted it would be emitted to it's parent and if the parent doesn't handle the event it would be emitted to the next parent and so on untill eventually the event gets handled

**Comment by posva** [comment]
This has been discussed already and it was intentionally removed/discouraged. Please search in existing issues
