### ISSUE TITLE
Hand cursor for the Subscribe button

### ISSUE THREAD

**Issue by ArunRaj6** [vuejs/vue#12093]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/x5etfrzb/1/](https://jsfiddle.net/x5etfrzb/1/)

### Steps to reproduce
Open the home page (https://vuejs.org/).
Scroll to the bottom end.
Hover on the Subscribe button near the Email field.

### What is expected?
Change the cursor into a hand when the user hovers over the Subscribe button.

### What is actually happening?
The cursor icon is not changing to hand when the user hovers over the Subscribe button like the other buttons on the page.

---
Losing the consistency.

**Comment by posva** [comment]
Feel free to open a Pull request on the docs repo
