### ISSUE TITLE
2.6.12版本和2.6.13版本渲染不一致

### ISSUE THREAD

**Issue by tmrcui** [vuejs/vue#12108]
### Version
2.6.13

### Reproduction link
[https://codepen.io/honggook/pen/GRWQLQd](https://codepen.io/honggook/pen/GRWQLQd)

### Steps to reproduce
vue 2.6.13
https://codepen.io/honggook/pen/GRWQLQd

vue 2.6.12
https://codepen.io/honggook/pen/qBrxwYm

### What is expected?
foo foo
bar

### What is actually happening?
foo foo

**Comment by posva** [comment]
Already fixed
