### ISSUE TITLE
Unexpected v-if behaviour in slot/template

### ISSUE THREAD

**Issue by mrkwdwrd** [vuejs/vue#12107]
### Version
2.6.13

### Reproduction link
[https://codepen.io/mrkwdwrd/pen/YzZedOe](https://codepen.io/mrkwdwrd/pen/YzZedOe)

### Steps to reproduce
Use the button to toggle the value of 'foo'.

### What is expected?
The elements in the 'content' slot with the v-if directive should display based on whether the value of 'foo' is true/false.

The elements with no v-if directive should display regardless of the value of 'foo'.

### What is actually happening?
When the elements are direct children of the slot template, neither are visible when 'foo' is false, both are visible when 'foo' is false **if the element with the v-if directive is the first**.

If the element **without** the v-if directive is the first, it is always displayed while the the the element **with** the v-if directive displays according to the value of 'foo'.

When the elements are wrapped and **not** direct children of the slot template, the element with the v-if directive displays according to the value of 'foo'. The element with no v-if directive always displays.

---
The behaviour was as expected before upgrading to vue@2.6.13. Rolled back to vue@2.6.11 and the expected behaviour was restored.

**Comment by doooooit** [comment]
I have the same problem

**Comment by mrkwdwrd** [comment]
Issue also not present on v2.6.11 - though there's no release notes for this version

**Comment by posva** [comment]
Already fixed. Search existing issues first, please
