### ISSUE TITLE
error in nuxtjs after upgrade to latest version 

### ISSUE THREAD

**Issue by YallaDealz** [vuejs/vue#12100]
### Version
2.6.13

### Reproduction link
[https://admin.yalladealz.com/](https://admin.yalladealz.com/)

### Steps to reproduce
after i upgrade today vue-server-renderer@2.6.13
├── vue-template-compiler@2.6.13
├── vue@2.6.13

i got this error when rendering my nuxt app on the server  Nuxtjs v2.15.6

ERROR in ./node_modules/vuetify/src/components/VGrid/VGrid.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VGrid/VGrid.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
3 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VGrid/VGrid.sass 3:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VGrid/VGrid.sass 4:14-204
 @ ./node_modules/vuetify/lib/components/VGrid/VCol.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./pages/en/dashboard/subscriptions/_id.vue
 @ ./node_modules/.cache/nuxt/router.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/.cache/nuxt/client.js

### What is expected?
to resolve compatibility for latest version 

### What is actually happening?
ERROR in ./node_modules/vuetify/src/components/VGrid/VGrid.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VGrid/VGrid.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
3 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VGrid/VGrid.sass 3:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VGrid/VGrid.sass 4:14-204
 @ ./node_modules/vuetify/lib/components/VGrid/VCol.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./pages/en/dashboard/subscriptions/_id.vue
 @ ./node_modules/.cache/nuxt/router.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/.cache/nuxt/client.js

**Comment by ZaneHow** [comment]
This could be of interest.

**Comment by ZaneHow** [comment]
https://github.com/vuetifyjs/vuetify/issues/13737

**Comment by posva** [comment]
Open the issue on Nuxt instead with a boiled down repro, not your whole website
