### ISSUE TITLE
The v-if on the first child tag in the template tag will affect other child tags 

### ISSUE THREAD

**Issue by gongshun** [vuejs/vue#12101]
### Version
2.6.13

### Reproduction link
[https://github.com/gongshun/vue-template-bug-repetition](https://github.com/gongshun/vue-template-bug-repetition)

This is a component with slots 

![image](https://user-images.githubusercontent.com/29347231/120456029-d090f080-c3c7-11eb-9b99-417694deb69c.png)

When i use it 

![image](https://user-images.githubusercontent.com/29347231/120456149-e999a180-c3c7-11eb-9346-61968b7410c9.png)

Its result

![image](https://user-images.githubusercontent.com/29347231/120456229-fb7b4480-c3c7-11eb-9ecc-201a10df5f40.png)

### Steps to reproduce
```
npm install
```
```
npm run serve
```
open http://localhost:8080/ in browser 

### What is expected?
The v-if on the first child tag in the template tag affects other child  tags 

### What is actually happening?
The v-if on the first child tag in the template tag does not affects other child  tags

**Comment by fydwxyd** [comment]
i have the same problem

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue/issues/12102
