### ISSUE TITLE
Vue js 2.6.13 component not rendering

### ISSUE THREAD

**Issue by litt1e-p** [vuejs/vue#12111]
### Version
2.6.13

### Reproduction link
[https://codesandbox.io/s/vue-component-2613-5hzzy](https://codesandbox.io/s/vue-component-2613-5hzzy)

### Steps to reproduce
After upgrading vue js from v2.6.12 to v2.6.13 some components don't get render and no warning message or error message in the console. but when I try to downgrade to version 2.6.12, the component successfully render.

Component code that doesn't get render using v2.6.13

### What is expected?
should render the component

### What is actually happening?
component does not render

---
why is the component not rendering, but it works when give them a wrapper container , here is a [demo](https://codesandbox.io/s/vue-component-2613-forked-it5yd?file=/src/components/HelloInput.vue:1247-1271)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue/pull/12104
