### ISSUE TITLE
Named default slot not working with multiple conditional elements

### ISSUE THREAD

**Issue by martinlundin** [vuejs/vue#12110]
### Version
2.6.13

### Reproduction link
[https://codesandbox.io/s/boring-paper-gxdk3?file=/src/App.vue](https://codesandbox.io/s/boring-paper-gxdk3?file=/src/App.vue)

### Steps to reproduce
Open repro, open App.vue. 
See that what is inside of the default template is not rendered. Remove the `#default` from the `<template>` tag and it works.

### What is expected?
List should render. In vue 2.6.12 it did.

### What is actually happening?
List is not rendered.

**Comment by posva** [comment]
Already fixed. Please check existing issues first

**Comment by martinlundin** [comment]
Okay great, could not find any, can you link it?

**Comment by jelle-eastground** [comment]
> 
> 
> Okay great, could not find any, can you link it?

https://github.com/vuejs/vue/issues/12107
