### ISSUE TITLE
Fallback slot is not showing up

### ISSUE THREAD

**Issue by Daniel4Digital** [vuejs/vue#12116]
### Version
2.6.13

### Reproduction link
[https://codepen.io/daniel4digital/pen/oNZqQgm](https://codepen.io/daniel4digital/pen/oNZqQgm)

### Steps to reproduce
Click the switch button, it will switch between two components with slots and without slots. The components without slots should not appear the slots passed to the components with slots

### What is expected?
Should display the fallback slot, as it did on 2.6.12 with the key workaround:
https://codepen.io/daniel4digital/pen/XWMEyWE

### What is actually happening?
Displays nothing:
https://codepen.io/daniel4digital/pen/oNZqQgm

PS: It is related with this fix: https://github.com/vuejs/vue/pull/11795

**Comment by posva** [comment]
Remove the `this.` in templates.

**Comment by Daniel4Digital** [comment]
@posva allright... I tested without the this and now that report I did it works BUT there seems to exist a biggest problem on this last release. I still think it is related with this. Not sure though.

If I've a template with a v-if on a div + others html elements, for example:

```
 <template #body class="mx-3">
            <div v-if="loading" class="py-5 my-5">
                <custom-mdb-spinner big>
                    <div class="title pt-3">{{ trans('_v4.general.navigation.loading') }}</div>
                </custom-mdb-spinner>
            </div>

                <custom-mdb-input
                    id="url"
                    v-model="form.fields.url"
                    :label="trans('_v4.general.app.label.url')"
                    size="xs"
                    type="url"
                />

                <custom-mdb-input
                    id="comment"
                    v-model="form.fields.comment"
                    :label="trans('_v4.general.app.label.description')"
                    size="xs"
                    type="text"
                />

        </template>
```

On the last version it was working fine. But on this new one, I need to add an extra div with v-else:
` <template #body class="mx-3">
            <div v-if="loading" class="py-5 my-5">
                <custom-mdb-spinner big>
                    <div class="title pt-3">{{ trans('_v4.general.navigation.loading') }}</div>
                </custom-mdb-spinner>
            </div>
            <div v-else>
                 <custom-mdb-input
                    id="url"
                    v-model="form.fields.url"
                    :label="trans('_v4.general.app.label.url')"
                    size="xs"
                    type="url"
                />

                <custom-mdb-input
                    id="comment"
                    v-model="form.fields.comment"
                    :label="trans('_v4.general.app.label.description')"
                    size="xs"
                    type="text"
                />
            </div>
        </template>`
        
        Diff between both, the code I had before, and the one I need to have now: 
        https://www.diffchecker.com/8x5kMbH1

**Comment by posva** [comment]
already fixed
