### ISSUE TITLE
First v-if inside a named template causes sibling elements to only render when it itself is rendered

### ISSUE THREAD

**Issue by SarthakSingh31** [vuejs/vue#12118]
### Version
2.6.13

### Reproduction link
[https://codesandbox.io/s/relaxed-sun-291he?file=/src/App.vue](https://codesandbox.io/s/relaxed-sun-291he?file=/src/App.vue)

### Steps to reproduce
1. Create a template with a named slot inside it.
2. Use this template inside a component.
3. Put a `<div v-if="false"></div>` as the first element inside the template for the named slot.
4. Add a sibling element after the `<div v-if="false"></div>`.

### What is expected?
The sibling element is rendered irrespective of the `<div v-if="false"></div>` being rendered

### What is actually happening?
The sibling element only renders when `<div v-if="false"></div>` renders i.e. when I set `v-if="true"`

---
This is my first time using codesandbox.io so I also created a git repo with the mcve incase the codesandbox.io link does not work.
https://github.com/SarthakSingh31/vue-mcve

**Comment by logaretm** [comment]
Same issue with `v-slot` syntax for default slots

https://codesandbox.io/s/red-https-vfqxw?file=/src/App.vue

**Comment by posva** [comment]
Please search existing issues before opening one. Already fixed

**Comment by SarthakSingh31** [comment]
I think it will help if #12102 is labeled as a bug as that is the label I searched under when I was looking for an existing issue.
