### ISSUE TITLE
Contains the content of the V-IF, and the order causes a rendering exception

### ISSUE THREAD

**Issue by HaSasa** [vuejs/vue#12114]
### Version
2.6.13

### Reproduction link
[https://codepen.io/hasasa/pen/zYZWRRE](https://codepen.io/hasasa/pen/zYZWRRE)

### Steps to reproduce
the firs button has "v-if";
the second button is normal

### What is expected?
Content without a judgment condition is rendered normally in each column

### What is actually happening?
Normally, button 2 should be in every column. In fact, when there is the content of the judgment condition. Cannot render properly without the normal content of the judgment condition.

When the content without a judgment condition is placed in the first position, the rendering is normal

---
<el-table-column  label="operate">
        <template slot-scope="scope">
          <el-button v-if="scope.row.date === '2016-05-02'">button1</el-button>
          <el-button>button2</el-button>
        </template>
</el-table-column>

**Comment by jacekkarczmarczyk** [comment]
#12104

**Comment by xpxs** [comment]
+1

**Comment by posva** [comment]
**Always** search existing issues first
