### ISSUE TITLE
Vue slot with conditionnal content

### ISSUE THREAD

**Issue by dev-oups** [vuejs/vue#12112]
### Version
2.6.13

### Reproduction link
[https://codepen.io/devoups/pen/xxqWExb?editors=1010](https://codepen.io/devoups/pen/xxqWExb?editors=1010)

### Steps to reproduce
Clic on toggle value. 

### What is expected?
The "false value" label should be visible.

### What is actually happening?
The "false value" label is never visible.

---
Adding an empty div make it works.

**Comment by jacekkarczmarczyk** [comment]
#12104
