### ISSUE TITLE
Is there a way to customize event modifiers

### ISSUE THREAD

**Issue by rocyuan666** [vuejs/vue#12127]
### What problem does this feature solve?
Custom event modifiers can be used to solve the problem of anti chattering and throttling

### What does the proposed API look like?
Customizable event modifiers

**Comment by posva** [comment]
There is no way to do so at the moment but it's worth open an RFC in the rfcs repository to propose an API similar to https://v3.vuejs.org/guide/component-custom-events.html#handling-v-model-modifiers
