### ISSUE TITLE
slot fallback content compiler error

### ISSUE THREAD

**Issue by trcat** [vuejs/vue#12122]
### Version
2.6.14

### Reproduction link
[https://codepen.io/trcat/pen/QWpxaVx](https://codepen.io/trcat/pen/QWpxaVx)

### Steps to reproduce
write a slot with fallback content, and use vue-template-compiler to build it, the fallback content will not work when no content is provided

### What is expected?
fallback content will work when no content is provided

### What is actually happening?
fallback content will not work when no content is provided.

fallback content will wrapped by a  function, but never invoked, so fallback content will never show

2.6.12 slot fallback content compiler

<img width="1029" alt="截屏2021-06-08 上午12 25 08" src="https://user-images.githubusercontent.com/23648263/121057862-4f37c480-c7f2-11eb-945e-cc5b31a005e9.png">

2.6.14 slot fallback content compiler

<img width="570" alt="截屏2021-06-08 上午12 42 05" src="https://user-images.githubusercontent.com/23648263/121058071-87d79e00-c7f2-11eb-8ddc-ef365032c6da.png">

2.6.14 slot fallback content wrapped with a function but never invoked, so the fallback content while never show.

please forgive me poor English

**Comment by trcat** [comment]
2.6.12 slot fallback content compiler

<img width="1029" alt="截屏2021-06-08 上午12 25 08" src="https://user-images.githubusercontent.com/23648263/121057862-4f37c480-c7f2-11eb-945e-cc5b31a005e9.png">

2.6.14 slot fallback content compiler

<img width="570" alt="截屏2021-06-08 上午12 42 05" src="https://user-images.githubusercontent.com/23648263/121058071-87d79e00-c7f2-11eb-8ddc-ef365032c6da.png">

**Comment by trcat** [comment]
2.6.14 slot fallback content wrapper with a function but never invoked.

**Comment by trcat** [comment]
please forgive me poor English

**Comment by posva** [comment]
Please open a new issue with the boiled down template and its compiled version with 2.6.12 in the provided codepen so I can test it
