### ISSUE TITLE
[vue-server-renderer] Use JSON.parse for larger __INITIAL_STATE__ JSONs

### ISSUE THREAD

**Issue by shinrox** [vuejs/vue#12126]
### What problem does this feature solve?
Sometimes the application end up having a large JSON to handle as the __INITIAL_STATE__, taking this post for examples on how this could impact in performance https://v8.dev/blog/cost-of-javascript-2019#json

The JSON.parse approach could improve script evaluation time for the initial load when needed 🙏 

### What does the proposed API look like?
The renderState method could use a context prop to use the JSON.parse approach after the JSON is serialized

https://github.com/vuejs/vue/blob/612fb89547711cacb030a3893a0065b785802860/packages/vue-server-renderer/build.dev.js#L9085

```js
var stateSerialized = this.serialize(context[contextKey]);
var autoRemove = '';
var state = context.parseState ? "JSON.parse(" + JSON.stringify(state) + ")"  : stateSerialized
  return context[contextKey]
    ? ("<script" + nonceAttr + ">window." + windowKey + "=" + state + autoRemove + "</script>")
    : ''
```

Would this bring any issue to code security or anything else?

**Comment by posva** [comment]
This is something you should handle yourself at https://ssr.vuejs.org/guide/data.html#final-state-injection because depending on what is in the state `JSON.stringify()` is not always possible

**Comment by shinrox** [comment]
Just a doubt, if I send the state as a string on that step, won't the `context.serialize` (inside the renderState method) run upon a string and not on an Object as is intended to?

And the `JSON.parse` approach, would avoid an extra step on the client code too

---

if handling this on the final state injection we'll have the following

```
ssr -> context.state = String
ssr -> serialize a String
ssr -> put the __initial_state__ = String on the final HTML
browser -> needs any other script, get the __initial_state__ and then parse to an object
```

If this is handled by the renderState method it would be like

```
ssr -> context.state = Object
ssr -> serialize an object
ssr -> put the __INITIAL_STATE = JSON.parse(str)
browser -> no extra script/step needed
```
