### ISSUE TITLE
Where is "_compiled" set up？

### ISSUE THREAD

**Issue by GpingFeng** [vuejs/vue#12130]
### Version
2.6.14

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/dist/vue.runtime.esm.js#L2999](https://github.com/vuejs/vue/blob/dev/dist/vue.runtime.esm.js#L2999)

### Steps to reproduce
I notice there is a setting [here](https://github.com/vuejs/vue/blob/dev/dist/vue.runtime.esm.js#L2999), but I can't find where to set it?

### What is expected?
Find positions

### What is actually happening?
Did not find

**Comment by GpingFeng** [comment]
PS: The reason I want to know this is because I have noticed that in some cases when using a functional component,  children are passed a String type. If "_compiled" is set to true, it will return an error.

![image](https://user-images.githubusercontent.com/20135760/121815723-60794900-ccaa-11eb-8ad9-d6903f50de1b.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
