### ISSUE TITLE
During a jump route, the DOM of the previous route is selectively preserved

### ISSUE THREAD

**Issue by GuoChen-thlg** [vuejs/vue#12136]
### What problem does this feature solve?
I tried to implement a recording function in one route, which required the video tag and canvas tag, but when I jumped to another route, even though I cached the component using Keep-Alive, its DOM was destroyed, so I couldn't continue recording.

### What does the proposed API look like?
You want to be able to customize the DOM and move it out of your APP, keep it working, hide it, and then restore it to its original location

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
