### ISSUE TITLE
Slot content is processed even v-if="false"

### ISSUE THREAD

**Issue by AuspeXeu** [vuejs/vue#12138]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/heuristic-darkness-3i6zm](https://codesandbox.io/s/heuristic-darkness-3i6zm)

### Steps to reproduce
1. Open link
2. Check the console for errors
```
[...] Error in render: "TypeError: _vm.obj is undefined"d
```

### What is expected?
The slot content should not be touched.

### What is actually happening?
The slot content references an object which is undefined. Despite the fact that v-if="false" was set on the slot element it will still throw an error and break the app.

**Comment by posva** [comment]
This is how regular slots work in Vue 2. Either add a `v-slot` to defer its execution or use a `v-if`. Otherwise a slot will always be rendered even if not used:


```vue
<HelloWorld msg="Hello Vue in CodeSandbox!" v-slot>
      <div>
        {{ obj.name }}
      </div>
    </HelloWorld>
```
