### ISSUE TITLE
tsconfig.json  set strict false,  vue props has a any type

### ISSUE THREAD

**Issue by tenadolanter** [vuejs/vue#12137]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/wonderful-fast-bnksk](https://codesandbox.io/s/wonderful-fast-bnksk)

### Steps to reproduce
# test.vue

```
<template>
  <div></div>
</template>

<script lang="ts">
import type { PropType } from "vue";
import Vue from "vue";

interface NameType {
  name: string;
}
export default Vue.extend({
  props: {
    type: {
      default: () => [],
      type: <PropType<NameType[]>> Array,
    }
  },
});
</script>
```

# tsconfig.json

```
{
  "compilerOptions": {
    "strict": false
  }
}
```

### What is expected?
hover  on  type props,  get `(property) type: PropValidator<NameType[]>` 

### What is actually happening?
 hover  on  type props,  get `(property) type: PropValidator<any[]>` 

---
value of strict effect typescript, wants to know why ?

**Comment by posva** [comment]
See the note at https://v3.vuejs.org/guide/typescript-support.html#recommended-configuration

> Note that you have to include strict: true (or at least noImplicitThis: true which is a part of strict flag) to leverage type checking of this in component methods otherwise it is always treated as any type.
