### ISSUE TITLE
Can I declaration multiple setup in vue3? 

### ISSUE THREAD

**Issue by wuweikd** [vuejs/vue#12139]
### What problem does this feature solve?
Can I declaration multiple setup in vue3? 
我能定义多个组合式API吗？

Thanks

### What does the proposed API look like?

Can I declaration multiple setup in vue3? 
我能定义多个组合式API吗？

Thanks

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by wuweikd** [comment]
当然，谢谢你的解答。
Of course, thank you for your answers
