### ISSUE TITLE
reactive does not work properly.

### ISSUE THREAD

**Issue by Rasool-deldar** [vuejs/vue#12149]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/keen-hugle-mjros](https://codesandbox.io/s/keen-hugle-mjros)

### Steps to reproduce
For example, I have a tree view component that I have used more than 20 times for ref, inject, and provide (up to 60) and I want these items to be reactive to send to the children of the component with a provide and with a inject to get it

### What is expected?
Data tracking is expected to work properly with a reactive

### What is actually happening?
I noticed that reactive does not work properly, for example, in ssr mode, it shows data within nuxt-js for one second, and then the data is deleted automatically, and in general, the changes inside it are not applied properly. Please resolve this issue.

**Comment by LinusBorg** [comment]
1. This is not a minimal reproduction. It's a nuxt project.
2. If this is a bug with Vue, it's with the composition AP plugin, not Vue core.

So please provide a *minimal* reproduction of the issue using nothing but vue composition API, and open the issue in github.com/vuejs/composition-api
