### ISSUE TITLE
vForm: TypeError: Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by Devendra3097** [vuejs/vue#12148]
### Version
2.6.14

### Reproduction link
[http://127.0.0.1:8000/edit/46](http://127.0.0.1:8000/edit/46)

<input
              type="text"
              class="form-control"
              v-model="post.description"
              :class="{ 'is-invalid': post.errors.has('description') }"
            />
            <HasError :form="post" field="description" />

### Steps to reproduce
http://127.0.0.1:8000/edit/46

### What is expected?
need to work validation properly

### What is actually happening?
TypeError: Cannot read property 'has' of undefined while editing the form with vform server-side validation package in laravel and vue js

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
