### ISSUE TITLE
Warning when providing an unknown argument to defineComponent

### ISSUE THREAD

**Issue by 1beb** [vuejs/vue#12140]
### What problem does this feature solve?

When typing "mixin" instead of "mixins". The mixin will fail silently, but there will be no error message. Providing an error or warning while Vue is in development would provide a quick pointer to the developer that they made a typo. 

Silent failures are the worst.

### What does the proposed API look like?

I imagine that you could iterate over the defineComponent arguments and test that they are within an array of known argument names. Even a general warning like "you have includedd a non-standard argument"

**Comment by posva** [comment]
This is expected and has been raised before. In vue, plugins can add anything.
The best to avoid these silent failures is to use types like TS
