### ISSUE TITLE
Unable to set Vue Router into History mode

### ISSUE THREAD

**Issue by jmriyaz84** [vuejs/vue#12147]
### Version
2.6.14

### Reproduction link
[https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations)

### Steps to reproduce
1. Enable Router mode as history 
2. Add following rule in httpd.config file as per the https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

> <IfModule mod_rewrite.c>
>   RewriteEngine On
>   RewriteBase /
>   RewriteRule ^index\.html$ - [L]
>   RewriteCond %{REQUEST_FILENAME} !-f
>   RewriteCond %{REQUEST_FILENAME} !-d
>   RewriteRule . /index.html [L]
> </IfModule>

3.httpd.conf file not accepting this rule , we can't use .htacess file for security & performance issue

### What is expected?
Apache server has to accept the rule , when user hit any child url it has to be redirected to index.html

### What is actually happening?
Getting 404 error page

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
