### ISSUE TITLE
SSR: attributes not updating on client re-render (_uid missmatch)

### ISSUE THREAD

**Issue by cjohannsen** [vuejs/vue#12154]
### Version
2.6.14

### Reproduction link
[https://github.com/cjohannsen/vue-SSR-uid-issue-reproduction](https://github.com/cjohannsen/vue-SSR-uid-issue-reproduction)

### Steps to reproduce
Clone the repository, install dependencies and run it. (npm install, npm run dev)

Now open localhost:8080 and you will see a label and an input. They both should be connected via id="..." and for="...", but the values are different. If you check the page source, you can see in the ssr result, that the uids are matching. But on the client, it is not updated.

### What is expected?
The client should rerender the attributes on the elements, that the _uid is matching on both elements.

### What is actually happening?
Vuejs just updates the input, I guess this is because of the v-model. However, the _uids are not matching, and you cannot focus the input via clicking on it.

---
We develop a cms where wo don't know how often a user will use a component on his page. Therefore we add the _uid to the id and the for attribute of the label / input, to focus the input on label click.

I used google a lot, but didn't find any other persons running in this issue.

I already created a thread in the forum for this, but after some reproduce trials, I have the thought it could be a bug in the framework.
(https://forum.vuejs.org/t/ssr-uid-is-not-updating-on-client-side/117923)

**Comment by posva** [comment]
This is too much for a reproduction, could you boil it down to just vue (no i18n, vuex, router, pug, etc)?

**Comment by cjohannsen** [comment]
hey @posva, thanks for your response. I just crated it with a boilerplate, just to give a reproduction. We will provide a new repo soon, asap.

**Comment by cjohannsen** [comment]
hello @posva, I remove all the packages, could you please check if this is acceptable for a reproduction? I also added a label in the component "Hello", to indicate if the uids are not matching. 

Thanks

**Comment by posva** [comment]
oh you were using the internal `_uid`. You need to use something else generated by your code to handle that in a way that it matches in server and client render
