### ISSUE TITLE
Deep 'set' in get-set computed property

### ISSUE THREAD

**Issue by willpakpoy** [vuejs/vue#12151]
### What problem does this feature solve?
Being able to have something happen when a computed property that is an object is updated, without having to use a watcher. Basically the "deep" option for watchers, but for computed properties.

### What does the proposed API look like?
```
computed {
	item: {
		get() {
			return getMyThing()
		},
		set(to) {
			setMyThing(to)
		}
		deep: true
	}
}
```

**Comment by posva** [comment]
This shouldn't be necessary if your object returned in the computed is reactive. Make sure the object returned in the better is properly reactive. The watcher would work the same way
