### ISSUE TITLE
vue slot 里面插入slot上面的默认内容显示不出来，而且我在我的项目里还会出现undefined

### ISSUE THREAD

**Issue by wuli-collov** [vuejs/vue#12153]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/amazing-easley-n35zm?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/amazing-easley-n35zm?file=/src/components/HelloWorld.vue)

### Steps to reproduce
组件里面写两个slot
<slot>
      <div>插槽默认内容</div>
      <slot name="hello">hello</slot>
</slot>
父页面调用组件 
<HelloWorld msg="Hello Vue in CodeSandbox!">
      <template name="hello">123</template>
    </HelloWorld>
就显示不出来插槽默认内容

### What is expected?
不要出现这个bug

### What is actually happening?
出现了slot bug

**Comment by posva** [comment]
It's

```vue
<HelloWorld msg="Hello Vue in CodeSandbox!">
      <template #hello>123</template>
    </HelloWorld>
```

or `v-slot:hello`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by wuli-collov** [comment]
额。。。那这个和旧的就不兼容了啊

**Comment by wuli-collov** [comment]
> It's
> 
> ```
> <HelloWorld msg="Hello Vue in CodeSandbox!">
>       <template #hello>123</template>
>     </HelloWorld>
> ```
> 
> or `v-slot:hello`
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

额。。。那这个和旧的就不兼容了啊

**Comment by yangmiao7** [comment]
If slot fallback content is Vue component, fallback content is not work,

**Comment by wuli-collov** [comment]
> If slot fallback content is Vue component, fallback content is not work,

yes,Can this problem be solved

**Comment by BryanAdamss** [comment]
fallback to `2.6.12` its work for me

**Comment by wsida** [comment]
要注意 vue 与 vue-template-compiler 版本一致，主要原因是 vue 中 renderSlot 方法 调整，在 v2.6.14 版本，renderSlot 第二个参数支持 函数类型，同时 vue-template-compiler  编译slot 返回一个函数，但是v2.6.12 版本，renderSlot 第二个参数只是VNode，同时 vue-template-compiler  编译slot 直接返回一个VNode。因此如果 vue-template-compiler 版本比vue 版本高，就会出现这种情况。希望有帮助

**Comment by shimangdian** [comment]
fallback to 2.6.12 its work for me too,thanks for @BryanAdamss

**Comment by zg19990220** [comment]
> 要注意 vue 与 vue-template-compiler 版本一致，主要原因是 vue 中 renderSlot 方法 调整，在 v2.6.13 版本，renderSlot 第二个参数支持 函数类型，同时 vue-template-compiler 编译slot 返回一个函数，但是v2.6.12 版本，renderSlot 第二个参数只是VNode，同时 vue-template-compiler 编译slot 直接返回一个VNode。因此如果 vue-template-compiler 版本比vue 版本高，就会出现这种情况。希望有帮助

现在我的是一致的版本 都是2.6.14 一样还是出现了这个问题  不同的是我的是ssr项目 有什么办法解决么

**Comment by zg19990220** [comment]
> 

项目正在升级webpack5  由于一些特殊原因  只能使用2.6.14版本@ @wsida

**Comment by qingniao99** [comment]
get it! thanks all.
