### ISSUE TITLE
Computed Property(Form) error

### ISSUE THREAD

**Issue by brnaldomesi** [vuejs/vue#12159]
### Version
2.6.14

### Reproduction link
[https://stackoverflow.com/questions/50821843/updating-a-computed-property-form-in-vue-on-error](https://stackoverflow.com/questions/50821843/updating-a-computed-property-form-in-vue-on-error)

### Steps to reproduce
Okay so I followed along with the entire Vue Laracasts videos, which ends up having a Form and an Errors class.

### What is expected?
Now what I'm trying to do is integrate Vuex to keep track of my currently logged in user, prefill a form with the current values, and show errors if any of the Laravel validation fails.

The problem I seem to be running into is that I have to set my authUser as a computed property, to pull it from the Vuex store. 

### What is actually happening?
Then since I can't use these in anything set in data I had to move my form to a computed property. Now that it's a computed property it never gets updated so my form never has errors even when errors are being thrown.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
