### ISSUE TITLE
The loop of findIdxInOld should start with index [ start + 1 ]

### ISSUE THREAD

**Issue by Vgbire** [vuejs/vue#12150]
### Version
2.6.14

### Reproduction link
[https://forum.vuejs.org/t/patch/117529](https://forum.vuejs.org/t/patch/117529)

### Steps to reproduce
First of all, findIdxInOld calls the samevnode method by looping oldStartIdx to (oldEndIdx - 1) to determine whether it is the same vnode to return index. Before the findIdxInOld method is executed, the samevnode comparison of oldStartVnode and newStartVnode has been executed in the previous judgment. Therefore, if the findIdxInOld method is to be executed, the loop  should be from (oldStartIdx  + 1) to (oldEndIdx - 1)
![image](https://user-images.githubusercontent.com/32129111/123506538-3f93f900-d697-11eb-8fba-8c5097bec773.png)

### What is expected?
The loop of findIdxInOld should start with index [ start + 1 ]

### What is actually happening?
The loop of findIdxInOld start with start index [start]

---
this is not a bug，but it maybe can reduce a comparison

**Comment by posva** [comment]
Thanks for the PR but no need to open an issue for this
