### ISSUE TITLE
Direct content of a component is processed even if the default slot is not rendered in the component, while if placed in a `<template #default>` it is not processed`

### ISSUE THREAD

**Issue by pdanpdan** [vuejs/vue#12157]
### Version
2.6.14

### Reproduction link
[https://codepen.io/pdanpdan/pen/YzVPZLO?editors=1010](https://codepen.io/pdanpdan/pen/YzVPZLO?editors=1010)

### Steps to reproduce
Load the codepen and open inspector console.
Check the messages logged in the console.

### What is expected?
Direct content of a component to behave identical to the case when it's placed inside `<template #default>`

### What is actually happening?
In the console of the codepen:
- there are 2 components (one renders the default slot, one does not)
- if the default slot is rendered then both direct content and content in `<template #default>` behave the same way
- if the default slot is not rendered then direct content is still processed, while content in `<template #default>` is not

**Comment by LinusBorg** [comment]
in Vue 2, 
* normal slots are evaluated in the parent and then passed to the child.
* scoped slots are functions passed down to the child and only valuated when used.

So this behaviour is expected.

In Vue 3, all slots are functions and behave like the scoped slots in Vue 2.

**Comment by pdanpdan** [comment]
So `<template #default>` always generates a scoped slot, while the direct content always generates a normal slot?

**Comment by LinusBorg** [comment]
Yes. For the former, you can also do:

```html
<component v-slot>
  ....
</component>
```

which is a shorthand you can use if there's only one default slot

See https://vuejs.org/v2/guide/components-slots.html#Abbreviated-Syntax-for-Lone-Default-Slots

**Comment by CamilleDrapier** [comment]
Alright, sorry for my knowledge to go only so far 🙇 
I'll use scoped slots until I can migrate to quasar2 than 🙇 
Thanks a lot for taking the time to look into this!!
