### ISSUE TITLE
Cannot set !important in CSS variable using the object syntax.

### ISSUE THREAD

**Issue by infinnie** [vuejs/vue#12156]
### Version
2.6.14

### Reproduction link
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDEgOnN0eWxlPVwieyctLWEnOicjY2NjIWltcG9ydGFudCd9XCI+e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgaDEge1xuICAgIGNvbG9yOnZhcigtLWEsIzMzMyk7XG4gIH1cbjwvc3R5bGU+In0=

### Steps to reproduce
In both 2.x and 3.x, when setting an element’s style using the object literal syntax, and when the CSS property is a CSS variable, one cannot set the value to `!important` like

```html
<h1 :style="{'--a':'#ccc!important'}">{{ msg }}</h1>
```

The code above does not work.

### What is expected?
The `--a` property is correctly set to `#ccc` and `important`.

### What is actually happening?
The value for `--a` is not set at all.

---

#### Notes
https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/platforms/web/runtime/modules/style.js#L10

https://github.com/vuejs/vue-next/blob/master/packages/runtime-dom/src/modules/style.ts#L45

**Comment by posva** [comment]
In HTML, you cannot set important in a style.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by infinnie** [comment]
> In HTML, you cannot set important in a style.
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug

However, compatibility has been achieved for other CSS properties:
```js
if (importantRE.test(val)) {
  // !important
  style.setProperty(
    hyphenate(prefixed),
    val.replace(importantRE, ''),
    'important'
  )
}
```

https://github.com/vuejs/vue-next/blob/fd7fa6f694ded9c78dcb149e996e16a7e78352d5/packages/runtime-dom/src/modules/style.ts#L50

So I wonder why the behaviors for CSS variables are not consistent.

**Comment by infinnie** [comment]
Please reopen this issue because it is about the inconsistent behavior that the workaround of “setting important in a style” is only added for non-variable properties. It is not about “set important in a style” _per se_.
