### ISSUE TITLE
Vue3 Provide / Inject is not working properly with reactive

### ISSUE THREAD

**Issue by zarub2k** [vuejs/vue#12155]
### Version
3.0.5

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPENoaWxkIC8 XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBwcm92aWRlIH0gZnJvbSAndnVlJztcbiAgaW1wb3J0IHN0b3JlIGZyb20gJy4vc3RvcmUuanMnO1xuICBpbXBvcnQgQ2hpbGQgZnJvbSAnLi9DaGlsZC52dWUnO1xuIFxuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgY29tcG9uZW50czoge1xuICAgICAgQ2hpbGRcbiAgICB9LFxuICAgIHNldHVwKCkge1xuICAgICAgY29uc3QgbXNnID0gJ1Byb3ZpZGUgKyBJbmplY3QgKyBSZWFjdGl2ZSBFeGFtcGxlJ1xuICAgICAgcHJvdmlkZSgnU1RPUkUnLCBzdG9yZSlcbiAgICAgIHJldHVybiB7XG4gICAgICAgIG1zZyxcbiAgICAgIH1cbiAgICB9XG4gIH1cbjwvc2NyaXB0PiIsInN0b3JlLmpzIjoiaW1wb3J0IHsgcmVhY3RpdmUsIHJlYWRvbmx5IH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgY3VycmVudFVzZXI6IHt9LFxuICBjb3VudDogMFxufSk7XG5cbmNvbnN0IHVwZGF0ZUN1cnJlbnRVc2VyID0gKHVzZXIpID0 IHtcbiAgc3RhdGUuY3VycmVudFVzZXIgPSB1c2VyO1xufTtcblxuY29uc3QgaW5jcmVtZW50ID0gKCkgPT4ge1xuICBzdGF0ZS5jb3VudCsrO1xuICBjb25zb2xlLmxvZyhzdGF0ZS5jb3VudCk7XG59XG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgc3RhdGU6IHJlYWRvbmx5KHN0YXRlKSxcbiAgdXBkYXRlQ3VycmVudFVzZXIsXG4gIGluY3JlbWVudFxufTsiLCJDaGlsZC52dWUiOiI8dGVtcGxhdGU XG4gIDxkaXY XG4gICAgQ2hpbGQgY29tcG9uZW50OiB7eyB2YWx1ZSB9fVxuICAgIDxwPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJwbHVzT25lXCI XG4gICAgICAgICsxXG4gICAgICA8L2J1dHRvbj5cbiAgICA8L3A XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgaW5qZWN0IH0gZnJvbSAndnVlJztcbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIHNldHVwKCkge1xuICAgICAgY29uc3Qgc3RvcmUgPSBpbmplY3QoJ1NUT1JFJyk7XG4gICAgICBjb25zdCB2YWx1ZSA9IHN0b3JlLnN0YXRlLmNvdW50O1xuICAgICAgY29uc3QgcGx1c09uZSA9ICgpID0 IHtcbiAgICAgICAgc3RvcmUuaW5jcmVtZW50KCk7XG4gICAgICB9O1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgdmFsdWUsXG4gICAgICAgIHBsdXNPbmVcbiAgICAgIH1cbiAgICB9XG4gIH1cbjwvc2NyaXB0PiJ9](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPENoaWxkIC8 XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBwcm92aWRlIH0gZnJvbSAndnVlJztcbiAgaW1wb3J0IHN0b3JlIGZyb20gJy4vc3RvcmUuanMnO1xuICBpbXBvcnQgQ2hpbGQgZnJvbSAnLi9DaGlsZC52dWUnO1xuIFxuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgY29tcG9uZW50czoge1xuICAgICAgQ2hpbGRcbiAgICB9LFxuICAgIHNldHVwKCkge1xuICAgICAgY29uc3QgbXNnID0gJ1Byb3ZpZGUgKyBJbmplY3QgKyBSZWFjdGl2ZSBFeGFtcGxlJ1xuICAgICAgcHJvdmlkZSgnU1RPUkUnLCBzdG9yZSlcbiAgICAgIHJldHVybiB7XG4gICAgICAgIG1zZyxcbiAgICAgIH1cbiAgICB9XG4gIH1cbjwvc2NyaXB0PiIsInN0b3JlLmpzIjoiaW1wb3J0IHsgcmVhY3RpdmUsIHJlYWRvbmx5IH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgY3VycmVudFVzZXI6IHt9LFxuICBjb3VudDogMFxufSk7XG5cbmNvbnN0IHVwZGF0ZUN1cnJlbnRVc2VyID0gKHVzZXIpID0 IHtcbiAgc3RhdGUuY3VycmVudFVzZXIgPSB1c2VyO1xufTtcblxuY29uc3QgaW5jcmVtZW50ID0gKCkgPT4ge1xuICBzdGF0ZS5jb3VudCsrO1xuICBjb25zb2xlLmxvZyhzdGF0ZS5jb3VudCk7XG59XG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgc3RhdGU6IHJlYWRvbmx5KHN0YXRlKSxcbiAgdXBkYXRlQ3VycmVudFVzZXIsXG4gIGluY3JlbWVudFxufTsiLCJDaGlsZC52dWUiOiI8dGVtcGxhdGU XG4gIDxkaXY XG4gICAgQ2hpbGQgY29tcG9uZW50OiB7eyB2YWx1ZSB9fVxuICAgIDxwPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9XCJwbHVzT25lXCI XG4gICAgICAgICsxXG4gICAgICA8L2J1dHRvbj5cbiAgICA8L3A XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgaW5qZWN0IH0gZnJvbSAndnVlJztcbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIHNldHVwKCkge1xuICAgICAgY29uc3Qgc3RvcmUgPSBpbmplY3QoJ1NUT1JFJyk7XG4gICAgICBjb25zdCB2YWx1ZSA9IHN0b3JlLnN0YXRlLmNvdW50O1xuICAgICAgY29uc3QgcGx1c09uZSA9ICgpID0 IHtcbiAgICAgICAgc3RvcmUuaW5jcmVtZW50KCk7XG4gICAgICB9O1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgdmFsdWUsXG4gICAgICAgIHBsdXNPbmVcbiAgICAgIH1cbiAgICB9XG4gIH1cbjwvc2NyaXB0PiJ9)

### Steps to reproduce
The reactive value is not reflecting to the child component. See the above link with example 

### What is expected?
The count value should be incremented through state mutation

### What is actually happening?
The value is incremented in the console. But the reactive property is not picked up in the UI

---

**Comment by HIMISOCOOL** [comment]
this repo isnt for vue3, this is the correct one:
https://github.com/vuejs/vue-next

**Comment by posva** [comment]
Your reproduction doesn't work. Can you open a proper an issue at the right repo (vuejs/vue-next) with a link that works?
