### ISSUE TITLE
call form reset method is not Responsive

### ISSUE THREAD

**Issue by zui-coding** [vuejs/vue#12162]
### Version
2.6.14

### Reproduction link
[http:// not link](http:// not link)

### Steps to reproduce
I have a form element,for example:
```
<form>
 name: <input type="text" v-mode="user.name">
</form>
export default {
        name: "User",
        data() {
            return {
                user: {
                    name:""
                }
        }
}
```
when I call  form reset() method ,  i find the user object is not Responsive by vue tool

ok, my english is just so-so ,Hope you can understand what i mean. gook luck

### What is expected?
Can also be responsive

### What is actually happening?
not responsive

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
