### ISSUE TITLE
Nodes not removing when changing route if you interact with an input

### ISSUE THREAD

**Issue by edulavin** [vuejs/vue#12163]
### Version
2.6.14

### Reproduction link
[https://codepen.io/edulavin/pen/LYyVMqO](https://codepen.io/edulavin/pen/LYyVMqO)

### Steps to reproduce
Open the codepen in debug mode and the performance monitor in Chrome Devtools
Write something in the input in Component 1
Click on the button to go to Component 2
Force the GC in the Chrome Devtools
Get back to Component 1

### What is expected?
Nodes reduce to the previous value

### What is actually happening?
Nodes count remains the same and if you go back to component 1 the node counts double in size. If you repeat the process the node count keeps rising

**Comment by posva** [comment]
![Screen Shot 2021-07-02 at 15 42 50](https://user-images.githubusercontent.com/664177/124283410-29c97c80-db4c-11eb-8efb-7c47ceba73dd.png)

Can't reproduce

**Comment by edulavin** [comment]
You have to open it in debug mode, otherwise the DOM Nodes counter doesn't work properly.

**Comment by edulavin** [comment]
> ![Screen Shot 2021-07-02 at 15 42 50](https://user-images.githubusercontent.com/664177/124283410-29c97c80-db4c-11eb-8efb-7c47ceba73dd.png)
> 
> Can't reproduce

You have to open it in debug mode, otherwise the DOM Nodes counter doesn't work properly.
