### ISSUE TITLE
vue@cli installation fails saying -- npm ERR! cb() never called!

### ISSUE THREAD

**Issue by danushk** [vuejs/vue#12160]
### Version
2.6.14

### Reproduction link
[https://github.com/npm/cli/issues/3502](https://github.com/npm/cli/issues/3502)

### Steps to reproduce
docker run -it -p 8080:8080 alpine:latest /bin/sh

apk add npm

npm i -g @vue/cli@nex

Node.js v14.17.1.

npm -v --7.17.0

### What is expected?
successful vue@cli installation

### What is actually happening?
screenshot

https://i.imgur.com/hz7P54y.png

# npm install -g @vue/cli@next
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T09_35_38_653Z-debug.log

---
i wanted to run vue on a docker container - so followed the usual steps and ended up with this.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
