### ISSUE TITLE
Nodes not removing when changing route if you interact with an input

### ISSUE THREAD

**Issue by edulavin** [vuejs/vue#12169]
### Version
2.6.14

### Reproduction link
[https://codepen.io/edulavin/pen/LYyVMqO](https://codepen.io/edulavin/pen/LYyVMqO)

### Steps to reproduce

- Open the codepen in **debug view** and the performance monitor in Chrome Devtools
- Write something in the input in Component 1
- Click on the button to go to Component 2
- Force the GC in the Chrome Devtools
- Get back to Component 1

### What is expected?
Nodes reduce to the previous value

### What is actually happening?
Nodes count remains the same and if you go back to component 1 the node counts double in size. If you repeat the process the node count keeps rising.

If you don't write anything on the input and change to Component 2 the component is properly destroyed and the DOM Nodes counter reduces

---
**It's necessary to open it in Debug View, otherwise the DOM Node counter won't work properly as it's an iframe**

**Comment by posva** [comment]
Don't open duplicate issues

**Comment by edulavin** [comment]
> Don't open duplicate issues

Then what sould I do? You closed the other issue but you couldn't reproduce because you didn't open it in debug view

**Comment by posva** [comment]
I did and even showed you a screenshot... I copied the code into an html file and ran it directly. If your need help debugging memory issues, you can always try with SO, Discord or the forum
