### ISSUE TITLE
[All versions] V-for dont cache all array elements [different render patch branches on v-for?]

### ISSUE THREAD

**Issue by SergeyMustafin** [vuejs/vue#12161]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/youthful-sara-xrlh3?file=%2Fsrc%2FApp.vue](https://codesandbox.io/s/youthful-sara-xrlh3?file=%2Fsrc%2FApp.vue)

### Steps to reproduce
To reproduce the bug, click on the second or third item, and then on the fourth or fifth.
The first three elements receive the transition, and the rest do not.

### What is expected?
All elements must change their width

### What is actually happening?
First three elements have a transition, but rest are not

---
https://forum.vuejs.org/t/v-for-dont-cache-all-array-elements-v-for-render-bug/118603

**Comment by posva** [comment]
This seems to be related to how the width property doesn't transition when an element is moved around with DOM operations and not with how Vue handles it. You will have to find a way to stick the width to the element when it moves so the CSS engine can trigger the transition

**Comment by SergeyMustafin** [comment]
> This seems to be related to how the width property doesn't transition when an element is moved around with DOM operations and not with how Vue handles it. You will have to find a way to stick the width to the element when it moves so the CSS engine can trigger the transition

But why first items change their width? And rest items dont change their width?

I tested it on React, on the React it works
