### ISSUE TITLE
HarmonyOS App support?

### ISSUE THREAD

**Issue by medz** [vuejs/vue#12170]
### What problem does this feature solve?
HarmonyOS App is developed in javascript language, is there any tool chain to support it? E.g:
- `@vue/cli`
- `vite`
- ...more

### What does the proposed API look like?
`@vue/cli` or `@vue/vite` CLI

**Comment by medz** [comment]
I seem to be stupid to raise such an issue!
harm!!!

**Comment by centosl** [comment]
That's a good idea

**Comment by GO-DIE** [comment]
That's a very good question, I have the same question too.

**Comment by ganshiqingyuan** [comment]
HarmonyOS seems like using vue in their website 
[HarmonyOS](https://www.harmonyos.com/cn/home/)

**Comment by medz** [comment]
> HarmonyOS seems like using vue in their website
> [HarmonyOS](https://www.harmonyos.com/cn/home/)

Yes, the HarmonyOS website is developed using Vue!

**Comment by lionlic** [comment]
Sounds like a good opportunity. Big company, Big money.right?

**Comment by medz** [comment]
> Sounds like a good opportunity. Big company, Big money.right?

Uhhhhhhm, you are the real master!

**Comment by posva** [comment]
Any bundler should do if they can run a webapp

**Comment by medz** [comment]
> @posva : Any bundler should do if they can run a webapp
Your opinion makes me feel sorry 😫, Vue.js is defined as "progressive JavaScript framework" instead of "browser framework"

**Comment by Justineo** [comment]
With the new architecture of Vue 3, it should be possible to implement runtime support in addition to the web, eg. miniapps. But the core team currently has no plan and not enough bandwidth to provide such support for these proprietary platforms, so let's see what solution our community will come up with.
