### ISSUE TITLE
3.x里面的template标签 为什么一定要指定默认的solt呢？

### ISSUE THREAD

**Issue by xiaocai-rookie** [vuejs/vue#12179]
### What problem does this feature solve?
template #default 能否默认就有，而不需要开发者再去添加

### What does the proposed API look like?
template #default 嫩否默认就有，而不需要开发者再去添加

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
