### ISSUE TITLE
尤大大，帮忙看个问题呗：vue2.6.x中通过对树进行递归，然后对组件进行渲染，递归生成嵌套的createElement函数体，最后渲染结果是：只渲染了首层组件，子组件都没有渲染进去

### ISSUE THREAD

**Issue by frontendWangqun** [vuejs/vue#12173]
### Version
2.6.14

### Reproduction link
[https://codepen.io/pen/](https://codepen.io/pen/)

### Steps to reproduce
1. 这是一个简单的树：（用的是elementUI组件）
const tree = [
  {
    componentName: 'Form',
    props: {},
    children: [
      {
        componentName: 'FormItem',
        children: [
          {
            componentName: 'Button'
          }
        ]
      }
    ]
  }
]

2. 这是渲染相关的代码：
function render(tree, createElement) {
  let childTemplete
  let renderRes = []
  tree.forEach((node) => {
    if (node.children) {
      childTemplete = createElement(
        node.componentName,
        {},
        render(node.children, createElement)
      )
    }
    renderRes.push(childTemplete)
  })
  return renderRes
}

new Vue({
  render: function(createElement) {
    const self = this
    return createElement(
      'div',
      {
        class: {
          'render-content': true,
        }
      },
      render(tree, createElement)
    )
  }
})

以上是整个过程的间代码

### What is expected?
希望tree中的所有组件可以正常渲染。

### What is actually happening?
只渲染了最外层组件(From)，其子组件FormItem和Button都没有渲染到dom中。

---
遇到这个问题暂时没有链接（重现链接是无效的），上面提供了相关的代码，希望看到答复我哦，在线等

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
