### ISSUE TITLE
How to use option `name` in `<script setup>`?

### ISSUE THREAD

**Issue by shenzhongchaoii** [vuejs/vue#12178]
### What problem does this feature solve?
Options API:
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'App', 👈
  setup() {
    return {}
  },
})
</script>

Composition API:
<script lang="ts" setup>
// want name
</script>

**Comment by Michal-Dziedzinski** [comment]
If you need to use ```name``` option or, for example,  ```inheritAttrs```you can use another ```<script>``` block with ```export default```. It will be compiledin to one ```script``` with options defined in ```<script>``` and setup function which will contains all the ```<script setup>``` things.
