### ISSUE TITLE
Could not read data of array at child component

### ISSUE THREAD

**Issue by martinym28** [vuejs/vue#12172]
### Version
2.6.14

### Reproduction link
[https://stackoverflow.com/questions/58700143/typeerror-cannot-read-property-id-of-undefined-in-vue](https://stackoverflow.com/questions/58700143/typeerror-cannot-read-property-id-of-undefined-in-vue)

### Steps to reproduce
------ array 
post: { "id": 1, "create": "2021-07-05", "update": "2021-07-05", "start": "2021-07-05", "end": "2021-07-05"}

------ @parent component
{{post.id}} show 1

------ @child component
{{post.id}} show Error in render: "TypeError: Cannot read property 'id' of undefined"

{{post}} show { "id": 1, "create": "2021-07-05", "update": "2021-07-05", "start": "2021-07-05", "end": "2021-07-05"}

------ how to read data as same at any component?

### What is expected?
how to read data as same at any component?

### What is actually happening?
Could not read data of array at child component

**Comment by standbyoneself** [comment]
Show the code / repository, please

**Comment by posva** [comment]
Use the forum or chat for questions
Always provide a boiled down runnable repro in bug reports, like asked in the issue helper

**Comment by martinym28** [comment]
------ add more code 
<PriceChild :post="this.post['price_formula']"  /> 
<PriceChild :post="this.post"  />
