### ISSUE TITLE
文档顶部’示例‘跳转有bug

### ISSUE THREAD

**Issue by 251205668** [vuejs/vue#12177]
### Version
2.6.14

### Reproduction link
[https://vuejs.bootcss.com/examples/](https://vuejs.bootcss.com/examples/)

### Steps to reproduce
resolve this bug

### What is expected?
resolve this bug

### What is actually happening?
resolve this bug

---
resolve this bug

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
