### ISSUE TITLE
IOS 15beta  use v-if  no dispaly if you first render the page

### ISSUE THREAD

**Issue by zzx2** [vuejs/vue#12186]
### Version
2.6.14

### Reproduction link
[https://codepen.io/zzx2/pen/yLbbeaB](https://codepen.io/zzx2/pen/yLbbeaB)

### Steps to reproduce
please open the Vue page in  IOS15 beta  env,if you use v-if  directive,you will see the dom is render but no display when you first render.(v-if is bind true)

### What is expected?
can render when you first render

### What is actually happening?
open the Vue page in  IOS15 beta  env,if you use v-if  directive,you will see the dom is render but no display when you first render.(v-if is bind true)

**Comment by posva** [comment]
You don't have any Vue code...
