### ISSUE TITLE
[Vue warn]: Property or method "nativeEvent" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by lanistor** [vuejs/vue#12181]
### Version
2.6.14

### Reproduction link
[https://www.npmjs.com/package/vue](https://www.npmjs.com/package/vue)

### Steps to reproduce
[Vue warn]: Property or method "nativeEvent" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
eval @ instrument.js?ea14:109
warn @ vue.esm.js?a026:628
warnNonPresent @ vue.esm.js?a026:2056
has @ vue.esm.js?a026:2101
isSyntheticEvent @ is.js?f404:128
normalizeValue @ object.js?e8f5:170
walk @ object.js?e8f5:207
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
walk @ object.js?e8f5:226
eval @ backend.js?ffa0:56
eval @ scope.js?2a3c:369
Scope._notifyScopeListeners @ scope.js?2a3c:368
Scope.addBreadcrumb @ scope.js?2a3c:278
Hub.addBreadcrumb @ hub.js?956e:196
Breadcrumbs._consoleBreadcrumb @ breadcrumbs.js?fd98:133
callback @ breadcrumbs.js?fd98:55
triggerHandlers @ instrument.js?ea14:76
eval @ instrument.js?ea14:106
mounted @ ScrollLoad.vue?f362:19
invokeWithErrorHandling @ vue.esm.js?a026:1872
callHook @ vue.esm.js?a026:4244
insert @ vue.esm.js?a026:3167
invokeInsertHook @ vue.esm.js?a026:6401
patch @ vue.esm.js?a026:6620
Vue._update @ vue.esm.js?a026:3972
updateComponent @ vue.esm.js?a026:4090
get @ vue.esm.js?a026:4504
run @ vue.esm.js?a026:4579
flushSchedulerQueue @ vue.esm.js?a026:4335
eval @ vue.esm.js?a026:1998
flushCallbacks @ vue.esm.js?a026:1924
Promise.then (async)
timerFunc @ vue.esm.js?a026:1951
nextTick @ vue.esm.js?a026:2008
queueWatcher @ vue.esm.js?a026:4427
update @ vue.esm.js?a026:4569
notify @ vue.esm.js?a026:739
reactiveSetter @ vue.esm.js?a026:1064
NOTIFY_MESSAGE__DONE_DATA @ index.ts?776d:21
wrappedMutationHandler @ vuex.esm.js?2f62:844
commitIterator @ vuex.esm.js?2f62:466
eval @ vuex.esm.js?2f62:465
_withCommit @ vuex.esm.js?2f62:624
commit @ vuex.esm.js?2f62:464
boundCommit @ vuex.esm.js?2f62:409
loadDatas @ index.ts?d20d:56
async function (async)
loadDatas @ index.ts?d20d:29
onRefreshData @ index.vue?b392:56
handleChangeTabClick @ index.vue?b392:45
invokeWithErrorHandling @ vue.esm.js?a026:1872
invoker @ vue.esm.js?a026:2197
invokeWithErrorHandling @ vue.esm.js?a026:1872
Vue.$emit @ vue.esm.js?a026:3912
handleTabClick @ tabs.vue?612b:75
click @ tab-nav.vue?4f50:250
invokeWithErrorHandling @ vue.esm.js?a026:1872
invoker @ vue.esm.js?a026:2197
original._wrapper @ vue.esm.js?a026:7609
sentryWrapped @ helpers.js?bf37:72
Show 23 more frames
instrument.js?ea14:109 [Vue warn]: Property or method "preventDefault" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

### What is expected?
No warn, read this.$el normally.

### What is actually happening?
Cannot read this.$el, even use ref, but can read the child element of the component.

**Comment by posva** [comment]
Follow the bug reporting guidelines and provide a boiled down repro when reporting a bug in a new issue.
Or use the chat or forum to ask questions
