### ISSUE TITLE
Command "Vue create .... " does not take its content through the proxy but directly through the firewall.

### ISSUE THREAD

**Issue by martidinho8** [vuejs/vue#12183]
### Version
2.6.14

### Reproduction link
[https://github.com/](https://github.com/)

### Steps to reproduce
Vue create via this registry.npmjs.org does not work through proxy with the specific url. Even though proxy's were filled in manually via microsoft visual studio code/ via specific code in "vue create" -

### What is expected?
That the content, from this webadress; registry.npmjs.org , goes automatically through the proxy.

### What is actually happening?
All the data obtained from that url goes directly to the firewall, bypassing the proxy. Even if the data was mandatory sent through the proxy(via command "vue create .... --proxy   manually via microsoft visual studio code).

Vue create takes like 20 minutes before it time-outs.

---
For security reasons, the proxy is required.

Looked already into these issues which are comparable; 

https://github.com/vuejs/vue-cli/issues/1364
https://github.com/vuejs/vue-cli/issues/1009

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
