### ISSUE TITLE
In custom directive, how to watch $emit in components?

### ISSUE THREAD

**Issue by tu6ge** [vuejs/vue#12184]
### What problem does this feature solve?
I search it in google, but mine not fonund mean

### What does the proposed API look like?
directive

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
