### ISSUE TITLE
Mulltiple checkbox bound to an array looses reactivity if data is modified before being assigned to the state

### ISSUE THREAD

**Issue by amorphine** [vuejs/vue#12187]
### Version
2.6.14

### Reproduction link
[https://jsfiddle.net/0pmojd65/6/](https://jsfiddle.net/0pmojd65/6/)

### Steps to reproduce
1. Uncheck Product 1 or Product 2 checkbox. You'll see no state visual changes but checkbox is unchecked. 

### What is expected?
Product 1 checkbox and Product 2 checkbox should no be unchecked

### What is actually happening?
Product 1 checkbox and Product 2 checkboxes are checked/unchecked

---
I  just want to be able to make a "middleware" for user data manipulation: prevent some checkboxes from being unchecked in computed setter or Vuex mutation. But checkboxes state seems to be not reactive. The workaround is to make checkboxes disabled but I am sure there's an explanation of such behaviour because I'm sure that's just my own misconception. Thank you.
- I asked at Vue discord channel 
- I posted a question at https://stackoverflow.com/questions/68412132/mulltiple-checkbox-bound-to-an-array-looses-reactivity-if-data-is-modified-befor

**Comment by posva** [comment]
For this specific scenario with checkboxes you need to manually set the checked state back to its original value in the computed as Vue will not have anything to update.
Please use the chat or forum for questions
