### ISSUE TITLE
Shadow DOM: DOMException: Failed to execute 'attachShadow' 

### ISSUE THREAD

**Issue by vkings1** [vuejs/vue#12198]
![ShadowDOM](https://user-images.githubusercontent.com/22137536/127290175-4c32b9b9-c076-4fae-ad32-617133c7d8b8.png)
### Version
2.6.14

### Reproduction link
[https://gist.github.com/praveenpuglia/0832da687ed5a5d7a0907046c9ef1813](https://gist.github.com/praveenpuglia/0832da687ed5a5d7a0907046c9ef1813)

### Steps to reproduce
I want to set, or select shadow DOM, but gives an error: DOMException: Failed to execute 'attachShadow' on 'Element': This element does not support attachShadow

### What is expected?
I want to create show dom.

### What is actually happening?
gives an error: DOMException: Failed to execute 'attachShadow'

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
