### ISSUE TITLE
RangeError traverse

### ISSUE THREAD

**Issue by Kolobok12309** [vuejs/vue#12193]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/crimson-worker-x4lgd?file=/src/App.vue](https://codesandbox.io/s/crimson-worker-x4lgd?file=/src/App.vue)

### Steps to reproduce
1. Add data prop with null value
2. Add to template dynamic class which value use prop from first step `{ foo: bar }`
3. Set prop value by array like this `[{ node: DomNode }]` where `DomNode` is root node for any vue component

### What is expected?
Boolean type cast of array

### What is actually happening?
```
RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at _traverse (eval at V (eval.js:31), <anonymous>:2144:63)
    at _traverse (eval at V (eval.js:31), <anonymous>:2160:19)
```

---
If i use class  `{ foo: !!bar }` all worked normally

**Comment by posva** [comment]
Use `Object.freeze()`: `this.el = Object.freeze(...)` so Vue doesn't try to observe the element which contains references to the Vue instance and thus creating an infinite loop.
