### ISSUE TITLE
Feature Request: Use `inject` like `props` for typescript

### ISSUE THREAD

**Issue by Keillion** [vuejs/vue#12194]
### What problem does this feature solve?
The `inject` just like a long range `prop`. 

So how about making them more similar?

Then typescript can know more about what types are the injected things.

### What does the proposed API look like?

```ts
export default defineComponent({
  props: {
    msg: String,
  },

  // how about making inject like prop
  inject: {
    user: String,
  },
  // more complex, like props
  inject: {
    user: {
      type: String,
      required: false,
      default: ()=>"K",
    },
  },

  // so we do not need to
  setup(props, context){
    const user = inject("user") as string;
    // later...
  },

  // and we can:

  // 1st API design
  setup(props, context, inject){
    const user = inject.user;
    // later...
  },

  // 2st API design
  setup(props, context){
    const user = context.inject.user;
    // later...
  },

  // maybe 2st is better, leave more space for future features
};
```

**Comment by posva** [comment]
This should go through an RFC on the rfcs repo.
In practice this is already possible with the injection symbols so it's not really worth to complicate the api

**Comment by Keillion** [comment]
I apologize, maybe this feature requests should go through RFC.

<br>

> 
> 
> In practice this is already possible with the injection symbols.

@posva  But I am not very sure what this `injection symbols` refers to.

<br>

I know we already have `provide/inject`.  I do not mean to Reinventing `inject`, but improve it.

It seems that some vue+ts users have encountered the same problem ([66067916](https://stackoverflow.com/questions/66067916/vue-3-inject-plugin-with-composition-api-and-typescript), [58613472](https://stackoverflow.com/questions/58613472/how-to-use-provide-inject-with-typescript-but-without-vue-class-component)) but there is no good enough solution. 

I find that [ts+props](https://v3.vuejs.org/guide/typescript-support.html#using-with-composition-api) do well. Maybe `inject` can do the same.
