### ISSUE TITLE
Vue 无法监听 Set 和 Map 类型元素的添加和删除

### ISSUE THREAD

**Issue by elewen** [vuejs/vue#12197]
### What problem does this feature solve?
希望页面对 Set 及 Map 遍历时如果添加或删除了元素，页面能实时更新dom节点。

### What does the proposed API look like?
希望页面对 Set 及 Map 遍历时如果添加或删除了元素，页面能实时更新dom节点。

**Comment by elewen** [comment]
虽然 $forceUpdate 可以强制更新，但是仅限于 Set 或 Map 来自同一个 Component。如果Set 或 Map 来自 props 或 store，还是没有合适的时机在组件内执行  $forceUpdate，除非 boardcast 一个事件或者额外通过目标组件的引用去调用一个更新的方法，但这也太麻烦了。

**Comment by Justineo** [comment]
Duplicate of #6774
