### ISSUE TITLE
Minimum Browser versions supported by Vue library 

### ISSUE THREAD

**Issue by jesusarockias** [vuejs/vue#12196]
### Version
2.6.14

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=)

### Steps to reproduce
I have searched the documentation but we are not able to find the minimum version of browsers (Chrome, Firefox, etc..) supported by Vue library.

Can anyone please let me know about this browser compatibility details of Vue 2 & 3library.

### What is expected?
Minimal browser versions

### What is actually happening?
minimal browser versions

**Comment by posva** [comment]
Search docs for issues about this and open a new one if nobody has
