### ISSUE TITLE
Inbuilt Obfuscation - FEATURE Request

### ISSUE THREAD

**Issue by ksarpotdar** [vuejs/vue#12202]
### **FEATURE Request**

There is Javascript-Obfuscation as well as webpack-obfuscation plugin which is through javascript-obfuscation. However can we get this feature **_### built in_** so that the webpack by default gives the moderate obfuscation...

### What does the proposed API look like?
Code Obfuscated

**Comment by posva** [comment]
This is completely unrelated to Vue. As you said, it has to be done with webpack.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
