### ISSUE TITLE
Vue features column on wikipedia - JS Web Framework Comparison 

### ISSUE THREAD

**Issue by deltaag** [vuejs/vue#12200]
### What problem does this feature solve?
Checking some Vue comparisons, I have come across this Wikipedia page (https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_web_frameworks) which has the Vue column empty. Considering being an open-source project, I think using Wikipedia to provide the data for the world would be nice.

### What does the proposed API look like?
Hope someone can spend some time to complete this.

**Comment by posva** [comment]
Anybody can contribute to Wikipedia. Feel free to do so 👍

**Comment by deltaag** [comment]
Unfortunately, I do not have the proper knowledge to do so, hence checking the Internet and Wikipedia for it.
