### ISSUE TITLE
Slot is not working in rare and unpredictable cases

### ISSUE THREAD

**Issue by Instinctlol** [vuejs/vue#12206]
### Version
2.6.14

### Reproduction link
[https://stackblitz.com/edit/vuejs-starter-ipzkcs?file=app.js](https://stackblitz.com/edit/vuejs-starter-ipzkcs?file=app.js)

### Steps to reproduce
Please look at the field "additionalArguments", it contains a link.
Press ALT M to load new data, instead of rendering a link here, the default slot content for that named slot is rendered instead.
You can press ALT J to load the original data, again no link.

### What is expected?
Instead of rendering the default slot content defined by the child, the passed down slot from orderDataCard should be rendered instead (the link).

### What is actually happening?
The slot can not be manipulated by collapsableCard.

---
So I have this weird problem where a certain slot doesn't work properly in very rare, but unknown conditions. What happens is that instead of rendering the slot according to the grandparent (OrderDataCard), the grandchild's (HeadLessTable) slot renders the default slot instead.

If you look at the render window in stackblitz, you will notice a table where a row contains the label "additionalArguments". Here, instead of rendering a string, a link shall be rendered instead. And this is obviously already working for this example. However, if you change the data via ALT M, the slot stops working and the default content will be rendered.

What's funny is that, if I use vue-devtools to copy over the new values one by one, there will be no issues.

CollapsableCard wraps the slot of HeadlessTable and passes it to OrderDataCard in a way that is described here: https://github.com/vuejs/vue/issues/11478#issue-647344835
But the issue here is not that this is done in a reusable way - it also happens if you pass the slots manually (EDIT: see [here](https://stackblitz.com/edit/vuejs-starter-xb8d3i?file=collapsableCard.js))

What I noticed is that if you uncomment line 19 in app.js, the issue does not occur. But in production the issue arises e.g. when invoices is set (line 88 app.js).

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro when reporting a bug.

**Comment by Instinctlol** [comment]
> 
> 
> Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro when reporting a bug.

I minimalized it, please open the issue again. Check Reproduction link section or click [here](https://stackblitz.com/edit/vuejs-starter-uzpckr?file=app.js) for minimalized code.
