### ISSUE TITLE
When a font name with a space in the style attribute is bind

### ISSUE THREAD

**Issue by reefle** [vuejs/vue#12203]
### Version
2.6.14

### Reproduction link
[https://codepen.io/reefle/pen/RwVBjxa](https://codepen.io/reefle/pen/RwVBjxa)

### Steps to reproduce
```html
 <main>
   <p :style='style'></p>
</main>
 <script src='js/vue/2.6.14-custom.js'></script>
 <script>
   new Vue({
     el:'main',
     data:{
       style:{
         fontFamily:'sample regular font'
       }
     }
   })
</script>
```

### What is expected?
Font names with spaces should be enclosed in single quotes. Otherwise, the web browser will fail to parse the HTML.
```html
<p style="font-family:'sample regular font';"></p>
```

### What is actually happening?
Google Chrome 92.0.4515.107（Official Build）
```html
<p style="font-family:" sample regular font" ;"></p>
```

---
vue is a great project :-)

**Comment by posva** [comment]
This is working as expected, you are passing the string `sample font`, not `'sample font'`, so Vue will set that. This is similar to not passing the unit to a number
