### ISSUE TITLE
大量数据在较小宽度的dom上使用Mustache语法的模块渲染导致浏览器崩溃

### ISSUE THREAD

**Issue by merfais** [vuejs/vue#12209]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/keen-hugle-x6hx9?file=/src/App.vue](https://codesandbox.io/s/keen-hugle-x6hx9?file=/src/App.vue)

### Steps to reproduce
0， 使用chrome 版本 90.0.4430.72（正式版本） （64 位）
1. 造一份比较大的对象数组，对象在10个以上字段，数组长度5000以上
2. template中添加一个dom，如div，设定宽度为100px,
3. 将数据通过 {{data}}的方式添加在上一步的dom中， 如 <div>{{bigData}}</div>
4. 为了方便观测效果，生成并添加bigData时，最好采用异步方式

### What is expected?
正常渲染

### What is actually happening?
浏览器崩溃，提示
错误代码：SBOX_FATAL_MEMORY_EXCEEDED”

---
猜测可能是vue的bug，需要官方确认下，

经测试，通过 this.$refs.dom.innerHTML = JSON.stringify(this.bigData, null, 4)的方式将数据写入dom中是可行的，所以猜测是vue的问题。

**Comment by posva** [comment]
Vue has a small overhead over direct DOM manipulation. Such big datasets require special handling to avoid observing them, for example `this.bigData = Object.freeze(a)`

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by merfais** [comment]
> Vue has a small overhead over direct DOM manipulation. Such big datasets require special handling to avoid observing them, for example `this.bigData = Object.freeze(a)`
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

do you have test it ?

`Object.freeze(a)` is also not work ! 

I am not sure that is vue's bug,  but I'm sure it didn't cause by observing data。

Please  taking the problem seriously，test it and find the reason, 3q. 

[demo link]( https://codesandbox.io/s/keen-hugle-x6hx9?file=/src/App.vue)
