### ISSUE TITLE
Props validation function is not called when the props is set to `null` or `undefined`

### ISSUE THREAD

**Issue by gilles-crealp** [vuejs/vue#12201]
### Version
2.6.14

### Reproduction link
[Vue SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxwPlRoZSBwcm9wcyB2YWxpZGF0aW9uIGZ1bmN0aW9uIGlzIG5vdCBjYWxsZWQgd2hlbiB0aGUgcHJvcHMgaXMgc2V0IHRvIDxjb2RlPm51bGw8L2NvZGU+IG9yIDxjb2RlPnVuZGVmaW5lZDwvY29kZT4uPC9wPlxuICAgIDxvbD5cbiAgICAgIDxsaT48YnV0dG9uIEBjbGljaz1cInRlc3QgPSAndmFsaWQgc3RyaW5nJ1wiPnRlc3QgPSAndmFsaWQgc3RyaW5nJzwvYnV0dG9uPiBPSyBkb24ndCB0aHJvdyBhbiBlcnJvci48L2xpPlxuICAgICAgPGxpPjxidXR0b24gQGNsaWNrPVwidGVzdCA9IG51bGxcIj50ZXN0ID0gbnVsbDwvYnV0dG9uPiA8Yj5LTzwvYj4gc2hvdWxkIHRocm93IGFuIGVycm9yLjwvbGk+XG4gICAgICA8bGk+PGJ1dHRvbiBAY2xpY2s9XCJ0ZXN0ID0gdW5kZWZpbmVkXCI+dGVzdCA9IHVuZGVmaW5lZDwvYnV0dG9uPiA8Yj5LTzwvYj4gc2hvdWxkIHRocm93IGFuIGVycm9yLjwvbGk+XG4gICAgICA8bGk+PGJ1dHRvbiBAY2xpY2s9XCJ0ZXN0ID0gJ290aGVyIHZhbGlkIHN0cmluZydcIj50ZXN0ID0gJ290aGVyIHZhbGlkIHN0cmluZyc8L2J1dHRvbj4gT0sgZG9uJ3QgdGhyb3cgYW4gZXJyb3IuPC9saT5cbiAgICAgIDxsaT48YnV0dG9uIEBjbGljaz1cInRlc3QgPSAnZmFpbCBzdHJpbmcnXCI+dGVzdCA9ICdmYWlsIHN0cmluZyc8L2J1dHRvbj4gT0sgdGhyb3cgYW4gZXJyb3IuPC9saT5cbiAgICAgIDxsaT48YnV0dG9uIEBjbGljaz1cInRlc3QgPSAxMjNcIj50ZXN0ID0gMTIzPC9idXR0b24+IE9LIHRocm93IGFuIGVycm9yLjwvbGk+XG4gICAgPC9vbD5cbiAgICA8cD48L3A+XG4gICAgPFRlc3QgOnRlc3Q9XCJ0ZXN0XCIgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuaW1wb3J0IFRlc3QgZnJvbSBcIi4vVGVzdC52dWVcIjtcblxuZXhwb3J0IGRlZmF1bHQge1xuICBuYW1lOiBcIkFwcFwiLFxuICBjb21wb25lbnRzOiB7XG4gICAgVGVzdFxuICB9LFxuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICB0ZXN0OiBcIlwiXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD4iLCJUZXN0LnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHA+Q29tcG9uZW50IDxjb2RlPnRlc3Q8L2NvZGU+IHZhbHVlOiBcInt7IHRlc3QgIT09IG51bGwgJiYgdGVzdCAhPT0gdW5kZWZpbmVkID8gdGVzdCA6IHRlc3QgPT09IG51bGwgPyAnbnVsbCcgOiB0ZXN0ID09PSB1bmRlZmluZWQgPyAndW5kZWZpbmVkJyA6ICc/JyAgfX1cIjwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIG5hbWU6IFwiVGVzdFwiLFxuICBwcm9wczoge1xuICAgIHRlc3Q6IHtcbiAgICAgIHR5cGU6IFN0cmluZyxcbiAgICAgIHZhbGlkYXRvcih2YWx1ZSkge1xuICAgICAgICBjb25zb2xlLmxvZyhcInZhbGlkYXRvclwiLCB2YWx1ZSwgJy0+JywgdmFsdWUgIT09IG51bGwgJiYgdmFsdWUgIT09IHVuZGVmaW5lZCAmJiB2YWx1ZSAhPT0gXCJmYWlsXCIpXG4gICAgICAgIHJldHVybiB2YWx1ZSAhPT0gbnVsbCAmJiB2YWx1ZSAhPT0gdW5kZWZpbmVkICYmIHZhbHVlICE9PSBcImZhaWwgc3RyaW5nXCJcbiAgICAgIH1cbiAgICB9XG4gIH0sXG4gIHdhdGNoOiB7XG4gICAgdGVzdCgpIHtcbiAgICAgIGNvbnNvbGUubG9nKFwid2F0Y2hcIiwgdGhpcy50ZXN0KVxuICAgIH1cbiAgfVxufTtcbjwvc2NyaXB0PiJ9)

### Steps to reproduce
Pass `null` or `undefined` to a component with a validation function.

### What is expected?
The prop validation function must be called for everything passed even `null` or `undefined`.

### What is actually happening?
The prop validation function is not called.

**Comment by posva** [comment]
This is intended: `null` and `undefined` pass any type of validation: https://v3.vuejs.org/guide/component-props.html#prop-validation

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
