### ISSUE TITLE
Scoped states

### ISSUE THREAD

**Issue by AbrahemAlhofe** [vuejs/vue#12212]
### What problem does this feature solve?
when we want to do something like hide / show password input we should add state called "IsVisible" in our data but actually this data is specific for this input not relate to our app so we shoud put it on a scope of the element to prevent our data's pollution

### What does the proposed API look like?
```html
<div class="field" v-data="{ isVisible : false }">
   <button @click="isVisible = !isVisible">isVisible ? 'hide' : 'show'</button>
   <input :type=" isVisible ? 'text' : 'password' " />
</div>
```

**Comment by posva** [comment]
Please search v-scope in issues and PR to see this was already asked

**Comment by nfplee** [comment]
@posva where can I find the existing pr/issue? I’ve tried searching it in both but cannot find it. This is actually how I stumbled upon this issue as this is the one thing I can do in petite vue that I can’t do in vue without having to create a component.

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/pull/7325
