### ISSUE TITLE
支持defineCustomElement API

### ISSUE THREAD

**Issue by xiaoqqchen** [vuejs/vue#12226]
### What problem does this feature solve?
Vue3.2发布了defineCustomElement API非常好用。Vue2.x能否也能提供这种功能呢？

### What does the proposed API look like?
https://v3.vuejs.org/guide/web-components.html#building-custom-elements-with-vue

**Comment by posva** [comment]
There is https://github.com/vuejs/vue-web-component-wrapper and https://github.com/karol-f/vue-custom-element.
