### ISSUE TITLE
Options object on defineAsyncComponent

### ISSUE THREAD

**Issue by possibility-of-offense** [vuejs/vue#12229]
### Version
3

### Reproduction link
[https://github.com/possibility-of-offense/defineAsyncComponent](https://github.com/possibility-of-offense/defineAsyncComponent)

### Steps to reproduce
I wanted to use the options object instead of the basic usage of the defineAsyncComponent in App.vue.
So everything is fine but I cannot load the loadingComponent.
When I tested this in codesandbox (initially I was ready to give a link to the project in codesandbox) it was working fine; the component was load, but when I did it locally generating the project through vue-cli, I couldn't load the loadingComponent - the mock API is working though. But I want some feedback when the data is being fetched.

### What is expected?
Someone to explain me what I'm missing

### What is actually happening?
Not loading a component when it should

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by possibility-of-offense** [comment]
Thank you for your reply. I was not sure if here is the place to ask :)
