### ISSUE TITLE
Sorry, I don't know what to call it

### ISSUE THREAD

**Issue by DoniNx** [vuejs/vue#12221]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/vue-3-fuc20](https://codesandbox.io/s/vue-3-fuc20)

### Steps to reproduce
Open the code. clear our the todo list by pressing the DONE button at the right hand corner. Click the Add Task button to view the Add Task form. Next try adding a new item to the todo list. it will add, the issue occurs when you try to add a second todo item. it will start over writing the first one. i am sure that there is no issue with my code. take a look yourselves

### What is expected?
it should have added my item to the todo list. 

### What is actually happening?
when i add a new item to the todo list it adds it but when I try to add a new one it replaces the text in the former one not add a new one. its kinda hard to explain so take a look at the codesandbox

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).


When reporting a bug read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro. Most bugs should be reproducible with the [SFC Playground](https://sfc.vuejs.org). BTW, you should open the issue on vue-next repo
