### ISSUE TITLE
When changing the class of an element, the methods of child elements are called again

### ISSUE THREAD

**Issue by b01010110** [vuejs/vue#12235]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/vue2-reactive-test-wr1wf?file=/src/App.vue](https://codesandbox.io/s/vue2-reactive-test-wr1wf?file=/src/App.vue)

### Steps to reproduce
click to button and watch to console

### What is expected?
I expected that the method will be called again only when the element on which this method is hanging will be remounted.

### What is actually happening?
When you click on the button, the class of the element is dynamically changed.
The 'veryLongCalculation' method is called again on the children of this element.
Is this normal behavior?

**Comment by posva** [comment]
This is indeed expected behavior. You can use a computed property (no parameters) to cache the call.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by b01010110** [comment]
@posva See example 2, how is here to use computed property?
