### ISSUE TITLE
Component property is not recognized in @Component decorator

### ISSUE THREAD

**Issue by Faber-smythe** [vuejs/vue#12233]
### Version
2.6.14

### Reproduction link
[https://github.com/nuxt/nuxt.js/issues/9689](https://github.com/nuxt/nuxt.js/issues/9689)

### Steps to reproduce
Create a component looking like this :

```
import { Component, Vue } from 'vue-property-decorator'

@Component({
  head() {
    return {
      title: this.name
    }
  }
})

class Index extends Vue {
  name: string =  'Index Page'
}

export default Index
```

### What is expected?
The goal is to have dynamic page title (meta head tag).

As discussed in this Nuxt issue (https://github.com/nuxt/nuxt.js/issues/684) the way to use the head() method in a Class-based component is to put it in the @Component decorator.

Based on the "Steps to reproduce" above, the browser tab displaying the project should have the name "Index Page"

### What is actually happening?
The property is not recognized, and the displayed page title is the default project name.

With typescript and Vetur, it show the following error :
"Property 'name' does not exist on type 'Vue'."

**Comment by LinusBorg** [comment]
class components and the property-decorator package are not part of this repo. Please open a new issue in the repo fo the package you are having issues with.
