### ISSUE TITLE
how to invoke method by method name then can use this

### ISSUE THREAD

**Issue by jianchengwang** [vuejs/vue#12237]
### Version
2.6.14

### Reproduction link
[https://codepen.io/jianchengwang/pen/MWogRjB](https://codepen.io/jianchengwang/pen/MWogRjB)

### Steps to reproduce
Here is my code
```
var vue = new Vue({
  el: "#view",
  data: {
  },
  methods: {
    invokMethod(event) {
       console.info(this.$options)
       this.$options.methods[event]()
    },
    event1() {
      console.info(this.$options)
    }
  }
})
```

### What is expected?
two **this** should be same

### What is actually happening?
two **this** is different, second **this** is not vue component **this**, lose much things.

**Comment by JuniorTour** [comment]
It has nothing to do with Vue.js. 

It is correct behavior of Javascript `this` keyword

I suggest you close this issue

Reference:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#as_an_object_method
![image](https://user-images.githubusercontent.com/14243906/130399670-cb7fd1c3-5a27-4362-a164-ae71f1ab1945.png)

Or your can simply pass `this` as a param:
``` js
invokMethod(event) {
       console.info(this.$options)
       this.$options.methods[event](this.$options)
},
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
