### ISSUE TITLE
Should 'Unknown custom element'  be recognized as  an error instead of a warn?

### ISSUE THREAD

**Issue by WilkinWendy** [vuejs/vue#12236]
### What problem does this feature solve?
In my project, for some reasons,  some components are not registered correctly when refactoring.
Surely, this is a mistake of the developer , but i think this should be an error so that it can be reported in production mode

### What does the proposed API look like?
          if (isUnknownElement$$1(vnode, creatingElmInVPre)) {
            globalHandleError(
              'Unknown custom element: <'   tag   '> - did you '  
              'register the component correctly? For recursive components, '  
              'make sure to provide the "name" option.',
              vnode.context
            );
          }

**Comment by posva** [comment]
You can implement this with https://v3.vuejs.org/api/application-config.html#compileroptions-iscustomelement

**Comment by WilkinWendy** [comment]
Is there any solution in v2? @posva

**Comment by posva** [comment]
You can maybe use https://vuejs.org/v2/api/#ignoredElements or https://vuejs.org/v2/api/#warnHandler but it will still development only because these errors should be caught during development.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by WilkinWendy** [comment]
@posva Of course, errors should be caught during development. But  in my case, the ignorance of this problem causes a user case without any exception infos after the refactoring of our system .
I'm trying  to find an approach to report this error.
Every programmer can't not ensure he would not make any mistake,is it?
