### ISSUE TITLE
`createElement` option `attrs` should not mutate input

### ISSUE THREAD

**Issue by woshiguabi** [vuejs/vue#12240]
### Version
2.6.14

### Reproduction link
[https://codesandbox.io/s/optimistic-architecture-vrdvu?file=/src/App.vue](https://codesandbox.io/s/optimistic-architecture-vrdvu?file=/src/App.vue)

```
<script>
import Vue from "vue";
const Foo = {
  props: ["foo"],
  render(h) {
    return h("li", ["label: ", this.foo]);
  },
};

export default {
  name: "App",
  components: { Foo },
  data() {
    return { attrs: { foo: "foo" } };
  },
  render(h) {
    return h("ul", [
      h("li", ["version: ", Vue.version]),
      h(Foo, { attrs: this.attrs }),
      h(Foo, { attrs: this.attrs }),
    ]);
  },
};
</script>
```

### Steps to reproduce
see codesandbox

### What is expected?
The second render result same as the first. And `this.attrs` should not be mutated.

### What is actually happening?
`this.attrs.foo` has been deleted.

**Comment by posva** [comment]
This is by design. I couldn't find the original issue but I think it was for performance reasons. You need to pass a _"fresh"_ object to `h`. So in this case, you need to copy `this.attrs`:

```js
      h(Foo, { attrs: {...this.attrs} }),
      h(Foo, { attrs: {...this.attrs} }),
```
