### ISSUE TITLE
Component rendering in production build but not in development

### ISSUE THREAD

**Issue by parthibd** [vuejs/vue#12246]
### Version
2.6.14

### Reproduction link
[http://localhost:8080/](http://localhost:8080)

### Steps to reproduce
Just replace the vue dev build library with vue production build library.

### What is expected?
Component should render in dev build . 

### What is actually happening?
High CPU usage and component is not rendering

---
When I do a production build , the app just works fine but in dev build the whole page goes unresponsive with high CPU usage. And it's related to just one component.

I am unable to show you a minimal reproduction since it's happening only in development but not in production :(

**Comment by parthibd** [comment]
Update:

The issue seems to be this line 

https://github.com/vuejs/vue/blob/7094fc081ade9208e9f759a9145ec34a28143bf1/src/compiler/codeframe.js#L16

It's was stuck in an infinite loop. I do not experience with the compiler codebase so I am not sure if it's the only reason for my bug.

**Comment by parthibd** [comment]
Related:

https://github.com/vuejs/vue/issues/10547
https://github.com/vuejs/vue/pull/10553

**Comment by parthibd** [comment]
Seems to be addressed in Vue 3 but not Vue 2

https://github.com/vuejs/vue-next/issues/3987

**Comment by parthibd** [comment]
@posva @yyx990803

**Comment by posva** [comment]
Open a new issue with an actual reproduction. Otherwise we can't do much
