### ISSUE TITLE
Flashing images in reactive content

### ISSUE THREAD

**Issue by adamlwgriffiths** [vuejs/vue#12259]
### Version
2.6.14

### Reproduction link
[v3.vuejs.org](https://v3.vuejs.org/examples/markdown.html)

### Steps to reproduce
Add the following markdown:

`![](https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg)`

Then begin typing other content and let the page update.

### What is expected?
The image to remain and only new text to be appended.

### What is actually happening?
Images are being deleted and re-added.
* This triggers a GET (seen on server logs for my local case).
* The image starts unloaded as zero size, triggering a layout reflow
* The image then loads and appears, triggering another layout reflow.

When updating content dynamically, this causes flashing.

---
My context: I'm trying to append markdown to a 'markdown' widget. But any images in the widget cause flashing.
Your example markdown widget works the same way mine does (albeit my additions are automated and so don't have timers to trigger them).
Every time I add content, the image flashes, which is very disturbing.

Viewing the elements in the inspector, it's apparent that the <img> nodes are being deleted and re-added (click the image element, the selection will be pushed off as the element is momentarily removed and re-added).

Because this existing content isn't deleted, I would've expected the VDOM diffing to take no action here.

It should be noted that disabling markdown "sanitize" and inserting <img> tags with fixed styling (width / height set to fixed pixel sizes) does *not* stop the flashing. So this isn't an artefact of markdown/css.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

The demo is meant for learning purposes. It uses `v-html`, there is no vdom diffing at all.
