### ISSUE TITLE
Show warning or error when v-for key is undefined

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue#12251]
### What problem does this feature solve?
If you have a duplicate key in v-for or a key that isn't a primitive type, you get a helpful warning in the console in development mode. But if you spell the key name wrong `:key="object.typ"` instead of `:key="object.type"`, the `key` becomes undefined and there's no warning or error, even though all keys are undefined and therefore duplicates.

### What does the proposed API look like?
Same API but with browser console error like is shown for other v-for key errors.

**Comment by posva** [comment]
this is expected, an `undefined` key is the same as not passing the `key` attribute at all. Creating this warning would be problematic for existing users.
