### ISSUE TITLE
Add shorthand for default prop value

### ISSUE THREAD

**Issue by Rednas83** [vuejs/vue#12262]
### What problem does this feature solve?
Higher readabilty for using common attributes (why a shorthand for setting the type and not for setting the default value?)

### What does the proposed API look like?
props {
  title: this.title || this.blok.title || "menu",
}
OR (when conflicting with setting the shorthand for the datatype?)
props {
  title= this.title || this.blok.title || "menu",
}
INSTEAD OF
    title: {
      default: (value) => {
        value || this.blok.title || "menu"
      },
    },

**Comment by posva** [comment]
This wouldn't work because of `this`. Defining a prop based on other props is already in another issue.

**Comment by Rednas83** [comment]
Defining a default value based on another prop value already works for me like this. Why is that an issue? Please re-open because I think this could be a really Nice improvement for readibilty

**Comment by Rednas83** [comment]
@posva Why did you close? I don't see any reason why this couldn't work. Most of time the default attribute is the only one I set. Would it not be great to have a shorthand for that?

Something like:
```
props {
  title: this.title || this.blok.title || "vue",
}
```
Instead of:
props {
  title: {
   default: (value) => {
     value || this.blok.title || "menu"
  },
},
