### ISSUE TITLE
Add 'nonce' option to context for ssr outlet style

### ISSUE THREAD

**Issue by laurencedorman** [vuejs/vue#12267]
### What problem does this feature solve?

Since 2.6.0+, if context.nonce is present, it will be added as the nonce attribute to the embedded script. This allows the inline script to conform to CSP that requires nonce. However, nonce is not currently added to any <style> tags that are generated. This feature would add nonce to the style tags so they can conform to CSP as well.

See this issue for the PR that added the nonce for the script tag : https://github.com/vuejs/vue/pull/8047

### What does the proposed API look like?
No API change. If context.nonce is present, it will be added to both the script tag, and any style tags generated by `vue-server-renderer`

**Comment by posva** [comment]
Is this fixed by https://github.com/vuejs/vue/pull/11826?

**Comment by laurencedorman** [comment]
Oh yes thanks looks like it 👍
