### ISSUE TITLE
Vue Build causes broken deploy with error "cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [vuejs/vue#12269]
### Version
2.6.11

### Reproduction link
[github.com](https://github.com/webpack/webpack/issues/959)

### Steps to reproduce
This is an extremely tricky issue. It happens about once in twelve builds. Clearing the cache usually fixes it, but doesn't always. We are using Vue 2.6.11 with typescript. Here is a link to the webpack issue: https://github.com/webpack/webpack/issues/959 . However, it can't entirely be webpack. I've worked on other projects with webpack and never ran into this issue before. 

It will seemingly randomly do this. I can't seem to peg down why. 

### What is expected?
A successful build to result in working code

### What is actually happening?
About 1/10 times, a build results in an error. 

---
I know this is vague, but if I could successfully reproduce the bug it would be a lot easier to attempt a fix. I'm not just being lazy here

**Comment by posva** [comment]
Unfortunately, it really is impossible to help here with this information. Even less find the origin of the issue and fix it, if it really is within vue code. I recommend you to try on forums or the discord chat

**Comment by JustAnotherSoftwareDeveloper** [comment]
@posva Hey I figured out what's going on. I think it might be specific to my build, but I am going to comment in the event someone else stumbles upon this.

So Webpack generates a file called `chunk-vendors.js`. This works fine until you start hashing your output. When that happens, the main `app.[hash].js` is updated while the `chunk-vendors.js` is cached. If you used new external libraries since your last build, this will cause an error. The new app.js will try to reference the older `chunk-vendors.js` and will error out. 

I ended up fixing it as part of my configureWebpack. Here's the entire thing. Note that it has a lot of stuff to ensure source maps work correctly, and other things that are not needed for this build:

```javascript
    console.log(`Environment: ${process.env.NODE_ENV}`);
    console.log(`API URL: ${process.env.VUE_APP_API_URL}`);

    if (!PROD_ENVIRONMENTS.includes(process.env.NODE_ENV)) {
      config.devtool = "eval-source-map";
      config.output.devtoolFallbackModuleFilenameTemplate =
        "webpack:///[resource-path]?[hash]";
      config.output.devtoolModuleFilenameTemplate = (info) => {
        const isVue = info.resourcePath.match(/\.vue$/);
        const isScript = info.query.match(/type=script/);
        const hasModuleId = info.moduleId !== "";

        // Detect generated files, filter as webpack-generated
        if (
          // Must result from vue-loader
          isVue &&
          // Must not be 'script' files (enough for chrome), or must have moduleId (firefox)
          (!isScript || hasModuleId)
        ) {
          let pathParts = info.resourcePath.split("/");
          const baseName = pathParts[pathParts.length - 1];
          // prepend 'generated-' to filename as well, so it's easier to find desired files via Ctrl+P
          pathParts.splice(-1, 1, `generated-${baseName}`);
          return `webpack-generated:///${pathParts.join("/")}?${info.hash}`;
        }

        // If not generated, filter as webpack-vue
        return `webpack-vue:///${info.resourcePath}`;
      };
    } else {
      console.log("No Source Maps");
      config.devtool = "nosources-source-map";
    }
    const SW_ENVS = ["production", "development"];
    if (!SW_ENVS.includes(process.env.NODE_ENV)) {
      const swPlugin = new GenerateSW({
        cacheId: "courtcall-ui-v3",
        cleanupOutdatedCaches: true,
      });
      config.plugins.unshift(swPlugin);
    }
    config.output.filename = "[name].[hash].js";
    config.output.chunkFilename = "[id].[chunkhash].js";
    console.log("Environment Config");
    const getEnvName = () => {
      if (process.env.NODE_ENV === "production") {
        return "environment.prod.ts";
      } else if (process.env.NODE_ENV === "dev") {
        return "environment.dev.ts";
      } else if (process.env.NODE_ENV === "stage") {
        return "environment.stage.ts";
      } else {
        return "environment.ts";
      }
    };

    const normalModuleReplacementPlugin = new webpack.NormalModuleReplacementPlugin(
      /environments\/environment\.ts/gi,
      `./${getEnvName()}`
    );
    config.plugins.unshift(normalModuleReplacementPlugin);
```

The two important parts are 
```
    config.output.filename = "[name].[hash].js";
    config.output.chunkFilename = "[id].[chunkhash].js";
```

After this, I stopped experiencing these errors.
