### ISSUE TITLE
3.2 使用script setup 模式下无法定义组件name属性

### ISSUE THREAD

**Issue by muziyu0503** [vuejs/vue#12263]
### What problem does this feature solve?
3.2 使用script setup 模式下无法定义组件name属性

### What does the proposed API look like?
能够定义name
```ts
<script lang="ts" setup>
import Page from '@/components/page/page.vue'
import { Card } from 'ant-design-vue'
</script>
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

```vue
<script>
export default {
  name: 'Name'
}
</script>

<script setup>
...
</script>
```
