### ISSUE TITLE
the content isn't destroyed when `$destroy` is used in `new Vue`

### ISSUE THREAD

**Issue by Jim-jw** [vuejs/vue#12268]
### Version
2.6.14

### Reproduction link
[codepen.io/jim-jw/pen/powemmX](https://codepen.io/jim-jw/pen/powemmX)

### Steps to reproduce
const app = new Vue({
    el: '#app',
    },
    data: {
        message: 'Hello Vue!'
    },
});
app.$destroy();

### What is expected?
this page is empty

### What is actually happening?
this page has `Hello Vue!`

**Comment by posva** [comment]
This is expected and has been reported before: you have to remove it yourself
