### ISSUE TITLE
combine v-if and v-show

### ISSUE THREAD

**Issue by signmeuptwice** [vuejs/vue#12274]
### What problem does this feature solve?
Right now we use either or; we cannot use both

But sometime we might want to destroy or hide on a certain condition to save rendering time, etc..

### What does the proposed API look like?
something like v-display(conditionToShowHide, conditionType)
by default if would behave like v-if and switch to v-show when conditionType is true

or just upgrade the existing v-if

We can also condition without a second argument with v-if argument input type:
bool = normal v-if
string = transforms v-if in v-show

**Comment by LinusBorg** [comment]
You can do this:
```html
<template v-if="conditionA">
  <div v-show="condiditionB">

  </div>
</template>
```

**Comment by posva** [comment]
I don't think this needs an implementation inside vue. If you think this is worth adding, open an RFC on the rfcs repository
