### ISSUE TITLE
SFC defineExpose exposes wrong variable name

### ISSUE THREAD

**Issue by Im-Beast** [vuejs/vue#12271]
### Version
2.6.14

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBhYmMgPSAxMjNcblxuZGVmaW5lRXhwb3NlKHtcbiAgYmNkOiBhYmNcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGgyPlxuICAgIHt7IGFiYyB9fVxuICAgIDwhLS0gYmFkOiB7eyBiY2QgfX0gLS0+XG4gIDwvaDI+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59In0=)

### Steps to reproduce
1. create variable
2. expose variable via defineExpose using key name different than variable name

### What is expected?
bcd being exposed variable name

### What is actually happening?
abc is exposed variable name

---
Tried to return id as userId without changing variable name

**Comment by posva** [comment]
defineExpose is for the outside [See this example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG4gIGNvbnN0IGVsID0gcmVmKClcbiAgb25Nb3VudGVkKCgpID0+IHtcbiAgICBjb25zb2xlLmxvZyhlbC52YWx1ZS5iY2QpXG4gIH0pXG5pbXBvcnQgQ29tcCBmcm9tICcuL0NvbXAudnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENvbXAgcmVmPVwiZWxcIi8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IGFiYyA9IDEyM1xuXG5kZWZpbmVFeHBvc2Uoe1xuICBiY2Q6IGFiY1xufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8aDI+XG4gICAge3sgYWJjIH19XG4gICAgPCEtLSBiYWQ6IHt7IGJjZCB9fSAtLT5cbiAgPC9oMj5cbiAgPGlucHV0IHYtbW9kZWw9XCJtc2dcIj5cbjwvdGVtcGxhdGU+In0=)

BTW, this repo is for Vue 2.
