### ISSUE TITLE
Allow variables starting with underscore.

### ISSUE THREAD

**Issue by turbosheep44** [vuejs/vue#12270]
### What problem does this feature solve?

Currently a warning is displayed when variables are declared with a leading underscore like `_price`.

This issue is asking that the Vue team reconsider #5879  which basically made the following points. Using underscores `_` and dollar symbols `$` is a common convention in JS and TS and it seems unnecessary that *both* should be restricted for Vue internals. Another frustrating point, is that double underscores also cannot be used because of course the name would still start with an underscore, for example `__price`.

### What does the proposed API look like?

By refactoring Vue internals to use a double underscore instead of a single underscore this would allow developers to use single underscores for prefixes in their own code.

Ideally this would be done before Vue 3 becomes the latest stable version.

**Comment by posva** [comment]
And mentioned in the other issue this won't happen
