### ISSUE TITLE
props中的数据已经更新到data中，而且data时深度监听props中的数据，再利用vue.set(this.$set)，视图没有更新，目前问题时视图没更新，监听的时数组变化

### ISSUE THREAD

**Issue by littlegreay** [vuejs/vue#12273]
### Version
2.6.10

### Reproduction link
[ats-exp.51zhaopin.cn/](https://ats-exp.51zhaopin.cn/#/pc/resume/detail?resumeId=163091888336113)

### Steps to reproduce
页面数据通过上一页下一页翻页，更新数据，之后视图变化，深度监听props中的数据（数组），更新到data中，data中的数据是通过vue.set赋值的，而且data中的数据是有更新到，但是视图没有更新

### What is expected?
深度监听props中的数据（数组），更新到data中，data中的数据是通过vue.set赋值的，而且data中的数据是有更新到，但是视图没有更新

### What is actually happening?
深度监听props中的数据（数组），更新到data中，data中的数据是通过vue.set赋值的，而且data中的数据是有更新到，视图做相应的更新

**Comment by posva** [comment]
That's not a valid repro
