### ISSUE TITLE
Custom Validator is running after Computed Property

### ISSUE THREAD

**Issue by AllanOricil** [vuejs/vue#12288]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/AllanOricil/vue-virtual-picklist)

### Steps to reproduce
1 - yarn install
2 - yarn serve
3 - Add a breakpoint inside the Options Validator
4 - Add a breakpoint inside the availableOptions computed property
5 - Refresh the page and verify that the availableOptions computed property was reached before the Validator function

### What is expected?
the validator function should run before the computed property

### What is actually happening?
the validator function runs after the computed property

---
Related https://github.com/vuejs/vue/issues/12286

**Comment by AllanOricil** [comment]
@posva you can use this project to debug

**Comment by posva** [comment]
Please provide a boiled down repro like asked in the issue helper

**Comment by AllanOricil** [comment]
@posva could you explain why the simple project I shared here inst a "boiled down repro"?
It has only one component and the app for you to debug.
