### ISSUE TITLE
Add shorthand for default prop value

### ISSUE THREAD

**Issue by Rednas83** [vuejs/vue#12283]
### What problem does this feature solve?

Easier syntax for setting the most common attribute (why a shorthand for setting the type and not for setting the default value?)

### What does the proposed API look like?
```
props {
  title: this.title || this.blok.title || "vue",
}
```
Replacing :
```
props {
  title: {
    default: (value) => {
    value || this.blok.title || "menu"
  },
},
```

**Comment by posva** [comment]
This isn't possible. The this keyword doesn't work like that

**Comment by Rednas83** [comment]
That's  the whole point. Using a shorthand Will replace the function where it is possible to use this.
