### ISSUE TITLE
[typescript] Properties with `default` value should not have "... | undefined" type

### ISSUE THREAD

**Issue by larvanitis** [vuejs/vue#12289]
### What problem does this feature solve?
When using TypeScript, any prop that has a default value is still inferred as `<Type> | undefined`.

For example:

1. Create a component
2. Add a property with `type: Number` and `default: 5`, while not `required: true`

Expected: the prop type to be `number`
Actual: the prop type is `number | undefined`

```vue
<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    testProp: {
      type: Number,
      default: 5,
    },
  },
  mounted() {
    this.testProp; // testProp: number | undefined
  },
});
</script>
```

This is reproducible in
- vue 2.6.14
- vue 3.2.12
- @vue/composition-api 1.1.5

### What does the proposed API look like?
The types should account for a defined `default`, the way they account for `required: true`.

**Comment by posva** [comment]
Open a new issue with an actual repro for Vue 3 or for Vue 2 in the Vue repo instead
