### ISSUE TITLE
Writing renderless components with <script setup> syntax

### ISSUE THREAD

**Issue by dmitriykorobkov** [vuejs/vue#12281]
### What problem does this feature solve?
For now, there isn't any possibility to write `<script setup>` SFC without template. I have to write old syntax setup function with `return () => null;`
I'm using renderless components for modifying behavior of components, which contains first ones as slots. 

### What does the proposed API look like?
I think, nothing should be changed. If there is no `<template>` section, compiler infer `() => null` as render function.

**Comment by posva** [comment]
See https://github.com/vuejs/vue-next/issues/17#issuecomment-441552397

**Comment by dmitriykorobkov** [comment]
@posva How [this](https://github.com/vuejs/vue-next/issues/17#issuecomment-441552397) comment helps to solve my issue?

**Comment by posva** [comment]
We want to keep the behavior explicit because of what the comment says

**Comment by dmitriykorobkov** [comment]
@posva How and where can I write/return noop render function using `<script setup>` syntax?

**Comment by posva** [comment]
Use an empty [`template`](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9)
