### ISSUE TITLE
Provide Vue version in default export

### ISSUE THREAD

**Issue by AustinGil** [vuejs/vue#12287]
### What problem does this feature solve?
As a library author, it's hard to know what version of Vue is running on both v2 and v3. 

Vue 2 provides the following:
```
import Vue from 'vue'
console.log(Vue.version)
```

Vue 3 offers
```
import { version } from 'vue'
console.log(version)
```

But it's hard to use a system that works for both. Version 3 does not have a default export, so trying to use `Vue` leads to warnings or ""export 'default' (imported as 'Vue') was not found in 'vue'"

A similar warning happens with trying to get `version` from named exports in a version 2 project.

My proposed solution would be to add a default export to Vue 3 that provides some context.

### What does the proposed API look like?
From the main Vue.js entrypoint
```js
export default {
  version: {vue version imported from package.json}
}
```

**Comment by posva** [comment]
This makes more sense in Vue Demi
Vue 3 simply doesn't have a default export, it would be misleading to have one for migrating apps

**Comment by AustinGil** [comment]
Well, this isn't a migration app. It's for [Vuetensils](https://vuetensils.stegosource.com/). I'm trying keep it compatible for both Vue 2 and 3, but I haven't found a reliable way. I've seen Vue Demi and it looks nice, but I'd rather not bring in a 3rd party library just for this.

If you have any other ideas on how it might be accomplished to check whether the installed Vue version is 2 or 3 (either would work) I'd love to hear it. Best I got right now is checking for the version from the named export. The only down side is that it causes a warning in the console, but it works alright. But I also know people will file GitHub issues for that :/

**Comment by posva** [comment]
Using Vue Demi is really the recommended approach 🙂
Its size is empty at the end!
