### ISSUE TITLE
2.6.13 release changelog typo in nbsp

### ISSUE THREAD

**Issue by Ariane-B** [vuejs/vue#12297]
### Version
2.6.13

### Reproduction link
[github.com](https://github.com/vuejs/vue/releases/tag/v2.6.13)

### Steps to reproduce
1. Read the issue

### What is expected?
The following element:

compiler: avoid converting &nbps; to spaces (#11065) 55a30cf, closes #11065

Should say "nbsp"

### What is actually happening?
It says nbps

---
Pretty minor but I was Ctrl-F-ing the releases to see if anything included the nbsp fix and wasn't finding anything. Might be worth fixing the typo.

**Comment by posva** [comment]
Fixed

**Comment by Ariane-B** [comment]
Thanks! :)On Sep. 26, 2021 15:56, Eduardo San Martin Morote ***@***.***> wrote:
Fixed
