### ISSUE TITLE
Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined

### ISSUE THREAD

**Issue by Juken8104** [vuejs/vue#12293]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/Juken8104/monorepo-test)

### Steps to reproduce
I create a monorepo by lerna.then I create vue2 project and vue3 project in packages. when I ren the vue2 project and vue3 project. They can run success. And then I create vue3 project wiht typescript.The vue2 project run failded. The  vue3 project and another vue3 project wiht typescript run success

### What is expected?
the vue2 project run success

### What is actually happening?
the vue2 project run faild

**Comment by Juken8104** [comment]
I use yarn to manage packages

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by YXYH-12138** [comment]
我更新vue-template-compiler就行了
