### ISSUE TITLE
Vue.set Unable to update properties in the middle of the prototype chain

### ISSUE THREAD

**Issue by zjruan** [vuejs/vue#12299]
### Version
2.6.14

### Reproduction link
[codepen.io/zjruan/pen/qBjLrJr](https://codepen.io/zjruan/pen/qBjLrJr)

### Steps to reproduce
1. click first button, you will find the button text change
2. click second button, Nothing happened
3. click first button again, both button text change 

### What is expected?
name and age both reactive

### What is actually happening?
only name is reactive

---
// src/core/observer/index.js:212  
if (key in target && !(key in Object.prototype)) 

I don’t know if this is a deliberate design, but for inherited objects, there will be some unexpected operations. The key is that the official website document does not specifically point out this.  
Why do we check  Object.prototype and not use target.hasOwnProperty(key)

**Comment by liyongning** [comment]
这里其实不是一个 bug，Vue2 响应式模块的设计本身就不对原型对象上的数据做响应式处理，而且只对对象自身已经存在的数据做监听，比如你的 this.peo.name，但是 this.peo.age 就不行，因为 age 属性在原型对象上，所以 Object.defineProperty 就无法监听 age 属性。

至于判断 key in Object.prototype 是为了防止 key 是 Object 对象上的原生属性

这里有两种解决方案：

1、改动你的代码
    `
    const ani = { name: 'ani', age: 0 };
    const peo = JSON.parse(JSON.stringify(ani));
    `
2、改动源码，把 `/src/core/observer/index.js` 中 214 行的 `return val` 去掉，也能解决问题

建议采用第一种方案，因为第二种需要改源码，而且这个改动会违背 Vue 响应式模块本身的设计

**Comment by zjruan** [comment]
我的意思是:
> src/core/observer/index.js:212

为什么要这样写
```javascript 
if (key in target && !(key in Object.prototype))
```
而不是，写成这样
```javascript
if (key in target && target.hasOwnProperty(key))
```
这么写的目的是什么？毕竟向子类实例添加属性时，属性最终是添加到子类实例上的。
不过，采用上面的写法，添加的是非响应属性
采用下面的写法，添加的是响应属性。

类的继承，在开发的过程中，是很常见的。那么我在实例化子类的时候，不对所有父类属性 `overwrite ` 也是合理的述求。
在运行的过程中，修改的自己的属性，也是正常的述求。
不过现在直接修改，是非响应式的。那么我们第一反应，肯定是使用 `Vue.set` 方法。
但是这个方法，也不能满足我们的要求。
然而，这时候我们去官网查看 API，你会发现，API 里面也没有相应的描述，去指出这点。
![image](https://user-images.githubusercontent.com/12164900/135212733-e0d5052d-1bc2-4041-8fdf-cb120cc890de.png)

如果你安装了 `vue.js devtools` 插件的话，你会发现，其实属性已经添加到对象上了，只不过这个对象是非响应式的，这点与文档描述不符。

我是不明白这么设计的初衷是什么？如果真有一些特殊原因，那么也应该去修改一下官方文档，将这个点作为**注意事项**放在接口文档下面

**Comment by liyongning** [comment]
![image](https://user-images.githubusercontent.com/26913352/135474837-4f80ffe6-99d1-4244-9d99-1065cae8956c.png)

先说使用方式，data API 说了原型对象上的属性会被忽略，所以不建议用继承，因为继承的属性都在原型对象上；而且示例中的代码也是用了继承后在对象自身上覆写了属性，所以在这里使用继承没什么意义；另一个问题就是假设支持响应式继承而来的属性，那原型对象上的属性会被多个 Vue 实例公用，也有点违背单文件组件中 data 属性建议为函数的目的。所以像你真有继承的需求，建议直接用深拷贝去解决。

另一个问题，源码中为什么不是 target.hasOwnProperty(key)，而是 key in Object.prototype，仔细想想，我觉得这个要求可以有

**Comment by liyongning** [comment]
所以，总结就是，我觉得源码可以改（优化），但是使用上还是不建议用继承，真有继承的需要，直接用深拷贝实现

**Comment by zjruan** [comment]
这个 `Issue` 确实不是一个 bug，它的本质是在讨论，从设计角度出发，思考下面这句代码的用意是什么？
```
if (key in target && !(key in Object.prototype))
```

从我的角度来看，`if (key in target && target.hasOwnProperty(key))` 这样写更好，可以让 `Vue.set` 更符合它的 api 人设 
>向响应式对象中添加一个 property，并确保这个新 property 同样是响应式的，且触发视图更新。

就像数组一样，我们知道直接修改数组，是不能触发视图更新，同样的，通过 data api 文档，我们也知道了，原型上的属性是不具备响应式的。那么我们有没有办法修改这些属性的时候，触发更新呢？
注意：这里没有说要原型上的属性具有响应式，而是说通过 `Vue.set` 方法，向对象上添加具有响应式的属性，去覆盖原型属性。

不过，目前的实现方式，是不具备这种能力的，那么，是出于什么目的，放弃了这种能力，还是有什么顾忌。或者是当时设计的时候没有考虑到这种场景。
