### ISSUE TITLE
Proposed shorthand for v-model

### ISSUE THREAD

**Issue by warrensearle** [vuejs/vue#12300]
### What problem does this feature solve?
Vue provides special shorthands for two of the most often used directives, `v-bind` and `v-on`. [See here](https://v3.vuejs.org/guide/template-syntax.html#shorthands)

`v-model` is also an often used directive and in Vue 3 it's usage will increase now that we have arguments and a replacement for two-way binding using `.sync`. [See here](https://v3.vuejs.org/guide/migration/v-model.html#_3-x-syntax)

Here we propose a shorthand for `v-model` with and without arguments

### What does the proposed API look like?
**`v-model` Shorthand**
```
<!-- full syntax -->
<ChildComponent v-model="pageTitle" />

<!-- shorthand -->
<ChildComponent ::="pageTitle" />
```

**`v-model` with argument Shorthand**
```
<!-- full syntax -->
<ChildComponent v-model:title="pageTitle" />

<!-- shorthand -->
<ChildComponent ::title="pageTitle" />
```

This means the three shorthands are `:` for one-way binding `::` for two-way binding
 and `@` for events

**Comment by posva** [comment]
Open a discussion or PR in the rfcs repository.

**Comment by warrensearle** [comment]
Ok, thanks @posva
