### ISSUE TITLE
Can't Use Sass Variables In Globally, Without Sass Loader

### ISSUE THREAD

**Issue by QusayAL-Sherbi** [vuejs/vue#12304]
### What problem does this feature solve?
Use Sass Variables Easily, Without Sass Loader

### What does the proposed API look like?
Good

**Comment by Justineo** [comment]
I'm sorry but this is not a valid feature request.

**Comment by QusayAL-Sherbi** [comment]
OK. Thank Your So Much, I hope you more success for VueJs project.
**I Wish From VueJs Development Team, Fix This Issue, In Order To Use Sass Globally Variables With VueJS, In Easily Way.**
Thank You.

**Comment by LinusBorg** [comment]
Again, there is nothing to "fix".
