### ISSUE TITLE
Transition group not working as expected

### ISSUE THREAD

**Issue by bitbytebit1** [vuejs/vue#12302]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/bitbytebit1/nuxt-starter-msd6ze)

### Steps to reproduce
Click on "activate navbar"

### What is expected?
The items should be staggered and animated correctly

### What is actually happening?
The items are staggered however not animated correctly

---
slide-x isn't being removed, removing all code from the hooks in TransitionGroupStaggered fixes animation issue, however then the items are not staggered
Here is a stackblitz link to the repo
https://stackblitz.com/edit/nuxt-starter-msd6ze

**Comment by posva** [comment]
Hi, this is a question about how to get your own animation working as you want. Please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by bitbytebit1** [comment]
Sorry, but I feel you were too quick to judge here, something is clearly not right with transition-group. It is working exactly as expected in one scenario however completely failing in another with no discernible difference in the code. I have looked at this for a long time and see absolutely no reason as to why it should fail in the second scenario.

The transition never finishes, the classes aren't removed. If this is some sort of obscure intended behavior this should be in the documentation. 

Please download the repro and try locally.
