### ISSUE TITLE
No documentation on how to watch a prop in Composition API

### ISSUE THREAD

**Issue by mzenz** [vuejs/vue#12313]
### What problem does this feature solve?
There's not a single mention in the docs about how to watch for mutations to a component's prop, making users go on a wild goose chase for ways to accomplish this. Thanks.

### What does the proposed API look like?
A section on both Composition API and <script setup> section documentation describes the watch() API and how to monitor component props' mutations.

**Comment by posva** [comment]
There are examples and explanations on how to use watch. If you have improvement proposals, open a pr to the docs repository.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
