### ISSUE TITLE
flushCallbacks function in file vue.esm.js  takes long time 

### ISSUE THREAD

**Issue by MisherLiu** [vuejs/vue#12323]
### Version
2.5.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/sweet-sunset-ieylf?file=/src/components/HelloWorld.vue:11500-11512)

### Steps to reproduce
1. Main code in sandbox, however it cannot run correct as I use CDN to load fundamental library.
2. Run Perfromance in google devtool
![image](https://user-images.githubusercontent.com/64764287/137083456-71b59145-bf3b-4282-9d8f-e8904f048677.png)

### What is expected?
Expect suggestion on :
What case flushcallback function takes long time
How can improve this

### What is actually happening?
function flushCallbacks () in vue.esm.js  takes long time.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
