### ISSUE TITLE
Style conflicts caused by using v-if and custom directives at the same time

### ISSUE THREAD

**Issue by KID-joker** [vuejs/vue#12352]
### Version
2.5.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/hopeful-roentgen-rp1x3)

### Steps to reproduce
1. click the white button
2. v-wide will change the backgroundColor

### What is expected?
The second popup's backgroundColor should be blue

### What is actually happening?
The popup's backgroundColor is red that is the previous one

---
I use v-if and a custom directives to update the inline style at the same time. when the next element is displayed, it will inherit the style of the previous one. And the displayed element doesn't trigger the inserted lifecycle.

**Comment by LinusBorg** [comment]
Use a `key` attribute to make sure that a new element is being created instead of the old one being re-used.

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key
