### ISSUE TITLE
Memory leak ??

### ISSUE THREAD

**Issue by ovaldi** [vuejs/vue#12358]
### Version
2.6.14

### Browser

MacOS, Chrome 96.0.4664.45

### Reproduction link
https://jsfiddle.net/ToBeBest/n4gtcpea/

### Steps to reproduce

1. Click the `Sign` button
2. Chrome DevTools - Memory - Take heap snapshot (Select JavaScript VM instance:  fiddle.jshell.net)
3. Filter by `Detached HTMLButtonElement`
4. Now you can see the detached button as below

![image](https://user-images.githubusercontent.com/4537336/141889676-6647bc51-ada0-4f88-957b-5e8fa0a52186.png)

![image](https://user-images.githubusercontent.com/4537336/141889624-ddf1a2ef-4f82-4843-b515-d7225fa0182b.png)

### What is expected?
Vue should release the button

### What is actually happening?
The button shows in `Detached HTMLButtonElement`

**Comment by ovaldi** [comment]
It seems related to this [chrome bug ](https://bugs.chromium.org/p/chromium/issues/detail?id=1177010)

**Comment by LimeFavorCat** [comment]
I've tested it in Windows environment
and the same thing happens.

**Comment by ota-meshi** [comment]
I think it maybe the fix has been merged but it hasn't been released yet.
#10085

**Comment by Kamandlou** [comment]
It's ok on Firfox.

**Comment by yyx990803** [comment]
Fixed by #10085
