### ISSUE TITLE
the diff algorithm of Vue2， when add element to Array ,the Key  does not take effect

### ISSUE THREAD

**Issue by shenjunjian** [vuejs/vue#12357]
### Version
2.6.14

### Reproduction link
[gitee.com](https://gitee.com/40288193/test-the-diff-of-vue)

### Steps to reproduce
1、prepare the Data and methods
 let list = Array.from(Array(15)).map((v, i) => {
            return { id: "id" + (i + 1), title: "item " + (i + 1) }
        })
        let start10 = list.slice(0, 10)
        let end10 = list.slice(5, 15)
2、 bind to <template>
<tr v-for="item in display" :key="item.id">
                    <td>{{item.id}}</td>
                    <td>{{item.title}}</td>
 </tr>
3、trigger the method :   toggle. 

### What is expected?
the key take effect

### What is actually happening?
when data toggle from start10  to  end10,  all element recreated

---
please see  my demo :  https://gitee.com/40288193/test-the-diff-of-vue

**Comment by posva** [comment]
This is documented as a caveat in docs and is expected.
