### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by zidingz** [vuejs/vue#12351]
Hey there!

I belong to an open source security research community, and a member (@geeknik) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by posva** [comment]
@zidingz Please, follow https://v3.vuejs.org/guide/security.html#reporting-vulnerabilities for the time being

**Comment by JamieSlome** [comment]
@posva - thanks for the info! An e-mail was just sent ❤️
