### ISSUE TITLE
Vue template compiler : this to _vm auto compile feature please .

### ISSUE THREAD

**Issue by parsher** [vuejs/vue#12362]
### What problem does this feature solve?

```


const COMMAND = { 
TREND: {
LIST: "DATA_LIST"
}
};

data() {
    return {
        COMMAND: COMMAND.TREND
     }
}

<v-data-table
          fixed-header
          dense
          :headers="tableHeaders"
          :items="tableDataList"
          :header-props="{ 'sort-icon': 'mdi-arrow-up' }"
           :items-per-page.sync="this[COMMAND.LIST].pageSize"/>

```
        

============

Problem : Vue template compiler does not compile this to _vm
> lose link to _vm

"update:itemsPerPage": function($event) {
                        return _vm.$set(
                          this[_vm.COMMAND.PAGE_INFO],
                          "pageSize",
                          $event
                        )
                      },
                      "update:items-per-page": [
                        function($event) {
                          return _vm.$set(
                            this[_vm.COMMAND.PAGE_INFO],
                            "pageSize",
                            $event
                          )
                        },
                        _vm.search
                      ],

### What does the proposed API look like?
"update:itemsPerPage": function($event) {
                        return _vm.$set(
                          _vm[_vm.COMMAND.PAGE_INFO],
                          "pageSize",
                          $event
                        )
                      },
                      "update:items-per-page": [
                        function($event) {
                          return _vm.$set(
                            _vm[_vm.COMMAND.PAGE_INFO],
                            "pageSize",
                            $event
                          )
                        },
                        _vm.search
                      ],

**Comment by posva** [comment]
Never use this in templates

**Comment by parsher** [comment]
@posva Thanks, but is there any way to use sync properly using CONST variable as a name to access data?

**Comment by posva** [comment]
You can use a computed property or a method

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
