### ISSUE TITLE
Open a Vue for the elderly, called Older people or old-Vue.js

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [vuejs/vue#12368]
### What problem does this feature solve?
Around the world, screens dazzle the elderly, optimize services for the elderly and improve their quality.
Not only that, it can also make wechat and short video more focused on the elderly
可以解决中国(China)老人使用手机，对于手机屏幕不太娴熟，看的眼花缭乱，需要字体放大，更好的排版。
对于微信(WeChat)、快手、抖音、QQ、都建议引用 Old People Vue

### What does the proposed API look like?
Open a new library or one more class to redesign the typesetting of the exclusive elderly. I especially recommend such a humanized design, because serving the elderly has won more social attention, so that more people fall in love with Vue, and it has changed from three words to four, and the fourth is called "love"
新开一个库，或者多一个类，重新设计专属老人的排版。我特别推荐这样人性化的设计，因为服务老人赢得更多社会的关注，从而更多人爱上Vue，还有让它 从 三个词语变成四个，第四个叫做"关爱"

**Comment by Justineo** [comment]
Sorry but this is beyond the scope of Vue. You are free to design your application this way.
