### ISSUE TITLE
watch props not trigger in Child BUT in Parent

### ISSUE THREAD

**Issue by wfk007** [vuejs/vue#12367]
### Version
2.6.14

### Reproduction link
[github.com/wfk007/test-vue](https://github.com/wfk007/test-vue)

### Steps to reproduce
1. npm install 
2. npm run serve
3. visit http://localhost:8080/
4. click the button：add a field in item
5. see chrome dev console log

### What is expected?
console log：child props childProps update

### What is actually happening?
no log info

**Comment by posva** [comment]
This is expected: you are setting with `$set()` which recursively makes the whole object reactive and the parent is looking at it through a property: `object.property` while the child has direct access to it so it doesn't trigger because it's the same object

**Comment by wfk007** [comment]
> This is expected: you are setting with `$set()` which recursively makes the whole object reactive and the parent is looking at it through a property: `object.property` while the child has direct access to it so it doesn't trigger because it's the same object

**thx very much！** I got new understanding of responsiveness in vue2, especially the behavior in props
