### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by AncientFairy** [vuejs/vue#12365]
### What problem does this feature solve?
Can you provide the starter of the locked version, similar to the SpringBoot in Java? In other words, many components are easy to use in vue 2 version and may not be easy to use in vue 3 version. If I use the official starter, then I will no longer worry about the version of each component. Of course, this will increase the official work and is just a suggestion.

### What does the proposed API look like?
no

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
