### ISSUE TITLE
想通过babel修改template编译后的render函数

### ISSUE THREAD

**Issue by wulinsheng123** [vuejs/vue#12363]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/wulinsheng123/vue/blob/main/src/App.vue)

### Steps to reproduce
https://github.com/wulinsheng123/vue/blob/main/src/App.vue

### What is expected?
能获取render函数，并且能修改render函数

### What is actually happening?
通过webpack能获取到render函数，但是修改不了render函数

---
公司内部有2个ui框架elementUI和Ivivew，现在希望通过编译将elementUI转义为Iview UI框架。现在想法是通过拦截到render函数，然后通过babel编译，将ELementUI 转为IviewUI。只能通过webpack hook去拦截vue的render函数，但是vue生产的render时间比较特别，我想修改这个render就会报错
之前已经留言给了webpack，但是webpack觉得应该问vue-开发 ,
webpack/webpack-sources#141

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
