### ISSUE TITLE
There is a different point with Vue Document (v-for, v-if) 

### ISSUE THREAD

**Issue by Gkuer** [vuejs/vue#12378]
### Version
2.6.14

### Reproduction link
[https://github.com/gkuer](https://github.com/gkuer)

### Steps to reproduce
in https://v3.vuejs.org/guide/list.html#v-for-with-v-if,
'When they exist on the same node, v-if has a higher priority than v-for' 

in https://vuejs.org/v2/guide/list.html#v-for-with-v-if,
'When they exist on the same node, v-for has a higher priority than v-if'

they mean antonym each other.
the translation (ex. korean) also same state.

### What is expected?
they mean antonym each other.

### What is actually happening?
the translation (ex. korean) also same state.

---
in korean, 
'When they exist on the same node, v-if has a higher priority than v-for'
=== ' 동일한 노드에 두가지 모두 있다면, v-if가 v-for보다 높은 우선순위를 갖습니다. '

my github is 'https://github.com/gkuer'
if it may help to you, please add me to contributer. thank you!

**Comment by posva** [comment]
https://v3.vuejs.org/guide/migration/v-if-v-for.html
