### ISSUE TITLE
Tree Shaking Not working when using Vue.Extend

### ISSUE THREAD

**Issue by TomSmith27** [vuejs/vue#12384]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/TomSmith27/test-cli-esm)

### Steps to reproduce
* Create a Vue 2 project with Vite and typescript
* Add A component that uses Vue.extend (required for typescript)
* Make the Vite Config use lib mode
* Run a build
* Run npx agadoo
* Notice how it says not tree shakeable
* Notice how it says the failed to tree shake

### What is expected?
Vite should create a tree shakable library

### What is actually happening?
Vite doesnt create tree shakable library

**Comment by posva** [comment]
You need to mark Vue as external

—-

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by TomSmith27** [comment]
Hi in my example it is marked as external in the vite.config no?
