### ISSUE TITLE
Data proxy adds error handling

### ISSUE THREAD

**Issue by linjiahao962889027** [vuejs/vue#12397]
### What problem does this feature solve?
When using API to obtain data asynchronously, if deep data is used in the template, an error is often reported and execution cannot continue. It is hoped that an error handling proxy can be added, and undefined will be returned when an error occurs.

### What does the proposed API look like?
```javascript
function getDeepObjectValue(obj, path) {
    if (Array.isArray(path)) {
        path = path.join(".");
    }
    if (!obj) return undefined;
    try {
        if (!path) return obj;
        return path.split(".").reduce((o, i) => o[i], obj);
    } catch (error) {
        return undefined;
    }
}
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

—-

you likely need to add v-if in the template to check of an object being truths as you would in js

**Comment by linjiahao962889027** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
> 
> —-
> 
> you likely need to add v-if in the template to check of an object being truths as you would in js
It will report error when
```HTML
<el-row>
      <el-col :span='6'>
          <div class="description">
              <div class="description-label-1">name：</div>
              <div class="content-1">{{reviewData.library_data.sample_info.name}}</div>
          </div>
      </el-col>
<el-row>
```
![image](https://user-images.githubusercontent.com/46292984/146891608-acbae61f-4717-400a-a49d-1da992814c80.png)
It will be OK, when
```HTML
<el-row>
    <el-col :span='6'>
        <div class="description">
            <div class="description-label-1">患者姓名：</div>
            <div class="content-1">{{getVal('library_data.sample_info.name')}}</div>
        </div>
    </el-col>
</el-row>
```
So I hope the program can continue to run when an error is reported, because the data will be obtained soon. Because Vue uses a proxy, you can add an error handler and return undefined by default.
