### ISSUE TITLE
How to keep vue page status in a vue page which have a  iframe inside in it  between tab switch

### ISSUE THREAD

**Issue by minicloudsky** [vuejs/vue#12399]
### What problem does this feature solve?
I have two pages (tabA and tabB) using vue and vue-router,iview,user can switch tabs between tabA and tabB,tabA is a normal vue page,tabB is a vue page which includes iframe inside in tabB,when I switch to tabA and then click to back to tabB,however,tabB's iframe inside was refreshed,How can i keep tabB's iframe status and don't refresh between tab switchs,I tried <keep-alive>,however,It is useless, So what should I do to keep tabB's iframe status between tab switchs?

### What does the proposed API look like?
My pages like this:
```html
tabA

<template>
  <div>
    <Card>
      something...  
    </Card>
  </div>
</template>
```
tabB
```html
<template>
  <div>
    <Card>
      <div >
      <iframe  src="xxx.com">
  something
      </iframe>
        </div>
    </Card>
  </div>
</template>
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
