### ISSUE TITLE
cannot access

### ISSUE THREAD

**Issue by Im-Sue** [vuejs/vue#12392]
### Version
2.6.11

### Reproduction link
[cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js)

### Steps to reproduce
https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js

cannot access

### What is expected?
cannot access

### What is actually happening?
cannot access

**Comment by LinusBorg** [comment]
Works fine for me, must be your connection. We can't solve a connection problem between your and a CDN like JSDelivr.

**Comment by Im-Sue** [comment]
Try to clean up your browser cache and try again

**Comment by Im-Sue** [comment]
> Works fine for me, must be your connection. We can't solve a connection problem between your and a CDN like JSDelivr.

Try to clean up your browser cache and try again

**Comment by Enhoo** [comment]
I also have this problem

**Comment by Justineo** [comment]
It breaks at my place (in China) too. But as @LinusBorg said, it is a problem of JSDelivr itself. Maybe we should a little longer to see if they managed to fix this before we look for some alternative CDN service.
