### ISSUE TITLE
can't open vue from https://cdn.jsdelivr.net/npm/vue@v2.6.10

### ISSUE THREAD

**Issue by yanglei0321** [vuejs/vue#12394]
### Version
2.6.10

### Reproduction link
[cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/vue@v2.6.10)

### Steps to reproduce
Our project cannot be accessed because vue cannot be obtained from https://cdn.jsdelivr.net/npm/vue@v2.6.10，Copying the link to the browser will report an error

google chrome error info：
cdn.jsdelivr.net 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 cdn.jsdelivr.net 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 cdn.jsdelivr.net，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 cdn.jsdelivr.net，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

### What is expected?
can visit

### What is actually happening?
Not accessible

**Comment by Justineo** [comment]
Duplicate of #12392
