### ISSUE TITLE
Vue 3 is unfriendly to VSCode auto-import

### ISSUE THREAD

**Issue by ilyub** [vuejs/vue#12396]
### What problem does this feature solve?
For example, VSCode finds "InjectionKey" in "@vue/runtime-core" when it is actually located in "vue".
When you click on menu item showing "InjectionKey" VSCode does nothing.

![Screenshot](https://user-images.githubusercontent.com/70687432/146801523-ff930741-c51c-47f4-8c8a-04af734acd82.jpg)

### What does the proposed API look like?
Organize vue structure so that it does not mislead VSCode.

**Comment by posva** [comment]
This issue has been reported to the TypeScript repo already.
