### ISSUE TITLE
vue3.0 怎么获取router-view渲染后的component组件实例?

### ISSUE THREAD

**Issue by sc544177047** [vuejs/vue#12400]
### Version
2.6.14

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiLy8gcGFyZW50XG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgY2hpbGQgPSByZWYoKTtcbmNvbnN0IG9uQ2xpY2sgPSAoKT0+e1xuICAvLyBjaGlsZC52YWx1ZS5zaG93ICAgIHVuZGVmaW5lZFxuICBjaGlsZC52YWx1ZS5zaG93KClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxyb3V0ZXItdmlldyByZWY9XCJjaGlsZFwiPjwvcm91dGVyLXZpZXc+XG48L3RlbXBsYXRlPlxuXG4vLyBjaGlsZFxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHNob3cgPSAoKT0+e1xuICAvLyBubyBydW4gaGVyZVxuICBjb25zb2xlLmxvZygnUnVuJylcbn1cbmRlZmluZUV4cG9zZSh7XG4gIHNob3dcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIHJvdXRlckNvbXBvbmVudFxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=)

### Steps to reproduce
代码：
<router-view ref="child" v-else></router-view>

vue2.0通过this.$refs.child可以直接调用渲染后子组件里的methods的方法
vue3.0通过 let child= ref() 获取到的没有子组件expose的属性或方法

### What is expected?
像vue2.0一样能拿到router-view渲染的组件里 的方法和属性

### What is actually happening?
实际上无法获取到router-view 后的子组件expose的方法和属性

---
想在最外层包裹 统一实现下拉刷新，然后调用子组件的通用刷新方法（子组件响应内部逻辑处理），用的router-view跳转的，vue2是可以的 vue3刚试了不行  直接引入组件可以

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to use the ref on the `<component>` with the v-slot api:

```vue
<router-view v-slot="{ Component }">
  <component :is="Component" ref="someRefName" />
</router-view>
```
