### ISSUE TITLE
Unable to use interfaces in `defineProps` when the props object is required

### ISSUE THREAD

**Issue by illright** [vuejs/vue#12401]
### Version
3.2.26

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSc7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Q29tcCBtc2c9XCJIZWxsbywgV29ybGQhXCIgLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIkNvbXAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIj5cbiAgZXhwb3J0IGludGVyZmFjZSBQcm9wcyB7XG4gICAgbXNnOiBzdHJpbmc7XG4gIH1cbjwvc2NyaXB0PlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuICAvLyBpdCB3b3JrcyBpZiBJIGRlZmluZSBgUHJvcHNgIGhlcmUsIGJ1dCB0aGVuIEkgY2FuJ3QgZXhwb3J0IGl0XG4gIC8vIGl0IGFsc28gd29ya3MgaWYgSSBvbWl0IHRoZSBgY29uc3QgcHJvcHMgPSBgLCBidXQgdGhlbiBJIGNhbid0XG4gIC8vICAgY3JlYXRlIGNvbXB1dGVkIHByb3BzXG4gIGNvbnN0IHByb3BzID0gZGVmaW5lUHJvcHM8UHJvcHM+KCk7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU+In0=)

### Steps to reproduce
Navigate to the `Comp.vue` file and witness a syntax error after compilation.

### What is expected?
`defineProps` compiles away to a valid expression that can be assigned to a variable and used in computed props

### What is actually happening?
The code doesn't compile

---
As mentioned in the comment in the playground, the code compiles if:
* I define `Props` here, but then I can't export it
* I omit the `const props = `, but then I can't create computed props

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
this has already been reported in Vue-next repo

**Comment by illright** [comment]
@posva Sorry for that. I didn't realize that the development of Vue 3 is carried out in a separate repository. I was actually confused when trying to file this issue for the same reason. And that explains why I didn't find anything while searching through the issues.

Moving forward, perhaps it'd be a good idea to add a note to the issue templates that the issues related to Vue 3 should be filed in another repository?
