### ISSUE TITLE
the element does render correctly by the list data 

### ISSUE THREAD

**Issue by kpeng2016** [vuejs/vue#12409]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/flamboyant-khayyam-ikl46?file=/package.json:317-323)

### Steps to reproduce
firstly, I render the router page by a array data, then I create instance of sortablejs package, I want to drag and drop elements by the function of sortablejs. after the array data rendered, then I move a element from one div container to another  div , if the element does not move to the end of elements off this div container, it will not render correctly， see the picture as below. but the array data is correct.
see the link https://codesandbox.io/s/flamboyant-khayyam-ikl46?file=/package.json:317-323, when I move "a5" in "a1" to the position between "a3" and "a4" in "a2", then it render incorrectly.
moving
![sortable-error](https://user-images.githubusercontent.com/22167804/148325766-7b315d78-d820-4917-8e60-08dc0bdd06ce.png)
result
![sortable-error2](https://user-images.githubusercontent.com/22167804/148325875-683af136-0718-4bbd-9316-30061f86d3a8.png)

### What is expected?
it render correctly.

### What is actually happening?
not render correctly

**Comment by posva** [comment]
Sorry but this is too much for a reproduction, the code should be easy to follow and not depend on other dependencies like bootstrap vue or sortablejs.

Remember we have the [forum](http://forum.vuejs.org/) and the [Discord chat](https://vue-land.js.org/) to ask questions!
