### ISSUE TITLE
子组件的根节点会被父组件的作用域样式影响【强烈建议取消这功能】

### ISSUE THREAD

**Issue by ctforcp** [vuejs/vue#12412]
### What problem does this feature solve?
大部分时候组件都不想受到其它页面样式的影响。

组件的子节点好多时候是根据根节点的宽、高，颜色、背景颜色等等之类的布局的。
根节点一旦受到其它页面的样式影响，容易导致组件的子节点就开始发生错乱。

现在我为了定义不受其它页面的组件，不得不在根元素外面多添加一个没有必要的根节点。

而且想要调整该子组件布局，完全可以用props、style之类的达到目的。

### What does the proposed API look like?
https://codesandbox.io/s/youthful-bouman-9puy9?file=/src/components/Child.vue

如这里由于子组件样式受到父组件的影响。里面的文字已经看不清，一行的组件变成了两行。

**Comment by posva** [comment]
This has been discussed many times in vue-loader, the rfcs, and here, and is a necessary mechanism to allow styling components.
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
