### ISSUE TITLE
test:type script failed in async component test process

### ISSUE THREAD

**Issue by Giancarlo-Ma** [vuejs/vue#12410]
### Version
2.6.14

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
run yarn test:types

### What is expected?
no errors

### What is actually happening?
 error TS2322: Type '{ component: () => Promise<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>; }' is not assignable to type 'void | Promise<EsModule<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>> | { component: Promise<EsModule<Component<DefaultData<never>, DefaultMethods<...>, DefaultComputed, Record<...>>>>; loading?: VueConstructor<...> | ... 3 more ... | undefined; error?: VueConstructor<....'.
  Type '{ component: () => Promise<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>; }' is not assignable to type '{ component: Promise<EsModule<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>>; loading?: VueConstructor<Vue> | FunctionalComponentOptions<Record<...>, PropsDefinition<...>> | ComponentOptions<...> | { ...; } | undefined; error?: VueConstructor<...> | ... 3 more ... | unde...'.
    Types of property 'component' are incompatible.
      Type '() => Promise<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>' is missing the following properties from type 'Promise<EsModule<Component<DefaultData<never>, DefaultMethods<never>, DefaultComputed, Record<string, any>>>>': then, catch, [Symbol.toStringTag], finally

  9 const b: AsyncComponent = () => ({
                                    ~~
 10   // @ts-expect-error component has to be a Promise that resolves to a component
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 14     })
    ~~~~~~
 15 })
    ~~


Found 1 error.

error Command failed with exit code 1.

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
