### ISSUE TITLE
Please add option eventType for watcher.

### ISSUE THREAD

**Issue by 0xearl** [vuejs/vue#12411]
### What problem does this feature solve?
in my context i'm trying to build an auto-saving feature.
and I have a model named "Form" this model is an object which contains a lot of properties for ex: name, age, address, etc...

so when i first tried to make the auto-saving feature i first thought of using the watch(), since it does exactly what i wanted to do. 
then i tested it, noticed its firing the handler on every input event. which is something we dont want because it'd be a heavy request to the backend/api. so i figured if we just add an eventType parameter in the watch() then we can specify which event should we listen to before firing the handler.

### What does the proposed API look like?
``
watch() {
 form: {
   deep: true,
   eventType: 'change',
   handler: 'formChangeHandler'
 }
}
``

for the api version of watch() it'd be
``
this.$watch(
 'form',
 'change',
 () => {
})``

**Comment by posva** [comment]
This is not possible because a watcher is agnostic to events. You should use an event instead or use throttled/debounced watcher.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
