### ISSUE TITLE
Can not read props with array value inside watch

### ISSUE THREAD

**Issue by tuan-lm** [vuejs/vue#12420]
### Version
3.2.26

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJztcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnO1xuXG5zZXRUaW1lb3V0KCgpID0+IHtcbiAgIGxpc3QudmFsdWUgPSBbMSwgMiwgM107XG59LCAxMDApO1xuXG5jb25zdCBsaXN0ID0gcmVmKFtdKTtcbmNvbnN0IG1vZGVsID0gXCJhYmJjXCI7XG4gIFxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Q29tcCA6bGlzdD1cImxpc3RcIiA6bW9kZWw9XCJtb2RlbFwiLz5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjYvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIHdhdGNoIH0gZnJvbSAndnVlJztcblxuY29uc3QgcHJvcHMgPSBkZWZpbmVQcm9wcyh7XG4gIGxpc3Q6IEFycmF5LFxuICBtb2RlbDogU3RyaW5nLFxufSlcblxud2F0Y2goKCkgPT4gcHJvcHMubW9kZWwsICh2YWwpID0+IHtcbiAgY29uc29sZS5sb2cocHJvcHMubGlzdCk7XG4gIGNvbnNvbGUubG9nKHByb3BzLmxpc3QubGVuZ3RoKTtcbn0sIHtpbW1lZGlhdGU6IHRydWV9KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0e3tsaXN0fX1cbjwvdGVtcGxhdGU+In0=)

### Steps to reproduce
Open console and start change value of `model` at **App.vue**
You will see that even though the list that has been passed to **Comp.vue** show on the template, the value of list can not be read in the `watch` function ( only show `Proxy {}`, which is not a true value )

**What is more crazy is** that if you put `console.log(props)` right before or after `console.log(props.list)`, you will actually see that inside `props`, the list have the right data

### What is expected?
The value of `props` should be correct when read inside `watch` as it passed down

### What is actually happening?
value of list show correctly on template, but not in watch function

**Comment by posva** [comment]
This is because of how devtools work with objects. You have a timeout, so at the time of the console log, the array is empty.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
