### ISSUE TITLE
when I create Vue.directive like v-auth，and use a div with v-for over a div with v-auth.bug is appearing

### ISSUE THREAD

**Issue by SILENCEXZL** [vuejs/vue#12425]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/infallible-hopper-lgzi3?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
create Vue.directive like v-auth，and use a div with v-for over a div with v-auth.if the the div with v-auth has no auth,it will be removed.but the div with v-for is removed too.I don`t know what happend.

### What is expected?
<div>789</div> hidden
<div>1</div><div>2</div>  appear

### What is actually happening?
<div>789</div> and <div>1</div><div>2</div> are all hidden

**Comment by LinusBorg** [comment]
It's a really, really bad idea to remove an element with a directive as Vue's virtual DOM should control that.

You should ask for help on how to solve your problem in the community. chat.vuejs.org
