### ISSUE TITLE
Allow for bubbling of events in webcomponents

### ISSUE THREAD

**Issue by batje** [vuejs/vue#12433]
### What problem does this feature solve?
Events emitted from webcomponents never reach their parent. This limits the use of webcomponents.

The CustomEvent API has a parameter for this, called bubbles. https://developer.mozilla.org/en-US/docs/Web/API/Event/bubbles
 which fires the CustomEvent not just on the emitting webcomponent, but also on all its parents.

Currently, bubbles can not be set, only details are set: https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-dom/src/apiCustomElement.ts#L

### What does the proposed API look like?
The emit function could get an additional parameter, which would break things. Mainly, the emits function for webcomponents would be different than for normal components

Or bubbles could be defaulted to true, which would break other things. 

Emit can now receive an object with a name & callback. A property can be added to that object for options (there are more options than just bubbling: https://developer.mozilla.org/en-US/docs/Web/API/Event )

**Comment by posva** [comment]
Can you go through the RFC process in the rfcs repo?

**Comment by athewsey** [comment]
I also ran in to this problem and couldn't see it up on RFCs already, so started this discussion there: https://github.com/vuejs/rfcs/discussions/433
