### ISSUE TITLE
有没有props,emits的hooks?

### ISSUE THREAD

**Issue by guohuihot** [vuejs/vue#12436]
### What problem does this feature solve?
有没有props,emits的hooks?比如：useProps, useEmits
在做组件时props和emits还是共用不起来，虽然mixins或extends可以解决，但违背了组合api的设计理念，有点不论不类

### What does the proposed API look like?
setup() {
    const props = useProps()
    ...
}
再简单点我觉得setup都可以不要，直接export const fun就可以了

**Comment by markthree** [comment]
[单文件组件<script setup>](https://v3.cn.vuejs.org/api/sfc-script-setup.html#defineprops-%E5%92%8C-defineemits) 可以看下`setup`的宏，用 `defineProps`

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/150673172-091a31ae-9b8c-4b3c-9224-34865ec8c11b.png)
这是我现在的代码，由于buttonProps是通用的，要抽出来, button的逻辑也抽出来useButton, 这样就出现两个模块都有button的逻辑
![image](https://user-images.githubusercontent.com/3119995/150673319-bb236de7-11c2-4134-bba6-de4f9df38d5c.png)

我期望的结果是这样的，buttonProps应该放在useButton里，而不是单独再建个buttonProps放通用的props

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by guohuihot** [comment]
因为对v3不了解，搞笑了，仔细刷了官方文档，函数式组件可以满足我的需求
