### ISSUE TITLE
staticClass en el componente asincrónico empaquetado no representado en el servidor por vue-server-renderer

### ISSUE THREAD

**Issue by Juandieruiz** [vuejs/vue#12432]
### Version
2.6.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-issue-staticclass-on-wrapped-async-component-not-rendered-on-the-server-by-vue-server-renderer-nur3o?file=/_LOOK_HERE/test.html)

### Steps to reproduce
Ignore todas las cosas de Nuxt.js en el repositorio. Necesitaba un Container CodeSandbox, así que comencé con una plantilla de Nuxt.js. Solo concéntrese en los archivos que menciono en los siguientes pasos. ¡El error no tiene nada que ver con Nuxt.js! ¡También ignore la salida del navegador de CodeSandbox! ¡Solo se trata del HTML en ./_LOOK_HERE/test.html!
En el archivo ./_LOOK_HERE/test.html puede ver que <div class="AsyncDiv"></div> no tiene clase de prueba pero <div class="SyncDiv test-class"></div> sí. Ambos deben tener clase de prueba.
En ./main.js puede ver los componentes AsyncDiv y SyncDiv. Son casi iguales, pero el primero es un componente de fábrica asíncrono.
Los componentes WrapperAsync y WrapperSync son exactamente iguales pero representan los dos componentes respectivos. Esto es importante; si renderizo AsyncDiv directamente sin el contenedor, todo funciona como se esperaba.
En la aplicación, representamos ambos envoltorios con la misma clase estática.
En./render.js puede ver el código que produce ./_LOOK_HERE/test.html. Puede ejecutarlo en la terminal con node render.js, pero tiene un poco de errores en CodeSandbox si ha abierto test.html antes. Cierre la pestaña test.html antes de ejecutar el script. O simplemente créame que produce ./_LOOK_HERE/test.html.
No en la reproducción: si el código procesado por el servidor está hidratado en el lado del cliente, la clase de prueba se agrega a AsyncDiv. Entonces parece que en el lado del cliente este caso se maneja correctamente.

### What is expected?
In test.html both components should be rendered with the test-class.

### What is actually happening?
nly the SyncDiv component correctly renders test-class.

---
I would like to know if this new version has been updated, thank you very much

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction that follows the instructions at https://new-issue.vuejs.org/?repo=vuejs/vue#why-repro.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled down reproduction. You can use https://ssr.vuejs.org/ to create one
