### ISSUE TITLE
vue compile / rendering does not work in child elements

### ISSUE THREAD

**Issue by martinbe1io** [vuejs/vue#12438]
### Version
2.6.14

### Reproduction link
[codepen.io](https://codepen.io/martinbe1io/pen/NWaQavq)

### Steps to reproduce
I created a component "dynamic content" capable of displaying html (with vue variables/functions) generated from an api. the component utilizes vue.compile and render functions. it works great for the test case "slide working" in the app when I use my code for normal html tags. 

```
testdata slide working
<div>test {{this.getDynamic()}}<div><div>test {{this.getDynamic()}}<div>test {{this.getDynamic()}}</div></div></div></div>
```

as soon es I try to use variables in cascaded components (see the sample "slide notworking", uses a test component named "test component") the compile function seems to ignore all the Childs. 

```
testdataslidenotworking
<div>test {{this.getDynamic()}}<test-component>{{this.getDynamic()}}<test-component>test {{this.getDynamic()}}<test-component>test {{this.getDynamic()}}</test-component></test-component></test-component></div>
```

### What is expected?
vue.compile should compile the child components as well

### What is actually happening?
vue compile seems to stop at the first vue component

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

—-

Compile takes a static string only, it cannot evaluate the dynamic contest before compiling
