### ISSUE TITLE
how to custom sort component className

### ISSUE THREAD

**Issue by cjd6568358** [vuejs/vue#12439]
### Version
2.6.14

### Reproduction link
[new-issue.vuejs.org/](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
ComponentA:
```
<template>
<div class="A"></div>
</template>
```

ComponentB:
```
<template>
<ComponentA class="B"></ComponentA>
</template>
```

### What is expected?
renderDOM:
```
<div class="B A"></div>
```

### What is actually happening?
renderDOM:
```
<div class="A B"></div>
```

---
For some reason, the styles of A and B may conflict, and it is desirable to be able to adjust their priorities

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Classes are unordered, what defines the final style is the order in which rules are defined, not the order in which classes are applied, but this is unrelated to Vue.
