### ISSUE TITLE
Missing directive triggers strange error message: `Cannot read properties of undefined (reading 'deep')`

### ISSUE THREAD

**Issue by bandleader** [vuejs/vue#12446]
### Version
3.2.29 and all versions I tried since adopting Vue 3

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmV4cG9ydCBkZWZhdWx0IHtcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxpbnB1dCB2LWZvbz1cIjQyXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=)

### Steps to reproduce
```html
<input v-foo="3">
```

...with no directive registered called `foo`.

### What is expected?
Error message `Unknown directive: 'foo'` or similar.

### What is actually happening?
Error message `Cannot read properties of undefined (reading 'deep')`

---
- Note that in the 'new issue' form I couldn't choose any version past 2.6.13. I had to manually edit in the issue editor.
- Bug happens irrespective of whether options API with `data()` or new `setup()` composition API is used. I removed both in the repro for brevity, but you can add either one in and it still gives the same error.

### How bug was discovered

I ran into this error message a few times and couldn't determine the cause exactly, and it went away. Today while playing around I realized that missing directives trigger it.

Note that there are some other strange error messages that I run into all the time. Sometimes Vue even says "likely an internals bug." Hard to pinpoint why. I usually just edit until the error goes away. Unrelatedly, when using Vite and triggering HMR by pressing Ctrl+S, there often also strange errors. Manually refreshing the browser solves the problem.

Not complaining, Vue still gets the job done well; just want to do my part and report. Also, Vue 2 was much better about this (perhaps there were more defensive checks).

**Comment by posva** [comment]
It's already reported:

```
       [Vue warn]: Failed to resolve directive: foo 
  at <Repl>
```

**Comment by bandleader** [comment]
@posva

1) The REPL doesn't report those `Vue warn` warnings -- maybe that should be a separate bug?

2) The fact that Vue still tries to use the directive or something, and emits a strange internal error message, isn't a bug?
