### ISSUE TITLE
vue-server-renderer 多个入口情况会把所有入口的初始化资源加载进来

### ISSUE THREAD

**Issue by jery-Shen** [vuejs/vue#12448]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/client-plugin.js)

### Steps to reproduce
var manifest = {
  publicPath: stats.publicPath,
  all: allFiles,
  initial: initialFiles,
  async: asyncFiles,
  modules: { /* [identifier: string]: Array<index: number> */ }
};

### What is expected?
期望 initial 根据不同入口返回该入口所需要的资源文件

### What is actually happening?
优化性能

**Comment by posva** [comment]
That's not a valid repro. 
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
