### ISSUE TITLE
Vue 2 + Typescript + multiple types for props

### ISSUE THREAD

**Issue by ovidiu888** [vuejs/vue#12441]
### Version
2.6.14

### Reproduction link
[https://github.com/vuejs](https://github.com/vuejs)

### Steps to reproduce
When working with Vuejs v2.6.14, typescript version without decorators, I noticed that you cannot use multiple types (nor union types) for a prop type definition. Tried lots of alternatives, but always got the same error "Expected String with value '...', got Number with value '...'
E.g.: for a prop named title:
type: String || Number => doesn't work because the String constructor will always be truthy
type: String as PropType<String | Number> => sees only String as a type for the title prop
type: [String, Number] => not working as well
type: => tried creating a union type as well, but failed.
type: string | number => error: "a constructor is expected"

### What is expected?
- prop type should allow union types or multiple types
- you can set "any" type to a prop

### What is actually happening?
- you cannot have more than one different type for a prop
- you cannot set prop type to "any"

---
It cannot be reproduced via fiddle

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by ovidiu888** [comment]
Hi @posva, this a bug report, can you please reopen the ticket? Thanks!

**Comment by posva** [comment]
Use `as PropType<string | number>`. 
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
