### ISSUE TITLE
Vue runtime error log displays problems

### ISSUE THREAD

**Issue by lemonit-eric-mao** [vuejs/vue#12450]
##### vue.common.dev.js    Line 630
![image](https://user-images.githubusercontent.com/68628461/151646767-fdc5fcd4-1afc-4c2d-bc24-eae2ef0d2fb4.png)
``` javascript
......
warn = function (msg, vm) {
    var trace = vm ? generateComponentTrace(vm) : '';

    if (config.warnHandler) {
      config.warnHandler.call(null, msg, vm, trace);
    } else if (hasConsole && (!config.silent)) {
      console.error(("[Vue warn]: " + msg + trace));  //？
    }
  };
......
```

### What does the proposed API look like?
![image](https://user-images.githubusercontent.com/68628461/151646778-6dde02bc-7e45-481e-a199-a1b93f9fa6a4.png)

If the expected return here is a warning, it is recommended not to use error log

If the expectation here is error, then the expectation here is throw error

**Comment by posva** [comment]
This would technically breaking change so it cannot be changed now but it has in v3
