### ISSUE TITLE
Uncaught (in promise) TypeError: can't access property "nextSibling", node is null

### ISSUE THREAD

**Issue by bjorntj** [vuejs/vue#12451]
### Version
2.6.14

### Reproduction link
[github.com/bjorntj/vue-test](https://github.com/bjorntj/vue-test)

### Steps to reproduce
Run the application, make the window small so the main menu disappear and the mobile menu appear. Click the button to open the menu.

### What is expected?
No errors

### What is actually happening?
Get the following error:

Uncaught (in promise) TypeError: can't access property "nextSibling", node is null
    nextSibling runtime-dom.esm-bundler.js:36
    getNextHostNode runtime-core.esm-bundler.js:5632
    patch runtime-core.esm-bundler.js:4457
    patchBlockChildren runtime-core.esm-bundler.js:4806
    patchElement runtime-core.esm-bundler.js:4714
    processElement runtime-core.esm-bundler.js:4569
    patch runtime-core.esm-bundler.js:4486
    componentUpdateFn runtime-core.esm-bundler.js:5107
    run reactivity.esm-bundler.js:160
    callWithErrorHandling runtime-core.esm-bundler.js:155
    flushJobs runtime-core.esm-bundler.js:394
    promise callback*queueFlush runtime-core.esm-bundler.js:285
    queueJob runtime-core.esm-bundler.js:279
    effect runtime-core.esm-bundler.js:5139
    triggerEffects reactivity.esm-bundler.js:358
    triggerRefValue reactivity.esm-bundler.js:959
    set value reactivity.esm-bundler.js:1003
    set reactivity.esm-bundler.js:1018
    5 App.vue:71
    callWithErrorHandling runtime-core.esm-bundler.js:155
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:164
    invoker runtime-dom.esm-bundler.js:366
    addEventListener runtime-dom.esm-bundler.js:316
    patchEvent runtime-dom.esm-bundler.js:334
    patchProp runtime-dom.esm-bundler.js:398
    mountElement runtime-core.esm-bundler.js:4603
    processElement runtime-core.esm-bundler.js:4566
    patch runtime-core.esm-bundler.js:4486
    mountChildren runtime-core.esm-bundler.js:4685
    mountElement runtime-core.esm-bundler.js:4594
    processElement runtime-core.esm-bundler.js:4566
    patch runtime-core.esm-bundler.js:4486
    mountChildren runtime-core.esm-bundler.js:4685
    mountElement runtime-core.esm-bundler.js:4594
    processElement runtime-core.esm-bundler.js:4566
    patch runtime-core.esm-bundler.js:4486
    mountChildren runtime-core.esm-bundler.js:4685
    mountElement runtime-core.esm-bundler.js:4594
    processElement runtime-core.esm-bundler.js:4566
    patch runtime-core.esm-bundler.js:4486
    componentUpdateFn runtime-core.esm-bundler.js:5037
    run reactivity.esm-bundler.js:160
    setupRenderEffect runtime-core.esm-bundler.js:5156
    mountComponent runtime-core.esm-bundler.js:4939
    processComponent runtime-core.esm-bundler.js:4897
    patch runtime-core.esm-bundler.js:4489
    render runtime-core.esm-bundler.js:5641
    mount runtime-core.esm-bundler.js:3878
    mount runtime-dom.esm-bundler.js:1590
    <anonymous> main.js:7
    js app.js:129
    __webpack_require__ app.js:451
    __webpack_exports__ app.js:1615
    O app.js:497
    <anonymous> app.js:1616
    <anonymous> app.js:1618
runtime-dom.esm-bundler.js:36

---
If I use the Option API instead of composition, then the error does not happen...

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro when reporting a bug. Most bugs should be reproducible with the [SFC Playground](https://sfc.vuejs.org). Also, it should be opened in vuejs/core

**Comment by Akesure** [comment]
你好，这里是Akesure的小秘书，他在空闲时，会来回复你发送的e-Mail。
