### ISSUE TITLE
Suggestion: introduce new function for template refs in setup functions

### ISSUE THREAD

**Issue by theoephraim** [vuejs/vue#12453]
### What problem does this feature solve?
Just a small suggestion to introduce a new function for template refs in order to increase readability in setup functions.

For example, currently to reference a component in our template (for example `<Popup ref="popup" ... />`) we would write
```
const popup = ref(null); // does something very special because ref="popup" exists in the template
const loggedOutAt = ref(null); // does something totally different...
```

The ref name in the template must match our variable name exactly, and it is not immediately obvious that this ref does anything special compared to any other reactive ref which could be holding any other data.

Perhaps there are some important under the hood reasons for marrying the general reactivity ref with template refs, but I think it is slightly confusing for newcomers, and could be made more clear.

### What does the proposed API look like?
I suggest we just add a new function to distinguish regular refs from template refs and removes the tight coupling of the variable name.

For example:
```
import { templateRef } from 'vue';

const myPopup = templateRef('popup');
```

This will be immediately obvious to readers that `myPopup` is referencing something from the template, and it frees the user up to name the variable as they like.

the function could be called `templateRef`, `getTemplateRef`, `useTemplateRef`, ...

**Comment by posva** [comment]
Can you go through the RFC process in vuejs/rfcs, please?

**Comment by theoephraim** [comment]
For sure. Thanks!
