### ISSUE TITLE
HMR is not working

### ISSUE THREAD

**Issue by gp0119** [vuejs/vue#12461]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/gp0119/vue-hmr-test.git)

### Steps to reproduce
delete a line in `src/components/test.vue`, nothing has changed in the browser

### What is expected?
HMR is working

### What is actually happening?
HMR is not working

**Comment by spiropoulos94** [comment]
What is HMR????

**Comment by Foever18** [comment]
什么是vue

**Comment by Mayank1170** [comment]
Can you explain me the function of HMR ?
