### ISSUE TITLE
Not compatible with Firefox mobile

### ISSUE THREAD

**Issue by 332lfgb6** [vuejs/vue#12478]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/332lfgb6/firefox_bug)

### Steps to reproduce
see readme.md.

### What is expected?
The text is still here.

### What is actually happening?
text is gone.

---
sunsamg a6s
firefox mobile

**Comment by posva** [comment]
Can't reproduce.

**Comment by 332lfgb6** [comment]
> Can't reproduce.

Can you provide a screenshot of your mobile phone? A screenshot with the address bar and a screenshot without the address bar. I wonder if it's my phone.
