### ISSUE TITLE
vue2 not recognizing change when pushing a previously set array to query

### ISSUE THREAD

**Issue by mawsyh** [vuejs/vue#12482]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/bitter-river-bewtih?file=/pages/index.vue)

### Steps to reproduce
Imagine using this function to push the changes to query when user play with the website filters:
```
async pushQuery(inputs) {
      const query = Object.assign({}, this.$route.query);

      // if we are in page 5 for example when adding new filter we need to reset back to the first page!
      if (query.page) {
        delete query.page;
      }
      // In case we are doing the same filter need to toggle!
      for (const input of inputs) {
        if (query[input.key] === input.value) {
          delete query[input.key];
          if (!query[input.key]) return;
          return await this.$router.push({ query });
        }
       // formating the array form of query
        if (Array.isArray(input.value)) {
          input.key = input.key + "[]";
        }
       // making the query
        query[input.key] = input.value;
        if (input.value === "" || !input.value) {
          delete query[input.key];
        }
      }
     // finally we will push the new query
      await this.$router.push({ query });
    }, 
```
now everything is going to work fine the first time using this code, the problem will occur when the user has already changed some filters, let's say we have a dropdown filter called "country" and it's already set to "Canada" and "France", this is the result:
 https://website.com/find-tutors?country%5B%5D=Canada&country%5B%5D=France
If user try **reloading** the page then add or remove some countries, vue will fail to add changes to the path.

In order to make vue realize these changes I found 2 solutions:
We can add a new query like :
```
      query.changed = Math.floor(new Date().getTime() / 1000);

```
right before we call router.push .

Shuffling the country array (using underscore library e.g.) can also give us the results we are looking for.

### What is expected?
https://website.com/find-tutors?country%5B%5D=Canada&country%5B%5D=France&country%5B%5D=Iraq&country%5B%5D=Ukraine

### What is actually happening?
https://website.com/find-tutors?country%5B%5D=Canada&country%5B%5D=France

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
