### ISSUE TITLE
The latest progress of Vue 2.7 and the REAL approximate release time

### ISSUE THREAD

**Issue by crabkiller** [vuejs/vue#12497]
### What problem does this feature solve?
According to [this doc](https://v3-migration.vuejs.org/migration-build.html#:~:text=estimated%20late%20Q3%202021):
> A word of caution: if your application is large and complex, migration will likely be a challenge even with the migration build. If your app is unfortunately not suitable for upgrade, do note that we are planning to backport Composition API and some other Vue 3 features to the 2.7 release (estimated late Q3 2021).

### What does the proposed API look like?
The latest progress of Vue 2.7. Thanks~

**Comment by lorand-horvath** [comment]
Vue 2.7 seems to be a bit abandoned https://github.com/vuejs/vue/projects/8

**Comment by tomootes** [comment]
Would be really nice to have any update on the development of Vue 2.7. Seems like the only way to upgrade a large Vue application smoothly.

**Comment by ruantin** [comment]
is verver good!

**Comment by darrinmn9** [comment]
It is discussed in this recent podcast. Evan You mentions that 2.7 is now a priority, 2.7 will add several features including the vue-composition api into core to help ease the transition to Vue 3. After 2.7 is released there will be no new features added and will receive 18 months of maintenance support until its EOL.
 
https://podcasts.apple.com/us/podcast/s09e07-modern-web-podcast-state-of-vue-js-with-evan/id1084236187?i=1000555792786

**Comment by Azema4ka** [comment]
Top!

**Comment by an501920078** [comment]
And 2.7?

**Comment by yyx990803** [comment]
The work has started on 2.7 - we are porting the codebase to TypeScript and improving the outdated test setup. Regarding features - as mentioned above, the main goal is porting Composition API and `<script setup>`.

Timing estimated is still in flux, but should be within 2~3 months from now.

**Comment by lorand-horvath** [comment]
@yyx990803 Excellent news, Evan! I've been waiting for this for years, literally ;-)
