### ISSUE TITLE
Vue.extend方法中的cachedCtors感觉实际没有起到缓存构造函数的作用

### ISSUE THREAD

**Issue by py389172739** [vuejs/vue#12493]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/vuejs/vue/issues/new/choose)

### Steps to reproduce
我看vue源码中的Vue.extend方法中有这么一段代码，目的是判断当前constructor是否在缓存中，如果在则从缓存中取，从extendOptions._Ctor中获取缓存列表这行代码，我看整个vue源码中只有此处有用_Ctor ，但是并没有复制，那是不是意味着每次走到这里获取到cachedCtors 都是空对象，无法走到下面的if分支中去呢？

var cachedCtors = extendOptions._Ctor || (extendOptions._Ctor = {});
      if (cachedCtors[SuperId]) {
        return cachedCtors[SuperId]
      }

### What is expected?
extendOptions._Ctor 应该有个地方赋值

### What is actually happening?
extendOptions._Ctor没看到有地方赋值

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
