### ISSUE TITLE
No error handling for importing a component with the same name as the component you are importing into

### ISSUE THREAD

**Issue by yodahack** [vuejs/vue#12499]
### Version
2.6.11

### Reproduction link
[/nostalgic-turing-0p8v50 @ codesandbox.io](https://codesandbox.io/s/nostalgic-turing-0p8v50?file=/src/App.vue)

### Steps to reproduce
It is fairly easy to reproduce. You just need to create two components with the same name and import one into another.

The problem is trivial but in heat of development when one is doing a lot of work when this happens the error messages in the console are not very helpful. 

I am new to Vue, if you direct me to the proper area of code/module/subproject where it should be resolved I might attempt to resolve this myself and propose a patch.

Vue is a very good project.

I am @yodahack at github please contact me if need be.

### What is expected?
Plain Simple Error message during compilation phase or Plain Simple Error message during the execution phase.

### What is actually happening?
a dump of errors "Maximum call stack size exceeded"

**Comment by j05070415** [comment]
谢谢，您的邮件我已收到！

**Comment by posva** [comment]
This is because of recursive components: https://v2.vuejs.org/v2/guide/components-edge-cases.html?redirect=true#Recursive-Components.
An easier and faster to implement hint would be at the linting level if you are interested in implementing this.
