### ISSUE TITLE
Firefox: Parent anchor tag link is opened, even though child input stops event propagation

### ISSUE THREAD

**Issue by PremierJoe** [vuejs/vue#12490]
### Version
2.6.14

### Reproduction link
[codepen.io](https://codepen.io/PremierJoe/pen/VwrqwLw)

### Steps to reproduce
- create an `<a>` tag with a child element of a checkbox input
- on the click event of the checkbox, stop event propagation
- console log on each input event
- click input
- on Chrome and Firefox, `<a>` correctly does not fire a click event. Link is not opened on Chrome, but is on Firefox.

### What is expected?
- Both Chrome and Firefox check the checkbox and do not click on the `<a>` element

### What is actually happening?
On Chrome, checkbox is checked and link is not opened

On Firefox, checkbox is checked and link is opened

---
On both, the event propagation seems to be working correctly (i.e. `<a>` click not logged to console) however the link is still opened on firefox

**Comment by posva** [comment]
Tested with plain JS and it happens as well. Can you report the bug to firefox, please?

```html
<a href="https://example.com" id="a">
  <input type="checkbox" id="c">
</a>
```

```js
document.getElementById('c').addEventListener('click', e => {
  console.log('checkbox clicked')
  e.stopPropagation()
})

document.getElementById('a').addEventListener('click', e => {
  console.log('anchor clicked')
})
```

**Comment by AnandBIT** [comment]
I guess this doesn't happen with only checkbox, instead the anchor tag link will get opened even if the event has stopped propagating either through it's parent (by stopping event propagation while in capturing phase) or it's child (by stopping event propagation while in bubbling phase)
For your reference -> https://jsfiddle.net/anandbit/306azk28/5/

**P.S - This bug can be seen not only in firefox, but in all browsers out there**

Can anyone explain this absurd behaviour of anchor tag?
