### ISSUE TITLE
公司历史原因，在维护一个vue1的项目，vue1里面没有slot-scope的api，有什么可替代的写法吗

### ISSUE THREAD

**Issue by hmh9251** [vuejs/vue#12509]
### What problem does this feature solve?
如题

### What does the proposed API look like?
是否可以在vue1的版本中在加上slot-scope的api

**Comment by tfzzh** [comment]
如果项目不大，且比较重要。
建议直接用v3重写一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 晚上8:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [vuejs/vue] 公司历史原因，在维护一个vue1的项目，vue1里面没有slot-scope的api，有什么可替代的写法吗 (Issue #12509)




 
What problem does this feature solve?
 
如题
 
What does the proposed API look like?
 
是否可以在vue1的版本中在加上slot-scope的api

**Comment by hmh9251** [comment]
> 如果项目不大，且比较重要。 建议直接用v3重写一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月30日(周三) 晚上8:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [vuejs/vue] 公司历史原因，在维护一个vue1的项目，vue1里面没有slot-scope的api，有什么可替代的写法吗 (Issue #12509) What problem does this feature solve? 如题 What does the proposed API look like? 是否可以在vue1的版本中在加上slot-scope的api — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
