### ISSUE TITLE
关于微信分享导致路由失败的问题

### ISSUE THREAD

**Issue by seqwait** [vuejs/vue#12505]
有页面: http://example.com/#/abc 分享到微信后 会变成 http://example.com/#/abc&shareTo=weixin 这种,导致路由失败,必须在每个分享到微信的url加上?号吗,有没有好的解决方案.

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
