### ISSUE TITLE
若依前后端不分离项目中，如何使用vue

### ISSUE THREAD

**Issue by danranshizhi** [vuejs/vue#12500]
### What problem does this feature solve?
若依前后端不分离版本，想用element-ui组件库，则需要引入vue.js依赖。
index.html 通过点击左侧菜单，来控制右侧内容显示。右侧内容为一个个html页面，以iframe的方式内嵌，点击菜单时，控制对应iframe的显示与隐藏。
如果要在这样的项目中使用vue,在每个需要element-ui组件库的html页面中，都要使用new Vue({el: '#demo1', data() {...}})吗？（注：这种写法已试，element-ui组件可正常使用）
若每个页面都new Vue这种方式不对，请问正确的写法是什么？
是在需要使用element-ui组件库的html页面中，分别使用new Vue({el: '#demo1', data() {...}})吗？若不是，正确的要怎么写呢？

### What does the proposed API look like?
在需要使用element-ui组件库的html页面中，分别使用new Vue({el: '#demo1', data() {...}})吗

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
