### ISSUE TITLE
vuejs插值表达式 有没有办法支持 可选链操作符？

### ISSUE THREAD

**Issue by yokochen222** [vuejs/vue#12507]
### What problem does this feature solve?
<div>{{ obj.a?.v?.b }}</div>
简化对象判断

### What does the proposed API look like?
<div>{{ obj.a?.v?.b }}</div>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
