### ISSUE TITLE
文档内容错误

### ISSUE THREAD

**Issue by noxussj** [vuejs/vue#12513]
### Version
2.6.14

### Reproduction link
[https://cn.vuejs.org/v2/api/](https://cn.vuejs.org/v2/api/)

### Steps to reproduce
1、API文档——指令——v-on——用法——prop到表达式错别字
2、API文档——指令——v-bind——示例——class 绑定，缺少结束 div

### What is expected?
prop的表达式
<div :class="[classA, { classB: isB, classC: isC }]"></div>

### What is actually happening?
prop到表达式
<div :class="[classA, { classB: isB, classC: isC }]">

![0265d9366a6221f04f201db16dde4fe](https://user-images.githubusercontent.com/37679301/161241082-06745f5c-acc3-4bea-82bc-5cbd1e264256.png)

![242ccb0351c212b598442bc8a661d83](https://user-images.githubusercontent.com/37679301/161241104-2bc94b7e-320c-4fe0-8ec1-540d1a07f4fd.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
