### ISSUE TITLE
v-slot出来的值不会渲染

### ISSUE THREAD

**Issue by is-liyiwei** [vuejs/vue#12519]
### Version
2.6.11

### Reproduction link
[codesandbox.io/s/vqdrri](https://codesandbox.io/s/vqdrri)

### Steps to reproduce
bcom组件里面的devData不被渲染，但是随便修改这个组件的一些值就可以了(bcom组件里面有一个注释的了定时器代码，打开即可)

### What is expected?
v-slot的值可以渲染

### What is actually happening?
v-slot的值没有渲染，但是修改了一些值后可以

**Comment by posva** [comment]
This is explained as a reactivity caveat in docs

**Comment by is-liyiwei** [comment]
我需要怎么做才能正确渲染(Do I have to do in order to correctly apply colours to a drawing)
