### ISSUE TITLE
Repeated watch triggers 重复的watch触发行为

### ISSUE THREAD

**Issue by newlichuan** [vuejs/vue#12522]
### Version
2.6.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/patient-voice-2fst7s?file=/src/App.vue)

### Steps to reproduce
Please open the console and enter a value. At this time, the a property has not changed, but it is triggered once, but c does not, and a is not triggered when the second character is entered.
我同时watch了三个属性 a b c  但是当我第一次改变b时  a也被触发了,但是c并没有 ( 我如果事先定义好b就没问题了,但是我的属性是动态的,无法初始定义)

### What is expected?
Trigger only its own listeners  (只触发自己的监听器)

### What is actually happening?
Repeated watch triggers  (a不该被触发)

**Comment by posva** [comment]
This is because the property b doesn't initially exist in form so Vue calls `this.$set()` which triggers the reactivity of the whole object, including arrays.

**Comment by newlichuan** [comment]
Then why attribute c is not triggered?

**Comment by newlichuan** [comment]
> Member

Then why attribute c is not triggered?

**Comment by posva** [comment]
because it's a primitive value, not an object

**Comment by newlichuan** [comment]
> because it's a primitive value, not an object

Thank you!!
