### ISSUE TITLE
Initial data from props, BUT only object type data remains reactive

### ISSUE THREAD

**Issue by iamplex** [vuejs/vue#12528]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/initial-data-from-props-e3mxid)

### Steps to reproduce
I read this on the vue2 docs, and i try to create a child component and initial data from props, but i got some issue, not sure is this a bug or just my problem 

![initdatafromprops](https://user-images.githubusercontent.com/11267832/163914896-8bdc7830-355f-4039-abc0-0dd6dc35317c.jpg)

create a parent component like this:
```vue
<script>
import Child from "./components/Child";

export default {
  components: {
    Child,
  },

  data() {
    return {
      value: "a value",

      props: {
        num: 1,
        str: "a str",

        obj: {
          text: "a obj text",
        },
        arr: ["a arr text"],
      },
    };
  },
  methods: {
    onClick() {
      this.props.str = this.value;
      this.props.num++;
      this.props.obj.text = this.value;
      this.$set(this.props, "arr", [this.value]);
    },
  },
};
</script>

<template>
  <div id="app">
    <input v-model="value" />
    <button type="button" @click="onClick">Update Text</button>

    <Child v-bind="props"></Child>
  </div>
</template>
```

and create a child component:

```vue
<script>
export default {
  props: {
    num: Number,
    str: String,
    obj: Object,
    arr: Array,
  },

  data() {
    return {
      initNumFromProps: this.num,
      initStrFromProps: this.str,
      initObjFromProps: this.obj,
      initArrFromProps: this.arr,
    };
  },

  created() {
    console.log("I am render!");
  },
};
</script>

<template>
  <div>
    <div>
      <h4>Props:</h4>
      <div>Number: {{ num }}</div>
      <div>String: {{ str }}</div>
      <div>Object: {{ obj }}</div>
      <div>Array: {{ arr }}</div>
    </div>

    <div>
      <h4>Data:</h4>
      <div>Number: {{ initNumFromProps }}</div>
      <div>String: {{ initStrFromProps }}</div>
      <div>Object: {{ initObjFromProps }}</div>
      <div>Array: {{ initArrFromProps }}</div>
    </div>
  </div>
</template>
```

In the child component, when props updated, only `initObjFromProps` remain reactive, other data types are only updated once when the component is created

you can check [initial data from props](https://codesandbox.io/s/initial-data-from-props-e3mxid)

### What is expected?
Keep all data initialized from props remain reactive if props updated

### What is actually happening?
Only object type remain reactive

---
current my solution is add a key props in child component to make it rerender(would be go through the created/mounted life cycle again)
```vue
<Child v-bind="props" :key="props.str"></Child>
```

if anyone has a better way, please let me know

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is inherent to how objects are passed by reference in JS.
