### ISSUE TITLE
jsx 里面的props属性

### ISSUE THREAD

**Issue by bervis** [vuejs/vue#12535]
### Version
2.6.14

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==)

### Steps to reproduce
**当父组件使用temlpate模板时候**
`<template>
   <ecy-cascader
    :props="props"></ecy-cascader>
</template>`

**子组件ecyCascader使用$attrs**

`<template>
  <el-cascader
    v-bind="$attrs">
  </el-cascader>
</template>`
可以将**props**传递到el-cascader组件里面
**但是父组件使用jsx的时候**
`<EcyCascader
          options={this.options}
          props={props}
        ></EcyCascader>`
**$attrs** 无法将**props**传递到el-cascader组件里面，但是可以通过设置attrs={props}进行传递

### What is expected?
希望template和写jsx时候保持一致

### What is actually happening?
需要用不同的属性值props和attrs去传递

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by bervis** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

我描述的就是bug，**$attrs**无法拷贝**jsx**里面的**props**属性

**Comment by Justineo** [comment]
提交 bug 时我们[要求提供最小化复现](https://new-issue.vuejs.org/?repo=vuejs/core&lang=zh-cn#why-repro)，你提交的链接是 SFC Playground 的默认代码。

**Comment by bervis** [comment]
> 提交 bug 时我们[要求提供最小化复现](https://new-issue.vuejs.org/?repo=vuejs/core&lang=zh-cn#why-repro)，你提交的链接是 SFC Playground 的默认代码。

我再描述一下问题哈，在vue2版本的jsx写法里面, props里面的属性，无法被$attrs绑定到指定组件上。template写法没有问题，vue3无论用jsx还是template写法都没问题
