### ISSUE TITLE
I mistakenly took 0 as the divisor in computed, Caused Vue devtool to crash

### ISSUE THREAD

**Issue by tu6ge** [vuejs/vue#12538]
### Version
2.6.14

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG48c2NyaXB0PlxuZXhwb3J0IGRlZmF1bHR7XG4gIGRhdGEoKXtcbiAgICByZXR1cm4ge1xuICAgICAgdmFsMTowLFxuICAgIH1cbiAgfSxcbiAgY29tcHV0ZWQ6e1xuICAgIHZhbDIoKXtcbiAgICAgIHJldHVybiAxMC90aGlzLnZhbDFcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGlucHV0IHYtbW9kZWw9XCJtc2dcIj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9)

### Steps to reproduce
```
computed:{
   val1(){
      return 10/0
   }
}
```

### What is expected?
Expected to disable compilation

### What is actually happening?
Cause devtool to crash, It's not that easy to troubleshoot

**Comment by tu6ge** [comment]
I selected has wrong compoents in dev-tool, and dev-tool and webview is all crash. not selected it is normal

**Comment by posva** [comment]
It displays `Infinity`. Check you are using the latest devtools version (and not the beta)
