### ISSUE TITLE
Different behavior between type [Boolean, String] and type String in custom my-select components

### ISSUE THREAD

**Issue by rukonmin** [vuejs/vue#12531]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/distracted-shaw-x2w5rr?file=/src/App.vue)

### Steps to reproduce
In MyBooleanStringSelect component
1. prop value = ''
2. Display result is True

### What is expected?
Empty string value

### What is actually happening?
Value is True

---
MyBooleanStringSelect  and MyStringBooleanSelect have different behavior for prop value equals to ''

**Comment by posva** [comment]
As explaining multiple other issues this is expected

**Comment by rukonmin** [comment]
Can you get a link where it's describe?

> As explaining multiple other issues this is expected
