### ISSUE TITLE
throw error when refWrapped list pushed refWrapped value

### ISSUE THREAD

**Issue by bartlian** [vuejs/vue#12549]
### Version
2.7.0-alpha.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/withered-darkness-lffd1r?file=/src/App.vue)

### Steps to reproduce
case 1
step1. click add1
step2. string can be pushed to list
step3. view rendered as expected

case2
step1. click add2
step2. throw an error `TypeError: Converting circular structure to JSON` 

### What is expected?
refWrapped string should be pushed to refWrapped list

### What is actually happening?
throw an error

**Comment by posva** [comment]
You either need to push `msg.value` (this is probably what you want) or display `item.value`

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
