### ISSUE TITLE
Syntax error neither caught in window.error nor errorHandler

### ISSUE THREAD

**Issue by jayzun** [vuejs/vue#12547]
### Version
2.6.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/objective-thunder-gb76vp?file=/src/App.vue)

### Steps to reproduce
write following bug:

```
props: {
    text: {
      type: String,
      default: this.something, // 'this' is unexpected here
    },
  },
```

set error catcher: 

```
Vue.config.errorHandler = function (err, vm, info) {
  console.log("Vue.config.errorHandler", err, vm, info);
};

window.onerror = (err) => {
  console.log("window.onerror", err);
};
```

### What is expected?
I expect this kind of syntax error could be caught somehow, so we can report it in our monitor system.
if somebody wrote a bug like this,  we can receive report immediately and fix the problem.

### What is actually happening?
no console.log is triggered in this case.

**Comment by hbsjmsjwj** [comment]
"vue": "^3.2.11",
//component
<button @click="handleErr(1)">js error</button>
function handleErr(e){
  e.name=2
}
//main.js
window.onerror=function (message, url, lineNumber, columnNumber, error){
  console.log(message, url, lineNumber, columnNumber, error)   //-----npm run serve   ok!!
}

but 
但是 npm run build
Deploy to nginx
 does not take effect
