### ISSUE TITLE
Using 'v-for in array.sort()'  in dynamic components causes infinite update loop

### ISSUE THREAD

**Issue by Bacuuu** [vuejs/vue#12545]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/nostalgic-water-e8hx36?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
in dynamic components, use Array.sort() in v-for 

### What is expected?
run without any warning.

### What is actually happening?
In console,
[Vue warn]: You may have an infinite update loop in a component render function.

**Comment by LinusBorg** [comment]
sort mutates the array. That's a reactive operation. Reactive operations during render result in an infinite update loop, that's expected.

Possible Solutions include makeing a copy of the array befor sorting, i.e. `Array.from(testData).sort( ....)`
