### ISSUE TITLE
vue2的组件我觉得太单一，不方便，我用的版本不支持，多标签，只能单标签，而且单标签都不能加任何其他外在数据。

### ISSUE THREAD

**Issue by JavaAndPython55** [vuejs/vue#12544]
### What problem does this feature solve?
比如我想做一个人人都能用的登录模块。导入进去就能登录。
结果:【不支持标签外的数据】如：
 账号"<input  type="text"/>"。
这种都不支持，连“账号"都没有办法加到组件中。
------------------------------
目前不支持双标签
例如 "<button>login</button><button>regesiter</button> "
这种tempalte中都不支持。只能识别出第一个button
--------------------------
请问是我没有找到专用的地址，还是vue组件方面目前开发不够成熟呢：）

### What does the proposed API look like?
组件的升级化。
1.功能可以支持多个标签
2.可以在tempalte中引入，自动绑定模块
3.支持一套整体的组件模块，比方说，我定义的组件，调用这个自定义组件标签后，能直接使用创建一个登录模块。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by edison1105** [comment]
这跟 vue 有啥关系? 组件都是自己开发的。
