### ISSUE TITLE
console.log window object throw unrelated error

### ISSUE THREAD

**Issue by zecka** [vuejs/vue#12540]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-window-console-log-97be26?file=/src/App.vue)

### Steps to reproduce
In a component, try to log window object in console on mounted:

```javascript
export default {
  mounted() {
    console.log(window);
  },
};
```

### What is expected?
Get window object in console

### What is actually happening?
When log window object on console in mounted method, an unrelated error is throw:

[Vue warn]: Property or method "children" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

![image](https://user-images.githubusercontent.com/18116930/169643930-6d545d50-c531-4841-be0b-31c6956bb577.png)

found in
---> <App> at /src/App.vue

**Comment by liulinboyi** [comment]
I export the project run it locally, the project is not have error on the console.

step is:
1. `pnpm install`
2. `npm run serve`

https://user-images.githubusercontent.com/41336612/169658593-e30f2e01-dd02-4cfd-9882-4f3118828386.mp4

**Comment by posva** [comment]
seems unrelated to Vue, probably to codesandbox instead.
