### ISSUE TITLE
Focus on element wrapped in transition works incorrectly on ios(safari)

### ISSUE THREAD

**Issue by lil-kita** [vuejs/vue#12557]
### Version
2.6.10

### Reproduction link
[https://jsitor.com/ZGmF0GPpqO](https://jsitor.com/ZGmF0GPpqO)

### Steps to reproduce
I have button and textarea, which is invisible. When click on button textarea appears and is focused, the keyboard appears on ios(Safari), and the screen correctly scrolls to textarea.

However, if I wrap textarea with transition component screen does not scroll to textarea and textarea appears behind the keyboard. Please advise how I could have correct focus with transition?

---
link to StackOverflow: https://stackoverflow.com/questions/72607448/vue-transition-break-focus-on-ios-how-to-fix

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is related to how animations can affect some behaviors of the browser but it's not related to Vue itself. I think waiting for the animation to finish before focusing the textarea could help
