### ISSUE TITLE
use watchEffect should pauseTracking with array

### ISSUE THREAD

**Issue by okbug** [vuejs/vue#12565]
### Version
2.7.0-beta.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/loving-kilby-r59ebh?file=/index.html)

### Steps to reproduce
pauseTracking with array length when length-altering mutaion

### What is expected?
the first demo in Vue3 can show the [ 1, 2 ]
but in Vue2.7.0-beta.3 it shows [ 1, 2, 1, 2 ]

In the second demo will make page stop running.
it looks like https://github.com/vuejs/core/issues/2137

### What is actually happening?
not same result and page stop running

**Comment by yyx990803** [comment]
Unfortunately this is a limitation of Vue 2's reactivity system. Array mutation methods work by triggering updates of effects that tracks the array itself. There's no way to fix this.
