### ISSUE TITLE
Template Ref watcher not triggered in Vue 2.7

### ISSUE THREAD

**Issue by dm4t2** [vuejs/vue#12569]
### Version
2.7.0-beta.4

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-2-7-0-template-ref-watcher-issue-be6ghd?file=/src/App.vue)

### Steps to reproduce
Open the CodeSandbox and watch the console output.

### What is expected?
There should be a log entry.

### What is actually happening?
There's no log entry because the watcher is not triggered.

---
This works in Vue 2.6 (with Composition API plugin) and Vue 3:

https://codesandbox.io/s/vue-2-6-14-template-ref-watcher-working-example-3fec25?file=/src/App.vue
https://codesandbox.io/s/vue-3-2-33-template-ref-watcher-working-example-nd1imp?file=/src/App.vue

**Comment by stevebauman** [comment]
Hmm this still isn't resolved in 2.7.7...

**Comment by dm4t2** [comment]
My CodeSandbox reproduction works with v2.7.7: https://codesandbox.io/s/vue-2-7-template-ref-watcher-issue-be6ghd

**Comment by stevebauman** [comment]
Unfortunately not with an array of template refs:

https://github.com/vuejs/vue/issues/12675

**Comment by reidsolon** [comment]
bind the inputRef to the input element then add .value in watch. In my case:

watch( () => inputRef.value, () => { // } )
