### ISSUE TITLE
@vue/cli-plugin-babel@4.5.18  error! error! error! error!

### ISSUE THREAD

**Issue by chinaxcy** [vuejs/vue#12576]
### Version
2.6.14

### Reproduction link
[http://www.github.com/](http://www.github.com)

### Steps to reproduce
Module parse failed: Unexpected token (278:75)
File was processed with these loaders:
 * ../../node_modules/.pnpm/cache-loader@4.1.0_webpack@4.46.0/node_modules/cache-loader/dist/cjs.js
 * ../../node_modules/.pnpm/thread-loader@2.1.3_webpack@4.46.0/node_modules/thread-loader/dist/cjs.js
 * ../../node_modules/.pnpm/babel-loader@8.2.5_7f01cabc6cae6b1bed6d7aa154f5ac58/node_modules/babel-loader/lib/index.js
 * ../../node_modules/.pnpm/cache-loader@4.1.0_webpack@4.46.0/node_modules/cache-loader/dist/cjs.js
 * ../../node_modules/.pnpm/vue-loader@15.9.8_cd7d3296ac462ab2aecfca1edf15e195/node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.

### What is expected?
修复错误

### What is actually happening?
今天升级后突然BUG

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
