### ISSUE TITLE
Vue sfc compiler does not handle <img src="@/assets/..."> as alias

### ISSUE THREAD

**Issue by last-partizan** [vuejs/vue#12583]
HI, i'm trying to make alias for handling assets starting with `@/`, and it doesn't work with vue-2.7.

### Version
2.7.0-beta.7

### Reproduction link
[github.com](https://github.com/last-partizan/vue2.7-vite-img-src)

### Steps to reproduce
Just run example.

### What is expected?
It should display vue logo.

### What is actually happening?
It doesn't

---
This exact code works fine with vue-3 (just switch branch to `vue-3` and run again).

**Comment by yyx990803** [comment]
fixed in 008d78bd
