### ISSUE TITLE
Why does re-initialising a Vue 2 app doesn't work

### ISSUE THREAD

**Issue by pramodjodhani** [vuejs/vue#12586]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-app-reinitialize-example-qcovs4?file=/index.html)

### Steps to reproduce
I'm using Vue not as a SPA, but only as a widget on a page. There is a popup plugin (a jQuery plugin thats working outside of Vue) that deletes the Vue app's HTML and puts it back again to reposition it. I want to re-initiate the Vue app after repositioning is done by the popup plugin. I don't have access to the popup plugin and cannot change the way it works. After I reinitiate the Vue instance it doesn't work at all. 

### What is expected?
There should be a way to re-initiate the Vue App. 

### What is actually happening?
All event listeners stop working after the app is re-initialized. 

---
I have briefed the problem in this screencast: https://screencast-o-matic.com/watch/c31U1aV02rR

**Comment by posva** [comment]
This is because you cannot manually change the DOM that is handled by Vue. If you do Vue, has no way to correctly update it

**Comment by troy351** [comment]
After `new Vue`, DOM changed to a rendered result not the original Vue template.
e.g. from `<button @click="add">count is {{count}}</button>` to `<button>count is 0</button>`.
And initiate Vue from a rendered result won't work apparently

**Comment by pramodjodhani** [comment]
Hi @troy351 and @posva, Thank so you much for your reply. That definitely makes sense.  Can you think of ANY workaround to make this still work? I'm absolutely okay if the state reset to default and app would start afresh. 

I have tried to remove the HTML and set it again so that Vue would consider it as a different template but that also doesn't help. 

![image](https://user-images.githubusercontent.com/5794565/176390220-11f2882a-c3bf-4c47-95bc-e46a49521dc3.png)

Again, I really appreciate your help 🙌

**Comment by posva** [comment]
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by pramodjodhani** [comment]
I'm sorry @posva. I will post on the forum. Thanks
