### ISSUE TITLE
发布软件的正确流程是什么？

### ISSUE THREAD

**Issue by bbhxwl** [vuejs/vue#12585]
### What problem does this feature solve?
我如果每次生成完了上传服务器，名称每次不一样，所以我先删除全部，再上传。这样会造成已经在访问的人，访问可能会404，js不存在之类的。如果不删的话。发布多次可能没用的文件太多。而且正在访问的人也一直用的不是正式版。我应该怎么让他们在我发布新的后，用的是我新的程序？如果让名称不随机，是不是又有缓存问题？

### What does the proposed API look like?
我如果每次生成完了上传服务器，名称每次不一样，所以我先删除全部，再上传。这样会造成已经在访问的人，访问可能会404，js不存在之类的。如果不删的话。发布多次可能没用的文件太多。而且正在访问的人也一直用的不是正式版。我应该怎么让他们在我发布新的后，用的是我新的程序？如果让名称不随机，是不是又有缓存问题？

**Comment by pandavips** [comment]
hello,这可能不是这个项目需要解决的问题，你应该使用更专业的部署工具来解决这个问题，比如jenkins

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
