### ISSUE TITLE
Variables starting with _ causes warning: "not defined on the instance but referenced during render"

### ISSUE THREAD

**Issue by lsdsjy** [vuejs/vue#12587]
### Version
2.7.0-beta.8

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-2-7-setup-prefixed-with-underscore-eclmmd)

### Steps to reproduce
See console output

### What is expected?
One warning:
`Avoid using variables that start with _ or $ in setup().`

(Like in Vue 3)

### What is actually happening?
Two warnings:

`Avoid using variables that start with _ or $ in setup().`

`Property or method "_a" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

---
I think the second warning may be redundant.

**Comment by yyx990803** [comment]
This is fine since both warnings make sense and they do not affect behavior.
