### ISSUE TITLE
Upgrading to vue 2.7 broke vue-grid-layout

### ISSUE THREAD

**Issue by 2-5** [vuejs/vue#12598]
### Version
2.7.0

### Reproduction link
[codepen.io/collection/GoZoMJ](https://codepen.io/collection/GoZoMJ)

### Steps to reproduce
After opening the second code pen from the collection (version 2.7) you will see a grid of numbered rectangular gray panes.

Try dragging them around with the mouse or resizing them by the lower right corner.

### What is expected?
The rectangular panes should be draggable and resizable with the mouse.

### What is actually happening?
Panel dragging and resizing doesn't work.

It does work if vue 2.6.14 is used, like in the first code pen from the collection.

**Comment by posva** [comment]
Please open the issue in vue-grid-layout
