### ISSUE TITLE
Yet another prop and event handler shorthand

### ISSUE THREAD

**Issue by zsakowitz** [vuejs/vue#12599]
### What problem does this feature solve?
I commonly need to pass props down from one component to a child component. For example, I recently wanted to pass a `disabled` prop to a subcomponent called <Button />. I feel that writing

```vue
<Button :disabled="disabled" />
```

feels too cluttered. When people have suggested this elsewhere, some recommend using

```vue
<Button v-bind="{ disabled "} />
```

The problem with this approach is that an unnecessary `v-bind` is introduced which could be omitted.

### What does the proposed API look like?
I understand that the shorthand syntax

```vue
<Button :disabled @click />
```

has been scrapped [many](https://github.com/vuejs/vue/issues/5835), [many](https://github.com/vuejs/vue/pull/2877), [many](https://github.com/vuejs/vue/issues/6416), [many](https://github.com/vuejs/vue/issues/7144), [many](https://github.com/vuejs/vue/issues/9253), [many](https://github.com/vuejs/vue/issues/10463), [many](https://github.com/vuejs/vue/issues/11103) (holy moly, the list just keeps going) times in the past, but I propose a new syntax similar to Svelte's prop shorthands.

```vue
<Button {disabled} {@click} />
```

The above syntaxes are similar to the existing object shorthand in JavaScript, so it would feel familiar to new developers. Furthermore, it would not be a breaking change (compared to #5835) since Vue props rarely use curly braces in their names.

If possible, I would also wish for a shorthand such as

```vue
<Button {disabled, @click} />
```

to be allowed, but I realize that the space in the attribute name prevents it from being valid HTML.

**Comment by posva** [comment]
This should go in the vue/rfcs repo. Check there if there is an already open proposal.
