### ISSUE TITLE
vue 2.7.0  vm.$el is an HTML comment (<!----->) when I render jsx

### ISSUE THREAD

**Issue by sanding0** [vuejs/vue#12606]
### Version
2.7.0

### Reproduction link
[codepen.io](https://codepen.io/sanding0/pen/mdxJNQr?editors=0010)

### Steps to reproduce
babel:   "@vue/babel-preset-jsx": "^1.2.4"

### What is expected?
render succeeds

### What is actually happening?
the $el is a comment after $mount when I use jsx

**Comment by yyx990803** [comment]
Don't use arrow functions for `render()` because it won't get automatic `h` injection.

**Comment by dasDaniel** [comment]
I'm seeing a similar issue

When moving a component to use setup, I thought I could use the `return` from `setup` , but I'm seeing that it returns the comment. 
example: https://github.com/dasDaniel/vue-jsx-render-fun

AFAICT, there isn't a Vue v.2 equivalent of https://github.com/vuejs/babel-plugin-jsx 

I'd like to use something like this

```jsx
export default defineComponent({
  setup() {
    return <h1>HELLO</h1>;
  },
});
```
I'm getting the error `TypeError: this is null`, presumably from `const h = this.$createElement`

Is returning a JSX render function incompatible with 2.7 or is there a plugin available that handles this?
