### ISSUE TITLE
Wrong types for the .tsx elements

### ISSUE THREAD

**Issue by dawidreedsy** [vuejs/vue#12607]
### Version
2.7.0

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/focused-chatterjee-592rq0?file=/test.tsx:0-36)

### Steps to reproduce
Example code to get the wrong type

```
const spanElement = <span>a</span>
```

### What is expected?
Previously it gave the any type now it is giving `JSX.Element` for all the tags. I believe above code should return `HTMLSpanElement` not `JSX.Element`. This has changed in alpha 6 https://github.com/vuejs/vue/compare/v2.7.0-alpha.5...v2.7.0-alpha.6

### What is actually happening?
I cannot use any of the element functions like `outerHtml` as the TypeScript is complaining about the types.

**Comment by yyx990803** [comment]
Despite its return type, the type of a JSX expression is **not** native HTML elements. I don't know how ti worked previously for you but they've never been actual DOM elements.

**Comment by yyx990803** [comment]
The actual value of a JSX expression in Vue is a **VNode instance**, not an actual DOM element. Type of `spanElement` is `JSX.Element` which also extends `VNode` and the behavior of 2.7 is correct.

**Comment by dawidreedsy** [comment]
@yyx990803 
I actually dig deeper into the code of my project and apparently we use custom `renderJsx` function to speed up rendering of few components in our app. In the `tsconfig` we have this:
```
    "jsx": "react",
    "jsxFactory": "renderJsx",
```

and the `renderJsx` function it returns the native DOM elements, so the `jsx.d.ts` overridden our types, maybe worth to move them to definitely typed, so they can be optional?
