### ISSUE TITLE
SFC CSS v-bind doesn't create variable

### ISSUE THREAD

**Issue by oxypomme** [vuejs/vue#12621]
### Version
2.7.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/heuristic-panna-x1o6kd?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Upgrade to Vue 2.7.3
2. Create a component with some data
3. Link data in the style section with `v-bind`

### What is expected?
`v-bind` should create a CSS variable in the `style` attribute of the component's DOM element with the current value of the data **AND** translate the `v-bind(...)` into `var(...)` in the CSS.

### What is actually happening?
`v-bind(...)` is translated into `var(...)` in the CSS **BUT** there's no `style` attribute in the component's DOM element.

---
Note: I'm using TypeScript, SCSS and Nuxt. It may be an interference with one of these.

In minimal reproduction I have the same code (without TS and SCSS tho), the same versions, but I doesn't work at all on codesandbox...

**Comment by yyx990803** [comment]
Can't reproduce. CodeSandbox doesn't have proper 2.7 support because it doesn't actually run `webpack` and `vue-loader`.

**Comment by MissedWarrior** [comment]
I have the same issue with CSS v-bind, created a repo with reproduction. Repo was created with vue-cli and manually upgraded to vue 2.7 as stated in CHANGELOG.md [https://github.com/MissedWarrior/vue-2.7-css-binding](repro)

Intersting thing: there is no vue-demi package in lockfile even though I deleted both node_modules and lockfiles and reinstall packages

**Comment by CODPHISH** [comment]
same issue in vue2.7.8
