### ISSUE TITLE
Vue SFC template cannot display obj which has ref

### ISSUE THREAD

**Issue by Sleaf** [vuejs/vue#12630]
### Version
2.7.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vibrant-moon-qsi36f?file=/src/App.vue)

### Steps to reproduce
use obj which has ref variable in template mustache cannot render.
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Watcher'

    |     property 'vm' -> object with constructor 'VueComponent'

    |     property '_scope' -> object with constructor 'EffectScope'

    |     property 'effects' -> object with constructor 'Array'

    --- index 0 closes the circle

    at JSON.stringify (<anonymous>)
```

### What is expected?
render correctly like vue3

### What is actually happening?
error

**Comment by Teaghy** [comment]
please upgrade to 2.7.3 , I see your code, why do you put setup on top of script tag, maybe you can remove setup from script;

**Comment by Sleaf** [comment]
> why do you put setup on top of script tag

🤣 I didn't notice that, it fork from others,  hhhh

it works fine on 2.7.3, thank you! @Teaghy
