### ISSUE TITLE
Lack of some docs about 2.7

### ISSUE THREAD

**Issue by galenjiang** [vuejs/vue#12645]
### What problem does this feature solve?
With the release of Vue 2.7, which has Composition API built-in, but some api different from Vue@3, like as @vue/composition-api,  and that ts (definedComponent) support is also different from old version.
And the repo, @vue/composition-api , maybe deprecated by maintainer.
Where we should read docs about this section.

### What does the proposed API look like?
A new doc page about composition-api compatiable.

**Comment by maomincoding** [comment]
https://blog.vuejs.org/posts/vue-2-7-naruto.html?continueFlag=24b18743108fc3e584f79dec07a79f02

**Comment by yyx990803** [comment]
All new APIs in 2.7 that also exist in Vue 3 aim to have the same behavior with Vue 3 unless explicitly noted.

- For now, the [behavior differences](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#behavior-differences-from-vue-3) are documented in the changelog.
- With the above differences noted, if the API exists in Vue 3, use Vue 3 docs as a reference for API behavior.

**Comment by maomincoding** [comment]
> All new APIs in 2.7 that also exist in Vue 3 aim to have the same behavior with Vue 3 unless explicitly noted.
> 
> * For now, the [behavior differences](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#behavior-differences-from-vue-3) are documented in the changelog.
> * With the above differences noted, if the API exists in Vue 3, use Vue 3 docs as a reference for API behavior.

Thanks.

**Comment by galenjiang** [comment]
```javascript
import Vue, { VNode } from "vue";
import { ComponentRenderProxy } from "vue";

declare global {
  namespace JSX {
    interface Element extends VNode {}
    interface ElementClass extends ComponentRenderProxy {}
    interface ElementAttributesProperty {
      $props: any; // specify the property name to use
    }
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }
}

```
Some thing about type declare is missing, it didn't mentioned by changelog or blog.

**Comment by yyx990803** [comment]
Added a note on TS changes: https://github.com/vuejs/vue/blob/main/CHANGELOG.md#typescript-changes

**Comment by maomincoding** [comment]
Mr. You, you really teach me by hand.

**Comment by galenjiang** [comment]
Thanks

**Comment by jetBn** [comment]
> galenjiang

type  ComponentRenderProxy  how to solve
