### ISSUE TITLE
Vue 2.7 defineComponent type inference does not work for provide/inject

### ISSUE THREAD

**Issue by NikhilVerma** [vuejs/vue#12656]
### Version
2.7.5

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-4xhxlt?file=src/App.vue)

### Steps to reproduce
1. Open the URL - https://stackblitz.com/edit/vitejs-vite-4xhxlt?file=src/App.vue
2. In the terminal run - `vue-tsc`

### What is expected?

1. No errors to happen when we consume methods inside providers
2. Documentation on how to "type" injections

### What is actually happening?
```
src/App.vue:20:38 - error TS2339: Property 'increment' does not exist on type 'CreateComponentPublicInstance<{}, unknown, { counter: number; }, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

20       increment: computed(() => this.increment),
```

**Comment by yyx990803** [comment]
I'd say this is somewhat expected since your code contains other type errors. The missing props declarations breaks the inference of `startingCount` in `data()`, which in turn breaks `this.counter`, which is used in `increment()`. Not sure if there's anything we can do about this to be honest.
