### ISSUE TITLE
vue SFC type check was broken on tsx

### ISSUE THREAD

**Issue by iceprosurface** [vuejs/vue#12679]
### Version
2.7.0-2.7.7

### Reproduction link
[github.com](https://github.com/iceprosurface/vue2.7-tsx-error)

### Steps to reproduce
yarn serve

### What is expected?
no error

### What is actually happening?
throw error

---
@vue/compiler-sfc@2.7 & @vue/compiler-sfc@3.2 was not correct match
related to https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/765

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/main/src/typescript/extension/vue/type-script-vue-extension.ts#L28

fork-ts-check-plugin use `compiler.parseComponent` to check whether it is a vue2 version

```ts
  function isVueTemplateCompilerV2(
    compiler: VueTemplateCompilerV2 | VueTemplateCompilerV3
  ): compiler is VueTemplateCompilerV2 {
    return typeof (compiler as VueTemplateCompilerV2).parseComponent === 'function';
  }

```

https://github.com/vuejs/vue/blame/fc16281cf5bd1506e8cfe62eee1ef02dac82bad5/packages/compiler-sfc/src/parse.ts#L33

**Comment by iceprosurface** [comment]
Perhaps the package [compiler-sfc](https://github.com/vuejs/vue/tree/main/packages/compiler-sfc) should return version?

**Comment by yyx990803** [comment]
I'd say this is `fork-ts-checker` relying on unsafe heuristics here and should be fixed / improved. It should already be able to safely check the `@vue/compiler-sfc` version by loading the relevant `package.json`.
