### ISSUE TITLE
When I use the render function in the vue2.7+ version setup, I can't get the $refs of the dom correctly

### ISSUE THREAD

**Issue by a635273670** [vuejs/vue#12673]
### Version
2.7.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/serene-tesla-ebz2lr?file=/src/App.vue:189-207)

### Steps to reproduce
Use setup to return a render function, you can't get a reference to the ref dom after mounting; but it can be obtained in version 3.0+, I hope it can be consistent with 3.0

### What is expected?
dom re can be obtained

### What is actually happening?
The value of ref is still null

**Comment by MinatoHikari** [comment]
https://codesandbox.io/s/weathered-architecture-qeo8md

check @vue/composition-api's readme
https://github.com/vuejs/composition-api#template-refs
currently you can't use template ref in renderFn in setup.

**Comment by yyx990803** [comment]
Your reproduction doesn't work in Vue 3 either...

When using manual render functions in `setup()`, you need to pass the actual ref to the ref property:

```diff
      return h(
        "div",
        {
          class: "vue-charts",
-           ref: "chartRef"
+          ref: chartRef,
        },
        "helloWord"
      );
```

**Comment by a635273670** [comment]
Yes, this method does not work with vue3, but placing the render outside the setup can work, and vue2.7 will not work.
![image](https://user-images.githubusercontent.com/64343228/179393185-0560ff26-fc23-4c92-bea8-166abeb4753a.png)

**Comment by a635273670** [comment]
@yyx990803  thanks for your suggestion
