### ISSUE TITLE
Nested objects calling toRefs should not all return Ref objects

### ISSUE THREAD

**Issue by qqhtt** [vuejs/vue#12676]
### Version
2.7.7

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/beautiful-thompson-5x8ql7?file=/src/App.vue)

#### steps one
Define a props component that receives an array type

#### steps two
Call it in the parent component and use the v-model to bind an object returned by the toRefs method

#### steps three
The child component props validation returns an error

#### steps four
In this case, v-model= value of ref object can be used normally

### What is expected?
The toRefs method is expected to return a Ref object or a Reactive object based on the data type in the reactive object

### What is actually happening?
The toRefs method returns only Ref objects, which requires a ref.value object to be used when calling child components in the template

---
Using Ref objects in templates should not require a.value

**Comment by yyx990803** [comment]
I agree this can be confusing but this is expected behavior. Auto ref unwrapping only works on root-level bindings, see [relevant section in docs](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates) for more details.
