### ISSUE TITLE
Provide/Inject does not work within same component

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#12678]
### Version
2.7.7

### Reproduction link
https://github.com/johannes-z/vue27/tree/bug/provide-inject

### Steps to reproduce
1. git clone https://github.com/johannes-z/vue27/
2. git checkout bug/provide-inject
3. pnpm i
4. pnpm run dev

### What is expected?
`provide` in setup and `inject` in render should work. 

### What is actually happening?
An error is thrown:

> [Vue warn]: injection "Symbol(test)" not found.

---
With `@vue/composition-api` it's possible to provide a value in the `setup` and use `inject` in the render function, whereas `vue` only seems to check parents for provided values.

**Comment by jacekkarczmarczyk** [comment]
It seems to be now consistent with Vue 3 behaviour

**Comment by yyx990803** [comment]
This is expected behavior - 2.7 aligns everything with 3.x. Any deviance between `@vue/composition-api` plugin and v3 should be considered a bug and use v3 as the source of truth.

**Comment by StorkKershaw** [comment]
Possibly you can solve the problem with just instantiate the composable before injecting it.
```js
const someComposable = useSomeComposable()
provide(INJECTION_KEY, someComposable)

// below you can use someComposable
```
