### ISSUE TITLE
Destroy performance in Chromium browsers on macOS (w. potential solution)

### ISSUE THREAD

**Issue by kevinlee11** [vuejs/vue#12696]
### Version
2.7.8

### Reproduction link
[codesandbox.io/s/spqkdn](https://codesandbox.io/s/spqkdn?file=/src/views/Home.vue)

### Steps to reproduce
We’ve recently noticed a performance problem in our Vue 2 application when destroying 100+ item components in our grid, it can take a significant amount of time (30+ seconds). Each of our item components contains a lot of child components that all use a number of computed properties which is the root cause of this issue, as looking into how the destroy process works, it needs to clean all of them up. After doing some further digging we discovered this issue is **ONLY** occurring on Chromium browsers on macOS (tested on Chrome and Edge). Other browsers do not see this destroy delay.

Further performance digging has found the root cause to be the `Array.prototype.splice(`) in the remove function used by Vue in the destroy process.

![image](https://user-images.githubusercontent.com/18740390/180701814-55234317-2c05-4497-94ed-8d576794d3d2.png)

In the name of looking for an easy win, simply switching the logic in the remove function to use `Array.protoype.pop()` instead fixes the issue.

![image](https://user-images.githubusercontent.com/18740390/180701842-1c97db0d-d5d9-4f76-ab7e-82edb922622d.png)

Of course, this approach would only work if the order of the arrays passed into the remove function did **NOT** matter. Looking at the source code I can see there’s a number of files that make use of this remove function in the util file, and I don’t know the codebase well enough to understand the ramifications of this particular approach.

Could be we might need to create an alternative remove function that can be called by callers who don’t care about the order of their arrays (assuming some do care about the order)?

Hoping some people can chime in on this, thanks! 🙂

Note the attached minimal reproduction is a very simplified version of the issue.

### What is expected?
Destroy should happen without any major delays.

### What is actually happening?
Destroy takes 30+ seconds.

**Comment by yyx990803** [comment]
This sounds more like a Chromium/V8 bug, and likely a recent regression. I would suggest reporting this to Chromium/V8 instead since it's a pretty serious defect.

**Comment by kevinlee11** [comment]
@yyx990803 Thanks for the quick response, logged an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1347350.

For a temporary fix, not sure if you know off the top of your head if the arrays passed into the remove are dependent on order, and whether in our application's build process, we could modify the remove logic to use pop? Or even if we could offload some of the callers into a new `popRemove` function, it would help us immediately address the issue.

**Comment by Tofandel** [comment]
From your repro it took 20 seconds for me on Chrome, Firefox and Edge on windows (impressively edge was a bit faster)

Given that there is 10 000 elements would you say that 20 seconds is expected?

It couldn't hurt to have those kind of performance improvements though

**Comment by kevinlee11** [comment]
I think there is a perf issue with Chromium which really exasperates this particular issue, esp if there's a ton of watchers and computed props with lot of children elements (beyond my simple sample).

For a basic test I whipped this up: https://codesandbox.io/s/ih7t95?file=/src/index.js

And you'll notice it takes ~15-25 seconds on any Chromium browser vs ~0.05s on Firefox
![image](https://user-images.githubusercontent.com/18740390/188155005-3b335851-35da-4e52-b48c-9dcd9d23eb7e.png)
![image](https://user-images.githubusercontent.com/18740390/188155035-bf4232d1-f232-4d24-8a25-925ba76a7151.png)

Doesn't seem like Chromium will get around to solving that anytime soon, the bug I logged is still untriaged.

**Comment by Tofandel** [comment]
Okay now on this reproduction I'm getting the same result as you, weird that for the vue one even firefox takes 30+ seconds then

**Comment by kevinlee11** [comment]
Ya I think it's prob I just don't have a deep enough sample with fewer components but a lot more child components with a large number of watchers/computed props which is what causes this perf issue. In my team's actual prod site we only see the slow destroy on Chromium browsers.
