### ISSUE TITLE
add provides property to vue instance

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#12697]
### Version
2.7.8

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eNplULtuwzAM/BVWi10gltDVcAIUXdov6KLFdWjHgV6QaHcw9O+lnDRLNt0d78jTJt5DkOuCohVdGuIcCBLSEk7azTb4SLBBxPEAE9LHEiM6+nKJejcgZBijt1CxvdJOu8GzAjZNcCyeuvpEYzx8+2jOL9Xr/8BqWX+Oq+8D3qA0fqpXy0SnbkfxOQwIbTA9ISOA7vJ22rZ9Xc6dYrSzswsL72isP6M5asG6Fix16uEWB3Hr1tg+yGvyjttvxa3vQtKihZ0pHPcrWIsLUUitUmkcyp9dk/RxUvyScXE0W5SYbPMT/W/CyMFalIisXRb5D3Uqfm4=)

### Steps to reproduce
Inspect the vm returned by `getCurrentInstance`.

### What is expected?
Vue 2.7 should also define the property `provides` to align with Vue 3.

### What is actually happening?
Vue 2.7 does not have the `provides` property. You have to access `provides` by doing this:

```ts
  const vm = getCurrentInstance() as any
  const provides = vm?.proxy?._provided // vm?.provides in Vue3
```

**Comment by yyx990803** [comment]
This is intentional. Internal instance properties are internal and your code should never rely on it.

**Comment by johannes-z** [comment]
Bummer, this seemed like a good solution, were the `<Root>` component also needs access to the state that's provided.

The reason why this is needed in the first place: I created a component that shows data from a 3rd party data source. The component can be configured (e.g. endpoints) with props by the consumer, so there are a lot of props that need to be used through-out the component tree (<Root>, the table component, search bar, etc.)

I often read that you should define `refs` in the root of the file, rather than in the `useXYZ` function. But since my consuming App can have multiple instances of my component (even nested), the state would be global over all instances, not just the component tree.

```ts
// useXYZ.ts - new state each time I call useXYZ
export function useXYZ () {
  const state = ref(0)
  return { state }
}
// useXYZ.ts - global state for all instances
const state = ref(0)
export function useXYZ () {
  return { state }
}
```

Is there an official way to do this? `provide/inject` is the only thing that comes to mind, but the providers also relies on the data. The only way I can think of is 2 separate functions: one for initialization/providing and one for usage/injection.
