### ISSUE TITLE
style标签设置scoped属性，文件有修改后构建造成短时间的页面样式丢失

### ISSUE THREAD

**Issue by dafengxiang** [vuejs/vue#12691]
### Version
2.7.7

### Reproduction link
[vip.iqiyi.com](https://vip.iqiyi.com/2022thegodfather.html)

### Steps to reproduce
style标签设置scoped属性，文件有修改后构建生成的data-v-xxx属性中hash与修改前构架版本中hash不同，因为网络等原因css文件与js文件更新不同步，用户获取的css文件中data-v-xxx属性与js中的不一致，造成短时间的页面样式丢失

### What is expected?
期望data-v-xxx属性中hash值生成与文件内容无关（或可配置生成规则），只与文件路径相关，这样每次构建结果中data-v-xxx属性值都是保持不变的，不会造成页面样式丢失

### What is actually happening?
data-v-xxx属性中hash值生成与文件内容相关，修改文件内容会生成新的hash值

**Comment by Justineo** [comment]
请提供一个有效的重现链接。参见：https://new-issue.vuejs.org/?lang=zh-cn#why-repro

**Comment by dafengxiang** [comment]
这个是短时间存在的，是因为页面css文件和js文件网络缓存匹配不上

**Comment by dafengxiang** [comment]
> 请提供一个有效的重新链接。参见：https://new-issue.vuejs.org/?lang=zh-cn#why-repro

这个是短时间存在的，是因为网络等原因css文件和js文件更新版本匹配不上，造成用户页面样式丢失
