### ISSUE TITLE
Memory leaking when create computed of composition-api outside of setup() scope

### ISSUE THREAD

**Issue by enrilzhou** [vuejs/vue#12698]
### Version
2.7.8

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/romantic-swartz-f86eel?file=/src/App.vue)

### Steps to reproduce
1. Click the "Trigger Memory Leak" button on the linked reproduction page.
2. Click the "destroy MemoryLeak Component" button, then force GC by browser dev tools.

### What is expected?
The computed watchers are GCed.

### What is actually happening?
The computed watchers are NOT GCed.

**Comment by yyx990803** [comment]
This is expected behavior. Computed refs must be created synchronously within `setup()` to be "linked" to its owner component so that they can be stopped on component unmount.

Creating computed like this will surely lead to memory leaks. In short: don't do it.
