### ISSUE TITLE
vue2.7 setup不支持vuex3  pinia不支持IE 有什么解决方案么

### ISSUE THREAD

**Issue by longge951123** [vuejs/vue#12704]
如题，想将现有项目从2.6 升到 2.7 
vuex3 提供的mapGetters, mapActions 在vue2.7的setup的computed 不支持
放在外层的computed或使用getCurrentInstance 又做不到setup中数据响应式
替换pinia  IE又不兼容

[https://github.com/vuejs/vue/issues/12651](url)

请问有什么方案兼容在vue2.7中使用vuex响应式方式么
可以出个2.7 使用setup router与vuex兼容包么

**Comment by Ch2x** [comment]
pinia does not support ie?

**Comment by longge951123** [comment]
> pinia不支持ie？



> pinia does not support ie?

yes  
vue2.6 upgrade vue2.7 
vuex poor compatibility
vue2.x is used for IE compatibility，otherwise use vue3.x
