### ISSUE TITLE
::v-deep is not working

### ISSUE THREAD

**Issue by handhikadj** [vuejs/vue#12708]
### Version
2.7.8

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/wizardly-panini-oqizcy)

### Steps to reproduce
look at the .Vue components and the result tab

### What is expected?
::v-deep is working

### What is actually happening?
::v-deep is not working

---
I got projects and v-deep is working. don't know why it's not working on this one. I don't think I'm doing wrong on the sandbox, am I?

**Comment by donaf** [comment]
In you demo, in `package.json` ,  i have not see any `dependencies` about  `sass` 、`sass-loader`
if you want to use like this:
```vue
<style lang="scss" scoped>
::v-deep .h3 {
  color: blue !important;
}
</style>
```
you'll need to install `sass-loader`
``` cmd
yarn add -D sass-loader sass
```

or, you can use as this:
```  vue
<style  scoped>
>>> .h3 {
  color: blue !important;
}
</style>
```

**Comment by handhikadj** [comment]
thanks for responding. still not working anyway: https://codesandbox.io/s/distracted-panna-t1xvx6

**Comment by yixiu025** [comment]
![image](https://user-images.githubusercontent.com/33720237/181543792-2428c65e-c0ab-4330-811c-d42114b8a1fb.png)
![image](https://user-images.githubusercontent.com/33720237/181542884-e31710ca-aa75-4e81-bcc8-05b8e211bfea.png)
I tried it and found that this is the result, but I don't know why, looking forward to the reply from God...

**Comment by fiCeVitka** [comment]
You should use syntax of vue 3 with :deep instead ::v-deep or >>>

**Comment by JC-Guy** [comment]
use :deep() instead. e.g. :deep(.el-card__body){ width: 200px; }

**Comment by yyx990803** [comment]
CodeSandbox does not correctly support Vue 2.7. Don't use it for reproducing issues.

`::v-deep` is working correctly in local Vue CLI or Vite based projects.
