### ISSUE TITLE
Vue 2.7+ no longer fails on and report type errors in build and serve commands

### ISSUE THREAD

**Issue by RuudV** [vuejs/vue#12719]
### Version
2.7.8

### Reproduction link
[github.com](https://github.com/RuudV/vuejs-type-bug-demo)

### Steps to reproduce
Based from the `vuejs-type-bug-demo` root folder:

* `cd ./hello-world-2.6 && npm install && npm run build`
* `cd ./hello-world-2.7 && npm install && npm run build`

### What is expected?
In 2.7 I expect the errors in typing to fail the build as it does in 2.6

### What is actually happening?
Succeeding the build without any errors thrown

**Comment by nieyuyao** [comment]
This seems to be a `compiler-sfc` issue that causes the `ForkTsCheckerWebpackPlugin` to not get the correct script.

**Comment by yyx990803** [comment]
This relies on `ts-loader` to fix its compatibility with Vue 2.7.

The latest recommendation, however, is to avoid doing type check as part of the webpack build, and instead using [vue-tsc](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc). You can start it in a separate process in watch mode.

**Comment by RuudV** [comment]
Will try that, but it would be nice if this got mentioned in the upgrade to vue 2.7+. So users can determine if they can spare the extra time invested to setup vue-tsc and disable type checking in webpack during serve and build commands.

**Comment by rossinek** [comment]
I can confirm that this particular problem is fixed in `2.7.11`
