### ISSUE TITLE
2.7.x Building legacy bundle for production | Declaration or statement expected.

### ISSUE THREAD

**Issue by ademyalcin27** [vuejs/vue#12714]
### Version
2.7.8

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/typescript-awsjij?file=package.json)

### Steps to reproduce
<img width="681" alt="Screen Shot 2022-07-29 at 11 20 06" src="https://user-images.githubusercontent.com/5026172/181717767-9291d3be-2eb1-45cb-9fc6-705d04b2513b.png">

(node:9752) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(Use `node --trace-deprecation ...` to show where the warning was created)
⠴  Building legacy bundle for production...

 ERROR  Failed to compile with 4 errors                                               

 error  in node_modules/vue/types/jsx.d.ts:39:7

TS1110: Type expected.
    37 |    * https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors
    38 |    */
  > 39 |   [v: `--${string}`]: string | number | undefined
       |       ^^^^^
    40 | }
    41 |
    42 | type Booleanish = boolean | 'true' | 'false'

 error  in node_modules/vue/types/jsx.d.ts:39:20

TS1005: ';' expected.
    37 |    * https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors
    38 |    */
  > 39 |   [v: `--${string}`]: string | number | undefined
       |                    ^
    40 | }
    41 |
    42 | type Booleanish = boolean | 'true' | 'false'

 error  in node_modules/vue/types/jsx.d.ts:39:21

TS1128: Declaration or statement expected.
    37 |    * https://github.com/frenic/csstype#what-should-i-do-when-i-get-type-errors
    38 |    */
  > 39 |   [v: `--${string}`]: string | number | undefined
       |                     ^
    40 | }
    41 |
    42 | type Booleanish = boolean | 'true' | 'false'

 error  in node_modules/vue/types/jsx.d.ts:40:1

TS1128: Declaration or statement expected.
    38 |    */
    39 |   [v: `--${string}`]: string | number | undefined
  > 40 | }
       | ^
    41 |
    42 | type Booleanish = boolean | 'true' | 'false'
    43 | type Numberish = number | string

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.

### What is expected?
to build success

### What is actually happening?
gettin error and doesnt build project

**Comment by posva** [comment]
You need to upgrade your TypeScript version to support string literals

**Comment by ademyalcin27** [comment]
> You need to upgrade your TypeScript version to support string literals

thank you. that's worked;)

**Comment by lukaslaskovski** [comment]
@ademyalcin27 Which version 4.x typescript supports string literals ? I tried 4.1.5 but got some other errors.

**Comment by ademyalcin27** [comment]
> @ademyalcin27 Which version 4.x typescript supports string literals ? I tried 4.1.5 but got some other errors.

I explained it here
https://medium.com/@ademyalcin27/vue-2-to-vue-3-migration-adventure-e35fa0627b16
