### ISSUE TITLE
Slots break when passing to child component

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#12712]
### Version
2.7.8

### Reproduction link
[github.com/johannes-z/vue27](https://github.com/johannes-z/vue27)

### Steps to reproduce
1. git clone https://github.com/johannes-z/vue27.git
2. git checkout -b bug/slots
3. pnpm install
4. pnpm run dev

### What is expected?
`ChildComponent` should print `customSlot` AND `rootSlot`.

expected rendered HTML:

```html
<div>
   <div>test</div>
   <div>default: </div>
   <div>rootSlot: scopedSlot from Root</div>
   <div>customSlot: <b>scopedSlot from MainComponent</b></div>
</div>
```

### What is actually happening?
`rootSlot` is missing already missing from `$scopedSlots` inside `MainComponent`.

actually rendered HTML:

```html
<div>
   <div>test</div>
   <div>default: scopedSlot from Root</div>
   <div>rootSlot: </div>
   <div>customSlot: <b>scopedSlot from MainComponent</b></div>
</div>
```

---

**Comment by yyx990803** [comment]
Your app template slot syntax is wrong:

```vue
- <template name="rootSlot" slot-scope="props">
+ <template slot="rootSlot" slot-scope="props">
```
