### ISSUE TITLE
Incomplete vue/dist files causes broken webjars/vue 

### ISSUE THREAD

**Issue by okoell** [vuejs/vue#12734]
### Version
2.7.8

### Reproduction link
[github.com](https://github.com/webjars/vue/blob/master/pom.xml)

### Steps to reproduce
- build a SpringBoot application
- include dependency to webjars/vue@2.7.8
- setup a script tag to include the vue.runtime.min.js
=> vue.runtime.min.js is not included in the webjars bundle

### What is expected?
The vuejs/vue repo should have a complete distribution of Vue in the vue/dist directory.

### What is actually happening?
Since the 2.7.x releases vue/dist only contains 3 javascript files that depend on other modules not included in the directory.

---
vue@2.6.14 is the latest release containing a complete distribution in vue/dist.

The webjars/vue project relies on vue/dist containing a workable distribution.

**Comment by sodatea** [comment]
https://github.com/vuejs/vue/issues/12592#issuecomment-1171990780
