### ISSUE TITLE
Link to vuejs 2 documentation in description of repository details

### ISSUE THREAD

**Issue by dpschen** [vuejs/vue#12746]
### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
Open vuejs/vue repository on GitHub

### What is expected?
It should link to the archived v2 documentation https://v2.vuejs.org/

### What is actually happening?
The description of the repository details is linking to the documentation of vue v3, that is hosted directly on https://vuejs.org instead.

---
See image:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/6173598/184820524-38dbf82c-0a32-4e92-8b12-ba18ff4b3fdd.png">

**Comment by LinusBorg** [comment]
Good point, done!
