### ISSUE TITLE
use "v-for" and "v-if" on a same <template> tag render strange

### ISSUE THREAD

**Issue by sommouns** [vuejs/vue#12749]
### Version
2.4.4

### Reproduction link
[codepen.io](https://codepen.io/sommouns/pen/rNdQgxp)

### Steps to reproduce
```
<template>
  <div>
    <template v-for="item in [1, 2, 3, 8]" v-if="flag === 1">{{item}}</template>
    <template v-for="item in [5, 6, 7]" v-else>{{item}}</template>
  </div>
</template>

data: {
  flag: 2
}
```
### What is expected?
render "5 6 7"

### What is actually happening?
render "5 6 7 5 6 7 5 6 7 5 6 7"

**Comment by sodatea** [comment]
https://v2.vuejs.org/v2/guide/list.html#v-for-with-v-if
It is strongly discouraged to use `v-if` and `v-for` on the same node.
So I don't think this behavior is worth fixing.
