### ISSUE TITLE
Breaking change vue 2.7.8 with vue-composition-api 1.7.0

### ISSUE THREAD

**Issue by karachungen** [vuejs/vue#12752]
### Version
2.7.8

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-2-7-ref-issue-ofeh52?file=/src/App.vue)

### Steps to reproduce
[Vue 2.7.8 Sandbox](https://codesandbox.io/s/vue-2-7-ref-issue-ofeh52?file=/src/App.vue)

[Vue 2.6 + vue/composition-api Sandbox](https://codesandbox.io/s/vue-composition-api-wskmg3?file=/src/App.vue)

### What is expected?
[Vue 2.7 Sandbox](https://codesandbox.io/s/vue-2-7-ref-issue-ofeh52?file=/src/App.vue) passes assert function like in [Vue 2.6 + vue/composition-api Sandbox](https://codesandbox.io/s/vue-composition-api-wskmg3?file=/src/App.vue)

The first value inside array must preserve same structure as it was inited (with own ref for innerProp).

### What is actually happening?
Assert function is not passed in [Vue 2.7 Sandbox](https://codesandbox.io/s/vue-2-7-ref-issue-ofeh52?file=/src/App.vue)  

---
In [Vue3](https://codesandbox.io/s/vue-composition-api-wskmg3?file=/src/App.vue) assert function also not passed so i suppose that it how it should works actually.

**Comment by yyx990803** [comment]
Vue 2.7 behavior tries to align with Vue 3 wherever possible. There is no guarantee in terms of behavior consistency with `@vue/composition-api`, since any behavior from the plugin that differs from Vue 3 should in fact be considered a bug.
