### ISSUE TITLE
An error occurred when I used the built-in component element in jsx

### ISSUE THREAD

**Issue by luichooy** [vuejs/vue#12769]
### Version
2.6.14

### Reproduction link
[v2.cn.vuejs.org/v2/api/](https://v2.cn.vuejs.org/v2/api/#component)

### Steps to reproduce
I used Vue.js built-in component element as follow:
"&lt;component is={comp}  /&gt;"
And const comp is a  ComponentConstructor  that was already imported from the other .vue file

### What is expected?
Vue can recognise the built-in component element

### What is actually happening?
The error "[Vue warn]: Unknown custom element: <component> - did you register the component correctly? For recursive components, make sure to provide the "name" option." was print to Console

---
I wonder that it's a bug or becasue of jsx

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
