### ISSUE TITLE
SFC <script setup> not tree-shakable

### ISSUE THREAD

**Issue by 1593292349** [vuejs/vue#12765]
### Version
2.7.10

### Reproduction link
[github.com](https://github.com/1593292349/Test-tree-shakable.git)

### Steps to reproduce
1.Pull my project and install the dependency
2.Run the command `npm run build`
3.Compare the `src/app.vue` source code with the packaged `dist/main.js` code
4.I didn't use test2 or test3 in `src/app.vue`, But it's still inside `dist/main.js`
5.If I use <script> Rather than <script setup>, `dist/main.js` will not contain test2 and test3

### What is expected?
`dist/main.js` not contain code for test2 and test3

### What is actually happening?
`dist/main.js` contain code for test2 and test3

---
There is no problem in vue 3.2.37 + vue-loader 17.0.0
vue 2.7.10 + vue-loader 15.10.0  has some problems

**Comment by 1593292349** [comment]
![1](https://user-images.githubusercontent.com/48791868/187040708-503dfbb1-f7df-4e72-a046-b8acce9981bb.png)
SFC <script setup> not tree-shakable

**Comment by 1593292349** [comment]
![2](https://user-images.githubusercontent.com/48791868/187040735-71efc62d-92ae-4262-934c-2212767da996.png)
SFC <script> tree-shakable

**Comment by jens-morten-mikkelsen** [comment]
👀
