### ISSUE TITLE
;(value as any).__proto__ = arrayMethods Question point

### ISSUE THREAD

**Issue by xiaoxiaoyuanwang** [vuejs/vue#12768]
### What problem does this feature solve?
Looking at Observer today, I found a question

if (hasProto) {
          /* eslint-disable no-proto */
          ;(value as any).__proto__ = arrayMethods
          /* eslint-enable no-proto */
        } else {
          for (let i = 0, l = arrayKeys.length; i < l; i++) {
            const key = arrayKeys[i]
            def(value, key, arrayMethods[key])
          }
        }
这里的;(value as any).__proto__ = arrayMethods前面的“；”有什么特殊含义？

### What does the proposed API look like?
if (hasProto) {
          /* eslint-disable no-proto */
          ;(value as any).__proto__ = arrayMethods
          /* eslint-enable no-proto */
        } else {
          for (let i = 0, l = arrayKeys.length; i < l; i++) {
            const key = arrayKeys[i]
            def(value, key, arrayMethods[key])
          }
        }
这里的;(value as any).__proto__ = arrayMethods前面的“；”有什么特殊含义？

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

**Comment by sodatea** [comment]
无分号风格的写法会要求当 `(`, `[`, ``` ` ``` 出现在行首时必须在前面加一个 `;`
参见：https://standardjs.com/rules-zhcn.html#%E5%85%B3%E4%BA%8E%E5%88%86%E5%8F%B7

**Comment by xiaoxiaoyuanwang** [comment]
@sodatea 谢谢大佬指点
