### ISSUE TITLE
productionTip

### ISSUE THREAD

**Issue by 5-seasons** [vuejs/vue#12760]
### Version
2.7.9

### Reproduction link
[v2.cn.vuejs.org/js/vue.js](https://v2.cn.vuejs.org/js/vue.js)

### Steps to reproduce
I set ‘Vue.config.productionTip = false’ but it doesn't work.

### What is expected?
Production tips should be cancelled.

### What is actually happening?
The console production prompt is not canceled.

**Comment by nooooooom** [comment]
Can you provide a minimal reproduction, or a code snippet on your use of  Vue, as far as I know `productionTip` works on 2.7.9.

Maybe the timing of your settings is wrong. According to the source code, we should configure it immediately after Vue is loaded.

```js
if (inBrowser) {
      setTimeout(function () {
          // ...
          if (config.productionTip !== false &&
              typeof console !== 'undefined') {
              console[console.info ? 'info' : 'log']("You are running Vue in development mode.\n" +
                  "Make sure to turn on production mode when deploying for production.\n" +
                  "See more tips at https://vuejs.org/guide/deployment.html");
          }
      }, 0);
  }
```

**Comment by 5-seasons** [comment]
This is the HTML file content
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>

  </style>
  <!-- <script src="./js/vue.js"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/vue@2.7.9/dist/vue.js"></script>
</head>

<body>
  <div id="app">
    <vc></vc>
  </div>
  <script>
    Vue.config.productionTip = false;

    const template = `<div>
      <h1>Hello World!</h1>
      <h2>我是{{ name }}</h2>
    </div>`
    const vc = Vue.extend({
      template:template,
      data() {
        return {
          name: 'Tom'
        }
      }
    })

    const vm = new Vue({
      el: '#app',
      data: {
        mes: '信息...'
      },
      components: {
        vc
      }
    })
  </script>
</body>

</html>
html```

**Comment by nooooooom** [comment]
你说的提示应该是 `devtools` 这个配置发出的，如果你不需要使用 devtools 你可以将 `config.devtools` 设置为 `true` 来关闭提示

**Comment by posva** [comment]
Seems to work: https://jsfiddle.net/kwgto5du/

**Comment by 5-seasons** [comment]
> Seems to work: https://jsfiddle.net/kwgto5du/

![0657ad74b7d9e1fe365650b45586e7b8aeea84072b6aec83f09e91f3a9bbea58QzpcVXNlcnNcNS1zZWFzb25zXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wyMzQzODQ5OTY0X3YyXEltYWdlRmlsZXNcMTY2MTM0MTMyMDg1N18zOUYyRTIwNi0zMjcyLTQ3NjUtQTQzOS1FODFDOTk5MEM1NTcucG5n](https://user-images.githubusercontent.com/62876589/186409916-a62cb1ca-0098-4215-9ebc-18ac165bb58c.png)

**Comment by posva** [comment]
it only happens when loading the jsfiddle for the first time though. Maybe 0 is not enough on that setTimeout

**Comment by socalledhentai** [comment]
In the new version of chrome and edge. You use the code settimeout(func, 0) in the first js code introduced in html using <script>, which will call back immediately after the first js is allowed to finish.
Interestingly, Firefox and the same version of Chromium do not have this problem. Apparently, there is a change in the event loop of Chrome and Edga.
At least this approach worked at one time.
