### ISSUE TITLE
Changing an item of an array directly by its index triggers a view responsiveness

### ISSUE THREAD

**Issue by qq88310566** [vuejs/vue#12761]
### Version
2.7.8

### Reproduction link
[jsfiddle.net](https://jsfiddle.net/chenbingting/9u7g6nsc/11/)

### Steps to reproduce
```
<template>
   <div id="app">
        {{a[0]}} {{b[0].b}}
  </div>
</template>

```

```
data: {
   a:["hello"],
   b:[{"b":"world"}]
},
mounted() {
  this.a[0] = "world"
  this.b[0].b ="hello"

}
```

### What is expected?
hello hello

### What is actually happening?
world hello

**Comment by LinusBorg** [comment]
aassigning to `this.b[0].b` triggers a re-render of *the component template*. In that re-render, the latest data will be used for *all content*, so this behavior is totally normal.
