### ISSUE TITLE
Confusing v-deep deprecation message

### ISSUE THREAD

**Issue by rchl** [vuejs/vue#12783]
### Version
2.7.10

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
The message:

https://github.com/vuejs/vue/blob/0f1d7ae29a1d785a2979dc640aa5f5cecf83cf85/packages/compiler-sfc/src/stylePlugins/scoped.ts#L132-L133

also triggers in this case:

```vue
<style lang="scss" scoped>
:deep {
  h1 {
    content: '';
  }
}
</style>
```

Notice how there is no `::v-deep` here and the warning still triggers.

### What is expected?
The warning mentions `:deep` also.

### What is actually happening?
The warning only mentions `::v-deep`.

---
(The link to reproduction is a dummy because the link in the bug report for Vue 2 points at the Vue 3 template and so I don't have time to look for the Vue 2 template)

**Comment by yyx990803** [comment]
Deprecation warnings are removed in 2f335b2f - they are still in v3 so we should not force 2.x users to make changes.
