### ISSUE TITLE
Vue 2.7 组件库的组件怎么按需引入？ 

### ISSUE THREAD

**Issue by carr666** [vuejs/vue#12797]
### What problem does this feature solve?
组件按需引入

### What does the proposed API look like?
可以进行组件按需引入

**Comment by carr666** [comment]
用<script setup> 脚本 怎么重命名组件

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

**Comment by carr666** [comment]
> 感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

thank you
