### ISSUE TITLE
[2.7.10] Unexpected behavior of watcher callback triggered with composition API

### ISSUE THREAD

**Issue by mangogan-git** [vuejs/vue#12808]
### Version
2.7.10

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vue2-vite-watch-bug?file=README.md)

### Steps to reproduce
click "change id" button, `watch( ()=> props.obj, cb )` callback was triggered even `props.obj` not change anything

App.vue
```vue
<script setup>
import { ref } from 'vue'
import MyComponent from './components/MyComponent.vue'

const id = ref(1)
function toggle() {
  if (id.value === 1) {
    id.value = 2
  } else {
    id.value = 1
  }
}
</script>

<template>
<button @click="toggle"> Change Id </button>
<MyComponent :obj="{ key: 'test' }" />
</template>
```

MyComponent.vue
```vue
<script setup>
import { ref, watch } from 'vue'

const props = defineProps({
  obj: {
    type: Object,
    default: () => ({}),
  },
})

const count = ref(0)

// when App.vue change Ref<id>, watch callback also triggered
watch(
  () => props.obj,
  () => {
    console.log('trigger watch...')
    count.value += 1
  }
)

</script>

<template>
<div>
  <p>trigger count: {{ count }}</p>
</div>
<template>
```

### What is expected?
Watcher callback should not trigger

### What is actually happening?
Watcher callback triggered even props not change

**Comment by nooooooom** [comment]
Since your `App.vue` component's render function subscribes to the `id` changes, it will re-render when you click to toggle, which will cause `{ key: 'test' }` to be recreated. 

You can use a variable to save `obj` to avoid this.
