### ISSUE TITLE
script setup cannot work in vue2.7

### ISSUE THREAD

**Issue by weihenHong** [vuejs/vue#12805]
### Version
2.7.10

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/keen-ardinghelli-q4dyev?file=/package.json)

### Steps to reproduce
When I upgraded vue@2.7 in the old project , my code cannot work, However, I upgraded other projects to 2.7, everything is normal
So I guess there are other dependent effects ? I'm not sure .

```js 
<script setup>

const msg = 'Hello!';

console.log(msg);

function log() {

  console.log(msg);

}

</script>


<template>

<button @click="log">{{ msg }} </button>

</template>
``` 
error: 

error-log.js?b1fc:32 TypeError: Cannot read properties of undefined (reading 'msg')

### What is expected?
normal

### What is actually happening?
error-log.js?b1fc:32 TypeError: Cannot read properties of undefined (reading 'msg')

---

**this is my package.json, If there are other dependencies that affect  ?**

{

  "dependencies": {
  
    "@vue/babel-preset-app": "^4.5.4",

    "clipboard": "2.0.4",

    "codemirror": "5.45.0",

    "core-js": "^3.6.5",

    "cos-nodejs-sdk-v5": "^2.5.20",

    "crypto-js": "^4.0.0",

    "eslint-loader": "^4.0.0",

    "excel-loader": "^1.0.1",

    "file-saver": "^2.0.1",

    "fuse.js": "3.4.4",

    "hard-source-webpack-plugin": "^0.13.1",

    "vant": "^2.9.3",

    "vue": "^2.7.10",

    "vue-router": "^3.6.5",

    "vue-template-compiler": "^2.6.12",

    "vue-virtual-scroller": "^1.0.9",

    "vuedraggable": "2.20.0",

    "vuex": "^3.6.2"

  },

  "devDependencies": {

    "@babel/core": "7.0.0",

    "@babel/register": "7.0.0",

    "@carrotwu/check-vue-conflict-webpack-plugin": "^1.0.4",

    "@types/jest": "^24.0.19",

    "@typescript-eslint/eslint-plugin": "^4.18.0",

    "@typescript-eslint/parser": "^4.18.0",

    "@vue/cli-plugin-babel": "^4.5.4",

    "@vue/cli-plugin-eslint": "^4.5.4",

    "@vue/cli-plugin-typescript": "~4.5.13",

    "@vue/cli-plugin-unit-jest": "^4.5.4",

    "@vue/cli-service": "^4.5.4",

    "@vue/eslint-config-typescript": "^7.0.0",

    "@vue/test-utils": "1.0.0-beta.29",

    "autoprefixer": "^9.5.1",

    "axios": "^0.27.2",

    "babel-core": "7.0.0-bridge.0",

    "babel-eslint": "^10.1.0",

    "babel-jest": "23.6.0",

    "chokidar": "2.1.5",

    "compression-webpack-plugin": "^6.1.1",

    "connect": "3.6.6",

    "cross-env": "^7.0.3",

    "cz-conventional-changelog": "^3.3.0",

    "deme": "^1.0.5",

    "element-ui": "^2.15.7",

    "eslint": "^7.28.0",

    "eslint-config-prettier": "^8.3.0",

    "eslint-plugin-prettier": "^4.0.0",

    "eslint-plugin-vue": "^6.2.2",

    "html-webpack-plugin": "3.2.0",

    "husky": "^8.0.1",

    "lint-staged": "8.1.5",

    "mockjs": "1.0.1-beta3",

    "node-sass": "^4.14.1",

    "plop": "2.3.0",

    "runjs": "^4.3.2",

    "sass-loader": "^7.1.0",

    "script-ext-html-webpack-plugin": "2.1.3",

    "script-loader": "0.7.2",

    "serve-static": "^1.13.2",

    "speed-measure-webpack-plugin": "^1.3.3",

    "svg-sprite-loader": "4.1.3",

    "svgo": "1.2.0",

    "typescript": "~4.1.5",

    "vue-puzzle-vcode": "^1.1.3"

  }
}

**Comment by LinusBorg** [comment]
PLeasse provide a runnable reproduction. the codesandbox you linked to does not demonstrate the problem described.

Also makes sure to have followed the upgrade guide here:

https://blog.vuejs.org/posts/vue-2-7-naruto.html#upgrade-guide
