### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_normalized')

### ISSUE THREAD

**Issue by arslankhan1** [vuejs/vue#12811]
### Version
2.7.10

### Reproduction link
[](TypeError: Cannot read properties of undefined (reading '_normalized'))

### Steps to reproduce
TypeError: Cannot read properties of undefined (reading '_normalized')

### What is expected?
TypeError: Cannot read properties of undefined (reading '_normalized')

### What is actually happening?
TypeError: Cannot read properties of undefined (reading '_normalized')

**Comment by sodatea** [comment]
Please provide a valid reproduction when opening an issue.
