### ISSUE TITLE
@vue/cli 5.0.8创建的项目，在node_modules下的项目vue-test，无法触发热重载

### ISSUE THREAD

**Issue by yangzeyanlove** [vuejs/vue#12815]
### Version
2.7.10

### Reproduction link
[http://www.test.com/](http://www.test.com)

### Steps to reproduce
1.安装@vue/cli 5.0.8
2.在node_modules目录下，create 项目vue-test
3.启动服务，修改App.vue里面的代码，无法触发热重载

### What is expected?
希望在node_modules下的项目也可以触发热重载

### What is actually happening?
node_modules下的项目没有触发热重载

**Comment by sodatea** [comment]
参见 https://github.com/webpack/webpack/issues/11952#issuecomment-723910390
