### ISSUE TITLE
Changing compilerOptions directives in vue.config.js not working in 2.7 when building

### ISSUE THREAD

**Issue by tunnelpuzzle** [vuejs/vue#12828]
### Version
2.7.12

### Reproduction link
[github.com](https://github.com/tunnelpuzzle/vue-compiler-directive)

### Steps to reproduce
1. Clone the minimal reproduction repo and do `npm run build`. The code in vue.config.js: https://github.com/tunnelpuzzle/vue-compiler-directive/blob/master/vue.config.js#L11-L12 for the v-show directive won't be run.

2. Switch to Vue 2.6 `npm i vue@2.6.14 vue-template-compiler@2.6.14` and then do `npm run build`. The code to for the v-show directive is run.

### What is expected?
Changing the compilerOptions directives should work in Vue 2.7 when building.

### What is actually happening?
Changing the compilerOptions directives when building works in Vue 2.6 but not Vue 2.7

---
I looked in the release notes but couldn't find anything about this behavior changing in 2.7.

**Comment by yyx990803** [comment]
/cc @sodatea this seems to be related to `thread-loader` not able to pass options that contain functions to worker thread (only in build).

Not sure why this behavior is different between 2.6 and 2.7. Is there some logic in `vue-cli` that enables/disables thread-loader on `vue-loader`?

For now you can work around this by setting `parallel: false` in `vue.config.js`.

**Comment by sodatea** [comment]
> Not sure why this behavior is different between 2.6 and 2.7. Is there some logic in `vue-cli` that enables/disables thread-loader on `vue-loader`?

It's in `vue-loader`.
Vue 2.7+ also applies js loaders to compiled `<template>` code, and among them is `thread-loader`.

**Comment by sodatea** [comment]
This issue could be mostly mitigated if we detect and skip cloning `thread-loader` rules in `VueLoaderPlugin`

**Comment by sodatea** [comment]
Fixed in `vue-loader@15.10.1`
