### ISSUE TITLE
useCssModule is broken on Vue 2.7

### ISSUE THREAD

**Issue by Ansett** [vuejs/vue#12824]
### Version
2.7.11

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-2-7-usecssmodule-4tzs2z?file=/src/App.vue)

### Steps to reproduce
```
const style = useCssModule()
console.log(style.someClass) // undefined
// ...
<style module lang="css">
.someClass {
  background: pink;
}
</style>
```

### What is expected?
style object should contain defined class names

### What is actually happening?
style object is empty.

In console: *[Vue warn]: Current instance does not have CSS module named "$style"*

---
I checked https://github.com/vuejs/core/blob/v2-compat/packages/runtime-dom/src/helpers/useCssModule.ts which uses  `getCurrentInstance`, but on vue 2.7  `getCurrentInstance` returns `{ proxy: Vue }`.
Maybe that's something else :p

**Comment by skirtles-code** [comment]
I believe this is the same issue as #12822.

**Comment by sodatea** [comment]
Let's close this and track it in https://github.com/vuejs/vue/issues/12822 instead.
