### ISSUE TITLE
'WeakMap' is undefined in Vue 2.7.11 and above (IE10 and under)

### ISSUE THREAD

**Issue by gingerbenw** [vuejs/vue#12837]
### Version
2.7.11

### Reproduction link
[github.com](https://github.com/gingerbenw/vue2-minimal)

### Steps to reproduce
Open a Vue2 app using internet explorer 10 or below

### What is expected?
App loads and 'Hello Vue!' is displayed

### What is actually happening?
App does not load and 'WeakMap' is undefined is printed to the console

---
WeakMap is not supported in Internet Explorer 10 or less and was introduced to Vue in version [2.7.11](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#2711-2022-10-11)

**Comment by posva** [comment]
as a workaround, use a weakmap polyfill: https://github.com/polygonplanet/weakmap-polyfill

**Comment by gingerbenw** [comment]
Thanks @posva - we provide a framework to customers with a fairly wide browser base, while we're happy to include this polyfill for our own testing purposes, this does seem like a change in browser support that some of our customers may also be feeling. Does the Vue team intend to continue supporting these legacy browsers for Vue2, or is there an intended change in browser support that we should be prepared for?
