### ISSUE TITLE
The link for Korean docs seems to be broken.

### ISSUE THREAD

**Issue by Machineric** [vuejs/vue#12864]
### Version
2.7.13

### Reproduction link
[https://kr.vuejs.org/](https://kr.vuejs.org/)

<img width="697" alt="image" src="https://user-images.githubusercontent.com/26497426/199683193-77a535f5-54b9-44c3-b719-b5f836bc222d.png">

### Steps to reproduce
https://kr.vuejs.org/

### What is expected?
Other translated docs open except for the Korean one.

### What is actually happening?
The translated docs for Korean won't open.

**Comment by yyx990803** [comment]
Tracking in https://github.com/vuejs-kr/kr.vuejs.org/issues/227

**Comment by Bogyie** [comment]
Hello, @yyx990803, @Machineric. First of all, thank you for your interest in this matter. I really need a Vue 2 document translated into Korean.

I am a student taking a software education program (aka SSAFY) organized by Samsung in Korea. We are using Vue 2 in this training program. Therefore, we needed a Vue 2 document translated into Korean, and we are hosting it ourselves and using it.

In addition, most students are not familiar with open source contributions, so through this opportunity, they are experiencing open source contributions by additionally translating parts that have not yet been translated into Korean, although they are not the latest version.

I don't have enough authority to solve this problem, but I hope it will be solved as soon as possible. Also, if the translated part can be added to the official Vue 2 Korean document, it will be a great experience for students who have just studied programming and are trying to contribute to open source.

**Comment by Machineric** [comment]
> 

Great!

**Comment by Machineric** [comment]
> Hello, @yyx990803, @Machineric. First of all, thank you for your interest in this matter. I really need a Vue 2 document translated into Korean.
> 
> I am a student taking a software education program (aka SSAFY) organized by Samsung in Korea. We are using Vue 2 in this training program. Therefore, we needed a Vue 2 document translated into Korean, and we are hosting it ourselves and using it.
> 
> In addition, most students are not familiar with open source contributions, so through this opportunity, they are experiencing open source contributions by additionally translating parts that have not yet been translated into Korean, although they are not the latest version.
> 
> I don't have enough authority to solve this problem, but I hope it will be solved as soon as possible. Also, if the translated part can be added to the official Vue 2 Korean document, it will be a great experience for students who have just studied programming and are trying to contribute to open source.

Great!
