### ISSUE TITLE
`boolean` prop shouldn't be required when defined with `defineProps`

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/vue#12880]
### Version
2.7.14

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-ed531n?file=src%2FApp.vue&terminal=dev)

### Steps to reproduce
Use component having a `boolean` prop without passing this prop

```ts
// HelloWorld.vue
defineProps<{ msg: boolean }>();
```

```html
// App.vue
<template>
  <HelloWorld />
</template>
```

### What is expected?
No warning in the browser console

### What is actually happening?
`Missing required prop` warning

![image](https://user-images.githubusercontent.com/15625235/202761677-5abd5c8c-27ef-49b5-ae9f-2fdd174bd619.png)

**Comment by sxzz** [comment]
Try
`defineProps<{ msg?: boolean }>();`

**Comment by jacekkarczmarczyk** [comment]
Then this design is incosistent with design of other props and with object syntax

**Comment by edison1105** [comment]
@jacekkarczmarczyk 
this is designed since vue2. 
If the type of an attribute is boolean, the default value is set to `undefined`. `undefined` is also a falsely value when we use it. right?

**Comment by jacekkarczmarczyk** [comment]
Are you suggesting that this is a bug in Chrome that displays `undefined` as `false`?
![image](https://user-images.githubusercontent.com/15625235/202845427-f2752982-7c0c-4fc6-861c-cfc2adceb870.png)

**Comment by jacekkarczmarczyk** [comment]
TBH while I agree that the required prop might indeed throw a warning when not provided, the bigger problem is that non-required prop behaves differently with typescript and object syntax:
`prop: Boolean` (no `required: true`) - prop type is `boolean`
`prop?: boolean` - prop type is `boolean | undefined` (but still `false` is being passed when prop is not provided)
So I understand why this issue was closed, but I've created an issue in Vue 3 repo about this inconsistency and imho bad DX
