### ISSUE TITLE
watch a prop typeof array, unexpected execution

### ISSUE THREAD

**Issue by jinan5694** [vuejs/vue#12881]
### Version
2.7.14

### Reproduction link
[github.com](https://github.com/jinan5694/vue-issue)

### Steps to reproduce
1. clone repo
2. input something
3. TheTest component watch will execution

### What is expected?
watch will not exec.

### What is actually happening?
watch a array prop, pass a static value(not reactive or not in data)

the-test component code
<img width="577" alt="image" src="https://user-images.githubusercontent.com/3690120/202928194-bb67b535-71db-49f0-9489-f9113f8bace6.png">

app reproduce code
<img width="790" alt="image" src="https://user-images.githubusercontent.com/3690120/202928354-29b6df2e-ccdc-4a94-bcfc-24d08fca8e26.png">

i tried change the filters data in setup(or data in Option api) is ok.

i update my repo.just add some comment.and remove one line code unused.

**Comment by pikaqiu748** [comment]
It's so weird!!!

**Comment by kTelyakov** [comment]
@jinan5694 i try to reproduce your issue, but i cant )) 
![Vue-issue-gif](https://user-images.githubusercontent.com/31989028/202921355-8258a73c-8081-4e81-b690-566ef71304ec.gif)

**Comment by jinan5694** [comment]
> @jinan5694 i try to reproduce your issue, but i cant )) ![Vue-issue-gif](https://user-images.githubusercontent.com/31989028/202921355-8258a73c-8081-4e81-b690-566ef71304ec.gif) 

sorry for my english first...

i think you has reproduce in gif above.
the input bind value is not relative any other value . 

the-test component code
<img width="577" alt="image" src="https://user-images.githubusercontent.com/3690120/202928194-bb67b535-71db-49f0-9489-f9113f8bace6.png">

app reproduce code
<img width="790" alt="image" src="https://user-images.githubusercontent.com/3690120/202928354-29b6df2e-ccdc-4a94-bcfc-24d08fca8e26.png">

i tried change the filters data in setup(or data in Option api) is ok.

i update my repo.just add some comment.and remove one line code unused.

**Comment by posva** [comment]
This is because of the line

```vue
<TheTest :filters="[{ foo: 'bar'}]"></TheTest>
```

The array being inlined is recreated at each render which happens when you type. Move that array to a const:

```vue
<script setup>
const filters = [...]
</script>

<template>
<TheTest :filters="filters"></TheTest>
</template>
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!

**Comment by pikaqiu748** [comment]
OK， i see,thank you so much！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eduardo San Martin ***@***.***&gt;; 
发送时间: 2022年11月21日(星期一) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vuejs/vue] watch a prop typeof array, unexpected execution (Issue #12881)





 
This is because of the line
 <TheTest :filters="[{ foo: 'bar'}]"&gt;</TheTest&gt;
 
The array being inlined is recreated at each render which happens when you type. Move that array to a const:
 <script setup&gt; const filters = [...] </script&gt; <template&gt; <TheTest :filters="filters"&gt;</TheTest&gt; </template&gt;
 
 
Remember to use the forum or the Discord chat to ask questions!

**Comment by pikaqiu748** [comment]
one more question is why it cause recreate when typing every time.due to diff algorithm,it should update input box only.

**Comment by jinan5694** [comment]
> This is because of the line
> 
> ```
> <TheTest :filters="[{ foo: 'bar'}]"></TheTest>
> ```
> 
> The array being inlined is recreated at each render which happens when you type. Move that array to a const:
> 
> ```
> <script setup>
> const filters = [...]
> </script>
> 
> <template>
> <TheTest :filters="filters"></TheTest>
> </template>
> ```
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!

thanks for you response.

i have a question. the same code in vue3 is ok. why has different hehavior？
