### ISSUE TITLE
Array props watcher not being triggered in 2.7

### ISSUE THREAD

**Issue by Waynezhi** [vuejs/vue#12891]
### Version
2.7.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/magical-blackwell-4sszeg?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
click on update button, the first array does not change

### What is expected?
array props watcher should be triggered

### What is actually happening?
array props changes do not trigger watcher

**Comment by LinusBorg** [comment]
you need to use `deep: true` to watch the (stable) array's contents
