### ISSUE TITLE
big data render performance 

### ISSUE THREAD

**Issue by humyfred** [vuejs/vue#12903]
### Version
2.X

### What problem does this feature solve?
in the big data situtation, we use virtual scroll component, but still render slow。when we scroll table big data list，it would appear a white screen and then render trs

### What does the proposed API look like?
render

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

See https://vuejs.org/guide/best-practices/performance.html#reduce-reactivity-overhead-for-large-immutable-structures for additional best practices

**Comment by humyfred** [comment]
thanks， Is there a plan to support version 2.0 as the best practice
