### ISSUE TITLE
v-else-if scopedSlots content not update 

### ISSUE THREAD

**Issue by wuzhidexiaoming** [vuejs/vue#12922]
### Version
2.7.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/elastic-wood-3duzdw?file=/src/App.vue)

### Steps to reproduce
click a,b,c b to c,content not update

### What is expected?
normal update scopedSlot content

### What is actually happening?
Click a b c in turn, and found that the content of b to c has not been updated

---
if every div use v-if,then there will be no description problem. If for each 'Sup' component add `:value="value"`, scopedSlot content will update normally

**Comment by Justineo** [comment]
You need to add unique `key` to if branches if they are using the same kind of element.

**Comment by wuzhidexiaoming** [comment]
> 

thanks, Adding a unique key can also solve the problem. I found another issue #12244,similar to this one, it fixed #12223 ,but still can't update  with the above demo.So I think it's a vue problem

The current result is if i use v-else-if or v-else and children have the same component, i need to add a unique key to each component

**Comment by wuzhidexiaoming** [comment]
> You need to add unique `key`s to if branches if they are using the same kind of element.



> You need to add unique `key`s to if branches if they are using the same kind of element.

> 

thanks, Adding a unique key can also solve the problem. I found another issue #12244,similar to this one, it fixed #12223 ,but still can't update  with the above demo.So I think it's a vue problem

The current result is if i use v-else-if or v-else and children have the same component, i need to add a unique key to each component

**Comment by DaZuiZui** [comment]
添加一个唯一的建

**Comment by DaZuiZui** [comment]
Use v-if as a workaround:
