### ISSUE TITLE
In SSR mode, v-html always rerender

### ISSUE THREAD

**Issue by AlexBergal** [vuejs/vue#12929]
### Version
2.7.14

### Reproduction link
[gist.github.com](https://gist.github.com/AlexBergal/1f63624092b77212b54e7090bd6bb641)

### Steps to reproduce
app.vue
```html
<template lang="html">
  <div>
    <div v-html="content"></div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      content: '<p>hello</p>'
    }
  }
}
</script>
```

### What is expected?
do not re-render component

### What is actually happening?
component re-render with same content

---
Used with Quasar
-    mode.......... ssr
-    Pkg quasar........ v1.22.5
-   Pkg @quasar/app... v2.4.3

**Comment by amirafa** [comment]
use v-once in it

<template lang="html">
  <div>
    <div v-once v-html="content"></div>
  </div>
</template>

**Comment by amirafa** [comment]
use v-once in it

`<template lang="html">
  <div>
    <div v-once v-html="content"></div>
  </div>
</template>`

**Comment by amirafa** [comment]
use v-once in it
`
<template lang="html">
  <div>
    <div v-once v-html="content"></div>
  </div>
</template>
`

**Comment by amirafa** [comment]
use v-once in it

```
<template lang="html">
  <div>
    <div v-once v-html="content"></div>
  </div>
</template>
```
