### ISSUE TITLE
[2.7.x] Defined props using object syntax are not correctly inferred

### ISSUE THREAD

**Issue by ludwig801** [vuejs/vue#12935]
### Version
2.7.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/broken-type-inference-omdx65?file=/src/App.vue)

### What is expected?
Props object to be interpreted correctly and the props to be defined in the methods / computed / lifecycle hooks.

### What is actually happening?
Defined props using object syntax are not recognized as belonging to the instance.

---
My development environment is:

 - VSCode (v1.7.43)
 - Volar (v1.0.24) - takeover mode
 - Vue 2.7.14

**Comment by yyx990803** [comment]
No longer reproducible with latest version of Volar (1.8.25)
