### ISSUE TITLE
setCurrentInstance is not exported, causes instance fixes to be unavailable

### ISSUE THREAD

**Issue by daniluk4000** [vuejs/vue#12939]
### What problem does this feature solve?
The Why:
1. We need to use Composition API in our project as preparation for Vue 3 + Nuxt 3 migration
2. Nuxt Bridge is not stable enough, so we use Nuxt Composition API
3. Internally, Nuxt Composition API uses Vue's native instance realization
4. Nuxt Composition API doesn't have helper functions for context fixing, unlike Nuxt 3/Nuxt Bridge (can't use yet)
5. We lose instance after calling one await without able to restore
6. All Nuxt helpers become unavailable with "This must be called within a setup function" error

Example usage:

```typescript
import { defineComponent, onMounted, ref, getCurrentInstance, setCurrentInstance } from 'vue';
//...
        const instance = getCurrentInstance();
        onMounted(async () => {
            await someAsync();
            setCurrentInstance(instance?.proxy); //not exported right now
            store.action(); //Uses Nuxt Helpers, which are unavailable without instance
        });
```
### What does the proposed API look like?
setCurrentInstance is exported just like getCurrentInstance does

**Comment by posva** [comment]
There are no plans to add `setCurrentInstance()` to Vue 3 so this would still break in Vue 3. I don't know where `store` comes from but in composition API, you would ideally have a `useStore()` function called before `onMounted()`. It would internally use `inject()` to get the actual store.

In short, the thing you want to write **shouldn't be necessary in the first place**, so it's worth having a reproduction (without Nuxt) of what isn't working right now. Otherwise, this should be brought to Nuxt attention instead.

**Comment by daniluk4000** [comment]
@pi0 @danielroe I can make a bug/issue in Nuxt Composition API but will you actually fix it as it's legacy? We can't use Nuxt Bridge now due to many errors.

@posva 
> There are no plans to add `setCurrentInstance()` to Vue 3 so this would still break in Vue 3
How can export break something? Is there a way to restore instance by user action in Vue 3/Vue 2.7? That's why I actually needed to export this in a first place. Maybe useAsyncContext or something like that? I didn't find export anywhere as well.

> you would ideally have a useStore() function called before onMounted()
It's not about the store, it's about calling some instance-related functions inside the store, ex. router, e.t.c.
It could be any other composable/function that is called after the await which requires instance.

> Otherwise, this should be brought to Nuxt attention instead
I don't think they can actually exclude instance usage from their methods because Nuxt CAPI just works like that. The only way here is to restore context somehow or to pass composable results down to stores e.t.c.

**Comment by pi0** [comment]
Hi @daniluk4000 thanks for making the issue and explaining the problem.

I think also a direct `setCurrentInstance` could be dangerous at least.

A common issue we have with both Vue 2/3 and CAPI, is that when for any reason only a composable relies on a different Vue build the instances get out of sync (mostly hosting issues that causes multiple instances of Vue in CJS/ESM cache but can also be pnpm).

I will try to come up with an (vue3) issue and proposal with a new internal API, we can support opt-in sync of vue instances solving many of similar issues for Nuxt.

**Comment by daniluk4000** [comment]
> I will try to come up with an (vue3) issue and proposal with a new internal API, we can support opt-in sync of vue instances solving many of similar issues for Nuxt.

Thank you! I will close this issue for now then. If there is a workaround, I would like to hear it though.

> I think also a direct setCurrentInstance could be dangerous at least. With Nuxt, we take extra measures to expose callWithNuxt
That's what I miss so much in Legacy CAPI :(
Was my workaround in (another) Nuxt 3 project for such issues.
