### ISSUE TITLE
event triggers repeatedly

### ISSUE THREAD

**Issue by Alfred-Skyblue** [vuejs/vue#12954]
### Version
2.7.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/misty-platform-1nztpk?file=/src/App.vue)

### Steps to reproduce
```js
const vm = new Vue()
const fn = () => {
  console.log('hello world')
}

vm.$on('foo', fn)
vm.$on('foo', fn)
vm.$emit('foo')
// => "hello world" x 2
```

### What is expected?
// => "hello world" x 1

### What is actually happening?
// => "hello world" x 2

**Comment by posva** [comment]
I recall this was rejected in the past but I can't find the issue anymore... Since in practice you never write that same statement twice, I don't think this will fix any problem. Do you have any real world scenario where this is necessary?

**Comment by Alfred-Skyblue** [comment]
I think it should be deduplicated by Vue internally,  because it is also possible to use duplicate events inadvertently

**Comment by posva** [comment]
> because it is also possible to use duplicate events inadvertently

Which will then break if we fix this 😅

So, do you have any real world scenario use case? In practice people don't seem to do this and it seems to avoid a hard to spot duplication, so it looks better **not to change the current behavior**.

**Comment by Justineo** [comment]
> ### What is expected?
> // => "hello world" x 2
> 
> ### What is actually happening?
> // => "hello world" x 1

I'm confused. Do you actually expect `"hello world" x 1` instead of `"hello world" x 2`?

**Comment by posva** [comment]
they expect it to run it twice as it would make sense because there are 2 `$on` but at the same time writing twice `$on()` with the same function is unlikely to be intended

**Comment by Alfred-Skyblue** [comment]
> > ### What is expected?
> > // => "hello world" x 2
> > ### What is actually happening?
> > // => "hello world" x 1
> 
> I'm confused. Do you actually expect `"hello world" x 1` instead of `"hello world" x 2`?

Sorry, my description was wrong, I was expecting it to execute only once

**Comment by Justineo** [comment]
You listened to an event twice then your callback run twice so I wouldn't say this is a bug. Changing this would be a breaking change which we will not accept at the moment.

Ps. Node.js's `EventEmitter` doesn't dedupe but DOM's `EventTarget` does dedupe so I'm not saying there is one single correct behavior. We just won't change it in Vue.

**Comment by posva** [comment]
Huh, maybe I was wrong and it got accepted then? I can't recall anymore but I don't think it makes sense to change the behavior of `this.$on()` at this point as it doesn't exist in v3 anyway so this would just hurt existing projects that could be relying on the behavior
