### ISSUE TITLE
[2.x, 3.x]: Parameter value leaking from parent to grandchild if all three layers use the same HTML element

### ISSUE THREAD

**Issue by johnlife** [vuejs/vue#12952]
In the following setup:

**Parent.vue**
```
<template>
  <child leak="should not be visible" />
</template>
  
<script>
import Child from "./Child.vue";
export default {
  components: { Child },
};
</script>
```

**Child.vue**
```
<template>
  <grandchild leak="this should be the leak value" />
</template>

<script>
import Grandchild from "./Grandchild.vue";
export default {
  components: { Grandchild },
};
</script>
```

**Grandchild.vue**
```
<template>
  <div :leak="leak">this div should have leak prop set to {{ leak }}</div>
</template>

<script>
export default {
  props: {
    leak: {
      type: String,
      required: true,
    },
  },
};
</script>
```

One would expect "leak" prop to have value set by Child component. Since Child doesn't have "leak" property defined and doesn't use $attrs. So value specified by a parent should be ignored or at least overwritten by the component that actually has this prop and got its value specified (Grandchild).
In fact, rendered HTML tag has leak property set to "should not be visible".

Live demo: https://codesandbox.io/s/eager-hodgkin-3dxr3f?file=/src/components/Parent.vue

**Comment by posva** [comment]
This is expected behavior. Use `inheritAttrs` as shown in docs if you don't want to inherit attrs
