### ISSUE TITLE
`watch()` doesn't trigger when adding new property with `Vue.set( )`

### ISSUE THREAD

**Issue by depressedX** [vuejs/vue#12967]
### Version
2.7.14

### Reproduction link
[codepen.io/AxisZ/pen/RwYrmxq](https://codepen.io/AxisZ/pen/RwYrmxq)

### Steps to reproduce
Just open the codepen link, and open browser's devtool console

### What is expected?
The `Vue.set(obj, 'added', 1);` statement should trigger the watcher callback, which will print `[watch getter]obj changed`.

### What is actually happening?
nothing happened, the watcher does not be triggered

---
This behavior is not the same as neither vue2.6 or vue3.
Open this codepen writting with vue2.6+@vue/composition-api, It will print `[watch getter]obj changed`, which is expected.

vue2.6+@vue/composition-api demo:  https://codepen.io/AxisZ/pen/VwGeOEE

The core codes is here: 

```javascript
const { watch, reactive, set } = Vue;

const obj = reactive({ exist: 1 });

watch(
    () => obj,
    () => {
        console.log('[watch getter]obj changed');
    },
    { deep: true },
);

setTimeout(() => {
    console.log('should print watcher message↓↓↓↓');
  // add a new property, should trigger that watch below as expected
    set(obj, 'added', 1);
});

```

**Comment by depressedX** [comment]
found `@vue/compositon-api` tricky code here. Maybe there should also be something like this?

https://github.com/vuejs/composition-api/blob/1a05a1d4f2cdfdc1b66b094045b335d5605b2946/src/apis/watch.ts#L381-L391

**Comment by xiaowei-one** [comment]
```javascript
```

**Comment by xiaowei-one** [comment]
```javascript
// ChildOb is undefined in 2.7, but return an observer(maybe use watch new attribute) in 2.6
let childOb = !shallow && observe(val, false, mock) 
Object.defineProperty(obj, key, {
  enumerable: true,
  configurable: true,
  get: function reactiveGetter() {
    // ...
    if (childOb) {
      // It will run in 2.6, but not in 2.7
      childOb.dep.depend()
    }
    // ...
  },
})
```

**Comment by shrpne** [comment]
maybe related to https://github.com/vuejs/composition-api/issues/933

**Comment by shunting-yard-recognized** [comment]
> maybe related to [vuejs/composition-api#933](https://github.com/vuejs/composition-api/issues/933)





https://bonfireangel.github.io/4MuRP8d2pWi54T1QgGzmVpCoNtkRpK_4BAaHmMUsqP3x8k3qGvOhvPqbN1oRmEuJ/
