### ISSUE TITLE
 Node.appendChild: Cannot add children to a Comment 

### ISSUE THREAD

**Issue by i1v** [vuejs/vue#12961]
### Version
2.6.14

### Reproduction link
[https://www.justwatch.com/](https://www.justwatch.com)

### Steps to reproduce
since today, visiting this site:

https://www.justwatch.com

I get this result:

Uncaught (in promise) DOMException: Node.appendChild: Cannot add children to a
Comment

Vue.js v2.6.14

### What is expected?
no error

### What is actually happening?
error

**Comment by posva** [comment]
You are still missing the most essential part: the reproduction. Please follow the reproduction template

**Comment by i1v** [comment]
to reproduce, just visit the site  as I detailed. what is not clear about that?

**Comment by Justineo** [comment]
https://new-issue.vuejs.org/?repo=vuejs/core#why-repro
