### ISSUE TITLE
 升级vue2.7.14之后无法使用compositionAPI 

### ISSUE THREAD

**Issue by luhuiyang** [vuejs/vue#12971]
### Version
2.7.14

### Reproduction link
[v2.vuejs.org](https://v2.vuejs.org/v2/guide/migration-vue-2-7.html)

### Steps to reproduce
项目从vue2.6.x升级到^2.7.0，将本地的 @vue/cli-xxx 依赖升级至~4.5.18，同时从依赖中移除 了vue-template-compiler，移除了整个 node_modules 和package-lock.json文件，创建新的sfc文件，
```
import { ref } from 'vue‘,
```
 出现warning: export 'ref was not found in 'vue'。在SFC中使用
```
setup() {
  console.log('test setup')
}
```
时，setup()未执行

### What is expected?
我想要在vue 2.7中使用compositionAPI

### What is actually happening?
无法在vue2.7中使用compositionAPI

**Comment by Justineo** [comment]
请先确认自己项目中安装和引入的 Vue 的版本，再按 [issue 模板要求](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro)提供重现。谢谢。
