### ISSUE TITLE
type VNodeChildren should support number type

### ISSUE THREAD

**Issue by bartlian** [vuejs/vue#12973]
### Version
2.7.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/p/github/bartlian/vue2-issue/master?workspaceId=96b5a6db-8478-41dc-9e54-9e83fa364a7a&file=%2Fsrc%2Fmain.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cleqjldkc0006g6fz7vbt23mo%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fmain.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cleqjlg3m0011356ifgzsa9u1%2522%253A%257B%2522key%2522%253A%2522cleqjlg3m0011356ifgzsa9u1%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cleqk63ur014p356iwqo151as%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cleqjlg3m0011356ifgzsa9u1%2522%252C%2522spacesOrder%2522%253A%255B%2522cleqjlg3m0011356ifgzsa9u1%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

### Steps to reproduce
result: Compilation error.

### What is expected?
type VNodeChildren should support number type

### What is actually happening?
vue-tsc compiles error

---
version:
vue 2.7.14
vite 3.0.2
typescript: 4.9.5

**Comment by bartlian** [comment]
[#12974](https://github.com/vuejs/vue/pull/12974)
Having pulled a request, Plz confirm

**Comment by xonx4l** [comment]
Hey I think this can be the solution . PR-fix: type VNodeChildren supports type number #13067
