### ISSUE TITLE
media print header in every page and long text print

### ISSUE THREAD

**Issue by TingNLP** [vuejs/vue#12993]
I have a long text in page and need to print. 
This url give some explain and solutions.
[https://medium.com/@Idan_Co/the-ultimate-print-html-template-with-header-footer-568f415f6d2a](url)

**sample code：**
[https://stackblitz.com/edit/web-platform-1wg2qq?file=index.html](url)

It's work in html but not work in vue2.0.
Can anyone give me a simple example for vue?

thank you.

**Comment by TingNLP** [comment]
Actually, it works.
But there is a limit to the size of the **thead** 和 **tfoot**.
This will cause part of the text be obscured between the pages.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
