### ISSUE TITLE
how can I use the expression compile in my directives?

### ISSUE THREAD

**Issue by JokerSora** [vuejs/vue#12994]
### What problem does this feature solve?
when I define a directive which make a event debounce,such as v-debounce:click="somefunction",this can work since I can compile the directive expression "somefunction" by using vnode.componentInstance.somefuncion.
but when the expression is complicated,such as  v-debounce:click="somefunction($event,{a:b},'asdf',2)" ,
how can i compile the expression just like using v-on:click did?

### What does the proposed API look like?
I think the v-on directive needs a way to debounce and throttle a function,since sometimes we need the event do only once in tiny time interval or do only once at the end of consecutive event fires

**Comment by JokerSora** [comment]
I knew that vue1 had such throttle and debounce and vue2 dropped them,but I need to realize them by myself,so I need the expression compile function

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
