### ISSUE TITLE
$set shallowRef value lost reactivity

### ISSUE THREAD

**Issue by troy351** [vuejs/vue#12998]
### Version
2.7.14

### Reproduction link
[codepen.io](https://codepen.io/troy351/pen/QWVepao)

```js
// for short, makes `shallowRef` lost
console.log(reactive({foo: shallowRef({ bar: "123" })}));
```

### Steps to reproduce
- open reproduction page
- see console log

### What is expected?
`shallowRef` remain

### What is actually happening?
`shallowRef` lost, `foo` here became a plain object

<img width="636" alt="image" src="https://user-images.githubusercontent.com/8372385/229456233-7e1b4b27-d3cb-410a-8c84-775436149c80.png">

FYI. works in vue3

<img width="333" alt="image" src="https://user-images.githubusercontent.com/8372385/229457406-7e40def7-caec-430e-a35d-a380133e7e78.png">

**Comment by yyx990803** [comment]
It's just the logging output being different because you are looking at the raw Proxy value in the Vue 3 log (Vue 2 doesn't use proxies). The shallow ref is unwrapped and tracked in both cases.
