### ISSUE TITLE
Export types of built-in components

### ISSUE THREAD

**Issue by kingyue737** [vuejs/vue#13002]
### What problem does this feature solve?
Vue 2.7 does not export types of built-in components like `Transition` and `TransitionGroup` (In Vue 3 they are exported via `@vue/runtime-dom`). As a consequence, users cannot get intellisense and type check with `@vue/language-tools`. Furthermore, VSCode will show warning if `vueCompilerOptions.jsxTemplates` is turned on in `tsconfig`.

![image](https://user-images.githubusercontent.com/40021217/232362548-beb9a1b0-1232-4d36-b199-eaa29f8520f7.png)

Ref: vuejs/language-tools#2540

### What does the proposed API look like?
Line 76
https://www.unpkg.com/browse/@vue/runtime-dom@3.2.47/dist/runtime-dom.d.ts

**Comment by MoisesF17** [comment]
THANKS

**Comment by rchl** [comment]
Not sure if Volar issue but a simple transition with `key` shows an error now:

![Screenshot 2024-02-01 at 13 30 29](https://github.com/vuejs/vue/assets/153197/7b23ec1b-228d-4947-9dda-772871ebe6a6)

(I think `key` is allowed on transition?)
