### ISSUE TITLE
Vue.Js should be a fully featured framework.

### ISSUE THREAD

**Issue by CordialGit** [vuejs/vue#13016]
Normally, JavaScript is powerful. It can do so much on the frontend. And it is a sufficient tool especially when paired with PHP or Node.Js.

Now, I'm offended that creators of JavaScript frameworks are now making Frontend Development too difficult.

My particular anger goes to Vue.JS.

If I've taken the pain to learn HTML, CSS and JavaScript. Then I'm going forward to learn Vue on top of JavaScript, why didn't Vue ensure that this should be enough?

Why do I still need to learn **Nuxt** for Server Side Rendering, **Pinia** for Storage, **Vuetify** for Components, and **Vitest** for testing?

With so much frontend power in JavaScript already, can't Vue just come with these additional features in-built?

And if they are not in-built, can't Vue integrate them into the Vue core in a next update to the Vue Framework?

You see, it's frustrating learning too much and learning some new tools because of some ordinary small additional features--- small features that can simply be built into Vue core.

All of these over-learning is making frontend Development too difficult.

And I'm hoping for Vue to become a fully featured batteries included framework like Python.

This fully featured batteries included framework concept for Vue means that, after the pain of learning JavaScript and we then add Vue on top of it,we should need nothing more.

I make websites with WordPress, and all the headaches that coding from scratch presents, are all taken away--while using WordPress.

With WordPress, a Database is already there. A Content creation Interface is already there. Admin Dashboard for managing **Themes**(Looks) and **Plugins**(Functionality) is already there.  Everything you need is all there, and it's simply drag and drop to build your website.

The WordPress process is so easy, and it keeps evolving to make life and website development so easy.

In essence, I am asking that Vue should make our life easier by being a fully featured Framework with a **Batteries-Included** approach--- where if we add Vue on Top of JavaScript, we should need nothing more and nothing extra. 

All the features that will make us need Nuxt, Vuetify, Pinia and Vitest, should all come as core in-built features of Vue.

Regards.

**Comment by posva** [comment]
This is a very opinionated topic and has been asked in the past. (One of) The short answer(s) is: Vue is a progressive framework and what you describe doesn't allow the progressive enhancement Vue allows. I think [Nuxt](https://nuxt.com/) seems to be a better match for you
