### ISSUE TITLE
Backticks in the source code ruin a build process

### ISSUE THREAD

**Issue by yanbess** [vuejs/vue#13011]
### Version
2.7.14

### Reproduction link
[github.com/yanbess/vue-test](https://github.com/yanbess/vue-test)

### Steps to reproduce
npm install
npm run prod

### What is expected?
Successful building

### What is actually happening?
 ERROR  Failed to compile with 4 errors                                                                                                                                                 

 error  in node_modules/vue/types/jsx.d.ts:39:7

TS1110: Type expected.
  > 39 |   [v: `--${string}`]: string | number | undefined
       |       ^^^^^
...

You need just replace ` with ' or " here:
https://github.com/vuejs/vue/blob/a9ca2d85193e435e668ba25ace481bfb176b0c6e/types/jsx.d.ts#L39

**Comment by yyx990803** [comment]
Your typescript version is way out of date. Template literal types were introduced in TS 4.1 in Nov 2021...
