### ISSUE TITLE
ios16.5白屏（white screen on ios16.5）

### ISSUE THREAD

**Issue by dxr11111** [vuejs/vue#13028]
### Version
2.7.14

### Reproduction link
[github.com/dxr11111/zsyw.git](https://github.com/dxr11111/zsyw.git)

### Steps to reproduce
在iPhone系统版本为ios16.5的手机上访问vue2项目，打开后白屏（When you access the vue2 project on a mobile phone running ios16.5, a blank screen is displayed after it is opened）

### What is expected?
可以正常访问页面（The page can be accessed normally）

### What is actually happening?
页面一片空白（The page is blank）

**Comment by Justineo** [comment]
请提交一个[最小化重现](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#why-repro)来确认这是 Vue 本身的问题。
