### ISSUE TITLE
npm run build fails on compiling to npm package for vue 2.7.14

### ISSUE THREAD

**Issue by ethanseow** [vuejs/vue#13040]
### Version
2.7.14

### Reproduction link
[github.com](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)

### Steps to reproduce
first time doing open source contributions and wanted to solve https://github.com/vuejs/vue/issues/12998
but was unable to compile vue into node package

Steps:

git clone https://github.com/vuejs/vue/tree/v2.7.14

yarn at root of project

npm run build at root of project

following these steps outlined here
https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md

### What is expected?
the entire Vue NPM package should exist and be built into [root]/dist

### What is actually happening?
npm run build

> vue@2.7.14 build
> node scripts/build.js

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '@vue/consolidate/package.json'
Require stack:

**Comment by yyx990803** [comment]
You are following the instructions from an outdated branch (`dev`). The current default branch is `main`.
