### ISSUE TITLE
计算属性被解析成组件

### ISSUE THREAD

**Issue by GuoSirius** [vuejs/vue#13046]
### Version
2.7.14

### Reproduction link
[http://huangshuwei.gitee.io/vue-easytable/#/en/doc/table/api?anchor=row-expand-option](http://huangshuwei.gitee.io/vue-easytable/#/en/doc/table/api?anchor=row-expand-option)

### Steps to reproduce
const demo = computed(() => ({ render: () => '123' }))

### What is expected?
正常解析为计算属性

### What is actually happening?
计算属性返回的对象里包含 render 方法，导致被视为 组件

```javascript
const props = defineProps({
  trigger: {
    type: String,
    default: 'icon'
  }
})

const realExpandOption = computed(() => {
  const { trigger } = props

  return { trigger, render: () => '123' }
})
```

![image](https://github.com/vuejs/vue/assets/48358523/a2194a75-84cc-4bb2-af02-64f29cb77fb8)

**Comment by posva** [comment]
open the issue on vue-easytable
