### ISSUE TITLE
Node V18 support?

### ISSUE THREAD

**Issue by default-kaas** [vuejs/vue#13042]
### Version
2.7.14

### Reproduction link
[github.com/vuejs/vue/issues](https://github.com/vuejs/vue/issues)

### Steps to reproduce
-

### What is expected?
Will Vue 2 get support for node v18?
Node v16 will be end of life on 09-11-2023, but that is 3 months before Vue 2 will be end of life.

Link to node release schedule:
https://nodejs.dev/en/about/releases/

### What is actually happening?
-

**Comment by posva** [comment]
AFAIK Vue already supports the latest node. If you find any bug, open an issue with a repro
