### ISSUE TITLE
The output of v-html directive is incorrect in case the <> of a tag are serialized

### ISSUE THREAD

**Issue by chicong065** [vuejs/vue#13056]
### Version
2.6.10

### Reproduction link
[play.vuejs.org/](https://play.vuejs.org/#eNp9kUFPAjEQhf9K7YGFBCGGGywkakjUgxo18dID6+6wFLtt086uJJv97067gh4Mt877XmfetC2/tnbS1MDnPPW5kxaZB6ztSmhZWeOQtczBlnVs60zFErImQgudG+2RVb5ky8CHyR0oZdi7caq4SEZCp9O+HTWiAqGyKkOgirF0d7Vq23i569IpVVGV2tbImsvKFKCWghMXvEeFbAjssAr6JpSrgcJFP2FQ4iJT4HCYZB95MgrkZ3hA6TTYN9SqP4Vopzh8zNHTLltZTvbeaHqGNkwUPDeVldT1yaKkXQWfs0gCy2jVr4eooathfNTzHeSf/+h7fwia4M8OPLgGBD8xzFwJ2OP16yMc6HyC9BS1IvcZ+ALeqDpk7G03tS4o9h9fTHsfP1Pq8s2vDwjaH5cKQYOzi37B6YNvz6z+G3c2mcV7Qne8+waqHsEY)

### Steps to reproduce
1/ Please add this string as content of v-html: `<div>&lt;script&gt;alert('abc')&lt;/script&gt;</div>`.

2/ Inspect the section above, you'll see the script tag is rendered as html element, not a string.

### What is expected?
This part `&lt;script&gt;alert('abc')&lt;/script&gt;` will be rendered as a string, not html tag.

### What is actually happening?
This part `&lt;script&gt;alert('abc')&lt;/script&gt;` is rendered as a html tag, not a string.

**Comment by posva** [comment]
This is because you are putting it directly in the HTML so the escaped characters get unscaped (not Vue BTW). In practive the value should be in a js variable, in which case you will see the behavior you want.
