### ISSUE TITLE
Property "" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by Matthew2306** [vuejs/vue#13065]
> **Warn: [Vue warn]: Property "shows" was accessed during render but is not defined on instance.** 

I have a similar situation, could anyone tell how can I fix the v-for loop? 

Design:
![Screenshot 2023-08-15 at 11 02 19 AM](https://github.com/vuejs/vue/assets/75374080/0fe52a1c-0f08-4993-92fe-6cff3eae2695)

Template:
```
<div class="show-column">
  <div class="circle-bg">
    <div class="date">{{ show.date }}</div>
    <div class="month">{{ show.month }}</div>
  </div>

  <div class="show show-box">
    <div class="show-name">{{ show.showName }}</div>
    <div class="show-desc">{{ show.showDesc }}</div>
  </div>
</div>
```

Script:
```
const activeIndex = ref(0);
const shows = ref([
  {
    date: "15",
    month: "JUN",
    showName: "Piano Duo Recital by Lucas & Arthur Jussen",
    showDesc: "Hong Kong Museum of Art",
  },
  {
    date: "15-18",
    month: "JUN",
    showName:
      "Chinese Opera Festival 2023: Opening Programme - Peking Opera Theatre of Beijing",
    showDesc: "Hong Kong Museum of Art",
  },
  {
    date: "15-30",
    month: "JUN JUL",
    showName: "Chinese Culture and Dance Festival 'Hong Kong Dance Expo 2023'",
    showDesc: "Hong Kong Museum of Art",
  },
  {
    date: "30",
    month: "JUN",
    showName: "4",
    showDesc: "Test",
  },
]);
```

_Originally posted by @Matthew2306 in https://github.com/vuejs/vue/issues/3780#issuecomment-1678364902_

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.

**Comment by Matthew2306** [comment]
> Please follow the issue template, otherwise we'll close the issue directly. Thank you.

Issue template? What do you mean

**Comment by Justineo** [comment]
See https://new-issue.vuejs.org/

**Comment by LeonardoRick** [comment]
@Matthew2306 did you opened another one?

**Comment by kdekooter** [comment]
Yo @Justineo please do not hide behind some bureaucratic rule. This is a real issue that users are bumping into on a daily basis. And there is not a word in the documentation explaining this. 

<img width="584" alt="image" src="https://github.com/user-attachments/assets/ab68d8e4-b57e-4cc1-b8dd-6c5c9cae7241" />

So please consider reopening this issue and explain how we can fix this.
