### ISSUE TITLE
Textarea Character Limit Bug: Inability to Add Characters After Deletion (Safari Browser)

### ISSUE THREAD

**Issue by geaaronkow** [vuejs/vue#13074]
### Version
2.7.14

### Reproduction link
[codepen.io](https://codepen.io/Aaron-Kow/pen/bGOEZxY)

### Steps to reproduce
Please open the provided CodePen in the Safari browser and follow these steps:

1. Enter or paste a lengthy text with line breaks in between until it reaches the maximum supported length.
2. Delete one or two characters from within the long text.
3. Attempt to input any character, and you will observe that you cannot add more characters within the long text.

### What is expected?
I anticipate that, following the deletion of some characters within the long text within the textarea, I will be able to input additional characters to reach the maximum character limit.

### What is actually happening?
The provided CodePen, when opened in the Safari browser, presents an issue where users are unable to input additional characters within a long text after deleting some characters. This occurs when following the steps of entering or pasting a lengthy text, deleting characters, and then attempting to add more characters within the text.

<img width="410" alt="issue" src="https://github.com/vuejs/vue/assets/137856749/86c9f5e1-0968-40a5-b609-50c9a9d39585">

**Comment by posva** [comment]
The same problem seems to appear without any JS. You should report this to webkit, it cannot be fixed here.

**Comment by geaaronkow** [comment]
Thanks. Yes, I managed to replicate it.
