### ISSUE TITLE
<script setup>supports defineExpose(), which cannot be exported correctly

### ISSUE THREAD

**Issue by bbhxwl** [vuejs/vue#13077]
### Version
2.7.14

### Reproduction link
[http://b/](http://b)

### Steps to reproduce
The following code may not find a method, but it can be used normally in Vue3.

v1.vue 
let searchList=()=>{
  //tb.value.btnSearchAdlData(data);
}
defineExpose({
  searchList
})

v2.vue
const tbGateMagnet = ref(null);
tbGateMagnet.value.searchList();

### What is expected?
The following code may not find a method, but it can be used normally in Vue3.

### What is actually happening?
The following code may not find a method, but it can be used normally in Vue3.

---
The following code may not find a method, but it can be used normally in Vue3.

**Comment by yeli19950109** [comment]
在 v2.vue 的 onMounted 之后再调用 tbGateMagnet.value.searchList();

**Comment by bbhxwl** [comment]
> 在 v2.vue 的 onMounted 之后再调用 tbGateMagnet.value.searchList();

多谢，我脑子坏了。
