### ISSUE TITLE
assets not showing 

### ISSUE THREAD

**Issue by kirbyfern** [vuejs/vue#13083]
### What problem does this feature solve?
hosted on ghpages on a custom domain, 

quite new, tried figuring out why assets are not showing up
try fixing vue.config.js

const { defineConfig } = require('@vue/cli-service');
const details = require('./src/assets/details.js');

module.exports = {
    publicPath: process.env.NODE_ENV === 'production'
        ? '/Verify_Kirby/'
        : '/',
    transpileDependencies: ['vuetify'],
};

repo link: https://github.com/kirbyfern/verify-k

### What does the proposed API look like?
n.a

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
