### ISSUE TITLE
Can 2.6.15 be published for this issue with the below fix

### ISSUE THREAD

**Issue by shyamzpassion** [vuejs/vue#13094]
@LinusBorg 

Request to publish 2.6.15 for this issue (https://github.com/vuejs/vue/issues/12445) with this fix: https://github.com/vuejs/vue/pull/10085

_Originally posted by @shyamzpassion in https://github.com/vuejs/vue/issues/12445#issuecomment-1752123974_

**Comment by posva** [comment]
it's already released on 2.7

**Comment by shyamzpassion** [comment]
@posva 

2.7 seems to have an upgrade guide due to the other changes involved. For a large scale application this could take time and effort. However if the same change change is made available as 2.6.15 there wouldn't be any hesitation for upgrading
