### ISSUE TITLE
attached

### ISSUE THREAD

**Issue by marfalkov** [vuejs/vue#131]
Foo getting rendered in both cases but the attached callback never get called in the first case.
jsfiddle: http://jsfiddle.net/marfalkov/B8vZL/

``` javascript
var Foo = Vue.extend({
    template: "<p>foo</p>",
    attached: function() {
        console.log("I'm attached"); // only run in test2
    }
})

var test1= new Vue({
    template: "<div v-component='foo'></div>",
    components: {
        foo: Foo
    }
})
test1.$appendTo("body")

var test2 = new Foo()
test2.$appendTo("body")
```

**Comment by reemaalwail** [comment]
Now this is my problem 🤗

**Comment by marfalkov** [comment]
@reemaalwail now you can use a global event bus or vuex:

https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860

**Comment by reemaalwail** [comment]
> @reemaalwail now you can use a global event bus or vuex:
> 
> https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860
thanks bro I am solved
