### ISSUE TITLE
vue的tags组件router-link标签跳转已打开页面不重新加载数据,有什么好方法吗？

### ISSUE THREAD

**Issue by smilingClown** [vuejs/vue#13119]
### What problem does this feature solve?
需要让页面不进行重新加载

### What does the proposed API look like?
<div class="tags" v-if="showTags">
    <ul>
        <li class="tags-li" v-for="(item,index) in tagsList" :class="{'active': isActive(item.path)}" :key="index">
            <router-link :to="item.path" class="tags-li-title">
                {{item.title}}
            </router-link>
            <span class="tags-li-icon" @click="closeTags(index)"><i class="el-icon-close"></i></span>
        </li>
    </ul>
    <div class="tags-close-box">
        <el-dropdown @command="handleTags">
            <el-button size="mini" type="primary">
                标签选项<i class="el-icon-arrow-down el-icon--right"></i>
            </el-button>
            <el-dropdown-menu size="small" slot="dropdown">
                <el-dropdown-item command="other">关闭其他</el-dropdown-item>
                <el-dropdown-item command="all">关闭所有</el-dropdown-item>
            </el-dropdown-menu>
        </el-dropdown>
    </div>
</div>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by xu-yi-hang** [comment]
set router parms ，if true update component key value
