### ISSUE TITLE
When ref and reactive are used together with computed and watch, computed loses its effect.

### ISSUE THREAD

**Issue by milletlovemouse** [vuejs/vue#13139]
### Version
2.7.16-beta.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/p/sandbox/vue2-demo-vwcsg3?file=%2Fsrc%2FApp.vue)

### Steps to reproduce
> **Go to the reproduction link and first open the console to see the print information.**
> computed relies on ref or reactive, and watch relies on computed. At this time, computed loses its effect and cannot get the latest data. The following code replaces reactive with ref and has the same effect.
```js
import { ref, reactive, computed, watch } from "vue";
const state = reactive({});
const com1 = computed(() => state.a || []);
const com2 = computed(() => state.b || []);
watch(
  () => com1.value,
  () => {
    console.log(com1.value, com2.value, "watch");
  }
);
window.setTimeout(() => {
  const data = { a: [{ code: 1 }], b: [{ code: 2 }] };
  Object.keys(data).forEach((key) => {
    state[key] = data[key];
  });
  console.log(com1.value, com2.value, "test");
}, 1000);
```

### What is expected?
```js
// print:
[Object] [Object] test
[Object] [Object] watch
```

### What is actually happening?
```js
print:
[] [Object] test
```

**Comment by yyx990803** [comment]
In Vue 2.7, **all [Vue 2 change detection caveats still apply](https://v2.vuejs.org/v2/guide/reactivity#Change-Detection-Caveats).

This means `reactive({})` creates an empty object that won't track newly added properties. To ensure properties can be tracked, you need to initialize them with `null` or `undefined` values just like in `data()`.

**Comment by milletlovemouse** [comment]
> In Vue 2.7, **all [Vue 2 change detection caveats still apply](https://v2.vuejs.org/v2/guide/reactivity#Change-Detection-Caveats).
> 
> This means `reactive({})` creates an empty object that won't track newly added properties. To ensure properties can be tracked, you need to initialize them with `null` or `undefined` values just like in `data()`.

I thought vue2.7 would be the same as vue3🥰
