### ISSUE TITLE
Missing "./types" specifier in "vue" package, how to use withDefaults in Vue2.7.15 with ts setup

### ISSUE THREAD

**Issue by 52javascript** [vuejs/vue#13138]
### Version
2.7.15

### Reproduction link
[codepen.io/wuxx/pen/GReRwwy](https://codepen.io/wuxx/pen/GReRwwy)

### Steps to reproduce
import { withDefaults } from 'vue/types'

interface Props {
  layout: string
}

const props = withDefaults(defineProps<Props>(), {
  layout: 'total, prev, pager, next, sizes, jumper'
})

### What is expected?
i want to set props default value

### What is actually happening?
8:34:23 PM [vite] Internal server error: Missing "./types" specifier in "vue" package
  Plugin: vite:import-analysis

**Comment by yyx990803** [comment]
`withDefaults` is a macro. There is no need to import it.
