### ISSUE TITLE
$forceUpdate causes getCurrentScope to get an incorrect value

### ISSUE THREAD

**Issue by 1593292349** [vuejs/vue#13134]
### Version
2.7.16-beta.2

### Reproduction link
[github.com](https://github.com/1593292349/vue-demo.git)

### Steps to reproduce
1.npm install
2.npm run start
3.Execute the "getCurrentScope "method on the console, Get the correct value
4.Click the render button
5.Execute the "getCurrentScope "method on the console,  Get the wrong value

### What is expected?
The getCurrentScope method always returns undefined

### What is actually happening?
The getCurrentScope method returns not undefined after calling the $forceUpdate method

**Comment by HawtinZeng** [comment]
![image](https://github.com/vuejs/vue/assets/73981739/c8192599-fe0f-4466-a7d9-6d3f1a147f7a)
The screen shot shows the return value of getCurrentScope, it may be the effect scope of current component?(App.vue component in your offered codebase), by the way, your new vue instance(vm) have not be mounted into the DOM(.$mount() haven't offer position reference to mount).

**Comment by HawtinZeng** [comment]
I found some new details, 
![image](https://github.com/vuejs/vue/assets/73981739/559cfc55-0ed7-484a-98e3-f7fc3eb48538)
when I place console.log(getCurrentScope()); at #1, the result including effects property, whose value is an array, have a item whose $el property is <div id='app'....> dom node, and when palced console.log(getCurrentScope()); at #2, in the same place, whose $el property is <div>..
