### ISSUE TITLE
Dynamic component not rendering slot tree

### ISSUE THREAD

**Issue by Dimas-e63s** [vuejs/vue#13177]
### Vue version

2.6.12

### Link to minimal reproduction

https://codepen.io/Dimi_0-o/pen/QWPKENG?editors=1010

### Steps to reproduce

1. Open https://codepen.io/Dimi_0-o/pen/QWPKENG?editors=1010 with chrome, full width,
2. click the "Open Create Modal", the modal with text-field renders properly
3. Decrease the width of the window so that you hit the mobile media query (max-width: 800px)
4. the modal is now in fullscreen but label of text-field is not rendered

### What is expected?

the label of text-field should be rendered

### What is actually happening?

once a dynamic update of the drawer component, the label of text-field (slot) is not rendered

### Any additional comments?

It's the same issue as this one https://github.com/vuejs/vue/issues/6891, however, git history shows that there were fixes to this issue in version 2.5.3, but the bug still appears in 2.6.12

**Comment by posva** [comment]
Only open issues with minimal repros (no vuetify)
