### ISSUE TITLE
Preserve async component element until loaded

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#1318]
Example:
http://jsfiddle.net/5sH6A/164/

Should the element be removed if a component is a factory function? I may want to have "Loading" text within the element before the Async component has loaded, or classes on the element to show a loading animation.

**Comment by yyx990803** [comment]
That's a good point, should be doable.

**Comment by niluanxy** [comment]
When i'm coding，i also meet this question,my solation is make a timer to listen check dom's height value,when can get the dom's height value,it means the dom has render. this is my code:

```JavaScript```
/* 简单判断元素渲染完成后执行某操作 */
render: function(call) {
    var handle, that = this, argv = [];

    for(var i = 1; i<arguments.length; i++)
        argv.push(arguments[i]);
    handle = setInterval(function() {
        if (that.width() > 0 && that.height() > 0) {
            if (typeof call == "function")
                call.apply(null, argv);
            clearInterval(handle);
        }
    }, 20);

    return handle;
}
```

**Comment by niluanxy** [comment]
by the ways,in my solation,it can't check dom that is't display,because these dos can't get value of height or width.

**Comment by TerenceZ** [comment]
@niluanxy I think you can consider this [repo](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js) to listen the resize of an element (by writing a `resizable` component in my case). However, to do more with vue, you can update `resizable`'s size in `attached` hook and rewrite the `v-show` by adding an event bus to trigger an event like `ui-visible` to let the `resizable` know to update its size info if needed. 

@yyx990803  by the way,  to rewrite the `v-show` I have to import "vue/src/transition" in explicit, so is it possible to export the transition so the plugin can use it when "I know what I am doing"?

**Comment by straps** [comment]
+1 for the loading text or animation, are there any news on this topic?

**Comment by yyx990803** [comment]
The outlined behavior in the original request actually conflicts with the slot usage, so this will unlikely be implemented. We will consider how to handle async components' pending state separately.
