### ISSUE TITLE
Why does manipulating the style property of the DOM not take effect?

### ISSUE THREAD

**Issue by workCleaner** [vuejs/vue#13204]
### Version
2.5.22

### Reproduction link
[codesandbox.io](https://codesandbox.io/p/sandbox/bold-keldysh-wxsf5x)

### Steps to reproduce
When a DOM element uses style="display:none;" and is involved in v-else-if rendering within a component, removing the style attribute directly from the DOM can fail. On the App page in CodeSandbox, the removal method will execute after a seven-second delay.

### What is expected?
The style attribute is removed correctly.

### What is actually happening?
The style attribute is not removed correctly.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
