### ISSUE TITLE
fail to resolve custom directive on component

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue#1442]
```html
<comp v-custom-directive></comp>
```
As above, if we apply a custom directive on a component, then vue will complain the custom directive not found because the directive is resolved on the component's options, not its context.

 Here is an online [example](https://jsfiddle.net/TerenceZ/ee5b5p99/1/). An error message is logged in the console.

Test version: 1.0.0-beta.4

**Comment by posva** [comment]
I found this problem yesterday too. Not sure if this is intended or not

**Comment by karevn** [comment]
It's by design. https://github.com/vuejs/vue/issues/1297
