### ISSUE TITLE
Pass token string as prop doesnt work

### ISSUE THREAD

**Issue by Smeaven** [vuejs/vue#1443]
Html File
```html
<manager name="MyName" token="{{ token }}"></manager>
```

With vue-loader I created a custom component (below), which I use in my html file (above)

Component
```vue-js
<template>
    <p>{{ token }}</p>
    <p>{{ name }}</p>
</template>

<script>
    module.exports = {
        props: ['token','name']
    }
</script>
```

I pass a token (a very long string) as a prop to my component. It seems, that Vue cannot handle such large strings, because the output of token is empty. For short string I got no problems - the name prop is shown.

Output
```html
    <p></p>
    <p>MyName</p>

**Comment by fnlctrl** [comment]
name="`MyName"
or name="MyName" ？

**Comment by Smeaven** [comment]
That ` was a typo!

**Comment by fnlctrl** [comment]
Sorry, I replied to the old issue email sent automatically sent from github...

**Comment by Smeaven** [comment]
The isssue is kind of solved.
In my original code is use `accessToken` as prop name. In that case, it couldn't set the property, but if I do it like in my example, it does work.

**Comment by yyx990803** [comment]
http://rc.vuejs.org/guide/components.html#camelCase_vs-_kebab-case
