### ISSUE TITLE
Why change data in for() with another var, model also changed?

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vue#1444]
http://jsbin.com/bujuvi/1/edit?html,output
I tried to define a new var to change data in model (don't want to change it in Vue model), why data in Vue model also changed?

**Comment by yyx990803** [comment]
This is exactly what should happen... you are modifying the array by reference.

**Comment by galenyuan** [comment]
so how can I only change in for(), keep it in Vue model?

**Comment by yyx990803** [comment]
You need to do a deep clone of the array.
