### ISSUE TITLE
Dynamic component's v-bind one way and .once modifier not working. 1.0.0-rc.1

### ISSUE THREAD

**Issue by tianhai82** [vuejs/vue#1445]
v-bind one way and v-bind .once still allows child component to change parent component's data.
See http://jsfiddle.net/9a0uxja6/1/.

Click on one of the link "CompA" or "CompB". Edit the text in the input textbox in the child component.
The value of the parent component will be changed accordingly even if the .once modifier is used to pass the data to the child component.

**Comment by yyx990803** [comment]
See the red note section: http://rc.vuejs.org/guide/components.html#Prop_Binding_Types

You are passing down an object by reference. `.once` only ensures if the child sets `this.comp = somethingElse` it won't affect the parent. If you want a completely fresh object you need to make a deep clone yourself.

**Comment by tianhai82** [comment]
Thanks.

**Comment by weilao** [comment]
How about a deep clone modifier?

**Comment by fullfs** [comment]
@weilao you could use a custom filter for that

**Comment by weilao** [comment]
@fullfs Thanks, it works!
