### ISSUE TITLE
Demo for transitions in current docs broken

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue#1447]
http://vuejs.org/guide/transitions.html#Staggering_Transitions

The embedded fiddle: http://jsfiddle.net/yyx990803/ujqrsu6w/light/

error: `[Vue warn]: Failed to resolve directive: transition`

Because it's using the js from the `dev` branch which is rc1, but the fiddle uses the old 0.12 syntax (v-repeat, v-transition)

**Comment by marcvdm** [comment]
If you want old syntax with deprecation warnings you can use the migration branch
http://jsfiddle.net/ujqrsu6w/41/

This is a working rc fiddle
http://jsfiddle.net/ujqrsu6w/40/

**Comment by cheapsteak** [comment]
Thanks, I'm mainly concerned about anyone looking at the broken example in the doc

**Comment by yyx990803** [comment]
Fixed, thanks!
