### ISSUE TITLE
Docs for RC missing `transition-mode`

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue#1448]
It's there in docs for 0.12 http://vuejs.org/guide/components.html#transition-mode

Missing from docs for RC:

http://rc.vuejs.org/guide/transitions.html#JavaScript_Transitions

**Comment by crswll** [comment]
Is this what you believe is missing? http://rc.vuejs.org/guide/components.html#transition-mode

**Comment by cheapsteak** [comment]
Oh yes, there it is o_o 
I was looking for it in the wrong place
