### ISSUE TITLE
Don't remove attributes directives in debug mode

### ISSUE THREAD

**Issue by finico** [vuejs/vue#1452]
Vue removes all directive attributes after compiling them.
Is it difficult to do so that they were not removed in debug mode?
It would be very convenient for debugging.

[suggestion]

**Comment by syntime** [comment]
+1

**Comment by yyx990803** [comment]
Unfortunately this would somewhat interfere with Vue's compilation process and it's not a simple change, but in the future the new vue devtool will allow you to inspect directives bound to an element.
