### ISSUE TITLE
动态模板问题

### ISSUE THREAD

**Issue by peijian708** [vuejs/vue#1453]
现在有这样一个需求，数据是通过ajax加载的，加载数据不变，通过动态切换模板，来实现前端页面不同的展现风格，我找到了这个 https://github.com/vuejs/vue/issues/159，但是我不知用partial还是component，partial模板只能是拼接字符串的方式，能不能加载一个 `<script type="x-template" id="temp">`，component是不是要用 `<component :is="componentId"></component>`，但是这样我如何把data参数传过去，能不能象knockoutjs那样加载template，能不能加载一个html片段的方式。请您给解答一下，谢谢！

**Comment by yyx990803** [comment]
1. 问题请不要发在这里，发到[论坛](http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87)。
2. 提问请条理清晰一些。看不懂我也没法帮你。
