### ISSUE TITLE
Filter used in options only run once 

### ISSUE THREAD

**Issue by A-limon** [vuejs/vue#1454]
Template:

```javascript
<select  v-model="selected" options="selecteList | youCanUse"></select>
```

Filter:

```vue
Vue.filter('youCanUse', function (value) {
  return value.map(function (item) {
        return {
            text: item.name,
            value: item,
            disabled: item.disabled
       }
  });
});
```

when I change the one of the  `selecteList`  object item's `disabled` property to `false`.
the `youCanUse` filter doesn't make that option's disabled property to `false`.

Does the filter in options only run once or I used in a wrong way ? And How can I make it work properly？

**Comment by squirmy** [comment]
Gave it a shot, this mostly works for me:
https://jsfiddle.net/ypt9700e/

The caveat is that it doesn't update whilst the select box is still open.

**Comment by A-limon** [comment]
@squirmy Thank you !!
I think I found the reason: I didn't initial the `selecteList ` `disabled` property
```vue
selecteList: [{
   name: 'Learn JavaScript'
}, {
   name: 'Learn Vue.js'
}],
```
that won't work properly.

And I found another problem:
https://jsfiddle.net/ypt9700e/1/

when I changed the `v-model` `selected` to an object, it doesn't fired the `change` event.

**Comment by yyx990803** [comment]
`change` event only fires from user input. It doesn't fire when you set the value in JavaScript.

**Comment by squirmy** [comment]
no problems - i'm actually surprised the disabled thing worked :)

you can set the selected object, try doing this instead:

```javascript
setTimeout(function () {
    demo.selected = demo.selecteList[0];
}, 2000);
```
your problem was that you were setting it to an object which didn't exist in the select
