### ISSUE TITLE
Problems with new syntax

### ISSUE THREAD

**Issue by fullfs** [vuejs/vue#1455]
Hello!
Having some troubles trying v1.0 lately.

1. Jade fails to work with ```:name``` attributes (the ones beginning with colons). If used two in line, you will get syntax error. For example ```div(:name="something" :title="other")```. It look like it's a jade bug and I've reported it, but I feel like the developers won't fix it because colons a special in jade syntax too

2. Using Webpack UglifyJsPlugin like ```webpack.optimize.UglifyJsPlugin({minimize: true})``` fails on ```@click``` attributes. It just freezes out on building

Overall, it's not directly Vue.js problem, yes. But it looks like Vue.js developers will have to face many unexpected problems with new syntax. I don't think the list above is a complete one.

**Comment by fullfs** [comment]
*Update:*
You have to write like this in Jade
```div(":name"="something" ":title"="other")```
I you want begin with colon

**Comment by posva** [comment]
I personnaly use `v-bind` everywhere when writing in jade and I never had that bug with  webpack. Do you have a repro

**Comment by yyx990803** [comment]
I think proper Jade syntax is that you **should** separate attributes with commas: http://jade-lang.com/reference/attributes/

And as for `@click`, I've never had the issue - make sure you upgrade everything (webpack, vue-loader) to the latest version.
