### ISSUE TITLE
1.0.8 Alpha Deprecation issue on v-bind:readonly

### ISSUE THREAD

**Issue by ibcooley** [vuejs/vue#1456]
I'm getting deprecation warnings when using v-bind:readonly="isReadonly" on an input field.
```html
[Vue warn]: {DEPRECATION} Mustache interpolation found in non-native attribute "readonly": attribute interpolation will be limited to native attributes only in 1.0.0. Use v-bind for custom attributes and props.
```
I can make this warning go away with using the hyphenated version: v-bind:read-only="isReadonly",
however it does not behave as expected (putting the readonly attribute on the html element).  Instead it adds the 'read-only' attribute to this element.

I suspect this is due to the javascript equivalent of the attribute being 'readOnly', whereas the html version is 'readonly'.

Are there any known/planned workarounds for this?

**Comment by yyx990803** [comment]
This warning has been relaxed in 1.0.0-rc.1. The alpha version is using the old check, which should be fixed soon.

**Comment by ibcooley** [comment]
Excellent, that is good to hear. I suspect this means the attribute binding will still behave as expected?

**Comment by yyx990803** [comment]
yes.
