### ISSUE TITLE
v-transition's `leave` should be called before the component's `destroy`

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue#1457]
When I have a component that has child components, I'd like to call methods on the child component to animate out when the parent component needs to leave, but in the `leave` hook you can't access references anymore because everything has already been destroyed

```js
leave (el, done) {
  this.$refs.childcomponent.animateOut().then(done);
  // error because this.$refs.childcomponent is null
}
```

I think components should wait for the leave to finish before calling destroy

**Comment by yyx990803** [comment]
Can you make a repro?

**Comment by cheapsteak** [comment]
Here's what I have for now, one of the libraries doesn't have a cdn version, will make a fiddle after work
https://github.com/cheapsteak/demo-react-transitiongroup/blob/vue/src/main.js

**Comment by yyx990803** [comment]
Turns out changing that order is more complicated than I thought - 9719cfa64c49d5daa55d35268f46e7e405107624 is more like a workaround (children are still destroyed, but refs are kept) - it seems to address your specific issue, although I'm not sure if there's a valid use case where we want the child to be alive in the leave hook.

**Comment by cheapsteak** [comment]
It doesn't quite address the issue, I accidentally left a line out (was editing the code around a lot yesterday)

The parent's animateOut is supposed to have something like

```
    //the parent
    async animateOut () {
      await this.$refs.child.animateOut();
      await animate.to(this.$el, 0.5, this.animationStates.out)
    }
```


the `leave` in the parent is supposed to call a method on the child to tell it to animate out (because the child doesn't receive transition events when the parent animates out)

So when a a leave happens, the transition calls `animateOut` on the parent, and the parent would call `animateOut` on the child, only having a reference is not sufficient since no methods can be called

**Comment by yyx990803** [comment]
Have you considered doing this type of sub-animation in the `deactivate` route hook instead of the transition?

**Comment by cheapsteak** [comment]
That works perfectly, thank you!

**Comment by stephanebressani** [comment]
Hello, i have a similar problem with await this.$refs
My code:
```
mEventAlert: async function(emitAlert) {
   // some code
   await this.$refs.menus_en_ligne.mLoadList()
   // await this.$refs.pages_hors_ligne.mLoadList()
   // await this.$refs.blocks_hors_ligne.mLoadList()
   this.$forceUpdate()
}
```
This work, when i put a alert('test') inside this.$refs.menus_en_ligne.mLoadList()

When i put:
```
mEventAlert: async function(emitAlert) {
   // some code
   await this.$refs.menus_en_ligne.mLoadList()
   await this.$refs.pages_hors_ligne.mLoadList()
   // await this.$refs.blocks_hors_ligne.mLoadList()
   this.$forceUpdate()
}
```

Only the first is loading, the other give me a error
```
Uncaught (in promise) TypeError: Cannot read property 'mLoadList' of undefined
```

And when i put:
```
// await this.$refs.menus_en_ligne.mLoadList()
await this.$refs.pages_hors_ligne.mLoadList()
// await this.$refs.blocks_hors_ligne.mLoadList()
```
the second is loaded fine

the solution for me now... write code without async :(

**Comment by stephanebressani** [comment]
i solved the problem with beforeDestroy(), mount()...

**Comment by m4heshd** [comment]
Just ran into this issue. All `before-leave`, `leave` and `after-leave` are fired **after** the component is destroyed. There's no workaround for me. Issue is still there on Vue 3.
