### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Zharv** [vuejs/vue#1460]
v 1.0.0-rc2 line 9491

var fn = expParser.parse(expression).get 

Uncaught TypeError: Cannot read property 'get' of undefined
  Directive._checkStatement	
  Directive._bind	
  linkAndCapture	
  compositeLinkFn	
  exports._compile	
  exports.$mount	
  exports._init	
  Vue	
  init

**Comment by yyx990803** [comment]
You need to provide a reproduction showing what code is causing this error.

**Comment by rpkilby** [comment]
Hi. I ran into this when updating code using an older version of vue-router. The problem is improper v-link syntax, such as `v-link="/foobar"`.

Correct syntax is `v-link="'/foobar'"` or `v-link.literal="/foobar"`.

The error message could be improved though.
