### ISSUE TITLE
v-text in option

### ISSUE THREAD

**Issue by duebbert** [vuejs/vue#1461]
Not sure if this is strictly a bug of vuejs (tested in rc2). JSfiddle: https://jsfiddle.net/7gzaous5/ 

This doesn't work:
```html
    <select v-model="span">
        <option v-for="obj in contacts" v-bind:value="obj.value">
            <span v-text="obj.text"></span>        
        </option>
    </select>
```
The obj.text is not shown.

While this works:
```html
    <select v-model="span">
        <option v-for="obj in contacts" v-bind:value="obj.value">
            {{ obj.text }}
        </option>
    </select>
```

The reason is most likely that &lt;option&gt; only allows text but at least Chrome doesn't have a problem with normal &lt;span&gt;s in it, so it must be connected to how vuejs is treating the v-text.

**Comment by yyx990803** [comment]
Chrome removes empty `<span>` tags inside options. This is not Vue related.

**Comment by duebbert** [comment]
OK, but why are they empty? They shouldn't be.

**Comment by duebbert** [comment]
Ah sorry, I assume that chrome removes the tag before vue starts. All clear
now. Might be worth a comment in the docs somewhere as I'm probably not the
only one to fall into this trap
