### ISSUE TITLE
v1.0.0-rc.2 Not passing data to child components via props

### ISSUE THREAD

**Issue by Teevio** [vuejs/vue#1463]
Child components are unable to inherit data from their parent via the props attribute.

The steps to reproduce this are to create a child component and try to pass down data properties as outlined in the docs: http://vuejs.org/guide/components.html#Props

You can see this reproduced here: http://jsfiddle.net/2uqmj2jj/4/

**Comment by yyx990803** [comment]
You are not passing the props: http://jsfiddle.net/yyx990803/2uqmj2jj/6/

**Comment by Teevio** [comment]
@yyx990803 ahhhh thanks!
