### ISSUE TITLE
Invalid prop type check - String/Undefined

### ISSUE THREAD

**Issue by bryannielsen** [vuejs/vue#1464]
I'm getting the following warning with 1.0.0-rc.2 

`Invalid prop: type check failed for mapId="map". Expected String, got Undefined.`

I'm transitioning a 0.12.16 setup and this seems to be my last issue I can't get past. 
Thanks for the help!

**Comment by yyx990803** [comment]
Most likely you are not passing the prop correctly. Note in 1.0 you need to explicitly pass props when using `v-for` on a custom component. Can't help you further without looking at actual code.

Closing since this is unlikely to be a bug.

**Comment by bryannielsen** [comment]
Thanks for the quick response!

I've distilled the code down a bunch so that I can share it, it seems pretty simple and straightforward to me, but you're right it could definitely be an issue on my end.  I'm not using a `v-for` directive anywhere in this component so I don't think it's related to that.

Component props section:
````
props: {
      mapId: {
        type: String,
        required: true
      }
}
````

Calling component:
`<component v-bind:map-id="map"></component>`

Thanks for taking a look

**Comment by simplesmiler** [comment]
@bryannielsen I'll take a guess and say that you are trying to pass a literal string to the prop. The syntax for this would be `map-id="map"`.

**Comment by yyx990803** [comment]
`v-bind` will treat `map` as an expression and try to evaluate it.

**Comment by bryannielsen** [comment]
Ah you're absolutely right @simplesmiler, I got overzealous in converting all the props during my upgrade.  Thanks for the help and thanks for the awesome framework @yyx990803!
