### ISSUE TITLE
$index and $value in v-for vue 1.0.0

### ISSUE THREAD

**Issue by onefriendaday** [vuejs/vue#1465]
Hi!

I upgraded a project made with 0.12 to 1.0.0 and saw that the values to get the current index in vue subcomponent aren't available anymore.

In my project i used following to get the index and key inside a v-for:
```
<template v-for="subitem in item">
   <tree :model="subitem"></tree>
</template>

var key = this.$index // This gave me back the current index
var container = this.$parent.$value // This gave me back the containing array
```

What's the best way to get this back working?
My idea was to pass the key and index as props to the child-component.
<tree :parentkey="key" :index="$index" :model="subitem"></tree>

Thanks

**Comment by yyx990803** [comment]
Yes, pass them as props.
