### ISSUE TITLE
v-if and v-else don't work correctly with some tags

### ISSUE THREAD

**Issue by HelloGravity** [vuejs/vue#1467]
Hello,
I have noticed that v-if, v-else don't work correctly when applied to ```<p>```.
Here is an example: http://jsfiddle.net/373nkkg5/
In the example I made a simple nested if-else. It does work with ```<div>``` or ```<u>``` instead of ```<p>```. 
It only fail when ```number``` is 1.
I don't think that this is specific to ```<p>```, but for all other tags that I tried it did work.

**Comment by OEvgeny** [comment]
According to [HTML5 spec](http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-p-element) nested `p` tags are not allowed see [this](http://stackoverflow.com/a/9852381).
