### ISSUE TITLE
vue directives in v-html directive

### ISSUE THREAD

**Issue by envomer** [vuejs/vue#1468]
I am trying to parse HTML text that uses some vue directives.

```
var content = '<a v-link="{path: \'/somewhere\'}"> redirect </a>'.
```

Inside my html file i've got

```
<div v-html="content"></div>
```

Is there any way to parse that content?

**Comment by yyx990803** [comment]
1. Don't abuse `v-html`. Use components.

2. If you want to reuse templates, use [partials](http://vuejs.org/api/#partial)
