### ISSUE TITLE
beforeDetach hook

### ISSUE THREAD

**Issue by zenozeng** [vuejs/vue#1469]
I am now trying to write a list view component for Vue.
And I had a problem saving state of current items before detach.

I want to collect boundingClientRect of all list items on beforeDetach, so that I can restore the ListView when re-attach <list-view>.

So, I wonder, if there is a way to exec certain code right before detach, or is there any plan for it?

**Comment by yyx990803** [comment]
Currently no, but it is easy to add. For now you can use a transition's `leave` hook...

**Comment by zenozeng** [comment]
Thanks a lot.

**Comment by fnlctrl** [comment]
+1

**Comment by smolinari** [comment]
If I may ask, what is a list view component @zenozeng ?

Scott

**Comment by zenozeng** [comment]
See https://github.com/CatchLabs/vue-list-view

**Comment by smolinari** [comment]
Thanks @zenozeng. 

Scott

**Comment by yyx990803** [comment]
Dropping this because in most cases you can do this before you manipulate the data instead.

For items with transitions, do it in the `beforeLeave` hook.

Also in 2.0, attach/detach hooks are being deprecated. If a component is being removed then it is being destroyed.
