### ISSUE TITLE
Comment Nodes returned for component this.$el

### ISSUE THREAD

**Issue by billcolumbia** [vuejs/vue#1471]
While having `Vue.config.debug = true;` enabled, I noticed that a component would return it's debug comment nodes: `<!--v-start-->` when trying to access `this.$el` on the component. I tried to recreate on JSFiddle but had quite a few issues. I'm on v1.0.0rc2 and using the `component_name.vue` to have template, script, and style together. Here's some code I hope can help...

https://github.com/billcolumbia/fieldeditor/blob/debug-thisel/resources/assets/js/components/field.vue#L36

The JS is all in `resources/assets/js`. I was able to keep deving by turning off this debug prop for now.

The goal is to have an `Editor` component appear under each row of `Field` types where the field that is clicked can be edited. That's why I am passing the `Field` component's data and it's parent node (the row) via `.$dispatch()` (to the `App` component), which then sets the an `anchor` prop on the `Editor` component so it knows which row to be appended after:

Click `Field` component -> `.$dispatch( field's data, field's parent node)` to `App` component -> `App`'s `event.startEditing(args)` sets the `anchorEl` as a prop on the `editor` component -> used by `Editor` to append itself after passed `anchorEl`.

I'm new to Vue as of this week, and it has been a challenge to think outside of the jQuery, so I apologize if my way of getting this to work is very roundabout. I'm learning a ton, and more importantly re-learning how to think about solving problems with Vue - it's awesome so far. Hope this issue helps!

**Comment by yyx990803** [comment]
That extra comment node is turning the component into a [fragment instance](http://vuejs.org/guide/components.html#Fragment_Instance). Just remove the comment node to ensure your component template has a single root node.
