### ISSUE TITLE
Error in documentation: Building Large-Scale Apps > Unit Testing - wrong test

### ISSUE THREAD

**Issue by skupr** [vuejs/vue#1472]
http://vuejs.org/guide/application.html#Unit_Testing

my-component.js data contains **msg** property, but in test:
```javascript
    var defaultData = myComponent.data()
    expect(defaultData.message).toBe('hello!')
```
it is referred as **message**.

**Comment by posva** [comment]
@skupr Next time you can create the fix yourself at https://github.com/vuejs/vuejs.org and submit a PR :smile:. (Be sure to contribute to the right branch)
