### ISSUE TITLE
Two-way Binding and Spaces

### ISSUE THREAD

**Issue by qw3rtman** [vuejs/vue#1476]
In the [Two-way Binding example on the Getting Started section of the docs](http://vuejs.org/guide/index.html#Two-way_Binding), using multiple spaces in a row in the `input` translates to only one space in the `p`. This same behavior is seen in HTML with multiple spaces in a row.

In order to more accurately translate what is passed in the `input`, the number of spaces should be the same. This could be done by replacing a space with `&nbsp;` in order to bypass HTML's behavior.

Thoughts?

**Comment by yyx990803** [comment]
If you want accurate whitespace, just use a `<pre>` tag.
