### ISSUE TITLE
Async component and asset array syntax v1.0

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#1477]
Prior to v1.0 i was able to create an async component (factory function) and give it an `id` to that I could register it with array syntax. e.g:

```javascript
export function chartistComponent (resolve, reject) {
  // async request and resolve
}
chartistComponent.id = 'chartist';
```

```javascript
// other component - import component and register
import { chartistComponent } from 'xxx';

...
     components: [chartistComponent],
...
```
Now that `id` has changed to `name`, I can no longer do this as `Function.name` is read only.  Apart from not using the array asset registration syntax, is there anything that can be done here?

**Comment by yyx990803** [comment]
Hmm, this is something I overlooked when renaming that option. You can use `id` again as in 296dc78

Also, with ES6 you can do this:

``` js
export function Chartist (resolve, reject) {
  // ...
}
```

``` js
import { Chartist } from 'xxx'

export default {
  components: { Chartist }
}
```
