### ISSUE TITLE
Bug: filterBy resulting in duplicate entries

### ISSUE THREAD

**Issue by kcalliauw** [vuejs/vue#1479]
Hi,

As witnessed in the following JSbin:
http://jsbin.com/liwexa/5/edit?html,js,output

When filtering on multiple fields, the search value should be null instead of an empty string. When a user types something in the search box, the filter works, but when deleting the input again, the output results in duplicate entries. The initial rendering can be fixed by initialising search as null.

Cheers,
Koen

**Comment by BuptStEve** [comment]
我也碰到这问题了╮(╯_╰)╭，因为用的v1.0.0 ，升级之后解决～=￣ω￣=～
