### ISSUE TITLE
`v-bind` not a sufficient replacement for `v-attr`

### ISSUE THREAD

**Issue by adamgoose** [vuejs/vue#1499]
The `v-attr` directive used to allow you to pass an object like `{class: 'form-control', min: 3}`. For example...

```html
<input type="text" v-attr="aforementionedObject">
```

would render...

```html
<input type="text" class="form-control" min="3">
```

Now, using the new `v-bind` attribute in v1.0 would result in the following output.

```html
<input type="text" null="[object Object]">
```

Is there a new way to mass-assign attributes to a DOM element using the `v-bind` attribute?

**Comment by ppq1991** [comment]
v1.0 style
```javascript
<input type="text" v-bind:class="myClass"  v-bind:min="myMin">
```
or
```javascript
<input type="text" :class="myClass"  :min="myMin">
```

**Comment by adamgoose** [comment]
I'm aware of this format, however I need the ability to pass a dynamic object to the directive. We're building a form-builder.

![](http://d.enge.me/1dlTm+)

**Comment by posva** [comment]
you should be able to simulate the same behaviour with a directive that add the bindings. Thought I am not sure this is the best...

**Comment by theGC** [comment]
I'm had the same issue moving from ~0.12 to v1

We have unknown attribute keys being passed and can no longer attach the object to v-attr, and v-bind only works if we know what the keys are.

I think we need a special directive for v-bind much like class & style: 

`v-bind:attr`

If it only accepts an object then we could pass any unknown attributes to it and have them output on the element.

Not sure about others, or if it makes a great difference to the way its built, but in the cases I currently have it wouldn't need to track the state of the object it outputs as attributes as they are static.

**Comment by adamgoose** [comment]
Temporary solution:

- Grab the old `v-attr` source from [here](https://github.com/vuejs/vue/blob/0.12/src/directives/attr.js).
- Remove the "priority" option (not necessary)
- Add `deep: true` to the object.
- Register it as a custom directive where necessary. 

Seems to work well enough for me, but I still think it should be supported.

**Comment by TerenceZ** [comment]
version^1.0.2 supports object binding for `v-bind="attrs"` now, you can check from the commit  d9fa2b47b1be9e06e3f0c28c5bfe768d053e9f76

**Comment by theGC** [comment]
Works well for me, it isn't "reactive" but that's fine for the cases where I currently need this feature. 

@yyx990803 Thank you

**Comment by yyx990803** [comment]
@theGC ah, it **should** be reactive. That will be the case in next patch.

**Comment by theGC** [comment]
@yyx990803 I was testing in 1.0.3 if that helps... http://jsfiddle.net/thebigsurf/vs0sh7b0/
