### ISSUE TITLE
P标签使用v-for无法正常执行

### ISSUE THREAD

**Issue by qkzsky** [vuejs/vue#1500]
P标签改为其它标签如DIV可正常执行，版本1.0.1
代码如下
HTML
<div id="demo">
    <p v-for="item in list">
        <div v-text="item.message"></div>
    </p>
</div>

JS
new Vue({
    el: "#demo",
    data: {
        list: [
            {message: "123456"},
            {message: "ABCDEFG"}
        ]
    }
});

**Comment by yyx990803** [comment]
P 里面不能嵌套 div。
