### ISSUE TITLE
Upgrading to 1.0: Duplicate value found in v-for

### ISSUE THREAD

**Issue by PhillippOhlandt** [vuejs/vue#1552]
Hello,

I try to upgrade my vue app to 1.0 and get the following error over 200 times for each for loop:
`[Vue warn]: Duplicate value found in v-for="book in books": "\"". Use track-by="$index" if you are expecting duplicate values.`

This is my template code with 2 loops:
```
<select name="relation[books][]" multiple="" tabindex="-1" style="display:none;">
        <template v-for="book in books">
            <option :value="book.id" selected>
                {{book.title}}
            </option>
        </template>
    </select>

    <div id="sortable-books" class="extended-relation-select__list --entries">
        <template v-for="book in books">
            <div>
                <i class="fa fa-bars"></i>

                {{book.title}}

                <div class="pull-right">
                <span class="buttons">
                    <i class="fa fa-times" @click="removeEntry($index)"></i>
                </span>
                </div>
            </div>
        </template>
    </div>
```

And this is my array with the entries:
```
"books": [
    {
      "id": "55",
      "title": "Wir nennen es Politik"
    },
    {
      "id": "1",
      "title": "Die Bienen"
    },
    {
      "id": "2",
      "title": "Finnisches Feuer"
    },
    {
      "id": "3",
      "title": "Träume Digitaler Schläfer"
    }
  ]
```

Can someone explain me the issue here?

**Comment by yyx990803** [comment]
Please make a live reproduction.

**Comment by PhillippOhlandt** [comment]
I solved it a few minutes ago. I had a component in which I inserted a JSON string through a prop and in the `ready` method I converted the JSON string to an array and override the prop. 

But it seems that 1.0.1 tries to iterate over the JSON string before the `ready` method is called. 
Solved it by renaming the prop and save the converted JSON string in a data array on the component.

**Comment by leigang** [comment]
you should return jsonObject, instead of jsonString.
