### ISSUE TITLE
How to stop click event from bubbling?

### ISSUE THREAD

**Issue by tiye** [vuejs/vue#161]
For DOM tree like this:

``` jade
#outside(v-on='click: doOut')
  #inside(v-on='click: doIn')
```

clicking `#inside` triggers `doOut` too, despite of `event.stopPropagation()`.
What is the right way to prevent events in Vue?

**Comment by ggepenyan** [comment]
So how to fix it in vue if I'm not using jquery

**Comment by sirlancelot** [comment]
@ggepenyan This closed issue is 5+ years old and is no longer an issue. Use `@click.stop="handler"`
