### ISSUE TITLE
Filter just not work

### ISSUE THREAD

**Issue by awesomes-cn** [vuejs/vue#1641]
The `say` filter didn't work ,My demo code is:
```html
<html>
<head>
  <script type="text/javascript" src="vue.min.js"></script>
</head>
<body>
  <div id="app">
    <ul>
      <li v-for="item in items">
        <h4>{{item.name}}</h4>
        <h5>{{item.age | say}}</h5>
      </li>
    </ul>
  </div>
  <script type="text/javascript">
    var vm = new Vue({
      el: '#app',
      data: {
        items:[{
          name: 'hxh',
          age: 15
        },{
          name: 'huhu',
          age: 87
        }]
      },
      created: function(){
        console.log(this.message)  
      }
    })
    
    Vue.filter('say',function(value){
      return value + 20;
    })
  </script>
</body>
</html>

```

**Comment by azamat-sharapov** [comment]
Try to register filter before initializing vm and post questions like this on forum.vuejs.org next time.

**Comment by awesomes-cn** [comment]
Thanks,this work! just write the filter before initializing vm. mybe the Custom Filters part in guid should indicate this.

**Comment by azamat-sharapov** [comment]
It says about it here: http://vuejs.org/guide/components.html#Registration  
I recommend you to dedicate an hour or two for reading whole guide, it's very useful!

**Comment by awesomes-cn** [comment]
Good,I am reading the guid,now is to  `Conditional Rendering` part.
