### ISSUE TITLE
[suggestion] Add a transition mode for transition on list (v-for)

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#1654]
Hi, 
I have a list of components which are rendered via an array prop like such :

```
<child-component is="example"
    v-for="item in myArrayProp"
    transition="bounce"
    stagger="200"
</child-component>
```

Fact is `myArrayProp` is already filled from the beginning and I would like to transition (bounce-in) the list at the beginning for the first time.

I could do it by triggering myself some class but I'll loose the benefit from the stagger effect.

To achieve it, I found no other way to dirty hack it with flush the prop at the beginning and refills after `nextTick`

So why not give the option to trigger the "enter" transition for the first time ?
Thanks

**Comment by yyx990803** [comment]
Yeah, I've been thinking about this, could be useful.

**Comment by AlexandreBonaventure** [comment]
Glad to hear it will eventually be implemented in future versions. Thanks

**Comment by simplesmiler** [comment]
I believe this should not take the name of `transition-mode`, because this would clash with the existing meaning of `transition-mode`.

**Comment by yyx990803** [comment]
This is implemented in 2.0 as the `appear` prop. Although we'd like to backport it to 1.x, this is a non-critical change that requires non-trivial effort. Given the bandwidth we have, we are reducing the scope of 1.1 to a number of critical features and low hanging fruits, so unfortunately this will not be implemented for 1.x.

**Comment by the94air** [comment]
It's been 2 years now. Is there any chance of implementing this on Vue2?

**Comment by posva** [comment]
Did you read the comment just above yours? 😆

**Comment by the94air** [comment]
🤦‍♂️, Sorry. I am a terrible reader.
