### ISSUE TITLE
class name propagation

### ISSUE THREAD

**Issue by pcalin** [vuejs/vue#1655]
vue components do not propagate css class names more than one level deep.

working example using jade:
``` jade
parent component
  component1.first-class-name

component1
  div
```
final outcome:
div.first-class-name

perfect

however when using another components inside component1...
failing example using jade:
``` jade
parent component
  component1.first-class-name

component1
  component2

component2
  div
```
final outcome:
div

the first-class-name is missing.

**Comment by OEvgeny** [comment]
It is by design. See docs [fragment instance](http://vuejs.org/guide/components.html#Fragment_Instance).

**Comment by yyx990803** [comment]
As said, this is by design. Will have better warnings in this case in later releases.
