### ISSUE TITLE
Fail to resolve literal binding

### ISSUE THREAD

**Issue by noirbizarre** [vuejs/vue#1661]
Literal bindings are not resolved with the `v-bind:prop.literal="value"` or  `:prop.literal="value"` syntaxes.
It needs to be written `:prop="'value'"` to be resolved.

I managed to reproduce this issue on Vue.js 1.0.0-migrate and Vue.js 1.0.3. 

Here's a fiddle that reproduce the issue:
http://jsfiddle.net/noirbizarre/frqxygf0/2/

**Comment by yyx990803** [comment]
Literal modifier doesn't work on props. Literal props is just prop="string".

**Comment by noirbizarre** [comment]
Even simpler ! Thanks !
