### ISSUE TITLE
Custom directive params binding problem

### ISSUE THREAD

**Issue by Rhincodon** [vuejs/vue#1662]
Hi. I am using Vue 1.0.3 and trying to bind params into custom directive, but all params parsed as strings. This problem can be seen in this example http://vuejs.org/examples/select2.html on vuejs site. `Options` param no longer parsed as array, its just a string. I tried to use `v-bind`, but its also convert params to string `[Object, Object]`.

**Comment by yyx990803** [comment]
Ah, this is because of the custom directive didn't setup priority properly after the params API change... the fiddle is fixed with an explicit priority now, but it should work by default next release.
