### ISSUE TITLE
中文和英文文档不一致，能用心吗

### ISSUE THREAD

**Issue by humucai** [vuejs/vue#1665]
中文版的todos v-repeat 指令还存在么，给的jsfiddle上也不能渲染出数据，是替换成 v-for了嘛 ,反正我试了 控制台说v-repeat不存在的指令 for可以

**Comment by okoala** [comment]
@humucai  亲~你可以提PR。很多工作需要社区的支持才能做得更好~~

**Comment by Jinjiang** [comment]
1.0 的文档改动较大，我们新发起了一个项目 https://github.com/vuejs/cn.vuejs.org @yanxyz 已经在加紧翻译了，可以移步这里了解最新的进展

**Comment by humucai** [comment]
没注意中文文档是0.12的，npm安装了1.0的，见笑了。
