### ISSUE TITLE
Using variables in class attribute seems  to cancel out any :class binding

### ISSUE THREAD

**Issue by eybarta** [vuejs/vue#1666]
Before updating to new Vue, I was doing things like this:

```
< div class="someclass {{valign}} {{swidth}}" v-class="someclass: someBool">No Problem< / div >
```

Now with new Vue:

```
< div class="someclass {{valign}} {{swidth}}" :class="someclass: true">Problem< / div >
```

someclass never shows.. 

am I doing something wrong or is this a bug?
thx

**Comment by arthurkirkosa** [comment]
Post come code example

**Comment by eybarta** [comment]
hmm I guess I'm not too savvy here.. :) how do I post code? for now I spaced the code lines above
to show but I'm sure there's a better way to post inline code in here

**Comment by yyx990803** [comment]
@eybarta read how to use markdown: https://help.github.com/articles/github-flavored-markdown/

These two are compiled into the same thing. Don't mix them. Pick one style or the other.

``` html
<div :class="['someClass', valign, swidth, condition ? 'someclass' : null]"></div>
```

**Comment by eybarta** [comment]
ok thx
