### ISSUE TITLE
rendering custom component in list

### ISSUE THREAD

**Issue by Deall0c** [vuejs/vue#1667]
I'm trying to render a list of posts which are contained in an async loaded component in a list;
something like this:
```html
<social-post v-for="post in posts"></social-post>
```
However now I cannot access the current item (post) neither indirectly or directly (using post.<whatever>) anymore.
I am trying to upgrade from 0.12 to 1.0.4
in version 0.12 using the v-repeat this worked without problem but now I've upgraded to 1.0.4 it doesn't

[here's](http://jsfiddle.net/30LLtrx6/) a JSfiddle that demonstrates a stripped down version of the problem

**Comment by yyx990803** [comment]
Please read the upgrade guide carefully. With v-for you need to explicitly pass data in as props.

**Comment by Deall0c** [comment]
I swear to god this did not work five minutes ago...
well, must've mistyped something I guess.
apologies

**Comment by Deall0c** [comment]
After a quick review I noticed that it worked because I had accidently reverted to 0.12 again;
As shown in this updated fiddle, this doesn't work; http://jsfiddle.net/30LLtrx6/1/

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue/releases/tag/1.0.0

Search the `v-for` section.

**Comment by Deall0c** [comment]
Indeed my bad, though it seems counter intuitive to have both v-for and then explicitly having to respecify the same variable

**Comment by yyx990803** [comment]
It's more intuitive when you are trying to refactor or reuse your component later.
