### ISSUE TITLE
better warning

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue#1669]
Since the commit 778734aa888fe573f69d4bf72a5cb070d45c29f3, vue will always complain that fragment should not contain multiple attributes. However, I think the following props (for components) should not be warned:

- slot
- component props
- event bindings

Consider the following example, `slot`, `@custom-change`, `:prop` should be passed, and `:not-prop` should be warned. The `v-bind` is a complexed case, because the object may contain some props and some attributes for element and __dynamic__:(.
```
<root>
  <child slot="child" @custom-change="onchange" :prop="prop" :not-prop v-bind="mixedWithSomeProps"></child>
</root>

<template id="child">
  <inner-comp>
    <!-- something -->
  </inner-comp>
</template>
```

**Comment by yyx990803** [comment]
Props are stripped before reaching the warning check, so no need to worry about them :)
