### ISSUE TITLE
v-model directive on <div contenteditable>

### ISSUE THREAD

**Issue by bdedardel** [vuejs/vue#1670]
v-model directive can only be used on textarea o or input elements for now.
It would be nice to use it on 'contenteditable' !

Best regards,
Benjamin

**Comment by yyx990803** [comment]
Content editable involves a lot more complexity than input bindings, and it's best to use an external library dedicated to this purpose (e.g. [Medium.js](http://jakiestfu.github.io/Medium.js/docs/)), wrapped by a custom directive.

**Comment by abdulahkam** [comment]
*sorry @yyx990803 I saw that you close this issue.

Hello @bdedardel 
I work with summernote today and found your question.

My solution is you can use summernote's onChange callbacks like so :
let 'program' as my vue instance
and 'detail' as my model in 'program'. 

```javascript
          $('#summernote').summernote({
              onChange: function(contents, $editable) {
                // console.log($editable);
                program.detail = $editable;
              }
            })
```
I do not know if this is a good way to solve your problem 
*most probably you have already got it

**Comment by bdedardel** [comment]
@abdulahkam Thanks for your post. I will try this solution, even if summernote does not respond exactly to my needs!

**Comment by marrouchi** [comment]
I did manage to work with contenteditable. Here is my proposed solution : 

`Vue.component('title-editable', {
    props: ['entity','name','icon','canEdit','loading','max'],
    data: function () {
  	    return {
  	        editable: false,
  	        canEdit: this.canEdit,
  	        oldVal: this.entity[this.name],
  	        id: Math.round(new Date().getTime() + (Math.random() * 100)),
  	    }
    },
    ready: function(){
		var $scope = this;
		
		// Limit input size
		jQuery('#te_' + this.id).on('keydown',function(e){
			// Blur en enter
			if(e.which == 13) {
				jQuery(this).blur();
				e.preventDefault();
		        return false;
		    }
			// Limit string length and excempt keys(arrows, del, backspace, home, end);
			var excempt = [37,38,39,40,46,8,36,35];
			if(excempt.indexOf(e.which) === -1 
					&& jQuery(this).text().length > $scope.max){
			   e.preventDefault();
	           return false;    				
			}			
		});
	},
    methods: {
    	update: function(){
      	  var $scope = this;
      	  var newVal = jQuery('#te_' + this.id).text();
      	  if(!newVal){
      		jQuery('#te_' + this.id).text($scope.oldVal);
      	  }
      	  if(newVal != $scope.oldVal && newVal){
      		$scope.entity[$scope.name] = newVal;
      	  }
        }
    },
    template: ' \
			<h2 class="ui dividing header"> \
				<i class="icon {{icon}}" style="display: inline;"></i> \
				<span id="te_{{id}}" contenteditable="{{canEdit}}" v-bind:class="{\'ui title-editable\': canEdit}" v-on:blur="update(this.innerText)" v-on:focus="oldVal = entity[name]">{{entity[name]}}</span> \
    			<span class="ui active mini inline loader" v-show="loading"></span> \
    		</h2>',
});`

**Comment by muthu32** [comment]
Here is v-model for contentEditable https://codepen.io/muthu32/pen/oNvGyQX
