### ISSUE TITLE
Error raised when using with jQuery 2.

### ISSUE THREAD

**Issue by Gerhut** [vuejs/vue#1678]
Demo: <http://codepen.io/Gerhut/pen/RWBLYq?editors=101>

When use Vue Component, Vue create a Document Fragment to cache the DOM(?).

jQuery find delegate nodes [from event.target up](https://github.com/jquery/jquery/blob/2.1-stable/src/event.js#L421). It do not check the node it find is or is not a Element.

In jQuery 3, [A nodeType check is added](https://github.com/jquery/jquery/blob/master/src/event.js#L500). But this fix is not applied to 2.1-stable branch.

**Comment by Gerhut** [comment]
Discussion on jquery/jquery#2529

**Comment by yyx990803** [comment]
Looks like there's nothing Vue can do about this...
