### ISSUE TITLE
How can i get the real DOM where the event is binded？

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#1679]
If i click the child element of the event Dom (the e.target is the child) , How can i get the real DOM where the event binded(not the child)？

    <span class="tit" @click="eventHandler">
        <i class="i fa fa-bar-chart"></i>
        <i class="arrow fa fa-angle-right"></i>
        菜单一
    </span>

    methods: {
        eventHandler: function(e) {
            // if i click <i class="i fa fa-bar-chart"></i>
            // how to get <span class="tit" v-on="click: eventHandler">
            console.log(e.target)
        }
    }

**Comment by Mat-Moo** [comment]
Please use http://forum.vuejs.org for asking questions.
In answer to your question, pass the event info though @click="eventhandler($event)" then e.$el I think  should work (off the top of my head)

**Comment by yyx990803** [comment]
`e.currentTarget`.
