### ISSUE TITLE
Unexpected token for when using new .vue files

### ISSUE THREAD

**Issue by JoeDawson** [vuejs/vue#1685]
Hello,

Currently trying use a single-file Vue component for one of my views, but I get some errors when Browserify gets to work.

It's blank right now...

```html
<template>
	<ol class="breadcrumb">
		<li><a href="/">Home</a></li>
		<li class="active">Profiles</li>
	</ol>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus tempore excepturi ipsa dolore provident hic delectus maxime officia fuga culpa, praesentium ullam sapiente deleniti veniam quam doloremque ut vel aliquam?</p>
</template>

<script>
export default {

	name: 'ProfilesView',

	components: {
		//
	}

}
</script>
```

This gives me the following error...

```
Browserify Failed!: Unexpected token

/resources/assets/js/views/ProfilesView.vue:1
<template>
^
ParseError: Unexpected token
```

After looking at your Hacker News example (https://github.com/vuejs/vue-hackernews), I do think I have everything spelt correctly so can't see why it's throwing this error?

Any ideas?

**Comment by yyx990803** [comment]
You need to use correct build setup - for browserify you need [vueify](https://github.com/vuejs/vueify).

**Comment by JoeDawson** [comment]
Thanks @yyx990803, must have overlooked that somewhere in the docs.

**Comment by reed-josh** [comment]
Using vueify and still experiencing this issue:  http://stackoverflow.com/questions/39667838/third-party-vue-component-throwing-unexpected-token-error-when-importing
