### ISSUE TITLE
[Question/Suggestion] Using v-pre on a slot ?

### ISSUE THREAD

**Issue by JulienTant** [vuejs/vue#1686]
I created a hightlighted-code component, you can find the definition here :

https://gist.github.com/JulienTant/a81d0441fe2fbd97a05a

My problem is that if the code inside my slot contains {{ }}, then it breaks. So i immediatly thought about v-pre on the slot, but it doesn't work. i'm not sure if it's an issue, a request or a simple question actually, sorry about that.

**Comment by JulienTant** [comment]
I'm so sorry i created an issue instead of posting on the forums, i'm closing this. http://forum.vuejs.org/topic/350/use-v-pre-with-a-slot

**Comment by yyx990803** [comment]
This does seem like a use case that can be improved.

**Comment by JulienTant** [comment]
Do you have any idea about a workaround for now ? 

The only "solution" i see is to turn my component into a directive for now and apply it on the "<pre>" tag, but it's not as sexy as I want it to be

**Comment by yyx990803** [comment]
Aha, in fact, the proper way to handle this is to can make it an [Element Directive](http://vuejs.org/guide/custom-directive.html#Element_Directives) instead, since you want to interpret anything passed in as plain string, you need more control than the slot distribution mechanism.

**Comment by JulienTant** [comment]
I'll look into it then. Thanks for your time mate
