### ISSUE TITLE
[Feature] have v-el be a list combined with v-for

### ISSUE THREAD

**Issue by janschoenherr** [vuejs/vue#1697]
When using v-ref combined with v-for, it will give you an array of _refs_. It would be nice to have this feature for v-el too.

**Comment by noirbizarre** [comment]
It was the case before with Vue.js 0.12.
I can't finish my migration because some part of my app is depending on this behavior.

**Comment by HerickAmador** [comment]
+1

**Comment by fnlctrl** [comment]
+1

**Comment by cheapsteak** [comment]
is this slated for release 1.1.0 (a "will-implement"?)

btw +1

**Comment by yyx990803** [comment]
yeah it's in the milestone.

**Comment by maingao128** [comment]
+1

**Comment by galenyuan** [comment]
Why not use `v-el` in component?
In my opinion, any item in `v-for` should be separated as a component.

**Comment by fnlctrl** [comment]
FYI this is already shipped in 2.0 with the new `$refs`. Don't know if Evan wants to back port it to 1.x though.
