### ISSUE TITLE
v-show with transition bug……

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#1698]
vue.js version: 1.0.4
template：
    
    <ul class="ul ul-b" v-show="0==1" transition="toggle">
        <li class="li li-b" v-for="sub in menu.subs">                            
            <a href="{{sub.href}}" class="link">{{sub.title}}</a>
        </li>
    </ul>  

    //or just like this:
    <div class="ul ul-b" v-show="0==1" transition="toggle">
        some string
    </div> 

css:

    .ul-b.toggle-transition
        transition all .5s  
        transform scale(1)
        
    .ul-b.toggle-enter,
    .ul-b.toggle-leave
        transform scale(.5)

after first rendered，the dom is not hide，and it‘s html like below：

    <ul class="ul ul-b toggle-transition toggle-leave">

if I make the ul empty like below, that's ok

    <ul class="ul ul-b" v-show="0==1" transition="toggle">
    </ul>

**Comment by ccqgithub** [comment]
another bug：

if I make below：

    <ul class="ul ul-b" v-show="!menu.href && menu._open">
        <li class="li li-b" v-for="sub in menu.subs" v-show="!menu.href && menu._open" transition="toggle">
            <a href="{{sub.href}}" class="link">{{sub.title}}</a>
        </li>
    </ul>

has a error：`TypeError: this.op is not a function`
in code js:

    p.leaveDone = function () {
	  this.left = true
	  this.cancel = this.pendingJsCb = null
	  this.op()  // here
	  removeClass(this.el, this.leaveClass)
	  this.callHook('afterLeave')
	  if (this.cb) this.cb()
	  this.op = null
	}

**Comment by yyx990803** [comment]
Can't reproduce. You will need to make an actual reproduction.

**Comment by AlexandreBonaventure** [comment]
I have the error `TypeError: this.op is not a function` also in 1.0.migration. I will try to make a repro.

**Comment by ccqgithub** [comment]
I will try to make a repro later.

**Comment by ccqgithub** [comment]
@yyx990803 the demo for the first bug in jsfiddle:

http://jsfiddle.net/5b6x9rax/

**Comment by ccqgithub** [comment]
@AlexandreBonaventure   TypeError: this.op is not a function, 

I find my reason(i use variable start with _):

> Properties that start with _ or $ will not be proxied

and you ?

**Comment by yyx990803** [comment]
You repro has errors... your `.toggle-leave` has extra selectors. Fixed and it is working properly without errors: http://jsfiddle.net/yyx990803/5b6x9rax/1/

**Comment by ccqgithub** [comment]
@yyx990803 
先前的例子有问题，bug还存在，真实的情况是这样的（在list中有问题）：
http://jsfiddle.net/qdexaaL1/

**Comment by ccqgithub** [comment]
@yyx990803 http://jsfiddle.net/bfwuLskL/
这个bug重现了，只有在Firefox中有问题，chrome 没问题，看看是不是兼容性问题

**Comment by ccqgithub** [comment]
@yyx990803 
如果在后面重设一下show的值，才会好

    vm.show = true;
    vm.$nextTick(function() {
	vm.show = false;
    });

**Comment by szkrd** [comment]
It still happens if I remove the parent component with a v-if and the child inside is still transitioning. I understand that this is not a "nice" situation and it shouldn't happen, but technically the dom node is not around anymore, so an `if (!this.op) return;` (in leaveDone) would help. What's your opinion?

**Comment by sirzxj** [comment]
I come accross this problem today 
I found *leaveDone* function execute twice while this.op is null at the end of first time lead this problem;

```
p$1.leaveDone = function () {
  this.left = true;
  this.cancel = this.pendingJsCb = null;
  this.op();
  removeClass(this.el, this.leaveClass);
  this.callHook('afterLeave');
  if (this.cb) this.cb();
  this.op = null;
};
```

**Comment by nigelvon** [comment]
最近使用 vue-router 的时候会发生这个错误。场景是当一个组件的 on-hide 事件触发的时候运行 `this.$router.go('xxx')` 就会报错。

**Comment by PurpleDandelion** [comment]
vue 版本1.0.28；使用iview 1的插件Tag标签，并更新数据（与Tag关联的数据）的时候遇到此问题。不过暂时替代解决，重新定义一个变量，值和Tag上关联的数据一致，只修改重新定义的变量。到现在这个时间了，还在用vue1 的，我只是来记录一下
