### ISSUE TITLE
How to filterBy  just equal instead of in

### ISSUE THREAD

**Issue by awesomes-cn** [vuejs/vue#1707]
```
<div v-for="user in users | filterBy 'Jack' in 'name'">
```

I just want to filter the user which  `name == 'Jack'`,but the above code will make `"JackHello"` matched.

So how should I do ?

If the filter should be 
```
<div v-for="user in users | filterBy 'Jack' is 'name'">
```

**Comment by yyx990803** [comment]
Please open questions at the forum instead. Issues are for bugs and features.

For your use case, just use a custom filter.
