### ISSUE TITLE
Issue with class and v-bind:class binding on IE9

### ISSUE THREAD

**Issue by kzima** [vuejs/vue#1712]
On IE9, this does not render properly:
```<div v-bind:class="{ bold : true }" class="{{someClass}}">Should be bold and green, but it is only bold</div>```

http://jsfiddle.net/kzima/nonL6gp9/1/

**Comment by yyx990803** [comment]
It is a bad idea to mix these two styles. In addition to this, the reason IE9 gets confused is because it treats `v-bind:class` and `class` as the same attribute... this is pretty nasty to work around for, so just use one style or the other. I have added a warning for such usage.
