### ISSUE TITLE
Object in array lost $set method in 1.0?

### ISSUE THREAD

**Issue by NemoAlex** [vuejs/vue#1714]
Hi,
Try this code in Vue 0.12 and Vue 1.0:

```
var $vm = new Vue({
  data: {
    a: [{}]
  }
})
```

In 1.0, `$vm.a[0].$set` is `undefined`.

Any ideas?

**Comment by yyx990803** [comment]
Please read at the 1.0 upgrade notes carefully. Object prototypes are no longer extended. Use http://vuejs.org/api/#Vue-set instead.
