### ISSUE TITLE
The new data-binding syntax doesn't render component method results

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#1715]
Is this intentional?

**Comment by OEvgeny** [comment]
Can you provide a reproduction?

**Comment by yyx990803** [comment]
Please be more specific... likely your method is returning `null` or `undefined`, which will be rendered as empty.

**Comment by thelinuxlich** [comment]
It's this, `foo` used to evaluate in older versions http://jsfiddle.net/oe7axeab/49/

**Comment by yyx990803** [comment]
Well this was never intended to work... most likely just a coincidence that it worked.
