### ISSUE TITLE
delete data object attribute

### ISSUE THREAD

**Issue by xusimin1008** [vuejs/vue#1716]
hello, I want to delete object attribute in Vue's data, for exmaple,
```
data = {
    msg: 'hello',
    attris: {
        a: 1,
        b: 2,
    }
}
```
I want to delete data.attris.b,
but I see that ``` vm.$delete( key ) ``` only can delete the root attribute of data,
what can I do?

**Comment by OEvgeny** [comment]
There are `Vue.set` and `Vue.delete` to handle this.
