### ISSUE TITLE
<template v-for> doesn't seem to work in IE/Edge

### ISSUE THREAD

**Issue by zzzxtreme** [vuejs/vue#1725]
hi guys, I have this code

			<template v-for="item in eventlocation.list">
				<option value="{{item[1]}}">{{item[0]}}</option>
			</template>

works in Chrome, FF. but not IE10 and Edge. Is this a known issue or it's just me doing something wrong ?

Thanks in advance

**Comment by OEvgeny** [comment]
I think it can be caused by template tag.. Just try this:
```html
<option v-for="item in eventlocation.list" :value="item[1]" v-text="item[0]"></option>
```

**Comment by yyx990803** [comment]
Most likely IE enforces what elements are allowed inside `<select>`, similar to `<table>`. Just use the non-template version.

**Comment by Chris-May** [comment]
Thanks for posting this. Saved me a ton of time!
