### ISSUE TITLE
Programmatic slot access API

### ISSUE THREAD

**Issue by noirbizarre** [vuejs/vue#1726]
Is there a proper way for a component to access its transcluded children ?

This will allow to:
- change the component behavior  depending on transcluded content presence
- use child component data, properties or method from parent

**Comment by yyx990803** [comment]
Transcluded children are also in the component's `$children` array.

For checking presence - there will probably be a `$hasSlot` and a `$childAtSlot` method in the future - for now you have to do something like `this.$el.querySelector('[slot="xxx"]')`.

**Comment by noirbizarre** [comment]
Thanks for the tip !

**Comment by prog-rajkamal** [comment]
`$hasSlot and `$childAtSlot` gives impression that there is atmost one component at a slot. while in reality multiple components can be targeted at a single slot.

I think it is better to change the name to  `$childrenAtSlot[]` with `$childrenAtSlot.length` to determine count. 
And supply `$firstChildAtSlot` for most common use case.

**Comment by fullfs** [comment]
@yyx990803 I'd agree with @prog-rajkamal on his last point. Those methods does not look like nice way to solve the problem. I'd like to see some more universal way of content-slot-component communication.

**Comment by yyx990803** [comment]
This is addressed in 2.0 - however it is very difficult to backport to 1.x with a similar API, so unfortunately this is not going to land in 1.x.

**Comment by Nanobrainiac** [comment]
> This is addressed in 2.0 - however it is very difficult to backport to 1.x with a similar API, so unfortunately this is not going to land in 1.x.

How is it addressed? Reply is too vague. This thread needs continuation.

**Comment by mbrodala** [comment]
@yyx990803 Can you add a link or similar here so people are able to find the solution?

**Comment by sylvainpolletvillard** [comment]
Solution for v2.x :
You can access slots content through the [$slots API](https://vuejs.org/v2/api/#vm-slots).

The default slots are accessible through `vm.$slots.default`, while the named slots are accessible through `vm.$slots.yourSlotName`. These return VNodes, you can find information about [VNode interface here](https://vuejs.org/v2/api/#VNode-Interface)

For exemple, to get the text content of the default slot, use :
```
computed: {
   textContent(){
      return this.$slots.default[0].text
   }
}
```

**Comment by mryellow** [comment]
`this.$slots.default[0].text` This doesn't seem to be documented along with other slot uses.

https://vuejs.org/guide/components/slots.html

**Comment by mryellow** [comment]
In fact it doesn't seem like `Vnode` is documented.
