### ISSUE TITLE
[1.0.6] Boolean props shorthand stopped working

### ISSUE THREAD

**Issue by mzgajner** [vuejs/vue#1727]
I have a boolean prop on my component. In 1.0.3, simply including it like this resulted in it being true:
`<my-component some-prop></my-component>`
In 1.0.6, this no longer works. I get no error, the property value is just false. I now have to explicitly pass it in order for it to work:
`<my-component :some-prop="true"></my-component>`.

I went through the changelog but I haven't noticed anything about this being removed. Is it a bug?

**Comment by lebedenko** [comment]
I have the same issue in 1.0.6
