### ISSUE TITLE
v-bind:src does not work

### ISSUE THREAD

**Issue by alioygur** [vuejs/vue#1731]
when I use the v-bind:src like below

    <img v-bind:src="image_url" alt="">

i getting this error

    Uncaught Error: Cannot find module "./image"

not: I am using vue 1.0.6

**Comment by yyx990803** [comment]
I assume you are using `vue-loader`, please read this section: https://github.com/vuejs/vue-loader#asset-url-handling

**Comment by alioygur** [comment]
@yyx990803 no I not using vue-loader.

there are my dependencies list

```
  "dependencies": {
    "dateformat-light": "~1",
    "expose-loader": "~0",
    "highlight.js": "~8",
    "html-loader": "~0",
    "js-cookie": "~2",
    "json-loader": "~0",
    "marked": "~0",
    "path": "~0",
    "style-loader": "~0",
    "vue": "~1.0",
    "vue-resource": "~0.1",
    "vue-router": "~0.7",
    "webpack": "~1"
  }
```

**Comment by yyx990803** [comment]
That still applies for `html-loader`: https://github.com/webpack/html-loader

**Comment by alioygur** [comment]
@yyx990803 so how can i fix it ? I have read the doc but I confused.

**Comment by alioygur** [comment]
okey, I got it.

I have to use vue-html-loader instead of html-loader

**Comment by yyx990803** [comment]
Not only that.. you need to install `file-loader` and use it to load the image extensions in your webpack config.
