### ISSUE TITLE
node_module main script

### ISSUE THREAD

**Issue by greennyreborn** [vuejs/vue#1763]
I install Vue with npm and use webpack to pack.
But I find webpack will compile Vue from source and if you use sourcemap, source code of vue will also show up in the source tag in Chrome's dev tool which makes it a little bit confusing.
 because in the package.json:
```
"main": "src/vue.js"
```

I think the main script should be `dist/vue.js` or `dist/vue.min.js` for npm-publish version

**Comment by yyx990803** [comment]
Isn't it more helpful to get the actual source when debugging? What's
confusing about it? The dist file is not meant to be read, the source is.

**Comment by greennyreborn** [comment]
@yyx990803 Yeah, but I don't need to debug `Vue`, I'm just debuging my own code. 
For examble, I'm trying to debug index.js, but when I type `index` in the filter of source tag:
![img](http://i.imgur.com/GqKgm6z.png)

**Comment by yyx990803** [comment]
It does show the full path though, so you can just ignore all the Vue files?

The dist file is already packed with Webpack and is inefficient if Webpack
packs it again.
