### ISSUE TITLE
$watch doesn't detect the change in during a loop except when loop ends

### ISSUE THREAD

**Issue by greennyreborn** [vuejs/vue#1764]
```js
var vm = new Vue({
  el: '#test',
  data: {
      a: 1
  },
  methods: {

  }
})

vm.$watch('a', function(newVal, oldVal) {
  console.dir(newVal)
})

for (var i = 0, len = 2; i < len; i++) {
  vm.a += 1;
}

```

In this case, when `a` changes to 2, nothing happened. Just `alert 3` in the end

[Repro link](http://jsfiddle.net/Greenny/c6yxsjme/2/)

**Comment by Mat-Moo** [comment]
That's correct behavior, please read http://vuejs.org/guide/reactivity.html

**Comment by greennyreborn** [comment]
@Mat-Moo Thanks for the explanation!
