### ISSUE TITLE
Programatic registration of local dependencies?

### ISSUE THREAD

**Issue by cheapsteak** [vuejs/vue#1766]
Is there a way to register local dependencies in one of the lifecycle hooks (e.g. in `beforeCompile`)?

That would let me pass dependencies down via props and use it in the child

parent:
```vue
<child-component custom-component-dependency="$options.components.componentA" />
```

child:
```vue
<template>
  custom component that was passed in:  
  <custom-component/>
</template>
<script>
  export default {
    props: {
      customComponentDependency: Function
    },
    created: {
      // do something to register <custom-component> using the passed in prop
    }
  };
</script>
```

**Comment by yyx990803** [comment]
Yes, just do `this.$options.components.xxx = this.customComponentDependency` should work.

**Comment by yyx990803** [comment]
One small thing to watch out for is that component linkers are cached after first compilation, so if the first occurrence of your child component failed to locate the component at compile time, it will affect all later instances. This can be circumvented by making the component prop required.

**Comment by cheapsteak** [comment]
Thanks! That works perfectly :)
I'll close the ticket
