### ISSUE TITLE
集中报告几个问题 (1.0.7)

### ISSUE THREAD

**Issue by rendongsc** [vuejs/vue#1767]
1、1.0.3我提过的  https://github.com/vuejs/vue/issues/1656
     代码可以正常工作了，就是还在输出警告信息：
    [Vue warn]: v-on:click="onColumnClick(column)" expects a function value, got undefined

2、#1727 Boolean props not working properly，修复了吗？  
     html模板： pager="false" 或者  pager=false
      pager属性始终解析为true，只有把pager干掉才OK！

3、Number属性解析问题。  
     html模板：   duration=100 或者 duration=”100“      
      都不能正确解析。
  [Vue warn]: Invalid prop: type check failed for duration="100". Expected Number, got String.

**Comment by yyx990803** [comment]
1. 给重现。

2 & 3: 请仔细阅读文档。`pager="false"` 和 `duration="100"` 传递的都是**字符串**。只有 `:pager="false"` 和 `:duration="100"` 传递的才是 **JavaScript 表达式**。

**Comment by rendongsc** [comment]
1、重现代码请见#1656 回复内容，直接在给的grid案例上加上几行代码就可以重现。
2、2&3既然是你给的回复，那么就是官方的了。
     文档又仔细看了一遍，对于非字符串类型并没有强调说明必须是表达式。
     对于bool 、数值等可以像字符串一样设置属性值，是不是更简洁些？
