### ISSUE TITLE
Registering component doesn't work for recursive rendering

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue#1769]
Hey. 

I faced that problem the other day where I updated Vue version from some beta release to rc release and the code that I have just broke.

I had a code which takes a folders tree and renders it. I have a `foldersTree` manager component which registers locally a `folder` component. 

Now the `foldersTree` is using the `folder` component in its template with a `v-for` for the "root" folders.

Each `folder` component checks to see if it has some children and if so it renders itself again - using the `folder` component along with a `v-for` for its children and so on. Basically it should render a nice folder tree.

This worked perfectly on the Beta releases but as I upgraded to the rc releases I got a weird error which is true for the current release as-well. The "root" folders are being rendered properly but when it tries to render the children folder it throws an error and says that the `folder` component isn't registered.

The solution I found for this issue is to register the `folder` component globally in the `beforeCompile` method of `foldersTree` but it's weird.

Sorry it took my thing long to report this if this is indeed a bug and not intentional.

**Comment by yyx990803** [comment]
Just add a name option. See the docs for the name option.

**Comment by kfirba** [comment]
@yyx990803 oh. Haven't seen that before. Guess it's new. Thanks for to the quick reply tho.
