### ISSUE TITLE
object数据类型的删除 无法更新视图

### ISSUE THREAD

**Issue by senyawang** [vuejs/vue#1773]
demo:    http://codepen.io/senyawang/pen/NGLdQp

items: {
          "A001":{"type": "按钮1", "num": 10},
          "A002":{"type": "按钮2", "num": 10}
  }
对于上面的数据类型， 无论是 delete obj.name  还是Vue.delete(obj, name) 都无法更新视图，请问该如何操作

**Comment by yyx990803** [comment]
你用的是 0.12，删除用的是 `obj.$delete(key)`。`Vue.delete` 是 1.0 才有的。看报错啊...

**Comment by senyawang** [comment]
哦。。好的。谢谢了

**Comment by flftfqwxf** [comment]
$delete只能删除顶级属性无法删除子属性，如果我要删除 子属性，又该怎么写？？
items: {
item:{
"A001":{"type": "按钮1", "num": 10},
"A002":{"type": "按钮2", "num": 10}
}

}
