### ISSUE TITLE
Add v-model 'options' parameter back for select form items.

### ISSUE THREAD

**Issue by zwagoth** [vuejs/vue#1777]
I have an existing project that is using Vue 0.12.16 and recently migrated the code over to Vue 1.0.7.

The project went from a startup time of 0.7s to 6.8s with the change of `<select v-model="item.value" options="dropdownChoices"></select>` to `<select v-model="item.value"><option v-for="opt in dropdownChoices" value="{{* opt.value }}">{{* opt.text }}</option></select>`

The cause of the dramatic increase in time comes from the additional fragments and directives that are created by the removal of the options= parameter.

The application in question contains a very large list of items that each have an associated select dropdown. The dropdown choices are identical for list each item, but the items are often updated based on another area of the application.

I attempted to create a new directive that created the option items the way the old item had, but ran into the problem of being unable to signal to v-model that it needed to update which item was selected, and I did not have access to the value that it was watching.

Please add the v-model select 'options' parameter back, as it is a very large performance gain when working with a large number of items.

Vue 1.0.7 method: https://jsfiddle.net/mc33346o/
Vue 0.12.16 method: https://jsfiddle.net/s7pwqkjn/

**Comment by yyx990803** [comment]
Hmm, didn't expect a use case like this... but your custom directive that duplicates the old behavior can access the `v-model` directive bound to the same element as `this.el.__v_model`.

The custom directive can be as simple as:

``` js
Vue.directive('options', {
  update: function (value) {
    this.el.innerHTML = value.map(function (o) {
      return '<option value="' + o.value + '">' + o.text + '</option>'
    })
    if (this.el.__v_model) {
      this.el.__v_model.forceUpdate()
    }
  }
})
```

Let me know if this helps..

**Comment by zwagoth** [comment]
I was not aware of the ability to access alternate directives through the element. This proves to trivialize what I was previously trying and more or less solves my problem. I had to use the method from the previous system where it removes and then builds a new copy of the options and option groups to support IE9.

I can also understand why this wouldn't be an expected use case. There was some potentially questionable UI choices taking place.

Thanks for the help.
