### ISSUE TITLE
v-ref inside component that appears multiple times

### ISSUE THREAD

**Issue by andoband** [vuejs/vue#1779]
I see the following warning when I have multiple instances of a component on a page:

`v-ref:my-inner must be used on a child component. Found on <div>.`

See repro: http://jsfiddle.net/5sH6A/198/

The warning started appearing with v1.0.5.  I'm not having any issues beyond seeing the warning.

**Comment by fenivana** [comment]
+1. I encountered this issue when switching components that has child components.

http://jsfiddle.net/1g80pzLn/
