### ISSUE TITLE
a problem about table components

### ISSUE THREAD

**Issue by Mrluobo** [vuejs/vue#1780]
I write a component called vuetable:
```
<td v-for="item in datalist">{{item}}</td>
```

I use the component like this:
```
<table class="table table-bordered table-hover"> 
    <thead>
         <tr>
             <vuetable :datalist="datalist"></vuetable>
         </tr> 
    </thead> 
</table>
```
but  after rendered , the DOM become like this:
```
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<table> 
    <thead>
         <tr>
         </tr> 
    </thead> 
</table>
```
why the `<td>` rendered out of the `<table>`tag?

**Comment by simplesmiler** [comment]
This is limitation of HTML, `<tr>` only permits `<td>` and `<th>` inside itself, so `<vuetable>` gets cut off by the browser before Vue can reach it. Either enclose the whole table in your component or use the `is` syntax:
``` html
<tr>
  <td is="vuetable" :datalist="datalist"></td>
</tr> 
```

**Comment by CodeOfDavid** [comment]
Thank you, this helped!
