### ISSUE TITLE
The 'afterEnter' hook dose not 'wait for the transition to finish'

### ISSUE THREAD

**Issue by zcoding** [vuejs/vue#1781]
`afterEnter`钩子并没有等到transition结束才调用，而是在transition刚触发后就调用了？

我以为我写错了，然而我看了[官网的例子](http://vuejs.org/guide/transitions.html#Example)，afterEnter也是在transition结束之前就调用了。但是afterLeave确实在transition结束之后才调用。

为什么afterEnter没有像afterLeave那样，在transition结束之后才调用呢？这对我写过渡效果的组件影响很大，因为很多时候需要在过渡结束的时候写回调，而过渡的时间又是在CSS里面控制。

`vue`的版本刚升级到1.0.7，chrome和firefox都试过了。

**Comment by tanrenjie** [comment]
你好，我现在也被这个问题困扰了，能告知我一下最后的解决方案吗，谢谢。

**Comment by joenil** [comment]
这个问题现在还存在，我用的是2.3.4的版本，在用transition-group的时候。

**Comment by joenil** [comment]
@tanrenjie @yyx990803 我发现是因为当前视图中依赖的数据在transition完成之前发生了变化，触发了transition提前结束，我在线写了一个重现的例子https://jsfiddle.net/ahcL844p/
