### ISSUE TITLE
I need vm.$data.obj.$set(key, value) and obj.$get()

### ISSUE THREAD

**Issue by thkdog** [vuejs/vue#1782]
The older version of vue supports this style, which makes dynamic add property easy.
And also $get() is required, sometimes we need a vm object to become a plain json object to set to a existing vm key, or the whole vm data will be passed.
sample: 
```
vm.$data.obj1 = { test: 1 };
vm.$data.obj2 = obj1; // here is the problem
vm.$data.obj2 = JSON.parse(JSON.stringify(obj1)) // that's really what I want
```

**Comment by OEvgeny** [comment]
Please read docs: [Vue.set()](http://vuejs.org/api/#Vue-set), [instance methods](http://vuejs.org/api/#Instance_Methods_\/_Data).

**Comment by thkdog** [comment]
I have read docs, but it's not convenient, see blow
v-for template:
```
 <div @click="onItemClick(item)" />
```
code
```
onItemClick (item) {
    vm.$set(??item??, xxx) // I don't know the keypath infact, I prefer item.$set or $get could work
}
```
and how can I get the plain json object?

**Comment by thkdog** [comment]
currently, I use
```
var plain = JSON.parse(JSON.stringify(vmObj));
```
to get the POJO

**Comment by OEvgeny** [comment]
Use `Vue.set` for objects:
```js
onItemClick (item) {
    vm.$set(item, xxx) // You don't need to know the keypath.
}
```

**Comment by OEvgeny** [comment]
It is ok to use JSON methods to get plain objects. There is no special methods for this case.
Please post questions to the forum next time.

**Comment by thkdog** [comment]
Thanks for the response
I just tried this, but it gets error.

this referers to vm, it's in a instance method scope
```
this.$set(this.carInfo, {"test": 1})
vue.min.js:7 Uncaught TypeError: t.trim is not a function
    at Object.e.parse (http://localhost:5389/webapp/ship/webresource/common/vue.min.js:7:14765)
    at n.e.$set (http://localhost:5389/webapp/ship/webresource/common/vue.min.js:8:6295)
    at n.eval (eval at evaluate (unknown source), <anonymous>:1:6)
    at Object.InjectedScript._evaluateOn (<anonymous>:904:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:963:21)
    at n.BasePageView.extend.render.Vue.methods.onCarSwitchClick (http://localhost:5389/webapp/ship/webresource/views/ship/booking.js:77:25)
    at n.e.bind [as onCarSwitchClick] (http://localhost:5389/webapp/ship/webresource/common/vue.min.js:6:2307)
    at n.eval (eval at h (http://localhost:5389/webapp/ship/webresource/common/vue.min.js:7:13741), <anonymous>:3:15)
    at r._checkStatement.n (http://localhost:5389/webapp/ship/webresource/common/vue.min.js:8:4518)
```

**Comment by thkdog** [comment]
BTW, I'm using the latest vue 1.0.7 (just upgrade :))

**Comment by OEvgeny** [comment]
`vm.$set` expects path string as the first argument...

**Comment by yyx990803** [comment]
It should be `this.$set('carInfo', ...)`

If you set an object by reference then it obviously should be the same object. If you want to clone it, then explicitly clone it... there's no reason for Vue to clone an object on set.

**Comment by thkdog** [comment]
You dont get me... item is the one item of a v-for repeat, i set an v-on:click event, and there is a handler onItemClick with a argument 'item', and now I want to set a new property on this item, it would be weird to resolve the key path from this situation.

发自我的 iPhone

**Comment by yyx990803** [comment]
Then you should use Vue.set, not this.$set. Hasn't this been mentioned
above?

**Comment by thkdog** [comment]
Yes, you are right... I misunderstanded before... THX !~

**Comment by michaelsogos** [comment]
A better and performant way to get plain JSON from vue.$data is the following code.

```javascript
function deepClone(obj){
  var result = {};
  var props = Object.keys(obj);
  props.forEach(function(propName) {  
      var clonedValue = obj[propName];
      if(typeof clonedValue === 'object'){
            clonedValue = deepClone(obj[propName]); 
      }        
      result[propName] = clonedValue;
  });
  return result;
}
```

Click this [Test](https://jsfiddle.net/michaelsogos/w6m1x5ve/) to get performance better result than JSON.parse(JSON.stringify(...))
