### ISSUE TITLE
v-model , behavior not persistent

### ISSUE THREAD

**Issue by magicdawn** [vuejs/vue#1783]
see https://jsfiddle.net/okv0rgrk/243/
### senario 1
1. wait 1000ms for fake Ajax
2. click `all` , to select All, click `all` again to unselect all
everything looks fine.

### senario 2

*run again to refresh the page, just press `run` button, important!*

1. wait 1000ms for fake Ajax
2. click `1` first, to select 1
3. then click `all` select all, then click `all` again to unselect all
4. seems the `1` is outof control. the selectAll / unselectAll is broken.

**Comment by magicdawn** [comment]
In chinese
就是一开始不点123, all全选是好的, 然后再run一下,进入场景2, 先点1, 再去全选/反选, 1就out of control了

**Comment by magicdawn** [comment]
先选择 `1` 的话, $watch 也有问题 https://jsfiddle.net/okv0rgrk/244/

**Comment by zcoding** [comment]
你的checkbox没有value，建议直接控制checked属性
`<input type="checkbox" :checked="checked[item.id]" />`

**Comment by magicdawn** [comment]
@zcoding `:checked` = `v-bind:checked="checked[item.id]"` 这只是单向绑定吧

**Comment by yyx990803** [comment]
这里确实有一个 edge case，主要是因为 `checked[item.id]` 这样的复合动态路径，如果初始值不存在，虽然能设置值，但是不会转化为 reactive 的属性。能避免用 `$set` 还是尽量避免。

更好的做法是利用 1.0 支持 checkbox 绑定到 Array 的写法：https://jsfiddle.net/yyx990803/okv0rgrk/249/

**Comment by magicdawn** [comment]
好的.

**Comment by yyx990803** [comment]
如果觉得 Array 写法不方便，那就做好数据初始化（见 line 30) https://jsfiddle.net/yyx990803/okv0rgrk/264/

**Comment by g8up** [comment]
https://jsfiddle.net/yyx990803/okv0rgrk/249/ 中有个问题：勾选 All ，再取消勾选 1，All 还是勾选的状态。

感觉这个实现比较好：
https://jsfiddle.net/Simga/b6nhh3t9/3/
