### ISSUE TITLE
Array.$remove callback?

### ISSUE THREAD

**Issue by dalanmiller** [vuejs/vue#1788]
I see [here in the documentation that $remove](http://vuejs.org/api/#vm-remove) can take a callback as a second parameter which will be called once the element has been removed from the DOM and all transitions have occurred. 

Am I understanding this correctly?

**Comment by yyx990803** [comment]
That is `vm.$remove()`, not `Array.prototype.$remove()`. The former removes the Vue instance and accepts callback, the latter is synchronous.

**Comment by simaodeveloper** [comment]
Okay, but where is Array.prototype.$remove() in documentation?

**Comment by thelinuxlich** [comment]
http://vuejs.org/guide/list.html#Caveats
