### ISSUE TITLE
Props with router-view broken?

### ISSUE THREAD

**Issue by Nublust** [vuejs/vue#1789]
I'm passing a prop to my router-view like so:
```
<router-view :user="Hello!"></router-view>
```
But the console is showing:
```
main.js:13842 [Vue warn]: Attribute ":user" is ignored on component <router-view> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment_Instance
```
The link it gives me seems to indicate this is possible, unless I'm not understanding?

**Comment by yyx990803** [comment]
This is likely because on of your router view components does not have the `user` prop. If that's not the case, please reopen with a reproduction.

**Comment by Nublust** [comment]
Sorry, you're correct. I had another router-view sat between them and didn't realise.
