### ISSUE TITLE
v-model 导致中文拼音输入时带拼音

### ISSUE THREAD

**Issue by likezero** [vuejs/vue#1790]
如下使用，在Yosemite 10.10.5系统，搜狗输入法时 ，输入中文，会自动带入中文的拼音
 ```html
<input v-model="taskName" value="{{taskName}}"  type="text" class="form-control" >
```
```html
  wo'lai我来ce'shi测试a啊a啊
```
最后发现使用debounce 降低同步速率，可以解决问题。
```html
 <input  v-model="taskName" value="{{taskName}}" debounce="10" type="text" class="form-control" >
````

期待在v-model内部解决~

**Comment by yyx990803** [comment]
因为你同时把 `value` 也绑定了。去掉 value 的绑定即可（本来就不需要）

**Comment by singhello** [comment]
<el-form-item prop="account" >
        <el-input type="text" v-model="ruleForm2.account" auto-complete="off" placeholder="账号"></el-input>
      </el-form-item>
就是正常的数据绑定，对于低版本的chrome浏览器，仍然会带出拼音，例如输入‘你好’，输入框会显示‘nihao你好’，不知道什么原因

**Comment by singhello** [comment]
`<el-form-item prop="account">
        <el-input type="text" v-model="ruleForm.account" auto-complete="off" placeholder="账号"></el-input>
      </el-form-item>`
就是正常的数据绑定，对于低版本的chrome浏览器，仍然会带出拼音，例如输入‘你好’，输入框会显示‘nihao你好’，不知道什么原因

**Comment by singhello** [comment]
> 因为你同时把 `value` 也绑定了。去掉 value 的绑定即可（本来就不需要）
`<el-form-item prop="account">
 <el-input type="text" v-model="ruleForm.account" auto-complete="off" placeholder="账号"></el-input> 
</el-form-item>`
就是正常的数据绑定，对于低版本的chrome浏览器，仍然会带出拼音，例如输入‘你好’，输入框会显示‘nihao你好’，不知道什么原因
