### ISSUE TITLE
v-model on textareas inside v-for causes textareas to lose focus on change

### ISSUE THREAD

**Issue by rokkamokka** [vuejs/vue#1791]
Below is a minimal working example of the problem. Whenever you type anything inside the textareas, the focus is immediately lost. It looks like the textareas are demolished and recreated on change.
http://jsfiddle.net/d1rppdfc/

I also found an old, closed bug that looks related: https://github.com/vuejs/vue/issues/689

**Comment by pocke** [comment]
I think you can use `track-by`. #1730

https://jsfiddle.net/d1rppdfc/1/

I encountered same problem today. :cat:

**Comment by rokkamokka** [comment]
An unusual quirk. Your suggested solution seems to work any way, so thanks! :)
