### ISSUE TITLE
遇到一个v-model的bug

### ISSUE THREAD

**Issue by GuoYongfeng** [vuejs/vue#1795]
我在页面的一个元素上绑定了v-model，运行后我修改了v-moel的值，但是始终没有生效，在浏览器中渲染的v-model一直是最初设置的那个值，无法改变。求解

**Comment by yyx990803** [comment]
报 bug 要给重现啊同学... 你连一行代码都没有怎么帮你...

**Comment by GuoYongfeng** [comment]
@yyx990803 说的是，这是个很low的习惯，后来检查后是我代码逻辑的问题，thx。
