### ISSUE TITLE
Can not use a multi-byte character set for data binding

### ISSUE THREAD

**Issue by nanila** [vuejs/vue#1796]
```javascript
var base = new Vue({
    el: '#base',
    template: html,
    data: {
      漢字: {
        太郎君: '1000',
        花子: '4000'
      }
    }
});
```
```html
<div>{{漢字.太郎君}}</div>
<div>{{漢字.花子}}</div>
```

#### Result in Chrome
[Vue warn]: Error when evaluating expression "漢字.太郎君". 
debug.js:33 ReferenceError: 漢字 is not defined
[Vue warn]: Error when evaluating expression "漢字.花子". 
debug.js:33 ReferenceError: 漢字 is not defined

**Comment by yyx990803** [comment]
Unfortunately, Vue's expression parser only support alphanumeric identifiers. Avoid using unicode chars as identifiers.
