### ISSUE TITLE
v-model inside v-for doesn't set value when property name is dynamic

### ISSUE THREAD

**Issue by inca** [vuejs/vue#1797]
As explained in [this forum post](http://forum.vuejs.org/topic/507/v-model-on-missing-properties) and demonstrated by [this fiddle](http://jsfiddle.net/eLexpfqu/2/), if you have something like `v-model="obj['prefix-' + key]"`, you occasionally get this:

```
Cannot read property "get" of undefined
```

or that:

```
[Vue warn]: Invalid setter function body:  'prefix-'+scope.key
```

**Comment by yyx990803** [comment]
Yes, this is a known issue. But in general, the advice is **never rely on v-model to create a non-existent property for you**. Follow the best practice and properly initialize your data.
