### ISSUE TITLE
Prop validation, mix of array and object hash syntax

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#1798]
After searching I couldn't find if this was already suggested and discounted, but at the moment when we can specify component props with a simple array of strings or complex object hash.

I think I might be useful if we could mix the two:

    props: [
        'propA',
        'propB',
        {
            name: 'propC',
            type: Number,
            default: 100
        },
        'propD'
    ]

I often find I have props in an array of strings, and at a later stage need to add a prop which has validation. Meaning I have to concert the array of strings to a hash.

**Comment by shuaibird** [comment]
Is this feature supported in v2?
I've tried it and got the warning: `props must be strings when using array syntax.`

**Comment by thomasaull** [comment]
I'm getting the same error, when putting the props-example from the test (https://github.com/vuejs/vue/commit/8ed14c8e4b0c896c59c92455b2b7aa95214382c9#diff-2092e089df2ae66b53f34b1d728f3acc) in my component:

`props: [
  'b',
  {
    name: 'c',
                type: Number
              },
              {
                name: 'd',
                required: true
              }
],`

**Comment by vibrantBits** [comment]
Is there an accepted practice/answer to this issue?

**Comment by penance316** [comment]
A bit late but was this ever sorted? I just noticed I am having the same issues as mentioned. Mixing prop types as shown in the tests is throwing an error.
Thanks
