### ISSUE TITLE
Vue Element and Masonry Plugin

### ISSUE THREAD

**Issue by socieboy** [vuejs/vue#1799]
Hey I try to make a grid with the Masonry plguin and it's works perfect until I load more data to my json object of posts... seems like my news posts doesn't get the plugin.

```
template: require('./posts.template.html'),

    data: function(){
        return {
            currentPage: 1,
            posts: ''
        }
    },

    ready: function(){
        this.loadPosts();
    },

    methods: {
        loadPosts: function(){
            this.$http.get('/', {'page': this.currentPage}, function(response){
                this.$set('posts', response.data)
                this.currentPage++;
            }.bind(this));
        },
    }
```
And what I get on my HTML.. The posts that I load in the begin with my PHP code get the plugin but the others that are loaded by the post data doesn't
```
<div class="post__container" style="position: relative; height: 200px;">
    <div class="post__box" style="position: absolute; left: 0px; top: 0px;"></div> 
    <div class="post__box" style="position: absolute; left: 380px; top: 0px;"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
    <div class="post__box"></div>
</div>
```

**Comment by yyx990803** [comment]
You need to notify Masonry to trigger a reflow after new items are added.

After you set your data, use `Vue.nextTick()` to wait for the DOM update, then use whatever method from Masonry's API to force it re-calculate the layout.

The issues are for Vue-specific bugs and feature discussions, please post questions like this to the forum in the future.

**Comment by socieboy** [comment]
Ok!

**Comment by shershen08** [comment]
I've wrote one simple masonry vue 2.x directive recently - https://github.com/shershen08/vue-masonry hope it may be helpfull
