### ISSUE TITLE
Converted single quotes issue in string

### ISSUE THREAD

**Issue by fitztrev** [vuejs/vue#1801]
In my application (using Laravel), single quotes are converted to `&#039;`, which seems to cause an issue with the js.

Here's an example of the issue: http://jsfiddle.net/xqq5oos4/

<img width="947" alt="screen shot 2015-11-12 at 9 24 28 pm" src="https://cloud.githubusercontent.com/assets/271432/11137236/ccc3f350-8983-11e5-81e7-e4afd84811e8.png">

**Comment by yyx990803** [comment]
Chars inside attribute string should **not** be escaped. This is expected behavior.
