### ISSUE TITLE
Partials transitions

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#1808]
I can't find any information about dynamic partials transitions but I did saw some comments that suggest it was possible. Are they planned or perhaps discarded?

Anyway it would be useful to have the same transition and transition-mode features as with components.

**Comment by yyx990803** [comment]
The intention of partials is mostly allowing flexibility for composing template parts depending on component props. Dynamic partials are not really meant for runtime swaps (although they can). if you are looking for transition effects on the parts then it indicates you may be better off just make them into components.

**Comment by miljan-aleksic** [comment]
They could be used as if/else statements with transitions for big amounts of texts. If creating components has a performance cost it should be wiser using partials. Anyway, thanks for looking into it.
