### ISSUE TITLE
Problems with v-model and a components $data

### ISSUE THREAD

**Issue by airtonix** [vuejs/vue#1810]
http://codepen.io/anon/pen/qOgWjz

1. `v-on:submit` has no effect (does not trigger specified method)
2. `v-model` doesn't update the components data. (it's updating something though)
3. `:class` doesn't reflect components data changes.

**Comment by airtonix** [comment]
Looks like I've fallen victim to : http://vuejs.org/guide/components.html#Compilation_Scope

**Comment by airtonix** [comment]
in short, I needed to go from this:

```html
	<form is="contact-form" :class="state" v-on:submit.prevent="onSubmit">
	...
	</form>
```

to this:

```html
<div is="contact-form" inline-template>
	<form :class="state" v-on:submit.prevent="onSubmit">
	...
	</form>
</div>
```

**Comment by rpkilby** [comment]
@airtonix Any reason you aren't placing the markup in the component's own template?

```html
<!-- contact-form template -->
<form :class="state" @submit="send">
    <div class="row">
        ...
    </div>
</form>

<!-- parent template -->
<contact-form></contact-form>
<!-- or -->
<form is="contact-form"></form>
```

**Comment by airtonix** [comment]
@rpkilby because, reasons.

https://github.com/vuejs/vue/issues/963#issuecomment-156256104
