### ISSUE TITLE
 uikit html editor not displaying text when data is retrieved dynamically using vue-resource 

### ISSUE THREAD

**Issue by chagamkamalakar** [vuejs/vue#1815]
i'm using trying to use uikit htmleditor , which displays data retrived dynamically
## html code 
```
<textarea data-uk-htmleditor="{markdown:true,mode:'tab'}">{{hotel.description}}</textarea>


<!--  this is working if hard coded  property is used  -->
<textarea data-uk-htmleditor="{markdown:true,mode:'tab'}">{{description}}</textarea>
```
## vuejs **
<pre>
export default {
  data () {
    return {
      is_edit:false,
      description:"This is hardcoded value",
      hotel: {}
    }
  },

  route: {
    data ({ to }) {
      return {
        hotel:this.details(to.params.slug) 
      }
    }
  },

  methods:{
     details (slug) {
        this.$http.get('/admin/hotels/' + slug)
                .success(function(hotel) {
                    this.hotel = hotel;
                }).error(function (error) {
                    alert("error")
                });
     }
  }
</pre>

what i am doing woring?

**Comment by Atinux** [comment]
Hi @chagamkamalakar 

Can you post your issue on the Vue.js forum please? A lot of people of there to help you on that :)
http://forum.vuejs.org/category/5/help

So @yyx990803 can focus only on bug and suggestion for vue.js here.

Thank you

**Comment by chagamkamalakar** [comment]
sorry .. for that ... i sorted out this issue by keeping this code
```
 $.UIkit.htmleditor('#description', { /* options */ });
var editor = $('.CodeMirror')[0].CodeMirror;
editor.setValue(this.hotel.description);
```

**Comment by chagamkamalakar** [comment]
sorry .. for that ... i sorted out this issue by keeping this code
```
 $.UIkit.htmleditor('#description', { /* options */ });
var editor = $('.CodeMirror')[0].CodeMirror;
editor.setValue(this.hotel.description);
```

thanks for your suggestion .. i'll use only vuejs forum

**Comment by Atinux** [comment]
I see @chagamkamalakar, you should post it on vue.js forum anyway because I think there's maybe a better solution for this issue (like using a directive).
