### ISSUE TITLE
Can't listen to events

### ISSUE THREAD

**Issue by levan1993** [vuejs/vue#1822]
Hi,
when I create component I can't listen to events on root element outside of component unless I set replace option to false. Any idea how to reproduce this?

**Comment by yyx990803** [comment]
Please post questions to the forums. Also, it's unlikely that you will get any helpful response without showing any code.

**Comment by levan1993** [comment]
It's not a question it's BUG

**Comment by azamat-sharapov** [comment]
Then provide REPRODUCTION, like it says in [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines).

**Comment by yyx990803** [comment]
Your description is too vague to be considered a bug report.

**Comment by levan1993** [comment]
Menu Template:
~~~
<template>
	<div class="ui-menu" :class="classes">
		<ui-icon-button v-el:btn @click="open" :name="icon"></ui-icon-button>
		<div class="ui-menu-inner" v-el:menu @keydown="handleKeyDown" :class="menuClasses">
			<div class="ui-paper ui-z-depth-1" v-el:paper>
				<div class="ui-menu-inner">
					<slot></slot>
				</div>
			</div>
		</div>
	</div>
</template>
~~~

Menu Item Template: 

~~~
<template>
	<div class="ui-menu-item" :class="classes" >
		<div class="ui-menu-item-inner">
			<ui-icon v-if="icon" :name="icon" :size="48"></ui-icon>
			<div class="ui-menu-item-label"><slot></slot></div>
		</div>
	</div>
</template>
~~~

In component I use it like this:

~~~
<ui-menu>
	<ui-menu-item @click="handleClick" @mouseenter="handleMouseEnter">Item 1</ui-menu-item>
	<ui-menu-item @click="handleClick">Item 2</ui-menu-item>
	<ui-menu-item @click="handleClick">Item 3</ui-menu-item>
</ui-menu>
~~~

But none of events are fired.

**Comment by yyx990803** [comment]
And JavaScript?

**Comment by levan1993** [comment]
Menu Item
~~~

<script>
	export default {
		replace: false,
		props: {
			icon: {
				type: String,
				default: ''
			},
		},
		computed: {
			classes() {
				return {
					'ui-has-icon': this.icon.lenght > 0
				};
			}
		}
	};
</script>

~~~

Menu

~~~

<script>
export default {
	props: {
		icon: {
			type: String,
			default: 'more-vert'
		},
		position: {
			type: String,
			default: 'bottom-left'
		}
	},
	data() {
		return {
			isOpen: false,
		}
	},
	computed: {
		classes() {
			return {
				'ui-is-open': this.isOpen
			}
		},
		menuClasses() {
			let classes = {};
			classes['md-open-' + this.position] = true;

			return classes;
		}
	},
	methods: {
		open() {
			this.isOpen = true;
		},
		close() {
			this.isOpen = false;
		}
	}
};
</script>

~~~

Component

~~~
<script>
	export default {
		methods: {
			handleClick(event) {
				...
			},
			handleMouseEnter(event) {
				...
			}
		}
	}
</script>
~~~

**Comment by simplesmiler** [comment]
@levan1993 I've put together a fiddle from your code, and I can not reproduce the issue: https://jsfiddle.net/simplesmiler/ajp8qfzf/1/

**Comment by simplesmiler** [comment]
@levan1993 I believe you have been hit by some sort of [Fragment Instance](http://vuejs.org/guide/components.html#Fragment_Instance) caveat.

Specifically:
> ... [for fragment instance] non-flow-control directives, non-prop attributes and transitions on the component element will be ignored, because there is no root element to bind them to.

Please read carefully through this part of docs.
