### ISSUE TITLE
The class item:hover is not work when use v-for for my <div class='item'> . why?

### ISSUE THREAD

**Issue by yuhongwei1122** [vuejs/vue#1824]
<div v-for="el in mycompanys" class="item">my vue test</div> 
<style>.item:hover{color:red;}</style>

**Comment by yyx990803** [comment]
Nit enough information. Please provide a reproduction.

**Comment by yuhongwei1122** [comment]
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
         <meta name="viewport" content="maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width,initial-scale=1.0"/>
    <title>公司联系人列表页</title>
    <style>
            .item:hover{color:red;}
    </style>
</head>
<body>
          <div class="item" v-for="el in mycompanys">{{el.name}}</div>
</body>
</html>

**Comment by yuhongwei1122** [comment]
![Uploading QQ截图20151118135646.png…]()
