### ISSUE TITLE
v-for在ios下的排序问题

### ISSUE THREAD

**Issue by changexbc** [vuejs/vue#1827]
vue:1.0.8
浏览器:ios9.1 safari
问题:使用v-for遍历对象时，当对象的key为字母时，排序为降序

http://sandbox.runjs.cn/show/1rrmulgo
http://runjs.cn/code/1rrmulgo
![1447858756](https://cloud.githubusercontent.com/assets/8199684/11244527/e7866a0a-8e48-11e5-8489-3f874bb3817c.png)

**Comment by yyx990803** [comment]
文档里已经说了，v-for 遍历对象时不保证顺序，因为 JS 规范里并没有限定，所以不同的引擎顺序可能不一致。http://cn.vuejs.org/guide/list.html#对象_v-for

如果要保证顺序，可以加个排序的 filter 或者改用数组。

**Comment by changexbc** [comment]
谢谢
