### ISSUE TITLE
Remove item from multidimensional array based on index.

### ISSUE THREAD

**Issue by opheliadesign** [vuejs/vue#1828]
I am in the process of upgrading a project to Vue 1.0. I have an array of objects in the following format:
```
data: {
shifts: {
            '43' : {
                userId: 43,
                name: 'Frank'
            },
            '90' : {
                userId: 90,
                name: 'Martha'
            }
        }
}
```
Prior to 1.0, to remove an object, I would use `this.shifts.$delete('90')` to delete that object. This no longer works and it is unclear to me what the replacement is. I have also tried `this.$remove(this.shifts, '90')`, `Vue.$remove(this.shifts, '90')`, etc.

Also, `$add` was deprecated in favor of `$set` but I cannot figure out how to add a new object (such as `'95: { userId: 95, name: 'John' })` with `$set`.

Very frustrating, any help would be appreciated.

**Comment by yyx990803** [comment]
The new API is `Vue.delete`: http://vuejs.org/api/#Vue-delete

It has been mentioned in the [upgrade guide](https://github.com/vuejs/vue/releases/tag/1.0.0) under general changes.

**Comment by alexmgillis** [comment]
I think this is relevant to my issue, so I will post here although if you want I can add a new question is that is better.
so i am trying to work with a json that has each row attah to an id in the follwing way:
idnumber : {field1:value 1, field2:vlaue2...),
idnumber : {field1:value 1, field2:vlaue2...),

this si helpfull to me becuase i can access directly to the row i want by using the id.
my problem is that when i do this it not longer accepts push as a function for when i want to add a new row
here is a very simple reprodutiont of my issse:
[https://jsfiddle.net/alexmgillis/ekq2x98r/](https://jsfiddle.net/alexmgillis/ekq2x98r/)`
