### ISSUE TITLE
Ability to disable/not trigger watch handler on data?

### ISSUE THREAD

**Issue by dalanmiller** [vuejs/vue#1829]
For my application, I'm mutating the object in my  `data: [{...}, {...}, {...}]` to state changes occurring at other open instances of my application (happening through web sockets etc, etc). I have a handler on the data structure like this below:

```
watch: {
    todos: {
	    deep: true,
	    handler: todoStorage.save,
    },
},
```

Triggering `todoStorage.save` would unnecessarily save the contents of the array back to my database where I already know the current state of the application.  

Is there a way to mutate the array _without_ triggering the handler? It seems that trying to `undefine` the handler while making the operation doesn't work.

**Comment by yyx990803** [comment]
The point of a watcher is that it will fire when the data changes. Instead of thinking about stopping it from firing, just do a conditional check inside the watcher callback.

**Comment by dalanmiller** [comment]
I wish I could @yyx990803 :cry: 

In this case I cannot do a conditional check in the watcher callback since there's no way for me to check whether I'm going to receive more deletion messages via WebSocket which come one at a time. If every object in my `data` Array is saved after every modification to the Array I get into this case:

1. I receive deletion message for an object in `data`
2. Save all remaining documents in `data` to DB
3. Receive another deletion message for a different object in `data` which was just saved in previous step. 
4. Possible further repetition depending on number of deleted objects.

This results in errors on my backend because I'm trying to update data that no longer exists there. Is there a recommended Vue.js pattern for this?

**Comment by yyx990803** [comment]
I don't think I understand your use case, but maybe using a deep watcher to persist the whole is just the wrong idea to begin with. You should probably use a component for each item in the array so you can do fine-grained persistence.

**Comment by matyo91** [comment]
Hello, i guess i understand the issue from @dalanmiller.

In fact, i was stuck on a similar issue : the fact that you don't want the watcher trigger the callback every time when you manually decide to affect the value somewhere.

For instance : i got my data from an rest api call in an async way. Then i decide to affect the data in my component, but the watcher detect change and will trigger the callback that notice update the changes to my rest api : there were no data change but i got an api 'Set' call ! 😕 

More into this issue, i did a codepen to explain that (VueJS 2.0) : http://codepen.io/matyo91/pen/ZBpjVz
📝 What i want is to fire change only when i manually change the value into the textarea.
Here, the 'code' variable will call onUpdateCode on sync change every time => not what i want 🐛 . And the 'coder' variable will not call onUpdateCoder because i did add a dirty silence mechanism. And onUpdateCoder is only called when i do change text into the coder textarea.
The coder is what i want 🍎 (i tried a better solution with Vue.nextTick, but it fail, i think it could have worked if Vue.nextTick can dispatch by setting a priority parameter)

I come to this code, because somehow, i got a similar issue when integrating ace.js into a VueJS component. And the ace team got the same issue and it's resolved by that comment from @nightwing : https://github.com/ajaxorg/ace/issues/503#issuecomment-163761023
The next comment from @davidthornton notice it's a https://en.wikipedia.org/wiki/Operational_transformation logic.

@yyx990803, you did already answered this in this issue : https://github.com/vuejs/vue/issues/1157
But it's not really this case here.

So i think it's more a design pattern issue. But now i don't know how to write it into a "smart code".

Any idea ?!

**Comment by njleonzhang** [comment]
It seems I encounter a similar issue, my solution is that use this.$watch instead of watch option, this.$watch return a handler to `unwatch` function, which I can call it when I want to stop watch, after that I watch the value again, it's terrible........

**Comment by thuijzer** [comment]
Had the same issue. But I think the fix is simple. Just use the watch function to decide if you would like to call a method:

{{{code=javascript}}}
this.$watch('myModel', function(newVal, oldVal) {
    if([your statement]) {
        this.loadSomeData();
    }
});
{{{code}}}

**Comment by intijk** [comment]
I found that action of the firefox and chrome is different, in updated(), if the event was triggered, firefox fall into stuck and never come out, but chrome can deal with this correctly.

**Comment by mikob** [comment]
whether you use $watch and unwatch, or set a flag to prevent the watch from handling, you'll need to wait for this.$nextTick() otherwise you will unwatch/turn off the flag prematurely and the watcher will still get executed.

**Comment by doncatnip** [comment]
Not sure why this is closed .... it's pretty obvious at this point that this would be a rather useful feature in many situations.

**Comment by danielfaust** [comment]
I'd rather have some kind of `context` added to the watch. Something along the lines of

```
<input type="checkbox" id="checkbox" v-context="my-html" v-model="light_is_on">
<label for="checkbox">Kitchen light is: {{ checked?"on":"off" }}</label>

watch: {
  light_is_on: function(value, old, context) {
    if (context !== 'my-websocket') {
      websocket.send({'light_is_on': light_is_on})
    }
  },
},
methods: {
  websocketHandler(event) {
    if (event.light_is_on !== undefined) {
      Vue.enter_context('my-websocket');
      this.light_is_on = event.light_is_on;
      Vue.exit_context()
    }
  },
},
```

Where this context string is not a global variable which could get changed from anywhere, but is somehow intrinsically attached to the execution flows which get triggered in between the `enter` and `exit` calls.

**Comment by Gruski** [comment]
I like the idea of getting the source from the watch function(value, old, source). I have the same problem and there are only ugly solutions.

**Comment by irongomme** [comment]
Hello, here is what i'm doing for that problem. I had to face with reseting twice search and filters, without trigger multiple watch at the same time.

```
data: {
  search: null,
  filters: { filter1: null, filter2: null },
  watchInPause: false,
},
watch: {
  search() {
    if (!this.watchInPause) {
      this.refresh();
    },
  },
  filters() {
    handler() {
      if (!this.watchInPause) {
        this.refresh();
      }
    },
    deep: true,
  },
},
async onResetFilters() {
  this.watchInPause = true;
  this.search = null;
  this.filters = {
    filter1: null,
    filter2: null,
  };
  await this.refresh();
  this.watchInPause = false;
},
```

Hope this helps ...

**Comment by abellion** [comment]
I made a mixin which brings a `$withoutWatchers()` method. This method disables the watchers within its callback :

```js
$withoutWatchers(() => {
  // Watchers will not get fired
})
```

<details><summary>Here is the mixin</summary>
<p>

```js
const WithoutWatchers = {
  methods: {
    $withoutWatchers (cb) {
      const watchers = this._watchers.map((watcher) => ({ cb: watcher.cb, sync: watcher.sync }))

      for (let index in this._watchers) {
        this._watchers[index] = Object.assign(this._watchers[index], { cb: () => null, sync: true })
      }

      cb()

      for (let index in this._watchers) {
        this._watchers[index] = Object.assign(this._watchers[index], watchers[index])
      }
    }
  }
}
```

</p>
</details>

Be aware that this mixin uses the internal Vue's API, which may change between minor versions. That would be cool to have this kind of method within Vue's core.

**Comment by nftopham** [comment]
@abellion wonderful solution to this problem.

**Comment by johnantoni** [comment]
Nice work @abellion

**Comment by hhaensel** [comment]
@abellion really nice!

- What about using `active: false` instead of `cb: () => null`
- Can you comment on what is more performant?
```
this._watchers[index] = Object.assign(this._watchers[index], { active: false, sync: true })
```
or
```
ww[index].active = false;
ww[index].sync = true
```

**Comment by hhaensel** [comment]
> @abellion really nice!
> 
> * What about using `active: false` instead of `cb: () => null`
> * Can you comment on what is more performant?
> 
> ```
> this._watchers[index] = Object.assign(this._watchers[index], { active: false, sync: true })
> ```
> 
> or
> 
> ```
> ww[index].active = false;
> ww[index].sync = true
> ```

I had tried to use `active` and it seemed to work - but later failed, maybe, something was not updated. So I went back to using @abellion 's original version.
I'd be happy to understand, what the difference is and why `sync = true` is needed.

**Comment by mavyfaby** [comment]
How about in typescript?

**Comment by hutch78** [comment]
@abellion THANK YOU! This is very helpful. Battling data properties and watchers has been a thorn in my side for a long time.

**Comment by haolian9** [comment]
i figured out another solution, in my small project, it works well...

```
{
    data() {
        return {
            avoid_changes: 0,
            count: 1,
        }
    },
    watch: {
        count: function(a, b) {
            if (this.avoid_changes > 0) {
                this.avoid_changes -= 1
            } else {
                // triggered
            }
        }
    }
}

vm.avoid_changes += 1
vm.count = 9
```

**Comment by Arturexe** [comment]
I don't know if this helps anyone but I needed a watcher that watches `state.title` only for the first change. This worked for me:

```

const triggerWatch = watch(() => state.title, () => {
    if (state.title) {
        console.log(state.title)
        triggerWatch()
    }
})
```

**Comment by h-sigma** [comment]
In my case, I only wanted to watch a partial object.
```
      pagination: {
        page: 1,
        perPage: 5,
        totalPages: 0,
        totalRecords: 0,
      },
```
`totalPages` and `totalRecords` are set from the API response, while `page` and `perPage` are set from the UI.
I was able to bypass the issue by making a computed property that only watches the UI-changeable parts of the paginator.

**Comment by timmaier** [comment]
For those using vueuse library: https://vueuse.org/shared/watchignorable/

**Comment by mralston** [comment]
Here's a follow up to @abellion's [solution](https://github.com/vuejs/vue/issues/1829#issuecomment-624193371).

As abellion predicted, Vue's internal architecture seems to have changed between versions 2 and 3, and I found that the mixin no longer worked after upgrading.

After a little digging, I found that the watchers had moved within Vue's hierarchy, but the basic premise appears to be same.

Here's an updated version of @abellion's mixin. I believe this works correctly in Vue 3. However I strongly suggest that anyone deciding to adopt it should test it carefully.

```js
export default {
    methods: {
        $withoutWatchers (cb) {
            const watchers = this._.type.watch;

            for (let index in this._.type.watch) {
                this._.type.watch[index] = Object.assign(this._.type.watch[index], { cb: () => null, sync: true })
            }

            cb()

            for (let index in this._.type.watch) {
                this._.type.watch[index] = Object.assign(this._.type.watch[index], watchers[index])
            }
        }
    }
}
```

**Comment by jsodeman** [comment]
For anyone finding this still using Vue 2, as of 2.7.x abellion's solution above needs to be changed to:

```js
 export default {
	methods: {
		$withoutWatchers(cb) {
			const watcher = {
				cb: this._watcher.cb,
				sync: this._watcher.sync,
			};

			this._watcher = Object.assign(this._watcher, { cb: () => null, sync: true });

			cb();

			this._watcher = Object.assign(this._watcher, watcher);
		},
	},
};
```

**Comment by john-** [comment]
> There's a watchIgnorable in the vueuse library: https://vueuse.org/shared/watchignorable/ that allows you to stop the watch

Thanks for pointing this out.  I ran against the issue and was able to resolve it by using watchIgnorable in my Vue 3 application.

Keywords: Parent initiated update alters property in child.   Child UI to ignore updates as a result of the property change.  [Code](https://gitlab.com/john---/test_mojojs/-/blob/d8a1d9a819ce6fb8a8cc364faa6bb8c144a3edec/FrontEnd/src/components/ScannerTransmission.vue#L45)

**Comment by mralston** [comment]
Anyone got any ideas on how to do this in Vue 3 with the Composition API and the `<script setup>` tag?

**Comment by john-** [comment]
> Anyone got any ideas on how to do this in Vue 3 with the Composition API and the `<script setup>` tag?

The code I linked to on 10/14 worked for me in this situation.

**Comment by mralston** [comment]
> > Anyone got any ideas on how to do this in Vue 3 with the Composition API and the `<script setup>` tag?
> 
> The code I linked to on 10/14 worked for me in this situation.

Thank you! I'll take a look. :)

**Comment by hhaensel** [comment]
> There's a watchIgnorable in the vueuse library: https://vueuse.org/shared/watchignorable/ that allows you to stop the watch

That was my rescue as the other solution ceased to work. However, instead of relying on the full VueUse library I copied only the code of watchIgnorable from VueUse, which works perfectly also as a standalone function.

**Comment by rhoffmann** [comment]
> Here's a follow up to @abellion's [solution](https://github.com/vuejs/vue/issues/1829#issuecomment-624193371).
> 
> As abellion predicted, Vue's internal architecture seems to have changed between versions 2 and 3, and I found that the mixin no longer worked after upgrading.
> 
> After a little digging, I found that the watchers had moved within Vue's hierarchy, but the basic premise appears to be same.
> 
> Here's an updated version of @abellion's mixin. I believe this works correctly in Vue 3. However I strongly suggest that anyone deciding to adopt it should test it carefully.
> 
> ```js
> export default {
>     methods: {
>         $withoutWatchers (cb) {
>             const watchers = this._.type.watch;
> 
>             for (let index in this._.type.watch) {
>                 this._.type.watch[index] = Object.assign(this._.type.watch[index], { cb: () => null, sync: true })
>             }
> 
>             cb()
> 
>             for (let index in this._.type.watch) {
>                 this._.type.watch[index] = Object.assign(this._.type.watch[index], watchers[index])
>             }
>         }
>     }
> }
> ```

I tested it, and in my opinion this solution does not work for vue3. The code never stores/copies the original watchers, but assigns a reference to the object with `const watchers = this._.type.watch;` thus restoring back after patching just restores the patched watchers (same reference).

Also, i think `cb` and `sync` are not a thing in vue3, at least i did not find any in the prototype chain of the `_type.watch`. I assume the watchers on this._.type.watch are just methods that be completely replaced during the pre-callback monkeypatch.

Anyways, i would probably advise using this approach in general, preferrably solved with other solutions like `watchIgnorable`.

This approach seems to work for me, but as the OP said, test it yourself before using it in production :)

```
$withoutWatchers(cb) {
      let originalWatchers = {}

      // no structured clone because we only need the references
      for (let [key, watcher] of Object.entries(this._.type.watch)) {
        originalWatchers[key] = watcher
      }

      this._.type.watch = {}

      cb()

     // restore watchers
      this._.type.watch = Object.assign(this._.type.watch, originalWatchers)
    },
```

**Comment by putrafajarh** [comment]
There is a solution from vueuse
https://vueuse.org/shared/watchIgnorable/

**Comment by tmcdos** [comment]
The correct code for Vue 2.7.x is
```javascript
  methods:
    {
      /**
       * Pause watchers during the callback to avoid unwanted triggering
       * @param cb {Function}
       */
      $skipWatchers(cb)
      {
        const version = (('_base' in this.$root.$options) 
          ? /* Vue 2 */ this.$root.$options._base.version 
          : /* Vue 3 */ this.$root.$.appContext.app.version).split('.');
        if (version[0] === '2')
        {
          if (version[1] < 7)
          {
            // Vue 2.6.x - https://github.com/vuejs/vue/issues/1829#issuecomment-624193371
            const watchers = this._watchers.map((watcher) => ({
              cb: watcher.cb,
              sync: watcher.sync
            }));

            for (const index in this._watchers)
            {
              this._watchers[index] = Object.assign(this._watchers[index], {
                cb: () => null,
                sync: true
              });
            }

            cb();

            for (const index in this._watchers)
            {
              this._watchers[index] = Object.assign(this._watchers[index], watchers[index]);
            }
          }
          else
          {
            // Vue 2.7.x
            const effects = this._scope.effects;
            const old = Array(effects.length);
            effects.forEach((effect, index) =>
            {
              if (effect.user && this === effect.vm)
              {
                old[index] = {
                  cb: effect.cb,
                  sync: effect.sync,
                };
                effect.cb = () => null;
                effect.sync = true;
              }
            });

            cb();

            old.forEach((effect, index) =>
            {
              if (effect)
              {
                effects[index].cb = effect.cb;
                effects[index].sync = effect.sync;
              }
            });
          }
        }
        else
        {
          // Vue 3 - https://github.com/vuejs/vue/issues/1829#issuecomment-2252350910
          const originalWatchers = {};

          // no structured clone because we only need the references
          for (const [key, watcher] of Object.entries(this._.type.watch))
          {
            originalWatchers[key] = watcher;
          }

          this._.type.watch = {};

          cb();

          // restore watchers
          this._.type.watch = Object.assign(this._.type.watch, originalWatchers);
        }
      }
    }
```

**Comment by tmcdos** [comment]
I am not sure why but the suggested code for Vue 3 does not work for me:
```javascript
  const originalWatchers = {};

  // no structured clone because we only need the references
  for (const [key, watcher] of Object.entries(this._.type.watch))
  {
    originalWatchers[key] = watcher;
  }
  this._.type.watch = {};
  cb();

  // restore watchers
  this._.type.watch = Object.assign(this._.type.watch, originalWatchers);
```
What did work for me was this:
```javascript
const effects = this._.scope.effects;

effects.forEach(effect =>
{
  if (effect.flags === 5) // ACTIVE and TRACKING
  {
    effect.flags = 69; // ACTIVE, TRACKING but PAUSED
  }
});

cb();

effects.forEach(effect =>
{
  if (effect.flags === 69)
  {
    effect.flags = 5;
  }
});
```
