### ISSUE TITLE
[HELP NEEDED] Custom event listener never called?

### ISSUE THREAD

**Issue by adcentury** [vuejs/vue#1830]
I want to dispatch a custom event from child and deal with it in parent.

http://vuejs.org/guide/components.html#v-on_for_Custom_Events says i can use `v-on` to listen on custom event.

I added a method in parent component
```
methods: {
    handleSeatSelect(name) {
      console.log(name);
      this.seatSelected = name;
    }
  }
```

then listen to custome event `seatSelect` when create child component seat
```
<seat
  ...
  @seatSelect="handleSeatSelect">
</seat>
```

in the child component, it dispatched the custome event `seatSelect`
```
onSelect(event) {
  this.$dispatch('seatSelect', this.name);
  console.log('send select ' + this.name);
}
```

now `this.$dispatch('seatSelect', this.name);` executed, but `handleSeatSelect` never get called.

**Comment by yyx990803** [comment]
HTML is case insensitive. Don't use uppercase for event names.

**Comment by adcentury** [comment]
thanks a lot :)
