### ISSUE TITLE
There is a place of origin code that I don't understand

### ISSUE THREAD

**Issue by silaLi** [vuejs/vue#1831]
```javascript
//this is the first 386 lines of code 
function (a) {
        var l = arguments.length
        return l
          ? l > 1
            ? fn.apply(ctx, arguments)
            : fn.call(ctx, a)
          : fn.call(ctx)
}
```
I don't understand the ```return```.
why need to analyze ```arguments.length```.
why not replace with```function(){fn.apply(ctx, arguments)} ```

**Comment by yyx990803** [comment]
This is just for optimization because `fn.call` is faster than `fn.apply`, and most of the time bind has 0 or 1 arguments.

PS. Please do not use issues to ask questions.

**Comment by silaLi** [comment]
sorry,I will read README carefully.
