### ISSUE TITLE
Templates using v-if directive using computed values where cache is false don't react predictably

### ISSUE THREAD

**Issue by tremendus** [vuejs/vue#1833]
Issue: computed properties calculated from properties passed to child component from parent DO update value in $vm (and vue js developer toolbar) when cache = false, but DO NOT update in templates 

Consider the following vue component for a select input in a parent form component:

```javascript
var vue = {
	name: 'FormSelect',
	props: ['field', 'unsaved'],
	computed: {
		isDirty: {
			cache: false,
			get: function () {
				var bool = this.unsaved.hasOwnProperty(this.field.id)
				return bool
			}
		}
	}
}
// props[field] =  a form field, where the select option value is bound to the 'value' key
// props[unsaved] = a list of dirty fields from parent component (the form)
// isDirty simply checks if the id of the field for this component is in the unsaved object in the parent
```
The requirement is to conditionally display an element if the field isDirty (has been changed from loaded value) 

```jade
.form-group
	label.control-label {{field.label}} {{isDirty}}
		span.label.label-danger(v-if="isDirty") unsaved changes
	select.form-control(v-model="field.value")
		option(v-for="option in field.options", v-bind:value="option.value") {{option.label}}
```

issue: when selecting a new value from the select options, the computed property does change in the VueJS developer tool bar and when putting $vm -> console, but the templates do not react.

**Comment by yyx990803** [comment]
Does `this.field.id` or `this.unsaved` change as a result of selecting a different option? The select `v-model` is bound to `field.value`. It doesn't affect any dependencies of your computed property.

**Comment by tremendus** [comment]
Sorry, tried to make this clear from the post. The parent 'form' component has watchers setup on the values. When a change to the value occurs, its id is either added to this unsaved object or removed (depending on whether the new value is the same or different to the old value). Accordingly, this unsaved object is passed to child form inputs and with the cache set to false, they correctly update in the $vm ... but not in the template. Note the $vm behaves as expected, but the view falls out of synch.

**Comment by yyx990803** [comment]
Are you using `Vue.set` to modify the `unsaved` object?

**Comment by tremendus** [comment]
Not the Vue global, but `this.$set()`, yes

I wonder could it be that in this project I have to work with ids of the objects coming from ajax are numerical strings eg "5434" ? So my set statement is like this: 

`this.$set('unsaved[' + s.id + ']', val)`

I ask because I did notice it caused an issue when calling the component yesterday: 
I had to change the calls to double quoted attributes ie. `form-select(v-bind:field="settings['1001']", v-bind:unsaved="unsaved")` from single quoted ones (with double quoted numerical strings) otherwise the databinding to display the values failed 

I wonder if the whole concept of trying to support the native data structure - numerical strings - is causing my issues. Perhaps I should reformat the data ... ?

**Comment by yyx990803** [comment]
Well, seems like it should work - but it's hard to determine what really is wrong without a reproduction. If you can, please provide a minimal repro to help isolate the problem.

**Comment by tremendus** [comment]
Yeah, I will, there are a lot of mixins and dependencies but I'll try to strip them out and put a pastebin or something up, thanks Evan. Ps still lovin' Vue, it's become my goto tool now, used it as a base on my last 3 projects, and they've been some of the most enjoyable / least painful ones I've ever done :)

**Comment by yyx990803** [comment]
Closing (inactivity)
