### ISSUE TITLE
Thoughts on property defaults.

### ISSUE THREAD

**Issue by amanpatel** [vuejs/vue#1834]
Consider a component caled Box with the following property:

```js
export default {
props: {
    type: {
        type: String,
        default: "text"
    }
}
}
```

The intension of the component designer here is that anything we don't have a **meaningful** input for "type", it should be "text".

In Vue it seems that defaults are assigned only if the property is omitted. Consider the following example of using the box component.

```html
<template>
Box type:
   <box :type="box_type" />

Box text type:
  <box />
</template>
```

In the first case if "box_type" is defined, this works well and good. If "box_type" is undefined for whatever reason, this causes the Box component's type property to be unset and a warning to be issued in the console.

The second usage of <box> works as expected and the property defaults to "text".

Should undefined property values cause defaults to be assigned? I think it would make for a nicer development practice.

**Comment by young-steveo** [comment]
I've run into this as well.  I feel like the default should be used if a prop is not defined.

**Comment by posva** [comment]
what if you want to explicitly set the value to undefined?

**Comment by amanpatel** [comment]
@posva That is indeed a good point, however I'm failing to see how an API designer would make sure of this. Would you give me an example of how that would work. 

>RANT I feel like the undefined type shouldn't have existed in the first place. It's one of those JS language constructs that is probably too late to get rid of now. Every time I've come head to head with undefined types in Javascript it's always under bad circumstances :-)

**Comment by posva** [comment]
You may have a component that is showing up yet is waiting for some async resource to be available.
Although null could be used too but this may be tricky for some users

**Comment by AlexandreBonaventure** [comment]
+1 for bringing this up to the table.

**Comment by yyx990803** [comment]
The semantics of `default` is for providing a value when the prop is absent (i.e. the consumer of the component did not even provide a value). This is different from providing a value, but with a value of `undefined`. As @posva mentioned, this could lead to unexpected results for some users, and is also a breaking change, which in general we should try to avoid if there's no strong benefits in doing so.

I think the use case can be covered by the suggested `coerce` option though: https://github.com/vuejs/vue/pull/1955

**Comment by noirbizarre** [comment]
Hi !

I think this is debatable.
In JavaScript, the sole purpose of `undefined` is precisely this case: explicitely saying that no value has been affected.
This is the sole definition of `undefined` value in the ECMA specifications: http://www.ecma-international.org/ecma-262/6.0/#sec-undefined-value
It should be interpreted as a value but as the absence of value.
This is also why `JSON.stringify` will dump `null` keys but not`undefined` ones.

So, in my opinion, when ``undefined`` is set as property anywhere, it should be interpreted as "no value is assigned" and in the case of Vue properties, it should trigger default.

**Comment by yyx990803** [comment]
This is debatable exactly because some users feel the other way. And the point is that this **will be a breaking change**, so I prefer to leave it in current state unless everyone agrees it should be changed.

**Comment by amanpatel** [comment]
Agreed. Perhaps in the next MAJOR (semantic version), this could be reconsidered by opening it to the community (as you already suggest).

This is not that hard to workaround, and the coerce option makes it even better. Thanks.

**Comment by revati** [comment]
is it possible to access default value from coerce callback?
So i could do it manually where needed.

Or event better way would be: is it possible to conditionally pass prop to child component?
```vue
<child :msg="parentMsg"></child>
``` 

So, if `parentMsg` is undefined it is not passed at all?

**Comment by lopugit** [comment]
Where are we at with this decision? 

In my opinion it is embedded in the nature of javascript for a schema to use the default value of the property if the property is passed as undefined.

Actually it isn't embedded but that's how mongoose schema definition does it and it's logical in my opinion.

How else do you make a <component v-for="item in items" :item="item" ></component>

with a default item value resort to the default when you want to add a new item to items, and do so by pushing an undefined value into the items list. So that the component takes care of the default value, because you shouldn't have to put any component logic into the parent, am I right.

What workaround is there for my use case to ensure that :item is only passed if it is not undefined? So I can get the default value working?

thank you kindly vue team

**Comment by revati** [comment]
Im still favouring undefined value as no value (use default value), if value is null or false, than use passed one.

Otherwise i have to write:
```vue
<template>
   <box v-if="box_type" :type="box_type" />
   <box v-else />
</template>
```

But i could write:
```vue
<template>
   <box :type="box_type || undefined" />
</template>
```

**Comment by sirlancelot** [comment]
You could build your `Box` component to use a computed property based on the prop, and if the passed prop matches your criteria, make it a default:

```javascript
export default {
    name: "box",
    props: ["box_type"],
    computed: {
        internalBoxType() {
            return this.box_type || "default"
        }
    }
}
```

Then you only use `internalBoxType` within your `Box` component.

**Comment by lopugit** [comment]
A computed property doesn't break the v-binding nature of properties?

**Comment by revati** [comment]
@sirlancelot yeah, but that sort of makes props default value obsolete.

This is the way i usually approach similar things. i don't use default prop values at all (there could be cases where that would work, but for sake of consistency across project...)

**Comment by revati** [comment]
@lopugit https://vuejs.org/v2/guide/computed.html#Computed-Setter is the way to use computed properties for two way binding (as v-model)

**Comment by WickedSik** [comment]
@revati Could you show an example as how you'd use this? By just saying there is a way, without explaining, the rest of us are still poking in the dark.

**Comment by revati** [comment]
@WickedSik here you go https://jsfiddle.net/revati/na4wddt0/3/

its little bit expresive, but this is the way we handle optional props.
