### ISSUE TITLE
@ready event for v-for elements? 

### ISSUE THREAD

**Issue by xkjyeah** [vuejs/vue#1836]
Not sure if a workaround already exists. After I add to a list of text boxes, I want to focus on the most recently added box. However there isn't a @ready event for repeated elements.

**Comment by yyx990803** [comment]
Use `Vue.nextTick`: http://vuejs.org/guide/reactivity.html#Async_Update_Queue

**Comment by xkjyeah** [comment]
Sorry, I wasn't clear enough on this. I understand how nextTick works, but
AFAIK it doesn't tell the event handler which element is involved.

E.g. I cannot do $(event.target).find('input').focus()

Because event.target is not set.

Does this sound like a reasonable feature?

**Comment by yyx990803** [comment]
If the order is fixed you can do something like `$('li').last().find('input').focus()`. Otherwise you might need to implement the list item as a component.
