### ISSUE TITLE
Possible Form Input - Checkbox Binding Bug

### ISSUE THREAD

**Issue by Teevio** [vuejs/vue#1837]
I'm not sure if this is a bug, but someone posted about this in the forums.

When doing something like this `<input type="checkbox" v-model="isChecked" v-on:click="checkboxHandler" />` the checkboxHandler method is not reporting the incorrect `isChecked` value in Firefox/Chrome but Safari reports the correct value (tested on OS X).  You can see this in action here: http://jsfiddle.net/5sH6A/214/

**Comment by simplesmiler** [comment]
@Teevio `v-model` reacts to the `change` event, not the `click` one. And apparently `click` and `change` may be triggered in different order, depending on the browser.

**Comment by Teevio** [comment]
@simplesmiler ahhhh, I hadn't thought about that, so not a bug :+1:
