### ISSUE TITLE
commentNode.contains broken in IE10/11

### ISSUE THREAD

**Issue by knownasilya** [vuejs/vue#1838]
So I'm using an older version v0.11.10, and am getting the issue where `contains` is undefine. This is happening in `getContainedComponents` (`if (cur.contains(c.$el)) {`) where `cur` is a comment node with the contents `<!--v-component-->`. Seems like a shim for `contains` is necessary, has this been added in newer versions?

Example non-vuejs fiddle with the isolated issue: http://jsfiddle.net/Lbfpm7j3/
Related IE issue: https://connect.microsoft.com/IE/Feedback/Details/780874

This is a high profile app, and there might not be budget to update to the latest version of Vue at this time. Is there anything that could be done beyond upgrading (if that will even solve the issue).

**Comment by knownasilya** [comment]
Ah, found the fix https://github.com/vuejs/vue/pull/893 I guess I can just apply the fix manually.

**Comment by yyx990803** [comment]
Cool, glad you found it :)

**Comment by knownasilya** [comment]
Hopefully we can update to v1 soon.
