### ISSUE TITLE
v-for , v-repeat and Flask  have conflicts

### ISSUE THREAD

**Issue by chanyying** [vuejs/vue#1844]
```
<ul>
      <li v-repeat="to in ototoxic">
            {{to.time}}
      </li>
</ul>
```
```
jinja2.exceptions.UndefinedError
UndefinedError: 'to' is undefined
```

**Comment by AStaroverov** [comment]
this will help you
http://vuejs.org/api/#delimiters

**Comment by rpkilby** [comment]
Checkout jinja2's builtin [template escaping](http://jinja.pocoo.org/docs/dev/templates/#escaping).

For django users, There are the `verbatim`
```
{% verbatim %}
...
{% endverbatim %}
```

**Comment by mjchaudhari** [comment]
I know this is very old post. but you can get rid of using moustache. Rather use `<span v-text="to.time">  ` you may not need to use delimiters.
