### ISSUE TITLE
Computed properties (arrays), duplicating in Safari (bug?)

### ISSUE THREAD

**Issue by amanpatel** [vuejs/vue#1847]
Fiddle:
http://jsfiddle.net/amanpatel/1gxhL4Lv/2/

Run this under **Safari Version 9.0.1 (11601.2.7.2)**, I'm seeing two "firstName - Foo".

I'm expecting only one.

**Under Chrome 46, I'm seeing the correct behavior.**

**Comment by yyx990803** [comment]
This is not related to Vue. It's because you are using `for ... in` to iterate over an Array. This is wrong usage and not guaranteed to work consistently in different JavaScript engines.

**Comment by amanpatel** [comment]
Thank you. I've been using it this way ```for .. in``` the past couple of years without any ill effects (well exception this one).

For people who find this issue later on, here's a link with much more discussion in it
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea
