### ISSUE TITLE
Issue with Vue.util.extend not removing data binding to object properties

### ISSUE THREAD

**Issue by jjaulimsing** [vuejs/vue#1849]
Hi,

I have a situation where I have the following object
```
data : {
			navigation : {
				step : {
					prev : 0,
					current : 1,
					next : 2
				},

				phase : {
					prev : 0,
					current : 1,
					next : 2
				},

				next_type : 'phase',

				can : {
					prev : false,
					next : false
				}
			},

			history : []
		},
```

but using ``` Vue.util.extend( {}, this.navigation ) ```  maintains the data binding. Thus if I say `this.navigation.phase.current = 5` it will also update the object pushed in `this.history` which I am trying to avoid. 

Can anyone advise if am doing something wrong or if it is an actual bug to the util.export?

I played around with the fiddle http://jsfiddle.net/huLygoag/2 and forked into a new version where I could replicate my issue http://jsfiddle.net/5kxrwuag/. Right now my only option seems to be `this.history.push( { navigation : { phase : Vue.util.extend ( this.navigation.phase ), ...` for each properties.

**Comment by simplesmiler** [comment]
@jjaulimsing if your data is nested, you need to make a deep copy. One option to do this is `JSON.parse(JSON.stringify(...))`. To make this work your data has to be plain (no circular or shared references, no prototypes, no functions).

**Comment by jjaulimsing** [comment]
@simplesmiler I came across this workaround `JSON.parse(JSON.stringify(...))` a few minutes after posting here. I read in the jquery doc that the .extend supports deep copy. I am not sure if Vue.util.extend supports the same as I read it's not documented in the API.

I've been proceeding with the workaround suggested above up to now, I guess this will have to do it. Thanks for clarifying as well the cause.

**Comment by yyx990803** [comment]
`Vue.util.extend` has nothing to do jQuery's extend. It's always a shallow clone.
