### ISSUE TITLE
Question about event.targetVM

### ISSUE THREAD

**Issue by HustLiuCN** [vuejs/vue#1852]
I found there is no `event.targetVM` in the latest version , and in another issue I saw **"This is no longer necessary because v-for no longer creates anonymous child instances."**

then, **what's the best way to change a property of a item which created by `v-for`**?
in old way, I just need to do like `e.targetVM.prop = false`.
now I think I have to do like:
```
<li v-for="li in list" @click="_handler($index)>xxx</li>

_handler: funcion(index){
this.list[index].prop = false;
}
```

**Or, is there any other more convenient method to do this ?**

**Comment by simplesmiler** [comment]
@HustLiuCN you can pass the item directly.
``` html
<li v-for="li in list" @click="_handler(li)>xxx</li>
```
``` js
_handler: funcion(item) {
  item.prop = false;
}
```

**Comment by HustLiuCN** [comment]
thx a lot :D
