### ISSUE TITLE
can i use v-model features on child component ?

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#1908]
this feture will be used for custom style with input elements……

this is a checkbox component

    <div class="c-checkbox" :checked="checked">
        <input type="checkbox" name="{{name}}" value="{{value}}" :checked="checked" v-el="val">
        <label v-on:click="toggle"><i></i><slot></slot></label>
    </div>

I use it as a checkbox elements:

    <p>
        <checkbox name="sex" :value="user.sex" v-model="something">男</checkbox>
    </p>

How to realize this kind of usage?

**Comment by posva** [comment]
Just pass a two way prop and use the v-model inside the component. Here is an example in coffee and jade

```vue
<template lang="jade">
label.mdl-checkbox.mdl-js-checkbox(v-bind:for.once='id' v-bind:class='{ "is-disabled": disabled, "is-checked": isChecked }')
  input.mdl-checkbox__input(v-bind:value='value' type='checkbox' v-bind:id.once='id' v-model='checked' v-bind:disabled='disabled')
  span.mdl-checkbox__label
    slot
</template>

<script lang="coffee">
common = require '../mixins/toggle.coffee'
module.exports =
  checked:
      validator: (value) ->
        typeof value is 'boolean' or value instanceof Array
      required: true
      twoWay: true
    disabled: Boolean
    id: String
    value:
      required: false
  computed:
    isChecked: ->
      if typeof @checked is 'boolean'
        @checked
      else
        @value in @checked
  mixins: [common]
  ready: ->
    componentHandler.upgradeElements @$el
</script>
```

**Comment by ccqgithub** [comment]
@posva i see, tks !
