### ISSUE TITLE
Vue 1.0.10: touchmove event is not triggered on iOS 9.

### ISSUE THREAD

**Issue by Dafrok** [vuejs/vue#1909]
### Thank you for your work!

**Comment by Mat-Moo** [comment]
You have an error in your code - e.preventDefault() is not a function, which isn't a surprise as you reassign e.

**Comment by Mat-Moo** [comment]
Ok so you've updated your code, but now you have another error Cannot set property of 'touches' on undefined (If you view compiled it doesn't seem to know that touches is in the data object) - Please check the console before posting non-bugs and if you're still having issues please use the forum of gitter.

**Comment by Dafrok** [comment]
@Mat-Moo So sorry, That's my fault, but it still doesn't work well. I think there's another problem with touch event.

**Comment by Dafrok** [comment]
@Mat-Moo I fixed that error just now, it's a mistake.

**Comment by Dafrok** [comment]
@Mat-Moo Yes I checked the console, when you were checking my code, I fixed it soon but the problem is still alive :-( So I think it's not non-bugs.

**Comment by yyx990803** [comment]
`e.touches` is a `TouchList` native object, not an array. It also contains native `Touch` objects, not plain objects. Vue only observes plain objects. Convert `e.touches` to plain objects before setting it on the vm, e.g. `[].map.call(e.touches, function (t) { return { force: e.force, x: e.pageX, y: e.pageY }))`

**Comment by Dafrok** [comment]
I got it, thanks a lot!
My code works well on Mac, iPad, Andriod phone, even though PSV & 3DS, but iPhone6s, so I felt uncertain about that.

**Comment by Dafrok** [comment]
@yyx990803 I got it, thanks a lot!
My code works well on Mac, iPad, Andriod phone, even though PSV & 3DS, but iPhone6s, so I felt uncertain about that.
