### ISSUE TITLE
suggestion：Support $trigger and $triggerEl ……

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#1913]
$trigger: trigger a event to a component
$triigerEl: trigger a original event to a element , just like : 

    if (typeof CustomEvent !== 'undefined') {
            e = new CustomEvent(evt, opt);
            if (el) {
                el.dispatchEvent(e);
            }
        } else {
            e = document.createEvent("CustomEvent");
            e.initCustomEvent(evt, true, true, detail);
            if (el) {
                el.dispatchEvent(e);
            }
        }

**Comment by yyx990803** [comment]
Why?

**Comment by ccqgithub** [comment]
ooo, i want to do something like that before， but i find another beter way to do it, i close the issue now ……

**Comment by qur2** [comment]
Hi,

I'm diving my way in vuejs, whihc is great so far. I'm posting on this issue just because I have a question on this topic. Forgive me if that is irrelevant and/or already seen.

I'm wondering what's the difference between the API at http://vuejs.org/api/#vm-emit and actually using a `CustomEvent` such as:
```javascript
// in a parent component
// <dropdown :options="options" label="Marke" v-on:select="filter" for="brand"></dropdown>
  filter: function (evt) {
      const { filter, value } = evt.detail
      this.$data.filters[filter].selected = value
    }

// in a child component
  select: function (evt) {
      const t = evt.target
      const i = indexOf(t.parentNode.children, t)
      const e = new CustomEvent('select', {
        detail: { filter: this.for, value: this.options[i] }
      })
      this.$el.dispatchEvent(e)
    }
```

Is that a bad idea and I should use vue API? Why?

Thanks for your help.

**Comment by yyx990803** [comment]
@qur2 Vue's custom event system is lighter weight as it is pure JavaScript, and `$emit` doesn't do a full propagation, so the effect of the triggered event is contained.

**Comment by qur2** [comment]
Thanks for the clarification!
