### ISSUE TITLE
get initial value after cancelling

### ISSUE THREAD

**Issue by thibaultvanc** [vuejs/vue#1914]
Hello there,
How is it possible to get the initial value of a variable if the user press on a cancel action?

for example, my initial value is 'hello'
I start editing to 'hello word'
and before saving I call a cancel Method
--> How to retrieve the initial value, in this case : 'hello'

Thanks for help

**Comment by jwebcat** [comment]
You have to save it in another var then restore it if user cancels

**Comment by yyx990803** [comment]
Please use the Gitter channel or the forum for questions.

**Comment by thibaultvanc** [comment]
it's what I did but the variables seem to be linked
