### ISSUE TITLE
Crashes on chrome but working on explorer

### ISSUE THREAD

**Issue by actuallymab** [vuejs/vue#1916]
Hello, 

I'm a backend guy but must handle a situation on a dashboard. I listen two events on pusher and trigger two integer data in vue js. 

```
                    this.pusherChannel.bind('TransactionWasCreated', function (message) {
                        if (message.source == 'bulk') {
                            vm_index.$set('transaction.operation.bulk.completed', vm_index.$get('transaction.operation.bulk.completed') + 1);
                            vm_index.$set('transaction.operation.bulk.success_completed', vm_index.$get('transaction.operation.bulk.success_completed') + 1);
                            if (vm_index.$get('transaction.operation.bulk.completed') == vm_index.$get('transaction.operation.bulk.count')) {
                                vm_index.finishTransactionBulk();
                            }
                        }
                        vm_index.transactions.unshift(message.transaction);
                        vm_index.transactions.pop();
                    });
                    this.pusherChannel.bind('TransactionCouldNotCreated', function (message) {
                        if (message.source == 'bulk') {
                            vm_index.$set('transaction.operation.bulk.completed', vm_index.$get('transaction.operation.bulk.completed') + 1);
                            vm_index.$set('transaction.operation.bulk.fail_completed', vm_index.$get('transaction.operation.bulk.fail_completed') + 1);
                            if (vm_index.$get('transaction.operation.bulk.completed') == vm_index.$get('transaction.operation.bulk.count')) {
                                vm_index.finishTransactionBulk();
                            }
                        }
                    });
```

After 200-240th trigger chrome crashes (it achieves this count in nearly 80-90 secs). But internet explorer is still working like a charm. I am opening this issue here, not on stackoverflow, because I think there might be a structural problem that I could not understand.

**Comment by yyx990803** [comment]
Can't really tell what's wrong just by looking at this, but here's a few things you should try:

1. Just use plain syntax: `vm_index.transaction.operation.bulk.complete = ...`. If your initial data is declared properly there's no point in using `$get` and `$set`.

2. Use Chrome's profiling tool to take memory heap snapshots and see if there's a leak somewhere.

3. Provide more context on what your code is doing.

**Comment by actuallymab** [comment]
Hello @yyx990803 thanks for quick reply, 
1. I tried that, nothing changed.
2. could not do that because of crash, it remains "recording.." situation.
3. actually this code snippet is the whole lifecycle. It listens pusher, and when it catches two events, one of them `TransactionWasCreated`; counts up success & total variables, the other is `TransactionCouldNotCreated`; counts up fail & total variables. I can't see any wrong structure here. That's why it's weird. 

By the way, I use vue.js on my whole projects until today without a headache! Thanks for making this brilliant library. It helps me very much at front end.

**Comment by yyx990803** [comment]
What does your `vm_index` component look like?

**Comment by actuallymab** [comment]
while investigating it again and again I found the problem was occured because of using pusherChannel like `this.pusherChannel` it was a wrong declaration inside of vue component, anyone should define it like `pusherChannel`. thanks for helping btw.
