### ISSUE TITLE
problem when use input[type="date"]

### ISSUE THREAD

**Issue by airyland** [vuejs/vue#1918]
```
var box = new Vue({
    el:'#box',
    data:{
      form:{
      "date-1":'',
      "date2":''
      }
   }
  });
```
After selecting date, the value of `form.date-1` is NaN.

http://jsbin.com/cujuxohewo/edit?js,output

**Comment by Mat-Moo** [comment]
It's not the input type is the reference with a - in it, e.g. http://jsbin.com/honelo/1/edit?html,js,output you see data 2 works correctly

**Comment by yyx990803** [comment]
Use form['date-1']
