### ISSUE TITLE
Version number "v" prefix

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue#1920]
Versions [`v1.0.9`](https://github.com/vuejs/vue/releases/tag/v1.0.9) and [`v1.0.10`](https://github.com/vuejs/vue/releases/tag/v1.0.10) are git-tagged with the `v` prefix as opposed to the [`1.0.8`](https://github.com/vuejs/vue/releases/tag/1.0.8) and former (and also [`1.0.10-csp`](https://github.com/vuejs/vue/releases/tag/1.0.10-csp)). Is this intentional or accidental? If intentional, then what's the reasoning behind the sudden change and will it stay?

**Comment by yyx990803** [comment]
This is overlooked when I switched to the new release script, but it doesn't make any real difference. Package managers that resolve against GitHub can handle both formats - we will probably stick with the `v` prefix from now on.

**Comment by simplesmiler** [comment]
@yyx990803 it's not a big deal. I only noticed when the rawgit link for `1.0.10` didn't work until I added the prefix. Sticking with the `v` sound fine.
