### ISSUE TITLE
Android Browser Issue

### ISSUE THREAD

**Issue by SONiD3L4V** [vuejs/vue#1921]
In android 4.3.1, on default browser at page of vue.js documentation I saw this:

![2015_11_25_00 26 49](https://cloud.githubusercontent.com/assets/16020735/11404304/d8a4f022-93a9-11e5-94aa-6b5eb9957a01.png)

please fix this render issue. it's too same for something like vue.js
Keep good work.

**Comment by yyx990803** [comment]
Not really a bug in Vue, it's because the example used `<template>` tag which is not natively supported in older Android. Fixed in the docs repo.
