### ISSUE TITLE
Directive paramWatchers, oldVal provided is the actually the value after the change (the new value)

### ISSUE THREAD

**Issue by tianhai82** [vuejs/vue#1922]
I setup a paramWatcher to watch a dynamic parameter passed to a directive.
The param is called 'options'. When I make a change in 'options' from the parent vm and print out the oldVal and newVal in the param watcher function, both give me the same value.  
http://jsfiddle.net/tianhai/uco50er6/2/

**Comment by simplesmiler** [comment]
Please read through https://github.com/vuejs/vue/issues/1086.
In short:
> newVal and oldVal for reference type values (Arrays and Objects) will be the same if it is just mutated rather than replaced entirely.

**Comment by tianhai82** [comment]
Ic. Thanks for the reply. Seems like I have no way to implement selectize as Vue directive to achieve changing options and items selected from parent vm.

**Comment by tianhai82** [comment]
From another issue. Not sure whether it's a bug.
http://jsfiddle.net/tianhai/uco50er6/3/
Click on "Change Selected" button. The value inside the array is changed. But the update() method in the directive is not triggered at all. "deep:true" is set in the directive.

**Comment by yyx990803** [comment]
@tianhai82 `update` is firing for me when clicking "Change Selected". Closing for now since the original issue has been explained by @simplesmiler.
