### ISSUE TITLE
orderBy failed when some item in the array don't have key

### ISSUE THREAD

**Issue by pandada8** [vuejs/vue#1923]
http://jsfiddle.net/pandada8/031shLq1/1/

maybe this worked on purpose……, then just close this issue.
BTW, if there is a value has same name with vusjs internel name, `$value` or  `$index` by example, what's the designed behavior ?

to reproduce: delete line 9 in js and the orderBy function normally

**Comment by yyx990803** [comment]
If the sub element is an array, `orderBy` doesn't traverse into it. This is working as intended.

Your object having properties like `$value` or `$index` is fine, because you have to access them via the `v-for` alias.

**Comment by pandada8** [comment]
I don't want orderBy to traverse into it, actually in a more general
situation orderBy would fail when the item don't have a sortkey, and I
think orderBy could be more robust to such situation.

Evan You <notifications@github.com>于2015年11月28日周六 上午12:11写道：

**Comment by yyx990803** [comment]
But what would you expect to be the desired behavior? Should items with no sortKey be always at top? At bottom? To me the best solution is just make sure your data is formatted consistently...

**Comment by pandada8** [comment]
fine……maybe we can make it more clear in the document
