### ISSUE TITLE
markdown editor inline (inside the textarea)

### ISSUE THREAD

**Issue by mstnorris** [vuejs/vue#1924]
Similar to this screenshot taken from [StackEdit.io](https://stackedit.io).

![imgur-2015_11_26-21:11:22](http://i.imgur.com/XIl2DqH.png)

I would like to render the markdown as you type. Is this something that I would be able to achieve, or something you'd be able to implement?

**Comment by DanGamble89** [comment]
Theres a very simple working example of this here: http://vuejs.org/examples/index.html

**Comment by yyx990803** [comment]
Please do not use issues to ask questions, as stated in the contribution guidelines.

**Comment by mstnorris** [comment]
@yyx990803 I can't ask this question on the forum as I can't verify my email address. I signed up with GitHub so my email address can never be verified. This is my email address that you've pulled in - **mstnorris@users.noreply.github.com**, although this isn't my GitHub account email address. Also, where are the contribution guidelines? A link would help.

@DanGamble89 Thanks, I have been using that, and similar thins, but that renders the markdown separately. I'm looking to render the markdown as you type, in the same textarea or div.

**Comment by yyx990803** [comment]
@mstnorris it's likely because you don't have a public email address in your GitHub account... I've deleted your account, maybe try signing up directly with your own email address.

The [contribution guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) are linked right above the input boxes when you open a new issue.

**Comment by mstnorris** [comment]
Thanks, I don't know how I missed those. I must have been in autopilot. Will sign up now!
