### ISSUE TITLE
Vue throws error if binding path is null

### ISSUE THREAD

**Issue by shredmaster** [vuejs/vue#1926]
I have a dynamic component which is activated when user clicks the reset button (this button set the currentForm = 'reset'). In the reset password component template, I display error message with data from ajax call. I have ajax call inside the activate hook. To my surprise, activate hook is invoked after compiled hook and also vue throws "Uncaught TypeError: Cannot read property 'alert' of undefined" because data is not ready. 

Why does Vue throws error if data is null? and also, shouldn't activate hook invoke before compiled hook? I thought it's a hook for incoming component to perform some asynchronous operation before it should be swapped in. 

I'm on 1.0.10. 
thanks in advance

```
// parent component template
components: {
        "reset": function (resolve) {
            require(['../forms/user.password.reset'], resolve)
        }
}

//html
component(:is="currentForm" keep-alive)
```

```javascript
//child component
{
 activate:function(done) {
        var self = this;
        restApi.getMessage()..done((data)=>{
            self.validCode = data.status === 'OK';
            self.$set("i18n", data.messages);
            done();
        }).fail(()=>{
        });
    }
}

// html
   .alert.alert-success(v-if="validCode")
        h3(v-text="i18n.alert.almost.there") Almost there...
```

**Comment by yyx990803** [comment]
`activate` is fired after the component is compiled and about to be inserted. Its purpose is to control the timing of the DOM manipulation. So the hook order is `compiled -> activate -> ready`.

Best practice for writing expressions with potential unset property is doing a conditional check:

``` jade
h3(v-text="i18n && i18n.alert.almost.there")
```

**Comment by shredmaster** [comment]
didn't know you can do that, that's easy. Could you explain why vue is designed to throw exception if expression binding contains null object?

**Comment by yyx990803** [comment]
It's not because it's `null`.

If you run this in js:

``` js
var a = null
var b = a.alert.almost.there
```

You get an error. Same for expressions in Vue templates.
