### ISSUE TITLE
vue js does not work with Internet Explorer 11

### ISSUE THREAD

**Issue by Pabloledesma** [vuejs/vue#1928]
I am declaring the library in the header and the browser does not recognize the script.
I tried to declare the end of the body but did not work either.

**Comment by yyx990803** [comment]
Show us the code please.

**Comment by yyx990803** [comment]
Closing (inactivity)

**Comment by mariomenjr** [comment]
Hello! I am new at Vue and I just made an implementation of Vue by a CDN link in a script (not using a package manager).

Everything works just fine in Chrome and FF but I just cannot make it work on IE I have already try the babel-polyfill thing but nothing worked.

index.html
![image](https://user-images.githubusercontent.com/1946936/34634139-fd2f272c-f235-11e7-80c9-4ed6ff7bbf72.png)

vue.js (controller)
![image](https://user-images.githubusercontent.com/1946936/34634151-0b28ba6e-f236-11e7-8bf2-09d3b617a39c.png)

When I open the console view of IE11 it seems that it deletes the #app div
![image](https://user-images.githubusercontent.com/1946936/34634164-32bbad2a-f236-11e7-889d-62d610b4869f.png)

Help please.

**Comment by JounQin** [comment]
@mariomenjr Then provide reproduce please.

**Comment by Akryum** [comment]
@mariomenjr Please use the [new issue tool](https://new-issue.vuejs.org/) to open a new issue.
