### ISSUE TITLE
v-for and v-else do not work together.

### ISSUE THREAD

**Issue by ryanmortier** [vuejs/vue#1930]
When using `v-else`, it doesn't seem to work when the sibling element is also using `v-for`.

I'm not sure if I'm just using it wrong (as in don't use it with `v-for`), or if this is an unintended result.

A workaround has been posted in the StackOverflow question linked below.

See the following:
StackOverflow: http://stackoverflow.com/questions/33963551/vue-js-v-show-and-v-else-not-working-as-intended
jsFiddle: https://jsfiddle.net/p2ycjk26/2/

```html
<table>
    <thead>
        <tr>
            <th>Heading</th>
        </tr>
    </thead>
    <tbody>
        <tr v-for="test in tests" v-show="tests.length">
            <td>{{ test.name }}</td>
        </tr>
        <tr v-else>
            <td>No data available in table</td>
        </tr>
    </tbody>
</table>
```

```javascript
new Vue({
    el: 'table',

    data: {
        tests: [{
            name: 'Testing'
        }, {
            name: 'Testing 2'
        }, {
            name: 'Testing 3'
        }]
    }
});
```

Actual output:
![image](https://cloud.githubusercontent.com/assets/2053960/11447358/f356ca70-9512-11e5-9bec-46cb3217ca30.png)

Expected output:
![image](https://cloud.githubusercontent.com/assets/2053960/11447365/052b4bfe-9513-11e5-8c94-6052baf05ee9.png)

**Comment by yyx990803** [comment]
v-for has higher priority than v-show, so the v-show is compiled inside
each v-for fragment. The v-else is outside that fragment and therefore
cannot connect. Just use a negation v-show instead.

**Comment by ryanmortier** [comment]
Thanks for clarifying.
