### ISSUE TITLE
HTML attribute ‘contenteditable’ can not bind data?

### ISSUE THREAD

**Issue by icarusion** [vuejs/vue#1936]
<div class="create_main_paragraph" contenteditable="true" v-model="test">

</div>

I test,it is not work, so ,is vue not support html attribute contenteditable?

**Comment by azamat-sharapov** [comment]
https://github.com/vuejs/vue/issues/1670

**Comment by icarusion** [comment]
@azamat-sharapov  @yyx990803 Is  binding event  a good way to solve it?

<div class="create_main_paragraph" contenteditable="true" v-on:keyup="set"></div>

**Comment by yyx990803** [comment]
Use a custom directive. http://vuejs.org/guide/custom-directive.html
