### ISSUE TITLE
how to rebind JQuery when array push?

### ISSUE THREAD

**Issue by z358z358** [vuejs/vue#1937]
http://jsfiddle.net/9pL4ftpu/1/

I use JQuery multiselect and v-for

when I push new item, I want to rebind multiselect item options.

I use watch, but it`s not work.

help , thx

**Comment by yyx990803** [comment]
[Please don't use issues for questions.](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines)
