### ISSUE TITLE
v-on shorthand `@` broken in html-minifier

### ISSUE THREAD

**Issue by lmk123** [vuejs/vue#1938]
When I use `<button @click="method">click me</button>` with [html-minifier](https://github.com/kangax/html-minifier)(or use [html-loader](https://github.com/webpack/html-loader) with `webpack -p`), it throw an error, then I change this to `<button v-on:click="method">click me</button>`, it works fine.

I think this isn't a bug, but maybe we can document it to save some time for other people who hit this issue?

Ref: [HTMLMinifier can't work with invalid or partial chunks of markup.](https://github.com/kangax/html-minifier#working-with-invalid-markup)

**Comment by posva** [comment]
The `@` doesn't make the HTML invalid. This looks like a bug on html-minifier. There is a `vue-html-loader` that (I believe) fixes this and other related issues

**Comment by lmk123** [comment]
@posva Thanks, I will try it!

**Comment by yyx990803** [comment]
If you are using webpack, use `vue-html-loader` instead of `html-loader`.

If you are using `html-minifier` alone, here's the option you need to make it work with Vue 1.0 templates: https://github.com/vuejs/vue-html-loader/blob/master/index.js#L69
