### ISSUE TITLE
bootstrap-select directive doesn't react with v-on

### ISSUE THREAD

**Issue by san4io** [vuejs/vue#1939]
Hey, I have following directive for bootstrap-select: 
```javascript
Vue.directive('selectpicker',{
    twoWay: true,
    deep: true,

    bind: function() {
        $(this.el).selectpicker().on("change", function(e) {
            this.set($(this.el).val());
        }.bind(this));
    },
    update: function (value) {
        $(this.el).selectpicker('refresh').trigger("change");
    },
    unbind: function () {
        $(this.el).off().selectpicker('destroy');
    }
});
```
The question is why Vue.js ignores v-on on my custom directive? Then I change option, searchAgreements not firing. 
```html
<select class="form-control"  v-selectpicker="filter.limit"  v-on:change="searchAgreements">
    <option value="20">20</option>
    <option value="50">50</option>
    <option value="100">100</option>
 </select>
```
Thanks in advance

**Comment by yyx990803** [comment]
Make sure you include jQuery **before** Vue so that Vue knows it needs to handle jQuery triggered events. jQuery `trigger` does not fire native events, so Vue detects for jQuery presence to listen to jQuery events. If you include jQuery after Vue, it won't work.

**Comment by san4io** [comment]
Well actually I'm including jquery before Vue, any other ideas?

global.jQuery = global.$ = require('jquery');

global.Vue = require('vue');
Vue.use(require('vue-resource'));

Vue.directive('selectpicker', require('./salestool/directives/selectpicker'));

**Comment by yyx990803** [comment]
I tested locally and it seems to work fine for me. If you are still having issue, please provide a live reproduction.

**Comment by san4io** [comment]
Yep, sorry. It seems that I was using old bootstrap-select plugin.
