### ISSUE TITLE
Question (should be implemented in docs as well)

### ISSUE THREAD

**Issue by Francismori7** [vuejs/vue#1940]
So I was looking around and didn't find what I was looking for.

My data contains an order's details as well as its order "lines", one for each line of the order. I need to find out how to add another line with its field in v-model instances. I tried unsuccesfully using `v-for="line in lines"` and then adding `v-model="product"` inside it. Then adding a button that pushes an empty object into the lines array.

It didn't work for me. Does that make sense or am I seeing this wrong?

**Comment by yyx990803** [comment]
[Please don't use issues for questions.](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines)
