### ISSUE TITLE
用v-for动态生成的div，绑定事件，如何获取当前的element？

### ISSUE THREAD

**Issue by icarusion** [vuejs/vue#1941]
@yyx990803  我知道你会中文，我就不吭哧英文了，哈哈！现在有这么个问题，我要用`v-for`动态生成一些可编辑的div，然后绑定keyup事件里，想获取当前的元素，怎样获得呢？
```
<article v-for="item in article">
    <div contenteditable="true" v-contentedit="item.content" v-on:keyup="handler($index)"></div>
</article>
```

**Comment by yyx990803** [comment]
`v-on:keyup="handler($index, $event)"` 然后获取 `event.target`。

另外，以后不要用 issue 问问题: https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by icarusion** [comment]
好的，初次使用，请见谅！

**Comment by amingRo** [comment]
感谢大神解答
