### ISSUE TITLE
请问如何绑定touch事件

### ISSUE THREAD

**Issue by hxqbeyond** [vuejs/vue#1943]
我使用的版本是v0.12.16，
v-on="touch: demo()"
v-on="touchend: demo()"
均无效

**Comment by yyx990803** [comment]
请给重现。

**Comment by cor** [comment]
Could someone translate this issue?

**Comment by francisfeng** [comment]
Roughly translation would be the following:
>
How to bind touch event?

>I am using v0.12.16 and both  `v-on="touch: demo()"` and `v-on="touchend: demo()"` wouldn't work.

**Comment by hxqbeyond** [comment]
我在测试vue1.0，配合vue-touch.js，事件中如下绑定：
<a href="javascript:;" v-touch="tap: test();">test</a>
会报这个错误：
Uncaught TypeError: Cannot read property 'indexOf' of null
in vue-touch.js
if (event.indexOf(gestures[i]) === 0) {
  recognizerType = gestures[i]
}
这样写也不行
<a href="javascript:;" v-on:tap="test();">test</a>,
然后再提个问题哈，vue的事件绑定是不是不支持触摸事件，一定要用vue-touch插件？

**Comment by yyx990803** [comment]
vue-touch 插件很久没更新了，目前不建议使用。
原生触摸事件当然是支持的，`v-on="touchstart: onTouchStart"` 应该是可以的，如果不行，请给重现。另外建议升级到 1.0。

**Comment by hxqbeyond** [comment]
Thank you very much.

**Comment by lxang** [comment]
vue-touch 今年又开始维护了吗？ 要监听tap, swipe等事件， 还有什么替代方案吗？

**Comment by limuran** [comment]
v-on="touchStart: onTouchStart"
