### ISSUE TITLE
Need more variables in inline statement

### ISSUE THREAD

**Issue by rhyzx** [vuejs/vue#1945]
~~Currently only `$event` variables is [provided](https://github.com/vuejs/vue/blob/d716ef46e781a4d65c71b2a1e94f6902ec14d7b4/src/directive.js#L232), and it represents the first argument this handler being called(DOM events in most case). But it is not suitable for custom vm events, especially with multi arguments.~~

eg.
```js
// parent
<my-component v-for="item in items" @my-event="handle($index, /* i want 'bar' here */)"></my-component>

// child
this.$emit('my-event', 'foo', 'bar')
```

I suggest add a more flexible variable(such as `$` or `$$`) to represents all arguments, so we can get any argument by `@my-event="handle($[0], $[1])"`.

For convenient, we can provide `$0` - `$9` to represents corresponding arguments like [Bash](http://tldp.org/LDP/abs/html/othertypesv.html#POSPARAMREF1).

@yyx990803 , if you agree with me and think this is necessary, please let me pull a PR for this :trollface:

**Comment by rhyzx** [comment]
Well, after a researching of src codes, i found there is no variable(even `$event`) [provided](https://github.com/vuejs/vue/blob/dev/src/instance/api/data.js#L25) for custom events.

**Comment by yyx990803** [comment]
Thanks, I think something like `$arguments` is more explicit. What we need to do is basically wrap the `handler` here: https://github.com/vuejs/vue/blob/dev/src/instance/internal/events.js#L41 - before calling the handler, we set `$arguments` on the current scope, and reset it afterwards.

**Comment by rhyzx** [comment]
got it

**Comment by Rolanddoda** [comment]
Does `$arguments` still exists in the template ? Bc I am trying to access it but it doesn't work. I am using a library which returns 2 arguments .

If I do:
```
<lib-component
    @some-event="$emit('some-event', $event)"
>
</lib-component
```

It catches only the first argument. So somehow I need to catch all events and seemed that $arguments is the best solution.

**Comment by Rolanddoda** [comment]
Oh Ok I found that $arguments do not exists but `arguments` without $ sign exists.
