### ISSUE TITLE
inconsistent :class binding behavior in IE9

### ISSUE THREAD

**Issue by pkawiak** [vuejs/vue#1946]
Hello,

I am creating component using following markup as template:
```
<div :class="{'inner-class': true}">Stuff<div>
```

Then I am using this component as follows:
```
<my-component class="outer-class"></my-component>
```

I would expect to see ```<div class="inner-class outer-class">``` as a result and it's true for modern browsers. Unfortunately on IE9 (real one, not emulated mind you) ```class``` is empty.

Live demo: http://jsfiddle.net/pkawiak/fLxbokth/

Is t a bug or am I missing something?

**Comment by crswll** [comment]
Just out of curiosity what happens if you do `v-bind` instead of `:`?
