### ISSUE TITLE
suggest: methods like '$appendTo' work with component instance

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#1947]
like:

    var Alert = require('component/alert/alert')
    module.exports = function(message) {
        var vm = new Alert({})
        vm.$appendTo('body')
        vm.message(message)
    }

now, component instance can't directly $appendTo DOM, report ` el is null`
so i must do like this:

    var Alert = require('component/alert/alert')
    module.exports = function(message) {
        var vm = new Alert({})

        vm.$mount(document.createElement('div'))
        vm.$appendTo('body')
        vm.message(message)
    }

suggest: vm can directly $appendTo DOM

**Comment by yyx990803** [comment]
This is the cost to pay if you are using the imperative APIs. Note you can omit the div in `$mount` (an empty div will be created for you) and chain it:

``` js
new Alert().$mount().$appendTo('body').message(message)
```

**Comment by ccqgithub** [comment]
ok，tks
