### ISSUE TITLE
Compatibility with linters's rules "no-new" and "no-undef"

### ISSUE THREAD

**Issue by arianrhodsandlot** [vuejs/vue#1948]
I'm using ESlint for code linting. When my Vue code goes like this:
```js
var demo = new Vue({
  el: '#demo',
  data: {
    message: 'Hello Vue.js!'
  }
})
```
The linter will say "`demo is defined but unused`" because of [this](http://eslint.org/docs/rules/no-undef.html).

But if I write:
```js
new Vue({
  el: '#demo',
  data: {
    message: 'Hello Vue.js!'
  }
})
```
The linter will say "`do not use 'new' for side-effects`" because of [this](http://eslint.org/docs/rules/no-new.html).

It's okay if I can add an config file for the linter to my project. But when it comes to using an unconfigable linter, like [Standard](http://standardjs.com/), the error will always be shown.

Is there any way to avoid this, or a new method in further versions? Like:
```js
Vue.create({
  el: '#demo',
  data: {
    message: 'Hello Vue.js!'
  }
})
```

**Comment by yyx990803** [comment]
That is not Vue's concern if you are using an unconfigurable linter. You can just create that method yourself:

``` js
Vue.create = function (options) {
  return new Vue(options)
}
```

**Comment by simplesmiler** [comment]
You can always avoid warning by exporting the variable.
