### ISSUE TITLE
Suddenly i've discovered hidden? feature with class bindings

### ISSUE THREAD

**Issue by fobdy** [vuejs/vue#1950]
And it's very cool, here it is:

```html
<div v-bind:class="{ [type]: true }"></div>
```
`type` is component prop/variable

I think it's need to be documented!

**Comment by yyx990803** [comment]
Thanks, but this only works if the browser supports ES6 computed property names. This is not a Vue feature and it will not work in old browsers.

**Comment by fobdy** [comment]
Maybe `vue-loader` can transpile these expressions for us?

02.12.2015, 17:43, "Evan You" <notifications@github.com>:
> Closed #1950.
> 
> —
> Reply to this email directly or view it on GitHub.

-- 
С уважением,
Николай.

**Comment by yyx990803** [comment]
It's possible, but not very easy because babel turns this into very complex code.

**Comment by OEvgeny** [comment]
@yyx990803 Just curious. Can we detect if ES2015 is supported and than add some extra-logic to the parser to emulate this behaviour in old browsers? 

Not sure that it should be implemented through.

**Comment by fobdy** [comment]
I didn't carefully study the docs, it turns there is special [array syntax](http://vuejs.org/guide/class-and-style.html#Array_Syntax) for that
