### ISSUE TITLE
如果template内容非常多，该如何做？总不能真的这样拼字符串吧

### ISSUE THREAD

**Issue by lcsoftware** [vuejs/vue#1951]
var Example = Vue.extend({
  template: '<div>{{ message }}</div>',
  data: function () {
    return {
      message: 'Hello Vue.js!'
    }
  }
})

在官方的网站上就是找不到说明！

**Comment by hbrls** [comment]
这个？ http://vuejs.org/guide/application.html#Single_File_Components

**Comment by yyx990803** [comment]
学会用构建工具。
