### ISSUE TITLE
Parent component activate hook can't be used in conjunction with child required props.

### ISSUE THREAD

**Issue by BrendanNeufeld** [vuejs/vue#1952]
When using 'activate' hook on a parent component, the child components will throw vue errors/warnings if they have required props. For example the parent is doing some async data fetching which resolves the activate hook once loaded. Any child that has a 'required' prop dependant on that data prior to the 'activate' hook being resolved will throw a vue error.

I am not sure that this is a bug as this makes logical sense based off 'activates' description but this does make async loading and required props a little difficult to deal with.

**Comment by yyx990803** [comment]
You can add `v-if` on the child components so that they only get instantiated after your data is fetched. This behavior is unlikely to change in the short term since it's potentially breaking.
