### ISSUE TITLE
How to use this.$http.post syncronously, not async?

### ISSUE THREAD

**Issue by Danjavia** [vuejs/vue#1954]
I maked a post request for get data and replace the data into vue. But when  I run the code the vue instance not change their data still after a time.

**Comment by yyx990803** [comment]
You should avoid synchronous HTTP requests, because it hangs your UI while waiting: http://blogs.msdn.com/b/wer/archive/2011/08/03/why-you-should-use-xmlhttprequest-asynchronously.aspx

**Comment by Danjavia** [comment]
Yes but i need set the object and use it after setted. but how isn't sync the object pass the previous data and no the setted data

**Comment by yyx990803** [comment]
I don't think I understand what you mean...
