### ISSUE TITLE
Null is not treated as Object in component prop check

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue#1961]
I have a component that let's user select an object from an array.
```
<comp :selected.sync="selectedObject">
// parent data
data: {
    selectedObject: null
}
// comp prop
props: {
    selected: {twoWay: true, type: Object}
}
```

and in parent template I have something like
```html
<div v-if="selectedObject"> blah blah blah </div>
<div v-else> please select an object </div>
```
which displays different content based on whether an object is selected.

and I get
```
[Vue warn]: Invalid prop: type check failed for selected="selectedObject". Expected Object, got Null.
```

I know i can just remove the "type: Object" check and suppress the warning,
but wouldn't it be better if component props checks treat null as an object?

Because javascript does that (typeof null === 'object'),
and setting null as an initial value (to my knowledge) doesn't affect mutation observation.

**Comment by yyx990803** [comment]
It fails because `null` is not an Object... the `typeof` behavior is commonly considered a bad design in the JavaScript language itself.

Just initialize it to an empty object.

**Comment by fnlctrl** [comment]
Initializing with an {} will cause it to evaluate to true.. which means I'll have to create another variable to store whether an object is really selected.
I'll just remove the type check then..

**Comment by lsbyerley** [comment]
@fnlctrl you just need to change it to `v-if="Object.keys(selectedObj).length > 0"`

**Comment by dulowski-marek** [comment]
@fnlctrl Which is a workaround, where either using such an exaggerated expression in template or writing a getter for each object to check if it is initialized seems not right.

Using Typescript with Vue complicates this even more, as one has to denote all objects as `Partial<T>` or `T | {}` for that approach to work. 

What is the status of this issue in upcoming 3.0 release?

**Comment by vannitotaro** [comment]
Another workaround is to define a custom validator:
https://github.com/vuejs/Discussion/issues/374#issuecomment-137981959

Anyway something Vue-native like `type: [Object, null]` would be really useful to handle `value` prop of `v-model` in input-like components with direct mapping with server-side model field when the field accept null value (for example a date picker with date not required).

**Comment by Christhofernatalius** [comment]
So, the documentation means by **any type** is not actually any type?
![image](https://user-images.githubusercontent.com/13524958/51589558-f8c7d500-1f19-11e9-9442-9dff3b16b9e7.png)

**Comment by Flamenco** [comment]
When using Typescript, I have no way to specify `string | null`.

My use-case is a filter that sets the value to null when cleared.
I know the workaround is to transform the null value to a string
before sending the prop to the component, but I _should not have to do that_.

Ideally, one of these would be the syntax:
```js
{type: [Null,String] as () => string | null}
{type: Any as () => string | null}
{type: [Object,String] as () => string | null} // with null considered an object
```

## Dead Ends

```js
// This will not work because 'Null' is not a type
{type: [Null,String] as () => string | null}
```

```js
// This will not work because 'Any' is not a type
{type: Any as () => string | null}
```

```js
// This will not work because null is not considered an Object, although is should be
{type: [Object,String] as () => string | null}
```

```js
// This will not work because string is not considered an Object
{type: Object as () => string | null}
```

So I end up doing this, and the Typescript value is now undefined instead of `string | null`
 ```js
{
      validator: prop => typeof prop === 'string' || prop === null,
      required: true,
 }
```

**Comment by dimitor115** [comment]
@Flamenco 
I am using some kind of workaround:
```typescript
props: {
    status: {
      type: String as PropType<SomeType | null>,
      default: null
    }
  }
```
The typescript compiler understand `this.status` as `SomeType` or `null` however vue doen't have problems with passing null via prop.

**Comment by yann-yinn** [comment]
I know people didn't like the first answer https://github.com/vuejs/vue/issues/1961#issuecomment-162007987 but this is not so bad actually : when calling your component, you can fill your prop this way, to make sure this is an object:

```js
<CoachingSidebarCheckout :coaching="coaching ? coaching : {}" />
```

And then in your component, you can use a  custom function like "isEmptyObject" (https://stackoverflow.com/questions/679915/how-do-i-test-for-an-empty-javascript-object?answertab=votes#tab-top) or use `_.isEmpty({})` from lodash 

```js
 <template v-if="!isEmptyObject(coaching)"> ...
```

At least your components props type declaration still makes sense 

```
  props: {
    coaching: {
      type: Object,
      required: true
    }
  },
```

Allowing "null" leads to strange declaration, where a prop might be "required" but a "null" value is accepted...

```js
  props: {
    coaching: {
      type: null, // will accept also an object
      required: true
    }
  },
```

At the end, you can also bypass type validation and just declare props this way : 

```js
  props:: ['coaching']
```

**Comment by Volmarg** [comment]
Sadly this problem still exists. What's more annoying is the error saying. `got Null` (first letter is uppercase) but there is only `null`.

**Comment by mspoulsen** [comment]
I think the key here is to use a default value of null:

```javascript
foo: {
      type: (Object as () => Foo) || null,
      default: null,
    },
```

This works for me. If I use "required" instead of "default" I get the error mentioned above.

**Comment by GordonSo** [comment]
Exactly as @dimitor115 and @mspoulsen said. 
Also removing the `required: true` setting is necessary.

**Comment by rgrignon1** [comment]
I don't know why is this issue closed and have never been reopened since it has never been fixed.

Setting a default value as null is not the same as explicitly requiring a value that could still be null. Forcing a default value and removing the `required` param setting is a weak workaround at best and at worst it just doesn't work at all, especially without typescript.

It's a great issue when you need a dynamic prop that is updated often and could be set to null, like a selection component, which is a pretty common use case that has been mentioned by others and is also mine.

**Comment by plehnen** [comment]
https://github.com/vuejs/core/issues/3948
