### ISSUE TITLE
slot in "select" doesn't work 

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue#1962]
Hi,

I have a component (i-select) template like the following:
```
  <div class="select-label">
    {{value ? value : '请选择'}}
    <select v-el:select v-model="value">
      <slot></slot>
    </select>
  </div>
```

And the parent template use this component like the following:
```
<i-select :value.sync="selectedValue">
  <option>AL</option>
  <option>CA</option>
  <option>IL</option>
</i-select>
```

The content cannot be inserted into the slot somehow. If I move the slot out of the select, everything works just fine.

**Comment by OEvgeny** [comment]
According to html5 spec ``slot`` is not allowed in ``select`` tag.

**Comment by yyx990803** [comment]
This is expected, similar to how you cannot use `<slot>` in `<table>`.

**Comment by Milewski** [comment]
okay then whats the solution for this? how to dynamically add the options in an select?

**Comment by miljan-aleksic** [comment]
@Milewski, the select options should be created with `v-for` directive reading the data from a prop or local. Read the doc Guide form section for examples and if you still have questions please address them on the forum or chat.
