### ISSUE TITLE
Support of jQuery .data() method when binding data- attribute

### ISSUE THREAD

**Issue by kerbylav** [vuejs/vue#1963]
Yes, I understand that it is jQuery 'feature' when it does not update its internal data array once data- attributes are changed on element. But it breaks expected reactivity when binding with data- attributes.

It changes .data() storage for the first time but futher changes doesn not have any effect

http://jsfiddle.net/m8nkzp9u/1/

**Comment by AlexandreBonaventure** [comment]
It's not an issue.
Please read : https://api.jquery.com/jquery.data/

Here's the line that should help you understand : 
Regarding HTML5 data-* attributes: This low-level method does NOT retrieve the data-* attributes unless the more convenient .data() method has already retrieved them.

Here's is a working fiddle (with $.data() you have to set explicitly an item so you can retrieve the same value):
http://jsfiddle.net/m8nkzp9u/2/

**Comment by kerbylav** [comment]
@AlexandreBonaventure I explicitly stated that I *know* that it is jQuery 'feature'. My point that it is unclear and unexpected behavoir and Vue is all about simplicity and clean way of handling data bindings. There are alot of possible solutions but all of them are just workarounds and not... umm.. natural way, considering how often people use jQuery with Vue.

**Comment by yyx990803** [comment]
This is really more jQuery's issue rather than Vue's. The "unexpected-ness" comes from how jQuery works, rather than how Vue works, it doesn't make sense to change Vue because of jQuery's unexpected behavior.

**Comment by simplesmiler** [comment]
@kerbylav if you already have the data in the viewmodel, why would you want to give it a roundtrip though the DOM? There is probably a better way to achieve what you are trying to achieve.

**Comment by kerbylav** [comment]
@simplesmiler There are jquery libs which uses data mechanism to keep options, states and stuff for components, for example http://getbootstrap.com/javascript/#tooltips-options 

So it would be great to have easy and clean way to bind such data dynamically.

@yyx990803 Yes, of course it's jQuery issue, but still implement and re-implement similar behaviour is quite frustrating. What would you suggest to keep things done in reusable way? Some kind of custom directive perhaps?

**Comment by simplesmiler** [comment]
@kerbylav I'm afraid most jQuery plugins are not designed to be reactive-friendly. jQuery does not standardize the data flow, so in general you have to write a custom directive / component (or few) per jQuery plugin.

**Comment by arthurkirkosa** [comment]
@kerbylav If your interested in Bootstrap Tooltips check http://yuche.github.io/vue-strap/#tooltip

Maybe some info there will help.

**Comment by David-Bascom** [comment]
Had a similar problem and solved it with a jQuery-plugin that can rebuild / refresh the jQuery.data()-cache after VueJS makes changes to the data-attribute:

[http://labor.99grad.de/jquery-rebuild-data-data-attribut-erneut-parsen-einlesen/](http://labor.99grad.de/jquery-rebuild-data-data-attribut-erneut-parsen-einlesen/)
