### ISSUE TITLE
Property of object without explicit initialisation in constructor does not become 'reactive'

### ISSUE THREAD

**Issue by pamtbaau** [vuejs/vue#1968]
I assign an array of Task objects to Vue.data. When an instance property of Task is not being set in/by constructor, Vue will not attach setter/getter functions. Is this by design?

In the following case, `show` will  not be 'reactive':

    class Task
         name: ''
         isRunning: false
         show: true
     
     constructor: (@name, @isRunning = false) ->

Below, `show` is being set explicitely in the constructor and will be 'reactive'

    class Task
        name: ''
        isRunning: false
        show: true

        constructor: (@name, @isRunning = false, @show = true) ->

Vue creation:

    class ViewModel
        search: ''

        constructor: (@view, @tasks, controller) ->
            allowUnsafeNewFunction =>
                @vm = new Vue
                    el: @view
                    data: {
                        'tasks': @tasks # Array of Tasks
                        'search': @search
                    }
                    methods: controller
                    watch: {
                        'search': @searchTasks
                    }

NB, local `search` property is not being set explicitely in in/by constructor either, but is reactive nontheless.

**Comment by yyx990803** [comment]
Vue observer ignores prototype properties, this is by design.

**Comment by pamtbaau** [comment]
But why then is `search` reactive. It is not set either...

**Comment by yyx990803** [comment]
Because it's initialized in `data`. Please read http://vuejs.org/guide/reactivity.html
