### ISSUE TITLE
Vue+Vue-Router，组件切换后jquery和jquery的自定义滚动条失效。

### ISSUE THREAD

**Issue by Lxxyx** [vuejs/vue#1969]
## 开发环境
Vue+Vue-loader+Vue-Router+Jquery+perfect scroll/jquery
## 问题
因为项目需要，必须引进jquery和perfect scroll/jquery这两个组件。在使用vue-router时候，载入首页时可以完成dom操作的，但是使用vue-router进入另外一个组件，切换回来时。perfect scroll/jquery和jquery控制部分就会失效。
这是引用perfect scroll这个插件的代码，需要直接控制dom.
scroll.vue的源代码
```
<script>
	var $ = require('jquery');
	require('perfect-scrollbar/jquery')($);
	require('../../../../lib/perfect-scrollbar.min.css');

	$(".view-danamic").perfectScrollbar(
		{
			wheelSpeed:7,
		}
	);
	$(".notice").perfectScrollbar();
</script>
```
![qq 20151205183355](https://cloud.githubusercontent.com/assets/13161470/11607372/c1fc7b9c-9b7e-11e5-8c33-16f590863eb8.jpg)
组件切换回来后
![qq 20151205183418](https://cloud.githubusercontent.com/assets/13161470/11607379/d41c9c4e-9b7e-11e5-8479-521bf25a70ea.jpg)

切换回来时候无论在vue组件或者router的哪个生命周期中添加对scroll.vue的引用，都不起作用了。

**Comment by yyx990803** [comment]
组件内部的代码只在加载时执行一次，你想要在组件被实例化的时候执行代码要用组件本身的生命周期钩子。
