### ISSUE TITLE
Why not add v-on:doubleClick

### ISSUE THREAD

**Issue by bohanyang** [vuejs/vue#1971]
A double click event?

**Comment by yyx990803** [comment]
You can use any native event, e.g. `v-on:dblclick`.

**Comment by bohanyang** [comment]
Thanks.

**Comment by hqxluoyang** [comment]
v-on:dblclick 

Still wrong

**Comment by eljefedelrodeodeljefe** [comment]
For reference with Vue 2 it should be : `v-on:dblclick.native`

**Comment by fnlctrl** [comment]
^ Note: `.native` is only necessary when binding native events on components
```
// components
<foo v-on:dblclick.native ="doBar"/>
// normal elements
<div v-on:dblclick="doBar"/>
```

**Comment by seansio1995** [comment]
nice

**Comment by clearlivings** [comment]
i has inpute dbclick,solve my problems----dblclick!!

**Comment by clearlivings** [comment]
thanks
