### ISSUE TITLE
JS question: listen object property change

### ISSUE THREAD

**Issue by MikhailTatsky** [vuejs/vue#1973]
I am sorry for silly question.
I only start learn view.js
How did you do this?

"The data and the DOM are now linked, and everything is now reactive. How do we know? Just open up your browser developer console and modify exampleData.name"

I was very suprised.
Do you use Observe from ECMAScript 7 ?

**Comment by posva** [comment]
http://vuejs.org/guide/reactivity.html
Use the forums for questios http://forum.vuejs.org/ :smile:

**Comment by yyx990803** [comment]
^
