### ISSUE TITLE
Async problem while passing property into child component

### ISSUE THREAD

**Issue by NaderIkladious** [vuejs/vue#1974]
I have two component (grid) is the parent which contain an array of emotions which use v-for to initiate multiple (emotion) component.

fight is a computed property that depends on data from the data property using AJAX

```html
<ul class="list" v-for="list in fight">
      <li class="emotion" v-for="item in list">
        <emotion :emotion=item></emotion>
      </li>
    </ul>
```

this is the emotion component
```html
<template id="emotion">
  <a  href="" :class="{'selected': selected}" v-text="emotion.name"></a>
</template>
```

```javascript
module.export = {
  props: ['emotion']
}
```

errors I receive in console

```
[Vue warn]: Error when evaluating expression "emotion.name". 
VM54101:3 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined(…)
```

I require the emotion component (child) in the parent component, which seems to be rendered before it has data to work with.

Thanks in advance.

**Comment by yyx990803** [comment]
Hmm, `<emotion>` should not be rendered if `list` is empty. Can you add `{{ list | json }}` and see what value it has?

**Comment by yyx990803** [comment]
Better yet - create a repro if possible.

**Comment by NaderIkladious** [comment]
Thanks for the prompt response

The problem was a typo

```module.exports``` instead of ```module.export```

Thanks so much
