### ISSUE TITLE
Adding transition to component breaks v-show/v-if

### ISSUE THREAD

**Issue by DanGamble89** [vuejs/vue#1976]
I have a fiddle here: http://jsfiddle.net/oe7axeab/125/

If you remove L17 in the html like so: http://jsfiddle.net/oe7axeab/126/ it works fine. Is there something stupid i'm missing? I'd like to be able to transition each tab change but atm `v-show` doesn't seem to work and the end state of the transition seems to persist on the non active tabs.

If you change the `v-show` to `v-if` (http://jsfiddle.net/oe7axeab/127/) then it seems to get worse and the DOM just seems to get each active item added to it instead of removing it when it becomes inactive as well

**Comment by posva** [comment]
Remove the `opacity: 1` in transition-fadein. This is an updated example. Not perfect. http://jsfiddle.net/6w1L05v8/
My guess is that you should use the v-if in the component `tab` itself. I'm creating another jsfiddle to illustrate it

**Comment by DanGamble89** [comment]
That still leaves the problem of the `<Tab>` stacking due to the inactive ones not being removed from the flow of the document. The `height: 0` kind of fixes it but it jumps when you go from 2 or 3 back to 1

**Comment by posva** [comment]
It works on chrome though. I've got some urgent things to do right now, I'll come at you later if nobody find a solution. Sorry :(

**Comment by DanGamble89** [comment]
I'm using Chrome as well and this is what i get: http://gfycat.com/ForkedDeliriousCockatiel

Your solution does seem to help though as i kind of understand why it's doing it but i would have thought it would do it when the `activeIndex` increased as well as decreases instead of just when it decreases..

**Comment by yyx990803** [comment]
This is actually a CSS specificity gotcha: `fadein-transition` is always present, and because you put it after `fadein-enter` and `fadein-leave`, it will be overriding them all the time. If you adjust the CSS rules order it would work properly :)

**Comment by DanGamble89** [comment]
Wow, and i call myself a Frontend dev.. Such a basic thing. Thanks for the quick close :D
