### ISSUE TITLE
$broadcast in data or activate hook not working

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue#1977]
Codepen: http://codepen.io/sztrzask/pen/zrxvew

Events are an empty collections during activate or data phase - $broadcast or even $emit is not working during data and activate hooks. I didn't found any information suggesting this is by design - and I don't think it should be.

**Comment by yyx990803** [comment]
Why would you `$broadcast` inside `data`? It's not a lifecycle hook. Also, `activate` is only called when you switch between dynamic components. It's used to control the timing of DOM manipulations.

`$boradcast()` would only work **after** the component has compiled its content (and therefore created its children), so it would only work in `compiled` or `ready`.

**Comment by sztrzask** [comment]
Turns out the `data` and `activate` I was `$broadcasting` in is part of vue-router transition pipeline, not vue. Sorry for the chaos.
