### ISSUE TITLE
$broadcast description in Api is misleading

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue#1978]
``Broadcast an event that propagates downward to all descendants of the current instance. ``

should be

``Broadcast an event that propagates downward to all immediate descendants of the current instance.`` 

as the _eventsCount only returns immediate descendants' events

``Vue.prototype.$broadcast = function (event) {  if (!this._eventsCount[event]) return; ...``

optionally - there's a bug that makes _eventsCount return only immediate descendants' events :)

**Comment by yyx990803** [comment]
`_eventsCount` is [recursively updated along the parent chain in `$on`](https://github.com/vuejs/vue/blob/dev/src/instance/api/events.js#L15).

**Comment by sztrzask** [comment]
Could you please update the `$broadcast` description to note that broadcasting is not available before the `ready` event?

**Comment by yyx990803** [comment]
You can submit a PR to the vuejs.org repo.
