### ISSUE TITLE
Shorthand syntax of component definition is not properly working

### ISSUE THREAD

**Issue by CrazyUmka** [vuejs/vue#1979]
When using shorthand syntax only the first one of several sequentially defined components is rendered.

Example:
```html
<style><style>
<template>
  <hello />
  <world />
</template>
<script type="text/babel">
export default {
  components: {
    hello: {
      template: '<div>Hello</div>'
    },
    world: {
      template: '<div>World</div>'
    }
  }
}
</script>
```
Result: only the first component <hello/> rendered, component <world/> is ignored.

**Comment by posva** [comment]
Have you tried using a parent div like this:

```html
<div>
  <hello />
  <world />
</div>
```

(http://vuejs.org/guide/components.html#Fragment_Instance)

**Comment by yyx990803** [comment]
This is because HTML5 does not support auto-closing tags. Always close your
custom elements.

**Comment by CrazyUmka** [comment]
Okay, i should use this <hello></hello> instead <hello />, right?

**Comment by yyx990803** [comment]
yes
