### ISSUE TITLE
请问为什么双向过滤 修改后面的值 model没变化?

### ISSUE THREAD

**Issue by huqiliang** [vuejs/vue#1984]
请问为什么双向过滤修改后面的值 model没变化 而官网的demo上为什么会联动?

官网：http://vuejs.org/guide/custom-filter.html#Two-way_Filters
我的demo地址 ： https://jsfiddle.net/bhnddowinf/qwLfcu3x/1/

希望能指出我哪里写错了 或者怎么解决这样的问题

谢谢

**Comment by huqiliang** [comment]
sorry 已经解决了 是自己想错了 请关闭

**Comment by xiaolongyuan** [comment]
不要在这里贴问题  问题上论坛或者segmentfault.com

**Comment by yyx990803** [comment]
解决了自己也可以关...
