### ISSUE TITLE
Vue multiple checkbox

### ISSUE THREAD

**Issue by pyaesone17** [vuejs/vue#1986]
There is a bug using vue checkbox. I used like this from documentation but when i check on one button vue automatically select all other items too
```html
<input type="checkbox" id="jack" value="Jack" v-model="checkedNames">
<label for="jack">Jack</label>
<input type="checkbox" id="john" value="John" v-model="checkedNames">
<label for="john">John</label>
<input type="checkbox" id="mike" value="Mike" v-model="checkedNames">
<label for="mike">Mike</label>
<br>
<span>Checked names: {{ checkedNames | json }}</span>
```

**Comment by Nirazul** [comment]
Is your checkedNames variable an array?
Show the vue code, please.

**Comment by pyaesone17** [comment]
Thank you . I forgot to set this on Vue instance.

**Comment by azamat-sharapov** [comment]
But it docs, it's not working for me: http://vuejs.org/guide/forms.html#Checkbox

**Comment by yyx990803** [comment]
I assume the original issue has been resolved - reopen if not.
