### ISSUE TITLE
el move to another place unexpectedly after vm created

### ISSUE THREAD

**Issue by craynic** [vuejs/vue#1989]
http://jsfiddle.net/c99wgmjb/
I put `<tr>` in `<tbody>`, but after vm created they have been moved in `<body>`. Why it behave so?

**Comment by Nirazul** [comment]
`<div>` can't live within a `<tbody>` element. It gets thrown out by the browser police as soon as the dom is parsed.

**Comment by yyx990803** [comment]
^ what @Nirazul said
