### ISSUE TITLE
Add Vue to jsdelivr

### ISSUE THREAD

**Issue by lithiumjake** [vuejs/vue#199]
It would be awesome if Vue were available on jsdelivr (https://github.com/jsdelivr/jsdelivr), the CDN run by Mozilla.  I could do it, and keep it up-to-date, if you give the thumbs up. If you would like me to handle it, the only question I would have is would you prefer it to be added as vue, vuejs, or vue.js?

**Comment by greenify** [comment]
sorry to be annoying - is there a reason why new versions aren't pushed to jsdelivr?

**Comment by yyx990803** [comment]
@greenify we didn't set up auto updating there. You can use it from cdnjs though.
