### ISSUE TITLE
[suggestion] Allow to control $dispatch whether to trigger on self or not

### ISSUE THREAD

**Issue by Lin-H** [vuejs/vue#1990]
When I use recursive component to build a Tree component, I want All the leaf nodes to dispatch an event with its data to the upper node, so I can get the whole data of tree from its root node. But when I wrote
```js
events: {
    returnData: function(dataFromChildren) {
        this.model.children = dataFromChildren;
        this.$dispatch('returnData', this.model);
    }
}
```
it just keep triggering itself and crush. Although I can use two way binding.
So, my advice is to add a param to $dispatch to control whether to trigger on self or not. Somthing like
```js
this.$dispatch(false, 'returnData', this.model);
```
which the problem can be solved.
By default $dispatch still triggers on self(omit or set `true`). So it should be compatible.
Please consider it.
I have implement it, if it's OK, I can submit a PR, thanks.

**Comment by yyx990803** [comment]
Well, first of all this doesn't sound like a good idea - I would suggest you take a look at [vuex](https://github.com/vuejs/vuex) for a cleaner state management solution.

Second, it should be simple to do it yourself:

``` js
events: {
    returnData: function(dataFromChildren) {
        if (this.__dispatching) return
        this.__dispatching = true
        this.model.children = dataFromChildren;
        this.$dispatch('returnData', this.model);
        this.__dispatching = false
    }
}
```
