### ISSUE TITLE
Chrome plugin mode not support

### ISSUE THREAD

**Issue by awesomes-cn** [vuejs/vue#1991]
My `index.html`  is:
```html
<div id="app">
    <h1>{{name}}</h1>
</div>
```

 ```js
 new Vue({
  el: '#app',
  data: {
    name: "hxh"
  }
 })
```

I can run this directly in browser.

Now I am developing a chrome plugin,and I use it:
```js
"chrome_url_overrides": {
  "newtab": "index.html"
}
```

but this not work,just show:
```html
<div id="app">
      <h1></h1>
</div>
```
So, is vue.js use some feature that not supported in chrome plugin mode?

**Comment by azamat-sharapov** [comment]
Are you using [CSP](https://github.com/vuejs/vue/releases/tag/1.0.10-csp) version?

**Comment by yyx990803** [comment]
See above - you need to use the CSP build for Chrome apps.

**Comment by awesomes-cn** [comment]
Thanks
