### ISSUE TITLE
Escaping custom tag as vue component

### ISSUE THREAD

**Issue by sohelamin** [vuejs/vue#1993]
Hey,

I want to ignore a custom tag eg: <my-tag></my-tag> to treat or count as a vue component.
How can I do that?
It is giving warning now.

Is there any way to change commonTagRE as below
```
commonTagRE = /^(div|p|span|img|a|b|i|br|ul|ol|li|h1|h2|h3|h4|h5|h6|code|pre|table|th|td|tr|form|label|input|select|option|nav|article|section|header|footer|my-tag)$/;
```
Or it can be done via Vue.util.extend() ?

**Comment by yyx990803** [comment]
Are you trying to use a native element as a Vue component? If that's the case - you shouldn't, that's why there's a warning.

**Comment by sohelamin** [comment]
No I was trying with a custom element "<trix-editor>" and that causing the warning.
Is there any way to ignore or escape the warning for a tag (if I set in config) ?

**Comment by yyx990803** [comment]
There's currently no built-in mechanism for that - however you can register an empty elementDirective:

``` js
Vue.elementDirective('trix-editor', {})
```

This also makes Vue skip any content inside that element.

**Comment by sohelamin** [comment]
Thanks a lot @yyx990803 we're all planned to use VueJs in our company (wedevs.com)[wedevs.com]
It's really cool and simpler thing you've made.
