### ISSUE TITLE
[Feature] Passing props to partials

### ISSUE THREAD

**Issue by nilssolanki** [vuejs/vue#2004]
As far as I understand partials, the scope of variables inside a partial is that of its surrounding component:

    Vue.partial('my-partial', '<p>This is a partial! {{msg}}</p>')

    <my-component>
        <partial name="my-partial"></partial>
    </my-component>

In this case, `{{ msg }}` would be part of the data of `my-component`, right?

**Passing props to partials**

I would find it really useful to be able to pass props directly to a partial:

    Vue.partial('my-partial', '<p>This is a partial! {{msg}}</p>')

    <my-component>
        <partial name="my-partial" msg="My Message"></partial>
    </my-component>

**Reasoning**

We often use partials for functionless snippets such as svg icons, but we need to be able to pass in different values. And using components in this case seems like too much. Example:

    Vue.partial('my-partial', '<svg class="icon"><use v-bind="{ 'xlink:href': '#' + svgName }"></use></svg>')

    <my-component>
        <partial name="my-partial" svgName="okay"></partial>
        <partial name="my-partial" svgName="cancel"></partial>
    </my-component>

I'm sure that there are plenty of use-cases. What do you think?

**Comment by yyx990803** [comment]
The while point of partials is that they are scope-less (i.e. evaluated in surrounding scope). If you want prop passing, use dynamic components.
