### ISSUE TITLE
Clear way to contribute to Wiki

### ISSUE THREAD

**Issue by rodzzlessa24** [vuejs/vue#2005]
Hey guys I was trying to add a skeleton application I created to the `User Contributed Components & Tools` However I have not figured out how I can add it since forking the project won't fork the wiki along. I cloned the wiki to my desktop and made the changes tried pushing it up but got a 403. It may just be me being new to GitHub; however, maybe I quick explanation doc how to contribute would be nice

**Comment by yyx990803** [comment]
Unfortunately there have been constant spammers spamming the Wiki, so I had to disable it. You can make a pull request to https://github.com/vuejs/awesome-vue or share your app on the [forum's Show & Tell section](http://forum.vuejs.org/category/15/show-tell).
