### ISSUE TITLE
[Feature] Computed property in Component

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#2006]
Assumption: A list of objects, that can be represented as components. These components have a bit of complexity, where computed properties would come in handy. As of now, I could not find any solution on how to elegantly handle this (see solutions below).

*I once had a project using Vue 0.12.7, and with the usage of "v-component" I was able to have computed properties inside a component, that I called while iterating over an array using these components...*

I already asked in the forums and on gitter, but nobody was able to help me as of yet, so I assumed that it's possibly not implemented (yet).

This is a simple example showing what I would like to accomplish, or what feature I'm requesting. This way the parent VM does not have to know anything about it's contents. It simply sets the data and the component - the rest is done in HTML. In the item, that's emitted from the loop, I want to call a computed property to sum up it's contents - which doesn't work the way I implemented it, but should give an idea on what I'm trying to do.
http://jsfiddle.net/4pjeynqx/4/

This is a work around, abusing the computed property of the parent VM. This way, the parent has to know about it's data, and has to compute all the properties for it's children. I imagine that this is very badly performing for larger data structures.
http://jsfiddle.net/4pjeynqx/1/

I don't know where it would be best to define a computed property related to the item rather than the container (parent VM), but the Component used to display a child seems about right...

**Comment by young-steveo** [comment]
Like this: http://jsfiddle.net/4pjeynqx/6/

**Comment by young-steveo** [comment]
Notice in the template, it's just `{{ totalPrice }}` so that it accesses the computed property of the component.

**Comment by johannes-z** [comment]
Hm, interesting. Couldn't find anything in the docs either.

So what is happening there? When I just put `{{ totalPrice }}` in the template, it's scope is the Component, while `{{ item.totalPrice }}` would be in the item's scope, which is basically just the plain object?

**Comment by yyx990803** [comment]
Computed properties are exposed directly on the component itself. Inside the component `item` is indeed a plain object, which was passed in as a prop.

So yeah the component scope basically looks like:

``` js
{
  totalPrice: ...,
  item: {
    // ...
  }
}
```

You should install [vue-devtools](https://github.com/vuejs/vue-devtools) - inspecting the instance makes it a lot easier to understand its state.
