### ISSUE TITLE
Mistake with v-for and directive json

### ISSUE THREAD

**Issue by alexahdp** [vuejs/vue#2007]
I have component:

```javascript
var userList = Vue.extend({
	props: ['users'],
	template: `
		<p>HERE</p>
		<h3>Users</h3>
		<div id="userList">
			<div class="text-right">
				<button v-on:click="addUser" class="user-list__addBtn btn btn-success">Add</button>
			</div>
			<ul class="user-list list-group">
				<v-user v-for="user in users" :user="user"></v-user>
			</ul>
		</div>
	`,
	methods: {
		addUser () {
			var userComponent = this.$children[0];
			this.$dispatch('addNewUser', userComponent.getNew());
		}
	},
	components: {
		'v-user': user
	}
});
```

and here is subcomponent user:

```javascript
var user = Vue.extend({
      props: ['user'],
        template: `
		<li v-on:click="preview" class="user-list__item list-group-item">
			<span class="user-list__item-email list-group-item-heading">{{ user.email }}</span>
		</li>
	`,
	methods: {
		preview (e) {
			this.$dispatch('previewUser', this.user);
		},
		getNew () {
			return {
				_id      : null,
				email    : '',
				firstName: '',
			};
		}
	}
});
```

All work fine but if I write {{$data | json}} instead <p>HERE</p> I get error:

Uncaught TypeError: Cannot read property 'addDep' of null
Dep.depend @ vue.js:1969
reactiveGetter @ vue.js:2170
read @ vue.js:9029
Vue._applyFilters @ vue.js:8078
Watcher.get @ vue.js:3074
Watcher @ vue.js:3027
Directive._bind @ vue.js:7626
linkAndCapture @ vue.js:6321
compositeLinkFn @ vue.js:6299
Vue._compile @ vue.js:7885
Vue.$mount @ vue.js:8822
Vue._init @ vue.js:2355
VueComponent @ VM45522:2
build @ vue.js:5869
mountComponent @ vue.js:5789
(anonymous function) @ vue.js:5754
(anonymous function) @ vue.js:5769
cb @ vue.js:366
Vue._resolveComponent @ vue.js:8129
resolveComponent @ vue.js:5771
setComponent @ vue.js:5753
bind @ vue.js:5713
Directive._bind @ vue.js:7607
linkAndCapture @ vue.js:6321
compositeLinkFn @ vue.js:6299
Vue._compile @ vue.js:7885
Vue.$mount @ vue.js:8822
Vue._init @ vue.js:2355
Vue @ vue.js:8881
(anonymous function) @ app.js:12

**Comment by alexahdp** [comment]
I decided problem. Just nedd

```javascript
data () {
    return this.users;
},
```

in UserList component

**Comment by yyx990803** [comment]
Is this resolved? The original error doesn't look right to me though, it'd be great if you can make a live reproduction.
