### ISSUE TITLE
遍历 使用VUE绑定后的对象时，Safari与Chrome有不同的结果

### ISSUE THREAD

**Issue by yuhere** [vuejs/vue#2008]
再现方法：
使用Safari与Chrome分别打开附件，
观察 《VUE绑定前》《VUE绑定后》的结果，
Chrome前后没有变化，而Safari前后顺序被改变了。

[0.12.16、1.0.7]都存在这个问题。

请参见附件[index3.html.zip](https://github.com/vuejs/vue/files/58995/index3.html.zip)（需要修改script src）

作为Object，key的顺序并不重要。
但对于一些特定的操作，顺序被改变是很麻烦的。

**Comment by yyx990803** [comment]
`v-for` 被用在对象上时**不保证遍历顺序**，这是由 JavaScript 引擎的实现决定的。如果你需要固定顺序，用 `orderBy` 或者自己把对象转成数组。

**Comment by yuhere** [comment]
不使用v-for或vue的操作，只是轻轻的绑定一下，绑定之前与绑定之后的顺序就不一样了。
附件中的例子证实了，vue对数据做出了预想外的改变。

在safari中，一个数据对象，var obj = {"x":"1","a":false,"b":true,"c":1,"d":0}在没有绑定之前，Object.keys(obj)的顺序是[x,a,b,c,d]，使用new Vue({data:{ xxx: obj }})后，再Object.keys(obj)，得到了[d,c,b,a,x]。预想之外的结果。

**Comment by luckymore** [comment]
@yuhere 你学过js吗 :cry:

**Comment by ppq1991** [comment]
@yuhere 这个没有任何问题，和 Vue 无关。

**Comment by yuhere** [comment]
@luckymore 你学的不错。:cry:

对不起，附件中好像写错误，

修改VUE关于Observer.walk:
Observer.prototype.walk = function (obj) {
  var keys = Object.keys(obj)
  var i = keys.length
  while (i--) {
    this.convert(keys[i], obj[keys[i]])
  }
}
为：
Observer.prototype.walk = function (obj) {
  var keys = Object.keys(obj)
  for (var i=0;i<keys.length;i++) {
    this.convert(keys[i], obj[keys[i]])
  }
}
使其正序，Safari得到了正确的顺序。

@ppq1991 和 Vue 无关?

**Comment by yyx990803** [comment]
虽然确实和 Vue 有关，但是无论用不用 Vue，你的任何代码都不应该依赖对象的 property enumeration
order，如果有那么你最好改一下这个习惯...

**Comment by yuhere** [comment]
不应该依赖对象的 property enumeration order，赞成。
那不是我的习惯，数据传到服务器端，服务器端按用这个顺序，
服务器端的程序确实不好，没办法，控制不了。

**Comment by yuhere** [comment]
修改了，/src/observer/index.js（3处），Safari中可以得到正确的结果。
Jasmine单元测试显示，607 specs, 0 failures。认为，这3处修改是没有问题的。

![jasmine](https://cloud.githubusercontent.com/assets/4280487/11760053/510f7c20-a0c6-11e5-9abb-066201ac3079.png)

[Property原生顺序 修改.diff.zip](https://github.com/vuejs/vue/files/60047/Property.diff.zip)

**Comment by yyx990803** [comment]
请发 pull request, 不要用上传...

**Comment by galenyuan** [comment]
大部分情况下对property的顺序改变是没有什么影响的..
不知道楼上各位试没试过salesforce下的开发，salesforce中的数据库字段是对应JSON的各个key的，在字段有依赖时改变顺序就会造成很多麻烦..
当然这很坑爹，而且在99%的使用环境中是不会出现的
