### ISSUE TITLE
Conditional slots, is it possible?

### ISSUE THREAD

**Issue by kzima** [vuejs/vue#2009]
How to achive this?
http://jsfiddle.net/kzima/5v8rLmp6/1/

My component's template looks like this:
```html
<button v-show="!href"><slot></slot></button>
<a href="href" v-show="href"><slot></slot></a>
```

and it only works if I set the 'replace' param on the component to true, but then I end up with custom tag in my html.

Any thoughts?

**Comment by posva** [comment]
You can use v-if in slots, if that's your question

**Comment by yyx990803** [comment]
1. `v-show` means you will have two default slots at the same time, which is not good - use `v-if`;
2. Your component is a fragment instance, so the `v-on:click` has no root node to attach to. Make sure to always give your component a single root node.

Also, please post questions at the forum.
