### ISSUE TITLE
What is the release plan of CSP

### ISSUE THREAD

**Issue by hbrls** [vuejs/vue#2012]
It is now `1.0.10`, not `1.0.11`. And the main is `dist/vue.common.js` which should be `dist/vue.js`.

Will you have a auto-build along the normal release?

**Comment by yyx990803** [comment]
1.0.11-csp is out. The main is correct - `vue.common.js` is only distributed on npm, not in the source code.

**Comment by hbrls** [comment]
Where will be the Vue 2 csp?
