### ISSUE TITLE
Testing needs to be sorted out

### ISSUE THREAD

**Issue by thetutlage** [vuejs/vue#2016]
Hello

I have not seen anyone talking about testing with `VueJs`, all i can see is checkout the source code and tests or testing is not VueJs issue. I believe it is.

Testing is a broad concept, and with frameworks like `VueJs` , there needs to be some official documentation of covering different aspects of testing. I agree unit testing is not an issue with `VueJs` as every component is an object and can be tested easily.

## Where is the problem ?

While writing my code, i make use of `Vueify` and it breaks in testing and breaks so badly

Next, i tried making use of frameworks like `zombie js` for e2e testing and it breaks because these frameworks expect me to test my click events with the help of Css selectors and with VueJs i am not in the habit of creating css selectors as i am easily two 2 way data binding. Resulting e2e tests are hard to write and no one is using frameworks to do hard work.

I am not upto date with VueJs development, might be you guys have great plans to sort it out. But denying the fact that testing is not the framework issue is not what we are expecting.

**Comment by azamat-sharapov** [comment]
Have you looked at these?

http://vuejs.org/guide/application.html#Unit_Testing
https://github.com/vuejs/vue/tree/dev/test

**Comment by thetutlage** [comment]
@azamat-sharapov Yes, really not helpful, it does not talk to vueify and these are unit tests not e2e tests. Which are way more complex.

**Comment by posva** [comment]
@thetutlage Take a look at https://github.com/posva/vue-mdl I have e2e set with nightwatch. I inspired myself from https://github.com/vuejs/vue-router

**Comment by thetutlage** [comment]
@posva That seems interesting and nightwatch can be good option too. So i believe to test to click events you will be using css selectors with nightwatch ?

**Comment by posva** [comment]
Yes, using css selectors is great as it allows you to write maintainable tests even if you elements change

**Comment by azamat-sharapov** [comment]
@thetutlage it's open source framework, if docs are not good enough, you can contribute to make it better! 

e2e tests don't care what kind of framework you are using, I don't understand why this should be in Vue docs.. unrelated. That link to source code I gave you is more than helpful, believe me (if you are willing to code at all).  

When, for example using casperjs as testing tool, you look at it's API and check what options it has for that "click" you are talking about. Selecting element is not limited to CSS class, you can use any other plain JS way, on casperjs at least (check clickLabel() on casper docs for example, to have idea). Nightwatch is similar to Casper and works with selenium, where casper works with phantomjs or slimerjs.

[Also, please ask this kind of questions on forum next time.](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines)

**Comment by yyx990803** [comment]
Having opinionated test guidance is nice, but seriously, don't take it for granted and ask it in a demanding tone. Vue is provided to you for free, I don't have any obligations to solve all your problems (technically this is not even a problem, because you are basically asking me to do free research for you when you already got something from me for free).

You could have suggested it along the lines of "It would be nice if Vue provides official guidelines on how to approach testing with Vueify...", but you chose to phrase it as if Vue owes you for not doing that. This makes me sad as a maintainer, really.

With that said...

1. The testing guide mentioned that Karma has plugins for both Browserify and Webpack. Did it ever occur to you that using the Browserify plugin for Karma would allow you to use `vueify` in your tests?

2. E2E is not a Vue-specific issue, period.

**Comment by NitishTyagi** [comment]
@yyx990803 You seems to be like an angry bird, no one forced you to write vueJs, respect your project and it is always to open integration options rather than being rude and saying it's not your job.

You used VueJs to be free, because you know no one will ever pay for it. Respect to gain respect

**Comment by posva** [comment]
@NitishTyagi Wow, just wow. Please, stay away from this community. Not only your behaviour is toxic but the points you're trying to defend don't even make sense if you read the initial comment: it wasn't very respectful.

**Comment by jonagoldman** [comment]
@NitishTyagi you must be a troll... there's no way you are being serious. You talk about respect? A guy gives you one of the best written pieces of code I have ever seen and all he asks is to behave in a decent way and ask nicely. That's respect.

**Comment by smolinari** [comment]
I agree with @posva and @jonagoldman. @NitishTyagi and @thetutlage have no clue about OSS and community effort.

@yyx990803 - Evan. Don't let this get you down or bothered at all. You've put together something masterful and I personally are am very appreciative of your hard work. Please keep it up! :+1: 

Scott

**Comment by jonagoldman** [comment]
yeah he's a troll... don't waste your time, here is this guy contributions: ![NitishTyagi](http://s2.postimg.org/balsqq995/Screenshot_from_2015_12_13_20_02_23.png)

**Comment by thetutlage** [comment]
I believe we should leave this issue, if you guys think i was rude then i was not. All i was asking to let's talk about testing seriously as while browsing other issues i have found community is more diverted towards `this is not our problem`. Which can be quoted as `why don't you suggest something ?`.

Trolling someone's profile is not great in itself @jonagoldman yours is not fancy aswell.

I respect @yyx990803 for his hard work and maintaining an open source is not an easy task and requires lot of time management. But after doing lot of hard work a nice reply will do even better.

**Comment by smolinari** [comment]
Your post isn't rude @thetutlage, but it still doesn't do what you wanted to do and that is to open up a positive dialog about more documentation on testing. You basically left the door closed. As Evan noted, your "tone" was off. 

Scott

**Comment by jonagoldman** [comment]
@thetutlage you just don't get the vibe, I'm not comparing profiles, I'm just showing that @NitishTyagi has no GitHub activity at all, meaning its probably a fake or trolling account.
Anyways, better stop the discussion here as its not contributing and it doesn't really belong here.

**Comment by jwebcat** [comment]
@NitishTyagi :trollface:

**Comment by jwebcat** [comment]
After reading the above comments:

@yyx990803 I have been following your work for years I just wanted to personally reach out and give you thanks for all your life blood you have poured into this project.

:+1:

**Comment by yyx990803** [comment]
Thanks for everyone who made positive responses to this thread.

@thetutlage I'm just trying to make a simple point here: if you want a nice answer, ask nicely. If you think you asked nicely, think again.
