### ISSUE TITLE
on:submit bug

### ISSUE THREAD

**Issue by srph** [vuejs/vue#2017]
Pressing the enter button (keyboard) on an input (this triggers the `on:submit` event in the `form`) does not cause "reactive" changes from the input, while clicking the `submit` button does.

Here's the [demo](http://srph-playground.github.io/vue-js-on-submit-bug/) / [repo](https://github.com/srph-playground/vue-js-on-submit-bug)

**Edit**: Changed "clicking" to "pressing". Might have been a source of confusion.

**Comment by posva** [comment]
which browser are you using. It works fine on chrome

**Comment by srph** [comment]
I am using Chrome 47.0.2526.80 (64-bit) on OSX 10.11 (El Capitan)

**Comment by yyx990803** [comment]
Seems to work fine for me too. Please be more specific about

1. Steps necessary to reproduce the issue
2. What are you expecting
3. What is the actual behavior

**Comment by srph** [comment]
Expected: The input (in the create form) will become blank when I submit the form.
Actual: The input only becomes blank when I click the click the "create" button. When I try to press the `enter` key, everything works except that the input is not blank.

Steps to reproduce:

1.) Click on the "create a new task" button
2.) Fill the input with characters (anything)
3.) Press the enter key.
4.) Repeat steps 1-2.
5.)) Click the "create" button

**Comment by srph** [comment]
Thank you! Very much appreciated.
