### ISSUE TITLE
Support for multiple JavaScript dialects in expressions

### ISSUE THREAD

**Issue by taylorzane** [vuejs/vue#2018]
# Support alternate dialects in Vue expressions.

## Introduction

I was thinking about implementing support for using other dialects of JavaScript (ES6/Babel, CoffeeScript, Opal) in expressions (handlebars, directives), and figured I would open an issue to see if the Vue community would benefit from this.

## Motivation

Implementing this would allow developers to use one programming language to form a cohesive application. It would remove the need for a developer to use multiple programming languages to build an application. While the amount of vanilla JavaScript used in expressions is small, it can cause a hiccup if a developer wants to use a sugar that is available in their language, that would be cumbersome to write in vanilla JavaScript, in an expression.

## Pros

- One JavaScript dialect for all code
- Use syntactic sugar of desired dialect

## Cons

- Could cause confusion if another developer attempts to read/modify the code
  and is unaware of a special dialect
  - Resolution: Brief developer of custom Vue configuration.
- If syntax highlighting inside of expressions is supported in the future, this could cause the syntax highlighter to break.
  - Resolution: Since the syntax highlighter doesn't have access to the Vue runtime, one would specify a tag similar to `lang`, such as `dialect/expression="coffee-script"` for the syntax highlighter to interpret.

## Detailed Example

The workflow to use this would be something like this (example is for a webpack-enabled app)

```coffee-script
# app.coffee
# ==========
# Probably better to require these as a webpack.ProvidePlugin
coffee = require 'coffee-script'
Vue = require 'vue'

# Could be .compiler or .dialect (or whatever makes the most sense)
# The config value would be set to the function that transpiles 
# the language to Javascript.
Vue.config.expressionDialect = coffee.compile

## Alternate method if compiler requires extra options
Vue.config.expressionDialect = (expression) ->
  coffee.compile expression, bare: true

Vue.component 'app', require 'app.vue'

vm = new Vue
  el: 'body'
  methods:
    someMethod: (options) ->
      options.opt1 && options.opt2 is 'bar'

```

```jade
//- app.jade
//- ========
html
  body
    app(v-if="someMethod opt1: 'foo', opt2: 'bar'")

    script(src="app.js")
```

```vue
<!-- app.vue -->
<!-- ======= -->
<template lang="jade">
#app
  .my-class {{ if getDate '10/10/2015' then 'Today' else 'Not Today' }}
</template>

<script lang="coffee">
module.exports =
  data: ->
    someVar: 1234
  methods:
    getDate: (date) ->
      d = new Date date
      today = new Date
      if d.toDateString() is today.toDateString()
        return true
      else
        return false
      
</script>
```

## Detailed Implementation

1. The developer would set `Vue.config.expressionDialect` equal to the dialect's transpilation function.
2. The developer would write their Vue components using their desired dialect in expressions.
3. When Vue parses an expression, it will check if `Vue.config.expressionDialect` is defined.
  1. If `expressionDialect` is defined, the parser will pass the expression to the transpile function, and eval (and return) the transpiled expression.
  2. If `expressionDialect` is not defined, the parser will simply eval (and return) the expression.

## Impact on existing code

This would not affect existing codebases as the default value of
`Vue.config.expressionDialect` would be to use vanilla JavaScript.

## Miscellaneous Commentary

One may argue that using logic in expressions is unnecessary since all logic could be moved to a method. A counter-argument to this could be the ability to call a nested function in an object tree structure using CoffeeScript's existential operator.

The vanilla JavaScript is either significantly more verbose, or simply doesn't handle undefined children.

```jade
//- Vanilla JavaScript
#some-component
  .some-div {{ app ? app.foo ? app.foo.bar ? app.foo.bar.baz ? app.foo.bar.baz.someMethod('args') :null:null:null:null }}

  //- One could simply write this as

  .some-div {{ app.foo.bar.baz.someMethod('args') }}

  //- and just accept the fact that Vue will throw a warning.
```

The CoffeeScript syntax would handle any undefined child and simply stop walking the tree.

```jade
//- CoffeeScript
#some-component
  .some-div {{ app?.foo?.bar?.baz?.someMethod('args') }}
```

Another example for this implementation's usefulness could be the ability to use CoffeeScript's list comprehension.

(This is an extremely contrived, probably useless, example)

```vue
<template lang="jade">
//- Vanilla JavaScript
#some-component
  .some-div(v-repeat="arr in fooTheFoo(foo)")
    .some-other-div {{ arr[0] }}
</template>

<script lang="coffee">
module.exports = 
  data: ->
    foo:
      bar: [1, 2, 3]
      baz: [4, 5, 6]
      qux: [7, 8, 9]
  methods:
    fooTheFoo: (foo) ->
      results = []
      for val in foo
        results.push val
      results

      # Obviously since the script is written in CoffeeScript one could simply write the following
      # but this is to provide an example of not being able to write a list comprehension
      # in the v-repeat directive.
      val for val of foo
</script>
```

```vue
<template lang="jade" dialect="coffee-script">
//- CoffeeScript
#some-component
  .some-div(v-repeat="arr in foos = (val for val of foo)")
    .some-other-div {{ arr[0] }}
</template>

<script lang="coffee">
module.exports = 
  data: ->
    foo:
      bar: [1, 2, 3]
      baz: [4, 5, 6]
      qux: [7, 8, 9]
</script>
```

If you have any questions, or comments, feel free to reply to this issue or contact me on Twitter ([@thetaylorzane](https://twitter.com/thetaylorzane)) or on Gitter ([@taylorzane](https://gitter.im/taylorzane))

**Comment by yyx990803** [comment]
This is an interesting proposal! Here are some of my technical concerns:

1. This compilation would have to happen at runtime, which means
  1. You will have to include the entire transpiler runtime with your app;
  2. Expression parsing will be slower.

2. Some transpilers would expand simple expressions into quite verbose code. e.g. array comprehension in CoffeeScript will compile this:

  ``` coffee
  cubes = (num for num in list)
  ```

  Into this:

  ``` js
var cubes, num;

cubes = (function() {
  var i, len, results;
  results = [];
  for (i = 0, len = list.length; i < len; i++) {
    num = list[i];
    results.push(num);
  }
  return results;
})();
  ```

  Which is **not a single expression**, and therefore cannot be easily passed on to Vue's expression parser for further evaluation. It's possible to modify Vue's expression parser to make this work, but it's going to be non-trivial.

**Comment by taylorzane** [comment]
1. I think that doing the compilation and compile-time would greatly improve the performance, while I don't feel that CoffeeScript is slow to compile, when one is doing hundreds of evals per second, it can add up. This would also remove the need to bundle the transpiler runtime with the app; it could stay a devDep.

2. The fact that this code transpiles to a much more verbose output, is certainly a hurdle. I understand that the output is not a single expression, but granting one the ability to use an alternate language may be worth the overhead of extending the parser.

I'll look through the parser source, and walk through a call to the parser from start to finish to fully understand what steps we would have to take.

**Comment by taylorzane** [comment]
Well, after some testing this morning, I've realized that compile-time may be our only feasible option for this. CoffeeScript (I don't know about the others) relies on a few node modules that aren't available to the browser. So transpiling to JavaScript through a secondary loader, may be our best bet.

**Comment by posva** [comment]
As a Coffeescript user I wouldn't use this if it affects performance. The amount of js code written inside html/jade is minimal and therefore the benefit from using coffee in expression will not counter the amount of work needed to setup and handle the dialect.

I really like the idea behind but I think this will mean a lot of work for very little value

**Comment by mark-hahn** [comment]
> The fact that this code transpiles to a much more verbose output, is
certainly a hurdle.

That is incorrect.  The coffeescript code starts out 33% smaller and
expands to the same size as native JS would occupy.  I have used CS for
four years and work with the transpiled output in the inspector frequently.

**Comment by taylorzane** [comment]
@mark-hahn I think Evan is more concerned with the fact that we're transforming what is an expression in CoffeeScript `v = (val for val in val)` to a very long JavaScript function (in this example). The main issue that I can see of this, is that the expression parser forbids functions, among other things.

**Comment by yyx990803** [comment]
I think @posva 's comment pretty much sums up my take on this - too much work for marginal gain. If this can be done in a way that doesn't affect how Vue's core expression parser works, I'm all for it, however that doesn't seem to be the case.
