### ISSUE TITLE
Transitions on a view model that has parent set

### ISSUE THREAD

**Issue by lorengreenfield** [vuejs/vue#2019]
It seems that transitions don't fire for templates who's view model has the parent property set. Using the example from the vue website at js fiddle: http://jsfiddle.net/yyx990803/mvo99bse/light/ - If you change the external resource to use v1 or later (not beta like it's set to), then add a "var vm = Vue({})" and then in the existing view model add a "parent: vm," the transition animation stops firing. Simply commenting out the "parent: vm," allows it to work again. Is this a bug or am I missing something?

**Comment by taylorzane** [comment]
@lorengreenfield I don't think that the way you're going about creating a new Vue instance is correct. There should only ever be one `new Vue` instance. All other instances should be components, or partials.

I've forked the example to follow the suggested parent/child pattern. http://jsfiddle.net/taylorzane/mvo99bse/22/

As you can see, `vm` is the parent and `child` is a child component of the parent instance. If you call `this.$parent` in the scope of the child component, the parent (`vm`) instance is returned.

**Comment by lorengreenfield** [comment]
I've not wanted to use the baked in component system and didn't think creating a parent-child relationship required it. It works fine for the event system, so was just a little surprised that it prevents transitions from working by doing it this way. Components are just extended Vue instances aren't they?

**Comment by taylorzane** [comment]
You are correct. A component is simply syntactic sugar for a `Vue.extend({})`. But you may only have one root instance (`new Vue({/* options */}`). You can certainly do something like [this](http://vuejs.org/guide/components.html#Local_Registration) to manage all of your components. But there is a logical different between `new Vue` and `Vue.extend({})`, which prevents you from instantiating a child using `new Vue({ parent: parentVM })`.

**Comment by lorengreenfield** [comment]
Pre 1.0, I used a vm.$addChild({}) to create children (http://012.vuejs.org/api/instance-methods.html - scroll to the bottom of that page). These instances didn't have to be created using Vue.extend, that was optional. If this has changed now, that's fine, I can adapt, but interestingly, using transitions with the old $addChild system also has the same issue.

**Comment by taylorzane** [comment]
Well, I stand corrected. I skimmed through the change logs and found this in the 1.0.0 release notes.

> - Instance method vm.$addChild() has been deprecated. Instead, a new option, parent has been (re)introduced. The usage is pretty simple:

> ```
> // before
> var child = parent.$addChild(options)

> // after
> var child = new Vue({ parent: parent })
> ```

I suppose I need to brush up on my Vue 1.x docs.

**Comment by taylorzane** [comment]
[Here](http://jsfiddle.net/taylorzane/k4aps2tb/4/) is a working fiddle. The second (child) Vue instance has the `parent` attribute. For me, the transitions still work as expected.

**Comment by lorengreenfield** [comment]
OK, it seems the key is the el option in the parent. I think we can call it problem solved. I'm going to have to rework my code a little bit but it makes sense now. @taylorzane Thanks for your help!
