### ISSUE TITLE
How to receive a oauth token with vue since the routes are behind #

### ISSUE THREAD

**Issue by e72575f3** [vuejs/vue#2020]
I'm using an oauth provider that forwards a token to an URL like this `?#access_token=TOKEN`

So if I set the oauth redirect url to
```
 https://vueapp/#!/oauth
```
I end up with
```
 https://vueapp/?#access_token=TOKEN
```
and loose my `oauth` route. I've tried all tricks in the book but can't figure it out.

How do I deal with this in vue? Do I have to configure nginx to make it work? Thanks so much!

Disclaimer: I've posted this issue also in vue-router but maybe this is the appropriate place for it.

**Comment by yyx990803** [comment]
This issue does belong to `vue-router`. I'll take a look over there.
