### ISSUE TITLE
v-model with debounce param issue. Uncaught TypeError: Cannot read property 'set' of null

### ISSUE THREAD

**Issue by losadaem** [vuejs/vue#2023]
The debounce internal timeout id needs to be clear when unbinding the v-model directive to avoid calling Directive.set() after the directive _teardown call.

To reproduce the error just focus on the input field and click the hide button.

http://jsfiddle.net/5sH6A/224/

**Comment by losadaem** [comment]
I've just realized that the blur handler if checking this situation. Maybe this check can be done directly inside the listener function.

I've realized also that the blur handler is calling the debounced version of the listener. It doesn't make much sense to debounce the blur event in my opinion. I think is better to sync the model directly in the blur event to avoid stale data to be summited when clicking the submit button right after the last input field.

**Comment by losadaem** [comment]
@yyx990803 what about not debouncing the blur handler?

I can create a different issue to explain this use case if you want.

**Comment by yyx990803** [comment]
Yeah, please open a separate issue.
