### ISSUE TITLE
bug regarding Array.unshift together with v-for, v-model and radio-button group

### ISSUE THREAD

**Issue by tianhai82** [vuejs/vue#2024]
http://jsfiddle.net/tianhai/7906445s/
Click on "Add" the first time, the value of the original radio button will disappear although v-model value is still there.
Click on "Add" the second time, no dom is added at all although the array is changed.

**Comment by yangjunjun** [comment]
you can try `track-by="$index"` , see: http://jsfiddle.net/7906445s/1/

**Comment by tianhai82** [comment]
That works! thanx!

**Comment by yyx990803** [comment]
Use the dev build (non-minified), and you will see a warning that prompts you to use `track-by="$index"`.

**Comment by rgigger** [comment]
Is this still valid for Vue 2.1? It does not work for me. array.push works find but when I change it to unshift it alters the array correctly but in the DOM it just duplicates the last element. The track-by thing does not work for me.

**Comment by posva** [comment]
@rgigger You need to use the `key` attr (https://vuejs.org/v2/guide/migration.html#track-by-replaced) in Vue 2

**Comment by shepelevstas** [comment]
Hi! I have the same issue as **rgigger**, `:key` does not help.
I have `<mycomponent v-for="(item,index) in simpleArray" :key='index' :propA='item'>`...
When I `simpleArray.unshift('newItem')`, the array changes correctly, but `v-for` just duplicates the last mycomponent. Is it a bug, or I just do something wrong?

**Comment by posva** [comment]
using the index as the key is the default behaviour, you need to use a unique identifier (eg: a db id) otherwise, deletions in the array will reuse components

**Comment by shepelevstas** [comment]
May be the problem with simple arrays is that with unshift the elements change their indexes, and vue only renders additional component for the new element (the old last element of array), the rest components dont change! unshift does not trigger vue component rerender for existing elements.
