### ISSUE TITLE
form doesn't sync changes on submit when using debounce option

### ISSUE THREAD

**Issue by losadaem** [vuejs/vue#2028]
The blur handler is calling the debounced version of the listener. In my opinion the purpose is to debounce only the keystrokes but on blur it makes sense to sync the changes immediately to avoid stale data.

Example, input something and press enter or click submit right after.

http://jsfiddle.net/17j6cjgm/

**Comment by dragantl** [comment]
Seems like this still has not been fixed:

https://jsfiddle.net/4eh989ee/2/
