### ISSUE TITLE
Chrome plugin prevent the enter key action.

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue#2029]
In this [example](http://codepen.io/erguotou520/pen/LGGZOV), we can input some info into `username` and `password` form input. When it focus on `password` input, I press `Enter` key, nothing happened. Finally, I found when I remove Chrome's plugin `1 Password`, the message shows.
![image](https://cloud.githubusercontent.com/assets/7945757/11831011/9367cf24-a3e5-11e5-8a68-d7ac220d6356.png)
Is this a Vue bug or browser problem?

**Comment by yyx990803** [comment]
这个真是个很神奇的问题... 我研究了半天发现是 1Password 在看到 grant_type 的值为 `password` 后误以为那个框才是密码框，所以只有在那个框上按回车它才触发 form submit 事件...

如果你把 grant_type 的值改成随便其他什么，一切就正常了... 这个绝对是 1Password 的 bug...

**Comment by erguotou520** [comment]
WTF!
