### ISSUE TITLE
数组中watch变化的问题

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vue#2030]
watch数组变化时，会在数组中对一个changed标识符进行更新，在save后会将此标识符重置回初始状态，怎样能在save后重置的时候不监听标识符的变化，或者能够不触发watch呢？

**Comment by galenyuan** [comment]
Demo地址：https://jsfiddle.net/j0uexefy/
很急的需求..研究了两天也没研究出解决方案，麻烦解答一下，十分感谢！

**Comment by luckymore** [comment]
@galenyuan  老兄，item变是因为双向绑定，不是因为watch。watch是在运行时改变起作用的。

**Comment by galenyuan** [comment]
@luckymore 所以我问的是watch运行时不监听changed的方法。

**Comment by yyx990803** [comment]
加一个 saving flag: https://jsfiddle.net/j0uexefy/3/
