### ISSUE TITLE
JavaScript vs filter syntax

### ISSUE THREAD

**Issue by mindplay-dk** [vuejs/vue#2031]
Any particular reason Vue needs to invent custom syntax for filters?

IMO, `{{ x(y(a)) }}` would be more intuitive in a JS context than `{{ a | y | x }}`.

It's easy to mistake it for a JS syntax extension, expecting things like `{{ a + (b | x) }}` to work.

Alternatively, maybe the syntax could align better with JS, e.g. `{{ today | date('YYYY MM DD') }}` ?

Or maybe a more subtle syntax extension, like a special character to indicate filter expressions (and also allow inline evaluation) e.g. `{{ ~x(~y(a)) }}` rather than `{{ a | y | x }}` ?

Just throwing out ideas :-)

**Comment by posva** [comment]
well, as you said it's a filter, not a function/method. I like the way it looks, it feels readable because you read the pipeline

**Comment by mindplay-dk** [comment]
But it is a function?

Sometimes it refers to one of two functions (read or write) but it's still just a function, isn't it?

**Comment by yyx990803** [comment]
I appreciate your ideas, however please note that Vue has reached 1.0 status and is used in production by many. It's unlikely to consider breaking changes without substantial, concrete reasons to do so.

**Comment by mindplay-dk** [comment]
I wasn't suggesting a breaking change, though I understand if syntax issues have low priority.

**Comment by posva** [comment]
@mindplay-dk it's a special kind of function I'd say: in a function you can have side effects. A filter is intended to modify the data that is **displayed** on the view. In the other hand, a method is intended to do much more things like emitting events, creating requests, change the model, etc. A filter never changes the model
