### ISSUE TITLE
Reserved component names?

### ISSUE THREAD

**Issue by mindplay-dk** [vuejs/vue#2033]
For my very first try out, I attempted this:

```
<script src="https://cdn.jsdelivr.net/vue/latest/vue.js"></script>

<div id="app">
    {{message}}
    <slot></slot>
</div>
```

With this:

```
new Vue({
    el: '#app',
    components: {
        'slot': {
            template: '<div>Hello!</div>'
        }
    },
    data: {
        message: 'hello'
    }
})
```

This looked pretty by-the-book to me, and it turns out, it does work - just change the name `slot` to `foo`, and for some reason everything is fine.

There's no error message or anything, with the name `slot` it just doesn't work - nothing shows up below `{{ message }}` which does output correctly.

What gives?

Is the component name `slot` reserved for something?

Are there any other reserved component names?

If so, maybe reserved names should be prefixed with `$` or something, so they don't collide with userland component names?

**Comment by eduardostuart** [comment]
Slot is a special element: http://vuejs.org/api/#slot

**Comment by smolinari** [comment]
http://vuejs.org/guide/components.html#Content_Distribution_with_Slots

Scott

**Comment by crswll** [comment]
`slot` is part of the shadow DOM specification: 

https://w3c.github.io/webcomponents/spec/shadow/#slots

I think that's the only one besides: `div|p|span|img|a|b|i|br|ul|ol|li|h1|h2|h3|h4|h5|h6|code|pre|table|th|td|tr|form|label|input|select|option|nav|article|section|header|footer` you have to worry about.

**Comment by mindplay-dk** [comment]
Ah, makes sense.

So I take it maybe it's best practice to "namespace" your components, e.g. `my-foo` rather than `foo`?

Maybe the guide section on components should make this general recommendation?

**Comment by crswll** [comment]
A `-` used to be required in 0.11 but that was lifted. It was nice since you always avoided conflicts but also a little annoying. I guess the "W3C Custom Elements specification" dropped that requirement? Too lazy to look it up haha. It just makes me nervous. If a new HTML5 `<commoncomponentname>` tag is released it could make things messy.

**Comment by yyx990803** [comment]
It is indeed a good practice to "namespace" it. In fact Vue would warn you for some of the most commonly used HTML elements, I should just add `slot` to that list.

**Comment by mindplay-dk** [comment]
Actually, the [W3C spec](http://www.w3.org/TR/custom-elements/#concepts) has several more rules:

> The custom element type identifies a custom element interface and is a sequence of characters that must match the NCName production, must contain a U+002D HYPHEN-MINUS character, and must not contain any uppercase ASCII letters

There's a list of some reserved element names that do follow those rules as well.

**Comment by yyx990803** [comment]
Yeah, Vue originally followed the spec and enforced a hyphen in component names. However the spec remained in draft status and is still going through constant changes (lots of disagreements within the work group). So now Vue's implementation is loosely modeled after the spec but does not aim to be 100% spec compliant (API stability > a spec that is in flux).

**Comment by hajarrashidi** [comment]
@yyx990803 So is there a list of all the reserved directives?

**Comment by LinusBorg** [comment]
what do you miss from the list of directives in our documentation?

**Comment by hajarrashidi** [comment]
@LinusBorg Oh i see, i didn't know about this -> https://vuejs.org/v2/api/#Directives
