### ISSUE TITLE
Access $data inside slot fallback

### ISSUE THREAD

**Issue by eduardostuart** [vuejs/vue#2034]
Is possible to access parent $data inside slot fallback?

Component example:
```vue
<template>
    <div class="mycomponent">
        <slot></slot>
    </div>
</template>
<script>
module.exports = {
    data:function(){
        return {
            something: 'cool'
        };
    }
};
</script>
```

Example (Can I do this?)
```html
<mycomponent>
    {{ $data | json }} or {{ $parent.$data | json }}
</mycomponent>
```

**Comment by posva** [comment]
Nope, you can't because they're linked to the parent scope http://vuejs.org/guide/components.html#Compilation_Scope

**Comment by eduardostuart** [comment]
I saw that..but, how can I access $data inside slot `fallback`? 

```
Anything originally inside the <slot> tags is considered fallback content. Fallback content is compiled in the child scope and will only be displayed if the hosting element is empty and has no content to be inserted.
```

I can do this:
```vue
<template>
    <div class="mycomponent">
        <slot>{{ $data | json }}</slot>
    </div>
</template>
<script>
module.exports = {
    data:function(){
        return {
            something: 'cool'
        };
    }
};
</script>
```

But..can't do inside slot `fallback`. Even if I try to $parent $data.

**Comment by yyx990803** [comment]
What do you mean? The example in your last comment should work.

**Comment by eduardostuart** [comment]
I'm sorry.. I misstyped .. that's not the fallback, but the original content.

```
<mycomponent>
    original content, $data is empty and $parent.$data fails 
   {{ $data | json }} or {{ $parent.$data | json }}
</mycomponent>
```

**Comment by eduardostuart** [comment]
Here is a fiddle: https://jsfiddle.net/eduardostuart/gmc2ef6x/

**Comment by yyx990803** [comment]
That's expected:

- Original content is compiled in parent scope;
- Fallback content is compiled in child scope.

The `$data` in original content refers to the root vm (which has empty data)
The `$data` in fallback content refers to the child component's data. And you can use `$parent.$data` in fallback content.

https://jsfiddle.net/gmc2ef6x/3/
