### ISSUE TITLE
Issue with v1.0.11

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#2035]
With 1.0.10 the below works fine, with 1.0.11 I get error `TypeError: text.replace is not a function`

```html
<icon class="abc" icon="def"></icon>
```

```javascript
new Vue({
  el: 'body',
  components: {
  	icon: {
    	props: ['class', 'icon'],
        template: '<svg class="si-icon {{icon}} {{class}}"><use xlink:href=""></use></svg>'
    }
  }
});
```

Vue 1.0.10 - working
http://jsfiddle.net/fergal_doyle/7wvfq6jp/2/

Vue 1.0.11 - error
https://jsfiddle.net/fergal_doyle/m5Lr59of/3/

**Comment by eduardostuart** [comment]
I'm not sure, but I think that's because you can't register components like that anymore.

Try to register globaly or extend Vue.

Example:
```js
Vue.component('icon',{
    	props: ['class', 'icon'],
      template: '<svg class="si-icon {{icon}} {{class}}">yeap <use xlink:href=""></use></svg>'
});

new Vue().$mount('body');
```
