### ISSUE TITLE
Vue.delete key from object in v-for

### ISSUE THREAD

**Issue by Sheby** [vuejs/vue#2038]
Hello, so i got something like this.
```javascript
     new Vue({
            el: '#content',
            data: {

                notActive: {
                    1:anotherObject,
                    2:anotherObject
                }
            }
        });
```
And in HTML
```html

                <tr v-for="account in notActive">
                        <td class="text-center">
                            <label class="option option-primary">
                                <input type="checkbox" name="mobileos" value="@{{  strigify(account) }}">
                                <span class="checkbox"></span>
                            </label>
                        </td>
                        <td>@{{ account.type }}</td>
                        <td>@{{ account.email }}</td>
                        <td>@{{ account.first_name }}</td>
                        <td>@{{ account.last_name }}</td>
                        <td>
                            <button @click="invite(account)" type="button" class="btn btn-xs btn-primary">
                            Invite</button>
                        </td>
                    </tr>
```

when i do in some method
```javascript
Vue.delete(this.notActive, 1);
```
Uncaught TypeError: Cannot read property 'parentNode' of null

pops out, any idea on this?
My next option is to convert nonAction into an array but that would be a pain so would like a solution for this if there is any.

I've tried removing all of the inner contents of v-for but error still occurs, only when I remove the v-for completely from HTML error does not pop out
Thanks.

**Comment by yyx990803** [comment]
It works for me in minimal test case, I'll need a live repro.

**Comment by Sheby** [comment]
Got it.
Its jQuery DataTables and its pagination. 

it fails here, 

´´´´javascript
  /**
   * Insert el after target
   *
   * @param {Element} el
   * @param {Element} target
   */

  function after(el, target) {
    if (target.nextSibling) {
      before(el, target.nextSibling);
    } else {
      target.parentNode.appendChild(el);
    }
  }
´´´´
I guess the jQuery plugin removes the element form the DOM before vue fires this.
Anyway this is not a problem with vue, closing this.
