### ISSUE TITLE
Suggestion: API change to add new reactive values to observed array items

### ISSUE THREAD

**Issue by skyronic** [vuejs/vue#2041]
I faced a problem where I had a component like this:

```
<div v-for="(index, item) in items" v-show="!item.hidden" @click.prevent="hide(index)>
{{ item.text }}
</div>

{
   data: {
      items: [
          {text: 'foo'},
          {text: 'bar'}
      ]
   }
   methods: {
       hide: function (index) {
           // hide the item by setting item[index].hidden
      }
}
```

Now If I did:

```
item[index].hidden = true;
```

That didn't work, which is expected since `hidden` isn't a property registered by the observer. I was able to make it work with this:

```
Vue.set (item[index], 'hidden', true);
```

I think there might be nicer ways to do this, and can be added to the array observer. Please note *there might already be a way to do this better than what i'm doing right now, but I couldn't find it in the docs*. These are my proposals:

```
this.item.$extend (index, { hidden: true });
```

This works similar to `$set` but instead of replacing the object, it just extends the object. This can work if you're setting multiple properties. 

```
this.item.$set (index, 'hidden', true);
```

This works by enhancing the `$set` in the arrays prototype. If you pass two args, it will have current behaviors but if you pass 3, you set the key on it.

**Comment by posva** [comment]
You should initialize every variable in the data object:

```js
 data: {
      items: [
          {text: 'foo', hidden: false},
          {text: 'bar', hidden: false}
      ]
   }
```

**Comment by skyronic** [comment]
Yes. But in this case I'm pulling in the `items` from a XHR.

So I'm doing:

```
var self = this;
this.$http.get ('/items', function (data) {
    self.$set ('items', data);
});
```
Instead I'll have to do:
```
self.$set ('items', data.map (function (val) {
    val.hidden = true;
    return val;
});
```
Which seems a bit unnecessary since very few items will have the `hidden` property. And also `hidden` isn't the only one. I may have more which may be set or added later.

**Comment by smolinari** [comment]
I'd also think it would be good to differentiate between data needed for display logic and the data actually being displayed.  

Scott

**Comment by posva** [comment]
I may be wrong but adding the properties to an object make them work for objects added later. You should just declare every prop used. You can play around with the example here https://jsfiddle.net/posva/vjwbj5c6/

**Comment by skyronic** [comment]
@psova - you were correct, and I knew that declaring it will make it work. Vue makes it 'reactive' when declared directly.

If I did it the way you described it will work 100% but the thing is I am not setting the data as a hand-coded array. It's being fetched with XHR. I can still inject the properties. 

I'm merely saying that this is a common pattern (fetching objects and later adding an observed value) and having a helper function can make it easier for the other users.

**Comment by posva** [comment]
What about this https://jsfiddle.net/posva/vjwbj5c6/1/ ?

**Comment by posva** [comment]
You add a dummy object so every property is watched

**Comment by skyronic** [comment]
@posva: This is closer to what I'm doing: https://jsfiddle.net/yex35a4j/1/

I don't have complete control over how my data object is when I retrieve it. If I was hand-coding the data object or constructing it on client-side I can take your approach.

If you have ideas on how you can modify my code to add a `hidden` property on all of the items that would be great.

**Comment by posva** [comment]
@sjoerdvisscher Fetche your model somehow, or create it and upgrade your items before using `$set`

i hope this example is clear enough: https://jsfiddle.net/posva/v1fqmvv7/2/

**Comment by smolinari** [comment]
@posva - That is quite a verbose example for what it does, don't you think?

Scott

**Comment by posva** [comment]
@smolinari I don't think so, it is a very small example (~40 lines)

**Comment by yyx990803** [comment]
Thanks for the suggestion - I think this will be somewhat similar to the proposed `Vue.assign`: https://github.com/vuejs/vue/issues/1811

``` js
Vue.assign(items[index], { hidden: true })
```

It's not exactly what you wanted, but is more explicit on what we are doing. And if possible I'd like to add as few extensions as possible to native prototypes.

**Comment by smolinari** [comment]
@yyx990803 - :+1: That sound promising.

Scott
