### ISSUE TITLE
关于返回接口数据的json格式中，小数点问题。

### ISSUE THREAD

**Issue by AnyGong** [vuejs/vue#2045]
我请求的一个接口数据返回的json格式如下：
`[ "price":4.00 ]`，因为是价格，需要精确到小数点后2位来显示，可通过数据解析的时候解析成了 4，我知道我这里可以filter，也可以让接口改造一下，变成 `[ "price":'4.00' ]`。这是vue的处理逻辑是这样，还是bug？再有就是我们的接口数据不规范，还是我需要单独filter掉, tks
Demo: https://jsfiddle.net/Ldta3v2q/1/

**Comment by AnyGong** [comment]
通过chrome测试，console出来的也是这个结果，猜测是json自己内部的处理机制，作者有 更好的想法或建议吗？thanks

**Comment by yyx990803** [comment]
这个和 Vue 没关系... 展示小数点本来就应该是展现层的事情。用 filter 或者 `{{ price.toFixed(2) }}`

**Comment by AnyGong** [comment]
thanks @yyx990803
