### ISSUE TITLE
Svg attribute interpolation exception

### ISSUE THREAD

**Issue by fobdy** [vuejs/vue#2046]
```html
<circle cx="100" cy="{{ 1 + 1 }}" r="50"></circle>
```
will raise
`Error: Invalid value for <circle> attribute cy="{{ 1 + 1 }}"`

but nevertheless it will be interpolated

https://jsfiddle.net/dgwhq9vj/

**Comment by yyx990803** [comment]
This is just how SVG works. Prefer `:cy="1 + 1"` when working with SVGs.
