### ISSUE TITLE
Directive is always bound to the root..?

### ISSUE THREAD

**Issue by kwando** [vuejs/vue#2047]
Inside this ```directive.bind``` function I would expect that  ```this.vm``` would be an ```UiFullscreen``` instance, though I allways get the root Vue instance.

Using vue 1.0.11.

```html
<!DOCTYPE html>
<html id="app">
<head>
  <title>merciless.me</title>
</head>

<body>
<ui-fullscreen v-test>

  <div style="width: 32em;font-size: 10vw">
    Hello World
  </div>

</ui-fullscreen>
<script type="text/javascript" src="/bundle.js"></script>
</html>
```

```javascript
Vue.component('ui-fullscreen', {
    template: '<div class="fullscreen-container"><slot></slot></div>',
  });
  Vue.directive('test', {
    bind: function(){
      console.log('this.vm == this.vm.$root => ' + ( this.vm == this.vm.$root));
    }
  });


  new Vue({
    el: '#app'
  })
```
console says:
```this.vm == this.vm.$root => true```

**Comment by yyx990803** [comment]
Please see http://vuejs.org/guide/components.html#Compilation_Scope

**Comment by kwando** [comment]
@yyx990803 damn, I've read the docs twice (including that section) and I still got bitten by that.

Thanks anyway! Been playing around with Vue for a few days, so easy, so nice, so not angular.
