### ISSUE TITLE
Vuejs to change templates based on media queries

### ISSUE THREAD

**Issue by ardoramor** [vuejs/vue#2048]
This is a suggestion/inquiry as to whether Vuejs can handle dynamically applying templates based on media query. That is, is it possible to implement a support for defining component with several templates, each one is for a different media query, and have Vuejs apply the template when the query changes?

Playing with css media queries allows one to simply adjust the style of a layout to better fit the screen size. However, it does not offer to alter the layout in any way such as applying a different hierarchy with the same element in it but with different parents or nesting depths.

Because Vue compiles the templates, it potentially could reconnect the same data and re-attach the same components but to a different template.

**Comment by yyx990803** [comment]
I don't think this should be built-in to Vue. You can use a media query breakpoint detection library together with dynamic components to achieve this yourself.

**Comment by rpbarbati** [comment]
Vue components can respond to media queries without any additional libraries.  I solved this problem using the following approach...

for my CSS, I used the following...

```
my-style {
     width: 100%,
     --render-compressed: false;
}
```

And within a media query....

```
my-style {
     width: 100%,
     --render-compressed: true;
}

The --render-compressed is a custom CSS value, and as it turns out, where Vue can not read normal CSS values, it can read custom CSS values.  I will have to find my code that does it, but I absolutely guarantee it can be done.
