### ISSUE TITLE
Ignore non-vue elements in template

### ISSUE THREAD

**Issue by thelucre** [vuejs/vue#2051]
I'm working with with [AFrame](https://aframe.io/docs/guide/) which used its own custom web component syntax. Vue is trying to parse, for example, `<a-scene>` as a component. Can non-Vue elements be ignored in Vue templates?

**Comment by simplesmiler** [comment]
There is `v-pre`, which lets you manually specify the element nodes to be ignored.

**Comment by yyx990803** [comment]
Yeah, you can just add `v-pre` to `<a-scene>`:

``` html
<a-scene v-pre>
  <!-- aframe stuff -->
</a-scene>
```
