### ISSUE TITLE
Computed properties with dependencies

### ISSUE THREAD

**Issue by sunabozu** [vuejs/vue#2053]
Hi.

I have a feature request. It would be nice if we could declare dependencies for computed properties, so they could run only when one of described values actually changed. Now, if I understand correctly, computed properties run on any update, which is not very efficient, plus we cannot track actual changes inside them. There is `$watch`helper, but it can be bound only to a single value. Here is what I mean:
```javascript
computed: {
	property1: {
		dependencies: ['property2', 'property3'],
		run: function() {
			// computed property itself
			// runs only when property2 or property3 have been changed
			return this.property2 + this.property3
		}
	}
}
```

I think it would be a nice declarative alternative to having multiple watchers for running the same function.

**Comment by smolinari** [comment]
Not too sure about "computed properties run on any update, which is not very efficient," 

http://vuejs.org/guide/reactivity.html#Inside_Computed_Properties

Scott

**Comment by yyx990803** [comment]
Computed properties do track accurate dependencies. I'm not sure if this request makes sense.

**Comment by mildewey** [comment]
This would be useful if you want to refer to a member by a string key, EG:
this['property1']

Perhaps by using a for loop to generate those string keys.
