### ISSUE TITLE
Safari on Windows 8 silently fails

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#2055]
I tested an App using `vue 1.0` and `vue-router` on Safari on Windows 8.

Most pages render, but when navigating the page goes blank without errors or warnings.

I will make a demo and figure out where it goes wrong, but perhaps others have similar findings?

**Comment by kvdmolen** [comment]
However, I just learned Apple will stop supporting Safari on Windows.

**Comment by NicolasParada** [comment]
"will"?
It's already so D:

**Comment by yyx990803** [comment]
Does anyone actually use Safari on Windows?... I don't think they even officially distribute it anymore. It's a dead browser and I don't really think it's worth catering to.
