### ISSUE TITLE
Google Maps - Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by StevenBock** [vuejs/vue#2057]
Hello,

When trying to add a Google Maps object to a data property on a Vue instance, I receive the following error:  Google Maps - Uncaught TypeError: Converting circular structure to JSON.

I've created a basic JSFiddle to demonstrate this - you will see the error in your development console.  http://jsfiddle.net/5sH6A/235/

Thank you and please let me know if I can provide more details.

**Comment by yyx990803** [comment]
Vue reactive data must be plain objects. Do not treat complex objects as reactive data. If you need to attach it to the instance, just set this.map = map in the created hook.
