### ISSUE TITLE
How to use component according to async data?

### ISSUE THREAD

**Issue by berryliu** [vuejs/vue#2058]
There are some trouble to me, when I use component after async data ready.
Say that, I fetch data in router's data hook, and need use other components according to the data I fetched. Before I fetched the data, I don't know which component need I use, or what components orders.
so, I've no idea what the template is, until I fetched the data. And I need push component and it's params to the template according to the data.
How should I do?
Thanks for answering!

**Comment by yyx990803** [comment]
Please do not use issues to ask questions. Use either Gitter or the forum.

**Comment by berryliu** [comment]
got it, sorry.
