### ISSUE TITLE
定义一个先于 v-if 执行的指令

### ISSUE THREAD

**Issue by qiu8310** [vuejs/vue#2060]
我定义了一个指令，将它的优先级指定成了 4000 (v-if 的优先级是 2000），希望在同一个 div 上，这个指令可以先于 v-if 执行，但结果总是 v-if 先执行，当 v-if 的条件为 false 时，我自定义的指令也就无法执行了。

一个简单的 DEMO: http://codepen.io/qiu8310/pen/rxLxBP?editors=101

**Comment by yyx990803** [comment]
为什么要先于 v-if 执行？这个指令是干嘛的？

**Comment by qiu8310** [comment]
自定义了一个 loading 指令，用于向后端加载数据，希望在 loading 过程中 v-if 得到的是 false，loading 完成之后，v-if 就变成 true 了，所以需要 loading 先于 v-if 执行。

这样我就可以用 
```
<div v-loading v-if="something"> .... </div>
```

而不是这样
```
<div v-loading>
    <div v-if="something"></div>
</div>
```


PS: 知道 vue-router 上有个 data 方法，可以用它去异步加载后端的数据。但有时我并不是在 router 的时候就需要数据，可能是在用户点击某个按钮后才触发。

**Comment by Mrxdh** [comment]
看来双向绑定你还没懂

**Comment by qiu8310** [comment]
补充下，v-loading 在执行过程中我会在指定的 dom 上做一些动画效果，loading 结束就销毁动画。

**Comment by yyx990803** [comment]
思路不对啊。

``` html
<div v-if="loading">
  loading...
</div>
<div v-else>
  展示数据
</div>
```

尽量不要用指令做产生副作用的事情。

**Comment by qiu8310** [comment]
你说的也没错，但每个地方都有这么个loading变量和那个动画效果，我觉得很不爽，把它们提取出来放到一个指令中不好吗？



还有，为什么不能定义比if优先级高的指令？难道只是基于你没遇到过对应的使用场景，并且它的实现成本比较高吗？




在 2015-12-22 00:02:26，"Evan You" <notifications@github.com> 写道：


思路不对啊。

<divv-if="loading">
  loading...
</div>
<divv-else>
  展示数据
</div>

尽量不要用指令做产生副作用的事情。

**Comment by yyx990803** [comment]
在 Vue 当中，指令的最佳使用场景是映射一个表达式的值到具体的 dom 行为。这个行为理想情况下应该是同步、易于理解的。你的 `v-loading` 指令既不包含映射的表达式，又包含复杂的异步行为，其实对于其他人来说是很难理解和维护的。

如果要抽象出可复用的行为，大可以把 loading 相关的东西做成一个组件的 mixin 来进行复用，而不是以指令的形式。

**Comment by yyx990803** [comment]
另外，优先于 `v-if` 的指令实现成本确实很高，对我来说也没有什么有意义的使用场景。如果你有兴趣，欢迎贡献。

**Comment by qiu8310** [comment]
mixin方案可能不错，我忽略了，回头试试。
谢谢解释！



在 2015-12-22 07:12:52，"Evan You" <notifications@github.com> 写道：


在 Vue 当中，指令的最佳使用场景是映射一个表达式的值到具体的 dom 行为。这个行为理想情况下应该是同步、易于理解的。你的 v-loading 指令既不包含映射的表达式，又包含复杂的异步行为，其实对于其他人来说是很难理解和维护的。

如果要抽象出可复用的行为，大可以把 loading 相关的东西做成一个组件的 mixin 来进行复用，而不是以指令的形式。

**Comment by wsyxl365** [comment]
感谢尤大的耐心解释。 有一种情况不知道是否有更优雅的方式去解决，我的一个组件的显示或隐藏 是来自多个不同维度数据融合判断之后的结果， 举例说明: 我有一个按钮， 首要要判断我这个角色是否有权限使用这个按钮，确认有权限之后，还需要根据后台返回的数据来判断此按钮在某个status字段下是否应该展示， 这就牵扯到不通维度数据管理的问题， 我现在的做法就是在指令中判断权限，然后再按钮组件上用v-if再继续判断status状态；也遇到了执行时机的问题，总是优先执行v-if

**Comment by tfzzh** [comment]
分拆不同层级的 template就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月24日(周三) 中午1:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [vuejs/vue] 定义一个先于 v-if 执行的指令 (#2060)




 
感谢尤大的耐心解释。 有一种情况不知道是否有更优雅的方式去解决，我的一个组件的显示或隐藏 是来自多个不同维度数据融合判断之后的结果， 举例说明: 我有一个按钮， 首要要判断我这个角色是否有权限使用这个按钮，确认有权限之后，还需要根据后台返回的数据来判断此按钮在某个status字段下是否应该展示， 这就牵扯到不通维度数据管理的问题， 我现在的做法就是在指令中判断权限，然后再按钮组件上用v-if再继续判断status状态；也遇到了执行时机的问题，总是优先执行v-if
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wsyxl365** [comment]
> 分拆不同层级的 template就好了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月24日(周三) 中午1:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [vuejs/vue] 定义一个先于 v-if 执行的指令 (#2060) 感谢尤大的耐心解释。 有一种情况不知道是否有更优雅的方式去解决，我的一个组件的显示或隐藏 是来自多个不同维度数据融合判断之后的结果， 举例说明: 我有一个按钮， 首要要判断我这个角色是否有权限使用这个按钮，确认有权限之后，还需要根据后台返回的数据来判断此按钮在某个status字段下是否应该展示， 这就牵扯到不通维度数据管理的问题， 我现在的做法就是在指令中判断权限，然后再按钮组件上用v-if再继续判断status状态；也遇到了执行时机的问题，总是优先执行v-if — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的 可以抽一个权限组件出来包裹这些复杂需要二次判断的组件， 就是想看看能不能一步解决这些问题且保持优雅，又可以分开维护逻辑 哈哈~。~
