### ISSUE TITLE
link css don't applied in ready hook.

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue#2062]
If I don't use `Single File Components` and `webpack`, and my html template looks like:
```html
<div>
  <link href="/app/component/tootip/tooltip.css"/>
  <div>
    some tooltip template
  </div>
</div>
```
and the tooltip.js looks like:
```js
Vue.component('tooltip', {
    template: require('./tooltip.html', 'html'),
    data: function() {
      return {
        data: {}
      };
    },
    ready: function() {
      // do some position calculation like offsetLeft, offsetWidth
    });
  });
```
I debugged the code and found when `ready` hook is called, the `tootip.css` is still `pending`, so the position attribute like `offsetLeft`,`offsetWidth` is not the actural value that I wanted.
![image](https://cloud.githubusercontent.com/assets/7945757/11924219/f3decd24-a7e8-11e5-9c74-b31438d29e89.png)
Then, how to fix this problem?

**Comment by yyx990803** [comment]
This is because `<link>` triggers an HTTP request to fetch the CSS after it is inserted (which is **asynchronous**). Ready is called synchronously after insertion. It's just the way it works.

Short answer is you should just use Vueify.
