### ISSUE TITLE
微信中的h5界面是否适用？

### ISSUE THREAD

**Issue by zlxbuzz** [vuejs/vue#2063]
目前打算开发一个微信端的h5界面，比较多的数据交互，是否适用呢？谢谢？会不会有低安卓版本不兼容的问题呢？谢谢

**Comment by leebo** [comment]
我现在就在用这块做微信的开发 如果微信升级到最新版本的话 应该兼容性都没什么问题

**Comment by yyx990803** [comment]
请不要用 issue 问这类问题。
