### ISSUE TITLE
change from 1.0.11 to 1.0.12 have problem

### ISSUE THREAD

**Issue by iLexN** [vuejs/vue#2068]
when i upgrade the vuejs from 1.0.11 to 1.0.12 , my app is going wrong.

here is the example : 
1.0.11 : http://jsfiddle.net/5sH6A/236/
1.0.12 : http://jsfiddle.net/5sH6A/237/

the main different is the data cannot load to the input box when the app create.
- 1.0.11 the data can show in the input box correctly
- 1.0.12 the data is empty in the input box , and also update the data to empty(cos the input  box is empty ?)

also try changed the 'ready' to 'created' , 
1.0.11 : http://jsfiddle.net/5sH6A/238/
1.0.12 : http://jsfiddle.net/5sH6A/239/
the result is also not the same.

i guess , the v-model in the input field
1.0.11 the data show in the v-model input field
1.0.12 the v-model updated the data

i may be doing in the wrong way , need some suggestion.

many thank
please forgive my poor engish.

**Comment by simplesmiler** [comment]
This will probably get fixed, but here is a few recommendations:

- Use `v-bind:attribute="expression"` instead of `attribute="{{ expression }}"` unless you have a good reason.
- Do not use `value` attribute alongside `v-model` directive.

**Comment by Vorror** [comment]
Why close it? Shouldn't this issue still get looked at? Especially if it worked in a previous build?

**Comment by yyx990803** [comment]
This is a wontfix because using a `value` binding with `v-model` is redundant and
