### ISSUE TITLE
Vue JS in combation with FastClick = weirdness

### ISSUE THREAD

**Issue by kirkbushell** [vuejs/vue#2071]
Loving Vue JS - great job!

I have a weird problem though with FastClick when being used with it. Events are firing, I';m listening for "click" accurately, Vue JS is not bothered by it, until I try and set the data from the event to an object that is data-bound. It's almost like it doesn't update the rendering of the view for that binding.

The full use-case is I have an exercise selector component, where you select the exercise and then that exercise gets used in an input element on the previous screen. This all works fine until I use FastClick, and again the issue appears to be just the data-binding bit. Everything else is working fine. 

Quite odd.

What's even weirder is that if I duplicate that exercise that has the selected exercise in it, then it shows up in the duplicated exercise in the array, but not the original. It's like the original isn't being rendered or hasn't detected a change.

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by kirkbushell** [comment]
Before I do, is it possible to force the render of an element or component?

**Comment by yyx990803** [comment]
It's possible, but I'd rather figure out what is really wrong than just
forcing re-render.

**Comment by kirkbushell** [comment]
I'd like to do that as well, but I'd like to know if it is indeed an update issue or not, because that's what it feels like but I'm not 100% sure.

**Comment by yyx990803** [comment]
I can't tell until there is a production.

**Comment by kirkbushell** [comment]
Can you just let me know so i can test myself? Does it need to be this difficult to do my own investigation before providing a more thorough report?

**Comment by yyx990803** [comment]
It's an internal API that may or may not be there in the future, and I
don't want people using it. If you insist, you can call vm._digest() on an
instance to force re-render. But the point is, you can just vm.$log() the
state of the component to see if it's a reactivity issue - forcing a
re-render doesn't help much in diagnosing the problem.

**Comment by yyx990803** [comment]
Tbh, I'm not trying to make this hard, it's just people often make wrong assumptions about what is actually causing the issue, and most of the time it's more helpful to provide actual code.

**Comment by kirkbushell** [comment]
Oh I agree, that's why I wanted to investigate further. I wasn't aware of $log, that's perfect - I'll investigate using that and then figure out how the hell to convert .vue to something usable I can demo with :P

**Comment by kirkbushell** [comment]
Okay so quick test on my local, $log() shows all the data applicable to the instance, but isn't rendering. When I call _digest(), it shows up as I expect. So FastClick appears to be getting in the way somewhere with Vue's only calls. What's odd is that the click event is firing, it's getting the right data and back in the parent component it has the data correctly, it's just not re-rendering or updating the required collection of selected exercises.

Anyways, will setup a fiddle/bin and reproduce.

**Comment by yyx990803** [comment]
Closing (inactivity)
Feel free to reopen if you have a repro or more information available.
