### ISSUE TITLE
vue为什么用的时候要加一个new呢

### ISSUE THREAD

**Issue by kyo4311** [vuejs/vue#2073]
new Vue({});
是否可以这样子用呢？vue({})

**Comment by Alexorz** [comment]
当然也能做成你说的那样，设计模式不同罢了。

前者`new Vue({});`通过实例化一个类获得实例对象，后者`vue({})`通过执行工厂方法获得实例对象。

**Comment by yyx990803** [comment]
因为 `Vue` 是一个构建函数，返回创建的实例。
请不要用 issue 问类似的问题。

**Comment by kyo4311** [comment]
嗯！其实我想问的是：作者为什么设计成要用new的。
因为我们看到的jquery，react或是angularjs等，很少有需要用new的，在使用的时候自动返回实例了，
作者这么做肯定有原因的，在设计的时候需要我们使用new
