### ISSUE TITLE
一个vue实例的某个data字符串可否被vue解析

### ISSUE THREAD

**Issue by marzk** [vuejs/vue#2074]
比如说
[演示地址](http://jsfiddle.net/6LLjwthm/3/)
HTML部分
```html
<body>
  <div id="#app">
    {{{ content }}}
  </div>
</body>
```
JavaScript部分
```javascript
new Vue({
  el: '#app',
  data:
    'content': '<span>hello world!</span><demo-component></demo-component>',
  components:
    'demoComponent': xxx
})
```
我想了一个，vue处理的是模板HTML的部分，对其内部的data部分并没有做处理，这是合乎逻辑的。但是如果我想让vue做这个解析的话，应该怎么做呢？

（上面的描述是精简问题后的描述，遇到的真实问题是这样的，做一个CSS文档演示的网站，简单来说就是markdown文件 -> html文件，但是CSS不仅应该有代码还应该有一个展示的区域，我的做法是改一下markdown的render，遇到```demo-html的时候转换为<demo-html>code</demo-html>，然后vue引用组件部分进行处理，但没找到解决方法）

无论是意见还是建议，都十分感谢。

**Comment by yyx990803** [comment]
这里的 markdown -> html 转换是构建时进行的还是运行时进行的？如果是运行时的话不建议这样使用，因为容易导致 XSS。你的用例描述还是不够具体，不太明白为什么要用这样的做法。

**Comment by yyx990803** [comment]
issue 先关掉了，因为不是 bug，但是可以继续讨论。

**Comment by marzk** [comment]
是构建时引入的。

**Comment by marzk** [comment]
项目背景是做了一个css framework，把这个单独发布成一个npm包，里面有markdown文件。又建了一个演示网站的npm包，依赖于这个css framework包，并根据那里面的markdown文件生成一个可以浏览的演示网站。

**Comment by yyx990803** [comment]
那就直接作为组件的 `template` 而不是用 `{{{ }}}` 啊
