### ISSUE TITLE
class="className {{ className }}" cause duplicated result

### ISSUE THREAD

**Issue by ppq1991** [vuejs/vue#2075]
source:

``` html
<div class="icon icon-{{test}}"></div>
```

expect:

``` html
<div class="icon icon-test"></div>
```

result:

``` html
<div class="icon icon- icon-test"></div>
```

here's the code:

https://jsfiddle.net/10ons60y/

 是我的使用姿势不对吗  _(:3」∠)_

**Comment by Nirazul** [comment]
Please see:
http://vuejs.org/guide/class-and-style.html

**Comment by ludo237** [comment]
That's an interesting behaviour, looking forward to some fix

**Comment by smolinari** [comment]
Interesting it hasn't been found sooner. Good catch. 

Scott

**Comment by billcolumbia** [comment]
`<div :class="['icon', 'icon-' + test]"></div>` - [Class Bindings - Array Syntax](http://vuejs.org/guide/class-and-style.html#Array_Syntax)

**Comment by smolinari** [comment]
Nice Bill. Thanks for the solution.

Still, the binding of "test" shouldn't cause "icon-" to be inserted twice, should it? 

Scott

**Comment by billcolumbia** [comment]
@smolinari I would say no. Judging by docs, I just went along with the two default ways to bind classes. Always assumed that interpolation in any attribute value wouldn't work without prefixing with `v-` or `:`

**Comment by smolinari** [comment]
Cool. @pespantelis looks to have figured out the issue. Nice work Pantelis. :+1: 

Scott

**Comment by pespantelis** [comment]
Thanks @smolinari :smiley:
