### ISSUE TITLE
重大bug吗？v-for渲染对象时， 在ios设备上的结果是倒序的

### ISSUE THREAD

**Issue by Blueria** [vuejs/vue#2077]
html如下
```html
<ul id="myVue">
	<li v-for="(key, val) in list">{{key}}</li>
</ul>
```
js如下
```javascript
new Vue({
	el: '#myVue',
	data: {
		list: {
			a: 123,
			b: 456,
			c: 789
		}
	}
});
```

vue.js 版本1.0.10
ios(9.2) 下Safari、Chrome、UC、微信均测试过
测试地址http://jsbin.com/sarowunabe

电脑上效果如下（正常）
![2015-12-24](https://cloud.githubusercontent.com/assets/7038130/11980615/19a73808-a9d7-11e5-92b7-f7e2b494266b.png)
ios上效果如下（倒序）
![img_2660](https://cloud.githubusercontent.com/assets/7038130/11980624/24a92dce-a9d7-11e5-932b-d6aa7302ca99.PNG)

**Comment by pespantelis** [comment]
A user at StackOverflow had the same issue too.
http://stackoverflow.com/questions/33923721/vue-js-v-for-loop-reverses-order-in-safari

**Comment by Blueria** [comment]
已经在#2008 看到这个问题了 +1

**Comment by yyx990803** [comment]
This is expected. `v-for` on object **does not guarantee enumeration order**, it's determined by the JS engine. Use `orderBy` for explicit ordering.

**Comment by Roadirsh** [comment]
@yyx990803 How can we use orderBy with the index ?
