### ISSUE TITLE
Event not fired when calling similar route

### ISSUE THREAD

**Issue by thepratt** [vuejs/vue#2081]
Loving vue.js so far, I appreciate all the work you've put into this!

I don't know if this is an issue, I assume I'm probably doing something wrong.
I'm using vuex 0.2.0 in addition to vue 1.0.8, but the problem doesn't seem to be related to stores.

I have a route with a parameter (called slug; with `canReuse: false`), and a computed value. When I navigate to the same route, with a different slug, the data isn't updated. `attached()` is never called, even though `canReuse` is `false`. It works with the if statement I have inside the computed value, but I'm assuming this is the wrong way to go about it.

routes.js
````
export default function (router) {
    router.map({
        ...
        'user': {
            name: 'userSearch',
            component: UserSearchView
        },
        'user/:slug': {
            name: 'userProfile',
            component: UserProfileView,
            canReuse: false,
            subRoutes: {
                '/': {
                    component: UserProfileTimelineView
                },
                'timeline': {
                    name: 'userProfileTimeline',
                    component: UserProfileTimelineView
                },
                'gallery': {
                    name: 'userProfileGallery',
                    component: UserProfileGalleryView
                },
                ...
````

UserProfileView.vue
````
<script lang="babel">
import store from '../../store'
const { getUserBySlug } = store.actions

export default {
    computed: {
        user() {
            if (store.state.currentUserSlug != this.$route.params.slug) {
                getUserBySlug(this.$route.params.slug)
            }

            return store.state.user.data
        }
    },
    attached() {
        getUserBySlug(this.$route.params.slug)
    }
}
</script>
````

Is there some way to force it to re-attach itself to update the data?

**Comment by yyx990803** [comment]
The `canReuse` should be configured under the component's `route` option.
But maybe in the future I will allow it being configured in both places.

**Comment by thepratt** [comment]
@yyx990803 Thanks!

This is the wrong project for this, but it could be useful for an example, or more explanation around the location of these options; just that they apply to `route: {}` in the component. I assume this applies to all listed in http://vuejs.github.io/vue-router/en/pipeline/index.html?

Merry Christmas.
