### ISSUE TITLE
vm.$set(): [Vue warn]: You are setting a non-existent path...

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#2084]

**Comment by ludo237** [comment]
I think you have put the description of the issue into the title :worried:

**Comment by posva** [comment]
You just copy pasted the console warning... Provide a repro ad show some interest when creating an issue, otherwise you'll just get ignored...

**Comment by ludo237** [comment]
And closed :skull:

**Comment by yyx990803** [comment]
Please be more specific on the issue. Closing until more descriptions are provided.

**Comment by fenivana** [comment]
Sorry I haven't think clearly whether it's vue's issue or I did it in a wrong way when I created the issue, and then I put it aside and lately forgot it totally..

**Comment by ludo237** [comment]
ping @yyx990803

**Comment by smolinari** [comment]
@fenivana - have you looked at vue-strap?

https://github.com/yuche/vue-strap

Scott

**Comment by fenivana** [comment]
@smolinari Here I said "bootstrap" means a boot loader, the entry point of app.js, rather than the bootstrap css framework.

**Comment by smolinari** [comment]
Doh! Sorry I mentioned anything. LOL!

Scott

**Comment by fenivana** [comment]
Hi @yyx990803 , if you have time, please check it. Thanks you very much :)
