### ISSUE TITLE
mustache in class compiles to undefined

### ISSUE THREAD

**Issue by xuanyan0x7c7** [vuejs/vue#2085]
```javascript
var child = {
  template: '<div class="one"></div>'
}
var parent = {
  template: '<child class="pre-{{name}}"></child>',
  data() {
    return {name: "two"}
  },
  components: {child}
}
```
It compiles to `<div class="one pre-undefined"></div>`.
The bug won't appear if there is no class attribute on the root of child component.

**Comment by yyx990803** [comment]
Note after the fix, the parent class will overwrite the child class. This is because `class="{{ abc }}"` always sets the entire class. If you want to preserve child class you should still use `v-bind:class` instead.
