### ISSUE TITLE
how to run with nodejs

### ISSUE THREAD

**Issue by tigernassau** [vuejs/vue#2086]
can vue be run from nodejs? or need simple webpack config that runs on linux

**Comment by divmgl** [comment]
What are you trying to accomplish?

I'm sure Vue.js can run on a Node.js server; you'll just need something like JSDOM to emulate the `window`. But I don't know what you're trying to do.

**Comment by yyx990803** [comment]
Please ask questions in Gitter or on the forum.

Regarding your question - Vue currently needs jsdom to render things in Node.
