### ISSUE TITLE
About css reflow

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue#2087]
This is my [tabset example](http://codepen.io/erguotou520/pen/YwGEZB?editors=101), I used `Bootstrap` css frame.
In `tab` template, if I change the code
```html
<div class="tab-pane fade" v-el:panel :class="{active:active,in:in}">
```
to
```html
<div class="tab-pane fade" v-el:panel :class="{active:active,in:active}">
```
No animation works. I debugged `Bootstrap`'s code and found this
```js
element[0].offsetWidth // reflow for transition
```
So, this is the `css reflow`'s problem. Then my code looks like
```js
this.$nextTick(function() {
  this.$els.panel.offsetWidth;  // force css reflow
  this.in = isActive;
});
```
It works fine, but I have another solution:
```js
setTimeout(function() {
  self.in = isActive;
}, 0);
```
Which is better? Or which is more vue's style? Or other solution?

**Comment by yyx990803** [comment]
`setTimeout(0)` doesn't always guarantee a reflow (for example in Firefox). Prefer explicitly forcing reflows.
