### ISSUE TITLE
在传递一个参数为对象时，如果对象里含有对象，那接受到的对象里面那个参数对象为 undefined

### ISSUE THREAD

**Issue by AnyGong** [vuejs/vue#2088]
RT：问题重现是在事件传递参数的时候，测试打印出来的是 undefined。
eg：

`<div @click="test( {  a :"a" ,  aa: { value: "aavalue" }     } )">`

在test 事件里面可以获取到 `a`对象的值，但获取不到 `aa` 这个对象以及他的值，打印出来的是 undefined。请问是bug吗?

**Comment by yyx990803** [comment]
Cannot reproduce. Please provide a reproduction.

**Comment by mage3k** [comment]
@AnyGong 
```
<div @click="test( { a :"a" , aa: { value: "aavalue" } } )">
```
把参数里的双引号换成单引号

**Comment by yyx990803** [comment]
Closing (inactivity)
