### ISSUE TITLE
Watched properties start to update only after deletion

### ISSUE THREAD

**Issue by fzaffa** [vuejs/vue#2089]
I have encoutnered what I think is a bug. First here is the codepen to reproduce it http://codepen.io/anon/pen/dGOMMO?editors=101

Now, if the watched property is an array of objects and only a property of one of those object is changed then the watch callback is not called, but, if I delete one of the elements then any other subsequent change is properly tracked down.

To reproduce it try to change any of the properties in the input fields, then try deleting one (by pressing X), then try to change again some property.

**Comment by pespantelis** [comment]
To detect nested value changes inside Objects, you should enable the `deep` option:

````js
watch: {
  'people': {
    handler: function() {
      this.peopleWatched = this.people
    },
    deep: true
  }
}
```

http://vuejs.org/api/#watch
