### ISSUE TITLE
v-if, v-show and v-else

### ISSUE THREAD

**Issue by berryliu** [vuejs/vue#2090]
发现 v-else 可以和 v-if 在同一元素连用，达到 elseif 的效果，
但是 v-else 和 v-show 不能，即达不到 elseshow 的效果。
但是 v-if 和 v-show 元素都可以接 v-else 元素，不知道 v-if 与 v-show 除了是不是惰性渲染的区别，还有与 v-else 连用的区别？
感谢！

**Comment by xgqfrms-GitHub** [comment]
https://vuejs.org/v2/guide/conditional.html
