### ISSUE TITLE
vue在created前，我需要对当前模板进行自定义包裹时候无法操作

### ISSUE THREAD

**Issue by cevio** [vuejs/vue#2092]
我希望得到这样的代码：
new Vue({
       el:el,
        name: 'webview',
        props: {
            name: {
                type: String,
                required: true
            }
        },
        created: function(){
            //console.log(this)
            //browser.createWebview(this.name, this);
            this.$parent.createWebview(this.name, this);
        },
        template: function(html){
            return '<div>' + html + '</div>'
        }
    }
});

我希望template可以变为自定义。但是现在貌似只能是字符串。是否可以解决？还是有其他方式处理？

**Comment by yyx990803** [comment]
Vue 的模板可以理解为**对状态到 DOM 的映射关系的一种描述**，你应该用 Vue 的模板本身提供的逻辑原语比如 `v-if` 和 `v-for` 来描述这种映射，而不是用拼接字符串的思路去做这样的事情。如果需要动态组合模板，用 slots 和 partial。
