### ISSUE TITLE
Computed properties cannot depend on computations

### ISSUE THREAD

**Issue by phroggyy** [vuejs/vue#2093]
Currently, if I have the following

```
data: {
    date: moment()
},
computed: {
    monday: function () {
        return this.date.isoWeekday(1).format('d');
    }
}
```

my `monday` variable will not be updated if `date` is updated. Vue would be aware of the dependency for `this.date.isoWeekday(1)`, but since `monday` is dependent on modifying `this.date`, it somehow does not work.

Here's a JSFiddle demonstrating it:
https://jsfiddle.net/r03bd488/3/

As you can see, none of the computed properties update, despite updating the dependency (which is changing, see console log)

**Comment by yyx990803** [comment]
I think you misunderstood how Vue's reactivity works. A `moment()` object is a blackbox with its own complex internal state. It's not a plain data object that Vue can guarantee to observe.

See more at http://vuejs.org/guide/reactivity.html
