### ISSUE TITLE
scoped css with content distribution

### ISSUE THREAD

**Issue by rascada** [vuejs/vue#2094]
Component scope css rules didn't applies to elements in slot.

![image](https://cloud.githubusercontent.com/assets/10521222/12037107/18c9416e-ae4c-11e5-80da-77c83e66481a.png)

**Comment by ludo237** [comment]
Could you provide a jsfiddle?

Also, what `_v-40..` stand for?

**Comment by yyx990803** [comment]
That's intended. Slot content is considered from parent and thus styled by the parent.

**Comment by yyx990803** [comment]
Actually, there might be a better way to handle this. But let's move this to `vue-loader`.
