### ISSUE TITLE
how to implement the countdown using vuejs？

### ISSUE THREAD

**Issue by zchking** [vuejs/vue#2099]

**Comment by ludo237** [comment]
This is not place for this kind of question!

**Comment by amirrustam** [comment]
@zchking please us the Vue community forum (http://forum.vuejs.org) or StackOverflow (http://stackoverflow.com/questions/tagged/vue.js) for these types of questions. The issues section within Github is for reporting potential bugs or providing feedback to enhance the project.

**Comment by azamat-sharapov** [comment]
Looks like it's for new year countdown and he needs it urgently :D 

https://jsfiddle.net/jtcpmrgf/

Happy new year and make sure you read contribution notes in new year :trollface:

**Comment by zchking** [comment]
thanks, Happy new year!

**Comment by LAMike310** [comment]
@azamat-sharapov you're a hero!
