### ISSUE TITLE
MVVM费内存的问题

### ISSUE THREAD

**Issue by strrchr** [vuejs/vue#2103]
发现每个ViewModel实例都要关联一堆getter、setter对象，看起来很耗费内存，比如一个1000个元素的列表，每个元素都有一份getter、setter对象的内存占用。
如果把修改操作做成全局函数就能消除这部分内存开销，代价是语法上不方便，不能直接赋值了，得调用函数去赋值，如：
```
Vue.set(object, propertyName, propertyValue);
```
不知道我纠结的这个内存问题是不是个问题？

**Comment by yyx990803** [comment]
请不要用 issue 问这类问题...

getter setter 本身只是函数，并不占多少内存。真正占内存的是依赖追踪相关的开销，比如 Dep。

但是说回来，在你实际上遇到性能瓶颈之前纠结这种问题毫无意义...
