### ISSUE TITLE
Changing limitBy limit through data doesn't seem to work

### ISSUE THREAD

**Issue by larsboldt** [vuejs/vue#2105]
While changing offset using this method seem to work, changing limit doesn't re-render the list correctly after a value change. Changing value in select box correctly updates data.limit, but the list seem to end up without a limit afterwards and nothing happens on further changes.

See: http://jsbin.com/mucexutenu/edit?html,output

**Comment by yyx990803** [comment]
This is because the `<select>` value is a string instead of a number. This probably should work even if it's a string, but before the next release you can just add `number` on `<select>` to force its value to be a number.
