### ISSUE TITLE
Does Vue.js support content-less components (e.g. <my-component /> ) ?

### ISSUE THREAD

**Issue by cristianpascu** [vuejs/vue#2107]
Hello, love your framework! I have noticed that when using components without a closing tag, Vue.js will only render the first item and ignore the rest. Please see a test case here: https://jsfiddle.net/jx73sqp0/

When using &lt;tag v-for="item in items" /&gt;, however, it works fine. 

Am I doing something wrong or missing something?

**Comment by yyx990803** [comment]
Vue templates are valid HTML5, and HTML5 doesn't support self closing tags.

**Comment by cristianpascu** [comment]
Got it! Thanks for your response! :)
