### ISSUE TITLE
如何让表格动态显示

### ISSUE THREAD

**Issue by mumofa** [vuejs/vue#2110]
初学vue 想做个动态显示的表格
这是html结构

    <div v-cloak id="table">
        <button v-for="button in tables" @click="change($index)">
            {{$index}}
        </button>
        <table>
            <thead>
            <tr>
                <th v-show='tables[0]'>一</th>
                <th v-show='tables[1]'>二</th>
                <th v-show='tables[2]'>三</th>
                <th v-show='tables[3]'>四</th>
                <th v-show='tables[4]'>五</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th v-show='tables[0]'>一</th>
                <th v-show='tables[1]'>二</th>
                <th v-show='tables[2]'>三</th>
                <th v-show='tables[3]'>四</th>
                <th v-show='tables[4]'>五</th>
            </tr>
            </tbody>
        </table>
    </div>

js

    var table = new Vue({
        el : '#table' ,
        data : {
            tables : [true,true,true,true,true] ,
            ok : true ,
            false : false
        } ,
        methods : {
            change : function(index){
                table.tables[index] = !table.tables[index];
            }
        }
    });

点击按钮的时候 让表格显示或隐藏 为什么data里面的数据改变了也没用变化
是要改成双向绑定才有效果吗？
还是有其他更好的方法？

**Comment by yyx990803** [comment]
**请不要用 issue 问问题，issue 只接受 bug 或者 feature request**
问问题请到论坛。
