### ISSUE TITLE
safari浏览器下+vue作用域内，for in 会出现两次重复循环

### ISSUE THREAD

**Issue by Joey-93** [vuejs/vue#2111]
这里是Demo (http://jsbin.com/xuwoni/edit?html,js,output)

分别用Safari和其他浏览器就可以看到其中的区别

**Comment by yyx990803** [comment]
用 for ... in 循环数组本来就是应该避免的用法，因为不能保证循环的都是 index。请用正常的 for loop 或者 forEach.
