### ISSUE TITLE
v-for transition duplicated items

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue#2112]
This seems to occur when setting `transition-duration` on the transitioning element.

[Fiddle](http://jsfiddle.net/wmztxg9z/)

**Comment by yyx990803** [comment]
Vue uses the `transition-duration` property to detect possible transitions. You are giving the element a transition duration but not specifying a property to transition for, so no transition is actually going on. The leaving transition hangs waiting for something to happen.

With proper transition: http://jsfiddle.net/yyx990803/wmztxg9z/2/

**Comment by decademoon** [comment]
Do I have to provide both `v-enter` and `v-leave` transition classes? What if I only want an entrance transition? I found that if I omit `v-leave` then I still get duped items (for the reason you mentioned), so what I did was just:

```
&.v-leave {
  display: none;
}
```

which seems to work. Is this the correct way to do it?

**Comment by yyx990803** [comment]
You can just override `.v-leave` with `transition-duration: 0`

**Comment by decademoon** [comment]
Thanks for your help.

**Comment by decademoon** [comment]
I was playing around with this again today and `transition-duration: 0s` does not work on Safari when `.v-transition` has multiple animated properties (but not using `all`). I get duplicated items. This only happens on Safari, not Chrome or Firefox.

Try this [fiddle](http://jsfiddle.net/wmztxg9z/7/) in Safari if possible. In the meantime, I'll stick to `display: none` which seems to work fine.
