### ISSUE TITLE
Triple Handlebars doesn't always render raw HTML

### ISSUE THREAD

**Issue by NomNomCameron** [vuejs/vue#2113]
I am trying to bind an `svg` element from an object held in the VM's `data`

When binding to it in the template using triple handlebar syntax, it still renders in the template as if `toString()` were called on the element.

An example of this can be found here:
https://jsfiddle.net/zba31mnw/

I am fetching an `svg` here over AJAX and assigning the XML from the response to the data that gets bound to the template.

**Comment by yyx990803** [comment]
You are passing the triple handlebars an SVG element, not the actual markup string...

fixed: https://jsfiddle.net/yyx990803/zba31mnw/1/

**Comment by NomNomCameron** [comment]
thank you so much @yyx990803
