### ISSUE TITLE
vue $set with numeric key in path throws invalid expression

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#2115]
My VM has an object as data, and I wanted to add an object based on it's ID to it, but when using `vm.$set` with a path that has numeric keys, Vue throws an invalid expression warning. 

See: https://jsfiddle.net/ps5dssLn/1/
The problem here is the `'.' + id` part. The ` + type ` part works fine. This only occurs if the key is numeric only.

**Comment by yyx990803** [comment]
Well, this is because `components.components1.1` is not a valid JavaScript keypath. You need to make it `components.components1[1]`.
