### ISSUE TITLE
Vue with Ionic?

### ISSUE THREAD

**Issue by DarrylD** [vuejs/vue#2116]
I think the concept of Ionic is awesome but, to remove angular and use vue instead would be very interesting. Obviously not everything can be easily ported over (their js components for example) but, I think the css components would be a good start.

Has anyone tried or thought about this mash up?

**Comment by yyx990803** [comment]
Sorry, but please ask this type of questions on the forum. Issues are for bugs and core feature requests.

**Comment by smolinari** [comment]
Link to forum -> http://forum.vuejs.org/

Scott
