### ISSUE TITLE
Vue.js seems not compatible with OnsenUI

### ISSUE THREAD

**Issue by wildtang** [vuejs/vue#2117]
I tested Vue.js with Onsen UI 2 beta today,
The Vue binding below not works, but if I modify ons-navigator to div, Vue binding works.
Can anyone tell me how to let Vue.js compatible with Onsen UI? thanks.

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    
        <title>Onsen UI 2 Quick Start</title>
    
        <script src="lib/vue/dist/vue.js"></script>
    
        <script src="lib/onsenui/js/onsenui.js"></script>
    
        <link rel="stylesheet" href="lib/onsenui/css/onsenui.css" type="text/css" media="all" />
        <link rel="stylesheet" href="lib/onsenui/css/onsen-css-components.css" type="text/css" media="all" />
    
        <script>
        </script>
    
        <style>
            .page__content {
                margin: 50px;
            }
    
            .login-form {
                text-align: center;
                width: 80%;
                margin: 60px auto 0;
            }
    
            input[type=email], input[type=password] {
                display: block;
                width: 100%;
                margin: 0 auto;
                outline: none;
                padding-top: 24px;
                padding-bottom: 24px;
            }
    
            .login-button {
                width: 100%;
                margin: 0 auto;
            }
    
            .forgot-password {
                display: block;
                margin: 8px auto 0 auto;
                font-size: 14px;
            }
    
        </style>
    </head>
    
    <body>
    
    <script src="cordova.js"></script>
    
    
    <div id="app">
    
        <ons-navigator title="Navigator" id="pageNavigator">
    
            <ons-page >
                <ons-toolbar>
                    <div class="center">{{title}}</div>
                </ons-toolbar>
    
                <div class="login-form" id="vapp">
                    <input type="email" class="text-input--underbar" placeholder="{{email}}" value="">
                    <input type="password" class="text-input--underbar" placeholder="Password" value="">
                    <br><br>
                    <ons-button modifier="large" class="login-button">Log In</ons-button>
                    <br><br>
                    <ons-button modifier="quiet" class="forgot-password" onclick="gotoIndex()">Forgot password?</ons-button>
                </div>
    
            </ons-page>
    
        </ons-navigator>
    
        <ons-template id="page1.html">
            <ons-page>
                <ons-toolbar>
                    <div class="left">
                        <ons-back-button>Back</ons-back-button>
                    </div>
                    <div class="center">{{title}}</div>
                </ons-toolbar>
    
                <div style="text-align: center">
                    <br />
                    <ons-button modifier="light" onclick="pageNavigator.popPage()">
                        Pop Page
                    </ons-button>
                </div>
            </ons-page>
        </ons-template>
    </div>
    
    <script>
        var pageNavigator = document.getElementById('pageNavigator');
    
        var appVue = new Vue({
            el: '#pageNavigator',
            data: {
                email: 'please enter your mail',
                title: 'Quick Start'
            }
        });
    
        function gotoIndex() {
            pageNavigator.pushPage('page1.html');
        }
    </script>
    
    </body>
    </html>

**Comment by ferry77** [comment]
have you tried to change the delimiter?
Vue.config.delimiters = ['${', '}']

**Comment by yyx990803** [comment]
It seems OnsenUI compiles the page asynchronously. When `new Vue()` is called the page hasn't finished upgrading the custom elements yet. If the `new Vue()` is called after say 100ms it works properly. This can probably work if OnsenUI provides a hook so that we know it has finished compilation.

However, this is not really Vue.js' problem, so I'm closing this issue.

**Comment by wildtang** [comment]
Thanks for your reply :)
