### ISSUE TITLE
is there any plan for "vue-native"?

### ISSUE THREAD

**Issue by ferry77** [vuejs/vue#2119]
Hi @yyx990803 
Thanks for your great work.. I enjoy Vue so far.
This question just across my head, is there any way or do you have plan to bridge Vue to React-Native? 

Thanks again

**Comment by yyx990803** [comment]
Native bridge is very complex in scope and it's unlikely for me to work on it alone. The closest thing I know is that Alibaba (the Amazon of China) is working on a project called Weex that uses Vue's component syntax to render to native components. It's not open source yet but they plan to do so later this year.

**Comment by smolinari** [comment]
What would be the advantage of doing such a bridge?

Scott

**Comment by yyx990803** [comment]
@smolinari native performance, that's the only advantage ;)

**Comment by smolinari** [comment]
I could understand a Vue-Native. That would be totally cool and it sounds like Weex might be that kind of project. 

You'll probably do it anyway, but I will ask anyway. :smile: Can you please make it a point to announce it everywhere you can, when Weex does go open source? Or is there a way I can follow the project's status myself?

Scott

**Comment by YerkoPalma** [comment]
> project called Weex that uses Vue's component syntax to render to native components

Is only Vue syntax without Vue? or they are actually working from Vue? I mean, are they using Vue source or just mimic the syntax?

**Comment by yyx990803** [comment]
@YerkoPalma currently it's not full Vue, but they do use part of Vue's source code. We are talking about future collaboration.

**Comment by YerkoPalma** [comment]
Awesome, then is just a matter of time to have Vue native around :+1:

**Comment by smolinari** [comment]
And the announcing or self-tracking?

Scott

**Comment by yyx990803** [comment]
@smolinari I'll definitely announce it when it's time, but it's too early to say for now

**Comment by smolinari** [comment]
Super! Thanks. 

Scott

**Comment by ferry77** [comment]
Thanks Evan.. This is great news and hopefully it happens soon :)

**Comment by eljefedelrodeodeljefe** [comment]
Would be happy if  this continues. To tighten the scope: it's especially useful having native drawer menues that route to vue and maybe integrating native views on top of vue when performance is really needed. The performance for vue on the mobile client is already really good.

I tried react-native and find it to be a little overkill.

**Comment by qusiba** [comment]
@eljefedelrodeodeljefe [Weex](http://alibaba.github.io/weex/) is coming...

**Comment by eljefedelrodeodeljefe** [comment]
@qusiba thx for the link 👍

**Comment by smolinari** [comment]
@qusiba - I signed up, but nothing happened. How long is the wait to get access?

Scott

**Comment by Jinjiang** [comment]
@smolinari Thx for signing, I am a member of the team. We will invite you all for private github permission soon.

**Comment by smolinari** [comment]
@Jinjiang - can you define "soon" a bit better? Are we talking days, weeks or months? :smile: 

Scott

**Comment by fnlctrl** [comment]
@Jinjiang I've only subscribed to the mailing list, could I have access too? :smile:

**Comment by ferry77** [comment]
@Jinjiang me too please :)

**Comment by Jinjiang** [comment]
@smolinari just a few days

**Comment by jpokrzyk** [comment]
@Jinjiang Could you add me to the private beta please. Thanks!

**Comment by smolinari** [comment]
@jpokrzyk - you have to simply sign up for the newsletter.

http://alibaba.github.io/weex/#subscriptionWeex

Scott

**Comment by Jinjiang** [comment]
done @jpokrzyk @smolinari

**Comment by smolinari** [comment]
@Jinjiang - so have you gents at Alibaba been helping out Evan with Vue 2.0? That is some really cool stuff! :smile: 

Scott

**Comment by Jinjiang** [comment]
Weex will be public maybe the end of June. Just keep watching :-)

**Comment by smolinari** [comment]
@Jinjiang - I am going to assume public also means open sourced, which I applaud. :clap: :smile: 

Scott

**Comment by ferry77** [comment]
@Jinjiang just a dumb question.. why don't you put 'Native' on the headline copy on http://alibaba.github.io/weex/?
such as, "A framework for building **Native** Mobile cross-platform UI"

**Comment by azamat-sharapov** [comment]
Also, I couldn't find word Vue anywhere. First thing I did, was searching for word *Vue*, when opened your page. I thought maybe you don't use Vue.js source there, just style, but after Evan's post on Vue.js 2.0, I'm thinking Weex should give some credit to Vue on their page..

**Comment by smolinari** [comment]
Look at the code examples. It uses Vue extensively. :smile: 

Scott

**Comment by YerkoPalma** [comment]
Yes, there is even a branch for Vue 2.0. But I think that he is talking about the Weex site, there is no reference to Vue, but I think that site is really provisory, and will be dramatically changed when Weex get published. I hope that then it includes some Vue.js references.

**Comment by rclai** [comment]
Is [this repo](https://github.com/weexteam/weex-vue-framework) at all related?

**Comment by smolinari** [comment]
This is the right repo for Weex.

https://github.com/alibaba/weex

Scott

**Comment by rclai** [comment]
Yes, but I'm pretty sure the Vue-powered Weex work seems to be happening in the repo I mentioned.

**Comment by CodelabStudios** [comment]
great stuff! finally an alternative to React Native or Ionic. This is huge for the Vue.js community

**Comment by smolinari** [comment]
I'd also like to bring attention the Quasar Framework. Someone has already mentioned they've created iOS and Android apps with this framework. They are also porting to Vue 2.0 as we speak. 

http://quasar-framework.org/

Scott

**Comment by ljanecek** [comment]
Onsen UI for Vue.js
https://onsen.io/vue/

But it's not like React Native.

**Comment by mg1075** [comment]
It would be great if NativeScript had support for Vue.
I added my vote for Vue support on the NativeScript ideas site.

- https://nativescript.ideas.aha.io/?sort=popular

Look for the idea called "Vue.js support in NativeScript".

**Comment by nesbocaj** [comment]
Adding to what @mg1075 said, there's also a github issue concerning this: NativeScript/NativeScript#2437 wherein @valentinstoychev among other things says the following:

> I want to encourage someone who has a good knowledge of the internals of Vue.js to get in touch with us and we can help him with guidance and development to enable Vue.js in NativeScript. It will be a great experience for us to work together.
>
>—
>[#2437 (comment)](https://github.com/NativeScript/NativeScript/issues/2437#issuecomment-254188595).

**Comment by mika76** [comment]
Hi Evan ( @yyx990803 ) the guys at Nativescript were looking for some help implementing Vue with Nativescript : https://github.com/NativeScript/NativeScript/issues/2437#issuecomment-254188595
I can't think of anyone better 😄

**Comment by 7ammer** [comment]
The [Weex project](https://github.com/alibaba/weex) has [moved](https://github.com/apache/incubator-weex/) to the Apache Software Foundation. Not sure what that means for the project.

**Comment by nesbocaj** [comment]
I don't know if you guys are already aware, but it seems stuff is happening with regards to the Vue NativeScript implementation:

> We have started on a community-led initiative to port NativeScript for Vue.js! Take a look at our Community Slack in the #vue channel. The very initial steps are being taken by Igor here: https://github.com/rigor789/nativescript-vue and we need PRs and lots of help! Please join us!
—
[https://nativescript.ideas.aha.io/ideas/NS-I-94 (comment).](https://nativescript.ideas.aha.io/ideas/NS-I-94)

**Comment by mg1075** [comment]
...just came across this very interesting tweet from Max Lynch of of [Ionic](http://ionicframework.com/) about supporting VueJS (and other frameworks):

https://twitter.com/maxlynch/status/861597030132596737

![image](https://cloud.githubusercontent.com/assets/2031435/25853789/92470a20-3493-11e7-8560-7dc598ff0113.png)

**Comment by nesbocaj** [comment]
That's cool and all @mg1075 but Ionic is actually not native:

> Ionic emulates native app UI guidelines and uses native SDKs, bringing the UI standards and device features of native apps together with the full power and flexibility of the open web. Ionic uses Cordova or Phonegap to deploy natively, or runs in the browser as a Progressive Web App.
—
http://ionicframework.com/

Still awesome that Ionic supports Vue though. 👍

**Comment by mg1075** [comment]
@nesbocaj - One of the draws for Ionic is their support for Progressive Web Apps. 

Interesting discussion on PWA's here:
http://www.dotnetrocks.com/?show=1381

**Comment by coderabsolute** [comment]
Guys, Am getting familiar with VueJs but now the requirements arise for the mobile development to maintain single code base (as much as possible) to support iOS and android platform, the app must also support the Push Notifications. I know this thread is almost a year old, what choices do I have now? Please help me!!!

**Comment by rof20004** [comment]
@codelabstudios Quasar framework: http://quasar-framework.org/

**Comment by coderabsolute** [comment]
@rof20004 Yes, am exploring the Quasar framework which is awesome!

**Comment by 7ammer** [comment]
Been using quasar for my latest project. The lead developer is very committed to the project and very actively involved in the projects community.

Its worth mentioning that the next version is just a few days away and has many new features:
http://forum.quasar-framework.org/topic/253/future-v0-14-feature-list

**Comment by steffanhalv** [comment]
@yyx990803 Do you know how its going with weex?

Im currently looking at weex 2 documentation which looks uncomplete and shows alot of 'native code (Java and C)' which im trying to avoid and has no clear steps of how to build an .apk.

Also quasar scares me with installation of Android Studio etc. and the alternatives is expanding:

- weex
- native-script
- ionic
- framework7
- quasar
- vue-cordova
- +++

For desktop apps electron works great, but for native mobile apps im still not sure what to use :/

**Comment by Hanks10100** [comment]
Weex is *"A framework for building Native Mobile cross-platform UIs"*. Moreover, with Evan's help, Weex has already supported Vue.js 2.0 as one of its front-end frameworks. In other words, **you can use Vue.js syntax to develop native apps based on Weex.**

@steffanhalv have a good try, that's great!

Most of the Vue.js 2.0 features are still available in Weex platform, except for those web platform-based features, like `v-html` and `x-templates`.

Weex Project has been moved to Apache Software Foundation (ASF), here is latest resources of Weex:

+ Official website: http://weex.apache.org/
+ Respo(mirror of Apache Weex): https://github.com/apache/incubator-weex
+ Mailing list: http://mail-archives.apache.org/mod_mbox/incubator-weex-dev/

**Comment by VSG24** [comment]
Weex has horrible documentation with broken English.

**Comment by reviewher** [comment]
@VSG24 weex is an open source project and you can help clean up the documentation!

**Comment by f3ltron** [comment]
is that weex is like react-native doesnt just render in a webview but create a real native app like react native does?

**Comment by 7immer** [comment]
weex looks well built but its hard to get support for it.
http://nativescript-vue.netlify.com looks nice! Its a little bit behind vs weex but there is more support and you can use many of the existing nativescript plugins: https://market.nativescript.org

**Comment by rof20004** [comment]
@f3ltron 

Like @Hanks10100 said:

> Weex is "A framework for building Native Mobile cross-platform UIs". Moreover, with Evan's help, Weex has already supported Vue.js 2.0 as one of its front-end frameworks. In other words, you can use Vue.js syntax to develop native apps based on Weex.

**Comment by VSG24** [comment]
Guys just forget about any mobile app development solution that uses JS. I have a lot of experience with Cordova, ReactNative and I even recently made an app for iOS using Framework7 + Vue and result is a pretty and unreliable piece of garbage. If you really must do it using a common language, just use Xamarin otherwise go for Kotlin (Android) and Swift (iOS).

**Comment by rof20004** [comment]
@VSG24  I agree.

Today I think PWA is more recommended when I want hibrid app, If not hibrid, I go for Kotlin or Swift.

**Comment by Hanks10100** [comment]
@f3ltron Weex is not based on webview, it rendered native components on the mobile. http://weex-project.io/guide/index.html#native-components

However, Weex also can be downgraded to the web and render pages in the webview.

**Comment by f3ltron** [comment]
@Hanks10100 thanks. @VSG24 how can you say that did you see the compatibility ? lol you just can't do complete hybrid app with pwa actually

**Comment by rof20004** [comment]
@f3ltron No one here says that PWA = Native

**Comment by ellinabereza** [comment]
Another resource which says that it is too soon for Weex https://applikeysolutions.com/blog/weex-review-and-comparison-with-react-native

**Comment by sasivarnan** [comment]
[NativeScript-Vue](https://nativescript-vue.org/) 1.0 is out now and it looks amazing.

**Comment by AndrewBogdanovTSS** [comment]
Just watched a promo live webinar of NativeScript-Vue and it looks amazingly promising! Let's keep it rolling!

**Comment by sanketsahusoft** [comment]
https://vue-native.io/

It's unofficial and it isn't endorsed by the Vue team. And to give you a full disclaimer, I co-authored it.

It's clean, fast, stable, truly native and transpiles to React Native.

**Comment by AndrewBogdanovTSS** [comment]
@sanketsahusoft compiling to React Native feels kinda dirty to me. I would rather prefer NativeScript-Vue which is compiling to native code without a need to involve React as a middle-man

**Comment by sanketsahusoft** [comment]
@AndrewBogdanovTSS Yeah, that may sound dirty but NativeScript-Vue does the exact same thing, instead of using React Native Bridge, it's using the NativeScript Bridge. Though, it also boils down to a personal style of writing. :-)
