### ISSUE TITLE
Using this.set(value) with array in directive

### ISSUE THREAD

**Issue by Daniesy** [vuejs/vue#2120]
I have a custom directive which is meant to handle a select multiple element. The array my directive is bound to - `items` -  is used to generate a list. The directive's bind method looks like this:

    bind: function () {
        var self = this;
        $(this.el)
            .select2({ placeholder: "Select a value"})
            .on('change', function () { 
                var values = [];
                for (var option in this.selectedOptions){
                    if (this.selectedOptions[option].value) {
                        values.push({"id": this.selectedOptions[option].value, "label": this.selectedOptions[option].label});
                    }
                }
                self.set(values)
            })
    },

Whenever `self.set` is called, the `items` value is updated and soon after the whole list is rendered again. This is a **HUGE** problem because i lose every input values in the list. Everything works as expected when using objects instead of arrays: the new selected element is added to the list instead of redrawing the whole list again. I've red in the documentation that Vuejs has some ways of efficiently overwriting arrays, however they don't seem to work in this case. 

[Here's an example of the problem on Codepen](http://codepen.io/daniesy/pen/YwZYyJ).

**Comment by yyx990803** [comment]
You need `track-by="$index"` for primitive values. Vue can track the identity of Objects automatically, but cannot do so for primitive values. That's why you need to give it the permission to update in place instead of a fresh redraw.
