### ISSUE TITLE
Trying to access component from its directive

### ISSUE THREAD

**Issue by eybarta** [vuejs/vue#2121]
Hi, thank you for the Vue framework!!

Not sure I'm going about this the right way, but I was hoping to access my
component back from it's directive.. I was sure `this.vm` would give me
back the component but instead it gives me the parent.. As you can see here:
https://jsfiddle.net/L83h0fvv/4/

I was able to access it using > `this.el.__vue__`, but I'm not sure this is the intended way
of doing this.. 

**Why**: After a method has been invoked inside the directive I want to send a status object
back into the component for further action.

Any thoughts or insights?

Much appreciated.

**Comment by yyx990803** [comment]
Please see http://vuejs.org/guide/components.html#Compilation_Scope

**Comment by boussou** [comment]
you can try the  _directives array.

vm._directives when vm is your vue object
