### ISSUE TITLE
Easier component registration

### ISSUE THREAD

**Issue by jamen** [vuejs/vue#2122]
I think adding the ability to use arrays for component registration would be great.  This way Vue is more flexible for loading multiple components in different objects (i.e. component frameworks).

For example:
```javascript
const foo = new Vue({
  components: [
    require('some-vue-framework'),
    require('another-vue-framework'),
    { 
      'custom-component': { /* ... */ } 
    },
  ]
})
```

**Comment by yyx990803** [comment]
You can write a simple helper to do that. Or just use [`object-assign`](https://github.com/sindresorhus/object-assign):

``` js
components: assign.apply(null, [ ... ])
```

**Comment by jamen** [comment]
Thanks.  :D

**Comment by jamen** [comment]
Could you explain what you mean by it accepting an array?  I didn't see it anywhere in the docs for components.

**Comment by jamen** [comment]
Ah, nevermind.  I see what you mean.

```javascript
var Foo = Vue.extend({
  name: 'foo',
  // ...
});

const example = new Vue({
  components: [ Foo ]
});
```
