### ISSUE TITLE
vue －autoprefixer

### ISSUE THREAD

**Issue by shawushe** [vuejs/vue#2123]
你好：
     昨天请教过，今天再贴出代码请教，用的就是vue.js 版本为Vue.js v1.0.13。
     （这个跟js几乎无关只是创建了实例，所以没有贴js）
html：“<／div v-bind:style="{ color:activeColor, fontSize: fontSize + 'px',borderRadius:'5px',display:'flex' }">纯内嵌</div>”

经过编译后展示在页面：“<／div style="color: red; font-size: 20px; border-radius: 5px; display: flex;">纯内嵌</div>”

教程中（http://cn.vuejs.org/guide/class-and-style.html），提到当 v-bind:style 使用需要厂商前缀的 CSS 属性时，如 transform，Vue.js 会自动侦测并添加相应的前缀。
从我上边的结果来看没有达到这个效果，不知为何。（display:flex和border－radius都应该添加厂商前缀，结果没有）

**Comment by Dafrok** [comment]
建议在生产中用:class代替:style 写几个状态类
使用内联样式有很多局限性 维护也会变得困难

**Comment by shawushe** [comment]
@Dafrok 刚开始了解，你建议的这个肯定是对的，主要在看到这一块的时候，测试发现没有实现这个功能，困惑是这个😄

**Comment by Dafrok** [comment]
@shawushe 最好告知一下你测试用的浏览器版本号。Chrome从36，Firefox从16开始就不需要transform加前缀了，border-radius和flex就更早了。

**Comment by shawushe** [comment]
但是用autoprefixer插件 编译还是会加的，试了下transform也没有加，我用的chrome确实是最新版本的

**Comment by yyx990803** [comment]
:style 用的是运行时前缀探测，不需要的话是不会加的

**Comment by Dafrok** [comment]
autoprefixer是开发环境插件 而vue的runtime是客户端 autoprefixer通过配置项全范围地cover一定比例的浏览器 而不是检测你使用的是什么浏览器

**Comment by shawushe** [comment]
谢谢 我试试别的

**Comment by shawushe** [comment]
@yyx990803  thx，@Dafrok解释的很清楚 thx

**Comment by leftjs** [comment]
@yyx990803 v-bind:style会在runtime检测是否需要添加厂商前缀，:class也会自动添加厂商前缀么
