### ISSUE TITLE
Globally registered components not available within child components

### ISSUE THREAD

**Issue by leon13** [vuejs/vue#2125]
I have a few components registered globally, as they appear sporadically throughout my app. If I try to use one component within another, the one being nested is not compiled.

I may be misunderstanding, but I would have thought a globally registered component would be available everywhere?

It's worth noting that I'm using `inline-template` too.

Here's a JSFiddle outlining my issue: https://jsfiddle.net/ju003gcf/2/

**Comment by yyx990803** [comment]
Global components are registered via the global `Vue.component` method. The way you are defining it makes them local components to the root instance only.

**Comment by leon13** [comment]
Ah, my mistake! Thanks!
