### ISSUE TITLE
Using v-ref and v-el with slot

### ISSUE THREAD

**Issue by saviilsy** [vuejs/vue#2128]
I cannot seem to make v-ref and v-el work with slot.

I have a template with :
```
<template>
  <slot v-el:load v-if="inLoad" name="load"/>
  <slot v-el:error v-if="inError" name="error"/>
</template>
```

But in "ready" function this.$els.load and this.$els.error are undefined. Tried using the v-ref too and same thing.

**Comment by AnyGong** [comment]
hi, I saw a note interface documentation,See description api http://vuejs.org/api/#vm-els, 
So I think the reason is because `slot` not dom element ?

**Comment by AnyGong** [comment]
@yyx990803 ,顺便我也问个问题`[英文单词不好，见谅]`

var mixins=require('./components/mixins')
var app = new Vue({
    mixins:[mixins],
    el: 'body',
    replace: false,
    template: '<app title="hello"></app>',
    components: {
        app: require('./components/partial/head.vue')
    },
})
我想问的是2个问题，
1.  该js里面如何知道，components 里面的组件是加载完毕的状态，就是组件在当前页面渲染完毕，并显示出来。因为我想在 components 里面组件加载完毕之后，再执行 action，用组建的 asyn 绑定的话，这是个方案吗？
2.  如果在 head.vue 里面有没一种方法，按块渲染显示，例如
`<template>
    <div>
           <p>优先显示</p>
           <span>{{ title }}</span>
   </div>
</template>`
p元素优先显示，用户可以看得到，span元素等待显示
这是我项目想到的一些优化方案，求解答。
`ps：文档看了很多次，一直在死磕，可能底层功力有限，还是有些不太明白，麻烦你解答一下，谢谢`

**Comment by saviilsy** [comment]
Hi!

Yes that could be, but on the parent I am giving the slots an element, so in the parent :
```
<loader @load="onLoad" @error="onError" v-ref:loader>
    <div slot="load">
      <i class="fa fa-circle-o-notch fa-spin fa-2x"></i><br/>
      <span style="color:rgb(0,0,0);">{{loadingText}}</span>
    </div>
    <div slot="error">
      <i class="fa fa-exclamation-triangle fa-2x"></i><br/>
      <span style="color:rgb(255,0,0);">{{errorText}}</span>
    </div>
  </loader>
```
and in the child :
```
<template>
  <slot v-el:load v-if="inLoad" name="load"/>
  <slot v-el:error v-if="inError" name="error"/>
</template>
```

so should it at least on theory work because the slots are occupied (granted, only when v-if is satisfied).

I tried to do this with dynamic component :is but i would need a programmatic access to component structure to add and replace components at will.

Or is this related to the issue having programmatic access to slots ?

**Comment by yyx990803** [comment]
@saviilsy the idea here is that the only directives respected on `<slot>`s are terminal directives like `v-if`. Normal ones like `v-el` are not copied onto the inserted elements. This should be mitigated once we have programatic access to the slots. For now, you can wrap the `<slot>` in an additional element where `v-el` can work properly.

@AnyGong your question seems to be unrelated to the original issue, please use the forum instead.
