### ISSUE TITLE
State managment in components

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue#2129]
I try to use store module in my project, the store looks like:
```js
module.exports = {
  state: {
    login: false
  },
  setLoginState: function(login) {
    this.state.login = login;
  }
};
```
And my component code looks like:
```js
Vue.component('some-component', {
    template: require('./some-component.html'),
    data: function() {
      return {
        isLoggedIn: store.state.login
      };
    }
  });
```
But I found that whatever I changed `store.state.login` to, the `isLoggedIn` always return false(the default value). Then, how to fix it?

**Comment by Nirazul** [comment]
You are setting `isLoggedIn` to the value contained in `store.state.login`. This value is copied, not referenced. It should work, when you change it to an object reference:

```
Vue.component('some-component', {
  template: require('./some-component.html'),
  data: function() {
    return {
      state: store.state
    };
  }
});
```

and then change it like this:

```
this.state.login = true;
```

**Comment by erguotou520** [comment]
Ok, got it, thx.
