### ISSUE TITLE
Relative background-image URLs do not work within .vue

### ISSUE THREAD

**Issue by Phunky** [vuejs/vue#2131]
Relative background-image URLs don't seem to be resolving correctly within .vue files, i've tested this on sass and vanilla css.

Using the same property values inline within the <template> works as expected. What I have noticed in Chrome at least is that it seems to be missing the host and attempts to load it from the root of Chrome dev tools.

ie: chrome-devtools://devtools/static/img/geos.png instead of http://localhost:8080/static/img/geos.png

**Comment by yyx990803** [comment]
This has been fixed in `vue-loader@^8.0.0`: https://github.com/vuejs/vue-loader-example/issues/43
