### ISSUE TITLE
Extends a components?

### ISSUE THREAD

**Issue by socieboy** [vuejs/vue#2133]
Hi, there is a way to extends a component?

I have to include this event to each one of my components?
```

    events: {
        'userRetrieved': function (user) {
            this.user = user;
            return true;
        }
    },
```

In the main component a retrive the user and broadcast to all nodes, but I find a little bit dirty to declare the same method on each component, there is a way to extend the component from other that include this event? I'm using browserify

**Comment by jonagoldman** [comment]
http://vuejs.org/guide/mixins.html

**Comment by yyx990803** [comment]
Please do not use issues for questions, as stated in the contribution guide.

**Comment by socieboy** [comment]
Sorry but I already try in the forum and the chat, and it's pretty hard to have some feedback, no body knows to much about Vue, so I take the decition to ask here, and as you see I got pretty fast feedback.

**Comment by Nirazul** [comment]
You could try [Stackoverflow - tagged: vue.js](http://stackoverflow.com/questions/tagged/vue.js) next time. You'll get quite fast feedback.

**Comment by socieboy** [comment]
I just post something in the Chat, no body have something to say.

https://gitter.im/vuejs/vue

**Comment by yyx990803** [comment]
If nobody answers, that means people are either not online, busy or your
question is too generic.

That doesn't justify opening an issue against explicitly stated rules.

**Comment by socieboy** [comment]
what's so wrong to ask for help here?

**Comment by suhaotian** [comment]
@socieboy  :email: :email: :e-mail:

**Comment by yyx990803** [comment]
Because I use issues to track bugs and features, and people using it for
Q&A brings unwanted noise to the system and significantly distracts me.
