### ISSUE TITLE
在iPhone Safari浏览器里无法使用

### ISSUE THREAD

**Issue by jrainlau** [vuejs/vue#2134]
开发了的应用，在iPhone的Safari浏览器里无法编译出来，会显示{{xxx.yyy}}；
而在手机QQ浏览器内是正常的，请问是什么原因呢？

**Comment by yyx990803** [comment]
iOS 版本，重现代码...

**Comment by jrainlau** [comment]
是因为我用的是开发者版本所导致的吗？

**Comment by yyx990803** [comment]
请给重现.......

**Comment by jrainlau** [comment]
因为是公司业务代码不方便直接公开，请问你方便留一个邮箱吗，我通过邮件发给你

**Comment by yyx990803** [comment]
全部的代码我没有时间看... 请自己花点时间缩小问题范围

**Comment by jrainlau** [comment]
当然，我会先研究，然后把可能出现的一小段代码告诉你，这样可以吗

**Comment by ppq1991** [comment]
iOS设备用数据线接OS X ， 开Safari调试模式 ，可以直接debug设备上的浏览器。

可以试试 ，顺便看看有没有什么报错信息。

**Comment by yyx990803** [comment]
Closing (inactivity)
