### ISSUE TITLE
Using Vue with Craft CMS - curly brackets.

### ISSUE THREAD

**Issue by admench** [vuejs/vue#2135]
Hi!

I'm just getting to grips with using vue. I have an issue in that the `{{ curly brackets }}` used with Craft cms twig templates are the same as vue. Is there a way to overcome this? I tried `@{{ $data | json }}` but Craft still throws an `Internal Server Error Unexpected character "$".`

**Comment by smolinari** [comment]
Either with Twig or with Vue, you can change the delimiters as you please. 

Twig: http://twig.sensiolabs.org/doc/recipes.html#customizing-the-syntax

Vue: http://vuejs.org/api/#delimiters

Scott

**Comment by smolinari** [comment]
Oh, and better to use the forum or the gitter room for such questions. Issue on Github are only for bugs or suggestions.

https://gitter.im/vuejs/vue
http://forum.vuejs.org/

Scott

**Comment by admench** [comment]
Thanks Scott :+1:

**Comment by khalwat** [comment]
You can also just use the Twig `{% verbatim %}` tag wrapped around blocks you don't want Twig to interpret
