### ISSUE TITLE
Vue.options.components is empty within a component

### ISSUE THREAD

**Issue by revati** [vuejs/vue#2136]
If i dump `Vue.options.components` from `.js` file it shows all registered elements, but if i do the same in `.vue` file it returns `{}`

Are there any special way to do it?

**Comment by posva** [comment]
are you doing it outside the component instance:

```js
Vue = require('vue')

// Wrong --> {}
console.log(Vue.options.components)

module.exports = {
  ready: function() {
    // Right --> {...}
    console.log(Vue.options.components)
  }
}
```

**Comment by yyx990803** [comment]
Like @posva said, this is most likely due to module import order.

**Comment by revati** [comment]
Thanks, didn't know about ready function
