### ISSUE TITLE
optional "track-by" in list

### ISSUE THREAD

**Issue by ferry77** [vuejs/vue#2138]
Hi,
in relation to http://vuejs.org/guide/list.html#track-by 
Is it possible to set it like 
```
    track-by="_uid || $index"
```
so when there isn't property of _uid it will use $index?

Thanks in advance

**Comment by yyx990803** [comment]
Unfortunately no, it has to be consistent for every element in the array, and it's a plain string, not an expression.

**Comment by ferry77** [comment]
Thanks Evan for your prompt reply,
I was thinking of this because I am creating component where a List can get value from different source, either primitive array (then use $index) or array of object with unique property value (eg: _uid)
Is that make sense though?
