### ISSUE TITLE
Component with another component as template root has $el node as #text

### ISSUE THREAD

**Issue by cristianpascu** [vuejs/vue#2139]
Hello, I may again doing something wrong here, so I apologise for my ignorance in advance, but I am confused. If a component has a template with a standard HTML node, it's $el is set normally as a DOM element. However, it the template has another component as root, it's $el is of type #text 

Could you please tell me what I'm doing wrong? Here's a test case: https://jsfiddle.net/thws9806/ Check the console. 

Thanks!

**Comment by yyx990803** [comment]
See http://vuejs.org/guide/components.html#Fragment_Instance
