### ISSUE TITLE
父组件内容为空和有内容但内容被完全注释掉时，子组件slot显示不一致，是特性还是bug？

### ISSUE THREAD

**Issue by Alexis374** [vuejs/vue#2140]
以文档http://cn.vuejs.org/guide/components.html#u5355_u4E2A_Slot的例子为例，
代码在这里http://jsbin.com/muzuvofiwo/edit?html,console,output（可能再次打开的时候注释被取消掉了）。
如果将my-component内的两个p标签删掉，而将my-component2中的两个p标签注释掉，相同的子组件显示的级结果是不一样的。
不知这个是特性还是bug？

**Comment by yyx990803** [comment]
是特性啊，注释被插入了...
