### ISSUE TITLE
twoWay in Props of component & .sync in v-bind

### ISSUE THREAD

**Issue by zyf0330** [vuejs/vue#2141]
我发现twoWay不起作用，不论是true还是false，只有设置了.sync才会双向绑定。或许我理解错了twoWay的使用情况？

**Comment by yyx990803** [comment]
对，twoWay 只是要求，必须设置 `.sync`。有警告的。

**Comment by zyf0330** [comment]
另外一个相关的就是，在双向绑定时，使用计算属性，内属性值修改后，会出现：内属性get一次用于外属性set一次，然后外属性又get一次用于内属性set一次。后一半我想不应该出现吧，这样双向绑定就变成始终以外设置内收尾了。

On Mon, Jan 11, 2016, 09:59 Evan You <notifications@github.com> wrote:

> 对，twoWay 只是要求，必须设置 .sync。有警告的。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vuejs/vue/issues/2141#issuecomment-170415828>.
>
-- 

追随
