### ISSUE TITLE
v-resource breaking tests

### ISSUE THREAD

**Issue by YerkoPalma** [vuejs/vue#2142]
I'm using Karma and Jasmine to make unit testing in my Vue app. It works fine with almost all of my components, but when I try to test some components that use the `v-resource` plugin, the test breaks. What exactly breaks is the browser that launch the tests, I tried with `PhantomJs` and `Chrome`. I'm not pretty sure if this is a Vue bug, or if it is normal behaviour and I have to make some work around like using `jasmine-ajax` or something.

**MY component**

    var Vue = require('vue');
    module.exports = Vue.extend({
    template: "#userstemplate",
    data: function () {
        return {
            users: []
        };
    },
    ready: function(){
        this.$http.get('users.json').then(function(response){
            
            this.users = response.data;
        }, function(response){
            
            console.log(JSON.stringify(response));
        });
    });

**My test**

    var Vue = require('vue');
    Vue.use(require('vue-resource'));
    var UsersList = require('../../app/assets/javascripts/users/userslist');

    var usersListInstance = new UsersList();

    describe('addUserInstance', function() {
      it('should get users', function(){
        usersListInstance.$mount();
        var usersLength = usersListInstance.users.length;
        expect(usersListInstance.users.length).toBe(usersLength);
      })
    });

**My karma.config.js**

    // https://github.com/Nikku/karma-browserify
    module.exports = function (config) {
      config.set({
        browsers: ['PhantomJS'],
        frameworks: ['browserify', 'jasmine'],
        files: ['test/unit/**/*.js'],
        reporters: ['spec'],
        preprocessors: {
          'test/unit/**/*.js': ['browserify']
        },
        browserify: {
          debug: true
        },
        // if you want to continuously re-run tests on file-save,
        // replace the following line with `autoWatch: true`
        singleRun: true
      })
    };

**Comment by yyx990803** [comment]
Please post this to `vue-resource`'s repo instead.

**Comment by YerkoPalma** [comment]
Understood. Copied [here](https://github.com/vuejs/vue-resource/issues/198) :+1:
