### ISSUE TITLE
v-model using value from v-for (v-model and v-for on the same element)

### ISSUE THREAD

**Issue by xDarkShadowKnightx** [vuejs/vue#2143]
Are v-model bindings using values from a v-for possible? I couldn't find any examples showing how to do this. I'm trying to populate a large list of predefined values using this system. Here's an example of what I'm trying to do:

```html
<input v-for="props in fields" v-model="users.primary.{{ props.key }}" type="text" placeholder="{{ props.placeholder }}"/>
<input v-for="props in fields" v-model="users.secondary.{{ props.key }}" type="text" placeholder="{{ props.placeholder }}"/>
<script>
var app = new Vue({
    data: {
        fields: {
            {"key": "username", "placeholder": "Username"},
            {"key": "address", "placeholder": "Address"},
            {"key": "email", "placeholder": "Email"},
            {"key": "name", "placeholder": "Name"},
            {"key": "pass", "placeholder": "Password"},
            {"key": "pass_repeat", "placeholder": "Repeat Password"},
            {"key": "city", "placeholder": "City"},
            {"key": "zip", "placeholder": "Zip"},
            {"key": "phone", "placeholder": "Phone"}
        }
    }
});
</script>
```

The "placeholder" part of this works, but the two way data binding on the v-model isn't working.

**Comment by xDarkShadowKnightx** [comment]
I moved this to http://forum.vuejs.org/topic/1317/v-model-using-value-from-v-for-v-model-and-v-for-on-the-same-element

**Comment by fugroup** [comment]
The link to that page doesn't work anymore.

**Comment by Chrisstar56** [comment]
https://web.archive.org/web/20160914001544/https://forum.vuejs.org/topic/1317/v-model-using-value-from-v-for-v-model-and-v-for-on-the-same-element not too much info there though
