### ISSUE TITLE
过渡效果如何应用于元素非插入/移除时？

### ISSUE THREAD

**Issue by ekousp** [vuejs/vue#2146]
Hi,

Vue 文档中写明 transition 仅在元素插入或者移除时才会触发。我想实现的效果是，模型的值在更新时，有动画效果，目前的实现在这里：
[https://jsfiddle.net/sd8900jp/](https://jsfiddle.net/sd8900jp/)。

请问有没有更好的办法？感觉这里的实现比较 trick。

**Comment by ekousp** [comment]
另外，使用 `this.$data.key` 还是 `this.data` 好？官方有没有推荐的最佳实践？

**Comment by ablipan** [comment]
:cry: 个人觉得这种实现方式上的问题用不着开issue吧... 在qq群或者 gitter里问一下
另外，`this.$data.key === this.key`，用`this.key`更简洁

**Comment by ekousp** [comment]
抱歉没有使用 QQ 群或者 gitter 讨论技术问题的习惯，所以就直接来问啦，见谅。 😄

**Comment by Twiknight** [comment]
这种问题去论坛问啊骚年。
戳这里：http://forum.vuejs.org/
这里是发Bug和feature request的去。

你可以参考这个：
https://github.com/Twiknight/vue-transition
我为了随时触发transition和animation造的轮子，原理很简单。
