### ISSUE TITLE
The Vue.set(obj, key, value) method returns undefined or the set value??

### ISSUE THREAD

**Issue by YuKaiChan** [vuejs/vue#2149]

**Comment by smolinari** [comment]
The same goes here. You're going to have to explain more. Evan will just close this (as he did your other post), because you aren't explaining your problem at all. 

See the contributor guidelines. 

https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md

Scott

**Comment by ludo237** [comment]
:-1: Read contributing guidelines first

**Comment by azamat-sharapov** [comment]
In case you are having language problems, please post questions in forum.vuejs.org, there may be people speaking your language in forum.
