### ISSUE TITLE
Feature-request: enable expressions for transitions

### ISSUE THREAD

**Issue by plakhin** [vuejs/vue#2151]
It would be great to have an ability to apply transitions using expressions, like:
````html
<div v-transition="somevar ? 'transition' : ''"></div>
````

**Comment by Twiknight** [comment]
Try this:
https://github.com/Twiknight/vue-transition

call the play method on your need.

**Comment by crswll** [comment]
You can use `:transition="foo"` and it'll change based on that. Here's a quick demo: https://jsfiddle.net/crswll/paxna6by/

**Comment by yyx990803** [comment]
^ what @crswll demoed

**Comment by plakhin** [comment]
@crswll thanks a lot!
