### ISSUE TITLE
Stateful filters

### ISSUE THREAD

**Issue by losadaem** [vuejs/vue#2152]
Any plans to support stateful filters? 
The purpose is to implement async filters that handle promises directly.

**Comment by yyx990803** [comment]
I personally don't think that's a good idea, unless you can provide a convincing use case example.

**Comment by amirrustam** [comment]
Angular JS has stateful filters and this is what they have to say about them in their [docs](https://docs.angularjs.org/guide/filter#stateful-filters):
>It is strongly discouraged to write filters that are stateful, because the execution of those can't be optimized by Angular, which often leads to performance issues. Many stateful filters can be converted into stateless filters just by exposing the hidden state as a model and turning it into an argument for the filter.

Not sure if their issue with it would be directly reflected in Vue, but I thought I mention this for the sake of a well-rounded view on the matter.

**Comment by losadaem** [comment]
The purpose of interest was only to handle data binding directly from promises and avoid the verbosity of initializing data from Promise returns.

For example:

```
var vm = new Vue({
  data: {
    model: null
  },
  ...
})
Model.find().then(function(model){ vm.model = model })
```

compared to

```
var vm = new Vue({
  data: {
    model: Model.find()
  },
  ...
})
```

But after digging deeper it seems to add complexity that exceeds the benefits.

**Comment by yyx990803** [comment]
The latter doesn't really need stateful filters - you can write a plugin to achieve that, similar to how [vue-rx](https://github.com/vuejs/vue-rx) allows you to directly bind to observables.

**Comment by losadaem** [comment]
My example was a simple one. I've looked at [vue-rx](https://github.com/vuejs/vue-rx) but I think we can't achieve more complex situations.

```
var vm = new Vue({
  data: {
    model: Model.find()
  },
  methods: {
    reload: function(){
      this.model = Model.find()
    }
  } 
  ...
})
```

**Comment by yyx990803** [comment]
I think it only complicates the mental model - `data` is declarative binding, but the actual property should always be plain values.

**Comment by apneadiving** [comment]
I would like to update a little this issue. A reason why stateful filters can be useful is: you have an id as a raw value and you need to display real human readable data (fetched through ajax for instance).

Here is a js bin, I wonder if you have suggestion to make it work: https://jsbin.com/corogo/edit?html,js,console,output

**Comment by sirlancelot** [comment]
A filter is not the correct abstraction for what you're trying to accomplish, @apneadiving. Based on your description, you should make a component which accepts the ID as a prop and would display the user-presentable value. Components are already stateful, allowing to even show a spinner in-place while the async data is being fetched.

Feel free to ask specifics in [Discord](https://chat.vuejs.org/) or the [Forum](https://forum.vuejs.org/).

**Comment by apneadiving** [comment]
Thanks for your quick answer @sirlancelot ! 🐴🗡
