### ISSUE TITLE
Transition getting stuck on leave in firefox for modal window example if it's put in a .vue component file (problem is display: table)

### ISSUE THREAD

**Issue by aaronjpitts** [vuejs/vue#2156]
If you put the following example in a .vue component file http://vuejs.org/examples/modal.html the display: table on the .modal-mask class causes the transition to get stuck on leave in Firefox. This issue is only with display: table. display:block|inline-block|flex etc. work fine.

**Comment by yyx990803** [comment]
It shouldn't behave differently when placed in a `*.vue` file. Please provide an actual reproduction.

**Comment by yyx990803** [comment]
Closing (inactivity)

**Comment by zllovesuki** [comment]
I can confirm that such bug does exist.

Steps to reproduce:
1. Produce a .vue component file from the example
2. Register the modal
3. Use the component in other parts of the application
4. Open modal
5. Close the modal

Expected Result:
Modal closes, nothing left behind

Actual Result:
The modal disappears. However, the elements within the modal are still clickable.

Changing display from table to *anything* other than "table" will seemingly solve the problem.

**Comment by LinusBorg** [comment]
...and that only happens with a.vue file?

Can you provide the code you used to reproduce this?
