### ISSUE TITLE
关于异步加载组件后，导致ready不能通过$refs获得组件问题

### ISSUE THREAD

**Issue by lpreterite** [vuejs/vue#2158]
目前公司写后台管理系统是通过异步方式按需加载组件和页面的，某些组件（如：summernote）是基于jQuery时，事件写法并不能在vue中使用（比如bootstrap model组件的显示事件`show.bs.modal`），需要获得元素（或者组件）方式来注册事件。由于组件是异步加载的，页面加载完后进入ready钩子其实并不代表组件加载完。

问：我啥时候才能知道组件加载完？还是有更好的方法解决这类需求？

**Comment by yyx990803** [comment]
在异步组件自己的 `ready` 里面做相关操作呗。类似问题请不要开 issue，到论坛或者 Gitter 或者 QQ 群里问。
