### ISSUE TITLE
Custom HTML in Custom Components

### ISSUE THREAD

**Issue by xkjyeah** [vuejs/vue#2167]
Is it possible to use the innerHTML in components?

e.g.
&lt;script>
Vue.component('fancy-button', {...})
&lt;/script>

&lt;fancy-button>
&lt;img src="icon.png" /> Caption to icon
&lt;/fancy-button>

**Comment by Mat-Moo** [comment]
Please leave "Issues" for vue issues, and direct questions to the forum.http://forum.vuejs.org/ :) Thank you

**Comment by yyx990803** [comment]
http://vuejs.org/guide/components.html#Content_Distribution_with_Slots
