### ISSUE TITLE
Passing an integer to a component throws warning because vue takes it as string

### ISSUE THREAD

**Issue by tristanbes** [vuejs/vue#2168]
Using `vue 1.0.14` when using a component like:

`<quick-assign-primary-user users_count=0></ quick-assign-primary-user>`

With a `props` definition
```javascript
var QuickPrimarySelect = Vue.extend({
    template: '#quick-primary-user-template',
    props: {
        users_count: {
            type: Number,
            required: true
        }
    }, ...
})
```

Gives an error/warning :
`[Vue warn]: Invalid prop: type check failed for users_count="0". Expected Number, got String.`

Resulting in `users_count` variable to be `undefined`

**Comment by ediamin** [comment]
use a semicolon before users_count attribute `:users_count=0` or `:users_count="0"`

**Comment by tristanbes** [comment]
Thanks. Does all the variable passed to a component needs to have `:` prefix or is it valid only for `Number` type ?

**Comment by kwando** [comment]
@tristanbes ```:``` is a shortcut for the ```v-bind``` directive, so ```:user_count="0"``` is the same as ```v-bind:user_count="0"```.

The attribute value will always be a string if you are not using v-bind.

http://vuejs.org/api/#v-bind

**Comment by tristanbes** [comment]
Thanks !

**Comment by broox** [comment]
it also may not be as explicit, but `type` can also accept an array of object types. e.g.

```
    props: {
        users_count: {
            type: [Number, String],
            required: true
        }
    }, 
```

This can be handy if the value you're passing comes from another variable or data attribute instead of a hard-coded number.

**Comment by RaschidGithub** [comment]
I'm using the `:` but I still get the error!

```
<ops-genie-alert-details :alert="{message:'hi'}"/>
```

I'm creating a standalon custom component with webpack so I don't know if that may be causing the problem in prop parsing.

**Comment by Mrcooder** [comment]
@ediamin  I had do this, but vue still takes it as string, I solved this problem by bind user_count to a variable.😄
