### ISSUE TITLE
Boolean attributes

### ISSUE THREAD

**Issue by rhyzx** [vuejs/vue#2169]
According to the HTML5 spec:

> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.
> - https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes

So, in order to make my code spec compatible, i'd do in this way in vue: `<input :checked="checked ? '' : false">`, do you think it is necessary to directly support boolean attributes in vue? @yyx990803 

Solutions I can think of are these:
- By another directive: `v-add:selected="true"` (not recommand)
- By modifier: `v-bind:selected.boolean="true"` (recommand)
- Auto: `v-bind:selected="true"`, we need to mantain a boolean attribute list([see](https://github.com/kangax/html-minifier/issues/63)), and this may have compatibility problems.

Again, if you think it is necessary, let me handle this! :trollface:

**Comment by yyx990803** [comment]
What's the problem with `<input :checked="checked">`? Vue removes the attribute if `checked` is falsy.

**Comment by rhyzx** [comment]
Well, `<input checked="true">` and `<input checked="1">`  are invalid in HTML(although they can work in most browsers), only `<input checked>` and `<input checked="checked">` are valid.

**Comment by yyx990803** [comment]
Ok, I guess the modifier is the best way to go. Should be easy too.

**Comment by rhyzx** [comment]
What about the modifier name? `.boolean` is ok?

**Comment by yyx990803** [comment]
Yeah I think so.

**Comment by rhyzx** [comment]
By the way, could you email your email address? it would be more convenient talk in my native language.    XD

**Comment by kazupon** [comment]
+1 😺

**Comment by posva** [comment]
@rhyzx Thank you for posting your issues in English! :smile:

**Comment by rhyzx** [comment]
@posva wel ;)
