### ISSUE TITLE
More intuitive aliases for $dispatch() and $broadcast()

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#2171]
The only thing I've found unintuitive in Vue so far are the `$dispatch()` and `$broadcast()` method names. At least from my understanding of the words, it is not intuitively obvious without referring back to the documentation which emits an event to ancestors and which emits an event to descendants.

My suggestion would be to include the following aliases:

- `$emitToAncestors()` for `$dispatch()`
- `$emitToDescendants()` for `$broadcast()`

My only hesitation is that "descendants" is notoriously difficult for many to spell and the variation "descend**e**nts" (with an "e") is also grammatically valid, so that would have to work as well. Another, much briefer possibility is:

- `$emitUp()` for `$dispatch()`
- `$emitDown()` for `$broadcast()`

And there may be a better naming scheme that simply isn't coming to mind right now. Whatever pair might be chosen, my thinking is the old names could eventually be deprecated and then removed if the aliases are embraced by the community.

What are others' thoughts? Is it just me who feels this confusion or would aliases be helpful?

**Comment by thelinuxlich** [comment]
+1 for that, sometimes I get confused by these too

**Comment by smolinari** [comment]
I would say, the syntax/logic goes along lines of the meaning of the verbs.

If you think of a general has to inform an army of soldiers (parent->child) she'd have to use a larger means to communicate, like a bullhorn, or even radio, to "broadcast" the message or order to them all. 

If there were a major in that same army, and he wanted to send the general a message, he'd have to "dispatch" a message to her, to go up the chain of command, from lieutenant colonel, colonel and then the general. 

I think that visualization helps. :smile:  

Scott

**Comment by amirrustam** [comment]
@smolinari that's exactly the same way I thought about them. I found their meaning to be self-explanatory. I've seen these names used in other frameworks, even non-JavaScript ones, but to each his own.

Creating aliases within the API is not really inline with the simple and rather small surface API of Vue as it creates redundancy and clutter. Let's focus on maintaining this trait of Vue.

**Comment by chrisvfritz** [comment]
Thanks @smolinari. I'm afraid I'm not personally familiar enough with the military for that metaphor to be helpful, but I do appreciate the attempt! :smiley: 

For me, "broadcast" suggests sending a message to many receivers, while "dispatch" seems an overly formal word for sending a message to a single receiver. Looking up the official definitions for these words, this does indeed seem to be their more generally accepted meaning. I did find the military use of "dispatch" that you were referring to, but "broadcast" does not seem to be military-speak for specifically communicating to one's subordinates, so I'm not sure the full metaphor holds up.

To be clear @amirrustam, I also enjoy the simple and small surface API and am definitely not suggesting stacking on any permanent aliases. `$dispatch()` and `$broadcast()` would eventually be removed in favor of more descriptive method names.

**Comment by yyx990803** [comment]
In native DOM API, we use `dispatchEvent` to send an event that bubbles upwards, which is what `$dispatch` does in Vue. And `broadcast` sends the event downward to all children of the broadcaster, which I think is pretty straightforward. (Angular has the same `$broadcast` method that does the same thing.

Overall the benefits of changing the name is subjective, but it requires us to either have two sets of methods that do the same thing or raise deprecation warning for the old ones. I don't think it's worth it.

**Comment by chrisvfritz** [comment]
Fair enough, if there are analogs in the DOM API. Thanks for the explanation @yyx990803.

**Comment by smolinari** [comment]
Note: I wrote this, but forgot to save it earlier. 

@chrisvfritz - How about if you think of a company? If you have a CEO that needs to communicate with all the employees, she'd have to use a communication method, which sends the message to as many of the employees as possible at once. The message or new order could be sent over the company's intranet or through email. They are both methods of broadcasting information.  

If, however, a manager within the company wants to send a message to the CEO, she might use email, but following proper internal rules of etiquette, it would be "dispatched" to her boss first, her boss passes it along to his boss, and this continues, until the CEO gets it.  

Scott

**Comment by azamat-sharapov** [comment]
Anyone, who is not pleased by naming, could wrap any of thouse into own method and attach it to Vue.prototype or create global mixin.

**Comment by chrisvfritz** [comment]
@smolinari Thanks again for taking the time. Having never worked for a company so big that I have to go through channels to "dispatch" a message to the CEO, that's still now how I think of those words. But I do appreciate the attempt and I'll be fine. They're not impossible to wrap my head around and I don't even have need for them yet. I just wanted to bring this up because it was the first thing I came across where I didn't think, "Yes, of course!" I accept and respect Evan's reasoning though.

@azamat-sharapov That's certainly true, though comes with its own problems. I would personally avoid that practice, as someone is less likely to be tripped up by a Vue method they have to look up, than by a _seemingly_ official Vue method that they can't find anywhere in the documentation. That someone includes future me. :smiley:

Either way, my main concern was accessibility to newcomers, which your suggestion doesn't address.
