### ISSUE TITLE
Watch doesn't work if an input type="number" value is incremented using the browser's incrementing/decrementing arrows

### ISSUE THREAD

**Issue by aaronjpitts** [vuejs/vue#2172]
Watch doesn't detect a value change if using an input type="number" element and changing the value using the browser's incrementing/decrementing arrows.

**Comment by OEvgeny** [comment]
Can you provide reproduction of this issue?

**Comment by crswll** [comment]
Which browser?

I can't replicate it in Chrome, Firefox or Safari.

Here's my test case: https://jsfiddle.net/rmz5dbof/

**Comment by yyx990803** [comment]
Closing (inactivity)

**Comment by devend711** [comment]
I am getting some possibly related and weird behavior when using a debugger statement and Chrome dev-tools open:

https://jsfiddle.net/b4h469am/

`n` increments forever

**Comment by simplesmiler** [comment]
@devend711 not a Vue bug per se, it's reproducible in vanilla: https://jsfiddle.net/simplesmiler/63ettzhh/.
I've filed an issue to the Chrome tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=613464.

**Comment by ejmolinelli** [comment]
I was actually able to reproduce this a different way by putting the ng-if on the input element.
