### ISSUE TITLE
Destroyed hook not called

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue#2178]
Hello,

I have a component (fragment) and the `beforeDestroy` hook is called but not the `destroyed` one. Is it normal or is it a bug ? 

Thank you

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by GuillaumeLeclerc** [comment]
This is happening in this component : https://github.com/GuillaumeLeclerc/vue-google-maps/blob/master/src/components/marker.vue. This is why I changed the `destroyed` hook into `beforeDestroy` in the latest release. I happens when the marker come from a v-for filtered that is changing quickly. 

But I'll try to make a reduced example now.

**Comment by GuillaumeLeclerc** [comment]
After a night of research. I found that it is a vue-router bug. 

Here is a repro: http://jsfiddle.net/xyu276sa/208/.

I don't know if you want to close the issue to open it on the other repo. 

I look at the source code and it seems [this part of the code](https://github.com/vuejs/vue-router/blob/5fbaffe91d91061abe0aa63b060f55e77a1463f2/src/override.js#L34) has not been updated for vue 1.0. (it works fine with vue 0.12)

**Comment by posva** [comment]
> I don't know if you want to close the issue to open it on the other repo.

If it's a vue-router bug then open an issue there. That'll be faster than asking someone to do it for you!

**Comment by GuillaumeLeclerc** [comment]
OK I will
