### ISSUE TITLE
Assigning a new array to an array model in the data of child component does not trigger DOM update.

### ISSUE THREAD

**Issue by tianhai82** [vuejs/vue#2179]
For a new Vue instance, assigning a new array to an array model triggers DOM update as expected.
However, for child components declared using "Vue.extend()", assigning a new array to an existing array model does not trigger any DOM update.
See fiddle:
https://jsfiddle.net/tianhai/arreefs9/

**Comment by simplesmiler** [comment]
You got caught by the common JavaScript gotcha. At line 41 you assign a new reference to the `store` variable instead of modifying data of the existing reference.

Fixed demo: https://jsfiddle.net/simplesmiler/arreefs9/1/

**Comment by tianhai82** [comment]
Oic! Thanks for the explanation!
