### ISSUE TITLE
v-ref & v-if problem on child access

### ISSUE THREAD

**Issue by FedericoLaggiard** [vuejs/vue#218]
Hi,

I'm having some issue using "v-ref" and "v-if", simply put: if I have a "v-if" directive on a node, childs node (whit "v-repeat" and "v-ref") are not accessible to parent view. If I remove the "v-if" directive everything works fine.
My html is something like this (I can prepare a fiddle if needed):

<pre>
<span class="nt">&lt;div v-if="showSubMenu" id="subMenu"&gt;</span>
<span>     &lt;div v-repeat="subMenu" v-ref="subMenuButtons"&gt;</span>
<span>         &lt;!--content--&gt;</span>
<span>     &lt;/div&gt;</span>
<span>&lt;/div&gt;</span>
</pre>

[..].$.subMenuButtons is never accessible if the v-if directive is on DOM. 
I understand that the list is not instantiated at all if the "v-if" condition is falsy. But even when the condition became truthy the reference is not set on the parent.
Is this an intended behaviour?

Many Thanks

**Comment by manavm1990** [comment]
`v-ref` is for Vue1 at this point, FYI.
