### ISSUE TITLE
In vue file, webpack would ignore the space value

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue#2180]
In a vue file, there is an input element in the template:

    <input type="submit" id="search_button" name="submitBtn" value=" ">

Notice that the value of value property is a space not empty.

After using webpack to build up, the input element is changed to this:

    <input type="submit" id="search_button" name="submitBtn">

The whole value property is gone! Then the default value of value property is shown up! I want the space kept there. Is that a bug of vue?

**Comment by yyx990803** [comment]
This is a behavior of [html-minifier](https://github.com/kangax/html-minifier) which is used by `vue-loader` and `vue-html-loader` to minify the HTML in production mode. The related option is `removeEmptyAttributes`. You should open an issue there.

In the meanwhile you can get around this with `value="&nbsp;"`
