### ISSUE TITLE
Enter transition never assigned

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue#2184]
When I use a transition on an element that's conditionally rendered, it never gets the `.v-enter` class assigned upon creation when the page loads.

I suspect it has something to do with the DOM not being ready yet, or something similar> Or maybe it has to do with routing (this element is a router end-point)?

But the following code will not get an enter class assigned:

```
<template>
  <h2>{{ name }}</h2>
  <div v-show="isLoading" transition="test">loading</div>
</template>

<script>
import { getProductsByCategory } from '../../helpers'
import loader from '../loader'

export default {

  components: {
    loader
  },

  route: {

    // Async data loading can occur here.
    // E.g. get products by category and return the result.
    data({ to, next }) {

      getProductsByCategory(to.params.category, (err, name, products) => {
        if (err) {
          console.log('error while loading data!')
        } else {
          next({
            isLoading: false
          })
        }
      })

    }

  },

  data() {
    return {
      isLoading: true
    }
  }
}
</script>

<style>
.test {
  position: relative;
}

.test-transition {
  transition: all .3s ease;
  transform: translate(0, 0);
}

.test-enter,
.test-leave {
  opacity: 0;
  transform: translate(0, 32px);
}
</style>
```

**Comment by yyx990803** [comment]
Transition is not applied on initial render. There will be a dedicated mechanism to control that in the next release, currently you will have to "trigger" a state change after initial render to simulate an initial transition.

**Comment by TheDutchCoder** [comment]
Alright thanks for letting me know!
