### ISSUE TITLE
dynamic v-ref 

### ISSUE THREAD

**Issue by arthurkirkosa** [vuejs/vue#2190]
Is there a way to read the properties of **this.$refs**?

```
methods: {
    makeMain(hash) {
      console.log(this.$refs); // Object
      console.log(this.$refs[hash]); // undefined
    }
  }
```

**Comment by yyx990803** [comment]
Make sure the method is called after the compilation. `$refs` will not be available in `created`. If you believe it's not working correctly, please reopen and provide a reproduction.

**Comment by arthurkirkosa** [comment]
Not sure what I was doing but it's working now.

The only thing I've changed is to use int refs instead of strings.
