### ISSUE TITLE
Collection-repeat in Vue?

### ISSUE THREAD

**Issue by jedidas** [vuejs/vue#2191]
Hello, Is there any plugin or directive in Vue that's how "collection-repeat" of Ionic?
[Doc collection-repeat](http://ionicframework.com/docs/api/directive/collectionRepeat/)

In my application I use a list of items, being so long the performance is lost.
There a way to display the list only in parts to improve performance? 

Thank you

**Comment by simplesmiler** [comment]
You can try to paginate your data with [`limitBy`](http://vuejs.org/api/#limitBy) to see if limiting the number of displayed items will help.

**Comment by yyx990803** [comment]
That's a third party implementation. It's possible if someone wants to implement it for Vue, but it's unlikely to be included in core by default.
