### ISSUE TITLE
关于CSS的问题

### ISSUE THREAD

**Issue by berwin** [vuejs/vue#2195]
当前组件下，没有调用的组件的style也会写到head中。。。好像不太好？
![image](https://cloud.githubusercontent.com/assets/3739368/12439651/d4caa1d2-bf6d-11e5-8ac5-c7068a43a788.png)
当前我只调用了两个组件~

**Comment by yyx990803** [comment]
组件只要被打包就会插入 CSS。这又不会有性能问题，哪里不太好了？生产环境下通常是抽取到单独的一个 CSS 文件里的。

**Comment by berwin** [comment]
组件之间的样式有可能会互相干扰啊。。。

**Comment by hbrls** [comment]
@berwin 建议看看这个 http://gilbox.github.io/css-bliss/walkthrough/release/

**Comment by xiaolongyuan** [comment]
@berwin 只用于组件的样式都会被重命名 不知何来干扰？

**Comment by berwin** [comment]
@xiaolongyuan 重命名？？ 我这貌似没有哇。。。

**Comment by xiaolongyuan** [comment]
<style scope></style>

**Comment by berwin** [comment]
@xiaolongyuan 
![image](https://cloud.githubusercontent.com/assets/3739368/12445187/d194c3fa-bf9d-11e5-88c9-d08437577185.png)
这会不会是我用错了。。。

**Comment by yyx990803** [comment]
用 `<style scoped>`...

另外，就算按需插入也不能保证不互相干扰，因为你不知道运行时哪些组件可能被同时使用。

**Comment by berwin** [comment]
噢噢噢。。原来是这样。。明白啦。多谢~~

**Comment by NickBang** [comment]
我也遇到了同样的问题。那如果多人开发。class名也有可能冲突。样式不久会干扰了么？
