### ISSUE TITLE
默认的数据类型只支持一级数据吗？

### ISSUE THREAD

**Issue by NangeGao** [vuejs/vue#2197]
尤老师你好，发现一个这样的问题。
```
data () {
	return  {
		query: {
			type: 1
		},
		api: true
	｝
｝
```

在Vue实例中定义data如上面代码段，`this.api` 的类型默认就是布尔值了，但是`this.query.type`却不支持默认设置为int型，更改model的过程中，有可能会变成布尔类型。
是因为`this.query`有可能会变化，`this.query.type` 可能本身就会变成 `undefined`，所以框架在设计的时候就没有考虑为非一级数据设置默认数据类型吗？

**Comment by xiaolongyuan** [comment]
关掉吧  无力吐槽 去看文档

**Comment by yangjunjun** [comment]
@NangeGao  也建议关掉。这里是提 issue 的地方，不是提问一些初级问题的地方。建议官方文档先看一下，有什么问题先到一些问答网站或QQ群问一下，不要随便提 issue.

**Comment by yyx990803** [comment]
请不要用 issue 问问题。
另外，说实话我看不懂你的意思... JavaScript 是动态类型的...

**Comment by NangeGao** [comment]
好的，抱歉，不太熟悉github
