### ISSUE TITLE
transition & v-if 

### ISSUE THREAD

**Issue by lazyhero** [vuejs/vue#2201]
这一切发生在chrome 和 安卓5.0 ios8.3以上都很正常
但在安卓4.4 4.3 ios8.2 就变了……
（示例代码在 https://github.com/lazyhero/vue-demo 放到了线上 不过github提示 有un-safe脚本……）
我要实现的效果为组件间的过渡转场
正常在chrome下为：
http://7jpswm.com1.z0.glb.clouddn.com/transitiontransition-bug.gif
![](http://7jpswm.com1.z0.glb.clouddn.com/transitiontransition-bug.gif)
但是在手机默认浏览器下安卓4.3 包括对应的webview下 
1.http://7jpswm.com1.z0.glb.clouddn.com/transition1.pic.jpg
2.http://7jpswm.com1.z0.glb.clouddn.com/transition2.pic.jpg
![](http://7jpswm.com1.z0.glb.clouddn.com/transition1.pic.jpg)
![](http://7jpswm.com1.z0.glb.clouddn.com/transition2.pic.jpg)

父组件代码-parent vm：
http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160121_139.png
![](http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160121_139.png)
子组件代码-panel vm
http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160121_140.png
![](http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160121_140.png)

**Comment by yyx990803** [comment]
Your images are not working :/

**Comment by lazyhero** [comment]
@yyx990803 i don't know why the images not working so i paste the url in here

**Comment by lazyhero** [comment]
@yyx990803 
出现这种情况后，子页面的点击全部失效，怀疑是不是在处理动画时用了一些新语法 旧版webview或者手机浏览器 不兼容 导致报错；后续的各种处理也都挂了；

**Comment by lazyhero** [comment]
@yyx990803 线索更新：
in ordinary situation 
![](http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160122_151.png)
you will find "removeClass" exec twice that the last it remove "page-current" it work well;
in un-normal situation
![](http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160122_152.png)

you will find "removeClass" only exec once that not to remove "page-current" it work wrong

**Comment by lazyhero** [comment]
线索更新：
![](http://7jpswm.com1.z0.glb.clouddn.com/transitionSnip20160122_155.png)

**Comment by lazyhero** [comment]
问题解决了 
但是没找到代码上的根本原因

解决方法是 在css动画的样式上补齐了-webkit前缀……shit……
