### ISSUE TITLE
Firebase + 验证 Example,想把Firebase后台存储改为自己的mysql存储，应该怎么做？

### ISSUE THREAD

**Issue by zwl1619** [vuejs/vue#2202]
Firebase + 验证 Example示例，想把Firebase后台存储改为自己的mysql存储，应该怎么做？
示例网址：http://cn.vuejs.org/examples/firebase.html

**Comment by yyx990803** [comment]
请不要用 issue 问此类问题。

**Comment by xiaolongyuan** [comment]
这个频道不是用来提问初级问题的  反馈BUG pr

**Comment by zwl1619** [comment]
好的，知道了。在哪里问这种问题比较好？

**Comment by xiaolongyuan** [comment]
http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87
http://segmentfault.com/t/vue.js
stackoverflow.com
