### ISSUE TITLE
Watching params in custom directives

### ISSUE THREAD

**Issue by nilssolanki** [vuejs/vue#2203]
Is there a way to watch `params` in a custom directive?

I need to watch a param and invoke an action when it changes. In the vue custom directive select2 example, I would like to update the options:

```
Vue.directive('select', {
  twoWay: true,
  priority: 1000,

  params: ['options'],
    
  bind: function () {
    var self = this
    $(this.el)
      .select2({
        data: this.params.options
      })
      .on('change', function () {
        self.set(this.value)
      })

    this.$watch('options', () => { // watch options to update select2
        $(this.el)
          .select2({
            data: this.params.options
        })
    })
  },
  update: function (value) {
    $(this.el).val(value).trigger('change')
  },
  unbind: function () {
    $(this.el).off().select2('destroy')
  }
});```

Is this a feature others would like to see as well?

**Comment by zuobaojing** [comment]
@nilssolanki I have the same requirement, How did you solve the problem?

**Comment by nilssolanki** [comment]
I read the documentation :)
It doesn't have any accompanying text though, so I didn't see it at first:
http://vuejs.org/guide/custom-directive.html#params

In the last code example there is a property called `paramWatchers`:

```
Vue.directive('example', {
  params: ['a'],
  paramWatchers: {
    a: function (val, oldVal) {
      console.log('a changed!')
    }
  }
})
```

**Comment by zuobaojing** [comment]
wow, this is great! thanks :)

BTW: I just figured it out this way http://jsfiddle.net/zuc27nw9/42/, not sure if it's a proper approach, but it seems clean and works
