### ISSUE TITLE
Boolean sent as string through ajax

### ISSUE THREAD

**Issue by rogervila** [vuejs/vue#2204]
I am using Vue with laravel, and the ajax requests are made with jQuery. 

I have a property which model is a input checkbox. 

On VueDevtools, the property changes between `true` and `false`, but when I send it through ajax, laravel returns the property as a string `'true'` or `'false'`.

Is this a problem with Vue or with jQuery?

Thank you.

**Comment by yyx990803** [comment]
This more likely a serialization issue and not related to Vue.
