### ISSUE TITLE
vue.js在采用ajax方式读入数据后，无法激活slide插件的滑动行为

### ISSUE THREAD

**Issue by csdudu** [vuejs/vue#2208]
我在mui+vue.js构建一个slide-pic组件，图片数据用ajax方式获取，vm数据能获取到，dom也发生了相应的改变。但数据读入后，无法激活slide组件的滑动行为。

以下是我做的一些探索:
直接使用vue初始化数据（非ajax）可以激活滑动行为。
使用jquery的append方式，把数据结合到dom后，也可以激活。
我将mui的slide-pic组件换成另一个滑动图插件TouchSlide1.1后，同样的现象，用vm方式无法激活。

请问这是什么原因？到底是vue还是mui/TouchSlide 插件机制的问题。
部分主要代码如附件：
[demo.txt](https://github.com/vuejs/vue/files/100204/demo.txt)

**Comment by ifci** [comment]
获取到数据后运行  mui('.mui-slider').slider() 就可以了

**Comment by ifci** [comment]
如果不行的话，写个定时器延迟200毫秒运行

**Comment by xiaolongyuan** [comment]
Issues

Please make sure to read the Issue Reporting Checklist before opening an issue. Issues not conforming to the guidelines may be closed immediately.

**Comment by Dafrok** [comment]
目测是[Vue.nextTick](http://cn.vuejs.org/api/#Vue-nextTick)可以解决的问题
此类问题请移步[论坛](http://forum.vuejs.org/) 会有更多的人帮你解决问题 在ISSUE里提问会增加维护者的负担

**Comment by AnyGong** [comment]
@Dafrok 说的是对的。我再补充一下，因为我今天刚踩过这个坑。。。你要把`ajajx`里面的`success`结果`callback`出来，然后在`callback`里面把结果去做`data的update`，然后下一步  `$nextTick`。这样依赖此`data`的视图就会更新了。我今天一直纳闷了好久。

`ajax回调！` `ajax回调！` `ajax回调！`重要的事情说三遍

**Comment by csdudu** [comment]
确实是nextTick就解决了，谢谢各位，以后提问会到官网论坛去问。
代码如下：
vm_slide.$nextTick(function () {
	// DOM 现在更新了
	mui("#slider").slider({
	 interval: 3000
	});
})
