### ISSUE TITLE
seems not necessary to return anything from Vue#_compile(el)

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/vue#2212]
https://github.com/vuejs/vue/blob/fe02b38c4f9883c26cf195fab319dbaf70eb569c/src/instance/internal/lifecycle.js#L97

Any other meaning here for returning an element in this internal method?

* It only be called in `Vue#mount(el,options)` but not necessary to return anything.
* And all test cases passed if I remove this line of code.
* The value `el` could be accessed by `this.$el` outside.

**Comment by yyx990803** [comment]
You are right. Feel free to open a PR!
