### ISSUE TITLE
如何扩展一个 filter

### ISSUE THREAD

**Issue by eyasliu** [vuejs/vue#2215]
我想要扩展一个filter，怎么在定义filter的地方调用已有的filter呢？
比如我要根据`currency`过滤器扩展成一个 `rmb`过滤器

```js
Vue.filter('rmb', function(val){
  // 这里如何调用已有的过滤器
  return Xxx.filter.currency(val, '￥');
})
```

**Comment by xiaolongyuan** [comment]
别做伸手党  去看教程 去看示例  顺便关掉issue

**Comment by Jinjiang** [comment]
(The question is how to call builtin filter as part of a custom one. for example use `currency` filter to finish a `rmb` filter)

I found `this.$options.filters.currency` work. But use `currency` directly is also not bad. Builtin filters can take args or be chained in Vue I think that's enough.

**Comment by yyx990803** [comment]
Or Vue.filter('currency')
