### ISSUE TITLE
v-if multiple expressions?

### ISSUE THREAD

**Issue by gapipro** [vuejs/vue#222]
So how can I use v-if with multiple conditions?

```
v-if="!lock || status== 'ok' "
```

This is currently not working. 

Any workarounds?

**Comment by JohnSmith0602** [comment]
v-if multiple expressions seem to be supported now. I tried it on 0.11.0, it worked as expected!

**Comment by mithublue** [comment]
@JohnSmith0602 will u please share the code ?

**Comment by MicroDreamIT** [comment]
can you take a look at this, I am trying to make it happen, but not working 
http://jsbin.com/cocavu/edit?html,js,output

**Comment by ludo237** [comment]
@JohnSmith0602 To be fair v-if shouldn't be use for complex expression, that's why there are computer properties 

@MicroDreamIT Here we go [fixed](https://jsbin.com/zexiyo/1/edit?html,js,output) . You shouldn't use issues for your personal problems tho because it wasn't related to v-if anyway

**Comment by mqliutie** [comment]
Hi , I have same problem. 
I want realize `<span v-if="support || isOrganizer">will be shown</span>`
If  write like above It can not work.
If I use `computed` property It can show but when I refresh browser It is gone.
So how can I solve it? Thanks

**Comment by gapipro** [comment]
@mqliutie if you are using latest version then `<span v-if="support || isOrganizer">will be shown</span>`should work as expected. 

But in case you are not try with `<span v-if="(support || isOrganizer)">will be shown</span>`

Adding `()` makes that whole condition a normal JS expression that is resolved on execution.

**Comment by mqliutie** [comment]
I have used `vue-cli` generator.
In `app.vue` have to components like below:
```HTML
<ing :result="result"></ing>
<ends :result="result"></ends>
```
This is `ing.vue `:
```HTML
<span v-if="(support || isOrganizer)">true</span>    
<span v-else>false</span>
```
```js
props:['result'],
data :function(){
 support:false,
 isOrganizer:false
}
watch:{
    result :function(newVal,oldVal){
         this.support = newVal.support;
         this.isOrganizer = newVal.isOrganizer
    }
}
```
Although I used `()` if I refresh this page Neither `true` nor `false` was gone.

Vue version is 1.0.21.
Thanks for your reply.

**Comment by gapipro** [comment]
@mqliutie you must be doing something wrong. Check my fiddle: http://jsfiddle.net/e0wpy14z/1/

I recommend upgrading to 1.0.26

**Comment by mqliutie** [comment]
I have found my mistake. I set value to a variable that wasn't initialized. So the value is not show at first

**Comment by HarshOB** [comment]
> @mqliutie you must be doing something wrong. Check my fiddle: http://jsfiddle.net/e0wpy14z/1/
> 
> I recommend upgrading to 1.0.26

Your fiddle URL is not working. maybe Vue version issue.

**Comment by yeyintnaung135** [comment]
<template v-if="detail_type != 'rq'">
                                <template v-if="check_invite==false">
                                    <a href="" class="btn btn-info m--pull-right" @click.prevent="gotoinvite()">
                                        Invite
                                    </a>
                                </template>
                                </template>

**Comment by moebaca** [comment]
@gapipro solution worked. I was thinking about trying the parens before Googling it, but force of habit hehe
