### ISSUE TITLE
事件会在子元素上触发

### ISSUE THREAD

**Issue by moxuandeng** [vuejs/vue#2222]
```
<div id="example">
<template v-for="item in items>
  <button v-on:click="greet" data-id="{{item.id}}" data-name="{{item.name}}">
    <i class="glyphicon glyphicon-edit icon-white"></i> Greet
</button>
</tempate>
</div>
```

```
var vm = new Vue({
  el: '#example',
  data: {
    name: 'Vue.js'
  },
  methods: {
    greet: function (event) {
      alert(event.target.tagName)
    }
  }
})
```

当点击按钮时, 如果点击的是<i>标签, event对象的target是<i>而不是button, 这样就无法获取到button的参数. 
虽然把参数和方法写成内联语句的形式没有问题, 但是当参数比较多时, 表达式会特别长, 而且看起来也不够直观.

**Comment by Dafrok** [comment]
要用MVVM思想考虑这个需求，数据不要通过DOM的方式来取，用view-model取。

**Comment by hanai** [comment]
一定要这样读数据的话，应该是 currentTarget

**Comment by moxuandeng** [comment]
@Dafrok 之前习惯了DOM的方式, 不知道view-model的方式是怎么取的?

**Comment by azad112358** [comment]
可以考虑将icon做成button的背景图

**Comment by yyx990803** [comment]
1. 这是事件冒泡的基本原理，和 Vue 无关；请参考 event.target 和 event.currentTarget 的区别。

2. 直接 `v-on:click="greet(item.name)"` 即可。先渲染到 DOM 再拿回来等于绕了一圈远路。

**Comment by moxuandeng** [comment]
谢谢各位解答
