### ISSUE TITLE
大神,能不能搞个vue.js,vue-route和loopback框架做个example或者generator

### ISSUE THREAD

**Issue by qxl1231** [vuejs/vue#2224]
angular.js和loopback框架有一个$ lb-ng server/server.js client/js/services/lb-services.js

可以很方便的生成相关的东西,但vue做前端,目前只有webpack+vue,而没有loopback+vue,
大神,能否搞一个适配loopback的脚手架` 目前企业级的公司,很多都采用的strongloop的loopback做东西,谢谢了~

**Comment by Dafrok** [comment]
vue-cli能否满足你？

**Comment by yyx990803** [comment]
我精力有限，只能专注前端的部分。如果需要你可以自己用 vue-cli 或者 yeoman 搭一个。

**Comment by cslinmiso** [comment]
Hi, I have made one of example for loopback.
[loopback-vue-boilerplate](https://github.com/cslinmiso/loopback-vue-boilerplate.git)
