### ISSUE TITLE
Suggestion: partial params

### ISSUE THREAD

**Issue by fullfs** [vuejs/vue#2232]
Hello!
Sometimes its nice to have an option to pass custom params into a partial. Like that:

```<partial name="block" :add-link="true">```
The principle I see is the same as lightweight VMs in ```v-for``` elements.

This would also require (probably) alternative syntax for partials: 

```
partials: {
    block: {
        props: {addLink: null},
        template: '<div>123</div>'
    }
}
```

You could say "use components then", but the point is I don't want most of components' features here. Just new data scope.

**Comment by posva** [comment]
You should just use a component! :smile: 

Look at #2221

**Comment by Nirazul** [comment]
What is the problem with using components? :D
Just exchange `partials` with `components` and go on to real problems :)

```js
components: {
    myBlock: {
        props: { addLink: null },
        template: '<div>123</div>'
    }
}
```

```
<component is="myBlock" :add-link="true">
```

**Comment by fullfs** [comment]
@Nirazul The case is exactly like with ```v-for``` instances. Actually, I want all parent component data to be inherited. Its like using now gone ```inherit: true```. Overall its very expensive in terms of performance. Using lighweight VM will lower the cost.

**Comment by fullfs** [comment]
@Nirazul If you take a look at ```v-for```, you can see it works exactly like I suggested for partials to work.
It creates new data scope, adding 1-2 additional props (key/item) to the scope, inherits parent's data.

I Could even use ```v-for``` for the case, repeating the partial with specialy created data objects.

**Comment by fullfs** [comment]
@Nirazul I mean, like that

```
{
    prop1: {value: true},
    prop2: {value: false}
}

<div v-for="addLink in prop1">
    <partial name="block"></partial>
</div>

<div v-for="addLink in prop2">
    <partial name="block"></partial>
</div>
```

**Comment by Nirazul** [comment]
I see, what you mean although I haven't been in the situation yet, where I wished this existed. 
It definitely would help to encapsulate some partials and improve reusability.

**Comment by oliverzy** [comment]
@Nirazul in this case, your partial has to be part of the component, right?

**Comment by Nirazul** [comment]
@oliverzy I'm not sure on what part you are replying to, but if you refer to my first comment: You can also use dynamic components with `<component :is="myComponentNameString">`. They should be registered globally beforehand, of course.

**Comment by oliverzy** [comment]
@Nirazul okay, I understand, thanks

**Comment by yyx990803** [comment]
Partials are something I always want to move away from: it's a composition mechanism very similar to string templates which I personally never use in my code.

I think if you are not concerned with performance, you should absolutely just use components instead. If performance is absolutely critical, then just replicate the blocks without using partials - because partials although being cheaper than components, still also has its own perf cost.
