### ISSUE TITLE
Keeping track of element in v-for when updated later?

### ISSUE THREAD

**Issue by cnicodeme** [vuejs/vue#2233]
Hi,

tell me if I'm wrong but I couldn't find any way to do it correctly.

I have a template that contains a v-for for an array, and a form element at the top.

When the user submit the form, I add a new entry in the array (at index 0, unshift) and then send a request to the server for processing.
The server can take time to process the data (quite heavy work on the back-end side) and return an updated result like 90 seconds after.

If I freeze the form while waiting for the server, I can update the line at entry 0 since I do an unshift of the array.

But the reason I add it right away is to allow the user to enter many entries from the form without having to wait for the server to reply.

The problem that arise is that when the server answer back, I don't have any idea how I can target the specific added entry in the array since it's not 0 anymore (new entries has been added in the mean time).

Here's a simplified .vue component of my situation : 

```
<template>
    <form method="post" v-on:submit.prevent="search">
        <input type="text" placeholder="Person name" required v-model="name" v-el="nameInput" />
        <input type="text" placeholder="Company" required v-model="company" v-el="domainInput" />
        <input type="submit" value="Search" class="btn show-m" />
    </form>
    <ul>
        <li transition="expand" v-for="contact in contacts" track-by="$index">
            <img v-bind:src="contact.avatar_url" width="40px" height="40px" class="cl-avatar" />
            <div class="cl-user">
                <strong class="cl-name">{{contact.name}} <span class="cl-company">{{contact.company}}</span></strong>
            </div>
        </li>
    </ul>
</template>

<script>
export default {
    data () {
        return {
            contacts: [],
            name: null,
            company: null
        }
    },
    methods: {
        search: function (event) {
            this.$http.post('/search', {
                name: this.name,
                company: this.company
            }).then(function (xhr) {
                // HERE ! How can I target the exact entry ?
                this.contacts.unshift(xhr.data)
            })

            this.name = ''
            this.company = ''

            this.contacts.unshift({'name': this.name, 'company': this.company})
        },
    }
}
</script>
```

**Comment by yyx990803** [comment]
Please ask questions on the forums.

**Comment by cnicodeme** [comment]
Sorry about that. (by the way, you are doing a truly great work, I really like vuejs, keep on going :) )
