### ISSUE TITLE
expose the api for adding custom modifier

### ISSUE THREAD

**Issue by pandada8** [vuejs/vue#2235]
I want to using a modifier to ignore bubbled event, and it will be very convenient if I can using something like `v-on:click.only` to limit the handler only be called when event only happened on the element.
Would it possible to expose the api ?

**Comment by smolinari** [comment]
http://vuejs.org/api/#v-on

Do you mean something like the .prevent or .stop modifiers?

You are also better off asking questions in the forum.  http://forum.vuejs.org/

Github issues are for bugs and suggestions only.

Scott

**Comment by yyx990803** [comment]
@smolinari I guess this counts as a feature request.

I'm not sure if opening up modification to built-in directives is a good idea, as that could make your code less portable. It seems this is not a very common use case and you can achieve that by simply checking `e.target === e.currentTarget` in your method.

**Comment by smolinari** [comment]
Ok. I guess I misunderstood what pandada8 meant by "ignore bubbled event" or what he intended to achieve overall. 

Scott

**Comment by pandada8** [comment]
Or just add this modifier in vue?
typing some modifiers is always easier than write `e.target === e.currentTarget` :smile:

**Comment by yyx990803** [comment]
@pandada8 how often do you need to do this? Can you provide an example of the use case?

**Comment by yyx990803** [comment]
Added `.self` modifier in 1.0.16.

**Comment by smolinari** [comment]
:+1: 

Scott

**Comment by pandada8** [comment]
thanks!
