### ISSUE TITLE
how to pass props to child through a directive

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#2238]
I want to custom a directive for dealing with props passing from parent to child. I didn't find much information from the doc, and I read the code of v-for, find it's complex to implement. 

In angular I can implement the compile function when custom a directive, is there a easy in vue to handle this?

**Comment by yyx990803** [comment]
Honestly I have no idea what you are trying to achieve. Why not just use normal props?

**Comment by yyx990803** [comment]
And please ask questions on the forum, not in issues.

**Comment by Jokcy** [comment]
@yyx990803 Actually it's not a question, it is a suggestion. I want to implement isolated scope like angular do. And after i read the code of v-for, I may have know some about it, and I suggest you make it easy. 

THX for your reply.

**Comment by yyx990803** [comment]
Vue directives are different from Angular directives, they should only be used for DOM manipulations. if you need props/scope you should use components.

**Comment by Giwayume** [comment]
@Tusko 
While the vnode is accessible, it is intended to be read-only.
