### ISSUE TITLE
<template v-if=''>

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/vue#2239]
这种形式不能弄简单点儿么

就直接
< v-if='' >< v >
这样不行么

**Comment by pandada8** [comment]
Vue 本身没有实现 html parser，模板的 parse 是靠浏览器来实现的
而且这个例子算个什么语法，符合 HTML 标准？

**Comment by yuu2lee4** [comment]
我就想说能不能整简单点儿  <t v-if=''></t>  也行啊  整那么长的单词没有必要

**Comment by icepy** [comment]
长一点我觉得可以接受，至少一眼能看明白，如果模版逻辑很多呢？这方面，我很赞同Apple的设计原则，虽然命名又臭又长。

**Comment by yuu2lee4** [comment]
能不能再提供一个类似上面的简短的 人们爱用哪个用哪个
