### ISSUE TITLE
Watch.deep not working as expected

### ISSUE THREAD

**Issue by taylorzane** [vuejs/vue#2240]
I'm running into an issue with `watch` using the `deep: true` option. I have the following component:

```coffee-script
MyComponent = Vue.extend
  template: '''
    <div id="bar">
      <button @click="changeFoo('up')">UP</button>
      <button @click="changeFoo('down')">DOWN</button>
      {{dir.up.foo}}
      {{dir.down.foo}}
    </div>
  '''
  data: ->
    dir:
      up:
        foo: false
      down:
        foo: false
  methods:
    changeFoo: (dir) ->
      @dir[dir].foo = !@dir[dir].foo
      console.log "changeFoo(#{dir})", @dir[dir].foo
  watch:
    # This one fires...
    'dir.up.foo': ->
      console.log 'watch.dir.up.foo', @dir.up.foo
    # This one fires...
    'dir.up':
      handler: ->
        console.log 'watch.dir.up', @dir.up
      deep: true
    # This one doesnt' fire. (Not that I expect it to)
    'dir.up': ->
      console.log 'watch.dir.up.no.deep', @dir.up
    # This one does not. Despite `deep: true`
    'dir':
      handler: ->
        console.log 'watch.dir', @dir
      deep: true


app = document.getElementById('app')

componentInstance = new MyComponent()

componentInstance.$mount().$before(app)
```

But `@dir[direction].foo = true` does not trigger the `dir` watch event.

It seems that `watch` is only traversing one level deep.

Here is a Fiddle for repro.

http://jsfiddle.net/tssk9ppx/4/

The Fiddle is Vue 1.0.8, I am also able to reproduce this issue on 1.0.15.

EDIT: Updated formatting.

**Comment by gebilaoxiong** [comment]
Remember to look at the compiled code
[code compile](http://coffee-script.org/#try:MyComponent%20%3D%20Vue.extend%0A%20%20template%3A%20'''%0A%20%20%09%3Cdiv%20id%3D%22bar%22%3E%0A%20%20%20%20%20%20%3Cbutton%20%40click%3D%22changeFoo('up')%22%3EUP%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3Cbutton%20%40click%3D%22changeFoo('down')%22%3EDOWN%3C%2Fbutton%3E%0A%20%20%20%20%20%20%7B%7Bdir.up.foo%7D%7D%0A%20%20%20%20%20%20%7B%7Bdir.down.foo%7D%7D%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20'''%0A%20%20data%3A%20-%3E%0A%20%20%20%20dir%3A%0A%20%20%20%20%20%20up%3A%0A%20%20%20%20%20%20%20%20foo%3A%20false%0A%20%20%20%20%20%20down%3A%0A%20%20%20%20%20%20%20%20foo%3A%20false%0A%20%20methods%3A%0A%20%20%09changeFoo%3A%20(dir)%20-%3E%0A%20%20%20%20%20%20%40dir%5Bdir%5D.foo%20%3D%20!%40dir%5Bdir%5D.foo%0A%20%20%20%20%20%20console.log%20%22changeFoo(%23%7Bdir%7D)%22%2C%20%40dir%5Bdir%5D.foo%0A%20%20watch%3A%0A%20%20%09%23%20This%20one%20fires...%0A%20%20%09'dir.up.foo'%3A%20-%3E%0A%20%20%20%20%09console.log%20'watch.dir.up.foo'%2C%20%40dir.up.foo%0A%20%20%20%20%23%20This%20one%20fires...%0A%20%20%20%20'dir.up'%3A%0A%20%20%20%20%09handler%3A%20-%3E%0A%20%20%20%20%20%20%09console.log%20'watch.dir.up'%2C%20%40dir.up%0A%20%20%20%20%20%20deep%3A%20true%0A%20%20%20%20%23%20This%20one%20doesnt'%20fire.%20(Not%20that%20I%20expect%20it%20to)%0A%20%20%20%20'dir.up'%3A%20-%3E%0A%20%20%20%20%09console.log%20'watch.dir.up.no.deep'%2C%20%40dir.up%0A%20%20%20%20%23%20This%20one%20does%20not.%20Despite%20%60deep%3A%20true%60%0A%20%20%09'dir'%3A%20%0A%20%20%20%20%09handler%3A%20-%3E%0A%09%20%20%20%20%09console.log%20'watch.dir'%2C%20%40dir%0A%20%20%20%20%20%20deep%3A%20true%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%0Aapp%20%3D%20document.getElementById('app')%0A%0AcomponentInstance%20%3D%20new%20MyComponent()%0A%0AcomponentInstance.%24mount().%24before(app))

**Comment by taylorzane** [comment]
@gebilaoxiong What is wrong with the compiled code?

**Comment by gebilaoxiong** [comment]
```javascript
    'dir': {
      handler: function() {
        console.log('watch.dir', this.dir);
        return {
          deep: true
        };
      }
    }
```
The indentation of the code has a problem

**Comment by taylorzane** [comment]
Yes, but if you look at the Fiddle that I linked, that indentation is not an error. I just didn't correct the indentation in the Issue because I linked to the Fiddle.

**Comment by gebilaoxiong** [comment]
the code from Fiddle

**Comment by taylorzane** [comment]
```javascript
// Generated by CoffeeScript 1.9.3
var MyComponent, app, componentInstance;

MyComponent = Vue.extend({
  template: '<div id="bar">\n  <button @click="changeFoo(\'up\')">UP</button>\n  <button @click="changeFoo(\'down\')">DOWN</button>\n  {{dir.up.foo}}\n  {{dir.down.foo}}\n</div>',
  data: function() {
    return {
      dir: {
        up: {
          foo: false
        },
        down: {
          foo: false
        }
      }
    };
  },
  methods: {
    changeFoo: function(dir) {
      this.dir[dir].foo = !this.dir[dir].foo;
      return console.log("changeFoo(" + dir + ")", this.dir[dir].foo);
    }
  },
  watch: {
    'dir.up.foo': function() {
      return console.log('watch.dir.up.foo', this.dir.up.foo);
    },
    'dir.up': {
      handler: function() {
        return console.log('watch.dir.up', this.dir.up);
      },
      deep: true
    },
    'dir.up': function() {
      return console.log('watch.dir.up.no.deep', this.dir.up);
    },
    'dir': {
      handler: function() {
        return console.log('watch.dir', this.dir);
      },
      deep: true
    }
  }
});

app = document.getElementById('app');

componentInstance = new MyComponent();

componentInstance.$mount().$before(app);
```

I compiled the code on my machine and this is the output that I got.

**Comment by taylorzane** [comment]
@gebilaoxiong I updated the code in the original post. I also updated the Fiddle.

Now the issue is not happening in the Fiddle. I will need to check this on my local environment again.

**Comment by gebilaoxiong** [comment]
Really? But he's normal on my machine.
You really should have a good check of the code.
Good night.

**Comment by gebilaoxiong** [comment]
yes! close it

**Comment by yyx990803** [comment]
The fiddle seems to be working fine now, could it be your local indentation (e.g. mixing spaces/tabs)? Closing for now, feel free to reopen if you can reproduce again.
