### ISSUE TITLE
watcher.run

### ISSUE THREAD

**Issue by gebilaoxiong** [vuejs/vue#2241]
[watcher:run](https://github.com/vuejs/vue/blob/dev/src/watcher.js#L231)
这个方法叫diff是不是更合适一些

事实上你只是把wacher放入队列中，但是还是在做diff的工作

**Comment by yyx990803** [comment]
这是 batcher 预期的 interface，每一个 batcher job 必须有 run 方法。
况且这里也不只是 diff，还会收集依赖，触发回调之类的。纠结这个方法的命名意义不大。

**Comment by gebilaoxiong** [comment]
可能是吧，我觉得你的命名不是很贴切
