### ISSUE TITLE
Passing Data with props question

### ISSUE THREAD

**Issue by badman-rodriguez** [vuejs/vue#2243]
This issue has been a pain and can't seem to get it working properly.
Some background, i'm using the modular approach which means i'm using vue templates and vueify to bundle it up.
I have this code:

the HTML is:
```
<li is="component" v-for="item in mutlpleItems" :itemData="itemData" :itemGroup="itemGroup" :passingText="passingText">
</li>
```

itemData, itemGroup, and passing text have data.

the vue template is:
```
<template>
<li v-if="passingText == text" >
// stuff
</li>
</template>
```

```javascript
<script>
    export default {
        name: 'single-item',
        props: {
            item: Object,
            itemGroup: Object,
            passingText: String
        },
        methods: {
            showStuff:function() {
                console.log(this.passingText);
                //returns undefined <---- Why does this happen?
                console.log(this.item);
                //returns item object <---- This works just fine, why not the string?
            }
        }
    }
</script>
```
Console Output:
``` javascript
Object {name: "passingText", path: "passingText", options: Object, mode: 0, raw: null}
passingText is: undefined
```
What am i missing here?

**Comment by yyx990803** [comment]
Please provide a runnable reproduction.

**Comment by Mat-Moo** [comment]
This should be on the forum, but it's the camel case issue on the props, you need to pass in the props as :item-data: item-group, passing-data:
http://vuejs.org/guide/components.html#camelCase_vs-_kebab-case
