### ISSUE TITLE
is there a vue way of React.createElement (How to pass vue element to child component through props)?

### ISSUE THREAD

**Issue by adcentury** [vuejs/vue#2245]
I know this is weird. 

In react, I can create an element using

```javascript
var ele = React.createElement(...);
```

then I can pass it to a child component through props

```javascript
<Child myElement={ele} />
```

In vue, we often use slot to pass content into a child component from outside. But I still want to know if there is a way to pass element to child like I did in react. Thanks!

**Comment by yyx990803** [comment]
There's no such equivalency - basically you have to use slots. It would be better if you also explain what use case you have for it.Also, this question is better posted on the forums.

**Comment by adcentury** [comment]
@yyx990803 Sorry about that... I have move it to the forums and added a user case.

http://forum.vuejs.org/topic/1752/how-to-pass-vue-element-to-child-component-through-props
