### ISSUE TITLE
If the component is an asynchronous component, the v-ref is not properly acquired in the parent component

### ISSUE THREAD

**Issue by chenweiqun** [vuejs/vue#2247]
If the component is a async component, then the v-refs is empty.

		var test = Vue.component('test',{
			template:"<div><async-example v-ref:ae></async-example><normal v-ref:nm></normal></div>",
			ready:function(){
				console.log(this.$refs);//ae is null nm is object
			}
		});

		Vue.component('async-example', function (resolve, reject) {
		  setTimeout(function () {
		    resolve({
		      template: '<div>I am async!</div>'
		    });
		  }, 1000);
		});

		Vue.component('normal',{
					template:"<div>normal compoent</div>",
		});

		new test().$mount("#app");

**Comment by Nirazul** [comment]
I did a [quick pen](http://codepen.io/Nirazul/pen/XXqeRG?editors=1111) with your code.

As you can see, after the async component has been loaded, the `$refs` object is set as you would expect it.

**Comment by yyx990803** [comment]
Obviously the ref cannot be set before the component is actually rendered.
