### ISSUE TITLE
v-el behaviour

### ISSUE THREAD

**Issue by jbrialon** [vuejs/vue#2248]
Hello,

right now when we use v-el we are able to register a reference to a DOM element on its owner Vue instance’s $els object for easier access.

it could be great if it could retrieve an array of object by using v-els for example

```html
<span v-els:msg>hello</span>
<span v-els:msg>world</span>
```

```javascript
this.$els.msg // -> array(<span>hello</span>,<span>world</span>);
```

**Comment by lbineau** [comment]
@jbrialon would be a great feature ! :+1:

**Comment by blake-newman** [comment]
:+1:

**Comment by yyx990803** [comment]
I don't quite get why this is useful. Any convincing use case?

**Comment by jbrialon** [comment]
In my case I was animating different elements using Tweenmax and using v-el was pretty convenient then I had to use the stagger function from Tweenmax and I thought it would have been great if we could retrieve an array 

that's one example of course but there would be other applications for the functionality

**Comment by cgarnier** [comment]
Yes could be great for massive animation stuff.

**Comment by AnyGong** [comment]
@jbrialon  Vue.js the `if-else` equivalent to `document.getElementById ()`, which is similar to your needs, is not used `document.querySelectorAll ('.msg') // -> Array (<span> hello </ span>, <span> world </ span>);`，
I have this idea possible? You can not achieve this requirement?

**Comment by jbrialon** [comment]
@AnyGong of course but why implementing v-el if you could use document.getElementById in the first place then

**Comment by young-steveo** [comment]
It seems useful.  Might I suggest this syntax:

Instead of `v-els` use a modifier for the standard `v-el`.  A `.list` modifier would tell the directive to put the elements in an array:

```html
<span v-el:message>hello</span> <!-- this.$els.message -->
<span v-el:messages.list>world 1</span> <!-- this.$els.messages[0] -->
<span v-el:messages.list>world 2</span><!-- this.$els.messages[1] -->
```

**Comment by jbrialon** [comment]
v-els was a suggestion but .list is a good idea too ! 👍

**Comment by blake-newman** [comment]
I like the modifier as my preference but either will suffice.

**Comment by Gerhut** [comment]
I have a requirement that make the window scroll to the nth row of a table rendered by `v-for`.

It array of `v-el` is supported I can wrote:

```html
<table>
<tbody>
  <tr v-for="" v-el:row></tr>
</tbody>
</table>
```

```
exports.methods.scrollToRow = function (index) { window.scrollTop = this.$els.row[index].scrollIntoView() }
```

**Comment by yyx990803** [comment]
I'm not convinced by the benefits of this suggestion - it introduces extra syntax on Vue's part (increases both implementation complexity and learning cost) while the same can simply be achieved with `this.$el.querySelectorAll`.
