### ISSUE TITLE
关于采用limitBy进行取数据时，元素的高度问题

### ISSUE THREAD

**Issue by AnyGong** [vuejs/vue#2251]
```
<div v-el:wrapper>
   <span v-for="list in lists | limitBy 10"></span>
</div>
```

我是采用`limitBy`显示指定条数据，`lists `的对象数据大概有100条，我是默认显示10条，用户知道要去拖动滚动条才能看到第10条数据。在

```
$nextTick(function(){
     console.log("渲染完数据元素的高度："+this.$els.wrapper.clientHeight)
     window.onscroll=function(){
        console.log("用户开始滚动的高度："+this.$els.wrapper.clientHeight)
     }
})
```

测试发现`渲染完数据元素的高度`和`用户开始滚动的高度`结果不一样。我的理解，元素的可见区域高度不是应该都是不变的吗？除非我滚动的时候，对这个`lists`进行了改变，可我滚动的时候没有做任何其他更新dom的操作。忘作者解惑。

测试环境：

> android4.4 hybrid h5

```

**Comment by yyx990803** [comment]
这个属于提问，请发到论坛，另外附上重现。

**Comment by AnyGong** [comment]
sorry,后来经过我的不断测试，发现是我用的这个hybrid框架造成的。后续我会多加注意的。tks！
