### ISSUE TITLE
Including comment in template body breaks prop inheritance

### ISSUE THREAD

**Issue by efc-awebb** [vuejs/vue#2253]
Was having a world of trouble getting prop inheritance to work between a template and its instance (with the `class` prop specifically). Turns out that having comments in the code breaks this behavior.

Presumably an issue of trying to apply them to the first node in the template's element tree, regardless of whether it is a CommentNode.

<script src="https://gist.github.com/efc-awebb/bc6b4bccc2d9c426f20f.js"></script>

**Comment by efc-awebb** [comment]
https://gist.github.com/efc-awebb/bc6b4bccc2d9c426f20f

<script src="https://gist.github.com/efc-awebb/bc6b4bccc2d9c426f20f.js"></script>

**Comment by efc-awebb** [comment]
Relevant dependencies:

```json
    "vue": "^1.0.15",
    "vue-hot-reload-api": "^1.2.0",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^8.0.0",
    "vue-style-loader": "^1.0.0",
```

**Comment by jsiebach** [comment]
Comments are considered nodes, and therefore by having a comment as well as a div in the template you've created a fragment instance (a template with multiple nodes).  You can read about the disadvantages of fragment instances [here](http://vuejs.org/guide/components.html#Fragment_Instance), one of which is no prop attributes are accepted.  You can solve it by moving your comment inside the div

```
<template>
	
	<div>
        <!-- Comment here is ok -->
		<slot></slot>
	</div>
</template>
```

**Comment by Nirazul** [comment]
Maybe this should produce a warning.

**Comment by jsiebach** [comment]
In debug mode it does: "[Vue warn]: Attribute "class" is ignored on component because the component is a fragment instance"

**Comment by Nirazul** [comment]
Hmm.. I guess it's quite hard to add information to why the fragment instance was created.

**Comment by efc-awebb** [comment]
Thanks! I would consider updating the docs, since the comment thing specifically feels like a little bit of a gotcha - e.g.:

```
There are multiple conditions that will turn a Vue instance into a fragment instance:

1. Template contains multiple top-level elements (including HTML comment nodes).
```

**Comment by krishna303063** [comment]
this is a very intresting topic so very exclusive [bing dashboard](http://bingrewards.info) and positive think in article any problem so search now bing is a search engine
