### ISSUE TITLE
Event Modifier:  @click.capture="captureClick"

### ISSUE THREAD

**Issue by diverted247** [vuejs/vue#2264]
IE9+ supports EventTarget.addEventListener() with capture and bubble phases. Events default to the bubble phase but sometimes, it is handy to catch the event as it heads to the target across the DOM.

I would love to see an event modifier added to support making capture easy to add into template/components.

Example:
```html
<div @click.capture="captureClick" @click="bubbleClick" >
     <a @click="doThat">CLICK ME</a>
</div>
```

**Comment by yyx990803** [comment]
Shipped in 1.0.16.
