### ISSUE TITLE
Select complex objects

### ISSUE THREAD

**Issue by lbineau** [vuejs/vue#2266]
Hi,

I'm trying to do a simple country/city selector (you select the coutry, it updates the city list)
The values of the select options have complex JS value (Object) rather than a simple String value.
I can't manage to always have the first option selected even if I put selected="selected" attribute.
Here is a usecase : http://codepen.io/lbineau/pen/KVedvL

Is there any way to give the option a JS Object rather than a String value and select the first item ?

**Comment by yyx990803** [comment]
See http://vuejs.org/guide/forms.html#Value_Bindings
