### ISSUE TITLE
slot in child component

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#2268]
Hi,

I know this is somewhat strange but I need nested components which pass their content on.
```jade
//comp1 template
.comp1
  comp2
    slot

//comp2 template
.comp2
  slot

//usage
comp1
  comp3
```
the generated dom turns out correctly (which is amazing :smile:)
```jade
comp1
  comp2
    comp3
```
but the comp3 will be in `$children` of comp1 and not of comp2
(in my case it is even more complicated as comp2 and comp3 have `v-for`s and so I can't even search the right comp3 out of the `$children` of comp1)

**Comment by paulpflug** [comment]
I tried to work around by basically doing this:
```jade
// comp1 template
.comp1
  slot(:data="data" v-for="data in dataset")
// usage
comp1
  comp2
```
but comp2's data prop won't be bound..

**Comment by yyx990803** [comment]
This is working as intended, so I think this is more like a question. Please move it to the forum instead.
Also please clarify what are you trying to achieve - access `comp3` from `comp2`?

**Comment by paulpflug** [comment]
I made a small [fiddle](https://jsfiddle.net/dswto9g5/1/)

I'm trying to build a sophisticated `v-for` with [Clusterize.js](https://nexts.github.io/Clusterize.js/) functionality in form of a component.
Basically I have 4 clusters (own components - only used within the main component) with each a few (depending on content and overall height) rows (also own components, managed by the corresponding cluster component).
The clusters move on scrolling and the rows get filled with the appropriate data.

I got this already working but only when I create the rows from a fixed template.

here is my code more detailed: 
```vue
##clusterize.vue
<template lang="jade">
.clusterize
  // ...
  clusterize-cluster(v-for="cluster in 4"")
    slot
 // ...
</template>
<script lang="coffee">
module.exports =
  components:
    "clusterize-cluster": require "./clusterize-cluster"
   # ...stuff to fill clusterize-cluster.data
</script>

##clusterize-cluster.vue
<template lang="jade">
.clusterize-cluster
  slot(:data.sync="d" v-for="d in data")
</template>
<script lang="coffee">
module.exports =
  props:
    "data":
      type: Array
      default: -> []
</script>

##clusterize-row.vue
<template lang="jade">
.clusterize-row(v-show="data != null")
  slot
</template>
<script lang="coffee">
module.exports =
  props:
    "data":
      default: null
</script>

```

I want it used like this:
```jade
// in template
clusterize(data="[{name:'something'}]")
  clusterize-row
    {{name}}
```
But I can't get the data within 'clusterize-row' or access the right 'clusterize-row' within 'clusterize-cluster'.

(later on I want to make it a small datatable (like [ag-grid](https://www.ag-grid.com/)) where I define the content by columns, so clusterize-row need to be exchangeable, a buggy version of my first try is [here](https://github.com/paulpflug/vue-materialize/blob/master/src/data-table.vue))

**Comment by paulpflug** [comment]
I uploaded my current state of [vue-clusterize](https://github.com/paulpflug/vue-clusterize)
