### ISSUE TITLE
Dynamic Components not listening to Broadcasedt events 

### ISSUE THREAD

**Issue by ikristher** [vuejs/vue#2269]
Hello When I try loading a component dynamically, it does not listen events fired by its parent  using $broadcast method. There must me something I am doing wrong

Here is the code in my parent component

```
<component
:flights-search="flightsSearch"
:booking-request.sync="bookingRequest"
:selected-flight.sync="selectedFlight"
:is="currentView"

:flights.sync="flights"
:airports="airports"
:get-airport="getAirport"
:airlines="airlines"
>
```

**Comment by ikristher** [comment]
Okay got it working, I delayed calling the broadcast to 500 ms. Also using the activate hook is an alternative.

**Comment by majuansari** [comment]
@ikristher  Do you think there is a better way than delaying the broadcast using setTimeout ?
