### ISSUE TITLE
change of an reactive a[0] doesn't trigger setters of a[0].b.c?

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue#2270]
in the following case the output remains 2 rather than 3, which implies that vue doesn't trigger getter of a.b[1].c when a.b[1] changes.
```
<div id="app">{{ output }}</div>`
```
```
vm = new Vue({
  el : '#app',
  data : {
    a : {
      b : [
        {c : 1},
        {c : 2}
      ]
    }
  },
  computed : {
    output : function () {
      return this.a.b[1].c
    }
  }
})
vm.a.b[1] = {c : 3}
```
I tested a few cases and found:

change of `a` triggers `a.b`
change of `a` triggers `a.b.c`
change of `a.b` triggers `a.b.c`
change of `a` triggers `a[0].b.c`
change of `a[0]` **doesn't** trigger `a[0].b.c`
change of `a[0].b` triggers `a[0].b.c`

**Comment by yyx990803** [comment]
http://vuejs.org/guide/list.html#Caveats
