### ISSUE TITLE
When using v-for and conditional rendering - custom filter doesn't update the template as expected

### ISSUE THREAD

**Issue by bryandease** [vuejs/vue#2273]
I'm having a problem showing filtered results when using v-if inside a v-for template block.  My current template looks like this (I'm using laravel so the @include is just some html that gets inserted to show the proper markup for that type of card): 

    <ul>
        <template v-for="card in cards | onlyMatching">
            <li transition="expand" v-if="card.Data.event_type === 'user_comment'">
                @include('feed.card_templates.user_comment')
            </li>

            <li transition="expand" v-if="card.Data.event_type === 'user_position'">
                @include('feed.card_templates.user_position')
            </li>
        </template>
    </ul>

In my component I have a data property called "filterKey" which the custom filter uses to filter results.  So my custom filter looks like this:

	Vue.filter('onlyMatching', function(cards)
	{
	    var $this = this;
	
	    return cards.filter(function(item)
	    {
	        return item.Data.event_type.match($this.$data.filterKey);
	    });
	});

The problem is - whenever I dynamically change the filterKey property from user_comment to user_position the HTML that is rendered from the template doesn't update.  And when I click off of one and back to the other it actually duplicates the original html in the browser.  When I look at devtools I can see the filter type changing but it's not reflected on the actual page.  

I know the filter itself is working properly - because if I take out the conditional parts and just do this:

    <ul>
        <template v-for="card in cards | onlyMatching">
            <li>@{{{ card.Data.event_type }}}</li>
        </template>
    </ul>

The event types for each of these items list out just fine - and changing the "filterKey" property shows only those li's that match as expected.  Is there some other way I need to go about doing this conditional rendering to make this work as expected or should it work the way I have it now?

**Comment by yyx990803** [comment]
Can you please provide a minimal reproduction in the form of a jsfiddle or jsbin?

**Comment by bryandease** [comment]
Looks like this was a problem with Laravel's blade engine and using template partials.  I was able to get it working.  Thanks!
