### ISSUE TITLE
Checkbox model not working in IOS

### ISSUE THREAD

**Issue by impeto** [vuejs/vue#2274]
Does enyone else have problems with the click event of checkboxes in IOS? It looks like when you check a checkbox the model doesn't propagate and nothing happens as a result of checking the checkbox.

**Comment by yyx990803** [comment]
Please make sure to read [the issue filing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening issues. For bug reports you should provide a JSFiddle or JSBin containing a set of reproducible steps. Simple descriptions are not enough for us to triage the issue.
