### ISSUE TITLE
获取到$children数组乱序

### ISSUE THREAD

**Issue by zhangking** [vuejs/vue#2275]
父组件通过$children获得的子组件数组乱序
如父组件有12个子组件，获得的数组顺序变为
7	1	3	4	5	6  	2  	8	9	10  	11	12
是否是为了做并行解析相关的事情还是什么，应该如何做获取正确顺序

**Comment by yyx990803** [comment]
`$children` 并不保证顺序，也不应该依赖子组件的顺序。能够依赖的是产生这些子组件的数据。

**Comment by rwu823** [comment]
一直在思考一個問題，請問尤大如要設計 `Select` 組件，哪一種為最佳實踐？

```jsx
<Select options={options} />
```
v.s 

```jsx
<Select>
  { options.map((option)=>{
    return <Option></Option>
  }})
</Select>
```

上面的好處是，能夠依賴數據源 `options`，下面的好處是可以很靈活應對每次數據源格式的不一致，如果採用下者該如何獲取數據源 `options`？
