### ISSUE TITLE
Immediate flag on $watch breaks unwatching

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue#2276]
Repro: https://jsfiddle.net/simplesmiler/cz9cm64p/

**Comment by yyx990803** [comment]
This is technically not a bug, because with `immediate: true` the callback is called **before** the assignment to `unwatch` is complete.

This usage also doesn't seem to make sense: it's basically equivalent of `console.log(this.value)`. Why do it with a $watch?

**Comment by simplesmiler** [comment]
I have overlooked the fact about the **before** part. I now see why this does not work.

I also see that my example is not representative. My actual code calls `unwatch` conditionally. I don't want to call `doSomething` until the `value` is defined.
Currently I have the following:
``` js
if (this.value !== undefined) {
  doSomethng(this.value);
} else {
  var unwatch = this.$watch('value', function(value) {
    if (value !== undefined) {
      unwatch();
      doSomething(value);
    }
  });
}
```

I'm closing the issue since there is no bug. I'm probably doing something weird anyways.
