### ISSUE TITLE
Array on dynamic Prop

### ISSUE THREAD

**Issue by nsilvah** [vuejs/vue#2278]
I'm trying to pass an array as a dynamic prop, but the prop is passed as undefined instead of the actual array.

Here is a small fiddle showing the issue:

https://jsfiddle.net/ukt11zam/2/

**Comment by yyx990803** [comment]
You fiddle has nothing to do with what you described...

**Comment by nsilvah** [comment]
Sorry, forgot to update the fiddle. Now the fiddle is correct.

**Comment by nsilvah** [comment]
https://jsfiddle.net/ukt11zam/10/
