### ISSUE TITLE
How to limit number of checked checkboxes?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [vuejs/vue#2279]
I am trying to limit number of checkboxes selected for one model, but it is giving me a really hard time. I run out of ideas, so I have tried to create a custom directive, but it doesn't seem to get triggered on checkbox change.

Could you please advice what is the best approach for this?

https://jsfiddle.net/h41L1Lb2/

```
Vue.directive('five', function (value) {
	console.log(this.el)
})


new Vue({
    el: '#app',
    data:{
    	providers:[1,2,3,4,5,6,7],
      selected_providers: []
    },
    computed:{
        limit_reached: function(){
            if(this.selected_providers.length > 5){
                return true;
            }
            return false;
        }
    }
})
```

Thanks

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening the issue. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
