### ISSUE TITLE
Attribute complex expression

### ISSUE THREAD

**Issue by fullfs** [vuejs/vue#2281]
Hello!
Sorry, maybe there is already answer somewhere, didn't know how to search for it.

In version 0.12 syntax it was possible to write attribute value like this:

```title="{{value | filter}} {{anotherValue | filter2}}"```

Is there a way to do the same in the new syntax?

**Comment by Mat-Moo** [comment]
Please ask questions in the forum : http://forum.vuejs.org
Depends on the context, but you can do something like :-
http://jsbin.com/mitivizife/edit?html,js,console,output

**Comment by fullfs** [comment]
@Mat-Moo Sorry, you didn't get the case. Looks like my description is a bit off.
Thanks for the forum link, posted a topic there: http://forum.vuejs.org/topic/1948/attribute-complex-expression (the description in there is more detailed).

**Comment by Mat-Moo** [comment]
Updated, your original syntax is still good http://jsbin.com/rolobudeco/edit?html,output

**Comment by fullfs** [comment]
Oh. Thanks! Thought the syntax was deprecated :)
