### ISSUE TITLE
slot in table tag (colgroup, tbody)

### ISSUE THREAD

**Issue by jingz** [vuejs/vue#2283]
I want to create a table component that distribute styling columns through `colgroup` and `col` tags and let who use the component can override how `tbody` content rendered. I use `named slot` in Vuejs but It dose not work (the **colgroup** and **table body content** slot seem not to replace with the user's content) here the simple code [jsfiddle](https://jsfiddle.net/k1eq1369/)

not sure this is a proper way. is there any better solution. Thanks

**Comment by yyx990803** [comment]
`<slot>` cannot appear inside `<table>` due to HTML spec restrictions - it can only appear inside `<td>` afaik. Also, table elements like `<tbody>` cannot appear "naked" without a surrounding `<table>`. This is a limitation of how HTML works and unfortunately you just have to work around it.

**Comment by jingz** [comment]
Thanks. I use `is` attribute for working around it. https://jsfiddle.net/0xgj83up/

**Comment by xiaolongyuan** [comment]
+1

**Comment by julianandreszb** [comment]
Please check this. It works for me:
https://jsfiddle.net/9cdLvfvw/1/
