### ISSUE TITLE
vue下如何实现如angular对于单一相对的item的scope进行改变而不影响全局？

### ISSUE THREAD

**Issue by almoce** [vuejs/vue#2284]
列子， 如何实现像angular下那样的效果

```
<div id="app">
 <li v-for="item in items">
            <button v-on:click="showtext = !showtext">change</button>
            <span v-show="showtext">{{item.text}}</span>
      </li>
</div>
```

```
   var thedata = new Vue({
    el: '#app',
    data: {
        items: [
        {'id':1, 'text':'text1'},
        {'id':2, 'text':'text1'},
        {'id':3, 'text':'text1'},
        {'id':4, 'text':'text1'},
        ]
    },
})
```

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
