### ISSUE TITLE
Convert string of css using V-bind

### ISSUE THREAD

**Issue by chrisbell08** [vuejs/vue#2285]
I have a string on some inline styles in a db column and before using vue I would just output that value into the style tag server side like so:

`` 
$someStyles = "top:10px;left:150px;position:absolute;";
<button style="{!! $someStyles !!}"></button>
``
I'm trying to move this all over to Vue but at the moment I have to use php to play around with the string to break apart the properties and values to and array, to then json encode, and then parse so I can assign them to a js object and use v-bind. Is there a way to pass a string of css to to v-bind and have it break apart the string instead of an object?

I think it would be a nice feature if not already available?

Cheers

**Comment by OEvgeny** [comment]
Please use forum to ask questions.

As I know it is not already available. But you can use custom directive to do it.

**Comment by yyx990803** [comment]
You can directly give `v-bind:style` a string.

**Comment by OEvgeny** [comment]
@yyx990803 Wow didn't know about that.

**Comment by chrisbell08** [comment]
@OEvgeny Sorry hadn't spotted the forum before, will go there in future.
@yyx990803 That's awesome, saves me a lot of headache manipulating strings!

Cheers Guys!
