### ISSUE TITLE
v-for中嵌套v-if，无法做到数据绑定。

### ISSUE THREAD

**Issue by haoziluo** [vuejs/vue#2286]
只是在初始化的时候会做一次判断，之后数据的改变无法同步到dom，不知道这是不是Vue.js本身的设计，如果遇到这种列表子元素会动态变化的情况，应该怎么办？

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by haoziluo** [comment]
![image](https://cloud.githubusercontent.com/assets/2647388/12772829/4fa1f7cc-ca70-11e5-8678-e6bf202d2a4e.png)

**Comment by haoziluo** [comment]
v-bind在这种情况下也会失效。

**Comment by AnyGong** [comment]
@haoziluo 你说的这种`列表子元素会动态变化`。不知道你是怎么改变的。我的猜测是，你的子元素更新，肯定是依赖父元素的状态。就像 DOM一样，你的parent是 display:none，child再怎么更新操作，也还是无用功，不会显示，更不会更新。始终记得脑子里面的VM模型，Vue的核心，

> 用数据驱动视图

**Comment by AnyGong** [comment]
补充一下 @haoziluo 在 `v-for`里面的这种操作，我在我项目中也用到过，不会出现你说的这种情况，`v-if`,`v-show` 都不会

**Comment by lincenying** [comment]
order.layer是不是根本不存在?

**Comment by yyx990803** [comment]
重现的意思是要看到 bug 实际出现。只有模版是不够的，问题可能出在你的 js 代码里，比如 order.layer 初始化的时候没有定义。

**Comment by yyx990803** [comment]
Closing (inactivity). Please reopen if you can follow up with more information.

**Comment by bnugong** [comment]
这个bug好像真的有。。。

**Comment by wuze** [comment]
row 是外面的，　这样　也是显示不出来的　
 <template v-for="nd in smsTpl">
     <template v-if="nd.action==row.val">{{nd.content}}</template>                                                           
  </template>

**Comment by wuze** [comment]
```
 row 是外面的，　这样　也是显示不出来的
<template v-for="nd in smsTpl">
    <template v-if="nd.action==row.val">{{nd.content}}</template>                                                           
   </template>

```

**Comment by lincenying** [comment]
在data里把row初始化进去

**Comment by OuYancey** [comment]
请参阅：https://cn.vuejs.org/v2/guide/list.html#注意事项

**Comment by tonyDx** [comment]
这个bug确实存在，原因在于v-if和v-else的并行使用，v-else去掉吧
