### ISSUE TITLE
Element generated with slot does not update contents dynamically.

### ISSUE THREAD

**Issue by ardoramor** [vuejs/vue#2288]
I've read through the API and didn't see anything that said this should not work:

My parent component has the following template:

	<template>
		...
        	<component v-ref:navbar :is="navbarType" keep-alive>
			<template slot="menu-options">
				<li v-for="menuOption in menuOptions">
					<a v-link="menuOption.link" class="btn withripple" @click="onMenuOptionAction(menuOption.id)">
						<i class="material-icons" v-if="menuOption.icon">{{menuOption.icon}}</i>
						<span v-if="menuOption.title">{{menuOption.title}}</span>
					</a>
				</li>
			</template>
		</component>
		...
	</template>

Child component has the following template:

	<template>
		...
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header pull-left">
					<a class="navbar-brand">Test</a>
				</div>
				<div class="navbar-header pull-right">
					<ul class="nav navbar-nav navbar-left">
						<slot name="menu-options"></slot>
					</ul>
				</div>
			</div>
		</nav>
		...
	</template>

If the `menuOptions` are available before `<navbar>` renders (there is a case when `navbarType` may be null, resulting in not rendering of navbar but is later set), options render properly. However, if the `menuOptions` are not set or are later updated, the change does not pass through onto the `slot`. I understand that the slot is a component or based on that API. Yet, there is no mention that the content of the slot cannot change once generated. Did I make a mistake somewhere?

**Comment by yyx990803** [comment]
Please provide a reproduction of the bug actually happening. Also, make sure you've read [this section](http://vuejs.org/guide/reactivity.html).

**Comment by ardoramor** [comment]
Ok, I have actually created a jsfiddle for it. After writing it from scratch, I saw that the concept works as I expected. So then I compared my code to my jsfiddle and saw that I somehow accidentally put `menuOptions` in the `App` right outside of `data`! Doh!
