### ISSUE TITLE
Unwatch keypath specification

### ISSUE THREAD

**Issue by hiendv** [vuejs/vue#2289]
```js
var a = {
  b: {},
  c: {}
}
var unwatch = vm.$watch('a', function (newVal, oldVal) {
  // do something
}, { deep:true });
```
Is is possible to unwatch a specific key or in other words **exclude** a property when deep watch?
```js
unwatch('a.b')
```
Thank you !

**Comment by yyx990803** [comment]
I don't think that makes sense - unwatch and the watcher is a one to one relationship. If you want to watch only a subpath, then use separate watchers.

**Comment by hiendv** [comment]
Well, I think it would be *easier* than specifying, e.g. 9 watchers because of the other prop shouldn't be watched. Thank for your explantion.

**Comment by yyx990803** [comment]
Relying on a single deep watcher for this many properties with exceptions seems like a sign of design problems to me. Consider using computed properties or watching a function instead. Only use watch when you absolutely has to.

**Comment by hiendv** [comment]
@yyx990803 Thank you so much for the advice !

**Comment by hiendv** [comment]
@yyx990803 This is what I'm trying to do. It doesn't feel right.
![screenshot from 2016-02-04 12-15-01](https://cloud.githubusercontent.com/assets/1917947/12806466/0d4bb402-cb39-11e5-91bc-23c47d51e672.png)

**Comment by yyx990803** [comment]
@hiendv what are you doing inside `self.update()`?

**Comment by hiendv** [comment]
@yyx990803 Dispatch an event which fires a request to update the item. Whenever an attribute changes, the item is updated, that's my usecase.

**Comment by yyx990803** [comment]
And why do you need to exclude certain paths? That sounds odd if the `item` object is supposed to be persisted. If some piece of data should not be persisted, then it should not be on `item`.

Alternatively you can do this:

``` js
var self = this;
['name', 'content', 'order'].forEach(function (path) {
  self.$watch('item.' + path, self.update); // if `update` is a method it is auto-bound to the instance
});
```

**Comment by hiendv** [comment]
Actually, I would refactor instead of duplicating these lines. But my problem is properties which have their own watchers e.g relationships. These changes would be caught twice causing an unneeded update request on the original item whose *actual* attributes didn't change.
I understand that it's totally logic for this to happen but I just want to avoid that in the easiest way. Anyway, thank you for your patience. Happy Lunar New Year.

**Comment by simplesmiler** [comment]
@hiendv pardon the interruption, but it seems to me you are trying to reinvent computed properties.

**Comment by hiendv** [comment]
@simplesmiler Evan said the same thing so I guess that I did not read the documentation carefully enough.
