### ISSUE TITLE
v-show does not pass the element?

### ISSUE THREAD

**Issue by huglester** [vuejs/vue#2293]
Hello,

VueJS is really great. thanks for it!

Just came across the problem, maybe I am doing something wrong, but did not find any information on this in docs or google.
I have simple HTML markup:
```html
<div id="app-categories">
        <input type="text" name="name" v-model="filter" value="" autocomplete="off">
        <ul>
          <li v-show="filterItems()">Keyword</li>
          <li v-show="filterItems()">Car</li>
          <li v-show="filterItems()">Mouse</li>
          <li v-show="filterItems()">Computer</li>
          <li v-show="filterItems()">Full Name</li>
        </ul>
        <pre>
          {{ $data | json }}
        </pre>
    </div>
```

and js:
```js
new Vue({
        el: '#app-categories',
        data: {
            filter: ''
        },
        methods: {
            filterItems: function(e) {
                console.log(e);
            }
        }
    });
```

What I do try to achieve, is make input field to accept 'search query', and if the li>innerHTML does not contain needed string - I just make the <li> element invisible.

The problem is that console.log(e) does return `undefined`...

Maybe I am doing something wrong?

Thank you

**Comment by yyx990803** [comment]
It's not an event listener, so obviously there is no event to be passed. It's generally considered bad practice to be retrieving values from the DOM when you can just do it in JS. Here you can just do `filterItems('the string')`.

**Comment by Mat-Moo** [comment]
Think outside the dom, and harness the power of Vue and Filters :-
http://jsbin.com/diwowelase/edit?html,js,output

**Comment by huglester** [comment]
Thank. Understand now. I must 'load' those items using vue, so they strart working/filtering
