### ISSUE TITLE
$appendTo 是否可以更新 vm父子关系

### ISSUE THREAD

**Issue by rachardking** [vuejs/vue#2295]
$parent 
$children

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
