### ISSUE TITLE
v-on:click.self event not work

### ISSUE THREAD

**Issue by loyalove** [vuejs/vue#2296]
v-on:click.self event not work

**Comment by azamat-sharapov** [comment]
Provide reproduction.

**Comment by loyalove** [comment]
Can you speak Chinese

**Comment by loyalove** [comment]
`
<div class="list">
        <div class="head border-t">
            <span class="title">推荐</span>
        </div>
        <ul class="items border-t">
            <li class="item" v-on:click.self="addItem"><i class="fa fa-plus fa-2x"></i></li>
        </ul>
        <div class="clear"></div>
    </div>
`

`
var vm = new Vue({
                el:'body',
                data:{
                    user:{
                        name:'loyal',
                        age:25
                    },
                    count:0
                },
                methods:{
                    addItem:function(event){
                        var item = $(event.target).clone();
                        item.unbind().hide().html(++this.count);
                        $(event.target).before(item);
                        item.fadeIn();
                    }
               }
      });
`

**Comment by loyalove** [comment]
```html
<body>
        <div class="list">
        <div class="head border-t">
            <span class="title">推荐</span>
        </div>
        <ul class="items border-t">
            <li class="item" v-on:click.stop="addItem"><i class="fa fa-plus fa-2x"></i></li>
        </ul>
        <div class="clear"></div>
    </div>
</body>
```
```javascript
var vm = new Vue({
                el:'body',
                data:{
                    count:0
                },
                methods:{
                    addItem:function(event){
                        var item = $(event.target).clone();
                        item.unbind().hide().html(++this.count);
                        $(event.target).before(item);
                        item.fadeIn();
                    }
                }
            });
```

**Comment by xuanyan0x7c7** [comment]
v-on:click.self="addItem($event)"

**Comment by loyalove** [comment]
$event is required？

**Comment by paulpflug** [comment]
shouldn't be required:
http://vuejs.org/api/#v-on

**Comment by yyx990803** [comment]
Cannot reproduce. Your example is working as expected. Make sure you are using the latest version of Vue (`.self` is only supported in 1.0.16+). Reopen if you can provide an actual reproduction.

**Comment by iahu** [comment]
坑爹的 Vue
