### ISSUE TITLE
window. child objects return undefined when using NW.js

### ISSUE THREAD

**Issue by nicklaw5** [vuejs/vue#2297]
I've just begun using [NW.js ](https://github.com/nwjs/nw.js) alongside vue.js for a project. When attempting to declare vue via the node `require` method, I found three issues relating to the `navigator`, `document` and `DocumentFragment` objects, which I'm guessing relates specifically to NW.js but perhaps also other projects as well.

Each of the above object references in the **vue.common.js** file need to be prefixed with `window.`. For example:
* `window.navigator`
* `window.document`
* `window.DocumentFragment`

Failure to do so will result in an undefined error, like this:
`Uncaught ReferenceError: navigator is not defined`

As @Teevio mentioned in my [forum post](http://forum.vuejs.org/topic/1972/help-uncaught-referenceerror-navigator-is-not-defined/2), it would seem that NW.js only makes these variables available explicitly via the `window` object. This could be because NW.js provides it's own `Window` object, which is a wrapper of the DOM’s `window` object ([see here](http://docs.nwjs.io/en/v0.13.0-beta5/References/Window/)).

**Comment by yyx990803** [comment]
I don't think you need to use `window.document` in nw.js.
