### ISSUE TITLE
Currency filter shows negative numbers incorrectly

### ISSUE THREAD

**Issue by igidas** [vuejs/vue#2300]
Hey, thanks for an awesome work on VueJS!

According to  [this answer](http://ux.stackexchange.com/questions/1869/preferred-format-to-display-negative-currency-us-english/1875), currency filter shows negative numbers incorrectly.

Here is reproduction:
https://jsfiddle.net/n2bw2nau/3/

**Comment by yyx990803** [comment]
Thanks for reporting the issue. The filter now places the minus symbol first. The quote notation will require a custom filter, as that is a corporate-finance-specific use case.
