### ISSUE TITLE
Allow component prop type to be an array of accepted types

### ISSUE THREAD

**Issue by saul** [vuejs/vue#2337]
At the minute, prop types can only be custom/native constructors. It would be helpful if the type could be an array of custom/native constructors, and if the passed in prop value matches any of these functions, it would be deemed valid.

For example, a prop with name `value` that can accept either an `Array` or `Number` as its type:
```js
props: {
	value: {
		type: [Array, Number],
		default: 5 // or: default: [1, 2, 3]
	}
}
```

**Comment by ealves-pt** [comment]
@yyx990803 is this up for grabs? I want to give an hand. :smiley:

**Comment by yyx990803** [comment]
@ealves-pt sure thing! Just make sure to include tests in your PR

**Comment by ealves-pt** [comment]
Perfect. :+1:

**Comment by ealves-pt** [comment]
Should I update the documentation to reflect this changes?

**Comment by phanan** [comment]
@ealves-pt Sure, please do. 
@Everyone: Let's continue the discussion (if need be) in the PR. I'm closing this issue to keep the list clean.
