### ISSUE TITLE
Leave animation randomly makes leaving element flicker on IE11

### ISSUE THREAD

**Issue by sztrzask** [vuejs/vue#2338]
Keyword "randomly".

in transition code:
```
 /**
   * The "cleanup" phase of a leaving transition.
   */

  p$1.leaveDone = function () {
    this.left = true;
    this.cancel = this.pendingJsCb = null;
    this.op();
    removeClass(this.el, this.leaveClass);
    this.callHook('afterLeave');
    if (this.cb) this.cb();
    this.op = null;  
  };
```
The flicker I'm randomly experiencing is the element returning to normal state when leave class is removed, just before the element is removed from DOM.

Moving the removeClass(this.el....) to next tick seems to resolve the flickering.

**Comment by yyx990803** [comment]
`this.op()` is the line which actually removes the element, so the class should be removed **after** the element is removed. Not sure if this is a bug in IE11 or not. If possible please provide a repro.

**Comment by sztrzask** [comment]
I'l try to record it on video as it happens randomly and provide you a simplified repro on monday, but from what I saw I think its a bug on IE where after removing the class the layout refreshed for some reason before removing the element from DOM.

**Comment by sztrzask** [comment]
We've managed to capture the flicker on video happening on IE Mobile (IE11 Update for Windows Phone 8.1):
[20160215_165900.zip](https://github.com/vuejs/vue/files/132328/20160215_165900.zip)

Here's a simplified repro: http://codepen.io/sztrzask/pen/MKxZvO

It really does seem like IE bug.

Delaying the cleanup phase seems to work around it (with appropriate guards in case elements were removed).

**Comment by smolinari** [comment]
> It really does seem like IE bug.

No surprise there.

Scott

**Comment by yyx990803** [comment]
@sztrzask 

> Moving the removeClass(this.el....) to next tick seems to resolve the flickering.

Are you using Vue's nextTick or just a setTimeout?

**Comment by sztrzask** [comment]
Vue's nextTick with guard checking if element still exists in next tick.

**Comment by yyx990803** [comment]
@sztrzask any reason why the existence guard check is necessary? I'm just thinking whether adding a nextTick to leaveDone would make this work.

**Comment by sztrzask** [comment]
I thought that `this.cb();` removes the element from DOM and makes `this.el` null; thus if ` removeClass(this.el, this.leaveClass);` would be executed in the nextTick, it might throw an error because the first argument is null. I didn't check my reasoning though.

**Comment by sztrzask** [comment]
After a moment of consideration, I belive it might not be necessary :)

**Comment by yyx990803** [comment]
Ok, I found a simpler solution: add `animation-fill-mode: forwards;` to your transitioned element. This ensures the animation ending state stays even when the class is removed, and doesn't require Vue to change its behavior to cater to an IE bug :)

**Comment by sztrzask** [comment]
The proposed fix works partially. The flicker is less likely to appear, but it's still happening.

**Comment by kalvn** [comment]
The fix worked well on my side, thanks :)
