### ISSUE TITLE
problem with nested v-repeat directives.

### ISSUE THREAD

**Issue by twarogowski** [vuejs/vue#234]
Hi,

When I nest 2 v-repeat directives, inner directive contents is recreated on every model update. Apart form performance penalty, this results in loosing HTML input focus.

Take a look:

http://jsfiddle.net/twarogowski/E8KH6/

**Comment by lensgolda** [comment]
Have some code
```
<div v-repeat="hotel: hotels>
                <span v-show="hotel.starsCode" v-repeat="hotel.starsCode | int" ></span>
```
trying to use int filter on hotel.starsCode:
```
Vue.filter('int', function (val) {
    console.log(val);
    var n = parseInt(val, 10);
    isNaN(n) ? 0 : n;
})
```
console.log(val) outputs ["2"] ["5"] ... typeof object
so when i try parseInt this values, and get string value of hotel.starsCode = "not defined" - for example, it returns NaN, so i check this and return 0(zero)or int 1 to v-repeat, and get error
```
Uncaught TypeError: Cannot read property 'length' of undefined
```
Even if i return int 1, have the same problem.
why Vue.js haven't int filter or v-repeat can't get 0 value? How can i solve this? Can you help me please?
(sorry for my English)

**Comment by yyx990803** [comment]
@lensgolda you should be returning an Array in the filter.

**Comment by lensgolda** [comment]
oh, thanks!
