### ISSUE TITLE
Two-way filter on the fly

### ISSUE THREAD

**Issue by DenisAlliswell** [vuejs/vue#2341]
First of all, I really love Vuejs.

How one can do two-way filter for model updating on the fly. 
I mean, not after the input blur, but like on keypress.

Many thanks in advance for any help!

**Comment by smolinari** [comment]
This would be better off[ in the forum](http://forum.vuejs.org/). If it turns out it isn't possible, or there is a bug, you can then post a suggestion of issue here.

Scott

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by DenisAlliswell** [comment]
Hello, Evan!

I mean, no one knows that) I've already asked where I even could)
It seems like there's no possibility to do the two-way Filter updating on the fly (keypress) in Vue.

For sure, there's way to implement that functionality via 3rd part plugins (e.g. autoNumeric.js), but I'd like to use pure Vue. It's more convenient and, what is more, I guess Vue has enough power to do that kinda stuff) At least, I wish so.

This code works fine, but only on the input blur. Like with `lazy` attr on.

```javascript
Vue.filter('currencyDisplay', {
  // model -> view
  // formats the value when updating the input element.
  read: function(val) {
    return '$'+val.toFixed(2)
  },
  // view -> model
  // formats the value when writing to the data.
  write: function(val, oldVal) {
    var number = +val.replace(/[^\d.]/g, '')
    return isNaN(number) ? 0 : parseFloat(number.toFixed(2))
  }
})
```

Please, pay some time on this one.

Thank you.
