### ISSUE TITLE
Data adaptor support or magic=false

### ISSUE THREAD

**Issue by gejgalis** [vuejs/vue#2342]
Hi!

We are working on multiple products using VueJS, OpenLayers, Cesium and who knows what else in the future. In our application we need to share the same data between Vue and map engines. So we have 3 different libraries which have different observable models implementation.

We have written our ObservableModel abstarction which is synchronized with Vue, OpenLayers and Cesium. We encountered performance issue related to generate too much

**Comment by gejgalis** [comment]
... getters and setters. To avoid too much generation of get/set we need to have models with more painful API like: model.set('foo', 'fooValue').

Have you considered to implement data adaptors or magic: false flag like in RactiveJS? 

http://docs.ractivejs.org/latest/magic-mode

http://docs.ractivejs.org/latest/adaptors

**Comment by yyx990803** [comment]
By "too much", how many is that? And do all those properties have to be reactive? I have personally never seen the getter/setters becoming a perf bottleneck, so more details would help.

**Comment by gejgalis** [comment]
In worse scenario we have around 1000 items presented on both - map and DOM (in DOM we use paging to show as little as possible). Each item contains around 20 properties and few nested objects which gives us around 3000 objects. We have perf bottleneck only when objects are CREATED (perf tool points to Object.defineProperty as most intensive function) especially on IE9/10. You are right that most of properties are not reactive - only few of them are changing, but how can we define which properties shouldn't be wrapped by get/set ?

**Comment by yyx990803** [comment]
Hmm, maybe there could be a property whitelist/blacklist feature for special scenarios like this. Although there's another possible approach: do not make all data reactive upfront, keep them pristine on initial load, and only "feed" them into Vue instances when needed.

**Comment by smolinari** [comment]
Could you give us a short explanation on how the data feeding could work? :smile: 

Scott

**Comment by yyx990803** [comment]
@smolinari Vue only converts data to be reactive when it is "set" on a Vue instance:

``` js
var vm = new Vue({
  data: {
    items: []
  }
})

var items = [{a: 1}, {a: 2}] // still non-reactive

vm.items = items.filter(item => item.a > 1) // now only the second object becomes reactive
```

So the idea is, initialize the instance with an empty array, and keep the full data array unobserved. On pagination change, get a filtered copy of the items to display and set it on the instance (which causes Vue to convert them). This way objects are only converted as needed instead of a huge conversion cost upfront.

**Comment by smolinari** [comment]
Thanks for the explanation Evan @yyx990803. It makes perfect sense (especially for me, a novice JS programmer). I actually just reread the Reactivity in Depth, and now that makes a lot more sense too. 

Would you consider this another example to add to the docs, under Reactivity in Depth? If you do, I'd like to give it a go.

Scott

**Comment by pkawiak** [comment]
It is not only performance issue. It's more about how we approach MVVM architecture.

Please forgive me for this wall of text, but I'd like to describe our situation and the story behind this conversation.

Company we work for has a fairly large, highly customizable, suite of products that share common code. We strive to achieve consistency of the look and feel, promote code reuse and define clear architecture that will allow multiple teams to work effectively with minimum side effects. Our apps consist of multiple modules written using our own interpretation of [Patterns For Large-Scale JavaScript Application Architecture.](https://addyosmani.com/largescalejavascript/) 

Inside our modules we follow MVVM approach and we would like it to be consistent. We would like our developers to be able to switch between modules and feel comfortable with what they see.

As much as we **love** Vue, we would like to benefit from observable collections, computed properties, custom model events and more, without relying on Vue's presence.

Extracting observable model to a separate layer, independent of Vue, enables us to share the same paterns across modules. Some of those modules don't use Vue at all!

Our current solution is as folows:

We have ```ObservableModel```, ```ObservableCollection``` and ```ObservableMap``` classes, that support us with all the benefits of interactive models (computed properties, watching changes etc.). When such model enters Vue realm, we call it's ```toVue``` method which returns a proxy carrying out synchronization logic. When we change a prop on _our_ model, Vue model is updated. When a computed propery of _our_ model changes, Vue's equivalent is updated. This obviously works the other way too. As a result, our Vue instances don't have any computed properties, any watches etc. They only have simple methods emitting events that are handled outside.

This works really well but has a performance impact meaningful in visualising large data sets. Our ```toVue``` method returns an object which is later on augmented by Vue and observed by us to synchronize changes.

Do you think it would be feasible to define an API that is required by Vue to be able to _plug in_ to existing implementations of observable model? By default, when no _adapter_ is provided, Vue would augment plain object, exactly as of now. With _adapter_, no augmentation would be necessary, as Vue could use it to observe and update underlying model.

Do you see value in such approach or do you think it's too complicated?

**Comment by yyx990803** [comment]
So, as of 1.0.18, simply freezing an Object/Array with `Object.freeze` will let Vue skip observation for that object and its nested values. This should mitigate the perf concerns in places when replacing large but never-expected-to-change data structures.

Alternatively, you can feed in the data piecemeal like I suggested earlier.

I don't think we will look into adaptors any time soon - I can see it as a valid use case, but it's a rare one in practice, so I'm not sure if it's worth the effort given other priorities.
