### ISSUE TITLE
Else statement for v-for directive

### ISSUE THREAD

**Issue by bartlomieju** [vuejs/vue#2343]
First of all huge thanks Evan! Vue's great!

To the point: I am developing app that uses many lists. Those list are often filtered by user input. Before switching to Vue I used plain Django templates, and relied heavily on {% empty %} tag. 

Unfortunately there is no such directive in Vue core. In my opinion it would be incredibly awesome and handy to be able to write:
<template>

	<input v-model="q">	
	<ul>
		<li v-for="product in products | filterBy q in 'name' | sortBy sortKey sortOrder">
			{{ product.id }} - {{ product.name }}
		</li>
		<li v-for-else>
			There are no products matching your query
		</li>
	</ul>
</template>

Have you ever thought about implementing it? What's your opinion?

**Comment by yyx990803** [comment]
You can use a custom filter to "record" the length of the filtered result:

``` js
Vue.filter('recordLength', function (result, key) {
  this.$set(key, result.length)
})
```

``` html
<li v-for="product in products | filterBy q in 'name' | orderBy sortKey sortOrder | recordLength 'productCount'">
</li>
<li v-if="!productCount">
    There are no products matching your query
</li>
```

**Comment by bartlomieju** [comment]
Thanks for the answer! Yeah sure, I already used that a couple times. Why do you think it is not a good idea to implement?

**Comment by neitanod** [comment]
I second that!

**Comment by shadoWalker89** [comment]
@yyx990803 Shouldn't the recordLength filter return the result ?

I'm using vue 1.0.26 and if i don't return the result from the filter nothing appears on the screen.

**Comment by LinusBorg** [comment]
@shadoWalker89 indeed.

```js
Vue.filter('recordLength', function (result, key) {
  this.$set(key, result.length)
  return result
})
```

**Comment by joshtipton28** [comment]
How can you display the value of the number of results? I tried {{productCount}} or {{productCount.length}} but both displays nothing.

**Comment by GioLogist** [comment]
This answer doesn't seem to work anymore. Is there a new way of accomplishing this?

**Comment by salvisb** [comment]
@GioLogist did you find a solution?
