### ISSUE TITLE
Passing a function to custom directive..

### ISSUE THREAD

**Issue by socieboy** [vuejs/vue#2344]
Hi I don't know if this has been done. but there is a way to pass  a component function to a custom directive...
```
Vue.directive('custom', {

   params: ['function'],

})
```
and do something like that
```
div custom function="onCompleted",
````
And have defined the onCompleted function in the component.

**Comment by sirlancelot** [comment]
You would need to pass it like `<div :function="onCompleted">`

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
