### ISSUE TITLE
Error when evaluating expression with v-if and v-for

### ISSUE THREAD

**Issue by mightylal** [vuejs/vue#2347]
```
<div v-for="slot in card" class="panel panel-default">
<div class="panel-heading">{{ slot.name }}</div>
<div class="panel-body">
    <p v-for="wrestler in slot.wrestlers">
        {{ wrestler.team }}
        <p v-if="true">okay</p>
        {{ wrestler.team }}
    </p>
</div>
</div>
```

It throws a warning Error when evaluating expression "wrestler.team". The initial wrestler.team is shown and so is the word "okay", but the second wrestler.team throws that warning. Is this expected behavior?

**Comment by crswll** [comment]
Do you actually have a variable named `true`? Can't see that ending well.

**Comment by mightylal** [comment]
No, true is just true.

The problem and I'm not sure if this is by design, but passing a <p> within a v-for on a <p> tag will cause the error to be thrown. Simply changing the v-if to a <span> tag or any other non-<p> tag will not throw the error.

**Comment by hanai** [comment]
your template is incorrect

``` html
<div v-for="slot in card" class="panel panel-default">
    <div class="panel-heading">{{ slot.name }}</div>
    <div class="panel-body">
        <p v-for="wrestler in slot.wrestlers">
            {{ wrestler.team }}
            <p v-if="true">okay</p>
            {{ wrestler.team }}
        </p>
    </div>
```

the outer div is not enclosed

**Comment by mightylal** [comment]
No, I just forgot to copy that ending div tag over.

**Comment by crswll** [comment]
You can't have paragraph tags nested like that. It could be the browser just handling it funny.

**Comment by mightylal** [comment]
Really? I did not realize that. Thanks @crswll
