### ISSUE TITLE
Allow loading Vue in "no conflict" mode

### ISSUE THREAD

**Issue by dmitrijs** [vuejs/vue#2349]
Similar to jQuery:
```
var $j = jQuery.noConflict(true);
```

**Comment by yyx990803** [comment]
Just curious, what other library also uses a `Vue` global?

**Comment by roblav96** [comment]
lol

**Comment by dmitrijs** [comment]
@yyx990803 In my case - other version of Vue. I'm loading Vue on a number of websites, and although, none of them has ever used Vue yet - I'm optimistic - it might become much more popular in the future.

This feature would minimize any risk of overwriting older (or newer, or extended(!)) version of Vue, that is already being used on the website.

**Comment by katzgrau** [comment]
+1

**Comment by katzgrau** [comment]
I should elaborate. In my case, I use Vue because it's lightweight and it makes sense for a widget I'm building which will run on a lot of different sites. Those sites *probably* don't use Vue, but I'd rather avoid potential version conflicts if I could.

**Comment by sirlancelot** [comment]
I think if you're using a bundling mechanism like Webpack or Browserify, this isn't even an issue. Vue doesn't bind itself to `window` if it can just add itself to `module.exports`

**Comment by posva** [comment]
@sirlancelot that's exactly what I wanted to say :smile:

**Comment by katzgrau** [comment]
@sirlancelot I hadn't noticed that - I'm not in a place where I can use browserify et al, but simply defining module.exports before inclusion does the trick for me.

**Comment by yyx990803** [comment]
I think the best practice is: if you are expecting your code to run in an environment that you don't control, do not rely on window globals and do not expose window globals. Use a module bundler :)
