### ISSUE TITLE
Vueify in Gulp.

### ISSUE THREAD

**Issue by daphen** [vuejs/vue#2350]
Hey. I've started learning Vue and I'm loving it so far.
However, I have stumbled upon an issue. This might not be the suitable forum for this type of query and if not, excuse me and just remove my comment. 
I'm trying to get Vueify to work with Browserify in Gulp and I can't for the life of me understand what I'm doing wrong. It works fine without Vueify, but if I try to require in a .vue file, the script file in my source directory is outputted completely empty. If I comment out the require line, it works again. 
I'll attach the link to my code below so if anyone has got the time to have a look, that would be super helpful. Also, I tried both with gulp-browserify and with regular browserify and both of them gave the same result. 
Thanks in advance and great job with Vue. It truly is a great framework and is much easier to get into than both React and Angular.

(I'm guessing the problem is in my gulpfile.js, but since I don't know what is wrong, I can't say for sure.)

[https://github.com/daphen/vueifygulp](url)

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by daphen** [comment]
Hi, I posted on the forums as well but received no answer.
Sorry.

Regards, David.
