### ISSUE TITLE
尤大, 很喜欢您的vue,但是webpack用的不顺手,您能组织一个fis的基于es6的封装方案吗?

### ISSUE THREAD

**Issue by CheneyLiu** [vuejs/vue#2351]
目前有的fis封装方案是基于es5的,用文件夹分割组件的形式如下:
  components
    |--app
         |--app.css
         |--app.html
         |--app.js
   |--card
   ...
但是没有发现fis基于es6的方案

**Comment by xiaolongyuan** [comment]
http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87
