### ISSUE TITLE
如何通过v-bind:style动态生成背景图？

### ISSUE THREAD

**Issue by For-me** [vuejs/vue#2352]
在通过v-for出来子集之后，要生成当前节点的背景图，通过v-bind:style="{background:url(list.Cover)}"
无法正确便利出结果.
 [Vue warn]: Error when evaluating expression "{background:url(list.Cover)}". Turn on debug mode to see stack trace.
请尤大大解答下，谢谢

**Comment by hanai** [comment]
大致这样

v-bind:style="{background: 'url(' + list.Cover + ')'}"

**Comment by For-me** [comment]
@hanai 如果我这里的背景图是类似于"http://sss.xxxx"域下的图片。直接这样绑定是不是就是失败的？
现在我已经改成你说的那个样子，但是div中根本没行内样式引入

**Comment by For-me** [comment]
@hanai 代码如下：
`<template>
 <div class="card" v-bind:class="{'card-1':$index%4==1||$index%4==2,'card-top':$index == 2}" v-for="item in data" v-bind:style="{backgroundImage:item.Cover}">
 	<h3>Room<strong>{{item.Name}}</strong></h3>
 	<div class="card-mock"></div>
 	<div class="card-detail">
 		<span class="card-icon">
 			<img :src=item.Tenant.Avatar v-if="item.Tenant">
 			<img :src='' v-else>
 		</span>
 		<span class="card-des" v-if="item.Tenant">
 			<p>{{item.Tenant.Nickname}}{{index}}</p>
 			<p>{{item.Tenant.Age}}岁<i class="sex" v-bind:class="{'icon-man':item.Tenant.Gender == 0 ,'icon-woman':item.Tenant.Gender == 1}"></i></p>
 		</span>
 		<span class="card-des" v-else>
 			<p>优客君在等你哦</p>
 		</span>
 	</div>
 	<p v-if="item.Tenant">{{item.Tenant.Intro}}</p>
 	<p v-else>暂时还没租哦，快来占有它吧</p>
 </div>
</template>

<script>
	export default {
		props:['data'],
		data (){
			return{
				headBack:'background-image:url(/source/images/head-default.png'
			}
		},
		ready (){
			console.log(this.data);
		}
	
	}


</script>`

**Comment by For-me** [comment]
@hanai 代码如下：
<template>
 <div class="card" v-bind:class="{'card-1':$index%4==1||$index%4==2,'card-top':$index == 2}" v-for="item in data" v-bind:style="{backgroundImage:item.Cover}">
 	<h3>Room<strong>{{item.Name}}</strong></h3>
 	<div class="card-mock"></div>
 	<div class="card-detail">
 		<span class="card-icon">
 			<img :src=item.Tenant.Avatar v-if="item.Tenant">
 			<img :src='' v-else>
 		</span>
 		<span class="card-des" v-if="item.Tenant">
 			<p>{{item.Tenant.Nickname}}{{index}}</p>
 			<p>{{item.Tenant.Age}}岁<i class="sex" v-bind:class="{'icon-man':item.Tenant.Gender == 0 ,'icon-woman':item.Tenant.Gender == 1}"></i></p>
 		</span>
 		<span class="card-des" v-else>
 			<p>优客君在等你哦</p>
 		</span>
 	</div>
 	<p v-if="item.Tenant">{{item.Tenant.Intro}}</p>
 	<p v-else>暂时还没租哦，快来占有它吧</p>
 </div>
</template>

<script>
	export default {
		props:['data'],
		data (){
			return{
				headBack:'background-image:url(/source/images/head-default.png'
			}
		},
		ready (){
			console.log(this.data);
		}
	
	}


</script>

**Comment by For-me** [comment]
@hanai 代码如下：
`<template>
 <div class="card" v-bind:class="{'card-1':$index%4==1||$index%4==2,'card-top':$index == 2}" v-for="item in data" v-bind:style="{backgroundImage:item.Cover}">
 	<h3>Room<strong>{{item.Name}}</strong></h3>
 	<div class="card-mock"></div>
 	<div class="card-detail">
 		<span class="card-icon">
 			<img :src=item.Tenant.Avatar v-if="item.Tenant">
 			<img :src='' v-else>
 		</span>
 		<span class="card-des" v-if="item.Tenant">
 			<p>{{item.Tenant.Nickname}}{{index}}</p>
 			<p>{{item.Tenant.Age}}岁<i class="sex" v-bind:class="{'icon-man':item.Tenant.Gender == 0 ,'icon-woman':item.Tenant.Gender == 1}"></i></p>
 		</span>
 		<span class="card-des" v-else>
 			<p>优客君在等你哦</p>
 		</span>
 	</div>
 	<p v-if="item.Tenant">{{item.Tenant.Intro}}</p>
 	<p v-else>暂时还没租哦，快来占有它吧</p>
 </div>
</template>

<script>
	export default {
		props:['data'],
		data (){
			return{
				headBack:'background-image:url(/source/images/head-default.png'
			}
		},
		ready (){
			console.log(this.data);
		}
	
	}


</script>`

**Comment by For-me** [comment]
@hanai 代码如下：
<template>
 <div class="card" v-bind:class="{'card-1':$index%4==1||$index%4==2,'card-top':$index == 2}" v-for="item in data" v-bind:style="{backgroundImage:item.Cover}"> </div>
</template>

**Comment by yyx990803** [comment]
`'url(' + list.Cover + ')'`...

**Comment by For-me** [comment]
@yyx990803 尤大大，如果要在这里面用三元表达式，应该怎么处理呢？常规方法会抛异常。

**Comment by Jiiiiiin** [comment]
code：
div class="swiper-slide" v-for="slide in fields.slides">

                
                
                <div  v-bind:style="background-image: url(slide.img);"></div>
err msg：

vue.js?bust=1480478486341:2643 [Vue warn]: failed to compile template:

<div id="app" xmlns:v-on="http://www.w3.org/1999/xhtml" xmlns:v-bind="http://www.w3.org/1999/xhtml">

    <main-header></main-header>

    
    <div class="swiper-container first-content" v-show="condition.slideListLoaded">
        <div class="swiper-wrapper">
            <div class="swiper-slide" v-for="slide in fields.slides">

                
                
                <div v-bind:style="background-image: url(slide.img);"></div>

**Comment by Jiiiiiin** [comment]
通过img标签直接绑定图片是可以的，但是绑定成bi就失败了。

**Comment by Jiiiiiin** [comment]
<div  :style="{backgroundImage: 'url(' + slide.img + ')'}"></div>  这样成功了 = =。。。。

**Comment by leafiy** [comment]
@Jiiiiiin 
:style="background-image: 'url(' + slide.img + ')';"

**Comment by Lawrence51** [comment]
如果这种写法，后面再添加样式的话，会报错呢，写法：
:style="{background: 'url(' + techContain.bgSrc + ')',backgroundSize :100% }"

**Comment by chensiun** [comment]
:style="`background-image: url(${list.Cover})`"

**Comment by dingguoqing513** [comment]
绑定background:linear-gradient（xxxxx）呢

**Comment by JustDoIt521** [comment]
:style="{backgroundImage:`url(${gift.reward_pic})`, color: 'red'}"
如果多个属性的话 这样写

**Comment by vidis01** [comment]
What it is?


2019-10-30, tr, 14:16 JustDoIt521 <notifications@github.com> rašė:
