### ISSUE TITLE
preventDefault is called before the v-on handler

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#2354]
[on.js#L46L51](https://github.com/vuejs/vue/blob/5c3f0b56a9cc9bc23d398108716b89c4e1f97b86/src/directives/public/on.js#L46-L51)
```js
function preventFilter (handler) {
  return function preventHandler (e) {
    e.preventDefault()
    return handler.call(this, e)
  }
}
```
is there a specific reason, that `handler.call(this, e)` is after `e.preventDefault()`?

In this case I can't check in the handler, if it was prevented somewhere else already.

**Comment by young-steveo** [comment]
This filter is only applied if the directive uses the `.prevent` modifier.  However, you could always check [Event.defaultPrevented](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented)

**Comment by paulpflug** [comment]
Say I have 2 elements overlapping and I click on them. Both have `.prevent` modifier, then I can't sort out which one got the click first.
Because `Event.defaultPrevented` will be true in both calls.

I think it makes more sense to switch `e.preventDefault()` with `handler.call(this, e)`. Then `Event.defaultPrevented` would be false in the first and true in the second call.

**Comment by young-steveo** [comment]
[Event.target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) will tell you which DOM node dispatched the event.

**Comment by paulpflug** [comment]
Say I have 3 elements overlapping and I click on them.1. is on top without `prevent`. 2 and 3 have `.prevent` modifier, then I can't sort which got the event second.

**Comment by young-steveo** [comment]
@paulpflug Not that I'm opposed to your change suggestion, but the order of the handlers in your hypothetical third scenario shouldn't matter.  Why would one care which element prevented default? The event will still propagate to all of the handlers.

I guess I mean to say, I'm curious about your problem domain.

**Comment by paulpflug** [comment]
I read this [article](https://css-tricks.com/dangers-stopping-event-propagation/)

And I just belief 
```js
if (event.defaultPrevented) return; // is event already consumed
// do the stuff
event.preventDefault() // mark the event as consumed if needed
```
is a good way for event management

but it obviously doesn't work the other way around
```js
event.preventDefault()
if (event.defaultPrevented) return;
// will never be done 
```

this issue isn't very important as I simply don't use the `.prevent` modifier and do it manually in the code instead

**Comment by yyx990803** [comment]
I'll close this since it doesn't seem to need a fix.
