### ISSUE TITLE
Transitionend does not recognize multiple transitions

### ISSUE THREAD

**Issue by bennyschudel** [vuejs/vue#2355]
Hi there

http://jsbin.com/ragifepexo/1/edit?html,css,output

Not sure if this is on purpose or not.

Best wishes
Ben

**Comment by yyx990803** [comment]
The transition is considered finished on the first `transitionend` event fired, because Vue cannot predict how many there will be...

If you need to transition multiple properties with complex timing, use CSS animations instead.

**Comment by bennyschudel** [comment]
Wow, that was fast! Thanks a lot.
