### ISSUE TITLE
Problem with computed property inside v-attr

### ISSUE THREAD

**Issue by mereskin-zz** [vuejs/vue#236]
Example markup:

```
<img v-attr="src: src" />
...
computed: {
  src: function(){
    return 'http://cdn.path/' + this.imageId;
  }
}
```

Once imageId is changed img's src is not getting updated. Works again if the dependent property is included in markup explicitly:

```
<img v-attr="src: src" /> {{ imageId }}
```

**Comment by ThomasRalee** [comment]
Hi
I am kind of stuck here, can someone hep me out? 

<img v-repeat="images | filterBy '1' in 'profile'" v-attr="src:src"/>
...
computed: {
	  src: function () {
	    return 'img/'+ this.imagePath;
	  }    
},
...

this.imagePath seems to return undefined. 

Much appreciated.

Thanks in advanced!
