### ISSUE TITLE
Collection API for VueJS and v-for

### ISSUE THREAD

**Issue by diverted247** [vuejs/vue#2362]
First.. v-for is very powerful but I feel the string based api is limiting, not runtime malleable, and not extensible. There are many additional data features ( paging, stop/start, lazy loading of data, events ) that would be ideally exposed in a list/collection api.

Today:
Example: http://codepen.io/__ted__/pen/LGvrMN
```html
<listitem v-for="location in locations | filterBy filter in 'state' 'city' | limitBy 10" track-by="city" :location="location" :filter="filter"></listitem>
```

Rather than refining collections in a template, it would be better to create a collection api within the viewmodel.

```javascript
var app = new Vue({
  el: '#app',
  data: {
    filter: "",
    locationsRaw: []
  },
  collections:{
      locations: Vue.collection( this.locationsRaw ).track( 'city' ).filter( this.filter , 'state' , 'city' ).limit( 10 )
  }
})
```

template:
```html
<listitem v-for="location in locations" :location="location" :filter="filter"></listitem>
```

Creates a list and returns itself ( chain-able to make viewmodel creation simpler )
```javascript
'locations': Vue.collection( datasource )
```

track by features
```javascript
.track( id )
```

filter by features
```javascript
.filter( filter:string, value1 , value2, ...)
```

limit by features
```javascript
.limit( count )
```

order by features
```javascript
.order( 'name' , -1 )
```

As these are not in the template, they should be malleable at runtime...

remove filters
```javascript
app.locations.clearFilters()
```

add filter to results where population > 10000
```javascript
app.locations.filter( 'population' , 10000 , 1 )
```

clear limit
```javascript
app.locations.clearLimits()
```

set limit to 100
```javascript
app.locations.limit(100)
```

These can also be done in 1 go given chain-able api:
```javascript
app.locations.clearLimits().limit(100)
```

As with all APIS in vue, it should be extensible so you can add new filters to the collection API.

```javascript
Vue.collectionFilter( 'name' , function );
```

Initially it should be limited to fully expose the existing list api and the ability to add extensions to it.

If the existing internal data API were exposed, it would be possible to add features like:

stop and start DOM updating
```javascript
app.locations.stop()
// expensive data manipulation task
app.locations.start()
```

If the above were possible, you could build lazy loading, and many other data manipulation layers into Vue without exhausting the existing string v-for api. I feel this gives Vue the foundation for a larger data manipulation api but does not cross the line into framework territory.

Respectfully,

Ted :)

**Comment by yyx990803** [comment]
Isn't this achievable with a computed property?

**Comment by diverted247** [comment]
You could generate the v-for string in a computed property but you would still be limited to the string based API in features. I would like to see the existing v-for internals exposed as an extensible collections API.

You could provide an extension mechanism for the string v-for API such that "| command arg arg" maps to:

Vue.collection( command, function( arg , arg ){} )

That feels like there is value in making the v-for string format extensible at a min.

**Comment by ppq1991** [comment]
:+1:

**Comment by yyx990803** [comment]
What I mean is this:

``` js
var filterBy = Vue.filter('filterBy')

// ... in component definition
computed: {
  filteredLocations () {
    return filterBy(this.locations, this.filter, 'state', 'city').slice(0, 10)
  }
}
```

You do have the full power of JavaScript - you are also not limited to the built in filters: you can write whatever filtering function you want.

**Comment by diverted247** [comment]
Ok... well actually
Maybe wow is a better response.

My paradigm error was limiting "computed" use to primitives, I really never thought about using them with arrays / objects. 

My mental model of the reactive parts of vue is a spreadsheet.
data --> raw data values entered into a cell
computed --> calculated values that depend on other cells

The problem with the spreadsheet paradigm is that 'cells' rarely contain complex data types.

So...
1. v-for string is just an expression with "|" delimited calls to builtin filters. So it is extensible by adding filters via Vue.filter( name , function )

2. computed properties can return complex types and results are cached until any dependent values change. You can create new filters to manipulate arrays/objects and use full js as needed. See http://vuejs.org/guide/reactivity.html#Inside_Computed_Properties

Closed!

Thanks Evan. Elegant
