### ISSUE TITLE
$index in v-for changed everytime with filterBy 

### ISSUE THREAD

**Issue by AnthemiusGuo** [vuejs/vue#2363]
when I need do something in v-for block for onclick to do something, I need transfer the "real" index of the data and use this data to do ajax post.
but the $index changed because filterBy changed. and same for orderBy.

我需要在v-for的内容中使用$index作为下标在点击事件中的参数, 从而直接引用到原始数据中的值用于ajax post.
但是由于filterBy 和OrderBy的作用, 我在v-for中没有任何办法拿到该条目的原始数据下标, 目前只能把原始id存在内容字段中, 然后用遍历数组找到对应id的数据来提交的方法实现需求,这样无疑是低效的.

建议增加一个$originalIndex之类的变量, 用于标记数据的原始在数组中的index.

**Comment by simplesmiler** [comment]
Chances are, you will use this index to retrieve the item from the original array. In that case you might as well just pass the item itself instead of the index.
After that, if you still need the index, you can use `items.indexOf(item)`.

**Comment by yyx990803** [comment]
`$index` is used for visual display only. As @simplesmiler suggested, if you need the original item, just pass the item directly instead of `$index`.
