### ISSUE TITLE
ES6 template string

### ISSUE THREAD

**Issue by yukulele** [vuejs/vue#2364]
Vue.js don't support es6 template string

```html
<div :style="{template:`rotate(${angle}deg)`}">
```

example:
http://codepen.io/yukulele/pen/KVLKoO

**Comment by posva** [comment]
I don't know if this can be easily implemented but, why should vue support an es6 feature, knowing that it isn't yet supported on most mobile devices (http://kangax.github.io/compat-table/es6/#test-template_strings)?

**Comment by yyx990803** [comment]
Note the fix only handles expression getter generation - it would still only work in Browsers that support template strings natively.

**Comment by yukulele** [comment]
thank you!

It works but only support one placeholder

it works for my first exemple,
```html
<div :style="{transform:`rotate(${angle}deg)`}">
```
but not this one
```html
<div :style="{transform:`translate(${x}px, ${y}px)`}">
```

**Comment by jankjn** [comment]
@yukulele looks 2.0 fix this, 1.0 still not

**Comment by yukulele** [comment]
It works !
http://codepen.io/yukulele/pen/KVLKoO

thank you !

**Comment by booxood** [comment]
Mark...

**Comment by jingsam** [comment]
We can not use expressions with ES6 syntax in templates unless browsers support it, for the reason that babel can not extract out these expressions and transform them into ES5. 

As I know, in vue 2.0, we can precompile templates into rendering functions in the backend. So, I want to know if it is possible to use babel to transform ES6 expressions into ES5? How do you think about it? @yyx990803 @posva

**Comment by jingsam** [comment]
I made a simple test with Vue 2.0. I noticed that babel can properly transform ES6 expressions into ES5. It's great and one more benefits to use Vue 2.0 instead of Vue 1.0. Sorry to disturb.

**Comment by gaby64** [comment]
filters dont work inside an es6 template

<a :href="`/url/${test | myfilter}`">

**Comment by posva** [comment]
@gaby64 filters can only be used at the end of the expression: https://vuejs.org/v2/guide/filters.html

Locking this very old thread
