### ISSUE TITLE
Component only events

### ISSUE THREAD

**Issue by rhyzx** [vuejs/vue#2367]
eg.

```html
<foo @click="do"></foo>
```

`do` will attach on `<foo>`'s root DOM and its' internal component event system(like `vm.$emit()`), there are some disadvantages in this approach:

1. It's confusing in my opinion.
2. DOM event may conflict with Component event(such as being called twice).
3. If we want avoid 2, we will struggle with the naming of this event.

I suggest providing some way to bind component only events, such as:

1. `@click.component-only`
2. Treat all events on component as component only events, if we need DOM events, just bind on its' parent DOM:

    ```html
    <div @click="domClick">
      <foo @click="componentEmitClick"></foo>
    </div>
    ```

**Comment by yyx990803** [comment]
Since this is a breaking change, this will have to go in a major release. Closing for now and keeping it in the breaking changes backlog.
