### ISSUE TITLE
router-view used in transition will affect subassembly transtion animation execution (micro-channel mobile terminals)

### ISSUE THREAD

**Issue by For-me** [vuejs/vue#2368]
hello.youdada!
When I use the router-view when using a transition animation transtion, but this movie will block subassembly executed animation, it will be Caton. Able to answer this question?
Code like this
`<template>
	<router-view class="view" transition="test" transition-mode="out-in" keep-alive></router-view>
</template>.view {
  transition: all .5s ease;
}`
and child components
`<div id="commentBox" class="commentBox" v-show="isShow" transition="expand"></div>.commentBox{
		position:absolute;
		top:0;
		left:0;
		bottom:0;
		width:100%;
		transform-origin:90% 90%;
		z-index: 3;
		opacity: 1;
		transform: scale(1) translateZ(0);
	}
	.expand-transition{
				transition: all .5s ease;
           }
           .expand-enter{
						 opacity: 0;
						 transform:scale(0) translateZ(0);
           }
           .expand-leave{
						 opacity: 0;
						 transform:scale(0) translateZ(0);
           }`

**Comment by yyx990803** [comment]
请用中文在论坛提问吧... 并且请好好格式化代码。
