### ISSUE TITLE
vue 1.0.16 data binding not work in tbody (by binding DOM id)

### ISSUE THREAD

**Issue by liupangzi** [vuejs/vue#2369]
### Vue.js version
1.0.16

### Reproduction Link
[JSFiddle](https://jsfiddle.net/liupangzi/2bog4et7/)

### Steps to reproduce
`<div id="app">` works fine
`<tbody id="fml">` fails

### What is Expected?
as documented

### What is actually happening?
see jsfiddle

i figured out a way working around, but i'm not sure if  usage `<tbody id="fml">` is correct.

thx.

**Comment by angelnuernberg** [comment]
Hi, 
I am trying out vue.js and have found your issue and have just read your code in jsfiddle. 
It works for me right when I include the tags tr and td inside tbody, like this: 

```
 <table >
        <tbody id="fml">
            <tr>
            <td>
            <p>{{ message }}</p>
            <input v-model="message">
            <tr>
            <td>
        </tbody>
    </table>
```
It also works fine when including the id inside the table tag. 

Does this solve your issue? When not, could you please share your workaround? 
Best Regards

**Comment by hanai** [comment]
maybe you can look this https://github.com/vuejs/vue/issues/1780

**Comment by yyx990803** [comment]
Your markup is invalid. Table elememts have strict rules on what can appear inside them.

**Comment by liupangzi** [comment]
@angelnuernberg  thx, i've figured this out by putting `id="fml"` in `<div>` wrapping `<table>`, like:

`<div id="fml">
    <table>
    ......
    </table>
</div>`

i think your solution may also work(i'll try later), thanks.

@hanai thanks. i'm new to vuejs today and i tried to search tbody in the issues, but i failed.

@yyx990803 thanks yyx. i did not find the _strict rules_ in our [vuejs manual](http://cn.vuejs.org/guide/), maybe we can add them in the manual? :-P

**Comment by yyx990803** [comment]
@liupangzi that's just how HTML works, not really about Vue... https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
