### ISSUE TITLE
Bind an element's CSS value, which is outside our control, to a component's data?

### ISSUE THREAD

**Issue by groovy9** [vuejs/vue#2377]
In the course of writing a datagrid component with Vue and Semantic UI, I found myself wishing for the ability to bind, for example:

jQuery(this.$el).parent().css('display') --> data.parentVisible

such that I could then:

  watch: {
     'parentVisible': function(new, old) {
        // stuff to do when parent becomes visible again
        // such as by clicking on the tab we live in
     }
  }

To be clear, I'm talking about CSS properties that another entity (Semantic UI in this case) is controlling.

Is this possible today?  Feasible to implement?

**Comment by groovy9** [comment]
Also, the obvious question is why not just put a click handler on the tab, but then the click handler fires before the contents of the tab are actually toggled visible by Semantic UI.  I have a functional workaround, but it's inelegant.

**Comment by prog-rajkamal** [comment]
have you tried vuejs [$broadcast](http://vuejs.org/guide/components.html#Custom_Events])?

by this mechanism,
the parent, on class change, will $broadcast a **custom event** to all its children. and
the child will **listen** to that event and act accordingly.

**Comment by groovy9** [comment]
The parent isn't controlling the CSS.  A 3rd-party CSS/JS UI framework is.

**Comment by simplesmiler** [comment]
@groovy9 you will have to rely on the UI framework to emit event or execute a callback.
In case of Semantic UI tabs that would be [Modules > Tab > Setting](http://semantic-ui.com/modules/tab.html#/settings), section "Callbacks".

**Comment by groovy9** [comment]
You know, I spent 10 minutes searching through their online docs looking for events and came up empty.  I'm apparently blind to that "settings" tab. You are my hero.

**Comment by yyx990803** [comment]
Closing as this is a question.
