### ISSUE TITLE
Interpolate content inside elementDirective

### ISSUE THREAD

**Issue by gejgalis** [vuejs/vue#2378]
Hello,

I'm trying to implement an `elementDirective` which resolves classes based on props values and some more complicated logic:

    <my-label type="small" modifier="action" theme="inherit">Label text with {{expressions}}</my-label>

As a result there should be:

    <my-label class="label-small-action-dark">Label text with expressionsResult</my-label>

I don't want to use component - it is too heavy for simple thing like this. Inline directive doesn't look sexy (IMO) either:

    <span v-label="{type: 'small', modifier: 'action', theme: 'inherit'}">Label text with {{expression}}</span>

I registered `my-label` elementDirective which works well for me, but unfortunately `{{expression}}` is not interpolated by default. I made a workaround using:

 1. Parse `this.el.innerHTML` using `import {parseText} from "vue/src/parsers/text"`
 2. `this._scope.$watch` to watch parsed tokens
 3. `this._scope.$interpolate` to interpolate template every time tokens were changed

Is other way to achieve my goal with `elementDirective`? If not - is there a chance `this._scope` became supported as `this.scope` inside directive in future? Maybe `interpolateContent: true` flag would be nice feature in elementDirective?

**Comment by simplesmiler** [comment]
Normal directives can have params: http://vuejs.org/guide/custom-directive.html#params

**Comment by gejgalis** [comment]
@simplesmiler Params work well for me either in elementDirective. I have trouble with inner content interpolation.

**Comment by simplesmiler** [comment]
I meant the following:
``` js
<span v-label type="small" modifier="action" theme="inherit">Label text with {{expressions}}</span>
```

**Comment by gejgalis** [comment]
@simplesmiler Now I see. I think it is good enough for us. Thank you!
