### ISSUE TITLE
$broadcast doesn't trigger a component's event

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue#2381]
Not a huge issue, and maybe there's a really good reason for this behaviour, but $broadcast doesn't get handled by the component that invokes it, while $dispatch does.

This means that for global events (like my top level App broadcasting an event that the App itself needs to act on, as well as some children components), I have to invoke the event manually as well, in order to get the App to act on it.

It would be nicer if the component itself would process the $broadcast like it does with $dispatch.

### Vue.js version
1.0.16

### Reproduction Link
http://jsfiddle.net/Phunky/f499tr15/

### Steps to reproduce
N/A

### What is Expected?
The component itself should catch the broadcast, similar to how a component catches a $dispatch

### What is actually happening?
The component ignores the $broadcast and needs to be triggered manually.

**Comment by vuchl** [comment]
From [here](http://vuejs.org/guide/components.html#Custom_Events):

> * Trigger events on self using $emit();
> * Dispatch an event that propagates upward along the parent chain using $dispatch();
> * Broadcast an event that propagates downward to all descendants using $broadcast().

To me the strange behavior is actually that the component is getting the `$dispatch` event.

But you can work around that with
```javascript
triggerEvent: function () {
    this.$dispatch('parentevent');
    this.$emit('selfevent');
}
```
or just calling the code inside the self event.

**Comment by TheDutchCoder** [comment]
I still believe $broadcast should behave like $dispatch, where it will also trigger an event on itself, because I might have global events that I want to fire off that are both caught by the component itself, as well as its child components.

Sure I can emit it manually, but that's my point: it's extra work that doesn't need to happen.

**Comment by yyx990803** [comment]
Yeah, this makes sense. Although introducing this at the moment would be a breaking change. Or maybe this could be considered a "fix"...

**Comment by TheDutchCoder** [comment]
Yeah I understand it would break a lot of code out there, which is unfortunate :/

Not sure what to recommend, but I'm assuming this would be part of a major release because of the implications? You probably don't want people to upgrade their minor version and then having their code break.

Thanks for looking into it though!

**Comment by yyx990803** [comment]
Yeah, I'm going to close this for now, since there is a simple workaround and changing it may cause breakage. We'll probably ship this when we have enough breaking changes queued up for a major release.

**Comment by TheDutchCoder** [comment]
That works for me, thanks!
