### ISSUE TITLE
Feature : v-show modifier for toggling visibility

### ISSUE THREAD

**Issue by weotch** [vuejs/vue#2382]
It would be nice to be able to do:

```html
<div v-show.visible="bool"></div>
```

... to toggle between `visibility:hidden` and `visibility:visible`. 

My use case is an element with a transition.  When the element transitions out, I'd prefer for the space it took up to not collapse.

**Comment by vuchl** [comment]
You could create a [custom directive](http://vuejs.org/guide/custom-directive.html) for that and use the [instance properties](http://vuejs.org/guide/custom-directive.html#Directive_Instance_Properties) (this.modifiers) to get the `v-directive.modifier`.

The only thing i can not really make out right now is if you can override the `v-show`directive.

**Comment by simplesmiler** [comment]
@weotch is `opacity: 0;` different to `visibility: hidden;` for your use case?

**Comment by yyx990803** [comment]
It's probably better to just create your custom directive like `v-visible`. Unfortunately the internal transition API is not exposed at the moment, but it will be in the next release and you will be able to achieve what you want using `Vue.transition.applyTransition()`.

**Comment by weotch** [comment]
@vuchl Thanks for the input, but I don't believe that solution would trigger transitions like normal `v-show` does.

@simplesmiler no, those would be equivalent for my use case.

@yyx990803 I don't think a custom directive would work because I wouldn't be able to communicate to the transition system to do an enter / leave.  But cool to know about that new API, thanks!

**Comment by yyx990803** [comment]
@weotch if changing the opacity is what you want, then you can do it with a simple class toggle with CSS transitions instead of using `v-show`.

**Comment by azamat-sharapov** [comment]
> Unfortunately the internal transition API is not exposed at the moment

Ha! this got me not long ago, but there is solution: `var apply = Vue.directive('show').apply`

**Comment by canamo06** [comment]
@yyx990803 is there API of transitions in the new version? because I want to trigger the transition in my component or with a custom directive.

 I'm doing some calculations with the offsetHeight, so I need to use 'visibility' instead of 'display'(v-show)

**Comment by bennyschudel** [comment]
how does this work in 2.0?

**Comment by noudadrichem** [comment]
I had the same prob, here is the fix I found. Custom directive in the form of a Node module:
https://www.npmjs.com/package/vue-visible

**Comment by m4heshd** [comment]
@noudadrichem not a solution at all since it doesn't trigger Vue transitions. It's simply setting `visibility` to `hidden` conditionality. Can easily be done with a class or style binding without needing any external dependencies.

```html
<div :class="{'hidden': myCondition}"> SOME CONTENT </div>
```

**Comment by noudadrichem** [comment]
> @noudadrichem not a solution at all since it doesn't trigger Vue transitions. It's simply setting `visibility` to `hidden` conditionality. Can easily be done with a class or style binding without needing any external dependencies.
> 
> 
> 
> ```html
> 
> <div :class="{'hidden': myCondition}"> SOME CONTENT </div>
> 
> ```
> 
> ```css
> 
> .hidden {
> 
>   visibility: hidden;
> 
> }
> 
> ```

The module does the same thing. And this is 3 years ago? 😂

**Comment by m4heshd** [comment]
> The module does the same thing. And this is 3 years ago? 😂

I know. But the question is related to transitions. So I thought I'd mention that before people go ahead and waste their time with testing.

**Comment by noudadrichem** [comment]
> because this still is an issue on Vue as far as I know.
But it's not an issue, see the comment of @yyx990803 about creating a directive yourself.

**Comment by m4heshd** [comment]
> see the comment of @yyx990803 about creating a directive yourself

I've seen that but still not possible to trigger a Vue transition manually. We have to write the whole switching functionality ourselves. Anyways, I wrote my own stuff and got it to behave the way I want. Still would be nice to have more control over Vue transitions because it's such a nice feature.
