### ISSUE TITLE
watch of component not triggered  

### ISSUE THREAD

**Issue by zyf0330** [vuejs/vue#2383]
### Vue.js version
1.0.13

### Reproduction Link

https://jsbin.com/vasime/edit?html,js,console,output
### Steps to reproduce
run. 
### What is actually happening?
you will find that dynamic-bind-value doesn't trigger watch of component. I think it is not acceptable

**Comment by yyx990803** [comment]
Your jsbin seems to be working as intended.

**Comment by zyf0330** [comment]
If I don't understand you wrongly, what I mean is I think that situation is not acceptable.
Why dynamic-bind-prop not trigger watch in component?

**Comment by yyx990803** [comment]
The jsbin **is** triggering the watcher in the component.

**Comment by zyf0330** [comment]
@yyx990803 that is because I write 

> vm.arr = [1,2,3,4];

**Comment by yyx990803** [comment]
Are you expecting the watcher to fire on component initialization? If that's the case, your expectation is wrong. Watchers only fire when an existing value has changed, so it is working as intended.

**Comment by zyf0330** [comment]
@yyx990803 but, the value is set by prop-bind.
Ok, could you tell me a good method to handle this situation?
I want to do something related to bind-prop in component when it is updated.

**Comment by yyx990803** [comment]
Your understanding of how props work is a bit off. If you need to do
something with a prop on component init, just do it in the component's
lifecycle hooks.

**Comment by zyf0330** [comment]
What I want to do is related to prop, so I can't do it with life cycle hook.

On Wed, Feb 24, 2016, 12:08 Evan You <notifications@github.com> wrote:

> Your understanding of how props work is a bit off. If you need to do
> something with a prop on component init, just do it in the component's
> lifecycle hooks.
> On Tue, Feb 23, 2016 at 11:04 PM 追随 <notifications@github.com> wrote:
>
> > @yyx990803 <https://github.com/yyx990803> but, the value is set by
> > prop-bind.
> > Ok, could you tell me a good method to handle this situation?
> > I want to do something related to bind-prop in component when it is
> > updated.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vuejs/vue/issues/2383#issuecomment-188053749>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vuejs/vue/issues/2383#issuecomment-188054970>.
>
-- 

追随

**Comment by zyf0330** [comment]
And what I do is at when prop is set or update.

On Wed, Feb 24, 2016, 12:20 yf z <zyf034100@gmail.com> wrote:

> What I want to do is related to prop, so I can't do it with life cycle
> hook.
>
> On Wed, Feb 24, 2016, 12:08 Evan You <notifications@github.com> wrote:
>
>> Your understanding of how props work is a bit off. If you need to do
>> something with a prop on component init, just do it in the component's
>> lifecycle hooks.
>> On Tue, Feb 23, 2016 at 11:04 PM 追随 <notifications@github.com> wrote:
>>
>> > @yyx990803 <https://github.com/yyx990803> but, the value is set by
>> > prop-bind.
>> > Ok, could you tell me a good method to handle this situation?
>> > I want to do something related to bind-prop in component when it is
>> > updated.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/vuejs/vue/issues/2383#issuecomment-188053749>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vuejs/vue/issues/2383#issuecomment-188054970>.
>>
> --
>
> 追随
>
-- 

追随

**Comment by zyf0330** [comment]
OK, I can only realize by another way. In the ready hook, I handle prop
value once. And set a watch for it to handle it when be set.

On Wed, Feb 24, 2016, 12:22 yf z <zyf034100@gmail.com> wrote:

> And what I do is at when prop is set or update.
>
> On Wed, Feb 24, 2016, 12:20 yf z <zyf034100@gmail.com> wrote:
>
>> What I want to do is related to prop, so I can't do it with life cycle
>> hook.
>>
>> On Wed, Feb 24, 2016, 12:08 Evan You <notifications@github.com> wrote:
>>
>>> Your understanding of how props work is a bit off. If you need to do
>>> something with a prop on component init, just do it in the component's
>>> lifecycle hooks.
>>> On Tue, Feb 23, 2016 at 11:04 PM 追随 <notifications@github.com> wrote:
>>>
>>> > @yyx990803 <https://github.com/yyx990803> but, the value is set by
>>> > prop-bind.
>>> > Ok, could you tell me a good method to handle this situation?
>>> > I want to do something related to bind-prop in component when it is
>>> > updated.
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <https://github.com/vuejs/vue/issues/2383#issuecomment-188053749>.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/vuejs/vue/issues/2383#issuecomment-188054970>.
>>>
>> --
>>
>> 追随
>>
> --
>
> 追随
>
-- 

追随
