### ISSUE TITLE
observer.walk中是否遗漏了过滤关键字

### ISSUE THREAD

**Issue by gebilaoxiong** [vuejs/vue#2384]
### Vue.js version
1.0.16

### Reproduction Link

[observer.walk](https://github.com/vuejs/vue/blob/dev/src/observer/index.js#L52)
### What is Expected?

我记得在以前的版本里这里是过滤了以$和_开头的属性，在新版本是去掉这个了吗？

### What is actually happening?

**Comment by yyx990803** [comment]
是的，去掉了。
