### ISSUE TITLE
Custom directive's deep doesn't work when add key to a json object

### ISSUE THREAD

**Issue by brucesong08** [vuejs/vue#2385]
I want to custom a directive with a json Object. When I add new key to the json object, the directive doesn't work.
Example:

  props: {
    node: {
       attr:{}
    }
  },

<div v-updAttr="node.attr"/>

directives:{
   updAttr:{
     deep: true,
     update:function{
      /******do something********/
      }
  }
////add a key it doesn't work
node.attr['a'] = "test";

////if clone a new obj, it works
var attr = jQuery.extend(true, {}, node.attr);
attr["a"] = "test";
node.attr = attr;

**Comment by azamat-sharapov** [comment]
http://vuejs.org/guide/reactivity.html#Change_Detection_Caveats

**Comment by brucesong08** [comment]
Thank you for your comment. 
But I get the error:

Uncaught TypeError: exp.trim is not a function
parseExpression @ vue.common.js:2923
Vue.$set @ vue.common.js:8569

**Comment by azamat-sharapov** [comment]
Can you show how you used it? It's best to make repro on jsfiddle (or somewhere else)

**Comment by brucesong08** [comment]
I think the way is same as my way.
this.someObject = Object.assign({}, this.someObject, { a: 1, b: 2 })

I used the way instead  jQuery.extend(true, {}, node.attr);

Thanks again.
