### ISSUE TITLE
Output dynamic <script>{ ... }</script> tag

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#2387]
I'd like to output a dynamic script-tag (for [Google Structured Data](https://developers.google.com/structured-data/rich-snippets/events))

Output of the script tag works, but it seems to be not dynamic:

http://jsfiddle.net/14fk9hg5/2/ (see source for output)

I also tried:
```js
{{{"<script>{'name': " + name + "}</script>"}}}
```
but doesn't work either.
Thanks

**Comment by dansullivan86** [comment]
As mentioned in the docs when you use triple braces data bindings are ignored.  http://vuejs.org/api/#v-html  You need to add the script tags to a template.

**Comment by kvdmolen** [comment]
Thanks to simplesmiler, this also works great: http://jsfiddle.net/simplesmiler/14fk9hg5/4/
