### ISSUE TITLE
Two-way filter updating on the fly

### ISSUE THREAD

**Issue by DenisAlliswell** [vuejs/vue#2388]
Hello, Evan!

Why two-way filter works only on change? There's no possibility to make it work on the fly (while typing, on keypress).

For sure, there's way to implement that functionality via 3rd part plugins, but I'd like to use pure Vue. 
Let's say, it could be some property (or attribute) to enable updating two-way filter on the fly.
It's would be more convenient and I guess Vue has enough power to do that.

This docs code works fine, but only on the input blur. Like with `lazy` attribute on.

```javascript
Vue.filter('currencyDisplay', {
  read: function(val) {
    return '$'+val.toFixed(2)
  },
    var number = +val.replace(/[^\d.]/g, '')
    return isNaN(number) ? 0 : parseFloat(number.toFixed(2))
  }
})
```

Please, pay some time on this one.

Thank you.

**Comment by yyx990803** [comment]
Updating two way filters when the user is typing results in very awkward UX. Trust me, it's a bad idea. Also, this was the way it worked in an old version of Vue and it's very hard to get the behavior right - for example, how do you re-position the cursor when the text has changed, when the filter can modify the input arbitrarily? The typing experience would be worse most of the time if you make it update on the fly.
