### ISSUE TITLE
Click event not firing on slot child component

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue#2390]
I thought I'd post this here first in case I was encountering a bug, or if not whether it'd be a quick feature to implement into Vue.js. I can easily move it to the forum if needed.

I'm trying to add a click handler to a child component (using `slot`), but the method doesn't seem to be firing when the target is clicked (see http://jsbin.com/ficihu/edit?html,js,console,output). I'm sure I've seen other people use a similar thing, but I could be wrong.

Any guidance as to whether this is an issue or not would be awesome. Thanks!

**Comment by simplesmiler** [comment]
Related to https://github.com/vuejs/vue/issues/2306

**Comment by yyx990803** [comment]
Closing in favor of #2306
