### ISSUE TITLE
build error with new new syntax of event

### ISSUE THREAD

**Issue by niluanxy** [vuejs/vue#2391]
I use webpack + vue in my project,but when i use UglifyJsPlugin of webpack,it will make build error.when i debug,it is because of new syntax of event,when i use "@tap",it will make build faild.i use webpack of gulp,and has update webpack to latest.
<img width="813" alt="qq20160225-1 2x" src="https://cloud.githubusercontent.com/assets/7076522/13311417/60d6de3a-dbc9-11e5-8684-2005921e0404.png">
<img width="524" alt="qq20160225-2 2x" src="https://cloud.githubusercontent.com/assets/7076522/13311421/662a509c-dbc9-11e5-844d-473bacc097cd.png">

**Comment by yyx990803** [comment]
Make sure to use vue-html-loader instead of html-loader. Also please open issues at corresponding repos.

**Comment by niluanxy** [comment]
Thank you,use vue-html-loader has solved.PS:hope you can add this tip in vue.org website.
