### ISSUE TITLE
Better watch structure

### ISSUE THREAD

**Issue by Hendriksie** [vuejs/vue#2395]
Hi there,

I've searched around and haven't find it so far so I hope it's no duplicate.

Playing around with the watcher of VueJs I've found a small "ergonomic" issue.

When I want to watch a property of a object a way to logically do this could be this:

```
var App = new Vue({
    data: {
         object: {
               key: 'value'
         }
    },
    watch: {
        object: {
            key: function() {
                  console.log('watched');
            }
        }
    }
});
```
But that does not work, instead I have to do it like this:
```
var App = new Vue({
    data: {
         object: {
               key: 'value'
         }
    },
    watch: {
        'object.key': function() {
             console.log('watched');
        }
    }
});
```

Is this something to consider? I personally like the way I showed in the first example better.

Thank you.

**Comment by hanai** [comment]
``` js
data() {
  return {
    key: 'value'
  };
}
```

**Comment by azamat-sharapov** [comment]
Because that's by design: you pass  `path` as a key to `watch` option. Same thing applies to `$watch()` method: it takes path as first parameter.

**Comment by azamat-sharapov** [comment]
To me, it feels less verbose. Why nest so many objects, when I can just do `'a.very.complicated. huge.js.object'`.

**Comment by yyx990803** [comment]
I think using nested objects to declare watch path is abusing the language syntax. Note we are keeping the options consistent with the imperative `vm.$watch` API as @azamat-sharapov mentioned, and also, the keypath can handle cases where nested objects can't, e.g. `arr[index]` or `a + b`.

**Comment by azamat-sharapov** [comment]
btw, Evan. Couple of times, I had problem setting paths containing `.` in key. Specifically, using `Vue.set()`. I worked around, but maybe you have some good solution for this? (i just thought, maybe escaping dot is possible in path?)

**Comment by Hendriksie** [comment]
Alright, thank you for explaining, that really helped!

**Comment by yyx990803** [comment]
@azamat-sharapov can you open a separate issue for that?

**Comment by azamat-sharapov** [comment]
Sure. I'll try to make repro and open.
