### ISSUE TITLE
Initial prop value in child component

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue#2397]
### Vue.js version
1.0.16

### Reproduction Link

https://jsfiddle.net/azamatsharapov/w6nry3ms/

### Steps to reproduce
See console for self-explanatory logs.

### What is Expected?
Parent component's data property has been changed in route `activate` hook, so the new value is expected in child component, when passed as `prop`.

### What is actually happening?
Child component has old value of `prop` on initialization.

Please let me know if anything not clear. Thank you.

**Comment by Mat-Moo** [comment]
I've note used router yet, but that looks correct to me? The indexComponent is initialised that kicks the sub component (null) then the route active kicks in and set the message and the watcher kicks in? I might be wrong, but because of the way Vue batches updates, I don't believe the order you see the console messages reflects 100% the way the data is being batched and processed.

**Comment by azamat-sharapov** [comment]
1. `indexComponent` has router `activate` hook, which is fired first
2. In that `activate` hook, we change `vm.message`
3. Then sub-component gets `ready`, but `msg` prop (which is `$parent.message`) has old value
4. Finally sub-component `prop` is updated to newest value of `vm.message`.

I'm starting to think, that this is more related to vue-router. I expected router hooks to process before component lifecycle hooks..

**Comment by yyx990803** [comment]
This is because prop propagation is also async using the internal batcher queue. The child's `ready` is called synchronously after the parent's `activate`, so the prop hasn't been propagated yet. I think I should probably mention this in the doc.

**Comment by azamat-sharapov** [comment]
Hmm, one solution would be to use `$parent.prop`. Anything else you could advice?

**Comment by yyx990803** [comment]
Similar to waiting for DOM updates, you can do a `nextTick` in the child's `ready` hook.

**Comment by azamat-sharapov** [comment]
Interesting! Works, thanks :)
