### ISSUE TITLE
$els isn't available through this.vm in directives in v-for.

### ISSUE THREAD

**Issue by crswll** [vuejs/vue#2398]
### Vue.js version
1.0.16

### Reproduction Link
https://jsfiddle.net/crswll/3c2p9bgk/6/

### Steps to reproduce
View the console. You'll see it works when not in a `v-for`.

### What is Expected?
I expected it to work in the `v-for`.

### What is actually happening?
It's returning undefined.

**Comment by yyx990803** [comment]
The problem is should we return an array? What if there are nested `v-for`s? Do we return an array of arrays? That doesn't seem to be useful...

I think it's better to describe the exact scenario that led you to want this feature. What are you trying to achieve?

**Comment by hfalucas** [comment]
Actually it was me who raised this question in gitter, but later realized that I was tackling the problem in the wrong way.

Basically wanted to create a directive to slideToggle an element. The `v-el` would be bounded to the element to be toggled, so I could check if the `v-el` is visible or not.

**Comment by crswll** [comment]
@yyx990803 I just messed around with `v-el` a bit more and I think I understand the situation a lot better now. I was under the impression that `vm.$els` held all the elements for that component. It appears you can only get to `$els` from the root component.

This is what helped me to understand: https://jsfiddle.net/crswll/3c2p9bgk/7/
