### ISSUE TITLE
[Feature request] escape dot in path

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue#2399]
https://jsfiddle.net/azamatsharapov/9daapg2u/

Above fiddle is super simple. I had a situation, where I had to set deep nested objects coming from server. Object keys had dots and code became verbose, because I had to first create each key via `Vue.set()` and then assign value using `Vue.set()` again. It would be nice if we could escape dot in object.

**Comment by yyx990803** [comment]
You can actually do `this.$set('obj.subObj["' + keyWithDot + '"]', 'works')` ;)

**Comment by azamat-sharapov** [comment]
oh :smile: xie xie
