### ISSUE TITLE
<header> tag makes a commponent fragment instance

### ISSUE THREAD

**Issue by tommyZZM** [vuejs/vue#2403]
http://developer.mozilla.org/zh-CN/docs/HTML/Element/header

child
```javascript
`<header></header>`
```

parent
```javascript
`<child class="my-class-name"></child>`
```

output
```javascript
`<header></header>`
// with:
// [Vue warn]: Attribute "class" is ignored on component <app-header> because the component is a 
// fragment instance: http://vuejs.org/guide/components.html#Fragment_Instance
```

if child use `div` ,every thing is ok

child
```javascript
`<div></div>`
```

parent
```javascript
`<child class="my-class-name"></child>`
```

output
```javascript
`<div class="my-class-name"></div>`
```

**Comment by simplesmiler** [comment]
Most likely it's not because of the `<header>`, but because your parent contains another component as a root. Thy the following template for parent: `<div><child class="my-class-name"></child></div>`.

**Comment by yyx990803** [comment]
This is expacted - please read the fragment instance docs carefully.
