### ISSUE TITLE
Issue in IE 11: template v-if in table row leads to fragment instance

### ISSUE THREAD

**Issue by pgunya** [vuejs/vue#2404]
### Vue.js version
1.0.16

### Reproduction Link
https://jsfiddle.net/pgunya/v8ndoocg/

### Steps to reproduce
Add `<template v-if="...">` element in table row and check in IE.

### What is Expected?
No fragment instance and correct behaviour.

### What is actually happening?
In Internet Explorer 11 when `<template v-if="...">` element is present inside template's table row then vue gives a warning about fragment instance and template v-if doesn't work as expected. In latest Chrome and Firefox this works fine. At the same time `<template v-if="...">` works fine if placed inside other tag, example: https://jsfiddle.net/pgunya/sa7vtgtt/

**Comment by azamat-sharapov** [comment]
IE does not support `<template>` inside elements like `<table>`, `<select>`.. You may want to read through this post: http://forum.vuejs.org/topic/2088/table-and-template-on-ie

**Comment by pgunya** [comment]
Yes, now I see. 
But then I have a silly question: template is located inside a `<script>` tag, I thought that it content should not be parsed by browser until vue compile it and insert into target element. Am I wrong? Thanks!

**Comment by yyx990803** [comment]
Vue renders the template into real html before compiling it, so the same html restrictions apply for Vue templates, no matter how you define it.
