### ISSUE TITLE
acceptStatement:true 与 v-on directive 的 handler 参数

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue#2405]
### Vue.js version
1.0.16
### 问题
文档里有提到设置了`acceptStatement:true` 后，`fn` 参数是 function：
```js
update: function (fn) {
    // the passed in value is a function which when called,
    // will execute the "a++" statement in the owner vm's
    // scope.
  }
```
在 v-on directive 中检查了 `handler` 是否为 function，这个 if 是不是多余的？
https://github.com/vuejs/vue/blob/dev/src/directives/public/on.js#L92

**Comment by yyx990803** [comment]
It can be undefined or null.
