### ISSUE TITLE
[Proposal] v-show add a modifier 

### ISSUE THREAD

**Issue by vieks** [vuejs/vue#2408]
First of all thanks for your amazing work. Vue is powerful and elegant at the same time, pretty neat !

It will be nice to add a "visible" modifier or any suitable name to the `v-show` directive.
Indeed by default `v-show` use `display:none` css property which hide the element as it was not in the DOM. Unlike `visibility:hidden` where the element will be hidden but still affecting the layout.

eg:
```html
<!-- default behavior: display:none @false -->
<div v-show="prop">Hello</div>
```

```html
<!-- modifier behavior: visibility:hidden @false -->
<div v-show.visible="prop">Hi</div>
```

**Comment by Mat-Moo** [comment]
https://github.com/vuejs/vue/issues/2382
