### ISSUE TITLE
Allow for passing null / undefined into a typed, none required prop

### ISSUE THREAD

**Issue by rmp135** [vuejs/vue#2411]
If a prop is declared with type validation but `required:false`, the validation will fail when passing either null or undefined as the value.

I think that the type validation should only occur on none required props if an actual value (not null or undefined) has been passed. I believe this is similar to issue #1070.

[Here's](https://jsbin.com/qanixo/edit?html,js,console,output) a JSBin demonstrating this.

**Comment by rmp135** [comment]
Shouldn't the prop check for a default value first? It would keep it more in line with what happens if you omit the prop completely.

[Here's](https://jsbin.com/cikebo/edit?html,js,output) another JSBin showing the different ways to pass a non value prop through. I'm thinking it should fall back to the default value in all cases.

**Comment by yyx990803** [comment]
I have thought about this before, and didn't implement it because user may explicitly want to pass down undefined - but now I think it is appropriate to map it to the semantics of JS function calls so that default value would be used if the passed down prop is undefined.

**Comment by yyx990803** [comment]
See 04116fc

**Comment by rmp135** [comment]
Thanks. I was going to suggest a `nullable` prop option for allowing nulls to be passed down in the  case of none required props. In this case, the default would only apply if the prop was completely absent.

**Comment by lopugit** [comment]
@yyx990803 I'm a bit confused by the commit, it says

`if (raw === null) {
          // initialize absent prop
 -        initProp(vm, prop, getDefault(vm, options))
 +        initProp(vm, prop, undefined)`

but I can't see any code for handling undefined, and the commit actually says that if it is null, then it's set to default. 

when is undefined passed as a prop handled?

**Comment by lopugit** [comment]
// check default value
  if (value === undefined) {
    value = getPropDefaultValue(vm, prop, key);
    // since the default value is a fresh copy,
    // make sure to observe it.
    var prevShouldConvert = observerState.shouldConvert;
    observerState.shouldConvert = true;
    observe(value);
    observerState.shouldConvert = prevShouldConvert;
  }
  {
    assertProp(prop, key, value, vm, absent);
  }

I found this bit in vue.js v2 dist, is it around this part that defaults are now handled?

I can't find a comment of

Build a function that applies props to a vm.

anywhere in the current v2 vue.js build
