### ISSUE TITLE
<vue> root element in Single file components

### ISSUE THREAD

**Issue by JackuB** [vuejs/vue#2418]
1. [Single file components](http://vuejs.org/guide/application.html#Single_File_Components) are awesome.
1. They are an XML notation - `<template>`, `<script>` and `<style>` are an XML elements. Whole file is being parsed by parse5.
1. Currently, they are invalid from an XML standpoint: `<template></template><script></script>` is missing root element. [Vue itself knows it's problematic](http://vuejs.org/guide/components.html#Fragment_Instance)

My suggestion is to add _optional (?)_ root `<vue>` element so `.vue` could be parsed by _any_ XML parser instead of only HTML parsers.
 
```xml
<vue>
  <template></template>
  <script></script>
  <style></style>
</vue>
```
 
Currently, vue-loader won't compile such files. 

I'll be happy to prepare PRs for this.

**Comment by yyx990803** [comment]
What are the benefits? Vue files are HTML, not XML. Why should it be made
to be XML-parsable when it is already HTML-parsable?

**Comment by JackuB** [comment]
We were playing with ideas around de/serialization of .vue files for building devcards for Vue components. But after taking a closer look at parse5 and logic around parseFragment, `<vue>` isn't needed. Thanks for reply, closing this.
