### ISSUE TITLE
在v-for过程中，能否有地方可以存储对item的简单计算结果？

### ISSUE THREAD

**Issue by Joey-93** [vuejs/vue#2419]
在使用v-for过程，有时候需要对item进行一些操作，这个时候使用filter,method都可以实现。
不过，比如我会在**两处**地方使用```item | filter```，这个时候会进行两次filter过滤运算，而且代码上，还要写两次 ```| filter```。
我想有没有跟v-for对应的指令，比如```v-save.test="item | filter"```，用来保存一次过滤后的结果，可以在之后使用test变量值。

**Comment by yyx990803** [comment]
用计算属性。
