### ISSUE TITLE
Directive priority

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2420]
Hi, i have some question about priority for directives and components.
I right understand that components it's also directive and component have priority 1500?
If it's right, then why if i create directive with priority > 1500 (like v-if directive with 2000 priority) this directive will be init after component init?

Thanks for the help

**Comment by vuchl** [comment]
> component have priority 1500?
[yes](https://github.com/vuejs/vue/blob/dev/src/directives/priorities.js#L6)

>  if i create directive with priority > 1500 (like v-if directive with 2000 priority) this directive will be init after component init?
No. Higher priority means earlier compilation. So if yoou want to create a directive that is compiled later, you need to give it a lower priority.

**Comment by yyx990803** [comment]
Components' directive priority is only relative to other directives in the same scope. A directive *on the same element with a component** is considered a directive **inside** that component's scope.

Also, directive priority only affects **compilation order**, which is different from **collection order**. During the collection phase, terminal directives like `v-if`, `v-for` and components have hard-coded highest priority.

**Comment by AStaroverov** [comment]
Thx for answer @yyx990803 !
Then it might be worthwhile to add the ability to create terminal directive like v-if or is it not possible?

**Comment by yyx990803** [comment]
@AStaroverov it's already possible, but not documented, as it involves a lot of understanding of Vue internals. Basically you can define a directive and push its name into the `Vue.compiler.terminalDirectives` array.

**Comment by AStaroverov** [comment]
Awesome! Intresting information :+1:
