### ISSUE TITLE
[suggestion] Better symbol to apply filters

### ISSUE THREAD

**Issue by niceue** [vuejs/vue#2422]
Thanks a lot for this great work. I talk my little idea.

Vue use the unix “pipe” symbol to apply filters: 
```
{{ message | filterA | filterB }}
```
But it is also a javascript symbol as "bitwise or". It seems rather strange.
I think the better way to apply filters is arrow:

```
{{ message -> filterA -> filterB }}
{{ myNumber -> currency }}
```

**Comment by yyx990803** [comment]
Thanks for the suggestion. As you've noted, the pipe is common for data piping in unix, so the concept is familiar. `->` seems to have no obvious benefits to me.

On the other hand, do note Vue is a post 1.0 project, so we're not going to make any breaking changes without strong arguments behind them.

**Comment by myst729** [comment]
Since filters are supported in `v-bind` expressions prior to version 2.1.0, does this issue need to be revisited?

**Comment by xcatliu** [comment]
@yyx990803 Thanks for the great framework!

For this issue, I would agree to @niceue , Vue.js SHOULD supports the full power of JavaScript expressions inside templates.

We can use template like these:

```
{{ number + 1 }}
{{ ok ? 'YES' : 'NO' }}
{{ message.split('').reverse().join('') }}
```

But it's strange that Vue.js support above syntax but doesn't support bitwise or.

I've write a demo to show the strange behavior.

https://jsfiddle.net/hxrnbanr/2/

```html
<div id="app">
{{ n & 2 }}
<br/>
{{ n | 2 }}
</div>
```

```js
new Vue({
  el: '#app',
  data: {
    n: 1
  }
})

alert(1 & 2);
alert(1 | 2);
```

HTML renders to `0`, `1`.
While `alert` shows `0`, `3`.

---

However, I don't like `->`, but I haven't think out a perfect solution.

**Comment by myst729** [comment]
Revisiting this issue., now I turn to be happier with a computed property. Not only for the bitwise issue, but also more flexible, as filters are still limited to text interpolations and v-bind expressions.
