### ISSUE TITLE
如何动态的控制一个按钮的禁用和启用（控制disabled属性）

### ISSUE THREAD

**Issue by satrong** [vuejs/vue#2423]
`<button disabled="disabled"></button>`
如果需要禁用一个button只需要加上`disabled`属性，需要启用就需要删除`disabled`属性。
请问除了用原生的方法删除属性，在vuejs中有没有相应的方法？

我用Knockoutjs的时候它有专门处理`disabled`的方法，不知vuejs有没有。

目前想到的一个方法是：
```html
<button v-show="!disabled" disabled="disabled"></button>
<button v-show="disabled"></button>
```
如果button或者input多了，就有点繁琐了

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by yyx990803** [comment]
`<button :disabled="disabled">`

**Comment by xiaolongyuan** [comment]
这也算一个问题。。。。。。。。。

**Comment by SimplyY** [comment]
@xiaolongyuan 

Questions should be posted to the Gitter chat room, forum or StackOverflow. Thanks.


看英文少年，应该去 Gitter chat room, forum or StackOverflow 这些地方问。

**Comment by satrong** [comment]
@yyx990803 谢谢，在API中没找到有这方法

**Comment by jddy** [comment]
举一反三的能力还是需要多多锻炼！ 作者不可能写完所有例子。

**Comment by orange-pig** [comment]
@yyx990803 

`<button :disabled="disabled">`

这个方法不行，disabled设置成true，disabled属性就被移除了。修改绑定值为fasle后，并没有禁用好吧。
并在这个地方
`
  function before(el, target) {
    target.parentNode.insertBefore(el, target);
  }
`
报了一个一个异常：

> vue.js:1205 Uncaught TypeError: Cannot read property 'insertBefore' of null(…)before @ vue.js:1205(anonymous function) @ vue.js:1060applyTransition @ vue.js:1102beforeWithTransition @ vue.js:1059singleBefore @ vue.js:3809insert @ vue.js:4643update @ vue.js:4626_update @ vue.js:8334Watcher.run @ vue.js:3344runBatcherQueue @ vue.js:3075flushBatcherQueue @ vue.js:3045nextTickHandler @ vue.js:449

Version: Vue.js v1.0.26

我也碰到提issues的兄弟这个问题了才来搜搜issues，看来只能手动撸代码解决了。

真是心寒，没想到github上也能看到 @xiaolongyuan @jddy 这种优越党，问题都没搞清楚就开始嘲讽。

**Comment by FrankFang** [comment]
即使使用了 :disabled="disabled" ，也要给每个按钮加，有没有更好的方法呢？

**Comment by chuanPro** [comment]
@FrankFang  @orange-pig 作者（代指“VUE作者”）不建议操作DOM，是因为操作DOM会导致渲染速度等诸多因素。在适当的时候还是应该以操作DOM的形式来快速解决问题，这种情况依然没有违背作者的初衷。推荐使用路由的方式来更改input标签的disabled属性，用来区分是查看详情还是编辑详情：
 mounted () {  // 组件创建完成
      let el = document.querySelectorAll('input')
      if (!this.$route.query.disabled) {
        for (let x of el) {
          x.setAttribute('disabled','disabled')
        }
      }
    }
提示：你依然可以配置为全局方法，在页面重新渲染的时候进行该操作（先行了解关于VUE的生命周期钩子），但不推荐这样做，除非你很多地方都用了这个属性。

**Comment by FrankFang** [comment]
@chuanPro 为什么用路由？感觉用路由控制按钮的disabled状态不符合直觉

**Comment by chuanPro** [comment]
@FrankFang 因为路由可你帮你处理当前打开的状态是否可编辑，是可编辑还是仅仅是查看。这只是一个思路，有一种愚蠢的方法，就是选择class进行disabled，同样是可以的，不同的场景不同的思路。你应该致力于思考这个问题：“一切重复的工作都是不必要的，一旦发现自己在重复的写一个东西，你就应该考虑一下这是否是最优的解决方式”

**Comment by AplloBattlestarGalactica** [comment]
`newValue.map(index => {
          temData.push({
            name: index.fileInfo.name.replace(/"/g),
            size: JSON.stringify(index.fileInfo.size / 1048576).replace(/"/g).slice(0, 5) + 'MB',
            dimensions: {
              width: index.fileInfo.width,
              height: index.fileInfo.height
            },
            inputState: true})
        })`

`<el-input
          :disabled="scope.row.inputState"
          :value="initWidth(scope.row)"
          placeholder="宽"
          size="mini" />
        <p>&nbsp;&nbsp; * &nbsp;&nbsp;</p>
        <el-input
          :disabled="scope.row.inputState"
          :value="initHeight(scope.row)"
          :focus="editPic(scope.row)"
          placeholder="高"
          size="mini" />`
或许可以这样写

**Comment by AplloBattlestarGalactica** [comment]
`
<el-input
          :disabled="scope.row.inputState"
          :value="initWidth(scope.row)"
          placeholder="宽"
          size="mini" />
        <p>&nbsp;&nbsp; * &nbsp;&nbsp;</p>
        <el-input
          :disabled="scope.row.inputState"
          :value="initHeight(scope.row)"
          :focus="editPic(scope.row)"
          placeholder="高"
          size="mini" />
`
`
newValue.map(index => {
          temData.push({
            name: index.fileInfo.name.replace(/"/g),
            size: JSON.stringify(index.fileInfo.size / 1048576).replace(/"/g).slice(0, 5) + 'MB',
            dimensions: {
              width: index.fileInfo.width,
              height: index.fileInfo.height
            },
            inputState: true})
        })
`
或许可以这样写

**Comment by aaaxiu** [comment]
> > 举一反三的能力还是需要多多锻炼！ 作者不可能写完所有例子。
> 
> 初学者不了解原理，怎么举一反三？举一反三都是在正确深入的了解原理后，才能达到呢，像我们这种菜鸟，难道就不应该提问吗？现在那些聊天室、群等等哪个不是吹牛逼的时候高朋满座，一问个问题，就各种冷嘲热讽，说各种 little case 的人，我们还怎么解决？知道你们是大神，忙着各种业务方面的重大改进等，但是我们实在是没办法了才来这问的啊，大神的某些经验，肯定比那些净瞎吹牛逼的各种群友要强，要少走好多弯路，不是吗？

不要偷换概念, 不是不让提问, 而是提问的方式和地方不对
