### ISSUE TITLE
Problem with transition

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2425]
### Vue.js version
1.0.17

### Reproduction Link
http://worldofwarships.com/en/community/accounts/teams/

### Steps to reproduce
Press the button "load more" fast as possible

### What is Expected?
In one time this button can be blocked

### What is actually happening?
I have overlay layer for table and button

overlay:
```
<div v-show="stateOfLayer" transition="v-simple-opacity"></div>
```

transtion:
```
.v-simple-opacity
  &-transition
    transition: opacity .2s ease-out
    opacity: 1

  &-enter,
  &-leave
    opacity: 0

```

and then i do async query,  i change stateOfLayer at true,
after response i set ``stateOfLayer = false``
and some times overlay layer not receive the property ``display: none``,
only class ``.v-simple-opacity-leave``

What I have noticed from experimentation:
if response is faster than the duration of the animation, then sometimes  a bug occurs
and if after response i set ``stateOfLayer = false`` with delay more than 200ms, bug not accurs

I think there is problem with vue transition system.

P.S. This bug can live maximum about 2-3 days, after we release patch, where i add delay for change ``stateOfLayer`` and Sorry for my english.

**Comment by yyx990803** [comment]
The live link seems to be down, do you have a simpler repro, e.g. a jsfiddle?

**Comment by AStaroverov** [comment]
ok, i try repeat it at jsfiddle

**Comment by AStaroverov** [comment]
I couldn't repeat this at jsfiddle.
Сan a Transition Directive have some difficulty in components with a large number of reactive variables, or this has nothing to do?

**Comment by yyx990803** [comment]
Unfortunately I can't really triage this without a testable repro - but feel free to open a new issue when you run into it later (and hopefully reproducible)

**Comment by AStaroverov** [comment]
Okay)

пн, 14 марта 2016 г., 21:10 Evan You <notifications@github.com>:
