### ISSUE TITLE
Loops twice in Safari

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#2429]
The following runs twice in Safari. Safari problem or Vue problem?:

```js
for(var i in this.myArray){
    this.myArray[i] ...
}
```

https://jsfiddle.net/kvdmolen/onf0nmkn/2/ (Safari 9.0.3, OSX 10.11.3)

**Comment by yyx990803** [comment]
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea
