### ISSUE TITLE
Conditional display v-if/v-show is not working inside of table tag

### ISSUE THREAD

**Issue by GitYong** [vuejs/vue#2431]
Conditional display is not working with tags inside a table tag. Please heck https://jsfiddle.net/t9u4ve2b/1/ for details.
```
        thead
            tr(v-if="items.length > 0")
                th QTY
                th ITEM
                th.right-align PRICE
            tr(v-else)
                p This is a faulty transaction
```

**Comment by yyx990803** [comment]
Your fiddle is loading Vue over http in an https page. Once fixed it's working as intended.
