### ISSUE TITLE
Can't listen to change the value of jQuery?

### ISSUE THREAD

**Issue by rainwsy** [vuejs/vue#2433]
I use ajaxupload upload, upload success after the return of a JSON containing the URL value, using jQuery to set the value of the text box for the URL in the JSON
So I found that vuejs did not listen to this value changed. What is the solution? Or I will use `$(''#id) (.Val)` to directly get?

**Comment by Twiknight** [comment]
You should update the `data` rather than the dom elements if you're not handling a input-like component.

Personally, I strongly recommend single-binding. Double-binding leaves a back door for bad code.

If you intend to update the dom tree manually, why using Vue?

**Comment by rainwsy** [comment]
I understand. This is a historical problem. vue js with jquery are in use.Thanks

**Comment by yyx990803** [comment]
Vue doesn't listen to direct DOM changes - it only listens to user input events. For more questions please use the gitter room or the forum.
