### ISSUE TITLE
How to pass a function by props to child component?

### ISSUE THREAD

**Issue by nolest** [vuejs/vue#2434]
### Vue.js version
1.0.16

How to communicate Between parents and child?

There are two button in parents.
`<ui-button func="button"></ui-button>`
`<ui-button func="button2"></ui-button>`
When i click them the click function in each button will call `func` form parents.
I want to pass a function for each one by `props` but it show me 
`[Vue warn]: Invalid prop: type check failed for func="button2". Expected Function, got String.`
When i trigger them
`Uncaught TypeError: this.func is not a function.`

The document in 
[http://vuejs-ru.github.io/vuejs.org/guide/best-practices.html#communication-between-instances](url)
**Communication Between Instances** did not work anyway.Maybe the by version v0.12.14.

Can the props pass function? 
Could you show the right way to do this?

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

---

To your question: it needs to be bound as `v-bind:func="button"` or `:func="button"`.
