### ISSUE TITLE
v-if and v-for

### ISSUE THREAD

**Issue by skinTest** [vuejs/vue#2444]
when the two diretives come together in one el , the v-if will be ignored.
Although, this can be coped with
``
<template v-if=''>
  <el v-for= ''></el>
</template>
``
or wrap the two directives the other way around, however,  ``<el v-if v-for></el>`` seems more intuituve

**Comment by yyx990803** [comment]
I don't think that's the case. Please provide a reproduction.

**Comment by paulpflug** [comment]
I'm not 100% certain, but maybe the problem is, that the `v-if` is bound to each instance of the `v-for`?
This definitely works (I used it already):
```html
<el v-if="child.show" v-for="child in children"></el>
```
Maybe the scope of the parent vm is inaccessible?
Is the following the problem?
```html
// assuming showChildren is on the same scope as children
<el v-if="showChildren" v-for="child in children"></el>
```

**Comment by yyx990803** [comment]
Closing (inactivity). Please reopen if you can follow up with more information.
