### ISSUE TITLE
Dynamic components, ready, activate and v-for strange behaviour

### ISSUE THREAD

**Issue by straps** [vuejs/vue#2445]
### Vue.js version
1.0.17

### Reproduction Link
https://jsbin.com/lagucugemu/12/edit?html,js,output

### Steps to reproduce
Create 2 components, one that reference the other, and use it in a v-for loop

### What is Expected?
Component ready callback should always be be called

### What is actually happening?
I have a component that references another component.

Everything works well until I use it in a v-for loop

Outside v-for it renders ok
`<component :is="compB"></component>` ==> `Component B containing "component A"`

Inside v-for component-a ready callback gets never called
`<component v-for="n in 1" :is="compB"></component>` ==> `Component B containing "component ???"`

Is there a valid reason for this or is it a bug?

Thanks

**Comment by ryanshawty** [comment]
It appears that the ready event is only called once per component, using 'created' seems to work https://jsbin.com/fukosaqosu/edit?html,js,output

I don't know if this is intentional or not.

**Comment by straps** [comment]
@ryanshawty I've commented out the component outside `v-for`, but `ready` and `attched` hooks are still not called

See here: https://jsbin.com/seceqotazi/3/edit?html,js,console,output

I can't use the `created` callback because I need to be sure `$el` is attached to the `DOM`

**Comment by prog-rajkamal** [comment]
@straps I can't find any docs related to `activate` hook. can you tell me where you found it?

**Comment by straps** [comment]
See here: http://vuejs.org/guide/components.html#activate_Hook

**Comment by prog-rajkamal** [comment]
@straps sorry, i found it right after commenting and deleted my comment, so others won't have to bother . guess i was late in deleting

**Comment by straps** [comment]
Thank you @yyx990803
