### ISSUE TITLE
Input checkbox broken when initiating with localstorage

### ISSUE THREAD

**Issue by tianshuo** [vuejs/vue#2446]
### Vue.js version
1.0.17

### Reproduction Link
http://runjs.cn/code/gl3lbezs

### Steps to reproduce
1. Open link.
2. Click checkbox to disable
3. Refresh page

### What is Expected?
4. Shows unchecked checkbox and `false` label

### What is actually happening?
4. Shows checked checkbox and `false` label

Very strange behavior.
In the console `myV.$data.check` outputs `false`. Running `myV.$data.check=myV.$data.check` does nothing, but running `myV.$data.check=false` unchecks the checkbox.

**Comment by yyx990803** [comment]
Please use correct localStorage API....

**Comment by tianshuo** [comment]
How is the localStorage API wrong?

**Comment by azad112358** [comment]
The type of the `localStorage.check` is `string`,not `boolean`.

**Comment by tianshuo** [comment]
Thank you, I fixed it by checking `localStorage.check=="true"`
