### ISSUE TITLE
Component DOM element not removed when destroyed and using instance DOM methods

### ISSUE THREAD

**Issue by rjoo** [vuejs/vue#2448]
### Vue.js version
Latest dist

### Reproduction Link
http://jsfiddle.net/up5prrnp/

### Steps to reproduce
Have a component rendered conditionally with `v-if` directive, and in the `ready` hook appended elsewhere with `this.$appendTo()`.

### What is Expected?
The element to be removed when condition is no longer met; basically the same behavior when `this.$appendTo()` or any of the other similar methods isn't used.

### What is actually happening?
Element persists and can potentially cause duplicates. The fiddle isn't the greatest example as I know that it's preferable to use `v-show` in that case, but in a nested component structure, a child component's moved element will not be removed even if the parent component is removed.

**Comment by yyx990803** [comment]
You should never use dom api to move components generated and managed by directives. When you do, there's no guarantee about correct behavior.

**Comment by rjoo** [comment]
Thanks for your quick response!

What would you be your recommended solution then to say a 'lightbox' component that needs to be a direct child of the `<body>` due to the z-ordering nature and needs of a lightbox.

For example, I'm using the dynamic `<component :is="">` to conditionally render views. Within some of those views, there are 'lightbox' components nested within other components. When switching views, the stale lightbox elements persist in the `<body>`.

I'm manually removing the elements in the component's `beforeDestroy` hook, but I wonder if I've approached this all wrong after reading your comment. Again, thanks for your input!

**Comment by simplesmiler** [comment]
@rjoo [vue-transfer-dom](https://github.com/rhyzx/vue-transfer-dom).
