### ISSUE TITLE
[docs] Pressing enter in docs search only refreshes current page 

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#2449]
If this isn't the right place for the issue, I apologize! I couldn't find a docs repo and no one in Gitter channel knew of one.

### What's happening

When typing something in the search at [vuejs.org/guide/](http://vuejs.org/guide/), a dropdown of results appear. I can click on items in those results, but if I press _Enter_, the list of results disappears and the page is refreshed.

### What I expect to happen

When pressing _Enter_, it would make sense to me if the top result in the search were navigated to, instead of refreshing the current page.

**Comment by yyx990803** [comment]
The docs repo is at https://github.com/vuejs/vuejs.org

The search is using algolia's [docsearch](https://github.com/algolia/docsearch), maybe open an issue there instead?

**Comment by chrisvfritz** [comment]
@yyx990803 Thanks! I'll be sure to post there for future documentation issues.

**Comment by chrisvfritz** [comment]
@yyx990803 This should now be fixed in [docsearch 1.1.1](https://github.com/algolia/docsearch/commit/1d7930a90aef4d5a588a1550feb0542f575ccd4d). :tada:

**Comment by yyx990803** [comment]
Sweet
