### ISSUE TITLE
vm.$interpolate not attaching events in HTML being parsed

### ISSUE THREAD

**Issue by leonardo-ferreira-caldas** [vuejs/vue#2454]
### Vue.js version
1.0.17

### Reproduction Link
https://jsbin.com/hocoyo/edit?html,js,output

### Steps to reproduce
Just click the link created during iteration in the example above.

### What is Expected?
To show an alert.

### What is actually happening?
Nothing.

**Comment by yyx990803** [comment]
This has nothing to do with `$interpolate`: raw HTML interpolation (which is `v-html` under the hood) **does not** compile the content as template, it's just inserted as raw HTML: http://vuejs.org/api/#v-html
