### ISSUE TITLE
How to make element transition on its first render?

### ISSUE THREAD

**Issue by tommyZZM** [vuejs/vue#2495]
i try to  use `v-if` to wrap these element, and then toogle boolean variable on ready();

but i thik it's a little verbose.

**Comment by jonagoldman** [comment]
For questions and support please use the[ Gitter chat room](https://gitter.im/vuejs/vue) or the [official forum](http://forum.vuejs.org/). The issue list of this repo is exclusively for bug reports and feature requests.

**Comment by Twiknight** [comment]
I'd make a shameless pr on [vue-transition](https://github.com/Twiknight/vue-transition)

BTW, I never consider it a good idea to wrap transition in vue

**Comment by simplesmiler** [comment]
Related to https://github.com/vuejs/vue/issues/1654

**Comment by yyx990803** [comment]
Currently you have to do it manually. This will likely be easier in 1.1.
