### ISSUE TITLE
提一点关于methods的建议

### ISSUE THREAD

**Issue by meixuexiang** [vuejs/vue#2496]
现在的methods只支持纯粹的对象类型，并在_initMethods方法里bind到this上，以便于在调用到的时候，拥有固定的上下文。

是否可以考虑支持new出来的对象的原型链上的方法呢？比如：
`function Foo(){

}
Foo.prototype = {
    methodA: function(){},
    methodB: function(){}
};
...
    methods: new Foo() //期望methodA和methodB都是可用的
...
`

并且把bind操作推迟到绑定事件甚至触发事件的时候再做。

改造的难度并不大，而好处是显而易见的，盼复

**Comment by yyx990803** [comment]
请问有什么好处

**Comment by meixuexiang** [comment]
可以用基于原型的继承的方式来管理methods，利于代码复用
可以动态的向methods对象或者原型链上添加方法，增强可扩展性
动态添加的方法也可以获得同样的context
不需要预扫描methods里的所有方法，化整为零，提高new Vue的速度

**Comment by yyx990803** [comment]
1. 不建议用这样的方式管理 methods，用 Vue 本身的 mixin 即可

2. 在模版固定的前提下，动态添加方法并没有太多意义。动态添加方法使得组件的行为不可预测，也不利于维护。

3. 预扫描 methods 的代价在整体的组件初始化过程中可以忽略。

**Comment by meixuexiang** [comment]
1. 如果只是出于管理methods考虑，的确用mixin比较合适。不过，多了一种可能，未必是坏事，这要看从什么角度来看待了。
但是，增加对原型链上的方法支持，还可以为使用方法提供了多一种方式，更是可以方便的调用第三方的方法，如 lodash （当然，这需要对methods的机制做一点改进，比如：善加利用return）

2. 同意你的说法

3. 不是预扫描 methods 的代价花不起，而是，我觉得，提前做了可能不需要做的事，浪费了不必浪费的时间，对用户体验也没有明显改善，从情理上都不应该如此。

其实，我希望的只有一点：methods支持调用原型链上的方法
如有说的不对的地方，请海涵、指正

**Comment by tigerui** [comment]
尤神辛苦
