### ISSUE TITLE
About the click event is also use '@click' in the mobile. 

### ISSUE THREAD

**Issue by mlyknown** [vuejs/vue#2498]
About the click event is also use '@click' in the mobile. In's the offcial website  "vue - touch" is obsolete, have any plugin for vue ?

**Comment by ClassicOldSong** [comment]
This should not be a problem.
The 'click' event triggers on mobile even you use native javascript.

**Comment by mlyknown** [comment]
so delay will happen on mobile.

**Comment by simplesmiler** [comment]
Delay has nothing to do with vue. You can mitigate the delay with dedicated libraries.

**Comment by ClassicOldSong** [comment]
You can use vue-touch to remove the 300ms delay

**Comment by sirlancelot** [comment]
You can also add CSS: `touch-action: manipulation;` to the element.

**Comment by mlyknown** [comment]
thnaks 0.0
