### ISSUE TITLE
filterBy 的bug

### ISSUE THREAD

**Issue by luckycol** [vuejs/vue#2502]
使用中的情景是：
从数据库中读取1-100号id序列，含名字、分组编号。
例如：
id,pid,name
1,1,name1
2,12,name2
3,13,name3
4,25,name4
……
在输出时使用 v-for 循环， filterBy过滤编号为【1，12，13，25】4组，（编号非有序）。

`<a href="#" v-for="field in fields | filterBy '1' in 'pid'" v-on:click.prevent="set_search(field.id)" v-bind:class="{'active':field.checked}">{{field.classify_name}}</a>`

在输出1时，将会把12、13分组的也带出来。

这是我遇到的问题，没有研究过源码，猜想过滤的是相似而非等于，在API中也没有找到是否有参数控制是相似还是等于，不知道是否算是bug，或者是您有更深远的想法。

希望能够得到一点反馈，谢谢。

还有希望在教程中获取对于某个教程的思路，例如：这个教程一般用于解决什么样的问题，还有其他什么样的场景能够用到。因为通过这样有目的性的教程，可以更加有代入感，且印象深刻，在以后遇到问题时也能够想起来如此的解决方案；光看技术解释则有种生硬的感觉。
好的软件技术是为了更好解决问题而生，缩短理解时间也是更好的。而且您有这么好的技术，定是有巨量的经验加上细致的思考，如果能够通过某几个典型问题结合来说……功德无量。
个人浅见，冒昧之处请见谅。

**Comment by yyx990803** [comment]
filterBy 的用例是用来搜索字符串匹配的，只要部分匹配就会包含进来。需要精确匹配可以自己写一个 filter 或者用 computed property.

**Comment by luckycol** [comment]
了解了，感谢回复。
