### ISSUE TITLE
Uncaught exception in Vue.filter function may cause the framework crash?

### ISSUE THREAD

**Issue by Nihiue** [vuejs/vue#2503]
I think it's very common that you got an uncaught exception in filter function because of an unexpected input , which should not cause the whole page crash.

Maybe tell everybody ALWAYS use try...catch for filter function in document , or the framework should handle this exception and goes on .

**Comment by fullfs** [comment]
@Nihiue Hello!
It's definitely a pain sometimes and I think it's a good thing to treat it the same way as template expression error with throwing a warning message.
The issue should probably be labeled as ```suggestion```.
As for now I propose you to check the value type in filter function.
For example, if you expect an Array, you could handle it like this:

```javascript
function (value) {
    if (Array.isArray(value)) {
        return value.map(function (item) { return item });
    }

    return value;
}
```

**Comment by yyx990803** [comment]
I think it is the user's responsibility to handle edge cases the custom filters, just like in any other code you write. Throwing errors in JavaScript always crash the app, that's just how it works.
