### ISSUE TITLE
In the directive  how to make a judgment dom tree has been built or CSS are already in the dom element

### ISSUE THREAD

**Issue by mlyknown** [vuejs/vue#2504]
![qq 20160316232724](https://cloud.githubusercontent.com/assets/12880984/13848488/0185b2ba-ec8d-11e5-87d2-bc4f0f5c05ad.png)

When the bind function is executed ,css properties has not been effective.

**Comment by yyx990803** [comment]
The `bind` happens when the element is still off-the-DOM.

You can do `this.vm.$once('hook:ready', ...)` to wait for the vm to be ready.

**Comment by mlyknown** [comment]
thanks
