### ISSUE TITLE
Feature request: v-fragment-root on <slot>

### ISSUE THREAD

**Issue by prog-rajkamal** [vuejs/vue#2509]
Motivation
========
As you might already know, `<slot>` does not allow attributes whether html or vue directives (except v-if) the main reason behind this is 
>Directives are ignored on <slot> because it's only a placeholder for parent inserted content, and it may contain non-elements, e,g, just text nodes. 

My feature request aims to provide a way to create an exception for the non-elements. so that we can use `v-el`, `v-show` etc on `<slot>`

this is a pretty popular request https://github.com/vuejs/vue/issues/2494 https://github.com/vuejs/vue/issues/2390 https://github.com/vuejs/vue/issues/2128

Syntax
======

the core idea is that in most use-cases, we will be using directives on *named* slots instead of default slot and those named slots are more likely to not be a fragment instance. so we basically need mechanism to handle edge cases only.

To that end, I propose to add a directive `v-fragment-root` (name will hopefully change in future ).

Syntax:
     
    <slot name="item" 
          v-fragment-root="div"   //use <div> tag for fragments   
          class="my-item"         //add attributes on slot
    ></slot>
   
    <slot 
         v-fragment-root=""      //this causes current behavior
         class="my-item"         //attribute is ignored and a warning is raised.
    ></slot>

Possible Problems
===============

1)  `v-for` will either not work or will be confusing to use. As `<slot>` will depend on both props passed to component and `<slot>` tags passed.
2)  `v-el` is slightly different case. a named `<slot>` can be targetted multiple times but `v-el` can target only one element. like in following code.
  
     <my-tag class="hack">
        <child1 slot="item"> </child1>
        <child2 slot="item"> </child2>
       <child3 slot="item"> </child3>
     </my-tag>

**Comment by fullfs** [comment]
@prog-rajkamal Hello! Good to see such detailed feature request. I can say its related to #1726 by now.

**Comment by prog-rajkamal** [comment]
@fullfs thanks.
it is related to https://github.com/vuejs/vue/issues/1726 as both deal with slot api. though https://github.com/vuejs/vue/issues/1726 proposal act through js while my feature request act through html. so they are actually complimentary.

**Comment by nothing628** [comment]
when this feature is finished?
but in my case, i want to bind some data to slot, this my code for parent component
```html
<template>
 <div class="parent">
  <div class="item" v-for="item in items">
   <slot :some-props="item"></slot>
  </div>
 </div>
</template>
<script>
 module.exports = {
  props: {
   items:[]
  }
 }
</script>
```
and template for child component
```html
<template>
 <div class="content" v-text="someProps"></div>
</template>
<script>
 module.exports = {
  props: {
   someProps: ''
  }
 }
</script>
```
so, i can write my component to html like this

```html
<my-comp :items="['one','two']">
 <child-item></child-item>
</my-comp>
```
i want ``<slot>`` can more flexible to bind another data

**Comment by simplesmiler** [comment]
@nothing628 you can not achieve this with slots currently in 1.x, but since 1.0.19 you can pass components as props: https://jsfiddle.net/simplesmiler/5p420nbe/

**Comment by nothing628** [comment]
thanks @simplesmiler , it solve my problem. I think it will take a long time

**Comment by yyx990803** [comment]
For 1.x, I think this is overly complex for an edge use case. For me it seems better to just wrap the slot in an element so that it works for element/text content alike.

In 2.x, you can programmatically inspect and modify slot content using `render` functions.
