### ISSUE TITLE
feature request: more built-in modifiers such as 'f1', 'shift', 'control'

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue#2512]
since now users can customize modifier keycodes, say, use `.f1` for `.112`, it would be nice to take this a little bit further, putting more modifiers into the default modifier list? for example:
`.f1` = `.112`
`.shift` = shift pressed down
`.alt` = alt pressed down
`.ctrl` = ctrl pressed down
`.meta` = window\meta pressed down

**Comment by yyx990803** [comment]
You can do that in 1.0.17+ like this:

``` js
// enable @keyup.f1
Vue.directive('on').keyCodes.f1 = 112
```
