### ISSUE TITLE
My style bindings are disappearing after production build

### ISSUE THREAD

**Issue by esahione** [vuejs/vue#2513]
My style bindings are not working after I build the code for production (I'm using the Webpack skeleton initially generated by vue-cli).

The code is for a simple parallax component - you can find it here: https://gist.github.com/esahione/6a7dc75f1dec971c4c06

Here's my Webpack production config file: https://gist.github.com/esahione/c8d75d51ff7e59b10d5a
And here's the Webpack development configuration file: https://gist.github.com/esahione/c305121816040f849547

The code should be self explanatory. It works flawlessly on development, but when I try to build it for production it stops working. In fact, when I look at the code through the browser there is no style tag.

Is this a bug? Am I doing something wrong?

**Comment by yyx990803** [comment]
Please report this to https://github.com/vuejs-templates/webpack instead.
