### ISSUE TITLE
v-bind:style 'background-image' error:  url is not a function

### ISSUE THREAD

**Issue by ziqianghe** [vuejs/vue#2514]
```
<template>
<div :style="{ 'background-image': url ( backgroundImage ) }">
</template>
<script>
data: {
  backgroundImage: 'http://image.com/image.png',
}
</script>
```

`// TypeError: scope.url is not a function`

**Comment by azad112358** [comment]
You can use `<div :style="{ 'background-image': 'url(' + backgroundImage + ')' }">` instead.
ref:[2352](https://github.com/vuejs/vue/issues/2352)

**Comment by GreenMelon** [comment]
it do work and help me out! THX

**Comment by jhonny111s** [comment]
works for me, 
in controller:

``` getUrlMap: function () {
            var url = "IMage or google map"
            return {
                'background-image': 'url("' + url + '")'
            }
        }```
in html:
```<div class="img" :style="getUrlMap(order.address)"></div> ```

**Comment by heziqiang** [comment]
Thanks

**Comment by kamil-kielczewski** [comment]
@jhonny111s your answer work for non-local url - thanks :)

**Comment by nizamdev** [comment]
:style='{ backgroundImage: "url(" + imgUrl + hotel.image.name + ")", }'

define imgUrl on data function

**Comment by salar80** [comment]
`<div class="img-banner" :style="{'background-image': 'url(' + require('./assets/media/baner1.jpg') + ')'}"></div>`

**Comment by Shujee** [comment]
What if my background is a gradient (`linear-gradient`) instead of an image? I'm basically trying to use a style where I could change element background color dynamically.

**Comment by neberaa** [comment]
What about template literals? Something like: 
```<div :style="{'background': `linear-gradient(#e66465, ${color_variable});`}"```

**Comment by Alinawaz-786** [comment]
I need your help when i was using the vue js get following error

app.js:106867 [Vue warn]: Error in v-on handler: "ReferenceError:
stripeResponseHandler is not defined"

found in

---> <MessagepackageslistComponent> at
resources/js/components/MessagePackagesList.vue
       <CreditdetailComponent> at
resources/js/components/CreditDetailComponent.vue
         <Root>
warn @ app.js:106867
logError @ app.js:108126
globalHandleError @ app.js:108121
handleError @ app.js:108081
invokeWithErrorHandling @ app.js:108104
invoker @ app.js:108421
original._wrapper @ app.js:113774
app.js:108130 ReferenceError: stripeResponseHandler is not defined
    at VueComponent.stripeResponse (app.js:4295)
    at invokeWithErrorHandling (app.js:108096)
    at HTMLFormElement.invoker (app.js:108421)
    at HTMLFormElement.original._wrapper (app.js:113774)
logError @ app.js:108130
globalHandleError @ app.js:108121
handleError @ app.js:108081
invokeWithErrorHandling @ app.js:108104
invoker @ app.js:108421
original._wrapper @ app.js:113774
(index):3 Uncaught Error: Your key is invalid, as it contains whitespace.
For more info, see https://stripe.com/docs/stripe.js
    at Function.b.validateKey ((index):3)
    at Function.b.create ((index):2)
    at Function.c.createToken ((index):2)
    at HTMLFormElement.<anonymous> (app.js:4222)
    at HTMLFormElement.dispatch (app.js:22950)
    at HTMLFormElement.elemData.handle (app.js:22757)


how to solved thie error

**Comment by VishalBty** [comment]
My workaround is to add the following method
`methods: {
    url(value) {
      return "url("+value+")"
    }
  }`
