### ISSUE TITLE
通过props传递Array后，getter获取出现异常

### ISSUE THREAD

**Issue by skyline0705** [vuejs/vue#2516]
### Vue.js version
1.0.18

### Reproduction Link

https://jsfiddle.net/5tz17aqx/2/

### Steps to reproduce
点击对应后面的-来移除元素
### What is Expected?
理论上对应元素应该正常删除
### What is actually happening?
点击通过props传递进来的list中的-，除了第一项，其他项均无法正常删除
点击通过data构造的list中的-，均可以正常删除

还没来得及深入跟踪源码，目测是通过props传递进来的list，在触发getter的时候没有返回对应的Observe Array导致出现问题。相关细节后续再具体补充一下

**Comment by ClassicOldSong** [comment]
改成这样：
···
data: (function () {
    return {
        list1: [11,22,33,44,55]
    }
})(),
···

**Comment by scottsut** [comment]
可以正常在1.0.16和1.0.17中运行，到了1.0.18就不行了

**Comment by ClassicOldSong** [comment]
Similar to #2520
