### ISSUE TITLE
vuejs router 页面不刷新问题

### ISSUE THREAD

**Issue by yangfeiloveG** [vuejs/vue#2522]
从A页面（url里带查询参数） 到B页面(利用A页面里查询参数ajax查询),再返回A页面，在进入B页面，B页面 不刷新（第二次竟然不发送任何ajax了），请问遇到这样的问题吗？

**Comment by yyx990803** [comment]
1. 此类问题请仔细阅读文档，然后去论坛提问。
2. router 的问题请到 vue-router 的仓库开 issue
