### ISSUE TITLE
Feature Request: Ability for executing functions before vm data change

### ISSUE THREAD

**Issue by littlstonee** [vuejs/vue#2523]
As we know, _$watch_ can be used to detect value change, but it is triggered after value changed.
Is that possible to provide some APIs for executing functions before data change? 

For example:

```
var prependCustomFunction=function(value){
	console.log('A.value will be changed to '+value);
};
var apppendCustomFunction=function(value){
	console.log('A.value was changed to '+value);
};
var A={
	_value:100,
	set value(value){
                //do something before  data change, is this possible?
		prependCustomFunction(value);
		this._value=value;
                 //do something after data change, this can be executed in $watch
		appendCustomFunction(value);
	}
}; 
```

**Comment by AStaroverov** [comment]
http://vuejs.org/api/#vm-watch
U can use option immediate for watch for this case.

пн, 21 марта 2016 г., 9:13 littlstonee <notifications@github.com>:

**Comment by littlstonee** [comment]
@AStaroverov 
Thanks for your replay!
Option immediate can be used to trigger $watch callback immediately after callback registered, but I need trigger a function every time before watch expression change, so may be this option can not help me.
Maybe still other ways to modify vm data setter? 
Thanks again.

**Comment by fullfs** [comment]
@littlstonee Hello!
You could use something like mirrored values, like this: https://jsfiddle.net/kk1rxm73/12/

By the way, please note you could as for tips in [Forum](http://forum.vuejs.org/) if you're not sure about feature capability. It's probably better to write there first and if there is not workaround, to post an issue with a feature request :)

**Comment by blake-newman** [comment]
Could 'computed' values,  with a set option resolve this issue for you? Could you post a small example of the code surrounding your needs so we can try to evaluate your use case.

**Comment by littlstonee** [comment]
@fullfs 
Thanks for your tip!
I  redesigned my component based on your mirrored solution, and it works well now.

And also, thanks for your kindly note.
