### ISSUE TITLE
modify array and the view update problem

### ISSUE THREAD

**Issue by LoeiFy** [vuejs/vue#2525]
### Vue.js version
1.0.17

### Reproduction Link
https://jsfiddle.net/am0200/t7mksmnj/3/

### What is actually happening?

i am not sure this is my code problem

you can see the demo: https://jsfiddle.net/am0200/t7mksmnj/3/

when click `click me`, the `click me` should be `new`, but not

when `click me too`,  the `click me too` should be `new` ，it works

but the code do the same thing: 

```js
// not ok
this.items[index] = p;

// ok
this.items.splice(index,1,p)
```

why the view not update on the first

**Comment by fullfs** [comment]
@LoeiFy Hello! Please read https://vuejs.org/guide/list.html#Caveats

**Comment by LoeiFy** [comment]
@fullfs thanks

**Comment by fullfs** [comment]
@LoeiFy You're welcome! If you have any questions left you may post it on the [Forum](http://forum.vuejs.org/)
P.S. Sorry if you felt any dryness from my previous answer :)

**Comment by LoeiFy** [comment]
@fullfs 
i am ok, you are right.
i am a starter on vue, and haven't read the document carefully.
there is too much documentation, and i begin vue width vue examples
