### ISSUE TITLE
关于组件通信

### ISSUE THREAD

**Issue by xcheese** [vuejs/vue#2527]
hello，请问：
比如body下有A、B两组件，实现body上委托鼠标经过A的位置弹出B，怎么在commonJS的方式下，通信呢。。是只有dispatch->parent上然后再broadcast这一种方式吗

**Comment by phanan** [comment]
你好。这种问题，请在[论坛](http://forum.vuejs.org/)或是[Gitter](https://gitter.im/vuejs/vue)问。谢谢。
