### ISSUE TITLE
Component watch in 1.0.18

### ISSUE THREAD

**Issue by vladra** [vuejs/vue#2529]
Hi guys!

I've encountered a problem after upgrading to 1.0.18 with `watch` inside component. Same code that was working in 1.0.17 stopped triggering events. I've checked release update note, but found nothing related there.

I've tried to create something similar in jsfiddle to reproduce my issue (my code is very different though and is difficult to reproduce exactly in jsfiddle)

So, this fiddle is using 1.0.17 version and is triggering watch events as intended:
https://jsfiddle.net/vladra/2Le9erop/2/

And this is exactly same fiddle using 1.0.18, which is not triggering watch events (and actually it doesn't see changes to props at all):
https://jsfiddle.net/vladra/4ynoyvf0/2/

Thanks for looking into this issue

**Comment by yyx990803** [comment]
This is a known issue and has been fixed - in particular it's about props with inline values not being reactive: https://github.com/vuejs/vue/commit/30e9edaf8e14c34f8742a7098c7ae37272c83e55
