### ISSUE TITLE
error when build vue code

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue#2531]
### Vue.js version
v1.0.13

### VueRouter.js version
v0.7.11

### Reproduction Link
[src mode](http://vue-demo.erguotou.me/demo/abc)
[build mode](http://vue-demo-uglify.erguotou.me/demo/abc)

### Steps to reproduce
A(src mode):
1. click `go to add`
2. click `go to edit`
3. click `go to add`
Everything goes OK
B(build mode):
1. click `go to add`
2. click `go to edit`
3. click `go to add`
The add page contains the edit data.

### What is Expected?
Build code runs the same with the src code.

### What is actually happening?
In build mode, the add page contains the edit data.

### P.S.
In my project I use [coolie](https://github.com/cooliejs/coolie-cli), a frontend build cli, not webpack.
Hope you can answer, thk.

**Comment by phanan** [comment]
Isn't the "src mode" page totally blank?

**Comment by yyx990803** [comment]
There's no information about your build setup... what do you mean by src mode? what do you mean by build mode? It seems to be more like an problem in coolie. Please open new issue when you have more information available.

**Comment by erguotou520** [comment]
Sorry for not detailed information. Src mode means code in develop mode, no build. Build mode means  production mode, with uglify, concat.   
And the repository is https://github.com/erguotou520/vue-coolie-demo, the `src` directory is the src mode, links to http://vue-demo.erguotou.me/demo/abc, the `dest` directory is the build mode, links to http://vue-demo-uglify.erguotou.me/demo/abc
