### ISSUE TITLE
Feature request, download missing module

### ISSUE THREAD

**Issue by robertleeplummerjr** [vuejs/vue#2533]
I want to detect if a directive is missing, when it is, I'd like a callback to try and download it.  After looking at source, most of the functions are private and simply cannot, but I could be missing something.

I have searched for this, and as well asked in chat, I didn't get a response.

**Comment by skyronic** [comment]
I don't think you can detect a missing directive and lazy load it. Have you looked into [code splitting](https://webpack.github.io/docs/code-splitting.html) ?

**Comment by robertleeplummerjr** [comment]
I have.  I believe the functionality doesn't exist, but could easily be implemented as a setting perhaps.

**Comment by Nirazul** [comment]
Do you have a use case for this? When would this behaviour be useful?
It's possibly dangerous if somebody would place some malicious code into a directive called `vue-laoder` when you accidentally typed this instead of `vue-loader`.

**Comment by yyx990803** [comment]
But why? I think lazy-loading directives is too granular (introduces too much implementation/usage complexity for very little gain). I think we should keep async loading at component level.

**Comment by robertleeplummerjr** [comment]
Use case:  A crm with 100 directives, and only 2 or 3 are being used on
different pages.  Likely it would be more efficient to load only what is
needed, not the entire set of directives.

It would load just be an optional callback, so it can be handle wherever
vue is being used.

On Tue, Mar 22, 2016 at 11:52 AM, Nirazul <notifications@github.com> wrote:

> Do you have a use case for this? When would this behaviour be useful?
> It's possibly dangerous if somebody would place some malicious code into a
> directive called vue-laoder when you accidentally typed this instead of
> vue-loader.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vuejs/vue/issues/2533#issuecomment-199877256>
>



-- 
Robert Plummer

**Comment by fullfs** [comment]
@robertleeplummerjr you could have those directives each in a single module (file), then just import those are needed into a component where you need it to use. If you use any webpack based loading system your js-bundles will be filled only with those directives you've actually imported.

**Comment by robertleeplummerjr** [comment]
Thanks guys for your stellar feedback.  After careful consideration, I believe I'm going to have the process pull in the needed directives before vuejs processes the script here: https://github.com/Enpowi/Enpowi/blob/master/src/client/Enpowi/App.js#L321
.  I must say, vuejs is pretty fantastic, here is a blog post handler for Enpowi: https://github.com/Enpowi/Enpowi/blob/master/modules/blog/index.php#L32

For work I've had my head buried in React/Redux, and although it does a fine job, vuejs w/ Enpowi seems to do the same thing in hardly any lines:  29 lines of data setup, 47 line for user interface, 0 lines of sadness.

Thanks again guys!
