### ISSUE TITLE
[Suggestion for Performance] `.once` directive argument for v-for, :class etc

### ISSUE THREAD

**Issue by rstoenescu** [vuejs/vue#2535]
It would be great if all Vue directives would support `.once`: `v-for.once`, `:class.once`, `v-if.once` for situations where you know the binded data won't change. I imagine this will increase performance.

**Comment by yyx990803** [comment]
Sounds like a good idea.

**Comment by blake-newman** [comment]
Idea is nice! Additionally would it be good to allow this API level of the directive, for custom directives that may only ever need a single bind. 

```
{
  once: true,
}
```

**Comment by yyx990803** [comment]
@blake-newman if you supply only `bind` without `update` then it is "once" already :)

**Comment by blake-newman** [comment]
@yyx990803  Very true.. doh! We have now implemented this into 2.0, and the plan is to keep this functionality to 2.0 only.

Closing: @vuejs/collaborators reopen if there is a change of plan.

**Comment by liming9515** [comment]
This proposal has been accepted yet?

**Comment by posva** [comment]
Not in Vue 1. In Vue 4 you have [`v-once`](http://rc.vuejs.org/api/#v-once)
