### ISSUE TITLE
Transitions Not Firing

### ISSUE THREAD

**Issue by dolbex** [vuejs/vue#2536]
Evan,

It seems like I'm running into an issue with a parent changing a property of a child component and it not firing off the transitions of any v-show / v-if's in that child component that lean on that property. 

In the following example when you click on the TicketTemplate it will hide the ticket summary (red background) by changing the isActive property of that component and sets a timeout that changes the isActive property of the TicketExpanded component. This should fade the middle-content in (blue background) but it just pops in that first time. Subsequent edits to that element using devtools or codepen's editor will show the 5s transition. 

I've done my best to try and recreate this with the following codepen: http://codepen.io/dolbex/pen/BKRzye

*Structure: *
Ticket 
  - TicketSummary
  - TicketExpanded

**Comment by phanan** [comment]
As this is more like a question than a bug report, I'd suggest asking on the forum or [Gitter](https://gitter.im/vuejs/vue). I'm sure the folks (me included) will be happy to help you there.
