### ISSUE TITLE
Error: nextSibling of null

### ISSUE THREAD

**Issue by xueenda** [vuejs/vue#2537]
There is a wired bug in latest vue. Everything is OK when clicking on tabs slowly. Keep switching between tags, if clicking too fast without the previous transition finished there will be a redirect loop. 

Here is the sample code:
[https://github.com/xueenda/vue-redirect-loop](https://github.com/xueenda/vue-redirect-loop)

It's better to test on phone with both fingers tabbing fast on the footer tab.

Here is the screenshot of the error:
[https://raw.githubusercontent.com/xueenda/vue-redirect-loop/master/page1.pic.jpg](https://raw.githubusercontent.com/xueenda/vue-redirect-loop/master/page1.pic.jpg)
[https://raw.githubusercontent.com/xueenda/vue-redirect-loop/master/error.pic_hd.jpg](https://raw.githubusercontent.com/xueenda/vue-redirect-loop/master/error.pic_hd.jpg)

**Comment by yyx990803** [comment]
Please move this to `vue-router`'s repo instead.
