### ISSUE TITLE
change event triggers twice when my component contains a radio input and dispatches a event naming 'change'

### ISSUE THREAD

**Issue by airyland** [vuejs/vue#2538]
### Vue.js version
Latest

### Reproduction Link
http://output.jsbin.com/najukaquko/

### Reproduction Step

Change the radio value

### What is Expected?

Change event should trigger once.

### What is actually happening?

Change event triggers twice, one maybe dispatched by the radio input and the other is dispatched manually by my component.

``` js
change `1`
change `Event Object`
```

**Comment by airyland** [comment]
I found `.stop`in the document and fix it by adding:

``` js
@change.stop
```
Is this a proper way?

**Comment by carlosingles** [comment]
I made a few modifications to your component, I believe you were listening to the change event twice:

HTML:
``` html
<script type="vue/template" id="tpl">
    <div>
       my-component
      <input type="radio" name="radio1" v-model="value" value="1" @change="change"/>
      <input type="radio" name="radio1" v-model="value" value="2" @change="change"/>
    </div>
</script>
<div id="demo">
  <my-component></my-component>
</div>
```

JS:
``` js
var component = Vue.component('my-component', {
  template: document.querySelector('#tpl').innerHTML,
  data: function (){
    return {
      value: '1'
    };
  },
  methods: {
    change: function(event){
      console.log('change', event);
      console.log('value', this.value);
    }
  }
});

var vm = new Vue({
  el: '#demo'
});
```

**Comment by airyland** [comment]
@carlosingles But if I want to  listen to the change event on parent vm, it still trigger twice.

https://jsbin.com/tilaru/edit?html,js,output

**Comment by carlosingles** [comment]
You should be listening to any dispatch events through the `events` property, not the `methods`, try the following:

HTML:
``` html
<script type="vue/template" id="tpl">
  <div>
     my-component
    <input type="radio" name="radio1" v-model="value" value="1" @change="change"/>
    <input type="radio" name="radio1" v-model="value" value="2" @change="change"/>
  </div>
</script>
<div id="demo">
  <my-component></my-component>
</div>
```

JS:
``` js
var component = Vue.component('my-component', {
  template: document.querySelector('#tpl').innerHTML,
  data: function (){
    return {
      value: '1'
    };
  },
   methods: {
    change: function(event){
      this.$dispatch('change', this.value);
    }
  }
});

var vm = new Vue({
  el: '#demo',
  events: {
    change: function(val){
      console.log('change', val);
    }
  }
});
```

**Comment by airyland** [comment]
@carlosingles You are right. But what if there are more than one child component dispatching the change event? I cannot distinguish which component dispatches the event.

**Comment by carlosingles** [comment]
You could pass a reference to the component through the dispatch event, but this is probably not a good idea.

What are you trying to achieve? Perhaps holding the model on the main component and then passing the values via [props](http://vuejs.org/guide/components.html#Props) would be a better approach, since then you could manage all the values from the parent component and you could assign each model to a component.

For example, I have a Form component which manages all values that then get passed via props to the different Input components, I don't have to watch for value changes since they're automatically updated

**Comment by rhyzx** [comment]
@airyland is this issue related? https://github.com/vuejs/vue/issues/2367 , you need rename your component event name to avoid conflict with DOM event name, `@event` will listen to both component event and DOM event.

**Comment by airyland** [comment]
@carlosingles  Watching the value of child component is a normal usage.. The main problem is the event name just conflicts with DOM event, and if I change event name to `valueChange` will fix that.

@rhyzx I think so. Component event name may conflict  with DOM event. 
Close it for the moment.
