### ISSUE TITLE
this.$http is not a function

### ISSUE THREAD

**Issue by gdzgshum** [vuejs/vue#2539]
main.js
import Vue from 'vue'
import VueResource from 'vue-resource'
import './config/router'

Vue.config.debug = false
Vue.use(VueResource)

Vue.http.options.headers={
    'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'
};
Vue.http.options.crossOrigin = true
Vue.http.options.xhr = {withCredentials: true}

index.vue:
export default {
  data () {
    return {
    }
  },
  ready () {
    
  },
  methods: {
   fetch: function (next) {
      var url = 'xxx.com'
      var that = this
      this.$http({url: url, method: 'GET'}).then(function (response) {
        that.items = data
        next()
      }, function (response) {
          console.log(response)
      });
    },
  },
  route: {
    activate ({ transition }) {
      this.fetch( function() {
        transition.next();
      })
    }
  }
}

why?

**Comment by phanan** [comment]
Please ask on the forum or Gitter. Repo issues are exclusively for bug reports and feature requests, as stated in both [contribution guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) and [issue template](https://raw.githubusercontent.com/vuejs/vue/dev/issue_template.md). Thanks.
