### ISSUE TITLE
Vue changes the nested structure of HTML for some elements

### ISSUE THREAD

**Issue by JackGit** [vuejs/vue#2541]
### Vue.js version
1.0.16

### Reproduction Link
[JSFiddle][1]

  [1]: https://jsfiddle.net/ygjack/8o8LLLg0/

### Steps to reproduce
For some element like `li`, `a`, Vue would change the nested structure while parsing the template. But the issue is not there for elements like `div`, `span`. 
For example, i have a template like this:
```
...
  <a>outer archor
    <span>
      <a>inner archor</a>
    </span>
  </a>
...
```

### What is Expected?
And I expected output HTML structure as below:
```
...
  <a>outer archor
    <span>
      <a>inner archor</a>
    </span>
  </a>
...
```
### What is actually happening?
But actually I got this:
```
<a>outer archor
    <span></span>
</a>
<a>inner archor</a>
```

**Comment by yyx990803** [comment]
This has nothing to do with Vue..... you cannot nest `<a>` inside itself.

https://jsfiddle.net/8o8LLLg0/4/

**Comment by phanan** [comment]
If you really want/have to, you can use a trick (refered by Vitaly Friedman of SmashingMagazine as "dirty"), like this:

```html
<a class="outer">Lorem <object><a class="inner">ipsum</a></object></a>
```

I wouldn't recommend it though.

**Comment by JackGit** [comment]
`<a>` nested case is not mine. I though this would be an easy example. 
My case is nested list. Any suggestions?
https://jsfiddle.net/ygjack/8o8LLLg0/

**Comment by fullfs** [comment]
@JackGit It also has nothing to with Vue. You've got an invalid html when using ```<li><collapsible><li><slot></slot></li></collapsible></li>``` template. You've got ```li``` inside ```li``` there. Please note that a browser will parse the html before it's compiled by Vue. So your templates should valid html before compilation.

I've fixed the example to get it work right:
https://jsfiddle.net/8o8LLLg0/9/
