### ISSUE TITLE
Suggestion: Allow to pass named slots from nested components

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue#2542]
Imagine I have a `main-view` component:
```html
<template>
  <header>
      <slot name="header">
         <default-header></default-header>
      </sloot>
  </header>
  <main class="content-container">
     <slot name="content">
         <h1>404</h1>
         <p>There is no content. Sorry!</p>
     </slot>
  </main>
</template>
```

And I need to dynamically switch slots from the other components. 

In that case my App component should look like:
```html
<template>
  <main-view>
     <component :is="currentView"></component>
  </main-view>
</template>

<script>
  export default {
    data {
      currentView: 'index'
    }
  }
</script>
```
And index component:
```html
<template>
  <div slot="content">
   ...
  </div>
<template>
```

For now it is possible to use only one content insertion point. So named slots from nested component are not supported. My suggestion is to allow (some-way) to export components slots to the parent component.

What are your thought on this?

**Comment by OEvgeny** [comment]
I thought about this little bit more. Now it's not sound like a good idea. I found that usually I don't want my components to be split by parent. I also don't want to store two parts which I can separate from each other in one component. 

I closing this for now. Feel free to reopen anyway :)

**Comment by tsunamilx** [comment]
Is there workaround for this?

**Comment by OEvgeny** [comment]
@tsunamilx I guess [named router views](https://router.vuejs.org/en/essentials/named-views.html) can solve this problem.
