### ISSUE TITLE
Nested li element structure changed

### ISSUE THREAD

**Issue by JackGit** [vuejs/vue#2543]
### Vue.js version
1.0.16

### Reproduction Link
[JSFiddle][1]

  [1]: https://jsfiddle.net/ygjack/8o8LLLg0/

### Steps to reproduce
For some element like `li`, `a`, Vue would change the nested structure while parsing the template. But the issue is not there for elements like `div`, `span`. 
For example, i have a template like this:
```
...
  <div id="mountNode">
  <menu>
    <menu-item>item 1</menu-item>
    <menu-item>item 2</menu-item>
    <menu-collapsible-item>
      <collapsible-header>header</collapsible-header>
      <collapsible-item>c item 1</collapsible-item>
      <collapsible-item>c item 2</collapsible-item>
    </menu-collapsible-item>
  </menu>
</div>
...
```
and components:
```
Vue.component('collapsible', {
  template: '<ul><slot></slot></ul>'
})

Vue.component('collapsible-header', {
  template: '<div class="header"><slot></slot></div>'
})

Vue.component('collapsible-item', {
  template: '<div><slot></slot></div>'
})

Vue.component('menu', {
  template: '<ul><slot></slot></ul>'
})

Vue.component('menu-item', {
  template: '<li><slot></slot></li>'
})

Vue.component('menu-collapsible-item', {
  template: '<li><collapsible><li><slot></slot></li></collapsible></li>'
})
```

### What is Expected?
And I expected output HTML structure as below:
```
<ul>
  <li>item 1</li>
  <li>item 2</li>
  <li>
    <ul>
      <li>
        <div class="header">header</div>
        <div>c item 1</div>
        <div>c item 2</div>
      </li>
    </ul>
  </li>
</ul>
```

### What is actually happening?
But actually I got this:
```
<ul>
   <li>item 1</li>
   <li>item 2</li>
   <li>
      <ul></ul>
      </li><li>
      <div class="header">header</div>
      <div>c item 1</div>
      <div>c item 2</div>
   </li>
</ul>

```

**Comment by blake-newman** [comment]
Hello, 

Your HTML structure you are trying to create is not valid. As you have nested `li`'s. This is why you get odd results.

To achieve the structure you want you can remove the wrapping `li` from the `menu-collapsible-item`: 
```
Vue.component('menu-collapsible-item', {
  template: '<collapsible><li><slot></slot></li></collapsible>'
})
```

**Comment by JackGit** [comment]
but it's valid and display correctly with raw html:
```
<ul>
  <li>item 1</li>
  <li>item 2</li>
  <li>
    <ul>
      <li>
        <div class="header">header</div>
        <div>c item 1</div>
        <div>c item 2</div>
      </li>
    </ul>
  </li>
</ul>
```

**Comment by blake-newman** [comment]
@evan do you have any opinion on why this may be happening.

**Comment by blake-newman** [comment]
@jackbit

Just to clarify,  Vue uses a standard html parser to generate the html.  The reason your html works as a standalone unit,  because the browsers in use will cleverly interpretate it.  

Using this html structure you could get unexpected results in other browsers that are not so clever. This is why having nested `li` without a `ul/ol` won't work with Vue as you intend.  

This may feel like a caveat to Vue. However this comes with a benefit - as it respects standard DOM interpretation.
