### ISSUE TITLE
[feature] Add component strategy for v-model

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vue#2544]
Just formalizing [these](https://github.com/vuejs/vue/issues/2428#issuecomment-193020645) comments as a feature request.

There seem to be some common pitfalls with two-way data binding, and you've expressed a desire to deprecate it. Currently though, there is at least one good use case for `.sync`, which revolves around higher level input components. eg:

- split value inputs (date/time, feet/inches)
- wrappers around existing input libraries (select2)
- [vue-select](https://github.com/sagalbot/vue-select)
- [vue-datepicker](https://github.com/hilongjw/vue-datepicker)

Adding a component strategy for v-model would reduce the need for the `.sync` modifier while providing a nicer API for input-like components.

**Proposal:**
Use `model` as a component option that behaves similarly to a single value `props`. 
- signals that the component is compatible with v-model
- the bound value is stored in the property specified by model.

**Example component:**
```html
<!-- height.html -->
<input type="number" min="0" v-model="feet" number />
<input type="number" min="0" max="11" v-model="inches" number/>
```
```js
// height-input.js
import template from './height.html';

export default {
  name: 'height-input',
  model: 'value',
  template: template,

  data: function() {
    return {
      feet: this.value ? Math.trunc(this.value / 12) : '',
      inches: this.value ? this.value % 12 : '',
    };
  },
  ...

};
```

**Example usage:**
```html
<!-- form.html -->
<height-input v-model="user.height"></height-input>
```

**Comment by yyx990803** [comment]
How would you sync the value back up in your example? You need some way to convert the computed feet and inches back into `user.height`.

**Comment by rpkilby** [comment]
Yep - just snipped the example for brevity. There might be a better way, but we used a series of watchers. It looks like [vue-select](https://github.com/sagalbot/vue-select/blob/master/src/components/Select.vue#L265-L278) does the same thing.

```js
import Vue from 'vue';
import template from './templates/height.html!text';


export default Vue.extend({
    props: ['model'],
    template: template,

    data: function() {
        return {
            feet: this.model ? Math.trunc(this.model / 12) : '',
            inches: this.model ? this.model % 12 : '',
        };
    },

    watch: {
        feet: function(value) {
            this.model = (12 * value) + this.inches;
        },

        inches: function(value) {
            this.model = (12 * this.feet) + value;
        },

        model: function(value) {
            // Compare the incoming value to a computed value. If they're not the
            // same, this indicates that the incoming value was set externally by
            // the parent Vue or otherwise.
            const inputHeight = (12 * this.feet) + this.inches;
            if (value !== inputHeight) {
                this.feet = Math.trunc(this.model / 12);
                this.inches = this.model % 12;
            }
        },
    },
});
```

**Comment by paulpflug** [comment]
I think this is a cool feature, as it brings consistency to user generated input-components with very little cost.
I would suggest a very simple implementation:
when `model: someName` is set in the component
let `v-model` be a shorthand for `v-bind.sync:someName`

**Comment by fullfs** [comment]
IMO it will bring more confusion than profit. Can't see any problem using `:prop.sync` here. To my POV it's just like "I want it to look like a real input". Way too subjective :)

**Comment by rpkilby** [comment]
@fullfs There isn't any problem with the `:prop.sync` syntax except that there seems to be some push to deprecate it.

**Comment by yyx990803** [comment]
@rpkilby it's just a thought at the moment, not happening until v2 (which means not in the near future)

**Comment by paulpflug** [comment]
I think this should atleast be considered.
Advanced input fields usually have numerous props, here from `vue-select`:
```html
<vue-select  options="options" :value.sync="value" searchable="false" multiple placeholder="text" clearSearchOnSelect="false"></vue-select>
// vs.
<vue-select options="options" v-model="value" searchable="false" multiple placeholder="text" clearSearchOnSelect="false"></vue-select>
```
the change is small but when you imagine to review the code 2 month later you can profit from the `v-model` convention.

The other benefit would be the implicit naming convention. Imagine you have 4 or 5 different advanced input fields and they all use different names for the same thing: `:value.sync`,`:text.sync` , `:content.sync`, `:data.sync`, etc. 

you would save many round trips of doc reading to recall which component uses which name for its value..

**Comment by fullfs** [comment]
@paulpflug If you write down you tag attributed in a column, there is not problem reviewing it:

```html
<vue-select 
    :options="options" 
    :value.sync="value" 
    searchable="false" 
    multiple 
    placeholder="text"
></vue-select>
```

It looks even better if you use `jade`:
```jade
vue-select(
    :options="options",
    :value.sync="value",
    searchable="false",
    multiple ,
    placeholder="text"
)
```

I'm working on large-scale project based on Vue with a number of developers. We didn't have any problem understanding component props in any way even if its is written by another developer.

Well, there might be something behind the idea. I just don't see it from my experience, sorry =)

**Comment by buyzhi** [comment]
作者你好

**Comment by yyx990803** [comment]
This is already implemented in 2.0.

**Comment by rpkilby** [comment]
Sweet - will this also be backported to 1.1?

**Comment by yyx990803** [comment]
@rpkilby unlikely, but we'll see

**Comment by rpkilby** [comment]
If anyone else was looking for the Vue 2.0 [syntax](https://github.com/vuejs/vue/issues/2873#issuecomment-223759341)..

**Comment by iagafonov** [comment]
For vue components `v-model="someModel"` as I understand from Vue 2.0 livestream is simple syntax sugar for this:
`<some-component :value="someModel" @input="someModel = $event.target.value""></some-component>`
And nothing warry about, because this is only internal vue component event (without dom events), but for select, textarea and input tags I guess v-model does more than simple binding to input event, so
`<input type="text" :value="someModel" @input="someModel = $event.target.value"">`
will work, but without binding to some extra dom events and value conversion for input type="number" and other stuff.
For now I see that if I want basic html inputs works well in one-way binding style i need to reimplement some v-model internal logic. May be it is possible to divide v-model event binding into separate special complex event like this:
`<input type="text" :value="someModel" @v-model="someModel = $event.target.value">`
to be sure that v-model is only syntax sugar for that from above
Or maybe I have misunderstood something...
