### ISSUE TITLE
$route.query is incorrect for particular string input

### ISSUE THREAD

**Issue by dk020130** [vuejs/vue#2546]
the url: http://domain.com/abc/index.html?token=8RiDvDd-NS26yuSrrpqdnw==
"8RiDvDd-NS26yuSrrpqdnw==" is a valid url parameter value (rfc4648 base64 url safe);
but $route.query.token is "8RiDvDd-NS26yuSrrpqdnw";

**Comment by blake-newman** [comment]
Please open an issue with a reproduction link at: https://github.com/vuejs/vue-router
