### ISSUE TITLE
How to pass component as props?

### ISSUE THREAD

**Issue by loujiayu** [vuejs/vue#2548]
I'm looking for a way to pass component as props ,something like in react:
`<parent-component  child={<child-component />} />`

How to do this in vue?
Thanks

**Comment by taoche** [comment]
http://vuejs.org/guide/components.html#Props

**Comment by phanan** [comment]
I don't think you can do such a thing (passing components as props) in Vue. Props are meant for data only (even though I would imagine you can pass a template string and construct a component with it). I'd suggest reading [Vue components](http://vuejs.org/guide/components.html) to structure your app flow the Vue way instead.

**Comment by simplesmiler** [comment]
Also there are [slots](http://vuejs.org/guide/components.html#Content-Distribution-with-Slots).
``` html
<parent-component>
  <child-component></child-component>
</parent-component>
```

**Comment by fullfs** [comment]
@loujiayu Hello! By the way, please note you could use either [Gitter](https://gitter.im/vuejs/vue) or [the official forum](http://forum.vuejs.org/) for simple questions :)

**Comment by loujiayu** [comment]
@fullfs ok

**Comment by blocka** [comment]
I've done this before
```<parent-component child={() => <child-component />} />```

**Comment by blocka** [comment]
I would also disagree with the notion that props are only for data. I think we'll all agree that it's perfectly normal to pass functions. Vue 1.0 allowed passing component constructors as well.

A component is a black box, much like any function. It takes inputs (props) and outputs a vdom. Nothing there says props are "data".

**Comment by fnlctrl** [comment]
@blocka props can indeed pass functions as of 2.0, though it's not documented anymore.

**Comment by blocka** [comment]
I know you can...I was just ranting off against the props is data comment.

**Comment by LinusBorg** [comment]
Well, props are "meant" for data in the sense that Vue's conventions rely on events to register callbacks, even more so in 2.0. You *can* pass a callback as a prop, Vue just encourages to seperate the two mechanisms:

    <child :prop="dataDown" @change="callbackHere"></child>

That being said, even with respect to this convention there are scenarios where passing down a function is completely valid.

And passing a component config object to be used in a funtional component is also a common pattern in 2.0
