### ISSUE TITLE
Issue with hot-reload and nested routes

### ISSUE THREAD

**Issue by sergeymorkovkin** [vuejs/vue#2550]
I'm having a common admin panel application with nested routes for the layouts. This way, in my application template I have \<router-view\> only. Also, there is a Layout component, which has another \<router-view\>. This way, I'm trying to have this:

- /login
- /account/home
- /account/users

It all works perfectly unless I try modify Layout.vue (which should be turned on by the /account/ part). On every hot reload it duplicates Layout.vue's template in the DOM. As many times as I change the Layout.vue.

Tried playing with canReuse with no luck. Also, it appears that router mixes \<router-view\>
 tags up. Instead of working with parent one it uses the one inside the Layout.vue's template.

Am I doing something wrong?

**Comment by yyx990803** [comment]
This is related to `vue-router` and `vue-loader` - please open this at vue-router's repo instead, ideally with actual code reproduction.

**Comment by mrzzcn** [comment]
@sergeymorkovkin do you fix it?

**Comment by sergeymorkovkin** [comment]
Haven't fixed it. Trying to find some time to create proper ticket in the right repo with demo project...

**Comment by antoniputra** [comment]
@sergeymorkovkin do you fix it? I have exactly issue like yours.

**Comment by sergeymorkovkin** [comment]
Not yet. A workaround might be not using vue-router and replace it with <component is="...">.

**Comment by zheeeng** [comment]
Encounter the same problem.
