### ISSUE TITLE
使用jQuery on事件问题

### ISSUE THREAD

**Issue by cancanyang** [vuejs/vue#2552]
当jQuery存在时Vue会使用jQuery的on等事件，但on操作jQuery 1.7+版本才引入。所以使用1.7版本以下的会导致出错

**Comment by yyx990803** [comment]
你用的旧版本的 Vue 吧。最新版本修正过这个问题。

**Comment by cancanyang** [comment]
确实，我用的版本是1.0.10，刚看新版本已经修复了这个问题。谢谢了，回复也很及时，感谢了。
