### ISSUE TITLE
Wrapping component.

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2554]
Hi, I have some case but I can't find solution for this.
I need to wrap a component to some simple template without miss scope.
It should be like $(component).wrap(template), but as I understand jq or native way for wrap can break rerender template. 
I think that best is to choose partials with use <slot> ,  but <slot> doesn't work with partials. Have vuejs a legal solution for this?

**Comment by imaia** [comment]
Create a component that listens to a "hide" event. When the child component does not have any data, dispatch the hide event and hide the whole thing. That's how I do it. Works fine.

**Comment by FadyMak** [comment]
Hi @AStaroverov! Please use [Gitter](https://gitter.im/vuejs/vue) or the [official forum](http://forum.vuejs.org/) for questions.
