### ISSUE TITLE
Dynamic Components NameMap API

### ISSUE THREAD

**Issue by banricho** [vuejs/vue#2555]
When I use **Dynamic Components**,  I need to get the Components Name Map.

```JS
`<component
:is="currView"
keep-alive></component>`
```

```JS
components: {
  'popfood': Popfood,
  'hightea': Hightea,
  'mnsnack': Mnsnack
}
```

```JS
computed: {
  // read tab keys
  viewList() {
      return Object.keys(this.$options._componentNameMap); // <==
  },

  // show current tab
  currView() {
    return this.viewList[this.currTab];
  }
}
```
```JS
const tabNum = this.viewList.length; // <==
```

It works in the development version but not in the production version. So I print `this.$options` and find `_componentNameMap` is just a private API. 

Then I print `this.$options`, there's no open API (in the production version) to get Dynamic Components NameMap immediately. 

I think it is useful. Could I get it?

Thanks very much.

**Comment by yyx990803** [comment]
Why? You can just do `<component :is="currTab">`... the NameMap is used only for detecting possible misuse of component tags, you don't need it at all for dynamic components.

**Comment by banricho** [comment]
我换个语言表述一下，见谅 -。-

是这样的，currTab 是 Number，由外部传入（比如 menu）。

外部的 menu 只会传入它的 $index，这样就减少了和 tab 部分的耦合。当我新增 tab 页的时候，只需要在 menu 上新增一个按钮，而并不需要再添加对应的 tabName。

同样的，在进行触摸事件绑定的时候，我也需要知道 tab 的数量（不过这个可以用 this.$options. _context.$children 获得）（这个也不是公开的 API）

**Comment by yyx990803** [comment]
不建议这样随便依赖内部 API，因为随时可能改的。

但是组件注册是有稳定 API 的，用 `Object.keys(this.$options.components)`
