### ISSUE TITLE
Partial in the table

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2556]
### Vue.js version
1.0.18

### Reproduction Link
https://jsfiddle.net/nx4ffts3/

### Steps to reproduce
Open jsfiddle

### What is Expected?
partial 'td' in the tr

### What is actually happening?
partial 'td' is out from table

**Comment by jonagoldman** [comment]
probably related to this: http://vuejs.org/guide/components.html#is-attribute

> Some HTML elements, for example <table>, have restrictions on what elements can appear inside them. Custom elements that are not in the whitelist will be hoisted out and thus not render properly. In such cases you should use the is special attribute to indicate a custom element.

**Comment by AStaroverov** [comment]
Yes, but ``is`` doesnt work for partial.

**Comment by fullfs** [comment]
@AStaroverov Hello!
@jonagoldman You're right.

The thing is: browser will parse the html before it's compiled by Vue. So your templates (it's same for both partials and components) should valid html before compilation.
Browser won't allow anything else than `<td>` tag inside `<tr>` so `<partial>` got moved outside the table.

You probably can't use a partial inside `<tr>`. Consider using a component.
