### ISSUE TITLE
$data props is no longer available in created step in 1.0.18

### ISSUE THREAD

**Issue by imaia** [vuejs/vue#2557]
In version 1.0.17, I've got some code where the child component accesses a prop passed down from the parent component during created. In 1.0.18, it no longer works. What happened? Is this a bug? Is this a bug fix? 

<div id="parent">
<div is="child" :my-prop="value">

</div>
</div>

```coffee
new Vue
  el: "#parent"
  data: -> {value: 1}
  components:
    child:
      props: ['myProp']
      created: ->
        console.log @$data.myProp
```

**Comment by simplesmiler** [comment]
This is an unintentional breaking change, you can read more here: https://github.com/vuejs/vue/issues/2520#issuecomment-199082346
Note that you can access props and data without `$data`. This should work in your case:
``` coffee
new Vue
  el: "#parent"
  data: -> {value: 1}
  components:
    child:
      props: ['myProp']
      created: ->
        console.log @myProp
```

**Comment by imaia** [comment]
Thanks @simplesmiler
