### ISSUE TITLE
component $watch 'data'. How do I know what variable changed?

### ISSUE THREAD

**Issue by happilymarrieddad** [vuejs/vue#2558]
Hey guys, I was wondering if there is a way to know what specifically changed when watching $data. 
```
var SettingsAssetsRouter = {
	component:Vue.extend({
		template:templatizer.home.settings.assets({}),
		data() {
			return {
				search:'',

				add:{
					name:'',
					make:'',
					model:'',
					year:'',
					vin:'',
					description:'',
					type:'',
					owner:''
				}
			}
		},
		methods: {
			create() {
				console.log(this.add)
			}
		},
		watch:{
			'$data': {
				handler:function(val,oldVal,changed) {
					console.log(val)
					console.log(oldVal)
					console.log(changed)
				}, deep:true
			}
		}
	})
}
```

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

---

To your question: fine-grained deep watch is usually a bad idea. In most cases you can achieve it more declaratively with computed properties instead.
