### ISSUE TITLE
Upgrading from 1.0.18 to 1.0.19 cause an uncaught TypeError.

### ISSUE THREAD

**Issue by panteng** [vuejs/vue#2561]
My app works fine with Vue@1.0.18 but gets uncaught TypeError with Vue@1.0.19.

![qq 20160325170915](https://cloud.githubusercontent.com/assets/8369690/14041501/85bd9cda-f2ac-11e5-84ff-f8ad878e7f47.png)
![qq 20160325170948](https://cloud.githubusercontent.com/assets/8369690/14041502/87a87ad8-f2ac-11e5-9471-55a642404f95.png)

Is this a bug?

**Comment by yyx990803** [comment]
You probably need to upgrade vue-validator to make use of the latest terminal directive API. /cc @kazupon
