### ISSUE TITLE
keep-alive动态组件当activate未完成时切换组件报错

### ISSUE THREAD

**Issue by cxr29** [vuejs/vue#2566]
vue.js:8889 Uncaught TypeError: Cannot read property 'parentNode' of null

### Vue.js version
1.0.x

### Reproduction Link
https://jsfiddle.net/rnyLuhyh/

### Steps to reproduce
使劲点按钮切换组件就会报上面的错误

### What is Expected?
不知道是不是使用动态组件的姿势不对

**Comment by mrcuix** [comment]
写一个function到methods里面

写成这样：

[https://jsfiddle.net/skppfjgz/](https://jsfiddle.net/skppfjgz/)
