### ISSUE TITLE
数据绑定单次插值的时候"*"被解析为运算符

### ISSUE THREAD

**Issue by haozi23333** [vuejs/vue#2570]
![image](https://cloud.githubusercontent.com/assets/12862771/14049220/bbb0ab42-f2ee-11e5-8c58-ecf01c3e0e1c.png)
初学 `Vue.js`
我想随机选择其中的一些个数据不绑定message，但是`*`被识别为运算符

**Comment by yyx990803** [comment]
* 只能用在 {{ 后面，不是 js 语法的一部分。
