### ISSUE TITLE
[feature request] :class object support multiple class names as key

### ISSUE THREAD

**Issue by luwenjin** [vuejs/vue#2571]
just like this
`:class="{'a b c': flag, d: flag2}"`
as well as this
`:class="[flag?'a b c':'']"`

**Comment by luwenjin** [comment]
this is a real life example when i was using semantic-ui framework

**Comment by luwenjin** [comment]
So I tried as the second example. and I failed again

**Comment by Axnyff** [comment]
The second exemple would work as an expression returning a string, not a list.
The best way to it imo would be to use a list as a property computed from flag

https://jsfiddle.net/x54ju3em/1/

**Comment by luwenjin** [comment]
@Axnyff use a string works well.
the first case is still worth consideration (I've edit a little to reflect the use case)
