### ISSUE TITLE
can't bind a non-value attr to expression

### ISSUE THREAD

**Issue by bluedarker** [vuejs/vue#2572]
### for example:
`<input {{draft.logo?"":"required"}} type="file" />`

### expect result:
`<input required type="file" />`
or
`<input type="file" />`

### actual result:
`<input {{draft.logo?"":"required"}} type="file" />`

nothing happen!

**Comment by yyx990803** [comment]
Vue templates must be valid HTML - you cannot use `{{ }}` that way, it can only appear **inside** attribute values or as plain text.

**Comment by bluedarker** [comment]
thank you!
