### ISSUE TITLE
[feature request] local variables in v-for

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#2575]
Here is a nested `v-for` case

```html
<div v-for="x in xs">
      <div v-if="calcYs(x).length>0">
            <div v-for="y in calcYs(x)"> {{y}} </div>
      </div>
      <div v-else>fallback content</div>
</su-tab>
``` 
where `calcYs` is a method. As you can see, for every `x`, `calcYs(x)` will be called twice (if not empty) which is not necessary. It would be more efficient if we can bind the result of `calcYs(x)` to some local variables inside `v-for`.

**Comment by yyx990803** [comment]
This complicates the template quite a bit with very little benefits. I don't think it's worth it.

**Comment by rpkilby** [comment]
Could this be accomplished with a custom directive? eg,

```html
<div v-for="x in xs">
    <div v-with="ys = calcYs(x)" v-if="ys.length>0">
        <div v-for="y in ys"> {{y}} </div>
    </div>
    <div v-else>fallback content</div>
</div>
```

**Comment by jakobrosenberg** [comment]
I have a similar problem. I would like to do something like this ``v-for="project.relations().tasks()"``.

What would the recommended approach be? A new component just to list task names seems like overkill.

**Comment by jakobrosenberg** [comment]
Please disregard my previous post. It was working all along.

**Comment by drafterleo** [comment]
Code below generates "active table". It would be nice to have a local v-for variable for current index: (r-1)*10 + (c-1).
```html       
<p v-for="r in 5" style="margin: 1px">
    <span v-for="c in 10"
        class="bordered"
        style="margin: 1px; width: 30px; height: 30px; display: inline-block;"
        @mouseover="hoverIndex = (r-1)*10 + (c-1)"
        @mouseleave="hoverIndex = -1"
        @click="selectIndex = (r-1)*10 + (c-1)"
        :class="{hovered: hoverIndex == (r-1)*10 + (c-1) && showHover,
                    selected: selectIndex == (r-1)*10 + (c-1)}"> 
    {{ (r-1)*10 + c}} </span>
</p> 
```

**Comment by AlexandreBonneau** [comment]
I too think that having a `v-with` or `v-var` directive would help greatly with performance.
For instance, I have a template where an array is parsed with `.find()` every time I need to display a property from that object.
```html
<div v-if="subtotalRows.includes(payment.term)">
	<div>{{ findSubtotal(payment.term).shortDescription }}</div>
	<div>{{ anFloat(findSubtotal(payment.term).int) }}</div>
	<div>{{ anFloat(findSubtotal(payment.term).cap) }}</div>
	<div>{{ anFloat(findSubtotal(payment.term).ins) }}</div>
	<div>{{ an(findSubtotal(payment.term).fee) }}</div>
	<div>{{ anFloat(findSubtotal(payment.term).ter) }}</div>
</div>
```
and the method:
```js
findSubtotal(termIndex) {
    return this.subtotals.find(st => st.tpTerms === termIndex);
},
```

Is there a workaround I'm missing here to improve performance?
If not, I think reopening this issue could solve that problem, thanks!

**Comment by Kingwl** [comment]
@AlexandreBonneau   
 https://github.com/vuejs/vue/issues/6913

**Comment by x000000** [comment]
@AlexandreBonneau 
As a quick hack you can try this way:

```javascript
<div v-if="subtotalRows.includes(payment.term)">
    <template v-for="scope in [{ subtotal: findSubtotal(payment.term) }]">
        <div>{{ scope.subtotal.shortDescription }}</div>
        <div>{{ anFloat(scope.subtotal.int) }}</div>
        <div>{{ anFloat(scope.subtotal.cap) }}</div>
        <div>{{ anFloat(scope.subtotal.ins) }}</div>
        <div>{{ an(scope.subtotal.fee) }}</div>
        <div>{{ anFloat(scope.subtotal.ter) }}</div>
    </template>
</div>
```

**Comment by posva** [comment]
this issue is one year old 😅 
You can give https://github.com/posva/vue-local-scope a try too

**Comment by MarSoft** [comment]
Sometimes it turns out to be more convenient to move repeating code out to a separate component.

**Comment by Glandos** [comment]
> Sometimes it turns out to be more convenient to move repeating code out to a separate component.

It can't cover all use cases, but it was a nice and working advice for me. A small and easy-to-maintain subcomponent.
