### ISSUE TITLE
elem.appendChild

### ISSUE THREAD

**Issue by gebilaoxiong** [vuejs/vue#2576]
### Vue.js version
1.0.16

### Reproduction Link

[elem.appendChild](https://github.com/vuejs/vue/blob/dev/src/compiler/transclude.js#L58)
### What is Expected?

您好，我不是很清楚IE中哪个版本会出现这个问题(IE中插入的注释节点会在clone操作的时候被丢弃)。能否说明下。感谢

**Comment by yyx990803** [comment]
请不要用 issue 问问题...

IE 中空的 textNode 在 cloneNode(deep) 的过程中会被丢掉。

**Comment by gebilaoxiong** [comment]
@yyx990803 但是appendChild(elem, true);并不能解决这一问题

**Comment by gebilaoxiong** [comment]
@yyx990803 抱歉，是我看错了
