### ISSUE TITLE
Reactivity doesn't work on nested attribute when parent is affected/set

### ISSUE THREAD

**Issue by noirbizarre** [vuejs/vue#2577]
### Vue.js version
1.0.20 (tested with previous versions too)

### Reproduction Link
https://jsfiddle.net/noirbizarre/61oyrsya/

### Steps to reproduce
Bind any nested property somewhere and change the root object (by affectation or using `$set`).

### What is Expected?
The binding take the nested value of the new affected object.

### What is actually happening?
No reactivity, no change occurs.

**Comment by yyx990803** [comment]
This is not a Vue bug: `this.container2.value++` returns the **current** value of `container2.value`, and although you mutated the original object, you then replaced it with the new object which contains the old value.
