### ISSUE TITLE
partial doesn't work?

### ISSUE THREAD

**Issue by zhangking** [vuejs/vue#2578]
the component file like this 
index.vue
```javascript
<template>
<div>
  <partial :name="templateName"></partial>
</div>
</template>

<script>
import Vue from 'vue'

export default  {
    props: {
      template:{
        type:String,
        default:''
      }
    },
    data() {
      return {
        item:1,
        templateName:'default'
      }
    },
    created(){
       if(this.template != ''){
          this.templateName = 'template-'+ this._uid
          Vue.partial(this.templateName, this.template)
        }
    }
  }
</script>

```
and the index.js

```javascript
import test from "./index.vue"
import Vue from "vue"

Vue.mixin({
	components:{
		test
	}
})

module.exports = Vue
```
and I use webpack 

this html like this 

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
    <test
        :template="Template">
    </test>
</body>
<script src="./static/build.js"></script>
<script type="text/javascript">
new Vue({
  el:"body",
  data:{
    Template: '{{ item }}'
  },
  ready:function(){
  }
});
</script>
</html>
```
but it shows 

> [Vue warn]: Failed to resolve partial: template-1

I don't know how to resolve it ,please! maybe it's a bug

**Comment by fullfs** [comment]
@zhangking Hello! You should register partials _before_ you use them: https://jsfiddle.net/y4jhaxo0/

As I see, you're a beginner at Vue.js, so it would be faster for you use either [Gitter](https://gitter.im/vuejs/vue) or [the official forum](http://forum.vuejs.org/) for questions like this one.

**Comment by zhangking** [comment]
thanks for your answer,but I want to register partials dynamically in my component . Because I want to use the template which developer pass with props

**Comment by zhangking** [comment]
and I found that it does't work if I use **mixin**  . 
```javascript
import test from "./index.vue"
import Vue from "vue"
// Vue.mixin({
// 	components:{
// 		test
// 	}
// })

new Vue({
  el:"body",
  data:{
    Template: '{{ item }}'
  },
  components:{
  	test
  }
});
```
this will work

**Comment by fullfs** [comment]
@zhangking Partials are not supposed to be registered dynamically. Probably there are many ways how you could achieve the the same result. Take a look at http://vuejs.org/guide/components.html#Async-Components

Also, you don't need `Vue.mixin` to register a component globally. Just use `Vue.componet('test', ...)` for the purpose.

**Comment by zhangking** [comment]
@fullfs  thank you very much
