### ISSUE TITLE
Wrong (or maybe actually right) scope when `a` tag not closed

### ISSUE THREAD

**Issue by simonmysun** [vuejs/vue#2582]
### Vue.js version
1.0.12(current version on jsfiddle.net)

### Reproduction Link

https://jsfiddle.net/simonmysun/n731tqw0/
### Steps to reproduce
Just run it. 
### What is Expected?
The `a` tag can be closed by browser then bind to vue model. 
### What is actually happening?
When the `href` attribute of __second__ unclosed `a` tag is binded it trys to find the value in a wrong scope. What is interesting is that, if this `href` attribute is not binded, it's content can be successfully binded. 

`<a :herf="{{ branch.target }}">` doesn't work either, of course. 

I know the code itself is totally inappropriate. I'm just curious about why Vue process them differently and trying to note whether the debug info is correct.

**Comment by yyx990803** [comment]
This has nothing to do with Vue. The markup

``` html
<div>
  <a>
  <a>
</div>
```

When parsed by the browser, becomes

``` html
<div>
  <a>
  </a><a>
  </a></div><a>
</a>
```

If you write incorrect HTML... Vue can't produce correct results.

**Comment by simonmysun** [comment]
Thank you for your reply! 

This really interests me and by the way as I believe here are two complete examples: 

    <div><div><a>x<a>y</div> </div>

and

    <div><div><a>x<a>y</div></div>

I think I should learn the html standard to figure out the difference between this.
