### ISSUE TITLE
How to bind tap event for mobile pages?

### ISSUE THREAD

**Issue by xiaoyunchen** [vuejs/vue#2584]
How to bind tap event for mobile pages?
I try to use v-bind:on  and v-touch:on  and didn't work.
any suggestions?

### Vue.js version
1.0.17

### What is Expected?
tap event works!

**Comment by phanan** [comment]
You want a normal `@click` directive.

**Comment by xiaoyunchen** [comment]
@phanan sorry,@click in vuejs is the origin click event with 300ms delay on the mobile phones

**Comment by yyx990803** [comment]
Use fastclick or vue-touch. Again, issues are not for questions, read the
guidelines.

**Comment by sam3d** [comment]
Hi @yyx990803, the `fastclick` project appears to be no longer maintained and `vue-touch` is not yet compatible with `2.0`. Any chance of a built-in solution or workaround?

**Comment by posva** [comment]
@sam3d use the beta

**Comment by sam3d** [comment]
Well that was silly of me, thank you @posva.

**Comment by phyrun** [comment]
how i catch data ,what should i do?

**Comment by realanmup** [comment]
use vue2-hammer

**Comment by realanmup** [comment]
use vue2-hammer. search for it in npm
