### ISSUE TITLE
add docs for arr.$remove and arr.$set

### ISSUE THREAD

**Issue by alsotang** [vuejs/vue#2586]
In http://vuejs.org/api/ , there is no api for arr.$remove and arr.$set. 

But they are add by this file: src/observer/array.js

When I saw $remove usage in some example code, I feel confused but api page dont see anything.

**Comment by sirlancelot** [comment]
It's here: http://vuejs.org/guide/list.html#Caveats

**Comment by alsotang** [comment]
I know guide page has it. But it also belong to api page.

**Comment by alsotang** [comment]
I know guide page has it. But it also belong to api page.

**Comment by yyx990803** [comment]
Moved to vuejs.org repo: https://github.com/vuejs/vuejs.org/issues/265
