### ISSUE TITLE
Coerced props returning objects are not reactive

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#2587]
### Vue.js version
1.0.20

### Reproduction Link
https://jsfiddle.net/oe7axeab/668/

Then, how can I set reactivity on a coerced prop so I could extend a prop with multiple new reactive property  (with Object.assign(prop, { a: 0, b: 2}) , for example)

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by yyx990803** [comment]
This seems like a legit issue.
