### ISSUE TITLE
Problem with v-for + v-if in firefox

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2592]
### Vue.js version
1.0.20

### Reproduction Link
https://jsfiddle.net/2so6kua0/2/

### Steps to reproduce
Start example

### What is Expected?
We should get 
```
val == 1
val == 2
val == 3
val == 4
val == 5
val == 6
```

### What is actually happening?
In firefox we get nothing, but if we will change 
``<div v-for="val in arr" v-if="val">val == {{val}}</div>``
to 
```
<template v-for="val in arr">
  <div v-if="val">val == {{val}}</div>
</template>
```
all work correctly.

**Comment by phanan** [comment]
Actually the second snippet doesn't work for me either (Firefox 44.0.2, Yosemite).

**Comment by zigomir** [comment]
Interesting. To make it work you need to put v-if before v-for in Firefox, but to work in Chrome it's the other way around. Might have something to do with priorities? https://github.com/vuejs/vue/issues/2573

**Comment by yyx990803** [comment]
Yes, in 1.0.20 `v-if` and `v-for` is dependent on appearance order due to conflicting priority. This should have been fixed by https://github.com/vuejs/vue/commit/89b4ee9cd0ec2305199e9ce3dd199e5bf7653ac4

**Comment by zigomir** [comment]
@yyx990803 I'm not 100% sure this is problem here. Do we maybe have mater/dev branch build anywhere so I can test if it works same in Chrome and Firefox?

**Comment by yyx990803** [comment]
@zigomir in Firefox `element.attributes` enumeration order is in reverse, therefore in the fiddle `v-if` is compiled first in root scope.

**Comment by zigomir** [comment]
Ah, great, thanks for explanation.

**Comment by jeffmarshall** [comment]
Is this fix in a distribution? How can I get it into my project?

**Comment by yyx990803** [comment]
@jeffmarshall you will have to do the dev build: http://vuejs.org/guide/installation.html#Dev-Build

**Comment by jeffmarshall** [comment]
@yyx990803 ok, thanks
