### ISSUE TITLE
v-bind:class with object doesn't remove classes

### ISSUE THREAD

**Issue by arasharg** [vuejs/vue#2597]
When using an object in a v-bind:class ,classes are not removed from the element : 

[https://jsfiddle.net/arasharg/tLef7wfh/](https://jsfiddle.net/arasharg/tLef7wfh/)

**Comment by yyx990803** [comment]
Vue class bindings **do not** affect existing static classes on the element, this is working as intended.

**Comment by arasharg** [comment]
Before new version I had no problems

**Comment by yyx990803** [comment]
If you want the class to be controlled by Vue then you shouldn't put the static class there in the first place.

**Comment by davejamesmiller** [comment]
I'm relatively new to Vue.js so I never used the old version, but I have a use case where I need to have a class set on load (before Vue.js is loaded, to prevent FOUC, or if JavaScript is disabled to enable fallback functionality), but once Vue.js is loaded it should be able to remove that class.

I eventually came up with the following workaround:

```html
<body class="sidebar-pinned" :class="'sidebar-' + sidebar.state">
```

```js
new Vue({
    el: 'body',
    data: {
        sidebar: require('./stores/sidebar'),
    },
    beforeCompile() {
        // Remove the default class so Vue.js can manage it
        this.$el.classList.remove('sidebar-pinned');
    },
});
```

It's not ideal as it requires the JS code to know about the template structure, but it works well.

If anyone can suggest a better solution I'd love to hear it.

**Comment by Nirazul** [comment]
When it comes to JS disabled states, it's a common pattern to have a `no-js` class in the HTML tag which is removed by a JS snippet at the very first possible moment.
Considering your FOUC problem: You could add a class that's added after compilation that renders the base styles invalid:

```js
<body class="sidebar" :class="['sidebar-initialized', 'sidebar-' + sidebar.state]">
```

Then adapt accordingly in CSS

```css
.sidebar {
    /* default styles */
}

.sidebar-pinned,
.sidebar:not(.sidebar-initialized) {
    /* pinned styles */
}
```

**Comment by davejamesmiller** [comment]
Thanks for the suggestion @Nirazul. It is a possibility, but the CSS is already a bit more complicated than that and I was trying to avoid making it even more complicated. Plus the sidebar could be either open (pinned) or closed on page load (it's remembered via cookie and initalised server-side) - so I'd need two initial states and it would go from something this:

```css
.sidebar-pinned .sidebar { ... }
.sidebar-closed .sidebar { ... }
.sidebar-pinned .content { ... }
.sidebar-closed .content { ... }
...
```

(Plus a few more rules that tweak parts of the layout as needed...)

To this:

```css
.sidebar-pinned .sidebar,
.sidebar-default-pinned:not(.sidebar-initialized) .sidebar { ... }

.sidebar-closed .sidebar,
.sidebar-default-closed:not(.sidebar-initialized) .sidebar { ... }

.sidebar-pinned .content,
.sidebar-default-pinned:not(.sidebar-initialized) .content { ... }

.sidebar-closed .content,
.sidebar-default-closed:not(.sidebar-initialized) .content { ... }

...
```

It also changes the specificity of the rules, which could create extra bugs and certainly requires more testing.

So it just seems like a lot of work compared to doing it in JavaScript...

**Comment by blexxed** [comment]
I had the same problem and what solved mine is the first suggested solution of @davejamesmiller. The only thing I did is migrate the code to VueJS 2.0. Instead of using `beforeCompile()`, I used `created()`.

**Comment by smiller171** [comment]
@yyx990803 This is an annoying limitation when using 3rd-party components. The ability to override their classes would be nice

**Comment by golgote** [comment]
Knockoutjs can deal with this without problem. An example use case is when you have a form field that is validated server side and you want to have the validation to also happen client side using vuejs. Then you need to deal with css classes with same name coming from two sources, server says field is invalid, but the user corrects the value and the client validation should update the css class, but with Vuejs it is not possible because Vuejs apparently considers that the invalid class is static. Sounds silly to me.
