### ISSUE TITLE
v-for如何遍历一个二维数组

### ISSUE THREAD

**Issue by biluochun** [vuejs/vue#2600]
这是我目前的处理，但并不理想  `<li v-for="i in (list.length * list[0].length)"></li>`  
希望得到一个好的建议。

**Comment by hanai** [comment]
``` html
<div>
  <ul v-for="x in list">
    <li v-for="y in x"></li>
  </ul>
</div>
```

**Comment by biluochun** [comment]
这样的结果并不是我想得到的。

**Comment by Twiknight** [comment]
如果你想要把二维数组解压成一维数组，直接上lodash： 

`_.flattenDeep(arr)`

不需要让vue做什么，按照MVVM的习惯做法，这一步应该在view-model上动手脚，而不是在view上想办法。

PS：提问请去 [论坛] (forum.vuejs.org)
