### ISSUE TITLE
Some problem in v-show

### ISSUE THREAD

**Issue by For-me** [vuejs/vue#2604]
When i use v-show to control a modal. In this modal, i have a input .But when i open the modal,I can't get focus into input. Why? When i delete v-show. I can focus into input. What happend?

**Comment by weilao** [comment]
Let me guess...
You should call focus() like this:

```js
Vue.nextTick(function(){
    someInput.focus();
});
```

**Comment by For-me** [comment]
@weilao yeah.like u say.I solve it.Thx

**Comment by simplesmiler** [comment]
@For-me I've struggled with focus in the past, and written a module that helps with common focus use cases: https://github.com/simplesmiler/vue-focus
In this particular use case you would put `v-focus-auto` on the input.
