### ISSUE TITLE
Component Props: coerce not working with default option in v1.0.20

### ISSUE THREAD

**Issue by JosephusPaye** [vuejs/vue#2606]
Hi there, first I would like to say thanks for Vue, it is truly awesome.

I think I may have found a slight regression in Vue 1.0.20. It seems like the `default` option for component props is not passed through the `coerce` function in Vue 1.0.20. I had this working in 1.0.17 before I upgraded. See the Fiddles below for details.

Thanks

### Vue.js version
1.0.20

### Reproduction Link
Not working Fiddle (Vue 1.0.20): http://jsfiddle.net/5sH6A/292/
Working Fiddle (Vue 1.0.17): http://jsfiddle.net/0w62a9xx/1/

### Steps to reproduce
See the Fiddles above.

### What is Expected?
The prop default should be passed through the coerce function.

### What is actually happening?
Only props that are specified in the template (and not defaults) are passed through the coerce function.

**Comment by simplesmiler** [comment]
This looks like unintentional breaking change, but I don't think the behavior was ever documented.
As a workaround you can move default into the coerce function: http://jsfiddle.net/5sH6A/297/

I'm pinpointing a commit where the change has happened.

**Comment by simplesmiler** [comment]
Fixed by https://github.com/vuejs/vue/pull/2610

**Comment by simplesmiler** [comment]
Landed in 1.0.21.
