### ISSUE TITLE
在安卓4.1.1下，文本框v-model bug

### ISSUE THREAD

**Issue by AnyGong** [vuejs/vue#2607]
### Vue.js version
1.0.17

### Reproduction Link

http://jsfiddle.net/rw5m9fn2/

### Steps to reproduce
当输入到指定位数，触发符合 v-modal 的条件

### What is Expected?
当符合 v-modal 时，qqInfo 会显示出来

### What is actually happening?
Hybrid的开发模式，采用是的dcloud平台打包方式。在安卓4.1.X的手机上测试时，当触发了符合  v-modal 条件时，这时的输入键盘突然下去了。同样平台的打包方式，安卓4.4.X则不会。会是因为安卓版本的原因，还是Vue？

**Comment by yyx990803** [comment]
这显然是旧 Android 或者是打包环境的问题... 请再定位一下触发条件，不要用 v-show 看看。

**Comment by AnyGong** [comment]
@yyx990803 感谢回复！sorry , 由于节假日，今日才来回复。
我经过测试，又重新定位了一下问题，其实我在那个符合 v-model 的时候，拿到了  val 的值，进行了 ajax查询，查询出的结果对`$data`的属性赋值之后，才发生了那样的问题
`this.muiAjax(mixins.pkg.interface.getQQInfo, {qq: value}, function (result,vm) {
                        vm.qqInfo=result.data
                    })`。如果不是通过ajax查询出的结果进行赋值，不管是  `v-if , v-show`在哪个安卓版本下,都没问题。不知道这块在安卓4.1.X中，进行 ajax查询对`$data`的属性进行赋值时,如何避免键盘会弹下去。正在探索中,目前还没更好的解决方案，

**Comment by yyx990803** [comment]
我感觉这个不属于在 Vue 的范围内能解决的问题，但如果你找到了解决办法，欢迎提供线索。
