### ISSUE TITLE
Browser freeze (Safari iOS 9; possibly Webkit bug)

### ISSUE THREAD

**Issue by nevsnode** [vuejs/vue#2608]
### Vue.js version
1.0.20

### Reproduction Link
x

### Steps to reproduce
Haven't been able to pin down the exact conditions, please have a look at the longer description.

### What is Expected?
No "infinite loop"/frozen browser.

### What is actually happening?
In our production environment Safari on iOS randomly freezes (and uses 100% cpu) when a component-method is about to be called through a click-handler (`@click`).
Unfortunately it is very hard to debug this as we couldn't reproduce it in any development-environment, but with very simple console.log output we came to the belief that there is some "infinite loop" before our mentioned method is called from Vue.

In some situations it helped to just reload the page twice. Also just to be said there is nothing special going on in that method, just changing a variable of the main Vue-instance and it works perfectly fine in every other browser.

I am afraid that this could be caused by some Webkit-bug where `typeof` returns the wrong value for a function/object:
https://bugs.webkit.org/show_bug.cgi?id=156034
_"So it seems that problem here that we mistakenly return "object" for typeof of a function in some JITed code."_

As this report probably violates the guidelines a lot, I want to apologize in advance, for being that vague. I will try to get some more information tough :-/

**Comment by posva** [comment]
Do you have a method or computed property that calls itself? I've seen this freeze Safari

**Comment by nevsnode** [comment]
Hey, thanks for your reply. No not that is not the case, we basically have a structure like that:

```html
<div id="app">
  <component :is="step"></component>
</div>

<script>
  var app = new Vue({
    el: '#app',
    data: {
      step: 'step-1',
    },
    components: {
      'step-1': {
        template: '<div class="some-element" @click="nextStep"></div>',
        methods: {
          nextStep: function() {
            console.log('goStep(step-2)');
            goStep('step-2');
          }
        }
      },
      'step-2': {
        template: '<div>Step 2</div>'
      }
    }
  });

  var goStep = function(step) {
    app.step = step;
  };
</script>
```

The issue now is that when the element with the `@click` handler is pressed, the random freeze occurs. We've tried to debug that as good as possible, however as we do not see the `console.log` output we believe there is some loop before `nextStep` is actually called...

**Comment by posva** [comment]
Ok, In order to give you further help we'll need you to provide a minimal reproduction in a jsfiddle :smile:

**Comment by nevsnode** [comment]
I'll try to do that. I currently have an iPhone 5 with iOS 9.2.1 here for testing, but the issue does not appear.
We've yet seen that only on an iPhone 6/iPhone 6s plus with iOS 9.x.x; I'll probably have to wait till next week to get my hands on those for testing

**Comment by nevsnode** [comment]
Seems like we were able to fix it now, and it's likely completely unrelated to Vue.
The element with the click handler was an anchor-element like this:

```html
<a class="button" @click="nextStep">
  next step
</a>
```

The freeze did not happen when changing the element in one of two ways: Either make it a button-element or add an href-attribute:
```html
<a class="button" href="javascript:void()" @click="nextStep">
  next step
</a>

<!-- or -->

<button type="button" class="button" @click="nextStep">
  next step
</button>
```

As there are no further listeners I would probably like to blame Safari, but I still can't say for sure, as this was not reproducible in other situations (or on jsfiddle).
Interestingly, when we removed an optional, unrelated js-library, the freeze happened on a different "step" :confused:

Anyway, I hope this may help if someone experiences similar issues...

**Comment by blake-newman** [comment]
Perhaps you needed to have `@click.prevent` modifier to prevent the default behaviour of the link.

**Comment by nevsnode** [comment]
If I remember correctly, we did try that as well as `stopPropagation()` without any influence.
I would also expect that it should affect much more devices/browsers then :sweat_smile:

**Comment by kamaldhariyal** [comment]
Do anyone of you have a script to freeze the latest version of iphone siri browser with an pop up execute. Its Urgent needed.
