### ISSUE TITLE
Specify Filter with Variable

### ISSUE THREAD

**Issue by frankdugan3** [vuejs/vue#2609]
### Feature Request
It would be nice to be able to use a variable to specify a filter. For example, a table component could have a column definition passed as a prop:
```
columns: [
    {
        key: 'cost',
        label: 'Cost',
        filter: 'currency',
    }
]
```
And the implementation of the column could use the filter from the prop:
```
<td v-for="column in columns">
    <span>{{ row[column.key] | column.filter }}</span>
</td>
```
As of now, I'm using a filter-loading filter as a workaround (obviously far from ideal):
```
Vue.filter('getFilter', (value, filter) => {
	if (filter !== undefined) {
		filter = Vue.filter(filter)
		return filter.read !== undefined ? filter.read(value) : filter(value)
	}
	return value
})
```
```
<td v-for="column in columns">
    <span>{{ row[column.key] | getFilter column.filter }}</span>
</td>
```

**Comment by yyx990803** [comment]
I think your solution is fine. Resolving filters using both string ids AND expressions is inconsistent and can be confusing (you don't know where to look for it).

**Comment by simplesmiler** [comment]
@frankdugan3 you can also improve `getFilter` by fetching the filter from the `this.$options.filters` instead of the global `Vue.filter`.
