### ISSUE TITLE
directive 下用vm的$set方法会发出警告

### ISSUE THREAD

**Issue by fengxiaotx** [vuejs/vue#2611]
我想请问下，在指令下面，我直接对vm对象$set 会发出警告，有没有办法解决这个问题呢？
`	Vue.directive('ms-form',{
		id: 'ms-form',
		priority: 10001,
		bind:function () {
			let vm = this.vm;
			let el = this.el;
			let formName = el.getAttribute("name");
			//vm["formName"]="";
			vm.$set("formName",formName);
			//zvm[formName]={};
			vm.$set(formName,{
				"$valid":true,
				"$invalid":false
			});
debugger;
			vm.$watch(formName,function (newValue,oldValue) {
				let valid = true;
				for(let index in newValue){
					if( newValue[index]["$invalid"] != undefined &&  newValue[index]["$invalid"] ){
						valid = false;
						break;
					}
				}
				newValue.$invalid = !valid;
				newValue.$valid = valid;
			},{
				deep: true
			});

		}
	});`

比如这段代码，就会抛出这样的警告
[Vue warn]: You are setting a non-existent path "formName" on a vm instance. Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.
[Vue warn]: You are setting a non-existent path "categoryForm" on a vm instance. Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.

**Comment by yyx990803** [comment]
警告的意思是建议你在组件的 data 中初始化要用到的值，而不是在指令中动态添加。
