### ISSUE TITLE
how to set data  in $watch?

### ISSUE THREAD

**Issue by jie** [vuejs/vue#2613]
Code like this. Data 'disabled'  could not set to other value in $watch.

export default {
        props: ['mytext'],
        data() {
            return {
                disabled: 'disabled',
            }
        },
        watch: {
            mytext: {
                handler (data) {
                    if(this.mytext.length > 5) {
                        this.disabled = 'disabled'
                    } else {
                        this.disabled = '';
                    }
                }
            }
        }  
    };

**Comment by yyx990803** [comment]
Set it to null or false.
