### ISSUE TITLE
V-For for Arrays Triggers Alias Warning?

### ISSUE THREAD

**Issue by bryanleetc** [vuejs/vue#2616]
`array = [3, 4, 5, 6]`
`
<li class="page" v-for="item in array">
  {{ item }}
</li>
`
The above code is triggering a "Vue warn]: Alias is required in v-for." warning in the console. Might this be a bug?

Here's a jsfiddle for it, but it seems that the warning doesn't get triggered in the fiddle
http://jsfiddle.net/5sH6A/298/

**Comment by yyx990803** [comment]
If you cannot reproduce it in a fiddle, then it's like you have some syntax error in your template. Please make sure to only open the issue if you are sure it's a bug and can reliably reproduce the issue.
