### ISSUE TITLE
"Duplicate value found" warning with v-for

### ISSUE THREAD

**Issue by pierrebonbon** [vuejs/vue#2618]
I've been using [twitter-fetcher](https://github.com/jasonmayes/Twitter-Post-Fetcher) to circumvent Twitter's latest API without much issues until recently when I started getting the following errors, after posting a duplicate tweet:

    [Vue warn]: Duplicate value found in v-for="tweet in tweets": "<p class=\"tweet\">tweet parsed from json file!</p>". Use track-by="$index" if you are expecting duplicate values.

    vue.js:1174 Uncaught TypeError: Cannot read property 'parentNode' of null. 

Why would `v-for` throw an error when there's a duplicate value? I've reproduced the warning [here](https://ide.c9.io/pierrebonbon/twitter-fetcher)

**Comment by blake-newman** [comment]
This is standard behaviour, please see http://vuejs.org/guide/list.html#track-by for an explaination list rendering. The syntax for this is similar to that of angular to resolve this - `track-by`.

**Comment by pierrebonbon** [comment]
Thanks for the clarification and the link!
