### ISSUE TITLE
Make the $children instance property a reactive array

### ISSUE THREAD

**Issue by ajanes93** [vuejs/vue#2621]
I wanted a computed property that re-evaluates every time the $children instance property is updated, in my case this was every time a component was added/removed from the DOM.  on each change I wanted to return a list of all component names currently active in the DOM.  This however did not function as expected because $children is not reactive.

see fiddle which shows the issue:  https://jsfiddle.net/ajanes92/k729g6jb/26/

I managed to work around it by creating a reactive array in the ready method based on this.$children, see updated fiddle here: https://jsfiddle.net/3mwpd96r/1/

is there a reason why $children is not reactive? And if not can it be made reactive so it can be used in computed properties as per my requirements?

Thanks

Andres

**Comment by Twiknight** [comment]
If your components are generated from a reactive array, it's easy to make it.

Just change `children` to `children.filter((x)=>x)` or some way you can check if a item should be show  as a item in your component list.

fiddle: https://jsfiddle.net/k729g6jb/34/

Hope it would help.

BTW..
I don't think it is necessary to make `$children` reactive. I think __only__ data should be reactive.

**Comment by phanan** [comment]
@Twiknight was right. `$children` is about components, not data, and thus shouldn't be reactive. [Vue's reactivity](http://vuejs.org/guide/reactivity.html) simply doesn't work that way (DOM events, as in your case).
