### ISSUE TITLE
using $set on the ios9.3.x devices causes view not update 

### ISSUE THREAD

**Issue by fengiming** [vuejs/vue#2623]
using $set on the ios9.3.x devices causes view not update with  vue 1.0.20

**template:**

    <div class="shop-list-wrap">
        <shop-item v-for="item in showShopData" v-bind:item="item | dealShopItem"  track-by="id"></shop-item>
    </div>

**souce code:**
           setShowShopData: function () {
                var newShopData = this.totalShopData.slice(0, curIndex+5);
                this.$set('loading', false);
                this.$set('showShopData', newShopData);
                this.$set('showNoData', newShopData.length == 0);
                loadingForAppend = false;
                curIndex += 5;
            },    
line:   this.$set('showShopData', newShopData), when I call this function as a ajax request callback,  this line doesn't work on the ios9.3.x devices and the view doesn't update ,but on the Andriod or Ios below 9.3 devices it work ok , i don't know why.

-------------------------------------------------------------------------------------------------------
中文描述： IOs 9.3.x 版本设备上，列表上拉加载数据，使用 this.$set('showShopData', newShopData) ，为列表v-for 数组赋一个全新的数组对象，但这样并不更新视图并且会导致错误。在 PC端 、andriod 设备 、 ios 9.3.x 以下版本设备上则能正常更新视图。因为用的是node打包到一个js文件中，IOs 9.3.x 版本设备上一出错，导致整个项目就崩溃掉。
      打包后的项目在附件中，可以浏览器中打开home.html 页面查看列表下拉加载效果，问题代码出现在 shopList.vue 文件中，路径 views/bank/shopList.vue

[Uploading merchant.zip…]()

**Comment by yyx990803** [comment]
Can you provide a full, runnable reproduction?

**Comment by fengiming** [comment]
why do  i can't upload zip file ?

**Comment by fnlctrl** [comment]
'reproduction' actually means a runnable code snippet on jsfiddle/codepen, which is the bare minimal of your code that 'makes the bug happen again', not an excerpt of your production code.

**Comment by fengiming** [comment]
sorry, this problem has been resoved yet ,which is not caused by Vue 1.0.20 .Thank you !
