### ISSUE TITLE
stopPropagation on a double click doesn't work

### ISSUE THREAD

**Issue by guillaumevincent** [vuejs/vue#2625]
### Vue.js version
1.0.16 (tested with 1.0.20 as well)

### Reproduction Link

https://jsfiddle.net/d070emwu/2/

### Steps to reproduce

```html
<div @click='actionA | debounce 1000'>
  <button @dblclick.stop='actionD'>@dblclick.stop (error)</button>
</div>
```
`actionD` is called with a double click but don't stopPropagation. `actionA` is called

Warning maybe this is the expected behaviour. There is probably an another way to catch a double click with a simple click on an element.

**Comment by yyx990803** [comment]
`dblclick` and `click` are different events, stopping `dblclick` doesn't affect `click` from propagating. Use `@click.stop` on the inner button.

**Comment by guillaumevincent** [comment]
> dblclick and click are different events
thanks for the precision 

> Use @click.stop on the inner button
I wanted a simple and a double click on the same element. simple click -> select, double click -> open.
Like on google drive for a folder or a document. I will use a custom method.

**Comment by Malian** [comment]
@guillaumevincent Did you find a solution? I want to do the same as you. Thanks!

**Comment by guillaumevincent** [comment]
@Malian the double click and simple click on the same element wasn't really good in term of accessibility.
I tried another approach
