### ISSUE TITLE
[1.0.18+]input value clears on blur in nested "v-for"

### ISSUE THREAD

**Issue by horans** [vuejs/vue#2626]
### Vue.js version
1.0.18+ 
(chrome 51/ ie 11/ firefox 45)

### Steps to reproduce
1. image
![vue-1 0 18-input](https://cloud.githubusercontent.com/assets/12060804/14310526/d7f82bde-fc14-11e5-896f-af6b7e9cc86a.png)

2. scenario
each "attendee" from `order.attendee_adult` has several options to fill in. the options store in `detail.contact_adult`.

3. code

			<div class="people adult transition" v-for="attendee in order.attendee_adult" transition="expand">
				<div class="top">
					<div class="title">成人 {{ $index + 1 }}</div>
					<ul class="action list-inline">
						<li class="directory hidden"><i class="fa fa-fw fa-users"></i></li>
						<li class="toggle"><i class="fa fa-fw fa-angle-up"></i></li>
					</ul>
					<span class="state transition"><i class="fa fa-check"></i></span>
				</div>
				<div class="inputs row active transition fast ease">
					<div class="input col-xs-12 col-md-6 error unload" v-for="option in detail.contact_adult">
						<span class="title">{{ option.title }}</span>
						<input type="text" name="{{ option.name }}" v-model="attendee[option.name]" required>
						<span class="state transition"><i class="fa fa-remove"></i></span>
						<span class="info transition">请输入{{ option.title }}</span>
					</div>
				</div>
			</div>

4. problem
value clears when input lost focus.
however data binding works till a next focus on input, which will then also clear the data in vue.
no "custom filter" used.

### What is Expected?
works fine on 1.0.17

### What is actually happening?
may have something to do with #2491

**Comment by yyx990803** [comment]
Please provide a full reproduction - just the template doesn't help.

**Comment by dalphyx** [comment]
I have same problem when update vue from 1.0.17 to 1.0.18, just test 1.0.21 it's works fine again

**Comment by simplesmiler** [comment]
@horans try adding proper `track-by` on the elements with `v-for`. By default list items are tracked by identity, and when the identity changes corresponding element will be destroyed and created again, thus losing focus.

**Comment by horans** [comment]
this problem occurs on 1.0.18/19/20.
and works fined again on 1.0.21 as @dalphyx mentioned.
