### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by kucherenkovova** [vuejs/vue#2628]
### Vue.js version
1.0.19
### Steps to reproduce
use webpack
run your web-app in browser
### What is Expected?
work as well, as it works in electron
### What is actually happening?
In browser environment I get this error `Uncaught ReferenceError: process is not defined`
It fails in file `vue.common.js ` on line 913

**Comment by kucherenkovova** [comment]
Just in case somebody is facing same issue there's a workaround for it. Just add to your plugins this one
`new webpack.DefinePlugin({ 'process.env.NODE_ENV': '"development"' })`
in your `webpack.config.js`

**Comment by FadyMak** [comment]
Hi there! I doesn't seem very clear to me what the issue you're mentioning is. This seems to be more of an issue with your Webpack configuration as opposed to a Vue issue.

**Comment by kucherenkovova** [comment]
@FadyMak 
It looked really strange for me that vue.js doesn't work with webpack right out of the box. Even if it is a normal behaviour (which I think is not) you should've mention this webpack-specific thing with `DefinePlugin` somewhere in readme or in the doc.
I think it would be way better to make a little check for environment since vue.common.js can be used in browser as well.

**Comment by Nirazul** [comment]
`vue.common.js` is the common-js bundle. I don't think that you intentionally used this version.
Just use `vue.min.js` or the development version and you will see, that no such thing as a `webpack.DefinePlugin` is needed.

**Comment by kucherenkovova** [comment]
@Nirazul It's quite disappointing that it is possible to use a wrong version of lib without realizing it. I just did `require('vue')` and it seemed to me pretty obvious that everything will work like butter :(

**Comment by yyx990803** [comment]
Webpack should automatically shim the `process` unless you explicitly tell it not to, same for Browserify. Are you using Webpack 2 beta? That might cause different behavior.

**Comment by kucherenkovova** [comment]
@yyx990803 nope, I'm running `webpack 1.12.9`. Thanks for your reply, it pointed me to the real cause of the problem. Webpack indeed shims `process` variable for us automagically. I just had `target: 'electron'` in my `webpack.config.js`. When I changed it to `target: 'web'` everything worked as expected! 
It turned out to be not a vue issue at all

**Comment by mnieber** [comment]
fyi the suggestion by @kucherenkovova makes the symptom go away (I'm not sure it also solves or works around the problem, perhaps it does) by ensuring that `process.env` is indeed defined, it has nothing to do with the value of `NODE_ENV`. So the following also "works"

  plugins: [
    new webpack.DefinePlugin({
      'process.env': {}
    }),
  ],

**Comment by drzraf** [comment]
.min.js version is not suitable for ES6 imports
.esm.js version is not suitable for ES6 imports
