### ISSUE TITLE
object using custom directives does not trigger events

### ISSUE THREAD

**Issue by alextime** [vuejs/vue#2629]
I tried to use a select2 integration following the official Custom Directive Example (http://vuejs.org/examples/select2.html).

In this scenario the classic v-on:change="someMethod" approach stop working. If I remove the custom directive and the select become a simple standard select the event handling work again.

**Comment by yyx990803** [comment]
This is because `select2` doesn't dispatch native `change` events. You can use a watcher to watch the bound value instead.
