### ISSUE TITLE
[bug] unmounting element that was mounted with `replace: false` results in removal of the mount element

### ISSUE THREAD

**Issue by dragantl** [vuejs/vue#2630]
### Vue.js version
1.0.20

### Reproduction Link
https://jsfiddle.net/ardoramor/kf2yooho/1/

### Steps to reproduce
Check and un-check the checkbox.

### What is Expected?
Expectation is that mounting with `replace: false` option set will preserve the mounting point when the removal happens. This allows for reuse of the mounting point if anything else needs to be mounted in place of the old component. In the example, once the checkbox is unchecked, the child should be removed but the blue box (`.mount` class) should remain.

### What is actually happening?
Mounting onto the `.mount` with option `replace: false` and unmounting results in removal of the original mount point.

**Comment by yyx990803** [comment]
This is intended. `replace: false` simply uses the existing element as `this.$el` for the component, so it is removed when you remove the component.

**Comment by dragantl** [comment]
Can you then suggest on an alternative? I'm using this approach to mount dynamic components onto body of a modal. I do not know the components ahead of time so I cannot include them in `components` and use dynamic switching. How can I preserve the mounting point?

**Comment by yyx990803** [comment]
`new Component().$mount().$appendTo('#target')`
