### ISSUE TITLE
style object in v-for elements not reactively updated

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#2631]
### Vue.js version
1.0.20

### Reproduction Link

http://www.webpackbin.com/EJ3ZasRCl

### Steps to reproduce
Click 'Move' button, wait until the transition ends

### What is Expected?
`x.styleObject` should be update as well, i.e. the message should turn green.

### What is actually happening?
`x.msg` gets reactively updated but `x.styleObject` does not.

**Comment by yyx990803** [comment]
http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats
