### ISSUE TITLE
Transitions not trigger on dynamic component when component constructor is passed

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue#2633]
### Vue.js version
1.0.20

### Reproduction Link
https://jsfiddle.net/Lnnju3ej/3/

### Steps to reproduce
Click to button 2.

### What is Expected?
Transition starts on components.

### What is actually happening?
Components switches without transition.

Note what it works correctly when component name is passed: https://jsfiddle.net/Lnnju3ej/5/

**Comment by paulpflug** [comment]
I think that will is no bug, as you create a constructor when extending:
`compConstructor = Vue.extend(obj)`
(as you also wrote)

the instances are created in vue compilation, based on this:
```js
components: {
  	MyHeader, Slide1, Slide2
  }
```

In my eyes it makes no sense to select a instance by its constructor,
as this it is allowed to have two instances of the same constructor:
```js
let Slide = Vue.extend(obj)
components: {
  "slide1": Slide,
  "slide2": Slide
}
```

**Comment by OEvgeny** [comment]
@paulpflug
It's not about `components` instance property. I pass components directly as a parameter for `:is`. This components are different but transition is not apply. I think it should work. When I pas component names as parameters it works as intended. See my note above.

I updated reproduction to clarify.

**Comment by paulpflug** [comment]
I do understand, the problem is you are not passing the component directly..
```js
// Comp is the constructor
Comp = Vue.extend(obj)
// comp is the component
comp = new Comp()
// you are passing `Comp`, the constructor

// but in your Vue block it is allowed to use the same constructor multiple times:
components: {
  slide1:Comp,
  slide2:Comp
}
// I think you could also do this:
components: {
  slide1:obj,
  slide2:obj
}
```
The point is, the only way to identify a component is its name..

The reason why no transition is triggered, is that the same component stays in place the whole time.

**Comment by yyx990803** [comment]
The problem is actually because calling `Vue.extend` on the same object returns the same (cached) constructor, so `Slide1` and `Slide2` are actually the same object.

Again this is similar to what I described in #2634 : we will add a dedicated mechanism for this type of transitions.

**Comment by OEvgeny** [comment]
Ok, thanks Evan!
