### ISSUE TITLE
Add child-parent communication with Components

### ISSUE THREAD

**Issue by gjuchault** [vuejs/vue#2636]
Hi !

I was trying to create a custom select tag. But components only support parent -> child communication with props. But there is no way to use something similar to what `v-model` would be to inputs.

Thanks :)

**Comment by simplesmiler** [comment]
Hello!

For two-way style there are [props binding types](http://vuejs.org/guide/components.html#Prop-Binding-Types), especially `.sync` that allows the child to change the value, and propagate this change to the parent.

For one-way style there are [custom events](http://vuejs.org/guide/components.html#v-on-for-Custom-Events), that can be `$emit`ed from the child and picked up the parent with `v-on`.

---

Please note, that this issue tracker is for bugs and feature requests. For questions and support we have a [gitter chat](https://gitter.im/vuejs/vue) and a [forum](https://forum.vuejs.org/). You can find help there quicker.

**Comment by gjuchault** [comment]
My bad, I though this was not a feature yet (as not referenced in Components but in Props) and that would have been a feature request.
