### ISSUE TITLE
Web component with "is" attribute not rendered in the view.

### ISSUE THREAD

**Issue by SaidAhemtNolaroads** [vuejs/vue#2642]
Hi there!

First of all thanks for your work. I'm using Vue everyday, and it's great!

I just encountered however a problem when I tried to use a Web Component (with webcomponentjs polyfill) with the `is` attribute, inside a view. However, this component works perfectly when I use a custom tag. The problem with the custom tag approach, is that I can't extend default HTML elements anymore.

During my investigation, I noticed that Vue checks if the component is declared in the vm or not. But when the component is not declared, it's not rendered.

Is there a way to specify inside a view which component we would like to ignore during the evaluation of the template ?

**Comment by posva** [comment]
Hi!

Please make sure to sure to ask the question on the [forums](forum.vuejs.org) or the [gitter chat](https://gitter.im/vuejs/vue). You'll get faster feedback. We try to questions out of issues :smile:

As for the question, I'm not sure I understand the point. Why would you ignore a component? Maybe you can use the v-pre directive http://vuejs.org/api/#v-pre

**Comment by yyx990803** [comment]
Adding `v-pre` to the element should solve the issue.

**Comment by SaidAhemtNolaroads** [comment]
Thank you so much @posva and @yyx990803!! You made my day ^^

**Comment by SaidAhemtNolaroads** [comment]
Wait, I forget to mention something... I also need to keep the other directives working. Since I extended an `<input>` element, I would like to use directives like v-model. But the `v-pre` disables everything.

**Comment by yyx990803** [comment]
@SaidAhemtNolaroads that is indeed a problem - I've fixed it so that `is` attribute that doesn't resolve to a Vue component will be preserved.
