### ISSUE TITLE
Deleting deep level property doesn't trigger digest cycle

### ISSUE THREAD

**Issue by jyloo** [vuejs/vue#2643]
I am trying to delete a deep level property of an object, and since vm.$delete doesn't perform the task, i copy it to a variable, delete the property, and set back to vm. However, weird thing happens. vue doesn't re-digest the data as stated in documentation where every call to vm.$set should trigger digest cycle.

sample code here: http://codepen.io/jyloo/pen/dMJjaO

**Comment by FadyMak** [comment]
Hey there! This is actually a limitation that Vue cannot detect property deletion on a reactive object.

Instead, you should be using `Vue.delete()` as mentioned in the [Vue API](http://vuejs.org/api/#Vue-delete)

In your case you would be doing something like this:

```javascript
Vue.delete(this.o, "child1")
```

**Comment by jyloo** [comment]
Yes this is exactly what i wanted! I tried this Vue.delete() method earlier but guess i missed putting 'this'. Now i try again, everything works perfectly! tqvm @FadyMak
