### ISSUE TITLE
Set length to 0 on an array doesn't update the view

### ISSUE THREAD

**Issue by Getz85** [vuejs/vue#2646]
### Vue.js version
1.0.21

### Reproduction Link
http://jsfiddle.net/LdgLa6jm/

### Steps to reproduce
Click on clear button.

### What is Expected?
The list of todos must be empty.

### What is actually happening?
The list is still popuplated, even if the `console.log(this.todos)` show an empty array.

```javascript
var demo = new Vue({
    el: '#demo',
    data: {
        title: 'todos',
        todos: [{done:false,content:'testing'}]
    },
    methods: {
    	clear: function(){        
      	this.todos.length = 0;
        console.log(this.todos);
      }
    }
})
```

It works fine if we empty the array element by element:

```javascript
while (this.todos.length) {
    this.todos.pop();
  }
```

**Comment by posva** [comment]
Hi, this is working as intended: http://vuejs.org/guide/list.html#Caveats
You should just replace it with a new array: `this.todos = []`, that'll work :smile:
