### ISSUE TITLE
[Feature] Recompiling from inline-template

### ISSUE THREAD

**Issue by drdaemos** [vuejs/vue#2651]
I'm trying to integrate Vue.js into existing platform and having troubles with implementation of component reloading. I need such feature because it can be too complex to update view state with information from backend and it'll be easier just to redraw the component with new data.

There is a tree of components on the page (all of them use _inline-template_ feature) and i want to be able to recompile a certain element from html string or **DOMElement** on some trigger.

I've tried two ways of accomplishing this, but both just don't work exactly as i need:
1) tried creating element and replacing **this.$el** and then **$mount** (with flags reset), but that renders some cached template (probably):

        var temp = document.createElement('div');
        temp.innerHTML = html_string;
        var el = temp.querySelectorAll(this.$options.name)[0];
        $(this.$el).replaceWith(el);
        this._isCompiled = this._isAttached = this._isReady = false;
        this.$mount(document.querySelectorAll('div[is=shipping-methods]')[0]);
2) tried **$compile** from html node, but this constructs another Vue instance and i can't get reference to it in a clean way:

        var host = this.$parent;
        var temp = document.createElement('div');
        temp.innerHTML = html_string;
        var el = temp.querySelectorAll(this.$options.name)[0];
        this.$compile(el, host);
        // i can make this.$destroy(true); here but can't get reference on new vm

Is there any way to achieve this? 
I understand that such way of DOM manipulation is not preferred and can be considered dangerous, but i can't just adapt the whole platform to the new rendering system momentarily.

**Comment by drdaemos** [comment]
Update: managed to get it working by modifying the first variant like this:

    var temp = document.createElement('div');
    temp.innerHTML = html_string;
    var el = temp.querySelectorAll(this.$options.name)[0];
    this.$options.template = Vue.util.extractContent(el, true);
    this._isCompiled = this._isAttached = this._isReady = false;
    this.$mount(this.$el);
       
I guess this issue can be closed now, but i'm not sure if it is the sane way of doing such update.

**Comment by yyx990803** [comment]
I don't understand why it can "get complex to update view state". That sounds like a design problem in your view state. If you are doing things properly it should just be a matter of shoving in a new object/array fetched from the server.
