### ISSUE TITLE
vue-cli and vue-router do not play nicely together

### ISSUE THREAD

**Issue by maclover7** [vuejs/vue#2653]
### Vue.js version
1.0.16

### Reproduction Link
https://github.com/maclover7/pinger

### Steps to reproduce

- Create new vue-cli application, and convert to using CommonJS from ES6/Babel
- Install vue-router and attempt to initialize the router stack
- Add a `/foo` router, and have it be routed to a `Foo` component

### What is Expected?

The Foo component's template is served

### What is actually happening?

The page is blank.

**Comment by yyx990803** [comment]
1. Cannot reproduce. It is working fine for me. Are you sure you are looking at `http://localhost:8080/#!/foo`?

2. Please open this tyoe of issues to the [webpack template](https://github.com/vuejs-templates/webpack) instead of the core repo.

**Comment by maclover7** [comment]
:+1: - `http://localhost:8080/#!/foo` displays properly for me.

Why would the proper link be `http://localhost:8080/#!/foo` as compared to `http://localhost:8080/foo`?

**Comment by yyx990803** [comment]
You need to use router's HTML5 history mode to get rid of the hash.
