### ISSUE TITLE
Wrong style interpolation

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#2654]
### Vue.js version
1.0.21

### Steps to reproduce
```html
<div :style="{backgroundSize:'100%'}"></div>
```
### What is Expected?
```html
<div style="background-size:100%;"></div>
// or
<div style="background-size:100% auto;"></div>
```
### What is actually happening?
```html
<div style="background-size:100% 100%;"></div>
```

from css documentation of background-size:
Sets the width and height of the background image in percent of the parent element. The first value sets the width, the second value sets the height. **If only one value is given, the second is set to "auto"**

**Comment by simplesmiler** [comment]
This is a webkit misfortunate feature:
> WebKit-based browsers originally implemented an older draft of CSS3 background-size in which **an omitted second value is treated as duplicating the first value**; this draft does not include the contain or cover keywords.

Demo: https://jsfiddle.net/re2y30hh/
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#Browser_compatibility

**Comment by simplesmiler** [comment]
Vue was set to test prefixed version before the non-prefixed by https://github.com/vuejs/vue/commit/8dd598c2106c74932e20fa0bd9d53bc46ec04119 to fix https://github.com/vuejs/vue/issues/2219.
I think it should test non-prefixed version first, with the exception for buggy properties (like `filter`).

**Comment by yyx990803** [comment]
Does using non-prefixed name fix this duplicate value issue?

**Comment by simplesmiler** [comment]
Yep, `setProperty('background-size', '100%')` works and `setProperty('-webkit-background-size', '100%')` does not.

**Comment by yyx990803** [comment]
@simplesmiler ah ok. So we get bitten by browser vendors either way. Oh well... yeah let's check for non-prefixed version first, and treat `filter` as a sepecial case.

**Comment by simplesmiler** [comment]
Fixed with https://github.com/vuejs/vue/pull/2668
