### ISSUE TITLE
Vue triggers "componentchanged" forever in .vue files

### ISSUE THREAD

**Issue by alexcheninfo** [vuejs/vue#2656]
Sorry, I'm not sure if I should open this in the Vue CLI or the Vue CLI Webpack template repository. I'll migrate them if necessary.

The problem is, Vue triggers the `componentchanged` event of an [a-frame](https://aframe.io/docs/core/entity.html#Events) component forever.

This is the code:
```
<a-scene>
  <a-entity>
    <a-camera @componentchanged="onChange()">
    </a-camera>
  </a-entity>
</a-scene>

<script>
export default {
  methods: {
    onChange: function () {
     console.log('Changed!')
  }
}
</script>
```
Here's a demo: https://desolate-island-90618.herokuapp.com/#!/5EfhFj+R3DY1zo8JIGGQhosrSqn7p0t8pON9y5asxnM= (see console).

This only happens in `.vue` files. The problem doesn't occur in a simple `new Vue` instance: http://codepen.io/anon/pen/PNQdwO

(_Note:_ I also tested this code in a fresh `vue init webpack` project. The problem, seem to occur in `.vue` files.)

(_Note 2:_ The event is being triggered even if the `oldData` is the same as the `newData`.)

**Comment by yyx990803** [comment]
Vue only adds the event listener to the element... I'm not sure if this is a Vue issue or an A-Frame issue. But since it doesn't happen with vanilla Vue, maybe it's a `vue-loader` issue. I'd suggest making a minimal repro and open the issue at `vue-loader`'s repo.

**Comment by alexcheninfo** [comment]
Glad this time my issue has to do with Vue! (Well, it seems so far).

I opened the issue in the `vue-loader` repo: https://github.com/vuejs/vue-loader/issues/203

I added the steps to reproduce the bug + the live example.
