### ISSUE TITLE
template-tag, v-for, v-if together, not as expect

### ISSUE THREAD

**Issue by hisland** [vuejs/vue#2657]
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/hisland/f9gdg0d1/

### Steps to reproduce
i want a condition v-for

```
template(v-for="a in 6" v-if="a%2")
  p {{a}}
```
i got 0-5, i don't want this
p 0
p 1
p 2
p 3
p 4
p 5

```
  template(v-for="a in 6")
    template(v-if="a%2")
      p {{a}}
```

this is ok
p 1
p 3
p 5

### What is Expected?
can i use template(v-for="a in 6" v-if="a%2")?

**Comment by simplesmiler** [comment]
Closed with https://github.com/vuejs/vue/issues/2663
