### ISSUE TITLE
how to turn an object to reactive?

### ISSUE THREAD

**Issue by xiaofuzi** [vuejs/vue#2660]
is there a good way to turn an object to  be reactive after the vue instance was inited. 

I have to call Vue.set recursively to turn an object to be reactive, is there an confortable way?
thx

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

---

`vm.$set(key, object)` -> object is now reactive

**Comment by dguttman-jacada** [comment]
The above did not work for me. however, [this one](https://forum.vuejs.org/t/how-to-make-a-simple-reactive-object-that-can-be-shared-between-components/13199/3) did:
```javascript
var sharedObject = {/*...*/};
var tmpVm = new Vue({ data : { sharedObject } });
sharedObject = tmpVm.sharedObject;
```

and in my case, I was running it in a constructor of a class, so:
```javascript
constructor() {
  new Vue({ data: { reactive: this } });
}
```

**Comment by WhereJuly** [comment]
For anyone reaching to this point [Vue.observable(object)](https://v2.vuejs.org/v2/api/#Vue-observable) of Vue 2.6.0+ is the solution.
