### ISSUE TITLE
Iteration over Set's with v-for

### ISSUE THREAD

**Issue by msalestream** [vuejs/vue#2662]
I was building something the other day with a set, and noticed I couldn't seem to iterate over it with a v-for. 

Example (Use Modern Browser): 
https://jsfiddle.net/n9b9g0t0/3/ 

I understand Set's do behave a little differently then plain objects and array's, but I do see a massive benefit in adding them into v-for iteration. I am open to writing this addition if deemed useful.

**Comment by simplesmiler** [comment]
Closed if favor of https://github.com/vuejs/vue/issues/2410 (Support more collection data types in v-for).
