### ISSUE TITLE
条件渲染遇到嵌套的A元素工作不正常

### ISSUE THREAD

**Issue by NAMAKABE** [vuejs/vue#2664]
```
<a v-cloak v-for="i in 3">
	{{ $index }}
	<div v-if="true">
		<a>1</a>
	</div>
</a>
```
以上代码中，将会输出0121
而将内层的a变为div后，输出为011121

**Comment by phanan** [comment]
Nested `<a>` isn't supported by W3C, so your HTML is invalid. See [Template Parsing](http://vuejs.org/guide/components.html#Template-Parsing).
