### ISSUE TITLE
Test suite require old version of phantomjs

### ISSUE THREAD

**Issue by ludo237** [vuejs/vue#2665]
### Vue.js version
1.0.21+

### Reproduction Link
No jsfiddle ma simple code snippet

```
Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.1 @ /usr/local/bin/phantomjs.
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
```

### Steps to reproduce
- Clone Vue
- Install phantomjs from the site or homebrew or whatever
- run `npm install`

### What is Expected?
I expect to finish the installation

### What is actually happening?
Downloading another phantomjs version, the 1.9.19.

**Comment by yyx990803** [comment]
This is intended. There are breaking changes in PhantomJS 2.0 which requires non-trivial changes to the test suite. If anyone is interested feel free to try upgrading it.

**Comment by ludo237** [comment]
I'll try.

**Comment by josephzidell** [comment]
Is PhatomJS 2.x supported now?
