### ISSUE TITLE
@event expression is not handled correctly

### ISSUE THREAD

**Issue by pkawiak** [vuejs/vue#2670]
### Vue.js version
1.0.21

### Reproduction Link
http://codepen.io/pkawiak/pen/grezPW?editors=1111

### Steps to reproduce

Click `model.log` and `model.log()` buttons and observe console. Replace model by clicking `Replace Model` button and repeat clicking `model.log` and `model.log()` buttons.

### What is Expected?

1. Click `model.log()`: `Model 1` message appears in console.
2. Click `model.log`: `Model 1` message appears in console.
3. Click `Replace Model`: model is replaced.
4. Click `model.log()`: `Model 2` message appears in the console.
5. Click `model.log`: `Model 2` message appears in the console.

### What is actually happening?

1. Click `model.log()`: `Model 1` message appears in console.
2. Click `model.log`: `Model 1` message appears in console.
3. Click `Replace Model`: model is replaced.
4. Click `model.log()`: `Model 2` message appears in the console.
5. Click `model.log`: **`Model 1`** message appears in the console.

**Comment by paulpflug** [comment]
hmm strange, even 
```js
this.$set("model.log",m2.log)
```
doesn't change the `v-on:press='model.log'` binding to the `m2.log`
