### ISSUE TITLE
Pass props to component instance

### ISSUE THREAD

**Issue by abiaskosty** [vuejs/vue#2671]
Hi, 
I'm looking for a way to pass properties to a component instance which is created by `new` operator:  
```
var MyComponent = Vue.extend({ /* component options */ })
var myComponentInstance = new MyComponent()
```
Now having `myComponentInstance` I would like to pass some properties to it with ability to use one-way/two-way data binding.

For example, assuming `prop1` is one way and `prop2` is two-way, in a template I would use it like:
```
<my-component :prop1="field1" :prop2.sync="field2"></my-component>
```
In this case vue compiler would automatically bind `this.$data.field1` and `this.$data.field2` to `prop1` and `prop2` and props would be updated reactively. 

Therefore I'm looking for a solution to achieve such reactivity for `myComponentInstance`.
Possible solution might be to set up watchers like this:
```
// for one way binding
this.$watch('field1', function (newVal) {
  myComponentInstance.prop1 = newVal
})

// for two-way binding
this.$watch('field2', function (newVal) {
  if (myComponentInstance.prop2 == newVal) return // to prevent loops
  myComponentInstance.prop2 = newVal
})
myComponentInstance.$watch('prop2', function (newVal) {
  if (this.field2 == newVal) return // to prevent loops
  this.field2 = newVal
}.bind(this))
```
It is pretty verbose and I believe it repeats the same functionality that is already implemented inside vue.js to bind props when component is compiled inside a template.

May be I missed another solution in docs. I imagine it could look like:
```
myComponentInstance.$bind(this, {
  'prop1': 'field1',
  'prop2.sync': 'field2'
})
```

**Comment by yyx990803** [comment]
It's not recommended to use `new` to manually construct child components. It is imperative and hard to maintain. You probably want to make your child components data-driven, using `<component :is="xxx">` and `v-for` to dynamically render child components instead of constructing them yourself.

**Comment by abiaskosty** [comment]
yeah, this is the answer I was afraid to hear) Still thank you for the awesome framework!

**Comment by wychurry** [comment]
mark

**Comment by timur-gilauri** [comment]
> It's not recommended to use `new` to manually construct child components. It is imperative and hard to maintain. You probably want to make your child components data-driven, using `<component :is="xxx">` and `v-for` to dynamically render child components instead of constructing them yourself.

Situations when you need to manually create component instance still there. What if I need to dynamically insert component in a specific place of the page, that is not exist yet.  So how do I do that the best way?
