### ISSUE TITLE
[Doc] Should we have a gitbook edition of official guide like other plugins

### ISSUE THREAD

**Issue by qiansen1386** [vuejs/vue#2675]
I think the format of our docs are not so consistent. 
Since the docs of `vue-loader`/`vue-router`/`vuex` are all written with gitbook, the `core` should follow too, don't you think?

One more thing, we'd better provide a page listing out all the related docs of those important submodules, instead of hiding the links inside the guide. I have got to use Google to find them out sometimes :sweat_smile:

**Comment by posva** [comment]
I think the documentation is fine as it is now. It's beautiful and attract more people than gitbooks documentation

I don't understand your second point :confused: All of them are where they should be: in the related repository

**Comment by yyx990803** [comment]
The core docs has specific demands that cannot be easily customized in gitbook.

We may eventually move docs for all projects into the same place, but at this moment gitbook is used because it quick and takes little effort.

**Comment by qiansen1386** [comment]
@yyx990803 
Cool :+1: 

@posva 
I mean the new comers will not get a bigger picture of how many official plugins we have and what are they all about so easily. So we'd better have place to showcase those plugins.

**Comment by smolinari** [comment]
If anything, the guide could incorporate a page about the Vue community and its efforts and how to be a part of it (despite the links in the site navigation). The page could cover these topics.

- The Community 
    -  Forum 
    - Gitter Channel
- Third Party Contributions
   - The Awesome View Page
   - Contributing to Vue
- Contributing to Vue
   - The rules to contribute
   - The rules for issue reporting

Did I miss anything?

Scott

**Comment by yyx990803** [comment]
@smolinari I like that - we can turn the current Community dropdown into an actual page. Would take a PR for that.

**Comment by smolinari** [comment]
Actually, I'd keep the drop down, as I've used it very often to get to those different places. It would be disadvantageous to have to click through the page to get to those places. Maybe, at most, have an "About" linking to the page at the bottom of the pulldown, should anyone be interested in an explanation. I'd be glad to do the page. Let me see about adding it as a PR.

Scott

**Comment by smolinari** [comment]
Ok PR is up. https://github.com/vuejs/vuejs.org/pull/284

I think a better text for the direct link in the navigation would be "Join us!". :smile: 

Scott
