### ISSUE TITLE
v-for transition-mode

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#2677]
Why v-for do not support transition mode?
![transitionmode](https://cloud.githubusercontent.com/assets/16253399/14568306/fb2d9b56-0340-11e6-9215-2eca04c27766.gif)

**Comment by yyx990803** [comment]
Because `transition-mode` is only meaningful when you transitioning out/in exactly one item. If you want to have a out-in transition for your v-for items, consider using delays in your CSS transition/animations to achieve that.
