### ISSUE TITLE
v-el not working in some cases with script tags

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vuejs/vue#2681]
### Vue.js version
1.0.21

### Reproduction Link
http://www.webpackbin.com/4kjH1Xoy-

### Steps to reproduce
append a `v-el:titi` to a script tag (only in some configurations, sometimes is work)

### What is Expected?
`this.$els.titi` is defined

### What is actually happening?
`this.$els.titi` is undefined

**Comment by simplesmiler** [comment]
JSON LD is better handled with a directive: https://jsfiddle.net/simplesmiler/6ohn7a44/4/

**Comment by GuillaumeLeclerc** [comment]
Maybe directive works better but in my opinion it's semantically more correct to do a component in this case. Since component structure should reflect the DOM structure.

Apart from this debatable choice this is still a bug.
