### ISSUE TITLE
Transition/animate for reordering of v-for

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#2684]
Currently it seems that transitions on v-for can only be one when new items are added or removed from the list. But for lists one common thing is also that elements in the array can be reordered. To my understanding Vue is good at tracking element reorder and uses it when updating DOM, but it seems you cannot apply transition out of the box for element reorder. I think that would be a great feature to have.

**Comment by yyx990803** [comment]
You probably want this: https://github.com/vuejs/vue-animated-list

It's not part of core because it's CSS and IE10+ only. Custom JS hook for moving animations are more complicated and unlikely to be included in core.

**Comment by mitar** [comment]
I made this pull request to tell this in the guide: https://github.com/vuejs/vuejs.org/pull/280
