### ISSUE TITLE
Data function is called twice not once.

### ISSUE THREAD

**Issue by audinue** [vuejs/vue#2687]
### Vue.js version
1.0.21

### Reproduction Link
http://jsbin.com/doxonuviwe/edit?html

### Steps to reproduce

- Register a Vue component with data function.
```javascript

Vue.component('my-hello', {
	data: function() {
		console.log('hello')
		return {};
	}
});

new Vue({
	el: 'body'
});
```
- Instantiate the component.
```html
<my-hello></my-hello>
<my-hello></my-hello>
```
- You will see in the console (DevTool):
```
hello
hello
hello
hello
```

### What is Expected?
Data function should be called twice since there is only two instances of Vue component.

### What is actually happening?
Data function called four times.

### Quick Fix
Set the data in the `created` hook.
```
Vue.component('my-component', {
	created: function() {
		this.$data  = {}; // Set your data here.
	},
});
```

Hope this helpful.

**Comment by blake-newman** [comment]
Hello, the data hook is working as expected. 

The `data` hook is expected to be called per initialised component. For each `my-hello` component in the DOM the `data` hook will be called. The created hook is called once as this is when the component itself has been `created` by Vue.
