### ISSUE TITLE
示例问题

### ISSUE THREAD

**Issue by synchronizingtheworld** [vuejs/vue#2688]
http://cn.vuejs.org/guide/forms.html#Checkbox-1
http://cn.vuejs.org/guide/forms.html#Radio-1
http://cn.vuejs.org/guide/forms.html#Select_Options
这3个使用测试不出效果
http://cn.vuejs.org/guide/forms.html#number
这一个有什么用，怎么测试它的效果。

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by synchronizingtheworld** [comment]
@yyx990803   OK
