### ISSUE TITLE
component slot v-show @click not working

### ISSUE THREAD

**Issue by mrodriguez777** [vuejs/vue#2690]
hello, i have this probles
my main component
``` html
<template>
   <div>
     <wizard>
        <button @click="doThis">click</button>
        <div v-show="isVisible==true">show this</div>
   .......
</template>
<script>
export default{
   data(){
      isVisible: false
},
   methods:{
       'doThis': function(){
            alert(" this not work ='( ")
            return this.isVisible
         }
    }
}
```
wizard is another component with this template
``` html
<template>
   <div clasS='someClass'>
      <slot></slot> //simple slot
   </div>
</template>
<script>
.......
```

why not work?

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by mrodriguez777** [comment]
forget about this, i found the problem, i lost vue binding because de wizard plugin move the content of slot with jquery html() method.
any solution? thank!

**Comment by posva** [comment]
We still cannot help you if you don't provide a repro 😛 

Anyway, make sure to sure to ask the question on the [forums](forum.vuejs.org) or the [gitter chat](https://gitter.im/vuejs/vue). You'll get faster feedback. We keep questions out of issues :smile:

Closing this. Feel free to reopen the issue if you find out there really is a bug.
