### ISSUE TITLE
how i can build multiple SPA inside one peoject

### ISSUE THREAD

**Issue by mouafa** [vuejs/vue#2692]
Hi there,
first of all thanks Evan for your amazing work.

so, i'm building a large scale application, and i want to break it down to multiple SPA so for example if the user want to login then he'll use the 'auth' SPA under '/auth' route than he'll be redirected to the main SPA under '/', and if he want to access the dashboard it'll be in the '/dashboard' as an another SPA, anyway the project is much bigger and by doing his i'm trying to solve the problem if serving a heavy SPA to the user which in 80% of cases he'll only use 20% of it.

so is there anyone try to implement this before with webpack?

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by mouafa** [comment]
@yyx990803  sorry,
but do you have a solution?

**Comment by boussou** [comment]
What you describe is just the old way of doing things, a web page that will countain a vue.js instance, without the router. You already know how to do it.

at best, you could try to use pjax style.
