### ISSUE TITLE
why this.$data Can't get the data?

### ISSUE THREAD

**Issue by yczz** [vuejs/vue#2697]
In ublpanel formed created methods can't get this. $data, in V1.0.16 is correct

`<uborderlayout height="500px" collapsible="true" resizable="true">
		<ublpanel slot="top" height="10%">
				top
		</ublpanel>
</uborderlayout>`

`created: function() {
			console.log(this.$data);
}`

**Comment by posva** [comment]
Hello!

Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.
For instance we don't even know what `ublpanel` is 😅

**Comment by yczz** [comment]
this is code, in V1.0.16、V1.0.17 is correct

<a class="jsbin-embed" href="http://jsbin.com/gepete/embed?html,output">$data bug on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.35.12"></script>

**Comment by egoist** [comment]
this commit answers this question https://github.com/vuejs/vue/commit/d1788b98ac8dce4352e9f78810d13380449bd321

**Comment by posva** [comment]
@yczz You should directly access the value instead of going through `$data`. The problem is that you are trying to access a value from the props. `$data` is `data` and it doesn't mirror props properties

**Comment by yyx990803** [comment]
props are no longer merged into `$data`, they are directly defined on the instance itself.
