### ISSUE TITLE
如何为数据对象中的每项单独列出计算属性

### ISSUE THREAD

**Issue by 74sharlock** [vuejs/vue#2698]
https://jsfiddle.net/1c9wzxfd/4/

如代码，虽然单独为obj下面的每个数组项单独计算了求和的属性，但是显然不具备监控的作用。

如何才能为类似的对象的每项单独建立属性呢？computed是否可以做到？新手求解惑。

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
