### ISSUE TITLE
Directive: custom prefixes

### ISSUE THREAD

**Issue by nablex** [vuejs/vue#2705]
We have taken to prefixing our components by default but we would like to keep the same naming convention for our directives. However it seems the `v-` prefix is mandatory.

Is it possible to allow multiple prefixes? Or detect whether a prefix is present and only mandate `v-` if not?

**Comment by blake-newman** [comment]
The reason for this implementation is to make sure it is clear that it is a Vue directive. Achieved by a clear simple `v-` prefix. 

This makes it simple to integrate other tools, even angular, without clashes.

**Comment by simplesmiler** [comment]
@nablex slightly tangent, but you don't need to prefix your components except for the stylistic preference. Unless you are using global components, there is no chance for components to clash for the name, because the names are defined locally in the code that uses them.

**Comment by nablex** [comment]
We are building a tiny library of reusable components and have taken to naming them with a prefix to make it clear that they belong to the central library. The reason for the `v-` is clear, I just wish you could use your own, clashes being your own responsibility (as it is with components).

**Comment by simplesmiler** [comment]
@nablex again, unlike in angular, library developer does not decide on the name under which a component will be used in a the template, but library consumer does.

``` js
var GoodLibrary = require('GoodLibrary');

module.exports = {
  components: {
    Accordeon: GoodLibrary.GoodAccordeon, // library consumer decides on the name
  },
},
```
``` html
<!-- not <good-accordeon ...><good-accordeon> -->
<accordeon ...></accordeon>
```

**Comment by nablex** [comment]
@simplesmiler I get that that is possible but it is a feature we are not using. In light of our own development I am simply stating that it would be nice to be able to choose the prefix. Having more options is generally a good thing.

**Comment by ChristianKienle** [comment]
Sorry to jump onto this topic that late but why can't you simply register your directives with a name that includes your prefix alongside the `v-`-standard prefix?

```html
<button v-$prefix-icon="helloworld" />
```
