### ISSUE TITLE
"literal" modifier on custom directive causes v-if to be ignored

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue#2707]
### Vue.js version
1.0.21

### Reproduction Link
http://jsfiddle.net/5sH6A/317/

**Comment by blake-newman** [comment]
Quick fix: `<div v-test.literal="" v-if="false" >1. This should not be visible</div>`

Placing the literal before v-if resolves this bug for a quick fix. This is indeed a bug.

@yyx990803 Assigning to myself to look at.

**Comment by blake-newman** [comment]
@vuejs/collaborators FYI

This is due to the modifiers of directives being parsed to directives. so `.literal` is being fed to the previous directive even though it's not applied to that directive.

**Comment by simplesmiler** [comment]
Wowsie.
Does not happen with every directive/modifier though, e.g. `@click="doSomething" @mouseover.prevent` does not prevent the click default.

**Comment by blake-newman** [comment]
@simplesmiler Happens with terminable directives

Found the issue and creating PR now
