### ISSUE TITLE
rAF for mutation DOM

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2708]
Why vue dont use rAF for some function as appendChild, insertBefore, innerHTML?
It can to help reduce frame for update dom.

**Comment by posva** [comment]
What is rAF?

**Comment by yyx990803** [comment]
I've benched with rAF and it doesn't make any significant difference.

**Comment by AStaroverov** [comment]
Thx for answer

пт, 22 апр. 2016 г. в 18:56, Evan You <notifications@github.com>:

**Comment by rpkilby** [comment]
@posva I had to look this up to. Sounds like it's [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

**Comment by posva** [comment]
cool, thanks @rpkilby I couldn't find it 😆
