### ISSUE TITLE
The template tag dosen't work well in edge

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue#2709]
the ``template`` with ``v-for`` dosen't work well in browser ``edge``,code like:
```html
       <select class="choose" v-model="query_params.store">
            <template v-for="store in stores">
              <option :value="store">{{store.name}}</option>
            </template>
      </select>
```
the ``stores`` is empty arrary,the error is that evaluating expression 'store.name' error,but it work well like this:
```html
      <select class="choose" v-model="query_params.store">
          <option v-for="store in stores" :value="store">{{store.name}}</option>
      </select>
```

**Comment by simplesmiler** [comment]
Hello!

Although by the standard, `<template>` tag may appear everywhere, this is not the case in some browsers. Please read through [this section](http://vuejs.org/guide/components.html#Template-Parsing) for explanation and similar caveats.

For your particular case you would have to use `v-for` directly on the `<option>`. This is sufficient for simple cases. In case if you want to, for example, have two `<option>` per array item, you would have to prepare your data either with computed property or with a filter.

I'm closing this, as there isn't much we can do right now about a browser not following the standard.

**Comment by leaves4j** [comment]
@simplesmiler thanks for your reply, This question appeared in table with template also,and I test it in IE11 and Edge browser,it all dosen't work.It is necessary, I think, to add this question into the guid of vue.js,although it's a bug in browser
