### ISSUE TITLE
Properties are no longer updating in template in latest versions

### ISSUE THREAD

**Issue by aaronjpitts** [vuejs/vue#2710]
Is anyone else having issues with their data properties not updating in the template when changing them via a method? In vue devtools I can see they update fine, but never update in the template, they always remain the default value they were set in data

**Comment by posva** [comment]
Hi there!

Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described, this would help us a lot 😉
