### ISSUE TITLE
Pass Old Value To Method Handler

### ISSUE THREAD

**Issue by tpck** [vuejs/vue#2711]
I would like to request a feature where we could pass the original value to the method handler using the `v-on` directive.

Here is a [link](http://forum.vuejs.org/topic/3846/get-the-old-value-inside-of-a-method-handler-for-a-change-event) to my issue.

Example:

    <select v-model="example" v-on:change="update($event, $originalValue)">
        <option value="1">1</option>
        <option value="2">2</option>
    </select>

    <script type="text/javascript">
        methods: {
            update: function(event, originalValue) {}
        }
    </script>

**Comment by yyx990803** [comment]
Use a watcher on `example` since you are already using `v-model`.

**Comment by tpck** [comment]
@yyx990803 

I don't see how that will work. If I use a watcher to watch `example` and reset it if it fails some logic, this will cause that watcher to fire twice. Now if I reset the value manually (without Vue.js), then the watcher will not be aware that `example` has changed.

**Comment by tpck** [comment]
@yyx990803

I don't see how that will work. If I use a watcher to watch `example` and reset it if it fails some logic, this will cause that watcher to fire twice. Now if I reset the value manually (without Vue.js), then the watcher will not be aware that example has changed.

**Comment by sirlancelot** [comment]
You could run your `v-model` through a filter which saves the original value to a property which you can grab later.

Example: http://codepen.io/sirlancelot/pen/EKepqw?editors=1010

**Comment by tpck** [comment]
@sirlancelot 

Thanks! That did the trick.

**Comment by sirlancelot** [comment]
No problem! You may also consider doing your work in the filter handler instead of a DOM event. It's up to you and depends on the problem you're solving.
