### ISSUE TITLE
Component Dynamic-Props works incorrect in MS Edge

### ISSUE THREAD

**Issue by dsonet** [vuejs/vue#2715]
### Vue.js version
1.0.21

### Reproduction Link
http://vuejs.org/guide/components.html#Dynamic-Props

### Steps to reproduce
1.Focus the input element, press backspace, it doesn't work(nothing happened).
2.Move the cursor ahead, then you can use backspace to delete the input value, delete them all.
### What is Expected?
The message passed to child component should sync the input value (as this case it should be an empty string)
### What is actually happening?
Last one character stay the same in the child component.
![screenshot](https://cloud.githubusercontent.com/assets/457552/14761313/66501ae0-098f-11e6-824b-a8e960caa3b1.png)

**Comment by yyx990803** [comment]
Cannot reproduce on latest Edge/Windows 10.

**Comment by dsonet** [comment]
I tested on the this version:
  Microsoft Edge 37.14332.1001.0
  Microsoft EdgeHTML 14.14332
It's still stay the same. Maybe the bug is from Edge.
