### ISSUE TITLE
Custom class with getters and setters as data in VM

### ISSUE THREAD

**Issue by nervgh** [vuejs/vue#2718]
Hi

I try to use my own class as data in VM with getters and setters but it does not works. It is correct behavior?

Example https://jsfiddle.net/okv0rgrk/3019/

Thanks.

**Comment by jonagoldman** [comment]
data must be a plain object, you are giving it a class. its explained [in the docs](http://vuejs.org/guide/reactivity.html).

**Comment by yyx990803** [comment]
All prototype methods are ignored. Using non-plain objects as state is a rabbit hole to complexity and it is not supported by design.

**Comment by nervgh** [comment]
@jonagoldman , thanks, I read that
@yyx990803 , thanks

I has asked this question, because [this](https://jsfiddle.net/okv0rgrk/3020/) example works fine.

**Summary**:
- not works
```html
<input v-model="symbol" type="checkbox" />
<input v-model="test" type="checkbox" />
```
```js
new Vue({
    el: '#app',
    data: obj
})
```
- works
```html
<input v-model="bar.symbol" type="checkbox" />
<input v-model="bar.test" type="checkbox" />
```
```js
new Vue({
    el: '#app',
    data: {
    	bar: obj
    }
})
```

**Comment by yyx990803** [comment]
you will see that the getter is not reactive.

**Comment by nervgh** [comment]
hmm, exactly :cry:

**Comment by milaniliev** [comment]
Sorry to revive an old issue - I couldn't find any relevant discussion of this elsewhere.
@yyx990803, I encounter this problem when trying to separate my presentation logic (in the Vue VM) from the client-side business rules and persistence code (in a model). Having my model be a class instance is pretty natural.

Does the fact a VM's `data` attributes doesn't support class instances mean a Vue VM instance is intended to contain presentation, business and persistence logic? Or is there some other pattern I haven't considered?

Thanks for creating a reactive view library that can be used progressively instead of taking over your app, by the way.

**Comment by manast** [comment]
hmm, interesting to read about this limitation. For me, a class with custom getters is equivalent to computed properties in Vue, the only difference is that I handle the computed properties somewhere else. I agree this an increase side effects and complex edge cases, but that could be left to the user, after all, Vue is supposed to be un-opinionated, but by making this somewhat artificial limitation it is in fact imposing an opinion which in some cases it is not trivial to work around.

**Comment by sirlancelot** [comment]
This works fine for me. It just can't be the root data object. Plus you will want to store the original reference to your class instance object. Vue will call the getters and setters every time.

**Comment by manast** [comment]
yeah, reactivity is tricky, probably better to have a limitation than a more complex codebase. Despite inconveniences there are always workarounds, so I take back my previous comment :).

**Comment by Feofilakt** [comment]
Hello. It is 2020 now and still there is nothing about https://github.com/vuejs/vue/issues/2718#issuecomment-214003100 in documentation. Maybe I missed it? In other case it looks like vue user must read not only documentation but also all yyx990803 comments throughout the internet.

**Comment by sirlancelot** [comment]
https://vuejs.org/v2/api/#data

> **The object must be plain**

It's in bold even.

My comment from 2018 (over two years ago) is still valid, it's _possible_ to use class instances, they just can't be the root data object.

**Comment by jonagoldman** [comment]
Yup, is very clear in the docs as I pointed in my 2016 comment.

**Comment by Feofilakt** [comment]
> It's in bold even.

Thank you for pointing out. I haven't looked in this section. Was thinking that API is just a reference and all the details are containing in the "guide".
