### ISSUE TITLE
this.$addChild is not a function

### ISSUE THREAD

**Issue by obonyojimmy** [vuejs/vue#2719]
am trying to create a dynamic component in a defined component as below :

main component ( should dynamically create the component `extform-input` when called )

```
 ...
components: {
       'extform-input' : ExtformInput
  
    },
methods : {
      changeType: function () {
       var self = this 
      var TheComponent = this.$options.components['extform-input'];
      self.$addChild(TheComponent);
}

...
```

i get error `self.$addChild is not a function`

**Comment by sirlancelot** [comment]
`Vue#$addChild` was removed in Vue 1.0

**Comment by yyx990803** [comment]
Use the `parent` option.

**Comment by obonyojimmy** [comment]
@yyx990803  a code example would be really helpful

**Comment by simplesmiler** [comment]
@obonyojimmy something along https://jsfiddle.net/qsm2axry/
