### ISSUE TITLE
v-show and v-bind:style override bug

### ISSUE THREAD

**Issue by loujiayu** [vuejs/vue#2722]
demo: https://gist.github.com/loujiayu/2cbe1413303a0d189514c15e32191129

It works fine in chrome, but in firfox :style override v-show style.
`<div :style="style" v-show="open" ></div>`

and if change the order of directives:
` <div v-show="open" :style="style" ></div>`
override issue appears in chrome.

**Comment by phanan** [comment]
Might be related: #2592.

**Comment by yyx990803** [comment]
Do not use plain string styles. Use an object.
