### ISSUE TITLE
Warn on mixed bind and mustache interpolation?

### ISSUE THREAD

**Issue by rpkilby** [vuejs/vue#2725]
Reading #2721, should Vue warn a user if using mixed v-bind and mustache interpolation?

**Comment by yyx990803** [comment]
It already does if you are using the dev build: https://jsfiddle.net/1zuw6be5/

**Comment by rpkilby** [comment]
Oh, right. I could have *sworn* this wasn't an issue, but was confused by the lack of a warning. Didn't notice that he was using the production build...
