### ISSUE TITLE
[Bug ?] Render a component with component definition bound to is attribute

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#2727]
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/oe7axeab/789/

### What is Expected?
According to 1.0.19 release note, components can now be rendered dynamically by bounding is attribute with a component definition.
In the fiddle I try to make the example work but b component is not rendered. Did I miss something here ?
Thanks

**Comment by pespantelis** [comment]
Please check [this section](http://vuejs.org/guide/components.html#Dynamic-Components) of  the documentation carefully.

[Working demo](https://jsfiddle.net/pespantelis/eazkjcu4/)

**Comment by AlexandreBonaventure** [comment]
Ok, I got it. We have to pass a constructor via Vue.extend
Heres a working fiddle https://jsfiddle.net/oe7axeab/790/

**Comment by AlexandreBonaventure** [comment]
@pespantelis Thanks, but it was not the behaviour I was looking for. 
See https://github.com/vuejs/vue/releases/tag/v1.0.19. 
I don't think it appears in official doc yet.
