### ISSUE TITLE
Updating model during watch is not causing dom to be updated

### ISSUE THREAD

**Issue by bohaozhang** [vuejs/vue#2728]
### Vue.js version
1.0.21

### Reproduction Link
http://jsfiddle.net/6c0k3ynq/2/

### Steps to reproduce
When you start typing in the first input box, eg, enter 2, all the other boxes stay as 1, then if you continue to type, 3, then the other boxes will update to having 2 in them, it seems its always 1 step behind.

### What is Expected?

all input box content should be synchronised

### What is actually happening?
I think the DOM update is not being queued while in a watch block.

**Comment by FadyMak** [comment]
Hey there! It seems like you've provided the wrong Fiddle link.

**Comment by bohaozhang** [comment]
Sorry.
this is the right one http://jsfiddle.net/6c0k3ynq/2/

**Comment by simplesmiler** [comment]
Hello!

This is a limitation of ES5: http://vuejs.org/guide/list.html#Caveats
Replace `this.radius.size[1] = v` with `this.radius.size.$set(1, v)` and things will work: http://jsfiddle.net/6c0k3ynq/4/

**Comment by bohaozhang** [comment]
Thank you simplesmiler. 
That solves the problem.
