### ISSUE TITLE
Using ID that are Leading digits comes error

### ISSUE THREAD

**Issue by Ende93** [vuejs/vue#2729]
# Vue.js version

1.0.21

# Reproduction Link

https://jsfiddle.net/ende993/wmhLbxk6/

# Steps to reproduce

no

# What is Expected?

element should be rendered

# What is actually happening?

passing leading digit ID that dont be escaped  to document.querySelector will comes error

**Comment by yyx990803** [comment]
This is a DOM error, you cannot use numbers as Ids. This has nothing to do with Vue.
