### ISSUE TITLE
How can I reference DOM elements by v-el directive which have declared v-for directive?

### ISSUE THREAD

**Issue by miusuncle** [vuejs/vue#2732]
RT

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you can reference the elements with `this.$el.querySelectorAll`.
