### ISSUE TITLE
参数特性不可用？

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue#2734]
http://vuejs.org.cn/guide/forms.html#number

<input v-model="age" number>

问题：

添加“number"属性后，并未达到效果，依然可以输入任意字符.

版本：
Vue.version
"1.0.21"

**Comment by stormhouse** [comment]
请用`type="number"`

**Comment by Cuixote** [comment]
type="number" 不是 HTML5 特性 ?

**Comment by clovery** [comment]
应该是 vue 的一个 bug，源码可以参考这里[directives/public/model/text.js](https://github.com/vuejs/vue/blob/dev/src/directives/public/model/text.js#L68)，转换规则出了问题。
pc 端可以用 `type="number"`，移动端需要自己解决。

**Comment by Centaur** [comment]
html5的 type="number" 实在很鸡肋，个人意见是还不如基于 type="text" 自定义一个 number-input 组件

**Comment by egoist** [comment]
`number` 特性只是在你输入类似 '4' 时自动转换为 4，你需要的是 `type="number"`

**Comment by yyx990803** [comment]
这个不算 bug 吧。`number` 的描述本来就不具备限制输入的功能，只是在写到 model 时进行类型转换而已。现在改成限制输入的话是 breaking change，1.x 不会考虑。不过下个大版本会改。

**Comment by Cuixote** [comment]
看来是我理解错误了。

强烈建议 把文档中误导我的 <input v-model="age" number> 修改为 <input type="number" v-model="age" number >
