### ISSUE TITLE
Submit event trigger by press 

### ISSUE THREAD

**Issue by iahu** [vuejs/vue#2736]
### Vue.js version
1.0.16

**Comment by yyx990803** [comment]
Please follow the issue reporting guidelines and provide clear description and reproduction steps.

**Comment by budiadiono** [comment]
This issue might related to this SO question: http://stackoverflow.com/questions/35297759/vue-js-uncaught-typeerror-cannot-read-property-forcontext-of-null

**Comment by iahu** [comment]
Think you, @budiadiono .

**Comment by budiadiono** [comment]
You're welcome @iahu. I have same problem here. Seems you have already make PR for this fix on https://github.com/vuejs/vue/pull/2737, but it's not merged yet. Any reason why? I can't understand the conversation on that PR :)

**Comment by budiadiono** [comment]
Ah forget it, the problem is on my own code. I have several custom directives in my app, the error was causing by `unbind` callback on those directives -- while removing fragment I did `fragment.remove()` I've changed to `fragment.destroy()` then the problem solved.

**Comment by timonreinhard** [comment]
@iahu Are you using vue-validator on that form? Asking because I'm facing the same issue but could not yet reproduce it in a fiddle using vue.js only.

**Comment by iahu** [comment]
Hi @timonreinhard ,
No, I am not using vue-validator. I am also could not reproduce it. But I have make a PR to fix this issue. You may have to modify the source code by yourself.
see here -> https://github.com/vuejs/vue/pull/2737/commits/54cd73e86d460ef8be08a5f7ae4dbe858797a512
