### ISSUE TITLE
In vue watch, after remove Obj key, Obj does not sync

### ISSUE THREAD

**Issue by FQZhang** [vuejs/vue#2742]
### Vue.js version
1.0.20

### Reproduction Link
http://codepen.io/ryanzhang/pen/XdPOZw

### Steps to reproduce
I passed paraments in component:  styles and bg(key in styles)
### What is Expected?
when toggle button, the Object needs to insert {"bg":{}} or delete {"bg":{}}
### What is actually happening?
when switch is on, the {"bg":{}} is inserted, when switch is off, {"bg":{}} is not deleted

**Comment by yyx990803** [comment]
You need to use `Vue.delete`: http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats

**Comment by FQZhang** [comment]
Hi yyx990803,

Thank you for your reply. That works for me.
I wondering that:  if the v-if was false, then should the div with v-if="" be automatically removed from DOM? 
I got this warning: [Vue warn]: Error when evaluating expression "styles.bg.colour".

**Comment by yyx990803** [comment]
That's expected, because you deleted `styles.bg`. You can use `styles.bg && styles.bg.colour`.

**Comment by FQZhang** [comment]
That doesn't work. Because styles.bg.colour always false

**Comment by yyx990803** [comment]
I'm not seeing the error warning - isn't it working?

**Comment by FQZhang** [comment]
the object deletion works.
the v-if, still does not work

**Comment by yyx990803** [comment]
Please open a separate issue for the `v-if` problem, preferably with a more isolated codepen reproduction.

**Comment by FQZhang** [comment]
Could you please look at this : https://jsfiddle.net/72oozov2/6/
