### ISSUE TITLE
'v-model' make all vue reactive stuck.

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vue#2744]
### Vue.js version
1.0.21

### Reproduction Link
http://s.codepen.io/leonz/debug/NNLJpo

### code causing the issue.
```
<div class="input-price-container">
      <span>Message is: {{ title }}</span>
      <input type="text" class="input-price" placeholder="请输入协商后价格" v-model="title">
 </div>
```
### Steps to reproduce
1. open the link with wechat(6.3.16) on iphone6 (9.3.1).
2. input any thing into the <input>
    repeat these actions:
       'input', 'delete' , 'close keyborad', 'open keyboard' 
3. somethings, your input will not update to the <span>
   If this occur, all reactive data will stop to work. (nothing will render until you refresh the page)

PS: issue is easier to reproduce with 'sogou input'.

my EN is poor，so I describe the issue again with chinese:
1.把重现连接发给自己的微信，然后在微信打开连接。
2.在输入框里重复的输入一些内容，快速的多输入一点

期待结果：输入的内容和页面上展示区的内容保持一致。
实际结果：展示区的内容和突然不在改变，然后再也不刷新了。另外，页面上的所有reactive变量都不会刷新页面了，切换到其他页面也一样不会渲染reactive的变量，感觉起来就像reactive的watcher线程卡死了。

### **normal：**
![image](https://cloud.githubusercontent.com/assets/13174059/14844078/619f2f4a-0c87-11e6-9712-24e762783a45.png)
![image](https://cloud.githubusercontent.com/assets/13174059/14844076/5ef6ad72-0c87-11e6-9d69-70c9fca9c97c.png)

### **issue occur**
![image](https://cloud.githubusercontent.com/assets/13174059/14844064/4fc088c8-0c87-11e6-82f2-541edaf5a0f7.png)
![image](https://cloud.githubusercontent.com/assets/13174059/14844064/4fc088c8-0c87-11e6-82f2-541edaf5a0f7.png)

**Comment by yyx990803** [comment]
This is a known issue with Wechat's embedded browser and should be fixed with this commit: https://github.com/vuejs/vue/commit/8b847e20fc7b878ac1f428fe4aa094983d287c02 (should be out in next release)

**Comment by njleonzhang** [comment]
@yyx990803 when will the next release come out?
