### ISSUE TITLE
v-for breaks after drag'n'drop DOM manipulation

### ISSUE THREAD

**Issue by mayakokits** [vuejs/vue#2745]
Attempt to use [Dragula](https://github.com/bevacqua/dragula) alongside with Vue
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/17j1L9c1/1/

### Steps to reproduce
1. After loading the fiddle, drag the *third* item somewhere out of the `<ul>` and drop it there, so that Dragula’s `cancel` event fires (see console log) -- OR -- alternatively drag the first item to the third position.)
2. Click the *add item* button.

### What is Expected?
Another item to be added to the list

### What is actually happening?
Uncaught TypeError: Cannot read property 'parentNode' of null

Adding new items works fine after other drag'n'drop operations, also after dragging and cancelling other items than the last one. Dragging and cancelling the last item seems to throw in most cases.

Appearantly Dragula puts the actual `<li>` element back to it’s former position in the DOM, it still has its `__v_frag` object. Yet Vue seems to lose track of it somehow... ?

I found a workaround for this issue by replacing the array with a fresh array (`refreshModel()` in the fiddle) and thus triggering Vue to rerender the v-for. This is not an elegant solution though, as any watchers on the array will fire too, altough the array's order didn't change in case of a `cancel` event.
The workaround is here: https://jsfiddle.net/L8y4fry1/1/

**Comment by obonyojimmy** [comment]
i recommend listening to native drag events in component and call method on what is to be achieved , i mnaged to create a dynamic component system with native drag and drop its acctully not that hard ie : 

```
### template
<div id="{{ randomid }}" class="form-group maincomponentclassname" @dragleave.stop.prevent  @dragover.prevent="newdragover" @dragenter="newdragenter" @drop="newcomponentdrop" @dragend="dragend"  @dragstart.self="dragnewcompont"  draggable="true">
		
		
	  </div>

### methods 
 dragnewcompont: function(e) {
  e.dataTransfer.setData('text', dataset );
//call some event or set data to drag transfer
},
newcomponentdrop: function(e) {
   console.log('newcomponentdrop')
  var data = e.dataTransfer.getData("text")
 ////call some event or manaipulate data
}
```
NB : you might need to recreate / destroy dynamic componets during the drag /drop events 

hope this helps .
