### ISSUE TITLE
Component is considered a fragment instance after Vue update

### ISSUE THREAD

**Issue by YerkoPalma** [vuejs/vue#2747]
### Vue.js version
1.0.21

### Reproduction Link

[Mi personal site](https://github.com/YerkoPalma/YerkoPalma.github.io)

### Steps to reproduce
1. Clone the repo
```bash
git clone https://github.com/YerkoPalma/YerkoPalma.github.io.git
```
2. install and run it
```bash
npm install && gulp
# or
npm install && npm run build
```

### What is Expected?
The site runs as before

### What is actually happening?
It throws 
```
app.production.js:1382 [Vue warn]: Attribute "align" is ignored on component <rights> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment_Instance
```
for every single component. I'm using `vueify` and gulp for development, I'm not pretty sure if this is a Vue error or maybe vueify error. I'm not using any vue plugin and the rest of the dependencies can be checked in the repo link. If any further information is needed please let me know

**Comment by rpkilby** [comment]
What version were you using before the update?

**Comment by YerkoPalma** [comment]
1.0.8

**Comment by posva** [comment]
Can you try to extract the problem in a jsfiddle. It's quite hard to find the bug using an entire site 😅

**Comment by jimzitrone** [comment]
usually putting the template into an empty div solves the problem when i get that error:

`<template>
  <div>
    <div :class="{ 'pull-left': align === 'left', 'pull-right': align === 'right'}">
      <p class="copyright">© {{ (new Date()).getFullYear() }} - {{author}}</p>
    </div>
  </div>
</template>`

**Comment by posva** [comment]
@YerkoPalma Any updates on this?

**Comment by YerkoPalma** [comment]
I can't find a way to reproduce this in a different project, but I've seen others having the same issue, as you can see in [here](https://github.com/yuche/vue-strap/issues/182). I've tried what @RufusK said with no luck. Anyway, when I start my projects with `vue-cli` I never had a problem, so I think it might be some error using vueify directly. If I can provide any further information just let me know, unfortunatelly I can't do more than that for now.

**Comment by posva** [comment]
If you cannot reproduce the issue in a different environment, check your build config, something must be missing. Try creating a new project and including your components one by one.

**Comment by posva** [comment]
I tried debugging your project but cannot see the issue in the js or vue files. I don't use gulp nor vueify so I cannot check those but I recommend you creating a new project with vue-cli and start from there

**Comment by YerkoPalma** [comment]
I'll rebuild my project with vue-cli, I think is the best option. But I still think this is a weird case, but not related with Vue. I guess there are some specific environments where this issue appears. 

Anyway, I think you can close the issue for now, as it looks like a bad build setting or something, not a Vue issue :smile:

**Comment by posva** [comment]
Sure. Please if you find more information ping me here 😉
