### ISSUE TITLE
vue updated model before teardown component

### ISSUE THREAD

**Issue by FQZhang** [vuejs/vue#2750]
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/72oozov2/15/

### Steps to reproduce
1. Turn on "Set Background",
2. Turn on "Set Background Colour"
3. Turn off "Set Background"
4. Look at Browser DevTools

### What is Expected?
No error displaying. app keeps on working

### What is actually happening?
Got an error: [Vue warn]: Error when evaluating expression "styles.bg.colour": TypeError: Cannot read property 'colour' of undefined

The error stops app to keep on working

**Comment by zigomir** [comment]
@FQZhang You can solve it like so: https://jsfiddle.net/72oozov2/16/

I don't think this is Vue's problem per se, because in my opinion using `Vue.set` or `Vue.delete` inside watcher will always allow for such edge cases when error will appear.
