### ISSUE TITLE
The transition of vue. Js system 

### ISSUE THREAD

**Issue by lee134134134** [vuejs/vue#2752]
I'm layer at the same time each add a father and son transition。code example：

.ay-modle-view(v-if="isButtonList" @touchmove.prevent="" @click.prevent.stop="switchButtonList(false)" transition="fadeIn")
            .ay-big-button-list(v-if="isButtonList" transition="fade")

But sub-layer won't trigger fade-leave。How can I solve，tanks

**Comment by yyx990803** [comment]
Contained elements are removed as part of the parent element, so no transitions are triggered. You can however use CSS selectors to apply transition behavior in the parent element's transition classes:

``` css
.fadein-leave .ay-big-button-list {
  /* ... */
}
```
