### ISSUE TITLE
display undefined

### ISSUE THREAD

**Issue by chenyouxiang** [vuejs/vue#2759]
when data like this
data:{
   item:{}
}
then bind v-model="item.id" display "undefined"
i think display empty string is right

**Comment by phanan** [comment]
No, `item.id` is clearly undefined, and obviously not a string, even an empty one…

**Comment by chenyouxiang** [comment]
display "undefined" in textbox is not proper，when undefined why not show empty
display empty in v1.0.2

**Comment by chenyouxiang** [comment]
when you show "undefined" in a textbox, the user can not understand

**Comment by chenyouxiang** [comment]
why not show empty like v1.0.2

**Comment by yyx990803** [comment]
Why don't you just define it, like the docs suggested?

**Comment by chenyouxiang** [comment]
i'm lazy to define it
show empty string is better like other template do
like the smarty template engine show empty string when variable is not define

**Comment by blake-newman** [comment]
Then problem found...

> i'm lazy to define it

Define it or you will get unexpected results. It's much better to declare your data structures.

**Comment by chenyouxiang** [comment]
but is have so much code write in v1.0.2

**Comment by chenyouxiang** [comment]
can not show empty string like most template engine?

**Comment by blake-newman** [comment]
What is the difference between: 

```
data:{
  item:{}
}
```

and 

```
data:{
  item:{
    id: ''
  }
}
```

One line? Can't do all the work for you.

**Comment by azamat-sharapov** [comment]
@chenyouxiang Vue.js does not try to solve all issues, it's goal is to be lightweight. You can create small helper function to convert `undefined` into empty string:
```
function get (object, prop) {
  if (typeof object[prop] !== 'undefined') {
    return object[prop]
  }
  return ''
}
```

Note, that it's recommended to define all properties in you `data` for better maintainability and reactivity.

**Comment by arturhood** [comment]
@azamat-sharapov How can I add your piece of code to a Vue application, is it possible to add the helper function so it applies to all variables the template engine uses?

That is a beautiful solution in the case where new data in a NoSQL database may include new props that old data doesn't have... to make Vue not crash when displaying old data.
