### ISSUE TITLE
v-model中checkbox无法与整数数组匹配

### ISSUE THREAD

**Issue by xusimin1008** [vuejs/vue#2763]
```
<label class="checkbox-inline col-md-2">
    <input type="checkbox" value="1" v-model="stars_query"> <i class="fa fa-star" v-for="n in 1"></i>
</label>
<label class="checkbox-inline col-md-2">
     <input type="checkbox" value="2" v-model="stars_query"> <i class="fa fa-star" v-for="n in 2"></i>
</label>
 <label class="checkbox-inline col-md-2">
       <input type="checkbox" value="3" v-model="stars_query"> <i class="fa fa-star" v-for="n in 3"></i>
</label>
```

为什么在vue实例中
存在stars_query: [1, 2, 3],
却无法与上面的html中的checkbox进行匹配，
而换成stars_query: [‘1’, ‘2’, ‘3’]则可以，
但我想要的是stars_query是一个整数数组。

**Comment by posva** [comment]
Hello,

This is an expected behaviour because `value` is a string. If you want a number you can write `:value="1"` to make it a number.

Please tell me if that wasn't the problem, I don't speak chinese

**Comment by xusimin1008** [comment]
Thanks for your answer!
It works, not a problem.@posva
