### ISSUE TITLE
eval debounce doesn't work?

### ISSUE THREAD

**Issue by DophinL** [vuejs/vue#2770]
### Vue.js version
1.0.21

### Reproduction Link

http://forum.vuejs.org/topic/3901/eval-debounce-doesn-t-work (there is a fiddle link)

**Comment by yyx990803** [comment]
`$eval` doesn't work that way... it's like returning a function vs. calling that function.

**Comment by DophinL** [comment]
Thanks for reply:)
so `"update | debounce"` means  return a function which will be delayed when called?
but `"update() | debounce"` means what?

and is there a way to simplify `update('remark') | debounce 500` cause it appears at many places?
