### ISSUE TITLE
Vue Currency Filter Decimal Place not working.

### ISSUE THREAD

**Issue by libern** [vuejs/vue#2773]
```
{{ amount | currency '₫' 0 }}
```

The 0 simply not taking effect.
The result is always xxx.00

**Comment by libern** [comment]
@yyx990803 Links: http://jsfiddle.net/5sH6A/334/

**Comment by phanan** [comment]
Don't think this feature is released yet. Vue v1.0.21 is out 21d go, when the feature #2676 was added 14d ago.
