### ISSUE TITLE
sequence of vue.data(), route.data() and HTML render

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vue#2774]
I have multi-layer data in vue component, which may look like:

```
data(){
  return {
        id: '',
        Info: {
          address: {
            address: '',
            name: '',
            detail: '',
          },
          ...........
       }
   }
}
```
I update the `info`, in vue-router hook `router.data() `, 

```
route: {
     data(transition) {
        .........
        api.getInfo(id).then(function(data) {
            this.info = data
        })
    }
}
```

So there may be a gap between data update and html render.
can VUE ensure that data update firstly and then the html render happen?
can I write the info as:

```
data(){
  return {
        id: '',
        Info: {
          address: {},
          ...........
       }
   }
}
```

**Comment by blake-newman** [comment]
Vue router is likely to be streamline, as we rebuild it for use with 2.0. There will be some issues opened up in vue-router, to discuss a good implementation. There may be some already.

**Comment by simplesmiler** [comment]
@njleonzhang you probably want `route:activate` hook instead `route:data`.
Also it's not necessary to define all the fields inside of an object. You can do something like this:
``` js
data: function() {
  return {
    id: undefined,
    info: undefined,
  };
},
```
``` html
<template v-if="info !== undefined">
  <!-- use `info` fields -->
</template>
```

**Comment by njleonzhang** [comment]
@simplesmiler why should I use `router:active`? Can you give me some explanation?

**Comment by simplesmiler** [comment]
@njleonzhang `route:activate` hook is called before component is shown, so that rendering will only happen after your data has arrived.
You can read more in docs: http://vuejs.github.io/vue-router/en/pipeline/data.html#details

**Comment by Steviey** [comment]
Link is broken

**Comment by posva** [comment]
@Steviey https://github.com/vuejs/vue-router/blob/1.0/docs/en/pipeline/data.md#details
