### ISSUE TITLE
[Suggestion] Vue 2.x should follow strict Semantic Versioning.

### ISSUE THREAD

**Issue by young-steveo** [vuejs/vue#2776]
I [posted about this on the forum](http://forum.vuejs.org/topic/553/new-backwards-compatible-functionality-in-patch-versions-of-vue) a few months back, but I think it fell through the cracks.  It would be awesome if the Vue project started adhering to strict [Semantic Versioning](http://semver.org/).

Past versions of Vue 1.x have included a *lot* of new functionality in patch versions rather than bumping the minor version.  This can be tricky when trying to figure out if new functionality can be used.

For example, [`v1.0.21`](https://github.com/vuejs/vue/releases/tag/v1.0.21) added support for using a string of multiple classes in `:class` bindings.  Since Vue is using a versioning scheme that **looks** like semver, it's not clear on the surface that `v1.0.20` doesn't support this feature.

The semver issue is highlighted by the bold message at the top of the release notes for [`v1.0.20`](https://github.com/vuejs/vue/releases/tag/v1.0.20):

> **This is a small patch release with only bug fixes. There were a few new features in 1.0.19 - make sure to check it out.**

With semver, a bump from `v1.0.19` -> `1.0.20` already implies that only bug fixes are included.

**Comment by yyx990803** [comment]
This is something I wanted to do, but the practical difficulty in isolating new features and patch fixes costs a lot more than you think.

The 1.x process has basically followed the development model of "every commit goes into `dev`" - so when we are releasing a patch, inevitably it includes some new features. Separating features and bug fixes into separate branches and keeping them in sync until a minor release makes the development model a lot more complex.

That said - I'm not convinced about every little detail re semver, especially for projects with marketing concerns. (It is often easy for people to argue in favor of strict semver when version numbers have practically no impact on the success of their project, but that is not the case for Vue). The most important part is the major/breaking bumps. If we really want to go super-strict semver, we could've just hidden those features and later announce them as part of 1.1 ;)

**Comment by young-steveo** [comment]
@yyx990803 Isolating new features from patches is a solved problem.  It's presumptuous to think that I do not understand the costs.  My argument is that the benefits outweigh the costs, though I understand that on this point we may disagree.

However, I can't get on board with the marketing claim.  What marketing benefit can be derived from calling a version `1.0.21` v.s. calling it `1.1.0`?

Finally, some anecdotes:

Lodash follows strict semver but I don't see jdalton having a marketing problem.  If anything, *more* developers use lodash instead of underscore.js simply because lodash follows semver and underscore.js does not.  This level of stewardship is greatly appreciated by their users.

React follows semver.  They did some goofiness by switching from `0.14` to `15.0` this year, and that *was* due to marketing concerns, but it's interesting to see them embracing a very large major version number.

I'm happy to hear that you will "explore the possibility of semantic minor releases" and I hope you can come to the conclusion that it will only better the community.

**Comment by yyx990803** [comment]
@young-steveo what I'm basically saying is - it's not worth it for 1.x at this point, but we will reconsider for 2.x.

**Comment by young-steveo** [comment]
@yyx990803 Gotcha.  Thanks!
