### ISSUE TITLE
v-bind:multiple doesn't work properly

### ISSUE THREAD

**Issue by geodeveloper** [vuejs/vue#2779]
Hi, I've tried to create a component (which is a wrapper for <select>) and I want the multiple attribute to be rendered based on condition.

I've set-up an example here: https://jsfiddle.net/hg6hjo6f/3/ and the really strange behaviour is on example 3 (selected3 component) which is exactly as selected1 component, the only difference is that selected1 uses dynamic "multiple" attribute and selected3 uses static "multiple" attribute.

Is this kind of a bug or i'm missing something ?

Thank you.

**Comment by simplesmiler** [comment]
While it appears to work in some cases, Vue 1.x does not currently support using `v-model` on components. Instead you should use a `.sync` prop, or `$emit` to signal for the parent to change the value.

Demo on the `.sync` approach: https://jsfiddle.net/hg6hjo6f/3/

**Comment by geodeveloper** [comment]
Thanks for the clarification. I was surprised it worked in some cases.
