### ISSUE TITLE
Official paid support

### ISSUE THREAD

**Issue by leon-andria** [vuejs/vue#2781]
Hi, 
Can we talk an official paid support on vue.js ? 
Please contact me on andrianarivony@gmail.com.

Please remove this after you acknowledge this as it' was really hard to find out the right channel to contact you.

Léon

**Comment by blake-newman** [comment]
[Vue.js' Patreon campaign](https://www.patreon.com/evanyou)

**Comment by leon-andria** [comment]
Thank you, can you bridge me to Evan to able to contact him by email. I would like to able to discuss with him.

Léon

**Comment by boussou** [comment]
Hi, otherwise If he cannot answer --> I can. Besides, I live in france.

**Comment by leon-andria** [comment]
Excellent. I'm French also. you can contact me on skype andrianarivony@gmail.com or by this email.
I will remove this email after.
