### ISSUE TITLE
Proposal: Give access to component's internal functions

### ISSUE THREAD

**Issue by leonardo-ferreira-caldas** [vuejs/vue#2783]
### Vue.js version
1.0.21

### Proposal
I dont know if there is a way to do the following scenario today, but if there is not, i really think would be great to include it in the next VueJS version. 

Let's say that a modal component has two internal methods named "open" and "close", and by using v-ref, it could be possible to do the following code.

    <modal v-ref='modalTest'> ... </modal>

    <button v-on:click='modalTest.open()'>Open</button>
    <button v-on:click='modalTest.close()'>Close</button>

**Comment by yyx990803** [comment]
Why don't you try it before opening the issue?...

**Comment by leonardo-ferreira-caldas** [comment]
Actually i had tried, but after your reply, i did some more tests and it worked. 

Sorry for the inconvenience.
