### ISSUE TITLE
$appendTo on Circle Benchmark (fork of jashkenas's benchmark) on Vue 2.0

### ISSUE THREAD

**Issue by boussou** [vuejs/vue#2785]
Not very urgent, nor important.

I tried to make this old jsfiddle work (it no longer works on Evan JSfiddle account).
I wanted to compare to various other frameworks (I'll add ampersand to the list) so I quickly fixed all of the dependancies.
I run into issues with the API changes and deprecated items of vue 2.0

The Fiddle (I hate jsfiddle so it is jsbin):
http://jsbin.com/gabubu/edit?html,css,js,console,output

 in peculiar: "v-bind:style" vs "v-style": is it the right syntax?

<script type="x-template" id="vue-template">
    <div class="box"  v-bind:style="style">{{content}}</div>
</script>
    
`             box.$appendTo('#grid');`
should become
 ```
           box.$mount();
            $('#grid').append(box.$el);
```

It executes, but no display. 

(and I don't want to dig into the Vue source code to understand why).

Maybe Evan consider this benchmark's no longer relevant?
(I just wanted to put this newly improved performance to the test)

(for the record: The fixed reworked fiddle with working v0.12  http://output.jsbin.com/jomocu/6)
Thanks

**Comment by boussou** [comment]
RTFM ;-)
Reading here [https://vuejs.org/guide/class-and-style.html](https://vuejs.org/guide/class-and-style.html) I changed it to return an object for style binding.

Not we got 1 (visible) circle running.

**Comment by yyx990803** [comment]
Please read the 2.0 feature tracking list. $appendTo has been deprecated.

**Comment by boussou** [comment]
I know.

I went over the past issues too. I just wanted to be certain that the $mount() that generates the $el was the good way to do. 

Circle benchmark with 2.0: It is fixed now: http://jsbin.com/gabubu/edit?html,js,output

Indeed It is faster (compared to the v0.12 above)

**Comment by boussou** [comment]
JsFiddle versions 
http://jsfiddle.net/azimuth/4u9pLhy3/2/
