### ISSUE TITLE
the position of "v-for" is different in template and option

### ISSUE THREAD

**Issue by elover** [vuejs/vue#2786]
here is  code  [https://jsfiddle.net/nansir/2wmwL0sj/](https://jsfiddle.net/nansir/2wmwL0sj/)

```html
<div id="demo">
  <select v-model="selected">
  <template v-for="option in options">
    <option  value={{option.value}}>
    {{ option.text }}
  </option>
  </template>
</select>
<span>Selected: {{ selected }}</span>
<br>
<select v-model="selected2">
    <option v-for="option in options2" value={{option.value}}>
    {{ option.text }}
  </option>
</select>
<span>Selected: {{ selected2 }}</span>
</div>
````
```js
new Vue({
  el: '#demo',
  data: {
    selected: '',
    options: [
    ],
    selected2: '',
    options2: [   
    ]
  },
  ready:function(){
  this.selected = 'B'
	setTimeout(()=>{
	this.options = [{ text: 'One', value: 'A' },
      { text: 'Two', value: 'B' },
      { text: 'Three', value: 'C' }]
  },10);
  
  this.selected2 = 'B'
	setTimeout(()=>{
	this.options2 = [{ text: 'One', value: 'A' },
      { text: 'Two', value: 'B' },
      { text: 'Three', value: 'C' }]
  },10)
  }
})
```
![cbce4d1c-7587-455c-a4c5-4e5355717544](https://cloud.githubusercontent.com/assets/4330913/14941031/89bcb60a-0fc0-11e6-9f63-250d69dd75c9.png)

**Comment by rigor789** [comment]
It does indeed act differently, but you are setting selected before you even have the list of options. If you move the `this.selected = 'B'` into the `setTimeout` it works as expected.
https://jsfiddle.net/2wmwL0sj/1/

**Comment by yyx990803** [comment]
http://vuejs.org/guide/components.html#Template-Parsing

Do not use `<template>` inside `<select>` because its behavior is inconsistent between browsers. There's nothing Vue can do in 1.x, but in 2.x if you use string templates you will not be subject to these exceptions.
