### ISSUE TITLE
Render only first custom component with list rendering

### ISSUE THREAD

**Issue by sztm** [vuejs/vue#2788]
### Vue.js version
edge version in JFFiddle

### Reproduction Link

https://jsfiddle.net/6ya0v5ct/2/

### Steps to reproduce
put two different custom components with list rendering(my-elem, my-elem2) in same parent component

### What is Expected?
render two lists like this
```
1.1
1.2
...
2.1
2.2
...
```

### What is actually happening?
render only former list

**Comment by yyx990803** [comment]
Incorrect markup. HTML5 is not XML - `<xxx/>` is treated as **opening tag only**.

**Comment by sztm** [comment]
Thanks!
