### ISSUE TITLE
VueJS :disabled is not working with an array

### ISSUE THREAD

**Issue by dominikveils** [vuejs/vue#2792]
Hello,
Example is here: https://jsbin.com/sayaqefuxo/edit?html,js,output

First select is not changing the 'disabled' state when 'Toggle' button is clicked. But the second select is working...
Whats wrong with my code? How can I use array for :disabled feature?
Is that a bug or just a feature?

**Comment by posva** [comment]
Hi!

Please make sure to sure to ask the question on the [forums](forum.vuejs.org) or the [gitter chat](https://gitter.im/vuejs/vue). You'll get faster feedback. We try to questions out of issues :smile:

About the question, this is a caveat: http://vuejs.org/guide/list.html#Caveats

The update of a raw value in an array cannot be detected and therefore the `disabled` attribute was never updated, you can have an object instead: https://jsbin.com/dikerowisi/edit?html,js,output

**Comment by dominikveils** [comment]
@posva thank you for your answer.
I've asked on forums yesterday, but no one answered there...
Now I see its working!

Thank you again.
