### ISSUE TITLE
vue2.0 发布出来后 可以使用.vue文件来实现 服务端和客户端的同构吗？

### ISSUE THREAD

**Issue by yjj5855** [vuejs/vue#2793]
我目前没有使用.vue 而是用的传统的.js .html .css 方式写的，想问一下以后会不会支持.vue文件用在服务端？

**Comment by weilao** [comment]
issue 是用来提提交 BUG 的。
提问题请到[论坛](http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87)

**Comment by yyx990803** [comment]
可以
