### ISSUE TITLE
Passing objects as attribute in initial HTML and weird things

### ISSUE THREAD

**Issue by vedmant** [vuejs/vue#2795]
Hi, sorry for bothering, I'm just starting with Vue, I have some weird issues with Vue when I pass initial data as attribute:

            <comments
               :comments='{"total":2,"per_page":15,"current_page":1,"last_page":1,"from":1,"to":2,"items":{"1":{"id":86,"rel_id":81,"rel_type":"album_items","user_name":"Anatolii Vedmant","user_link":"http:\/\/localhost:8000\/profile\/1","user_image":"\/media\/0\/103\/conversions\/thumb.jpg","content":"Another comment","date":"39 seconds ago","mine":true},"0":{"id":85,"rel_id":81,"rel_type":"album_items","user_name":"Anatolii Vedmant","user_link":"http:\/\/localhost:8000\/profile\/1","user_image":"\/media\/0\/103\/conversions\/thumb.jpg","content":"Comment","date":"3 minutes ago","mine":true}},"count":2}'
            ></comments>

First problem is that items sort order doesn't have any effect, it renders it always the same way, I use `v-for="comment in comments.items"`. In this example "Another comment" should be first, but it's last, even if I reverse back items array on backend.

Second problem, when I try to unshift items array `this.comments.items.unshift(comment)` it throws exception TypeError: this.comments.items.unshift is not a function. Here is screenshot with this.comments.items dump http://screencast.com/t/TmKvizmcgiok.

This might be something really simple, maybe I misuse Vue when passing object as param from template. But it looks like obvious way to pass initial data from backend without making lots of ajax requests, as I have lots of comments blocks on the page.

Thanks!

**Comment by yyx990803** [comment]
You are using an object, not an array. In ES5, object key enumeration order is not guaranteed (it is specified in ES6 however that is not guaranteed to be implemented in every browser). Also, `unshift` is an Array-only method.

**Comment by vedmant** [comment]
Oh, yeah, items supposed to be array, thanks, I didn't notice this!
