### ISSUE TITLE
v-show will not work properly when other css class has "display:none;"

### ISSUE THREAD

**Issue by yunhor** [vuejs/vue#2798]
v-show 在元素其它类包含有 display:none; 时，监控变量为true时 输出是空，这样的渲染的结果是元素不可见！不知道是我刚用Vue不知道是不是有其它的用法？
我简单在 toggle修改了下：
`   function toggle() {
        el.style.display = value ? 'block' : 'none';
      }
`
暂时解决这个问题

**Comment by yyx990803** [comment]
既然用了 v-show 就不要用 css 去控制了... 用 v-show 绑定的值去控制啊

**Comment by yunhor** [comment]
可是有些场景下原本就有这些类存在，只是简单的用v-show控制下 ，比如 在 登录页面 有好几个form 切换登录/注册/忘记密码 我只是简单在每个form加个变量用v-show控制显示 。但这些form有许多其它css ,其中就有题目所说的 隐藏 样式 ，总不能手工将其它地方的样式改掉吧

**Comment by yyx990803** [comment]
v-show 要保留初始 display 值，因为你也可能需要 display inline。既然这个元素是需要动态切换的你的 css 就不应该默认是 display: none，你改样式显然比改 Vue 的源码合理。

**Comment by yunhor** [comment]
有道理，只是实际操作中，有时是改造旧代码，有时是从别人现有工作开始，有时就会碰到不是很方便改动样式，另外，也是偷懒，不想去详细跟踪样式设计，所以简单修改了事

**Comment by yunhor** [comment]
也许终极方案是扩展一个指令或是v-show能带外饰符或是参数
