### ISSUE TITLE
v-bind:class 数组中使用对象无效

### ISSUE THREAD

**Issue by xiaoniao** [vuejs/vue#2799]
### Vue.js version
1.0.21

在教程 http://vuejs.org.cn/guide/class-and-style.html#对象语法 中有这么一句话
![alt text](http://liuzhuangzhuang.com/wordpress/wp-content/uploads/2016/05/1.png)

按教程执行后显示

![alt text](http://liuzhuangzhuang.com/wordpress/wp-content/uploads/2016/05/2.png)

代码是这样
![alt text](http://liuzhuangzhuang.com/wordpress/wp-content/uploads/2016/05/3.png)

应该渲染成 static class-a class-b class-c 
但现在渲染的是 static class-a classB classC

**Comment by posva** [comment]
Hi,

This is an expected behaviour, you're passing a literal object, `classB` is just parsed as a string.
You cannot interpolate the variable `classA`, (that's an es6 feature btw). I think that would be possible in vue 2 though. Anyway you can also use a computed property:

```js
computed: {
  classes: function () {
    var classes = {}
    classes[classB] = isB
    classes[classC] = isC
    classes[classA] = true
    return classes
  }
}
```

**Comment by yyx990803** [comment]
你没理解用法，你的代码和例子不一样啊
