### ISSUE TITLE
Can't set "v-for" value into "slot" when constructing a component.

### ISSUE THREAD

**Issue by wolfFN** [vuejs/vue#2801]
Vue.js version       1.0.13

When constructing a compoment, I want to use v-for and <slot>，to generate different html code for different input.
like 
```javascript
contents: ['home-info', 'profile-info', 'messages-info', 'settings-info']
```

```html
    <div class="tab-content"  v-for="item in contents">
        <div class="tab-pane">
            <slot name="{{item}}">
            </slot>
        </div>
    </div>
```

and when using the component,

```html
                <vue-tab  :titles.sync="formData.tabData.titles" :contents.sync='formData.tabData.contents'>
                    <div slot='home-info'>
                        Home slot Info
                    </div>
                    <div slot='profile-info'>
                        Profile slot Info
                    </div>
                </vue-tab>
```
In the component,
If I set name="{{item}}" to other elements like div, we can get the right work.
And if I use
```html
            <slot name="home-info">
            </slot>
``` 
 It works two.
But when combine slot with v-for,  this didn't work. Can't set value into slot.

Thanks for your patience.

**Comment by simplesmiler** [comment]
Hello!

Since 1.0 `{{ interpolation }}` inside of attributes is deprecated. Use `:name="item"` instead.
Working demo: https://jsfiddle.net/simplesmiler/Lrk9sxjf/36/
