### ISSUE TITLE
请问Vue可以与RequireJS结合来组织模块吗？

### ISSUE THREAD

**Issue by OneNewLife** [vuejs/vue#2803]
我现在不想用Browserify或者Webpack来打包，也不想用Vue-Router，想直接用RequireJS来组织我的模块，现在我的做法是这样：
``` javascript
// main page
require.config({
	baseUrl: MIS.STATIC_ROOT
});
require(['lib/jquery', 'lib/vue', 'components/login', 
	'components/register'], function(login, register) {
	
	var index = {
		init: function() {
			login.methods.greet()
			register()
		}
	}

	index.init()

})
```
``` javascript
// component
define(['lib/jquery', 'lib/vue'], function($, vue) {
	var login = new Vue({
			  el: '#login',
			  data: {
			    name: 'Vue.js'
			  },
			  // 在 `methods` 对象中定义方法
			  methods: {
			    greet: function (event) {
			      // 方法内 `this` 指向 vm
			      alert('Hello ' + this.name + '!')
			      // `event` 是原生 DOM 事件
			      alert(event.target.tagName)
			    }
			  }
			})
	return login.methods.greet
})
```

这样是无法实现的，不知道我代码是否有错，或者说 Vue 现在还没有提供这个特性？求指教

**Comment by yyx990803** [comment]
理论上用任何模块系统都可以，这个应该是你自己用法有问题。

**Comment by sinoon** [comment]
是的，实际上你看Vue打包出来的代码是UMD规范的，所以浏览器规范都兼容

2016-05-05 1:13 GMT+08:00 Evan You <notifications@github.com>:

**Comment by cmal** [comment]
@OneNewLife 请问您最后如何解决的该问题？因为项目需求，我尝试直接在html script tag中引入vue，但 requirejs 报错 `Uncaught Error: Mismatched anonymous define() module` 。可能是由于vue.js中使用了`define`的缘故。参考requirejs的文档 http://requirejs.org/docs/errors.html#mismatch 。所以目前我还没有找到解决的办法。不知是否有其他的解决方案。十分感谢！

**Comment by OneNewLife** [comment]
@cmal 

你遇到的是匿名模块不匹配的错误，我当时并没有遇到过，具体你是怎么用的我不清楚。首先要明确一点： vue.js 使用了 define  是没有什么毛病的。你在 HTML 中引入 vue 具体是怎么引入？是否遵守官方 API 了？手动引入模块的时候要注意模块命名的问题，你下面的链接里面提供了 4 个解决方案，你是否一一尝试过了？没有代码我只能分析到这里了。

使用新框架（Vue、Angular、React）的时候建议你还是用 Webpack，上手非常快，如果你坚持使用 RequireJS 的话，最好先熟悉一下 AMD 模块系统，不然你还是会遇到很多问题。

**Comment by cmal** [comment]
@OneNewLife 感谢您的耐心回答。在您的指导下我查看了requirejs的文档，仍然有疑问、没有解决问题，还是想请教您：

刚开始是直接在html中加入script tag的方式，使用 `<script src="//some-cdn/vue.js"></script>`的方式引入vue，加入该标签会立即得到上述匿名模块不匹配的错误。

我的项目使用的是grunt-contrib-requirejs，grunt中requirejs的option如下：
```
    files.forEach(function (file) {
        options[file] = {
            options: {
                baseUrl: path.join(__dirname, '../public'),
                include: file,
                create: true,
                out: path.join(__dirname, '../public/asset/', file + '.js'),
                optimize: process.env.NODE_ENV == 'local' ? 'none' : 'uglify',
                preserveLicenseComments: !false,
                packages: [
                  ...
                ]
            }
```

在渲染的模板文件中是这样来用的：
```
  <script type="text/javascript">
    require.config({
      baseUrl: '/asset',
      packages: [
            ...
        ]
    });
    require(['wx/js/secuinfo'], function (secuinfo) {
      secuinfo.init(<%-JSON.stringify(params)%>);
    });
  </script>
```

由于发现vue.js是UMD的方式，所以我将html中的script tag去掉，用bower安装了vue，在上述两段代码的`packages`中加入了
```
            {
                main: 'vue.common',
                location: '/lib/vue/dist',
                name: 'vue'
            },
```

结果发现vue并没有被成功编译到requirejs生成的文件中，在生成的js文件中找不到vue字样，而且不知为何，本来dev环境不会被concat的js代码被concat成超长的行了。只是在packages中加了vue.common的结果。

我又将上面的vue.common改为vue，requirejs生成的文件仍然找不到vue的相关内容。

不知道这种改动是否是4个解决方案中的第1种的正确做法。

以往我用过这种方式成功引入了新的package，比如echarts和一些CommonJS模块，但用同样的方式对vue不起作用了。

---------

4个解决方案中的第二个：当前我的代码中，jquery是通过bower安装的，然后通过script tag引入的。现在我尝试用相同的方式引入vue，会出现匿名模块不匹配的错误。

同样请教一下原因？ 为什么同样的方式jquery可以，vue却不行？

---------

而第三个、第四个说的好像不是我遇到的情况。

另外我现有的项目中使用的是requirejs，是打算用vue做一些局部的尝试，我没有切换到webpack的权限。

期待得到回复，十分感谢！

**Comment by cmal** [comment]
已经可以运行了。使用API的方式在代码中require一下vue就好了。
