### ISSUE TITLE
组件中this.$el选中注释

### ISSUE THREAD

**Issue by wolfFN** [vuejs/vue#2807]
Vue.js version 1.0.13

尤大，好

开发组件时，我使用以下代码引入模板
```javascript
Vue.component('vue-swiper', {
    template: __inline('./vue-swiper.html'),
    ready: function() {
```
此时html中代码如下：
```html
<!--
@file xxx
@author xxx
@date 2016-05-04 15:05:48
 -->
<div class="vue-swiper">

</div>
```

此时在js中使用 this.$el获取元素时，只能获取到前面注释的text节点，如果删除掉注释，就可以获取到后面的div节点。

**Comment by reverland** [comment]
fragment components?

**Comment by yyx990803** [comment]
模板里的注释会让组件变成 fragment instance。你可以在 __inline 函数里面做个处理把注释剥掉。

2.x 不会有这个问题
