### ISSUE TITLE
:class bindings multiples classes on a string and arrays

### ISSUE THREAD

**Issue by ElMatella** [vuejs/vue#2808]
### Vue.js version
1.0.21

Hi, on the last Vue release, the following feature was added:
```
:class bindings now support using a string of multiple classes
```
So it works well for: `<div :class="{ 'a b c': true }"></div>`

but doesn't for `<div :class="[ true ? 'a b c': 'd e' ]"></div>`

Is there a particular reason? 

Here is a jsFiddle reproducing: https://jsfiddle.net/o5u4utrp/

**Comment by yyx990803** [comment]
This has been fixed in the dev branch and will be working as expected in the next release.
