### ISSUE TITLE
TypeError: Cannot define property:__v-for__1, object is not extensible.

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue#2809]
I have a list of objects to which I don't need observation to happen. The recommended way I've read about is to use `Object.freeze()` which works great _except_ when I need to iterate over frozen objects in an array.

### Vue.js version
1.0.21

### Reproduction Link
http://codepen.io/sirlancelot/pen/aNPaNZ

### Steps to reproduce
- Create an array of frozen objects with `Object.freeze()`
- The array should NOT be frozen, just the items within it.
- Iterate over the array with `v-for=""`

### What is Expected?
Array is rendered without errors.

### What is actually happening?
An error is emitted in the console: `Uncaught TypeError: Cannot define property:__v-for__1, object is not extensible.`

**Comment by yyx990803** [comment]
When `v-for` is rendered with data objects and has no `track-by` key, it will attempt to add a hidden key to the objects in order to track them. When the object is frozen, this strategy cannot be used, so you need to explicitly use a `track-by` key in this case. I've added a warning for it.

**Comment by sirlancelot** [comment]
Thanks! I submitted a PR to update the documentation for this as well.
