### ISSUE TITLE
is there a date filter like angular date filter?

### ISSUE THREAD

**Issue by dengjianan** [vuejs/vue#2811]
### Vue.js version
1.0.16

**Comment by dengjianan** [comment]
i want a filter to formte the date

**Comment by dengjianan** [comment]
maybe i can try to code it, then other people can reuse it

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by posva** [comment]
Hi http://lmgtfy.com/?q=vue+filter+date

look at vue-filter.
