### ISSUE TITLE
Vuejs Security Errors with ChromeOS Kiosk App CSP

### ISSUE THREAD

**Issue by patsplat** [vuejs/vue#2813]
### Vue.js version
1.0.16

### Reproduction Link
See below

### Steps to reproduce
1. git clone https://github.com/patsplat/vuejs-chrome-example.git
2. Open chrome://extensions/
3. Check the Developer mode box.
4. Click Load unpacked extension.
5. Browse to the vuejs-chrome-example directory
6. Click Launch
7. Under "Inspect Views" click "application.html"

### What is Expected?
to see text "A custom component!"

### What is actually happening?
get an error in the console:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".
```

Content Security Policy for Chrome Apps: https://developer.chrome.com/apps/contentSecurityPolicy
How to create a Kiosk App: https://support.google.com/chrome/a/answer/6137027?hl=en

**Comment by patsplat** [comment]
https://github.com/vuejs/vue/blob/dev/src/global-api.js#L143-L150

**Comment by yyx990803** [comment]
Please use the CSP-compliant build: http://vuejs.org/guide/installation.html#CSP-compliant-build

**Comment by patsplat** [comment]
ty!
