### ISSUE TITLE
<select>的v-model,无法区分" "和 0

### ISSUE THREAD

**Issue by azad112358** [vuejs/vue#2815]
### Vue.js version
1.0.21 (22也有此问题)

### Reproduction Link
http://jsbin.com/bupoxudaqo/edit?html,js,output

### Steps to reproduce
点击链接,即可看到,当是字符串'0'的时候没这个问题
### What is Expected?
select框里选择的是"否"
### What is actually happening?
select框里选择的是"请选择"

**Comment by fnlctrl** [comment]
``html
<select v-model="testmodel">
    <option value="undefined">请选择</option>
    <option value="1">是</option>
    <option value="0">否</option>
  </select>
```
“请选择”对应undefined呗

另外，既然要显示"请选择"，为什么默认值要是0（显示对应否）？

**Comment by egoist** [comment]
`<option>请选择</option>` 不设置 `value` 就行了

**Comment by yyx990803** [comment]
select 值比对的时候用的是 `==`，为的是能够 match 数字和字符串。这里你不要设置 value 即可。
