### ISSUE TITLE
Should use a white list instead of `element.toString()` to check if a tag is a custom tag?

### ISSUE THREAD

**Issue by JasinYip** [vuejs/vue#2816]
Vue.js version: 1.0.16

Good day~

We are using PhantomJS to test our web application which have been using a `<audio>` tag in some pages. It looks all good in browsers, but when we testing in our PhantomJS environment, it triggered a error like this:

```
[Vue warn]: Unknown custom element: <audio> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

I found the issue https://github.com/vuejs/vue/issues/1389 that Evan said Vue is using `element.toString()` to check if the tag is a browser-support tag. Obviously, PhantomJS is not supporting the media tags such as `<audio>` and `<video>`, so Vue will consider these tags are custom tags then trigger the above error.

I think the way that Vue is using to check if a tag is a custom tag might not the best way, maybe using a white list(which list all W3C standard tags) is a better way to check that?

**Comment by phanan** [comment]
Actually Vue checks the element against a list of [common tags](https://github.com/vuejs/vue/blob/13e033551ad2b23f1d5883926c4786d767bb72ba/src%2Futil%2Fcomponent.js#L12), just like what you suggested. `el.toString()` test is only triggered in non-production environments for warnings. It seems the common tag list is missing several tags though (`audio`, `video`, `track`, `t(head|body|foot)`…) @yyx990803 or am I simply misunderstanding anything here?

**Comment by JasinYip** [comment]
But why we need to test `el.toString()`?

If the white list is included all of W3C standard tags, all things we need to do is checking the tag's name is in the list.

**Comment by yyx990803** [comment]
Please upgrade to latest version.

**Comment by JasinYip** [comment]
It still happens...😭

**Comment by yyx990803** [comment]
Should be addressed once https://github.com/vuejs/vue/issues/3090 ships.
