### ISSUE TITLE
ES2015 Template String Delimiters not working in component templates

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue#2818]
### Vue.js version
1.0.22

### Reproduction Link
http://codepen.io/Codebryo/pen/ZWwRRJ

### Steps to reproduce
If the Vue object is configured to use the ES2015 Template Delimiters `${` `}` they are not working when used inside the components template code.
```
`
  <div>
  	${dataMsg}
   </div>
`
```

### What is Expected?
It should print out the correct dataMsg.

### What is actually happening?
It's crashing as JS can't resolve the reference. I know it's

I know this is expected behavior but I would like to know if there is a way around or maybe define the delimiters only outside of template strings and enforce the default `{{` `}}` inside those templates.

**Comment by yyx990803** [comment]
Please read the docs. Use Vue.config.delimiters.

**Comment by codebryo** [comment]
@yyx990803 Hi Evan, I have nothing but respect for you :)
But please take a look at the code example. 
I guess I miswrote my question. I am using the delimiters configuration. The problem is that it then enforces me to use those in the inline templates of the components as well. And there it causes errors as it's trying to use the JS default and vue is not able to use the delimiters in there.

**Comment by codebryo** [comment]
```
// Use the new ES2015 delimiters
Vue.config.delimiters = ['${', '}']

var MyComponent = Vue.extend({
	data: function(){
  	return {
    	innerMsg: 'Hello'
    }
  },
  template: `
  <div>
  	${innerMsg}
  </div>
  `
})
```

That's the code where `innerMsg` can't be resolved. Is it possible to ignore the delimiters for the component declaration?

**Comment by vinicius73** [comment]
I believe this is not "blame" the vuejs.
It is the javascript you want to "interpret" this expression, so I think it's virtually impossible to use this syntax.

JSX has a similar problem with class, having to use className.

**Comment by codebryo** [comment]
Okay thanks @vinicius73 that's what I figured.
I didn't intend to blame Vue in any way. It's just that it would be interesting to still use the the ${ } delimiters in the main view of the app, but the default {{ }} in the templates.
And the vue config is globally.

**Comment by vinicius73** [comment]
It's really boring, visually would be good.
It took me a while to understand why it was not working in your example.

**Comment by yyx990803** [comment]
@codebryo that's not really Vue's concern because it's JavaScript syntax... you can just use plain strings and concat them with `+` instead of template strings, or better yet, don't use inline strings for templates.

**Comment by anboo** [comment]
Vue.config.delimiters = ['${', '}'] and new Vue({delimiters: ['${', '}']}} not working.

**Comment by hyperking** [comment]
@anboo Your delimiter settings is not the same in your template string.

try changing 
```
<div class="author">{$author}</div>
```
into
```
<div class="author">${author}</div>
```
Nevertheless, I'm having issues with Vuejs accepting the new delimiter setting. My app uses Jinja2 and will not properly parse the template tag.

If you are using Jinja2 templating engine to render html page you may need to wrap the block with
```{% raw %}...insert js code here...{% endraw %}```
