### ISSUE TITLE
Slot attribute is not removed from compiled HTML.

### ISSUE THREAD

**Issue by jschatz1** [vuejs/vue#2820]
### Vue.js version
1.0.16

### Reproduction Link

http://vuejs.org/examples/modal.html

### Steps to reproduce
1. Open http://vuejs.org/examples/modal.html and view the source of the resulting HTML. This also works in the latest version. I noticed that vue attributes are removed from compiled HTML. `slot` is not removed. 

2. View result:  

<img width="390" alt="modal_component_-_vue_js" src="https://cloud.githubusercontent.com/assets/322665/15113357/c1bef20a-15c1-11e6-8ae6-c2379b65abb1.png">

### What is Expected?
The `slot` attribute should be removed from compiled HTML.

### What is actually happening?
The `slot` attribute is included in compiled HTML

**Comment by yyx990803** [comment]
This is intentional to allow styling slot elements.
