### ISSUE TITLE
在计算属性computed中使用for in进行循环对象，IOS环境下双倍计算的bug

### ISSUE THREAD

**Issue by hasbug** [vuejs/vue#2822]
目前有这么个需求，我一个订单页面，每个订单有单价和数量，我使用计算属性进行计算总价。
在计算属性computed中使用for in来遍历对象计算，在pc和安卓端正常，但在iso环境下出现的结果不正确，经过打印输出发现，进行了双倍的计算。
例如有：订单一单价为10块，买了2、订单二单价为20块，买了1.
正常应该是10X2 20X1 ，pc和安卓正常。
但在ios下出现10X2 20X1 10X2 20X1的结果。

**Comment by yyx990803** [comment]
不要用 for in 循环数组，这是错误的用法，不能保证不同引擎下行为一致。

**Comment by hasbug** [comment]
哦，我懂了。我还以为是对象···
