### ISSUE TITLE
表单的number特性不生效

### ISSUE THREAD

**Issue by icarusion** [vuejs/vue#2832]
[demo](http://output.jsbin.com/gijalahaza)

文档中说的：

如果想自动将用户的输入保持为数字，可以添加一个特性 number：
```
<input v-model="age" number>
```

但是并没有作用啊？

**Comment by pespantelis** [comment]
https://jsfiddle.net/pespantelis/qj7kk3s2/

Try to change the value of two fields and you can see the difference  :)

**Comment by icarusion** [comment]
原来是这样使用的，感谢

**Comment by uedkx** [comment]
如果想自动将用户的输入转为 Number 类型（如果原值的转换结果为 NaN 则返回原值），可以添加一个特性 number：

<input v-model="age" number>

以上是管网文档的描述，跟上面的demo对比起来还是有差异的，比如：如果原值的转换结果为 NaN 则返回原值
上面的demo是加了number会做一个Number 和 String的转换。
