### ISSUE TITLE
dblclick event trigger  click event

### ISSUE THREAD

**Issue by lmh2072005** [vuejs/vue#2833]
### Vue.js version
v1.0.22

### Reproduction code
    <div v-on:click="showMsg()" v-on:dblclick="showDblMsg()">test</div>
### What is actually happening?
when i dblclick the element ,the click event triggered twice.

**Comment by phanan** [comment]
I can't say it better than jQuery docs (it's jQuery of course, but the same applies):

> It is inadvisable to bind handlers to both the `click` and `dblclick` events for the same element. The sequence of events triggered varies from browser to browser, with some receiving two `click` events before the `dblclick` and others only one. Double-click sensitivity (maximum time between clicks that is detected as a double click) can vary by operating system and browser, and is often user-configurable.

So, avoid this. If you must, implement your own mechanism, for example utilizing `setTimeout()`. Nonetheless, it's not a Vue issue.
