### ISSUE TITLE
为什么代码里都不写分号呢?

### ISSUE THREAD

**Issue by wuxiaolan91** [vuejs/vue#2835]
### Vue.js version
1.0.16

**Comment by ACookieBear** [comment]
本来我也习惯写分号的，但是用尤大提供的vue-cli时写分号会报错，后来就不写分号，然后慢慢觉得分号很丑了，然后回去写java时也时不时忘记写分号

**Comment by iniaks** [comment]
代码风格的问题，不觉得ES6+去分号，代码非常清爽么

**Comment by fnlctrl** [comment]
See: https://github.com/yyx990803/semi


> ## Why???

> Because style.

> On a more serious note, some people (including me) feel more comfortable and productive when writing JavaScript without semicolons. (If you disagree, [read this](#but-semicolons-are-required)) However, this is often not viable in a team environment, or when working on a project with established code style requirements.

**Comment by phanan** [comment]
What @fnlctrl said, also this type of question doesn't belong here. Please read the contributing guide.

**Comment by wuxiaolan91** [comment]
有道理~
