### ISSUE TITLE
Can I pass data of a component to its slot (so users can get data from slot)?

### ISSUE THREAD

**Issue by hectorguo** [vuejs/vue#2836]
I have viewed this [example](http://jsfiddle.net/yyx990803/hdpgrxp4/9/) created by Evan, it looks great to custom and repeat <td> elements.

```html
<!-- Component -->
<script>
Vue.component('test_slot', {
    template: '<table><thead><th v-for="item in items">{{item}}</th></thead><tbody><tr v-for="item in items"><td><slot name="test"></slot><td></tr></tbody></table>',
    props: ["items"]
});
<script>

<!-- APP -->
<test_slot :items="items">
    <span slot="test">foo</span>
</test_slot>

<script>
new Vue({
    el: 'body',
    data: {
        items: ['A', 'B', 'C']
    }
})
</script>
```

but I wonder if I could pass some dynamic data to the slot.

Something like this:
```html
<test_slot :items="items">
    <span slot="test">{{item}}</span>
</test_slot>
```

Note that, `{{item}}` is from `v-for="item in items" `. 
and it will render like this:
```html
<td>A</td>
<td>B</td>
<td>C</td>
```
rather than the fixed value: 

```html
<td>foo</td>
<td>foo</td>
<td>foo</td>
```

 I am not sure if there are some solutions to support this feature.

Ask for help !!!

**Comment by fnlctrl** [comment]
I think it's not possible because `v-for` is compiled inside `test_slot`'s scope, and `<span slot="test">{{item}}</span>` is compiled inside `body`'s scope.

**Comment by phanan** [comment]
Please adhere to the [contributing guide](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) and direct this question to [Gitter](https://gitter.im/vuejs/vue) or the [forum](http://forum.vuejs.org/). I'm sure you'll get lots of help there. If you believe this is a missing feature and want to request for it instead, feel free to modify/reword this issue as such, or open a new one. Thanks.

**Comment by simplesmiler** [comment]
@fnlctrl https://github.com/vuejs/vue/issues/2509#issuecomment-216509500

**Comment by fnlctrl** [comment]
@simplesmiler Thanks!
