### ISSUE TITLE
template slot content disappears on subsequent visit

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#2837]
### Vue.js version
1.0.22 (works fine in 1.0.21)

### Reproduction Link

http://www.webpackbin.com/EyyK3F9b-

### Steps to reproduce
click button 'view2' then click button 'view1'

### What is Expected?
both 'template slot content' and 'nontemplate slot content' should show.

### What is actually happening?
'template slot content' disappeared

**Comment by pespantelis** [comment]
Avoid to use the `template` tag as a wrapper. You could use a `div` instead.

```html
<!-- avoid this -->
<template slot="fillme">
  template slot content
</template>

<!-- use this -->
<div slot="fillme">
  template slot content
</div>
```

https://github.com/vuejs/vue/issues/681#issuecomment-75392474
