### ISSUE TITLE
Slot tag in parent instead of directive/attribute?

### ISSUE THREAD

**Issue by devboxr** [vuejs/vue#2839]
NOT a bug report, but would be intended use from my perspective.

### Vue.js version
1.0.21

### Reproduction Link
http://jsbin.com/cixorubeju/edit?html,js,output

### What is Expected?
I would expect to be able to use `<slot>` inside the parent declaration as well.

### What is actually happening?
It does not work as an independent tag, but instead only as directive/attribute.

Is this intentional? If so, any way around it? It would really be useful not to push markup around. In my use-case for instance, I have a `<ul>` that always comes with a set of classes, and I want only the `<li>`'s to be in the <slot> component on a parent.

**Comment by yyx990803** [comment]
Because it's not designed to work like this? I think the doc explains it pretty well. `<slot>` stands for "replace this with parent content", you are basically using it in reverse.

I still have no idea what you are trying to achieve after reading your explanation, but if you just want to insert plain text, use `<template slot="xxx"></template>`.

**Comment by simplesmiler** [comment]
@devboxr you can not use `<slot name="one">` in place of `<... slot="one">`, because former defines a "box" while later defines content to be placed into a "box".

**Comment by devboxr** [comment]
Hi Evan,

I understand what the docs say, you did a great job writing these. What I am saying is that the use case for me will not allow this to work.

What I am trying to achieve is simple:
I do have a component that is contains a `<ul class="specific classes here">`. When using the component, I do not want to repeat the markup for the unordered list, but instead only use a slot that contains list items, that are then placed in the appropriate slot inside the component (= inside the unordered list).

I cannot wrap the `<li>something</li>` with anything else. First of all would this be unnecessary markup, and secondly does the `<ul>` break when doing this.

I see that there was a mistake in the jsbin, I updated the example:
http://jsbin.com/suhohuceqo/edit?html,js,output

How would you guys approach this?

**Comment by yyx990803** [comment]
In that case, this is a question and should not be opened as an issue. Please adhere to the issue reporting guidelines.
