### ISSUE TITLE
Feature request: `<div v-bind:content>` as a shorthand for `<div v-bind:content="content">`

### ISSUE THREAD

**Issue by bopjesvla** [vuejs/vue#2843]
This pattern is quite common. The intent of the shorthand seems clear to me, and it currently has no effect I'm aware of.

**Comment by posva** [comment]
Just as a side note you can actually achieve this already by using a mixin: https://jsfiddle.net/posva/t728xa3o/1/
**I don't recommend you using it though** as this will add a loop on all props everywhere

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/pull/2877#issuecomment-226618510
