### ISSUE TITLE
watcher inside component not triggered in 1.0.22

### ISSUE THREAD

**Issue by ppq1991** [vuejs/vue#2847]
### Vue.js version
1.0.22

### Reproduction Link
later provided

### Steps to reproduce
```html
<some-component :param="param"></some-component>
```
when changing param in current component

```javascript
this.param.someAttr = 'chuck norris'
```

the watcher side <some-componenet> would not be triggered
```javascript
// in some-component
{
  watch: {
    param () {
      alert('param changes!')
      // nothing happend
    }
  }
}
```

### What is Expected?
this works fine in 1.0.21, but all our projects failed after updated to 1.0.22.

### What is actually happening?
i'm working on it

**Comment by sqal** [comment]
Propably same issue i have reported recently - https://github.com/vuejs/vue/issues/2821

**Comment by ppq1991** [comment]
@sqal same issue, thanks!

**Comment by simplesmiler** [comment]
This does not appear to be the same issue, but it works as intended. If you need to detect changes to object keys, you should use `deep: true` watcher.

**Comment by sqal** [comment]
@simplesmiler @ppq1991 yeah actually I checked this now with vue@1.0.22 and this not related to issue #2821 and everyting seems working fine, you just need to use deep watcher:

```
  props: ['param'],
  watch: {
    param: {
      handler: function() {
        console.log('param updated');
      },
      deep: true
    }
  }
```
