### ISSUE TITLE
"Uncaught SecurityError" with embedded SoundCloud player

### ISSUE THREAD

**Issue by samu** [vuejs/vue#2853]
I'm getting the following error:

`Uncaught SecurityError: Blocked a frame with origin "http://localhost:8080" from accessing a frame with origin "https://w.soundcloud.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.`

I have a simple app that can display a list of sound cloud players.

Steps to reproduce:

Clone my repo `https://github.com/samu/vue-playground`, then `npm install && npm run dev`

In the browser you'll see a bunch of buttons labeled with `x`: Click the very last one and the exception will be thrown.

**Comment by txchen** [comment]
Related to #2852

**Comment by yyx990803** [comment]
Duplicate of #2852
