### ISSUE TITLE
Separate the observer to a module?

### ISSUE THREAD

**Issue by jamen** [vuejs/vue#2859]
Vue.js's [`observer`](https://github.com/vuejs/vue/tree/dev/src/observer) looks quite handy, and I actually want to use it in a project of mine to "deep listen" on an object much like how `data` works on Vue.  

But, I don't know Vue's codebase, so I'm not sure how it is tied to Vue...  This idea might not be feasible if it is closely attached.

**Comment by Jinjiang** [comment]
The `observer/*` works well with `watcher.js` and `instance/internal/state.js` together I think. And the last part could be customized by yourself easily.

**Comment by yyx990803** [comment]
I didn't do it, and probably will never do it because doing this complicates the project with no obvious gain for the project itself. If you are looking for a standalone reactive implementation, check out https://github.com/mobxjs/mobx

**Comment by jamen** [comment]
Fair enough.  Thanks, I'll check that out.
