### ISSUE TITLE
[$add vs $set] Update only a line in list

### ISSUE THREAD

**Issue by grelu** [vuejs/vue#2862]
Hi,

How can I update a line in a list ? I tryed $set and it's ok to set a new array but when there is just one line is changed, I don't understand... I tryed $add but it doesn't work. And I have an issue with $index. Because my list is filtered (filterBy) and I have need my id (I have this) and not $index.

Thanks for help

**Comment by grelu** [comment]
It's ok with this 

`this.personnes.$set(0, {Nom:nom,Prenom:prenom});`

But I have always the issue with $index, can I replace $index by my id in v-for ?

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, chances are you are trying to do this in a method. If so, then just pass the item to the method:
``` html
<ul>
  <li v-for="items in item | ..." @click="handleClick(item)">{{ item.title }} [{{ item.clicked }}]</li>
</ul>
```
``` js
handleClick: function(item) {
  item.clicked += 1;
},
```
If that does not help you, try using vanilla methods [`<Array>.findIndex`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) and [`<Array>.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

**Comment by grelu** [comment]
Oh I am sorry...

Ok, thank you for help !
