### ISSUE TITLE
url change, but component not update.

### ISSUE THREAD

**Issue by liming881227** [vuejs/vue#2864]
url change, but component not update.

use this.$router.router.go 

change to this.$router.go
 
this issue exist too.

**Comment by simplesmiler** [comment]
Please file router issues to [`vue-router` issue tracker](https://github.com/vuejs/vue-router/issues).
Also please provide a live reproduction so that it's possible to debug the issue.

**Comment by liming881227** [comment]
got the answer, write the deactive fun, but do nothing.
after remove the deactive, everything is ok!
