### ISSUE TITLE
no way to pass parameter into promise before async component resolve?

### ISSUE THREAD

**Issue by kidsit** [vuejs/vue#2865]
Hi,
I can not receive email verification from forum.vuejs.org, so i have to post a thread here.
I know we can use async component declaration within the resolve function. 
But how can i  pass a url parameter(used to retrieve data before component compiled into live) to async component? Say: 
```
Vue.component('async-example', function (resolve, reject) {
this.$http.get('/admin/permissions/data').then(
function(resp) {
resolve({
 // vue component declaration object.
})
```
above example, i hope the $http.get parameter can be passed in like something like this:
```
<async-example url="some/other/entrypoint"></async-example>
```
What is the best way to achieve that ?
Thanks!

**Comment by simplesmiler** [comment]
Hello!

Re: confirmation email. If you signed in with GitHub, make sure your email is set as public in your GitHub profile. You can also try to change the email in your forum profile.

Re: question.You are confusing component resolution and component instantiation. To instantiate a component from the markup it should already be resolved, thus url should be known beforehand.

What you can do though is to make a higher order component, and define url when declaring the component.
``` js
var AsyncExample = function(url) {
  return function(resolve) {
    return Vue.$http.get(url).then(function(resp) {
      // ...
    });
  };
};

Vue.component('async-example-data', AsyncExample('/admin/permissions/data'));
Vue.component('async-example-rules', AsyncExample('/admin/permissions/rules'));
```

I will go ahead and close this, because this is a usage question. Feel free to post link to this in the forum when you get access.

**Comment by kidsit** [comment]
thanks for your quick response, that is what i want.

**Comment by cnweibo** [comment]
@simplesmiler , I have written following code to test according to your proposal, but it always pop up following error:
```
Uncaught (in promise) ReferenceError: resp is not defined
```
can you help me out? It should be javascript scope issue, but i am not sure, thanks a lot!
1. declare a wrapper function with url and componentOptions object as paramter. In this function we fetch the data from the url, and within promise we call the resolve function;
```
var AsyncComponentWithPromise = function(url,compOptions) {
	return function(resolve) {
	    return this.$http.get(url).then(function(resp) {
	        // we will use as input data for the resp in the resolve function compOptions 
                // here we always not work
	        resolve(compOptions);
	    });
};
```
2.called as following to declare a component
```
Vue.component('ajax-user-add',AsyncComponentWithPromise('/admin/users/data',{
    template: document.getElementById('ajax-user-addTemplate').innerText,
    props: ['roleid','shouldopenme'],
    data: function(){
        return {
            data: resp.data,  // here we always have an undefined refer to resp
        };
    },));
```
3. control the ajax-user-add to display/hide with v-if
```
<ajax-user-add v-if="shouldopenme" :shouldopenme.sync="shouldopen" ></ajax-user-add>

```
4. have other mechanism to trigger shouldopenme to true.

thanks~!

**Comment by cnweibo** [comment]
By the way, I still can not get received the verification email after login with github account(with email public available), I think it is possibly because I signed up into forum.vuejs.org 20 days ago, and at that time my github account is not expose my email address?

**Comment by cnweibo** [comment]
Hi, the issue i can not post thread in forum.vuejs.org solved by manually update my email.
But the forum.vuejs.org still has the bug of such scenario:
when first logged into the system with github(email not set as public), the forum will never update again even after I set github email as public.
Please know about that
thanks!

**Comment by kidsit** [comment]
I solved myself with javascript closure feature.
