### ISSUE TITLE
动态组件里同时执行同一个快捷键监听

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#2866]
没错，就是我，总舵主您好，这是我们对您的尊称！

我不确定我遇到的这个问题是不是一个bug，还是说，只是我的逻辑错误，我有两个动态组件，我分别在这两个组件的ready方法里写了同一个快捷键的监听事件，然后当我按下Ctrl+Z这个快捷键组合时，就会同时触发两件组件里的方法，而我实际只想触发当前组件里的方法，that's all, 不用问我为什么不把快捷键设定到根组件，相信我，我有不得已的原因！

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](forum.vuejs.org) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:
