### ISSUE TITLE
Lodash Throttle/Debounce Cancel Method Compatibility

### ISSUE THREAD

**Issue by roblav96** [vuejs/vue#2870]
I'd like to be able to throttle a method in a component and be able to call its cancel() method but can not do so.

### jsfiddle
https://jsfiddle.net/roblav96/zbb8keps/

### _.throttle() Docs
https://lodash.com/docs#throttle

Is there any way we can make this work?

**Comment by sirlancelot** [comment]
Make the function in `methods` the bare, un-throttled function. And then make a computed property which returns a wrapped version.

```javascript
var $vm = new Vue({
    methods: {
        socket: function() {
            console.log("this.socket()")
        }
    },
    computed: {
        throttledSocket: function() {
            return _.throttle(this.socket)
        }
    }
})

$vm.throttledSocket()
$vm.throttledSocket()
$vm.throttledSocket()

$vm.throttledSocket.cancel()
```

**Comment by roblav96** [comment]
@sirlancelot Thank you very much sir!!! :D

**Comment by cklmercer** [comment]
Any examples of using this in combination with a watcher?

**Comment by FINDarkside** [comment]
Why do you need the computed method? I seems to work the way OP posted, except that the debounced method lacks cancel method.

**Comment by cklmercer** [comment]
Im not sure if I figured it out or just moved on, but I know it's no longer an issue.

**Comment by FINDarkside** [comment]
Makes sense, thanks!

**Comment by Eunknight** [comment]
> Make the function in `methods` the bare, un-throttled function. And then make a computed property which returns a wrapped version.
> 
> ```js
> var $vm = new Vue({
>     methods: {
>         socket: function() {
>             console.log("this.socket()")
>         }
>     },
>     computed: {
>         throttledSocket: function() {
>             return _.throttle(this.socket, 1000)
>         }
>     }
> })
> 
> $vm.throttledSocket()
> $vm.throttledSocket()
> $vm.throttledSocket()
> 
> $vm.throttledSocket.cancel()
> ```
also
```
data(){
  return {
    throttleUpdates:_.throttle(this.updateFilters, this.throttle)
   }
}
```
keyword: vue lodash debounce cancel
