### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#2874]
We are using [Flow](http://flowtype.org/) to type-check Vue 2.0's codebase. This provides the benefits of static type checking with gradual opt-in and without deviating too far from standard ECMAScript and the associated build tools (Babel, ESLint, etc).

To run the flow check, just run `npm run flow`. Note this doesn't work on Windows at the moment.

You can also install flow globally with `npm install -g flow-bin`, so that you can use `flow` in server mode which gives much faster re-checks.

**Note:** globally available type declarations are in the [flow directory](https://github.com/vuejs/vue/blob/next/flow/)

It is also recommended to install appropriate editor plugins during development:

- SublimeText: [SublimeLinter](http://www.sublimelinter.com/en/latest/) + [SublimeLinter-flow](https://github.com/SublimeLinter/SublimeLinter-flow)
- Atom: [Linter](https://atom.io/packages/linter) + [flow-ide](https://atom.io/packages/flow-ide), or [Nuclide](http://nuclide.io/)

### Progress Tracking

- [x] compiler
  - [x] directives
  - [x] parser
  - [x] codegen
  - [x] events
  - [x] helpers
  - [x] index
  - [x] optimizer
- [x] core
  - [x] global-api
  - [x] instance
  - [x] observer
  - [x] util
  - [x] vdom
  - [x] config
  - [x] index
- [x] entries
- [x] platforms
  - [x] web
    - [x] compiler
    - [x] runtime
    - [x] server
    - [x] util
- [x] server
- [x] shared

**Comment by blocka** [comment]
It's great the vue 2.0 uses flow. What if we want to use flow in "userland"?

**Comment by posva** [comment]
@blocka Setup flow as usual in your workflow.
Please, don't hijack issues for questions 😉

**Comment by blocka** [comment]
@posva tried that. I get about 130 issue from vue, because there are no type definitions. Don't worry. I've already asked this question on gitter, then forum and the flow IRC channel. From the vue sources, I have not received a response. Nor can I really find any examples of people uses flow with vue. From the IRC channel it basically seems that you need publish flow definitions for other people to use.

**Comment by LinusBorg** [comment]
I already replied to your post on the forum. It seems you load Vue from /src ?

**Comment by blocka** [comment]
@LinusBorg I will check the forum... I didn't get any notifications, so I didn't realize somebody answered, and will continue the discussion there.

**Comment by andreiglingeanu** [comment]
Is there any plan to bring a more tightly integration with flow in the user-land?

Particularly, I'm interested if there's a plan to bring static type checking for components (especially for props and computed) the way flow [integrates well](https://flowtype.org/docs/react.html#_) with React out of the box.
