### ISSUE TITLE
I want use third-party libs（like ueditor） in vue.js + webpack project

### ISSUE THREAD

**Issue by chunhei2008** [vuejs/vue#2875]
I want use third-party libs（like ueditor） in vue.js(v1.0) + webpack project, but ueditor is not support in npm , how to pack the third-party as a component for vue.js , thks.

**Comment by phanan** [comment]
Please ask on [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue), thanks.
