### ISSUE TITLE
Add jsnext:main to package.json

### ISSUE THREAD

**Issue by NicolasParada** [vuejs/vue#2880]
I noticed that in vue-router, you added [jsnext:main](https://github.com/vuejs/vue-router/commit/89a1542116c710ecf59ff94cb675d2dbfe477f94) pointing to the `src` folder.
Why you didn't do the same in all vuejs projects?

**Comment by yyx990803** [comment]
It is a non-standard property only used by some tools. As Node is starting to discuss official support for ES6 modules, we'll just wait for something more standarized.

**Comment by NicolasParada** [comment]
Ok ;)

**Comment by rpjohnst** [comment]
This is fixed in 2.2, using the new `pkg.module` instead of `jsnext:main`.

**Comment by ryanve** [comment]
@rpjohnst are there docs for `pkg.module` on the web? Is this an official npm field or a convention?

**Comment by rpjohnst** [comment]
@ryanve The place I ran into it was [here](https://github.com/rollup/rollup/wiki/pkg.module). Seems to be a convention shared among several bundlers.

**Comment by ryanve** [comment]
@rpjohnst Cool thanks!
