### ISSUE TITLE
Can we use vue2.0 for a formal project right now?

### ISSUE THREAD

**Issue by liuyajuntm** [vuejs/vue#2881]
The vue2.0 is a wonderful framework.
Is it possible to use it for a formal project right now?
When the stable version and full toolchain will release?

**Comment by blake-newman** [comment]
At the moment we are in alpha. API may and could be likely to change, official support is not available. Some plugins are currently subject to change and have to be ported to work with 2.0. 

You can use at your own risk, however I would certainly recommend waiting for a RC version. We are aiming to bring Beta soon once tests and some plugin updates are complete.

**Comment by posva** [comment]
I recommend you using latest Vue 1 version and carefully read about Vue 2 features to make migration as easy as possible
