### ISSUE TITLE
can't get `this` in watch event if using es6 arrow function

### ISSUE THREAD

**Issue by mrzzcn** [vuejs/vue#2883]
<p data-height="265" data-theme-id="dark" data-slug-hash="PNvqyX" data-default-tab="js,result" data-user="zhangzhen" data-embed-version="2" class="codepen">See the Pen <a href="http://codepen.io/zhangzhen/pen/PNvqyX/">PNvqyX</a> by zhen zhang (<a href="http://codepen.io/zhangzhen">@zhangzhen</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

Open the demo up
press Change 1 and Change 2 button
see the chrome console
you'll see the problem

**Comment by simplesmiler** [comment]
This is how arrows work by design. It's incorrect to use them when defining methods. Use enhanced object literals instead: http://codepen.io/anon/pen/LNopYd

**Comment by mrzzcn** [comment]
thanks
