### ISSUE TITLE
1.0 vue components named 'Col' cann't be recognized correctly

### ISSUE THREAD

**Issue by frontoldman** [vuejs/vue#2893]
### 1.0 vue components named 'Col' cann't be recognized correctly

like this:

`<Row>
  <Col></Col>
</Row>`

**Comment by yyx990803** [comment]
<col> is a native element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

**Comment by sirlancelot** [comment]
Try a different name: the `<col>` tag is already taken: [`<col>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col)

**Comment by frontoldman** [comment]
why Button is ok ?
