### ISSUE TITLE
Please more info about error

### ISSUE THREAD

**Issue by zyf0330** [vuejs/vue#2895]
### Vue.js version
1.0.13

### Steps to reproduce
remove `unsafe-eval` in CSP
### What is Expected?
`new Function` throws exception, developer can see error message about it.
### What is actually happening?
there is not  error detail only 
>[Vue warn]: Invalid expression. Generated function body: scope.current_href

I think more detail info about error should be shown in debug mode.

**Comment by posva** [comment]
Hello!

Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described. Also, try to use the latest stable version, please

**Comment by yyx990803** [comment]
You need to use the [csp build]() in CSP without `unsafe-eval`: http://vuejs.org/guide/installation.html#CSP-compliant-build

**Comment by zyf0330** [comment]
@yyx990803 THanks for your guide.
But what I want to say firstly is asking for more detailed info of error itself shown to developer.

**Comment by yyx990803** [comment]
@zyf0330 the information has always been on the installation page. Vue cannot detect whether function generation failed because of invalid expression or CSP policy.

**Comment by zyf0330** [comment]
I see the code and find the error is caught, but handler doesn't get its
message and just warn a message about wrong new Function execution.

On Thu, May 19, 2016, 00:09 Evan You <notifications@github.com> wrote:

> @zyf0330 <https://github.com/zyf0330> the information has always been on
> the installation page. Vue cannot detect whether function generation failed
> because of invalid expression or CSP policy.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/vuejs/vue/issues/2895#issuecomment-220076465>
>
-- 

追随

**Comment by yyx990803** [comment]
You're right, added: https://github.com/vuejs/vue/commit/df9663b3076f17ca1d11c31cd957d5378202e260

**Comment by zyf0330** [comment]
Thanks. I have thought you would just put error caught into warn called. And I think it is more stretchable, is it?
