### ISSUE TITLE
Please create source map for vue.min.js

### ISSUE THREAD

**Issue by benrondeau** [vuejs/vue#2900]
Can a source map please be generated when releasing versions of `vue.min.js`? I am using it in production and when I get an error, I get a reference that is very difficult to debug (referencing a method on `line 6` which has thousands of characters on it).

Maybe this has already been asked or I am just missing finding the file?

Thanks

**Comment by sirlancelot** [comment]
I imagine this is not possible until Rollup.js supports sourcemaps.

**Comment by sirlancelot** [comment]
Relevant Rollup.js Documentation: [Sourcemaps](https://github.com/rollup/rollup/wiki/JavaScript-API#sourcemap)

**Comment by yyx990803** [comment]
Do you have any reason why you have to debug the issue in production? You should be using the non-minified version during development.

**Comment by benrondeau** [comment]
I track bugs that occur in production, which I use the minified version of vue.js. It seems to be almost a universal practice with other libraries and other frameworks, such as jQuery and Angular, to include a source map with the minified production version of the file . It is also so trivial to accomplish in the build stage. Thanks

**Comment by yyx990803** [comment]
Will be included for future releases.

**Comment by WadeShuler** [comment]
It is over 3 years later.. I still don't see a map file?

It is handy for Rollbar and other error monitoring services. The minified JS file should use the sourceMappingURL comment tag at the end:

Example from bootstrap.min.js:

    //# sourceMappingURL=bootstrap.min.js.map

**Comment by whippet71** [comment]
Agreed, why is this not included? It would be _really_ useful for debugging errors in production...
