### ISSUE TITLE
Any way to tell when a component is done rendering?

### ISSUE THREAD

**Issue by coolcorey** [vuejs/vue#2918]
I am attempting to use bootstrap-table. I can post more details, but the only way I can get it to work is to delay bootstrap-table from attaching/seeking the table until rendering by VueJS is complete. Is there any way to tell when the table component has finished it's first render?

At the moment, bootstrap-table works when I do a setTimeout for x (in this case 2000) milliseconds before returning the data.

**Comment by phanan** [comment]
Please ask these questions on the [forum](http://forum.vuejs.org/) or [Gitter](https://gitter.im/vuejs/vue).

**Comment by FadyMak** [comment]
Hi there! This question is best suited for the Forum or Gitter. To quickly answer your question, you can use the Lifecycle Hooks that Vue provides: http://vuejs.org/api/#Options-Lifecycle-Hooks

For your case, you can try using the `ready` hook depending on the specifics of bootstrap-table.

**Comment by drasnop** [comment]
In Vue 2.0, `ready` has been replaced by `mounted`. If you want to make sure that all child components have also been mounted, use `vm.$nextTick`:
```
mounted: function () {
  this.$nextTick(function () {
    // Code that will run only after the
    // entire view has been rendered
  })
}
```
Source: https://vuejs.org/v2/api/#Options-Lifecycle-Hooks

**Comment by Uthpala** [comment]
-@drasnop Wrong it does not guarantee that -> https://github.com/vuejs/vue-router/issues/289

**Comment by weituotian** [comment]
does `nextTick` for all components updated?

**Comment by blysq65** [comment]
@matthewmorgan I have the same problem, I am using v-for in my template. Can I solve this in any way?

**Comment by eddivalen** [comment]
This is how I do it and it works for me:
Before execute my action, I ask first if my component exists, until my target component is finally loaded.
```
 updated: function(){
    var ref = this
    this.$nextTick(function () {
      if(typeof ref.$refs.table != 'undefined'){
          ref.$refs.table.setPage(this.pageNum)
        }
      })
  }
```

**Comment by orrd** [comment]
Here is a solution from the comments of similar issue #9200:

https://www.npmjs.com/package/vue-force-next-tick

Apparently in some situations the "double requestAnimationFrame method" is needed.

**Comment by manuelgeek** [comment]
> This is how I do it and it works for me:
> Before execute my action, I ask first if my component exists, until my target component is finally loaded.
> 
> ```
>  updated: function(){
>     var ref = this
>     this.$nextTick(function () {
>       if(typeof ref.$refs.table != 'undefined'){
>           ref.$refs.table.setPage(this.pageNum)
>         }
>       })
>   }
> ```
> 
> My target component has a 'ref' prop, that one I used for the condition
> 
> ```
> <v-client-table ref="table">
> ```

works great

**Comment by matthewmorgan** [comment]
@manuelgeek Thanks for the tip.  I am very sad that something like the above is needed..seems like hacking around something that ought to be baked in.

**Comment by buildingcardinal** [comment]
The answer came through



https://javascripter.space/questions/what-is-the-process-of-invoking-a-function-from-a-different-component-in-vue-3

**Comment by weituotian** [comment]
好~(￣▽￣)~*
