### ISSUE TITLE
Hi, You! I want use   >  v-bind:class=''{'classA': isA}'' <  syntax , but i get error with following:

### ISSUE THREAD

**Issue by wangqianjun** [vuejs/vue#2921]
tab.html:453 Uncaught SyntaxError: Unexpected identifier

 var MyComponent = Vue.extend({
        template: '<div v-bind:class="{'classA': isA}">A custom component!</div>'
    });

### Vue.js version
1.0.23

**Comment by wangqianjun** [comment]
由，why close this issue?

**Comment by azamat-sharapov** [comment]
Because it does not follow rules: https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by azamat-sharapov** [comment]
You messed quotes in your code. You need to escape them. That is not Vue related, it is simple JavaScript.

**Comment by wangqianjun** [comment]
Ok, I will pay attention next time, and check my code again~ Thank u!

**Comment by simplesmiler** [comment]
@wangqianjun
``` js
var MyComponent = Vue.extend({
  template: '<div v-bind:class="{ \'classA\': isA }">A custom component!</div>'
});
```
