### ISSUE TITLE
2.0 component keepAlive option removal

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#2922]
Hi:
Appears 2.0 will not have "keep-alive" option for dynamic component usage
but will be part of router function.
What if I do not use router but need this function, which is useful for carouseling
different widgets.

Thanks.

**Comment by roblav96** [comment]
This should certainly be implemented. All my projects rely on keep-alive 👻

**Comment by banricho** [comment]
+1
`keep-alive` is really useful, I hope it will support the same component constructor.
Thanks!

**Comment by fnlctrl** [comment]
I wrote a ListView component that removes invisible items in a list when scrollling, and I depends on keep-alive to avoid re-initializing the items' components when they come into view. So I hope we can keep `keep-alive` in 2.0.
demo: http://catchlabs.github.io/vue-list-view/

**Comment by yyx990803** [comment]
`keep-alive` is now implemented for 2.0 ;)

**Comment by banricho** [comment]
Thanks!

I have tried it. So it's same as Vue 1.x, only supports different `Vue.extend()` component constructor.

T_T
