### ISSUE TITLE
why vue2.0 component props can not pass a plain string

### ISSUE THREAD

**Issue by yczz** [vuejs/vue#2923]
vue2.0 component props can not pass a plain string

     `<script type="text/x-template" id="demo-template">
			<ubutton label="sdfd"></ubutton>
	    </script>
	    
	    <script type="text/x-template" id="select2-template">
	      	<button class="btn">
				{{label}}
			</button>
	    </script>
	    
	    <script src="vue.js" type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript">
			Vue.component('ubutton', {
      			template: '#select2-template',
			    props:["label"]
			})

		    var vm = new Vue({
		      el: '#el',
		      template: '#demo-template',
		      data: {
		      }
		    })
		</script>

**Comment by LinusBorg** [comment]
Hi yczz, 

It seems the code your povided is missing the actual `demo-template`.

Please provide a complete example to reproduce the behaviour you see as a bug.

**Comment by yczz** [comment]
The following code is able to run normally
<script type="text/x-template" id="demo-template">
        <ubutton :label="'sdfd'"></ubutton>
    </script>

**Comment by yyx990803** [comment]
At this stage we are not accepting Vue 2.0 bug reports, since there is no official release yet and tests are not complete.
