### ISSUE TITLE
2.0 watch bug

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#2924]
sorry, I'm not sure this is a bug, maybe you can confirm.

when I use watch in a component, eg: watch a array variable， if I change the array's property value, then it can't trigger watch, only when I change array itself can trigger 

Forgive my poor English

simple is like this:

change : tags.name = 'abc' ,  Trigger  X
change: tags = {name:'abc'},  Trigger  √

Thanks!

**Comment by phanan** [comment]
You need deep watching. Please read the doc: https://vuejs.org/api/#watch. It's 1.x, but applicable for 2.x.
