### ISSUE TITLE
domready for vue?

### ISSUE THREAD

**Issue by wwanghee** [vuejs/vue#2925]
when I use jQuery or Zepto, I use `$(function(){//domready})` to start my coding. I use vue instead of Jquery or Zepto, How can I write my code with `domready` event, or just put my code at the end of the `</body>` ?

**Comment by phanan** [comment]
You normally don't need such an event, as Vue will manage DOM for you. Anyway, as the repo issue list is strictly for bugs or feature requests, this type of questions better fits our [forum](http://forum.vuejs.org/) or [Gitter](https://gitter.im/vuejs/vue). Please direct them there ;)
