### ISSUE TITLE
how can vue ingore the letter of pinyin when i inputing some chinese worlds?(vue是如何能够忽略掉输入中文时候输入框中出现的拼音字母)

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#2927]
it's so magic in this example:http://cn.vuejs.org/guide/forms.html#Text
when i input some chinese world by pinyin,you know,the input box will first show the letter of pinyin,but vue kown it is not userful value and ignore it until the chines worlds be completed!
so,why?why vue can do it?
英文水平有限:
这个例子太神奇了:http://cn.vuejs.org/guide/forms.html#Text
大家都知道，如果你用拼音输入法在输入框中输入文字的时候，输入框中首先会出现拼音字母，直到你选了候选字。但是vue竟然能够知道输入框中出现的拼音字母不是有用的值,直到我真正输入完汉字才会去获取value,是怎么做到的？

**Comment by yyx990803** [comment]
请 google composition events 然后看源码

**Comment by aweiu** [comment]
哈哈 秒回啊，多谢尤大大！然后还有个问题，我现在决定用node的express框架,它也有类似于vue-cli的工具:express-generate，然后也会生成一个模板，但是vue-cli也有webpack模板，这两种不同的目录结构我该怎么让它们优雅的结合起来呢。。
[如图](http://awei.oss-cn-shenzhen.aliyuncs.com/tmp/question.png)

**Comment by aweiu** [comment]
而且express还默认jade模板，感觉有点乱，不知道有没有express+vue的实例

**Comment by yyx990803** [comment]
我回复你的第一个问题是因为觉得你发现了这个细节挺不错的，其他的问题就不要在这里问了。

**Comment by jingsam** [comment]
你用vue写的页面打包后复制到express的public目录就行了
vue是在客户端生成页面，不同于与往由服务端基于模板生成，所以你最好单开一个vue项目，不要集成到express的项目里面

**Comment by aweiu** [comment]
谢谢！现在我就是这么做的。
是直接用html页面作为ejs模板。之所以不直接映射成静态资源，纯静态的缺点就是缓存。我觉得至少得保证页面是无缓存的，用来更新其他缓存过期的静态资源

**Comment by xiaoshan5733** [comment]
@yyx990803 这种做法会导致移动端的bug，当同时存在两个输入框时，在第一个输入框输入中文，先别点完成，此时切换到第一个输入框，就会发现第一个输入输入了值但是vue的绑定并未生效，demo：http://output.jsbin.com/sosakifuna
![image1](https://cloud.githubusercontent.com/assets/854370/15699876/09273b0e-2803-11e6-8c25-2ed1a04ad5b5.PNG)

**Comment by xiaoshan5733** [comment]
@yyx990803 PC端特殊情况下会出现另外一个问题
![uma0zgrlv0](https://cloud.githubusercontent.com/assets/854370/15700034/f0fbac62-2803-11e6-892c-346ee02ec31d.gif)
