### ISSUE TITLE
Select element with v-model and v-on="change:onChange" works differently in FF

### ISSUE THREAD

**Issue by gapipro** [vuejs/vue#293]
Hi,

I noticed that in FF onChange event is triggered before v-model variable is updated.

In all other browsers variable is updated first. 

Here is an example: http://jsfiddle.net/aDhEr/

When you select new value in select element, text below will be updated to selected value. But in FF it is equal to last selected value.

**Comment by flasher007** [comment]
v-on:change="onChange"

**Comment by Li-ReDBox** [comment]
I know this is very old thread but I am not sure if this browser consistence problem has been solved. I am trying to capture the change of a <select>. In Chrome, with key press, the value of model changes but in Firefox, only mouse can make model changes. Nothing comes out of onChange. $watch does not help. Any suggestions?

**Comment by sunmer** [comment]
@Li-ReDBox 
I have it working in both Chrome and Firefox (for Mac).

I did encounter problems when using @change though, so using $watch was the way to go. The way I first tried it was 

`<select v-model="thing"  @change="addThing(thing)"><option v-for="thing in things" v-bind:value="thing" @>{{ thing }}</option></select>`

But that called the addThing method before the thing variable was set. Here's the watch that made it work:

`watch: {
    'thing': function() {
      //put your addThing code here, as you now have the thing variable set.
    }
  },`

**Comment by thuijzer** [comment]
Another hack is to wait for the next tick:

`<input type="checkbox" v-model="myModel" @change="myFunction()">`

`myFunction: function() {`
`var context = this;`
`Vue.nextTick(function () {`
`alert(context.myModel);`
`}`
`}`

**Comment by Oliboy50** [comment]
using a `v-model` as `computed (with setter)` works well too 
(my use case was something like removing an option just after selecting it):

```js
<template>
  <select v-model="selected">
    <option :value="null"></option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
  </select>
</template>

...

    computed: {
      selected: {
        get () {
          return null;
        },
        set (optionValue) {
          this.selected = this.selected.filter(s => s !== optionValue);
        },
      },
    },
```

**Comment by ivanromakh** [comment]
I wanna to ask. v-on:change="function" works only on form elements? I used it on child element and it does`t work. like this
<vvv-component v-model="changing" v-on:change="onChanged()" /> 

but on input it worked
<input v-model="inputText" v-on:change="onChanged()" />

**Comment by Ethan0007** [comment]
I just want to ask on how can I add or upload the same file? because when i used @change event it will not uploaded same file also I tried v-on:change.

Thanks!

**Comment by maoxiaoke** [comment]
I found a way to solve this problem. Maybe you can try: 

```html
<input type="checkbox" v-model="myModel" @change="myFunction()">
```

```javascript
myFunction: function() {
    let context = this
    setTimeout(() => {
      // some code
    }, 0)
}
```

**Comment by Oliboy50** [comment]
@maoxiaoke FYI, [this answer](https://github.com/vuejs/vue/issues/293#issuecomment-265716984) is more "vuejs compliant"

**Comment by frizar** [comment]
@Oliboy50 nextTick is called when the DOM changed, if i am correct. this is ok to use nextTick over setTimeout? or this is ok only for this case?

**Comment by Oliboy50** [comment]
@frizar well, [according to the doc](https://vuejs.org/v2/api/#Vue-nextTick), you're correct

> Defer the callback to be executed after the next DOM update cycle

but I think `setTimeout(() => {}, 0)` seems much more like "I've no idea what I'm doing, but it works 🤷‍♂️" than a `Vue.nextTick()` since it's (at least) documented somewhere 😄 

anyway, during the 6 last months, I didn't had to deal with this kind of hack (except in unit tests, where `Vue.nextTick()` may be useful when dealing with asynchronous stuff), so now I think that if I have to use these hacks again, then I'm doing it wrong

**Comment by bedus-creation** [comment]
did anyone have solved this in 2018 ?

**Comment by armikhalev** [comment]
> did anyone have solved this in 2018 ?

For me lodash `_.debounce` solved this problem, if it helps. 
```javascript
onChange: _.debounce(function(event) {
	// do stuff
}, 1000)
```
and template something like: 
```html
<select v-model="myVal" @change="onChange">
    <option value="my-value">Val</option>
</select>
```
Tested on Chrome and Firefox.
