### ISSUE TITLE
Using with datatables problem!

### ISSUE THREAD

**Issue by NightZpy** [vuejs/vue#2931]
I'm using datatables plugin, i wan't execute a modal from vuestrap components with data vía ajax/json in the table. But vue don't recognize data loaded in datatable, and events how @click doesn't work.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

Also, it would help if you could provide a demo in jsfiddle.
