### ISSUE TITLE
 Feature request: a safe way to pass down a component or a node using props.

### ISSUE THREAD

**Issue by Dafrok** [vuejs/vue#2933]
## Feature

I hope if there is any safe way to pass down a component or a DOM node to child components using props, but render without v-html. Thank you for your work.

#### Parent component

```vue
<template lang='jade'>
foo(:inner=`<bar msg="hello" />`)
</template>
<script>
import Foo form 'foo'
import Bar from 'bar'
export default {
  components: {
    foo: Foo,
    bar: Bar
  }
}
</script>
```

#### Child Component

```vue
<template lang='jade'>
section
  inner
</template>
<script>
import Foo form 'foo'
import Bar from 'bar'
export default {
  props: ['inner']
  components: {
    inner: this.props.inner // or some other ways to pass props to child components
  }
}
</script>
```

**Comment by fnlctrl** [comment]
Read the docs.
http://vuejs.org/guide/components.html#Content-Distribution-with-Slots

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you can use slots for content distribution, and you can pass a component like this: https://jsfiddle.net/simplesmiler/5p420nbe/
