### ISSUE TITLE
use vue-html-loader load img 

### ISSUE THREAD

**Issue by Relsoul** [vuejs/vue#2934]
### Vue.js version
1.0.23

### Question
```
<img src="./img/owl-login.png" alt="img">
```
use webpack  compile

### Error
ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./front-dev/vue/components/rHeader.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./img/owl-login.png in D:\soft\phpstudy\WWW\relsoul\front-dev\vue
\components
 @ ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./front-dev/vue/components/rHeader.vue 1:232-262

I don't want to let webpack or vue-loader to load img or css . 
How to solve?

**Comment by Relsoul** [comment]
the nodejs version: 6.0

**Comment by Relsoul** [comment]
okay 
use html:raw in webpack.config.hs
```
    vue:{
        loaders:{
            js:"babel",
            html: 'raw'
        }
    }
```

**Comment by yyx990803** [comment]
Please read vue-loader docs.
