### ISSUE TITLE
fail to use "v-for" to render a table

### ISSUE THREAD

**Issue by OneNewLife** [vuejs/vue#2938]
``` html
// html
<table id="userArray">
  <tr v-for="item in items">
    {{ item.msg }}
  </tr>
</table>
```
``` javascript
new Vue({
  el: '#userArray',
  data: {
    items: [
      { msg: 'sadasd' },
      { msg: 'asdasd' },
      { msg: 'asdasd' }
    ]
  }
});
```
and there is nothing to show

**Comment by simplesmiler** [comment]
You forgot `<td>`: https://jsfiddle.net/Lrk9sxjf/52/

**Comment by Rastishka** [comment]
You missed <td> tag

**Comment by OneNewLife** [comment]
@simplesmiler excuse me, I get a JSON object now, and how to render that?
``` javascript
email: "xxx@qq.com"
nikeName: "haha"
password: "202CB962AC59075B964B07152D234B70"
permissionSum: null
roles: null
superAdmin: false
userId: 2
```

**Comment by simplesmiler** [comment]
@OneNewLife please ask questions like this on the forum or gitter.
You can use `v-for` on objects too. If you need both key and value, then `v-for="(key, value) in obj"`. But there's no guarantee on the order of keys.
