### ISSUE TITLE
A way to manipulate model from custom directive

### ISSUE THREAD

**Issue by yemi** [vuejs/vue#294]
It would be nice to have a way to directly change the model data passed to a custom directive.

My directive might look like this: `v-my-directive="req.postalcode"` and if i want to change the model when it's updated or on an event ill have to access it like this:

``` javascript
//...
bind : function () {

  // Not very nice :/
  var props = this.key.split('.')
  this.vm[props[0]][props[1]] = 12345
  console.log(this.vm.req.postalcode) // -> 12345

  // Would like something like this
  this.model = 12345
}
// ...
```

In the guide it sais: 

> You should treat all these properties as read-only and refrain from changing them

I think it would be nice to be able to manipulate model data from directives, and as it is now I don't see any other solution than the ugly one I made.

**Comment by metalfox6383** [comment]
But, this doesn't work in v-for.
