### ISSUE TITLE
2.0, delimiters and cached HTML

### ISSUE THREAD

**Issue by bartlomieju** [vuejs/vue#2940]
### Vue.js version
2.0.0-alpha

### Steps to reproduce
```
const vm = new Vue({
  	data: {
  		a: 1
  	},
  	template: '<div>{{ a }}</div>'
}).$mount()
expect(vm.$el.textContent).toEqual('1')

const Test2 = new Vue({
  	delimiters: ['[[', ']]'],
  	template: '<div>{{ a }}</div>',
  	data: {
  		a: 1
  	}
}).$mount()
expect(Test2.$el.textContent).toEqual('{{ a }}')
```
### What is Expected?
`1` and `{{ a }}`

### What is actually happening?
In Test2 `1` is printed. 

So I was trying to write some test for 2.0 and got this strange output. It turns out Vue caches parsed HTML, ignoring different delimiters in `options`. Not sure if it was desired.

**Comment by yyx990803** [comment]
Thanks, fixed. The related test should probably be placed in `test/unit/features/options/delimiters.spec.js`.

**Comment by bartlomieju** [comment]
Will do!
