### ISSUE TITLE
Warn On Unmatched v-else

### ISSUE THREAD

**Issue by atomaka** [vuejs/vue#2946]
Currently, using `v-else` on an element without the presence of `v-if` will always display the element.  This was confusing to me when I misused `v-show` instead of `v-if` and my `v-else` component always displayed.

```
<div>
  <div v-show="true">I always show because true is true!</div>
  <div v-else>I always show because I don't have a matching v-if</div>
</div>
```

I think this should trigger a Vue warning. This would make `v-else` misuse much clearer to beginners such as myself/

**Comment by yyx990803** [comment]
In 1.x `v-else` does work with `v-show`: https://jsfiddle.net/re9Lcf3p/

I think it's probably something else.

**Comment by atomaka** [comment]
I wasn't successful reproducing this in a fiddle, but I've provided an application that was created using `vue init webpack`: https://github.com/atomaka/vue-issue

This maintains an array in a store that is initialized with six empty objects (`{}`).  A component iterates over these lists and decides to display a `MiniCard` component if the array element is populated or a `NullCard` component if the array element is still an empty object.

```
<ul>
  <li v-for="(index, card) in team" @click="startSelectCharacter(index)">
    <mini-card v-show="card.name" :card="card"></mini-card>
    <null-card v-else></null-card>
  </li>
</ul>
```

The initial view is rendered as expected.  However, when performing the action that changes a value in the store array, both `MiniCard` and `NullCard` components are displayed.  Here is an example if this in action:

![example](https://cloud.githubusercontent.com/assets/650603/15514903/62ee57e4-21b9-11e6-9762-fa9238646361.gif)

After clicking a `MiniCard` in the listing that pops up, the expected action is for the `MiniCard` component to show and the `NullCard` component to not show.  However, in the screenshot, we can see that six `NullCard` components show in addition to the `MiniCard`.

Running my master branch that uses `v-if` instead of `v-show` works as expected.  `git diff` between master and the branch with the issue.

```
index 9b1b02b..8b0d6dd 100644
--- a/src/components/TeamList.vue
+++ b/src/components/TeamList.vue
@@ -1,7 +1,7 @@
 <template>
 <ul>
   <li v-for="(index, card) in team" @click="startSelectCharacter(index)">
-    <mini-card v-if="card.name" :card="card"></mini-card>
+    <mini-card v-show="card.name" :card="card"></mini-card>
     <null-card v-else></null-card>
   </li>
 </ul>
```

**Comment by yyx990803** [comment]
Ah ok, this is related to https://github.com/vuejs/vue/issues/2639

Basically when `v-show` is used on a component, `v-else` will not be able to match it. This is a wontfix in 1.x since `v-show` will no longer work with `v-else` in 2.0. Just use the negation condition instead.
