### ISSUE TITLE
Custom directive update function on objects returning two equal values

### ISSUE THREAD

**Issue by jackxli** [vuejs/vue#2949]
### Vue.js version
1.0.24

### Reproduction Link
[JSBin](http://jsbin.com/zupaqodehi/edit?html,js,output)

### Steps to reproduce
Set up a custom directive with an update function and inspect the oldValue and newValue it returns. The update function runs, but the values are the same for JS objects.

### What is Expected?
Directive update function returns different values for oldValue and newValue.

### What is actually happening?
Directive update function is returning the same values for oldValue and newValue.

I see that in the docs, the example for the `deep` option makes use of only the object, and not the oldValue and newValue params, so maybe it's intended behavior?

**Comment by yyx990803** [comment]
This is expected, because you are **mutating** the same Object/Array without replacing it.

**Comment by jackxli** [comment]
Thanks for the quick response, @yyx990803!
