### ISSUE TITLE
[Bug Report] Template conflicted between multi components when dynamically changing template

### ISSUE THREAD

**Issue by hectorguo** [vuejs/vue#2951]
### Vue.js version
1.0.24

### Reproduction Link

here is the code:
http://codepen.io/hectorguo/pen/bebEoV

Short Code:
```javascript
// When I change template like this, it goes not right when multi `<ad-time>` are used in one page.
Vue.component('ad-time', {
        created: function() {
            this.$options.template = NEW_TEMPLATE;
        }
}

```

### What is Expected?

All three components should show different result depending on the `format` attribute.

### What is actually happening?
Now you can see, all three components show the **same template** (same as the first component) result.

And if you delete the first example, it will show the second example's template.

I'm sure that each component's `$options.template` is right.

So I am not sure if i could **change the template dynamically** like this.

**Comment by simplesmiler** [comment]
No, you can not change the template like this. You should consider anything that is inside `$options` to be read-only and non-reactive.

If you need template to depend on data, then make multiple components with different template and use dynamic `:is="type"` to pick the one you need for particular data.
