### ISSUE TITLE
ES2016 Template string not allowed in CSP build?

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#2955]
### Vue.js version
1.0.24

### Reproduction Link
http://www.webpackbin.com/VkxPaAyQb

i recenly replaced standalone Vue build with CSP build and this update broke some parts of my app, the parts where i use ES2015 template strings. You won't see any errors on webpackbin but on my site, console throws the following error:

`[Vue warn]: Invalid expression. Generated function body:  `${scope.path}/image.png``

`[Vue warn]: Error when evaluating expression "`${path}/image.png`": TypeError: Cannot read property 'call' of undefined (found in component: <test>`

Is this normal behavior and I actually can't use template strings with vue-csp or is it some bug? I would appreciate if someone could explain what should i do in this case.

**Comment by yyx990803** [comment]
This is expected, since in CSP build we are parsing and evaluating the expressions using an ES5 only evaluator.

We may consider switch to something that supports ES6 in the future, but for now stick to ES5 in expressions.

**Comment by fritx** [comment]
I'm not sure if I'm having a similar issue.

I was using template strings inside `:src` like `<img :src="static/img/${scope.item}.jpg`">`.
It works fine in some modern browsers, however, breaks (probably) in the PhantomJS test!

I'm confused why the template strings inside **vue expression** were not converted into ES5 despite of babel-preset-es2015.

```plain
12 07 2016 23:12:37.573:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#QObU3ye6U-e0JXK2AAAA with id 59926515
ERROR LOG: '[Vue warn]: Invalid expression. Generated function body:  `static/img/${scope.item}.jpg`'
ERROR LOG: '[Vue warn]: Invalid expression. Generated function body:  `${scope.item} image`'
```

**Comment by yyx990803** [comment]
`:src` expects a JavaScript expression, you need to do `:src="`...${}...`"

But even that it's probably not supported in CSP because the expression parser doesn't handles ES6 syntax.
