### ISSUE TITLE
Splice a element with $remove doesn't work

### ISSUE THREAD

**Issue by chrobaks** [vuejs/vue#2958]
Hello,
Im using vue 1.0.24 and have following code to refresh a list
with eventdata:
`
deleteEvent: function(index) {
   this.events.$remove(index)
 }
`
but nothing happens, but if i do : 
`
deleteEvent: function(index) {
  this.events.splice(index,1);
 }
`
than it work's.

Demo is here:
[http://www.netcoapp.de/vue/](http://www.netcoapp.de/vue/)

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by chrobaks** [comment]
Sorry, i forgot, here is a example-url:
[http://www.netcoapp.de/vue/](http://www.netcoapp.de/vue/)

**Comment by bartlomieju** [comment]
You are passing `index` to `$remove` while it expects the actual element you want to remove.

**Comment by simplesmiler** [comment]
This is not a bug. `$remove` takes a reference to the item, not an index.

**Comment by chrobaks** [comment]
Thanks for quick response, could it be that the $remove-method has a change form v0.12.12 to ver1.0.24? In the example tutorial from scotch.io i found this example with vue.js v0.12.12:

[https://vue-events.herokuapp.com/](https://vue-events.herokuapp.com/)

I didn't realise that i'm using in my example a newer version (1.0.24). So had two problems:

1. v-repeat dosn't work so i replaced it with v-for
2. the scott.io-example call the delete-method with a integer-parameter:

`deleteEvent: function(index) {

       this.events.$remove(index);   

}`

but this didn't  work with ver1.0.24. i change now to following code:

`deleteEvent: function(index) {

    if(confirm("Die Daten löschen?")) {

           var event = this.events[index];

          if (event) {

               this.events.$remove(event);

          }

     }

 }`


Unfortunately i found only some small documentation for $remove in the Vue-Docu (ver1), there is no notice, that there is a change for the param-type for this method.

Thanks for helping me to step into Vue.js, a realy handsome js-library ,sorry for terrible english...

**Comment by yyx990803** [comment]
Yes, it was a breaking change in 1.0.
