### ISSUE TITLE
请问http://forum.vuejs.org/是什么程序？discourse？

### ISSUE THREAD

**Issue by medmin** [vuejs/vue#2961]
看着挺好的，请指教。
不好意思，在知乎上提了好几次这个问题，没得到您的回复。特来issue提问了。

### Vue.js version
1.0.23

**Comment by yyx990803** [comment]
我在知乎上并没有看到。请不要用 issue 问这类问题。

**Comment by medmin** [comment]
我也知道确实不妥。不好意思。删了吧。
我确实在知乎上，给您写私信，发不出去，在您的回答下评论，也没有回应。不好意思啊

能指点一下吗？这个论坛是用什么搭建的？谢谢

**Comment by yyx990803** [comment]
NodeBB

**Comment by hefengxian** [comment]
@medmin  去Vue论坛看了，有人问这个问题，而且有人回答了是NodeBB，为啥要在issue里面问这个问题呢？问之前应该先去搜索。确定没有答案之后才问更好
