### ISSUE TITLE
Clarify `vm.$mount(el)` in lifecycle diagram

### ISSUE THREAD

**Issue by MarkLodato** [vuejs/vue#2962]
On http://vuejs.org/guide/instance.html#Lifecycle-Diagram, the `Has "el" option? -> no` path says `vm.$mount(el)`.  This makes it sounds like Vue calls that function, which doesn't make any sense.  It took me several minutes of reading other documentation to realize that Vue is *waiting for that to be called*.  Therefore, I recommend changing that line to be `Wait for vm.$mount(el)`.

**Comment by yyx990803** [comment]
that's a good point, however this issue should be opened at the vuejs.org repo instead.

**Comment by MarkLodato** [comment]
Ah, that explains why I couldn't find the source!  Filed https://github.com/vuejs/vuejs.org/issues/310.
