### ISSUE TITLE
Local storage not available in Safari private browsing

### ISSUE THREAD

**Issue by benedu** [vuejs/vue#2969]
### Vue.js version
1.0.23

### Steps to reproduce
Take your Safari Browser and enter the private browsing mode. Or just disable local storage.

### What is Expected?
VueJS should work as expected even if no local storage is available.

### What is actually happening?
On of my clients respond with a message to me, that some functions on their website aren't working properly. I found out that when you browsing in Safari private mode that there is no local storage available. In Firefox and Chrome local storage works fine in private browsing.
For my bugs I just wrapped the necessary local storage accesses in a try catch block. That solved my problem.

Any ideas about if this should be solved?

**Comment by simplesmiler** [comment]
This is unrelated to Vue.js. Vue.js is an interface library, and does not use local storage.
