### ISSUE TITLE
paramWatchers in directive with negative priority is not working

### ISSUE THREAD

**Issue by kpym** [vuejs/vue#2970]
### Vue.js version
1.0.24

### Reproduction Link
https://jsfiddle.net/nsLm8sc5/1/

### Steps to reproduce

Create a custom directive with negative priority, parameters and `paramWatchers`.

### What is Expected?

When the parameter is changing the corresponding `paramWatchers` should fire.

### What is actually happening?

When the parameter is changing the corresponding `paramWatchers` is not firing.

But everithing works ok if the priority is positive.

**Comment by posva** [comment]
Do you need  a negative priority for a particular reason?

**Comment by kpym** [comment]
No. But I have seen negative priority in examples, and I haven't seen a limitation for this in the documentation. If the priority should be positive it must be mentioned in the documentation and all negative priorities should be converted to 0, IMO.
In my case I have copied/pasted one example that I have modified by adding `paramWatchers`, and I have spent some time to discover why it was not working.

**Comment by posva** [comment]
Sorry for the delay, I checked it  and it doesn't work with a priority under 850 because that's the bind priority and since you're using a bind on the `a` param, your directive get applied after that while no the `a` attribute no longer exist.

**Comment by kpym** [comment]
Strange, as you can see in the jsfiddle link in the originals quastion it is working with priority 0 (and not working with priority -1). So the explanation about 850 is not clear to me.

**Comment by posva** [comment]
That's because a priority o f 0 gets converted to the default priority. I think we should avoid priorities < 1. [Here](https://github.com/vuejs/vue/blob/45b49e8143044ad795ea040e9fd59a4762d4ed09/src/compiler/compile.js#L122) is where the default value gets applied
