### ISSUE TITLE
Default v-transition class is not being removed after transition is updated

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#2972]
### Vue.js version
>= 1.0.18 (any version i think)

### Reproduction Link
http://www.webpackbin.com/VyoNXXrXb

### What is Expected?

If dynamically binded transition is updated, and previous transition was vue default, v-transition class should be removed.

### What is actually happening?

Check the example. If we change transition from default, v-transition class is not being removed. But when we have some custom transition on start e.g. slide and we change it to fade then slide-transition class is properly removed.

**Comment by Teddy-Zhu** [comment]
it seems the default value `transition: ''` causes the problem
when i set transition: 'xxxx'(xxxx is anthing) ,the `v-transition` had been removed normally

**Comment by posva** [comment]
Let me take a look 😄
