### ISSUE TITLE
using render in 2.0

### ISSUE THREAD

**Issue by weepy** [vuejs/vue#2973]
Hi - I'm trying tp use a custom render function for Vue 2.0, but can't get it to work.

Right now I'm doing: 

```
 render() {
    const x = document.createElement("div")
    x.innerHTML = "hello"
    return x
  },
```

to no avail.

**Comment by yyx990803** [comment]
The render function should return a **virtual node**, not actual DOM nodes. Please wait for proper docs.

**Comment by weepy** [comment]
Ok I got something working with this.$createElement. I can see it would be
relatively easy to work out a kinda hyperscript like interface. Is that the
idea?

**Comment by yyx990803** [comment]
@weepy yes, it is basically hyperscript with slightly different vnode format. There will also be a JSX babel plugin for it.

**Comment by voronianski** [comment]
@yyx990803 @weepy is it possible to have `onClick` and etc. handlers in Vue's render function?

**Comment by yyx990803** [comment]
@voronianski `this.$createElement('div', { on: { click: () => {} }})`

**Comment by voronianski** [comment]
@yyx990803 thanks, just figured it out with `console.log`ing data when using template prop :)
