### ISSUE TITLE
super() in a method overriden via Vue.extend

### ISSUE THREAD

**Issue by softomatix** [vuejs/vue#2977]
It would be great to have `super()` method available to be able to call parent implementation.

**Comment by yyx990803** [comment]
1. This won't be implemented in Vue.js core because I don't want to endorse deep class inheritance.
2. You can use `this.constructor.super.options.methods.method.call(this)` - this is obviously super verbose, but you can easily write a helper to shorten it to something like `callSuper(this, 'methodName')`.

**Comment by rpkilby** [comment]
Hi @softomatix - I wrote [vue-super](https://github.com/rpkilby/vue-super), which might be helpful.

**Comment by druppy** [comment]
Sorry, to keep answering into a closed thread :-(

I really like to known more about why Vue are not using ES6 classes, besides "I don't want to endorse deep class inheritance".

I agree that "deep inheritance" is not a god thing to encourage, but that is not a really good argument for not using ES6 classes more directly.

Some times ago, You wrote something about static properties that would be a problem in native classes, what else could be a problem, and could there be found a solution ? 

Would it be possible to have a Vue.extend type and ES6 class in parallel, to make a more natural integration to both ES6 and Typescript ? As I wrote before, this is the single most strange thing about Vue, and I really like all the rest a lot !

/BL

**Comment by simplesmiler** [comment]
@druppy [classes are not awesome](https://github.com/joshburgess/not-awesome-es6-classes).
Also, https://github.com/vuejs/vue/issues/2371#issuecomment-186238466 and https://github.com/vuejs/vue/issues/2371#issuecomment-186280912.

**Comment by druppy** [comment]
Ok, that was an interesting read, I understand the reason better now ... So I guess vue-class-component will enable static type checking in ts (I can fake data types in the class declaration), and the rest could be a good idea to reconsider (inheritance in this case).

**Comment by phil294** [comment]
Fyi, The syntax specified by yyx990803 does not seem to be valid anymore.  `this.constructor.super.options` does not contain a `methods` property (using `extends: MyComp` syntax)

**Comment by milworm** [comment]
> 1. This won't be implemented in Vue.js core because I don't want to endorse deep class inheritance.
> 2. You can use `this.constructor.super.options.methods.method.call(this)` - this is obviously super verbose, but you can easily write a helper to shorten it to something like `callSuper(this, 'methodName')`.

It's not about deep class inheritance, it's about using "extends" property according to how it's done everywhere and how it is described in the docs. Are you planning to remove "extends" in future releases of vue?

**Comment by hrobertson** [comment]
Slight modification to @phil294 's `MyComp.methods...`: I found I needed `MyComp.options.methods...`

```vue
export default {
  name: 'MyComponent',
  extends: OtherComponent,
  methods: {
    foo() {
      let value = OtherComponent.options.methods.foo.call(this);
      // do your thing, modify value, etc
      return value;
    },
  },
};
```

**Comment by likemusic** [comment]
[vue-just-super](https://www.npmjs.com/package/vue-just-super) - my implementation for call super() in child inhetited components (both by `extends` and `mixins`).

It allows you to call parent component's method just by `this.$super(arguments)` in child component's method (and also in mixin's methods).

**Comment by xuanWangisAlibaba19960403** [comment]
[vue-super-options](https://github.com/xuanWangisAlibaba19960403/vue-super-options)

**Comment by ghost** [comment]
I provide my solution
```javascript
/**
 * Mix properties into target object.
 */
function extend (to, _from) {
    for (var key in _from) {
      to[key] = _from[key];
    }
    return to
}


function superExtend (to, _from) {
    for (let key in _from) {
      let parentMethod = to[key];


      if(to[key]){
        to[key] = function (...args) {
            let proxyThis = new Proxy(this,{
                get(target,p,receiver){
                    if (p === '_superInherit') {
                        return parentMethod.bind(target);
                    }
                    return Reflect.get(target,p, receiver);
                }
            })
            return _from[key].apply(proxyThis, args);
        };
      }else{
        to[key] = _from[key];
      }
    }
    return to
}


Vue.config.optionMergeStrategies.methods = function (
    parentVal,
    childVal,
    vm,
    key
  ) {
    if (!parentVal) { return childVal }
    var ret = Object.create(null);

    extend(ret, parentVal);

    if (childVal) { superExtend(ret, childVal) }

    return ret
};

```
