### ISSUE TITLE
elementDirective produces "unknown custom element" warning

### ISSUE THREAD

**Issue by thany** [vuejs/vue#2982]
I've created (or attempted to) a custom element directive that is going to show a simple heading text. I think I understand the concept. Simply register one via `Vue.elementDirective` and be done with it, if I understand the guide correctly.

### Vue.js version
1.0.24

### Reproduction Link
https://jsfiddle.net/dnagrcq5/
A simple todo app, with my attempt to create a directive in it

### Steps to reproduce
Just run the demo, I suppose. I used Firefox 46, but I'm not sure if that matters.

### What is Expected?
A working directive. The least thing that should happen, is for Vue to execute the `bind` function of the directive. That's not happening.

### What is actually happening?
It produces this warning:
```
[Vue warn]: Unknown custom element: <heading> - did you register the component correctly? For recursive components, make sure to provide the "name" option.1 vue.js:1018:11
warn() vue.js:1018
checkComponentAttr() vue.js:1588
checkComponent() vue.js:7305
compileElement() vue.js:7100
compileNode() vue.js:7060
compileNodeList() vue.js:7243
compile() vue.js:6846
lifecycleMixin/Vue.prototype._compile() vue.js:8572
lifecycleAPI/Vue.prototype.$mount() vue.js:9407
initMixin/Vue.prototype._init() vue.js:2461
Vue() vue.js:9471
window.onload/<() _display:52
window.onload() _display:49
```
And the directive doesn't output anything, and leaves the `<header>` in the DOM as-is, as if completely untouched by Vue.

**Comment by sirlancelot** [comment]
You need to define the element directive before you use it.

**Comment by thany** [comment]
Thanks. I would have hoped the `new Vue` block would not immediately fire itself up, but only do so when everything has done loading. I'm coming from an Angular background, and that's kind of how it works in Angular. 

So can this be a feature request then? I personally prefer writing directive under my "controllers", because controllers is where I'm at most of the time. Even in jQuery I write plugins underneath my regular code.

Also, in the mean time, it might be a good idea to document this (more explicity, if I overlooked it?) in the guide and/or API.

**Comment by simplesmiler** [comment]
@thany just define things locally instead of globally.

**Comment by thany** [comment]
That could work too. Thanks, I'll go and try that.
