### ISSUE TITLE
[BUG] one time binding doesn't deal with null like value properly

### ISSUE THREAD

**Issue by dsonet** [vuejs/vue#2988]
### Vue.js version
1.0.24

### Reproduction Link
http://jsbin.com/yesozewezu/1/edit?html,js,output

### Steps to reproduce
For one time binding, undefined value would display as "undefined", it's different from two-way binding.
### What is Expected?
Should display as empty.
### What is actually happening?
Display undefined.

**Comment by LinusBorg** [comment]
Hello @dsonet, 
Thank you very much for this report. We will continue this in your pull request #2989

**Comment by dsonet** [comment]
@LinusBorg FYI. Just updated the reproduction case, also new fix.
