### ISSUE TITLE
watcher value update problem v1.0.22+

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue#2992]
### Vue.js version
1.0.22 to 1.0.24

### Reproduction Link
1.0.21: http://jsfiddle.net/5sH6A/421/
1.0.22: http://jsfiddle.net/5sH6A/422/

### Steps to reproduce
1. set a new value for twoWay prop in a watcher function
2. set it back to old value immediately

### What is Expected?
both value in parent component and child component set back to the old value
### What is actually happening?
the prop value in child component remains the "new value"

wrap the "set back to old value" expression in a setTimeout can fix it temporary.

**Comment by LinusBorg** [comment]
Did you provide the correct version of your fiddle? it's missing the exernal vue.js file library and the template for the `test` component (which you nest in itself without a clear reason/relation to the issue) seems unfinished.

I can kind of see what you refer to, but it's not really conclusive.

Anyways, what I  think is happening is that your code kind of gets ahead of itself and runs in a circle:

* you set `parentNumber` to `1`
* This will trigger the two-way sync and propagate the value to the item in the parent.
* But you also set `item.number` to 0 immediatly afterwards - and you do this on the *original object*, not the `parentNumber` prop.

So now we have some kind of a race condition: you change a two-way prop which triggers an event to update the parent element, and at the same time you update said parent element dírectly, which should trigger a downwards update of the prop `parentNumber` ...

The result now depends when which reactive update event fires, beause reactive updates are async:

* first, the direct update of `this.item.number` succeeds. the parent object is now `0`
* only then after the stack is done, the reactive update to the parent form the two-way prop comes along, changing it again to 1
* while the first change to 0 already triggered a change downwards, changing the prop `parentNumber` to 0.

This is a first guess/observation, but the bottom line is, ttwo-way bindings are a bitch to debug, especially when you tinker with both sides of the binding at the same time (if setting to 0 and to 1 is done on `this.parentNumber`, everything behaves normally).

So I don't think it's a bug, but simply a side-effect of an anti-pattern when working with two-way bindings.

**Comment by Astray-git** [comment]
Thanks for your detailed answer.
I put two vue.js scripts in `<head>` (with version 1.0.21 commented). You can switch between the 2 versions to see a different result. I understand it is not a good practice to use twoway props in this way. I Just wonder why this code works well with version 1.0.21

Maybe it's related to the watcher invocation order fix introduced in 1.0.22?

**Comment by LinusBorg** [comment]
presumably, can't tell at first glance.

**Comment by Astray-git** [comment]
The watcher queue are different:
in 1.0.21 the watch expression order is like `parentNumber`, `item.number`, `item.number` ...
while in 1.0.22+, the order is `item.number`, `item.number`, `parentNumber`
`parentNumber` is set to `1` in the last watch run.

**Comment by LinusBorg** [comment]
yeah that seems to be the case. 

Are you ok with me closing this issue, judging it's a edge-case sideffect of reactivity that is not entirely preventable when manipulating two sides of a binding at the same time (which one shouldn't be doing anyways)?

**Comment by LinusBorg** [comment]
I will close this issue. Please comment if you think it should be re-opened and why.
