### ISSUE TITLE
weird behavior for v-transition

### ISSUE THREAD

**Issue by ahmad-ibrahim** [vuejs/vue#301]
I tried to use http://goratchet.com/ with vue.js to create html5 mobile app like the one found in this tutorial http://coenraets.org/blog/2014/03/building-mobile-apps-for-salesforce-com-with-ratchet-2-0/

but I'm facing a weird problem that v-transition didn't do the animation neither destroy the old object component, code can be found here http://jsfiddle.net/mido0o0o/Z99un/6/

probably this isn't a bug and I did a stupid mistake there but I didn't find any other place that I can ask for support, I think vue needs google group or something for this kind of inquires

**Comment by mgutz** [comment]
@Ahmad-Ibrahim How did ratchet + vue work out? I'm deciding between Vue + ratchet or Ionic. I would prefer the vue solution of course.

**Comment by Ahmad-Ibrahim** [comment]
vue is great but ratchet was pain in the ass and I think ratchet is dead now.. I tried ionic but didn't like it so I used vue with bootstrap

**Comment by mgutz** [comment]
I went with ionic. I didn't want to deal with mobile-related browser issues and it's very active. Angular is painful compared to vue, but for my project and deadline angular is the right tool for a hybrid app. It took several hours to understand the SUBTLE differences between provider, service and factory. About the only feature in angular I like over vue is the dependency injection. It makes testing easier. In the end, I appreciate vue even more for its simplicity.
