### ISSUE TITLE
怎样更改数组中某一个对象属性，而不触发其它属性的视图更新

### ISSUE THREAD

**Issue by Keyves** [vuejs/vue#3017]
在图片的回调中调用此函数，从而更改宽高，按文档的做法是$set一个新对象，但这样会触发这个图像的其它属性的视图更新，比如src,导致读取src的img再次渲染从而触发回调造成无限循环的情况
* `vuex` -> `store`
```js
//picList[0] => {width: '', height: '', src: ''}
const picList = state.picList[0]
picList.width = width
state.picList.$set(0, {...picList})
```

然后我发现在模版文件里这样改，可以做不到src不更新
* template
```js
methods: {
  changePicItem(width) {
     this.$set('picList[0].width', width)
  }
}
```
但是`store.state`并没有`$set`方法，而且不支持类似chai的表达式
```js
state.picList.$set('[0].width', width) //无效
```

**Comment by yyx990803** [comment]
为什么不是 priceList[0].width = width? 完全没必要用 $set...

**Comment by Keyves** [comment]
但是这个属性是中途引入的，回调读取后才有的宽高

**Comment by yyx990803** [comment]
初始声明为 0 不就行了

**Comment by Keyves** [comment]
@yyx990803 好吧 但我觉得数据量一多 总会出现不能初始或者初始麻烦的情况吧，为何不尝试增加'[0].a.b'的支持呢。。。
