### ISSUE TITLE
[Bug][2.0] Error value watched with Chinese input on `input` tag.

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#3018]
>     <div id="editor">
>       <input name="song-name" type="text" id="song-name" v-model="songname" class="text">
>       {{ songname }}
>     </div>
> 
>     <script>
>       new Vue({
>         el: '#editor',
>         data: {
>           songname: 'hello'
>         }
>       })
>     </script>

if you input word with chinese, You'll see a miracle. like this:

![20160602174938](https://cloud.githubusercontent.com/assets/7891096/15741307/a8d7b104-28eb-11e6-9ef2-bd95506bbac8.png)

**Comment by posva** [comment]
Can you provide more information on how this is a bug?
Please read the [Contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) next time

PS: It's not the first time you do this 😕

**Comment by aviggngyv** [comment]
Trust me, this is so obvious, a number of my friends have confirmed!
Sorry, I forgot to tell you, I use Vue 2.0

**Comment by aviggngyv** [comment]
Maybe you need install a chinese input software,  not English

**Comment by posva** [comment]
You're still not explaining what happens. It's not a matter of trust...

**Comment by aviggngyv** [comment]
sorry, look this gif:

![20160602220702](https://cloud.githubusercontent.com/assets/7891096/15747715/996f830e-290e-11e6-8190-35aac5e3f040.gif)

**Comment by aviggngyv** [comment]
>   function onCompositionEnd(e) {
>     e.target.composing = false;
>     **// trigger(e.target);**
>   }

and if try to comment this line ( line 3321), this bug will fixed.

**Comment by yyx990803** [comment]
2.0 dist files are out of date, please wait until an actual release before filing bugs.
