### ISSUE TITLE
Javascript ForLoop Issue in data object.

### ISSUE THREAD

**Issue by jovvybersamin** [vuejs/vue#3019]
Hi Guys,

I'm using forloop to check the items in my data in COMPONENT.

```
{
  data:function(){
    return {
      items:[
       {id:1,name:'John'},
       {id:2,name:'FooBz'}
      ]
    }
  }
}
```
now I want to check the value first in console in ready hook of my component.

```
{
  .....
 ready:function(){
   console.log(this.items);
   // this return a [__ob__: Observer]
   this.items.forEach(function(x,y){
       ............
   });
 }
}
```
the this.items return a '[ob: Observer]' which I can't iterate through because the length of that value is 0 it supposed to be 2.

EDIT: this is strange on my JSBIN all are working but in my real code its not. Even though I copied my logic from my real code I'm using Laravel Elixir to compile my javascript and 1.0.24 version of Vue.

[JSBIN](http://jsbin.com/gijaniqero/edit?html,js,console,output)

here is the value return in console from my real code I dump the console.log(this.$parent.items);

![untitled](https://cloud.githubusercontent.com/assets/8434972/15766473/833e0278-2971-11e6-83b6-59b03c7bdfde.png)

**Comment by posva** [comment]
Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.
