### ISSUE TITLE
array.$set removing item from the DOM

### ISSUE THREAD

**Issue by schleumer** [vuejs/vue#3022]
### Vue.js version
1.0.24

### Reproduction Link
http://codepen.io/schleumer/pen/NrqGxg

### Steps to reproduce
Use `array.$set` in a multidimensional array with primitive values.

### What is Expected?
The value to change and the DOM to update.

### What is actually happening?
The value changes, but it's removed from the DOM whilst exists in the array.

**Comment by simplesmiler** [comment]
Looks like a bug. In the meantime you can work around it with `track-by="$index"`.

**Comment by pespantelis** [comment]
This is not a bug.

> [Vue warn]: Duplicate value found in v-for="(column_index, column) in row": -1. Use track-by="$index" if you are expecting duplicate values.

https://github.com/vuejs/vue/blob/dev/src/directives/public/for.js#L658-L667

So, the `track-by` seems to be the only way to accomplish that.

**Comment by schleumer** [comment]
Thanks for clarify this, @pespantelis. 👍

**Comment by simplesmiler** [comment]
@pespantelis you are entirely correct, my bad.
