### ISSUE TITLE
bug of filter 'pluralize'

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue#3023]
###  HTML
`<div id="app">
    <span v-for=" a in b">
        {{a}}{{a | pluralize 'apple' 'orange'}}
    </span>
</div>`

### JS
`new Vue({
    el:　‘#app’,
    data: {
        b: 6
    }
})`

### output

`
0orange 1apple 2orange 3orange 4orange 5orange
`

I think the output should be link:
`
0apple  1orange 2orange 3orange 4orange 5orange
`

Is this a bug of filter 'pluralize'?

Here is[ jsbin link](http://jsbin.com/zocuyem/edit?html,js,output)

**Comment by yyx990803** [comment]
In English, 0 uses plural form...
