### ISSUE TITLE
approach to implement a reusable vuejs spinner directive?

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3025]
Hi, guys,
Sorry for posting this question here. (I have posted in the forum, but no reply).
I am considering approach to implement a vuejs spinner directive which wrap spin.js and can be reused anywhere if needed.
I'd like to use it this way:
```
<div v-spin>
     <ajax-component></ajax-component>
</div>
```
The scenario is : when ajax-component execute ajax operation, the spin should be triggered and show, when ajax finished, the spinner should disappear.
How do you think I should implement this functionality?
The best approach i know maybe is: the v-spin directive will listen a custom event which triggered by ajax-component when ajax is started. But it seems that directive can not listen event, right?

Any proposal is aprreciated!

**Comment by simplesmiler** [comment]
Well, the answer is that you should not implement it as a directive, but rather as a component.
Also, it's better to turn the things around, and let the ajax component import and use the spinner component instead of wrapping spinner component around ajax component.

**Comment by cnweibo** [comment]
@simplesmiler ,thanks for your advice! I have implemented according to your proposal, It works great!
