### ISSUE TITLE
question about event binding in component

### ISSUE THREAD

**Issue by fiongogo** [vuejs/vue#3026]
```
module.exports = Vue.component("tool-bar", {
    template: "<ul>\r\n<li><button  v-on:click=\"greet\">text</button></li>\r\n<li><a href=\"#\">pic</a></li>\r\n</ul>", 
  	methods: {
    	greet: function (event) {
	      alert('Hello ' + this.name + '!');
	      alert(event.target.tagName);
    	}
  	}
});
```

above it‘s my code ,but it doesn't work

and i get the log  is "Failed to resolve directive: on:click"

I don't know why

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, I've tried your code, and it works without any issues: https://jsfiddle.net/simplesmiler/Lrk9sxjf/81/
