### ISSUE TITLE
v-model breaks selectionStart

### ISSUE THREAD

**Issue by kucherenkovova** [vuejs/vue#3029]
### Vue.js version
1.0.24

### Reproduction Link
https://github.com/kucherenkovova/piano/tree/BUG-report-vue
go to demo folder and open index.html

### Steps to reproduce
Input something into the `Email layout` input field.
Put the cursor in the middle of your text.
Hit backspace on the virtual keyboard.

### What is Expected?
The text will be removed in the cursor position.
### What is actually happening?
The text removes from the end of the string. `selectionStart` attribute is changed somehow by Vue.js 

P.S. You can test it on other input elements which do not have `v-model` on it.Everything will work well.

**Comment by posva** [comment]
Hello!

Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

I cloned your repo and tested it on chrome, it works well. Next time provide a simple repro. People can't go through your whole application to help...

**Comment by kucherenkovova** [comment]
Thanks for the feedback. I'll provide a gh-pages link soon. It's impossible to reproduce the bug on the codepen or jsfiddle due to Piano.js nature.

**Comment by posva** [comment]
I see, in that case it may be due to Piano.js. It'd be great if you can create a repro without pianojs 👍

**Comment by kucherenkovova** [comment]
@posva Hi again! Here's a [codepen with repro](http://codepen.io/kucherenkovova/pen/qNONPG?editors=1010)
Steps to reproduce:
1. Insert text into first input
2. Select some text
3. Click a button near your input

Looking forward for your response!

**Comment by posva** [comment]
Thanks! I found the bug. The update resets those values so caching them [here](https://github.com/vuejs/vue/blob/dev/src/directives/public/model/text.js#L74) and taking them back [there](https://github.com/vuejs/vue/blob/dev/src/directives/public/model/text.js#L77) actually solves the issue. I'm not sure about how to test this though. I may have to write an e2e test

PS: I'm doing this tomorrow, going to sleep 😴

**Comment by posva** [comment]
I didn't had internet yesterday 😢 I hope being able to do it this evening

**Comment by posva** [comment]
Finally got internet back. I'm having some trouble creating a test that breaks as a unit test. I'll try again today with an e2e test although it's a by overkill. Calling the blur method on the input doesn't behave the same way as actually doing.
The fix I came up with is not setting the input value if it hasn't changed at blur. It's basically adding `_toString(self._watcher.value) !== el.value` to the conditions [here](https://github.com/vuejs/vue/blob/dev/src/directives/public/model/text.js#L75)
