### ISSUE TITLE
Not support modifying components dynamicly?

### ISSUE THREAD

**Issue by aflext** [vuejs/vue#3035]
The scenario: I need to fetch remote data to get a collection of components to render in the current page, so i want to change the components attribute in then created lifecycle in the main component.

Assuming that i have a main component which renders lots of sub components and the expected code is:
```
<template>
  <div id="home">
      <component v-for="item in items" :is="item.type"></component>
  </div>
</template>

<script>
import $ form 'jquery';

export default {
    data: function () {
        return {
            items: []
        };
    },
    components: {},
    methods: function () {
        loadData: function () {
            var me = this;
            $.get('api/components')
            .then(function (list) {
                  var components = {};
                  var items = [];
                  list.forEach(item, function () {
                      components[item.type] = item.component;
                      items.push(item.type);
                  });
                  me.components = components;
                  me.items = items;
            });
        }
    }
    created: function () {
        this.loadData();
    }
};
</script>

<style src="./index.less" lang="less"></style>
```

**Comment by RenShine** [comment]
you can try $set method

`me.$set("components",components)
`
see [Reactivity in Depth](https://vuejs.org/guide/reactivity.html)

**Comment by aflext** [comment]
@RenShine how can i pass data or event to the sub component in the loop?Some people suggest using v-if in a loop of a list instead of using the preserved `component`

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

Take a look at http://vuejs.org/guide/components.html#activate-Hook
