### ISSUE TITLE
Registration in $refs when call $appendTo(), or another way to add in $refs dynamically

### ISSUE THREAD

**Issue by Saymon-biz** [vuejs/vue#3037]
Let's consider the case with a tooltips, which are added via directive:
```html
<a v-tooltip="{ effect: 'scale', placement: 'right', content: someContent }">
```

E.g. we have the following code inside the ```update``` hook in our directive definition:

```js
var Tooltip = Vue.extend({
  ...
})

var objTooltip = new Tooltip({
  ...
})

this.objTooltip.$mount().$appendTo('body')
```

And we can't know in advance what is the structure of an app, which uses this plugin. But we can assume that the ```body``` belongs to root Vue instance or to any of its children. And lets assume that we need to get access for a one of tooltips via $root.$refs.tooltip_123, but we have no any way to define refs, because in this case we have no the place for ```v-ref``` definition. So may be it 's reasonable to let an opportunity to define a name for ```$refs``` in ```$appendToBody()``` call?

E.g. via third parameter:
```js
vm.$appendTo( elementOrSelector, [callback], [refName] )
```
Or may be provide any way to link components as parent and child:
```js
vm.$addRef(objChildComponent)
```
or conversely
```js
vm.$addAsRefTo(objParentComponent)
```

**Comment by yyx990803** [comment]
If you are not relying on `$refs` in your template for reactive updates, you can just set `vm.$refs[key] = child`, and remember to unregister it when the vm is removed.

However, manually instantiating child components is not part of the recommended best practice and especially in 2.0 you should consider using a proper component instead.
