### ISSUE TITLE
Issue with nested v-for loop

### ISSUE THREAD

**Issue by senn77** [vuejs/vue#3041]
Hello,

I don't know if it's a bug or not but unfortunately  nobody could help me.
I have 2 items, when I click on one of both I call a method which display content (with v-if property and 2 nested v-for). It works well the first time but next, I get this message : Uncaught TypeError: Cannot read property 'raw' of undefined ? Basically, I want to display the current content (after click on the item) and hide the others in playing with a "visible" boolean property.

Here is the whole code (simplified) :http://jsbin.com/jubuko/edit?html,output
and project test here : http://telkea.com/CI-test/

This is odd, I hope we could help me.
Thank you very much.

**Comment by simplesmiler** [comment]
Hi!

Didn't you mean `children1 in object.children` instead of `children1 in object` in the second loop? It appears to be working when this is fixed.

**Comment by senn77** [comment]
you are the boss!!!!!! 
Thank you so much.
