### ISSUE TITLE
Transition exception: VueRouter / keep-alive / Hot-reload

### ISSUE THREAD

**Issue by drcmda** [vuejs/vue#3042]
Every now and then Vue seems to break when hot-reloading VueRouter with keep-alive routes. The error is: *vue.common.js:1082 Uncaught TypeError: Cannot read property '__v_trans' of null*. Digging in it looks like vm.$el is empty in the insert function. Null is passed up until it crashes in applyTransition.

The callstack is as follows:

``` javascript
function applyTransition(el, direction, op, vm, cb) { el = null, direction = 1, op = (), vm = VueComponent {$router: Router, $el: null, $parent: null, $root: null, $children: null…}, cb = undefined
  var transition = el.__v_trans;

  function beforeWithTransition(el, target, vm, cb) {
    applyTransition(el, 1, function () {

    function insert(vm, target, cb, withTransition, op1, op2) { vm = VueComponent {$router: Router, $el: null, $parent: null, $root: null, $children: null…}, target = text, cb = undefined, withTransition = undefined
        ...
        op(vm.$el, target, vm, cb);

          Vue.prototype.$before = function (target, cb, withTransition) { target = text, cb = undefined, withTransition = undefined
            return insert(this, target, cb, withTransition, beforeWithCb, beforeWithTransition);

            VueRouter.transition
            VueRouter.insert
            ...
```

I do not use transitions yet and have no idea what it might be. It happens when i switch routes after hot-reloading changes.

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I seem that this is vue-router issue.
Please report the below issues.
https://github.com/vuejs/vue-router/issues
