### ISSUE TITLE
Editing the DOM inside Vue instance with Devtools stops Vue binding altogether

### ISSUE THREAD

**Issue by benhanks040888** [vuejs/vue#3049]
[http://jsfiddle.net/6pzxsx12/1/](http://jsfiddle.net/6pzxsx12/1/)

Steps to reproduce:

1. Open DevTools
2. Traverse to `<div id="app">` then edit as HTML
3. Add something anywhere inside the `<div id="app">`
4. The counter stops.

**Comment by yyx990803** [comment]
This is expected, you replaced it with a different DOM Node that Vue has no way to track.
