### ISSUE TITLE
[Feature] Mouse event listener modifiers

### ISSUE THREAD

**Issue by edjroot** [vuejs/vue#3050]
First of all, I'd like to thank everyone who has contributed to this absolutely wonderful library.

I was reading the docs on [key modifiers](https://vuejs.org/guide/events.html#Key-Modifiers) (for example, `@keyup.enter`) and was wondering if it would be worth having the same kind of thing for mouse buttons. This would make handling much simpler since the same events that are available for the left button by default would be for the other ones as well without the need for repetitive checking in the JS code.

For instance:

```
<button @click.left="hello" @click.right="bye">Say hello or bye</button>
<div @mousedown.middle="drag">I'm draggable!</div>
```

The only possible "downside", I guess, is that `@click.right` would become a synonym for `@contextmenu`, but it doesn't sound that bad.

Is this viable?

Thanks in advance!

**Comment by zoomclub** [comment]
Yes, there is some good potential with the @event interface. Like the suggestions made and also had a question/suggestion along the same lines for an @stream interface here: https://github.com/vuejs/vue-rx/issues/5

**Comment by Kingwl** [comment]
ping @posva
