### ISSUE TITLE
[Feature] Chain event listeners in HTML

### ISSUE THREAD

**Issue by edjroot** [vuejs/vue#3051]
Would it make sense to chain event listeners so that the associated expression is only evaluated when the whole group of events occurs? I'm not sure how much of a good idea this is or how useful it would be for most people, but I see several cases where this could be applied. It seems to me that code could become cleaner and simpler to maintain. The basic syntax could be:

    <div @mousedown.stop@mousemove="paint(me, $events)">[....]</div>

I'm including some further ideas, but they may be flawed:

```
    // js
    Vue.directive('on').keyCodes.shift = 16;
    Vue.directive('on').keyCodes.ctrl = 17;
    Vue.directive('on').keyCodes.G = 71;
```

1. When chaining events, some other symbol such as `&` could be used instead of `@`: `@foo&bar.self` (but `@` is easier to see).
1. Shorter syntax for multiple modifiers on the same event type: `@keydown.left,right="doCombo"`
1. Events that should be triggered only once until the user releases at least one of the keys and presses them again (not completely related to this issue, but I thought it would make sense to include it here):

```
    <textarea @keydown.single.ctrl,G="toggleSearchAndReplace">Replace me</textarea>
```

1. Multiple event groups:

     ```
    <div @dblclick="doStuff"
             @keydown.ctrl@dblclick="doSpecialStuff"
             @keydown.ctrl,shift@dblclick="doSuperSpecialStuff">
             I'm special!
    </div>
    ```

  - There's an issue here: When an event group fires, what should happen to the other ones that match the current state?

    - Maybe they shouldn't run by default, but do so in the presence of some new modifier (_e.g._, `always`)....
    - or there could be even another symbol, like a "negation operator", so that one could use `@dblclick!keydown` and `@keydown.ctrl,!shift@dblclick`. Benefits are questionable for the complexity, but you are probably a better judge.

I hope my ideas can be useful in some way, even if only to spark some in you. Thanks for your attention!

**Comment by phanan** [comment]
I think this introduce a whole new layer (or two) of implicitly and unreadability. Not to mention, when you "combine" two events like this `@keydown.ctrl@dblclick="doSpecialStuff`, what event will `doSpecialStuff()` receive? Is it the `keydown` event, or `dblclick` event, or both?

**Comment by smolinari** [comment]
I think the events would be all or nothing. A logical AND. So, all the key presses would be needed to do "doSpecialStuff". I can see where the idea is heading, like for making very interactive programs, and certainly mixing and matching events would be handy. However, I agree with phanan, placing them all in the HTML as suggested isn't very clean. 

@phanan - is there a way to mix and match events and introduce them cleanly in the HTML currently?

Scott

**Comment by edjroot** [comment]
I could have made it more explicit, but my idea was that all events would be passed in an array, as the first example shows.

You're probably right about your assertion, but honest question: What are the best current alternatives? Is it currently possible to do something cleaner in HTML? I can only think of associating a function (probably the same one) for each event _(e.g., `<div @keydown.ctrl="check" @keydown.shift="check" @dblclick="check">do it</div>`),_ checking these combinations within it, and then calling the appropriate functions. This seems more verbose, at least to me. But I'm not very good at these things, so I may be getting it all wrong.

**Comment by phanan** [comment]
I'd go for a simple `@click` and then inside the handler, check for the event's `ctrlKey` or `altKey` etc. to determine the action.

**Comment by blake-newman** [comment]
Agree with @phanan

This implementation is unreadable, and confusing to the eye. The solution should be help within the handler, allowing much more flexibility.

**Comment by edjroot** [comment]
Ok, thanks.
