### ISSUE TITLE
Nested components (tree structure) communication problem

### ISSUE THREAD

**Issue by iNDicat0r** [vuejs/vue#3052]
I have got a json data structure which represents a file system. So i have a root folder and i have nested folders, and folders can be inside nested folder with not limitation on the depth of the folder.. Vue has an example of such a structure and i want some help with an issue that i face.

```
<item
												:model="treeData"		
											>
											</item>
```

```
<script type="text/x-template" id="item-template">
	<li class=''>
		<span :class="{'active': selected}"  @click="select" class=''>
			<span class='title'> {{ model.folder.name }}</span>
		</span>
		<ul style='display: block;'>
		<item
			v-for="model in model.folders"
			:model="model">
		</item>
		</ul>
	</li>
</script>
```

Now i want to be able to when i select a folder the other components change their active state and remove their "active" class so one folder is selected only..

I have tried to dispatch or broadcast but that doesnt inform all the component that a change has happened.... so basically i need to inform all the other component for a change when a folder component is clicked... any way to do it ?

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

You can use a variable passed with `sync` to all children items. The click can set this variable and the state will depend on that variable

**Comment by stefanosandes** [comment]
Maybe this can help: https://jsfiddle.net/kfckjw50/

**Comment by smolinari** [comment]
I believe you should avoid using `sync` as it will be deprecated in 2.0. 

https://github.com/vuejs/vue/issues/2873 (under Props Behavior)

Scott

**Comment by iNDicat0r** [comment]
Please see the template structure that I have included in the first post. How should I pass data to the inner item componemt? The problem is that the child items componemts are not directly childs of the parent vue instance..they can be childs of childs of childs...of the instances.. I need some clarification here
