### ISSUE TITLE
view doesn't update after model update 

### ISSUE THREAD

**Issue by hardfist** [vuejs/vue#3055]
### Vue.js version
1.0.18~1.0.24
### Reproduction Link

[1.0.18](http://jsbin.com/mobozinoni/edit?html,console,output)
[1.0.17](http://jsbin.com/govirekabo/1/edit?html,console,output) 
### Steps to reproduce
step1: check the first checkbox  in left table
step2: check the first  checkbox in right table
### What is Expected?
I expect it generate the same result of the two version and after I check the first check box on the right table,all the checkbox bellow are checked.
### What is actually happening?
It generates different results of the two version. I try version between 1.0.18~1.0.24,after I check the first checkbox on the right  ,all the checkbox bellow  are not checked,which is not what I expect.

**Comment by simplesmiler** [comment]
Your `selectedRows` is a computed property, so manual changes to it are ignored.

**Comment by yyx990803** [comment]
This is not a bug, you mapped your array to different objects in the computed property, mutating these derived objects will not cause any changes because they are "temporary" and will be lost whenever your source data changes.
