### ISSUE TITLE
How to insert template into nested component?

### ISSUE THREAD

**Issue by elonbase** [vuejs/vue#3057]
Hey, guys! I am very new to Vuejs and my english is poor. I hope you can see what i want to express :) 

Okay, i have a department tree,i use the official example——TreeView to render it.Yeah,it work well.And now i have got users's information from backend by vue-resource, i want to render users's information under the department item which is clicked.Here is my goal and code.

![tree.jpg](https://github.com/elonbase/vue-learn/blob/master/deptree.jpg)

Treeview.vue
    
	<template>
		<div>
		<li v-for="model in models">
    		<div @click="renderUsers($index,model.departmentid)">
    			<span>{{model.departmentname}}</span>
      			<span>addGroup</span>
      		</div>
      	<ul v-if="isFolder">
        	<item :models="model.children">
        	</item>
      	</ul>
      	</li>
		</div>
	</template>

my users's information template like this:

    <li v-for="user in users">
      <img src="{{user.url}}"/>
      <span>{{user.username}}</span>
    </li>
So,how can i insert the users's information template under the department item dynamically,or other better ways to achieve. Thanks!

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you should put the expanded variant in the template directly, and tell Vue to show it conditionally with `v-if`: https://jsfiddle.net/simplesmiler/Lrk9sxjf/85/
