### ISSUE TITLE
Add a alias for v-model

### ISSUE THREAD

**Issue by danielschmitz** [vuejs/vue#3058]
Please add a alias for v-model like @click or :bind

My suggestion: "m"

Example

```
<input type="text" m="user.name"/>
```

**Comment by posva** [comment]
Come on, it's not on the same level :smile:
You use events and bindings much more times that you use `v-model`.
That said, you can create your own directive `v-m` that adds`v-model` to an element before other directives

**Comment by yyx990803** [comment]
`v-on` and `v-bind` can use shorthands because **they are almost always used with arguments**. I don't think shorthands for non-argument usage makes sense.

**Comment by shadowcodex** [comment]
I think this could be useful. To do something like `$property` to bind any property vue instance in the form of a model? So instead of `v-model="name"` one would simply do `$name`.

**Comment by mikeerickson** [comment]
How about = 

<input =name />
vs
<input v-model=“name” />

Or I +1 use of @

**Comment by dnistreanu** [comment]
So, no shorthand for v-model yet? How about **`$="name"`** ?

**Comment by sirlancelot** [comment]
This issue was closed over three years ago. `v-model` is sufficient.
