### ISSUE TITLE
微信中有关dom无法响应属性变化的奇怪问题。

### ISSUE THREAD

**Issue by guan6** [vuejs/vue#3059]
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/chongzi/6s53gxrp/1/

### Steps to reproduce
页面滚动过程中，快速点击按钮，将导致一个奇怪的问题，vue中数据的变化不会再出发dom更新。

### What is actually happening?

此问题出现在微信浏览器中，其他浏览器没有此问题。

问题详细描述：

设备：iphone6 （ios9.3.2）
微信版本：6.3.19

快速滚动页面，当页面滚动还未结束时，点击页面中的任何按钮（此按钮通过修改某个属性，控制dom显示/隐藏）。快速重复以上操作。

很快，dom不再随属性变化而变化（无论是否再滚动页面）。

经测试，click事件是被触发的，属性值也会被改变。但是dom不会再随着属性变化而更新了。

-----------------------------------

下面的一个问题，没有仔细测试。

如果data中绑定的数据稍大。比如jsfiddle中的样子。则在微信中点击被渲染出来的按钮时。越是最后渲染出来的按钮，响应速度越慢。明显感觉延迟。

所有这些现象，都有一个共同点，就是：通过属性变化，控制dom变化时才出现。

**Comment by guan6** [comment]
此问题可能非vue问题，但是却影响到vue在微信中的使用。刚刚又测试了一下，凡是页面滚动未完成时，点击那些通过修改属性来控制dom的按钮时，都会导致vue重新触发dom更新的功能失效。

**Comment by yyx990803** [comment]
这个问题在最新版本里已经修正过了，升级一下。

**Comment by HelKyle** [comment]
尝试了一天，没有找到问题根源，替换1.0.26版本就解决了，感谢尤大！！！
