### ISSUE TITLE
Update CDN links from latest to pinned versions

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3060]
Since jsdelivr's "latest" is now the 2.0 alpha branch, any repos referencing such CDN links or jsfiddles containing such links should be updated with pinned versions. Some jsfiddles are also referencing pre-1.0 versions of Vue when it isn't appropriate, which should be fixed.

Necessary updates include:

- [x] [jsfiddle links](https://github.com/search?p=1&q=org%3Avuejs+jsfiddle&ref=searchresults&type=Code&utf8=%E2%9C%93)
- [x] [jsdelivr links](https://github.com/search?utf8=%E2%9C%93&q=org%3Avuejs+%22jsdelivr.net%2Fvue%2Flatest%22&type=Code&ref=searchresults)

What may be even more ideal for jsfiddles is a strategy similar to [this](https://github.com/chrisvfritz/vue-workshop/blob/master/src/config/exercises.js#L35), where code contents are directly embedded in the URL. This way, linked code examples could be kept in version control and programmatically updated with the appropriate versions of Vue. 

Testing for a bit, I wasn't able to get that working with jsfiddle - but now that they're sponsors, maybe we could ask them. 😉

**Comment by yyx990803** [comment]
Removed cdnjs since there are no `latest` usage for it.

**Comment by yyx990803** [comment]
done.
