### ISSUE TITLE
[2.0] server render with renderToStream

### ISSUE THREAD

**Issue by ustbhuangyi** [vuejs/vue#3061]
hi, I try to use renderToString and renderToStream at server-side，it works well with renderToString，but as for renderToStream，I don't know how to deal with the back-end template such as jade、ejs and so on. renderToStream has better performance than renderToString when the component is complex，but in real application it seems not easy to apply on the existed framework such as express, so I hope there is an example to show us how to use renderToStream in real application，thx~

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

The example is here https://github.com/vuejs/vue/blob/next/benchmarks/ssr/renderToStream.js.
About using express, you just need to do `stream.pipe(res)`. Here's is an example https://youtu.be/c9esL3I4IGM?t=1h31m55s
