### ISSUE TITLE
Multiline HTML interpolation fails on 1.0.24

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3062]
[Here's a minimal viable example.](http://jsbin.com/xababikije/edit?html,console,output)

Not a huge deal, but:

``` html
<pre><code>{{{
  code
}}}</pre></code>
```

is often preferable to:

``` html
<pre><code>
  {{{ code }}}
</pre></code>
```

since preformatted text would preserve the line breaks at the beginning and end of the code block.

**Comment by simplesmiler** [comment]
I think it's better done with just `<pre><code>{{{ code }}}</code></pre>` (an I think you actually meant double brackets).

But I agree. Newline is already handled correctly in double-bracket expression, so for the consistency sake it should be handled correctly in the triple-bracket expression.

**Comment by chrisvfritz** [comment]
@simplesmiler In the real-world case where I encountered this, `pre` and `code` both had attributes making that line longer and `code` was actually `highlight(exercise.example.code)`, so with everything added up, splitting it out into multiple lines was much nicer. 😃  I did also mean triple brackets here, since the code was being passed through highlight.js.
