### ISSUE TITLE
What's the use of  'v-bind="obj"'?

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue#3065]
This is [API document address](http://vuejs.org/api/#v-bind)。

I have two question.

1. first: 
 What's the use of  `<div v-bind="{ id: someProp, 'other-attr': otherProp }"></div>` ?
2. last:  "Note in this mode class and style does not support Array or Objects. "-----Is this sentence in document  wrong? [example](http://jsbin.com/katosedoge/edit?html,css,js,output)

**Comment by kazupon** [comment]
Hi!
Thank you for your question. 😃 

>first: What's the use of `<div v-bind="{ id: someProp, 'other-attr': otherProp }"></div> `?

This usage is the data binding which bound an object  to a value of each attributes defined as reactive data (e.g. `data` option or computed properties).
Therefor, You need to define the property with `data` option or computed properties, etc.

>last: "Note in this mode class and style does not support Array or Objects.

I checked your example codes.
I found that `someProp` and `otherProp` don't defined in your codes.
You can work with below code.

```js
new Vue({
  el: '#app',
  data: {
    classA: 'a',
    classB: 'b',
    someProp: '11',
    otherProp: 'red'
  }
});
```

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, the use case for this is a dynamic list of attributes, unknown upfront (e.g. props and attributes depending on the type of component). As for the class/style, here's what it's talking about: http://jsbin.com/vusefohife/1/edit?html,css,js,output

**Comment by Cuixote** [comment]
Thank you very much!I will be ask questions in the right place to  later.
