### ISSUE TITLE
suggest: vue compontent should export complite scope object

### ISSUE THREAD

**Issue by niluanxy** [vuejs/vue#3067]
i was use vue in my work，and have write many compontent of vue,but when i use compontent in repeat,like v-for,it does't have no way to get a root compile scope. if i what to get compile scope value,i must define it in props,whether does the vue will export compile scope,i now can get root scope;

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

**Comment by simplesmiler** [comment]
As for the question, component should not rely on values being implicitly provided in the compilation scope. That said, you can pass the whole parent `$data` as a prop explicitly: `<component :parent-data="$data">` (make sure to define the `parentData` prop in the component).
