### ISSUE TITLE
two-way bind is always tip error

### ISSUE THREAD

**Issue by niluanxy** [vuejs/vue#3068]
i use two-way bind in my compontent,but it always tip error: vue.js:1018 [Vue warn]: Prop "value" expects a two-way binding type. But when i use  :value.sync it can run will,i has try set type.

![qq20160613-1 2x](https://cloud.githubusercontent.com/assets/7076522/16005192/852fe7d4-3198-11e6-8917-1fcb55c98ac5.png)
![qq20160613-2 2x](https://cloud.githubusercontent.com/assets/7076522/16005226/b4c54c78-3198-11e6-9e96-be8781836aad.png)

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

That's normal. Two way binding is achieved the `sync` modifier
