### ISSUE TITLE
关于 Error when evaluating expressio 的问题

### ISSUE THREAD

**Issue by lmnsg** [vuejs/vue#3070]
当代码里报了很多这个错误以及频繁设置non-existent path on vm instance的时候，
在 mac 的 chrome 中，会导致 chrome卡死，通过活动监视器发现是 google chrome helper 占用了高达10多 G 的内存。
不知道是什么原因， 下面贴上一些报错以及活动监视器 的截图
![image](https://cloud.githubusercontent.com/assets/10400425/16013007/652658d0-31be-11e6-9d64-99d08eab6857.png)
![image](https://cloud.githubusercontent.com/assets/10400425/16013046/8c6dc18a-31be-11e6-9c78-744ce0e7ab5d.png)
![image](https://cloud.githubusercontent.com/assets/10400425/16013066/a24530c4-31be-11e6-8472-f38fa2fdcffd.png)

@yyx990803 help..

**Comment by yyx990803** [comment]
你想要我帮什么忙？Chrome 的问题我又没办法。如果是 Vue， 我唯一的建议是好好照着文档写，别触发警告...

**Comment by lmnsg** [comment]
@yyx990803 好的...  我想问的是，vue 在触发这样的警告后， 是否会造成严重的性能问题，或者内存问题？ 因为业务需要频繁 set non-existent path

**Comment by yyx990803** [comment]
思考下是否真的需要这样做。如果实在不行设置 `Vue.config.silent = true`

**Comment by lmnsg** [comment]
ok...   不过还是想你看下是否会有我上面问的问题，关于，vue 在触发这样的警告后， 是否会造成严重的性能问题，或者内存问题？ 
因为我发现在 safari 没有这样的现象。
thanks.

**Comment by yyx990803** [comment]
如果你关掉控制台不出现性能问题，就说明这是 Chrome 的 devtools 导致的，和 Vue 无关。
