### ISSUE TITLE
Array of primitive values isn't binded

### ISSUE THREAD

**Issue by YerkoPalma** [vuejs/vue#3072]
### Vue.js version
1.0.24 and 1.0.12

### Reproduction Link
[example 1](https://jsfiddle.net/crabbly/Leqy66r8/)
[example 2](https://jsfiddle.net/yerkopalma/m1byy7k3/1/)

### Steps to reproduce
Click on the buttons that modify an array of booleans.

### What is Expected?
The reactive data to be updated

### What is actually happening?
data isn't updated

===

It seems that Vue isn't changind reactive data arrays of primitive data, booleans in this case. If there is an array defined like this

```
[true, true, false]
```

it won't be updated. A workaround for that case is to use it like this.

```
[{value: true}, {value: true}, {value: false}]
```

If this isn't a bug, then it should be mentioned in the docs.

**Comment by simplesmiler** [comment]
It has nothing to do with primitive values specifically, its a reactivity caveat due to limitations of JavaScript: https://vuejs.org/guide/list.html#Caveats
