### ISSUE TITLE
Selected status of the select element is not set after selected option is removed

### ISSUE THREAD

**Issue by xMort** [vuejs/vue#3076]
Hello,

I'm not sure if this is a bug or not but I just found about this behavior in my application. Unfortunately it's legacy application that is rendered on server and all the Vue attributes are attached via jQuery in onload event. This is the reason why I cannot render whole select element by Vue repeater.

When one Vue computed variable removes active selectbox option from another select, this other select will not trigger changed event and second computed variable will not get recalculated.

I replicated the behavior in following jsFidle [http://jsfiddle.net/wdgfnn0h](http://jsfiddle.net/wdgfnn0h)

When you try to switch the second select box you cannot because there is no other option. Switch the first one and second checkbox has second option. When you use it, the watcher will enable checkbox on the right. However when you switch the first select box again the option will get removed from the second select box correctly and selection is changed. Unfortunatelly the "second" model observer is not triggered and checkbox stays enabled which is incorrect. Is there some mistaken in how I use Vue or is this a bug?

**Comment by pespantelis** [comment]
The watcher enables the right dropdown, because the `second` variable has changed.
If you switch the first dropdown, the `second` variable will not be changed. Hence, the watcher will not be triggered correctly.

I suggest you to reset the `second` variable when the first dropdown changes.

http://jsfiddle.net/pespantelis/wdgfnn0h/1/

**Comment by xMort** [comment]
Thank you for the example, I will try to implement it similarly. However I'm not sure why the `second` is not changed when first dropdown is used. The relevant selected option element was removed from the dropdown and model change should be triggered imho as now the DOM and model is out of sync.

**Comment by xMort** [comment]
I fixed it by triggering DOM `change` event on the dropdowns that have the options removed. It works now. Each time expression that removes the option is recalculated I fire the change event, the Vue get notified about the change and if some relevant property needs to be updated, its recalculation is triggered. It would be nice if this would happen automatically (it would be handled by framework itself) but I will not pressure anyone and close this issue.

Working example is here if anyone is interested or is trying to solve something similar:
[http://jsfiddle.net/8s3s8sk8/](http://jsfiddle.net/8s3s8sk8/)
