### ISSUE TITLE
RangeError with form of method "POST

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3079]
As [reported here](https://github.com/vuejs-templates/webpack/issues/162), [this simple app](http://jsbin.com/bulahadezi/1/edit?html,console,output):

``` html
<app></app>

<script>  
  Vue.component('app', {
    template: '\
      <form method="POST">\
        <input name="attributes">\
      </form>\
    '
  })

  new Vue({ el: 'body' })
</script>
```

throws:

```
vue.js:235 Uncaught RangeError: Invalid array length
```

If changing the form method to something other than `POST` or the input name to something other than `attributes`, it seems to work fine.

**Comment by pespantelis** [comment]
I believe that it is not a bug.

Each element has an [`attributes` property](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes) which returns a collection of all attribute nodes. By using an input field named **attributes**, replaces the contents of that property ([demo](https://jsfiddle.net/pespantelis/7f7xh1Lt/)).

The Vue [uses that property](https://github.com/vuejs/vue/blob/master/src/compiler/transclude.js#L131-L135) and I thought that it is hard (even impossible) to change.

An error message to inform about that conflict, I believe it's ok:
```js
function extractAttrs (el) {
  if (el.nodeType === 1 && el.hasAttributes()) {
    if (!(el.attributes instanceof NamedNodeMap)) {
      console.error('...')
    }
    return toArray(el.attributes)
  }
}
```

Also, if (for any reason) we want to set a field named **attributes**, we could interpolate the `name` attribute:
https://jsfiddle.net/pespantelis/qoLpbxfv/

**Comment by yyx990803** [comment]
This is exactly what @pespantelis described above. Unfortunately, there's no way to workaround this from Vue's part. The recommended solution is **avoid using input names that are also native DOM Element properties**.
