### ISSUE TITLE
How to preselect for select element

### ISSUE THREAD

**Issue by etanxing** [vuejs/vue#308]
How to set `selected` attr to `<option>` element whose value is equal to item.category? Especially when item.category is changed.

```
<select class="form-control" name="template" v-model="item.category">
            <option v-repeat="templates" value="{{name}}">{{name}}</option>
</select>
```

**Comment by dbrown546** [comment]
<select v-model="select">
    <template v-for="option in options">
        <option v-bind:value="option" v-bind:selected="option == savedOption">{{ option }}</option>
    </template>
</select>

I know this is old, but ran into this. This seems to solve the issue.

**Comment by cyrilchapon** [comment]
That doesn't answer the question. The question is not "how to bind a model to a select". The question is "how to preselect select element" which is pretty different.

I personaly need both v-on:change behavior and preselect, without binding to my model property (I need to one-way databind, once)

**Comment by LinusBorg** [comment]
Please don't comment on closed two-.year old issues.

Ask questions on forum.vuejs.org, or open a new issue if you found a bug.

Thanks!

**Comment by cezar62882** [comment]
http://jsfiddle.net/tyb22/25/

**Comment by nickmessing** [comment]
@cezar62882, you know this was close  Jun 21, 2014?

**Comment by ergonomicus** [comment]
@nickmessing , you know @cezar62882 actually helped me July 7, 2017?

**Comment by nickmessing** [comment]
@ergonomicus, initial issue was about Vue 1, now it's Vue 2, can you please tell what browsers behave wrong when using simple `:selected="name == item.category"` as opposite to ternary as in @cezar62882's example?

**Comment by ergonomicus** [comment]
@nickmessing I was not talking about weather to use ternary or not. The thing is that @cezar62882 provided a working example for Vue 2 that pointed me in the right direction, that's all. And I got here by desperately google-ing around for solution, so that might help others too in the future...

**Comment by nickmessing** [comment]
@ergonomicus, good point, sorry for being rude @cezar62882.

**Comment by guilhermeaiolfi** [comment]
I took the example and expanded to my use case: http://jsfiddle.net/e5t758h6/1/

What am I doing wrong? I would expect it to be preselected.

**Comment by nickmessing** [comment]
@guilhermeaiolfi, you cannot use an object as `v-model`, that's designed for strings

**Comment by guilhermeaiolfi** [comment]
Sure you can. I've used it before. It's just not working for pre selecting using the v-if.

**Comment by nickmessing** [comment]
@guilhermeaiolfi, http://jsfiddle.net/e5t758h6/2/ your fiddle without `v-model`... when you do `:value="something"` and `something` is an object it gets converted to string `[object Object]` so `v-model` in here cannot be used as an object. Use just `:selected` and `@change`, this is an example how that is possible in your context: http://jsfiddle.net/e5t758h6/3/

**Comment by nickmessing** [comment]
And please, don't use Github issues for questions:

> For questions and support please use the [Discord chat room](https://vue-land.js.org/), [Gitter chat room](https://gitter.im/vuejs/vue), or [the official forum](http://forum.vuejs.org). The issue list of this repo is **exclusively** for bug reports and feature requests.

https://github.com/vuejs/vue#questions

**Comment by sirlancelot** [comment]
@guilhermeaiolfi If you're using `v-model`, then you don't need to hard-code a selected attribute. However, you need to be aware that `v-model` on a `<select>` requires strict equality `===` to an `<option>`'s value in order to get selected. I updated your Fiddle here: http://jsfiddle.net/e5t758h6/4/

**Comment by bajras** [comment]
Quick question:

I’m creating dynamic selects depending on the data and would like to set it in a way where the first option is always selected and is passed in to the v-model. Since i'm setting formData to empty object on initial load and v-model is bind to that it doesnt get assigned to the v-model. How can I get it to work where I would like to add the selected option to be in the v-model.

```html
<select v-model="formData[word.name]" :name="word.name">
 <option v-for="(option, index) in word.fieldProps.opts" 
 :key="index" :value="option.value" 
 :selected="index === 0 ? 'selected' : ''">{{ option.value }}</option>
</select>
```

```javascript
data() {
 return { 
 formData: {}
};
```

**Comment by daintycode** [comment]
Something like that still doesn't work. The first tr has no real selection, it just uses the first option. All options after it get the right one selected.

`groupA` is a bunch of objects having a prop called `propA`, which will determinate which one of the things in `groupB` (objects with keys where one will have the same name as `propA`) is selected. So selected should be applied if `bkey === a.propA`.

Using `:selected="a == b"` won't work at all, neither with or without `v-model` .

```
<tbody id="stuff">
	<tr v-for="(a, akey) in groupA">
		<td class="cell">
			<select v-model="a.propA">
				<option v-for="(b, bkey) in groupB" v-bind:value="bkey">{{ b.propB }}</option>
			</select>
		</td>
	</tr>
</tbody>
```

**Comment by bhavinjr** [comment]
simply use it. it is work for me `Vue:- ^2.5.11`
```
<select v-model="user.role">
        <option v-for="(role,key) in roles" 
	 selected="key == user.role"
	 :value="key">
		 {{role}}
	 </option>
</select>
```

**Comment by manusiakemos** [comment]
you should use :selected
