### ISSUE TITLE
Ignoring reactivity on certain data  properties

### ISSUE THREAD

**Issue by iNDicat0r** [vuejs/vue#3082]
Imagine within a component I have got a property that references a jquery selector or a plugin..in my case I use jquery datatable and initialization/configuration of this plugin is done within a components which saves the state of this plugin to a local property. 

So after vuejs does its magic I can see this property has been modified by vue js and all the extra getters and setters are set etc..

In such cases I would like to just tell vue js to ignore reactivity on this property because essentially its doing extra stuff that are not necessary in such cases.

**Comment by yyx990803** [comment]
Don't include it in `data`, just set the property in `created` hook, e.g. `this.nonReactive = { ... }`.
