### ISSUE TITLE
how to get parent component props?

### ISSUE THREAD

**Issue by justnull** [vuejs/vue#3083]
I get a component from NPM.
```
<collapsible :accordion="true">
                      <collapsible-item >
                        <p slot="header" v-on:click="greet" :my-message="isOpened" class="bt f14"><span style="position: relative;top: 7px">test1</span></p>
                        <p>body 1</p>
                      </collapsible-item>
                      <collapsible-item>
                        <p slot="header" class="bt f14"><span style="position: relative;top: 7px">test2</span></p>
                        <p>body 2</p>
                      </collapsible-item>
                    </collapsible>
```
 `<p slot="header" class="bt f14"><span style="position: relative;top: 7px">test2</span></p>'` has to be raw html tags. cause of I have try to define a component inside  `<collapsible-item >`. I want to get the 'isOpened' of the props of `<collapsible-item>`.

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
