### ISSUE TITLE
"Error when evaluating expression" occurs only on IE browser?!

### ISSUE THREAD

**Issue by cnx2016** [vuejs/vue#3084]
一段非常简单的代码，v-for循环生成多个option，在Firefox完全正常，在IE11中出现"Error when evaluating expression"。

代码见附件。
[ie_test.html.txt](https://github.com/vuejs/vue/files/315719/ie_test.html.txt)

**Comment by posva** [comment]
Hello!

Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described. Also, please include the version used.

**Comment by cnx2016** [comment]
Good idea!!
I have created a JSBin template, as this:
http://jsbin.com/jayotepumu/edit?html,output

All is ok on firefox, but it is failed on IE.

**Comment by pespantelis** [comment]
You do not need to wrap the `option` in a `template` tag:
```html
<option v-for="opt in opts" value="{{opt.v}}">{{opt.n}}</option>
```

**Comment by cnx2016** [comment]
@pespantelis 
Thank you! It works fine now!

**Comment by posva** [comment]
It seems IE removes `template`s inside `select`s. As @pespantelis said, you don't need to wrap it 😄

**Comment by cnx2016** [comment]
@posva 
You are right, maybe IE removes the template node.
