### ISSUE TITLE
how can i bind a  name for the child component to its parent component

### ISSUE THREAD

**Issue by heiliuer** [vuejs/vue#3085]
![f2do bg rasnxd vr gnni](https://cloud.githubusercontent.com/assets/6746060/16074394/e2bf0ca6-331c-11e6-9008-ddea829f4b6b.png)
how can i define a  variable for the switcher component so i can use it to attach the switcher by the parent component。

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

As for the question, you should pass the data as a prop. If that's not possible, you can access the `$parent` property if it really have to be used inside some other type of component. Keep in mind that this makes the component harder to reason about

**Comment by heiliuer** [comment]
i got it.thanks.

**Comment by heiliuer** [comment]
Maybe i did not describe the issue exactly.
At all,i find the solution by reading readme doc.
Use **v-if** direction.
