### ISSUE TITLE
one nested loop,it has outer loop and inner loop.both of them have two different json object to loop.how to get the index value of outer loop when we are in the inner loop.

### ISSUE THREAD

**Issue by martinko2009** [vuejs/vue#3087]
循环嵌套，外层循环和内层循环，循环的内容分别是两个对象object，内层循环如何获取外层循环的索引值
one nested loop,it has outer loop and inner loop.both of them have two different json object to loop.how to get the index value of outer loop when we are in the inner loop.

有两个v-for循环嵌套，外层循环的是一个对象，内层循环的也是一个对像，因为循环的都是对象，所以无法给索引取一个别名，只能用$index，这样外层和内层循环的索引变量都叫$index，内层循环就无法获取外层循环的索引值，代码如下：
There is a nested loop with two v-fors.outer loop has one json object,inner loop has another json object.because what they loop are both json object,so we can't alias the name of $index,we just use $index in outer and inner loop.it leads to have the same name of $index in both of loops,we can't get the index of outer loop when we are in the innerloop.

 ```
<div id="selectContainer">
    		<div v-for="(key,dataItem) in dataObject">
    		<div v-bind="cc = $index"></div>
    		<template v-for="(key1,dataobj) in dataItem">
    			<div>
    				<div>内层循环索引值 inner loop index value {{$index}}</div>
    				<div>外层循环索引值 outer loop index value {{cc}}</div>
    			</div>
    			<hr></hr>
    		</template>
    		<hr></hr>
    		</div>
	</div>

<script>
    	var vm = new Vue({
    		el:'#selectContainer',
    		data:{
    			dataObject:{
    				aa:{ee:"4",ff:"5"},
    				bb:{cc:"2",dd:"3"}
    			},
    			cc:-1
    		}
    	});
    </script>
```
    
    结果是这样的：
    the result is:
    内层循环索引值 inner loop index value 0
    外层循环索引值 outer loop index value 1
    内层循环索引值 inner loop index value 1
    外层循环索引值 outer loop index value 1
    内层循环索引值 inner loop index value 0
    外层循环索引值 outer loop index value 1
    内层循环索引值 inner loop index value 1
    外层循环索引值 outer loop index value 1
    
    
    内层调用外层循环索引的值都是1，从内层调用外层循环索引的值，并没有随着循环的继续，索引值发生变化。
    请问，这样的情况如何让内层循环获取外层循环的索引值的内容是正确的呢。
    that we get the index of outer loop has the same value, number one, in the inner loop, it won't get different index value in the loop.
    what i want to ask is how to get the correct index value from outer loop when we are in the inner loop.

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

Use this syntax:

```html
<div v-for="(index, item) in items">
  {{ index }} {{ item.message }}
</div>
```
