### ISSUE TITLE
page jump

### ISSUE THREAD

**Issue by fengtaijun0507** [vuejs/vue#3089]
i submit a request in the page login and do not see any response through network ,but the page jump to login with query parameters , including account and password .I have no idea. It is danger!

**Comment by kwando** [comment]
A little more context could probably be helpful.. is this _your app_, _github_, _forum_ or something else?

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:
