### ISSUE TITLE
Maybe there is a bug in vue2.0.0-alpha

### ISSUE THREAD

**Issue by zkwolf** [vuejs/vue#3091]
Vue Version:2.0.0-alpha.3
In /src/compiler/error-detector.js,define a regexp type const `identRE`,when it test string like 'value', it return false and raise an error.

**Comment by posva** [comment]
Hello, can you give more details, please? A jsfiddle would be helpful!

**Comment by yyx990803** [comment]
Ah yes indeed. Fixing

**Comment by yyx990803** [comment]
Closed via https://github.com/vuejs/vue/commit/f058a21b70b88197d9faa51ede8de7d19735526d
