### ISSUE TITLE
Select option DOM didn't change when I change option's data only in pure IE9

### ISSUE THREAD

**Issue by lilyjiang-cit** [vuejs/vue#3093]
### Vue.js version
1.0.23

### Reproduction Link
[https://jsfiddle.net/lilyjiang/jhmfwjcu/](https://jsfiddle.net/lilyjiang/jhmfwjcu/)

### What is Expected?
I have two selects, when I select first one, I want the second one update the dates immediately.

### What is actually happening?
All other browsers have nothing wrong, only on pure IE9 when I change the first select, the second select's option DOM will not update.

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by hgc81538** [comment]
I found that there are UTF-8 spaces (%C2%A0) in line 5, 6, 8, 10, 12 in Javascript in https://jsfiddle.net/lilyjiang/jhmfwjcu/
They may affect IE9 to malfunction.

**Comment by LinusBorg** [comment]
removing "need repro" label since jsfiddle was now provided.

**Comment by kazupon** [comment]
I tried to reproduce in IE9, but did not happen to this issue.
close.
