### ISSUE TITLE
template option not work in vueify dev environment?

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3094]
Hi, 
I am trying to use vue component as follows:
1. define the vue component in .vue file;
2. the component's template should refer to some backend rendered html, and is referred in component' defination via template option;
3. the component is inserted into the html delivered by backend.
The issue is : It seems that template option not work in such case??
Following is the code fragment:
```
export default {
        data: function(){
          return {
              currenttab: 'login'
          };
        },
        template: '#loginmodal'
}
```
When the html is scanned and compiled, vue complains as follows:
```
Invalid template option: #loginmodal
```
Can you give me a clue, whether or not it is a bug or not?

**Comment by yyx990803** [comment]
Make sure the element with that id is present when the Vue instance is rendered. Otherwise, you need to provide a reproduction.

**Comment by cnweibo** [comment]
@yyx990803 , thank you for your proposal. I figured it out: I move the template section in advance , it works, thanks~!
