### ISSUE TITLE
v-for重复渲染大量数据性能问题

### ISSUE THREAD

**Issue by chenzhiguo** [vuejs/vue#3095]
你好，一直在用vue，目前遇到性能问题。重复渲染递增数据的时候。比如页面用for循环输出logList[],页面定时循环请求新的数据，量很大，次数很多，请求成功后，数据结果合并。每次都会执行
`demoVue.logList = demoVue.logList.concat(response.logList); `
这样，页面会全部重新渲染logList这个数组吧？
但是现在发现性能有问题，请问有什么好的优化方法吗？

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

This may be handy https://github.com/vue-comps/vue-clusterize

**Comment by iamsee** [comment]
socket 在推送信息做列表动画效果时候也会出现一定量后就卡主，不知道怎么解决
