### ISSUE TITLE
use v-data- prefix for special attributes like key, transition and ref

### ISSUE THREAD

**Issue by prog-rajkamal** [vuejs/vue#3099]
When scanning a vue template, I find vue specific attributes are easier to scan and identify as they *usually* follow `v-` prefix. It has always irked me that `transition` is used in place of `v-transition`, but I was able to memorize it as it was only a single exception. 

But now that there are 3 special attributes, I believe it will be better to have a special prefix for them.  

I know from the the long discussions on binding syntax *which surpassed multiple issues* that  `v-` prefix will not be used for them. 

So I propose using a prefix `v-data-` for those attributes. If it looks too long, then we can use shorthand `$` for `v-data`

Example snippet 

```html
 <!-- before -->
<comp ref="foo"></comp>
<comp v-for=" item in items" key="item.id" class="app-list__open prime" transition="anim" v-bind> 
 //
</comp>

<!-- after -->
<comp v-data-ref="foo"></comp>

<comp v-for=" item in items" $key="item.id" class="app-list__open prime" $transition="anim" > 
 //
</comp>
```

**Comment by yyx990803** [comment]
I don't really see any practical disadvantage of using non-prefixed special attributes. If you really want to keep Vue related attributes different, you can always use `v-bind:ref="'foo'"`.

**Comment by prog-rajkamal** [comment]
@yyx990803 

In my experience, I have found only 3 disadvantages  of non-prefixed attributes:

 - Scanning vue templates
 As we have known, a code is written once but read many times. With special prefix, vue specific attributes will stand out and be easier to identify, especially when other vue specific attributes *do* start with `v-`. It really irks me when i scan a vue template and got to remember that `transition` attribute is a vue attribute.

 - Adding more vue specific atrributes in future.
 It is very likely that many of vue's attributes, in future, may likely take a string value instead of js expression. Or there are cases where we will require to add another special attribute. Naming things are hard, especially when you are using global namespace. 

 By using prefix, we make it easier to add more vue-specific attributes.

 - Beginner pitfalls
 A beginner will not definitely fall on it just like they write `a = b` in stead of  `a==b`. if it was just one special attribute (transition), i would go for simplicity, But with 3 attributes(and more may come), i find it better to have a prefix.


PS: `v-bind:ref="'foo'"` is clearly a hack, but will work for now.

**Comment by yyx990803** [comment]
The "many more to come" is not really true, I do want to limit the number of special attributes and currently don't have plans for adding anymore. `key`, `ref` and `transition` are the only ones there are and they all serve very clear purposes. Remember that you are already using custom elements.

I'll make it clear that I do not plan to change how they currently work.

**Comment by prog-rajkamal** [comment]
>I do want to limit the number of special attributes and currently don't have plans for adding anymore.  

I really commend your effort and foresight. But we are software developers, not fortune tellers. We never know what edge cases we have overlooked. 

Maybe I am reading too much into this, but I think your reluctance, to add more special attributes, is a direct consequence of having no vue specifc prefix. If prefixes were there, then adding a new one is easy. but without them, we have to consider polluting global scope, interference with already existing html/svg  attributes and increasing their numbers. 

For now, I have to concede that you are more experienced and, hence, know better than me. But vue 2 is still alpha, if situation occurs where a new special attribute is required, please consider adding a prefix instead.
