### ISSUE TITLE
"vm.dataProp = {}"行为有点奇怪

### ISSUE THREAD

**Issue by smadey** [vuejs/vue#3100]
### Vue.js version
1.0.25

### Reproduction Link
[demo](http://jsbin.com/gipefisalu/1/edit?html,js,output)

### Steps to reproduce
Press the "reset" button

### What is Expected?
alert '' and ''

### What is actually happening?
alert '' and 'test'

**Comment by banama** [comment]
你把 `:value.sync="filter.test"` 改为 `:value="filter.test" ` 结果应该就符合你的预期了。

之所以会有这个区别是因为，双向绑定了`props`， 在你更新子组件的 props 值时，会执行该指令的 `parentWatch.set` 方法。 

filter 被重新赋值大概在下面的地方
https://github.com/vuejs/vue/blob/dev/src/directives/internal/prop.js#L50
https://github.com/vuejs/vue/blob/dev/src/parsers/expression.js#L176

**Comment by yyx990803** [comment]
如上所述
