### ISSUE TITLE
Is there anyway slot can support v-bind:name ?

### ISSUE THREAD

**Issue by Thyiad** [vuejs/vue#3103]
Like title, slot does not work in v-bind:name, is there anyway can do this ?

```html
<div v-for="tab in tabs" class="tab-pane fade" :id="tab.id">
       <slot :name="‘tabBasic’"></slot>    // if use v-bind, can not work, is there anyway can do this ?
</div>
```

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by Thyiad** [comment]
Thank you
