### ISSUE TITLE
v-el specified dom can not be referred by owner component's $vm.$els??

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3105]
Hi, according to vuejs documentation, v-el give a great way to refer to the dom if we use v-el:someid.
But that only works on the root $vm, it does not be available at parent component's $vm instance?
the code is:
```
<comp>
    <div class="slot" v-el:couldnotavailabeinComp>this is the slot content</div>
</comp>
```
above code, the root $vm can access the slot which is wrapped by comp component via $vm.$els.couldnotavialbleinComp, but in the comp vm instance, it can not be accessed.
Is it  a bug or something wrong i did?

**Comment by yyx990803** [comment]
You must use all lowercase for the id because HTML is case-insensitive.

**Comment by cnweibo** [comment]
@yyx990803 , the point you mention is not the root cause of this issue.
Please help me out:
1. whether or not in above scenario, only the root vm instance can refer to the 'couldnotavailabeincomp' DIV elemenet?  That is to say, we can not access it in comp's $vm.$els ?
I verify above test by using vuedev tool in chrome.
2. If that is true, can you update the document : http://vuejs.org/api/#v-el , it really costs me several hours to figure it out

thanks~!

**Comment by cnweibo** [comment]
@yyx990803 , also please note that : the dom element i attached with v-el:couldnotavailabeincomp is in NOT in the comp's template, it IS in the transcluded content, does that matter?
thanks~!
