### ISSUE TITLE
How to dynamically create a Modal or Notification?

### ISSUE THREAD

**Issue by fundon** [vuejs/vue#3107]
I use wepack + vue-loader to development my project.

Sometimes we want to create a modal by the button, the modal must be inserted to body, and we have the `Modal.vue` component.

So is there the best practice to solution it?

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, put `v-if="modalShown"` on the modal element in the template, and toggle `this.modalShown` from the code.

**Comment by fundon** [comment]
@simplesmiler Thanks.

The `v-if="modalShown"` is not a good answer. 

I want to  dynamically create a Modal and the Modal instance will be inserted to **document.body**.

**Comment by simplesmiler** [comment]
https://github.com/rhyzx/vue-transfer-dom

**Comment by fundon** [comment]
@simplesmiler Thanks for your share.

The `vue-transfer-dom` has some problems:

1. Should define a component template in the app.

2. Will clone the dom and append to body.

They are not good for me.

Thanks again! :)

**Comment by jonagoldman** [comment]
https://forum.vuejs.org
https://gitter.im/vuejs/vue

**Comment by fundon** [comment]
@simplesmiler @jonagoldman OK. 

Done. see http://forum.vuejs.org/topic/4362/how-to-dynamically-create-a-modal-or-notification/2.

**Comment by simplesmiler** [comment]
@fundon 
> will clone the dom and append to body

This is exactly what `vue-transfer-dom` does **not** do, because if you do that, you lose reactive bindings and experience a few other issues.

I will follow up in the forum.
