### ISSUE TITLE
Transition freezing browser

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#3108]
### Vue.js version
1.0.25

### Steps to reproduce
Install vue-js 1.0.25
Install vue-router 0.7.13

Create a main App component with the router-view.  Create a transition, ( I used a fade one with 0 opacity ), set the transition-mode to out-in ( does not happen on in-out ).  Create 2 new components and switch between them both.

### What is Expected?
Fade of component in and out

### What is actually happening?
I started to notice this when I upgraded to 1.0.25 yesterday.  All of a sudden, when I would click to my different views in my SPA, the chrome tab would just freeze.  After much deliberation, I determined that it is the transition-mode="out-in".  If I remove transitions, or change to in-out, it would completely stop.  Using the hackernews vue-router example, I set my vue-js version to theirs, and it all of a sudden worked again (with transition-mode="out-in").  I slowly upgraded my vue-js version, checking everything from 1.0.8 to 1.0.25.  Every version worked until I got to 1.0.25.

One thing that I noticed was, it would go from an immediate freeze, to intermittent, if I removed the v-model from my <select> tag.

**Comment by repsac-by** [comment]
repo:  https://jsfiddle.net/3jp7vy4L/3/
fixed:  #3104

**Comment by volodymyrrudyi** [comment]
The issue is still present in 1.0.26

**Comment by repsac-by** [comment]
@volodymyrrudyi  мой пример с использованием 1.0.26 показывает, что вопрос решен.
https://jsfiddle.net/zhzoqwpc/1/
