### ISSUE TITLE
:style not work by using SASS and npm run build.

### ISSUE THREAD

**Issue by VinceXie** [vuejs/vue#3109]
Vue version:1.0.20
Chinese post:http://forum.vuejs.org/topic/4366/style%E5%9C%A8%E4%BD%BF%E7%94%A8sass%E5%90%8Enpm-run-build%E5%B0%B1%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%E4%BA%86

```
<input
    type="text"
    title="input date"
    :style="inputStyle"
    readonly/>

inputStyle: {
            'display': 'inline-block',
            'padding': '0px',
            'line-height': '0px',
            'font-size': '14px',
            'border': '0px solid #fff',
            'box-shadow': '0 0px 0px',
            'border-radius': '0px',
            'color': '#808080',
            'text-align': 'right'
          }
```
when i use \<style\> in vue component, it work both "npm run dev" and "npm run build".  but when i use \<style lang='scss'\> in vue component, it only work in  "npm run dev" . There are nothing style for the input element in "npm run build" .
please help me. 
thank you.

**Comment by yyx990803** [comment]
Please post the issue to the corresponding vue-cli template repo. Also make sure you've installed `node-sass`.
