### ISSUE TITLE
Should v-show warn when used on template tag?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3110]
I just noticed it doesn't while revising some docs. I'm not sure if it's worth throwing a warning for.

**Comment by yyx990803** [comment]
Theoretically any directive that is not `v-if` or `v-for` will be ignored on `<template>`, not sure if `v-show` is worth a special case here.

**Comment by chrisvfritz** [comment]
If it's not a common issue for people, then I don't think we need to.
