### ISSUE TITLE
export defalut function can't work

### ISSUE THREAD

**Issue by santinoDu** [vuejs/vue#3111]
In a component , I have a function named foo,  `export default foo`,
In another component I use this component after import foo, like foo(),  then it's get an error.
Console warnnings  Cannot read property 'el' of undefined
`/**
 * Create a record for a hot module, which keeps track of its construcotr,
 * instnaces and views (component directives or router-views).
 *
 * @param {String} id
 * @param {Object} options
 */

exports.createRecord = function (id, options) {
  if (typeof options === 'function') {
    options = options.options
  }
  if (typeof options.el !== 'string' && typeof options.data !== 'object') {
    makeOptionsHot(id, options)
    map[id] = {
      Component: null,
      views: [],
      instances: []
    }
  }
}`

If it support options as a function, why still get options.el or options.data,
if it doesn't support function, why have the first if?

**Comment by yyx990803** [comment]
You can only export Component constructors returned by Vue.extend, not any functions.
