### ISSUE TITLE
Value of textarea is not sync back to model

### ISSUE THREAD

**Issue by michaelliao** [vuejs/vue#312]
Hi

If I bind model with a textarea, it works fine only if the content of textarea was modified by JavaScript:

```
$('#text-content').get(0).setRangeText('hi');
```

The model does not change after insert some text by JavaScript.

Here is an example:

http://jsfiddle.net/y6tfL/

Thanks!

**Comment by BelinChung** [comment]
@yyx990803 这个问题在 0.11 里面解决了？ `$sync` 方法？

**Comment by meirlamdan** [comment]
[Here](https://github.com/vuejs/vue/issues/2804#issuecomment-344386912) is the correct answer
You will need to add

`elem.dispatchEvent(new Event('input')) `
