### ISSUE TITLE
pass adapted data from parent component to child component

### ISSUE THREAD

**Issue by hughgr** [vuejs/vue#3132]
Hi @yyx990803 

I've been playing with vuejs for serval time, so I have a few question to discuess

Due to the single data flow design philosophy, is directly passing reference data to child component through props a good practice? if I do so,everything become easy ,but the child component have to manage the parent data/state

second, is there any way to adapt data from parent component to child component?
for example 

I got child component has a prop named "info", and it requires data like {"name": "test","age":23,"class":1}
but the parent component have to pass data like {"singleName":"test","singleAge",23,"class":1}

computed property does NOT work on reference object , is there an elegant way to manage that.(I don't want to use custom event or deconstruct the data to three prop name, age ,class )

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

As for your question. Passing data to a child through props is the way to go. To modify them from child components either use two way bindings or emit events from child component and catch them on parent:

```html
<child @someevent="doStuff"></child>
```

On child:
```html
<button @click="$emit('someevent')"></button>
```

A computed prop should work. Better post a repro on the forums or gitter

**Comment by hughgr** [comment]
@posva maybe I didn't make myself clear.but thanks anyway 

by the way.I tried several times but I didn't receive the confirm email from the [forums](http://forum.vuejs.org/), and I also searched the trash email(I'm using gmail)

would it bother you if check the server log and see what's going on 

thanks

**Comment by simplesmiler** [comment]
@hughgr you need to make your github email public in the settings, and then auth again.
