### ISSUE TITLE
Multiple vue instance bug

### ISSUE THREAD

**Issue by douzi8** [vuejs/vue#3133]
### Vue.js version
 Vue.js v2.0.0-alpha.5

### Reproduction Link
https://jsbin.com/xedizivigi/edit?html,js,console,output

### Steps to reproduce
First read  'bar.car.log', then assign  bar.car.log = 'baoma'

### What is Expected?
foo object will not update

### What is actually happening?
foo object  will also be updated

**Comment by pespantelis** [comment]
Hi @douzi8,

I have checked your bin and the `foo` object remains the same as expected.

**Comment by simplesmiler** [comment]
Interesting, looks like a bug to me.

**Comment by ealves-pt** [comment]
It's working as expected for me, `bar.car.log` gets a new value assigned and `foo.car.log` is not changed.

**Comment by simplesmiler** [comment]
@ealves-pt but `update` is still called for `foo`, which should not be happening.

**Comment by ealves-pt** [comment]
@simplesmiler hmmm indeed didn't noticed that. Interesting...
