### ISSUE TITLE
多个同名 vue 文件（不同路径）同时在页面中引用时 hot reload 将产生错误

### ISSUE THREAD

**Issue by dawnwish** [vuejs/vue#3138]
英文不佳，实在抱歉！用中文描述会更准确些。

### Vue.js version
1.0.25

### Reproduction Link
https://github.com/dawnwish/vue-hot-reload-bug

### What is happening?
若在页面中引入两个同名的 vue 组件（路径不同），例如：
   `require('./components/footer/index.vue');`
   `require('./components/header/index.vue');`
然后通过 webpack-hot-middleware 和 webpack-dev-middleware 配置 hot reload

修改其中某个组件，如 footer/index.vue，页面会进行 hot reload，正常情况下修改的那个组件将被重新加载

然而实际情况是，页面中的两个组件都会被重新加载为 footer/index.vue（即原来的 header 也会被加载为 footer）

我尝试修改其中的某个文件名为 index1.vue，hot reload 功能就可以正常使用，原因可能是出在对同名文件的处理上。

**Comment by yyx990803** [comment]
Fixed in `vue-loader@8.5.3`.

以后此类问题请到对应的 repo 开 issue。

**Comment by dawnwish** [comment]
好的，多谢尤大大！
