### ISSUE TITLE
[Vue 2.0] text input with number modifier displays NaN value

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#3140]
### Vue.js version
2.0.0-alpha.5, 2.0.0-alpha.6 (haven't checked previous releases)

### Reproduction Link
https://jsfiddle.net/9mt1fjrg/

### Steps to reproduce

Type any letter into input field.

### What is Expected?

Shouldn't display NaN value.

**Comment by kazupon** [comment]
looks like a bug to me.
