### ISSUE TITLE
When the page in a component of the watch throw error, the whole Vue hung up

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/vue#3142]
When the page in a component of the watch throw error, the whole Vue hung up
```js
new Vue({
  el: '#app',
  data: {
    text: 1
  },
  methods: {
  	add: function() {
    	this.text++ 
    },
    undf: function() {
    	var obj = {}
    	this.text = obj.value
    }
  },
  watch: {
  	text: function(newVal) {
    	// Once reported here, Vue will hang up.
    	if(newVal.toFixed(3)) {
      	console.log('changed')
      }
    }
  }
})
```
this is reproduce the scene:

https://jsfiddle.net/chaoren1641/xognutk1/4/

**Comment by yyx990803** [comment]
This is not a bug, you have an uncaught error in user logic...

**Comment by yyx990803** [comment]
Added the ability to use `config.errorHandler` to handle the error instead of throwing.

**Comment by chaoren1641** [comment]
You're so efficient, so great.
Novices usually do not handle such errors in any place, such as when the data returned by the server is abnormal, this time the entire page of the Vue components will lose their jobs, I have encountered two such examples. Can throw a warning or frame level to avoid it is the best of course!

thanks :)
