### ISSUE TITLE
v-show/v-if doesn't work when property name starts with underscore?

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#3145]
### Vue.js version
1.0.25

### Reproduction Link
https://jsfiddle.net/sgp4haLb/1/

### Steps to reproduce
Click on the toggle button to show elements.

### What is Expected?
v-show/v-if should work regardless of whether property starts with underscore or not ?? I can't find any mention in the docs about prohibition of use variables with underscore at the beginnin so I don't know if this behavior is actually a bug or a feature :D

### What is actually happening?
v-show/v-if ignores properties names that starts with underscore.

**Comment by yyx990803** [comment]
Root level properties that start with underscores are reserved for Vue's internal prototype methods.
