### ISSUE TITLE
How to watch a global variable and update

### ISSUE THREAD

**Issue by jianyunli** [vuejs/vue#3146]
I have a graph and want to dynamically show the ID of the user selection node. The graphics are implemented in D3, based on user click, I set the window.currentNode = to user selected node.

Then I set the data of my Vue component as

```
data: function () {
return {
id: window.currentNode.ID
};
},
```

I can see the window.currentNode is changed, but the Vue component is not updated? Can someone point what I did wrong?

thanks much
John

**Comment by yyx990803** [comment]
Hi there, please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

---

For your question, please read the reactivity in depth section in the guide. `window.currentNode.ID` is not a reactive data source.
