### ISSUE TITLE
dynamic components a question

### ISSUE THREAD

**Issue by lawrence-peng** [vuejs/vue#3148]
### i have like this app :
```javascript
new Vue({
      el:'#app',
      data:{
         cartData:[],
          currentView:'home'
      },
     components:{
            order:order,
            orderDetail:orderDetail
            cart:cart
     }
});
var order = Vue.component('order',{
    props:[cartData],
    ...
});
var cart = Vue.component('user-cart',{
    props:[cartData],
    ...
});
var orderDetail = Vue.component('order-detail',{
    props:[cartData],
    ...
});

```
### in html file
`
<component :is="currentView" keep-alive transition="slide"></component>
`

so ,my question is how can i give a prop `cartData` into my components?
thank you~~

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
