### ISSUE TITLE
v1.0.25 v-model用在select上造成页面假死

### ISSUE THREAD

**Issue by lincenying** [vuejs/vue#3150]
系统, MAC
浏览器, chrome 51
bug描述,

当某个页面的v-model用在select上, 
直接打开这个页面, 不会有问题, 
但是从其他页面跳转到这个页面, 则出现浏览器假死崩溃...

**Comment by posva** [comment]
Hello!

Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by lincenying** [comment]
@posva 

http://jsfiddle.net/xyu276sa/672/

click 'Go to Bar'

**Comment by repsac-by** [comment]
#3104

**Comment by posva** [comment]
@lincenying I don't think the problem is related to the transition, it is ignored anyway. The issue is related to #3104 as @repsac-by said. The item is not yet inserted in the dom while the nextTick keeps calling the _forceUpdate

**Comment by posva** [comment]
Sorry, I wasn't focused enough. This bug has already been fixed and will be shipped in next version
