### ISSUE TITLE
How to add es6 classes logic in methods section?

### ISSUE THREAD

**Issue by 6pm** [vuejs/vue#3151]
In vue.js all methods united in methods: {...} section. It uneasily when we have more methods in one component. How to divide methods and implements in es6 classes, as in this example - https://jsfiddle.net/slavik_210/9a5waya2/

**Comment by fnlctrl** [comment]
1.ES6 Classes are unnecessary here.
2.If your goal is to divide methods, you can simply put them in a separate file
```javascript
import {foo, bar} from 'some-other-file'
...
methods: {
   foo,
   bar
}
```

**Comment by phanan** [comment]
Besides, please use forum and/or Gitter for such questions.

**Comment by 6pm** [comment]
phanan, thank you! I wrote this questions in gitter but bobody answer.
