### ISSUE TITLE
Cannot resolve module 'sass-loader' while set style lang as scss

### ISSUE THREAD

**Issue by xinshouke** [vuejs/vue#3152]
Cannot resolve module 'sass-loader' while set style lang as scss, I thought these are two different things.

**Comment by phanan** [comment]
If you're talking about vueify, there's no `lang="scss"`, but `lang="sass"`. You will need to install `node-sass` as well.

**Comment by chrisvfritz** [comment]
Yes, if you're going to use `scss`, you need to install `sass-loader`. Generally, you can solve `cannot find module 'x'` errors with `npm install --save(-dev) x`. 😃

**Comment by xinshouke** [comment]
@phanan I just set <style lang="scss"> in my vue file, but I get the same issue as iawia002 description in [https://github.com/vuejs-templates/webpack/issues/121](url)

**Comment by phanan** [comment]
`npm i --save-dev node-sass sass-loader`?
