### ISSUE TITLE
Uncaught error during transition:

### ISSUE THREAD

**Issue by lixinxiaobai** [vuejs/vue#3156]
### 1.0.21
I use the vue-router.
When using the back button, that is,``` history.back ()```
Would be such an error
```
[vue-router] Uncaught error during transition: 
```
The scene is this, for example, my URL is ```localhost:8080/message/id/10```
It's from ```locahost:8080/message/id/9```
URL will become``` localhost:8080/message/id/9``` when you click back

But the data on the ```localhost:8080/message/id/9``` page will not be rendered and will be reported to the above.

**Comment by yyx990803** [comment]
Please open the issue at vue-router's repo instead, also with a reproduction.

**Comment by stoneyong** [comment]
This problem is solved?

**Comment by fnlctrl** [comment]
It wasn't a problem since no repro was provided to confirm it.
