### ISSUE TITLE
Should init lifecycle hook be renamed to beforeCreate for consistency and increased clarity?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3158]
With the new lifecycle hooks, we have natural pairs with `beforeMount`/`mounted` and `beforeDestroy`/`destroyed`. `init` and `created` are the exception. The name `init` can also cause confusion, because nothing has actually been _initialized_ at that point in the lifecycle.

To resolve both of these issues, I'm thinking about renaming `init` to `beforeCreate`. Thoughts?

**Comment by yyx990803** [comment]
Implemented.
