### ISSUE TITLE
Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by BelinChung** [vuejs/vue#3159]
### Vue.js version
v1.0.25

### Steps to reproduce
jsfiddle: https://jsfiddle.net/Belinchung/20ey6q5j/5/

### Description

In my app I use `v-for` to render a list with `track-by` attribute and insert a duplicate value. 
Then an error occurred while trying to replace the array with new objects.

**Comment by phanan** [comment]
Duplicated `track-by` value is officially not supported, and will trigger an error in Vue. If you look at the console, there's this line:

`vue.js:1023 [Vue warn]: Duplicate value found in v-for="(index, user) in users": {"mid":"001","name":"aaaa"}. Use track-by="$index" if you are expecting duplicate values.`

Any subsequent behavior, therefore, is unpredictable and prone to problems.
