### ISSUE TITLE
Backbone + Vue

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue#316]
Is it possible to use Backbone models with Vue?

**Comment by boussou** [comment]
@yyx990803 This is truly awesome.
I'll try to make it work with collections too.
This is a relevant for people who has existing backbone apps & want to get rid of the BB view  part.

**Comment by boussou** [comment]
I made a test,  it works partially : http://jsfiddle.net/x1jeawzv/4/

then if you do this it works partially
```
list.add(new Backbone.Model({
        name: 'hello'
    }))
```
incomplete, I see there are a lot to do before it is complete: too much work ;-)
(sync the other way, update newly added models because the stuff created() must be performed on them, ..)
