### ISSUE TITLE
global variable without reactivity

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vue#3160]
sometimes, I need to define a global variable for data share between vue method. I always define this kind of variable in vue's property `data`. But according to my understanding, variable defined in `data` property is converted to reactive variable for UI render. 

In my scenario, the variable is just for data share, and is not related to the UI, so is there any other method by which I can define a global variable without reactivity in VUE.

for example: 
```
export default{
   data() {
      return {
         selectedItem: {}
      }
   },
   
mothods: {
     chooseItem(item) {
        this.selectedItem = item
     },
    
     deleteItem() {
        api.delete(this.selectedItem);
     }
   }
}
```

If `selectedItem` is never used to render the UI, where should I define `selectedItem`?

**Comment by LinusBorg** [comment]
Hello @njleonzhang 
Thank your for your interest in this project.

However, this is a usage question, and we encourage you to ask it on [forum ](http://forum.vuejs.org) or [gitter](http://gitter.im/vuejs/vue). The issue tracker is exculesively for bug reports and feature requests.
