### ISSUE TITLE
Referencing dynamically created components

### ISSUE THREAD

**Issue by iNDicat0r** [vuejs/vue#3161]
any idea how to reference dynamically created components?
the components are created based on a json tree object with each inner object having unique ids, i want a way to associate these ids with the components. Imagine a category can be within another category and so on.. i don't know the exact number therefore i need to reference each component by an id.. is this possible or any way to do ?

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
