### ISSUE TITLE
当值变化时候，触发transition

### ISSUE THREAD

**Issue by IamFive** [vuejs/vue#3162]
比如 ：

`<span v-text="someValue" transition="xx"></span>`

能不能做到触发动画呢。找了文档似乎没找到。

具体到应用。。就是想实现一个 数字变化的过程，像NBA比分那样，比方现在是 1:1, 过一会这个值变成
4:1 的时候，系统1->4有一个变化的过程

**Comment by mlyknown** [comment]
这种只有自己修改class吧。。。

**Comment by IamFive** [comment]
@mlyknown  这么晚了居然有人在。。 我重新更新了问题，你在看下。

**Comment by yyx990803** [comment]
1. 不要用 issue 问问题。

2. 1.x 不支持，但是可以用一个 `v-for` 模拟

 3. 2.0 可以用 `:key="someValue"` 来触发

**Comment by IamFive** [comment]
Sorry, 感觉算个issue，挺基础的功能，文档里没找到。下次发讨论组。

1.x  到 2.0 可以平稳升级吗，还是说有要注意的地方(帮忙连接下， google没搜到).

**Comment by fnlctrl** [comment]
github.com/vuejs/vue/issues/2873
