### ISSUE TITLE
Child Component not getting registered on a global component?

### ISSUE THREAD

**Issue by Milewski** [vuejs/vue#3164]
i dont know if i am missing something... but the following code is not working

```
let nav = Vue.extend({
            template: require('../templates/nav/nav.html'),
            components: {
                'item': { 
                      name:'item',
                      template: require('../templates/nav/item.html') 
                 }
            }
        });

Vue.component('nav', nav);
```

```
<nav>
    <item></item>
</nav>
```

it says..

```
app.js:1112 [Vue warn]: Unknown custom element: <item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Vue v1.0.24

**Comment by yyx990803** [comment]
`nav` is a native element. Do not use that as a component name.

**Comment by Milewski** [comment]
@yyx990803  im sorry... i had just simplified the name to post here in github.... but in all my components i am using compounded named in this case the one i am really using was:

```
<ark-nav>
      <ark-item></ark-item>
</ark-nav>
```

**Comment by yyx990803** [comment]
Then you should provide a jsfiddle reproduction.

**Comment by Milewski** [comment]
@yyx990803 here you are [https://jsfiddle.net/milewski/s3vcxkgm/1/](url)

**Comment by yyx990803** [comment]
`<ark-item>` should be registered alongside `<ark-nav>` because **they are used in the same scope.**

**Comment by Milewski** [comment]
doesn't it means i will end-up having two global components? and ark-item will be able to exist without ```<ark-nav>``` ?

according with the docs: [https://vuejs.org/guide/components.html#Local-Registration](https://vuejs.org/guide/components.html#Local-Registration)


```
var Child = Vue.extend({ /* ... */ })

var Parent = Vue.extend({
  template: '...',
  components: {
    // <my-component> will only be available in Parent's template
    'my-component': Child
  }
})
```

if i am to do
```
Vue.component('parent', Parent);
```

i would be able to do the same as my example isnt? but both examples isnt working...

**Comment by fnlctrl** [comment]
> Everything in the parent template is compiled in parent scope; everything in the child template is compiled in child scope.

```javascript
var Child = Vue.extend({ /* ... */ })

var Parent = Vue.extend({
  template: '...',
  components: {
    // <my-component> will only be available in Parent's template
    'my-component': Child
  }
})
```

The above will only work if `Child` is in `Parent`'s template
```
var Parent = Vue.extend({
  template: '<my-component>', // you can only use Child here.
  components: {
    'my-component': Child
  }
})
```

And in your use case, this is in `Parent`'s parent's template (Note that `Child` is not a child of `Parent` here)
```
<parent>
  <child></child>
</parent>
```

So inside `Parent`'s parent's template you need
```javascript
components: {Parent, Child}
```

**Comment by Milewski** [comment]
so it means externally if i am outside of the template i cant invoke the child.. it would need to be a global component for that and access the parent with this.$parent ?

for example this workflow would be impossible right?

```
<parent>
    <child></child>
</parent>

<another-parent>
     <child></child>
</another-parent>
```

in this example the ```<child>``` must to be a global component.. and the two child will be exactly the same not mattering who is the parent? if i want to differentiate them then i would go like this

```
<parent>
    <child-one></child-one>
</parent>

<another-parent>
     <child-two></child-two>
</another-parent>
```

so in this case i will have 4 global components... this is the only way? there is no way to shirnk it down to 2 global components ```<parent>``` and ```<another-parent>``` and have the ```<child>``` element as a child within the same name? 

```
<component>
    <child></child>
</component>

outputting..

<div class="im-component">
    <button>im child</button>
</div>
```
and

```
<another-component>
    <child></child>
</another-component>

outputting..

<div class="im-another-component">
    <div>
        <input>
    </div>
</div>

```

note: i am using the same name ```<child>``` on both places

**Comment by simplesmiler** [comment]
@Milewski you can try to use `inline-template`, but this won't let you specify templates for the components, and will prohibit the use of slots.
