### ISSUE TITLE
@change not work using vue with jquery and select2

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue#3165]
when I use select2 to pick up an item, variable 'a' will be changed ( see from the hidden input ), but method 'b' won't run.

```
<input type="text" v-select2="" v-model="a" @change="b">
<input type="hidden" v-model="a">

<script>
new Vue({
  data: {a: '1'},
  methods: {
    b: function(){
      console.log(1);
    }
  }
});
</script>
```

**Comment by masquevil** [comment]
https://jsfiddle.net/zuxxzu1v/

**Comment by yyx990803** [comment]
Many jQuery plugins including select2 only dispatch jQuery events, not native DOM events. `@change` only listens to native DOM events. You should just chain `.on('change')` on your select2 call.
