### ISSUE TITLE
[2.0][Bug] HTML5 Audio tag src disappeared

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#3166]
This bug is complex, I don't know how to describe， I have a project , it work well when use v2.0.0-alpha.6 , today, I update to alpha.7, then I found a strange problem, I try many times, I'm sure this bug is existence.

I know this not easy to reproduce, I will try to write a jsfiddle demo to show. 

Thanks!

**Comment by yyx990803** [comment]
Make sure you also re-install `vueify` or `vue-loader` if you are using them.

**Comment by aviggngyv** [comment]
sorry , maybe it's my mistake, but also so strange , I try to modify again, it already solved,   it like this:

Not work:

> <div class="max-lrc-text" v-if="show_lrc">
>     @{{ lrc_data[lrcBlockIndex][1] }}
> </div>


Work:

> <div class="max-lrc-text">
>     @{{ show_lrc ? lrc_data[lrcBlockIndex][1] : '' }}
> </div>
