### ISSUE TITLE
child component lifecycle not fired

### ISSUE THREAD

**Issue by Awakening-j** [vuejs/vue#3167]
```
export default {
		    name: 'a',
		    created() {
		        alert(1)
		    }
		  }
```
alert not fired when import this component to parent.

**Comment by LinusBorg** [comment]
Hello @Awakening-j 

thank you for your interest in this project.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.

Thank you.
