### ISSUE TITLE
Components that are registered locally have no $parent set.

### ISSUE THREAD

**Issue by LukasKnuth** [vuejs/vue#3169]
When I create a top-level component, which then registers one or multiple other components **locally**, and they have the `el`-property set, the local-components don't seem to have a `vm.$parent`-instance set.

I have created this small fiddle to demonstrate the problem: https://jsfiddle.net/r8q9wdvp/5/

As you can see, the `vm.$children`-count is `0` and the dispatched message is not being received.

Or am I missing something here?

**Comment by yyx990803** [comment]
Local component **should not** have the `el` option, you are using it wrong. Give it its own template instead.

**Comment by LukasKnuth** [comment]
Giving the local-component a template seems to add it correctly (child-count is now `1`), however, the content isn't rendered: https://jsfiddle.net/t1cmzw8d/ - Even if I also give the root-component a template.

BUT, if I take the same component and register it globally, it seems to work fine.

**Comment by ktsn** [comment]
@LukasKnuth You have to pass a component constructor instead of its instance to `components` option like following code.

```js
const RootMV = Vue.extend({
  // ...
  components: {
    "content": ContentMV
  }
  // ...
}
```

**Comment by LukasKnuth** [comment]
Well, now I feel stupid. Thanks @ktsn 

@yyx990803 I still feel that the documentation should explicitly state that `el` should not be used in local-components. I could send a pull-request to the vue.org repository.
