### ISSUE TITLE
Tab key doesn't work 

### ISSUE THREAD

**Issue by dalenguyen** [vuejs/vue#3170]
Hi, 

I'm using //cdnjs.cloudflare.com/ajax/libs/vue/1.0.25/vue.js, and I have problem with calling tab key event with keyup. 

It works with other keys such as up or down

```
@keyup.up = "functionName"
```

but not with the tab key. The code below doesn't call the event handler.

```
@keyup.tab = "functionName"
```

Please take a look at this one. 

Thanks,

**Comment by sleewoo** [comment]
try `@keydown.tab` and prevent default cause on keyup tab default event already took place

**Comment by dalenguyen** [comment]
Thank @sleewoo . Your method works!!! 

I have another relevant question. How about when user don't press the tab button, and they use the mouse to select some things else instead? How I can catch that event together with the tab key?

**Comment by YerkoPalma** [comment]
Your question should be in some QA site like [StackOverflow](http://stackoverflow.com/questions/tagged/vue.js) or the [Vue forum](http://forum.vuejs.org/), not as an issue. For what you are asking, I think that the `@focus` event is what you need

**Comment by dalenguyen** [comment]
@YerkoPalma you're right. It also works. Thanks for your help.
