### ISSUE TITLE
[Feature] Allow binding (via v-text) the content of a script tag

### ISSUE THREAD

**Issue by weotch** [vuejs/vue#3171]
To support [JSON-LD based microdata](https://developers.google.com/search/docs/data-types/breadcrumbs) it would be nice to be able to set the content of a script tag.  My use case is using Vue.js to render breadcrumb microdata.  

Here is an example of `v-text` not working with a `script` tag: http://codepen.io/weotch/pen/pbeVqg.  

Here is an example of JSON-LD from the Google docs for breadcrumbs microdata:

```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://example.com/books",
      "name": "Books",
      "image": "http://example.com/images/icon-book.png"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://example.com/books/authors",
      "name": "Authors",
      "image": "http://example.com/images/icon-author.png"
    }
  },{
    "@type": "ListItem",
    "position": 3,
    "item": {
      "@id": "https://example.com/books/authors/annleckie",
      "name": "Ann Leckie",
      "image": "http://example.com/images/author-leckie-ann.png"
    }
  },{
    "@type": "ListItem",
    "position": 4,
    "item": {
      "@id": "https://example.com/books/authors/ancillaryjustice",
      "name": "Ancillary Justice",
      "image": "http://example.com/images/cover-ancillary-justice.png"
    }
  }]
}
</script>
```

**Comment by yyx990803** [comment]
It already works, you just need to specify `type="application/ld+json"`. Vue filters out `<script>` without `type` attribute or `type="text/javascript"` for obvious reasons, but allows `<script>` with other types.

**Comment by weotch** [comment]
Thanks, [I see what you mean](http://codepen.io/weotch/pen/GqWaKe).  

FWIW, it doesn't seem to be parsing v-text, though, when [my template is a jade template](https://gist.github.com/weotch/ccdf05dde63373430461154112007a86) as part of a .vue file being compiled by vue-loader.  I haven't investigated yet where in the pipeline it's breaking down.

**Comment by Froxz** [comment]
@yyx990803 is not the case anymore in vue 3

```js
<script type="application/ld+json" v-html="jsonLD"></script>
```

`SyntaxError: Tags with side effect (<script> and <style>) are ignored in client component templates.`
