### ISSUE TITLE
Update vuejs model value by jquery trigger, but not take effect

### ISSUE THREAD

**Issue by sinbo520** [vuejs/vue#3173]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/qkcmcogk/8/

### Steps to reproduce

update the select dom value in jquery,but the v-model not take effect

**Comment by phanan** [comment]
jQuery event system != native browser event, so Vue doesn't know about the jElement's `trigger()`. I suggest you read https://learn.jquery.com/events/triggering-event-handlers/.

**Comment by phanan** [comment]
Also, if you get stuck, please ask on our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue). I'm sure a lot of folks there will help you.

**Comment by sinbo520** [comment]
tks ,solved， http://stackoverflow.com/questions/21290775/jquery-el-triggerchange-doesnt-fire-native-listeners
