### ISSUE TITLE
Vue cannot watch Object.assign?

### ISSUE THREAD

**Issue by Emiya0306** [vuejs/vue#3175]
Here is my [code](https://jsfiddle.net/esc228/sbn8g1Lt/2/). 

First question is Why only equal can emit Vue watch, but `Object.assign` not?

Second question is How to watch all the Object inner key? I can add a new key `this.commentsList.['2016-06-07']`, it will also emit Vue watch?

Thanks.

```html
<div id="editor">
  <div v-for="(date, comments) in commentsList">
    <div>
      {{date}}
    </div>
  </div>
</div>
```

```javascript
new Vue({
  el: '#editor',
  data: {
  	commentsList: {}
  },
  ready() {
  	const comments = {'2016-06-06': [
    	{title: 'title1', content: 'content1'},
    	{title: 'title2', content: 'content2'}
    ]}
  	
    //Object.assign(this.commentsList, {'2016-06-06': comments['2016-06-06']}); // cannot work
    
    this.commentsList = 
        Object.assign({} ,
            this.commentsList, 
            {'2016-06-06': comments['2016-06-06']}); // can work
  }
})
```

**Comment by crossjs** [comment]
http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats

**Comment by phanan** [comment]
What @crossjs said. For deep watch, use `deep` option. Please read the manual. Also, our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) should be better fits for questions like this.
