### ISSUE TITLE
Vue.js v2.0.0-alpha.8 bug

### ISSUE THREAD

**Issue by douzi8** [vuejs/vue#3176]
### Vue.js version
Vue.js v2.0.0-alpha.8

### Reproduction Link

https://jsbin.com/mayoqebeha/edit?html,js,console

### Steps to reproduce
1. define empty arr
2. define an element after `v-for` element, can not leave a blank space
3. then assign arr data

**Comment by simplesmiler** [comment]
Hi, thanks for reporting the issue!

It looks like a template parsing bug. I'll give it a go this evening if no one will beat me to it.

Improved repro: https://jsbin.com/biqixinuzu/1/edit?html,js,output

**Comment by simplesmiler** [comment]
Welp :grin:
