### ISSUE TITLE
Props validation fails (Vue warn) when component initialized with proper propsData

### ISSUE THREAD

**Issue by iagafonov** [vuejs/vue#3183]
I made a universal component (modal) that can be used as inline component
`<modal :entity="some">`
or via service
`this.$modal.open({propsData: {...}, component: ModalForm})`
it works fine, but warns about invalid props, because it runs in `compileProps` step, and propsData will be used later in `makePropsLinkFn` step (compile-props.js).
I think propsData should also be a source of validation along with element attributes

version 1.0.26 [jsFilddle](https://jsfiddle.net/oe7axeab/1296/) (see console)
version 2.0.0-alpha.8 does not have this problem

**Comment by kazupon** [comment]
Close (Fixed in #3193)
