### ISSUE TITLE
Vue 2.0 webpack hot reload

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#3185]
### Vue.js version
2.0.0-alpha.8

### Reproduction Link

https://github.com/johnleider/vue-materialize

### Steps to reproduce
clone repo, npm install, npm run dev.  Updating any component will trigger the webpack hot reload but it will not update the component.  If you click to another view and back, it will be updated.  

### What is Expected?
Hot reload of component

### What is actually happening?
Web pack push is happening, components do not update live, require manual reload

### Extra
I was originally using the template provided @ https://github.com/vuejs-templates/webpack-simple-2.0 which for a time was working.  The original vue version was alpha.2 but now npm auto downloads alpha.8.  Not sure if this would have anything to do with it.

**Comment by yyx990803** [comment]
Thanks, this is a bug in `vue-hot-reload-api` and is now fixed. If you re-install vue-loader it should work properly.

**Comment by johnleider** [comment]
works perfect, ty.

**Comment by dcastillom** [comment]
Hot reload is not working for me :(
{
  "name": "modules",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "build": "webpack-dev-server --hot --inline"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.17.3",
    "vue": "^2.1.7",
    "vueify-insert-css": "^1.0.0",
    "webpack": "^2.2.0-rc.3"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2015-native-modules": "^6.9.4",
    "css-loader": "^0.26.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.4.0",
    "vue-hot-reload-api": "^1.3.3",
    "vue-loader": "^9.9.5",
    "vue-template-compiler": "^2.1.7",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-server": "^1.16.2"
  }
}
Could you tell me what is my problem here? Thanks!
