### ISSUE TITLE
props.sync will be invalid when do this

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3188]
```
<parent>
  <child :prop.sync="mProp"></child>
</parent>
```
_in parent data,i don't defined **mProp**_
if i run "**this.mProp='xxxx'**" in parent before run "**this.prop='xxxx'**" in child,the sync will be invalid
why?
懂中文的还是用中文回我吧==

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:

As for the question, you need to define it on parent
