### ISSUE TITLE
input value changes by JQ code ,v-model variable don't changes ?

### ISSUE THREAD

**Issue by MonKong** [vuejs/vue#3194]
HTML
```
<div id="vue">
  <input type="text" id="input" v-model="value"/> <br>
  Vue-model: {{value}} <br><br>
  <i>input value changed, but model value didn't changed?</i> <br>
  <i>can model value auto updated by other JS code that change input value?</i>
</div>
```

JS
```
new Vue({
	data:{"value":"one"},
  el:"#vue"
})

setTimeout(function(){
	$("#input").val("two")
 },1000)
```

here is run code: [https://jsfiddle.net/monkong/xmdpksa5/9/](https://jsfiddle.net/monkong/xmdpksa5/9/)

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your interest in this project.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by LinusBorg** [comment]
This is the second time today. Please - use the forum or gitter.
