### ISSUE TITLE
:item as shorthand for :item="item"

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3196]
There are many times when it's using to do something like `:item="item"`. Would it be useful and feasible to have `:item` be a shorthand for that?

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/pull/2877

**Comment by chrisvfritz** [comment]
Thanks! I figured that someone must have brought this up before, but couldn't find it. 😃

**Comment by zhangenming** [comment]
how about `:shorthand = '{item}'`
