### ISSUE TITLE
SVG `image` tag is incorrectly converted to `img` unless inside `<svg>`

### ISSUE THREAD

**Issue by whitelynx** [vuejs/vue#3197]
### Vue.js version

1.0.26
### Reproduction Link

http://codepen.io/whitelynx/pen/PzmbEo
### Steps to reproduce

Use multiple components to define an SVG drawing, and include an `<image></image>` element in one of the components which does _not_ include an `<svg>` tag.
### What is Expected?

The image should correctly draw.
### What is actually happening?

The image does not appear. It seems that Vue is replacing the `<image>` element with an unclosed `<img>` element that has the same attributes. This happens even if the `<image>` element is inside a recognized SVG tag (e.g., `<g>`) in the template; the only situation where it does not happen is if it's inside an `<svg>` element.

In environments which use `vue.common.js` (in my case, [Electron](http://electron.atom.io/)), this causes further issues: Since `<img>` is not a valid SVG element, the DOM will auto-close the containing SVG tags before opening the `<img>`, which can also cause `stringToFragment()` to fail with `Uncaught TypeError: Cannot read property 'tagName' of null`. (since `node.lastChild` will no longer be the `<svg>` element defined by `prefix` and `suffix`, but instead a text node containing the trailing whitespace from the template)

---

There is a workaround: wrapping the `<image>` element directly with an `<svg>` element wherever it appears. However, it's unexpected that this would be required, and it forces some odd contortions compared to just using an unwrapped `<image>` tag. (e.g., the `x` and `y` attributes need to appear on the `<svg>` tag instead of the `<image>` tag, and the `width` and `height` attributes need to appear on _both_)

**Comment by kazupon** [comment]
> Uncaught TypeError: Cannot read property 'tagName' of null

This issue is fixed already in #3212, so I think that dont' need to fix in this issue.

>  However, it's unexpected that this would be required, and it forces some odd contortions compared to just using an unwrapped <image> tag. 

I do not think so about this. because this <image> tag is required the svg namescpace in `template` tag.
See the below URL.

- Namespaces Crash Course
https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

**Comment by yyx990803** [comment]
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.
