### ISSUE TITLE
use v-model for textarea and use {{value}} , browser ben collapse

### ISSUE THREAD

**Issue by taoche** [vuejs/vue#3199]
### Vue.js version
1.0.26

### Steps to reproduce
https://hyperdev.com/#!/join/d6611fee-1d30-4353-87e6-16a00fd3dd0f

I know this syntax is wrong...  but input tag not have this problem..
write this to document or resolve browser crash ?

**Comment by posva** [comment]
Input tags are self closing, so yeah...
I think it's worth mentioning in the guide a tiny example about a textarea. I couldn't find one
