### ISSUE TITLE
binding expressions with non-ascii literals not wrok in IE 11 input textbox

### ISSUE THREAD

**Issue by yidazh** [vuejs/vue#3200]
### Vue.js version
1.0.23

### Reproduction Link

[https://jsfiddle.net/4Lykzdwj/](https://jsfiddle.net/4Lykzdwj/)
### Steps to reproduce
Run JSFiddle

### What is Expected?
Binding expressions produce results as JavaScript expressions work.

### What is actually happening?
Expressions not executed.

In chrome and firefox, problems do not exist.

**Comment by kazupon** [comment]
Hi!
Sorry, for late reply.

I think that this issue is Internet Explorer.

The below minimum reproduction code.
(This code is DOM API only, not use Vue.)
http://jsfiddle.net/kazupon/aak3vvpy/

This issue can avoid by using `v-bind` ( `:value`)
https://jsfiddle.net/wkcjoya5/1/

**Comment by kazupon** [comment]
Close (5 days inactivity)
