### ISSUE TITLE
关于v-for的无法渲染问题

### ISSUE THREAD

**Issue by yubang** [vuejs/vue#3201]
在调用$set方法的时候，数组里面如果是相同数字就会无法渲染。
下面是出问题的代码demo，id="test1"里面是无法渲染， id="test2"可以正常渲染

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>VUE.js</title>
    </head>
    <body>
        <div id="test1">
            <p v-for="obj in objs">{{obj}}</p>
        </div>
        <div id="test2">
            <p v-for="obj in objs">{{obj}}</p>
        </div>
        <script src="//cdn.bootcss.com/vue/1.0.24/vue.min.js"></script>
        <script>

            new Vue({
                el: "#test2",
                data: {
                    objs: []
                },
                ready: function(){
                    this.$set("objs", [1, 2, 3]);
                }
            });
            
            new Vue({
                el: "#test1",
                data: {
                    objs: []
                },
                ready: function(){
                    this.$set("objs", [1, 1, 1]);
                }
            });
        </script>
    </body>
</html>
```

**Comment by fnlctrl** [comment]
不是bug，如果你想要渲染重复值的话 用$track-by
http://cn.vuejs.org/guide/list.html#track-by

**Comment by yyx990803** [comment]
渲染重复的 primitive value 需要 `track-by="$index"`

2.0 里面 `track-by="$index"` 是默认行为就不需要了

**Comment by yubang** [comment]
明白了，多谢了 @fnlctrl @yyx990803

**Comment by agileago** [comment]
@yyx990803  尤大  遇到同样的问题，就不开新的issue了
要做一个榜单列表，榜单里面的数据可能会有重复，因为是分页的，也许取第二页的时候数据库里面已经加了好多数据，返回结果中很可能和第一页的数据有冲突，所以要去重，使用`track-by="id"`

发现如果一开始数组是个空数组，然后异步获取数据concat进去，v-for是不会渲染的，但假如说一开始的数据有长度，那么后续的渲染完全符合预期 **既能做到去重，渲染也ok**  我觉得既然这样的话，空数组也应该渲染正常的，不太明白为什么停止渲染, 做了一个在线demo，把我遇到的一些问题都列了出来

[DEMO](http://codepen.io/agileago/pen/PzJJdx?editors=1010)

另外提个建议， 列表获取到的数据很可能会有重复数据，这时候去重可以是自己建个id索引，来规避重复数据，另外有没有可能在`track-by`上加个修饰符 `track-by.distinct` 来明确指出我要vue来帮我去重数据，毕竟vue里面应该自己也会建立索引

**Comment by yyx990803** [comment]
track-by 不是去重的意思，用了 track-by 正是限制了不能有重复 id。去重要你自己去做。

**Comment by agileago** [comment]
这么快就回复了，👍

但针对初始化数组有数据这种情况，后续渲染完全符合预期，是vue实现去重一个hack么？

**Comment by yyx990803** [comment]
@agileago 某些情况下能工作，但并不保证所有情况都可以。track-by 预设了每个 id 都是唯一的。

**Comment by display-b** [comment]
v-for出现了undefined 请问是什么情况？
<div v-for="n in rank" v-on:click="calRank(n)" class="cmt-box-inner-main-row-item disheart"></div>
<div v-for="item in 10">{{item}}</div>
export default {
        name: 'CommentBox',
        props: [],
        data () {
            return {
                rank: 5,
                ranked: 0,
                cmtCnt: ''
            }
        }
}
