### ISSUE TITLE
component's props change can't update dom

### ISSUE THREAD

**Issue by dawnwish** [vuejs/vue#3203]
hello!
### Vue.js version
1.0.23

### Reproduction Link

https://jsfiddle.net/3zw9u5ym/10/
### Steps to reproduce
click the "reverse" buttons, component will reverse the props.
one of them will update dom, the other one won't
### What is Expected?
all of them will reverse the array and update dom automaticly.
### What is actually happening?
if I set the component's props with the vm's data, when I change the props inside component, dom will update automaticly.
but if I set the props with the vm's computed data, when I change the props inside component, dom won't update. I try to use $set and arr.splice, they don't work as before.

**Comment by yyx990803** [comment]
Computed properties are derived data - they will be re-created any time the source changes, so mutating them doesn't make sense. If the source value never changes, them it should not be computed; if it does change, the child should emit an event to let the parent mutate the source instead.

**Comment by dawnwish** [comment]
ok, thank you!
