### ISSUE TITLE
$refs in loops are not in sync - the sub components instances do not get updated

### ISSUE THREAD

**Issue by GianlucaGuarini** [vuejs/vue#3204]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/e2zfe3se/

### Steps to reproduce
Check the above example

### What is Expected?
The $ref object should be updated using the new sub components instances

### What is actually happening?
The $ref object caches the old components instances and all the references to the new DOM elements created get lost

**Comment by johnleider** [comment]
After some digging it happens during the unbuild process.  It is called with defer of undefined.  If the refs are unbound with deferred true, it stops that from happening.

**Comment by LinusBorg** [comment]
can you share the location of the problem in src?

**Comment by johnleider** [comment]
Sorry, not sure why I didn't before.  src/directives/internal/component.js, line 287 "child.$destroy(false, defer)".

**Comment by kazupon** [comment]
Close (Fixed in #3217)
