### ISSUE TITLE
[vue next] `with` keyword is invalid in `strict` mode.

### ISSUE THREAD

**Issue by terrykingcha** [vuejs/vue#3205]
When I compile the templates, then bundle them by rollupjs, it will throw a error `'with' in strict mode`.  How can I handle this?

**Comment by yyx990803** [comment]
You can set the `useStrict` option to false: https://github.com/rollup/rollup/wiki/JavaScript-API#usestrict

**Comment by terrykingcha** [comment]
Yes, I try, But still throw the error. The ES6 module is always in `strict mode`. And I think `rollup` is not very fit  for bundling the vue file, due to the `with` keyword.

**Comment by yyx990803** [comment]
Rollup should bundle the whole app in a single function scope, with `useStrict: false`, it should only throw an error if you are nesting that whole bundle under another function scope with `'use strict'`.

This has to do with your build setup, but typically this is what I would do in the final bundle:

``` js
// rollup bundle (non-strict)
(function () {
  'use strict'
  // other code...
}())
```

**Comment by eirikb** [comment]
I believe @terrykingcha is correct, ES6 modules are by default strict, so they can't contain code using the keyword `with`.
`useStrict` is for the bundler only, so it's possible to output a file without strict mode, 
but this error occures when running rollup itself.
As can be [seen here](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22with%22%7D%5D%7D).

**Comment by gongph** [comment]
The same question, what should I do? @eirikb

**Comment by eirikb** [comment]
@gongph The only real solution is to remove the dependency to `with` from Vue (might be gone, haven't checked in a while).  
If you need a hack right away then evaluating code run-time is a plausible but horrible workaround, I made a small library for fun, where I did this: https://github.com/eirikb/vuetwo/blob/master/plugin.js#L6-L8

**Comment by yyx990803** [comment]
FYI latest versions of `vue-loader` and `vueify` both generate render functions that don't use `with`.
