### ISSUE TITLE
monkberry.js like templating syntax

### ISSUE THREAD

**Issue by Pandahisham** [vuejs/vue#3207]
```
<ol>
  {% for todos %}
    <li>
      {% if complete %}
        <del>{{ text }}</del>
      {% else %}
        <em>{{ text }}</em>
      {% endif %}
    </li>
  {% endfor %}
</ol>
```

this looks better in my opinion , feel free to add your counter arguments

**Comment by yyx990803** [comment]
I'm sorry but it's not enough to justify a significant breaking syntax change just because it looks better (which is subjective)
