### ISSUE TITLE
Vue and Horizon

### ISSUE THREAD

**Issue by zoomclub** [vuejs/vue#3208]
Hi, I'm still checking Vue out at this point and was wondering if there was any plans for a Horizon module? I'm seeing a lot of interest in Horizon from other frameworks these days, for example:

https://medium.com/@roman01la/introducing-react-horizon-4c26f9ef628c#.xkfeps83i
https://github.com/lifegadget/ember-horizon

Vue without solid Horizon support does not work for me. I need an alternative to Vuex/Redux and a tight integration between Vue and Horizon would do it. Horizon is taking the world by storm, check it out:

https://rethinkdbweekly.curated.co

**Comment by yyx990803** [comment]
It's trivial to sync Vue with Horizon, there are even official Horizon examples using Vue: https://github.com/rethinkdb/horizon/tree/next/examples

Currently the team has no bandwidth for it. If it does not work for you, why don't you write a binding yourself?

**Comment by zoomclub** [comment]
Right and thanks, forgot about those "official Horizon examples" in the heat of the pace here. It might be a worthwhile idea to highlight how "trivial to sync" Vue actually is somewhere in plain sight.
