### ISSUE TITLE
The index of this.$children in v-for is incorrect

### ISSUE THREAD

**Issue by rwu823** [vuejs/vue#3209]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/dh9ypwq7/

### Steps to reproduce
Just open reproduction link

### What is Expected?
The first child's text content is "2", but should be "1"

### What is actually happening?
`v-for` makes `$children`'s index to first instead of non `v-for` `$children`

**Comment by yyx990803** [comment]
this.$children does not guarantee order, you should not rely on that.

**Comment by 6pm** [comment]
I had the same problem. And I add data-attribute with order and used filters render slots by nuber data-attribute.
