### ISSUE TITLE
Parsing object as a filter argument fails with spaces inside

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#3210]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/0o853fzd/

Take a look at example. You can see that when i try to pass object to the filter as an argument it doesn't work when there is some space in the string.

![Err](http://image.prntscr.com/image/8d9b80adc23744cf966a4f983b6d6c52.png)

Isn't supposed to PR #834 fix this issue? or is it forbidden to use spaces when passing obejct to the filter like this?

**Comment by yyx990803** [comment]
This is because the 1.x filter syntax uses space as the argument delimiter. If anyone wants to work on this, the relevant logic is here: https://github.com/vuejs/vue/blob/dev/src/parsers/directive.js#L20-L35

**Comment by defcc** [comment]
I am working on a simple expression parser to parse the filter syntax rather then the regex way。Is it an acceptable method ? If so I will make a pull request soon.

**Comment by yyx990803** [comment]
@defcc code size is also a concern here. We don't want to bloat the code for a relatively rare use case.

**Comment by defcc** [comment]
ok, got it. @yyx990803
