### ISSUE TITLE
vue slot event passed on all components

### ISSUE THREAD

**Issue by obonyojimmy** [vuejs/vue#3211]
i am facing a dilemma here :  i have a component which has a slot , the slot passes an event to the component which is the acted on by the component , however if i add 2 component and pass the custom event on an event lets say click event , 2 instances of the events are returned , which means the event is listened by the two components unlike by the component that its slot has passed , check code below : 

the main script that handles has both component (it will pass two instances of the event)
```
<notie-js>
 <button class="margin btn btn-success" @click.prevent="$broadcast('show::notie-js')" type="button">Success</button>
</notie-js>

<notie-js>
 <button class="margin btn btn-success" @click.prevent="$broadcast('show::notie-js')" type="button">Success</button>
</notie-js>
						
						
```

the component **notie-js**

```
<template>

<slot></slot>

</template>

<script>

var notie = require('notie');

module.exports = {
	
    props:{
		
		alert: {
		  type: Object,
		  default: function () {
			  return {
				alertType: 1 ,
				message: 'Success' ,
				time: 2
				
				
			  }
		  }
		  
		},
		
		
	},
	
    data: function () {
            return {
             
          }
        },
	created: function() {
	   
	   
	},
	ready: function(){
	   
	},
	methods : {
		
	   doNotification : function(){
		  
		  if(this.alert){
			  notie.alert(this.alert.alertType,this.alert.message,this.alert.time);
		   }

		 
		   
	   },
	   
	  
	  
	},
  events: { 
	  
     'show::notie-js': function () {
      console.log('notie-js event received');
     // this.doNotification();
    }
    
  },
 computed: {
    
  }

}
</script>
```

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by LinusBorg** [comment]
Thsi is not a bug. a `$broadcast` event is sent to all children, so ig you have two instances of `<notie>` as child components, both will react on this. (One of the reasons that `$broadcast`will be deprecated in 2.0 - these unintended behaviours make `$broadcast` rather useless.)
