### ISSUE TITLE
[Question] Vue2 data watch

### ISSUE THREAD

**Issue by kobezzza** [vuejs/vue#3215]
```js
Vue.component('foo', {
  props: {
    initValue: {
      default: 'Hello world!'
    }
  },
  data() {
    return {
      value: this.initValue
    };
  },
  watch: {
    initValue: {
      immediate: true,
      handler(value) {
        // Fires, all fine
        console.log('initValue');
      }
    },

    value: {
      immediate: true,
      handler(value) {
        // Not fires
        console.log('value');
      }
    }
  }
});
```

It is normal behavior?

**Comment by sqal** [comment]
Can't reproduce - https://jsfiddle.net/10eLvwyg/1/

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.

Thank you.

**Comment by kobezzza** [comment]
Oh, after update to alpha.8 everything worked as it should :)
