### ISSUE TITLE
Correct way to reference a inserted child component?

### ISSUE THREAD

**Issue by li3p** [vuejs/vue#3216]
I am writing a example like the [official Tree example ](https://vuejs.org/examples/tree-view.html).

But I extend it to add a 'adding a sibling node' feature, My code is on [jsfiddle](https://jsfiddle.net/li3p/5o4awfn8/12/).

Expected:
 1. by clicking "[+sib]" after some node , I can insert a sibling node just below it.
 2. after then I wanna change the `.mode` attribute of the newly added node to some other values, so I need get the reference of the newly added `item` component.

I got:
After new sibling node added, but using the same offset in `$parent.$children` cannot find the correct node which newly added. Instead by using console.log and vue-dev-tools  I found :
 1. In the same tick , `$parent.$children` cannot found the newly added node.
 2. In the Vue dev tools, I found the index of the newly added node always be the last element in the `$parent.$children` .

Since I really need it to do some extra work after creation, I am wondering which is the correct way to get the reference of the newly created element by index ? I mean the `$index` in the order of the view that can been seen by eyes.

Thanks in advance

**Comment by LinusBorg** [comment]
Hello @li3p ie3p

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by li3p** [comment]
Thank you for replying. But currently the forum only allow github account as Oauth , after login into it , I cannot get the confirm email , so I cannot post to forum.

**Comment by LinusBorg** [comment]
Sorry to hear that, I assume you checked your spam folder?

We had to disable all other modes of registering because we had massive problems with spam bots, unfortunately.

**Comment by yyx990803** [comment]
@li3p make sure to set your GitHub email to public when you register (you can turn it back to private after you get the confirmation email)

**Comment by li3p** [comment]
@LinusBorg , @yyx990803  thank you guys. I turned my Github email to public and re-logined into forum, still cannot got confirmation email after click the link on the reminder tips. and I am sure I checked my spam folder . I am using gmail as my email.
