### ISSUE TITLE
Chrome/Firefox on OS X and Linux

### ISSUE THREAD

**Issue by markrjr** [vuejs/vue#3222]
What would it take to get support for Vue.js on OS X and Linux in both Chrome and Firefox?

I'm currently building a production app with Vue.js and this is kind of a deal breaker. 

Any Vue content just silently fails. Just try using the [Vue.js site](https://vuejs.org/guide/events.html) in Chrome on OS X. None of the examples work.

**Comment by rekateka** [comment]
@markrjr So none of the examples in http://vuejs.org/examples work? Are you running any additional plugins? I'm using OS X with Chrome 51 and Firefox 47 and all of them work fine.

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We keep questions out of issues :smile:
