### ISSUE TITLE
v-else attribute doesn't work

### ISSUE THREAD

**Issue by PavelTytyuk** [vuejs/vue#3223]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/koshpavel/3vh62y7r/

### Steps to reproduce
All explanations are in the output

### What is Expected?
Expected to not show <tr> with v-else attribute

### What is actually happening?
<tr> has both v-if and v-for, both of them works fine, but next <tr> with v-else attribute still renders.

**Comment by repsac-by** [comment]
it's  expected behavior.
`v-for` has higher priority than `v-if`
`v-if` in this case applies to each element which produces a `v-for`

**Comment by LinusBorg** [comment]
Hi @PavelTytyuk 

Adding to what @repsac-by explained, you can make it work by putting the v-if on a seperate element, like this:
```
    <ul v-if="contracts.length > 0">
      <li  v-for="contract in contracts">
        {{ contract }}
      </li>
    </ul>
    <div v-else>
      No contracts (now shown as expected)
    </div>
```
