### ISSUE TITLE
关于 Vue.mixin() 在使用 webpack + vue-loader 时候的问题

### ISSUE THREAD

**Issue by lmnsg** [vuejs/vue#3224]
当在 webpack 模式下，在 entry 中使用Vue.mixin({}) 会引发在子组件中使用Vue.partial注册全局 partial失效...

@yyx990803  help...  
是否是我使用 Vue.mixin 的时机不对呢？应该在什么时候进行 mixin 呢？
我是在路由启动前进行 mixin 的
```js
Vue.mixin({})

router.start(require('src/app.vue'), '#mainApp')
```

**Comment by yyx990803** [comment]
这个属于 `vue-loader` 的问题，请到相关仓库重开。另外请附上重现。
