### ISSUE TITLE
hot reload not propagating updated data to children

### ISSUE THREAD

**Issue by vird** [vuejs/vue#3225]
### Vue.js version
1.0.26

### Steps to reproduce

    vue -V
    2.1.0
    vue init webpack my-project
    # press many times ENTER
    cd my-project
    npm i
    # fill components like this https://gist.github.com/vird/e07fbff0cb56dcec5ec4ce2e2d125661
    npm run dev
    # open localhost:8080
    # click focus text. See that textarea focused properly
    # go to shared.js, replace 'focus' to 'focus '
    # hotreload applied
    # click focus text. shared.js?c91c:8 Uncaught TypeError: Cannot read property 'focus' of null

### What is Expected?
textarea focused properly

### What is actually happening?
shared.js?c91c:8 Uncaught TypeError: Cannot read property 'focus' of null

### What happens
new instance of SharedController, new instance of Hello are created.
Nested has old SharedController that has reference to old Hello instance in textarea_get closure.
Expected Nested has new SharedController instance after hot reload

Sorry for posting here. But https://github.com/vuejs/vue-hot-reload-api/ has no issues tab.

**Comment by LinusBorg** [comment]
You used an arrow function where you shouldn't because arrow functions have lexical `this` - it does not point to the current vue instance because arrow functions can't be bound.
```
  ready: function () {
    this.sharedController.textarea_get = () => {
      return this.$els.textarea // `this` will not be the vm.
    }
  },
```

**Comment by vird** [comment]
Ok. Another example without arrow function. https://gist.github.com/vird/a3ff8a4f9adc8b37a776335693e0846b
Here I have reference to textarea that not in document. Almost same problem.

replacing quoted string 'focus' in console.log('focus') to console.log('focus ') just triggers hot reload.

**Comment by vird** [comment]
Seems I understand a problem.
https://github.com/vuejs/vue-hot-reload-api/blob/1.x/index.js#L271
Hot reload kills new state and replaces it with old one.
Expected
1. replace state
2. ready 

Actual
1. Ready
2. replace state

**Comment by yyx990803** [comment]
This is a `vue-loader` & `vue-hot-reload-api` problem - please open at appropriate repo.
