### ISSUE TITLE
A form component  is embedded in my custom modal component, how to open the modal every time the embedded component's data is the latest

### ISSUE THREAD

**Issue by ruanzy** [vuejs/vue#3229]
A form component  is embedded in my custom modal component, how to open the modal every time the embedded component's data is the latest

`
<div id='app'>
<a class="btn btn-primary" @click="this.$ref.modal.show=true">open</a>
<my-modal v-ref:modal><addform v-ref:addform></addform ></my-modal>
</div>`

Modal second time to open the addform data should be changed but it not
because the addform component only be create at first

so,
How to open modal each time to build the addform component to call it‘s ready/create method to get the latest data

**Comment by posva** [comment]
Hello, please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). We use the issues to keep track of bugs and feature requests 😉
