### ISSUE TITLE
Can not use crypto ？？？

### ISSUE THREAD

**Issue by qk4089** [vuejs/vue#3230]
####  It is possible to write a demo js ,run  with node

test.js
```
'use strict'

var crypto = require('crypto');
var encrypted = "";
var cip = crypto.createCipher('rc4', 'abc');
encrypted += cip.update('asd', 'binary', 'hex');
encrypted += cip.final('hex');
console.log(encrypted);
```

```
$ node text.js
weasdaf // 
```
![qq 20160706180341](https://cloud.githubusercontent.com/assets/5036964/16614541/67d85996-43a4-11e6-9e91-065a0db12a52.png)

![qq 20160706180419](https://cloud.githubusercontent.com/assets/5036964/16614533/5e6e5086-43a4-11e6-8734-171b35a2d06d.png)

but when i use in component,has  a mistake
```
sorry, createCipher is not implemented yet
```
why?

**Comment by OpenGG** [comment]
Not related to Vue.js .
