### ISSUE TITLE
Can I pass propsData to dynamic component  in template 

### ISSUE THREAD

**Issue by terrydai** [vuejs/vue#3231]
when  I  render **form.jade** from **columns.json** ,   I  try to  pass propsData(multi props) to component , but It seems unsupported.    Is there a better way  to do this?  

> json 
```json 
[
  {"title": "A", "name":"a",  "component": "ui-dropdown" , "propsData": {"options": [], "on":"hover" }},
  {"title": "B", "name":"b",  "component": "ui-dropdown" , "propsData": {"options": [] , "on":"click"}},
]
```
> template : 
```jade
.ui.segment.form.bottom.attached
    .field(v-for="column in columns")
        label {{column.title}}
        component(:is="column.component",
                           :propsData="column.propsData", 
                           :value.sync="editor[column.name]")
```

Of course ,  there is a way to pass props one by one , but it seems not so good.
```jade
.ui.segment.form.bottom.attached
    .field(v-for="column in columns")
        label {{column.title}}
        component(:is="column.component", 
                           :options="column.propsData.options", 
                           :on="column.propsData.on", 
                            :value.sync="editor[column.name]")
```

**Comment by posva** [comment]
You misunderstood what are propsData for: http://vuejs.org/api/#propsData
You can actually pass and object to the `v-bind` directive. It looks like what you're trying to do:http://vuejs.org/api/#v-bind

**Comment by terrydai** [comment]
Thank you,  it's just what I need. So,  pass object(multi props) to component , 
I can use **propsData** in Vue instance  or **v-bind** in template .

**Comment by fnlctrl** [comment]
`v-bind` only binds attributes, it doesn't pass props. So I guess you have to pass each prop explicitly.

**Comment by terrydai** [comment]
@fnlctrl  ,  tks for your reply.  I have wrote a directive  to do this   and really appreciate  `vue` would  add this feature in the future:   
```javascript
directives: {
    props(props){
      let comp = this.vm.$children[this.vm.$children.length - 1];
      if(props && comp){
        // apply properties to component data
        _.forOwn(props, (value, key)=>{
          comp[key] = value
        })
      }
    }
  }
```
template: 
```jade
.ui.segment.form.bottom.attached
    .field(v-for="column in columns")
        label {{column.title}}
        component(:is="column.component",
                           v-props="column.propsData", 
                           :value.sync="editor[column.name]")
```

**Comment by iagafonov** [comment]
I have the same problem! @terrydai - this is good solution. I try it now.
For now I manually create new instances and mount them in particular element like this
`new MyComponent({el: '#id', propsData: {...}})`

**Comment by posva** [comment]
@fnlctrl You're right.
Sorry for misleading you @terrydai 
Marking this as duplicate of #2114
