### ISSUE TITLE
component data option and  the pipeline of data within vue-router

### ISSUE THREAD

**Issue by ericxin1982** [vuejs/vue#3233]
Hi,

I try to use vue-router, just confused with component data option and the pipeline of data when using vue-router together.
Does it mean when the pipeline of data get defined, then at this step, transition.next would set data into the component data option?
Or how to use?

Thanks
Eric Xin

### Vue.js version
1.0.23

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
