### ISSUE TITLE
Directive param renders as html attribute.

### ISSUE THREAD

**Issue by enomado** [vuejs/vue#3236]
In this [directive select2 example](https://vuejs.org/examples/select2.html) param `:option` is rendered as 

`<select tabindex="-1" class="select2-hidden-accessible" aria-hidden="true" options="[object Object],[object Object]">`

By opening on google chrome inspect devtools.

**Comment by yyx990803** [comment]
Ah, that example was using old outdated syntax... updated.

**Comment by enomado** [comment]
Oh wait. Why this worked before ? `:options` passed to tag with `directive` worked and it really appear in directive.params. So options should not be passed through directive this way(lets say the component way)? 

BTW you're still passing `data: this.params.options` to `select2` constructor despite its undefined. And it works. But may be confusing.
