### ISSUE TITLE
Watched array of models issue

### ISSUE THREAD

**Issue by rokups** [vuejs/vue#3239]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/9f9dmLrq/

### Steps to reproduce
1. Enter `a` to first input
2. Enter `b` to second input
3. Enter `c` to third input
4. Delete `b` from second input

### What is Expected?
Third input with `c` should move to second place while keeping input value `c`.

### What is actually happening?
Third input moves to second place but it is value is cleared. Model array has correct value `c` as it is displayed before input correctly.
Workaround is to use `@keyup="manage"` instead of watching `items` array as answered [here](http://stackoverflow.com/questions/38229626/array-items-as-models-in-vuejs/38232720#38232720).

**Comment by phanan** [comment]
Wrapping your function within a `$nextTick` will solve the problem: http://jsfiddle.net/dv31js0p/. You can read more about `nextTick` [here](https://vuejs.org/api/#Vue-nextTick).

**Comment by rokups** [comment]
Oh okay, could you please elaborate what exactly was happening here?
