### ISSUE TITLE
Why Code not woring on second vue instance ?

### ISSUE THREAD

**Issue by thisismyaim** [vuejs/vue#3240]
I created download function and in html file i have component called <Download> and it is in repeat state. so if i have to files then two download buttons.

On the first instance timer works fine but on second instance timer starts but does not stop when clear interval also not updaing vm.seconds in view {{ seconds }}

Is there any why to call timer function separate on each vue instance but same function download ?

````
download() {
                var vm = this;
                var timer = null;
                vm.seconds = 100;
                timer = setInterval(function() {
                    if(vm.cancel) {
                        return clearInterval(this);
                    }
                    vm.seconds -= 1;
                    if(vm.seconds == 0) {
                        vm.$http.post('/first', {
                            adv: vm.adv
                        }).then(function() {
                            vm.$http.get('/second', { }).then(function(response) {
                                document.getElementById("download").style.display = "block";
                                vm.file = window.open('/download?file=' + response.request.params.file + "&filename=" +
                                        response.request.params.filename + '&adv=' + vm.adv);
                                vm.file = "";
                            });
                        });
                    }
                }, 1000);
````

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). If you're sure this is a Vue's bug, please create a reproducing fiddle.

**Comment by thisismyaim** [comment]
Thanks
