### ISSUE TITLE
The templates show in a inverted order on iOS when I use v-for to render a list. 

### ISSUE THREAD

**Issue by ChinTeo** [vuejs/vue#3241]
As it said in title, and the code : 

```
    var data = {
        pagetype: {
            'common': 'common',
            'link': 'link',
            'detail': 'detail',
            'list': 'list',
            'rn': 'rn'
        }
    };
    var demopage = new Vue({
        el: '#container',
        data: function() {
            return data;
        }
    })
```

```
<div class="container" id="container">
    <template v-for="ele in pagetype">
        <div>{{ele}}</div>
    </template>
</div>
```

What I expect is:
![image](https://cloud.githubusercontent.com/assets/7775037/16648863/9f16af6a-4468-11e6-88a1-28f829a009b7.png)

But on iOS:
![image](https://cloud.githubusercontent.com/assets/7775037/16648898/bb928efc-4468-11e6-9e89-eb8cde668dcd.png)

why?

**Comment by phanan** [comment]
Properties order in objects is not guaranteed in JavaScript. Also, please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
