### ISSUE TITLE
Can I rename Vue to the other names?

### ISSUE THREAD

**Issue by losywee** [vuejs/vue#3242]
For the project necessary, can I rename Vue to the other names?

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by yyx990803** [comment]
If you are using the standalone build then no. If you use a module bundler e.g. Browserify/Webpack then it doesn't matter because there are no globals.

**Comment by losywee** [comment]
@phanan  I am sorry for the mistakes, thanks.

**Comment by losywee** [comment]
@yyx990803  Thanks.
