### ISSUE TITLE
Directive function syntax throws an error

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3243]
> __EDIT__: Turns out this syntax is not deprecated, it just needs to be fixed. 😃 

When using this deprecated directive syntax:

``` js
Vue.directive('my-directive', function (value) {
  // this function will be used as update()
})
```

The errors thrown are:

```
vue.js:2168 [Vue warn]: Error during component render (found in root instance)
vue.js:3479 Uncaught TypeError: Bind must be called on a function
```

These are pretty vague, so wasn’t sure if we wanted to throw a better warning, similar to when users don’t have a root element in their template for example. Maybe something like:

```
[Vue warn]: Directive definition must be an object (Function definition is deprecated)
```

**Comment by yyx990803** [comment]
Hmm, the function shorthand should still be supported. This seems like a bug.

**Comment by chrisvfritz** [comment]
@yyx990803 Good to know! Edited the issue. The reason I thought it was deprecated is because `update` is no longer called after `bind`, which seemed to eliminate the use case for this feature. Or is that a bug too?
