### ISSUE TITLE
Remove argument from directives?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3244]
I believe the argument syntax previously used by features such as `v-el` and `v-ref` has now been completely removed from Vue's API - except in custom directives. It may be a lack of imagination, but I can't personally think of a use case where I would use an argument over a value or modifier. Should arguments just be removed from the directives API?

**Comment by simplesmiler** [comment]
Aren't `v-on` and `v-bind` using it?

**Comment by chrisvfritz** [comment]
Yep - I just forget because I always use the shorthands. 😛
