### ISSUE TITLE
[Vue 2.0] render is being called twice

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#3249]
### Vue.js version
v2.0.0-beta.1

### Reproduction Link
https://jsfiddle.net/7c602hb8/

### Steps to reproduce
Check console

### What is Expected?
Render function should be called only once (?) or is this correct behavior?

### What is actually happening?
Rener function is called twice

**Comment by sqal** [comment]
wow, ok i actually didn't close wrap-tag, so its my fault, please close the issue

**Comment by aeolusheath** [comment]
@sqal  hey bro,  you didn't close what wrap-tag?
