### ISSUE TITLE
Rendering problem with v-show, transition and v-model update.

### ISSUE THREAD

**Issue by cemelo** [vuejs/vue#3252]
### Vue.js version
2.0.0-beta.1

### Reproduction Link
https://jsfiddle.net/cemelo/h8Lyqa3e/3/

### Steps to reproduce
Write some e-mail in the provided input provided at the fiddle.

### What is Expected?
An image should appear _(and stay)_ bellow the input.

### What is actually happening?
The image shows for some apparently random time and then disappears.

**Comment by LinusBorg** [comment]
Hello @cemelo 

Thanks for filing this issue. It seems that there is indeed an issue with the transition (it works without it).

We will look into it.

**Comment by cemelo** [comment]
@LinusBorg no worries, man. I tried to look into it, but without any knowledge of the codebase, I couldn't figure out the reason. Just a heads up, the bug seems to happen with v-if as well.
