### ISSUE TITLE
Not syncing with object oriented coding

### ISSUE THREAD

**Issue by acterhd** [vuejs/vue#3254]
Hello. I updating Array object in children element (when ready I bind array object to children), but Vue can't sync arrays. I mean, Vue.js not observe arrays. So not updating, even computed values. In one word - I change array object but changes not applied. Not helped no sync, no anything with two-way binding. And yes, I don't know how to bind array (or any object) for observation. I used custom  components. 

My example very big, but soon I present.

**Comment by posva** [comment]
Are you aware of this: http://vuejs.org/guide/list.html#Caveats ?

**Comment by acterhd** [comment]
Sad here is no 
```
this.$set("channels[0]", value)
```

**Comment by acterhd** [comment]
I already fixed.
