### ISSUE TITLE
dynamical appended vuejs content: scope.test is not a function

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3255]
Hi Vuejs team,
I am trying to find a workable solution for following scenario:
1. vuejs will render its "main" content first;
2. when some click happen, it loads some vuejs aware html(including both component referring  and its  data);
3. that dynamically loaded vuejs partial html should be compiled and inserted to a pre-defined node(mount point).
I am now trying to use the $mount functionality to give a try.
You can have a check on this fiddle http://jsfiddle.net/matiascx/cd35khy8/
Also, i paste code here:
```
<div id="app">
    <button v-on="click: addNewElement()">Add custom Element</button> 
    <br />
    <div id="dynamicloaded"></div>
</div>
new Vue({
    el: '#app',
    data: {
        sampleElement: '<div><button v-on="click: test()">Test</button></div>'
       
    },
    methods:{
        addNewElement: function(){
        
           
           
           var vmtemp = Vue.extend({
                            template: this.sampleElement,
                            methods: {
                            }
                        });
           new vmtemp().$mount(document.getElementById('dynamicloaded'));
        },
        test: function(){
           alert('Test');
        }
    }
});
```
The vuejs always complain: 
```
VM1881:3 Uncaught TypeError: scope.test is not a function
```
I am wondering it is because wrong scope assigned to newly mounted content.
1. How to fix it?
2. Is that the proposed way to achieve that goal (**dynamically compile and mounted count with right scope**)
Thanks for your help out!

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

---

For your use case, consider using Webpack code splitting with [async components](http://vuejs.org/guide/components.html#Async-Components).

**Comment by cnweibo** [comment]
@yyx990803 , thanks for response. Gitter can not be accessed in cn you know. I have submitted one stackoverflow and pasted here: http://stackoverflow.com/questions/38299400/dynamical-appended-vuejs-content-scope-test-is-not-a-function
I also found this is quite common questions raised. Please spend a little time to give vuejs users answer for how to "achieve the goal : dynamically compile and mount ajax loaded content(vuejs aware html) with the right scope)"
thanks!

**Comment by yyx990803** [comment]
The "proper" way to do it is what I suggested: async components.

**Comment by cnweibo** [comment]
尤大，great, i have give that try,  it really works with right parent-child relationship.
But there is still one thing i am annoyed. 
The dynamical loaded content works as async component's template, and that template contains some other child component, I MUST define that child component as a global component with Vue.component('child-should-be-in-async-component' {});
Can I work the same way browserfiy/webpack manner with just info of {components: {ChildShouldBeInAsyncComponent}} in component configuration object?
Thanks~!

**Comment by Kingdaro** [comment]
Export a function from your component files instead?
```vue
<template> <!-- ... --> </template>

<style> /* ... */ </style>

<script>
export default (resolve, reject) => {
  some.api.call()
    .then(() => resolve({ /* component stuff... */ }))
    .catch(() => reject('some error message'))
}
</script>
```
Not 100% sure if this actually works though

**Comment by cnweibo** [comment]
@Kingdaro, I have followed official vuejs async component, and it works as expected. The only remaining issue is: how can i let async component know its child component defination referrenced in its template. Now I MUST let that child component GLOBAL defined with Vue.component pattern

**Comment by cnweibo** [comment]
@yyx990803 , in my above comments of https://github.com/vuejs/vue/issues/3255#issuecomment-231772850, it is not valid. I can use normal webpack browsefiy pattern to referencing child component with { component:{ LocalChildComp}} pattern. Ignore it. Sorry for bring confusing info here
