### ISSUE TITLE
How to dynamic add computed property

### ISSUE THREAD

**Issue by languanghao** [vuejs/vue#3256]
### Vue.js version
1.0.23

### Reproduction Link
https://vuejs.org/examples/firebase.html

### What is Expected?
From the code, the computed property 'validation' will cacl when all data properties changed. If we add 'validation_name', 'validation_email' as computed property can solve the problem.

Now the problem is, how can I dynamic add 'computed property' without hard code the 'validation_name' property? I tryed vm.$set method, but it only create a data propery.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.
