### ISSUE TITLE
v-model emitting native change/input events

### ISSUE THREAD

**Issue by aristidesfl** [vuejs/vue#3260]
The following example shows Vue with a jQuery plugin. It almost works, but not when changing the vm.data. Writing custom directives is an option in this kind of integration, but for many plugins this wouldn't be necessary if Vue emitted a change even on the bound element. 

Example: https://jsbin.com/ruwisiyowo/edit?html,css,js,output

Related: https://github.com/vuejs/vue/issues/503

**Comment by yyx990803** [comment]
I don't think it's Vue's responsibility. You can easily write a custom directive to emit the change event and use it alongside `v-model`:

``` js
Vue.directive('emit-change', function () {
    var el = this.el
    Vue.nextTick(function () {
      $(el).trigger('change')
   })
})
```

**Comment by aristidesfl** [comment]
It makes sense. But maybe it would be useful to a lot of people if this directive was included by default.

**Comment by Kingdaro** [comment]
I disagree. It's convenient, but logically, separating HTML events handled by HTML elements from Vue events handled by Vue components makes things much more straight forward to reason about, without muddying it all together.

**Comment by aristidesfl** [comment]
They would still be separated, in a directive.
