### ISSUE TITLE
how to bind image onerror event

### ISSUE THREAD

**Issue by nqdy666** [vuejs/vue#3261]
When the image url is returned 404, it will triggere onerror event.
I want to use it as such, but it does not take effect
```js
<template>
   <img :src="avatarUrl" @onerror="imageLoadOnError" />
</template>
<script>
export default {
    methods: {
      imageLoadOnError () {
        this.avatarUrl = DEFAULT_AVATAR
      }
    }
}
</script>
```

**Comment by phanan** [comment]
Use `@error`. And please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by xiaoboRao** [comment]
in vuejs. please  use @error. and img url must be url link. cant be like base64 format
