### ISSUE TITLE
Handlebars comments

### ISSUE THREAD

**Issue by victorwpbastos** [vuejs/vue#3262]
Would be great to have a syntax for comments. Like Handlebars does:

```hbs
{{!-- comment block --}}
```

**Comment by phanan** [comment]
What's wrong with `<!-- -->`?

**Comment by victorwpbastos** [comment]
`<!-- comment -->` gets rendered in the output while `{{!-- comment --}}` don't. For code comments I think `{{!-- comment --}} is better.

**Comment by phanan** [comment]
But for production you should always use a minifier/uglifier, no? ;)

**Comment by victorwpbastos** [comment]
I guess you're right!

**Comment by yyx990803** [comment]
For production code if you minify your templates with `html-minifier` (included in both vueify and vue-loader), the comments will be stripped.

In 2.0 comments are ignored by default.

**Comment by Kingdaro** [comment]
For the record, using Javascript multilines works for this purpose.
```vue
<template>
  {{"I get rendered"}}
  {{/* I do not */}}
</template>
```

**Comment by jeroenlammerts** [comment]
Is there going to a setting in 2.0 to keep the comments?
https://jsfiddle.net/tf7ja0y4/

Would be nice to have a setting like [ractive](http://docs.ractivejs.org/latest/options#stripComments)
