### ISSUE TITLE
.vue file,  webpack converts background-image relative path  to local path

### ISSUE THREAD

**Issue by yezongyang** [vuejs/vue#3265]
![uf4h6 _4 y02 wj5 jzik](https://cloud.githubusercontent.com/assets/8924156/16758966/3ab19e08-4847-11e6-83a7-42882abc5d50.png)

**Comment by yezongyang** [comment]
![uf4h6 _4 y02 wj5 jzik](https://cloud.githubusercontent.com/assets/8924156/16758944/1e2b116a-4847-11e6-8535-833c294678b8.png)

**Comment by iltegin** [comment]
Use  [forum vue js](forum.vuejs.org)  or [Gitter](https://gitter.im/vuejs/vue) for question like this.

**Comment by phanan** [comment]
I see you created the same issue here: https://github.com/vuejs/vue-loader/issues/284. Closing this in favor of that.
