### ISSUE TITLE
Custom directive params validation

### ISSUE THREAD

**Issue by medelasri** [vuejs/vue#3266]
Hi,

I develop a custom directive with params option and I want to validate params types + disable v-bind for some of them. This feature is available for props in components (props validation). 

Please any ideas??

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by medelasri** [comment]
I have posted on chat without response... Params validation it is not a feature??

**Comment by yyx990803** [comment]
directive params will be deprecated in 2.0 and will unlikely to get validation support in 1.0.
