### ISSUE TITLE
Strange behavior using 'watch' inside components.

### ISSUE THREAD

**Issue by iNDicat0r** [vuejs/vue#3267]
I am using watch to listen for changes done to an array which is shared between components, and i see a strange behavior. The function that watches the array gets triggered multiple times instead of one time. for example if i insert an item to this array the watch function gets called 3 times... any idea what is happening ?

component:

```
data: function() {
		return {
			sharedState: store.state }
}
```
```
watch: {
        'sharedState.selectedItems': function(val , oldVal){ console.log('i got triggered') }
}
```

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
