### ISSUE TITLE
why cant custom directive catch the event?

### ISSUE THREAD

**Issue by smildlzj** [vuejs/vue#3268]
hi,

this is a event listener in bind function , but i cant trigger it from parent component.

$dispatch and $broadcast also dosen work.

```
  Vue.directive('ajax', {
    params: ['for' , 'to'],
    terminal: true,
    bind: function () {
      var self = this;
      var el = self.el
      self.anchor = createAnchor('v-ajax')
      replace(el, self.anchor);

      self.on('ajax-success' , function(res){
        self.render(self.params['for'] , self.params['to'] , res);
      });
    },
  .......

  });
```

中文用户，英语不太好。。。

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
