### ISSUE TITLE
vuejs app architecture for dynamic template with dynamic data and dynamic component type issue

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3270]
Sorry for posting 'issue' here. I have posted question on vue forum and stackoverflow but with no feedback. I am now developing an app with vuejs and the architecture is important from begining.
Here is the link:
http://forum.vuejs.org/topic/4604/how-to-address-component-with-dynamic-template-and-its-relative-data
http://stackoverflow.com/questions/38342241/vuejs-better-way-to-address-component-with-dynamic-template-and-its-relative-dat
I copy here for kind proposal. It is an architecture issue.
I have following question/requirement, if anyone has good idea, please kindly post for discussion It is for the dynamically rendering for dynamical template and data use component The scenario is as following:
1.root vue instance fetch data from backend, say following data returned:
```
[
{
    /* this section will be fed to a component */
    type: 'FirstSub',
    templatestr: '<div> <more-vue-customized-component itsdata="xxx"></more-vue-customized-component>  </div>',
    data: [
        datafordynamicComponent: xxxx
    ]

},
...
{
    /* this section will be fed to a component */
    type: 'lastSub',
    templatestr: '<p> <more-vue-customized-component itsdata="xxx"></more-vue-customized-component>  </p>',
    data: [
        datafordynamicComponent: xxxx
    ]

}
```
2. Which structure/architecture we can use to render as following composition using above data?
```
<root>
<FirstSub></FirstSub>
...
<lastSub></lastSub>
</root>
```

**Comment by fnlctrl** [comment]
Does this solve your problem?
```html
<component v-for="item in yourComponentsFromAPI" is="item.name" :some-prop="item.data">
</component>
```

**Comment by cnweibo** [comment]
@fnlctrl , thanks for your response. That dynamic component pattern can meet the requirement if we have no "dynamically loaded template".  The templatestr string data works as the template for the FirstSub/lastSub component. 
The only gap here is: how we dynamic compile and make alive FirstSub component with its template and other data in live reactive manner. 
thanks to @yyx990803 , i found async component pattern can bridge some gap(can make dynamic loaded html into live). @fnlctrl , Unfortunately, i do not know how to give props to async component.
That is to say: if  yourComponentsFromAPI contains an async component, how can we access the some-prop property within that async component??

Again, I have raised one stackoverflow for that specific question:
http://stackoverflow.com/questions/38344091/vuejs-can-we-give-props-to-async-component-via-dynamic-component-pattern-compo


Thanks~!

**Comment by cnweibo** [comment]
@fnlctrl , please see live fiddle here:　
https://jsfiddle.net/matiascx/wjab87om/8/

**Comment by fnlctrl** [comment]
How "dynamic" is your ajax loaded template? Are they arbitrary and random? If not, have you tried extracting the "dynamic" bits and create static components (they can be async-loaded with webpack)

If you just need to pass props to a dynamically created component, use [propsData](http://vuejs.org/api/#propsData)

**Comment by LinusBorg** [comment]
Hello ..

your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

And you seem to know this.

So this issue is closed now.

**Comment by cnweibo** [comment]
@fnlctrl , you are right, if i extract the dynamic data in the template string, it can work. But not want to do that way. I'd like to save the templatestr(including some variables)into database and fetch it as a whole. 
Throw the data to vuejs for rendering.
propsData seems not valid for dynamical component?
thanks~!

**Comment by cnweibo** [comment]
@fnlctrl , i have no idea how to make webpack work, now i use browersify , unfortunately, it can not support that feature you mentioned.(async-loaded )

**Comment by terrydai** [comment]
Here is a related issue with feature request  https://github.com/vuejs/vue/issues/2114.

I have wrote a ```component-proxy```  to  resolve it which may do some  help to  you. 

````javascript 
import _ from 'lodash'
import Vue from 'vue'


export default {
  props: ['name', 'props', 'value'],
  template:  '',
  created(){
    let props = []
    if(this.props ){
      // apply properties to component data
      _.forOwn(this.props, (value, key)=>{
        // console.debug( key,  this[key])
        props.push(`:${_.kebabCase(key)}="props['${key}']"`)
      })
    }

    // console.debug('component proxy', props.join(' '))
    this.$options.template = `<component :is="name" ${props.join(' ')} :value.sync="value"></component>`
  },
}



```

About usage: 

```jade
.ui.form
    .field(v-for="column in table.columns")
      label {{column.title}}
      component-proxy(:name="column.editor.type",:props="column.editor.propsData",:value.sync="column.name")
```

**Comment by cnweibo** [comment]
@terrydai , thanks, it seems it is a great idea, i will do some try.. For the usage, i can not understand well.
What does .field and .ui.form mean?  Would you give a little explain on your usage code?
thanks a lot!

**Comment by terrydai** [comment]
@cnweibo  It is  jade template ,    using Semantic-UI

**Comment by cnweibo** [comment]
@terrydai , i have found your contribution on https://github.com/vuejs/vue/issues/3231 ,great idea.
in your comments, what is the intention for value.sync here? can you give a small explain on :name,:props and :value.sync respectively? I have not full caught what should i do following your proposal.

```
component-proxy(:name="column.editor.type",:props="column.editor.propsData",:value.sync="column.name")
```
thanks~!

**Comment by terrydai** [comment]
@cnweibo  you need to review `jade` docs  and my `component-proxy` definition above

**Comment by cnweibo** [comment]
@terrydai , i got it, that is defined in jade

**Comment by spooio** [comment]
ffasfdfs
