### ISSUE TITLE
Why input value no updata?

### ISSUE THREAD

**Issue by owen-hong** [vuejs/vue#3271]
![image](https://cloud.githubusercontent.com/assets/6466628/16798135/3b62f85c-491d-11e6-83ce-f6ed9482396a.png)

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). 

If you're sure this is a Vue's bug, please provide a minimal JSFiddle containing a set of reproducible steps that can lead to the behavior you described.

Thanks.

**Comment by yyx990803** [comment]
信息不全，无版本无重现，不符合 issue 要求。
