### ISSUE TITLE
Bad parsing when bound data contains a backtick

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue#3273]
### Vue.js version
1.0.26

### Reproduction Link
http://codepen.io/sirlancelot/pen/zBPVBo?editors=1010#0

### Steps to reproduce
* Bind an inline object with a value containing the backtick character

### What is Expected?
* Object is reproduced properly in the data model

### What is actually happening?
* `scope.` is being added to everything between the backtick and an escaped quote.

We're using props to curry an initial data model from the server to the browser. We're doing it in a manner similar to the example shown in the CodePen. Basically, our root Vue instance contains a list of props that will show up on the element and are populated by the server.

**Comment by Etheryte** [comment]
As a temporary workaround, you can bypass the issue by escaping the backtick.

```
//broken
:items="[{'title':'one','value':1},{'title':'t`wo','value':2}]"

//works
:items="[{'title':'one','value':1},{'title':'t\`wo','value':2}]"
```

**Comment by skyronic** [comment]
I made a change to a regular expression and this seems to be working fine now. However this seemed like a very important regexp and I am not sure of the patch.

### Before

![screen shot 2016-07-19 at 10 45 27 pm](https://cloud.githubusercontent.com/assets/80173/16959450/c710d8a8-4e02-11e6-937b-adbe6576902f.png)

### After

(I've highlighted the part in red)

![screen shot 2016-07-19 at 10 45 02 pm](https://cloud.githubusercontent.com/assets/80173/16959461/d7ee1492-4e02-11e6-94c7-6afcef30c53a.png)

**Comment by LinusBorg** [comment]
@skyronic what RegExp tool is that? looks very useful...

**Comment by skyronic** [comment]
@LinusBorg - I used https://www.debuggex.com/ very handy!

**Comment by nerdyglasses** [comment]
@skyronic thx! I use http://rubular.com/ a lot. It tests with the ruby lib but works fine too.
