### ISSUE TITLE
bower installed version does not contain dist directory

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3274]
### Vue.js version
1.0.26
### Steps to reproduce
bower install vue
### What is Expected?
there should be a `dist/` directory under `bower_components/vue/`
### What is actually happening?
there is only `src/` directory and its content cannot be referenced directly in html files.

BTW, this same issue also happens for vue-resource

**Comment by yyx990803** [comment]
Cannot reproduce. This is likely due to outdated bower version, make sure to install the latest.

**Comment by Centaur** [comment]
Indeed. Thank you for point it out.
