### ISSUE TITLE
Vue v1.0.26 input view value no updata

### ISSUE THREAD

**Issue by owen-hong** [vuejs/vue#3275]
### Vue.js version
v1.0.26

### Reproduction Link
https://jsfiddle.net/520UED/n00a572z/

### Steps to reproduce
点击刷新按钮时间戳正常更新到input中，一切正常，但是手动输入改变Input输入值后，再次点击刷新按钮，Current.spriteName和Current.cssName正常更新，通过chrome调试工具看到input值也改变了，但是界面中的input值却没更新
![image](https://cloud.githubusercontent.com/assets/6466628/16826388/8c43eb72-49af-11e6-879d-52c4c3cf6dda.png)

**Comment by LinusBorg** [comment]
This is normal,expected behaviour for attribute interpolations.

if you want to have the attribute updated, use a binding instead:
```js
<input v-on:blur="blurUpdataTime" type="text" v-bin:value="Current.spriteName">
```

**Comment by yyx990803** [comment]
用 `:value="Current.spriteName"`，不要用 `{{ }}`。后者只能设置初始值。

**Comment by owen-hong** [comment]
原来如此，非常感谢
