### ISSUE TITLE
Unit testing: Directives not evaluated?

### ISSUE THREAD

**Issue by reinvdwoerd** [vuejs/vue#3277]
Hi,

I'm having trouble unit testing my Vue components.
The component and It's children render correctly, but directives are not evaluated.

For example: "{{count}}" is not replaced by the value of the expression, but remains 
"{{count}}"

I've tried doing the assertion in a vm.$nextTick() callback, but with no difference.

I'm using AVA as test runner.

### Vue.js version
1.0.23

### Reproduction Link
https://jsfiddle.net/zphut3zw/

**Comment by yyx990803** [comment]
AFAIK Ava does not support running tests in browsers. https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md
