### ISSUE TITLE
Not receiving confirmation email from the forum.

### ISSUE THREAD

**Issue by mytc** [vuejs/vue#3278]
Hi, I tried to register in the forum http://forum.vuejs.org/ , but I can't get my confirmation email hence I can't create support topic there.
It said the email has succesfully sent but I just not receiving 
I don't know if this is the place to report the issue, I am sorry if I am in the wrong place, but I just couldn't get in touch with the forum admin.

**Comment by yyx990803** [comment]
Make sure to have your GitHub email address public when registering - you can set it back to private after you've received the confirmation email.

**Comment by mytc** [comment]
I already did, but still not getting the email.

**Comment by OpsRJ** [comment]
I have the same problem. I´m not able to create a new topic

**Comment by mytc** [comment]
@OpsRJ , I managed to get the confirmation email by change the email in vue account setting.  It was the github generated email when I registered in the forum, that's why I didn't get the email. You will get it after change it to your active email.
