### ISSUE TITLE
The command v-for of a String Array can not be displayed

### ISSUE THREAD

**Issue by yp2005** [vuejs/vue#3279]
There is my code:

`<template>
    <div>
        <ul>
            <li v-for="pic in pictures">
               <img src="{{pic}}">
            </li>
            <li v-if="pictures[0]" >
               <img src="{{pictures[0]}}"/>
            </li>
            <li v-if="pictures[1]" >
               <img src="{{pictures[1]}}"/>
            </li>
            <li v-if="pictures[2]" >
               <img src="{{pictures[2]}}"/>
            </li>
        </ul>
        <p v-for="pict in pictures">{{pict}}</p>
        <p v-for="(index, pictu) in pictures">{{pictures[index]}}</p>
    </div>
</template>

<script>
    export default {
        data: function() {
            return {
                pictures: []
            };
        },
        ready: function() {
            //In fact，there get data by ajax request
            this.pictures = [
                'http://cdn.duitang.com/uploads/item/201409/04/20140904220031_HwxTy.thumb.700_0.jpeg',
                'http://cdn.duitang.com/uploads/item/201409/04/20140904220031_HwxTy.thumb.700_0.jpeg',
                'http://cdn.duitang.com/uploads/item/201409/04/20140904220031_HwxTy.thumb.700_0.jpeg'
            ];
        }
    }
</script>`

The array is a simple String array, and the command v-for just like the, it's not special at all. But these doms can not be displayed, and if I use v-if, it can be displayed.

So, can you help me? what's the problem of my code.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by yp2005** [comment]
i think this is a bug, but i'm not sure.
