### ISSUE TITLE
support for `$watch`-ing any property on a vm

### ISSUE THREAD

**Issue by weisjohn** [vuejs/vue#328]
I'm trying to subscribe to any data changes made against any property on the vm, not just pre-defined property names.  I couldn't find any way to do it, so here's my proposal.

I made an example here: http://jsfiddle.net/BBk3j/.  In the first `$watch`, I subscribe to changes on the `foo` property. The next two `$watch` statements would be my proposal to allow any watching for updates on any property. Either support a wildcard syntax (which I don't think is a great idea, because `*` is a valid property name in JS), or a better syntax that makes the string property name optional.

**Comment by usmanhalalit** [comment]
In case anyone is struggling like me with this in Vue.js 1.0.x, then here's how you do that:

```js
vm.$watch(
    '$data',
    function (newVal, oldVal) {
        
    },
    {
        deep: true
    }
);
```

**Comment by guitcastro** [comment]
How can I get which property is changing when watching  $data?

**Comment by janokary** [comment]
It is all documented here. Very easy:
http://vuejs.org/api/#watch

**Comment by guitcastro** [comment]
@janokary  The documentation does not give any hint how do know witch property changed when using "$data". I am able to get notify about the new and oldvalue for all property in my viewmodel but not about which property changed

**Comment by NoelDavies** [comment]
as mentioned by @guitcastro  this still doesn't mention how to watch an item within a list.

Say I have a list like so

    ```
    data: {
        items: [
            {name: 'a', quantity: 2},
            {name: 'b', quantity: 2},
            {name: 'c', quantity: 2}
        ]
    }
    ```

If I do a watch on this using

    ```
    watch: {
        'items': {
            handler: function (value, mutation) {
            },
            deep: true
        }
    }
    ```

How will I know what item has been mutated / changed?

This is the issue I, nor guys on my livestream can work out.

**Comment by keepitreal** [comment]
@NoelDavies I'm wondering the same. The docs say that watching an array that mutates will not even provide the new value of the entire array. So you couldn't even loop through old and new values to find differences.

http://vuejs.org/api/#vm-watch

**Comment by giohappy** [comment]
Why do you need it? If you think in a reactive way you should't need to know which property has changed while watching the whole object/array. In case you need to perform custom logic for a specific property change you should watch that property...

**Comment by rpkilby** [comment]
@keepitreal I think the recommend way to work around this is to have a component that wraps each element in your array. The wrapper-component would then watch for mutations. Something like...

```html
<div v-for="el in myArray">
   <wrapper-component v-bind:el.sync="el"></wrapper-component>
</div>
```

**Comment by happilymarrieddad** [comment]
What's the best way to do this in a component if you just want to watch for any changes in the components data and not the whole app?

I've tried to do things like
```
watch:{ '$data':function() { console.log('changed') } }
```
and
```
watch:{ 'this.$data':function() { console.log('changed') } }
```

Thanks!

**Comment by ajanes93** [comment]
is it possible to do this with $children property?  I have tried but doesn't seem to work.  basically I want to fire a method every time a child is added/removed from the DOM.

`watch:{
    '$children': {
        handler:function() {
            console.log('changed')
        },
        deep:true
    }
},`
