### ISSUE TITLE
Sign-in Google inside Component

### ISSUE THREAD

**Issue by Antoniobk** [vuejs/vue#3282]
Hi, want to insert into a 'component' the button 'sign-in' google that call the function 'onSignIn' to obtain the data, in this case when I click the button 'sign-in' does not listen to the function inside my component, someone who can help me?

_Sign.vue_
```
<template>
   <div class="g-signin2" data-onsuccess="onSignIn" data-theme="ligth"></div>
</template>
<script>
  import Firebase from 'firebase';

  export default {

    data() {
      return {
        firebaseApp: this.$router.app.fireAPP
      };
    },
    methods: {
      onSignIn: function(googleUser){
        console.log('Google Auth Response', googleUser);
      }
    },
  }
<script>
```

**Comment by posva** [comment]
Hi!
Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue) and to provide more information 😉.
