### ISSUE TITLE
MutationObserver在hybrid app中失效

### ISSUE THREAD

**Issue by lianer** [vuejs/vue#3285]
app首页是h5实现，通过原生实现下拉刷新功能，如果h5中全局绑定touchmove事件后修改属性（比如实现导航栏固定），vue内部调用了nextTick，这时候修改textNode的值并不会触发nextTickHandler，导致了nextTick队列一直在pending，所有后续的数据操作均无法更新到DOM。

458行的值改动后，并没有触发451行的nextTickHandler回调。

![image](https://cloud.githubusercontent.com/assets/9332264/16905354/5ad88180-4cd7-11e6-81d2-2c6de3574b25.png)

**Comment by yyx990803** [comment]
你用的版本旧了吧，这个问题有针对性的修复过。请提供 Vue 和 OS 的版本信息。

**Comment by lianer** [comment]
我看到新版本中对ios9.3+做了排除，暂时没有测过ios9.3以下的系统。
还有即将出的ios10不知道是否对MutationObserver支持良好？

**Comment by yyx990803** [comment]
@lianer ios10 出了才知道，这个严格来说是 iOS 的 bug，有可能会在 10 被 fix。
