### ISSUE TITLE
when <a> add :href, its color will don't work with css? why?

### ISSUE THREAD

**Issue by mcc108** [vuejs/vue#3286]
when I add
```
 <a id="github" :href="github" target="_blank">Github</a>
```
then
```
#github { color: #fff; }
```
and
```
data: {
 "github": "https://github.com/"
}
```

when I will open it on safari,  link's color sometime will don't work with css, It's going to be black, not #fff .
when I will open it on chrome,  link's color will change from black to white.

but I replace `:href="github"` to `href="https://github.com/"` ,   then it's work fine.

How to solve this problem？

**Comment by mcc108** [comment]
and i also add `v-cloak`

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an **example** on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by posva** [comment]
It looks like a safari bug, thought

**Comment by mcc108** [comment]
e...   i think it looks like i use `this.$http.get('data.json')` cause it

**Comment by mcc108** [comment]
[https://congm.in/demo/vue/1/](https://congm.in/demo/vue/1/)    it's demo ,  please open it, and look  top right corner `Github`  ,   its color is #fff,  but sometime it will be black

**Comment by ktsn** [comment]
It can be reproduced without Vue.js, looks like a Safari's bug. https://jsfiddle.net/ktsn/he2pf46d/1/

It would be avoid by adding v-if and hide the link until you receive the data. https://jsfiddle.net/evdeayjb/
