### ISSUE TITLE
Accessing slot contents

### ISSUE THREAD

**Issue by KKSzymanowski** [vuejs/vue#3287]
Is there a simple way to access component's slot contents?
For what I know the only way is to access it is to get eg. `this._slotContents.default.textContent`.

I'd like to propose creation of instance property called `$slots` which will contain contents of slots.
For example
```javascript
console.log(this.$slots);
//Would print
Object {
    default: 'This is the default slot',
    someNamedSlot: 'This is a named slot'
}
```

I'm aware I can do everything with `prop`s but in many cases the `slot` syntax is just, at least for me, more natural and elegant.

What do you think about this?
I'm not familiar with VueJS source at all, otherwise I would make a PR.

**Comment by ktsn** [comment]
It's intended to implement. Please see #1726

**Comment by miljan-aleksic** [comment]
@KKSzymanowski, you could create a plugin which will save those slots content as you expect. Seems quite a specific feature.

**Comment by KKSzymanowski** [comment]
@miljan-aleksic For me it feels more like a part of the core, but if, as @ktsn said, it's intended to be implemented I will close this and wait patiently for this functionality.
Thanks.
