### ISSUE TITLE
Beta 2 Transition Bug - Content visible for a split second before transition begins

### ISSUE THREAD

**Issue by theotherzach** [vuejs/vue#3288]
### Vue.js version
2-beta-2

### Reproduction Link
http://codepen.io/theotherzach/pen/mEXWQd?editors=1010

### Steps to reproduce

If you go to the code pen and hit the "open panel b" button

### What is Expected?

Panel A should `slideUp` and then Panel B should appear via `slideDown`.

### What is actually happening?

If you go to the code pen and hit the "open panel b" button

1. panel a will slide closed
1. **panel b becomes visible**
1. **panel b disappears**
1. panel b slides open

Steps 2 and 3 are unexpected and possibly a bug, though I may be using the transitions in a way that they're not intended or using the wrong hooks.

**Comment by yyx990803** [comment]
This is likely because Velocity applies the animation on the next frame (in a `requestAnimationFrame`). You can fix this by adding a `@before-enter` hook which sets `el.style.display = 'none'`.

**Comment by theotherzach** [comment]
Yup, that did the trick. Thanks and I apologize for the erroneous bug report.


http://codepen.io/theotherzach/pen/mEXWQd?editors=1010
