### ISSUE TITLE
Get props not list in component props config

### ISSUE THREAD

**Issue by HeChenTao** [vuejs/vue#3290]
I want to get other props which are not list in component props config. I write a Input component, like this:
```
 <div class="my-input-wraper">
    <input class="my-input" type="text"/>
 </div>
```
When i use like this:
```
<my-input placeholder="please input"></my-input>
```
It render as:
```
 <div class="my-input-wraper" placeholder="please input">
    <input class="my-input" type="text"/>
 </div>
```
The placeholder attribute now is applied on the wraper. I want get the props not list in component props, so I can apply them to the input element. Just like react `{..props}`.

**Comment by yyx990803** [comment]
I don't see a reason why you are not listing it as an explicit prop.

Anyway, this is impossible in 1.0. In 2.0 you can do this by accessing the raw component vnode data, but you will have to wait for official documentation on that.
