### ISSUE TITLE
[feature-request] Add scope prop to <slot>

### ISSUE THREAD

**Issue by joshglendenning** [vuejs/vue#3293]
Something I've always wanted working with Vue components was an ability to pass some child/component data to a `<slot>` (while still compiling in parent scope), like the way `v-for` works. I've seen a few issues others have had with this use case, with some weird workarounds (see below).

- http://forum.vuejs.org/topic/366/slot-as-an-item-row-template
- http://forum.vuejs.org/topic/526/repeating-table-row-with-slot
- https://forum.vuejs.org/topic/3456/slots-but-with-data-binding/2

Looking through the source code it seems like this is definitely achievable with a small modification to the slot elementDirective by some sort of scope param, to be merged with the parent somewhere around [here](https://github.com/vuejs/vue/blob/dev/src/directives/element/slot.js#L41).

As an example, here's a jsfiddle with a (hacked-in) `<scoped-slot>` elementDirective which is used to build a sortable table component with a custom column template.

https://jsfiddle.net/joshglendenning/7r86jmu3/3/

It would be fairly straightforward to integrate this sort of `:scope="..."` behavior in the native <slot>, but I wanted to greenlight it on here before doing a pull request.

**Comment by posva** [comment]
Scoped slots are harder to reason about since they are compiled inside the component which is not visible (cf `item` variable).
But the main issue with them is that there's already a way of achieving the same behaviour with components and props which are concepts already exist in Vue.
Moreover scoped slot are not possible in Vue 2: you can pass components or functions and easily use them in render functions

Your code snippet is working nicely and you can still use it if you prefer using the scoped-slot syntax. You may consider using `paramWatchers` to handle name modification. You should share it as a lib so others can benefit from it too 😄 !

**Comment by joshglendenning** [comment]
Makes sense. I'll release it as a standalone plugin 👍 . Out of curiosity, what would be the idiomatic way to achieve this sort of functionality  in Vue 2?

**Comment by posva** [comment]
I'm coming back asap with a fiddle to illustrate that 😉

**Comment by posva** [comment]
Coming back at you with the example soon. The idea is to use a render function and use prop functions. You can bind the function call with the vm context

**Comment by posva** [comment]
@chrisvfritz helped out on this one: you can declare a function on the Vue object (not in methods) and pass that down to a component:
https://jsfiddle.net/chrisvfritz/1LdqxLs0/

Obviously the code would look much better with jsx. You'd also need to make sure that `h` is available (something as as `const h = this.$createElement`)

**Comment by posva** [comment]
ping @joshglendenning

**Comment by miljan-aleksic** [comment]
@joshglendenning, I have recently shared my workaround about this. You can check it out [here](http://forum.vuejs.org/topic/4771/reuse-slot-as-multiple-rendering-template).

**Comment by joshglendenning** [comment]
@posva Interesting, thanks for the update. Is there a convenient way to use a DOM element or template string instead of using `this.$createElement`?

@miljan-aleksic, I'll take a look, thanks.

**Comment by joshglendenning** [comment]
Also here is a gist of my `scopedSlot` solution if anyone is interested.

https://gist.github.com/joshglendenning/1efb58edb0598e37da348236b15c3022

**Comment by posva** [comment]
@joshglendenning Yes there is: [you can use jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx) (same as react)

**Comment by martynchamberlin** [comment]
@joshglendenning Curious if you've made this plugin in a way that's compatible with Vue 2.0? Vue.elementDirective [is deprecated in 2.0](https://github.com/vuejs/vue/issues/2873), making this solution no longer work.

**Comment by posva** [comment]
Scoped slots exists in vue 2. No need for a plug-in 😉

**Comment by martynchamberlin** [comment]
Ah cool. You're right! https://vuejs.org/v2/guide/components.html#Compilation-Scope

**Comment by joshglendenning** [comment]
Oh man, this is amazing, I didn't know they were added to Vue 2. Great work as always with Vue!
