### ISSUE TITLE
Cannot get slots in 2.0-beta.2

### ISSUE THREAD

**Issue by YunSun-CN** [vuejs/vue#3297]
From the latest version(2.0.0-beta.2), I can't get slots through `this.$slots`;
See the demo here:

> https://jsfiddle.net/hhfLhaxm/2/

**Comment by LinusBorg** [comment]
Vue does not allow self-closing tags like React.
wrong:

    <slot />

right:

    <slot></slot>

Then it works:

https://jsfiddle.net/Linusborg/hhfLhaxm/3/

**Comment by YunSun-CN** [comment]
@LinusBorg 
However, no `this.$slots` yet.

**Comment by LinusBorg** [comment]
Oh, you tried to get slots in the main Vue instance, but the slot is in the `demo` component, so of course `this$slots` does not return any slots.

https://jsfiddle.net/Linusborg/hhfLhaxm/4/
