### ISSUE TITLE
想实现一个页面过渡效果

### ISSUE THREAD

**Issue by NeilJee** [vuejs/vue#3298]
有两个页面，页1，页2。

页1->页2时，使用 in-out，即页2先从右侧进入，页1再从右侧出去。
页2->页1时，使用out-in，即页2先从左到右离开屏幕，然后页1显示出来。

这里有个问题，第二部页2离开时，会有白屏，然后页1才会加载。
请教如何解决。

PS：个人也尝试过第二步使用 in-out，即页1先进来，但是刚进来时是被页2覆盖的。然后页2离开，页1会出现在下面。

谢谢

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。

**Comment by lichenhao** [comment]
https://github.com/Augus/ngAnimate 原理和 NG 动画其实是一致的。动画要有状态 https://docs.angularjs.org/api/ngAnimate

**Comment by ahkjxy** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。
