### ISSUE TITLE
v-for access root variable

### ISSUE THREAD

**Issue by shenglingshi** [vuejs/vue#3299]
how to access root variable in v-for binding

**Comment by kazupon** [comment]
Hi!
Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue) and to provide more information 😉.

**Comment by shenglingshi** [comment]
其实我想问，怎么在v-for 循环体里面，访问Vue data下的直接属性。
