### ISSUE TITLE
Get element client width in directive

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue#3300]
I want to get element client width in directive , I find that  `bind()` and first time `update()` couldn't get element client width, Maybe the DOM still not ok，what should I do to get the client width

**Comment by posva** [comment]
Hi!
Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).
You can take a look at `requestAnimationFrame` or `Vue.nextTick`
