### ISSUE TITLE
Adding a shortcut reference to this in the render function

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#3304]
Basically this would be a convenience feature.  Instead of
```
render:function(h){
  var vm=this;
  return h('div',vm.text)
}
``` 
you would have
```
render:function(h,vm){
  return h('div',vm.text)
}
``` 
Which reduces the code (at least a little) the programmer has to write for each render function.

One other thing it would help with, is keeping track of the right `this` in anonymous functions. Again this would be a convenience feature, but `this` can be hard to deal with if you're not paying attention. 
```
render:function(h,vm){
  return h('div',{on{keyup:function(e){if(e.keycode==13)vm.text='success'}}},vm.text)
}
```

**Comment by yyx990803** [comment]
I don't think this is necessary. `h` is there because `const h = this.$createElement` can be tedious to type, but `this` is fine, especially if you use arrow functions.
