### ISSUE TITLE
v-enter class not applied when using <transition>

### ISSUE THREAD

**Issue by mzgajner** [vuejs/vue#3305]
### Vue.js version
v2.0.0-beta.2

### Reproduction Link
[JSFiddle](https://jsfiddle.net/9n0te2on/)

### Steps to reproduce
1. Add an element that can be toggled.
2. Wrap it with `<transition>` as per latest [Transition API](https://github.com/vuejs/vue/releases/tag/v2.0.0-beta.2).
3. Define styling for `.v-enter` and `.v-enter-active` classes.
4. Toggle the element.

### What is Expected?
The `.v-enter` class should be applied for a moment to set an initial state and then `.v-enter-active` should be applied with the end state to make the transition happen.

### What is actually happening?
Only `.v-enter-active` is applied and the transition never happens.

**Comment by YunSun-CN** [comment]
As far as I know, `.v-enter` is added but with `.v-enter-active`concurrently.
So it not works.

And `.v-appear`, `.v-appear-active` are not added even if setting `appear` to true.
```
<transition appear>
</transition>

**Comment by LinusBorg** [comment]
v-enter is only on the element for 1 frame to set the starting styles. you will never see it in the dev tools with your eyes ;)

Anyway, it works like this: https://jsfiddle.net/Linusborg/9n0te2on/2/

**Comment by mzgajner** [comment]
Ah, I see, so I just misapplied it. Thanks, closing!

It could be useful to document this a bit more clearly, after reading about [Vue 2.0 features](https://github.com/vuejs/vue/issues/2873) I understood it differently, especially since it's mentioned it works in the same manner as ReactCSSTransitionGroup, which has an example of styling in [their tutorial](https://facebook.github.io/react/docs/animation.html) that doesn't work with this behaviour.

**Comment by mzgajner** [comment]
@YunSun-CN setting appear to true will not automatically generate those classes, it will use v-enter[-active] by default (which makes a lot of sense IMHO). If you want a different class for first appearance, you need to specify it: `<transition appearClass="some-class" appearActiveClass="some-other-class">`. See [here](https://github.com/vuejs/vue/issues/2873) for more details.
