### ISSUE TITLE
v-model doesn't work with computed setters on checkboxes?

### ISSUE THREAD

**Issue by kaptajnen** [vuejs/vue#3307]
It is not 100% clear from the documentation if this is supposed to work on for checkboxes. If not, I would like to know how to work around this issue.

### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/p04dgeba/

### Steps to reproduce
Set v-model on a checkbox to a computed property with a setter. Setter is not called.

### What is Expected?
Setter should be called

### What is actually happening?
Setter is not called

**Comment by kaptajnen** [comment]
Edited to make it clear this issue is for checkboxes

**Comment by repsac-by** [comment]
Your code is not correct, the computed has no dependencies.

**Comment by kaptajnen** [comment]
Awesome, thanks!

**Comment by phanatomtalonTalon** [comment]
data is array not string
