### ISSUE TITLE
Look at my Framework, please =) you may get ideas

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [vuejs/vue#3310]
https://www.npmjs.com/package/ui-js

Just interested in your opinion, or any questions, such as I emulated Shadow DOM or Shadow Styles.
If you need some advice, I will share experiences and prompt =)

And in general, what do you think?

**Comment by phanan** [comment]
No spam please.

**Comment by uMaxmaxmaximus** [comment]
i want span

**Comment by phanan** [comment]
Yeah? Here you go: `<span>No spam please.</span>`
