### ISSUE TITLE
Few Vue 2 questions

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3311]
1) What would be the best way to test a not released version (the last code builded locally)? For example the `v-text` directive from latest code in `next`repo, even though is passing all tests, is not working on my environment. It just doesn't render and after a few try and error I can tell exactly after what commit it is happening.

1A) It could be a braking change, but don't see any comment about that.
1B) Or something wrong with my code for which I would like to test on jsfiddle but is not possible as is not released.

2) Not sure if this is Vue 2 specific. The vue-loader is always returning an Object with default property. That works fine if using ES6, not for ES5 where a workaround `require(...).default` is necessary. As using ES6 is not a requirement, it should neither be to know about its behaviour. Vue-loader could use `module.exports` instead and support both ES5 and ES6. Otherwise, let's at least document it.

**Comment by yyx990803** [comment]
1. No guarantees about anything in a non-released branch.

2. It uses ES6 exports only if you use `export default { ... }`. If you use `module.exports = { ... }` then you can `require()` it.
