### ISSUE TITLE
watched checkboxes have the same old value as new value

### ISSUE THREAD

**Issue by Philipp-M** [vuejs/vue#3313]
When multiple checkboxes are used, that fill up an array, and this array is watched, the old value is equal to the new value in the watch function
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/philmi/75kznpcx/

### Steps to reproduce
Just click the checkboxes and watch the console
### What is Expected?
The old value should be the value before a checkbox was clicked
### What is actually happening?
The old value is the same as the new value

**Comment by yyx990803** [comment]
Although not directly related, this has been fixed in https://github.com/vuejs/vue/commits/dev
