### ISSUE TITLE
Trying to access non-existent property "outerHTML" while rendering

### ISSUE THREAD

**Issue by finico** [vuejs/vue#3315]
I noticed that strange warning is displayed to the console

### Vue.js version
2.0.0-beta.3

### Reproduction Link
[http://jsbin.com/yujokuhura](http://jsbin.com/yujokuhura/edit?html,js,output)

### Steps to reproduce
Click on div with text "click me"

### What is Expected?
In the console will appear instance of Vue app 

### What is actually happening?
In the console will appear warning `[Vue warn]: Trying to access non-existent property "outerHTML" while rendering. Make sure to declare reactive data properties in the data option. (found in root instance)`

ps: in the v1.0.16 all ok

**Comment by LinusBorg** [comment]
This is a problem with jsbin. It works fine on jsfiddle, for example: https://jsfiddle.net/vx0ks9yo/

**Comment by finico** [comment]
Yup.. and the locally all is well
Not a bug :yay:

**Comment by jakob-e** [comment]
This is also the case on _codepen.io_ in _editor view_
