### ISSUE TITLE
this.$children is empty inside computed property when it's iterated

### ISSUE THREAD

**Issue by Lourayad** [vuejs/vue#3316]
### Reproduction Link

https://jsfiddle.net/ylrd/s36mwtst/

When there's a computed property that returns an array, and when this property is iterated in a `v-for`, `this.$children` returns an empty array.

What could be the issue here?

**Comment by yyx990803** [comment]
Do realize that `this.$children` is **not** a reactive data source, so using it in computed properties will not work as expected.

Instead, generate the child components with a source data array and base your computed properties on that array.
