### ISSUE TITLE
[v2.0.0-beta.3] v-model in component not showing value in input initially

### ISSUE THREAD

**Issue by richardwyke** [vuejs/vue#3317]
I have a very simple component, which was working in beta 2, but no longer works as of beta 3.

The template and JS looks like this:
```html
<template id="transaction_qty_only">
    <div>

        {{ quantity }}

        <input type="text" v-model="quantity" placeholder="edit me">

    </div>
</template>

<script>
    export default {

        template: '#transaction_qty_only',

        data() {
            return {
                quantity: '10'
            }
        },

    }
</script>
```

On load in beta2 the input shows the value of 10, however in beta 3 it is empty. When you type in the input it will update the quantity value, however it is blank initially.

v2.0.0-beta.2
<img width="177" alt="screen shot 2016-07-25 at 11 04 01 am" src="https://cloud.githubusercontent.com/assets/1467807/17088263/2a1040fc-5258-11e6-81d5-db044cf9d0ce.png">

v2.0.0-beta.3
<img width="176" alt="screen shot 2016-07-25 at 11 05 44 am" src="https://cloud.githubusercontent.com/assets/1467807/17088267/355d481a-5258-11e6-9495-5eaa5c172170.png">

**Comment by yyx990803** [comment]
Cannot reproduce, please provide a reproduction.

**Comment by miljan-aleksic** [comment]
@richardwyke, try deleting node_modules folder and installing npm dependencies again. I had similar issues that were solved like that.

@yyx990803, if the solution works it could be wise to highlight it on the release notes for others.

**Comment by richardwyke** [comment]
thanks @miljan-aleksic that sorted it - sorry for the false alarm @yyx990803
