### ISSUE TITLE
Bug where if a container component is deleted then it's private state replaces the next component in the array.

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#3318]
### Vue.js version
2.0.0.beta.3

### Reproduction Link

https://jsfiddle.net/06qp6o1e/
Here is a simpler one that doesn't involve a child component
https://jsfiddle.net/06qp6o1e/2/

### Steps to reproduce
Click on Alpha's delete button.

### What is Expected?
That the Alpha container and child component are deleted completely from the list, and Beta replaces it in the first position and retains whatever number it had originally.

### What is actually happening?
When Alpha is deleted the child component's state is being transferred to Beta's child component. Meaning if Alpha was showing an number 5 and Beta is showing a number 9 then when Alpha is deleted Beta will now show Alpha's number 9.

### Note
This does not occur if you pass in the number as a property. Here is an edited version showing this https://jsfiddle.net/06qp6o1e/1/

**Comment by yyx990803** [comment]
This is not a bug. You need to give each component a unique key to avoid that.
