### ISSUE TITLE
[Vue 2.0] How can I terminate rendering in custom directive?

### ISSUE THREAD

**Issue by YunSun-CN** [vuejs/vue#3319]
### Vue.js version
2.0.0

I want to create a custom [virtual-repeat](https://material.angularjs.org/latest/demo/virtualRepeat) directive, but I can't terminate rendering children nodes.
Or any other ideas to simulate?

**Comment by yyx990803** [comment]
You cannot. In 2.0 structural directives are reserved and you can only create binding directives.

Instead, create a higher-order component (which controls its children) for that purpose. You will probably want to wait for docs on how to work with the virtual dom.
