### ISSUE TITLE
Vue.js and Web Components

### ISSUE THREAD

**Issue by AlessandroEmm** [vuejs/vue#332]
Hey there

I've been trying to to get vue.js running with a custom Element (Web Component) and I cant seem to get it running. I tried to hand it a { el: 'template', data: { test:" test"}} but it did not work (no errors). 

Where as the template consists of

```
         <template>
         <h1> {{ test }}</h1>
          </template>
```

While the template can be resolved by vue the problem is that template is no ordinary HTML element and doesn't have the H1 as direct child. It has however a document fragment as an attribute which itself has the children in it. Passing vue this fragment didnt work either unfortunately. A document fragment is obviously not the same as full blown element so could that be the issue?

Thank you!
Alessandro

**Comment by kristianmandrup** [comment]
How can I package a Vue component as a web component? Couldn't find any examples of that so far...
