### ISSUE TITLE
source load twice when use {{{ Mustache }}} interpolations

### ISSUE THREAD

**Issue by hejinjun** [vuejs/vue#3320]
### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/hejinjun529/x58tpy5a/2/
### Steps to reproduce
1. open the browser developer tools and switch to the Network panel.
2. filter the ajax request, only keep the Media request.

### What is Expected?
mp3 file request should be load only twice.
(once by directive v-html )
(once by {{{ Mustache }}} interpolations )

### What is actually happening?
mp3  file request load thrice.
(once by directive v-html )
(twice by {{{ Mustache }}} interpolations ) . it should only load once like v-html do.

**Comment by yyx990803** [comment]
This is because `{{{ }}}` needs to first parse the string into a document fragment, cache it, and then clone it. This is a wontfix. To workaround it, just use `v-html`.
