### ISSUE TITLE
HTML5 elements support in older browsers

### ISSUE THREAD

**Issue by afkatja** [vuejs/vue#3321]
### Vue.js version
1.0.26

### Reproduction Link

A bare bone example code can be found here:
http://codepen.io/afkatja/full/RRrQzG/

### Steps to reproduce
Include HTML5 elements, such as `main` and `picture`, together with vue.js, in your project and view it in IE9. See that the project fails *if you have not IE dev tools open*.

### What is Expected?
vue.js should ignore elements that the browser does not recognize.

### What is actually happening?
If devtools are open, you get the errors 
```
[Vue warn]: Unknown custom element: <main> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

[Vue warn]: Unknown custom element: <picture> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
```
but functionally, the page works in IE9.

**Comment by yyx990803** [comment]
Cannot reproduce, it's working for me. The warning itself doesn't cause any behavior difference, so it's unlikely a Vue issue.
