### ISSUE TITLE
[REGRESSION][V2.0.0-beta.4]Passing JSON data into components props

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#3326]
In 1.* versions of Vue DOM templates where evaluated `as-is` and we where able to pass into them data from PHP in form of JSON strings (just had to remember to single quote the attribute):
```
<my-component :parameters='{"minValue":1,"maxValue":6,"range":true}'></my-component>
```
And next use them like:
```
<template id="my-component">
<input type="number" :min="parameters.minValue" :max="parameters.maxValue" v-model="value">
</template>
```

But with virtual DOM in 2.* branch now all attributes are converted to double quoted, so our code fails to render because of unescaped doublequote characters in JSON content.
```
- invalid expression: :parameters="{&quot;minValue&quot;:1,&quot;maxValue&quot;:6,&quot;range&quot;:true}"
```
It disables all kind of possibilities, and will force users to manually JSON.parse those strings at components creation time.

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by sqal** [comment]
everything works fine if you pass object this way:

```
<my-component :parameters="{ minValue: 0, maxValue: 100, range: true }"></my-component>
```

https://jsfiddle.net/ttzad3w1/

**Comment by Uriziel01** [comment]
Doh!
I'm an idiot then, been so much into my solution I've forgotten about the most obvious solution.
Closing the `issue` then :+1:

**Comment by Francismori7** [comment]
This is actually an issue. In Laravel (PHP), when generating JSON from an object/model/class, you will get quoted keys, and thus the compiler in Vue will break the property passing.

**Comment by vinicius73** [comment]
@Francismori7 you need pass a JSON String to params.
`<comp my-prop='{{ $model }}' />`
single quotes are important, because the generated json has double quotes

**Comment by Francismori7** [comment]
@vinicius73 well of course and I'm using them. Still not working properly.
