### ISSUE TITLE
Attributes transclussion on functional components

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3328]
### Vue.js version
2.0.0b4

### Reproduction Link
https://jsfiddle.net/miljan/Lof3r8pb/

### Steps to reproduce
Open the jsfiddle and examine the rendered buttons code.

### What is Expected?
I expect the aria attribute to be set on both components, as per transclusion feature.

### What is actually happening?
The transclusion doesn't works on functional components.

**Comment by yyx990803** [comment]
Functional components do not have auto attribute transclusion, you get exactly what you returned from its render function. To "pass down" the raw data, do:

``` js
render (h, ctx) {
  return h(
    'button',
    ctx,data, // use "transcluded data"
    ['Button']
}
```
