### ISSUE TITLE
vue怎么获取动态变量名的数据

### ISSUE THREAD

**Issue by cuiziwei** [vuejs/vue#3331]
如：我要获取的数据为
data : {
   "a" : 123,
  "b" : 456
},
"current" : "a"

{{ current }}

应用场景：切换tab时实时更新数据

**Comment by crossjs** [comment]
使用 computed：

```
computed: {
  currentData () {
    return this[current]
  }
}
```

**Comment by cuiziwei** [comment]
@crossjs 非常及时，谢谢了~不使用computed也可以的，重点是通过this[current]，忘记还可以这么用了

**Comment by crossjs** [comment]
@cuiziwei 在 template 里使用 this，不是太合适

**Comment by cuiziwei** [comment]
@crossjs 额，不太优雅是吧，也没用this，默认在模板读取变量值的话就可以省略this

**Comment by yyx990803** [comment]
请不要用 issue 问问题。
