### ISSUE TITLE
define component ways

### ISSUE THREAD

**Issue by Thstone37** [vuejs/vue#3333]
according to doc:
  1,we can use Vue.extend+Vue.component();
  2,we can use registration sugar Vue.component();
  3,also,we can use <template>in HTML
which way is the best?

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).

It depens on your usecase and backend:

- Server Render backends like ruby on rails: Better use inline-templates
- SPA or Nodejs: use `.vue` files
- Prototyping: inline or `script` tags are fine

On top of that:
- Define components globally when needed
- Vue.extend can be used when you don't have a `.vue` file but most of the time you won't even need to use it
