### ISSUE TITLE
Allowing shorthand syntax for static classes and ids in render function

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#3335]
In looking at snabbdom I noticed you could do `h('div#container.two.classes',...` to add classes or ids. Could this be option when writing render functions? Right now Vue spits out an error thinking that `div#container.two.classes` is an unknown custom element.

**Comment by yyx990803** [comment]
This is intentional because parsing the string can be quite costly. You can use some custom helpers to wrap the `h` function to achieve that, e.g. https://github.com/ktsn/vue-vnode-helper

**Comment by pwang2** [comment]
even answered by Evan and closed here. still want to +1.
some Emmet basic syntax will be quite helpful.
