### ISSUE TITLE
[2.0] resolveAsyncComponent for es6 module

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#3336]
When we use asyncComponent as an es6 module, it can't be resolved automatically now for the following reason:
The module exported from es6 is now something like
``` javascript
{
  __esModule: true.
  default: Component
}
```
so we must resolve asyncComponent by ourselves like that:
``` javascript
export default new VueRouter({
  mode: 'hash',
  routes: [
    {
      path: '',
      component: function (resolve) {
        require(['../App'], function (Component) {
          resolve(Component.default);
        });
      }
    }
  ]
});
```

Maybe we should provide a *Syntactic sugar* to prevent *repetitive tasks* in the [resolveAsyncComponent](https://github.com/vuejs/vue/blob/v2.0.0-beta.5/src/core/vdom/create-component.js#L202) function like:
``` javascript
if(res.__esModule && res.default && 1 === Object.keys(res).length) {
    res = res.default;
}
```

**Comment by yyx990803** [comment]
This is a userland issue. Also with Webpack 2 you can just do:

``` js
component: resolve => System.import('../App').then(resolve)
```

**Comment by JounQin** [comment]
``` javascript
component: resolve => System.import('../App').then(resolve)
```

It doesn't work with the argument of callback is still like
``` javascript
{
  __esModule: true.
  default: Component
}
```

My test code:
``` javascript
export default new VueRouter({
  mode: 'hash',
  routes: [
    {
      path: '',
      component: resolve => System.import('../App').then(function (Component) {
        console.log(Component);
        resolve(Component);
      })
    }
  ]
});
```

**Comment by yyx990803** [comment]
You need to use `babal-preset-es2015-webpack` to avoid ES6 module syntax being transpiled. `vue-loader` currently still has some issues with Webpack 2, but what I showed is what eventually should work.

**Comment by yyx990803** [comment]
Actually it seems even with the webpack preset it still returns the object with `default`. I guess you just have to do that for any `System.import`ed modules in Webpack 2.

**Comment by JounQin** [comment]
Yep, it still doesn't work and that makes import asyncComponent becoming something foolish. :(

**Comment by yyx990803** [comment]
Just updated `vue-loader`. Now this works:

``` js
component: resolve => System.import('../App').then(m => resolve(m.default))

// or

component: resolve => require(['../App'], m => resolve(m.default))
```

**Comment by JounQin** [comment]
What's the difference with the previous solution?

We still must resolve`esModule.default` by ourselves not by `vue` nor `vue-loader`.

My point is that we could provide a solution to prevent it.

Anyway, maybe I should do it in my own code like that:
``` javascript
import VueRouter from 'vue-router';

const resolveAsyncComponent = resolve => m => {
  m.__esModule && Object.keys(m).length === 1 && (m = m.default || m);
  resolve(m);
};

export default new VueRouter({
  mode: 'hash',
  routes: [
    {
      path: '',
      component: resolve => require(['../App'], resolveAsyncComponent(resolve))
    },
      ...otherRoutesWithAsyncComponent
  ]
});
```

**Comment by yyx990803** [comment]
This is build-system specific and easy enough to do in userland with a single function. I don't think it needs to be in Vue itself.
