### ISSUE TITLE
Large applications style guide

### ISSUE THREAD

**Issue by vinicius73** [vuejs/vue#3338]
VueJS is **awesome**. I think amazing how simple it is to create applications with it.
But, large applications need bigger planning.
It would be great if the documents provide more tips for people who are not yet accustomed to component-based applications.

Obviously there must be only tips, not rules.
VueJS is beautiful by the flexibility it provides, giving freedom in the development of applications.

Well, I think it would be great that this initiative came from the core VueJS.

Thanks.

**Comment by hernandev** [comment]
+1

**Comment by LinusBorg** [comment]
Please re-open this issue on the docs repo: github.com/vue/vuejs.org

**Comment by vinicius73** [comment]
thank you @LinusBorg 
https://github.com/vuejs/vuejs.org/issues/343
