### ISSUE TITLE
select Form Input Bindings

### ISSUE THREAD

**Issue by luckymore** [vuejs/vue#3339]
### Vue.js version
v0.12.12

### What is Expected?
```html
  <select options="opts" v-model="opt">
    <option value="" v-text="请选择借款期限"></option>
  </select>
```
```javascript
  this.opts = [{value: 12, text: 12}, {value: 24, text: 24}, {value: 36, text: 36}];
  this.opt = 6;

  //Shouldn't `this.opt` be setted '' automatically.
  
```

### What is actually happening?
the webpage performance that none of the option is selected, and `this.opt === 6`.
![image](https://cloud.githubusercontent.com/assets/5390013/17200159/79bd6f62-54b5-11e6-83ba-19442fdde84d.png)

**Comment by dpweberza** [comment]
Hi @luckymore 

I think your trying to dynamically render select options, with the select list defaulting to "Please Select".
You can see an example of that here: [https://jsfiddle.net/91bdot7t/1/](url)

Regarding 

>  //Shouldn't `this.opt` be setted '' automatically.

The model is the source of truth, not the view.
So the select list defaults to the value you specify using `opt = 6`, the model doesn't default to the value in the view.

**Comment by LinusBorg** [comment]
Hello @luckymore 

Thank your for your interest in this project.

Version 0.12 is no longer supported converning bugs, 1.0 has be out for long enough and we are abouot to release 2.0

Furthermore, for usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by luckymore** [comment]
@dpweberza thx. 💯
