### ISSUE TITLE
CSP compliant build

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#334]
Basically use a different `exp-parser` that uses Esprima. Since size doesn't matter that much in CSP-enforcing environments, the extra code is an acceptable tradeoff.

**Comment by gapipro** [comment]
Just tried to use CSP version in Chrome App and I still get 


`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:".`
