### ISSUE TITLE
[2.0]Lost whitespace in `<pre><code> </code></pre>`

### ISSUE THREAD

**Issue by QingWei-Li** [vuejs/vue#3341]
### Vue.js version
2.0.0-beta.5

### Reproduction Link

https://jsbin.com/guyudu/edit?html,js,output

### Steps to reproduce

template
```html
  <div>
  This is correct.
  
  <pre>
    <span>1. Hello</span>
    <span>2. Vue</span>
  </pre>
  
  This is incorrect. Lost whitespace
  
  <pre>
    <code>
      <span>1. Hello</span>
      <span>2. Vue</span>
    </code>
  </pre>
</div>
```

### What is Expected?
```html
        1. Hello
        2. Vue
```

### What is actually happening?
```html
     1. Hello 2. Vue
```

**Comment by selfcatering** [comment]
**<span>** as an immidiate child of a **<pre>** tag is rendered as a block element, in the second example it acts as a regular inline element since it's wrapped with a **<code>** tag - that has nothing to do with **vuejs**
