### ISSUE TITLE
transition attribute dosen't work in vue 2.0.0-beta.5

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#3343]
above the vue Version 2.0.0-beta.1, the transition attribute dosen't work, but the vue 2.0 [document](https://github.com/vuejs/vuejs.org/blob/2.0/src/guide/transitions.md) still reserve this usage.

### Vue.js version
2.0.0-beta.5

### Reproduction Link
https://jsbin.com/lipeni/edit?html,css,js,output

### Steps to reproduce

```
<div>
      <input type="text" class="input" v-show="visible" transition="fade">
      <button @click="visible = !visible">toggle</button>  
</div>
```

### What is Expected?
the input toggle with fade transition
### What is actually happening?
the input toggle without the fade transition

**Comment by rekateka** [comment]
Wasn't this a breaking change introduced in [Beta 2](https://github.com/vuejs/vue/releases/tag/v2.0.0-beta.2) onwards?

**Comment by baiyaaaaa** [comment]
@rekateka I see it, thanks~

**Comment by baiyaaaaa** [comment]
@rekateka I see it, thanks~
