### ISSUE TITLE
why dynamically mounted components can not be accessed by rootvm.$children??

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3344]
Hi, 
I have read the vuejs official document:
http://vuejs.org/api/#parent
it says " Parent option Specify the parent instance for the instance to be created. Establishes a parent-child relationship between the two. The parent will be accessible as this.$parent for the child, and the child will be pushed into the parent’s $children array"
I have tested with $mount a component to a mount point, Unfortunately,  the newly inserted component CAN NOT be accessed by root vm via $children property.
I have written a stackoverflow ticket also here.

http://stackoverflow.com/questions/38307070/why-dynamically-mounted-vuejs-content-is-not-child-component-of-root-vue-instanc

Please explain whether or not it is a vuejs bug or something i did wrong.

thanks~!@

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, this is certainly not a bug. If the component is not created by the parent, but by user code, the parent cannot be added automatically.

Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by cnweibo** [comment]
@LinusBorg , thanks for feedback." If  the component is not created by the parent, but by user code, the parent cannot be added automatically ", that is ok, but the documentation says we can set up the parent-child relationship with setting the parent property, unfortunately, we can not. It should be bug either for vuejs itself, or we should upgrade the vuejs documentation , isn't it? If that is true(change parent to setup new parent-child relationship), how to do to let that work, we should make it clear. Thanks~!

**Comment by yyx990803** [comment]
If you think it's a bug you need to provide a reproduction.

**Comment by cnweibo** [comment]
@yyx990803 ,
@LinusBorg 
I have created jsbin at http://jsfiddle.net/matiascx/7Ljygv81/4/ to demonstrate what is wrong here.
This is a normal component and  a "dynamic mounted component" by clicking a button. 
The "normal" component can receive broadcasted message from root vue instance and his vm.$parent points to the root vue instance;
The "dynamic mounted component" can not receive broadcasted message from root vue instance and his vm.$parent is undefined.  I have setting explicitly child.$parent = rootVueInstance, that does not help.

So, please check whether or not it is a vuejs bug, or it is vuejs documentation bug, or I have not did wrong.

Thanks~!

**Comment by cnweibo** [comment]
Hi, VUEJS team,
Can you have a look on above fiddle to check whether or not it is an issue or something i did wrong?
thanks~!
