### ISSUE TITLE
[Feature] In-browser vue transpiler

### ISSUE THREAD

**Issue by congrady** [vuejs/vue#3345]
Hello,

This might not be the best place to consult this, but I couldn't find the solution to my problem on either stackoverflow, gitter or forum.

I'd like to start a new project optimized for HTTP/2. (no bundling, no concatenating). In development mode, I'd like to avoid build step completely.

Is there a way to use Vue compiler in-browser? (Possibly babelifying my javascript files with selected plugins and pre-processing less or sass files).

There is a standalone build for babel, and in-browser less compiler. Is itpossible to make a standalone vue compiler build? (UMD build that would expose an API to transpile strings extracted from .vue files)

Thanks and sorry if this isn't the right place for this issue

**Comment by yyx990803** [comment]
First, [HTTP/2 doesn't solve all the problems - you will still need bundling](https://medium.com/webpack/webpack-http-2-7083ec3f3ce6).

Second, it's terribly inefficient to do asset transpilation at runtime - you need to send down all the transpilers to the client AND compile everything there. This is simply not feasible if you want decent UX.

The only thing that can do in browser transpiling is SystemJS/jspm, although Vue does have a plugin for it, it offers a much less optimal development experience than the Webpack counterparts.

So, my recommendation is... just use Webpack.
