### ISSUE TITLE
Can I use Highcharts in Vue

### ISSUE THREAD

**Issue by malaimoo** [vuejs/vue#3346]
as above ,if the answer is YES, then how to use it ,can you give me an example? Thank a lot!

**Comment by simplesmiler** [comment]
The issue was closed because it does not follow the [guideline](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines). We encourage you to ask usage questions on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).
