### ISSUE TITLE
A <template> bug in iOS 8.3 iPhone's Safari

### ISSUE THREAD

**Issue by lmk123** [vuejs/vue#3347]
### Vue.js version

1.0.26
### Reproduction Link

https://jsfiddle.net/lmk123/a54ccLLc/
### Steps to reproduce

 Use a **iOS 8.3** iPhone's Safari open the above link.
### What is Expected?

The "hi" should be appears.
### What is actually happening?

In iOS 8.3 iPhone's Safari, the "hi" not appears.

**Comment by chrisvfritz** [comment]
@lmk123 Thanks for reporting this. There's quite a lot going on in that example (e.g. `v-if` on a `<template>`, state change in a `ready` hook, `<template>` in a component slot, etc). Can you do some more work to isolate which of these specifically (or which combination) is causing the problem you're seeing?

**Comment by lmk123** [comment]
@chrisvfritz The two things combination causing the problem: `<template>` in a component slot and `v-if` on the `<template>`, then in iOS 8.3 Safari, the state change don't reactive to the DOM.

**Comment by xujiongbo** [comment]
It seems that `v-for` on `<template>` has the same problem too.

**Comment by keepwn** [comment]
`v-for` on `<template>` still has the same problem in 1.0.26. (I just tested in iOS 8.4)

**Comment by chenjishu** [comment]
hehe

**Comment by chenjishu** [comment]
我正在找素材哈哈哈哈开心吗

**Comment by hooraygith** [comment]
@chrisvfritz i meet the problem too, and i simplify it in here:  https://jsfiddle.net/xraLywqp/
