### ISSUE TITLE
In the console shows no validation error

### ISSUE THREAD

**Issue by stranger-ru** [vuejs/vue#3356]
**Documentation:** "When a prop validation fails, Vue will refuse to set the value on the child component, and throw a warning if using the development build."
http://vuejs.org/guide/components.html#Prop-Validation

**Code:**
```
<div id="test">
	<child msg="abc"></child>
</div>

Vue.component('child', {
	template: '<div>{{ msg }}</div>',
	props: {
		msg: Number
	}
})
	
var vm = new Vue({
	el: '#test',
})
```

**Result:** In console there is no errors and warnings!

**Comment by fnlctrl** [comment]
You need to enable debug mode first.
http://vuejs.org/api/#debug

**Comment by posva** [comment]
thanks @fnlctrl 😉

**Comment by stranger-ru** [comment]
enable on debug:

`
<div id="test">
    <child msg="abc"></child>
</div>

Vue.config.debug = true;

Vue.component('child', {
    template: '<div>{{ msg }}</div>',
    props: {
        msg: Number
    }
})

var vm = new Vue({
    el: '#test',
})
`
 In console there is no errors and warnings!

**Comment by posva** [comment]
@stranger-ru in that case, can you provide a jsfiddle with the reproduction, please?

**Comment by stranger-ru** [comment]
https://jsfiddle.net/49p7oz6c/2/

**Comment by posva** [comment]
Remember to use the development version (non min). Here's the repro: https://jsfiddle.net/ue1p5kxL/

A warning would be helpful. It already exists in Vue 2 but it doesn't in Vue 1. Let me give it a look 😄

**Comment by stranger-ru** [comment]
> If you change the library path Vue "https://npmcdn.com/vue/dist/vue.min.js" "https://npmcdn.com/vue/dist/vue.js" then it starts to work

> Remember to use the development version (non min). Here's the repro: https://jsfiddle.net/ue1p5kxL/

it doesn't always work, it can be seen in jsfiddle

Google Chrome 52.0.2743.82

**Comment by posva** [comment]
What do you mean? If you uncomment the line it works, otherwise no warning shows up, which is he issue here

**Comment by stranger-ru** [comment]
Oh, sorry, Yes, it works. 

Thanks!
