### ISSUE TITLE
image loading exception in a template... just see here and help me please!

### ISSUE THREAD

**Issue by iminif** [vuejs/vue#3357]
### Vue.js version
1.0.26

### What is actually happening?
Just see [here](http://www.iminif.com)

**Comment by fnlctrl** [comment]
Not related to vue... just visit [w3schools](http://www.w3schools.com/css/default.asp) and learn css please!

**Comment by JounQin** [comment]
First, it's not an issue of vue...
Second, there is an inline-style `height:200px` on `.bg-green` under `#block-b`.

**Comment by iminif** [comment]
So I see, thank you anyway! @JounQin
