### ISSUE TITLE
Failed to load plugin html: eslint-plugin-html

### ISSUE THREAD

**Issue by lianer** [vuejs/vue#3359]
compiler error on dev environment

windows server 2012
nodejs 6.2

![image](https://cloud.githubusercontent.com/assets/9332264/17270906/4422c4d2-56a0-11e6-9bc9-0118e97c3b33.png)

**Comment by sqal** [comment]
How is this vue problem? But have you installed this plugin? `npm i eslint-plugin-html` ?

**Comment by lianer** [comment]
Sorry, It's webpack problem
