### ISSUE TITLE
dynamic props to parent component's array element such as items[1]

### ISSUE THREAD

**Issue by seaify** [vuejs/vue#3362]
There is a component  'posting' which has props called items(array type), and pass single element to component 'tip'.

if item in component tip change, can it dynamic update posting component?

through 
```
        li is="tip" v-for="item in items" track-by="$index" :item["$index"]="item" :edit_mode="false"
```
?

**Comment by iagafonov** [comment]
`:item["$index"]` - what does it mean? If it should bind item1, item2, ... prop to item - it will not. Dynamic property binding is not supported right now.
`:item="item"` is enough if item is properly swapped with new item object inside items array like `items.splice(index, 1, newItem)`.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you can use `v-bind="{ 'prop-name': value }"`, but you can only use it for static prop name. You can try with ES6 syntax of computed field names, but that would only work in ES6 environment: `v-bind="{ [item[$index]]: item }"`.
