### ISSUE TITLE
表单控件双向绑定会忽略js对value的改变

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3363]
```
<input v-model="test"/>
```
如题，如果我用js修改了上述输入框的值,test并不会监听到变化，这个为什么没有实现呢？

**Comment by aweiu** [comment]
刚想了一下 ，ie低版本可以实现
其它浏览器就很难了，暂时没想到办法

**Comment by yyx990803** [comment]
这个从来都不支持。自己手动触发个 input 事件就行了。

**Comment by aweiu** [comment]
恩。还是想讨论一下，比如我写了一个校验插件，当输入框内容改变的时候出错提示消失
在输入框很多的时候手动触发会比较折磨人。。
不过因为使用的是您的框架，大部分输入框的值的改变是vue触发的。那么可不可以监听指定输入框的value绑定的数据呢？
比如 <input :value="test"> <input v-model="test2">
如果我能通过input获取到"test"和“test2”，从而去监听它们的变化也是可以的
vue可不可以获取到输入框绑定的数据呢？

**Comment by yyx990803** [comment]
用 watcher

**Comment by aweiu** [comment]
这个知道，关键是如何通过表单元素获取到需要watch的数据

**Comment by sutra** [comment]
我发现如果是这样：

```
<input v-model="testObj.test"/>
```

```
this.$set(this.testObj, 'test', 'hello world') // https://cn.vuejs.org/v2/api/#vm-set
```

input 输入框内的值就会变。
