### ISSUE TITLE
watcher performs differently (decide by datas type)  in components

### ISSUE THREAD

**Issue by chenzhuo1992** [vuejs/vue#3364]
### Vue.js version
2.0.0-beta5

### Reproduction Link
https://jsfiddle.net/wx9u6dkw/16/

### Steps to reproduce / What is actually happening?
Click the 1st <button>, it will NOT alert.
Click the 2nd <button>, it WILL alert by the watcher.
If data changes (Line 39) to number 1 or string '1', it will never alert.
(In Vue 1.0.26, it will never change even if ['1'], https://jsfiddle.net/wx9u6dkw/14/ )

**Comment by yyx990803** [comment]
``` js
1 === 1
[1] !== [1]
```
