### ISSUE TITLE
$vm.$delete('object.key') doesn't work

### ISSUE THREAD

**Issue by aristidesfl** [vuejs/vue#3368]
### Vue.js version
1.0.26

### Reproduction Link
http://jsbin.com/cavadiwosi/1/edit?html,js,console,output

### Steps to reproduce
`$vm.$delete('object.key')`
### What is Expected?
`$vm.object.key` should not exist
`$vm.$set('object.key', value)` seems to work fine

### What is actually happening?
`$vm.object.key` doesn't change

**Comment by Kingdaro** [comment]
`$set` and `$delete` are deprecated in the new version. Use `Vue.set` and `Vue.delete` instead.

```js
toggleRow: function(row) {
  key = row.id
  if (this.selectedRows[key]) {
    console.log('deleteRow: ', key)
    Vue.delete(this.selectedRows, key)
  }
  else {
    Vue.set(this.selectedRows, key, row)
  }   
}
```

**Comment by yyx990803** [comment]
Note the API only supports deleting the vm's own keys. Also, prefer Vue.delete.

**Comment by luckylooke** [comment]
@kingdaro vm.$set and $vm.delete does not seem to be deprecated in actual version 2.x https://vuejs.org/v2/api/#vm-set :)
