### ISSUE TITLE
Warning on unused resources

### ISSUE THREAD

**Issue by Kingdaro** [vuejs/vue#3369]
After refactoring, it's often possible that a computed property or component that was once needed is no longer required. And typoes are a thing, too. It'd be fantastic if Vue could detect if a computed property, method, component, etc. wasn't being used, and warned in the console if so. Maybe with a `strict` config flag, or similar?

Simple example when a warn should be triggered for data fields. The `value2` data field is unused.
```html
<template>
  <span>{{ value1 }}</span>
</template>

<script>
export default {
  data () {
    return {
      value1: 'Hello, world!',
      value2: 'unused'
    }
  }
}
</script>
```

Limitation: the component/instance might be using the resource inside its definition, and not in the template.
```html
<template>
  <span>{{ computedValue }}</span>
</template>

<script>
export default {
  data () {
    return {
      value: 'Hello'
    }
  },
  computed: {
    computedValue () {
      return this.value + ', world!'
    }
  }
}
</script>
```

Would it still be possible?

**Comment by yyx990803** [comment]
I don't think this is Vue's responsibility. Also a computed property may get used in non-template scenarios. Instead you can detect unused code with a coverage tool.
