### ISSUE TITLE
Vue 2 returns input value as string

### ISSUE THREAD

**Issue by k9** [vuejs/vue#3370]
### Vue.js version
2.0.0-beta.6

### Reproduction Link
https://jsfiddle.net/j9kp8jfe/2/

### Steps to reproduce
Slide the slider

### What is Expected?
I would expect `xyz` to be a number so `+` would perform addition, as in Vue 1 https://jsfiddle.net/j9kp8jfe/1/

### What is actually happening?
`xyz` is a string, so `10` is being concatenated. Note that `number` attribute is being used https://vuejs.org/guide/forms.html#number

**Comment by yyx990803** [comment]
Number is now a modifier, use v-model.number instead.
