### ISSUE TITLE
Using polymer component in vue component error

### ISSUE THREAD

**Issue by yutingzhao1991** [vuejs/vue#3372]
> Vue.js template engine is DOM-based and uses native parser that comes with the browser instead of providing a custom one.

Because of that, template will parse error when I use a polymer component or a webComponent which created by `document.registerElement`.

See code in vue:

https://github.com/vuejs/vue/blob/7059c15d906f33fe993c505f9b8edfe860319b35/src/parsers/template.js#L119

```js
    var node = document.createElement('div')

    node.innerHTML = prefix + templateString + suffix
    while (depth--) {
      node = node.lastChild
    }
```

In my case, after `node.innerHTML = prefix + templateString + suffix`  Node.innerHTML != prefix + templateString + suffix.

Any solution for this issue?

**Comment by yyx990803** [comment]
1. There is no way around this in 1.x
2. It should work in 2.0 if you use it in string templates
3. It seems the custom elements you are using is not using shadow DOM, and it's a bad idea to mix that with Vue.
