### ISSUE TITLE
vm.$set will give error message. But Vue.set will work well.

### ISSUE THREAD

**Issue by vrbvillor** [vuejs/vue#3373]
```html
<div class="cart"></div>
```
```javascript
var cart=new Vue({
    el:".cart",
})

cart.$set("absolute",123);
```

It will send an error message in the console.  Why can't I use `instance.$set` to give the instance a new attribution?

**Comment by Kingdaro** [comment]
The property should have a default value in `data`. The warning is there so you don't accidentally set a property that shouldn't exist.

```js
var cart = new Vue({
  el:".cart",
  data: {
    absolute: 0
  }
})
cart.$set("absolute",123)
```
This should work fine.

**Comment by vrbvillor** [comment]
But in the tutorial, it says 
> However, there are ways to add a property and make it reactive after an instance has been created.

[http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats](http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats)

**Comment by LinusBorg** [comment]
Well, it's a warning message, not an error (and won't show up in production). 

And the warning explains why it's better to properly initialize your data:

> You are setting a non-existent path "absolute" on a vm instance. Consider pre-initializing the property with the "data" option for **more reliable reactivity and better performance**.

While $set() *works*, it's better to pre-initialize your data.

**Comment by vrbvillor** [comment]
OK I see , but the warning message should use the yellow color printed by console.warn........
