### ISSUE TITLE
[BUG in Vue 2.0]<slot></slot> not update properly

### ISSUE THREAD

**Issue by HeChenTao** [vuejs/vue#3374]
### Vue.js version
2.0.0-beta.5

### Reproduction Link
http://jsbin.com/ziluqaxege/1/edit?html,js,console,output

### Steps to reproduce
1. type 9  in the `<input>`
2. the rendered items is not right, but the console out is right,  the `<slot></slot>` doesn't update properly.

### What is Expected?
The `<slot></slot>` should be sync  with the parent. 

### What is actually happening?
The `<slot></slot>` can not update.

**Comment by abinadave** [comment]
just use Angular JS. it is developed by google.
ALL IN ONE FRAMEWORK !!

**Comment by prog-rajkamal** [comment]
It works when I add `:key="item.key"` in `<item>` http://jsbin.com/ficufaruyi/edit?html,js,output

**Comment by HeChenTao** [comment]
Thanks.  I tried `key="item.key"`, it doesn't works. So the right usage is `:key="item.key"`,  my fault.

**Comment by prog-rajkamal** [comment]
@HeChenTao If you recently started learning vuejs, then I strongly suggest you to use `v-bind:key` and `v-on:event` in place of shorthands `:key` and `@event`.

**Comment by HeChenTao** [comment]
Thank you for your advice. I use vuejs for several months. It's great.
