### ISSUE TITLE
Reusing childs in Render Functions error

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3376]
### Vue.js version
2.0.0.beta-6

### Reproduction Link
https://jsfiddle.net/miljan/mx3tfskL/

### Steps to reproduce
Click on the links and watch the console log.

### What is Expected?
To output `Clicked` for each one.

### What is actually happening?
Only does so for the first Menu, for the second throws an `Uncaught TypeError: o.fn is not a function` error.

**Comment by chrisvfritz** [comment]
Note: when `Item` is not a functional component, then the first `<ul>` instead renders with no children.

**Comment by yyx990803** [comment]
This is expected, you **should not** be reusing the same vnodes in the same render tree.

**Comment by chrisvfritz** [comment]
@yyx990803 Should we emit a warning if this is attempted - at least within the same array of children?

**Comment by yyx990803** [comment]
@chrisvfritz it's nice to have, but it would add quite some runtime cost. Not sure if it's worth it. Good to mention it in the render function guide though.
