### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

### ISSUE THREAD

**Issue by duruitang** [vuejs/vue#3378]
I double clicked this:
`<input name="num" class="box-input" type="number" pattern="[0-9]*" placeholder="">`

chrome console:
`Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.`

| Q                | A
| ---------------- | ---
| vue version      | 1.0.26

**Comment by posva** [comment]
Hello, there's nothing related to Vue in what we have given 😓 

Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by duruitang** [comment]
It's strange...
