### ISSUE TITLE
'0' value BUG @vue2.0 beta-6

### ISSUE THREAD

**Issue by ije** [vuejs/vue#3381]
```javascript
Vue.extend('id', {
    data: {
        template: '<li :class="{current: current == index}" v-for="(val, index) in list">{{val}}</li>',
        current: -1;
        list: []
    }
})
```

in this example, when `current=1~n`, the `<li>` can get the **current class**, but if set `current = 0`, the **current class** goes away!

**Comment by posva** [comment]
Can you provide a jsfiddle with the issue, please?
⚠️  The template should be outside of the `data`

**Comment by LinusBorg** [comment]
Also, `Vue.extend()` only takes one argument: an Object. So `Vue.extend('id', { ... })` is invalid syntax.

**Comment by ije** [comment]
so srroy, i think it's my mistake.
i'm trying to run a simple example ([jsfiddle](https://jsfiddle.net/ijex/wcgcwokd/12/)) which look like my real project, but is't running prefectly! 
i'm testing to upgrade my project with vue 2.0 (beta-6) and vuex (1.0 rc2).
thanks guys.
