### ISSUE TITLE
Transition inside forms crashing in Safari 9.1.1

### ISSUE THREAD

**Issue by cemelo** [vuejs/vue#3383]
### Vue.js version
2.0.0-beta.6

### Reproduction Link
http://jsbin.com/miyoru/edit?css,js,output

### Steps to reproduce
In the jsbin above, click in the `Toggle` button.

### What is Expected?
An animation expanding the input field.

### What is actually happening?
The animation starts and then the application crashes.

PS: if you remove the `<form>` tag, the animation works accordingly.

**Comment by yyx990803** [comment]
This is not a Vue bug. Safari seems to treat the `<button>` inside the form as the submit button by default, so it submits the form and reloads the page.

**Comment by vuchl** [comment]
yes, if you add [`v-on:submit.prevent`](http://vuejs.org/guide/events.html#Event-Modifiers) to the form it stays visible

**Comment by iagafonov** [comment]
<button> without type="button" considered as the submit button by default in any browser
