### ISSUE TITLE
confused v-for in component,a strange problem i met

### ISSUE THREAD

**Issue by yiyunzhi** [vuejs/vue#3384]
### Vue.js version
1.0.26

###
that's what i met.i write a tiny component named 'alert', it's look like so.
```javascript
<template>
    <div class="uk-alert" data-uk-alert >
        <a class="uk-alert-close uk-close"></a>
        <p>{{message.body}}</p>
    </div>
</template>
<script>
    export default{
        data(){
            return {}
        },
        props: {
            message: {
                type: Object
            }
        },
        ready: function () {
        }
    }
</script>
```
and then i used it in my app.vue like this
```javascript
  <app-alert :message="message" v-for="message in messages" ></app-alert>
```
and the script of messageMixin.js like this
```javascript

var messageMixin = {
	data: function () {
		return {
			messages: [],
		}
	},
	events: {
		'app_message_update': function (msg) {
			this.messages.push(msg);
		}
	}
};
export default messageMixin;

```
i use mixin option into the app.vue.
as you see i have defined the messages as a empty array,and a event listener.i send the new message object use DISPATCH method in other component ,and in this mixin listen this value,the strange thing comes.
1situation:use above <app-alert> tag  not working and got  a error
```javascript
  Uncaught TypeError: Cannot read property 'childNodes' of undefined,
  Uncaught Error: [vue] async stack trace
```
the error in this line
```javascript
this.messages.push(msg);'!
```
2situation:no <app-alert> tag in app.vue but go straight write the html  in <template> tag with v-for,
```javascript
<template v-for="message in messages" >
<div class="uk-alert" data-uk-alert >
        <a class="uk-alert-close uk-close"></a>
        <p>{{message.body}}</p>
    </div>
</template>
```
that's works good.

maybe its my problem,but i don't really know where and what happened. thanks

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).

I doubt the messages variable exist. Can you define it in the Vue instance using the app-alert component?

**Comment by iagafonov** [comment]
can not reproduce.
it works: https://jsfiddle.net/v4gaoqyd/

**Comment by yiyunzhi** [comment]
yes,that works,please add this.message.push(some object
) in ready hook of app.vue,then you will see the errors.:)

**Comment by iagafonov** [comment]
@yiyunzhi 
https://jsfiddle.net/v4gaoqyd/4/ - works in my browser
