### ISSUE TITLE
[2.0.0-beta.6] Bug - Passing string to v-html div doesn't render

### ISSUE THREAD

**Issue by Async0x42** [vuejs/vue#3385]
### Vue.js version
2.0.0-beta.6

### Reproduction Link
Vue 1.0 (working): https://jsfiddle.net/jv3w42so/1/
Vue 2.0 (broken): https://jsfiddle.net/fyb6cas4/1/

### What is Expected?
Binding to a string containing html should render with v-html (like {{{ }}} would in 1.0)

### What is actually happening?
The string text is outputted with no html rendering

I didn't see any documented changes other than {{{ }} being depreciated and to use v-html, so I'm assuming this is a bug.

**Comment by yyx990803** [comment]
Wrong syntax. Use v-html="html"

**Comment by Async0x42** [comment]
Ah, thanks!

**Comment by voronianski** [comment]
@yyx990803 `v-html` is not working in jsx.

**Comment by yyx990803** [comment]
@voronianski it doesn't. Use `{ domProps: { innerHTML: '...' }}`
