### ISSUE TITLE
  vue模板渲染问题  Vue template rendering problem

### ISSUE THREAD

**Issue by humorHan** [vuejs/vue#3387]
I want to know the Vue render loop template is not the time to remove node, because I have encountered a problem, that is, Vue with rich text editor umeditor if circular data is retrieved from the server while performing initialization umeditor, this time initialization umeditor invalid, but if finished rendering in the initialization

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by humorHan** [comment]
Yes, I am feeling whether Vue should add similar data to drive an attempt to complete the hook function that can solve all of the above problems。
But I'm still going to put this issue to the community to determine what!
Thank you for answering
