### ISSUE TITLE
Vue.partial is chained?

### ISSUE THREAD

**Issue by earlymeme** [vuejs/vue#3388]
Can I use partial as follow:
`
Vue
    .partial('partial', '<div></div>')
    .partial('partial1', '<div><a></a></div>');

`

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
