### ISSUE TITLE
Firefox warning TypeError: mutating the [[Prototype]]...

### ISSUE THREAD

**Issue by cdekok** [vuejs/vue#339]
On this line firefox gives a warning: https://github.com/yyx990803/vue/blob/fe996b388971b014279b1f90df26ef95d8b00f05/dist/vue.js#L2458

TypeError: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by paperscissors** [comment]
i'm noticing integration with components on firefox 30 is extremely slow--- it keeps spitting out this error and spinning.

works fine on webkit browsers. and it's a small set of stuff it's rendering.

**Comment by yyx990803** [comment]
Why are you using FF30 anyway?... it's like 15 versions behind...
