### ISSUE TITLE
Feature Request: Better warning message when a dynamic component is a fragment instance 

### ISSUE THREAD

**Issue by brendanbowidas** [vuejs/vue#3390]
When using `<component :is>` syntax, the fragment instance warning message `Attribute 'something' is ignored on component '<component>' because the component is a fragment instance` is confusing if I have multiple dynamic components in my app. I don't know which component it is coming from.
Maybe the compileRoot method can check whether the tagName is 'component' and if so, use `options.name` in the error message instead of `options.el.tagName`. I will submit a PR for this if you guys think this is a valid issue/solution

Thanks!

**Comment by yyx990803** [comment]
Sounds good, a PR would be appreciated!

**Comment by Squawk09** [comment]
Hello, 

I am interested in resolving this issue.  Can it be marked as in progress?

**Comment by posva** [comment]
@Squawk09 It's enough to say you're on it 😄

**Comment by Squawk09** [comment]
@posva  cool, thanks!

**Comment by M-ZubairAhmed** [comment]
@Squawk09 are you still working on this ? or do you want me to look into this.

**Comment by yyx990803** [comment]
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.
