### ISSUE TITLE
Slot in children not sync right

### ISSUE THREAD

**Issue by HeChenTao** [vuejs/vue#3391]
### Vue.js version
2.0.0-beta.5

### Reproduction Link
http://jsbin.com/jehoxayuyo/1/edit?html,js,output

### Steps to reproduce
type in the input. In vue 2.0, it doesn't show the input value. And if you switch to Vue 1.x, edit the html's head, it shows the input value.

### What is Expected?
show the input value.

### What is actually happening?
In Vue 2.0, it doesn't show the input value.

**Comment by yyx990803** [comment]
fixed in b5b963f51df1fa3124cd8a9846be5455408bc52a and related commits.
