### ISSUE TITLE
Weird comportement with data

### ISSUE THREAD

**Issue by lionel-bijaoui** [vuejs/vue#3392]
### Vue.js version
1.0.26
### Reproduction Link

Click on the buttons alternatively. Reset will fail in the weird example.
Working example : http://www.webpackbin.com/4JtOOq6db
Weird example : http://www.webpackbin.com/EyVvd96u-
### Steps to reproduce
Initialize `data` from an existing object, and try to use this object normally later.
```js
var myobject = {
   some: 'properties'
}
export default {
   data() {
       return myobject;
   },
   methods: {
       _checkSomeData() {
           console.log(myobject.some); // will fail to get the data :(
       }
   }
};
```
When I use a variable (object) in the return function of `data`, Vue seem to change the original variable (object) and add it properties like `get` and `set` to every value. It is no longer a simple object and break any other usage.
Since this variable is only returned, it shouldn't change, no ? I'm not extremely good with javascript, so maybe this is perfectly normal, but I thought that the return was acting as a factory, and thus making another copy for Vue, leaving the original intact.
Of course, there is an easy solution, but I'm very surprised by this, and I want to make sure and understand why it is doing that.
Sorry if it is a non issue for the community, and thank you for your help anyway.
### What is Expected?
The original object should remain a simple object.
### What is actually happening?
The original object is no longer a simple object, but is now changed.

**Comment by posva** [comment]
Hi!

Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).

In Javascript objects are passed by reference, so doing `return myObject` shares the object
You can instead create a new object using `myObject` like the first example. In ES6 you can do `return {...myObject}`
