### ISSUE TITLE
About Ie11 not support object.assign

### ISSUE THREAD

**Issue by fangsj** [vuejs/vue#3394]
Hi!
 I find IE11 not support object.assign, i user jquery.post get data, then response data I want to add Vue'$data

**Comment by abdullah** [comment]
Please, ask an answer with issues guide. jsifiddle,codepen etc.. If you ask question with this way don't answer your question , See [contributing](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md )
Thanks.

**Comment by sqal** [comment]
Not related to Vue. But to anwer your question, just add Object.assign polyfill on your page, there is many ways you can do that, one of them can be https://polyfill.io/v2/docs/

**Comment by yyx990803** [comment]
This has nothing to do with Vue, just use a polyfill.
