### ISSUE TITLE
Transitions trigger too often - currently using 2.0.0-beta7

### ISSUE THREAD

**Issue by JochenHoertreiter** [vuejs/vue#3395]
Looking at this [jsFiddle](https://jsfiddle.net/bv30bspo/2/)
you will see a &lt;transition&gt; around a simple div that should fade in/out when you click on 'Show'/'Hide'
That works correctly!
But changing the divs class from 'red' to 'black' also let the transition trigger.

Same thing happens if you have nested v-show elements in the transition div.
Clicking on 'Nested element show'/'hide' triggers the transition.
See that example in this [jsFiddle](https://jsfiddle.net/ogd2afqw/2/)

Same thing happens when an inner elements class is changing like in the first fiddle.
By changing the inner elements color class the whole divs transition activates.
See that one in this [jsFiddle](https://jsfiddle.net/apks43qm/1/)

**Comment by prog-rajkamal** [comment]
Please ensure that jsfiddle link is working.
