### ISSUE TITLE
<transition> can't not use in jsx

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#3396]
### Vue.js version
2.0.0 beta.6

### Steps to reproduce
```
render() {
    return (
<transition name="md-fade-bottom">
  <div class="box">
      content
  </div>
</transition>
    )
}
```
### What is actually happening?
it will render nothing, how can i use transition in jsx?

**Comment by yyx990803** [comment]
If you are using the jsx babel plugin 3.0, make sure to upgrade to beta.7.

**Comment by JounQin** [comment]
+1, and the error message is `vue.js:2249 [Vue warn]: A component's children should be a function that returns the children array. This allows the component to track the children dependencies and optimizes re-rendering.`.

Is there an example of using transition in jsx?

**Comment by yyx990803** [comment]
As I said, **make sure to use `vue@^2.0.0-beta.7` with `babel-plugin-transform-vue-jsx@^3.0.0`**.

**Comment by JounQin** [comment]
Of course I've upgraded them and I removed and reinstalled all the (dev)dependencies.

**Comment by yyx990803** [comment]
Then I'm afraid I can't reproduce the problem.
