### ISSUE TITLE
server side render with chinese encoding

### ISSUE THREAD

**Issue by nyrf** [vuejs/vue#3397]
### Vue.js version
2.0.0-beta.7

### Reproduction Link

`demo.js`

```javascript
const Vue = require('vue')
const renderer = require('vue-server-renderer').createRenderer()
const vm = new Vue({
  render (h) {
    return h('div', '中文')
  }
})
renderer.renderToString(vm, (err, html) => {
  console.log(html) // -> <div server-rendered="true">中文</div>
})

```

### Steps to reproduce

```
node demo.js
```

### What is Expected?

```html
<div server-rendered="true">&#x4E2D;&#x6587;</div>
```

### What is actually happening?

```html
<div server-rendered="true">中文</div>
```

**Comment by yyx990803** [comment]
Why is this necessary?

**Comment by yyx990803** [comment]
FYI, the renderer assumes UTF-8 encoding so it only encodes entities that may interfere with HTML parsing. Encoding all special chars will add extra cost during SSR even if it's not needed.

If you need to encode special chars you can write a transform stream yourself and pipe the response through it before sending back to the browser.

**Comment by nyrf** [comment]
When use ssr, the html page source code would't show chinese. 
@yyx990803 Ok, thanks.
