### ISSUE TITLE
how can i use custom directive in jsx?

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#3398]
### Vue.js version
2.0.0 beta.7

### Steps to reproduce
```
return (
   <div class="el-autocomplete" v-clickoutside={this.handleBlur}>
          {input}
      <transition name="fade-bottom">
            {suggestions}
      </transition>
   </div>
);
```
### What is actually happening?
the clickoutside directive is do not work

**Comment by yyx990803** [comment]
Moved to https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/15
