### ISSUE TITLE
改变数据了但是VUE没有监听 到怎么办

### ISSUE THREAD

**Issue by yibbay** [vuejs/vue#3401]
如当一个模块ready 后，我在document.body上监听点击事件，我在这个模块要实现doc的隐藏，这个doc通过v-show绑定，但是我document.body点击事件后，改变了绑定的值为false，数据也变化了，可以vue没有监听到这个变化，也就是说doc没有隐藏

**Comment by yibbay** [comment]
dom

**Comment by yibbay** [comment]
简单说就是，通过点击页面任何地方，实现某一模块的数据的改变,而且vue能监听 到

**Comment by yyx990803** [comment]
请仔细阅读开 issue 的要求。没有重现的 bug 是不会有人修的。

**Comment by yyx990803** [comment]
不符合要求并没有及时修正，请在有重现之后重开。
