### ISSUE TITLE
Vue js broadcast not working

### ISSUE THREAD

**Issue by Corstiaan84** [vuejs/vue#3402]
I have this Vue instance:

```
var vm = new Vue({
    el: '#app',
    data: {
        user: {
            email: '',
            password: '',
            passwordconfirm: '',
            bars: {},
            authentication_token: '',
            id: 0
        }
    },
    components: {
        dashboard: dashboard
    },
    events: {
        'onLoginSuccesfull': function(user) {
            // do stuff with user obj
            this.$broadcast('onUserLoggedIn');
        }
    }
}
```

It has a 'dashboard' component:

```
var dashboard = Vue.extend({
    template: '#dashboard',
    data: function() {
        return {
            currentPage: 'main'
        }
    },
    components: {
        'dashboard-mainpage': dashboardmainpage
    }
    events: {
        'onUserLoggedIn': function() {
            alert('I should be firing bu I am not!');
        }
    }
});
Vue.component('dashboard', dashboard);
```
The 'dashboard' has a 'dashboard-mainpage' component:

```
var dashboardmainpage = Vue.extend({
    template: '#dashboard-mainpage',
    methods: {
        loadData: function() {
            this.$http.get('/dashboard/main.json', {
                authenticity_token: window._token
            }).then(function(response) {
                var data = JSON.parse(response.body);
                console.log(data);
            }, function(response) {
                console.log(response);
                this.$dispatch("onRequestUnauthorized");
            });
        }
    },
    events: {
        'onUserLoggedIn': function() {
            alert('I should be firing as well but I am not!');
            this.loadData();
        }
    }
});
```

The problem is that when the 'onLoginSuccesfull' event is triggered on the main Vue instance, the subsequently broadcasted 'onUserLoggedIn' on the 1st and 2nd level descendant are not triggered, when calling 'this.$broadcast('onUserLoggedIn');'.

I know that event callbacks must return true to keep propagating down the chain but the first event callback (on 'dashboard') is not even triggered.

What am I missing?

**Comment by marco-a** [comment]
Just a quick side note:

`Vue.component('dashboard', dashboard);` will globally register the component so

```
components: {
    dashboard: dashboard
}
```

Is either doing something funny or is just redundant.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
