### ISSUE TITLE
I can't set a setter as function?

### ISSUE THREAD

**Issue by oknoorap** [vuejs/vue#3404]
I got error ``Invalid setter expression``, I want to make dynamic model.

```
<input v-model="model('key')" />
```

```javascript
const App = new Vue({
    computed: {
           model: {
                 get () {
                     return (key) => // get object based on key
                 },

                 set (value) {
                     return (key, value) => // set object with given key and value
                 },
           }
    }   
})
```

Is this possible to make this work?

**Comment by yyx990803** [comment]
That's not how v-model / computed works... you are using both incorrectly. Closing and please redirect the question to Gitter / forum.

**Comment by oknoorap** [comment]
yeah I know, but I have large objects in iframe, I can't set model directly when iframe doesn't loaded yet. Hmm I can't explain details here. But in iframe there is dynamic element, when I added new element, it's has a new properties. So this input can handle all those elements.
