### ISSUE TITLE
Two strange find when i begin to use vue.js

### ISSUE THREAD

**Issue by inxi-pc** [vuejs/vue#3408]
When i create a test application by using webpack & vue-loader,  everything is ok after i created a main.js, some components, webpack.config.js, and etc.

But when i integrate all components into index.html by using customer component tag, like this:

```html
<html>
    <body id="app">
        <script src='build.js'></script>
        <my-header></my-header>
        <my-todo></my-todo>
        <my-footer></my-footer>
    </body>
 </html>
```
My main.js, import all components, and register them, then i can use them in index.html.

```javascript
import Vue from 'vue'
import header from './components/header.vue'
import footer from './components/footer.vue'
import todo from './components/todo.vue'

new Vue({
    el: '#app',
    components: {
        "my-header": header,
        "my-footer": footer,
        "my-todo": todo
    }
})
```

todo component:

```javascript
<style>

</style>

<template>
    <div>
        <input v-model="newTodo" v-on:keyup.enter="addTodo">
        <ul>
            <li v-for="todo in todos">
            <span>{{ todo.text }}</span>
            <button v-on:click="removeTodo($index)">X</button>
            </li>
        </ul>
    </div>
</template>

<script>
export default({
    data: function () {
        return {
            newTodo: "",
            todos: [
                { text: "Add some todos" }
            ],
        }   
    },

    methods: {
        addTodo: function() {
            var text = this.newTodo.trim();
            if (text) {
                this.todos.push({text: text})
                this.newTodo = "";
            }
        },

        removeTodo: function(index) {
            this.todos.splice(index, 1);
        }
    }
})
</script>

```
Everything is fine, but the strange thing is i saw my page has no any content, it is blank! No tag change, no logic happen!

![2 pic](https://cloud.githubusercontent.com/assets/8216273/17474348/09b15036-5d88-11e6-98b7-1b67bdbfa880.jpg)

After i try many failed ways, i replace script place, it is before components tag before, and i write it after components tag, everything is ok! What is happened? 

I guess if is the Vue render and parse mode issue? If i set the script before components, the script dont find the template to replaced, if i write after components, it can be process correctly?

**Comment by inxi-pc** [comment]
Additional, i found another bug, if i dont set any tag in component, the programmer will report issue "build.js:15900 Uncaught TypeError: Cannot read property 'tagName' of null"

![3 pic](https://cloud.githubusercontent.com/assets/8216273/17474585/392e18de-5d89-11e6-9fd3-e52587db1240.jpg)

My blank template component header or footer:

```javascript
<style>

</style>

<template>

</template>

<script>
export default {

}
</script>

```

when i added the any tag in template, the issue disappear. is it a bug for vue?

**Comment by sqal** [comment]
You have export syntax error. It should be 

```
export default {}
```

not (no parentheses)

```
export default ({})
```

Don't you have any webpack errors in the terminal? And btw. since it's not a Vue issue, you should ask that kind of questions on official forum, gitter or stackoverflow.

**Comment by inxi-pc** [comment]
@sqal

```javascript
<style>

</style>

<template>
    <div>
        <input v-model="newTodo" v-on:keyup.enter="addTodo">
        <ul>
            <li v-for="todo in todos">
            <span>{{ todo.text }}</span>
            <button v-on:click="removeTodo($index)">X</button>
            </li>
        </ul>
    </div>
</template>

<script>
export default{
    data: function () {
        return {
            newTodo: "",
            todos: [
                { text: "Add some todos" }
            ],
        }   
    },

    methods: {
        addTodo: function() {
            var text = this.newTodo.trim();
            if (text) {
                this.todos.push({text: text})
                this.newTodo = "";
            }
        },

        removeTodo: function(index) {
            this.todos.splice(index, 1);
        }
    }
}
</script>
```
Removed (), but if i write script before customer components, also dont have any thing! no console error.

**Comment by inxi-pc** [comment]
![5 pic](https://cloud.githubusercontent.com/assets/8216273/17475677/aea198a2-5d8e-11e6-9f93-60a14dc35aff.jpg)
![4 pic_hd](https://cloud.githubusercontent.com/assets/8216273/17475679/b079479c-5d8e-11e6-97b5-e3deb31d9306.jpg)

**Comment by sqal** [comment]
Can you do this:

```
import todo from './components/todo.vue'

console.log(todo)

```

and see how te import looks, maybe you have some issue with vue-loader

**Comment by inxi-pc** [comment]
@sqal 

Sir, you are right, it is true vue component. But how to check vue-loader, because i dont set more about vue-loader, only  match file setting.

![6 pic_hd](https://cloud.githubusercontent.com/assets/8216273/17475960/16e5d83c-5d90-11e6-8884-54d24a3a9031.jpg)


```javascript
module.exports = {
    entry: './src/main.js',
    output: {
        path: __dirname + '/static',
        filename: 'build.js'
    },

    module: {
        loaders: [
            {
                test: /\.vue$/, // a regex for matching all files that end in `.vue`
                loader: 'vue'   // loader to use for matched files
            },
            {
                test: /\.js$/,
                loader: 'babel-loader', // Enable es6 support by babels
                exclude: /node_modules|vue\/dist|vue-router\/|vue-loader\/|vue-hot-reload-api\//
            }
        ]
    },
    
    babel: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
    }
}
```

**Comment by sqal** [comment]
what version of vue & vue-loader are you using?

**Comment by inxi-pc** [comment]
@sqal 
"vue-loader": "^8.5.3"

Yes, move it to the end page is successful. This is my problem, why i must move it to the end page?

**Comment by sqal** [comment]
becouse Vue doesn't wait for DOM to finish loading (doesn't listen to DOMContentLoaded event) so if you put script with your app before anything else, DOM is not completely loaded yet and Vue can't find required components

**Comment by inxi-pc** [comment]
@sqal 
It is great! i understand.
