### ISSUE TITLE
Variable not accessible in IE11

### ISSUE THREAD

**Issue by mewejo** [vuejs/vue#3410]
Hi,

I have a Vue app setup which is searching for domain names for purchase. Basic flow is:

1. Setup the list of domains to search for
2. Render a table of the domains, with loading status
3. Adjust the status to success as and when the domain results come in.

My problem is that in the results, we have price sets for each registration period. I cycle through them with a for loop, and call it `price_set` - but `price_set.term` is not accessible in IE11, but it is in every other major browser. Even tried adding a `v-if` to the statement where it's used to no success.

JS fiddle setup, bit messy as I've had to rip it out of our app and get it running without the rest of the app but the issue still persists.

http://jsfiddle.net/5sH6A/583/

Click the search button and wait 4 seconds, one second per domain, and you'll see the results. This is different in production and works as expected. If you remove the `v-if` on the table, and debug `VueApp.step_4_domain_results` you'll see the table should show.. setting `step_4_show_all_tlds` will force a re-render.

I can't seem to get the error out of IE now, but the error I was getting was: "Unable to get property 'term' of undefined or null reference"

You'll see the drop downs in the price column are empty in IE11 but not in Firefox.

### Firefox
![7be2ac4d](https://cloud.githubusercontent.com/assets/1097093/17481360/a56cd57c-5d74-11e6-9ce7-1e8f4ba00183.png)

### IE11
![037f11b9](https://cloud.githubusercontent.com/assets/1097093/17481359/a5633a8a-5d74-11e6-9e34-fd5718baddc5.png)

Hope someone can help.

Thank you,

Josh

**Comment by yyx990803** [comment]
I'm afraid the issue description and the fiddle is still very hard to understand. Please try to narrow down the reproduction and provide a clearer description of what exactly is expected.

**Comment by mewejo** [comment]
Hi,

You see in the Period/Price selects, IE just shows `Years - £` where as what should be shown is `2 Years - £10.00` for example. The variables are not available for use in IE11 like they are in Firefox and other browsers.

**Comment by mikekidder** [comment]
@mewejo the issue is not with Vue.js but IE11, I believe, attempting to remove tags between the select/option..  Polymer has/had similar issue... https://github.com/Polymer/polymer/issues/1735

**Comment by mikekidder** [comment]
@mewejo http://jsfiddle.net/sfua0m4b/1/  -- sample working in IE11 with a minimal amount of refactoring
