### ISSUE TITLE
Slot as template

### ISSUE THREAD

**Issue by Grafikart** [vuejs/vue#3412]
I noticed some people have problems using slots with sub component. 

## The problem

Let's take a simple example where I have VueJs binded on body. Within my HTML I have this code

```html
<tabs>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
</tabs>
```

To make this code work I need to register 2 components globally `tabs` (that would use `<slot>` within his template) and `tab`

But sometimes we don't want to do that. We want to register `tab` locally on `tabs` component so people won't have to import every subcomponents used within a specific component.

## Solution

The current behaviour is logic and shouldn't be replaced. The idea would be to add a way of telling VueJS : "Do not parse the content of my componen; inject it in the template and parse it using local registered component"

For instance we could have a directive for this use-case

```html
<!-- MyComponent.vue -->
<template>
  <tabs>
    <slot v-local>
      <tab title="hello">lorem ipsum</tab>
      <tab title="hello">lorem ipsum</tab>
      <tab title="hello">lorem ipsum</tab>
    </slot>
  </tabs>
</template>

<script>
import Tabs from './Tabs.vue'
// No "Tab" component registered here

export default {
   components: { Tabs }
}
</script>
```

```html
<!-- Tabs.vue -->
<template>
    <div class="tabs"><slot></slot></div>
</template>

<script>
import Tab from './Tab.vue'
// Tab is registered here and would be interpreted within this template

export default {
   components: { Tab }
}
</script>
```

With this directive, the Tabs template would be populated with the raw content. Then VueJS would try to resolve every component. The main benefit would be to be able to package a component that rely on subcomponents without having to tell to the end-user to import everything. It would also allow this kind of sorcery : 

```
<!-- It would be possible to use 2 components that use the same name for subcomponents without conflict  -->
<tabs>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
</tabs>
<panel>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
    <tab title="hello">lorem ipsum</tab>
</panel>
```

## Caveat

- This feature would make the code less easy to understand since we can use component without having them declared anywhere in our code. 
- I don't know how VueJS is build internally but it could be a pain to preserve some code from the parser and populate template differently for some components
- This is a specific use case scenario, is it REALLY necessary ? A good naming convention could avoid conflic use `tabs-item` instead of `tab` as component name.

**Comment by yyx990803** [comment]
I really don't think this makes sense. Vue template scoping is lexical similar to how JavaScript works: components are imported where they are used. The only benefits here is saving a few import statements for the end user - which doesn't seem like a reasonable tradeoff (convenience vs. correctness).
