### ISSUE TITLE
xxx.vue 如何 配合 slm 使用？（基于webpack）

### ISSUE THREAD

**Issue by noman798** [vuejs/vue#3413]
slm 代码库库地址 https://github.com/WealthBar/slm-loader

webpack配置如下

          {
                test: /\.vue\.slim$/,
                loaders: ["vue", "slm"]
          }

报错

ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
  at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/app.vue.slim 4:14-213

ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
  at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
 @ ./src/vue/app.vue.slim 3:17-185

ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
  at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
 @ ./src/vue/app.vue.slim 8:19-132

PS：为了有朝一日，汉语可以类似英文取代那样拉丁文成为新的世界通用语。我通常尽量使用中文。个人的民族自豪感，勿扰。

**Comment by yyx990803** [comment]
为了更好地维护项目，我通常使用英文，勿扰。

**Comment by yyx990803** [comment]
As for your issue, it is a question, so it should be asked in Gitter or on the forum, not via an issue. Even if you prefer Chinese, you should have read the issue reporting guidelines.
