### ISSUE TITLE
:class behaviour changed between patch version

### ISSUE THREAD

**Issue by thammin** [vuejs/vue#3416]
### Vue.js version
1.0.19 ~ 1.0.26

### Reproduction Link
`v1.0.13`
https://jsfiddle.net/thammin/ddw05t83/3/

`v1.0.26`
https://jsfiddle.net/thammin/70mc1pr1/8/

I found that the behaviour of `:class` had changed after https://github.com/vuejs/vue/pull/2540 is patched.
Maybe we could add tests to cover this behaviour?

**Comment by yyx990803** [comment]
This is a behavior change, but the latest behavior is the "fixed" behavior, because it follows a simple rule: a static `class` means that class will always be there.

If you want to programmatically control the presence of `foo`, you shouldn't have it as a static class in the first place.

**Comment by thammin** [comment]
Thanks for the clear reply about which behavior is correct and the beautiful project you had worked! 
Btw I just thought that this could be add to the test since it changed after https://github.com/vuejs/vue/pull/2540.
