### ISSUE TITLE
transition和v-show/v-if搭配有bug

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3418]
代码如下：
```
<template>
    <div :class="['modal-backdrop', 'fade']" transition="modal" v-if="isShow"></div>
</template>
<script>
  import vue from 'vue'
  vue.transition('modal', {
    enterClass: 'in'
  })
  export default{
    props: ['isShow', 'title']
  }
</script>

```
如果是“v-if”，isShow = false 的时候那个div并不会被移除
如果是"v-show"，isShow = false 的时候那个div并没有 display: none

**Comment by yyx990803** [comment]
请给出完整重现。

**Comment by aweiu** [comment]
@yyx990803 
[jsfiddle:查看完整重现](https://jsfiddle.net/orvmjfx7/3/)

**Comment by yyx990803** [comment]
这属于使用不当。你定义了 opacity transition，却没有触发 opacity 变化，Vue 会一直等待 opacity 的 transitionend 事件，等不到就不会移除。
