### ISSUE TITLE
"Change" in array causes re-rendering

### ISSUE THREAD

**Issue by marco-a** [vuejs/vue#3419]
**I'm not sure if thats a bug or intentional behaviour.**

### Vue.js version
1.0.23

### Reproduction Link
http://jsfiddle.net/5sH6A/587/

### Steps to reproduce
* Create a component with a property.
* Pass an object with an array as a property to the component.
* Watch the array in the property on the component.
* Set the array outside the component to the current value.

### What is Expected?
That no re-rendering is triggered because the array stayed the same.

### What is actually happening?
A re-rendering is triggered.

**Comment by yyx990803** [comment]
This is expected behavior, you've changed the identity of the array / mutated it, so the watcher **should** be triggered. But that is not equivalent to "re-render", because the DOM didn't get touched at all.
