### ISSUE TITLE
组件内部获取slot

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/vue#3423]
我想在组件内部知道是否有slot传进来，还有去获取到slot编译前和编译后的内容
目前好像没有办法。。。。

**Comment by yyx990803** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。

**Comment by sheng-xiaoya** [comment]
@yuu2lee4 你的问题解决了吗？

**Comment by yuu2lee4** [comment]
@sheng-xiaoya   vue2.0提供了slot属性了啊

**Comment by sheng-xiaoya** [comment]
@yuu2lee4 vue2.0是提供了slot属性了，但$slots.slotName获取的只是VNode组成的数组，根本无法获取slot中的代码内容。
我的需求是这样的：比如实现了一个Select组件，在做文档的时候，我需要在该Select示例的地方再放置一个button，点击该button则显示实现这个界面的代码。
如:
<code-box title="基本" describe="button基本用法">
            <i-button>Default</i-button>
</code-box>
我需要抽取this.$slots.default中的代码内容 ‘ <i-button>Default</i-button>’ ，加highlight再放到<pre><code></code></pre>中，实现代码展示

**Comment by yuu2lee4** [comment]
@sheng-xiaoya 看来你在做组件库。。。。或许你可以试着自己去编译一下。。。这个我后来也没去深究了 https://cnodejs.org/topic/58c0ad17d282728c0ec4029a
