### ISSUE TITLE
How to avoid the flash out caused by Javascript latency when page loading on Chrome?

### ISSUE THREAD

**Issue by kevinzheng** [vuejs/vue#3424]
When using `Vue.js` or any other `Javascript` to construct a page, the inevitable constructing latency causes transitory but annoying flash out when loading the page on Chrome. The latency doesn't lead by asynchronous `ajax` request, but just the constructing processing. How can we avoid this? This problem doesn't exist on FireFox and Safari, I guess they don't show the pages until rendering and constructing are completed, but on Chrome, it shows the pages at the same time of rendering and constructing side by side, so you will see the pages are fluctuant, that's really unacceptable. Anyone have good ideas?

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
