### ISSUE TITLE
vue do not update correctly when use Array.prototype.splice.call to modify data

### ISSUE THREAD

**Issue by pzxbc** [vuejs/vue#3434]
### Vue.js version
1.0.21

### Reproduction Link

* [The example code without using call](https://jsfiddle.net/pzxbc/vxdc95kt/14/)
* [The example code with using call](https://jsfiddle.net/pzxbc/quLtxe7t/13/)

### Steps to reproduce

just click the apple or orange

in the first example without using call(`this.items.splice`), you can see that the clicked item is deleted from page. In the second example with using call(`Array.prototype.splice.call`), the clicked item is still here, but you can see it deleted from items array in the console log.

### What is Expected?

I want to know why using `Array.prototype.splice.call` make vue not work. i search the call function on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call). 

** the description of it **

> the call() method calls a function with a given this value and arguments provided individually.

so, i can't figure out why, any one could explain it, thanks~

**Comment by prog-rajkamal** [comment]
The reason is that `Array.prototype.splice` and `this.items.splice` are different functions.

When Vue makes an array *reactive*, it modifies the `splice` function, so that Vue is notified when array is changed.

So when you use `Array.prototype.splice.call`, you modify the array, but Vue is not notiifed. but when you use `this.items.splice`, Vue is notified. 

Source : [Vuejs Guide](http://vuejs.org/guide/list.html#Array-Change-Detection)

**Comment by yyx990803** [comment]
This is a wontfix as explained above. It seems there's no particular reason to use call instead of direct splice.

**Comment by pzxbc** [comment]
@prog-rajkamal thanks for you reply.  I encounter this problem when i use [lodash](https://lodash.com/docs#remove) `_.remove` function.

lodash use `call` function in the base module `_basePullAt.js`

 I'm new to javascript, could you recommend other javascript utils library working with vue. i want to find a library manipulating with collections, thanks~~

**Comment by prog-rajkamal** [comment]
@pzxbe vue also adds a $remove() method to array. You can use that one instead of lodash's version

**Comment by fnlctrl** [comment]
@prog-rajkamal tip: $remove is removed in 2.0, so avoid using it if you plan to upgrade to 2.0 :)

**Comment by prog-rajkamal** [comment]
@fnlctrl thanks! I didn't realize it.

**Comment by Toilal** [comment]
I hit this issue when using lodash with VueJS. using `_.remove()` function on a reactive array doesn't invoke watchers.

see https://github.com/lodash/lodash/issues/3111

**Comment by akaibukai** [comment]
Hello,
I just hit the same problem with lodash `_.remove()` function using VueJS..
Another workaround could be to use the _[replacing an array](https://vuejs.org/v2/guide/list.html#Replacing-an-Array)_ method with the lodash `_.reject()` function which does not mutate the array.
