### ISSUE TITLE
输入框value单向绑定的问题

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3435]
`<input :value="test"/>`
该输入框的value只能响应一遍test的值，一旦再手动输入了内容，修改test值，输入框就不再响应

**Comment by hyiso** [comment]
不是很清楚场景，但是输入框之类的绑定不是用v-model么。。

**Comment by aweiu** [comment]
@hyiso 是 v-model不会有问题。是有些场景如果支持单向绑定会更方便，有些值不想被输入框改变，但它可以改变输入框

**Comment by hyiso** [comment]
@aweiu 那完全没必要用输入框哇

**Comment by aweiu** [comment]
@hyiso 毕竟也是要输入的哦。虽然变通实现可以绕过这种需求，但从框架的完善角度考虑的话，既然提供了v-bind这个api，结果就应该是确定的，必须是能响应数据变化的。

**Comment by hanai** [comment]
觉得是你 js 代码写错了，模板这里是正常的

**Comment by aweiu** [comment]
@hanai 不要“觉得”，可以自己试一下
[在线试](https://jsfiddle.net/orvmjfx7/1/)

**Comment by QingWei-Li** [comment]
这不是 Bug

`:value="test"` 只是让 input 标签获得 test 的值，那么你进行输入操作 'test' 的数据并没有改变，点击 click，此时 'test' 获得值 'changeByButton'，那么你再次输入，'test' 的值也并没有改变，再次点击按钮，由于值未改变，所以并不会再次赋值。

另外， **issue 是提 BUG 和 Feature 的地方** 请不要在这提问，可以到论坛或者 Gitter 里
