### ISSUE TITLE
v-model疑问

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3436]
子组件**my-input**:
```
<template>
  <input type="text" v-model="childTxt">
</template>
<script>
  export default {
    watch: {
      childTxt (v) {
        console.log(v)
      }
    }   
  }
</script>
```
父组件:
```
<template>
  <my-input v-model="parentTxt"></my-input>
</template>
<script>
  export default {
    watch: {
      parentTxt (v) {
        console.log(v)
      }
    }   
  }
</script>
```
如上代码，等于给输入框双向绑定了两次数据
问题来了：
在父组件里修改 parentTxt的值 子组件并不会监听到childTxt的变化
在子组件里修改 childTxt的值 父组件并不会监听到parentTxt的变化
这确实很好，符合vue对父子组件通信的原则。只是对于v-model来说就显得有些**奇怪**了，因为
v-model的意思是双向绑定啊，组件之间的数据是不应该被干扰，但v-model会有一个输入框的value作为中介啊，输入框的值变化了，数据就应该得到响应啊。。。
不过这个功能基本应该实现不了，毕竟在非ie低版本浏览器里，只能通过input事件去监听输入框值的实时变化，难以监听到js的改变行为，除非是用定时器了吧。唉，只是小小的吐槽下，这种问题应该不适合发在issues里面，但论坛里太冷清了，没人理我。。见谅！尤大大

> 最新发现，上面说的那种情况不同组件之间虽然不会即时响应数据变化，但是！！！在输入框获取再失去一下焦点的时候竟然就响应了！！具体原因不清楚，猜想可能是为了解决上述问题vue做了焦点监听，想延时同步补救一下。。。然而这样会让数据变得更加扑朔迷离啊

**Comment by theseawolves** [comment]
> You can use the v-model directive to create two-way data bindings on form input and textarea elements

so, my-input component is not a form input.


> Data can be passed down to child components using props.

**Comment by aweiu** [comment]
最新发现，上面说的那种情况不同组件之间虽然不会即时响应数据变化，但是！！！在输入框获取再失去一下焦点的时候竟然就响应了！！具体原因不清楚，猜想可能是为了解决上述问题vue做了焦点监听，想延时同步补救一下。。。然而这样会让数据变得更加扑朔迷离啊

**Comment by yyx990803** [comment]
1.0 并不支持这样的用法。

**Comment by sr2318522** [comment]
amaze的select是改变值后触发change事件 但是我给v-model加上.lazy后v-model还是没办法监听到改变后的值
