### ISSUE TITLE
$set behavior is unexpected. Does not update value if key is already under watch

### ISSUE THREAD

**Issue by imaia** [vuejs/vue#3438]
Please, take a look at these two snippets:

- http://jsfiddle.net/cmrdo6mx/
- http://jsfiddle.net/f6mxqkt7/ 

Shouldn't both behave the same? When "$setting" and the value is already there, the update simply does not happen.

**Comment by yyx990803** [comment]
In the first example you are just setting a local variable `val`, not even changing the `query` object.
