### ISSUE TITLE
[2.0.0-rc.1] Regression: v-model does not work on input=range in IE11

### ISSUE THREAD

**Issue by patrickb1991** [vuejs/vue#3439]
Version 2.0.0-rc.1

v-model does not seem to work in **Internet Explorer 11** on input type=range fields in the release candidate.  It does work without any problems in version 1 of vue.js, however.

Working example with vue.js version 1: http://fiddle.jshell.net/05vax3b2/1/
Same code but with vue.js 2.0.0-rc.1 included: http://fiddle.jshell.net/kzkfv5y3/2/

**Comment by sqal** [comment]
In IE11 it doesn't work in any 2.x release

**Comment by yyx990803** [comment]
Thanks @sqal for the pointer.
