### ISSUE TITLE
Invalid expression on iOS 8, works in iOS 9

### ISSUE THREAD

**Issue by sleewoo** [vuejs/vue#3441]
### Vue.js version
2.0.0-rc.1

Loading templates using `vue-loader`.
Failing template has a expression like `@click="set_x({x})"`
It compiles and works well on iOS 9.
However on iOS 8 same compiled template throws `failed to compile template` and template not rendered.

![screen shot 2016-08-13 at 4 23 27 pm](https://cloud.githubusercontent.com/assets/9264860/17643418/60240ab0-6172-11e6-8204-f38a8a2a90e6.png)

Worth to note that `@click="set_x({x: x})"` syntax works well.

Not a big issue, just wanted let you know in case it has deeper consequences somewhere.

**Comment by yyx990803** [comment]
You are using ES2015 syntax in a browser that doesn't support it. Make sure to stick to supported features in template expressions because they will not be transpiled for you.

**Comment by sleewoo** [comment]
supposed that but somehow i thought templates are transpiled for me.
realising now it was a ill assumption.
thanks.
