### ISSUE TITLE
2.0.0-rc.1 Select2 directive

### ISSUE THREAD

**Issue by thanosalexander** [vuejs/vue#3443]
Hi!
Did someone managed to make it working? I use select2 inside a component..with no luck.

**Comment by ktsn** [comment]
Hi, @thanosalexander.

Please make sure to follow [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), the issue list only accepts bug reports or feature requests.
You can use [gitter chat room](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask your question, thanks :)
