### ISSUE TITLE
cannot bind class

### ISSUE THREAD

**Issue by kiuka** [vuejs/vue#3445]
Hello,

I try to bind a class by using data attribute, but it doesn't work when it comes to child components.

I've made a jsfiddle example: [https://jsfiddle.net/ccypbxv8/](https://jsfiddle.net/ccypbxv8/) h1 should have the desired class from data, but it doesn't have and - and also experienced that it works if I use props instead of data.

Am I missing something or is it a bug?

Thanks in advance.

**Comment by fnlctrl** [comment]
Not a bug.
Component's `data` option should be a function returning an object, and you are using a minified vue which can't warn you about it.
```javascript
const TestComponent = Vue.extend({
      		data: function() {
          	return {
            	testClass: "test-class"
            }
          },
      	  template: `<h1 v-bind:class="[testClass]">test</h1>`
      });
```
https://jsfiddle.net/oujL1d24/

**Comment by kiuka** [comment]
Thank you very much!
