### ISSUE TITLE
html mustache output not working?

### ISSUE THREAD

**Issue by caiokawasaki** [vuejs/vue#3446]
### Vue.js version
Lastest - https://cdn.jsdelivr.net/vue/latest/vue.js

### Reproduction Link
http://codepen.io/caiokawasaki/pen/dXaPyj

### Steps to reproduce
Fill the input field in the top right

### What is Expected?
Highlight the text using the filter I've created

### What is actually happening?
The filter is returning html as expected, but when outputing with {{{}}} I'm geting an error

Stackoverflow : http://stackoverflow.com/questions/38925579/how-to-output-html-from-filter-inside-mustache

**Comment by phanan** [comment]
Are you talking about `product.name | highlight`? If so, `{{{ }}}` shorthand has been deprecated, use `v-html` instead. I'd use computed property by the way.

**Comment by caiokawasaki** [comment]
But, how to apply a filter into a v-html? I tried and things don't work as expected...

**Comment by phanan** [comment]
I'd use a computed property, for example:

``` javascript
computed: {
  highlightedName: function () { /* return your htmlized name here */ }
}
```

``` html
<span v-html="highlightedName"></span>
```

By the way, please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this.
