### ISSUE TITLE
cant register vue forum

### ISSUE THREAD

**Issue by east2005** [vuejs/vue#3450]
Does anyone know where to register vue forum? checked all the login page and cant find where to register

### Vue.js version
1.0.23

**Comment by simplesmiler** [comment]
You can sign in with your GitHub account: http://forum.vuejs.org/auth/github
Make sure your email in GitHub profile set to public at least for the first time.

**Comment by east2005** [comment]
Hi thanks for the reply. I tried login using github email but it says my
email has not been confirmed. And I didn't received any email from Vue
forum.
My GitHub email is set to public already. Could you help on this matter?

Thanks!

2016-08-15 17:42 GMT+08:00 Denis Karabaza <notifications@github.com>:

**Comment by rekateka** [comment]
@east2005 Setting my GitHub email to public wasn't enough for me; have you tried changing your forum email? Check out http://forum.vuejs.org/user/<your-user-name>/edit/email

**Comment by east2005** [comment]
Hi thanks for the reply. It seems there's no way I can find my email
setting in forum since I logged in using GitHub email. Did I miss something?

[image: 内嵌图片 1]

Thanks and regards

2016-08-15 22:01 GMT+08:00 Nicolás Mutis Mesa <notifications@github.com>:
