### ISSUE TITLE
[2.0.0-git] v-model mutation inside a method that is executed with the @input event is not working

### ISSUE THREAD

**Issue by Philipp-M** [vuejs/vue#3452]
### Vue.js version
2.0.0-git

### Reproduction Link
https://jsfiddle.net/philmi/cof5rfkb/2/

### Steps to reproduce
Just type a space, it should remove the input
### What is Expected?
Like said, a space in the input should just remove the text in the input field
### What is actually happening?
the method that is connected with the input event gets executed, but the model/view doesn't get updated if it is modified

**Comment by yyx990803** [comment]
When using `v-model`, you should use a watcher on `input` instead of a raw DOM listener, because `v-model` listens to the input event too and whatever you changed in your listener will be overwritten by `v-model`.
