### ISSUE TITLE
Auto Prefixing support for css3 gradients?

### ISSUE THREAD

**Issue by cho-is** [vuejs/vue#3458]
### Vue.js version
1.0.21

```
v-bind:style="{ backgroundImage: linear-gradient(45deg, ' + color1 + ', ' + color2 + ')' }"
```
Auto Prefixing support for css3 gradients is not supported?

Thanks in advance.

**Comment by yyx990803** [comment]
Autoprefixing only supports CSS property names, not values.

**Comment by cho-is** [comment]
thanks for the answer :)

**Comment by cho-is** [comment]
I am quite new with Vue, I am trying to figure out how to achieve this.

**Comment by quangv** [comment]
@cho-is maybe use class names instead?

**Comment by cho-is** [comment]
@quangv I am using Vue 2 now together with GSAP for animations.

**Comment by quangv** [comment]
Nice! GSAP is amazing, Vue is great, I was thinking of combining them
too... assuming they work nicely together?

**Comment by cho-is** [comment]
Indeed, it is all javascript. 
Playing much better now with new Vue 2 transitions!
