### ISSUE TITLE
Compilation of templates fails if it contains html sensitive characters

### ISSUE THREAD

**Issue by GlurG** [vuejs/vue#3459]
### Vue.js version
2.0.0-rc.2

### Reproduction Link
https://jsfiddle.net/x0r59ur1/

### Steps to reproduce
Create a component with a template containing "<".

### What is Expected?
No errors.

### What is actually happening?
Throws an "Error parsing template" message.

This worked in 1.0.26.

Escaping "<" with the corresponding html-code solves the problem.

**Comment by yyx990803** [comment]
This is expected. In valid HTML, `<` needs to be escaped. The 2.0 template parsing also requires escaping `<` properly.
