### ISSUE TITLE
Data binding within v-for loop in html data property

### ISSUE THREAD

**Issue by mmochetti** [vuejs/vue#3460]
## Vue.js version

2.0.0-rc2 (dist build)

## Reproduction Link

https://jsfiddle.net/6hnkz0rh/

## Steps to reproduce

As shown in the jsfiddle: The data-id HTML attrbute within the inner v-for loop is not being parsed.

## What is Expected?

Show the id of the item in the data-id HTML attribute

## Notes

If you change Vue version to 1.x it works fine. I couldn't find any breaking change [here](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) that would break this.

**Comment by yyx990803** [comment]
Use the non-minified build and you should see a warning that attribute interpolation has been deprecated. Use v-bind.

**Comment by mmochetti** [comment]
Thanks!
