### ISSUE TITLE
Removal of a DOM with an empty transition is not executed "immediately on next frame"

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#3461]
### Vue.js version
2.0.0-rc.2

### Reproduction Link
https://jsbin.com/degeceneci/edit?html,js,output

### Steps to reproduce
Click any of the 4 buttons to create a corresponding DOM below. The DOM has an empty transition. Click a button whose corresponding DOM is already created to remove that DOM. To reproduce my problem, click the "a" button, and then click it again.

### What is Expected?
first click prints:
immediate: []
next tick: [div]

second click prints:
immediate: [div]
next tick: []

### What is actually happening?
first click prints:
immediate: []
next tick: [div]

second click prints:
immediate: [div]
next tick: [div.no-transition-leave.no-transition-leave-active]

According to the 2.0 doc:

> If no CSS transitions/animations are detected and no JavaScript hooks are provided, the DOM operations for insertion and/or removal are executed immediately on next frame.

The first click(DOM insertion) works fine. But the second(DOM removal) fails. It's not removed on the next tick, and it still has transition-leave classes.

**Comment by LinusBorg** [comment]
What Browser do you test this in? IT works as expected for me in chrome:

**Comment by Leopoldthecoder** [comment]
@LinusBorg Chrome 52.0.2743.116
doesn't work in safari or firefox as well

**Comment by LinusBorg** [comment]
I'm on windows at the office right now, will check on OSX later. But it definitely works for me:

**Comment by LinusBorg** [comment]
![untitled screencast](https://cloud.githubusercontent.com/assets/1444526/17728316/07201388-645f-11e6-883d-87424b0e91a6.gif)

**Comment by Leopoldthecoder** [comment]
Please check out the console. As I mentioned above, what printed in the console is unexpected.

**Comment by LinusBorg** [comment]
I see what you mean now, thanks.

**Comment by Leopoldthecoder** [comment]
no problem.

**Comment by yyx990803** [comment]
The reason is that nextFrame !== nextTick.

Next frame is decided by `requestAnimationFrame`, while `nextTick` is a mechanism for Vue's internal scheduling queue which uses the microtask queue (via MutationObserver). These are two different concepts.

The "next frame" timing is a implementation detail that you should not care about - instead you should be using the transition events/hooks to perform tasks at desired timings.
