### ISSUE TITLE
[1.0.23] Vue work with proxy data in Chrome cause Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Ruikuan** [vuejs/vue#3464]
### Vue.js version
1.0.23

### Reproduction Link
https://jsfiddle.net/liruikuan/jo0v8j48/7/

### Steps to reproduce
click "init data" button
### What is Expected?
The code work well with Edge/Firefox, even work well with Chrome 51.0.2704. But after Chrome auto update to 52.0.2743, if click 'init data' button, you will get a Error:  vue.js:3232 Uncaught RangeError: Maximum call stack size exceeded.

### What is actually happening?
Maybe Vue work with proxy data cause some infinite recursive call.
How should I do for my proxy to make code work well?

**Comment by yyx990803** [comment]
Looks more like an issue in Chrome's proxy implementation rather than Vue's problem, unfortunately I don't think there's much we can do here.
