### ISSUE TITLE
How do I create a nested v-for

### ISSUE THREAD

**Issue by icodebuster** [vuejs/vue#3465]
### Vue.js version
1.0.26

This is what the server is sending me, here the error data can be random (title, body, abc, xyz)

    var error = {
         "title": [ "The title is already taken.", "The title must be at least 2 characters." ], 
         "body": [ "The body must be at least 20 characters." ],
    };

vue.js part

    <div  id="server-errors" class="ui negative message">
         <ul class="list">
             <li v-for="error in errors">{{ error }}</li>
         </ul>
     </div>

the above code will outputs 

    <div id="server-errors" class="ui negative message">
        <ul class="list">
            <li>The title is already taken.,The title must be at least 2 characters.</li>
            <li>The body must be at least 20 characters.</li>
        </ul>
    </div>

But I need to display all the error in a list form

    <div id="server-errors" class="ui negative message">
        <ul class="list">
            <li>The title is already taken.</li>
            <li>The title must be at least 2 characters.</li>
            <li>The title must be at least 2 characters.</li>
            <li>The body must be at least 20 characters.</li>
        </ul>
    </div>

Is there a way to nest a `v-for` to display all the `values`

in jQuery I could have done something like this 

    var errors = {
        "title": [ "The title is already taken.", "The title must be at least 2 characters." ],
        "body": [ "The body is already taken.", "The body must be at least 2 characters." ],
    };

    $.each(errors, function(key, value) { 
        $.each( value, function( i, val ) {
            $('body').append('Value: '+val+'<br />')
    });
  

Any help much appreciated.

**Comment by fnlctrl** [comment]
Hello @icodebuster
Thanks for filling the issue :smile:, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) for questions.

**Comment by icodebuster** [comment]
@yyx990803 
Can you tel me quick solution.

Thanks
