### ISSUE TITLE
Filter Dynamic Arguments don't support object['key'] notation

### ISSUE THREAD

**Issue by aristidesfl** [vuejs/vue#3466]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/nbq25a5L/

### Steps to reproduce
Try to access an object property using the `object['key']` notation in a filter parameter.

### What is Expected?
Both `value | filter object.key` and `value | filter object['key']` should work 

### What is actually happening?
Only `value | filter object.key` works

**Comment by defcc** [comment]
@yyx990803  this issue seems to be fixed already  with  #3734 

I update the demo here http://jsfiddle.net/nbq25a5L/1/ , use 1.0.27 version

**Comment by yyx990803** [comment]
@defcc yes, forgot to close!

**Comment by aristidesfl** [comment]
thank you!
