### ISSUE TITLE
How can I get a total from multi-dimensional array in a table?

### ISSUE THREAD

**Issue by dogrod** [vuejs/vue#3469]
Hello! I'm a starter of Vue.js. And I'm trying to write a table show product's amount. Unluckily I got some trouble when it computes the total amount. 
Here's my code.

`<div id="main" >
			<table class="order-specs-table" align="center" v-for="order in orders">
				<thead class="order-specs-table-thead">
					<th v-for="row in order.rows">{{row.name}}</th>
				</thead>
				<tr v-for="spec in order.specs">
					<td align="center">{{spec.color}}</td>
					<td v-for="amount in spec.coloramount" align="center">
						<input type="number" v-model="amount.num" @blur="unpaied_check(amount.num)" style="border-radius: 0; border-top:0px; border-left:0px; border-right:0px ;text-align: center; ">
					</td>
					<td align="center">{{total()}}</td>
				</tr>
			</table>
        </div>`

`var vm = new Vue({
            el: '#main',
            methods:{
                   	total:function(){
                   		var total = 0;
                   		this.spec.forEach(function(s){
                   			s.coloramount.forEach(function(c,n){
                   				total+= n.num;
                   			});
                   		});
                   		return total;
                   	}
		          
                },
            data: {
                orders: [
                {
                    id:1234567890,
                    rows:[
	                    {name:"size"},
	                    {name:"S"},
	                    {name:"M"},
	                    {name:"L"},
	                    {name:"total"}
                    ],
                    specs:[
	                    {color:"yellow",
	                    coloramount:[
	                    	{num:200},
	                    	{num:100},
	                    	{num:300},
	                    ]
	                    },
	                   	{color:"green",
	                   	coloramount:[
	                    	{num:400},
	                    	{num:300},
	                    	{num:100},
	                    ]},
	                   	{color:"blue",
	                   	coloramount:[
	                    	{num:300},
	                    	{num:600},
	                    	{num:500},
	                    ]}
                   	]
                }]
            }
        })`

**Comment by fnlctrl** [comment]
Hello @dogrod 
Thanks for filling the issue :smile:, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) for questions.
