### ISSUE TITLE
$index in "v-for",not used?

### ISSUE THREAD

**Issue by EliazTray** [vuejs/vue#3470]
### Vue.js version
^2.0.0-alpha.7

### What is Expected?
$index is not valid.
### What is actually happening?
Trying to access non-existent property "$index" while rendering.   in  console.log

**Comment by phanan** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by gera2ld** [comment]
`$index` is deprecated. see #2873

**Comment by phanan** [comment]
Oh right, was thinking `index` (without `$`). Thanks, @gera2ld. Closing the issue now.
@EliazTray: Just explicitly use `(val, idx) in list` in 2.0.
