### ISSUE TITLE
some problem on "v-bind:class"

### ISSUE THREAD

**Issue by and3013819** [vuejs/vue#3471]
hello , i have a problem:

	<div id="example" class="static" v-bind:class="[classA,{classB:isB,classC:isC}]">22</div>
    <script>
    	var vm=new Vue({
    		el:"#example",
    		data:{
    			classA:"class-a",
    			classB:"class-b",
    			classC:"class-c",
    			isB:true,
    			isC:false
    		}
    	});
    </script>
the result is:
`<div id="example" class="static class-a classB">22</div>`

why is classB ?

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by and3013819** [comment]
ok

**Comment by theseawolves** [comment]
@and3013819 **classB** is a key of Object, not a variable.
