### ISSUE TITLE
option 'name' on component creation gives warning and doesn´t work

### ISSUE THREAD

**Issue by indus** [vuejs/vue#3472]
### Vue.js version
2.0.0-rc.2

### Reproduction Link
http://jsfiddle.net/af3cq646/1/
```JS
var CUSTOM = Vue.component('custom',{name:'custom'});
console.log(new CUSTOM());
```

### Steps to reproduce
run fiddle and open console

### What is Expected?
no warning and component showing up with the name 'custom'

### What is actually happening?
warning "***```[Vue warn]: options "name" can only be used as a component definition option, not during instance creation```***" and component is named "**```VueComponent```**"

**Comment by LinusBorg** [comment]
Can confirm this, came across this yesterday as well.

**Comment by indus** [comment]
Name in console is still "VueComponent" in version 2.0.0-rc.3 !?

**Comment by yyx990803** [comment]
2.0 doesn't use `new Function` to change constructor name anymore (this is to make the whole runtime build CSP-compliant) - the `name` option only affects debug messages and vue-devtools inspection.
