### ISSUE TITLE
[vue2.0]v-model dosen't work well with input with type radio

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue#3473]
code demo [https://jsfiddle.net/leaves/rjdm75p1/2/](https://jsfiddle.net/leaves/rjdm75p1/2/)
This work well in vue 1.0,but I couldn't switch radio button with vue@2.0

**Comment by posva** [comment]
You're missing the `native` modifier on the click event on `test` component: `@click.native="triggerClick"`

**Comment by leaves4j** [comment]
@posva  in `titleClick`,if doesn't change the `this.helper_show` ,the v-model work well ,why?
```js
    titleClick(){
      this.helper_show=!this.helper_show
    }
```

**Comment by posva** [comment]
I don't understand your question 😕 . Consider asking the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue)
