### ISSUE TITLE
[2.0] Transition fails to show with components using render functions

### ISSUE THREAD

**Issue by mtpc** [vuejs/vue#3474]
### Vue.js version
v2.0.0-rc.2

### Reproduction Link

https://jsfiddle.net/wy1frr50/3/
### Steps to reproduce
Push the button until it cycles back into "First", then push it again
### What is Expected?
A fade transition to "Second"
### What is actually happening?
`Uncaught TypeError: Cannot read property '_pending' of null`
After investigation, it sounds like the element being transitioned out is (logically) removed from the dom, but the old reference is still kept. When vue tries to recycle it for rerendering, the reference lacks a `parentNode` property, leading to this error.

**Comment by LinusBorg** [comment]
your `key` assignment was on the VNode instead `VNode.data`

This works as expected: https://jsfiddle.net/Linusborg/wy1frr50/4/

**Comment by yyx990803** [comment]
You should not be mutating the vnode's key in `mounted` - by that time the vnodes have already been rendered into real DOM nodes, mutating them in `mounted` doesn't do anything.

Instead, do that directly in the render function before returning them: https://jsfiddle.net/80nazax6/

**Comment by yyx990803** [comment]
Btw, there's no need for `h(Vue.options.components['Transition'])` - just `h('transition')` will do.

And there's also no need for registering `Elm` and `Container` and then retrieve them from `this.$options.components`, just use them directly.

https://jsfiddle.net/80nazax6/1/

**Comment by LinusBorg** [comment]
@yyx990803 That does not fix the error described in this issue, unfortunately.  _If I click the button in your latest fiddle until "Second" appears for the second(!) time, you will see the error in the console, and clicking the button again won't transition to "third"

**Comment by mtpc** [comment]
Thanks for the advices regarding the unnecessary boilerplate!
Your solution doesn't seem to fix the issue, though, as @LinusBorg mentioned
