### ISSUE TITLE
Slot in nested list

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#3475]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/5sH6A/604/

### Steps to reproduce
````html
<ul>
  <li>
    <comp1>
      <li>some content</li>
    </comp1>
    outside:
  </li>
</ul>
```
```html
<!-- comp1 template -->
<ul>
  <li>In Comp1:</li>
  <slot></slot>
</ul>
```
### What is Expected?
```html
<ul>
  <li>
    <ul>
      <li>In Comp1:</li>
      <li>some content</li>
    </ul>
    outside:
  </li>
</ul>
```
### What is actually happening?
````html
<ul>
  <li>
    <ul>
      <li>In Comp1:</li>
    </ul>
  </li>
  <li>some content</li>
  outside:
</ul>
```

**Comment by ktsn** [comment]
Because `<li>` element is only allowed to put as the child of `<ul>` or `<ol>` in HTML.
To handle this problem, we can use `is` attribute.
https://jsfiddle.net/ktsn/5sH6A/607/

FYI: in v2.0, we are free from this HTML restriction when we precompile our templates using `vue-loader` or `vueify`.

**Comment by paulpflug** [comment]
thanks for the workaround :+1:
