### ISSUE TITLE
[2.0.0-rc.2] when use v-for with  v-if and v-else, it will render square of the expected number

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#3479]
### Vue.js version
2.0.0-rc.2

### Reproduction Link
https://jsfiddle.net/WhiteCusp/frfekkf5/3/

### Steps to reproduce
just run
### What is Expected?
0-aaaa
1-bbbb
2-cccc
### What is actually happening?
0-aaaa
1-bbbb
2-cccc
0-aaaa
1-bbbb
2-cccc
0-aaaa
1-bbbb
2-cccc

**Comment by prog-rajkamal** [comment]
This looks like a bug to me. 
 [Workaround](https://jsfiddle.net/frfekkf5/4/)

**Comment by Elfayer** [comment]
This is not a bug, you are doing twice the same loop, one inside the other:

```
<ul>
  <li v-if="!customItem" v-for="(item, index) in data">{{item}}</li> <!-- First loop here -->
    <component
      v-else
      :is="customItem"
      v-for="(item, index) in data" <!-- Second loop here, just remove this loop and you have it -->
      :item="item"
      :index="index">
    </component>
</ul>
```

**Comment by Elfayer** [comment]
+1 If we use `v-if="customItem"` instead of `v-else` it works fine. Looks like it comes from the `v-else` directive.

[**DEMO**](https://jsfiddle.net/frfekkf5/6/)

**Comment by LinusBorg** [comment]
`v-for` followed by an element using `v-else` does not play nice together, because v-if relys on the previous sibling elements v-if result - but there can be more than one, as `v-if` is evaluated after `v-for` so evaluated for each item in the loop.

This can lead to unexpected behaviour.

**Comment by posva** [comment]
You can surround the element with a `template` and use the `v-if`/`v-else` there:
https://jsfiddle.net/frfekkf5/7/
