### ISSUE TITLE
vuejs route between components scroll same

### ISSUE THREAD

**Issue by huanxijiuhao** [vuejs/vue#3483]
```
<template>
    <div class="index">
        <common-header id="common-header" class="common-header"></common-header>
        <router-view transition keep-alive class="index-view"></router-view>
    </div>
</template>
```
The route view will show two component A and B, while component A scrollY is 0, I route to component B, and scroll down, and then route to component A, A is also scroll. And I have try set router options saveScrollPosition, but the result is same. Anyone have any ideas?

**Comment by LinusBorg** [comment]
Please open this issue in the correct repository if you think this is a bug. 

If you need support,  ask on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
