### ISSUE TITLE
Dev: Hint in console when v-show used on element with the inline 'display: none;'

### ISSUE THREAD

**Issue by oaleynik** [vuejs/vue#3484]
```html
<div v-show="foo" style="display: none;"></div>
```

`v-show` will be flipping `none` to `none`.  It is developer's mistake, but feels like `v-show` doesn't work as expected.

Vue version: 2.0.0-rc.2

**Comment by miljan-aleksic** [comment]
As stated in the changelog, v-show now respects the original display value of the element. Why would you set it to none?

**Comment by oaleynik** [comment]
Indeed. This is irrational. We've seen situation when `display: none` was set in original design and after attaching `v-show` nobody removed `display: none;`. Would be nice to see some hint in console about this. We actually faced this with server side rendering  where `v-show` just sets `display: none;` and goes away.

**Comment by miljan-aleksic** [comment]
The change is ment to fix the situation where 'display: none' is set in the CSS, while just removing the display from dom would keep it invisible. It does make sense to completely remove it if the display is set to none, though.

@chrisvfritz, what do you think?

**Comment by oaleynik** [comment]
@miljan-aleksic thanks! This is exactly our debate in office. What should be happening in this case? Drop inline CSS? Or respect original inline value?
IMO respect original inline value is the correct behaviour because engineer dictates what should be happening, not library. Instead of inline CSS some class with the `display: none;` can be used. In this case inline `display: none;` which will be set by `v-show` will override the value from the class.

The only thing we agreed after debate is that small warning from Vue in the console (when in devmode of course) will not hurt :)

**Comment by yyx990803** [comment]
I think `v-show` should just ignore inline `display: none`, because

1. this doesn't make sense;

2. it needs to be able to override this when this value is itself set by `v-show` during SSR.
