### ISSUE TITLE
isPlainObject helper returns true for all objects

### ISSUE THREAD

**Issue by fenduru** [vuejs/vue#3485]
### Vue.js version
2.0.0-rc.1

### Reproduction Link
https://jsfiddle.net/ngzxjsxo/

### Steps to reproduce
See assertion failure in console

### What is Expected?
The object should not be converted to an observable object since it is not a plain object

### What is actually happening?
Any object is deeply converted to an observable object. There seems to be [existing code trying to guard against this](https://github.com/vuejs/vue/blob/be7339b38ad5083fd0d0baaa2eb9f508b5f9ce23/src/observer/index.js#L174), however the helper function [`isPlainObject`](https://github.com/vuejs/vue/blob/547a64e9b93d24ca5927f653710b5734fa909673/src/util/lang.js#L293) is not returning the correct result, This implementation is broken because `Object.prototype.toString.call(value)` will return `[object Object]` no matter what `value` is.

For reference, it looks like lodash's `isPlainObject` function does some addition checks, and returns the expected value.

This is problematic for me as I am attempting to store a large Immutable.js object on my Vue instance, which is freezing the browser when trying to recursively make the object observable.

**Comment by yyx990803** [comment]
Any user created object is considered a plain object. The check only guards against native objects, e.g. `window`.

The proper way to explicitly avoid observation is by freezing the object with `Object.freeze`.

**Comment by fenduru** [comment]
@yyx990803 `Object.freeze` doesn't seem to prevent the entire object from being walked

**Comment by sirlancelot** [comment]
> `Object.freeze` doesn't seem to prevent the entire object from being walked

It freezes the entire object. It is not, however, recursive.

**Comment by yyx990803** [comment]
@fenduru the observation system will stop the walk whenever it detects a frozen object. If that's not happening, please provide a proper reproduction.
