### ISSUE TITLE
When the interpolation expressions and class binding simultaneously used, class binding does not work.

### ISSUE THREAD

**Issue by charleslo1** [vuejs/vue#3486]
When the interpolation expressions and class binding simultaneously used, class binding does not work.

\<label class="ui-label ui-label-{{type}}" :class="{'ui-label-plain': plain}"\>
	{{text}}
\</label\>

**Comment by yyx990803** [comment]
The doc explicitly tells you not to use both at the same time: http://vuejs.org/guide/class-and-style.html#Binding-HTML-Classes
