### ISSUE TITLE
2.0 sort $slots?

### ISSUE THREAD

**Issue by rwu823** [vuejs/vue#3487]
I tried to sort from `$slots` but it doesn't work correct, is it supported?

**Comment by rajibahmed** [comment]
Please be more specific and try out forum first. Maybe solution to you problem is provided in the forum.

**Comment by posva** [comment]
As @rajibahmed stated, make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue). Your question is vague. In a render function you can sort your `$slots` however you like if that's the question
