### ISSUE TITLE
v-for首元素样式错位

### ISSUE THREAD

**Issue by zhujz** [vuejs/vue#3491]
A BUG
version: v2.0.0-rc.3

 － 当我使用v-for的时候，如果v-for外面没有被一个标签包起来（即有兄弟标签），那么v-for中第一个元素就会被其他标签样式干扰（看起来是变得和下方某标签样式相同，而且只受该标签行内style影响）；
 － 如果用一个div将v-for的标签包起来，就不会出现问题；
 － 之前的版本我使用的是v2.0.0-beta.5，换到最新版v2.0.0-rc.3依然有问题，用v1.0.10测试没有问题；

如果需要最小化复现，我再去搞一下。

**Comment by fnlctrl** [comment]
需要最小化复现，请去搞一下。

**Comment by zhujz** [comment]
https://jsfiddle.net/mbwLoLo9/12/

**Comment by rajibahmed** [comment]
<div id="demo">
  <div class="a" v-for="item in list">{{item.name}}</div>
  <div v-show="test"></div>
</div>

Works ! need to remove extra <div></div>

**Comment by zhujz** [comment]
It's just minimized, not extra.It can't be removed.
The only way I found to solve it like this https://jsfiddle.net/mbwLoLo9/15/.
But I don't know the reason.

**Comment by fnlctrl** [comment]
@yyx990803 Looks like a bug to me: `v-show` is affecting sibling elements, as in https://github.com/vuejs/vue/issues/3491#issuecomment-241400909

**Comment by zhujz** [comment]
@fnlctrl 还有个线索，不只是v-show，之前我试过用行内style也会影响循环首元素，但是复现不出来了，出问题的条件不一样
