### ISSUE TITLE
1.0.* v-for textarea bug

### ISSUE THREAD

**Issue by zhujz** [vuejs/vue#3492]
A BUG
version: v1.0.10

v-for中如果有textarea标签，在mac chrome环境下，浏览器前进或后退渲染页面导致textarea赋值错误
 － 刷新页面没有渲染问题，只在该页面有多个history时，前进或后退会出现问题
 － 具体赋值错误表现为：在数据模型改变后，渲染页面的过程发生了两次，第二次是错误的，覆盖了第一次正确的的结果
 － v-for中的input无此问题
 － Safari环境下无此问题
 － 在v1.0.10之后的v1.0.*均有此问题
 － v2.0.0以后版本无此问题，不知道这是已知的bug还是歪打正着修复了

**Comment by fnlctrl** [comment]
请给重现

**Comment by zhujz** [comment]
`<div v-for="item in [{name:1},{name:2}]"><textarea v-model="item.name"></textarea></div>`
1、用v1.0.10去chrome下测试
2、用浏览器前进后退到此页面
结果：渲染出来的两个textarea值都是1

**Comment by fnlctrl** [comment]
重现的意思是jsfiddle.net, codepen.io之类的在线例子

**Comment by zhujz** [comment]
这个是v1.0.16测试，还是有问题的[https://jsfiddle.net/mbwLoLo9/1/](https://jsfiddle.net/mbwLoLo9/1/)

**Comment by zhujz** [comment]
刚刚测试时发现1.0.17已经修复此问题了
有问题的最后一个版本是1.0.16：https://jsfiddle.net/mbwLoLo9/1/
在chrome上后退再前进，会发现两个textarea值都变成了1
之前并没有测试全面，不是1.0.*都有此问题，更换版本就好了，多谢提醒

**Comment by fnlctrl** [comment]
没事 那把这个issue关了呗

**Comment by zhujz** [comment]
https://jsfiddle.net/mbwLoLo9/1/

**Comment by zhujz** [comment]
1.0.17及以后版本依旧存在此问题，但与之前版本复现条件不同
操作步骤：
1、用chrome（版本无限制）先打开https://jsfiddle.net/mbwLoLo9/1/
（测试1.0.16，在1.0.17中修复了此写法带来的bug）
2、在当前页跳转至https://jsfiddle.net/mbwLoLo9/34/
（测试1.0.26，换一种写法，依然存在问题）
3、使用浏览器“后退”，第二个textarea值错误渲染为1，再“前进”，第二个textarea值错误渲染为1

**Comment by fnlctrl** [comment]
这应该jsfiddle加载机制的问题。你返回前进的时候jsfiddle的iframe里加载的是1.0.16的版本。

**Comment by zhujz** [comment]
是前进后退带来的问题，花五分钟运行个实际的例子看看吧，实际用着就有bug，排除jsfiddle试试 @fnlctrl

**Comment by fnlctrl** [comment]
@zhujz 前进后退的话，你给个加上vue-router的例子呗

**Comment by zhujz** [comment]
@fnlctrl 
1、更改地址栏34到37有问题
2、点update到保存成新的没问题
原因在于2、页面没有在前进后退时重新加载，试试1、是有问题的，稳定复现，放到实际测试也是稳定复现

**Comment by fnlctrl** [comment]
好吧 chrome上的确后退的时候有问题。但这个应该是浏览器相关，因为：
1. 我用Edge测试，没有问题
2. 首次渲染没问题，刷新也没问题，只在后退的时候有问题。

怀疑是chrome的后退保持textarea内容的功能导致的，手头没有firefox，你可以试一下。

**Comment by zhujz** [comment]
明白，辛苦了
2.0是没有这个问题的，如果1.0也能够解决就好了[/抱拳]

**Comment by fnlctrl** [comment]
没事。。1.0的修复要等一阵子。。
