### ISSUE TITLE
Directive: 在自定义指令时，jQuery只能获取到组件内的元素

### ISSUE THREAD

**Issue by DomenLee** [vuejs/vue#3493]
如题；
当组件A嵌套组件B时，B里面的自定义指令只能获取到B里面的element；

我现在想做出一个判断自己所处位置然后做出相应响应的效果，需要叠加所有父级元素的offset属性；

有什么好的办法吗？

现在已经是项目维护阶段，如果用组件的方式是可行的，但是代价太大，远远不如在需要响应的元素里面加上一条指令！

**Comment by fnlctrl** [comment]
你好，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请确保有完整的重现步骤。
请使用[论坛](http://forum.vuejs.org/category/10/%E4%B8%AD%E6%96%87)提问

**Comment by DomenLee** [comment]
好滴
