### ISSUE TITLE
Bug / Necessary Workaround for tables

### ISSUE THREAD

**Issue by Cadienvan** [vuejs/vue#3494]
Hi everyone,
I'm encountering a seriously annoying issue related to tables in chrome.

As you can see in my JSFiddle: https://jsfiddle.net/yk800dto/
I'm doing a v-for on a list of elements inside an array in order to properly write a table.
After every third element in such a table, I should close current tr and open a new one, in order to properly divide items in rows.

Fact is: Whenever I run this code, Chrome doesn't write `</tr><tr>` but `<tr></tr>` instead, vanishing my efforts of creating multiple lines. I already tried using `{{{</tr><tr>}}}` and nothing changed.

I guess it's not a Vue.js issue, but it'd be nice to have a workaround for it.

**Comment by fnlctrl** [comment]
This is one of Vue 1.0's [Template parsing](http://vuejs.org/guide/components.html#Template-Parsing) limitations.
The only workaround is to use vue 2.0 because
> The template parser no longer relies on the DOM (unless you are using the real DOM as your template), so as long as you are using string templates (<script type="text/x-template">, inline JavaScript strings, or compiled via single-file components), you are no longer subject to any of the template parsing limitations in 1.x. However, if you are relying on mounting to an element with existing content as template (using the el option), you will still be subject to those limitations.
Read more about 2.0 here: https://github.com/vuejs/vue/issues/2873#High Level Changes

**Comment by LinusBorg** [comment]
> The only workaround is to use vue 2.0 
.... or refactor the content into a component and use the special `is=` attribute to turn a tabel row/cell into that component.

**Comment by fnlctrl** [comment]
@LinusBorg Thanks! Wasn't aware of this workaround.

**Comment by Cadienvan** [comment]
@fnlctrl Thank you so much, I'll check 2.0 out for sure, I'm falling in love with Vue.js :P
@LinusBorg I'll check it out, I'm kinda new to Vue.js so didn't use components yet :)
