### ISSUE TITLE
failed to reference $children in v-for

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3497]
### Vue.js version
2.0.0-rc.3

### Reproduction Link

https://jsfiddle.net/fxwnmk7q/6/

### Steps to reproduce
Run

### What is Expected?
Parent1 should display `1` 3 times but none.

### What is actually happening?
`v-for` in `Parent1` does not work. As you can see , if set `$children` to a data field in `created` as in `Parent2`, the `v-for` works as expected.
 
This issue does not affect 1.0.26

**Comment by LinusBorg** [comment]
$children is not available in templates, because it contains references to child components.

**Comment by yyx990803** [comment]
You are not supposed to use $children in templates.
