### ISSUE TITLE
Is it possible to use v-model inside JSX render method?

### ISSUE THREAD

**Issue by voronianski** [vuejs/vue#3498]
I have a list of inputs and want to use `v-model` with them:

```js
render(h) {
  return (
    <div>
      {this.items.map(item => <input type="text" v-model="item.text" />)}
    </div>
  );
}
```

So far it's not working for me and I have doubts regarding possibility of making it work actually.

**Comment by LinusBorg** [comment]
You will have to replicate the behaviour with setting the value attribute and adding an input event.

**Comment by yyx990803** [comment]
What @LinusBorg said.

**Comment by blocka** [comment]
What is the reasoning behind this? While it works fine for custom components, it seems that `v-model` is doing quite a bit more then `this.$emit('input')`. Almost seems like "punishment" for those that actually like JSX...

**Comment by LinusBorg** [comment]
Honestly: JSX Was not a "first-class citizen" during 2.0 development. It was added later with a babel transform.

But `v-model` directives are compiled into normal Javascript and inserted into the render function during template compilation:

https://github.com/vuejs/vue/blob/3e8ac270a8d62630cae4191e016602c36b2b6beb/src/platforms/web/compiler/directives/model.js

So far, we haven't had the time (or felt the prettsure) to duplicate this delicate piece of code in the jsx compiler.

**Comment by Jerret321** [comment]
I want to support this future. when our team use the `vue.runtime.common.js` in the production env,   we want to write the tests for our component with the runtime version, but `v-model` can not be supported in jsx. It is so ugly to use the render function that our teammates can not understand it easily. So we have to use `vue.common.js` version  in  the `v-model` tests  sample. Please support it. Thanks
