### ISSUE TITLE
cannot set props to dynamic components

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3501]
### Vue.js version
2.0.0-rc.3

### Reproduction Link

https://jsfiddle.net/x9t73qa6/1/

### Steps to reproduce
Run

### What is Expected?
Should show child components content `1` `2` `3`

### What is actually happening?
`from-parent` props are not properly set to child components.

This works in 1.0.26 https://jsfiddle.net/wgdxhdsm/

**Comment by LinusBorg** [comment]
Templates need one root element. you have `v-for` on the child's root element.

https://jsfiddle.net/Linusborg/x9t73qa6/2/

PS: you would see a warning if you did not use a vue.min.js
