### ISSUE TITLE
how to dynamic insert the child-components into father-components

### ISSUE THREAD

**Issue by YeomanYang** [vuejs/vue#3502]
I have such a demand.There have one father-components and also some child-components，I want to dynamic insert the child-components into father-components,but i've not fount a right way.
For example the father-components called 'container',the child-components called 'simulator'
```
setTimeout(function() {
                $(".container").append("<simulator id='simulator'></simulator>")
            }, 1000);
```
I fount that <simulator> would not be parsed. 

In addition,it can't be solved by 'v-if',because i need to control the order of the child-components.

My project is very urgent, hope to get help.Thanks.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Hint: you can use `v-for` on components too.
