### ISSUE TITLE
Sorting components produces duplicate nodes in the dom

### ISSUE THREAD

**Issue by CristianGiordano** [vuejs/vue#3503]
Thank you so much for this awesome framework. I've only been working with the framework for a couple of months now, and still unsure of all of the limitations. This looks like a limitation of the component system.

### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/CristianGiordano/cdLp4uz2/

### Steps to reproduce

Move a person from one list to another (The list component is re-rendered alongside the moved dom node)

### What is Expected?
No duplication of elements. Here is a working version (same code) without a `person` component.

https://jsfiddle.net/CristianGiordano/ghwgzgtx/

### What is actually happening?
It looks like VueJS cannot re-use existing nodes or find the node which was moved. 

 - I have tried adding a `track-by` id with the relevant object properties.
 - I have tried SortableJS and Dragula sorting libraries with the same issue.

p.s. Apologies if this is not the right forum to raise such an issue.

**Comment by LinusBorg** [comment]
It works when you remove the element : https://jsfiddle.net/Linusborg/cdLp4uz2/8/ (JS Line 54)

The reason that it does not work is that the dropped element somehow looses the connnection to the component instance (it's usually saved on the element in an attribute called `__vue__`), and I think Vue can't do much about it.

**Comment by CristianGiordano** [comment]
Ok cool thanks. I thought it was as such but thought I could be doing something wrong. 

Thanks for your time :)
