### ISSUE TITLE
setSelected triggered on <select> by unrelated data object replacement

### ISSUE THREAD

**Issue by jingman** [vuejs/vue#3504]
### Vue.js version
2.0.0-rc.3 (or any 2.0 version)

### Browser version

Platform | Browser | Reproduces
---------|----------|------------
OS X | Chrome 52.0.2743.116 (64-bit) | yes
Windows | Firefox 48.0.1 x64 | yes
OS X | Safari 9.1.2 (11601.7.7) | no
Windows | Chrome | no
Windows | Edge 38.14393.0.0 | no

(Windows tests performed by @fnlctrl)

### Reproduction Link
http://jsfiddle.net/jingman/85b96530/2/

### Steps to reproduce
1. Make a `<select>` element and give it a `v-model`.
2. Make an object in `data`, give it a property, and render that property on the page.
3. Replace the `data` object, and you'll see (by recording and inspecting the timeline) that Vue's `setSelected` function is being called, even though the model and options for that element have not been touched.

### What is Expected?
Nothing should happen. `setSelected` should not be called, since that element's model is untouched.

### What is actually happening?
It seems that in some browsers, if _any_ object's property is being rendered to the page (`bar.name` in my fiddle), and that object is _replaced_, `setSelected` will be called, and the `<select>` will be repainted, even if its model is untouched. This causes an open `select` menu to flash. In this example I'm replacing the unrelated `data` object every second:

![repaint](http://i.giphy.com/l0MYI0k4NxtTfidDq.gif)

If you just change the prop, it doesn't trigger the re-render.

This issue is present in all `rc` and `beta` versions of Vue 2.0 (for OS X Chrome).
It is _not_ present in Vue 1.0.26. http://jsfiddle.net/jingman/og2b6uub/1/

**Comment by 3vand0ng** [comment]
this is bug?
no fix it
https://jsfiddle.net/5415dk6y/4/

**Comment by jingman** [comment]
@3vand0ng Interesting, this seems to be a regression.

@LinusBorg do we need to file a new issue for this, or reopen this one?

**Comment by posva** [comment]
Better fire a new one with, always following the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) 😛

**Comment by 3vand0ng** [comment]
https://jsfiddle.net/5415dk6y/5/ 
or this?
if option bind a value and setTimeout update other value, This problem will happen
