### ISSUE TITLE
Merging a null value into v-model attribute removes the attribute (maybe?)

### ISSUE THREAD

**Issue by gregrobson** [vuejs/vue#3505]
(apologies in advance if this is not a Vue issue! I can't quite fully identifiy the cause with my own knowledge!)
### Vue.js version
2.0.0 RC 3

### Reproduction Link
https://s.codepen.io/gregrobson/debug/jAoKLA

### Steps to reproduce
1. Set up a standard select element with a few options (each with a numeric value as index)
2. Set the select to a model value (starts as *null*)
3. Merge in new data (from API) that also has a *null* value for the model value.

### What is Expected?
1. Entry to remain in Vue Devtools

### What is actually happening?
4. Entry disappears from Vue Devtools - although it possibly may still exist???

![vue_error](https://cloud.githubusercontent.com/assets/1911321/17894921/229a3d12-6943-11e6-9a78-6177630bb57e.png)

### Possible cause?
FYI - I'm not an experienced Javascript Dev, so I can only provide educated guesses.

1. **It could be Vue Devtools at fault.** Perhaps during the variable merge Dev Tools looses track of the variable? If that's the case, then accept my apologies for putting the issue here.
2. If the intention is that `v-model` should always match an entry in the `v-for` then that makes it tricky for API developers as the select option might be loaded after the page is initialised. I prefer to have empty lists and `v-model` set to null until the data is loaded in. If that's the wrong approach then I'll have modify my code!

### Anything else...
I :heart: Vue :smile:

**Comment by yyx990803** [comment]
This is not really a bug - `v-model`'s behavior on `<select>` is that it will set the bound value to `undefined` if none of the options are selected, so `null` was converted to `undefined` in the nextTick after you called `pullState()`.

Then there is a bug in the DevTools that it ignores fields that have the value of `undefined`, but that is not really a separate issue (opened at the devtools repo)

**Comment by gregrobson** [comment]
Thank you for the quick reply @yyx990803 - that all makes sense. I'll know to expect that behaviour in the future :+1:
