### ISSUE TITLE
Tag attribute that is a vue property and vue directive parameter at the same time cannot be reached from vue params.

### ISSUE THREAD

**Issue by unidwell** [vuejs/vue#3507]
### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/gregmi/yLqnv2ex/

### Steps to reproduce

1. run and check the output, it says: "params.myAttr: undefined"
2. comment out the line 13 (props)
3. run again and check the output, it says: "params.myAttr: content"

### What is Expected?

It should say: "myAttr: content"

### What is actually happening?

When there is a tag **attribute** that is also a vue **property** and vue **directive** parameter at the same time, it is not reachable from within a vue directive (_this.params.myAttr_), but one can get it from vm (_this.vm.myAttr_).

It seem like a race condition of sorts (in time when vm properties are created) between vue component and vue directive.

**Comment by posva** [comment]
It is, indeed,because the component gets compiled before the directive. So it has already removed the attr from the dom when the directive tries to access it. If you want to access the attr, you'll have to access through the `vm`.

What is your use case, what problem are you trying to solve?

**Comment by unidwell** [comment]
I have a component with a dynamic property ":my-attr='variable'" and the idea is to use the attribute 'my-attr' also in the vue directive. Of course it is possible to bind the same variable to additional property that is not shared with specific component and that would solve it. But if one has more that one directive on the same element, there will be a lot of duplication (just to protect the component attributes) and as the directive user you must also be **aware of all** the components properties. On the other hand one also does not want the implementation of the directives to be **bound to the implementation details** of the specific component (i.e. getting attributes trough vm) and is preferable, more explicit and unsurprising to get the attributes trough the element attribute 'interface'.

There is **similar problem** when **more then one directives** compete for the same attribute and one can play with the priority attribute to select which one will win (as in this [fiddle]( https://jsfiddle.net/gregmi/523xpcg1/)).

And what can one do, when one is using **$index in v-for** and **two directives** need it at same time. That cannot be gotten trough vm (not directly) and one needs two attribute on the component :index1="$index" and :index2="$index" instead of just :index="$index".

So the fact that attributes are [extracted](https://vuejs.org/guide/custom-directive.html#params) is meant quite literally.

(tried similar stuff also with Vue2.0 and there one can get the unobserved attributes with vnode.data.attrs, but no params (for now))

**Comment by posva** [comment]
Can you give the real example, with real names? I don't understand why you'd have directives and components sharing the same attrs name. If that's a choice of yours, you'll have to handle it by yourself. 

Having the same attr named `index` can easily be solved with a meaningful variable name

**Comment by yyx990803** [comment]
This is expected behavior imo, having conflicting prop/params can be very confusing and I'd personally avoid such scenarios completely. In 2.0 this is also no longer possible due to directives no longer have params.

**Comment by unidwell** [comment]
Thank you for the info. Super to remove params to prevent such scenarios - 2.0 will be awesome :-)
