### ISSUE TITLE
Transition bug with keep-alive

### ISSUE THREAD

**Issue by banricho** [vuejs/vue#3510]
Vue version: 1.0.26
Demo: https://jsfiddle.net/banricho/1xrmf1bk/2/
1. Use `<component>` tag with `keep-alive`
2. Use `:transition` with different class names
3. Fast switch components

Vue can't remove the class name which was used last time, and throw an error in the console:

```
vue.js:1230 Uncaught TypeError: Cannot read property 'removeChild' of nullremove @ vue.js:1230(anonymous function) @ vue.js:1074p$1.leaveDone @ vue.js:6674(anonymous function) @ vue.js:220onEnd.pendingCssCb @ vue.js:6800
```

Thanks :)

**Comment by banricho** [comment]
Here's a demo in Vue 2.0:
https://jsfiddle.net/banricho/1xrmf1bk/3/

No bug & less css, nice!

**Comment by yyx990803** [comment]
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.
