### ISSUE TITLE
how can i get location in template

### ISSUE THREAD

**Issue by ly303550688** [vuejs/vue#3511]
how can i get location in template? in template window is undefined.

method or data?

**Comment by ktsn** [comment]
Hi, @ly303550688!

Please make sure follow [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), The issue list is reserved for bug reports and feature requests.
You can use [Gitter chat root](https://gitter.im/vuejs/vue) or [the official forum](http://forum.vuejs.org/) to ask usage questions.
Thanks.
