### ISSUE TITLE
'this' in render function is not defined

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue#3512]
code [https://jsfiddle.net/leaves/xt5ndyLx/](https://jsfiddle.net/leaves/xt5ndyLx/)
in render function ,this doesn't point to vue instance
vue version: 2.0.0-rc3

**Comment by ktsn** [comment]
Because you define the component as functional component.
Functional components cannot have their instance (`this`). If you want to use props in functional components, you can get them via 2nd argument.

```js
{
  functional: true,
  render: function(createElement, {props, children}) {
    console.log(props)
  }
}
```
