### ISSUE TITLE
Add $update method to arrays

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vue#3513]
Request from @dmx374 (who couldn't open an issue himself, appearantly for technical reasons)

Also, it would be really great to add an $update method to arrays, so we can update existing properties or add new ones (and make them reactive).

I've made a quick and dirty patch working for my needs :

    /**
     * update an element at the given index with new keys,
     * and emits corresponding event.
     *
     * @param {Number} index
     * @param {*} keys
     * @return {*} - replaced element
     */
    def(arrayProto, '$update', function $update(index, keys) {
        if (index >= this.length) {
            this.length = Number(index) + 1;
        }
        var val = [],
            source = this[index];

        for (var i in source) {
            val[i] = source[i];
        }
        for (var i in keys) {
            val[i] = keys[i];
        }
        return this.splice(index, 1, val)[0];
    });

**Comment by dmx374** [comment]
Thank you LinusBorg,

The main raison I posted that issue is to avoid ugly things like this: 

```js
/**
 * - contact is a reactive object with multiple existing properties
 * - we need to add a new key named "invited" to some contacts
 * - index is the index of contact in the contact list (this.contacts)
*/

var updated_contact = [];
for (var i in contact) {
	updated_contact[i] = contact[i];
}
updated_contact.invited = true; /* add our new "invited" key so it becomes reactive */
this.contacts.$set(index, updated_contact);
```

with an $update method, we will be able to simply do this: 

```js
this.contacts.$update(index, {
	invited : true
});
```

**Comment by yyx990803** [comment]
We are no longer augmenting built-in prototypes in 2.0 (as `$set` and `$delete` are both now either global or instance methods), so I'd avoid adding even more to 1.x.

This doesn't seem to need to be a prototype method anyway - why not just use a custom helper function? If you really want you can attach it to Vue or `Vue.prototype` for easier access.
