### ISSUE TITLE
textarea bug

### ISSUE THREAD

**Issue by zhujz** [vuejs/vue#3514]
version: v2.0.0-rc.3
https://jsfiddle.net/mbwLoLo9/18/
and browsers will crash in practical scene

**Comment by rajibahmed** [comment]
This looks are a problem/bug

**Comment by LinusBorg** [comment]
Not sure weither this is strictly a bug - one might want to add interpolated data to the textarea content... weither it's in a comment or not.

**Comment by rajibahmed** [comment]
Yep not sure it can be categorised as bug, but surely can have a documentation if not allowed. Or Have a console warn something like that.

**Comment by posva** [comment]
AFAIK you're not supposed to use v-model + inner content on textareas. I thought this was documented 😓

**Comment by iagafonov** [comment]
Documented here: #2873 (see v-model changes)

**Comment by posva** [comment]
@iagafonov Thanks! I'll make sure to add that to the docs this eveninig
