### ISSUE TITLE
Feature Request: loading...

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#3519]
Hi Guys

Vue 2.0 is working well with me. only I have small featrue request, maybe you can think about it.

I use Vue-resoure to pull data from other server, so I offten saw it need to wait the http response, so this led our client misunderstand us that our website is die.  so I think if before we get the response, there have a notice message to show "loading" will better. I know ,I can do this by myself, but I think if this feature in core will better.

Thanks for all your hard work.

**Comment by yyx990803** [comment]
This is a completely userland problem - different APIs, different loading requirements... I don't see how we can do this in core.
