### ISSUE TITLE
Using Vue.component from extended component has dependency issues 

### ISSUE THREAD

**Issue by gsouf** [vuejs/vue#3520]
As discussed in #1297 comments, using ``.component`` method on an inherited item does not transmit the components from the inherited elements:

```js
var Root = Vue.extend()

Root.component('Foo', {
	template: '<div>Foo</div>'
});

Root.component('Bar', {
    // We expect bar to be aware about foo, because foo was registered globally
	template: '<div>Bar, uses <foo></foo></div>'
}); 

new Root({
	template: '<div><bar></bar></div>'
}).$mount('#app')

// Throws: [Vue warn]: Unknown custom element: <foo> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in component <Bar>)
```

This fails because ``Bar`` component was built with ``Vue.extend`` instead of ``Foo.extend`` : https://github.com/vuejs/vue/blob/dev/src/global-api.js#L216

I would like to tell that it is an issue and the factory should use ``this.extend`` instead of the static ``Vue.extend``, but in the unit test it's already defined like that: https://github.com/vuejs/vue/blob/dev/test/unit/specs/global_api_spec.js#L105

Though there is an obvious workaround (``Root.component('Bar', Root.extend);``), I think the way the factory works is ambiguous and leads to confusion. 

What's your thoughs?

**Comment by yyx990803** [comment]
This is expected behavior. Only Vue.component registers global components.

**Comment by gsouf** [comment]
@yyx990803 your answer is not answering my question. 

I dont ask about Root.component for registering global component. Instead I ask about the factory of Root.component creating ``Vue`` instance and not ``Root`` instance

**Comment by gsouf** [comment]
Well, it will be simpler explained this way:

```js
Root.component('Foo', {
    template: '<div>Foo</div>'
});
```

is equivalent to 

```js
Root.component('Foo', Vue.extend({
    template: '<div>Foo</div>'
}));
```

When I was expecting it to be equivalent to:


```js
Root.component('Foo', Root.extend({
    template: '<div>Foo</div>'
}));
```

**Comment by yyx990803** [comment]
Then it doesn't make sense. Component registration is a separate concern from component inhertence. implicitly mixing the two doesn't sound like a good idea to m AND is a breaking change, so no.
