### ISSUE TITLE
Events not fired on a child component

### ISSUE THREAD

**Issue by clegendre** [vuejs/vue#3522]
Hello,

Version: Vue 2.0.0-rc.3
Repro link: https://jsfiddle.net/p9mcn2tp/2/

When an `@click` event is attached to a child component directly, the event is forgot.
But when the component is not the root, and the event is attached to the wrapper element, it works.

Uncomment the template line in the repro link, to see the workaround: the `@click` is on a wrapper div.

**Comment by fnlctrl** [comment]
use `.native` modifier on components.
```<foo @click.native="doSomething"></foo>```

**Comment by clegendre** [comment]
Thank you, it works !
This is indeed documented into the Custom Event part of the **Component section**, but it could also be added into the Event Modifiers part of **Methods and Event Handling** section

**Comment by asethwright** [comment]
Thanks. Missed this in the documentation. I would agree with @clegendre that it could be added.

**Comment by asethwright** [comment]
It would also be helpful to add this to vue-migration-helper, if possible, because this wasn't required in v1.0.

**Comment by defcc** [comment]
@chrisvfritz , could it be added to the vue-migration-helper ?

**Comment by chrisvfritz** [comment]
This unfortunately isn't something the migration helper can catch, but I'lol look into adding a second reference to the guide.
