### ISSUE TITLE
context of "this" within nestings.

### ISSUE THREAD

**Issue by smithb1994** [vuejs/vue#3528]
In the watchers example for 2.0  
```javascript
<script src="https://npmcdn.com/axios@0.12.0/dist/axios.min.js"></script>
<script src="https://npmcdn.com/lodash@4.13.1/lodash.min.js"></script>
<script>
var watchExampleVM = new Vue({
  el: '#watch-example',
  data: {
    question: '',
    answer: 'I cannot give you an answer until you ask a question!'
  },
  watch: {
    // whenever question changes, this function will run
    question: function (newQuestion) {
      this.answer = 'Waiting for you to stop typing...'
      this.getAnswer()
    }
  },
  methods: {
    getAnswer: _.debounce(
      function () {
        var vm = this
        if (this.question.indexOf('?') === -1) {
          vm.answer = 'Questions usually contain a question mark. ;-)'
          return
        }
        vm.answer = 'Thinking...'
        axios.get('http://yesno.wtf/api')
          .then(function (response) {
            vm.answer = _.capitalize(response.data.answer)
          })
          .catch(function (error) {
            vm.answer = 'Error! Could not reach the API. ' + error
          })
      },
      // This is the number of milliseconds we wait for the
      // user to stop typing.
      500
    )
  }
})
</script>
```  
We keep having to do hackey workarounds to keep the "this" context, by doing `var vm = this;`  
In angular, they got around this by passing a variable $scope, so you didn't have to wory about "this" scope, you would just use $scope. It would be nice if we could do the same for vue, either through a passed variable similar to how $scope worked, or if possible, something like this:  
```javascript
<script src="https://npmcdn.com/axios@0.12.0/dist/axios.min.js"></script>
<script src="https://npmcdn.com/lodash@4.13.1/lodash.min.js"></script>
<script>
var vm = new Vue({
  el: '#watch-example',
  data: {
    question: '',
    answer: 'I cannot give you an answer until you ask a question!'
  },
  watch: {
    // whenever question changes, this function will run
    question: function (newQuestion) {
      vm.answer = 'Waiting for you to stop typing...'
      vm.getAnswer()
    }
  },
  methods: {
    getAnswer: _.debounce(
      function () {
        if (vm.question.indexOf('?') === -1) {
          vm.answer = 'Questions usually contain a question mark. ;-)'
          return
        }
        vm.answer = 'Thinking...'
        axios.get('http://yesno.wtf/api')
          .then(function (response) {
            vm.answer = _.capitalize(response.data.answer)
          })
          .catch(function (error) {
            vm.answer = 'Error! Could not reach the API. ' + error
          })
      },
      // This is the number of milliseconds we wait for the
      // user to stop typing.
      500
    )
  }
})
</script>
```  
Let me know your thoughts. Thanks.

**Comment by LinusBorg** [comment]
Hello @smithb1994,

thank you for filing this issue.

Those "hackey workarounds" are called closures, and they are everywhere in JS.

And for most situations, if you use babel, they can be avoided by using an arrow function (which will be transpiled to a function bound to the current context).

Providing something like $scope would nessessitate changes at a fundamental level of how a vue instance is structured and operates, so in my opinion it won't be worth it.

**Comment by smithb1994** [comment]
Is there any way to do  
```javascript  
var vm = new Vue({
   ...
```
And then using 
```javascript  
vm.something = 1
```
rather than 
```javascript  
this.something = 1
```
within the Vue object?

**Comment by LinusBorg** [comment]
No.

**Comment by fnlctrl** [comment]
I don't think it's worth adding a feature for this, since it's a non-issue with the use of arrow functions.
By the way, $scope was something advised against in [angular styleguide](https://github.com/johnpapa/angular-styleguide)

**Comment by smithb1994** [comment]
I disagree, I feel this is a problem every developer will run into over the course of their vue project. Every developer will have to do a `var vm = this` over the course of their project, not to mention .bind too. The angular styleguide advised against using $scope for an unrelated reason and I think some alternative to "this" is important.

**Comment by fnlctrl** [comment]
Yes, some may encounter problem with `this`, but most of them just learned
javascript and started using arrow functions to solve it.

**Comment by smithb1994** [comment]
For those who are interested in a solution to this. As of right now, the cleanest solution is to put `vm = this` as a default function parameter.  
Example:  
```javascript  
...
  methods: {
    sortBy: function (vm = this, key) {
      vm.sortKey = key
      vm.sortOrders[key] = vm.sortOrders[key] * -1
    }
  }
```
It's a satisfying solution I can do on a personal bases, that doesn't take up too much space.  
Keep up the good work, I look forward to the full 2.0 release. :)

**Comment by Joshfindit** [comment]
Now that some time has passed on this and we are on 2.2.4, is there a best practice for this?

I find it comes up a lot when working with axios.

**Comment by LinusBorg** [comment]
as mentioned above: arrow functions.

**Comment by Joshfindit** [comment]
Excellent, now I know the way forward, thank you.

Is there a vuex and/or axios example of this?
(Have not learned arrow functions yet)

**Comment by Akryum** [comment]
There is [a lot of documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) about arrow functions on the web. This is not specific to Vue.

```javascript
created () {
  doSomething().then(() => {
    console.log(this.myProps) // 'this' is the component instance
  }
}
```
