### ISSUE TITLE
directive in slots should be binded into "in-dom" structure of parent component

### ISSUE THREAD

**Issue by iagafonov** [vuejs/vue#3529]
### Vue.js versions
1.0.26, 2.0.0-rc.3
### Reproduction Link
[fiddle 1.0.26](https://jsfiddle.net/kpe5rgLv/4/)
[fiddle 2.0.0-rc.3](https://jsfiddle.net/6a44np9u/5/)
### What is Expected?
expected dom structure will be the same in directive bind hook and after tick from it
### What is actually happening?
in bind hook `<comp />`  is #docuement-fragment (or null in 2.0)
after tick from bind it `<div><p>...</p></div>`

I know, may be it'is not a bug. Slots compiles under parent of component that has slots (root instance in this case), and may be it is not possible to bind directives after slot component is "in dom" but who knows?

**Comment by yyx990803** [comment]
Implemented in 2.0, this will likely be a wontfix in 1.x, but we will revisit it when working on 1.1.

**Comment by yyx990803** [comment]
Note: the behavior is introduced in rc.4 but will be reverted in next release. Instead, a new custom directive hook `inserted` is introduced, which will be called when the element has been inserted into a parent node.
