### ISSUE TITLE
Using With Large Forms

### ISSUE THREAD

**Issue by shakee93** [vuejs/vue#3530]
I have a huge form with 20+ fields. i feel so much redundancy on the code i write now. What is the best way ?

    <script>
    new Vue({
     	data : {
    		user : {
    			first_name : "",
    			last_name : "",
    			username : "",
    			and 20+.........
    		}
    	}
    });
    </script>
    
    <form>
    	<input name="first_name" v-model="user.first_name">
    	<input name="last_name" v-model=.user.last_name">
    	<input name="username" v-model=.user.username">
    	and 20+......... input fields
    </form>

i feel something like this would be nice. the user object will be created dynamically.. is this possible ?

    <script>
    new Vue({
     	data : {
    		user :  Object
    	}
    });
    </script>
    
    <form v-model="user">
    	<input name="first_name">
    	<input name="last_name">
    	<input name="username">
    	and 20+......... input fields
    </form>

Is this possible ? i have to define each repeatedly in data object and in the form.  it would be nice if we can achieve it something similar or simpler than that..

**Comment by fnlctrl** [comment]
google `Object.keys` and use it with `v-for`.

**Comment by shakee93** [comment]
Please check i have updated the post. 

A v-model should be pre defined in data object right? My question is to map the subkeys of the object with the input name.

I am not getting how will v-for and Object.keys would help on this. Can you please elaborate?

**Comment by dflock** [comment]
Not an expert, so this code will need modifying, but something like this is probably what you want:

```vue
<script>
new Vue({
    data : {
        user :  Object
    }
});
</script>

<form v-model="user">
    <div v-for="k in Object.keys(user)">
        <input name="{{ k }}">
    </div>
</form>
```

or, maybe using [Object v-for](https://vuejs.org/guide/list.html#Object-v-for), like this:

```vue
<script>
new Vue({
    data : {
        user :  Object
    }
});
</script>

<form v-model="user">
    <div v-for="value in user">
        <input name="{{ $key }}" value="{{ value }}">
    </div>
</form>
```

**Comment by ktsn** [comment]
I'm not sure that auto-generating form models in child component is good idea. But we can do this by using 2.0's render option.
https://jsfiddle.net/ktsn/xxodL5pc/3/
(I have no idea why the reset button does not affect input fields...)

**Comment by yyx990803** [comment]
This is a userland problem since it's achievable via components.

**Comment by shakee93** [comment]
Its not about generating the INPUTS !!

@dflock yes. but it is not about generating the input elements. it is about data binding actually sorry if i have missed clarify it on the first post.

@ktsn Thanks. that is what i am trying to achieve. but it would be nice if vue has it out of the box. i am not aware of the technical side. but it will be cool feature. like laravel collective form model binding

```
// current approach
<form  @submit="submitForm>
   <input name="first_name" v-model="user.first_name">
   <input name="last_name" v-model="user.last_name">
</form>

// it would be nice if we could have this kind of approach out of the box
form v-model="user" @submit="submitForm">
        <input name="first_name">
        <input name="last_name">
</form>
```

@yyx990803 Yeah Even thanks. but i would be pleased. if you direct me to correct way. below is the exact thing i am trying to achieve. it is similar laravel collective form model binding.

```
<script>
new Vue({
        el : '#app',
        data : {
            user : { type : Object , default : {} }
        },
        methods : {
            submitForm: function(){
                // now the user object contains the this.user.first_name and this.user.last_name
                // i can directly submit as json object to the api
                submitItWith(this.user);
            }
        }
});
</script>
```

**Comment by fnlctrl** [comment]
@shakee93 
```
<form>
    <div v-for="(value, key) in user">
        <input v-model="user[key]"/>
    </div>
</form>
```

And please use the [forums](http://forum.vuejs.org/) to ask questions next time.

**Comment by shakee93** [comment]
@fnlctrl Please check my last comment. i have checked your fiddle. sorry but i am not trying to achieve that. i already have the full form designed with input tags and all. i need to bind them dynamically. without adding `v-model` on inputs.

**Comment by fnlctrl** [comment]
What do you mean by `bind them dynamically`?
and why without using v-model?

**Comment by shakee93** [comment]
I am trying to achieve this. please read the above one.

```
form v-model="user" @submit="submitForm">
        <input name="first_name">
        <input name="last_name">
</form>`
```

**Comment by fnlctrl** [comment]
Then it's not possible. Please re-design your form.

**Comment by shakee93** [comment]
Great !! but will be available in future ? or no way to this ? it will be clean there is alot redundancy of same variable name. can this be a feature request ?

**Comment by fnlctrl** [comment]
This is a non issue because you can already solve it easily enough with v-for.
And as Evan said `This is a userland problem since it's achievable via components.`
