### ISSUE TITLE
Lifecycle hooks are not always called

### ISSUE THREAD

**Issue by birdlord** [vuejs/vue#3531]
### Vue.js version
2.0.0-rc.3

### Reproduction Link
http://codepen.io/anon/pen/KrjbkJ?editors=0110

### Steps to reproduce
1. Open the console
2. Click on "Switch to tab 1" 

### What is Expected?
You should see `mounted` and `created` being logged in the console every time you press the button

### What is actually happening?
`mounted` and `created` are only logged initially

### Additional info
Only seems to happen when a component is inside a template with a v-for

**Comment by yyx990803** [comment]
The `key` should be placed on the component itself, not the surrounding `<template>`.
