### ISSUE TITLE
this lost reference in created hook of component

### ISSUE THREAD

**Issue by kuma0605** [vuejs/vue#3532]
<img width="554" alt="screen shot 2016-08-26 at 11 39 10 am" src="https://cloud.githubusercontent.com/assets/2958589/17993362/be147b0a-6b81-11e6-8f33-21d669758d19.png">
<img width="1278" alt="screen shot 2016-08-26 at 11 39 31 am" src="https://cloud.githubusercontent.com/assets/2958589/17993370/cc289172-6b81-11e6-9978-053a0cc9c3ce.png">

a little confusion about it.

**Comment by fnlctrl** [comment]
Please read more about [`this` in javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)

And [Array.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) if you have time.

**Comment by iagafonov** [comment]
if you have time :laughing:

**Comment by kuma0605** [comment]
that's a shame!
