### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by ropeladder** [vuejs/vue#3533]
### Vue.js version
2.0rc3 (probably was occurring in 1.x versions but I'm not sure)

### Reproduction Link
https://jsfiddle.net/7e0sfqo7/

Sorry it's not very minimal. Had a hell of a time reproducing this.

### Steps to reproduce
Click "Change Data" button.

### What is Expected?
New data will populate template.

### What is actually happening?
Firefox: "NotFoundError: Node was not found" 
Trace:
insertBefore()
updateChildren()
patchVnode()
updateChildren()
patchVnode()
patch()
lifecycleMixin/Vue.prototype._update()
lifecycleMixin/Vue.prototype._mount/vm._watcher<()
get()
run()
flushSchedulerQueue()
nextTickHandler()

Chromium: "Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

I'm assuming this is related/similar to https://github.com/vuejs/vue/issues/3043.

**Comment by jddy** [comment]
I also met

**Comment by ktsn** [comment]
The error is caused by `<br>` on line 363. It works when I remove it.
But looks like this error has more complex cause because it may work when I remove the other parts. 😕
