### ISSUE TITLE
When multiple alive components "watch" the same state in Vuex, only the first generated component can "watch" it successfully.

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue#3535]
### Vue.js version
1.0.25

### Steps to reproduce
Multiple alive components "watch" the same state of the same store in Vuex
### What is Expected?
All the components should "watch" the state successfully.
### What is actually happening?
Only the first created component can "watch" the state successfully.

**Comment by fnlctrl** [comment]
Please provide a reproduction on jsfiddle/codepen etc.

**Comment by cnweibo** [comment]
@snowffer , proposed start to use vuejs2.0, i have spent time to 2.0, that is really awsome

**Comment by posva** [comment]
@snowffer ping

**Comment by snowffer** [comment]
@posva I'm writing the repro demo on jsfiddle.

**Comment by snowffer** [comment]
@posva Sorry, can't repro.

But for watch, I have a question. If the new value is equal to the old value, the watcher would not be triggered, right?

**Comment by posva** [comment]
It should not, at least on Vue 1
