### ISSUE TITLE
v-model="new" is  wrong

### ISSUE THREAD

**Issue by jddy** [vuejs/vue#3536]
### Vue.js version
2.0.rc3

### Reproduction Link

https://jsfiddle.net/jddy/7m12wdwr/2/
### What is Expected?

I think a lot of key words are wrong。eg：var new function。。。
But the object is not picky key。

v-model shouldn't limit some words。I think。

**Comment by iagafonov** [comment]
If you change 2.0.0-rc.3/vue.min.js to dev version 2.0.0-rc.3/vue.js, you'll see this in console:

`VM92 vue.js:2238 [Vue warn]: failed to compile template:

<input type="text" id="new" name="new" v-model="new">

- avoid using JavaScript keyword as property name: "new" in expression v-model="new"

 (found in root instance)`
