### ISSUE TITLE
can't open vue.org or http://cn.vuejs.org

### ISSUE THREAD

**Issue by Helloooooooooo** [vuejs/vue#3537]
`http://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.css`
this request file is peding...
many people has the same problem.
please solve this!
Thanks!

**Comment by LinusBorg** [comment]
This works for me, I can access this URL.

Probably. access to jsdelivr.net does not work from where you are (china?) ...

**Comment by sirlancelot** [comment]
vue.org doesn't belong to the Vue project.

I can access both [vuejs.org]() and [cn.vuejs.org]() without any problems. Maybe there's an issue with that CDN in particular.

**Comment by yyx990803** [comment]
This is either the CDN's problem or your network issue. Either it has nothing to do with Vue.
