### ISSUE TITLE
Global component in .vue doesn't get a render method during compilation

### ISSUE THREAD

**Issue by clegendre** [vuejs/vue#3539]
When creating a global component within a .vue file, the template defined in the .vue is not transformed into a render function during the webpack build. 
This leads to the error: "template or render function not defined".
Only component defined with `export default` in a .vue file has their template transformed.

Is there another way, or workaround, to register a global component in .vue file, without referencing the vue-compiler at runtime ?

vue: version 2.0.0-rc.3
vue-loader: version 9.4.1

```html
// Global component template is NOT transformed to a render function
<template>
  <input type="text" name="test" id="a" v-model="someData" />
</template>
<script>
Vue.component('my-input', {
	data(){
    return {
      someData: ''
    }
  }
})
</script>

// Template is transformed to a render function
<template>
  <input type="text" name="test" id="a" v-model="someData" />
</template>
<script>
export default {
	data(){
    return {
      someData: ''
    }
  }
})
</script>
```

**Comment by fnlctrl** [comment]
It's not how vue-loader works. vue-loader expects you to export a plain object, in order to let it compile template for you.
If you need to register a global component, just do
``` javascript
import Foo from './foo.vue'
Vue.component('foo', Foo)
```
