### ISSUE TITLE
Vue1.0 project  when  body using touchmove，v - if,: class instruction such as failure, what reason be excuse me?

### ISSUE THREAD

**Issue by lee134134134** [vuejs/vue#3540]
As the title，help me！

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by lee134134134** [comment]
3q
