### ISSUE TITLE
Add a v-model modifier to treat empty input values as null

### ISSUE THREAD

**Issue by bopjesvla** [vuejs/vue#3541]
The straightforward reason for this request is that there's currently no way to create an optional numeric field using v-model since empty inputs are reset to zero.

The fuzzier reason is that in many if not most models an empty input signifies the absence of its value, hence the error message "Please enter a username" instead of "Please enter a username that isn't empty," and the fact that, in contrast to data validation tools like JSON schema, HTML5 doesn't allow `required` fields to be empty.

I have no idea what this modifier should be called, though.

**Comment by defcc** [comment]
> v-model since empty inputs are reset to zero.

According to the description, this should be with 1.0.
