### ISSUE TITLE
how to registe vue.js forum? 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [vuejs/vue#3542]
# Anybody can help me?

**Comment by yyx990803** [comment]
You sign up with your GitHub account.

**Comment by xgqfrms-GitHub** [comment]
sorry,no  authorization!

**Comment by selfcatering** [comment]
I'm experiencing same - Github autorized me, but forum is rejecting it and issues redirect_uri_mismatch parameter in the URL
