### ISSUE TITLE
indexOf not working on observed array?

### ISSUE THREAD

**Issue by crossRT** [vuejs/vue#3543]
### Vue.js version
v1.0.26

### Steps to reproduce
1. use vue-resource request an API to get an array which contains number only.
2. the array becomes an **observed array**.
3. try to use `array.indexOf(numberToSearch)` on it to find whether a certain number in the array or not.

### What is Expected?
If `numbers = [1, 2, 3, 4, 5]`, then `numbers.indexOf(2)` should return the position of value 2 in the array.

### What is actually happening?
`indexOf()` not working on observed array

I'm still very new to vuejs, still got a lot to learn from the community.
Any help would be appreciated.

**Comment by fnlctrl** [comment]
Please provide a live reproduction (without using vue-resouce) on jsfiddle, codepen etc.

**Comment by sqal** [comment]
Seems like it's working as expected https://jsfiddle.net/L0v7csjd/

**Comment by crossRT** [comment]
sorry, it's my fault.
I passed in the string of the value into `indexOf()`, thus it can't located properly.
Problem solved. thank you.
