### ISSUE TITLE
向数组push的时候在ios上有bug

### ISSUE THREAD

**Issue by draguo** [vuejs/vue#3545]
## Vue.js version

1.0.26
## Demo
[jsfiddle](https://jsfiddle.net/zu4r9xw6/)
## 描述
向data中的array push 时，在特定的手机上出现，push 之后的 array 会有两个相同的 object 或 array
在computed 中会出现计算错误的问题
### 会出现 (已测试)
ios 9.3.3 and 9.3.4   iphone 6s plus 和 iphone 5s
### 不会出现（已测试）
ios 8.2 的 iphone 6 ，大多android 手机（测试五台），PC chrome
## 效果
左边是没问题的，右边是有问题的。
![效果图](http://i2.buimg.com/4851/81f9675d9d50bb71.png)

## 测试地址
上面的 demo 并没有采用vue cli 构建，所以不一定会出现问题(暂时无法测试上面demo)
这个是之前进行测试的地址
[出现问题的实例](http://www.casarover.com/test)

## 场景
使用vuex vue-router 实现本地购物车功能，在本地进行总金额的计算时出现问题

**Comment by fnlctrl** [comment]
请给重现(jsfiddle, codepen,jsbin etc)

**Comment by draguo** [comment]
https://github.com/vuejs/vuex/tree/master/examples/shopping-cart
这个vuex官方的例子也是有问题的，我现在怀疑是不是vuex的问题，没使用vuex的时候单页应用是可以的。这个问题是出现在特定的手机上，不是每台都有问题的。

**Comment by fnlctrl** [comment]
那你至少说一下ios系统版本吧....

**Comment by draguo** [comment]
在ios 9.3.4和9.3.3的iphone6s plus 和 5s上有这个问题

**Comment by draguo** [comment]
手机上的效果是这样的
![手机效果](http://i2.buimg.com/4851/67c543e621c31802.jpg)

**Comment by rubyless** [comment]
@draguo  说句题外话, 你这个微信的控制台是哪里的...

**Comment by xalexec** [comment]
@rubyless https://github.com/WechatFE/vConsole

**Comment by yyx990803** [comment]
还是没有给出具体的重现，能跑起来的那种。

**Comment by draguo** [comment]
@yyx990803 更新了一下描述，因为是项目快上线之前出现的问题，所以只好采用其他方案，今天才有时间完善一下。

**Comment by yyx990803** [comment]
jsfiddle 不能复现，能复现的那个没源码... 你叫我怎么帮你
另外你确定不是 vConsole 的问题？

**Comment by yyx990803** [comment]
经测试在 OS X Safari 上也有相同问题，但是只在 vConsole 里出现，Safari 自己的 console 里面是正常的。建议去 vConsole 开 issue。

**Comment by draguo** [comment]
@yyx990803 我可能表达的有些不清楚，问题的关键是最后进行计算的时候结果有些问题，我重新写了一个例子，实例和 jsfiddle 源码基本相同，不同的地方是实例是用 vue-cli 构建的
https://jsfiddle.net/zu4r9xw6/3/

[实例](http://casarover.com/test)
 
在最后返回的 result 值是不同的
左边是 ios 9.3.4 的iphone 6 plus 右边是我的小米手机
![result](http://i2.buimg.com/4851/05693b7fd1df5c67.jpg)

在 ios 8.2 的iphone 6 上没有上述问题

**Comment by 327326724** [comment]
怎么解决的我也遇到相同的问题

**Comment by draguo** [comment]
@327326724 看下这个吧，看看我们的问题是不是一样的，[computed使用小问题](https://segmentfault.com/a/1190000006851315)

**Comment by fnlctrl** [comment]
根本原因是如果在for
in时不检查hasOwnProperty，会遍历到原型，所以你的计数无故增加了。Array的map/reduce等方法不会有这个问题
