### ISSUE TITLE
Functional components' lifecycle events do not behave consistently

### ISSUE THREAD

**Issue by HerringtonDarkholme** [vuejs/vue#3546]
When functional component is created by `new`,  life cycle hooks are called. But when component is declared locally in parent components' asset option, no hook is called.

Currently the [doc](http://rc.vuejs.org/guide/render-function.html#Functional-Components) specifies that functional component does not have `data` nor `this`. But other options are not mentioned. 

### Vue.js version

2.0.0-rc1 in demo, the same in rc3

### Reproduction Link

https://jsfiddle.net/mxskrwe1/3/

### Steps to reproduce
Click run. There are two components, both having `created` life cycle hooks to `alert`.

### What is Expected?

Both/Neither life cycle called. Two alerts or no alert at all.

### What is actually happening?

Exactly one `alert` pops up.

**Comment by yyx990803** [comment]
It doesn't make sense to `new` a functional component... or, the functional option will simply be ignored when you use `new` to create a component instance, because by definition functional components **do not have instances**, so there's no lifecycle either.

**Comment by HerringtonDarkholme** [comment]
Why not make `functional` component another asset type like `directive`, I wonder? So API consumers will not make such mistakes.

**Comment by iagafonov** [comment]
@HerringtonDarkholme may be it is a good idea

**Comment by posva** [comment]
@HerringtonDarkholme You can already with `Vue.component()`. After all, it's just a simplified component

**Comment by HerringtonDarkholme** [comment]
@posva I would argue it is not. `functional` component is different from `component` in many ways: it has no state, it has no lifecycle, it has no `this`, it cannot be `new`ed. Most configurations of `component` cannot be applied to `functional` component. It behaves less like  a `component` than an `elementDirective` which has its own asset type in Vue1.0.

**Comment by yyx990803** [comment]
It's a component in that you can use it to composite UI using the same interface in templates.

Also we are in rc now, so no more breaking changes can be introduced.
