### ISSUE TITLE
Prevent keyup enter event from getting fired

### ISSUE THREAD

**Issue by bekite** [vuejs/vue#3547]
The following fiddle shows the strange behaviour I encounter:
https://jsfiddle.net/okv0rgrk/6965/

I have two input fields. One is inside a form and one is outside having a keyup.enter attached to it.
When I submit the form then the submit handler is called in which I focus the other input. Although I provide stop and prevent on the submit event, the keyup.enter on the other input is still called.
My current workaround is to provide a small delay (using setTimeout) before I focus the other input. Is there a better way to stop the firing of the keyup.enter event on the input outside the form?

**Comment by posva** [comment]
Hi, please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).

The form is submitting on the enter keydown event (Don't release the enter key to better see the effect). Therefore the keyup event always happens

**Comment by bekite** [comment]
Thank you for the answer. I didn't know about the normal behavior of a form being submitted on keydown. I posted the issue here, because I thought this was a bug in vuejs.
