### ISSUE TITLE
Failed to resolve directive: link (found in component: <menubar>)

### ISSUE THREAD

**Issue by ParmerYE** [vuejs/vue#3549]
<menubar> is component of app， "v-link" is not work but "route.go" is fine. I don't know why. help!
我在router-view外面引用的组件(比如导航栏), v-link  指令不起作用，无法跳转，会报错：Failed to resolve directive: link (found in component: <menubar>)，但是在组件内用click 点击事件下 route.go 是 可以进行路由跳转的。
请教！谢谢！

**Comment by fnlctrl** [comment]
请使用[论坛](forum.vuejs.org/category/10/中文)提问，issue是用于提交bug的

**Comment by ParmerYE** [comment]
论坛进不去， 这样，你有思路的话帮我解决下，谢谢

**Comment by ParmerYE** [comment]
@fnlctrl
