### ISSUE TITLE
Variable index of v-for cannot be used in v-show command

### ISSUE THREAD

**Issue by NextSeason** [vuejs/vue#3550]
### Vue.js version
1.0.26

### Steps to reproduce

``` html
<template v-for="( index, item ) in list">
    <li v-show="index == x">
           <img src="{{item}}" />
    </li>
</template>

```
### What is actually happening?

the list item would not be shown even if "x" is equal index.

**Comment by fnlctrl** [comment]
Cannot reproduce
https://jsfiddle.net/5k6e187t/
Please provide a live reproduction on jsfiddle, codepen etc.

**Comment by fnlctrl** [comment]
By the way, 1.0.26 has already deprecated mustache binding props
so instead of 
```html
<img src="{{item}}" />
```

you use
```html
<img :src="item" />
```
