### ISSUE TITLE
[2.0.0-rc.3] Vue.set() fails when trying to .set data used as HTML in template tag

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#3551]
### Vue.js version
2.0.0-rc.3

### Reproduction Link
https://jsfiddle.net/uriziel01/bh9ex1Lh

### Steps to reproduce
Click on `Click me` button.

### What is Expected?
Both rows content should change.
### What is actually happening?
Only the first one change (because its located inside `DIV`) and the second one fails with `Uncaught TypeError: Cannot convert undefined or null to object` because its located inside of template tag.

**Comment by fnlctrl** [comment]
You are accessing a non-existent index '2'
``` Vue.set(this.objects[2], 'name', 'second [CHANGED!]');```
https://jsfiddle.net/o4a51axb/
