### ISSUE TITLE
Struggling on how to make a numeric field comma formatter work on 2.0

### ISSUE THREAD

**Issue by marcalc** [vuejs/vue#3554]
In 1.0 we had filters which helped us translate comma-separated decimals in text inputs to javascript numbers (eg. '2,91' to 2.91). It was very straightforward.

How can such translation be implemented in 2.0? Maybe extending v-model directive? Creating a totally new directive and repeating all v-model boilerplate? Computed get/setters?

Thanks a lot!

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Regarding your need, the recommended approach in 2.0 is creating an extended component that handles the underlying conversion logic, e.g. `<numeric-input v-model="val"></numeric-input>`
