### ISSUE TITLE
`delete` key modifier includes backspace?

### ISSUE THREAD

**Issue by simshaun** [vuejs/vue#3557]
This is a bit confusing to me. I expected my event to only be triggered by the Delete key, but it's also being triggered by the Backspace key.

I see that [**keyCodes.delete**](https://github.com/vuejs/vue/blob/master/src/directives/public/on.js) includes the keycodes for both Backspace & Delete.

Would it not make more sense for `keyCodes.delete` to just be the Delete key? A new keyCode could be added for the Backspace key.

**Comment by thecrypticace** [comment]
See https://github.com/vuejs/vue/pull/2211

**Comment by yyx990803** [comment]
This is an intentional decision, and probably will remain so because changing it would be breaking. It is pretty straightforward to workaround it by using explicit keyCodes.

**Comment by simshaun** [comment]
I would never have guessed the current functionality because I've never used a Mac keyboard, so the problem described in #2211 is a non-issue for me and the solution only created confusion on my part.

I feel like [the docs](https://vuejs.org/guide/events.html#Key-Modifiers) should at least state that "delete" handles both the Delete key & Backspace key (if user's keyboard has it).
