### ISSUE TITLE
[BABEL] Note: The code generator has deoptimised the styling of "public/src/App.vue" as it exceeds the max of "100KB".

### ISSUE THREAD

**Issue by netroby** [vuejs/vue#3558]
[BABEL] Note: The code generator has deoptimised the styling of "public/src/App.vue" as it exceeds the max of "100KB".

While i build my project. i got this message. how to resolve it ?

My app.vue contains many codes

**Comment by fnlctrl** [comment]
This is not related to vue.
-----------
Hint: if something exceeds some limit, try breaking it down.

**Comment by tkaven** [comment]
@netroby wow!! is wonderful see you here!

**Comment by netroby** [comment]
@tkaven nice to see you .but i can not remember you. can you please let me know more about you?
