### ISSUE TITLE
First enter doesn't trigger transition

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#3559]
### Vue.js version
2.0.0-rc.4

### Reproduction Link
https://jsfiddle.net/uur9e91L/1/

### Steps to reproduce
Click the toggle button

### What is Expected?
On first click, the content fades in.

### What is actually happening?
On first click, the content doesn't fade in. It only fades in/out on the following clicks.

This only happens when the content is controlled by both `v-if` and `v-show`. But in Vue 1.x, it works fine as shown in this [demo](https://jsfiddle.net/xjf1ooov/)

**Comment by fnlctrl** [comment]
Using v-if and v-show at the same time is not supported in 2.0

**Comment by fnlctrl** [comment]
You need to use the `appear` prop, see https://github.com/vuejs/vue/issues/2873
https://jsfiddle.net/mLafkom3/

**Comment by Leopoldthecoder** [comment]
Thanks.

**Comment by vuchl** [comment]
Yeah this is pretty hidden in the docs: http://rc.vuejs.org/guide/transitions.html#Transitions-on-Initial-Render

**Comment by yyx990803** [comment]
This is indeed a bug, fixed in commit referenced above.
