### ISSUE TITLE
element shows up in mounted() when its v-show is false

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#3560]
### Vue.js version
2.0.0-rc.4

### Reproduction Link
https://jsfiddle.net/qbwjtr0z/1/

### Steps to reproduce
Just run the demo.

### What is Expected?
Alerts '0'.

### What is actually happening?
Alerts '435'(This may vary in different browsers. But it's always larger than 0).

The `visible` is always `false`, thus the `#container` div has `display: none`. But it seems on entering the page, it is visible for a very short period of time because `clientWidth` of the `p` element is 435. In fact, if we change `alert(this.$el.clientWidth)` to `debugger`([here](https://jsfiddle.net/qbwjtr0z/2/), remember to open the console), we can actually see the `p` element.
Is this a new feature introduced in rc.4? Because rc.3 doesn't do this.

**Comment by yyx990803** [comment]
This is unintentional, fixed in ada90e5
