### ISSUE TITLE
Render function applying props in a strange way

### ISSUE THREAD

**Issue by victorwpbastos** [vuejs/vue#3562]
### Vue.js version
2.0.0-rc.4

### Reproduction Link
https://jsfiddle.net/h9ttwoht/2/

### Steps to reproduce
Comment the line 22 in https://jsfiddle.net/h9ttwoht/2/

### What is Expected?
The <comp> props should be applied to the input element.

### What is actually happening?
The <comp> props are applied to div element.

**Comment by yyx990803** [comment]
This is intended behavior. When using a component, if any attributes on that component element is not explicitly declared as a prop, it will be set on the component root node as plain DOM attributes.

**Comment by victorwpbastos** [comment]
It should be the expected behaviour when using templates. I think when you are using render functions is because you don't want the default behaviour. Is there some way to override this?

**Comment by LinusBorg** [comment]
remove them from the root vnode?

**Comment by victorwpbastos** [comment]
How? I tried to do this in mounted hook but does not work. I'm supposed to use jquery?

**Comment by yyx990803** [comment]
I think it makes more sense to keep the behavior consistent between templates and render functions. If you want to allow user to customize the non-root element, you need to declare all attributes you want to intercept as props.

**Comment by victorwpbastos** [comment]
So in this case what's the purpose of render functions? I thought render functions should allow this level of customization. For a simple input component I have to map all html input attributes as props? What if the user want to apply a data-something attribute to the input?

**Comment by victorwpbastos** [comment]
Would be great to have a way to override this default behavior.

**Comment by yyx990803** [comment]
@victorwpbastos yeah, I'll think about that

**Comment by fenduru** [comment]
@victorwpbastos what exactly are you trying to accomplish by doing this? I think if the consumer of a component is trying to put a `data-something` attribute onto a deeply nested element, there isn't a strong separation of concerns (which is the reason for using components).
