### ISSUE TITLE
Dynamically set component not works

### ISSUE THREAD

**Issue by 6pm** [vuejs/vue#3568]
I try dynamically show component: 
```javascript
import GroupsGrid from './../../components/groups'
import RolesGrid from './../../components/roles'
import MainTabs from './../../components/main-tabs.vue' // <-- this component will be render other components

    data: {
        tabs: {
            'GroupsGrid': GroupsGrid,
            'RolesGrid': RolesGrid
        }
    },
```

And in 'main-tabs.vue' I try to render other files. In dynamically props I'm giving object `this.tabs` . I don't now how many components will be in `this.tabs`, I need render this components. This code doesn't work:
```html
<component :is="tabs.GroupsGrid"></component>
```

How do this?

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

If you think this is a bug, you need to provide proper reproduction.
