### ISSUE TITLE
import .html and set prop to component

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#3569]
### Vue.js version 2.0.0@rc4

I want have one component with any templates.
In result i get unrendered tags. For example: '<a v-if="false"></a>'
I try use "vue-template-compiler" and "render: {}", but it is not clear enough ¯\(ツ)/¯

`<template>
  <div id="slider-scroll">
    <slide v-for="s in slides" :template="s.template" :actions="s.actions"></slide>
  </div>
</template>

<script>
import slide from './sliderScroll/slide'

import welcomeHtml from './sliderScroll/welcome.html'
import templateHtml from './sliderScroll/template.html'

export default {
  name: 'PARENT'
  data: () => ({
    slides: [
      {name: 'Slide #1'},
      {name: 'Slide #2', template: welcomeHtml},
      {name: 'Slide #3', template: templateHtml},
    ],
  })
}
`
`<template>
  <section>
    <h1>{{ name }}</h1>
    <div v-html="template"></div>
  </section>
</template>

<script>
import defaultHtml from './default.html'

export default {
  name: 'CHILDREN'
  props: {
    name: String,
    template: {
      type: String,
      default: defaultHtml
    }
  }
}`

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
