### ISSUE TITLE
input content update bug

### ISSUE THREAD

**Issue by 0326** [vuejs/vue#3572]
### Vue.js version
1.0.12

### Reproduction Link

https://jsfiddle.net/0326/opymqm35/

### Steps to reproduce
I bind the variable named `text` to the input tag, and add a watch for it: while the `text`'s length is more than 10, slice `text` and reassign it to limit the length in 10.

### What is Expected?
the `text`'s length is less than 10, and the content in input is also less than 10.

### What is actually happening?
while the input length is more than 10,  the `text` in model data is actually sliced and updated, but the content in input tag is not update. unless you blur the input.

I just wanna limited the input length, but it's seems not work.

**Comment by hughgr** [comment]
maybe try maxlength or something like that. I don't actually think it is a bug. handle DOM update after blur is a way of optimization

**Comment by yyx990803** [comment]
This is intended behavior. In 1.x you should use a two way filter on the v-model value.
