### ISSUE TITLE
`leave` transition doesn't work if the element is shown by default

### ISSUE THREAD

**Issue by matkovsky** [vuejs/vue#3573]
### Vue.js version

1.0.26
### Reproduction Link

http://codepen.io/matkovsky/pen/EgYRyV?editors=1010
### Steps to reproduce
1. Create a custom transition.
2. Add it to an element that has `v-show` set to true by default.
3. Toggle the value of `v-show` (by toggling the corresponding data in the model, of course).
### What is Expected?

It should animate.
### What is actually happening?

The first `leave` is not animated. It looks like the `v-leave` (`[transitionName]-leave`) class is missing the first time.

**Comment by gsouf** [comment]
I'm also facing this issue with the example from vuejs modal: https://vuejs.org/examples/modal.html

If i use show:true by default, I can't hide the popup

**Comment by efegurkan** [comment]
Just FYI, maybe that helps,

When I tried to debug the Transition.prototype.leave it worked perfectly during debugging. But when there is no debugger attached It fails as explained on this issue.

**Comment by liuhao1025** [comment]
`` javascript
``

**Comment by liuhao1025** [comment]
Try this
``` javascript
leave(element) {
  setTimeout(() => {
    element.style.height = 0;
  }, 10);
}
```

**Comment by Kingwl** [comment]
http://codepen.io/anon/pen/xgaWyN?editors=1010
try it
height should always be set

**Comment by posva** [comment]
@matkovsky Tested your codepen but it actually works. Is this still an issue? If so, can you update the repro?

**Comment by posva** [comment]
After checking it again, this is not a bug. The element has not been rerendered the first time when you set the height on the `beforeLeave` hook, and therefore the CSS transition triggers as if the height is still 0.

You need to ensure the height is always set and _used_ before setting the height to 0. You should use requestAnimationFrame in the `leave` hook to make it work properly (the same way you should do it in the leave hook:

```js
leave(element) {
  requestAnimationFrame(() => {
    element.style.height = 0
  })
}
```

It also works with the solution @liuhao1025 proposed, but using `requestAnimationFrame` is a more reliable solution

**Comment by jdnz** [comment]
Has something changed that means the @posva solution no longer works? I am having the same problem, but that solution does not work for me. Using `setTimeout` works most of the time, but sometimes the item just collapses without animation.

**Comment by posva** [comment]
Hey, this is a Vue 1 issue. Implementing the CSS collapsing transition is sometimes tricky and varies depending on browsers. There are nice articles out there to implement this like: https://markus.oberlehner.net/blog/transition-to-height-auto-with-vue/

I'm locking this thread as it is outdated
