### ISSUE TITLE
Param attribute "number" set 0 as default

### ISSUE THREAD

**Issue by AnthonySendra** [vuejs/vue#3577]
### Vue.js version

1.0.26
### Reproduction Link

https://jsfiddle.net/59Lh3310/
### Steps to reproduce
- Click on the input
- Click somewhere else
### What is Expected?

Empty input
### What is actually happening?

The value is set to 0 (even if the default value is set to null) because of Param Attributes Number (http://vuejs.org/guide/forms.html#number)

**Comment by LinusBorg** [comment]
Same problem as #3541, but for 1.0

**Comment by zcoding** [comment]
The `v-model` directive will reset the input's value on blur, and if you give a `number` param, it will always change the value to `Number`.
See [here](https://github.com/vuejs/vue/blob/master/src/directives/public/model/text.js#L69).

**Comment by Buwder** [comment]
The v-model directive will reset the input's value on blur, and if you give a number param, it will always change the value to Number.
See here.

**Comment by LinusBorg** [comment]
@Buwder you simply copied the comment above yours. Are you going to add anything of your own or can I delete your comment?

**Comment by defcc** [comment]
@LinusBorg  this issue seems to be fixed in 2.0 ?

**Comment by LinusBorg** [comment]
Which is why this issue is tagged as 1.0... :-P
