### ISSUE TITLE
`v-leave` transition class should be removed in 2.0

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3580]
None of the example code has used it. And can someone come up with any real-world leaving animation that does not start with the normal/current state of the element? "No real use".

**Comment by yyx990803** [comment]
This is different from other deprecated API due to the symmetry and logical completeness - you wouldn't cut off a limb because you never use it.

**Comment by Centaur** [comment]
Ridiculous justification. But you are the boss.

**Comment by Centaur** [comment]
![e3a74002-2655-442f-8225-27552c603407](https://cloud.githubusercontent.com/assets/265524/18897809/c1464b58-855f-11e6-96aa-4befbcc922c0.png)

This is a screenshot from one of the qq group about vuejs. And I predict that such questions will come up again and again in the future, because the users commonly expect symmetric api brings symmetric usage.

We wouldn't decide to cut off a limb not **just** because we hardly use it, but we would cut it off if we don't use it and it is causing trouble, like the cecum.

**Comment by khty2000** [comment]
i meet the same question.  first i think it will work as same as v-enter . but it does't。。
