### ISSUE TITLE
[Question] Streaming SSR

### ISSUE THREAD

**Issue by haohcraft** [vuejs/vue#3584]
Hey,
Noticed that the new version of Vue comes with a `stream server side rendering`, I found a hard time to find any doc or dig into the code base for that part. Since I am new to vue, could point me to the related parts in the code base? I am more than happy to study and write some doc for that at the end. Thanks a lot.

**Comment by fnlctrl** [comment]
Hello! Please use our [forum](forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the contributing guidelines. Thanks.

---------

http://rc.vuejs.org/guide/ssr.html
