### ISSUE TITLE
Error when evaluating expression 'distance' on undefined

### ISSUE THREAD

**Issue by gholol** [vuejs/vue#3585]
### Vue.js version
1.0.23

### Steps to reproduce

DemoComponent.vue:

`<template>
  <div>Distance Test: {{distance}}</div>
</template>
`

    <script>
        export default {
            props: ['data'],
            computed: {
                distance: function() {
                    return this.data.distance;
                }
            }
        }
    </script>

app.js: 
        
       import DemoComponent from './components/DemoComponent.vue'        

       /..

        var Demo = Vue.extend(DemoComponent);
        var di = new Demo({el: DOMElement})
              di.data = {distance: 100 };

### What is Expected?

Working component.

### What is actually happening?

Computed property displays proper value and  component is succesfully mounted, but at the same time it throws warning into the console.

>Vue warn]: Error when evaluating expression "function distance() {
            return this.data.distance;
        }": TypeError: Cannot read property 'distance' of undefined

**Comment by posva** [comment]
Hi, please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).

---

You should be passing props through HTML
