### ISSUE TITLE
vue template add blank line error way?

### ISSUE THREAD

**Issue by mykite** [vuejs/vue#3586]
error
![image](https://cloud.githubusercontent.com/assets/9413389/18191805/d41c0380-7100-11e6-8086-20c77a9bac90.png)
![image](https://cloud.githubusercontent.com/assets/9413389/18191853/639cea9c-7101-11e6-8356-09ff8920f39b.png)

success
![image](https://cloud.githubusercontent.com/assets/9413389/18191818/ff9a3360-7100-11e6-8872-0b6aafc3702c.png)
![image](https://cloud.githubusercontent.com/assets/9413389/18191838/3c739a24-7101-11e6-9d85-921bf981614d.png)

use sublime text3 and  vue plugin

**Comment by fnlctrl** [comment]
not related to vue.

**Comment by mykite** [comment]
thanks, this standard too strict....

**Comment by LinusBorg** [comment]
you can change the rules in `.eslintrc.js`

**Comment by mykite** [comment]
i didn't change, but i try to delete, no effect

**Comment by LinusBorg** [comment]
please get familiar with the way eslint works.

The vue-cli template that you use extends a set of eslint rules (depoending on what you chose when during init, either `standard`or `airbnb`. 

If you don't like any of those rules, you will have to overwrite it in your `.eslintrc.js` file:
```js
rule: {
  'no-trailing-spaces': 0
}
```

**Comment by mykite** [comment]
thanks,  I get to this skill

**Comment by andrietri** [comment]
thanks @LinusBorg, you save my time ^^
