### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by EHadoux** [vuejs/vue#3589]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/ej77a93w/

### Steps to reproduce
Add a local vue-csp.min.js.
Open in Chrome.

### What is Expected?
To load the script and then all components in subsequent files.

### What is actually happening?
The console reads `Uncaught ReferenceError: Invalid left-hand side expression in postfix operation` when the page is open using Chrome on both Ubuntu and Mac OSX.
However, it's working perfectly well on Safari.

As a live experiments, the form on http://thesciencevessel.herokuapp.com/papers should be hidden.
It's shown on Chrome but is hidden as it should on Safari.

**Comment by yyx990803** [comment]
I can't get any meaningful information from the jsfiddle - consider narrowing down the problem and providing a more isolated reproduction.

**Comment by EHadoux** [comment]
Don't you have the error in the developer console?

**Comment by EHadoux** [comment]
Okay, so actually, it does not seem to like this line:
`this.id = '__v-for__' + ++uid$3;`

Okay I quite can see why now, I guess it's because once minified by Heroku, `+ ++uid$3`becomes `+++uid$3`.

**Comment by posva** [comment]
I'm glad you find a solution. The problem with your jsfiddle is that you just included a minified js file. You can use the provided jsfiddle template in contributing guidelines to show off the issue.

**Comment by EHadoux** [comment]
I have found the problem. A solution would be to wrap `++uid$e` with parenthesis. I think it should have bee done in the first place though.
