### ISSUE TITLE
Template escape using $el property

### ISSUE THREAD

**Issue by bahmutov** [vuejs/vue#3590]
### Vue.js version
1.0.26 

### Reproduction Link
http://jsfiddle.net/bob4vmko/1/

### Steps to reproduce
Open the fiddle, see alert box

### What is Expected?
The HTML template expression should not execute javascript code
```
<p>Hello, {{ + $el.innerHTML='<script>alert(1)</script>' }}</p>
```

### What is actually happening?
The alert box pops up - the script tag is executing

**Comment by sirlancelot** [comment]
It's executing because you are changing the `innerHTML` via javascript. It has nothing to do with Vue.js

**Comment by bahmutov** [comment]
Oh, my bad!

**Comment by fnlctrl** [comment]
as explained above thanks to @sirlancelot , for 1.0

For 2.0, <script> will still execute because vue can do nothing for you when you are manipulating dom using native api (element.innerHTML)
