### ISSUE TITLE
Input binding does not update when styled with Materialize CSS

### ISSUE THREAD

**Issue by wesleywerner** [vuejs/vue#3593]
### Vue.js version
1.0.26

### Reproduction Link
https://jsfiddle.net/b766b0ep/1/

### Steps to reproduce
* Implement the select binding as given in the [Vue guide](http://vuejs.org/guide/forms.html#Select).
* Add the [Material design](http://materializecss.com/getting-started.html) styling framework.
* Apply the [select element styling](http://materializecss.com/forms.html#select).

### What is Expected?
* The "selected" binding in the model should update to reflect the value the user selects from the drop-down.

### What is actually happening?
* The bound value stays stale, it does not reflect the value the user selected.

### Workaround
* Material offers a ".browser-default" class which overrides the style of the control to the default. Using this style on the select fixes the Vue binding.

This is demonstrated in the fiddle provided.

### Notes
Apparently the value of the underlying `select` element is updated differently when the material style is used, and this bypasses the Vue change detection.

**Comment by fnlctrl** [comment]
Vue cannot detect changes made by other libraries. 
And also, vue works under the assumption that you do not modify dom yourself (or with other libs).
