### ISSUE TITLE
@click handler lost under weird condition

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3594]
### Vue.js version
2.0.0-rc4

### Reproduction Link

https://jsfiddle.net/86md11zj/1/

Sorry but I am not able to make this code smaller.
### Steps to reproduce
click `Show Dialog` button

In the dialog, click any of the checkboxes for

1. 0 times, then `Submit`
1. once, then `Submit`
1. 2 or more times, then `Submit`

### What is Expected?
`onSubmit` handler should be called whenever 'Submit' is clicked, logging 'doSubmit' in console

### What is actually happening?
If any of the checkboxes is clicked once,  then `Submit`,  `Uncaught TypeError: o.fn is not a function` error is throwed, `onSubmit` handler is not called.
If the checkboxes are clicked 0, 2 or more times (count different checkbox clicks), then `Submit`, no error, `onSubmit` handler gets called.

There is no where in my code that ever touch the 'onSubmit' handler.

**Comment by sqal** [comment]
Probably related to #3556

**Comment by Centaur** [comment]
@sqal Except that there is no `v-show` here.

**Comment by yyx990803** [comment]
@Centaur it's the same issue, slot content being reused will cause this. Will be fixed in rc5.
