### ISSUE TITLE
$watch silently ignores changes in sealed objects

### ISSUE THREAD

**Issue by ashmind** [vuejs/vue#3596]
### Vue.js version
1.0.26

### Reproduction Link
http://jsbin.com/sarehituko/1/edit?js,console

### Steps to reproduce
1. Pass `data: { nested: Object.seal({ property: value }) }` to `Vue` constructor.
2. Watch `nested` with `deep: true`.
3. Change `property` either directly or through binding.

### What is Expected?
Either one of:
1. `Vue` constructor or `$watch` fails with an error.
2. Watch calls callback for sealed object property.

### What is actually happening?
There is no error, but `$watch` callback is never called.

**Comment by yyx990803** [comment]
This is expected behavior, any object that is [not extensible](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isExtensible) will be skipped for observation.

**Comment by ashmind** [comment]
@yyx990803 Yes, but I feel it should produce at least a log warning (when not production) -- took me a long time to understand why it doesn't work.
