### ISSUE TITLE
Scoping CSS to slot content not working properly

### ISSUE THREAD

**Issue by RashadSaleh** [vuejs/vue#3597]
### Vue.js version
^1.0.0

### Reproduction Link
<none>

### Steps to reproduce
Make two components: Big and Small. Big has two Small instances. Small has a slot where you can insert HTML from Big into small. Big inserts two <button> elements in each Small instance. Small has scoped css styling. Small tries to apply styles to any button inserted in the slotfrom Big using something like:

.small button {
 margin-right: 5px;
}

### What is Expected?
Buttons from Big inserted in Small should have a margin of 5px to the right. Vue should generate the following css rule:

.small[attr] button {
 margin-right: 5px;
}
((where attr is the attribute generated automatically by vue to scope the styling))

### What is actually happening?
Buttons are not styled and instead the following css rule is added:

.small button[attr] {
 margin-right: 5px;
}

**Comment by fnlctrl** [comment]
Vue doesn't manage css. Scoped css is one of [vue-loader](https://github.com/vuejs/vue-loader)'s features, so if you believe there is a bug, please open an issue there instead.
