### ISSUE TITLE
Custom transition class doesn't work for router-view

### ISSUE THREAD

**Issue by petrelselina** [vuejs/vue#3598]
I config the animate.css class name like:
```
Vue.transition('flipX', {
  enterClass: 'flipInX',
  leaveClass: 'flipOutX',
});
```

and add attributes:
   ` <router-view keep-alive transition-mode="in-out" class="animated" transition="flipX"></router-view>
`
I found that vue will add the leave class "flipX-leave" but not "flipOutX" for the leaving page, so this page cannot leave. 
And I try use this transition with v-if or v-for elements, it works well.
`<list-item class="animated" transition="flipX" v-show="resultList.length"
      v-for="item in resultList" track-by="$index" :info="item"></list-item>`
 Please verify it. (version: vue1.0.26 vue-router0.7.13)

**Comment by LinusBorg** [comment]
Hi @pespantelis,

thanks for filing this issue.

Could you nprovide a reproduction on jsfiddle please? this would help us a lot to get to the bottom of this.

**Comment by petrelselina** [comment]
Sorry, I figure out that I write the config after router.start function, it's my fault, sorry.
