### ISSUE TITLE
Can't bind firefox wheel event in vue.

### ISSUE THREAD

**Issue by SidKwok** [vuejs/vue#3599]
### Vue.js version
1.0.26

### Reproduction Link
[jsFiddle](https://jsfiddle.net/7msmz93x/1/)

### Steps to reproduce
1. bind mousewheel event
2. mousewheel event is different between firefox and chrome, so I bind two events, which are `mousewheel` and `DOMMouseScroll`
### What is Expected?
Both events should work.

### What is actually happening?
It only works in chrome.

### My opinion
HTML attributes are case-insensitive, so `DOMMouseScroll` equals `dommousescroll` in HTML, and firefox does't have event named `dommousescroll`.

What should I do?

**Comment by sqal** [comment]
>What should I do?

Use wheel event - https://developer.mozilla.org/en-US/docs/Web/Events/wheel

**Comment by posva** [comment]
As @sqal said: https://jsfiddle.net/cpa9nbu5/
