### ISSUE TITLE
Dynamic values in array undefined in props ready method

### ISSUE THREAD

**Issue by avanerk** [vuejs/vue#3602]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/qta4ny91/

### What is Expected?
Have the dynamic array value props available in the components ready method.

### What is actually happening?
The dynamic array value props are undefined.

**Comment by posva** [comment]
That's working as expected since the array is intantiated while the stats object is still empty (because of the timeout)
I think you're looking to do something like this: http://jsfiddle.net/u7ydz6cp/

**Comment by avanerk** [comment]
If you open the console, you can see that the values are still undefined. Even when I remove the timeout it's still undefined. http://jsfiddle.net/7eyg09v2/

**Comment by posva** [comment]
@avanerk That's because the ready hook is fired **after** the compilation: http://vuejs.org/guide/instance.html#Lifecycle-Diagram
You can use `beforeCompile` but I recommend you using either a computed property or a method
