### ISSUE TITLE
v-model loses binding when used with dynamically bound type="radio" on <input> (v-model 在input 动态指定type时失效。)

### ISSUE THREAD

**Issue by wgbbiao** [vuejs/vue#3603]
### Vue.js version
2.0.0.rc-1

### 测试链接

https://jsfiddle.net/ouu5vj0f/1/

**Comment by fnlctrl** [comment]
没能重现
![_20160906114944](https://cloud.githubusercontent.com/assets/5557143/18261236/0dcf2e02-7428-11e6-879c-5c227eef70df.png)

**Comment by wgbbiao** [comment]
我可能没有说清楚，是input的value的值没有了。
https://jsfiddle.net/ouu5vj0f/3/

这是在1.0版本下的效果
https://jsfiddle.net/ouu5vj0f/4/

**Comment by fnlctrl** [comment]
既然是两个表单为什么要绑同在一个数组上？你给的第二个链接，点表单一的选项，表单二里面就全选上了，这是预期的行为？

**Comment by wgbbiao** [comment]
只有一组数据的时候，问题依然存在。这只是例子。
2.0.0.rc-4
https://jsfiddle.net/ouu5vj0f/5/

1.0
https://jsfiddle.net/ouu5vj0f/6/

**Comment by fnlctrl** [comment]
@wgbbiao 的确是bug
---------

This is a bug where v-model loses binding when used with dynamically bound `type="radio"` on `<input>`
e.g. `<input v-model="foo" :type="'radio'">`

working 1.0 example:
https://jsfiddle.net/nj9oLdt7/

bug with 2.0-rc.4:
https://jsfiddle.net/y54j15jm/

working 2.0-rc.4 example (with static `type="radio"`)
https://jsfiddle.net/y54j15jm/1/

**Comment by yyx990803** [comment]
This is never supported: `v-model` does not support dynamic types.

**Comment by wgbbiao** [comment]
@yyx990803 好吧，我想其它办法。
