### ISSUE TITLE
build mobile apps?

### ISSUE THREAD

**Issue by chovy** [vuejs/vue#3604]
Are there any plans to build a `vue native` similar to `react native` for developing native iOS and Android apps?

This is probably the one thing holding me back on using vue.js over react. I would eventually like to build native mobile apps for my product.

**Comment by fnlctrl** [comment]
Please use our [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask questions.

------

checkout [weex](http://alibaba.github.io/weex/) - it's a vue-native project powered by alibaba.
Currently it's the only one.
