### ISSUE TITLE
Data load as JSON string rather than JSON object on server.

### ISSUE THREAD

**Issue by rjchauhan** [vuejs/vue#3605]
![image](https://cloud.githubusercontent.com/assets/8499250/18262587/9fb4bda8-7420-11e6-91fb-66168c277c95.png)

![image](https://cloud.githubusercontent.com/assets/8499250/18262594/b4d6e3fa-7420-11e6-9890-bda27b35ba60.png)

The first screenshot is of local version of site, which is working file. 

The second screenshot is of production version of site and it's hosted on digital ocean. If you check the data objects on right hand side, data comes from API loading as a JSON string rather than JSON object. This break downs the whole application. The content type of API data is application/json.

**Comment by fnlctrl** [comment]
This is not related to vue, please check you http library that is responsible for http requests and api calls.
You're possibly missing a `JSON.parse`.

**Comment by rjchauhan** [comment]
Tried that already. If I use JSON.parse() it works on production but then it's started failing on local copy.

**Comment by fnlctrl** [comment]
@rjchauhan Check your API then.

**Comment by LinusBorg** [comment]
Further discussion/support possible on forum.vuejs.org :)

**Comment by LinusBorg** [comment]
Hint: I assume you use vue-resource, the production server is running HTTPs, and in chrome this means the `content-type` header is lowercase, but Vue-Resource expects `Content-Type`.

See this ticket for a workaround: https://github.com/vuejs/vue-resource/issues/317

Also, this was solved in the most recent release of vue-resource.

In the future, please open issues in the correct repository. This is the vue repository, not vue-resource.
