### ISSUE TITLE
[2.0]SSR with scoped style after refresh page in NODE_ENV=production

### ISSUE THREAD

**Issue by sarik93** [vuejs/vue#3606]
### Vue.js version
2.0.0-rc.4

### Reproduction Link

https://github.com/vuejs/vue-hackernews-2.0

### Steps to reproduce
If write scoped style in any component, for example UserView.vue add scoped - 
```html
<style lang="stylus" scoped></style>
``` 
After they:
```sh
npm run build && npm start
```
Open project to home page and go to user page (route in client-side) you can see normal style and normal attr data-v-#, but if you refresh user page you can see style not working and data-v-# changed.

### What is Expected?
After refresh page expected data-v-# not change and scoped style work.

### What is actually happening?
Scoped style not work because change data-v-#.

**Comment by fnlctrl** [comment]
Hi there, thanks for filling the issue, however scoped style is [vue-loader](https://github.com/vuejs/vue-loader)'s feature, so if you believe there is a bug, please open an issue there instead, thanks!
