### ISSUE TITLE
Handling transitions elements outside <router-view> 

### ISSUE THREAD

**Issue by cho-is** [vuejs/vue#3609]
Not clear in the docs if I need to use `router.beforeEach(hook)` and `router.afterEach(hook)` or Transition Hooks? Using Vue Loader and single file components and not sure, every time a route changes, where to write the hook for animating the header for instance?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Your question is too vague, make sure to make it clearer when asking it on the  forums or gitter :wink:

**Comment by cho-is** [comment]
There are a lot of similar questions with no answer on the forum you are referring to. Already checked a no luck.
