### ISSUE TITLE
Vue cannot detect the Change of Date

### ISSUE THREAD

**Issue by smalllong** [vuejs/vue#3613]
### Vue.js version
1.0.24

### Reproduction Link
https://jsfiddle.net/bsqgx1f9/5/

### Steps to reproduce
Add a Date as vue data, then change it.
### What is Expected?
the html change when the Date object change
### What is actually happening?
No change on html

**Comment by LinusBorg** [comment]
Vue does not watch methods of Date objects, so if you mutate it, Vue cannot recognize it.

You have to do this:
```
this.d. = this.d.setFullYear(2000);
```
