### ISSUE TITLE
dispatchEvent breaking model synchronization

### ISSUE THREAD

**Issue by iFarmGolems** [vuejs/vue#3614]
Hello, found this when I was trying to write unit tests for my module:

https://jsfiddle.net/iFarmGolems/cxc8cp34/

Why is this happening?

**Comment by iagafonov** [comment]
wrapping textarea in `<div id="app"> solves problem
[jsfiddle](https://jsfiddle.net/tvuudtff/)

**Comment by iagafonov** [comment]
in 2.0 works fine

**Comment by crswll** [comment]
This happens because the change event fires before the DOM gets a chance to update. Therefore, the v-model updates the value on that change event to what it was before the DOM gets a chance to update.

Here's an updated fiddle that works: https://jsfiddle.net/crswll/cxc8cp34/3/
