### ISSUE TITLE
Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by zuibunan** [vuejs/vue#3615]
### Vue.js version
2.0.0-rc.4

### Steps to reproduce
I have built an app , like vuex/example/chat, but more complex than it
the problem is sometimes when I switch the thread, 
the error occurred,
 like the pictures below
and then the view can not change any more, but the events can still trigger

my message list view has multiple types like text , audio, video, image etc
if I replace the complex html of different message item with a normal text item
then the app works well

the most maddening thing is the error is from vue.js , without  any clue of my code

the errors never happened when I used vue1.x ,  until I upgrade vuejs to 2.x

I am sorry I can't provide a demo

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/3386786/18304226/c65a33cc-7513-11e6-8313-e1d9dc88a30c.png)
![image](https://cloud.githubusercontent.com/assets/3386786/18304249/e5fb8c76-7513-11e6-8205-48102bc0cae1.png)

**Comment by fnlctrl** [comment]
We won't be able to help if there isn't a repro... Please do provide one.

By the way, this may have already been fixed by recent commits though,
which will land in rc.5 soon. You can wait untill then, and draft a repro
if the error persists.

**Comment by zuibunan** [comment]
Now I upgrade to Vue.js v2.0.0-rc.5
the error still occurred

**Comment by yyx990803** [comment]
Can't help you if you cannot provide a repro... I'll have to close this, feel free to reopen when you can provide one.
