### ISSUE TITLE
Maybe false alarm "Duplicate presense of slot found in the same render tree" warnings

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3642]
### Vue.js version
2.0.0-rc5

### Reproduction Link

https://jsfiddle.net/oldpig/zb4zLxkb/1/

### Steps to reproduce
Click any tab to switch

### What is Expected?
Tab switched, everything goes fine.

### What is actually happening?
There are warnings in console, multiple times each switch.

I am aware that this warning is introduced in rc.5. But I am not sure what goes wrong.

**Comment by posva** [comment]
This looks like an error, indeed. The `_rendered` property is never reset. Let me take a look

**Comment by kobezzza** [comment]
👍

**Comment by yyx990803** [comment]
I realized this after release... It's been fixed in 100a2969aa5c64bd71758c79881cf4531e9907be

**Comment by posva** [comment]
Well that'd explain why I was having a bad time trying to reproduce it 😆

**Comment by skyrpex** [comment]
Oh, I was going to create an issue for this, too. :ok_hand: I just created a [minimal jsfiddle](https://jsfiddle.net/skyrpex/95s0vjn4/3/) that reproduces the problem (just in case you want to add it to any test...).

That's great!
