### ISSUE TITLE
数据延迟加载显示undefined的问题

### ISSUE THREAD

**Issue by zhe-he** [vuejs/vue#3644]
当我实例化一个vue时，因为数据是通过请求过来的，获得的数据类似如下：
`data={
    "key": 111,
    "someArr": [{"key1":"1","key2":"2"},{"key1":"1","key2":"2"}]
}`
因为数据太多，实例化的时候不可能都设置默认值，所以页面显示了一堆的警告。

完整示例代码如下：
html:
`<div id="test">     
     <h2>{{key}}</h2>    
    <section track-by="$index" v-for="item in someArr">    
        <p>{{item.key1}}</p>    
        <p>{{item.key1}}</p>    
    </section>    
</div>`
js:
`new Vue({
    el: "#test",
    data: {},
    ready: function (){
        this.$http.jsonp(url).then(function (d){
            this.data = d.body;
        })
    }
})`

--------------------------------------------------------------------------------------------
当我改成：在请求后实例化 vue，但是页面的vue里面的模版标签被用户看见很不美好（v-cloak必须实例化没考虑），于是用了一个加载层挡住，代码如下：
`<div id="load">
    <div v-if="isWaiting">loading</div>
    <div id="main" v-if="!isWaiting">真正的内容页</div>
</div>`
当实例化load之后，发现报错，vue中不能嵌套vue，没办法只好分开，最后用的原生判断。

-------------------------------------------------------------------------------------------------------
我想知道 以上的问题 vue一般是怎么处理的，或者有没有类似的例子？

**Comment by wgbbiao** [comment]
this.data = d.body
this的作用域，可能错了。

**Comment by fnlctrl** [comment]
请使用论坛或gitter提问

----------------------

同上，this错了
```js
new Vue({ el: "#test", data: {}, ready: function (){ this.$http.jsonp(url).then((d) => { this.data = d.body; }) } })
```

**Comment by zhe-he** [comment]
代码中 this已修改
问题还是刚才那个问题，sorry，示例代码写错了

**Comment by fnlctrl** [comment]
如果不想显示undefined，就必须设置初值。通过v-for渲染的可以不需要初值。

**Comment by zhe-he** [comment]
好的，谢谢
