### ISSUE TITLE
When the official release of version 2.0？

### ISSUE THREAD

**Issue by Dreampie** [vuejs/vue#3645]

**Comment by fnlctrl** [comment]
Soon.

**Comment by Dreampie** [comment]
On npm no new version, must use the source code? Upgrade release too much trouble，soon

**Comment by fnlctrl** [comment]
https://github.com/vuejs/vue/releases

**Comment by Dreampie** [comment]
I hope npm,not add file in project

**Comment by fnlctrl** [comment]
`npm install vue@2.0.0-rc.5`
Please learn more about how npm works.

**Comment by Dreampie** [comment]
ok,thaks
