### ISSUE TITLE
Can i get all event listeners in Vue Components ?

### ISSUE THREAD

**Issue by KID-WuMeng** [vuejs/vue#3646]
I have a vue-component named v-button:

```
<template>
  <div @click="tap"></div>
</template>

<script lang="coffee">
  module.exports = 
    ready:->
      // Want to know how much tap event listener be registered.
    methods:
      tap:-> this.$emit('tap')
</script>
```

I use the component for example:

```
<v-button @tap="...">
```

Please look the component's ready method. My question is what is the way to get all event listeners or the count of listeners ?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however this issue tracker is reserved for bugs and feature requests.
Please use our [forum](http://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask questions.

**Comment by KID-WuMeng** [comment]
@fnlctrl I'm Sorry and Thanks
