### ISSUE TITLE
[2.0] Is there a way to use <transition-group> to animate on container resize ?

### ISSUE THREAD

**Issue by magne4000** [vuejs/vue#3647]
I'm unable to access the forum right now, so I though I'll ask here:
Can we somehow triger FLIP transitions when resizing `<transition-group>` component (or when resizing window, i.e., whenever it triggers a reflow) ?

**Comment by fnlctrl** [comment]
You can also use the [gitter](https://gitter.im/vuejs/vue). 
Please understand we keep usage questions out of this issue tracker as it's reserved for bug reports and feature requests.

**Comment by yyx990803** [comment]
Short answer is no. `<transition-group>` is only responsible for element insertion/removal/reorder caused by Vue re-render.
