### ISSUE TITLE
Property mutation with simple components

### ISSUE THREAD

**Issue by wwlsascha** [vuejs/vue#3648]
### Vue.js version
2.0.0-rc.5

### Reproduction Link
http://codepen.io/anon/pen/ORyJAa

### Scenario

Most of our applications are build with a huge amount of backbone.js or marionette code. Especially for simple components like selects, search dropdowns or autogrowing textareas, the combination of our existing application stack and vuejs (1) components made ui development much more simple and consistent (and fun too). 

For example: We've got complex form views (written in marionette), where you'll find sth. like:

```hamlc
%form{ ... }
  %our-input-component{ name: 'title', value: @title, large: 'true' }
  
  %our-select{ name: 'gender', value: @gender }
    %our-select-item{ value: 'f' } female
    %our-select-item{ value: 'm' } male

```

By extending marionette just a little, it works pretty good currently. The marionette views are listening to the components to change (e.g. from the input or select) and then propagating those changes to models.

### Problem

Now we've had a look on vuejs 2 (2.0.0-rc.4 and 2.0.0-rc.5). 

Let's take the select component example. The items were inserted through a slot. Clicking on an item will cause an event on the parent component. The select component manages it's value based on those events.

With vuejs 2, can't just change the value property due to the mutation warning:

```javascript
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value.
```

### Question 

Our implementations worked pretty much like polymer / webcomponents. With some marionette helpers, it was pretty simple to e.g. retrieve component attributes without knowing much internal stuff.

Now my question is, how those simple scenarios might be handled without maintaining some kind of global state or so?

**Comment by phanan** [comment]
Not sure if I get you right, but if you _absolutely_ need to do so, then you may use an _object_ for the prop, and modify its properties instead. Notice that this is an anti-pattern and props in 2.0 should be treated as immutable, so the result might be unexpected.

Also, please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by wwlsascha** [comment]
FYI: Asking here because the forum is often offline (500 cloudfare message or so).

**Comment by phanan** [comment]
@wwlsascha I see… Thanks for the info, we'll look into that. Meanwhile, Gitter is always open and friendly ;)

**Comment by wwlsascha** [comment]
Still cannot access the forum (Europe/Germany) and Gitter is not much helpfull currently... more an offensive argument :-P 

Maybe somebody can help me here directly - even if it doesn't meet the guidelines.

**Comment by yyx990803** [comment]
@wwlsascha I'm actually more concerned about your impression that the Gitter room is offensive - I haven't been paying much attention to it lately, could you elaborate on that?

**Comment by wwlsascha** [comment]
@yyx990803 Just some minutes ago. But that's not really the point. Can't access the forum time to time and it's hard to get help if not here...

**Comment by yyx990803** [comment]
@wwlsascha the point is we don't answer questions here - if we make an exception, then everyone will just start asking questions in issues.
