### ISSUE TITLE
Class Binding and Removing Class in DOM

### ISSUE THREAD

**Issue by mapodev** [vuejs/vue#3649]
Hey,

is it possible to have binding in the `v-bind:class="{'test':test}"` when also removing the class. What I mean by this, for example we have `<div v-bind:class={'test':test}>Stuff</div>`

and a Vue Instance

``` 
new Vue({
   el: "#stuff",
   data: {
     test: true
   }
});
```

Now when I remove the class in the DOM like this `$("div").removeClass("test");` I would expect to have `data.test = false` after removing the class from the div.

**Comment by fnlctrl** [comment]
No. Vue doesn't react to your manual Dom manipulations.

**Comment by mapodev** [comment]
But could this be a Feature Request?

**Comment by fnlctrl** [comment]
No. It is against the fundamental assumption upon which Vue works: you do
not manipulate Dom yourself (or with other libs)
