### ISSUE TITLE
v-model for input['datetime-local'] not binded

### ISSUE THREAD

**Issue by WingGao** [vuejs/vue#3652]
### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/bsqgx1f9/7/

### Steps to reproduce
Fill the datetime input.

### What is Expected?
 The object didn't binded

**Comment by yodfz** [comment]
myDate is didn't watch!
look this http://vuejs.org/guide/reactivity.html.
you can need

var vm = new Vue({
                el: '#app',
                data: {
                		anObject: {myDate :''},
                },
                ready(){
                	//alert('ready');
                	this.anObject.myDate ="2001-01-02T00:00:00"
                },
                methods: {
                    change: function() {
                        this.d.setFullYear(2000);
                        alert('changed');
                    }
                }
            });

**Comment by fnlctrl** [comment]
If you want an object's property to be reactive, please declare it upfront, or use `Vue.set`. 

http://vuejs.org/guide/reactivity.html#Initialize-Your-Data

> Although Vue.js provides the API to dynamically add reactive properties on the fly, it is recommended to declare all reactive properties upfront in the data option.
