### ISSUE TITLE
Add link from offical docs to RC docs

### ISSUE THREAD

**Issue by markmarijnissen** [vuejs/vue#3653]
As somebody new to vue, I decided to start with vue 2, as it seems to be very close to an official release.

I was using v1 docs as the API didn't appear to have changed much.

Took me a week to find out there is actually rc.vuejs.org. It was mentioned in some newsletter.

It would be a major help for developer new to vue if the documentation could be more easily found. For example, just link to it from the official docs.

**Comment by posva** [comment]
@markmarijnissen Did you look for the v2 docs at some time? If so where did you expected to find the information?

**Comment by markmarijnissen** [comment]
I found the v2 docs in an old newsletter. Before I assumed the weren't
written yet. I expected a link in the current v1 docs.

Op za 10 sep. 2016 18:38 schreef Eduardo San Martin Morote <
notifications@github.com>:

**Comment by posva** [comment]
I see. Did you expected the link on the version select?
I think that adding it there plus some "Looking for vue 2 docs? Click here" in the homepage is enough.
Do you think that is enough?

**Comment by markmarijnissen** [comment]
Yes! Both options are fined. I expected them in drop-down, and would
definitely have noticed at homepage. The incomplete warning at rc docs is
loud and clear

Op za 10 sep. 2016 18:47 schreef Eduardo San Martin Morote <
notifications@github.com>:

**Comment by zeratulmdq** [comment]
+1

I keep up to date with all the changes and I wasn't aware of the RC guide until yesterday. I think a link just below the "Getting started" title would be nice.

**Comment by chrisvfritz** [comment]
To provide more context, the lack of links to the 2.0 guide is actually intentional. Many parts are still being actively revised and there are a few API changes that haven't made it in yet. The migration guide also isn't yet complete, which I imagine may be the first stop for many current Vue users.

**Comment by chrisvfritz** [comment]
I think it might be good to hold off on adding a link - at least until the migration guide is done, which will _hopefully_ be within a few days.

**Comment by posva** [comment]
There's a PR on vuejs/vuejs.org#399
Closing this because it belongs to that repo instead
