### ISSUE TITLE
[Vue 2.0] Issue with styles as array and reactivity

### ISSUE THREAD

**Issue by probil** [vuejs/vue#3657]
First of all, thank you for you work. Vue.js is awesome :sunglasses: 

But I have an issue with reactivity and style binding as array in Vue 2.0-rc.5 . I have used this syntax:
```
:style="[object1,object2]"
```
In this case `object2` used only one on init render. When I change `object2` prop, actual `style` is not changed. Even through I can see changes in devtools. So it's not reactive. It [was working](https://jsfiddle.net/probil/6f7r6b8b/) on Vue 1.X without such issue at all.

If it's not a bug but feature (I don't think so), please, describe it in docs.

### Vue.js version
2.0.0-rc.5

### Reproduction Link
First one (with computed properties)
https://jsfiddle.net/probil/ztcrvLeo/

Second one (simplier)
https://jsfiddle.net/probil/017Lqvvh/

### Steps to reproduce
1. Create two objects in `data()` -> `object1` and `object2`. 
2. Describe some styles in `object1`. In `object2` describe `backgroundImage`
1. Create element with `:style=[object1,object2]`
2. Change `backgroundImage` to another image of `object2` (on button click for example)
3. See no changes on the screen

### What is Expected?
Images should be changed. It works great in Vue 1.X . Proof link https://jsfiddle.net/6f7r6b8b/2/

### What is actually happening?
Images is is not changed. Even through I see actual changes in `vue-devtools`.

**Comment by fnlctrl** [comment]
You 1.x link is actually using 2.0... Here is a fixed one https://jsfiddle.net/6f7r6b8b/2/
2.0 docs for it :http://rc.vuejs.org/guide/class-and-style.html#Array-Syntax-1, so maybe it's a bug (or the part in the docs isn't updated to reflect a deprecation).
