### ISSUE TITLE
Stagger attribute not working for transitions

### ISSUE THREAD

**Issue by thelucre** [vuejs/vue#3658]
**Version**: 1.0.26

**Demo**: http://codepen.io/thelucre/pen/WGQaPd

**Steps**: Rendering a list with a `stagger` attribute and value has no affect on the transition timing

**Expected**: The stagger value should add incremental transition delay to each item in the `v-for` list

**Comment by fnlctrl** [comment]
Stagger transition with v-for is only triggered when there is a change in the data, so it doesn't work with v-if.
http://codepen.io/fnlctrl/pen/RGWOPJ
