### ISSUE TITLE
vue 2.0 can't use filter in v-html

### ISSUE THREAD

**Issue by anysome** [vuejs/vue#3660]
DON'T WORK
&lt;label v-html="item.latestMessage.content | deluxe"&gt;&lt;/label&gt;

CAN WORK, but html code escaped.
&lt;label&gt;{{item.latestMessage.content | deluxe}}&lt;/label&gt;

**Comment by LinusBorg** [comment]
This is expected. Filters only work in interpolations (`{{}}`) in Vue 2.0
