### ISSUE TITLE
vue-template-compiler generates broken code for escaped ampersands in attributes

### ISSUE THREAD

**Issue by trikadin** [vuejs/vue#3662]
```html
<div v-if="bla &amp;&amp; baz">
Valid HTML. Doesn't work.
</div>
```
![image](https://cloud.githubusercontent.com/assets/1655230/18434497/25153f16-78f6-11e6-9ec5-a0c438caeed2.png)

**Comment by fnlctrl** [comment]
It is valid html, however the compiler is expecting javascript expressions for directive and interpolations (such as {{ }})), and in fact they are directly used as javascript expressions afterwards, so please don't escape these characters.
