### ISSUE TITLE
[Recommend]:why not add v-elif directive?

### ISSUE THREAD

**Issue by Telanx** [vuejs/vue#3665]
**why not add v-elif directive?**
希望Vue支持v-elif指令配合v-if v-else使用

**Comment by fnlctrl** [comment]
这个问题已经讨论过了，见https://github.com/vuejs/vue/issues/2353。

**Comment by octolink** [comment]
This is an excellent idea. A block like this:

    <template v-if="obj.open">
      <a class="button">Now is the time</a>
    </template>
    <template v-else>
      <a v-if="obj.over" class="button disabled">Too late</a>
      <a v-else class="button disabled">Too early</a>
    </template>

Could look like this:

      <a v-if="obj.open" class="button">Now is the time</a>
      <a v-elif="obj.over" class="button disabled">Too late</a>
      <a v-else class="button disabled">Too early</a>

Way easier to read.
