### ISSUE TITLE
2.0.0-rc.6 breaks "beforeRouteEnter" hook

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3667]
### Vue.js version
2.0.0-rc6 & vue-router 2.0.0-rc4

### Reproduction Link

https://jsfiddle.net/oldpig/zw5ncxso/1/

### Steps to reproduce
run 

### What is Expected?
Should log `typeof vm` as `object` in console
 
### What is actually happening?
`vm` is undefined

This issue is introduced in rc.6, fine in rc.5.

**Comment by yyx990803** [comment]
This will be fixed in a new release for vue-router.
