### ISSUE TITLE
Objects with `v-bind` fails with components.

### ISSUE THREAD

**Issue by Kingdaro** [vuejs/vue#3670]
### Vue.js version
2.0 rc6 (also said not to work in 1.0.26)

### Reproduction Link
https://jsfiddle.net/Kingdaro/mzLkbo8p/

### Steps to reproduce
Create an object with props. Pass in the object to assign its keys as props to a component, as documented [here](http://rc.vuejs.org/api/#v-bind).

### What is Expected?
Both lines should output "Value is: foo"

### What is actually happening?
The first example when passing a single prop works fine. The second does not receive "value" from the object passed to `v-bind`.

**Comment by AlexandreBonaventure** [comment]
Is this going to be fixed in 1.x ? Thanks
