### ISSUE TITLE
manual transition triggering

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#3677]
I'm currently in the situation, that I need the dimensions of an element *before* transition. 
(dropdown / tooltip should change opening direction when they won't fit in the viewport)

In this case I even want to use `v-if` - the implementation is a nightmare:
Open:
- set `transition` to `null`
- set `v-if` and `v-show` to `true`. Apply style `opacity: 0`
- wait a tick
- calculate dimensions. Set `v-show` to `false`. Apply style `opacity:null`. Set the desired `transition`
- wait a tick
- set `v-show` to `true`

Close:
- set `v-show` to `false`
- set `transition` to `null`
- wait for transition to end
- set `v-if` to `false`

these solutions come to my mind:
- don't use vue transitions (my first approach - but I want to provide a good usability for my standalone components - allow the user to use what he knows)
- make a directive similar to `v-show` which uses `opacity` or `visibility` instead of `display`
- allow manual transition triggering (which I prefer)

**Comment by fnlctrl** [comment]
Transition hooks are designed for this, check it out: http://vuejs.org/guide/transitions.html#JavaScript-Transitions
You can retrieve dimensions inside `enter` hook, and call `done` after that to start the transition.

**Comment by paulpflug** [comment]
related to #3678. 

I want to use a user generated transition inside a custom component. 
I see no way to access transition hooks.

**Comment by fnlctrl** [comment]
> I want to use a user generated transition inside a custom component. 
> I see no way to access transition hooks.
That's a different topic, and I'll continue explaining in 3678
