### ISSUE TITLE
[2.0] Class binding removes externally added class

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#3679]
### Vue.js version
v2.0.0-rc.5

### Reproduction Link
https://jsfiddle.net/h7mz81oo/5/

### Steps to reproduce

1. Add a `:class` binding to an element, and also add a class to that element using DOM methods (`this.$el.querySelector('span').className += " external-class";`).

2. Update the `:class` binding

### What is Expected?
The class added using DOM methods should sill be present on the element along with the class added via vue binding

### What is actually happening?
The class added using DOM methods is removed and only the class added via vue binding remains

**Comment by yyx990803** [comment]
This is expected behavior in 2.0. If you use Vue to manage the class then all class manipulation needs to happen theough Vue.

**Comment by cnweibo** [comment]
@yyx990803 , i think, it will be better if we only handle the bounded className under vuejs management. In many cases, one tag has some other pre-populated class which is not under vuejs control. The behaviour works perfect under vuejs1.0
