### ISSUE TITLE
vue-element is deprecated

### ISSUE THREAD

**Issue by davidtorroija** [vuejs/vue#3681]
Hi, 
With the vue 0.11 version vue-element is working fine, but when I use the bue 1.0.26 version, the shadow dom is not working, the app fires attached event and also dettached event, also overrides the app's div content
see the fiddle below:

https://plnkr.co/edit/eUZLfHIdtWoCdjp67MPb?p=preview

**Comment by posva** [comment]
That's because it's not supported by Vue 1. It's on the readme https://github.com/vuejs/vue-element#requirements

**Comment by davidtorroija** [comment]
> yyx990803 commented an hour ago
> Yes, this library needs to be updated, partly to be compatible with newer versions of Vue and also newer versions of custom element and shadow dom specs. We will look at this after 2.0 launch.

@posva next time please inform better before respond the question

**Comment by posva** [comment]
Sure, I'll try to use a time machine in the future! 😄
