### ISSUE TITLE
Case sensitive attributes do not preserve casing when bound

### ISSUE THREAD

**Issue by nhydock** [vuejs/vue#3685]
### Vue.js version
1.0.23

### Reproduction Link
https://jsfiddle.net/vv6oaqmh/

### Steps to reproduce
Bind a case sensitive attribute, such as SVG's `viewBox` attribute with a value.  

### What is Expected?
Case sensitivity should be preserved

### What is actually happening?
When the view is updated, the attribute will no longer be properly cased

**Comment by yyx990803** [comment]
Use the `.camel` modifier:

``` html
<svg :view-box.camel="xxx">
```
