### ISSUE TITLE
Directives map inside vnode.data.directives [vue2]

### ISSUE THREAD

**Issue by wszerad** [vuejs/vue#3687]
In my case I want to get value of v-model from another directive. Currently I need loop to iterate through directives so access is difficult. Shouldn't be vnode.data.directives object like vnode.data.attrs or hybrid like vnode.elm.attributes? ({0: v-model, model: v-model, length: 1})

```
//now
{
  update(el, bind, vnode, oldVnode) {
    var dir = vnode.data.directives;
	for(var i=0; i<dir.length; i++) {
		if(dir[i].name === 'model') {
			if(dir[i].value !== oldVnode.data.directives[i].value) {
				 //do something
			}
			
			break;
		}
	}
}

//future?
{
	update(el, bind, vnode, oldVnode) {
		if(vnode.data.directives.model.value !== oldVnode.data.directives.model.value) {
			//do something
		}
	}
}
```

**Comment by yyx990803** [comment]
This is intentional. Directives may have multiple bindings on the same element due to different modifier/argument combinations.
