### ISSUE TITLE
how to pass v-modal Dynamically 

### ISSUE THREAD

**Issue by shireen22** [vuejs/vue#3688]
vue.js version v1.0.26

view
 <template v-for="urnItems in pfc.gpl_items.urns">

                                <tr :class="selected_data.urn.indexOf(urnItems.id) >= 0 ? 'text-primary' : ''">
   <td>
                                        <input type="number" max="100" maxlength="3" class="txt-form"
                                               style="width:50px;"
                                               v-model="selected_data.urn_qty[urnItems.id]"
                                               :value="urnItems.qty">
                                    </td>
 </template>

---------------------------------------------------------------------------
in vue.js
 , 'selected_data.urn': function (value, oldValue) {

                var urns = this.pfc.gpl_items.urns;
                var selected_urns = this.selected_data.urn;
                var firstSelectedId = selected_urns[0];

                if (typeof selected_urns[0] === 'undefined') {
                    this.selected_data.selected_urn_name = '';
                    this.selected_data.selected_urn_price = '';
                    return;
                }

                this.selected.selected_urn_other_name = [];
                this.selected.selected_urn_other_price = [];
                this.selected.selected_urn_qty = [];
                this.selected_data.urn_qty = [];

                for (var urn in urns) {
                    for (var sdataurnindex in this.selected_data.urn) {
                        if (urns[urn].id == this.selected_data.urn[sdataurnindex]) {
                            if (firstSelectedId) {
                                this.selected_data.selected_urn_name = urns[urn].name;
                                this.selected_data.selected_urn_price = urns[urn].price;

                            } else {
                                this.selected_data.selected_urn_other = '';
                                this.selected_data.selected_urn_price = '';
                            }
                            //    this.selected.selected_urn_other_name.push(urns[urn].name);
                            //   this.selected.selected_urn_other_price.push(urns[urn].price);
            this.selected_data.selected_urn_qty.push(this.selected_data.urn_qty[this.selected_data.urn[sdataurnindex]]);

                        }

                    }
                }
                console.log(this.selected_data.urn_qty);
            }

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions.
