### ISSUE TITLE
Is there a way to watch $children in computed?

### ISSUE THREAD

**Issue by smalllong** [vuejs/vue#3690]
### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/85uw2gyb/

### What is Expected?
I want to make a checkable tree using vuejs. The checkboxes on the parents are computed from the leaves under them. At first, I tried to use $children in computed to compute the checked state of parents, but I found that $children is **not reactive**, which is said at https://github.com/vuejs/vue/issues/3316. So I turned into using a function to recursively check the state of the leaves under that parent. This works. But the question is that this recursion runs on every parent, without taking advantage of the result of his children, making it **slow**. So is there a way to do this more efficiently? And why $children can't be reactive in computed? Is there any technical difficulty?

**Comment by yyx990803** [comment]
Think of it this way: both the checkboxes AND `$children` should be derived results from the same underlying state. Instead of rendering checkboxes based on `$children`, they should be rendered based on the **state** that determines `$children`, which you already have and is reactive.
