### ISSUE TITLE
android webview 如何调用vuejs中methods事件?

### ISSUE THREAD

**Issue by JaneCC** [vuejs/vue#3692]
android webview 如何调用vuejs中methods事件?

**Comment by smalllong** [comment]
与网页中并无差异

**Comment by fnlctrl** [comment]
请使用[论坛](http://forum.vuejs.org/)提问。

----------------

安卓原生和web通信需要由原生向web注入一个对象

**Comment by 515580096** [comment]
mWebView.loadUrl("javascript:showResult('" + resultStr + "')");  这样并不能解决。not working,  anyone could make it ?

**Comment by iceuncle** [comment]
how to resolve?

**Comment by yuxingfafu** [comment]
@515580096 你那边是否解决了y呀？？？我也正遇到这个问题

**Comment by iceuncle** [comment]
可以调用window方法，然后用eventbus发通知解决

**Comment by yuxingfafu** [comment]
@iceuncle 什么意思？我这边原生的是要提供一个异步的方法给js调用。用html写js会回调，vue的不会。
![image](https://user-images.githubusercontent.com/7764483/29355763-db18cc2a-82a4-11e7-9205-be212c8fed72.png)
![image](https://user-images.githubusercontent.com/7764483/29355771-e3fa4878-82a4-11e7-8aa6-26945ed009c9.png)

**Comment by yuxingfafu** [comment]
@iceuncle 能否帮忙看看的呀谢谢了

**Comment by yuxingfafu** [comment]
https://forum.vuejs.org/t/vue/9434/7
哪位哥们有遇到过并且解决的帮忙看看谢谢

**Comment by iceuncle** [comment]
你原生调用js的方法，需要将方法挂载在window上，然后在方法体里用eventbus发通知，在vue里接收通知处理就好了

**Comment by iceuncle** [comment]
vue有内置eventbus

**Comment by yuxingfafu** [comment]
@iceuncle  将方法挂载到window是指?方便贴下代码么？

**Comment by yuxingfafu** [comment]
哪位哥们能够帮忙解答下，非常感谢!这个问题找了好久

**Comment by yuxingfafu** [comment]
created里面添加
window.functionName=this.functionName;
就可以了，公司的一个同事解决了这个问题。
