### ISSUE TITLE
[vue@2.0.0-rc.6] props default not works when propsData is undefined in instance creation, 1.0 is ok

### ISSUE THREAD

**Issue by jokeryu** [vuejs/vue#3693]
### Vue.js version
2.0.0-rc.6

### Reproduction Link
https://jsfiddle.net/qgey2hkn/

### Steps to reproduce
Open reproduction links, check alert

### What is Expected?
alert `true`

### What is actually happening?
alert `undefined`

But if passing propsData, it alerts `true`.

**Comment by rajibahmed** [comment]
I think I saw in the docs you must initialise every props. Vue2 and Vue1 has different philosophy on this issue.

**Comment by LinusBorg** [comment]
Root components can't have props in 2.0. It works for child components:

https://jsfiddle.net/5naacdqL/1/
