### ISSUE TITLE
Vue (2.0rc6) with webpack (using vue-cli) - simple root component without template doesnt work.

### ISSUE THREAD

**Issue by dmaker3000** [vuejs/vue#3694]
### Vue.js version
2.0rc6. using Vue-Cli Webpack-simple 

### Steps to reproduce
main.js (modified from original):
`import Vue from 'vue'`
`new Vue({`
`  el: '#app',`
`  data:{`
`      msg: 'a simple message!'`
`  }`
`})`

index.html (modified from original generated by vue-cli):
`<body>`
`  <div id=app>`
`    <h1> {{ msg }} </h1>`
`  </div>`
`  <script src="dist/build.js"></script>`
`</body>`

### What is Expected?
Msg to display correctly.

### What is actually happening?
nothing happens.
works without webpack (v2.0rc6) , as well as version 1.0 with webpack though.

**Comment by LinusBorg** [comment]
Hello @dmaker3000,

thanks for filing this issue.

Zhis is not a bug, however.

`import Vue from 'vue'` imports the 'runtime-only build', which does not support in-HTML templates.

https://rc.vuejs.org/guide/installation.html#Note-on-NPM-Builds
