### ISSUE TITLE
camelize comment typo

### ISSUE THREAD

**Issue by monkindey** [vuejs/vue#3696]
one comment about **camelize** function, 
which can be found in [this line](https://github.com/vuejs/vue/blob/dev/src/util/lang.js#L170)

```javascript
/**
 * Camelize a hyphen-delmited string.
 *
 * @param {String} str
 * @return {String}
 */
```

Did the **delmited** word mean the **delimited** ？

**Comment by posva** [comment]
Yes, it does. If you could submit a PR for this, that'd be great 😄

**Comment by monkindey** [comment]
ok, i submit a PR, you can check it. Thanks!

**Comment by posva** [comment]
Thanks, don't worry about that 😉
