### ISSUE TITLE
how to user the webpack code splitting with vue filters?

### ISSUE THREAD

**Issue by wenkanglin** [vuejs/vue#3697]
we can use resolve just like components:
component: resolve => require(['component'], resolve)
but it doesn't work with:
filter: resolve => require(['filter'], resolve).
is there any way to solve it?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
