### ISSUE TITLE
Click event callback was triggered for twice if wrap a checkbox and label

### ISSUE THREAD

**Issue by xuzicn** [vuejs/vue#3699]
### Vue.js version
1.0.26

### Reproduction Link
http://codepen.io/xuzicn/pen/vXXmrb

### Steps to reproduce
Click the 'test' label, the "trigger" property increases 2. but its value increases 1 if just clicking on the checkbox.

### What is Expected?
increasing step should be 1.

### What is actually happening?
The testClicked callback was called for twice.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Unfortunately this is browser behavior: When you click on a `<label>` for an <input>, a click event will automatically be triggered on the `<input>`, so the outer div receives 2 events, one from label, one from input.
You can work around this by adding @click.prevent on the `<label>`: http://codepen.io/fnlctrl/pen/Xjjgdk

**Comment by bpossolo** [comment]
Given what @fnlctrl said, you could just have the click handler on the input element.
That will spare you having to add the `@click.prevent` on the label.
