### ISSUE TITLE
$event in template contains emitted value instead of event.

### ISSUE THREAD

**Issue by asvae** [vuejs/vue#3708]
### Vue.js version
2.0.0-rc.6

### What is Expected?
Error of some kind. I'm splicing **event** from array of **images**. That shouldn't work, right?

### What is actually happening?
No error.

---------------------------

So this is mostly naming issue. I suggest leaving `$event` for DOM events and use `$argument` for custom events.

**Comment by yyx990803** [comment]
There's no "event object" for custom events emitted via `$emit`. It just passes along arguments. http://rc.vuejs.org/api/#vm-emit

**Comment by asvae** [comment]
@yyx990803 Why is it called $event then? Is it intended?

**Comment by yyx990803** [comment]
`$event` is just the alias for the first argument in all `v-on` handlers.
