### ISSUE TITLE
why v-text can't use filter in 2.0

### ISSUE THREAD

**Issue by xusimin1008** [vuejs/vue#3716]
where I define a filter, but it has no effect,
`<span v-text="'abcdef' | strLimitBy(2)"></span> `

it has effect like
`<span>{{ "abcdef" | strLimitBy(2) }}</span>`

and why?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

----

filters can only be used on text interpolation in Vue 2
