### ISSUE TITLE
Can't access to action methods in created hook of component.

### ISSUE THREAD

**Issue by robynico** [vuejs/vue#3717]
### Vue.js version
2.0.0-rc.6 / vuex : v2.0.0-rc.5

### Reproduction Link
https://jsfiddle.net/robynico/41vz5tx4/

### Steps to reproduce
Nothing, when created method of component is called, component instance can't access to action method (init). This one is undefined whereas we can call it with the init button.

### What is Expected?
Like in vuejs 1.0.x : call action method in created hook.

### What is actually happening?
action method undefined in created hook

**Comment by LinusBorg** [comment]
don't use arrow functions in hooks. `this` will not point to the vm instance.https://jsfiddle.net/Linusborg/41vz5tx4/19/

**Comment by robynico** [comment]
thx for explanation !
