### ISSUE TITLE
Null prop is not passed through validation

### ISSUE THREAD

**Issue by dodas** [vuejs/vue#3720]
### Vue.js version
1.0.26 & 2.0-rc.6

### Reproduction Link
https://jsfiddle.net/af5aLyks/

### Steps to reproduce
See console output

### What is Expected?
I was expecting value of `null` will not pass both (1) type check (2) validator check.

### What is actually happening?
It looks like it is actually not even passed through these checks and value `null` will remain on this property.

**Comment by yyx990803** [comment]
`null` prop always skip validation. If you want to prevent it use `required: true`.
