### ISSUE TITLE
Default prop value function called on any prop change

### ISSUE THREAD

**Issue by dodas** [vuejs/vue#3721]
### Vue.js version
2.0-rc-6

### Reproduction Link
https://jsfiddle.net/u9opaam1/1/

### Steps to reproduce
Open console, wait 3 seconds.

### What is Expected?
Function for generating default value for prop should be called only on initialization of component, or when this property changes and does not have value.

### What is actually happening?
Function is called when ANY of props changes.

**Comment by yyx990803** [comment]
This is expected behavior in 2.0 because the component is rendered with new props (which need to be re-calculated).
