### ISSUE TITLE
[2.0]Render method creating element svg in IE/MS Edge not working correctly

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#3722]
### Vue.js version
2.0.0-rc.6

### Reproduction Link
https://jsfiddle.net/uriziel01/s9nr8znh/

### Steps to reproduce
Watch the fiddle result ;)

### What is Expected?
Yellow circle should appear.

### What is actually happening?
Nothing appears. If You inspect DOM the element is there, just not visible at all.

Everything works fine in Chrome/Firefox/Opera. It just fails in IE/Edge.

EDIT:
And a small coment from last moment, I've just checked that fiddle on 14931 insider build of Windows 10 (public beta version) and it seems that Edge is fixed there, but IE still failing. And and of course in regular Windows 10 build both of them are still failing.

**Comment by yyx990803** [comment]
This is not related to Vue - setting `innerHTML` of SVG elements simply doesn't work in IE: https://jsfiddle.net/yyx990803/zsg36wjq/

**Comment by belichuk** [comment]
IE doesn't currently support the innerHTML method on SVG Elements. The alternative solutions is the InnerSVG polyfill which allegedly works in Internet Explorer 9 and newer.

https://jsfiddle.net/zsg36wjq/3/
