### ISSUE TITLE
Need a way to (de)activate component watchers as needed

### ISSUE THREAD

**Issue by 1player** [vuejs/vue#3723]
I'm working on a virtual list component to render a huge list (1000+ rows, can't paginate) with Vue 2.0.

I've got the basics done, but in the latest iteration of my prototype I'm replacing the components out of view with placeholder divs (with just a height set). When one scrolls up and down, the placeholders are replaced with the actual component vnodes, created from scratch.

Creating and removing component vnodes (actually, replacing when with empty placeholder divs) will initialize and teardown the watchers, making the scrolling a bit janky. I've been reading the source code for hours to see if it's possible to cache the component vnodes somehow, but I'm on the bleeding edge here and testing the limits of the new vdom implementation.

Anyway, I'm implementing the virtual list to limit the reactive changes only to the items visible on screen, to have great performance even with thousands of items, and one possible way to do this would be to deactivate the watcher for items outside the viewport, and reactivate them when they are visible again. There doesn't seem to be a way of doing so. vm.$destroy tears down the handlers, but I don't need to destroy the element completely and removing it from the parent, just deactivating the watchers so reactive changes won't affect them.

Thoughts?

**Comment by 1player** [comment]
I have found an unorthodox way to pull this off:  when I render an item component, hook the init function and manually disable the watcher. I then store the item vnode into a cache:
```
var item = h(itemCtor, {
    hook: {
        init: function(vnode) {
            vnode.child._watcher.active = false
        }
    }
});
this.itemCache[id] = item;
```

Then, when I later know whether or not the item is visible, I just get the vnode from the cache and enable/disable the watcher.

It's just a crazy hack, but boy, it works and it's snappy. Also, on further "render" calls, if the item list hasn't changed, I just reuse the vnodes in the itemCache, even though reusing vnodes is bad (or so I've read in the WIP documentation).

Still, we might want an officially sanctioned way to do something like this.

**Comment by yyx990803** [comment]
So you are trying to implement a virtual scroll list container, but I'm not sure if you are going in the right direction - if I were doing it I'd just let the render function return the items that should be rendered in the viewport.

I'm interested too see something like that, but I don't think the "deactivate watcher" approach is something I'd consider. Something like [react-virtualized](https://github.com/bvaughn/react-virtualized) may be a useful reference.
