### ISSUE TITLE
Unable to use v-else and v-for in a same element?

### ISSUE THREAD

**Issue by HanSon** [vuejs/vue#3725]
I can use v-if and v-for in the template element,  but when I use v-else and v-for after that, it can't not be compile , is it a bug?

**Comment by jingman** [comment]
Can you please provide a [jsfiddle](jsfiddle.net) that reproduces this?

**Comment by HanSon** [comment]
@jingman https://jsfiddle.net/ba9u4sw1/1/ thanks

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
When you use `v-if` with `v-for` on the same element, `v-if`'s scope is limited on that element. (and this means `v-if` is evaluated for every item)
So you need to use `v-if` on an outer tag.
https://jsfiddle.net/xfab1mse/

**Comment by HanSon** [comment]
@fnlctrl Thanks,I know this way can work , but I'm wondering why use v-if can work but v-else can not work.

**Comment by fnlctrl** [comment]
`v-else` is a special directive because it depends on the previous `v-if`,
in other words they need to be in the same scope, while using v-if with
v-for on the same element limits `v-if`'s scope on that element, so it
can't be reached by `v-else`.
