### ISSUE TITLE
v-bind global function

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#3727]
### Vue.js version

1.0.23
### Reproduction Link

http://jsfiddle.net/e035jvj6/
### Steps to reproduce

in comp:

``` coffee
props:
  coerce:
    type: Function
```

``` html
<comp :coerce="Number"></comp>
```
### What is Expected?

`this.coerce === Number`.
Or at least a error if global functions are not allowed
### What is actually happening?

silently fails:
`this.coerce === undefined`

**Comment by defcc** [comment]
@yyx990803 how about build the makeGetterFn with **WITH**,  the global function  problem could be resolved as there is no need to replace path with **scope.**

**Comment by sirlancelot** [comment]
I updated the JSFiddle to use Vue@1.x: http://jsfiddle.net/e035jvj6/2/

I also switched the test to use `typeof` so that the problem gets better visibility.

The output should read `"function"` but instead it reads `"undefined"`

In Vue@2.x this isn't a problem.
