### ISSUE TITLE
Literal string in Vue 2.0 directives

### ISSUE THREAD

**Issue by matkovsky** [vuejs/vue#3728]
In Vue 2.0 there is a way to get the `value`, as well as the `expression` from a directive. And that's great. But there are times when I just want to pass down a string. A simple string, as it is. In those cases, however, Vue warns me that the data does not exist.

In Chrome it's a simple warning:

![chrome](https://cloud.githubusercontent.com/assets/1693178/18777401/384dfb28-816f-11e6-85b0-206d0dfb574b.png)

In Safari the JavaScript fails to load:

![safari](https://cloud.githubusercontent.com/assets/1693178/18777402/3916e1d2-816f-11e6-8757-d11eed495370.png)

Is there a way to explicitly tell Vue 2.0 that the value should not be interpreted as an expression other than writing `v-mydirective="'whatever simple string'"`?

(The directive I'm using in the examples is this one: https://github.com/matkovsky/vue-svg-directive/tree/vue2)

Thanks.

**Comment by LinusBorg** [comment]
> Is there a way to explicitly tell Vue 2.0 that the value should not be interpreted as an expression other than writing `v-mydirective="'whatever simple string'"`?

No. 

Even if we provided a ``.literal` modifier, that would take more characters to type than a simply quoting the `'string'`, so I don't see an advantage in that.

**Comment by matkovsky** [comment]
While that could be _a_ solution, my thoughts revolved more around making this a "setting" in the directive object itself (by setting `literal: true` before `bind()`, or something like that).

**Comment by posva** [comment]
@matkovsky No, because that'd make directives behaviour inconsistent. Some will secretly accept only literals without any way for the user to detect that by just looking the markup

**Comment by matkovsky** [comment]
@posva Oh, I see. Understood. :)
