### ISSUE TITLE
">" in pug doesn't work 

### ISSUE THREAD

**Issue by didiself** [vuejs/vue#3731]
pug:
`li(v-for="(item,index) in dataList",v-if="index >= 6")`

output:
`template syntax error - invalid expression: v-if="index &gt;= 6"`

vue  "version": "2.0.0-rc.6"
pug  "version": "2.0.0-beta6"

test jade@1.11.0 in vue@1.0.26 is work!!

**Comment by posva** [comment]
That's a problem with jade escaping the `>`. Please open an issue there

**Comment by ktsn** [comment]
Workaround is just use `!=`.
https://pugjs.org/language/attributes.html#unescaped-attributes

**Comment by didiself** [comment]
if use '!=' ,Module build failed;

so I can't use '>' or '<' in pug for vue???

now, I used computed to this effect.
