### ISSUE TITLE
v-model with uninitialized property

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#3732]
### Vue.js version
2.0 rc

### Reproduction Link
http://codepen.io/anon/pen/xEqbmN?editors=1010#0

### What is Expected?
Not sure if this is what is expected in Vue 2.0. Tried to search but couldn't find anything. 
e.g:
```javascript
data: {
  model: {
    a: ''
  }
}
```
```html
<input v-model="model.a" />
<input v-model="model.b" />
```
If you pass an uninitialized property (`model.b`) to `v-model`, it's obviously not reactive so bindings won't update or a deep watch on `this.model` won't fire off either.

Any chance that `v-model` could use `Vue.set` internally if it detects a binding with value `undefined` to automatically create reactive properties? (like Vue 1.0)

Or failing that, it should `warn` when an uninitialized property is passed to `v-model`

**Comment by yyx990803** [comment]
This is an intended change in 2.0 - `v-model` no longer creates non-existent properties for you, all root-level properties must be declared in `data` at instance creation.

**Comment by pyrostrex** [comment]
@yyx990803 is there any other way i can do this in vue2?

**Comment by waveiron** [comment]
It's ok that non-existent properties of `data` could not be tracked, but when `data.row = {}` and `data.row.username` could not be tracked?  Ridiculous.

**Comment by laurentvdl** [comment]
When building large forms, I now need to duplicate all property names in the template, the data initialiser function (for create) and make sure any objects that are edited have all possible properties present (null value for missing properties) before binding them in vue.

v-model still creates the properties without warning, but not as a reactive property, meaning some properties become reactive and some not, leading to strange behaviour. (for instance when using computed properties)

A custom v-model directive can be a solution, but it's a pity the default behaviour has changed.

**Comment by codeofsumit** [comment]
@yyx990803 we definitely need this as well to have bindings to non-existend sub-properties. Any workarounds? The models we're dealing with here are way to big to provide default stuff (also, this is send to the API and is just messy).

**Comment by posva** [comment]
@codeofsumit You should always try to fill the `data` property. If that's not possible use `Vue.set`
Next, time please, use the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions. Thanks 🙂

**Comment by codeofsumit** [comment]
@posva I'll follow up on this in the forums. Thank you!

**Comment by ryangpts** [comment]
This seems like a big deal. Is it just root-level properties or properties on root-level properties as well? My data has a root level property declared. When edit an existing object, I pull that record from the API. The API (as most I have seen) does not serialize null values. Instead it ignores them. In this case, is vue incapable of adding that property via v-model? I am seeing strange behavior like @laurentvdl points out. As I edit a form with 10 values. Sometimes properties get created and sometimes they don't.

**Comment by neitanod** [comment]
According to the documentation, `v-model="item.prop"` is just syntactic sugar for:
`v-bind:value="item.prop" v-on:input="item.prop = $event.target.value"`

So to achieve what we all (except Evan) want, we should stop using `v-model="item.prop"` and start writing: `v-bind:value="item.prop" v-on:input="$set(item,'prop',$event.target.value)"` which is sugar free and sad.

**Comment by joaomnb** [comment]
This behavior seems to have been reverted. In the latest version 2.5.16, reactivity also works with previously uninitialized properties. Can't find the pull request that brought this back, though.
