### ISSUE TITLE
Named mixins

### ISSUE THREAD

**Issue by Y-Less** [vuejs/vue#3735]
Currently, mixins look like this (as I'm sure you know):

```javascript
var MyMixin = { props: [ 'other' ] };
Vue.component('thing', { mixins: [ MyMixin] });
```

This seems to have two drawbacks:

1) The syntax is not consistent with other Vue part declarations - everything else is done via `Vue.factory` methods, these mixins are just plain arrays (though I know you can use other `Vue` objects as mixins as well).

2) This polutes namespaces, since your mixins must be explicitly stored somewhere.

I'd propose a slight modification to the `Vue.mixin` method to accept an optional first parameter of a name, as in many other similar functions:

```javascript
Vue.mixin({ data: [ 'foo' ] }); // Global mixin as before.
Vue.mixin('second-mixin', { data: [ 'bar' ] }); // New named mixin.
```

The named mixin would not be applied to every component but would instead have to be explicitly included as with the current bare object mixins - using a string name instead of an object to differentiate them (and to keep supporting the old method):

```javascript
new Vue({ mixins: [ MyMixin, 'second-mixin' ] });
```

**Comment by yyx990803** [comment]
1. I don't see how names are useful for mixins. Directives/Filters/Components all need names so that they can be referenced in templates. Mixins don't.

2. This would be a breaking change for no obvious gain.

**Comment by Y-Less** [comment]
1) The name is to avoid global namespace pollution, which makes it easier to import modules with mixins defined in them without worrying about what global variable they stored them in.  They simply register them by name internally instead.

2) There is nothing breaking about it - the existing method is still fully supported.  The last example I gave showed both the current object-based mixin system and the proposed name-based system used together.  Detecting an object vs. a string is trivially easy.  I also gave examples of `Vue.mixin()` with and without a name, again to show backwards-compatability.

**Comment by yyx990803** [comment]
Mixin is by nature different from other "assets". I think your proposal is

1. overloading `name` with a different purpose (template reference vs. in-JS-usage).
2. overloading `Vue.mixin` semantics (two very different usage)

With a module system, the global namespace issue is non-existent. Even if you don't use a module system you can just do `Vue.mixins = { a: { ... }, b: { ... }}` or nest them under some global namespace.
