### ISSUE TITLE
Upgrade to 1.0.27 breaks v-ref on a component with v-if

### ISSUE THREAD

**Issue by matfish2** [vuejs/vue#3754]
### Vue.js version
1.0.27

### Reproduction Link
https://jsfiddle.net/matfish2/7m1a799t/

### Steps to reproduce
a. Create a component
b. apply `v-ref` to it
c. apply `v-if` to it

### What is Expected?
`v-ref` should not break the code

### What is actually happening?
It throws an error:

`Uncaught TypeError: Cannot read property 'scope' of undefined`

**Comment by ahus1** [comment]
Seems to be related to #3217

**Comment by slevp** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/6696585/18823651/8d20124a-83ee-11e6-837b-1af291f63fba.png)

**Comment by oguzhanaslan** [comment]
+1

**Comment by 285858315** [comment]
+1
