### ISSUE TITLE
Simple data bind doesn't work in @next

### ISSUE THREAD

**Issue by rw3iss** [vuejs/vue#3755]
Dead simple example data bind doesn't work on standalone text.
If I bind with attributes it works.
For example:
```
var app = new Vue({
  el: '#app',
  data: {
  	message: 'hello'
  }
})
```
```
<div id="app">
  <span>{{message}}</span>
  <textarea :value="message"></textarea>
</div>
```

The span does not show the message or anything at all. 
The textarea does show the correct value of the message.
Am I missing something?

**Comment by rw3iss** [comment]
What's weird is the databinding seems to be recognized, but nothing show. ie if I add some list elements to the example, the list elements show up, but no text within them:

```
<div id="app">
	<span>{{ message }}</span>
	<textarea :value="message"></textarea>
	<ol>
	    <li v-for="todo in todos">
	      {{ todo.text }}
	    </li>
	 </ol>
</div>
```
```
var app = new Vue({
  el: '#app',
  data: {
  	message: 'hello',
	todos: [
		{ text: 'Learn JavaScript' },
		{ text: 'Learn Vue' },
		{ text: 'Build something awesome' }
	]
  }
})
```

Displays:
```
(textarea with message)
1.
2.
3.
```
But the list elements have no text... weird?

**Comment by ktsn** [comment]
Hi, thank you for reporting this issue.
Can you please provide a live reproduction by [jsfiddle](http://jsfiddle.net/)? (I cannot reproduce this problem from your provided code)
And also please tell us what version of vue.js you use.

**Comment by rw3iss** [comment]
Hi, thanks for the response. 
I'm using the @next version (latest 2.0). It seems to work with the CDN version of Vue on jsfiddle:
https://jsfiddle.net/s9u7g9tz/
However, if I try to use this same exact code locally, it doesn't work (as mentioned above). 

I am using Webpack to bundle the code. The only code webpack is building is this simple app.js file.

I though maybe it has to do with the whole template/render alias issue mentioned in the Vue installation:
http://rc.vuejs.org/guide/installation.html#NPM

...but, if I remove webpack all together, and just load the Vue CDN, and the plain app.js file (with just the code above), it still doesn't work! Very weird! I'll try to upload my code to my server for a different test.

**Comment by rw3iss** [comment]
Ah I think I know what's happening... I think my server-side view preparation, written in handlebars, is stripping the Vue syntax! Duh! I noticed the client code in the browser source does not have the {{ message }}, but if I extract the code to a single .html page, it stays and shows the content as expected. Sorry for the confusion! Thanks for your help.

**Comment by chisumo2016** [comment]
I am having the same issue .
var  todoApp = new Vue({
    el:'#app',
    data: {
        displayTitle: true,
        displayAddTasks: true,
        displayTaskStatistics: true,
        displayTasks: true,
        displayProgressBar: true
    }
});
