### ISSUE TITLE
vue2.0 调用$destroy方法不会destroy子组件

### ISSUE THREAD

**Issue by chenhongtu** [vuejs/vue#3756]
我调用$destroy后子组件不受影响功能还正常
[http://runjs.cn/code/o36fn2qx](url)

调用$destroy方法后，直接移除dom就行，还是要主动调用子组件的$destroy方法再移除dom？

**Comment by yyx990803** [comment]
手动 $destroy 在 2.0 完全不建议，尤其是当组件本身不是手动创建的时候。请用父组件状态来控制子组件。

**Comment by chenhongtu** [comment]
@yyx990803 我准备在已有的项目里，要做一些比较复杂的的功能，我想用vue来做必须要手动创建销毁，这种情况下我是不是用1.0比较好？

**Comment by kxxoling** [comment]
同样的情况，我用 Vue 1 实现的通知系统会自动调用 $destroy 自我销毁，升级到 2 之后 $destroy 就不支持了。有什么兼容性的解决方案吗？

**Comment by cike8899** [comment]
有个组件是需要keep-alive的，如果我需要在某种情况下把缓存的组件清除掉，该怎么办？我的是vue2，不用destroy，还有其他的办法干掉缓存的组件吗？

**Comment by yeomanyang** [comment]
@cike8899  同问，相同需求

**Comment by dukanglyb** [comment]
+1

**Comment by haizhilin2013** [comment]
可以使用keep-alive的include，但也是会有些问题

**Comment by MoonyPoet** [comment]
> 有个组件是需要keep-alive的，如果我需要在某种情况下把缓存的组件清除掉，该怎么办？我的是vue2，不用destroy，还有其他的办法干掉缓存的组件吗？

请问大佬，你解决了么~ 遇到相同需求。
