### ISSUE TITLE
parentNode of app container become null after Vue.js object initialization

### ISSUE THREAD

**Issue by limonte** [vuejs/vue#3757]
### Vue.js version
2.0.0-rc.7

### Reproduction Link
https://jsfiddle.net/xwq6cffw/

### What is Expected?
Both console.log statements should print `body`

### What is actually happening?
The first console.log (before Vue.js initialization) prints `body`, the second one (after Vue.js initialization) prints `null`.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Your `appContainer` is replaced by Vue, so your old reference doesn't work anymore.
https://jsfiddle.net/fjyv7t44/
