### ISSUE TITLE
vue2 transition does not take effect

### ISSUE THREAD

**Issue by TOP-Chao** [vuejs/vue#3758]
migration from 1.x
[vue1.x](https://jsfiddle.net/5qoyjrfr/)  to [vue2](https://jsfiddle.net/r400agsd/)
`vm.$appendTo` to `myElement.appendChild(vm.$el)`
`vm.$remove` to `vm.$el.remove()`

transition does not take effect，component root nodes arouse transition ？

**Comment by yyx990803** [comment]
Transitions are no longer triggered via imperative DOM manipulations in 2.0. You need to control them with Vue's rendering mechanism.

**Comment by TOP-Chao** [comment]
那我该如何完成这个动画呢? 尤大 能否给我举个栗子。
