### ISSUE TITLE
paramWatchers doesn't work in version 1.0.27

### ISSUE THREAD

**Issue by crnogaj** [vuejs/vue#3759]
### Vue.js version
1.0.27

### Reproduction Link
[jsfiddle](https://jsfiddle.net/oz04mztk/)

Here is same [example](https://jsfiddle.net/f9u05755/) with version 1.0.26 where it works

### What is Expected?
In this case alert should popup if number is changed by clicking on button.

**Comment by cannap** [comment]
it works for me https://i.gyazo.com/4e57ddd6cf8493203911195375ff60f2.png 
Version 54.0.2840.34 beta-m (64-bit)

**Comment by yyx990803** [comment]
FYI this is also fixed by https://github.com/vuejs/vue/pull/3776 (currently in review)

**Comment by yyx990803** [comment]
Fixed by #3776
