### ISSUE TITLE
Add "slim" release tag which is installed without envify.

### ISSUE THREAD

**Issue by Gerhut** [vuejs/vue#3760]
When using Vue.js in browser-with-node environment such as electron or nw.js, we can just use

    $ npm install --save vue

    <script>const Vue = require('vue`)</script>

to grab the library into the environment. However, when installing vue from npm, envify is also been installed as a dependence of the package. It is just for browserify bundling and useless in such situation.

Some browser-with-node environment packager such as [electron-packager](/electron-userland/electron-packager) just copy the whole node_modules directory into dist files, which makes a lot of useless packages such as envify increase the file size.

![image](https://cloud.githubusercontent.com/assets/2500247/18812526/3d64b4d4-830a-11e6-9372-d1e318d3da73.png)

So how about add a vue@slim release tag for just Vue.js installation, using in these situations.

**Comment by yyx990803** [comment]
I think that's a problem with `electron-packager`, not with Vue. File size doesn't matter in Electron anyway...
