### ISSUE TITLE
install by vue-cli failed

### ISSUE THREAD

**Issue by 5j2f** [vuejs/vue#3766]
npm-debug.log:
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error vue@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 3221225501
23 error Failed at the vue@1.0.0 dev script 'node build/dev-server.js'.

and  there are warning when execute npm intall :  Not compatible with your operating system or chitecture:fsevevts@1.0.14

what's problem  please!

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
