### ISSUE TITLE
Directive params casted into strings

### ISSUE THREAD

**Issue by webzhongwang** [vuejs/vue#3768]
### Vue.js version
1.0.27

### Description
Parameter data type is illegal to chang

### Reproduction Link

[jsfiddle](https://jsfiddle.net/jawc4bpo/)

### What is Expected?

Here is same [example](https://jsfiddle.net/gn4aezn2/)  with version 1.0.26 where it works

**Comment by defcc** [comment]
seems sortDirectives function breaks it ?

Object.keys(groupedMap)  returns an array whose elements are strings 

When it sorts, the string type value breaks it.

**Comment by juukie** [comment]
I'm having troubles with this too.

**Comment by johonunu** [comment]
I am also having this problem. Directives get object params as "[Object]" (string representation).
