### ISSUE TITLE
When using the v-else statement will cause a memory leak ? 

### ISSUE THREAD

**Issue by liming9515** [vuejs/vue#3769]
> Here‘s the simple code

`<table id="myTable">`
&nbsp;&nbsp;&nbsp;&nbsp;`<tr v-for="row in rows">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<td v-for="col in cols">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div v-if="col.format != null" class="grid-content">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`{{ col.format(row) }}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div v-else  class="grid-content">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`{{ row[col.name] }}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</td>`
&nbsp;&nbsp;&nbsp;&nbsp;`</tr>`
`</table>`

`<script type="text/javascript">`

&nbsp;&nbsp;&nbsp;&nbsp; `var vmm = new Vue({`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `el: "#myTable",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `data: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`rows: [],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`cols: []`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` }`
&nbsp;&nbsp;&nbsp;&nbsp; `});`

&nbsp;&nbsp;&nbsp;&nbsp;` vmm.cols = [{name: "Field1", format: function(row) {`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;` return "Field1-" + row["Field1"];`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;`}}, `
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;`{name: "Field2"}, `
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;`{name: "Field3"}];`

&nbsp;&nbsp;&nbsp;&nbsp; `window.setInterval(function() {`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `if(vmm.rows.length > 500)`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `{`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `vmm.rows.splice(0, 100);`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `}`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `vmm.rows.push({`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `Field1: Math.random(),`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `Field2: Math.random(),`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; `Field3: Math.random()`
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;  `});`
&nbsp;&nbsp;&nbsp;&nbsp; `});`
`</script>`

> Monitor by Chrome, the number of nodes are growing all the time. But if i replace **v-else** with **v-if="col.format == null"**, it will be hovering near the peak.

> I'm so sorry for my poor English, if you can't understand what i means, read the following Chinese.

以上代码通过Chrome监测，会发现dom节点的数量一直在增长，直到浏览器崩溃，如果将 **v-else** 替换为 **v-if="col.format == null"**，则节点数量会在到达峰值之后回收一部分，然后重新达到峰值，再次回收，如此往复，浏览器不崩溃。

**Comment by posva** [comment]
Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by liming9515** [comment]
@posva 
Vue.js  v1.0.13
JSFiddle https://jsfiddle.net/g4z684q9/

**Comment by yyx990803** [comment]
Your version is way too old. Please upgrade to latest version and reopen if issue persists.

**Comment by liming9515** [comment]
@yyx990803 Thank you for advise!  I run the test in the v1.0.26, the problem does not exist. By the way, could you tell me how to do performance optimization at initialization time ? Is there some related documents?

**Comment by posva** [comment]
@liming9515 Look at the guide http://vuejs.org/guide/  search `once`

**Comment by liming9515** [comment]
@posva My problem very similar to this
https://github.com/vuejs/vue/issues/2000
I use vue to render a grid that have more than 10000 cells, it cost almost 8s. Is there a simple way to make it fast?

**Comment by liming9515** [comment]
@posva Thank you for much! I think i know what you mean now.
https://github.com/vuejs/vue/issues/2535

**Comment by posva** [comment]
You'll be better off searching or asking on the forums http://forum.vuejs.org/ 😉 
Google can also help you with that

**Comment by liming9515** [comment]
@posva Thank you very much! I will search more information for that. 
This proposal has been accepted yet? https://github.com/vuejs/vue/issues/2535
