### ISSUE TITLE
Vue.js on server with jsdom

### ISSUE THREAD

**Issue by fullfs** [vuejs/vue#377]
Trying to make both-side templating with Vue.js and jsdom
It seem to work mostly, but still got 2 problems:
1. rendered Vue component gets "undefined" content instead of proper string from 'template' param.
2. it seems jsdom won't fully emulate modern object functions, so changing data objects after Vue initialization won't result DOM updates.
Any help?

**Comment by remoe** [comment]
Does anyone checked this with vue 0.12.8? I can't get it to work.

**Comment by fullfs** [comment]
@remoe I've checked, It does not work, yeah. Though maybe it can be fixed easily.

**Comment by yyx990803** [comment]
@remoe @fullfs what does the error stack trace look like?

**Comment by remoe** [comment]
Ok, I tested with windows. So for newer version of vue one need to change this:

```javascript
var compilerPath = require.resolve('vue').replace('src\\vue.js', 'dist\\vue.min.js')
```

But now it doesn't run after mounting. I need to investigate ...

**Comment by remoe** [comment]
@yyx990803 after changing the code to this:

```javascript
          var vm = new Vue({
              el: '#temp',
              data: {
                  hello: 'Hello World!'
              }
          })
```

I had the following strack trace:

```javascript
about:blank:undefined:undefined<script>:1694
          text = text.replace(/\n/g, '')
                      ^
TypeError: text.replace is not a function
    at Object.exports.parse (about:blank:undefined:undefined<script>:1694:16)
    at collectAttrDirective (about:blank:undefined:undefined<script>:2731:28)
    at compileDirectives (about:blank:undefined:undefined<script>:2657:14)
    at Object.exports.compileAndLinkRoot (about:blank:undefined:undefined<script>:2304:25)
    at Vue.exports._compile (about:blank:undefined:undefined<script>:8658:17)
    at Vue.exports.$mount (about:blank:undefined:undefined<script>:9799:9)
    at Vue.exports._init (about:blank:undefined:undefined<script>:7775:11)
    at new Vue (about:blank:undefined:undefined<script>:80:9)
```

**Comment by yyx990803** [comment]
Turns out this is a subtle problem because when checking `_.isPlainObject()` on a jsdom element it returns true...

I've refactored a little bit to not rely on this check in latest `dev` and the snippet above is working again.

**Comment by remoe** [comment]
@yyx990803 confirmed! Thanks!

**Comment by remoe** [comment]
I try to use the vue-router/vue with jsdom. My app works without jsdom, but with it has the following warning on vue:

```javascript
[Vue warn]: Failed to resolve directive: link
```

This throws in:

```javascript
router.start(App, '#js-container' );
```

Does anyone has a working JSFiddle sample of Vue **with** vue-router? I can't get it to work :/
