### ISSUE TITLE
No initial selected state of a html select while there is an option with a 'selected' attribute (since the 1.0.27 update)

### ISSUE THREAD

**Issue by nickgr6** [vuejs/vue#3770]
### Vue.js version
1.0.27

### Reproduction Link
https://jsfiddle.net/eLf31dac/1/

### Steps to reproduce
Simply open the fiddle. You see an empty value select.
When looking in the dev tools, the source is:
`<option value="/app/en/products/overview/canada" selected>
      Canada
    </option>`
which is correct?

### What is Expected?
Default selected state should be 'Canada' due to the 'active=true' property.
This is the actual behaviour with VueJS 1.0.26: https://jsfiddle.net/c8999or7/1/

### What is actually happening?
There's no initial 'selected' state of the select option

**Comment by LinusBorg** [comment]
Indeed seems like a regression.

Workaround: it works if you define the value in the v-model field upfront:

https://jsfiddle.net/Linusborg/eLf31dac/4/

**Comment by yyx990803** [comment]
Fixed by #3776
