### ISSUE TITLE
can not use v-show in slot tag

### ISSUE THREAD

**Issue by soluty** [vuejs/vue#3772]
### Vue.js version
2.0.0-rc.6

```
Vue.component('test', {
  template: '<div><slot v-show="isshow"></slot></div>',
  data: function(){
     return {
       isshow: false
     }
  }
})
```

### What is Expected?
when i use this component like this it will render nothing
`<test>i am test</test>`
### What is actually happening?
text rendered

but if i change v-show to v-if  it works fine

**Comment by posva** [comment]
I think this is because that's a text element and the style `display: none` cannot be applied to it. So basically it's intended but I'm still unsure.
You can just use `v-if`

**Comment by LinusBorg** [comment]
Hello @soluty,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by LinusBorg** [comment]
@posva I agree. You can't apply `display: none` to text, it needs a surrounding element.

This should work with v-show:
```html
<test>
  <span>i am test</span>
</test>
```

**Comment by yyx990803** [comment]
This is intended, `<slot>` is an abstract element, there's no target to apply `v-show` to.

(FYI this never worked even in 1.0)

**Comment by j4yk21** [comment]
you can't use v-show on <slot>

but you can put your slot inside a div end then use v-show inside your div like that `<div v-show="showSlot">
    <slot />
</div>`
