### ISSUE TITLE
When the transition "fade out" ended, it removes all "out" classes in the element

### ISSUE THREAD

**Issue by YamiOdymel** [vuejs/vue#3773]
### Vue.js version
2.0.0-rc.5

### Steps to reproduce
```html
<transition enter-active-class="fade out right" ...>
        <section class="out and cubic animated">
            ...
```
### What is Expected?

When the transition ends, it should've removed `fade out right` and **left** `out and cubic animated`.

### What is actually happening?

When the transition ends, it left `and cubic animated` **only** (everything with `out` was gone).

&nbsp;

### Why `fade out` naming convention?

Because I am using the CSS framework: [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI),

the naming convention with Semantic-UI is to **split each word**,

for example: `ui input`, `ui large fluid input` so are the animations, any possible ways to fix this please?

**Comment by LinusBorg** [comment]
Why do you add the "out" class via `enter-active-class` if it's already present on the element?

**Comment by YamiOdymel** [comment]
Sorry that's just an simplified example, it's actually

```
<transition enter-active-class="fade in right" leave-active-class="fade out right" mode="out-in">
        <section class="out and cubic animated" v-show="screen === 'register'">
```

**Comment by LinusBorg** [comment]
I still have the same question, basically. 

What influence does `out` have on the leave-animation/transition if it is present before, during, and after this animation?

To put it in other terms: `leave-active-class="fade right"`should work exactly the same, right?

**Comment by YamiOdymel** [comment]
The `out` and `in` are just a decoration class to make it _semantic-ize_, 

and Semantic UI use the selector `[class*=""]` (for example: `[class*="vertical flip in"]`) to prevent the naming conflict (so `vertical xx flip xxx in` won't work),

and this issue will also happen on a `ui right labeled icon button` if I want to put a `fade right` (or `fade in right`) transition on it.

**Comment by LinusBorg** [comment]
*(Disclaimer: Bear with me, my CSS-wizardry is weak, and I have never worked with Semanti-UI so correct me if I'm wrong here)*

So Semantic-UI relies on the order of classnames? Sounds like a recipe for desaster in dynamic UIs.

To work, the section element have to would look like this during leave transition:
```html
class="out and cubic animated fade out right"
```
...which is not valid HTML. Furthermore, Vue uses `classList.add() / remove()`, so both ocurrences of `out` would be removed.

**Comment by YamiOdymel** [comment]
I think that I will change the naming convention of the animation from `fade in right` to `fadeInRight` to solve the problem temporary,

sorry for wasting your time, and thanks for the explanation :D

**Comment by LinusBorg** [comment]
No need to be sorry, Always glad to help :)
