### ISSUE TITLE
Error parsing template when using `<` carret as text

### ISSUE THREAD

**Issue by dustindowell22** [vuejs/vue#3778]
### Vue.js version
v2.0.0-rc.7

### Reproduction Link
http://codepen.io/dustindowell/pen/zKwEaV

### Steps to reproduce
```html
<div id='app'>this is < than this</div>
```

### What is Expected?
No error

### What is actually happening?
Error

```error
Uncaught Error: Error parsing template:

< than this</div>
```

**Comment by blake-newman** [comment]
You should be using `&lt;` as that is valid DOM structure. 

If you find that this does not work please feel free to reopen.
