### ISSUE TITLE
[1.0.27] Weird custom directive behaviour

### ISSUE THREAD

**Issue by schleumer** [vuejs/vue#3779]
### Vue.js version
1.0.27

### Reproduction Link
https://jsfiddle.net/oocnvztb/2/

### Steps to reproduce
Create a custom directive, every param, even binded params, became strings, empty arrays became boolean(something somewhere is calling `toString`).

### What is Expected?
Binded values

### What is actually happening?
String representation of values

**Comment by yyx990803** [comment]
Duplicate of #3768
