### ISSUE TITLE
Vue2.0 bootstrap table style display incorrectly when use vm.$mount or  'vue component'

### ISSUE THREAD

**Issue by wengang** [vuejs/vue#3782]
### Vue.js version
2.x

### Reproduction Link
https://github.com/wengang/vue-bootstrap-table
https://github.com/wengang/vue-bootstrap-table/tree/issue

in master branch table style display correctly,
but in issue branch table stlye display incorrectly

**Comment by posva** [comment]
You just forgot the `tbody` tag my friend 😉
