### ISSUE TITLE
明明有数据， v-for却渲染不出来

### ISSUE THREAD

**Issue by Wang-Kai** [vuejs/vue#3783]
tickets 是一个数组，里面有两个对象。对象的长度可以显示出来，转换为JSON的文本，也能显示出来。
但  v-for 循环渲染的时候就是显示不出来！！！！

觉得十分奇怪！！！

<img width="506" alt="2016-09-27 12 32 07" src="https://cloud.githubusercontent.com/assets/13144386/18860313/b3ad53e4-84ae-11e6-9839-30dd3272ad38.png">
<img width="352" alt="2016-09-27 12 31 59" src="https://cloud.githubusercontent.com/assets/13144386/18860315/b5f261bc-84ae-11e6-9f13-0749b49fe662.png">

**Comment by yodfz** [comment]
尝试debug 数组的修改是否未被vue追踪

**Comment by yyx990803** [comment]
请 给 重 现
