### ISSUE TITLE
recursive single-file component

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue#3786]
hello!

after reading this http://rc.vuejs.org/guide/components.html#Recursive-Component i can understand how to create recursive component from js code. 

How to create single file recursive component? i am trying this

```html
<template>
    <node-as-tree" >
        <node-as-tree v-if="node.parent" :model="model.parent"></node-as-tree>
        {{model.name}}
    </node-as-tree>
</template>

<script>
    module.exports = {
//        name:"node-as-tree", this not works
        props: ["id", "model"],
    }
</script>
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

**Comment by posva** [comment]
This is the **third** time already you ask a question in a issue. Please, don't do it again, it makes it harder for us to review real issues with Vue

**Comment by alexey2baranov** [comment]
OK. this is the last time. I registred on forum by github account but can not post any topic by "email-not-confirmed-email-sent" error. What should I do?

**Comment by posva** [comment]
Add a public email to your github profile the time to register so the forum can send a confirmation email

**Comment by alexey2baranov** [comment]
I have a public e-mail alexey2baranov@gmail.com

**Comment by posva** [comment]
It must be shown on your profile for it to work

**Comment by alexey2baranov** [comment]
It got me crazy! I spent last 1 hour to register on forum

> ОШИБКА
> MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

sorry if i distract you but i realy don't know where to write this. your forum don't like me) Move me to another forum's issue tracker or confirm my account manualy. Now I register second public email baranova@id.te.ru on my github account but cant confirm it by this error

**Comment by posva** [comment]
Try using https://gitter.im/vuejs/vue instead in that case
