### ISSUE TITLE
Migration process doesn't talk about package.json

### ISSUE THREAD

**Issue by tobeorla** [vuejs/vue#3788]
http://rc.vuejs.org/guide/migration.html#FAQ
## Where should I start in a migration?

That section should also warn user to upgrade Vue's npm packages and it's plugins too. (And also check if all it's plugins are Vue 2.0 compatible before starting the upgrade)

**Comment by blake-newman** [comment]
That is totally up to you, as it is dependent on the project, and what features you may have used. In terms of the npm packages, it is a nice idea @chrisvfritz what is your opinion on this.

**Comment by chrisvfritz** [comment]
Not everyone will be using Vue through NPM (in fact, possibly most will not be), but I think it would be a good idea to include a generic reminder that Vue plugins will likely also need to be updated. 👍

**Comment by yyx990803** [comment]
@chrisvfritz any updates on this? Either way, this should be moved to the vuejs.org repo.

**Comment by chrisvfritz** [comment]
It's done - sorry I forgot to come back and close.
