### ISSUE TITLE
Vuejs 2 does not model bind file input

### ISSUE THREAD

**Issue by leocflam** [vuejs/vue#3789]
After migration I found this problem.

The data value bind to file input always keep empty string.
After selecting a file, the file path should be in the data but it doesn't. With 2.0.0-rc7 Only Chrome has the issue while ME and Firefox are Okay. With 1.XX all browsers are Okay.

version : 2.0.0-rc.7
http://jsfiddle.net/5sH6A/704/
firefox -->> OK
ME --->> OK
chrome -->> not OK
(chrome version: 53.0.2785.116 m)

1.0.27 was OKAY:
http://jsfiddle.net/mvo6sg72/1/

**Comment by posva** [comment]
Thanks for filing the issue 😄 . Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by leocflam** [comment]
Hi Posva, I reproduced it. It seems the issue appear with 2.0.0-rc-7 on Chrome only
my chrome version is 53.0.2785.116m and OX is Windows10

**Comment by posva** [comment]
Thanks! Checking that

**Comment by posva** [comment]
we're missing the `change` event for the input[type=file]. Let me add a PR for that

**Comment by posva** [comment]
@leocflam What's happening here is that input with `type=file`'s value cannot be set with js (for browser security reasons). This means that input is read only, therefore the proper way to handle is using a `@change="photo = event.target.value"` handler
Here's the right way to handle it: http://jsfiddle.net/posva/5sH6A/706/

It's worth mentioning in the docs. I'll do that 😄

**Comment by posva** [comment]
@leocflam This example is better: http://jsfiddle.net/posva/32Lvxmmo/
It uses the FileList which is better than the value

**Comment by posva** [comment]
FYI I created a PR to add a warning: #3791

**Comment by leocflam** [comment]
Great! very detailed. Hey, Thanks =)
