### ISSUE TITLE
Not importing correctly with Rollup

### ISSUE THREAD

**Issue by danreeves** [vuejs/vue#3790]
### Vue.js version
2.0.0-rc.7

### Reproduction Link
http://vue-rollup-undefined-this.surge.sh

### Steps to reproduce
https://github.com/danreeves/vue-rollup-undefined-this-bug-report

### What is Expected?
Vue should init

### What is actually happening?
From Rollups mouth: "The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten". A quick fix to test this out is to replace any calls to `this` with `Vue.prototype`, and it starts working.

**Comment by posva** [comment]
Let me check it. I got vue + rollup working on multiple projects

**Comment by posva** [comment]
Vue is a constructor. You have to call it with `new`

**Comment by danreeves** [comment]
I'm such an idiot! Thanks

**Comment by standino** [comment]
方法createComponentInstanceForVnode 的两行注释导致rollup报错，请修改注释位置。能不能发这个方法的注释调整到方法头上？谢谢。

node_modules\vue\dist\vue.runtime.esm.js
 function createComponentInstanceForVnode (
    vnode, // we know it's MountedComponentVNode but flow doesn't
    parent // activeInstance in lifecycle state
  ) {
