### ISSUE TITLE
Vue's Devtool still show up after NODE_ENV set to production in 2.x

### ISSUE THREAD

**Issue by kevinongko** [vuejs/vue#3794]
### Vue.js version
2.0.0-rc.8

The devtool is hidden correctly in 1.0.28 but still appear when using 2.0.0-rc.8

### What is Expected?
Vue's devtool doesn't show up anymore in chrome's dev console

### What is actually happening?
Vue's devtool still show up in chrome's dev console

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

That's not enough, the variable need to be replaced on the code. Check the templates for help about how to setup that: https://github.com/vuejs-templates/webpack
