### ISSUE TITLE
How to add pdfjs

### ISSUE THREAD

**Issue by guojianlan** [vuejs/vue#3796]
I use vue-cli to build the program, and now I want to add pdfjs to the program, but the introduction of the relevant documents will be reported to the wrong, there is no relevant examples

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by guojianlan** [comment]
Thanks, I remember, I deleted the problem.
