### ISSUE TITLE
v-repeat not working with component

### ISSUE THREAD

**Issue by shadoWalker89** [vuejs/vue#3797]
### Vue.js version
1.0.26

I wanted to use a component with a v-repeat but i kept getting this error 

[Vue warn]: Failed to resolve directive: repeat

At first i thought that may be i did something wrong so i copied the code in this example from the vue js site.

http://012.vuejs.org/guide/components.html#List_and_Components

And it was all the same, it didn't work.

By the way

The component html is rendered, but the `data` is not filled.

Following the example on the site, the `name` and `email` attributes aren't filled in the component

**Comment by LinusBorg** [comment]
you re using 0.12 sntax with the 1.0 version. it's v-for now.

Please read the 1.0 docs when using the 1.0 version.

**Comment by shadoWalker89** [comment]
Thanks, bro

I really don't know how i ended up on the 0.12 docs.
May be you can add a notification on the legacy documentation to alert people that this is no the current docs.
