### ISSUE TITLE
v2.0.0-rc.8 IE/Edge select fix regression

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#3798]
Related to: 
https://github.com/vuejs/vue/issues/3689
https://github.com/vuejs/vue/pull/3719

Unfortunately reverting `nextTick`  to use microtask semantics causes the IE/Edge select fix to only partially work. IE/Edge remembers the selected value after page refresh (but is OK after a hard refresh)

I was wondering why using just `nextTick` in my PR didn't work when I did for you, then I saw that `nextTick` had changed implementation so must have been taking that little bit longer before it executed.

Potential solutions:
Might be some flicker
````javascript
if (isIE || isEdge) {     
  setTimeout(function () {
    setSelected(el, binding, vnode.context)
  }, 0)        
}
```

No flicker
````javascript
if (isIE || isEdge) {
  nextTick(function () {
    setSelected(el, binding, vnode.context)
  })        
  setTimeout(function () {
    setSelected(el, binding, vnode.context)
  }, 0)        
}
```

**Comment by yyx990803** [comment]
ugh, stupid IE... I guess we'll go with the no flicker version of it (they can share the same callback) - PR welcome.
