### ISSUE TITLE
debug wnen using vue-router

### ISSUE THREAD

**Issue by yangshipo** [vuejs/vue#3799]
### Vue.js version
2.0.*

### What is actually happening?
when using vue2.0 with vue-router0.7 : Cannot read property 'component' of undefined.
when usind vue1.0.26 with vue-router0.7 : good.

**Comment by fnlctrl** [comment]
Please make sure follow [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), and provide a reproduction on jsfiddle/codepen etc. And when the reproduction is created, please open a issue at vue-router's repo, thanks!

**Comment by LinusBorg** [comment]
vue-router 0.7 does not work with Vue 2.0. There's vue-router `v2.0.0-rc.5` for this

`npm install vue-router@next`
