### ISSUE TITLE
about set compent's style

### ISSUE THREAD

**Issue by gxlmyacc** [vuejs/vue#3800]
Hi, I am a new user of Vue. and I try to use webpack to pack the.Vue file. I now have a problem like this. For instance, I have a test.vue:
```
<template>
   <h1>title1</ht>
   <one-component></one-component>
</template>

<script>
   import one from "./compontents/one-component"
  export defalut {
    components: {
      one
    }
  }
</script>

<style>
   ...
</style>
```
in _**style**_ tag, I don't know how to set the style to the one-component, unless I know the actual model of one-component. Is there any way to set the style to it in case I don't know the actual model of one-component?

I have an idea,  When Vue replace one-component to template, the root element for the template to add a.One-component class, so that I can write style:
```
<style>
   .one-component {
   }
  or 
   .oneComponent {
   }
</style>
```

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Add css classes to it
