### ISSUE TITLE
Add late binding feature?

### ISSUE THREAD

**Issue by rabrenio** [vuejs/vue#3806]
It would be great if vue have this feature. My team and I once encountered a difficulty, we had this dynamic form and we want to bind this with a model. Unfortunately we did not find any solutions and we ended up using jquery to pull all the data from the input fields.

**Comment by yyx990803** [comment]
Please be more specific on what you mean by late binding, and provide desired usage code sample. This is too vague to be a feature request.

**Comment by posva** [comment]
Pulling data from the input fields can be achieved with vanilla JS. Once you have access to the form element you can just access any form variable using the name attribute for each field. You can even add a `ref` to the element to have a fast reference on your Vue instance (`v-el` for Vue 1)

**Comment by rabrenio** [comment]
@posva I don't want to pull the data from the field, what I really want is pull the data from the model. What I wrote above is wrong sorry. 

@yyx990803 thank you for the response but I already found a way to get data from dynamic model. It can be accomplised via vm.$compile.
