### ISSUE TITLE
solt位置不正确

### ISSUE THREAD

**Issue by jin9999** [vuejs/vue#3809]
定义了accordion 和panel组件，
```html
<accordion  type="info">
	  <panel is-open type="primary">
	    <strong slot="header"><u>Panel #1</u></strong>
	    test1
	  </panel>
	  <panel header="Panel #2">
	    test2
	  </panel>
	  <panel header="Panel #3">
            test1
	  </panel>
	  <panel header="Panel #4">
	    test4
	  </panel>
</accordion>
```
这里的代码，点击第一个panel的title,会导致solt="header"的内容,跑到panel的solt默认位置去。
![image](https://cloud.githubusercontent.com/assets/22189628/18946605/33a9ae4e-8662-11e6-916f-da2f593dbbfa.png)

[Panel.txt](https://github.com/vuejs/vue/files/500112/Panel.txt)
[Accordion.txt](https://github.com/vuejs/vue/files/500113/Accordion.txt)

**Comment by fnlctrl** [comment]
请使用jsfiddle/codepen给重现，记得将与问题无关的代码排除，不要放在例子里。

**Comment by posva** [comment]
The slot attribute must be used on the parent element (on the panel). Otherwise, move the `strong` element outside of the panel

**Comment by jin9999** [comment]
初始化的时候是正确，点击之后Panel #1位置就变了。
![image](https://cloud.githubusercontent.com/assets/22189628/18947989/e17db858-8667-11e6-9310-21a95d2d0be7.png)
![image](https://cloud.githubusercontent.com/assets/22189628/18948009/f3dbda0c-8667-11e6-909f-907ef652512b.png)

**Comment by jin9999** [comment]
@posva @fnlctrl 
![image](https://cloud.githubusercontent.com/assets/22189628/18977658/c728943c-86ee-11e6-978a-e5ee9f41eaae.png)
![image](https://cloud.githubusercontent.com/assets/22189628/18977662/ca7f8df2-86ee-11e6-9050-a86c15f3bfb4.png)

**Comment by yyx990803** [comment]
Screenshot is not a reproduction.
