### ISSUE TITLE
Computed properties caching issue

### ISSUE THREAD

**Issue by miedzinski** [vuejs/vue#3811]
### Vue.js version
2.0.0-rc.8

### Reproduction Link
https://jsfiddle.net/r647qdz1/

### Steps to reproduce
Open above JSFiddle.

### What is Expected?
HTML output is "1".

### What is actually happening?
Property is executed only once (should be twice), gets cached and doesn't update.

___
I'm not really sure what is causing the problem here. Using try or arrow functions separately works, but with them combined into `tryDef` function, Vue's reactivity doesn't work as expected.

**Comment by LinusBorg** [comment]
you are using Vue 1.0 in this example:

https://rawgit.com/yyx990803/vue/master/dist/vue.js

As Vue 2.0 is still in Rc and not officially released, the master branch is still 1.0.x

If you change `mounted()` to `ready()` (name of that hook in 1.0.x), your example works as expected: https://jsfiddle.net/Linusborg/r647qdz1/1/

**Comment by miedzinski** [comment]
I am using 2.0.0-rc.8 locally. You are right, computed property works with `tryDef` function; there was another problem with my code and I've overlooked it.

https://mdzn.pl/_/vue.html

As you can see, it works. My bad, sorry.
