### ISSUE TITLE
Vue@2.x use single file component render slow

### ISSUE THREAD

**Issue by bluemsn** [vuejs/vue#3812]
Vue@2.x
I use single file component to render page, but very slow? i don't know why?

 simple example, and does not use complex nested components 

https://github.com/bluemsn/vue-render-performance-comparisons/tree/sfc-test

At first, I wanted to test the rendering performance of nested components in complex scenes, but now it's very slow to render in a simple nested component

**Comment by bluemsn** [comment]
https://github.com/chrisvfritz/vue-render-performance-comparisons/issues/2

**Comment by fnlctrl** [comment]
You're not making the components functional as the original vue example did, and you're duplicating `<div id="root">` inside each `List`. 
Please make sure to check if your implementation matches the original implementation, before posting questions here, thanks!
