### ISSUE TITLE
A suggestion/question for the method protoAugment .

### ISSUE THREAD

**Issue by tangbc** [vuejs/vue#3813]
I have a suggestion when I came to `src/core/observer/index.js`, in the line [83](https://github.com/vuejs/vue/blob/dev/src/core/observer/index.js#L83). Why not use `Object.setPrototypeOf` if it is avaliable in some case? I think that would be working well:
```javascript
let setProto = Object.setPrototypeOf;
function protoAugment (target, src) {
  if (setProto) {
    setProto(target, src);
  } else {
    target.__proto__ = src
  }
}
```

Is there any problem using this featrue ?

**Comment by yyx990803** [comment]
There's no practical difference, `__proto__` is supported in more browsers, and is also standardized so it works in the future.

We **can** use `setPrototypeOf` but there's just no reason to write extra code that achieves nothing.
