### ISSUE TITLE
Disallow object spread operator without specified objectAssign or polyfill helper

### ISSUE THREAD

**Issue by bowen31337** [vuejs/vue#3814]
### Vue.js version
2.0.0-rc.8

### Steps to reproduce
when updates  ./src/shared/util.js in line 143
```js
export function extend (to: Object, _from: ?Object): Object {
  return { ...to,..._from }
}
```
then 
```
npm run dev

```
### What is Expected?
It should have passed the test.
### What is actually happening?
Throw error 'with 'buble' plugin: Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper.'
it is a similar issue to this repo [Object spread operator requires specified objectAssign option with \'Object.assign\' or polyfill helper.](https://gitlab.com/Rich-Harris/buble/issues/113)

**Comment by posva** [comment]
That is something you have to do with babel or buble in your build env.
I don't understand why you're modifying vue code as a _repro_

**Comment by bowen31337** [comment]
@posva It is about Dev environment, Babel officially supports Object spread operator in stage 2, see [https://babeljs.io/docs/plugins/transform-object-rest-spread/](https://babeljs.io/docs/plugins/transform-object-rest-spread/),  [https://babeljs.io/docs/plugins/preset-stage-2/](https://babeljs.io/docs/plugins/preset-stage-2/)

However, It is quite sad that Rollup doesn't support it, **I am also sad** that Vue chose Rollup. There is quote from [https://github.com/rollup/rollup/issues/354](https://github.com/rollup/rollup/issues/354):

> With Babel 6.x and preset 2015, things like the spread attribute works right out of the box when I use them with Browserify and Webpack. So all plugins included there.However. As I stated all the time, this is not supported by Rollup. At least tons of issues to solve to get it working, and I still haven't got it working.I gave up rollup, and went with a webpack solution. It took me 2 minutes to set up with webpack, and spread attribute works.

**Comment by Alendorff** [comment]
Have the same issue while trying to test component with jest, but use object spread in template. In dev/prod works fine, but not with jest.

**Comment by posva** [comment]
that's a completely different problem from this 3y old issue though 😄 
You probably need to setup babel-jest or similar, there are plenty of resources out there.

Locking as this is an old resolved issue
