### ISSUE TITLE
Inline :style with value 0 ignored

### ISSUE THREAD

**Issue by jeroennoten** [vuejs/vue#3816]
### Vue.js version
2.0.0-rc.8

### Reproduction Link
https://jsfiddle.net/Lcp6zekn/

### Steps to reproduce
Add a style attribute with value 0, e.g. `<div :style="{opacity: 0}"></div>` or `<div :style="{padding: 0}"></div>`.

### What is Expected?
The value is respected.

### What is actually happening?
The value is ignored.

**Comment by apulley** [comment]
Works in 1.x, which is interesting. https://jsfiddle.net/2mnyqnnt/

In 2.0, I've found that I've had to turn Falsy values into strings or Vue will not apply the attribute. (is this expected in 2.0?) In this case, it's not applying the style attribute for `opacity:0`.

Similar issues here with an aria attribute that has a boolean value e.g. `aria-invalid="boolean"`
