### ISSUE TITLE
[bug] Vue2.0.0-rc.8 `v-if` AND 'slot'

### ISSUE THREAD

**Issue by myronliu347** [vuejs/vue#3819]
https://jsfiddle.net/myronliu347/mj7xmfjn/3/embedded/

when `open` change more ,   name is test `slot` to 'default'

**Comment by LinusBorg** [comment]
Hello @myronliu347 

Thanks for filing this issue, it seems to be a bug indeed.

**Comment by WalterZou** [comment]
it seems to be a bug in Android Webview, still
