### ISSUE TITLE
Inconsistent call behaviour between filters and watchers.

### ISSUE THREAD

**Issue by Y-Less** [vuejs/vue#3820]
### Vue.js version
1.0.28

### Reproduction Link
```html
<html>
	<head>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.min.js"></script>
		<style type="text/css">

class-1: { background-color: #FFF; }
class-2: { background-color: #000; }

		</style>
	</head>
	<body>
		<div id="eg">
			<div :class="myBool | name-filter">
				HelloWorld
			</div>
		</div>
		<script type="text/javascript">

Vue.filter('name-filter', function (val) {
	// Filter expression to be called every time the value changes.
	console.log('filter called');
	return val ? 'class-1' : 'class-2';
});

var myVue = new Vue({
	el: '#eg',
	data: {
		myBool: true,
	},
	watch: {
		myBool: function () {
			// Watch expression to be called every time the value changes.
			console.log('watch called');
		},
	}
});

setInterval(function () {
	// Toggle the value.
	myVue.myBool = false;
	myVue.myBool = true;
}, 1000);

		</script>
	</body>
</html>
```

### Steps to reproduce
Add a watch and a filter to a variable and quickly toggle it (change it to something else and change it back again).

### What is Expected?
Either the watch is called, or the filter isn't.  Basically, either both should be called because there was an update, or neither because the value didn't change between the start and end of the tick.

### What is actually happening?
The watch isn't called.  This could be considered fine since the value hasn't changed over one tick; however, any filters that rely on that value ARE called with the final value even if that is not different to the value from the last tick.  This seems inconsistent, since filters aren't that much different from other functions that rely on a value.  I do like the filter behaviour, since it is only called once in this case with the final value each time the interval is called, so you can use this trick to re-apply something.

**Comment by yyx990803** [comment]
A watcher, when any of its dependencies change, need to **re-evaluate** to find out whether the value has changed. And the filter is part of a watcher expression to be re-evaluated. Makes sense?

**Comment by Y-Less** [comment]
Ahh, yes that does make sense.
