### ISSUE TITLE
SSR document not defined with Vue2.0

### ISSUE THREAD

**Issue by cannap** [vuejs/vue#3822]
hi, since i updated to Vue 2.0 i get document not defined on server 🎯 
and in Hackernews 2.0 example also 
```
ReferenceError: document is not defined
    at C:\Users\marko\Desktop\Renka\vue-hackernews-2.0-master\node_modules\vue\dist\vue.js:5549:24
    at C:\Users\marko\Desktop\Renka\vue-hackernews-2.0-master\node_modules\vue\dist\vue.js:7:83
```
not sure its a Vue 2.0 error i dont know how to debug this :/

thanks for Vue its an awesome framework 👊

**Comment by gkedzierski** [comment]
I can confirm, happens even on freshly cloned vue-hackernews-2.0 project. (never happened for RC releases)

Some environment details:

```
❯ node -v
v6.7.0

❯ npm -v
3.10.3

❯ npm ls | grep vue
vue-hackernews-2.0@ ~/vue-hackernews-2.0
├── vue@2.0.0
├─┬ vue-loader@9.5.1
│ ├── vue-hot-reload-api@2.0.6
│ ├── vue-style-loader@1.0.0
│ ├── vue-template-compiler@2.0.0
│ └── vue-template-es2015-compiler@1.0.0
├── vue-router@2.0.0
├─┬ vue-server-renderer@2.0.0
├── vuex@2.0.0
├── vuex-router-sync@3.0.0
```

**Comment by cannap** [comment]
i checked the dist/vue.js source code its the line 
5549 
i changed from
`var decoder = document.createElement('div')`
to and now it works not sure this will break other stuff but why should it xD
`var decoder = inBrowser ? document.createElement('div') : false`

i cant make a pr atm ;/

**Comment by yyx990803** [comment]
Noticed - need to reverting npm main export to commonjs build. fixing soon.

**Comment by yyx990803** [comment]
Fixed /w 2.0.1, please do a fresh npm install.

**Comment by xpepermint** [comment]
Is this fixed, because I can still see this error message.

**Comment by facesea** [comment]
@yyx990803 i import 3rd libary `alertifyjs`, i get error is `ReferenceError: document is not defined` when SSR, i don't want to change the code of `alertifyjs` ,what can i do?

**Comment by DualWield** [comment]
@facesea @yyx990803 +1 , when i import https://github.com/ElemeFE/vue-swipe ,I get error ``ReferenceError: document is not defined`` when SSR, what should I do?

**Comment by facesea** [comment]
@DualWield i had stop SSR, waiting for update:)

**Comment by yyx990803** [comment]
FYI this is not something that Vue can fix - instead, the libraries should prevent accessing `window` or `document` directly without checking for the environment first. You should be opening issues in the libraries you want to use regarding this.

**Comment by DualWield** [comment]
@yyx990803 Thank you very much~~

**Comment by ram-you** [comment]
@yyx990803 
The majority of libraries uses window or document because they are client-oriented. I think that instead of asking everyone to find a solution to this problem, it is better to think of a global and universal solution that would solve all these problems at a glance. thank you.

**Comment by mib200** [comment]
@yyx990803 I agree with @ram-you . I end up forking out most of the libraries and patching them up myself to check for the environment. It would be great if this can be incorporated in Vue itself.

And the way. I am 500% Vue convert. No more framework hells for me. Totally in love with SailsJS and VueJS architecture. Kudos to you and VueJS team.

Regards
