### ISSUE TITLE
Vue 2.0.0, vue-loader, splitted template and script

### ISSUE THREAD

**Issue by jxlarrea** [vuejs/vue#3823]
Just upgraded to Vue 2.0.0 final. My main.vue file is defined like this:

```
<template src="./main.htm"></template>
<script src="./main.js"></script>

```
I'm attempting to use the Vue 2.0 runtime only library but the above doesnt seem to work. I keep getting the following warning:

> vue.common.js:2569[Vue warn]: Failed to mount component: template or render function not defined. (found in root instance)

It seems like vue-loader is not actually compiling the referenced template. Am I missing something? Is this possible at all?

**Comment by sirlancelot** [comment]
Did you upgrade `vue-loader` too? If so, then it's probably a bug in `vue-loader` and you should report the issue there instead.

**Comment by posva** [comment]
Tested with latest vue and vue-loader. It works.
Try using vue@latest, vue-loader@9.5.1
If, after updating, you still have the issue, please open an issue on vue-loader
