### ISSUE TITLE
<template> unable to work, Cannot create property 'isStatic' on string ' '

### ISSUE THREAD

**Issue by lampard7824** [vuejs/vue#3824]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/3qpzv7v0/

template tag should be able to use for group multiple elements and inject into component slot. this used to work in rc8

**Comment by posva** [comment]
The parsing is generating an empty text node between the two `p`. As a workaround you can remove the space between them until we release a fix
