### ISSUE TITLE
Extra information for the transition guide that might help

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vue#3827]
I just upgraded an app from 1.0 to 2.0 and stubbed my toe on a few things. Here's a list of items that might help others if they were added to the transition guide:

1. A mention that the `events` option is gone. It's implied but not obvious.
2. A mention that `.literal` directive modifier is gone and how to handle.
3. A mention that `twoWay` directives and filters should be converted to `v-model` on a component wrapping an `input` (at least that seems the case).

I did not use the migration tool. My project was small enough where it didn't seem worth the effort.

**Comment by fnlctrl** [comment]
@chrisvfritz

**Comment by chrisvfritz** [comment]
Thanks @davidkhess! Can you open issues for each of these at [vuejs/vuejs.org](https://github.com/vuejs/vuejs.org/issues)? That's the repo for the core documentation.

**Comment by davidkhess** [comment]
Will do.
