### ISSUE TITLE
Vue 2.0 not render anything, 1.0 version is fine

### ISSUE THREAD

**Issue by overallduka** [vuejs/vue#3828]
Vue 2.0 is not rendering correctly.

I have this code:

`<span id="sample">{{ msg }}</span>`
```
new Vue({
    el: "#sample",
    data: {
      msg: "aqui"
    }
 }))
```

With vue 1.0.27 is ok, render fine the phrase, with 2.0 none is rendered. This is just an sample code, with real code nothing renders too. If i inspect element just appear `<!-->` in the place that should appear the code.

Im using brunch to manage the javascript file with normal import:

`import Vue from 'vue';`

inspecting the element i can see that vue is loading correctly(image below):

https://www.dropbox.com/s/84we5tnnt1nm22q/Screenshot%202016-10-01%2022.00.57.png

Well, just for information Vue is loading inside an iframe. I return to 1.0.27 version by now, try some things and nothing worked, hope you can help me. Thanks much.

**Comment by Halfeld** [comment]
There should be a Render Function there...

Check out: https://vuejs.org/guide/render-function.html

or as you is brasilian, I written a article about it: http://www.vuejs-brasil.com.br/render-functions-no-vue-js-2-0/

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
If you `import Vue from 'vue';` you get the runtime only build that cannot compile templates (either in-dom templates or `template` option).
In this case you need the standalone build, here is a helpful section explaining this:
https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by overallduka** [comment]
Thanks @Halfeld and @fnlctrl , the standalone version works fine for my case.
For who needed use standalone version in brunch the alias config in brunch-config should be:
```
npm: {
    aliases: {
      vue: "vue/dist/vue.js" 
    }
}
```
