### ISSUE TITLE
Polyfills for IE 8+ & Some mobile browsers

### ISSUE THREAD

**Issue by 11111000000** [vuejs/vue#383]
It is very difficult as you think?

**Comment by jcoffland** [comment]
Could you use this polyfill?: https://github.com/inexorabletash/polyfill/blob/master/es5.js

Some reliable estimates show that around 4% of the Internet is still using IE8.  Sad but true.

**Comment by TMiguelT** [comment]
I don't think that will work. [The code](https://github.com/inexorabletash/polyfill/blob/master/es5.js#L73) just seems to try  `__defineSetter__` and `__defineGetter__`, neither of which exist in IE, and it also tries IE8's native defineProperty which only works on DOM nodes while we need it to work on ordinary JS objects. I don't have a way of testing it, however.

**Comment by jcoffland** [comment]
Yeah, I think you're right.  It does say, "Partial support for most common case - getters, setters, and values."
