### ISSUE TITLE
refs not available in parent component 

### ISSUE THREAD

**Issue by crswll** [vuejs/vue#3834]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/crswll/acx3yvLt/3/

### Steps to reproduce
Just check out the console...

### What is Expected?
I expected the refs to be available in the parent component `<tabs>`.

### What is actually happening?
They're not available, but they are available in the root... Not sure if this is a bug or not?

**Comment by ktsn** [comment]
I think this is expected behavior since the `<tab>` is created on root component, same rule as data scope.
http://vuejs.org/guide/components.html#Compilation-Scope

**Comment by fnlctrl** [comment]
As explained by @ktsn.
`<tab>` and `<tabs>` are both root's children as they both appear in root's template.
> Everything in the parent template is compiled in parent scope; everything in the child template is compiled in child scope.

**Comment by crswll** [comment]
100% more clear this morning. Thanks!
