### ISSUE TITLE
$compile and cleanup

### ISSUE THREAD

**Issue by FrizzaUK** [vuejs/vue#3840]
I am currently migrating to vue 2, however the $compile and clean up methods no longer exist.  I have a component that dynamically creates layouts which include other component HTML.  I have taken a look at Vue.compile, but I cannot see how to replace the existing component template or render function with the one that has been compiled.

**Comment by yyx990803** [comment]
This is a pattern that is no longer supported nor recommended in Vue 2.0. Always try to drive the presence of child components via parent state instead of imperatively.
