### ISSUE TITLE
2.0 docs-- missing "slot" option on render function's data object

### ISSUE THREAD

**Issue by asselin** [vuejs/vue#3841]
Referring to this part of the doc: http://vuejs.org/guide/render-function.html#The-Data-Object-In-Depth

When writing a render function, if you want to pass something in a named slot to a component, you have to write something like this:

````
createElement(component, { }, 
  createElement('div', {
    slot: 'some-named-slot'
  }, [ <some content> ])
);
````

Currently, the documentation for `createElement`'s data object doesn't mention the `slot` field.

CC: @chrisvfritz

**Comment by Shmasya** [comment]
Why don't use a template?

**Comment by LinusBorg** [comment]
@asselin Thanks, good catch!

@Shmasya he just brought our attention to a mistake in our documentation, there's not problem with templates or anything.

**Comment by Shmasya** [comment]
@LinusBorg Why do we need such method? Can I use the old way with a template?

**Comment by LinusBorg** [comment]
Sure, you can. Vue 2.0 offers both ways

**Comment by Shmasya** [comment]
@LinusBorg but which path to choose? Which is more easier and faster? Or this way using render() is created for the people who came with the React?

**Comment by yyx990803** [comment]
Let's move this to the vuejs.org repo.

@Shmasya it's a matter of preference. If you are familiar with templates, I'd suggest stick to templates and only use render functions when you feel you have some component logic that cannot be expressed with templates.

**Comment by asselin** [comment]
@Shmasya In my case, I needed to write a render function to have more control than a template could provide.  The beginning of the page on render functions (http://vuejs.org/guide/render-function.html) provides an example of why you might want to write one vs use a template.

@LinusBorg I'll go ahead and open an issue against the vuejs.org repo per Evan
