### ISSUE TITLE
vue.common.js: Uncaught TypeError: Cannot read property 'toLowerCase' of undefined (on node <!---->)

### ISSUE THREAD

**Issue by rw3iss** [vuejs/vue#3844]
Seems to happen if I assign a value to a component data property from within the beforeMount() method. The component references the data object like:
```
 <div v-if="user != null">
      Hello.
 </div>

beforeMount() {
      this.user = this.$store.state.user;
}
```

Error is being thrown inside vue.common.js, line 4089:
```
  function assertNodeMatch (node, vnode) {
    if (vnode.tag) {
      console.log("assetNodeMatch", node, vnode);

      return (
        vnode.tag.indexOf('vue-component') === 0 ||
        vnode.tag === nodeOps.tagName(node).toLowerCase() // <----- thrown here
      )
    } else {
      return _toString(vnode.text) === node.data
    }
  }
```

It's interesting to note the error is only thrown when I actually assign this.user within beforeMount(). If I leave the v-if reference in the template, but don't assign anything to the property ever, nothing is thrown.
The console.log I put here shows this right before the error is thrown:

> assetNodeMatch  VNode {tag: "div", data: undefined, children: Array[1], text: undefined, elm: undefined…}

So it's seeing the node as plain '', and then nodeOps.tagName can't find a .tagName property on this given node, so it throws the error. This  node is generated by Vue, but I'm not sure why. Maybe it's if the server and browser template state is not matching (I'm using SSR), but regardless, this error should maybe be handled differently. 
Anyone have any suggestions?

**Comment by rw3iss** [comment]
Seemed to be because I was setting user on the main app component, and also a component underneath, but the component still thought the element was there, which seems weird.

**Comment by rw3iss** [comment]
I keep experiencing this in seemingly simple cases.
If I have a template which tries to access a data property as such:

```
    <div v-if="someData">
      <div>{{someData}}</div>
    </div>
```

This just wants to render the data if it exists.
Then in my component, I have:

```
    data() {
      return {
        someData: null
      }
    },

    created() {
      if(typeof window != 'undefined') {
        this.someData = {test: 'test'}
      }
    }
```

However, setting someData in any other method (besides the initial data() property) causes the error to be thrown. Does this happen for anyone else?

**Comment by LinusBorg** [comment]
While I not really know the hydration part of the codebase, it seems to me that what you are doing is asking for your App to break.

* you are rendering the component on the server with `someData: null`
* therefore, the Div is not rendered on the server.
* then, when the App is booting on the client, you *change* the state of the component to `someData: {test: 'test'}`
* you do this in `created`, so  *before* the component's virtual DOM is rendered.

This essentially means that the server didn't render the div, but the virtualDOM on the client expects it to exist.

And the reason that it does not happen when you do it in `mounted` is that in this case, you change the component's state *after* initial client-side render of the virtualDOM, and then change the components state, triggering a re-render.

**Comment by rw3iss** [comment]
@LinusBorg Thanks! I was just trying to understand why the error was being produced. Sounds like that's a solid reason.

**Comment by olsonpm** [comment]
I got this error due to "comments" containing angle braces outside one of my single-file-components.

e.g.

```vue
//
// README
//   - This component is an alternative to <my-button>
//
<template>
  <div>...</div>
</template>

<script>
...
</script>
```

**Comment by shiva1809** [comment]
[Vue warn]: Error in mounted hook: "TypeError: __WEBPACK_IMPORTED_MODULE_12_chargebee___default.a.init is not a function"


I have this type of error in vuejs2 what can i do now ? 
please help me i'm in trouble guyz

**Comment by LinusBorg** [comment]
This is a closed issue about a different problem. 

Use forum.vuejs.org for a questions, please.
