### ISSUE TITLE
Strange Error on Reload

### ISSUE THREAD

**Issue by nueko** [vuejs/vue#3847]
### Vue.js version
2.0.1

### Steps to reproduce
On Chrome push 5 to 15 times CTRL+SHIFT+R 
### What is Expected?
![vue-issue](https://cloud.githubusercontent.com/assets/2134953/19068904/ac7defde-8a4e-11e6-9d88-75e07625cdc9.JPG)

**Comment by fnlctrl** [comment]
Please make sure to follow [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), and provide a reproduction on jsfiddle/codepen etc. Thanks!

**Comment by anishdcruz** [comment]
@nueko are u using laravel elixir? If yes it has something to do with hot reloading delay.

**Comment by nueko** [comment]
Yes, hot reload, how to do that?
