### ISSUE TITLE
Problem with ordering of array with Sortablejs component

### ISSUE THREAD

**Issue by codylandry** [vuejs/vue#3849]
I created a vue 2.0 sortable component that takes in a javascript array and emits an event with the new ordering of the array when an item is dropped.  I'm having a weird issue where this just doesn't work in some situations.  I thought it was related to having images in the v-for, but was able to reproduce it without images.  In my jsfiddle, you'll see that the list on the left will break after reordering items several times, whereas the list on the left never breaks.  

The 'position' property should update to reflect the new order (1, 2, 3, 4) after the item is dropped.  

I'm hoping that it's something simple I'm missing with using sortable.  Here's the fiddle:

https://jsfiddle.net/codylandry/4wsnh3sk/50/

**Comment by LinusBorg** [comment]
Unless you are sure that this is a Vue-related bug, please use our forum for support-releted questions: forum.vuejs.org
