### ISSUE TITLE
v-focus does not work in official document 2.0

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3854]
### Vue.js version
2.0.0-rc.3

### Reproduction Link
[https://jsfiddle.net/matiascx/tdhzjavg/1/](https://jsfiddle.net/matiascx/tdhzjavg/1/)

### Steps to reproduce
run
### What is Expected?
input focused
### What is actually happening?
No focus happen on input element

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, but it actually belongs to the [vuejs.org](https://github.com/vuejs/vuejs.org) repo, please you open an issue there instead, thanks!

**Comment by cnweibo** [comment]
@fnlctrl , what do you mean "it belongs to vuejs.org repo?"
It shouldn't be a bug??

**Comment by fnlctrl** [comment]
It's no longer a bug. rc.3 is way too old. https://jsfiddle.net/tpj09eoo/
The only problem here is that the docs weren't updated...
