### ISSUE TITLE
vendor.js load so slow!

### ISSUE THREAD

**Issue by vopjie** [vuejs/vue#3855]
my project is builded with vue-cli, and the vendor.js is loaded very very slow!
![image](https://cloud.githubusercontent.com/assets/9351855/19111508/78ae7a0e-8b32-11e6-83a0-bbbf8b837df5.png)

somebody please help me !

**Comment by LinusBorg** [comment]
Hi @vopjie,

1. This is not a Vue problem (and problably not a vue-cli problem either), it's a webpack problem
2. Issues on Github are reserved for bug reports.

Please use forum.vuejs.org or ask webpack experts on Stakc Overflow.

**Comment by vopjie** [comment]
ok, thank you so much
