### ISSUE TITLE
Vue doesn't understand cdata: <![CDATA[...]]>

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue#3856]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/haobxtgh/

### Steps to reproduce
Use <![CDATA[ <div></div> ]]> in a slot.

### What is Expected?
Vue treats the content inside cdata as plain text.

### What is actually happening?
Vue attempts to parse the cdata content and does strange things.

**Comment by yyx990803** [comment]
Upon investigation, CDATA is actually XML only - this type of usage is not supported in HTML5, with or without Vue.
