### ISSUE TITLE
Computed value from parent as a child component's props should be reactive.

### ISSUE THREAD

**Issue by Emiya0306** [vuejs/vue#3860]
Just like the title describe.

I have a parent component, this parent component has a computed value (which is set cache: false, and have not reactive dependency in getter, just like Date.now()).

So I want to send this computed value to a child component as a props. But in fact, the computed value in child component is not reactive.

[Here](https://jsfiddle.net/esc228/zpkt93eL/2/) is the example to show this(resize the editor and click the button, you will see this). I think it is normally for computed value is reactive for component.

**Comment by posva** [comment]
It's working as expected: it's not reactive in bindings, only works for js:
http://v1.vuejs.org/guide/reactivity.html#Inside-Computed-Properties (at the end)
You should open the question on the forums (http://forum.vuejs.org/) for help

**Comment by Emiya0306** [comment]
@posva But it does not make sense that when I make computed no cache, and call it again in component, I will get the value never compute.

**Comment by fnlctrl** [comment]
> However, note this only affects programmatic access inside JavaScript; data-bindings are still dependency-driven.

Therefore, it doens't work if you pass the computed property by prop (which is a data-binding), and it only works when you execute `this.parentWidth = this.$parent.realtimeWidth`.

**Comment by Emiya0306** [comment]
@fnlctrl Oh... I see, so it means there is no way to bind computed value to child component... THX!

**Comment by fnlctrl** [comment]
No I didn't mean you cannot bin computed value as prop to child component. It just doesn't work in your case, because your computed value doesn't have dependencies (`this.$el.getBoundingClientRect().value` isn't a dependency, nor is it reactive)

**Comment by Emiya0306** [comment]
Yeah~ Get it, I'm sorry I lost this point. 😄
