### ISSUE TITLE
Possible tag feature

### ISSUE THREAD

**Issue by wffranco** [vuejs/vue#3862]
You have some tags reserved for easy handle of items...
- `<template>` like a group container (e.g. v-if validations, v-for cycles)
- `<slot>` for parent content extention
- `<component>` for dynamic component

But you don't have the simplest need... some that let you mutate a single element:
- choice between create a `div` or `li` or `tr` depending of a container.
- create a dinamic `input` element, that let me choice if create an `input` or a `textarea`.

That just examples. So I think that you could create a reserved tag like component.
You can call it e.g `<element :is="tag"></element>`.

I know that I can do that in Vue 2 using render... but I think that a render is harder to handle for something as simple as choice if use a `div` or a `span`.

**Comment by yyx990803** [comment]
As you said, this can be done with render functions and it's trivially easy to implement. I think this is best left in userland.

**Comment by wffranco** [comment]
I said that is easy for things like mutate between single items, but when you need events or something else look harder to render it.
Well, is just an idea.

**Comment by wffranco** [comment]
Now testing I discovered that the attribute "is" is not reserved for components, so this do exactly what I need 👍
