### ISSUE TITLE
[Router] router.start is not in either migration and/or migration-helper

### ISSUE THREAD

**Issue by lsv** [vuejs/vue#3865]
My old code was

```
var App = require('./component/App.vue');

var router = new VueRouter();
router.transitionOnLoad = true;
router.map({
    '/': {
        component: FrontComponent
    }
});

router.redirect({
    '*': '/'
});

router.start(App, '#app');
```

After running migration tool my code is

```
var App = require('./component/App.vue');

var router = new VueRouter({
    routes: [
        { path: '*', redirect: '/' },
        { path: '/', component: FrontComponent },
        { path: '/:station', component: BoardComponent },
        { path: '/:station/:url', component: JourneyComponent }
    ]
});
router.start(App, '#app');
```

Im getting this `Uncaught TypeError: router.start is not a function` so I looked through [vue router migration](http://vuejs.org/guide/migration-vue-router.html#router-map-deprecated) but router.start is not defined anywhere.

Then I looked in the docs for [router 2.0](http://router.vuejs.org/en/), but router.start is not defined anywhere, and the getting started is just

```
const app = new Vue({
  router
}).$mount('#app')
```

But I use a .vue file to generate my app, so I'm a bit lost on what to do

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, can you open this on the [migration helper](https://github.com/vuejs/vue-migration-helper/)'s repo instead? Thanks!

As for your question, simply do:
```js
var App = require('./component/App.vue');
const app = new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```
