### ISSUE TITLE
computed class [ bug ? or  originally designed]

### ISSUE THREAD

**Issue by bluemsn** [vuejs/vue#3871]
I found a bug when using the computed props, the class that changed data generation is always just the class that the default node merges. Maybe I manually added class or removed class in `mounted hooks`, and vue does not help to add up

eg.

https://jsfiddle.net/ga968ff3/2/

 

and  fix it by this 

```js
function updateClass (oldVnode, vnode) {
  // ....
  updateVnodeStaticClass(vnode) // fix the custom addClass from el.className
  var cls = genClassForVnode(vnode)
}
// to fix it 
function updateVnodeStaticClass(vnode) {
  var el = vnode.elm
  var data = vnode.data
  var classList = Array.prototype.slice.call(el.classList)
  var staticClass = data.staticClass.split(' ')
  // find the diff class from el.className
  classList.forEach(function(item) {
    var vnodeClass = Object.keys(data.class);
    if (vnodeClass.indexOf(item) == -1 && staticClass.indexOf(item) == -1) {
       staticClass.push(item)
    }
  })
  vnode.data.staticClass = staticClass.join(' ')
}

```

**Comment by yyx990803** [comment]
Vue 2.0 does not support manually adding/removing classes when you are already using a Vue-managed class binding. If you want to manage the class, do it through Vue - don't mix it. The implementation is intentionally using a string to ensure class order.

**Comment by bluemsn** [comment]
ok, Thanks 

just 

Sometimes, I use a third-party library, will change the class, but when I update the data, it will cover it
