### ISSUE TITLE
How can a functional component be used as a named slot of another component?

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#3872]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/x3k60w7c/

### Steps to reproduce
Just run the demo

### What is Expected?
Default slot fallback
[inner]

### What is actually happening?
[inner]
Named slot fallback

`inner` should replace the `<slot name="abc">` part of `outer`, but instead it replaces the `<slot>` part. Seems its `slot` attribute is not working. 
It works fine if `functional: true,` is deleted (line 15). So is functional component not supposed to be a named slot of another component or am I using it wrong?

**Comment by yyx990803** [comment]
This should work, indeed a bug.
