### ISSUE TITLE
Mistake in a code sample in the documentation

### ISSUE THREAD

**Issue by nickretallack** [vuejs/vue#3873]
https://vuejs.org/guide/render-function.html#Constraints

```javascript
render: function (createElement) {
  var myParagraph =
  return createElement('div',
    Array.apply(null, { length: 20 }).map(function () {
      return createElement('p', 'hi')
    })
  )
}
```

The `var myParagraph` line should be removed.

https://vuejs.org/guide/reactivity.html#Declaring-Reactive-Properties

"you have to initialize you instances"

**Comment by posva** [comment]
Nice catch, thank you!

I added a PR for it. In case next time you prefer submitting  the PR yourself, you can do so on https://github.com/vuejs/vuejs.org
