### ISSUE TITLE
suggest: props can be used without declare is better

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#3874]
In my case, I always define an component which is suit for almost all scene. And always I will extend this component to fit one project. In vue, props should be declared in component, which makes it complex, I need to declare the same props again. So why not just like rect, props just used for validation.

**Comment by simplesmiler** [comment]
Do you define your function with `()` signature, and then use `arguments`?

**Comment by Jokcy** [comment]
@simplesmiler what's that mean?

**Comment by ktsn** [comment]
I understand the convenience of this in react world.
However, the props of vue components are assigned under `this` while react has dedicated property `this.props`. So allowing to pass props without declaration possibly occur naming conflict with `data`, `computed` or `methods`.

**Comment by Jokcy** [comment]
@ktsn Yeah, this is a problem. But in my opinion, especially in vue2.0 which we can use jsx style, my issue is more usefully. besides we can use props validation to avoid your problem or just like react put props in props object.

Also, vue is great, and I will use vue2.0 to restructure my app, I just want it get better😁

**Comment by yyx990803** [comment]
Like @ktsn explained, this is not feasible in Vue.

And imo it's more maintainable to always declare props.
