### ISSUE TITLE
The word "emitted" is written to "$emit ted" in "Migration from Vue 1.x" doc

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue#3875]
### Vue.js version
2.0.0-rc.1

### Reproduction Link
http://vuejs.org/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on

### Steps to reproduce
Read the first line of "Listening for Native Events on Components with v-on" in Chapter "Migration from Vue 1.x":

When used on a component, v-on now only listens to custom events **`$emit` ted** by that component. 
### What is Expected?
When used on a component, v-on now only listens to custom events **emitted** by that component. 
### What is actually happening?
**`$emit` ted**

**Comment by posva** [comment]
that's intended, `$emit` is the function name
