### ISSUE TITLE
 v-model and dynamic input type (2.0)

### ISSUE THREAD

**Issue by SuperSeb92** [vuejs/vue#3877]
### Vue.js version

2.0.1

### Reproduction Link
https://jsfiddle.net/2wv71Lzv/1/

I'm building a form component, and given the radio / check inputs are so similar, I'd like to reuse the same component by having the type as dynamic (with a "isMulti" flag turning it into a checkbox rather than a radio)

This doesn't seem to work with v-model in VueJS 2

**Comment by yyx990803** [comment]
This is not supported (and never supported in v1) because `v-model`'s binding is performed once at creation time. You will need to use `v-if` branches.
