### ISSUE TITLE
Multi-type prop validation is not consistent

### ISSUE THREAD

**Issue by aphofstede** [vuejs/vue#3879]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/alexman/f7sb0rd3/9/

### Steps to reproduce
Create a component with a prop of type `[String, Boolean]` and instantiate it with a boolean value or shorthand prop notation. (`<my-component my-prop></my-component>`)

### What is Expected?
Booleans are accepted and passed to the validator as a boolean value.

### What is actually happening?
You'll see that it will not validate booleans / shorthand prop notation. 
Defining it reversed, `[Boolean, String]`, does seem to work as expected except for not being able to pass false as a value.

### Observations
I noticed `validateProp()` does the following "magic", which doesn't seem to take the option of an array of types into account?
```
  if (getType(prop.type) === 'Boolean') {
    if (absent && !hasOwn(prop, 'default')) {
      value = false
    } else if (value === '' || value === hyphenate(key)) {
      value = true
    }
  }
```

**Comment by defcc** [comment]
getType func seems not to deal with multi-type props, it just returns the first type

I will try to make a pr

**Comment by posva** [comment]
I'm not sure to understand the issue. Were you expecting the value to be cast as a Boolean? Although you said it was either a String or a Boolean?. Why would using the  order to specify what the prop should be cast to be non-consistent?

**Comment by aphofstede** [comment]
Not consistent: Because the behaviour differs between `type: [Boolean, String]` and `type: [String, Boolean]`.
About expectations: Using just the `type: Boolean` does some magic to convert the eventual `value` to a boolean type. With multiple allowed types, when the caller passes a "boolean'able" value, I would expect `value` to be a boolean type also. If it cannot be resolved to a boolean but conforms to another type in the array of allowed types (and after it passes custom validation) -> also valid. Otherwise -> invalid.

**Comment by posva** [comment]
What do you mean by magic?  Do you refer when there's no value?
I'd say it's normal to differ because types are differents (order in array matters)

**Comment by aphofstede** [comment]
I referred to the piece of code mentioned in "Observations" above.
Why does the order matter? I interpret it as "any of X, Y, Z"

**Comment by posva** [comment]
I'll share the rest of the team.
