### ISSUE TITLE
Conditional statements on paths that may not exist

### ISSUE THREAD

**Issue by FrizzaUK** [vuejs/vue#3880]
### Vue.js version
2.0.0

### Reproduction Link
http://jsfiddle.net/mattrisby/9esbgeLw/6/

### Steps to reproduce
See above
I could use a computed property or by changing if statements, e.g. v-if="my.data && my.data.path && my.data.path.exists".  This is not ideal as it would add a lot of unnecessary code.

### What is Expected?
v1 of Vue would not fail if a property path does not exist.

### What is actually happening?
TypeError exception is thrown.

**Comment by yyx990803** [comment]
No, 1.x doesn't support this either. Implicitly eating non-existent paths can lead to very hard to debug scenarios, e.g. if you make a typo, everything just fails silently. Also, this is a breaking change so it's out of the question.

**Comment by FrizzaUK** [comment]
It was working in 1 as we are migrating lots of components to v2.  A warning message is sent to the console rather than an exception: 
[vue warn] Error when evaluating expression "my.data.property.does.not.exists": TypeError: Cannot read property 'not' of undefined

Just forked the example to point to Vue 1.0.28

http://jsfiddle.net/mattrisby/tdoa46s7/1/

**Comment by FrizzaUK** [comment]
Looking at the code, version 1 has a try catch within the function Watcher.prototype.get, which then outputs the warning message.

**Comment by yyx990803** [comment]
@FrizzaUK there is warning in v1, which means it's not supported and you should not be doing it. In v2 the try catch is done at a component level instead of expression level, so it causes the affected component to output nothing but doesn't affect other components.

**Comment by FrizzaUK** [comment]
Understood, but surely an 'if' statement within a template engine should handle whether a property path exists?  Granted that Javascript doesn't really support this behaviour hence why some third party libraries such as lodash provide basic functions (_.get) to plug the gaps.  It seems a shame to have to write verbose statements or by wrapping them in a function call, e.g. 
v-if="doesPathExist(my, 'data.property.does.not.exists')"

**Comment by posva** [comment]
@FrizzaUK 
> if you make a typo, everything just fails silently
If you're having the same `obj && obj.property` in the same component, consider using `v-if` in a higher node.
