### ISSUE TITLE
bug:  when i use && in the directive, it transfrom to  &amp;&amp;

### ISSUE THREAD

**Issue by ivan403704409** [vuejs/vue#3889]
vue2,   when i use **&&** in the directive, it transfrom to  **&amp;&amp;**

###  `v-show="isInit && commentTeacherLen"`
 ==>
### `- invalid expression: v-show="isInit &amp;&amp; commentTeacherLen"`

but,i don't want to use compiled cause it's so simple.

**Comment by yyx990803** [comment]
Cannot reproduce. Make sure you are using the latest version of Vue (2.0.1).
