### ISSUE TITLE
Vue 2.0.1: Single letter key aliases in key modifiers don't work.

### ISSUE THREAD

**Issue by hootlex** [vuejs/vue#3890]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/wowg5tta/

### Steps to reproduce
Type 'v' in the first textbox.

### What is Expected?
It is expected to see an alert.

### What is actually happening?
No alert is shown.

### More info
If you type 'v' in the second textbox which uses keycode 86 instead of the key alias it works as expected.

**Comment by crossjs** [comment]
valid keyCode aliases:
```
  esc: 27,
  tab: 9,
  enter: 13,
  space: 32,
  up: 38,
  left: 37,
  right: 39,
  down: 40,
  'delete': [8, 46]
```
https://github.com/vuejs/vue/blob/master/src/compiler/codegen/events.js#L5-L16

**Comment by phanan** [comment]
If you want to support custom keys, define them as global [keyCodes](http://vuejs.org/api/#keyCodes).

**Comment by hootlex** [comment]
The example I've posted on jsfiddle is taken from the Vue 2 guide.
So, key aliases should be either removed from the guide or added in the keyCode object.

http://vuejs.org/guide/events.html#Key-Modifiers

**Comment by phanan** [comment]
Oh, indeed. We may need to amend our doc. Ping @chrisvfritz.

**Comment by phanan** [comment]
By the way, I think the usage sample for http://vuejs.org/api/#keyCodes could be better, as `esc: 27` support is built-in and not any "custom." Will submit a PR to the repo.

**Comment by hootlex** [comment]
The same applies for `Vue.config.keyCodes.f1 = 112` in the guide too.
I will submit a PR there.

**Comment by phanan** [comment]
What's wrong with `f1`? It works just according to the docs https://jsfiddle.net/phanan/wowg5tta/1/

**Comment by hootlex** [comment]
Yes, it works. But if single letter key aliases come back, it won't.

**Comment by hootlex** [comment]
For custom, I have in mind something like `Vue.config.keyCodes.submitKey = 112`.
Isn't that the case?

**Comment by phanan** [comment]
What do you mean by single letter key aliases coming back? The feature has been removed from 2.0 I believe. What we need to do is amend the doc to reflect this change.

For your other question, please see the keyCodes API link above for documentation. If you need more help, I'd suggest using the [forum](http://forum.vuejs.org) instead.

**Comment by hootlex** [comment]
I mean that if they are not deprecated and it's just a bug, they could come back.
If you say this feature is removed then they won't. :)

It is weird though since I can't find the deprecation on the [Vue 2 Changes](https://github.com/vuejs/vue/issues/2873). Maybe it's just missing.
