### ISSUE TITLE
Vue cannot compile template string of ES6 in some browsers

### ISSUE THREAD

**Issue by heyz-scott** [vuejs/vue#3891]
### Vue.js version
2.0.1 stand-alone build

### Reproduction Link
https://jsfiddle.net/loliconer/Lazssgog/

### What is Expected?
The link url should be compiled to "http://vuejs.org/api".

### What is actually happening?
Vue cannot compile ES6's template string in IE11 and below, Tencent X5(QQ mobile, wechat), UC mobile.
In these browsers:
```
[Vue warn]: failed to compile template:
```

**Comment by crossjs** [comment]
Tencent X5 does NOT support ES6's template string currently.
You should NOT use ES6 in template.

**Comment by heyz-scott** [comment]
@crossjs I know that, but since Vue supports IE9+ according to the README.md, shouldn't it support IE11 in this occasion?

**Comment by yyx990803** [comment]
Vue itself supporting IE9 doesn't mean you can use JS features not supported in IE9. The expressions you use in templates must take your target browsers into account.
