### ISSUE TITLE
Views created inside components: {} are put in global scope

### ISSUE THREAD

**Issue by aphofstede** [vuejs/vue#3892]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/alexman/xqzen1ng/1/

### Steps to reproduce
Set up a as a template with a component tag and an "is" attribute:
```
<template>
    <component is="viewname"><slot></slot></component>
</template>

```
And create a view in the components field:
```
    components: {
  	'first-view': Vue.component('first-view', {
        render: function (createElement) {
          return createElement(
                  'div',
                  this.$slots.default
          )
        }
    })

```
Now create a second component with the same "is". It will render.

### What is Expected?
The [documentation states](http://vuejs.org/guide/components.html#Local-Registration) that components created in the `components` object of a component will only be available in that component's scope.

### What is actually happening?
The view becomes a global component. This makes code re-use tricky and gives unexpected results if using somewhat generic view names.

**Comment by yyx990803** [comment]
It's registered globally by the Vue.component() call, which is unnecessary here...

**Comment by aphofstede** [comment]
@yyx990803 I see. Is there another way to inline a simple component here, that doesn't require template client-side rendering? Specifically I want to do `isComplex ? 'div' : 'button'` and `hasHref ? 'a' : 'div'`.
I saw a PR coming up with a fix that would allow v-if/v-else in the main template, but it would be nice to know how to do it here anyway.

**Comment by yyx990803** [comment]
Use a render function? Please make sure to read through the docs before opening issues / asking questions.

**Comment by LinusBorg** [comment]
```js
components: {
    'first-view':  {
        render: function (createElement) {
          return createElement(
                  'div',
                  this.$slots.default
          )
        }
    }
}
```

**Comment by aphofstede** [comment]
Thanks @LinusBorg, that works. I thought I had tried that, but I think I forgot to wrap it in an object { render: ... } and ran into problems.
