### ISSUE TITLE
add warning or trim for event handler with extra space in template

### ISSUE THREAD

**Issue by HeChenTao** [vuejs/vue#3893]
### Vue.js version
2.0.1

### Reproduction Link
http://jsbin.com/faremewici/2/edit?html,js,console,output

### Steps to reproduce
As you can see , `@click=" onClickHandler "` has extra space.  
then click the link in output
### What is Expected?
the console should warn that event handler doesn't exist or execute `onClickHandler` directly
### What is actually happening?
the console output nothing

Even in webpack dev environment, Vue doesn't show any warning.
I expect Vue can give a warning in this situation or just trim it to execute `onClickHandler` method.

**Comment by posva** [comment]
@HeChenTao I'm curious, how did you find yourself with spaces around that handle?

**Comment by HeChenTao** [comment]
@posva Because I find the handler is not called, so I look into the code again and find spaces.
That's not important. Just need a warning for it in dev environment.

**Comment by posva** [comment]
@HeChenTao But, how were the spaces introduces in the first place?

**Comment by HeChenTao** [comment]
@posva Yes. I just made a mistake. I wrote code like`@click="handler "`. Adding a warning in this case can make Vue more friendly.
