### ISSUE TITLE
Issue with rendering certain Unicode characters

### ISSUE THREAD

**Issue by dwightwatson** [vuejs/vue#3895]
### Vue.js version
2.0.1

### Reproduction Link
http://jsfiddle.net/wmmw143f/1/

### Steps to reproduce
Run the JSFiddle above and you will see the content isn't displayed and errors in the console.

### What is Expected?
I would expect the app to run regardless of the Unicode characters, without errors.

### What is actually happening?
```
[Vue warn]: failed to compile template:

<div id="app">
  This is user-generated content, and unfortunately includes the Unicode character 2028 right here:  .
</div>

 (found in root instance)
[Vue warn]: Error when rendering root instance: 
Uncaught TypeError: Cannot set property 'isStatic' of undefined
```

### Background
I'm not sure if this is the right place for this or not, but I'm of the feeling this is a bug with Vue. I'll also point out that I'm not that knowledgable about character encodings, but here is the information I have.

We have been testing the Vue 2.0 upgrade on our website which has a lot of user-generated content. It appears that some of our user-generated contains uncommon Unicode characters like [U+2028 Line Separator](http://www.fileformat.info/info/unicode/char/2028/index.htm). These appear invisible by standard.

However, when they appear in the content of a Vue 2.0 page, Vue fails completely and then removes it's entire DOM node from the tree, leaving the page bare.

[Here is a JSFiddle that demonstrates the issue](http://jsfiddle.net/wmmw143f/1/). You'll notice that JSFiddle highlights the Unicode character in question. When you remove that character, the app runs correctly.

**Comment by defcc** [comment]
According to [ Line Terminators](http://ecma-international.org/ecma-262/5.1/#sec-7.3), both \u2028 and \u2029 could cause this problem.

Should the special chars be replaced in genText func? If so, I will try to make a pr.

**Comment by defcc** [comment]
Maybe it's better to the replacement during the phases of chars parsing

**Comment by btolarz** [comment]
`Uncaught TypeError: Cannot set property 'isStatic' of undefined`
for Vue 2.0.7 when \u2028 character is in DOM element attribute on creating new Vue instance.
`<img src="http://placehold.it/350x150" alt="hello\u2028 word" />`
http://jsfiddle.net/3hmp0e16/
