### ISSUE TITLE
Data variables cannot be accessed in computed property filter function

### ISSUE THREAD

**Issue by jolamar** [vuejs/vue#3897]
See this code pen [demonstrating a data variable not accessible from within a list filter](http://codepen.io/jolamar/pen/QKmXwZ) but it is accessible if you [assign a temporary variable before the filter](http://codepen.io/jolamar/pen/EgEBKW)

**Comment by yyx990803** [comment]
this.odd inside the iterator function doesn't point to the Vue instance.
