### ISSUE TITLE
Chrome+Vue 2 = multiple select items not selected correctly 

### ISSUE THREAD

**Issue by lauri911** [vuejs/vue#3901]
Addition to issue #3852 via f9bef75.

When I opened issue #3852, there was also another problem, I did not know was they related or not.

Looking at solution f9bef75, I tried it right away --- multiple selections don't work as they should:
only last item is selected from preselected items.

https://jsfiddle.net/9uw2q3xp/1/
or
https://jsfiddle.net/u2xbkp34/1/

PS. Vue 1 works fine, I already downgraded my apps :)

**Comment by defcc** [comment]
When pathing dom, the **mutliple** attribute of select dosen't apply at first, so the mutli selected option dosen't work.
