### ISSUE TITLE
v-if && operator not working

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#3906]
### Vue.js version
2.0.1

### Steps to reproduce
```pug
div(v-if="boolean1 && boolean2")
```

will give an error `invalid expression: v-if="boolean1 &amp;&amp; boolean1"`

could be a problem of pug render engine translating `&` to `&amp;` ?

**Comment by vuchl** [comment]
I bet it's pug since it works with default html template. You can try with 
```html
div(v-if="boolean1 #{&}#{&} boolean2")
```
to not escape the ampersant

**Comment by nerdyglasses** [comment]
You're supposed to use a computed value instead if I understand the docs right.

Have a look that the documentation:
http://vuejs.org/guide/syntax.html#Using-JavaScript-Expressions

> one single expression

**Comment by paulpflug** [comment]
```jade
div(v-if="boolean1 #{&}#{&} boolean2")
```
yields
`v-if="boolean1 #{&amp;}#{&amp;} boolean2"`

I'm using computed values instead, but this is very verbose very fast:
```coffee
computed:
    boolean1AndBoolean2: -> @boolean1 and @boolean2
    boolean1AndNotBoolean2: -> @boolean1 and not @boolean2
```

**Comment by yyx990803** [comment]
Pretty sure this is pug's problem - it works in vanilla Vue templates properly. There should be some way to make pug not escape special chars in attribute values.

**Comment by nanotronic** [comment]
Had the same problem with vue-multiselect for vue 2 and gulp-babelify. But without pug. Switching to webpack solves this...

**Comment by red436** [comment]
When you are using pug you have to use v-if!="boolean && boolean2" the ! after the attribute being key.
