### ISSUE TITLE
transition for children created with v-for are only triggered with appear

### ISSUE THREAD

**Issue by paulpflug** [vuejs/vue#3909]
### Vue.js version
2.0.1

### Reproduction Link
http://jsfiddle.net/5sH6A/770/

### Steps to reproduce
Have a list with v-for and transition for each item

### What is Expected?
Transition should be triggered on adding a item on runtime

### What is actually happening?
Transition is only triggered on removing item and not on adding

**Comment by yyx990803** [comment]
In 2.0 for a list of items you need to use `<transition-group>`: http://vuejs.org/guide/transitions.html#List-Transitions
