### ISSUE TITLE
Empty data string is converted to object

### ISSUE THREAD

**Issue by gapipro** [vuejs/vue#391]
I have created data property with empty string as value.
Then in view I used v-if to display element only when length of created property is higher then 0.

When using such property in input field it shows '{}' and it looks like that property was converted from string to object.

Here is a fiddle with this issue: http://jsfiddle.net/gapipro/o4c1fjcg/ 

How do I fix this behaviour?

**Comment by AndersBillLinden** [comment]
This is marked as resolved without a solution. vue should not convert an empty string to an object, right?
