### ISSUE TITLE
iOS Safari/Chrome + Multiselect + Vue 2

### ISSUE THREAD

**Issue by lauri911** [vuejs/vue#3911]
#3852 and #3901 --- Its not over yet. 

https://jsfiddle.net/5sjt0jyq/1/

Run this Fiddle on iOS Safari or Chrome and you see at first that "3 items" are selected --- but when you open this select, then 1st item is unselected. 
Just click "done" and "3 items" remains. 
Open it again (1st item is unselected) and click "done" again --- now "2 items" selected. 
Open/close again and "3 items" selected. 
Repeat this sequence and "3 items" and "2 items" keep changing without selecting or deselecting anything.

**Comment by sqal** [comment]
I don't know if these commits fixed the, but they're not included in the latest 2.0.1 build. You have to wait for the next release or clone the repo and build it by yourself.

**Comment by lauri911** [comment]
You are right about it - i tought they was included already in vue.js at dev. 
Ok, lets wait next release then.

**Comment by yyx990803** [comment]
I tested your fiddle locally, and interestingly, this is a bug in iOS itself: `<select multiple>` is just messed up. The weird behavior exists even without Vue involved at all.

**Comment by lauri911** [comment]
Youre right again :)
Seems that multiselect is some "very special" item in 21st century. And we are waiting for self-driving cars? :)
