### ISSUE TITLE
get props value through code

### ISSUE THREAD

**Issue by rockkratos** [vuejs/vue#3914]
Hi Guys, 

May I know how to get props value through code? 
Not just only in template by v-bind. 

I want to get this props value to control css class in data function. 
Just like the below. 

```
data() {
    return {
      classes: {
        switch: true,
        'float-left': true,
        () => {
            return this.props.size;
        }
      }
    };
  },
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

---------

```js
data() {
    return {
      classes: {
        switch: true,
        'float-left': true,
        size: this.size
      }
    };
  },
```
or use `this.size` directly.

**Comment by rockkratos** [comment]
Thanks for your feedback quickly. 

Just a little fixed. 

```
data() {
    return {
      classes: {
        switch: true,
        'float-left': true,
        [this.size]: true
      }
    };
  },
```

That should be fine.
