### ISSUE TITLE
Can't change select box with arrow keys in certain cases

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue#3916]
I've uploaded a simple standalone project to https://github.com/rightaway/demo that explains the situation.

If you focus the select dropdown and try to use the up/down arrow keys to change it, it doesn't work. In the console the 'oninput' does get printed though for every key press.

But if you comment out https://github.com/rightaway/demo/blob/master/src/Page1.vue#L32, then it does work. Or if you leave that uncommented but instead remove the :class part in https://github.com/rightaway/demo/blob/master/src/Page1.vue#L5, it does work as well.

I'm working against the latest stable Chrome, and have tried to figure out what could be causing such strange behavior but no luck.

**Comment by LinusBorg** [comment]
The problem is that the component rer-renders onInput because you change the class of the select, but at this point, the new selected value has not been saved to `data` yet. So the component re-renders with the initial value.

https://jsfiddle.net/Linusborg/726utwzz/1/ (check the console)

If you use the `change` event instead of input (which comes after), the value has been written when the class is changed, so the component re-renders with the new value

https://jsfiddle.net/Linusborg/726utwzz/2/

**Comment by rightaway** [comment]
Actually while it doesn't work in Chrome it works in Firefox. Any specific reason that might be the case?

**Comment by rightaway** [comment]
Based on your explanation, wouldn't I see the same problem when changing the dropdown with the mouse? Why is this problem only appearing when trying to change the value with the keyboard?

**Comment by LinusBorg** [comment]
> Actually while it doesn't work in Chrome it works in Firefox. Any specific reason that might be the case?

Appearantly, Firefox does not issue an `input` event in that case, only a `change` event. I tried to `console.log` from the `onInput` callback, but the console did not show anything.

> Based on your explanation, wouldn't I see the same problem when changing the dropdown with the mouse? 

You should, and it does happen with the mouse as well, at least for me, with my reproduction fiddle, from above.

**Comment by rightaway** [comment]
> You should, and it does happen with the mouse as well, at least for me, with my reproduction fiddle, from above.

In the fiddle (the first of both fiddles above, demonstrating the problem), if I select a different element in the dropdown with the mouse then both `name` and `myClass` update along with what appears in the checkbox. If I try to select a different dropdown element by up/down on the keyboard then only `myClass` changes.

Are you not seeing the same behavior? I'm on a very recent stable chrome 53.0.2785.143 on linux.

**Comment by LinusBorg** [comment]
I'm on latest stable chrome on Mac (and tested on Windows as well when I replied before), and no, I don't see what you are describing.

The error happens with mouse or keyboard for me.
