### ISSUE TITLE
Multiple select elements @change event problem

### ISSUE THREAD

**Issue by taskaz** [vuejs/vue#3917]
Multiple select box does not work in same Vue instance.

### Vue.js version
* Vue.js v2.0.2

### Reproduction Link
https://jsfiddle.net/hd0drbo0/3/

### Steps to reproduce
Change second select box value, method "testMethod" will be called infinite times, even it is not bonded to second select box.
Change first select box value, and later change second select box value, everything works as expected.

### What is Expected?
Update of different models of select.
### What is actually happening?
Infinite call of not assigned @change method.

**Comment by fnlctrl** [comment]
Cannot reproduce on windows 10 x64 Chrome 53 / Firefox 48 / Edge, everything works fine here.
Can you specify the system and browser you're using?

**Comment by taskaz** [comment]
Windows 10 x64, Chrome 53.0.

**Comment by fnlctrl** [comment]
> This happens only if at least one select element model is not initialized, existing value in select options is not specified in model by default. 

Ok.. I see the problem now, looks like a bug to me.
