### ISSUE TITLE
Issues templates and JSFiddle require updating

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3918]
I noticed that the Issues template states by default vue 2.0.0rc1. It would be nicer if it just state 2.x.x.

Additionally if you follow the fiddle link provided it doesn't execute as the example is setting the body as element, which is now forbidden.

**Comment by fnlctrl** [comment]
Thanks! The jsfiddle template has been fixed in https://github.com/vuejs/vue/pull/3921
