### ISSUE TITLE
beforeUpdate hook in directives?

### ISSUE THREAD

**Issue by naltatis** [vuejs/vue#392]
We are trying to find a solution for being notified before a dom update takes place.

In our particular usecase we are integrating vue with a third party plugin that also manipulated the DOM. We are looking for a safe way to ensure this execution order:
1. vue renders dom
2. lib initializes (dom modification)
   ==> state update ($set)
3. lib uninitialize (revert dom modification)
4. vue rerenders dom
5. lib initializes (dom modification)

We've tried to use a directive for this but this only solves step 2 and 5 (`Directive.update`). We are looking for something like `beforeUpdate` inside the directive to handle 3.

Is there a proper way to handle this?

**Comment by dennisreimann** [comment]
Looks like this [made it into 2.0](https://github.com/vuejs/vue/wiki/2.0-features) 👏
