### ISSUE TITLE
Set a <component> to an already created but unmounted component?

### ISSUE THREAD

**Issue by prawnsalad** [vuejs/vue#3920]
I've gone over the docs, got no response in the chat room or forum so i'm starting to wonder if this is currently not possible.

We can create a dynamic component via `<component v-bind:is="currentView"></component>` and then setting `currentView` to a component. But I can't seem to set `currentView` to an existing component instance.

Example of working and non working here: https://jsfiddle.net/6nyc4zcw/

I have a case in which components need setting up before they are shown by setting its data or calling it's methods.

**Comment by fnlctrl** [comment]
No. `<component>`'s `is` prop only accepts string name or constructor function. You should always avoid manually creating components, and should instead drive them through parent state.

**Comment by prawnsalad** [comment]
Then what would be the best way to handle this case?

I have an app with a <div></div> element which will contain an arbitrary component. The component is not known until runtime and may be anything. I'm currently creating a Vue instance and then calling a function to set it active into that <div> - but how do I go about that?

**Comment by fnlctrl** [comment]
Please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

-----

Just pass the component constructor via prop and then use `<component :is="propName">`.

**Comment by prawnsalad** [comment]
Thanks, I've moved your response to the existing unanswered forum thread: http://forum.vuejs.org/t/how-to-set-component-to-a-created-vue-instance/1298/2

If you have any idea it would be much appreciated!

**Comment by fnlctrl** [comment]
Discussion is continued in the forum thread.
