### ISSUE TITLE
Can't receive event in global child component which event is emit in router beforeEach method.

### ISSUE THREAD

**Issue by lsxiao** [vuejs/vue#3927]
### Vue.js version
2.0.2

### Steps to reproduce

```
router.beforeEach((to, from, next) => {
	bus.$emit('test');
        .......
});
```

### What is Expected?

receive event in child component。

### What is actually happening?

received nothing,because the event is not sticky.when it is emit,the child component may not be created.

**Comment by yyx990803** [comment]
This is expected behavior, you actually explained it yourself.

**Comment by lsxiao** [comment]
any plan to support sticky event in Vue2.0 eventbus?
