### ISSUE TITLE
Duplicate attribute: class in edge and IE

### ISSUE THREAD

**Issue by tdekoning** [vuejs/vue#3929]
### Vue.js version
2.0.2

### Reproduction Link
http://codepen.io/anon/pen/WGyrdz

### Steps to reproduce
Just load up the page in edge or internet explorer (11) with your console open. Vue will display the warning "duplicate attribute: class".
When removing the `class` attribute, the warning goes away.

### What is Expected?
No warnings :). I expect vue to use both the regular `class` attribute and the `:class` attribute and merge them together into the `class` attribute.

**Comment by yyx990803** [comment]
Actually it's IE that messed up outerHTML by duplicating the attribute :(
I've just disabled this warning for IE.

**Comment by tdekoning** [comment]
Thanks!

**Comment by jdalton** [comment]
I'm not able to [repro this](https://jsbin.com/fagusa/1/). In the simplified test case `:class` shows up in the attributes list in IE11 and Edge 14.

**Comment by Kcharle** [comment]
As @jdalton said, this is still an issue in Edge 14.

**Comment by posva** [comment]
@Kcharle Could you open a new issue with a repro, please?  I'm not sure to understand. Does this mean we can remove the check?

**Comment by Yangfan2016** [comment]
I‘m meeting this too
