### ISSUE TITLE
 Vue.transition is not a function in webpack with vue project

### ISSUE THREAD

**Issue by hxfdarling** [vuejs/vue#3938]
import Vue from 'vue';

Vue.comonent('test',{
 template: "<span>test</span>",
}); 
//this is ok,but blow code can not run, I got error " Uncaught TypeError: Vue.transition is not a function"
Vue.transition('fade', {
    css: false,
    enter: function(el, done) {
        $(el)
            .css('opacity', 0)
            .animate({ opacity: 1 }, 1000, done)
    },
    enterCancelled: function(el) {
        $(el).stop();
    },
    leave: function(el, done) {
        $(el).animate({ opacity: 0 }, 1000, done)
    },
    leaveCancelled: function(el) {
        $(el).stop();
    }
});

**Comment by fnlctrl** [comment]
http://vuejs.org/guide/migration.html#Vue-transition-for-Reusable-Transitions-deprecated
