### ISSUE TITLE
why vue 2.0 not working on ios 9.3.5?

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#3939]
it's not render on ios <= 9.3.5 ! ios 10 work fine!

**Comment by yyx990803** [comment]
No reproduction = not important.

**Comment by aviggngyv** [comment]
http://test.ipangdou.com/ this is the test page.

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>联系客服</title>
    <script src="vue.js"></script>
    <script src="vue-resource.js"></script>    
  </head>
  <body>

    <div id="editor">
      <select v-model="selected" @change="getMakerQQ(selected)">
        <option v-for="(maker, index) in maker_list" :value="maker.mid" :class="'maker'+index"> {{ maker.name }}</option>
      </select>
      <a :href="maker_qq_url">联系客服</a>
    </div>

    <script>
      new Vue({
        el: '#editor',
        data: {
          selected: 0,
          maker_list: [],
          maker_qq_url: ''
        },
        mounted: function () {
            this.getMakerList();
        },
        methods: {
          getMakerList: function (e) {
            var vm = this;
            vm.$http.get('http://hunteryun.com/api/maker/list').then((response) => {
              vm.maker_list = response.data;
            }, (response) => {
              alert('获取商家列表失败！');
            });
          },
          getMakerQQ: function (mid) {
            var vm = this;
            vm.$http.get('http://hunteryun.com/api/maker/get/qq/'+mid).then((response) => {
              vm.maker_qq_url = 'mqqwpa://im/chat?chat_type=wpa&uin='+response.data+'&version=1&src_type=web&web_src=oicqzone.com';
            }, (response) => {
              alert('获取商家QQ失败！');
            });
          }
        }
      })
    </script>

  </body>
</html>
`

**Comment by yyx990803** [comment]
I don't have an iOS 9 device at hand. Do you see any errors (you can use https://github.com/WechatFE/vConsole)?

**Comment by aviggngyv** [comment]
yes, I alreay install vConsole on my test page, and I find a error on ios 9
![qq 20161014111813](https://cloud.githubusercontent.com/assets/7891096/19374669/0ddd28e0-9200-11e6-887d-8986c1949dcd.png)

**Comment by ivanberry** [comment]
看起来是语法错误？

On Oct 14, 2016 11:20, "aviggngyv" <notifications@github.com> wrote:
>
> yes, I alreay install vConsole on my test page, and I find a error on ios
9

**Comment by yyx990803** [comment]
Does reverting to 2.0.2 work?

**Comment by yyx990803** [comment]
... I think it's not about Vue, you are using arrow functions which are not supported in iOS 9.3...

**Comment by vorthess** [comment]
Bump, I have problem that on ios <9.3.5 safari CRASHES after page load with lots of html rendered... Depending on device, faster doesn't crash while iPod f.e does even with small markup. 

Anything? I can't reproduce, it's commercial project...

**Comment by vorthess** [comment]
I managed to fix iPad problem by initing vue in DOMContentLoaded callback... However slow 2014 ipod crashes anyway

**Comment by arma7x** [comment]
Happen to me too, using vuejs 2.2.6. Not render on ios<=9.3, but works on ios>=10. Testing on iphone using appetize.io

**Comment by arma7x** [comment]
Happen to me too, using vuejs 2.2.6. Not render on ios<=9.3, but works on ios>=10. Testing on iphone using appetize.io

**Comment by arma7x** [comment]
Happen to me too, using vuejs 2.2.6. Not render on ios<=9.3, but works on ios>=10. Testing on iphone using appetize.io

**Comment by LinusBorg** [comment]
Guys, 'm sorry to say this, but saying "it happens to me too" without any further information, let alone code to analyse, does not enable us to help you in any way.
