### ISSUE TITLE
Vue 2.0.3 packages version mismatch

### ISSUE THREAD

**Issue by solarhell** [vuejs/vue#3941]
### Vue.js version
2.0.3

### Reproduction Link
[My app](https://solarhell.github.io)
[CI log](https://travis-ci.org/solarhell/solarhell.github.io)

The app's console says that `Uncaught Error: Cannot find module "../components/List.vue"(…)`

When i use CI to build my app, the bug happens, and the CI log shows that 
```
Vue packages version mismatch:
- vue@2.0.3
- vue-template-compiler@2.0.2
```
FYI,i used `vue-cli` and `webpack` template to create my app.
And i have reinstalled the `vue-loader`.
The weird thing is that when i use `npm run dev`, it works well.

**Comment by yyx990803** [comment]
Re-install vue-loader.

**Comment by solarhell** [comment]
Re-install `vue-loader` still can't work.
I switched to `vue@2.0.2` and it works now.

**Comment by yyx990803** [comment]
Are you using `yarn` with lock? This is likely either your npm registry not being up to date or you're not explicitly upgrading `vue-loader`.

**Comment by fiveanddone** [comment]
`npm update vue`

Fixed it for me

**Comment by ryanweal** [comment]
I was following the official "getting started" guide and I couldn't even get a hello world up until I saw the previous comment. I was following the "CLI method" here: https://vuejs.org/v2/guide/installation.html

**Comment by lbineau** [comment]
Same issue for me I've just upgraded a project that have been generated by vue-cli few months ago.
The problem is maybe because it is declared as peerDependencies in vue-loader?
https://github.com/vuejs/vue-loader/blob/master/package.json#L47

My solution (may be not the right one) is to add the library manually in the generated project 
```json
"devDependencies": {

    "vue-template-compiler": "^2.1.8",

}
```

**Comment by gdomiciano** [comment]
I've removed my **node_modules** folder and executed `npm install` .

**Comment by rodwin** [comment]
In my case, I am using laravel mix and like @gdomiciano, I've removed the node_modules and run `npm install`

**Comment by thulioph** [comment]
```
$ rm -rf node_module
$ npm install
```

**Comment by Juice007** [comment]
```
weex xbind repair toolkit-repair
weex repair
```
you can try this , it works for me

**Comment by eblanshey** [comment]
I was using Laravel Mix which has a dependency on an older `vue-template-compiler`, and somehow the lock file wasn't consistent. I updated Laravel Mix and the lock file fixed itself, and the error disappeared.

**Comment by GeetHoobs** [comment]
`npm update vue-template-compiler` solved my problem, or you can try to re-install it

**Comment by warren32** [comment]
`npm uninstall vue-template-compiler` 
`npm install vue-template-compiler`
 worked for me

**Comment by juanvillegas** [comment]
I did what @gdomiciano suggested, but probably @warren32 's would also work and much faster.

**Comment by wagnlinzh** [comment]
`vue-template-compiler` and `vue` should be the same version  (for me)

**Comment by var23rav** [comment]
vue-template-compiler and vue should be same, true..
Should't `npm install vue-template-compiler` do a check on available **vue** js version.
And install the correct same version !

**Comment by MrTinyByte** [comment]
**yarn** installation has a problem, although I specified the _exact version_, yarn seems to install latest version of **vue-template-compiler** for me!
I cleared yarn's cache and removed the node_modules folder, but no luck.

After all that, `npm install` got the job done!

**Comment by jezzdk** [comment]
Lots of great comments here. If you have a few minutes, or just want everything to work, do this (worked for me at least):

1. Remove `node_modules` folder
2. Delete `package-lock.json`
3. Delete `yarn.lock`
4. Run `yarn`
5. Profit

**Comment by mhimi1** [comment]
reinstalling vue-loader did it for me.

**Comment by bhattaru** [comment]
npm uninstall vue-template-compiler
npm install vue-template-compiler
worked for me

**Comment by imsnif** [comment]
Hi friends - just FYI: this issue could also happen if you're using a mirror of npm. (eg. when the mirror has an updated version of one package and not of the other). The solution then (IMO, of course) would be to either update the mirror or lock both versions.

**Comment by MaG21** [comment]
```bash
# one may not need -g, in my case I was installing vue/cli globally.
npm install -g vue
npm install -g vue-template-compiler
```

**Comment by webblufter** [comment]
> In my case the problem was a version mismatch with `vue` and `vue-template-compiler`. Fixed by upgrading both packages, so now they both have the same version.
> 
> ```shell
> # one may not need -g, in my case I was installing vue/cli globally.
> npm install -g vue
> npm install -g vue-template-compiler
> ```

**Faceing issue for Vue and Vue-template-compiler mismatch**
THIS SOLUTION SOLVED MY PROBLEM

**Comment by karsa87** [comment]
> In my case the problem was a version mismatch with `vue` and `vue-template-compiler`. Fixed by upgrading both packages, so now they both have the same version.
> 
> ```shell
> # one may not need -g, in my case I was installing vue/cli globally.
> npm install -g vue
> npm install -g vue-template-compiler
> ```

It work for me 
Thank you

**Comment by Etienereum** [comment]
I navigated to the `/vue `directory and the `/dist` directory. This worked for me.

`/usr/local/lib/node_modules/vue/dist`

**Comment by hasyjay** [comment]
> In my case the problem was a version mismatch with `vue` and `vue-template-compiler`. Fixed by upgrading both packages, so now they both have the same version.
> 
> ```shell
> # one may not need -g, in my case I was installing vue/cli globally.
> npm install -g vue
> npm install -g vue-template-compiler
> ```

works like charm.....thanks champ

**Comment by asynccallbackalfonso61** [comment]
@yyx990803 +1
