### ISSUE TITLE
[2.0] nextTick don't guarantee this.$el in in-document

### ISSUE THREAD

**Issue by imcvampire** [vuejs/vue#3945]
### Vue.js version
2.0.3

### Steps to reproduce
I try to use this but Chrome logs an error `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`:
```
mounted() {
   this.$nextTick(() => {
       this.calendarHeight = this.$el.querySelector('.calendar').getBoundingClientRect().height 
   })
}

```

**Comment by defcc** [comment]
You could add a jsfiddler to provide more context.

**Comment by yyx990803** [comment]
This doesn't seem to be related to wether it's in-document or not: the query for `.calender` returned `undefined` (shouldn't it be `null`?).

If `.calendar` should be rendered in the component's template but is not there when the component is mounted, then this is a bug; however this seems highly unlikely so a repro is needed.

**Comment by imcvampire** [comment]
I will try my best to repro this because I face this problem when working in a private repo.
