### ISSUE TITLE
Inherit/Bind all props from parent

### ISSUE THREAD

**Issue by znck** [vuejs/vue#3946]
Allow child component to auto inherit props from its parent.

``` html
<!-- ComponentA.vue -->
<template>
  <div>{{ hello }}</div>
</template>

<script> 
export default {
  props: {
    hello: String,
  },
};
</script>
```

``` html
<!-- ComponentB.vue -->
<template>
  <div>
    <component-a></component-a> World!
    <!-- or -->
    <component-a v-props></component-a> World!
  </div>
</template>

<script> 
import ComponentA from './ComponentA.vue';

export default {
  props: { ...ComponentA.props },
  components: { ComponentA },
};
</script>
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Inheriting everything is an anti-pattern, and had been removed from Vue long ago, so please declare the props specifically.

**Comment by znck** [comment]
Totally agree with that.

BTW how about something like this?
``` html
<template>
   <component-a props="{ title, show, other }"></component-a>
   <!-- instead of -->
   <component-a :title=title :show=show :other=other></component-a>
</template>
```

**Comment by fnlctrl** [comment]
You can use v-bind ;)
```html
<component-a v-bind="{ title: title, show: show, other: other }"></component-a>
```

And if you're sure your target browser supports [object literal extensions](http://kangax.github.io/compat-table/es6/#test-object_literal_extensions)
It can be simplified to
```html
<component-a v-bind="{ title, show, other }"></component-a>
```

**Comment by dotBits** [comment]
You can do even better with
```javascript
<component-a :cprop="computed" v-bind="this.$props"></component-a>
```
component-a will receive only its own props even if this.$props contains other props which the child is not interested in, they will be filtered.
By doing so, if you have a computed property, you have to specify the watcher (see cprop)
