### ISSUE TITLE
runtime-only build from CDN contain references to process.env.NODE_ENV - offer alternative build?

### ISSUE THREAD

**Issue by NicolasParada** [vuejs/vue#3948]
I'm bundling my code only  and using Vue from [unpkg](https://unpkg.com/).
But even if I'm not using the `template` option, I'm forced to use the standalone build because the runtime-only one has some node variables, like `process` or `module`.

> Uncaught ReferenceError: process is not defined

**Comment by fnlctrl** [comment]
Why would you want to use the runtime-only build inside browsers? 
Are you sure you don't need template/jsx compilation and write all render functions by hand?

**Comment by NicolasParada** [comment]
I have my build system configured with support for `.vue` files and `jsx`, and the both of them don't use the `template` option.

**Comment by fnlctrl** [comment]
Since you have a build system, why not just use runtime-only build with it, instead of loading vue separately in browser?

**Comment by NicolasParada** [comment]
I just don't want one single big bundled file. It would be better if I just load frameworks and libraries separately from my code.
In webpack there is CommonsChunkPlugin, but I'm using Rollup here :/

**Comment by LinusBorg** [comment]
add a  script tag that adds process.env. to the global namespace:

**Comment by posva** [comment]
I think the runtime only is meant to be used with a bundler. If you're using rollup you can use https://github.com/rollup/rollup-plugin-replace

**Comment by NicolasParada** [comment]
@LinusBorg `module.exports` gave problemas too...
@posva Yeah, there is a couple of solutions, but... there could be a CDN script that offer the runtime-only build for browsers.

**Comment by posva** [comment]
@NicolasParada They're automatically added to CDNs so it's normal for some of them not to be browser ready and/or without a minified version

**Comment by thbar** [comment]
I wanted to start using the CDN version of vue inside a Rails app today and met the same issue. Building upon @LinusBorg & @NicolasParada input, here is the version that works for me: 

```javascript
<script type="text/javascript">
  window.process = { env: { NODE_ENV: 'production' } };
  window.module = {};
</script>
```

I wonder if there's a version hosted somewhere which can be used without any tweak?

**Comment by yyx990803** [comment]
When next release is out you can use the UMD runtime build via https://unpkg.com/vue/dist/vue.runtime.js

**Comment by lizidashen** [comment]
when I change vue.common.js to vue.min.js,problem solved.however,I still don't understand why.
