### ISSUE TITLE
using `:something-attribute` on element and using it with Vue makes element disappear from DOM and no errors in console.

### ISSUE THREAD

**Issue by tttomat19** [vuejs/vue#3949]
version with vue.min.js 2.0.3 https://jsfiddle.net/gjqttao8/1/ 
vue library: https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.3/vue.min.js

based on recommended template:
http://jsfiddle.net/df4Lnuw6/3/

working ok with vue 1.0.26
http://jsfiddle.net/df4Lnuw6/6/

using `:something-attribute` on element and using it with Vue makes element disappear from DOM and no errors in console.

**Comment by fnlctrl** [comment]
Your example wasn't using valid syntax.
Corrected: http://jsfiddle.net/df4Lnuw6/9/

And I did get errors:
![1](https://cloud.githubusercontent.com/assets/5557143/19399519/76a8104a-9284-11e6-9979-220035338c4a.png)
Don't know what really happened on your side.
