### ISSUE TITLE
Installation docs link to 2.0.1 version

### ISSUE THREAD

**Issue by iabdulin** [vuejs/vue#3952]
Here:
https://vuejs.org/guide/installation.html

![image](https://cloud.githubusercontent.com/assets/622315/19406917/c48102c2-924d-11e6-85de-369b82266914.png)

**Comment by defcc** [comment]
Thanks so much @iabdulin . 

This is an issue with [vuejs.org](https://github.com/vuejs/vuejs.org/issues).  You could report it there, or just make a PR to fix it.

**Comment by defcc** [comment]
@iabdulin problem fixed.
