### ISSUE TITLE
1.x $compile() to 2.x?

### ISSUE THREAD

**Issue by reefki** [vuejs/vue#3954]
Sorry to ask this question here, I've asked on Gitter and VueJS forum but didn't receive answer at all, I am really stuck! Feel free to close if you thinks I am asked in wrong place.

I'm currently using 1.x and trying to migrate to 2.x, for some technical reason some of my components are loaded and inserted dynamically then I'm call `this.$compile()` so that inserted components can be rendered correctly. I notice there is `Vue.compile()` in 2.x but looks like it doesn't help.

1.x: https://jsfiddle.net/reefki/cdzqLscg/
2.x: https://jsfiddle.net/reefki/Lv3uaexg/

Thanks

**Comment by fnlctrl** [comment]
There you go:
https://jsfiddle.net/fnlCtrl/fmqzu1w1/

Note that this method should work in both 1.x and 2.x(standalone build)
