### ISSUE TITLE
Problem in updating an array with key binding to element

### ISSUE THREAD

**Issue by David-Desmaisons** [vuejs/vue#3955]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/dede89/rq049kpp/

### Steps to reproduce

Click on change button to update the array.

### What is Expected?
The dom should update and display "James" and "Bill"

### What is actually happening?
Only "James" is displayed. The following warning is logged on the console:

[Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.

And then an exception is the raised:
Uncaught (in promise) TypeError: Cannot read property 'tag' of undefined(…) lign 4044

**Comment by ktsn** [comment]
You passes objects to `key` attribute and it stringify to `[object Object]`, then the keys are duplicated.
Just pass `element.id`
