### ISSUE TITLE
how to do local-registration with data in vue?data must be function?

### ISSUE THREAD

**Issue by matisha001** [vuejs/vue#3960]

**Comment by matisha001** [comment]
![image](https://cloud.githubusercontent.com/assets/19816700/19424684/c926806a-945d-11e6-9a0b-c025c1158f18.png)

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
