### ISSUE TITLE
[feature request] Add 'max-stack' in component 'keep-alive'

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vue#3961]
like this:

``` html
<keep-alive :max-stack='10'>
    ....
</keep-alive>
```

vue will only cache 10 switched-out components

**Comment by posva** [comment]
When does this come in handy? @fnlctrl

**Comment by fnlctrl** [comment]
Things like an infinite list/virtual scroll, where there could be many many
detached but kept-alive components.

**Comment by yyx990803** [comment]
This seems to have little traction and the virtual list use case is imo not what `<keep-alive>` was designed for. Also cached components can already be to some extent controlled via the `include` and `exclude` props.
