### ISSUE TITLE
watched input have the same old value as new value

### ISSUE THREAD

**Issue by NidhoggC** [vuejs/vue#3962]
### Vue.js version
1.0.28

### Reproduction Link
https://jsfiddle.net/jhmkedt4/2/

### Steps to reproduce
Just  write something in input and watch the console
### What is Expected?
The new value and the old value should be different
### What is actually happening?
The new value and the old value are same

**Comment by fnlctrl** [comment]
You are watching an object that's been mutated, so the newVal and oldVal both point to the original object.
In your case, you should watch `a.b` instead. https://jsfiddle.net/fnlCtrl/zseq7gk5/

**Comment by NidhoggC** [comment]
i have update this demo https://jsfiddle.net/jhmkedt4/5/
when the object  'a' has dynamic keys ,there will be problem

**Comment by fnlctrl** [comment]
Then use the `this.$watch('a.dynamicKey')` approach whenever the dynamic key changes, (and also don't forget to unwatch the old one)
