### ISSUE TITLE
Slog component not working in render function.

### ISSUE THREAD

**Issue by towry** [vuejs/vue#3970]
### Vue.js version
2.0.2

I have followed this [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx) to using JSX in my project, everything goes well except that I can not get the `slot` component working if I use it in `render` function.

Here is my code.

Child component:

```jsx
// image-preview.jsx
export default Vue.extend({
	mounted() {
		console.log(this);
	},
        // If i only use template here, it will work.
	// template: '<div class="test"><p>hi</p><slot></slot></div>'

	render(h) {
		return (
			<div class="test">
				<p>hi</p>
				<slot></slot>
			</div>
		)
	}
})
```

Parent component/app:

```jsx
import ImagePreview from './image-preview.jsx';

new Vue({
	el: '.app',

	components: {
		ImagePreview
	},

	render(h) {
		return (
			<div>
				<image-preview>
					<h1>hello</h1>
					<img src="http://res.cloudinary.com/towry/image/upload/v1476760890/sample.jpg" alt="" />
				</image-preview>
			</div>
		)
	}
})
```

If I inspect the element with devTool, it's just a `<slot></slot>` element.

**Comment by xuanyan0x7c7** [comment]
use `this.$slots.default`

**Comment by towry** [comment]
@xuanyan0x7c7 Thanks.

I changed it to:

```jsx
return (
	<span class="test">{ this.$slots.default }</span>
);
```

Now it works.
