### ISSUE TITLE
Inline-template Issues from http://vuejs.org/guide/components.html#Inline-Templates

### ISSUE THREAD

**Issue by matisha001** [vuejs/vue#3981]
![image](https://cloud.githubusercontent.com/assets/19816700/19506385/b42a4704-95fd-11e6-8cfd-a1e998f57926.png)
Inline-template components must have exactly one child element. 
![image](https://cloud.githubusercontent.com/assets/19816700/19506371/91e76258-95fd-11e6-836c-f4384e4967b6.png)

**Comment by matisha001** [comment]
This issue is in vuejs2.0

**Comment by defcc** [comment]
Thanks for your reporting @matisha001 .  This should be an issue of [vuejs/vuejs.org](https://github.com/vuejs/vuejs.org/issues)

We will update the document as soon as possible.
