### ISSUE TITLE
$on $emit in component not work

### ISSUE THREAD

**Issue by Shmasya** [vuejs/vue#3982]
How create events for my component? I created Vue and component. This code work. 
```
var App = new Vue({
	el: '#app',
	components: {
		'vue-calendar': VueCalendar,
		'vue-cart': VueCart
	}
});
```
and i create component
```
var VueCart = Vue.extend({
	template: '#template-vue-cart',
	created: function() {
		this.$on('test', function() { console.log('Work'); });
	}
});
```
and i trying call this event from jquery:
```
$('.add-product').click(function(e) {
	e.preventDefault();
	VueCart.$emit('test');
});
```
But this not work. This work with App only :(

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
