### ISSUE TITLE
Can not use 'key' as prop name of a component

### ISSUE THREAD

**Issue by NemoAlex** [vuejs/vue#3984]
### Vue.js version
2.0.3

### Reproduction Link
http://codepen.io/nemoalex/pen/PGxoGG

### Steps to reproduce
As the sample

### What is Expected?
this.key === 'key'

### What is actually happening?
this.key === undefined

Vue 1.0 has no problem with it:
http://codepen.io/nemoalex/pen/VKVwZk

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
`key` is the 2.0 counterpart of `track-by` in 1.0, so it is reserved and cannot be used as prop name.
