### ISSUE TITLE
Some problem with a custom directive's update callback

### ISSUE THREAD

**Issue by NidhoggC** [vuejs/vue#3985]
### Vue.js version

1.0.28
### Reproduction Link

https://jsfiddle.net/pamkLc21/3/
### Steps to reproduce

just write something  in input and watch the  console
### What is Expected?

'update'function should be excuted when i change the input value
### What is actually happening?

'update'function cannot be excuted when i change the input value

**Comment by defcc** [comment]
The update function seems to be invoked actually. What browser and OS are you using?

**Comment by NidhoggC** [comment]
chrome 53.0   OS X10.11

**Comment by LinusBorg** [comment]
Works on Chrome 53 Windows.

Have you tested this in an incgnito window, to ensure that no exptensions or sth. interfer?

**Comment by NidhoggC** [comment]
I test in an incgnito window  and chrome on windows,still doesn't  work. maybe some one can give me a demo that how to invoke custome directive's update callback? XD

**Comment by yyx990803** [comment]
The update hook doesn't get triggered when you call `this.set` in a custom directive, otherwise it would end up in an infinite loop. It only triggers when the value is programmatically changed in your app code.
