### ISSUE TITLE
Strange component communication

### ISSUE THREAD

**Issue by amigo** [vuejs/vue#3987]
In Vue 2.0  with data object without defined property. "fail" property receive event when another component triggered event.

Step to reproduce:
1. Type into "fail" field.
2. Type into "success" field.

https://jsfiddle.net/s5tmh6uv/

Vue 1.0 has fine reaction, but "success" field doesn't receive "text" property.

https://jsfiddle.net/wn8pau5v/

**Comment by vinicius73** [comment]
This is intencional @amigo 
#3567

**Comment by fnlctrl** [comment]
As explained by @vinicius73 .
>  this is required in 2.0 - v-model no longer implicit create non-existent paths for you. This is an intentional decision
