### ISSUE TITLE
Vue2.03, can ignore [ v-model='' ]?

### ISSUE THREAD

**Issue by liufajian** [vuejs/vue#3989]
### Vue.js version
2.0.3

### Reproduction Link

https://jsfiddle.net/lummon/rwagaqw5/

when v-model='', if use vue.js, chrome console will output " vue.js:2611 [Vue warn]: failed to compile template", but if use vue.min.js, there is not any information outputed to console , but empty webpage.

### What is Expected?

ignore this case , dont compile it.  like v-on:click="", this does not cause any problem

**Comment by phanan** [comment]
Firstly, you should always use development version when, duh, develop, so the error is pretty much obvious. Secondly, I do think writing `v-on:click=""` is not much different from `el.addEventListener("click", )`, which is a syntax error, and silently ignoring errors is just not a good idea.

**Comment by fnlctrl** [comment]
^ As explained by @phanan
