### ISSUE TITLE
Vue 2.0 v-bind:class   not work

### ISSUE THREAD

**Issue by aeolusheath** [vuejs/vue#3990]
render div  the class binding  has something wrong

```html
    <div class="group-container tag">
      <div v-bind:class="'group-title ' + false ? '': 'clear-border'">
            title content
      </div>
   </div>
```

but result in the chrome is like this:

```
    <div class="group-container tag">
      <div >
            title content
      </div>
   </div>
```
the child div  should be  

```
      <div class="group-title clear-border">
            title content
      </div>
```

anyone help?

**Comment by phanan** [comment]
Have you tried evaluating the expression in Chrome console?

![image](https://cloud.githubusercontent.com/assets/8056274/19544787/0cebe0d0-96b4-11e6-9b48-4272c228f577.png)

Please use [the forum](http://forum.vuejs.org) for such questions.

**Comment by aeolusheath** [comment]
@phanan  oops ,sorry . it's my own fault
