### ISSUE TITLE
Vue.js v1.0.26 【v-if】

### ISSUE THREAD

**Issue by lgc** [vuejs/vue#3991]
### Vue.js version
1.0.26

### Reproduction Link

https://jsfiddle.net/garvinlgc/opxcad19/4/

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
