### ISSUE TITLE
Dom rendering the first time will flashing when i use v-if and v-show with v-cloak

### ISSUE THREAD

**Issue by 327326724** [vuejs/vue#3993]
`<div v-show="isShow"  v-cloak>一些内容</div>`

`<style>`
     `[v-cloak] { display: none }`
`</style>`

Vue.js v1.0.28

how to use it correctly?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
