### ISSUE TITLE
Do events on components bubble up to parent?

### ISSUE THREAD

**Issue by znck** [vuejs/vue#3994]
``` vue
// In ComponentA.vue
<component-b @some-event="foo"></component-b>

// In ComponentB.vue
<component-c> ... </component-c>

// In ComponentC.vue
<div @click="$emit('some-event')"></div>
```

**Comment by fnlctrl** [comment]
No. You'll have to re-emit it in ComponentB.

**Comment by znck** [comment]
Is it possible to do something like `v-on="{ click: foo, 'some-event': bar }"`

**Comment by fnlctrl** [comment]
Please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!

-------

Not possible with templates. You can use [render functions](http://vuejs.org/guide/render-function.html#The-Data-Object-In-Depth) for this.
