### ISSUE TITLE
vue2 template v-for="item in items" 不能全部渲染信息

### ISSUE THREAD

**Issue by tangtanglove** [vuejs/vue#3995]
<template v-for="item in items">
			            <div class="app-box middle" title="{{item.title}}" @dblclick="openapp(item.name)" name="{{item.name}}">
			                <span class="app-icon">
			                    <img src="{{item.icon}}" onerror=alert('xxx') alt="{{item.title}}" class="img-rounded">
			                </span>
			                <span class="app-name">{{item.title}}</span>
			                <div class="clear"></div>
			            </div>
 </template>

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
