### ISSUE TITLE
Overwriting "style" attribute [Vue 2.0]

### ISSUE THREAD

**Issue by rstoenescu** [vuejs/vue#3997]
Hello,

With Vue 1 "style" attribute is "merged", but with Vue 2 it is completely overwritten. Is this by design?

In the following jsfiddle, if you remove "style" attribute it will then apply "style" from within component definition. As long as "style" is present on "<my-car>" (from main HTML window), it will completely overwrite component's style:
https://jsfiddle.net/rstoenescu/t0kb6vyu/2/

Thanks!

**Comment by LinusBorg** [comment]
If you define a static attribute, Vue will not attempt to dynamically merge it.

If you provide a binding, Vue will do that:

https://jsfiddle.net/t0kb6vyu/3/

**Comment by rstoenescu** [comment]
Ok, nice to know. But Vue 1 did merge regardless of static or dynamic attribute. It would be nice if this behavior can be continued with Vue 2 as this is quite important when writing libraries/frameworks with Vue 2. I can elaborate if needed. Just my thoughts. Thanks for the answer!

**Comment by LinusBorg** [comment]
Yeah we will look into that, sure!

**Comment by defcc** [comment]
Like class module, I think **style** should also have the same behavior for consistency. I'll try to make a PR.

**Comment by yyx990803** [comment]
@defcc yeah, probably need to treat `staticStyle` and `style` separately, and need to parse static style strings into objects.

**Comment by defcc** [comment]
OK, I'll take a look :)

**Comment by defcc** [comment]
Almost done. I'll make a PR later.

**Comment by rhyek** [comment]
Will this change merge styles in this case?
```html
<text-element style="color: red;"/>
```
*text-element.vue*
```js
<script>
  export default {
    render(createElement) {
      return createElement('input', {
        attrs: {
          type: 'text',
          style: 'text-align: right;'
        }
      });
    }
  };
</script>
```
