### ISSUE TITLE
$index is not defined

### ISSUE THREAD

**Issue by jarodrigues** [vuejs/vue#3998]
Someone help?
$index is not defined
.................................................. Code
<a href="#" v-on:click="removeElement($event, $index)" class="btn btn-primary tbn-sx">X</a>

methods: {
        removeElement: function (e, index) {
            e.preventDefault();
            this.elements.splice(index, 1);
        }
}

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Check this: http://vuejs.org/guide/migration.html#v-for-Argument-Order-for-Arrays

**Comment by jarodrigues** [comment]
Sorry man, i did not know. My first post. 
But i do know the problem, my version of vue is 2.0

**Comment by wf123537200** [comment]
are u use v-for like this `<div v-for="it in xx">{{$index}}</div>`?

**Comment by abdullah** [comment]
@jarodrigues 
Did you check `key` property  ?  https://vuejs.org/guide/list.html#key

**Comment by JWplanet** [comment]
$index was removed at Vue@2.0. 
If you want to use $index, you should change the vue version 2.0 to 1.x

**Comment by wf123537200** [comment]
@jarodrigues 2.0 can simple change the code like <div v-for="(it, index) in xx">{{index}}</div>
