### ISSUE TITLE
Local components inheritance

### ISSUE THREAD

**Issue by terion-name** [vuejs/vue#3999]
This topic was discussed a long time ago in #1297, but I want to return to it, because I think many developers will benefit of this feature.

We all try to make apps as modular as possible. Moreover, component approach forces us to make many simple, mostly stateless, components. All these components are set in tree-like hierarchy, that often leads to situation, when some set of components is used in only one branch of this tree. In this case registering components globally is a bad thing, obviously — we should register them globally only if they are truly global, if they are used all over the app. On the other hand registering them locally will lead to code overbloat and repeatings, that rises possibility of errors and makes app support harder.

I'll show a real example, an app I am currently working on (but there are many other cases). structure is cutted just to illustrate the case

```
app
|-blog
|-projects-registry
|-presentation-builder
|-|-menu
|-|-previews
|-|-|-slides-templates
|-|-editor
|-|-|-slides-templates
```

So in an app there is a `presentation-builder` that can be considered a a sort of sub-application (it's a thing like keynote or powerpoint). It consists of various components, but the key here are `slides-templates`, that are used only in builder, but in various sub-components (in `previews`, `editor` and more). There are lots (tens) o templates, but they are never used outside the builder.

Obviously, it is not good to register them globally. It's also obviously that repeated local registration of 10—20—30 components in many places is horrible. 

Yes, probably I could collect these components in a single file, that will export an object with them and require this file in several places. With es6 object destruction this can work not bad. In fact, that's the way I am forced to do it now:

``` js
// components/slides/index.js
export default {
    'slide-idea': require('./slide-idea.vue'),
    //....
}
```

``` html
// editor.vue
...
<script>
  export default {
    components: {
      ...require('../../components/slides').default
    },
   //...
</script>
```

But I really don't think that it is a proper solution, it's more like a hack and this will not work in more granular cases.

I also don't think that local components inheritance will break dependency tree's lucidity, especially with vue inspector that could tip you where this component came from.

Maybe this type of components should b registered in other property, not in `components`, but in something like `globalComponents` or `sharedComponents`, this is a thing to think of, but I suggest that this feature will make life easier in many scenarios.

**Comment by posva** [comment]
Just to make sure, would this be a correct TLDR; ?

> Importing individual components in a large application becomes troublesome and registering them globally may break things. Components defined on a Parent Component should be available from its children components.

**Comment by terion-name** [comment]
@posva well, yes. Maybe even "Component should be **optionally** available from its children components"

**Comment by posva** [comment]
@terion-name Sorry, I had this on hold. I think it's a nice idea. It needs further discussion, though. Let me discuss this with the team and come back with some proposals. IMO having custom `*components` properties is not ideal. I'd rather have this as the default behaviour for the components properties: components being able to use declared components on parent components.

**Comment by yyx990803** [comment]
This was the behavior in a very early version (0.x) but changed to what it is now. The general rule of thumb is:

> You should be able to locate the child components used in a component by looking at that component's code.

Implicitly inheriting components, no matter how it is done, **does** break dependency tree's lucidity, in that when you look at a component's code, you cannot be sure where the child component it used came from.

Explicitly importing child components sure leads to repetition. But in my opinion, contrary to your argument that it "rises possibility of errors and makes app support harder", it makes your code more robust and easier to read/follow/maintain. In fact, your approach of collecting components in a single file is a good middleground and is what I would probably do if I run into similar situations.

**Comment by hpsoar** [comment]
Hello, I think this limitation limited a good design pattern.

I have a relatively universal Layout component, but the content is configurable by the components that use the Layout component, eg. component A use Layout and want to configure its content with component B, some other component may use Layout and configure its content with component C, etc.

Should this pattern be supported?

Or is there any solution to replace this design?
