### ISSUE TITLE
list rendering with v-html doesn't work well

### ISSUE THREAD

**Issue by farzher** [vuejs/vue#4000]
The html elements always get replaced.
http://stackoverflow.com/questions/40151014/vuejs-2-v-for-key-not-working-html-being-replaced

Is this working as intended?
Does anyone know a workaround that'll allow me to stay on v2 instead of going back to v1?

(I have external plugins return arbitrary html to be rendered in my list. A good example is embedded youtube videos that are unwatchable because they keep getting replaced)

**Comment by phanan** [comment]
It works as intended. The "data" (which are essentially HTML in your case) are re-evaluated and patched into DOM, causing your elements to be replaced. A workaround might be as simple as not turning your returned HTML reactive data. This is one of those edge cases where directly manipulating HTML might be  preferred.

Btw, please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this.

**Comment by farzher** [comment]
? I can't "directly manipulate html", it's an arbitrary html string being given to me by some plugin

I tried Gitter and stackoverflow before coming here.
Gitter wasn't very helpful
stackoverflow eventually solved it though with an `<unknown-html>` component. For anyone else having this issue checkout the stackoverflow I linked
