### ISSUE TITLE
Vue Router (router-link) does not update properly if using tag

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue#4001]
### Vue.js version
vue@^2.0.1:
  version "2.0.3"
  
vuex@^2.0.0:
  version "2.0.0"

vue-router@^2.0.0:
  version "2.0.1"

### Reproduction Link
https://jsfiddle.net/b40xckws/

### Steps to reproduce
Hover over link : you should see 

https://fiddle.jshell.net/site/1

click on button

you will see the that the site id has changed but the link does not

### What is Expected?

You should click the button and see 

https://fiddle.jshell.net/site/4

### What is actually happening?

You see https://fiddle.jshell.net/site/1

## how to fix 
Remove tag on` router-link`
https://jsfiddle.net/vLvvjk2p/

**Comment by LinusBorg** [comment]
I took the freedom to make your example readable:

https://jsfiddle.net/Linusborg/b40xckws/2/

**Comment by LinusBorg** [comment]
This is the wrong repository, please open it in the vue-router repository.

Thanks.

**Comment by lukepolo** [comment]
@LinusBorg thanks, ill do that ~

**Comment by lukepolo** [comment]
@LinusBorg should we repopen this one per response of : vuejs/vue-router#810
