### ISSUE TITLE
a problem when i type in the console

### ISSUE THREAD

**Issue by QuoniamYIF** [vuejs/vue#4004]
document: https://vuejs.org/guide/index.html

there is such a description in the document:

> How do we know? Just open up your browser’s JavaScript console and set app.message to a different value. You should see the rendered example above update accordingly.

this is my code.
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="css/style.css" rel="stylesheet"> -->
</head>

<body>
    <div id="app">
      {{ message }}
    </div>

    <script src="../jquery.js"></script>
    <script src="../vue.js"></script>
    <!-- <script src="../myvue.js"></script> -->
    <script>

      var app = new Vue({
        el: "#app",
        data: {
          message: "Hello, World!"
        }
      });

    </script>
</body>

</html>
```

but why is the value of `app.message` is `undefined`?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
