### ISSUE TITLE
Using class names instead of attributes would make scoped styles faster

### ISSUE THREAD

**Issue by esprehn** [vuejs/vue#4013]
### Vue.js version
2.0.2

Vue per the docs is using a generated attribute names for scoped styles, for example it turns &lt;style scoped&gt; selectors from .a:hover into .a[vue-1]:hover. Matching and tracking the invalidation of attribute selectors is slow though, and you'd get much better RecalcStyle (see Chrome devtools timeline) performance if you use a generated class name like .a.vue-scope-1:hover {}

**Comment by fnlctrl** [comment]
Scoped style isn't vue's feature, please open an issue in the [vue-loader](https://github.com/vuejs/vue-loader) repo instead, thanks!
