### ISSUE TITLE
Allow css variable in style binding (object syntax)

### ISSUE THREAD

**Issue by vbrajon** [vuejs/vue#4017]
I am not sure if this is intentional, I would like to be able to do:

`<div :style="{ '--color': player.color }">…</div>`

instead of:

`<div :style="'--color :' + player.color">…</div>`

I was able to find the workaround quickly thanks to the doc search here: http://vuejs.org/guide/migration.html#v-bind-style-with-Object-Syntax-and-important-deprecated

It's a bit different from !important so I would like to push for this feature.

Thanks a lot for your good work, I can work on a PR if you agree with this proposition.

**Comment by defcc** [comment]
**--color** ?  this is not a valid css property name

**Comment by phanan** [comment]
@defcc `--color` is a CSS3 variable syntax.

**Comment by phanan** [comment]
I'm not sure if this should be supported – the current style binding only supports CSS properties. Reopening this, however, so that @yyx990803 and other members can chime in with their ideas.

**Comment by defcc** [comment]
My mistake. Then this should be a bug.

**Comment by tsteuwer** [comment]
@phanan I believe the correct syntax is ``var(--color)`` and it's css4 not 3.

**Comment by phanan** [comment]
AFAIK `var(--color)` is the usage, `--color: #fff` is the definition syntax. I'm not sure about 4vs3, but it shouldn't affect our main issue here anyway.

**Comment by yyx990803** [comment]
Fixed in 4b8eb75
