### ISSUE TITLE
Vue is not work by use “<iframe>” 

### ISSUE THREAD

**Issue by K-walker** [vuejs/vue#4019]
My code is as follows：
`<body>`
    `<div class="main">`
        `<span>{{message}}</span>`
    `</div>`
    `<div class="common-pop-box" v-if="showPop">`
        `<iframe width="100%" height="100%" frameborder="0" />`
   ` </div>`
`</body>`
`<script>`
   ` new Vue({`
       ` el: ".main" ,`
       ` data:{`
            `message:"hello world",`
           ` showPop:true`
     `   }`
   ` })`
`</script>`
Because I used the iframe tag,The value of the span tag is not turned into “hello world” .
where is the problem?

**Comment by yanzhenzeng** [comment]
you should use </firame> to close the iframe tag

**Comment by twolun** [comment]
@yanzhenzeng you are right!

**Comment by K-walker** [comment]
thanks . it's work @yanzhenzeng
