### ISSUE TITLE
[feature request] v-once data-bound

### ISSUE THREAD

**Issue by KingMario** [vuejs/vue#4020]
Is there any method to restrain the data responsive for a while?

I mean, since v-once directive seems to restrain the data responsive like for ever, should it be data-bound to indicate when to restrain the data responsive and when not to. The DOM won't re-render while the data is true, and while the data is false, the DOM will be still data responsive.

I'm making a search result page. I want to hold the search result static while the user is entering a new search term and the page's fetching search result to fulfill autocomplete.

After the user hit the return key or click the search button, the search result will be refreshed.

pseudo-code

``` html
<template>
  <div>
    <input @keyup.enter="doSearch" @keyup="preSearch" v-model="searchTerm">
    <search-auto-complete-list :result="searchResult"></search-auto-complete-list>
    <search-result v-once="!enterHit" :result="searchResult"></search-result>
  </div>
</template>

<script>
  // ... import ...

  export default {
    data () {
      return {
        enterHit: false
      }
    },
    vuex: {
      getters: {
        _searchTerm: state => state.searchTerm,
        searchResult: state => state.searchResult
      },
      actions: {
        setSearchTerm,
        search
      }
    },
    computed: {
      searchTerm: {
        get () {
          return this._searchTerm
        },
        set (term) {
          this.setSearchTerm(term)
        }
      }
    },
    methods: {
      preSearch (term) {
        this.searchTerm = term
        // ... debounce search implementation ...
      },
      doSearch (term) {
        if (term !== this.searchTerm) {
          this.searchTerm = term
          // ... stop debounce search ...
          // and do it immediately
          search(term).then(() => {
            this.enterHit = true
          })
        } else {
          this.enterHit = true
        }
      }
    }
    // ... other options ...
  }
<script>
```

**Comment by posva** [comment]
You don't need at all `v-once` for that. You can refresh the data that holds the results when the user hits return.

The feature can still be discussed with another use case

**Comment by KingMario** [comment]
But how to hold the data? Ain't all data in Vue responsive?

**Comment by posva** [comment]
Yes, but you decide when to change the data. You can use different variables to hold results and autocomplete suggestions. If you need more help, I encourage you to open a topic on the [forums](http://forum.vuejs.org/)

**Comment by KingMario** [comment]
I see.
Thanks.
