### ISSUE TITLE
Embeddable apps

### ISSUE THREAD

**Issue by terion-name** [vuejs/vue#4023]
As far as I understand, many things in Vue are bound to vue prototype, not the instance. vuex, router, etc. When I call `Vue.use()` — I bound an extension to prototype.

While this is not a problem for a standalone vue-driven application, this makes it impossible to build encapsulated/embeddable apps with it.
With modern techniques, availability of CORS  support in browsers and web trends — this is a growing market. For stuff from widgets (sort of "like button", or support chats, or weather/stock widgets) to full-featured embeddable applications, that one can drop in his own site on some page and provide some services.

Ember.js provides this option. It can be set up without prototype overloading, fully isolated and configured to route via history api with a base url.

In case of Vue there is one main stopper — if a target page already uses Vue. Then we will have problems :)

Can this feature be considered in a roadmap? I don't know what amount of work will be needed to unbound extensions from prototype and how this will break existent extensions, but I think, this will be beneficial for many cases

**Comment by fnlctrl** [comment]
You only need to bundle your own vue/vuex/vue-router along with your app with webpack/browserify, so they are not global and can never affect anything outside your app.

**Comment by morrislaptop** [comment]
Might help - https://github.com/kartsims/vue-customelement-bundler
