### ISSUE TITLE
about $compile function

### ISSUE THREAD

**Issue by huliqun** [vuejs/vue#4025]
### Vue.js version
2.0.2

I just miss  the _self.$compile(_self.$el) way to rebuild the page.
Is there any easy way to realize it ?
Because so many public js components are base on jquery. 
most of them has self-render function.  and event Listener, 
Although can use jquery way to bind function and bla, bla, bla things.
In vue i think Vue's way is better.
So , could u help with it.
I found many others have the same puzzle.

**Comment by fnlctrl** [comment]
Just use `this.dynamicComponent = Vue.extend({template: '......'})` to get a component, and then use it with `<component :is="dynamicComponent">`

**Comment by nilssolanki** [comment]
This only works when you know where the compiled template is going to be inserted. Is there a more generic solution than this?
