### ISSUE TITLE
建议改进config. ignoredElements

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#4026]
目前ignoredElements的配置项类型支持Array或String，然后检测逻辑是
ignoredElements.indexOf(tag)
这会导致当
ignoredElements ＝ ‘custom-el1,  custom-el2’  || ['custom-el1', 'custom-el2'] 都可以通过
当写一些需要拓展ignoredElements属性的通用组件时会造成困扰，当ignoredElements的类型是String时很可能会覆盖掉用户定义的原始ignoredElements值，不方便合并配置

**Comment by fnlctrl** [comment]
ignoredElements没有打算支持String类型的(https://github.com/vuejs/vue/blob/dev/src/core/config.js#L11)，只是碰巧String和Array都有indexOf方法罢了。
运行时对这类config加类型检测没有意义，请不要使用String类型，只用Array即可。
