### ISSUE TITLE
vue2.0.3渲染卡顿

### ISSUE THREAD

**Issue by breezefeng** [vuejs/vue#4028]
使用vue重构了一个页面，但是发现性能上比之前的页面还差
重构的页面：http://imgcache.qq.com/gc/gamecenterV2/dist/index/detail/detail_v3.html?ver=0&gc_version=2&module=game&appid=1104466820&_wv=1&notShowPub=0
之前的页面：http://imgcache.qq.com/gc/gamecenterV2/dist/index/detail/detail_v2.html?ver=0&gc_version=2&module=game&appid=1104466820&_wv=1&notShowPub=0

会发现重构的页面在loading快要消失的时候明显卡顿，在安卓机上更明显

**Comment by fnlctrl** [comment]
请阅读[Issue提交要求](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines)后再开issue。

**Comment by breezefeng** [comment]
vue.js性能优化有什么方法没
