### ISSUE TITLE
Suggestion about node.js-side rendering

### ISSUE THREAD

**Issue by fullfs** [vuejs/vue#403]
Hello, again!
I'm sorry about being impatient about the subject, but I would like to make a suggestion about how to implement node.js-side rendering (if you would).
I've tested rendering with jsdom a bit and came with conclusion it's rather slow. With huge amount of elements to render the time could reach 10-20 seconds (!!)
So maybe it would be smarter to implement separated template-preparing engine. Maybe something similar to Ractive .toHTML() (http://docs.ractivejs.org/latest/ractive-tohtml)
And with the separated engine it would be much easier to make a system for picking up server-side-rendered html in browser :)

P.S. Thanks for your efforts! I really loved Vue.js and hoping to use it as a basis at my project and I absolutely will if I will be able to produce proper server-side rendering :)

**Comment by fullfs** [comment]
Recently we've made a pre-release of the project I'm working on where we use Vue.js and also my insane script that imitates Vue's behavior on server side - VueServer (we use one component code both on server and client).
And I'm glad to say its all working just fine!
There it is: http://novosibirsk.n1.ru/ (sorry its on russian, can't help you there...). You could press some buttons or so... :) Also, check it out with javascript disabled to see server-side html.

P.S. @yyx990803 thanks so much for your Vue.js! It's like it made me fall in love with frontend development once again :)

**Comment by yyx990803** [comment]
Nice! Glad to know it's working out for you :)

**Comment by nkovacs** [comment]
I've started experimenting with the picking up hints part in [this branch](https://github.com/nkovacs/vue/tree/server-side), I've got simple text binding so far: http://jsfiddle.net/nkovacs/jt3zjadn/

It looks like this in the html:

```html
<!-- {{test -->Server side<!-- }} -->
```

As soon as Vue is initialized, it will overwrite the server-side text with the client-side text. This could be skipped by making the linking functions aware that they are being run for the first time, so they would skip the dom manipulation (but set up watchers).

**Comment by yyx990803** [comment]
@nkovacs wow nice! Please keep me updated. I'm wondering if it's possible to expose compilation hooks so that these can be made its own optional plugin.

**Comment by nkovacs** [comment]
v-model seems to work out of the box.
I've tried to implement v-repeat by reusing the elements generated by the server, and I think it works. It's a pretty ugly hack though.
http://jsfiddle.net/nkovacs/jt3zjadn/4/

**Comment by fullfs** [comment]
@nkovacs it looks great! I could combine it with my server-side vue-like rendering and it would work completly perfect!

**Comment by fullfs** [comment]
@nkovacs I mean I'm already able to do things like that:
http://jsfiddle.net/4o6o7bw2/

**Comment by nkovacs** [comment]
I've opened an issue on my fork as a to-do list: https://github.com/nkovacs/vue/issues/1
Most of the stuff already works out of the box, so that's great.

**Comment by chrisalexander55** [comment]
I am considering writing my new app with Vue and wanted to know the status of @nkovacs SS-rendering POCs, or another, and how that relates to Evan's vision for eventually supporting/merging in SS-rendering in Vue. Thanks.

**Comment by yyx990803** [comment]
@chrisalexander55:

@nkovacs' work was pre-1.0, so it's likely no longer relevant now. I do have plan to experiment with SSR early 2016 - my intuition is that getting idiomatic Vue components to render in Node should be relatively easy, but proper hydration without blowing away server-rendered DOM can be tricky.

**Comment by smolinari** [comment]
What are the problems trying to be solved, by making Vue SSR capable? It is one thing to want it. It is another to actually understand the reasons for wanting it and there have been none offered thus far. I'd like to put forth the reasons one *might* want SSR or maybe not?. 

Better SEO - [No longer needed](http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157)
Accessibility - [not really that hard to make a WAI-ARIA capable content client side](http://usabilitygeek.com/accessible-web-development-using-w3c-wai-aria/)
Fast first paint to screen times - [what are you loading, that needs fast paint times?](http://www.onebigfluke.com/2015/01/experimentally-verified-why-client-side.html)

What other factors or problems might need to be considered?

As a last bit of information to help develop a point of view (if you don't already have one), please have a look [at this blog](https://medium.com/google-developers/tradeoffs-in-server-side-and-client-side-rendering-14dad8d4ff8b#.hy63x3hkx). 

I am currently neither for nor against server-side rendering of Vue. I am just not truly understanding how any of the benefits of having SSR outweigh the risks of not having it. Any further insight, especially from Evan, would be greatly appreciated.

Scott

**Comment by fullfs** [comment]
@chrisalexander55 You can use [vue-server](https://github.com/ngsru/vue-server) right now. It's 99% compitable with latest Vue.js version. It's also tested in production.

**Comment by fullfs** [comment]
@smolinari Google in not the only one SE. Russian segment, for example, is highly dependent on [Yandex](http://yandex.ru) and its not able to properly parse js right now (maybe soon it will).
You could also share Vue.js components and templates in services like Emails generation or API resources that provide some html

**Comment by smolinari** [comment]
Good points. Thanks @fullfs Andrey. Any others?

Scott

**Comment by chrisalexander55** [comment]
Thank you @yyx990803, @smolinari and @fullfs for responding. My principle use case is related to a custom client-side performance metric of Time-To-First Art (an art and gift web site). It is important to scaffold some DOM, pull-in media from a CDN cache and ensure our end-users see product ASAP. This was the impetus behind my question. I am in the process of Proofing the app with Vue. If SSR'ed DOM is replaced by Vue component instances vs. attaching to DOM, then this would be a show stopper for us. Is this case? I simply haven't gotten to the point in the Proof to test this yet.

**Comment by fullfs** [comment]
@chrisalexander55 SSR'ed DOM replacing is overall ok and looks fine, try serfin through http://novosibirsk.n1.ru/ (no ENG support, sorry), probably you won't notice the moment of replacing.

But ofc, it has some restrictions. For example, if you animate something like banners or videos you will have to pull those parts of content after the moment of replacing.
Good thing is Vue.js itself is very fast at first loading and it won't take much time to rerender all the DOM.
Server-render DOM will also allow you to begin loading simple media content like images before the app is inited, so you can have some boost here.

**Comment by yyx990803** [comment]
@chrisalexander55 "blowing away existing DOM" sounds expensive, but in reality it's not really that bad, especially if your app itself is not that complex (e.g. just displaying a catalog of artworks). If anything, focusing on optimizing your image compression and distribution would probably yield much better return.

**Comment by jpodwys** [comment]
I've been looking into light-weight JS frameworks and I'm currently tinkering with riotjs but wanted to keep an eye on vuejs to see its take on SSR. I'd like to offer another couple of reasons why SSR is important. 

1- SSR is extremely important if you want to have the largest international user base possible. Many parts of the world are running on old browsers and even feature phones. Many of these devices either don't run JS or don't have the JS features required to run a modern site without downloading an obscene amount of shims. 
2- Bandwidth and latency concerns in emerging markets may not allow for downloading 500+KB in JS alone. Not referring to vue's size here, just a number I've seen on many modern sites. 

Having a server-rendered/client-rendered hybrid app ensures you can reach the largest audience while still allowing you to have a modern experience for those users that can enjoy it. Additionally, initial page load will be faster for 100% of users as no JS is required to have a working page (excuse the progressive enhancement plug).

**Comment by blake-newman** [comment]
I would say the hydration with hooks generated by Sir would be the best approach.  It will allow the SSR to become more behaviour driven giving possibility to serve partial SSR templates, diverting load to the server where applicable. 

http://tomdale.net/2015/02/youre-missing-the-point-of-server-side-rendered-javascript-apps/

It would also mean Vue can be extended to cope with SSR outside of the core.  Which is better than having the core being bloated.

I myself think Vue incorporating SSR,  could attract a larger audience.  I also think Vue could help reduce the complexity of SSR through the hydration model as described.

**Comment by yyx990803** [comment]
Closing as it's now in 2.0 ;)
