### ISSUE TITLE
Triggering a method of a child component through broadcast

### ISSUE THREAD

**Issue by kumarbalap** [vuejs/vue#4030]
Hi,

I found users having the similar issue, but so far no solution.

Please look at the below code, that calls a child component in v-for.

```
    <div id="plListCont" class="plListCont" v-on:scroll="getDataOnscroll">
        <span class="startLabel"><i class="fa fa-bookmark"></i></span>
        <ul>
            <li v-for="(index, pitem) in plistitem">
                <child-item :itemindex="index" :pitem="pitem"></child-item>
            </li>
        </ul>
    </div>
```

In **childItem** component I have a method called **toggle**.

Now I want to trigger the toggle method for specific child component instance.

I know that we cant have dynamic **ref** or **el** using the index.

Moreover **$children** is coming as 0 in created ( I have a broadcast defined).

Any suggestion or solution?

Thanks,
Bala

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.
