### ISSUE TITLE
[feature request] Check if iterator in v-for is first or last

### ISSUE THREAD

**Issue by krychu90** [vuejs/vue#4031]
I need to check if iterator in v-for is first/last.

Example:
```html
<ul>
    <li v-for="[key, val] of array" :class="{ 'first': $isFirst, 'last': $isLast }">{{key}} - {{val}}</li>
</ul>
```

```javascript
array: {'key1': 'value1', 'key2': 'value2'}
```

No problem if array/object keys are numeric (from 0). 

/vue 2

**Comment by simplesmiler** [comment]
For non-numeric keys there is no notion of order, so there's no first or last element.
You can easily achieve this by converting your data into a numerically-keyed array in a computed property.

**Comment by yyx990803** [comment]
First, as @simplesmiler pointed out, there's no guaranteed key iteration order for Objects. The notion of "first" can also depend on how your keys are named, so the implementation is dependent on your use case.

I'd suggest just create custom methods like `isFirst` and use it like this:

``` js
<li :class="{ first: isFirst(key, obj) }">
```
