### ISSUE TITLE
same ref name in multiple item do not create array in this.$refs when in render function

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#4035]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/WhiteCusp/gmve9d3p/35/

### What is Expected?
this.$refs.a should be a dom node list
### What is actually happening?
this.$refs.a is a single dom

**Comment by posva** [comment]
This is working as expected, `v-ref` creates an array with `v-for` loops. I see how this could be useful for form elements or any other element of different nature that needs the same function to be applied. However, it's something you can already achieve manually by specifying different references to different elements.

**Comment by baiyaaaaa** [comment]
but my example abrove do not creates an array,  because is in render function. it working as expected only in <template></template> with v-for loop. so how can i achieve that in render function?

**Comment by defcc** [comment]
add a refInFor attribute
```js
  render(createElement) {
  	return createElement('ul', [
      createElement('li', { ref: 'a', refInFor: true }, 'a'),
      createElement('li', { ref: 'a', refInFor: true  }, 'a'),
      createElement('li', { ref: 'a', refInFor: true  }, 'a'),
      createElement('li', { ref: 'a', refInFor: true  }, 'a')
    ]);
  }
```

**Comment by baiyaaaaa** [comment]
Thanks @defcc , it work well

**Comment by LeonardoRick** [comment]
@defcc Is there a way to do that using the template syntax?
