### ISSUE TITLE
SSR - TypeError: h is not a function 

### ISSUE THREAD

**Issue by imcvampire** [vuejs/vue#4036]
I'm trying to implement server-side rendering but I have faced this problem when to try to make `server-bundle`. 

PS: I'm using functional component in my project.

You can view more in http://stackoverflow.com/questions/40255939/vuejs-2-0-server-side-rendering

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

`h` is the name usually given to the `createElement` argument in a render function and it's necessary to name it that way when using jsx. I hope this helps 😉
