### ISSUE TITLE
vue-cli 1.x版本

### ISSUE THREAD

**Issue by nieyulin112** [vuejs/vue#4038]
尤大神，你好！我之前安装了vue-cli 2.x的版本，发现vue2.0的很多ui插件还没有支持，我想重新回到vue-cli 1.x,安装了sudo npm install -g vue-cli@1.0，但是悲剧发生了，通过vue init webpack 项目名，结果报了这样的错误: 
                      vue-cli · ((helpers.if_eq || (depth0 && depth0.if_eq)) || helperMissing).call is not a function

查了相关的资料，没有解决的办法，求大神，帮忙解决一下，谢谢！

**Comment by yyx990803** [comment]
1. 请不要用 issue 问问题

2. 还是用 2.x 的 vue-cli，要用 1.0 的 template 用 `vue init webpack#1.0`
