### ISSUE TITLE
vue2.0的移动UI

### ISSUE THREAD

**Issue by nieyulin112** [vuejs/vue#4039]
尤大神，支持vue2.0的移动UI的组件，有哪个支持的比较好的，望推荐一下，我所知道的，vux目前还没有发出支持vue2.0的版本，项目比较急，希望大神推荐一下

**Comment by ivan403704409** [comment]
@nieyulin112 mint-ui还不错
https://github.com/ElemeFE/mint-ui

**Comment by yyx990803** [comment]
请不要用 issue 问问题。

**Comment by xiazanzhang** [comment]
http://element.eleme.io/#/ 基于2.0 饿了么开源的

发自我的 iPhone

在 2016年10月27日，上午8:55，nieyulin <notifications@github.com<mailto:notifications@github.com>> 写道：


尤大神，支持vue2.0的移动UI的组件，有哪个支持的比较好的，望推荐一下，我所知道的，vux目前还没有发出支持vue2.0的版本，项目比较急，希望大神推荐一下

―
