### ISSUE TITLE
[Suggestion] Warn if user overrides Vue's internal methods

### ISSUE THREAD

**Issue by phanan** [vuejs/vue#4041]
Currently, properties that start with `_` or `$` are not proxied on the Vue instance because they may conflict with Vue’s internal. The same doesn't apply for _methods_, leading to problematic cases like [this one](https://jsfiddle.net/phanan/ruvft5cy/1/), where users may (accidentally) define methods which override Vue's internal API. 

Suggestion: Though this arguably belongs in userland, it might be helpful of Vue to introduce a console warning (`Warn: You're overriding Vue's internal method $emit. Be aware of misbehaviors.`) for such cases.

**Comment by yyx990803** [comment]
Yes - PR welcome.
