### ISSUE TITLE
Interpolation inside attributes has been removed, not just deprecated

### ISSUE THREAD

**Issue by regularmike** [vuejs/vue#4042]
I brought this up in the forums first and @phanan agreed that "deprecated" is misleading in this warning message that is logged when trying to use interpolation inside attributes: 

'Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead. For example, instead of `<div id="{{ val }}">`, use `<div :id="val">`.'

This suggests that the feature is still present but will be removed in the future and so should be avoided. However, it has already been removed so it seems that "deprecated" should be replaced with "removed." I'm happy to create a PR if that is helpful.

Repro steps:
1. Use a mustache in any HTML attribute.
2. View messages logged to the console.

This fiddle doesn't show the console warning but demonstrates that the feature has been removed: http://jsfiddle.net/zcg2d825/1/

**Comment by defcc** [comment]
Thanks @regularmike for your suggestion . We are working on it. @chrisvfritz

**Comment by chrisvfritz** [comment]
@defcc I just fixed this earlier today in the docs and migration helper and [this PR](https://github.com/vuejs/vue/pull/4043) will fix it in Vue's warnings. I'll reopen this until it's merged.
