### ISSUE TITLE
Can't get the old value when use object literal in directive

### ISSUE THREAD

**Issue by banricho** [vuejs/vue#4047]
### Vue.js version
2.0.2
2.0.3

### Reproduction Link
https://jsfiddle.net/banricho/vjbg2Lt2/

### Steps to reproduce
1. Use object literal in directive
2. Change

### What is Expected?
`binding.oldValue` is old value

### What is actually happening?
If value is an object, `binding.oldValue === binding.value`

**Comment by simplesmiler** [comment]
This is expected. When you don't change the reference, but mutate a property, there's no way to tell which property got mutated.
