### ISSUE TITLE
[Vue 2 Typescript types] Module '"node_modules/vue/types/index"' has no default export.

### ISSUE THREAD

**Issue by skyrpex** [vuejs/vue#4054]
I can't import Vue from within a Typescript file. Are the types OK?

test.ts

```ts
 
import Vue from 'vue'; // The compiler shows: Module '"node_modules/vue/types/index"' has no default export.
```

package.json

```json
{
  "scripts": {
    "test": "ts-node test.ts"
  },
  "dependencies": {
    "@types/node": "^6.0.45",
    "ts-node": "^1.6.1",
    "typescript": "^2.0.3",
    "vue": "^2.0.3"
  }
}
```

**Comment by HerringtonDarkholme** [comment]
That's exactly what typescript do. `import * as Vue from 'vue'` is equivalent to `var Vue = require('vue')`

**Comment by ktsn** [comment]
There is the difference of the way to transpile `import/export` between TypeScript and Babel.
As `Vue` is exported as commonjs style, we need to write `import * as Vue from 'vue'` in TypeScript like @HerringtonDarkholme said.

**Comment by skyrpex** [comment]
Thanks guys. I guess it's just common knowledge then... I'm kind of new
with TypeScript :+1:
