### ISSUE TITLE
V-model on a component - Error

### ISSUE THREAD

**Issue by victorditadi** [vuejs/vue#4057]
### Vue.js version
2.0.2

### What is actually happening?
Hi, i'm new on VueJS and i'm making a chat following a tutorial.
in the tutorial, the guy puts a v-model in a component, and when i doing this, not work, the component not shown and the console answer "text is not defined"

I not used jsfiddle because he want a HTTPS request, and my server don't have.

So a put a dontpad repository
http://dontpad.com/vuejs-forum

The problem it's in the input with id "problem".

Thanks.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
