### ISSUE TITLE
_xx keyed data is not accessible with this._xx in vue2.0.3, but can access with $vm.$data._xx

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#4058]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/matiascx/xoL8d7rk/2/

### Steps to reproduce
run 
### What is Expected?
this._mydata of child component is printed out in the console
### What is actually happening?
undefined printed out

**Comment by pzanitti** [comment]
As per the manual: https://vuejs.org/api/#data

> Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.

So you'll have to do `console.log(this.$data._mydata)` to print its value.

**Comment by xieguanping12** [comment]
fixed test #3802 @BigBlueHat

**Comment by fnlctrl** [comment]
As above. Thanks for the explanation by @pzanitti.
