### ISSUE TITLE
Composing templates with slots?

### ISSUE THREAD

**Issue by kristianmandrup** [vuejs/vue#4061]
Say I have a layout component as follows

```html
<template>
  <quasar-layout>
    <div slot="header" class="toolbar inverted orange">
      <left-menu ref="leftMenu"></left-menu>
    </div>
    ...
  </quasar-layout>
</template>
```

Normally I would have one or more items inside the element with the `slot="header"`, however to avoid huge components, I'd like to compose it.
However if I try to move it into a child component, I'm stuck with having to use a wrapper element (which doesn't work in my case due to strict CSS rules).
I don't think I can move the full element with the `"slot=header"` into the child component, as it would then apply to itself, and not the parent element. Any way to circumvent this composition limitation!?

```
<template>
  <span> <-- Trying to avoid having to wrap like this. Any way to tell the template to use some kind of virtual wrapper node!? is this a limitation from web components? WTF!?
    <button
      class="hide-on-drawer-visible"
      @click="onClickLeft()"
    >
      <i>menu</i>
    </button>      

    <quasar-toolbar-title :padding="1">
      Components
    </quasar-toolbar-title>

    <button
      class="hide-on-drawer-visible"
      @click="onClickRight()"
    >
      <i>menu</i>
    </button>      
  </span>
</template>
```

**Comment by defcc** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
