### ISSUE TITLE
`components` option should support readonly object

### ISSUE THREAD

**Issue by xiaoping0x** [vuejs/vue#4062]
### Vue.js version

2.0.0
### Steps to reproduce

```
// components/index.js export Foo, Bar etc.
import * as components from './components';

export default {
  name: 'app',
  components
};
```
### What is Expected?

Show ok without errors.
### What is actually happening?

Browser throw error `components has only getter.`
### Reasons

```
function normalizeComponents (options) {
  if (options.components) {
    var components = options.components;
    var def;
    for (var key in components) {
      var lower = key.toLowerCase();
      if (isBuiltInTag(lower) || config.isReservedTag(lower)) {
        "development" !== 'production' && warn(
          'Do not use built-in or reserved HTML elements as component ' +
          'id: ' + key
        );
        continue
      }
      def = components[key];
      if (isPlainObject(def)) {
        // should create or clone new components object inside Vue
        // instead of old one
        components[key] = Vue$3.extend(def);
      }
    }
  }
}
```

**Comment by defcc** [comment]
@xiaoping0x could you please provide a JSFiddle/JSBin/Codepen to demonstrate your issue ?

**Comment by ktsn** [comment]
It seems because webpack 2 treats an imported object as read only.

**Comment by HerringtonDarkholme** [comment]
@ktsn I think this is a ES-spec conforming behavior. http://exploringjs.com/es6/ch_modules.html#sec_imports-as-views-on-exports also here http://www.ecma-international.org/ecma-262/6.0/index.html#sec-module-namespace-exotic-objects
