### ISSUE TITLE
v-if not dynamically updated

### ISSUE THREAD

**Issue by Shmasya** [vuejs/vue#4063]
In my plunk v-if not work with dynamic data in v-if. http://plnkr.co/edit/etZO8QcPRDALsUaxeJQr. When i answer on question, i must see comment to question, but v-if not reload my data and not view new isShow on variable.

**Comment by Shmasya** [comment]
Oh, v-if not dynamically updated. In VueJS 1 it worked.

**Comment by defcc** [comment]
@Shmasya  you need declare your data  in your data function, like bellow

```javascript
{
  question: 'Question 1',
  answer: 1,
  comment: {
    text: 'Comment 1',
    isShow: false
  }
},
```
For more info, you could take a look at [http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats](http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats)

**Comment by Shmasya** [comment]
@defcc how to use vue.$set?

**Comment by defcc** [comment]
That's ok :)
