### ISSUE TITLE
v-html not working with iframes

### ISSUE THREAD

**Issue by joeinnes** [vuejs/vue#4070]
### Vue.js version
2.0.2

### Reproduction Link

~~http://jsfiddle.net/df4Lnuw6/~~
http://jsfiddle.net/joeinnes/36x7yvyf/1/

### Steps to reproduce
Add an iFrame into a v-html rendered field

### What is Expected?
The iframe should render

### What is actually happening?
Not clear - looks like Vue tries to render itself into the iframe.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Your repro link doesn't seem to show the problem, please fix it.

**Comment by joeinnes** [comment]
Apologies, corrected the fiddle to http://jsfiddle.net/joeinnes/36x7yvyf/1/

**Comment by fnlctrl** [comment]
The iframe is rendering fine here.
http://jsfiddle.net/L092crg4/
Also your original src won't work inside jsfiddle, so I changed it to bing.com

![1](https://cloud.githubusercontent.com/assets/5557143/19850897/09af9160-9f96-11e6-9d77-013813fd362b.png)

**Comment by joeinnes** [comment]
The original src might be what's causing the problem. I'll double check when I get home.

**Comment by joeinnes** [comment]
Yes, that was it. I'm sorry, I didn't read the src carefully enough, I believed it was a normal twitter embed frame, but it looks like there's some kind of custom Ajax call in there that's breaking the rendering.

Apologies for wasting your time.
