### ISSUE TITLE
Works in dev, does nothing in build

### ISSUE THREAD

**Issue by tobeorla** [vuejs/vue#4073]
### Vue.js version
2.0.3

### Reproduction Link
http://jsfiddle.net/5sH6A/848/

### Steps to reproduce
- Execute the same code in build, "Badalejo component" won't appear + no errors will be shown

### What is Expected?
Dev behaviour in build. (Display the newly added component in elements array)

### What is actually happening?
The new component isn't shown.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Can you clarify what you mean by 'build' and 'dev'? Are you using npm and a build system like webpack/browserify? If so, you need to provide a github repo for us to look into.

**Comment by tobeorla** [comment]
Yes, i'm using Vue's webpack kit.
In npm run dev works, while in npm run build doesn't.
Repo is private :(

**Comment by fnlctrl** [comment]
If you're using vue's webpack kit, vue-loader would require vue's standalone version in dev, but runtime-only version in build. So I assume that's what caused you problem.
As you're using `template` option in components, you need to use vue's standalone version. Please check out the section here: http://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by tobeorla** [comment]
¡You're right!
An exception would be appreciated if template var is not supported and client is making use of it.

**Comment by fnlctrl** [comment]
@toberorla Normally it would, but in build the exceptions messages are stripped and in dev it won't throw an exception.. I'll create an issue in vue-loader later.
