### ISSUE TITLE
[feature request] map parent attributes, events binding of component to child element within the component

### ISSUE THREAD

**Issue by lampard7824** [vuejs/vue#4075]
Using the example in https://vuejs.org/guide/components.html#Form-Input-Components-using-Custom-Events. 

```
<div id="v-model-example">
  <p>{{ message }}</p>
  <my-input
    label="Message"
    v-model="message"
  ></my-input>
</div>
```

```
Vue.component('my-input', {
  template: '\
    <div class="form-group">\
      <label v-bind:for="randomId">{{ label }}:</label>\
      <input v-bind:id="randomId" v-bind:value="value" v-on:input="onInput">\
    </div>\
  ',
  props: ['value', 'label'],
  data: function () {
    return {
      randomId: 'input-' + Math.random()
    }
  },
  methods: {
    onInput: function (event) {
      this.$emit('input', event.target.value)
    }
  },
})
new Vue({
  el: '#v-model-example',
  data: {
    message: 'hello'
  }
})
```

What if i wanted to add HTML attributes such as "placeholder" to the input box without adding "placeholder" as a new prop
or
I wanted to bind an "keypress" event to the input box without adding the `$emit('keypress')` in the component , like following

`<my-input value="test value" label="test label" placeholder="test placeholder" @keypress="doSomething"></my-input>`

Currently the result will be 

```
<div class="form-group" placeholder="test placeholder" onclick="doSomething">
   <label for="someRandomId">test label:</label>\
    <input id="someRandomId" value="test value">
</div>
```
you can see that the placeholder attribute and the keypress event are always attached to the root element (which is the form-group `div`) instead of the `<input>` element. I hope you can provide a new feature to route/map the event binding/attributes attachment to a specific child element instead of always the root element, so that it will be like the following:

```
<div class="form-group">
   <label for="someRandomId">test label:</label>
    <input id="someRandomId" value="test value" placeholder="test placeholder" onclick="doSomething">
</div>
```

**Comment by fnlctrl** [comment]
> What if i wanted to add HTML attributes such as "placeholder" to the input box without adding "placeholder" as a new prop
> or
> I wanted to bind an "keypress" event to the input box without adding the $emit('keypress') in the component , like following

That's against the the basic ideas of component properties and parent-child communication. 
Please explicitly declare the props you need and events to emit.

**Comment by evorine** [comment]
> That's against the the basic ideas of component properties and parent-child communication.
Please explicitly declare the props you need and events to emit.

If this is not technically impossible, I think this is a must feature. Sometimes, our main DOM element isn't the highest element in the component template. And we can't know which attributes will be added to the component. We just want all the attributes to be transferred to the marked element.

Can you rethink about this feature please? This will help many framework developers.

**Comment by FFX01** [comment]
I don't think implicitly routing html attributes and event bindings to internal html nodes is a good idea at all. In fact, I can see such behavior causing major headaches. Implicit bindings are never a good idea. 

In my opinion, trying to pass html attributes directly to a component without declaring them as props is also a terrible idea. Components are not html nodes, they are components and should be treated as such. If you want an html node, write an html node.

Your use case is easily solvable by simply explicitly declaring the attributes as props and populating them in the component. You could also have a computed value that will return a default in the event one of the props is undefined.
