### ISSUE TITLE
Switch the value and keys back to Vue 1.0

### ISSUE THREAD

**Issue by Jordan-Work** [vuejs/vue#4077]
### Vue.js version
2.0.2

First of all I would like to compliment you on the Vue.js library, after looking at the choices of front-end frameworks Vue came out on top so much so that we bet or major Quarterly release on this framework and are rebuilding our tools to integrate with this amazing framework. 
the documentation and community are solid.

Our feature request is to revert the `v-for="(value, key) in object"`
to `v-for="(key, value) in object"`

We are using this since we are coming from a Vue 1.0 library and desire to slowly update to Vue 2.0 .
 
Switching these would greatly assist us in upgrading to Vue.js 2.0 ?
https://snag.gy/UogiTA.jpg

### What is Expected?
the value and keys should be the same as Vue 1.0

Thank you,
For your consideration

**Comment by simplesmiler** [comment]
The order was switched to:
- `(value, index)` for arrays to be consistent with JavaScript's `forEach` and `map`.
- `(value, key)` for objects to be consistent with arrays and other object iterators (such as `lodash.forIn`).

**Comment by yyx990803** [comment]
As @simplesmiler pointed out, this was an intended major breaking change, and switching it back would be another breaking change for existing 2.0 users. So unfortunately this will not happen.
