### ISSUE TITLE
Using scoped css in v-html generated elements

### ISSUE THREAD

**Issue by dcefram** [vuejs/vue#4078]
First off, I'm aware that #3045 was filed before. But it is closed, and I would like to elaborate the special case that this would actually be needed, and how other tools actually accomplish this, along with suggestions on how to get this done.

## Scenario

First off, the case that I'm having is that I'm trying to style elements generated by a markdown parser. I wouldn't want the styles of a particular component mess up the styles of other components, so I would really prefer using `scoped` css.

**Sample code:**

```javascript
<template>
  <div class="some-component">
    <div class="contents" v-html="marked(value)"></div>
  </div>
</template>

<script>
import marked from 'marked';

export default {
  name: 'story',
  data() {
    return {
      value: '#Hello World',
    };
  },
  methods: {
    marked(value) {
      return marked(value);
    },
  },
};
</script>

<style lang="stylus" scoped>
.some-component
  
  h1
    color #F00
</style>
```

I could've used BEM or other approaches to do this, but I believe that Vue's `scoped` feature was intended to do what BEM was for, but just much cleaner and more elegant (in the source code at least).

Unfortunately, this wouldn't work since the generated html element won't have the unique identifier attribute that Vue would append to other elements, whilst the generated css would append that unique identifier to the `h1` style.

## How other tools compare

The only other tool that I ever used when using another view layer library was CSS Modules. Here's a sample code:

```javascript
render() {
  return (
    <div class={styles.someComponent}>
      {marked(this.props.value)}
    </div>
  );
}
```

```stylus
.someComponent

  h1
    color #F00
```

The code above would work properly, without the H1 styling mess up with the global H1 styles. Even if I have another component probably made by someone else, who has the same classname (`.someComponent`), it wouldn't still get the style of my H1, since css modules would replace/append unique strings to the class name, but at the same time, it wouldn't add anything to the h1.

On Vue's scoped approach, Vue seems to append a unique attribute even to element styles (those that are not classes or ids). So the style `h1` would be `h1[data-v-someuniquevalue]`.

## Suggestion (ie. my expected behavior)

Vue's scoped feature should just append a unique data-v-identifier to the root element of a component. Since Vue **requires** you to have only **one** root element for each component, I believe that is the best place to only append the unique identifier attribute.

The CSS should then be transpiled in such a way that it would not append attribute selectors, but rather, it would just prepend the parent element.

**Example:**
```
.some-component

  h1
    color #F00
```

should then be transpiled to:
```
[data-v-someuniqueid] h1 {
  color: #F00;
}
```

This way, it would still behave the same way as it is right now, but on the plus side, it would still be able to style any element added to a child element with a `v-html` attribute.

It would also mimic how css modules works, which is an extra plus for people coming from other libraries and were expecting a certain behavior to be the expected behavior... well, because that behavior makes more sense.

I would love to know what others would think, and obviously, since I believe there's only 2 of us who uses vue that is concerned with this behavior, it would be just fine if you someone can point out a workaround to this matter (without using BEM, or requiring me to name my classes in funny cryptic class names)

Thanks! And sorry in advance if ever I worded some sentences in a rude way.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

First of all, scoped css and any css related thing isn't vue's concern, nor would they be vue's feature (or react/angular etc.). It's supposed to be part of the build process.
Currently, scoped css is vue-loader's feature. Just like any other framework's build tool, it requires compilation.
What you're suggesting is adding css scope at runtime, which isn't possible because vue can never be  aware of your css files.
Therefore, the suggestion remains as in https://github.com/vuejs/vue/issues/3045.

**Comment by dcefram** [comment]
I see, thanks for the reply. So this could be possible to do in vue-loader. I'll go and take a look at the source code there.

> What you're suggesting is adding css scope at runtime

I believe that this is not the case. This can be done on compile/transpiling the css code, the same way it is done right now.

Right now, the vue-loader appends the unique attribute. All we have to do is not append it, and just prepend it as a parent element selector. Anyways, since regardless of how this would be done, this would most likely be a low prio issue for your team considering other much more important feature/issues you would work on, I'll be forking the loader and look into it myself.

Thanks again for the reply :)

**Comment by fnlctrl** [comment]
> I believe that this is not the case. This can be done on compile/transpiling the css code, the same way it is done right now.

Sorry I misunderstood your feature request...  Would you mind opening this issue at vue-loader's repo?

**Comment by dcefram** [comment]
Sure thing, thanks again :)

**Comment by simplesmiler** [comment]
One issue is that styles would still bleed through.
``` css
[parent] div { padding: 10px; }
[child] div { color: blue; }
```
The child's div would have padding, because it in fact is matched by both `[child] div` and `[parent] div`.
