### ISSUE TITLE
Using filters inside attributes with Vue 2.0

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue#4080]
Both of the following work in Vue 1:

```js
<a href="{{ 'something' | linkHandler }}">link</a>
<a :href="'something' | linkHandler">link</a>
```

Neither of them work in Vue 2.0, because you can only use filters inside interpolations, and you can't use interpolations as attributes anymore.

Any way around this?

**Comment by happyDemon** [comment]
You could use a computed property

**Comment by callumacrae** [comment]
Kinda defeats the point in using a filter, though. I don't want to declare 30 computed properties, and I don't want to declare duplicate methods across multiple components.

**Comment by iagafonov** [comment]
@callumacrae declare method in mixin (and use it) or in Vue.prototype like Vue.prototype.$linkHandler = function (value) {....} and use `<a :href="$linkHandler('something')">link</a>

**Comment by sqal** [comment]
https://github.com/vuejs/vue/issues/2756#issuecomment-246712696

**Comment by callumacrae** [comment]
@iagafonov: How is that not a workaround? What are filters for?

I'd suggest that you should either be able to be able to use filters everywhere—which would mean allowing interpolations as attributes when there is a filter—or filters should be removed. The current behaviour is confusing.

**Comment by yyx990803** [comment]
This has been discussed extensively during the 2.0 API design thread - please read that thread, most of the arguments have been raised already. Filters were originally to be removed but added back for the most common use case. There's no intention in changing how it works for 2.0.

**Comment by tronghiep92** [comment]
It work with ` <a :href="$options.filters.linkHandler('somthings')">link</a> `

**Comment by callumacrae** [comment]
Thank you for changing your mind on this 🙌 🙌 🙌

**Comment by vijaypws** [comment]
Its not working for me.
my code is : 

```html
<p v-html="getHtml('status')"></p>
```
I want to apply `caps` helper.

any idea ?

**Comment by adamreisnz** [comment]
If the `$options.filters.xxxxx` workaround works, then why on earth make us jump through hoops and not just support filters directly in attributes?

**Comment by michtio** [comment]
Also I see a lot of use for filters in attributes ... certain words going to lowercase as css class for example

**Comment by posva** [comment]
This is quite old but filters can be used in v-bind directives as well as text interpolation: https://vuejs.org/v2/guide/filters.html
