### ISSUE TITLE
Re-render elements when used array.unshift()

### ISSUE THREAD

**Issue by Opppex** [vuejs/vue#4082]
ISSUE  how to make that are not re-render template when unshift?
## Vue.js version
2.0.3
## Steps to reproduce.
Open devtools. Find my list (ul).
Click button.
Re-render elements when used unshift().  
When use push() all good, just add new element.
i just open devtools and I see how re-render items.
## Reproduction Link
https://jsfiddle.net/philvv/sxxjkf1a/

I know when unsift is used, the array indices are shifted.
But angular does not re-render elements. 
Question: 
Since the list is a lot of data, wouldn't it be expensive to redraw all the elements??

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by Opppex** [comment]
Ok. Thank you. But is a maybe bug. Because I think no need to re-render the entire list))

**Comment by TheDutchCoder** [comment]
You should use the `key` property for this.
Vue tracks unique keys when re-rendering lists. If you don't provide keys it will do a complete re-render: https://vuejs.org/guide/list.html#key
