### ISSUE TITLE
Odd data/dom syncing bug

### ISSUE THREAD

**Issue by revati** [vuejs/vue#4085]
https://jsfiddle.net/revati/1khq32ed/8/ When reordering, it changes dom, but not state (it because reorder method does nothing), but when i add logic in it

https://jsfiddle.net/revati/1khq32ed/9/ When reordering, it changes state, but dom goes to previous state.

**Comment by yyx990803** [comment]
Read about the key: https://vuejs.org/guide/list.html#key

Correct behavior with proper key usage: https://jsfiddle.net/1khq32ed/10/

**Comment by revati** [comment]
Thanks, i were dealing with this bug like whole weekend 😂 
Will look into keys :)

**Comment by kenmaclord** [comment]
@yyx990803 thanks you saved my day !
