### ISSUE TITLE
[error] “DevTools was disconncted from the page”

### ISSUE THREAD

**Issue by allenou** [vuejs/vue#4089]
### Vue.js version
2.0.1

### Steps to reproduce
1. Make the component name and module name the same
2. Used the component
3. Debuging

Here is code :
```javascript
<template>
<div id="notice">
    <notice></notice>
</div>
</template>

<script>
import Notice from './components/Notice.vue'
export default {
  name: 'Notice',
  components: {
    Notice
  }
}
</script>
```
### What is actually happening?
The Chrome page crashes and have a error :
> DevTools was disconncted from the page.
Once page is reloaded, DevTools will automatically reconnect

**Comment by defcc** [comment]
The component name **Notice** conflicts, which cause an infinite render loop.

**Comment by allenou** [comment]
So it's not a bug of vue? Ok, I know, now close it.
