### ISSUE TITLE
 vuejs didn't render the same pushed value?

### ISSUE THREAD

**Issue by linvar** [vuejs/vue#4092]
//index.js
var vm = new Vue({
       ...
       data: {
             headers: []
       },       
       method: {
             onClicked: function(){
                   this.headers.push('');
             }
        }
})

//index.html
<button v-on:click="onClicked">Add</button>
<template v-for="header in headers">
       <input type="text"  v-model="header"><br>
</template>

what i expected was:
when clicked on button,  add one empty <input> element, and associated with vm.headers element.

the result is:
the first <input> element is added, but no more <input> added when i clicked.

from the console, i explore the vm.headers has more than one empty element, 

it seem vuejs didn't render for the same value ??

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by luventa** [comment]
I guess he need to add 'v-bind:key' because the value in headers are all the same.

**Comment by luventa** [comment]
@linvar 

this works correctly with vueJs 2.0.3:

new Vue({
  el: '#test',
  data: {
    headers: []
  },
  methods: {
    onClicked: function(){
	this.headers.push('');
    }
  }
})

html:
<div id="test">
  <button v-on:click="onClicked">Add</button>
  <input type="text" v-for="header in headers" v-model="header">
</div>

**Comment by linvar** [comment]
@luventa sorry not to mention the version i used.
i used csp version of vuejs 1.x in chrome extension, 
because i failed to find out how to get csp version of vuejs 2.x.

from vuejs.org installation guide,  i use "npm install vue",
and trying to get the runtime version from node_modules/vue/dist/ directory.

i also tried git clone vue and wanna build from src,  during npm install dependencies, failed.

@yyx990803   the link of  Issue reporting guidelines you provied is 404,
i had try to use "insert code" syntax...

**Comment by simplesmiler** [comment]
@linvar you can use `track-by="$index"` on the element with `v-for` in this case.

**Comment by linvar** [comment]
@simplesmiler i works!  thanks
