### ISSUE TITLE
method in expression be called unlimited

### ISSUE THREAD

**Issue by gaojunle** [vuejs/vue#4096]
### Vue.js version
2.0.3

### Reproduction Link
http://codepen.io/gaojunle/pen/YpKJQB

### Steps to reproduce
According to the document described in the Computed-Caching-vs-Methods, methods defined in "methods" can be called in the template expression. but I found the method is called unlimited. if you do something before return, the page will crash;

### What is Expected?
Method is called once;

### What is actually happening?
Method is called unlimited

**Comment by yyx990803** [comment]
This is expected because there is a state change in your method, and state change triggers a re-render, so it ends up in an infinite loop.

Method calls in templates / render functions should be pure and not produce side effects / state changes.
