### ISSUE TITLE
Unexpected recalculation of computed property

### ISSUE THREAD

**Issue by Bob4ever** [vuejs/vue#4097]
### Vue.js version
2.0.2

### Reproduction Link
https://jsfiddle.net/bob4ever/88ztn9fb/

### Steps to reproduce
Click 2 times on the button.

### What is Expected?
I would expect that the computed property "bar" doesn't update after the second click on the button because the value of "foo" doesn't change

### What is actually happening?
The computed property "bar" will be recalculated after "foo" was recalculated even when the computed value of "foo" doesn't change.

Is this behavior intended and I'm just missing something?

**Comment by dstrang** [comment]
I believe this is intended behavior. The computed property 'bar' has a dependency on the computed property 'foo' and 'foo' has a dependency on 'test'. Therefore, whenever the button is clicked and 'test' is updated, anything with that dependency is updated and so on down the chain.

**Comment by yyx990803** [comment]
As @dstrang pointed out, this is the expected (and correct) behavior.
