### ISSUE TITLE
textarea placeholder is set into textarea value (IE11)

### ISSUE THREAD

**Issue by KhristenkoYura** [vuejs/vue#4098]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/wxw3aa86/1/

**Comment by LinusBorg** [comment]
It seems this is a bug in IE11:

https://connect.microsoft.com/IE/feedback/details/811408

We'll have to see if there is a way to work around this bug.

**Comment by gebilaoxiong** [comment]
If this is a BUG

[web-runtime-with-compiler.js#L67](https://github.com/vuejs/vue/blob/dev/src/entries/web-runtime-with-compiler.js#L67)

Then here can not directly use `outerHTML`, is it?

**Comment by LinusBorg** [comment]
1. The IE bug happens with both innerHTML and outerHTML
2. We use outerHTML to get the in-DOM template, this is not really a functionality we can replace.

**Comment by gebilaoxiong** [comment]
@LinusBorg I know...I need to find the core members confirm, and then fix it....
