### ISSUE TITLE
Between the two pages how to use Vue to pass information

### ISSUE THREAD

**Issue by K-walker** [vuejs/vue#4108]
Triggers a click event, how to go through the Vue to listen to the other page
like this 
    page1.html
        <button v-on:click="showInfo">click<button>
        new Vue({
                el:'',
                 methods:{
                      showInfo:function () {
                              // TODO 。。。。
                      }
                }
        })
How to receive this event in Page2 by Vue;

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
