### ISSUE TITLE
Flow type declarations are missing from the npm package

### ISSUE THREAD

**Issue by atleta** [vuejs/vue#4109]
While the git repo has the flow type declarations (besides the typescript ones), they are not present in the npm package (unlike the typescript ones). This makes it impossible to use flow with a Vue.js project. 

Note that there might be other obstacles, as I've tried to manually copy the flow directory and its contents to my project then add it to my .flowconfig and I'm still getting errors for the imports in the Vue.js source files (i.e. the lib, and not my code). Seems to be a problem with relative imports, e.g.: 

```
node_modules/vue/src/platforms/web/compiler/index.js:6
  6: import { compile as baseCompile } from 'compiler/index'
                                            ^^^^^^^^^^^^^^^^ compiler/index. Required module not found
```

But it may be me as I'm new to flow.

**Comment by HerringtonDarkholme** [comment]
Hi, can you elaborate more about your use case? It seems you are using compiler which doesn't have a type definition at all. 

You should use compiler package https://www.npmjs.com/package/vue-template-compiler.

For vue to work with flow, I don't know whether flow support reading typing in package.json. The [doc](https://flowtype.org/docs/third-party.html) says you might need to submit pull request to flow-typed official repo.

**Comment by yyx990803** [comment]
Vue's internal flow annotation is not intended for public consumption. It relies on the alias configured in Vue's own `.flowconfig`. We may submit a public flow definition to flow-typed in the future, not currently it's not available yet.
