### ISSUE TITLE
input lose the focus when list rendering use "v-model" and ":key"

### ISSUE THREAD

**Issue by hanan198501** [vuejs/vue#4113]
```
      <div v-for="(item, index) of value" :key="item.text">
        <input  v-model="item.text" /> 
      </div>
```
For this example, the item plus a `key` and use `v-model` on input of item . The input will lose the focus when keyup ，how to resolve problem ？ thanks.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, you are literally recreating the input every time the text is changed. You should give your items identifiers, and key using them instead. As an alternative, you could `:key="item"` to track items by reference.
