### ISSUE TITLE
Vue 2.x – Bootstrap 3 – Templating issue when creating Vue instance on show.bs.modal

### ISSUE THREAD

**Issue by mariofink** [vuejs/vue#4114]
### Vue.js version
2.0.3

### Reproduction Link

http://jsbin.com/migigir/3/edit?html

### Steps to reproduce
Create a Bootstrap 3 modal window and attach a function to its show.bs.modal event.
This function creates a new Vue app instance with the modal window as root element.
Add a button to the page that will show the modal.
Inside the Bootstrap modal there is an input field bound to Vue data.

### What is Expected?
The data bound to the input field should be rendered at the first opening of the modal window.
If you exchange Vue 2 with Vue 1 inside the JSBin example you can see the expected behaviour.

### What is actually happening?
If you open the modal via clicking the button, then the input field will not be filled with that data. Only when you close the modal and open it a second time will the data be properly shown.

**Comment by yyx990803** [comment]
Vue 2.0 replaces the target element if you use in-dom templates. This may be conflicting with how Bootstrap handles the modal element. Although in your case you don't need to (and shouldn't) bootstrap the Vue app everytime the modal opens, just call `createVueApp()` directly and everything works fine.

**Comment by mariofink** [comment]
Thanks for the quick response. I will change my code accordingly.
