### ISSUE TITLE
V-if possible in-patch strategy issue

### ISSUE THREAD

**Issue by bolerodan** [vuejs/vue#4119]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/yvstzudp/

### Steps to reproduce
Increase the counter on A  to 1
Increase the counter on B to 2
Click toggle to view counter C
### What is Expected?
That the C counter is created and instantiated new with its own unique UID and the counter value set to 0.
### What is actually happening?
It seems that Vue is reusing dom elements and possibly doing its in-patch strategy. I expect the components to be destroyed (hook never called) when v-if is false, and recreated new. This example shows that this does not happen. The destroy method only happens on the B counter, but never A or C. If I put in key="" attribute on the v-if and v-else, it solves this issue, but this is not mentioned anywhere in the docs or I feel like this is not expected behavior

**Comment by yyx990803** [comment]
This is unfortunately expected behavior due to how the patch works - simply add a key to the if/else blocks to differentiate them: https://jsfiddle.net/yvstzudp/1/

**Comment by bolerodan** [comment]
@yyx990803  is it possible that this could also be mentioned in the docs for v-if? I know the key caveat is listed under list rendering, but specifically mentioned "v-for". I only came across the solution of using the key attribute on my own by thinking of the list rendering case and thought, why not, probably the patch strategy (turns out I was right) But this is not mentioned for v-if in the docs.

**Comment by yyx990803** [comment]
Yes, absolutely
