### ISSUE TITLE
Event on nested component since v2

### ISSUE THREAD

**Issue by maxwarch** [vuejs/vue#4121]
Hello,

i notice a possible bug since v2 that i don't have in v1.x on nested component.

This works on click test : [fiddle](https://jsfiddle.net/racbns2x/4/)
This doesn't work on click test : [fiddle](https://jsfiddle.net/racbns2x/5/)

I this normal or is it really a bug ?

Thanks.

**HTML**
```
<div id='parent'>
    <h1>{{title}}</h1>
    <div id='children'>
        <h4>{{titleChildren}}</h4>
        <comp></comp>
    </div>
</div>
```

**JS**
```
var comp = {
	template:'<div><a href="#" @click="toggle()">test</a></div>',
    methods:{
    	toggle:function(){
      	alert('ok') // don't fire in V2
      }
    }
};

var child = new Vue({
	el: '#children',
  components:{
  	'comp':comp
  },
    data:{
    	titleChildren: 'Test - Children'
    }
})

var parent = new Vue({
	el: '#parent',
    data:{
    	title: 'Test - Parent'
    }
})
```

**Comment by yyx990803** [comment]
Hmm, you are not supposed to manually mount inside another already-mounted Vue instance. This is incorrect usage - the fact that it happens to work in Vue 1.x is a coincidence, and 2.0 does not support it. You should register child as a proper child component of parent and use it in parent's template.
