### ISSUE TITLE
v2.0.4 Breaks IE conditional statements

### ISSUE THREAD

**Issue by darrylhein** [vuejs/vue#4125]
### Vue.js version
2.0.4 (works in 2.0.3)

### Reproduction Link
http://codepen.io/darrylhein/pen/BQabVR

### Steps to reproduce
Add IE conditional comments with HTML inside them.

### What is Expected?
Stay hidden unless the version of IE is matched. Thus hidden in all other non-IE browsers.

### What is actually happening?
IE conditional comments are removed and thus content inside the conditional is always displayed.
If there is no HTML then the content is hidden (as it should be).

**Comment by yyx990803** [comment]
FYI Vue removes the comments during template parsing, so supposedly the conditional content would not show in IE8 either. You probably don't want to use Vue to compile these conditional comments at all.

**Comment by darrylhein** [comment]
Well that's good to know. Thanks for the fix.
