### ISSUE TITLE
Feature request: expose 'createElement' under 'Vue' object.

### ISSUE THREAD

**Issue by SeanJM** [vuejs/vue#4126]
Feature request
=======================

This one is simple, expose 'createElement' on the `Vue` object, so that `h` can be omitted from the `render` function. So that when JSX is typed, we can lower the error margin, by excluding one step.

**Comment by yyx990803** [comment]
1. The `createElement` passed to render functions are bound to the instance being rendered. This is required for Vue vnodes to have correct render context.

2. If exposed on global `Vue`, you'd need to do `import Vue from 'vue'` in every component, which is in fact more verbose.

**Comment by SeanJM** [comment]
I'll play around with it I guess. Maybe I am trying to hard to make it similar to React...

**Comment by yyx990803** [comment]
@rusintez you can get the listeners in `context.data.on`

**Comment by rusintez** [comment]
@yyx990803 !!! 👍 completely forgot about that, thanks )

**Comment by haan123** [comment]
I don't know if this is valid or not, but it works for me

``` javascript
import Vue from 'vue'
import Modal from '~/components/Modal'
import Logo from '~/components/Logo'

Vue.prototype.$modal = {
  open(params) {
    ...

    const ModalComponent = Vue.extend(Modal)
    const modal = new ModalComponent({
      ...
    })

    modal.$slots.header = modal.$createElement(Logo) // here i used vm.$createElement to create the logo for modal's header

    return modal
  }
}
```
