### ISSUE TITLE
oppo or xiaomi phone will be thrown directly

### ISSUE THREAD

**Issue by rambo-panda** [vuejs/vue#4129]
### Vue.js version
2.0.3

### What is actually happening?
In some `oppo x909t` `oppo r817t` or xiaomi2 phone, will be thrown directly because of the use of the keyword
 [`native`](https://github.com/vuejs/vue/blob/v2.0.3/dist/vue.js?#L6720) **SyntaxError: Unexpected token native**
 and 
[`class`](https://github.com/vuejs/vue/blob/v2.0.3/dist/vue.js?#L3456) **Uncaught SyntaxError: Unexpected token class**

**Comment by rambo-panda** [comment]
Seemingly `Andrews 4.2-` will have this problem

**Comment by yyx990803** [comment]
Vue itself doesn't use these keywords - are you sure this is from Vue's code? What does the Error stack trace look like?

**Comment by shusiwei** [comment]
@rambo-panda you need change babel config

**Comment by rambo-panda** [comment]
@yyx990803  @shusiwei 
I am using the code directly in the dist folder

### Error location:

https://github.com/vuejs/vue/blob/v2.0.3/dist/vue.js?#L6720
https://github.com/vuejs/vue/blob/v2.0.3/dist/vue.js?#L3456

**Comment by yyx990803** [comment]
Sigh, what browsers do they use on those phones? The tests pass on a stock Android 4.2 browser and even IE9...

**Comment by yyx990803** [comment]
Unfortunately this will be a wontfix. The phones you listed are more than 3 years old, and I haven't seen any Android 4.2 browsers that demonstrate this behavior.

Vue's support list are browsers that conform to the ES5 spec - and by the spec, the presence of `native` as a variable name and the use of `class` as a property identifier should not cause parsing errors.
