### ISSUE TITLE
all transitions also emit animationend event

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue#4130]
`<transition name="fade">
    <div class="ui-popup ui-content-size ui-content-fixed ui-content-fixed" v-show="visible" @animationend="destroy($event)">
      <transition name="zoom">
        <div class="ui-popup-animate" v-show="visible">
          <p>{{message}}</p>
        </div>
      </transition>
    </div>
  </transition>`

.ui-popup && .ui-popup-animate
the animationend event is also fired

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by shusiwei** [comment]
https://jsfiddle.net/Ly2eshmr/

**Comment by yyx990803** [comment]
Please be more specific about what is your expected behavior and what you think is wrong...

**Comment by shusiwei** [comment]
in this example, use cont as div.ui-popup's animationend event cont the number of executions，but click animate button, we can see the count will plus twice, because div.ui-popup-animate also listen to animationend event, we can see the event.target element, they are different，but only div.ui-popup's listen to animationend event.

**Comment by yyx990803** [comment]
Isn't this expected behavior? `visible` controls both the outer transition and the inner transition, it only makes sense to fire two events...

**Comment by shusiwei** [comment]
@animationend only bind div.ui-popup
