### ISSUE TITLE
<img> :src set the filter error 

### ISSUE THREAD

**Issue by CodinngLee** [vuejs/vue#4132]
just like it 
`<img :src="product.adImage | appendParams " class="img-responsive"/>`

i register the filter appendParams

but the error:
Property or method "appendParams" is not defined on the instance but referenced during render

i want to change the image url before render。how can I deal with it?

**Comment by defcc** [comment]
You could ask your question on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

------

As for your problem, you could use computed properties. You could take a look [this doc](https://vuejs.org/v2/guide/syntax.html#Filters)
