### ISSUE TITLE
Inconsistent documentation or behaviour of vm.$watch

### ISSUE THREAD

**Issue by atleta** [vuejs/vue#4133]
### Vue.js version
2.0.2

The following code produces the following error on the console:

```
const app = new Vue({
    el: '#app',
    // template: '#app-template',
    data: {
        height: 0,
        weight: 0,
    },
// ....
});
app.$watch('weight + height', function () {
  // do something
});
```

```
vue.js:2611[Vue warn]: Failed watching path: "weight + height" Watcher only accepts simple dot-delimited paths. For full control, use a function instead.
```

OTOH the documentation (https://vuejs.org/v2/api/#vm-watch) explicitely states that it's a valid syntax. It even has the same example.

**Comment by defcc** [comment]
Thanks @atleta ,  the document needs to be updated

**Comment by yyx990803** [comment]
moved to vuejs.org

**Comment by defcc** [comment]
A PR created. https://github.com/vuejs/vuejs.org/pull/570 .

**Comment by lopugit** [comment]
I got this error when trying to watch a literal path `'some.path.with a space delimited property path.value'`, do spaces still work? I thought this should act the same as any square bracket property access syntax, such as `some.path['with a space delimited property path'].value` ?
