### ISSUE TITLE
Select input is default option not binded

### ISSUE THREAD

**Issue by seuaCoder** [vuejs/vue#4136]
Not sure if this is a bug but i wonder why the second select input (in the example) is blank on change ? 

### Vue.js version
2.0.2

### Reproduction Link
https://jsfiddle.net/aj6g87dh/1/

### What is Expected?
Default option selected or first option selected bby default

### What is actually happening?

On change, the second select is blank

**Comment by yyx990803** [comment]
The selected option always reflect the value of v-model value which is `list`. When you switch options, `list` doesn't change, so nothing in the new options are selected.

You probably want to explicit set `list = this.options[0].value` in `onChange`.
