### ISSUE TITLE
mixin will support route hook ?

### ISSUE THREAD

**Issue by Gavin-Gong** [vuejs/vue#4137]
``` JavaScript
const mixin = {
  beforeRouteLeave (to, from, next) {
    console.log('from mixin router'); // do't work 
  },
  created () {
    console.log('from mixin created'); // work
  },
};

export default mixin;
```

I want to mixin some route hook function `beforeRouteEnter` `beforeRouterLeave` to options, but I find Vue ignore route hook. build-in options like `created` is ok.

**Comment by yyx990803** [comment]
Please open issue at `vue-router`'s repo.
