### ISSUE TITLE
Some props seems to be reserved but undocumented

### ISSUE THREAD

**Issue by Phyks** [vuejs/vue#4139]
### Vue.js version
2.0.4

Hi,

I tried to set a `slot` prop on my component, and I had a lot of troubles with it, Vue was keeping telling me that the prop was not filled while it obviously was and it took me a long time to figure this out.

Finally, I changed the prop name to `slotInfo` and everything worked without modifying the code anywhere else.

So, it seems to me that `slot` is a reserved prop name and should not be used, although I am not 100% sure about this. It is also the case for [some others keywords](https://github.com/vuejs/vue/issues/3984).

When looking at [the doc](https://vuejs.org/v2/api/#props) I could not find any list of such reserved error, and the error message was too generic (missing required prop) to make me think about such a thing.

It would be really helpful to have either a list of such reserved prop names or a more explicit error message I think.

Thanks

**Comment by yyx990803** [comment]
http://vuejs.org/v2/api/#Special-Attributes

**Comment by Phyks** [comment]
Indeed, thanks for the link!

Maybe adding a link to this section in the `prop` section would give it more visibility?

**Comment by chasegiunta** [comment]
@yyx990803 is `hash` reserved, by chance? Having an issue with that prop name.
