### ISSUE TITLE
Why the this => data , show in the safari is '?'

### ISSUE THREAD

**Issue by ringcrl** [vuejs/vue#4140]
just like that

![qq20161107-0](https://cloud.githubusercontent.com/assets/16740021/20043425/12e8b234-a4c8-11e6-9714-dfc662b9dea9.png)

I thought it is inconvenient...

**Comment by ringcrl** [comment]
I must click the eye-button to see the data...

Why...

**Comment by yyx990803** [comment]
Because they have been converted to getters and setters. Use JSON.parse(JSON.stringify(data)) to normalize it.
