### ISSUE TITLE
Internal method overriding detection

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#4142]
2.0.5 introduced a feature that Vue warns if user is trying to override an internal method. It's a good thing, though I think the current detecting implementation is debatable.

According to [this commit](https://github.com/vuejs/vue/commit/4078ce9c58830fecff095ab96dc41693377794dd#diff-cb87aa7890fa694dd923ea9f162256d2R154), every method on Vue's prototype is checked. But not everything there is necessarily an internal method. For example, if I manually add a method to `Vue.prototype`, and try to manipulate this method later on, I'll get a warning. Same thing happens when a third party package adds some method to `Vue.prototype`.

Such cases can be confusing because the method that gets warned is not actually shipped with Vue itself. Any chance this will get improved?

**Comment by HerringtonDarkholme** [comment]
Hi, I have considered this case in this commit. My opinion is that if a third library added a method on Vue's prototype, the library author probably don't want it get changed by end users. Can you elaborate your situation more? 
If that will be long, we can migrate it to forum. https://forum.vuejs.org/

**Comment by Leopoldthecoder** [comment]
> My opinion is that if a third library added a method on Vue's prototype, the library author probably don't want it get changed by end users.

Agreed. I see the discussion in #4111, and I think detecting methods that starts with `$` or `_` is a good approach. Closing this issue now.
