### ISSUE TITLE
Using SSR with defined dynamic components, not rendered classes at tag (component)

### ISSUE THREAD

**Issue by PowerfulPony** [vuejs/vue#4143]
### Vue.js version
2.0.2

### Steps to reproduce

1. Create component
```
Vue.component('testcomponent', {
  render: h => h('div', 'contain')
})
```
2. Use the components within the parent component template with className
```
  <div id="appcomponent">
    <testcomponent class="testclass" />
  </div>
```

### What is Expected?
Expected to render on the server side
```
  <div id="appcomponent">
    <div class="testclass">contain</div>
  </div>
```
Similarly, as the client-side

### What is actually happening?
The server side is not renders classes in dynamically generated components
```
  <div id="appcomponent">
    <div>contain</div>
  </div>
```
At the same time, the client side, renders everything with classes

```
  <div id="appcomponent">
    <div class="testclass">contain</div>
  </div>
```

This behavior causes a twitch of the interface, due to the belated addition of classes with styles.
Also incorrect display if the js file not to load on slow internet.

**Comment by LinusBorg** [comment]
Hello @PowerfulPony,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by PowerfulPony** [comment]
Hi @LinusBorg,
I do not understand how you can demonstrate through the server render jsfiddle.

**Comment by LinusBorg** [comment]
In this case, a repository would be the better option, oviously.

**Comment by defcc** [comment]
Seems to be a bug, similar to #4076
