### ISSUE TITLE
Vue stripping out styles from inline SVG

### ISSUE THREAD

**Issue by morrislaptop** [vuejs/vue#4144]
### Vue.js version
2.0.3

### Reproduction Link
https://jsbin.com/lurayuxofo/edit?html,js,console,output

### Steps to reproduce
1. Include inline SVG with some styles within a Vue instance
1. Init vue instance

### What is Expected?
1. SVG to be styled according to the style element

### What is actually happening?
1. Vue is giving a warning "[Vue warn]: Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>. " and also stripping the style element so the SVG is appearing with no style.

**Comment by oppiansteve** [comment]
There is a workaround - give a duplicate namespace and use that explicitly in the style declaration:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" viewBox="-10908 -1035.2 142.8 140.6">
  <defs>
    <svg:style>
      .cls-1 { fill: red; transform-origin: 50% 50%; } .cls-2, .cls-4 { fill: none; } .cls-2 { stroke: #1f1f1f; stroke-width: 5px; } .cls-3 { stroke: none; }
    </svg:style>
  </defs>
```

**Comment by HerringtonDarkholme** [comment]
Just as the warning said, please don't put styling logic in your components. style tags in SVG is the same as putting a style tag in head/body. It has side-effect. https://jsbin.com/gejegacamu/edit?html,output

If you want scoped or modularized styling, you can have a look on vue single file component.

**Comment by vcavallo** [comment]
@oppiansteve when I try this, I get the following error:

```
Error: SVGO for /path/to/the-icon.svg failed.
```

Any ideas?

**Comment by PierBover** [comment]
`<style>` in an inline SVG is perfectly valid markup and Vue shouldn't mess with it.

**Comment by jorgejesus** [comment]
Just to make it clear, you can copy SVG style content into the vue style section of your component

**Comment by blwsh** [comment]
Should this really be marked as resolved? The current solution is basically the equivalent of.
Don't worry, you can move your 1+1 equation from JS to PHP.

Style tag in SVG is valid markup so why doesn't it work.

**Comment by MeisterTea** [comment]
seing this issue doesn't get any more exposure since it's been closed for years now, I have opened this one instead: https://github.com/vuejs/vue/issues/11697
