### ISSUE TITLE
Questions SPA

### ISSUE THREAD

**Issue by GlauberF** [vuejs/vue#4145]
Hello,
I'm new to VUE.js and VUEX development precisso develop a SPA to communicate with my api done in lumen, like some material, videos, to assist me in building des from beginning to end of the SPA, if the Portuguese- language en best, can not be English.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by GlauberF** [comment]
ok
