### ISSUE TITLE
renderToStream data event not called

### ISSUE THREAD

**Issue by masious** [vuejs/vue#4147]
Hi. I'm trying to add SSR to my vue project and I have a problem with renderToStream.

```
  const context = { url: req.url }
  const renderStream = renderer.renderToStream(context)

  console.log('I do work just fine');
  res.write(html.head)
  renderStream.on('data', chunk => {
    console.log('I AM NOT LOGGED!')
    res.write(chunk)
  })

  renderStream.on('end', () => {
    res.end(html.tail)
    console.log(`whole request: ${Date.now() - s}ms`)
  })

  renderStream.on('error', err => {
    // Render Error Page or Redirect
    res.status(500).end('Internal Error 500')
    console.error(`error during render : ${req.url}`)
    console.error(err)
  })
```

In the code above, none of the callbacks are called. When I open the page, Only the title of the page is rendered and nothing else is shown. None of the console commands, are called either. The browser just shows the loading logo in the top of the page, and nothing happens.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Looks like you are not piping the stream to the response.
