### ISSUE TITLE
$emit doesn't fire on callback

### ISSUE THREAD

**Issue by evu** [vuejs/vue#4148]
Hello, new to Vue but can't seem to find answers anywhere, and those I have got state it should work so perhaps this is a bug?

Repo: https://github.com/evu/vue-test

Comments in code.

Note.vue
```
<template>
	<div class="note">
		<h1>{{ note.title }}<h1>
		<pre>{{ note.content }}</pre>
		<button type="button" v-on:click.stop="remove">Remove</button>
		<button class="edit" type="button" v-on:click="selectNote(note)">Edit</button>
	</div>
</template>

<script>
	import NoteRepo from '../../data/NoteRepo';

	export default {
		props: ['note'],
		methods: {
			remove(){
				console.log(this) // This is the same Vue instance as the one below

				// If I put the $emit here, it works fine. Just not in the callback below

				NoteRepo.remove(this.note, (err) => {
					if (err) {

						console.log('should fire') // This does get echoed to console
						console.log(this)  // This is the same Vue instance as the one above

						// But this event doesn't get emitted
						this.$emit('alerted', {
							type: 'error', 
							message: 'Failed to remove note'
						});
					}
				})
			},
			selectNote({key, title, content}) {
			        // This event works fine, just like when moving the above out of the callback
				this.$emit('selected', {key, title, content});
			}
		}
	}
</script>
```

Notes.vie
```
<template>

	<div class="notes" ref="notes">
                // Here's where they're captured
		<note v-for="note in notes" :note="note" v-on:selected="emitNote(note)" v-on:alerted="emitAlert"></note >
	</div>

</template>


<script>


import Note from './Note';
import NoteRepo from '../../data/NoteRepo';

export default {
	components: {
		Note
	},
	data() {
		return {
			notes: []
		}
	},
	methods: {
		emitNote({key, title, content}) {
			this.$emit('selected', {key, title, content});
		},
		emitAlert(alert) {
			console.log('recieved') // This is never fired when inside the callback
			this.$emit('alerted', alert);
		}
	}
}
</script>
```

Unfortunately I'm not able to reproduce it in a fiddle or pen, but if you require any more of the above codebase let me know. Hope the comments make sense.

**Comment by posva** [comment]
The comments make sense but a repro would make things faster that someone else trying to isolate your code. I took a look but couldn't find anything wrong.
You may get more help on the [forums](https://forum.vuejs.org/)

**Comment by evu** [comment]
https://github.com/evu/vue-test 

There's a repo, think that should be everything. If there's anything wrong let me know. I've tried the forums, glitter and SO but no luck unfortunately.

**Comment by posva** [comment]
a repro, not a repo 😐

**Comment by evu** [comment]
Ah, haha I can't be the first to fall for that :)

I'm unable to recreate it in JSfiddle, etc I'm afraid as I'm quite new to Vue, and have only been using the single file component method so far. The repo should provide a working example at least, just need to click the remove button. (I understand there's the whole npm install thing, unfortunately).

**Comment by posva** [comment]
No, you aren't, others have fallen too 😄 
I'll give it a shot

**Comment by posva** [comment]
@evu I tried and it works nicely after some edits. I got a `PERMISSION_DENIED` error and a red message appears on top.
The problem seems to appear because of a weird character on your App.vue template at line 6.
It looks like a simple tab but that doesn't make any sense, I'll look deeper
