### ISSUE TITLE
Link with characters especial not show image in style background image.

### ISSUE THREAD

**Issue by BlackMix** [vuejs/vue#4149]
### Vue.js version
2.0.5

I have one question in link with characters especial.. type:

1: Here image not show 
 `<div class="episode_thumb_image" :style="{ backgroundImage: 'url(' + image + ')' }">`
  
2: Here image show  
`<img class="episode_thumb_image" :src="image" />`
   
this is link image:
 http://3.bp.blogspot.com/-vGXHaT9Uu54/U7V7181HiNI/AAAAAAAAAMA/mOr9AUN0FxA/s1600/ss+(2014-06-05+at+11.04.40).jpg

### Link text:
https://jsfiddle.net/qyoj220f/2/

where am I wrong at this? is bug or I wrong? 

thanks.

**Comment by yyx990803** [comment]
value inside `url(...)` cannot contain more parens. You need to wrap them in quotes.
