### ISSUE TITLE
Asynchronous actions reset the value of an input with unrelated data properties.

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#4150]
### Vue.js version
2.0.2

### Reproduction Link

https://jsfiddle.net/am2mrpv6/1/
### Steps to reproduce
1. Click on the test button
2. Immediately select the text in the input and change something
3. Wait for 3 seconds 

### What is Expected?
Nothing in the input box should change. The method tester is only changing the property test. Value should be left alone.

### What is actually happening?
The value of the input is reset to whatever it's last saved value was.

I realize that if I used `v-model` then the value would change as I type, but that is not desirable in a situation where you are using the input as part of a larger component. Also, only updating `onchange` has the nice side effect of limiting any related operations to be done on completed values instead of on every keystroke.  As background here is something closer to the real problem I ran into https://forum.vuejs.org/t/stop-an-asynchronous-store-update-from-also-updating-other-values-in-a-component/2612. I thought it was something I had done wrong, but I feel that after simplifying it further this is actually a bug.

**Comment by yyx990803** [comment]
Binding `:value="value"` is basically creating a one-way bind that makes the value of the input box constant. It's not the same as binding default value. You should either be using `v-model` to make the value sync on input, or use `:default-value.prop="value"` to create a binding for default value only.

**Comment by qw3n** [comment]
Neither of those solutions work. This isn't about default values that was just part of the simple example. Perhaps I should have gone into more detail about placing this in a component, but if you set this to `v-model` inside a component your restrictions on mutating props kick in. I was following the example Linus Borg gave about 3/4 down the page here https://forum-archive.vuejs.org/topic/4468/trying-to-understand-v-model-on-custom-components/10

```javascript
// parent
<zipcode v-model="zipcode"></zipcode>

//child
<input :value="value" @input="$emit('input', $event.target.value)" >
<script>
export default {
   props: ['value'] // special prop received from v-model
}
</script>
```

Here is an example that is closer to what I am trying to do https://jsfiddle.net/1wtdzg4a/ just imagine that it is instead packaged into a component with props instead of data variables. The problem is like I said if I dynamically update the quicklist at the bottom of the component it resets the text input which would be completely frustrating for an end-user making the whole thing unusable. 

This feels like a rock and a hard place since I'm not supposed to mutate the props which is what v-model does yet your telling me to use v-model.
