### ISSUE TITLE
the element set v-bind:style="{ backfroundColor: config.background_color}", but :active in style doesn't work at all,why and how to deal with it?

### ISSUE THREAD

**Issue by OnlyBreak** [vuejs/vue#4151]
### Vue.js version
2.0.2

**Comment by BlackMix** [comment]
See this link https://github.com/vuejs/vue/issues/4149

And it https://jsfiddle.net/qyoj220f/9/ and https://jsfiddle.net/qyoj220f/7/

U can use this with your question.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
