### ISSUE TITLE
Asynchronous updates inside a component reset an input's value.

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#4158]
### Vue.js version
2.0.2

### Reproduction Link

https://jsfiddle.net/r8ohn7z3/

### Steps to reproduce
1. Choose a basic color from the dropdown
2. Start typing a different color into the textbox
3. When the time changes if you are still typing it will reset it to the previous color

### What is Expected?
The input's value is left the way it is when the `time` update happens.

### What is actually happening?
The value of input is being reset and so the user's input is being removed

### Background
I previously submitted this [bug](https://github.com/vuejs/vue/issues/4150) in which I may not have clearly stated that this is inside a component. But because this is a component, your advice about using `v-model` is not even possible. The idea is for user's convenience having multiple ways for a user to input a value.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
It seems that the problem here is the `change` event from `<input>` isn't fired until `<input>` loses focus, and this is a browser behavior which we can't really help with. 
The workaround is simple: explicitly bind the `input` listener to `<input>`, which is immediately fired whenever the user types: 
https://jsfiddle.net/rx6jeznj/

**Comment by qw3n** [comment]
@fnlctrl thanks for the help this will definitely let me work around this, but there is something I don't understand. Why is this even necessary? The `time` value is the only thing that is being updated why does it trigger an update of all the values in the component? In other words it seems to me that because the `setInterval` function is only affecting one variable why should I have to worry about it updating `value`? I thought the reactivity was only supposed to efficiently update variables that had changed--in this case `time`.

**Comment by fnlctrl** [comment]
Simply put: before `change` event is fired, the `<input>` has its own temporary state that is different from the app's, and will be overridden by the app state when the render function is called, which is triggered by the update of `time`. The render function is called whenever anything reactive is changed.

**Comment by yyx990803** [comment]
Notice that you are allowing the user to create a DOM state (by typing into the input with only a one-way bound value) that is disconnected from the underlying application state. Whenever the component updates, the application state will force the DOM state in sync and throw away the temporary input state.

To precisely control what you want, you need to represent this temporary state in your application state by creating a separate local property (which you can then use `v-model` on): https://jsfiddle.net/r8ohn7z3/1/

**Comment by yyx990803** [comment]
I think we may need to follow React's take on this by warning such usage and freezing the input altogether.

**Comment by qw3n** [comment]
@yyx990803 thank you for your response. I spent several hours trying to figure out what was happening, and perhaps it was just me, but I think because frameworks tend to naturally be a black box combined with my misconception about the render function I was at a loss on what to do. In retrospect it makes much more sense what was happening and how to work around it. When running into these edge cases it would be nice if some type of error or warning were thrown to alert the developer to what is happening. But,I know that that isn't an easy solution since edge cases by definition are not something you run into all the time.

**Comment by yyx990803** [comment]
@qw3n yeah, we will most likely add a warning for one-way value bind in the future.
