### ISSUE TITLE
Is it possible to still render server-side when using vue-router?

### ISSUE THREAD

**Issue by jdosullivan** [vuejs/vue#4163]
Hello,

I have an app that renders server-side but did not have routing. I am using Vue 2.0. I decided to add Vue-router and use a <router-view> component to render. The app works fine but I've lost my server-side rendering. So for example:

**< template>
  < div class="page">
          <MainHeader></MainHeader>
      < router-view>< /router-view>
  < /div>
< /template>**

The main header renders just fine, but the page content that fits into the router-view does not show up when I view source in the browser even though the app works just fine. Is this expected behavior? 

Also bear in mind this is on initial page load that I am talking about, not moving from one page to another. So I am doing a browser load typing in the url.

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You should find this useful: https://github.com/vuejs/vue-hackernews-2.0

**Comment by jdosullivan** [comment]
Thanks I'll post on there.
