### ISSUE TITLE
tapmode attribute  is not work 

### ISSUE THREAD

**Issue by K-walker** [vuejs/vue#4164]
code :
`<html>`
`<body>`
     ` <div id="main">`
           `<div tapmode=""  v-on:click="showAlert"> show Alert </div>`
     `</div>`
`</body>`
`<script>`
     `  new Vue({`
              `el:"#main" ,`
               `data:{},`
               `methods:{`
                       `showAlert:function() {`
                                   `alert("hello");`
                       `}`
                `}`
       `})`
`</script>`
`</html>`

I use tapmode attribute  to eliminate the delay of 300ms by using Vue , but it's not work . why ?

**Comment by LinusBorg** [comment]
Hello @K-walker ,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by K-walker** [comment]
ok @LinusBorg 
 
I have changed 
Trouble you to give me the answer
thank you !
