### ISSUE TITLE
Intercepting checkbox values?

### ISSUE THREAD

**Issue by kristianmandrup** [vuejs/vue#4167]
I'm trying to intercept a checkbox value in order to save it in a Vuex store.
I'm on Vue2 and using `vue-material`, but that shouldn't make a difference (same underlying model).

```html
    <md-checkbox 
      v-for="choice in prompt.choices" 
      :name="prompt.name"
      :id="prompt.name"
      @input="updateChoice($event)"
      @change="updateChoice($event)" 
      class="md-primary" 
      v-model="choice.value">{{ choice.label }}</md-checkbox>
```

In my component, no matter what I do, I only get the true/false value passed in, never the full DOM event as I would expect. Are the docs off, and something changed in this regard with Vue2.
Please update the official Vue2 guide. Still almost half of it is for 1.x.

https://vuejs.org/v2/guide

```js
  methods: {
    updateChoice (e) {
      console.log(e)
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

> but that shouldn't make a difference

Yes it does, if the author of `md-checkbox` only wanted to pass the value when `$emit`-ing an `input`, you don't get the full DOM event. The `input` event only serves as an interface, and full DOM events are only guaranteed to be available when you're directly listening for `$emit` event on native `<input>`s.

**Comment by LinusBorg** [comment]
What should work: `v-on:input.native="yourcallback"`

This will listen for the native input event on the root element of the component. Even if that's a div and not the input element, you should be able to catch the event because it bubbles.

**Comment by yyx990803** [comment]
@kristianmandrup the docs have been fully updated for 2.0. If there are parts where it's still 1.x (and changed in 2.0), please open corresponding issue at the vuejs.org repo.

**Comment by kristianmandrup** [comment]
@fnlctrl I noticed as much. I looked into his code filed an issue and made a [PR](https://github.com/marcosmoura/vue-material/issues/49) however, trying out this change didn't work either. Now I tried the @LinusBorg approach also, but the native event is not even triggered.

Here is my attempt to fix it in `vue-material`

https://github.com/kristianmandrup/vue-material/blob/master/src/components/mdCheckbox/mdCheckbox.vue

Still getting nowhere. @yyx990803, there are still many inconsistencies in the docs... I will post some issues about the docs in the future.


```html
<template>
  <div>
    <md-checkbox 
      v-for="choice in prompt.choices" 
      :name="prompt.name"
      :id="prompt.name"
      class="md-primary" 
      @input.native="onChosen"
      v-model="choice.value">{{ choice.label }}</md-checkbox>
  </div> 
</template>
<script>
export default {
  props: ['prompt'],
  data () {
    return {
    }
  },
  mounted () {
    this.$watch('prompt.choices', (newChoices, old) => {
      console.log('newChoices', newChoices)
    })
  },
  methods: {
    onChosen (e) {
      console.log(e)
    }
  }
}
</script>
```

**Comment by LinusBorg** [comment]
Glad that "half" the docs" became "some inconsistencies" within the last 90 minutes. :)
