### ISSUE TITLE
Sortable with Vuejs, works in 1, doesn't work in 2

### ISSUE THREAD

**Issue by alexcorvi** [vuejs/vue#4168]
I'm trying to make the sortable list two-way bound

[Here's an example of HTML and array elements in `vue 1`](https://jsfiddle.net/alexcorvi/h3d55yxs/)

As you can see it works as expected.

[Here's the same example ported to `vue 2`](https://jsfiddle.net/alexcorvi/9ne1m5js/1/)

it looks broken!

I think it's because the way vue 2 handles dom diffing? Or is it a bug? Is there a a way to work around it?

**Comment by defcc** [comment]
You could add a unique key for each list item, take a look at [list rendering doc](https://vuejs.org/v2/guide/list.html#key)  

I updated the fiddle here https://jsfiddle.net/defcc/9ne1m5js/2/

**Comment by posva** [comment]
It's because sortable works with the dom in place and Vue needs a hint to keep track of dom elements
