### ISSUE TITLE
v-model 处理方式不一致性问题

### ISSUE THREAD

**Issue by asmodai1985** [vuejs/vue#4170]
### Vue.js version
2.0.5

### Reproduction Link
https://jsbin.com/supetu/edit?html,js,output

### What is Expected?
自定义组件处理v-model和value应该和input处理方式是保持一致的

### What is actually happening?
自定义组件并不能使value设置无效，反而是使的v-model 无效了

同时设定value 和v-model 应该是错误的使用方式，但这确实给我使用过程中带来了一点小问题(因为我还在比较多的使用后端模板)--期望开发组有时间能来处理下这个小问题。

**Comment by HerringtonDarkholme** [comment]
Please read the doc.

https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

**Comment by asmodai1985** [comment]
thanks for your answer.
