### ISSUE TITLE
When Standalone build encounters a missing template/renderFn, misleading warning "you use runtime-only build..." is logged

### ISSUE THREAD

**Issue by MikeRalphson** [vuejs/vue#4171]
### Vue.js version
2.0.5

### Reproduction Link

https://jsfiddle.net/df4Lnuw6/40/

### Steps to reproduce

A newbie accidentally creates an empty template, or the template fails to compile, while using the compiler-included build.

### What is Expected?

The Vue warning `Failed to mount component: template or render function not defined.` or similar.

### What is actually happening?

The Vue warning `You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

This warning message is misleading in the compiler-included build. If it was defined differently in the two builds, this would solve the issue.

**Comment by LinusBorg** [comment]
@MikeRalphson, Thanks for filing this issue.

This warning should *not* appear when using the compiler-inlcuded build, so we will need a reproduction repo for that, please.

**Comment by MikeRalphson** [comment]
@LinusBorg Thank you for the prompt response. Issue updated with the repro fiddle. See console output when run.

**Comment by posva** [comment]
@MikeRalphson There're no logs there

**Comment by MikeRalphson** [comment]
@LinusBorg my apologies, I didn't realise that the fiddle did not auto-save. I've updated it now.

**Comment by LinusBorg** [comment]
@MikeRalphson sorry, but you haven't updated the link. https://jsfiddle.net/df4Lnuw6/ still points to the basic "starter" code.

**Comment by MikeRalphson** [comment]
@LinusBorg sincere apologies, jsfiddle didn't give me an updated link until I created an account...

Please try https://jsfiddle.net/df4Lnuw6/40/

**Comment by LinusBorg** [comment]
Thanks! That seems indeed to be a bug.
