### ISSUE TITLE
Filters in :bind

### ISSUE THREAD

**Issue by lsv** [vuejs/vue#4172]
### Filters in :bind does not work

```
<span :title="text | doUppercase">{{ text | doUppercase }}</span>
<span :title="doUppercase(text)">{{ text | doUppercase }}</span>
```

[Working example](https://jsfiddle.net/yMv7y/1918/) not using in any binds, but just in plain simple element `<span>{{ text | doUppercase }}</span>`

[Adding filters](https://jsfiddle.net/mrztubpa/) to a bind via `<span :title="text | doUppercase">{{ text | doUppercase }}</span>`

Result in a `vue.min.js:6ReferenceError: doUppercase is not defined(…)`

Also tried [adding filters](https://jsfiddle.net/k9krLqp4/) via `<span :title="doUppercase(text)">{{ text | doUppercase }}</span>`

Result in a `vue.min.js:6ReferenceError: doUppercase is not defined(…)`

So you can not use filters in :bind?

[In the documentation is reads](https://vuejs.org/v2/guide/syntax.html#Filters): Vue 2.x filters can only be used inside mustache bindings

Is this a mustache bindings? - 

My use case is quite simple

My output would be something like this

Input: `<span :title="date | momentFull">{{ date | moment }}</span>`
Output: `<span title="2016-11-10 08:32">2 hours ago</span>`

```
filters: {
  moment (date) {
    return Moment(date).fromNow();
  },
  momentFull (date) {
   return Moment(date).format('YYYY-MM-DD HH:mm');
  }
}
```

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

No, you can't https://vuejs.org/v2/guide/migration.html#Filters-Outside-Text-Interpolations-removed

**Comment by lsv** [comment]
Shouldn't this also be written somewhere close to [Filters](https://vuejs.org/v2/guide/syntax.html#Filters) instead of only in the migration?

**Comment by posva** [comment]
I don't think so because it belongs to migration. It's absent on the Vue 2 docs because it doesn't exist anymore after all

**Comment by lsv** [comment]
I havent used filters in vue 1.x (im still pretty new :)
Filters can be used when writing but not in binds, thats confusing from my point of view

`{{ data | filter }}` then I would expect that I also could use it in binds (and everywhere else).

But maybe thats just me, and there are properly a reason why its not working.

**Comment by posva** [comment]
It looks pretty clear to me: https://vuejs.org/v2/guide/syntax.html#Filters
The reason is that bindings' content is jslike. Filters are a common practice in interpolation
