### ISSUE TITLE
Can no longer use jqGrid in Vue?

### ISSUE THREAD

**Issue by linfulongnet** [vuejs/vue#4177]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://unpkg.com/vue@2.0.3/dist/vue.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/element-ui@1.0.0-rc.8/lib/theme-default/index.css">
    <script src="https://unpkg.com/element-ui@1.0.0-rc.8/lib/index.js"></script>

    
    <script type="text/ecmascript" src="js/jquery-1.11.0.min.js"></script>
    
    <script type="text/ecmascript" src="js/i18n/grid.locale-en.js"></script>
    
    <script type="text/ecmascript" src="js/jquery.jqGrid.min.js"></script>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    
    <link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid-bootstrap.css" />
    <script>
        $.jgrid.defaults.width = 780;
        $.jgrid.defaults.styleUI = 'Bootstrap';
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>
<div id="nav">
    <el-menu default-active="1" class="el-menu-demo" mode="horizontal">
        <el-submenu index="1">
            <template slot="title">data</template>
            <el-menu-item index="1-1" @click.native="test = true">data 1</el-menu-item>
        </el-submenu>
    </el-menu>
    <el-dialog title="data" v-model="test">
        <div style="margin-left:20px">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </el-dialog>

</div>
<script type="text/javascript">
    new Vue({
        el:"#nav",
        data:{
            test:false
        }
    });
    $(document).ready(function () {
        $("#jqGrid").jqGrid({
            url: 'http://trirand.com/blog/phpjqgrid/examples/jsonp/getjsonp.php?callback=?&qwery=orders',
            mtype: "GET",
            datatype: "jsonp",
            colModel: [
                { label: 'OrderID', name: 'OrderID', key: true, width: 75 },
                { label: 'Customer ID', name: 'CustomerID', width: 150 },
                { label: 'Order Date', name: 'OrderDate', width: 150 },
                { label: 'Freight', name: 'Freight', width: 150 },
                { label:'Ship Name', name: 'ShipName', width: 150 }
            ],
            page: 1,
            width: 800,
            height: 500,
            rowNum: 20,
            scrollPopUp:true,
            scrollLeftOffset: "83%",
            viewrecords: true,
            scroll: 1, // set the scroll property to 1 to enable paging with scrollbar - virtual loading of records
            emptyrecords: 'Scroll to bottom to retrieve new page', // the message will be displayed at the bottom
            pager: "#jqGridPager"
        });
    });

</script>

</body>
</html>

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
