### ISSUE TITLE
v-else and v-once on custom component inside v-for

### ISSUE THREAD

**Issue by fmairesse** [vuejs/vue#4182]
Here is a list rendering using a custom component and the `v-once` directive:
```html
<li v-for="item of items" :key="item.model.id">
    <item :model="item.model" v-once></item>
</li>
```
[JsFiddle using Vue@2.0.5](https://jsfiddle.net/wwyk89jk/3/)
Note that this does not work using Vue@2.0.3, unless we remove the `v-once` directive.

Now let's add a conditional rendering:
```html
  <li v-for="item of items" :key="item.model.id">
    <span v-if="item.model.id===1">BOB</span>
    <item :model="item.model" v-else v-once></item>
  </li>
```
[JsFiddle using Vue@2.0.5](https://jsfiddle.net/pabkqads/4/)
[JsFiddle using Vue@2.0.3](https://jsfiddle.net/f713xc59/4/)
This fails using Vue@2.0.5 with the error: 
> Property or method "item" is not defined on the instance but referenced during render.

but works with 2.0.3 (2.0.3 failed when there was no `v-else`)

**Comment by posva** [comment]
Thanks for reporting that! In the meantime, a workaround would be to move the `v-once` inside the component

**Comment by defcc** [comment]
elseBlock should be walked through too in **markStaticRoots** fun. I'll make a PR to fix it.

**Comment by zeeshankamboh** [comment]
how to fix this problem???? any idea regarding it???

**Comment by zeeshankamboh** [comment]
actually vue is reporting a very bad error in console  because of this issue. and i dont know how to tackle this problem.
