### ISSUE TITLE
Kebab-case css property names don't work for v-bind:style

### ISSUE THREAD

**Issue by agaripian** [vuejs/vue#4184]
### Vue.js version
2.0.5

### Reproduction Link
https://jsfiddle.net/agaipian/n4cedd59/1/

### Steps to reproduce
Use the following syntax ` v-bind:style="{ margin-top: spacer + 'px' }">`
The Vue documentation says:  (https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles) 
`The object syntax for v-bind:style is pretty straightforward - it looks almost like CSS, except it’s a JavaScript object. You can use either camelCase or kebab-case for the CSS property names:`

Kebab-case is not working for the style binding, camelCase only works. See fiddle above.

### What is Expected?
The margin-top style for the element should contain the proper value

### What is actually happening?
Vue is throwing an error `invalid expression: v-bind:style="{ margin-top: spacer + 'px' }"`

**Comment by LinusBorg** [comment]
> `it’s a JavaScript object.`

When using hyphen in an object key, they has to be put in quotes. That's Javascript, not Vue.

**Comment by yangzhixiao** [comment]
@LinusBorg and how to write when I want then margin-top, padding-top..., I try this, paddingTop, but it doesn't works. please help..

**Comment by jkzing** [comment]
It should work, see [https://jsfiddle.net/j7q9tLb0/1/](https://jsfiddle.net/j7q9tLb0/1/)
