### ISSUE TITLE
Problem with v-model in Vue.js 2.0

### ISSUE THREAD

**Issue by ricvelozo** [vuejs/vue#4185]
### Vue.js version
2.0.5

### Reproduction Link

https://jsfiddle.net/tqwxk226/

### Steps to reproduce
Switch between versions of Vue.js, and enter any text in the input

### What is Expected?
Property update on input, like in Vue.js 1.0

### What is actually happening?
When using Vue.js 2.0, the field changes to empty on input event (any key)

**Comment by fnlctrl** [comment]
Seems to be a 2.0.4/2.0.5 regression, working fine on 2.0.3. @defcc 
https://jsfiddle.net/bk7gbeq5/

**Comment by defcc** [comment]
Thanks, I am looking into it.
