### ISSUE TITLE
Filter image src binding

### ISSUE THREAD

**Issue by daryl** [vuejs/vue#4190]
Is it possible to filter the image source when data binding? I realise I could just make a computed property, but I feel like I'm missing a trick.

```html
<img :src="src | dpi" />
```

**Comment by JounQin** [comment]
https://vuejs.org/v2/guide/syntax.html#Filters

Maybe you can de this, maybe ugly but useful:
``` vue
<img :src="$options.filters.dpi(src)" />
```

Of course, they will tell you that it is not an issue and you should ask this question in Gitter or forum.😂

**Comment by defcc** [comment]
Thanks @daryl ,  you could use computed property or the way as @JounQin mentioned for now.  It's still under discussion whether to bring the **pipe** syntax back to attribute or not.
