### ISSUE TITLE
mergeData cannot works properly with Array

### ISSUE THREAD

**Issue by zhu** [vuejs/vue#4191]
### Vue.js version
2.0.5

### Reproduction Link

https://jsfiddle.net/crjL62kL/4/
### Steps to reproduce
1 Create an array
2 Add something to Array.prototype or add some property to the array obj
3 use this array as data and trigger mergeData
### What is Expected?
the array is merged withou error and without key-values in prototype
### What is actually happening?
TypeError or key-values in prototype is copy to the array

**Comment by Jinjiang** [comment]
It seems `for (key in from) { ... }` in `mergeData` let them go through.
https://github.com/vuejs/vue/blob/v2.0.5/src/core/util/options.js#L44

**Comment by zhu** [comment]
`obj.length = Math.max(obj.length, key)` in `set` throw the TypeError when the array has own properties. I think it's better to merge all elems and properties from the `from` array.
https://github.com/vuejs/vue/blob/v2.0.5/src/core/observer/index.js#L189

**Comment by yyx990803** [comment]
This seems to be a bug in the VueCharts library, because `mergeData` should never be called on arrays. This means the library is somehow passing an array as the `data` option, which is not supported.

**Comment by zhu** [comment]
The VueCharts library does not pass an array as the `data`.
https://github.com/vuejs/vue/blob/v2.0.5/src/core/util/options.js#L49
The `mergeData` will be called recursively. So the function will be called on arrays when the data include array properties.

Here's another example without VueCharts:
https://jsfiddle.net/bdpkrnus/

And I think the `mergeData` will copy properties from `from` object's prototype to the `to` object. Is this by design?

**Comment by yyx990803** [comment]
There is indeed a bug in `mergeData`, but your usage is incorrect: you should not be declaring a prop and a data property using the same key.

After the fix you should see a warning message telling you not to do that.
