### ISSUE TITLE
$emit with inline style?

### ISSUE THREAD

**Issue by YamiOdymel** [vuejs/vue#4193]
I'm trying to communicate with the parent component, instead of doing

```js
<template lang="pug">
    //- Register button
    button.fluid.basic.inverted(@click="switchScreen()")
</template>

<script>
methods: {
    switchScreen() {
        this.$emit('switchScreen', 'register')
    }
}
</script>
```

can we just do something like this?

```js
<template lang="pug">
    //- Register button
    button.fluid.basic.inverted(@click.emit="switchScreen | 'register'")
</template>
```

or perhaps:

```js
<template lang="pug">
    //- Register button
    button.fluid.basic.inverted(@click="$emit('switchScreen', 'register')")
</template>
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
You can simply use $emit in templates: 
@click="$emit('switchScreen', 'register')"

**Comment by A1vinSmith** [comment]
`@click="val => $emit('switchScreen', val)"`

**Comment by neospeed83** [comment]
When I emit events inline like both of the comments above suggested, when unit testing these emit events, I was unable to see any events being fired. But when I moved the `this.$emit('eventName')` to a method and called the method in `@click="methodName('eventName')` I was able to test is properly. Any reason why this is happening?
