### ISSUE TITLE
ios第一次打开一个新的评论页面，input输入框无法获取焦点，而页面后退时，软盘又不能消失！

### ISSUE THREAD

**Issue by linklin7** [vuejs/vue#4194]
我做的是移动端的项目，使用vue-router组件。
问题描述：
打开一个页面展示详情信息，底部有一个“评论”的按钮，点击该按钮打开“评论”组件页面，第一次打开input输入框无法自动获取焦点，后退页面再点击该按钮，input输入框才能自动获取焦点（输入法软盘调起），而这时不做任何输入，直接后退回到详情信息页面，出现软盘不能自动消息。

评论组件里已在mounted方法中，触发focus事件。同时在beforeDestroy、destroyed方法里触发input的blur事件。

求解决!

### Vue.js version
2.0.5

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！
