### ISSUE TITLE
 v-on:keyup.enter is not working on korean character(2bytes)

### ISSUE THREAD

**Issue by vingorius** [vuejs/vue#4196]
### Vue.js version
2.0.2

### Reproduction Link
[https://jsfiddle.net/vingorius/yLqutdg5/5/](https://jsfiddle.net/vingorius/yLqutdg5/5/)

### Steps to reproduce

- On input field, i enter korean character, for example '안녕', and 'Enter' key down .
- It does not invoked, but i enter english words 'Hello', and 'Enter' key down.
- It works. 

### What is Expected?
inputEnter function is invoked
### What is actually happening?
Nothing.

### Run Env.
Firefox 49.0.2 on Ubuntu 16.04

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. By `expire` do you mean `called` or `invoked`?
If I copy the Korean characters into the input field, and press "enter" key, the `inputEnter` method is called. 
Please check if you have custom IME programs that are interfering with keyboard input.

**Comment by vingorius** [comment]
@fnlctrl  right. I changed it. Thanks.
