### ISSUE TITLE
使用vuejs，window.open(url)，传参

### ISSUE THREAD

**Issue by VmLia** [vuejs/vue#4197]
场景：
A.html是列表页面，A.html 有事件，激活window.open(B.html);
请问：
如何将A.html的信息传递到B.html

**Comment by fnlctrl** [comment]
![image](https://cloud.githubusercontent.com/assets/5557143/20260654/a2757900-aa95-11e6-99a0-7c7856451f8a.png)

-----------------

跨页面传参是框架无关的
