### ISSUE TITLE
 If the parent component of the class attributes to all sub-components, how to do it?

### ISSUE THREAD

**Issue by dongyang03** [vuejs/vue#4199]
For example, react in "React.Children.map"

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
