### ISSUE TITLE
v-else issue

### ISSUE THREAD

**Issue by Mat-Moo** [vuejs/vue#4201]
### Vue.js version
2.0.5

### Reproduction Link
https://jsbin.com/wexurugeje/edit?html,js,console,output

### Steps to reproduce
Run jsBin

### What is Expected?
Expecting to see
HTML conten 1
Hello content 1
HTML content 2
Hello content 2

### What is actually happening?
As soon as the v-else is hit, all other out put is terminated, e.g. if you move the "Hello content 1" block to the top of the list, it only shows that and terminates.

**Comment by defcc** [comment]
There is something wrong with your template .  </block-xxx> should be </block-xxx1>
