### ISSUE TITLE
Strange default props(Object/Array) behavior when watcher it.

### ISSUE THREAD

**Issue by Clunt** [vuejs/vue#4203]
### Vue.js version
2+

### Reproduction Link
https://jsfiddle.net/55sbet10/2/

### Steps to reproduce / What is actually happening?
- Refresh window: Click Demo1 `Click diff` button, will alert;
- Refresh window: Click Demo1 `Click same` button, will not alert;
- Refresh window: Click Demo2 `Click same` button, will not alert;
- Refresh window: Click Demo2 `Click same` button, will not alert;

## 中文
props属性未传递时，不同方式返回默认值导致watch表现奇怪。

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. You're not supposed to return an already created object for props, as it will be shared across all instances.

**Comment by Clunt** [comment]
@fnlctrl 我应该是没有表达清楚，目前的状况是watcher会莫名被调用。唯一的区别是一个返回全局的default props，另外一个是每次单独创建。单独创建的属性被watch时，会被莫名调用

**Comment by yyx990803** [comment]
This is already fixed in 2.0.5... your fiddle is using an 2.0-beta.x version.
