### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by rwatts3** [vuejs/vue#4206]
Greetings, 

First and foremost I believe Vue is a revolutionary framework. I have just started working with Vue and see great potential in the way we build applications for the future. With that being said I believed one of the many things that has helped frameworks like React, Angular, and Polymer grow so rapidly is a clear and concise direction on how to build, publish and distribute "Components" and "Component Libraries" not necessarily Applications or SPAs. Although the webpack setup has great configuration for distributing your application, I have been able to find a seamless webpack setup that offers the same publishing/testing capabilities as the Vue templates.

I believe if clear directions on vuejs.org and/or configuration settings in the webpack/browserify templates also included publishing a single component or component library this could be the igniter to the rocket that set's Vue on an even higher level than other frameworks.

Kind Regards, 

Ryan W.

**Comment by yyx990803** [comment]
Thanks for the suggestion! Moved to https://github.com/vuejs/vuejs.org/issues/585

**Comment by rwatts3** [comment]
Thank you Evan.

My apologies didn't realize there was a repo for the site.
