### ISSUE TITLE
v-bind:style= "[condition ? {styleA} : {styleB}]"  use inside the v-for is unexpected?

### ISSUE THREAD

**Issue by ringcrl** [vuejs/vue#4210]
I want to add some inline-style to every img label,but need some judge...

<img width="1362" alt="qq20161116-1 2x" src="https://cloud.githubusercontent.com/assets/16740021/20334033/f543d78c-abf1-11e6-8735-847e878c698f.png">

My data structure is like that...

![qq20161116-1](https://cloud.githubusercontent.com/assets/16740021/20334062/38c96512-abf2-11e6-8573-1d60163281e1.png)

but the result is unexpected

![qq20161116-0](https://cloud.githubusercontent.com/assets/16740021/20334070/4bc4488a-abf2-11e6-97fe-498f04138e9d.png)

**Comment by yyx990803** [comment]
Your width and height are strings...

```
'1080' < '400' // true
```

**Comment by ringcrl** [comment]
😯...

一语道破，期待周五的 StuQ 大神直播会~

还有那个知乎 Live ~
