### ISSUE TITLE
浏览器自动填写的表单的数据，vue无法获取到数据。

### ISSUE THREAD

**Issue by panwenhua** [vuejs/vue#4211]
浏览器自动填写的表单的数据，vue无法获取到数据。
浏览器保存帐号密码了，并且表单做了非空验证。
等第二次再进入登陆界面时，无法获取到帐号密码，可是明明input框上有数据，只不过是浏览器填的。

**Comment by yyx990803** [comment]
这属于浏览器的非规范行为，各个浏览器行为不一，Vue 不可能一一对应处理的。通常这些密码是在 Vue 初始化完毕后才被填入的，密码被填入后手动触发一遍 input 框的 input 事件即可。
