### ISSUE TITLE
v-model doesnt bind data to component when used on router-view

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4213]
this is my code for Login Form

it doesnt work with v-model directive 

<template>
    <form class="form" role="form" v-csrf @submit.prevent='submitForm'>
        <div class="form-group">
            <input type="email" class="form-control" name="email" v-model="email" placeholder="Email"> 
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="password" v-model="password" placeholder="Password"> 
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-info btn-block"> Login </button>
        </div>
    </form>
</template>

```
`<script>
    export default {
        
        data() {
            return {
                errors: [],
                    email: '',
                    password: '',
            }
        },
        
        methods: {
            submitForm() {
                this.axios.post('/login',[this.email,this.password])
                    .then(response => {
                        console.log(response.data);
                    })
                    .catch(response => {
                        console.log(response.data);
                    })
            }
        }
    }
`</script>``
```

**Comment by fnlctrl** [comment]
Hi, please open this issue at vue-router's repo, with a reproduction on jsfiddle/codepen/etc. Thanks!
