### ISSUE TITLE
Inputing anything in an input managed via a computed property makes it lose its focus when those inputs are generated by `v-for`

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue#4215]
Using v2.0.6, I have two inputs, `year` and `month` where when I enter a number in one input, the other one gets calculated automatically.
This works great by using one `computed` property ;
```js
data() {
	return {
		dataObj : {
			months : 24,
		}
	}
},

computed: {
	years : {
		get() {
			let unRoundedResult = this.dataObj.months / 12;
			return Number(unRoundedResult.toFixed(2));
		},
		set(newValue) {
			this.dataObj.months = Math.round(newValue * 12);
		}
	},
}
```
and the html :
```html
<input type="text" v-model.number="years">
<input type="text" v-model.number="dataObj.months">
```
You can see that in action working correctly on [this codepen](http://codepen.io/AnotherLinuxUser/pen/YpGVjP?editors=1010).

However, I encounter a problem when I generate those inputs via a `v-for` loop ; in this case, whenever I enter a number into the `year` or `month` input, I lose focus and need to click back into the input to continue editing it (cf. [this other codepen](http://codepen.io/AnotherLinuxUser/pen/WoxXzm?editors=1010)).

As this annoying behavior is not happening when I'm not using a `v-for` loop, I tend to think this is a bug.

If I'm wrong, would you see why the focus is lost there?

Note : If I use the mouse wheel to change those input values *(note :  the mouse wheel events only works under Chrome for some unknown reasons)*, everything works as intended. Also, if I modify only the decimal part of the year (so that the calculated value for the months do no change), I do not lose focus.

*note; this question has first been asked on Gitter then on the [forum](https://forum.vuejs.org/t/entering-anything-in-an-input-makes-it-lose-its-focus/3000).*

**Comment by HerringtonDarkholme** [comment]
Confirmed, when adding `:key` to an input will reproduce this problem.

For workaround now you can remove the `:key`. I'll give it a look.

**Comment by LinusBorg** [comment]
Totally missed that key prop. Good eye @HerringtonDarkholme , thanks

**Comment by AlexandreBonneau** [comment]
Thank you @HerringtonDarkholme , I missed that too obviously!
