### ISSUE TITLE
Repeated inline-template within v-if is wrongfully reused

### ISSUE THREAD

**Issue by guidobouman** [vuejs/vue#4216]
### Vue.js version
2.0.6 (latest)

### Reproduction Link
http://codepen.io/guidobouman/pen/qqajGr

### Steps to reproduce
Repeat a conditional (v-if, not v-show) check with an `inline-template` component inside.

### What is Expected?
When changing the value, the conditional check should display the right child component. Which in turn displays it's own `inline-template` with the unique value.

### What is actually happening?
The first time a value (for the v-if) is selected, the right `inline-template` is being used. When you change the value afterwards the inline-template from the first value is being re-used each time.

### Additional info
When none of the conditional checks hit (by selecting the value 0), the state is reset. The next matching value that's selected will display the correct value again.

So: As long as one of the conditional checks matches, the template is not being reset.

**Comment by guidobouman** [comment]
Temporary workaround:
```js
  export default {
    props: [ 'subject' ],
    data() {
      return {
        subjectProxy: this.subject,
      }
    },
    computed: {
      selectedSubject: {
        get() {
          return this.subjectProxy
        },
        set(value) {
          if(this.subjectProxy == value) {
            return;
          }

          this.subjectProxy = '';
          this.$nextTick(() => {
            this.subjectProxy = value;
          })
        }
      }
    }
  };
```

**Comment by defcc** [comment]
Thanks @guidobouman, I'll take a look.

**Comment by LinusBorg** [comment]
key the dynamic components accordingly:

`<div is="child" inline-template  :key="value">`

**Comment by guidobouman** [comment]
@LinusBorg Thanks for getting back to me.

Does the key work even when not using a `v-repeat`? Then I think this should be explained in the conditionality section of the docs (https://vuejs.org/v2/guide/conditional.html.)

**Comment by guidobouman** [comment]
`v-for` in the api has a reference to `key` in it's `see also:` section. Adding this reference to `v-if` in addition to the guide would make it even clearer.

**Comment by yyx990803** [comment]
@guidobouman yep, we are working on it, thanks for the suggestion!

**Comment by LinusBorg** [comment]
Further discussion of docs improvement on this topic here: vuejs/vuejs.org#587
