### ISSUE TITLE
Request: add '_scopeId' to type definition of ComponentOptions

### ISSUE THREAD

**Issue by bartsidee** [vuejs/vue#4218]
We are using pre-compiled templates to be CSP compatible but do like to segment our TS code from the *.vue template files. 

As a result we are pre-compiling our templates with web-pack and importing them into typescript using the below pattern (basically copying the render functions and injecting them into the new TS component)

```
let template = require("./sample-component.vue");
@Component({
  render: template.render,
  staticRenderFns: template.staticRenderFns,
})
export default class SampleComponent extends Vue {
}
```

Some of our components are using scoped scss logic though and we would like to pass down the scopeId as well. Like so:

```
let template = require("./sample-component.vue");
@Component({
  render: template.render,
  staticRenderFns: template.staticRenderFns,
  _scopeId: template._scopeId
})
export default class SampleComponent extends Vue {
}
```

ES6 version
```
import template from './sample-component.vue'
export default Vue.extend({
  _scopeId: template._scopeId,
  render: template.render,
  staticRenderFns: template.staticRenderFns,
})
```

This is working fine in ES6, but is not working due to the missing '_scopeId' type property in the vue type definition found here:
https://github.com/vuejs/vue/blob/dev/types/options.d.ts

Would it be possible to add _scopeId to the ComponentOptions definition interface?

Vue.js: 2.0.6

**Comment by HerringtonDarkholme** [comment]
scopId is an implementation detail. And it is not documented in official doc either. I wonder whether we should rely on the private API.

But you can always augment TypeScript definitioin, though
https://github.com/HerringtonDarkholme/av-ts/wiki/FAQ#3-componentmeta-augmentation

**Comment by bartsidee** [comment]
thank you! augment the definition resolved the issue for us.

Agreed that it is not ideal to use a private API, it would be great to find a better way to precompile templates that do not include the component JS/TS. 

For us it is mainly that we want to JS/TS code to be leading. (prevent mixed imports from JS -> Vue template -> JS)

**Comment by yyx990803** [comment]
Closing since the issue can be resolved in userland. And yeah we probably don't want to expose private APIs in the official type definitions.
