### ISSUE TITLE
为什么vuejs 项目中的input框在苹果手机上无法输入

### ISSUE THREAD

**Issue by y-xin** [vuejs/vue#4219]
出现的问题：
    项目在苹果手机浏览器上访问，input输入框能调起苹果输入法，但是没法输入，
    就是简单的写一个input框，不绑定v-model 也没法输入 。button按钮也点不了。
    使用vue-cli 构建的。
    但是去掉所有js单纯一个html 页面却又可以。
    请问要怎么解决。

**Comment by fnlctrl** [comment]
请使用jsfiddle/codepen/jsbin提供重现。

**Comment by y-xin** [comment]
谢谢，问题已解决。并非js 问题， 而是样式表中加了 -webkit-user-select:none; 属性。
