### ISSUE TITLE
template event handler bind with vue prototype method

### ISSUE THREAD

**Issue by ije** [vuejs/vue#4220]
when i try to bind an event handler in template without `()` using vue prototype method, the handler scope will be not a valid Vue instant. but the instant method is ok.

```html
<a href="#" @click="foo">foo</a>
<a href="#" @click="foo()">foo()</a>
```

with
vue 2.0.5

example see:
https://jsfiddle.net/ijex/1mj4xgd1/6/

**Comment by deohnas** [comment]
Well, I may be out of scope here (I'm new to JavaScript) but it looks like when you call just simply foo, you'll return the function/method as a string, and when called (it does not really belong / have any connection to the instance anymore).

This can be proved by this fiddle: https://jsfiddle.net/Lr7sen97/8/

We call the `foo.hello()` and it alerts the function. There after we assign the foo.hello to the bar and then call bar, as you can see it returns undefined.

This could _maybe_ be solved by conditionally check if `foo` exists in the Vue instance and if so, call it. 
From my naive example above:
`foo[func]();`
https://jsfiddle.net/4y0wcavc/1/

**Comment by ije** [comment]
@deohnas thanks! i'm new to the javascript too. you example is perfectly clear. 
i think using object's method as a event handler is a terrible way.
