### ISSUE TITLE
if list instance referred by link then  list does not cleared 

### ISSUE THREAD

**Issue by MaksimSkomorokh** [vuejs/vue#4221]
if list instance referred by link then can't clear list

### Vue.js version
2.0.6

### Reproduction Link

http://jsfiddle.net/apokjqxx/23/

### Steps to reproduce
Click to clear button.

### What is Expected?
List should be cleared.

### What is actually happening?
List doesn't cleared

**Comment by defcc** [comment]
Thanks @MaksimSkomorokh . It's a expected behavior,  because the component's list data is not changed when you make an assignment to the list inside another function.

**Comment by yyx990803** [comment]
`list = []` doesn't do anything, because `list` is a local variable binding, not a reference.

**Comment by MaksimSkomorokh** [comment]
Interesting... If delete item from list then it's works fine
http://jsfiddle.net/apokjqxx/26/
