### ISSUE TITLE
dynamic props do not update when using keep-alive

### ISSUE THREAD

**Issue by rjoo** [vuejs/vue#4222]
### Vue.js version
2.0.6

### Reproduction Link
https://jsfiddle.net/116nxpd8/

### Steps to reproduce
Switch components & increment number multiple times.

### What is Expected?
The `number` prop to stay consistent between all components.

### What is actually happening?
The `number` in component A stays stale and does not reflect the parent's `number` although it's a dynamic prop.

One hacky workaround I'm having to use is to force the change by changing the number twice on nextTick. I would be really surprised if this is the intended behavior with keep-alive.

**Comment by rjoo** [comment]
Ugh. Incrementing number on nextTick fixes this. Closing.

**Comment by Mupati** [comment]
how you go about with implementing the nextTick. facing similar problem when passing the prop with vue router and using keep-alive on the router-view

**Comment by rjoo** [comment]
Whatever you are updating, wrap it in a nextTick callback arg. Eg. `this.$nextTick(() => { this.number++; })`
