### ISSUE TITLE
$emit can't bubbling to parents module

### ISSUE THREAD

**Issue by santinoDu** [vuejs/vue#4228]
I have three vue file as a.vue, b.vue, c.vue.
In a.vue template:
`<b-view @closeTest="closeHandle"></b-view>`

In b.vue template:
`<c-view></c-view>`

In c.vue template:
`<div @click="close"></div>`

c.vue script:
`close () {
     this.$emit('closeTest')
}`

when I click div in c.vue, a.vue closeHandle can't be trigger,
 I must write a medium method in b.vue to trigger closeHandle in a.vue.
Is it necessary to write a medium in b.vue or have some way to trigger closeHandle?

### Vue.js version
2.0.2

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Event's don't bubble up in vue 2.0, you'll have to manually re-emit it all the way up, or use vuex. A [event hub](https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced) pattern may also help in this case.
