### ISSUE TITLE
Hot Module Replacement on chrome apps

### ISSUE THREAD

**Issue by trendy-weshy** [vuejs/vue#4229]
Hey,

How can I perform hot module replacement using webpack and vue-loader when am developing a chrome application or a chrome extension ?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, so please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions. Thanks!
