### ISSUE TITLE
Did anyone had success using Vue with Datatables?

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#423]
The initial rendering works but if I try to use datatables search or pagination it shows me a table row with the uncompiled repeat directive

**Comment by davidkhess** [comment]
For anybody else who stumbles across this, my approach to integrating DataTables looks like this:

1) Create a simple DataTables component that creates a DataTables instance on the component's DOM.
2) Provide from the model via props an `options` object used to initialize the DataTables instance so that you can configure it from the model.
3) Via props, provide the component with a `data` prop that's used to provide an array to the DataTables instance. Use a watch on this property to reload the table as needed.
4) Via props provide a writable object to the component where status information is written by the component (such as which rows are selected, is one row selected, are multiple rows selected, etc.).

This isn't that hard to accomplish and tends to be enough to do the trick in most cases.

**Comment by amndplz** [comment]
davidkhess can you post some example code to help with this issue?

**Comment by davidkhess** [comment]
This has some dependencies (such as lodash) and some personal design decisions, but you get the idea:

```
Vue.component("data-tables", {
    "props": [ "options", "status", "data" ],
    "template": "<table></table>",
    "ready": function () {
        var self = this;

        var default_options = {
            "dom": '<"uk-hidden"T>lfrtp',
            "paging": false,
            "tableTools": {
                "sRowSelect": "os",
                "aButtons": [ "select_all", "select_none" ],
                "fnRowDeselected": function (nodes) {
                    self.selection_changed();
                },
                "fnRowSelected": function (nodes) {
                    self.selection_changed();
                }
            }
        };

        _.assign(default_options, self.options);
        self.options = default_options;

        self.data_table = $(self.$el).DataTable(self.options);
        self.$set("status.one_row_selected", false);
        self.$set("status.one_or_more_rows_selected", false);
        self.$set("status.selection", []);

        self.load_data();

        self.$dispatch("data_tables_ready", self);
    },
    "watch": {
        "data": {
            "handler": function (value, old_value) {
                var self = this;
                self.load_data();
            },
            "immediate": true
        }
    },
    "methods": {
        "load_data": function () {
            var self = this;

            if (_.isUndefined(self.data) || _.isUndefined(self.data_table)) {
                return;
            }

            self.data_table.clear().rows.add(self.data).draw();
        },
        "selection_changed": function () {
            var self = this;
            var table_tools = TableTools.fnGetInstance(self.data_table.table().node());
            var nodes = table_tools.fnGetSelected();
            self.status.one_row_selected = nodes.length == 1;
            self.status.one_or_more_rows_selected = nodes.length >= 1;
            self.status.selection = table_tools.fnGetSelectedData();
        }
    }
});
```

**Comment by redabakr** [comment]
You can use the following approach: 
`methods:{
GetData:function(){
 // Logic Here
// Initialize DataTable
setTimeout(function() { $("#datatableId").DataTable(); }, 1000);
}
}`

**Comment by Djagannath** [comment]
you can try this 

HTML
    <input type="button" class="btn btn-success" value="Get data" v-on:click="getData">
    <datatable :data="dataTable" :columns="tableColumns"></datatable> 

SCRIPT

<script>
    var dataTableResult = [];
    var Columns = [];
    var vm = {};
    
    Columns = [
        { title: "articul", mData: "articul" }, 
        { title: "img", mData: "img" },
        { title: "price", mData: "price" },
        { title: "retail", mData: "retail" },
        { title: "wholesale", mData: "wholesale" },
        { title: "amount", mData: "wholesale_amount" },
        { title: "discount", mData: "discount" },
        { title: "dateAdd", mData: "dateAdd" },
    ];
    
    $(document).ready(function() {
        vm = new Vue({
            el: "#app",
            data: {
                dataTable: dataTableResult, 
                tableColumns: Columns, 
                articul: '',
                price: '',
                retail: '',
                wholesale: '',
                discount: '',
            },
            methods: {
                getData: function() {                
                    var dataResult = 
                    $.post('/admin/ajax_get_test')
                    
                    dataResult.done(function(data){
                        dataTableResult = JSON.parse(data);
                        vm.dataTable = dataTableResult;
                    });                                      
                }
            }
        });
        
        $('#table tbody').on( 'click', 'tr', function () {
            
            var table = $('#table').DataTable();
            var data = table.row(this).data();
            
            if( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
            
            vm.articul = data.articul;
            vm.price = data.price;
            vm.retail = data.retail;
            vm.wholesale = data.wholesale;
            vm.discount = data.discount;    
        } );
    });
          
    var TagDataTable = {};
    TagDataTable.install = function(Vue, options) {
        'use strict';

        Vue.component('datatable', { 
            name: 'datatable',
            template: '<table id="table" class="display" v-on:click="getDataFromTD"></table>', 
            props: ['data', 'columns'], 
            watch: { 
                data: {
                    handler: function(val, oldVal) { // data changed
                        this.DataTable.fnClearTable(); 
                        this.DataTable.fnAddData(val); 
                    },
                    deep: true 
                }
            },
            mounted: function() { // when the plug-in is ready
                this.DataTable = $('#table').dataTable({
                    data: this.data,
                    columns: this.columns 
                    /*[  You can specify explicitly or through a variable
                        { title: "articul", mData: "articul" }, 
                        { title: "img", mData: "img" },
                        { title: "price", mData: "price" },
                        { title: "retail", mData: "retail" },
                        { title: "wholesale", mData: "wholesale" },
                        { title: "wholesale_amount", mData: "wholesale_amount" },
                        { title: "discount", mData: "discount" },
                        { title: "dateAdd", mData: "dateAdd" },
                    ]*/
                })
            }
            }
        });
    };//---/ Create a new plug-in
    
    // turn plug
    Vue.use(TagDataTable);

//  to download table for default data
//    dataTableResult = [
//        {articul: "00001", dateAdd: "2016-07-01", discount: "180", group_id: "1", img: "https://pp.vk.me/c406331/v406331779/908c/w1afdu2hHFs.jpg",  price: "100", product_id: "1", retail: "200", viewing: "0", visible: "1", wholesale: "150", wholesale_amount: "10"}
//    ];
</script> sorry for my English =)

**Comment by guanzo** [comment]
I managed to programmatically mount a vue component to an element, as well as pass props, can anyone tell me if this is an appropriate strategy? It seems to work.. The components don't show up in the vue dev tools, but that's not a big deal.


datatables provides a callback function "createdCell", which allows you to manipulate the cell html.

Here's my code:

ApplicabilityIcon is a .vue file.

```
import Vue from 'vue'
import ApplicabilityIcon from '@/components/partsplanning/customer/parts/ApplicabilityIcon'
Vue.component('appl-icon',ApplicabilityIcon)
```


```
//cell is a node
createdCell:(cell,data,rowData)=>{
	var ApplIcon = Vue.component('appl-icon')
	new ApplIcon({
		propsData:{
			material: rowData.product.material,
			hasAppl: rowData.product.hasAppl
		}
	}).$mount(cell)
 }
```

**Comment by bseib** [comment]
If you land here after googling for Vue + DataTables, here is another approach I found that works.

Use Vue just to render the `<table>` once using a non-observable list variable. Then hand over the `<table>` to DataTables and only use the DataTables calls to alter the data after that.

```
created: function() {
  // non-observable vars can go here
  this.dataTable = null;
  this.persons = [];  // v-for will iterate on this one time only
  this.init();
},

methods: {
  init: function() {
     this.persons = getTheData();
  }
}
```

Here's a gist with more detailed code: https://gist.github.com/bseib/bb4ea32731376318a545d527752f88a1

**Comment by antho1jp** [comment]
I have a slightly different approach that worked for me. I'll leave it here in case it helps someone else. This solution is in a .vue file of a SPA. My data is a JSON feed from an api using axios. I also needed to manipulate the date format using moment timezone for display.

`
import axios from 'axios';
import jquery from 'jquery';
require('@/assets/js/plugins/DataTables/datatables.js')
require('@/assets/js/plugins/DataTables/datatables.css')
moment().tz("America/Los_Angeles").format();

export default {
        name: "componentName",
        data() {
            return {
                lists: [{
                    id: 0,
                    SentFile: "",
                    DTSent: ""
                }]
            }
        },
       methods: {
            moment: function () { return moment() }
        },
       mounted(){
            axios
                .get('pathToApiEndPoint', {
                    crossdomain: true,
                    headers: {
                        'authorization': "Bearer " + token,
                        'Content-Type': 'application/json'
                    }
                })
                .then((response) => {
                    let self = this;
                    this.lists = response.data.map(function (item) {
                        return {
                            "Name": moment(item.DTSent).format('dddd, MMMM Do YYYY, h:mm:ss a'),
                            "Download": '<a href="item.downloadLink" download="listName">Download</a>'
                        }
                    })
                    jquery('#listTable').DataTable({
                        data: this.lists,
                        columns: [
                            { "data": "Name" },
                            { "data": "Download" }
                        ]
                    });
                })    
       }
`

**Comment by iberastegui** [comment]
> I have a slightly different approach that worked for me. I'll leave it here in case it helps someone else. This solution is in a .vue file of a SPA. My data is a JSON feed from an api using axios. I also needed to manipulate the date format using moment timezone for display.
> 
> ```
> import axios from 'axios';
> import jquery from 'jquery';
> require('@/assets/js/plugins/DataTables/datatables.js')
> require('@/assets/js/plugins/DataTables/datatables.css')
> moment().tz("America/Los_Angeles").format();
> 
> export default {
>         name: "componentName",
>         data() {
>             return {
>                 lists: [{
>                     id: 0,
>                     SentFile: "",
>                     DTSent: ""
>                 }]
>             }
>         },
>        methods: {
>             moment: function () { return moment() }
>         },
>        mounted(){
>             axios
>                 .get('pathToApiEndPoint', {
>                     crossdomain: true,
>                     headers: {
>                         'authorization': "Bearer " + token,
>                         'Content-Type': 'application/json'
>                     }
>                 })
>                 .then((response) => {
>                     let self = this;
>                     this.lists = response.data.map(function (item) {
>                         return {
>                             "Name": moment(item.DTSent).format('dddd, MMMM Do YYYY, h:mm:ss a'),
>                             "Download": '<a href="item.downloadLink" download="listName">Download</a>'
>                         }
>                     })
>                     jquery('#listTable').DataTable({
>                         data: this.lists,
>                         columns: [
>                             { "data": "Name" },
>                             { "data": "Download" }
>                         ]
>                     });
>                 })    
>        }
> ```
i made something like your answer, but with 3k+rows it already takes 7 seconds, does anybody knows how to datatable+vue2+spa?
because making a vfor in the tr and filling the for with an axios call and then initializacion jquery dattable clinet side is not the answer for huge amounts of records.

**Comment by antho1jp** [comment]
Here is what I have been doing with large datasets:
```
var $ = require('jquery');
require( 'datatables.net-bs' );
require( 'datatables.net-buttons-bs' );
require( 'datatables.net-buttons/js/buttons.print.js' );
require( 'datatables.net-responsive-bs' );
require( 'datatables.net-scroller-bs' );
require('datatables.net-select-bs');

//data section
data(){
    return {
         lists: []
    }
}

// mounted section
mounted() {    
     this.buildDataTable();
     this.getData();
},

// methods section
methods: {
     async getData() {
         try{
           let response = await axios.get('pathToApiEndPoint', {
                    crossdomain: true,
                    headers: {
                        'authorization': "Bearer " + token,
                        'Content-Type': 'application/json'
                    }
             });
            this.lists = response.data.map(function (item) {
                        return {
                            "Name": moment(item.DTSent).format('dddd, MMMM Do YYYY, h:mm:ss a'),
                            "Download": '<a href="item.downloadLink" download="listName">Download</a>'
                        }
             });
            
            // now add the data to the table and update the view
            this.updateTable();
         } catch(err){
              console.log(err);
         }
     },
     updateTable() {
          this.table.clear().draw(); // clear the table
          this.table.rows.add(this.lists).draw(); // adding data through DataTables api
          this.table.columns.adjust().draw(); // redraw with data
          this.table.responsive.recalc(); // ensure responsive settings are recalculated
       },
      buildDataTable() {
          if (!$().dataTable) { return; } 
          this.table =  $('#dataTable').DataTable({ // options here with no data loaded
                    "deferRender": true,
                    "autoWidth": false,
                    "processing": true,
                    "responsive": {
                        breakpoints: [
                            { name: 'desktop', width: Infinity },
                            { name: 'tablet',  width: 1024 },
                            { name: 'fablet',  width: 768 },
                            { name: 'phone',   width: 480 }
                        ]
                    },
                    //data: payload, normally you load your data on init but here I remove this prop
                    "order": [[0, "desc"]],
                    "columns": [
                        { data: "Name" },
                        { data: "Download" },
                    ],
                    "lengthMenu":[[10, 25, 50, 100], [10, 25, 50, 100]],
                    dom: 'lBfrtip', // allow buttons usage
                    buttons: [ // I have some buttons for exporting the data to excel and print abilities here ]
              })              
      }
}
```
Using this way you can use this.updateTable() in any observable section or after an asynchronous function.

I am using this method for over 60k records and it loads extremely fast.

**Comment by antho1jp** [comment]
> > I have a slightly different approach that worked for me. I'll leave it here in case it helps someone else. This solution is in a .vue file of a SPA. My data is a JSON feed from an api using axios. I also needed to manipulate the date format using moment timezone for display.
> > ```
> > import axios from 'axios';
> > import jquery from 'jquery';
> > require('@/assets/js/plugins/DataTables/datatables.js')
> > require('@/assets/js/plugins/DataTables/datatables.css')
> > moment().tz("America/Los_Angeles").format();
> > 
> > export default {
> >         name: "componentName",
> >         data() {
> >             return {
> >                 lists: [{
> >                     id: 0,
> >                     SentFile: "",
> >                     DTSent: ""
> >                 }]
> >             }
> >         },
> >        methods: {
> >             moment: function () { return moment() }
> >         },
> >        mounted(){
> >             axios
> >                 .get('pathToApiEndPoint', {
> >                     crossdomain: true,
> >                     headers: {
> >                         'authorization': "Bearer " + token,
> >                         'Content-Type': 'application/json'
> >                     }
> >                 })
> >                 .then((response) => {
> >                     let self = this;
> >                     this.lists = response.data.map(function (item) {
> >                         return {
> >                             "Name": moment(item.DTSent).format('dddd, MMMM Do YYYY, h:mm:ss a'),
> >                             "Download": '<a href="item.downloadLink" download="listName">Download</a>'
> >                         }
> >                     })
> >                     jquery('#listTable').DataTable({
> >                         data: this.lists,
> >                         columns: [
> >                             { "data": "Name" },
> >                             { "data": "Download" }
> >                         ]
> >                     });
> >                 })    
> >        }
> > ```
> 
> i made something like your answer, but with 3k+rows it already takes 7 seconds, does anybody knows how to datatable+vue2+spa?
> because making a vfor in the tr and filling the for with an axios call and then initializacion jquery dattable clinet side is not the answer for huge amounts of records.

In the method I described above the data is loaded into the table not with a V-For but with a DataTables "data" prop during initialization.

```
jquery('#listTable').DataTable({
    data: this.lists, // here is where the data was loaded
    columns: [
        { "data": "Name" },
        { "data": "Download" }
    ]
});
```
If you are using a V-for in the 'tr' tag that is going to be slow and in most cases break the DataTables sorting and searching.

Another way to do it is you init (build) your dataTable with empty data on mount. Then you use the DataTables api to add data. In my example above I was doing both at the same time.

Here is another way:

```
    var moment = require('moment-timezone');
    moment().tz("America/Los_Angeles").format();
    var $ = require('jquery');
    require( 'datatables.net-bs' );
    require( 'datatables.net-buttons-bs' );
    require( 'datatables.net-buttons/js/buttons.print.js' );
    require( 'datatables.net-responsive-bs' );
    require( 'datatables.net-scroller-bs' );
    require('datatables.net-select-bs');
    import { sortByDateFormat } from '@/assets/datatable-datetime-sorting.js';
    import { dataToDownload } from '@/controllers/prospects_api.js';

    export default {
        name: "dataTableExample",
        data() {
            return {
                tableData: [],
                table: null,
            }
        },
        mounted() {    
            sortByDateFormat('M/D/YYYY'); // using the date sorting plugin in another file exported
            this.getData(); // use axios async to get data from server then update table view
        },    
        methods: {  
            clearTable: function () {
                console.log('clear table');
                this.table.clear().draw();
                this.tableData = [];
            },
            updateTable() {
                this.table.clear().draw();
                this.table.rows.add(this.tableData).draw();
                this.table.columns.adjust().draw();
                this.table.responsive.recalc();
            },
            async getData() { // this gets the data that is filtered using datatables search for exporting
                try {
                    let response = await axios.get('path to api call');
                    this.tableData = response.data;
                    this.updateTable();
                } catch (err) {
                    console.log(err);
                }
            },
            buildDataTable() {
                var table = $('#dataTable');
                var oTable = table.DataTable({
                    "deferRender": true,
                    "autoWidth": false,
                    "processing": true,
                    "responsive": {
                        breakpoints: [
                            { name: 'desktop', width: Infinity },
                            { name: 'tablet',  width: 1024 },
                            { name: 'fablet',  width: 768 },
                            { name: 'phone',   width: 480 }
                        ]
                    },
                    //data: payload,
                    "order": [[0, "desc"]],
                    "columns": [ // whatever columns you need must match your data set
                        { data: "FirstName" },
                        { data: "Middle" },
                        { data: "Lastname" }
                    ],
                    dom: 'lBfrtip',
                    "pageLength": 100,
                    buttons: [                      
                       // can add buttons from API here
                    ]
                });
                if (!$().dataTable) {
                    return;
                }        
                this.table = oTable;
            }
        }
    }
```
