### ISSUE TITLE
vue 2.0 + bootstrap-datepicker 使用v-model取值为空字符串

### ISSUE THREAD

**Issue by 15992033543** [vuejs/vue#4230]
<div id="app">
      <input type="text" id="startDate" v-model="startDate">
      <button type="button" class="btn btn-default" @click="getDate">GET</button>
</div>

var app = new Vue({
      el: '#app',
      data: {
        startDate: '',
      },
      mounted() {
        $("#startDate").datepicker();
      },
      methods: {
        getDate() {
          console.log(this.startDate);// 空字符串
        },
      }
})

使用vue1.0没有问题，望修复

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
