### ISSUE TITLE
Attribute doesn't update if binded to a property called `selected`

### ISSUE THREAD

**Issue by hay** [vuejs/vue#4233]
If you have an element that is binded to an attribute called `selected` it won't update in the DOM. For example:

    <p v-bind:selected="selected">selected is {{selected}}</p>
    <button v-on:click="selected = !selected">toggle</button>

Note that the `{{selected}}` template works fine, and the variable updates as well. It's just the attribute that doesn't update. 

Here's a codepen that reproduces the problem: http://codepen.io/hay/pen/mOOrWK

Problem occurs in Vue 2.0.7. This example works fine in 1.0.28.

**Comment by yyx990803** [comment]
Selected is bound as a property instead of an attribute. P tags don't have selected attribute, why would you want to bind that?

**Comment by hay** [comment]
This is indeed for styling purposes. But why should you be using a class? Attributes can be styled in CSS, and sometimes they're more useful than classes.

**Comment by hay** [comment]
Just checked and the patch in the 2.0.8 fixed this. Thanks so much!
