### ISSUE TITLE
Props can get out of sync on dynamic components with keep-alive

### ISSUE THREAD

**Issue by sebpettersson** [vuejs/vue#4237]
I'm not sure if this is a bug or intended behavior, but if so, maybe this could be clarified in the documentation (and how to go about getting fresh values passed down after coming back from an inactive state).

### Vue.js version
2.0.7

### Reproduction Link

https://jsfiddle.net/ueLxbc0f/3/

### Steps to reproduce
1. Click on Switch component
2. Click Increase value
3. Click on Switch component

### What is Expected?
That the component has its prop updated when coming back from inactive state.

### What is actually happening?
The prop of the component is out of sync with its parent's data.

**Comment by defcc** [comment]
> If you want to keep the switched-out components in memory so that you can preserve their state or avoid re-rendering, you can wrap a dynamic component in a <keep-alive> element:

According to the [docs](https://vuejs.org/v2/guide/components.html#keep-alive),  it should be an expected behavior, that's what keep-alive does.

**Comment by sebpettersson** [comment]
I understand that the state is preserved (like all data in the component), but to me it feels a bit unintuitive that in addition to that, dynamically bound props breaks under these circumstances.

**Comment by simplesmiler** [comment]
It looks like a bug to me. I'd expect the component to be updated when switched in.
