### ISSUE TITLE
The props in a component are not watched properties to render directives

### ISSUE THREAD

**Issue by ArtistNeverStop** [vuejs/vue#4240]
### Vue.js version
2.0.2

**Comment by ArtistNeverStop** [comment]
<template>
	<div class="container">        
		<div class="create-candidate-container hoverable">
			<div class="row">
				<div class="col-md-12">
					<input @keydown.enter="retrive_employee" type="number" v-model="ticket.employee_id">
					<button @click="retrive_employee" class="btn" >Buscar</button>
					{{employee}}
				</div>
				<div class="col-md-12">
					<div class="input-field col s3">
						<input class="validate" type="text" v-model="ticket.description" id="description">
						<label for="name">Descripcion</label>
					</div>
					<div class="input-field col s3">
						<input class="datepicker validate" type="date" v-model="ticket.started_at" id="started_at">
						<label for="started_at">Fecha de Inicio</label>
					</div>
					<div class="input-field col s3">
						<input class="datepicker validate" type="date" v-model="ticket.finished_at" id="finished_at">
						<label for="started_at">Fecha de Fin</label>
					</div>
					<div class="input-field col s3">
						<button @click="generate_ticket" class="btn">Generar Boleta</button>
					</div>
				</div>
				<div class="col-md-12">
					<li v-for="(ticket, index) in tickets">
						<p>{{index}}</p>
					</li>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
		export default {
			props : ['props_tickets'],
			data: function() {
				return {
					tickets: [],
					ticket : {
						description: '',
						started_at: '',
						finished_at: '',
						employee_id: ''
					},
					employee:{
						
					}
				}
			},
			computed:{
			},
			methods:{
				retrive_employee(){
					this.$http.get(`/api/employees/filter/id/${this.ticket.employee_id}`)
					.then((response)=>{
						this.employee = response.body;
					},(response)=>{
						console.log(response.body);
					});
				},
				generate_ticket(){
					this.$http.post(`/vacationTickets/`,this.ticket )
					.then((response)=>{
						this.tickets.push(response.body);
					},(response)=>{
						console.log(response.body);
					});
				}
			},
			mounted() {
				this.tickets  =  this.props_tickets;
     		}
 		}
</script>

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues.
Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
