### ISSUE TITLE
keep-alive activated and deactivated hooks should trigger recursively when toggled

### ISSUE THREAD

**Issue by nothinggift** [vuejs/vue#4242]

**Comment by yyx990803** [comment]
Please be more specific on why you think it should work like that, what use case are you running into that needs this. A single title doesn't qualify as a feature request.

**Comment by nothinggift** [comment]
很抱歉没有做更详细的说明，我们项目中的页面级组件都会带有设置页面meta属性的参数，当页面跳转时会自动设置这些属性，很自然他们是由activated/created来触发的，而在部分嵌套页面里，这个功能失效了，于是我们发现了这个问题。
keep-alive的组件在重新激活时，不会触发子组件的任何事件钩子，这导致在需要刷新子组件时，只能由父组件手动去触发，如果是多级嵌套的组件就会非常繁琐，所以希望keep-alive支持更细粒度的操作。
子组件随父组件activated/deactivated，他们理应触发这些钩子啊。

**Comment by tgustinak** [comment]
I have the same issue. Do you think this will be in next releases?

**Comment by kinglion** [comment]
同样的困惑，假如A跟B两个组件都有keep-alive。他们有共同的组件C，那么A初始化的以后C会执行一次create,B初始化的时候C同样会执行一次create。这时返回A，页面上的C组件不会触发任何生命周期的事件...

**Comment by nothinggift** [comment]
@kinglion keep-alive的子组件目前不触发生命周期事件钩子，需要手动调用，调用方法参考[callHook 方法](https://github.com/vuejs/vue/blob/fce3f04a44073a03eff8e0c1ff4c10d2e4c7751e/src/core/instance/lifecycle.js)

**Comment by kinglion** [comment]
@nothinggift 嗯，这个也是一个hack方法 😊

**Comment by zuibunan** [comment]
> keep-alive的子组件目前不触发生命周期事件钩子，需要手动调用，调用方法参考callHook 方法

这个就太麻烦的，我的页面现在全都是keep-alive的，每个页面根元素是个自己封装的<container>组件，里面加了一些回调，比如动画结束之类的回调事件，如果需要手动去触发子组件的钩子，每个页面都得在activated函数里callHook，这个应该能在每个组件中配置是否触发子组件的钩子

**Comment by kinsliy** [comment]
我也遇到这个问题，谁有解决办法？？请告诉我，thank you

**Comment by Aierui** [comment]
you can remove it.

**Comment by shusiwei** [comment]
keep-alive很难使用，建议事件开发组可以使用采用事件机制

**Comment by huanghuixin1** [comment]
@Aierui How to remove it?

**Comment by cqgsm** [comment]
我的第三级路由组件 ，只能触发deactivated函数， activated不能触发，很奇怪啊，二级路由就都可以触发，下面是子路由插座的写法
<transition name="slide">
            <keep-alive>
                <router-view class="child-view"></router-view>
            </keep-alive>
</transition>

**Comment by zydemail** [comment]
也遇到同样的问题，路由对应的入口组件里边的activated，deactivated钩子触发了，但是入口组件里边引用的子组件的deactivated,activated钩子都没有被触发
