### ISSUE TITLE
v-html binding for <template> is not working

### ISSUE THREAD

**Issue by alarstyle** [vuejs/vue#4243]
### Vue.js version
2.0.7

### Reproduction Link
http://jsfiddle.net/0n8m1akb/2/

**Comment by yyx990803** [comment]
The `<template>` element has special semantics when used in Vue templates, e.g. when used for `v-if`, `v-for` and as a slot container.

What is your use case for this?

**Comment by alarstyle** [comment]
I just wanted to output HTML without wrapping in an extra div.
My structure is something like this:
```html
<div v-for="item in items">
    <template v-if="item.someValue">
          ...
    </template>
    <template v-else v-html="item"></template>
</div>
```

**Comment by yyx990803** [comment]
Unfortunately that's not supported. `v-html` must be used on a normal element because it's just an alias for `innerHTML`, it doesn't make sense for an abstract container like `<template>`.

**Comment by xpader** [comment]
vue 要求必须一个顶层容器的形式我觉得有太多浪费，比如一个 vue-router 的单页应用，页面首先要一个 div 之类的做主容器，然后窗口里放页面也是 vue 实例，这个 vue 页面也要有一个顶层容器，很多非必要的情况下会强制浪费掉两层嵌套。对于常规的DOM树来说，这两层完全无必要。

再比如这里的 v-html 实例，不能使用 template 这种抽象的元素来放，导致必须又得有一个容器存放，某些特殊的情况，会导致浪费三层DOM，想要做到不浪费，即使再怎么精心设计都多多少少还是没法避免这些情况。

我觉得应该想办法改进这些东西。

**Comment by sntran** [comment]
I do have a different use case that I may need it.

I have a custom input component that works with `<datalist>`. As I try to support IE9 (as a polyfill), I need to have my HTML as following:

```html
  <datalist>
      <!--[if lte IE 9]><select><![endif]-->
        <slot ref="options"></slot>
      <!--[if lte IE 9]></select><![endif]-->
    </datalist>
```

The reason for this is because IE9 won't render `<datalist>`, and thus the `<select>` element is needed in IE9. However, as much as I try, I can't find a way to render HTML comment. `v-html` directive seems to be the way to go, but I can't use it on any HTML element.

**Comment by ptflp** [comment]
You can use this, its worked for me in modal, when loading data to body
```html
<template id="some-template">
 <div class="header">
  <slot name="header"></slot>
  <slot name="body"></slot>
  <slot name="footer"></slot>
 </div>
</template>
<div id="app">
 <some>
  <div slot="header" v-html="rawHtmlheader"></div>
  <div slot="body" v-html="rawHtmlbody"></div>
  <div slot="footer" v-html="rawHtmlfooter"></div>
 </some>
</div>
```

**Comment by aebrs** [comment]
Hi,
Using vue.js I need to create an index.vue page for product and people, where number of text box and drop down list are not fixed, I mean some product has 5 props other may have 10.
I tried to add all html element using v-html, but it seems not a wise way.
Some offered to use components, it sounds little complicated or confusing.
I am looking for a sample or good example.
Thanks in advance.

**Comment by hirokiosame** [comment]
Couldn't this be potentially implemented by inserting a comment node where you do a `replaceWith`?

**Comment by HaseenaArafath** [comment]
Hi,

In my case, I am replacing a link on top of paragraph element using v-html 

Please find the code snippet as follows

    <p v-html="websiteHTML"></p>

where, websiteHTML: '''<a v-bind:href="https://www.google.com/">Google</a>'

The <p> tag is being rendered with Google but doesn't have hyperlink to navigate to https://www.google.com/

Could you please help in finding the error

Thank you

**Comment by mix3d** [comment]
I don't see why we couldn't have a special case where a `<template>` with a `v-html` would replace itself with a text node or the contents of the parsed html in the parent node.

My case I'm trying to replace `<template>{{ computedPropThatHasHtmlCharacters }}</template>` with `<template v-html="computedPropThatHasHtmlCharacters"></template>`, because the former escapes the characters and you get `&amp;` printed to the DOM.

**Comment by dougbrunton** [comment]
> I don't see why we couldn't have a special case where a `<template>` with a `v-html` would replace itself with a text node or the contents of the parsed html in the parent node.
> 
> My case I'm trying to replace `<template>{{ computedPropThatHasHtmlCharacters }}</template>` with `<template v-html="computedPropThatHasHtmlCharacters"></template>`, because the former escapes the characters and you get `&amp;` printed to the DOM.
> 
> I understand that it's a departure from a DOM elements' `innerHtml` though.

@mix3d - I wanted `v-html` in a template for similar reasons, and ended up using a filter that looks like

```
  filters: {
    decodeEntities: function (value) {
      if (!value) return '';
      value = value.toString();
      const parsed = new DOMParser().parseFromString(value, "text/html");
      return parsed.documentElement.textContent;
    }
  },
```

then calling something like `<template>{{ computedPropThatHasHtmlCharacters | decodeEntities }}</template>`

**Comment by jez9999** [comment]
Why on earth did Vue stop supporting the triple-brace syntax for outputting raw HTML?  And then not replace it with any equivalent?  Anyone know?
