### ISSUE TITLE
v-if syntax confusion

### ISSUE THREAD

**Issue by zzz6519003** [vuejs/vue#4245]
```js
  it('v-for', function (done) {
    new Vue({
      el: el,
      template: '<test v-for="n in list" :n="n"></test>',
      data: {
        list: [1, 2, 3]
      },
      components: {
        test: function (resolve) {
          setTimeout(function () {
            resolve({
              props: ['n'],
              template: '{{n}}'
            })
            next()
          }, 0)
        }
      }
    })
    function next () {
      expect(el.textContent).toBe('123')
      done()
    }
  })
```

I think it should be OK if we have
      template: '<test v-for="n in list" n="n"></test>',
omit the ":"

**Comment by fnlctrl** [comment]
`:n` is a shorthand of `v-bind:n`.

**Comment by zzz6519003** [comment]
sorry  I mean 
`template: '<test v-for="n in list" :n="n"></test>'`

@fnlctrl

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
