### ISSUE TITLE
Undefined computed classname keys

### ISSUE THREAD

**Issue by bmaland** [vuejs/vue#4246]
### Vue.js version
2.0.7

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/55/

The classname generator outputs the string 'undefined' instead of an empty string when a computed key is `undefined`. Of course it's possible to avoid this issue in userland, but it would be nice if it was handled in core.

This issue happens mainly in combination with css-modules. The same thing happens in the `classnames` repo: https://github.com/JedWatson/classnames/issues/96. You can check that issue for more details if necessary.

**Comment by defcc** [comment]
Sounds good, however **undefined** is a valid class name, if we add this check, it will be impossible to add an **undefined** class. Maybe it's better to avoid it in userland.

**Comment by yyx990803** [comment]
I think this is better left to userland, as there is really no way to tell whether you really want `"undefined"` or not. The workaround is not that complicated either:

``` js
{
    [cssModule.container || '']: true
}
```

**Comment by bmaland** [comment]
The problem is specifically when the key is `undefined`, the string 'undefined' should still work. I agree that the fix is simple, but it might be worth implementing anyway since this might pop up for other css-modules users in the future

**Comment by yyx990803** [comment]
The problem here is that comouted property names is not a Vue mechanism - it is a JS language feature. The result of evaluating that code is always going to end up with the string "undefined" before Vue can even do anything.
