### ISSUE TITLE
Feature request: allow to acess to the modifier for v-on when bound to functional component

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue#4248]
It would be nice to share `v-on` modifier for functional components to add ability to extend standard `v-on` modifiers. 

In simple cases we can work around of this by adding additional props to the functional component `e.g. <my-comp @reset="process" modifier="hard"></my-comp>`. 

But there are cases when it is very difficult to do it the same way. I believe, this feature will help with this. 

As an example with this feature we can create something like `input-context` component which handles input event when it is in focus:
```vue
<input-context 
    :focus="isFocused" 
    @click="isFocused = true" 
    @key.down="scrollDown(1)" 
    @wheel.down="scrollDown(3)">
      ...
</input-context>
```

**Comment by posva** [comment]
Can you give an example of how you would actually extend the `on` events passed down to the `createElement` function? That's the real interesting part because the method passed to `v-on` is bound depending of the modifiers

**Comment by OEvgeny** [comment]
@posva As I can see from [`v-on`](https://vuejs.org/v2/api/#v-on) docs modifiers should contain `native` when used in components and it produces bindings to native events. So, it should work the same way.

Other component events we can simply modify and patch. See example: http://jsfiddle.net/fm0gzbac/

So, probably we can decide to pass modifier to the component or not on processing modifiers step.

**Comment by OEvgeny** [comment]
Fixed example fiddle

**Comment by posva** [comment]
I'm sorry but I don't get what are you needing the modifiers information in your code snippet

**Comment by OEvgeny** [comment]
@posva Snippet only shows what we can patch component event without changing something in Vue. For now there is no way to get `v-on` modifier in component. Just take a look on the first message to get some example how this feature can be used.

**Comment by yyx990803** [comment]
What makes this fundamentally different from `@key-down` and `@wheel-down`?

**Comment by OEvgeny** [comment]
@yyx990803 hmm, you are right, probably nothing. Only it looks different from `@keyup.down` default syntax, but definitely can be used.

When we define `v-on` handler on component with modifier, it will silently be ignored and event without modifier will be fired. May be we can pass raw string with modifier (e.g. `key.down`) to the component event when it is not native event, or warn in dev mode what dot notation is not supported for component events. What do you think?

**Comment by yyx990803** [comment]
Most modifiers (except `.once` and `.native`) are actually specific to native events, so they don't really make much sense on components anyway. I think it's best to keep component events simple and just use event name to differentiate them, since they are ultimately different events rather than the same event with different behavior.
