### ISSUE TITLE
v-bind:style written as @style doesn't compile

### ISSUE THREAD

**Issue by daryl** [vuejs/vue#4252]
A minor issue, this doesn't compile for me, I get an `Unexpected token` error raised.

**Comment by posva** [comment]
The shortcut is `:style` `@` is for `v-on`
You should read the [guide](https://vuejs.org/v2/guide/), it really is helpful 😄

**Comment by daryl** [comment]
Yeah, I just realised this. Sorry, I've been up all night, my mistake.
