### ISSUE TITLE
Directive Application Structure?

### ISSUE THREAD

**Issue by vinceh** [vuejs/vue#4254]
Been looking far and wide and couldn't find any suggestions on where/how to structure directives in a Vue project.  Since directives are defined by `Vue.directive` I'm not even sure how to define it outside of my `main.js` file.  Any suggestions?

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Directives are just objects / functions. Generally you just organize them as normal JavaScript modules, then import and register them in your entry file.
