### ISSUE TITLE
Cross Browser Issue on Vue API Docs Sidebar

### ISSUE THREAD

**Issue by alexhernandez** [vuejs/vue#4258]
When viewing the Vue 2.0 API docs on Safari the sidebar does not seem to render. It works on chrome however.

Chrome (Version 54.0.2840.98 (64-bit)):
![chrome](https://cloud.githubusercontent.com/assets/2424355/20465686/4078afd8-af18-11e6-959d-a64112fe1e65.png)

Safari (Version 9.1.2 (11601.7.7)):
![safari](https://cloud.githubusercontent.com/assets/2424355/20465700/963d5d92-af18-11e6-87e0-9b02cf4992e4.png)

**Comment by yyx990803** [comment]
Do you see any errors in the console? It works fine for me on Safari 10 and even IE but I don't have Safari 9 to test.

Anyway, please open corresponding issue with any console information at https://github.com/vuejs/vuejs.org instead.

**Comment by alexhernandez** [comment]
Sounds Good.
https://github.com/vuejs/vuejs.org/issues/598
