### ISSUE TITLE
vue-cli 中的vue 升到 2.0.8 报错， vue-loader已经是最新的了

### ISSUE THREAD

**Issue by nathenchan** [vuejs/vue#4261]
ERROR in 

Vue packages version mismatch:

- vue@2.0.8
- vue-template-compiler@2.0.7

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

**Comment by lincenying** [comment]
错误不是说的很清楚了吗? vue和vue-template-compiler的版本不匹配, 把这两个版本改成一样

**Comment by nathenchan** [comment]
问题是我没使用这个叫vue-template-compiler的东西

**Comment by fnlctrl** [comment]
> If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

请重新安装vue-loader。vue-template-compiler是vue-loader的依赖项。

**Comment by norfish** [comment]
@nathenchan 我是按照提示升级了 vue-loader 之后还是报同样的错误。最后的解决方案是升级了 vue 到最新的版本，从2.3.2升级到了2.5.2
