### ISSUE TITLE
use 'this.$parent.$on' register event with a issue

### ISSUE THREAD

**Issue by Joey-93** [vuejs/vue#4262]
I use 'this.$parent.$on' register event in a component, and the event callback is change the component's data.

all same component data is changed (include 'v-else' component) when trigger in parent.

jsfiddle demo: [demo](https://jsfiddle.net/fkc9rmvy/)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. You should never be using `$parent` to register events, as your callback contains a reference to the component instance, and prevents it from being destroyed by vue. So the callback will be run for all instances, including the ones that are supposed to be destroyed (but not).

**Comment by Joey-93** [comment]
@fnlctrl 
First of all thank you, but I still can't understand it.
According to your answer, all component's data (include 'v-else' component) will be change if i use `$parent`, but no.
Only the same ‘position’ component's data has changed when I do it, the other did not.

with a new demo :[demo](https://jsfiddle.net/fkc9rmvy/2/)

In addition,how can I 'broadcast something' to all child component in parent if this is not a issue.

**Comment by fnlctrl** [comment]
> According to your answer, all component's data (include 'v-else' component) will be change if i use $parent, but no.

That's not what I said. I only said a callback that holds a reference to the component instance will prevent it from being destroyed by vue, (then cause a memory leak). And you can see that in the fiddle if you swap components twice and change data. Notice the callback is run for more than one time, for the supposed-to-be-destroyed components.

> In addition,how can I 'broadcast something' 

Use a [event hub](https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced), or use vuex. For usage questions please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/). Thanks!
