### ISSUE TITLE
[feature request] destructuring in template

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#4264]
For now we can use `concise-object` in template, and it works well with `UglifyJs`.

When I try to use object `destructuring` in `v-for ... of` directive, it works very good in `development` environment. But then it falls when I build it with `UglifyJs`.

For example, I'm using:
``` html
<div v-for="{id, name} of params">
{{ id }}
{{ name }}
</div>
```

It compiles to sth like:
``` js
_h(..., function({id, name}){})
```

So, `UglifyJs` throw an error during compiling.

**Comment by yyx990803** [comment]
Yep, this will be supported in the next release. (vue-template-es2015-compiler actually, but it depends on some changes in core)
