### ISSUE TITLE
2.0.8 vue-template-compiler breaks scoped css 

### ISSUE THREAD

**Issue by tonypee** [vuejs/vue#4266]
When using vue-class-component library with vue-router in 2.0.8, dom elements are not being id'd and therefore the 'scoped' css is broken.

To replicate, simply install VueRouter in a test project that exports using the js like:

```
// hello.vue
...
<script>
import Component from 'vue-class-component'

@Component export default class Login {
  name = 'hello'
  msg = 'Welcome to Your Vue.js App'
}
</script>
...
```

```
// app.js
import Vue from 'vue'
import App from './App'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
})
```
"vue": "^2.0.8",
"vue-class-component": "^4.3.1",
 "vue-router": "^2.0.3"

I also find it impossible to roll back vue (i want to roll back to 2.0.7) because the vue-loader library which is a dependancy of vue has a subdependancy of vue-template-compiler@^2.0.5 which will then just install the latest, and throw a version mismatch error. It would be nice to be able to lock to an older version

**Comment by LinusBorg** [comment]
If this only happens with vue-class-component, please open an issue in that repo.

**Comment by tonypee** [comment]
the issue is with view-template-compiler tho, so i moved the bug here

**Comment by tonypee** [comment]
Here is an example repro

https://github.com/tonypee/vue-issue-4266

**Comment by yyx990803** [comment]
Haven't looked into the details but I suspect it may have to do with `vue-class-component` not handling `_scopeId` properly. I don't see anything between 2.0.7 and 2.0.8 that could cause this problem.

**Comment by ktsn** [comment]
I'll look into it.
