### ISSUE TITLE
Feature request: use props as flags

### ISSUE THREAD

**Issue by titouandk** [vuejs/vue#4269]
It would be nice to be allowed to use custom props as flags.

So here, even if the properties `primary` and `light` have no value, they are present, so their values should be set to `true` in the component.

```html
<my-button primary light>test</my-button>
```

**Comment by posva** [comment]
That's what happens already, you have to specify its type as a boolean:
https://jsfiddle.net/posva/zLgy7k69/
I'm closing this supposing this is a FR for Vue 2, please, tell me if otherwise so I can reopen
