### ISSUE TITLE
Ahead of Time (AoT) Compilation

### ISSUE THREAD

**Issue by vinicius73** [vuejs/vue#4272]
Some people have been asking about Vue.js and AoT
Is there any such information, or forecast for any support for AoT in the future?
Aor perhaps some technical explanation that shows that Vue does not need it, would be very good to have this information.

For references
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
https://github.com/toshok/echojs
http://chrjs.net/
https://medium.com/javascript-scene/why-we-need-webassembly-an-interview-with-brendan-eich-7fb2a60b0723

**Comment by yyx990803** [comment]
`vue-loader` and `vueify` supports AoT out of the box - which means any project scaffolded with `vue-cli` are already using AoT.

**Comment by vinicius73** [comment]
Thanks @yyx990803

**Comment by vinicius73** [comment]
@yyx990803 
Is it possible to mention this in the documentation?
I can not find any reference about it.

**Comment by ishowman** [comment]
> `vue-loader` and `vueify` supports AoT out of the box - which means any project scaffolded with `vue-cli` are already using AoT.

Maybe some articles about aot in vue-cli is neccessary.
