### ISSUE TITLE
Slot rendering before checking if it's needed

### ISSUE THREAD

**Issue by thatguystone** [vuejs/vue#4273]
### Vue.js version
2.0.8

### Reproduction Link
https://jsfiddle.net/thatguystone/23a85L16/

### Steps to reproduce
When using v-if with slots, the full content of each slot is rendered before evaluating if that slot should be rendered. This causes errors when there's no data ready for that slot.

### What is Expected?
In this example, the data for `slot1` isn't set, so the `v-if` should stop any attempts to render.

### What is actually happening?
All slots are being rendered, but because there's an error with `slot1`, nothing is being put on the page. The following is dumped to the console:

```
vue.js:2658 [Vue warn]: Error when rendering root instance:
vue.js:2278 TypeError: Cannot read property 'data' of null(…)
```

This worked as of 1.0.27: https://jsfiddle.net/thatguystone/5kh3Lt9j/

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
Anything in the parent template (`<p slot="slot1">` in this case) are evaluated immediately in parent scope, so accessing `slot1.data` would throw an error. You need to add `v-if` in the parent template.
https://jsfiddle.net/fnlCtrl/23a85L16/3/
