### ISSUE TITLE
keep-alive下回退导致页面不显示

### ISSUE THREAD

**Issue by nothinggift** [vuejs/vue#4275]
[http://codepen.io/nothinggift/pen/LbbqWJ/](http://codepen.io/nothinggift/pen/LbbqWJ/)

触发条件是路由keep-alive，一个页面根节点添加v-if，并在页面退出时设置显示条件为否

打开该页面->后退->再次打开该页面->后退->上一个页面消失

文档中没有看到v-if指令不能添加到模版根节点的说明，所以判断为bug

**Comment by yyx990803** [comment]
Cannot reproduce with latest version (2.0.8), please upgrade your Vue version.
