### ISSUE TITLE
list items delete and refresh of virtual dom

### ISSUE THREAD

**Issue by Hishengs** [vuejs/vue#4277]
vue version: 2.0.7
I have a list( fetched by Ajax from server ) on my page which looks like :
(generated by using v-for)
```
<ul>
    <li id="a"></li>
    <li id="b"></li>
    <li id="c"></li>
</ul>
```
then I want to delete an item, such as item b, first I use jQuery to hide the element, and then send a delete request to server, then fetch  new data and replace the old items.
1. (use jQuery to hide item b: $('#b').hide() )
```
<ul>
    <li id="a"></li>
    <li id="b" style="display:none;"></li>
    <li id="c"></li>
</ul>
```
2.send request and got new data, the list should be:
```
<ul>
    <li id="a"></li>
    <li id="c"></li>
</ul>
```
but it showed to be:
```
<ul>
    <li id="a"></li>
    <li id="c" style="display:none;"></li>
</ul>
```
the last one item was hidden.
I have try using document.getElementById('b') to delete item, but it still the same.
If using $().remove(), the new last one also be removed.
and then I try hide all the items after delete one item.then fetch new data to build the list. but it cames that the all new items was hidden...I'm now so confused.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
