### ISSUE TITLE
Documentation extension needed for $on and dynamic components

### ISSUE THREAD

**Issue by sinkaszab** [vuejs/vue#4280]
### Vue.js version
2.0.2-3

### Reproduction Link
https://jsfiddle.net/sasiszabi/1s4vtk6k/15/

### Steps to reproduce
- I am not sure I have chosen the right solution because the guide lacks on information of $on and dynamic components.
- I couldn't produce the result of this fiddle just by following the guide:
  - https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events
  - https://vuejs.org/v2/guide/components.html#Dynamic-Components
- I couldn't find it anywhere how to properly catch the event emitted by a dynamic component as it will not explicitly defined in the instance as in the examples above.

### What is Expected?
Extend guide and documentation on this topic.

### What is actually happening?
- Hack or proper solution? You tell me!

**Comment by defcc** [comment]
I updated the fiddle [here](https://jsfiddle.net/1s4vtk6k/19/)

You need add v-on  in the parent template. [https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events)

**Comment by sinkaszab** [comment]
Great! Thanks a lot!

I still think that's not really clear from the guide. (I am new to Vue.)

**Comment by defcc** [comment]
I'll close this issue. Maybe we could make an improvement to dynamic component docs. I'll follow it.
