### ISSUE TITLE
Allow to change delimiters in browser build

### ISSUE THREAD

**Issue by max13fr** [vuejs/vue#4281]
Hello,

Currently, we can only change delimiters in the standalone build (https://vuejs.org/v2/api/#delimiters).

It's really annoying because vuejs use the same delimiters as twig (mustache operators {{ and }}) and I would like to add vuejs from a twig template.

Could you allow to change delimiters in browser build ?

Anyway, congratz for you're awesome work !

Max

**Comment by yyx990803** [comment]
The standalone build **is** the browser build. It should work as expected.

**Comment by max13fr** [comment]
I found my error : I set delimiter only on the main view and not on the components. Sorry for my mistake.

Just a last question : how can I set delimiters for all components & the main vue ?

Thanks in advance,
Best regards, Max

**Comment by rpkilby** [comment]
@max13fr - you can use `Vue.extend` to create a new constructor with your desired options ([example](http://jsfiddle.net/ucvg3ysp/)).

For some historical context, see #2766.

**Comment by yyx990803** [comment]
Or use a global mixin

**Comment by rpkilby** [comment]
> Or use a global mixin

Wouldn't that affect 3rd party components? If a component expects the default delimiter, wouldn't it break?

**Comment by yyx990803** [comment]
Yes it would. But that's what @max13fr asked for

**Comment by max13fr** [comment]
Thanks for all replies. I agree, it could lead to potential issues in external components (from an another project for example).
