### ISSUE TITLE
I found that vue transition component can't have nested elements. How to solve this problem.

### ISSUE THREAD

**Issue by hieeyh** [vuejs/vue#4282]
### Vue.js version
2.0.2

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by yyx990803** [comment]
In the future, we will be closing issues that lack even the most basic information immediately. Please make sure to actually read the issue template before opening one.
