### ISSUE TITLE
how to custom render of a treenode with scopedslot

### ISSUE THREAD

**Issue by zuomingcai** [vuejs/vue#4283]
```
        <ez-tree-node :data="books">
            <template slot="nodeTemplate" scope="ctx">
                {{ctx.node.title}}1122
            </template>
        </ez-tree-node>

```

the result:only the root node get rendered from the customed template
![image](https://cloud.githubusercontent.com/assets/13760662/20550438/8fb4500c-b170-11e6-9867-223b118faf92.png)

the tree component template:
```
<template>
	<div class="ez-tree-node">
		<div class="ez-tree-node-self" @click="onItemClick">
			<span class="ez-tee-node-icon" :class="{'expanded':data.expanded,'hasChildren':data.hasChildren()}"></span>
			<slot name="nodeTemplate" :node="data">
				<span class="ez-tee-node-content">{{data.title}}</span>
			</slot>
		</div>

		<div class="ez-tree-node-sub" v-if="data.hasChildren()" :class="{'expanded':data.expanded}">
			<span class="ez-tree-node-indent"></span>
			<span class="ez-tree-node-children">
				<template v-for="node in data.getChildren()">
					<ez-tree-node :data="node" />
				</template>
			</span>
		</div>
	</div>
</template>
```

### Vue.js version
2.0.2

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

And, of course you can have recursion on scoped template.
https://jsfiddle.net/L92w2372/

**Comment by zuomingcai** [comment]
many thanks
