### ISSUE TITLE
computed properties can't correctly track dependency relationship.

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue#4285]
[DEMO](https://jsfiddle.net/whoisbigZ/phvertL9/)

There are 2 properties (P & S) in DEMO.
In loadP() methods which load some new data to P, you can found:  P[index].s === S[P[index].i]

Bug:
After vm be created, we call loadP() again.
If we modify the new members of P ( P[new].s.val ), and corresponding S (S[P[new].val]) don't be reference by any elder member of P ( P[any old].s.val), then computed properties (based S) can't correctly track dependency relationship.
And, {{P[0].s.val}} cause some error log, but it's working. Why?

-----

Demo说明：
vm有两个属性S和P。
在对P初始化的方法loadP中，可以看到：P[index].s = S[P[index].i]。
可以简单理解为：P是指向S的指针。对P[index].s的修改，本质是修改了S[P[index].i]。

问题：
如果vm初始化后，P又加载了新内容。这时，如果修改P中的新成员（的s属性），且对应的S未被P中原有成员引用，这时，（基于S的）计算属性将不能正确的跟踪依赖关系。
之后，如果修改了P中另外的某个成员，而其对应的S已经被原来P引用过，这时，计算属性又恢复正常。

另外：
vue对{{P[0].s.val}}会报错，但是实际上能够正常工作。为什么？

----

**Comment by defcc** [comment]
When vue inits your app,  `P` is empty, so it causes an error. Then you update the data in the mounted method, and it displays correctly again. You could take a look at the [lifecycle diagram](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)

**Comment by yyx990803** [comment]
This is expected behavior. When the template is rendered for the first (before `mounted` is called), P is still an empty array.

**Comment by bigZ-again** [comment]
I have update DEMO, and initial P in created not in mounted, nothing is different. So it should not be expected behavior.
I create a new issues. [#4296](https://github.com/vuejs/vue/issues/4296)
