### ISSUE TITLE
update to 2.1.0 missed a dependency?

### ISSUE THREAD

**Issue by dsl101** [vuejs/vue#4294]
I originally created a test app with vue-cli, and just ran `npm update` in the project directory. All appeared OK, until I ran `npm run dev`. In the console, I see this error:

	ERROR in

	Vue packages version mismatch:

	- vue@2.1.0
	- vue-template-compiler@2.0.8

	This may cause things to work incorrectly. Make sure to use the same version for both.
	If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

	 @ ./src/main.js 11:11-27

I had to manually update vue-template-compiler and then all was well. Did I do something wrong to trigger this in the first place?

**Comment by dsl101** [comment]
Sorry - just seen the template compiler regression issue - guess I could have been caught by someone in the midst of fixing that?

**Comment by yyx990803** [comment]
`npm update` likely did not bump `vue-template-compiler` which was a nested dependency. Anyway as long as you make sure they have the same version it is fine.
