### ISSUE TITLE
Vue JS 2.1 - Type Error: vnode is undefined

### ISSUE THREAD

**Issue by krsrk** [vuejs/vue#4295]
When i'm trying to delete an element from a list throws me an error on vue.js : TypeError: vnonde is undefined. This causes when i try to delete a element from my list of objects or clean  the entire list.

The data structure is an array of array of objects. Where the item i want to delete ara childs of another child item.

Can anyone help me with this please?

**Comment by krsrk** [comment]
Here is an image example of the error, i do a console.log of the item before and after delete. Whe you  delete the item throws that error.
![error vuejs](https://cloud.githubusercontent.com/assets/5818377/20567537/af7040f2-b15e-11e6-88ed-fbd1c2f4d68c.PNG)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by krsrk** [comment]
i dont know if i can live repro this issue due to that this is a especific env in the dev project, tell what more options do i have to show this ...

**Comment by fnlctrl** [comment]
Sorry but we need the code so that we can look into it. You don't need to include everything in your project, just the minimum code needed to reproduce the error (in this case, a sample list data, the procedures you used to remove an item, etc.)

**Comment by krsrk** [comment]
OK. I can post the data structure and the methodos. Here is the data:

[Object { id=1,  title="Go Shopping",  items=[2]}, Object { id=1,  title="Go Read"}, Object { id=1,  title="Go Vacations"}]

inside items: Object { id=1,  item="Diet Coke"},Object { id=2,  item="Coke"}

**Comment by krsrk** [comment]
the delete method:

delTodo: function (index) {
     this.todos.splice(index,1);
}

**Comment by krsrk** [comment]
the view:

<template>
        <ul>
             <li v-for="(todo, index) in todos">
                   <p>@{{ todo.title }}</p>
                   <p v-for="item in todo.items">@{{ item.item }}</p>
                   <button @click="delTodo(index)">Delete</button>
              </li>
        </ul>
</template>

**Comment by krsrk** [comment]
Im using Laravel 5.3 blade template with Vue.js 2.1 with vue-response

**Comment by yyx990803** [comment]
Sorry, but we can't really deduce what is going on with snippets like these...

Can you 1. show the error's expanded stack trace and 2. show the line in the Vue source code where the error is thrown (click on the line number on the right)?

**Comment by krsrk** [comment]
![error vue-2](https://cloud.githubusercontent.com/assets/5818377/20573418/47ab5b8e-b175-11e6-9f61-59b4c9d1adbb.PNG)
![error vue-3](https://cloud.githubusercontent.com/assets/5818377/20573417/47ab3668-b175-11e6-8ceb-6a8bd75c58b8.PNG)

**Comment by krsrk** [comment]
Now it deletes the first time an re-renders the view, but if i delete for second time it throws the error. I wil test with more complex data.

**Comment by krsrk** [comment]
This is what Chrome throws:

![error vue-5](https://cloud.githubusercontent.com/assets/5818377/20573795/299a6a8e-b177-11e6-805b-8b9af60ec9b5.PNG)
![error vuejs](https://cloud.githubusercontent.com/assets/5818377/20573796/299e06b2-b177-11e6-9fe0-4bb08d4725a1.PNG)

**Comment by krsrk** [comment]
![error vue-4](https://cloud.githubusercontent.com/assets/5818377/20573840/529bea5c-b177-11e6-856a-40d954ff91c0.PNG)

**Comment by krsrk** [comment]
![error vue-6](https://cloud.githubusercontent.com/assets/5818377/20573902/a43b6a9a-b177-11e6-9c38-8be82e6d3139.PNG)

**Comment by defcc** [comment]
@krsrk , something like this [jsfiddle](https://jsfiddle.net/defcc/ercr6dxj/1/) ? If something missing, you could update it with more details.

**Comment by yyx990803** [comment]
In theory, the error means a `staticRenderFn` returned an Array that contains an `undefined` value. I'm not sure how that could possibly happen though...

**Comment by krsrk** [comment]
its weird i dont know if its about the data structure or the technologies i used like Laravel and Materialize CSS... i've already run a JsFiddle with todos data and works great but in the project fails with that error when im trying to delete.

**Comment by krsrk** [comment]
i notice, i can delete the items outside the collapsible plugin of materialize css, it doesnt throw error.

![vuejs outsidecollapse](https://cloud.githubusercontent.com/assets/5818377/20575577/80691b5a-b17f-11e6-9a1a-c59a4b24680f.PNG)

**Comment by krsrk** [comment]
![vuejs outsidecollapse2](https://cloud.githubusercontent.com/assets/5818377/20575580/85fda428-b17f-11e6-8620-d1a05adbec22.PNG)

**Comment by krsrk** [comment]
diggin in this issue, i found a trouble when getting data from the select2 plugin autocomplete.

**Comment by posva** [comment]
@krsrk you found _a_ trouble or __the__ trouble? If it's the second you should close the issue 😉

**Comment by krsrk** [comment]
Kind of ... if select2 its not wrapped in a Vue Component it doesnt work well, it adds data to the vue instance prop but when you delete throws vnode is undefined. So the solution its to wrapp select2 plugin

**Comment by unsama** [comment]
```
select: function () {
            var self = this;
            self.$http.post("/purchase/rfq-table", {
                "username": self.options,
            }).then(function(res){
                var data = res.body.result;
                self.tabledata = [];
                if(data.length > 0){
                    data.forEach(function(val) {
                        self.tabledata.push({
                            "data": [
                                val.name,
                                val.schedule_date,
                            ],
                            "url": "/purchase/RQ/"+val.id,
                        });
                    });
                    console.log(self.tabledata);
                }
                //self.options =res.body.data;
            },function(err){
                alert(err);
            });
        },
```

> **## Uncaught (in promise) TypeError: Cannot read property 'length' of undefined**


i dont know the error please help me out this.
