### ISSUE TITLE
computed properties can't correctly track dependency relationship.(#4285 update)

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue#4296]
[DEMO update](https://jsfiddle.net/whoisbigZ/phvertL9/1/)

I have move loadP() from mounted to created, so this should not be expected behavior.  

more information
[#4285](https://github.com/vuejs/vue/issues/4285)

**Comment by yyx990803** [comment]
there is no error in the console any more, isn't it working now?

**Comment by posva** [comment]
Closed in favour of #4307. Don't open a new issue each time please, update the existing one instead
