### ISSUE TITLE
Regression v2.1.1 with <transition>

### ISSUE THREAD

**Issue by Atinux** [vuejs/vue#4300]
By upgrading to the v2.1.1, I got the following warning from Vue.js:
> vue.js:515 [Vue warn]: Property or method "_leaving" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <transition>)

Live demonstration (look at the console and clic on the "Toggle Component" button): https://jsfiddle.net/Atinux/d290e5rq/

Live demonstration with v2.1.0 with no warning: https://jsfiddle.net/Atinux/rxg4yqyx/

**Comment by yyx990803** [comment]
Thanks, this is a known issue, I'm working on this.

**Comment by yyx990803** [comment]
Can you confirm the warnings are gone with 2.1.2?

**Comment by Atinux** [comment]
Vue packages version mismatch:
- vue@2.1.1
- vue-server-renderer@2.1.2

Did you build Vue before publishing on npm?

**Comment by Atinux** [comment]
See https://github.com/vuejs/vue/blob/dev/dist/vue.js#L3518

**Comment by JounQin** [comment]
version mismatch +1

**Comment by vertoo** [comment]
I have other version mistmatch error:
- vue@2.1.1
- vue-template-compiler@2.1.2

**Comment by yyx990803** [comment]
Ah, SauceLabs keeps disconnecting today so I had to push a manual release... missed that part :(

**Comment by yyx990803** [comment]
2.1.3 is out with version mismatch fix.

**Comment by Atinux** [comment]
Working perfectly, you rock @yyx990803

**Comment by weihuana** [comment]
vue.esm.js?65d7:479 [Vue warn]: Vue is a constructor and should be called with the `new` keyword
