### ISSUE TITLE
computed properties can't correctly track dependency relationship.(#4296 update)

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue#4307]
以前的描述可能让你偏离了重点，我进一步简化了重现代码，代码本身应该足够清晰了！

[DEMO v3](https://jsfiddle.net/whoisbigZ/phvertL9/2/)

[#4296](https://github.com/vuejs/vue/issues/4296)

**Comment by posva** [comment]
This is working as expected: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

In your case, you just need to set `this.S` once the whole object is ready: https://jsfiddle.net/posva/56jfoL6u/
