### ISSUE TITLE
Vue 2 Single Slot rendering Problem

### ISSUE THREAD

**Issue by melon** [vuejs/vue#4308]
### Vue.js version
2.1.3

### Reproduction Link

single slot is not correctly rendered(version 2.1.3):
https://jsfiddle.net/kbbdbtok/2/
children elements within v-box component is NOT rendered

while using vue 1, it is correct(version 1.0.28):
https://jsfiddle.net/kbbdbtok/3/
children elements within v-box component is rendered, though in vue 1, <transition> hasn't had its meaning as in vue 2 yet.

### Steps to reproduce
see jsfiddle examples above

### What is Expected?
according to https://vuejs.org/v2/guide/components.html#Single-Slot , single slot feature should be available in vue 2.

### What is actually happening?
But it seems not working properly.

**Comment by ktsn** [comment]
This is because the `v-box` component has multiple root element. Vue v2.0 requires exactly one root element for each component.
If you use development build (not minified build), you can get error messages for that.
