### ISSUE TITLE
[improvement]Allow usage of event modifiers on functional component events

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#4311]
To stop event propagation in functional components I have to include dirty piece of `DOMEvent` code in form of:
```javascript
attrs: {
    role: 'button',
    alt: __('reset_to_default_value'),
    title: __('reset_to_default_value'),
    'onclick': 'event.stopPropagation()'
},
on: {
    click: context.parent.resetValue
}
```
it would be really neat if we could use standard vue's event modifiers known from standard templates,
perhaps in form of (to keep the syntax similar to existing `watch` syntax):
```javascript
on: {
    click: {
        stop:true, 
        prevent:true,
        handler: context.parent.resetValue
    }
}
```

**Comment by posva** [comment]
it's up to the click function to control that:

``` js
on: {
  click (event) {
    event.stopPropagation()
    context.parent.resetValue(event)
  }
}
```

Adding those attrs will just do the same for you

**Comment by Uriziel01** [comment]
Wow, just wow.

I was so trapped inside particular way of thinking about it I've missed the obvious solution, thank You @posva 👍
