### ISSUE TITLE
Vue 2 Single Slot rendering Problem 2

### ISSUE THREAD

**Issue by melon** [vuejs/vue#4312]
### Env
vue 2.1.3
vue-template-compiler 2.1.3
vue-loader 10.0.1

### Reproduction Link

because it seems to be related with vue-loader, it's a bit difficult to reproduce it merely on JSFiddle, I'll just describe the steps below.

### Steps to reproduce

create a file called `box.vue`
``` 
<template>
    <div>
        <slot></slot>
    </div>
</template>

<script>
    export default {
    }
</script>
```

then a snippet of html code
```
<div id="container">
    <v-box>
        hello
        <p>lalala</p>
        <p>lilili</p>
    </v-box>
</div>
<script>
    new Vue({
        el: '#container',
        components: {
            "v-box": require('./box.vue')
        }
    });
</script>
```

### What is Expected?

expected to show 
```
hello
lalala
lilili
```

### What is actually happening?

actually only shows
```
hello
```

### Others
I created a related issue #4308 before, though that issue has proven to be a mistake by myself, I still haven't gotten my problem solved.
p.s. If use vue@2.0.0, the above problem does not exist any more.

**Comment by LinusBorg** [comment]
Would it be a problem to create a littel repository for us to clone? That would be very helpful.

**Comment by yyx990803** [comment]
Cannot reproduce with exact same setup - please reopen with an actual reproduction.

**Comment by melon** [comment]
I've created a repository https://github.com/melon/single-slot , and successfully reproduced the issue at my machine. It's really weird.
p.s. I use node v5.4.0, I don't know if it matters, just for your information.
