### ISSUE TITLE
[Documentation] Cannot click on demo button

### ISSUE THREAD

**Issue by Elfayer** [vuejs/vue#4314]
Here is a picture of what is not working : 

<img src="https://forum.vuejs.org/uploads/default/original/2X/d/dfdb21be5f15a7ab160d5e6226ee27518e437eaf.png" width="689" height="377">

The padding of the `p` comes above the button which makes it not clickable.

I think, the css should look like:

```
margin: 1.2em 0 -1.2em; // Correction: margin: 1.2em 0;
padding-bottom: 1.2em; // Correction: no padding.
```

Tested on Chrome:
<img src="https://forum.vuejs.org/uploads/default/original/2X/e/e29b253bf0940d018aef36aa908ef32e459533ed.png" width="339" height="164">

**More:** I could also mention that there is an `overflow-x: scroll;` on the class `.demo` which makes every demo have a visible unused scroll. Why not simply replacing it by `overflow-x: auto;` ?

**Comment by LinusBorg** [comment]
This is the wrong repository.

I already told you on the forum to open an issue at github.com/vuejs/vuejs.org
