### ISSUE TITLE
Rerendering a functional component which renders a component with a slot

### ISSUE THREAD

**Issue by blocka** [vuejs/vue#4315]
### Vue.js version
2.1.3

### Reproduction Link
http://jsfiddle.net/5sH6A/

### Steps to reproduce

Press run and wait a second

### What is Expected?

You should see 

```
2
["slot1"]
```
in the output
 
### What is actually happening?

```
2
["default"]
```
shows up after a second, indicating that the component is not seeing any slots.

**Comment by yyx990803** [comment]
The jsfiddle link seems to be wrong

**Comment by blocka** [comment]
http://jsfiddle.net/5sH6A/919/
