### ISSUE TITLE
npm run dev error with vue-cli+vue2.1.0？

### ISSUE THREAD

**Issue by windluo** [vuejs/vue#4316]
### I follow the steps below:
_____________________
$ npm install --global vue-cli
$ cd my-project
$ npm install
$ npm run dev
________________________________
### in the last step，NPM error：
（OS: Windows_NT 6.1.7601）
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.0.2
3 info using node@v4.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle myproject@1.0.0~predev: myproject@1.0.0
6 silly lifecycle myproject@1.0.0~predev: no script for predev, continuing
7 info lifecycle myproject@1.0.0~dev: myproject@1.0.0
8 verbose lifecycle myproject@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle myproject@1.0.0~dev: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\.npm_npminstall\node_modules\.4.0.2@npm\bin\node-gyp-bin;D:\mytest\my-project\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;D:\Java\jdk1.8.0_73\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\microsoft shared\TigerKin;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\admin\AppData\Roaming\npm
10 verbose lifecycle myproject@1.0.0~dev: CWD: D:\mytest\my-project
11 silly lifecycle myproject@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle myproject@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle myproject@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: myproject@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\.npm_npminstall\node_modules\.4.0.2@npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\.npm_npminstall\node_modules\.4.0.2@npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid myproject@1.0.0
16 verbose cwd D:\mytest\my-project
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v4.5.0
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error myproject@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the myproject@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the myproject package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs myproject
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls myproject
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by posva** [comment]
You can try using npm 3. This issue belongs to https://github.com/vuejs-templates/webpack (I believe that's the template you're using).
Can you please, see if the error persists and if so open an issue there with a cleaner output if possible, thanks.

**Comment by windluo** [comment]
Sorry for late! I installed the npm3, although it's still npm4,but problem has been resolved. Thanks very much.

**Comment by windluo** [comment]
#4316
Sorry for late! I installed the npm3, although it's still npm4,but problem has been resolved. Thanks very much.

**Comment by windluo** [comment]
Sorry for late! I installed the npm3, although it's still npm4,but problem has been resolved. Thanks very much.

**Comment by windluo** [comment]
@posva 
Sorry for late! I installed the npm3, although it's still npm4,but problem has been resolved. Thanks very much.
