### ISSUE TITLE
Vue 2 Single Slot rendering Problem 3

### ISSUE THREAD

**Issue by melon** [vuejs/vue#4318]
### Env
node v5.4.0
vue 2.1.3
vue-template-compiler 2.1.3
vue-loader 10.0.1

### Reproduction Link

https://github.com/melon/single-slot

### Steps to reproduce

see repository

### What is Expected?

expected to show 
```
hello
lalala
lilili
```

### What is actually happening?

actually only shows
```
hello
```

### Others
related #4312

**Comment by HerringtonDarkholme** [comment]
Don't use runtime build at the same time with full build.

This effectively means:

1. adding this lien to your webpack config `resolve: { alias: { vue: 'vue/dist/vue.js' }, },` which resolve vue to full build
Or 
2. change require('vue/dist/vue.js') to 'vue', and adding a render function in your entry component

Reference:
https://github.com/vuejs/vue/blob/dev/dist/README.md
https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#what-does-this-mean
