### ISSUE TITLE
firefox not work

### ISSUE THREAD

**Issue by ChangeZhang** [vuejs/vue#4319]
![image](https://cloud.githubusercontent.com/assets/6948367/20619557/1e8e7c56-b330-11e6-91ab-b41a735fcce9.png)

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!
