### ISSUE TITLE
Suggestion: Re-enable path support in Vue.set()

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue#4320]
Between v1 and v2, the ability to specify a path in Vue.set was removed, allowing only object keys to be passed. Right now, running:

```javascript
Vue.set(state.data, 'theme.color', 'blue');
```

...simply adds the key `theme.color` to the `data` object with a value of `blue`. Was there any particular reason this functionality was removed? I can't find anything documenting the change on the guide, API or release/migration notes.

My main use-case is that I have a form that allows a user to update a resource (in the above case, a "page" where the user can change their theme settings). I'm using vuex and retrieving the page data from an API, and storing it under `page.data`. When any field in the update form is changed (using `@input('...')`) I add/update that same property in a `page.payload` object, and send `page.payload` in the update request, meaning I only send the updated fields.

Though I've read that it's better practice to define your reactive data initially (and then update later), this isn't possible in this case since I don't want to send empty fields to the update endpoint.

It just seems strange that you can define nested data initially within a component, but then can't add to this later (shown here: http://jsbin.com/hiciye/edit?html,js,output).

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

> It just seems strange that you can define nested data initially within a component, but then can't add to this later (shown here: http://jsbin.com/hiciye/edit?html,js,output).

Since you've already defined initial nested data, the proper way of setting a property in your example would be 
```javascript
Vue.set(this.data.theme, 'background', 'http...');
```

The reason of removing path support is that it requires a proper path parser (to support things like `a.b[0].c`), which bloats the code only for a rare use case. Also, it really can be avoided to simply use the example above.
