### ISSUE TITLE
Please extract Vue core into smaller modules for more flexibility

### ISSUE THREAD

**Issue by kristianmandrup** [vuejs/vue#4321]
I was wondering if there are plans to extract more of Vue core into individual modules.
I see there are currently two platforms, a specific VDOM implementation etc.

In my mind, all these would make sense as modules that could be included/substituted as needed.
Perhaps a sensible idea for Vue 3. Where would I submit such feature/design suggestions?
Is there a roadmap? Thanks!

**Comment by yyx990803** [comment]
What exact flexibility are you thinking of? Please read https://github.com/babel/babel/blob/master/doc/design/monorepo.md

TL;DR: extracting into smaller modules come at a cost, and a non-trivial one. At the same time, I don't see clear benefits of doing so. Even if there are, it has to be significant enough to justify the cost.

**Comment by kristianmandrup** [comment]
Fair enough. We should overcome this cost as a community. The main issue is sharing the same dev environment across multiple repos. 

Anyways, I was interested in trying to integrate Cycle.js with Vue2. They look like a good fit. 
I think I already found a way to do it, simply:

`const h = bind(createElement, vm)`

And then use the `h` function from within Cycle.js to interact with the VDOM of Vue :) ??

I first thought about substituting the VDOM of Vue, which would be easier to reason about, if it was in a separate module..

**Comment by kristianmandrup** [comment]
and create components via `const vnode = createComponent(child, data, vm, vm)`

**Comment by yyx990803** [comment]
Well, I'd say it's very unlikely we will ever go to that level of modularity. Vue is simply not designed for that type of use case.

Also - using Cycle.js and Vue together doesn't seem sound right to me. Cycle + snabbdom or a custom DOM driver sounds more like the right match.

If you simply want to use Rx with Vue, [`vue-rx` allows you to write pretty Cycle-like code](https://github.com/vuejs/vue-rx/blob/master/example/counter.html).
