### ISSUE TITLE
[Vue 2.1.3] customized filter bump into "[Vue warn]: You may have an infinite update loop in a component render function."

### ISSUE THREAD

**Issue by IChocolateKapa** [vuejs/vue#4323]
### Vue.js version
2.1.3

### Steps to reproduce
**As you can see from the link below:**
[https://jsfiddle.net/n25w0ka2/2/](https://jsfiddle.net/n25w0ka2/2/)

when I click the button to sort list, the result is as what I expect,  but it consoled "[Vue warn]: You may have an infinite update loop in a component render function."

So can anyone tell me where am I wrong? Do I use the customized filter correctly?

**Comment by sqal** [comment]
Your example is not complete but I guess you have to use .slice() to make sure you're working on a copy of original array

https://github.com/vuejs/vue/issues/1153

**Comment by IChocolateKapa** [comment]
@sqal Thank you so much,  _.slice()_just worked like charm. Thank you!
