### ISSUE TITLE
virtual scroll list - feature

### ISSUE THREAD

**Issue by SpareShade** [vuejs/vue#4324]
@yyx990803 mentioned in #2000
... might work on a  "virtual scroll list" where it only renders items in the viewport in the future

just wondering if this could be logged as feature request as it would be a really great solution for many use cases.

thank you all for great work that makes vuejs what it is !!!

**Comment by Akryum** [comment]
[Here](https://github.com/Akryum/vue-virtual-scroller) is a component you can take inspiration from or use directly with webpack.

**Comment by yyx990803** [comment]
Closing as this is now doable in userland and @Akryum already implemented one :)
