### ISSUE TITLE
a grammar mistake in the documentation?

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vue#4327]
![qq 20161120161750](https://cloud.githubusercontent.com/assets/1060733/20649629/a553f462-b4fe-11e6-8523-fb006b040477.png)

is it okay to use the conjunction "because" here?
"that" is really appropriate instead?

**Comment by yyx990803** [comment]
Where is this paragraph? Can you provide a link?

Also - please file documentation issues at vuejs/vuejs.org repo instead.
