### ISSUE TITLE
Warning about the properties of the components in the props

### ISSUE THREAD

**Issue by herozzSage** [vuejs/vue#4329]
### Vue.js version
2.0.2

### Steps to reproduce
More than one Component has a similar  Vue warning
### What is Expected?
Eliminate Vue warning

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/24214972/20657791/b16ebb18-b573-11e6-81b4-a557b6586e35.png)
![image](https://cloud.githubusercontent.com/assets/24214972/20657803/d43d208a-b573-11e6-96b3-7eeab83b5741.png)
![image](https://cloud.githubusercontent.com/assets/24214972/20657838/036bbf10-b574-11e6-9ff3-8d82baa39cf2.png)

I think Prop has specified the validation requirements.
I did not respond to a warning in the VueJS1.0, but this warning was only occurred when the migration was VueJS2.0.
How to solve the props to avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Props should not be mutated inside components: https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow

**Comment by yyx990803** [comment]
This may be related to vue-class-component. /cc @ktsn

**Comment by ktsn** [comment]
Hmm, I cannot reproduce.

@herozzSage 
Can you please provide reproduction if the warning persists even if you actually aren't mutate props?

**Comment by herozzSage** [comment]
@ktsn 
I received the props directly.However, the use of official documents, the render is invalid.

**Comment by ktsn** [comment]
Can you provide reproduction or example repository? because I cannot reproduce this.
