### ISSUE TITLE
Please document using vue-server-renderer and vue-router together

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue#4331]
Hey!

I'm currently [really struggling](http://stackoverflow.com/questions/40847692/vue-server-side-rendering-with-vue-router-error-thrown) to get vue-server-renderer and vue-router to work together, using basically exactly the same code from vue-hackernews-2.0 minus the Vuex stuff.

I'm unable to debug it myself because I don't understand _why_ stuff is happening: a code example is better than nothing, but isn't giving me enough information to figure out what is going wrong, or even what code to provide for other people to help me debug it.

Nobody currently on Gitter seems to know how this works, either.

Some documentation would be fantastic! If I figure it out before someone else writes it, I'll write it myself, but given how stuck I am right now, that seems unlikely.

**Comment by defcc** [comment]
Thanks @callumacrae, We'll trace this issue in the [vue.js issue](https://github.com/vuejs/vuejs.org)
