### ISSUE TITLE
Feature Request: Precompute/pre-cache "computed" bindings beforehand to determine if need to render() or not.

### ISSUE THREAD

**Issue by Glidias** [vuejs/vue#4333]
I'm not sure about how computed property caching works, but it seems the caching is done on the fly during the render() logic cycle? Why not do it before render()? (Sort of like "precompute").

I was thinking, since you collect binding dependencies along the first render() , (anyway to trace this on end-user developer side?) you determine first which properties within the computed property methods has been invalidated and needs to be re-calculated (this is already done by VueJS), BUT, on the next state change but before render() is called, re-execute and pre-cache the invalidated computed properties' final values to determine if anything has changed from before? If no computed property has changed and no other dependency exists, however, render() can be skipped entirely.

One might say,  howeve,r with this approach includes the chance of wastefully pre-computing computed properties in situations where it might be not needed in a particular situation, if it exist in a different if/else block within the render() method. But then again, pre-computing outside of if/else blocks are always required as part of the initial scan render() logic (as stated in documentation) if one wishes to ensure those are made as invalidation dependencies regardless of the if/else state situation (short of having a render(firstTime:Boolean) parameter flag where firsttime renders require reflection of all property invalidation dependencies to VueJS). Thus, in any case, there is already precomputation of invalidated properties, so why not do it before render() since their bound to be used anyway?

Anyway, if you precomputed "computed" properties before render() as a further pre-condition to render(), this would allow better integration with "replace with immutable state atom" approaches as shown in example below, since replacing the root state atom will not trigger a render() in situations where all pre-computed properties' leaf values remain unchanged and no other dependencies has been invalidated except for those computed properties. Also, behind the scenes, it means that computed properties' leaf values are can always be automatically assumed be cached by default during the render() logic cycle.

http://jsfiddle.net/xu7ba2gu/

**Comment by Glidias** [comment]
**Temporary approach as of now**

As of now, the temporary solution (that should work in various cases under components) is to use a default: function binding for the component props within a component to to connect it to root state's/store (or manually pass the value bindings down  directly as attributes). The component does not compute or bind any methods based on the root application state, but work purely on it's given props.  Thus, this does not involve actual precomputation of computed methods, but only pre-resolution of component prop values.  Thankfully, prop values will optimize based on the leaf values (they are treated as reactive notifying getters within the local component scope), so, if the leaf values remain the same, no component render update will be triggered.

https://jsfiddle.net/x9v1knLm/

I've also used a seperate helper class to perform the leaf binding calculation within such handler prop efault value handler methods, to ensure scope is limited to root access only. Accessing other local component props/methods/computed getters etc within the local scope should be disalllowed in Prop default value resolution handler functions, because other local props may  not be initialized at that time a prop value is being resolved.  I've adopted this practice as well in my own project https://github.com/Glidias/haxevx/blob/master/src/haxevx/vuex/examples/shoppingcart/components/CartVue.hx#L64 . When `default:function(){}` approaches are used for component props which references a a root/store's state,  use a seperate handler method (prefably inlinable to avoid additional  function call) that restricts access scope to available contextual parameters only.

**Comment by yyx990803** [comment]
On the higher level, I think this strategy brings in a lot of complexity for unknown perf gain (in most cases re-rendering a single component is extremely fast).

Also, computed properties that are never used in `render` (e.g. under a falsy if branch) will never be evaluated. For example:

``` html
<div v-if="someObject">
  {{ computed }}
</div>
```

Inside `computed`, the code can assume `someObject` is truthy. This is the current behavior, and pre-evaluating it out of render will throw if `someObject` turns out to be undefined. Technically this is a breaking change, which makes it a no-go.

Ultimately, Vue's reactivity system is not designed for immutable data structures - it intrinsically relies on mutations to be able to efficiently determine which components need to re-render. I don't think it's worth it to shoehorn it to be able to play nicer with immutable data structures.

**Comment by Glidias** [comment]
Yea, after some looking through myself, precomputing is indeed a bad idea and subjected to many unpredictabilities.

When it comes to Immutable structures, it'll be manually passing down prop value for now as the best approach, rather than referencing data from root (which always changes) in order to get the best performance with mutable props from outside the component. (.  In fact, that's generally a reccomended practice for React, anyway, and the same applies to Vue (except there's no need to manually implement  `shouldComponentUpdate` boilerplate).
