### ISSUE TITLE
v-model.trim bug report

### ISSUE THREAD

**Issue by ageofsys** [vuejs/vue#4334]
### Vue.js version
2.0.2

### What is actually happening?

Sorry, my english is not very good and first bug report

it's ok when the trim modifier of v-mode where desktop browser. but it is not ok when mobile browser.

this trim modifier remove all space of sentence in mobile browser.

i have tested on the safari and chrome mobile browser

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
