### ISSUE TITLE
Event handlers in capturing mode won't be removed

### ISSUE THREAD

**Issue by KingMario** [vuejs/vue#4335]
### Vue.js version
2.1.3

### Reproduction Link
http://codepen.io/KingMario/pen/yVzvoR?editors=0011
From the code pen, you can see that the handler is registered again and again and again without being removed.

### What is Expected?
The second h function in the ternary statement returns a new DOM tree will remove the click event handler registered in the first h function.

### What is actually happening?
The click event handler is not removed.

### Bug Fixed?
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener), 

> Removal of a capturing listener does not affect a non-capturing version of the same listener, and vice versa.

The bug is fixed in 4th [commit](https://github.com/vuejs/vue/pull/4267/commits/53c14db1514e31d3f9e1ff1e9b23cf8893036bb4) of this [PR](https://github.com/vuejs/vue/pull/4267), so please review it or tell me to split it into another PR.

**Comment by sqal** [comment]
I think it's happening because Vue can't differentiate between these two root divs. Simply add a `key` attribute to one of them and the problem will be solved.

Check similar issue - https://github.com/vuejs/vue/issues/4119

**Comment by KingMario** [comment]
@sqal

Vue CAN differentiate them.

It's only the problem that registered event handlers in capturing mode should be removed the same mode.

Meanwhile, you can treat this issue as a new feature of rendering function enhancement. Since, currently, events like `'!click'` is not encouraged to use in the rendering function, there seems no necessity to remove a capturing listener during virtual DOM diff.

**Comment by sqal** [comment]
@KingMario yeah sorry, i deleted my answer because i realized that it wasn't proper solution

**Comment by KingMario** [comment]
@sqal no problem.

**Comment by yyx990803** [comment]
fixed by merging #4267
