### ISSUE TITLE
Any plans for native support ?   Or any ideas I can leverage Vue.js with some other native library ? 

### ISSUE THREAD

**Issue by jpca999** [vuejs/vue#4340]
### Vue.js version
2.0.2

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

-----------------

https://github.com/alibaba/weex
https://medium.com/the-vue-point/vue-2-0-is-here-ef1f26acf4b8#.8c1eu1vh2
> One More Thing…
The engineers at Alibaba, the biggest e-commerce company in China, have been working on a project called Weex, which renders components written in a Vue-inspired syntax into native mobile UI. But soon, “Vue-inspired” will become “Vue-powered” — we have started an official collaboration to make Vue 2.0 the actual JavaScript runtime framework for Weex. This will enable users to write universal Vue components that can be reused across Web, iOS and Android! The collaboration is still in early stages, but it will be a big focus for us now that 2.0 is out, so stay tuned!
(Yes, it is native like ReactNative or NativeScript, not Cordova.)
