### ISSUE TITLE
webpack + vue + jinja

### ISSUE THREAD

**Issue by BusyHe** [vuejs/vue#4341]
i use webpack+vue,can i use jinja,what can i do

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
