### ISSUE TITLE
how to get vue object in JQuery callback function

### ISSUE THREAD

**Issue by ShukriChiu** [vuejs/vue#4342]
I wrote my code like this : 
`
.api({
          action: 'signup users',
          method: 'post',
          dataType: 'JSON',
          beforeSend: function(settings) {
            let email = $('#regemail')[0].value
            let name = $('#regname')[0].value
            let password = $('#regpassword')[0].value
            settings.data = {
              email: email,
              name: name,
              password: password
            }
            return settings;
          },
          onSuccess: function(response) {
            console.log(response)
            Cookies.set('user_name', response.user.name);
            Cookies.set('user_token', response.user.token, {
              // 30mins
              expires: 1 / 48
            });
          },
`

However I want to use vm.$emit in onSuccess function, how can I get vue object in JQuery callback function

above code is wrote in mounted: function() {}

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
