### ISSUE TITLE
Godawful error messages

### ISSUE THREAD

**Issue by janat08** [vuejs/vue#4345]
My slumps code that produces the unkown: http://pastebin.com/2Nb2LBLM
What you should take after: https://github.com/Akryum/meteor-vue-component/issues/48
I got two errors both of which originate from (unkown) which is exceptional in sight of errors that quite possibly don't ever link to the source in stack trace eg common.js. akryum:vue-components took the time time to actually improve those where if something breaks it actually points at the line of the file that's not working, at which point you can step on shaky grounds of guessing your way through and away from copy and paste.

**Comment by simplesmiler** [comment]
Godawful report, to be honest.
Could you please take some time to make a usable reproduction that actually demonstrates the issue instead of hoping that someone will do it for you?

**Comment by yyx990803** [comment]
This error report lacks the most basic information:

- What actual error messages are thrown?
- Vue version?
- Node version?
- Webpack version?
- `vue-loader` version?
- From official CLI template?

Also, pasted info is not actually runnable. This fails to comply with the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines).

I might as well add: this is not an appropriate way to open issues. If you want your issue to be respected, please respect the time of the maintainers as well.

**Comment by janat08** [comment]
Lets face your errors, are shit, no matter how you reproduce it, all you
had to do was take a peek at proper library.
