### ISSUE TITLE
Ctrl modifier with enter key is not working

### ISSUE THREAD

**Issue by allesan** [vuejs/vue#4347]
### Vue.js version
2.1.3

It looks like Ctrl modifier with Enter key is not working.
This works <textarea @keyup.alt.67="clear">
but <textarea @keyup.ctrl.enter="clear"> fires on Enter key no matter if ctrl is pressed or not.

### What is Expected?

With <textarea @keyup.ctrl.enter="clear"> it's expected to trigger "clear" only when Ctrl key is pressed down and hit Enter.

### What is actually happening?

"clear" is triggered every time Enter is hit, wether Ctrl is pressed or not.

**Comment by defcc** [comment]
Related to this commit https://github.com/vuejs/vue/commit/b45b974a5c866abd8dc777ccac511af30b72b91b#diff-cd513113ac480c30cffa092f5fe266ed

Maybe it should not be limited to mouse events ?  It's a common usage in keyboard events handling.

cc @yyx990803

**Comment by yyx990803** [comment]
The primary reason I did that is because allowing it for key events would break the following:

``` js
Vue.config.keyCodes.ctrl = 17
```

Although the above usage seems rare, this would still technically be a breaking change.

**Comment by defcc** [comment]
We may need document it here https://vuejs.org/v2/guide/events.html#Modifier-Keys. I'll update the doc.

**Comment by yyx990803** [comment]
Alternatively, we can add a deprecation warning when the user attempts to define a built-in modifier as a custom keyCode alias.

**Comment by defcc** [comment]
I think that would be better, considering the common usage of keyboad event. I'll try to make a update.

**Comment by defcc** [comment]
@allesan , currently you might need to deal with the special key in your event handle like `if(!evt.ctrlKey)return` and that's what vue does internally.

**Comment by KingMario** [comment]
I didn't noticed that limit and accidentally modified the events document by adding the keyboard events, note on meta key and samples.

Should have studied the codes and the release commit list before modifying the document. Feel sorry.

**Comment by allesan** [comment]
@defcc thanks, that works.

**Comment by defcc** [comment]
Closed with https://github.com/vuejs/vue/commit/e8d6bd9dc73cacbc665ce132d81a7b629bef764b

And we need update the relative doc, will track it in the vuejs.org issues.

**Comment by zzjalpaca** [comment]
https://user-images.githubusercontent.com/19635504/53807719-40b33080-3f8b-11e9-97cb-116cb3ca6fbc.png
sdad
