### ISSUE TITLE
Dynamic Image URL not possible while looping through an object

### ISSUE THREAD

**Issue by dpollard** [vuejs/vue#4351]
### Vue.js version
2.0.2

### Reproduction Link

See the fiddle here -> https://jsfiddle.net/99hrw6uj/

### What is Expected?
We use a system where the users picture is automatically displayed in a restful format: `/user/pic/:id`, but with vuejs, displaying the users picture is tedious and I would rather not try a hacky work around.

### What is actually happening?
The following error is thrown: 
```
VM992 vue.js:2601[Vue warn]: src="https://placehold.it/160x160/000000/ffffff?text={{person.name}}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.
```

Any suggestions would be helpful! Thanks!

**Comment by fnlctrl** [comment]
https://vuejs.org/v2/guide/migration.html#Interpolation-within-Attributes-removed
