### ISSUE TITLE
v-html does not work with filters

### ISSUE THREAD

**Issue by peterkorgaard** [vuejs/vue#4352]
### Vue.js version
2.1.3

### Reproduction Link
https://jsfiddle.net/peterkorgaard/t1Lxnwoq/16/

### Steps to reproduce
In my fiddle I have added a filter and two uses of it. One with v-html and one with mustache interpolations. The first one (v-html) returns 0 and throws an error in the console. The latter prints the html code produced by the filter - but it is of course not rendered as html, because this is not supported with mustache interpolations. The example with v-html, on the other hand, should render as html.

### What is Expected?
Rendered html

### What is actually happening?
Vue does not recognize the filter when using v-html. For the record. The same thing happens when using v-text.

**Comment by yyx990803** [comment]
2.0 filters only work in mustache tags and v-bind.

**Comment by SlyNet** [comment]
How to implement a highlight that was simple in v.1:
```
{{{ option.title | highlight(searchTerm) }}}
```

with filter `highlight` that wrapped found text in spans?

**Comment by simplesmiler** [comment]
@SlyNet put your `highlight` into `methods`, and `v-html="highlight(option.title, searchTerm)"`.

**Comment by mtrunt** [comment]
What if I have a filter that outputs HTML? Do I have to use a computed property or is there a better way?

**Comment by Akryum** [comment]
Computed properties are the best way. You get automatic caching.

**Comment by Fridus** [comment]
You can use `$options.filters` :
```
v-html="$options.filters.highlight(option.title, searchTerm)".
```

**Comment by kirillgroshkov** [comment]
Fridus - works indeed! But looks like undocumented private API

**Comment by dsky1990** [comment]
@Fridus this works fine ,thx

**Comment by posva** [comment]
@Fridus You can safely rely on that: `$options` are the options passed to the Vue constructor when creating a vm (so any component or new Vue). From that point on is just javascript 🙂

**Comment by arivera12** [comment]
@Fridus I really like this way to do it. No nasty mustache tags needed for this! Thanks!

**Comment by kakulukia** [comment]
Why is this issue closed although its still not working?

**Comment by ppKrauss** [comment]
The solution `"$options.filters.highlight(option.title, searchTerm)"` **is ugly**, the pipe is need to be  [orthogonal](https://en.wikipedia.org/wiki/Orthogonality_(programming))... **Seems a LANGUAGE DESIGN BUG**.
