### ISSUE TITLE
I inited the value of msg 1, but my data bind in html{{msg++}},result:102, ,the code is following

### ISSUE THREAD

**Issue by smile-night** [vuejs/vue#4353]
html Code：
```
<div id="app">
    <p>Message: {{msg++}}</p>
</div>
```
JS Code：
```
<script type="text/javascript">
    var vm1 = new Vue({
        el: "#app",
        data: {
            msg : 1,
            dynamicId: "test",
            someDynamicCondition: true
        }
    })
</script>
```
result：
```
Message: 102
```
detail：if I change the code in html  `{{msg++}}`  to  `{{msg+1}}` 
I will get this result：Message: 2

**Comment by yyx990803** [comment]
msg++ has a side effect, so every time the component renders it triggers a new render, ending in an infinite loop.

You should never use an expression with side effects in your template other than in event handlers.

**Comment by smile-night** [comment]
Oh, yeah ,you are right ,thank you very much
