### ISSUE TITLE
Vue instance used as a non component

### ISSUE THREAD

**Issue by rhyek** [vuejs/vue#4354]
Hi. I asked [this question](https://forum.vuejs.org/t/is-using-a-vue-instance-as-a-non-component-object-supported-recommended/3632) on the forums, but have gotten no answer.

Basically, I'm using Vue instances as data records and not components as shown [here](http://codepen.io/rhyek/pen/MbObbX?editors=1010).

Is this supported/recommended use? I'm interested in doing this since I need computed properties and methods that function in the context of individual objects and not the current component.

I have not seen this sort of usage mentioned in the official docs, hence my curiosity. Thanks.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. It is supported, though not officially recommended. 
Non-component vue instances has been used in vuex to manage state, and also in the [eventHub](https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced) pattern as a global event hub.

**Comment by rhyek** [comment]
Thank you.
