### ISSUE TITLE
vue2.0 template required 

### ISSUE THREAD

**Issue by qianoop** [vuejs/vue#4357]
I am a beginner ,when I run a sample with vue-cli ,I found this problem .
Here is my problem .
I denfined "required" property  in the template html element like this
`<input type="text" required='21321'>`
when I run this project 
I found this in chrome  debug
`<input type="text" required="required">`
I would like to  know where this is true or not .
I will use the property   to  validate the element whether is required or not 
like this  "required ='true'  required  = 'false' " 
but all this will render like this
`<input type="text" required="required">`
please tell me why .thanks.

my environment
vue:2.1.0 
just create the project with vue-cli
and  write this in app.vue template

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by defcc** [comment]
@qianoop required is a boolean attribute. 

According to [w3 specification](https://www.w3.org/TR/2011/WD-html5-20110525/common-microsyntaxes.html#boolean-attributes)
>  The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.
> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

So you could use custome attribute like `data-required="false"`
