### ISSUE TITLE
Feature Request: keep-alive component transition mode directive

### ISSUE THREAD

**Issue by mendieta** [vuejs/vue#4361]
Hello everyone

I think a pretty useful feature of Vue 1.X was the ability to have transition mode between components with different transitions, especially useful with vue-router. And extremely useful on sites that rely on transitions.

As an example of what im saying is this jsfiddle: http://jsfiddle.net/Mendieta/fb215702/

That was achieved using 

`<router-view keep-alive transition-mode="out-in"></router-view>`

With Vue 2.X , now keep alive is a component and there is no way to achieved the example above. So i figure it would be useful for the keep alive component to have a transition mode directive to use in such cases.

`<keep-alive transition-mode="out-in"></keep-alive>`

or maybe a transition shallow/wrapper component. If you do not declare a name for the transition and only the mode it will orchestrate the transitions on the child components.

`<transition mode="out-in"></transition>`

I place the feature request here, as i think it is more related to the keep alive component  rather than the vue-router.

If i missed something out, please let me now.

**Comment by yyx990803** [comment]
It is supported: https://github.com/vuejs/vue/blob/dev/test/unit/features/component/component-keep-alive.spec.js#L260-L279

**Comment by mendieta** [comment]
hi, my understanding and tests are that it is supported only if the transition component contains a keep-alive component that contains dynamic components, all of which will use the same transition.

My request was in the use case where each component contains a different transition.

**Comment by yyx990803** [comment]
Ah sorry, yes you are right - it is not currently possible in 2.0.

**Comment by yyx990803** [comment]
I thought about the use case and I think `transition-mode` on `keep-alive` doesn't make much sense, because it's not really about `keep-alive` or the component being switched.

Instead, I'd make a custom transition component that communicates over a shared event bus: https://jsfiddle.net/yyx990803/dksrq698/

You can use this component as the base and make variations of it for different views, but they can all share the same communication channel as long as they belong to the same `<router-view>`.

Note the fix for `<keep-alive>` is not released yet so I'm not including it in the fiddle.

**Comment by mendieta** [comment]
Thanks,

I have checked the fiddle, and i see the `out-in` mode works nicely.  But i think i found a bug, when you navigate for the first time to a route the transition is not triggered.

I think the solution is a bit "hacky" and i'm not sure that a transition mode `in-out` would be possible using your suggested approach. Do you think that i should move this feature request to `vue-router` ? Given that as you mentioned this does not belong to the `keep-alive` component.

BTW awesome response times!!

**Comment by yyx990803** [comment]
This is not a hack, if I were to implement it internally, the logic would be largely similar. I doubt this can be done differently given how the new transition system works...

**Comment by yyx990803** [comment]
Another possible solution: instead of using `<transition>` inside the child components, you can write a higher-order component that wraps its slot child in different transitions based on the child's name/type. I might release this as a separate component later.

**Comment by mendieta** [comment]
@yyx990803 thank you for the suggestions. In the provided fiddle you make use of `this._pending` but i havent found any documentation on this. Can your point me in the right direction so i can understand how it is accomplished.

And the high-order component would be awesome. Greets

**Comment by yyx990803** [comment]
`this._pending` is just a property specific to that component, not an API. (it's the callback on line 11)

I actually should've avoided prefixing it with an underscore.

**Comment by mendieta** [comment]
Oh, now everything makes sense. Now i have one more question. The first transition is not triggered because on line 11 the enter transition is only triggered if the event is received, which only be triggered after the first leave transition. I will try to improve your fiddle just to have a better example for future reference.

**Comment by yyx990803** [comment]
I updated the fiddle and initial enter should be working now.

**Comment by mendieta** [comment]
awesome, thank you

**Comment by mendieta** [comment]
On more, thing. Sorry for keeping you busy on this. Just to clarify, if i wanted to make an `in-out` transition.  The events dispatched should be inverted? dispatching `bus.$emit('next')` once the enter animation is completed?
