### ISSUE TITLE
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>

### ISSUE THREAD

**Issue by wgq837051** [vuejs/vue#4363]
Because the page body in the <script> label, through the vue analytic html, html source code is not a <script> tag, I can shield this function, or do not resolve the <script> tag？

**Comment by defcc** [comment]
Seems that you mount the Vue instance `el` to your body element? It's not recommended. You could refer https://vuejs.org/v2/api/#el

You could do as bellow
```js
const vm = new Vue({
  'el': '#app'
})
```

```html
<body>
  <div id="app"></div>
  <script src="path/to/your/script"></script>
</body>
```

**Comment by yyx990803** [comment]
Do not use Vue on `<body>` - there should've been a warning if you did that.

**Comment by abrhambas01** [comment]
Try to close out your divs properly.

**Comment by trusktr** [comment]
It'd be nice if Vue throws an error for unclosed tags, like with JSX. That would improve developer experience.

**Comment by sirlancelot** [comment]
@trusktr It does?
![image](https://user-images.githubusercontent.com/71916/63250213-f4e60200-c21f-11e9-9f35-9859d7d57952.png)

**Comment by timster** [comment]
@sirlancelot No, that's your editor that is showing that warning/error. Vue doesn't warn if you have an unclosed tag.

**Comment by jacekkarczmarczyk** [comment]
Yes: https://codepen.io/jkarczm/pen/jONMbLp
