### ISSUE TITLE
Vue Js warning "The el option shouild be a function that returns a per instance.."

### ISSUE THREAD

**Issue by ianrussel** [vuejs/vue#4364]
Hi, 

I have this warning 

       vue.common.js?e881:1137[Vue warn]: The "el" option should be a function that returns a per-instance     value in component definitions.

   Any ides how to remove this warning? My app works fine, just want to remove warning in console 

           require('./packages');
           require('./components');
           require('./routes');

          const app = Vue.extend({
              el: '#app',
           });

**Comment by fnlctrl** [comment]
Are you using the `app` variable later as `new app()`?
If not, you can simply change it to
```js
const app = new Vue({
  el: '#app',
});
```

**Comment by yyx990803** [comment]
Only pass el at instantiation time, not extension time.
