### ISSUE TITLE
currency filter, bug upon pressing tab key

### ISSUE THREAD

**Issue by jaasaria** [vuejs/vue#4366]
using:
<input name="itemcost[]" type="text"   v-model="row.cost | currency ''"  class="form-control" placeholder="Cost">

everytime i click tab key , the value changes in my input text. hope someone could help me on this. thanks in advance.

### Vue.js version
2.0.2

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
