### ISSUE TITLE
Using "default" in prop validation breaks ECMA 6th standard and YUI compressor

### ISSUE THREAD

**Issue by zsoltgrigore** [vuejs/vue#4367]
### Vue.js version
1.0.26

### Reproduction Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/default
The reserved word "default" must not be used in an object literal as property name!

### Steps to reproduce
1. Make a component with validation
```javascript
Vue.component('comp', {
    props: {
        foo: {
            type: String,
            default: 'a'
        },
        bar: {
            type: String,
            default: 'b'
        }
    }
}
```

2. Paste it to YUI compressor
http://ganquan.info/yui/

3. Compress

### What is Expected?
Postprocessors using the produced code should not fail. 

### What is actually happening?
[ERROR] 5:20:invalid property id

[ERROR] 5:21:syntax error

[ERROR] 6:10:syntax error

[ERROR] 7:13:syntax error

[ERROR] 8:18:syntax error

[ERROR] 9:21:syntax error

[ERROR] 11:5:syntax error

[ERROR] 1:0:Compilation produced 7 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 7 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:154)
	at org.mozilla.javascript.Parser.parse(Parser.java:392)
	at org.mozilla.javascript.Parser.parse(Parser.java:337)
...

**Comment by simplesmiler** [comment]
That's a mistake on YUI compressor part. It's only illegal to use keywords as identifiers, not as property names and accessors. Reference: [MDN / Reserved word usage](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage).
If you have to deal with YUI compressor, you can quote the keywords:
``` js
Vue.component('comp', {
    props: {
        foo: {
            type: String,
            'default': 'a',
        },
        bar: {
            type: String,
            'default': 'b',
        }
    }
})
```

**Comment by zsoltgrigore** [comment]
Ok thank you for the hint. May be that should be added to the docs.

"default" is a confusing property name anyway, even if it is allowed. "let" or "return" should be used instead ;-).

**Comment by LinusBorg** [comment]
> "default" is a confusing property name anyway.

Why do you feel that way? it's used to define the default value to use when no other value was provided.

**Comment by zsoltgrigore** [comment]
May be it is just me but I do not like to reuse reserved words if it is not absolutely necessary. If the purpose is to "define the default value to use when no other value was provided", than why not to name it defaultValue so you will make also the syntaxHighlighter and YUI happy :) or just state somewhere that this notation is fine also for props {"default" : "foo"}.
Unfortunately It seems that it is not clear for frontend people (at least not in my circles) that you can define props with any js object notation style. It is obviuos now after the comment of @simplesmiler. So I have to admit that we should have though of it before filing the issue.
Thanks again @simplesmiler

**Comment by yyx990803** [comment]
Because in this case, we are conforming to the standard and YUI is not. Why should we cater to some 3rd party tool that fails to comply with the standard?

**Comment by zsoltgrigore** [comment]
From that point "using reserved words in allowed context" is a matter of personal taste so I do not want to argue on that. It is your decision to use it so stick with it if you wish.
Luckily there is a workaround for people who has to work with YUI so for me that is fine.
Thanks again

**Comment by zsoltgrigore** [comment]
> is a workaround for people
...and it is not even a workaround but a fully standard way to define objects in JS, just to be correct
