### ISSUE TITLE
v-once don't work inside router-link

### ISSUE THREAD

**Issue by gabrielbuzziv** [vuejs/vue#4368]
### Vue.js version
2.0.2

### Reproduction Link
Sorry, i don't know how to reproduce in JS Fiddle, follow the code:

```
<router-link :to="{ name: 'users.show', params: { user: $route.params.user } }" tag="li" >
    <a v-once>{{ user.name }}</a>
</router-link>
```

### Steps to reproduce
- Instanciate a data with an object
- Create a router-link and set the context an attribute of the object you create previously
- Add v-once (in this step) the text stop showing

### What is Expected?
Expect to show the user name and don't change the value if the object data is changed.

### What is actually happening?
When add the v-once directive to the wrap element of the var the attribute is not showed any more.

**Comment by yyx990803** [comment]
Please move this issue to https://github.com/vuejs/vue-router

Also, I cannot reproduce the issue. You can make a reproduction based on this fiddle: http://jsfiddle.net/yyx990803/xgrjzsup/
