### ISSUE TITLE
[Vue 0.11] Uncaught TypeError: Cannot read property '__vue__' of null 

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#437]
Getting this error with computed dependencies adding and removing rows of a table(I've incremented the grid example with search and pagination)

Debugger points to this method:

```
function findNextVm (vm, ref) {
  var el = (vm._blockEnd || vm.$el).nextSibling
  while (!el.__vue__ && el !== ref) {
    el = el.nextSibling
  }
  return el.__vue__
}
```

**Comment by VictorSigma** [comment]
I had the same problem. I couldn't find a easy fix for this inside Vue. I instead just made sure that the comment was always at the end of the list after sorting. So in your sortable options...
```javascript
      onEnd: function (evt) {
        this.list.splice(evt.newIndex, 0, this.list.splice(evt.oldIndex, 1)[0]);
        
        var nodes = this.$$.listElement.childNodes
        for (var i = 0; i < nodes.length; i++) {
          if (nodes[i].nodeName == "#comment")
            var comment = nodes[i];
        };
        
        if (comment) this.$$.listElement.appendChild(comment)
      }.bind(this)
```

**Comment by japboy** [comment]
:+1:

**Comment by CremboC** [comment]
Dunno if this is going to help anyone, but in my case I had a `track-by="id"` and the elements in the array didn't have an id field in them.
