### ISSUE TITLE
Should beforeMount etc be called when server has rendered component?

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue#4374]
With Vue 2.0 server-side rendering, if a component has been rendered by the server should its `beforeMount`, `mount` and similar lifecycle methods be called on the client, since the component's content has technically already been mounted (by the server)?

I'm having an issue where I'm loading initial data into a vuex state for a page, but since the API request is also in the `beforeMount` function (to ensure it's requested when the component is re-mounted), a request for the same resource is made on the client as well when the page is first loaded.

I've had a look over the issue list, but can't find quite what I'm referring to here.

**Comment by yyx990803** [comment]
Since you are using vuex, the store should serve as a caching layer - the same fetch action should not send an ajax request if corresponding data is already in the store (inlined and hydrated from the server render).
