### ISSUE TITLE
Unable to debug radio buttons being unchecked randomly

### ISSUE THREAD

**Issue by chrzrdx** [vuejs/vue#4375]
### Vue.js version
2.1.4

### Reproduction Link
Kindly see: [https://jsfiddle.net/chrzrdx/krrczkx5/](https://jsfiddle.net/chrzrdx/krrczkx5/)

### Steps to reproduce
Cycle through the questions by using the prev, next buttons. 

### What is Expected?
v-model should set the radio buttons to checked.

### What is actually happening?
while the v-model is in sync with the field storing the value of the set radio button, sometimes certain radio buttons render with unchecked, when actually, the field bound to v-model is showing that the value is present (i.e. the radio button should render as checked)

### Text of the question as posted on stackoverflow/vuejs forums 
This is on `vue 2.1.4`

I have a questions array in my vue.data, and I'm cycling through them every time the next or prev button is pressed. I store the `id` of the active question, and compute the active question from there. I am using `v-model` on the radio button to store the state in the active question's `selected` property.
 
The questions already have a default value (`selected` initially contains the value of the default option). But some radio buttons display as unchecked even though the `selected` field of the current (active) question is set.

The issue persists even if there are no default values in `selected`, and the user clicks each button herself.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. This is caused by vue's dom patching strategy. As described in the docs (https://vuejs.org/v2/guide/list.html#key):

> This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).

So, you can simply fix it by adding a `key` attribute to each element:

https://jsfiddle.net/gowfxayt/

And also, 
>It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.
