### ISSUE TITLE
Lagging in v-on:change

### ISSUE THREAD

**Issue by luqmanrom** [vuejs/vue#4377]
I had an input with v-on:change directive in it to call some method I declared inside the Vue objects. But I realized there are delays in calling the method whenever the value is changed.

I reproduced it in here:

https://jsfiddle.net/lookman/4y2wmxot/2/

**Comment by luqmanrom** [comment]
Okay. Browsers will not fire a change event until the item loses focus. Using input event seems working better

**Comment by posva** [comment]
@luqmanrom Yes 😄
