### ISSUE TITLE
v-on seems to not be able to bind to events with names containing periods

### ISSUE THREAD

**Issue by cdrubin** [vuejs/vue#438]
Bootstrap 3 fires events with names like:

```
  show.bs.collapse
```

but vue complains with "Error parsing expression" when encountering something like:

``` html
  <div v-on="show.bs.collapse: method_call">
```

**Comment by ryanmortier** [comment]
@yyx990803 This doesn't appear to work still?

`@hidden.bs.modal="resetSource()"` will still fail to trigger the event.

**Comment by yyx990803** [comment]
@ryanmortier this conflicts with the modifier syntax introduced in 1.0. Do not use periods in event names.

**Comment by tolbxela** [comment]
There are cases, for example if you use some library, when you can't change the event name. 
Check my [question at StackOverflow](https://stackoverflow.com/questions/64389504/vue-js-unable-to-catch-an-event-with-a-point-in-name-using-v-on)

I guess, it should be possible to handle such events in the right way. If the event modifier after dot is not known, just to pass event further. 

I'll try to check the vue code.
