### ISSUE TITLE
altering html structure breaks bindings

### ISSUE THREAD

**Issue by itsmill3rtime** [vuejs/vue#4380]
### Vue.js version
2.0.2

### Steps to reproduce
```
<div id="navigation">
    <ul>
        <li>Discussions</li>
        <li>Tasks {{open_tasks}}</li>
    </ul>
</div>
<script>
    navVue = new vue({
    el: '#navigation',
    data: {
        tasks:[]
    },
    methods: {
        getTasks: function (){
            ........
        } 
    },
    computed: {
            open_tasks: function () {
                return this.tasks.filter(function (task) {
                    return task.status.indexOf('open') > -1 || task.status.indexOf('in progress') > -1
                })
            }
        }
});
</script>
```

is original code and runs fine. displays the computer property **open_tasks**

in order to make the `<li>` tabs scrollable, i have tried a few different jQuery plugins. once i enable any of them they change the structure so the `<ul> `is wrapped in 1 to 3 additional divs. 
### What is Expected?
when the value of open_tasks changes the value should update
### What is actually happening?
the value stays the same. however if the plugins are disabled it updates correct. also if the vue instance is created after the jQuery plugins have initialized it will work correctly too. however delaying the vue instance creation is far from ideal in my situation.

**Comment by yyx990803** [comment]
If a plugin replaces the DOM nodes Vue is managing, then breaking is expected behavior. We cannot predict behavior of arbitrary 3rd party plugins.
