### ISSUE TITLE
Default binding inline style with number in object to `px`

### ISSUE THREAD

**Issue by CYBAI** [vuejs/vue#4385]
When we want to bind inline style with object, we might use object in `data` like this way.

```js
data() {
  return {
    style: {
      width: '400px',
    },
  };
}
```

I think it might be useful for users to just write `number` and it will suffix with `px` automatically.

```js
data() {
  return {
    style: {
      width: 400,
    },
  };
}
```

Is it possible to default unit with `px` when using numbers?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. There are many other css properties like `line-height` that works with numerical values, i.e. `line-height: 40`. So appending `px` by default will break these usages.

**Comment by CYBAI** [comment]
@fnlctrl Thanks for your reply first.

It's awesome to have some css properties to work with numerical values; however, some properties which also should have this feature cannot work with it. Will it be good to work with numerical values for those css properties which would have units?

**Comment by kazupon** [comment]
@CYBAI 
I think it's possible to implement with computed properties.
Also, In Vue.js 2.1 later, we can use the filter of `v-bind`.

e.g.
```js
const prefix = val => {
  return val + 'px'
}
new Vue({
  computed: {
    prefixedStyle () {
      return prefix(this.style)
    }
  },
  data () {
    return {
      style: {
        width: 400,
      }
    }
  },
  filters: { prefix }
}
```

```html
<!-- computed property -->
<img :width="prefixedStyle">

<!-- v-bind filter-->
<img :width="style | prefix ">
```

**Comment by CYBAI** [comment]
@kazupon

Looks good to me though I hope vue will support suffix `px` automatically 😄 
Besides, using `filters` or `computed` properties might be more flexible for users.
Thanks for your reply and great example.

**Comment by whatthecole** [comment]
i agree with @CYBAI . it's flexible when calculating the style
