### ISSUE TITLE
Fieldname to Component selection (feature suggestion)

### ISSUE THREAD

**Issue by MarcTe** [vuejs/vue#4389]
As an app will use many more different fields than generic display components needed to display them, for keeping low the amount of code to send client side, and templates as clean as possible, developers should be able to position a fieldname on a template, (the perfect context for positionning and program surrounding behaviours), and be understood as a sub-component selection with parameter passing. (see more details below)

1) A fieldname would translate to a component selection/call, according to a meta data vuex structure. (I am still not an expert in JS nor Vue, so the syntax is an approximate). Here is an example of such structure:

```
PUBLISH  // client side version

{'pubName' :<name>,

 CD : ''    //Table level permissions (Create Delete) (see billow)
 Fields:[
	     {Name :< >
	     VE : '',   //Field level permissions (View Edit) (see billow)
             Type // text, currency...
	     Component
             Optional
	     Width,height
	     Min
	     Max
	     Regex
	     ListType},

	    {},   //other fields
	    {}
         ] 
}
Other contexts
```

This structure is to be standardized a way or another such as 
-For a context (pubName) and field name, be able to access field parameters, including Component.

**Table level permissions** 
'' Cannot Create nor Delete
'C' Can Create not Delete
'D' Can Create and Delete

**Field level permissions** 
'' Cannot View nor Edit // In fact, this value would result in not even including this field in this list in   the version sent to client
'V' Can View not Edit
'E' Can View and Edit

2) Some parameters need to be passed forward to the called component.
Also, in complexe components such as data grids, a component might need to call an even lower component, thus needing again to call a component and pass parameters.
This should ideally be done without defining this call in code, because it would increase code size (to pass to client, to display in the code file, and to code error free, and would make less clean templates for each field insert).

This is why, it would be really useful to have asap (my wish! : ) ) a feature that does this :

The following : `<f FirstName>` would replace it with something like :

`<component :is="Publish.(context).fields['Firstname'].Component" name='FirstName' :value='FirstName' :context='context' :mode.sync ='mode'>` 

But WITHOUT defining components (in the actual component) to be used in the actual dynamic component use.

`<f`' would stand for field or forward (if not already in use in HTML specifications)

**FirstName** : the field to display. A lookup in the meta data would select what component to call. But also, it would be passed to that called component to an attribute named FieldName (for further use of metadata by the called component).

**Value** : the value received by data received, passed to a generic FieldValue attribute in the called component.

**Context** : Selecting which section of the meta data to look at the specified field (here, the pubName in the meta data), also passed to Context attribute (for further use of metadata by the called component). This attribute in the calling component is the same for all fields in the template.

**Mode** : a 2 way (possibly an array of multiple attributes).
This would allow subcomponents to set a record wide or form wide status) AND as well, react to them.
If this is conceptually considered bad, at least we need to pass a reference to what variable we need to call the setter and listen to the getter.

**Finally**, it could be very interesting to have a version of this feature that takes a list of fields and loops through them and perform the call for each one. 

For previous reflexions leading to this model, you can look at https://forum.vuejs.org/t/frontend-framework-structure/3704
One element in my reflexion is that we can have several contexts for the same template. Thus, we can have a template that includes a field but that is set as non editable or editable, or is not present in the specified context, so leading to an empty display of that field. This context would be provided from a query to the server and would be returned to the client, according to allowed permissions. This context would be added to those already in the meta data list.
This would allow flexible use of the same template (quick view or full view, or user permissions).

The whole system would also allow to simplify templates by not patching multiple exceptions, but by stating what we want in a specific context, in a meta data driven way.

I think it is a good way towards cleaner templates, incapsulating more code in lower but reusable components despite more complex behaviours. It also addresses somehow the fatness of an application that can inflate its code only once arrived on the client side, leveraging metadata.
It also opens the door to form based customization, without coding.

**Comment by posva** [comment]
Hi @MarcTe , thanks for your interest in Vue.
Your idea very high level and fits better in the user land as an abstraction on top of Vue.
I don't see what you're talking about with _fields_, but it just looks like a specific component.
Good luck with your idea 😄

**Comment by MarcTe** [comment]
The problem is to get the vue.js code sugar that will for sure work OK and not break Vue.js features.
So, I really think, especially for those people like me, not experts in interpreter workflow, how to implement such feature. It is sad that you close this thread before some people have time to comment.

The main point is to have a Vue feature that does what I describe, beacon replacement and implicit parameter passing. 

This would highly simplify an improve the frontend framework.

Marc

**Comment by MarcTe** [comment]
@posva By field, I mean (in the old database vocabulary) an attribute (or column) in a record in a table of a database, such as last name, first name, phone number ...

**Comment by posva** [comment]
That sugar you're talking about is just a component you can create yourself.
I closed because I looked at all the things that have already been said (which there's too much) and realised this fits the userland better.

Cheers

**Comment by MarcTe** [comment]
But @posva, if done in userland, it forces either to define dynamic component code for each element on the form (rather than get it done automatically behind the scene at runtime on the client) OR define an intermediary component that will anyway have to code all possible components in a dynamic call (one more place to code when we add a component which is not so bad, but will add one more component level for each element in the top form) above the lower component. 
BUT, this also means on the top form, each call needs 5 parameters passing. 

Why not simplify things? Visually, code size wise, memory usage wise, speed wize.

Marc

**Comment by MarcTe** [comment]
@posva , I would like to discuss the topic with you by Skype (EMHmark7). It could be in French or in English. Thanks. Marc

**Comment by yyx990803** [comment]
@MarcTe , no offense, but it was quite difficult for me to understand your proposal even after reading it twice. I imagine it would be similarly or even more difficult for less experienced users to comprehend it. Since Vue has always focused on being approachable and easy to understand, I don't think this is something we'd consider pulling into Vue.js itself. I'd recommend building this in userland to suit your specific needs.

**Comment by MarcTe** [comment]
Thanks @yyx990803 for your reply. But I am really trying to express it in the best way. 
The more I think about it, the more I see it as a must for the framework, and not as userland.
Maybe I am misunderstood because of the use of some terms that mean something else to you.

The main point is: if we program in sub-components,
that are reusable, 
and want to place them in templates by using short & simple beacons, we need to pass anyway some parameters, 
such as the context and an acceptable way to reflext upwards sub-component reactions to the manager of the upper component.

This means it would be natural to have an implicit way of putting a component in the template,
and have Vue.js either interpret it a more elaborate way, or at least replace it behind the scene with a longer verison before it is interpreted by Vue.js.

For less verbose component insert, some information need to come from a metadata source.

Example: I put a button component with just the name of the component:
`<StartButton>` Or `<button context="Start">`
This would be replaced by a call to a button component with a reference to metadata related to the StartButton. It would also wire things so this sub-component can reflect its state to the upper component. This upper component is the one to which the meaning of the button state has a meaning. For good practices and debugability, the button component should change the state of the upper component by calling an attribute setter or a manager procedure that is central to the upper component. 

Another cool feature could be that inserting such button, could create related attributes for managing it.

Of course, maybe it makes more sense to show it through visual sketches.
I would also be very open to have a Skype conversation with you on this matter (EMHmark7).

I already have a new handwritten schema showing the problem.

I am really trying to use Vue the best and elegant way. 
We should remind us that we are thlking about a front-end framework, meaning, related to visual objects, not long and complicated JS.

Marc

**Comment by MarcTe** [comment]
In other words @yyx990803, @posva and @LinusBorg :

Whatever allowing data driven templating (and app code slimming) or not, 
the idea can be synthesised this way: 

To have a way to insert components without the need of a long statement of parameters.
This way, templates can look more visual and only include code that is mostly related to component positionning, beside the minimum behaviour code that needs to be outside these components.

This would allow: (see simple solution billow)
-An apparently simple framework (vue.js) for graphic designers, or anyway making easier and cool to see our template code.
(that would offer a "natural" way of inserting a component in a universe of components)
-Highly repetitive code to be generated by client side.
(namely: take the component beacon (`<whatever>` OR `<CodeReplacementTag whatever>`)and replace it with all the necessary call syntax that would anyway be necessary for each and every component calls of this component type)

Solution:
The simplest way to do that is triggering a code replacement before Vue.js interprets it.
This code replacement could take the string in the beacon (ex: firstName in `<firstName>` OR `<cr firstName>`)
and process it in a function that returns the JS statement to interpret.
(this is similar in some ways to Dynamic Templates,, but also allows to define the parameters we want to pass and do some processing for defining the values passed).

It would also allow a simpler way to connect data flow between different component levels.
Althougs not explicit in the code, this could be made explicit in a function, somewhere in global code files.
A great thing would be that the function returning the statement could have the logic to select different return formats (what and how many parameters, etc.), according to what serves better the context. 

Bottom of the line: this feature would allow really cool and visually appealing code, whatever way we want to take advantage of it. 

I really think it is a great step to take, or to allow.

Marc
