### ISSUE TITLE
Vue2.0 is used with jQuery1.12. The jQuery click event is disabled

### ISSUE THREAD

**Issue by wgq837051** [vuejs/vue#4397]
Vue.js version
2.0.2
<body>
  <html>
  		<table id="table1">
								<tbody>
									<tr height="50px"><td>one</td><td>two</td></tr>
									<tr height="50px" ><td>three</td><td>four</td></tr>
								</tbody>
							</table>
  </html>
</body>

` $(document).ready(function(){
$("#table1").find("tbody").click(function() {
console.log('click running@@');
});
	var  vm = new Vue({
	      el:"#table1", 	     
		  methods: {			     			  
		  }		    
	  });	
 });`
When you do not call vue, the click event can be executed, call vue, click event can not be executed, vue2.0 and jquery can not be used together?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Vue 2 replaces your dom and therefore dom events like the click one are replaced. You should put the jquery manipulation in the `mounted` event. You can also google for examples, there're many

**Comment by LinusBorg** [comment]
Note: @wgq837051 I already replied to your first issue with the same question one hour earlier.

**Please don't open any more issues for this**

Support/Help: http://forum.vuejs.org
