### ISSUE TITLE
Event modifiers not working

### ISSUE THREAD

**Issue by robert-hoffmann** [vuejs/vue#4398]
I have a form, and no matter how i try to place event modifiers, the form is always submitted.

Didn't have this problem with 1.xx

Here is a very simple failing example:
https://jsfiddle.net/9momgu8y/3/

**Comment by fnlctrl** [comment]
var model = new Vue({
  el: "#test", // 'el', not 'ele'
  methods: {
    showMessage: function () {
      alert("hi");
    }
  }
});

**Comment by robert-hoffmann** [comment]
!! My bad !!
