### ISSUE TITLE
jquery sortable and vue 2.0 bug

### ISSUE THREAD

**Issue by ZhangJunkang** [vuejs/vue#4399]
code：`
<div class="container" id="app">
    <div class="row">
        <sortable-list :items="items"></sortable-list>
    </div>
</div>
<script>
    var sortableList = Vue.extend({
        template: '<ul id="sortable" class="list-group" style="width: 200px">' +
        '<li class="list-group-item" v-for="item in items">{{item.title}}{{item.id}}<button type="button" class="close" aria-label="Close" v-on:click="remove(item)"><span aria-hidden="true">&times;</span></button></li>' `+'</ul>',`
        props:['items'],
        methods: {
            remove: function(item) {
                var index = this.items.indexOf(item);
                //alert(index);
                this.items.splice(index, 1);
                for(var i=0;i<this.items.length;i++){
                    console.log(this.items[i].id);
                }
            }
        },
    });

    var vm = new Vue({
        el: '#app',
        data: {
            items: [{
                id: 1,
                title: "Item"
            }, {
                id: 2,
                title: "Item"
            }, {
                id: 3,
                title: "Item"
            }, {
                id: 4,
                title: "Item"
            }, {
                id: 5,
                title: "Item"
            }]
        },
        mounted: function() {
            //console.log($("#sortable"));
            $("#sortable").sortable({
                start: function(e, ui) {
                   ui.item.data('start', ui.item.index());
                },
                update: function(e, ui) {
                    var start = ui.item.data('start'),
                            end = ui.item.index();
                    vm.items.splice(end, 0, vm.items.splice(start, 1)[0]);
                    /*for(var i=0;i<vm.items.length;i++){
                        console.log(vm.items[i].id);
                    }*/
                }
            });
            $("#sortable").disableSelection();
        },
        components: {
            sortableList
        },
    });
</script>`
error ：列表拖动交换数据后，数据打印正确，但是页面列表显示顺序不正确

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by yyx990803** [comment]
Vue 不保证与任意可能操作 dom 的第三方库的兼容性。请自行查找兼容的插件。
