### ISSUE TITLE
transition-group odd behaviour with transitions (fiddle)

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue#4401]
### Vue.js version
2.1.3

### Reproduction Link
https://jsfiddle.net/z11fe07p/83/

### Steps to reproduce
Click the "Switch" button a few times, sometimes the squares pop in, sometimes they fade like they should.

If everything works fine, reload a couple of times, it seems to be triggered at random on load.

### What is Expected?
Squares should always fade in/out.

### What is actually happening?
It feels random, but sometimes the squares will pop in, instead of fading in. I can't wrap my head around why this is happening.

**Comment by TheDutchCoder** [comment]
This must have been a fluke or something, after going out for lunch it suddenly works completely normal. Sorry for opening the bug report, something must be up on my end!

**Comment by TheDutchCoder** [comment]
Additional details, it seems that having a `path` property with certain values will mess up the transitions:

Broken fiddle, has path property: https://jsfiddle.net/z11fe07p/85/
Working fiddle, no path property: https://jsfiddle.net/z11fe07p/87/

**Comment by sqal** [comment]
Please check `console.log(r)`

> Squares should always fade in/out.

Well, no, they shouldn't. You just probably getting the same image index few times in a row so image doesn't change. Your function doesn't guarantee that the drawn index will be different from the previous one. Besides this everything looks good to me.

**Comment by TheDutchCoder** [comment]
That's not the point, I know the same index will not trigger a change, that's not the bug.
Now opening the fiddle suddenly works, but sometimes it doesn't.

Could this be an issue with (hot) reloading?

I'm having the exact same issue with my local build (vue-cli, webpack template) and it seems to mainly occur when the code gets hot reloaded.

I have people on the gitter channel confirm the same behaviour, it's not just my machine it seems, but it's VERY random.

**Comment by TheDutchCoder** [comment]
Additional info: when launching the fiddles in other browsers I get the same (random) results.

Reloading makes it sometimes work and sometimes break.

**Comment by sqal** [comment]
alright, after further checking there's definitely something weird going on. When the transition-property is set to `all` i don't see images animating at the beginning (but after 3-4 switches). But when you change the `all` to just `opacity` it works great. So yeah it's weird issue.

**Comment by TheDutchCoder** [comment]
Correct, it also happens in all kinds of browsers and sometimes on reload, sometimes not.
For now I can specify the properties individually, but this seems like a real bug to me.

**Comment by Plasmatium** [comment]
I tested in chrome, firefox, IE11 with nearly 20min, switched, reloaded, reruned. No problems found. Maybe this is a bug in jsfiddle and fixed now.

**Comment by yyx990803** [comment]
@Plasmatium interesting - indeed I can no longer reproduce the issue, probably accidentally fixed in latest Vue by some other changes.
