### ISSUE TITLE
Using router-link "events" property for a double click event doesn't work.

### ISSUE THREAD

**Issue by dschissler** [vuejs/vue#4404]
Based upon the 2.1 documentation I would expect : `<router-link :to="to" events="dblclick" exact>` to only trigger on the `dblclick` event instead of `click,` but this doesn't change the default behavior to fire on double click.  If this is not the intention of the `events` property then this has not been made clear in the documentation.

I'm currently enjoying being able to wrap around `router-link` instead of needing to handle anchor events and to then call `e.preventDefault()`.  However, without either better documentation of this feature or a patch to provide it then it will be a large dead end for me.

**Comment by TheDutchCoder** [comment]
This would belong in the vue-router repo, could you please post it there?

**Comment by dschissler** [comment]
Done
