### ISSUE TITLE
Dynamic filter names

### ISSUE THREAD

**Issue by rubyisapm** [vuejs/vue#4405]
According to the document, the filterId would be parsed by using the text after | as the filterId. Is there possible to support use expression as the filterId. For example: we can use obj.filter as the filterId. vue can calc the expression, then use the result to be the filterId? Thx for your time:)

**Comment by posva** [comment]
If the filter was named `uppercase` and stored in a variable `filter`, you could do that with 

```
this.$options.filters[filter](val)
```

instead of

```
val | uppercase
```

Which is ofc non-dynamic

**Comment by posva** [comment]
IMO having dynamic filters breaks a bit the readability of templates and should be moved to the js instead with a computed property and an explicit name about what it represents.
Also, I don't really see what syntax could be used `val | [filter](options)` ?

**Comment by yyx990803** [comment]
I'd just use computed properties instead or a plain method call. Filters are designed for readability and are expected to be static.

**Comment by asafh** [comment]
Without saying whether this is useful or better to avoid, you can define a dynamic filter this way:  
```javascript
Vue.filter('dynamicFilter', function(value, name, ...args) {
    return Vue.filter(name)(value, ...args);  //Argument pass-through
});
//Use:
{{value | dynamicFilter(filterNameExpression, arg1Exp, arg2Exp) }}
```
