### ISSUE TITLE
Vue rendering data model problem

### ISSUE THREAD

**Issue by woshihaoren** [vuejs/vue#4406]
### Vue.js version
2.0.1

### Reproduce link
right code:    http://jsfiddle.net/df4Lnuw6/75/
wrong code:  http://jsfiddle.net/df4Lnuw6/76/

### Steps to reproduce
1. On right code, When click AAA and BBB button, They become blue, And console log same to Vue Devtools model
2. On wrong code, When click AAAA and BBBB button, They have problem, just one button can become blue,And console log dont's same to  Vue Devtools model

### What is Expected?
On wrong code, click AAAA and BBBB button,They become blue
### What is actually happening?
On wrong code,  click AAAA and BBBB button, just one button can become blue

Real code is use (this.$http.get) to get data

**Comment by fnlctrl** [comment]
http://jsfiddle.net/fv55rdwc/
```js
    created: function () {
    	// Use this.$set to add new reactive properties
      this.$set(this.selectOption.namespace, 'AAAA', false)
      this.$set(this.selectOption.namespace, 'BBBB', false)
    },
```
Please refer to: http://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
