### ISSUE TITLE
no error on src {{}},my html disappear

### ISSUE THREAD

**Issue by lin-hun** [vuejs/vue#4407]
vue2.0
When I write like this.
```script
<img class="componentImg" draggable="false" :src='{{name_url}}' />
```
The  result html will be like this.
![image](https://cloud.githubusercontent.com/assets/7136386/20970070/cc3ace14-bcc6-11e6-9c23-a7fe9f99468d.png)
My html disappear,but I cant find the error.

uh,I know the syntanx is an error that used for angular.

**Comment by fnlctrl** [comment]
You'll need a non-minified development build to see vue warning.
Please refer to: https://github.com/vuejs/vue/tree/dev/dist

**Comment by lin-hun** [comment]
thx
