### ISSUE TITLE
Warning at compilation when the template is invalid

### ISSUE THREAD

**Issue by xiaoyann** [vuejs/vue#4408]
### Vue.js version
2.1.4

### Reproduction Link
https://jsfiddle.net/xiaoyann/phL4cLht/

### What is Expected?
throw a warning or an error

### What is actually happening?
Although this [case](https://jsfiddle.net/xiaoyann/phL4cLht/) works well. But the result is not expected. And there are no any warning or error displayed so that it is very difficut to find the template mistake.

**Comment by defcc** [comment]
I'm looking into it. Maybe we could improve the parser,  or we could achieve it in vue-loader and vueify considering the compiler code size.

**Comment by mateuszgachowski** [comment]
@defcc have you considered using `DomParser`?

Example:
`document.body.innerHTML = new DOMParser().parseFromString('<div></p></div>', 'text/xml').documentElement.innerHTML`
