### ISSUE TITLE
Unsupport html tag <m/>

### ISSUE THREAD

**Issue by martyfan** [vuejs/vue#4411]
Vue.js version
2.1.4

I found that vue.js unsupport html5 tag 'm'
[Vue warn]: Unknown custom element: <m> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by defcc** [comment]
Should be `mark` element , right ? There is no `m` tag in html5.

https://www.w3.org/TR/html5/text-level-semantics.html#the-mark-element
