### ISSUE TITLE
Indirect help about upgrading from 2.0.7 to 2.0.8 or higher

### ISSUE THREAD

**Issue by paulocheque** [vuejs/vue#4412]
Hi, I created my project using the webpack a long time ago (initially using Vue 1.* version). I updated properly to use the 2.rc versions and now I can upgrade safely to 2.0.7.

If I update to 2.0.8 untill 2.1.4 I am getting an error in a another library I am using, not directly related to Vue. I checked the release notes (https://github.com/vuejs/vue/releases) but nothing appears to be related to me.

I would just asking for some tips. Do you guys think it is related to the Vue-Loader? Vue-Template-Compiler? Another library? Promises changes?

Information:
- I have a `library.js` in the `/static` directory and I link it directly in my `index.html` file.

Sorry about the abstract question and thanks in advance.

**Comment by defcc** [comment]
> If I update to 2.0.8 untill 2.1.4 I am getting an error in a another library I am using, not directly related to Vue.

Will you please provide more details ?

**Comment by yyx990803** [comment]
At least you can tell us what library it is and what errors you are getting?...

**Comment by paulocheque** [comment]
Hey, thanks for the fast answer.

About the error, unfortunately I dont have more information right now. I know this not enough, for that reason I would just expect some "hey, check the vue-loader version" or "maybe your webpack scripts need to be update because that change in 2.0.8" or something.

Well, too abstract even for me, sorry again about that.

**Comment by yyx990803** [comment]
Well, in that case we can't really help much since we cannot be held responsible for compatibility with arbitrary 3rd party libraries. Closing for now, but please follow up with more information if available (e.g. error stack traces, minimal repro)

**Comment by paulocheque** [comment]
Using the *Vue.js 2.1.8*

I identified the issue. It is something related to `v-if`. Check these 2 JSFiddles:

This one uses `v-show` and the book appears: https://jsfiddle.net/ao06u40n/
This one uses `v-if` and the book does not appear: https://jsfiddle.net/p62t9ozv/

Any ideas? Is some issue with `v-if`? Or some I am missing some `Vue.nextTick` or something?

**Comment by sirlancelot** [comment]
The epub framework is changing the DOM directly. When Vue is managing the DOM for you, these kinds of side-effects can happen. In good practice, you should not manually update any of the DOM hierarchy that Vue manages.

**Comment by paulocheque** [comment]
Thanks!
