### ISSUE TITLE
Vue2 just crashed in IOS8

### ISSUE THREAD

**Issue by sundaywill** [vuejs/vue#4413]
### Vue.js version
2.1.4

Vue just crashed in ios8, it did not start yet, just white page, network is well, dose not vue 2 support ios 8 ?

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by blacksunset** [comment]
+1

**Comment by luandapipi** [comment]
+1

**Comment by blacksunset** [comment]
Fixed, i used  filter: grayscale(100%); , but didn't  enable hardware acceleration.  just added 
`transform: translateZ(0);
  perspective: 1000;
  will-change:all;
  backface-visibility: hidden;`
