### ISSUE TITLE
slot  can't use in vue transtion component

### ISSUE THREAD

**Issue by alicePan** [vuejs/vue#4414]
Soucce code of  defined transition-demo component
```
<template>
  <div class="doc-ctn computed">
    <h4 class="ctn-title">transition</h4>
    <div class="ctn-demo">

      <transition name="demo">
        <!-- slot fangzai   -->
        <slot ></slot>
      </transition>
    </div>
  </div>
</template>
```
Then i use transition demo component in  parent component:
```
<transition-demo>
        I am disappearing
</transition-demo>
```

content ' I am disappearing' dose not rendered.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by TheDutchCoder** [comment]
Works fine: https://jsfiddle.net/z11fe07p/99/

**Comment by yyx990803** [comment]
In your usage the slot expands to a piece of plain text, which is not transition-able. Wrap it in an element like `<span>`.

**Comment by alicePan** [comment]
thanks a lot
