### ISSUE TITLE
Filter not recognized when filtered value contains a '/'

### ISSUE THREAD

**Issue by adriaanzon** [vuejs/vue#4415]
### Vue.js version
2.1.x

Works fine in 2.0.x

### Reproduction Link

https://jsbin.com/fuxitojugu/edit?html,console,output

### Steps to reproduce
Divide a number using the `/` operator, then apply a filter to it.
```vue
{{ price / 100 | currency }}
```

### What is Expected?
This divided number gets filtered, just like with other arithmetic operators.

### What is actually happening?
Get this error:

> "[Vue warn]: Property or method \"currency\" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

"currency" is the name of the filter here, but it got recognized as a property or keyword, not as a filter.

I think, as of this commit https://github.com/vuejs/vue/commit/38b8cfdf967ac684883e3356ce8277e9334f0522, the expression gets recognized as a regular expression because it contains a `/`.

**Comment by LinusBorg** [comment]
As a quick workaround: `{{ (price / 100) | currency }}`works.
