### ISSUE TITLE
slot couldn't add a 'slot' attribute on itself 

### ISSUE THREAD

**Issue by lynsun** [vuejs/vue#4416]
### Vue.js version
2.1.4

### Reproduction Link

http://codepen.io/anon/pen/GNGMGw
### Steps to reproduce
run the demo directly 
### What is Expected?
slot content in component foo should be displayed correctly
### What is actually happening?
i encounter a problem when  upgrading my project to 2.x，slot couldn't add a 'slot' attribute on itself in vue@2.x，but works well in 1.x， the upgrading guide has not mentioned the issue yet，finally ，i solve it by wrapping slot into a template tag

**Comment by fnlctrl** [comment]
http://vuejs.org/v2/guide/migration.html#slot-Attribute-Styling-removed
