### ISSUE TITLE
Custom vue filter always having a vue warn error not defined

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4420]
Im using filters for chunking arrays but errors pops up like this one

![image](https://cloud.githubusercontent.com/assets/19868205/21017459/65cd564a-bda4-11e6-8cd7-3b0e79594c49.png)

```
Vue.filter('chunk',(array, length) => {
  return _.chunk(array,length);
});
```

and use it to my component

```
    <transition-group v-for="data in dataList | chunk(3)"
                      class="row"
                      enter-active-class="animated bounceInRight"
                      leave-active-class="animated bounceOutRight">
      <div class="col-xs-12 col-md-4" :key="data['.key']">
        <md-card md-with-hover>
          <slot :data="data"></slot>
        </md-card>
      </div>
    </transition-group>
```

**Comment by fnlctrl** [comment]
The component seems to be lacking access to the filter.
Are you exporting a plain object inside `card.vue`?  If you're doing something like `export default Vue.component(...)` or `export default Vue.extend(...)` then it's the cause of the problem.
If not, please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a repo on github to reproduce the issue, thanks!

**Comment by yyx990803** [comment]
In 2.x filters only work in mustache interpolations and `v-bind`.

**Comment by dodiko1d** [comment]
${} - cant access filter. Thank you @yyx990803(Evan You).
