### ISSUE TITLE
Feature Request: vue-devtools for Firefox 

### ISSUE THREAD

**Issue by p-adams** [vuejs/vue#4422]
Is it possible to create a vue-devtools extension for Firefox? Also, what about enabling vue-devtools (Chrome, Firefox, etc) when not running on a server? In React, if I am just including React in my script, I am still able to use React's devtools; however, in Vue, (though I usually use vue-cli) if I want to enable the devtools I have to create a simple http server in order for Chrome to recognize Vue on the page.

**Comment by yyx990803** [comment]
1. This should be tracked in the vue-devtools repo (and yes there has already been such a request, but it's not high priority)

2. You need to check "allow access to file URLs" for Vue devtools in the extensions panel.

**Comment by sirlancelot** [comment]
vuejs/vue-devtools#57
