### ISSUE TITLE
Vue.set Data has been updated can not get

### ISSUE THREAD

**Issue by bigrocs** [vuejs/vue#4423]
`import Vue from 'vue'
import VueResource from 'vue-resource'
Vue.use(VueResource)

const vm = new Vue({
        data: { responseData: 'response1' }
});

class getJson {
    constructor(){
        Vue.http.get(Config.Api.mainUrl).then(function(response) {
            Vue.set(vm,'responseData','response5');
        });
        console.log(vm);
        console.log(vm.responseData);
    }
    routes(){
        return json.routes;
    }`

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
