### ISSUE TITLE
Why all values are not Dynamically Passed in Html using Vue JS?

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [vuejs/vue#4424]
Here, [Original Question](http://stackoverflow.com/questions/40927338/why-all-values-are-not-dynamically-passed-in-html-using-vue-js/40933103#40933103)

I can't pass the initial value from one component to another.
Value only changed on click only, event i can pass the value of "t_id" (here) directly, 
but i cant send 't_showList' value.

HTML (Template):

```
 <template v-if="showTemplate" id="segment_body">
    <div class="col-md-2" align="center">
      <b>Grid</b><br>
      <a href=javascript:void(0) @click="t_showList=false"><i class=""></i>Grid</a> |
      <a href=javascript:void(0) @click="t_showList=true"><i class=""></i>List</a>
    </div>
    <b>ID : @{{ t_id }}</b><br>
    <b>LIST : @{{ t_showList }}</b>
</template>
```

HTML (Data Source):

```
<script> var a = { list: false} </script>

 <div>
    <campaign_segment :t_id=1 :t_showList="a.list"></campaign_segment>
 </div>
```

VueJS :

```
Vue.component('campaign_segment', {
      template: '#segment_body',
      props: ['t_showList','t_id']
 });

```
OUPUT :

```
 ID : 1
 LIST : 
```

If i click Option "Grid",

OUTPUT :

```
 ID: 1
 LIST : False
```

What's wrong with this ?
Is i did anything wrong ?

**Comment by fnlctrl** [comment]
You should have received a warning that directly mutating a prop value is forbidden. Please use [Custom Events](http://vuejs.org/v2/guide/components.html#Custom-Events) to change the value instead.

**Comment by shankarThiyagaraajan** [comment]
OK, but here ID is successfully binded.
"LIST" only not able to bind on load.

Why this difference is there ?

**Comment by fnlctrl** [comment]
You didn't define `a` on the parent component, instead you wrongly defined it as a global variable.
For further questions, please use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/). Thanks!
