### ISSUE TITLE
How can i get the old value of of input type number on @change event

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4425]
I want to deduct the quantity of the item to another quantity 

For Example if

Item1.quantity = 100

Item2.quantity = 1000

this quantity will change on the @change event listener

if i deduct 2 in item1

item1.quantity = 98

item2.quantity = 1002

how can i achieve this

it seems that i dont get the old value 
```
                        :ref="item.stock"
                        :name="item.stock"
                        v-model.lazy="item.quantity" type="number" @change="deductQuantity(item,$event)">
```

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You can use a watcher on the value (item.quantity)
