### ISSUE TITLE
[Docs] No capitalized prop-names  w/ v-bind

### ISSUE THREAD

**Issue by valgaze** [vuejs/vue#4426]
**Problem**: The scenario below could trip up beginners if they use capitalized prop-names. ```v-bind:PROPNAME="item"``` isn't quite HTML (**[it looks almost like an XML namespace prefix](https://www.w3.org/TR/REC-xml-names/#NT-PrefixedName)**) but yet still must conform to HTML case-insensitivity behavior. If capitalized propnames are used on the directive & component template key & props array, the lookup will naturally fail.

**Proposal:** In v-bind docs/tutorial prominently flag out that since HTML is case-insensitive capitalized prop-names are not allowed. (Frankly I don't think it's worth expending the calories & taking the sure performance hit to check capitalization of props in components in order to fire a warning. Flagging a subtle thing like this in the docs would probably get the job done but curious what others think.)

**Example of issue:**
### https://jsfiddle.net/valgaze/z6buvpc2/

```html
<div id="app">
<ol>
<weird-todo-item v-for="item in todos" v-bind:propname="item"></weird-todo-item>
</ol>
</div>
```

```js
Vue.component("weird-todo-item", {
  template: "<li>{{propname.text}}</li>",
  props:["propname"]
})
new Vue({
el:"#app",
data: {
    todos: [{text:"A"},{text:"B"},{text:"C"}]
}
});
````
### https://jsfiddle.net/valgaze/am5a7629

```html
<div id="app">
<ol>
<weird-todo-item v-for="item in todos" v-bind:PROPNAME="item"></weird-todo-item>
</ol>
</div>
````

```js
Vue.component("weird-todo-item", {
  template: "<li>{{PROPNAME.text}}</li>",
  props:["PROPNAME"]
})
new Vue({
el:"#app",
data: {
    todos: [{text:"A"},{text:"B"},{text:"C"}]
}
});
```

**Comment by LinusBorg** [comment]
Well, I think this is already explained here: 

https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

Also: We have a dedicated repo for the website/docs: www.github.com/vuejs/vuejs.org

Please open a new issue there if you think this is still an issue. If you do, please try to answer these questions:

* Do you have any suggestions how the aforementioned can be improved? 
* Do you miss a link to this secion from somwhere else in the docs?

----
