### ISSUE TITLE
Filters are not accessibles inside another filter

### ISSUE THREAD

**Issue by yoannlecoguic** [vuejs/vue#4427]
### Vue.js version
2.0.2

### Reproduction Link
http://jsfiddle.net/5sH6A/951/

When i call a filter inside the params of an another filter, VueJs doesn't find it.
It works if i use a method instead.

**Comment by LinusBorg** [comment]
That is expected. This is not supported and won't be in the future.  use computed properties or methods if you need complicated nesting of filters.
