### ISSUE TITLE
Ambiguous component name error does not mention first character cannot be numeric.

### ISSUE THREAD

**Issue by ThePendulum** [vuejs/vue#4428]
When assigning a component name, it is matched against a regex that does not allow the first character of the name to be numeric. However, the error thrown only mentions that the component name has to be alphanumeric:

`Invalid component name: "0650475a". Component names can only contain alphanumeric characaters and the hyphen.`

Other than the typo 'characaters', the provided component name also matches the condition of the error. It would be helpful if ~~~either the regex or~~~ the error is changed accordingly.

Thank you in advance!

**Comment by phanan** [comment]
The component name can't start with a digit any more than HTML/XML tag names can't start with a digit, simply because the component name `'0650475a'` will be turned into a tag name `<0650475a>`.

**Comment by phanan** [comment]
Oh, I see you've modified the subject. In such a case, maybe a more helpful warning can be introduced.

**Comment by ThePendulum** [comment]
I understand that, but maybe the error message can highlight this fact?

**Comment by ThePendulum** [comment]
Heh, let me not edit that last message then since we're on this in real time; that is indeed what I was thinking, thanks! :)

**Comment by phanan** [comment]
Interestingly your issue just revealed a typo in Vue's source code. I'll see to that too.
