### ISSUE TITLE
devtools is always enabled when using `dist/vue.js`

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#4430]
https://github.com/vuejs/vue/blob/dev/dist/vue.js#L249

Notice this line of code, it will always be `true` what means even in production devtools will be enabled.

**Comment by yyx990803** [comment]
1. You can overwrite this in your application code.

2. Use `dist/vue.common.js` when bundling via Webpack or Browserify so you can control env variables.

**Comment by JounQin** [comment]
Thanks for your quickly answer.

But there is another weird code to me: https://github.com/vuejs/vue/blob/dev/src/core/util/env.js#L27

It seems to be a hack for webpack, what is the purpose?

Sorry for the interruption.

**Comment by posva** [comment]
@JounQin That's for SSR

**Comment by JounQin** [comment]
Hmm, I know it is for SSR, but why not preserving it to be `process.env.VUE_ENV` in `dist/vue.common.js` so that we can override it with webpack simply, although the code is very short.
