### ISSUE TITLE
transition的根元素如果样式表中有display:none，将导致过渡效果失效

### ISSUE THREAD

**Issue by heroazure** [vuejs/vue#4433]
以模态框举例，比如：.modal-mask {
  display: none;//其他样式省略
  transition: opacity 3s ease;
}
由于v-show仅仅只是添加或者移除内联的style="display:none;"，由于样式表中的display: none元素一直处于不可见状态

**Comment by fnlctrl** [comment]
如果使用v-show，就不能用样式表的display: none来设置初始状态，应该直接让v-show绑定的表达式的初始值为false。
