### ISSUE TITLE
Feature Request: determine if a reactive object is observed by any Vue instance

### ISSUE THREAD

**Issue by kailniris** [vuejs/vue#4437]
I would like to request a new feature.
I want to determine if a reactive object is observed by any Vue instances.

Example:
```
var obj1 = {name: 'obj1'};
var obj2 = {name: 'obj2'};

var app = new Vue({
  el: '#app',
  data: {
    item: {}
  },
  mounted: function onMounted(){
    this.item = obj1;
    this.item = obj2;
  },
  methods: {
    pickItem: function pickItem() {
    	this.item = items[this.pickedElemId];
    }
  }
});
```

I want to determine if _obj1_ is observed by any Vue instances. In this example it is clear that the _obj2_ is observed but _obj1_ is not.

The reasons behind this feature request is discussed in this issue:
https://github.com/vuejs/vue/issues/4384

**Comment by posva** [comment]
@kailniris Can you summarise the reasons or use cases behind the feature request, please? The thread is very long

**Comment by kailniris** [comment]
Short story is if you have a global data set which is fairly big and over the time when you make more and more objects reactive from this data set the memory consummation gets out of hand.

You can control the memory usage if you remove the unused observer properties and getter setters from the unobserved objects with a self rewrite deep clone, like:
`obj1 = _.cloneDeep(obj1); `

But in order not to remove observers from actually observed objects by Vue instances somewhere in the code you have to be sure the object is unobserved. This is why i require this feature.

In the linked issue there were suggestions for cloning the original object before make it reactive or freeze the object but these won't solve this issue cuz there are some situations where you need the observed objects reference to make mutations on it out from the Vue instance itself.
Here is a fiddle representing this use case: http://jsfiddle.net/bLaowkjf/9/

**Comment by fnlctrl** [comment]
You can already check it now using the (private) `__ob__` property.
```js
if (obj.__ob__) { ... }
```

Though I don't know if it's worth adding a public API for it. Maybe `__ob__` is good enough (at least for 2.0)?

**Comment by kailniris** [comment]
Even non observed reactive object has the `__ob__` property. Like in the example above the `obj1 `has the observer but its not observed by the `app` Vue instance.

**Comment by fnlctrl** [comment]
Well, normally `observed` means having been made reactive by Vue (having getter/setters and `__ob__`).
If you need to know if the object being observed is actually going to trigger view changes, you can go deeper and use the `__ob__.deps.subs` array.
```if (obj.__ob__ && obj.__ob__.deps.subs.length > 0) {/* If I'm changed the view will update */}```

Though it's still a `use at your own risk`-thing.

**Comment by kailniris** [comment]
Sorry for not being specific enough, i am still learning Vue.

The method You suggested is sufficient enough for this task.
What did you meant with "use at your own risk", what are the possible risks?
Anyway thanks you very much for the information.
Vue impresses me every moment.

**Comment by fnlctrl** [comment]
Well, since `obj.__ob__` is an undocumented private property which belongs to the internals of Vue, it's implementation is subject to change (e.g. renamed to `__foo__`). If you rely on this, you face the risk of it being changed some time in the future, undocumented.

**Comment by kailniris** [comment]
I understand. A public api would be needed for this then.
What are the chances? Could it be a feature in the future?

**Comment by kailniris** [comment]
The pattern discussed in this (https://github.com/vuejs/vue/issues/4384) issue is a suitable workaround for the problem so this feature request is unnecessary.
