### ISSUE TITLE
Component prop can't use style as prop name

### ISSUE THREAD

**Issue by iburning** [vuejs/vue#4438]
```
props: {
    style: {
      type: String,
      default: 'default'
    },

   test: {
      type: String,
      default: 'default'
    }
}
```

```
<my-button style="primary" test="primary"></my-button>

```

test works, but style is always 'default'

before v2.0.5 that's OK.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. `style` is a special attribute in Vue which is used for binding styles (as its name suggests), please rename your prop to something else.
