### ISSUE TITLE
Remove ROW performance decrease (2.1.3)

### ISSUE THREAD

**Issue by cj** [vuejs/vue#4439]
Seems like there is a performance issues with removing rows and v2.1.3, when running these benchmarks https://github.com/krausest/js-framework-benchmark

![](http://image.prntscr.com/image/55fa23b8c1e44500b95d672d985b414f.png)

**Comment by yyx990803** [comment]
It's normal for a specific benchmark to fluctuate between versions, and we do keep an eye on them. Please make sure to open issues that adheres to the guidelines.
