### ISSUE TITLE
Feature Request allow to change the value of scoped slots props

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4440]
Im doing something like this

In my scoped slot component
`    <slot :search="search" :searchKey="searchKey" name="search"></slot>`

In the parent 
```
      <template slot="search" scope="props">
        <md-button @click="props.search = 'Search Value'"> Owned Items </md-button> 
      </template>
```

**Comment by yyx990803** [comment]
You can simply pass in a method prop instead.
