### ISSUE TITLE
Circular References Between Components

### ISSUE THREAD

**Issue by xalexec** [vuejs/vue#4442]
https://jsfiddle.net/alexec/d6ksvd5b/1/

The [document](https://vuejs.org/v2/guide/components.html#Circular-References-Between-Components) say,Circular References with Vue.component can automatically resolved。

I understand it wrong ?

>When you look closely, you’ll see that these components will actually be each other’s descendent and >ancestor in the render tree - a paradox! When registering components globally with Vue.component, >this paradox is resolved for you automatically. If that’s you, you can stop reading here.

**Comment by yyx990803** [comment]
The error you are seeing is not related to circular references. You have an incorrect use of `v-else` which is leading to an infinite recursion.

**Comment by xalexec** [comment]
https://jsfiddle.net/alexec/d6ksvd5b/ 
I'm sorry, i provided the wrong code
I change the code ,make this is looks right.
But i have a another question.

In the new code, It can work like that
``````
<span v-if="child.children">
  <tree-folder :folder="child"/>
</span>
<span v-else>{{ child.name }}</span>
``````
It doesn't work like that
``````
<tree-folder v-if="child.children" :folder="child"/>
<span v-else>{{ child.name }}</span>
``````
> vue.js:2574 [Vue warn]: v-else used on element <span> without corresponding v-if. 

In that simple it can work.
https://jsfiddle.net/alexec/3c72kqqs/

**Comment by yyx990803** [comment]
/> is not valid closing syntax in HTML5. You need to close your tags explicitly.

**Comment by xalexec** [comment]
You are very nice, I understand this , thanks again.

**Comment by superchangme** [comment]
thank you very much
