### ISSUE TITLE
Invalid regular expression with vue.js and gulp-requirejs

### ISSUE THREAD

**Issue by sn00pee** [vuejs/vue#4445]
similar to  #4344 
I get an error: 
```
Parse error using esprima for file: /.../bower_components/vue/dist/vue.js
Error: Line 6386: Invalid regular expression
In module tree:
    src/js/main.js
      loadmore

    at /.../node_modules/gulp-requirejs/node_modules/requirejs/bin/r.js:23419:47
```
Line 6386:
`var regexEscapeRE = /[-.*+?^${}()|[\]/\\]/g;`

when using vue.js with requirejs
Doesn't happen when used with vue.min.js
### Vue.js version
2.1.4

**Comment by yyx990803** [comment]
This is likely a bug in requirejs rather than Vue.js.
