### ISSUE TITLE
vue-server-renderer got some trouble with v-html and slot

### ISSUE THREAD

**Issue by toxic-johann** [vuejs/vue#4447]
Vue.js version

2.1.4

Reproduction Link

https://codepen.io/toxic-johann/pen/RoYRWB

Steps to reproduce
just look at the console you will see the warning

What is Expected?
the server render html is right.i use createBundleRenderer.renderToString to do it.And i wish the client side run without waring

What is actually happening?

throw the warning

**Comment by yyx990803** [comment]
Hmm, you cannot use `v-html` on a custom component - `v-html` is just an alias for directly setting `innerHTML`, the content is not considered slot content. Slots are meant for content programmatically rendered by Vue.

You should probably just make the plugin-base component accept a string prop and use `v-html` inside it.

We might need to add a warning for that in the future.
