### ISSUE TITLE
Why i can't use prop(variable) to init loop value ?

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [vuejs/vue#4449]
Here i specify the [example](http://stackoverflow.com/questions/41094571/why-i-cant-use-variable-on-for-loop-in-vuejs).

For Loop will works fine when i pass int value directly.

Instead, if i pass variable for init the loop value, it returns empty.

**Sample Code :**

`<template id="segment" t_nb=2></template>
`
```
  <b>@{{ t_nb }}</b>
  <div v-for="a in t_nb">
    <seg>@{{ a }}</seg>
  </div>
```

**Output :**
       
     2
           

If, i specify value in directly,

```
  <div v-for="a in 2">
    <seg>@{{ a }}</seg>
  </div>
```

**Output:**
```

     1
     2
     <!-- Loop works -->      
```

What's wrong with this ?

**Comment by LinusBorg** [comment]
You can't define props on the `<template>` element used to define a components template - that's not how props work or what they are meant for.

Props are meant for passing data from a prent component *in the parent's template* to a child component

Please read the guide on props.
