### ISSUE TITLE
Options for setting the default transition-mode to out-in

### ISSUE THREAD

**Issue by adalberth** [vuejs/vue#4453]
When using vue 2.0 and vue-router 2.0 I want to make a ['Per-Route Transition'](https://router.vuejs.org/en/advanced/transitions.html) . But I also want the transition mode to be 'out-in'. https://jsfiddle.net/47gcfvg2/5/

I want my transition logic to exist inside the component it belongs to and I want to use JS to do it. But the transition mode is 'simultaneous' when using the 'Per-Route Transition'-technique. 

So if I want the transition-mode to be 'out-in' I have to wrap the 'router-view' with a transition. But then all my transition logic exists in the parent component. And if I want to have custom JS transition logic for each component it becomes complex very fast. https://jsfiddle.net/47gcfvg2/8/

So is it possible to create an option for setting the default transition-mode to out-in?

**Comment by simplesmiler** [comment]
I would guess things like transition mode can not really belong to the component itself. Imagine component A having transition mode `in-out`, while component B having transition mode `out-in`. How the transition between A and B would look like then? A is stuck waiting for B to finish the `enter` transition, while B is stuck waiting for A to finish the `leave` transition.

**Comment by adalberth** [comment]
Maybe your right. Im just using the example from https://router.vuejs.org/en/advanced/transitions.html and thats why I though that if you could change the default transition mode to 'out-in' you could solve the problem.

But A shouldn't way for B to enter. B should wait for A to leave and then enter - right?

**Comment by yyx990803** [comment]
Maybe #4361 can provide some reference - basically, you will need to implement a custom transition component so that when two instances of it are used together, they can coordinate the sequencing.

I think this may eventually be an entry under cookbook one day, or released as a separate plugin one day.
