### ISSUE TITLE
vue.js?3de6:427TypeError: (0 , _jQuery2.default)(...).isotope is not a function(…)

### ISSUE THREAD

**Issue by vondiplo** [vuejs/vue#4457]
Cannot seem to integrate jQuery plugins inside project.
Specifically when trying to add the isotope project (note, I didn't add the vuejsisotope as it didn't work as expected).
I tried adding this.$nextTick in created hook.

How do I add jquery plugins into vuejs 2.1 components?

Thank you,

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by vondiplo** [comment]
@fnlctrl, I apologies. The default text in comment wasn't in English so I didn't know how to respond to it. If I upload a jsfiddle with an example would it be possible to post it here and receive an answer?

**Comment by fnlctrl** [comment]
Sorry but no. Vue doesn't guarantee compatibility with arbitrary 3rd party libs/plugins.

**Comment by yyx990803** [comment]
FYI this seems like a babel ES module transpile issue, not related to Vue.
