### ISSUE TITLE
The font node in td rendered error

### ISSUE THREAD

**Issue by NewSilen** [vuejs/vue#4459]
The font node in td rendered error, the html seems ok but the font dose not display. The bug I found when upgrade vue from 1.0 to 2.0. code here. [https://jsfiddle.net/newsilen/m0qef51f/](url)

**Comment by yyx990803** [comment]
`<font>` is deprecated since HTML 4.1, in 2.0 it's being recognized as an SVG element and thus created with SVG namespace.

If you have control over it, you should not be using `<font>` in HTML anymore. Is there any reason that forces you to use it?
