### ISSUE TITLE
use extend and get custom class names

### ISSUE THREAD

**Issue by indus** [vuejs/vue#446]
Building custom Vue-Components and logging their instances to console is not very satisfying to me:

``` js
Sub {$el: div, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:19
Sub {$el: div, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:25
Sub {$el: div, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:31
Sub {$el: div, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:37
Sub {$el: div, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:43
Sub {$el: div, $parent: undefined, $root: Sub, $: Object, $$: Object…}      main.js:6
```

Actually all of the `Subs` are different Components. But besides that the last one is some sort of root I get no clue about their "class" and purpose.

Of course it is not that bad if you name your elements properly to get:

``` js
Sub {$el: div#apple, $parent: Sub, $root: Sub, $: Object, $$: Object…}            main.js:19
Sub {$el: div#orange, $parent: Sub, $root: Sub, $: Object, $$: Object…}           main.js:25
Sub {$el: div#basket, $parent: undefined, $root: Sub, $: Object, $$: Object…}     main.js:6
```

but a more telling `$parent` would be pleasing too, I think.
I don´t want to stringify them, but inspect their properties.
I would love to see that `extend(extendOptions)` gets a second parameter `customConstructor` (or some better solution of course ;-)

``` js
Vue.extend({/*extendOptions*/},
                    function MyClass (iOpt) { Vue.call(this, iOpt) });
```

I know that this is a lot just for some console cosmetic, but also take `typeof` and `instanceof` things into account.

**Comment by indus** [comment]
There is a bug when a component has a nested repeat: http://jsfiddle.net/u7nzpp9c/3/
the class name gets lost during compilation.

**Comment by yyx990803** [comment]
This is interesting... the class name actually shows MyClass in beforeCompile but changes in ready...
This seems to be a Chrome issue since it works properly in Safari's devtools

**Comment by yyx990803** [comment]
Isolated the issue: http://jsfiddle.net/yyx990803/uz3t4eo8/
Indeed a Chrome bug

**Comment by indus** [comment]
And I tried to track it in your code ;-) Stupid!
