### ISSUE TITLE
Component property undefined, Uncaught Reference Error

### ISSUE THREAD

**Issue by young-steveo** [vuejs/vue#4462]
### Vue.js version
2.1.4

### Reproduction Link
https://jsfiddle.net/0eLxm25L/

### Steps to reproduce
1) Create a new vue instance with a component that uses x-template string.
2) Use v-for on the component and pass data from the v-for expression to a component property.
3) Attempt to access the property in the template.

### What is Expected?
I expect to see the data passed in from the parent scope displayed in the component template

### What is actually happening?
`Uncaught ReferenceError: PROP is not defined` where PROP is the property referenced in the template.

Note:  If I add `note : {}` to the parent data object in the repro above, the bug goes away and the component renders properly.  However, this seems like unexpected behavior.

**Comment by yyx990803** [comment]
Why would you put the template script tag inside where Vue is being mounted on? Just move it outside...

**Comment by young-steveo** [comment]
Ah, that didn't occur to me; I guess it was late. Thanks.
