### ISSUE TITLE
Can't import vue-static-renderer in Webpack 2

### ISSUE THREAD

**Issue by digitalheir** [vuejs/vue#4463]
I get an error when I import vue static renderer in a script in Webpack 2. This is relevant when i want to use [static-site-generator-webpack-plugin](https://www.npmjs.com/package/static-site-generator-webpack-plugin).

### Vue.js version
2.1.5

### Reproduction Link
https://github.com/digitalheir/vue-2-webpack-2-bug

### Steps to reproduce
`npm run build`

### What is Expected?
Project compiles without errors

### What is actually happening?
```
WARNING in ../~/vue-server-renderer/build.js
6217:47 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ../~/vue-server-renderer/build.js
Module not found: Error: Can't resolve 'module' in '/home/maarten/WebstormProjects/vue-static-render-bug/node_modules/vue-server-renderer'
 @ ../~/vue-server-renderer/build.js 10:35-52
 @ ../~/vue-server-renderer/index.js
 @ ./app.js
```

**Comment by posva** [comment]
vue-server-renderer is meant to be used with node, on the server. `require` works differently in node and webpack. You can refer to this: https://github.com/vuejs/vue-hackernews-2.0 for more help

**Comment by digitalheir** [comment]
In that case, can this be a feature request because it would make prerendering much easier.

**Comment by JounQin** [comment]
@digitalheir you can see https://github.com/Atinux/vue-hackernews-2.0-lazy which implements lay loading for ssr for now.

**Comment by posva** [comment]
Or just use Nuxt: https://github.com/nuxt/nuxt.js
