### ISSUE TITLE
Regression: render components list with v-else & v-for

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vue#4464]
### Vue.js version
2.1.5

### Reproduction Link
https://jsfiddle.net/7jcoogfc/5/

### Steps to reproduce
Nothing to do, see output.
Using `v-if` and `v-else` to show message when empty list, or list of rendered components

### What is Expected?
List of 1,2,3,4 expected

### What is actually happening?
`undefined` rendered with 0 errors

In Vue.js 2.1.4 all works!

**Comment by defcc** [comment]
Nested VNode not normalized. I'll try to make a patch.

**Comment by s00d** [comment]
Not only components https://jsfiddle.net/7jcoogfc/6/

**Comment by yyx990803** [comment]
@defcc I'm looking into this as well

**Comment by defcc** [comment]
Got it :)

**Comment by yyx990803** [comment]
fix shipped in 2.1.6.

**Comment by tomByrer** [comment]
Patch works in [demo](https://jsfiddle.net/7jcoogfc/7/) also.  (Which I assume test is derived from.)
