### ISSUE TITLE
2.1.5 breaks app - TypeError: Cannot create property 'isRootInsert' on boolean 'false'

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#4466]
### Vue.js version
2.1.5

### Reproduction Link
working v2.1.4 - https://jsfiddle.net/7eje1znn/ 
not working  v2.1.5 - https://jsfiddle.net/74zsdfv5/

### Steps to reproduce
Just open fiddle with v2.1.5 and check the console.

### What is Expected?
Well it should work without throwing exception since I don't see any breaking changes in this new release regarding render function.

### What is actually happening?

It seems that Vue suddenly doesn't accept `false` value in array of children vnodes.. And if we change this line:

` labelLeft && label`

to ` labelLeft ? label : null`

then everything works correctly. No Error.

**Comment by defcc** [comment]
Seems that [false] node is not normalized

https://github.com/vuejs/vue/blob/dev/src/core/vdom/helpers/normalize-children.js#L31

**Comment by yyx990803** [comment]
fix shipped in 2.1.6.

**Comment by spyshiv** [comment]
Possible duplicate of https://www.jianshu.com/p/f9a6bba4a3cd
