### ISSUE TITLE
 Line 6460: Invalid regular expression

### ISSUE THREAD

**Issue by Davidzhu001** [vuejs/vue#4471]
node_modules/vue/dist/vue.js: Line 6460: Invalid regular expression
```
```
const $ = jQuery = require('jquery');
const bootstrap = require('bootstrap')
var fs = require('fs')
var path = require('path')
var Vue = require('vue/dist/vue.js');

function getDirectories(srcpath) {
  return fs.readdirSync(srcpath).filter(function(file) {
    console.log(file)
    return fs.statSync(path.join(srcpath, file)).isDirectory();
  });
}
getDirectories('./')
    var app = new Vue({
        el: '#main',
        data: {
            message: 'Hello .js!',
        }
    });
```

```

`  
`  "vue": "^2.1.6"`
`

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

**Comment by Davidzhu001** [comment]
@fnlctrl thanks
