### ISSUE TITLE
[2.1.5+]Multiple root nodes from functional component render function not allowed now?

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#4472]
### Vue.js version
2.1.5, 2.1.6

### Reproduction Link
[2.1.4] https://jsfiddle.net/uriziel01/kx1yuu3a/ [working]
[2.1.5] https://jsfiddle.net/uriziel01/kx1yuu3a/3/ [broken]
### Steps to reproduce
Return array of elements from render function in functional component.

### What is Expected?
Multiple root nodes seems to be dissallowed in Vue2 everywhere but not here.
I think that the correct solution would be to throw appropriate error to console and avoid returning `undefined`. Or is that designed logic and this should be handled by the engine as it was in older versions? You decide.
### What is actually happening?
`undefined` is rendered as a result and no correct error is thrown to the console.

**Comment by eachmawzw** [comment]
I met the same problem, I want to use version 2.1.4, what should I do?

**Comment by Uriziel01** [comment]
Use 2.1.5+ versions and encapsule all the elements in additional parents like so:
````
h('div', {}, [h('label', 'Test123'), h('label', 'Test123')];
````
Or just revert to 2.1.4 and wait to see what will happen with this Issue.

**Comment by eachmawzw** [comment]
The question has been decided.Thank you so much.

**Comment by Darkside73** [comment]
I use functional component as the only way to get rid of extraneous root component

**Comment by trusktr** [comment]
@yyx990803 This version should've bumped Vue to 3.0.0. It's completely breaking.

**Comment by trusktr** [comment]
Oops, nvm, forgot to rerun on jsfiddle with newer version, it works.
