### ISSUE TITLE
Props data passing between Parent to Child not working

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [vuejs/vue#4476]
Here, i use some list of data in Javascript variable to pass to VueJs Template Loop.

My Javascript Variable,

        var templates = {
                          0:{ 
                              'nb':1,
                              'column':2
                             },
                          1:{ 
                              'nb':1,
                              'column':2
                             }
                      }

My Parent Template is,

       <div v-for="(te,index) in templates" class="row">
            <campaign_segment :t_nb="te.nb" :t_column=te.column></campaign_segment>
       </div>

Parent Template's Source,

        <template v-if="showTemplate" id="segment_body">
                <b>@{{ t_nb }}</b>
                <div v-for="a in t_nb">
                   <block v-if="t_column == 4 || t_column > 4"></block>  // <== Child Template,
                 </div>
        </template>

Child Template's Source,

      <template id="campaignBlock">
         <b>HIT</b>
      </template>

My VueJS,

       // For Parent Template
        Vue.component(
        'campaign_segment', {
           template: '#segment_body',
           props: ['t_nb', 't_column']
         });

        // For Child Template
        Vue.component('block', {
             template: '#campaignBlock'
        });

In general,

               <div v-for="a in t_nb">
                   <block v-if="t_column == 4 || t_column > 4"></block>  // <== Child Template,
                 </div>

No loop were generated.

here, if i use,

                <div v-for="a in 2">
                   <block v-if="t_column == 4 || t_column > 4"></block>  // <== Child Template,
                 </div>

Loop working fine.

Whats wrongs with this ?

Why vuejs never uses the same instance to process the loop ?

Any Suggestions...!

Thanks in Advance !

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
