### ISSUE TITLE
beforeDestroyed hook is not triggered for a component which is switch another

### ISSUE THREAD

**Issue by webrsb** [vuejs/vue#4481]
### Vue.js version
2.0.6 & 2.1.6

### Reproduction Link
http://jsfiddle.net/3LtLk906/2/

### Steps to reproduce
Use render functions to switch between seperate component.

### What is Expected?
BeforeDestroyed hook will trigger When change another component.

### What is actually happening?
BeforeDestroyed is not triggered.

**Comment by yyx990803** [comment]
The hook name is `beforeDestroy`...

**Comment by webrsb** [comment]
Sorry, this is my shame..
