### ISSUE TITLE
the component render result is incorrect 

### ISSUE THREAD

**Issue by bruce4dev** [vuejs/vue#4483]
Hi,
Her are the question details:

I have an items list: 1,2,3
then I want to insert an new item: 4 in list, the rendered result is: 1,2,3,3. 
but the correct result should be: 1,4,2,3

this issue only in vue 2.0 version , vue 1.0 is right.

Below is the sample code:
====================

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>vue test</title>
</head>
<body>
    <div id="container">
        <h1>vue test</h1>
        <p>{{msg}}</p>
        <hr>
        <ul>
            <li v-for="item in items">
                <ui-item :context="item"></ui-item>
            </li>
        </ul>
    </div>
    
    
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script>
 

        Vue.component("ui-item", {
            template: "<div>{{vars.name}}</div>",
            props: ["context"],
            data: function () {
                return {
                    vars: this.context.getVars()
                };
            }
        });

        function Context(vars) {
            this.vars = vars;

            this.getVars = function () {
                return this.vars;
            };
        };

        var vm = new Vue({
            el: "#container",
            data : {
                msg: "hello, vue",
                items: [
                    new Context({id: 1, name: "1"}),
                    new Context({id:2, name: "2"}),
                    new Context({id: 3, name: "3"})
                ],
                children: []
            },
            mounted: function () {
                var self = this;
                setTimeout(function () {
                    self.items.splice(1,0, new Context({id: 4, name: "4"}) );
                }, 2000);
            }
        });
    </script>
</body>
</html>

**Comment by fnlctrl** [comment]
Please manually add a `key` attribute for the `v-for` item.
https://jsfiddle.net/qxq1h6qo/

More explanation: https://vuejs.org/v2/guide/list.html#key

**Comment by bruce4dev** [comment]
still not work when add key  @fnlctrl

**Comment by fnlctrl** [comment]
@bruce4dev https://jsfiddle.net/qxq1h6qo/

**Comment by bruce4dev** [comment]
how to process this case: iff there are no id filed to identify the data? use $index still not work.

**Comment by fnlctrl** [comment]
$index is removed in 2.0. Please refer to:
https://vuejs.org/v2/guide/migration.html#v-for-Argument-Order-for-Arrays-changed
