### ISSUE TITLE
Slot not working in root component instance

### ISSUE THREAD

**Issue by fvanwijk** [vuejs/vue#4485]
Vue.js 2.1.5 and vueify 9.4.0

### Steps to reproduce
index.html
```html
...
<div id="main">
  <p>Main contents</p>
</div>
...
```

bootstrap.js
```js
import Main from './main.vue';
new Vue({
  el: '#main',
  render(h) {
    return h(Main, this.$slots.default);
  }
});
```

Main.vue
```vue
<template>
  <div>
    <h2>Main</h2>
    <slot></slot>
    <test>Test contents</test>
  </div>
</template>
<script>
import Test from './test';
export default {
  name: 'main',,
  components: { Test }
}
</script>
```

Test.vue
```vue
<template><div><slot></slot></div></template>
```

Output should be `<h2>Main</h2><p>Main contents</p><p>Test contents</p>` but is `<h2>Main</h2><p>Test contents</p>`.

According to the documentation, `vueify` compiles the templates into render functions, but when bootstrapping the app (which is a JS file) you need to write a render function yourself, including filling of the slots.

It looks like `this.$slots` in the bootstrap does not contain any of the slots eg. `this.$slots.default` is `undefined`, perhaps because the component is not registered but just an instance?
The `anchored-heading` example is perfectly reproducible in this example app.

Is it possible to use slots when having a component created with `new Vue(...)`?

Alternative approach I had was to initialize Vue on the `#main` element without render function (thus no template). This was possible with Vue 1 but not with Vue because a render function is required.

**Comment by LinusBorg** [comment]
This compination of an in-DOM template and a custom render function won't work. This is expected behaviour.

Either you define a template in index.html for the root instance, or you define a render function. You can't have both,

```html
index.html should look like this:

<div id="main">
  <main>
    <p>Main contents</p>
  </main>
</div>
```
...and you remove this render function.
