### ISSUE TITLE
Vue should not mount when there is no element to mount to.

### ISSUE THREAD

**Issue by lsascha** [vuejs/vue#4486]
### Vue.js version
2.1.6

### Reproduction Link
https://jsfiddle.net/Lru3ans2/1/

### Steps to reproduce
create a new Vue instance with "el" set to an element that does not exist in the HTML.

### What is Expected?
Vue should not call "mounted" when there is no element on the page to mount to.

### What is actually happening?
"mounted" is called even though i don't expect Vue to mount to nothing (since there is no element)

**Comment by yyx990803** [comment]
When `el` is not available, the component mounts in memory (similar to calling `$mount()` without arguments).

There are warnings in the console telling you that the target `el` cannot be found. I don't think this needs a fix.

**Comment by lsascha** [comment]
Sure. That's what I noticed. 
Maybe it's more clear when I explain my usecase.

I wanted to create an vue application for a website. But that vue application is only used on a single page of the website. The Javascript however is inserted globally from the CMS.  I understood the documentation that mounted is only called when it mounts to memory, so there would not be much problem when using a XHR request in the mounted method to load a json.  However like this, the json is loaded on every page.

My current workaround is to remove el from the options and check if the element is avaliable. 
```
if (document.getElementById('app-contactsdb') != null) {
  contactsdb.$mount('#app-contactsdb');
}
```

It's not clear in the documentation that it mounts always.
