### ISSUE TITLE
Vue (1.0.28) not picking click event when rendered element is not in DOM

### ISSUE THREAD

**Issue by iFarmGolems** [vuejs/vue#4487]
Hello, I've made a small fiddle explaining the problem [here](https://jsfiddle.net/iFarmGolems/f77at1aa/).

This should be possible, right?

Can someone explain why is this happening? I am trying to write unit tests for my Vue module using Jasmine.

Thanks.

**Comment by facetothefate** [comment]
I think this is becasue the input elements don't append to the body element will not fire the change event.

Since the event is missing, the vue will not update the data.

Check this:
https://jsfiddle.net/facetothefate/4mhw6d22/3/

**Comment by posva** [comment]
As @facetothefate said, the element needs to be in the dom for the change event to fire
