### ISSUE TITLE
benchmark introduction is missing in the homepage

### ISSUE THREAD

**Issue by jinouwuque** [vuejs/vue#4489]
Hello. I am reading the material in the following page. 
https://vuejs.org/2016/04/27/announcing-2.0/

I notice that the benchmark page doesn't exist anymore. But I am really interested about it.
Do you know how can I get it?

Thanks

### Vue.js version
2.0.2

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue/tree/dev/benchmarks
