### ISSUE TITLE
Feature Request: Allow adding event handlers to Slots

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4495]
for example
`
<slot @click="method"></slot>`

this will surely used the method from the slot component and passed on the content using the methods inside the slot component?

**Comment by LinusBorg** [comment]
> this will surely used the method from the slot component and passed on the content using the methods inside the slot component?

I'm not sure I understand what you mean here, but it sounds like maybe [scoped Slots](https://vuejs.org/v2/guide/components.html#Scoped-Slots) woudl solve your problem?

**Comment by yyx990803** [comment]
This doesn't actually work because `<slot>` is an abstract placeholder that doesn't have an element of its own - it may expand into a single element, or multiple elements, or just text, the behavior of an event listener would be unpredictable based on what the content is.

Instead, just wrap the slot in an element and use event listeners on that wrapper.

**Comment by ealves-pt** [comment]
@yyx990803 according to your suggestion this should work: http://codepen.io/anon/pen/vyvMea?

I currently have this use case where I have a component that represents a `<list>` and a component that represents the `<list-item>`. When I click the `<list-item>` I emits a custom event that I'm trying to capture in the `<list-item>` component but nothing is being triggered.

Am I missing something?

Also, if I want to send an event from the `<list>` component down to all the elements inside the slot how can I achieve it?

**Comment by ealves-pt** [comment]
I think I managed to get this working with scoped slots and an event bus. Just don't know if it is the best approach at all: http://codepen.io/ealves-pt/pen/gLqOpg. Any comments?
