### ISSUE TITLE
Cannot use protocols inside anchors with v-bind

### ISSUE THREAD

**Issue by eliashdezr** [vuejs/vue#4496]
### Vue.js version
2.1.6

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/83/

### Steps to reproduce
```
  <a :href="mailto:email">Send us an email</a>
  <a :href="tel:telephone">Call us</a>
```
### What is Expected?
Anchors should work when using `v-bind ` with protocols (`mailto`, `tel`, etc.), so when used in websites on mobile phones should raise the proper applications to handle those events.

### What is actually happening?
Getting a compilation error on the template.

```
<div id="app">
  {{ foo }}
  <br>
  <a :href="mailto:email">Send us an email</a>
  <br>
  <a :href="tel:telephone">Call us</a>
</div>

- invalid expression: :href="mailto:email"
- invalid expression: :href="tel:telephone"
```

**Comment by fnlctrl** [comment]
v-bind expects javascript expressions and `mailto:email` isn't a valid javascript expression.
Simply remove the colon `:` to bind a string,
```html
<a href="mailto:email">Send us an email</a>
```
or bind a string with v-bind
```html
<a :href="'mailto:email'">Send us an email</a>
```

**Comment by eliashdezr** [comment]
@fnlctrl

I don't think that is a solution. I want the anchor to have the value of my binded property, so the out output should be something like this:`
`<a :href="mailto:email">Send us an email</a>`

To
`<a href="'mailto:someone@mail.com'">Send us an email</a>`

With the old syntax, would be something like this:
`<a href="mailto:{{ email }}">Send us an email</a>`

**Comment by fnlctrl** [comment]
<a :href="'mailto:' + email">Send us an email</a>
https://vuejs.org/v2/guide/migration.html#Interpolation-within-Attributes-removed

**Comment by arronf2e** [comment]
@fnlctrl  nice
