### ISSUE TITLE
v-for doesn't support String

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#4497]
Per the doc ( https://vuejs.org/v2/api/#v-for ), string iteration is supported, but I think it hasn't been implemented ( https://github.com/vuejs/vue/blob/dev/src/core/instance/render.js#L176 )

JSFiddle: http://jsfiddle.net/fenivana/5sH6A/969/

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
  </head>

  <body>
    <div id="app">
       hello <span v-for="v in foo">{{v}}</span>
    </div>

    <script>
    new Vue({
      data: {
        foo: 'foo'
      },

      el: '#app'
    })
    </script>
  </body>
</html>
```

**Comment by posva** [comment]
Nice catch, I'll add it
