### ISSUE TITLE
Unable to load filter with additional parameter

### ISSUE THREAD

**Issue by jayfk** [vuejs/vue#4498]
### Vue.js version
2.1.6

### Reproduction Link
https://github.com/jayfk/vue-filter-issue/blob/master/index.html

### What is Expected?
The filter to be loaded by vue.

### What is actually happening?
Error message: Failed to resolve filter: concat 'bar'

**Comment by fnlctrl** [comment]
https://vuejs.org/v2/guide/migration.html#Filter-Argument-Syntax-changed
