### ISSUE TITLE
transitions inside components don't apply the *-leave class

### ISSUE THREAD

**Issue by ostroso** [vuejs/vue#4502]
### Vue.js version
2.0.2

### Reproduction Link

http://jsfiddle.net/ost83/ot06gma2/
### Steps to reproduce
I've created a component with two different transitions inside for an appear effect. I've followed the documentation example for a simple toggle button, but it seems that the classes -leave and -leave-active aren't added to the elements, while the -enter and -enter-active classes are working fine. I've also added the original code from the documentation and it works without problems.
### What is Expected?
Reverse animation.
### What is actually happening?
Using the inspect web tool, it shows that the -enter classes are applied, while the -leave not.

(I think this is an issue, but I'm new to VueJS and I'm not 100% sure that I'm not doing something wrong. Sorry if this post is in the wrong place)

**Comment by facetothefate** [comment]
Hi, 
your animation is not right

check this:
http://jsfiddle.net/ot06gma2/9/

besides, with my listener method added, you can see the class added.

You need provide the right duration to your animation, your effect actually don't have any duration when leave, it will dispear directly.

**Comment by andreipfeiffer** [comment]
@ostroso I also had problems with CSS Transitions, using the *-leave, *-leave-active, *-enter, *-enter-active classes.

However, I've tried to replace them with CSS Animations, and it works as expected, plus you get more flexibility on defining the animation.

Take a look at this example:
https://github.com/andreipfeiffer/timjs.ro/blob/master/src/editionsVue/edition.css

**Comment by posva** [comment]
You're just missing the `-active` at

```css
  .image-anim-enter-active, .image-anim-leave{
    transition: all 1.5s .5s;
  }
```

**Comment by ostroso** [comment]
Urgh... was that simple... '-_-
Thank you guys! I definitely must do as @andreipfeiffer suggests with CSS Animations
