### ISSUE TITLE
Ability to stop updates to view upon exit transition

### ISSUE THREAD

**Issue by Eiskis** [vuejs/vue#4508]
I've been writing a demo application for an app that has a camera video recording interface. The (fake) video feed has a "Preview" label overlayed, which switches to "Recording 00:01" with the duration of the taping when the user starts capturing. When they tap "stop", I stop the recording and transition to a new view which shows the recording details.

Now, this is a small thing that I can engineer around easily, but as I transition out the label switches back to "Preview". This makes sense, I'm only showing the other message during recording but I have no "recording complete" state in this view; I don't really need it since I'm showing the result in a new view.

This got me thinking how nice it would be if I could simply tell Vue to stop pushing updates to the view as I prepare it for transitioning out. As I make my view more complex and add more elements, having to check for this `complete` state will be more work even though I don't want to do anything in the view after it's done recording.

Perhaps it could look like something along these lines:

- Support `vm.$freeze` and `vm.$unfreeze` methods that I can call before starting an exit transition
- Support something like `<transition freeze="out">` to make it easy to stop updates a view in the most common

There might be many other use cases for a generic freeze functionality of course, and TBH I was a little bit surprised that I could not find any info about this in the docs. I think this is similar situation to when you're transitioning out, let's say, a toast message and you need to keep the view populated with a message value for the duration of the transition even though it might not be the value of an observable parameter any more. In this case I'd want to be able to listen to a value of some message parameter that I've bound to my view and freeze updates if it's empty (meaning the control should maybe be on a parameter-by-parameter basis, although it might get tricky writing the logic that decides which updates should be reflected in the view and which not).

**Comment by posva** [comment]
You should be able to keep the state by using the `key` attribute on the transition. Here's an example: http://jsfiddle.net/posva/khd2ur97/
Tell me if that doesn't work and why so I can reopen the issue 😉

**Comment by Eiskis** [comment]
That's a neat trick, very useful to know! But if I understand this correctly, it doesn't work for me in this example I mentioned, because I'm transitioning a parent view via routing, not that specific element. When I transition my view out, I want nothing to happen to my rendered duration value, and I don't apply any transitions to it either. Maybe I could apply that somehow, I'd have to push that key up to parent views via references or something.

**Comment by posva** [comment]
Mmh, I'm having some trouble to understand your use case. Can you create a little demo, ideally on a jsfiddle, please?

**Comment by Eiskis** [comment]
Here's the demo app: http://jerryjappinen.com/dev/demo/#/recording/126

I applied a transition to the changing timestamp to try out your suggestion, but as you can see it still transitions to "0:00" at the end. I can very easily store this in a separate property but then I can't use a nice one computed for it and have to write a lot of extra code, and will have to do the same thing for other things I add to the view as well.

**Comment by Eiskis** [comment]
Another way of looking at this actually: can we make it possible for computeds to return whatever was the previous value?

**Comment by posva** [comment]
you can use the `:key` on the `router-view` component getting the key from the child. Caching the value somewhere else is an easy way of doing this in userland, so let's keep it how it is
