### ISSUE TITLE
Timing gap between transitions

### ISSUE THREAD

**Issue by softomatix** [vuejs/vue#4510]
Sometimes there is a gap between **enter** and **leave** transitions.

https://jsfiddle.net/2x6xyxLx/

This example looks a bit funky - I just try to reflect my real case where I use dynamic components. Here is the screenshot of what I mean:

![screenshot](https://cloud.githubusercontent.com/assets/12428252/21295464/78c2b9c0-c5ba-11e6-97e5-87fe3b6e0691.png)

Be patient to reproduce this issue - as I mentioned it happens only sometimes. 

There is no such problem in Vue 1.0:

https://jsfiddle.net/Lhf19n98/

Do you have any idea what is the reason for that? Is it a bug or I am doing something wrong?

**Comment by Yusoo** [comment]
在这个例子上使用新的v-leave-to，由red切换到blue时没有过渡效果
