### ISSUE TITLE
Invalid regular expression @6460 vue.common.js

### ISSUE THREAD

**Issue by ViktorPontinen** [vuejs/vue#4511]
### Vue.js version
2.1.6

### Steps to reproduce

Using the standalone build; vue.common.js

Running following gulp task:

```javascript
gulp.task('scripts', function(){
  return gulp.src('renderer/js/renderer.js')
    .pipe(plumber({
      errorHandler: function (error) {
        console.log(error.message);
        this.emit('end');
    }}))
    .pipe(browserify())
    .pipe(concat('main.min.js'))
    .pipe(gulp.dest('renderer/bundle/js/'))
    .pipe(browserSync.reload({stream:true}))
});
```

### What is happening?
`Parsing file ...\node_modules\vue\dist\vue.common.js: Line 6460: Invalid regular expression`

And getting `Failed to mount component: template or render function not defined. (found in root instance)` in browser. Which probably means that Vue didn't get built correctly in the gulp task.

Checking vue.common.js im suspecting it's the following line @6459:
```javascript
var regexEscapeRE = /[-.*+?^${}()|[\]/\\]/g;
```

### "Debugs" attempted

Commenting the whole line out seems to remove both the gulp error and the browser error and makes vue run.

Adding an extra `\` right after [\\] like so:
```javascript
var regexEscapeRE = /[-.*+?^${}()|[\]\/\\]/g;
```
also seems to remove gulp error, browser error and makes vue run.

**Comment by rekateka** [comment]
Not sure if this is related to this other one: https://github.com/vuejs/vue/issues/4445

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. That's a perfectly valid regex, so it's a bug of your js parser. https://www.debuggex.com/r/m5_-DylMNluN0e-_

**Comment by arielpchara** [comment]
Vue version 2.1.8 still have this problem
