### ISSUE TITLE
Problem when use v-else or v-else-if with v-for.

### ISSUE THREAD

**Issue by kciter** [vuejs/vue#4512]
### Vue.js version
2.0.3

### Reproduction Link
https://jsfiddle.net/7bhmonyv/1/
https://jsfiddle.net/7bhmonyv/3/ (Resolution)

### Steps to reproduce
1. Use `v-if` with `v-for` in `v-for`.
2. And then use `v-else-if` or `v-else` with `v-for`.

#### A
* 1
* 2
* 3
* 4
* 5
* 6
#### B
* 1
* 2
* 5
* 7
* 8
* 1
#### C
* [6]
* [3]
* [6]
* [2]
* [7]
* [3]

#### A
* 1
* 2
* 3
* 4
* 5
* 6
#### B
* 1
* 2
* 5
* 7
* 8
* 1
* 1
* 2
* 5
* 7
...
#### C
* [6]
* [3]
* [6]
* [2]
* [7]
* [3]
* [6]
* [3]
* [6]
* [2]
* [7]
* [3]
...

**Comment by ChangJoo-Park** [comment]
In [first link](https://jsfiddle.net/7bhmonyv/1/) case. , 
These are result when that codes through the `genFor(el)`

```js
_l((group.items), 
function(item){ 
  return _c('li',[_v("\nB."+_s(item)+"\n")]) 
})


_l((group.items),
function(item){
  return _c('li',[_v("\nC."+_s(item)+"\n")]) 
})


_l((group.items),
  function(item){ 
    return (group.type === 'A')? _c('li',[_v("\nA. "+_s(item)+"\n")]) : 
           (group.type === 'B')? _l((group.items), function(item){
            return _c('li',[_v("\nB."+_s(item)+"\n")])}) : 
                    _l((group.items), function(item){
                      return _c('li',[_v("\nC."+_s(item)+"\n")])
  }) 
})


_l((groups), 
  function(group){ 
    return _c('div', [_l((group.items), function (item) {
      return _c('li',[_v("\nA. "+_s(item)+"\n")])
    }), _v(" "),_v(" ")],true) 
  })
```
Generated B and C code before ternary. 

See [here](https://github.com/ChangJoo-Park/v-if-with-v-for) in [this line](https://github.com/ChangJoo-Park/v-if-with-v-for/blob/master/vue.js#L7559)

**Comment by defcc** [comment]
Currently v-for has higher priority.  Maybe we need to make it explicitly in the document.

**Comment by ChangJoo-Park** [comment]
@defcc It may be confusing.

**Comment by kciter** [comment]
I have found a code for priority. I need the document for people like me. :D
```js
// line 45 in src/compiler/codegen/index.js
if (el.staticRoot && !el.staticProcessed) {
    return genStatic(el)
  } else if (el.once && !el.onceProcessed) {
    return genOnce(el)
  } else if (el.for && !el.forProcessed) {
    return genFor(el)
  } else if (el.if && !el.ifProcessed) {
    return genIf(el)
  }
…
```

**Comment by defcc** [comment]
@ChangJoo-Park  yes, the result is right.

**Comment by yyx990803** [comment]
This is expected behavior, we will improve the docs to make the priority more obvious.

In the meanwhile your template can be simplified with a filter: https://jsfiddle.net/7bhmonyv/4/
