### ISSUE TITLE
$refs not creating an object when used with v-for object - instead always creates an array of DOM elements

### ISSUE THREAD

**Issue by theGC** [vuejs/vue#4526]
### Vue.js version
2.1.16

### Reproduction Link
https://jsfiddle.net/thebigsurf/5L5d5c7e/

### Steps to reproduce
run the fiddle and open your console

### What is Expected?
According to the docs: [https://vuejs.org/v2/guide/components.html#Child-Component-Refs](https://vuejs.org/v2/guide/components.html#Child-Component-Refs)

> When ref is used together with v-for, the ref you get will be **an array or an object** containing the child components mirroring the data source.

### What is actually happening?
`this.$refs` always contains an array of elements when used with v-for. This seems to go against what is suggested in the docs where I would expect the object `this.$refs.objectItems` to produce an object with a key for each DOM element.

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/api/#ref

> When used on elements/components with v-for, the registered reference will be an Array containing DOM nodes or component instances.
