### ISSUE TITLE
Form value binding not updating fast enough

### ISSUE THREAD

**Issue by sebastiaanluca** [vuejs/vue#4527]
Say I have a simple component with nothing but a `mounted` method that does the following:

```javascript
this.myValue = 'a value'

$(this.$el).parent('form').submit()
```

My component html looks like this:

```html
<form action="http://…">
    <input type="text" :value="myValue">
</form>
```

As you can see I'm using jQuery to submit the form and if both assigning the value and submitting the form happen in the same function, __empty data is submitted__. I can work around this by using a timeout with no delay, but of course that's not ideal.

```javascript
setTimeout(() => {
    $(this.$el).parent('form').submit()
})
```

This also happens when it's not in the mounted method, but for instance `on blur out`, so it has nothing to do with page load or delays. Same goes for `:value` versus `v-model`.

I don't know much of the internals of Vue or JS, but I presume it's because it hasn't been able to assign the values yet. Using a timeout, the submit occurs on the next tick.

**Comment by Yunfeng** [comment]
I thought there is no way to resolve the problem.

In this situation, I manually write param's value for ajax.

**Comment by sebastiaanluca** [comment]
Has this issue been posted before then? Couldn't find anything.

Well, in my case, I just want to submit the form automatically including the page refresh, don't want to (and can't) send it via Ajax. If there's no solution, perhaps a mention in the docs would be nice to have?

**Comment by defcc** [comment]
Use vm.$nextTick

```js
this.myValue = 'a value'

this.$nextTick(function () {
  $(this.$el).parent('form').submit()
})```
