### ISSUE TITLE
v-bind="obj" syntax with scoped slot

### ISSUE THREAD

**Issue by jacobmischka** [vuejs/vue#4529]
I'm trying to make a custom list component using a scoped slot like the one in the docs, and I would like to expose all of the item properties as props to the template. Unfortunately, the `v-bind="obj"` syntax doesn't seem to be working for me in a scoped slot. Is this deliberate?

Regular `v-bind:prop="obj.prop"` syntax is working correctly, but it would be great if I could expose everything at once.

I don't believe I'm making a mistake, but sincere apologies if I am, or if this has been mentioned somewhere else that I missed.

Thank you!

---

Entry point:
```vue
<custom-list :items="listItems">
	<template scope="item">
		<li>{{ item }}</li>
	</template>
</custom-list>
```

CustomList with implicit v-bind object binding:
```vue
<template>
	<ul>
		<slot v-for="item of items" v-bind="item"></slot>
	</ul>
</template>
```

Result:

![image](https://cloud.githubusercontent.com/assets/3939997/21364773/cddea38a-c6b7-11e6-8bed-b27cc7db6cf1.png)

CustomList with explicit prop binding:
```vue
<template>
	<ul>
		<slot v-for="item of items" :id="item.id"></slot>
	</ul>
</template>
```

Result: 
![image](https://cloud.githubusercontent.com/assets/3939997/21364761/c2423a78-c6b7-11e6-847c-3bfa737f0a73.png)

**Comment by jronwesternvp** [comment]
Here's what I did, I have an array of object instances of a specific class. That class has public functions in it and I need to invoke those functions on the template. It just seems the v-bind converts the passed value to a standard object. Is there any way I can invoke those class functions in there? Cheers.
