### ISSUE TITLE
render error with v-for

### ISSUE THREAD

**Issue by dyw934854565** [vuejs/vue#4532]
### Vue.js version
2.1.6

### Reproduction Link

[http://codepen.io/dyw/pen/XNGELL?editors=1111](http://codepen.io/dyw/pen/XNGELL?editors=1111)
### Steps to reproduce
when i use v-for on p element with a child element p, Vue render error.
change child p to span, or use a template wrapper, it works
### What is actually happening?
can not wrap p element with p?or any other problem

**Comment by fnlctrl** [comment]
Nested `<p>` tags isn't valid HTML.
http://stackoverflow.com/questions/12015804/nesting-p-wont-work-while-nesting-div-will
