### ISSUE TITLE
IE9  error log : " polyfill-eventsource added missing EventSource to window"

### ISSUE THREAD

**Issue by haochengxu** [vuejs/vue#4534]
A vue project works fine in other browser, including chrome, firefox. But in IE9, there is an error reported. 
Didn't test in other IE browsers, this is under dev mode with hot reload enabled.

Error picture.

![image](https://cloud.githubusercontent.com/assets/7252540/21386206/b90ea02c-c7ac-11e6-9f68-e1d0313d430a.png)

**Comment by fnlctrl** [comment]
That's webpack's behavior. Not related to vue.
