### ISSUE TITLE
Vue.js input[type=password] not working nicely with 1Password

### ISSUE THREAD

**Issue by kylewelsby** [vuejs/vue#4537]
### Vue.js version
2.1.6

### Reproduction Link
https://codepen.io/kylewelsby/pen/ENMMoM

### Observed on
Mac Chrome 55.0.2883.95 

### Steps to reproduce
With 1Password Chrome Extension installed and enabled
Click the Login Button
You will see 2 alert boxes with `onSubmit!`

### What is Expected?
The form submit event should be triggered once per button click.
You should see only 1 alert box with `onSubmit`

### What is actually happening?
When clicking a submit button type in a form, the form submit event is triggered more than once at a time.
This only happens when the field includes a `type=password`

**Comment by fnlctrl** [comment]
Sorry but it seems to be a problem of the plugin. 
Try binding the submit handle directly on the button with `@click="onSubmit"`, to prevent the plugin from messing with native dom events.
https://codepen.io/fnlctrl/pen/WomWym
