### ISSUE TITLE
Vue DevTools keep showing me it's version 1.0.26

### ISSUE THREAD

**Issue by rsm23** [vuejs/vue#4541]
I'm using vue with Laravel 5.3, and here is my packages file :
![screen shot 2016-12-22 at 1 20 55 am](https://cloud.githubusercontent.com/assets/2084708/21410966/1f1cfac0-c7e5-11e6-8155-5346864bb9df.png)

After install using **Yarn** or **NPM**, the DevTools keep showing my that I'm using version 1.0.26:

![screen shot 2016-12-22 at 1 15 33 am](https://cloud.githubusercontent.com/assets/2084708/21411002/58173d5e-c7e5-11e6-87b1-711c68fc363c.png)

**Comment by yyx990803** [comment]
Please open issue at the vue-devtools repo instead. Also try `console.log(Vue.version)` in your code to ensure you are indeed using the right version.
