### ISSUE TITLE
$watch returning same object for both fields

### ISSUE THREAD

**Issue by OmgImAlexis** [vuejs/vue#4543]
### Vue.js version
2.1.6

### Steps to reproduce
```
// main.js
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueStash from 'vue-stash';
import store from './services/store.js'
import routes from './services/routes.js'
import Home from './App.vue'

Vue.use(VueRouter);
Vue.use(VueStash);

const router = new VueRouter({
    routes,
    mode: 'history'
});

const app = new Vue({
    router: router,
    render: h => h(App),
    data: { store }
}).$mount('#app');
```

```
// store.js
export default {
    config: {
        layout: {
            comingEpisodes: null,
            history: null,
            home: null
        }
    }
}
```

```
// Home.vue
export default {
    name: 'home',
    store: ['config'],
    data () {
        return {
        }
    },
    mounted () {
        var vm = this;
        vm.$watch('config', function(x, y){
            console.log(x);
            console.log(y);
        }, {
            deep: true
        });
    }
}
```

### What is Expected?
Changes to config.layout.home to trigger the watch with new info.

### What is actually happening?
Changes to config.layout.home return the same object to both fields in $watch

I'm using [vue-stash](https://github.com/cklmercer/vue-stash) and I'm not sure if that's causing this but I found if I change the watch to be specific like config.layout.home I actually get the old and new values where as with just using config I get the new object twice.

I've tried simplifying this down from my project so I hope I haven't missed anything.

**Comment by OmgImAlexis** [comment]
I have a feeling it may have todo with config being a computed property because of vue-stash.

**Comment by fnlctrl** [comment]
http://vuejs.org/v2/api/#vm-watch

> Note: when mutating (rather than replacing) an Object or an Array, the old value will be the same as new value because they reference the same Object/Array. Vue doesn’t keep a copy of the pre-mutate value.

**Comment by OmgImAlexis** [comment]
So I'd need to watch strings to get around this?

**Comment by fnlctrl** [comment]
You can watch primitive values, or replace the watched object with a fresh
new one.
