### ISSUE TITLE
Reusable transitions with vue-router break in vue@2.1.6 (last one). Can reproduce.

### ISSUE THREAD

**Issue by zhenyong** [vuejs/vue#4545]
My initial purpose is to make transition  in [vue-router/examples/transitions](https://github.com/vuejs/vue-router/tree/next/examples/transitions) reusable.

Before change codes, transition works as a's expected:

1. vue-router@2.1.1 + vue@2.1.6 👍 
Expected  https://jsfiddle.net/feipigzi/uqotvzft/3/

Click `/parent` and `/parent/foo` , make slide left or right transition.

After make resuable, unexpected:

2. vue-router@2.1.1 + vue@2.1.6 (resuable transition) 👎 
Unexpected: https://jsfiddle.net/feipigzi/uqotvzft/

And I try to use older version vue.js, work as expected

3. vue-router@2.1.1 + vue@2.0.0-rc.4 (resuable transition) 👍 
Expected: https://jsfiddle.net/feipigzi/uqotvzft/2/

Increase version, unexpected again:

4. vue-router@2.1.1 + vue@2.0.0-rc.5 (resuable transition) 👎 
Unexpected: https://jsfiddle.net/feipigzi/uqotvzft/1

**Comment by posva** [comment]
I don't see the issue. 1 and 2 yields the same result
Can you give use more details please?

**Comment by zhenyong** [comment]
Slow down transition, click `/parent` then click `/parent/foo`, different dom class

1. https://jsfiddle.net/feipigzi/uqotvzft/3/
￼![](http://ww4.sinaimg.cn/large/68ef88dagw1fazpgjbv6cj20ui07ojtm.jpg)


2. https://jsfiddle.net/feipigzi/uqotvzft/
￼![](http://ww2.sinaimg.cn/large/68ef88dagw1fazphsxc5oj20us0co425.jpg)

**Comment by posva** [comment]
ooh, one transition goes to the right instead of the left

**Comment by zuibunan** [comment]
I have a similar problem
vue2.1.7
vue-router2.1.1
vuex 2.1.1

app.vue
```
...
<keep-alive>
   <router-view ></router-view>
</keep-alive>
...
```

pageA.vue
```
<container ...>
</container>
```

component container.vue
```
  <transition @after-enter="onViewIn(0)" @after-leave="onViewOut(0)" :name="theTransitionName">
    <div class="container" :transition-name="theTransitionName">
      <slot></slot>
    </div>
  </transition>
```

transition component seems slow down one step when i use keep-alive and put transition component in each route view

this is my spa transition snapshots

1: first load
![image](https://cloud.githubusercontent.com/assets/3386786/21475129/78ae5d4c-cb62-11e6-81fb-c42eca5f6f4a.png)

2: forward
![image](https://cloud.githubusercontent.com/assets/3386786/21475134/9078ee56-cb62-11e6-8fc0-e7af705f6e70.png)

3: back
![image](https://cloud.githubusercontent.com/assets/3386786/21475138/9af2ad18-cb62-11e6-9d42-a640ea2a75da.png)

**Comment by TiBianMod** [comment]
With vue@2.1.6+ I have also problems with the transitions.
> Note: I'm using only Vue


```vue
<transition
        enter-active-class="transitionEnter"
        leave-active-class="transitionLeave"
>
    <div v-show="show">
        <slot></slot>
    </div>
</transition>
```
First I see the empty component and after start the transition,
is like the directive v-show is not working.

I hope this will be fixed in next version :)

**Comment by zuibunan** [comment]
My problem remains even though upgrade to 2.1.8, maybe I should provide a demo
https://github.com/vuejs/vue/issues/4545#issuecomment-269163326
