### ISSUE TITLE
VueJS cached placeholders issue with external plugins 

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue#4546]
### Vue.js version
2.0.2

### Reproduction Link
http://jsfiddle.net/5sH6A/976/

### Steps to reproduce
Click on event 3 , then click add event

### What is Expected?
The event 3 should stay highlighted while the rest should not.

### What is actually happening?
The placeholder of event 3 is highlighted instead of the actual event 3 

This is happening because of a plugin we are using. I know I could switch to make vue add the class instead based on the object but would rather let this plugin handle in this case.

**Comment by LinusBorg** [comment]
`<p v-for='event in events' :key="event">`

**Comment by lukepolo** [comment]
Ah clever thank you!
