### ISSUE TITLE
Custom filters should be working on v-html.

### ISSUE THREAD

**Issue by maxKimoby** [vuejs/vue#4549]
The v-html attribute should be able to use filters because it is only use to display formated text. This should be working :

`<span v-html="myParam | line_break"></span>`

Where, in this case, line_break detect \n and replaces them with `<br />`

**Comment by defcc** [comment]
I agreed. Maybe we could improve it for text transformation purposes.

**Comment by yyx990803** [comment]
This would become a special case. Now the rules becomes more complicated. And I fear it would slowly bring the feature creep back to "all directives should support filters".

In this case, a dedicated sanitization method works just fine. I don't think it's worth it to open a special case for the simple rules.
