### ISSUE TITLE
suggest use another name for scoped slot other than "template" tag-name

### ISSUE THREAD

**Issue by kaven276** [vuejs/vue#4551]
a .vue file has root elment `<template>`, but vue support scoped slot using `<template>` also,
when in atom editor, vue code bueatify will always trim indent with `</template>`,
I suggested that the vue component file perserve root element name with `<template>`, but use another name for scoped slot.
```
<template>
...
<div class="parent">
  <child>
    <template scope="props">
      <span>hello from parent</span>
      <span>{{ props.text }}</span>
    </template>
  </child>
</div>
...
</template>

<script>
...
</script>
```

**Comment by yyx990803** [comment]
We obviously can't introduce a breaking change just because Atom can't indent the code correctly...

**Comment by kaven276** [comment]
scoped slot can use `<template>` tag as before, but we can introduce another tag like `<container>`, `<context>` or `<door>` and some other suitable tag that behave just same as `<template>`, it will not introduce a breaking change, but avoid the same word with .vue root element `<template>`

**Comment by posva** [comment]
@kaven276 `template` is a reserved html tag that fits well our needs. What you should do is open an issue in the atom plugin repository so they can fix it. `template` tags can be inside other `templates`
