### ISSUE TITLE
`$mount` and `created` behavior changed

### ISSUE THREAD

**Issue by mrkishi** [vuejs/vue#4552]
Hello, folks.

This is likely an edge case, but the `vm.$mount()` behavior was silently changed in the recent versions. Previously, we could call `$mount` from a `created` callback just fine, but now (at least 2.1.5-2.1.6) it fails.

### Vue.js version
2.1.6

### Reproduction Link
https://jsfiddle.net/rdjjpc7a/895/ - this is of course a silly example, since `target` could be passed in as `el`, but you get the idea.

### What is Expected?

I'm not implying the previous behavior was correct, as it's simple enough to call `$mount` after the Vue constructor returns. However, it'd probably be wise to note in the docs it shouldn't be called from the `created` callback. I naively thought `created` would happen _at least on the next tick_ (the docs clearly state it's called synchronously, though), which is obviously not the case as the component is not fully ready by the time it is called -- but it is right after the constructor returns.

**Comment by yyx990803** [comment]
Well, this was not explicitly documented, but as you suspected it was never designed to work that way. All examples call `$mount` after instance has been created, and it worked only by accident. Feel free to submit a PR to https://github.com/vuejs/vuejs.org/ to add a note about this.
