### ISSUE TITLE
Wrong scope in directive "bind" hook

### ISSUE THREAD

**Issue by StarpTech** [vuejs/vue#4555]
### Vue.js version
2.1.16

### Reproduction Link

https://jsfiddle.net/e8wfkv3q/1/ with Vue 1.0.16 has the correct scope of the directive

https://jsfiddle.net/68cs9a23/1/ with Vue 2.1.6 has Window as scope.

### What is Expected?

The context should reference to the current directive scope.

### What is actually happening?

In 2.1.6 the directive bind hook has the wrong scope.

**Comment by posva** [comment]
Directives have been simplified, my friend 😄 : https://vuejs.org/v2/guide/migration.html#Custom-Directives-simplified
There's no more `this` in them

**Comment by StarpTech** [comment]
@posva thanks!
