### ISSUE TITLE
tr couldn't be wrapped by template in IE9-11

### ISSUE THREAD

**Issue by lynsun** [vuejs/vue#4563]
### Vue.js version
1.0.28

### Reproduction Link
http://codepen.io/sugarboy/pen/GNaevV

### Steps to reproduce
run the demo

### What is Expected?
table is rendered correctly in all browser include IE

### What is actually happening?
table rendering is ok in  modern borwser such as chrome but incorrect in IE. if i don't use template,it's ok

**Comment by simplesmiler** [comment]
This is a limitation of some browsers. You can work around that by putting `v-for` directly on `tr`, or by using `tbody` in place of `template` within tables. More details in docs: http://v1.vuejs.org/guide/components.html#Template-Parsing

**Comment by lynsun** [comment]
thx
