### ISSUE TITLE
<template> tag with v-for render undefined

### ISSUE THREAD

**Issue by shjyh** [vuejs/vue#4564]
if i use a Array as a prop of custom component,
the template element with v-for directive just render undefined

```
<component :list="list"></component>
<template v-for="item of list">{{item.name}}</template> <!-- output undefined -->
```

it's strange.
only template element tag has this problem.
 

### Vue.js version
2.1.7

### Reproduction Link
simple demo here
https://github.com/shjyh/vue_error_demo/tree/master/2016-12-26

**Comment by posva** [comment]
The `template` tag is meant to wrap multiple elements like:

```html
<template v-for="item in list">
   <span>{{ item.key }}</span>
  <span> {{ item.name }}</span>
</template>
```

In your case you should simply use `<span v-for="item in list"></span>` to wrap the text nodes

**Comment by shjyh** [comment]
I know.
but the real scene in my code is more complex than this demo. I need to wrap multiple elements in a template tag, but the output is undefined.
and it works all right in v2.1.6.
it seems all v-for directive inside a template tag output undefined if there's child component with props bind before the tag.
like this:

```
<component :list="list"></component>
<template v-if="ready">
        <div v-for="item of items">{{item.name}}</div> <!--here undefined-->
        <!-- ...other -->
</template>
```

and is this the expected behavior?

**Comment by posva** [comment]
It's very weird, indeed. I'll give it a look this afternoon.

**Comment by shjyh** [comment]
at least the template like:

```
<component :list="list"></component>
<template v-for="(item,index) of list2">
    <div>{{index}}</div>
    <div>{{item.name}}</div>
</template>
```
works wrong.

and sometimes the v-for directive inside a template tag also output undefined, and works ok if I modified some code. I really don't know how it happen;

**Comment by simplesmiler** [comment]
Does happen in 2.1.7: https://jsfiddle.net/14dtfh51/8/
Does not happen in 2.1.6: https://jsfiddle.net/14dtfh51/9/

**Comment by defcc** [comment]
Seems an issue with normalize children. I'll try to make a patch.

**Comment by dankuck** [comment]
I'm still seeing a similar problem when running against the latest code.

Example: https://dankuck.github.io/TiltMaker/buggy.html

References: https://cdn.rawgit.com/vuejs/vue/dev/dist/vue.js

Github: https://github.com/dankuck/TiltMaker

**Comment by buzdykg** [comment]
So, what's going on here.. Any updates?

**Comment by posva** [comment]
if there's a bug, please, open a new issue with the corresponding repro

**Comment by doydoydoy** [comment]
Any updates regarding this? I am getting the same error. My code is very similar to the first post.

**Comment by Nirazul** [comment]
As many will stumble upon this issue:
It's already been fixed in vue@2.5.1, the latest version currently being [vue@2.5.2](https://github.com/vuejs/vue/tree/v2.5.2).

Issue:
https://github.com/vuejs/vue/issues/6790

Commit:
https://github.com/vuejs/vue/commit/1f84dd1c2488d12ef144d4b548b0e80647f9403c

Release:
https://github.com/vuejs/vue/tree/v2.5.2

**Comment by dankuck** [comment]
I finally solved my problem when I realized that I was loading a separate version of Vue on the page. Only the one webpacked into my distribution files was necessary.

**Comment by zikyfranky** [comment]
I was facing the same issue, and nothing on here solved I for me (using Vue3)

After lot of frustration, I discovered I caused the issue, as I was binding v-for, check your code, it should be `v-for=""` and not `:v-for=""`

I only had to remove the colon `:` and it works now.
