### ISSUE TITLE
<slot> doesn't support <my-tag /> syntax

### ISSUE THREAD

**Issue by roroco** [vuejs/vue#4566]
### Vue.js version
2.1.7

### Reproduction Link

https://jsfiddle.net/roroco/8jt5txac/

### What is Expected?
I hope vue support `<my-tag text="my text" />`  like android xml
### What is actually happening?
In my ins, it only show one `<li>` when i use `/>`,  when i change it to `></my-tag>` it will show all `<li>`

**Comment by posva** [comment]
That's a browser limitation. If you want to use that syntax you should use a bundler like webpack and use vue-loader so you're not limited by the browser to write html. In `vue` files you can write things like

```html
<MyTag/>
<my-tag/>
```

Also this may help: https://github.com/vuejs/vue-cli
