### ISSUE TITLE
possible bug with float numbers

### ISSUE THREAD

**Issue by ctf0** [vuejs/vue#4569]
### Vue.js version
2.1.6

### Reproduction Link
http://codepen.io/ctf0/pen/LbKYjg

### Steps to reproduce
1- select all items then unselect them one by one

### What is Expected?
when all are unselected the `total` should be `0`

### What is actually happening?
![screen shot 2016-12-26 at 6 15 31 pm](https://cloud.githubusercontent.com/assets/7388088/21484199/64b2e3c8-cb97-11e6-944e-3e9a1e0437d0.jpg)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. This is actually not related to Vue, but Javascript's floating point number's precision issue. You may refer to: http://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by ctf0** [comment]
many thanx, the fix was simple using `{{ parseFloat(total).toFixed(2) }}` 👍
