### ISSUE TITLE
请问v-touch:tap 绑定的事件，我如何通过代码触发

### ISSUE THREAD

**Issue by worry127722** [vuejs/vue#4575]
你好，我的代码中是这样写的，如下图所示
![image](https://cloud.githubusercontent.com/assets/6937117/21492363/fdc4cb60-cc3e-11e6-952d-c04980fd01b1.png)

我现在想要通过代码触发这个tap事件，请问代码应该怎么写？
我的意思是：我想通过document.getElementsByTagName().click(),类似这种代码实现触发tap事件，请问代码应该怎么写？

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！
