### ISSUE TITLE
TypeError: Cannot read property 'componentOptions' of undefined

### ISSUE THREAD

**Issue by billwing** [vuejs/vue#4577]
### Vue.js version
2.1.3

### Steps to reproduce
Deploy to server but failure. Show the errors:

    [ERROR]     at renderElement (/home/leanengine/app/node_modules/vue-server-renderer/build.js:6102:5)
    [ERROR]     at renderNode (/home/leanengine/app/node_modules/vue-server-renderer/build.js:6055:7)
    [ERROR]     at next (/home/leanengine/app/node_modules/vue-server-renderer/build.js:6187:9)
    [ERROR]     at cachedWrite (/home/leanengine/app/node_modules/vue-server-renderer/build.js:36:9)
    [ERROR] error during render : /
    [ERROR] TypeError: Cannot read property 'componentOptions' of undefined

### What is actually happening?
I'm not sure the errors happen with code or server.

**Comment by LinusBorg** [comment]
Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.
