### ISSUE TITLE
In the image upload using FileReader, change the value of VM, the file will become empty

### ISSUE THREAD

**Issue by baixiaosh** [vuejs/vue#4578]
code:
template:
<input type="file" v-on:change="onFileChange">
js:
data(){
 return {
  test:''
 }
},
onFileChange(event){
let files = event.target.files
let reader = new FileReader()
reader.onload = (event)=>{
 let img = new Image()
  img.onload = () => { 
  console.log(files[0]) //has file
 }
}
reader.readAsDataURL(files[0])
}

but:
onFileChange(event){
let files = event.target.files
let reader = new FileReader()
this.test = 'test val'
reader.onload = (event)=>{
 let img = new Image()
  img.onload = () => { 
  console.log(files[0]) //undefined
 }
}
reader.readAsDataURL(files[0])
}

**Comment by baixiaosh** [comment]
"vue": "^2.1.4"

**Comment by LinusBorg** [comment]
Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If nessessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .


Thank you.

**Comment by baixiaosh** [comment]
https://jsfiddle.net/u5gddcah/

**Comment by baixiaosh** [comment]
https://jsfiddle.net/u5gddcah/1/

**Comment by baixiaosh** [comment]
https://jsfiddle.net/u5gddcah/2/

**Comment by baixiaosh** [comment]
Thank you,  I found the wrong

**Comment by yyx990803** [comment]
You have a `value` binding to `null`, which is not needed for `<input type="file">`. This is expected behavior. Just remove the `value` binding and it works properly.
