### ISSUE TITLE
vue-router will not work when vue components render throw error

### ISSUE THREAD

**Issue by chrisbing** [vuejs/vue#4580]
### Vue.js version
2.1.7

### Steps to reproduce
I am using vue2.1.7 and vue-router 2.1.1.  I found that when vue ```render``` throws an error, the router will not work (when back and forward by browsers , pages can't change, and ```render``` function will not be called anymore ) .

So I read the source code of Vue,  found that there is no try-catch on render function.

I wrote the code in my project as follow to catch the error:
```javascript
// vue fix
const h = new Vue().$createElement

let _render = Vue.prototype._render

Vue.prototype._render = function () {
    try {
        return _render.apply(this, arguments)
    } catch (e) {
        console.error("Error when render called : ", e)
        return h()
    }
}
``` 

I wander if you removed try-catch for performance on purpose,  or just forgot it .

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by yyx990803** [comment]
Also, please open this issue at the vue-router repo instead. Thanks.

**Comment by Ghjsw** [comment]
gd
