### ISSUE TITLE
Can I help with anything?

### ISSUE THREAD

**Issue by syntacticsolutions** [vuejs/vue#4587]
Hey guys, I'm really glad to see you guys working on this project. This is going to be so amazing. I have a little bit of a background with Java and I use VueJS on any and all projects that I possibly can. I was wondering if I could help with this project. Even If it's just writing documentation. I'm glad to help in any way that I can.

**Comment by yyx990803** [comment]
Hi @syntacticsolutions , thanks for the interest to help. There are many ways to help but it really depends on what you are familiar with. The simplest way to help is answering questions for other users on the forum, Gitter chatroom or StackOverflow; you can also try to help triage new issues by narrowing down bugs or even submit PRs. Please read [the contribution guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) for more details.

Note that issues are reserved for bug reports and feature requests, no please keep that in mind in the future.
