### ISSUE TITLE
$item parameter for event handlers

### ISSUE THREAD

**Issue by andrisi** [vuejs/vue#4588]
I love that Vuejs is data bound, and so it would be nice to have a parameter for v-on that would refer to the data item, array element, etc. that was used to build the element clicked, hovered over, etc. So let's say I'm working on a drag & drop component, based on a data array (v-for item in array), that would avoid all html-manipulation by changing the underlying data (item.category = ... or item.position = n), and instead have Vuejs update the html. For this I would need a reference to the data to modify. I would like to receive the data element, array index, object property in some form. Something like $event. Could be $item. This is doable without a magic param like $item, for example adding data elements, but that would be visible in the html source. And would not be so elegant anyway.

**Comment by yyx990803** [comment]
You already have the `item` alias that points to the item, why would you need a magic param for that? I may not be understanding you correctly but I don't really see the need for this.
