### ISSUE TITLE
Render error with keep-alive children.

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#4590]
### Vue.js version
Vue: 2.1.7, VueRouter: 2.1.1

### Reproduction Link

https://jsfiddle.net/JounQin/s9vgy7gu/

### Steps to reproduce
Click router-link B, then Home, then A

### What is Expected?
Should not render CompB when going to A.

### What is actually happening?
CompB is rendered.

**Comment by shidianxia** [comment]
Seems similar to my issue #4633 
Anyone can help?
