### ISSUE TITLE
Microchange for capitalize function

### ISSUE THREAD

**Issue by vlashchanka** [vuejs/vue#4593]
I suggest microchange for capitalize function:
`var capitalize = cached(function (str) {
  return str.charAt(0).toUpperCase() + str.slice(1)
});`
`var capitalize = cached(function (str) {
  return str.[0].toUpperCase() + str.slice(1)
});`
https://i.stack.imgur.com/tNwKk.png

**Comment by yyx990803** [comment]
Thanks for the suggestion, but `charAt` always returns a string while `[0]` does not (can be `undefined`).
