### ISSUE TITLE
var Component = this.$options.components.inputFile;

### ISSUE THREAD

**Issue by suifengfengye** [vuejs/vue#4596]
var Component = this.$options.components.inputFile;
      new Component({
        parent: this,
        el: el
      });

when use vue 2.0.3, it work ok!

but when I updated vue to 2.1.7, there is a Uncaught TypeError:
Uncaught TypeError: Component is not a constructor.

What happen?

**Comment by yyx990803** [comment]
`$options.components` are no longer turned into constructors for you. This is considered an internal change because the behavior was never explicitly defined in the documentation.

You can simply `Vue.extend()` it before using `new`.
