### ISSUE TITLE
What's the alternative renders way?

### ISSUE THREAD

**Issue by lavezzi1** [vuejs/vue#4600]
Hello everyone,

I do multiple page app.  In vue 1.0.28 I used to have html & js file for each page:

Example

**index.html**
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <META http-equiv="X-UA-Compatible" content="IE=11">
        <title>Page – Title</title>
    </head>
    <body>
        <div id="app">
            <alert align="center" type="success">Your account was updated successfully.</alert>
            <div class="">Another html elements that display immediately</div>
        </div>
    </body>
</html>
```

**index.js**
```
import Alert from './library/alert';
new Vue({
    el: '#app',
    components: {
       Alert
    }
})

```

So it works perfect. Now I am upgrading to vue 2.1.8 and actually don't understand how to work in the same direction. 
I got this error: 
```
Failed to mount component: template or render function not defined. 
(found in root instance)
```

**Important thing:** I don't want to write all html inside of template in App.vue, I want display all elements immediately on the page, and then when vue is initialized show components. 

I use webpack 1.13.1. Config: https://gist.github.com/lavezzi1/5bb6db29a19a2ca4b1ec08c4a01b19f5

Thanks!

**Comment by LinusBorg** [comment]
Add this to your webpack aliases: 

`'vue$': 'vue/dist/vue.common.js'

This will make sure that the standalone build is loaded instead if the default runtime-only build. You need the standalone build if you want to define template code in your index.html as you currently do.
