### ISSUE TITLE
Error on wrap component example about select2

### ISSUE THREAD

**Issue by alextime** [vuejs/vue#4602]
### Vue.js version
2.1.8

### Reproduction Link
http://jsbin.com/xahiwuvozo/edit?html,js,output

and even the default official fiddle used on the official website for the wrapper component example

https://jsfiddle.net/yyx990803/fruqrvdL/

### Steps to reproduce
Using the wrapper component example, a component to wrap a select2 jquery plugin, the values of the options (no matter if passed through an object or through a slot) are evaluated as string I guess and it is impossible to select values greater than 9.

### What is Expected?
If I try to select the value 11, 11 should be selected

### What is actually happening?
always 1 will be selected.

**Comment by defcc** [comment]
Thanks @alextime , it's not a bug of Vue.js. I updated the fiddler here https://jsfiddle.net/fruqrvdL/265/

I updated the watch  function 

```js
value: function (value) {
  // update value
  $(this.$el).val(value)
}
```

**Comment by alextime** [comment]
Glad to see it is not a Vue issue but only a mistake on the Vue example demo. Anyway, even in this scenario, passing a value as a prop updates the value of "value" but this will no be reflected on the ui.
