### ISSUE TITLE
VM._data computed property creates conflict without any (useful) warnings

### ISSUE THREAD

**Issue by truefusion** [vuejs/vue#4603]
Attempting to define computed property '_data' causes, at least observably, internal conflict, but no useful warning is given. Having a warning like, "'_data' is a reserved property and cannot be used as a computed property," would make debugging the issue simpler.

### Vue.js version
2.1.8

### Steps to reproduce
Define computed property '_data'

### What is Expected?
The computed property to work like any other

### What is actually happening?
Not able to access data from computed property '_data'

**Comment by te1** [comment]
https://vuejs.org/v2/api/#data
> Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.

**Comment by yyx990803** [comment]
In 2.1.8 you already have a warning:
<img width="807" alt="screen shot 2016-12-29 at 2 03 49 pm" src="https://cloud.githubusercontent.com/assets/499550/21552457/ae4ca46c-cdcf-11e6-97dd-0e50172dde4f.png">

**Comment by magicdawn** [comment]
Hello @yyx990803 
Vue warns `_data` computed property conflict, but not props
In vue@2.5.3, a prop with key = `_data` has no warnings. but results only

```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "_data"

found in

---> <SubComp> at sub.vue
       <App> at App.vue
         <Root>
```

the `App.vue` renders `SubComp.vue`

```vue
// App.vue
<template lang="html">
  <div>
    <sub-comp :_data='$data' />
  </div>
</template>

<script>
import Sub from './sub.vue'

export default {
  data(){
    return {
      a: 1,
      b: 2,
      c: 3
    }
  },

  components: { SubComp: Sub }
}
</script>

<style lang="css">
</style>
```

```vue
// sub.vue
<template lang="html">
  <div class="sub">
    {{a}}
  </div>
</template>

<script>
export default {
  props: {
    _data: Object
  },

  data(){
    debugger
    return {...this._data}
  }
}
</script>

<style lang="css">
</style>
```

It works after I change `_data` to `__data`, I believe here need a warning.
What do you say ?
