### ISSUE TITLE
关于异步组件的一系列疑问

### ISSUE THREAD

**Issue by Mark24Code** [vuejs/vue#4604]
##PARTI: 关于异步组件
问题 1:Vue 中的组件异步加载，和打包结构有关么？
vue2 的文档，异步组件部分，只提到了，在声明组件时使用 resolve => require(['./components/xxxx.vue'],resolve)语法。是不是不论我如何打包（一个或者多个），只要组件是这样子声明，组件就可以异步加载？

问题 2:组件的异步加载可以观察么？在本地把 一个非常简单的不涉及请求的 demo （ https://github.com/Mark24Code/vue-tutorial ），所有组件变成异步组件写法，似乎无论从“网络 internet ” js 加载，还是“ Sources 资源”里面对 vue 、 js 文件的加载，都是瞬间的，并没有看到随着点击而出现。在这边有疑问，**异步加载是不可观察的么**？

 问题 3 ：想知道如何才能确定且确保做好异步加载（现在是我及时语法写成文档推荐的样子，似乎看不到任何反馈）。组件层面需要做什么，webpack需要做什么？文档是否可以描述详细点。

##PARTII: 关于异步组件==>惰性加载
问题4： 之所以会产生上面三个问题，是我遇到了一个到底是把全站打包成一个index.html文件，还是多个html文件的问题。 就是目前 vue 脚手架，默认是打包成一个文件.html 。当网站变大，变复杂，更倾向于，多页面，每个页面自己成为 SPA ，而不是一个网站都打包成一个 index.html.就是这种多页面打包的情况。暂时我的想法是，依然打包成一个 index.html 然后把组件打包成多个js，异步加载 = 来等价于打包成多个SPA的情况。

但是我觉得更好的方式，应该是懒加载，这样子就能极大地模拟多页面的情况。

Vue里对，惰性加载组件，有相关的描述么？

看了好多资料，没有得到满意的答案，跑到这儿来问问。

**Comment by Mark24Code** [comment]
我先自己研究下，我发现要做到这点，可能重点在于webpack而不是vue

**Comment by Mark24Code** [comment]
解决方式：https://github.com/vuejs/vue-router/issues/215

**Comment by hx4111** [comment]
你好，关于使用vue-router lazy-load打包的过程，请教一个问题。
问题描述：使用vue-cli webpack构建项目，使用vue-router 并结合webpack实现lazy-load。开发环境使用npm run dev可以正常运行项目，但是生产环境通过npm run build生成dist文件夹并同步部署到服务器上无法正常运行。部署到服务器因为是子项目，不在根目录。想问一下有没有解决方法？

**Comment by Mark24Code** [comment]
@hx4111 部署这方面暂时没有经验。我对webpack也不太熟，但是这个问题直觉上，解决方法应该在webpack的打包设置里。

**Comment by hx4111** [comment]
谢谢。我再查查看。

**Comment by hx4111** [comment]
>你好，关于使用vue-router lazy-load打包的过程，请教一个问题。
问题描述：使用vue-cli webpack构建项目，使用vue-router 并结合webpack实现lazy-load。开发环境使用npm run dev可以正常运行项目，但是生产环境通过npm run build生成dist文件夹并同步部署到服务器上无法正常运行。部署到服务器因为是子项目，不在根目录。想问一下有没有解决方法？

关于上述问题的解决：
在部署到服务器非根目录时，页面无法渲染的原因，是由于vue-router 没有设置非根目录路径的重定向，导致无法匹配当前子目录路由。
在 vue-router的配置里增加
    path: '/test', redirect: '/' //test为所放置的文件夹名称，不修改的话可能会无法显示页面
参考自[http://gaojiajun.cn/2016/12/vuecli-production-deploy/](http://gaojiajun.cn/2016/12/vuecli-production-deploy/)

**Comment by thisjs** [comment]
@Mark24Code 如果不用vue-router，在页面滚动的时候加载某个组件，如何把组件挂载到vm里呢

**Comment by Mark24Code** [comment]
@thisjs 这个我没有研究过~

**Comment by huangyanxiong01** [comment]
和楼主同样的问题啊?完全看不出异步加载，异步加载理论上XHR请求，当我这么做的时候，完全看不出来

**Comment by WangHansen** [comment]
在dev环境下，用lazy loader可以看出来效果，chrome Network tab可以看到不同的route加载的数据不一样。但是npm run build之后我又看了一下，好像就没有async加载的效果了，一步就全部加载了。

**Comment by yozosann** [comment]
@bnuephjx 你好 你这个问题解决了吗。。 我这也有同样的问题 dev ok，但是build就有问题了
