### ISSUE TITLE
delete obj[attr] cannot be bound to the view

### ISSUE THREAD

**Issue by fanyer** [vuejs/vue#4609]
for example
```
<template lang="jade">
  .container
    p(@click='del') {{params.a}}
</template>

<script>
export default {
  data () {
    return {
      params: {
        a: 'aaa'
      }
    }
  },
  methods: {
    del (e) {
      delete this.params.a
    }
  },
}
</script>
```
When the event is triggered , not only the view , but also vm.$data showed in the Components part of vue-devtools doesn't update .
is object[key] of vm.$data can be traced and bound with view?

**Comment by fnlctrl** [comment]
Please use Vue.delete/this.$delete to delete
 reactive properties. https://vuejs.org/v2/api/#Vue-delete
