### ISSUE TITLE
weex-compiler编译出来的是React Dom?

### ISSUE THREAD

**Issue by zimengle** [vuejs/vue#4610]
好奇怪，求解答。。。难道是这样就可以直接适配成React-Native了？
![image](https://cloud.githubusercontent.com/assets/5935585/21562518/67f54b96-ceb4-11e6-8228-459abddae01c.png)
![image](https://cloud.githubusercontent.com/assets/5935585/21562519/6bd04f72-ceb4-11e6-93c2-024c02a86c05.png)
![image](https://cloud.githubusercontent.com/assets/5935585/21562524/70a36372-ceb4-11e6-868d-beb580f9b233.png)

**Comment by yyx990803** [comment]
你配置有问题吧... 信息太少了。
