### ISSUE TITLE
Textarea binding, so that the operation will appear all the data show the same

### ISSUE THREAD

**Issue by sunriseshow** [vuejs/vue#4611]
My demand is that, on the H5 page WAP page, upload a picture, the picture is displayed below, with a description of the frame, upload at least three Zhang, ten more. The picture is horizontal scrolling display, with iscroll, select the corresponding picture will be displayed below。
In order to realize the demand, determine the current input and the contents of store and database operations, textarea without V-model, using the <textarea><template v-if= "list.desctipt" >list.desctipt</template></textarea>.

Upload three pictures is fine, with more than three images will appear, strange things, the first one to delete after store data is correct, but the data show the picture description, then describe all of the boxes are the last one to fill the content of information. This is not a bug of Vue

**Comment by LinusBorg** [comment]
> This is not a bug of Vue

Why did you open an issue then? 

I don't understand what you want, at all.

**Comment by yyx990803** [comment]
如果是问题的话请到论坛或者 segmentfault 用中文吧... 这样交流比较困难，issue 也只用于处理 bug。
