### ISSUE TITLE
component template fragment cached when string id, but not node 

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue#4615]
If I specify a string for a component template like `template: '#some-template'`, Vue appears to cache the template's HTML fragment. I'm running into an issue where if my template's HTML changes, Vue always uses the original template fragment.

However, specifying a _node_ for a component template won't cache it: `template: document.querySelector('#some-template')` .

I'm not sure if this is a bug (with behavior inconsistency) or a feature request, but it would be nice if the template caching was optional. Here's a JSFiddle: http://jsfiddle.net/9v8v6zLb/

**Comment by yyx990803** [comment]
What's the use case for this? It sounds like a bad idea to reload your app by mutating template nodes...

**Comment by nerdcave** [comment]
I'm integrating Vue into an app that uses older, ajax-style rendering, so I'm wrapping some server-rendered view code blocks in templates. I'm sure it would be best to just let Vue render all things dynamic, but converting all the server rendering is too complicated for a first round of refactoring.

Feel free to close this out if you feel like it's too edge case or encourages something you shouldn't be doing anyway.

**Comment by yyx990803** [comment]
I personally think this may be too much an edge case to add special treatment for. The current behavior actually gives you the ability to decide whether the content should be cached, so it seems no changes are really necessary.
