### ISSUE TITLE
Order issue when combining v-if and v-for

### ISSUE THREAD

**Issue by nasebee** [vuejs/vue#4616]
### Vue.js version
2.1.8

### Reproduction Link

http://codepen.io/nasebee/pen/OWLyQq

### Steps to reproduce
Apply a v-if directive to an element with a v-for on it; the v-else will never trigger. If you inverse the cases, and apply the !v-if to the previous v-else, and the v-else to the v-for, everything works as expected.

### What is Expected?
The v-else element hanging under a v-for should display if the v-if check fails; in the example, I would expect <div>Nothing here</div><div>Nothing here first</div> to display.

### What is actually happening?
The initial v-else is not displaying after the v-for: <div>Nothing here</div> won't show. The conditional is working as <div>Nothing here first</div> does display.

I think that this is an odd case to render and doesn't need to be rendered, but it should be documented as a special case in the List rendering section of the documentation. The workaround of only applying v-for on the v-else element is not breaking anything, it's just not expected behaviour.

**Comment by defcc** [comment]
Thanks. Already opened a PR https://github.com/vuejs/vuejs.org/pull/669
