### ISSUE TITLE
vue props variable name does not support camelCase, undefined returned 

### ISSUE THREAD

**Issue by johnqiuwan** [vuejs/vue#4617]
### Vue.js version
2.0.1

### What is Expected?
should be return the right value

### What is actually happening?
vue props variable name does not support camelCase, "undefined" returned. 
For example, if I use camelCase as the props variable name, "undefined" returned, however, if I change it to camelcase, everything works as expetected

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by johnqiuwan** [comment]
I was using laravel 5.3 with Vue 2.0.1
However, it looks like the issue will happen only if I use laravel to pass data from laravel controller to blade template to vue components
