### ISSUE TITLE
Vue2.1.0 version of the page is normal, upgrade to 2.1.8 on the wrong, can only load a Vue instance

### ISSUE THREAD

**Issue by GodD6366** [vuejs/vue#4619]
### Vue.js version
2.1.8

### What is actually happening?
Vue2.1.0 version of the page is normal, upgrade to 2.1.8 on the wrong, can only load a Vue instance

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
