### ISSUE TITLE
Nedb 在 Vue 中使用时的存储路径问题

### ISSUE THREAD

**Issue by shookgao** [vuejs/vue#4621]
使用 webpack-simple 创建工程：
```
vue init webpack-simple nedbtest
```
安装 nedb 数据库：
```
npm i nedb -S
```
修改工程文件 App.vue 为：
```
<template>
<div>
  <button @click="insert">插入数据</button>
  <button @click="find">获取数据</button>
</div>
</template>

<script>
var Datastore = require('nedb')
var db = new Datastore({filename:'./test.db', autoload:true})
export default {
  name: 'app',
  methods:{
    insert () {
      db.insert({name:"admin", password:"123"}, function(err, res) {
        console.log(res)
      })
    },
    find () {
      db.find({}, function(err, res) {
        console.log(res)
      })
    },
  }
}
</script>
```
所有命令都能成功执行，但是在工程目录下找不到 `test.db` 数据库文件，使用 Nodejs 可以在目录下找到 `test.db` 文件，请问 Vue 配合 Nedb 使用的时候数据库文件存到哪儿去了呢？

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
