### ISSUE TITLE
Unit test "warn against infinite update loops" leaves a warning

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#4627]
I was doing some changes to scheduler code and I noticed that after the "warn against infinite update loops" test succeeds, the following tests, if they fail, contain the following:

```
	Failed: Unexpected console.error message: [Vue warn]: You may have an infinite update loop in a component render function. 
	(found in anonymous component - use the "name" option for better debugging messages.)
	    at Object.<anonymous> (webpack:///test/helpers/to-have-been-warned.js:61:11 <- .../vue/test/unit/index.js:18678:13)
```

I think this can be leading to false understanding what is happening and probably the "warn against infinite update loops" should clear debugging messages so that this is not shown later on.

**Comment by mitar** [comment]
Oops. I think this is connected with my changes. Closing.

**Comment by yanlee26** [comment]
[Vue warn]: You may have an infinite update loop in a component render function. 
(found in component <project> at D:\me\vue\oa\src\components\common\list.vue)
warn @ vue.common.js?e881:521
flushSchedulerQueue @ vue.common.js?e881:2812
(anonymous) @ vue.common.js?e881:473
nextTickHandler @ vue.common.js?e881:422
