### ISSUE TITLE
Vue filter causes render error: raw is not defined

### ISSUE THREAD

**Issue by zangab** [vuejs/vue#4629]
### Vue.js version
2.1.8

### Reproduction Link
[Fiddle](https://jsfiddle.net/jrebzk3f/22/)

### What is actually happening?
I have a **custom filter** in my app (sample in the fiddle) to calculate the time difference between now and a given date-time string (data comes from an API, thats based on laravel). If that component gets initialized, there will be an error in the console sayin `[Vue warn]: Error when rendering anonymous component` and `vue.js:437 ReferenceError: raw is not defined` - screenshot of the error [here](http://sesos.at/images/vue_error_raw.png). `Note: there is now variable called raw in my app`. If I remove the filter, everything workes fine - but thats not what I want! It could also happen that the first rendering is fine, but if I update the date (dropbox upload -> time update) error is here - app is down!

Thx.

**Comment by crswll** [comment]
`raw` is on line 16.

**Comment by fnlctrl** [comment]
^ What @crswll said.
Line of error:
> if (offset <= MINUTE) span = ['', raw ? 'now' : 'seconds ago'];

**Comment by zangab** [comment]
holy sh** ... sry, didnt see that and it took me almost a whole day to kinda debug this stuff - but thx for the quick response 👍

**Comment by yyx990803** [comment]
FYI if you inspect the stack trace of the thrown Error, it points to exactly where the error occurs in your code.
