### ISSUE TITLE
v-if and css :empty

### ISSUE THREAD

**Issue by Yusoo** [vuejs/vue#4630]
more than one v-if,    :empty not work

### Vue.js version
2.1.8

### Reproduction Link

[https://jsfiddle.net/r2jopp79/](https://jsfiddle.net/r2jopp79/)

**Comment by yyx990803** [comment]
Vue preserves the whitespace between the two `<li>`s. You can put them on the same line without whitespace in between.

If using `vue-loader`, you can use the `preserveWhitespace: false` option: http://vue-loader.vuejs.org/en/options.html#preservewhitespace
