### ISSUE TITLE
父组件异步$set  子组件获取不到 

### ISSUE THREAD

**Issue by zdz1993** [vuejs/vue#4631]
父组件异步$set  子组件获取不到

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
