### ISSUE TITLE
Conditionally keep-alive component cache goes wrong when 'include' prop dynamically changes

### ISSUE THREAD

**Issue by shidianxia** [vuejs/vue#4633]
### Vue.js version
2.1.8 with vue-router 2.1.1

### Reproduction Link
https://jsfiddle.net/shidianxia/ckj7xbqq/

### Steps to reproduce
a -> b -> c -> Back (b) -> Back(a) -> b -> c -> Back(b)

### What is Expected?
b is cached and enter into activated lifecycle
Component "a,b" Cached

### What is actually happening?
b is cached but mounted a new one
Component "a,b,b" Cached

**Comment by LinusBorg** [comment]
You might have wanted to mention that you change `include`all the time. that looks complicated to track :D

**Comment by shidianxia** [comment]
@LinusBorg Yes,I'd like to cache the components so I can see the cached content when I hit the back button. But I want to destroy the last component in order to re-render it when I enter again.
I'm not sure if I had describe my situation clearly 😂

**Comment by shidianxia** [comment]
Thanks for the update!
