### ISSUE TITLE
Missing data, when requested, is not gracefully handled

### ISSUE THREAD

**Issue by wsw70** [vuejs/vue#4634]
_Note: this is a bug report but I believe that the behaviour may be expected, by design, and probably follows some best practices in JS. If such is the case please close the issue, or maybe treat it as a feature idea_

### Vue.js version
2.0.2

### Reproduction Link
https://jsfiddle.net/gkfpqLab/

### Steps to reproduce
Call in the HTML code a `data` element (`{{something.like.this}}`) when it has not been defined (yet) crashes the script. In the JSFiddle example above the console information is

```
Uncaught TypeError: Cannot read property 'text' of undefined
    at Proxy.eval (eval at makeFunction (vue.js:7434), <anonymous>:2:72)
    at Vue$3.Vue._render (vue.js:2240)
    at Vue$3.<anonymous> (vue.js:1695)
    at Watcher.get (vue.js:740)
    at new Watcher (vue.js:732)
    at Vue$3.Vue._mount (vue.js:1694)
    at Vue$3.$mount (vue.js:5592)
    at Vue$3.$mount (vue.js:7494)
    at initRender (vue.js:2208)
    at Vue$3.Vue._init (vue.js:2552)
```

### What is Expected?
That the exception would be caught and gracefully ignored

### What is actually happening?
An Untaught TypeError which stops the execution of the script

### Why should it be different?
To account for the cases where the data is provided asynchronously (though an API call for instance) and is not available yet when the JS script starts

### Are there workarounds?
Yes, define some defaults in `data` which are consumed by the calls before actual data is available. This leads to a lot of code, potentially, if the amount of data is large/complicated.

**Comment by smolinari** [comment]
You are right. That is how Vue is designed. 

If you haven't already, read through this doc. https://vuejs.org/v2/guide/reactivity.html

It talks about your concern in the "Change Detection Caveat" and "Declaring Reactive Properties" sections and explains why Vue requires the data for the root-level properties upfront as it does. 

Scott

**Comment by fnlctrl** [comment]
^ What @smolinari said.

**Comment by 1beb** [comment]
Is there a recommend approach / design pattern to accomodate for this? Right now, I'm using `v-if` at the head of every component as a guardrail so that the component doesn't attempt to render unless the data it needs is available but it feels kind of ugly.

**Comment by smolinari** [comment]
Yeah, you usually have a loading spinner or a skeleton showing until the data is available.  Here some examples from Quasar.

https://quasar.dev/quasar-plugins/loading
https://quasar.dev/vue-components/skeleton#introduction

Scott
