### ISSUE TITLE
property doesn't work when using camelcase name for custom template -- see example code

### ISSUE THREAD

**Issue by kiwikefei** [vuejs/vue#4635]
Property "testData" won't work unless changed to "testdata", is there anything wrong with the camelcase or I miss something?
thanks a lot.
-------------
```
<div id="root">
<test testData="hello"></test>
</div>
<script src="https://unpkg.com/vue@2.1.6/dist/vue.js"></script>
<script>
Vue.component('test',{
	template: "<h1>Hello {{ testData}}</h1>",
	props: ['testData']
});
var app = new Vue({
	el: '#root',
});
</script>
```

**Comment by zhangyufen** [comment]
you should use  <test test-data="hello"></test>

**Comment by zhangyufen** [comment]
you should use <test test-data="hello"></test>

**Comment by zhangyufen** [comment]
you should use test-data

**Comment by zhangyufen** [comment]
HTML attributes are case-insensitive, so when using non-string templates, camelCased prop names need to use their kebab-case (hyphen-delimited) equivalents

**Comment by fnlctrl** [comment]
You're using in-dom template which doesn't support cased prop names, so please use `test-data` instead as @zhangyufen suggested.
If you're using vue-loader/vueify, it's OK to use cased prop names.
