### ISSUE TITLE
no warning for duplicated options

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vue#4636]
![image](https://cloud.githubusercontent.com/assets/1060733/21605109/e54b2e3c-d1e1-11e6-8991-6cc7cca1a6bd.png)

as you can see,i repeatly defined the `methods` option twice
so the last one will overwrite the first one
but,there will be no warning for that
i didn't know what is the matter when there was an error said that ` handleFoo` is not defined
cause of actually i did have defined it

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Vue doesn't get to detect a duplicate property inside an object literal -  It's automatically removed by javascript engines. e.g.

![image](https://cloud.githubusercontent.com/assets/5557143/21607356/8594408c-d1f0-11e6-8e7e-c503343a4b48.png)
