### ISSUE TITLE
when use a no import components，not throw any error

### ISSUE THREAD

**Issue by itbeihe** [vuejs/vue#4637]
### Vue.js version
2.1.8

### Steps to reproduce
1.use the newest vue-cli init a webpack project
2.use a  no import components
![image](https://cloud.githubusercontent.com/assets/703427/21605575/0982f278-d1e5-11e6-9407-27dd4002bcb4.png)
3. npm run dev
4. look at http://localhost:8080/
### What is Expected?
console panel can report prompt error message
### What is actually happening?
The browser display blank and not throw any error

**Comment by yyx990803** [comment]
It does throw an error for me.

<img width="704" alt="screen shot 2017-01-03 at 9 23 29 am" src="https://cloud.githubusercontent.com/assets/499550/21610490/52013022-d196-11e6-9d32-a1209c191ba7.png">

**Comment by itbeihe** [comment]
thank you, I found the reason,because a chrome plugin (https://github.com/Selection-Translator/crx-selection-translate)  block this error tip.
