### ISSUE TITLE
v-for="(data) in datas"    error

### ISSUE THREAD

**Issue by sqchenxiyuan** [vuejs/vue#4643]
### Vue.js version

vue.js 2.1.8  and old version also have this problem

### Reproduction Link

[jsfiddle](https://jsfiddle.net/sqchenxiyuan/Lxgm07Lm/)

### Steps to reproduce

``` html
 <div id="app">
   <div v-for="(data) in datas">
     {{data}}
   </div>
</div>
``` 

``` javascript
new Vue({
  el: '#app',
  data: {
    datas:[1,2,3]
  }
});
```

error

[Vue warn]: failed to compile template:

### What is Expected?

success compile template

>Because I think the variables in parentheses are like parameters, V-for just attach data to them and should not be wrong when there is only one parameter

>因为我认为括号内的变量就像是参数一样，v-for 只是给它们附上数据，不应该当只有一个参数的时候就报错

### What is actually happening?

[Vue warn]: failed to compile template:

**Comment by defcc** [comment]
The v-for usage is documented already, however maybe there could be an improvement for this case.

**Comment by voquanghoa** [comment]
Why didn't you make it simpler?
```html
<div id="app">
   <div v-for="data in datas">
     {{data}}
   </div>
</div>
```

**Comment by gurkancakir** [comment]
`<div v-for="data in datas">` this is true.

[jsfiddle](https://jsfiddle.net/Lxgm07Lm/1/)

**Comment by sejr** [comment]
[Relevant documentation.](https://vuejs.org/v2/guide/list.html#Basic-Usage)

Variables in parentheses are interpreted as properties of single JavaScript objects.

**Comment by yyx990803** [comment]
The syntax is by design. The braces are there to indicate the presence of an index or key.
