### ISSUE TITLE
Checkbox is not unchecking programmatically

### ISSUE THREAD

**Issue by rorc** [vuejs/vue#4645]
https://jsfiddle.net/rorc/pwbfc990/

**Expected behaviour:**
When `counter == 3`, after one second counter will equal 0 and checkbox must be unchecked.

**Comment by posva** [comment]
This is a limitation of inputs while focused: they cannot update. You can however get around it by running the `blur()` method: https://jsfiddle.net/posva/ka9rLjwu/

**Comment by rorc** [comment]
@posva Ok, thanks.

**Comment by rorc** [comment]
@posva And this way is right?
https://jsfiddle.net/rorc/pwbfc990/2/

**Comment by posva** [comment]
Yes, it also works. In v-model we don't change an input if it's focused because it may end up in weird ux
