### ISSUE TITLE
Events listeners are not unbound when reusing nodes

### ISSUE THREAD

**Issue by posva** [vuejs/vue#4650]
### Vue.js version
2

### Reproduction Link
http://jsfiddle.net/posva/hdqz1bc3/

### Steps to reproduce

1. Click the toggle
2. select a value in the select

### What is Expected?
No error in console

### What is actually happening?
The select is trying to fire the change from the previous `select`. Adding a `key` attribute to one of the selects is a workaround @rorc

**Comment by defcc** [comment]
Seems an edge case for update-listener
```js
old.length = cur.length
for (let i = 0; i < old.length; i++) old[i] = cur[i]
```

cur is a function type here, so it breaks. I'll fix it.

**Comment by jimczj** [comment]
@posva I have forked your JSFiddle example ,and I found that if your added` @change="foo"` to the select2,it can run normally. [http://jsfiddle.net/jimczj/hm0onwy9/1/](url)

**Comment by posva** [comment]
@jimczj Yes, that makes the function defined when trying to invoke it
