### ISSUE TITLE
Feature request: dynamic subcomponents

### ISSUE THREAD

**Issue by unirgy** [vuejs/vue#4651]
Hello, I have a situation when I'd like to have a computed local subcomponents. Something like this:

```
var DataGridRow = {
    props: ['columns'],
    template: '<tr><component v-for="col in columns" :is="col.component"></component></tr>',
    components: function () {
        var comps = {};
        // Logic here to build subcomponents dynamically
        return comps;
    }
}
```

In my tests that didn't work. 
Does this exist and I'm using it wrong?
If not, is it feasible to implement? 
My specific case is custom data grid row cell components.

Thank you.

**Comment by Mat-Moo** [comment]
https://vuejs.org/v2/api/#component

Can't use use <component :is="componentId"></component>

**Comment by unirgy** [comment]
@Mat-Moo thank you, i was hoping it's just not documented, like `computed` properties that can accept arguments:

```
computed: {
    prop: function () {
        return function (arg1, arg2) {
            return arg1 + arg2;
        }
    }
}
```

**Comment by fnlctrl** [comment]
Hi, you can simply use a computed property for a component:
```js
{
  components: {foo, bar, baz}
  computed: {
    myDynamicComponent() {
       let {foo, bar, baz} = this.$options.components
       // decide whether to return foo or bar or baz
       return foo;
    }
  }
}
```
```html
<component :is="myDynamicComponent"></component>
```

**Comment by unirgy** [comment]
Is it necessary at all to declare subcomponents, if the `:is` property is actual component declaration?

**Comment by fnlctrl** [comment]
>Is it necessary at all to declare subcomponents, if the :is property is actual component declaration?

No, it's not necessary to delcar all components inside the `components` option, since you can directly use a component declaration, e.g.
```js
data: {
    myDynamicComponent: {
          name: 'foo',
          template: '<div><div/>'
   }
}
```

Please refer to the [docs](https://vuejs.org/v2/api/#component), thanks.

**Comment by unirgy** [comment]
Thank you!
