### ISSUE TITLE
textarea element default value bug when v-model  bound  to the same Array

### ISSUE THREAD

**Issue by Jungley8** [vuejs/vue#4654]
v2.1.3
[https://jsfiddle.net/Jungley/7pejtaq0/](url)

I hope the 'textarea' element default value is blank
But Now the 'textarea' default value is '[]'

How can I set the textarea default value

**Comment by dotneet** [comment]
Use blank string literal instead of empty array.

```
new Vue({
  el: '#app',
  data() {
    return {
      content: ''
    }
  }
})
```

**Comment by Jungley8** [comment]
英语不好，还是用中文吧。 

我用 textarea 模仿 [`Multiple checkboxes, bound to the same Array`](https://vuejs.org/v2/guide/forms.html#Checkbox) 的写法，发现行不通。估计 input[type=text] 也行不通。

是不是暂时 不支持 将 input、teatarea 绑定到 数组呢？

@yyx990803

**Comment by defcc** [comment]
是的，暂时不支持。对于复选框来说这种场景很常见，因为他有一致的业务逻辑。你将 model 绑定到多个 textarea 是基于什么场景来考虑的呢？

**Comment by Jungley8** [comment]
目前想到的解决办法是 将 v-model 设置成 {} ，就可以了
