### ISSUE TITLE
Strange binding behaviour

### ISSUE THREAD

**Issue by Rhincodon** [vuejs/vue#4658]
### Vue.js version
2.1.7+

### Reproduction Link
[https://jsfiddle.net/rhinodontypicus/tvcz49bd/](https://jsfiddle.net/rhinodontypicus/tvcz49bd/)

### Steps to reproduce
Change input value, click Button -> value rolls back.

### What is Expected?
Input value must not be touched at all.

### What is actually happening?
Input value rolls back to origin value.

If we remove v-bind:disabled from button, it works as needed — nothing happened.

**Comment by defcc** [comment]
This is an expected behavior in Vue.js 2. When `doing` value changes, your app gets re-rendered, so the input value is reseted to 1. You could use v-model. I updated the fiddler here https://jsfiddle.net/tvcz49bd/1/

**Comment by Rhincodon** [comment]
@defcc Why this behavior appeared only in Vue 2.1.7+ , not in prev releases. Is this not breaking change?

**Comment by Rhincodon** [comment]
@defcc And if you say, that whole template is re-render, why if we change input to textarea, its value not rolled back like input value?

**Comment by defcc** [comment]
@Rhincodon , I'll have a check on it.

**Comment by posva** [comment]
@Rhincodon This is a very good usecase for `v-once` actually 🙂  (as @defcc pointed out). It's a coincidence it worked with vue.
If you need to send data with ajax, just put `v-once` on the container element if every child (+ parent) doesn't need vue. Otherwise put it for every child. So, no, it's not correct, you can absolutely use Vue for that 😄

**Comment by defcc** [comment]
Thanks @Rhincodon , I'll open this issue.

**Comment by defcc** [comment]
In 2.1.7 static value attribute was added to dom property, which introduced the different behavior between the previous version. Related issue: https://github.com/vuejs/vue/issues/4530.

**Comment by Rhincodon** [comment]
@defcc @posva Thanks, I partially understand now. All parts of my html with not binded inputs that inside app template need to be wrapped in `v-once`?

**Comment by defcc** [comment]
In fact, Vue will do this automaticly, you don't need to keep it in mind. You could check this doc  for more details: https://vuejs.org/v2/api/#v-once.

As for this issue, we might need to fix this case.
