### ISSUE TITLE
Finding v-model's from an array only works when inlined

### ISSUE THREAD

**Issue by scottbedard** [vuejs/vue#4659]
### Vue.js version
2.1.8

### Reproduction Link
http://jsfiddle.net/uxjdfh0r/

### Steps to reproduce
Create a list of form inputs, where the `v-model` value needs to be found from an array.

### What is Expected?
I'm able to extract the logic finding my `v-model` to a function.

### What is actually happening?
It only works if the logic is inline. I'm not sure if this is a bug, or if it is intended behavior.

**Comment by defcc** [comment]
Thanks @scottbedard , it's an expected behavior. 

For  `v-model="a.value"`, Vue.js will generate code like this under the hood

```js
on: {
  change: function() {
      a.value = select.value
  }
}
```
