### ISSUE TITLE
Delimiters in single file components

### ISSUE THREAD

**Issue by marcelombc** [vuejs/vue#4661]
Delimiters in single file components is not working.
Here is my component:
```vue
<template>
<div>
    <div>A custom [[message]]!</div>
</div>
</template>

<script>
export default {
    name: 'my-component',
    delimiters: ['[[', ']]'],
    data() {
        return {
            message: 'component'
        };
    }
};
</script>
```

**Comment by yyx990803** [comment]
The delimiters option is only available for the standalone build: https://vuejs.org/v2/api/#delimiters

Single file components are compiled statically, no changing delimiters via a runtime option is not possible. AFAIK there's no practical reason to change delimiters in single-file components except for stylistic preferences.

**Comment by marcelombc** [comment]
Thanks for the explanation Evan.
You're right, there's no practical reason to change delimiters. It was just to maintain coherence in my code 😄 .
