### ISSUE TITLE
Vue not changing typed arrays

### ISSUE THREAD

**Issue by daveroberts** [vuejs/vue#4664]
### Vue.js version
v2.1.8 (Fiddle links to https://unpkg.com/vue/dist/vue.js)

### Reproduction Link
https://jsfiddle.net/5phxc71r/

### Steps to reproduce
* Enter value into first input box
* Array value changes
* Enter value into second input box
* Array value does not change

### What is Expected?

The value should be changed within the typed array by Vue

### What is actually happening?

The value in the typed array is not changing.

**Comment by yyx990803** [comment]
Vue's reactivity system currently does not support typed arrays.

**Comment by daveroberts** [comment]
Vue is awesome

**Comment by hajnalben** [comment]
Is it the same with ES6 Maps too?

**Comment by yyx990803** [comment]
Closing to track along in #2410 - we will likely only implement this when these new data types reach a significant support rate. Alternatively, we may ship a "mordern browser only" build that leverages ES2015 Proxy which makes supporting all these new data structures (including `Map` and `Set`) less hacky.
