### ISSUE TITLE
Class instance not working in computed definition.

### ISSUE THREAD

**Issue by sant123** [vuejs/vue#4666]
Hi, I have this code:

``` javascript
class People {
    constructor(name, lastName, age) {
        this.name = name;
        this.lastName = lastName;
        this.age = age;

        this.fullName = this.name + " " + this.lastName;
    }
}

class Computed {
    filteredPeople() {
        return this.people.filter(person => {

            var searchThis = person.fullName.toLowerCase();
            var searchIn = this.search.toLowerCase();

            return searchThis.includes(searchIn) || person.age.toString().includes(searchIn);
        });
    }
}

class Data {
    constructor() {
        this.search = "";
        this.people = [
            new People("Santi", "Aguilar", 21),
            new People("Paito", "Moreno", 21),
            new People("Javier", "Florian", 21),
            new People("Luisa", "Cordoba", 23)
        ]
    }
}

class App {
    constructor() {
        this.el = "#app";
        this.data = new Data();
        this.computed = new Computed();
    }
}

var app = new Vue(new App());
```

But I get the following error:

`[Vue warn]: Property or method "filteredPeople" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in root instance)`

This happens because methods in a class are always defined as non-enumerable. That's why I implemented this code to solve it:

``` javascript
function getObjectKeys(obj) {
    var keys = Object.keys(obj);

    if (keys.length === 0) {
      keys = Object.getOwnPropertyNames(Object.getPrototypeOf(obj)).filter(function(item) { return item !== "constructor" });
    }

    return keys;
}

function initComputed (vm, computed) {
  var keys = getObjectKeys(computed);

  for (var index in keys) {
    var key = keys[index];
    /* istanbul ignore if */
    // and so on.....
```

What would you think about it? I haven't tested if only computed definitions have this problem. Also I had to make a filter in the keys because it always returns the constructor in the object.

PD: I know I can use a plain object, but in other to use classes in Vue.js this would be the way.

Thanks.

**Comment by yyx990803** [comment]
Please don't do this. Component options are expected to be plain objects and I don't really see the point of using class for class' sake. The proper way to use classes is with vue-class-component.

**Comment by sant123** [comment]
Got it! ☺
