### ISSUE TITLE
the Array.prototype.splice would not trigger view update

### ISSUE THREAD

**Issue by SKing7** [vuejs/vue#4668]
error please see:[http://stackoverflow.com/questions/41500958/what-is-the-difference-with-array-prototype-splice-and-arr-splice-in-vuejs]( http://stackoverflow.com/questions/41500958/what-is-the-difference-with-array-prototype-splice-and-arr-splice-in-vuejs)

**Comment by fnlctrl** [comment]
If you think it's a bug, please provide a repro, instead of a stackoverflow question.
