### ISSUE TITLE
You will get a 'infinite update loop...' warning when data for watching is NaN 

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#4669]
I think it caused by:
`NaN !== NaN`
[see here](https://jsfiddle.net/0bvy4qrr/1/)

**Comment by fnlctrl** [comment]
You're using jsfiddle's vue on the global scope which is 1.0.12.
This has been fixed in 2.0.8: https://github.com/vuejs/vue/releases/tag/v2.0.8
