### ISSUE TITLE
Textarea Bind a bug

### ISSUE THREAD

**Issue by sunriseshow** [vuejs/vue#4671]
### Vue.js version
Vue.js v2.1.0

### Reproduction Link
My English is not very good, before the issue has also been issued, perhaps I did not express clearly, then I all the questions in the forum, the website has issued a problem. Almost a week has passed, have not been answered, I am very anxious, waiting for the project on-line yet. Although it is a small problem, just an optimization point.
But for a page performance, I think it is very important.
As the business code is more complex, I first made on the gif link.
[Demo connection](https://pan.baidu.com/s/1dFGDwvZ)
Here is the code
`<template>
  
  <div class="editTryPresent clearfix" id="report-step2">
    
    <div class="uploadPic clearfix">
      
      <div class="uploadPic-btn">
        <input type="file" id="picFileId" v-if="noApp" accept="image/png,image/gif,image/jpeg" />
      </div>
      <div class="uploadPic-listCon">
        <ul class="uploadPic-list" data-listidx="0">

          
          <li :class="{current:item.isActive}" :data-index="index+1" v-for="(item,index) in picList">
            <div class=uploadBg :style="{backgroundImage: 'url(' + item.base64 + ')'}" @tap="change(index)"></div>
            <em class="close" @click="remove(index,item.isActive)"></em></li>
            <my-progress></my-progress>
        </ul>
      </div>
    </div>
    
    <div class="uploadPic-content clearfix">
      <div class="uploadPic-explain clearfix" :class="{uploadPicShow:item.isActive}" contenteditable="true"
           :data-index="index+1" v-for="(item,index) in picList">
        <textarea placeholder="描述下您的试用背景情况，比如申请该款产品的目的， 试用的理由等" @input="judgeContent(index)" contenteditable="true" >{{item.descript}}</textarea>
        <div class="describ-tips">至少输入<i class="word numDes" :class="{textWarn:isNum}">10</i>个字</div>

      </div>

    </div>
    
    <div class="editTryPresent-Btn clearfix">

      <a v-show="showPre" href="javascript:void(0)" :class="{disabledActive:disabledpreActive}" @click="prev">上一步</a>
      <a href="javascript:void(0)" :class="{disabledActive:disabledActive}" id="nextStep" @click="next">下一步</a>
      
    </div>
    
    <p class="loginTry" style="display: none">如您已添加过商品到购物车，<a id="cartBtnNew" name="wapgwcy_none_main_dl">登录</a>&nbsp;后查看
    </p>
  </div>
</template>`

I do not know if I use the page or the problem of the bug, we can not understand the gif animation.
The problem is this, I put an array json object, which can package a number of pictures address and description information, saved to the vuex inside the page variable data picList and vuex is the corresponding.
I do not know if I use the page or the problem of the bug, we can not understand the gif animation.
The problem is this, I put an array json object, which can package a number of pictures address and description information, saved to the vuex inside the page variable data picList and vuex is the corresponding. So I uploaded a picture, the picture address and a description of the information described in the push into picLIst, the page will change. Will be inserted in the dom picture information and textarea, the picture is horizontal scrolling, the current selected picture is not used v-model = "item.descript", to bind textarea, because the data changes, vuex storage Of the content and textarea value value has been the same.I would like to have a database of data storage time...
`data() {
      return {
      picList: this.$store.state.picInforList
      }
 }`

### Steps to reproduce
After my test, I uploaded less than equal to three pictures, there is no problem, (the picture iscroll rolling, when more than three pictures will be bound when the iscroll plug-in), when more than three pictures, strange (The fourth picture on the outside of the screen, the mobile end of the page does not fit). If I upload a total of five pictures, the first three pictures I have described to fill in, the fourth also wrote, the fifth did not write. At this time I went back to the first one, the picture deleted, and I set up, if you delete a picture, will automatically move the selected picture to describe all the pictures did not write the picture, and display textarea content , This time found that the description of the fifth picture, although not written, but the fourth and the information displayed is very strange.At this time, I have all the textarea are set to display, found that all the textarea, show exactly the same, I console the picList, and vuex in the corresponding data, the display is correct, only the page display is not normal.
### What is Expected?
I actually want to get the result is to upload a picture, will be inserted into the page, and will insert a corresponding textarea in the dom editor, the user operation, the step-by-step must be filled before the textarea more than ten The contents of the word. Select the same operation is the same as the next step, only to meet the requirements described in order to select the next map, when the delete operation,
The selected position of the current image will target the first image that does not meet the requirements for all images. After uploading pictures, delete pictures, the user to edit textarea in the content, will save the database, but I want to textarea content in the picture switch, the previous step, the next step to switch, if the content does not change, Do not save the database.
### What is actually happening?
I described the above problems do not know clearly described No, I do not know if I used the wrong, or where there is a problem.
Such a strange thing happened, I really hope someone can answer my question. Because I really can not, and other places are not the answer.
I do not know how to write a demo with a vue extension on other sites.
I am a vue beginner
If no one can answer my question, tell me how to write online vue example code is also OK. There is no way.

**Comment by posva** [comment]
> then I all the questions in the forum, the website has issued a problem. Almost a week has passed, have not been answered, I am very anxious, waiting for the project on-line yet.

It's not because the question has not been answered that you can skip the issue reporting guidelines.

If you really find a bug within Vue, make sure to create a repro on a fiddle (please, keep the code as short as possible) and open a new issue. There's no need to add such long explanation, shorter makes them clearer too  🙂

**Comment by defcc** [comment]
@sunriseshow 你可以用一个最小化的 demo 来复现你遇到的 bug，然后把这个 demo 放到 jsfiddler 上去，这样方便对问题的跟进。等你准备好了 demo 重现了这个问题，你可以再新提交一个 issue。
