### ISSUE TITLE
Can you post about product created with Vue.js?

### ISSUE THREAD

**Issue by happierall** [vuejs/vue#4673]
Hello,
Vue.js, Vue-Router, Vuex and other helpers things is super helpful and awesome.
I've create online javascript editor with Vue, can you post about this tool?

It post can explain people how fast can be web apps with Vue, http2 and golang.
link: [playcode.io](https://playcode.io)

**Comment by happierall** [comment]
I don't know where write about this request...

**Comment by CodinCat** [comment]
A more proper place: https://github.com/vuejs/awesome-vue

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Thanks.

**Comment by smolinari** [comment]
@happierall - nice work. Is the editor open source?

**Comment by happierall** [comment]
@smolinari Thank you! I'm not sure, that this editor must be open source, it's based on ace editor, that is open source.

**Comment by smolinari** [comment]
Ah, ok. Understand. Still, good work! 👍 

Scott

**Comment by dotshift** [comment]
I'm confuse, why do I get an old issue bug appear in my notification?
