### ISSUE TITLE
Prop validation does not work correctly with native constructors

### ISSUE THREAD

**Issue by rmp135** [vuejs/vue#4676]
When binding a value to a child, if the value was created with a native constructor it does not validate correctly, printing the following to the console.

```
"[Vue warn]: Invalid prop: type check failed for prop \"num\". Expected Number, got Number. 
(found in component <child>)"
```

I've created a [jsbin](https://jsbin.com/goqapupagu/edit?html,js,console) to demonstrate this behaviour.

**Comment by posva** [comment]
I'd say this is expected because an instance of `Number` is actually not of type `number` but rather an `object`, which is what is tested (the same happens with Boolean). `Number` and `Boolean` are usually used without the `new` operator so they return proper types: `a = Number('35')`.
