### ISSUE TITLE
devtools development is not defined

### ISSUE THREAD

**Issue by xyang0917** [vuejs/vue#4678]
vue-cli命令行工具生成的脚手架项目，将config目录中configdev.env.js、prod.env.js和test.env.js的NODE_ENV配置，从双NODE_ENV: '"development"'改成NODE_ENV: 'development'后，运行时报“development is not defined”错误,因为我想加入一些项目的配置到相应环境的配置文件中，这样得到的值会是带双引号的值，不是我需要的

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by defcc** [comment]
@xyang0917 `NODE_ENV` is only used to build production mode. Refer: https://vuejs.org/v2/guide/deployment.html#With-Build-Tools
