### ISSUE TITLE
[SSR ]update warning message about runtime/standalone builds

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vue#4680]
Currently, SSR will warn like this when a standalone build is used in the SSR bundle:

> [vue-server-renderer] You are using the standalone build (vue/dist/vue.js) for server-side rendering. It is recommended to use the CommonJS build (vue/dist/vue.common.js) instead so that the code can run in production mode by setting NODE_ENV=production. The server renderer supports the template option regardless of what build you are using.

After the new build introduced with Vue 2.1, this should probably read:

> [vue-server-renderer] You are using the standalone build (vue/dist/vue.**common**,js) for server-side rendering. It is recommended to use the **runtime-only CommonJS** build (vue/dist/vue.**runtime**.common.js) instead so that the code can run in production mode by setting NODE_ENV=production. The server renderer supports the template option regardless of what build you are using.

**Comment by yyx990803** [comment]
Actually with the new dist file setup, users will most likely be using CommonJS builds by default, so this check is no longer necessary.
