### ISSUE TITLE
v-model on every html tags

### ISSUE THREAD

**Issue by dawadam** [vuejs/vue#4681]
Hello,
Why is it not possible to add v-model on each tag?
For example to add it on a h1 tag and use the contenteditable attribute.
It's too bad
Thanks

**Comment by yyx990803** [comment]
`contenteditable` has many edge cases that need to be handled differently from form elements, and it's best to use a dedicated library for that purpose. Otherwise Vue core would be bloated with a relatively low-usage use case.

And no, it's not that bad ;)

**Comment by dinadoghmosh** [comment]
ppppppppppppppppppppp
