### ISSUE TITLE
item index inside v-for/v-if loop

### ISSUE THREAD

**Issue by andrisi** [vuejs/vue#4685]
I have an interface item, a list, that is based in an array, but not all items are displayed. It's a v-for/v-if loop. I'd like to put an index number by each visible item. Could Vuejs expose some kind of a counter for visible items? I guess Vuejs has this info internally, so it would be nice to expose it. Thanks, and sorry, if this is something already done.

See: https://forum.vuejs.org/t/v-for-v-if-counter-of-shown-items/4997/3

**Comment by znck** [comment]
Use computed property.

**Comment by fnlctrl** [comment]
^ What @znck said.

> I guess Vuejs has this info internally

No, vue doesn't keep track of that.

**Comment by yyx990803** [comment]
Use a computed property / method to filter the `v-for` array instead of using `v-if` inside `v-for`.

**Comment by andrisi** [comment]
Thanks @znck and @fnlctrl perfect solution as this still has two way sync with the base data.
