### ISSUE TITLE
Class is not applied to component extending abstract component

### ISSUE THREAD

**Issue by mrTimofey** [vuejs/vue#4692]
### Vue.js version
2.1.8

### Reproduction Link
[Codepen](http://codepen.io/mr_t_the_butcher/pen/YNwgwM)

*outer* class is not applied to a component`s *$el* node.
Try to comment *absract: true* line and you will see that class is applying.

### What is Expected?
Outer class must be applied to the root component element.

### What is actually happening?
Outer class is not applied if the component extends a base component with *abstract* flag.

**Comment by znck** [comment]
Extending an abstract component, the component `test` becomes abstract too. **IMO** abstract components can have only bindings defined in props.

**Comment by yyx990803** [comment]
Abstract components are not designed to render templates of their own - they are like "decorators" that simply wrap other components/elements via composition. e.g. `<transition>`:

``` html
<transition>
  <component></component>
</transition>
```

So abstract components **do not have DOM elements of its own** - it simply enhances its slot children. Extending an abstract component and give it some concrete DOM doesn't make sense.

Also, abstract mode is not publicly documented and may change without notice, you should avoid using it unless you are really sure you know what you are doing ;)

**Comment by myst729** [comment]
Any plan to include **abstract components** in the doc?
