### ISSUE TITLE
Defines the name of props

### ISSUE THREAD

**Issue by Alphmega** [vuejs/vue#4695]
Component properties are converted to the same name of the vm member variable, personally think that it should provide the relevant configuration to modify the component's property name.
For example, we can use the following code convert 'name' attribute to 'componentName' member variable
```html:
<template>
    <div :class="componentName"></div>
</template>
<script>
    export default {
        props: {
            componentName: {
                name: 'name',
                type: String
            }
        }
    }
</script>

```

```html:
<my-component name="name">
```

**Comment by yyx990803** [comment]
What's the use case for this? I don't see the point...

**Comment by LinusBorg** [comment]
Closed for inactivity. 

Feel free to open a new issue with an explanation of the use case
