### ISSUE TITLE
`v-on:click.once` not working on Safari

### ISSUE THREAD

**Issue by paulocheque** [vuejs/vue#4696]
# `click.once` issue on Safari

### Vue.js version
2.0.7 (I posted this issue because I did not find anything about this issue in the release notes)

### Comments

This works on Chrome, Firefox and Safari (the `myFunc` has been called):

    <a v-if="loaded" v-on:click="myFunc()"></a>

This works well in Chrome and Firefox, but not in Safari. The function `myFunc` has not been called on Safari.

    <a v-if="loaded" v-on:click.once="myFunc()"></a>

ps: testing in OSX

**Comment by znck** [comment]
It works. [Here](https://jsfiddle.net/znck/sve0p3Lq/1/) is repro.

**Comment by posva** [comment]
@paulocheque Updating to the latest version of Vue seems to fix the issue 🙂
