### ISSUE TITLE
vue-router refresh 404

### ISSUE THREAD

**Issue by qianthinkover** [vuejs/vue#4697]
### Vue.js version
2.0.2

### Reproduction Link

When I deployment my vue app to IIS, refresh page in SPA component, I go 404 error

**Comment by fnlctrl** [comment]
http://router.vuejs.org/en/essentials/history-mode.html

**Comment by qianthinkover** [comment]
My server is IIS , is there a solution?

**Comment by fnlctrl** [comment]
This may help: http://stackoverflow.com/questions/12614072/how-do-i-configure-iis-for-url-rewriting-an-angularjs-application-in-html5-mode
