### ISSUE TITLE
v-model for contentEditable

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#47]

**Comment by CJLees01** [comment]
Does anyone have a working gist of such a custom directive wrapping medium.js please? Spent hours now trying to make it work, but no luck.

**Comment by straps** [comment]
+1 for @CJLees01 request, any news?

**Comment by robertleeplummerjr** [comment]
I have one, let me get source.

**Comment by robertleeplummerjr** [comment]
https://github.com/Enpowi/Enpowi/blob/master/src/client/Enpowi/directives.js#L145

**Comment by robertleeplummerjr** [comment]
I just realized that is the source editor, which uses codemirror.  Let me see if I can put a sample together.

**Comment by robertleeplummerjr** [comment]
Done: http://robertleeplummerjr.github.io/vue-medium.js/

**Comment by straps** [comment]
Great, thanks @robertleeplummerjr

**Comment by FranzSkuffka** [comment]
@robertleeplummerjr I built a more complete version:
https://github.com/FranzSkuffka/innovant/blob/firebase-wip/app/directives/medium.coffee

You need the fixed medium.js version available in the same repository to enable modes other than 'inline'

**Comment by robertleeplummerjr** [comment]
💝

**Comment by robertleeplummerjr** [comment]
@FranzSkuffka mind adding a gh-pages branch for us all to fall in love with?

**Comment by FranzSkuffka** [comment]
Oh I'm too dumb to use gh-pages! I will put some on netlify though.

**Comment by robertleeplummerjr** [comment]
nice

**Comment by FranzSkuffka** [comment]
Done!
https://github.com/FranzSkuffka/vue-medium.js

https://franzskuffka.github.io/vue-medium.js/

**Comment by robertleeplummerjr** [comment]
_tears up from the beauty_

**Comment by Nobi322** [comment]
Hello, I'm still new in vue.js, but this method didn't work in vue 2.0 
![image](https://cloud.githubusercontent.com/assets/6026022/20963365/b9a68dd4-bc75-11e6-980f-324c345aa1d5.png)

**Comment by FranzSkuffka** [comment]
Now available for Medium-Editor:
https://github.com/FranzSkuffka/vue-medium-editor

compatible with vue1 and vue2 :green_apple: 

@Nobi322 you need a plugin
