### ISSUE TITLE
Entering a value in a text input resets an unconnected select box.

### ISSUE THREAD

**Issue by steveholmes** [vuejs/vue#4705]
I have a 'select list' and an 'input'. I select an item and then when I enter a value in the input box, the select value gets reset.

### Vue.js version
2.1.7 & 2.1.8
(works correctly in 2.0.0 to 2.1.6)

### Reproduction Link
https://jsfiddle.net/qz4cu3gc/1/
https://forum.vuejs.org/t/entering-a-value-in-an-input-is-resetting-a-select-value-am-i-missing-something/5126

### Steps to reproduce
1. Select an item from the select list.
2. Enter anything in the text input

### What is Expected?
Chosen item in the select list item stays selected

### What is actually happening?
Select list item is being reset.

**Comment by yyx990803** [comment]
This has been fixed by #4662 and will be released soon.

**Comment by steveholmes** [comment]
Great thx, sorry didn't recognised the same issue.
