### ISSUE TITLE
Image render improperly in List-Rendering

### ISSUE THREAD

**Issue by cecilpeng** [vuejs/vue#4706]
I'm new here. I don't know if vue can support it.

I use v-repeat to render list. When the list shifts a new item, vue reuses dom, and rebind the data. However, image will show the old one until loaded. It is uncomfortable when the network is slow on mobile phone. I struggled to choose which way to resolve it. To develop a directive of togglling visibility around the loaded time of the image. Or vue can work around.

![2674502c-7da3-4d73-82be-f403d1cb9964](https://cloud.githubusercontent.com/assets/3832621/21916591/aa329f04-d97c-11e6-8609-db9704e0b598.png)

After shift a new item, before the new image is loaded.

![image](https://cloud.githubusercontent.com/assets/3832621/21916672/0f8bd2a8-d97d-11e6-8515-0ad27bd63a9e.png)

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen. You could start with [this template](http://jsfiddle.net/df4Lnuw6/) that already includes the latest version of Vue.

**Comment by phanan** [comment]
Please use the [forum](https://forum.vuejs.org) for such questions. IIRC, there was a thread about this exact topic.

**Comment by cecilpeng** [comment]
@znck see http://jsfiddle.net/df4Lnuw6/115/. Thanks.

**Comment by znck** [comment]
@cecilpeng Use `key` with `v-for`. Fixed your fiddle [http://jsfiddle.net/znck/df4Lnuw6/119/](http://jsfiddle.net/znck/df4Lnuw6/119/). 

Use [forum](https://forum.vuejs.org/) for such questions.
