### ISSUE TITLE
用组件做树形结构，怎么做算好的思路

### ISSUE THREAD

**Issue by shangxinbo** [vuejs/vue#4707]
我有一个场景，要做一个类似windows 文件资源管理器似的交互tree，首先根节点散发出不定数量的主干节点，每个主干节点会散发下一级的枝干节点，一直到叶子节点。这里的树深度是根据data来决定，也就是说每个枝干的深度由data决定，每个节点是否是叶子节点也是由data决定。
dom结构很好理解，就是ul>li>ul>li…… 的嵌套结构，如果一开始整棵树都加载下来大概有百万级的节点，考虑页面渲染性能和服务器负载，data需要懒加载，首先会加载树的主干节点，然后点击主干节点再获取枝干节点的data从而渲染枝干节点的dom，直到叶子结点。这个过程想用动态组件实现，但是不知道怎么个实现方法。
![img](http://upload.chinaz.com/upimg/allimg/110128/1032162.jpg)
请教一下，如果要实现我的交互需求，应该怎么做。

**Comment by phanan** [comment]
请使用[论坛](https://forum.vuejs.org)提出这些问题。虽然你的问题看来跟Vue.js没有关系。
