### ISSUE TITLE
Slot emit does not go up to the component

### ISSUE THREAD

**Issue by bodinsamuel** [vuejs/vue#4709]
Hi,

I rencently got into VueJS so if my question is dumb, please excuse me.
But as I follow the doc and the example provided, I stumbled accros something not expected.

I wanted to an overlay, that actually is a component, with a slot to replace main part. 
Mostly like the one provided in the example (https://vuejs.org/v2/examples/modal.html)

My bug is that, in this example there is close button, that $emit('close') on the slot="footer"
It works as intended but when we replace the slot with our footer and put another button that will also trigger $emit('close') the event is not passed back to the component.
Which is not very handy.

I presume it's a bug, otherwise the demo would be very missleading.
I provided you the reproduction link (which is just a copy paste from the example with the overrided button)

Thanks a lot for everything :)

### Vue.js version
2.1.6

### Reproduction Link
https://jsfiddle.net/mwLbw11k/276/

### Steps to reproduce
- Run
- Click on button
- nothing happen

### What is Expected?
- Run 
- Click on button
- Overlay close

### What is actually happening?
- The event is not triggered or not passed to the component.

**Comment by LinusBorg** [comment]
It's not a bug.  You have a misunderstanding about the compilation scope of sclots. Please read this:

https://vuejs.org/v2/guide/components.html#Compilation-Scope

Your corected example:

https://jsfiddle.net/Linusborg/mwLbw11k/277/

Please visit the forum for further support.

**Comment by bodinsamuel** [comment]
Many thanks for quick answer,

I understand your point and how slot are compiled,
however I find this behaviour not predictable, especially the way it's presented in the example.
It let us believe we can override and keep the same behaviour

If I can correct my initial question: 
- Slot with default content will trigger and call the method in the component correctly
- Overrided slot will trigger and call the method in parent of the component 
It's not ideal as it break the context separation
Again, I may be missleading somewhere, I'm not assuming it's a bug.
And I could also use the event bus but again it send an event in the wild with everything else, 
while the component could handle it directly.

```
<script type="text/x-template" id="modal">
  <slot name="footer">
   <button class="modal-default-button" @click="close">
   Override: Default will call App.modal::close();
   </button>
  </slot>
</script>

<modal>
  <div slot="footer">
   <button class="modal-default-button" @click="close">
    Override: Default will call App::close();
    </button>
  </div>
</modal>
```
Direct examples: https://jsfiddle.net/mwLbw11k/279/

There is probably a better solution that I could think of.
Thanks again :)

**Comment by LinusBorg** [comment]
I dont see how it is confusing. 

Slot defaults are defined in the child, so their directives run in the scope of the child. 

Slot content is defined in the parent, so its directives run in the scope of the parent. 

Of you want to pass a template to the child that the child can run in its own scope, look at "scoped slots" in the docs.
