### ISSUE TITLE
Boolean prop parses as true with empty string.

### ISSUE THREAD

**Issue by MKRazz** [vuejs/vue#4710]
I'm having an issue in my project so I created a repo to try to recreate the issue. It appears my exact problem may have been resolved in a later version of Vue than my project is using, but I was still able to reproduce this part in the latest version (2.1.8).

If I create a component with a prop that expects a type of Boolean, passing an empty string will return true when I'd expect it to return false since an empty string is falsey.

https://github.com/MKRazz/vue-boolean-prop-issue

**Comment by yyx990803** [comment]
In HTML, boolean attributes are considered truthy if the value is an empty string. Vue treats Boolean props the same way.

**Comment by ninofiliu** [comment]
Ah! I thought I had found a bug, but now it makes sense that `Parent`

```vue
<!-- Child.vue -->
<template>
  <pre>{{ { foo } }}</pre>
</template>
<script>
export default { props: { foo: { type: Boolean } } }
</script>
```

```vue
<!-- Parent.vue -->
<template>
  <div>
    <pre>{{ { foo } }}</pre>
    <Child :foo="foo"/>
  </div>
</template>
<script>
import Child from './Child.vue'
export default {
  components: { Child },
  data() { return { foo: '' } }
}
</script>
```

doesn't render to

```html
<pre>{ "foo": "" }</pre>
<pre>{ "foo": "" }</pre>
```

but rather

```html
<pre>{ "foo": "" }</pre>
<pre>{ "foo": true }</pre>
```

because `foo` inside `Child` is not passed directly but rather *"html-coerced"* into a boolean

@yyx990803 I didn't find it clear from reading the docs, I expected the info you just gave to be included [here](https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean), do you concur? If yes, I'd be happy to write a PR to the doc repo with this update

**Comment by flipflopsimsommer** [comment]
here is an [example](https://play.vuejs.org/#eNrdVU9vmzAU/yoWl6ZSA4ftxCjSuvWwSNuqNUcuBF6IU2N7tkkTIb77ng0kEJVK67JLueD317/33o9H7X2W0t9V4IVepDNFpSEaTCXjhNNSCmXI98OdEGypyVqJklz5Qa+wYVefzvwW536Lo18UtBdgahQMlJKlBpxESGTSFbMCwScyG0jzTrCiOp6dcSAR8kzN5ius04oZPfAKRm7nQYtHsjxImApAob/S6k9gIrMS+WES2Qmzk8vDfIUtmBtNqJ5LJWSsN9irKDhZhvHBKMFkuu1kuu1kukFFb4B9m3hGVZB4sX1dDP5U2v9Yxjpl2l7o3pcsZCLxpUuJ85bq/wz9TUDxeOQ/nrtPFk/9x+zdeEZngq9p4W+14LhWauuceJkoJWWgfkpDBdeJFxJnsbaUMfG8cDpLhJten20ge3pBv9V7q0u8BwUa1A77frSZVBVgWvP94w/Y4/loLEVeMfR+xfgLtGCVxdi63VU8R9gDP4f2m1t6lBdLfb83wHVflCM0ejbOP/Fw+X15pfQT3A/+RxeX8Aa7OFyyg93MUl7YrwaTtHuaFMBB0QyVS4L1AM81saGQYgE4HByGNsSSVJPb0bKc2euQTpTDgzVHHSiqrRj2WVwdTTy7xoPz6O2OQKhExNfn63284JEsOd2RMGOp1oi0LhQAD1tUfpuvcWgdyaSCONJMmCCua1L39428SdNEgXVsqYjpx0TsQGhzYECQkRIsoX13satilWZPhRI43XkmmFAhcTYsBOvBWmygpfPwL3b+k/zL5g96PRt1smu8wT/SuO1uPnZYp25bpYLfFVWQd9qeNi9M4b3MofkDgpW4rw==)
