### ISSUE TITLE
Maybe we need a better child-template overriding solution than slot?

### ISSUE THREAD

**Issue by ash0080** [vuejs/vue#4712]
```
<div class="container">
    <slot name="a-thumbnail"></slot>
    <slot name="a-button"></slot>
</div>
```

```
<my-componet>
  <img slot="a-thumbnail">a img</h1>
  <button slot="a-button">Here's a button</p>
</my-componet>
```

1. if we change the order in parent, nothing change 

```
<my-componet>
	<button slot="a-button">Here's a button</p>
  	<img slot="a-thumbnail">a img</h1>
</my-componet>
```

2. if we need wrappers like a css framework,

```
<my-componet>
	<div class="a wrapper">
		<button slot="a-button">Here's a button</p>
	  	<img slot="a-thumbnail">a img</h1>
	</div>
</my-componet>
```

of course, we can wrap the componet like this

```
<div class="a wrapper">
	<my-componet>
		<button slot="a-button">Here's a button</p>
	  	<img slot="a-thumbnail">a img</h1>
  	</my-componet>
</div>
```

but in more complex practical works, not working, right?

```
<div class="columns">
	<my-componet>
		<div class="column is-half">
			<button slot="a-button">Here's a button</p>
		</div>
		<div class="column is-half">
		  	<img slot="a-thumbnail">a img</h1>
		</div>
  	</my-componet>
</div>
```
yes, we still can resolve the slot one layer out like this

```
<div class="columns">
	<my-componet>
		<div slot="a-button" class="column is-half">
			<button>Here's a button</p>
		</div>
		<div slot="a-thumbnail" class="column is-half">
		  	<img>a img</h1>
		</div>
  	</my-componet>
</div>
```
but, in more more complex situation, for example, the button and img are not in same level

```
<div class="columns">
	<my-componet>
		<div slot="a-button">
			<div class="column is-half">
				<button>Here's a button</p>
			</div>
			<div slot="a-thumbnail" class="column is-half">
			  	<img>a img</h1>
			</div>
		</div>
  	</my-componet>
</div>
```

in this situation, cuz the slot='xxx' is wrote inside a pair html-tag, not working?
 
in this example, we have to write parts of the wrappers inside componet template, but this will make the component tightly coupled! 

so now, slot has 2 defects
1, can't change the order
2. can't be nested

I'm still newbie in VUE, so maybe my understand has wrongs, please favor me with your instructions

抱歉, 刚不小心还没写完就点到了回车 ;P

**Comment by znck** [comment]
IMO slots are for content distribution that are like holes in UI which can be filled with anything. 

The component decides where should content go as the parent component does not know markup of its children.

If you need to reorder slots then you can use `props` and `v-if / v-else`. 

Take this to Vue forum.

**Comment by ash0080** [comment]
@znck 
I don't agree, 

for reordering,
even though slots can be reorder by passing a prop
A better solution is read the order in parent, but make the slots in component like a mutable array, at least a mutable option,

for nesting,
html wrappers are very common usage, and you haven't reply my inquiry.

or do we have a better solution for child template overriding?  Mixin, maybe?

**Comment by znck** [comment]
Components are self contained entities. 
In theory, a component does not know its surrounding. Only way to interact with them is using `props` and `events`. 

If you have a specific problem, then post it over forum.

**Comment by ash0080** [comment]
plz check the question 2 @znck

**Comment by ash0080** [comment]
for now, if you wrote something like this

```
<my-componet>
something a
<div slot="a"> slot a content</div>
something b
<div slot="a"> slot a content</div>
something c
</my-componet>
```
how can you organize your component to display all content from parent?
```
<slot></slot>
<slot name="a"></slot>
<slot></slot>
<slot name="b"></slot>
<slot></slot>
```

maybe it works, but if the slots are not in same level , how can you deal with that?
as I mentioned before, 

```
<div class="columns">
	<my-componet>
		<div slot="a-button">
			<div class="column is-half">
				<button>Here's a button</p>
			</div>
			<div slot="a-thumbnail" class="column is-half">
			  	<img>a img</h1>
			</div>
		</div>
  	</my-componet>
</div>
```
maybe you would say I can combine this two slots into only one, but if the two slots has different scope props, so how?

**Comment by jingsam** [comment]
For ordered or nested contents, just use the default slot instead of named slots:
```
<div class="container">
    <slot</slot>
</div>
```

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with this [template](http://jsfiddle.net/df4Lnuw6/) that already includes the latest version of Vue.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**Provide a live reproduction using

**Comment by ash0080** [comment]
@jingsam 
default slots could be nested?

**Comment by yyx990803** [comment]
1. Slot is a **composition mechanism**, not for overriding. You seem to misunderstand what it is designed for.

2. Slots cannot be reordered by parent exactly because the position of slots inside the child is controlled by the child. This is the whole point of slots. However, order of the elements distributed into the same slot is controlled by the parent.

3. I don't see the point of nested slots. It makes it a lot more complex for no obvious gain.

4. You can always use render functions if you feel you cannot achieve a specific goal via slots.

5. **Only open an issue if you have a concrete proposal on what you think may be a better solution. As stated several times already, general questions should be posted to the forum. Please respect the rule and time of the maintainers.**
