### ISSUE TITLE
Transition immediately finished when rendering fast.

### ISSUE THREAD

**Issue by YunSun-CN** [vuejs/vue#4717]
### Vue.js version
2.1.8

### Reproduction Link
https://jsfiddle.net/4a0otgab/

### Steps to reproduce
1. Click the button once, you can see the ripple's transition. And after the transition is finished, the ripple will be removed from DOM.
2. Double click the button ( as fast as you can ), then you could see the first ripple is immediately removed without transition and the second ripple remained in the DOM.

### What is Expected?
Act as what transitions should to be.

### What is actually happening?
As mentioned above.

**Comment by yyx990803** [comment]
You should be using `:key` instead of `key` for dynamic key bindings.

**Comment by YunSun-CN** [comment]
@yyx990803 My fault. I made a mistake in writing the demo. But when I fixed the demo using `:key` instead of `key`, the bug remains.
See the updated demo here: https://jsfiddle.net/4a0otgab/1/
Expect rendering two transitions when double click on the button, but transtions finished immediately ( triggering `after-enter` hook ) and left the second rendered element in the DOM.
