### ISSUE TITLE
Perhaps Vue.js has in violation status of MPL.

### ISSUE THREAD

**Issue by sntakahaya** [vuejs/vue#4720]
### What is happening?

Vue included and modified "html-parser.js", Moreover chosen [Mozilla Public License(MPL)](https://www.mozilla.org/en-US/MPL/1.1).
MPL obliges the following provision.
```
3.1. Application of License.
The Modifications which You create or to which You contribute are governed by the terms of this License, including without limitation Section 2.2. 
The Source Code version of Covered Code may be distributed only under the terms of this License or a future version of this License released under Section 6.1, and You must include a copy of this License with every copy of the Source Code You distribute. 
...
```

Since Vue has chosen MIT license,Vue has two licenses and it does not include a copy of the license that MPL obliges, it is considered to be in violation of MPL's terms.

If you modify it to include a copy of the license terms of MPL, you can avoid violating the rules,But

* It may be necessary to be able to distribute modified vue.js.
* License is described as MIT and distributed, there is a possibility that it may differ from intention.

### What is Expected?
If you choose [Apache Software License 2.0](http://www.apache.org/licenses/LICENSE-2.0) instead of MPL, these problems will be solved.
Does Vue use "html-parser.js" by selecting Apache Software License 2.0 license?
In that case, I want you to explicitly select Apache.

**Comment by smolinari** [comment]
I think the fact that the original developers and their licenses being mentioned [at the top of the code in question](https://github.com/vuejs/vue/blob/08bd81f8c0bd39816b5b509c5132a12188b412d7/src/compiler/parser/html-parser.js) satisfies the rules of the MPL. If you read this section, you should also think the same. 

>**3.7. Larger Works.**
>You may create a Larger Work by combining Covered Code with other code not governed by the terms of this License and distribute the Larger Work as a single product. In such a case, You must make sure the requirements of this License are fulfilled for the Covered Code. 

Scott

**Comment by posva** [comment]
After searching about this, there's no problem in **using** a piece of code released under Apache license as long as you leave the notice. We can replace the line at https://github.com/vuejs/vue/blob/dev/src/compiler/parser/html-parser.js#L8 with `Original code by Erik Arvidsson, Apache License, Version 2.0`.
But, as @smolinari said, we should not need this

**Comment by yyx990803** [comment]
As @smolinari pointed out, it seems to be fine to only attribute the specific covered code under MPL - which means you can still use/distribute Vue under MIT, as long as you keep the MPL notice in Vue's source code intact.
