### ISSUE TITLE
Vue not correctly makes hierarchy of components

### ISSUE THREAD

**Issue by faforty** [vuejs/vue#4721]
Vue not correctly makes hierarchy of components. The enclosure of components is necessary. 
Example: 

```
<ui-tabs>
<ui-tab></ui-tab>
<ui-tab></ui-tab>
</ui-tabs>
<!-- or -->
<ui-button><ui-button></ui-button></ui-button>

```

Result:

![2017-01-16 15 19 28](https://cloud.githubusercontent.com/assets/5086285/21982987/f07d8aa2-dbff-11e6-83c3-9afd2b2780fa.png)
![2017-01-16 15 20 06](https://cloud.githubusercontent.com/assets/5086285/21983004/09b399f8-dc00-11e6-888e-a9179e0f963d.png)

Help please. What's the problem?

**Comment by posva** [comment]
This should be opened on https://github.com/vuejs/vue-devtools/ instead.
Please, check for issues similar to this one and if they don't exist, make sure to provide a repro 😉 
I found this one, that may be related: https://github.com/vuejs/vue-devtools/issues/122

**Comment by faforty** [comment]
In the context component don't find $parent and $childrens, also $parent counduct $root element
