### ISSUE TITLE
Mixins: props are not correctly mixed in when registered globally

### ISSUE THREAD

**Issue by CinKon** [vuejs/vue#4722]
Duplicates #3957

### Vue.js version
2.1.8

### Reproduction Link
https://jsfiddle.net/CinKon/qwaacqon/1/

### Steps to reproduce
Open DevTools. Console-Error:
`[Vue warn]: Property or method "myText" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in root instance)`

### What is Expected?
Props that are imported via mixin should render without problems.

### What is actually happening?
Console throws error, prop is not transmitted.

**Comment by posva** [comment]
the template should be outside of the app. Also the prop needs to be lower case due to html limitations: https://jsfiddle.net/posva/p6puekc3/

**Comment by CinKon** [comment]
OK, got it. Problem was that I didn't export the mixin var (`export default buttonMixin`)
