### ISSUE TITLE
Vue.config.errorHandler to handle Vue.nextTick and vm.$nextTick exceptions

### ISSUE THREAD

**Issue by ianhk** [vuejs/vue#4728]
Our app attempts to catch unexpected exceptions so they can be captured and reported back to base. 

I can use Vue.config.errorHandler for Vue render and watch exceptions, but this doesn't catch exceptions within Vue.nextTick or vm.$nextTick closures. 

For now I've interposed the nextTick and prototype.$nextTick functions to catch the errors, but this feels fragile. 

The suggestion is that the existing errorHandler should be used to report Vue.nextTick and vm.$nextTick exceptions.

**Comment by posva** [comment]
Moving the discussion to #4730
