### ISSUE TITLE
using v-if and v-for with string, render result is unexpected

### ISSUE THREAD

**Issue by yreenchan** [vuejs/vue#4729]
### Vue.js version
2.1.7 2.18 2.1.9

### Reproduction Link
https://jsfiddle.net/yreenchan/e1jw7qh0/

### Steps to reproduce
1. use v-if and v-for to render string
2. when the value is not Array, v-else also render as v-for

```
<div id="app">
  <p v-if="Array.isArray(desc)" v-for="item in desc">{{item}}</p>
  <p v-else>else: {{desc}}</p>
</div>
```

### What is Expected?
When the value is not Array, render v-else once as a string expected.

### What is actually happening?
v-else render multiple times.

**Comment by repsac-by** [comment]
https://vuejs.org/v2/guide/list.html#v-for-with-v-if
> When they exists on the same node, **v-for has a higher priority than v-if**

**Comment by posva** [comment]
what @repsac-by said. You can use the `template` tag: https://jsfiddle.net/posva/kakqtbpu/

**Comment by yreenchan** [comment]
@repsac-by @posva I got it, thanks!
