### ISSUE TITLE
`Vue.config.errorHandler` does not catch errors thrown in lifecycle hooks

### ISSUE THREAD

**Issue by blocka** [vuejs/vue#4730]
### Vue.js version
2.1.9

### Reproduction Link
https://jsfiddle.net/o2azdhbx/

### What is Expected?
Expect to see an alert saying "Caught an error"

### What is actually happening?
See an uncaught exception in the console

**Comment by LinusBorg** [comment]
As stated in the docs, this handle only catches errors during *render*:

> If a runtime error occurs during a component’s render, it will be passed to the global Vue.config.errorHandler config function if it has been set. 

Demo:

https://jsfiddle.net/Linusborg/o2azdhbx/1/

But it might be a good enhancement to make this possible for lifecycle hooks as well.

Optinions @vuejs/vue ?

**Comment by blocka** [comment]
Why is this not considered an error during render? Did it not happen while rendering the parent component?

**Comment by kay999** [comment]
It's quite annoying, because a non-cought error can stop a SPA working.

For example using a small catch around watcher.run() in flushSchedulerQueue makes live easier if an error happens while evaluating a getter:

```
function flushSchedulerQueue () {
    ...
    try {
		watcher.run();
    }
    catch(e) {
		config.errorHandler.call(null, e, watcher.vm);
    }
    ...
}
```

**Comment by yyx990803** [comment]
Implemented in `dev`, will land in 2.2.

**Comment by githoniel** [comment]
still exist in the newest Vue 2.2.4
hope this will land soon~~~

**Comment by LinusBorg** [comment]
This did land in 2.2. 

If you still experience problems, please open a new issue, with a live reproduction on jsfiddle.

**Comment by githoniel** [comment]
https://jsfiddle.net/githoniel/gL3f27eg/

it throw error in data function
