### ISSUE TITLE
Can't signup on vuejs forum

### ISSUE THREAD

**Issue by g-patel** [vuejs/vue#4734]
### Vue.js version
2.0.2

### Steps to reproduce
1) Go to https://forum.vuejs.org
2) Try to signup with github account.

### What is Expected?
I should be able to sign up for forum.

### What is actually happening?
Getting following error:
![image](https://cloud.githubusercontent.com/assets/12045773/22028877/8b863fb6-dc8d-11e6-9f2f-955497590ca2.png)

**Comment by g-patel** [comment]
Could not file a repo for codebase for https://forum.vuejs.org/, so filing the issue here.

**Comment by smolinari** [comment]
I can confirm the issue. 

Scott

**Comment by yyx990803** [comment]
Do you have a public email address associated with your GitHub account?

**Comment by g-patel** [comment]
@yyx990803 I have selected "Don't show public email" in my github account settings.

**Comment by g-patel** [comment]
Couple of folks in Gitter channel also confirmed the issue happening for them.

**Comment by liam-potter** [comment]
Can also confirm this issue. I'm guessing by your comment @yyx990803 that we need to have a public email address in order to sign up using GitHub?

**Comment by yyx990803** [comment]
It may have to do with the auth callback URL not using HTTPS - I just updated the settings, can you try again?

**Comment by liam-potter** [comment]
Works fine for me now. Thanks @yyx990803!

**Comment by g-patel** [comment]
Worked. @yyx990803

**Comment by sqal** [comment]
I think it's fixed now, ref: https://github.com/vuejs/vue/issues/4734
