### ISSUE TITLE
编写 vue 插件报错："plugin.apply is not a function"

### ISSUE THREAD

**Issue by zhaozhe0831** [vuejs/vue#4737]
node: 6.9.2
npm: 3.10.9
os: macOS Sierra 10.12.2 (16C67)

这是插件的入口文件，打包工具使用的是 webpack v1。

```
import {
    Components,
    Name
} from './components';

const version = '0.0.1';

const options = {
    prefix: 'Base' // 前缀
};

const install = (Vue, opts = options) => {
    if (install.installed) {
        return;
    }
    install.installed = true;
    const prefix = opts.prefix;
    Name.forEach((key) => {
        Vue.component(`${prefix}${key}`, Components[key]);
    });
};

export default {
    version,
    install,
    Components
};
```

插件是按官网上的说明来写的。
在项目中引用未打包的插件源文件时，是没有任何问题的。

```
import Vue from 'vue';
import App from './App';
import BaseComponents from '../components'; // 插件源文件目录

Vue.use(BaseComponents, {
    prefix: 'vue'
});

new Vue({
    el: '#app',
    template: '<App/>',
    components: {
        App
    }
});
```

引用编译后的插件文件时，浏览器控制台会报错，"plugin.apply is not a function"
```
import Vue from 'vue';
import App from './App';
import BaseComponents from '../../dist/index';  // 插件编译目录

Vue.use(BaseComponents, {
    prefix: 'vue'
});
/* eslint-disable no-new */
new Vue({
    el: '#app',
    template: '<App/>',
    components: {
        App
    }
});
```

![image](https://cloud.githubusercontent.com/assets/12945873/22053442/a2b95b6a-dd8b-11e6-82d6-d8ad3af081e1.png)

不确定是 webpack 的原因还是 vue 的原因。

**Comment by zhaozhe0831** [comment]
我在解决这个问题中，发现很多 vue 插件的 github 中都有这样的 issue。
但是没有找到确切的解决方法。
> https://github.com/sagalbot/vue-select/issues/84

**Comment by SterileSummer** [comment]
有的vue插件是一个[组件,Components](https://cn.vuejs.org/v2/guide/components.html)而非[插件,Plugins](https://cn.vuejs.org/v2/guide/plugins.html)，对这样的插件像Vue.use()这样使用是会报错："plugin.apply is not a function"

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

---

It may be that when you import `BaseComponent` you have to use `BaseComponent.default`. Try doing that in the `Vue.use(BaseComponents.default)`. If so something seems to be wrong with your webpack setup

**Comment by zhaozhe0831** [comment]
https://github.com/VueBaseUi/BaseComponents

**Comment by fnlctrl** [comment]
Closing as OP said the issue was resolved.

**Comment by Leomemory** [comment]
yarn global add @tarojs/cli@对应的版本
