### ISSUE TITLE
v-html can't work with v-if

### ISSUE THREAD

**Issue by iburning** [vuejs/vue#4738]
```
<div v-if="textShow" class="text" v-html="textShow"></div>
```

It's ok when first mounted. But when i change the data, it thows 'Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.'

I tryed sometimes and found it can work will by this way:

```
<div v-if="textShow" class="text">
  <p v-html="textShow"></p>
</div>
```

**Comment by posva** [comment]
Works fine for me: http://jsfiddle.net/posva/2yhustwu/
Update your Vue version to fix it. If it doesn't, open a new issue with a reproduction
