### ISSUE TITLE
2.1.6 父子组件通信 用$emit 触发事件 事件名不能使用驼峰 只能用小写 ,监听事件时也是一样 否则无法触发或者响应

### ISSUE THREAD

**Issue by raygongo** [vuejs/vue#4741]
### Vue.js version
2.0.2

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by yyx990803** [comment]
DOM 中的 HTML 不区分大小写。

**Comment by zhx0311** [comment]
的确是，$emit触发事件用驼峰命名法的确不响应，Vue.js version 2.1.9

**Comment by Yusoo** [comment]
可以响应啊
