### ISSUE TITLE
compile simple html via Vue.compile method

### ISSUE THREAD

**Issue by R-iskey** [vuejs/vue#4743]
Hi @yyx990803 , 
I've got a problem with the Vue.compile method.
I use jquery.datatables with Vue2 and want to use 'child row' functionality, for details please look into following link:
https://datatables.net/examples/api/row_details.html

I want to use datatable the same way as described in the link above, but I don't know how can I implement through Vue.component method.

Could you please help me out with this issue? Thanks in advance.

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com)to ask questions. Thanks!
