### ISSUE TITLE
Input radio not reset checked state when using as component

### ISSUE THREAD

**Issue by rorc** [vuejs/vue#4744]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/rorc/rhv2tLxk/1/

### Steps to reproduce
Clicking on radio, click on reset button.

### What is Expected?
1. Only one radio must keep checked.
2. After reset redio by clicking reset button, all radio must be not checked.

### What is actually happening?
All radio keep checked.

**Comment by yyx990803** [comment]
Your usage is incorrect - fixed: https://jsfiddle.net/rhv2tLxk/2/

**Comment by rorc** [comment]
Oh dude, thanks 😄
