### ISSUE TITLE
keep-alive include报错

### ISSUE THREAD

**Issue by Super-Meng** [vuejs/vue#4749]
![image](https://cloud.githubusercontent.com/assets/12838245/22100102/0c68d012-de69-11e6-8b62-85dbc65d7974.png)
![image](https://cloud.githubusercontent.com/assets/12838245/22100107/1129fe3c-de69-11e6-9b74-d47383c0be24.png)
sos......点击连接报错

**Comment by defcc** [comment]
@Super-Meng 请按照 issue-reporting-guidelines 来 报告 issue， 描述清楚潜在的 bug 的复现步骤，多谢。

**Comment by Super-Meng** [comment]
目前没有报错，但是view没有还是没有被keep-alive
![image](https://cloud.githubusercontent.com/assets/12838245/23389001/50df5e04-fda0-11e6-9dbc-b2ad5b9b1c45.png)
代码和上面一样，vue 2.1.6版本是可以的.
实在找不出问题原因求大神搭救...
