### ISSUE TITLE
Data reactivity bug, component discarding change

### ISSUE THREAD

**Issue by uptownhr** [vuejs/vue#4750]
This may be a very specific scenario but found when using data tree structures for recursion - ie: parent child relations. The bug is that, when a mutation to a child occurs, the parent receives to reactivity event but child components disregards the updated property. 

This is the simplest scenario I have been able to reproduce the bug. Here is a fiddle reproducing the problem, http://jsfiddle.net/cs9tu4hf/11/

You will be able to see that the root components are rendered without a problem. However, any childs added will not cause a change trigger. However, you can see that reactivity is still in play from the parent. 

This from the parent will be updated as childrens are added into the parent.
```
<ul v-if="trees[0]">
      <li v-for="child in trees[0].children">{{child.id}}</li>
    </ul>
```

**Comment by uptownhr** [comment]
I'm thinking this may be by design and if so, is there a better way to structure by data so changes are reflected? Currently, my only option is to repopulate the entire tree again.

**Comment by defcc** [comment]
```js 
this.byId[node.id] = node
```
this should be updated to 
```js
this.$set(this.byId, node.id, node)
```

please refer https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by LinusBorg** [comment]
```javascript
this.byId[node.id] = node
```

[Array Change Detection Caveats](https://vuejs.org/v2/guide/list.html#Caveats)
