### ISSUE TITLE
component use vue-server-renderer,the v-show is disabled

### ISSUE THREAD

**Issue by czonechan** [vuejs/vue#4751]
example
```
<component v-show="false" /> // render a span
<div v-show="false" />
<component :style="{display: show ? '' : 'none'}" />
```
result
```
<span />
<div style="display:none" />
<span  style="display:none"/>
```

**Comment by LinusBorg** [comment]
Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.

**Comment by leaves4j** [comment]
Same problem

**Comment by LinusBorg** [comment]
same answer.
