### ISSUE TITLE
v-model for components that wraps not text inputs (not default model)

### ISSUE THREAD

**Issue by nolimits4web** [vuejs/vue#4754]
### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/8n5qo677/

### Steps to reproduce
Check/uncheck checkboxes

### What is Expected?
Both inputs are should be checked/unchecked and represent model value in the first paragraph (bold value)

### What is actually happening?
Second (custom) input doesn't reflect and doesn't change binded model value

Hi, i'm porting Framework7 mobile framework to Vue.js (http://framework7.io/vue/) which provides a huge set of ready to use UI components for mobile development, including custom component inputs required for addition inputs appearance. The issue is when we use component with v-model that wraps input such as "checkbox", "radio" and "select" is binded to default model (used for text inputs, which binds to "value" and "input" events) because (i believe) Vue can not recognize what type of input inside. It is ok, but looks like there is no way to control such behavior, all we can do is to handle "change" event manually and bind it "checked" attribute. 

So would be good if we have kind of additional modifiers for v-model directive that allow us to tell Vue which kind of model is inside. E.g `<my-input v-model.checkbox="toggle">` etc.

And according to the source code at https://github.com/vuejs/vue/blob/7cb0ee5835458422f1e3b1d179ec638ecc788429/src/platforms/web/compiler/directives/model.js#L27-L34 the fix could be pretty simple such is:
```js
  if (tag === 'select' || modifiers.select) {
    genSelect(el, value, modifiers)
  } else if (tag === 'input' && type === 'checkbox' || modifiers.checkbox) {
    genCheckboxModel(el, value, modifiers)
  } else if (tag === 'input' && type === 'radio' || modifiers.radio) {
    genRadioModel(el, value, modifiers)
  } else {
    genDefaultModel(el, value, modifiers)
  }
```

Let me know if it is a good idea and can send a PR with this fix

**Comment by znck** [comment]
Fixed [your example](http://jsfiddle.net/8n5qo677/1/)

**Comment by nolimits4web** [comment]
@znck well, it is only solution for the current case, not for distributable components. What to do if we need to preserve input's value, and what to do with radios in this case: [Example with custom radios](http://jsfiddle.net/3mf4471x/1/)?

**Comment by znck** [comment]
`v-model` is supported with any component. Read the [docs - input components](https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events).

**Comment by nolimits4web** [comment]
@znck examples in docs are only for text inputs. Otherwise how to modify this [example with custom radios](http://jsfiddle.net/3mf4471x/1/) to be compatible with v-model?

**Comment by posva** [comment]
@nolimits4web You have to provide a prop with a different name than `value` to map to the checkbox, radio or option value

**Comment by nolimits4web** [comment]
@posva it is ok with this, but how to be with "checked" state binding as `:checked="value"` won't work here because the value is a string in this case rather what makes it always checked http://jsfiddle.net/112p0gs6/

**Comment by posva** [comment]
`<checkbox v-model="checked" real-value="foo"/>`. value is used for the input value, so you have to use a different name for the value:

`<input type="checkbox" :value="realValue" :checked="value">`

**Comment by nolimits4web** [comment]
@posva as I mentioned above it's ok for checkbox but doesn't work with input type="radio", check the example above

**Comment by posva** [comment]
just do `:checked="value === inputValue"`: http://jsfiddle.net/posva/a8oasrgt/
