### ISSUE TITLE
dynamic component v-model

### ISSUE THREAD

**Issue by zuomingcai** [vuejs/vue#4763]
vuejs does not behave properly when use v-model with dynamic component .

jsfiddle adress:
http://jsfiddle.net/zuomingcai/4pukLmnc/1/

focus the input element in above fiddle and press any key to see the hehavior.

**Comment by yyx990803** [comment]
The compiler generates different code for `v-model` based on

1. Wether the tag is a component
2. If native, the tag of the element (`input` vs `select`, `textarea` etc.)

`<component :is="xxx">` will be treated as a component and you should not use it to render native elements. This is a wontfix and you should use if branches if you want to render different elements with `v-model`.
