### ISSUE TITLE
Methods should not be executed more than once

### ISSUE THREAD

**Issue by chenweiqun** [vuejs/vue#4764]
### Vue.js version
2.1.10

### Reproduction Link
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div id="app">
    <div>
      {{getData()}}
    </div>
    <div>
      <input type="text" v-model="key">
    </div>
  </div>
</body>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.min.js"></script>
<script>
  new Vue({
    el:"#app",
    data(){
      return {
        key:"",
      }
    },
    methods:{
      getData(){
        console.log("When the value of key is changed");
        return "not change";
      }
    }
  })
</script>
</html>

```

### Steps to reproduce
 1. Modify the value of input
 2. View console panel
### What is Expected?
The getData method will be repeated, although there is no data dependency,
but the 1.0.28 is normal.only be executed once
### What is actually happening?
The getData method will be executed once.
Although the use of  computed can be solved, when I feel that should not be executed multiple times

**Comment by yyx990803** [comment]
In 2.x templates are compiled into render functions, and the entire function will be called whenever the component updates. This means your templates should never contain side effects. Put it in lifecycle hooks instead.
