### ISSUE TITLE
vue的props有什么用？ （is props property in vue useless?just for demo perpus?）

### ISSUE THREAD

**Issue by iasybvm** [vuejs/vue#4765]
> <html>

><head>
><script type="text/javascript" src="js/vue.js">
></script>
></head>
><body>
><div id="test">
>   <div>
>  <div is="comp1"></div>
> </div>
></div>
    <script type="text/javascript">
var  comp1 = Vue.component('comp1', {
    props: ['list'],
    // data: function() {
    //     return {list:['a', 'b']};
    // },
    template: '<a>{{ list }}</a>'
});
var   obj = new Vue({el:'#test',
    data: function() {
    return {list:[], item:30};
},
    created: function() {
        this.list = [1,2,3,4,5];
    }
});
    </script>
</body>
</html>

这种程度的父子组件，已经不能正常工作了，我还没有在ajax环境中使用它。
In this demo, it does not work as expected, even before I use some ajax.

如果上面，我写的不是var   obj = new Vue({el:'#test',而是定义了一个父组件，那么，vue，并用ajax从服务器获取list，那么，vue将会告诉我说，list undefined。

If I did not define a vue instance as above,  but defined a vue component, and use some ajax to fetch list from a remote server, then vue would say: list is undefined!

IT DID WORK IN DOC DOME, FOR DEMENSTRATION PURPOS!
竟然把官方论坛开到了墙外，祝邪恶政府，早日灭亡！

### Vue.js version
2.0.2

**Comment by yyx990803** [comment]
你真的有认真看文档吗？http://cn.vuejs.org/v2/guide/components.html#Prop
