### ISSUE TITLE
Wrong bind 'this' in .vue file's methods.

### ISSUE THREAD

**Issue by skatpgusskat** [vuejs/vue#4768]
### Vue.js version
2.1.10

### Code
.vue file
```
<template>
  <div>
    <button v-on:click="start">start</button>
  </div>
</template>

<script>
  export default {
    data: () => ({
      value: false,
    }),
    methods: {
      start: () => {
        console.log(this) // return undefined
      },
    },
  };
</script>
```

### What is Expected?

I expected ```this``` will have ```this.value``` as ```false```, but ```this``` was undefined.

### What is actually happening?

I found that if I change ```mothods```'s functions from arrow function to general function, It's solved.
I mean, with below code,
```
    methods: {
      start: funciton start() {
        console.log(this) // return { ..., value: false, ... }
      },
```
there are no problem.
But I think ```.vue``` file should provide ES2015, including arrow funciton.

Am I wrong?

**Comment by sqal** [comment]
That's not Vue's fault.  You shoud not use arrow function like this, use object shorthand syntax:

```
someMethod() {
  this.value = true; // this = vm
}
```

This article will probably explain it you better - thttps://rainsoft.io/when-not-to-use-arrow-functions-in-javascript/

**Comment by HerringtonDarkholme** [comment]
@sqal is right. Arrow function captures lexical `this`. In this case, your `() => this` will return undefined in strict mode. So this is expected.
