### ISSUE TITLE
(Chrome only) v-on events triggered on elements, which are hidden with v-if

### ISSUE THREAD

**Issue by chvelkov** [vuejs/vue#4771]
Hello,

I noticed some inconsistent behavior between browsers regarding how events are triggered when the DOM they're bound to is hidden.
Please check the JS fiddle below: it works as expected in Firefox, but in Chrome (Version 55.0.2883.87) when I click "Lock" both the lock() and unlock() callbacks are executed.

**Reproduction link:**
https://jsfiddle.net/26gavb93/4/

Thank you.

PS Vue is awesome! Thanks for the great work!

**Comment by phanan** [comment]
Hmm… Looks like on Chrome, the event is propagated up and is triggered on the `v-else` div as well. Not sure if it has anything to do with Vue. In the meantime, you can utilize the `.stop` modifier, like [this](https://jsfiddle.net/phanan/26gavb93/5/).

**Comment by chvelkov** [comment]
Yes, probably on Chrome vue patches the DOM faster than the event propagates up and as soon as the event reaches the div.item the other callback has been already reattached.

**Comment by LinusBorg** [comment]
It works when you add keys:

https://jsfiddle.net/Linusborg/26gavb93/6/

Then Vue will not re-use the div, and instead destroy it and create a fresh one for the v-else part.

**Comment by chvelkov** [comment]
@LinusBorg thanks, you are right.
