### ISSUE TITLE
Invalid render function if `v-if` is present on self closing tag

### ISSUE THREAD

**Issue by znck** [vuejs/vue#4772]
For `<i v-if="condition" class="foo" />` invalid render function is generated.

### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/zy7nj7zj/3/

### Steps to reproduce
--

### What is Expected?
Button should have text in it.

### What is actually happening?
Button does not have any text.

The render function is generated by vue-template-compiler@2.1.10.

**Comment by znck** [comment]
Yes, with template works find.

The render function is compiled with vue-template-compiler@2.1.10 using rollup.

😝 @posva Basically [your plugin template](http://github.com/posva/vue-plugin-template)

**Comment by posva** [comment]
@znck I tested locally after updating all dependencies and everything works fine
Maybe the vue-template-compiler was outdated?

**Comment by znck** [comment]
Can you share the generated render function?

**Comment by posva** [comment]
It did work with webpack but not with the rollup build 😅 . maybe the rollup plugin deps are outdated

**Comment by znck** [comment]
Okay! Then I've to update. I'm moving them to peerDeps.

**Comment by znck** [comment]
``` html
<icon v-if="icon" :type="icon" class="mr-2" />
```
compiles to
``` js
(_vm.icon)?_c('icon',{staticClass:"mr-2",attrs:{"type":_vm.icon}},[_vm._t("default",[_vm._v(_vm._s(_vm.value))])],2):_vm._e()
```

``` html
<icon v-if="icon" :type="icon" class="mr-2"></icon>
```
compiles
``` js
(_vm.icon)?_c('icon',{staticClass:"mr-2",attrs:{"type":_vm.icon}}):_vm._e(),_vm._t("default",[_vm._v(_vm._s(_vm.value))])
```

**Comment by znck** [comment]
Issue is with parse5 `serialize` method.

**Comment by mojodna** [comment]
@znck can you elaborate? i'm still seeing this (similar compiled templates) with vue@2.5.17 and vue-template-compiler@2.5.17.

I'm using Parcel@1.10.3 as the bundler, in case that's related...

**Comment by znck** [comment]
As much I remember, this was an issue with `parse5` usage in `rollup-plugin-vue`. 

In older version of `rollup-plugin-vue`, it was processing HTML templates with `parse5` to replace CSS classNames from CSS modules. The output HTML from `parse5` was in  case of `v-if` on self closing tag. 

You can check in parcel if it does some processing before using `vue-template-compiler`'s compile method.

**Comment by mojodna** [comment]
Awesome, thank you. I'll have a look.

**Comment by mojodna** [comment]
For anyone who's following along at home, the issue w/ Parcel is in posthtml-parser and can be fixed with a custom `.posthtmlrc` (see https://github.com/parcel-bundler/parcel/issues/1103#issuecomment-406483009).
