### ISSUE TITLE
Custom methods through vue-class-component are not recognized with $ref

### ISSUE THREAD

**Issue by Yc-Chen** [vuejs/vue#4773]
Hi all,

I have got an error message like this:

```
error TS2339: Property 'show' does not exist on type 'Element | Vue | Vue[] | Element[]'
```

It points to a line like this:
```typescript
this.$refs['myDialog'].show()
```

This `show` is a method implemented in TypeScript using vue-class-component. It is in a class that extends Vue. I located the line in ./types/vue.d.ts [here](https://github.com/vuejs/vue/blob/dev/types/vue.d.ts#L41).

I guess it should be modified using generics like this:

```typescript
readonly $refs: { [key: string]: [V extends Vue] | Element | Array<V extends Vue> | Array<Element>};
```

But it doesn't work by just doing that.

Does anyone know how to do it right?

Thanks!

**Comment by HerringtonDarkholme** [comment]
You either need cast it `<YourComonent>this.$refs` or reify `$refs`.
https://github.com/HerringtonDarkholme/av-ts/wiki/FAQ#2-property-reification

**Comment by pengliheng** [comment]
your descript don't let me know how to fix this problem. pls show answer step by step.

**Comment by pengliheng** [comment]
your descript don't let me know how to fix this problem. show the answer step by step, pls.

**Comment by pengliheng** [comment]
really confuse about ts+ vue
