### ISSUE TITLE
Custom input and object in v-model

### ISSUE THREAD

**Issue by fsblemos** [vuejs/vue#4775]
### Vue.js version
2.0.2

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/129/

### Steps to reproduce
When using an object in v-model of a custom input and then I try to clean it, it doesn't work. In a native input it cleans but still not printing the emitted value `{{ form. email }}`. If I declare all properties in the form variable like this:

```
data() { 
  form: { 
    name: null, 
    email: null,
  } 
}`
```

the problem is solved, but for me, the main advantage of using objects in this case is not to have to declare all form fields. 

Am I doing something wrong or this is the only way to bind data using v-model and objects? I'd like the object values were updated as the same way normal variables do.

**Comment by yyx990803** [comment]
This is because you didn't declare `form.name` when you set it as an empty object so it's not even reactive. Fixed: http://jsfiddle.net/df4Lnuw6/130/
