### ISSUE TITLE
Failed to exec lint script

### ISSUE THREAD

**Issue by qq286735628** [vuejs/vue#4778]
### Vue.js version
2.1.10
### Steps to reproduce

1. clone mater (success)
2. exec `npm install` (success)
3. exec `npm run install:hooks` (success)
4. exec `npm test` (fail, Failed to exec lint script)
5. exec `npm run lint` (fail)

### What is actually happening?

> bobbli-mc1:vue libo$ npm run lint --verbose
> npm info it worked if it ends with ok
> npm verb cli [ '/usr/local/bin/node',
> npm verb cli   '/usr/local/bin/npm',
> npm verb cli   'run',
> npm verb cli   'lint',
> npm verb cli   '--verbose' ]
> npm info using npm@3.10.10
> npm info using node@v6.9.4
> npm verb run-script [ 'prelint', 'lint', 'postlint' ]
> npm info lifecycle vue@2.1.10~prelint: vue@2.1.10
> npm info lifecycle vue@2.1.10~lint: vue@2.1.10
> 
> > vue@2.1.10 lint /Volumes/Transcend/code/vue
> > eslint src build test
> 
> 
> /Volumes/Transcend/code/vue/src/platforms/weex/framework.js
>   103:5  error  Identifier '__weex_require_module__' is not in camel case  camelcase
> 
> /Volumes/Transcend/code/vue/build/build.js
>   51:11  error  Identifier 'screw_ie8' is not in camel case   camelcase
>   52:11  error  Identifier 'ascii_only' is not in camel case  camelcase
>   55:11  error  Identifier 'pure_funcs' is not in camel case  camelcase
> 
> /Volumes/Transcend/code/vue/build/karma.sauce.config.js
>   12:5  error  Identifier 'sl_chrome' is not in camel case        camelcase
>   17:5  error  Identifier 'sl_firefox' is not in camel case       camelcase
>   21:5  error  Identifier 'sl_mac_safari' is not in camel case    camelcase
>   29:5  error  Identifier 'sl_ie_9' is not in camel case          camelcase
>   35:5  error  Identifier 'sl_ie_10' is not in camel case         camelcase
>   41:5  error  Identifier 'sl_ie_11' is not in camel case         camelcase
>   47:5  error  Identifier 'sl_edge' is not in camel case          camelcase
>   55:5  error  Identifier 'sl_ios_safari_8' is not in camel case  camelcase
>   60:5  error  Identifier 'sl_ios_safari_9' is not in camel case  camelcase
>   65:5  error  Identifier 'sl_android_4_4' is not in camel case   camelcase
>   70:5  error  Identifier 'sl_android_5_1' is not in camel case   camelcase
> 
> ✖ 15 problems (15 errors, 0 warnings)
> 
> 
> npm verb lifecycle vue@2.1.10~lint: unsafe-perm in lifecycle true
> npm verb lifecycle vue@2.1.10~lint: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Volumes/Transcend/code/vue/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbib:/usr/local/Cellar/php56/5.6.29_5/sbin:/usr/local/Cellar/php56/5.6.29_5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> npm verb lifecycle vue@2.1.10~lint: CWD: /Volumes/Transcend/code/vue
> npm info lifecycle vue@2.1.10~lint: Failed to exec lint script
> npm verb stack Error: vue@2.1.10 lint: `eslint src build test`
> npm verb stack Exit status 1
> npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at EventEmitter.emit (events.js:191:7)
> npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at ChildProcess.emit (events.js:191:7)
> npm verb stack     at maybeClose (internal/child_process.js:877:16)
> npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> npm verb pkgid vue@2.1.10
> npm verb cwd /Volumes/Transcend/code/vue
> npm ERR! Darwin 16.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint" "--verbose"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! vue@2.1.10 lint: `eslint src build test`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue@2.1.10 lint script 'eslint src build test'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the vue package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     eslint src build test
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vue
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls vue
> npm ERR! There is likely additional logging output above.
> npm verb exit [ 1, true ]
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Volumes/Transcend/code/vue/npm-debug.log

**system**

OSX 10.12.2

**JAVA -version**

> bobbli-mc1:vue libo$ java -version
> java version "1.8.0_77"
> Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
> Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by posva** [comment]
Moved to the relevant repository

**Comment by posva** [comment]
Install packages with yarn and you should be good to go

**Comment by qq286735628** [comment]
install yarn with brew, it will made my npm not broke. i reinstall npm to fixed.

use yarn install package . but lint still exec fail.

> bobbli-mc1:vue libo$ npm run lint --verbose
> npm info it worked if it ends with ok
> npm verb cli [ '/usr/local/bin/node',
> npm verb cli   '/usr/local/bin/npm',
> npm verb cli   'run',
> npm verb cli   'lint',
> npm verb cli   '--verbose' ]
> npm info using npm@3.10.10
> npm info using node@v6.9.4
> npm verb run-script [ 'prelint', 'lint', 'postlint' ]
> npm info lifecycle vue@2.1.10~prelint: vue@2.1.10
> npm info lifecycle vue@2.1.10~lint: vue@2.1.10
> 
> > vue@2.1.10 lint /Volumes/Transcend/code/vue
> > eslint src build test
> 
> 
> /Volumes/Transcend/code/vue/src/core/observer/index.js
>   156:5   error  Expected indentation of 2 spaces but found 4    indent
>   157:9   error  Expected indentation of 6 spaces but found 8    indent
>   158:9   error  Expected indentation of 6 spaces but found 8    indent
>   159:13  error  Expected indentation of 10 spaces but found 12  indent
>   160:13  error  Expected indentation of 10 spaces but found 12  indent
>   161:17  error  Expected indentation of 14 spaces but found 16  indent
>   163:13  error  Expected indentation of 10 spaces but found 12  indent
>   164:17  error  Expected indentation of 14 spaces but found 16  indent
>   167:9   error  Expected indentation of 6 spaces but found 8    indent
>   170:5   error  Expected indentation of 2 spaces but found 4    indent
>   171:9   error  Expected indentation of 6 spaces but found 8    indent
>   173:9   error  Expected indentation of 6 spaces but found 8    indent
>   174:13  error  Expected indentation of 10 spaces but found 12  indent
>   177:9   error  Expected indentation of 6 spaces but found 8    indent
>   178:13  error  Expected indentation of 10 spaces but found 12  indent
>   180:9   error  Expected indentation of 6 spaces but found 8    indent
>   181:13  error  Expected indentation of 10 spaces but found 12  indent
>   183:13  error  Expected indentation of 10 spaces but found 12  indent
>   185:9   error  Expected indentation of 6 spaces but found 8    indent
>   186:9   error  Expected indentation of 6 spaces but found 8    indent
> 
> ✖ 20 problems (20 errors, 0 warnings)
> 
> 
> npm verb lifecycle vue@2.1.10~lint: unsafe-perm in lifecycle true
> npm verb lifecycle vue@2.1.10~lint: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Volumes/Transcend/code/vue/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbib:/usr/local/Cellar/php56/5.6.29_5/sbin:/usr/local/Cellar/php56/5.6.29_5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> npm verb lifecycle vue@2.1.10~lint: CWD: /Volumes/Transcend/code/vue
> npm info lifecycle vue@2.1.10~lint: Failed to exec lint script
> npm verb stack Error: vue@2.1.10 lint: `eslint src build test`
> npm verb stack Exit status 1
> npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at EventEmitter.emit (events.js:191:7)
> npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> npm verb stack     at emitTwo (events.js:106:13)
> npm verb stack     at ChildProcess.emit (events.js:191:7)
> npm verb stack     at maybeClose (internal/child_process.js:877:16)
> npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> npm verb pkgid vue@2.1.10
> npm verb cwd /Volumes/Transcend/code/vue
> npm ERR! Darwin 16.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint" "--verbose"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! vue@2.1.10 lint: `eslint src build test`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue@2.1.10 lint script 'eslint src build test'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the vue package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     eslint src build test
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vue
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls vue
> npm ERR! There is likely additional logging output above.
> npm verb exit [ 1, true ]
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Volumes/Transcend/code/vue/npm-debug.log

**Comment by HerringtonDarkholme** [comment]
It's probably caused by your eslint configuration. I cannot reproduce it in my local machine. ESLint should prefer local configuration over global one. Would you like recheck your eslint?

**Comment by qq286735628** [comment]
i check again and i have no global config for ESLint.

and global config will make node crash ? (exit status 1)

**Comment by HerringtonDarkholme** [comment]
I believe this is configuration problem. This error message ` 156:5 error Expected indentation of 2 spaces but found 4 indent` indicates eslint is not using local configuration. 

While I'm not confident about this, it seems your path `/Volumes/Transcend/code/vue/npm-debug.log` is strange. Maybe clean cloning and installing in a directory with full permission `777` will generate different results.

**Comment by qq286735628** [comment]
this will work

> bobbli-mc1:vue libo$ node node_modules/eslint/bin/eslint.js src build test
> 
> /Volumes/Transcend/code/vue/src/core/observer/index.js
>   156:5   error  Expected indentation of 2 spaces but found 4    indent
>   157:9   error  Expected indentation of 6 spaces but found 8    indent
>   158:9   error  Expected indentation of 6 spaces but found 8    indent
>   159:13  error  Expected indentation of 10 spaces but found 12  indent
>   160:13  error  Expected indentation of 10 spaces but found 12  indent
>   161:17  error  Expected indentation of 14 spaces but found 16  indent
>   163:13  error  Expected indentation of 10 spaces but found 12  indent
>   164:17  error  Expected indentation of 14 spaces but found 16  indent
>   167:9   error  Expected indentation of 6 spaces but found 8    indent
>   170:5   error  Expected indentation of 2 spaces but found 4    indent
>   171:9   error  Expected indentation of 6 spaces but found 8    indent
>   173:9   error  Expected indentation of 6 spaces but found 8    indent
>   174:13  error  Expected indentation of 10 spaces but found 12  indent
>   177:9   error  Expected indentation of 6 spaces but found 8    indent
>   178:13  error  Expected indentation of 10 spaces but found 12  indent
>   180:9   error  Expected indentation of 6 spaces but found 8    indent
>   181:13  error  Expected indentation of 10 spaces but found 12  indent
>   183:13  error  Expected indentation of 10 spaces but found 12  indent
>   185:9   error  Expected indentation of 6 spaces but found 8    indent
>   186:9   error  Expected indentation of 6 spaces but found 8    indent
> 
> ✖ 20 problems (20 errors, 0 warnings)
> 

this not work

> bobbli-mc1:vue libo$ npm run lint
> 
> > vue@2.1.10 lint /Volumes/Transcend/code/vue
> > eslint src build test
> 
> 
> /Volumes/Transcend/code/vue/src/core/observer/index.js
>   156:5   error  Expected indentation of 2 spaces but found 4    indent
>   157:9   error  Expected indentation of 6 spaces but found 8    indent
>   158:9   error  Expected indentation of 6 spaces but found 8    indent
>   159:13  error  Expected indentation of 10 spaces but found 12  indent
>   160:13  error  Expected indentation of 10 spaces but found 12  indent
>   161:17  error  Expected indentation of 14 spaces but found 16  indent
>   163:13  error  Expected indentation of 10 spaces but found 12  indent
>   164:17  error  Expected indentation of 14 spaces but found 16  indent
>   167:9   error  Expected indentation of 6 spaces but found 8    indent
>   170:5   error  Expected indentation of 2 spaces but found 4    indent
>   171:9   error  Expected indentation of 6 spaces but found 8    indent
>   173:9   error  Expected indentation of 6 spaces but found 8    indent
>   174:13  error  Expected indentation of 10 spaces but found 12  indent
>   177:9   error  Expected indentation of 6 spaces but found 8    indent
>   178:13  error  Expected indentation of 10 spaces but found 12  indent
>   180:9   error  Expected indentation of 6 spaces but found 8    indent
>   181:13  error  Expected indentation of 10 spaces but found 12  indent
>   183:13  error  Expected indentation of 10 spaces but found 12  indent
>   185:9   error  Expected indentation of 6 spaces but found 8    indent
>   186:9   error  Expected indentation of 6 spaces but found 8    indent
> 
> ✖ 20 problems (20 errors, 0 warnings)
> 
> 
> npm ERR! Darwin 16.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! vue@2.1.10 lint: `eslint src build test`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue@2.1.10 lint script 'eslint src build test'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the vue package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     eslint src build test
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vue
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls vue
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Volumes/Transcend/code/vue/npm-debug.log

this not work again

> bobbli-mc1:vue libo$ eslint src build test
> 
> Oops! Something went wrong! :(
> 
> ESLint couldn't find the plugin "eslint-plugin-flowtype". This can happen for a couple different reasons:
> 
> 1. If ESLint is installed globally, then make sure eslint-plugin-flowtype is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
> 
> 2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
> 
>     npm i eslint-plugin-flowtype@latest --save-dev
> 
> If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

**Comment by qq286735628** [comment]
maybe problem is `eslint-plugin-flowtype`

**Comment by qq286735628** [comment]
`777` not work.

where is the eslint global config? i have check `/User/libo/` and not found `.eslintrc` or `eslintrc.json` or something call eslint

**Comment by HerringtonDarkholme** [comment]
Remove your global `eslint` from your path or so.  You can try `eslint` in your source directory it should report the same error.

**Comment by rixlabs** [comment]
+1

**Comment by rixlabs** [comment]
Hi I had the same exact problem when using npm to install dependencies. All works fine with yarn.

My npm attempt was on a fresh installed mac so no possible conflict situation.

**Comment by jodriscoll** [comment]
@qq286735628 were you able to properly resolve this issue? Since it has nothing to do with Vue.js really, I'm concerned it's been resolved and I'll have to chase down the proper solution outside of this Issue report.
