### ISSUE TITLE
`destroyed` is triggered before `afterLeave`

### ISSUE THREAD

**Issue by weizhenye** [vuejs/vue#4782]
### Vue.js version
2.1.10

### Reproduction Link

https://codepen.io/weizhenye/pen/mRwoqE

### Steps to reproduce

1. Open DevTools.
2. Click Toggle Button.

### What is Expected?

Should outputs

```
beforeDestroy
beforeLeave
leave
afterLeave
destroyed
```

### What is actually happening?

It outputs

```
beforeLeave
leave
beforeDestroy
destroyed
afterLeave
```

In Vue v2, `beforeDestroy` is triggered after `leave`, and `destroyed` is triggered before `afterLeave`

In [Vue v1 document](http://v1.vuejs.org/api/#beforeDestroy), it mentions
> Note if there is a leaving transition, the destroyed hook is called after the transition has finished.

And I also write a [demo](https://codepen.io/weizhenye/pen/EZXMPd) with Vue v1, it works as expected.

**Comment by posva** [comment]
It's probably intended but I may be missing something

**Comment by yyx990803** [comment]
Yes, this is intended behavior in 2.x.

**Comment by ParallelUniv3rse** [comment]
Could anyone clarify why is this intended behavior and some possible solutions to wait for the transition to complete before destroying listeners in a component? 
My particular use case is waiting for a page transition to finish before deregistering some child components from mouse position updates.
