### ISSUE TITLE
Checkbox value not binding if v-model is present

### ISSUE THREAD

**Issue by amostajo** [vuejs/vue#4785]
The value is not binded to an input if the type is checkbox and the v-model attribute is present (works for radio and text inputs).

Here is the case scenario:
```html
<template v-for="(row, index) in someData">
    <label>
        <input name="input-sample"
            type="checkbox"
            :value="row"
            v-model="selected"
        />
        <span>{{row.name}}</span>
    </label>
</template>
```

Compiled result:
```html
<label>
    <input name="input-sample" type="checkbox" value="">
    <span>Row A</span>
</label>
<label>
    <input name="input-sample" type="checkbox" value="">
    <span>Row B</span>
</label>
```

**NOTE:** As noted, If the input is `radio` type the value is correctly binded, for some reason the bug is only present only for checkboxes. The value is also bindend if the `v-model="selected"` attribute is removed.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behaviour you described.

**Comment by yyx990803** [comment]
If your `row` is an object, what do you expect to see in the markup when binding it as `value`?
I tested using latest dev branch and if value is bound as a string it renders properly.

**Comment by amostajo** [comment]
It is not binding for me, even if it is a text. Only happens when the input
is a checkbox though.

**Comment by yyx990803** [comment]
Then you need to provide a reproduction. Otherwise there's nothing we can do.

**Comment by amostajo** [comment]
Seems to be working on this pen:
http://codepen.io/amostajo/pen/bgrQbE

**Comment by bg** [comment]
I had a similar issue and upgrading Vue to 2.2.1 fixed it. The key difference may be that I was using vue-cli webpack-simple in my failing case. When I converted it to a plain html file without this toolchain, the problem went away.

My app.vue is:

```
<template>
  <div>
    <input type="checkbox" name="test" v-model="test">
    Test: {{ test }}
  </div>
</template>
<script>
export default {
  name: 'app',
  el: '#app',
  data() {
    return {
      test: false,
    };
  },
};
</script>
```

My test.html is:

```
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.js"></script>
</head>
<body>
<div id="app"></div>
<script src="app-bundle.js"></script>
</body>
</html>
```

**Comment by bg** [comment]
I realize the above leaves out a lot for a reproducible test case, so I started from scratch as follows:

```
mkdir test
cd test
npm install vue-cli
vue-init webpack-simple
```

Edit index.html to add this:

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.js"></script>
```

Edit webpack.config.js to add:

```
  externals: {
    "vue": "Vue"
  },
```

Replace src/App.vue with:

```
<template>
  <div id='app'>
    <input type="checkbox" name="test" v-model="test">
    Test: {{ test }}
  </div>
</template>
<script>
export default {
  name: 'app',
  data() {
    return {
      test: false,
    };
  },
};
</script>
```

And finally build everything:

```
npm install
webpack
```

When I toggle the checkbox I expect to see:

```
[x] Test: true
```

Instead, I see:

```
[x] Test: false
```

Changing 2.1.10 to 2.2.1 in index.html results in the expected behaviour.

Ben
