### ISSUE TITLE
ican't dynamic add events  to a tag in my custom grid component

### ISSUE THREAD

**Issue by hpym365** [vuejs/vue#4786]
our company is devloping a grid component for javaer use in jsp or html by js
https://github.com/hpym365/vue-element
```
<template>
  <tbody>
  <template v-for="(row,index) in datalist">
    <tr @click="rowevent != null?rowevent(row,this.$el):''" :class="index % 2 === 0?bodytrclass[0]:bodytrclass[1]">
      <td v-if="col.show" v-for="col in collist" @click="eventbus(row,$event)" @mouseover="eventbus(row,$event)">
        <template v-if="col.type">
          <component v-for="com in col.type" :is="com" :rowdata="row" :colname="col.colname"
                     :tdcbfun="col.cbfun"></component>
        </template>
        <template v-else>{{ row[col.colname] }}</template>
      </td>
    </tr>
  </template>
  </tbody>
</template>
```
now  a question 

`<tr @click="rowevent != null?rowevent(row,this.$el):''" :class="index % 2 === 0?bodytrclass[0]:bodytrclass[1]">`

how can i add events by data (props) ?   dynamic v-on? 
i don't want to write @click @mouseover @.......

i want like this ....
```
props: {
  trevent: [{event:'click',eventfun:function (rowdata) {
    if(rowdata.age<10){  //@:click=eventfun(rowdata)
       alert('children')
    }
 }},{event:'mouseover',eventfun:function (rowdata) {
    if(rowdata.age<10){//@mouseover=eventfun(rowdata)
       tip('children')
    }
 }}]
}
```

another example  button component

```
<template>
  <div>
    <button @click="eventbus" @mouseover="eventbus">{{options.btnname}}</button>
  </div>
</template>

methods: {
      eventbus: function (rowdata, event) {
        var eventname = event.type
        var eventpos = event.currentTarget.localName

        this.$root.$emit(eventpos + eventname, rowdata)
      }
    }

vm.$on('trclick',function(){
.......do something
})
```
if sometime emit not $on  dont do it    ...this kind of  settlement  so .....

and  i also can use component :is   but javaer must write   component   so much
oh  v-if

终于可以写中文了  
我们公司正在开发一个公共组件，刚开始做现在正在做表格的组件。
这个组件是通用的，想用在公司的不同的系统上，也是开源的。
https://github.com/hpym365/vue-element
麻烦大家帮看看  现在如何可以 根据传入的props 数据 ，动态添加事件到某个标签上？
我找不到办法动态添加v-on   
想做的功能多一些  还不想总让研发人员写动态的component  
我尽量将vue封装成 jquery那种调用形式，大家都比较容易会。
其次是我现在在mainjs 里把vue写好的组件暴露出来window.$grid = grid.vue  然后在引入webpack打包好的js
然后直接使用  请问还有其他更好的关于把vue做成组件在外部调用的例子吗？
还有如果我这种方式引用的话  是否还能使用vue-router ? 最好给个例子 
英语不好麻烦各位了

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:36139 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo1Q-003lc6-24
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:39:44 -0600
Date: Tue, 24 Jan 2017 20:09:20 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485317360;
	bh=gT8e3rKe5sAHRUjWE4t1BLA3AvRDAfMvwPgEvEIyjQY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=eET3x/NHPinw2n9l6ILxNaxNyFooPgj54ipk5H4oHw+TtuP63HT8GJF896EZgjhrz
	 fC98ih1Teo51dVubGfh0H3KoL7I0O66NhuNntza7FJeqR699O5hTaQKsPqF9Ig3CZM
	 yqrsSWybv+3MuicUAyfd+NQvAAqBSp5KMUZ1/ml4=
