### ISSUE TITLE
Computed Property Set method not being hit

### ISSUE THREAD

**Issue by GeorgeHanson** [vuejs/vue#4794]
### Vue.js version
1.0.28

### Reproduction Link
[https://jsfiddle.net/1r8hgof7/2/](https://jsfiddle.net/1r8hgof7/2/)

### Steps to reproduce
Create a computed property with a getter and a setter. Create an input field with `v-model` to the computed property.

### What is Expected?
The set method to get hit 

### What is actually happening?
The set method is not getting hit

**Comment by stefanosandes** [comment]
Computed properties are read-only. If you want to format the values ​​displayed in your input, you can create a component and put the formatting logic in it. https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events.

**Comment by pzanitti** [comment]
@stefanosandes computed properties are not read-only, at least on v2, since you linked to its guide.

https://jsfiddle.net/z11fe07p/404/

**Comment by simplesmiler** [comment]
This is working as intended. If the `figure` setter was to hit, then what the `value` argument would be, and how would you tell which field has actually changed?

What you want is a computed property for every field, not a single property with a bulk of them.
