### ISSUE TITLE
Array syntax for style binding not working

### ISSUE THREAD

**Issue by ppillot** [vuejs/vue#4798]
### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/badmcfko/1/

### Steps to reproduce
Use array syntax for style binding [as described in the docs](https://vuejs.org/v2/guide/class-and-style.html#Array-Syntax-1) 

### What is Expected?
Each subsequent style refered at in the array should be applied to the element

### What is actually happening?
In 2.0.8, the first style only is applied. In 2.1.10, none is used (see jsfiddle)

**Comment by yyx990803** [comment]
Array syntax only accept an Array of style objects, not strings. Only the top level value can be a direct CSS string.

**Comment by ppillot** [comment]
Ooops... my apologies !
