### ISSUE TITLE
Synchronization between two variables off by one

### ISSUE THREAD

**Issue by wsw70** [vuejs/vue#4809]
### Vue.js version
2.1.10

### Reproduction Link

https://jsfiddle.net/WoJWoJ/honartnp/

### Steps to reproduce

I would like the height of one element to be synchronised with the height of another element. The contents of the second element change with time.

As visible in the linked example, the changes of the height of the upper `div` (with the blue background) are off by one with the changes of the height of the lower `div`. The behaviour is the same whether I use `Vue.nextTick()` or not.

### What is Expected?

That the height of the upper `div` changes in synchronization of the one of the `div` below (at the same moment)

### What is actually happening?

The change is off by one, that is only the next change in the lower `div`  after its height has changed trigger a change in the upper one.

_Note: this bug report was initially [a question on SO](http://stackoverflow.com/questions/41901521/why-is-a-watch-off-by-one-tick-in-vue-js)._

**Comment by posva** [comment]
You should use a `requestAnimationFrame` so the content is displayed when retrieving the div size: https://jsfiddle.net/ncx2y0no/

```js
    requestAnimationFrame(() => {
      document.getElementById("square").style.height = document.getElementById("text").offsetHeight + 'px';
    })
```
