### ISSUE TITLE
Vue fails to render in electron when required

### ISSUE THREAD

**Issue by justinmchase** [vuejs/vue#4811]
### Vue.js version
v2.1.10

### Reproduction Link
Fairly complex repro which I don't have time to make a whole repo for it

### Steps to reproduce
1. Install electron and vue via npm
```bash
$ npm install electron
$ npm install vue
```
2. Create index.html
```html
<html>
<body>
<div id="app">
  {{ message }}
</div>
<script>
var Vue = require('vue')
window.addEventListener('DOMContentLoaded', () => {
  var app = new Vue({
    el: '#app',
    data: {
      message: 'Hello Vue!'
    }
  })
})
</script>
</body>
</html>
```
3. Create electron main process file:
```js
const { app, BrowserWindow } = require('electron')

let mainWindow
app.on('ready', () => {
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800
  })
  mainWindow.loadURL(`file://${__dirname}/index.html`)
})
```
4. Run the app
```bash
$ electron main.js
```

### What is Expected?
The message "Hello Vue!" is rendered

### What is actually happening?
Nothing is rendered. This warning is produced:

```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in root instance)
warn 
@ E:\code\evenflow-ui\node_modules\vue\dist\vue.runtime.common.js:521Vue._mount 
@ E:\code\evenflow-ui\node_modules\vue\dist\vue.runtime.common.js:2600Vue$2.$mount 
@ E:\code\evenflow-ui\node_modules\vue\dist\vue.runtime.common.js:6178Vue._init 
@ E:\code\evenflow-ui\node_modules\vue\dist\vue.runtime.common.js:3381Vue$2 
@ E:\code\evenflow-ui\node_modules\vue\dist\vue.runtime.common.js:3429(anonymous function) 
@ index.js:166
```

### NOTE: It works as epxected if you instead load via:
```html
<script src="https://unpkg.com/vue/dist/vue.js"></script>
```

From stepping into the code the versions in the comments appear to be identical but the actual code files have different line numbers. I tried to follow through both and see whats going on but I couldn't figure it out. The only thing I could see was that `$options.render` was null in the require'd case and was assigned an empty renderer instead.

**Comment by yyx990803** [comment]
The default npm export from `require('vue')` is the [runtime-only build](https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build) so it doesn't support compiling templates on the fly.

Better yet you may want to use a Electron + Vue boilerplate: https://simulatedgreg.gitbooks.io/electron-vue/content/

**Comment by justinmchase** [comment]
I see, thanks! I was trying to be lazy and avoid webpack since you don't technically need it in electron but it would solve this problem so thanks for the info.
