### ISSUE TITLE
v-bind with get/set function

### ISSUE THREAD

**Issue by andrisi** [vuejs/vue#4814]
Sometimes the connection between data and displays is not so direct. For example I need a list of checkboxes, but store only the checked one's ids in an array. It would be useful to be able to add a get/set function pair in v-bind, with the ability to pass an aditional value to it. So it would be called with set(id, true) on clicking the checkbox, and get(id) when initialising it. Or perhaps extend the computed property's get/set functions with this ability.

(See: https://forum.vuejs.org/t/checkboxes-based-on-wether-a-value-is-in-an-array/5752)

**Comment by yyx990803** [comment]
FYI `v-model` supports checkboxs bound to Arrays out of the box: https://vuejs.org/v2/guide/forms.html#Checkbox

**Comment by andrisi** [comment]
Thanks!

**Comment by andrisi** [comment]
Would this binding type of checkboxes work with radio buttons too? Storing the selected radio item's value into the array, and removing all others' values? But leaving any other values in that array intact as we might use them to store other selections too.

**Comment by yyx990803** [comment]
@andrisi unlikely. Radio buttons represent a single value by definition... I think you'd be better off to stick to a data structure that aligns with what the form inputs are designed for.

**Comment by andrisi** [comment]
@yyx990803 Form inputs are for display, while they might not represent the best way to store the selection. If you have a flat and selectable features then you use a checkbox, but some features are mutually exclusive (house or flat) so you use a radio button but you'd still like to store them in the features list as that's suites the relational model. If Vuejs is so data based, this should not be a surprise, or we'll need some workaround. Then the initial feature request here would come in handy, having set/get functions for v-model.

**Comment by posva** [comment]
Your form inputs should definitely represent at least a subpart of the data structure.
Since this is already achievable with computed setters I don't think we need to add anything new to the API

**Comment by andrisi** [comment]
@posva Yes, but this requires us to create a computed property for each radio group. While if the get/set function pair would support an id param, the solution could be cleaner.

**Comment by posva** [comment]
A computed property would gather those getters and setters together, and would be, imo, cleaner

**Comment by andrisi** [comment]
Maybe I don't understand your solution. You'd have a computed property and it's get/set function for each radio group - say 10? It is doable, of course, but isn't it simpler to add a v-model="computedWithParam" and then a single computedWithParam with one set(id, val) and one get(id) function?

**Comment by posva** [comment]
I don't see the difference. I think you should add a jsfiddle to show what you're trying to do 😄 
2 groups are enough for the example 😛

**Comment by yyx990803** [comment]
1. Store your form data in a structure that suits what is natural with the form input bindings (most likely an object)

2. Create a single computed property that translates this whole data structure into your desired format (e.g. an Array).

**Comment by andrisi** [comment]
@yyx990803 Sure, it'll work. Somehow I wanted to avoid the intermediate step - lots of code to translate back and forth, and just have a single view of the data. This will require even more mingling when sending the data to the server, as some data will come from some props, while this array will have to be manually added as it's a computed property.

**Comment by andrisi** [comment]
@posva https://jsfiddle.net/w3hrnqby/4/ - let's say "something" is based on other controls, and I did not even implement the set function. Instead I'd have v-model.set="setprop", and called as setprop(name, value).

**Comment by posva** [comment]
This is what I was talking about: https://jsfiddle.net/posva/2mn1nuL0/
ofc it looks silly with such a simple example. IMO a better approach would be using an object instead of an array. Keep in mind the computed setters and getters can be generated. Hope it helps
Cheers
