### ISSUE TITLE
String argument in @click with a single quote html encoded as content breaks vue.

### ISSUE THREAD

**Issue by emilioastarita** [vuejs/vue#4815]
### Vue.js version
1.0.28

### Reproduction Link
https://jsfiddle.net/76ueL3f8/2/

### Steps to reproduce
1. Call in `@click=` a function of a vue instance using as argument a string with a single quote html encoded as: `@click.prevent="test('own&#039;s')" `

### What is Expected?
2. Execution of the calling function `test` in the vue instance.

### What is actually happening?
Vue js fails with a: `Invalid expression. Generated function body:`

**Comment by simplesmiler** [comment]
This is not a bug. `&#039;` gets parsed by html parser into `'`, and Vue only sees `test('own's')`, which is not a valid expression.

If you want to pass literal `&#039;` to the function, you have to entity encode the ampersand: `test('own&amp;#039;s')`. If you want to pass literal `'` to the function, you have to encode it as JavaScript expects: `test('own\'s')`.
