### ISSUE TITLE
FEATURE REQUEST : access transition components via $refs

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#4816]
Hi, 
Wondering why we can't have access to transition components via `$refs`. 
(fiddle here : https://jsfiddle.net/vu4xugeh/2/ )

It would be great so we can listen to transition hook programatically, so we handle easily chained animations, like :
```
methods: {
  triggerAnimationA: {
  // change state to trigger animation A
  },
  triggerAnimationB: {
    this.triggerAnimationA()
   this.$refs.animationA.$on('leave', () => {
    // change state to trigger animation B
   })
  }
}
```

Am I misleading ? Do you think it's a good idea or there any workaround ?
I stumbled upon this cause I need to control timing of multiple transitions within in one of my project.
Thanks.

**Comment by yyx990803** [comment]
Transition components are "abstract", they don't show up in the parent chain, nor are they "ref-able". This is intentional to keep them as declarative as possible.

As for your use case - why not just directly use a listener in the template?

**Comment by AlexandreBonaventure** [comment]
I can use a listener in the template, but I don't want to couple transition with my action. So one way to do it is to emit an event and trigger animation in the callback. Like 
```
<transition @after-leave="$emit('animationA-finish')"></transiiton>

and in component definition
methods: {
  triggerAnimationA: {
  // change state to trigger animation A
  },
  triggerAnimationB: {
    this.triggerAnimationA()
   this.$once.('animationA-finish', () => {
    // change state to trigger animation B
   })
  }
}
```
Is that correct ?
It just seemed it was a little verbose but that should be the way to go.
Thanks

**Comment by yyx990803** [comment]
I think that would work and definitely looks better than the ref-based solution.
