### ISSUE TITLE
Lazy Loading Components are not resolved and Vue Router and Vue.component doesn't display it

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#4817]
### Vue.js version
2.1.10

### Reproduction Link
No Repro but here is the code

```js
//components.js
import Vue from 'vue';

function lazyLoadComponents(paths) {
    let resolver;
    return paths.reduce((components, path) => {
        resolver = resolve => require([`./${path}.vue`], resolve);
        components[path] = resolver;
        Vue.component(path, resolver);
        return components;
    }, {})
}
let components = lazyLoadComponents([
    'App',
    'User',
    'Home',
    'Inquiry',
    'Product',
    'Rental',
    'Report',
    'Users',
    'Rentals',
    'Products',
    'Inquiries',
    'Dashboard',
    'Login'
]);

export default components;
```

```js
//routes.js
import Components from './components';
console.log(Components);
const routes = [{
        path: '/',
        component: Components.Home,
        name: 'home'
    },
    {   
        path: '/login',
        component: Components.Home,
        name: 'login'
    },
    {
        path: '/dashboard',
        component: Components.Dashboard,
        name: 'dashboard',
        children: [{
                path: 'users',
                component: Components.Users,
                name: 'users'
            },
            {
                path: 'rentals',
                component: Components.Rentals,
                name: 'rentals'
            },
            {
                path: 'inquiries',
                component: Components.Inquiries,
                name: 'inquiries'
            },
            {
                path: 'products',
                component: Components.Products,
                name: 'products'
            },
            {
                path: 'user/:user',
                component: Components.User,
                name: 'user'
            },
            {
                path: 'product/:product',
                component: Components.Product,
                name: 'product'
            },
            {
                path: 'rental/:rental',
                component: Components.Rental,
                name: 'rental'
            },
            {
                path: 'inquiry/:inquiry',
                component: Components.Inquiry,
                name: 'inquiry'
            }
        ]
    }

]

export default routes;
```

### Steps to reproduce
1. Install webpack-simple using vue-cli
2. Install vue-router
3. Create a router-view in App.vue
4. use lazyLoadComponents and pass the file names .vue components (without extensions)
5. use the returned components in Vue Router component paths
### What is Expected?
Resolve components for to use in Vue Router and Vue.component
### What is actually happening?
Component is not resolved using webpack and displays a blank page

![image](https://cloud.githubusercontent.com/assets/25447231/22452836/2aa05082-e7b5-11e6-96dd-069ad3ce433c.png)
![image](https://cloud.githubusercontent.com/assets/25447231/22452847/3a4c75d8-e7b5-11e6-9867-d6cb70b5f46c.png)

**Comment by posva** [comment]
I see you created a second account @DevEclipse but it looks like you still didn't read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines). 
Here are the relevant docs: https://vuejs.org/v2/guide/components.html#Async-Components, https://router.vuejs.org/en/advanced/lazy-loading.html in case you missed them
In case you're using webpack 2 check this: https://webpack.js.org/guides/migrating/#code-splitting-with-es2015

Please, next time open a post on the [Forums](https://forum.vuejs.org/) instead to ask for help and come back here when you have found a bug and narrowed down a reproduction for it, thanks.

**Comment by DevEclipse** [comment]
I can't really post on the forums ip is blocked and i don't know why even registration is blocked how can i do that?

I've read all the documentations as you can see on the code the resolve => require([`./${path}.vue`],resolve);

is in a resolver variable and passed on

well i'll guess i'll try the import function

**Comment by posva** [comment]
I reached out for help about the ip block 🤞

**Comment by LinusBorg** [comment]
uhm ... you just posted?

https://forum.vuejs.org/t/async-components-not-resolving-components/5792

**Comment by ralphchristianeclipse** [comment]
well good thing i can post right now 

thanks
