### ISSUE TITLE
Can't login to vue.js web-site to participate at discussions

### ISSUE THREAD

**Issue by alexmakeev** [vuejs/vue#4818]
I see empty login page
![2017-01-31_11-09-43](https://cloud.githubusercontent.com/assets/4517420/22454173/dc2ce0be-e7a5-11e6-8784-3d46142212f7.png)

**Comment by alexmakeev** [comment]
Chrome 55.0.2883.95  64bit on MacOS 10.11.6

**Comment by posva** [comment]
You're looking for https://forum.vuejs.org/
The archives are for the old forum and is read only
