### ISSUE TITLE
running vue-cli for the first time 

### ISSUE THREAD

**Issue by siempay** [vuejs/vue#4821]
### Vue.js version
2.0.2

### Steps to reproduce
$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev
### What is Expected?
expect to see the page of vue-cli in my browser 
### What is actually happening?
`localhost/:3 Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (app.js:696)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.<anonymous> (app.js:587)
    at __webpack_require__ (app.js:556)
    at app.js:579
    at app.js:582`

**Comment by posva** [comment]
https://github.com/vuejs/vue-cli/issues/318
