### ISSUE TITLE
Simplify list-rendered slots

### ISSUE THREAD

**Issue by mrcsmcln** [vuejs/vue#4823]
When I want to render a slot in a list, I need to do something like this:

Child.vue:
```vue
<template>
  <ul>
    <li v-for="name in Object.keys($slots)">
      <slot :name="name"></slot>
    </li>
  </ul>
</template>
```

Elsewhere we have:
```vue
<child>
  <p slot="foo_0">Lorem ipsum dolor sit amet</div>
  <img slot="foo_1" src="/images/1.png">
  <blockquote slot="foo_2">Hello, World!</blockquote>
</child>
```

This produces:
```vue
<ul>
  <li>
    <p>Lorem ipsum dolor sit amet</div>
  </li>
  <li>
    <img src="/images/1.png">
  </li>
  <li>
    <blockquote>Hello, World!</blockquote>
  </li>
</ul>
```

If I want to namespace these slots (e.g., all slots starting with `foo_`), then I need to make a computed property that filters out all non-`foo_` slots and iterate that property instead.

Would there be a way for Vue.js to sense that a given slot is being rendered in a list and/or that it has multiple entries, like so?

Child.vue:
```vue
<template>
  <ul>
    <li v-for="item in $slots.foo.items"> <!-- or $slots.foo.length, $slots.foo.items.length, etc. -->
      <slot name="foo"></slot>
    </li>
  </ul>
</template>
```

And elsewhere we would have:
```vue
<child>
  <p slot="foo">Lorem ipsum dolor sit amet</div>
  <img slot="foo" src="/images/1.png">
  <blockquote slot="foo">Hello, World!</blockquote>
</child>
```

The rendered code would be exactly the same as mentioned above. I think this would greatly simplify an uncommon but useful practice.

**Comment by yyx990803** [comment]
I think the proposed syntax is quite confusing - `<slot name="foo"></slot>` is static inside each loop, it doesn't make use of `item`; and what does `item` represent?

I think this is a use case where a render function would make much more sense since you get full JavaScript flexibility. I really don't think adding more micro syntax to slots is a good idea.
