### ISSUE TITLE
Simplify use of arguments object in events

### ISSUE THREAD

**Issue by SawyerHopkins** [vuejs/vue#4824]
Occasionally I will run into situations in my project where I need data to be bound to my callback for events such as in the example below.

```vue
<!-- app.vue -->
<my-component @test:event="testHandler('someValue', arguments)"></my-component>

methods: {
    testHandler(componentValue, args) {
    }
}
```

```html
<!-- MyComponent.vue -->
<button @click="$emit('emitValue1', 'emitValue2')">Click me</button>
```

I think that explicitly accessing the arguments object is a bit tedious. I propose creating a new modifier `.bind` which will automatically apply the arguments object to the function, such that the final syntax would look like:

```vue
<!-- app.vue -->
<my-component @test:event="testHandler.bind('someValue')"></my-component>

methods: {
    testHandler(componentValue, emitValue1, emitValue2) {
    }
}
```

```html
<!-- MyComponent.vue -->
<button @click="$emit('emitValue1', 'emitValue2')">Click me</button>
```

I have already looked into this and it is a fairly small change to the compiler. I don't know if `bind` is the correct word to use for this, as it doesn't allow change to the `this` context, maybe `apply`? Anyway feedback is welcome, and if this is a desirable feature I can write tests for this and create a PR.

**Comment by LinusBorg** [comment]
> I think that explicitly accessing the `arguments` object is a bit tedious. I propose creating a new modifier `.bind` which will automatically apply the arguments

I don's think this provides a significant advantage - you save exactly 2 characters by replacing `"arguments"`(9 chars) with `".bind()"` (7 chars).

Furthermore, ES6 makes it very easy to deal with arguments with destrcturing:

```javascript
handler(someValue, [value1FromArgument, value2FromArgument]) {
  // do your thing
}
```
Live example: https://jsfiddle.net/Linusborg/50wL7mdz/12329/

**Comment by yyx990803** [comment]
Or use the spread operator:

``` html
<my-component @test:event="testHandler('someValue', ...arguments)"></my-component>
```
