### ISSUE TITLE
Nested scoped slots (provide content for parent without losing child scopes)

### ISSUE THREAD

**Issue by hector-humberto** [vuejs/vue#4826]
Hello. I am trying to develop a small component for personal use. It is a data table component that should allow customization of `tr` element and its `td` child elements independently. Both element types are scoped slots that each offer fallback markup. This is a very simplified example of what I am working with:
```html
<table>
  <tbody>
    <slot name="row" v-for="(row, index) of rows" :row="row" :index="index">
      <tr>
        <slot v-for="(value, key) of row" :name="key" :value="value">
          <td>{{ value }}</td>
        </slot>
      </tr>
    </slot>
  </tbody>
</table>
```
I am currently able to customize `tr` and `td` slots, but changing out `tr` requires for me to re-implement it's `td` children. I understand the reason for this is that whatever markup I place inside `<slot/>` is *fallback* content. So, by specifying content for `<slot name="row"/>`, the component no longer has any knowledge of each `td` slot. However, I would still like to be able to customize that `tr` root element independently somehow while still keeping the *rest* of the slot's fallback content, optionally being able to also customize one or several of the `td` slots. Here is an example of what I want to do:
```html
<example :rows="rows">
  <template slot="row" scope="{ row, index }">
    <tr :class="[ (index + 1) % 2 === 0 ? 'even' : 'odd' ]">
      <!-- somehow show td slots' fallback markup -->
      <template slot="id" scope="{ value }"> <!-- customize only 'id' slot -->
        <td style="text-align: right; background-color: blue; color: white;">{{ value }}</td>
      </template>
    </tr>
  </template>
</example>
```
I asked this question on the vue forums and got no answer, so I assume this isn't currently possible. I am submitting this as a feature request.

I have a codepen up and running [here](http://codepen.io/hector-rodriguez/pen/ZLvQqm) for testing. Thank you very much for your help.

**Comment by HerringtonDarkholme** [comment]
I would suggest you to use render function or JSX to manipulate VNode. 

IMHO, the suggestion here would require template users mark a position to insert fallback content.

For example.

```html
<slot name="row">
  <tr>
   additional text
   <insert-default-td-here>
  </tr>
</slot>
```

This is quite hard to add without adding [compilation scope](https://vuejs.org/v2/guide/components.html#Compilation-Scope) caveats. 

On the other hand, Vue's render function support will give you enough power to express arbitrary logic in template code. This case is a niche for render function.

**Comment by hector-humberto** [comment]
Hm. Hadn't really thought of that. Mind providing an example?

**Comment by yyx990803** [comment]
Content inside slots are parsed as fallback content, so the proposed syntax is a no-go. As suggested, render functions are exposed for the exact purpose of full programmatic flexibility in composing content, but that is a usage question so please discuss that on the forum instead.

**Comment by hector-humberto** [comment]
Ok, thank you @yyx990803. I will try and figure it out. It is just a shame that something conceptually simple and practical is only achievable through the proposed solution which sounds a bit complicated and perhaps not worth it. I worry about what @HerringtonDarkholme mentioned about the compilation scope caveats.

**Comment by codebykyle** [comment]
I have this exact same use case as @hector-humberto. Thanks for the suggestions.
