### ISSUE TITLE
[Feature Req] bind 'event' to lifecycle hooks

### ISSUE THREAD

**Issue by ctf0** [vuejs/vue#4827]
atm vue treats the data coming from the instance as the only truthy source https://vuejs.org/v2/guide/forms.html#Basic-Usage which is fine in most of the time, but what if am using something like **Laravel** or any backend where we could send something to the view file.

> but why not get those data through ajax ?

because when we use the **inline-template** feature, we can then use the code we are already used to in blade while using the full power of vue 💃 
```blade
@extends('layouts.app')

@section('content')
    <auth-form inline-template>
        {{ Form::open(['route' => 'post.resetpassword', 'class'=>'form-horizontal','@submit.prevent'=>'FormSubmit']) }}
        
            {{-- Token --}}
            <form-input inline-template>
                <input type="hidden" name="token" value="{{ $token }}">
            </form-input>

            {{-- Email --}}
            <form-input inline-template :has-errors="errors.email">
                <div :class="[{'has-error': hasErrors}, 'form-group']">
                    {{ Form::label('email', 'E-Mail Address', ['class'=>'col-md-4 control-label']) }}
                    <div class="col-md-6">
                        {{ Form::email('email', $email, ['class'=>'form-control','autofocus','v-model'=>'input']) }}
                        <form-errors :errors="hasErrors"></form-errors>
                    </div>
                </div>
            </form-input>
       
            ...
        {{ Form::close() }}
    </auth-form>
@endsection
```

but the problem starts to raise when we want to add a pre-init value to the `v-model` like
```blade
<form-input inline-template>
    <input type="hidden" name="token" value="{{ $token }}" v-model="input" >
</form-input>
```
which is sadly is not available for the input fields https://vuejs.org/v2/guide/forms.html#Value-Bindings

however, we can still achieve that through a dirty hacky fix, like
```blade
<form-input inline-template>
    <input type="text" name="token" data-token="{{ $token }}" @blur="hiddenValue" autofocus style="opacity: 0;height: 0;width: 0">
</form-input>
```
```js
methods: {
    hiddenValue() {
        this.input = event.target.dataset.token
    }
},
```

### But 
what if we instead got an `event` instance available for us through the lifecycle hooks, same as `watch,computed,event methods`, and now we can make things even cleaner by
```blade
<form-input inline-template>
    <input type="hidden" name="token" data-token="{{ $token }}">
</form-input>
```
```js
created(event) {
    this.input = event.target.dataset.token
},
```

**Comment by sirlancelot** [comment]
You can listen on the `mounted` event for your inline component. Inside that handler, you can access the rendered DOM tree in `this.$el`.

**Comment by hector-humberto** [comment]
Dracula is on the right path, but if you print your initial data before invoking your Vue script, it should already be available to your `data` callback. Something like:

```blade
@section('content')
<div id="app">
  <some-component></some-component>
</div>
<script>
  var initialData = {!! json_encode($initialData) !!};
</script>
<script src="app.js"></script>
@stop
```
```html
// some-component.vue
<script>
export default {
  data() {
    return { ...initialData }
  }
}
</script>
```

**Comment by hector-humberto** [comment]
Provided a more complete example.

**Comment by ctf0** [comment]
@sirlancelot thanx for the suggestion, but it returns the dom elem itself, is which case its not exactly what am after.

@hector-humberto thanx for hacky way around, but again not what i was after

**Comment by HerringtonDarkholme** [comment]
Hi, I think @sirlancelot 's approach is good enough for server-side rendered form.

 Example: http://jsfiddle.net/gjwL7byz/

Also @hector-humberto 's approach is a standard way for SSR. See https://github.com/vuejs/vue-hackernews-2.0 for example.

IMHO, the OP's suggestion is probably impossible for some lifecycle. When `created`  is called, Vue has not yet found the dom element, thus no `event.target`.

**Comment by hector-humberto** [comment]
@ctf0:
> @sirlancelot thanx for the suggestion, but it returns the dom elem itself, is which case its not exactly what am after.

> created(event) {
      this.input = event.target.dataset.token
},

You are contradicting yourself here.

> @hector-humberto thanx for hacky way around, but again not what i was after

Not sure how you interpret my code as hacky. Seems pretty clean to me.

@HerringtonDarkholme:
> Also @hector-humberto 's approach is a standard way for SSR. See https://github.com/vuejs/vue-hackernews-2.0 for example.

It's not exactly what SSR does. I'm only prerendering the JSON data. It's essentially the same as initially doing an AJAX call before rendering your component. The actual html is still generated client-side.

**Comment by yyx990803** [comment]
@sirlancelot 's suggestion does exactly what your proposed solution does:

``` js
mounted () {
  this.input = this.$el.dataset.token
}
```

**Comment by ctf0** [comment]
@hector-humberto hacky in a way that we first bind the value to the window, then we call it from vue
where instead i was looking more into binding the data to the input itself and call it from vue, which as you & @yyx990803 said its @sirlancelot solution is the correct one which last night for some strange reason was giving me error :cold_sweat: when trying `this.$el.dataset.token` and now its working.

still am more than thanx for all ur help ❤️ .

**Comment by hector-humberto** [comment]
No problem, brother.

**Comment by ctf0** [comment]
on a sidenote, if anyone could tell me why when using `watch()` with `mounted()` we get an error ?
here is the code
```js
export default {
    props:['hasErrors'],
    components: {
        'FormErrors': require('./Errors.vue')
    },
    data() {
        return {
            input: ''
        }
    },
    mounted () { // get the hidden inputs value
        if (this.$el.type == 'hidden') {
            this.input = this.$el.value
        }
    },
    watch: { // send data to the central storage to be picked up by the parent
        input(val) {
            storage.data.userInfo[event.target.name] = val;
        }
    },
}
```
and the error `Cannot read property 'target' of undefined`

**Comment by posva** [comment]
there's no event

**Comment by ctf0** [comment]
@posva but if i commented out the `mounted()` it works without any issues

**Comment by ctf0** [comment]
@posva here is a small vid of the problem
without `mounted()`
https://cl.ly/3V3p3U2L2I3j/Screen%20Recording%202017-02-01%20at%2007.59%20PM.gif
with
https://cl.ly/3H3p3j3H3n2J/Screen%20Recording%202017-02-01%20at%2008.01%20PM.gif

maybe its a bug or is it intended, not sure maybe @yyx990803 can shade some light over it ?

**Comment by posva** [comment]
There's no event variable in 
```js
input(val, oldVal) {
            storage.data.userInfo[event.target.name] = val;
        }
```
That's the js error

**Comment by ctf0** [comment]
i understand, but why when `mounted()` is left off , the event is magically available ?

**Comment by HerringtonDarkholme** [comment]
Because you set value input in `mounted`, so `watch` is executed. If you comment `mounted` out, `watch` will not run. It just hides the error, not magically cures the error.

If you have extended problem. Asking on gitter is more suitable. GitHub issue is for bug reporting and feature request.

**Comment by ctf0** [comment]
@HerringtonDarkholme i know about gitter but you are wrong about the `mounted` & `watch`

**Comment by LinusBorg** [comment]
@ctf0 Sorr, but @HerringtonDarkholme is right.

in your watch, you access `event`, which (in some browsers) is globally available during an browser(!) event callback, i.e. started by a `click` event.

But as the watch method is triggered by the data change resulting from the code in `mounted()`, there is no  `event`, or in other words: `event` is `undefined` - hence: `Cannot read property 'target' of undefined`
