### ISSUE TITLE
`created` hook throws error in JSFiddle… cannot submit other issue

### ISSUE THREAD

**Issue by speasley** [vuejs/vue#4828]
I have an issue that I am trying to replicate with JSFiddle but as soon as I try to leverage the `created` hook, it starts throwing errors. So I am unable to create the JSFiddle for what my actual issue is.

http://jsfiddle.net/speasley/8qL1kv1v/

Any ideas for a workaround so I can submit my real issue?

**Comment by sirlancelot** [comment]
The `created` property needs to be a Function. You've specified an Object.

**Comment by hector-humberto** [comment]
Dracula is right. Although that's not even a valid object declaration.

**Comment by speasley** [comment]
Right. Silly me.

Thanks.
