### ISSUE TITLE
v-model binding with array element malfunction 

### ISSUE THREAD

**Issue by sydwang** [vuejs/vue#4831]
### Vue.js version
2.1.10

### Reproduction Link

https://jsfiddle.net/seakid/novroard/
first time to use jsfiddle, hope you can see it.

### Steps to reproduce
  The first two raws demonstrate the v-model binding with array elements, they don't work normally.

### What is Expected?
The third raw is what I need, I am trying to create a table and I can modified the last column as I demonstrate with the last raw, by using - and +.

**Comment by sydwang** [comment]
I tried several version of vue.js, but all failed. I checked this website, and found the issue about v-model binding with array was discussed before. But I still fail to make my codes run correctly.

**Comment by HerringtonDarkholme** [comment]
Flip iteration to `(product, index)`.

https://jsfiddle.net/novroard/6/

**Comment by sydwang** [comment]
but the button - and + don't work normally.

**Comment by sydwang** [comment]
https://jsfiddle.net/seakid/novroard/7/
Just update the first two raws, the view doesn't update immediately. But if you update the third raw, the data of first two lines could be updated together.

**Comment by HerringtonDarkholme** [comment]
Please read the doc. https://vuejs.org/v2/guide/list.html#Caveats

https://jsfiddle.net/novroard/8/
