### ISSUE TITLE
Filter not recognized when filtered expression contains a '/' with ()

### ISSUE THREAD

**Issue by tals** [vuejs/vue#4838]
### Vue.js version
2.1.10

### Reproduction Link
A variation on #4415 
https://jsbin.com/heguyujupu/edit?html,console,output

### Steps to reproduce
```js
{{ (price) / 100 | currency }}
```

### What is Expected?
This divided number gets filtered

### What is actually happening?
Get this error:

```
[Vue warn]: Property or method \"currency\" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in root instance)"
```

**Comment by rixlabs** [comment]
The parser think  is a regex due to this check

`
(!p || !/[\w$]/.test(p))
`
line 58 of *filter-parser.js*


If you test it with the close parenthesis ')' it gives true.

I can add another 'if' and open a PR. If anyone see a better way just let me know

**Comment by tals** [comment]
Thanks for the quick response!

Seems like `data[0] / 1` and `1. /2` will blow up for the same reason. Might be worth rolling that into your PR

**Comment by rixlabs** [comment]
you're right I have to check all the parenthesis and the point. Is not the case for comma if I'm not wrong

**Comment by rixlabs** [comment]
Added dot and square brackets verification
