### ISSUE TITLE
Dynamic transform styling inside transition-group randomly not applied

### ISSUE THREAD

**Issue by mzgajner** [vuejs/vue#4840]
### Vue.js version
~~2.1.10~~ 2.2.6

### Browser version
~~Safari 10.0.3, also reproduced on a proprietary WebKit-based Samsung TV browser~~
All latest browsers (tested FF 52, Chrome 57 and Safari 10.0.3)

### Reproduction Link
~~[JSFiddle](https://jsfiddle.net/yMv7y/2239/)~~ [JSFiddle](https://jsfiddle.net/yMv7y/2447/)

### Steps to reproduce
1. Create a `<transition-group>` and apply a dynamic `transform` style to elements inside it.
2. ~~**Rapidly** (before the ongoing transition ends)~~ update values your transform is based on.
3. Observe some elements not receiving styling.

### What is Expected?
All elements should receive consistent transform styling.

### What is actually happening?
~~When updates are fast enough (nothing extreme, simply click on up/down buttons in the example as fast as you can),~~ some elements aren't styled.

The issue **doesn't** occur:

- ~~in other browsers (tried latest Chrome and Firefox);~~
- with other style properties (tried `font-size` and `color`);
- ~~if updates are slow enough current transitions can end;~~
- if you replace `<transition-group>` with just a `<div>` (but that doesn't provide consistent transitions).

**Comment by posva** [comment]
Hello, sorry for the delay.

I tried your fiddle but it yields the same result on Chrome and Safari. Can you, please, provide a GIF and double check the _Steps to reproduce_ ?

**Comment by mzgajner** [comment]
I checked the reproduction steps and they seem to be correct. Basically all you have to do is open the provided fiddle and click up/down buttons a few times very quickly. Here's how it looks on my side - doing it slowly works well while quick changes break it:
![safari-bug](https://cloud.githubusercontent.com/assets/1853648/22715068/9247145c-ed8f-11e6-9291-ba4e7c924121.gif)
I successfully reproduced it on two different machines in the office (both with latest macOS and Safari) and three different Samsung TVs with a custom WebKit browser, where I initially discovered the issue (we're developing a Vue based smart TV app).

**Comment by posva** [comment]
Damn, it just works fine in my Safari. Can you make sure no plugins are installed?
![screenflow](https://cloud.githubusercontent.com/assets/664177/22715702/8fcf3bb6-ed92-11e6-8d06-d291a0c2950b.gif)

**Comment by mzgajner** [comment]
Yup, just checked and I have no extensions installed. I also went under _Preferences > Security_ and unchecked `Allow Plug-ins`, no difference.

Can you try completely quitting Safari a few times? While testing this it sometimes randomly worked (maybe 1 out of 10 times), but all it took to break it again was a browser restart.

**Comment by posva** [comment]
I tried a bunch of times but it just works fine. Are you sure you don't have any extension activated?

**Comment by posva** [comment]
Can you share your user agent?
@phanan reproduced it with Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
Turns out I have a more recent version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

You can check that on http://www.whatsmybrowser.org/

**Comment by mzgajner** [comment]
I have the same version as you: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8`

**Comment by yyx990803** [comment]
It may have to do with this.... https://twitter.com/jaffathecake/status/829344704311488514

**Comment by mzgajner** [comment]
In case it helps, one of the TV browsers I mentioned where the issue is reproducible has the following: `Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1`

Though in my experience, these devices sometimes have incorrect user agents hardcoded, so take it with a grain of salt.

**Comment by mzgajner** [comment]
@yyx990803 I think it's not related to that regression for two reasons:

1. Apart from the already mentioned Samsung browser, I have since tried it on a few other devices with older WebKit and managed to reproduce it.
2. If I replace `<transition-group>` in the attached JSFiddle with a regular `<div>`, the bug is no longer reproducible (though this kills transitions in one direction because of elements being moved as [you previously explained to me](https://github.com/vuejs/vue/issues/4834)). The behaviour is absolutely consistent, I can open the JSFiddle in Safari and switch tags back and forth with the bug appearing/disappearing accordingly. This leads me to believe it's somehow connected to `<transition-group>`.

**Comment by mzgajner** [comment]
I've made a small breakthrough - I managed to isolate a [much better test case](https://jsfiddle.net/yMv7y/2446/) that is consistently reproducible in all the browsers I tried (latest Safari, Chrome and FF).

I'm also pretty certain it is related to how `<transition-group>` works, since everything goes back to normal if I simply use a `<div>`.

I have updated the initial post accordingly.

**Comment by posva** [comment]
But that's not how transition-group should be used: Check out the lazy sudoku example [here](https://jsfiddle.net/chrisvfritz/sLrhk1bc/)

**Comment by mzgajner** [comment]
OK, hmm, but the logic behind it is practically the same as in the first example.

So if I understand you correctly - I should position my elements with something else then transforms (flex/float/absolute/whatever) and the transition group will automatically animate using transforms?

**Comment by LinusBorg** [comment]
Yep, pretty much that.

**Comment by mzgajner** [comment]
Great, thanks a lot, closing.

**Comment by mgiraldo** [comment]
@mzgajner I ran into this same problem but in my case I'm using SVG so I don't have much of an option other than using CSS transforms for Vue-animated transitions. How to address this or am I left with no Vue transitions for my case?

**Comment by mgiraldo** [comment]
never mind. i figured it out. for anyone curious, [this is the component](http://livingarchive.herokuapp.com/bubble) i was talking about (link might change). click on the circles to see them moving around as you traverse the graph. this is all vue transition.

if curious about the code, [here's the code at this moment](https://github.com/mgiraldo/livingarchive/blob/7b5f8c2cf5a5faa2bbb73b8af6aa0b3bc1787fc3/components/BubbleComponent.vue)
