### ISSUE TITLE
Functional components cannot accept classes

### ISSUE THREAD

**Issue by scottbedard** [vuejs/vue#4842]
### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/5sH6A/993/

### Steps to reproduce
Render a functional component, and attach a class to it.

### What is Expected?
The component should be rendered with the given class.

### What is actually happening?
The component is rendered, but without the class.

### Additional info
It appears that we cannot accept a prop named `class` either, as it is always equal to whatever it's default value is.

**Comment by yyx990803** [comment]
Functional components do not inherit anything from the placeholder element - the raw bindings are contained in `context.data`. You need to do something like this to inherit them:

``` js
render (h, ctx) {
  return h(
    'div',
    ctx.data, // inherit raw binding data from placeholder node
    [ ... ]
  )
}
```

**Comment by scottbedard** [comment]
Sweet, thanks for the fast response!
