### ISSUE TITLE
Functional component OR CreateElement() (Bug or doc unclear to me)

### ISSUE THREAD

**Issue by MarcTe** [vuejs/vue#4851]
Hi,
I have been trying to make Functional Component work and get help for resolving this on the forum. But did not succeed yet.

Could it be because of a bug or a misunderstanding of the doc about Functional Component or CreateElement() or $emit?

The example component hierarchy is App-f-tx2-myButton
(f is the functional component selecting tx2)
For visual overview of my component hierarchy (a pdf)
[functional component not working.pdf](https://github.com/vuejs/vue/files/752440/functional.component.not.working.pdf)

1) I am able to call a tx2 component from f's createElement();

2) I am not able to propagate the click event (from myButton to tx2 it works, but not from tx2 back to App), even if I add this in f:

```
return createElement(
      retComp(),
      context.parent  // if I add this
    )
```
But, now, I am able to call it directly  from tx2 with: `this.$parent.addOne();`
It however, generates, at every call, a re-render of f component TWICE, as it occurs during the f instanciation. (this was also occuring before I used this method of direct call) 
Is it normal that functional component be called twice at instanciation and twice at re-render?
(this occures even if addOne does not mean any change in the f and its down line components)

Not shure how to forward down the App context
3) I am not able to read app context from within f

4) Parent's context in the f component does not seem to contain the expected content (props, children, slot, data and parent) I get: `[{"text":"tx","raw":false,"isStatic":false,"isRootInsert":true,"isComment":false,"isCloned":false,"isOnce":false}]`

5) Nor this context seems to be in a usable format by (JSON.strignify or JSON.parse) or easily accessed as context.[0].... for reading the text value.
I need to do this:
```
      var str=JSON.stringify(context.children);
      var res= str.substr(1, str.length-2);
      var res2=JSON.parse(res);
      console.log('str:'+res2.text);
```

6) Not shure how to really access App methods or data from children 
with parent's pointer (that I could get from context) without declaring 
`props `and `on:` in the component call
(I know, maybe not a good programming technique, but as it is the upper component that needs to take care of the upper logic that is the logic surounding multiple components, is there a more direct, less heavy, and natural way to forwards states and requests for actions back up to the parent?

7) Not shure about `this.$emit('click',this); `
- if one could put something else as the first 'this' (such as parent pointe for emitting directly to the parent pointer)
- if should include the 'this' in its parameter

8) Not shure why `props:` or `on:` would need to be declared in f if tx2 declares them anyway (such feature not used in the present example)

Here are the links about 2 forum topics.
https://forum.vuejs.org/t/emit-through-a-functional-component/5851
https://forum.vuejs.org/t/functional-components-in-a-vue/5236/8

Use case:
I am trying to design a data driven templating system that will select what component type to instanciate. (that I could share with the community)
Lower components will encapsulate some details, but as in the case of a multi-attribute document (such as First Name, Last Name, Address, Phone), the upper component (the form) will be the place where the logic specific to the whole will be (such as new record, edit, post, etc.)

I really hope for being able to use Functional components.
Thanks,

Marc

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
When you bind click event to a functional component like
```html
<f @click="addOne">tx1</f>
```
The event is bound to the functional component itself, and not implicitly to any other component it may render.
The event handler is available on `context.data.on.click`, and you'll have to bind it to other components inside `f`'s render function.

```js
render (createElement, context) {
   return createElement('tx2', {on: {click: context.data.on.click}})
}
```

with jsx and destructuring it would be much easier to read:
```
render (h, {data}) {
  return <Tx2 onClick={data.on.click}/>
}
```

And don't forget to check for `context.data.on` because it maybe undefined.

**Comment by MarcTe** [comment]
@fnlctrl Thanks for answer, but it does not work.

And it does not solve the access to context values.

`this.$slots.default` does not work.

Maybe a clearer doc is necessary. I read it many times (render and createElement) and it does not help.


Thanks,
Marc

**Comment by MarcTe** [comment]
@fnlctrl 

Even if I put "" `in {on: {"click": context.data.on.click}}` 
It sais `click `is not defined in tx2, even if I pu this method in tx2t: 

```
    click() {
      this.$emit('click', this);
    }
```
And even if there is already a click() in the app component.

Also, doc is not clear on how we pass a reactive parameter :something

Marc

**Comment by fnlctrl** [comment]
1.
> this.$slots.default does not work.
https://vuejs.org/v2/guide/render-function.html#Functional-Components

> Everything the component needs is passed through context, which is an object containing:
props: An object of the provided props
children: An array of the VNode children
slots: A function returning a slots object
data: The entire data object passed to the component
parent: A reference to the parent component'

2. context.data.on.click is registered by @click in the parent template
and also, 
 > In cases like this, we can mark components as functional, which means that they’re stateless (no data) and instanceless (no this context). A functional component looks like this:
So your use of `this` is invalid.

Please read the docs carefully.

**Comment by MarcTe** [comment]
Now it works with {on: {"click": context.data.on.click}} in the functional component AND still with <f @click="addOne">tx2</f> in the app.

1) Is it normal that we still need to include a @click in the app?

2) What about reading the context ? Is there something wrong  in the way I read context object? 
- The context object is not as expected;
- it is not beginning with { but with [ ;
- example: I cannot do:   var x=context.children.text; 
- JSON.stringify(context.children.text) is undefined;
- It seems not possible to directly access context variables.
- context.children does not contain  "tx2" in:  `<f @click="addOne">tx2</f>`

Marc
