### ISSUE TITLE
Weird behaviour with components data

### ISSUE THREAD

**Issue by Abusal7** [vuejs/vue#4852]
### Vue.js version
2.0.2

### Reproduction Link

https://jsfiddle.net/abusal7/8wa7dn9z/2/

### What is Expected?
When deleting a component the next component data will not get changed. 
 
### What is actually happening?
When deleting a component the next component data gets the deleted component data.

### Try This 

1. change the **row component: line4** Number to 5
2. delete **row component: line4** 

^ after trying this what happening is that **row component: line5**  Number is 5 !!!

**Comment by sqal** [comment]
You need to add `key` attribute to the row-component with unique value to help Vue identify those components.

More about `key`in the docs 
- https://vuejs.org/v2/api/#key
- https://vuejs.org/v2/guide/list.html#key

Fixed example - https://jsfiddle.net/stjfus1v/

**Comment by yyx990803** [comment]
Key is the proper solution to this - in the next version v-for components without keys will receive warnings.

**Comment by Abusal7** [comment]
Thank you @sqal, problem was fixed.
