### ISSUE TITLE
Not able to pass down properties to external template

### ISSUE THREAD

**Issue by JFusco** [vuejs/vue#4854]
Hello, what i'm trying to do is pass down properties to HTML that's defined via `template` tag:

**HomeComponent.vue**
```js
<template id="home-comp">
	<div class="home-message">
		<h1>{{message}}</h1>
		<span>my home message</span>
	</div>
</template>

<script type="text/babel">
	import Vue from 'vue'

	Vue.component('home-component', {
		template: '#home-comp',
		props: ['message']
	})
</script>
```

Then in my app view i register the component and add a message

**App.vue**
```js
<template>
	<div>
		<home-component message="testing a message"></home-component>
	</div>
</template>

<script type="text/babel">
	import homeComponent from './components/HomeComponent.vue'

	export default {
		components: {
			homeComponent
		}
	}
</script>
```

Results in the following error:
"Property or method "message" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option."

It seems pretty straight forward and not sure if this is a bug or if I'm doing something wrong. I checked the forum as well as did some Googling around and can't really find an answer.

Thanks!

**Comment by JFusco** [comment]
I found out that it does work with straight up javascript though

HomeComponent.js
```js
'use strict';

import Vue from 'vue';

export default Vue.component('home-component', {
	template: '<div>{{message}}</div>',
	props: ['message']
})
```

**Comment by yyx990803** [comment]
You don't need to give the template an id in vue files... They are already in the same file.

**Comment by JFusco** [comment]
```js
<template>
	<div class="home-message">
		<h1>{{message}}</h1>
		<span>my home message</span>
	</div>
</template>

<script type="text/babel">
	import Vue from 'vue'

	Vue.component('home-component', {
		props: ['message']
	})
</script>
```

Still results with the same error message.

**Comment by yyx990803** [comment]
You also need to export your component instead of registering it globally... Please read the docs for vue-loader.

**Comment by JFusco** [comment]
This worked, thanks for the tips and your hard work.
```js
<script type="text/babel">
	import Vue from 'vue'

	export default Vue.component('home-component', {
		props: ['message']
	})
</script>
```
