### ISSUE TITLE
`v-model` and `:type`

### ISSUE THREAD

**Issue by sellvana** [vuejs/vue#4858]
`:type` is not supported by `v-model`, but works with `:value` + `@input`.  

If it is just syntactic sugar, why the difference?

https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

Could there be issues with `<input :type="type" :value="value" @input="value = $event.target.value">` ?

**Comment by posva** [comment]
That syntactic sugar is for components, it's a bit more complicated for inputs. Basically, some listeners must be set up and different inputs behave differently. You can dig further here: https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js

**Comment by janga1997** [comment]
Has this been implemented?

**Comment by posva** [comment]
yes, `v-model` and dynamic types work now

**Comment by janga1997** [comment]
I didn't need it in the end anyway, since I only wanted to ensure number input for a field, and I realized there's `v-model.number` for that.
But good for future projects I suppose.
