### ISSUE TITLE
about v-for

### ISSUE THREAD

**Issue by display-b** [vuejs/vue#4861]
vue version:2.1.4
error:
    get undefined when used 'v-for'
  
![image](https://cloud.githubusercontent.com/assets/10875327/22634205/9533a654-ec62-11e6-813d-c9d49c492389.png)
![image](https://cloud.githubusercontent.com/assets/10875327/22634210/9e0f26ea-ec62-11e6-8800-416aaba0305d.png)

anybody for help?

**Comment by fnlctrl** [comment]
Please upgrade vue to the latest version. (2.1.10)
https://jsfiddle.net/fnlCtrl/t11vxeL9/

**Comment by display-b** [comment]
@fnlctrl 
thx!But i got the problem.
![image](https://cloud.githubusercontent.com/assets/10875327/22634651/ee8b9bcc-ec66-11e6-862b-dd6868d9adde.png)

**Comment by fnlctrl** [comment]
You'll have to install both `vue` and `vue-template-compiler` since they are now peer dependencies.
```
npm install --save-dev vue-template-compiler@2.1.10
npm install --save vue@2.1.10
``

**Comment by display-b** [comment]
@fnlctrl 
Ok~Thx
