### ISSUE TITLE
Not enough information in SSR error / stacktraces

### ISSUE THREAD

**Issue by jvandenaardweg** [vuejs/vue#4862]
### Vue.js version
2.1.10

### What is Expected?
An error/stracktrace that points me to the code/component that caused the real error.

### What is actually happening?
This morning i had an error during de server side rendering of my app. This resulted in the app not being available to everybody.

When started with SSR i already noticed the error reporting lacks some critical information as to where exactly errors happen. 

This is my current error handling during renderStream, almost the same as the hackernews 2.0 example because i used that example as my boilerplate:

```javascript
renderStream.on('error', err => {
  // 404 error
  if (err && err.code === '404') {
    if (isProd) {
      var errorMessage = new Error(`404 during renderStream: ${req.url}`)
      opbeat.captureError(errorMessage)
    }
    res.status(404).end('404 | Page Not Found')
    return
  } else {
    // Render Error Page or Redirect
    if (isProd) {
      var errorMessage = new Error(`Error during renderStream: ${req.url}. ${err}`)
      var errorMessage2 = new Error(err)
      opbeat.captureError(errorMessage2)
    }
    // console.error(errorMessage)
    res.status(500).end('Internal Error 500')
  }
})
```

I use opbeat to track errors in my app and get nofications about them as soon as they happen.

This morning, it resulted in this error: 
`Error: TypeError: Cannot read property 'path' of undefined`
With no hints to look for where this happend in my code/components.

The stacktrace provided only points me to *node_modules/vue-server-renderer/build.js* (see attached screenshot) and there it ends. Which seems not the root of the problem, just where the error gets passed on to my server.js.

<img width="942" alt="screen shot 2017-02-06 at 09 07 47" src="https://cloud.githubusercontent.com/assets/5155373/22638997/15bbcc6e-ec4c-11e6-838d-421ac33f5a33.png">

It would be really great if there's a better error stacktrace for SSR apps or somebody here knowing how to proper debug this. Unfortunately these errors just don't help enough :(

**Comment by jvandenaardweg** [comment]
Probably related to this: https://github.com/vuejs/vue/issues/4376

**Comment by posva** [comment]
@jvandenaardweg Yes, it is and it's on the roadmap. It'll be out in the near future 🙂 
Closing in favour of that issue
