### ISSUE TITLE
<select v-model="arr" v-bind:multiple="multiple">

### ISSUE THREAD

**Issue by iamzhangjinpeng** [vuejs/vue#4864]
### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/myuvgsj8/

### What is actually happening?
Error:
VM281 vue.js:525 [Vue warn]: <select multiple v-model="arr"> expects an Array value for its binding, but got String 
(found in root instance)

**Comment by posva** [comment]
Thanks. It looks like a bug. I'm looking into it.

**Comment by posva** [comment]
It has been fixed already in the dev branch https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js#L138
