### ISSUE TITLE
Post and get

### ISSUE THREAD

**Issue by GoshanFloyd** [vuejs/vue#4865]
Where i can find guide to get and post method on Vue.js?

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Interesting read: https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.lhtb9hi6q

tldr: use axios or fetch
