### ISSUE TITLE
md-button takes a while to make a table responsive

### ISSUE THREAD

**Issue by mzupancic19** [vuejs/vue#4867]
I've got table with 100 cells in my table. 

Table example: 
`<md-table-row  v-for="(row, index) in filter.rows" :key="index" :md-item="row">
            <md-table-cell class="center-content">
              <md-switch v-model="row.status" class="md-warn"></md-switch>
              <md-button v-on:click="removeRow(index)" class="dark-gray"><md-icon class="dark-gray">delete_forever</md-icon></md-button>
            </md-table-cell>
          </md-table-row>`

Remove row method:
`removeRow: function (index) {
            this.filter.rows.splice(index, 1);
        }`

When I use `md-button`, table loading is slow. Table is not responsive when I hover the rows, it takes approximately 4-5 sec until I can see that colors are changing when I hover them. But when I use a regular `button` instead, it takes less then 1 sec.

**Comment by yyx990803** [comment]
This is a problem in the UI lib you are using, not Vue core.
