### ISSUE TITLE
Server-side rendering and native html incompatibility issues

### ISSUE THREAD

**Issue by surmon-china** [vuejs/vue#4868]
When I use nuxt.js for server-side rendering,
I will encounter the following two issues, it now appears that these two issues are caused by vue.js:

1: I used the swiper component in the project. Since this component depends on the window object, I used the process.BROWSER_BUILD object judgment in nuxt.js to render the component only on the server side. When the page loads, the component renders correctly , The correct rendering, view the source code, you can see the corresponding swiper component code is not compiled before the component call code, such as: <swiper> ... </ swiper>, then the console by vue.js abnormal

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. And performing full client-side render.

This should not have existed

2: When I use the datalist element in html5 in a project, vue also throws an error like the one above

So I think, vue on the original html tags may not be sufficient to judge the rich, while rendering for the server, some judge is not perfect

Can there be improvements, or temporary solutions? Thank you!

**Comment by yyx990803** [comment]
For (1), it's generally difficult to work with 3rd party components that have hard-coupling with the DOM if you are using SSR. If something is designed without SSR in mind we can't magically make it work well with SSR.

For (2), please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by posva** [comment]
I think you're looking for this: https://vuejs.org/v2/api/#ignoredElements to ignore the swiper component but I'm not sure to understand the problem. The warning makes sense if you changes what the server renders and what the browser renders. It looks more of a question

**Comment by surmon-china** [comment]
@yyx990803 
@posva 
thanks! 

I think I will improve the swiper component, so that he is more suitable for ssr work.

**Comment by Super-Meng** [comment]
@surmon-china 现在项目情况如何呢. 正采用swiper和ssr遇上了这个的问题--!

**Comment by surmon-china** [comment]
@Super-Meng 勿抽象为组件，而是直接dom，按照官方的实例去使用，在mounted时实例化对象，销毁时释放

**Comment by posva** [comment]
Closing for (repro) inactivity

**Comment by funkyLover** [comment]
@surmon-china I find a tricky way to use external 3rd vue component when use nuxt.js for server-side rendering. already test `vue-awesome-swiper` too!

follow the [nuxt.js doc](https://nuxtjs.org/faq/window-document-undefined) and modify the your project config.

and then just use the component
``` js
if (process.BROWSER_BUILD) {
  var { swiper, swiperSlide } = require('vue-awesome-swiper')
}

// ...
components: {
  // if you just set 
  // swiper: swiper,
  // swiperSlide: swiperSlide
  // you will get an error: 
  // The client-side rendered virtual DOM tree is not matching server-rendered content.
  // you need to use the async component(https://vuejs.org/v2/guide/components.html#Async-Components)
  swiper: () => Promise.resolve(swiper),
  swiperSlide: () => Promise.resolve(swiperSlide)
}
// ...
```

however, it is always the best choice to improve the component itself.

@yyx990803 is this solution too hack? or just a `bug` way usage?

**Comment by surmon-china** [comment]
@funkyLover https://github.com/surmon-china/vue-awesome-swiper#use-in-ssr

**Comment by funkyLover** [comment]
@surmon-china I know you have already update `vue-awesome-swiper`, what I say is that the trick I post above can make custom component can fit SSR without any modification to component itself.
