### ISSUE TITLE
How to create Unit test with slots? 

### ISSUE THREAD

**Issue by iCaio** [vuejs/vue#4870]
```
describe('FixedHeader.vue', () => {
  it('should render correct contents', () => {
    const vm = new Vue({
      el: document.createElement('div'),
      render: (h) => h(FixedHeader)
    })
    expect(vm.$el.querySelector('.moip-slogan h2').textContent).to.equal('Moip')
  })
})
```

Hi, my component `FixedHeader` has one `slot`, how do I insert a HTML element in this slot on my test? 

I am using the Webpack template with Karma.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

Slot content is just children elements: `h(FixedHeader, [ /* children here */ ])`

**Comment by iCaio** [comment]
Thanks and sorry
