### ISSUE TITLE
[Vue warn]: Error when evaluating expression "function 

### ISSUE THREAD

**Issue by stop2stare** [vuejs/vue#4873]
Hello, everyone.
Just like the title said. When I tried to jump from `#!/a` to `#!/b`, Vue print a warn on the console.
```
[Vue warn]: Error when evaluating expression "function 
aid() {
      return this.tab.aid ? 0 : this.tab.aid;
    }": TypeError: Cannot read property 'tab' of null
```
`aid` is a *computed* value, and it may not belong to nor `#!/a` or `#!/b`, for example, it may be a value in page `#!/c`.
I was puzzled and couldn't figure out what's been going on. How could `this` be `null`?

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!
This should be opened in the vue-router repository, so I'll close this issue and let you open a new one there. But this time please, **provide a repro**
