### ISSUE TITLE
Passing or Accessing parent elements for index or key in child component

### ISSUE THREAD

**Issue by pulkitnandan** [vuejs/vue#4875]
Simple template like

OS.vue
```
 <div class="card card-item" v-for="(product, index) in products" :key="index">
              <delivery-mode v-bind:delModeIndex="index"></delivery-mode>
</div>
```
DM.vue
```
<template>
 <input type="radio" v-bind:name="'dmode' + delModeIndex">
</template>
export default {
    props: ['delModeIndex'],
}
```
This is giving [Vue warn]: Error when rendering component <delivery-mode> at /home/rohitn/unistore/components/DeliveryMode.vue: 
warn @ vue.runtime.common.js:521
vue.runtime.common.js:435TypeError: Cannot read property 'delModeIndex' of undefined

I think passing index or key attribute of for is completely skipped in documentation.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a reproduction repo on github. Thanks!

**Comment by LinusBorg** [comment]
`v-bind:delModeIndex`

You use CamleCase here, but props in templates have to be written in kebap-casel, as explained in the docs.

`v-bind:del-mode-index`
