### ISSUE TITLE
Warning when overriding native directives?

### ISSUE THREAD

**Issue by texelate** [vuejs/vue#4876]
In Vue 1.0 with `.config.debug` set to `true` I just spent ages trying to find out why `v-html` was causing errors and finally realised it was because I had a custom directive v-html for a WYSIWYG editor.

Would it be a good idea to issue a warning when this happens?

Thanks. 

Amazing work, by the way. I _love_ Vue!

**Comment by gebilaoxiong** [comment]
@yyx990803 
Can I submit a PR?

When the constructor `directives ()` && `extend` is called and the time of initialization

Check whether the directive is a built-in directive

**Comment by yyx990803** [comment]
@gebilaoxiong the check should probably be done in `core/util/options` when merging options.

**Comment by gebilaoxiong** [comment]
@yyx990803 Yes, but this time options may be built-in options

**Comment by yyx990803** [comment]
@gebilaoxiong you can just import the built-in options and check during merge (also, only need to check child value)

**Comment by gebilaoxiong** [comment]
@yyx990803 understand, thank you very much .

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/pull/5328#issuecomment-291042541
