### ISSUE TITLE
Select UI and v-model only update after second click when model value is retrieved from prop

### ISSUE THREAD

**Issue by stephanmax** [vuejs/vue#4877]
Hi, and first of all thank you for this amazing project!

### Vue.js version
2.1.10 from https://unpkg.com/vue@2.1.10/

### Reproduction Link
https://jsfiddle.net/stephanmax/ut7hsbz7/6/

### Steps to reproduce
* Click on the `+` button and a new custom component will appear, where option `Test1` is pre-selected
* Select option `Test2` from the dropdown

### What is Expected?
I would expect the dropdown to change to `Test2` and the model to `test2`.

### What is actually happening?
Nothing. Try it a second time (choose `Test2` from the dropdown) and both UI and model change as expected.

Now my question is: Why do I have to click twice? Putting a watcher on the model of the select element (`facet`) reveals that the value is not changing, although I am choosing a different option.

My goal is to create a search interface where you can add/remove different filters.

**Comment by defcc** [comment]
Thanks @stephanmax , there should be an error reported in the devtools if you use the development mode (with https://unpkg.com/vue@2.1.10/dist/vue.js). 

For your issue, you could refer the doc here https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow. I updated the fiddle here https://jsfiddle.net/ut7hsbz7/9/

**Comment by stephanmax** [comment]
Facepalm. Thanks a million for your rapid reply, @defcc!
