### ISSUE TITLE
v-if is not updating

### ISSUE THREAD

**Issue by huzjakd** [vuejs/vue#4878]
Why is this one not working: http://jsfiddle.net/asx9eh6b/

And this one is working: http://jsfiddle.net/ax3o95h9/

I need the first one to work i.e. v-if needs to get updated and the div displayed when the checkbox is checked.

**Comment by Austio** [comment]
Setting array by [] is not reactive use arr.$set(index, value)

https://vuejs.org/2016/02/06/common-gotchas/
