### ISSUE TITLE
Interpolate CSS in .vue components?

### ISSUE THREAD

**Issue by zoomclub** [vuejs/vue#4879]
Until now I had always thought that the CSS section in a .vue component remains static after the component is mounted. To enhance this I was thinking of using CSS Variables and then I ran across this recent fiddle by @yyx990803. The feature looks awesome and just what I was hoping for but dragging the slider does nothing.

http://fiddle.jshell.net/yyx990803/B5JTg/

Being able to interpolate state in both the template and the style layers of a component makes good sense. I had just never heard of this feature in the guide, can it be confirmed and added?

**Comment by posva** [comment]
It's not an existing feature. You can come across a similar hack by using style tags to define inline css but the right way to do would be to define computed properties like this: http://jsfiddle.net/posva/r35xagt3/

**Comment by zoomclub** [comment]
@posva @yyx990803 Sorry to hear this, I really thought Vue had nailed it again. This will make the integration of the feature I had in mind for .vue components more difficult. 

The computed property approach does not anticipate more than changing a few values here and there so it is less powerful, scalable and more verbose than the interpolation solution, which to be honest looks much more like the kind of transparent reactivity Vue is all about.

**Comment by yyx990803** [comment]
That fiddle was using Vue 1.x - it's just a hack, I wouldn't suggest using that for production as it likely causes a re-calc of the stylesheet on every update. Vue files are a different story and the styles in them are indeed static.

**Comment by zoomclub** [comment]
Thanks for letting me know. Looks like components then only provide static CSS and optional style bindings that are additive only (not replaceable) . I'll start from that then I see that I can do 👍

**Comment by posva** [comment]
> The computed property approach does not anticipate more than changing a few values here and there so it is less powerful, scalable and more verbose than the interpolation solution

Using a computed is definitely a way to go since it adapts and scales perfectly. Think of it as dynamic CSS modules

**Comment by zoomclub** [comment]
Interesting, I'll consider this more in the next days 💯

**Comment by zoomclub** [comment]
@yyx990803 Just to be clear, you had mentioned "as it likely causes a re-calc of the stylesheet on every update", which was the situation with the interpolation hack. If I'm using standard CSS Variables I can expect normal one-on-one recalc behavior right? 

The goal for me at time is to tweak a grid, which would be defined in the style section of a .vue component. The kind of dynamic alteration of static CSS I'm after is well demonstrated here: https://googlechrome.github.io/samples/css-custom-properties/index.html

I just need a way to reach back into the CSS in the style section and it looks like CSS Variables are perfect for this. So I think the picture is complete again? It would be great to see some CSS recipes along these lines in the new upcoming Vue cookbook :1st_place_medal:
