### ISSUE TITLE
Using < in custom delimiters yields wrong compiled template

### ISSUE THREAD

**Issue by jingz** [vuejs/vue#4880]
### Vue.js version
2.1.10

### Reproduction Link

https://jsfiddle.net/mwmaaju6/

### Steps to reproduce
It seem that Vue parse the template strings improperly.
if you add a space before open delimiter. The rendering is correct.

try inside `<p> tag`
`<p> <% text %> </p>` 

### What is Expected?
correctly rendering

### What is actually happening?
improperly rendering, I seem to strip the next tags, in this case <textarea>

**Comment by posva** [comment]
Thanks, looks like a bug due to the delimiter starting with `<`

**Comment by defcc** [comment]
Thanks, this issue has been fixed via https://github.com/vuejs/vue/pull/4753. Not released yet.
