### ISSUE TITLE
Chaining multiple filters without spaces doesn't work

### ISSUE THREAD

**Issue by nervgh** [vuejs/vue#4881]
### Vue.js version
1.0.28

### Reproduction Link
https://jsfiddle.net/8L7f9u53/2/

### Steps to reproduce
1. Define few filters
2. Apply them each other

### What is Expected?
Pipelining (chaining) filters

### What is actually happening?
Only first filter executes

---
```html
<div id="mount-point">
  <p v-text="test|foo"></p>      <!-- string.foo -->
  <p v-text="test|bar"></p>      <!-- string.bar -->
  <p v-text="test|foo|bar"></p>  <!-- string.foo but expected string.foo.bar -->
</div>
```
```js
Vue.filter('foo', function(s) {
  return s + '.foo';
})
Vue.filter('bar', function(s) {
  return s + '.bar';
})

new Vue({
  el: '#mount-point',
  data: {
    test: 'string'
  }
})
```

**Comment by Kingwl** [comment]
https://jsfiddle.net/8L7f9u53/3/
please pipelining filters with space

**Comment by kazupon** [comment]
Hmm, there are not strictlify filter grammer spec in docs,  but I think pipelining filters with space is good human readable coding design.
http://v1.vuejs.org/guide/custom-filter.html
