### ISSUE TITLE
Watch doesn't seem to fire when using `v-model`

### ISSUE THREAD

**Issue by garygreen** [vuejs/vue#4883]
### Vue.js version
2.0.2

### Reproduction Link
https://jsfiddle.net/pesg7zpb/

### What is Expected?

If you change the name in the field, it should fire the watch method and log to the console.

### What is actually happening?

It shows "Changed name" once, for the initial load, and then doesn't fire again when updating the input box.

**Comment by posva** [comment]
You should check the docs: https://vuejs.org/v2/api/#vm-watch
You probably want to do this: https://jsfiddle.net/posva/skanfpga/

**Comment by garygreen** [comment]
@posva thanks for the example, it was a simplified example I am actually trying to watch an array for changes, so I thought I could globally watch as per the example in the docs... how come it doesn't fire that function?

**Comment by posva** [comment]
Please, ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

There's no _global_ watch you need to

> Watch an expression or a computed function (reference `this.name`) on the Vue instance for changes

You should check https://vuejs.org/v2/guide/list.html#Caveats for arrays

The search is excellent, so you should be able to find what you need without even going to the forums
