### ISSUE TITLE
Feature request: transition-group provide hook when all children moves are finished 

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#4885]
Hi,
This will allow more control on transitions. My use-case is a transition in two steps :
`giving an array model like [1, 2, 3]`

1
2
3

**1.  that reorder elements (`[2, 3, 1]`) with move transition**

2
3
1

**2.  that remove elements (`[2]`)**
2
<- 3
<- 1
 
If I had a hook I will be firing the second step after 1 has finished moving. Instead, as a workaround, I'm firing it after a timeout.

https://github.com/vuejs/vue/blob/ae93d2bef8e20402ae3501aa5cdcf14b0ee19c12/src/platforms/web/runtime/components/transition-group.js
Looking at the sources, it seems to be pretty trivial to implement, since moving is all about setting and remove class. We could fire an event after all transitionend events are finished. Could provide a PR if accepted.

Thanks

**Comment by Kingwl** [comment]
#3974

**Comment by yyx990803** [comment]
see https://github.com/vuejs/vue/issues/3974#issuecomment-316372415
