### ISSUE TITLE
关于$root使用问题

### ISSUE THREAD

**Issue by LeungKaMing** [vuejs/vue#4889]
### Vue.js version
2.0.2

### What is Expected?
尤大您好，求教下我在根组件写了一个方法showloading，我在子组件里面用this.$root.showloading()并不能访问，但是翻阅2.0文档的api发现还在，而用this.$parent.showloading()则可以访问。在控制台打印$root，发现我写在根组件的方法都不在里面，所以得出结论是$root不能用了？
### Code
根组件
···
// template
<div>
  <child></child>
</div>
...
// js
export default {
  ... ,
  methods: {
    showloading: function () {
      console.log('I am loading')
    }
  }
}
···

子组件
···
// template
<div>I am child.</div>
...
// js
export default {
  ... ,
  created () {
    this.$root.showloading()
  }
}
···

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).


---

The root is the top most Vue (or extended) instance. If you used the official webpack template, it's the `new Vue`. That's where methods have to be added
