### ISSUE TITLE
filters and v-if

### ISSUE THREAD

**Issue by ram-you** [vuejs/vue#4891]
Have filter that returns Boolean depends on value. Doesn't work in v-if.
`
v-if="value | filterName"
`

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---


Filters can only be used in mustache bindings and v-bind: https://vuejs.org/v2/guide/syntax.html#Filters

**Comment by ram-you** [comment]
@posva It wasn't a question. It can be a request or a suggestion, because it will be very interesting if we can evaluate a value in v-if or in v-show in dependence of filters.
Otherwise, thank you for response.

**Comment by yyx990803** [comment]
This is by design. Filters are only meant for formatting text. Other types of logic should either be a computed property or a method call.
