### ISSUE TITLE
two v-if nodes' removal and interpolation changed the dom elements between the two v-if nodes.

### ISSUE THREAD

**Issue by shawtung** [vuejs/vue#4893]
### Vue.js version
2.1.10
//cdn.bootcss.com/vue/2.1.10/vue.js

### Reproduction Link
[github] https://shawtung.github.io/me/v-if_bug.html
[jsfiddle] http://jsfiddle.net/shawtung/ta03ny63/
They are the same.

### Steps to reproduce
No more steps are needed. Nine spans with different but ordinal ids and texts reside directly in the root element 'div#vue', with two divs mixed within, whose existence are determined by parameter 'state'. At first nine spans are assigned to nine corresponding variables and printed (id and textContent, both on the screen and in the console) sequentially. Then I change 'state', which leads to the first v-if div to be removed, and the second interpolated. After that I re-print the nine spans as like before. But this time the printed content between the two v-if divs are reversed, that is, the intermediate part of the span sequence has been changed unexpectedly.

In the example I provide, elements four five six become six five four. Since id and textContent are swapped, I infer that the elements' all other attributes will also be swapped. The new nodes seem totally the same to the old ones while their referencing variables and positions in dom tree show that they have been changed.

But when I change one of the intermediate tags from span to any other type, the result become correct. It seems only consecutive and same tags between two v-if nodes (of which the first is removed and the second is simultaneously interpolated and vice versa) will reproduce this bug. 

### What is Expected?
The intermediate part shouldn't be in wrong order.

### What is actually happening?
Maybe there's something wrong with the dom updating or rendering.

ps:
I'm just a noob in Vue and Web frontend (and MD). Your attention and response will be much appreciated! Thanks in advance!

**Comment by fnlctrl** [comment]
It's because your reference to the elements are outdated, and they have been modified by vue's virtual dom diffing algorithms. You'll have to use `document.getElementById()` to get updated references of the elements.

http://jsfiddle.net/fnlCtrl/qdL7cmgu/

**Comment by shawtung** [comment]
@fnlctrl 水平有限不太能理解，为啥这个virtual dom diffing算法会把顺序颠倒一下？是有意这样设计的么？而且我发现如果用一个div把这几个东西包起来就ok了，这意味着这个算法只把sibling elements纳入考虑？

**Comment by fnlctrl** [comment]
关于内部实现的问题，请自己阅读源码，或者使用论坛/stackoverflow/gitter提问。
