### ISSUE TITLE
How to use helper functions for imported modules in vuejs .vue template?

### ISSUE THREAD

**Issue by rlightner** [vuejs/vue#4895]
I have a helper.js file with contains:
```javascript
module.exports = {
    getSrmColor: (color) => {
        return color;
    }
}
```
My .vue file has:
```vue
<template>
<div>
{{ recipeHelper.getSrmColor(recipe.color) }}
</div>
</template>
<script>
import recipeHelper from "./helpers.js";
export default {
        name: "Recipe",
        props: ["recipe"]
    }
</script>
```

I get the following error:
```
Property or method "recipeHelper" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by aelmariya** [comment]
jjjjjjjjjjjjjjjjjjjj
