### ISSUE TITLE
how to Import Files .css and .js global

### ISSUE THREAD

**Issue by israeleriston** [vuejs/vue#4898]
### Vue.js version
2.0.2

**Comment by znck** [comment]
Your issue seems usage/support question. If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.

**Comment by israeleriston** [comment]
Im Sorry
