### ISSUE TITLE
[Feature Request] Allow directly setting the slot scope

### ISSUE THREAD

**Issue by bundyo** [vuejs/vue#4903]
Currently we can set properties in the scope, by assigning them to slot attributes, like this:

```html
<my-awesome-list :items="items">
  <template scope="props">
    <li class="my-fancy-item">{{ props.item.text }}</li>
  </template>
</my-awesome-list>
```

```html
<ul>
  <slot name="item"
    v-for="item in items"
    :item="item">
  </slot>
</ul>
```

However, sometimes (when all our data is in the item) it may be more useful to directly set the scope and avoiding having to use special property for the item data or to have to define the properties separately. For instance one way this can be done is if the attribute name is the same as the scope name - something like this:

```html
<my-awesome-list :items="items">
  <template scope="props">
    <li class="my-fancy-item">{{ props.text }}</li>
  </template>
</my-awesome-list>
```

```html
<ul>
  <slot name="item"
    v-for="item in items"
    :props="item">
  </slot>
</ul>
```

Let me know if you need a better description.

**Comment by LinusBorg** [comment]
You can use destructuring: 
`scope="{ item}"`

**Comment by bundyo** [comment]
Nice, but some documentation would be nicer :)
