### ISSUE TITLE
Component navigation guard before route enter next not called?

### ISSUE THREAD

**Issue by nexflo** [vuejs/vue#4905]
beforeRouteEnter (to, from, next) {
Console.log("route1");
  next(vm => {
    // access to component instance via `vm`
Console.log("route2");
  })
}

Route1 logs, route2 never gets logged. 
This happens inside components navigation guards

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. When the reproduction is ready, please open an issue at [vue-router](https://github.com/vuejs/vue-router)'s repo instead. Thanks!
