### ISSUE TITLE
Object reactivity caveat?

### ISSUE THREAD

**Issue by cloud-tribal** [vuejs/vue#4912]
[Caveats](https://vuejs.org/v2/guide/list.html#Caveats)

> Due to limitations in JavaScript, Vue cannot detect the following changes to an array (...)

Is this the case for objects as well?

This fails:

`state.sportType.sports[keyToAdd] = {...sportPrototype}`

where `sports` is an object; and this passes:

`Vue.set(state.sportType.sports, sportsLength, keyToAdd)`

**Comment by andreiglingeanu** [comment]
Yes, that's the case for objects as well. Whenever you add new properties to objects you should use `Vue.set`.

**Comment by posva** [comment]
As @andreiglingeanu pointed out, yes. Next time, please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). The issues are for bugs and feature requests only

**Comment by cloud-tribal** [comment]
Posted this here to specify that it should probably be updated in the List Rendering docs, which mention this caveat for arrays only. (Despite it being mentioned in Reactivity)

**Comment by yyx990803** [comment]
Array indices and Object properties are not the same thing.

**Comment by LinusBorg** [comment]
Yeah, it's not really the same thing.

* For arrays, `array[index] = 'something'` can **never** be detected.
* For objects, `object['key'] = 'something'` can be detected for *existing* properties - it's only a problem when trying to *add* new props this way (for which we have to use `Vue.set()`)
