### ISSUE TITLE
router.replace doesn't work as expected in some android webiews

### ISSUE THREAD

**Issue by rayanywhere** [vuejs/vue#4917]
### Vue.js version
all versions

### What is actually happening?
implementation of router.replace is relying on window.location.replace function, which has buggy in some android system.  For more detail, please refer to http://stackoverflow.com/a/34523390.

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!

--------------

`router.replace` can work either with `location.replace` in `hash` mode or `history.replaceState` in `histroy` mode. If none works properly in your target environment then there's nothing we can do to help.
