### ISSUE TITLE
v-model input[type=email] bug on Chrome when entering cyrrilic symbols

### ISSUE THREAD

**Issue by PavloAndriiesh** [vuejs/vue#4920]
Hi. I experienced some kind of bug when trying to fill input[type=email] field with latin and cyrrilic symbols. 
When type is text - bug is not reproducing. Also bug is not reproducing in Opera or Edge. Only Chrome and type=email. 
On entering cyrrilic symbols somewhere between latin - some strange text inserts into model.

### Vue.js version
2.1.0

### Reproduction Link
[http://codepen.io/Pablontus/pen/YNddEz](http://codepen.io/Pablontus/pen/YNddEz)

### Steps to reproduce
Open Chrome latest stable version. 
1. Attach v-model to input field.
2. Set input field type to email.
3. Try to type any cyrrilic symbol somewhere after "@" between latin letters. 

### What is Expected?
Expected that model is updated correctly with symbol entered.

### What is actually happening?
Some strange text inserted into model instead of real cyrrilic symbols. For example: "Ф" => "xn--t1a"

**Comment by posva** [comment]
It seems to be a Chrome issue unrelated to Vue: http://codepen.io/posva/pen/vgvbOX?editors=1111
Notice how clicking on get value the first time works but after updating the input, the string changes. An email with unicode is the domain is not valid anyway, that's probably why chrome is changing the value: http://stackoverflow.com/questions/3844431/are-email-addresses-allowed-to-contain-non-alphanumeric-characters

You should lookup on the chromium bug tracker

**Comment by PavloAndriiesh** [comment]
Great, thanks!
