### ISSUE TITLE
关于vue ssr 生命周期内异步获取数据无法渲染的问题 

### ISSUE THREAD

**Issue by shaoxiong789** [vuejs/vue#4922]
vue2.0服务端渲染，在created方法中用axios httpclient 功能调后台接口，created方法在服务端渲染生命周期内，但是在axios 回掉函数获取数据前，服务端已经渲染结束。能否让开发人员自己控制渲染的生命周期什么时候结束。

**Comment by yyx990803** [comment]
ssr 数据抓取需要特殊处理，参见 https://github.com/vuejs/vue-hackernews-2.0/
