### ISSUE TITLE
Asynchronous Data re-render

### ISSUE THREAD

**Issue by Thstone37** [vuejs/vue#4927]
I change datas by ajax,and return right data!I use **updated()** hook.but dom data not change!

![image](https://cloud.githubusercontent.com/assets/11756943/22911928/81e71da6-f29d-11e6-871f-daeff6d6fcd6.png)

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

Thanks!
