### ISSUE TITLE
Transition component removes all of the assigned classes except the last one

### ISSUE THREAD

**Issue by n3gotium** [vuejs/vue#4931]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/pg0pfzkb/

### Steps to reproduce
In order to reproduce this issue you should assign a multiple classes to the element which is wrapped by the transition component. One of the assigned classes must be equal to the value of the transition component's name property.

### What is Expected?
When transition ends, all of the assigned classes should remain.

### What is actually happening?
When tranisition ends, only the last assigned class remains.

**Comment by LinusBorg** [comment]
Hi,

you use a string with a space / multiple class names as a name for a transition. That is not supported.

**Comment by n3gotium** [comment]
Oh, sorry. I missed this. Thank you for your quick reply!
