### ISSUE TITLE
vue2.1.10 Cannot read property 'text' of undefined 

### ISSUE THREAD

**Issue by wgq837051** [vuejs/vue#4935]
### Vue.js version
2.1.10 

build vue2.1.10 project by vue-cli  , when npm run dev , 
![text](https://cloud.githubusercontent.com/assets/6071212/22964801/62b9a8a6-f395-11e6-9c71-988d7053d4a8.png)

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!


------------------------------
Check if the object you're accessing exists, if not, declare a default value in the `data` option.
