### ISSUE TITLE
vuejs+vuex最新版本写的h5系统，在安卓UC浏览器显示空白，

### ISSUE THREAD

**Issue by chenpengjun** [vuejs/vue#4938]
错误信息如下：
Use of const in strict mode;
Cannot call method 'call' of undefined

### Vue.js version
2.0.2

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
