### ISSUE TITLE
document.createEvent()

### ISSUE THREAD

**Issue by jackPanyj** [vuejs/vue#4939]
when i see the vue.js, i find some api that is deprecated, is that because need to be compatibled with IE?

this is the link from MDN [Document.createEvent()](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent)

``` js
function trigger (el, type) {
  var e = document.createEvent('HTMLEvents');
  e.initEvent(type, true, true);
  el.dispatchEvent(e);
}

```

**Comment by yyx990803** [comment]
CustomEvent API is not supported in the entire IE line.
