### ISSUE TITLE
Feature request: fallback for unresolved components

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#4941]
I try to create a plugin that can handle component declaration with a specific format:
```
  ...
  components: {
    myComponent: 'url:<URL_OF_THE_COMPONENT>',
    ...
```

Currently, `function createComponent() in vue.js`, can only support `function` else it fails with `"Invalid Component definition: ..."`.
Is it possible to have a hook or a fallback that can be defined in a plugin definition ?
Or maybe a generic way for resolving assets from a plugin ?

**Comment by posva** [comment]
Hello!
I'm not sure to understand the issue you're facing to ask for this feature, you can already handle the custom components with a mixin: http://jsfiddle.net/posva/1h4cq7a3/

**Comment by FranckFreiburger** [comment]
Hello posva, thanks for your reply.
I know that it is possible to create a global mixin that can transform any component in the beforeCreate hook. This implies to iterate through all sub-components declaration at each component creation.
I was wondering if it was possible to have a more elegant mechanism to do this.

**Comment by posva** [comment]
I find the mixin solution quite elegant and extremely flexible solution tbh.
What is your use case?

**Comment by FranckFreiburger** [comment]
I try to create a plugin that can load components whose name start with 'url:' through an httprequest.
I already have version that work properly using Vue.mixin() and beforeCreate hook.
The only thing that bothers me is having to process the of sub-components at each component creation.

**Comment by posva** [comment]
and what is your plugin's usecase?

**Comment by FranckFreiburger** [comment]
for example:

```
Vue.use(httpVueLoader);

...
components: {
  foo: 'url:foo.vue',
  bar: 'url:http://...'
}
```

see: [httpVueLoader plugin](https://github.com/FranckFreiburger/http-vue-loader)

**Comment by posva** [comment]
I meant why do you need to use that plugin?
I can see it useful for testing isolated components (can load components from a lib using unpkg) in which case there's no need for anything new. If you're trying to achieve code splitting, there're better ways: https://vuejs.org/v2/guide/components.html#Async-Components

**Comment by FranckFreiburger** [comment]
My plugin already use async-components:

1. http request the vue file
2. load the vue file in a document fragment
3. process each section (template, script and style)
4. return a promise to Vue (async components)

**Comment by posva** [comment]
I'm sorry but I don't see what your plugin is missing to work with `url:foo`...
As a side note, I really think it's better to use it as it is now: it much more explicit

**Comment by FranckFreiburger** [comment]
Ok, thanks !
