### ISSUE TITLE
Input field focus is killed on list reordering

### ISSUE THREAD

**Issue by matrunchyk** [vuejs/vue#4942]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/qLm86j4n/

### Steps to reproduce
Open the link, and try to remove "20" from the first input.

### What is Expected?
It's expected that this list will be reordered without killing a focus on the current input.

### What is actually happening?
It's reordering, but it kills the focus.
The problem is only happening when the input moves up. When you open the link again and add "0" the the second input (it should be "150"), the focus will not be killed.

---
This is another way to check: https://jsfiddle.net/odjc8sqf/

STR:
1. Open link
2. Click on 1st input field
3. Press "Down" key on your keyboard. It decreases a current number by "10" so the list will be reordered and the field will be moved down. And it *kills the focus*.

Thank you!

**Comment by posva** [comment]
unfortunately, this is a normal behaviour: the element is removed from the dom to reinsert it so the focus is lost.
You can easily work around it, though: https://jsfiddle.net/posva/nfgdaxx6/

**Comment by matrunchyk** [comment]
@posva thank you, but why the focus is not lost when it's moving down?

**Comment by posva** [comment]
because I'm refocusing it

**Comment by matrunchyk** [comment]
I mean in my example. https://jsfiddle.net/qLm86j4n/

> When you open the link again and add "0" the the second input (it should be "150"), the focus will not be killed.

**Comment by posva** [comment]
oh, that's because the one being moved is the first input. The second input in the dom remains the same

**Comment by matrunchyk** [comment]
So this is the thing — why the one is just reordered and isn't removed from DOM, and another one is removed from DOM?

Docs say the following:
`To give Vue a hint so that it can track each node's identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item.`

> reorder *existing* elements.

**Comment by posva** [comment]
it's an optimisation: one is removed instead of two.

**Comment by matrunchyk** [comment]
Ok, wouldn't be nice to move (via `insertBefore`) a sibling instead of target element? It would avoid focus loss. Like here: https://jsfiddle.net/ffnjhk8y/

**Comment by posva** [comment]
It would have a cost in the patching for a very specific use case that can be easily _workarounded_, so not really.
