### ISSUE TITLE
Scoped style on SVG Path doesn't work

### ISSUE THREAD

**Issue by igor-ribeiro** [vuejs/vue#4943]
```vue
<template>
  <div class="container">
    <div class="box"></div>
    <svg>
        <path />
    </svg>
  </div>
</template>

<style scoped>
.container div {
  background: red /* works */
}

.container path {
  fill: red /* does not work */
}
</style>
```

If I remove the `scoped` it works.

**Comment by posva** [comment]
I tried it by creating a new project and it worked fine
<img width="299" alt="screen shot 2017-02-16 at 13 41 50" src="https://cloud.githubusercontent.com/assets/664177/23021728/bf375110-f44d-11e6-912f-3b9a91e04b69.png">

You would have to provide a repro. And make sure you open the issue on https://github.com/vuejs/vue-loader

**Comment by igor-ribeiro** [comment]
I know what it is... I'm using D3, so the `path` is inserted after Vue did it's job.

**Comment by igor-ribeiro** [comment]
Updated the title so it's more clear.

**Comment by posva** [comment]
https://github.com/vuejs/vue-loader/issues/559#issuecomment-271479195
