### ISSUE TITLE
Components instantiated with multiple `v-for`'s not destroying properly

### ISSUE THREAD

**Issue by blackfyre** [vuejs/vue#4944]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/gnick666/pb129j4c/

### Steps to reproduce
Instantiate components with more than one `v-for`, push the button.

### What is Expected?
The component should be destroyed once the one of the v-for source set has been modified.

### What is actually happening?
The component get re-used with the new data, but since it's not created again, the data property doesn't update, because create hasn't been run again.

### Steps to mitigate
You can watch the prop for change: https://jsfiddle.net/gnick666/pb129j4c/2/

**Comment by posva** [comment]
Hello! You're actually abusing the `created` hook here. It's not meant to be called for every component each time the v-for loop is called. In that simple example, a computed property would be the way to go. If you want to control which components are created/removed, you should use the `key` attr, although I wouldn't recommend it for this particular case (it's great for animations, for example)

**Comment by blackfyre** [comment]
The example is simplified. The actual use case includes input value setting with v-model, so the computed prop isn't really an option (to my knowledge).

**Comment by Akryum** [comment]
You can do computed setter:

```javascript
computed: {
  name: {
    get () { return something },
    set (value) { ... }
  }
}
```

**Comment by blackfyre** [comment]
I didn't know about that 😄 
Thanks for all the help!

**Comment by smolinari** [comment]
This may be asking for a lot. But, could you make a new JSFiddle with the solution?

Scott
