### ISSUE TITLE
Input value isn't updated after @submit event in Firefox

### ISSUE THREAD

**Issue by abdgad** [vuejs/vue#4947]
### Vue.js version
2.1.10 dev mode

### Reproduction Link
https://jsfiddle.net/djmt6gmn/

### Steps to reproduce
Just submit the form using Firefox 51.0.1 (64-bit).
It works fine in Google Chrome. I haven't tested this in other browsers.

### What is Expected?
hidden table input value to be updated before submitting the form.

### What is actually happening?
the form is submitted with table input value empty ''. It should contain JSON string of **this.table**

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a **minimal** JSFiddle containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by abdgad** [comment]
@posva done.

**Comment by posva** [comment]
That's working as expected: you're updating the `value` of the hidden input in the very same event as you submit, therefore the input is not updated until the nextTick: https://jsfiddle.net/posva/66qdey5e/

**Comment by abdgad** [comment]
@posva but it works find in Google Chrome. What solution do you suggest?

**Comment by marktopper** [comment]
This is not expected behaviour. Since it works differently in two modern browsers...
Please reopen this @posva

**Comment by posva** [comment]
@abdgad I'd probably forge the post request myself and send it instead of using a hidden input. You can use the method used in the Fiddle otherwise.

> This is not expected behaviour. Since it works differently in two modern browsers...

@marktopper It's a browser dependent behaviour, which is, sometimes, unreliable

**Comment by yyx990803** [comment]
1. The fiddle is not demonstrating working behavior in Chrome.
2. If browsers decide to fire `submit` event at different timings there's nothing Vue can do about it.
3. Easiest solution is simply make `tableJson` a computed property.
