### ISSUE TITLE
Dynamic slot name not working with scoped slots

### ISSUE THREAD

**Issue by stevendesu** [vuejs/vue#4951]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/jsv397us/

### Steps to reproduce
 1. Create a [scoped slot](https://vuejs.org/v2/guide/components.html#Scoped-Slots) using the `<template>` element, as is necessary
 2. Use [dynamic props](https://vuejs.org/v2/guide/components.html#Dynamic-Props) to set the `slot` property on the `<template>`
 3. Attempt to utilize this slot

### What is Expected?
The slot is loaded and display correctly

### What is actually happening?
Dynamic properties don't seem to work on the `<template>` component, so the "slot" property is getting set to null and it is not being loaded

By changing `<template>` to `<div>` the slot loads, but the scope stops working, throwing the error "Property or method "props" is not defined on the instance but referenced during render."

**Comment by yyx990803** [comment]
This has already been fixed in dev branch (e7083d0) and will be out in next release.
