### ISSUE TITLE
v-for, refs and access to refs.<array of components> by array index after Array.unshift

### ISSUE THREAD

**Issue by alekzonder** [vuejs/vue#4952]
here example: https://jsfiddle.net/alekzonder/1zcLkuwq/
vue.js 2.1.10

steps in example: 

1. press "unshift new" button
2. then press "set bold" with 0 index in input

problem: item with index 1 is bold after Array.unshift in data

if remove `:key=item.id` in template with v-for, all works right

bug or feature?

**Comment by Kingwl** [comment]
https://jsfiddle.net/z11fe07p/773/
a simple version

**Comment by alekzonder** [comment]
@Kingwl thanks for simple version!

i can iterate $refs.items and search component by data, but not sure this right way

**Comment by sqal** [comment]
@alekzonder I guess this PR https://github.com/vuejs/vue/pull/4807 will help you with your problem, but you have to wait until it comes out with the next reelease of Vue

**Comment by yyx990803** [comment]
Note that v-for refs do not guarantee the same order as your source Array.

In the next release you can determine how to register refs yourself by passing a function to `:ref`.

**Comment by ixcat** [comment]
Sorry to respond to a closed issue -

Is the list behavior documented anywhere?

I did not see in for example:

https://vuejs.org/v2/guide/list.html#key
https://vuejs.org/v2/guide/migration.html#v-for-Argument-Order-for-Objects-changed

Seems to snag others, occasionally, as seen here and in:
https://forum-archive.vuejs.org/topic/5190/this-refs-ref_name-on-dynamic-component-is-array-instead-of-vuecomponent/3

seems a quick note might be beneficial to save headaches..

thanks for a great framework either way :)

**Comment by feliperaul** [comment]
"Note that v-for refs do not guarantee the same order as your source Array"

Well this is a *huge* bummer.

**Comment by Fmajor** [comment]
In the document https://vuejs.org/v2/guide/components.html#Child-Component-Refs, it says

> **$refs** are only populated after the component has been rendered, and it is not reactive. 

But i really have the requirement for a dynamic ref in v-for

for the example @Kingwl https://jsfiddle.net/z11fe07p/773/, i found a solution https://jsfiddle.net/Fmajor/cuay7v1j/

just manually clear the old ref array to null, and it works

**Comment by feliperaul** [comment]
For the problem of $refs not being reactive, I'm using this.$nextTick(function () { }) and it works, I get an updated list of $refs.

But for the problem of v-for $refs returning an array that does NOT match the order of your source data, I had to code a hack using custom uids, and resetting those uids (0 indexed) just before trying to access $refs, and then filtering that array by that uid property.

**Comment by adamwathan** [comment]
Anyone come up with a solution they think is clean for this yet? It’s currently really hard to answer questions like “what is the bounding box of the element where item x in this array is being rendered?” since the refs array order is not synchronized with the data source order.

Best I’ve come up with is assigning a different unique ref name for each item in the list like `:ref=“‘option:’ + item.id”` but that’s really gross, especially considering I have to access that ref as element 0 of an array with only one item in it now since the ref is on a v-for.

Other solution I had was adding a `:data-key=“...”` attribute so I can find the ref I want by traversing all of them and looking for a match but man does it ever feel anti-Vue to be storing data in the DOM like that.

**Comment by atilkan** [comment]
@yyx990803 
Is there any update on this?

**Comment by trollfred** [comment]
fuck that was painful

**Comment by zijjj** [comment]
如果更新后的refs数组与源数据数组的顺序不一致，那么这个refs数组还有什么意义呢？
数组元素我们只能通过索引来查找，但是这时候顺序又不一致，那这不算是一个BUG吗？

**Comment by zijjj** [comment]
@yyx990803 
如果更新后的refs数组与源数据数组的顺序不一致，那么这个refs数组还有什么意义呢？
数组元素我们只能通过索引来查找，但是这时候顺序又不一致，那这不算是一个BUG吗？

**Comment by karljakober** [comment]
I needed to find a dom resource of the first element in a v-for using a dynamic component.
I solved this using lodash to find where :key was equal to 0, but I'm concerned about if the array gets huge.

`let index = _.findIndex(this.$refs.dataArray, function(ele) { return ele.$vnode.key == 0; });`
`this.$refs.dataArray[index].$el.offsetHeight;`

**Comment by fnlctrl** [comment]
@zijjj @karljakober 
The current behavior is to ensure better performance, otherwise we get the overhead of ensuring $ref array index every time render functions are called.

The correct approach to get the correct index is just as @adamawang proposed:
Bind index to dom as `:data-index="index"` and then access it via `parseInt(el.dataset.index)` when using `$refs`

**Comment by Anima-t3d** [comment]
https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

>When ref is used together with v-for, the ref you get will be an array containing the child components mirroring the data source.

I think this text is misleading as clearly it doesn't "mirror" the sequence.
Should be:
>When ref is used together with v-for, the ref you get will be an array containing the child components mirroring the data source. **But take note that v-for refs do not guarantee the same order as your source Array.**

**It took me a few hours to discover that the order in `$refs` was not guaranteed.**

For being complete these are the resources I went through to find this issue:
1. https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/core/vdom/modules/ref.js#L39 (discovered that the implementation is just pushing)
2. https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/test/unit/features/ref.spec.js (discovered that the spec only tests sequential DOM/data)
3. Found this thread when looking to report this issue
4. https://vuejs.org/v2/api/#ref (checked and doesn't mention this behaviour)
5. https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements (checked here and also doesn't mention anything, it even insinuates the opposite)

**Comment by thedamon** [comment]
Trying to scroll to a newly added element and trying to have reasonable performance...
would it be more performant to just grab the dom element based on a known data-attribute and scroll to that, or to create a ref and access the first element of its array to scroll to..?

both look fairly bad, but i think the ref approach maybe looks slightly less bad if we look past the `[0]`

**Comment by cihad** [comment]
I think the best way is that to write vue instance the object of iterating:

https://jsfiddle.net/cihad/2a9wyvbh/

**Comment by dexcell** [comment]
Really guys? It's already 2019 and still not fixed yet.
Wasted an hours figure this out. thought it was bug on my code.
Now i have to write ugly code like adamwathan suggested.

**Comment by mernst-github** [comment]
I'm late to this party but wouldn't the obvious fix be for vue to publish for-refs as an object keyed with the item :key instead of an array? vue already uses :key to identify the items, why shouldn't we?

**Comment by rightaway** [comment]
Is this code not guaranteed to work as expected (comes from https://forum.vuejs.org/t/better-method-of-using-refs-inside-a-v-for-based-on-object/21352/2)?

```vue
<list v-for="(item, key, index) in objectOfItems" :key="key">
  <q-popover ref="editor">
    <editor :item="item" @cancel="$refs.editor[index].close()">
```

Or is this code fine and this github issue is actually referring to a different problem?

**Comment by colefranz** [comment]
To anyone coming to this late, another potential workaround is to reorder your ref onto a parent and use it's children instead.

```js
<div ref="listParent">
    <div v-for="..." :key="key">
        <item />
    </div>
</div>
...
this.$refs.listParent.children[index];
```

But I'm not a huge fan of this loose coupling to the markup as adding another element to the `listParent` could result in unexpected defects to another developer coming into the component.

**Comment by quacainia** [comment]
It's not amazing, but if it works for anyone else who runs into this problem, I just made a method that does a lookup based on parameters:

```vue
<template>
  <div v-for="item in items" :key="item.key">
    <myitem :item="item" ref="items"></myitem>
  </div>
</template>

<script>
export default {
  methods: {
    refItem(item) {
      return this.$refs.items.find((refItem) => {
        return refItem.item.key === item.key;
      })
    },
    otherMethod(item) {
      this.refItem(item).doThing();
    }
  }
}
</script>
```

For me using it is relatively low incidence so it's not too expensive overall. I don't think this would be great if it was for every render.

**Comment by Drumstix42** [comment]
I went with this implementation for when there's a unique identifier for the iterated array/object. Does this make sense?

```
                <item-card
                    v-for="item in items"
                    v-bind:ref="`item_${load.id}`"
                    v-bind:key="item.id"
                    v-bind:item="item">
                </item-card>
```

**Comment by infinnie** [comment]
> It took me a few hours to discover that the order in $refs was not guaranteed.

So true.

**Comment by fuweichin** [comment]
It took me 40 minutes to discover and solve the order problem.

I solve it by using a helper function `syncArrayOrder`, which is defined and demonstrated below:

```vue
<template>
<ul>
  <li v-for="item of itemList" :key="item.id" data-id="item.id"><canvas ref="canvas"></canvas></li>
</ul>
</template>

<script>
export default {
  data(){
    return {
      itemList: []
    }
  },
  mounted(){
    this.itemList = [{id:'1'}, {id:'2'}];
    this.$nextTick(()=>{
      // let canvasArray = this.$refs.canvas;
      let canvasArray = syncArrayOrder(this.$refs.canvas, (elem)=>elem.parentNode.dataset.id, this.itemList, (item) => item.id);
    })
  }
};

function syncArrayOrder(elemArray, idFunc, dataArray, keyFunc) {
  let map = new Map();
  for (let i = 0; i < elemArray.length; i++) {
    let elem = elemArray[i];
    map.set(idFunc(elem), elem);
  }
  return dataArray.map((item) => {
    let key = keyFunc(item);
    return map.get(key);
  });
}
</script>
```

**Comment by DazzRune** [comment]
> **It took me a few hours to discover that the order in `$refs` was not guaranteed.**
This is not a record... So now it's 2024

**Comment by Drumstix42** [comment]
Recommend using template Function Refs now in Vue 3: https://vuejs.org/guide/essentials/template-refs.html#function-refs
Also, the `useTemplateRef` as of Vue 3.5
