### ISSUE TITLE
绑定keyup事件，ctrl/shift/alt/meta按键修饰符不起作用

### ISSUE THREAD

**Issue by b1g3rr0r** [vuejs/vue#4955]
### Vue.js version
2.1.10

### Reproduction Link

http://jsfiddle.net/johnny0x00/hww0ohfk/

### Steps to reproduce
在input上绑定keyup，并使用ctrl(shift/alt/meta)按键修饰符，但是不起作用。但是按住ctrl键，再按其他按键，可以执行绑定的事件处理方法

### What is Expected?
按绑定的按键修饰符，执行绑定的事件处理方法

### What is actually happening?
ctrl、shift、alt、meta按键修饰符不起作用

**Comment by posva** [comment]
Hi, this is actually an expected behaviour: when you release the meta (or any other modifier) key, the keyup event triggers but the modifier key is not longer being pressed so the event is filtered out.

I think it's worth adding a note to the docs. I'll do that 🙂
