### ISSUE TITLE
__vue__ property leaked in DOM element, even in vue.min.js

### ISSUE THREAD

**Issue by andreiglingeanu** [vuejs/vue#4957]
### Vue.js version
dev branch

### Steps to reproduce
1. Open [this](https://github.com/vuejs/vue/blob/dev/dist/vue.min.js)
2. Search for `__vue__`

### What is Expected?

To not see any `__vue__` leaks onto the actual DOM element.

### What is actually happening?
Vue instance is stored inside `__vue__` onto the DOM element itself.

<hr>

Is this by purpose? I think the only usage for `__vue__` property is to make the instances discoverable by `vue-devtools`. Should that be present in minified build? I can come up with a pull request with a fix for that.

**Comment by yyx990803** [comment]
Minified build can still use the devtools when `Vue.config.devtools` is explicitly set to `true`. This is intended.

**Comment by andreiglingeanu** [comment]
This means that if I got some `__VUE_DEVTOOLS_GLOBAL_HOOK__` in my `window` object - devtools will walk through my _all_ DOM elements.

That's the same problem I got in #4958 - multiple Vue dependencies load on the same page.

**Comment by andreiglingeanu** [comment]
@yyx990803 Can we at least go about removing those `__vue__` properties based on an ENV variable, other than `NODE_ENV='production'`?

I'll be happy to build Vue by myself.

I really need it to be as closed from the outside world as possible.

**Comment by yyx990803** [comment]
Why?

**Comment by andreiglingeanu** [comment]
I don't want the components compiled under production env to be detectable by devtools. This happens if I have components that are compiled under development env.

**Comment by yyx990803** [comment]
It's only **detectable**, but not **inspectable**. The devtool will walk your page nodes anyway regardless of whether `__vue__` is exposed or not.

**Comment by andreiglingeanu** [comment]
They __do__ appear in devtools and they clash with other components, if they have the same `_uid`.

**Comment by yyx990803** [comment]
Okay, then I think the root of the problem is in the clash of multiple copies of Vue on the same page, which I strongly recommend you to avoid.

**Comment by andreiglingeanu** [comment]
Yep, that is right and I totally can't avoid that, even if I would want to. Basically, I'm creating third-party components that can be just plugged in (multiple number of them, quite often on the same page) somewhere and they should avoid clashing one with another as much as possible.

It is really a pain the ass to develop them if devtools are broken in such a way.

**Comment by yyx990803** [comment]
Can't these components all just use a shared global Vue?

**Comment by andreiglingeanu** [comment]
> Can't these components all just use a shared global Vue?

Sadly, no.

> I really can't rely on the host of my components to provide a global and valid version of Vue.

**Comment by andreiglingeanu** [comment]
Is there something that can go wrong by removing those `__vue__` properties? I really can't seem to get why that may cause any troubles...

**Comment by yyx990803** [comment]
I just don't think it's fixing the right problem. The real problem is how can multiple copies of Vue work together on the same page with the devtool.

**Comment by andreiglingeanu** [comment]
@yyx990803 What if we check [here](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L112) for `instance.$options._base.config.devtools`? Why would we want to accept instances that have devtools `disabled`?

Also, I see no reason to log events for such instances. [Here](https://github.com/vuejs/vue-devtools/blob/master/src/backend/events.js#L13) we can make the check.

By the way, from a security standpoint, what if someone will want to modify components data from outside, having `__vue__` leaked gives an easy way of doing just that.

**Comment by yyx990803** [comment]
This is because the devtools assumes there's only one copy of Vue on the page. This is simply an edge case we never expected.

Security wise, if you have someone being able to execute arbitrary JavaScript on your page, you have much bigger problems than `__vue__`.

**Comment by andreiglingeanu** [comment]
@yyx990803 I've added a small pull request regarding all of that discussion we had: https://github.com/vuejs/vue-devtools/pull/260.
