### ISSUE TITLE
`vm._uid` is not unique enough

### ISSUE THREAD

**Issue by andreiglingeanu** [vuejs/vue#4958]
### Vue.js version
dev branch

### Steps to reproduce
1. Load 2 separated vue components on the same page, by using two different webpack builds. Each of them has to not share the Vue module they're using.

### What is Expected?
To not have repeated `vm._uid` across multiple components. This breaks `vue-devtools`.

### What is actually happening?
Devtools are working in a strange way because of the repeated `_uid` they are relying on.

<hr>

A possible solution is to generate those `_uid`s a bit more randomly, with `Math.random()`. I can come up with a pull request for that.

<hr>

> Load 2 separated vue components on the same page, by using two different webpack builds.

No, there's no other way around and using global Vue is a no go for me.

**Comment by yyx990803** [comment]
This also means you are loading two copies of Vue on the same page - quite sub-optimal and not really a use case it's designed for.

Isn't it better to make the two webpack bundles share the Vue dependency instead?

**Comment by andreiglingeanu** [comment]
> This also means you are loading two copies of Vue on the same page - quite sub-optimal and not really a use case it's designed for.

Yeah, that's how I'm doing it. I'm loading them via code splitting and they're happen to load at completely different stages.

Sharing Vue dependency across webpack bundles is not an option because those two bundles actually come from two completely separated repos.

**Comment by andreiglingeanu** [comment]
Looks like it really is a bad idea to load multiple Vue dependencies on the same page.

I'd probably have to go with global Vue instead.

**Comment by motanelu** [comment]
@yyx990803  there are valid use cases for this, for example when an widget is being shipped to be used by 3rd parties. The widget needs to be embedded in a page without knowing what other frameworks / libraries are loaded - think a twitter button. Having the sites install vue separately will be a massive deal breaker for them. Can we just specify a prefix for all the components?

**Comment by posva** [comment]
Make Vue an external dependency of your widget library and make sure the client loads only one Vue copy. It's much better for your users too. Cheers.

**Comment by andreiglingeanu** [comment]
Confirmed, having one single instance of Vue is the best solution for this problem. I've avoided many problems that way.

**Comment by motanelu** [comment]
@posva It's not easier, it gets more complicated for them to the point that they may drop it in favour of something else.  Currently they just need to insert something like `<script type="text/javascript" src="http://s3-with-cloudfront-url-here.com"></script>` in their website and that's it, the widget works. 
A lot of them may be on wordpress, drupal and so on without having a build system in place. Asking them to install a specific version of vue separately from a different site is a deal breaker.

**Comment by andreiglingeanu** [comment]
@motanelu I'm doing with work on WordPress also and yes, that's still the best option.

**Comment by fnlctrl** [comment]
@motanelu As a drop-in widget, it should be bundled with it's own vue/vuex (and other dependencies) into one javascript file (with webpack/rollup etc), and never rely on the global vue provided by the user. This way your widget will always work no matter what website it runs on.

**Comment by motanelu** [comment]
@fnlctrl that's why it would be good to be able to prefix component uids

**Comment by fnlctrl** [comment]
Why would you need to prefix component uids? The bundled widget will run in a closure and will have no access to anything outside, so it will never interfere with other vue instances.

**Comment by motanelu** [comment]
I've experienced some issues with `vue-devtools`
