### ISSUE TITLE
error with .vue component

### ISSUE THREAD

**Issue by nanodesu88** [vuejs/vue#4961]
Hello! Can you help me please? 

### Vue.js version
2.1.10
vue-loader: 11.0.0
vue-template-compiler: 2.1.10

```html
<template>
    <div class="bbeditor-container">
        <textarea :value="content"></textarea>
    </div>
</template>
```
works fine, but
```html
<template>
    <div class="bbeditor-container">
        <textarea :value="content"></textarea>
        <div class="bbeditor-buttons-container">
            
        </div>
    </div>
</template>
```
throw me an error: 
[Vue warn]: Error when rendering component <wysiwyg> at c:\OpenServer\domains\aqproject\frontend\vue\wysiwyg.vue: 
TypeError: _vm._v is not a function

whats wrong with this core?

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

[Why is this required?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by nanodesu88** [comment]
sorry, this was because of library conflicts. ty
