### ISSUE TITLE
Some question about <template>tag with es6

### ISSUE THREAD

**Issue by jicjjang** [vuejs/vue#4963]
I'm passing from 'React' to 'Vue'.
It's not long.
(I'm sorry if this is a simple question.)

### Vue.js version
2.1.10

### Steps to reproduce
~~~javascript
Vue.component('my-cmp', {
  data: () => {
    return {
      status: 'Critical'
    }
  },
  template: '<p>Server Status: {{ status }} (<button @click="changeStatus">Change</button>)</p>',
  methods: {
    changeStatus: () => {      // here!!
      this.status = 'Normal'
      console.log(this)
    }
  }
})
~~~

### What is Expected?

I'm expected changing status is 'Normal' in this, but not working.

### What is actually happening?
It was just realizing in es5.
why not change this.status with es6??

---

Is my fault? or not?

**Comment by jicjjang** [comment]
Oh... Sorry, it was resolve!

**Comment by rohmanhm** [comment]
@jicjjang can you explain what's happened? so other users if had the same problems can resolve their case instantly.

**Comment by jicjjang** [comment]
It was occurred my wrong typo...
Changed under that. :)
~~~javascript
changeStatus () {      // Resolve!
    this.status = 'Normal'
    console.log(this)
}
~~~
