### ISSUE TITLE
ssr code split warn

### ISSUE THREAD

**Issue by yjj5855** [vuejs/vue#4967]
webpack 2.2
vue 2
```
  if (process.env.VUE_ENV === 'server') {
    resolve(require('./page/app.vue'))
  } else {
    require.ensure(['./page/app.vue'], () => {
      resolve(require('./page/app.vue'))
    }, 'app')
  }
```
这样写后报错
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

有什么方法解决吗？

不用require.ensure就没问题

**Comment by yyx990803** [comment]
等 2.2 会专门解决这个问题
