### ISSUE TITLE
vue 2.1.10 filter bug

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue#4968]
template
   varName | filter_name

when varName value 0 or undefined or null
filter_name report undefined this filter.( i try set varName = 1 , then ok)

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!
