### ISSUE TITLE
Cannot get object's keys stored in state from component before render

### ISSUE THREAD

**Issue by nxbaez** [vuejs/vue#4969]
### Vue.js version
2.1.10

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!
