### ISSUE TITLE
Exceptions thrown in dom handler expressions disappear

### ISSUE THREAD

**Issue by divmain** [vuejs/vue#497]
If DOM event is handled by function reference `click: onClick`, exceptions thrown inside the handler are reported in the console.  However, if a DOM event is handled by an expression `click: onClick()`, the exception is not reported.

Example:
http://jsfiddle.net/09zjkj5h/

**Comment by GITleonine1989** [comment]
我想做个异常监控，请问vue 有没有类似angularjs 的exceptionHandler，可以处理全局的异常 @yyx990803

**Comment by fnlctrl** [comment]
@GITleonine1989  https://vuejs.org/v2/api/#errorHandler
