### ISSUE TITLE
Neither this.$http.get nor Vue.http works in Vue 2

### ISSUE THREAD

**Issue by danielreed07** [vuejs/vue#4970]
Vue: 2.1.4
Vue Resource: 1.2.0

I've gone through past issues and video tutorials on Laracast, and it seems the defacto way of making an ajax requests is via `this.$http`, which gives me `undefined`. Some people have got `Vue.http` in the vue-resources repo to work but it's not working for me. The Migration Guide does not seem to address this either. 

This is the error I'm getting:
`Uncaught TypeError: Cannot read property 'get' of undefined`

`this.$http` works only in components, but not in the constructor method. 
```
new Vue({
  el: '#app',
  data: {
    showModal:       false,
    modalType:       'editor'
  },
  methods : {
    openModal:function(name) {
      this.showModal = true;
      this.modalType = name;
    },
    authenticate : function() {
      var token = { token: localStorage.getItem('token') };
      this.$http.get('http://localhost:3000/api/auth/token', token).then(function(res) {
        console.log(res);
      });
    }
  },
  mounted: function() {
    this.authenticate();
  }
});
```

**Comment by posva** [comment]
That's vue-resource, a non official package. You should read this: https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.m5pz5luux
