### ISSUE TITLE
多个Checkbox的value值 multiple checkboxes value

### ISSUE THREAD

**Issue by smadey** [vuejs/vue#4972]
### Vue.js version
1.0.28

### Reproduction Link
http://codepen.io/smadey/pen/MJMQaj

### Steps to reproduce
Click the second checkbox

### What is Expected?
value is 1,2 
like [1.0.26](http://codepen.io/smadey/pen/xgoYOY)

### What is actually happening?
value is 1

**Comment by posva** [comment]
You're simply missing the `.sync` modifier on the `:value` binding.

Please, next time make sure to check the docs further and ask the question on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) before opening issues. Thanks!
