### ISSUE TITLE
Data-View inconsistency with drag and drop

### ISSUE THREAD

**Issue by alex94puchades** [vuejs/vue#4977]
### Vue.js version
2.0.2

### Reproduction Link

http://pastebin.com/YmfpnjkA

### Steps to reproduce
1. Try to drag and drop any of the list items over other item or the square below.
2. See the output from the console.

### What is Expected?
The indexes are correct as per the console, so the view should be updated to reflect the 'ordered' computed property (which depends on 'indexes').

### What is actually happening?
The indexes shown at the console do not reflect the computed element order

**Comment by sqal** [comment]
https://vuejs.org/v2/guide/list.html#key

**Comment by posva** [comment]
As @sqal said: http://jsfiddle.net/posva/6s9o8bdj/

Please, next time, make sure to read our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md).
