### ISSUE TITLE
Unexpected watch behavior with multiple comps

### ISSUE THREAD

**Issue by SevenOutman** [vuejs/vue#4978]
In my component I watched an prop like this:
```js
  watch: {
    music(newMusic, oldMusic) {
      console.log(newMusic, oldMusic)
    }
  }
```

And in the parent comp I use this comp multiple times.

```html
<player :music="{
  title: 'Preparation'
}"></player>
<player :music="music2"></player>
<script>
  new Vue({
    // ...
    data() {
      return {
        music2: []
      }
    },
    mounted() {
      this.music2.push({})
    }
  })
</script>
```

As you see, I passed in the music prop in two ways - literal and property name.
What I expected to see in the console was the mutation of music prop in the second child comp, which was supposed to be `[Object]` twice.
But what came out to be logged was much more than I expected, including one `{title: 'Preparation'}`.

I don't know how to describe this well, but I think at least the `title: 'Preparation'` thing shouldn't have been there.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by SevenOutman** [comment]
@posva https://jsfiddle.net/SevenOutman/ew43j9rm/1/

**Comment by posva** [comment]
Oh, that's because you have an inline object passed to the `music` prop. Whenever the dom gets rendered (eg the other `music` prop value changes), the object expression get evaluated once again and passed as a new value, so the watcher gets triggered. This re render happens at the root level when you change the music2 value

**Comment by SevenOutman** [comment]
@posva Ok I understand, thank you.
