### ISSUE TITLE
how to prevent somebody from intercepting my data API link???

### ISSUE THREAD

**Issue by Jerry-goodboy** [vuejs/vue#4979]
Previously, when I use MVC framework, data and view always come together to be HTML document, and data API is behind the browser and nobody can access them, 
but now using MVVM framework( except server-side render), data and view is apart, view is always storing in the browser, and to get data from backend with data API, then to be HTML document dynamically, from now on, anyone can access my data API and add more pressure to the my API server.
what I'm concerned is how to prevent somebody from intercepting and accessing my data API when I am using MVVM framework that is vuejs framework I am using now?
this is about security and pressure on my server, so I want your help sincerely!
@wprater @asheb @nazo @BigBlueHat @sjoerdvisscher

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!
