### ISSUE TITLE
@key.tab not work in 2.1.10

### ISSUE THREAD

**Issue by jingz** [vuejs/vue#4981]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/vog3jurt/1/

### Steps to reproduce
pressing tab in textarea

### What is Expected?
It should alert something.

### What is actually happening?
nothing happen

**Comment by posva** [comment]
This is an expected behaviour: What happens is that the browser is moving the cursor out of the textarea on the keydown event, and therefore the keyup event never fires on the textarea. here you have an alternative: https://jsfiddle.net/posva/7cjemgkx/

**Comment by jingz** [comment]
thanks you.
