### ISSUE TITLE
Feature Request: @submit.enable="default"

### ISSUE THREAD

**Issue by Mapamatician** [vuejs/vue#4983]
Before I started using Vue I had a simple form that would update 1 value on 1 column @ 1 request at a time. Now I am using Vue and my form has a new 'middle' button that is being used to build up an array of items to submit 1 request to update multiple columns dynamically.

Problem is now that prevent default is enabled, my original form submission no longer works and I need to build up a new way to submit with Vue or what would be much more helpful at this stage of getting to production is if there was a way to re-enable default action on a button? Right now, this would be great.

<form @submit.prevent="newbutton">

// new button
<button @click="newbutton"></button>

// original button
<button @submit.enable="default"></button>

**Comment by posva** [comment]
I'm not sure to understand correctly: you have a `<form @submit.prevent>` somewhere and want it to work as before so you want to make thu submit button to work as before?
But in that case you simply need to pass a method to the `@submit.prevent`...

**Comment by yyx990803** [comment]
http://www.javascript-coder.com/javascript-form/javascript-form-submit.phtml
