### ISSUE TITLE
Unshifting array reflect on component incorrectly

### ISSUE THREAD

**Issue by inker610566** [vuejs/vue#4984]
Vue version: 2.1.10
Demo: https://jsfiddle.net/mtm6sLaq/1/
Explanation: This demo work on 1.x version of vue but failed on 2.1.10. The `push` to array will work correctly, but failed on `unshift`. It will also work, if array is render inside Vue instance directly without component.

**Comment by fnlctrl** [comment]
Please refer to the docs: https://vuejs.org/v2/guide/list.html#key

Simply key you `v-for`-ed component: https://jsfiddle.net/ckz7y6y3/
```<entry :key="entry" v-for="entry in entries"></entry><input v-model="new_entry">```
