### ISSUE TITLE
Error using the 'component' to traverse the component list

### ISSUE THREAD

**Issue by 1615450788** [vuejs/vue#4986]
![qq 20170222101009](https://cloud.githubusercontent.com/assets/15265570/23194128/47023040-f8e7-11e6-9355-ef87f4900b0f.png)
![qq 20170222101211](https://cloud.githubusercontent.com/assets/15265570/23194151/690ccf10-f8e7-11e6-87c2-68d56ed8abf4.png)

Remove 'is' attribute is normal

**Comment by yyx990803** [comment]
Not every export in ElementUI is a component. Check the values yourself.

**Comment by 1615450788** [comment]
After the inspection found that it is so, trouble you, thank you
