### ISSUE TITLE
When using this.$set, some properties are not converted to getter/setter

### ISSUE THREAD

**Issue by huguijie** [vuejs/vue#4987]
![image](https://cloud.githubusercontent.com/assets/22492042/23196381/3ece8100-f8f4-11e6-99d1-97c0d3e2689f.png)
![image](https://cloud.githubusercontent.com/assets/22492042/23196421/7ca314a0-f8f4-11e6-91ae-20dd0bc47269.png)
![image](https://cloud.githubusercontent.com/assets/22492042/23196426/8caf64ac-f8f4-11e6-8223-ddc9e375a909.png)
The following code is not annotated
![image](https://cloud.githubusercontent.com/assets/22492042/23198120/24487d20-f900-11e6-9c4e-18b4c0961766.png)
![image](https://cloud.githubusercontent.com/assets/22492042/23196431/9973b8aa-f8f4-11e6-9aba-d89fb7ffe44a.png)
The following code comments
![image](https://cloud.githubusercontent.com/assets/22492042/23198195/ab27772e-f900-11e6-81a2-058be3fdbc99.png)
![image](https://cloud.githubusercontent.com/assets/22492042/23198277/63059308-f901-11e6-912d-1d8d2bb45301.png)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by posva** [comment]
Closing inactivity
