### ISSUE TITLE
Resources section to feature books

### ISSUE THREAD

**Issue by packtpartner** [vuejs/vue#4988]
As Vue is gaining traction in JavaScript, Packt has published 2 books on Vue.js
[The Majesty Of Vue.js](https://www.packtpub.com/web-development/majesty-vuejs) written by Alex Kyriakidis & Kostas Maniatis
[Learning Vue.js 2](https://www.packtpub.com/web-development/learning-vuejs-2) written by Olga Filipova

Would it be possible to have a Resources section on the website to feature these books to help the community? I think it would prove to be a good learning material.

**Comment by znck** [comment]
You can add these to [awesome-vue](https://github.com/vuejs/awesome-vue).

**Comment by yyx990803** [comment]
Yeah, awesome-vue is the default collection of community resource right now. We are also planning to improve its curation quality in the near future.

**Comment by packtpartner** [comment]
Thanks for letting me know about [awesome-vue](https://github.com/vuejs/awesome-vue). Does this resource page reflect anywhere on [vuejs.org](https://vuejs.org/)?

**Comment by znck** [comment]
It's there in `Ecosystem > Resource Lists`.

**Comment by packtpartner** [comment]
Thanks @znck 
I will add the books on Awesome Vue under External resources
