### ISSUE TITLE
Modifiers to improve performance of larger datasets

### ISSUE THREAD

**Issue by thupi** [vuejs/vue#4989]
I just started working with Vuejs and have been using React and Mobx for a long time.

I quickly realized that the concept of modifiers was missing in Vuex. Furthermore i was wondering how to improve performance of large arrays of objects without having modifiers. In Vuex all the objects in an array must be converted to reactive object which might not be required and might be way less performant.

Wouldn't modfiers give the ability to further improve performance of Vuejs by giving the developer a way to tell Vuejs which parts of the data that have to be reactivity :) ?

See MobX modifiers: https://mobx.js.org/refguide/modifiers.html

**Comment by Akryum** [comment]
You CAN use `Object.freeze()` or [standard property definition](https://jsfiddle.net/Akryum/q8wu5aem/).

**Comment by znck** [comment]
Related vuejs/vuex#637

**Comment by thupi** [comment]
At the begining i thought that ```Object.freeze()``` wasn't the perfect solution but it looks like that exact function might be the best handle datasets and their reactivity :) 

Thanks :) !

**Comment by sqal** [comment]
@thupi or you can simply assign your data outside `data` object e.g.

```
created() {
 this.myData = []
}
```

but it  comes with a two caveats:

-  you have to call `this.$forceUpdate()` after updating the data
- you won't see this data in the Vue Devtools

**Comment by thupi** [comment]
@sqal Even though i would like to have immutable data i still like to have some level of reactivity. An example of the could be having an array which is reactive but have nested  immutable objective :)
