### ISSUE TITLE
Recreating `v-model` for my own directives

### ISSUE THREAD

**Issue by jdrydn** [vuejs/vue#4992]
![screen shot 2017-02-23 at 15 43 59](https://cloud.githubusercontent.com/assets/406967/23266182/ec69da7c-f9de-11e6-9941-838a43e728c9.png)

Using `v-model` in my custom components is excellent! Just so it's clear, my understanding of it is anything placed under `v-model` is relayed to the custom component as a property called `value`, and listens for `input` events to update that value. Great.

Could anyone point out to me where in the Vue source that's actually implemented? I'd like to create my own directive that does something similar (so that I have the *name* of the property being used) (much like the `expression` argument of a directive.

Thanks,

**Comment by Akryum** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, and we encourage you to use our dedicated [gitter](https://gitter.im/vuejs/vue) or [forum](http://forum.vuejs.org/) to ask questions or for discussion. Thanks!

**Comment by sqal** [comment]
@jdrydn 

https://vue-template-explorer.now.sh/#%3Cinput%20type%3D%22checkbox%22%20v-model%3D%22checked%22%2F%3E

**Comment by aziztitu** [comment]
@sqal The link seems to be broken. Could you share a new link?
