### ISSUE TITLE
组件name问题

### ISSUE THREAD

**Issue by files3** [vuejs/vue#4999]
### Vue.js version
2.0.2

### What is actually happening?

我用vue-cli ，new了一个项目，添加路由，添加组件，老是提示组件的name有问题
找到一个问题，原来这个name的空格都有影响

![wechatimg4](https://cloud.githubusercontent.com/assets/15240870/23300492/bed5ee38-fac0-11e6-9c2e-3da1de5270d5.jpeg)

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by files3** [comment]
@posva 上个问题我已经知道怎么回事了，谢谢

**Comment by RicoyWang** [comment]
@files3  Maybe,he can`t see chinese.
