### ISSUE TITLE
Feature: prop default function factory for standard types

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue#5003]
It would be great if we could get access to a prop's value when writing a factory function for its default value. This way you can add in some more flexibility when accepting props, without having to set up a computed value for them.

Current:
```js
props: {

  min: {
    type: Number,
    default: 100
    }
  }

},

computed: {

  computedMin() {
    return this.min > 100 ? 100 : this.min
  }

}
```

Requested:
```js
props: {

  min: {
    type: Number,
    default (value) {
      return value > 100 ? 100 : value
    }
  }

}
```

**Comment by posva** [comment]
The `default` is meant to give a value to a prop without one instead of coercing the value.
Using a computed property is actually the recommended way: https://vuejs.org/v2/guide/migration.html#coerce-Prop-Option-removed

**Comment by TheDutchCoder** [comment]
Alright, sounds reasonable.

Thanks!
