### ISSUE TITLE
VUEX2.0 and phantomjs-window2.1.1

### ISSUE THREAD

**Issue by lizhongyi** [vuejs/vue#5005]
I ran into a problem,about VUEX2.0 and phantomjs-window2.1.1

![image](https://cloud.githubusercontent.com/assets/3292807/23328081/838a18b0-fb54-11e6-9e23-f3a8dfecca44.png)

ps: This domain is my local domain,that is a demo with vue2.0 Family bucket app.

**Comment by fnlctrl** [comment]
As the error says: You need a Promise polyfill.
