### ISSUE TITLE
vue和微信js-sdk遇到的问题

### ISSUE THREAD

**Issue by files3** [vuejs/vue#5006]
### Vue.js version
2.0.2

### What is actually happening?

hello，我的项目weixin-js-sdk已经安装成功，new Vue里wx对象也有，就是我在组件用的时候wx这个对象的时候老是报错，想请教一下，在组件该如何初始化js-sdk呢
<img width="883" alt="wx20170225-165611 2x" src="https://cloud.githubusercontent.com/assets/15240870/23329840/626a0448-fb7b-11e6-8d1d-940f90c72844.png">

**Comment by fnlctrl** [comment]
你好，请使用[论坛](http://forum.vuejs.org/)或[gitter](https://gitter.im/vuejs/vue)提问，issue列表只用于提交bug和feature request，谢谢！

**Comment by Chooin** [comment]
https://github.com/Chooin/wechat-spa

**Comment by airyland** [comment]
挂载到prototype上：

``` js
import wx from 'weixin-js-sdk'
Vue.prototype.$wx = wx
```

组件里通过 `this.$wx` 调用。
