### ISSUE TITLE
[2.2.0-beta] How to test exception thrown inside a method

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#5007]
### Vue.js version
2.2.0-beta

### Reproduction Link
2.2.0-beta.2 https://jsfiddle.net/sqal/u7ogag2e/
2.1.10 - https://jsfiddle.net/sqal/Lsyvkwwm/

### Steps to reproduce
Check console of these two examples

### What is Expected?
I expect that first test in 2.2.0-beta.2 passes.

### What is actually happening?
The same test that passed in 2.1.10 is not passing in new vue 2.2.0 ...and I can't figure out why. I am guessing it has something to do with this commit 3c0cdb553590db84 but i am not entirely sure how to properly test these kinds of things now, Should I just follow this example - https://github.com/vuejs/vue/blob/1861ee9570730149e01f225323c3a52392e5900f/test/unit/features/options/renderError.spec.js and move all my exceptions to the render function and then test what the rendered output is? or maybe i am  just doing something wrong here? Anyway I would very much appreciate if someone would explain all of this to me. Thanks :)

**Comment by posva** [comment]
Hi. Thanks for reporting the issue.
The idea behind that commit is not to break the whole rendering (aka crash the app) when an error is thrown during a component lifecycle and to allow the user to handle themselves with the `Vue.config.errorHandler`. [This improves debugging](https://twitter.com/youyuxi/status/833542268065816576/video/1)

A current workaround for your case is to define a simple errorHandler that throws: 
```js
Vue.config.errorHandler = function (err, vm, type) {
  throw err
}
```

I think this is more of a feature than a regression 😆

**Comment by sqal** [comment]
Thank you @posva, Added your snippet to my test entry file and everything works now :) So easy. And  I acutally also like the new features, just couldn't quite find solution for my problem. I have to check docs more often. I think we can close this issue now. Thanks again :)
