### ISSUE TITLE
ES modules build in npm

### ISSUE THREAD

**Issue by c01nd01r** [vuejs/vue#5010]
### Vue.js version
2.2.0

### Reproduction Link
https://github.com/vuejs/vue/blob/dev/package.json#L9-L21

### What is Expected?
esm build files in npm package
### What is actually happening?
vue.runtime.esm.js and vue.esm.js are missing in npm package

Hi! 
Thanks for new release, but I can't find new ES modules build files in npm package.
Seems like, this files missing from package.json in `files` field?

**Comment by c01nd01r** [comment]
#5009

**Comment by yyx990803** [comment]
Published 2.0.1.
