### ISSUE TITLE
Yandex Map not work with Vue

### ISSUE THREAD

**Issue by webmarkelov** [vuejs/vue#5011]
Yandex Map not work with Vue :( bug or no? 

### Vue.js version
2.1.10

### Reproduction Link
[codepen](http://codepen.io/webmarkelov/pen/bqNXdp)

### What is Expected?

In console message: **Script element was removed from document**

**Comment by sfi0zy** [comment]
You can use the ID parameter in your Yandex Map - [codepen](http://codepen.io/sfi0zy/pen/BWyXmL)

**Comment by webmarkelov** [comment]
Thanks! but I need what work script

**Comment by simplesmiler** [comment]
@webmarkelov this is a usage question, and the issue tracker is reserved for core bugs and feature requests.

The way you are trying to do this is not supported. Components can not contain `<script>` tags.
