### ISSUE TITLE
feature request: vm.$watch should return a Promise

### ISSUE THREAD

**Issue by paglias** [vuejs/vue#5013]
I understand this would be a big breaking change but it would be useful in a promise-heavy project to be have vm.$watch return a promise instead of a function to cancel the watcher.

**Comment by Akryum** [comment]
An `Observable` would fit better than a Promise (which is supposed to resolve only once, but it's not standardized yet.

**Comment by yyx990803** [comment]
An `Observable` makes much more sense, and in that case you probably want something like [vue-rx](https://github.com/vuejs/vue-rx).`

And - as you said, it's a breaking change, but I don't see returning a Promise being that useful to warrant the change.
