### ISSUE TITLE
Different Behavior: tag a bind a function change href

### ISSUE THREAD

**Issue by 1ychee** [vuejs/vue#5018]
Test in newest Chrome, Safari, Firefox browser, vue.js is also newest.

I write tag a like this:
    `<a :href="url" @click="doSomething">{{url}}</a>`

new Vue instance, give url a default href, like https://www.google.com
In function doSomething only do 
    `this.url = 'http://cn.bing.com';`
When click a, Only Firefox jump to https://www.google.com, Chrome and Safari jump to http://cn.bing.com

If I write code like below in doSomething function:
    `let links = document.getElementsByTagName('a');`
    `links[0].href = 'http://cn.bing.com';`
When click a, Firefox, Chrome, Safari both jump to http://cn.bing.com

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with this [template](http://jsfiddle.net/df4Lnuw6/) that already includes the latest version of Vue.

**Comment by posva** [comment]
Changing the url on the click event definitely looks like a bad idea. I was expecting it to work on none of the browsers because the modification on the href is not reflected right away. You're also saying the user you're going to redirect them to a page then do something else 😬 

If you really want to have that behaviour you can, as you said, set the href in the handler: http://jsfiddle.net/6mhovjc1/3

**Comment by 1ychee** [comment]
I have update the code you give, @znck ,because I am not good at JSFiddle, you can take the code test in Firefox and Chrome, @posva I know what you said, but this found is when I see the document you give in vuejs.org chapter template syntax example, my English is not good, I hope you can understand what I am speak

**Comment by posva** [comment]
@1ychee  Can you share that doc page so we give it a look, please?

**Comment by 1ychee** [comment]
Your doc is right, I think wrong. Maybe the idea change a tag href url by js is very very very wrong! Anyway thanks answer the question
