### ISSUE TITLE
feature request:force render immedialty

### ISSUE THREAD

**Issue by zuomingcai** [vuejs/vue#5019]
sometimes we change component's data,and need the component to rerender immedialty so we can get the corresponding element's properties as return value.
currently,forceupdate can trigger the component to reredner but the rerender was not executed immediatly.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Since vue's render process is async, the proper way of accessing rendered element's properties is using a `nextTick` callback, e.g.

```js
this.$nextTick(() => console.log(this.$el.clientWidth))
```
