### ISSUE TITLE
v-model cant reflect input value  in wechat on iphone

### ISSUE THREAD

**Issue by gaecom** [vuejs/vue#5020]
### test environment
app(or wechat) on iphone
### Vue.js version
1.0 version
### Reproduction Link

visit the page in wechat on iphone
### Steps to reproduce
http://jsbin.com/kiquvesiju/edit?html,js,output
1. visit the page in wechat on iphone
2. switch to chinese ime(input method)
3. input any chinese ***without entering(hit) "确认/OK"*** and jump to next input field
4.  Alerted message when hit the "echo a1" button is empty.
### What is Expected?
expected echo data is your input message
### What is actually happening?
 Alerted message when hit the "echo a1" button is empty.

**Comment by posva** [comment]
I cannot test myself but I saw you were using an outdated version of Vue 1. Please test with the updated version

**Comment by HerringtonDarkholme** [comment]
Hi @gaecom . I found this behavior is IME specific. That is, Chinese IME will not input any characters without confirmation. The same behavior can be produced on plain input and various websites, e.g. GitHub. 
If you change another IME like Japanese IME, it will work as expected.

**Comment by yyx990803** [comment]
FYI ignoring composition events on desktop is necessary to ensure correct syncing behavior. Not sure if this is even possible to fix if the user does not finish composition.

**Comment by posva** [comment]
@HerringtonDarkholme Do you think we can close this?

**Comment by HerringtonDarkholme** [comment]
@posva Yes I think so. 

If some one has come up with a new solution, we can open a new issue. For now I don't think there is a panacea.
