### ISSUE TITLE
Reactivity when replacing data array with the new array

### ISSUE THREAD

**Issue by jingz** [vuejs/vue#5021]
### Vue.js version
2.2.0 with
I follow the doc https://vuejs.org/v2/guide/list.html#Replacing-an-Array

### Reproduction Link
https://jsfiddle.net/jxprjt0c/1/

### Steps to reproduce
click a remove button

### What is Expected?
It should remove the item at correct index.

### What is actually happening?
It always remove the last one.

**Comment by HerringtonDarkholme** [comment]
It is required that a `key` should be present on item in `v-for`.

https://jsfiddle.net/jxprjt0c/2/

Check the changelog out:  https://github.com/vuejs/vue/releases/tag/v2.2.0
