### ISSUE TITLE
Version of Bootstrap included in benchmarks includes links to files that do not exist

### ISSUE THREAD

**Issue by bzmwillemsen** [vuejs/vue#5029]
### Vue.js version
2.2.1

### Reproduction Link

The version of bootstrap in the Vue project located here: https://github.com/vuejs/vue/blob/v2.2.1/benchmarks/dbmon/lib/bootstrap.min.css
contains links to files that do not exist. Specifically: 
```
url(../fonts/glyphicons-halflings-regular.eot);src:url(../fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'),url(../fonts/glyphicons-halflings-regular.woff) format('woff'),url(../fonts/glyphicons-halflings-regular.ttf) format('truetype'),url(../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular)
```

### What is Expected?
That the files exist, or that the version of bootstrap that is compiled doesn't depend on font files.

### What is actually happening?
I'm trying to run a build tool with Django, called `collectstatic`, part of collectstatic is cache busting for links in `css` files, when it tries to follow these links it exits with an error because the file does not exist.

**Comment by yyx990803** [comment]
The benchmark doesn't use those glyphs, and the benchmarks are only intended to be run standalone, not intended to be used elsewhere. If you need bootstrap, use proper setup per their latest docs.

**Comment by bzmwillemsen** [comment]
> The benchmark doesn't use those glyphs, and the benchmarks are only intended to be run standalone, not intended to be used elsewhere.

Should the benchmarks be included in the bower package then? Personally I do not see a reason to include it in a bower package, just as `source`, and `.github` should not be included. Actually I just realized that there is no `bower.json` definition in the app, is that on purpose?

**Comment by posva** [comment]
yes: https://github.com/vuejs/vue/issues/4040
