### ISSUE TITLE
is there a way to use variable in html loop

### ISSUE THREAD

**Issue by artofspeed** [vuejs/vue#5033]
In html, when you loop an array, you have access to each variable in the array, then you can do {{variable}} to display it. However, if you need to bind a click function that has the same name as that variable, is there a way to do it?

```html
<div v-for='item in arr'>
    <div v-on:click='item'>Execute function {{item}}</div>
</div>
```

```javascript
var app = new Vue({
    data: {
        arr: ['fn1', 'fn2', 'fn3']
    },
    methods: {
        fn1: function(){},
        fn2: function(){},
        fn3: function(){},
    }
```
Here, when you click on each `div` in the loop, you are supposed to call a function whose name is the same as the `item` in the `arr`, currently it returns `Uncaught TypeError: fns.apply is not a function` on console.

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by fnlctrl** [comment]
use `this[item]` as `item` is actually used as a property name 
```html
<div v-on:click="this[item]"></div>
```

**Comment by artofspeed** [comment]
@fnlctrl Hi i tried your way and it doesn't work :( https://jsfiddle.net/pgsyotro/1/

**Comment by fnlctrl** [comment]
Sorry for giving a false answer, please use the forum or Gitter as @phanan said.
(Corrected one, for the record: https://jsfiddle.net/q3bvndc6/)

**Comment by artofspeed** [comment]
@phanan will do
@fnlctrl 谢谢 ^_^ u rock
