### ISSUE TITLE
使用props传递数据时获取不到需要的数据

### ISSUE THREAD

**Issue by Guoxd1031** [vuejs/vue#5034]
比如有数据：
`info:{
   list:[
     {"img":""}, {"img":""}, {"img":""}
  ]
}`
通过props传递之后在子组件中想获取 this.info.list,得到的是一个空数组
打印输出this.info.list.length，得到的结果是0.
这是为什么？

**Comment by kazupon** [comment]
Thanks for filing the issue! Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
