### ISSUE TITLE
函数式组件多Root返回节点渲染行为不一致

### ISSUE THREAD

**Issue by Clunt** [vuejs/vue#5035]
## 描述
烦请点击下方复现连接，并打开控制台查看[mounted (n), beforeDestory (n)]的输出次数。

- 1 2 对照组，区别在于`foo`组件内外是否同时存在`v-if`的元素。同时存在时`article`组件会反复重建；反之只会创建一次。
- 1 3 对照组，区别在于对`slot`的命名与否。命名为`custom`时`article`组件只有在`show`将要为`false`时才会重建，为`true`时不会（节点减少时重建，增加时不会）。同未命名的Demo 1表现不同。
- 2 4 5 参考组，2, 3区别在于对`slot`的命名与否，相同之处为`foo`组件内外并不同时出现`v-if`元素，但表现一致，作为参考。5在`foo`组件外部包裹一层`div`，表现同期望一致，作为基础参考。

补充：1 3会将插入body末尾的`article`组件重新放回`foo`组件中。

## 疑惑
期望节点的销毁不会导致`article`的重建，且不会使节点移回`foo`组件中。
但通过几个示例发现整体表现比较奇怪，没有太好的思路去查找哪里出了问题，不清楚哪种表现为正常状态。是否会在之后的版本保持一致？
非常感谢！

## 复现连接
https://jsfiddle.net/dr96pzmj/8/

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. I tried to read the translated version of your message but it wasn't easy to follow. After looking at your code, it looks like more like a question than an issue, so please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) and make sure the problem doesn't lie within your application code first, in which case provide a **minimal** reproduction for the bug.
I saw you did
```js
mounted() {
      console.log('mounted ' + this.demo);
      document.body.appendChild(this.$el);
    },
```
You shouldn't be using `document.body.appendChild(this.$el)` (or any other manual DOM manipulation) on elements that are manipulated by Vue. You'll probably find yourself in unexpected cases. In you case you should add the `el` attr to the `new Vue` call or call `$mount` on the resulting instance. Please, check the [docs](https://vuejs.org/guide/) for more information (there's a search on the top right)
Thanks!

**Comment by Clunt** [comment]
Well, i can remove the code `document.body.appendChild(this.$el);`, this is not the key. 
I want to say that lifecyle of functional components is weird. I'm sure this is not a question about programming, but Vue's weird performance at the time of processing.If you do not understand what I'm saying, please reopen the question and wait for someone else to answer. Thank you.

**Comment by Clunt** [comment]
@yyx990803 如果可以的话，希望可以在百忙之中查看一下这个问题。万分感激！

**Comment by fnlctrl** [comment]
First of all, this is not a bug (i.e. against documented behavior), but rather a usage question. I agree with @posva that it should have been posted to the forums.

As for your question, simply put:
1. Functional components don't have lifecycles.
2. The lifecycle behavior of a normal(stateful) component that's rendered by a functional component is determined by the virtual dom diffing algorithms, which belongs to internal implementation and thus no warrant is given.
3. However, the docs have clearly stated that this behavior can be manually controlled with `key`: http://vuejs.org/v2/api/#key, http://vuejs.org/v2/guide/list.html#key
so the solution is simply keying your stateful component: 
https://jsfiddle.net/zbukeqca/

=============

**tl,dr; Key your components, if you want a predictable behavior of their lifecycles.**

**Comment by Clunt** [comment]
@fnlctrl 首先非常感谢你的解答。添加Key之后的表现确实一致。但是我比较疑惑，在未加key时，demo 1 3只有slot命名与否的区别，但是在切换时子组件的重建表现却不一致。这不是Bug么？

**Comment by fnlctrl** [comment]
默认的行为是保证渲染结果正确的前提上尽量优化性能，内部实现的细节（对于命名的slot和默认的slot的处理）并没有任何行为上的保证，且文档已经说明了正确的使用方法（加key）。所以只要渲染结果没有出错，就不是bug。
