### ISSUE TITLE
createBundleRenderer('/path/to/bundle.json') failed

### ISSUE THREAD

**Issue by wongyouth** [vuejs/vue#5037]
`createBundleRenderer('/path/to/bundle.json')` failed.
but `createBundleRenderer(require('/path/to/bundle.json'))` succeed

And I found the pattern `/\.json$/` is tested based on file content but not based on file name:

```
bundle = fs.readFileSync(bundle, 'utf-8')
   if (/\.json$/.test(bundle)) {
```

see
https://github.com/vuejs/vue/blob/dev/src/server/create-bundle-renderer.js#L47-L48

**Comment by yyx990803** [comment]
Thanks for locating the problem!
