### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by stnickolas** [vuejs/vue#5040]
I have installed modules like in simple example:

    "devDependencies": {
      "babel-core": "*",
      "babel-loader": "*",
      "babel-preset-es2015": "*",
      "vue": "*",
      "vue-loader": "*",
      "vue-template-compiler": "*",
      "webpack": "*"
    }

and set up webpack config:

    module.exports = {
      entry:"./main",
      output:{
          filename:"app.js"
      },

      module:{
          loaders:[{
              test: /\.js$/,
              loader: 'babel-loader',
              query: {
                  presets: ['es2015']
              }},{
              test: /\.vue$/,
              loader: 'vue-loader'
          }]
      }
}

and created my entry:

    import Vue from 'vue';

    new Vue({
      el:'body',
      data: { message:"test" }
      })

build is ok, but in browser I see this:

> [Vue warn]: Failed to mount component: template or render function not defined. 
(found in `<Root>`)

**Comment by yyx990803** [comment]
Please read https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds
