### ISSUE TITLE
Nested Vue not working

### ISSUE THREAD

**Issue by mgholam** [vuejs/vue#5042]
Given the following, nested vue bindings
```html
<html>
<body>
    <script src="vue.js"></script>
	<div id="main" :dir="lang">
		<div id="a1" class="test">
			<input v-model="test" />
			<label>{{test}}</label>
		</div>
		<br> <br>
		<div id="a2" class="test">
			<input v-model="test" />
			<label>{{test}}</label>
		</div>
	</div>
    <script>
	function c(){
return new Vue(
{
    //el : "#a1",
    data :{
       test : ""
    }
});
};
new Vue({
 el:"#main",
 data:{
	lang:"RTL"
 }
});
c().$mount("#a1");
c().$mount("#a2");
	</script>
</body>

</html>
```
I get errors that `test` is not defined, am I using it wrong? and how can this be achieved?

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). Issue tracker is reserved for bug reports and feature requests.

As for the question:
1. You can not mount instances one inside of another.
2. You can not mount instance multiple times to different elements.

You should use [components](https://vuejs.org/v2/guide/components.html) instead.
