### ISSUE TITLE
Injecting falsy values

### ISSUE THREAD

**Issue by znck** [vuejs/vue#5043]
## Version
2.2.1

## Reproduction Link
[https://jsfiddle.net/agvmLg8t/1/](https://jsfiddle.net/agvmLg8t/1/)

## Steps to Reproduce
- View generated output

## What is expected?
Provided falsy values should be injectable.

## What is actually happening?
Check in [inject.js#L16](https://github.com/vuejs/vue/blob/f916bcf37105903290ad2353db9a9436536d6859/src/core/instance/inject.js#L16) prevents injection of falsy values.

**Comment by LinusBorg** [comment]
```
if (source._provided && typeof source._provided[provideKey] !== 'undefined') {
```

should be enough, right?

**Comment by znck** [comment]
`in` check would handle cases like `provide: { foo: undefined }`

**Comment by Akryum** [comment]
Or `provide.hasOwnProperty`? https://jsfiddle.net/Akryum/y7Lfa58j/

**Comment by znck** [comment]
`hasOwnProperty` ignores inherited properties.

I guess inherited properties are not required in our case. Should it be changed to `hasOwnProperty`?

**Comment by posva** [comment]
I like the fact that `in` makes a shorter version 😆 Just ping Evan on the PR 🙂
