### ISSUE TITLE
Multiple checkboxes with v-model and computed property works unexpectedly 

### ISSUE THREAD

**Issue by dmitrykurmanov** [vuejs/vue#5045]
Vue.js version: **2.2.1**

Reproduction Link: https://jsfiddle.net/badgoto/p8zhrg6g/5/ 

Steps to reproduce: just go to the console and click on checkboxes

What is Expected: **array** in the console

What is actually happening: **boolean** in the console

PS: I think this is because of that code:

https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js

`  addHandler(el, CHECKBOX_RADIO_TOKEN, ...` and Array.isArray check.

**Comment by dmitrykurmanov** [comment]
I've also posts this question to the forum: https://forum.vuejs.org/t/v-model-multiple-checkbox-and-computed-property/6544 and to stackoverflow: http://stackoverflow.com/questions/42248888/vuejs-v-model-multiple-checkbox-and-computed-property. But there are no answers.

**Comment by Akryum** [comment]
Don't use `_` at the beginning of data properties.

**Comment by dmitrykurmanov** [comment]
@Akryum thank you for your extremely quick answer! May be we should add this restriction into docs?

**Comment by posva** [comment]
It's [here](https://vuejs.org/v2/api/#data)

**Comment by dmitrykurmanov** [comment]
@posva oh yes, great! Thanks for your work!

**Comment by dmitrykurmanov** [comment]
@Akryum, @posva, I have one more question about it. What if I need default null value in data. Please see example: https://jsfiddle.net/badgoto/p8zhrg6g/8/

**Comment by Akryum** [comment]
What is your use case?

**Comment by dmitrykurmanov** [comment]
@Akryum, I have third-party object (with undefined by default) which i want to use in computed prop for multiple checkboxes.

PS we're trying to correct implement surveys checkbox in vue https://github.com/surveyjs/surveyjs/blob/master/src/vue/checkbox.vue

**Comment by Akryum** [comment]
Maybe you can try setting the initial value to `[]` if it's undefined.

**Comment by dmitrykurmanov** [comment]
Yes, we've tried something like that.
