### ISSUE TITLE
v-on:keydown.right and left seems to be broken in Vue 2.2.1

### ISSUE THREAD

**Issue by grofzero** [vuejs/vue#5046]
Hi,

Upgrading to 2.2.1 broke the following line <li v-on:keydown.right="focusMenu(1)"> Right and left modifiers on keydown seems to be broken, but v-on:keydown.39 is still working.

Thanks in advance,
grofzero

**Comment by Akryum** [comment]
Repro: https://jsfiddle.net/Akryum/9noa3eu5/

**Comment by grofzero** [comment]
Sorry, and thanks for the repro

**Comment by Kingwl** [comment]
i'm sorry about this problem
I think this is what I have caused

**Comment by posva** [comment]
@Kingwl It's ok 🙂
