### ISSUE TITLE
Minimize css in vue-style-loader

### ISSUE THREAD

**Issue by smitt04** [vuejs/vue#5051]
I would of added this in `vue-style-loader` but issues is not enabled.  I am using the Vue SSR and the `context.styles` to inject styles into the head. But It doesn't look like it supports minification of the css. Is there a way to turn it on. It could save a lot of bandwidth and document size from having minification.

**Comment by sqal** [comment]
Have you tried processing css using using postcss with https://github.com/ben-eb/cssnano plugin?

**Comment by smitt04** [comment]
My css does get minified with webpack and postcss. But when using the vue-server-renderer, vue-style-loader add css into `context.styles` with the `<style>` tag already. So now i am working on pulling out the css from the tags, minifying and putting back into `<style>` tags. I think this would be better for `vue-style-loader` to do this in production mode.

**Comment by blake-newman** [comment]
@smitt04 

Today I also bumped into this issue. If you are using an alternative loader, such as sass. You will need to configure this on Vue loader options. 


```js
{
  loaders: {
    scss: 'vue-style-loader!css-loader?minimize!style-loader'
  }
}
```

**Comment by Suven** [comment]
@blake-newman: Could you explain your solution? I can not find the correct place for that setting
