### ISSUE TITLE
Computed Value on Child Prop Not Binding on Creation

### ISSUE THREAD

**Issue by joshbodine21** [vuejs/vue#5057]
I have a child component that I pass some data to as a prop from my parent component. I then setup a computed value for that prop. However, that computed value is not returning anything upon initial load. Once the component is rendered, then the computed property will return the data. Basically, when I log my computed value to the console on mounted it is empty, but once the page is rendered and my for loop occurs, the computed value has the data. The lifecycle chart seems to indicate otherwise.

```
<template>
    <div v-for="(row, rowIndex) in validRows">
        {{ my data is available here now }}
    </div>
</template>

<script>
props: {
    rows: {
      type: Array,
      required: true
    }
},
computed: {
    validRows () {
      // will be doing some filtering here
      return this.rows
    }
},
mounted () {
     console.log(this.validRows)
}
</script>
```

**Comment by joshbodine21** [comment]
Nevermind, this is my fault. I now realize the issue is that my prop is being populated in the parent by an asynch operation that hasn't completed by the time the child component loads.

**Comment by geeksaurav** [comment]
So how you overcame it?
