### ISSUE TITLE
problem with window.onload=funtion()

### ISSUE THREAD

**Issue by xianweiliu** [vuejs/vue#5061]
Hi guys,
I just starting to using vue.js and I start off the first thing which using the HTML to code:
    <script>
        window.onload=function(){
            new Vue({
                el:'#box',
                data:{
                    msg:'hello world'
                }
            });
        };
    </script>
<body>
    <div id="box">
        {{msg}}
    </div>
</body>
once I tried to display it on the browser, it only shows {{msg}}, but not hello world. I also link the the source with it...

**Comment by goforward01** [comment]
@xianweiliu 先从官网文档：http://vuejs.org开始吧，issue是用来追踪问题的，不是提供教程的地方。

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue, however the issue tracker is reserved for bug reports and feature requests only, please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com)to ask questions. Thanks!
