### ISSUE TITLE
ES5 Vuex problem since Vue 2.2.0

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#5062]
I have an application in **ES5**. After updating to Vue **2.2.0** I get the message:

`[vuex] must call Vue.use(Vuex) before creating a store instance.`

The Vue 2.2.0 release notes quote:
> You should only use `import Vue from 'vue'` with webpack 2.

So instead of `var Vue = require('vue')`

However this solution does not work, perhaps because of a mix of ES5 and ES6?

Should we rewrite the entire application in ES6 or go back to Webpack 1?

### Vue.js version
2.2.0

### Reproduction Link
--

### Steps to reproduce
ES5 Vue 2.2.0 With Vuex 2.2.0 Application with Webpack 2

**Comment by fnlctrl** [comment]
ES6 is just javascript, and is completely compatible with existing ES5 code, so you don't need to rewrite the entire application even if you want to switch to ES6.

If you don't want to use `import`, simply use `var Vue = require('vue').default` instead.

**Comment by fnlctrl** [comment]
ES6 is just javascript, and is completely compatible with existing ES5 code, so you don't need to rewrite the entire application even if you want to switch to ES6.

If you don't want to use `import`, simply use `var Vue = require('vue').default` instead.

**Comment by kvdmolen** [comment]
@fnlctrl Thanks for your answer, however adding `.default` results in the error:

`Cannot read property 'use' of undefined` probably for `Vue.use(Vuex)`

**Comment by fnlctrl** [comment]
~~Cannot reproduce with the exact versions of the three. Can you try something like `console.log(require('vue').default)`?~~

Sorry, I forgot to mention that webpack 2 natively supports `import` clauses, so the best way is to use `import Vue from 'vue'`, you don't need transpilers (e.g. babel) for this.

**Comment by kvdmolen** [comment]
@fnlctrl thanks. For the record, this works:

```
var Vue = require('vue')
var Vuex = require('vuex').default
```

So only use the `.default` for the plugin

**Comment by yyx990803** [comment]
With webpack 2 you should not use require anymore, it natively understands
ES 2015 module syntax. Other parts or your code can stay es5.
