### ISSUE TITLE
Feature request: shorthand bindable attributes

### ISSUE THREAD

**Issue by neves** [vuejs/vue#5068]
Suppose the follow declaration inside a component:
```html
<input :value="value" :readonly="readonly" :disabled="disabled" :maxlength="maxlength">
```
My feature suggestion is a shorthand declaration for when the attribute is bound to a property with same name, so the code above could be written like this:
```html
<input :value :readonly :disabled :maxlength>
```
The same could be for **v-on**

**Comment by sqal** [comment]
https://github.com/vuejs/vue/pull/2877
