### ISSUE TITLE
all "input event" of all html input are triggered by a change of one of them

### ISSUE THREAD

**Issue by lemmel** [vuejs/vue#5069]
Hi.

I'm not really sure that it is a bug as it is a plain and simple code, but I found nowhere in the docs something talking about such a behaviour.

### Vue.js version
2.2.1

### Reproduction Link
You can test it here: http://codepen.io/anon/pen/jBWgZb
and below is the full test code:
```html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.js"></script>
  </head>
<body>
<div id="test">
  With vuejs<BR>
  <input type="text" v-model="value1" v-bind:input='change(1)'/>
  <input type="text" v-model="value2" v-bind:input='change(2)'/>
</div>
  Without vuejs<BR>
  <input type="text" oninput='vm.change(3)'/>
  <input type="text" oninput='vm.change(4)'/>

<script>
  var vm = new Vue({
    el: '#test',
    data: {
      value1: 1,
      value2: 2
    },
    methods: {
      change: function(nb) {
        console.debug('A change for:'+nb);
      }
    }
  })
</script>
</body>
</html>
```

### Steps to reproduce
Put a value in one of the input which are managed by vuejs.
Put a value in one of the input which are not managed by vuejs.
### What is Expected?
I expect to see only two messages in the debug console.
### What is actually happening?
By following the steps described earlier with firefox (51.0.1), you will get 3 messages: two for the vuejs input and one for the regular input 

It seems that when a value is set in one html's input managed by vuejs all of the input's event managed by vuejs are triggered when the value is changed.

**Comment by LinusBorg** [comment]
You are using `v-bind:` where you should be using `v-on:`

Please read the guide on how to deal with events.

**Comment by lemmel** [comment]
I don't understand how I could make such a mistake (I'm fairly used to vuejs).
Probably too tired to code that day (I even took time to build the snippet).
I'm sorry to have bothered, and I'm thankful.

**Comment by LinusBorg** [comment]
Happens to the best of us :)
