### ISSUE TITLE
Radio buttons in named slot using v-model update data but do not visibly change the currently checked

### ISSUE THREAD

**Issue by andrewsauder** [vuejs/vue#5071]
I am experiencing an odd issue when using a list of radio buttons with v-model attributes inside of a named slot in a component. Choosing a radio button successfully updates the parent data that it is tied to in v-model but the radio buttons themselves do not visibly change to select the appropriate value.

### Vue.js version
2.2.1

### Reproduction Link
Reproduction link: https://jsfiddle.net/3x0apcgd/4/

### Steps to reproduce
Reproduction steps:
1. Click on "show modal"
2. Change the radio button

### What is actually happening?
Notice that the display of the data {{ selected }} in the same component slot updates correctly and the radio buttons in the parent (visible in the background) select correctly as well.   

- I first assumed I had a reactivity issue but I do not believe this to be the case. Because it is a named slot defined in the parent template, it has the parent scope and the parent data and template appears to be updating correctly.
- I then assumed it was an issue with the dom being out of sync (however, this seemed odd since the data is displaying correctly in real time in the same slot with {{}}). I can $forceUpdate at the parent level by watching "selected" with no change (but I believe this to be expected since $forceUpdate doesn't automatically children).  I do not know how to trigger a $forceUpdate within the modal child component since the data inside of it is actually scoped to the parent level.

Hoping someone can shed some insight.

**Comment by sqal** [comment]
That's really weird, I checked other browsers and the results are: 

IE11 - works fine
Edge - updates selected value inside the modal, but checkboxes aren't checked
Firefox - nothing happens after clicking on the checkbox
Chrome - same behavior as in Chrome

**Comment by andrewsauder** [comment]
I confirm those test results with this minor exception: Chrome leaves the initial radio button checked while Edge unchecks all of the radio buttons upon change.

**Comment by johnleider** [comment]
Because you have ```v-on:click.stop.prevent``` on the modal. You don't need the prevent default. In fact, the relationship of model has nothing to do with it.

**Comment by andrewsauder** [comment]
Confirmed. Here's an updated fiddle in case others run across this in the future, as the modal component was pulled directly off of the Vue examples (https://vuejs.org/v2/examples/modal.html):
Corrected modal, working: https://jsfiddle.net/andrewsauder/3x0apcgd/9/
