### ISSUE TITLE
`v-bind:style` not binding certain properties

### ISSUE THREAD

**Issue by edjroot** [vuejs/vue#5074]
### Versions
Vue 2.2.1  
Chrome 56.0.2924.87 (64-bit)
Windows 10

### Reproduction Link
https://jsfiddle.net/zey5eL5v/

### Steps to reproduce
Testing on Chrome, bind `{ cursor: 'grab' }` to an element's `style` attribute.

### What is Expected?
At least on Chrome, `style` should be assigned `cursor: -webkit-grab` (noting that it should also be autoprefixed).

### What is actually happening?
On Firefox, `style` is assigned `cursor: grab` (works as expected). On Chrome, the element doesn't receive a `style` attribute.

I'm guessing Vue is simply ignoring the property because it's not recognized by Chrome.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
First of all, Vue isn't responsible for auto prefixing styles, it's the job of css processors.
And it's actually Chrome that's ignoring the `cursor: grab`, you can verify this simply by trying
```js
document.body.style.cursor = 'grab'
```
Browsers simply ignore css properties they can't recognize when setting style with javascript.

As for applying prefixed style objects (i.e. cursor: ['-webkit-grab','grab'], created by tools like `postcss`), it's currently not supported but there is an open PR for that. (https://github.com/vuejs/vue/pull/4994)

**Comment by edjroot** [comment]
Thanks for the quick response (and for the PR)!

> Vue isn't responsible for auto prefixing styles

Then I guess I'm misreading the [docs](https://vuejs.org/v2/guide/class-and-style.html#Auto-prefixing) (or it needs to be updated)?

> When you use a CSS property that requires vendor prefixes in `v-bind:style`, for example `transform`, Vue will automatically detect and add appropriate prefixes to the applied styles.

**Comment by fnlctrl** [comment]
> Then I guess I'm misreading the docs (or it needs to be updated)?

Oops, sorry I was wrong about that. Vue does automatically add prefixes to property names, but not property values. Perhaps this should be noted in the docs..

**Comment by edjroot** [comment]
No problem! That makes sense, thanks!

For now, how can I achieve this? I thought about returning something like `postcss([autoprefixer]).process(styleObj).css` in all computed properties, but I'm not sure if this is the recommended way.

**Comment by fnlctrl** [comment]
For now, the only way is using `<style>` tags + prefixed css, instead of binding inline style with `v-bind:style`, since binding objects like `cursor: ['-webkit-grab','grab']` requires `v-bind:style` to support array as value.

**Comment by fnlctrl** [comment]
Closing as the PR has been merged. https://github.com/vuejs/vue/pull/5460
