### ISSUE TITLE
v-on:click not firing while window is still scrolling?

### ISSUE THREAD

**Issue by cho-is** [vuejs/vue#5076]
### Vue.js version
2.2.1

### Reproduction Link
https://jsfiddle.net/rdjjpc7a/1869/

### Steps to reproduce
While scrolling try and click on the red button. Is happening on latest macOS and Chrome. 

### What is Expected?
Expected to fire the event?

### What is actually happening?
Not firing the click event while the window is scrolling. Not sure if this is the expected behaviour.

**Comment by znck** [comment]
Cannot reproduce. 

I guess it is browser specific issue. Can you update issue description to include you operating system and browser version?

**Comment by cho-is** [comment]
updated. Latest macOS and Chrome.

**Comment by tyurderi** [comment]
@cho-is I would write the specific version of macOS and Chrome because it could changed unexpectedly and we don't have the right version information anymore.

**Comment by NickolasBoyer** [comment]
I can reproduce it, using Mac OS 10.10.5 (14F2009) and Chrome Version 56.0.2924.87 (64-bit) plus Safari Version 10.0.1 (10602.2.14.0.7)

**Comment by LinusBorg** [comment]
Not reproducible on Windows + latest Chrome  (56.0.2924.87)

Also, please check weither a vanillaJS implementation works for you, or is buggy as well:

https://jsfiddle.net/Linusborg/rdjjpc7a/1879/

**Comment by rajibahmed** [comment]
I am using latest macOs safari and chrome ... I am scrolling with keyboard and clicking the button.
Works fine.

**Comment by cho-is** [comment]
@tyurderi I will provide specific versions in a couple of hours. 
@rajibahmed scrolling with keyboard should be fine, since is a step scrolling. It happens with mouse wheel, magic mouse or tap pad, it does an ease out scrolling.

**Comment by iCaio** [comment]
Can not reproduce using MacOS 10.11.6 and Chrome Version 56.0.2924.87 (64-bit), but I can do it on a iPhone using iOS 10.2.1 and latest Chrome.

**Comment by posva** [comment]
This is probably intended by OS X because you can stop the scrolling by clicking but since it's scrolling so fast, it's better to prevent the click and stop the scrolling than triggering a click.
Here's the example without Vue: https://jsfiddle.net/posva/nwom3jqk/
