### ISSUE TITLE
vuex problem?

### ISSUE THREAD

**Issue by ckken** [vuejs/vue#5079]
I use vuex in page and component and when unregisterModule,throw object not undefined,must add settimeout to fixed it
``````
beforeCreate(){
            this.$store.registerModule('admin_ticket',store)
        },
        destroyed(){
            setTimeout(()=>{
                this.$store.unregisterModule('admin_ticket')
            })
        },
``````

**Comment by LinusBorg** [comment]
Please open an issue in the vuex repository.

Also, please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
