### ISSUE TITLE
VNodeData interface broken

### ISSUE THREAD

**Issue by znck** [vuejs/vue#5080]
## Version
2.2.1

## Reproduction Link
[https://jsfiddle.net/dn61kvxw/1/](https://jsfiddle.net/dn61kvxw/1/)

## Steps to Reproduce
- Observe output

## What is expected?
`v-model` directive expression should be accessible.

## What is actually happening?
`directives` list not found in `VNodeData`.

Working example with v2.1.10: https://jsfiddle.net/dn61kvxw/2/

**Comment by yyx990803** [comment]
Ok, this is because in 2.2 `v-model` on component is now passed down as part of VNode's data instead of as a directive. So `<child v-model="foo">` is compiled into something like this:

``` js
h('child', {
  model: {
    value: foo,
    callback: function ($$v) { foo = $$v }
  }
})
```

Is there any particular reason you need access to the expression?

**Comment by znck** [comment]
I have a form implementation where `<form-component>` provides `errors` object and `<input-*>` components can get validation errors from the injected `errors` object. Validation errors are keyed by the expression.

```vue
...
<input-text v-model="attributes.name" />
...
// errors.get('name') would return validation errors for `name` attribute. 
```

**Comment by yyx990803** [comment]
I've added the raw expression in 12870be

You should be able to access it as `this.$vnode.data.model.expression`

**Comment by berniegp** [comment]
The `model` property is not defined in the `VNodeData` interface here:
https://github.com/vuejs/vue/blob/982d5a492fb95577217e2dacaa044eabe78a8601/types/vnode.d.ts

Should it be formally added there so we can depend on its presence?
