### ISSUE TITLE
Select element's value isn't updating when the selected option disappears from the DOM using "v-if" filtering

### ISSUE THREAD

**Issue by temporaryaccount** [vuejs/vue#5081]
Try to change the country, the region's value remains the old one until changed manually.

When the selected option disappears from the DOM I think the select element's value should default to null (or maybe even to the first available option's value, if there is any) but certainly it shouldn't remain to the old non-existent option's value.

Vue.js version is v2.2.0

`

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
        <meta charset="utf-8">
        <script src="vue.min.js"></script>
    </head>
    <body>

        <div id="app">
            {{ message }}

            <form action="/submit">
                <select name="country_id" id="country_id" v-model="city.country_id">
                    <option v-for="country in countries" v-bind:value="country.id">{{ country.name }}</option>
                </select>

                <select name="region_id" id="region_id" v-validate="'required'" v-model="city.region_id">
                    <option v-for="region in regions" v-bind:value="region.id" v-if="city.country_id == region.country_id">{{ region.name }}</option>
                </select>

                <button type="submit">save</button>
            </form>
        </div>

        <script>
            var app = new Vue({
                el: '#app',
                data: function() {
                    return {
                        message: 'Hello Vue!',
                        city: {
                            region_id: 1,
                            country_id: 11
                        },
                        countries: [
                            {id: 11, name: "USA"},
                            {id: 12, name: "Canada"},
                        ],
                        regions: [
                            {id: 1, name: "Texas", country_id: 11},
                            {id: 2, name: "California", country_id: 11},
                            {id: 3, name: "Alberta", country_id: 12}
                        ]
                    };
                },
                watch: {
                    'city.country_id': function(new_val, old_val) {
                        console.log('[1] old_country = ' + old_val + ', new_country_id = ' + new_val + ', region_id = ' + this.city.region_id);
                    },
                    'city.region_id': function(new_val, old_val) {
                        console.log('[2] old_region_id = ' + old_val + ', new_region_id = ' + new_val);
                    }
                }
            });
        </script>
    </body>
</html>

`

**Comment by NickolasBoyer** [comment]
Here's a fiddle if anyone is interested:

https://jsfiddle.net/zgz258w4/

**Comment by posva** [comment]
Thanks for the repro @NickolasBoyer 

> When the selected option disappears from the DOM I think the select element's value should default to null (or maybe even to the first available option's value, if there is any) but certainly it shouldn't remain to the old non-existent option's value.

Unfortunately for you, we think it's better to keep the value as it is and not changing it implicitly. Since you know when selects are changing, you should reset the value if you need it that way

**Comment by cristicVictory** [comment]
you can set the value in the "created"
