### ISSUE TITLE
Virtual DOM updates href too soon

### ISSUE THREAD

**Issue by andrejborstnik** [vuejs/vue#5083]
As the title states the ```href``` updates too soon on ```v-if``` elements that share the same Virtual DOM location. I.e. if we have two ```<a>```-s on the same level and we switch between them  by changing the  ```v-if``` variable on ```@click``` the ```href``` changes before the ```<a>``` is fully executed. Meaning that we visit the new href.

Example (we visit the wrong anchor when clicking the link):
https://jsfiddle.net/uL1do15y/2/

**Comment by LinusBorg** [comment]
You have to key those elements. Look up the key attribute in our guide to see an example

**Comment by posva** [comment]
because otherwise they get reused to make the app faster and can create some curious race conditions like the one you sown

**Comment by andrejborstnik** [comment]
Thank you for the suggestions, I know how to work around it. I just noticed the problem and I consider it a bug, as the changes that any event triggers should not affect its normal execution, unless explicitly coded. Here the event target (contents) was (were) changed by vue during execution.
