### ISSUE TITLE
Missing state of expected <Todo> when deleting another <Todo>

### ISSUE THREAD

**Issue by tyurderi** [vuejs/vue#5087]
### Vue.js version
2.2.0

### Reproduction Link
https://jsfiddle.net/u5cvsqk3/

### Steps to reproduce
1) Click on the "x"-Button on the first and the last todo. Then click on the "Yes"-Button showed at the first todo.
2) Click every "x"-Button for every todo and then click on the "Yes"-Button of the first todo.

### What is Expected?
1 & 2) The first todo should be deleted from the list. 

### What is actually happening?
1) The expected behavior and the delete-question at the last item gets hidden but it should not!
2) The expected behavior and the delete-question from the second todo gets hidden.

Am I doing something entirely wrong? I don' think so, thats why I am opening this issue.

**Comment by posva** [comment]
You need to key the `li` element: `<li v-for="todo in todos" :key="todo.label">` so the v-for rerender reuse correctly existing components
