### ISSUE TITLE
Global mixins cause memory leak in SSR

### ISSUE THREAD

**Issue by MopTym** [vuejs/vue#5089]
### Vue.js version

2.x.x

### Reproduction Link

https://github.com/vuejs/vue-hackernews-2.0

### Steps to reproduce

1. Clone the repo

2. Add the code below to `src/app.js`
```js
Vue.mixin({
  created () {}
})
```
![code](https://ws1.sinaimg.cn/large/ddf13c1dly1fdaxzqx3p2j20k50djdg4)

3. `npm i && npm run build`

4. `npm start`

5. Run a stress test: `ab -n 1000 -c 10 http://127.0.0.1:8080/`

### What is Expected?

No global mixin:

![result](https://ws1.sinaimg.cn/large/ddf13c1dly1fdaxzr0y7jj20m20gstb2)

![result](https://ws1.sinaimg.cn/large/ddf13c1dly1fdaxzqyyx0j20m10593z8)

### What is actually happening?

With global mixin:

![result](https://ws1.sinaimg.cn/large/ddf13c1dly1fdaxzqyzmqj20m106qjsf)

![result](https://ws1.sinaimg.cn/large/ddf13c1dly1fdaxzqxgsjj20m107vjsk)

**Comment by yyx990803** [comment]
This is because Vue is externalized, so each request you are adding a new mixin to the same copy of `Vue`. See https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#externals-caveats.

Calls to `Vue.use(plugin)` are fine **if the plugin is also externalized**, since Vue will check if the plugin is already installed.

Simple fix is adding a flag on `Vue` to make sure you only apply the mixin once.

Or, avoid using global mixins in application code if you can. They are meant for plugins.

**Comment by buddyff** [comment]
I've the same problem.. could you fix it ?

**Comment by hvalcourtSerdy** [comment]
Is it possible to put an exemple of correct code here ?

**Comment by manniL** [comment]
@yyx990803 Is it still an issue the current `vue-server-renderer` version (and `runInNewContext: false` by default?

**Comment by zhangtinghai** [comment]
> This is because Vue is externalized, so each request you are adding a new mixin to the same copy of `Vue`. See https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#externals-caveats.
> 
> Calls to `Vue.use(plugin)` are fine **if the plugin is also externalized**, since Vue will check if the plugin is already installed.
> 
> Simple fix is adding a flag on `Vue` to make sure you only apply the mixin once.
> 
> Or, avoid using global mixins in application code if you can. They are meant for plugins.

function mergeAssets (
  parentVal,
  childVal,
  vm,
  key
) {

  var res = Object.create(parentVal || null);
/*
Here is the reason of memory leak. 

The code below can fixed this reason:

var res = Object.create(null);
extend(res, parentVal)

*/

  if (childVal) {
    assertObjectType(key, childVal, vm);
    return extend(res, childVal)
  } else {
    return res
  }
}
