### ISSUE TITLE
About $watch() and unwatch()

### ISSUE THREAD

**Issue by GloriaCHL** [vuejs/vue#5090]
### Vue.js version
2.0.2

### Steps to reproduce
<https://jsfiddle.net/gloriaCHL/qvpdr9ud/>
### What is Expected?
I want to stop the previous callback and then create a new $watch, The new $watch should call the latest callback. 
### What is actually happening?
I use $watch to some data when the app mounted, and then I call unwatch() to unbind the $watch, after that I do a $watch again. I hope call a new callback not the previous. In fact, It not only call the new $watch callback, also call the previous $watch again.

**Comment by LinusBorg** [comment]
That doesn't seem to be the correct jsfiddle. It doesn't use $watch or unwatch()

**Comment by GloriaCHL** [comment]
Oh, I'm sorry! I forgot click update yet! I am not usually use jsfiddle. I had found the problem. It's my miss. Thank you for your comment!
