### ISSUE TITLE
Feature Request: define component get/set

### ISSUE THREAD

**Issue by neves** [vuejs/vue#5096]
# I want to use getters/setters like computed properties, but without cache/reactivity

### [DEMO](http://codepen.io/neves/pen/pebVWM)

The docs states here https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods that to avoid computed caching, I should use a method. So, instead of this:
```javascript
export default {
  computed: {
    now () {
      return Date.now()
    }
  }
}
```
I should use this:
```javascript
export default {
  methods: {
    now () {
      return Date.now()
    }
  }
}
```

But a solution I found for this specific case was to do this: (define a getter within the data)
```javascript
export default {
  data: () => ({
    get now () {
      return Date.now()
    }
  })
}
```

The problem with that, is `this` points to the data object, not the Vue instance.
```javascript
export default {
  data: () => ({
    get position () {
      return this.$el.selectionStart // this refers to the data object
    }
  })
}
```
So I defined the get like this:
```javascript
export default {
  get position () { // this.$options.position
    return this.$el.selectionStart
  }
}
```
But position is evaluated while vue is coping it to $options, so `this` points to where it was defined.

At my demo, I had to create a `accessors` property cause the original property descriptor is lost when copied to $options.

Using accessors property to organize the getters/setters is easy to implement at user land. But I think it would be shorter and cleaner to implement direct at the vue object template.

**Comment by andreiglingeanu** [comment]
> The problem with that, is `this` points to the data object, not the Vue instance.

<details><summary>problematic example</summary><p>

```javascript
export default {
  data: () => ({
    get position () {
      return this.$el.selectionStart // this refers to the data object
    }
  })
}
```

</p></details>

Well, define your `data` like this in order to have access to the Vue instance:

```javascript
  data () {
    let vm = this;

    return {
      get a () {
        // here is your actual Vue instance
        console.log(vm);
        return 1;
      }
    };
  }
```

[Working demo](https://jsfiddle.net/andreiglingeanu/txvLum28/1/)

**Comment by posva** [comment]
Unfortunately, there's no gain from adding that syntax and you can already achieve it with methods, so we rather not introduce a new syntax for something that already exists without any benefits.
If you still want to use the getter syntax, you can use the solution provided by @andreiglingeanu

**Comment by neves** [comment]
@posva Is there any way to have access to the original object used to populate $options?
In this [DEMO](http://codepen.io/neves/pen/yMJRXg?editors=1010) I simulate a `.original` property of $options, but is there other way to get that?

Thanks @andreiglingeanu, that was very clever 👍

**Comment by posva** [comment]
No, but you should be fine by using the `$options` property. I don't know why you want to rely on the original options object but you probably should avoid that

**Comment by neves** [comment]
@posva Sorry my example was not clear enough.
In this code, how can I have access to the `now` getter inside $options?
```javascript
export default {
  get now () { // $options.now is not the getter, but the result of now
    return Date.now()
  }
}
```
That's why I *want to rely on the original options object*.

**Comment by posva** [comment]
You can 

```js
Object.getOwnPropertyDescriptor(this.$options.data(), 'a')
// or maybe
this.$options.data().a
```

**Comment by neves** [comment]
@posva You've mistake my example with @andreiglingeanu 
How can I use Object.getOwnPropertyDescriptor to get the **now** getter from $options (it's not on data)
```javascript
export default {
  get now () { // $options.now is not the getter, but the result of now
    return Date.now()
  }
}
```

**Comment by andreiglingeanu** [comment]
@neves You better introduce one more function and reuse it:

```javascript

export default {
  get now() {
    return generateDate();
  }
}

// you can use this function anywhere else, for reusability
function generateDate() {
   return Date.now();
}
```

This is better comparing with accessing `this.$options` because it is more transparent and you can easily reuse small helpers like that in other components.

**Comment by posva** [comment]
@neves You can apply the getOwnProperty on that plain javascript object. It won't work on `$options` thought.

**Comment by neves** [comment]
Thanks @andreiglingeanu for the great help. I just wanted to be sure that there wasn't a way to access the original object.

**Comment by neves** [comment]
I just found this, maybe can help me
https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies
