### ISSUE TITLE
ssr problem tag <time> with filter

### ISSUE THREAD

**Issue by djvonavi** [vuejs/vue#5098]
this problem only on Safari mobile `[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. `
see code

html: `<time v-if="item.dates && item.dates.created" style="    margin-left: 5px;" class="date post-date"
											:datetime="item.dates.created|timeList">{{item.dates.created|timeList}}</time>`
filter: ```Vue.filter('timeList', function (time) {
			console.log(time)
			var toRet = '--:-- --/--/--';
			try {
				var timeArr = time.split('T');
				var left = timeArr[0].split('-');
				var right = timeArr[1].split('.')[0].split(':');
				var toRet = ''+ right[0] + ':' + right[1] + ' ' + left[2] + '/' + left[1] + '/' +left[0];
			} catch (e) {

			}
			return toRet;
		});```
warn: Parent
```<time datetime="08:36 25/01/2017" class="date post-date" style="margin-left:5px;">08:36 25/01/2017<a href="tel:36 25/01/2017">36 25/01/2017</a></time>```
what?? Carl!!! `a href="tel:"`?????
Anybody takes same issue?

**Comment by djvonavi** [comment]
UPDATE:
`<meta name="format-detection" content="telephone=no">`
this trick worked, but it no-good(

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
If you have a question or need help debugging your code, we encourage you to ask on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first.
If you're reporting a bug, make sure to provide a **minimal** reproduction in a jsfiddle or github repo.
Thanks!
