### ISSUE TITLE
When I use v-if and v-else that all include v-for. There is something wrong when the page rendered

### ISSUE THREAD

**Issue by dupeiduo** [vuejs/vue#5100]
**Vue.js version**

2.2.1

**Reproduction Link**

[https://jsfiddle.net/rwe9tz0n/1/](https://jsfiddle.net/rwe9tz0n/1/)

**Steps to reproduce**

I use v-if and v-else in a table. When switch between if else conditions it doesn't work as I wish. When go v-else the page printed undefined. When I use double v-if. It works well.

**Comment by fnlctrl** [comment]
Please make sure to follow [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines), and provide a reproduction on jsfiddle/codepen etc.

**Comment by LinusBorg** [comment]
..and use a key attribute (see docs for info).

**Comment by ccforward** [comment]
https://jsfiddle.net/ccforward/rwe9tz0n/2/

You'd better use a `template` to wrap the `v-if` and `v-else`

**Comment by posva** [comment]
https://vuejs.org/v2/guide/list.html#v-for-with-v-if

**Comment by znck** [comment]
Using `v-if` and `v-for` on same element:

```
<tr v-if="useA"  v-for="item in list">{{item.first}}</tr>
```

is equivalent to:

```
for (item in list) {
  if (useA) {
    // create <tr> element.
  }
}
```

if using `v-else`:
```
for (item in list) {
  else {
    // create <tr> element.
  }
}
```

which does not make any sense.

--------

Use [forum](forum.vuejs.org) for further questions.

**Comment by dupeiduo** [comment]
@znck  Thanks. I got it.
