### ISSUE TITLE
props not restore to default

### ISSUE THREAD

**Issue by callnothing** [vuejs/vue#5105]
i am using vue2.0.
i pass params by props, but when i fresh the browser, the props var are not restore to default.

**Comment by kazupon** [comment]
Thanks for filing the issue! 
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
