### ISSUE TITLE
children nodes can't  change parent's v-if  but other nodes can 

### ISSUE THREAD

**Issue by kinsliy** [vuejs/vue#5107]
<div>
  	  	 <div @click='change(item)'>
  	  	 	 <span>户型</span>
  	  	 	 <span>{{item.title}}</span>
  	  	 	 <span><img v-bind:src="item.img"></span>

  	  	 	 <div class='tip1' v-if='item.flag' >
  	  	 	 	 <div @click='pick(item,"户型1")'>户型1</div>
  	  	 	 	 <div @click='pick(item,"户型2")'>户型2</div>
  	  	 	 	 <div @click='pick(item,"户型3")'>户型3</div>
  	  	 	 </div>
  	  	 </div>
  	  	 <div>
  	  	 	 <span @click='pick(item,"户型2")'>面积</span>
  	  	 	 <input type="text" >
  	  	 	 <span class='span2'>平方米</span>
  	  	 </div>
  	  </div>

    methods:{
		 	  change(item){
		 	  	  item.flag=true;
		 	  },
		 	  pick(item,title){
                 
                 item.title=title;
                 item.flag=false; 
		 	  },
		 	  
		 }

           item.flag=false  not  work??

vue-v    2.1.6

**Comment by fnlctrl** [comment]
Hi, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Thanks!
