### ISSUE TITLE
Disabling warnings about inline value attributes for v-model on select

### ISSUE THREAD

**Issue by oliverpool** [vuejs/vue#5112]
### Vue.js version
2.2.0

### Reproduction Link

http://jsfiddle.net/wdgfnn0h/3/

### Steps to reproduce

Create a `<select v-model="value">` tag with a selected option: `<option selected>Value</option>`.

### What is Expected?

I expect not warning because in my app, I initialize the Vue values with the values extracted from the HTML (to keep a no-js compatibility). 
This has been discussed in https://github.com/vuejs/vue/issues/4733 and implemented in https://github.com/vuejs/vue/pull/4770

### What is actually happening?

A warning is shown in the console:

> [Vue warn]: Error compiling template:
> ```html
> <div id="app">
> <select v-model="first">
> <option value="0">option0</option>
> <option value="1" selected="">option1</option>
> </select>
> </div>
> ```
> - `<select v-model="first">`:
> inline selected attributes on <option> will be ignored when using v-model. Declare initial values in the component's data option instead.

**Comment by ccforward** [comment]
If you want the second option to be selected default, I suggest you remove the `selected` attribute nad set your data to be 

```js
data: {
  first: "1"
}
```

operate data not DOM

**Comment by oliverpool** [comment]
I want my form to still display fine if JS is disabled.
