### ISSUE TITLE
Not able to use lodash or jquery inside interpolations in .vue files

### ISSUE THREAD

**Issue by pixieaka** [vuejs/vue#5113]
https://github.com/JeffreyWay/laravel-mix/issues/417

![capture](https://cloud.githubusercontent.com/assets/17777237/23619863/b34b0104-029d-11e7-936b-a7b7f8bbf366.JPG)

**Comment by Akryum** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

[Why is this required?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Do `Vue.prototype._ = _` to use lodash as `$_` in templates. But I recommend you to define your own filters/methods that use lodash methods instead
