### ISSUE TITLE
Feature: transpile inline templates like vue-templates transpiled

### ISSUE THREAD

**Issue by martinoppitz** [vuejs/vue#5114]
History: https://github.com/vuejs/vue/issues/5108

Hello @fnlctrl,

why does that work. Because the vue-loader compiles a inline template to functional render function.

See https://github.com/krausest/js-framework-benchmark/issues/138
> The vue-keyed implementation already appears to translate the template to javascript like angular aot does (look at vue/dist/main.js). So I don't think anything can be gained by manually implementing the render function.

...

I would like transpile the inine template as vue-files will be compiled.

*How does it works?*

**Comment by martinoppitz** [comment]
**Before**
```js
Vue.component('my-tag', {
  data() {
    return ...;
  },
  methods: {
    ...
  },
  template: `<div v-if="" v-for="" :bind="whatEver"></div>`
});
```

**After**
```js
Vue.component('my-tag', {
  data() {
    return ...;
  },
  methods: {
    ...
  },
  render(h, c) {
    let markup = [];
    for() {
      if () {
        markup.push(h('div', {
        }));
      }
    }
    return h('div', {
      
    });
  }:
});
```

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/issues/5108#issuecomment-284626967

Please don't open new issues for closed ones.

**Comment by martinoppitz** [comment]
Sorry, I cant reopen
