### ISSUE TITLE
e.util.isObject is not a function

### ISSUE THREAD

**Issue by pbwei** [vuejs/vue#5119]
var logError = function (err) { console.error(err); };

426行

**Comment by znck** [comment]
`Vue.util.isObject` is not part of public API. You should not be using it.

------
Provide minimal reproduction code using JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with this [template](http://jsfiddle.net/df4Lnuw6/) that already includes the latest version of Vue.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**
