### ISSUE TITLE
A input bug in ios 10.2.1 safari

### ISSUE THREAD

**Issue by xiguaxigua** [vuejs/vue#5122]
### Vue.js version
2.1.10

### Reproduction Link
http://codepen.io/quietcoder/pen/jBVbVm

### Steps to reproduce
Enter some characters and delete them.

### What is Expected?
When the input from no characters to have some characters, when deleted from some characters to no characters.

### What is actually happening?
Sometimes, when I delete all the characters, there will leave a space, and this space can be deleted, if you enter some other characters, then the space will be replaced.

**Comment by xiguaxigua** [comment]
At the same time, you can also see the bug [here](http://code.daxigua.me/bug.html) to reproduce with your safari in ios

**Comment by yyx990803** [comment]
This seems to be a bug of iOS which has to do with how it handles `<input>` updates when there is other DOM updates in a microtask. Same behavior can be reproduced without Vue involved: https://jsfiddle.net/2231q1te/

I don't really think there's anything we can do in Vue, maybe you can open a bug in iOS Safari instead :/

**Comment by Aarbel** [comment]
@xiguaxigua did you found a way to fix this problem ?

**Comment by xiguaxigua** [comment]
@Aarbel I didn't found any way to fix it.
