### ISSUE TITLE
slot feature problem

### ISSUE THREAD

**Issue by Batur24** [vuejs/vue#5128]
### Vue.js version
2.0.2

### Reproduction Link

https://jsfiddle.net/baturYe/0z3682u8/
### What is Expected?
slot display correctly, and no error occur
### What is actually happening?
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` and slot display incorrectly when use jsfiddle vue version

if I use External Resources, http://vuejs.org/js/vue.min.js slot display differently but still incorrectly, the `child title` does not display

**Comment by yyx990803** [comment]
Your usage is wrong (registering an instance as a component). Please read the component section of the docs carefully.

**Comment by ccforward** [comment]
In your code 

```js
Vue.component(vm.name, vm);
```

`vm.name` is undefined.

**Comment by Batur24** [comment]
@yyx990803 @ccforward Thank you! Sorry, I mixed component and instance.
