### ISSUE TITLE
一个关于vue-cli的问题

### ISSUE THREAD

**Issue by baoxianggao** [vuejs/vue#5131]
用官方提供的vue-cli创建一个基于webpack的项目，配置中build的路径好像是少了一个‘.’ 导致npm run build出来的文件路径存在问题，问题定位在./config/index.js的第十行，这里的assetsPublicPath: '/'应该是assetsPublicPath: './'，想问一下作者这个是cli的bug还是单纯我这边存在这个问题

**Comment by Kingwl** [comment]
Hi!
Please make sure to follow the Issue Reporting Guidelines before opening an issue.
If you have a question or need help debugging your code, we encourage you to ask on the forum or StackOverflow first.
and you should open issue at https://github.com/vuejs/vue-cli/

**Comment by yyx990803** [comment]
build 时候的信息已经说了，build 出来的文件需要用 http server 来 serve...
