### ISSUE TITLE
scoped slots in v-for was parsed as slots

### ISSUE THREAD

**Issue by zuomingcai** [vuejs/vue#5133]
with the following template:
```
           <template :slot="'action-template'" scope="ctx">
                <a href="#">edit</a>&nbsp<a href="#">delete</a>
            </template>
            <template v-for="field in fieldList">
                <template :slot="'sex-template'" scope="ctx">
                    <div>sss</div>
                </template>
            </template>
```

    we print the slots with the following statement:
```
        console.log(this.$slots);
        console.log(this.$scopedSlots);
```

   and found sex-template in this.$slots but not in this.$scopedSlots;
while action-template was correctly parsed.

### Vue.js version
2.1.10

**Comment by yyx990803** [comment]
A scoped slot is like a reusable function, it doesn't even make sense to nest it inside a `v-for`...
