### ISSUE TITLE
Vue packages version mismatch - vue@2.2.1 / vue-template-compiler@2.2.2

### ISSUE THREAD

**Issue by gilsonsouzah** [vuejs/vue#5141]

**Comment by cyy0418** [comment]
![image](https://cloud.githubusercontent.com/assets/2883079/23735581/60f23578-04c1-11e7-833c-2b7d60ea0606.png)

**Comment by sunlei33** [comment]
checkout the version check in vue-template-compiler, I don't think string compare is a proper idea.

**Comment by znck** [comment]
Try `yarn add vue@^2.2.2 vue-template-compiler@^2.2.2`

**Comment by BarronLin** [comment]
Change "vue-template-compiler": "^2.2.1" to "vue-template-compiler": "^2.2.0"

**Comment by panwenhua** [comment]
Just reinstall it again.

**Comment by sunlei33** [comment]
open the [PR](https://github.com/vuejs/vue-loader/pull/702) for vue-loader, when version check fails, the loader should fail and webpack return error.

**Comment by yyx990803** [comment]
Somehow the release script didn't successfully publish Vue core 2.2.2 - should be fixed now, just reinstall.
