### ISSUE TITLE
v-model 问题

### ISSUE THREAD

**Issue by lesini** [vuejs/vue#5148]
input type=text   中文输入法输入 输入完 直接点击另外一个input 无法绑定到data上相应的值 （ios 必现）

**Comment by 2046** [comment]
中文输入法导致 v-model 的值不更新

代码：http://jsbin.com/robetuzuxo/edit?html,js,output
demo: http://output.jsbin.com/robetuzuxo

当用手机浏览器打开 demo 后，点击 input 输入框，切换至中文输入法，随便输入，然后直接点击 submit 按钮（不要点击完成或者 done），发现 v-model 的值没有更新，但是通过原生方法找到 input 的 value，发现 value 值是更新过的，这种情况要怎么处理？目前我们的解决方案是重新封装一个 input component 出来，但是以前的上线的全部业务现在出现这种情况，直接导致业务不可用了，望尤大能给一个好的解决方案

**Comment by ccforward** [comment]
@2046   说下你的系统和浏览器的型号、版本吧

我在  iOS 10.2.1 的 Safari、微信、UC 上直接点submit打开是可用的

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
