### ISSUE TITLE
When I use `slot` in latest version, it alwas has an error "Uncaught ReferenceError: testSlot is not defined"

### ISSUE THREAD

**Issue by TingYinHelen** [vuejs/vue#5149]
As the title says, when I use `slot` in latest version, it always says "testSlot is not defined".
This is my demo https://jsfiddle.net/HelenYin/ntg87c6m/
If I use another version it will be right: http://codepen.io/HelenYin/pen/ZeLGjO
I promise I read the latest API.

**Comment by posva** [comment]
Please next time ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first. Issues are for bug reports and feature requests only.

---

https://jsfiddle.net/posva/dhuo9hfn/
