### ISSUE TITLE
Can't use internal component tag: <component></component> in render function

### ISSUE THREAD

**Issue by daihere1993** [vuejs/vue#5152]
### Vue.js version
2.2.1

### My code
```js
const hello = {
  template: '<h1>Hello Vue!</h1>'
}

export default {
  name: 'render',
  data () {
    return {view: hello}
  },
  render (h) {
    return (
      <component is={ this.view }></component>
    )
  }
}
```

### Browser error
"Unknown custom element: \<component> - did you register the component correctly?"

 ********************** ********************** ********************** **********************
So, guys, any error of my code?

**Comment by posva** [comment]
If hello is the component object, you should be able to do:

```jsx
const Component = this.view
return <Component />
```

I didn't see this anywhere in the docs nor in the https://github.com/vuejs/babel-plugin-transform-vue-jsx. I think it's worth adding to the docs, showing how to implement the anchored heading example. wdyt @chrisvfritz

**Comment by daihere1993** [comment]
@posva Yeah, get it. 
thx bro!

**Comment by yyx990803** [comment]
Let's move this to the docs repo.

**Comment by Mouvedia** [comment]
@yyx990803 where exactly is this explained ?
