### ISSUE TITLE
Feature Request: Vue Native

### ISSUE THREAD

**Issue by sdras** [vuejs/vue#5153]
This is a big ask, I know- I was wondering if there were any plans in place to create something like React Native for Vue. I have come into a couple of situations where clients want an app to compliment the site and I'd *love* to not have to move over to another tech stack and rebuild or pair with a different team to do so.

Totally understandable if this is out of scope, I know that's a big undertaking. Thanks for your time!

**Comment by Akryum** [comment]
An official Vue Native solution will come soon with [weex](https://medium.com/the-vue-point/vue-in-2016-8df71d98bfb3#9365).

**Comment by posva** [comment]
btw, the git repo is here: https://github.com/apache/incubator-weex

Closing since, there's nothing such as a commit or PR that will close this issue 🙂

**Comment by sdras** [comment]
Awesome! I didn't know about this. Thank you!

**Comment by smolinari** [comment]
Hey Sarah! 

Have a look at [Quasar-framework](http://quasar-framework.org/) too (if you haven't seen it already). It offers a [Cordova wrapper](http://quasar-framework.org/guide/cordova-wrapper.html).  

Scott

**Comment by sdras** [comment]
Great, thanks!

**Comment by irthos** [comment]
+1 for vue native. 
-1 for any webview implementation in 2017 or greater.

**Comment by ansarizafar** [comment]
+1 for vue native.

**Comment by posva** [comment]
Locking to prevent further spam.
The current solutions are Weex and, in a near future, [NativeScript](https://www.nativescript.org/blog/a-new-vue-for-nativescript)
