### ISSUE TITLE
Why Vue doesn't have a tutorial?

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [vuejs/vue#5154]
Vue's document is very clear, all the concepts have been explained clearly. When it comes to the component, I think it lags behind. If I want to understand how I will use components in a real app, I don't get a solid understanding. I know how to register them and use them, but not the complete picture. It would be good to build a simple app. When I first learnt React; `thinking in react` was very helpful. This will help newbies like me understand the data flow, sending props, how components are created easier.

I hope this is the right place to request for this.

> Edit

Even Single File Components are not clear for me to use

**Comment by znck** [comment]
Please recreate this issue on https://github.com/vuejs/vuejs.org repository.
