### ISSUE TITLE
this.$el is a comment when using v-if on root element

### ISSUE THREAD

**Issue by milimetric** [vuejs/vue#5156]
If you're using v-if on a root element, and the condition of the v-if is false when your `created` event fires, then `this.$el` will be a comment element instead of the root you might expect.  This makes sense, but might be as confusing to others as it was to me.  Some warning in the documentation or on template compilation might be useful to others.  Example:

```
<template>
<div v-if="thisLoadsAsyncButIsFalseNow">
...
</div>
</template>

<script>
export default {
    created () {
        console.log(this.$el) // this might log correctly if your browser interprets it after the async update, but it's a comment node when the created event fires
    }
}
</script>
```

**Comment by LinusBorg** [comment]
Yes, this is expected behaviour, Vue needs *some* root node, and falsl back on a comment if your code doesn't provide a real one. 

If you think this should be made clear in the docs, please open an issue in the website's repository at github.com/vuejs/vuejs.org

**Comment by Rolice** [comment]
That is fine, but when the element is added to the the DOM (v-if is evaluated to `true`), it should update `this.$el` to that element, isn't it the correct behavior?

**Comment by darkiron** [comment]
I have the same issue on IE 11 without `v-if `on `mounted` event 
is expected behavior ?

**Comment by damien-roche** [comment]
^^ same without `v-if` on `mounted` event in production *only* (works fine in dev). Fun times :+1:

**Comment by koga73** [comment]
> ^^ same without `v-if` on `mounted` event in production _only_ (works fine in dev). Fun times 👍

For me vue was in production which is why I didn't see the actual error. One of my templates wouldn't compile in IE11 due to syntax problem

**Comment by Jason7158** [comment]
> > ^^ same without `v-if` on `mounted` event in production _only_ (works fine in dev). Fun times 👍
> 
> For me vue was in production which is why I didn't see the actual error. One of my templates wouldn't compile in IE11 due to syntax problem

Helps a lot!
