### ISSUE TITLE
vue-template-compiler do not have version 2.2.2

### ISSUE THREAD

**Issue by pinghe** [vuejs/vue#5157]
Module build failed: Error:

Vue packages version mismatch:

- vue@2.2.2
- vue-template-compiler@2.2.1

npm i  vue-template-compiler@2.2.2

output:  2.2.2 invalid

**Comment by yyx990803** [comment]
It is available:

```
$ npm view vue-template-compiler version
2.2.2
```

It's possible that you are using a registry that hasn't been fully synced.

**Comment by pinghe** [comment]
npm get

~~~~
; cli configs
metrics-registry = "https://registry.npmjs.org/"
~~~~

npm view vue-template-compiler version

~~~~
2.2.2
~~~~

npm i vue-template-compiler

~~~~
`-- vue-template-compiler@2.2.1
~~~~

npm i vue-template-compiler@2.2.2

~~~~
`-- vue-template-compiler@2.2.2  invalid
~~~~

**Comment by pinghe** [comment]
Ooh，My apologies - there was a typo in package.json. 

To confirm: ^2.2.1
