### ISSUE TITLE
use Newest vue-cli build project can't loader the  css style from the .vue file 

### ISSUE THREAD

**Issue by HelTi** [vuejs/vue#5160]
the App.vue <style></style> can loader .but I write components and  import the component  into App.vue.
Visit the website the <style type="text/css"></style> is blank . But the App.vue <style>.....</style> have style content ! 
why?

**Comment by znck** [comment]
Please move this issue to [vue-loader](github.com/vuejs/vue-loader).

**Comment by HelTi** [comment]
thanks
