### ISSUE TITLE
updateChildren throw error if bind key is an object

### ISSUE THREAD

**Issue by shjyh** [vuejs/vue#5167]
### Vue.js version
2.2.2

### Reproduction Link
https://jsfiddle.net/8azt2xz9/3/
and click `filter`, vue.js throw error `duplicate keys` error

if bind key is an object, vnode `updateChildren` algorithm has problems.
So the key is strictly required a string value?

**Comment by yyx990803** [comment]
This is expected, key should be a string or a number.
