### ISSUE TITLE
computed  not work if  it not visit data value

### ISSUE THREAD

**Issue by zhangsanshi** [vuejs/vue#5168]
### Vue.js version
2.2.1

### Reproduction Link

http://jsbin.com/bejekerawe/edit?html,js,output

### Steps to reproduce
1. click the add button much times util the computed value is 1
2. click then button,the computed value isn't increase, but `this.$data.x` value is increase

### What is Expected?
computed  value is still increase when `this.$data.x` is increase

### What is actually happening?
computed  isn't increase when `this.$data.x` is increase

**Comment by thom801** [comment]
@zhangsanshi Does this fix the issue you are having? 

http://jsbin.com/misiquwapi/1/edit?html,js,console,output

I commented out these lines in the watch block

```
       if (Math.random() > 0.5) {
         return 1;
       }
```

Do you need that portion of the code? That seems to be the issue. I don't think this is an issue with Vue but rather with your logic in the watch block. You can also see in your original example, the watch block is only being called once at the first run.

**Comment by posva** [comment]
The math return is making Vue impossible to watch for modifications. Just do this:

```js
watchData: function () {
      this.x
      if (Math.random() > 0.5) {
        return 1;
      }
      return this.x + 1;
    }
```

Also, you don't need `this.$data` just do `this.x`

Next time, please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first

**Comment by zhangsanshi** [comment]
This is a solution.But It look like strange.
How about specify it manually...
