### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by qm88888888** [vuejs/vue#5170]
I use this.$nextTick in mounted, I want to get this.$refs.chart,but it is undefined.later use hot-loader it is ok .  my English is very bad. Sorry
![image](https://cloud.githubusercontent.com/assets/18499175/23823790/19a366ca-06a5-11e7-9d24-d4480425f6ec.png)

**Comment by smolinari** [comment]
You'll want to ask this in [the Vue Forum](https://forum.vuejs.org/). The issues are only for bugs or suggestions.

Scott

**Comment by znck** [comment]
If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.

**Comment by qm88888888** [comment]
I think is a bug
