### ISSUE TITLE
v-on:keypress.enter.prevent preventing all input keys from working

### ISSUE THREAD

**Issue by dorianWB** [vuejs/vue#5171]
### Vue.js version
2.2.2

### Reproduction Link
https://jsfiddle.net/L0q7t4xj/4/

### Steps to reproduce
use v-on:keypress.enter.prevent

### What is Expected?
enter keypress events will call the given method with the default prevented

### What is actually happening?
I'm not entirely sure, but it looks like all keypress defaults are prevented and the given method is called for enter only

**Comment by Naeemo** [comment]
+1
It seems the .prevent is preventing default behavior for all keypress event(also keydown, keyup).

**Comment by amirrustam** [comment]
I'm seeing this as well in production after upgrading to 2.2.2. Seems to be a regression!

`@keydown.enter.prevent` will prevent all keys, which renders an input field unusable. 

If I'm not mistaken, there is a unit test for this: https://github.com/vuejs/vue/blob/4964b253d0dac29578458b8f1fd9dced4828be0c/test/unit/features/directives/on.spec.js#L532

But I couldn't see the test result within the CI build of the 2.2.2 release: https://circleci.com/gh/vuejs/vue/2929

**Comment by Naeemo** [comment]
Already resolved [#5169](https://github.com/vuejs/vue/issues/5169).

**Comment by amirrustam** [comment]
Nice. @posva this issue can be closed.

**Comment by anson-GH** [comment]
@keyup.enter.native="submitMETHOD"

**Comment by dev7ch** [comment]
`@keypress.13.prevent` in for in text input solved it for me

**Comment by hongsw** [comment]
@keypress.enter.prevent

**Comment by alexventuraio** [comment]
I had an issue with the enter key, after adding a tag by pressing enter key, it triggers the entire form submission.
To fix it I had to add this to the MultiSelect component `@keydown.enter.stop` and it worked just fine.
