### ISSUE TITLE
be more accurate when assigning inBrowser variable

### ISSUE THREAD

**Issue by mapleeit** [vuejs/vue#5172]
### Vue.js version
2.2.1

### problem
We need to use the server-side-render. But we simulate a `window` variable in Node Env. So it's not accurate for us to assign inBrowser with `window`.

Could this line of code 

vue/vue.runtime.common.js line: 360 AND vue-server-renderer/build.js:924:39
```javascript
var inBrowser = typeof window !== 'undefined';
```

be replaced by

```javascript
var inBrowser = typeof window !== 'undefined' && window.navigator;
```

I'm willing to make a PR if you guys think it's ok.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. The root cause is your simulating a `window` variable, and not vue's detection logic. What if next time someone simulates both `window` and `window.navigator`? Since there can be arbitrary code in a user's project, it's unrealistic for vue to cater to all of them.

**Comment by mapleeit** [comment]
Hi, @fnlctrl .  Thanks for your prompt reply.
But I'm sorry to bother you again because I really wish you to reconsider this problem again. Here are reasons:
- add this `window.navigator` will improve the compatibility of Vue. I admit that it's our inconsiderate variable definition causes this problem. But there is indeed a little unreasonable place in the code: at first, you use `typeof window !== undefined` and then `window.a.b`. and in some cases, it will report an error like `get b of undefined 'a'`. It could be better, what do you think? :)
- without any side effects.
- at last. you said what if simulate both `window` and `window.navigator`. I will tell you what happen exactly. It goes really well because I did that before. But I really can't stand the code, it's not very elegant.

I can understand you that it's unrealistic for vue to care all of this stuff. But I think it's great to make it more compatible. 99.999% to 100% is also a progress. isn't it？

**Comment by posva** [comment]
I agree with @fnlctrl, in the future someone may mock navigator and ask for a different check to make it your in **their** project

**Comment by mapleeit** [comment]
@posva 
> at last. you said what if simulate both window and window.navigator. I will tell you what happen exactly. It goes really well because I did that before. But I really can't stand the code, it's not very elegant.

I mentioned this circumstances in my last comment. There is no problem at all if someone mock the `navigator`. I did this now in my project and it's goes well. But I don't think it's a good way to fix this.

**Comment by posva** [comment]
it went well **for you**

**Comment by mapleeit** [comment]
how about this sniffing code?
```javascript
const inBrowser = (() => {
  try {
     return this === window;
  } catch(e) {
     return false
  }
})()
```
this can avoid any mock cases
