### ISSUE TITLE
Allow Conditional or Expressions on Event Handlers

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5173]
Please allow this functionality

```html
<test @click.native="subject.courses.includes(course._key) ? addSubjectCourse(subject,course) : deleteSubjectCourse(subject,course)"/>
```

so for example we want to change a function based on the conditional expression i know this is dirty but there are some use cases for it

**Comment by posva** [comment]
It already works: http://jsfiddle.net/posva/0q73c0qb/

**Comment by ralphchristianeclipse** [comment]
@posva http://jsfiddle.net/0q73c0qb/2/ it doesnt work with functions

**Comment by posva** [comment]
Dude you have a typo, it works after fixing it (increment instead of inrement)
