### ISSUE TITLE
微信浏览器 6s 10.2.1系统，5s 9.3.5 会出现卡死的现象

### ISSUE THREAD

**Issue by liujinjian1016** [vuejs/vue#5177]
1: 微信浏览器 手机 iphone6s ，系统版本10.2.1系统 的时候，当用户快速滑动页面，但是页面还没有停止下来的时候就去点击页面的click事件或者link，这个时候就会导致页面卡死，所有点击事件都失效。后来把页面中引入的fastclick去掉就没事情啦，但是会有300ms的延迟。想着引入v-tap插件，但是v-tap还是会出现页面卡死的现象。
2: 手机iphone 5s 系统版本9.3.5 微信浏览器  在一个长表单页面，多点击几次，就会导致页面所有click事件失效。  在测试的时候引入vconsole 没有发现打印出来error

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by yinxianwei** [comment]
移除cooking.conf.js内的babel-polyfill应该可以解决
