### ISSUE TITLE
there is some error in creating vue project 

### ISSUE THREAD

**Issue by Caraqin** [vuejs/vue#5178]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path D:\nodejs\sellfq\node_modules\.staging\abbrev-ab855b02
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'D:\nodejs\sellfq\node_mo
dules\.staging\abbrev-ab855b02' -> 'D:\nodejs\sellfq\node_modules\abbrev'
npm ERR!     at destStatted (C:\nodejs\node_modules\npm\lib\install\action\final
ize.js:25:7)
npm ERR!     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js
:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\nodejs\sellfq\node_mo
dules\.staging\abbrev-ab855b02' -> 'D:\nodejs\sellfq\node_modules\abbrev'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\nodejs\sellfq\node
_modules\.staging\abbrev-ab855b02' -> 'D:\nodejs\sellfq\node_modules\abbrev'
npm ERR!     at destStatted (C:\nodejs\node_modules\npm\lib\install\action\final
ize.js:25:7)
npm ERR!     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js
:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\nodejs\sellfq\node_mo
dules\.staging\abbrev-ab855b02' -> 'D:\nodejs\sellfq\node_modules\abbrev'
npm ERR!     at Error (native) parent: 'sellfq' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\sellfq\npm-debug.log

D:\nodejs\sellfq>npm run dev

> sellfq@1.0.0 dev D:\nodejs\sellfq
> node build/dev-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\nodejs\sellfq\build\check-versions.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sellfq@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sellfq@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sellfq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sellfq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sellfq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\sellfq\npm-debug.log

**Comment by S-YOU** [comment]
It said as `Please try running this command again as root/Administrator.`

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by Caraqin** [comment]
I use github firstly.Thank you for your advice,which is very helpful for me
