### ISSUE TITLE
Binding click event in ES6 template string ?

### ISSUE THREAD

**Issue by arifhussain353** [vuejs/vue#5182]
I generate some dynamically html content where i want to call function on click `eg:- @click="test"`. I call function on click event normal way but it did not work.This `htmlContent` variable will be append somewhere dynamically.
I posted question on `stackoverflow` but no one response there also. 
[http://stackoverflow.com/questions/42761557/how-to-bind-click-event-in-es6-template-string](url)
I asked question on vue chat website also 

```javascript
let htmlCotent =`<div class="popover" role="tooltip"> <i @click="test"></i> </div>`

 methods: {
  test(){
    alert("Clcik event")
   }
},
```

**Comment by posva** [comment]
Sorry, but it's not because you didn't get an answer there that you can skip the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines). Please, don't do this again, thanks.
