### ISSUE TITLE
can not click the component with props in vue-devtools

### ISSUE THREAD

**Issue by 383514580** [vuejs/vue#5185]
### Vue.js version
2.2.4
### Vue-devtools 
3.0.5

### code
![image](https://cloud.githubusercontent.com/assets/8264787/23881396/272d1100-0895-11e7-802b-3800c156b596.png)

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/8264787/23881196/dbaaa144-0893-11e7-8c15-f5f5988cb58b.png)
'CheckboxGroup' has props, i click  'CheckboxGroup' in vue-devtools, an error occurred.

### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/8264787/23881169/b2b9e2b8-0893-11e7-9293-643a3b015192.png)

**Comment by kazupon** [comment]
Thank you for your filling!

I think this issue is vue-devtools.
https://github.com/vuejs/vue-devtools/issues/271

/ping
@yyx990803 
Please check vue-devtools issue.

**Comment by yyx990803** [comment]
Closing since the fix needs to be in the devtools.
