### ISSUE TITLE
Custom Events  name can't be camelCase

### ISSUE THREAD

**Issue by yueswing07** [vuejs/vue#5186]
### Vue.js version
2.0.2

### Steps to reproduce
reffer to : https://vuejs.org/v2/guide/components.html  custom event 
event name on the parent component  increment to incrementp this.$emit('incrementp') work ok , but increment to incrementP  this.$emit('incrementP') not work .

  <div id="counter-event-example">
    <p>{{ total }}</p>
    <button-counter v-on:incrementP="incrementTotal"></button-counter>
    <button-counter v-on:incrementP="incrementTotal"></button-counter>
  </div>
  <script type="text/javascript">
  Vue.component('button-counter', {
    template: '<button v-on:click="incrementP">{{ counter }}</button>',
    data: function () {
      return {
        counter: 0
      }
    },
    methods: {
      incrementP: function () {
        this.counter += 1
        this.$emit('incrementP')
      }
    },
  })
  new Vue({
    el: '#counter-event-example',
    data: {
      total: 0
    },
    methods: {
      incrementTotal: function () {
        this.total += 1
      }
    }
  })
  </script>

### What is Expected?
event name on the parent component , increment to incrementP,this.$emit('incrementP') work ok .

### What is actually happening?
event name on the parent component  increment to incrementp this.$emit('incrementp') work ok , but increment to incrementP  this.$emit('incrementP') not work .

**Comment by yyx990803** [comment]
Same reason for this: https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

Avoid using camelCase when using in-DOM templates.

**Comment by yueswing07** [comment]
thanks  very much!

**Comment by Noblesse89** [comment]
With vue 2.6+ it is possible to use dynamic event name even in inline templates @[event] for camel case custom event names

**Comment by djmaze** [comment]
Just dropping a reference to the official documentation here, for people searching for this issue in the future: https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

> For these reasons, we recommend you always use kebab-case for event names.
