### ISSUE TITLE
DOM listeners haven't been removed when vm is destroyed, is this expected?

### ISSUE THREAD

**Issue by xujiongbo** [vuejs/vue#5187]
### Vue.js version
2.2.1

### Reproduction Link

https://jsfiddle.net/xujiongbo/jj7vatms/3/

### Steps to reproduce
Open the link, click ```Pic1 delegate```. (sorry about that the demo is a little complicated)

### What is Expected?
<img width="680" alt="2017-03-14 11 43 37" src="https://cloud.githubusercontent.com/assets/5391892/23885025/812a7d76-08ab-11e7-93c2-b66570ebe01d.png">
As the document says,  all event listeners are automatically removed when vm is destroyed.
Image load event should not been triggered after component Pic1 is destroyed and the click event on the outermost element of Pic1 should have been removed.

### What is actually happening?
The image load event was triggered after component Pic1 is destroyed and the click event on the outermost element of Pic1 haven't been removed.

Is this a bug ? or I misread the document ?

**Comment by yyx990803** [comment]
The doc is true for 1.x for not for 2.x. We need to update it.

In 2.x we no longer remove the DOM listeners when destroying vms, since all supported browsers actually can correctly garbage-collect them.

**Comment by faylai** [comment]
> But it can slow  garbage-collect，and  make the Memory snapshot mess  up.
