### ISSUE TITLE
computed set deosn't trigger if name includes `.`

### ISSUE THREAD

**Issue by jackPanyj** [vuejs/vue#5188]
when the computed attr is like a 'a.b', it won't trigger the set method.

this is the reproduction
[demo](https://jsfiddle.net/panshao/3rzte1nL/2/)

**Comment by KidneyFlower** [comment]
I think it is because JavaScript variables's name can't include '.' .
> var a.b = 1;
// Uncaught SyntaxError: Unexpected token .

**Comment by Etheryte** [comment]
You can have object properties with periods in them.

```js
const foo = {
  'a.b': 1
}
foo // Object {a.b: 1}
foo.a === undefined // true
foo['a.b'] === 1 // true
```

**Comment by yyx990803** [comment]
In 2.x you should avoid using `this` inside templates, since when compiled the expression may be inside a nested function. This also means you should simply avoid defining computed properties with non-identifier keys.
