### ISSUE TITLE
Uncaught ReferenceError: vm is not defined in vue 2.0 for vm.$data or any other properties or methods

### ISSUE THREAD

**Issue by Jak00711** [vuejs/vue#5189]
Hello Guys, i am using vue 2.0 & i have an error when i use vm.$data or any other in console to check the properties. I have latest version of vue.js 2.2.4.
Thank you in advance

**Comment by kazupon** [comment]
Thanks for filing the issue! 
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
