### ISSUE TITLE
Slot content inside `v-if` was compiled before condition is true

### ISSUE THREAD

**Issue by jilen** [vuejs/vue#5190]
### Steps to reproduce

component: foo
```javascript
Vue.component('foo', {
  template: '<div>foo<div v-if="bar"><slot></slot></div></div>',
 	props: ['bar']
});
```
component bar
```javascript
Vue.component('bar', {
  template: '<foo :bar="bar">bar{{bar.length}}</foo>',
  data() {
    return {
      bar: null
    }
  },
  mounted() {
    this.bar = [1, 2, 3]
  }
});
```
https://jsfiddle.net/h0k3nwnb/2/
### What is Expected?
Should never call `bar.length` if `bar === null`
### What is actually happening?
It is called

**Comment by yyx990803** [comment]
There's no such guarantee. Slot content will be rendered virtually before being passed down regardless of whether it's used by the child or not. This is extremely cheap and you should not worry about it.

**Comment by simplesmiler** [comment]
You can also kinda work around that with a scoped slot: https://jsfiddle.net/h0k3nwnb/3/

**Comment by jilen** [comment]
@simplesmiler Thanks, works like a charm
