### ISSUE TITLE
no change triggered after reassigned state

### ISSUE THREAD

**Issue by Hubu** [vuejs/vue#5191]
### Vue.js version
2.2.4

### Reproduction Link
https://jsfiddle.net/orzz/ucLrrnj4/6/

### What is Expected?
state declare in root component should change and render to html
same code in vue version 2.0.0 worked as expected https://jsfiddle.net/orzz/k18o6e0f/1/

### What is actually happening?
state changed in the callback emitted by child component is not worked as expected

**Comment by Etheryte** [comment]
It will be a lot easier for anyone to help you out if you simply share your code instead of images of your code. You can base your demo off of [the Jsfiddle template included in the readme](https://jsfiddle.net/39epgLj0/), if it's easier for you.

**Comment by posva** [comment]
This may help you: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by Hubu** [comment]
@posva if i watch the var named 'varieties' it worked well

**Comment by yyx990803** [comment]
FYI, just pasting the code does not satisfy the requirement for a reproduction. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

[Why is this required?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by LinusBorg** [comment]
@yyx990803 The reproduction jsfiddle is now interactive and I'm stumped as to why it behaves the way it does. :/

Maybe it's my dizzy sunday head, btu this looks like a bug?!?

**Comment by xujiongbo** [comment]
The newly pushed watcher caused by state changes inside updated hooks haven't been called at all.
In core/observer/scheduler.js L83 to L86, the queue is cleared after all updated hooks have been called.
