### ISSUE TITLE
After I executed the command "npm run bulid"on my project of vue.js 2.x version,I executed the command "npm run dev",the localhost:8080 page showed "cannot get".

### ISSUE THREAD

**Issue by yang06061079** [vuejs/vue#5195]
Before I executed the command "npm run build",I can  debug my project on the localhost:8080 page.

**Comment by yyx990803** [comment]
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

[Why is this required?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)
