### ISSUE TITLE
Dynamic props value can't consist 'space'

### ISSUE THREAD

**Issue by stefensuhat** [vuejs/vue#5196]
I want to send component props from my view but there is a space and it make vue return me `vendor.js:695 [Vue warn]: Error compiling template: - invalid expression: :user-name="Awesome Me"
- invalid expression: :user-name="Awesome Me"`

my view:

    <ActionButton :id="1"
              :user-name="Awesome Me"
              :main="1" />
</ActionButton>

my components:

<template>
	    <div>
	        <a href="#" @click.prevent="setAsMain(id, name)" class="main tooltip"
	           :class="{primary : main == 1}"
	           :title="this.mainMessage"
	        >
	            <i class="fa fa-check"></i>
	        </a>
	    </div>
	</template>

	<script>
	    export default{
	        props: {
	            id: {
	                type: String
	            },
	            userName:{
	                type: String
	            },
	            main: {
	                type: Boolean
	            }
	        },
	        methods: {
	            setAsMain(id){
	                // some stuff
	            },
	           
	        },
	        computed: {
	            mainMessage(){
	                return this.main == 1 ? 'Main character' : '';
	            }
	        }
	    }
	</script>

How can I send the `user-name` value consist of space?

**Comment by posva** [comment]
Please, next time ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Simply pass it as a string by not binding it:

```html
<ActionButton :id="1"
          user-name="Awesome Me"
          :main="1" />
```

**Comment by lurein** [comment]
for folks that are looking for a workaround for this:
When passing a string with non-breaking spaces as a prop, I just replaced the spaces with characters unlikely to be part of the string, in my case 'zzz'
`var newName = program_name.replace(/\s/g,'zzz');`

Then, in the actual component where I need to display or use this prop, I have a computed function that undoes the above action and replaces the placeholder chars with spaces again

```
correctedProgramName(){ //this reverses the space-replacing we had to do in reporting-dashboard.js
        let correctedProgramName = this.program_name.replace(/zzz/g, ' ')
        return correctedProgramName
      }
```
