### ISSUE TITLE
why render function is called only if has children

### ISSUE THREAD

**Issue by SenYu** [vuejs/vue#5197]
### Vue.js version
2.2.4

### Reproduction Link

[https://jsfiddle.net/imsenyu/y6z73kkn/7/](https://jsfiddle.net/imsenyu/y6z73kkn/7/)

### Steps to reproduce

click button["CLICK"] and
found string("render method triggered") is outputed for 2 times in Chrome's Console

### What is actually happening?

the `render`function of the 2 component  instances of "child-2" with children node "{{Math.random()}}" is called, but the one  without children node "{{Math.random()}}" is not called

### Question

why the `render`function of the 2 component  instances of "child-2" with children node "{{Math.random()}}" is called, but the one  without children node "{{Math.random()}}" is not called;

and what will going wrong if all `render` function of the 3 component instances is not called in this case

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
