### ISSUE TITLE
 `Vue.config.errorHandler` can not catch error throw in data function

### ISSUE THREAD

**Issue by githoniel** [vuejs/vue#5198]
### Vue.js version
2.2.4

### Reproduction Link
https://jsfiddle.net/githoniel/gL3f27eg/

### Steps to reproduce
throw error in data function
### What is Expected?
 Vue.config.errorHandler can catch it
### What is actually happening?
 Vue.config.errorHandler can not catch it

**Comment by githoniel** [comment]
Is my question too plain? 
I think that  throwing error in vue instance's data function is very common. Many people may come across this problem.
In my view, it seems verbose to write try catch  in every data function.

**Comment by posva** [comment]
imo errors in data should be handled too because errors in computed are already handled

**Comment by blocka** [comment]
Apologize in advance for the hijacking, but I'm really too lazy to open a new issue...

Seems errors in directives are not caught: https://jsfiddle.net/gL3f27eg/4/

**Comment by LinusBorg** [comment]
This comment on a closed issue will likely be drowned in the stream of notifications, so don't expect this issue to be fixed.
