### ISSUE TITLE
V-Model reference a not defined property of an object not works

### ISSUE THREAD

**Issue by remalkoil** [vuejs/vue#5199]
### Vue.js version
2.2.4

### Reproduction Link

https://jsfiddle.net/1u0z2d21/2/

### Steps to reproduce
V-Model reference a not defined property of an object throws an error.

### What is Expected?
In previous version of Vue.js it was working.
For example in version 1.0.28 it's works:
https://jsfiddle.net/daoh440r/2/

**Comment by yyx990803** [comment]
This is a breaking change in 2.x.
