### ISSUE TITLE
`<transition-group>` events not working

### ISSUE THREAD

**Issue by mrcsmcln** [vuejs/vue#5200]
### Vue.js version
2.2.1

### Reproduction Link
https://jsfiddle.net/ukd699sr/1/

### Steps to reproduce
Add a event to a `<transition-group>`.

### What is Expected?
The event should fire. In the provided reproduction link, a click event is bound to the "Toggle" button, which works as expected.

### What is actually happening?
The event does not fire. Also in the reproduction link, a click event is bound to a `<transition-group>`, which does not work as expected. I don't have a thorough knowledge of Vue.js's inner workings, but it appears the event is not actually bound.

**Comment by posva** [comment]
You need to use the `native` modifier on the `click` event because it's a component

**Comment by mrcsmcln** [comment]
Huh. Thanks!
