### ISSUE TITLE
router-link active-class

### ISSUE THREAD

**Issue by sunyuanfei** [vuejs/vue#5202]
![image](https://cloud.githubusercontent.com/assets/7675592/23977180/8aaef19c-0a27-11e7-9757-bbf9e0c2aee7.png)

![image](https://cloud.githubusercontent.com/assets/7675592/23977164/781f5198-0a27-11e7-9b9d-1cb4774d7cd7.png)

not found 'active'

**Comment by sunyuanfei** [comment]
second-level directory

**Comment by yyx990803** [comment]
1. This is a vue-router issue.
2. Screenshot is not a reproduction.
