### ISSUE TITLE
v-model for inputs and objects working so bad

### ISSUE THREAD

**Issue by owl1n** [vuejs/vue#5203]
### Vue.js version
since 2.2.0

### Reproduction Link

https://jsfiddle.net/bzttj9e5/

### Steps to reproduce
Create any object and bind this as model for element. On 2.1.10 Vue version this working very well, but after updates, in input value always "[object Object]"
### What is Expected?
Raw output for object in input value
### What is actually happening?
typeof of object in value

**Comment by yyx990803** [comment]
`v-model` on text input was never designed to work directly with objects. Don't you realize the original object gets replaced by a string when you type something? You should just `JSON.stringify` the object: https://jsfiddle.net/bzttj9e5/1/

**Comment by owl1n** [comment]
okay. thx for reply. 
Stringify with pair with computed var working  very well, thx.
But, why in 2.1.10 working pretty well? Without stringify and anymore functions
