### ISSUE TITLE
Vue event and data binding is not synchronized 

### ISSUE THREAD

**Issue by whatvn** [vuejs/vue#5208]
I have a use case like this, I think it's so common:

1. Template

```html
 <div id='my-id'>
 <span v-text="msg"></span>
 </div>
```
2. I use vue-resource to load data and fill to 'my-id'

 
```javascript
methods: {
             getProductList: function () {
                 this.$http.get('/test').then(function (response) {
                     this.msg = response.data;
                 });
             }
    }
```

Then I want when `this.msg` is ready, another 3rd party script will markup `this.msg` to give it some effect, I changed the code to: 
```javascript
 mounted: function () {
            makeup();
 },
methods: {
             getProductList: function () {
                 this.$http.get('/test').then(function (response) {
                     this.msg = response.data;
                    
                 });
             }
    }
```

`makeup` function usually run before msg bind to template, if I use 

```javascript
 mounted: function () {
     setTimeout(function() {
            makeup();
     }, 1000)
 },
```

it will work, but sometime getting msg is taking too much time, and problem happen again. 

How to make sure `makeup` will run exactly after template is completed load? 

Thanks,

**Comment by znck** [comment]
Provide minimal reproduction code using JSFiddle/JSBin/Codepen to demonstrate your issue.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**

**Comment by znck** [comment]
Your issue seems usage/support question. If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.
