### ISSUE TITLE
ES6写法，this不能正常获取vue实例

### ISSUE THREAD

**Issue by chenyeah** [vuejs/vue#5211]
![image](https://cloud.githubusercontent.com/assets/22478003/24033512/34589242-0b28-11e7-9f90-ac9d3db39e65.png)

**Comment by znck** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**

/ping @fnlctrl - This is a question. Right?

**Comment by Kingwl** [comment]
add repo 
https://jsfiddle.net/z11fe07p/970/

**Comment by yyx990803** [comment]
请搞清楚 ES6 箭头函数的 this...
