### ISSUE TITLE
您好，我想问一下.vue文件的组件和在js文件中Vue.component生成的组件有什么不同？

### ISSUE THREAD

**Issue by 1994crazyboy** [vuejs/vue#5213]
我打算采用vue框架在项目中，但是作为入门初学者，对前端并不是很熟，所以想问，使用.vue文件创建的组件和在js文件中声明创建Vue.component组件有什么不同呢？因为在Java 开发工具idea中并不能识别.vue文件，之前都是使用Vue.component声明组件的。

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
