### ISSUE TITLE
vue线上打包报错，麻烦各位帮忙看下

### ISSUE THREAD

**Issue by yaqi2015** [vuejs/vue#5214]
![image](https://cloud.githubusercontent.com/assets/11505520/24050453/ce1ef65a-0b69-11e7-89c0-f33e32f796bd.png)

**Comment by kazupon** [comment]
Thanks for filing the issue! 
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.
