### ISSUE TITLE
when using raw-loader or file-loader, Failed to compile

### ISSUE THREAD

**Issue by hxl-dy** [vuejs/vue#5215]
### version
2.2.4

### reproduction link
[http://cdn.bootcss.com/vue/2.2.4/vue.min.js](http://cdn.bootcss.com/vue/2.2.4/vue.min.js)

### steps to reproduce
0. npm install --save-dev file-loader
1. config _webpack.base.conf.js_
```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.swf$/,
        loader: 'file'
      }
    ]
  }
}
```
2. import something in _someComponent.vue_
```javascript
import swf from './path/to/something.swf';
```
3. npm run dev

### what is expected?
no Error occur

### what is actually happening?
 ERROR  Failed to compile with 1 errors                                   23:26:49

This dependency was not found in node_modules:

* ./path/to/something.swf in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?
type=script&index=0!./src/components/someComponent.vue

Did you forget to run npm install --save for it?

**Comment by posva** [comment]
This has nothing to deal with Vue, you should ask the questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
