### ISSUE TITLE
v-show doesn't work on <slot>

### ISSUE THREAD

**Issue by MountLion** [vuejs/vue#5219]
### Version
2.2.4

### Reproduction link
[https://output.jsbin.com/hihoceb](https://output.jsbin.com/hihoceb)

### Steps to reproduce
See link above.

### What is expected?
v-show works on`<slot>`

### What is actually happening?
v-show doesn't work on `<slot>`

**Comment by yyx990803** [comment]
This is expected: `<slot>` is not a real element (it may expand into text nodes or multiple elements), so directives that rely on a real element like `v-show` do not work on it. Use `v-if` instead.

**Comment by WofWca** [comment]
Also, dupe/related: #3772

**Comment by mathix420** [comment]
If for whatever reason you really need v-show on slot, use this simple workaround
```vue
<div v-show="showSlot">
    <slot />
</div>
```
