### ISSUE TITLE
$serverRendered

### ISSUE THREAD

**Issue by markuplab** [vuejs/vue#5221]
### What problem does this feature solve?
Now, page (component) which rendered after server request and after browser history navigation is equal. It's mean that we can't check how user navigate to this endpoint.
Key problem:
After server request we use vuex cache, and don't make any API calls, but if we came from other page we should do it. On store level we should validate requests like here - https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/store/index.js#L59 

Cache control is very hard way and better control it's on view layer.

### What does the proposed API look like?
Add flag $serverRendered for all components that rendered on served and not updated on client, then you can on any hook make decision - do or not do request to API.

**Comment by posva** [comment]
Can't you add it yourself by using the `$isServer` property in the mounted and/or updated hooks?

**Comment by markuplab** [comment]
No, it's should not work, because mount called twice, at server render and after hydration on client.

**Comment by posva** [comment]
I don't see the issue about the mounted hook being called more than once.
Do you need to know if the user reloaded the page (server request) or if he just navigated within the SPA? if that's the case you don't need anything vue specific, [Nuxt](https://github.com/nuxt/nuxt.js) managed to get it working. If that's not it, can you please explain it better?

**Comment by markuplab** [comment]
I check nuxt code, it's ok but look not so elegant.
