### ISSUE TITLE
Provide isn't reactive with a single array

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5223]
### Version
2.2.4

### Reproduction link
[http://codepen.io/anon/pen/VpyqEz?editors=1111](http://codepen.io/anon/pen/VpyqEz?editors=1111)

### Steps to reproduce
Create a parent and child component

Set the provide of the parent using vuex

Inject the provide of the parent to child

### What is expected?
Must be reactive

### What is actually happening?
Not Reactive

**Comment by posva** [comment]
It actually doesn't depend on Vuex. It happens with plain Vue: http://codepen.io/anon/pen/EWoMLr?editors=1111

Using a single array, nothing is tracked. But if we display another injected property (in this case bar), both are updating accordingly
