### ISSUE TITLE
全局变量或函数会导致污染的问题

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#5226]
### Version
2.2.4

### Reproduction link
[https://unpkg.com/vue/dist/vue.js](https://unpkg.com/vue/dist/vue.js)

### Steps to reproduce
而我的项目是用的vs2017 vue type来创建,并使用script标签引入vue.js,但vue.js中大量使用了全局函数,可能会导致变量污染的问题存在,建议改成自运行函数,弄一个入口函数或者对象即可

### What is expected?
建议改成自运行函数,弄一个入口函数或者对象即可

### What is actually happening?
可能会导致变量污染的问题存在

**Comment by yyx990803** [comment]
...你有仔细看文件吗，唯一的全局变量就是 Vue
