### ISSUE TITLE
`scoped slot` doesn't works well under vue@2.2.x

### ISSUE THREAD

**Issue by lynsun** [vuejs/vue#5230]
### Version
2.2.4

### Reproduction link
[http://codepen.io/sugarboy/pen/XMZWoo?editors=1010](http://codepen.io/sugarboy/pen/XMZWoo?editors=1010)

### Steps to reproduce
1  open the demo link on codepen, the default demo runs well under vue@2.1.4

2 change the version of vue to 2.2.0

3 then you can find component `v-table` with `scoped slot` doesn't render as expected and console warn throwed like：

`[Vue warn]: Property or method "age" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <App> at /Users/sunjianpeng/github/vue-pro/src/Demo.vue)`

`[Vue warn]: Property or method "operation" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <App> at /Users/sunjianpeng/github/vue-pro/src/Demo.vue)`

### What is expected?
component with `scoped slot` render well and no console warn throwed

### What is actually happening?
vue@2.2.x let us declare variable used in `scoped slot`，but in 2.1.x we doesn't need

---
the source of demo can by find in repo: https://github.com/lynsun/vue-pro

**Comment by posva** [comment]
You're simply binding the slot name while you shouldn't. Use `slot="age"` instead of `:slot`

**Comment by lynsun** [comment]
it works well now，thank u so much
