### ISSUE TITLE
Allow `this` during method calls in computed properties, i. e. mapGetters

### ISSUE THREAD

**Issue by dominik-bln** [vuejs/vue#5237]
### What problem does this feature solve?
When using mapGetters from vuex it would be nice to be able to provide the store namespace from a prop.

The use case for us is, that we have several store modules whose interfaces basically look the same. If we could provide the store namespace as a prop we could rely on that interface from a specific component without having to duplicate the mapGetters calls in all parent components that use the component.

### What does the proposed API look like?
```
computed: {
    ...mapGetters(this.storeNamespace, {'item': 'myGetter' })
}
```

See the following Codepen for a full example:

https://codepen.io/dmnk_bln/pen/yMvpLq/

**Comment by posva** [comment]
This is not possible because of how js works. You can however, do something:

```js
import { myGetter } from './my-module'
//...
computed: {
  myGetter () {
    return myGetter(this.$store.state[this.storeNamespace])
  }
}
```

Aside from that, it doesn't look like a good idea to use the prop to get to property on the state. You should save that on the state as well and have a root getter that get the information for you

**Comment by dominik-bln** [comment]
Ok, thanks for having a look, I thought there might be some way to do this.
