### ISSUE TITLE
JavaScript native click event failure in mounted

### ISSUE THREAD

**Issue by leviweili** [vuejs/vue#5240]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/7aj0bke1/2/](https://jsfiddle.net/7aj0bke1/2/)

### Steps to reproduce
1.click the gray head area popup menu
2.click test text

### What is expected?
menu disappear

### What is actually happening?
menu not disappear

---
The problem is on the IOS system
I tested the phone is iphone5s
System version is 8.1 (12B411)
Browser is QQ browser (7.3.0.2956)

**Comment by znck** [comment]
This is not caused by Vue.js

**Comment by znck** [comment]
BTW Try this - https://github.com/simplesmiler/vue-clickaway

**Comment by LinusBorg** [comment]
Closing because this is not a Vue-related Bug.

**Comment by leviweili** [comment]
Thanks for your reply ! @znck
