### ISSUE TITLE
vuejs doesn't support Sets as backing fields for binding 

### ISSUE THREAD

**Issue by amgadserry** [vuejs/vue#5241]
### Version
2.2.4

### Reproduction link
[https://github.com/amgadserry/vuejs-issue-sets](https://github.com/amgadserry/vuejs-issue-sets) or
[https://jsfiddle.net/zab31wxz/1/](https://jsfiddle.net/zab31wxz/1/)

### Steps to reproduce
click on the grey square

### What is expected?
each click should switch text between true and false

### What is actually happening?
it doesn't change text

**Comment by znck** [comment]
Could you create repro on jsfiddle/codepen?

**Comment by amgadserry** [comment]
@znck  sure https://jsfiddle.net/zab31wxz/1/

**Comment by LinusBorg** [comment]
Yes, you can't use Sets or Maps in reactive data currently. See #2410

**Comment by amgadserry** [comment]
@LinusBorg is there any intentions of supporting such data types in the future ?

**Comment by LinusBorg** [comment]
as explained by Evan in this https://github.com/vuejs/vue/issues/1319#issuecomment-162742130, we don't see the benefits big enough to justify the big changes that it would require, especially as long as native support is lacking (read: IE is still a supported platform).

Also, the problem of not being serializable is something that I don't see going away anytime soon - but that's something all store solutions will have to take into account when thinking about persistence (lcaolStorage ...)

That being said, I think it will be added some time in the future, but currently, it's not on our immediate todo-list.

**Comment by amgadserry** [comment]
@LinusBorg okay then gonna close the issue
