### ISSUE TITLE
Vue breaks setTimeout() parent scope

### ISSUE THREAD

**Issue by mariomka** [vuejs/vue#5244]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/g8480yb7/4/](https://jsfiddle.net/g8480yb7/4/)

### Steps to reproduce
Set a timeout, then initialize Vue.

### What is expected?
The timeout callback can access to parent scope variables.

### What is actually happening?
Seems like parent scope variables are copies of the original.

---
On jsfiddle run with and without Vue initialization, behavior changes.

**Comment by znck** [comment]
You've to re-query element as `innerHTML` is treated as `<template>` and new `.test` element is rendered. 

Updated fiddle: https://jsfiddle.net/g8480yb7/5/

**Comment by mariomka** [comment]
Isn't easy with more than an element.

Updated fiddle: https://jsfiddle.net/g8480yb7/7/

**Comment by mariomka** [comment]
And I could fix it if is my code, but what happens with third party libraries?

**Comment by znck** [comment]
InnerHTML of `div#app` is used as template, you should not query any element inside it until Vue app is mounted.

**Comment by mariomka** [comment]
Then I guess the solution is initialize these libraries or plugins after Vue. Thank you.
