### ISSUE TITLE
Vue component change the z-index

### ISSUE THREAD

**Issue by RoamIn** [vuejs/vue#5245]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/Roam/hcswpjcb/1/](https://jsfiddle.net/Roam/hcswpjcb/1/)

### Steps to reproduce
- Just make a vue component，write z-index in style
- Run command: `npm  run dev`，everything fine
- Run command: 'npm run build`，what a mess...my z-index value changed

I think the z-index value shouldn't be changed，because we may use the third party plugin like jQuery plugin which could use z-index. In this condition, the z-index calculation is unnecessary, and make mistakes.

### What is expected?
keep my z-index value

### What is actually happening?
my z-index changed

**Comment by znck** [comment]
External styles are not affected by Vue. Also this is not a repro 😑

**Comment by yyx990803** [comment]
This is actually an issue for the webpack CLI template - I have turned off unsafe optimizations in the latest template.
