### ISSUE TITLE
v-model does no sync when keyboard Backspace clicked in input[type="password"] & IE 9

### ISSUE THREAD

**Issue by Array-Huang** [vuejs/vue#5250]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/array_huang/9czpu10o/2/](https://jsfiddle.net/array_huang/9czpu10o/2/)

### Steps to reproduce
I can't test my code in jsfiddle with IE 9. So maybe you need to test it in the local file.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div id="app">
    <form action="">
      <input type="text" v-model="username">
      <p>{{username}}</p>
      <input type="password" v-model="pwd">
      <p>{{pwd}}</p>
    </form>
  </div>
  <script src="./vue.min.js"></script>
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        username: '',
        pwd: '',
      }
    })
  </script>
</body>
</html>
```

### What is expected?
when I input Backspace to delete any word in input[type="password"] with v-model & IE 9, it should sync like input[type="text"].

### What is actually happening?
It doesn't sync when I input Backspace.

**Comment by znck** [comment]
In most conditions these type of bugs are not caused by Vue. Still, can anyone confirm this?

/ping @vuejs/collaborators

**Comment by ktsn** [comment]
I just confirm this problem with the provided code. IE 9 emulator of IE 11 on Windows 10.
FYI, IE 10/11 don't cause this.

**Comment by Array-Huang** [comment]
Oh Ｉ forgot to tell I tested in IE 9 emulator of IE 11 on Windows 10. I don't really have an IE 9,so I can't promise that the bug can reproduce in an real IE 9.
