### ISSUE TITLE
[Feature Request] Share function reference betweeen directive hooks.

### ISSUE THREAD

**Issue by Dafrok** [vuejs/vue#5251]
### What problem does this feature solve?
The doc recommend me sharing data through a dataset of current element. But however, the dataset can't save a reference, I must create an object out of the directive hooks, it's ugly and unsafe. I thought someway to pass a reference with binding betweeen hooks is necessary.

The bad case:

```javascript
const share_ref = {}

Vue.directive('foo', {
  bind (el, binding) {
    const key = 'an_unique_key'
    share_ref[key] = e => {}
    el.dataset.key = key
    document.addEventListener('keypress', share_ref[key])
  },
  unbind (el, binding) {
    const key = el.dataset.key
    document.removeEventListener('keypress', share_ref[key])
  }
})
```

### What does the proposed API look like?
```javascript
Vue.directive('foo', {
  bind (el, binding) {
    binding.PROP_NOT_READONLY.which_to_be_shared = e => {}
    document.addEventListener('keypress', binding.PROP_READONLY.which_to_be_shared)
  },
  unbind (el, binding) {
    document.removeEventListener('keypress', binding.PROP_NOT_READONLY.which_to_be_shared)
  }
})
```

**Comment by yyx990803** [comment]
You don't have to use dataset, you can just directly attach an object to the element.

**Comment by Dafrok** [comment]
That's another point. I'm not sure if pollute the DOM element is reasonable.

**Comment by yyx990803** [comment]
@Dafrok that's actually fine as long as you keep the namespace unique and remove the reference in `unbind`.

**Comment by Dafrok** [comment]
I can not guarantee if another unpredictable directive use the same namespace on the same DOM element, it's unsafe too. Sharing reference with current binding looks more private and reasonable. That my opinion.
Anyway, thx for your explanation and hard working, if this issue does not help any more, just close it.

**Comment by Dafrok** [comment]
By the way, does that solution will be welcome to pull request to the documentation? I met someone with the same problem.

**Comment by yyx990803** [comment]
Sure, PRs are always welcome.
