### ISSUE TITLE
Provide components to immediate children

### ISSUE THREAD

**Issue by znck** [vuejs/vue#5252]
### What problem does this feature solve?
It would allow a parent components to inject a local component registration in a child component.

Consider cases like custom `<select>` component which would accept a prop `component` (name of component) to render `<option>` but then `component` should be globally registered.

### What does the proposed API look like?
```js
...
inheritComponents: true,
...
```

**Comment by Kingwl** [comment]
agreed 
but the 'functional' is similar as that
and maybe it will become more complicated

**Comment by yyx990803** [comment]
I think this is a bit too niche - you can already directly pass components as props via `$options.components.xxx`.
