### ISSUE TITLE
Selected option not working inside component

### ISSUE THREAD

**Issue by caiquecastro** [vuejs/vue#5255]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/caiquecastro/hh2bouv2/2/](https://jsfiddle.net/caiquecastro/hh2bouv2/2/)

### Steps to reproduce
I have a component, that encapsulates a select element.

When I set this value to null, the data is changed although the selected option on the select is not changed for the vue component, only for the native element.

### What is expected?
The same behavior as with native element (`<select>`).

### What is actually happening?
The variable data is changed although the selected option is not changed.

**Comment by PsychicCat** [comment]
@caiquecastro you should add `:value=value` to the select element.

example:

```
Vue.component('g-select', {
	template: `
  	<select :id="id"
            class="form-control"
            @change="updateValue($event.target.value)"
           :value="value">
        <option :value="null">Selecione</option>
        <option v-for="option in options" :value="option.id">
            {{ option[label] }}
        </option>
    </select>
```

**Comment by caiquecastro** [comment]
Thank you!
