### ISSUE TITLE
Please expose Dep in Vue.util

### ISSUE THREAD

**Issue by green-coder** [vuejs/vue#5258]
### What problem does this feature solve?

This is for users who are implementing bridges between the reactivity of VueJS and external systems which manage their own data internally and which have their own reactivity system.

Giving a way to users to access `Dep` will allow them to define a dependency in a simple way. The use case is for defining changing values from other systems (mini-mongo's reactive queries, for instance) as dependencies in watched functions.

Currently, the users can only use `defineReactive()`, which means that there should be an object and a field for the dependency to exist. It is quite painful since the only thing needed is a `const dep = new Dep()` on which we would call `depend()` each time the external resource (function, db cursor, etc ...) changed.

### What does the proposed API look like?
I propose to expose `Dep` in the object `Vue.util`.

**Comment by green-coder** [comment]
For reference, Meteor has a dependency tracking system very similar to the one used in VueJS, and they expose their [`Tracker.Dependency`](https://docs.meteor.com/api/tracker.html) class to the users on purpose :

> Applications will find Tracker.autorun useful, while more advanced facilities such as Tracker.Dependency and onInvalidate callbacks are intended primarily for package authors implementing new reactive data sources.

I hope the same can be done on VueJS.

**Comment by gustojs** [comment]
Can you please clarify how this issue correlate with https://github.com/vuejs/vue/pull/4652?

**Comment by green-coder** [comment]
You are totally right. I missed this PR when I did my search earlier. Thanks a lot!

**Comment by Gonzih** [comment]
Can this be reopened since mentioned pull request was abandoned?

**Comment by mitar** [comment]
I made [this package](https://www.npmjs.com/package/@tozd/vue-observer-utils) which exposes `Dep` and `Watcher` classes.
