### ISSUE TITLE
Add "datalist" html5 element support  to v-model

### ISSUE THREAD

**Issue by asolopovas** [vuejs/vue#5259]
### What problem does this feature solve?
Allows to utilize datalist html5 element instead of javascript plugins like typeahead. 

### What does the proposed API look like?
http://codepen.io/asolopovas/pen/KWRGXE?editors=1111

**Comment by posva** [comment]
It already works, you just have to move the `v-model` to the input

**Comment by asolopovas** [comment]
Is there a way to catch v-for option object value?

**Comment by posva** [comment]
I'm sorry, I don't understand your question. If you have a question, please ask it on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
You may find what you need by using the search on the docs: https://vuejs.org/v2/guide/ It works like a charm 🙂

**Comment by asolopovas** [comment]
Thats the thing that the guide does not explain this particular use case.
```
<input v-model='input' @input="performSearch()">
<datalist>
    <option v-for="result in results"  :value="result.name + ' ' result.surname">{{result.name}} {{result.surname}}</option>
</datalist>
```

performSearch fetches a list of objects that are required elsewhere in the code I an need to catch the selected result as it has additional data to be processed. Events like @select or @change do not catch the result they only do catch binded value.

**Comment by posva** [comment]
use a computed value to save the value as at object but read it as a string. If you have further questions, please, use the forum

**Comment by asolopovas** [comment]
@posva thanks will try that

**Comment by kakugiki** [comment]
Still not working. It only displays all the options after removed the v-model from the input.

**Comment by pedrorckt** [comment]
It works for me with `v-model.lazy="item"`!
