### ISSUE TITLE
Allow ignoring of HTML-parser errors at compile time

### ISSUE THREAD

**Issue by servermachine** [vuejs/vue#5261]
### What problem does this feature solve?
When using Webpack with hot-reload, any html tag that is unmatched and not specified in src/platforms/web/compiler/util.js with canBeLeftOpenTag will result in 'npm run dev' failure

eg:
``` - tag <div> has no matching end tag. ```

This is caused by conditional rendering in the Vue component.
At runtime, the HTML is rendered with correct syntax, so failing at compile time is not necessary.

### What does the proposed API look like?
Maybe add to webpack config file on option such as:

```javascript
module: {
    rules: [ { test: /\.vue$/,
        loader: 'vue-loader',
        options: { ignoreHTMLErrors:true }
 }]
```

**Comment by yyx990803** [comment]
This is intended, because when it happens it's almost always a mistake. Intentionally omitting closing tags is brittle and imo bad practice.
