### ISSUE TITLE
Segmentaion fault with Vue Client on Node 6.10

### ISSUE THREAD

**Issue by abbrechen** [vuejs/vue#5263]
### Version
2.2.2

### Reproduction link
[http://stackoverflow.com/questions/42892889/solved-segmentation-fault-on-vuejs-client-debian-server](http://stackoverflow.com/questions/42892889/solved-segmentation-fault-on-vuejs-client-debian-server)

### Steps to reproduce
1. Made a working Vue Cli project on Win10 64bit with Node 6.10
2. Uploaded the project (except of the node_modules folder) to my Debian 7.0 64bit server
3. installed the dependencies
4. npm run dev
5. segmentation fault (see link to minimal reproduction)

### What is expected?
I expected the server would run ...

### What is actually happening?
... the server didnt run.

---
I solved the problem with a downgrade of Node from 6.10 to 6.9.5.

**Comment by posva** [comment]
This is likely unrelated to Vue. It probably related to the tooling, or how we used it. So please, open the issue on the template repo instead. But before that, try to boil down the problem, with, at least, a stacktrace.
