### ISSUE TITLE
svg element <g>'s style does not work on childs

### ISSUE THREAD

**Issue by gfnba123** [vuejs/vue#5272]
### Version
2.2.4

### Reproduction link
[https://jsbin.com/xaloqeg/edit?html,console,output](https://jsbin.com/xaloqeg/edit?html,console,output)

### Steps to reproduce
1.when page load first time,the rect transform does not work with g's style: transform-origin: 50% 50% 0px;"
2.when I update some value in data,it works correctly;

### What is expected?
rect transform with transform-origin: 50% 50% 0px;"

### What is actually happening?
rect transform with transform-origin: 0% 0% 0px;"

**Comment by yyx990803** [comment]
This seems to be a webkit bug. Reproduced without Vue: https://jsbin.com/jujegecoru/1/edit?html,output
