### ISSUE TITLE
v-for in transition-group does not pick up instance data

### ISSUE THREAD

**Issue by wusfen** [vuejs/vue#5273]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/0xv177hw/1/](https://jsfiddle.net/0xv177hw/1/)

### Steps to reproduce

        <transition-group tag="table" name="fade">
            <tr v-for="item in list" :key="item.id">
                <td>
                    {{item.id}}
                </td>
                <td>
                    {{item.name}}
                </td>
            </tr>
        </transition-group>

### What is expected?
render as table

### What is actually happening?
error

**Comment by HerringtonDarkholme** [comment]
Hi, the issue list is reserved exclusively for bug reports and feature requests. 
That means we do not accept usage questions. You can find help on vuejs forum and vuejs gitter.

What goes wrong here is that you need to understand Vue's virtual dom patching algorithm. Transition group tag `table` cannot not have `tr` as children. You need to change the tag to `tbody` so vdom patching can patch correctly. 

Fixed: https://jsfiddle.net/0xv177hw/2/

**Comment by wusfen** [comment]
but the fade transition is not effective
