### ISSUE TITLE
vuejobs logo is broken

### ISSUE THREAD

**Issue by Kingwl** [vuejs/vue#5276]
### Version
2.2.5

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
https://raw.githubusercontent.com/vuejs/vuejs.org/master/themes/vue/source/images/vuejobs.png

### What is expected?
┑(￣Д ￣)┍

### What is actually happening?
┑(￣Д ￣)┍

---
┑(￣Д ￣)┍

**Comment by ly0** [comment]
It's very helpful to me!

**Comment by Akryum** [comment]
This has something to do with [this commit](https://github.com/vuejs/vuejs.org/commit/6fa907d9ca3758bc773b6b2cfb762284f9542c9e#diff-fef05edd532d047b8abeee30e5b69d4a).

**Comment by posva** [comment]
Local svg are not supported in gh readme, but we can use an external one, or the png

**Comment by yyx990803** [comment]
fixed
