### ISSUE TITLE
Binding :selected in Select > Option not working with v-model

### ISSUE THREAD

**Issue by evertramos** [vuejs/vue#5279]
### Version
2.2.5

### Reproduction link
[https://jsfiddle.net/evertramos/zn91j20b/](https://jsfiddle.net/evertramos/zn91j20b/)

### Steps to reproduce
Add a select tag with some options using vue with some properties from and object of database.

If you want to have a default value selected in your form when the user enter the form, you must use a **:select="condition..."**, as of below:

````
 <select>
      <option
        :selected="true">
      </option>
  </select>
````

If you add __v-model__ to the select tag **<select v-model="selected_option">** the **:selected...** stop working.

### What is expected?
When adding the v-model option to the selected tag, the default value **:selected** stop working.

### What is actually happening?
Should send the value selected to the v-model property.

**Comment by yyx990803** [comment]
I don't get what you are trying to do. The usage is fundamentally problematic because `v-model` is expected to control what options are selected, but then you explicitly control `:selected` with another condition - so you are basically telling Vue to contradict itself.

**Comment by evertramos** [comment]
Hello Evan @yyx990803,

You are right!

Just to keep a track of that, here is a work around:

Instead of using `v-model` we could use `@input="property_name = $event.target.value"` and that will do it.

Thanks!
