### ISSUE TITLE
expression with filter and concatenation

### ISSUE THREAD

**Issue by julesbou** [vuejs/vue#528]
I'm using following code to render gravatar images: [JSFiddle](http://jsfiddle.net/oaqxp3xw/)

``` js
<img v-attr="src: 'http://www.gravatar.com/avatar/' + email | md5 + '.jpg?s=50'">
```

Expected result: `<img src="http://www.gravatar.com/avatar/bar.jpg?s=50">`
Actual result: `<img src="http://www.gravatar.com/avatar/bar">`

---

Workaround: [JSFiddle](http://jsfiddle.net/oaqxp3xw/1/)

``` js
<img v-attr="src: 'http://www.gravatar.com/avatar/' + hash + '.jpg?s=50'" v-with="hash: email | md5">
```

**Comment by adamreisnz** [comment]
What if filters can't be placed at the end?

For example:

```
:suffix="totalPaymentsProcessed | currency + 'total processed'"
```

This is easily possible with un-bound attributes syntax:

```
suffix="{{totalPaymentsProcessed | currency}} total processed"
```

But sadly this is no longer allowed. Any workarounds that don't involve a new computed property or manually loading the filter into the component?
