### ISSUE TITLE
Sugar Syntax v-for="item in [ object.item ]"

### ISSUE THREAD

**Issue by kazusa-qooq** [vuejs/vue#5282]
### What problem does this feature solve?
We should use local variables to deep json items for readability.
Now, vue.js dose not support local variables and binding some object to some tag.
However, it is resolved by v-for with single item array.
We can access with short name to item in deep.
Unfortunally, this steatment is very dutty.
Could you make sugar syntax for this?

### What does the proposed API look like?
Now
`<p>{{object.long.long.name}} {{object.long.long.some}}</p>`

v-for
`<p v-for="obj in [object.long.long]"> {[obj.name}} {{ obj.some }}</p>`

sugar syntax example
`<p v-as="obj as object.long.long"> {[obj.name}} {{ obj.some }}</p>`

**Comment by Tzook** [comment]
Maybe call it "v-init" to comply with angular's ["ngInit" directive](https://docs.angularjs.org/api/ng/directive/ngInit).

**Comment by posva** [comment]
Just use a computed property, there's no need for a new syntax
