### ISSUE TITLE
Encounter a problem when using class binding together with js dom class operation

### ISSUE THREAD

**Issue by loveLibra** [vuejs/vue#5283]
### Version
2.2.5

### Reproduction link
[https://jsfiddle.net/98b0cgxs/](https://jsfiddle.net/98b0cgxs/)

### Steps to reproduce
1. click button **toggle**，the background color changed
2. click button **toggle2**

### What is expected?
excepted result is，only toggled the font color

### What is actually happening?
the background color reseted to the initial value

---
I think, class binding should only affect itself ...

**Comment by yyx990803** [comment]
You should not be manually manipulating the DOM controlled by Vue. Use Vue's binding system instead.
