### ISSUE TITLE
Inconsistent behavior when cancelling ondragover/ondragleave events

### ISSUE THREAD

**Issue by bluenote10** [vuejs/vue#5288]
### Version
2.2.5

### Reproduction link
[https://jsfiddle.net/bluenote10/d2waamdk/10/](https://jsfiddle.net/bluenote10/d2waamdk/10/)

### Steps to reproduce
In order to receive an `ondrop` event it is in general required to discard the default behavior of the `ondragover`/`ondragleave` events. The attached example discards events using the traditional `return false` approach. 

The example has two versions, a manual version and a Vue based version. Both implementations are exactly identical. Discarding the `ondragover`/`ondragleave` events does work properly in the manual implementation, i.e., the `drop` event arrives without problem.

### What is expected?
The Vue implementation should behave identical to the manual implementation.

### What is actually happening?
In the Vue implementation the events do not seem to be properly cancelled. As a result the `drop` event does not work.

---
Note that using `e.preventDefault` or also `@dragover.prevent` does work. Only the traditional discarding of using `return false` is affected and leads to the unexpected behavior.

The issue has also been discussed [here](https://forum-archive.vuejs.org/topic/659/html5-drag-and-drop-events-with-vue/10).

**Comment by yyx990803** [comment]
FYI return false is NOT part of the spec. It's supported for legacy reasons in some browsers but you should not rely on it.
