### ISSUE TITLE
vue自定义指令在.pug中编译报警告

### ISSUE THREAD

**Issue by ashersmtll** [vuejs/vue#5293]
如果组件中使用的html模板语法是 .pug/.jade语法编译的时候 使用自定义指令出现如下警告

如定义一个 v-lazyLoad 的自定义指令
[Vue warn]: Property or method "v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
[Vue warn]: Property or method "lazyLoad" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

如果组件使用 正常的html模板 就是正常的

**Comment by areyouse7en** [comment]
我也遇到这问题，官方demo那个v-focus都不行。
后来发现其他传参的指令就不报错
你可以尝试传个空值给它， div( v-lazyLoad=“” )，这样就没问题了

**Comment by fengbjhqs** [comment]
感谢，我也遇到这个问题了，一直以为是组件的问题，。。。
