### ISSUE TITLE
vue官网 谷歌字体加载太慢

### ISSUE THREAD

**Issue by guoxiangwen** [vuejs/vue#5294]
### Version
2.2.6

### Reproduction link
[https://cn.vuejs.org/v2/guide/](https://cn.vuejs.org/v2/guide/)

### Steps to reproduce
vue官网 谷歌字体加载太慢，如果没有翻墙，字体加载阻塞页面渲染

### What is expected?
希望把google字体文件用国内的

### What is actually happening?
确实是字体阻塞导致：
GET https://fonts.googleapis.com/css?family=Source Sans Pro:300,400,600|Roboto%20Mono net::ERR_CONNECTION_TIMED_OUT
(index):22 GET https://fonts.googleapis.com/css?family=Dosis:500&text=Vue.js net::ERR_CONNECTION_TIMED_OUT
vue.js:5846 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
(index):793 GET https://www.google-analytics.com/analytics.js net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ (index):793
(anonymous) @ (index):794

---
有时候翻不了墙，看官网学习 页面要等很久才出来。

**Comment by posva** [comment]
You seem to have some blockers either locally or on your network. But this has nothing to deal with Vue

**Comment by guoxiangwen** [comment]
First，Thanks for answer
yes,it really deal with Vue, but,in china,most of us can not download the google font. And it is really block the html render, it will be block us to view the vue website,it block us to study vue.You just change the font address on the server. but to us,it is the biggest problem,like a fishbone stuck in the throat。

**Comment by LinusBorg** [comment]
1. The website has its own repository: www.github.com/vue/vuejs.org
2. Why would it block you to view the website? Would the browser not simply use another font?

**Comment by guoxiangwen** [comment]
In China,We must Over the Internet wall could view Google.

**Comment by yyx990803** [comment]
请自行翻墙...
