### ISSUE TITLE
Vue.js（2.1.10） run in IE9, reported Unspecified error

### ISSUE THREAD

**Issue by wgq837051** [vuejs/vue#5300]
### Version
2.1.10

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
In IE9 under the debugging, will enter the vue.js source
`
function isDirty (elm, checkVal) { // return true when textbox (.number and .trim) loses focus and its value is not equal to the updated value return document.activeElement !== elm && elm.value !== checkVal }
`
	Create a separate html file, direct console.log (document.activeElement); in the local visit, will output null, through the struts2 .do visit, it will be reported not specified wrong.

### What is expected?
 run in IE9, reported Unspecified error

### What is actually happening?
Vue.js（2.1.10） run in IE9, reported Unspecified error

**Comment by yyx990803** [comment]
You did not provide a reproduction.
