### ISSUE TITLE
Vue 2.2.6 fails to register some components

### ISSUE THREAD

**Issue by ronjouch** [vuejs/vue#5304]
### Version
2.2.6

### Reproduction link
[https://github.com/ronjouch/vue-registerbug](https://github.com/ronjouch/vue-registerbug) (hope it's minimal enough, it's based on the `webpack` template)

### Steps to reproduce
Clone the bug GitHub repo and `npm install && npm run dev`. App opens in browser.

### What is expected?
* Three strings should show up: fromheader, fromroot, frombody

### What is actually happening?
* Only two strings show up: fromroot, frombody.
* The "fromheader" component doesn't load, and this pops up in the console: `[Vue warn]: Unknown custom element: <child> - did you register the component correctly? For recursive components, make sure to provide the "name" option. (found in <MyHeader> at /home/ronj/vue-registerbug/src/components/MyHeader.vue)`

---

*EDIT Having a final look at this I realize it is unlikely to be a bug, I must be missing something. And if this is indeed a bug, sorry for the imprecise title.*

**Comment by cpastore84** [comment]
It looks like you have typo in your MyHeader component. When registering a component locally, the component value should be an object and you have an array.

so this:
```
export default {
  components: [
    Child
  ]
}
```

should be :
```
export default {
  components: {
    Child
  }
}
```

**Comment by ronjouch** [comment]
> *"It looks like you have typo in your MyHeader component. When registering a component locally, the component value should be an object and you have an array."*

Barf, indeed 🤷‍. @cpastore84 @yyx990803 would this kind of mistake have been caught by TypeScript? Other tooling suggestions?

Thanks for the fast feedback, and sorry for the noise. Vue is a pleasure to use 👍.
