### ISSUE TITLE
Can't join forum

### ISSUE THREAD

**Issue by sbowman** [vuejs/vue#5305]
I am trying to join the forum, but I keep getting a message that "too many people have joined from my address".  Then it tells me to contact the staff from the staff page, which leads me to the vuejs.org page, which has no contact information or help button.  

Hoping you can help me through the GitHub system, though pretty sure my ticket will be "immediately deleted" because I can't use your custom ticketing form due to the fact that I can't create a required JS snippet to demonstrate I can't login.

*sigh*  

I'm feeling a bit like I've stumbled through the looking glass...

**Comment by sirlancelot** [comment]
@sbowman Try asking on Gitter to see if someone can unblock your IP: https://gitter.im/vuejs/vue
