### ISSUE TITLE
Can't login to forum:  "too many users from my address"

### ISSUE THREAD

**Issue by sbowman** [vuejs/vue#5306]
### Version
2.2.6

### Reproduction link
https://forum.vuejs.org

### Steps to reproduce
Try to register.  Get denied with a message "too many users have joined from my address".  Apparently big companies are shut out of joining the VueJS forums.

### What is expected?
To be allowed to registered.

### What is actually happening?
Being blocked from registering by some weird security system.

**Comment by yyx990803** [comment]
Bumped accounts per ip limits.
