### ISSUE TITLE
项目迭代，局部通过vue实现单页面应用，能否实现？

### ISSUE THREAD

**Issue by liudianliang** [vuejs/vue#5307]
老的项目使用jquery，现在要在老的项目中添加商城应用，有商城首页，列表页，详情页，订单页面等，商城可否用vue来实现？老的项目中也有产品列表页，和详情页，用vue重构商城，可否从老项目中直接跳转到vue的商品列表和详情页面等其他页面？

**Comment by leohxj** [comment]
你这个“商城应用”应该就是个独立的，只是在老项目中添加一个入口吧？页面之间切换，也只是url的跳转。
那这样的话，“商城应用”可以作为独立一个项目进行，使用 vue 技术栈。
