### ISSUE TITLE
Expose createCompiler in src/compiler/index.js and createPatchFunction from core/vdom/patch as a smaller package.

### ISSUE THREAD

**Issue by lyonlai** [vuejs/vue#5312]
### What problem does this feature solve?
I'm working on creating a compiler & runtime of Vue for a library I'm interested in. At the moment I'm putting my code inside Vue's source code as a platform. It is good that I can leverage existing functions & toolings from Vue for sure. But by doing this also means that I need to include the external library my runtime depends on into Vue's dependencies, which is ok if there's not that many runtimes around, but it surely will become a problem when the community grow.

In the progress I found that I only need createCompiler, createPatchFunction & the core of Vue to make my own runtime for Vue. It would be good to expose those along in a smaller npm package so that people can maintain their code in a separate codebase. 

Thoughts?

### What does the proposed API look like?
What's been proposed is a smaller npm package as vue-core

besides exposing the vue/core/index as default. it should also expose createCompiler from src/compiler/index.js & createPatchFunction from src/core/vdom/patch

**Comment by yyx990803** [comment]
Vue's npm package includes the source code - technically you can just create your project with Vue as a dependency and import the source code directly (requires flow syntax support).

**Comment by lyonlai** [comment]
It probably requires similar rollup config(especially the aliases in the project) to compile the whole thing. At the moment I've done my fun runtime in as a branch of Vue and it's working. I'll give the include source code approach a go to see how complex it is. Thanks @yyx990803

**Comment by lyonlai** [comment]
Alright, thanks @yyx990803  again for the advice. I've got my runtime out to its own repository. Feel free play around: [blessed-vue](https://github.com/lyonlai/blessed-vue)

**Comment by yyx990803** [comment]
Nice! Looks fun :)
