### ISSUE TITLE
v-bind:style floating point number precision problem

### ISSUE THREAD

**Issue by Zhangdroid** [vuejs/vue#5313]
### Version
2.2.6

### Reproduction link
[http://codepen.io/zhangzhuo/pen/pexKXV](http://codepen.io/zhangzhuo/pen/pexKXV)

### Steps to reproduce
set template like this:
```vue
<span :style="{ color: 'rgba(0,0,0,.1)' }">
  test
</span>
```

### What is expected?
Actual DOM should be:
```html
<span style="color: rgba(0, 0, 0, 0.1);">
  test
</span>
```

### What is actually happening?
```html
<span style="color: rgba(0, 0, 0, 0.0980392);">
  test
</span>
```

---
That's not a big problem and probably standard own problem. It would be better to fix it. Thanks~

**Comment by xujiongbo** [comment]
I don't think it's an issue related to vue.

**Comment by yyx990803** [comment]
Note really a Vue issue - if you do:

``` js
element.style.setProperty('color', 'rgba(0,0,0,0.1)')
```

The result is the same.
