### ISSUE TITLE
v-media directive

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5316]
### What problem does this feature solve?
this solves classes bindings like when you want to change the class of a component based on the media query 

### What does the proposed API look like?
```html
  <div v-media:600="mediaEvent"> Test </div>
```
```js
new Vue({
   el: '#app',
   methods: {
      mediaEvent(e) {
        console.log(e);
     }
   }
})
```

**Comment by posva** [comment]
This is something that should be created in userland. There're already some libs related to media queries out there, you should check them out.
BTW you shouldn't change the class based on media queries, you should change the style of a class based on media queries
