### ISSUE TITLE
v-for v-show combination 

### ISSUE THREAD

**Issue by zfan40** [vuejs/vue#5317]
### What problem does this feature solve?
I am using Vue 2.0 and unluckily run into a wander. 
v-for v-if combination is working perfectly fine, well v-for v-show appears to be acting without v-show directive functioning.
Any suggestions pls?

### What does the proposed API look like?
<slot v-for="(slot,index) in slots" v-show="index==activeIndex" :name="slot.name"></slot>

**Comment by caiquecastro** [comment]
Could you provide an jsfiddle?

**Comment by yyx990803** [comment]
If it's a bug, use the bug reporting format. Don't abuse the issue helper.
