### ISSUE TITLE
Feature Request: Async Mixins

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5319]
### What problem does this feature solve?
This solves asynchronous components to have mixins when they are resolved

### What does the proposed API look like?
just add a mixin asynchronously

**Comment by posva** [comment]
Why would you add an async mixin? This would make the component properties editable at runtime which can lead to very unexpected behaviours

**Comment by yyx990803** [comment]
I don't think this makes much sense... there's nothing that prevents an async component from using mixins normally.
