### ISSUE TITLE
VUE Single file components can't access this.$option.template in beforeCreate function

### ISSUE THREAD

**Issue by lfyfly** [vuejs/vue#5320]
### What problem does this feature solve?
VUE Single file components can't access this.$option.template in beforeCreate function。
我想在通过数据动态修改模板，但是单文件组件无法访问到template，所以无法修改。

### What does the proposed API look like?
Single file can access template in beforeCreate function。

**Comment by yyx990803** [comment]
动态修改模板是个完全错误的思路...

**Comment by TingYinHelen** [comment]
可以给slot赋值么
