### ISSUE TITLE
Node relocation makes Vue throw error

### ISSUE THREAD

**Issue by rstoenescu** [vuejs/vue#5321]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/rstoenescu/uqsath1t/2/](https://jsfiddle.net/rstoenescu/uqsath1t/2/)

### Steps to reproduce
Run jsfiddle, uncheck the tick box and look at browser console log. Vue tries to call Node.insertBefore() API but parent node does not match element's parent (which has been relocated in `mounted()` method). 

### What is expected?
Not to throw the error.

### What is actually happening?
Error is thrown: `DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.(…)`

---
Submitting fix in a bit. This helps with some features of Quasar Framework (Tooltip, Popover, and new ones currently unreleased).

**Comment by rstoenescu** [comment]
Refering PR which fixes this: https://github.com/vuejs/vue/pull/5322

**Comment by posva** [comment]
You shouldn't manipulate the dom that is handled by Vue because of that. You may be interested in   https://github.com/LinusBorg/portal-vue

**Comment by rstoenescu** [comment]
Hi,

Still, haven't seen any side-effects with the simple PR I wrote. What problems could there be with this change? Trying to fully understand. Haven't dug too deep in Vue internals to be honest because of the lack of time (working hard for next Quasar version).

Cheers,
Razvan

**Comment by posva** [comment]
Adding an if check in the patch can have an impact on performance. But, it's more the moving elements around that bothers me, it's a bad idea to manually manipulate the dom that is manipulated by Vue

**Comment by rstoenescu** [comment]
I agree that tampering with elements managed by Vue is a totally bad idea. But this is a different case.
The element itself is not manipulated in any way outside of Vue except for relocation. Vue still handles it 100% and from my analysis there is no side-effect. Vue component is still mapped to its element, except the element is in a different location. Virtual DOM works as expected and it really does not care about mapped element location and only about the actual DOM changes within, which is great.

Let me write an actual use case and the value the proposed change brings us to the table. Writing a tooltip component. You still want to control it from within the context of the element/component you bind it to, but you don't want the actual tooltip content inheriting CSS from parent (imagine complex CSS affecting Tooltip in unexpected ways -- talking from a framework owner perspective). Same for Popovers. There are alternatives to relocating element position for Tooltips/Popovers, but the overhead/boilerplate necessary in app space is just too much. I have some other use cases if necessary to make my case stronger. This is just the starting point.

Also, I think the added overhead of that additional "if" statement is negligible. Are there some ready-to-run benchmarks I can use to compute the difference?

Thanks.

**Comment by posva** [comment]
No, I don't think there's an impact 🙂 
Looks like an interesting example. I'll check Quasar tooltips and popovers to better understand that. Are they on a specific branch?

**Comment by rstoenescu** [comment]
https://github.com/quasarframework/quasar/blob/dev/src/vue-components/tooltip/Tooltip.vue
and https://github.com/quasarframework/quasar/issues/481

Contact me on Slack to speed this up if you'd like.
