### ISSUE TITLE
Props change will not trigger child component update if props not referred in template

### ISSUE THREAD

**Issue by RephoneYin** [vuejs/vue#5325]
### Version
2.2.6

### Reproduction link
[https://jsbin.com/pusozum/edit?html,js,console,output](https://jsbin.com/pusozum/edit?html,js,console,output)

### Steps to reproduce
Please check minimal reproduction:
2 components which are parent and child, parent pass props to child.
Child component will not update if the props is not referred in its template.

### What is expected?
Child component trigger its updated hook.

### What is actually happening?
Child component never trigger its updated hook

**Comment by yyx990803** [comment]
`updated` hook means the component did a re-render. If the prop is never used during render, why would you expect the component to re-render when it changes?

Put it another way: you are misunderstanding what `updated` should be used for.

**Comment by zhopon** [comment]
You should use [watch](https://vuejs.org/v2/guide/computed.html#Watchers) for this, as it's not dependent on whether the component was re-rendered or not.

**Comment by aboutqx** [comment]
But when it's used in `v-if`,still not trigger changes.

**Comment by aboutqx** [comment]
Sorry,it works with `v-if`,what i faced it's a parent to child prop.

**Comment by aboutqx** [comment]
oh,i made a mistake ,it actually works.

**Comment by efibn** [comment]
I found a workaround for this problem as @adamreisnz described it very well, as I'm coming from Angular myself. 

Since you cannot update a prop by equal "=" sign which creates a new reference in memory for the same property, just update the prop with the Object.assign(this.prop, newVal) when coming back from promise or event or any other change, then you can be assured working with the new updated value in the current hook, and for the next hook, it will be coming from the parent with the same updated value, so no worries.

And most important, no Watch/Computed/Data for preventing code duplications.

**Comment by posva** [comment]
In vue you the way to go would be to watch specific data or props to trigger side actions. It's very rare to need to watch the *whole* data tree to trigger a side effect, if it is, you should revisit the strategy you are using to see if it could be data-oriented instead (most of the time it is).
However, it's possible to observe data and props updates by doing `this.$watch('$data', handler, { deep: true })` or `this.$watch('$props', handler, { deep: true })`

**Comment by adamchenwei** [comment]
just go to ReactJS already. I am having enough of this state not changning mess in Vuejs. The positive part, its a bit less horrible thank AngularJS.

**Comment by tettoffensive** [comment]
Could someone post the solution to the jsbin? I'm having trouble discerning exactly what the answer is. Where do you watch for $props? in the parent or in the child?

**Comment by sirlancelot** [comment]
@tettoffensive Several options are available to you. Suppose you have a prop named "message":

https://vuejs.org/v2/api/#watch
```
export default {
  watch: {
    message(value, previousValue) {
      debugger
    }
  }
}
```

Or imperatively (for instance in a `created()` hook):

https://vuejs.org/v2/api/#vm-watch
```
this.$watch("message", (value, previousValue) => {
  debugger
})
```

For further questions, please use Discord or the Forums. Thanks!

**Comment by henhen87** [comment]
I am also having a similar issue. Is it normal to have watchers to update local component `data()` on prop changes. I am coming from React, and component will re-render every time props passed to component are updated. The code I am working on is set up using the `extend` API.

```
const myInput = {
   props: ['date'],
   data() {
   	inputDate: this.date //I want inputDate to have default value of props passed in. When
   											 //The date prop updates, it will not re-render but I can see in my
   											 //Vue dev tools that the prop is indeed updated. I initially did
   											 //not have a `watcher` for date props but after adding it, it updates.
   },
   watch: {
   	date(newVal, oldVal) { //Adding this watcher updates inputDate. Why do I need this? I assumed prop changes
   												 //would re-render similar to React
   		if new!== oldVal
   			this.inputDate = newVal
   	}
   }
   template: `
   	<input v-model = "inputDate" />
   `
}

const containerOne = Vue.extend({
	methods: {
		methodToUpdateItems() {
			... //The code here uses an external code outside of Vue. We are converting an old framework to Vue
			    //and use one of the legacy controller functions to update the model for the old framework.
			    //This model is assigned to `items` in this component
		}
	},
	data() {
		items: {
			dates: [date1, date2]
		}
	}
	...
	...
});

const containerTwo = containerOne.extend({
	...
	template: `
		...
		<table v-for="(item, index) in items.dates">
		 <myInput date="item" />
		 ...
		</table>
	`,
	components: {
		myInput
	}
});
```

**Comment by kenghot** [comment]
this works for me:
<template id="k-evaluate">
    <v-card-text>
        <v-row>
            <v-col cols="11">
                {{title}}
            </v-col>
            <v-col cols="1">

                <v-row>
                    <v-switch v-model="obj[fld]" color="green" inset></v-switch>
                </v-row>
                <v-row>
                    {{passText}}
                </v-row>
            </v-col>
        </v-row>

    </v-card-text>
</template>
<div id="appEvaluate">
    <v-app id="inspire">
        <v-card>

            <v-list-item>
                <v-list-item-content>
                    <v-list-item-title class="h2">กรณีองค์กรภาคเอกชนหรือองค์กรของผู้สูงอายุที่จดทะเบียนเป็นนิติบุคคล หรือ ได้รับการรับรองเป็นองค์กรสาธารณประโยชน์ตามกฎหมายว่าด้วยการส่งเสริมการจัดสวัสดิการสังคม</v-list-item-title>

                </v-list-item-content>
            </v-list-item>
            <k-evaluate ref="ref1" :obj="result" fld="sw1" title="(ก) มีอำนาจหน้าที่เกี่ยวกับการคุ้มครอง การส่งเสริม และการสนับสนุนผู้สูงอายุ">

            </k-evaluate>
            <v-card-text>
                <v-row>
                    <v-col cols="11">
                        (ก) มีอำนาจหน้าที่เกี่ยวกับการคุ้มครอง การส่งเสริม และการสนับสนุนผู้สูงอายุ
                    </v-col>
                    <v-col cols="1">

                        <v-row>
                            <v-switch v-model="result.sw1" color="green" inset></v-switch>
                        </v-row>
                        <v-row>
                            ผ่าน
                        </v-row>
                    </v-col>
                </v-row>

            </v-card-text>
            <v-card-text>
                <v-row>
                    <v-col cols="11">
                        (ข) ได้รับมอบหมายให้เป็นหน่วยงานรับผิดชอบในการดำเนินการตามประกาศ สำนักนายกรัฐมนตรี เรื่อง กำหนดหน่วยงานรับผิดชอบในการดำเนินการตามพระราชบัญญัติผู้สูงอายุ พ.ศ. 2546 หรือมีหน้าที่ดำนินการในการคุ้มครอง การส่งเสริม และการสนับสนุนผู้สูงอายุตามประกาศ กระทรวงที่เกี่ยวข้อง หรือมีหน้าที่ตามกฎหมายในการส่งเสริมกิจกรรมเกี่ยวกับผู้สูงอายุ
                    </v-col>
                    <v-col cols="1">

                        <v-row>
                            <v-switch v-model="result.sw2" color="green" inset></v-switch>
                        </v-row>
                        <v-row>
                            ผ่าน
                        </v-row>
                    </v-col>
                </v-row>

            </v-card-text>
            <v-card-actions>
                <v-btn text
                       color="deep-purple accent-4">
                    Read
                </v-btn>
                <v-btn text
                       color="deep-purple accent-4">
                    Bookmark
                </v-btn>
                <v-spacer></v-spacer>
                <v-btn icon>
                    <v-icon>mdi-heart</v-icon>
                </v-btn>
                <v-btn icon>
                    <v-icon>mdi-share-variant</v-icon>
                </v-btn>
            </v-card-actions>
        </v-card>
    </v-app>
</div>

Vue.component('k-evaluate', {
    template: '#k-evaluate',
    props: ['title','obj','fld'],
    data() {
        return {
            myPass: this.obj[this.fld]
        }
    },
    computed: {
        passText: function () {
            return this.myPass ? "ผ่าน" : "ไม่ผ่าน"
        }
    },

    }
})
var VueEvaluate = new Vue({
    el: '#appEvaluate',
    vuetify: new Vuetify(),
    data() {
        return {
            result: {
                sw1_1: false,
                sw1_2: false,
                sw2_1: false,
                sw2_2: false,
                sw2_3: false,
                sw2_4: false,
                sw2_5: false,
            }
        }
    },
})

**Comment by sirius0xff** [comment]
Really painfully experience when working with renderless component.
