### ISSUE TITLE
v-show v-for combination usage

### ISSUE THREAD

**Issue by zfan40** [vuejs/vue#5326]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/4doey5k0/1/](https://jsfiddle.net/4doey5k0/1/)

### Steps to reproduce
in the jsfiddle example, changing v-show in line 11 of HTML to v-if will get ideal switch result.

### What is expected?
show only one tab content with v-show

### What is actually happening?
show both tab contents with v-show

**Comment by xujiongbo** [comment]
You shouldn't use ```slot``` in this case, ```v-show``` is invalid with ```<slot>``` tag,  ```v-for``` and ```v-if``` is working because they are processed in compilation phase before ```<slot>```.

**Comment by zfan40** [comment]
I see, that would be dup with #3772. thanks
