### ISSUE TITLE
<br>or<hr>==>Error compiling template?

### ISSUE THREAD

**Issue by yijunjun** [vuejs/vue#5332]
### Version
2.2.6

### Reproduction link
[https://github.com/vuejs/vue/issues/5331](https://github.com/vuejs/vue/issues/5331)

### Steps to reproduce
``` html
<template id="page-footer-template">
    <br />
    <div>
      <h1>hello,world</h1>
    </div>
    <hr />
</template>
```

### What is expected?
hello,world

### What is actually happening?
Error compiling template:
Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

**Comment by yyx990803** [comment]
你是看不懂英文吗？Read the error message please.

**Comment by ytbryan** [comment]
> Component template should contain exactly one root element.

@yijunjun Try 

```
<template id="page-footer-template">
    <div>
      <br />
      <div>
            <h1>hello,world</h1>
       </div>
       <hr />
   </div>
</template>

```
