### ISSUE TITLE
@keyup.enter doesn't work with only one form element.

### ISSUE THREAD

**Issue by woodjamie** [vuejs/vue#5337]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/3n42xna1/](https://jsfiddle.net/3n42xna1/)

### Steps to reproduce
Case 1:
Using the jsfiddle link type some data into the Name input box and press enter.
Case 2:
Then uncomment the second element, named "uncomment me", run jsfiddle and repeat the above step.

### What is expected?
In the first case the counter should increment like it does in the second case.

### What is actually happening?
The counter doesn't increment, the form just tries to do a post.

**Comment by stefanonepa** [comment]
It seems to be a standard behavior of a form containing only one input. If you want to make it work with a single input, you should replace the ```<form>``` by ```<div>```.

(cf. https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/ )

**Comment by Kingwl** [comment]
```
  <form class="form-horizontal" role="form" @submit.prevent>
```
