### ISSUE TITLE
How to create a vue component similar to v-for. 

### ISSUE THREAD

**Issue by ta-dpanga** [vuejs/vue#5339]
### Version
2.2.6

### Reproduction link
[http://nolinkavailable.com](http://nolinkavailable.com)

### Steps to reproduce
<parent-component  pmodel="model">
<child-component model="pmodel" >
</child-component>
</parent-component>

### What is expected?
How to inject parent-component's pmodel into child element's scope. 

### What is actually happening?
How v-for sending the item to the child elements?
<p v-for="item in items">
 <a >{{item}}</a>
</p>

**Comment by yyx990803** [comment]
This is a question, not a bug report.
