### ISSUE TITLE
@click no effect when i use 'v-show'

### ISSUE THREAD

**Issue by ZzZxL** [vuejs/vue#5341]
### Version

2.8.1

### Reproduction link

https://jsfiddle.net/pr3nhtv7/2/

### Steps to reproduce

Case 1:
click the search
Case 2:
focus input and click the dd element

### What is expected?

first case the function 'search' work
second case the function 'hotSearch' work

### What is actually happening?

second case the function hotSearch doesn't work

**Comment by yyx990803** [comment]
`blur` fires before `click`, so the `dd`s are hidden before the click event is able to register.
