### ISSUE TITLE
Implement Vue.notify()

### ISSUE THREAD

**Issue by NoelDeMartin** [vuejs/vue#5342]
### What problem does this feature solve?
I am sorry if this has already been discussed because I think it's something quite basic but I was searching previous issues and I really didn't find it, so maybe I missed something.

When talking about reactivity in the guide, it's mentioned multiple times limitations about which operations will be reactive or not. For example, in the arrays example it mentions how `this.myArray[index] = value` will not be reactive and `Vue.set`or `Array.splice` should be used. But, for a general purpose scenario, there should be a `Vue.notify` method.

Let me give a real life example. I have a date picker component, which contains a `Date` object in the data. When I click a button to move the calendar to the next month, I execute the following code: `this.date.setMonth(this.date.getMonth() 1)` which doesn't trigger a notification, so I am forced to create a new object: `this.date = new Date(this.date.getTime())`. I have been looking in the source code to see how reactivity works exactly, and I found out this can be executed in order to trigger a notification: `this._data.date.__ob__.dep.notify()`. But this is obviously relying on internal implementation, so I think it would be useful to have a `Vue.notify` method (as well as `this.$notify`) in order to implement this functionality and make any further adjustments. 

I have also seen the implementation of `Vue.set` and it ignores any value which is already set, so maybe it would also be an option to have `Vue.set` notify watchers if the property already exists.

### What does the proposed API look like?
`Vue.notify({vue model}, {reactive-property});`

**Comment by yyx990803** [comment]
The key here is understanding the difference between plain object vs. native objects. A `Date` object is the latter and Vue will not attempt to observe its mutations.

And honestly, I think setting a fresh new Date object (treating date as immutable object) is cleaner, and I'd recommend using an immutable date utility lib like [date-fns](https://date-fns.org/) if you need to wrangle with dates a lot. I don't really see the necessity of an extra concept here.

**Comment by NoelDeMartin** [comment]
@yyx990803 Thanks for your reply!

This date scenario is only an example, I understand with date it may not be so necessary but in my case I am not using Date, I am using Moment (which is not a native object) and the same applies, I need to call notify() manually or create a new instance. Maybe with dates it isn't so bad, but there may be some scenarios where this would be better. At the end of the day it'd only be a helper method and people can choose to use it or not, I thought it made sense since this.$watch() is available. Maybe I should have mentioned that I am using typescript, not sure it that has anything to do with the moment object not being reactive.

In any case, thanks for all your work, I recently started using vue and it's awesome. If you think it doesn't fit in the framework it's ok, I can always implement this myself in my project :smile:.

Cheers
