### ISSUE TITLE
Unexpected calls on beforeUpdate and updated hooks with slot

### ISSUE THREAD

**Issue by zzmingo** [vuejs/vue#5343]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/p9twzujf/4/](https://jsfiddle.net/p9twzujf/4/)

### Steps to reproduce
Look into this https://jsfiddle.net/p9twzujf/4/

### What is expected?
child's hooks will be call 

### What is actually happening?
parent's hooks is calling

**Comment by xujiongbo** [comment]
The value prop haven't been used in child render function and it's changes will not lead to re-render of child.

see [https://jsfiddle.net/xujiongbo/e9mqg3n2/1/](https://jsfiddle.net/xujiongbo/e9mqg3n2/1/)

**Comment by posva** [comment]
This is expected: the updated hook is triggered after first update. Maybe this helps you to understand: https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram

**Comment by zzmingo** [comment]
Woooow, thanks, also I am confused by `when data changes`, it's abstract, i thought updated hook would be triggered when props changed, from the literal meaning of `when data changes`

**Comment by zzmingo** [comment]
What i am doing is that i trying to write a canvas/webgl runtime instead of dom (web runtime), like the following:

```
Vue.component('sprite', {
  props: ['x', 'y'],
  beforeCreate() {
    this.$sprite = new Sprite()
    this.$sprite.x = this.x
    this.$sprite.y = this.y
  },
  updated() {
    this.$sprite.x = this.x
    this.$sprite.y = this.y
  },
  render(h) {
    // Sadly updated not triggered, except i use xy here
    this.x + this.y
    return h('fake-element') // fake-element is a mock element in my node-ops.js
  }
})


new Vue({
  template: '<div><sprite :x="x" :y="y"/></div>',
  data() {
    return { x: 0, y: 0 }
  },
  created() {
    setTimeout(() => {
       this.x = 100
    }, 100)
  }
})
```
