### ISSUE TITLE
Keep-Alive inside of transition not working with include

### ISSUE THREAD

**Issue by cynecx** [vuejs/vue#5346]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/24930/](https://jsfiddle.net/50wL7mdz/24930/)

### Steps to reproduce
Click the "Switch view" button.

### What is expected?
The "home" view's state should have been kept alive when switching to the other signin view.

### What is actually happening?
Instead the "home" view is recreated everytime.

---
If I remove the include="home" option from keep-alive, it works as intended or if I remove the mode="out-in" option from the transition node, it also works as intended.
I've debugged this and it seems that when every time it switches the component, the "include" watch is somehow triggered with undefined as val parameter and then it's being triggered again with the correct "home" value but by then the first trigger has already removed the home node from the cache.

**Comment by LinusBorg** [comment]
To make use of the include option, you have to specify the `name` property for the component(s). This should also be explained in the docs.

**Comment by LinusBorg** [comment]
Actually, forget that, it should work...

**Comment by posva** [comment]
In the meantime, you can use an exclude with the rest of components as a workaround

**Comment by cynecx** [comment]
@posva Do you have any idea yet why the cache is being invalidated when I use include?
