### ISSUE TITLE
Components registered with the name "filter" silently fail

### ISSUE THREAD

**Issue by rokkamokka** [vuejs/vue#5347]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/24931/](https://jsfiddle.net/50wL7mdz/24931/)

### Steps to reproduce
Create a component and register it with the name "filter", then try to use it. No errors are thrown, but the component is never instantiated (\<filter\> elements are never "Vueified").

### What is expected?
The \<filter\> element should be detected and the registered component created correctly, or an exception should be thrown.

### What is actually happening?
Silent failure. The \<filter\> component never gets created, and no exception is thrown.

**Comment by rokkamokka** [comment]
Seems to happen with "map" too, so I'm guessing it's related to the Array.prototype methods of the same name.

**Comment by cpastore84** [comment]
`map` is a reserved HTML element and `filter` is an SVG element. Therefore both are prohibited. If you run the fiddle with the development console open you should see the warning message in there.

**Comment by yyx990803** [comment]
Use the development build during development.
