### ISSUE TITLE
data object with numerical keys and decimal values is mangled in Safari 10.1 and Safari on iOS 10.3

### ISSUE THREAD

**Issue by rosswintle** [vuejs/vue#5348]
### Version
2.2.6

### Reproduction link
[http://codepen.io/magicroundabout/pen/PpXXaa?editors=0001](http://codepen.io/magicroundabout/pen/PpXXaa?editors=0001)

### Steps to reproduce
Create a Vue application with a data object with non-sequential numerical keys and at least one decimal value such as:

```
data: {
  numbers4: { 2:3.3, 5:8 }
}
```

console.log this value (or try to iterate over it to do some calculation)

View the output in Safari 10.1 or on an iOS device with iOS 10.3

### What is expected?
In all other browsers I've tested (latest Firefox 52, latest Chrome, Safari 10.0.1, browsers in iOS 10.2) the object is output as:

numbers4: Object {
  2: 3.3,
  5: 8
}

I assume that this is what the output should be.

### What is actually happening?
The "gaps" in the integer "indexes" are being filled, even though this is an object, not an array:

numbers4: Object {
  0: NaN,
  1: NaN,
  2: 3.3,
  3: NaN,
  4: NaN,
  5: 8
}

---
This only happens in the stated browsers/OS's. And it only happens when the data object contains at least one decimal VALUE.  There are some other cases tried out in the CodePen.

I guess this is a Safari bug? But I'm logging it here in case it's something Vue is doing, or in case you can make a workaround for it.

You'll see from the CodePen tests that this doesn't happen if I just create an object outside of Vue. So if it IS a Safari bug then I'll need to know what Vue is doing to the data object to create a more minimal browser bug.

Context: I have a Vue 1.0.28 app that does a calculation by iterating over:

Object.getOwnPropertyNames( someObject ) 

where my object is a numerically indexed array with some integer values and some decimal values. When testing on an iPhone I was getting "NaN" as output. So I dug in to create a minimal test case and to try to nail down the exact conditions.

**Comment by gebilaoxiong** [comment]
He looks like the browser as an array, you can avoid the use of numbers as a property name. and I did not reproduce the bug

**Comment by yyx990803** [comment]
This is indeed a Safari bug. Reproduced without Vue involved: https://jsfiddle.net/uug0hjcg/

I'd suggest opening a ticket at WebKit's bugzilla: https://webkit.org/reporting-bugs/

**Comment by rosswintle** [comment]
Just for reference, looks like this got patched on Saturday: https://bugs.webkit.org/show_bug.cgi?id=164412
