### ISSUE TITLE
A Fast & Light Virtual DOM Alternative

### ISSUE THREAD

**Issue by ansarizafar** [vuejs/vue#5352]
### What problem does this feature solve?
viperHTML https://github.com/WebReflection/viperHTML is a great virtual DOM alternative in terms of speed and size.

### What does the proposed API look like?
const viperHTML = require('viperhtml');

function tick(render) {
  return render`
    <div>
      <h1>Hello, world!</h1>
      <h2>It is ${new Date().toLocaleTimeString()}.</h2>
    </div>
  `;
}

// for demo purpose only,
// stop showing tick result after 6 seconds
setTimeout(
  clearInterval,
  6000,
  setInterval(
    render => console.log(tick(render)),
    1000,
    // On a browser, you'll need to bind
    // the content to a generic DOM node.
    // On the server, you can directly use a wire()
    // which will produce an updated result each time
    // it'll be used through a template literal
    viperHTML.wire()
  )
);

**Comment by yyx990803** [comment]
This is not what issues are for.
