### ISSUE TITLE
Computed property bug in nw.js multi window environment

### ISSUE THREAD

**Issue by kailniris** [vuejs/vue#5357]
### Version
2.2.6

### Reproduction link
[https://github.com/kailniris/vue-multi-window](https://github.com/kailniris/vue-multi-window)

### Steps to reproduce
1. clone repo
2. npm run dev
3. Start the app in nw.js sdk *
4. press the "Open sub window" button in the main window
5. press the "Create 'item_new'" button in the main window
6. type "item_new" into the "itemId" input in the sub window
7. press the "Mutate 'item_new'" button in the main window

step 3:
- Start the app in nw.js sdk
- download nw.js https://dl.nwjs.io/v0.21.4/nwjs-sdk-v0.21.4-win-x64.zip
- create a shortcut with this target C:\path\to\nw.exe C:\path\to\vue-multi-window\package
- after the main window loaded open devtools and start record allocation timeline

### What is expected?
In the sub window the "item name: item_new" changed to "item name: item_new_mutatedXX".

XX is a random number

### What is actually happening?
"item name: item_new" text remains the same.

---
The "getItemById" computed property does not notice property addition mutations to "this.items" after the window was opened and does not notice other mutations with the newly created property.
But only with items which were created after the sub window was opened. If you open another sub window and type "item_new" into its input it will notice mutations happened with the item "item_new".

If i am correct this feature was working before 2.2.0.

**Comment by posva** [comment]
Can you try removing the `Vue.set` and using simply `=` ?
It works fine in a simple jsfiddle: http://jsfiddle.net/posva/47f4679o/

**Comment by kailniris** [comment]
This does not solves the issue. Actually the problem is not with the computed property used this way you showed.
I attached some screenshots, maybe it will be clearer this way whats tend to be the problem.

![subwindows](https://cloud.githubusercontent.com/assets/19587188/24651720/26d85016-192f-11e7-9971-78d205378b8c.jpg)

**Comment by kailniris** [comment]
Some more backstory:
The "items" global state is in the "main window" scope. In the "sub windows" the computed properties dependency is the "items" global state. The problem is after a sub window is opened the newly added properties to the global state won't notify the computed properties in the sub window on mutation.

**Comment by posva** [comment]
Can you try storing the items only on the Root Vue or using inject/provide? You should use Vuex for your global data 
People seems to be using electron with Vue just fine so it really looks like an issue with nw.js 😕

**Comment by kailniris** [comment]
I am using Vuex in the original source. In this example Vuex is not included for sake of minimalism. But if it helps I can refactor this repro case to use Vuex. I never tried inject/provide before, I will take a look.
I am using Vue with with nw.js without issues expect cross window data binding which has this issue and the other one about memory leak.

**Comment by posva** [comment]
Actually, just keep it that way, Vuex is probably the way to go 🙂

**Comment by yyx990803** [comment]
This is probably caused by the same fundamental issues in a multi-window nw.js environment. I'll keep #5356 open for possible future improvement, but it seems to be quite a niche case and is low priority for the moment.
