### ISSUE TITLE
`server-rendered="true"` generated code (and HTTP response) is not HTML5 compliant

### ISSUE THREAD

**Issue by Haeresis** [vuejs/vue#5358]
### What problem does this feature solve?
I understand what @yyx990803 said when he say :

Vue template respect the valid HTML syntax

The output of Vue (e.g. generating it from SSR or client-side) respect the fully-valid HTML to allows all indexer to correctly understand the code. And I understand why `data-v-` is not useful.

OK. Fine.

So what about `server-rendered="true"` property that is generated at the final HTML render ? That is the only thing that not allows a page gererated from server-side with `vue-server-renderer` to be fully-valid HTML.

What is the exact role of `server-rendered="true"` value ? Could not be a way to generate it into `data-server-rendered="true"` ?

If I remove it like that, using `response.send(renderer.renderToString(...).replace('server-rendered="true"', ""))`, which side-effect after ?

And how remove it with the renderer.renderToStream method because this is « lost » into chunck part.

### What does the proposed API look like?
The generated code could be :

```js
<div data-server-rendered="true">....</div>
```

and the HTML from server-side will be fully valid HTML5

That could allows project where a full HTML5 compliance is required by the customer.

**Comment by yyx990803** [comment]
This is already implemented and will be out in next release.
