### ISSUE TITLE
Event.$on runs its callback function when the componenet is created, despite the $emitter has not emitted any event

### ISSUE THREAD

**Issue by Zedonboy** [vuejs/vue#5365]
### Version
2.2.6

### Reproduction link
[https://www.no-link.com](https://www.no-link.com)

### Steps to reproduce
Hello guys i add an event listener to my component at the created() function when i tried running the app, the event listener callback runs the `alert('am handling') in it without being called by the emitter
my code

my navbar component
```
<template>
<li><a @click="Event.$emit('login')" class="uk-button uk-button-text" href="#">Login</a></li>
<li><a class="uk-button uk-button-text" href="#">Signup</a></li>
</template>
```
my login component
```
<template>
<div class="modal" :class="{'is-active':show_modal}">
  <div class="modal-background"></div>
</template>
<script>
created(){ Event.$on('login', alert('am handling')) // for debugging purposes
</script>
```
Globals  `window.Event = Vue();`
when i run it, the alert shows, when i have not triggered the event............... Please whats wrong

### What is expected?
For the listener callback to be activate when an event is emitted

### What is actually happening?
the callback just runs

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. The bot closed your issue for a reason.
Thanks!
