### ISSUE TITLE
Async Component Id based on Component name not resolved as kebab-case

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5367]
### What problem does this feature solve?
This feature solves the naming of the component

for example when i'm doing an async import using webpack like this

```js
import Vue from 'vue';

function asyncComponents(components) {
    return components.reduce((components, component) => {
        components[component] = () =>
            import (`./${component}.vue`);
        let name = `Teacher${component}`;
        Vue.component(name, components[component]);
        return components;
    }, {})
}

export default {
    ...asyncComponents([
        'Main',
        'Dashboard',
        'Subjects',
        'SubjectCard',
        'Schedule',
        'StudentGradeCard'
    ])
};
```
The id of the the component

will be

teacherstudentgradecard

instead of

teacher-student-grade-card

### What does the proposed API look like?
the out put must be kebab-case

**Comment by posva** [comment]
It seems to be working nice: http://jsfiddle.net/posva/zow5v2gf/
