### ISSUE TITLE
Update (hook) not called inside custom directive

### ISSUE THREAD

**Issue by hidegh** [vuejs/vue#5371]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/hidegh/a196s9yw/](https://jsfiddle.net/hidegh/a196s9yw/)

### Steps to reproduce
Change value in input box...

### What is expected?
Console output

### What is actually happening?
Update method does not get called

---
Yes, I wan't to use directive, not component. So i'm not searching for alt. methods to solve this...

**Comment by posva** [comment]
Hello, that is working as expected, the updated hook triggers when the component is updated. More at https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions
I don't know what your use case is but you should probably ask a question on the forums, maybe setting up some listeners is enough for you. Cheers.

**Comment by hidegh** [comment]
@posva IMHO in my provided sample the update hook is not called. It's clearly seen in the sample, which is created based on the link you provided - this means: this is either a **bug** or the documentation is missing some detail - if something similar was able to achieve as newbie in 30-60 mins on Knockout JS and not aft. hours of googling with VUE, maybe there's something missing or wrong...

 **i'm using a custom directive against an input element (not component).** the inserted/bind hooks are working fine... due to breaking changes (or just bad fiddler codes) most of the samples on this topic simply does not work.

btw: what originally was trying to achieve is a similar functionality as the binding handler override in **Knockout JS**, where with a simple code it's possible to: check if element is of a special type, if so, then execute custom two-way-binding (set/get on updates), if not then just call original handlers...

**Comment by posva** [comment]
This is an example of how the update works: https://jsfiddle.net/posva/qqjnngdz/
It's when the element/component gets updated, in the dom. Hope it helps, cheers

**Comment by hidegh** [comment]
*Thank* you for the provided sample, it took me some time to realize how it
works,* but the way it works is far away from any reasonable
behavior*...(unlike
initialized and bind events which IMHO works as they expected from anyone
who used MVVM)...

In the provided example event is raised, but behavior is different than
expected. *if you change value inside this input <input
v-demo-input="messageInput">, no update event is raised inside the
demoInput directive. *and if you change value inside this input <input
type="text" v-model="v"> the demoInput directive's update event is raised,
despite no change...

...so changes from UI element to model are not raising update event...

It just seems to work. And with experiences with other MVVM *this behaviour
is rather odd, than normal. *Furthermore, as I already stated - this
discussion started, because none of the available samples on google gave a
link to a working result...so a single working sample for a custom two-way
binding directive with hooks could save us all this.

what I need is the code below, with a working update event (hook) when
value inside model or in the UI changes...*or an explanation* why modifying
input (in the code below) does not raise update hook, but the binding does
rises the inserted and bind hook on the given input.

<div id="vue">
  <input v-demo-input="messageInput">
</div>

Vue.directive('demoInput', {
  isLiteral: false,
  isEmpty: false,
  twoWay: true,
  inserted: function(el) {
    console.log('inserted input')
  },
  update: function(el, binding, vnode, oldVnode) {
    // do something based on the updated value
    // this will also be called for the initial value
    console.log('update input')

// here i need to add code to set directly a value on an element or in case
it's a special UI element, use jQuery call to communicate with it...

  },
  bind: function(el, binding, vnode) {
    console.log('bind input')
    el.value = binding.value;
  }
})

new Vue({
  el: '#vue',
  data: {
    messageInput: 'hello input!'
  }
})

**Comment by hidegh** [comment]
**Thank** you for the provided sample, it took me some time to realize how it works, **but the way it works is far away from any reasonable** behavior...(unlike initialized and bind events which IMHO works as they expected from anyone who used MVVM)...

In the provided example event is raised, but behavior is different than expected. **if you change value inside this input <input v-demo-input="messageInput">, no update event is raised inside the
demoInput directive** and if you change value inside this input <input type="text" v-model="v"> the demoInput directive's update event is raised, despite no change...

**...so changes from UI element (with the given custom directive) to model are not raising update event...**

It just seems to work. And with experiences with other MVVM **this behaviour is rather odd, than normal** (comparing to KnockoutJS f. e.). Furthermore, as I already stated - this discussion started, because none of the available samples on google gave a link to a working result...so a single working sample for a custom two-way binding directive with hooks could save us all this.

what I need is the code below, with a working update event (hook) when value inside model or in the UI changes...**or an explanation** why modifying input (in the code below) does not raise update hook, but the binding does rises the inserted and bind hook on the given input.

```
<div id="vue">
  <input v-demo-input="messageInput">
</div>

Vue.directive('demoInput', {
  isLiteral: false,
  isEmpty: false,
  twoWay: true,
  inserted: function(el) {
    console.log('inserted input')
  },
  update: function(el, binding, vnode, oldVnode) {
    // do something based on the updated value
    // this will also be called for the initial value
    console.log('update input')

// here i need to add code to set directly a value on an element or in case it's a special UI element, use jQuery call to communicate with it...

  },
  bind: function(el, binding, vnode) {
    console.log('bind input')
    el.value = binding.value;
  }
})

new Vue({
  el: '#vue',
  data: {
    messageInput: 'hello input!'
  }
})
```

**Comment by posva** [comment]
It's when the dom **gets patched**, and it gets patched when things change. That's why the input element gets _updated_ when an adjacent content is updated too
