### ISSUE TITLE
How to use vuejs with postgresql ?

### ISSUE THREAD

**Issue by lyquocnam** [vuejs/vue#5372]
hi everyone, i tried to use vuejs with postgresql, i use Sequelize, but this error when run:
```
These dependencies were not found:

* fs in ./~/pgpass/lib/index.js, ./~/bindings/bindings.js
* dgram in ./~/native-dns/lib/server.js, ./~/native-dns/li

To install them, you can run: npm install --save fs dgram
```
so i tried install them: 
`npm install --save fs dgram`
but still error, please help !

**Comment by sirlancelot** [comment]
Looks like an issue with Sequelize as Vue has nothing to do with those modules.
