### ISSUE TITLE
Binding promises

### ISSUE THREAD

**Issue by buhrmi** [vuejs/vue#5373]
### What problem does this feature solve?
I have an array of IDs and I'd like to show some data that is returned by a promise for each of these IDs.

### What does the proposed API look like?
Assume `getDataUrl` returns a promise. It would be cool if one can simply write:

    <img :src="getDataUrl(id)" v-for="id in ids">

**Comment by yyx990803** [comment]
See https://github.com/foxbenjaminfox/vue-async-computed/blob/master/README.md
