### ISSUE TITLE
For clarification and removing confusion 'this.props.name', 'this.data.name', 'this.methods.name' needed emergency!

### ISSUE THREAD

**Issue by ShuvoHabib** [vuejs/vue#5375]
### What problem does this feature solve?
I'm stuck in a lot of problem with these issues. Like I'm passing a prop from parent element to child component. In the child component I imported a `mixin` & the `mixin` has got a function with the same name. Then the props overlaps with `mixin` functions and throws an error. And sometime we get confused and need to check every `methods`, `props` or `data` to know where does this `this.name` came from. Every time we need to answer the same question, Is this from a `method` or `props` , `data` or from `mixin` ? :/

As.. Props , data and methods are different, We badly need a namespace to differentiate them. They should not be called by the same way, I mean accessing by `this` only. Thanks :)

### What does the proposed API look like?
For props, this.props.name,
For Data, this.data.name
For Methods, this.methods.name
For Mixins, this.[mixinName].name

**Comment by fnlctrl** [comment]
Hi, thanks for filing this issue. We already have this.$data(https://vuejs.org/v2/api/#vm-data) and this.$props(https://vuejs.org/v2/api/#vm-props), and currently there's no need for a `this.$methods`.

**Comment by yyx990803** [comment]
You already have `this.$props` and `this.$data`. If you want to you can just use those everywhere. Namespace for mixins don't make sense to me - use mixins sparingly, and in particular, mixins should only register very unique props/data/methods because you don't know what component they might get mixed into.

**Comment by ShuvoHabib** [comment]
Thanks a lot for the clarification . I am going to use it.
