### ISSUE TITLE
Adding an unmount process

### ISSUE THREAD

**Issue by excid3** [vuejs/vue#5380]
### What problem does this feature solve?
I've been working with @jeffreyguenther on making a VueJS app compatible with Turbolinks and so far it's been pretty good. For anyone not familiar with Turbolinks, it replaces link clicks with AJAX requests so the browser doesn't have to reload the CSS/JS and it provides an HTML cache to make perceived load times faster.

Vue works pretty well with Turbolinks out of the box, the problem is that Vue doesn't have a way to fully unmount the component's template. Since the original element on the gets replaced with the Vue template, Turbolinks caches the Vue template, not the original element. That means that Vue naturally can't re-render if you view a cached page and unfortunately there's no built-in way for us to clean up Vue's html on one of the Turbolinks lifecycle events.

We built a little mixin for Vue that caches the original element to an internal variable and on the `destroyed` event we replace the Vue $el with the original element again. For reference, this is what we did: https://github.com/jeffreyguenther/vue-turbolinks/blob/master/index.js

This works well but it would be nice if Vue provided a way to return to the original element. It would provide a fully safe cleanup mechanism inside Vue and means that Turbolinks doesn't have to be intertwined inside of Vue's lifecycle events.

I feel like it makes sense to have a way to fully unmount the Vue app's template alongside of the existing $destroy method that Vue provides. I'd love to hear what you guys think about this idea!

### What does the proposed API look like?
This could either be an option you can pass into $destroy or a separate unmountComponent method that replaces the element. It could also be something passed in with the constructor so it could cache that original element then and remember that later on $destroy. I'm not quite sure what the best solution would look like for this but would love to hear some thoughts on it!

**Comment by posva** [comment]
Usually, we don't need to manipulate the element itself so this use case is pretty much a niche case and since it's fully doable in userland I really don't see this feature to be worth the cost.
What will bring this feature to Vue that it doesn't have yet?

**Comment by jeffreyguenther** [comment]
Ideally, it would make the the Vue component lifecycle idempotent. The destroy process would not only remove listeners and watchers. It would return the DOM to it's pre-mount state.

With the current implementation you can't re-mount a component after the component has been destroyed because the DOM has been changed and is likely missing an element with the id `<div id=#mount>` or <custom-element> the Vue component targets.

**Comment by yyx990803** [comment]
This seems to be easily doable in userland (If I were to implement it it would something very similar to what you did in the turbolink adaptor mixin), and imo a pretty niche case - which means we should probably keep it in userland.

**Comment by jeffreyguenther** [comment]
Thanks for reviewing @yyx990803! If you have any suggestions on how we can improve the mixin, please let us know!
