### ISSUE TITLE
Add scopedSlots to functional component context

### ISSUE THREAD

**Issue by kaleb** [vuejs/vue#5381]
### What problem does this feature solve?
Currently, when attempting to use scoped slots in a functional component, the slot is entirely missing in the context.slots() and context.children. Example: http://codepen.io/kaleb/pen/qrwwye?editors=1010

### What does the proposed API look like?
    render(h, ctx) {
      var scopedSlots = ctx.scopedSlots();
      return h('ul', ctx.props.items.map(i => h('li', {}, scopedSlots.default ? scopedSlots({value: i}) : i)));
    }

**Comment by sqal** [comment]
They are available under context.data.scopedSlotst

**Comment by posva** [comment]
More info at https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth
