### ISSUE TITLE
memory leaks in vue2.0 framework

### ISSUE THREAD

**Issue by brunoduan** [vuejs/vue#5385]
### Version
2.2.6

### Reproduction link
[https://github.com/brunoduan/brunoduan.github.io/blob/master/assets/data/Qiqu-playground.js](https://github.com/brunoduan/brunoduan.github.io/blob/master/assets/data/Qiqu-playground.js)

### Steps to reproduce
If we inject an object into VueComponent as below:
```
var store = new _vuex2.default.Store({
actions: _extends({}, appActions),
modules: {
app: _app2.default
}
});
new Vue(Vue.util.extend({ el: '#root', store: store }, _Qiqu2.default));
```
the Vue framework would remain all the references of Store objects and cause memory leaks happen.

We can get a compelete example bundle for reproducing the issue [here](https://github.com/brunoduan/brunoduan.github.io/blob/master/assets/data/Qiqu-playground.js)

### What is expected?
Run this bundle on Weex platform and lets take heap snapshots and compare them as below:
![Store leak](https://github.com/brunoduan/brunoduan.github.io/blob/master/assets/image/one-vue-component-memoryleak-store.png)

### What is actually happening?
From above we would found out:
* not all dependencies's subscribers get teardown
* The VueComponent tree remains in memory

---
* we need to set Watcher.vm to nulls.
* we need to set the reference of root VueComponent and destroy the document.

**Comment by yyx990803** [comment]
Please improve the reproduction steps - a big bundle file is next to useless for debugging. You need to provide your source code in a repository, with steps on how to actually run the code to produce the behavior you described.
