### ISSUE TITLE
Some error messages are not detailed enough to locate the problem

### ISSUE THREAD

**Issue by ydogus** [vuejs/vue#5389]
### Version
2.2.4

### Reproduction link
[https://jsfiddle.net/qk4ofq1q/](https://jsfiddle.net/qk4ofq1q/)

### Steps to reproduce
1. Create a component which will raise any error. (In my reproduction sample I defined a required prop and didn't referenced it later)
2. Create another component which will use the first component in its template.

### What is expected?
When an error occures in a component, I think error message should also contain the components name tree. Because when the error occurred from a common component like `<some-button>` we can't locate which component included this node.
So a detailed error message is expected.

Like:
> [Vue warn]: Missing required prop: "must" (found in <Demo>)
> Component Trace: Container (err line) -> Demo

### What is actually happening?
When an error is raised, browser's console mentions only the problematic component. Not it's parents...
> [Vue warn]: Missing required prop: "must" (found in <Demo>)

---
My application is built by webpack/vue-loader. So it is much harder to locate the problem as the source codes are being parsed by some tools.
So I think when this issue is solved, webpack/vue-loader structured projects will receive those detailed errors too?

**Comment by gebilaoxiong** [comment]
the `component name tree` sounds very nice
