### ISSUE TITLE
VueJS breaks Three.JS

### ISSUE THREAD

**Issue by brianrusso** [vuejs/vue#5390]
### Version
2.2.6

### Reproduction link
[https://codepen.io/brianrusso/pen/WpBYeP](https://codepen.io/brianrusso/pen/WpBYeP)

### Steps to reproduce
Basically if you put a three.js canvas INSIDE a vue app it breaks three.js.
broken example - https://codepen.io/brianrusso/pen/WpBYeP

If you take the exact same three.js code and have it run ADJACENT to vue; it works fine.
working example - https://codepen.io/brianrusso/pen/LWoXPW

I'm not sure if three.js thinks it is 'hidden' or something (?).

So in the example code, three.js is rendering into div#cube. When you put div#cube inside div#app; it renders nothing. I have similar code that works fine with D3. I'm not sure if this is some weird interaction between WebGLRenderer and Vue or what.

### What is expected?
Spinning green box

### What is actually happening?
Blank canvas.

---
I ran into this developing a vue app which includes embedded three.js.

**Comment by posva** [comment]
Both of your examples work...

**Comment by brianrusso** [comment]
Yeah that's because I figured out what the problem is. Naturally right after I submitted the bug report :-/

Basically you just have to create the three.js object AFTER the parent vue app is mounted.
