### ISSUE TITLE
Duplicate attribute class in MS Edge

### ISSUE THREAD

**Issue by Nirazul** [vuejs/vue#5394]
### Version
2.2.6

### Reproduction link
[http://codepen.io/anon/pen/WGyrdz](http://codepen.io/anon/pen/WGyrdz)

### Steps to reproduce
Open the codepen with MS Edge devtools open

### What is expected?
No warning. When you execute `el.outerHTML` within vuejs while the element is being mounted, you will see that the class attribute is duplicated.

### What is actually happening?
A warning (duplicate attribute class)

---
This has been dealt with in #3929 already but it seems that MS Edge 38 is not correctly handled.

**Comment by sqal** [comment]
This codepen uses Vue 2.0.2 not 2.2.6. There's no warning in latest version of Vue.

**Comment by posva** [comment]
ping @Nirazul Can you try with the latest version, please?

**Comment by sqal** [comment]
@posva ohh I am sorryfor misleading you.. indeed there is a warning

![img1](http://image.prntscr.com/image/04dd0aaaab3a4a40835fd103edf1ef75.png)
