### ISSUE TITLE
Seeking a PDF of Vue documentation

### ISSUE THREAD

**Issue by mroswell** [vuejs/vue#5395]
### What problem does this feature solve?
Do PDFs of vue/vuex/vue-router/vue-loader documentation exist? If so, just the URLs would be helpful. 

If not: I seek a bound paper copies of the docs, to mark off features as I learn them, to see both what I know, and what is left to be learned. I don't really want to just print the GitHub markdown pages, as they would print out of order. It would be easier just to open existing PDFs, and send to a print shop for binding. 

If PDFs will not be offered through the documentation, it would be helpful, at least, to have a script to generate one for each repo (vue, vuex, etc.)

### What does the proposed API look like?
Perhaps combination of a scraping project with a markdown-to-PDF generation library? but hopefully integrated directly into the guides. Something like: https://vuejs.org/v2/guide/pdf

**Comment by posva** [comment]
If you want them online you can clone the projects and have them locally. I am not aware of any PDF, but there may be some. Closing this since it's not directly related to Vue

**Comment by grantcarthew** [comment]
There is an option on GitBook to enable PDF for download. Could you please turn this on? I am going on a flight today and wanted to read the docs whilst offline. I was after both Vue and Vuex.

**Comment by posva** [comment]
Docs are not a gitbok. Clone the repos, really, it's the easiest way

**Comment by FirstWorldSlardar** [comment]
As I have an E-ink device, having the doc in .pdf or .epub would be much appreciated, though I know it is not requested by many

**Comment by glumanda99** [comment]
Yes, I'm looking for the same reason as @FirstWorldSlardar. To read them on an ebook reader while being off the grid. wish it would be on ReadTheDocs we could easily download a PDF then, but I guess our only chance is to somewhat generate them by our own. I'm gonna try it with pandoc and https://pandoc.org/epub.html

**Comment by glumanda99** [comment]
@FirstWorldSlardar I just created the PDF myself, looks fine. Though there are some `{{ raw }}` messages, but shouldn't be big of an issue.

[Vue.js - Guide.pdf](https://github.com/vuejs/vue/files/2177618/vue.pdf)

**Comment by sebastianrothbucher** [comment]
For those who want sth similar (or an updated version): here's how to create an ebook (or PDF) from the docs: https://gist.github.com/sebastianrothbucher/dd2a0ac8f11637375f8e4af79cbeae1e - for pdf just replace ```-o ALL.epub``` with ```-o ALL.pdf```. Maybe this is helpful for s/o

**Comment by mroswell** [comment]
A couple of years ago I manually created a pdf and bought a related domain
name. I think it was vuepdfdocs or something like that... Ah, here it is:
VueDocsPDF.com and VueDocsPDF.org. I never actually put the site up.

If anyone would like to manage such a site and keep current PDF docs there,
let me know, and I'll do my best to figure out how to transfer. If multiple
people respond, I'll ask you to "make the case" for being the best one to
maintain this.

When I created the docs, (that I printed, and read like a book) I made sure
to make the document MUCH shorter than the default. I remember that when I
just did straight HTML to PDF it was spread across way too many pages.

I see above, someone proposed ReadTheDocs, with a PDF download. That sounds
like a better solution, actually.

Margie

--
http://CommitteeMaps.org
http://SugarWars.com

**Comment by RichardJECooke** [comment]
My country has intermittent electricity access. It would be great to have the Vue docs available as an .epub file for offline use. It's a pity this issue has been closed. There are packages these days that could easily convert the generated HTML site into an epub each time it is published.

**Comment by osbre** [comment]
I've used https://github.com/paperbackapp/web-printer to make this PDF of Vue 3.2 documentation:

[Vue 3.2 Documentation.pdf](https://github.com/vuejs/vue/files/10775179/Vue.3.2.Documentation.pdf)

Hope it helps.

**Comment by osbre** [comment]
[Vue 3.2 Documentation with Composition API.pdf](https://github.com/vuejs/vue/files/10776864/Vue.3.2.Documentation.with.Composition.API.pdf)

And here is a version with Composition API.
