### ISSUE TITLE
 Cannot detect change of array from checkbox v-model?

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue#5398]
### Version
2.2.6

### Reproduction link
[https://fiddle.jshell.net/whoisbigZ/ec11h6gj/2/](https://fiddle.jshell.net/whoisbigZ/ec11h6gj/2/)

### Steps to reproduce
I use deep watch to trace an object. See source code, it's very simple.

### What is expected?
I hope the setter of v-model should notice deep watch. Why not?

### What is actually happening?
But I found the vue cannot detect the array change from checkbox.

---
I know some caveats about detect the changes of array, but I just use v-model in checkbox.

**Comment by posva** [comment]
You're falling under this caveat: https://vuejs.org/v2/guide/list.html#Caveats
You can use an object to overcome it (in many ways). Ex: instead of an array for `d` use an object: `{0: true, 1: false}` You can also have an array of objects: `d: [{model: true}, {model:false}]`

**Comment by bigZ-again** [comment]
I know everything that @posva said.
But I use v-model to bind a element of array to a input tag with type is checkbox, I don't directly set any element of array,  It been done by vue's v-model.
In my demo, I use v-model to bind a element of array to other input tag which type isn't checkbox, the change can be detected. 
Why checkbox is NOK! In this case, why v-model don't use Vue.set to set the element of array.
Maybe it isn't a issue, or feature request, PLEASE use vue.set when use v-model to bind a element of array to a checkbox.

**Comment by posva** [comment]
I'm giving it a deeper look. I'm not sure it's actually intended

**Comment by maximelebreton** [comment]
I think I have the same problem: 
https://jsfiddle.net/dq90hkb8/ 
`Vue 2.2.1`

**Comment by bigZ-again** [comment]
@maximelebreton Because storedValues.three isn't exist.
You can ref: https://jsfiddle.net/y43nse2o/1/
