### ISSUE TITLE
Another implement of popup by adding a attribute popupTemplate into vm

### ISSUE THREAD

**Issue by geguihong** [vuejs/vue#5399]
### What problem does this feature solve?
Many popup needs their logical parent's data.For example, a modal viewing a picture.
```html
<div id="app">{{imgSrc}}<div>
...
<div id="modal"><img :src="imgSrc"></img></div>
```
The modal use the "imgSrc" of vm#app.Since the modal has to be put at the end of body tag rather than in the vm#app,they can't put into the same vm and can't share the same data directly.They have to communicate by other way.

### What does the proposed API look like?
It looks like this.
```js
var vm = new Vue({
    popupTemplate: '<div v-if="show">{{text}}</div>',
    template: '<div>hello</div>',
    data: {
        text: "world",
        show: true
    },
    el: '#app'
})
```
The popupTemplate will be appended into the end of the Body tag and destroyed when the vm was destroyed.The popupTemplate shared the same data and methods and so on.
This feature reaches out of my capacity.can you tell me if it deserves implementing? Thank u!

**Comment by posva** [comment]
Use something like https://github.com/LinusBorg/portal-vue to move DOM around
