### ISSUE TITLE
Image binding error handeling

### ISSUE THREAD

**Issue by StevenPeeters** [vuejs/vue#5404]
### What problem does this feature solve?
The problem I'm trying to solve is when an img source is unavailable, I want a standard img to show instead. 
So what I have now is somthing like this: 
 
    <img v-bind:src="imgUrl" onerror="this.onerror=null;this.src='imagefound.gif';"> 
 
But this doesn't seem to do the trick.
I would like to have something like this:
 
    imgUrl: function() {
            var toReturn = Config.articlePlaceholder;
            // Probably need to do a check with the custom path in the if test, 
            // No problem to access the path al all times during this function
            if ( IMG Is FOUND // test with custom path ) {
                toReturn = "/Custompath";
            } else {
                // Return default img
                toReturn = "/houseStyle/img/default.png";
            }

            return toReturn;
        },

### What does the proposed API look like?
the call could look like this, path.doesExist
And you could use it like this
if (path.doesExist)
    return path;
else
    return defaultPath

**Comment by posva** [comment]
Hey, thanks for the interest. Unfortunately, this is something that is better handled on userland as a standalone component. For your specific use case, a CSS only solution is actually possible: https://bitsofco.de/styling-broken-images/

**Comment by RachelScodes** [comment]
this directly contradicts a similar question from last year: https://github.com/vuejs/vue/issues/3261

is the @error event on img tags deprecated?

**Comment by snsxn** [comment]
The **@error** event on img tags is not deprecated.

A working solution can be:

```html
<img :src="imgUrl" @error="imgUrlAlt">
```

And a method:

```javascript
imgUrlAlt(event) {
    event.target.src = "working-image.jpg"
}
```

**Comment by posva** [comment]
instead of setting `event.target.src`, you should set `imgUrl`. If it's a prop have a value in data and use a computed property that uses the data but fallbacks to the data. This allows you to have one single source of truth.

@RachelScodes The css approach is easier for image fallback imo. The `@error` allows you to trigger custom js, so more flexible

**Comment by tyrw** [comment]
To save others time: the CSS fix referenced isn't fully supported in Safari (desktop or iOS). It will work to style the text notifying you that the image is broken, but that is all for Safari.

`@error` looks like the best bet for real compatibility

**Comment by techcodex** [comment]
How I can pass multiple parameters to method that is calling on error ? @error('param1','param2') then how can I access event ?
