### ISSUE TITLE
Background image does not display when image url with parentheses

### ISSUE THREAD

**Issue by menyouneko** [vuejs/vue#5405]
### Version
2.2.6

### Reproduction link
[http://jsbin.com/zopecotada/edit?html,css,js,output](http://jsbin.com/zopecotada/edit?html,css,js,output)

### Steps to reproduce
Binding a image url to the style of background-image(image url with parentheses)
e.g. http://120.237.243.5/(with-parenthesis).gif

### What is expected?
Background image display correctly

### What is actually happening?
Background image does not display

---
I bind a image url to the style of the background image attribute. When the url with parentheses, the background image will not display.

My English is not good, I wish I could describe the problem clearly. :D

**Comment by yyx990803** [comment]
`url(...(...))` 这样明显是有歧义的，要用引号框起来... `url('...(...)')`
