### ISSUE TITLE
我想手抄一遍Vue，想了解作者用的什么ide，毕竟工欲善其事必先利其器嘛。。。

### ISSUE THREAD

**Issue by Mryong** [vuejs/vue#5406]
我想手抄一遍Vue，想了解作者用的什么ide，毕竟工欲善其事必先利其器嘛。。。

**Comment by ccforward** [comment]
这种事情不要在issue里说   论坛 其他社区都可以

但是我知道 Evan 用的是  sublime

**Comment by Kingwl** [comment]
竟然不是Atom🌚。。。
