### ISSUE TITLE
Dynamic Components isn't support event 

### ISSUE THREAD

**Issue by jason-chang** [vuejs/vue#5407]
### What problem does this feature solve?
Dynamic Components isn't support event 

### What does the proposed API look like?
<component :is="getComponentName(item.type)" :data="item" @delete="delete(key)"></component>

Got a exception like blow:

- avoid using JavaScript unary operator as property name: "delete(key)" in expression v-on:delete="delete(key)"

**Comment by simplesmiler** [comment]
That's because you are using `delete` as a method name. Rename the method and the issue will go away.

**Comment by jason-chang** [comment]
thinks i found that
