### ISSUE TITLE
component reset when other data changed.

### ISSUE THREAD

**Issue by vvpvvp** [vuejs/vue#5408]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/vvpvvp/n70qLojs](https://jsfiddle.net/vvpvvp/n70qLojs)

### Steps to reproduce
I wrote a demo for reproduce it.
step1: click the word 'click Me!', it's become 'clicked'
step2: click the button "添加"
result: word reset.

### What is expected?
component will not reset when other data changed.

### What is actually happening?
component reset when other data changed.

**Comment by yyx990803** [comment]
The last `<test-b>` belongs to the same parent with the `v-for` list, but is un-keyed - this makes the list "partially-keyed" and can lead to unexpected behavior.

Simply give it a key fixes it: https://jsfiddle.net/yyx990803/n70qLojs/3/

Also, you are using objects as keys, which is not suggested either. You should use unique strings or numbers instead.
