### ISSUE TITLE
v-for component error

### ISSUE THREAD

**Issue by vvpvvp** [vuejs/vue#5410]
### Version
2.2.6

### Reproduction link
[http://codepen.io/vvpvvp/pen/oZKpgE](http://codepen.io/vvpvvp/pen/oZKpgE)

### Steps to reproduce
step1: click "add" twice  
step2: click the last line  'click me'.  
step3: click the first line  'delete'.  

Test any line without last line.  

### What is expected?
Delete the first line component

### What is actually happening?
Delete the last line component

**Comment by yyx990803** [comment]
You are using the index as the key... which is the same as no key at all. You should give each of your data objects a unique id so that they can be keyed properly.

**Comment by wostex** [comment]
Change :key="index" to :key="item.value" == profit.

Your delete function is ok - it deletes the element of list you clicked.

**Comment by vvpvvp** [comment]
@wostex if changed to :key="item.value", and when the value is all equaled, it will be failed.

> Your delete function is ok - it deletes the list element you clicked.

Yes, it's deletes the list element, but remove the component incorrect.
And I want to ask @yyx990803  how can I do when there is no unique id ?

**Comment by ericmdantas** [comment]
@vvpvvp maybe create an "unique" property in your object. Something like:

```js
add: function() {
      this.list.push({
        _createdAt: Date.now(), // here
        value: 1 + this.list.length
      });
    },
```

**Comment by vvpvvp** [comment]
yes, that's the way I think about.
but I can't aways do that things in my code.
there is so many list control stuffs.
