### ISSUE TITLE
Caching computed properties which return function or possibility to pass arguments

### ISSUE THREAD

**Issue by evsign** [vuejs/vue#5418]
### What problem does this feature solve?
Now exist only one (not documented) way for receiving arguments in computed property. For achieve this you must return function with needed signature. But this is not cacheable and every time when any data changed this function will be triggered and component rerendered (if i correctly understand).

I ran into this when writing own internalization plugin. I create computed property which return function which receive additional parameters needed for translation and this function (returned) trigger reactive property getter what would help to fall into dependency of this property.

Example pseudocode:
```javascript
let langStore = new Vue({
    data: {
       lang: 'en'
    }
});

computed: {
    t() {
        return (text, params) => {
            console.log('rerender');

            //dependency tracking;
            langStore.lang;

            return translate(text, params);
        }
    }
}
```
This do the job, but every time component is rerendered if any data changed.
https://github.com/kazupon/vue-i18n is with the same issue.

Or maybe exists another way to achieve needed behavior without this issue? Thanks.

P.S. I'm beginning to hear how cooler start working faster on my i7 when i start typing in input with v-model on page with 50+ translated strings (50+ computed property usings). :smile:
### What does the proposed API look like?
Don't know)

**Comment by yyx990803** [comment]
It's undocumented because it's misusing computed properties - this is the same with just a method... And it's uncacheable because arbitrary arguments can be passed, and Vuejobs can't safely assume how to serialize them. Your best bet is implementing a caching mechanism yourself in the translate function.

**Comment by kazupon** [comment]
Evan mentioned it, this is undocumented. I don't recommended it. I'll try to improve the other ways.
