### ISSUE TITLE
v-repeat Pagination

### ISSUE THREAD

**Issue by masoodahm** [vuejs/vue#542]
hi, I have an issue with pagination I have the following code

<pre><code>
Vue.filter('paginate', function(value){
    
    var length = value.length;
    if(length > 10)
    {
        App.userList.pages = Math.ceil(length / 10); 
    }
    else{
        App.userList.pages = 1;
    }
    
    App.userList.createPages();
    
    return value.filter(function(item, index){
        var indices = App.userList.currentPage * 10;
        if(index &lt; indices && index &gt; indices - 10)
        {
            return item;
        }        
    }); 
});
</code></pre>

and then in my view

<pre><code>
v-repeat="list | filterBy searchText in username | paginate" 
</code></pre>

it works fine but the problem is it only works when the page is loaded. I want my items v-repeat to update when App.userList.pages value updates.

**Comment by atheleron** [comment]
@masoodahm can you please post your solution Im trying to load Laravel 5 pagination with ajax but then i get pagination from 123**4**567891011121314 to 38 instead 123**4**5..38 so it actually works but pagination is huuge hehe
