### ISSUE TITLE
In development mode,  Vue Warn

### ISSUE THREAD

**Issue by KellerLong** [vuejs/vue#5422]
### Version
2.2.6

### Reproduction link
[https://jsbin.com/wevinulemu/edit?html,output](https://jsbin.com/wevinulemu/edit?html,output)

### Steps to reproduce
```
> parent componts

<template>
  <div>
    {{text}}
    <demo-input v-model="text" > </demo-input>

  </div>
</template>
<script>
  import DemoInput     from 'components/input';

  export default {
    data () {
      return {
        text: ''
      };
    },
    components: {
      DemoInput
    }
  };
</script>
```

```
> childern componts

<template>
  <div>
    <input
      type="text"
      class="input-text"
      @input="updateInput($event.target.value)"
      :value="inputValue"
      ref="input"
      :placeholder="placeholder"
    >
  </div>
</template>

<script>
  import './style.less';

  export default {
    data () {
      return {

      };
    },
    props: {
      value: {
        default() {
          return '';
        }
      },
      placeholder: {
        type: String,
        default() {
          return '';
        }
      }
    },
    computed: {
      inputValue() {
        return this.value;
      }
    },
    methods: {
      updateInput(value) {
        this.$emit('input', value);
      }
    }
  }
</script>

```

> When input to content
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 

### What is expected?
not have warn.

### What is actually happening?
when update data->text, have warn.

---
Please forgive for my English is not good.

**Comment by caiquecastro** [comment]
Why don't you use :value="value" on your child component? You should not use computed properties for your model.

**Comment by LinusBorg** [comment]
> https://jsbin.com/wevinulemu/edit?html,output

This code is not runnnable, so it does not count as a reproduction. Please provide a reproduction.

**Comment by KellerLong** [comment]
jdbin.com pop: "Sorry this bin is too large for us to save"
so,  I submitted the code to " https://github.com/KellerLong/vue-question.git "
and 
use  :value="value" have error too
_______________________________________________________
Please forgive for my English is not good.

**Comment by LinusBorg** [comment]
Sorry, I can't read a whole app's bundled webpack code. Please provide source code for. *minimal* reproduction - that means the minimum of code for this problem to appear. 

Sending us your whole app will make our work very hard.

**Comment by KellerLong** [comment]
Sorry, Inconvenience to the team, But ,This problem only occurs when 'new webpack.HotModuleReplacementPlugin()' and develop state is used,  Can me create a webpack-cli?

**Comment by LinusBorg** [comment]
Sure.

**Comment by KellerLong** [comment]
Sorry, I can't reproduce, Demo is no problem.I don't know why there's such a mistake,I'll think about what's wrong,   ~_~|||

**Comment by KellerLong** [comment]
It's been a lot of days

**Comment by LinusBorg** [comment]
I will close this, you can open a new issue with a proper reproduction if you succeed in recreating the problem.
