### ISSUE TITLE
Need types for Vue v1.0.28 and Typescript v1.8.5

### ISSUE THREAD

**Issue by JonathanLoscalzo** [vuejs/vue#5424]
### What problem does this feature solve?
My project need to use Typescript v1.8.5 and Vue v1.0.28, but I can't find a typed interface to use. 
Anyone who use similar feature, could "pull request" this feature (I thought someone might have these files)

Sorry for my english and if I can help with these implementation files, contact me!

### What does the proposed API look like?
In Vue2, a folder "types" contains types for this version. Something Similar?

**Comment by yyx990803** [comment]
Sorry, but Vue 1 is now in maintenance mode and will only receive critical/security bug fixes. Typing Vue 1 (which itself has un-typed source code) is considerable amount of work and unlikely to be a priority for the team. We are obviously open to community contribution if anyone wants to do it though.
