### ISSUE TITLE
memory leak？ when vue instance destroyed before callBack function return

### ISSUE THREAD

**Issue by gloxing** [vuejs/vue#5430]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
a method has a callBack. when vue instance destroyed before callBack return. will it lead memory leak? and how to avoid

### What is expected?
deal memory leak

### What is actually happening?
memory leak

**Comment by yyx990803** [comment]
Please provide an actual repro.
