### ISSUE TITLE
vue v-show can't render html by use props property?

### ISSUE THREAD

**Issue by pcwang0205** [vuejs/vue#5432]
test.vue
```
<template>
  <div v-show="isShow"></div>
</template>
 <script>
   export default{
      props: {
        isShow: true
      }
   }
 </script>
```
`<test isShow=false></test>`
this is vue demo.
like this, which can't effect.
why ? why? why?

**Comment by simplesmiler** [comment]
`<test :isShow="false"></test>`, [here's why](https://vuejs.org/v2/guide/components.html#Literal-vs-Dynamic).
Please follow [Issue Guidelines](https://github.com/vuejs/vue/blob/master/.github/CONTRIBUTING.md) next time you open an issue.
