### ISSUE TITLE
Component Scoping issue with V-IF and V-ELSE

### ISSUE THREAD

**Issue by GeorgeHanson** [vuejs/vue#5433]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/3Lfrm6ds/1/](https://jsfiddle.net/3Lfrm6ds/1/)

### Steps to reproduce
Looking on the JS Fiddle, you can see I have created a test component which has one named slot. This component also has a computed property which detects whether or not any of the slots are being used.

On the Vue instance I have a simple v-if, with a button which toggles the value showing the next page. On the first page I am rendering the component using the slot. On the second page, I am also rending multiple components not using the slots. Despite this, the first component on the second page thinks it is using a slot.

### What is expected?
The usingSlots computed method to return false for the first component on the second page

### What is actually happening?
It is returning true

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

https://jsfiddle.net/Linusborg/3Lfrm6ds/2/
