### ISSUE TITLE
No style are applied with webpack with the target: node activated

### ISSUE THREAD

**Issue by raultrysw** [vuejs/vue#5435]
### Version
2.2.6

### Reproduction link
[https://github.com/raultrysw/issue-with-vuejs-and-webpack](https://github.com/raultrysw/issue-with-vuejs-and-webpack)

### Steps to reproduce
In the webpack.config.js file, quit the `target: node` option and next make `electron .` in the root folder, you will see that the style in component.vue appears correctly, but if that line is not present, not.

### What is expected?
The style appears whether is present or not `target:node`

### What is actually happening?
If `target: node` is present, the style not appears

**Comment by yyx990803** [comment]
target: node is used by vue-loader to detect server side rendering mode. This is expected behavior. Use target: electron if you are building for electron.

**Comment by raultrysw** [comment]
Thanks to all you!
Vuejs is a great framework for development apps! =)
