### ISSUE TITLE
meta modifier not work 

### ISSUE THREAD

**Issue by FlappyHeart** [vuejs/vue#5439]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/liuchunyao90/t29cxz3d/](https://jsfiddle.net/liuchunyao90/t29cxz3d/)

### Steps to reproduce
Change the "meta" to "ctrl" in the line 6 and press ctrl B, then the counter raise.

Change the "ctrl" to "meta" in the same place and press command B, nothing happened.

### What is expected?
Meta/Command modifier works on my Mac

### What is actually happening?
nothing happened

**Comment by yyx990803** [comment]
Mac does not fire `keyup` when the command key is pressed - it seems the keyup event is intercepted by the OS. But you can use `keydown` instead.

**Comment by kuceram** [comment]
Quite interestingly, when you specify key codes it works:
```
@keyup.91.enter="send"
@keyup.93.enter="send"
```

So are you sure Mac (Chrome) doesn't fire `keyup` event?

One problem with my solution is that it triggers the up event only if you release cmd key (not only enter).
