### ISSUE TITLE
embed标签allowfullscreen="true"解析错误

### ISSUE THREAD

**Issue by leyec** [vuejs/vue#5440]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/27478/](https://jsfiddle.net/50wL7mdz/27478/)

### Steps to reproduce
<embed src="//cloud.video.taobao.com/video/play/v/2002/sid/10552470/uid/1695300927/from/2/f/video.swf" type="application/x-shockwave-flash" allowfullscreen="true">
以上代码经过Vue解析后会变成:
<embed src="//cloud.video.taobao.com/video/play/v/2002/sid/10552470/uid/1695300927/from/2/f/video.swf" type="application/x-shockwave-flash" allowfullscreen="allowfullscreen">
从而造成allowfullscreen失效,无法全屏

### What is expected?
请保持allowfullscreen="true"原始状态吧,不要解析为allowfullscreen="allowfullscreen"

### What is actually happening?
由Vue解析allowfullscreen造成的全屏功能失效

---
第一次提交问题,不太懂规矩,麻烦了

**Comment by yyx990803** [comment]
Vue 的解析并没有错误，`allowfullscreen` 原则上是一个 boolean attribute，用 `"true"` 作为值反而是不正确的。Flash 不能处理 `"true"` 以外的值是 Flash 的问题...

建议用 `<object>` 来嵌：

``` html
<object type="application/x-shockwave-flash">
  <param name=movie value="http://cloud.video.taobao.com/video/play/v/2002/sid/10552470/uid/1695300927/from/2/f/video.swf">
  <param name=allowfullscreen value=true>
</object>
```

**Comment by leyec** [comment]
谢谢,您的分析很透彻.
刚才我用了一个computed属性html,然后用v-html="html"暂时给解决了,因为object标签目前做项目还不能使用,再次感谢这么及时的答复
