### ISSUE TITLE
Can we have a vue init template for weex?

### ISSUE THREAD

**Issue by colwilson** [vuejs/vue#5441]
### What problem does this feature solve?
It would be nice to have a vue template which more closely resembled the current webpack template. i.e. with src/components directory and a src/main.js file and all the niceties that we have become used to. 

### What does the proposed API look like?
vue init weex my-project

**Comment by mage3k** [comment]
You can temporarily use 
```
vue init Jinjiang/weex-template <project-name>
```

and I think you should post it in https://github.com/vuejs/vue-cli

**Comment by LinusBorg** [comment]
> and I think you should file it in https://github.com/vuejs/vue-cli

Correct.
