### ISSUE TITLE
Two way data binding in any HTML Attribute

### ISSUE THREAD

**Issue by montyclt** [vuejs/vue#5442]
### What problem does this feature solve?
I'm making an web application (Server rendered, not SPA), but with some client-side funcionality, such hide element when other element have some value, make HTTP calls or validate some input fields.

Now, I'm using WebComponents (`paper-elements` and others) to make the UI, and Vanilla JavaScript (with some Polyfills, such WebComponents.js or fetch.js) to do the functionality.

So far, however, I have realized that I have many JavaScript lines to do things (such as hiding an input field if a condition is not met) that could be reduced (or even deleted) with a framework like Vue.js and HTML with directives.

My problem is I'm using WebComponents like `paper-input` (By Polymer Project) to making the UI and I need two way data binding, but `v-model` doesn't work in these components because is limited to HTML inputs and some Vue Components.

Paper-input is a simple textfield and use value HTML attribute, but I have others more complex components like address input with 4 textfields and I need two way data binding in `street` or `country` attributes.

I propose a new directive like `v-bind` (to binding in any HTML attribute), but with two way data-binding.

### What does the proposed API look like?
An idea can be, while using a colon (shorthand of `v-bind`) to indicate one way data binding, (e.g. `:disabled="someCondition"`), use two colons to indicate two way data binding in any attribute (e.g. `::value="someData"`).

The directive can be named `v-two` or `v-two-bind`.

**Comment by yyx990803** [comment]
My suggestion: just wrap these paper elements with Vue components. Such combined usage is too niche to warrant adding extra binding syntax.

**Comment by montyclt** [comment]
I can do it for simple components like text-fields or dropdown, but I have more complex components that have multiple inputs, like address input, and in these, I can't use multiple `v-model` to the diferents attributes  (`street`, `country`, `postal-code`) that are changed direcly by the user typing.

I understand the reason why the feauture has been rejected, but could at least help me create my own directive to do this, if it can.

I'm new with Vue.js and I never created a directive, sorry my noob mistakes haha

`Vue.directive('two', {
            twoWay: true,

            bind: function () {
                 //Error here
                this.update();
            },

            update: function (el, binding) {
                //here, I set the attribute to the element
                el.setAttribute(binding.arg, binding.value);

                //But I don't know how I can detect changes in value (maybe with a whatcher?) and I don't know how I can set value in vm instance for do the two-way data binding
            }
        });`

Thanks you!

**Comment by montyclt** [comment]
And other cuestion: The core directives are made with same syntax of the custom directives?

In this case, where I can see the `v-model` source code? Is only for reference.
