### ISSUE TITLE
when components outside the project , error warn

### ISSUE THREAD

**Issue by KellerLong** [vuejs/vue#5447]
### Version
2.2.6

### Reproduction link
[https://github.com/KellerLong/vue-question.git](https://github.com/KellerLong/vue-question.git)

### Steps to reproduce
1 components outside the project

2 webpack use webpack.HotModuleReplacementPlugin

3 component use props

4 in project use component and bind prop attribute

5 in project update bind's data

### What is expected?
not have error.

### What is actually happening?
when update data, have error

---
Please forgive me for my poor English

**Comment by posva** [comment]
I gave it a look but didn't find anything. This looks more like a question than a bug, so, please ask it on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
If it turns out to be a bug, come back and open an issue, thanks.
