### ISSUE TITLE
父子组件通信，使用v-on绑定自定义事件时，v-on:onemethod="parentMethos"

### ISSUE THREAD

**Issue by Easte-r** [vuejs/vue#5453]
### Version
undefined

### Reproduction link
[http://cn.vuejs.org/v2/guide/components.html#使用-v-on-绑定自定义事件](http://cn.vuejs.org/v2/guide/components.html#使用-v-on-绑定自定义事件)

### Steps to reproduce
v-on:childonemethod="parentMethos"  success
v-on:childOnemethod="parentMethos" fail

自定义事件必须为小写字母，有大写字母会无法通信，如上，childOnemethod，这种写法通信不成功，驼峰表示法应该比较常见，建议支持

### What is expected?
预期能够支持驼峰式的写法
或者在官方文档中声明不支持大写包含大写字母

### What is actually happening?
实际有大写字母就会失败

---
http://cn.vuejs.org/v2/guide/components.html#使用-v-on-绑定自定义事件

bug问题在这个文档中

如果确认解决请告诉我一声呗，rzdong163@163.com  ——来自一个vue的推崇用户

**Comment by yyx990803** [comment]
https://cn.vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case
