### ISSUE TITLE
v-once directive in render function (Failed to resolve directive)

### ISSUE THREAD

**Issue by solovev** [vuejs/vue#5455]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/spritedev/ty2co130/1/](https://jsfiddle.net/spritedev/ty2co130/1/)

### Steps to reproduce

1. Open jsfiddle link
2. Type something in input
3. See warnings in console (Failed to resolve directive: once)

### What is expected?
I wrote two equals components, first component has template field, second - render function. I was expected that _v-once_ will work in render function properly (like in templates)

### What is actually happening?
Got warning message in browser console:
> [Vue warn]: Failed to resolve directive: once

**Comment by yyx990803** [comment]
`v-once`, like `v-if` and `v-for`, are compile-level directives and therefore not available inside render fns.

**Comment by rodrigoho** [comment]
Hi, I came up with the same issue, I was trying to use v-if inside a render, is it still not possible to use it?

**Comment by posva** [comment]
No, you use a ternary instead (like you would in JSX)
I'm locking this since it's a very old issue :)
---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
