### ISSUE TITLE
Mismatched elements causes weirdness with v-if/v-else

### ISSUE THREAD

**Issue by tastycake** [vuejs/vue#5456]
### Version
2.2.6

### Reproduction link
[https://codepen.io/tastycake/pen/jmPyvY](https://codepen.io/tastycake/pen/jmPyvY)

### Steps to reproduce
1. Use a `template` tag with a `div` sibling.
2. Set a `v-if` condition on the template tag.
3. Set a `v-else` condition on the div.
4. Notice that the `v-else` condition doesn't work.
5. Reverse the conditions (i.e. Set a `v-if` on the `div` and a `v-else` on the template tag.
6. Notice that it works as expected in this order.

### What is expected?
The v-else condition should be working on the div tag.

### What is actually happening?
The v-else condition is not being respected. If the conditions are reversed, it seems to work fine.

---
I ran across this bug when I was attempting to set up an empty results view.

**Comment by yyx990803** [comment]
`v-for` has higher priority than `v-if`, so the `v-if` is applied individually to each repeated item rather than the whole list. Wrap the `v-for` with an outer `v-if` for more explicit priorities:

``` html
<template v-if="...">
  <div v-for="..."></div>
</template>
<div v-else="..."></div>
```
