### ISSUE TITLE
Vue Style Guide

### ISSUE THREAD

**Issue by dwiyatci** [vuejs/vue#5457]
### What problem does this feature solve?
Providing an opinionated style guide and/or best practices for syntax, conventions, and structuring Vue applications.

### What does the proposed API look like?
Should be something similar to:
- https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
- https://angular.io/docs/ts/latest/guide/style-guide.html

**Comment by yyx990803** [comment]
Thanks, this should be posted as a feature request to vuejs.org.

**Comment by dwiyatci** [comment]
Cheers, Evan. Posted there just now. 🎉
