### ISSUE TITLE
Better support for libraries component within component model.

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#5459]
### What problem does this feature solve?
In some libraries I've seen this particular pattern
```
<parent>
  <child></child>
  <child></child>
</parent>
```
Where both components are provided by a library similar to `<li>` inside of `<ul>`. However, this presents a number of problems. Here is a non-exhaustive list of things I've noticed.

1. The primary problem is communication between components is impossible with standard techniques. Props and custom events only work with direct parent and child component relationships which these are not. 
2. Inserting new child components into a parent component. The example I was thinking of is if you want to show popup or snackbar alerts for a SPA where in the root component you have a parent component that handles positioning and manages all the messages. Then you have a child component that contains information specific to each message. It would be nice to be able to push a new child component into the parent component from anywhere in the SPA, but I don't see an intuitive way to do this. (Also, one reason you might want to have a full child component instead of just text pushed onto a list is so that you can customize each messages with possibly child components or other DOM markup).
3. Another thing that can happen when using this pattern is when you have a couple different child components that are meant for a single container component. Right now to distinguish between them you also need to set a slot unique to each type of child component so that the parent can distinguish between them which seems redundant. It seems like it would be useful to have something similar to the `$slots`, but for children custom components.

### What does the proposed API look like?
For point 1 perhaps something like provide/inject would help, but it doesn't solve the problems of passing events back up to the parent.
Point 2 I'm not sure the best way to solve this perhaps someone else has an elegant way of solving this problem.
For point 3 I think it could be as simple as adding something like `$childComponents.childComponentName`.

**Comment by yyx990803** [comment]
1. The cleanest pattern for "communicating" between `<parent>` and `<child>` is no communication at all - let both be driven by the state from the common parent. If that is somehow not feasible, then `<parent>` and `<child>` are most likely tightly-coupled by nature, and in that case calling `$parent.$emit()` inside `<child>` is ok.

2. Something like this might help:

  ``` html
  <msg-container>
     <msg v-for="msg in msgs" :msg="msg"/>
  </msg-container>
  ```

3. You can achieve this by using render functions, and filtering/grouping `$slot` nodes programmatically.

**Comment by qw3n** [comment]
@yyx990803 Here is pseudo code of what I was thinking for an alert system, but I don't see any way to do this with the current methods
```
/*index*/
<alert-con></alert-con>

//router links for page1 page2 etc
<router-view></router-view>

/*page1*/
//An asynchronous success message
addAlert(`<alert fade="4e3">Submitted Successfully</alert>`)

/*page2*/
addAlert(`<alert warning="true" onClose="completeDeleteCallbackFn">Deleted! <button @click=undo><icon>Undo</icon></button></alert>`)

/*globally*/
addAlert(`<alert height="double"><avatar id="foo"></avatar> John Doe is online.</alert>`)
addAlert(`<alert autoClose="false">You have {{unreadMessageCount}} new <a href="/messages">message{{unreadMessageCount>1:'s':''}}</a></alert>`)
```
About point 3 I have been using the render function. But the problem is slots returns the results of the `h()` call not a Vue component which isn't documented very well. The developer then has to handle a bunch of edge cases such as empty text nodes, non-empty text nodes, normal HTML and perhaps some other cases I haven't run into yet. It seems like there should be a better way of sorting content hence why I was suggesting something similar to slots but by tag name.
```
this.$slots.default.forEach(v=>{
      //Checks for empty text nodes
      if(v.tag==undefined&&v.text==undefined)return;
      //checks to see if it is normal html or non-empty text nodes
      if(v.componentOptions==undefined){
        defaultCon.push(v);
        return;
      }
      let tag=v.componentOptions.tag
      //Now you can sort by tag
```

**Comment by yyx990803** [comment]
An example of an alert component that can take strings, components and render fns: https://jsfiddle.net/fvv3848b/
