### ISSUE TITLE
'index' not available inside a v-bind:checked statement within a v-for loop

### ISSUE THREAD

**Issue by rolandszpond** [vuejs/vue#5463]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/28103/](https://jsfiddle.net/50wL7mdz/28103/)

### Steps to reproduce
You are able to use 'index' inside any other binding syntax besides v-bind:checked

### What is expected?
In the example, I'm expecting the radio input to be checked that has the index of 2 within the v-for loop statement

### What is actually happening?
It seems like the 'index' is being completely ignored within the v-bind:checked statement only, because you are able to see and use it inside any other v-bind syntax, i.e. v-bind:value, v-bind:name, etc...

---
With Vue 1.*, using v-bind:checked="$index === 2" worked perfectly and would check the corresponding element within that loop

**Comment by yyx990803** [comment]
It is available, it's just your `checked` binding is overwritten by `v-model`. If you are using `v-model`, you should use your initial `data` to control which boxes are checked instead of binding in the template.
