### ISSUE TITLE
name router-view not support children routers

### ISSUE THREAD

**Issue by QiiSyhx** [vuejs/vue#5466]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/gfdegb6o/](https://jsfiddle.net/gfdegb6o/)

### Steps to reproduce
click /home link

### What is expected?
baz
foo
baz

### What is actually happening?
foo
foo
baz

**Comment by yyx990803** [comment]
1. This is a vue-router issue. You posted it to the wrong place.
2. Your usage is wrong: none of your first-level route components contain a `<router-view>`, so the `/home` route will be the same as `/`. Your "expected behavior" doesn't even make sense.
