### ISSUE TITLE
TypeError: Vue is not a constructor

### ISSUE THREAD

**Issue by adyz** [vuejs/vue#5470]
### Version
2.2.6

### Reproduction link
[https://jsbin.com/domunix/edit?html,js,output](https://jsbin.com/domunix/edit?html,js,output)

### Steps to reproduce
I was using Vue 2.1.8 with webpack2 and loading vue in my backbone router with `require.ensure` function provided by webpack for code splitting. 
```
require.ensure([], function(){
            window.Vue = require('vue');
});
```

This allowed be to load Vue library only for the routes I needed, but since I've updated to 2.2.6 I get `TypeError: Vue is not a constructor` in the browser.

### What is expected?
To build as before

### What is actually happening?
TypeError: Vue is not a constructor

---
Using `import Vue from 'vue'` will not help since I want the Vue library to be loaded on demand. Is there any ways to achieve this.

**Comment by posva** [comment]
Please provide a real repro

**Comment by posva** [comment]
You can add a repository, but make sure to boil it down to the strict minimum, please

**Comment by adyz** [comment]
https://github.com/adyz/vuejs-backbone

**Comment by adyz** [comment]
This is the old version that used to work: https://github.com/adyz/vuejs-backbone/tree/oldvue

**Comment by adyz** [comment]
Ow shit, I guess it was all about the alias added on the `oldvue` branch


```
resolve: {
        alias: {
            'vue': 'vue/dist/vue.js'
        }
    }
```
