### ISSUE TITLE
v-model's .trim modifier doesn't work well with <input type="email">

### ISSUE THREAD

**Issue by Naeemo** [vuejs/vue#5471]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/ut6zctpk/1/](https://jsfiddle.net/ut6zctpk/1/)

### Steps to reproduce
Just try add some spaces to both ends.

### What is expected?
Whitespaces at both ends should be trimmed after the input lost focus.

### What is actually happening?
While the data string do got trimmed, the whitespaces remain on the input element. You can select them to see.

**Comment by posva** [comment]
This looks like a regression on Chrome. You can actually reproduce it without Vue: https://jsfiddle.net/k4n77nnf/
You should definitely fill an issue on their tracker, feel free to use the fiddle above 🙂
