### ISSUE TITLE
the incorrect warning when I miss the colon to :class property

### ISSUE THREAD

**Issue by monkindey** [vuejs/vue#5472]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/monkindey/5ssxjkuo/2/](https://jsfiddle.net/monkindey/5ssxjkuo/2/)

### Steps to reproduce
As above code, and open the console to see the warning.

### What is expected?
Give me the `invalid expression: :class="{" ` warning rather than `Property or method "arr" is not defined on the instance`

### What is actually happening?
The warning is `Property or method "arr" is not defined on the instance` which took me a lot time to debug.

**Comment by posva** [comment]
You forgot the `"` around the `class` value so the html gets completely messed up. When getting the html from the browser, it already fixes things up and therefore Vue sees things differently.

**Comment by monkindey** [comment]
Yep, Thanks for your reply. you are right. But as expected, it would be better if Vue give the `invalid expression: :class="{"` warning.
The strange thing is when I change to template like that

```javascript
<ul>
  <li :class={ disabled: disabled } 
  v-for="(arr, i) in array">{{ arr }}</li>
</ul>
```
get rid of the `===` and it will give me the `invalid expression: :class="{" ` warning.

**Comment by sirlancelot** [comment]
It's not possible for Vue to detect this when templates are parsed in the browser. By the time Vue "sees" the template it has already been normalized by the browser.

**Comment by yyx990803** [comment]
This is a wontfix. Vue templates need to be syntax-valid HTML. Always quote your attributes.
