### ISSUE TITLE
props not passed all the way to children of children

### ISSUE THREAD

**Issue by martinchu** [vuejs/vue#5473]
### Version
2.2.6

### Reproduction link
[https://github.com/martinchu/Game-of-Life](https://github.com/martinchu/Game-of-Life)

### Steps to reproduce
1. run the code on localhost
2. click the orange cell

### What is expected?
the cell should turn to grey, like the rest of the grid
(the color depends on the prop(state) and it should be false)

### What is actually happening?
nothing changed. The main.js/original data is changed. The board & row is updated dynamically but the cell level remain unchanged somehow.

**Comment by LinusBorg** [comment]
https://github.com/martinchu/Game-of-Life/blob/master/src/main.js#L54

Vue can't detect this change, see:

https://vuejs.org/v2/guide/list.html#Array-Change-Detection

You have to use `this.$set()`

**Comment by martinchu** [comment]
Thanks a lot!
