### ISSUE TITLE
Safari <img> CSS transition

### ISSUE THREAD

**Issue by sunyang713** [vuejs/vue#5474]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/uys1vofp/2/](https://jsfiddle.net/uys1vofp/2/)

### Steps to reproduce
Given a transition name `fade-overlay`,
in safari, the `<transition>` component doesn't seem to work when `position: absolute;` is added to the `.fade-overlay-enter, .fade-overlay-leave-to` CSS rule.

### What is expected?
Second image should smoothly fade in *on top* of the first image as the first image smoothly fades out.

### What is actually happening?
Images switch with no transition.

**Comment by posva** [comment]
Have you tried using a `transition` instead of `-webkit-transition`

**Comment by yyx990803** [comment]
You need to `key` your images: https://vuejs.org/v2/guide/transitions.html#Transitioning-Between-Elements

**Comment by posva** [comment]
I revisited this and the strange behaviour happens because of safari on `img` elements with the absolute position added at the same time that the transitioning CSS property (`opacity` here). A workaround is applying the `position: absolute` in an other class
Here's the barebones bug https://jsfiddle.net/kvdqgwkv/1/

**Comment by sunyang713** [comment]
@yyx990803 sorry, I actually meant to add the key attribute. even with the key attribute, it doesn't work. please make sure to visit the second revision of the jsfiddle in safari.

**Comment by posva** [comment]
@sunyang713 I think you should open the bug on Safari's or Webkit's bug tracker or web. You can use the fiddle I added

**Comment by sunyang713** [comment]
ah, okay. sorry I missed your earlier comment. I didn't realize this was actually a safari issue, not Vue. Thanks.
