### ISSUE TITLE
Async component loading with server-rendered="true" error

### ISSUE THREAD

**Issue by Haeresis** [vuejs/vue#5478]
### Version
2.2.6

### Reproduction link
[https://ide.c9.io/haeresis/website](https://ide.c9.io/haeresis/website)

#### Problem

Server-side, when I generate my response from server with `vue-server-renderer` mechanism all work and at end, in my client source code I have the `server-renderer="true"`.

Client-side, when I run following code using same files used for server rendering all work too. `require` is used by System.js so this code is really from client side part and `template`, `specific` and `model` are already loaded when `vm` is assigned.

```js
var model = require('views-models/home.js'),
      data = require("variations/home.json!json")
      view = require("views-models/home.htm!text"),
      vm = Vue.component('home', model(data, view));
```

Great. But this is sync. So I want load each component only when my router require it.

So I have changed my previous code into this:

```js
var vm = Vue.component('home', function (resolve) {
	Promise.all([
		System.import('views-models/login.js'),
		System.import('variations/home.json!json'),
		System.import('views-models/home.htm!view')
	]).then(function ([model, data, view]) {
		resolve(model(data, view));
	});
});
```

and I have the error.

#### Reproduce

From https://ide.c9.io/haeresis/website

1. If website not run, start command `haeresis:~/workspace (develop) $ node-atlas --webconfig webconfig.staging.json`

2. See here https://website-haeresis.c9users.io/ without `server-rendered="true"` that's work but there is FOUC

3. Re-introduce error
Return  into online IDE : https://ide.c9.io/haeresis/website
and into file `/assets/javascripts/boot.js` comment line 2 `document.getElementsByClassName('layout')[0].removeAttribute('server-rendered="true");`

4. See error in console from https://website-haeresis.c9users.io/ : [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

### What is expected?
Same render when I use a sync way (no FOUC because of server-rendered="true", Vue not execute animation first loading).

### What is actually happening?
Error message

> [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside &lt;p&lt;, or missing <tbody>. Bailing hydration and performing full client-side render.

and a white part is displayed when component is loaded asynchronously

---
**If now I remove `server-renderer="true"` with `document.getElementsByClassName('layout')[0].removeAttribute('server-rendered');` before using Vue in front side, all work again.**

How I can use SSR (to produce a source with all data already create by server for current page) AND in same time, load content async for others page (to not load all components data from starting but just when the component route is matched)?

And so what is the utility of server-rendered attribute? Avoid [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) ?

Another solution should be to remove server-side the `server-rendered` attribute to also allows my code to pass W3C validation and also fix my problem but I don't know how disable this.

PS : note that usage

```js
var vm = Vue.component('login', function (resolve) {
	var view = require("views-models/home.htm!text"),
	      data = require("variations/home.json!json");
	resolve(require('views-models/home.js')(data, view));
});
```

also work because when resolve is called I think require have already loaded files that is not the case with the Promise async requirement.

For any question about online running of problem, ask me.

**Comment by yyx990803** [comment]
The `server-rendered` attribute is what let's Vue know that it needs to "hydrate" the markup instead of throwing it away and render from scratch. When you remove it, Vue simply does a fresh client-side render which causes the FOUC.

As for the real cause, the short answer is you can't arbitrarily code-split when using SSR.

The reason is that 1. you need to ensure the async components are resolved before starting the render, otherwise the server rendered markup will render empty placeholders for the async components. 2. on the client you also need to resolve async components first before starting hydration, otherwise when hydrating the markup for async components, the definitions are not available yet, so it leads to mismatch.

This is why we currently only support route-based code splitting with `vue-router`, because async route components are auto-resolved before a route view is rendered (with `router.onReady()` for initial render)

There will be a more detailed SSR guide along with the 2.3 release, which should explain everything better.

**Comment by Haeresis** [comment]
Thx for you explainations. I will find another way.

**Comment by guzuomuse** [comment]
@yyx990803 ,

> The server-rendered attribute is what let's Vue know that it needs to "hydrate" the markup instead of throwing it away and render from scratch. When you remove it, Vue simply does a fresh client-side render which causes the FOUC.
> 
> As for the real cause, the short answer is you can't arbitrarily code-split when using SSR.
> 
> The reason is that 1. you need to ensure the async components are resolved before starting the render, otherwise the server rendered markup will render empty placeholders for the async components. 2. on the client you also need to resolve async components first before starting hydration, otherwise when hydrating the markup for async components, the definitions are not available yet, so it leads to mismatch.
> 
> This is why we currently only support route-based code splitting with vue-router, because async route components are auto-resolved before a route view is rendered (with router.onReady() for initial render)
> 
> There will be a more detailed SSR guide along with the 2.3 release, which should explain everything better.

我也想知道这个`data-server-rendered="true"`的作用，以及它存在的意义，有它没它的区别；上边的e文真是看的云里雾里；来一发中文解释可否，谢谢！

**Comment by guzuomuse** [comment]
....又看了一遍ssr的文档，应该是明白，6,7,8,9分了，所以尤大可以选择性的忽略上边问题；:)
