### ISSUE TITLE
Pass the same custom events in diffrent components in <component :is="view"></component>

### ISSUE THREAD

**Issue by tpvt99** [vuejs/vue#5479]
### What problem does this feature solve?
Well, I need to use this with transition but I need to pass differents custom events or props to different components to handle this easy but I need to use component. I find another way that passing different with different name to distinguish but I dont like this way. Is there any way better to solve this?

### What does the proposed API look like?
So if I use a function in just only one component named ComponentA while I dont want to use it in ComponentB but I have to do this:

<component :is="view" @handleFn="handleFn"></component>

That's means in 2 components: ComponentA and ComponentB, both will have the events handleFn.

**Comment by yyx990803** [comment]
Just use if branches if you want different bindings on different components...

**Comment by tpvt99** [comment]
So instead of using "view" controlling in :is="view", now I use "show" in v-if="show" to control which component to render, right ?
