### ISSUE TITLE
Use VueJS with already rendered html

### ISSUE THREAD

**Issue by howardEagle** [vuejs/vue#5483]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/vovchuck_bogdan/50wL7mdz/29017/](https://jsfiddle.net/vovchuck_bogdan/50wL7mdz/29017/)

### Steps to reproduce
I have already rendered html (AdonisJS). Layout example:

<div id="app">
{% block header %}
    {% include "layout/header.njk" %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include "layout/footer.njk" %}
{% endblock %}
</div>
<script src="/assets/dist/build.js"></script>
Main.js:

```
import Vue from 'vue';
import Subscribe from './components/Subscribe.js';
import VueRouter from 'vue-router'

Vue.use(VueRouter);

export const router = new VueRouter({
  mode: 'history',
  routes: [
    {path: '*', component: Subscribe}
  ]
});

new Vue({
  router
}).$mount('#app');
```

And Subscribe.js:

```
import Vue from 'vue';
import axios from 'axios';
import VeeValidate from 'vee-validate';
Vue.use(VeeValidate);

export default {
  el: '#subscribe',
  data () {
    return {
      email: ''
    }
  },
  methods: {
    onSubmit(event) {
      this.$validator.validateAll().then(function (res) {
        if (res) {
          axios.post(event.target.action, {email: this.email})
            .then(function (resp) {
              console.log('resp', resp);
            })
        }
      });
    }
  }
}
```
This code gives me an empty page, with only comment.
If i use Vuejs without webpack module bundler, it works like a charm.

### What is expected?
Rendered page

### What is actually happening?
Empty page

**Comment by posva** [comment]
Please don't disguise a question as a bug report. You can and should ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
btw, you added an `el` property on the subscribe component, but the el tag is meant for mounting Vue instances to the dom not to create elements. I encourage you read the guide: https://vuejs.org/v2/guide/index.html
