### ISSUE TITLE
@drag* events fail to fire for hidden elements, making full-page dropzones unfeasible

### ISSUE THREAD

**Issue by ronjouch** [vuejs/vue#5484]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/ronj/j0qoyqrq/](https://jsfiddle.net/ronj/j0qoyqrq/)

### Steps to reproduce
In the [jsfiddle](https://jsfiddle.net/ronj/j0qoyqrq/),

1. Confirm that dragging a local file over the over the red dropzone produces logging. (This is *not* what I want, it's a baseline case).
     
2. Now, remove `true || ` in the `:style` binding of the `div.dropzone`, re-run the fiddle, and try dragging the same file over the full-page (or jsfiddle output pane) dropzone.

### What is expected?
Expected: logging happens and visibility is toggled.

This "visible only when dragging files over the page" feature is the whole idea of the component: an invisible, whole-screen drop zone, that reveals itself visibly and accepts drop when dragging files over the page, much like the Dropbox website does:

![dropbox-whole-screen-file-upload](https://cloud.githubusercontent.com/assets/522085/25291027/62cf52be-269e-11e7-8a9b-07ea606a2a87.gif)

### What is actually happening?
Actual: no `drag{enter,over,leave,drop}` event is triggered (thus: no console log, no visibility toggling). It looks like Vue `drag*` events bound to an element are *not* triggered when the element `visibility` is `hidden`, unlike with vanilla DOM events (as demonstrated by this [pure-JS implementation fiddle](https://jsfiddle.net/oL2akhtz/)).

---
Note I get the same results when replacing the `:style` binding by a more vue-ish `v-show="hovering"` one.

I'm not sure this is a bug, maybe "not firing events for hidden elements" is intended Vue behavior. But then, is there an escape hatch in Vue letting me build such a whole-page (thus necessarily invisible / hidden) drop zone?

Thanks!

**Comment by yyx990803** [comment]
Notice that in your pure-JS implementation the `dragenter` event is attached to **window** instead of the dropzone element itself. With `visibility: false`, `dragenter` never triggers if attached to the dropzone element, so all your consequent logic fails.

FYI this is more of a usage question.

**Comment by ronjouch** [comment]
Gah, failed to see that, thanks!

And in case that ever helps someone, the answer to subsequent question "then how can I bind an event to `window`?" is to do it using `created` / `destroyed` (which I didn't know yet), as suggested by [StackOverflow / Add Vue.js event on window](http://stackoverflow.com/questions/36993834/add-vue-js-event-on-window).
