### ISSUE TITLE
Fix source maps in error logging for caught exceptions

### ISSUE THREAD

**Issue by chrisnicola** [vuejs/vue#5485]
### What problem does this feature solve?
Sourcemaps are not being shown in the console log messages on Chrome. Instead compiled locations are shown.

### What does the proposed API look like?
In several places exceptions are caught by Vue and then logged using `console.error(err)`. However this will not work with sourcemaps in files for Chrome. Instead the stacktrace has to be logged directly using `console.error(err.stack)`.

**Comment by yyx990803** [comment]
It seems to work the same for me. (with webpack + `devtool: 'cheap-module-source-map'`)

Please provide more info on your source map setup.

**Comment by chrisnicola** [comment]
I'm using the settings generated by vue-cli. Let me see if I can reproduce it more accurately outside of my project. The errors being handled are being thrown by another library (d3) in this case. That may have something to do with it.

**Comment by chrisnicola** [comment]
Ok this is trickier to reproduce than I originally thought. The source locations seem to work if an exception is thrown during most operations. However it doesn't work, or doesn't work reliably if the exception is thrown during D3's operations, such as in the `call` function of a selection. I've attached the error log. What is also interesting is I can occasionally get the sourcemap to work even in this situation but it seems very inconsistent. This may have something to do with the open Webpack bug with respect to sourcemaps in Chrome (https://github.com/webpack/webpack/issues/2145).

Changing the `devtool` to plain `source-map` does seem to fix the problem. The `cheap-module-source-map` also works fine. Either way I suspect this isn't a VueJS problem so I'm going to close this. Sorry about that.

```
Vue warn]: Error in mounted hook: 
(found in <D4Axis> at /Users/chrisnicola/src/d4.vuejs/src/d4-vuejs/Axis.vue)
warn @ vue.esm.js?65d7:558
handleError @ vue.esm.js?65d7:1443
callHook @ vue.esm.js?65d7:2275
insert @ vue.esm.js?65d7:2952
invokeInsertHook @ vue.esm.js?65d7:4958
patch @ vue.esm.js?65d7:5122
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
Vue._init @ vue.esm.js?65d7:3766
Vue$3 @ vue.esm.js?65d7:3847
(anonymous) @ main.js?1c90:15
(anonymous) @ app.js:880
__webpack_require__ @ app.js:660
fn @ app.js:84
(anonymous) @ app.js:1384
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712
vue.esm.js?65d7:1447 TypeError: Cannot read property 'apply' of undefined
    at Selection.selection_call [as call] (eval at <anonymous> (app.js:1156), <anonymous>:1197:11)
    at VueComponent.drawAxis (eval at <anonymous> (app.js:957), <anonymous>:119:34)
    at VueComponent.boundFn [as drawAxis] (eval at <anonymous> (app.js:723), <anonymous>:126:12)
    at VueComponent.draw (eval at <anonymous> (app.js:957), <anonymous>:114:12)
    at VueComponent.boundFn [as draw] (eval at <anonymous> (app.js:723), <anonymous>:126:12)
    at VueComponent.mounted (eval at <anonymous> (app.js:957), <anonymous>:260:10)
    at callHook (eval at <anonymous> (app.js:723), <anonymous>:2274:21)
    at Object.insert (eval at <anonymous> (app.js:723), <anonymous>:2953:7)
    at invokeInsertHook (eval at <anonymous> (app.js:723), <anonymous>:4959:28)
    at Vue$3.patch [as __patch__] (eval at <anonymous> (app.js:723), <anonymous>:5123:5)
handleError @ vue.esm.js?65d7:1447
callHook @ vue.esm.js?65d7:2275
insert @ vue.esm.js?65d7:2952
invokeInsertHook @ vue.esm.js?65d7:4958
patch @ vue.esm.js?65d7:5122
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
Vue._init @ vue.esm.js?65d7:3766
Vue$3 @ vue.esm.js?65d7:3847
(anonymous) @ main.js?1c90:15
(anonymous) @ app.js:880
__webpack_require__ @ app.js:660
fn @ app.js:84
(anonymous) @ app.js:1384
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712
```
