### ISSUE TITLE
Changing data in immediate watcher at first time does not update dom

### ISSUE THREAD

**Issue by rainfore** [vuejs/vue#5489]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/rainforest92/50wL7mdz/29118/](https://jsfiddle.net/rainforest92/50wL7mdz/29118/)

### Steps to reproduce
- Define two properties in data, like 'message' and 'value'
- Use immediate watcher to watch one ('value')
- Change another one ('message') in the watcher callback

### What is expected?
'second' is shown in browser

### What is actually happening?
'first' is shown in browser

**Comment by posva** [comment]
you're just missing the this `this.message`
