### ISSUE TITLE
filter的新需求

### ISSUE THREAD

**Issue by jetiny** [vuejs/vue#549]
你好，有些问题请教一下

Vue.filter('func',function(x, y){
    return x + '.' + y;
})

data:{
    a:'a 1',
    b:'b 2'
}

1 filter只接收一个data中的参数 {{ a| func b }} => a 1.b
2 filter的参数不能加引号 {{ a| func 'b' }} => a 1.'b' 
3 由于func只接收两个参数，所以也不能这样写 {{ a| func b 2 }} 

4 无法修改filter的参数调用顺序，| 前的只能是第一个参数，也就需要再定义个函数进行包装

5 另外想到调用全局的函数而不使用data中的数据该怎么做,比如我有个多语言的模块要翻译
window.tr('a.b')，目前只能 data:{ab:'a.b'} 然后做个filter，这样下来貌似得不偿失啊

**Comment by vaankong** [comment]
借楼问下尤大，vue1在数据不变的前提下，可以单独调用filter吗
