### ISSUE TITLE
无法使用v-bind动态绑定checkbox的true-value和false-value

### ISSUE THREAD

**Issue by zongyz** [vuejs/vue#5490]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/16t51p42/9/](https://jsfiddle.net/16t51p42/9/)

### Steps to reproduce
封装一个通用的checkbox组件，和checkbox一样设置true-value和false-value属性，

在input上直接v-bind:true-value属性是可以的，但由于这两个属性是可选属性，在input直接绑定会导致组件不使用该属性的场景下无法正确的获取value值，使用v-bind="{'true-value':...}"动态绑定亦不能生效，求解~

### What is expected?
v-bind可以绑定true-value和false-value属性，

或[true|false]-value的值为undefined的时候使用value的属性值

### What is actually happening?
v-bind动态绑定checkbox的[true|false]-value不生效，

v-bind:true-value方式绑定值为undefined的时候无法正确获取checkbox的value属性值

**Comment by weiyujia** [comment]
目测楼主要被 posva 喷了，哈，，提issue最好用英文，如果实在不行就中文下面配上英文

**Comment by adamshen** [comment]
请用英文提issue，不然请滚出issue界。

**Comment by yyx990803** [comment]
@adamshen 请注意文明用语。你的回复违反了 [Code of Conduct](https://github.com/vuejs/vue/blob/dev/.github/CODE_OF_CONDUCT.md)。

**Comment by adamshen** [comment]
@yyx990803 OK，已经删除

**Comment by posva** [comment]
@weiyujia I'm a good person, believe me 😇
