### ISSUE TITLE
access vue methods inside export default {}  from outside

### ISSUE THREAD

**Issue by Kuchiriel** [vuejs/vue#5491]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/219zpwuo/](https://jsfiddle.net/219zpwuo/)

### Steps to reproduce
Given the example in jsfiddle I am unable to access vue methods inside export, 'this.default' for example, returns undefined.

### What is expected?
I can access and call getUsers inside export.

### What is actually happening?
I can't access and call getUsers inside export.

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

(not a bug report, for questions, check the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js))
