### ISSUE TITLE
Use multiple conditions in :disabled

### ISSUE THREAD

**Issue by mirmousaviii** [vuejs/vue#5493]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/mirmousavi/mxa6vezg/2/](https://jsfiddle.net/mirmousavi/mxa6vezg/2/)

### Steps to reproduce
Use multiple conditions in ":disabled"
`  <button :disabled="condition1 && condition2">{{ message }}</button>`

### What is expected?
Disabled element

### What is actually happening?
Not disabled element

**Comment by caiquecastro** [comment]
`true && false === false`, `:disabled=false`

**Comment by yyx990803** [comment]
^ this is expected behavior.
