### ISSUE TITLE
"this" in custom directives

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#5494]
I like idea custom directives, because it's best solution for connecting parent <-> indirect child.
BUT i can't find 'this' into directive function((
[http://codepen.io/PatriciusSanctus/pen/KmMpYE](example1: console.info => undefined)
example2:
`<template>
<parent>
  <child>
    <indirect-child v-prop-export="'childedProp'"></indirect-child>
  </child>
</parent>
</template>

<script>
export default {
  data: () => ({
    childedProp: ''
  }),
  directives: {
    'prop-export': (el, binding, vnode) => {
    // ??? this =(, i want get childedProp from indirect-child.$data and set to parent component
    this[binding.value] = vnode.componentInstance.$data[binding.value]
  }
}
</script>
`

**Comment by wostex** [comment]
Look at `vnode.context`

**Comment by patriciussanctus** [comment]
oum i stupid... thanks! %)
