### ISSUE TITLE
RequireJS example

### ISSUE THREAD

**Issue by flo-sch** [vuejs/vue#550]
[Enhancement]

Would it be possible to provide a CommonJS example (with RequireJS for instance) ?
I am just learning how to use Vuejs, and I'm a bit lost with nested components and the events triggering system : my parent element does not catch the events emitted by its components.

Maybe an example would help to understand the good ways and tips to start writing reusable components with CommonJS ?

**Comment by Gamadril** [comment]
going back to the title of the issue.. Can vue.js be used together with require.js?

**Comment by cmal** [comment]
@Gamadril Does this question have an answer? Can vue.js be used together with require.js? Thanks!

**Comment by cmal** [comment]
@posva Hi, I'm currently having a problem using vue.js with requirejs. If I add vue.js as a html tag, requirejs will props an error which described in http://requirejs.org/docs/errors.html#mismatch . I've followed the instructions given there but no result. I use jquery the same way but no problem, but vue cannot. `MISMATCHED ANONYMOUS DEFINE() MODULES ...` Can you give me some opinions about how I can deal with that? Thank you very much!

**Comment by posva** [comment]
@cmal Sorry, last time I used requirejs was 3 years ago. I recommend you to use something else for bundling like webpack. You can start from this: https://github.com/vuejs-templates/webpack
Remember you should post question on the [forums](https://forum.vuejs.org/)
I'm locking this now to keep it quiet 🙂
