### ISSUE TITLE
Binding to non existent object property does not update other bindings

### ISSUE THREAD

**Issue by donnysim** [vuejs/vue#5504]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/70pmxrxw/](https://jsfiddle.net/70pmxrxw/)

### Steps to reproduce
Have an empty object and bind 2 or more inputs to the objects property.

### What is expected?
Both inputs show the same value when one of them is updated.

### What is actually happening?
Both inputs have different values but update the same object property.

**Comment by posva** [comment]
You have to define the full nested object, in your case `nested: { title: '' }` or dynamically set values with `Vue.set`
