### ISSUE TITLE
v-for rendering issue for dynamic components when adding new item at first position

### ISSUE THREAD

**Issue by andreizet** [vuejs/vue#5505]
### Version
2.2.6

### Reproduction link
[https://codepen.io/andreizet/pen/RpvJbQ?editors=1010#0](https://codepen.io/andreizet/pen/RpvJbQ?editors=1010#0)

### Steps to reproduce
Having a list o with dynamic components of the same type, if we look through that list, everything is working as it should. But if you need to add an item at the first position of that list, it will instead be added correctly in that variable, but it will be rendered as the last item, even if it it's the first one.

Just hit the "Add at first position" button from the above example. 

### What is expected?
The newly added value should be rendered at position 0.

### What is actually happening?
The newly added value is rendered at the last position although, in looped array the new item is added at position 0.

---
  Instead of adding the element at the first position, i've tried to add it in the end of the list. In this case everything works just fine. 
  If instead of "data", I sent the component's text through "props", it works, but in some cases this is useless since I need to use "data". An example can be found here:
https://codepen.io/andreizet/pen/rmMzxj?editors=1010#0

  Also, another strange behavior can be found here:
https://codepen.io/andreizet/pen/rmMvRp?editors=1010#0

  If instead of adding the same component at position 0, I add a different one, at first click it is added correctly, but the "data" of the ones after is rebuilt. Also, if you hit "Add at first position" again, "comp-b" will be rendered in the wrong place. 

Am I doing something wrong?

Many Thanks !

**Comment by posva** [comment]
You need to key them, it's on the console 🙂 
`:key="comp.id"` in the `component`

**Comment by posva** [comment]
Oh, the data didn't change, I'll give it a deeper look
