### ISSUE TITLE
_uid missing from types

### ISSUE THREAD

**Issue by lucastheisen** [vuejs/vue#5506]
### Version
2.2.6

### Reproduction link
[https://github.com/lucastheisen/vue-uidfail-repro](https://github.com/lucastheisen/vue-uidfail-repro)

### Steps to reproduce
Create a vue typescript project, create a component that uses `_uid`:
```
<script lang="ts">
import Vue from 'Vue'
import Component from 'vue-class-component'

@Component({
  name: 'app',
})
export default class App extends Vue {
  public componentId = `app-${this._uid}`
  public msg = 'Welcome to Your Vue.js App'
}
</script>
```
Then watch it fail:
```
ERROR in C:\Temp\vcli\uidfail\src\App.vue.ts
(30,36): error TS2339: Property '_uid' does not exist on type 'App'.
```

### What is expected?
No build error

### What is actually happening?
Typescript transpile error due to missing `_uid`

---
The `_` seems to imply that this is an internal implementation detail, but these resources:

* https://forum-archive.vuejs.org/topic/1635/how-to-set-a-unique-id-for-each-component-instance/10
* http://stackoverflow.com/a/34957052/516433
* https://github.com/vuejs/vue/issues/4958

All seem to imply that its use is permitted...  Also, I am unaware of another way around it...

**Comment by ktsn** [comment]
Because _uid is private/undocumented API, it should not be in official typings, IMO. If you really want to use it, you can add it by yourself. 

```ts
import 'vue'

declare module 'vue/types/vue' {
  interface Vue {
    _uid: number
  }
}
```

**Comment by yyx990803** [comment]
You should avoid using private properties since they are not part of the public API and can change without notice.

**Comment by lucastheisen** [comment]
Ok, I figured and agree.  And know this is not a forum for questions...  (a horrible preface to a _question_)...  Is there an _approved_ way to get at the runtime rendered ID of the component?  I need to integrate a vue component with another library, and that library needs the ID so it can progressively enhance...  I'll understand if you ignore the question, just that the general consensus from my (admittedly limited) research was to use `_uid`.

**Comment by yyx990803** [comment]
You can always attach an id yourself in lifecycle hooks.
