### ISSUE TITLE
My component can't be render in v-for

### ISSUE THREAD

**Issue by littlewrite** [vuejs/vue#5507]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/PaulnotPual/vwbya7qp/](https://jsfiddle.net/PaulnotPual/vwbya7qp/)

### Steps to reproduce
1.open the link.
2.the table not completed.

### What is expected?
there should be 5 columns.

### What is actually happening?
but there's 4 in the second row.
the table-name component don't render.

**Comment by xujiongbo** [comment]
See [https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats](https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats)

**Comment by littlewrite** [comment]
oh, Thanks.
