### ISSUE TITLE
Help v-for in IE

### ISSUE THREAD

**Issue by SnailOwO** [vuejs/vue#5512]

**Comment by SnailOwO** [comment]
静态的使用select的情况下，ie中select框没任何问题！但是在使用v-for动态生成option的时候，就存在问题了！下面上图：
![Uploading image.png…]()

**Comment by SnailOwO** [comment]
Anybody can help me ?

**Comment by crossjs** [comment]
这个跟 Vue 没关系，是浏览器对 Select 实现的差异。
