### ISSUE TITLE
Please do not close me ! Help vue 1.0 in IE1

### ISSUE THREAD

**Issue by SnailOwO** [vuejs/vue#5513]
My vue version is 1.0!This is not the key!When i use v-for  of select(option)，in other browser is no problem ! But,in ie ,the border of option is not over the select!
![image](https://cloud.githubusercontent.com/assets/20159622/25375689/1a9c1840-29d4-11e7-83d7-8b9ad05697d6.png)

**Comment by simplesmiler** [comment]
I'm sorry, but the issue tracker is not a support channel. Please ask questions on our [gitter](https://gitter.im/vuejs/vue).
