### ISSUE TITLE
Children-Parent component events crashing after mutating the array

### ISSUE THREAD

**Issue by Diferno** [vuejs/vue#5515]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/diferno/9pwzjfhd/5/](https://jsfiddle.net/diferno/9pwzjfhd/5/)

### Steps to reproduce
Either uncomment one of the commented lines that mutate the array of elements that create the children
// this.rows.splice(i,1)
// this.rows.pop()
// this.rows.splice(0,1)

And press RUN

### What is expected?
Each children, upon creation, has a timeout where it kills itself.
They should all die after the time is set

### What is actually happening?
Some elements are not killed. The parent stops receiving the events after the array has been mutated a couple of times.

---
If we don't mutate the array but simly log the element to be spliced, all the events are received ok.
If we alter the array (pop or splice), the events stop being received

**Comment by posva** [comment]
Use `:key="row"` (look at the console)
