### ISSUE TITLE
Data properties doesn't trigger rerender on change in IE 10

### ISSUE THREAD

**Issue by Et3rn4l** [vuejs/vue#5516]
### Version
2.2.6

### Reproduction link
[https://codepen.io/steinmiller/pen/ZKBQzb](https://codepen.io/steinmiller/pen/ZKBQzb)

### Steps to reproduce
Run in IE 10. I only tried the internet explorer emulator with ie10 agent and winXP ie10 browser.

### What is expected?
The textarea rerenders wiith updated textareaContent value, that was set in mounted.

### What is actually happening?
value is stored correctly as the console logs it, but no rerender happen, although textareaContent is reactive

---
works on all other browsers.

**Comment by dmdewey** [comment]
It does work in IE10 if you change "mounted" to "created". I don't know if that is feasible, but it is a possible workaround. I also noticed that the flicker of red seems less apparent.

**Comment by Et3rn4l** [comment]
Works as a workaround. Thanks a lot!

**Comment by yyx990803** [comment]
Tested with latest version (2.4) in IE10 and it works as expected... closing.
