### ISSUE TITLE
vue.common.min.js file not updated in build

### ISSUE THREAD

**Issue by scriptPilot** [vuejs/vue#5517]
### Version
2.2.6

### Reproduction link
[https://github.com/vuejs/vue/releases/tag/v2.2.6](https://github.com/vuejs/vue/releases/tag/v2.2.6)

### Steps to reproduce
1. Install Vue with "npm install vue" > version will be 2.2.6

### What is expected?
dist/vue.common.min.js has version 2.2.6

### What is actually happening?
dist/vue.common.min.js has version 2.0.3

---
dist/vue.common.js has correctly version 2.2.6

**Comment by yyx990803** [comment]
Thanks, this file is actually deprecated and included in the package by accident. Future releases will not include this file.

**Comment by scriptPilot** [comment]
Thank you @yyx990803, which file should be used instead? It's used in several Webpack starter kits.

**Comment by yyx990803** [comment]
@scriptPilot `.common.js` files are used for bundling, and bundle minification should be done with other parts of the code, .e.g. with `webpack.optimize.UglifyJSPlugin` + `webpack.DefinePlugin` (see [docs](https://vuejs.org/v2/guide/deployment.html#With-Build-Tools))

**Comment by scriptPilot** [comment]
@yyx990803 - Thanks!
