### ISSUE TITLE
Multiple $scopedSlots without declaring them in component

### ISSUE THREAD

**Issue by rigor789** [vuejs/vue#5520]
### What problem does this feature solve?
There are cases where we would like to provide multiple templates as scoped slots, and the component then decides which one to use.

In particular, I'm working on a NativeScript-Vue integration, and ListViews are not using v-for's. For every item, I resolve a slot, that renders the ListView item.

Consider this example: 
```
<list-view :items="items" :templateSelector="templateSelector">
<template scope="item">
    <stack-layout orientation="horizontal" style="padding: 20">
        <label>{{ item.value }}</label>
    </stack-layout>
</template>
<template name="alt" scope="item">
    <stack-layout orientation="horizontal" style="padding: 20; background-color: #333">
        <label>{{ item.value }}</label>
    </stack-layout>
</template>
</list-view>
```

The list-view component, calls the `templateSelector()` function which returns the template name, in this case either `default` or `alt`. Accessing the default scoped slot works with `this.$scopedSlots.default`, but there is no way of accessing the `alt` template.

### What does the proposed API look like?
The proposed API is the same as it currently is, except with the ability to select between templates.

**Comment by posva** [comment]
You should be able to achieve this by using a dynamic name in the slot definition in the component template, or if you prefer, using a render function: https://vuejs.org/v2/guide/render-function.html#Slots

**Comment by rigor789** [comment]
My use case differs, since I'm not actually rendering the slot inside the component. 

Here is the code that patches the slot template to actual elements: https://github.com/rigor789/nativescript-vue/blob/master/nativescript-vue/platform/nativescript/runtime/components/list-view.js#L90-L99

So slots are not rendered by the component.

What I'm trying to do right now, is write a custom compiler module, that will set the scopedSlots, which would be ideal, since I think this is a rare use-case.

If I can't figure it out, I'll ask on forums. Thanks!
