### ISSUE TITLE
关于data属性动态添加根属性的问题

### ISSUE THREAD

**Issue by bfrgithub** [vuejs/vue#5521]
### What problem does this feature solve?
 您好，我在使用vue的时候，在created方法里面通过ajax请求数据，并且将请求的数据以data的根属性的形式添加到data上面，然后在模板里面使用当前添加的属性进行判断，结果发现有时候可以获取到值，有时候不可以获取到，不知道是不是我使用的问题：例子
 
 

### What does the proposed API look like?
  data{}，
   created:function() {
   this.test= {
        flag: 1
   };
     ajax.get(url, function(res){
          this.test = res.data;
     }.bind(this));
 }
// 在模板中输出test里面的flag值
{{test.flag}} // 会发现有时候flag的值发生了变化，有时候还是1

**Comment by yyx990803** [comment]
请不要把问题伪装成 feature request.
