### ISSUE TITLE
vue2.0 keep-alive，如果不同路由使用的是同一组件，怎么分别缓存，希望用keep-alive解决

### ISSUE THREAD

**Issue by GuanJingkai** [vuejs/vue#5523]
### What problem does this feature solve?
路由代码如下

const routes = [{
path:'Form/:id',
component:Form
}]

我访问 Form/1 和 Form/2 希望打开两个页面分别保存状态（填写的未提交的数据，选项卡的选项，滚动的位置）,keep-alive可以解决这个需求，但是同一个组件不同路由只缓存一次，怎么对同一组件不同路由分别缓存呢？

### What does the proposed API look like?
keep-alive支持同组件多路由独立缓存

**Comment by yyx990803** [comment]
请不要用 feature request 问问题。

**Comment by GuanJingkai** [comment]
您好第一次用，虽然我问错了方式，但是能解决我的问题么，我这也算是功能要求，keep-alive 可以根据路由的不同 对同一组件分别缓存

**Comment by GuanJingkai** [comment]
那怎么问问题啊，只有这一个选项，另一个是提交bug

**Comment by ytbryan** [comment]
问问题，用 https://forum.vuejs.org/ 或 stackoverflow.com
