### ISSUE TITLE
Vue removes html tags in script tags wrapped by v-pre

### ISSUE THREAD

**Issue by marcelgwerder** [vuejs/vue#5526]
### Version
2.2.6

### Reproduction link
[https://jsbin.com/holacowepe/1/edit?html,js,console](https://jsbin.com/holacowepe/1/edit?html,js,console)

### Steps to reproduce
- Add script template including html tags
- Wrap script tag with Vue

### What is expected?
Script content isn't touched at all.

### What is actually happening?
All html tags are removed.

---
I am migrating a website to Vue and do have some plain js code that reads out templates in a script tag on click. When the html is within a Vue template it removes all html tags in the script tag. I can't rewrite the whole site so I wanted to leave this part as it is. The same happens if I use v-pre which to my understanding should prevent Vue from doing anything to this part of the DOM.

I guess there are good reasons for the behavior but I haven't quite figured them out yet...

**Comment by pbastowski** [comment]
@marcelgwerder 
Here are a couple of examples of how to use inline HTML templates.
https://jsbin.com/qebuzav/1/edit?html,js,output
Does this help you? Is this what you are trying to achieve?
