### ISSUE TITLE
When I ran npm test for first time and after they passed I got Starting selenium server... There was an error while starting the Selenium server

### ISSUE THREAD

**Issue by interglobalmedia** [vuejs/vue#5528]
### Version
2.2.6

### Reproduction link
[https://jsbin.com/kihexanuda/edit?html,js,output](https://jsbin.com/kihexanuda/edit?html,js,output)

### Steps to reproduce
npm test or npm run test

### What is expected?
I expected that the dev server would start up but it failed to do so even though the tests seemed to pass. I was only using the code to test that was initially provided. I literally just installed Vue for the first time with npm.

### What is actually happening?
The dev server failed to execute.

**Comment by yyx990803** [comment]
npm test obviously just runs the test... You should be using npm run dev if you want to start the dev server.

**Comment by interglobalmedia** [comment]
@yyx990803 Then why is it trying to start up? That seems to be a bug in itself. If it is meant for testing only, then the script should not be trying to start up the Selenium Server?

**Comment by yyx990803** [comment]
Because the e2e tests requires starting the dev server. It shuts it down after the tests are complete.

**Comment by suifeng123** [comment]
The answer is very good
