### ISSUE TITLE
.number modifier converts string to number

### ISSUE THREAD

**Issue by weizhenye** [vuejs/vue#5531]
### Version
2.2.6

### Reproduction link
[https://codepen.io/anon/pen/EmZmrO](https://codepen.io/anon/pen/EmZmrO)

### Steps to reproduce
input `3d`

### What is expected?
should display `3d`

### What is actually happening?
it displays `3`

---
```js
export function toNumber (val: string): number | string {
  const n = parseFloat(val)
  return isNaN(n) ? val : n
}
```
I find in source code, .number modifier is using `parseFloat` to parse string, which will convert strings start with number to number.

That cause number validator like [element-ui](http://element.eleme.io/#/en-US/component/form#number-validate) not work.

**Comment by yyx990803** [comment]
This is expected behavior. It's a bad idea to use `.number` and then expect the value to be a string.
