### ISSUE TITLE
[2.3.0] Uncaught TypeError: Cannot set property 'isRootInsert' of null

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#5536]
### Version
2.3.0

### Reproduction link
2.3.0 - [https://jsfiddle.net/f0n7jmL7/](https://jsfiddle.net/f0n7jmL7/)
2.2.6 - [https://jsfiddle.net/eu1q0a8b/](https://jsfiddle.net/eu1q0a8b/)

### Steps to reproduce
1. Open bug reproduction for 2.3.0 and check console.log - you ca see an error
2. Make change in FormErrors component so it will return empty `span` tag  instead of `null` value at the end - no error this time and the example works fine

### What is expected?
i expect the above example to work as it did in vue@2.2.6

### What is actually happening?
Vue throws an error `Uncaught TypeError: Cannot set property 'isRootInsert' of null` when functional component returns null value instead of vnode.

// EDIT: Also something I noticed in 2.3.0. If you will return `undefined` instead of `null` at the end of FormErrors, then our example works again.

**Comment by gebilaoxiong** [comment]
HI,  I think this problem is caused when creating vnode

https://github.com/vuejs/vue/blob/dev/src/core/vdom/create-element.js#L102

in 2.2.6:
``` javascript
  if (vnode) {
    if (ns) { applyNS(vnode, ns); }
    return vnode
  } else {
    return createEmptyVNode()
  }
```
