### ISSUE TITLE
[vue convention] The coding style of vue component (template/style/script code block order)

### ISSUE THREAD

**Issue by MikeCheng1208** [vuejs/vue#5537]
作者你好！
我们团队在共同开发vue专案上面有个小问题请教
我个人在写vue样板的习惯是先script -> template -> style，我觉得这样比较顺手
理由是 因为在调整html要去不同的区块修改样式时比较方便，比较邻近，还以专案在import哪些东西时比较清楚
但是团队有人提出 在官网图片样板顺序是 template -> script -> style，觉得应该直接遵循官方文件这样撰写
想请教作者看法～谢谢

**Comment by yyx990803** [comment]
这方面没有要求，挑自己或者团队喜欢的写法就行。

**Comment by MikeCheng1208** [comment]
thx~
