### ISSUE TITLE
optional prop with type of Boolean should be undefined if it is not passed in

### ISSUE THREAD

**Issue by petridw** [vuejs/vue#5541]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/30314/](https://jsfiddle.net/50wL7mdz/30314/)

### Steps to reproduce
Make a component with an optional prop and give it a type of Boolean. Use this component in a template and don't pass in the prop. If you inspect the component instance the prop will be there with a value of `false`.

### What is expected?
Other optional prop types are undefined when not provided. I would expect props with type Boolean to act the same way.

### What is actually happening?
The optional prop is being added to the component instance with a value of `false` when it should not be added to the component instance at all if it is not passed in.

---
This comes into play often when building reusable components with optional props. Often a reusable component will need to keep track of its own state in `data`, but allow optional prop types that can override the local value if they are provided. The way the component would check to see if the prop was passed in or not would be to see if the prop is `undefined`. When the prop defaults to `false` it is difficult to tell if it was passed in from the outside or not.

**Comment by posva** [comment]
Unfortunately, this is intended, it has been discussed many times in other issues. In short it's more common to have this behaviour.

**Comment by petridw** [comment]
Hmm, thanks for your response. Is there a workaround for determining if a Boolean type prop was passed in from the parent or not? The only option I can think of is to remove the `type` validation altogether, which seems like a step backwards.

**Comment by gregveres** [comment]
If anybody stumbles upon this issue looking for how to create an optional boolean prop, as I did, here is what I ended up doing:

```JS
props: {
  enableTooltip: {
    type: Object as () => boolean | undefined,
    default: undefined
  }
}
```

This seems to work fine. 

I still don't understand the original logic of making a not-specified prop false, when it could be handled properly in all cases with the default. If the developer wanted not specified to mean false, then use default: false. If the developer wanted not specified to be undefined, then use default: undefined. You could have a short cut of no default specified to fall to false.
