### ISSUE TITLE
When the sap page is too large, browser crash！

### ISSUE THREAD

**Issue by luandapipi** [vuejs/vue#5543]
When the sap page is too large, switching the page in the ios8 system will make the browser crash.
When i enter the site and then switch to a relatively large asynchronous load page. Then the browser crashes when you click back on the previous page.
Temporarily unable to locate the code to cause the problem, guess is used to keep-alive memory is too large problem. I would like to ask how to solve this case.
URL：http://mall.sentree.com.cn/wxmall/?#/shop

**Comment by foi** [comment]
no crash on firefox 53 windows 8.1
