### ISSUE TITLE
Input with 'v-model' in 'Wechat(微信)' WKWebView browser BACKSPACE problem

### ISSUE THREAD

**Issue by keepgoingwm** [vuejs/vue#5544]
### Version
2.3.0

### Reproduction link
[https://github.com/keepgoingwm/code-share/blob/master/vue-input-issue.html](https://github.com/keepgoingwm/code-share/blob/master/vue-input-issue.html)

### Steps to reproduce
+ open 'https://vuejs.org/v2/guide/#Handling-User-Input' in 'Wechat(微信)' WKWebView browser

+ delete the words 'Hello Vue!' one by one in the Input element with BACKSPACE

### What is expected?
BACKSPACE work well, cursor go right place

### What is actually happening?
Cursor go wrong place when delete last(means 'H' here) word sometimes. Screenshot:
http://i1.piimg.com/567571/dae7956005eabe04.png

---
+ only last word and only occurs sometimes

+ we also try safari on iphone with 'reproduction link' page, it can reproduce

+ one weird point:
we cannot reproduce it in 'https://jsfiddle.net/wangnew2013/50wL7mdz/30393/'

**Comment by posva** [comment]
That looks like a display issue so it's probably on WeChat's end 🙂 
Unfortunately, I don't know how you communicate this kind of issues to that project so I cannot help you with that

**Comment by xjchengo** [comment]
@posva It can reproduce on Safari iOS 10.3.1.
![wechat image_20170502101641](https://cloud.githubusercontent.com/assets/4819996/25601756/e1efe11e-2f20-11e7-9e20-4456666f60e4.png)
![wechat image_20170502101655](https://cloud.githubusercontent.com/assets/4819996/25601757/e1f38602-2f20-11e7-8b01-57141c428c47.jpg)

**Comment by xjchengo** [comment]
It behaves like this issue https://github.com/18F/web-design-standards/issues/277.

**Comment by posva** [comment]
Yeah, it's a bug on Safari. If you manage to fix that on the docs, we can take a look at a PR but I don't think it's worth your time because the bug will probably disappear in future releases of Safari. To make it clear, it's completely unrelated to Vue, though
