### ISSUE TITLE
Filters not working with 'v-for'

### ISSUE THREAD

**Issue by sumitridhal** [vuejs/vue#5545]
Vue.js version
2.1.10

Reproduction Link
http://codepen.io/sumitridhal/pen/ybVGZa?editors=1010

What is Expected?
filterBy OR limit filters not working with v-for

```v-for='(item, index) in filteredItems | filterBy search'```
``<input type="text" class="form-control medium" v-model="search">'``

What is actually happening?
application not loading...

**Comment by smolinari** [comment]
Filters can only be inside interpolations i.e. mustache brackets `{{ myVar | myFilter}} ` or in `v-bind` expressions `<div v-bind:id="someId | someIdFilter"></div>`

https://vuejs.org/v2/guide/syntax.html#Filters

Scott

**Comment by wostex** [comment]
For your case you should use computed property = filtered array
