### ISSUE TITLE
When displaying another container, data of a reused component remain

### ISSUE THREAD

**Issue by laobubu** [vuejs/vue#5547]
### Version
2.3.0

### Reproduction link
[http://laobubu.net/vue-bug-test-1/](http://laobubu.net/vue-bug-test-1/)

### Steps to reproduce
Create some tab pages, both of them contain one ComponentX.

```html
<div v-if="tab==0"><ComponentX/></div>
<div v-if="tab==1"><ComponentX/></div>
```

Use `v-if` to control tab pages' visibility.
When jumping to another tab page, the ComponentX data doesn't change.

To reproduce this bug, open <http://laobubu.net/vue-bug-test-1/> and follow the instruction.

### What is expected?
Components in different containers shall own different data.

### What is actually happening?
If one component is reused, the data of last component is still there.

**Comment by posva** [comment]
That's intended, you need to use [key](https://vuejs.org/v2/api/#key)
