### ISSUE TITLE
Can vue component bind to existing DOM elements?

### ISSUE THREAD

**Issue by dmfilipenko** [vuejs/vue#555]
Can we create Vue component, without defining it in template, and bind this component to existing DOM element?

``` javascript
Vue.component('component1', {
    el: '.component1',
    data: function() {
        return {
            name: 'some name'
        }
    }
})
new Vue({
    el: 'body'
})
```

``` html
<body>
    <div class="component1">{{name}}</div>
</body>
```

expect:

``` html
<body>
    <div class="component1">some name</div>
</body>
```

Any idea?

**Comment by Jorybraun** [comment]
@yyx990803 , sorry how would you do this with single file components?

**Comment by gzwsj95** [comment]
> @yyx990803 , sorry how would you do this with single file components?

maybe you can use 'import' ?
