### ISSUE TITLE
vue2.3 确信sync已经可用了么？

### ISSUE THREAD

**Issue by muei** [vuejs/vue#5554]
```json
{
    "vue": "^2.3.0",
    "url-loader": "^0.5.8",
    "vue-loader": "^12.0.2",
    "vue-style-loader": "^2.0.5",
    "vue-template-compiler": "^2.3.0",
}
```
`Hello.vue`:  
```html
<child v-bind:test.sync="test"></child>
```
`Child.vue`:  
```html
<template>
<div>
  <input type="text" v-model="test">
</div>
</template>
<script>
export default {
  props: {
    test: {
      type: String
    }
  }
}
</script>

```
type the words in input component, the error also exit:  
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "test"
```

**Comment by loveyunk** [comment]
`<div id="app">
    <my-component :foo.sync="bar"></my-component>
</div>`

`    Vue.component('my-component', {
        template: '<div @click="change">{{foo}}</div>',
        props: {
            foo: {
                type: String
            }
        },
        methods: {
            change () {
                this.$emit('update:foo', 'zzz');
            }
        }
    });

    new Vue({
        el: '#app',
        data: {
            bar: 'bar'
        }
    });`

**Comment by loveyunk** [comment]
`    Vue.component('my-component', {
        template: '<div @click="change">{{foo}}</div>',
        props: {
            foo: {
                type: String
            }
        },
        methods: {
            change () {
                this.$emit('update:foo', 'zzz');
            }
        }
    });

    new Vue({
        el: '#app',
        data: {
            bar: 'bar'
        }
    });
`
