### ISSUE TITLE
How to correctly use sync in the version 2.3 of vue ？

### ISSUE THREAD

**Issue by muei** [vuejs/vue#5556]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/30520/](https://jsfiddle.net/50wL7mdz/30520/)

### Steps to reproduce
1. 输入文字
2. 并未同步且报错

### What is expected?
同步子组件的输入

### What is actually happening?
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "test"

found in

---> <Child>
       <Root>

**Comment by LinusBorg** [comment]
https://jsfiddle.net/50wL7mdz/30533/
