### ISSUE TITLE
Changes made Array properties using Array.prototype.push.apply are not detected

### ISSUE THREAD

**Issue by joshgalicic** [vuejs/vue#5557]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/Lechvdd8/](https://jsfiddle.net/Lechvdd8/)

### Steps to reproduce
Create a Vue instance with an Array data property.
Add values to that array using Array.prototype.push.apply(ARRAY_PROPERTY, [ NEW_VALUES,... ]);

See that the array has changed to include these new values, but Vue has not detected the added values.

If instead you use the push method from the property itself (ex. ARRAY_PROPERTY.push.apply(ARRAY_PROPERTY, [ NEW_VALUES,... ]); ) it will work as expected and the change is detected.

### What is expected?
The Vue instance will detect the newly added value to the array

### What is actually happening?
The Vue instance is not detecting the change, even though the array contains the new values.

**Comment by wostex** [comment]
AFAIK: `array_property prototype = Array.prototype + wrapped reactive array-related methods`. This is described here:  `vue/src/core/observer/array.js`. Reactive methods do the same thing as native, and emit events to notify observer the data has changed.

**Comment by yyx990803** [comment]
This is expected behavior. Vue doesn't modify `Array.prototype` - it only modifies the mutating methods on observed arrays.
