### ISSUE TITLE
Combining contexts.

### ISSUE THREAD

**Issue by juliandavidmr** [vuejs/vue#5558]
### What problem does this feature solve?
Hello, is there any way to transfer the context of vuejs to an expressjs function (path)?

### What does the proposed API look like?
Hello, is there any way to transfer the context of vuejs to an expressjs function (path)?

**Comment by smolinari** [comment]
It's better to use the forum for such questions. The repo issues are only for bugs and suggestions.

https://forum.vuejs.org/

Scott
