### ISSUE TITLE
could not run well with async/await(regeneratorRuntime actually)

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#5559]
### Version
2.3.0

### Reproduction link
[https://github.com/JounQin/vue-hackernews-2.0/blob/async-await/src/store/actions.js](https://github.com/JounQin/vue-hackernews-2.0/blob/async-await/src/store/actions.js)

### Steps to reproduce
remove L1 and L9

### What is expected?
I've add 'regenerator-runtime/runtime' in client and server entry, which should register `global.regeneratorRuntime` already.

### What is actually happening?
throw Error `ReferenceError: regeneratorRuntime is not defined` every time

---
It worked before `vue-server-renderer` 2.3.0

**Comment by LinusBorg** [comment]
ßCan you explain what is happening, what the error is that you got?

**Comment by posva** [comment]
Sorry, but this is related to babel config not to Vue
Using the `transform-runtime` works (like in the [webpack template](https://github.com/vuejs-templates/webpack/blob/master/template/.babelrc))

**Comment by JounQin** [comment]
@posva Before migrating to new SSR solution, it worked just fine by using `regenerator-runtime/runtime`, so I think that it *does* be related to Vue.

What means the now SSR solution breaks `global` context of Node.js IMO.

**Comment by yyx990803** [comment]
@JounQin this is a change caused by `runInNewContext: false`. I see that you've figured out you need to register it explicitly on the bundle's `global` context - this will be fixed in the next release.

**Comment by yyx990803** [comment]
@JounQin after thinking about it, I think the 2.3.0 behavior should be preserved. The bundle *should* have a separate `global` context to prevent it from affecting the server process. For polyfills that modify `global`, the proper solution is either explicitly attach it to `global` inside bundle code (like you did), or whitelist it from server `externals`.

**Comment by JounQin** [comment]
@yyx990803 Thanks for your explanation and whitelisting `regenerator-runtime/runtime` from server `externals` works fine for me.

**Comment by jonaskuiler** [comment]
@JounQin Do you have a code example? I don't really understand what I have to do to make this work correctly. Are you using `webpack-node-externals`?

**Comment by JounQin** [comment]
@jonaskuiler After Vue 2.3.2, there is no need to do that if you are still using `runInNewContext: false`。

Of course, if you running with Vue 2.3.0 or `runInNewContext: 'once'`, you can do like this: https://github.com/JounQin/vue-ssr/blob/636bd0625bbe6a5efaa6f84409035eb86e97bfe4/build/webpack/server.babel.js#L58 。
