### ISSUE TITLE
Seperate css style in diferrent components

### ISSUE THREAD

**Issue by tpvt99** [vuejs/vue#5560]
### What problem does this feature solve?
I have a problem. Here I use router to route my app. I have LoginPage.vue for user to login and HomePage.vue for user who has login into website. I have Home.vue contains <router-view></router-view> to be the main root router components for the 2 above components.

Inside LoginPage.vue: <style lang="scss"> @import  '../../static/loginpage.scss' </style>
Inside HomePage.vue <style lang="scss"> @import  '../../static/homepage.scss' </style>

The problem here is in HomePage.vue or LoginPage.vue include both style in both 2 scss files. For example, in LoginPage.vue I have \<input type="text" /> has "color:red;" defined in loginpage.scss but in Homepage.vue \<input type="text" /> still has color is red whenever I did not style the input in homepage.scss. How can I solve this problem. I use vue-loader with webpack template.

### What does the proposed API look like?
I dont know the answer yet.

**Comment by yyx990803** [comment]
Use scoped styles.

**Comment by tpvt99** [comment]
thank you. But is there anyway to solve this? I just dont want attribute data-v appear all my html code like this way.

**Comment by yyx990803** [comment]
Then scope the CSS yourself with proper nested selectors.

**Comment by tpvt99** [comment]
ok. with the scoped i found a really annoying thing like this.
Suppose I have a LoginPage.vue. Inside LoginPage.vue I have LoginForm.vue and LoginHeader.vue. I want to style both 3 components using just only 1 scss file named login.scss. I also need to use scoped to prevent the problem I addressed. The problem is if I put the scss file in LoginPage.vue then the style dose not apply to LoginForm and LoginHeader. So I have to seperate 1 file into 3 files to apply approriate css file into each of them. Is there anyway to solve this? Thank you

**Comment by yyx990803** [comment]
Sorry, issues are not for questions or support, please use the appropriate channels - [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
