### ISSUE TITLE
Passing ref to component

### ISSUE THREAD

**Issue by nainemom** [vuejs/vue#5561]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/nainemom/y7vxa3fL/](https://jsfiddle.net/nainemom/y7vxa3fL/)

### Steps to reproduce
I want to pass reference of one component (c1) to another component (c2) and playing with methods of c1, inside c2 component. both components are siblings together.

### What is expected?
I expect c2.handler equals to c1.

### What is actually happening?
Nothing happened. just got undefined.

---
I think it is a bug, but for more information, if some changes applied to parent component, this would work. visit the [second link](https://jsfiddle.net/nainemom/y7vxa3fL/1) and click the button, before and after changing input.

**Comment by posva** [comment]
This is expected because `$refs` are not reactive. That's why it works when modifying the input: because the dom gets computed again and the ref exists.

When I need to communicate between two sibling components I usually have a common parent (these siblings are usually related to the ui) so it really makes sense. What is your use case?

**Comment by nainemom** [comment]
I writing a datepicker component. The most concept used for datepicker ui is:
```
<datepicker>
    <input @click="modal.open()" :value="value">
    <modal @change="input.update()"><!-- here, user select the date --></modal>
</datepicker>
```

But i want to write something else. Datepicker component just should render the modal function and selecting **value**, and another component named input just for handeling the opening and closing modal and keep the final value. So, my idea is:

```
<input @click="modal.open()"  :value="value">
<datepicker>
    <modal @change="input.update()"><!-- here, user select the date --></modal>
</datepicker>
```

All things works, but end-user does not like to write this stuff. In the input component, i want to just get the datepicker reference and handel the opening and closing and getting the value, by js, automaticly.

**Comment by yyx990803** [comment]
`$refs` are simply not designed to be used inside templates like this. Always prefer working with state/data than component instance references.
