### ISSUE TITLE
How to define empty multidimensional array

### ISSUE THREAD

**Issue by mohammad6006** [vuejs/vue#5562]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/30596/](https://jsfiddle.net/50wL7mdz/30596/)

### Steps to reproduce
I need to use multidimensional array model in my vuejs project

I define an array in my vuejs data

but I have error when I call not defined index

I use v-if to skip undefined index but it doesn't work 

### What is expected?
How can I skip not defined index?

### What is actually happening?
[Vue warn]: Error in render function: "TypeError: Cannot read property '1' of undefined"

**Comment by yyx990803** [comment]
This is a question, not a bug.

**Comment by mohammad6006** [comment]
@yyx990803 
But I couldnt find answer

could you help me please?
