### ISSUE TITLE
Passing BackgroundPosition as prop it doesn't take exactly the right position 

### ISSUE THREAD

**Issue by MatteoGiacomo** [vuejs/vue#5566]
### Version
2.3.0

### Steps to reproduce
if I pass this as prop 

```
dataBox : {
    bgPosition: {
       backgroundPosition: ('0px', '0px')
    }
}
```
and I use it in my component
```
<div :style="data.bgPosition" class="box"></div>

box {
    width: 100px;
        height: 100px;
        position: absolute;
        background-image: url('IMAGE');
        background-repeat: no-repeat;
}

```
the background position is going to set as -> 0px center  

### What is expected?
background-position: 0px 0px

### What is actually happening?
background-position: 0px center

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
