### ISSUE TITLE
Error passing function to mixins - 2.3.0

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#5567]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/fnda5s7L/1/](https://jsfiddle.net/fnda5s7L/1/)

### Steps to reproduce
https://jsfiddle.net/qd56hgqy/ - vue 2.2.6 - working
https://jsfiddle.net/fnda5s7L/1/ - vue 2.3.0 - error

When a mixin is a function (so that it can be passed directly to mixins or new'd with options) an error is thrown with Vue 2.3.0

Uncaught TypeError: Cannot read property 'props' of undefined at normalizeProps

Mixin type is checked here, if it's a function, it looks for an `options` property which might not exist
https://github.com/vuejs/vue/blob/086ae4469b0200e94b1ad0f70771e57c63ce18af/src/core/util/options.js#L278

### What is expected?
Mixin should be merged

### What is actually happening?
Errors

**Comment by posva** [comment]
Where did you get the idea of using functions for mixins? Mixins must be plain objects: https://vuejs.org/v2/guide/mixins.html
