### ISSUE TITLE
backgroundPosition

### ISSUE THREAD

**Issue by MatteoGiacomo** [vuejs/vue#5568]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/jxe6uuL6/1/](https://jsfiddle.net/jxe6uuL6/1/)

### Steps to reproduce
pass an object as prop to a component with style attribute as backgroundPosition 

```
dataBox: {
    backgroundPosition: ('0px', '0px')
}
```

and push the object straight to inline style in the component

`<div :style="{dataBox}"></div>`

### What is expected?
background-position: 0px 0px

### What is actually happening?
background-position: 0px center

**Comment by yyx990803** [comment]
`('0px', '0px')` evaluates to just `'0px'`.

**Comment by MatteoGiacomo** [comment]
if I have a sprite it consider the second parameter always 'center' also if it is set to 100px

**Comment by yyx990803** [comment]
What I mean is use `"0px 0px"` instead of `("0px", "0px")`.

**Comment by MatteoGiacomo** [comment]
It gives me 'Error compiling tamplate'.

**Comment by MatteoGiacomo** [comment]
Thanks, it works !
