### ISSUE TITLE
v2 Filter Documentation Wrong

### ISSUE THREAD

**Issue by nickaversano** [vuejs/vue#5569]
### Version
2.3.0

### Reproduction link
[https://vuejs.org/v2/api/#Vue-filter](https://vuejs.org/v2/api/#Vue-filter)

### Steps to reproduce
Navigate to vue api docs. Note that it mentions filters, but to my understanding these have been removed in the v2 api

### What is expected?
Expected not to see filter docs, or a note about removal in v1

### What is actually happening?
Still see v2 filter. Clicking the link to the source returns a broken link

**Comment by yyx990803** [comment]
It still in v2. Please read the template syntax section.

**Comment by rpkilby** [comment]
Worth noting - the `source` link for filters is outdated and returns no search results on GitHub. 

https://github.com/search?utf8=%E2%9C%93&q=repo%3Avuejs%2Fvue+extension%3Ajs+%22Vue.filter%22&type=Code

**Comment by smolinari** [comment]
@rpkilby - If you would be so kind, please start a new issue [in the vuejs.org website repo](https://github.com/vuejs/vuejs.org) for that problem.

Scott
