### ISSUE TITLE
Make creating functional components easier

### ISSUE THREAD

**Issue by padcom** [vuejs/vue#5572]
### What problem does this feature solve?
Currently when declaring functional components all you have to do is specify the `functional: true` field and supply a render method. It would be a lot clearer if instead of this the framework could figure it out by itself when it sees a function instead of an object.

### What does the proposed API look like?
Registering a function as functional component:
```
Vue.component('hello-world', function (h, context) {
  return h('h1', 'Hello, world!')
})
```
Registering components in for example .vue files:
```
export default {
  components: {
    hello (h, context) {
      return h('h1', 'Hello, world!')
    }
  }
}
```

**Comment by padcom** [comment]
Proposed implementation for the first part of it: https://github.com/padcom/vue/tree/GH-5572

**Comment by padcom** [comment]
I just realized that the construct where a function is passed as a parameter to the configuration object is actually reserved to async components. It's a pity but I can live with that.

**Comment by padcom** [comment]
I just realized that the construct where a function is passed as a parameter to the configuration object is actually reserved to async components. It's a pity but I can live with that. Thanks for the unit test!

**Comment by yyx990803** [comment]
FYI you might be interested in @nickmessing 's idea here (sugar via babel plugin): https://github.com/vuejs/babel-plugin-transform-vue-jsx/pull/77
