### ISSUE TITLE
[ssr] _uid is shared between requests

### ISSUE THREAD

**Issue by pi0** [vuejs/vue#5573]
### Version
2.3.1

### Reproduction link
[https://github.com/pi0/nuxt-test/blob/ssr_uid/pages/index.vue#L8](https://github.com/pi0/nuxt-test/blob/ssr_uid/pages/index.vue#L8)

### Steps to reproduce
This tests are based on [this](https://github.com/pi0/nuxt.js/tree/2.3.0) branch of nuxt.js which brings 2.3.x `runInNewContext` compatibility to nuxt.js. But can be reproduced with any other setup with `runInNewContext ` set to false.

### What is expected?
`_uid` should be incremented on context and reset after every request

### What is actually happening?
It is being shared across requests and each request affects next one.

**Comment by yyx990803** [comment]
`_uid` is internal and should not be used as part of the application state - I think it's fine as long as the user follows this rule.
