### ISSUE TITLE
Custom methods for text interpolation

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [vuejs/vue#5574]
### What problem does this feature solve?
It will allow to create custom methods(filters) for text interpolation.
Declare those methods as Actions, for example, in vuex and map them app-wide.
Thus, there would be no need in importing libraries.

### What does the proposed API look like?
For example, a developer could simply add the [following function](http://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript) as a method:
```
numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3}) (?!\d))/g, ",");
}
```
And then, inside the mustache syntax do the following:
```
{{ number.numberWithCommas }}
```
That would call the function and return a formatted number.

**Comment by OlzhasAlexandrov** [comment]
Another important part is that it could be applied to specific elements of the template, even though they bind to the same initial value.
Also, it could ease the filtering for text interpolation inside elements that have `v-for`

**Comment by HerringtonDarkholme** [comment]
What's the difference from the native filter, I wonder?
https://vuejs.org/v2/guide/syntax.html#Filters

**Comment by OlzhasAlexandrov** [comment]
oh I apologize, my bad, I missed that feature:)
Thank you for pointing that out

**Comment by OlzhasAlexandrov** [comment]
@HerringtonDarkholme is it possible to define filters once for the whole app though?

**Comment by posva** [comment]
`Vue.filter()`
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks 🙂
