### ISSUE TITLE
Allow key attribute on scoped slots with one single root element

### ISSUE THREAD

**Issue by foosx** [vuejs/vue#5575]
### What problem does this feature solve?
Improving the rendering performance of generic lists.

### What does the proposed API look like?
List.vue
```Vue
...
<slot name="item" :item="item" :key="item.id" v-for="item in items"></slot>
...
```
ListAFlavourA.vue
```Vue
<list>
  <template slot="item" scope="p">
    <item-a :item="p.item" :title="p.item.title | articlesLast" :subtitle="flavorA(p.item)"></item-a>
  </template>
</list>
```
ImaginaryListAFlavourB.vue
```Vue
<list>
  <item-a slot="item" scope="p" :item="p.item">
    <span slot="title">{{ p.item.title }}</span>
    <span slot="subtitle">{{ flavourB(p.item) }}</span>
  </item-a>
</list>
```

**Comment by posva** [comment]
Did you know you can use the `key` inside of the template: http://jsfiddle.net/posva/h2d4syz5/ ?

**Comment by foosx** [comment]
Was certain I tested that variant and didnt notice any performance difference, but it actually works.
Thanks
