### ISSUE TITLE
v-model directive doesn't set according prop value in child component (only when using single file comp)

### ISSUE THREAD

**Issue by chvelkov** [vuejs/vue#5577]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/h864k3yj/](https://jsfiddle.net/h864k3yj/)

### Steps to reproduce
Open the JSFiddle with vue 2.3.0 and then with with 2.2.6.

The result will be different:

With 2.3.0  the value prop is not set and the HTML output will be "PASSED PROP:". 
However with 2.2.6 the app will render "PASSED PROP: From parent" 

Here is the code with the two different versions:

2.3.1: https://jsfiddle.net/h864k3yj/ 
2.2.6: https://jsfiddle.net/gsexe735/

Discussion in Vue Forum about this issue: 
https://forum.vuejs.org/t/vue-2-3-0-reusable-components-v-model-issue/10194/7

### What is expected?
The ```value``` prop of the child component should be set to "From parent"

### What is actually happening?
```value``` is undefined when using vue 2.3.0 

---
I've noticed the issue a few days ago, but the tricky part to reproduce it was the fact that this only happens when using these render functions (which were generated by webpack/vue-loader).

Here's the original source of the two components, which were processed by vue-loader to create the render functions:

The child component, which doesn't receive the prop value:
```javascript

<template>
    <div>PASSED PROP:{{value}}</div>
</template>

<script>
    module.exports = {
        props: {
            value: String,
        }
    };
</script>
```

The parent:
```javascript

<template>
    <test-comp v-model="customVal"></test-comp>
</template>

<script>
    module.exports = {
        data: function() {
            return {
                customVal: 'Value from parent',
            }
        },
        components: {
            'test-comp': require('test-comp.vue'),
        }
    };
</script>

```

**Comment by posva** [comment]
Thanks for reporting this. You should be fine if you update the `vue-loader` package in your project. It has been updated recently. Tell me if this is still not enough so I can test locally.
Using Vue.compile works correctly: https://jsfiddle.net/posva/900Ljx6x/
