### ISSUE TITLE
Naming components in string templates different than in the documentation

### ISSUE THREAD

**Issue by padcom** [vuejs/vue#5581]
### Version
2.3.2

### Reproduction link
[https://jsbin.com/xurineq/2/edit?html,js,output](https://jsbin.com/xurineq/2/edit?html,js,output)

### Steps to reproduce
If component in components section is named in kebab-case then in the template it can only be used in kebab-case. If it is used in camelCase then it can be used in string template as both camelCase and kebab-case but not inTitleCase. When the name specified in components section is named TitleCase then all 3 forms are available in string templates

### What is expected?
According to documentation (https://vuejs.org/v2/guide/components.html#Component-Naming-Conventions) when registering components (or props), you can use kebab-case, camelCase, or TitleCase. Vue doesn’t care. 
The documentation also mentions that "When using string templates however, we’re not bound by HTML’s case-insensitive restrictions. That means even in the template, you can reference your components and props using camelCase, TitleCase, or kebab-case"

### What is actually happening?
components specified using kebab-case don't show when referenced using cameCase and TitleCase

components specified using camelCase don't show when referenced using TitleCase

**Comment by padcom** [comment]
On top of that the vue inspector in devtools always shows the TitleCase form of the component

**Comment by yyx990803** [comment]
The doc needs more clarification, but this is intended behavior. Kebab-case is the baseline and always supported; the other two are just convenience conversions.

This issue belongs to vuejs.org - feel free to submit a PR there.

**Comment by padcom** [comment]
Done. https://github.com/vuejs/vuejs.org/pull/896
