### ISSUE TITLE
Is this a clerical error

### ISSUE THREAD

**Issue by fengyinchao** [vuejs/vue#5585]
### Version
2.2.6

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/src/compiler/codegen/index.js](https://github.com/vuejs/vue/blob/dev/src/compiler/codegen/index.js)

### Steps to reproduce
The code locates in 'src/compiler/codegen/index.js',line 36

transforms = pluckModuleFunction(options.modules, 'transformCode');

I think the second parameter 'transformCode' is wrong, it should be 'transformNode' , because

options.modules[0]={
    genData:...,
    staticKeys:...,
    transfromNode:...  //not transfromCode
}

### What is expected?
transfromNode

### What is actually happening?
transfromCode

**Comment by LinusBorg** [comment]
No, this does not seem like a mistake. `transformCode` also is defined in the flow typings [here](https://github.com/vuejs/vue/blob/29445153e37a3bf973ce10594fcc7cced4707686/flow/compiler.js#L4)
 and unit tested [here](https://github.com/vuejs/vue/blob/7b8b0e48f7b3fa1dd3063d4a2cd38c0cde7baa99/test/unit/modules/compiler/compiler-options.spec.js#L43) (right after testing `transformNode` ;-) )

**Comment by fengyinchao** [comment]
@LinusBorg  Thanks~

**Comment by ouzhaoyuan** [comment]
https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js  The cdn on the official website also has this problem. Just now I thought I wrote the wrong transformNode
