### ISSUE TITLE
Input event triggered when clicking outside of an input field

### ISSUE THREAD

**Issue by laurem1381** [vuejs/vue#5587]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/x38qq616/1/](https://jsfiddle.net/x38qq616/1/)

### Steps to reproduce
In this jsfiddle: https://jsfiddle.net/x38qq616/1/

1) Type a character in the input field. The input event is logged in the console.

2) Click outside of the input field. Another input event is logged in the console (this should not happen)

### What is expected?
No input event should be triggered, like before (in vue 2.6.2)

### What is actually happening?
An input event is triggered

---
This is a regression, it did not occur in vue 2.6.2. This breaks our autocomplete component which relies on input events to trigger autocompletion.

**Comment by renedx** [comment]
Just tested, this is the same random-event mentioned in #5586 :)

**Comment by posva** [comment]
Closing as dup of #5586

**Comment by WouterSioen** [comment]
I have the same issue but with change events. When I click/tab out of an input field, the change event is triggered.
