### ISSUE TITLE
Allow using function call syntax to create a bound function for directive expressions

### ISSUE THREAD

**Issue by JosephSilber** [vuejs/vue#5588]
### What problem does this feature solve?

Similar to event binding, we should allow directive value to create bound functions:

```html
<element v-directive="dontCallMeNow(parameter)"></element>
```

...which would be functionally similar to this:

```html
<element v-directive="dontCallMeNow.bind(null, parameter)"></element>
```

This already works for event bindings:

```html
<element @click="iAmOnlyCalledOnClick(parameter)"></element>
```

...so it makes sense to have the syntax be consistent.

### Here's my use case

I have a `throttled-click` directive, which deactivates the element that was clicked until the returned promise is fulfilled. Here's a pen to better understand it: https://codepen.io/anon/pen/pPrggp

Since this is functionally similar to `@click` it makes sense for the same syntax to work for the both of them.

Currently, doing this:

```html
<button v-throttled-click="move(something)">Move</button>
```

...will call `move(something)` right away, and set its returned value to `binding.value`, which is not what we want.

### What does the proposed API look like?

```html
<element v-directive="method(paramters)"></element>
```

**Comment by posva** [comment]
> will call move(something) right away, and set its returned value to binding.value, which is not what we want.

Unfortunately, yes, it is. The `v-on` directive is an exception because you often need to execute an inline statement. On the other hand, a custom directive, as other directives, expects a value. This would also be a breaking change

You can already pass a function (no params):

```html
<element v-directive="dontCallMeNow"></element>
```

and, as in your example, bind arguments with `bind`

```html
<element v-directive="dontCallMeNow.bind(null, parameter)"></element>
```

`bind` being a commonly used part of js, it's better to know it and benefit from 🙂

**Comment by yyx990803** [comment]
FYI you can use `v-foo="() => foo(bar)"`
