### ISSUE TITLE
Ability to make shallow comparison between prev->next state/props before rendering

### ISSUE THREAD

**Issue by cubodehelio** [vuejs/vue#5590]
### What problem does this feature solve?
Provides a way to make at least a shallow comparison between the current state/props of a component and the next state/props to be able to abort unnecessary or unwanted component re-rendering in some situations pretty much like ReactJS `shouldComponentUpdate()`.

Perhaps I just can't find any mention/example related to this kind of situation or maybe I'm missing something?. In such a case sorry for the inconvenient!

### What does the proposed API look like?
```js
export default {
  beforeUpdate(nextState, nextProps) {
    return nextState.value !== this.value;
  }
};
```

**Comment by yyx990803** [comment]
Every Vue component has a similar mechanism built-in so you don't need to implement this yourself.

**Comment by cubodehelio** [comment]
Maybe i did not express myself well. For example In the case of React `shouldComponentUpdate`, it can be used to deliberately abort a re-rendering even if the current/next state/props are different. That's what  i meant.

Is there a way to accomplish something like that in vuejs?
