### ISSUE TITLE
Using scoped slots not syncing with select object literal

### ISSUE THREAD

**Issue by profsmallpine** [vuejs/vue#5594]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/31241/](https://jsfiddle.net/50wL7mdz/31241/)

### Steps to reproduce
1. Create a child component with a scoped slot.
2. In the parent template, add the scoped template to the child component with a bound select element to a data object.
3. Try selecting an option.

### What is expected?
I expected for this to sync the component object to the selected data object using the select data binding.

### What is actually happening?
Instead, nothing happens. If I change the option's values to string, then it binds correctly. I also noted that doing the same process but putting the select in the child component works as expected.

**Comment by posva** [comment]
`obj` should be initialised. You can find more information about this caveat here: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by profsmallpine** [comment]
@posva The object is initialized in the component's data. Did you misread the reproduction?

**Comment by posva** [comment]
Oh, sorry, I did misread, indeed. What is happening is that the `props` object should be treated as read-only, you **can not modify** the content of the scope in a scoped slot. Modifications of a component should explicitly pass through it

**Comment by profsmallpine** [comment]
Great, thanks! I did note that if  `obj` is a `String`, then this example works successfully. Is that just a side effect but not a recommended use?

**Comment by posva** [comment]
Can you share a fiddle of that? It shouldn't work: https://jsfiddle.net/posva/nyjwjg7x/

**Comment by profsmallpine** [comment]
I did not speak completely correct. It works when using `v-model` on an object's attribute. I guess this would be hard to avoid though since javascript will be pointing to the data object. https://jsfiddle.net/posva/nyjwjg7x/

**Comment by posva** [comment]
Yes, if you point to an attribute of an object, it will work because of javascript nature. No, it's not recommended although it can come in handy sometimes 🙂 
You can, however, pass a method through the scoped slot and use that as the `@change` event handler. Together with a `:value` binding, it replaces the `v-model` in your case. Although it's even better to keep the `select` within the component
