### ISSUE TITLE
SCRIPT1003 : 缺少 ':'  under IE, I use webpack vue router

### ISSUE THREAD

**Issue by float90** [vuejs/vue#5595]
`
new Vue({
  router,
  render: h => h(app)
}).$mount('#app')
`

**Comment by 1615450788** [comment]
Hello, have you solved this problem? I have the same problem, I have no clue for the moment. I also want to point out my e-mail 1615450788@qq.com. Thank you very much

**Comment by haies** [comment]
移除自动生产的代码，比如：
import ElCol from "element-ui/packages/col/src/col";
和
components: { ElCol },
就解决了，

**Comment by Carol1992** [comment]
@haies  你好，我在IE下也碰到这个问题，请问移除自动生产的代码是什么意思，可以说一下解决思路没，谢谢

**Comment by haies** [comment]
比如你使用col标签时，ide会自动生成
import ElCol from `"element-ui/packages/col/src/col";`
和components下的代码，实际上这个在最开始的地方已经引用了，
去掉这个两个地方后就没有这个错误了。@Carol1992

**Comment by byends** [comment]
目前我们也遇到这个问题了。这问题不是 vue 的，但已经提在这里就想问问 @haies 你移除了什么代码？找半天没找出问题所在，编译通过，chrome 下也没问题，就 IE 全线都报错。。。

**Comment by haies** [comment]
我那边也出现这个问题，上面已经说的很清楚了，应该是在页面重复应用了组件

**Comment by byends** [comment]
这就奇怪了。我们是全量引入，并不是单独某个模块引入，另外，webpack 打包本来就会自动处理重复引入的问题，不会出现同一个模块多份的情况。

**Comment by byends** [comment]
这里应该更多是 .babelrc 设置有问题，有空再看细看下 babel 的配置。

**Comment by ionicsakura** [comment]
@haies Thanks for help!!

**Comment by xiyue0814** [comment]
I also encountered this problem，the reason is that I did't config .babelrc
