### ISSUE TITLE
Allow that <slot> have access to all subcomponents declared on component

### ISSUE THREAD

**Issue by rentalhost** [vuejs/vue#5596]
### What problem does this feature solve?
I have [posted to SO](http://stackoverflow.com/questions/43771940/processing-local-components-with-vue/43772093?noredirect=1#comment74586396_43772093), but it seems be impossible currently. 
Then, lets do a feature request!

Seems that the DOM tree is processed from outside to inside, like:

```html
<first>
    <second></second>
</first>
```

Then vue process first the `<first>` then `<second>`. 
It is excelent for what I like to suggest.

Well, imagine that I have a component called `<my-select>` (an alternative to default `<select>`). It should be templated something like that:

```html
<template>
    <div class="Select"><slot></slot></div>
</template>
```

And too I have a subcomponent called `<the-option>`, templated as:

```html
<template>
    <div class="Option"><slot></slot></div>
</template>
```

As `<the-option>` is exclusive to `<my-select>`, does not make senses put it on global scope. Instead, we should declares it as a subcomponent. For instance (from `Select.vue`):

```js
export default {
    components: { theOption: require('./Select.Option.vue') }
}
```

With that method, we could create codes directly on HTML like:

```html
<my-select>
    <the-option>Hello</the-option>
    <the-option>World</the-option>
</my-select>
```

Result should be like:

```html
<div class="Select">
    <div class="Option">Hello</div>
    <div class="Option">World</div>
</div>
```

The problem is, when we run the code, we receives an error like `unknow custom element <the-option>`, justly because it is not declared globally and too because we are putting the content directly to `<slot>`. 

**And here starts the suggestion** (*finally!*).

My suggestion is: allow that `<slot>` have access to all subcomponents declared on component. It'll avoid we globalize very specific subcomponents like this case.

**Edit:** I know that we can pass a list to top component (`<my-select>`), but it spoils the readability when you are working with static code (mainly if you are not using some template engine to convert to JSON easily).

### What does the proposed API look like?
Not affects.

**Comment by posva** [comment]
Thanks for the proposal, unfortunately, this is an implicit behaviour and we are really against that, we want to keep things explicit because that's one of the things that make easy to collaborate on a Vue project.
It's ok to _globalise_ sub-components, my advice is to namespace them:

```
my-select
my-select-option
```

This makes it clearer that a component should be nested inside another
Sometimes you may not even need to namespace them if they're specific enough or if you change the parent name:

```
TabsContainer
Tab
```

**Comment by rentalhost** [comment]
@posva It seems a bit strange behaviour, because subcomponents are allowed if you put it directly on template ([_local registration_](https://vuejs.org/v2/guide/components.html#Local-Registration)):

```html
<template>
    <the-option>Hello</the-option>
</template>
```

The globalize seems to be very overloading because it will declares all subdependencies of a Vue project, even if it not make sense to be used outside a specific context/component (`option` doesn't make senses outside a `select`, for instance, same for tables and cells, tabs container and tabs buttons, so on).

I can't see a pratical reason to it be not wanted, considering this context. 

There are some kind of lifecycle limitation about that? 
If do, is something that we can work to make it possible on future?

**Comment by posva** [comment]
Local registration is **explicit**, that's how we want things to be 🙂

**Comment by rentalhost** [comment]
@posva Maybe we can think about turn local registration explicit too for slots? For instance:

```
<template>
    <div class="Select">
        <!-- slots supports the component "option" too -->
        <slot components="option, ..."></slot>
    </div>
</template>

export default {
    components: { option: require('./Option.vue') }
}
```

With that code we determine _explicity_ that the slot supports a subcomponent allowed on parent.

**Comment by posva** [comment]
But it's still not explicit in the component using the select. It's so much
intuitive and simple to add the component to the parent as usual, with no
new syntax or using the methods I described you above for global components
