### ISSUE TITLE
require.ensure 

### ISSUE THREAD

**Issue by ly-wuyi** [vuejs/vue#5600]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
route code :
const UserQuery = resolve => {
require.ensure(['./modules/userCenter/userQuery.vue'], () => {
resolve(require('./modules/userCenter/userQuery.vue'))
})
};
UserQuery.vue code
<style> .dashboard-user-resetpwd { margin: 0 10px; } </style>

### What is expected?
support webpack require.ensure and .vue style block

### What is actually happening?
at E:\NEProject\ICE\dashboard\client\modules\userCenter\userQuery.vue
at E:\NEProject\ICE\dashboard\client\modules\userCenter\userCenter.vue
at E:\NEProject\ICE\dashboard\client\modules\home\Home.vue
at E:\NEProject\ICE\dashboard\client\modules\App.vue

---
i find:
if delete <style>...</style> or against using webpack's require ensure ,that's working properly.

**Comment by yyx990803** [comment]
This is not a reproduction.
