### ISSUE TITLE
Vue组件中a标签失效问题（项目使用了vue-router）

### ISSUE THREAD

**Issue by WWR1234567** [vuejs/vue#5601]
### Version
2.3.2

### Reproduction link
[http://www.799189744@qq.com/](http://www.799189744@qq.com/)

### Steps to reproduce
//组件为这个
<div class="ad3">
		<a :href="['http://www.baidu.com']">
			<div class="ad-titie">
				{{title}}
			</div>
	   	<div class="ad-ad3">
	   		
			<img :src="imgList[0].img" alt="" :style="{height: scale * 7   'rem' }">
	   	</div>
	   	<p class="ad-ad3-p">
			{{ imgList[0].name }}
		</p>
		</a>
		<a href="http://www.baidu.com">去百度？</a>
	</div>
//在外部应用这个组件 

### What is expected?
这些a标签渲染出来点击之后可以挑战到百度首页，

### What is actually happening?
实际渲染出来，被点击之后的没有跳转到百度，html为：
<div data-v-5c932dc9="" data-v-074b3ff0="" class="ad3"><a data-v-5c932dc9="" href="javascript:void(0)" data-xs-href="http://www.baidu.com"><div data-v-5c932dc9="" class="ad-titie">
			单图片
		</div> <div data-v-5c932dc9="" class="ad-ad3"><img data-v-5c932dc9="" src="https://img.alicdn.com/bao/uploaded/i3/TB1RDO7QFXXXXc8XFXXXXXXXXXX_!!0-item_pic.jpg_430x430q90.jpg" alt="" style="height: 4.62rem;"></div> <p data-v-5c932dc9="" class="ad-ad3-p">
		设计稿分类
	</p></a> <a data-v-5c932dc9="" href="http://www.baidu.com">去百度？</a></div>

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. Provide an editable repro. You can use this as base: http://jsfiddle.net/posva/9r6xhqbp/
Thanks!
