### ISSUE TITLE
Automatically create nested namespaces if not exists

### ISSUE THREAD

**Issue by rottmann** [vuejs/vue#5602]
### What problem does this feature solve?
Automatically register namespaces.

Would be nice to have a function that register the paths or a function to check for path existance, or when registerModule could register the path automatically.

Currently only possible with a hack when access the "private" var `store._modulesNamespaceMap` directly.

I add dynamicaly loaded modules with namespaces (the order of loading could be changed), so each module must check if the namespace exists, if not then create it:

e.g.

    if ( ! store._modulesNamespaceMap['plugins/sub/']) {
      store.registerModule(['plugins', 'sub'], {
        namespaced: true
      })
    }

    if ( ! store._modulesNamespaceMap['plugins/sub/namespace/']) {
      store.registerModule(['plugins', 'sub', 'namespace'], {
        namespaced: true
      })
    }

### What does the proposed API look like?
extend registerModule with auto namespace creation
```
store.registerModule(['plugins', 'sub', 'namespace'], {
  namespaced: true,
  createPath: true // possibly not need an extra option
})
```

**Comment by posva** [comment]
Please, move this issue to https://github.com/vuejs/vuex/.
As for the fr, I don't understand why you would need to dynamically register a nested module before registering the containing modules, you should really talk about that.

**Comment by rottmann** [comment]
Sorry, wrong project.

Our app loads plugins from different companies (marketplace), each company has an own namespace.
e.g. plugins/company1/module1/

There it no separate company1 loading that sets plugins/company1, we have plugin loader that transfer the store to the plugin, which adds his own module1/

So each module from a company must currently check, if company1 exists.

**Comment by posva** [comment]
I think you can add a helper that registers the nested module and create any necessary modules. So those plugins call your `registerModule` instead of `store.registerModule` or register the topmost module if all modules are registered at the same time
