### ISSUE TITLE
optionMergeStrategies.inject

### ISSUE THREAD

**Issue by eddow** [vuejs/vue#5603]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/yywfw3cL/5/](https://jsfiddle.net/yywfw3cL/5/)

### Steps to reproduce
Make a component extend another one while both parent and child define an injection : the parent' injection is lost (overridden)

### What is expected?
Injections to be merged

### What is actually happening?
Injections override parent' ones

---
The injections initialisation looks for the injections own keys - so we cannot merge with a prototype like it is done in function mergeAssets or with "Other object hashes" : props/methods/computed
We instead have to copy the object and extend it in its own properties.
It might be cleaner if it was allowed to use the prototype.

**Comment by posva** [comment]
Thanks for reporting it.

This should be an easy first contribution because it needs little to no knowledge of Vue. The file that needs to be modified is at https://github.com/vuejs/vue/blob/dev/src/core/util/options.js. Inject are arrays or object, it should be able to merge both. `extend` from `shared/utils` can (and prolly should) be used.
In case someone is looking for a first contribution 🙂

**Comment by eddow** [comment]
jaj, ok, got it ;)

**Comment by eddow** [comment]
Salut Posva,
J'essaye de te contacter pour m'aider à installer l'env de dev pour vue (j'ai du mal) - j'essaye FB, sinon pourrais tu me contacter à l'addresse eeddow at protonmail stp?
J'effacerai ce msg quand tu m'auras répondu.

**Comment by LinusBorg** [comment]
> I have a question though : is the easiest way fork->pull request?

Yes.

**Comment by ryzokuken** [comment]
I would like to resolve this as my first contribution to the project.

**Comment by jkzing** [comment]
@ryzokuken Already an opened PR there. :) ([#5827](https://github.com/vuejs/vue/pull/5827))

**Comment by ryzokuken** [comment]
Okay. I'll look someplace else to get acquainted with the source. Thanks.
