### ISSUE TITLE
Allow vm.$watch signature similar to watch property

### ISSUE THREAD

**Issue by Nirazul** [vuejs/vue#5604]
### What problem does this feature solve?
I was running into an issue when using `this.$watch` instead of, what I'm usually doing, using a property within the watch object.
I tried the following signature as this is what I was accustomed:

```js
{
    mounted() {
        if (!this.someTest) {
            return;
        }

        this.$watch('prop', {
            handler() {
                console.log('triggered!');
            },
            immediate: true,
            deep: true,
        });
    },
}
```

instead of

```js
this.$watch('field', function() {
        console.log(`[${ this.field.id }] Watcher triggered!`);
        this.updateVal();
    }, {
    immediate: true,
    deep: true,
});
```

Is there a reason that this signature is not supported?

### What does the proposed API look like?
```js
this.$watch('prop', {
    handler() {},
    immediate: true,
    deep: true,
});
```

**Comment by LinusBorg** [comment]
There's no specific design decision behind this - it's just a common way of setting up such a function's arguments.

I can understand that similar API may seem intriguing, but personally I don't think that both API's need to be the same - one is a function call, the other is a config object, it's ok that they are different, and the API docs clearly document this.

Changing the syntax would be a breaking change that's not justified, and supporting both would add bloat to the codebase that is still not justified just by the comfort of a more similar API.

**Comment by Nirazul** [comment]
I understand. Would you agree that adding a warning would be appropriate?
