### ISSUE TITLE
Style is missing

### ISSUE THREAD

**Issue by luandapipi** [vuejs/vue#5609]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/luandapipi/vnq3ye9L/](https://jsfiddle.net/luandapipi/vnq3ye9L/)

### Steps to reproduce
1.new a iamges array
2. change array item value

### What is expected?
Old pictures are modified for new pictures, everything else is the same.

### What is actually happening?
The picture changed, but the style  background-size was gone.

**Comment by xujiongbo** [comment]
The ```background``` is a short hand for background styles including ```background-size```, use ```background-image``` instead of ```background``` will solve your problem.

**Comment by xujiongbo** [comment]
The ```background``` is a short hand for background styles including ```background-size```, use ```background-image``` instead of ```background``` will solve your problem.

**Comment by luandapipi** [comment]
@xujiongbo Thanks! I solve my problem!
