### ISSUE TITLE
Everything disappeared from the DOM.

### ISSUE THREAD

**Issue by iDhruv22** [vuejs/vue#5612]
### Version
2.3.2

### Reproduction link
http://jsfiddle.net/zfwnkc7e/

### Steps to reproduce
Provided comments in JSFiddle URL

### W](url)hat is expected?
There should be an error.

### What is actually happening?
The body content is disappeared.

**Comment by simplesmiler** [comment]
Not a bug, `v-bind` expects an expression.
Either use `src="https://..."` or `v-bind:src="'https://...'"` (note the single quote around the value).

**Comment by iDhruv22** [comment]
It should throw the error, removing everything from DOM is not correct.

**Comment by posva** [comment]
It does, you have to use the non minified version of vue 😉
