### ISSUE TITLE
Is element.__vue__ save to use?

### ISSUE THREAD

**Issue by jantimon** [vuejs/vue#5621]
Is there a clean way to get the current vue instance from a given DOM node or is it even future save to access `element.__vue__`?

The use case is the integration with a large famous enterprise content management system where we would like to build up all content elements out of vue components.
Unfortunately the CMS ships with javascript code which can't be changed without too high efforts.
These third party scripts allow authors of the cms to use drag'n'drop to place new content element (e.g. a carousel or a teaser) to the page.
After the drag'n'drop happened an event is fired which we would like to bind on and reinitialize all new placed inline template elements.

We managed to come up with a hack but maybe there is a better solution for this use case:
https://jsfiddle.net/5vxwr34o/

```js
/**
 * Content change handler
 */
function handleContentChange() {
  const inlineTemplates = document.querySelector('[inline-template]');
	for (var div of divs) {
    processNewElement(inlineTemplate);
  }
}

/**
 * Tell vue to initialize a new element
 */
function processNewElement(element) {
  const vue = getClosestVueInstance(element);
  new Vue({
    el: element,
    data: vue.$data
  });
}

/**
 * Returns the __vue__ instance of the next element up the dom tree
 */
function getClosestVueInstance(element) {
  if (element) {
    return element.__vue__ || getClosestVueInstance(element.parentElement);
  }
}
```

**Comment by yyx990803** [comment]
To some extent yes - the official devtool relies on it too, so it's unlikely to change or break.

**Comment by jantimon** [comment]
Thanks @yyx990803 - you see any reason not to follow this approach?

**Comment by yyx990803** [comment]
@jantimon can't really say much because this is such a niche case, but I'd suggest tearing down existing Vue instances that are no longer needed.

**Comment by Regaddi** [comment]
@yyx990803 I'm not sure if this is really a niche case. This pretty much affects every WYSIWYGish UI representation for editors of any content management system with such a feature.
From the point on you need or rely on some client-side rendering technique in a content component this case becomes present.
That are just my cents for this discussion 😃

**Comment by matthiasg** [comment]
we have had some issues were an outer component just delegates to another component using `<component :is="...">`  in those cases the outer component and the inner component both linked to the same $el and the __vue__ property was sometimes linked to the out component and sometimes to the inner component. So we don't rely on __vue__ to find the correct component all the time.

**Comment by rustyx** [comment]
Nitpick: `save` is a verb, `safe` is an adjective. These are [different words](https://translate.google.com/#op=translate&sl=en&tl=de&text=safe%2C%0Asave).

**Comment by nfplee** [comment]
What's the equivalent in Vue 3? I see there's `__vueParentComponent` but I have to now say __vueParentComponent.props.x instead of __vue__.x.

**Comment by hugoattal** [comment]
I think the vue3 equivalent would be `element.__vueParentComponent.ctx.$props`.
