### ISSUE TITLE
Vue.js is not available on Android 4.0.4 phone

### ISSUE THREAD

**Issue by meiliujun** [vuejs/vue#5623]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/nxymatcd/](https://jsfiddle.net/nxymatcd/)

### Steps to reproduce
1. use new Vue(...)
2. js is go dying

### What is expected?
new Vue object return true

### What is actually happening?
Uncaught SyntaxError
![img_20170504_160826](https://cloud.githubusercontent.com/assets/7381228/25777938/a793e600-3321-11e7-963c-0c4c4b475655.jpg

---

error msg in attachments

**Comment by meiliujun** [comment]
图片好像太大传炸了。。。
![1](https://cloud.githubusercontent.com/assets/7381228/25777938/a793e600-3321-11e7-963c-0c4c4b475655.jpg)
![2](http://a2.qpic.cn/psb?/700939298/nw5Il.BQFTdftFYaSqNNEYcqy9TnhmAH0Q9lA9n3R4c!/b/dG0BAAAAAAAA&ek=1&kp=1&pt=0&bo=FwOAAgAAAAARF7Y!&tm=1494129600&sce=60-3-3&rf=viewer_4)
![3](http://a3.qpic.cn/psb?/700939298/H5R6.uphAeY2LlY.pw0951DX.0u7MNXt*PaHQVmQenM!/b/dG0BAAAAAAAA&bo=gAJfAwAAAAARAOk!&rf=viewer_4)

我现在用最简单粗暴的方式解决了。
1vue.js里面的native关键字改成其他的native123xxx
2vue.js里面的严格模式去掉 //use strict;

**Comment by posva** [comment]
Don't have a device to test but the strict mode (which doesn't work on Android) is added by something else. Does the docs work: https://vuejs.org/v2/guide/#Handling-User-Input

**Comment by defcc** [comment]
@meiliujun 用的什么浏览器？

**Comment by meiliujun** [comment]
@defcc 一开始怀疑是某app内嵌的浏览器有问题，所以用的Google Nexus 原生浏览器再次做过测试还是白屏。
