### ISSUE TITLE
Expose an option to change contentPlaceholder value in createBundleRenderer function

### ISSUE THREAD

**Issue by vanesyan** [vuejs/vue#5624]
### What problem does this feature solve?
Make it more flexible it terms of SSR, allows developers decide on placeholder name, rather strictly dictate which one to use (i.e. `<!--vue-ssr-outlet-->`).

### What does the proposed API look like?
Assume following is `options` object for `createBundleRender` function
```
{
  ...
  contentPlaceholder: '{{{ app }}}'
}
```

**Comment by posva** [comment]
why would it make it more flexible?

**Comment by vanesyan** [comment]
For example, if I build framework something like next.js, I'd like to use layout with custom vue application entry name differ from 'vue-ssr-outlet' to make it a bit abstract out of implementation details.

**Comment by dsonet** [comment]
Would add extra cost to learn but gain barely benefit.
