### ISSUE TITLE
ssr-client-manifest & ssr-server-bundle can't be emitted to a non-public dir

### ISSUE THREAD

**Issue by riophae** [vuejs/vue#5626]
### Version
2.3.2

### Reproduction link
[https://github.com/riophae/vue-ssr-bug-minimal-reproduction](https://github.com/riophae/vue-ssr-bug-minimal-reproduction)

### Steps to reproduce
Follow these steps:

```bash
git clone https://github.com/riophae/vue-ssr-bug-minimal-reproduction.git
cd vue-ssr-bug-minimal-reproduction
npm install
npm run dev
```

Then open URL: `http://localhost:5000`, the app should work fine. 

Look into the `dist/` dir and it should be like this:

```
vue-ssr-bug-minimal-reproduction/dist
├── main.bundle.js
├── vue-ssr-client-manifest.json
└── vue-ssr-server-bundle.json

```

You can see that `main.bundle.js` and the ssr-client-manifest & ssr-server-bundle files are all there. Since we only use the ssr-client-manifest & ssr-server-bundle in the server side, those files should not be placed in a public folder.

Then I tried to specify a different dir for ssr-client-manifest & ssr-server-bundle to store by uncommenting [L10 of `build/webpack.client.config.js`](https://github.com/riophae/vue-ssr-bug-minimal-reproduction/blob/master/build/webpack.client.config.js#L10) and [L15 of  `build/webpack.server.config.js`](https://github.com/riophae/vue-ssr-bug-minimal-reproduction/blob/master/build/webpack.server.config.js#L15),  and rebuild the app by:

```bash
npm run dev
```

Then I don't see ssr-client-manifest & ssr-server-bundle files in the dir `build/non-public/` but in a very deep dir in `dist/`, which is `dist/mnt/d/Projects/vue-ssr-bug-minimal-reproduction/build/non-public-dir/` in my case. (My OS is WSL for Linux.)

### What is expected?
ssr-client-manifest & ssr-server-bundle files should be emitted to the dir `build/non-public/`

### What is actually happening?
ssr-client-manifest & ssr-server-bundle files were emitted to the dir `dist/mnt/d/Projects/vue-ssr-bug-minimal-reproduction/build/non-public-dir/`

**Comment by yyx990803** [comment]
Use a relative file path like `../`. Also - `dist` isn't necessarily public: it depends on how you serve it on your server. You can exclude `.json` files from your static serving middleware, or put public assets under `dist/public` instead.

**Comment by riophae** [comment]
It works, though I still think it would be better if absolute path is possible.
