### ISSUE TITLE
the vue page display as blank in the phone browser

### ISSUE THREAD

**Issue by leavesgreen** [vuejs/vue#5629]
### Version
2.3.2

### Reproduction link
[http://elemefe.github.io/mint-ui/#/](http://elemefe.github.io/mint-ui/#/)

### Steps to reproduce
http://elemefe.github.io/mint-ui/#/

this is the mint-ui project demo page. just open it in the pc web browser. and wechat inner browser, the other phone browser.

### What is expected?
all the browser shows well.

### What is actually happening?
the other phone browser show only a blank page.

---
I create a vue2.0 cli project and it run well on pc web browser. also display well in wechat inner browser.
but can not be displayed in qq,uc,sogou browser on the phone.

**Comment by yyx990803** [comment]
This is not necessarily a Vue issue. Please open at MintUI's repo instead.

**Comment by leavesgreen** [comment]
in fact I tried  mint-ui , and muse ui , which also build by vue2.0, and the two  have the same problem.  and I found even the mint-ui demo itself can not be opened in the mobile web browser. so I think there might be something wrong with vue.

**Comment by yyx990803** [comment]
Probably just lacking a Promise polyfill.

**Comment by wards247** [comment]
你好~我也是遇到这个问题~请问提问者这个问题解决了吗?

**Comment by wards247** [comment]
你好 我也是遇到这个问题 请问提问者这个问题解决了吗?
