### ISSUE TITLE
Cannot build successfully with pug

### ISSUE THREAD

**Issue by HuangStomach** [vuejs/vue#5630]
### Version
2.3.2

### Steps to reproduce
My webpack configuration is copied from VHN 2.0 without modification

I introduced the pug to do the development process without any problems

But when the build suggested that I can not find pug-loader

I do not know how to introduce the development environment used by the loader, so the additional installation of the pug-loader and made the following configuration

···
module.exports = {
  extractCSS: process.env.NODE_ENV === 'production',
  preserveWhitespace: false,
  postcss: [
    require('autoprefixer')({
      browsers: ['last 3 versions']
    })
  ],
  loaders: {
    'pug': 'pug-loader'
  }
}
···

But when I use npm run start to start the service, any visit to give me a gray page back there is no error

And I switch back to the development environment because pug-loader also thrown an exception, so I had to be in addition to the development of pug-loader deleted

I may not understand the depth of the webpack, the current investigation of difficult progress

### What is expected?
Can run successfully with pug

### What is actually happening?
:(

---
From Google Translate

**Comment by yyx990803** [comment]
Sorry but this is a question and not a bug report.

**Comment by HuangStomach** [comment]
After I try to find problem from my project but get nothing
I clone VHN 2.0 and modify a component use pug
```
<template lang="pug">
transition
  svg.spinner(:class="{ show: show }" v-show="show" width="44px" height="44px" viewBox="0 0 44 44")
    circle.path(fill="none" stroke-width="4" stroke-linecap="round" cx="22" cy="22" r="20")
</template>
```

and as the vue-loader document said:

Processing templates is a little different, because most Webpack template loaders such as pug-loader return a template function instead of a compiled HTML string. Instead of using pug-loader, we can just install the original pug:

```
npm install pug --save-dev
<template lang="pug">
div
  h1 Hello world!
</template>
```

I do it step by step, but the problem is still in the case of `npm run build`
only with `npm run build`:

```
ERROR in ./src/components/Spinner.vue
Module not found: Error: Can't resolve 'pug-loader' in '/data/vue-hackernews-2.0/src/components'
 @ ./src/components/Spinner.vue 8:2-343
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/ItemView.vue
 @ ./src/views/ItemView.vue
 @ ./src/router/index.js
 @ ./src/app.js
 @ ./src/entry-client.js
```

so……may still be an issue?

> From Google Translate
