### ISSUE TITLE
prop modifier doesn't work on v-bind

### ISSUE THREAD

**Issue by ma1oy** [vuejs/vue#5631]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/ma1oy/o43ksfkx/5/](https://jsfiddle.net/ma1oy/o43ksfkx/5/)

### Steps to reproduce
Bind the whole object to component's properties, but not to attributes (through `prop` modifier)

### What is expected?
Properties must be bounded only to component's properties.

### What is actually happening?
Properties hadn't been bounded.

**Comment by posva** [comment]
`.prop` is for element properties like `innerHTML`. Remove it and you're good to go

**Comment by ma1oy** [comment]
@posva but without this modifier there are still some unnecessary data in html if property has not presented in component. In the previous version of vue it had worked fine. Can you explain me please, why its behavior had changed?

**Comment by posva** [comment]
It never worked that way... You can find more info at https://github.com/vuejs/vue/issues/5606

**Comment by ma1oy** [comment]
@posva thank you very much and sorry to have wasted your time)
