### ISSUE TITLE
vue crash on ios8.12

### ISSUE THREAD

**Issue by luandapipi** [vuejs/vue#5632]
### Version
2.3.2

### Reproduction link
[http://mall.sentree.com.cn/wxmall/?#/shop](http://mall.sentree.com.cn/wxmall/?#/shop)

### Steps to reproduce
1.打开网站链接
2.点击任意商品详情页
3点击左上角的返回（使用的是this.$router.replace()方法）

### What is expected?
点击返回后正常返回首页

### What is actually happening?
浏览器白屏或微信直接崩溃退出

---
问题只会出现在ios8.x的版本的浏览器，其他版本的所有移动\pc浏览器均无此问题。
且一般是页面直接崩溃捕获不到任何异常。(用的是sentry异常框架)

**Comment by LinusBorg** [comment]
> http://mall.sentree.com.cn/wxmall/?#/shop

that's not a reproduction.
