### ISSUE TITLE
Data object naming with _ prefixes

### ISSUE THREAD

**Issue by vyushin** [vuejs/vue#5638]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/vyushin/54q4t5m0/4/](https://jsfiddle.net/vyushin/54q4t5m0/4/)

### Steps to reproduce
Open JSFiddle link and click "run". Look at the "vm2 part of code". I set data prop "_message" and it's not working with computed getters and setters.

### What is expected?
I want to feel free for variables naming

### What is actually happening?
Data props with _ prefixes doesn't working as axpected

---
I like Vue.js but I want to be free for variables naming. Underscore in variable name is not JavaScript exception. It's limitation of Vue.js.

**Comment by xujiongbo** [comment]
>Properties that start with ```_``` or ```$``` will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as ```vm.$data._property```.

See [https://vuejs.org/v2/api/#data](https://vuejs.org/v2/api/#data)

**Comment by vyushin** [comment]
Thanks for answer!
