### ISSUE TITLE
Transition not works with v-else

### ISSUE THREAD

**Issue by ekctpemict** [vuejs/vue#5639]
### Version
2.3.2

### Reproduction link
[https://codepen.io/EKCTPEMICT/pen/QvaRMq](https://codepen.io/EKCTPEMICT/pen/QvaRMq)

### Steps to reproduce
Open link and push the button.

### What is expected?
Smooth transition

### What is actually happening?
Elements changed without transition

**Comment by posva** [comment]
You didn't add any css for the transition. Also beware of Vue optimization to reuse dom elements. You may need to use `key`: https://vuejs.org/v2/api/#key
