### ISSUE TITLE
Nested Transition Not Working

### ISSUE THREAD

**Issue by nkalush** [vuejs/vue#5647]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/7xfktcn9/](https://jsfiddle.net/7xfktcn9/)

### Steps to reproduce
Try to transition elements inside an element that is transitioned.

### What is expected?
The interior elements would use the rules from the closest tag when they are supposed to transition.

### What is actually happening?
The interior elements do not transition, they use neither the closest or parent's transition tag's rule.

---
Might be similar to https://github.com/vuejs/vue/issues/3664, but that is for a much older version of vue and the user provided no jsfiddle and his example code used extra stuff.

**Comment by posva** [comment]
You need to add a `key` attr to the tabs 🙂 https://jsfiddle.net/me0tftdw/

**Comment by nwallis** [comment]
Is there mention of adding key in the docs - why does that need to be added?
