### ISSUE TITLE
Sync prop validation

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#5649]
### What problem does this feature solve?
Now that the `sync` modifier is back, make sense to recover the sync validator as well.

### What does the proposed API look like?
If an component relies on the sync modifier should be possible to state it on the prop declaration as:

```
props: {
  syncedProp: {
   sync: true
  }
}
```

**Comment by ktsn** [comment]
IMHO, we should not introduce `sync` prop validation in v2 since `sync` modifier in v2 is just a syntax suger of corresponding `v-on` handler. If a child component can have the `sync` validation, that would mean the child can control the state update strategy of the parent.

**Comment by miljan-aleksic** [comment]
You may be right. Ok.
