### ISSUE TITLE
HTML5 History and cyrillic chars

### ISSUE THREAD

**Issue by akaNightmare** [vuejs/vue#5655]
### Version
2.3.3

### Reproduction link
[http://jsfiddle.net/xgrjzsup/2052/](http://jsfiddle.net/xgrjzsup/2052/)

### Steps to reproduce
1. Click on Go to Foo link
2. Click on Go to Bar link
3. Click on Go to Foo link
4. Click on Go to Bar link
5. Click on back button or press `Alt + Left arrow` on keyboard

### What is expected?
when I click on back button
I see changing router-view from one state to another

### What is actually happening?
triggering `        { path: '*', component: NotFoundComponent },
`

**Comment by posva** [comment]
This belongs to vue-router
Dup of vuejs/vue-router#838
TLDR: don't use Unicode characters in route paths because they're not officially supported
