### ISSUE TITLE
v-on:click not adding to event listener

### ISSUE THREAD

**Issue by sethdorris** [vuejs/vue#5656]
### Version
2.3.3

### Reproduction link
[https://github.com/sethdorris/fantasymx](https://github.com/sethdorris/fantasymx)

### Steps to reproduce
You have to try it in my branch, I have been unable to reproduce on minimal reproduction tools.

https://github.com/sethdorris/fantasymx

login.vue
```
<template>
  <div>
      <div>Login</div>
      <div>
        <label for="reg-username">Username: </label>
        <input type="text" id="reg-username" v-model="username"/>

        <label for="reg-password">Password: </label>
        <input type="password" id="reg-password" v-model="password"/>

        <input type="button" id="submit-login" v-on:click="submit" />
      </div>
  </div>
</template>

<script>
export default {
  name: "login",
  data() {
    return {
      username: '',
      password: ''
    }
  },
  asyncData({store}) {
    console.log(store.state);
    return store.state.username;
  },
  methods: {
    submit: function() {
      console.log("hi")
    }
  }
}
</script>
```

### What is expected?
expect submit method to fire

### What is actually happening?
no event listener is even attached when using v-on:click directive

**Comment by AleksejDix** [comment]
Use submit inside of the form field. 
Button has a default type of submit inside form. 

You can use @submit.prevent="submitForm"

**Comment by LinusBorg** [comment]
See @AleksejDix's explanation

**Comment by sethdorris** [comment]
That also didn't work. I'm telling you, you'll have to actually checkout my branch, something weird is going on here with the directive that is preventing the attachment of the event listener.

**Comment by LinusBorg** [comment]
May have a look later.

But generally, if you fail to reproduce this in a simple setup, it's probably something with your setup, in which case this issue tracker is the wrong place, and something like our forum.vuejs.org would be the right one.

**Comment by LinusBorg** [comment]
Just tried to quickly clone it - the server doesn't start up:
> Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5432
>    at Object.exports._errnoException (util.js:1050:11)
>    at exports._exceptionWithHostPort (util.js:1073:20)
>    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

So no way for me to check this problem out quickly.

**Comment by sethdorris** [comment]
why is it trying to connect on port 5432, the https server should be running off port 3000

**Comment by xujiongbo** [comment]
It's the database server which listening on 5432.

**Comment by sethdorris** [comment]
I deleted the username and password from the server configurations on server/app.js, you'll need postgres

**Comment by TheDutchCoder** [comment]
Works fine, something must be up at your end: https://jsfiddle.net/z11fe07p/1771/

**Comment by sethdorris** [comment]
I know, but that's also without SSR setup... it works when using client side rendering, but something in the SSR is messing with the directives I think.

**Comment by yyx990803** [comment]
![screen shot 2017-05-12 at 1 17 29 pm](https://cloud.githubusercontent.com/assets/499550/25983180/65c182c6-3715-11e7-98b3-2b62235ee6df.png)

Copied your component verbatim into the Vue HN setup and the hydration is working properly. This is likely a problem in your specific setup/logic. Please try to further isolate the issue into something that can demonstrate it is indeed caused by Vue.

**Comment by sethdorris** [comment]
Thanks so much for looking into this all.

**Comment by Gi60s** [comment]
@sethdorris Did you ever get this figured out? I'm using webpack with vue and seeing the same issue. Click listener not being added to anything but v-binds and templating seems to work.

**Comment by VitaliPom** [comment]
same here, any issue resolve?

**Comment by Gi60s** [comment]
@VitaliPom It's been two months so I don't remember the details exactly, but I think there was a problem with my webpack configuration. I ended up finding a sample webpack config somewhere in the Vue documentation or forums (can't remember). That ended up making it work. Not sure why webpack would cause Vue to have issues.

**Comment by VitaliPom** [comment]
Okay thank you James. Meanwhile for myself, since I'm candidate for job
interviews I decided indeed to use vuejs,  but as soon as I struggle with
such catchy feature, I leave it alone and do a regular listener that would
call native Java Script. Eventually this is a big bonus, that we can access
data objects directly through js. (Meaning by all that for future purposes)

**Comment by tuboythers** [comment]
Hello! 

I am aware it's more than an year since the issue was posted, however, I couldn't locate anything on the Internet which might point me towards what the issue is, and I experience the very same issue.

Does anyone have any insights on the matter, which might help ? 

Basically, here is what I have:

`template>
    <div class="panel-menu builder">
        <div class="add-block" @click="openHierarchy()">
            <h1>Add block</h1>
        </div>
    </div>
</template>

<script>
import { EventBus } from '@/api/eventbus.js'

export default {
    methods: {
        openHierarchy () {
            console.log('test')
            EventBus.$emit('open-hierarchy')
        }
    }
}
</script>`

The click listener neither gets attached, neither does when I try to alter it accordingly like so: v-on:click/.native.

**Comment by crtjr64** [comment]
No and I'm having the same issue. I have been consistently having issues where the documentation verbatim in VueJs just doesn't work with Typescript and the 1 page Typescript and blog information is like feeding a hungry elephant a peanut.  So I'm stuck on an endless search trying to piece together instructions looking for the solution... sometimes it has taken days, sometimes minutes or hours, but every time it delays development and I've been programming for over 20 years. Take listeners, for example, at Vue Js website: https://vuejs.org/v2/guide/events.html is the instruction
````
<button v-on:click="warn('Form cannot be submitted yet.', $event)">
  Submit
</button>
---with the code 
methods: {
  warn: function (message, event) {
    // now we have access to the native event
    if (event) event.preventDefault()
    alert(message)
  }
}
````
For Typescript in my Core 2 environment I use:

````
<div id="grid-root"  v-on:click="warn('Form cannot be submitted yet.', $event)" >
---with code:
    warn(msg: string, e: any) {
        alert(msg);
    }
````
and immediately, the loader comes back with the following to which I have NO IDEA where to even begin to search for an answer. I can only add this to the myriad of features that just don't work! Using VueJs with Typescript and Core 2 was a huge mistake and I often find myself very frustrated spending most of my time searchinf and trying to piece together "how tos" in order to resolve the issues that continue to come up. While Vue Js and Typescript both have an appeal, I will never these these two together again. .Net does nto require a loader or bundler. Why force that issue. Use Vue Js by way of CDN and Visual Studio's  very basic bundling and then use the VueJs library as documented, or wait until whenever "they" decide it is important enough to do something about this:

ERROR in ./~/vue-loader/lib/template-compiler?{"id":"data-v-cb2b88ae"}!./~/vue-loader/lib/selector.js?type=template&index=0!./ClientApp/components/resource/resource.vue.html
(Emitted value instead of an instance of Error) 
  Error compiling template:
  
  <div>
      <div id="grid-root" v-on="click: onClick('Hello', event)" >
          
          <div style="font-size:.8em;">
              <div class="search-flex-container">
                  <div class="opts-flex-container">
                      <div class="lg-box">
                          <label class="">Search</label>
                          <input id="search" type="text" class="form-control" style="max-width: 250px; " name="query" v-model="searchQuery" />
                      </div>
                      <div class="compound-ddl">
                          <label class="">PCO Status </label><br />
                          <b-btn v-b-toggle.pcostatusColl data-toggle="tooltip" :title="selectedPcoStatusFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:90px;text-align: left;">{{selectedPcoStatusFilters.length === 1? selectedPcoStatusFilters[0]: '[Filtered]'}}</div>
                              <div style="display:inline-block;margin-left:10px;" class="arrow-down"></div>
                          </b-btn>
                          <b-collapse id="pcostatusColl" class="togl-ddl">
                              <b-card>
                                  <div id="ddlListContainers">
                                      <div v-for="status in filteredPcoStatusList"  style="font-size:1em; font-weight:500;"><input type="checkbox" @change="closePcoStatuOnAll" :value="status.phaseItemDesc" v-model="selectedPcoStatusFilters" /><span style="margin:0 auto;">{{status.phaseItemDesc}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                      <div class="compound-ddl">
                          <label class="">PCO Code</label><br />
                          <b-btn v-b-toggle.pcocodeColl data-toggle="tooltip" :title="selectedPcoCodeFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:90px;text-align: left;">{{selectedPcoCodeFilters.length === 1? selectedPcoCodeFilters[0]: '[Filtered]'}}</div>
                              <div style="display:inline-block;margin-left:10px;" class="arrow-down"></div>
                          </b-btn>
                          <b-collapse id="pcocodeColl" class="togl-ddl">
                              <b-card>
                                  <div id="ddlListContainer">
                                      <div v-for="pcoCode in filteredPcoCodeList" style="font-size:1em; font-weight:500;"><input type="checkbox" @change="closePcoCodeOnAll" :value="pcoCode" v-model="selectedPcoCodeFilters" /><span style="margin:0 auto;">{{pcoCode}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                  </div>
                  <div id="hiddenFilterClose" class="opts-flex-container hide" >
                      <button style="width:35px; height:35px;" v-bind:class="{hide: anyFiltersOn}" v-on:click="clearFilter"><font-awesome-icon icon="filter" style="margin-top:2%; font-size:1.8rem; color:rgb(5, 59, 122);" ></font-awesome-icon></button>                        
                  </div>
                  <div class="opts-flex-container">
                      <div class="compound-ddl">
                          <label class="">Division </label><br />
                          <b-btn v-b-toggle.divsColl data-toggle="tooltip" :title="selectedDivisionFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:105px;text-align: left;">{{selectedDivisionFilters.length === 1? selectedDivisionFilters[0]: '[Filtered]'}}</div>
                              <div style="display:inline-block;margin-left:10px;" class="arrow-down"></div>
                          </b-btn>
                          <b-collapse id="divsColl" class="togl-ddl">
                              <b-card style="max-height: 400px;overflow-y:auto;">
                                  <div id="ddlListdivsContainer">
                                      <div v-for="divs in divisionList" v-on:mousedown.stop="closeUncollapsed" style="font-size:1em; font-weight:500; white-space: nowrap;"><input v-on:click.stop="closeUncollapsed"  type="checkbox" @change="filteredDivision" :value="divs" v-model="selectedDivisionFilters" /><span style="margin:0 auto;">{{divs}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                      <div class="compound-ddl">
                          <label class="">Region </label><br />
                          <b-btn v-b-toggle.regionColl data-toggle="tooltip" :title="selectedRegionFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:115px;text-align: left;">{{selectedRegionFilters.length === 1? selectedRegionFilters[0]: '[Filtered]'}}</div>
                              <div class="arrow-down" style="display:inline-block;margin-left:10px;"></div>
                          </b-btn>
                          <b-collapse id="regionColl" class="togl-ddl">
                              <b-card style="max-height: 400px;overflow-y:auto;">
                                  <div id="ddlListregContainer">
                                      <div v-for="region in regionList" style="font-size:1em; font-weight:500; white-space: nowrap;"><input type="checkbox" @change="filteredRegion(true)" :value="region" v-model="selectedRegionFilters" /><span style="margin:0 auto;">{{region}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                      <div class="compound-ddl">
                          <label class="">District </label><br />
                          <b-btn v-b-toggle.districtColl data-toggle="tooltip" :title="selectedDistrictFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:150px;text-align: left;">{{selectedDistrictFilters.length === 1? selectedDistrictFilters[0]: '[Filtered]'}}</div>
                              <div class="arrow-down" style="display:inline-block;width:10px;"></div>
                          </b-btn>
                          <b-collapse id="districtColl" class="togl-ddl">
                              <b-card style="max-height: 400px;overflow-y:auto;">
                                  <div id="ddlListdistContainer">
                                      <div v-for="district in districtList" style="font-size:1em; font-weight:500; white-space: nowrap;"><input type="checkbox" @change="filteredDistrict(true)" :value="district" v-model="selectedDistrictFilters" /><span style="margin:0 auto;">{{district}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                      <div class="compound-ddl">
                          <label class="">Branch </label><br />
                          <b-btn v-b-toggle.branchColl data-toggle="tooltip" :title="selectedBranchFilters.join()" variant="primary">
                              <div style="color:lightgray;display:inline-block;width:190px;text-align: left;">{{selectedBranchFilters.length === 1 ? selectedBranchFilters[0]: '[Filtered]'}}</div>
                              <div class="arrow-down" style="display:inline-block;width:10px;"></div>
                          </b-btn>
                          <b-collapse id="branchColl" class="togl-ddl">
                              <b-card style="max-height: 400px; width:220px; overflow-y:auto;">
                                  <div id="ddlListbranContainer">
                                      <div v-for="branch in branchList" style="font-size:1em; font-weight:500; white-space: nowrap;"><input type="checkbox" @change="filterBranch(true)" :value="branch" v-model="selectedBranchFilters" /><span style="margin:0 auto;">{{branch}}</span></div>
                                  </div>
                              </b-card>
                          </b-collapse>
                      </div>
                  </div>
              </div>
          </div>
          
          <div id="frozen-grid-header" class="mi-freeze-header-container">
              <div class="frozen-header-border"></div>
              <div class="mi-grid-container">
                  <table class="">
                      
                      <thead>
                          <tr class="header-flex-container">
                               <th class="font-bold " style="text-wrap:normal;" v-for="column in currStageCols">
                                  <div>
                                      <label style="" class="">{{ column.columnHeader }}</label>
                                  </div>
                              </th>
                          </tr>
                      </thead>
                      
                      <tbody class="">
                          <tr v-for="rec in filteredData" vb-bind:data-pcostatus="rec.pcoCode.length > 0 && rec.commentsToLiquidate > 0? 'C': 'I'">
                              <td class="td-small " v-if="checkFieldStage('Action')">
                                  <input type="button" style="cursor: pointer;" value="PCO Req" data-toggle="modal" data-target="#pcoChangeRequestsModal" @click="setAccount(rec.accountNumberWithBranch, $event)" />
                              </td>
                              <td class="td-small" style="word-wrap:break-word; white-space: nowrap; font-size:1.2rem; font-weight:600; " data-toggle="tooltip" :title="getTitle(rec.pcoStatus)">
                                  
                                  {{rec.pcoStatus}}
                              </td>
                              <td class="selectable td-base-lg">
                                  <select class="mi-form-control mi-cell-default" v-model="rec.pcoCode" @change="updateComments(rec.pcoCode, rec.accountNumberWithBranch)">
                                      <option :value="stripPcoCodeFromWord(pcoCode)" v-bind:disabled="authNfi(pcoCode)" v-for="pcoCode in pcoCodeListDe">{{pcoCode}}</option>
                                  </select>
                              </td>
                              <td class="td-large" v-if="checkFieldStage('accountNumberWithBranch')">
                                  <div class="mi-edit-container" style="display: flex; padding-right: 10px;">
                                      <textarea v-bind:disabled="rec.pcoCode.length == 0" @blur="SavePcoCodeToDb(rec.accountNumberWithBranch, $event)" class="mi-form-control mi-cell-default" type="text" rows="10" v-model="rec.commentsToLiquidate"></textarea>
                                  </div>
                              </td>
                              <td class="left-justify td-base" v-if="checkFieldStage('RequestedPcoCode')">
                                  {{rec.RequestedPcoCode}}
                              </td>
                              <td class="left-justify td-base-lg" v-if="checkFieldStage('RequestedPcoCodereason')">
                                  {{rec.RequestedPcoCodereason}}
                              </td>
                              <td class="left-justify" style="text-wrap:none" v-if="checkFieldStage('divisionName')">
                                  {{rec.divisionName}}
                              </td>
                              <td class="left-justify" style="text-wrap:none" v-if="checkFieldStage('region')">
                                  {{rec.region}}
                              </td>
                              <td class="left-justify" style="text-wrap:none" v-if="checkFieldStage('districtName')">
                                  {{rec.districtName}}
                              </td>
                              <td class="left-justify" style="white-space: nowrap;" v-if="checkFieldStage('branchName')" data-toggle="tooltip" data-placement="top" :title="getHierarchyInfo(rec.districtName, rec.region, rec.divisionName)">
                                  {{rec.branchName}}
                              </td>
                              <td v-if="checkFieldStage('accountNumberWithBranch')" class="selectable" data-toggle="tooltip" data-placement="top" :title="getAccountInfo(rec.dateLastPayment, rec.nextPaymentDueDate, rec.loanType)">
                                  <span data-toggle="modal" data-target="#acctDetailModal" @click="setAccount(rec.accountNumberWithBranch)">
                                      {{rec.accountNumberWithBranch}}
                                  </span>
                              </td>
                              <td class="td-base-lg" style="text-align: left; padding-left: 10px;" v-if="checkFieldStage('name1')">
                                  {{rec.name1}}
                              </td>
                              <td class="" style="text-align: right; padding-right: 10px; text-wrap:none" v-if="checkFieldStage('grossBalance')">
                                  {{formatCurrency(rec.grossBalance)}}
                              </td>
                              <td class="" style="text-align: right; padding-right: 10px; text-wrap:none" v-if="checkFieldStage('rule78')">
                                  {{formatCurrency(rec.rule78)}}
                              </td>
                              <td class="" style="text-align: right; padding-right: 10px; text-wrap:none" v-if="checkFieldStage('netBalance')">
                                  {{formatCurrency(rec.netBalance)}}
                              </td>
                              <td class="" v-if="checkFieldStage('loanType')">
                                  {{rec.loanType}}
                              </td>
                              <td class="" v-if="checkFieldStage('dateLastPayment')">
                                  {{rec.dateLastPayment}}
                              </td>
                              <td class="" v-if="checkFieldStage('nextPaymentDueDate')">
                                  {{rec.nextPaymentDueDate}}
                              </td>
                              <td class="left-justify td-base-lg" v-if="checkFieldStage('Recommendation')" data-toggle="tooltip" data-placement="top" :title="getRecommendationInfo(rec.RecDate, rec.RefreshUpb)">
                                  {{rec.Recommendation}}
                              </td>
                              <td class="left-justify td-base-lg" v-if="checkFieldStage('RecDate')">
                                  {{rec.RecDate}}
                              </td>
                              <td class="left-justify td-base" v-if="checkFieldStage('RefreshUpb')">
                                  {{rec.RefreshUpb}}
                              </td>
                              <td class="td-base" v-if="checkFieldStage('originalStatus')" data-toggle="tooltip" data-placement="top" :title="getPcoChangeStatusData(rec.updateDate, rec.updateComment)">
                                  {{rec.originalStatus}}
                              </td>
  
                              <td class="" v-if="checkFieldStage('monthEndDate')">
                                  {{rec.monthEndDate}}
                              </td>
                              <td class="" v-if="checkFieldStage('brand')">
                                  {{rec.brand}}
                              </td>
                              <td class="" v-if="checkFieldStage('releasedAccountNumber')">
                                  {{rec.releasedAccountNumber}}
                              </td>
                              <td class="" v-if="checkFieldStage('releasedBranch')">
                                  {{rec.releasedBranch}}
                              </td>
                              <td class="" v-if="checkFieldStage('releasedDistrict')">
                                  {{rec.releasedDistrict}}
                              </td>
                              <td class="" v-if="checkFieldStage('releasedRegion')">
                                  {{rec.releasedRegion}}
                              </td>
                              <td class="" v-if="checkFieldStage('releasedDivision')">
                                  {{rec.releasedDivision}}
                              </td>
                          </tr>
                      </tbody>
                  </table>
              </div>
              
              
              
  
              <div class="row">
                  <div class="position-totals">
                      Showing {{startRecordCount}} to {{endRecordCount}} of {{totalRecords}} PCO Accounts
                  </div>
                  <div>
                      <b-pagination size="md" align="right" v-model="currentPage" v-on:change="paginationClickedEventhandler" :total-rows="totalRecords" :per-page="perPage" :hide-ellipsis=false class=""> </b-pagination>
                  </div>
              </div>
          </div>
          
      </div>
      
      <account-detail id="acctDetailModal" :acctdetail="accountinfo"></account-detail>
      <admin-settings id="adminsettingsModal" style="z-index: 1050;"></admin-settings>
  
      
      <div class="modal fade" id="pcoChangeRequestsModal" tabindex="-1" role="dialog" aria-labelledby="pcoChangeRequestsLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header page-titles">
                      <div class="modal-title" style="display: flex; justify-content: space-between; " id="pcoChangeRequestsLabel">
                          <div style="display:flex; justify-content:space-around; ">
                              <font-awesome-icon size="1x" style="color: #053b7a; " icon="medal"></font-awesome-icon>
                              <span style="color: #053b7a; font-size:1em; font-weight:600; ">&nbsp;&nbsp;&nbsp;PCO Change Requests: &nbsp;&nbsp; Acc't No:&nbsp;&nbsp; {{accountinfo.accountNumberWithBranch}}&nbsp;&nbsp; &nbsp;&nbsp; <b></b></span>
                          </div>
                          <div>
                              <button type="button" class="close" data-dismiss="modal" style="" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                      </div>
                  </div>
                  <div class="modal-body">
                      <div class="card-group">
                          <div class="card">
                              <div class="card-block buffer">
                                  <div class="row">
                                      <div class="reg-box">
                                          <label class="">Request PCO Code Change </label>
                                          <select class="mi-form-control mi-cell-default" v-model="PcoCodeRequested">
                                              <option :value="stripPcoCodeFromWord(pcoCode)" v-bind:disabled="authNfi(pcoCode)" v-for="pcoCode in pcoCodeListDe">{{pcoCode}}</option>
                                          </select>
                                      </div>
                                  </div>
                                  <p></p>
                                  <div class="row">
                                      <div class="reg-box">
                                          <label class="">PCO Status </label>
                                          <div class="mi-edit-container" style="display: flex; padding-right: 10px;">
                                              <textarea class="mi-form-control mi-cell-default no-expansion" type="text" style="width:320px;height:200px;" rows="10" v-model="PcoCodeRequestedreason"></textarea>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" @click="cancel()" data-dismiss="modal">Cancel</button>
                      <button type="button" class="btn btn-secondary" @click="saveChangeReq(accountinfo.accountNumberWithBranch)" data-dismiss="modal">Save</button>
                  </div>
              </div>
          </div>
      </div>
      
  </div>
  
  - invalid expression: Unexpected token : in

    click: onClick('Hello', event)

  Raw expression: v-on="click: onClick('Hello', event)"


 @ ./ClientApp/components/resource/resource.vue.html 10:2-192
 @ ./ClientApp/boot.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.ts

**Comment by jschoedt** [comment]
I had the same problem. For me it was forgetting to add the element the app should attach to when it is loaded in the browser. In this case the `<div id="app">`

```
<template>
    <div id="app">
        <router-view/>
    </div>
</template>
```
What confused me was the `mounted()` hook is called even without the  `<div id="app">`.
