### ISSUE TITLE
Click event emitted when pressing return

### ISSUE THREAD

**Issue by dak0rn** [vuejs/vue#5657]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/wng90g4n/1/](https://jsfiddle.net/wng90g4n/1/)

### Steps to reproduce
- Use the example referenced in the JSFiddle.
- Press the `Toggle` button to trigger the desired behaviour.
- Focus the input field and press return

### What is expected?
The input field either submit the form or simply do nothing.

### What is actually happening?
Pressing return in the input field _emits_ a `click` event (as stated by `event.type`) which in turn triggers the `Toggle` button.

---
I have not tried other Vue.js versions.

An extended example shows, that only one button is triggered. See: https://jsfiddle.net/wng90g4n/2/

**Comment by yyx990803** [comment]
This is not Vue related: https://jsfiddle.net/wng90g4n/3/

**Comment by dak0rn** [comment]
@yyx990803 thank you for the investigation.
I have just tested a few other markup variations and it looks like that's actually default behaviour.

Anyway, for the record:
if anyone else runs into this; put an `<input type="submit" />` instead of a button in the `<form>` to submit it.
