### ISSUE TITLE
在处理数据的函数中获取当前渲染的页面元素对象

### ISSUE THREAD

**Issue by chenym1992** [vuejs/vue#5658]
### What problem does this feature solve?
如：
<span class="sp-6" 
    :class="formatClass3(formatItems(item3.items))">
    {{judgeErr(item3.items)?formatItems(item3.items):''}}
</span> 
我需要通过函数处理的数据来判断有多少个字，根据字数，以及当前span的宽度，会给不同的class,但是我现在遇到问题了，我如何获取这个页面元素对象；我不知道怎么做，但是我确实有这个需求

### What does the proposed API look like?
function(target,data)
target 是渲染的元素对象，data是传递的数据

**Comment by chenym1992** [comment]
```
<span class="sp-6" 
    :class="formatClass3(formatItems(item3.items))">
    {{judgeErr(item3.items)?formatItems(item3.items):''}}
</span> 
```

**Comment by xujiongbo** [comment]
computed + ref 应该能解决你的问题

**Comment by chenym1992** [comment]
@xujiongbo  我同时需要传递数据

**Comment by posva** [comment]
If you need to pass data you can use a method or create a new component with props
Next time, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. You can ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
Thanks!
