### ISSUE TITLE
Strange variable or v-show behaviour within <transition-group> with component and vue-resource involved

### ISSUE THREAD

**Issue by ipa1981** [vuejs/vue#5661]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/33225/](https://jsfiddle.net/50wL7mdz/33225/)

### Steps to reproduce
Run JSfiddle several times.

There are two `<child>` components in source, displaying same content after http call done asynchronously.
One component is wrapped within `<transition-group>`, while other is not. 

### What is expected?
Both `<child>` components to display "I'm visible" when loaded.

### What is actually happening?
First component version within `<transition-group>` shows randomly.
`<div v-show="!loading1" key="content">` with `loading1 = false` still produces `style="display:none"` on element

---
It's strange, but it's happens only with conjunction of vue-resource, and styles in `<transition-group>`
In other cases everything works well

**Comment by posva** [comment]
Make sure to use **different** `key` attrs for the components, though. Your problem appears when the second child appears before the first one

**Comment by ipa1981** [comment]
`key` has nothing to do with it, as second component is not in `<transition-group>`. 

I've updated JSfiddle for your convenince and removed `key` from second component. Problem stays the same.

https://jsfiddle.net/50wL7mdz/33234/

Please reopen the issue.

**Comment by ipa1981** [comment]
For the sake of clarity it doesn't work as expected when only one component wrapped in `<transition-group>` exists on the page.

I've added second one just to illustrate the difference in result

**Comment by yyx990803** [comment]
You should be using `<transition>` instead of `<transition-group>`. The latter does not work with `v-show`.

**Comment by ipa1981** [comment]
@yyx990803 thanks for joining. Didn't know about that. Maybe it should be mentioned in docs. :).

However:
1. It actually works in most (except some rare) cases. Is there any type of race condition happening? For example it works well if I emit from child component on setTimeout(), rather than from http request callback.

2. In real prodution code I used `<transition-group>` because I need to show a loader in a separate div, while I wait the content in child component to load. Then transition should smoothly switch them between. For example:

```
<transition-group name="fade" appear mode="out-in">
  <div v-show="loading1" key="loader">Loading</div>
  <div v-show="!loading1" key="content">
    <child v-on:loaded="loading1 = false"></child>
  </div>
</transition-group>
```

However If I turn this into
```
<transition name="fade" appear mode="out-in">
  <div>
    <div v-show="loading1">Loading</div>
    <div v-show="!loading1">
      <child v-on:loaded="loading1 = false"></child>
    </div>
  </div>
</transition>
```
... transition applies only on top wrapper DIV element but doesn't apply when I need to hide first DIV (loader) and show DIV with child component.

You may see it in another Fiddle:
https://jsfiddle.net/50wL7mdz/33238/

When using `<transition-group>` it works well :).

**Comment by TheDutchCoder** [comment]
It would probably be better to approach this problem in a different way.

If you want to show a loader in place of where a component is still loading some data, I would recommend using a directive on the component that attaches a loader on a certain condition (i.e. `v-loading="myComponentIsLoading"`

Another approach would be to use a dynamic `<component :is="someComponent">` approach: https://jsfiddle.net/50wL7mdz/33240/

**Comment by ipa1981** [comment]
@TheDutchCoder:
Dynamic component approach doesn't work as child component which tells parent about it has loaded data _must_ be mounted to start loading data. Thus I use v-show, not v-if.

I didn't get the idea about custom directive. Could you elaborate?

**Comment by ipa1981** [comment]
Ok guys, we still didn't find no working answer, but issue is closed. 

Let me summarize once again.

I try to make a DRY solution to use different components in `<route-view>` and show spinner/loader within transition during component switch and some initialization.

What was tried: 

**First:**
```
<transition-group name="fade" appear mode="out-in">
  <div v-show="loading1" key="loader">Loading</div>
  <div v-show="!loading1" key="content">
    <child v-on:loaded="loading1 = false"></child>
  </div>
</transition-group>
```
**The problem:** transition applies only on top wrapper DIV element but doesn't apply when I need to hide first DIV (loader) and show DIV with child component.

**Second:** 
```
<transition-group name="fade" appear mode="out-in">
  <div v-show="loading1" key="loader">Loading</div>
  <div v-show="!loading1" key="content">
    <child v-on:loaded="loading1 = false"></child>
  </div>
</transition-group>
```
**The problem:** Both blocks get `display: none` randomly at the same time so both blocks ar not shown

**Third:** 
```
  <div v-show="loading1" key="loader">Loading</div>
  <div v-show="!loading1">
    <child v-on:loaded="loading1 = false"></child>
  </div>
```
**The problem:** No smooth transition. I'd like to switch blocks smoothly.

**Fourth:**
Same as above, but move loader inside component.

**The problem:** 1. Not DRY. 2. when component switches, the loader switches as well and thus the visually twitches.

The nearest solution to what is needed is **Second:**. But random `display: none` when it must be shown is unexpected, thus I reported it as a bug.

So how to achieve needed result with Vue 2 guys? :)

**Comment by Heleninsa** [comment]
To solve this, use v-if instead of v-show.<br/>
Also, to avoid warning, you cannot use v-if="condition" v-else,<br/>
Instead, use v-if="condition" v-if="!condition".<br/>
This works for me, I hope this will be helpful to you

**Comment by ipa1981** [comment]
@Heleninsa unfortunately `v-if` doesn't allow a component inside it to initialize. So you cannot track if it's loaded or not. It was mentioned somewhere in previous comments.
