### ISSUE TITLE
Inject <style> properties when rendering.

### ISSUE THREAD

**Issue by hernandev** [vuejs/vue#5662]
### What problem does this feature solve?
When using styles inside vuejs components, other porperties, like `media="print|screen"` are not automatically injected.

When you define inside a vue component, something like:

```html
<style media="screen">
 // some style here
</style>
```
The resulting injected style, will not contain any defined properties.

```html
<style>
<!-- injected style does not contains the properties defined on the component. -->
</style>
```

### What does the proposed API look like?
No API change. just different injected `<style>` tags.

**Comment by posva** [comment]
Please, open the issue in the vue-loader repository: https://github.com/vuejs/vue-loader/

**Comment by hernandev** [comment]
Migrated to vuejs/vue-loader#810

**Comment by hernandev** [comment]
Thanks @posva
