### ISSUE TITLE
Fails on iOS 9 webkit browsers by function isNative

### ISSUE THREAD

**Issue by SerikDM** [vuejs/vue#5663]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Run with iOS 9, Safari browser, add vue.js via AMD.
Throwing error from function `isNative`, when run at string 591-593. `Reflect` is `defined`, but `Reflect.ownKeys` is `undefined`.

`var hasSymbol =
  typeof Symbol !== 'undefined' && isNative(Symbol) &&
  typeof Reflect !== 'undefined' && isNative(Reflect.ownKeys);`

Add check for `Reflect.ownKeys` is `defined`, or add check for every variable in `isNative` is `defined` function will help

### What is expected?
Running without errors

### What is actually happening?
Throwing error

**Comment by yyx990803** [comment]
This should have already been fixed in 2.3.3 by this commit: https://github.com/vuejs/vue/commit/9311876c7c0084a65c6ff0d583d2789205fa83ee

Make sure you are actually using the latest version.
