### ISSUE TITLE
comparing values when firing "watch"

### ISSUE THREAD

**Issue by 719media** [vuejs/vue#5664]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/os7r6kay/11/](https://jsfiddle.net/os7r6kay/11/)

### Steps to reproduce
hi

i'm new to vue framework. i've been using it for a week or so. this is using the latest vue, 2.3.

I came about this problem when starting from https://vuejs.org/v2/examples/select2.html, and trying to implement "multiple" support.

I then removed select2 from the equation to simplify the "bug".

See the normal/simple select in the following:
https://jsfiddle.net/f4a8fdju/3/
It works as expected and everything is fine

See the following multiple select example:
https://jsfiddle.net/os7r6kay/11/

I have placed a counter to prevent the browser from hitting a javascript lock. If you uncomment the "return" in the change function, it will work because it breaks the infinite recursion. Alternatively, another solution is to uncomment the JSON stringify compares.

I am sure there is a lot more at play here that I am not aware of, being a vue noob. I suspect the issue here is that the watch event is only firing if the value changes. And when the value is an array, if you do ['hello'] == ['hello'], the result will be false, so it's hitting endless recursion between the change event firing and the value watcher.

If this is indeed the case, I don't know enough about vue to know if that, perhaps, the watch should perhaps make use of JSON.stringify() or something to compare the values when using the watch? Perhaps doing this would break other things?

I understand that the endless recursion is the fault of the script, in that it's firing change and then the watch is picking it up. My thought is that perhaps watch should be able to handle arrays (and maybe objects?) and not fire when they match.

Have mercy on me,

A vue noob

### What is expected?
endless recursion would not happen

### What is actually happening?
endless recursion

---
i love vue

**Comment by alevans4** [comment]
For what it's worth I [wrote a workaround](http://stackoverflow.com/a/43943641/38065) for this in a StackOverflowquestion today. I'm not sure changing the way properties work for arrays/objects is a viable solution for all cases.

**Comment by 719media** [comment]
Ya, I agree, not sure it's "worth" it either. I just thought it interested that the watch does not fire if the watched variable is "set", but to the same value. Was just curious if someone with more vue experience thought that perhaps the watch should use a more loose comparison for arrays/objects.

**Comment by victorhazbun** [comment]
Is this a VueJS bug?

**Comment by yyx990803** [comment]
The watcher checks whether it should fire using a strict equal `===` - changing this behavior would be breaking and unlikely to happen.

IMO it's the component's responsibility to avoid this infinite loop - also I think the more appropriate place to check shallow equality is inside your watcher callback.
