### ISSUE TITLE
check android

### ISSUE THREAD

**Issue by daheige** [vuejs/vue#5666]
### Version
2.3.0

### Reproduction link
[https://github.com/daheige/vue/blob/master/dist/js/vue.js](https://github.com/daheige/vue/blob/master/dist/js/vue.js)

### Steps to reproduce
 var isIE9 = UA && UA.indexOf('msie 9.0') > -1; //查找到该字符串就可以
var isEdge = UA && UA.indexOf('edge/') > -1;
// var isAndroid = UA && UA.indexOf('android') > 0;
var isAndroid = UA && UA.indexOf('android') > -1 || UA.indexOf('linux') > -1; //android终端或者uc浏览器

### What is expected?
i would you can fixed this bug in vue.js

### What is actually happening?
this check android error will make it work error in android.

**Comment by yyx990803** [comment]
That's not a reproduction, please try to properly explain what the bug is.

**Comment by daheige** [comment]
please make it to fixed android checking:
var isAndroid = UA && UA.indexOf('android') > -1 || UA.indexOf('linux') > -1;// it will check android cli and uc brower.

**Comment by yyx990803** [comment]
This is not enough information. What is the UC UserAgent string you are getting? What versions of UC browser you are using? What eventual bug is this check leading to? Reporting a bug is not just saying "fix this", you need to provide context.

**Comment by daheige** [comment]
hello,sorry,please listen me to explain this bug.
Vue.js 2.3.0 version vue.js file, 544 lines around the location of the place, there is a judge android detection, I think this place has a bug. Because we found in the production environment, in the uc browser, user-agent for JUC (Linux; U; 2.3.7; zh200; zhw cn; 320 * 480) UCWEB7.9.3.103 / 139/999, with this var isAndroid = UA && UA.indexOf ('android')> 0; and can not really detect that the user is using the device.
So, I read the code you wrote vue.js, I suggest using the following way to fix the bug in this place, please use this "var isAndroid = UA && UA.indexOf ('android')> -1 || UA .indexuf ('linux')> -1; "to detect, thank you!



1114789385@qq.com
 
From: Evan You
Date: 2017-05-13 14:12
To: vuejs/vue
CC: daheige; Author
Subject: Re: [vuejs/vue] check android (#5666)
This is not enough information. What is the UC UserAgent string you are getting? What versions of UC browser you are using? What eventual bug is this check leading to? Reporting a bug is not just saying "fix this", you need to provide context.

**Comment by yyx990803** [comment]
Your proposed fix would lead all Linux browsers to also be detected as Android. I don't think that's an appropriate fix.

The UC version you are using seem to be very old (7.9 vs latest 11.x) - it may also have to do with the device / Android OS you are using.
