### ISSUE TITLE
Tree component bug

### ISSUE THREAD

**Issue by superchangme** [vuejs/vue#5671]
I write a tree component,in it,i refer child component which required by itself.
![image](https://cloud.githubusercontent.com/assets/7008154/26042048/95af3914-3964-11e7-941e-8531906379da.png)
Vue warn :Failed to mount component: template or render function not defined.

Can't i use its own component in its tempalte?

**Comment by xujiongbo** [comment]
Did you provide your component with a ```name``` option ?

**Comment by K-walker** [comment]
在路由文件中，导入组件时不要使用  `const Comp =  import("./comp.vue")`  这样的方式导入组件
正确方式应该是这样：  `import Comp from './comp.vue'`  ，如果使用第一种方式，就会报错。
