### ISSUE TITLE
Computed value unable to track value dependency for dynamic object

### ISSUE THREAD

**Issue by viztor** [vuejs/vue#5672]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/33645/](https://jsfiddle.net/50wL7mdz/33645/)

### Steps to reproduce
1.click submit

2.expect value to change based on the change of object

3.yet you only see the change after you go back and change the value of input1.

4. nothing happened to the computed value who utilize the same dynamic size object.

### What is expected?
computed property changes based on the change of the object.

### What is actually happening?
the dependency tracking isn't working if we use other object methods.

---
if a dynamic object is not to be supported in this context, it should throw out an error.
As I spend few hours struggling with this bug, I expect few other folks to have similar problems as well, throw an error simply saves time.
and also, such behavior is kind of inconsistent. as the computed value that simply returns the same thing would respond to such change and a computed value that does not some actual computation doesn't.

I ran into this bug cause I'm trying to create a dynamic table view where the data is a dynamic list, and the user can add data to the list.

**Comment by posva** [comment]
This is a reactivity caveat, you need to use `Vue.set`: https://jsfiddle.net/posva/g2a9n5ob/

**Comment by viztor** [comment]
@posva do you think it would be fair to throw out a warning or error in this case?

**Comment by posva** [comment]
it's not detectable, search detection caveat on the docs, you'll understand 🙂
