### ISSUE TITLE
v-bind:class erase manually added classes

### ISSUE THREAD

**Issue by frlinw** [vuejs/vue#5677]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/33751/](https://jsfiddle.net/50wL7mdz/33751/)

### Steps to reproduce
Add a class with jquery on a tag with class toggled by v-bind:class

### What is expected?
the class added with jquery should remain when :class toggle a class

### What is actually happening?
the class added with jquery is deleted when :class toggle a class

**Comment by timster** [comment]
Try putting it in the `created()` function instead of `mounted()`.

**Comment by LinusBorg** [comment]
This is expected behavour. Vue's virtual DOM doesn't know what changes you applied to the DOM with jQuery or similar tools, so it will always be overwritten and removed whenever the component re-renders.
