### ISSUE TITLE
build.js

### ISSUE THREAD

**Issue by fsw0422** [vuejs/vue#5679]
### What problem does this feature solve?
so when you bootstrap Vue, it comes with all these dependency packages and devDependency packages in package.json. I'm currently dockerizing Vue, but only want to copy dependency packages to the container cuz everytime i build the container, it has to pull all the devDependencis as well, which is absurdly time consuming. I thing the build.js should not depend on any devDependency packages or else, abstracted by another build wrapper, so that the devs can set the NODE_ENV to production mode and npm install it. Angular2 does this with ng build and I think Vue should be able to do this as well for clean build support

### What does the proposed API look like?
no API is necessary

**Comment by posva** [comment]
devDependencies are for development and build.js is a development script. If you need a custom set of packages installed to have a custom build of Vue that fit your specific use case, you'll have to find a workaround.

can you explain what is the problem here? If you dockerize a Vue app, it won't install any devdep

**Comment by fsw0422** [comment]
```
require('./check-versions')()

process.env.NODE_ENV = 'production'

var ora = require('ora')
var rm = require('rimraf')
var path = require('path')
var chalk = require('chalk')
var webpack = require('webpack')
var config = require('../config')
var webpackConfig = require('./webpack.prod.conf')

var spinner = ora('building for production...')
spinner.start()

rm(path.join(config.build.assetsRoot, config.build.assetsSubDirectory), err => {
  if (err) throw err
  webpack(webpackConfig, function (err, stats) {
    spinner.stop()
    if (err) throw err
    process.stdout.write(stats.toString({
      colors: true,
      modules: false,
      children: false,
      chunks: false,
      chunkModules: false
    }) + '\n\n')

    console.log(chalk.cyan('  Build complete.\n'))
    console.log(chalk.yellow(
      '  Tip: built files are meant to be served over an HTTP server.\n' +
      '  Opening index.html over file:// won\'t work.\n'
    ))
  })
})
```
so this is the build.js that vue-cli has tossed me since I've bootstrapped. This script spits out the dist folder in production mode so I was thinking all the dependency resolve and build has to happen inside the node docker container.
```
# Create image based on the official Node 6 image from dockerhub
FROM node:6

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Get all the code needed to run the app
COPY . /usr/src/app

# Install all dependencies
RUN npm install
RUN npm run build

# Set Environmental Variables
# TODO: this was pulled down here due to npm install --all rather than npm install --production by default resulting in pulling in all the dev dependencies as well
ENV NODE_ENV production

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD ["npm", "start"]
```

here's my code for the Dockerfile
`{
  "name": "admin-vue2",
  "version": "2.0.0",
  "repo": "registry.amongstudy.com/sokin/amongstudy",
  "private": true,
  "scripts": {
    "publishLocal": "node build/publishLocal.js",
    "publish": "node build/publish.js",
    "start": "node build/prod-server.js",
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "test": "npm run unit && npm run e2e",
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "node test/e2e/runner.js"
  },
  "dependencies": {
    "express": "^4.14.1",
    "vue": "^2.3.2",
    "vue-resource": "^1.3.1",
    "vue-router": "^2.5.3",
    "vue-simplemde": "^0.3.8"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-istanbul": "^4.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chai": "^3.5.0",
    "chalk": "^1.1.3",
    "chromedriver": "^2.27.2",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^4.0.0",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "inject-loader": "^3.0.0",
    "json-server": "^0.10.0",
    "karma": "^1.4.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-phantomjs-shim": "^1.4.0",
    "karma-sinon-chai": "^1.3.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.30",
    "karma-webpack": "^2.0.2",
    "lolex": "^1.5.2",
    "mocha": "^3.2.0",
    "nightwatch": "^0.9.12",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.2.0",
    "phantomjs-prebuilt": "^2.1.14",
    "rimraf": "^2.6.0",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.7",
    "sinon": "^2.1.0",
    "sinon-chai": "^2.8.0",
    "url-loader": "^0.5.8",
    "uuid": "^3.0.1",
    "vue-loader": "^11.3.4",
    "vue-style-loader": "^2.0.5",
    "vue-template-compiler": "^2.2.6",
    "webpack": "^2.3.3",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}`

here's my package.json

**Comment by posva** [comment]
you're not explaining the problem... why don't you install the vue package?

**Comment by viztor** [comment]
maybe you want to use integrated CI for that?

**Comment by fsw0422** [comment]
@posva to make it concise,

- I want to make all my builds happen inside the docker container (building outside the container and copying makes reuse of modules, but sometime it clogs up with other packages that hasn't been cleaned up) 
- if build script does not depend on the devdep packages, it will cleanly build with only dependency packages, (which is also fast cuz there's much fewer packages)
- anyways it depends on it so I still have to pull in all the devdeps in order to build whilst packaging it in a container

@viztor u mean by building outside the container and copying it in?

**Comment by LinusBorg** [comment]
@posva He is not talking about building Vue - he's talking about building his app in a docker container.
@fsw0422 this question has nothing to do with Vue, and hardly anything with the webpack template (which you might have used and changed quite a bit?). Your question is essentially about how to optimize a webpack build with the minimum of packages installed. 

This repository is not the place for such a conversation.

If you have a suggestion about how to improve our webpack template, please open an issue there (www.github.com/vuejs-templates/webpack).

**Comment by fsw0422** [comment]
@LinusBorg  I acknowledge the fact that my issue has not been derived from Vue directly, although the whole build.js was built automatically out of vue-cli so I issued it here. I made this issue in terms of the previous framework I used (AngularJS) and they had an implicit cli build tool that abstracts and packages all the dependencies the build tool needs in one shot. (probably they use webpack as well and they included the whole package in dep (not devdep) Anyways thanks for the regards
