### ISSUE TITLE
Props are escaped in single file components.

### ISSUE THREAD

**Issue by sant123** [vuejs/vue#5680]
### Version
2.2.2

### Reproduction link
[https://github.com/jihonghai/vuejs-uib-pagination-issue](https://github.com/jihonghai/vuejs-uib-pagination-issue)

### Steps to reproduce
Follow the instructions of the repo :)

### What is expected?
Not escape characters on props inside single file components.

### What is actually happening?
At single file components &lsaquo; is been escaped.

---
Here you'll find the character &lsaquo; is not being escaped. https://plnkr.co/edit/hcfYWCTaQ7GnlO7AitGM?p=preview 

However when using single file components is immediately escaped, thus the visualization is not correct.

You can track the origin of the issue at https://github.com/sant123/vuejs-uib-pagination/issues/1

Thank you!

**Comment by lonelyclick** [comment]
I think you should use `v-html="getText('first')"` instead of `{{ getText('first') }}`

@sant123

**Comment by LinusBorg** [comment]
Please provide better steps for the reproduction - what component in your repository is affected?

**Comment by posva** [comment]
Also, please remove the vuejs-uib-pagination lib to make the repro easier

**Comment by sant123** [comment]
Thank you @lonelyclick 

@LinusBorg they are simple, really! The visualization of previous and next labels are affected because &amp;lsaquo; and &amp;rsaquo; are been escaped. 
@posva you can create a single tag with an attribute inside the template with the value above.

**Comment by sant123** [comment]
Please take a look at 'src/pages/Dashboard.vue' in the reproduction link. 

``` html
<template>
<section class="wrapper">
   <span data-some="&lsaquo;"></span> <!-- Here the attribute is been escaped. -->
   <uib-pagination  @change="fetch()" :boundary-links="true" :total-items="totalItems" v-model="pagination" class="pagination-sm" 
                         previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" :max-size="5" :rotate="true" :force-ellipses="true"></uib-pagination>
  </section>
</template>
```
![dc4564fe-39c1-11e7-9543-b41b0d7fb513](https://cloud.githubusercontent.com/assets/7959437/26106473/a1ac0948-3a0b-11e7-9810-6dbdf7c340ad.jpeg)

**Comment by posva** [comment]
please, take the time to create a proper repro

**Comment by sant123** [comment]
Thank you for your patience @posva :smile: I expect this helps....

https://github.com/sant123/testcase-vue-template

test1.html

![image](https://cloud.githubusercontent.com/assets/7959437/26139678/08ce7c64-3a98-11e7-99ab-95a94adbaf17.png)

test2.html

![image](https://cloud.githubusercontent.com/assets/7959437/26139689/185e16c6-3a98-11e7-9531-dad7a2281f81.png)

As you can see in App.vue the symbol at `data-some`  is been escaped.

**Comment by posva** [comment]
That's because you escaped it in App.vue. I tested using `data-some="›"` and it works nicely
