### ISSUE TITLE
Methods and filters are called many times and cause a performance issue

### ISSUE THREAD

**Issue by DeShadow** [vuejs/vue#5682]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/m1oq0xa8/1/](https://jsfiddle.net/m1oq0xa8/1/)

### Steps to reproduce
Yesterday I tested my Vue chat application and found, that when I typing new message my app is not very fast. And I found that the problem is filters.

With every message I show the date. And I use my filter with moment.js. But the filters are recalculate their values many-many times. Every my keydown event cause recalculating ALL filtered values (more than 250 values took about 70ms). These values are not depend on v-model value of input variable, but they are recalculating again and again.

You can view https://jsfiddle.net/m1oq0xa8/1/ and see in console many lines about recalculating.

In Vue 1.* method values and filters weren't recalculated until their dependencies have been changed. But in Vue 2.* they are recalculating for any event, for every typing in any input field. And this behaviour is similar to Angular 1.* dirty checking. It hasn't good performance. 

I know that you can say that Vue has computed values and I can use them. But I have many lists and I don't want create separate component with one computed property for each list item, because it causes overhead and very verbose for displaying simple list. 

### What is expected?
The filtered values and `{{ method(value) }}` are recalculated ONLY if their dependencies were changed.

### What is actually happening?
The filtered values and `{{ method(value) }}` are recalculated on EVERY changing in component even if the changed variable hasn't influence to these values.

**Comment by Nirazul** [comment]
I only see console output when I change the value. What browser are you using?

**Comment by DeShadow** [comment]
@Nirazul I use last version of Chrome on OSX Sierra.

You can see that input field has variable `a`.
But filtered values use variable `b`, not `a`! That's why input field not logically influences to filtered values. But they are recalculated every time when I changed variable `a`. It's very strange for me.

**Comment by posva** [comment]
The dom gets updated by Vue and therefore the methods get applied again. The filter is doing the same but I'm not sure if that's expected or not. You can use a computed property if you need caching

**Comment by DeShadow** [comment]
@posva I looked in generated render function and saw that filter function called every time when function `render` of component is called.

The behaviour of Vue 1.* was the different. And it had more performance, because you didn't need to create computed property for every transformation of value. This transform function called only when dependent values were changed. Now it's called for every rendering. If I have list with many elements it's very slow. And new behaviour is very similar to dirty checking... And it's sad.

**Comment by xujiongbo** [comment]
IMO this is expected, the change of ```a``` will lead to vm to call its render function which will invoke myFilter and myMethod. 
This can be improved if we keep a dependencies relation list between each vnode and the states they depend on.

**Comment by xujiongbo** [comment]
You can wrap elements that using ```b``` into a vue component a avoid this.

**Comment by DeShadow** [comment]
@xujiongbo Of course. I can created child component in this case. Or in case of list I need to created new component for every list item. Sometimes it's very verbose. 

But in fact I think that filters are become about useless with this behaviour. Because it's expected that they are also reactive. But it's not. That's why computed properties are much better when I need application with great performance. But creating new component for every small list item with only one `<div>{{ computedValue }}</div>` is a big overhead too.

**Comment by DeShadow** [comment]
Also the problem that for every property I need to created all computed properties with transformed data.

For example, I have property `date` of type Date in JS. I want display it in two places with different formats with moment.js. In fact to have good performance I have to created two new computed properties `dateFormat1` and `dateFormat2`. And it's looked a bit verbose too. Because it's looked like view layer,  but not model layer. But I had to move it to model due to performance issues.

**Comment by gebilaoxiong** [comment]
Well,  2.0 is different from 1.0 is `Virtual DOM`

### When the data was changed, how do we update the DOM element ?

#### In Vue `1.x` 
Because the directives( `{{}}` is `v-text` ) is associated with the DOM, We only need to calculate `filter` once

#### in Vue `2.0` 
We need to regenerate the new `Virtual DOM` tree. And then compare it to what is different from the old one. This process needs to recalculate all the expressions. 

If the value does not change, Vue is not going to modify dom

you can use `computed property`

**Comment by yyx990803** [comment]
First, this is expected behavior. In 2.x a component's entire render function is called when it is updated.

Second, the perf problem really is in `moment.js` rather than Vue... taking 70ms for calculating 250 dates is just... not good. Maybe you should try memoizing the calculation in your filters or use a faster alternative.

Third, having 250 values in the same component doesn't sound like a good idea, maybe consider splitting your component into smaller ones (which splits up the updates as well, so should result in better perf).

**Comment by gebilaoxiong** [comment]
Well, the boss is right.

**Comment by DeShadow** [comment]
@gebilaoxiong @yyx990803 
OK, I understand your position. 
250 values - it's a list with 250 items (chat with 250 loaded messages). Every message has date. That's why I need to show it.

> In fact, your request is very simple, you want to filter has the ability to cache the result. just like computed property

Absolutely right. Because I think it has performance improvements and logically right. But if you don't agree... OK

**Comment by adamvleggett** [comment]
I know this has been closed, but I would like to chime in here anyway. I think a lot of developers are under the impression that filter results are cached, making them a sometimes more convenient alternative to computed properties. This even seems to be implied in the accepted answer to https://stackoverflow.com/questions/47940007/what-is-the-difference-between-filters-and-methods-in-vue-js . It would legitimately make Vue a better framework if this were actually true.
