### ISSUE TITLE
Vue Introduction page error

### ISSUE THREAD

**Issue by MZOG** [vuejs/vue#5684]
### Version
2.3.3

### Reproduction link
[https://vuejs.org/v2/guide/#Conditionals-and-Loops](https://vuejs.org/v2/guide/#Conditionals-and-Loops)

### Steps to reproduce
Currently code on website looks like this:
```
<div id="app-3">
  <p v-if="seen">Now you see mep>
div>
```

There is missing **</** before p> and **</** before closing div.

### What is expected?
Add **</** to the example code

### What is actually happening?
I just noticed the error. I think everyone notice and this is not a big bug but yea if someone just started learning html then he'll be confused what happen or if someone just copy and paste code.

**Comment by ericmdantas** [comment]
Maybe report it here https://github.com/vuejs/vuejs.org/issues?

**Comment by posva** [comment]
it looks fine so it may have been fixed in the meantime. For this kind of problems, it's better to directly send a PR to the vuejs.org repo 🙁
