### ISSUE TITLE
Aggregate function in filters

### ISSUE THREAD

**Issue by paul-hammant** [vuejs/vue#5685]
### What problem does this feature solve?
Delivers sum, min, max, count, average to filters.  SQL's Select statement has had aggregate functions 
 them for 30 years. AngularJS sum() and average() from 2009 to 2011 (taken out in v1.0).

From SQL:

sum, count, min, max, average ... and groupBy

See http://paul-hammant.github.io/StoryNavigator/ for an Angular 0.9 usage of sum (and filter to support aggregate functions).
Specifically (in the source):
1. sum('duration') 
2. .$filter(   # this was before the shift to the pipe char in angular for filters.

### What does the proposed API look like?
{{ users | filterBy searchText | count }}

or a pivot:

<tr v-for="user in users | groupBy user.countryOfBirth | select user.countryOfBirth, average(user.age) as aveAge "><td>{{countryOfBirth}}</td><td>{{aveAge }}</td></tr>

**Comment by posva** [comment]
since Vue 2, no default filters are shipped, but you're free to create your own. You can search some too, I found this one: https://github.com/wy-ei/vue-filter 🙂

**Comment by paul-hammant** [comment]
That does indeed look like what I want.  I did google beforehand, but found nothing at all. #GoogleFuFailure
