### ISSUE TITLE
Multiple AJAX calls in component

### ISSUE THREAD

**Issue by Kubitini** [vuejs/vue#5686]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/cycx1s42/](https://jsfiddle.net/cycx1s42/)

### Steps to reproduce
There are two AJAX calls. One is in the parent and the other one is in the child. Both calls are performed on load. The issue is that always works only one.

### What is expected?
To load data from two AJAX calls.

### What is actually happening?
Only one call is performed

**Comment by posva** [comment]
That is not a repro...
You seem to be using a plugin to handle async computed, you may post the issue there or ask on gitter, the forums or stackoverflow
