### ISSUE TITLE
Functional component's context.children[0] wrong in Safari

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue#5687]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/p9cvojqt/](https://jsfiddle.net/p9cvojqt/)

### Steps to reproduce
Run the fiddle in Safari.

### What is expected?
Alerts 'form' twice on all browsers.

### What is actually happening?
Alerts 'input' then 'form' in Safari.

---
The slot is screwing something up in Safari.

**Comment by lonelyclick** [comment]
First of all, if you use the `render` or `template` option, will not appear. This situation will only appear in the html parsing, in Safari, if an element was wrapped by template tag, the results are normal, but if not, the form element will be removed, I do not know why.

```
<div id="app">
  <parent>
    <template scope="props">
      <wrapper id="wrapper1">
        <form><input type="text"></form>
      </wrapper>
    </template>
  </parent>

  <wrapper id="wrapper2">
    <form id="abc" class="abc">
      <input type="text" />
    </form>
  </wrapper>
</div>
```
-> outHTML 

```
<div id=\"app\">
    <parent>
      <template scope=\"props\">
        <wrapper id=\"wrapper1\">
          <form><input type=\"text\"></form>
        </wrapper>
      </template>
    </parent>

    <wrapper id=\"wrapper2\">
        <input type=\"text\">
    </wrapper>
  </div>
```

So I don't think this is a bug, much more like a safari approach.

**Comment by posva** [comment]
As @lonelyclick said, this is related to Safari. I wonder if you are allowed to include a form inside of a custom tag. MDS says: `Permitted parents	Any element that accepts flow content`

This won't happen if you use template strings or `vue` files 🙂
