### ISSUE TITLE
Using a .vue file to generate an Html and CSS file with an input model

### ISSUE THREAD

**Issue by marclave** [vuejs/vue#5689]
### What problem does this feature solve?
A vue component of mine, when applied a certain model generates certain HTML/CSS. Is there any CLI for extracting the output HTML/CSS into seperate entities? Currently I duplicate the Vue file with my own node templating generation.

### What does the proposed API look like?
Some CLI that lets you pass in a model and a Vue component, which outputs the html/css file appropriate to the input model.

**Comment by znck** [comment]
You should create this issue on [vuejs/vue-cli](https://github.com/vuejs/vue-cli).

**Comment by marclave** [comment]
Okay thanks @znck :)
