### ISSUE TITLE
input value too fast that v-model can not handle

### ISSUE THREAD

**Issue by PolarBearAndrew** [vuejs/vue#5693]
### Version
2.3.3

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
1. `<input type='text' v-model='value' >`
2. and use a very fast input to input value `12345678`
3. only get `1357`
the problem happen when I use a barcode scanner

### What is expected?
Let the `v-model` can handle faster input, or the reason why it can't be.

### What is actually happening?
I use `v-model` and `watch` to watch an input box.
The input box is waiting for barcode scanner, but the barcode scanner input text one by one, for example, `abcd` the scanner will input `a`, `b`, `c`, `d` one by one.
I have two scanners, one is old, another is brand new. The old one is find, just slow. The new one input characters very very fast, that `v-model` can't handle, input will become `a`, `c`.
I resolve this problem by use a `setInterval` to refresh the value by myself, replace the `v-model`.
I think the problem come from the browser (Chrom 58)?
Or is there any information I should know, but I miss it.

---
thanks a lot :"D

**Comment by rayrutjes** [comment]
You can use `this.$nextTick(function() {});`

**Comment by sirlancelot** [comment]
Your reproduction link is just a link to the Vue.js repository.

**Comment by posva** [comment]
Sorry, but we'll need a repro for that if you can somehow simulate it in a reasonable way. Feel free to open a new issue when you have it 🙂

**Comment by gothe92** [comment]
hi, i had a same problem what he wrote.

when use barcode reader, the input filled too fast and some char skipped.
(229934456 ->  2934456)

    Vue.directive('initvalue', {
        inserted: function(el, binding) {
            el.value = binding.value;
        }
    });

this directive helped me.

<input type="text" v-model="barcode" />

than:

<input type="text" v-initvalue="barcode" v-on:keyup="barcode = $event.target.value">

it's ugly but work, in this case.

**Comment by posva** [comment]
@gothe92 maybe `v-model.lazy` can help

**Comment by sirlancelot** [comment]
@gothe92 Why are you doing that and not just using `v-model`?  Simply replace those `v-initvalue` & `v-on` directives with a single `v-model="barcode"` and Vue will do the rest.

**Comment by gothe92** [comment]
it's problem for us only in Opera 12.16 (but what i said, our customers use this browser)
v-model  is just syntactic sugar for: `v-bind:value="x" v-on:input="x = $event.target.value"`
v-model.lazy is `v-bind:value="x" v-on:change="x = $event.target.value"`

i try found the exact problem

**Comment by nesterone** [comment]
Just checked on Opera 47.0 works without problems

**Comment by vupu83** [comment]
Using v-model.lazy resolved my problem (IE 11)
