### ISSUE TITLE
a list of components,when delete one of them,it always delete the last one

### ISSUE THREAD

**Issue by KodachiGitHub** [vuejs/vue#5699]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/Kodachi/50wL7mdz/34395/](https://jsfiddle.net/Kodachi/50wL7mdz/34395/)

### Steps to reproduce
click the input to delete it

### What is expected?
the one i clicked should be delete

### What is actually happening?
the last input was deleted

**Comment by yyx990803** [comment]
https://vuejs.org/v2/guide/list.html#key
