### ISSUE TITLE
Android 怎么调vue里面的方法(how android call vue methods)

### ISSUE THREAD

**Issue by iceuncle** [vuejs/vue#5700]
我在android使用 mWebView.loadUrl("javascript:hello()")，为什么调不了vue里面的hello方法呢，传统的webview和js的交互就是这么写的啊？

I use mWebView.loadUrl("javascript:hello()") in android ,but has no effect.

**Comment by yuxingfafu** [comment]
@iceuncle 哥们，你的问题解决了没有呀？

**Comment by yuxingfafu** [comment]
@vue-issue-bot 看了下，挺多人遇到Z换个问题呢？是否已经解决的了？

**Comment by yuxingfafu** [comment]
created里面添加
window.functionName=this.functionName;
就可以了，公司的一个同事解决了这个问题。

**Comment by t894924815** [comment]
@yuxingfafu it should be 
window['functionName']=this.functionName
