### ISSUE TITLE
Transition group event hooks

### ISSUE THREAD

**Issue by alexsasharegan** [vuejs/vue#5701]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/vtoy09cy/2/](https://jsfiddle.net/vtoy09cy/2/)

### Steps to reproduce
Create a transition-group with two or more uniquely keyed transition elements. Attach event listeners to transition hooks and log out the number of times that hook is called. Will equal the number of transition elements.

### What is expected?
Each transition element should fire their respective event hooks internally, but the group should emit the event hooks once each transition element has fired that hook. I expect the group to aggregate these events.

### What is actually happening?
When using the transition-group component, each uniquely keyed transition element will fire all the transition event hooks discretely rather than in a group. 

---
Is this the desired functionality? A technical limitation?

**Comment by yyx990803** [comment]
This is intended behavior. If the hook is used to manipulate the DOM elements then it has to be called for every single item respectively.

**Comment by alexsasharegan** [comment]
Thanks for the response! Any best practice tips for managing the events as an aggregate? A good ol' counter system is all I got, but I don't love the idea of manually syncing the number of transition elements with my counter logic.

**Comment by alexsasharegan** [comment]
Perhaps using namespaced keys and filtering through `vm.$children` and checking for a match with the `vm.$vnode.key`? Although you can have regular HTML elements as children, so that would have to be checked as well.
