### ISSUE TITLE
lifecycle hook.  can't get the new content of the dom after updating variables

### ISSUE THREAD

**Issue by newbie78** [vuejs/vue#5706]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/oxx514Lb/2/](https://jsfiddle.net/oxx514Lb/2/)

### Steps to reproduce
how can I get resultX after answering the last question? Not after clicking on the Again button.

### What is expected?
see "result" in the console after answering the last question

### What is actually happening?
see "5" in the console after answering the last question

---
https://forum.vuejs.org/t/lifecycle-updated-and-watch/11068
I created a topic on the forum but nobody answered yet.

**Comment by LinusBorg** [comment]
I don't understand your description of the problem.

What makes you think this is a bug?

**Comment by simplesmiler** [comment]
@newbie78, as @LinusBorg pointed out, that's due to transitions, the original element is still in the DOM, being animated out.
But anyway you should not query the DOM for the result. Instead this logic should be in a computed property: https://jsfiddle.net/oxx514Lb/3/
