### ISSUE TITLE
How to bind not bool arrtibute in list?

### ISSUE THREAD

**Issue by yunhor** [vuejs/vue#5708]
vue 2.0

![2017-05-20 02-56-02](https://cloud.githubusercontent.com/assets/1693437/26263615/16c97ee2-3d0c-11e7-9f56-8f60038107ae.png)

in this list ,some items have  arrtibute "data-wow-delay" and some no,how can I bind "data-wow-delay" ?

**Comment by Naeemo** [comment]
:data-wow-delay="'0.2s'"

**Comment by yunhor** [comment]
I know how to bind those lines with arrtibute "data-wow-delay",I just don't know how to deal with those lines without "ata-wow-delay".
all lines in a list

**Comment by Micaso** [comment]
You can pass it in anyway. 
The element wont care about it, if it get an attribute which it does not need. 
Same is true for components. 
If you do not specify the the prop in props you can not access it even if you pass it throw. 

Hope that helped

**Comment by yunhor** [comment]
Thanks @Micaso
