### ISSUE TITLE
`inject` as a function

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#5710]
### What problem does this feature solve?
It's possible to have [async local component registration](https://vuejs.org/v2/guide/components.html#Async-Components):
```
new Vue({
  // ...
  components: {
    'my-component': () => import('./my-async-component')
  }
})
```

This is very convenient when you have Webpack code splitting, however, when you are using provide/inject with Symbols (or unique hashes), it becomes hard to share the symbol across all components. This is because the Symbol is in a separate file, which is asynchronously loaded via import, and needs to be passed in via `inject`.

### What does the proposed API look like?

**Parent.vue**
```
<script>

const Parent = {

   key: Symbol('Parent'),

   provide() {
      return {
         [Parent.key]: { sharedState: 1 },
      };
   },
};

export default Parent;
</script>
```

**Child.vue**
```
<script>
const Parent = () => import('./Parent.vue');

const Child = {

   components: {
      Parent,
   },

   inject() {
      const Parent = this.components.Parent; // Made up

      return {
         parent: Parent.key,
      };
   },
};

export default Child;
</script>
```

**Comment by posva** [comment]
Why don't you export the Symbol in a separate file, so you can import it in both of your chunks?

**Comment by hirokiosame** [comment]
@posva 

That doesn't solve the problem; you still have to asynchronously load that file.

Actually complicates it more because you won't be able to leverage Vue's "async component" feature to block the declaration of the component till the chunk is loaded because the file is no longer a component.

**Comment by posva** [comment]
no, I meant not asynchronously loading that chunk since it's so small, it's unnecessary. It doesn't change the rest of the code, specially the async component part

**Comment by hirokiosame** [comment]
Perhaps I should have mentioned that both `Parent.vue` and `Child.vue` are entry points.

If you're suggesting that I synchronously load it, the Symbol file will be inlined in both entry points and will create two different symbols.

**Comment by posva** [comment]
oh, that's right, the Symbol will be different 😅 
Although, I should have raised this other point right from the start: why are you trying to async load two components that use inject? I suppose you're creating an app and not a lib. And I wonder if you need to use inject/provide which more targeted towards libs?
IMO if you relate two components the way you do, they should be in the same chunk (app wise)

**Comment by hirokiosame** [comment]
@posva 

I'm making a library :)

**Comment by posva** [comment]
A code split library?
Even though that looks like a bad idea, you should put those components in the same chunk

**Comment by hirokiosame** [comment]
@posva 

The library is modular and has many entry points to accommodate a specific use-case; but this is besides the point of this Feature Request and I won't be going into the details of it.

Normally, this shouldn't be an issue as Webpack has chunking and async loading. The inconvenience is in the fact that Vue has an async components loader but `inject` isn't a function so it's evaluated before the async components are loaded.

Asking to make `inject` take in a function seems like a reasonable feature request that could have other benefits. Thanks for trying to help but I'm not looking for solutions to a problem (at least in this thread) and would like for this Issue to be regarded simply as a feature request.

**Comment by posva** [comment]
Ah, I see, now I get the multiple entry-thing you said earlier 🙂 

> Thanks for trying to help but I'm not looking for solutions to a problem (at least in this thread) and would like for this Issue to be regarded simply as a feature request

It is being regarded as such 😓 
The feature may be convenient but I need to know what problem exists that makes it necessary, so it's pretty normal to ask questions 😄

**Comment by hirokiosame** [comment]
The problem the FR solves was described in the first post. It's understandable and fine to ask questions. I was concerned that the way you kept offering alternative solutions was steering this FR thread off-topic.

**Comment by posva** [comment]
Don't worry, I'm sceptical about my own FR too 😉 I'm usually worse at myself
I'm concerned about how this pattern could impact the usage of inject/provide.
The `Symbol` usage in inject/provide you provided is definitely as good one, the part I'm sceptical is the part referencing the parent from the child, it's basically the same as doing `$parent.something`. Right now, inject cannot access to the component, and it's very static, it limits the behaviour on purpose. Making it a function makes it super flexible and also dangerous

PS: I feel like it really bothers you that I'm asking you questions but I cannot understand why. The use-case may be super clear for you but it's not for me 😄 I'm not doing this to bother you, I'm doing it to make it clearer.

**Comment by hirokiosame** [comment]
@posva 

RE:
> the part I'm sceptical is the part referencing the parent from the child, it's basically the same as doing $parent.something

It's not. `this.$parent` is accessible only in the context of the component instance, hence `this.`. Note that `this.$parent` is referring to the instance of the parent component, **not it's declaration**. What I am doing in that example is closer to `this.$parent.$vnode.componentOptions.Ctor.extendOptions` in the context of the Child instance because that triple-equals to `Parent`, **the declaration**.

This is _safer_ because `Parent` is imported through an explicit dependency, rather than the implicit dependency of `this.$parent...`. This is crucial when the Parent is not an immediate parent to Child; a poor assumption to make.

RE:
> Right now, inject cannot access to the component, and it's very static, it limits the behaviour on purpose. Making it a function makes it super flexible and also dangerous

What's dangerous about that? Literally every method (all lifecycle event handlers, render (non-functional), data, provide, methods.*, computed.*,  etc.) is (or can be) a function that has access to it's own instance, and when it does, it can access `this.$options.components` to retrieve all components the component was declared with (global ones too).

Anyway, putting the `key` in the declaration of the component is not apart of the feature request (it's already something I can do). If it helps you understand the FR better, consider the Symbol to be in a separate file. Like I said before, the reason I put it in the component declaration is purely for convenience: organizational and to leverage Vue's async component feature.

RE:
> PS: I feel like it really bothers you that I'm asking you questions but I cannot understand why. The use-case may be super clear for you but it's not for me 😄 I'm not doing this to bother you, I'm doing it to make it clearer.

You're probably confused because you're overlooking what I wrote:
> It's **understandable and fine to ask questions**. I was concerned that the way you kept **offering alternative solutions** was steering this FR thread off-topic.

To reiterate: it's fine to ask questions.

**Comment by hirokiosame** [comment]
Discovered a work around. Withdrawing FR.
