### ISSUE TITLE
Importing static assets into a Vue Component

### ISSUE THREAD

**Issue by kumarvvr** [vuejs/vue#5713]
I am building a VUE JS based Image viewer which has the following script

    <script>
    import _image from './assets/default.jpg';
        export default {
            name: 'Clickable-Image',
            props:[
                'isSelected',
                'imageSource',
                'imageName',
            ],
            // Component Data.
            data(){
                return {
                    defaultImage:_image,                
                }
            },

            // Component Computed Properties
            computed:{
                // Appearance Computation.
                containerStyle : function(){
                    return{
                        ui:true,
                        raised:true,
                        very:false,
                        padded:true,
                        blue: !this.isSelected,
                        green: this.isSelected,
                        inverted:true,
                        segment:true,
                    }
                },

                // Image to show.
                displayImage(){
                    // This is working if I send the raw image URL
                    //return "http://i.imgur.com/N9yfg3C.jpg";
                    var src = "";
                    if(this.imageSource == "")
                        return this.defaultImage;
                    else
                        return this.imageSource;
                    
                    
                }

            },

            // Component Methods for Event Handling.
            methods:{
                ToggleSelection :  function() {
                    if(this.isSelected)
                        this.isSelected=false;
                    else
                        this.isSelected=true;
                }
            }
        }
    </script>

What I want to do is to show a default image in the component when no image URL is supplied as an input.

However, in the computed function, I am unable to return a default image. When I return a string with an Image URL (as shown in the code comments) the image is being displayed.

Note : when i "return _image" in my computed displayImage() function, the default image is being shown.

Here is my component template.

    <template>
        <div v-on:click="ToggleSelection()">
            <div v-bind:class="containerStyle">
                <div class="ui centered card">
                    <div class="image">
                        <img v-bind:src="displayImage">
                    </div>
                </div>
            </div>
        </div>
    </template>

I am using Vue-Cli with webpack-simple template starter. 

What am I missing here??

[![enter image description here][1]][1]

Project Directory Structure.
  [1]: https://i.stack.imgur.com/kzgqP.png

**Comment by Micaso** [comment]
I think your Problem is the way you import your image. 
Try:
import _image from "file!./asset/default.jpg"

**Comment by VictorMessias** [comment]
Just use ~@, its crazy but its works.
