### ISSUE TITLE
Vue生命周期执行问题

### ISSUE THREAD

**Issue by taolive** [vuejs/vue#5714]
1. 从 A页面 打开B页面，在B页面点击router-link，跳转到C页面，在C页面点击按钮，执行（this.$router.back()), 回到 B页面，B页面触发mounted，点击B页面中的按钮执行

（this.$destroy(); this.$router.back(); 代码） 回到 A页面

2. 从 A页面 打开B页面，在B页面点击router-link，跳转到C页面，在C页面点击按钮，执行（this.$router.back()), 回到 B页面，B页面触发了完整的生命周期钩子

为什么在执行上面步骤后，B页面会触发完整的生命周期？而1不会？

vue相关版本：Vue.js v2.3.3，vue-router v2.5.3，vuex v2.3.0

**Comment by RunningV** [comment]
i meet the same problem ,example is here : [https://jsfiddle.net/RunningV/02txjwj1/](https://jsfiddle.net/RunningV/02txjwj1/),  i print the lifecycle in components ABC, i only destroy component B when B >A, but after that, C>B will run all B's lifecycle, but u can;t see when B was destroyed. and i got `vm.$destroy` is not recommended ues manual, then how can i clear a cached component ?
