### ISSUE TITLE
Boolean attribute `aria-selected` with a true value doesn't render HTML5-conform

### ISSUE THREAD

**Issue by thasmo** [vuejs/vue#5715]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/Thasmo/50wL7mdz/34768/](https://jsfiddle.net/Thasmo/50wL7mdz/34768/)

### Steps to reproduce
Set an `:aria-selected="boolean-value"` attribute on an element.

### What is expected?
I expect it to render as `aria-selected` or `aria-selected="aria-selected"`.

### What is actually happening?
It's rendered as `aria-selected="true"`.

---
If the value is `false` the attribute is removed as expected but when it's `true` it's not rendered correctly. [W3C docs](https://www.w3.org/TR/wai-aria-1.1/#aria-selected)

**Comment by blake-newman** [comment]
https://www.w3.org/TR/wai-aria/states_and_properties#aria-selected

The spec clearly defines the value should be 'true/false/undefined'. If you have other usecase the Boolean value can also be a string.

**Comment by blake-newman** [comment]
https://www.w3.org/TR/wai-aria/states_and_properties#aria-selected

The spec clearly defines the value should be 'true/false/undefined'. If you have other usecase the Boolean value can also be a string.

**Comment by thasmo** [comment]
Ah, indeed. Thanks for pointing it out to me. Thanks for your time!
