### ISSUE TITLE
SSR client plugin should watch template change 

### ISSUE THREAD

**Issue by DiscipleD** [vuejs/vue#5716]
### What problem does this feature solve?
In v2.3.0, vue-server-renderer create a helper, client-plugin, that used to replace the html-webpack-plugin in server render situation. 

However, the new plugin doesn't watch the template file change. If the plugin add this feature, like html-webpack-plugin, that will improve development experience.

### What does the proposed API look like?
Not changes.

**Comment by yyx990803** [comment]
After looking at this - the feature should be implemented outside of `vue-server-renderer` via a userland setup. Here's how it's done in the vue-hn-2.0 demo app: https://github.com/vuejs/vue-hackernews-2.0/commit/27cb2c6f7758176a73c5400620a6478c57bc4dff
