### ISSUE TITLE
Vue too verbose about devtools extension despite config.silent

### ISSUE THREAD

**Issue by tim-janik** [vuejs/vue#5718]
### Version
2.3.3

### Steps to reproduce
Set
  Vue.config.silent = true;                                                                                                                            
Open DevTools in Electron (which doesn't support Chrome extensions).

Vue spams the devtools console with "Download the Vue Devtools extension..." despite needing to be silent.

### What is expected?
Vue.config.silent = true; ought to shut Vue up.

### What is actually happening?
Vue can't be silenced when devtools are used despite any possible reasons for not having vue-devtools.

---
Here's a patch to fix the issue:

	--- vue/dist/vue.common.orig 2017-05-21 17:48:33.757145111  0200
	    vue/dist/vue.common.js   2017-05-21 17:59:42.254510594  0200
	@@ -7578,7  7578,7 @@
	   if (config.devtools) {
	     if (devtools) {
	       devtools.emit('init', Vue$3);
	-    } else if (process.env.NODE_ENV !== 'production' && isChrome) {
	     } else if (process.env.NODE_ENV !== 'production' && isChrome && !config.silent) { // shutup inside electron
	       console[console.info ? 'info' : 'log'](
	         'Download the Vue Devtools extension for a better development experience:\n'  
	         'https://github.com/vuejs/vue-devtools'

**Comment by yyx990803** [comment]
AFAIK Electron does support devtool extensions: https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md

**Comment by joezimjs** [comment]
but is there a way to silence this message?

**Comment by lhermann** [comment]
This did the trick for me:

```
Vue.config.devtools = false;
```
