### ISSUE TITLE
component doesn't  support @blur.native event

### ISSUE THREAD

**Issue by stanleylin** [vuejs/vue#5719]
### What problem does this feature solve?
when i use component like this:<component-name @keyup.native></component-name>, it is works.
but doesn't worked if I use like this:<component-name @blur.native></component-name>.
I need this feature especially using form components.
 example:
     <mt-field label="name"  @blur.native="valiUserName()" placeholder="pls input name" v-model="user.name"></mt-field>
   

### What does the proposed API look like?
<component-name @blur.native></component-name>.

**Comment by coolzjy** [comment]
`@blur.native` works fine: https://codepen.io/cool_zjy/pen/rmQbBy

`<mt-field>` may looks like:
```
<div class="someclass">
  <input type="text">
</div>
```
and `blur` event never bubble, so it won't trigger on outer div.

**Comment by znck** [comment]
Blur event is triggered if the element captures focus e.g. <input>. You can use `tabindex` attribute to make any element focusable.
