### ISSUE TITLE
never used window but error window not defined

### ISSUE THREAD

**Issue by iapYang** [vuejs/vue#5722]
### Version
2.3.3

### Reproduction link
[https://github.com/iapYang/learn-vue-ssr](https://github.com/iapYang/learn-vue-ssr)

### Steps to reproduce
1. npm i
2. npm run server
3. npm run client
4. node ./server.js
5. open localhost:8080

### What is expected?
expected a rendered page

### What is actually happening?
500 Internal error page

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue/issues/5721#issuecomment-303051852
