### ISSUE TITLE
Prepending new DOM elements vs Appending VueJs2

### ISSUE THREAD

**Issue by hyperking** [vuejs/vue#5725]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/uds9cghq/2/](https://jsfiddle.net/uds9cghq/2/)

### Steps to reproduce
Clicking the add Item button in the provided link will insert a new item DOM element to the last position
and not the first.

### What is expected?
List items should be listed from newest to oldest. VueJS should allow user to define how new items are added. Javascript I can either append or prepend new elements.

### What is actually happening?
Not entirely sure what Vuejs2 is doing, but I believe it appends any new DOM element to the stack.

If tried reversing the computed list but that has not effect on the list order when rendered.

I also tried applying a js method within the component to reverse the list
example:
" v-for="(item, index) in list.reverse()" - FAIL
" v-for="(item, index) in reverse(list)" - FAIL
" v-for="(item, index) in computedReversedList" - FAIL

This causes an infinite loop error in vuejs see below error log.

You may have an infinite update loop in a component render function.

---
Reversing the list also messes up the list order completely. Please help or provide best practice to handle this situation.

**Comment by LinusBorg** [comment]
`.reverse()` mutates the oiriginal array, which you don'T want. create a shallow copy before to avoid this:

Also, make sure to use the `key` attribute when rendering lists.

https://jsfiddle.net/Linusborg/uds9cghq/3/
