### ISSUE TITLE
Data _numbers not defined

### ISSUE THREAD

**Issue by Tera3yte** [vuejs/vue#5726]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/35097/](https://jsfiddle.net/50wL7mdz/35097/)

### Steps to reproduce
- Create a variable named _numbers (It happens on every variable named _SOMENAME which is bound via v-model)
- Open console
- Load Page

### What is expected?
The variable should not be undefined

### What is actually happening?
The variable ist not defined

**Comment by sqal** [comment]
https://vuejs.org/v2/api/#data

> Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.
