### ISSUE TITLE
Child component's updated event is unexpected triggered.

### ISSUE THREAD

**Issue by rlsz** [vuejs/vue#5727]
### Version
2.3.3

### Reproduction link
[https://github.com/rlsz/vue-demo-issue-componentUpdated](https://github.com/rlsz/vue-demo-issue-componentUpdated)

### Steps to reproduce
Child component's updated event is unexpected triggered when it has content, not when it's content is changed.

### What is expected?
Child component's updated event is triggered only when it's content is changed.

### What is actually happening?
When parent component is changed, the child component with content will always be updated whether it's content is changed.

**Comment by jkzing** [comment]
It could be an expected behavior.
Vue will force update the component if the it has children.

**Comment by jkzing** [comment]
Not sure why, let's wait core members' answer. 😅

**Comment by rlsz** [comment]
@jkzing
=.=

**Comment by zhoushikui** [comment]
I had a similar problem like that.

**Comment by yyx990803** [comment]
This is expected behavior. When a child component has slot content, the slot content may have changed during the parent's re-render and a force update of the child is necessary.

**Comment by rlsz** [comment]
@yyx990803 
Actually, child component without slot will also be updated.The determinant is what child component look like, which means:
‘<child-component></child-component>' won't be updated when parent changes.
'<child-component>anything</child-component>' will be updated when parent changes, whether child has a slot.
Besides, you sad that the slot content may have changed during the parent's re-render, but it just a possibility, so vue will trigger the child's updated even if it's uncertain that child's content is changed, right?

**Comment by yyx990803** [comment]
@rlsz yes, because to determine whether the content has changed it needs to be diffed, however because that content is part of the child's vdom tree, the only way to diff it is to force the child to update.

**Comment by javoski** [comment]
I think ```<child>anything</child>``` will not make any sense when the child component doesn't have slot content, it's just the same as ```<child></child>.

**Comment by rlsz** [comment]
@yyx990803 
Thanks to point that. But there is better way, i think, to determine whether child's content has changed, such as differ the outerHtml of child's vdom tree.

**Comment by yyx990803** [comment]
@rlsz there is no outerHTML during updates, it's all vdom nodes.

**Comment by rlsz** [comment]
@javoski 
[https://jsfiddle.net/rlsz/06q3ctsp/8/](url)
You can try this.

**Comment by javoski** [comment]
@rlsz 
What I really meant was the content inside ```<child-component>``` tag will not be rendered if the child component was not intend to render any slot content.
It was not related to the topic about updated hooks, but a reply to:
>Actually, child component without slot will also be updated.The determinant is what child component look like, which means:
‘```<child-component></child-component>```' won't be updated when parent changes.
'```<child-component>anything</child-component>```' will be updated when parent changes, whether child has a slot.

**Comment by rlsz** [comment]
@javoski 
= =
What's your suggestion?

**Comment by jkzing** [comment]
@rlsz, the thing is, when a ancestor component changes, without regenerate child's vdom tree and diff with old ones, you can not know whether the child should be updated. So even if the child doesn't need to, it still will be updated. This also happens on vdom implementations like `React`, `React` just always rerender the child component whether it should or not (without `shouldComponentUpdate`).

**Comment by rlsz** [comment]
@jkzing 
That's a imperfection to React, also to Vue, i think.
