### ISSUE TITLE
【Vue 2.3.3】当我在子组件中调用vm.$emit("update:show", false)时，父组件的show属性被未被改变！

### ISSUE THREAD

**Issue by lihaizhong** [vuejs/vue#5729]
## .sync 方式在使用vue.js创建多页时有效，但是使用vue.esm.js时无效

当我在组件内想改变父组件的show属性了，自然而然想到了Vue重新引入的 [.sync](https://cn.vuejs.org/v2/guide/components.html#sync-修饰符)的方式

###  这是父组件中的一段pug代码
> calendar(:show.sync="show", @export="exportDate") 

### 这是子组件的部分代码 
> this.$emit('update:show', false);

然而并没有什么软用。通过[Chrome Devtools](https://github.com/vuejs/vue-devtools)，我检测到了update:show的事件一直被触发。但是show属性一直都没有改变。

### 摒弃这种语法糖后，我直接按照语法糖转化后的写法
> calendar(:show="show", @export="exportDate", @update:show="val => show = val")

最后我通过官方指导的扩展后的写法，发现能实现数据的改变。
在网上查阅了很多资料，发现并没有类似的问题（当然除了在我之前有个英文的提问，讲到了同样的问题）
[https://github.com/vuejs/vue/issues/5727](https://github.com/vuejs/vue/issues/5727)

不知道大家有没有遇到过这类问题，并且知道缘由的。

PS: 我使用[unpkg的vue.js 2.3.3](https://unpkg.com/vue/dist/vue.js) 并没有出现这类问题，代码能正常识别`.sync`的语法糖。

**Comment by hmh9251** [comment]
我也碰到这个问题，不知道如何解决，在更新的2.5的版本里面发现的

**Comment by mingyec** [comment]
same problem, who can resolve it?

**Comment by PLQin** [comment]
> @export="exportDate"

重点是 : `@export="exportDate"` 吗 ?
