### ISSUE TITLE
filterBy no-result

### ISSUE THREAD

**Issue by biquetto** [vuejs/vue#573]
Hi,

I'm just wondering if there is any way to test if a filterBy filter return a 0 length data result ?

**Comment by danielchou** [comment]
Hi yyx990803,
I also need a filterBy feature that could count the filtered objects.
I don't get the above code snip "this.games.filter" where does the ".filter" comes from?

**Comment by Nirazul** [comment]
@danielchou 
It's a native ES5 Array method in Javascript:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by danielchou** [comment]
@Nirazul Thank you. 
Native filter method is so powerful.

**Comment by hotrodfl** [comment]
@Nirazul You can use `filteredGames.length` to get the count.

**Comment by EHackettTriCore** [comment]
It's also worth noting that the examples above are case sensitive so if you search for "ea" vs "Ea" it will mean the difference between accounting for "treat" and "Eastern".

This means searching for ea might cause filteredGames.length to return 0 even though you have a result like "Easteregg Hunt".
