### ISSUE TITLE
<transition> with <keep-alive>: non-component child is not showing.

### ISSUE THREAD

**Issue by DeShadow** [vuejs/vue#5732]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/9f1tyowd/2/](https://jsfiddle.net/9f1tyowd/2/)

### Steps to reproduce
I want to create transition between component and div with my data (non-component). But also I want to cache my component. That's why my code looks like:
```
<transition name="fade" mode="out-in">
    <keep-alive>
        <div v-if="myCondition">Example text</div>
        <my-child-component v-else></my-child-component>
    </keep-alive>
</transition>
```

But this code is not working and there is no warnings or errors from Vue.js. `<div>` not showing, but component showing. The problem only in `<keep-alive>`, without it's working.

Without <keep-alive> (all is right): https://jsfiddle.net/9f1tyowd/1/
With <keep-alive> (`<div>` never showing): https://jsfiddle.net/9f1tyowd/2/

That's why the question: what is wrong?

If only components are allowed in `<keep-alive>`, why there is no warnings or errors? How can I switch between component and non-component in transition with caching of component?

If non-components are allowed, why they are simply ignored and not showing?

### What is expected?
Caching component and showing of `<div>`

### What is actually happening?
`<div>` is not showing.

**Comment by posva** [comment]
Yeah, it only works with components.
I think we could include a warning for non-components

**Comment by DeShadow** [comment]
@posva Okay. Is there any way to make transition between non-component and cached component? I don't want to create new component for non-component.

**Comment by posva** [comment]
Actually, everything can be a component, there is not a _non-component_ element 😅

**Comment by posva** [comment]
Closing this as seen in #5757 : You must use components inside `keep-alive`
