### ISSUE TITLE
Sum and concatenate issue from v2.2.0 onwards

### ISSUE THREAD

**Issue by hamutaro89** [vuejs/vue#5733]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/35243/](https://jsfiddle.net/50wL7mdz/35243/)

### Steps to reproduce
sum of input type="number" became concatenate from v2.2.0 - 2.3.3, it was ok on v2.1.10.

### What is expected?
total of sum

### What is actually happening?
concatenate

**Comment by pengchongfu** [comment]
@hamutaro89 the [commit](https://github.com/vuejs/vue/commit/9d6c8ec268f659a715e3b38c97a1e03964961703) lead to this.
but I think that using modifier `.number` is a better way.

**Comment by javoski** [comment]
This is expected according to the browser's default behavior.
Add modifier ```number``` to ```v-model``` directive will meet your expectation.

**Comment by hamutaro89** [comment]
Thanks for the solution on v-model.number. @pengchongfu @javoski
