### ISSUE TITLE
Global registered component has wrong render sequence

### ISSUE THREAD

**Issue by rottmann** [vuejs/vue#5738]
### Version
2.3.3

### Steps to reproduce
index.js
```
// Register global
import Child from 'child.vue'
Vue.component('child', Child)
```

parent.vue
```
<template>
  <div class="parent">
    <child>content</child>
  </div>
<template>

<script>
export default {
  name: 'Parent',
  created() {
    console.log('parent created')
  },
  mounted() {
    console.log('parent mounted')
  }
}
</script>
````

child.vue
```
<template>
  <div class="child">
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'Child',
  created() {
    console.log('child created')
  },
  mounted() {
    console.log('child mounted')
  }
}
</script>
```

### What is expected?
Parent should be mounted after child is created and mounted.

### What is actually happening?
Parent is created and mounted and after that the child ist created and mounted.

**Comment by LinusBorg** [comment]
Please include a reproduction link.

**Comment by LinusBorg** [comment]
Also from the desription, I'm unsure about what the actual problem is.

Are you indeed saying that the Parent's `created` hook fires after the child's? (Because everything else seems like expected behaviour.)

That would indeed be very strange.

**Comment by rottmann** [comment]
The parent is created and mounted and after this the child is created and mounted.

**console log is:**
parent created
parent mounted
child created
child mounted

**but it should be:**
parent created
child created
child mounted
parent mounted

**Comment by rottmann** [comment]
Ok it could be a loader problem, my code for loading the .vue is (i use webpack)

```
function component(name) {
  return () => System.import(`components/${name}.vue`)
}

// this is wrong
Vue.component('test', component('test'))

// this works
//import Test from 'components/test.vue'
//Vue.component('test', Test)
```

**Comment by LinusBorg** [comment]
* Rendering is a sync process. 
* Hwever, if you lazy-load a component with webpack, that happens asychronously.
* So the parent will finish rendering before the child has been lazy-loaded and rendered.

That's why the execution order is different, and that is to be expected.

**Comment by rottmann** [comment]
Thanks, thats what i thought too.

Feature Request: enable use of lazy loaded components

**Comment by rottmann** [comment]
but in my case the parent is the lazy loaded component.

**Comment by LinusBorg** [comment]
> Feature Request: enable use of lazy loaded components

You are using them, so that's not a feature request :D


Further discussion should be done in the forum.
