### ISSUE TITLE
v-for中key在不同的位置引发不同的问题

### ISSUE THREAD

**Issue by maiff** [vuejs/vue#5739]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/rdjjpc7a/3527/2/](https://jsfiddle.net/rdjjpc7a/3527/2/) 

[https://jsfiddle.net/rdjjpc7a/3526/](https://jsfiddle.net/rdjjpc7a/3526/) 

[https://jsfiddle.net/rdjjpc7a/3523/](https://jsfiddle.net/rdjjpc7a/3523/)

### Steps to reproduce
这三个链接都可以用下面的调试：
1.先加一个todo，然后点击todo的按钮让false变成true
2.再加一个todo，你会发现三个链接中会有不同的表现。第一个链接表现true，会跟着实际的todo走，第二个链接表现为true始终在第一个，第三个直接没有true。同时把第三个链接中

```
//第三个链接中代码的不同之处
<li  v-for="(todo, index) in todos">
      <todo-item
        v-bind:title="todo.text"
        :key="todo.index"
      ></todo-item>
    </li>
```

的key去掉，表现会跟第二个一样。
前面两种文档都有说，第三个代码的区别是key写在子组件而不是跟v-for写在一起，第三个链接为什么直接把子组件todo-item的自身的data.a全部初始化了。我主要的目的是看key加不加，加在不同的位置对子组件的data的影响

### What is expected?
在第三个链接中，虽然key跟v-for不在一个标签里，要么应该跟第一个链接加了key一样，要么跟没加key一样，仅仅把key当做一个用户传的props。

### What is actually happening?
但是实际上，在第三个链接中把所有的子组件自身的data也就是a全部初始化了

**Comment by yyx990803** [comment]
`key` 是针对获得 key 的元素的父容器而言的。key 加在里面的话，父容器是 `li`，没有任何 sibling，等于没有 key。

**Comment by maiff** [comment]
但是跟没有key的表现不一样。并没有复用子组件自身的数据，而是所有子组件的数据都初始化了。所以这里的key还是起到作用了。

**Comment by yyx990803** [comment]
因为外面的 li 被复用了，而里面的 todo key 变了，所以里面的 todo 都被重新创建了
