### ISSUE TITLE
component watch bug

### ISSUE THREAD

**Issue by dp199313** [vuejs/vue#5746]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/35709/](https://jsfiddle.net/50wL7mdz/35709/)

### Steps to reproduce
  组件watch一个props属性
  页面中存在多个组件实例
  其中一个组件的watch的属性被更改
  两个实例的watch处理函数都会被触发

### What is expected?
事实上它应该是两个组件实例互不干扰

### What is actually happening?
组件实例的watch的属性会互相影响

**Comment by posva** [comment]
This is working as expected. See #5740
tldr:

> To understand this you need to first understand how Vue 2 performs updates: templates are first compiled into render functions, and render functions are called every time the component is updated.
>
> Now since you are using an inline literal as a prop value (:users="['Bulma1', 'Goten1']"), a new literal Array will be created every time the parent component re-renders. And this causes the prop watcher to fire every time, too.
