### ISSUE TITLE
Allow component to indicate when it can no longer be reused by <keep-alive>

### ISSUE THREAD

**Issue by brad426** [vuejs/vue#5747]
### What problem does this feature solve?
Example markup:

```
<keep-alive>
  <router-view :key="$route.path"></router-view>
</keep-alive>
```

I use the `<keep-alive>` component so that my component instances will be reused when returning to the same route - allowing the state of the component to be maintained.

But at some point, I need to indicate that a particular component instance can no longer be reused, and a fresh instance of the component should be created.

For example, when a logged-in user visits the `/profile` route, the profile component should be reused if available, the user then navigates somewhere else, logs-out and then returns to the `/profile` route, the saved instance of the profile component should be discarded, and a fresh instance should be created.

### What does the proposed API look like?
Perhaps a `beforeActivated` hook could be added to a component, and when this method returns false, vue would create a fresh instance of the component, instead of reusing a previously saved instance.

```
export default {

  name: 'Profile',

  beforeActivated() {
    return someCondition ? true : false
  }
}
```

**Comment by posva** [comment]
I'm trying to understand better the problem. Why would you need te discard a component and create a new one. Current user is the kind of state that should be held with Vuex

**Comment by brad426** [comment]
I'm not using Vuex (maybe it's something I should look into), but for now the user data comes from a promise returning service.
My implementation look something like this:
```
export default {

  name: 'Profile',

  created() {
    UserService.getUser()
      .then(user => this.user = user)
  }
```

I know I could check to see if there is fresh data using the `activated` hook when the component is reused, but then the user will see the old state of the view, while the network request to get the new user data resolves.

I would prefer to just have a new instance of the profile component created when I know the user data has changed (due to user interaction elsewhere in the app)

**Comment by yyx990803** [comment]
We already have `include` and `exclude` props for `<keep-alive>` and they can be dynamically updated.
