### ISSUE TITLE
Feature Request: Nested Slots

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#5748]
### What problem does this feature solve?
I'm creating a Pages.vue that when i pass an array of objects it will create a paginated list of items inside the component which i would like to put a container before the scoped slots 

### What does the proposed API look like?
```pug

	div
		div(style="display: flex;justify-content: center;").pt-5
			.m-a
				v-pagination.mt-3(v-if="items.length", :length="pages.length" v-model="index")
		slot(name="container")
			slot(name="item", v-for="(item,i) in page", :item="item", :itemKey="i")
```
```js
<script>
	export default {
		name: 'admin-chunk',
		props: ['items','chunk'],
		data() {
			return {
				index: 1,
			}
		},
		computed: {
			page() {
				this.index = this.index > this.pages.length ? this.pages.length : this.index;
				return this.pages[this.index - 1];
			},
			pages() {
				return this.items.chunk(this.chunk || 4);
			}
		}
	}
</script>

```

and use it like this

```pug
admin-chunk(:items="items")
   div(style="display: flex" slot="container")
   template(scope="{item,itemKey}" slot="item")
      div {{item}} {{itemKey}}
  
```
maybe adding a prop like slot(nested name="container") would solve this and check the children vnodes if its a slot only

**Comment by yyx990803** [comment]
Content inside `<slot>` is considered fallback content - which means this proposal cannot be implemented without breaking changes.

Personally, I feel this makes slot composition overly complicated.
