### ISSUE TITLE
transition-group not working on table in edge

### ISSUE THREAD

**Issue by jclijmans** [vuejs/vue#5751]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/az8n11g1/](https://jsfiddle.net/az8n11g1/)

### Steps to reproduce
Transitions are not working on tables in my application. So I've created a jfiddle according to issue [#3907](https://github.com/vuejs/vue/issues/3907) to demonstrate the issue.

The transition works great in chrome but not in edge

I'm using edge 40.15063.0.0 on windows 10
.

### What is expected?
transition when shufling items

### What is actually happening?
transitions are ignored

**Comment by posva** [comment]
it seems to be a problem with edge itself not applying the `transform` property to `tr` elements. You should open a bug report in their tracker. It may be a limitation of tables too
