### ISSUE TITLE
the IE problem

### ISSUE THREAD

**Issue by cephiroth** [vuejs/vue#5753]
### Version
2.3.3

### Reproduction link
[http://dev.oss.yunsom.cn:801/yunsom/industrial-search.git](http://dev.oss.yunsom.cn:801/yunsom/industrial-search.git)

### Steps to reproduce
1.npm run build
2.running in IE11

### What is expected?
running normally

### What is actually happening?
IE11 prompt error：
1. "Promise"未定义
2. 对象不支持“n”属性或方法

---
1.The previous version is 2.2.2, everything is normal
2.Now updated to the latest version 2.3.3, compiled after running in IE11 browser suggested 'Promise' not defined
3.Project with vue-resource, replaced axios also reported the same mistake

**Comment by yyx990803** [comment]
Can't open the repro link, please provide a github repo instead.

**Comment by cephiroth** [comment]
https://github.com/cephiroth/search.git
can u open this?

**Comment by ematipico** [comment]
That could a problem related to the latest version of Webpack (2.6.0): https://github.com/webpack/webpack/issues/4916

**Comment by yyx990803** [comment]
Closing because I believe there's nothing in Vue itself between 2.2 and 2.3 that would lead to this error. Please make sure to provide a repro that shows this error is caused by **upgrading Vue only**.
