### ISSUE TITLE
vue 2.3.0版本directive的inserted钩子在 keep-alive 里面失效

### ISSUE THREAD

**Issue by weien601** [vuejs/vue#5755]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/twbv0sov/10/](https://jsfiddle.net/twbv0sov/10/)

### Steps to reproduce
inserted钩子应该是被插入到父节点后会被执行，但是在keep-alive的情况下，inserted只有在第一次插入时执行，被移除后再插入也不会再执行。
JSFiddle 选择2.2.0版本的 vue 也有此问题：

### What is expected?
能够在插入的时候调用inserted hook

### What is actually happening?
keep-alive 时 非首次插入不会执行inserted hook

**Comment by yyx990803** [comment]
This is expected behavior. `inserted` is called only once for the **initial insert**.
