### ISSUE TITLE
About handling of exception in Watcher

### ISSUE THREAD

**Issue by hangilc** [vuejs/vue#576]
Hi,
I was a little bit surprised when a computed value was just ignored when there happened an exception while being evaluated. Is it an intended behavior? It seems to me that it would be more helpful if vue.js warns the error, because in that manner I can detect that something went wrong.

Reading the source code, it appears that error message can be made to be output in p.get (/src/watcher.js) by modifying "catch(e){}" part.

Am I missing something?

``` javascript
p.get = function () {
this.beforeGet()
var vm = this.vm
var value
try {
value = this.getter.call(vm, vm)
} catch (e) {} // <== HERE!
// use JSON.stringify to "touch" every property
// so they are all tracked as dependencies for
// deep watching
if (this.deep) JSON.stringify(value)
value = _.applyFilters(value, this.readFilters, vm)
this.afterGet()
return value
}
```

**Comment by FlorianWendelborn** [comment]
@yyx990803 will this behavior be fixed in Vue 3 so that errors bubble up the stack instead of just being swallowed by Vue’s internals?
