### ISSUE TITLE
out-in transition issue with async components 

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#5760]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/z11fe07p/1959/](https://jsfiddle.net/z11fe07p/1959/)

### Steps to reproduce
- load https://jsfiddle.net/z11fe07p/1959/
- click the "B" button

### What is expected?
The previous component (A) should disappear before component B appears

### What is actually happening?
Components A and B are visible simultaneously

---
This behavior is happens only when component B is not already loaded. Next time you switch from A to B, everything is fine.

**Comment by posva** [comment]
Thanks, looks like a bug. Thanks for the concise and clear repro 🙂

**Comment by gebilaoxiong** [comment]
It seems that the async component is rendered too early

**Comment by gebilaoxiong** [comment]
As the `async component` has not yet been parsed, the `transition`  is a comment Element

**Comment by gebilaoxiong** [comment]
I have solved, wait a minute ...

**Comment by clingor** [comment]
Are you sure this solves the async component transitions?  I'm new to Vue so it's likely a bug in my code, but my repo below still exhibits the transition out-in bug where the incoming component doesn't wait for the out fade to complete.  Note I'm using the http-vue-loader named above.

[Async Component Transition Bug Demo](https://github.com/clingor/githubIssuesFileShare/tree/master/vue-async-component-bug)

**Comment by posva** [comment]
This is indeed still failing with the same repro. The transition starts right away as @clingor said

**Comment by gebilaoxiong** [comment]
@posva 

https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.js

Looks like this version does not contain the fix code

**Comment by yyx990803** [comment]
The fix has not been released yet. We closed issues when the patch lands in the `dev` branch, but it might not be in a public release yet.

**Comment by posva** [comment]
My bad, I just saw the commit was before the release and thought it was strange. It would have been in the release notes anyway

**Comment by clingor** [comment]
Sorry for the misunderstanding, and thank you for confirming the issue!

**Comment by clingor** [comment]
This doesn't appear to be fixed yet in 2.4.2.  Is this still pending release?

[Async Component Transition Bug Demo](https://github.com/clingor/githubIssuesFileShare/tree/master/vue-async-component-bug)

**Comment by posva** [comment]
@clingor Are you sure? The jsfiddle works nicely

**Comment by clingor** [comment]
The fiddle does work correctly, but the code in [my example GitHub repo](https://github.com/clingor/githubIssuesFileShare/tree/master/vue-async-component-bug) still exhibits the same behavior.  It could be the [http-vue-loader](https://github.com/FranckFreiburger/http-vue-loader) helper library, or maybe something in my code.  This example is simple and was created to demonstrate [the issue](https://github.com/FranckFreiburger/http-vue-loader/issues/6).

@FranckFreiburger would any of these VueJS changes require an update to [http-vue-loader](https://github.com/FranckFreiburger/http-vue-loader)?

**Comment by posva** [comment]
if you put the issue on a jsfiddle without the loader I can take a look

**Comment by SubheKhalaf** [comment]
Am 21.07.2017 21:16 schrieb "Chris Lingor" <notifications@github.com>:

**Comment by FranckFreiburger** [comment]
The culprit is `<keep-alive>` !

Steps to reproduce

1. see https://jsfiddle.net/z11fe07p/2382/
2. click the "B" button

**Comment by FranckFreiburger** [comment]
@posva, are you able to reproduce ?

**Comment by posva** [comment]
@FranckFreiburger You should open a new issue for that
