### ISSUE TITLE
The Reactive data doesn't work with Array in Object

### ISSUE THREAD

**Issue by ccforward** [vuejs/vue#5761]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/ccforward/fa35a2cc/](https://jsfiddle.net/ccforward/fa35a2cc/)

### Steps to reproduce
1.  In this demo, (https://jsfiddle.net/ccforward/fa35a2cc/) I cannot render the template and the data `resultWrong` equals `{}`

2. In this demo, (https://jsfiddle.net/ccforward/zoo6xzck/), if I use a temporary variable to save the async data ,then I can get the result and render the template

3. If I add another function named as `getRightData()` in the methods, then the  `getWrongData()`  can work and the template can be rendered.
link: https://jsfiddle.net/ccforward/7f42owpc/4/

4. If I delete the `getRightData()` method, then the `getWrongData()` cannot work.
link:  https://jsfiddle.net/ccforward/7f42owpc/3/

### What is expected?
https://jsfiddle.net/ccforward/zoo6xzck/

### What is actually happening?
https://jsfiddle.net/ccforward/fa35a2cc/

---

**Comment by LinusBorg** [comment]
You have to use `Vue.set` / `this.$set()` to add new keys to reactive objects.

https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
