### ISSUE TITLE
Create a vue language service extension for typescript 

### ISSUE THREAD

**Issue by lucastheisen** [vuejs/vue#5763]
### What problem does this feature solve?
Provides types for custom components written as SFC (.vue), imported by other files (like unit tests).  Right now, you suggest:
```
declare module '*.vue' {
    import Vue from 'vue'
    export default typeof Vue
}
```
But that results in every imported SFC component being of type `Vue` rather than the component type (which extends Vue).  It makes it much more difficult (annoying) to test.

### What does the proposed API look like?
It would conform to the recently released (ts version 2.3) [language server plugin supporty](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/#language-server-plugin-support)

**Comment by lucastheisen** [comment]
Support for `.vue` files was mentioned in the [typescript git repo](https://github.com/Microsoft/TypeScript/issues/10427#issuecomment-240939070), but that essentially just said:

>  I've spoken with Evan (@yyx990803) before. Supporting .vue files would be something that ideally a language service extension would take on (see [#10160](https://github.com/Microsoft/TypeScript/pull/10160) for details).

So now, i would like to request that an extension for `.vue` files gets written.

**Comment by ktsn** [comment]
There is a language service implementation for vscode by @octref and we currently working for it. 
https://github.com/octref/vetur

**Comment by yyx990803** [comment]
^ we currently don't have plan to implement it as a standalone project, so if you want some IDE-like experience, you'll need to use VSCode + vetur. Maybe @octref will be able to extract the language service into a standalone project in the future?

**Comment by octref** [comment]
Tracked in https://github.com/octref/vetur/issues/168 but not going to happen soon, since the language service is undergoing a major rewrite to have better template IntelliSense (previously dealing with each html/css/js regions separately, now using info from css/js sections for even more advanced IntelliSense in html).
