### ISSUE TITLE
Empty $children on app

### ISSUE THREAD

**Issue by terion-name** [vuejs/vue#5768]
### Version
2.3.3

### Reproduction link
[https://codepen.io/anon/pen/rmbdVK](https://codepen.io/anon/pen/rmbdVK)

### Steps to reproduce
1. create an app with template, render function or mount it to element with some content
2. try to get `$children` property

### What is expected?
list of child components

### What is actually happening?
empty array

---
I really don't know, if it is an issue, docs don't cover such scenario, but it by logic this should work

**Comment by ktsn** [comment]
Because you are not having any child components in your reproduction.
It works if child components are provided in the root instance.
https://codepen.io/anon/pen/gWyzro

**Comment by terion-name** [comment]
@ktsn hm. generic html tags are not treated as child components? 

But from here https://vuejs.org/v2/guide/render-function#slots-vs-children :
>```
><my-functional-component>
>  <p slot="foo">
>    first
>  </p>
>  <p>second</p>
></my-functional-component>
>```
>For this component, children will give you both paragraphs...

**Comment by ktsn** [comment]
It's the docs for the functional component's render context but not for the component instance. 
See: https://vuejs.org/v2/api/#vm-children
