### ISSUE TITLE
vue-server-renderer type definitions

### ISSUE THREAD

**Issue by cdekok** [vuejs/vue#5772]
### What problem does this feature solve?
Using vue-server-renderer with typescript, it seems vue and vue-router are supported it would be nice if vue-server-renderer came with typings to.

### What does the proposed API look like?
The same but with types directory.

**Comment by yyx990803** [comment]
@ktsn would you be interested in working on this? The [API surface](http://ssr.vuejs.org/en/api.html) is not too big so it should be relatively straightforward.

**Comment by ktsn** [comment]
@yyx990803 Done! #5775
