### ISSUE TITLE
Child components lost after parent hides, events are lost

### ISSUE THREAD

**Issue by terion-name** [vuejs/vue#5773]
### Version
2.3.3

### Reproduction link
[https://codepen.io/terion/pen/vmwKRN?editors=1010](https://codepen.io/terion/pen/vmwKRN?editors=1010)

### Steps to reproduce
1. try to listen to children components event
2. hide their parent
3. show it

### What is expected?
events keep working

### What is actually happening?
events don't work

---
I have an app that is hidden on init (via `v-if`), shown after some time, and it should listen to events of child components. But because it is hidden by default, it has no `$children` when mounted (see reproduction). And after mount when it is displayed — at that point `$children` are populated, but there is no hook for this lifecycle point.

Also if the app is displayed at start — events work, then I hide it and show again — no more events.

Setting `v-if` to nested wrapper does not change anything

**Comment by yyx990803** [comment]
Use `Vue.nextTick` to wait for updates after you change `this.showme`. Also, this is not a bug report.
