### ISSUE TITLE
Markdown demo bug

### ISSUE THREAD

**Issue by asharpe** [vuejs/vue#5780]
### Version
2.3.3

### Reproduction link
[https://vuejs.org/v2/examples/index.html](https://vuejs.org/v2/examples/index.html)

### Steps to reproduce
Visit the markdown demo...

Expected

     * a
      * b
       * c
      * d
       * e
        * f
      * g
       * h
        * i
         * j

Result

 * a
  * b
   * c
  * d
   * e
    * f
  * g
   * h
    * i
     * j

### What is expected?
A list indented as per the source

### What is actually happening?
Items at levels 2 and 3 (b,c,d,e,g,h) appear on level 2.  Items at levels 4 and 5 (f,i,j) appear on level 3.

It probably goes deeper than this...

---
This form was a bit of an insult at first, though I can understand why you'd do it.  I can't help but feel there's a middle ground somewhere, just not sure where that is yet though…

**Comment by yyx990803** [comment]
Markdown actually uses 4 spaces for list indent, so double-space will likely not display as expected (e.g. as seen in your result with github markdown). Also regardless of whether the behavior is correct, this is an issue with the markdown library (marked) instead of Vue itself.
