### ISSUE TITLE
partial ssr rendering

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#5787]
### What problem does this feature solve?
1/
Many component are not (yet) compatible with ssr and may require large changes to support it.
Partial ssr rendering could allow to use these component meanwhile they are eventually "ported".
The directives could also benefit from this behavior.

2/
Some components may not be mandatory for SEO, this could allow a better client-side/server-side load balance.

### What does the proposed API look like?
a vue component:
```
<template>
...
</template>
<script>
export default {
  allowServerSideRendering: false
  ...
}
</script>
```

**Comment by LinusBorg** [comment]
You can pretty easily define a wrapper component that keeps components from rendering during SSR (and postpones rendering on the client so hydration works correctly)

@egoist did this in like 5 lines of code: 

https://github.com/egoist/vue-no-ssr

**Comment by atom110436** [comment]
Get
เมื่อ 30 พ.ค. 2017 16:24, "Franck Freiburger" <notifications@github.com>
เขียนว่า:

**Comment by FranckFreiburger** [comment]
Thanks, this is fine for me !
