### ISSUE TITLE
Render Function: Data.directives should not allow both value and expression to be set

### ISSUE THREAD

**Issue by daniel-shuy** [vuejs/vue#5792]
### What problem does this feature solve?
When setting directives in a Render Function, if `expression` is provided, shouldn't `value` be automatically evaluated from `expression` instead (and not allow `value` to be set)? It would also be nice if `expression` is not allowed to be set if `value` is provided.

### What does the proposed API look like?
```javascript
createElement('div', {
    directives: [
        {
            name: 'my-custom-directive',
            // value should not be allowed to be set, instead be automatically evaluated from expression as 2
            expression: '1 + 1',
            arg: 'foo',
            modifiers: {
                bar: true
            }
        }
    ],
}

or 

createElement('div', {
    directives: [
        {
            name: 'my-custom-directive',
            value: 2,
            // expression should not be allowed to be set
            arg: 'foo',
            modifiers: {
                bar: true
            }
        }
    ],
}
```

**Comment by posva** [comment]
Thanks for raising the point. Setting the expression when doing jsx or pure js makes no sense since you can already pass an arbitrary expression and it will be evaluated. **You should only set the value** in render functions.
We can add a warning in Vue, but the most important part is updating the docs

playground: http://jsfiddle.net/yy2jLod1/

**Comment by daniel-shuy** [comment]
Ah I see. What about the other suggestion (automatically evaluating `value` using `expression`)?

**Comment by posva** [comment]
It's not possible because the expression is evaluated by the template compiler. Just use it directly as the value 🙂

**Comment by daniel-shuy** [comment]
I see, oh well, thanks for your time
