### ISSUE TITLE
Slot-component communication

### ISSUE THREAD

**Issue by NxtChg** [vuejs/vue#5793]
### What problem does this feature solve?
For slots to be really useful, there needs to be a way of communicating with the component. Either the ability to directly call component's methods or send an event to it.

Simple example is the dropdown component that has one slot for the button and the other for content. The button must open/close the dropdown and content items must be able to close it on click too.

Currently most dropdown components parse child items in slots in mounted() and attach event listeners to them. This is bad. This should be handled transparently by Vue.

### What does the proposed API look like?
Maybe something like $emit-local() which will send the event from slot items to the component itself.

Another idea is when you insert the elements into the slot - pass the component reference to them, so they can call the methods directly (although this is probably not a good design). As a compromise user can specify which methods of the component to expose, sort of mini-API.

**Comment by posva** [comment]
To expose methods to the parent component when customising a component content using a slot, use scoped slots and pass methods the same way you pass variables:

```html
<div class="child">
  <slot :open="open"></slot>
</div>
```
