### ISSUE TITLE
Dynamically added classes removed when using v-bind:class

### ISSUE THREAD

**Issue by benstevens48** [vuejs/vue#5795]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/sjfurg9a/](https://jsfiddle.net/sjfurg9a/)

### Steps to reproduce
Add v-bind:class to a tag which toggles a class based on some boolean view-model data variable. Now add a class to that HTML element directly using JavaScript (I tested using classList - haven't tried modifying the attribute). Now do something that causes to the boolean view-model variable to change. The dynamically added class is removed from the element.

### What is expected?
Dynamically added class should not be removed.

### What is actually happening?
Dynamically added class is removed.

**Comment by sirlancelot** [comment]
Not a bug, don't do that.

**Comment by posva** [comment]
This is expected, you should handle all the classes with vue

**Comment by benstevens48** [comment]
I think this is a bug. This behaviour means I can't use Vue in conjunction with other pieces of JavaScript. For example, I have a `FullscreenManager` class (independent of Vue), with a method `FullscreenManager.setFullscreenElement(element)`. This adds the class `fullscreen` to the element. If it happens to also have a class added with `v-bind:class`, then the `fullscreen` class is removed. This seems like a very reasonable use case to me which should work.

**Comment by posva** [comment]
Let me put it in another way: you can manage the classes with Vue alone, or use it a plugin/lib custom code to manipulate the classes and wrap that into a Vue component. But it's not a bug, really 🙂

**Comment by benstevens48** [comment]
But one of the core principles of Vue is that it works well with other frameworks and existing projects. This is taken from the opening paragraph of the Vue guide.

> Unlike other monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable. The core library is focused on the view layer only, and is very easy to pick up and integrate with other libraries or existing projects.

If you say I have to use Vue to manage everything, then that completely contradicts this core principle.

I don't see any technical reason why Vue can't preserve dynamically added classes. If you think this is not a bug, then can you convert it to a feature request?

**Comment by posva** [comment]
It actually is easy to integrate libs with Vue. If you need help you can always ask on the forum.
This dynamic class issue you're facing has been discussed many times already, looking up for other issues may help you
