### ISSUE TITLE
Unexpected data value after resetting data binded on @change

### ISSUE THREAD

**Issue by Tyki** [vuejs/vue#5797]
### Version
2.3.3

### Reproduction link
[https://www.webpackbin.com/bins/-KlX_9o6bM4fId_8YNwd](https://www.webpackbin.com/bins/-KlX_9o6bM4fId_8YNwd)

### Steps to reproduce
- Select "test1" then select "test2"
- When selecting "test2", you see the second select showing up
- Click "reset" button"
=> The second select shouldn't be there because " this.test = '' "

### What is expected?
the second select shouldn't appear when resetting with the button

### What is actually happening?
the second select is still in the DOM because of a undefined value

**Comment by sirlancelot** [comment]
It looks like that bin is actually using v2.2.4. Can you update it to the latest version? It's odd to me that the change event is firing when it shouldn't be.

**Comment by Tyki** [comment]
I don't think I can change it on the website.
I reproduce with the same issue with vue 2.3.3 and vue-template-compiler 2.3.3

Actually, we found out where is the problem.

When clicking on the "reset" button, I'm setting `this.test` to the value '' (empty quote)
Since there is no option with this value, the v-model can't match any option available in the DOM and set this.test to undefined

The workaround here is to put an 
`<option` value="" selected style="display:none;"></option>`

That's dirty but it works.

**Comment by posva** [comment]
Dup of #4524 
It's intended: if no possible option exist, the variable is set to `undefined`
