### ISSUE TITLE
Clarity in the docs if Vue 2.*.* is following semver strictly. 

### ISSUE THREAD

**Issue by daymos** [vuejs/vue#5798]
### Version
2.3.3

### Reproduction link
[https://vuejs.org/v2/guide/](https://vuejs.org/v2/guide/)

### Steps to reproduce
search in the docs for: versioning, semver, backward compatibility. No relevant answer are given.

### What is expected?
A statement to specify if vue 2 is strictly semver

### What is actually happening?
no info returned by searching with the search box

---
Looking at the issues on github, it seems it might, but I couldn't find a specific statement in the docs that Vue 2.*.* is strictly semver, and therefore offer full backward compatibility. Have I missed it or is not stated anywhere ?

**Comment by posva** [comment]
just for the info, yes, Vue follows semver 🙂 
It is not stated anywhere, I personally consider it's the default for any library.
Can you open the issue on the docs repo instead please: https://github.com/vuejs/vuejs.org/
Thanks!

**Comment by daymos** [comment]
allright, thanks.
