### ISSUE TITLE
Render function with nested children stops at first level

### ISSUE THREAD

**Issue by dotBits** [vuejs/vue#5801]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/cdev/fu5pj6sm/](https://jsfiddle.net/cdev/fu5pj6sm/)

### Steps to reproduce
Create a 2 levels deep components structure using createElement within a render function

### What is expected?
All children in hierarchy should be rendered

### What is actually happening?
Rendering stops at first hierarchy level and subsequent children are ignored

---
Is this by design?

**Comment by yyx990803** [comment]
This is expected - the children are being overwritten by your `innerHTML`.
