### ISSUE TITLE
nodejs server side templating incompatible with vue.js templating

### ISSUE THREAD

**Issue by matt212** [vuejs/vue#5806]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Hi , 
i am using below code to avoid {{}} templating issues between my server side templating and client side templating and i wanted to perform the same using vue.js 

```
var myApp = angular.module('scotch', ['userroleCtrl', 'SelectAsyncController', 'mystackedctrl', 'ContactChipDemoCtrl', 'mainapp', 'AppCtrl', 'Switchbase', 'fabctrl', 'ExampleCtrl', 'slidenav'], function($interpolateProvider) {
    $interpolateProvider.startSymbol('[{');
    $interpolateProvider.endSymbol('}]');

});
```

### What is expected?
some sort of interpolateProvider before or during lib which tells the vue.js to use '[{'  instead of {{ !

### What is actually happening?

it is not excatly an issue. hence  nothing is happening !

---
the reproduction part is not required since rather than issue it is an incompatibility issue while rendering on client side and also for you reference 
https://stackoverflow.com/questions/36517284/angularjs-not-working-in-nodejs-express

**Comment by posva** [comment]
I think you're looking for this: https://vuejs.org/v2/api/#delimiters
