### ISSUE TITLE
help needed for realworld.io sample project

### ISSUE THREAD

**Issue by omidfi** [vuejs/vue#5810]
### What problem does this feature solve?
Hello Vue community, 
I searched the issues but couldn't find anything related to this, hope it's not a duplicate. 

Recently Realworld.io is collecting a real world example of a blogging app written in different frameworks. There are already projects for react, angular, elm etc. It would be nice if the vue community helped to make the vue example. 

Please take a look:

https://github.com/gothinkster/realworld/issues/7

### What does the proposed API look like?
A full example of creating a blog using Vuejs, based on the spec of realworld.io

**Comment by yyx990803** [comment]
Thanks for raising this - however, I'd suggest posting this to the forums / gitter instead. The issue list is reserved for potentially actionable items for Vue itself.
