### ISSUE TITLE
Should "boolean" attributes on nodes explicitly extracted as props be booleans? (Functional Components)

### ISSUE THREAD

**Issue by crswll** [vuejs/vue#5811]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/crswll/e7b5y5qr/1/](https://jsfiddle.net/crswll/e7b5y5qr/1/)

### Steps to reproduce
Set a boolean attribute on a functional component.

`<foo bool>`

### What is expected?
`bool` is `true` in `context.props`

### What is actually happening?
`bool` is empty string `''` in `context.props`

---
This seems correct but not sure. It's easily doable from my side but it might be worth considering or a bug?

I arrived at this situation because I'm messing around with CSS in JS options and it's expecting something like:

```js
{
   mx3: true,
   p: 2,
}
```

From some markup like:

```html
<foo mx3 :p="2"></foo>
```

I'm also curious about default units for numbers on certain properties passed to `:style` (React has default units I guess for certain properties? but that's for another issue)

**Comment by yyx990803** [comment]
I think this is expected behavior because you did not explicitly specify types for the prop, so no casting would be performed. This is consistent with stateful components where you declare a prop with `any` type.
