### ISSUE TITLE
Vue js dynamically loaded component name from ajax

### ISSUE THREAD

**Issue by bhaktear** [vuejs/vue#5812]
I am new in vuejs . I want to load component from ajax response.

    <div id="app"></div>
    export default(){
      created: function(){
        const url = "xyz.json";
        this.$http.get(url).then(response => {
          this.resp = response.body;
          var comp = this.resp.components;
        }
      }
    }

Here is my JSON response

    {
       components: "Hello.vue",
       
    }
I want to draw dynamically components by using json data

**Comment by Kingwl** [comment]
try async component and dynamic import / require
