### ISSUE TITLE
Watchers Do Not Handle Arrays as Expected

### ISSUE THREAD

**Issue by chadcampbell** [vuejs/vue#5814]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/ecofic/n4z8sL1t/](https://jsfiddle.net/ecofic/n4z8sL1t/)

### Steps to reproduce
To reproduce the steps, please do the following:

1. Click the "add to cart" button next to any of the items in the catalog.
2. Review the "Total" and "Items" values.

### What is expected?
The expectation is that the "original" value of the watched `Array` would be the value of the `Array` prior to the item being added to the cart.

In the example, the expectation is that the values in the "Items" section does not match the values in the "Total" section.

### What is actually happening?
The original value of the Array is the same as the latest value. This does not seem correct.

---
I've been working on a developer training course named [Vue.js: Getting Started](https://www.ecofic.com/courses/vue-getting-started).  I stumbled on this issue while creating content for that course. For the time being, I'm updating the course content to work around this issue. However, I thought it should be reported as I didn't see anything similar listed on GitHub.

**Comment by posva** [comment]
It is expected, Vue doesn't create copies of the data. More info here: https://vuejs.org/v2/api/#vm-watch
