### ISSUE TITLE
Vue plugin component instance null

### ISSUE THREAD

**Issue by vanjadevs** [vuejs/vue#5821]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/38087/](https://jsfiddle.net/50wL7mdz/38087/)

### Steps to reproduce

Install the following plugin:
```js
const InplaceEditPlugin = {
  install (Vue, options) {
    Vue.prototype.$myAddedProperty = 'Example Property'
    Vue.prototype.$myAddedMethod = function () {
      console.log(this)  // <----- WRONG VALUE: THIS == NULL
      return Vue.myAddedProperty
    }
  }
}      
export default InplaceEditPlugin
```

Calling newly added $MyAddedMethod on a vue component/instance should log `this` (instance reference) to console .

### What is expected?
`this` should be a reference to a vue component/instance

### What is actually happening?
instead, it is null

---
I was writting a plugin that needs to add a method to all instances. This method utilizes `this` reference to an instance.

Followed the docs... Am I missing something?

Thanks in forward

**Comment by gebilaoxiong** [comment]
e.... 

first of all,  Please write the issue correctly...  for the other people can help you solve the problem quickly.

``` javascript
new Vue({
  el: '#app',
  data: {
    message: this.$myAddedMethod()
  }
})
```

seems the `this` is `window`. right ?

**Comment by posva** [comment]
You need to use `data` as a function to make _this_ work: https://jsfiddle.net/0vjvchzz/
I fixed the markup of your issue, in case you want to take a look

You should consider using the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for question, you will get faster feedback.

**Comment by vanjadevs** [comment]
That makes no sense whatsoever... What if I want to use method as a reaction to click event???
