### ISSUE TITLE
keep-alive-component  should allow create multiple instance when needed

### ISSUE THREAD

**Issue by zuibunan** [vuejs/vue#5823]
### What problem does this feature solve?
I googled my problem, and found someone have the same problem.

There are some pages A, B ... 
 A->B means jump from A to B, this is fine. When one page occurs multiple time in single stack like A in A->B -> ... ->A, I failed in trying to keep first A and B alive during back.

If I use <keep-alive> around <router-view>, the first A and the second A will share one component, I have to recreate the first A when click back button. And things will get worse without using <keep-alive>, I have to recreate every page in the stack.

https://stackoverflow.com/questions/40297068/vue-router-with-keep-alive-can-not-cache-pages-in-stack

examples
1: Order.vue > Pay.vue > Success.vue > Order.vue

2: ShopList.vue> Shop.vue(shop 1) > HotShops.vue > Shop.vue(shop 2)

### What does the proposed API look like?
Not ready yet ,  I am thinking about how to design the API...

may be someone else have a better idea ?

**Comment by yyx990803** [comment]
`<keep-alive>` is not designed for this type of navigation. What you need is a stack-like navigation library, but that's not going to be part of core.

**Comment by alexsandro-xpt** [comment]
@zuibunan any success? Are you try something like https://github.com/zack24q/vue-navigation ?

**Comment by VladZen** [comment]
For anyone, who is still craving for a solution
```
<router-view v-slot="{ Component, route }">
    <keep-alive include="Chat">
        <component :is="Component" :key="route.path" />
    </keep-alive>
</router-view>
```

Just add a `key`

**Comment by songkang1993** [comment]
> 

It does not work for me.
vue-router: 3.5.2
