### ISSUE TITLE
checkbox rendered by render function can't work correctly

### ISSUE THREAD

**Issue by rubyisapm** [vuejs/vue#5825]
### Version
2.3.3

### Reproduction link
[https://codepen.io/rubyisapm/pen/JJobZj?editors=1010](https://codepen.io/rubyisapm/pen/JJobZj?editors=1010)

### Steps to reproduce
1. Click the button and toggle the checked status very well. 
2. Change the checkbox manually, 
3. Click the button, it doesn't work - checkbox can't reflect the change of 'checked'

### What is expected?
checkbox can reflect the change of data in vm

### What is actually happening?
checkbox can't reflect the change of 'checked'

**Comment by yyx990803** [comment]
`checked` as an attribute only controls the initial state. You need to use `domProps: { checked: this.checked }` instead.
