### ISSUE TITLE
无法在表单中输入字符

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue#5826]
### Version
2.3.3

### Reproduction link
[https://codepen.io/shusiwei/pen/mwyOYw](https://codepen.io/shusiwei/pen/mwyOYw)

### Steps to reproduce
当某些数据更新很快

### What is expected?
正常的输入字符 

### What is actually happening?
表单无法输入字符

**Comment by yyx990803** [comment]
Use `@input` and it works as intended. It seems `keyup` fires too late so the timer may get fired in between the input's value change and the event firing.
