### ISSUE TITLE
Inline-template fails to display without an intermediate container.

### ISSUE THREAD

**Issue by mnbeer** [vuejs/vue#5830]
### Version
2.3.3

### Reproduction link
[http://plnkr.co/edit/1UvuoqHHGGaHy07Sy4ar?p=preview](http://plnkr.co/edit/1UvuoqHHGGaHy07Sy4ar?p=preview)

### Steps to reproduce
Add content in child component markup without surrounding in an intermediate container (div).

```html

    <div id="VueContainer">
      <child1 inline-template>
         <div>This text shows because it is inside of an container.</div>
      </child1>
      <child2 inline-template>
         This text does not show because it is NOT inside of a container. It fails
         silently with, leaving no obvious indication of what is wrong.
      </child2>
    </div>

```

### What is expected?
Everything in the template to render. Or, if unacceptable, some error or console message.

### What is actually happening?
Template simply does not render, failing silently and leaving the developer little clue as to how to debug.

---
This is somewhere between a bug report and feature request. This has tripped us up a couple of times and wasted a bunch of debugging time.  I know inline-template is not the preferred practice, but for retrofitting Vue into a legacy application, it works quite well.

**Comment by yyx990803** [comment]
There **is** a warning:  "Inline-template components must have exactly one child element."

**Comment by mnbeer** [comment]
Thanks for the reply; I'm sorry I missed that in the docs, but the general point still stands. Sometimes the best documentation occurs in the action of the code.  An error and/or console message would really help here.  Silent failure is rarely the best course of action.

**Comment by Akryum** [comment]
Open your browser console:

![image](https://user-images.githubusercontent.com/2798204/26837446-b70614a4-4add-11e7-99e2-7f20ba6048ff.png)

**Comment by mnbeer** [comment]
Wow. Believe me, we looked at our console multiple times and saw nothing.
Maybe we accidentally had the console filtered. I see it clear as day in my
plnkr example now. My apologies; that is perfect.

Matthew Nicholson Beer
The Foundry Software Development Co.
(314) 529-1455
matthew.beer@foundrysoftware.com

**Comment by caimaturo** [comment]
Same here, no warning or error on the console either.
