### ISSUE TITLE
Extend debug mode to help find subtle errors during development

### ISSUE THREAD

**Issue by Brimstedt** [vuejs/vue#5832]
### What problem does this feature solve?
To help developers not get stuck on hard to catch or non apparent bugs, it would be neat if debug mode could check:

  * Do we have data properties with same name as a method (to avoid confusing "xxx is not a method)
  * Did an object loose reactivity on some property (i.e. did a non getter/setter property on any of the managed objects appear)

Probably there are other helpers to be added as well.

### What does the proposed API look like?
There is already an API to turn on debug mode.

```Vue.config.debug = true```

**Comment by yyx990803** [comment]
All warnings are on by default in development mode.

There's no way to detect a newly added non-reactive property in ES5.

**Comment by Brimstedt** [comment]
Thanks for reviewing my feature request!

To bad about the reactivity detection.

What about warning when there is shadowing? I.e. properties, getters or methods with the same names?
