### ISSUE TITLE
$scopedSlots.default is not a function

### ISSUE THREAD

**Issue by chaishi** [vuejs/vue#5833]
```
render (createElement) {
    return createElement('thead', [
      createElement('tr', this.cols.map(item => {
        return createElement('th', [
          this.$scopedSlots.default({
            item: item
          })
        ])
      }))
    ])
  },
```
 TypeError: _this.$scopedSlots.default is not a function

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by lsycxyj** [comment]
I met the same problem. And it seems that there is no solution. This issue can be found on: 
https://forum.vuejs.org/t/weird-vuejs-error-with-elementui-table--self-scopedslots-default-is-not-a-function/12933

**Comment by WhereJuly** [comment]
Got the same error within a component's `render` function. Fixed with adding the HTML element with `slot-scope="{item: item}"` (just to match the example of the OP) insde the component.

Here is some code extract:

``` javascript
this.render = function() {
    return this.$scopedSlots.default({
        item: this.$data.item
    });
};
```

``` html
<component-with-render-function>
    <div slot-scope="{item: item}">
        {{ item }}
    </div>
</component-with-render-function>
```

The thing is, to my understanding, that until you create a scoped slot in the markup it is not available in the `render` function.

**Comment by begueradj** [comment]
In my case that happened because I did not inject props data from the parent component where it is used. This is exactly what @WhereJuly WhereJuly avoided.

**Comment by WhereJuly** [comment]
> you can write directly `item: this.item` instead of `item: this.$data.item`
@begueradj That its true. 

But the explicit use of `this.$data.zzz`, `this.$props.yyy` and the like is much better for the code clarity. All the times one uses props and data the relations between their items are quite stable.

E.g. you would always take values from props and put these to data. Not vice versa. Thus explicit mention `this.$data.zzz` and `this.$props.yyy` on the same expression at one sight gives a reader a much clearer understanding of what goes where.
