### ISSUE TITLE
Customizing v-model prop not working

### ISSUE THREAD

**Issue by KKSzymanowski** [vuejs/vue#5834]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/azvoLf8r/1/](https://jsfiddle.net/azvoLf8r/1/)

### Steps to reproduce
1. Create a component with customized `v-model` configuration:
```js
model: {
    prop: 'foo',
    event: 'bar',
}
```
2. Use the component with `v-model`:
```html
<custom-component v-model="parentFoo"></custom-component>
```
3. Use the prop in the component:
```
{{ foo }}
```

### What is expected?
The child component should display the value of `foo`

### What is actually happening?
Error is thrown:
```
[Vue warn]: Property or method "foo" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <CustomComponent>
       <Root>
```

I suppose I'm doing something wrong, but I've read the [docs](https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model) over and over and cannot figure out why this isn't working.

**Comment by LinusBorg** [comment]
You still have to actuall *define* the `foo` prop.

**Comment by KKSzymanowski** [comment]
Thanks a lot. Should I make a PR to the docs regarding this requirement?

**Comment by LinusBorg** [comment]
That would be helpful, yes. Thanks!
