### ISSUE TITLE
Module not found: Error: Can't resolve 'vue-roter' - Windows only

### ISSUE THREAD

**Issue by jrvidotti** [vuejs/vue#5836]
### Version
2.3.2

### Reproduction link
[https://pastebin.com/7Ct1wfzg](https://pastebin.com/7Ct1wfzg)

### Steps to reproduce
I got and "Module not found" error in Windows that doesn't happens in CentOS.
Steps: 
1. init a fresh webpack-simple project; running ok! 
2. npm install --save vue-router 
3. add a import "import VueRoter from 'vue-roter'" to main.js
4. gives error: "Module not found: Error: Can't resolve 'vue-roter' in ....

### What is expected?
Run smoothly

### What is actually happening?
Error Module not found

---
Node 8.0.0

**Comment by mcacek** [comment]
`vue-router` vs `vue-roter`?

**Comment by bedakb** [comment]
Actually if you go to the node_modules directory you will see there are not directory called like `vue-roter`, probably you will find something called `vue-router`.

Something like this should work:

```
import VueRouter from 'vue-router'

Vue.use(VueRouter)
```

**Comment by jrvidotti** [comment]
Shame on me! 😣
