### ISSUE TITLE
编程式路由没有正常渲染嵌套视图

### ISSUE THREAD

**Issue by blackstone86** [vuejs/vue#5840]
### Version
2.3.3

### Reproduction link
[http://jsfiddle.net/m3hxnhdp/](http://jsfiddle.net/m3hxnhdp/)

### Steps to reproduce
重复点击“user/foo”,嵌套路由匹配视图没有显示

### What is expected?
重复点击“user/foo”,嵌套路由匹配视图要显示

### What is actually happening?
嵌套路由匹配的视图没有显示

**Comment by posva** [comment]
1. This is a vue-router issue
2. Look at the console. it's giving you a hint about how to fix the issue
3. It's a dup of https://github.com/vuejs/vue-router/issues/1281
