### ISSUE TITLE
Is it possible for template to accept raw sink and sources, so that component becomes a simple reactive circuit of observables

### ISSUE THREAD

**Issue by 3n-mb** [vuejs/vue#5841]
### What problem does this feature solve?
Cyclejs shows in its devtool how a chain of observables, a circuit, looks like, and it shows dynamics. This is very vivid.
There are two immediate problems it solves: (a) spotting bugs issues, (b) understanding of someone else's code becomes much simpler.

If vue is given directly sink for event, that become sources of user intents for component, and sources of values that either displayed or are used in v-if, v-for, classes, that come from component (model) as sinks of view-changing events.

Operations on streams should not be done in template. And whoever uses streams directly will get nice separation of logic and presentation, while being able to view logic dynamically in a cycle-like devtool.

### What does the proposed API look like?
Markdown editor example will look as follows.
Template
```html
<div id="editor">
  <textarea :value="input" @input="inputSteam"></textarea>
  <div v-html="compiledMarkdownStream"></div>
</div>
```
JS code:
```javascript
new VueStreams({
  el: '#editor',
  domEventStreams: {
    inputSteam: rxjs.Subject()
  },
  componentOutStreams: {
    compiledMarkdownStream: inputSteam
      .debounce(300)  
      .map(input => marked(this.input, { sanitize: true })),
  }
});
```

**Comment by 3n-mb** [comment]
May be cleaner JS code for stream:
```javascript
new VueStreams({
  el: '#editor',
  createStreams: function() {
    const inputSteam = rxjs.Subject();
    const compiledMarkdownStream: inputSteam
      .debounce(300)  
      .map(input => marked(this.input, { sanitize: true }));
    return {
      domEvents: { inputSteam },
      domChangeTriggers: { compiledMarkdownStream }
    };
  }
});
```

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-rx

**Comment by 3n-mb** [comment]
@yyx990803  Thank you. This looks perfect :smile:
