### ISSUE TITLE
The execution sequence of mixins

### ISSUE THREAD

**Issue by lzxb** [vuejs/vue#5849]
### What problem does this feature solve?
`This is the case now`
```javascript
{
  // ... options
  mixins: [
    computed: {
      test () {
        return 'ok'
      }
    }
  ],
  data () {
    console.log(this.test) // optput => undefined
    console.log(this.test2) // optput =>  undefined
    return {}
  },
  computed: {
    test2 () {
      return 'ok2'
    }
  }
}
```

### What does the proposed API look like?
```javascript
{
  // ... options
  mixins: [
    computed: {
      test () {
        return 'ok'
      }
    }
  ],
  data () {
    console.log(this.test) // optput => 'ok'
    console.log(this.test2) // optput => 'ok2'
    return {}
  },
  computed: {
    test2 () {
      return 'ok2'
    }
  }
}
```

**Comment by nickmessing** [comment]
@lzxb, why would you need to use computed properties for initial data?
IMO data is the schema for your component and should not use any data from side, I'd rather have `created()` to put data from side into `this.$data`

**Comment by lzxb** [comment]
Some special cases need to be like this

**Comment by lzxb** [comment]
If the calculated attribute is not data dependent, the requirement is accessible

**Comment by yyx990803** [comment]
This has nothing to do with mixins. It's about the order of `computed` vs. `data`, and the current behavior is expected because **it's way more often and reasonable for `computed` to depend on `data` than the other way around**. Also, this change would be breaking for no obvious gain.
