### ISSUE TITLE
about vuejs partial print

### ISSUE THREAD

**Issue by cyzeng-Luca** [vuejs/vue#5850]
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/while_own/ha94pag4/1/](https://jsfiddle.net/while_own/ha94pag4/1/)

### Steps to reproduce
first: i want to partial print what i want;
seconed: i recovery original code,but i find function is not effective like print button after printing;

### What is expected?
all function is effective

### What is actually happening?
not effective

---
i thing i destroy the observe model probably,but i'm not want to open a new window for printing because i don't  know when to close the print window or use ifream to print beause i wang to use vuejs grammar to generate html not join it

**Comment by yyx990803** [comment]
You cannot overwrite innerHTML like that, whenever you set `innerHTML` it throws away all the DOM nodes Vue was controlling. Previous HTML is also just a string and doesn't contain any data.

**Comment by SukantaBala28** [comment]
Hi Evan, Then what is the solution of this problem? Instead of, window.document.body.innerHTML what should be used??
Thanks in advance
