### ISSUE TITLE
style object update delay when use el arg check it  in update hook 

### ISSUE THREAD

**Issue by dxcqcv** [vuejs/vue#5858]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/39knLpv9/](https://jsfiddle.net/39knLpv9/)

### Steps to reproduce
I wanna get newest style value in el, code like

```
          vnode.context.$nextTick(()=>{
            console.log(el)
          })
```

### What is expected?
newest style object properties

### What is actually happening?
prev style object properties

---
how do I fix it？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
