### ISSUE TITLE
VueSSRClientPlugin 在client 打包时，如果client有多个entry 的话。工作不正常

### ISSUE THREAD

**Issue by xiachaoxulu** [vuejs/vue#5859]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
client打包有2个entry： A，B
A 有assets  a.js  a.css
B 有assets  b.js  b.css
client 打包时  配置了VueSSRClientPlugin
所以生存了 maifest.json
在 ssr 渲染时，配置了clientManifest：clientManifest

现在 vueServerRender.createBundleRenderer（inject:true）  了一个A 页面的bundleRender。 
但是html 里会有B entry 下的所有资源

### What is expected?
应该要区分多页面的ssr 的情况

### What is actually happening?
ssr

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. That's not a repro
Thanks!

**Comment by xiachaoxulu** [comment]
i have  already follow the issue guide.  above, ssrclientplugin can not work well in multi entrys

**Comment by xiachaoxulu** [comment]
please give me a  message

**Comment by posva** [comment]
Sorry, but we keep Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). If you find out there really is an issue, please  open a new issue but **with a repro**

**Comment by zwmmm** [comment]
这个问题你解决了么

**Comment by jery-Shen** [comment]
这个问题解决了没
