### ISSUE TITLE
Boolean values in custom data html attributes

### ISSUE THREAD

**Issue by Renol7** [vuejs/vue#5860]
### What problem does this feature solve?
When there is a html element with a custom data attribute like:
```
<div :data-opened="false">My content</div>
```
Vue renders it like:
```
<div>My content</div>
```
And I expect that it would be:
```
<div data-opened="false">My content</div>
```

Issue https://github.com/vuejs/vue/issues/2169 solves the problem with the other types of html attributes, but it is valid that **data- attributes can have any string value like "false" and "true"**.

### What does the proposed API look like?
I propose that custom data attributes could have any string value and boolean logic only will apply to the rest of html boolean attributes.

**Comment by posva** [comment]
If you really want to have the `false` string as the value you can just pass it as a string instead of a boolean. Booleans will toggle the attribute on the element because that's the most convenient in most cases

**Comment by Renol7** [comment]
I agree with your answer, thank you very much!
