### ISSUE TITLE
v-model does not work in slot

### ISSUE THREAD

**Issue by FQZhang** [vuejs/vue#5862]
### Version
2.3.4

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
1. change 'showModal' to true;
2. fill up 'group name';
3. click 'Save'

### What is expected?
list.name should have value

### What is actually happening?
list.name is empty

---
`<transition name="fade">`
`            <anc-modal v-show="showModal">`
`                <h3 slot="label">User Group</h3>`
`                <div slot="content">`
`                    <div class="row">`
`                        <div class="col-xs-12">`
`                            <div class="form-group">`
`                                <input type="text" class="form-control" id="group-name"`
`                                       placeholder="Group Name" v-model="list.name">{{list.name}}`
`                            </div>`
`                        </div>`
`                    </div>`
`                </div>`
`                <div slot="button">`
`                    <div class="row">`
`                        <div class="col-xs-3">`
`                            <a class="btn btn-success" @click="save()">Save</a>`
`                        </div>`
`                        <div class="col-xs-3 col-xs-offset-6">`
`                            <a class="btn btn-danger">Cancel</a>`
`                        </div>`
`                    </div>`
`                </div>`
`            </anc-modal>`
`        </transition>`
// js
`export default{`
`        data(){`
`            return{`
`                showModal: false,`
`                list: {name:'',create_at:'', status: true}`
`            }`
`        },`
 `      methods: {`
`            save() {`
`                let date = new Date();`
`                this.list.create_at = date.getDate() '-' date.getMonth() '-' date.getYear();`
`                console.log(this.list)`
`                axios.post('/api/list', this.list)`
`                    .then(() => {`
`                        this.lists.push(this.list);`
`                    })`
`         },`
`        components: {`
`            ancModal`
`        }`

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by yyx990803** [comment]
Sorry, but this is not a valid reproduction.
