### ISSUE TITLE
Array replacement "smart heuristics" not working when array is wrapped in object and defined in component's data function

### ISSUE THREAD

**Issue by ThomHurks** [vuejs/vue#5863]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/vabrnmzg/105/](https://jsfiddle.net/vabrnmzg/105/)

### Steps to reproduce
- I have an object that includes an array and some convenience methods. In this case it's used to store validation errors. (I originally encountered this issue using VeeValidate, but my reproduction is only Vue code)
- This error bag object is created in a child component's data function.
- The convenience method "remove" of the error bag uses array.prototype.filter() to create a new array that does not include the values that need to be removed. Then it assigns this array back to this.errors inside the error bag.
- The validation logic may cause "remove" to be called each time, which means that the this.errors array inside the error bag is replaced after each keystroke, when the validation runs.
- Vue has "smart heuristics" that make sure the entire DOM isn't re-rendered after array replacement, but they seem to fail here. The entire DOM is re-rendered after each key stroke!
- Normally you might not notice this, but the parent component is also using v-model.trim on the child component. So when the child is re-rendered, it of course uses the newly trimmed value. This prevents you from typing any spaces while using v-model.trim, if the child component has a text input or textarea.
- Important: this issue does *not* occur when the ErrorBag is created in the child component's created() callback, or when the "remove" method uses array.prototype.splice() instead in order to modify the errors array in-place.

### What is expected?
When using an (object wrapped) array, and you use one of the array functions that return a new array, causing your array to be replaced, the DOM should not completely re-render. Vue should be smart about this according to the documentation.

### What is actually happening?
- When using a (object wrapped) array, the array replacement heuristics should make sure that array replacement does not cause the entire DOM to re-render.
- The code that watches the array in-place modification methods such as push, splice etc seems to work fine, so a workaround is to not replace the array but use the in-place modification methods instead.
- Currently, the child component re-renders its DOM when the errors array is replaced, which can cause issues when a parent component is using v-model.trim, because this prevents any typing of spaces.
- When using in-place modification, Vue realises that a DOM re-render is not necessary when you, for example, cleared an already-empty errors array, and it will not re-render the DOM and then everything works fine.
- Strangely enough, when creating the ErrorBag (the wrapped array) in the component's created() callback, everything works as expected. When creating the ErrorBag in the component's data function, you cannot type any spaces.

**Comment by yyx990803** [comment]
Underneath this is not really about array replacement heuristics - when you replace an Array, it indeed should trigger an update, so that's expected behavior. The real cause if that you are putting the `validate()` call directly inside the `v-on:input` handler - which means the component is validated and updated on every input, even if the extra whitespace doesn't make the trimmed text change.

Instead, we can trigger `validate()` only when `text` actually changes by using a watcher. Fixed fiddle: https://jsfiddle.net/yyx990803/vabrnmzg/106/

**Comment by ThomHurks** [comment]
Thanks for your response @yyx990803!

I did intentionally make this code inefficient by making it re-validate after each input and the ```remove``` method is also called every time, even if the error bag is empty. The reason I did that is because in VeeValidate's code, something similar seems to be happening. Because of the array replacement, this caused the issue where you can't type spaces in a textarea in a component. I patched their code to use in-place array modification and that fixed it.

Do you know why the code *does* work when you create the ErrorBag in the ```created()``` callback, and why there is such a behaviour difference with in-place array modification? Is the component always supposed to update on array replacement, even when the array itself may contain the same values? If this is all as expected and by design, perhaps the documentation can suggest to be wary of array replacement a bit more?
