### ISSUE TITLE
close cmd error

### ISSUE THREAD

**Issue by acodercat** [vuejs/vue#5867]
Version
2.3.3

Reproduction link
https://github.com/vuejs/vue

Steps to reproduce
npm run dev以后，直接关掉cmd，当前目录下会有一个npm-debug.log报错日志，并且cmd窗口闪现报错信息后关闭,直接是官方的wabpack的例子也会报错，

What is expected?
关掉后不报错

What is actually happening?
0 info it worked if it ends with ok 1 verbose cli [ 'D:\Program Files\nodejs\node.exe', 1 verbose cli 'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js', 1 verbose cli 'run', 1 verbose cli 'dev' ] 2 info using npm@4.1.2 3 info using node@v7.7.3 4 verbose run-script [ 'predev', 'dev', 'postdev' ] 5 info lifecycle client@1.0.0predev: client@1.0.0 6 silly lifecycle client@1.0.0predev: no script for predev, continuing 7 info lifecycle client@1.0.0dev: client@1.0.0 8 verbose lifecycle client@1.0.0dev: unsafe-perm in lifecycle true 9 verbose lifecycle client@1.0.0dev: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Cat\Desktop\vue\agro_lot\node_modules.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Python27;D:\Program Files\Python27\Scripts;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;D:\Program Files\Java\jdk1.7.0_79\bin;D:\wamp\bin\php\php5.5.12;D:\Program Files\curl;D:\Program Files\PuTTY;D:\Program Files\TortoiseSVN\bin;C:\Oracle\product\11.2.0\client_lite\bin;D:\Program Files\MongoDB\Server\3.2\bin;D:\Program Files\Redis;C:\Users\Cat\AppData\Roaming\npm;D:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;D:\Program Files\python35;D:\Program Files\python35\Scripts;D:\Program Files\nodejs;D:\Program Files\Yarn\bin;d:\Program Files\Microsoft VS Code\bin;C:\Users\Cat\AppData\Roaming\Composer\vendor\bin;C:\Users\Cat\AppData\Roaming\npm;C:\Users\Cat\AppData\Local\Yarn\bin 10 verbose lifecycle client@1.0.0dev: CWD: C:\Users\Cat\Desktop\vue\agro_lot 11 silly lifecycle client@1.0.0dev: Args: [ '/d /s /c', 'node build/dev-server.js' ] 12 silly lifecycle client@1.0.0dev: Returned: code: 3221225786 signal: null 13 info lifecycle client@1.0.0~dev: Failed to exec dev script 14 verbose stack Error: client@1.0.0 dev: node build/dev-server.js 14 verbose stack Exit status 3221225786 14 verbose stack at EventEmitter. (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16) 14 verbose stack at emitTwo (events.js:106:13) 14 verbose stack at EventEmitter.emit (events.js:194:7) 14 verbose stack at ChildProcess. (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14) 14 verbose stack at emitTwo (events.js:106:13) 14 verbose stack at ChildProcess.emit (events.js:194:7) 14 verbose stack at maybeClose (internal/child_process.js:899:16) 14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 15 verbose pkgid client@1.0.0 16 verbose cwd C:\Users\Cat\Desktop\vue\agro_lot 17 error Windows_NT 10.0.14393 18 error argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev" 19 error node v7.7.3 20 error npm v4.1.2 21 error code ELIFECYCLE 22 error client@1.0.0 dev: node build/dev-server.js 22 error Exit status 3221225786 23 error Failed at the client@1.0.0 dev script 'node build/dev-server.js'. 23 error Make sure you have the latest version of node.js and npm installed. 23 error If you do, this is most likely a problem with the client package, 23 error not with npm itself. 23 error Tell the author that this fails on your system: 23 error node build/dev-server.js 23 error You can get information on how to open an issue for this project with: 23 error npm bugs client 23 error Or if that isn't available, you can get their info via: 23 error npm owner ls client 23 error There is likely additional logging output above. 24 verbose exit [ 1, true ]

0 info it worked if it ends with ok 1 verbose cli [ 'D:\Program Files\nodejs\node.exe', 1 verbose cli 'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js', 1 verbose cli 'run', 1 verbose cli 'dev' ] 2 info using npm@4.1.2 3 info using node@v7.7.3 4 verbose run-script [ 'predev', 'dev', 'postdev' ] 5 info lifecycle client@1.0.0predev: client@1.0.0 6 silly lifecycle client@1.0.0predev: no script for predev, continuing 7 info lifecycle client@1.0.0dev: client@1.0.0 8 verbose lifecycle client@1.0.0dev: unsafe-perm in lifecycle true 9 verbose lifecycle client@1.0.0dev: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Cat\Desktop\vue\agro_lot\node_modules.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Python27;D:\Program Files\Python27\Scripts;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;D:\Program Files\Java\jdk1.7.0_79\bin;D:\wamp\bin\php\php5.5.12;D:\Program Files\curl;D:\Program Files\PuTTY;D:\Program Files\TortoiseSVN\bin;C:\Oracle\product\11.2.0\client_lite\bin;D:\Program Files\MongoDB\Server\3.2\bin;D:\Program Files\Redis;C:\Users\Cat\AppData\Roaming\npm;D:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;D:\Program Files\python35;D:\Program Files\python35\Scripts;D:\Program Files\nodejs;D:\Program Files\Yarn\bin;d:\Program Files\Microsoft VS Code\bin;C:\Users\Cat\AppData\Roaming\Composer\vendor\bin;C:\Users\Cat\AppData\Roaming\npm;C:\Users\Cat\AppData\Local\Yarn\bin 10 verbose lifecycle client@1.0.0dev: CWD: C:\Users\Cat\Desktop\vue\agro_lot 11 silly lifecycle client@1.0.0dev: Args: [ '/d /s /c', 'node build/dev-server.js' ] 12 silly lifecycle client@1.0.0dev: Returned: code: 3221225786 signal: null 13 info lifecycle client@1.0.0~dev: Failed to exec dev script 14 verbose stack Error: client@1.0.0 dev: node build/dev-server.js 14 verbose stack Exit status 3221225786 14 verbose stack at EventEmitter. (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16) 14 verbose stack at emitTwo (events.js:106:13) 14 verbose stack at EventEmitter.emit (events.js:194:7) 14 verbose stack at ChildProcess. (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14) 14 verbose stack at emitTwo (events.js:106:13) 14 verbose stack at ChildProcess.emit (events.js:194:7) 14 verbose stack at maybeClose (internal/child_process.js:899:16) 14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 15 verbose pkgid client@1.0.0 16 verbose cwd C:\Users\Cat\Desktop\vue\agro_lot 17 error Windows_NT 10.0.14393 18 error argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev" 19 error node v7.7.3 20 error npm v4.1.2 21 error code ELIFECYCLE 22 error client@1.0.0 dev: node build/dev-server.js 22 error Exit status 3221225786 23 error Failed at the client@1.0.0 dev script 'node build/dev-server.js'. 23 error Make sure you have the latest version of node.js and npm installed. 23 error If you do, this is most likely a problem with the client package, 23 error not with npm itself. 23 error Tell the author that this fails on your system: 23 error node build/dev-server.js 23 error You can get information on how to open an issue for this project with: 23 error npm bugs client 23 error Or if that isn't available, you can get their info via: 23 error npm owner ls client 23 error There is likely additional logging output above. 24 verbose exit [ 1, true ]

**Comment by yyx990803** [comment]
1. 这个 issue 应该发到你使用的 cli 模板的仓库
2. 贴错误日志的时候请用 markdown 格式化，这种全堆在一起的 log 根本没法看。
3. 重现的链接请不要随便乱贴一个
