### ISSUE TITLE
Expose createTextVNode() 's functionality in the API

### ISSUE THREAD

**Issue by green-coder** [vuejs/vue#5870]
### What problem does this feature solve?
In the Vue Component's `render()` function, there is no normal way to create a VNode which represents naked text, same as what `createTextVNode()` would create.

This is needed when we want to generate things like:
```
<div>
  Hello <strong>Vue</strong>'s world.
</div>
```

### What does the proposed API look like?
I propose to change the API in one of those 2 ways:

1. Add a behavior to the `h` function which is given to the user in the `render()` function so that it can be used for creating a 'text VNode', and document it. I propose to use the null or undefined on the first parameter.

2. Expose the `createTextVNode()` function (and why not also `VNode()`) somewhere inside Vue.

**Comment by green-coder** [comment]
Known 'hacky' workarounds:

1. Use a non-documented compiler method

```
render (h) {
  return this._v(val)
}
```

2. Use a poorly-documented method behavior's partial result.

```
render (h) {
  return h('p', val).children[0] // Works, but wastes CPU.
}
```

**Comment by yyx990803** [comment]
You can just provide raw text:

``` js
return h('div', [
  'Hello ',
  h('strong', 'Vue'),
  '\'s world.'
])
```

**Comment by green-coder** [comment]
That worked, thank you a lot.

You may want to add this information to documentation at https://vuejs.org/v2/guide/render-function.html#createElement-Arguments

**Comment by posva** [comment]
@green-coder that would be great, could you make a pr to https://github.com/vuejs/vuejs.org ?
