### ISSUE TITLE
A页面跳转到login的时候我在beforeEnter里面判断了本地是否有token，如果有的话，就next到from.fullPath，但是这样做NProgress就卡住，一直转了

### ISSUE THREAD

**Issue by acodercat** [vuejs/vue#5872]
### What problem does this feature solve?
A页面跳转到login的时候我在beforeEnter里面判断了本地是否有token，如果有的话，就next到from.fullPath，但是这样做NProgress就卡住，一直转了

### What does the proposed API look like?
```javascript

 path: '/login',
    name: 'login',
    component: login,
    beforeEnter(to, from, next) {
      if (localStorage.getItem('token')) {
        next(from.fullPath)
      } else {
        next()
      }
    }
```
```javascript

router.beforeEach((to, from, next) => {
  NProgress.start()
  next()
})
router.afterEach(() => {
  NProgress.done()
})
```

**Comment by acodercat** [comment]
发现只要 next到原来的路径就会卡住，换个有可以，这是怎么回事呢

**Comment by scopewu** [comment]
你可以阅读文档 https://router.vuejs.org/zh-cn/advanced/navigation-guards.html
@acodercat

**Comment by acodercat** [comment]
文档说next('/') 或者 next({ path: '/' }): 跳转到一个不同的地址。但是我的需求就是next到之前的地址，请问这种需求怎么解决呢，谢谢

**Comment by acodercat** [comment]
是不是直接在login组件里面进行判断，或者是在beforeEnter里用route.push跳走

**Comment by acodercat** [comment]
我这样做了，就可以
```javascript
next()
router.push(from.fullPath)```

**Comment by acodercat** [comment]
可以这样做吗？还有其他办法吗

**Comment by acodercat** [comment]
```javascript
 beforeEnter(to, from, next) {
      if (localStorage.getItem('token')) {
        next()
        router.push(from.fullPath)
      } else {
        next()
      }
    }
```

**Comment by acodercat** [comment]
编码强迫症，望大神相告，感谢

**Comment by acodercat** [comment]
群里很多人，在这块都没搞清楚，next到自身和直接在beforeEnter里面router.push不调用next，会导致afterEach不执行。

**Comment by posva** [comment]
I really don't understand what feature is missing here but this is definitely not vue, but rather vue-router. Your issue looks more like an usage question. You should ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
