### ISSUE TITLE
support transition classes as they are normal classes

### ISSUE THREAD

**Issue by SeregPie** [vuejs/vue#5874]
### What problem does this feature solve?
For now you are stuck with one computed class. It would make code cleaner, if transition class syntax were as powerful as normal class syntax.
I mean array syntax, object syntax, direct javascript and a mix of binded and static classes.

### What does the proposed API look like?
```html

<transition
    leave-active-class="animated"
    enter-active-class="animated position-absolute"
    :leave-active-class="currentIndex > previousIndex ? 'fadeOutLeft' : 'fadeOutRight'"
    :enter-active-class="currentIndex > previousIndex ? 'fadeInRight' : 'fadeInLeft'"
>
    <component
        :is="views[currentIndex].component"
        :key="views[currentIndex].key"
        v-bind="views[currentIndex].props"
    ></component>
</transition>

```

**Comment by posva** [comment]
A transition is only represented by one CSS class, why would you need multiple classes to be applied during the transition?

FYI ` :leave-active-class="currentIndex > previousIndex ? 'fadeOutLeft' : 'fadeOutRight'"` works already

**Comment by SeregPie** [comment]
As you see in example, sometimes you need to append two classes: `animated` and `fadeOut`.

In UIkit for example, you need to append an class  `uk-animation-reverse` to  reverse the animation.

If you want swap multiple components, you will need to append a class to a leaving or an entering component to make him position absolute over another component during the animation.

**Comment by posva** [comment]
But you don't need to add those classes as the `*-*-class`, you can add them as direct classes as they modify the behaviour of the transition. You can even use the array and object syntax there

**Comment by Akryum** [comment]
```html

<transition
    leave-active-class="animated"
    enter-active-class="animated position-absolute"
>
    <component
        :is="views[currentIndex].component"
        :key="views[currentIndex].key"
        v-bind="views[currentIndex].props"
        :class="currentIndex > previousIndex ? ['fadeOutLeft', 'fadeInRight'] : ['fadeOutRight', 'fadeInLeft']"
    ></component>
</transition>

```

**Comment by SeregPie** [comment]
I don't need those classes, when the transition is over.

This would be a nice feature to have. Until then I'm stuck with this. Which is fine too.

```html

<transition
    :leave-active-class="['animated', currentIndex > previousIndex ? 'fadeOutLeft' : 'fadeOutRight'].join(' ')"
    :enter-active-class="['animated', currentIndex > previousIndex ? 'fadeInRight' : 'fadeInLeft', 'position-absolute'].join(' ')"
>
    ...
</transition>

```
