### ISSUE TITLE
@click.prevent also prevents all child elements interactions

### ISSUE THREAD

**Issue by gerardreches** [vuejs/vue#5875]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/39994/](https://jsfiddle.net/50wL7mdz/39994/)

### Steps to reproduce
1. Click on the link, it will be prevented.
2. Try to open the input file, it will be prevented too.

### What is expected?
The element with `@click.prevent` will be prevented, child elements with default actions shouldn't be prevented.

### What is actually happening?
The element with `@click.prevent` is prevented, child elements with default actions prevented too.

---
I want to use elements with default actions inside a parent element that uses `@click.prevent`. `@click.prevent.self` doesn't help either.

**Comment by JounQin** [comment]
try `@click.self.prevent`

**Comment by posva** [comment]
you have to add self before the prevent as @JounQin said

**Comment by posva** [comment]
I'm creating a PR for the docs. Thanks for the feedback 🙂

**Comment by duyphamsalto** [comment]
Vue JS too bullshit
