### ISSUE TITLE
Accessing props in attributes of HTML elements

### ISSUE THREAD

**Issue by codewp** [vuejs/vue#5876]
### Version
2.3.4

### Reproduction link
[http://jsfiddle.net/k8mu1vhx/49/](http://jsfiddle.net/k8mu1vhx/49/)

### Steps to reproduce
Run above JSFiddle and you can see output in browser developer view.

### What is expected?
expected output in browser is :
`<div id="something"> something, Chris</div>`

### What is actually happening?
`<div id="{{greeting}}"> something, Chris</div>`

---
As you can see in above examples vue can not use props in attributes of HTML elements, and it set's id="{{greeting}}" instead of setting it to id="something".

I changed version of Vue to version 1 and it worked properly.

**Comment by posva** [comment]
in Vue 2, `{{}}` is for text interpolation only. Use `v-bind` instead
I recommend you to read the guide 😉 https://vuejs.org/guide
