### ISSUE TITLE
Multiple selectors of Vue Instance

### ISSUE THREAD

**Issue by lucas-viewup** [vuejs/vue#5877]
### What problem does this feature solve?
It would solve VueJS conflicts with Google Maps and Recaptcha.Sometimes, you can't have a vue container that wrap the whole site in one div, because for example, some plugins of Wordpress use the tag script besides the html template of them (inside of vue container) and vue doesn't allow that.

### What does the proposed API look like?
https://codepen.io/lucasviewup/pen/qjNyvw
the proposal is: allow vue to have multiple "islands" in the webpage

**Comment by yyx990803** [comment]
Unfortunately this is not possible given the way Vue's template compilation / rendering works. You can, however, mount multiple Vue instances that share the same data object.
