### ISSUE TITLE
Warn when using an arrow function in `data`

### ISSUE THREAD

**Issue by zatziky** [vuejs/vue#5878]
### What problem does this feature solve?
In our team we sometimes forget that `data` of a `Vue` instance must be declared as an ordinary function and not an arrow function (as described in https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function). 

This declaration causes an unexpected behavior that takes some time to debug.

```
new Vue({
   data: () => { ... } // instead of `data() { ... }`
})
```

### What does the proposed API look like?
Not an API request but a simple warning in the browser console would be helpful.

**Comment by posva** [comment]
Using an arrow function for the data can actually be a good idea because it makes it readable and forces you to just build a state object:

```js
{
  data: () => ({
    foo: 'foo'
  })
}
```
Therefore we cannot really warn against this. Also note we don't say it's bad to use arrow functions for the `data` in the docs

**Comment by yyx990803** [comment]
FYI this cannot be detected at runtime because you cannot tell whether a function is authored as an arrow function or not. It can only be done via static analysis (we probably will have a rule for this in the WIP official ESLint plugin)
