### ISSUE TITLE
key attribute set by `v-bind="obj"` is ignored by transition-group

### ISSUE THREAD

**Issue by Nirazul** [vuejs/vue#5881]
### Version
2.3.4

### Reproduction link
[https://codepen.io/Nirazul/pen/RgGRjm](https://codepen.io/Nirazul/pen/RgGRjm)

### Steps to reproduce
1. Click on the trigger button
2. There is only one list visible instead of two

### What is expected?
According to the [documentation](https://vuejs.org/v2/api/#key) I was expecting that I can use the v-bind object notation to set the key attribute.

### What is actually happening?
The list is not rendered when the `key` attribute is not directly present on the element.

---
I'm aware that `key` is a special attribute and that there may be some sort of "hen and egg" problem at work when rendering items in a transition-group.
If the behaviour is intentional, there's maybe some space for improvement in the documentation.

**Comment by yyx990803** [comment]
Yeah, we should improve the docs regarding the special case for key. In fact all [reserved attributes](https://vuejs.org/v2/api/#Special-Attributes) cannot be bound using `v-bind` object syntax.

/cc @chrisvfritz

**Comment by gebilaoxiong** [comment]
... I'm fixing it

**Comment by yyx990803** [comment]
@gebilaoxiong ah, I realized it should indeed be fixable. Just check for the special keys in https://github.com/vuejs/vue/blob/dev/src/core/instance/render-helpers/bind-object-props.js

**Comment by gebilaoxiong** [comment]
@yyx990803 

OK, boss
