### ISSUE TITLE
render function can't correct rendering DOM

### ISSUE THREAD

**Issue by pastry-2841** [vuejs/vue#5885]
### Reproduction link
[https://jsfiddle.net/50wL7mdz/40335/](https://jsfiddle.net/50wL7mdz/40335/)

### Steps to reproduce
run my code

### What is expected?
rendered dom should be `<div><span>1<br>2<span></div>` after 3s

### What is actually happening?
`<div><span>12<span><br></div>` after 3s

**Comment by yyx990803** [comment]
Incorrect usage: **do not reuse VNodes.** You should alway create fresh VNodes for each render.
