### ISSUE TITLE
keep-alive component (or other abstract component) ignores slot name

### ISSUE THREAD

**Issue by wonderful-panda** [vuejs/vue#5888]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/f055yu68/](https://jsfiddle.net/f055yu68/)

### Steps to reproduce
Just open reproduction link

### What is expected?
"foo-content" is shown at foo slot.

```
default-slot :  ???
foo-slot : foo content
```

### What is actually happening?
"foo-content" is shown at default slot.
`slot="foo"` specification is just ignored

```
default-slot : foo content 
foo-slot : ???
```

---
slot name is stored in `data`, and lost at this line.

https://github.com/vuejs/vue/blob/9cf6646f46ef3c13236677e58e72d2c6dd5c8abf/src/core/vdom/create-component.js#L171

Is this an intentional behaviour ?

**Comment by Oscar-ren** [comment]
hi, same the condition, what about scopedSlots?

here is the demo: https://jsfiddle.net/anyvh33j/

could append the scopedSlots in the abstract component?

thanks
