### ISSUE TITLE
v-for to support Array-like objects

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#5893]
### What problem does this feature solve?
Allow iterating over smart Arrays that extend/inherit the Array (instance of the Array) or something like arguments (not an instance of the Array).

### What does the proposed API look like?
No change in API

**Comment by yyx990803** [comment]
I don't think we can support arbitrary Array-like objects - the line between a actual "object" vs. "array-like" is blurry. We will stick to `Array.isArray` in this case.  But we can and should support Array subclasses.

**Comment by nickmessing** [comment]
Offtopic: @yyx990803, I've seen in some discussion that you didn't want to switch to proxies for reactivity because it creates a new object instead of editing the initial one, what has changed?

**Comment by hirokiosame** [comment]
@yyx990803 Sounds good. Thanks.

BTW, all that seems to be necessary to qualify interpreting an object as an array (logging it with square brackets) in V8 seems to be a numerical `index` and a function in `splice`: `({ length: 0, splice(){} })`

**Comment by nickmessing** [comment]
As an alternative we could use iterator protocol which works with way more iterable structures than just array and array-likes (`Map`, `Set`, `Iterator`)

**Comment by yyx990803** [comment]
@nickmessing that difference is still there so it will introduce some breaking changes, also the compatibility means we will only do it for v3.

**Comment by nickmessing** [comment]
OFFTOPIC: @yyx990803, if that is already a plan maybe it's a nice idea to have a v3 discussion issue about possible breaking/browser compatibility changes?

**Comment by yyx990803** [comment]
@nickmessing currently the only planned change in v3 is the reactivity system and browser compatibility (dropping IE for only evergreen browsers). The breaking changes would be minimal (only in terms of observed object equality) and the API will remain the same.

**Comment by nickmessing** [comment]
@yyx990803, what about using `v-for` for `Map` and `Set`? I've seen people asking that once in a while. If support of old browsers is gone then `Symbol.iterator` with `for of` is available everywhere.

**Comment by yyx990803** [comment]
@nickmessing yup, those will also be supported in v3.

**Comment by hirokiosame** [comment]
Just to clarify, I don't believe subclassing the Array is a ES6+ feature. What if I just inherit it ES5 style?
```
function Collection () {
     Array.apply(this);
}

Collection.prototype = Object.create(Array.prototype);

Object.assign(Collection.prototype, {
   ...methods
});
```

**Comment by yyx990803** [comment]
That's not true subclassing - see [this](http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/) for more details. Only ES6+ supports something like `class Collection extends Array {}`.

**Comment by mitar** [comment]
What about support for [objects defining iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)? So instead of relaying on inheritance, we could check if an object defines an iterator and then use that to iterate? This would probably not break backwards compatibility and could be done already now.

**Comment by nickmessing** [comment]
@mitar, as @yyx990803 said few comments ago, v-for will be using `Symbol.iterator` in v3 when we drop support for old browsers. Actual implementation works differently and I don't think it's a good idea to support "new" iteration while we support IE9+.

**Comment by mitar** [comment]
Just for reference, [this is how I implemented support for iterators](https://github.com/meteor-vue/vue/commit/06510255efafeb4d111c887492de6970b11e562f) in Meteor's Vue fork. I do not see it breaking anything if it would be already implemented in v2, but this is your call.

**Comment by nickmessing** [comment]
@mitar, why not `for of`?

That's Evan's call and looks like he decided that to be a part of v3, from my point of view if we support IE9+ we should not have code that will work only in newer browsers.

**Comment by mitar** [comment]
Hm, good question. I don't know if existing Vue code uses `for of`, so I just didn't want to use it myself.

**Comment by mrliptontea** [comment]
Iteration protocol does not ensure that iterator can be rewound (like generators), which means it will break when render function is called again. Also, array-likes generally don't simply read values from memory but do some extra work which shouldn't be repeated on each render.

That being said I don't think you would need to be able to iterate through array-like or custom object directly. Instead, you need array representation of underlying values (e. g. in a computed property), which will always be a native Array. Or possibly other built-in iterable, when they're supported.

**Comment by mitar** [comment]
> Iteration protocol does not ensure that iterator can be rewound (like generators)

But you can obtain a new iterator object when you want to iterate again?

```
const iterator = arrayLike[Symbol.iterator]();
```

And then you iterate. And you can call this as many times as you want. The same happens if you do not manually obtain an iterator, but use JS syntax.

**Comment by yyx990803** [comment]
Closing (lack of actionable items before v3)
