### ISSUE TITLE
是否官方来维护 `@types/vue` 呢，现在不是最新，需要安装整个 `vue`

### ISSUE THREAD

**Issue by tcdona** [vuejs/vue#5894]
### What problem does this feature solve?
`npm i @types/vue` 能获取最新的 d.ts 文件，而不需要安装整个 `npm i vue`

### What does the proposed API look like?
`npm i @types/vue`

**Comment by yyx990803** [comment]
为什么不直接安装 vue?

**Comment by tcdona** [comment]
sorry 我描述不清晰，尝试补上，其实我现在就是直接安装 vue 使用，这没啥问题，
其实是有这样另外一个问题的场景：
`
/**
 * @type {JQueryStatic}
 */
var $ = require('../lib/jquery.min.js')
$('dsfsdf').xxx
`
这里可以提示 jQuery lodash 也试过可以了

vue 的 d.ts 由于按模块输出的 vue ，所以我应该如何做到同样的提示呢？
我使用的是 `vue.min.js` 这样一个[特殊]的方式，不是 `npm_modules`

期待的场景：
`/**
 * @type {Vue}
 */
var V = require('../lib/vue.min.js')
var vi = new Vue({
//
})
vi.xxx
`

其实我郁闷的是，npm安装方式固然主流，直接使用一个相对路径的文件，感觉不该有什么问题呀！

**Comment by yyx990803** [comment]
@types 并不是我们维护的，如果我们去管会增加维护成本。如果除了『感觉好一点』之外没有什么实际的收益，就不予考虑了。

路径的问题，用模块 alias 来处理会比较好。
