### ISSUE TITLE
ssr directive access to dom

### ISSUE THREAD

**Issue by adwaer** [vuejs/vue#5898]
### What problem does this feature solve?
i want to prerender text resources.

### What does the proposed API look like?
ssr: {
      directives: {
        textresource: function (vnode, directiveMeta) {

          let binding = directiveMeta.value;
          if (typeof binding != "object") {
            return;
          }

          let text = vnode.context.$store.state.texts.keyValueArr[binding.group][binding.tag];
          if(<<binding.targetTag>>) {
			<<vnode.$el[>>binding.targetTag<<]>> = text
          } else {
			<<vnode.$el.innerText>> = text;
		  }

        }
      },
    }

**Comment by yyx990803** [comment]
SSR directives can only perform vnode data manipulations, there's no way to access DOM nodes because no DOM is ever created. What you need to do is modifying `vnode.data.domProps`.
