### ISSUE TITLE
ref with component list is not updated when using splice to swap elements

### ISSUE THREAD

**Issue by DreaminginCodeZH** [vuejs/vue#5899]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/bgees5og/](https://jsfiddle.net/bgees5og/)

### Steps to reproduce
- Open https://jsfiddle.net/bgees5og/ .
- Run and click the 0, 1, 2, 3 s to swap the components down.
- Confirm that ref is not updated.

### What is expected?
ref should be updated, because :key is supplied so components are really being swapped.

### What is actually happening?
ref is not updated.

**Comment by posva** [comment]
Refs do not guarantee order. See #4952
