### ISSUE TITLE
Transition mode is not honored with conditionally rendered elements

### ISSUE THREAD

**Issue by kenfred** [vuejs/vue#5900]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/y3oc20vs/1/](https://jsfiddle.net/y3oc20vs/1/)

### Steps to reproduce
Create a list of elements conditionally rendered based on a current index, within a transition group. Set the transition-group mode to "out-in" and exercise the transition. (See jsfiddle for code).

Compare that against a dynamic component whose template changes based on the current index.

### What is expected?
The conditional list of components should honor the "out-in" mode: the transition of the currently active element should finish before the transition of the next element begins.

The behavior should be the same as the dynamic component case.

### What is actually happening?
The "out-in" mode is ignored for the conditional list of elements and the transitions for the current and next elements happen simultaneously.

However, "out-in" behaves as expected for the dynamic component.

**Comment by yyx990803** [comment]
FYI `<transition-group>` does **not** support the `mode` prop.

**Comment by kenfred** [comment]
Thanks! I'll elevate this to a feature-request.

In general, I'd expect `transition-group` to have consistent behavior with `transition` on dynamic components, including being able to wrap multiple conditionally rendered elements (declared explicitly or with `v-for`).

**Comment by yyx990803** [comment]
There is already #3974 - however, it's unlikely to happen anytime soon due to the complexity involved.

**Comment by kenfred** [comment]
Good to know. Thanks!
