### ISSUE TITLE
windows.onerror is not working

### ISSUE THREAD

**Issue by atajadod** [vuejs/vue#5901]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/40803/](https://jsfiddle.net/50wL7mdz/40803/)

### Steps to reproduce
Create a global error handler, something like this:
window.onerror = function (e) {
    alert("Error caught");
};
inside a function of your vue methods, throw an exception. for example 
throw "hello!";

### What is expected?
alert box to be shown.

### What is actually happening?
nothing. it seems Vue silence the error.

---
I want to use this to have a centralized error handling mechanism for user generated errors.

**Comment by yyx990803** [comment]
Use `Vue.config.errorHandler`.

**Comment by atajadod** [comment]
Vue.Config.errorHandler don't work. I have already tested that.

As stated in the docs, this handle only catches errors during render:
> If a runtime error occurs during a component’s render, it will be passed to the global Vue.config.errorHandler config function if it has been set.

**Comment by yyx990803** [comment]
https://jsfiddle.net/50wL7mdz/40809/

**Comment by atajadod** [comment]
thanks yyx990803. 
I made it work in jsFiddle (order seems to be important), but I am not able to make it work on my project! I am using components heavily (SPA) and it doesn't work when the error comes from components!! I will update this post when I could pinpoint the issue.

**Comment by krimeshu** [comment]
The same problem, not working on components.

**Comment by codingfriend1** [comment]
The Vue.config.errorHandler is not catching errors inside of methods run after render. 

https://jsfiddle.net/50wL7mdz/40803/

If you have a button that throws an error when you call a method Vue.config.errorHandler won't catch it and neither will windows.onerror

**Comment by frontEnd-fucker** [comment]
@codingfriend1 the same problem. have you figure it out?

**Comment by codingfriend1** [comment]
No I haven't.

**Comment by hstarorg** [comment]
Use the `errorHandler` and `window.onerror` should catch all the errors.

**Comment by ianwalter** [comment]
You have to set both `window.onerror` and `Vue.config.errorHandler`? `throw 'strange'` indeed!

**Comment by zhaoqize** [comment]
`window.onerror` not work,vue version 2.5.13

**Comment by miser** [comment]
@zhaoqize I same question. Can U find where is the problem?

**Comment by wcjr** [comment]
@hstarorg , your example is not working...

**Comment by A1rPun** [comment]
@wcjr The example is working, check the console. [Updated fiddle](https://jsfiddle.net/ebo4d5xn/).
`Vue.config.errorHandler` is all you need, if you execute js code outside of Vue (for any reason) you can use the native `window.onerror`.

**Comment by wcjr** [comment]
yep, I see both alerts getting thrown now, I presume it had something to do with changes in 2.6 maybe?  Thanks for the heads-up @A1rPun

**Comment by cadenzah** [comment]
Still not resolved, any solution or update?

**Comment by leegee** [comment]
> @wcjr The example is working, check the console. [Updated fiddle](https://jsfiddle.net/ebo4d5xn/). `Vue.config.errorHandler` is all you need, if you execute js code outside of Vue (for any reason) you can use the native `window.onerror`.

The example is *not* working (latest Chromium): check the console.

**Comment by leegee** [comment]
Seems the Vue3 error handler consider `unhandledrejection` an error?

**Comment by leegee** [comment]
Seems Vue3 does not consider `unhandledrejection` an error, right?

**Comment by LinusBorg** [comment]
Not sure what you are referring to. the fiddle you claim doesn't work - *does* work (provided you make sure it uses Vue 2, as it was written for Vue 2 but the unpkg link now resolves to 3) - I don't get any errors in the console.

See here: https://jsfiddle.net/Linusborg/gqovLc9f/

Now, if you mean you tried this example in Vue 3: https://jsfiddle.net/Linusborg/h7085ypw/

**Comment by VonNeuwomann** [comment]
This might be caused by CORS, Please refer to this post,  https://catchjs.com/Docs/Vue
> Also, be aware that errors thrown in scripts loaded from another origin will only show up as "Script error.", unless you [take care to set up CORS](https://catchjs.com/Docs/ScriptError).

**Comment by hstarorg** [comment]
> @hstarorg , your example is not working...

Because vue has new version. I updated the example, see: https://jsfiddle.net/v9ru15m6/1/
