### ISSUE TITLE
Created / Mounted not called when component is inside v-else

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#5903]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/fergal_doyle/z241z72y/](https://jsfiddle.net/fergal_doyle/z241z72y/)

### Steps to reproduce
From what I can tell, there seems to be some caching of components within `v-if` blocks if the element structure if mirrored. E.g. if you have the following template, the issue is present in `icon[name=one]` and `icon[name=two]` because they have the same html structure while  `icon[name=three]` works as expected.
```
  <div v-if="isActive">
    <div class="someclass">
      <span>
        <icon name="one"></icon>
      </span>
    </div>
  </div>
  <div v-else>
    <div class="someclass">
      <span>
        <icon name="two"></icon>
      </span>
    </div>
    <icon name="three"></icon>
  </div>
```

Follow reproduction, open console, click on the Toggle isActive button

### What is expected?
When `isActive` is `true`,  `created` and `mounted` should be called within `<icon name="one">`

When `isActive` is `false`,  `created` and `mounted` should be called within `<icon name="two">` and `<icon name="three">`

### What is actually happening?
`created` / `mounted` is called within `<icon name="one">` on initial load

When `isActive` is set to `false`, only `<icon name="three">` has `created` / `mounted` called

When `isActive` is set back to `true`, nothing.

When `isActive` is set back to `false`, only `<icon name="three">` has `created` / `mounted` called

**Comment by yyx990803** [comment]
Because they are in the exact same position in the two toggled trees, they are reused instead of recreated. If you want to force remount, give them different keys: https://jsfiddle.net/3dLL5yur/
