### ISSUE TITLE
Bug with render function: img src not being used

### ISSUE THREAD

**Issue by adrianhelvik** [vuejs/vue#5905]
### Version
2.3.4

### Reproduction link
[https://codepen.io/adrianhelvik/pen/XgpewJ](https://codepen.io/adrianhelvik/pen/XgpewJ)

### Steps to reproduce
No steps. The src attribute is not included in the DOM.

### What is expected?
The src attribute should be included and the Vue logo should be visible.

### What is actually happening?
The src attribute is not included and the logo is thus not visible.

---
This also happened with the width/height attributes.

**Comment by donnysim** [comment]
Shouldn't it be `attrs: {src: 'https://vuejs.org/images/logo.png'},` ?

**Comment by yyx990803** [comment]
Only `style` and `class` has special top-level treatment. Other attrs needs to be nested under `attrs` or `domProps` as @donnysim pointed out: https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

**Comment by davestewart** [comment]
This just got me too!
