### ISSUE TITLE
Transition not working in Chrome version 60

### ISSUE THREAD

**Issue by jety91** [vuejs/vue#5906]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/5jd48xr9/](https://jsfiddle.net/5jd48xr9/)

### Steps to reproduce
- Install the Chrome beta 60.0.3112.24
- Visit the official Vue transition documentation example (https://vuejs.org/v2/guide/transitions.html) or the jsfiddle link
- Click on the toggle button

### What is expected?
The "hello" message is appears and disappears in 0.5s when we use the fade transition.

### What is actually happening?
The "hello" message is appears and disappears instantly

**Comment by Kingwl** [comment]
I tried it in version 60.0.3112.32
it looks like it is normal

**Comment by posva** [comment]
Thanks for reporting this but a beta may contain bugs and we cannot assure Vue will work with unstable releases. You may want to open a ticket on their side though.
