### ISSUE TITLE
在360浏览器下IE兼容模式使用vue.min.js,报错InvalidCharacterError vue.min.js(6, 26429);

### ISSUE THREAD

**Issue by dfggking** [vuejs/vue#5910]
### Version
2.0.5

### Reproduction link
[https://github.com/dfggking](https://github.com/dfggking)

### Steps to reproduce
1324

### What is expected?
no error

### What is actually happening?
,报错InvalidCharacterError

**Comment by gebilaoxiong** [comment]
你好，非常感谢你提交的问题

相关解答请查看: https://cn.vuejs.org/v2/guide/installation.html

> Vue.js 不支持 IE8 及其以下版本，因为 Vue.js 使用了 IE8 不能模拟的 ECMAScript 5 特性。 Vue.js 支持所有兼容 ECMAScript 5 的浏览器。

**Comment by dfggking** [comment]
感谢laoxiong的回复！！
