### ISSUE TITLE
updated () function run before async action in Chrome 59 but after in Firefox 54

### ISSUE THREAD

**Issue by tpvt99** [vuejs/vue#5911]
### What problem does this feature solve?
Here is my code

// Message.vue
```
props: ['messages'],
methods: {
  getMessages () {
    let promise = new Promise((resolve, reject) => {
      // this action will change the property 'messages' in this component
      this.$store.dispatch('message/getMessage', resolve)
    })
    promise.then(e => {
      console.log('has fetched')
    })
 },
 beforeUpdate () {
   console.log('before')
 }
 updated () {
   console.log('updated')
 }
}
```
What I expect is
1. has fetched
2. before
3. updated
//That is expected in Firefox 54.0 when run in Linux
.And those are the results in Chrome 59.0 run in Linux:
1. before
2. updated
3. has fetched

### What does the proposed API look like?
I dont know how to

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by tpvt99** [comment]
I think it is a bug

**Comment by posva** [comment]
It's the 3rd time you open an issue with a question. If you think it's a bug, you need to include a proper boiled down repro

**Comment by tpvt99** [comment]
thanks. i will ask it in vue forum
