### ISSUE TITLE
injected objects are reactive (despite documentation saying the opposite)

### ISSUE THREAD

**Issue by akarelas** [vuejs/vue#5913]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/41000/](https://jsfiddle.net/50wL7mdz/41000/)

### Steps to reproduce
Provide (from parent component) an object with a pre-existing key. Inject that object into child component. Either console.log the object to see that it is reactive, or modify the value of the pre-existing key to see that the value also changes on screen automatically.

### What is expected?
According to vue's documentation, injected objects are not reactive: "Note: the provide and inject bindings are NOT reactive.". The value should not change on the screen after 3 seconds, and console.log should not display the word Getter when logging the injected object.

### What is actually happening?
The injected object is reactive, and so the message changes on screen after 3 seconds, and console.log'ging the object shows it is reactive (displays the word Getter)

---
I use inject to inject commonly used libraries in objects, like moment, which I can then use in the templates to display nicely formatted dates. If the entire moment library object becomes reactive, then this will probably cause an unnecessary performance hit to the browser when using the moment library.

**Comment by LinusBorg** [comment]
Hm, indeed. It seems #5204 introduced this, but I don't think this was intended.

@yyx990803 I think this is a regression from the original, intended behaviour of `inject`

**Comment by Kingwl** [comment]
thanks for reporting this!
@LinuxBorg  actual https://github.com/vuejs/vue/pull/5229 introduced this

**Comment by Darival** [comment]
I'm glad I found this, I was pulling my hair off.

**Comment by Kingwl** [comment]
@Darival in https://github.com/vuejs/vue/pull/5229 

> We can just use that to do the warning when a child component attempts to mutate an injection binding. This is what we are doing for props too:

**Comment by rayrutjes** [comment]
Personally I considered this change as a feature more than a bug.

**Comment by LinusBorg** [comment]
@rayrutjes the injected properties themselves were left unreactive pretty much for the reason OP provided: So you can inject arbitrary objects, inlcuding complicated ones, in the background and have them left untouched.

If you need reactivity, just pass down an already reactive object - best of both worlds. ;)

**Comment by Kingwl** [comment]
@LinusBorg   
but the injected array will not changed even if it is really reactive...

**Comment by rayrutjes** [comment]
@LinusBorg I think that makes sense. Wondering how this will affect our existing code base ;)

**Comment by codylandry** [comment]
I'm confused by this issue.  The docs have a note that clearly state that if you provide an observed object, it will be reactive, which is what this fiddle does exactly. 
(See note at bottom of this section)
https://vuejs.org/v2/api/#provide-inject

**Comment by LinusBorg** [comment]
@Kingwl Could you make a PR to revert this behaviour?

**Comment by Kingwl** [comment]
@LinusBorg i'm going to try it tomorrow...
