### ISSUE TITLE
support 'passive' modifier in the render function

### ISSUE THREAD

**Issue by KyLeoHC** [vuejs/vue#5915]
### What problem does this feature solve?
When I try to use 'render' function, I found that there is no support for 'passive' feature in 'on' option.But the 'v-on' directive has supported 'passive' modifier.Is there any way to use 'passive' modifier in the render function to bind event.

### What does the proposed API look like?
```js
createElement('div', {
                on: {
                     'touchmove.passive': () => { /**do something**/ }
                }
            });
```

**Comment by javoski** [comment]
This may help you:
```javascript
h('div', {
  on: {
    '&touchmove': e => {}
  }
})
```
And see [https://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers](https://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers)
