### ISSUE TITLE
I can't get child component of clientWidth etc...

### ISSUE THREAD

**Issue by kinanson** [vuejs/vue#5917]
### Version
2.3.3

### Reproduction link
[https://jsbin.com/xigazitiqu/edit?html,js,console,output](https://jsbin.com/xigazitiqu/edit?html,js,console,output)

### Steps to reproduce
I can't get child component a lot of el property.I use ref to register below
`ref="marketlineTwo"`
and below is my javascript
```
  mounted () {
      console.dir(this.$refs.marketlineTwo)  
  }
```
below is picture
![image](https://user-images.githubusercontent.com/5998113/27272492-e7b22420-54fc-11e7-8961-8752f871865f.png)

But if i access dom in the child component.I can get dom of property.code is almost like below
```
mounted () {
    console.dir(this.$el)
  }
```
below is picture
![image](https://user-images.githubusercontent.com/5998113/27272506-fcee1cb8-54fc-11e7-9d3f-470aa6c0779d.png)

### What is expected?
I want access child dom of property on the root component

### What is actually happening?
I can get child dom of property in the child component self.But i can't get property on the root component.

---
But If isn't vue file.that is ok.I don't know why.I think is template element cause,So my jsbin example is not really situation.

**Comment by LinusBorg** [comment]
`mounted()` does not guarantee that the element is already in the document.

Use `$nextTick()` to make sure of that:

https://jsbin.com/porajuyeju/edit?html,js,console,output
