### ISSUE TITLE
safari浏览器下无法触发form标签的submit事件

### ISSUE THREAD

**Issue by lazyhero** [vuejs/vue#5918]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/lanlazy/qxwgbsa4/](https://jsfiddle.net/lanlazy/qxwgbsa4/)

### Steps to reproduce
问题描述:
在safari vue 渲染下的 form 使用dom.submit方法来提交form是无效的。
1.在chrome下 使用复现页面 打开控制台 随便选择一个文件 会看到控制台提示post出错的问题 这说明submit事件是触发了 只不过是接口方的问题。
2.在safari下 同样操作 未有任何反应。
3.将vue去掉 改为正常js事件绑定change 并提交 是可以的。

### What is expected?
safari能够触发submit

### What is actually happening?
safari无任何反馈

**Comment by posva** [comment]
Browsers don't fire the `submit` event when doing `form.submit` (https://jsfiddle.net/posva/55pzx05c/). For your use case, it's better to call the same `onSubmit` function and then `form.submit`. I guess you can also create an event and trigger it on the form

**Comment by lazyhero** [comment]
@posva why close it? 
i mean it do not work in Safari  by use Vue.It worked that use js-dom(only change vue-le name).
i know 'create event onSubmit' . I also check event-monitoring in Safari : can't trigger submit.

**Comment by posva** [comment]
It won't work on Chrome nor Safari. I closed it because it's not related to Vue. Did I misunderstand something?

**Comment by crossjs** [comment]
@lazyhero

**Comment by lazyhero** [comment]
@posva  it's not related to Vue?? Are you sure??
i think you don't understand the reproduction.you should open it that let others try solve it.
By chinese:

再说一下这个复现场景。大家不用关心这个post是否有成功的回执，只需要关注 这个post动作是否有就可以了。
在chrome下 打开控制台 记住
1.先打开控制台(DevTools-console)  
2.选择一个文件 
3.确定 
观察：你会发现在控制台提示post相关错误 这是正常的反馈 没有进入onsubmit是因为在发送post前 检查发现post相关参数不合法。
而在 safari下 是没有任何反馈的 。我理解@posva的意思 他的意思是 可能safari 没有报这个错误而且。不是的，通过safari的事件监控 可以观察到 submit事件是根本没有触发的。

如果证明这跟vue有关系？你把form从vue的挂载el中拖出来，提交代码挪出来 会发现 有这个 post动作了。
我疑惑的是 为什么在vue渲染下 就有这个问题。用button标签 和 input "submit"类型是没这个问题的 唯独
document.querySelect('dom').submit()有问题……这是我想问的

**Comment by posva** [comment]
Yes, I am because I even tried the same thing removing all the Vue code and put it on the fiddle I shared with you

**Comment by lazyhero** [comment]
@crossjs reproduction 缺少submit对应方法 这个我去掉了 之前的重现代码冗余  不断精简导致的，这个我向@posva道歉。
很感谢您提供的资料，safari下是肯定可以使用form.submit()方法的 我们在生产环境也是这么去用的，仅仅是把其中一部分改成了页面vue渲染 就失效了。所以才百思不得解。

**Comment by crossjs** [comment]
看我给的链接，支持 submit 方法，但是不触发 submit 事件。

**Comment by posva** [comment]
No worries 🙂 It's definitely confusing

**Comment by lazyhero** [comment]
@crossjs 
这个链接 https://jsfiddle.net/lanlazy/xLd40w5n/ 没有用vue

**Comment by crossjs** [comment]
https://jsfiddle.net/xLd40w5n/7/

**Comment by lazyhero** [comment]
@crossjs 是啊 这是没用vue的情况…… 你只要加上一句new Vue({el:"包起来"}) 保证就不好使了……https://jsfiddle.net/lanlazy/xLd40w5n/

**Comment by crossjs** [comment]
我这里依然很好使…… 正常提交到 iframe。

**Comment by lazyhero** [comment]
@crossjs safari下依然ok??

**Comment by crossjs** [comment]
@lazyhero 是的，有问题，Safari 下表单没有提交。
如果改成下面这样，就正常了，原因未知，可能需要看源码或 @yyx990803 了。
https://jsfiddle.net/xLd40w5n/9/

**Comment by lazyhero** [comment]
@crossjs 多谢~ 我也会琢磨下~ 辛苦~
