### ISSUE TITLE
setAttribute is not a function

### ISSUE THREAD

**Issue by Tazer** [vuejs/vue#5919]
### Version
2.3.4

### Reproduction link
[http://couldnt](http://couldnt)

### Steps to reproduce
I haven't been able to make a reproduce. But our environment is:

Vue 2.3.4 with SSR that is using renderToStream. This error occurs just sometimes so it feels like a race condition or something. The error:
```
TypeError: i.setAttribute is not a function
    at Array.an (vendor.5d5b0bb….js:formatted:4401)
    at b (vendor.5d5b0bb….js:formatted:6822)
    at L (vendor.5d5b0bb….js:formatted:6788)
    at b (vendor.5d5b0bb….js:formatted:6825)
    at L (vendor.5d5b0bb….js:formatted:6788)
    at b (vendor.5d5b0bb….js:formatted:6825)
    at L (vendor.5d5b0bb….js:formatted:6788)
    at b (vendor.5d5b0bb….js:formatted:6825)
    at o.e.nodeOps [as __patch__] (vendor.5d5b0bb….js:formatted:6887)
    at o.e._update (vendor.5d5b0bb….js:formatted:6393)
```

When look in the source it's this line that breaks: https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/class.js#L40

Cause `el` is never null-checked.

### What is expected?
The site to render correctly

### What is actually happening?
Getting an client-side error that breaks the site.

**Comment by yyx990803** [comment]
Sorry, but we can't help without a reproduction. Please try to make one.
Also, a stack trace with non-minified build would help.

**Comment by Tazer** [comment]
I will close it for now then. Switched back to renderToText and everything works for now.

**Comment by Tazer** [comment]
@yyx990803  FYI , I found the problem we have the following element:
```      
<div class="ribbon" v-if="showRibbon" :class="ribbonType">
        <span class="ribbon-text" v-html="ribbonText"></span>
</div>
```

And the above problem is cause vue trying to run the ":class" code on the comment and we think it's cause we had an invalid serverCacheKey .. so all items got the same cache key, but they arent "same" cause some should show the ribbon and some not.

**Comment by shahho** [comment]
https://codepen.io/shahho/pen/MvyPvV

<div id="app"><input id="b" :type="myProduct.type" :value="myProduct.id" v-on:click="greet"></div>

in the "vue" js code like this

data : {
    myProduct: {
      id: 6,
      type:"text"
    }
