### ISSUE TITLE
Filter trigger

### ISSUE THREAD

**Issue by frontgeeks** [vuejs/vue#5921]
### Version
2.3

### Reproduction link
[https://jsbin.com/dawulukuji/1/edit?html,js,output](https://jsbin.com/dawulukuji/1/edit?html,js,output)

### Steps to reproduce
Let's create a list of 5 elements. Apply to them a filter that will substitute the time of creation of this element. Let's add one more element.

### What is expected?
The filter function must be called for the last element added.

### What is actually happening?
The filter function is applied to all elements

**Comment by LinusBorg** [comment]
This is not a bug, but expected behaviour.
