### ISSUE TITLE
Confirmed memory leak when `runInNewContext` is `true`

### ISSUE THREAD

**Issue by geekdada** [vuejs/vue#5922]
### Version
2.3.4

### Reproduction link
[https://github.com/geekdada/vue-hackernews-2.0](https://github.com/geekdada/vue-hackernews-2.0)

### Steps to reproduce
```bash
$ yarn
$ MICRO_CACHE=false node --expose-gc --inspect server
$ ab -n 50 -c 20 http://127.0.0.1:8080/
```

Stimulate a garbage collection before dump memory heap.

### What is expected?
All `Vue$3` instances not being in use are garbage collected.

### What is actually happening?
As opposite.

![](http://d.pr/i/TVrpRB+)

---
My heap dump file can be found here: http://d.pr/f/H0ypK

**Comment by LinusBorg** [comment]
Hi, thanks for your report!

Can you explain your changes, why you made them and how they relate to the memory leak? That would be helpful.

**Comment by geekdada** [comment]
You can see the commit history.
1. Global mixin as a plugin; 2. Global component as a plugin;
The tricky part is I was unable to find how they related to the leak, plus there will be no leak if I turn off any of them.

李一航 Roy Li
On Tue, Jun 20, 2017 at 4:03 AM, Thorsten Lünborg <notifications@github.com> wrote:
Hi, thanks for your report!

Can you explain your changes, why you made them and how they relate to the memory leak? That would be helpful.

**Comment by yyx990803** [comment]
Global mixins **will** lead to memory leaks when you use `runInNewContext: true` AND externalizing Vue.

- With `runInNewContext: true` the mixin registration code will be called again on every render
- When Vue is externalized, the same mixin gets registered over and over again.

This is why you should be careful when using `runInNewContext: true` and also why we recommend using `'once'` or `false` instead.

**Comment by geekdada** [comment]
@yyx990803 I have made a plugin for registering global mixin, see here: https://github.com/geekdada/vue-hackernews-2.0/blob/master/src/util/mixin.js

Does this auto-prevent duplicate registration when using `runInNewContext: true`?
