### ISSUE TITLE
Using v-on with iframes

### ISSUE THREAD

**Issue by ventsislav-georgiev** [vuejs/vue#5923]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/41207/](https://jsfiddle.net/50wL7mdz/41207/)

### Steps to reproduce
Use v-on:click on iframe element.

### What is expected?
The click handler should be invoked.

### What is actually happening?
The click handler is not invoked.

**Comment by LinusBorg** [comment]
Well, that isn't possible with plain Javascript `addEventListener()` as well, so this is expected.

**Comment by LinusBorg** [comment]
I would rather suggest to wrapping the iframe in a small component.

IF you need help with that, join us on our forums on forum.vuejs.org.

GH Issues are not meant for that.
