### ISSUE TITLE
Looks like regression to .prop modifier with components in 2.3.0 

### ISSUE THREAD

**Issue by davidhewitt** [vuejs/vue#5925]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/cpfrydsh/6/](https://jsfiddle.net/cpfrydsh/6/)

### Steps to reproduce
Create a component.

Pass it some props using v-bind, and add the .prop modifier to them.

The property values appear to not be set in the component correctly (they'll just be undefined), and bad stuff occurs.

### What is expected?
In vue 2.2.6 the .prop modifier didn't do this, the only observable effect was that e.g. :foo.prop="bar" wouldn't write any html attribute if "foo" wasn't a prop for the component in question.

### What is actually happening?
In vue 2.3.0  the prop bound with the .prop modifier is "undefined" when accessing in the component.

---
I had a go at reading the docs but I couldn't find any concrete definition of how v-bind:foo.prop should interplay with components.

In vue 2.2.6 I used this because .prop would guarantee no HTML would be generated. It would be nice if either the 2.2.6 behaviour was restored or there was another modifier created to say "if this component doensn't have a prop called foo, then just ignore this binding".

e.g.

    
    
    <component :is="my_switchable_component" :foo.prop="my_foo_value">
    </component>

**Comment by jkzing** [comment]
If I'm understanding correctly. You are trying to use `.prop` modifier as `dynamic prop binding`, which means you want to bind the property to the component if it has been defined and omit it if it does not.
But as far as I know, `.prop` modifier is designed to bind _property_ to DOM instance. I suppose current behavior for `.prop` is correct.

**Comment by davidhewitt** [comment]
Ok - perhaps it was luck this worked on 2.2.6 and I shouldn't expect it to work?

Would it be worth having a note in the docs saying that using .prop modifier on a binding is incompatible with components? 

Thanks
David

**Comment by posva** [comment]
As @jkzing said, the `prop` modifier is meant to bind Dom properties. This is documented [here](https://vuejs.org/v2/api/#v-bind)
I would like to know what made you think it would work in the first place, is some blog post advocating the use of `prop` incorrectly? In the docs the `prop` modifier is only on the page I sent you

**Comment by davidhewitt** [comment]
I read about .prop from the docs; but one thing wasn't clear to me from that - is the target object on which to set the property when using .prop on a component the component's vm, or the component's $el?

It wasn't clear to me what the answer was, so I decided to try out, and found that in 2.2.6 the properties are set on the component's vm.

It would seem in 2.3+ they're set on the component's vm.$el.

Perhaps something like this should go in the docs, to clear it up for future people like me:

> .prop - Bind as a DOM property instead of an attribute. If the tag is a component then the component's $el will be the target object to receive the property.

**Comment by posva** [comment]
Sure, pr to docs are welcome ☺️

**Comment by davidhewitt** [comment]
Thanks, see https://github.com/vuejs/vuejs.org/issues/966
