### ISSUE TITLE
Add support for object destructuring in v-on

### ISSUE THREAD

**Issue by maurop123** [vuejs/vue#5926]
### What problem does this feature solve?
When declaring components, this sort of repetitive syntax occurs a lot:

```
<component @log="log" @alert="alert" />
```

This feature would allow event declarations to be more DRY, similar to the way v-bind currently works:

```
<component v-bind="{foo, bar}" />
```

### What does the proposed API look like?
```
<component v-on="{log, alert}" />
```

**Comment by posva** [comment]
dup of #5578

**Comment by maurop123** [comment]
@posva although this issue is very similar to #5578, the difference between the proposed API of each one is significant, so can this issue be reopened?

**Comment by posva** [comment]
I see the same API with different examples: one using native events and other using custom
Did I miss something?
