### ISSUE TITLE
Changes not detected in Vue.js v2 when using selenium IDE (works in v1)

### ISSUE THREAD

**Issue by mwerezi** [vuejs/vue#5927]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/L6k5qvjo/](https://jsfiddle.net/L6k5qvjo/)

### Steps to reproduce
Save the following into an .html file

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://jsfiddle.net/" />
<title>vue-selenium-v2</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">vue-selenium-v2</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/L6k5qvjo/</td>
	<td></td>
</tr>
<tr>
	<td>selectFrame</td>
	<td>result</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>css=input[type="text"]</td>
	<td>test</td>
</tr>

</tbody></table>
</body>
</html>

```
Open it with Selenium IDE in firefox then run it.

### What is expected?
It should show "test: hello" underneath the input text box.

### What is actually happening?
it only displays "text:"

---
If you modify the vuejs version by changing the script tag to:
<script src="https://unpkg.com/vue@1.0.18/dist/vue.js"></script>
The text updates correctly

(Or use this fiddle https://jsfiddle.net/hp3xurdx/)

If you enter the text manually, it works fine as well, but for some reason something changed between v1 and v2 that makes tests with selenium IDE stop working

I encountered this bug when doing selenium IDE testing after upgrading our code from vue.js v1 to v2

**Comment by mwerezi** [comment]
So after a lot of digging, it seems the "type" command doesn't trigger the input or change events. Eventually I realised that "sendKeys" was the way to go.

Not sure why it worked in v1 but not in v2, but my hypothesis is probably because of the dynamic compilation of templates into render functions...

**Comment by guiqide** [comment]
@erezmus thank you, I used "send keys" replace "type" resolve this problem。but why……
