### ISSUE TITLE
One-Way-Data-Flow not working

### ISSUE THREAD

**Issue by Darival** [vuejs/vue#5928]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/mv3394r3/](https://jsfiddle.net/mv3394r3/)

### Steps to reproduce
-pass data to child component as prop,
-save prop to component data,
-update data in child,
-object in parent is also updated

### What is expected?
saving and updating data passed as prop in child component.

https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow

### What is actually happening?
child components is mutating the parent’s state T.T

---
i'm passing an object to a component to be edited but the component can cancel the object edition before saving it, that's why i expect "One-Way-Data-Flow" to work.

**Comment by LinusBorg** [comment]
This is expected behaviour. 

Objects and arrays are passed by reference, this is explained in the documentation.

**Comment by Darival** [comment]
sorry =(

**Comment by LinusBorg** [comment]
No Problem, no hard feelings, better one issue too much than one too few :) 

I just tend to keep messages short to save time.
