### ISSUE TITLE
The .prevent modifier does not work for mousedown event

### ISSUE THREAD

**Issue by dxcqcv** [vuejs/vue#5929]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/dxcqcv/Lxcau1pg/17/](https://jsfiddle.net/dxcqcv/Lxcau1pg/17/)

### Steps to reproduce
click on the a tag with the left click of your mouse

### What is expected?
do not redirect to href link

### What is actually happening?
jump to href link

**Comment by sirlancelot** [comment]
This is not a bug. If you want to prevent navigation, you need to `preventDefault` the click event.

**Comment by dxcqcv** [comment]
thanks @sirlancelot
