### ISSUE TITLE
The example in Chinese doc is different  with which in English

### ISSUE THREAD

**Issue by pearlwang1106** [vuejs/vue#5930]
### Steps to reproduce
According to the Chinese doc (see at https://cn.vuejs.org/v2/guide/events.html)
1. Copy the example code（example-2） to my test page
2. In the console, enter `example2.greet()` , click `Enter`; it will show a dialog box, click `Enter` 
3. U will see an error in console.

And the  example in English doc is OK. At last, I found they are different:

Chinese:

![image](https://user-images.githubusercontent.com/22272732/27320939-eb32b082-55ca-11e7-867e-a2c5275f16c1.png)

English:

![image](https://user-images.githubusercontent.com/22272732/27320956-f812744a-55ca-11e7-862f-e56c4a48a0ec.png)

### What is expected?
PS: I think this create issues page is not friendly:
1. I can not use markdown language
2. I can not paste an image to describe the problem in a better detail

### What is actually happening?
![image](https://user-images.githubusercontent.com/22272732/27320918-cef8c776-55ca-11e7-9089-641f2dd42ed8.png)

**Comment by Kingwl** [comment]
https://github.com/vuejs/cn.vuejs.org  
welcome PR

**Comment by posva** [comment]
It would be great if you could directly do the PR 😄 
Closing since this issue should be on the Chinese doc

**Comment by pearlwang1106** [comment]
--

**Comment by pearlwang1106** [comment]
see at: https://github.com/vuejs/cn.vuejs.org/pull/381
