### ISSUE TITLE
Canvas node shouldn't be reuse here?

### ISSUE THREAD

**Issue by DevilsEyes** [vuejs/vue#5931]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/iNahoo/pqhg7rhy/](https://jsfiddle.net/iNahoo/pqhg7rhy/)

### Steps to reproduce
Like my jsfiddle.

### What is expected?
I hope a clean &lt;canvas&gt; when I switch tab.

### What is actually happening?
&lt;canvas&gt; node be reused so I get a used &lt;canvas&gt;

---
I guess the template might be compiled like this ?

```javascript
    render: h => {
        const child = [];

        if (this.tab === 0) {
            child.push(h('canvas'));
        } else if (this.tab === 1) {
            child.push(h('canvas'));
        }

        return h('div', {}, child)
    }
```

**Comment by posva** [comment]
Just give one of the canvas a `key` to prevent the node from being reused 🙂

**Comment by DevilsEyes** [comment]
Nice work!
Why not add this tip in Vue document ?

**Comment by posva** [comment]
It's actually in the docs
