### ISSUE TITLE
Can't tell which component custom event came from

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue#5933]
### What problem does this feature solve?
When adding an event listener to multiple components, it is impossible to tell which component custom events came from.

Take the following:

```html
<my-component v-for="foo in foos" @myEvent="handleMyEvent"></my-component>
```

The event handler is passed the object provided as an argument to `.$emit()`, but it has no way of knowing which component it came from.

I end up working around it by passing the index into the component, and then passing it back out again in the emitted event. This seems like a bit of a hack, though…

### What does the proposed API look like?
To be honest, I have no idea how to solve this one. I run into this issue pretty frequently, though, and there's a couple threads on the forums. Perhaps a second argument?

**Comment by yyx990803** [comment]
This?

``` html
<my-component v-for="(foo, index) in foos" @myEvent="handleMyEvent(index)"></my-component>
```

**Comment by callumacrae** [comment]
Then I lose the arguments passed through: I can get one or the other, but not both.

**Comment by yyx990803** [comment]
You can use `handleMyEvent(index, ...arguments)`

**Comment by yyx990803** [comment]
Regardless - this is a question, so closing in favor of forum discussion.

**Comment by jk3us** [comment]
In v1, you can do `@myEvent="handleMyEvent(index, $arguments)`, `$arguments` is an array of things passed into `$dispatch`/`$emit`/`$broadcast`.  See https://v1.vuejs.org/api/#v-on

According to the docs, in v2, you have `$event` instead of `$arguments`.  See https://vuejs.org/v2/api/#v-on

**Comment by clintonyeb** [comment]
Don't know but this works:

```js
<body>
  <div id="app">
    <examp @ex="handle"></examp>
  </div>

  <script>

Vue.component('examp', {
template: `<input @input="$emit('ex', $event, 'hi there')">`
})

    new Vue({
      el: '#app',
      data: {},
      methods: {
        handle($event, args) {
          console.log($event, args);
        },
      }
    })
  </script>
</body>
```
