### ISSUE TITLE
Make v-for syntax for objects work with arrays

### ISSUE THREAD

**Issue by giflw** [vuejs/vue#5936]
### What problem does this feature solve?
If one has an iteration over object or array, but do not know that before hand, would be usefull to use `(value, key, index) in object` or `(value, key, index) in array` having `key` and `index` properly populated.

### What does the proposed API look like?
When using `(value, key, index) in array`, `key` and `index` would have both the same value, the index of the element in the array.

**Template:**

```html
<ul id="repeat-object">
    <li v-for="(value, key, index) in object">
       {{key}} = {{ value }}
    </li>
    <li v-for="(value, key, index) in vector">
       {{key}} = {{ value }}
    </li>
</ul>
```

** JS: **

```js
new Vue({
    el: '#repeat-object',
    data: {
        object: {
             firstName: 'John',
             lastName: 'Doe',
             age: 30
        },
        vector: [
            "a", "b", "c"
        ]
    }
})
```
**Result**

- firstName = John
- lastName = Doe
- age = 30
- 0 = a
- 1 = b
- 2 = c

**Comment by posva** [comment]
I don't think this is really needed though because you can do

```html
<li v-for="(value, key, index) in collection">index: {{ index || key }}</li>
```

**Comment by giflw** [comment]
I've notice my example is not quite right. It should be `index` in the template instead of `key`.

Concerning your example, it works, but the developer must always think in the edge cases where it can be receiving an object or array, and remember to deal with it. The unification would just let the API easier to use, as both cases (array and object) would have the same syntax.

**Comment by posva** [comment]
When is it useful to use indexes for objects?

**Comment by giflw** [comment]
I think I become a little confused here.

Using `<li v-for="(value, key, index) in collection">index: {{ index || key }}</li>`, when the collection is an `object`, the value selectec will be `index`, and when the collection is an array, the value will be the `key`.

So when one want to access the key of the object or the index of the array, one should use `<li v-for="(value, key, index) in collection">index: {{ key }}</li>`, right?

So, the unified syntax would be inded `<li v-for="(value, key) in collection">index: {{ key }}</li>`.

But, if one use `(value, key, index)` to iterate and use `{{index}}` on the template, whe the collection is an array, the `index` variable will be empty.

My point is not the index of the object, but the array index beeing populate in the object syntax, to make it reusable when one receive either an object or an array. So, in the aray case, `index` and `key` will have the same value and one do not need to remenber that index will be empty to arrays and not empty to objects.

**Comment by posva** [comment]
> So, the unified syntax would be inded <li v-for="(value, key) in collection">index: {{ key }}</li>.

yes

> But, if one use (value, key, index) to iterate and use {{index}} on the template, when the collection is an array, the index variable will be empty

and my question is when does that happen, why would you rely on that index on an object loop? It really make sense to use `index || key` thought

**Comment by giflw** [comment]
Why the `(value, key, index)`  syntax exists to objects, if is not usefull? My point is not usefullnes, but consistence in the API, as some bugs could arise if one forgets when index will be empty and try to use it.

**Comment by posva** [comment]
> Why the (value, key, index) syntax exists to objects, if is not usefull? 

Well, I wonder why as well. That third argument should be the original collection 😆

**Comment by giflw** [comment]
Is this case, I think the `(value, key, index)` should be deprecated and in a future version (with breaking changes) added as `(value, key, cololection)`.

**Comment by LinusBorg** [comment]
I will close this issue for now as this won't be changed in 2.* and made an internal note on the long list for 3.0
