### ISSUE TITLE
v-model breaks the format applied on the input text fields

### ISSUE THREAD

**Issue by alexandretperez** [vuejs/vue#5938]
### Version
2.3.4

### Reproduction link
[https://plnkr.co/edit/Q31wtwyeajS4fF4dUSO4](https://plnkr.co/edit/Q31wtwyeajS4fF4dUSO4)

### Steps to reproduce
- Create two or more input:text.
- Define a v-model for each one.
- Format the input on the "blur" event.
- Remove the format on the "focus" event.

### What is expected?
Not loses the format of the not focused input on typing.

### What is actually happening?
The format is removed of all input:text that has the v-model attribute.

---
The plunker link has a more direct explanation of the problem and an angular sample was created to show the expected behavior.

**Comment by nickmessing** [comment]
@alexandretperez, that is expected behaviour, vue 2 is built with virtual-dom so that vue is "the only source of truth", you should never mutate the DOM generated by vue manually because it gets overwritten at next Vue tick

**Comment by yyx990803** [comment]
^ what @nickmessing said
