### ISSUE TITLE
@-webkit-keyframes hash not working

### ISSUE THREAD

**Issue by Chooin** [vuejs/vue#5946]
### Version
2.3.3

sass-loade: ^6.0.6
node-sass: ^4.5.3

### Reproduction link
[http://qr.dev.hemayun.com/static/css/app.360e94be2558dcfd9e4d865791173495.css](http://qr.dev.hemayun.com/static/css/app.360e94be2558dcfd9e4d865791173495.css)

### Steps to reproduce
npm run build

### What is expected?
``` bash
@-webkit-keyframes cursor-data-v-6178f221 {
	0% {
		opacity:1
	}
	25% {
		opacity:1
	}
	26% {
		opacity:0
	}
	74% {
		opacity:0
	}
	75% {
		opacity:1
	}
	to {
		opacity:1
	}
}
@keyframes cursor-data-v-6178f221 {
	0% {
		opacity:1
	}
	25% {
		opacity:1
	}
	26% {
		opacity:0
	}
	74% {
		opacity:0
	}
	75% {
		opacity:1
	}
	to {
		opacity:1
	}
}
```

### What is actually happening?
``` bash
@-webkit-keyframes cursor {
	0% {
		opacity:1
	}
	25% {
		opacity:1
	}
	26% {
		opacity:0
	}
	74% {
		opacity:0
	}
	75% {
		opacity:1
	}
	to {
		opacity:1
	}
}
@keyframes cursor-data-v-6178f221 {
	0% {
		opacity:1
	}
	25% {
		opacity:1
	}
	26% {
		opacity:0
	}
	74% {
		opacity:0
	}
	75% {
		opacity:1
	}
	to {
		opacity:1
	}
}
```

**Comment by LinusBorg** [comment]
Hi @Chooin 

Thanks for reporting this issue. However, this is not a valid, runnable reproduction. Please provide one.

**Comment by Chooin** [comment]
@-webkit-keyframes hash is empty

**Comment by jkzing** [comment]
@Chooin You can provide a github repo to reproduce your situation.
你只提供了css，没有构建过程，不能重现啊。😅
你可以提供一个github repo来重现问题。

**Comment by posva** [comment]
I tested with vue-loader and as @Chooin said, the prefixed version doesn't have the `data-*` scoped style while the non prefixed has it. I'm closing this as it is related to vue-loader or postcss. BTW, unless you're supporting safari 8, you don't need that prefix for keyframes
