### ISSUE TITLE
Running vue in development mode without virtual DOM

### ISSUE THREAD

**Issue by janat08** [vuejs/vue#5948]
### What problem does this feature solve?
It hopefully would produce actual errors.

### What does the proposed API look like?
Adopt some other framework without virtual dom to actually render stuff using vue syntax.

**Comment by janat08** [comment]
I imagine you'd also want to make it very clear that interfacing with DOM directly is a no-go, however well it goes in development.

**Comment by sirlancelot** [comment]
You can use the full build of Vue which includes the compiler. This is the build that is used for services like JSFiddle or CodePen. It generates actual errors as you describe.
