### ISSUE TITLE
热更新未知问题

### ISSUE THREAD

**Issue by Desever** [vuejs/vue#5953]
npm run dev 以后
控制台如下错误：GET http://localhost:8080/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by wangxiao** [comment]
@Desever  感觉是 nodejs 8.0 的一个 bug 导致的，你可以尝试升级 nodejs 到最新版本，并且同时升级 webpack 相关的 modules。
