### ISSUE TITLE
How to load a function upon page load?

### ISSUE THREAD

**Issue by heliosnarcissus** [vuejs/vue#5954]
I'm a beginner VueJS programmer.
I only know how to trigger a function using @click method from VueJS. However , I want to know how to trigger function after the page loads, something like v-init from Angular.

Thanks!

**Comment by jkzing** [comment]
If you are not asking for `load` for _window_ or `DOMContentLoaded` for _document_, you need to use vue's lifecycle hook.
In your case, `mounted` is what you want.

**Comment by heliosnarcissus** [comment]
@jkzing Thank you for replying. I will check the method you've provided.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

About your issue, what @jkzing said 😄
