### ISSUE TITLE
Passing empty string into boolean type prop result in true

### ISSUE THREAD

**Issue by jkzing** [vuejs/vue#5959]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/u2mo75oo/2/](https://jsfiddle.net/u2mo75oo/2/)

### Steps to reproduce
run repro

### What is expected?
`comp.name` to be *false* or get warning.

### What is actually happening?
`comp.name` is *true*.

**Comment by Kingwl** [comment]
https://github.com/vuejs/vue/blob/b5b1ac373a8f4d464454e7770a888fdd178891c4/src/core/util/props.js#L27  
i found https://github.com/vuejs/vue/issues/4539 to fix  https://github.com/vuejs/vue/pull/4538

**Comment by jkzing** [comment]
Seems this is intended, found the code here:  https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L27 

Is there any background reason for this?

**Comment by gebilaoxiong** [comment]
@Kingwl 👍 

@jkzing 

see: https://www.w3.org/TR/html51/syntax.html#name

> Just the attribute name. The value is implicitly the empty string.

**Comment by Kingwl** [comment]
@gebilaoxiong i found wrong commit so i delete that 😂

**Comment by jkzing** [comment]
Found it in docs as well...https://vuejs.org/v2/guide/migration.html#Built-In-Directives

Maybe we should make this more clear in component section?

**Comment by phanan** [comment]
You're welcome to submit a PR to Vue docs repo :)
