### ISSUE TITLE
Giving an error when add logical operators in v-model

### ISSUE THREAD

**Issue by donnes** [vuejs/vue#5960]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/7hy9bq4b/2/](https://jsfiddle.net/7hy9bq4b/2/)

### Steps to reproduce
Run repro

### What is expected?
Show first checkbox enabled and second disabled

### What is actually happening?
"ReferenceError: Invalid left-hand side in assignment in" on console

**Comment by phanan** [comment]
That's not how `v-model` works. `v-model` is just syntactic sugar for `v-bind:value` and `v-on:input`, so your example is essentially the same as:

```html
<input type="checkbox" v-bind:value="!question.disabled"  v-on:input="!question.disabled = $event.target.value">
```

Clearly that won't work.
