### ISSUE TITLE
v-for how to do this

### ISSUE THREAD

**Issue by htank-wang** [vuejs/vue#5962]
### What problem does this feature solve?
for (var i=0;i<5;i  ){
  //do something
}

thanks!

### What does the proposed API look like?
v-for

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as stated in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md). Thanks.
