### ISSUE TITLE
Recursively pass slots in a recursive component

### ISSUE THREAD

**Issue by ericwangqing** [vuejs/vue#5965]
### What problem does this feature solve?
Currently when we pass a slot to a recursive component, it is only effective in the first level. And it would be nice if it can be passed recursively.

### What does the proposed API look like?
```jade
my-recursive-component(:model="nested-obj")
  template(recursive-scope)
    span client content

//- my-recursive-component
div 
  div component content
  slot
  my-recursive-component(v-if="model.hasChild", :model="model.child")

```

**Comment by yyx990803** [comment]
I think this can be quite difficult to express with pure templates and I would suggest using render functions for sophisticated use cases like this.

**Comment by rayrutjes** [comment]
@ericwangqing here is a thread that might be of interest: https://forum.vuejs.org/t/recursive-scoped-slots/8220/5

**Comment by ericwangqing** [comment]
@rayrutjes thanks a lot 👍

**Comment by inca** [comment]
For anyone looking to implement recursive components (e.g. tree views) customizable by consumers with slots, this works pretty much as expected in Vue 3.

Pseudocode:

```vue
<!-- TreeView.vue -->
<div class="TreeView">
    <TreeViewItem
        v-for="item of items"
        :item="item">
        <template v-slot:line="{ item }">
            <!-- Pass the slot specified by the consumer into the recursive component -->
            <slot name="item" :item="item" />
        </template>
    </TreeViewItem>
</div>

<!-- TreeViewItem.vue -->
<div class="TreeViewItem">
    <div class="Line">
        <!-- Render the supplied slot with current item -->
        <slot name="line" :item="item" />
    </div>
    <TreeViewItem
        v-for="child of item.children"
        :item="child">
        <template v-slot:line="{ item }">
            <!-- Pass the supplied slot onwards to nested components -->
            <slot name="line" :item="item" />
        </template>
    </TreeViewItem>
</div>

<!-- Consumer.vue -->
<TreeView :items="myItems">
    <!-- Consumer-specified slot -->
    <template v-slot:item="{ item }">
        {{ item.label }}
    </template>
</TreeView>
```

All slots are essentially render functions, and you can think of scopes as function parameters — so the entire thing just works. 🎉
