### ISSUE TITLE
Support duplex v-model binding [提供v-model的双向绑定]

### ISSUE THREAD

**Issue by Alphmega** [vuejs/vue#5966]
### What problem does this feature solve?
这种场景
```javascript:
export default {
    props: {
        value: {}
    },
    data() {
        return {
            innerValue: this.value
        }
    },
    watch: {
        value(value) {
            this.innerValue = value
        },
        innerValue(innerValue) {
            this.$emit('input', innerValue)
        }
    }
}
```
在我使用vue的很多时候，会在组件内创建一个内部的value以供组件内部修改，而通过watch来emit到外部，这种做法实际上是让内部的value看起来像是双向绑定的
希望官方能提供语法糖，来实现这种行为

### What does the proposed API look like?
````javascript

export default {
    model: {
        name: 'value',
        event: 'input',
        duplex: true
    },
    methods: {
        changeValue(newValue) {
            this.value = newValue
        }
    }


}

````

**Comment by Kingwl** [comment]
> 这种做法实际上是让内部的value看起来像是双向绑定的  
i cannot understand this description...please explain again....

**Comment by jkzing** [comment]
你的意思是想使用自定义的prop和event来进行v-model绑定吗？
可能`.sync` modifier 能满足你的需求？https://cn.vuejs.org/v2/api/#v-bind

**Comment by posva** [comment]
I'm not sure to understand the problem. Usually, you do a one way binding of the value and listen for changes coming, eg: `change` event on a checkbox. And that's where you `emit` the change. Then, the value gets updated again from the parent.
About the inner values, you should consider [computed setters](https://vuejs.org/v2/guide/computed.html#Computed-Setter)

**Comment by xiangsongtao** [comment]
这个是你要的改进：https://cn.vuejs.org/v2/guide/components.html#sync-修饰符
