### ISSUE TITLE
router params can't be void string

### ISSUE THREAD

**Issue by gd602546628** [vuejs/vue#5968]
### Version
2.3.4

### Reproduction link
[http://localhost:8080/#/couponSearch/](http://localhost:8080/#/couponSearch/)

### Steps to reproduce
 ```javascript

{ 
      path: '/couponSearch/:keyword',
      name: 'couponSearch',
      component: couponSearch,
    }



this.$router.push({
            name: 'couponSearch',
            params: {keyword: keyword}
          })
```
if keyword is void string,this router can't be matched

### What is expected?
go to  'couponSearch/'  ，and params.keyword is  void string 

### What is actually happening?
this router can't be matched

**Comment by JounQin** [comment]
Maybe you should use `/couponSearch/:keyword?`.

VueRouter use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) on route matching.

https://vuejs.org/v2/guide/migration-vue-router.html#Route-Matching

**Comment by gd602546628** [comment]
Thanks a lot,
  i try this ,```params.keyword``` still can't be void string ,but can be ```null``` ,that's enough
