### ISSUE TITLE
Keep-Alive Component can not destory immediately when use vue-router

### ISSUE THREAD

**Issue by Sapphire2k** [vuejs/vue#5969]
### Version
2.3.4

### Reproduction link
[https://jsbin.com/piyitaj/edit?html,css,js,output](https://jsbin.com/piyitaj/edit?html,css,js,output)

### Steps to reproduce
KeepAlive Component Foo
NoKeepAlive Component Bar
Common Parent Content: `div.router-view`

Page Foo
Click `Go to Bar`
 -> Page Bar
Change `div.router-view`  Style -- > Height = '50px'
Click `Back to Foo`
-> Page Foo

### What is expected?
Page Foo Height --> Keep the right CSS
Page Bar Height --> '50px'

### What is actually happening?
Page Foo Height --> '50px'
Page Bar Height --> Nothing happen
T_T
---
Is there any solution? Thank you so much!

**Comment by JounQin** [comment]
You should use `nextTick` in `mounted` hook.
https://jsbin.com/jeqepikudo/edit?html,css,js,output

**Comment by Sapphire2k** [comment]
@JounQin thanks a lot!!
