### ISSUE TITLE
Consider giving a name to current default transition mode and 

### ISSUE THREAD

**Issue by Eiskis** [vuejs/vue#5972]
## 1. The current default has no name

There is no name for the current default. Logically it should be called something like `simultaneous` (hard to spell, I know), but currently there seems to be no name for it that could be documented in a quick reference, talked about with other developers and easily remembered.

Now, since this isn't really documented, I don't know how to handle the following scenario: I'm switching between transition modes programmatically, in which case my list of valid transition modes looks like this:

```js
const modes = ['', 'out-in', 'in-out'];
```

That's really weird. This is how I think it works, but TBH I'm not completely sure. Based on my experience this doesn't happen often, but I could imagine wanting to do this e.g. for certain routes dynamically.

I think it's just generally a good practice to provide a list of valid values for parameters like this, and explicitly point out which one is the default.

## 2. Better global default for most common use cases

As a little bit of background, I'm a UX designer and a FE dev, and have worked a lot on delivering motion design for devs on multiple platforms. I have been using Vue in tons of projects for a while now, and one of the things I'm most happy with is the transition system. It makes regular work with transition animations very easy, by far the most pleasant experience of all the JS frameworks or native platforms, and it makes implementing a satisfying level of transitions from the get-go very easy by reusing named transitions.

I've noticed that the _vast_ majority of use cases in practical development scenarios are either A) conditionally rendering one element or B) switching between two elements.

In scenario B, `out-in` is _almost always the desired mode_, but it needs to be explicitly set every time `<transition>` is used. `out-in` does not seem to affect scenario A. It's frustrating to manually have to set `out-in` each time, and forgetting this easily leads into hard-to-catch mistakes.

Since `out-in` is not the default, new developers have to learn more of the intricacies of transition modes before they can be effective with scenario B transitions, even though they don't have to care about the mode with scenario A. I think we could cover both scenarios better by having `out-in` as the default.

Of course the desired mode always depends on the specific art style and specific animations desired. However even as a designer I think `out-in` is a much better default, since transition specs (generally speaking) are broken into one element's exit transition and the entry transition of the next one. From this perspective it would make sense that by default these animations are played in succession. The dev should add an extra parameter to make them happen simultaneously, since this introduces more considerations for how to handle the state of both elements being in the DOM at the same time.

## Other notes

I'm sure this has been considered by the dev team before, and there are also good reasons for the current default. I think the best solution would be to be able to set the default transition mode in the global configuration on a project-to-project basis. I wouldn't mind configuring this with a `Vue.configuration.defaultTransitionMode = 'out-in'` one-liner, and this would let me as a dev make a conscious choice about this that reflects the design of my current project.

These are two individual requests, but I think they do go together to some extent, and naming the current default would be needed in order to support a configuration parameter for this I guess.

(To clarify, this request is not the same as #4453)

### What does the proposed API look like?

```
Vue.configuration.defaultTransitionMode = 'out-in';

// ...

const modesToToggle = ['simultaneous', 'out-in', 'in-out']

// ...

<transition mode="simultaneous">
```

**Comment by yyx990803** [comment]
Any value that is not `out-in` or `in-out` is treated as default, so you can already do what you want.

**Comment by yyx990803** [comment]
Oh nvm, yeah we have validations in place. Honestly though, I don't think we will change the current behavior because the value it provides is somewhat subjective while introducing API churn.

**Comment by Eiskis** [comment]
Are you saying I can change the default somehow? I don't think I can.

Like I stated above, I do understand the this is somewhat subjective, but for the reasons I mentioned I think we should look at what the most common use cases are and consider changing the default. I opened the issue since I've noticed the same pattern repeat itself in practically all of my Vue projects (which are quite varying). The vast, vast majority of the `<transition>` elements I write are using `out-in` with the other modes being rare exceptions.

Would love for others to pitch in, if the issue can be kept open. I didn't really understand the API churn point.

**Comment by yyx990803** [comment]
Changing the default is a breaking change. Breaking change for subjective reasons is a no-go.

**Comment by Eiskis** [comment]
I was proposing the configuration parameter for setting the default on a project-to-project basis for exactly that reason. I guess I'll provide a set of wrapper components for my guys to easily avoid the common mistakes with this in the future. Gets us around having to actually deal with the mode parameter altogether.

**Comment by posva** [comment]
I don't think it's a default worth adding a config option for though. The hoc solution looks nice imo
