### ISSUE TITLE
vue.watch api功能太弱！！

### ISSUE THREAD

**Issue by xltxlm** [vuejs/vue#5974]
### What problem does this feature solve?
只提供前后改变的值，没有提供改变的索引？？

### What does the proposed API look like?
vue.watch

这样做审核类似的页面，做不下去了，都不知道是哪一行的索引改动了，难道每一行定制一个函数？

**Comment by yyx990803** [comment]
请学会用得体的语言对开源项目提需求，话都不会好好说还指望别人帮你忙？

**Comment by shusiwei** [comment]
这种傻蛋，自己技术不怎么样，还满口喷，你不知道有个遍历props叫key？有时间多学学做人！

**Comment by Kingwl** [comment]
thanks for your suggestion
please take a new issue again😁
