### ISSUE TITLE
Error to add class on "table tr" of data

### ISSUE THREAD

**Issue by jeanechabaudis** [vuejs/vue#5979]
### Version
2.3.4

### Reproduction link
[https://codepen.io/jeanPool/pen/owGOgX](https://codepen.io/jeanPool/pen/owGOgX)

### Steps to reproduce
execute button "Agregar fila"

### What is expected?
help me!

### What is actually happening?
When adding a row to my data object I also want to add a class to that new record, then a link to the example, you will see that the last added record does not have the class

---

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You could add a property `active` to the array elements and use that to bind the `:class` of the rows
