### ISSUE TITLE
Click with modifiers versus click without modifiers

### ISSUE THREAD

**Issue by truefusion** [vuejs/vue#5980]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/42772/](https://jsfiddle.net/50wL7mdz/42772/)

### Steps to reproduce
Ctrl   click the element in the jsfiddle.

### What is expected?
Only one event should trigger.

### What is actually happening?
Both events trigger.

---
I believe there should be a distinction between clicks with modifiers and those without, for I feel there would be some redundancy without the distinction. Yeah, for general cases this is a non-issue, but with the distinction we would at least crunch down on the definitions to what signifies a click and a click with modifiers.

**Comment by posva** [comment]
This is expected behaviour, if you want to have better control over what code is executed, you should do the key filtering yourself inside the event callback and keep one single `@click` handler
