### ISSUE TITLE
Computed property is not updating in SSR

### ISSUE THREAD

**Issue by mrTimofey** [vuejs/vue#5982]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1. Create any `component.data` item.
2. Create any computed property which depends on this data item.
3. Create `created` hook with the following actions:
    1. Access the computed value.
    2. Change the data item to anything else.
    3. Print computed value somewhere (`console.log` for example).

### What is expected?
Computed prop value must be changed.

### What is actually happening?
Computed prop value remains unchanged in SSR.

---
I have created a watcher on `$route.query.key` value with `immediate: true` flag. I compare old computed value with new one (after some actions affecting the computed prop) and see the error 'SSR and client side DOM's are different'. After some debugging I found out that computed property is simply not changing after first call in SSR.
May be this behavior is normal but i don't remember something like that was in the documentation.

**Comment by mrTimofey** [comment]
Reproduction link is obviously not reproducing anything because there is no SSR in jsfiddle :)

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by mrTimofey** [comment]
I have created a branch in my repo with the reproduction code.
https://github.com/mrTimofey/vue-ssr-starter/tree/vue-ssr-computed-bug

### Steps to reproduce
1. `npm run dev` (or `npm build`, `npm start` in production mode)
2. open http://localhost:8080
3. compare server and browser consoles

The reproduction code itself is in the `src/app.vue` component.

**Comment by mrTimofey** [comment]
Sorry, I didn't notice that repo link can be also attached to the issue. I thought only code services like jsfiddle are permitted.

**Comment by yyx990803** [comment]
There is no reactivity during SSR: http://ssr.vuejs.org/en/universal.html
