### ISSUE TITLE
Got infinite update error while passing JSX VNode to ChildComponent in some case.

### ISSUE THREAD

**Issue by chairuosen** [vuejs/vue#5989]
### Version
2.3.4

### Reproduction link
[https://github.com/chairuosen/vue-bug-demo/tree/loop-update](https://github.com/chairuosen/vue-bug-demo/tree/loop-update)

### Steps to reproduce
clone the [demo](https://github.com/chairuosen/vue-bug-demo/tree/loop-update) 

checkout branch `loop-update`

install & run it

click second toggle bar

### What is expected?
no error in console

### What is actually happening?
[Vue warn]: You may have an infinite update loop in a component render function.

**Comment by jkzing** [comment]
It seems DOM attribute on element is the one to blame, `href` in this case. Needs deeper investigation.

**Comment by jkzing** [comment]
Wait...
You are passing vnode as prop to your component, and have an `this.someObj = this.obj` assignment...😅
This would make the whole vnode object reactive. What you should do is something like: 
``` jsx
// in Hello.vue
<Child>
  <ToggleContent>
    <a href="/">111111</a>
  </ToggleContent>
</Child>

// in Child.vue
<div>{this.slots.default}</div>
```

**Comment by chairuosen** [comment]
@jkzing thank you for reply. 
You mean its different between passing vnode by props and slots? I'll try it tomorrow, thank you for suggestion.

But why it is fine in case3, the only different between 2 and 3 is `ToggleContent` vs `Abc`, Both of them are simple.

**Comment by znck** [comment]
As @jkzing said, you should use slots. 

I'll close this now. If you still feel this is a bug, feel free to open it again.

**Comment by jkzing** [comment]
@chairuosen Not sure on it, what I could say is when you making vnode object reactively the behavior on it would not be expectable.

**Comment by chairuosen** [comment]
@znck We just know the solution to avoid the bug. but don't know the reason. and don't know why it works fine in case3.
also, I think the usage of my code isn't weird, I often pass the vnode with props in React. 
So I still think this is a bug.
But there is no reopen button for me in this page LOL. Could you please reopen the issue. Thank you.

**Comment by jkzing** [comment]
@chairuosen Actually it was not passing vnode as prop made this happen, it's assigning it to `data` property of a component by `this.someObj = this.obj`. Why this working in React is simple, because React would not make any object reactive to reflect your changes on it.

**Comment by chairuosen** [comment]
@jkzing Yeah, ^_^ same as I guess. a black-box's view. but can't explain case 3.

**Comment by jkzing** [comment]
@chairuosen Why not? In your case 3 you are using `slot`, which is not reactive.

**Comment by chairuosen** [comment]
@jkzing Both them are not using slot with `Child` , but using slot in vnode of the prop
case 2:
```
<Child obj={ {
                vnode:<ToggleContent title="this works not fine. click me">
                    <a href="/">11111</a>
                </ToggleContent>
            } }/>
```
case 3:
```
<Child obj={ {
                vnode:<Abc>
                    <a href="/">But this component works also fine with `a` tag.</a>
                </Abc>
            } } />
```

**Comment by znck** [comment]
Just an observation, don't know why this is happening.

``` jsx
<ToggleContent title="this works not fine. click me">
    <a href="/">11111</a>
     // If there is no attribute here, then no infinite look. Some how attributes on hidden html are causing re-render.
</ToggleContent>
