### ISSUE TITLE
Consi

### ISSUE THREAD

**Issue by dickeylth** [vuejs/vue#5990]
### What problem does this feature solve?
I'm building a website for code review platform, and I need to output `.vue` file source code to the html and highlight it, however I encountered an issue, the `koa-static-cache` module relied on `mime-types` module inside and figured the mime type for `.vue` file as missing corresponding define, which then fallback to `application/octet-stream`, and that's not what I desired.

I've send a [pr to `mime-types`](https://github.com/jshttp/mime-db/pull/84#discussion_r124300645) to add `.vue` configuration (personally I think `text/vue` is a good choice, you can also suggest a better one), but the contributor needs the source to declaim the mime type, so I think it's better to refer to you to confirm the best mime type and declaim it somewhere in the doc?

### What does the proposed API look like?
No related.

**Comment by yyx990803** [comment]
See https://github.com/jshttp/mime-db/pull/84#issuecomment-311570485
