### ISSUE TITLE
Child's private state doesn't reset when switch child component in father component written with JSX

### ISSUE THREAD

**Issue by chairuosen** [vuejs/vue#5991]
### Version
2.3.4

### Reproduction link
[https://github.com/chairuosen/vue-bug-demo/tree/strange-state](https://github.com/chairuosen/vue-bug-demo/tree/strange-state)

### Steps to reproduce
clone the demo https://github.com/chairuosen/vue-bug-demo/tree/strange-state
branch `strange-state`
install & run

by default, child 0 shown
click plus button to increase his count
then click button1, switch to child 1
the count doesn't reset to 0

### What is expected?
child1's count reset to 0 after switch

### What is actually happening?
child1's count is child0's count

**Comment by yyx990803** [comment]
You need to `key` the component because they use the same constructor.
