### ISSUE TITLE
关于IOS safari和微信浏览器后退出现空白遮盖的问题

### ISSUE THREAD

**Issue by chiknin** [vuejs/vue#5994]
### Version
2.3.4

### Reproduction link
[https://github.com/ElemeFE/mint-ui/issues/937](https://github.com/ElemeFE/mint-ui/issues/937)

#### 环境
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 MicroMessenger/6.5.9 NetType/WIFI Language/zh_CN
```
#### 步骤
1. 打开 http://elemefe.github.io/mint-ui/
2. 第一页滚动到下面， 点击任意链接进入第二页
3. 使用浏览器自带返回按钮 【返回】， 原来的第一个页面就会出现遮盖。

### What is expected?
返回应该正常显示上一个页面内容，不应该出现空白遮盖

### What is actually happening?
遮盖覆盖了原来的页面

---
试了几个开源vue项目都会出现这个空白遮盖的问题， 只要再次触摸、滚动就可以恢复正常。
如： https://github.com/bailicangdu/vue2-elm.git

演示git: https://github.com/ElemeFE/mint-ui/issues/937

**Comment by yyx990803** [comment]
涉及具体库的问题请不要随便来这里开 issue，除非你能提供一个库无关的重现。

**Comment by DeronEndless** [comment]
有解决的方案没
