### ISSUE TITLE
@click not working in Safarie

### ISSUE THREAD

**Issue by treaves** [vuejs/vue#5999]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/1jvk22xy/5/](https://jsfiddle.net/1jvk22xy/5/)

### Steps to reproduce
Select a item from the drop-down.

### What is expected?
The drop-down title reflects the selected item.

### What is actually happening?
The title does not change.

---
This is my first JSFiddle, and there is an issue with it, that may be unrelated.  In my 'real' code, this functionality works on Chrome.  When the user selected an item, the main drop-down button changes to display that.  In Safari, no change is made. Also in Safari, the @click method does not log anything.  So the click method is not being called.

In the referenced JSFiddle, in both Safari & Chrome, the console does show the log message, but, the button text does not change.

I'd appreciate anyone that may be able to tell me what's going on.  Thanks.

**Comment by posva** [comment]
replace the `self` by `this` in the method 🙂

**Comment by treaves** [comment]
Yes, that was the issue in the JSFiddle (don't know why I did that).  My code uses 'this' though, and it doesn't work in Safari.  It is working now in the JSFiddle.

That's the trouble with trivial examples, versus real code.  It's still defect.
