### ISSUE TITLE
Unexpected watch behavior for object props

### ISSUE THREAD

**Issue by nonadmin** [vuejs/vue#6000]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/nonadmin/1x4uvma8/](https://jsfiddle.net/nonadmin/1x4uvma8/)

### Steps to reproduce
Changing the "price" in the parent component has the expected behavior.  The v-model updates the object property and that's picked up in the child component.  Updates happen immediately on key up.  Now change the price in the "form" component.  The watch does not update until tabbing out of the input.

### What is expected?
The watch should behave the same as it does when the value is changed in the parent component

### What is actually happening?
Watch is only fired when tabbing out of the input

---
I came across this while trying to find the "best" way to pass props to my form components.  I think maybe the docs could be clearer on the best way to do this, and all I can find elsewhere are sort of contrived examples.  

The watch behavior makes me think I'm not doing things in the best/"Vue" way.  

In the application I'm developing, the pattern I've come up with for doing CRUD type changes is that I have an object representing a database record.  I fetch that object from the server in my parent component (issue action to vuex, but that's sort of irrelevant here).  I then clone that object into a child component that contains the form to update the object.  If the form passes some client side validations I then 'emit' the updated, cloned object to the parent and then the parent saves that to the server.

I tried to make a crude diagram.  I guess this is a little more than just a simple issue with the watcher.  In addition to that if there's a good example out there of the type 'record' update lifecycle I'm talking about, that would be really helpful.

```
                                          -------------------- 
                       (2)               |                    |
           --------------------------->  |      Database      |
          |       ajax request/response  |                    |
          |                               -------------------- 
          |
          |
          |                 (1) fetchData                         (4) clone dataObj
 --------- ----------  <--------------->  --------------------   ------------------>  -------------------- 
|                    |    (3) dataObj    |                    |                      |                    |
|   Vuex Store       |                   |     Parent         |                      |                    |
|                    |                   |                    |                      |    Form/Validation |
|                    |                   |                    |    (5) emit saVed obj|                    |
 --------------------  <---------------   --------------------  <-----------------   |                    |
                          (6) saveData                                                -------------------- 

```

**Comment by znck** [comment]
Props are readonly. You should not modify them instead emit an event to update.

``` vue
...
// before
<input v-model.number="obj.price" type="number">

// after
<input :value="obj.price" @input="e => $emit({ ...obj, value: e.target.value})" type="number">
```

As props are readonly, you should not use them with `v-model`.

**Comment by nonadmin** [comment]
Ah ok, I understand that.  But that does get into my second point there.  Is there a "VueJS" way for handling an html form component?  The easiest way for me to reason about it was to pass an object as a prop.  And then have the form input's work on each property of the object.  Obviously that's causing these sort of issues.

**Comment by znck** [comment]
You can read about [input components](https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events). I guess this is what you are looking for.
