### ISSUE TITLE
window resize后导致click事件无效

### ISSUE THREAD

**Issue by wangbagang** [vuejs/vue#6001]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/43916/](https://jsfiddle.net/50wL7mdz/43916/)

### Steps to reproduce
```
<popup v-model="dietPicker.show" class="diet-picker">
      <div class="search" ref="searchContainer" v-if="dietPicker.show">
        <input type="text" v-model="dietSearchInput" ref="dietSearch" class="r1b"/>
        <button @click="foodSearch">搜索</button>
      </div>
      <p class="s-loading" v-if="dietCheckList.length == 0" style="text-align: center;">正在加载食物列表...</p>
      <ul class="picker-list r1b" v-if="dietCheckList.length > 0" ref="chooseDietUl">
        <li v-for="diet in dietCheckList" @click="chooseDiet(diet)">
          <div>
            <img :src="diet.image"/><span>{{ diet.name }}</span>
          </div>
        </li>
      </ul>
    </popup>
```
点击button会弹出一个popup ，这是一个遮罩层，当遮罩层弹出来dietCheckList去后台拿数据，拿到数据后ul列表展示出来

### What is expected?
点击input后ul中的li可以调用chooseDiet方法

### What is actually happening?
在ios10.2.1上面当点击input后弹出手机的键盘后，li的click事件无效，点击键盘的收起按钮后，页面恢复后li的click事件依然无效

---
这是必现的问题，在最新版的ios10.3上面不会有任何问题，android和最新版chrome也不会有问题，jsfiddle上不一定可以复现，类似于这个：https://stackoverflow.com/questions/41746739/vue-js-directive-does-not-work-on-injected-element?answertab=active#tab-top

**Comment by wangbagang** [comment]
补充下：在ios 10.2.1，当点击事件无效的时候ul可以正常滑动，我监听了ul的touchmove事件后，li的click事件又恢复了，监听touchstart事件，li的click事件还是无效

**Comment by yyx990803** [comment]
What makes you think this is caused by Vue?

**Comment by wangbagang** [comment]
尤大大您好，你问确实是，这个问题不一定是因为vue引起的，我也实在想不出，找不出什么原因导致的，还望指点下。

**Comment by jkzing** [comment]
你需要把真正有问题的代码发出来，提供一个不能重现的jsfiddle别人帮不了你。

PS：寻求帮助的话你应该去[https://forum.vuejs.org/c/chinese](https://forum.vuejs.org/c/chinese)，而不是提issue
