### ISSUE TITLE
Improve documentation & searchability for v-on's .native modifier

### ISSUE THREAD

**Issue by alexsasharegan** [vuejs/vue#6003]
### What problem does this feature solve?
# TL;DR;
- Makes understanding native event binding on custom Vue components more accessible. 
- Also reduces downstream issue load on component libraries.

As component libraries of custom components become more prevalent, authors have one of two choice: re-emit all/common events on the component, or educate users to use native binding modifier. I personally think that the `.native` modifier should become the component lib standard usage pattern because it reduces code size and the mental overhead of manually re-emitting all necessary events on a custom component.

As a contributor to the [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue/) component library, I know we get a decent amount of issues around this. We educate devs about the amazingly useful `.native` modifier, but ultimately are burdened by the limited searchability of current documentation.

### What does the proposed API look like?
The documentation on this is already sufficient, but it is not prominent. I know about this modifier, yet I still have a hard time finding it in the documentation (or google). I think the common use-case would lead a dev to search something like "listen to event on component" or "v-on not working on vue component". Having some valuable results turn up would be a big win for DX.

**Comment by LinusBorg** [comment]
Could you move this issue to the vuejs/vuejs.org repository? 

Thanks!

**Comment by alexsasharegan** [comment]
Simple copy paste fine?

**Comment by LinusBorg** [comment]
Sure!

**Comment by alexsasharegan** [comment]
Done!
