### ISSUE TITLE
luosimao人机验证 data-callback回调 无法触发 | 3part vcode can not callback the method whick data-callback props in div setted

### ISSUE THREAD

**Issue by hh23485** [vuejs/vue#6005]
### Version
2.3.4

### Reproduction link
[https://luosimao.com/docs/api/56](https://luosimao.com/docs/api/56)

### Steps to reproduce
我在项目开发里用到luosimao的人机验证组件，认证的基本逻辑如下：
1. 前台<div> <script>向luosimao服务器请求认证的图片等内容
2. 用户点击认证
3. luosimao 的js文件发送请求验证并接受结果
4. 调用div里指定的回调方法，向后台发出二次验证的请求。

前三步都好好的解决了，但是第四步失败了没有办法触发。。

***

下面是代码
``` html
<div class="l-captcha" data-site-key="***********" data-callback="myResponse"></div>
```

``` js
methods: {
    //
    myCallback(resp){
         console.log(resp);
    }
    //
}
```

当然，我也尝试了在script块内写，也没有触发，只有在index.html中编写才触发，但是这并不能满足我的需求，我希望能够了解怎么处理。

[螺丝帽文档的链接](https://luosimao.com/docs/api/56);

### What is expected?
期望能够输出响应，当然也就是被调用了

### What is actually happening?
没有触发调用

---
我需要一个人机验证的模块，但是没有办法解决这个回调问题

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by defcc** [comment]
你好，建议你去螺丝帽网站去咨询这个问题，这个问题和 Vue.js 本身无关。

**Comment by peng666** [comment]
这个问题解决了吗

**Comment by XaveScor** [comment]
Can we reject all issues on non-English language?

**Comment by hh23485** [comment]
@peng666 yes, we make a simple solution. 

we add a command in the `created` method like this:

```
window.getResponse = (resp)=>{
    console.log('get a callback');
    /**
     * do what you want.
     */
}
```

**Comment by hh23485** [comment]
@XaveScor  
I am sorry for my poor english,
but i still think the chinese is necessary.

**Comment by XaveScor** [comment]
@hh23485 no problem, my English is poor too.

**Comment by 479496771** [comment]
照你这么写还是没用啊
