### ISSUE TITLE
v-if render <!----> if haven't v-else

### ISSUE THREAD

**Issue by f1729** [vuejs/vue#6007]
### What problem does this feature solve?
When using v-if, ```<!---->``` is rendered if it is not fulfilled and no haven't v-else, this causes problems if you are using properties like previousSibling, nextSibling, since these ```<!---->``` are counted as elements of the DOM

### What does the proposed API look like?
Without ```<!---->```

**Comment by blake-newman** [comment]
This would be more inconsistent if removed as you would have different number of children in different positions at each render.

Please provide a reproduction when filing issues like this, it is difficult to understand context. Furthermore, I'm not sure why you need to go that deep into the DOM API when you could use `ref` API or many other features.
