### ISSUE TITLE
Component property default() returns undefined if set to a mix-in computed/method result

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vue#6013]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/richardtallent/qn5kpgcx/2/](https://jsfiddle.net/richardtallent/qn5kpgcx/2/)

### Steps to reproduce
1. Create a mix-in with a method or computed property.
2. Add the mix-in to a component.
3. Set a component's property to default to the result of the mix-in computed property or method.

### What is expected?
Mix-in methods and computed properties should be available when the component prop default() is evaluated, allowing the component to use mix-in logic to default properties.

### What is actually happening?
It appears the mix-in has not been added when the prop default() is evaluated, leading to the property being defaulted to undefined. 

---
I have a "locale" property on a component that defaults to the browser locale setting. I wanted to move the code that pulls the browser's locale into a mix-in so I can use it in multiple components that need localization (along with some related utility methods for localization). This would also allow me to swap out the default locale logic quickly for a number of components (for example, if I wanted to move to SSR, where the navigation object is not available).

**Comment by znck** [comment]
To my knowledge, this is the behaviour, you can't access computed properties in props.

**Comment by yyx990803** [comment]
Mixins are resolved before the instance is created. During creation props are resolved before computed properties because it's much more often for computed properties to rely on props rather than the other way around. This behavior is not going to change because changing it would be breaking - nor should it be affected by whether the props/computed are defined in mixins or not.

For your use case, I don't understand why you need a prop to default to that value - why not just use that value directly?

**Comment by richardtallent** [comment]
Thanks for the quick response! Your explanation makes sense, and the only reason I noticed the issue was in the use of a mix-in, I'm glad to see the behavior is not specific to mix-ins.

The JSFiddle example was just a minimal example of the issue. The real use cases are for a calendar control's "locale" and "date" properties. The default values for both of these involve some logic that would be convenient to locate in a mix-in so I can create other components that rely on similar logic.

The workaround is simple enough -- my component can use a computed property that defaults to the mix-in's computation rather than expecting it via the prop's default() key.

The documentation doesn't cover this limitation of prop default, I'll see if I can send up a PR to enhance that section.
