### ISSUE TITLE
how can i use different style in vue-for?

### ISSUE THREAD

**Issue by zhangyuang** [vuejs/vue#6014]
<li v-for="(item, index) in list" :style=" 'li' + index" >
				
</li>
i want to use different style in <li> i want the result is <li style='li0'></li> <li style='li1'></li> but if i write this code, i can't get the result

**Comment by javoski** [comment]
I guess what you really want is `class`:
```vue
<li v-for="(item, index) in list" :class="'li' + index"></li>
```
