### ISSUE TITLE
'Vue.set'  When changing data  'watch' invalid

### ISSUE THREAD

**Issue by bigrocs** [vuejs/vue#6016]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/4m9a3z4y/10/](https://jsfiddle.net/4m9a3z4y/10/)

### Steps to reproduce
1、One Click
2、Two Click
3、View will be updated
4、but 'handleComponentPostData'   Will only execute once （bug）

### What is expected?
Each data update is executed

### What is actually happening?
'Vue.set' will be updated when new properties are added, but 'watch' cannot be triggered when updating properties data

**Comment by JounQin** [comment]
You should use [`deep: true`](https://vuejs.org/v2/api/#vm-watch) on your watcher:
``` js
watch: {
  currentComponentPostData: {
    deep: true,
    handler: 'handleComponentPostData'
  }
}
```

**Comment by bigrocs** [comment]
@JounQin Thanks very much
