### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ahmedkhan847** [vuejs/vue#6018]
### Version
2.3.4

### Reproduction link
[https://github.com/ahmedkhan847/commentwithlaravelandvue/blob/master/resources/assets/js/components/Comments.vue](https://github.com/ahmedkhan847/commentwithlaravelandvue/blob/master/resources/assets/js/components/Comments.vue)

### Steps to reproduce
Working with vuejs as I upgraded to vuejs2 I am unable to get the length of an array exist within an array. I am unable to get its length inside a vuejs function but not in template.

```
<div class="form-row reply" v-if="comment.replies.length > 1">
                    <a v-if="viewcomment[index]" @click="showComments(index)">Hide comments {{comment.replies.length - 1}}</a>
                    <a v-else @click="showComments(index)">View more {{comment.replies.length - 1}} comments </a>
                </div>
```

### What is expected?
I was expecting to get the length of array.

### What is actually happening?
I am getting error "TypeError: Cannot read property 'length' of undefined"

**Comment by yyx990803** [comment]
This is not a valid repro because it's part of a project, and more like a question than a bug report. Please either reduce the scope to a minimal repro or ask via other channels instead.

**Comment by wostex** [comment]
@ahmedkhan847 `v-if="comment.replies && comment.replies.length > 1"` will do the trick.

Your data is empty when component is mounted (because you get it asynchronously), so you need an additional guard.

**Comment by shibnathroy** [comment]
> @ahmedkhan847 `v-if="comment.replies && comment.replies.length > 1"` will do the trick.
> 
> Your data is empty when component is mounted (because you get it asynchronously), so you need an additional guard.

Thank YOu

**Comment by drewstaylor** [comment]
The reason that led to some confusion about this is that this seems to have changed recently. I re-opened a working project from several months ago and it now fails due to this problem.

**Comment by usmanbasharmal123** [comment]
just try this it will work
v-if="comment.replies!=undefined  && comment.replies.length > 1"
