### ISSUE TITLE
Mounted relaying information over Instances

### ISSUE THREAD

**Issue by 4eveRS** [vuejs/vue#6021]
### Version
2.3.4

### Reproduction link
[https://jsbin.com/cinazekaju/edit?html,css,js,console,output](https://jsbin.com/cinazekaju/edit?html,css,js,console,output)

### Steps to reproduce
Create two instances, make one really work (Create element that bind the instance to DOM) and left the other without an element to bind vue. Create functions/console.log on the second and make it run.

### What is expected?
In my opinion if the element to bind the instance is not available it should not run or have and option to not allow it to run.

### What is actually happening?
Even if there is no binding element, the function runs, causing a lot of problems.

---
 I'm working with Electron and Vue, and since in bundling it all in one .js file and working with dynamic elements, I need to make some functions to work only after the page is mounted. This problem relays all my console.log, functions and listeners through all the windows of Electron because of the bundle, causing a major performance drop and makes the functions available in other vue instances.

**Comment by posva** [comment]
Thanks for opening the issue. When adding the `el` option to the Vue constructor, it'll mount automatically. If you want to control when it mounts, you can remove the `el` property and then call `$mount('#app')` on the result. This way you can run your own checks before mounting 🙂
