### ISSUE TITLE
v-if render <!----> if haven't v-else

### ISSUE THREAD

**Issue by f1729** [vuejs/vue#6023]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/44430/](https://jsfiddle.net/50wL7mdz/44430/)

### Steps to reproduce
First set v-if before and after of a element, without v-else, select element by js, nextSibling and previousSibling (are not what they should) are ```<!---->``` (#text DOM).

### What is expected?
I would expect v-if not to return ```<!---->```. I should not return anything.

### What is actually happening?
v-if return ```<!---->```, if not haven't 'v-else'. This requires having a ``` <div v-else></div>```.

---
I leave an image of the DOM
http://i.imgur.com/b6wf4K5.png

**Comment by posva** [comment]
The comments are necessary and actually make things more consistent for you, as blake pointed out in #6007

You can also use refs instead btw: https://vuejs.org/v2/api/#ref
