### ISSUE TITLE
Nested transitions not engaging JavaScript leave hooks in child component using v-if

### ISSUE THREAD

**Issue by manas522** [vuejs/vue#6027]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/singlapradeep27/x0an4cup/5/](https://jsfiddle.net/singlapradeep27/x0an4cup/5/)

### Steps to reproduce
1) Click on Toggle Button (to toggle v-if flag of parent)
2) In console, parent leave callback is triggered but not the child leave callback
3) But it work in the case of enter callback

### What is expected?
Child's leave hook callback should be triggered.

### What is actually happening?
Only parent leave callback is triggered but not the child leave callback

---
In v-show, leave callback of child and parent are getting triggered.
But in the case if v-if on parent leave callback is triggered

**Comment by singlapradeep27** [comment]
I am also facing same issue. is there workaround?

**Comment by yyx990803** [comment]
This is expected behavior. The `v-if` controls the `<div>` of the outer transition, there's nothing that should trigger the hooks of the inner transition - the inner transition has a constant child that is never toggled. It should not and does not trigger regardless of using `v-if` or `v-show`.
