### ISSUE TITLE
页面打开时候，ajax异步请求了数据，然后需要操作dom

### ISSUE THREAD

**Issue by acodercat** [vuejs/vue#6031]
**Version**

2.3.4

**Reproduction link**

页面打开时候，ajax异步请求了数据，然后在mounted里面操作dom，但是无法操作

**What is expected?**

页面打开时候，ajax异步请求了数据，然后需要操作dom

**What is actually happening?**

页面打开时候，ajax异步请求了数据，然后需要操作dom

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue, especially adding a repro.
Thanks!
