### ISSUE TITLE
Component render 4 times

### ISSUE THREAD

**Issue by bleekbless** [vuejs/vue#6033]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
When I try to load a component it load 4 times before it shows.

### What is expected?
Expect to render/load the component only one time

### What is actually happening?
The component actually loads 4 times

**Comment by jonataswalker** [comment]
Where do see a component in the fiddle?

**Comment by DarynHolmes** [comment]
How do you know this is loading 4 times?

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
