### ISSUE TITLE
In v-for loop binding data using function can not be updated 

### ISSUE THREAD

**Issue by adrian999999** [vuejs/vue#6034]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/8ren7sdv/](https://jsfiddle.net/8ren7sdv/)

### Steps to reproduce
I want to binding data dynamically from a v-for loop for `timeslots` in `<timeslots>` components.
But `timeslots` can not be updated when `this.weekslots` changes

### What is expected?
`timeslots` need to be updated when  `this.weekslots`changes

### What is actually happening?
It did not change

**Comment by yyx990803** [comment]
This is not a valid reproduction because we can't run it. Please respect maintainers' time and provide something that can actually be debugged.
