### ISSUE TITLE
vue2.0 指令配合v-if v-else 导致bind生命周期binding和el不一致问题

### ISSUE THREAD

**Issue by AndyZhangChuan** [vuejs/vue#6035]
### Version
2.2.6

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
- step1: 使用自定义指令

```javascript
<img v-log:touchend="SelfieBannerShare" log-key="SelfieBannerShare" class="float-entrance-vote" :src="cdn   'images/selfie_canvass_float_banner.png'" v-if="active" @click="shareHandler()">
<img v-log:touchend="SelfieBannerVote" log-key="SelfieBannerVote" class="float-entrance-vote" :src="cdn   'images/selfie_vote_float_banner.png'" v-else @click="goToVote()">
```
- step2:在bind生命周期打印自定义指令

```javascript

     Vue.directive('log', {
            acceptStatement: true,

            bind (el, binding, vnode) {
                if(binding.expression == 'SelfieBannerShare' || binding.expression == 'SelfieBannerVote'){
                    console.log(el);
                    console.log("binding.expression=======" binding.expression "---" binding.arg);
                }
               
            },
            update (el, binding, vnode) {
                
            },

            unbind (el, binding, vnode) {
                vueLog.Statics.unbindDirective(el);
            }
        });

```

### What is expected?
```
<img log-key="SelfieBannerShare" src="./images/selfie_canvass_float_banner.png" class="float-entrance-vote">

binding.expression=======SelfieBannerShare---touchend
```

### What is actually happening?
```
<img log-key="SelfieBannerShare" src="./images/selfie_canvass_float_banner.png" class="float-entrance-vote">

binding.expression=======SelfieBannerVote---touchend

```

**Comment by jkzing** [comment]
请提供一个可以运行的repro link，比如[jsfiddle.net](jsfiddle.net)

**Comment by yyx990803** [comment]
以后 repro link 乱填的统一直接关闭。

**Comment by defcc** [comment]
Yes, maybe we could check more context via the bot, I'll check it and have a try.

**Comment by AndyZhangChuan** [comment]
Ok  and sorry, it's my first time to use it.

**Comment by AndyZhangChuan** [comment]
1. I have tried again,   add debug info  'img.src'.  It's amazing!   el  is not compare with  el.src！

```
console.log("update......"+binding.expression);
console.log(el);
console.log(el.src);
```
2. But  i use  v-if  to change v-else  ,the result is all right.Does this involve component reuse when is use v-if company with v-else?
<img v-log:touchend="SelfieBannerShare" log-key="SelfieBannerShare" class="float-entrance-vote" :src="cdn + 'images/selfie_canvass_float_banner.png'" v-if="active" @click="shareHandler()">
                <img v-log:touchend="SelfieBannerVote" log-key="SelfieBannerVote" class="float-entrance-vote" :src="cdn + 'images/selfie_vote_float_banner.png'" v-if='!active' @click="goToVote()">

**Comment by javoski** [comment]
The element have been reused during re-render process, so there's exactly only one DOM element and the directive bind hook will only call one time. Look at [https://jsfiddle.net/xujiongbo/487tzf9k/](https://jsfiddle.net/xujiongbo/487tzf9k/).
I'm not sure if this is expected, but it's easy to work around it, like adding different keys or different modifiers.
```html
<!--keys-->
<img v-log="v1" key="img1">
<img v-log="v2" key="img2">

<!--modifiers-->
<img v-log.1="v1">
<img v-log.2="v2">
```
