### ISSUE TITLE
vue（v2.1.8）在Android（v6.0.1）的微信（v6.5.8）内置浏览器，第一次进入某个有css3动效的页面后，整个页面渲染卡住

### ISSUE THREAD

**Issue by xuyongtao** [vuejs/vue#6036]
### Version
2.1.8

### Reproduction link
[http://h5.qmin91.com/test](http://h5.qmin91.com/test)

### Steps to reproduce
1、微信直接打开 http://h5.qmin91.com/test

### What is expected?
红色框框有动效

### What is actually happening?
1、第一次进入页面，页面卡住
2、在当前页面刷新就有了效果

**Comment by yyx990803** [comment]
1. 版本太旧
2. 重现打不开
3. 这样的重现即使能打开，没有源码也没办法 debug
