### ISSUE TITLE
Improvement: Declarable events that may require a listener 

### ISSUE THREAD

**Issue by mofux** [vuejs/vue#6040]
### What problem does this feature solve?
Sometimes it would be useful if a component would know if the consumer has registered an event listener. For example, an autocomplete input might ask for suggestions like this: 
```
this.$emit('suggest', search, (suggestions) => {
   // we only get here if somebody consumes this event and answers this callback
})
```

If nobody is listening to this event, the component will be stuck.

### What does the proposed API look like?
I can see two ways to solve this:

**A. (Preferred): Make events declarable (similar to props)**

```javascript
// vue component definition
{
  props: ['value'],

  // new and optional, the "emits" declaration
  emits: {
    suggest: {

       // if true, there has to be a listener for this event
       // otherwise Vue will throw an exception
       required: true,

       // optional, provide a list of arguments that are emitted with the event
       // they might get checked when $emit
       args: [
          { name: 'term', type: String, required: false, default: '' },
          { name: 'callback', type: Function, required: true }
       ]
     }
  }
}
```

I like this notation, because currently, there is no easy way to know what events are emitted by a component.
Also, it would not conflict with the current way, it's only extra information that can be useful.

**B: Add a function to the Vue instance that allows to check for listeners**
```javascript
// returns true or false
this.$hasListeners('submit')
```

**Comment by znck** [comment]
There should be something like this but I feel above API is too verbose.

**Comment by mofux** [comment]
Yep, I think there should be shortcuts, like with props:

```javascript

// simple, just for documentation really
{
  emits: ['suggest']
}

// simple, suggest event must be bound
{
  emits: { suggest: true }
}

// props style
{
  emits: { 
    suggest: { required: true }
  }
}

// with argument documentation & validation on $emit
{
  emits: {
   suggest: {
       required: true,
       args: [
          { name: 'term', type: String, required: false, default: '' },
          { name: 'callback', type: Function, required: true }
       ]
     }
  }
}

**Comment by mofux** [comment]
We could also offer a shortcut to describe the `args`:

```javascript
{
  // arguments, no validation, just for documentation really
  args: ['term', 'callback']
}
```

**Comment by znck** [comment]
Thoughts? 

/ping @posva @chrisvfritz @defcc @LinusBorg

**Comment by envomer** [comment]
i have been thinking the same thing... 👍

**Comment by fnlctrl** [comment]
You can actually pass a function as prop to be an event handler, so it's easier to check whether it exists.
In your case, you can declare a `onSuggest` prop,
so instead of 
```javascript
this.$emit('suggest', search, (suggestions) => {
   // we only get here if somebody consumes this event and answers this callback
})
```
You use
```javascript
if (this.onSuggest) {
  this.onSuggest(search,  suggestions)
}
```

**Comment by LinusBorg** [comment]
I tend to agree with @fnlctrl - we already can do this by passing callbacks through props. 

Adding a enw API  will further increase API surface and code size fo the library for little gain. As we just recently discussed that the API should not be added to unless the feature has sufficient use for a large group of people and can't be implented  with currently available options with reasonable effort.

**Comment by mofux** [comment]
I guess the problem I really want to target with this request is to have a standardised, documented way to describe the events that a component emits. At the moment one has to rely on component authors to either describe the events through code comments, or through some external documentation. I often find myself scanning the source code of components to figure out which events I can consume. Another benefit of this is that documentation generators could pull this information.

After all, in terms of functionality, this has no priority because (as mentioned by @fnlctrl) there are alternative ways to pass callbacks. 

I just wanted to point out a useful case where emitter definition is not just self-satisfaction.

**Comment by yyx990803** [comment]
For me, the whole point about events is that it's decoupled - you don't have to care whether there is a listener or how many listeners there are... documentation seems to be a whole different issue, I don't think that's the responsibility for the API. Yes, it's nice to have somewhat self-documenting code, but adding an API just so that the code can be self documenting seems to be the wrong approach to me.

**Comment by mofux** [comment]
I agree, as long as it doesn't add much value other than for documentation purposes it's not worth it. Thanks for your help and thoughts on this topic 👍
