### ISSUE TITLE
Nicer syntax for default scoped slot

### ISSUE THREAD

**Issue by blocka** [vuejs/vue#6042]
### What problem does this feature solve?
I use scoped slots a lot, and it seems to be the extra <template> is superfluous, and adds extra noise. I'm proposing that `scope` can be placed on the component itself. Of course, we would have to sacrifice a prop called "scope" (or would we?) but I think it's worth it.

### What does the proposed API look like?
```
<MyComponent scope="props">
   {{props}}
</MyComponent>
```

**Comment by yyx990803** [comment]
`<template>` was specifically used to avoid the ambiguous use of `scope` in scoped slot vs. props. I agree it's a bit verbose but IMO it's necessary to ensure you can always instantly notice a scoped slot when you read the code later.

**Comment by calebporzio** [comment]
Wondering if we can reconsider this cleaner syntax.

I don't see as much of a problem now that we use `slot-scope` instead of just `scope`.

Scoped slots are one of the most powerful features in Vue IMO and to be forced into such verbose syntax is a shame.

Thanks for the gift of Vue @yyx990803 and all your hard work on it!

**Comment by Justineo** [comment]
@calebporzio It’s already [documented](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) (see the note in the end of the section) that `<template>` is no longer necessary after we change the API to `slot-scope`.

**Comment by calebporzio** [comment]
![image](https://user-images.githubusercontent.com/3670578/49518728-51111d80-f86d-11e8-8838-127b27b610d3.png)

This reads to me like you still have to have a child element to add the "slot-scope" to. This is still restricting in two scenarios:
A) I have multiple root nodes for the default slot:
```
<foo-bar slot-scope="{ foo, bar }">
    <span>{{ foo }}</span>
    <span>{{ bar }}</span>
</foo-bar>
```
B) I don't have/want a root node
```
<foo slot-scop="{ foo }">
    {{ foo }}
</foo>
```

**Comment by Justineo** [comment]
Your code examples currently have different (but existing) semantics. Elements with `slot-scope` defined serve as the root node of all content in a scoped slot.
