### ISSUE TITLE
Allow seeing what specific props have changed when watching a deep object

### ISSUE THREAD

**Issue by happilymarrieddad** [vuejs/vue#6043]
### What problem does this feature solve?
It allows for watching an object instead of having to either watch each field independently or having to parse the newVal and oldVal arrays to find out which one changed. I was thinking a third parameter to the watch function that shows what field called this update

### What does the proposed API look like?
```
vm.$watch('item',(val,oldVal,prop) => server.sendData({`${prop}`:val}),{ deep:true })
```
instead of 
```
for (let key in vm.item) {
	vm.$watch(`item.${ key }`,val => {
		server.sendData({ `${key}`:val })	
	}))
}
```
or I guess better yet
```
item: {
    handler(val,oldVal,prop) {
        server.sendData({`${prop}`:val})
    },deep:true
}
```

**Comment by defcc** [comment]
Is there any other cases we should expose the api?

**Comment by happilymarrieddad** [comment]
I'm not sure.. I just find this to be an issue all over our app. I feel like our app is pretty ugly with having to create so many watchers instead of just one object watcher. Thanks for taking the time to look at this.

**Comment by yyx990803** [comment]
You can just create a generic userland helper that exposes the API you want. Implementing this in core  would be complex due to arbitrary depth of the objects.
