### ISSUE TITLE
`ref` attribute directive should be named `v-ref`

### ISSUE THREAD

**Issue by lepieru** [vuejs/vue#6044]
Maybe the `ref` attribute directive should be named `v-ref` to be more obviously Vue-related. It seems like a classic HTML attribute to my eyes.
 
An alias should be good enough.

**Comment by yyx990803** [comment]
We have only 4 [reserved attributes](https://vuejs.org/v2/api/#Special-Attributes) and there's very little value in changing it IMO.

**Comment by lepieru** [comment]
Thank you for your answer @yyx990803See #6045

**Comment by tarwin** [comment]
This is doubly confusing because Vue seems to remove the REF attribute after rendering.

**Comment by WORMSS** [comment]
How do I tell the template to leave the ref attribute on the dom element? A 3rd party library requires the attribute to exist.

**Comment by posva** [comment]
you will have to add it back manually before the 3rd party plugin comes in, or use v-pre.


--


Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
