### ISSUE TITLE
ref attribute directive should be named v-ref

### ISSUE THREAD

**Issue by lepieru** [vuejs/vue#6045]
### What problem does this feature solve?
Maybe the `ref` attribute directive should be named `v-ref` to be more obviously Vue-related. It seems like a classic HTML attribute to my eyes.

### What does the proposed API look like?
`v-ref` should behave like `ref`.

An alias should be good enough.

**Comment by posva** [comment]
things that start with `v-` contain js expressions while others like `ref` and `key` contain just text (like HTML attributes). So this is intended to make things consistent

**Comment by lepieru** [comment]
Thank you for the clarification.
