### ISSUE TITLE
Safari input placeholder overlaping(MacOS X)

### ISSUE THREAD

**Issue by prsth** [vuejs/vue#6046]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/wp27wa42/5/](https://jsfiddle.net/wp27wa42/5/)

### Steps to reproduce
Push the button "Set Data"

### What is expected?
Placeholder changes to data (works in Chrome, Firefox)

![image](https://user-images.githubusercontent.com/4288128/27931695-c8383e86-62a3-11e7-98ec-0bf2e07b8b23.png)

### What is actually happening?
Data overlaps placeholder

![image](https://user-images.githubusercontent.com/4288128/27931676-adb8c6c0-62a3-11e7-81f3-14a6add7ecb7.png)

---
Safari 10.1.1 (12603.2.4) Mac OS X 10.12.15

**Comment by defcc** [comment]
Could not reproduce it with the same env and the steps. Anyone else could check it?

**Comment by defcc** [comment]
@prsth The version in your fiddler is vue@2.2.1, it seems to be ok here with the same env & steps.

I update it with the latest version here https://jsfiddle.net/wp27wa42/6/, and it works well too.

Anyone else could help to check it.

**Comment by yyx990803** [comment]
Cannot reproduce either (Safari 10.1.1)
