### ISSUE TITLE
在vue2中模板中所有要用到数据必须定义到vue对象的data属性中

### ISSUE THREAD

**Issue by skywalker2013** [vuejs/vue#6047]
### What problem does this feature solve?
想比较vue1.x不强制做这种定义，无论在模板中定义了什么数据，在js中随时可以向vue对象中存取，很方便。现在vue2中每次定义一个vue对象，光data这一个属性就要定义一大长串，实在是不方便。

### What does the proposed API look like?
vue $data

**Comment by yyx990803** [comment]
这是为了可维护性考虑。一味的图方便后期维护会出问题，就好像你写数据库不写 schema 一样，后面出了问题都不知道数据是哪里定义的。
