### ISSUE TITLE
Unexpected click event propagation across different div elements, when they each have a class

### ISSUE THREAD

**Issue by jlem** [vuejs/vue#6048]
### Version
2.3.4

### Reproduction link
[https://codepen.io/anon/pen/bRxpJg?editors=1111](https://codepen.io/anon/pen/bRxpJg?editors=1111)

### Steps to reproduce
It's best to just look at the codepen reproduction, but the gist of it is this:

1. Create two divs and assign them classes (can be same class, or different classes), but they must have a class attribute.
2. Control their visibility using `v-if` and a flag of some kind (one being shown if true, and the other if false)
3. Give one of the divs themselves a click handler that sets the flag to true
4. Put a clickable cancel element inside of the other with a different click handler that sets the flag to false, but do not put a click handler on the div itself.
5. Observe that clicking the cancel button/element's click handler also ends up calling the click handler of the previously hidden div again (open console to see the log being fired unexpectedly).

### What is expected?
Clicking the cancel button/element inside of one div should not also trigger a click event on the div that had been hidden.

### What is actually happening?
The click event from one div is somehow propagating to the click handler of a previously hidden div

---
In the CodePen reproduction, the first example illustrates the unexpected broken behavior whereby the "cancel" button click event is also propagating to the click handler of the div that had been hidden.

The second example shows how this behavior can be fixed by passing in the `$event` and calling `$event.stopImmediatePropagation()`, but it is strange and unexpected that this should even be necessary.

The third example shows how omitting the `class` attribute from the divs will also fix this behavior, but this is obviously not a workable solution. It just illustrates the strangeness of the issue.

**Comment by jkzing** [comment]
Vue is reusing the `div` elements between `v-if` conditions, so you may need add `key` on each div like:

``` vue
<div class="foo" key="foo" v-if="!isCreateMode" @click="startCreateMode()">Click Me!</div>
<div class="bar" key="bar" v-else>
  Click That -> <button @click="cancelCreateMode()">Cancel</button>
```

**Comment by LinusBorg** [comment]
Closing as @jkzing is right.
