### ISSUE TITLE
Here's a [vue-langauge-server] issue in my vscode! The below code snippet contains only "is" and it says that it should hav ":is" , also when i replace "is" with ":is" then that two components just vanishes and does'nt display at all. Please suggest that what should i use and explain the difference if possible. Thanks

### ISSUE THREAD

**Issue by Meetzaveri** [vuejs/vue#6049]
<div v-if="isLoaded">
		<component is="navbar" :content="{nav_section,nav_more_section}"></component>
		<component is="banner" :content="data.banner_section"></component>
		<component v-for="item in data.section_format" :key="item.name+'index'" :is='item.name' :content="item.data"></component>
		<component v-for="item in data.more_section" :key="item.name+'index'" :is='item.name' :content="item.data"></component>
	</div>

**Comment by Meetzaveri** [comment]
But how can i solve this issue?

**Comment by jkzing** [comment]
Please follow the [issue reporting guiddlines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines).

And for `vue-language-server` issue should be reported in [vetur](https://github.com/vuejs/vetur).
