### ISSUE TITLE
failed to resolve filter

### ISSUE THREAD

**Issue by hibin101** [vuejs/vue#6050]
when i use filter in VUE  like 
`<p>{{noteItem.getModifyTime() | DateFormat 'yyyy-mm-dd HH:MM'}}</p>`

and then template parse like 
`_vm._f("DateFormat 'yyyy-mm-dd HH:MM'")(_vm.noteItem.getModifyTime())
`
the filter params cannot set

**Comment by sqal** [comment]
that's not how you should pass argument to the filter, please read the docs -  https://vuejs.org/v2/guide/syntax.html#Filters
