### ISSUE TITLE
Modify `vnode.data.attrs results` no effect in render function

### ISSUE THREAD

**Issue by Plasmatium** [vuejs/vue#6052]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/Plasmatium/L5ws0d88/20/](https://jsfiddle.net/Plasmatium/L5ws0d88/20/)

### Steps to reproduce
1. Open the browser dev-tool, inspect the element of `Menu List` dropdown menu.
2. Click `Menu List` dropdown button, watch the dom, its parent got new class: 'show', but nothing happand on itself.
3. Click outside the dropdown menu, 'show' is removed from its parent's class

You can not click dropdown menu to close it (means remove 'show' in its parent's class)

### What is expected?
The attribute `close-expand` should be added in the dropdown button (in the `<a role="button" href="#!"`...)

### What is actually happening?
Nothing happend, the attribute `close-expand` is not inserted into the dropdown button

---
In JAVASCRIPT panel -> line 69, two attrs is added, but only the static attr is rendered(`close-expand` here).

In line 76, the same to add `close-expand`, the only difference is that it is related on this.isExpand. As described above in reproduce steps, nothing happend.

If digging into the infomation in console, the vnode.data.attrs is inconsistent with vnode.elm.attributes (`close-expend` in vnode.data.attrs, but not in vnode.elm.attributes or dom)

Is anything I missed in document? I know the vnode should use only once, but I just modified it, not reuse.

**Comment by Plasmatium** [comment]
Meanwhile, I created a more simple reproduction [here](https://jsfiddle.net/Plasmatium/ka0oo7oh/2/)

`test0` is always red because `dom0.attrs['expand'] = ''`, but `test1` is not toggle color as expected. See the console in dev-tools for more infomation.

**Comment by simplesmiler** [comment]
Similar to https://github.com/vuejs/vue/issues/5986, parent did not update, so the slot content has the same vdom reference as before, leading to vdom patcher not updating the dom.

In short, you should treat slot content as immutable entity, and modify it accordingly, e.g.: https://jsfiddle.net/ka0oo7oh/3/

**Comment by Plasmatium** [comment]
Thank you @simplesmiler very very much.

Is this similar to react pureComponent? __All references__ on the path to a certain variable of an object should be a __new__ one, so `object-path-immutable` made this happen.

I tried below and also worked:
```javascript
let dom2 = Object.assign({}, dom1)
dom2.data = Object.assign({}, dom1.data)
dom2.data.attrs = Object.assign({}, dom1.data.attrs)
```

And thank you very much!

**Comment by yyx990803** [comment]
@Plasmatium that is correct - it's safer to always clone a new node. We do have an internal helper for doing that, and will likely expose it in future versions.
