### ISSUE TITLE
Filter dont work on v-html

### ISSUE THREAD

**Issue by prsolucoes** [vuejs/vue#6055]
Hi,

Im trying filter a value:

```
<span v-html="props.row.status | hcStatusFormat"></span>
```

But the only way today that works is:

```
<span v-html="$options.filters.hcStatusFormat(props.row.status)"></span>
```

Im using this component:
https://buefy.github.io/#/documentation/table

Thanks.

**Comment by sirlancelot** [comment]
That is by design in Vue 2.x: http://vuejs.org/v2/guide/syntax.html#Filters
