### ISSUE TITLE
vue component doesn't seem to work with razor partial view

### ISSUE THREAD

**Issue by arisliang** [vuejs/vue#6062]
For example, if the component resides in a partial view, the razor tags in the partial view doesn't seem to get rendered. Is this because component will be rendered as string, so any server templating engine won't work?

E.g.,
```
<!-- component template -->
<script type="text/x-template" id="component">
    <div>
        <form asp-controller="Home" asp-action="Index">

        </form>
    </div>
</script>
```
These razor tag doesn't get rendered if it's in a partial view component, however if they're in a normal view, they do seem to get rendered.

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Discord server](https://vue-land.js.org/), [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
