### ISSUE TITLE
v-model 是否可以使用某种方式保持dom的默认值

### ISSUE THREAD

**Issue by blqw** [vuejs/vue#6063]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/45667/](https://jsfiddle.net/50wL7mdz/45667/)

### Steps to reproduce
在一些比较特殊的情况下, input可能会存在默认值
是否可以使用某种修饰符, 例如 `v-model.default="value"`   来保持dom元素的默认值

### What is expected?
初始页面中 `<input value="1234" v-model="value" />`
使用v-model绑定后   vm.value 得到input的默认值  "1234"

### What is actually happening?
初始页面中 `<input value="1234" v-model="value" />`
使用v-model绑定后   vm.value 为空字符串  input.value 等于空字符串

**Comment by yyx990803** [comment]
`v-model` 文档里已经说明，应当以 JavaScript data 中的值作为 source of truth - 所以应当尽量以在 js 里面初始化初始值。让模板内容影响应用状态属于不建议的行为。
