### ISSUE TITLE
How to access (<typeof Vue)Component).options with typescript

### ISSUE THREAD

**Issue by blocka** [vuejs/vue#6064]
Each Vue constructor has an options properties which exposes the `ComponentOptions<T>` for that component. I see in vue-loader this is used to inject the `render` method. I also need to inject options into a constructor, however typescript complains that there is no such property on `typeof Vue`.
A quick fix would be to add options as a static property on Vue...except that it's technically not a static property, as in it's not shared across all vue instances.

**Comment by blocka** [comment]
My current "userland" fix is to do this: `(<ComponentOptions<Vue>>(<any>Component)).options`

**Comment by ktsn** [comment]
It is not declared in d.ts intentionally since it is actually a undocumented/private API.

**Comment by blocka** [comment]
When making an HoC, since vue requires props to be declared up front, we need to grab them from the wrapped component. How can that be done without reaching into options?

**Comment by yyx990803** [comment]
We may consider exposing this in the definition in the future, but closing for now since there's an easy workaround.

**Comment by blocka** [comment]
Just wanted to point out that @ktsn himself is relying on this (https://github.com/ktsn/vuex-connect/blob/master/src/connect.js#L139)
