### ISSUE TITLE
Nested transition groups, key/values not accessible

### ISSUE THREAD

**Issue by chasegiunta** [vuejs/vue#6068]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/kiddjones/hg3grrrt/](https://jsfiddle.net/kiddjones/hg3grrrt/)

### Steps to reproduce
Click on one of the list items. Console will warn about "value" not being available on transition groups, but if you uncomment the other ul, you can see that `value` _is_ and should be accessible.

### What is expected?
`value` should be accessible

### What is actually happening?
`value` is not accessible, also some other wonky things are not working correctly with nested transition groups. Example: `v-for="i in [1,2,3]"` will not function in a child transition group.

---
@posva did find a workaround: wrapping the child transition group in a template https://jsfiddle.net/posva/8o5kw19n/ — though, not the expected steps for accomplishing nested transition groups

**Comment by yyx990803** [comment]
Ok... so this is not a bug in Vue, but because per HTML you cannot nest `<li>` inside `<li>`, so the template gets re-formatted by the browser before passed to Vue's template parser. This would work  if using a pure-string template, but you should probably avoid it regardless.

**Comment by posva** [comment]
Argh, sorry, I didn't think `li` were also limited in that aspect 📝

**Comment by chasegiunta** [comment]
Thanks for taking a look at it @yyx990803 & @posva, but with all due respect, I wasn't trying to nest `<li>` inside a `<li>`. This is an attempt at a common practice of nesting `<ul>` inside of `<li>` (especially with navigations). I understand the limitation may be due to an order of events out of Vue's control, but I still feel like maybe this is something worth addressing.

@posva's workaround for wrapping the child `<ul>` in a template isn't difficult in the least bit, so _**is there a significant reason**_ I should be avoiding it? Alternatively, is there potentially some way to bypass the browser reformatting by using some sort of Vue custom element, setting a `tag` attribute for the child `<li>`? eg:

```
<transition-group name="list" tag="ul" appear>
  <custom-element tag="li" v-for="child in value" :key="child" class="list-item">{{child}}</custom-element>
</transition-group>
```

Appreciate you both!

**Comment by posva** [comment]
It's a limitation of html but the problem wont appear when compiling
templates (using vue files)

**Comment by yyx990803** [comment]
To get around it, use a string template instead of in-DOM template. See the difference in logs: https://jsfiddle.net/LeLexkgz/
