### ISSUE TITLE
Strange behavior with input type="number"

### ISSUE THREAD

**Issue by sinceow** [vuejs/vue#6069]
### Version
2.3.4

### Reproduction link
[https://codepen.io/sinceow/pen/dRQaPW](https://codepen.io/sinceow/pen/dRQaPW)

### Steps to reproduce
I want to build a input with 6 digital. The code above woks fine until I enter '0' more then 6 times.
'val' in Vue model is '000000', but the display is '00000000'

### What is expected?
I think it's a bug

### What is actually happening?
I don't know

**Comment by nickmessing** [comment]
@yyx990803, looks like [this](https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/dom-props.js#L73) check is the reason, is this behaviour expected?

P.S. `toNumber('03') === toNumber('3')` another potential case.
