### ISSUE TITLE
vm.$root.$vnode is undefined??

### ISSUE THREAD

**Issue by anchengjian** [vuejs/vue#6070]
### Version
2.3.4

### Reproduction link
[https://jsbin.com/dezebanezi/3/edit?html,js,console,output](https://jsbin.com/dezebanezi/3/edit?html,js,console,output)

### Steps to reproduce
``` javascript
console.log(this.$root.$vnode)
```

### What is expected?
`vm.$root.$vnode` is `$vnode` of root component.

### What is actually happening?
`vm.$root.$vnode` is `undefined`.

**Comment by yyx990803** [comment]
`$vnode` stands for "placeholder that represents a component in its parent's vdom tree". A root component has no parent vdom tree.

**Comment by javoski** [comment]
Maybe what you need is `vm.$root._vnode`.
