### ISSUE TITLE
dynamic prop array does not reactive when replacing the prop with new array in parent scope

### ISSUE THREAD

**Issue by jingz** [vuejs/vue#6071]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/72p856te/](https://jsfiddle.net/72p856te/)

### Steps to reproduce
wait for 500 milliseconds for replacing the array with new data ( Ajax simulation )

### What is expected?
the child component should re-render the data that dynamically bind from the parent (as an array) when the parent's change

### What is actually happening?
the child component did re-render with data in the array

**Comment by posva** [comment]
That is expected behaviour, the render function is reacting to the data property not the prop ( which is changing). Here's a working version: https://jsfiddle.net/posva/2rpspzvL/
