### ISSUE TITLE
一个工程如何使用2个router-view，并且可以指定渲染

### ISSUE THREAD

**Issue by gecaitao** [vuejs/vue#6075]
### What problem does this feature solve?
例如
<router-view name="a"></routet-view>
<router-view name="b"></routet-view>
可以指定渲染到a

### What does the proposed API look like?
例如
<router-view name="a"></routet-view>
<router-view name="b"></routet-view>
可以指定渲染到a

**Comment by jkzing** [comment]
你可以在两个router-view上分别写`v-if`和`v-else`。
也可以在你的两个router-view外面再包一层组件，然后在外面用一个router-view加载。

PS: 类似问题请至[https://forum.vuejs.org/](https://forum.vuejs.org/)提问

**Comment by javoski** [comment]
See [http://router.vuejs.org/en/essentials/named-views.html](http://router.vuejs.org/en/essentials/named-views.html)
