### ISSUE TITLE
assigning to a computed property without setter does not fail

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#6078]
### What problem does this feature solve?
If I have a computed property with only getter, setter is set to a noop. If I then try to assign to such a computed property, nothing happens. This can hide programming errors.

### What does the proposed API look like?
I would suggest that when not in production, instead of a noop a warning function would be assigned to a setter and a warning message would be printed if one tries to assign a value to such computer property.

Alternatively, output of computed property without setter could be configured without a setter at all, as a read-only property.

**Comment by Plortinus** [comment]
@yyx990803 
Now with the vue version `v2.4.2`, when I put a `state` into the computed property by the `mapState` helper function,I get a warn `[Vue warn]: Computed property "isLoading" was assigned to but it has no setter.`

I couldn't found `setter` in the vuex state,so I think the warn may should consider this condition.

codes like this:
```js
// store.js
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const state = {
  isLoading: false
}

const mutations = {
  updateLoadingStatus (state, payload) {
    state.isLoading = payload.isLoading
  }
}

export default new Vuex.Store({
  state,
  mutations
})
```
```js
// App.vue
<template>
  <div id="app">
    <router-view></router-view>
    <loading v-model="isLoading"></loading>
  </div>
</template>

<script>
  import { Loading } from 'vux'
  import { mapState } from 'vuex'

  export default {
    name: 'app',
    components: {
      Loading
    },
    computed: {
      ...mapState({
        isLoading: state => state.isLoading
      })
      }
    }
  }
</script>
```

**Comment by posva** [comment]
@Plortinus That happens because of the `v-model`. It' trying to change the value of `isLoading` but mapState will only create getters. You can probably make things work by binding the `value` to the `isLoading` and then handle the update by committing the mutations on the `@input`

**Comment by Plortinus** [comment]
@posva 

Thanks a lot.I tried to use the `sync` modifier to handle this problem.It works.

But I am wondering if my solution is a good practice or not.The purpose of these codes is to show a loading toast when switch one page to another page in an SPA.

```js
<template>
  <div id="app">
    <router-view></router-view>
    <loading :value.sync="isLoading"></loading>
  </div>
</template>

<script>
  import { Loading } from 'vux'
  import { mapState } from 'vuex'

  export default {
    name: 'app',
    components: {
      Loading
    },
    computed: {
      ...mapState({
        isLoading: state => state.isLoading
      })
    }
  }
</script>
```

**Comment by LinusBorg** [comment]
Why/when would the `<loading>` component ever want to change the value of "isLoading"? That component can hardly know when the process is over, can it?

**Comment by Plortinus** [comment]
I update the value of `isLoading` before/after the `router` action.
```js
router.beforeEach(function (to, from, next) {
  store.commit('updateLoadingStatus', { isLoading: true })
  next()
})

router.afterEach(function (to) {
  store.commit('updateLoadingStatus', { isLoading: false })
})
```

**Comment by LinusBorg** [comment]
Yeah sure, but then that value will go from your parent component *down* to the `<loading>` compoent, not up *from* the loading component.

Maybe you have a missunderstanding how props work, at least in combination with computed properties?

**Comment by CherishLyf** [comment]
https://stackoverflow.com/questions/46106037/vuex-computed-property-name-was-assigned-to-but-it-has-no-setter 刚看到的

**Comment by Mumbere7** [comment]
okay mate this is a snippet of my code maybe it may help you figure out where you are wrong but i Think it should be easier now since i also had the same error but with getter

computed: {
    comparePasswords() {
      return this.password !== this.confirmPassword
        ? "Passwoeds do not match!"
        : "";
    },
    user() {
      return this.$store.getters.user;
    }
  },

  watch: {
    user: function(value) {
      if (value !== null && value !== undefined) {
        this.$router.push("/");
      }
    }
  },
