### ISSUE TITLE
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by kumbharketanm** [vuejs/vue#6080]
I'm getting this error from last two day's. Before two day's it was working fine, but when i done same thing in other project it is throwing this error & the project that i were worked also throwing the same error. So anybody please help me.

**Comment by javoski** [comment]
Have you call `Vue.use(VueRouter)` to install `vue-router`?

**Comment by weiqiujuan** [comment]
你好，解决了吗？
