### ISSUE TITLE
Could we have export as namespace in typescript definition for js?

### ISSUE THREAD

**Issue by Thaina** [vuejs/vue#6082]
### What problem does this feature solve?
I am using vscode to write javascript and using `<reference path>` tag to add `.d.ts` for intellisense instead of import or require. It does not work with vue's `index.d.ts`

### What does the proposed API look like?
for make it work for vue I was told I need to add `export as namespace Vue;` at the end of `index.d.ts` file here

https://github.com/vuejs/vue/blob/dev/types/index.d.ts#L37

Without it intellisense for js does not work in vscode

This is the working sample I was did

![image](https://user-images.githubusercontent.com/1042507/28132124-1dc8c5d4-6766-11e7-9d2b-fed7f25a682c.png)

I don't know would it impact anything. It just work in my case that I use `<script>` tag to get vue so I need just intellisense here

This solution was guided from this thread : https://github.com/Microsoft/TypeScript/issues/17093

**Comment by yyx990803** [comment]
I don't think this is necessary as there are many users who are successfully using current Vue types in VSCode. Maybe @ktsn or @octref have some idea? Either way this is not actionable.

**Comment by ktsn** [comment]
Hmm, I don't think we can add `export as namespace Vue` in the current declaration because it seems to expose Vue's typings in global namespace. The declaration is intentionally written for module usages as it is shipped via npm.

So I would suggest you to declare a local declaration file in your project to expose Vue types in global.

```ts
// vue.global.d.ts
import Vue = require('vue')

export = Vue
export as namespace Vue
```

**Comment by Thaina** [comment]
Thank you for your suggestion

**Comment by octref** [comment]
Seems you are doing it wrong here. https://github.com/Microsoft/TypeScript/issues/17093

We import Vue for you for all *.vue files: https://github.com/vuejs/vetur/blob/master/server/src/modes/script/bridge.ts#L9

See https://github.com/octref/veturpack for a sample setup.

**Comment by Thaina** [comment]
@octref I know that I could use `import` for npm. But I prefer using `<script src="cdn">` and use vue as global variable instead of `import`

What happen here is I use plain javascript. But I just want to have intellisense in the same way as importing. It is possible for javascript in vscode to get intellisense with jsdoc comment `<reference src="some.d.ts">` and I prefer that

**Comment by octref** [comment]
Vetur only covers SFC for now. We don't have much plan for supporting html file that imports Vue through CDN. That's like general js-in-html support and you should open issues with VSCode.
