### ISSUE TITLE
Setter doesn't invoke if computed property is object

### ISSUE THREAD

**Issue by andycaramba** [vuejs/vue#6083]
### Version
2.3.4

### Reproduction link
[http://jsbin.com/cejakiw/edit?html,js,console,output](http://jsbin.com/cejakiw/edit?html,js,console,output)

### Steps to reproduce
* Open jsbin link
* Edit any form inputs in output view
* See console view, setter doesn't invoke and no console output after editing inputs

### What is expected?
Setter need to be worked for object computed properties

### What is actually happening?
Setter only works for scalar computed properties. See https://jsbin.com/navedoh/edit?html,js,console,output for example

---
I read the [Reactivity in Depth documentation](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats), but I do not understand how I can apply it to my case without using methods

**Comment by posva** [comment]
This is working as expected, the setter will only work when setting the value (`user` in your jsbin)
