### ISSUE TITLE
Can support props unfold？

### ISSUE THREAD

**Issue by lavyun** [vuejs/vue#6085]
### What problem does this feature solve?
Can support props unfold？ Like JSX: 

```html
<Component {...props} />
```

Beacuse I use the dynamic component,like this: 

```html
<component is="Button" type="primary">button</component>
```

I want to use 'v-for' to generate some components,but I don't know how to expand the props

### What does the proposed API look like?
```html 
<component is="Button" props="buttonProps">button</component>
```

```js
new Vue({
    data: {
        buttonProps: {
            type: 'primary',
            size: 'large',
            disabled: false
        }
    }
})
```

**Comment by JounQin** [comment]
https://vuejs.org/v2/api/#v-bind

``` vue
<!-- binding an object of attributes -->
<div v-bind="{ id: someProp, 'other-attr': otherProp }"></div>
```

**Comment by lavyun** [comment]
@JounQin Thank you, it is a sad story

**Comment by JounQin** [comment]
@lavyun If it works, please close this issue?
