### ISSUE TITLE
postinstall script error on installing 2.4.0

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#6086]
### Version
2.4.0

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/package.json#L9](https://github.com/vuejs/vue/blob/dev/package.json#L9)

### Steps to reproduce
There is no `build` folder after deploying to npm

### What is expected?
install vue 2.4.0 correctly

### What is actually happening?
> Error: Cannot find module 'D:\Workspace\GitHub\vue-ssr\node_modules\vue\build\install-hooks.js'

**Comment by shangxinbo** [comment]
I got this error too

**Comment by kangsLee** [comment]
I got this error too

**Comment by zcdll** [comment]
I got this error too

**Comment by yuu2lee4** [comment]
I got this error too
node version is8.1.3

**Comment by Ttou** [comment]
me too

**Comment by gdutwyg** [comment]
me too

**Comment by franklingu** [comment]
same here

node v4.4.5, v6.11.1. neither works

**Comment by Tazer** [comment]
me too , `yarn upgrade vue` doesn't work.

**Comment by franklingu** [comment]
npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/home/jgu/.nvm/versions/node/v6.11.1/bin/node" "/home/jgu/.nvm/versions/node/v6.11.1/bin/npm" "install" "vue"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! vue@2.4.0 postinstall: `node build/install-hooks.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue@2.4.0 postinstall script 'node build/install-hooks.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/install-hooks.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jgu/repos/trd_mon_front/npm-debug.log

**Comment by Rylai-Zihang** [comment]
me too

**Comment by ryancui-** [comment]
me too

**Comment by rkkautsar** [comment]
+1, with node v7,v8, npm v3, and yarn all fails

**Comment by tonyciou** [comment]
> vue@2.4.0 postinstall /home/tony/test/node_modules/vue
> node build/install-hooks.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/home/tony/test/node_modules/vue/build/install-hooks.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

me too, I got same error

**Comment by linhaobin** [comment]
me too

**Comment by yyx990803** [comment]
Fixed in 2.4.1

**Comment by corysimmons** [comment]
This entire thing was reported and fixed in realtime.

**Comment by luckyuns** [comment]
me too

**Comment by shirenjiuhao** [comment]
me too

**Comment by eddyerburgh** [comment]
@yyx990803 I'm happy to make a PR that deletes the `postinstall` script before commiting and publishing to npm. Unless you're already working on it
