### ISSUE TITLE
Cant install in windows 7 after this commit b5f08f3bed95e6cac47b20d3fa4148d00ffa8c55

### ISSUE THREAD

**Issue by kasselTrankos** [vuejs/vue#6089]
Hi, 
I found this commit b5f08f3bed95e6cac47b20d3fa4148d00ffa8c55
That change the method of post install. 

C:\node-scripts\pine>npm i -D vue

> vue@2.4.0 postinstall C:\node-scripts\pine\node_modules\vue
> node build/install-hooks.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\node-scripts\pine\node_modules\vue\build\install-hooks.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
npm WARN pine@1.0.0 No description
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "vue"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! vue@2.4.0 postinstall: `node build/install-hooks.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@2.4.0 postinstall script 'node build/install-hooks.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/install-hooks.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node-scripts\pine\npm-debug.log

npm : 3.10.10
node : v6.9.5
windows 7

Thanks a lot

**Comment by jkzing** [comment]
Is [2.4.1 release](https://github.com/vuejs/vue/releases/tag/v2.4.1) fix your error?
