### ISSUE TITLE
Problem with SSR rendering and scoped css, seems SSR doesn't set 

### ISSUE THREAD

**Issue by Tazer** [vuejs/vue#6095]
### Version
2.4.1

### Reproduction link
[https://github.com/Tazer/vue-hackernews-2.0/tree/ssr-css-problem](https://github.com/Tazer/vue-hackernews-2.0/tree/ssr-css-problem)

### Steps to reproduce
Check my fork. What I did is to set ItemList.vue style to "scoped" `<style lang="stylus" scoped>` ( https://github.com/Tazer/vue-hackernews-2.0/commit/928166c6fad900b9ec171b3ae91ed27fff920a42 )

The site still looks fine and the element get the correct `data-v-xxx`. for example `.news-list-nav`

Upgrade to vue 2.4.1 the `.news-list-nav` won't get the `data-v-xxx` ( hard refresh , cause it's the server side rendering that is failing somehow. )

### What is expected?
That it should work as in vue 2.3.4
![image](https://user-images.githubusercontent.com/132698/28164380-7e72554e-67cf-11e7-84c9-20bfb2cc1491.png)

### What is actually happening?
The `data-v-xxx` aren't added on some elements and that breaks scoped styling.
![image](https://user-images.githubusercontent.com/132698/28164459-c4757d32-67cf-11e7-94a6-003cbd2dd16e.png)

**Comment by yyx990803** [comment]
This turns out to be a bug in `vue-loader`. Fixed in 12.2.2 / 13.0.2.
