### ISSUE TITLE
Directives inside transitions are unbound before leave transition ends

### ISSUE THREAD

**Issue by galenmaly** [vuejs/vue#6101]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/uucedax5/2/](https://jsfiddle.net/uucedax5/2/)

### Steps to reproduce
In the fiddle, click the button to fade in the component, then click again to fade out the component.

### What is expected?
There is a simple directive to turn text red. The directive should not be unbound until after the "leave" transition finishes. The text should be red until the end of the "leave" transition.

### What is actually happening?
The directive is unbound at the beginning of the transition, so the text is no longer red for the duration of the "leave" transition.

---
Ran into this issue when transitioning out modals that had custom directives inside of them. The unbinding removed elements from the page resulting in a jarring transition.

I have been able to work around this by polling inside the unbind() function to see if the directive is inside of a transition and not performing the unbind actions until the transition finishes.

**Comment by yyx990803** [comment]
This is expected behavior and unlikely to change because it would be technically breaking. The piece of VDOM that's being transitioned out is "destroyed" the moment the leaving transition starts. Unfortunately the polling solution might be a necessary workaround for directives that mutates the DOM directly.

**Comment by jan-thoma** [comment]
Ran in this issue too, you don't need to poll for transition just poll if the el is still present in the Dom:

`            const poll = setInterval(() =>
            {
                if(!document.contains(el))
                {
                   /* Do stuff here */
                    clearTimeout(poll)
                }
            }, 1000)`

**Comment by Akryum** [comment]
> The unbinding removed elements from the page resulting in a jarring transition.

Having elements created by directives is bad practice.

**Comment by jan-thoma** [comment]
#

> Having elements created by directives is bad practice.

For using native js plugins like packery it's the most comfortable way to go is a directive. If i destroy the packery instance on unbind() directly my layout goes down the drain, if i don't destroy i'm producing a memory leak which slows down every following instance of packery. So i think this a relevant issue.
