### ISSUE TITLE
consistent  behavior for edit props

### ISSUE THREAD

**Issue by kinanson** [vuejs/vue#6103]
### What problem does this feature solve?
From now on child component edit props will be throw error in the console without object and array.I feel that is so weird.Member will ask me why i can't edit any type but only object and array can do that.I think edit object and array is two way binding.that is so bad.

I know object and array is reference type.But I just wish can consistent this behavior.I have two suggest.
1.When edit any props throw error.
2.Don't throw any error.Because when I edit number or string doesn't reactive to parent component.So I know to emit when I want parent component bind child component edit value.

But for now on feature.I feel just do on half for edit props.Some type can edit and some type can't edit.So wired.

### What does the proposed API look like?
just see description

**Comment by KyLeoHC** [comment]
It seems that this error only happen in the development environment.This error is disappear while in production environment(using `.sync`).

**Comment by kinanson** [comment]
Not realy.Also throw on production.

**Comment by yyx990803** [comment]
First, we can only detect prop mutation on its direct binding. Detecting mutation inside Array/Object prop value adds too much overhead in both perf and complexity and is not really worth it.

Also, mutating the top-level prop binding leads to the scenario where the mutated value gets reset when the parent updates. But directly mutating nested values without changing the binding does not have this problem. (although still not recommended, it is valid usage)
