### ISSUE TITLE
Code within mounted is not executed when component is within conditional

### ISSUE THREAD

**Issue by mofman** [vuejs/vue#6110]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/4mgx2zLj/1/](https://jsfiddle.net/4mgx2zLj/1/)

### Steps to reproduce
Create two or more components on the same page within conditionals. 

### What is expected?
Once the conditions are true I expect the component to mount and run what is inside mounted.

### What is actually happening?
Only the first component runs what is in mounted. 

---
Outside of the conditions, these mount as expected.

**Comment by LinusBorg** [comment]
Vue is re-using elements and components where possible, unless you tell it otherwise:

https://vuejs.org/v2/guide/list.html#key

**Comment by mofman** [comment]
Sorry for false report, appreciate your help Linus.
