### ISSUE TITLE
Vue runs no watchers during call to print()

### ISSUE THREAD

**Issue by davidhewitt** [vuejs/vue#6111]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/nu4t338u/](https://jsfiddle.net/nu4t338u/)

### Steps to reproduce
Tested on Chrome 59. My work computer has no other browsers available for me to test on, I would be interested to hear what the behaviour is on other browsers.

1.  Set up Vue instance which uses [matchMedia()](https://developer.mozilla.org/en/docs/Web/API/Window/matchMedia) to modify some values when printing the page.
2. Trigger the page to print using [print()](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) function

### What is expected?
The mediaQueryListener captures the print change and updates the values.

Vue calls appropriate watchers and redraws.

Printed page sees redrawn images.

### What is actually happening?
The mediaQueryListener captures the print change and updates the values.

User gets printed page without any redrawn data.

Vue calls watchers AFTER print is finished.

---
The issue is that calls to print() are blocking, and (on chrome at least) this seems to mean that the Promises Vue is using for nextTick don't execute until after print() exits.

However, some javascript can run during print() calls - stuff inside media query listeners!

I had a couple of thoughts on how to resolve this.

1) perhaps Vue can use a media query listener to detect this case and change its update loop appropriately?

2) expose a Vue.forceTickNow() function which calls the queued watchers immediately. Perhaps a bit evil but then I could force the redraw by hand inside the media query listener :)

3) vm.$forceUpdate() looks like it's asynchronous - as in it also doesn't execute anything inside my media query listener. Perhaps the behaviour of forceUpdate should be synchronous?

**Comment by posva** [comment]
If print is blocking, I think there's not much we can do, however, it's easily fixable on user-land by creating a custom print function: https://jsfiddle.net/ugs0b8sn/

**Comment by davidhewitt** [comment]
Hi posva,

Unfortunately that doesn't quite work for me - I am reliant on laying out some stuff in javascript depending on the screen dimensions. I need to read the height of the element inside the css media query listener callback. Like this: https://jsfiddle.net/7zmquq4u/

You will see that the printed page doesn't show an updated value but as soon as you close the print preview the text updates with the width it measured for the page during print preview.

I have looked into CSS for my use-case but I could not find a solution, hence why I'm doing this bit of layout with javascript.

Ouch 😢

**Comment by posva** [comment]
Hmm, well you can force update with

```js
  printing.addListener(() => {
      if (printing.matches) {
			  this.measure();
        this._update(this._render())
        // or this._watcher.run()
    	}
    });
```

I'm not sure if we should expose this as a public api though because this is an edge case.

**Comment by davidhewitt** [comment]
Ah - yep `this._watcher.run()` works for me here. Agreed that it seems overkill to make it a public API.

Thanks very much for the help.
David
