### ISSUE TITLE
Vue slot grab inner content for semantic code on both sides of slot usage.

### ISSUE THREAD

**Issue by alexbowers** [vuejs/vue#6113]
### What problem does this feature solve?

It will allow an element to become a slot with its other properties on it, rather than be nested within the element you want.

The problem with the current solution for example is if you want to make a `<h1>` tag a slot, it will have some element within it, that may cause your styling to not be as desired, and semantically it makes little sense.

If you want to have a class, style, or other attributes across the application, it should be inside the template.

### What does the proposed API look like?
```
<template>
    <div class="row page-header push-down fixed-top">
        <div class="col-md-6 text-center-screens push-down-screens">
            <h1 slot-name="title" class="header text-center"></h1>
        </div>
    </div>
</template>

<div id="VueApp">
    <sb-header>
        <h1 slot="title">Stock</h1>
    </sb-header>
</div>
```

This will currently not work, the way it has to work at the moment is `<h1 class="..."><slot name="title"></slot></h1>`.

This will cause a nested `h1` tag to be made, which isn't semantic.

**Comment by alexbowers** [comment]
The desired end result is:

`<h1 class="header text-center">Stock</h1>`

**Comment by alexbowers** [comment]
Alternatively, a way to make it so that the slot ignores it wrapper element.

It would still be semantic to provide `<h1 slot="title">Stock</h1>` but for the outermost element to be lost and the rest injected in the slot.

Perhaps by doing `<h1 class="header text-center"><slot ^name="title"></slot></h1>` with the ^ signifying to lose the top level. Or some other way to indicate this.

**Comment by alexbowers** [comment]
This demonstrates the problem i'm trying to solve: https://jsfiddle.net/ywau5crn/

**Comment by alexbowers** [comment]
Generated HTML: 
![image](https://user-images.githubusercontent.com/842974/28215885-784b0688-68a7-11e7-87f3-67d1c4bfe9c4.png)

**Comment by sqal** [comment]
@alexbowers

You can use `slot` on the `template` tag, then Vue will render only children vnodes:

`<template slot="title">Title</template>`

Or you can simply pass the title as a prop :)

**Comment by alexbowers** [comment]
@sqal 

> You can use slot on the template tag

That will only work for top level, with nothing else in the Template though correct?

It still isn't as semantic as allowing a child slot to be rendered with only children nodes.

**Comment by alexbowers** [comment]
Our use case is a header bar on the site, but this may have a title, subtitle, buttons, breadcrumbs, etc. 

We would like these to all be passed in as semantic a way as possible.

**Comment by yyx990803** [comment]
Please edit title to what you are actually requesting...

**Comment by alexbowers** [comment]
@yyx990803 Sorry not sure where that title came from. Changed.

**Comment by alexbowers** [comment]
If you want me to explain it any more, or provide other examples of where I need something like this, i'm on the discord, or can provide here.

**Comment by posva** [comment]
what @sqal said
If you want it to be more semantic when using the component, you can put the `h1` inside of the `slot` tag. The problem with this approach is that the user must specify the classes again, and the solution is to create sub components like sb-header-title so the user doesn't have to care about the original state but is still able to adds his own.
My personal opinion is to do what @sqal said, the semantics matters when the page is rendered not while it's being developed, you can always use meaningful names like you did (title)

**Comment by alexbowers** [comment]
@posva What @sqal provided isn't a solution that solves the problem though.

How would you do for example a modal, with a header, button and some body of content in a way with valid HTML (ie. no tags within h1).

**Comment by alexbowers** [comment]
Creating sub-components just so that the HTML is valid surely means that slots are effectively useless right? If in some circumstances a slot won't work, but a sub component will always work, why use a slot?

**Comment by posva** [comment]
> Creating sub-components just so that the HTML is valid surely means that slots are effectively useless right? If in some circumstances a slot won't work, but a sub component will always work, why use a slot?

No.
Because

> create sub components like sb-header-title so the user doesn't have to care about the original style but is still able to adds his own

(replaced state with style, that was a typo 😆 )
