### ISSUE TITLE
"Multiple return slots" for components

### ISSUE THREAD

**Issue by kay999** [vuejs/vue#6114]
### What problem does this feature solve?
Imagine the following usage of a component

```
<c-dialog>
    <slot name='content'>...</slot>
    <slot name='buttons'>...</slot>
</c-dialog>
```
But now I create a "form-component"

c-form:

```
<template>
   <slot returns='content'></slot>
   <div returns='buttons'>
      <button>Submit</Button>
      ...
   </div>
<template>
```

to use it with c-dialog:

```
<c-dialog>
  <c-form>
    <c-field>...</c-field>
  </c-form>
</c-dialog>
```

This would wire the 'buttons/content' return-slots from c-form with the buttons/content-slots of c-dialog.

This kind of component composition seems not to be possible now. Or is there some way to "simulate" it?

### What does the proposed API look like?
Define a template with multiple return slots:
```
<template>
   <div returns='slot1'></div>  
   <div returns='slot2'></div>  
<template>
```

**Comment by yyx990803** [comment]
I honestly have no idea what you are trying to do.

**Comment by kay999** [comment]
Imagine a 'dialog component' named 'c-dialog' with a template like

```
<template>
   <h1>{{ title}}</h2>
   <main><slot name='content'></main>
  <footer><slot name='buttons'></footer>
</template>
```

Now this can be used like 

```
<c-dialog>
    <slot name='content'>
       <div>This is my content</div>
    </slot>
    <slot name='buttons'>
        <button>Dismiss</button>
    </slot>
</c-dialog>
```

No problem so far.

But what if I have a component which defines both content and buttons? Like c-form above: Its a "form" which creates both a content-block and a buttons-block.
 
I couldn't simply create it as

```
<!-- c-form -->
<template>
   <slot></slot>
   <div class='buttons'>
      <button>Submit</Button>
      <button>Cancel</Button>
   </div>
<template>
```

and use it like

```
<c-dialog>
  <c-form slot='content'>
    <c-field>...</c-field>
  </c-form>
</c-dialog>
```

because now the 'buttons-div' from c-form would end up in the 'main'-tag of c-dialog instead of the 'footer'-tag. 

So how to solve this problem? An idea would be multiple return-slots. But maybe Vue can already do this in some way and I simply haven't found it yet.

**Comment by posva** [comment]
You can do this by splitting up in sub components like `DialogTitle`, `DialogBody` and give them to the user so they can use them to fill up the content of a dialog component and allow further customisation

**Comment by posva** [comment]
So instead of using one single component to fill up 2 different slots, use 2 different components, one for each slots.

**Comment by kay999** [comment]
Ok, thank you for the idea. I think this would work in my case, I'll try it out.

**Comment by posva** [comment]
FYI I'm referring to something like this: https://github.com/vuetifyjs/vuetify/tree/dev/src/components/cards

**Comment by kay999** [comment]
Two small remaining problems are 

- Order: The order of the elements in the resulting html-code can't be controlled by 'c-dialog'. In my case that's no big problem because I use flex-box and can reorder in css. But how to solve this in the general case?
- Replacement of c-dialog with some other component, let's call is 'c-page': Now if I can't change the code of 'c-form', c-page needs to work with 'DialogBody' etc.
Now DialogBody should render differently for c-page than for c-dialog, so I would need something like dispatching on '$parent.$options.name" in DialogBody  which is a bit cumbersome.

Both seem to be no problem in my use-case, so I think your solution works for me.

**Comment by posva** [comment]
You're complexifying things quite a lot. Maybe render functions are more appropriate for you. 
I suggest you to ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
