### ISSUE TITLE
Should props registered on a functional component remain in context.data.props?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#6115]
### What problem does this feature solve?

Currently, any props registered on a functional component will not appear in `context.data`. The result is that when used as a wrapper component, like this:

``` js
h(WrappedComponent, context.data, context.children)
```

Then no props shared between the functional component and `WrappedComponent` will be passed to `WrappedComponent`. 

You can get around this by adding the missing props to `context.data.props`, but you have to anticipate the behavior. When I encountered a user who noticed a discrepancy between `context.props` and `context.data.props`, they were very confused and I must admit, I was also confused at first.

### What does the proposed API look like?

Perhaps `context.data.props` should always match `context.props` and in rare cases where users don't want "transparent" wrapper components, they can explicitly create a sanitized data object. 

This change could technically change rendered results in existing applications, but I think the worst case might be extra attributes added to root elements, so not a _breaking_ change exactly.

**Comment by yyx990803** [comment]
The current behavior is that `context.data.props` is untouched if explicitly passed via `h(FunctionalComponent, { props: { foo: 'bar' }})`.

If passed in template as `<functional-component foo="bar"/>`, then it is actually passed in `context.data.attrs` and will be removed from `context.data.attrs` when the functional component resolves it as a prop.

**Comment by chrisvfritz** [comment]
Yeah, so I guess I'm wondering if the props removed from `context.data.attrs` should be added to `context.data.props`, so that `context.props` and `context.data.props` will always be identical.

**Comment by yyx990803** [comment]
I feel that if a functional component explicitly declares some props, it is "intercepting" them. If the functional component is meant to serve as a "pass through" wrapper, then it can simply not declare any props and use implicit props.
