### ISSUE TITLE
能否给自定义指令增加设置v-model绑定的变量的方法

### ISSUE THREAD

**Issue by fengyunhe** [vuejs/vue#6116]
### What problem does this feature solve?
因为有很多的输入方式的jquery插件，比如颜色选择器，日期选择器等，他们选择后往往是直接操作dom的value值，但是这个操作并没有将新的值同步到v-model指定的变量上。

### What does the proposed API look like?
这是一个颜色选择器的自定义指令，使用jquery的颜色选择器插件做了处理，选择颜色后此插件会触发changeColor事件，希望再此事件中能够同步新的值到v-model绑定的变量
```
Vue.directive('input-color', {
            // 当绑定元素插入到 DOM 中。
            inserted: function (el,binding,vnode,oldVnode) {
                $(el).colorpicker().on('changeColor',function () {
                    //希望这里可以设置v-model绑定的变量值
                }).on('showPicker',function () {
                    $(this).colorpicker('setValue', this.value || '#000000');
                });
            }
});
```

**Comment by fengyunhe** [comment]
vnode上能否提供一个方法来设置v-model绑定的变量的值，因为v-model并不一定是data的根路径开始的所以这里很难直接用v-model的值通过vnode.context来操作，有没有一个内置的方法来设置v-model绑定的变量的值

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Unfortunately, this depends on the jquery plugin
