### ISSUE TITLE
求组件中动态编译模板的方法

### ISSUE THREAD

**Issue by jaweii** [vuejs/vue#6117]
### What problem does this feature solve?
比如说，我想做个在线写vue代码的页面，那么就需要根据用户输入的内容来编译成html，这样用户在页面上即能编辑，也能预览

我查了很多资料，还是没有找到方法，只能来这儿提交了。。。

### What does the proposed API look like?
大概像这样：

`var inputVal=‘<my-component />’`（这是用户输入的内容，my-component是已经全局引入了的组件）
`var html=this.compile(inputVal)`      然后这样就得到了vue编译后的html代码

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Vue provide its template compiler with `Vue.compile` and as package as well.

**Comment by LoverMaker** [comment]
Maybe, this project can help you:  https://cinwell.com/vuep/#/?id=props @jaweii

**Comment by jaweii** [comment]
@LoverMaker thanks, but, I tried, vuep can not compile such a template:
this.code = `
<template>
    
     <my-global-component />
</ template>
`
