### ISSUE TITLE
Offer a .$listen() helper to wrap .$on() .$off() calls during the instance lifespan

### ISSUE THREAD

**Issue by prawnsalad** [vuejs/vue#6119]
### What problem does this feature solve?
I often add several event listeners to various things in my created() function, and then having to remove them in the beforeDestroy function.

This mixin helps a ton in every case for these cases, so that having to keep track of event listeners for a specific instance are cleaned up correctly.
```javascript
Vue.mixin({
    methods: {
        listen: function listen(source, event, fn) {
            this.listeningEvents = this.listeningEvents || [];
            this.listeningEvents.push(() => {
                source.$off(event, fn);
            });
            source.$on(event, fn);
        },
    },
    beforeDestroy: function beforeDestroy() {
        (this.listeningEvents || []).forEach(fn => fn());
    },
});
```

if this could be built in (bonus points if `(source.$on || source.on)()` is used for commonly used eventemitters!) then it should save a lot of time and ease of use for tracking weird bugs due to left over bound events.

### What does the proposed API look like?
On a Vue instance, `this.$listen(otherVueInstance, 'event_name', (event) => {});`.

No need to worry about cleaning up the event when the instance is destroyed.

**Comment by prawnsalad** [comment]
Quick addition to the proposed API.. `this.$listenOnce()` which has the same API but wraps `.$once` instead of `.$on`

**Comment by posva** [comment]
Events are already cleaned up 😄 
https://vuejs.org/v2/guide/events.html#Why-Listeners-in-HTML (3rd point)

**Comment by prawnsalad** [comment]
You've misunderstood. That's for HTML listeners.

This is for $on/$once functions called directly. Take this example: https://jsfiddle.net/2r16hmvf/
Each time you click to create a new component it adds a $on() for the event emitter and then destroys any previous components. Yet despite being destroyed the emit listeners are still there when you hit the emit event button.

**Comment by jkzing** [comment]
Um...as it could be done via mixins, what is the reason to make this particular case inside vue. 🤔Actually, I didn't use to deal with this kind of situation frequently before.

**Comment by prawnsalad** [comment]
I must know at least a handful of vue devs that attach event listeners in the created(), store them somewhere, and then remove them in one of the destroyed() functions.

Considering one of Vuejs big points of ease of use for common patterns, and in larger apps we are always binding events to different sources not in HTML templates this would be a huge pain relief for the larger apps.

We could always keep applying mixins.. but considering the HTML templates do already clean things automatically up it sounds logical that the API event listeners should also have a way to clean things up automatically.

**Comment by posva** [comment]
That fiddle is really different, you're attaching events to another source, they're not linked to the vue instance you're calling the `$on` function in any way, so it's normal for you to clean them up: https://jsfiddle.net/posva/71rfnyq8/

To make it clear: listeners setup with `this.$on` are cleaned up when the instance is destroyed.
So doing `this.$on` without `this.$off` in the `destroyed` event should be ok (no memory leaks, etc)

A note about `$destroy`: https://vuejs.org/v2/api/#vm-destroy

**Comment by prawnsalad** [comment]
> That fiddle is really different, you're attaching events to another source

Yup, that's the point.

For example if I have a global event bus and I want my component to listen to an event from it, then I must .$on() in the created function, and then .$off() in the destroyed function. That event bus may be passed down via a prop, imported module, $ref, anywhere. The usual case I have seen this and the most common in my own work is when using an event bus which is a very common pattern.

Sure, I could call $on/$off in 2 different Vue instance functions, but as it's a very common pattern and I know a few people that do this already, having that simple function to wrap it all up nicely within Vue just makes life that bit easier for the larger apps.

**Comment by posva** [comment]
You're using an external event emitter (even though it's a vue instance), so you're responsible for handling those 🙂
I suggest you to create a plugin with your mixin and post the link here

**Comment by prawnsalad** [comment]
@posva There is a mixin in the first message of this thread. It works and a fair few people I've see use similar. A *lot* of code I've seen applies the events and forget to clean them up without noticing the bugs it leaves behind. Having it built in would help a number of people!

**Comment by posva** [comment]
It's a specific case that, I don't know why you think is super common. Using an instance as an event emitter is useful in small projects but in larger projects we use Vuex. So we're not incrementing the size of Vue for only small projects.
On second thought, it'll be cool to add that mixin to the docs at https://github.com/vuejs/vuejs.org 
Could you submit a PR?

**Comment by prawnsalad** [comment]
Sure thing. Where specifically would it fit? I'm not familiar with the repo.

**Comment by posva** [comment]
I think it should go here: https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/migration.md#dispatch-and-broadcast-replaced
