### ISSUE TITLE
Allow suppression of warnings on an individual basis

### ISSUE THREAD

**Issue by khoker** [vuejs/vue#6120]
### What problem does this feature solve?
Some warnings generated at compile time may be by design (e.g., "component lists rendered with v-for should have explicit keys").  If a project generates enough of those warnings, other warnings that the author might care about could be missed.    
    
Warnings can be disabled completely using the "silent" flag, but that only allows for all-or-nothing approach.   It would be nice to be able to disable certain warnings.  Perhaps something as simple as an ignoredWarnings option in the config, where each type of state warning could be given a unique reference.   
   
Maybe there's not enough warnings now to matter, but it might be something nice for the future.

### What does the proposed API look like?
    
    config: {
        ignoredWarnings: ['v-for-keys']
    }

**Comment by jkzing** [comment]
Every warning should be cared about, that's why warnings exist. isn't it?😂

BTW, all warning would be gone in production.

**Comment by yyx990803** [comment]
I don't see a good reason to support this - you should not ignore any warnings.

**Comment by paritoshmmmec** [comment]
v-for-keys warning is really good , it will certainly save your time debugging later in case of problem.

**Comment by khoker** [comment]
Thank you for the consideration.   I agree that warnings are important, but I observed a situation where I thought I might miss _other_ warnings because the console was being flooded with warnings that were more or less false-positives for me.

I think there are situations where the "v-for key" warning would not be useful.  For example, v-for accepts a parameter of type _Array | Object | number | string_.   In my case, I am iterating over a collection of objects -- but I don't necessarily know what keys are in the object ahead of time.  I can get around this by injecting a GUID field to each object when the data is loaded.  But if you were iterating over an array of arrays, or a string or number, would you be able to address the warning of a missing key?    
   
Either way, I understand it is an edge-case.  Thanks again for the responses.  Vue is awesome!

**Comment by klesun** [comment]
Is there a way to explicitly tell v-for to use what it would have used if I did not specified the `:key` so that it did not yield warnings?

I have an array of arbitrary data that may include absolutely identical entries. The default behaviour when `:key` is not specified, I take it, is that vue always treats entries as unique and never reuses the DOM. That's exactly the behaviour I want for this kinds of data. Am I supposed to use `:key="Math.random()"` in such cases?

**Comment by klesun** [comment]
A bit hardcore, but I found a way to silence these v-for warnings:
```javascript
/**
 * the only way to ignore Module Warnings coming from vue-loader
 * see https://github.com/vuejs/vue/issues/6120#issuecomment-1450441760
 */
function interceptVForWarnings() {
    const consoleLog = console.log;
    let startedWarning = [];
    let skipABlankLine = false;
    console.log = (...args) => {
        const skippingABlankLine = skipABlankLine;
        skipABlankLine = false;
        const firstArg = args[0];
        if (typeof firstArg === "string") {
            if (firstArg.startsWith("\u001b[43m\u001b[30m warning \u001b[39m\u001b[49m in ")) {
                startedWarning = [args];
                return;
            } else if (firstArg.includes("component lists rendered with v-for should have explicit keys")) {
                startedWarning = [];
                skipABlankLine = true;
                return;
            } else if (firstArg.trim() === "") {
                if (startedWarning.length > 0) {
                    startedWarning.push(args);
                    return;
                } else if (skippingABlankLine) {
                    return;
                }
            }
        }
        for (const delayedArgs of startedWarning) {
            consoleLog(...delayedArgs);
        }
        startedWarning = [];
        consoleLog(...args);
    };
}

interceptVForWarnings();
```

If one wants to see such optimization suggestions, a much less intrusive way would be to actually get them from the configurable [vue/require-v-for-key](https://eslint.vuejs.org/rules/require-v-for-key.html) eslint rule rather than in form of unsilenceable flood in stdout from the framework's core loader.
