### ISSUE TITLE
A way to programmatically pass props and args to a new Vue instance and keep it updated

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#6121]
### What problem does this feature solve?
I am trying to integrate Vue with Meteor Blaze and am working on rendering of Vue components from Blaze templates. I would like to programmatically create an Vue instance (`new Vue(...)`) and pass it props and args which would be equivalent to doing `<vue-component :prop="propValue" :arg="argValue">`. So an object of key/values which would then be mapped to props, if keys are among props, or be set as element attributes otherwise. But the important part is to also be able to update all of them afterwards. So if any of the props or args change, allowing to call a function to update them would be great.

### What does the proposed API look like?
I propose that `propData` could be a function. So that I could provide a reactive function which would be used to populate both props and args (so any keys returned from the function which are not props would become args).

Alternatively. we could have `vm.$propsUpdate` function which I could run to update props and args in a more imperative way.

**Comment by Akryum** [comment]
Shouldn't be possible to autorun over the blaze data and then just affect it to the vue instance (which will update it)?

**Comment by mitar** [comment]
Yes, I could do:

```
this.autorun(() => {
  vm.$propsUpdate(Template.currentData());
});
```

But I do not see an easy way to determine which one should be props and which attrs and updating both of them as needed.

**Comment by Akryum** [comment]
You can wrap your component inside a Vue instance: [example](https://jsfiddle.net/9f2x2b7z/)

**Comment by mitar** [comment]
Yes, but this assigns all to `props`, what if some of those are not defined on the target component as props? Do they get mapped to `attrs` automatically?

**Comment by Akryum** [comment]
Why do you want to set attributes?

**Comment by mitar** [comment]
Oh, just to support non-prop attributes (which could be still bound to reactive value). I would like to fully support what you can do in Vue: `<vue-component :prop="propValue" :arg="argValue">`

**Comment by Akryum** [comment]
What's the point when you can do that on the root tag inside your component?

**Comment by mitar** [comment]
So that user can set attributes without developer of the component knowing about those. See [description and rationale here](https://vuejs.org/v2/guide/components.html#Non-Prop-Attributes). I would like to support it in Blaze as well, if possible. But it is not a big deal. But if Vue would have such a function, which would allow programmatically to set (and update) props and attrs like you can from template language, that would be very easy to do.

**Comment by Akryum** [comment]
It's generally to use non-vue libraries, but you will most likely write at least one Vue component to wrap it that should expose its features through props and events (the point is using Vue components in Blaze anyway).

**Comment by mitar** [comment]
I do not think it is needed. You could directly use Vue components. At least this is what I am aiming for in [this package](https://github.com/meteor-vue/blaze-integration).

**Comment by posva** [comment]
I don't get the fr...
You can already programmatically create Vue instances (with `new Vue`). Sharing an object as the state (`data`) will allow you to reuse the same data in multiple instances if needed.
To trigger functions when things change, use watchers.
What is missing?

**Comment by mitar** [comment]
So how would you programmatically create a component which would be equivalent to `<vue-component :prop="propValue" :arg="argValue">`, without knowing which props a component is accepting, so that all which it is not, become attributes?

**Comment by posva** [comment]
templates --> `v-bind`
render functions --> can access to available props, diff them, pass them as `attrs` or `props` (https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth)

**Comment by mitar** [comment]
This is trickier than it seems. :-) If you use render function, then you cannot modify anymore `props` (you get a warning) afterwards, because it is not a top-level component anymore.

**Comment by posva** [comment]
I still don't see what is missing...

**Comment by posva** [comment]
Sorry, that comment was a bit rude.

You can modify the props you pass down.
I feel like you haven't dug enough your problem but at the same time, to me, it looks like you understand more than the average user. Have you asked on the forum or discord to get further help?

**Comment by mitar** [comment]
No worries. I know it is sometimes hard to communicate online and also understand what all is the background. I have not asked anything on the forum because I think I have good enough grasp of Vue code (I have read through it) and what is currently possible, so I didn't feel that there are some questions I would need an answer to. But of course maybe I missed something.

(I have issues using the forum because when I try to login, I get "You can't log in as mitar from that IP address," but that is a different issue.)

So, I am working on Blaze integration with Vue. Current code is [here](https://github.com/meteor-vue/blaze-integration). What this issue relates to is how I could create a nice API to render Vue components from Blaze templates. Ideally, I wanted to support something like the following syntax:

```handlebars
{{> VueComponent component="my-vue-component" prop="propValue" arg="argValue"}}
```

What Blaze does is puts all the arguments into an object and passes it on to the code which would include Vue. If any of the values reactively change, code is rerun with new object with new value, which allows one to push those updated values to Vue component's instance. Now, there are two questions:
* how to know which of the values are props and which are args, and should I (as somebody using the code to push new values to the instance) even care, and should the developer using the above syntax care (they do not have to care when using `<vue-component :prop="propValue" :arg="argValue">`)
* how should I push these new values, given that I am getting a new object with new values

One approach would be that I ask the developer to specify which are props and which are args, by asking them to pass only to arguments, something like:

```handlebars
{{> VueComponent component="my-vue-component" props=props args=args}}
```

But I would prefer that developer does not have to do so.

I have tried two approaches. One with wrapping component, and one without. With wrapping component, code is something like (if `data` is the object above).

```js
const vm = new Vue({
  el,
  render: (createElement) => {
    return createElement(Vue.component(data.component), {props: filterProps(data), attrs: filterAttrs(data)});
  }
});
```

This works, but has two issues:
* how do I know what are props and what are attrs, I could inspect component's options and figure that out manually, but that would require me to duplicate the code which already existing in Vue, so it would be great if I could just pass an object of all of them and Vue figures this out
* how to update those props or attrs once they change, without recreating the whole component (maybe component keeps important state, or is a form which should not loose existing user input)

I tried something like:

```js
_.each(_.keys(vm.$children[0]._props || {}), (key, i) => {
  vm.$children[0]._props[key] = filterProps(data)[key];
});
```

But this throws a warning, because one should not be changing non-root props directly. Moreover, I have no idea how to change attributes in a similar way.

A second approach I tried is to do:

```js
const propsData = filterProps(data);
const component = Vue.component(data.component);
const vm = new component({
  el,
  propsData,
});
```

And then when I want to update props, I do:

```js
_.each(_.keys(vm._props || {}), (key, i) => {
  vm._props[key] = filterProps(data)[key];
});
```

Now it works. Alternatively, I suspect, I could just be setting values on `propsData` object directly and it might propagate by Vue. I have not yet tried this, because the issue with this approach is that I do not know how to pass attrs. And again, I have to manually filter props and attrs.

So, while working on this, I wondered why there is no API which would match the template API, where I can do `<vue-component :prop="propValue" :arg="argValue">` and Vue figures out which one is prop and which one is attr.

Maybe instead of `propsData` we could have `propsAndAttrsData` and that Vue would split them as needed. And then or augment the object to detect changes to it (observe), or provide `vm.$updatePropsAndAttrs` method.

So I think all this is doable without help by Vue. But my issue is that I think it should be simpler to do. Maybe I am complicating here though and there is easier way to do it.

**Comment by yyx990803** [comment]
FYI, you can get the normalized props metadata of a component via `vm.$options.props`... you can then group the raw args from Blaze into props and raw attributes based on that metadata. If I'm not mistaken, that should solve the desired use case.

**Comment by jbmikk** [comment]
I was wondering how to set the props of a component on the `beforeRouteEnter` router guard.
So I guess there is no official way of setting props programmatically?

I am using router guards to resolve some data and pass it down to the components if everything goes well.

Right now I'm using setter methods on the component to set inputs that would otherwise have been props. This seems a bit clumsy if you ask me, particularly when trying to reuse components.
