### ISSUE TITLE
I want get the value before change but not success, I dont't know what happened

### ISSUE THREAD

**Issue by confirmTing** [vuejs/vue#6122]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/smallMing/L754mh9s/1/](https://jsfiddle.net/smallMing/L754mh9s/2/)

### Steps to reproduce
It was good at first and failed, after I slid

### What is expected?
the value is current value and the beforeValue is previous value

### What is actually happening?
the value is identical beforeValue  after changed

**Comment by confirmTing** [comment]
please use this link [https://jsfiddle.net/smallMing/L754mh9s/2/](url)

**Comment by yyx990803** [comment]
This is question, not a bug report. It also is related to a 3rd party library. Please make sure to follow the issue report requirements.
