### ISSUE TITLE
Variable not updated by triggering from outside, but triggered by onclick.

### ISSUE THREAD

**Issue by vad11** [vuejs/vue#6124]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/vadvad/39wnvbxg/1/](https://jsfiddle.net/vadvad/39wnvbxg/1/)

### Steps to reproduce
 I update input from jquery for get results from selectize.js plugin

" <input id="lang_switcher20" v-model="lang2" v-on:click="greet1" >"

and
onChange: function(value) {
$("#lang_switcher20").val(value).trigger("click").trigger('change');
}

and i not see updating of lang2 variable in vue !!!!

BUT if I use :
greet1() {
this.lang2 = $('#lang_switcher20' )[0].value;
}

I give true lang2 variable.

Haw I must send message for update lang2 variable without onclick function?
What clear , simple and best way for get variable from plugin

### What is expected?
Update lang2 variable

### What is actually happening?
Not change lang2 variable

---
Haw I must send message for update lang2 variable without onclick function?
What clear , simple and best way for get variable from plugin

**Comment by LinusBorg** [comment]
This is a usage question, not a bug. Please ask your question on chat.vuejs.org or forum.vuejs.org

**Comment by vad11** [comment]
Why  this not bug. May be vue.js not process this message?

**Comment by vad11** [comment]
?

**Comment by jkzing** [comment]
@vad11 Because **it is** not a bug...and you are even not providing a valid repro link.

Please ask this kind of consulting questions at [forum.vuejs.org](https://forum.vuejs.org), I would be glad to help you there.
