### ISSUE TITLE
Was vue support v-on:drop and v-on:paste ?

### ISSUE THREAD

**Issue by Thaina** [vuejs/vue#6125]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/thainayu/50wL7mdz/47314/](https://jsfiddle.net/thainayu/50wL7mdz/47314/)

### Steps to reproduce
Drag file to red box (normal `ondrop`) work. But black box using `v-on:drop` does not

### What is expected?
`v-on:drop` should work like `ondrop` and trigger vue object's method like other event

### What is actually happening?
`v-on:drop` does not triggered

---
Same go for `paste`. `paste` may not be standard but at least jquery support it

**Comment by LinusBorg** [comment]
Your online code for the prevent default is wrong. 

Should be $event....

If you have a problem with paste, please provide a reproduction on a new issue.

**Comment by Thaina** [comment]
@LinusBorg Thank you very much. But that was got me another problem. Actually my problem is `md-layout` from vuematerial does not bind to `v-on` both clicking and dropping. I would try with paste next

**Comment by LinusBorg** [comment]
That would be a problem to ask on forum.vuejs.org

**Comment by nightgryphon** [comment]
The same trouble. v-on:dragover work fine but v-on:drop don't. Googled the whole day without luck.

**Comment by rmtry** [comment]
I accidentally found a simple solution for drop, hope it is not too late :D 
@drop.prevent="handleDrop"
