### ISSUE TITLE
Scoped styles not working on SSR

### ISSUE THREAD

**Issue by eugenioclrc** [vuejs/vue#6128]
### Version
2.4.1

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0/issues/229](https://github.com/vuejs/vue-hackernews-2.0/issues/229)

### Steps to reproduce
<style scoped> h1 { color: red!important; }</style>

### What is expected?
the h1 in red color

### What is actually happening?
You wont see the h1 in red when loading from server, insted if you load the page throught the router you will see

**Comment by LinusBorg** [comment]
Can you provide an actual reproduction? The hackernews repo is running on 2.4.1 and using scoped styles, and it renders with styles from the server, so what's the eel scenario that is not working for you? Please fork the repository and edit it so it demonstrates the issue.

**Comment by yyx990803** [comment]
This is caused by a bug in `vue-loader` and should be resolved after you upgrade `vue-loader` to 12.2.2 or 13.0.2.
