### ISSUE TITLE
Parent component updates, whenever its child's props change. That's wasteful.

### ISSUE THREAD

**Issue by akarelas** [vuejs/vue#6129]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/a0fsexqb/2/](https://jsfiddle.net/a0fsexqb/2/)

### Steps to reproduce
Create a parent component and a child component. Make the child have a prop variable. Make the parent modify the value of the prop attribute every second, and keep all variables related to the parent's view unchanged. Make the parent do a console.log whenever its view updates (i.e. set the parent's beforeUpdate to do a console.log)

### What is expected?
There shouldn't be a console.log happening every second.

### What is actually happening?
There is a console.log happening every second, because the parent view gets updated every second.

---
It takes CPU resources to update a component's view, even if the actual HTML hasn't changed at all, because the entire VDOM needs to be recalculated. Therefore, I believe that this behaviour is wasteful, and should be considered a bug. Imagine if the updates on the child's props happened 10 times each second, and the parent component's view contained 1000 non-changing variables.

**Comment by nickmessing** [comment]
Imagine the same in JSX:
```
export default {
  render () {
    return (
      <div>
        2+2={2+2}
        <child name={this.name}></child>
      </div>
    )
  }
}
```

To "pass" data to child components we have to re-render the "parent" component. There is no way around that and as you see in my example `this.name` is actually used in `render` method.
