### ISSUE TITLE
Native Events/Functional Components: Event.stopImmediatePropagation does not cancel event loop.

### ISSUE THREAD

**Issue by alexsasharegan** [vuejs/vue#6130]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/alexsasharegan/ojymho07/](https://jsfiddle.net/alexsasharegan/ojymho07/)

### Steps to reproduce
- Create a functional component:
  - create an event handler that calls `Event.stopImmediatePropagation`
  - put the context's event handler in an array with the component's handler, but place the component's handler at the first index. (Allowing the component's handler the first chance to stop propagation)
- Using this functional component in a parent component, bind a listener to the same event (e.g. `"click"`)
- Execute the event

### What is expected?
1. The functional component's handler should be called first, since it is first in the array
2. The functional component's handler should execute the `stopImmediatePropagation` call, and kill the event loop.

### What is actually happening?
1. Execution order is preserved correctly.
2. The parent component's handler is still being invoked (but additional handlers bound through `EventTarget.addEventListener` are not).

---
My use case starts at creating a link component that will respect a `disabled` property, but continues on to various other components to create a cohesive UI component API.

It would be beneficial to have some way to cancel the Vue event loop. I don't know my way around the source well enough, but I imagine that Vue internally tracks all event handlers for a given node, intercepts the native event first, then invokes all callbacks. This is why natively bound callbacks do not get invoked, but callbacks bound by Vue are invoked.

**Comment by LinusBorg** [comment]
That's because Vue is wrapping all of those functions in one function so it only has to register 1 instead of `n` listeners.

https://github.com/vuejs/vue/blob/dev/src/core/vdom/helpers/update-listeners.js#L26

You should simply do the same - wrap it all in your function instead of pushing your own into the array.
