### ISSUE TITLE
Resolve local components distributed with slots

### ISSUE THREAD

**Issue by rgtk** [vuejs/vue#6131]
### Version
2.4.1

### Reproduction link
[http://jsbin.com/lumukawigi/edit?html,js,console](http://jsbin.com/lumukawigi/edit?html,js,console)

### Steps to reproduce
1. Register component `Chart` with single slot and locally registered component `Bar` that is only accessible to its parent.
2. Pass `<bar>` element (of `Bar` component) to `<chart>` (of `Chart`) content through slot.
3. Initialize Vue instance.

### What is expected?
Element is resolved through `Chart` component that accepts slot and has registered `<bar>` (of `Bar`).

### What is actually happening?
`<bar>` is not resolved because Vue searches for it in scope of instance that doesn't have registered component for this element.

---
I was trying to create component with many local components to reduce name collision and simplify structure of view by making it more expressive, like this:
```
<chart> <!-- main component -->
  <set name="hits" data="[2, 3, 4]"> <!-- local component of main one -->

  <point v-for="point in sets.hits.points">
    <bar set="hits"> <!-- local component of <point> component -->
  </point>
</chart>
```
Since elements are distributed to parent through slots it would be make sense to at least try to resolve it in the context of its parent. That would make components much more modular and independent.

**Comment by yyx990803** [comment]
This is not a bug. Components are resolved based on which component's template it is used in.

What you need to do is expose both `Chart` and `Bar` to the user and register them together in the component that is using them.
