### ISSUE TITLE
组件实例更新引起其他同组件实例一同更新

### ISSUE THREAD

**Issue by iixxoo** [vuejs/vue#6133]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/5net58f8/](https://jsfiddle.net/5net58f8/)

### Steps to reproduce
点击： “重现问题” 按钮进行重现

### What is expected?
应该只有一个组件实例触发更新方法

### What is actually happening?
同一个组件的 多个实例(有嵌套内容的) 都触发了更新方法

**Comment by jkzing** [comment]
这是expected behavior，对于有children的组件，会强制重新渲染。

**Comment by nickmessing** [comment]
@jkzing, if it's not too hard and you got some time, can you please translate that to me because robotic translate is crazy? :smile:

**Comment by iixxoo** [comment]
@jkzing 能否解释一下为何要强制重新渲染？这样子的话，我觉得会存在两点问题：
 一、会影响性能，实例比较多的情况
 二、beforeUpdate、updated 进行操作的时候，是不是得进行实例区分判断？防止操作错误的实例

**Comment by jkzing** [comment]
@nickmessing sure😂
The basic idea is when you click on '测试一下' in that fiddle, `beforeUpdate` and `updated` hooks get called on `child` components with nested children (like `<child>1</child>`).

**Comment by nickmessing** [comment]
Oh, so you told him it's expected behaviour as I see. Can I close this issue?

**Comment by jkzing** [comment]
@nickmessing yes, we could close this.

**Comment by jkzing** [comment]
@iixxoo “强制重新渲染”指的是重新生成了vdom subtree，实际还是会diff再patch，并不会有性能问题。

如果对用法有问题，欢迎去[https://forum.vuejs.org/](https://forum.vuejs.org/)提问

**Comment by nickmessing** [comment]
@jkzing, thank you :+1:

**Comment by yyx990803** [comment]
简单解释下为什么要强制更新：因为父组件传给子组件的内容是在父组件的渲染函数中生成的，那么每次父组件更新的时候，传给子组件的内容可能会有变化，但传进去的内容只有在子组件也更新的情况下才能确保最终 DOM 的一致性。这里有优化的可能性，但绝大部分情况下都不会导致性能问题。

至于钩子问题，里面的 this 指向都不一样，怎么可能出现误操作？

**Comment by iixxoo** [comment]
@yyx990803 
虽然this指向不同的实例对象，但是 多个 实例 的data 中可能存在数据 type是一样的，然后需要在beforeUpdate在进行根据type判断，去执行某些操作。

一个场景：对话框组件，多个对话组件是共用一个遮罩层，在对话框显示时候，需要调整这个遮罩层的z-index值，如果每个实例都执行 update方法，那这个z-index值就需要额外的判断和控制

**Comment by yyx990803** [comment]
如果你的逻辑会因为 updated hook 触发的时机而产生问题，我觉得你应该重新设计下你的逻辑。

**Comment by iixxoo** [comment]
@yyx990803 
重新设计逻辑是可以解决问题，
但如果能做到只触发必要的实例，那么逻辑的设计应该会更简单。

**Comment by yyx990803** [comment]
`updated` hook 的定义就是组件可能发生了更新，任何组件依赖的数据变了都有可能发生更新，钩子里的逻辑本来就应该进行一定的状态判断的。
