### ISSUE TITLE
SSR context.renderStyles() returns empty string

### ISSUE THREAD

**Issue by Elevista** [vuejs/vue#6134]
### Version
2.4.1

### Reproduction link
[http://plnkr.co/edit/Gtp3uFFiBIxYMmyh3Se9](http://plnkr.co/edit/Gtp3uFFiBIxYMmyh3Se9)

### Steps to reproduce
webpack config rules : {test: /\.css$/, loader: "vue-style-loader!css-loader"}
```html
<script>
import './common.css';
export default {
	name: 'app',
};
</script>
<template src="./app.html"></template>
```
context has _styles property but context.renderStyles() returns empty string why is it?
client side works fine.
I don't know what I missed. please help.

有context._styles，不过context.renderStyles()的结果是“” 为什么？
浏览器上是正常添加STYLE。
不知道错过了什么，求解
![1](https://user-images.githubusercontent.com/9513647/28255815-cb3680c4-6af6-11e7-8a11-1b65fe8805ee.PNG)
![2](https://user-images.githubusercontent.com/9513647/28255817-ccb1735a-6af6-11e7-9497-7e3ac097aa95.PNG)

### What is expected?
context.renderStyles() => "<style>body {..}</style>"

### What is actually happening?
context.renderStyles() => ""

**Comment by Elevista** [comment]
```html
<script>
export default {
	name: 'app',
};
</script>
<template src="./app.html"></template>
<style src="./common.css"></style>
```
这样的话，没有context._styles。
context.renderStyles()结果一样是 empty string

**Comment by yyx990803** [comment]
Your reproduction is not runnable, please provide an actual repo.

**Comment by Elevista** [comment]
@yyx990803 
Here is the repo [](https://github.com/Elevista/temp)
'npm run prod' will run server in product mode with SSR

**Comment by yyx990803** [comment]
Ok, so I looked at your setup and it's because in [here](https://github.com/Elevista/temp/blob/master/app/boot.js#L14) you are using `extends: app` so essentially your `app` component is also the root component. The SSR CSS is injected in each component's `beforeCreate` hook, however you created the root instance **before** the render starts, so the injected CSS never got registered.

What you need to do is make the root component a wrapper:

``` js
// from this
app: new Vue({router, extends: app, store})

// to this
app: new Vue({router, store, render: h => h(app) })
```

**Comment by Elevista** [comment]
@yyx990803 
Thank you very very much <3
You're the king god maestro emperor code meister!
Vue.js forever xD
