### ISSUE TITLE
transition mode property accept default

### ISSUE THREAD

**Issue by jan-thoma** [vuejs/vue#6136]
### What problem does this feature solve?
if transition mode is defined it only accepts either 'out-in' or in-out' but not a default value.When transitioning between dynamic components it's sometimes needed to switch between all three modes.

### What does the proposed API look like?
mode='default' should switch to simultaneous mode

**Comment by LinusBorg** [comment]
You can simply pass `undefined`

**Comment by posva** [comment]
or an empty string
