### ISSUE TITLE
BUG input vue variable update not triggered ????????? !!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by vad11** [vuejs/vue#6138]
### Version
2.4.1

### Reproduction link
[http://jsfiddle.net/vadvad/1pohLabg/22/](http://jsfiddle.net/vadvad/1pohLabg/22/)

### Steps to reproduce
I ask this but issue was closed by posva, writed:  Vue cannot listen back to setting the value directly into the DOM element. This is not true see Evan You write in yyx990803 commented on Jul 29, 2014 https://github.com/vuejs/vue/issues/372

This is not work. Please return my previous issue https://github.com/vuejs/vue/issues/6135 for solution ! 

### What is expected?
type = ok

### What is actually happening?
type = not

---
Evan You write in yyx990803 commented on Jul 29, 2014
Vue does not detect the changes when directly setting value on input elements, that is by design. If you know when your external lib has changed the input value, you can manually trigger a change event on your input element to notify Vue to sync the value back to the model.

https://github.com/vuejs/vue/issues/372

**Comment by jkzing** [comment]
Vue was not even reach v1.0.0 in the year 2014...

**Comment by LinusBorg** [comment]
Dude, I showed you on the forum that triggering a *real* DOM Event works like an hour ago, here:

https://forum.vuejs.org/t/variable-not-updated-by-triggering-from-outside-but-triggered-by-onclick/14389/13?u=linusborg

Doing it with jQuery (which does whatever god knows behind the scenes) does not seem to work, agreed - but that's not our concern, we aim to be compatible with vanillaJS first an foremost.

I will close this issue again. If I have to close another issue for this, it might be the last one you open in this repository.
