### ISSUE TITLE
Wiki is quite outdated

### ISSUE THREAD

**Issue by etiennellipse** [vuejs/vue#6140]
### Version
Any

### Reproduction link
[https://github.com/vuejs/vue/wiki](https://github.com/vuejs/vue/wiki)

### Steps to reproduce
- Open up the wiki page (https://github.com/vuejs/vue/wiki)
- See "Vue 2.0 is almost here!"
- ...?

### What is expected?
Up-to-date information, or link to updated resources

### What is actually happening?
I see outdated information

---
- Remove the "Vue 2.0 is almost here!" block
- Add a link to the Vue.js documentation site instead
- Change the "Roadmap" side link to https://github.com/vuejs/vue/projects/3

I think it would give a better feel for people evaluating the product if the wiki was updated. I would provide a PR, but it's not possible to do it for the wiki.

**Comment by LinusBorg** [comment]
Hi!

You are right, the Wiki isn't being maintained anymore. I guess we could even deactivate it as we don'T use it for any kind of documentation - it's all on the website.

**Comment by yyx990803** [comment]
Yeah, wiki has been disabled now.
