### ISSUE TITLE
Date input does not accept a Date object as an initial value

### ISSUE THREAD

**Issue by shvelo** [vuejs/vue#6142]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/50wL7mdz/47503/](https://jsfiddle.net/50wL7mdz/47503/)

### Steps to reproduce
Use a Date object as v-model for input[type=date]

### What is expected?
The date input should use provided Date value

### What is actually happening?
Date input shows "mm/dd/yyyy" (blank state)

**Comment by posva** [comment]
You need to use a computed property for the moment: https://jsfiddle.net/posva/6j6L8fy1/
Date inputs not being widely supported this is something we'll probably skip until date is widely supported: http://caniuse.com/#feat=input-datetime

**Comment by shvelo** [comment]
Okay, I guess using a vue datepicker library is currently the best option for me.

**Comment by yyx990803** [comment]
`Date` is not a plain JavaScript object and thus not supported for reactivity.
