### ISSUE TITLE
Supports to Vue.component(..., require(...))

### ISSUE THREAD

**Issue by rentalhost** [vuejs/vue#6143]
### What problem does this feature solve?
It seems to be very common users trying uses it like `Vue.component(..., require(...))`, which is not supported. You should uses:

* `Vue.component(..., require(...).default)` or;
* `Vue.component(..., ImportedComponent)` as in `import ImportedComponent from "MyComponent.vue"`;

Else you will receive an error like:

> **Failed to mount component:** template or render function not defined.

### What does the proposed API look like?
`Vue.compoent()` 2nd parameter should try identify if you are using a `require()`'d instance, then get the `.default` property automatically as fallback, then this error will be avoided. 

**I guess that it can be done like:**

```js
if (!arg2.render && !arg2.template && arg2.default) {
    arg2 = arg2.default;
}
```

**Comment by nickmessing** [comment]
I personally think that we should not focus on `require()` support at all since it's non-standard and will likely be completely replaced by `import Comp from './somewhere'` and `import()`.

**Comment by yyx990803** [comment]
I agree with @nickmessing here - adding a `.default` really isn't that bad imo.
