### ISSUE TITLE
在改变一个属性后，会触发其他属性的过滤器和方法

### ISSUE THREAD

**Issue by zoro-web** [vuejs/vue#6147]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/3ms08t0o/1/](https://jsfiddle.net/3ms08t0o/1/)

### Steps to reproduce
在上述链接输入框输入文字，会发现打了跟这个属性无关的两条console

### What is expected?
改变当前属性只希望更改该属性挂钩的相关操作，不然组件一多，dom结构一多，一个小小的操作都会导致操作卡顿

### What is actually happening?
会导致一些没有必要的执行操作，组件多的时候，一个小操作会导致卡顿

**Comment by yyx990803** [comment]
不会卡顿。请自行了解 virtual dom 原理。

**Comment by jkzing** [comment]
因为你在computed `ddd`里引用了`bbb`啊...这不就是相关吗...

**Comment by zoro-web** [comment]
@yyx990803 你好，我想知道是不是因为数据变动了，会导致模板重新编译，从而导致相关函数的执行，按照我的理解，响应式原理不是修改当前数据，跟当前数据相关Dep才触发，从而发生改变，并不会影响其他数据的一个行为。麻烦帮忙解答一下，很疑惑。

**Comment by zoro-web** [comment]
@jkzing 并不是这种的原因，就算把这里的computed去掉了，控制台还是会输出那两条记录，所以怀疑是不是模板编译的时候执行的

**Comment by jkzing** [comment]
@zoro-web 不好意思之前没仔细看，是`show(bbb)`这个方法在你的模版里引用了两次，分别是`<p>{{show(bbb)}}</p>`和`<demo :data="show(bbb)"></demo>`。

至于为什么会执行，建议你用`vue-template-compiler`直接编译下你的模版，看看输出的render function的样子你应该就明白了。

**Comment by zoro-web** [comment]
@jkzing 我看了一下，是改了数据就会重新进行模板渲染过程吗

**Comment by neilyongge** [comment]
不是特别极端的情况，确实有轻微卡顿，filter很多，属性也很多，随便改一个属性，跟改属性无关的filter也执行了
