### ISSUE TITLE
DOM did't sync with data 

### ISSUE THREAD

**Issue by yangjunjun** [vuejs/vue#6149]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/yangjunjun/pfo1qmj3/7/](https://jsfiddle.net/yangjunjun/pfo1qmj3/7/)

### Steps to reproduce
click 'fetch_data' 

### What is expected?
DOM should show 'true' for 2s after click 

### What is actually happening?
DOM show 'false' always

**Comment by yyx990803** [comment]
read the docs. https://vuejs.org/v2/guide/reactivity.html

**Comment by posva** [comment]
That's because you're freezing the js process with the while loop...

**Comment by jkzing** [comment]
use `setTimeout(() => {}, 2000) instead of `while(Date.now() < start + 2000){}`...
