### ISSUE TITLE
IE9、10, report SyntaxError in app.js

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue#6151]
### Version
2.4.1

### Reproduction link
[https://github.com/yoyo837/vue-issue-report](https://github.com/yoyo837/vue-issue-report)

### Steps to reproduce
eval("/* eslint-disable */\n__webpack_require__(15)\nconst hotClient = __webpack_require__(34)\n\nhotClient.subscribe(function(event) {\n  if (event.action === 'reload') {\n    window.location.reload()\n  }\n})\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiOC5qcyIsInNvdXJjZXMiOlsid2VicGFjazovLy8uL2J1aWxkL2Rldi1jbGllbnQuanM/N2Q2NyJdLCJzb3VyY2VzQ29udGVudCI6WyIvKiBlc2xpbnQtZGlzYWJsZSAqL1xucmVxdWlyZSgnZXZlbnRzb3VyY2UtcG9seWZpbGwnKVxuY29uc3QgaG90Q2xpZW50ID0gcmVxdWlyZSgnd2VicGFjay1ob3QtbWlkZGxld2FyZS9jbGllbnQ/bm9JbmZvPXRydWUmcmVsb2FkPXRydWUnKVxuXG5ob3RDbGllbnQuc3Vic2NyaWJlKGZ1bmN0aW9uKGV2ZW50KSB7XG4gIGlmIChldmVudC5hY3Rpb24gPT09ICdyZWxvYWQnKSB7XG4gICAgd2luZG93LmxvY2F0aW9uLnJlbG9hZCgpXG4gIH1cbn0pXG5cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL2J1aWxkL2Rldi1jbGllbnQuanNcbi8vIG1vZHVsZSBpZCA9IDhcbi8vIG1vZHVsZSBjaHVua3MgPSAwIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Iiwic291cmNlUm9vdCI6IiJ9")

### What is expected?
IE9,IE10 work fine.

### What is actually happening?
create by vue-cli, in dev-client.js, does not seem to be compatible with IE10-!

**Comment by yoyo837** [comment]
What should I do?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yoyo837** [comment]
I guess I need babel-polyfill. Thanks!

**Comment by yoyo837** [comment]
I'm sure I have caused this problem myself because I changed the dev-client.js file var to const, i was so stupid. :(
