### ISSUE TITLE
when in lifecycle created commit mutation not be logger

### ISSUE THREAD

**Issue by MorisHarA** [vuejs/vue#6152]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/a1wqbmy9/](https://jsfiddle.net/a1wqbmy9/)

### Steps to reproduce
when in lifecycle created commit mutation not be logger in vue-devtool

### What is expected?
logger when first init

### What is actually happening?
when in lifecycle created commit mutation not be logger

**Comment by LinusBorg** [comment]
> https://jsfiddle.net/a1wqbmy9/
This is not a runnable reproduction. Please provide a small repository or similar that demonstrates the issue.

> when in lifecycle created commit mutation not be logger in vue-devtool

I don't understand this sentence, sorry :(

**Comment by posva** [comment]
As I asked you in the other issue, please, use the forums or chats to ask questions
