### ISSUE TITLE
scoped slots infinite update loop when binded to same data more than once

### ISSUE THREAD

**Issue by iagafonov** [vuejs/vue#6153]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/38d0jj83/2/](https://jsfiddle.net/38d0jj83/2/)

### Steps to reproduce
Open console and run.

### What is expected?
There will not be an infinite loop

### What is actually happening?
Second sort-page-control generates infinite update loop:

Console: [Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <SortPageControl>
       <Root>

---
As I understand, list getter in sort-page-control produces additional watchers or something like this.
v2.3.3 have problem too

**Comment by yyx990803** [comment]
`Array.prototype.sort` is a mutating method. Copy the array before calling it.

**Comment by iagafonov** [comment]
@yyx990803 You broke my world. Couple of years I and my friend was sure that it is not mutating method :O And I'm not alone! :O

**Comment by PJCHENder** [comment]
I faced the same problem ... Your are not alone(￣∇￣).
