### ISSUE TITLE
Dynamic textarea value not updating

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue#6154]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/Akryum/gknyjk33/](https://jsfiddle.net/Akryum/gknyjk33/)

### Steps to reproduce
Create a dynamic element with `<component is="textarea" :value="value">`

### What is expected?
The value of the textarea is set when `value` changes.

### What is actually happening?
Nothing happens. When first created, the text area is empty even if `value` has a text value.

**Comment by Akryum** [comment]
Maybe related, it seems `v-bind` `prop` modifier isn't working properly on `<component>`: https://jsfiddle.net/Akryum/334kya3t/

![capture d ecran de 2017-07-18 17-39-00](https://user-images.githubusercontent.com/2798204/28326072-02016d6e-6be0-11e7-8594-7ff68d0b4094.png)

**Comment by Akryum** [comment]
Also, using render function is working great. Here is an example:

```javascript
render (h) {
  return h('div', { class: 'row' }, [
    h(this.element, {
      class: ['input', this.inputClass],
      attrs: {
        type: this.type,
        placeholder: this.placeholder,
        ...this.$attrs,
      },
      domProps: {
        value: this.text,
      },
      on: {
        input: this.update,
      },
    }),
  ])
},
```

**Comment by posva** [comment]
I think It's just that `value` doesn't work as an attr on `textarea`

**Comment by posva** [comment]
I don't know why it works with `v-bind:value` but it doesn't with a plain `value` attr

And as you find out, using `.prop` makes it work.

**Comment by Akryum** [comment]
My issue is related to using `<component is="textarea">`

**Comment by posva** [comment]
There's a regression thought...

**Comment by posva** [comment]
Yeah, it also break things when using `is="input"`

**Comment by posva** [comment]
I'm so confused... I cannot manage to reproduce it consistently..
