### ISSUE TITLE
variable synchronization  with local memory

### ISSUE THREAD

**Issue by vad11** [vuejs/vue#6155]
### What problem does this feature solve?
I want open vue web app and I want define variables with custom attribute to save in local memory, and update it for all opened browser tabs.

### What does the proposed API look like?
Simple define for same variables attribute : = local memory sync

**Comment by yyx990803** [comment]
Sorry, but this is not a concrete feature request, but a support question.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
