### ISSUE TITLE
Allow ternary v-bind:type with v-model.

### ISSUE THREAD

**Issue by nickmessing** [vuejs/vue#6158]
### What problem does this feature solve?
There is common "Show Password" pattern today and we have to use v-if/v-else for that. Can we consider allowing ternary expression that returns only one of `text,number,password,search,email,tel,url` allowed in `v-bind:type`?

### What does the proposed API look like?
```html
<input :type="showPassword ? 'text' : 'password'" v-model="text">
```

**Comment by javoski** [comment]
I suppose this is supported.

**Comment by nickmessing** [comment]
Whoops, sorry, missed that.

**Comment by nickmessing** [comment]
Oh, check the console, we have `[Vue warn]: Error compiling template`

**Comment by javoski** [comment]
When switching input types between `text`, `number` or `file`, it will lead to some strange behaviors because the model value doesn't match the type.

**Comment by nickmessing** [comment]
@javoski, `file` - yes, that's why we have a list of text-like inputs as I mentioned in description (`text,number,password,search,email,tel,url`)

**Comment by mosinve** [comment]
Another way to do this clearly at current release, is to avoid ternary, for example: 
https://jsfiddle.net/cihkem/103b96fr/

**Comment by yyx990803** [comment]
We will likely support full dynamic type for `v-model` in the next minor release, so closing this one for now.
