### ISSUE TITLE
vue-server-render: when the serverCacheKey option is a string，there is no error or tip

### ISSUE THREAD

**Issue by zhaorui19910121** [vuejs/vue#6162]
### Version
2.3.4

### Reproduction link
[https://github.com/zhaorui19910121/my-blog/blob/master/src/views/App.vue](https://github.com/zhaorui19910121/my-blog/blob/master/src/views/App.vue)

### Steps to reproduce
The link is my demo to learn vue ssr. Clone and npm install ->  modify the serverCacheKey options in App.vue to a string -> npm start -> localhost: 3000

### What is expected?
There should an error or a tip show in the terminal, but there is nothing.

### What is actually happening?
Nothing is rendered in my browser, and there is no error or tip in my terminal. I don't know what happened. It need much time to debug.

---
I think the source code in vue-server-render/build.js:
```
var key = name   '::'   getKey(node.componentOptions.propsData);
```
should throw an error, but i don't know why it doesn't.

**Comment by yyx990803** [comment]
There **is** an error if you add [proper error handling](https://github.com/vuejs/vue-hackernews-2.0/blob/master/server.js#L87-L98).

![screen shot 2017-07-19 at 7 35 30 am](https://user-images.githubusercontent.com/499550/28365066-086ee724-6c55-11e7-99db-25f39ea74a24.png)
