### ISSUE TITLE
Using $refs in computed is ok but do not access it before mounted (otherwise it will always be undefined)

### ISSUE THREAD

**Issue by kenberkeley** [vuejs/vue#6163]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/kenberkeley/5n9kanyp/7/](https://jsfiddle.net/kenberkeley/5n9kanyp/7/)

### Steps to reproduce
Just uncomment `console.log(this.comp)` in `created` hook and Run again

### What is expected?
`this.comp` should not always be `undefined`

### What is actually happening?
Before uncomment, everything works fine (`this.comp` is reactive).  
Once uncomment, `this.comp` would keep `undefined` still.

---
Why accessing to `computed:comp` before `mounted` will lead to itself not reactive with `this.n`?

**Comment by simplesmiler** [comment]
`$refs` is not reactive.

**Comment by kenberkeley** [comment]
@simplesmiler 
I know `$refs` is not reactive, but `this.n` is reactive

**Comment by kenberkeley** [comment]
So here is a explanation for it:
In `created` hook, `computed` cached the value of `this.comp` (`undefined`).
After that, if `this.n` not change, `this.comp` keeps `undefined` still

**Comment by kenberkeley** [comment]
https://vuejs.org/v2/guide/migration.html#cache-false-deprecated
