### ISSUE TITLE
v-model  binds the id of input radio dynamicly appears only for the first time

### ISSUE THREAD

**Issue by xiaoguifly** [vuejs/vue#6164]
### Version
2.3.0

### Reproduction link
[https://codepen.io/xiaoguifly/pen/jwjWdq](https://codepen.io/xiaoguifly/pen/jwjWdq)

### Steps to reproduce
When I click one of the radio list,for example the second item ,the id attribute of the radio element only appears for the first time through the console,then I bind the value attribute to the radio, the id attribute appears all the time  

### What is expected?
the id attribute  of  radio appears all the time

### What is actually happening?
the id attribute of radio appears only the first time

---
Vue.js version

2.3.0

Chrome version

59.0.3071.115 (64-bit)

**Comment by LinusBorg** [comment]
> When I click one of the radio list,for example the second item ,the id attribute of the radio element only appears for the first time through the console,then I bind the value attribute to the radio, the id attribute appears all the time

I don'T understand what you mean by that. To me, the elements seem to work great - styles are applied correctly, a log is printed ot the console for each item on each click ...

What exactly is wrong?

**Comment by xiaoguifly** [comment]
@LinusBorg  Please follow the steps:
1  open the console
2  click one of the items serveral times
3  see the different log,then you can find the differences between the first log and others(the first log has id ,others not)

**Comment by LinusBorg** [comment]
Not for me: 

![image](https://user-images.githubusercontent.com/1444526/28356613-03de16e4-6c69-11e7-9540-68efcafebc0d.png)

However now I understood your problem - the id seems to be disappearing when you expect i to be the id (converted to a string)

**Comment by xiaoguifly** [comment]
@LinusBorg  my problem is that when you add :value="item.name" to the input radio,then you will see the logs are the same,I don't know why

**Comment by LinusBorg** [comment]
because your v-model`is still `v-model="item.id"` which still is wrong.

**Comment by xiaoguifly** [comment]
@LinusBorg  when I replace v-model="item.id" with v-model="item.name",the problem is still exist.Am I use the v-model wrong?Because I delete v-model ,then all is ok. Please give me a similar example of its usage,thank you!!!

**Comment by LinusBorg** [comment]
Please look at my example. `v-model="item.name"` is still wrong.

I will not answer more questions in this issue. This is not a bug, it's a usage problem on your side. As I alrady suggested, please post your question to forum.vuejs.org or chat.vuejs.org. 

I'm happy to help you further on the forum, but not here.
