### ISSUE TITLE
v-else for v-for

### ISSUE THREAD

**Issue by stephenfin** [vuejs/vue#6167]
### What problem does this feature solve?
Python (and presumably other languages) has a nifty for-else pattern that lets you provide a fallthrough condition if the for loop did had no iterations. For example:

    >>> def test_func():
    ...     for x in my_values:
    ...     print(x)
    ...     else:
    ...     print('There were no values')
    ...
    >>> my_func([])
    There were no values

It's concise and simplifies a fairly common case. I'd like to see something similar in the Vue templates with the `v-for` directive:

    <div v-for="item of items">{{ item }}</div>
    <div v-else>There were no values</div>

Is this something anyone else would care for. If so, I can take a shot at implementing this.

### What does the proposed API look like?
Once completed, you would be able to use the `v-else`conditional like so:

    <div v-for="item of items">{{ item }}</div>
    <div v-else>There were no values</div>

**Comment by rpkilby** [comment]
For reference, this has been requested in the past as #4174.

**Comment by stephenfin** [comment]
@rpkilby This is why we ask before filing PRs :smile: Thanks for the heads up. I'll close as a dupe.

**Comment by drdilyor** [comment]
By the way, pythons else behaves completely different 👀
