### ISSUE TITLE
vue-for在和watch配合使用时表现异常.

### ISSUE THREAD

**Issue by wqj97** [vuejs/vue#6169]
### Version
2.4.1

### Reproduction link
[https://codepen.io/wqj97/pen/PjraXz](https://codepen.io/wqj97/pen/PjraXz)

### Steps to reproduce
在codepen链接中, 有详细说明
---

这个问题发生在watch一个变量变化, 且这个变量由v-for打印的时候, 会出现无反应的情况

自己分析原因可能出在v-for为了优化性能等待变化结束再进行渲染, 而watch的存在导致无法触发渲染 (瞎分析的, 见笑)

暂时解决办法是先在watch中用一个变量先存起来, 当所有变化完成后, 一并触发渲染, 详见watch中的valInFixed()

第一次提交Issue, 很多地方不专业, 见谅. 希望Vue越做越好

### What is expected?
v-for能正常渲染

### What is actually happening?
v-for没有任何反应

---
这个Bug出现在任何情况, 已经在CodePen中复现

**Comment by posva** [comment]
Hello,

This is working as intended. You'll find an explanation [here](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) :smile:

**Comment by wqj97** [comment]
thanks very much
