### ISSUE TITLE
Error compiling template, even though one root element

### ISSUE THREAD

**Issue by eu81273** [vuejs/vue#6170]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/k5h2fvqh/](https://jsfiddle.net/k5h2fvqh/)

### Steps to reproduce
1. `<p>` tag as Root element
2. put `<div>` tag as child element

### What is expected?
Render template correctly

### What is actually happening?
Error compiling template with message "Component template should contain exactly one root element"

**Comment by nickmessing** [comment]
Here's minimal repro: https://jsfiddle.net/gq2ckLLf/

**Comment by nickmessing** [comment]
That is exected behaviour, `<p>` tag can not have child `<div>` (and others too) so `<p><div></div></p>` is parsed as `<p></p><div></div></p>` and as you can see it's more than one root element. That's HTML limitations.

**Comment by nickmessing** [comment]
Complete list of elements that "close" `<p>` is available [here](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element)

**Comment by juliolimareis** [comment]
https://jsfiddle.net/k5h2fvqh/50/
