### ISSUE TITLE
Input's value does not change after changing data

### ISSUE THREAD

**Issue by whtsky** [vuejs/vue#6172]
### Version
2.4.1

### Reproduction link
[https://github.com/whtsky/__vue-value-shorthanded](https://github.com/whtsky/__vue-value-shorthanded)

### Steps to reproduce
1. Type something in the input, so the `a` is changed
2. Click `Clear A` button

### What is expected?
Input's value=`''`

### What is actually happening?
Input's value did not change

**Comment by Kingwl** [comment]
add a online demo  
https://jsfiddle.net/qbcv68uw/1/

**Comment by Kingwl** [comment]
:value should be a domProps   
actually  it was attrs   
i think https://github.com/vuejs/vue/pull/6159 is already fix that

**Comment by yyx990803** [comment]
This is a JSX transform issue - see https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/84

@nickmessing I think it would make sense to treat `value` and [other necessary attributes](https://github.com/vuejs/vue/blob/dev/src/platforms/web/util/attrs.js#L10-L18) as domProps by default in babel-plugin-transform-vue-jsx.

**Comment by nickmessing** [comment]
@yyx990803, I'll do that in the next few hours, sorry for offtopic but can you please merge my PR in `babel-plugin-transform-vue-jsx`?
