### ISSUE TITLE
Circular dependency when using WebPack

### ISSUE THREAD

**Issue by jjpe** [vuejs/vue#6173]
### Version
2.4.1

### Reproduction link
[https://stackoverflow.com/questions/45222335/how-to-divide-vue-js-code](https://stackoverflow.com/questions/45222335/how-to-divide-vue-js-code)

### Steps to reproduce
1. Copy the code from the SO link to a bare-bones Vue.JS project and add the necessary dependencies to the package.json
2. Start Node
3. Open the browser developer console 
4. go to the site hosted on Node
5. Find errors like:
    * [Vue warn]: Error in beforeMount hook: "TypeError: Cannot read property '500' of undefined"
    * TypeError: Cannot read property '500' of undefined 

### What is expected?
No errors, as the code itself is correct AFAICT.

Otherwise, if there need to be errors, please word them so that the user knows what concretely is wrong rather than having to open up a SO issue as well as a bug report.

### What is actually happening?
I get a vague message about something called a 'mountBefore hook', and 'property 500 of undefined not being readable'.

---
I simply want to use Vue.JS while being able to locally define themes.
The combination of the 2 has proven rather difficult so far.

**Comment by yyx990803** [comment]
This is not a bug report but a usage question.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Discord chat](https://chat.vuejs.org),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by jjpe** [comment]
I did that, and got a non-answer, same as here apparently.

**Comment by waratah** [comment]
I have a problem with my themes and I suddenly got this.

background is not a valid item in a theme and it gives this message.

default: {
            primary: 'blue',
            accent: 'pink',
            background: 'rgb( 28,45,63 )'
        },

Preferred option:   'background is not valid in a theme' error.
