### ISSUE TITLE
Can you support cucumber.js is chioce for unit test and ui test

### ISSUE THREAD

**Issue by kinanson** [vuejs/vue#6176]
### What problem does this feature solve?
I know mocha is good unit test tool.But I think cucumber.js is better then mocha.I don't have any idea how to integration cucumber with karma.Can you support this in the cli or teach me how to integration both.

### What does the proposed API look like?
see above

**Comment by yyx990803** [comment]
I personally have never used cucumber and issues are not where questions like this should be posted to.

Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Discord chat](https://chat.vuejs.org),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

**Comment by kinanson** [comment]
I think this is new feature.I want cli have new choice for cucumber.js......

**Comment by nickmessing** [comment]
@kinanson, vue-cli initialises your project with whatever template you want, if you want to have `cucumber` option available you can just clone [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack) and make your own template with `cucumber` support. Anyway, this is not a vue issue so locking this conversation.
