### ISSUE TITLE
困扰很久 求助 Property or method "toJSON" is not defined on the instance but

### ISSUE THREAD

**Issue by liuhuanhui** [vuejs/vue#6179]
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
2vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Forhere> at src\pages\shop\forhere.vue
       <Shop> at src\pages\shop\Shop.vue
         <App> at src\App.vue
           <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
2vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
       <Forhere> at src\pages\shop\forhere.vue
         <Shop> at src\pages\shop\Shop.vue
           <App> at src\App.vue
             <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
8vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <FlexboxItem> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox-item.vue
       <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
         <Forhere> at src\pages\shop\forhere.vue
           <Shop> at src\pages\shop\Shop.vue
             <App> at src\App.vue
               <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
2vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Badge> at node_modules\_vux@2.5.2@vux\src\components\badge\index.vue
       <Forhere> at src\pages\shop\forhere.vue
         <Shop> at src\pages\shop\Shop.vue
           <App> at src\App.vue
             <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
44vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Badge> at node_modules\_vux@2.5.2@vux\src\components\badge\index.vue
       <FlexboxItem> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox-item.vue
         <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
           <Forhere> at src\pages\shop\forhere.vue
             <Shop> at src\pages\shop\Shop.vue
               <App> at src\App.vue
                 <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
2vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
       <Forhere> at src\pages\shop\forhere.vue
         <Shop> at src\pages\shop\Shop.vue
           <App> at src\App.vue
             <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53
2vue.esm.js?855e:459 [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <FlexboxItem> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox-item.vue
       <Flexbox> at node_modules\_vux@2.5.2@vux\src\components\flexbox\flexbox.vue
         <Forhere> at src\pages\shop\forhere.vue
           <Shop> at src\pages\shop\Shop.vue
             <App> at src\App.vue
               <Root>
warn @ vue.esm.js?855e:459
warnNonPresent @ vue.esm.js?855e:1615
get @ vue.esm.js?855e:1656
setPanelContent @ VM29841:38
(anonymous) @ VM29841:53

**Comment by pangjunpeng** [comment]
我靠我也是啊，莫名其妙诶
