### ISSUE TITLE
Table width binding not update automatically

### ISSUE THREAD

**Issue by doodlewind** [vuejs/vue#6181]
### Version
2.4.2

### Reproduction link
[http://jsbin.com/geyinet/1/edit?html,js,output](http://jsbin.com/geyinet/1/edit?html,js,output)

### Steps to reproduce
With the input box filled with 0 by default, simply click on button [ 10px]

### What is expected?
First table cell width bound with `:width` grows automatically (a method is triggered to change the data property, then the cell's width bound with this property should also change).

### What is actually happening?
No DOM update is performed unless uncommenting the `$forceUpdate` statement

---
Why must I manually call the VM to perform a force update? Is this a feature or a bug?

**Comment by javoski** [comment]
See [https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats)
