### ISSUE TITLE
this.$refs.key return undefined after hot reload

### ISSUE THREAD

**Issue by Shiva127** [vuejs/vue#6182]
### Version
2.4.2

### Reproduction link
No reproduction link, need hot reload...

### Steps to reproduce
Use this vue file:

```vue
<template>
  <div>
    <div ref="test"></div>
  </div>
</template>

<script>
export default {
  name: 'test',
  mounted () {
    setInterval(() => {
      console.log(this.$refs.test)
    }, 2000)
  }
}
</script>

<style>
</style>
```

Run it then edit the file, change `this.$refs.test` to `this.$refs.test.clientWidth`, save and watch the console.

### What is expected?
After hot reload, display the width of the `div`.

### What is actually happening?
After hot reload, return `undefined`, then the width of the `div`.

---
It the same if you use a `$refs` in a function of an event listener. Even if you destroy it in `deforeDestroy`.

**Comment by posva** [comment]
That happens because you have a `setInterval` still running, you should clear it in beforeDestory:
```vue
<template>
  <div>
    <div ref="test"></div>
  </div>
</template>

<script>
export default {
  name: 'test',
  mounted () {
    this.interval = setInterval(() => {
      console.log(this.$refs.test)
    }, 2000)
  },
  beforeDestroy () {
    clearInterval(this.interval)
  }
}
</script>
```

**Comment by noomz** [comment]
Wait. This is not about interval, he just want to show that `$refs.key` will be `undefined`. It seems like after hot-reloading, reference on `$refs.key` is missing. I still have this problem with Vue CLI 3.0.0-rc.11

**Comment by CrashyBang** [comment]
Can confirm I am not using `setInterval` anywhere and still having this issue.

**Comment by gunduzemreozer** [comment]
Yes, unfortunately I live this issue. I'am using this.$nextTick and also setTimeout, both of them are same result. I write console.log this.$refs on nextTick and it returns id of it in object key but the value is undefined.

**Comment by ecgk** [comment]
Im having the same issue. It was working in vue 2.5.17

**Comment by JhumanJ** [comment]
Same issue here.

**Comment by gilles-crealp** [comment]
FYI, the response from @posva is correct; it was because `setInterval` was still running.

**Comment by antoniandre** [comment]
In my case, I had event listeners which were not removed correctly on destroy.

**Comment by jonalxh** [comment]
Same case here, I was creating some listeners over my refs, I solved it by removing the listeners on the beforeDestroy hook. Thanks.
