### ISSUE TITLE
 <script src="./node_modules/vue/dist/vue.js"></script> Vue is not defined

### ISSUE THREAD

**Issue by Richar-Dada** [vuejs/vue#6183]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="./node_modules/vue/dist/vue.js"></script>
</head>
<body>
    <div class="app">
        <input type="text" v-model="name">
        <ul>
            <li v-for="user in newUsers" >
                {{ user.name }}
            </li>
        </ul>
    </div>
    <script>
        new Vue({
            el: '.app',
            data: {
                name: '',
                users: [
                    { name: 'Bruce' },
                    { name: 'Chuck' },
                    { name: 'Jackie' },
                    { name: '赵' }
                ] 
            },
            computed: {
                newUsers: function () {
                    var that = this;
                    return that.users.filter(function (user) {
                        return user.name.toLowerCase().indexOf(that.name.toLowerCase()) !== -1;
                    })
                }

            }
        })
    </script>
</body>
</html>

### What is expected?
Vue can be use

### What is actually happening?
Vue is not defined

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
