### ISSUE TITLE
"invalid expresson" in Internet Explorer when attribute contains tab characters

### ISSUE THREAD

**Issue by sa-0001** [vuejs/vue#6184]
### Version
2.4.2

### Reproduction link
[https://codepen.io/anon/pen/awegqr?editors=1111](https://codepen.io/anon/pen/awegqr?editors=1111)

### Steps to reproduce
when using a component which contains an object property, and splitting the object across multiple lines in a Pug template, Internet Explorer fails to compile the template with the error message "invalid expression".

while experimenting trying to fix this issue i found that removing the tab characters will cause the component to successfully render.  it's probably due to html-encoded characters (tabs, among others) which can't be or aren't decoded before eval.

before (does not render in IE): https://codepen.io/anon/pen/awegqr?editors=1111
after (renders in IE): https://codepen.io/anon/pen/VWoJXv?editors=1111

both examples correctly render in Chrome,Firefox

### What is expected?
bound prop containing object is evaluated

### What is actually happening?
in IE, string cannot be evaluated as it contains tab characters (other characters may have a similar effect)

**Comment by LinusBorg** [comment]
I don't see how we could do anything about this, since we can't access the attribute's value before IE itself.

**Comment by sa-0001** [comment]
if i do not instantiate the vue app and inspect the element in IE:

> el.attributes['v-bind:settings']

this is the result:

> {						component: 'alpha',						worksInIE: false				}

(i don't know how to display this in markdown, but all the tab characters are still there, perfectly preserved)

if i then later manually instantiate the app, i get the error "invalid expression".  meanwhile, in Firefox, all the above is exactly the same except that the component successfully renders.

**Comment by posva** [comment]
Unfortunately, there is nothing we can do as @LinusBorg said. The error is unrelated to Vue and happens before Vue even gets to parse the template

**Comment by sa-0001** [comment]
that's strange since

`el.attributes['v-bind:settings']`

returns exactly the same string in Firefox and IE.  are you saying that Vue uses a different method to access attribute values?

**Comment by posva** [comment]
I'm saying that the error is unrelated to Vue as it happens before Vue runs. BTW, it runs fine on IE11

**Comment by sa-0001** [comment]
to try and explain my confusion, i have produced a new example in HTML (eliminating the variable of Pug template)

before (renders in FF, Ch, *not* in IE 11.4) https://codepen.io/anon/pen/MoNNdK?editors=1111
after (renders in FF, Ch, IE 11.4) https://codepen.io/anon/pen/GEVVaY?editors=1111

to reiterate, in (my particular) IE (11.4), and the IE of dozens of our users (this is how i found the issue, due to bug reports about a missing field), the first example does not render, and the second example does, and the only difference between the two is tab characters.  if you edit the first example and remove the tabs one by one, the moment you remove the final tab the component will render correctly.

if it's still something that is considered not relevant to vue, would you be able to point me toward the part of the source code which reads attribute values?

**Comment by LinusBorg** [comment]
I'l' re-open this to take a closer look, maybe it's related to template parsing?

**Comment by sa-0001** [comment]
i am guessing that instead of using the DOM-nodes, Vue uses innerHTML, which i tested and does indeed return a different value in FF and IE.  whereas using el.attributes['v-bind:settings'] returns the same value.

**Comment by posva** [comment]
Ok, thanks for the further explanation, it makes more sense. I thought you were having an error `invalid expression` in IE, but it's Vue generating that error.
I don't know why, I just get no error in my IE...

**Comment by yyx990803** [comment]
Should be fixed in cfd73c2386623341fdbb3ac636c4baf84ea89c2c
