### ISSUE TITLE
2.3.4 to 2.4.2，Vue works wrong

### ISSUE THREAD

**Issue by gxmzjxk** [vuejs/vue#6185]
### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
import vueComp from '../ad-generator.vue';
var Ad = Vue.extend(vueComp);
var ad = new Ad({
     el: document.createElement('div'),
     data: data
});

### What is expected?
work properly，the data will prop into the component instance "ad"

### What is actually happening?
the props data in instance is undefined

---
when i run npm i，the vue upgrade into 2.4.2 , this problem happens.

**Comment by LinusBorg** [comment]
Hello, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.vuejs.org) to create an issue - thank you!

Specific reason: The provided reproduction link is not a reproduction, it's the vue repository.
