### ISSUE TITLE
data 中的值如何绑定多种数据类型

### ISSUE THREAD

**Issue by QinFeiFei** [vuejs/vue#6186]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/QinFeiFei/0vqqrjc3/3/](https://jsfiddle.net/QinFeiFei/0vqqrjc3/3/)

### Steps to reproduce
字符串转为数组不报错，数组再转为字符串就赋值失败了。

### What is expected?
..

### What is actually happening?
...

---
...

**Comment by QinFeiFei** [comment]
我期望的效果是数组-字符串-对象可以自由转换

**Comment by posva** [comment]
You used the same method on both buttons
