### ISSUE TITLE
Single file component templates can not share a script file

### ISSUE THREAD

**Issue by michaelalhilly** [vuejs/vue#6189]
I separate component code from its template. In some cases the code is the same for multiple templates and therefore I'd like to reference the same code. Unfortunately, the second imported template gets rendered twice.

Is there any way to do this?

Here's what I'm doing now:

This is the first template.
/src/js/view/loading/spinner.vue
```
<script src="./script.js"></script>
<template lang="pug">
	transition(name="spin-spinner" v-bind:duration="{ enter: 500, leave: 500 }")
		div(v-if="loading" class="spinner")
			div.wrap
				div.node.node-1
				div.node.node-2
</template>
```
This is the second template.
/src/js/view/loading/scanner.vue
```
<script src="./script.js"></script>
<template lang="pug">
	div(v-if="loading" class="scanner")
		div.outer
			div.inner
</template>
```
This is the shared script.
/src/js/view/loading/script.js
```
export default {
	props: ["loading"]
}
```
This is the demo template where I am using the 2 components above.
/src/js/view/demo/component.vue
```
<script src="./script.js"></script>
<template lang="pug">
	div
		div.row
			div.box
				spinner(:loading="loading")
		div.row
			div.box
				scanner(:loading="loading")
</template>
<style scoped>
	.box {
		position: relative;
		width: 200px;
		height: 100px;
	}
</style>
```
This is the demo script.
/src/js/view/demo/script.js
```
import Spinner from "../loading/spinner.vue"
import Scanner from "../loading/scanner.vue"

export default {
	components: { Spinner, Scanner },
	data: function() {
		return {
			loading: true
		}
	},
	created: function() {

		setTimeout(() => {

			this.loading = false

		}, 5000)
	}
}
```

**Comment by yyx990803** [comment]
You can use a mixin instead of sharing the script.

**Comment by michaelalhilly** [comment]
@yyx990803 Apologies for not using the issue helper. Will definitely do so if I have another issue.

Thanks for the quick reply. I will take a look at mixins. Thank you.
