### ISSUE TITLE
Invalid prop: type check failed for prop "value". Expected String, Number, , got Symbol.

### ISSUE THREAD

**Issue by vvpvvp** [vuejs/vue#6192]
### Version
2.3.4

### Reproduction

![image](https://user-images.githubusercontent.com/7303371/28489935-0b60a7c0-6f01-11e7-8233-a5fbc6e931ec.png)

### Steps to reproduce
use a Symbol value 

### What is expected?
Symbol type is ok

### What is actually happening?
Symbol type is not ok

**Comment by LinusBorg** [comment]
An error message is not a reproduction. 

Pleaser provide code that leads to this error. 

---

Likely, you didn't define a symbol as an allowed type for this prop.
