### ISSUE TITLE
Select with v-model triggers change event when its options are changed

### ISSUE THREAD

**Issue by floorish** [vuejs/vue#6193]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/floorish/e2h2vwc2/](https://jsfiddle.net/floorish/e2h2vwc2/)

### Steps to reproduce
Dynamically change the `<option>`s in a `<select v-model="val">` tag and the `v-model` triggers a change event, but the actually chosen option hasn't changed.

### What is expected?
`v-model` does not trigger a change event

### What is actually happening?
`v-model` triggers a change event

---
Change of behaviour intruduced in https://github.com/vuejs/vue/commit/c90b140e80f1bd5d01c733a5bd9fa6e9cb3c2b4d

**Comment by jkzing** [comment]
Looks like a regression

**Comment by posva** [comment]
The event is triggering at the beginning as well while it shouldn't
