### ISSUE TITLE
在绑定的方法中使用jQuery的deffered，但不会等待.done就被直接触发了。。。

### ISSUE THREAD

**Issue by nkdanfer** [vuejs/vue#6195]
### Version
2.2.1

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
在jsFiddle上无法重现。
jsFiddle上只是不触发。
但我在本机上是不等到defferred返回resloved就触发done了。
【详细代码在补充说明里】

### What is expected?
根据$.when().done().done()的顺序一个个执行。

### What is actually happening?
$.when().done().done()中的方法是一起调用的，没有等待

---
<script src="https://unpkg.com/jquery"></script>
<script src="https://unpkg.com/vue"></script>

<div id="app">
  <p v-on:click="test">{{ message }}</p>
</div>
==================================================
new Vue({
    el:'#app',
    data:{
    	message: 'Hello Vue.js!'
    },
    methods:{
      test:function(){
      alert('');
      $.when(this.d1()).done(this.d2());
 		},
    d1:function(){
     var count=0;
     var dfd=$.Deferred();
     var task=function(){
      alert("d1:" count);
      count  ;
      if(count>6) dfd.resolved();
			};
    return dfd.promise();
		}, 
    d2:function(){
     var count=0;
     var dfd=$.Deferred();
     var task=function(){
      alert("d2:" count);
      count  ;
      if(count>3) dfd.resolved();
		};
    return dfd.promise();
		}, 
  },
});

**Comment by gebilaoxiong** [comment]
感谢您提交的问题，关于其他框架的问题请到对应的仓库中提交issue

**Comment by Kingwl** [comment]
IMO this is not a issue of vue😅

**Comment by nkdanfer** [comment]
sorry,是我没有做足够的测试，不是vue的问题。关闭了吧。应该是我没会用deferred的问题。
😅

**Comment by javoski** [comment]
$.Deferred.done 接收一个函数作为 callback，而不是一个 Promise.

**Comment by nkdanfer** [comment]
是了，要用函数。一直写后台，不太明白js这么灵活的东西，写什么都不报错，还能运行。。。
