### ISSUE TITLE
How to create an NPM package of a project containing a Vuex module?

### ISSUE THREAD

**Issue by stephan-v** [vuejs/vue#6198]
### What problem does this feature solve?
Integration of Vuex modules through NPM.

### What does the proposed API look like?
I am wondering how to do this properly. I have a library of components that I would like to publish but they rely on the store state of a Vuex module.

How do I register my Vuex module into the store of someone who has installed my packaged through NPM?

Getting my components hooked up by creating a plugin is not a big deal:

```
export function install (Vue) {
  Vue.component('test', Test)
  /* -- Add more components here -- */
}
```

Unfortunately there does not seem to be a hook like this for registering Vuex modules. 

Can someone provide me with an example repository or perhaps guide my in the right direction? 

Perhaps I am wrong to even assume it would be viable to have someone else import my Vuex module if this is the case I would love to hear it.

I am asking here because gitter and stackoverflow do not yield any results since this is a pretty _in-depth_ question.

Something similarly has also been asked here:

https://forum.vuejs.org/t/how-to-build-open-source-components-that-others-can-use-like-date-picker-time-picker-and-etc/13524/13

This has not been resolved though.

**Comment by LinusBorg** [comment]
1. This is the Vue repository, not the vuex repository
2. This is essentially a "style" question, or one for better documentation "how to design a vuex extension)
3. I just answered the forum question.

So I will close this as it's in the wrong place.
