### ISSUE TITLE
rander里面如何使用自定义filter 

### ISSUE THREAD

**Issue by mrerhuo** [vuejs/vue#6206]
### Version
2.4.2

### Reproduction link
[http://127.0.0.1](http://127.0.0.1)

### Steps to reproduce
rander里面如何使用自定义filter 

### What is expected?
rander里面如何使用自定义filter 

### What is actually happening?
rander里面如何使用自定义filter 

---
rander里面如何使用自定义filter

**Comment by Kingwl** [comment]
https://jsfiddle.net/g0nxocbh/

**Comment by mrerhuo** [comment]
think y
