### ISSUE TITLE
Property syntax mixture

### ISSUE THREAD

**Issue by RobertBColton** [vuejs/vue#6207]
### What problem does this feature solve?
Currently I am writing a custom component where I have some properties, such as `value`, that I do not require validation for, but others I do require validation for. It would be nice if I could mix the array and object syntax to declare both of these kinds of properties easier.
```javascript
	props: {
		items: {
			type: Object,
			required: true
		},

		value: { }
	}
```

### What does the proposed API look like?
Ideally I would like the following to work:
```javascript
	props: {
		items: {
			type: Object,
			required: true
		},

		'value'
	}
```

**Comment by javoski** [comment]
The API you proposed is not a valid JavaScript syntax.
You can just use `null` to declare that the prop is not need for validation.
```js
props: {
  value: null
}
```
