### ISSUE TITLE
Select Options not Rendering as Components

### ISSUE THREAD

**Issue by Sephster** [vuejs/vue#6208]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/e1fjxwcr/2/](https://jsfiddle.net/e1fjxwcr/2/)

### Steps to reproduce
Create a component that produces <option> tags as templates that can be reused in a select box.

### What is expected?
The select options from the component should be rendered in the select box

### What is actually happening?
The select box is empty with just a white space where I would expect the options to be

**Comment by javoski** [comment]
Other element tags except `<option>` and `<optgroup>` will be ignored automatically by the browser according to the [html spec](https://w3c.github.io/html/sec-forms.html#the-select-element).

You can use `is` attribute to avoid this, see [https://jsfiddle.net/e1fjxwcr/3/](https://jsfiddle.net/e1fjxwcr/3/)
```html
<div id="broken-example">
  <select>
    <option is="test-options"></option>
  </select>
</div>
```
or wrap all html in template option, see [https://jsfiddle.net/e1fjxwcr/4/](https://jsfiddle.net/e1fjxwcr/4/)
```js
var brokenExample = new Vue({
  el: '#broken-example',
  template: `
  	<select>
    	<test-options></test-options>
    </select>
  `
});
```
