### ISSUE TITLE
select element can't be rendered correctly by vue 2.0.0 (or above) in IE 11

### ISSUE THREAD

**Issue by nightost** [vuejs/vue#6209]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/ntdd9g2a/86/](https://jsfiddle.net/ntdd9g2a/86/)

### Steps to reproduce
1. open the link in IE11
2. see the select element does't be rendered correctly

### What is expected?
The second option('菜单二') in select element should be in view 

### What is actually happening?
The third option('菜单三') in select element is still in view 

---
I have to use setTimeout to solve this problem. So i want to know how it happened

**Comment by posva** [comment]
There seems to be a problem, indeed. I'm not sure if we already fixed this but didn't released it yet though

**Comment by jkzing** [comment]
I didn't find the code on dev or a PR fixed this problem, so #6213 😁

**Comment by sidecut** [comment]
Workaround until this is fixed (which probably doesn't work in SSR):
```
  mounted: function() {
    var self = this;
    window.setTimeout(function() {
      self.selected = '2';
    }, 0);
```
`Vue.nextTick()` did not work.

**Comment by nightost** [comment]
Thank you for that.
