### ISSUE TITLE
vue 异步的组件可以命名

### ISSUE THREAD

**Issue by shuizhongyue120** [vuejs/vue#6210]
### What problem does this feature solve?
使用vue异步组件时，发现打包之后的组件的名字都是0.js，1.js等等。
可不可以像webpack 一样。异步组件可以命名

### What does the proposed API look like?
 require.ensure([], () => {
                resolve(require('../com/option.vue'))
            },"option");
or
 require(['../history/index.vue'], resolve,"xxxx");

**Comment by shuizhongyue120** [comment]
aaa

**Comment by shuizhongyue120** [comment]
有网友也遇到了同意的问题
[(https://segmentfault.com/q/1010000006727182)]

**Comment by shuizhongyue120** [comment]
[]((https://segmentfault.com/q/1010000006727182))

**Comment by shuizhongyue120** [comment]
segmentfault 上有人提了同样的疑问 https://segmentfault.com/q/1010000006727182

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
