### ISSUE TITLE
Empty $scopedSlots

### ISSUE THREAD

**Issue by Fl0pZz** [vuejs/vue#6212]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/u4w64n62/1/](https://jsfiddle.net/u4w64n62/1/)

### Steps to reproduce
Click `run` on jsfiddle and see console

### What is expected?
[Here](https://vuejs.org/v2/guide/render-function.html#Slots) is example with `$scopedSlots`

### What is actually happening?
It's not working!
`Error in render function: "TypeError: this.$scopedSlots.default is not a function"`

**Comment by LinusBorg** [comment]
You are not using the scoped slot syntax, instead you pass `<emited>` as a normal slot.

Please read the documentation here: https://vuejs.org/v2/guide/components.html#Scoped-Slots

If that doesn't help, ask on forum.vuejs.org or chat.vuejs.org
