### ISSUE TITLE
Build issue?

### ISSUE THREAD

**Issue by josephzidell** [vuejs/vue#6214]
Just updated to v2.4.2 and noticed this when reviewing the newest updates. Thought I'd bring this to your attention.

![screenshot 2017-07-25 11 57 46](https://user-images.githubusercontent.com/1812443/28581680-debdd62a-7130-11e7-8b21-beb6dbcce6fc.png)

**Comment by LinusBorg** [comment]
Thats normal, as that's the non-minified build. Those statements would be removed when minified with Uglifyjs.

**Comment by josephzidell** [comment]
Okey dokey
