### ISSUE TITLE
Validate numbers-only-field with get and set

### ISSUE THREAD

**Issue by getsetbro** [vuejs/vue#6215]
### Version
2.4.2

### Reproduction link
[http://jsbin.com/qeyiwagiqe/1/edit?js,output](http://jsbin.com/qeyiwagiqe/1/edit?js,output)

### Steps to reproduce
Observe http://jsbin.com/qeyiwagiqe/1/edit?js,output
Type text into the second field and tab out of it
Notice that the numbers-only validation doesn't happen until you tab to the last field and type something.

### What is expected?
I'd prefer the numbers-only validation to happen while typing in the field.

### What is actually happening?
The validation does not occur until a non-numbers only field is updated.

---
This may no be an issue with Vue. I'd welcome info on the best way to do numbers-only validation in a TEXT field.

**Comment by nickmessing** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Here you can see few ways how use inputs as numbers: https://jsfiddle.net/b67aunsr/
