### ISSUE TITLE
Opt-in virtual DOM

### ISSUE THREAD

**Issue by janat08** [vuejs/vue#6217]
### What problem does this feature solve?
A lot of complex UI elements generally reside outside of v-for which is where virtual DOM may hypothetically be helpful, looking through ui frameworks few provide extensibility or that is the degree of freedom that you would see without virtual DOM, pretty much none of it relates to rendering lists.

### What does the proposed API look like?
An option to render v-for with virtual DOM implying that virtual DOM is absent elsewhere, and is entirely opt-in.

**Comment by posva** [comment]
vdom is already opt-in. It's ui's framework responsibility to make it easy to customise, not Vue's
We do provide scoped slots and props to make it customisable

**Comment by sirlancelot** [comment]
I'm not sure I understand the problem, nor the conclusion that Virtual DOM should be optional.

**Comment by janat08** [comment]
CSS frameworks find it difficult to provide options or just as well port components or something because of virtual DOM where it basically is any good in lists, of which very small portion of CSS framework will in fact deal with- that is have a component for table.
