### ISSUE TITLE
circular dependency on observed properties

### ISSUE THREAD

**Issue by indus** [vuejs/vue#622]
i have two properties in my model that depend on each other. I run into a loop if i want to update one of them. What can I do to avoid this? I have seen your `_locked` property in the two-way binding, but there are no directives in my case. I tried to set the `active` property on the observer to `false` with no effect.

**Comment by M165437** [comment]
I've got a case like this and can't get my head around how to redesign it in order to make it work. Any suggestion?

```
var vm = new Vue({
  
  el: '#temperature-converter',
  
  data: {
    celsius: 0,
    fahrenheit: 32,
    kelvin: 273.15
  },
 
  watch: {
    'fahrenheit': function(val) {
      this.celsius = 5/9 * (parseInt(val) - 32);
      this.kelvin = (parseInt(val) + 459.67) * (5/9);
    },
    'celsius': function(val) {
      this.fahrenheit = 9/5 * parseInt(val) + 32;
      this.kelvin = parseInt(val) + 273.15;
    },
    'kelvin': function(val) {
      this.celsius = parseInt(val) - 273.15;
      this.fahrenheit = parseInt(val) * (9/5) - 459.67;
    }
  }
  
});
```

**Comment by yyx990803** [comment]
@M165437 Make one of them the source of truth and make the other two computed properties. For the two computed properties, their setters should just update the source of truth.

**Comment by M165437** [comment]
That works. Thanks a lot! ([Example on JS Bin](https://jsbin.com/tagupab/edit?html,js,output))

```
var vm = new Vue({
  
  el: '#temperature-converter',
  
  data: {
    celsius: 0
  },
  
  computed: {
    fahrenheit: {
      get: function() {
        return 9/5 * parseInt(this.celsius) + 32;
      },
      set: function(val) {
        this.celsius = 5/9 * (parseInt(val) - 32);
      }
    },
    kelvin: {
      get: function() {
        return parseInt(this.celsius) + 273.15;
      },
      set: function(val) {
        this.celsius = parseInt(val) - 273.15;
      }
    }
  }
  
});
```

**Comment by M165437** [comment]
A last one, a bit more complicated. It's a form to define a time span by setting start time (A) and finish time (B) and/or a duration (Diff) – here simplified with integers. Depending of which fields are filled the third one will be calculated. The rules are as follows:

A changes B if Diff is set
B changes Diff if A is set
Diff changes B if A is set
B sets A if A not set but Diff
Diff sets A if A not set but B

I've got a working script using `$watch`. Is this the way to go? ([Script on JS Bin](https://jsbin.com/gujuka/edit?html,js,output)) Thanks a lot!

```javascript
var vm = new Vue({
  
  el: '#calculate-difference',
  
  data: {
    diff: '',
    a: '',
    b: ''
  },
  
  watch: {
    'a': function(val) {
      if (val === '') return;
      
      if (this.diff !== '') {
        var newB = parseInt(val) + parseInt(this.diff);
        if (parseInt(this.b) !== newB) this.b = newB;
      }
    },
    'b': function(val) {
      if (val === '') return;
      
      if (this.a !== '') {
        var newDiff = parseInt(val) - parseInt(this.a);
        if (parseInt(this.diff) !== newDiff) this.diff = newDiff;
      } else if (this.a === '' && this.diff !== '') {
        var newA = parseInt(val) - parseInt(this.diff);
        if (parseInt(this.a) !== newA) this.a = newA;
      }
    },
    'diff': function(val) {
      if (val === '') return;
      
      if (this.a !== '') {
        var newB = parseInt(this.a) + parseInt(val);
        if (parseInt(this.b) !== newB) this.b = newB;
      } else if (this.a === '' && this.b !== '') {
        var newA = parseInt(this.b) - parseInt(val);
        if (parseInt(this.a) !== newA) this.a = newA;
      }
    }
  }
  
});
```

**Comment by kristofferdarj** [comment]
Ok this is a bit old but a problem with the way in the last comment is that a user can only input stuff in the celsius field. Trying to write anything in say Fahrenheit will change celsius which will then immediately change fahrenheit. 

Try typing 40 in the fahrenheit field for example.

I had to implement a similar thing with only two fields with two watchers and a semafor. Didn't feel right but it was the way I came up with.

**Comment by candu** [comment]
@kristofferdarj, @M165437 - if you drop the `parseInt()` calls, it behaves much more reasonably.  Otherwise these operations are not strict inverses of each other, so the fixed point - see comment by @yyx990803 about "stabilizing" above - is not what you expect, and that's what leads to the "F changes C changes F again" problem you're seeing.

See the [Vue docs](https://vuejs.org/v2/guide/migration.html#Two-Way-Filters-replaced) for ideas on how to round the shown values in your `<input>` elements to integers.
