### ISSUE TITLE
Attribute "key" looks invalid

### ISSUE THREAD

**Issue by KIDFUCKER** [vuejs/vue#6222]
### Version
2.4.2

### Reproduction link
[https://github.com/KIDFUCKER/vue-demo1.git](https://github.com/KIDFUCKER/vue-demo1.git)

### Steps to reproduce
1.Open index.html
2.Close item "2" （click the button "x" behind "2"）

### What is expected?
List will has 2 items left: "1" and "3"

### What is actually happening?
List has 2 items left: "1" and "2"

---
I bind attribute "key" to component "Item", but "v-for" reuse a component instance.

**Comment by KIDFUCKER** [comment]
My issue comes from a simple html file. Codes listing as follow:
`<!DOCTYPE html>
<html>
<head>
    <title>todo</title>
    <script type="text/javascript" src="https://unpkg.com/vue"></script>
</head>
<body>
<div id="app"></div>
</body>
<script type="text/javascript">
    var template = 
    `<div id="todo-list-example">
        <ul>
            <Item
                v-for="(todo, index) in todos"
                v-bind:index="index"
                v-bind:title="todo"
                v-on:remove="remove"
            ></Item>
        </ul>
    </div>`;
    var Item = {
      template: 
      `<li>
            {{ myTitle }}
            <button v-on:click="remove">X</button>
        </li>`,
        data: function () {
            return {
                myTitle: this.title
            }
        },
        props: ['title', 'index'],
        methods: {
            remove: function () {
                this.$emit('remove', this.index)
            }
        }
    };
    new Vue({
        el: '#app',
        template: template,
        data: {
            newTodoText: '',
            todos: [
                '1',
                '2',
                '3'
            ]
        },
        methods: {
            addNewTodo: function () {
                this.todos.push(this.newTodoText)
                this.newTodoText = ''
            },
            remove: function (index) {
                this.todos.splice(index, 1);
            }
        },
        components: {
            'Item': Item
        }
    })
</script>
</html>`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Using the index as the key in that scenario won't work, you need to use unique keys, but in your example, when the element 2 is removed, the 3rd elements takes its place. If you use `todo` as the key, it will work

**Comment by KIDFUCKER** [comment]
Thank you very much! It was a big help.
