### ISSUE TITLE
v-for key报错

### ISSUE THREAD

**Issue by bigcui** [vuejs/vue#6226]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/9k0yozbg/](https://jsfiddle.net/9k0yozbg/)

### Steps to reproduce
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

(found in <Root>)

### What is expected?
希望在安装的vue的时候 声明给用户 在编译的时候给用户  或者及时更新官网文档；
因为package里面是写的^2.3.0 重新安装的时候 就默认安装到nodemodule里了 2.3以后最新的包了 而用户却不知道 

### What is actually happening?
项目报错 出现红色警告  console里面
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

(found in <Root>)

**Comment by LinusBorg** [comment]
Your key is not unique, and it's not a primitive value.

This is also documented [here](https://vuejs.org/v2/api/#key) by the expected value for `key`

**Comment by anhzhi** [comment]
It's better that vue relax the restrictions on keys that supports string、number and **# object**
