### ISSUE TITLE
I cannot get already render dom in mounted funtion but tutorial say I can

### ISSUE THREAD

**Issue by PleaseTryAgain** [vuejs/vue#6229]
### Version
2.4.2

### Reproduction link
https://jsfiddle.net/50wL7mdz/49673/

### Steps to reproduce
https://jsfiddle.net/50wL7mdz/49673/
this is a example like my project faced issue

### What is expected?
I can obtain already render dom

### What is actually happening?
I get before render dom

---
please help me out, also when import a component I can get dom in parent template right away! can you help me again. I solved this with setTimeout function. That is not exactly right...

this issue I solved it by getting this dom after object voluation。then use this.$nextTick. but whenever I use this function.the dom will computed agian.that is not I want

**Comment by PleaseTryAgain** [comment]
html

``

> <script src="https://unpkg.com/vue"></script>
> 
> <div id="app">
>   <p>{{ message }}</p>
>   <ul class='inforList'>
>     <li v-for='(item, index) in list'>
>       <div>
>         {{item.name}}
>       </div>
>       <div>
>         {{item.age}}
>       </div>
>     </li>
>   </ul>
> </div>


js
> 

new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!',
    list: []
  },
  methods:{
  	chooseForm() {
    	this.getSomeInfor()
      //...other METHODS
		},
  	getSomeInfor() {
    	// actural is ajax request, there use a setTimeout function
      setTimeout(() => {
      	console.log(2222)
      	this.list = [{name: '1111', age: 11}, {name: '2222', age:'22'},{name: '3333', age: 33},{name: '4444', age: 44},{name: '5555', age: 55}]
      }, 5000)
    }
  },
  mounted: function(){
		this.chooseForm();
    // cannot obtain already render dom height
    console.log(document.getElementsByClassName('inforList')[0].offsetHeight)
    // also cannot obtain already render dom height after using this.$nextTick
    this.$nextTick(() => {
    	console.log(document.getElementsByClassName('inforList')[0].offsetHeight)
    })
  }
})

**Comment by nickmessing** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The code works as expected, your data is empty (`list: []`) so the height of `ul.inforList` is 0. What happens is: Vue calls `mounted` method, `mounted` calls `chooseForm` which calls `getSomeInfor` which starts a timer, then [call stack](https://developer.mozilla.org/en-US/docs/Glossary/Call_stack) gets cleared back up to `mounted` where it does `console.log`, timer didn't finsh yet so `list` is still emptry array and `ul` has 0 height. `this.$nextTick` just adds next function to the end of [event loop](https://developer.mozilla.org/en/docs/Web/JavaScript/EventLoop) (timer still didn't finish), when stack gets completely cleared VM pulls first thing (added by `nextTick`) from event loop into the call stack and executes that, timer still didn't finish, list is still empty, height is still 0, after some time (~5000ms) VM pulls function from `setTimeout` into the event loop, then pulls it from event loop into the call stack, then executes, so if you want to get the height you need to wait for this moment ([example](https://jsfiddle.net/rmm8a8yf/)). From links above you can find more about how call stack and event loops work in modern JavaScript VMs.

**Comment by PleaseTryAgain** [comment]
@nickmessing   very nice answer!!! thanks a lot, thanks for you patience and detailed explanation！
