### ISSUE TITLE
input 在使用 model双向绑定时无法更新或延迟更新

### ISSUE THREAD

**Issue by Deanllv** [vuejs/vue#6230]
### Version
2.4.2

### Reproduction link
[https://github.com/Deanllv/vueTest.git](https://github.com/Deanllv/vueTest.git)

### Steps to reproduce
项目可以直接运行
这次提交包含至少 2个问题
主要区别在与vue1的差别和兼容性上

其中使用了 第三方非Vue组件的第三方日历库
其中vue库引用 自身项目中 lib 中的vue1/2 min(应该是min,尝试过使用CDN的2.4.2问题依旧出现且结果相同)

重现步骤:
1.git项目中存在比对截图,以及编好号的重现流程及效果

出现的问题:
1.在Vue1中可以使用js特性在不声明对象下属性的情况下完成效果,而在vue2中不声明不报错但是无法实现即时的双向绑定(截图中 下方输入框呈现的内容 vue1 vue2 vue2init 效果都不相同)

2.在vue2中无法使用第三方库对数据框赋值来改变 vue对象中的值

### What is expected?
问题1:
在Vue2中可以不声明属性,只声明vue绑定对象以及旗下一层的子对象,不用声明子对象中的属性

问题2:
提高兼容性可以使用第三方库并改变vue属性中的变量

### What is actually happening?
问题1:
在vue2中,如果不提前声明属性,则无法使用双向绑定

问题2:
控件赋值无法赋给属性,只停留在输入框中

---
实际应用项目为 vue1 升级 vue2
在vue1 中被其强大的兼容性以及易用性折服

在vue1升级vue2的过程中出现大量代码差异,改起来比较费劲,但是上述两个问题基本使这次升级失败
在我们项目使用中 存在大量,只声明1级绑定对象以及其下2级对象,不声明2级对象下的属性,在使用时也只使用2级对象下的属性 例如 v-model="test.test1"

声明时 例如这样
vueData={
   "test":{}
}
这样在使用时完全不用声明属性,且会在运行时被自动创建并正常使用
这种用法使用方便而且避免了很多麻烦,而且这样即使一个几十个对象的长页面(后台修改编辑所用的页面),也只需要声明很少一部分即可使用
在初期升级vue2 的时候 如果不声明一级对象则会报错(vue1中完全可以不声明1级属性),后期发现不声明属性也无法正常使用
即上述问题

这种用法是我们觉得在代码开发中最省事的一种,大大减少了一个页面的开发时间,以及大大增加了容错率
非常惊艳vue可以这么使用,而且这种用法在不确定参数属性时尤其好用,尤其是例如弹窗封装库等不能确定子对象的方式

所以希望在vue2中保留这个用法.

日期控件完全是改完时才发现的问题,input的value改变但是属性未改变,希望能提升兼容性,同样也是为了减少开发量和更改量

期待回复,谢谢
如有疑问可联系
wangyan@choc-ya.com
或
woderpg@sina.com
或
qq:275433288 (请备注)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Your repo is way too big...
If you ever find out it's a real bug and you can boil it down using a smaller template (like http://jsfiddle.net/posva/wsr78d2w/) i can take a look

**Comment by Deanllv** [comment]
This is a question about vue1 and vue2 differences

This is not a problem but a number of questions

You said he was too big to see, I can not accept it

I can not use a shorter text to explain the problem

Thanks
