### ISSUE TITLE
Vue filter error

### ISSUE THREAD

**Issue by ttquoccuong** [vuejs/vue#6233]
### Version
2.3.4

### Reproduction link
[https://codepen.io/ttquoccuong/pen/LjVgvL](https://codepen.io/ttquoccuong/pen/LjVgvL)

### Steps to reproduce
on this codepen, please open commened html. the error's appear and Vue broken.

### What is expected?
Please fix it.

### What is actually happening?
The error "function is not defined" will appear when i use Vue filter in v-text. i tested v2.1.8 - v2.4.2 the all get error

**Comment by LinusBorg** [comment]
This is expected. You can't use filters in Vue directives. This will not change.

**Comment by sqal** [comment]
https://vuejs.org/v2/guide/syntax.html#Filters

> Vue 2.x filters can only be used inside mustache interpolations and v-bind expressions (the latter supported in 2.1.0+), because filters are primarily designed for text transformation purposes. For more complex data transforms in other directives, you should use Computed properties instead.

you can use method instead:

`<div v-text="test(message)">`

or 

`:text-content.prop="test(message)"`
