### ISSUE TITLE
Bound property on input field type date reset when using setInterval.

### ISSUE THREAD

**Issue by nickels** [vuejs/vue#6236]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/nickels/w1a31fmz/2/](https://jsfiddle.net/nickels/w1a31fmz/2/)

### Steps to reproduce
Please see the fiddle using chrome.

### What is expected?
I expect the bound property not to be reset.

### What is actually happening?
The bound property for a input (type date) is reset when using setInterval.

**Comment by gebilaoxiong** [comment]
see: https://jsfiddle.net/w1a31fmz/3/

**Comment by nickels** [comment]
Ah I see.  I was doing that dynamically so I needed to use Vue.set(target, key, value), instead of particpants.push({'date': ''}). Thank you for your time.
