### ISSUE TITLE
Allow adjusting the width of v-navigation-drawer

### ISSUE THREAD

**Issue by jjpe** [vuejs/vue#6237]
### What problem does this feature solve?
At the moment, the v-navigation-drawer API itself seems to have no way to adjust the width.
The reason for the request is that It's kind of possible to adjust the width by hand at the moment (and even have it react to data changes by binding it to data), but then on small screens the menu does not open and close properly.

It would be very useful to have this feature in the API and have it "Just Work" like the rest of Vue.JS. 

### What does the proposed API look like?
I'm thinking of a simple reactive width property for v-navigation-drawer that does all it needs to behind the screens.

**Comment by posva** [comment]
I think you're on the wrong repository 😄
