### ISSUE TITLE
router 动态 view

### ISSUE THREAD

**Issue by guohuihot** [vuejs/vue#6239]
vue有动态组件 `<component :is="currentView"></component>`

但是当它和router组合时，
```
<router-view></router-view>
```
对应一个
```
<component :is="currentView"></component>
```
再对应具体的组件，这个嵌套层太多
```
<xxx></xxx>
```
我是想如果可以动态`router-view`的话
就可以这样
```
<router-view :is="currentView"></router-view>
```
再对应具体的组件，这样可以少嵌套一层，整个思路就清晰多了
```
<xxx></xxx>
```

**Comment by guohuihot** [comment]
瞬间关闭你是怎么做到的？？？

**Comment by jkzing** [comment]
因为你应该遵守提issue的规则...[issue-reporting-guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines)，这种用法问题请到[forum.vuejs.org](forum.vuejs.org)提问。

---

你的这个问题不是嵌套路由解决的吗...[https://router.vuejs.org/en/essentials/nested-routes.html](https://router.vuejs.org/en/essentials/nested-routes.html)

**Comment by guohuihot** [comment]
这是一个想法，怎么给例子

或者我需要的功能是这样的

```
<div id="app">
  <router-view></router-view>
</div>
```

```
const router = new VueRouter({
  routes: [
    { 
          path: '/user/:id', 
         component: User
    }
  ]
})
```
router-view 怎么才能具有 component 的特性
e.g. component slot currentView
