### ISSUE TITLE
@wheel event does not have delta values

### ISSUE THREAD

**Issue by greenpdx** [vuejs/vue#6240]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/49856/](https://jsfiddle.net/50wL7mdz/49856/)

### Steps to reproduce
  <div  @wheel="onWheel($event)">
    <p>{{ message }}</p><br>
  </div>

  method: {
  	onWheel (evt) {
     console.log(evt)
    }
}

### What is expected?
wheel { target: <input>, deltax: 999, deltay: 999, deltaz: 999}

### What is actually happening?
wheel { target: <input>, buttons: 0, clientX: 226, clientY: 574, layerX: 226, layerY: 574 }

**Comment by greenpdx** [comment]
<div  @wheel="onWheel($event)">
    <p>{{ message }}</p><br>
  </div>

**Comment by greenpdx** [comment]
@wheel="onWheel($event)

**Comment by nickmessing** [comment]
Stop adding comments, you can edit original post, in your jsfiddle you should have `methods` instead of `method`, works as expected [here](https://jsfiddle.net/50wL7mdz/49856/)
