### ISSUE TITLE
Sync Modifier support object properties

### ISSUE THREAD

**Issue by altjz** [vuejs/vue#6241]
### What problem does this feature solve?
Sync Modifier support object properties. 
For example, I have a myObj object, it has a foo and a bar property.
```javascript
myObj: {
  foo: 'foo',
  bar: 'bar'
}
```
This feature could use `update:myObj.foo` and `update:myObj.bar` to update the value.
```javascript
this.$emit('update:myObj.foo', 'new-foo');
this.$emit('update:myObj.bar', 'new-bar');
```

### What does the proposed API look like?
Currently, I need to use below format
```html
<MyComponent :foo.sync="myObj.foo" :bar.sync="myObj.bar"></MyComponent>
```
```javascript
props: ['foo', 'bar']
...
this.$emit('update:foo', 'new-foo');
this.$emit('update:bar', 'new-bar');
```
But with this new feature:
```html
<MyComponent :myObj.sync="myObj"></MyComponent>
```
```javascript
props: ['myObj']
...
this.$emit('update:myObj.foo', 'new-foo');
this.$emit('update:myObj.bar', 'new-bar');
```
It becomes more simple and clear, especially when the object has many properties.

**Comment by javoski** [comment]
You can use `v-bind` without directive arguments:
```html
<MyComponent v-bind="myObj"></MyComponent>
...
props: ['foo', 'bar']
...
```

**Comment by altjz** [comment]
@javoski it seems more clear than before. So I can use like below code, right?
```javascript
this.$emit('update:foo', 'new-foo');
this.$emit('update:bar', 'new-bar');
```
but why not just `myObj.foo`? Especially the object has many properties.

**Comment by yyx990803** [comment]
Although I can see the point of this proposal, I don't feel that it's particularly needed. In some way it encourages passing multiple values in an object to avoid having to specify multiple props. It is very easy to abuse object props by tucking more and more properties into it, making it some sort of "super prop". However, I think having an explicit list of props makes your component's interface easier to understand.

**Comment by jackchoumine** [comment]
> 
> 
> You can use `v-bind` without directive arguments:
> 
> ```
> <MyComponent v-bind="myObj"></MyComponent>
> ...
> props: ['foo', 'bar']
> ...
> ```

using `sync` with an object  work well.
```html
<child :my-obj.sync = "myObj"/>
```
`myObj` take more than two key.
inner child 
```js
this.$emit("update:myObj",newObj)
```
who is more harder to understand? who is better? why?

**Comment by taha-mv** [comment]
> > You can use `v-bind` without directive arguments:
> > ```
> > <MyComponent v-bind="myObj"></MyComponent>
> > ...
> > props: ['foo', 'bar']
> > ...
> > ```
> 
> using `sync` with an object work well.
> 
> ```
> <child :my-obj.sync = "myObj"/>
> ```
> 
> `myObj` take more than two key.
> inner child
> 
> ```js
> this.$emit("update:myObj",newObj)
> ```
> 
> who is more harder to understand? who is better? why?

THis is great! works like a charm!
