### ISSUE TITLE
对于自定义组件的slot和v-for问题

### ISSUE THREAD

**Issue by xygahs0801** [vuejs/vue#6242]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/liuwei2017/s0rv4tba/](https://jsfiddle.net/liuwei2017/s0rv4tba/)

### Steps to reproduce
在v-for中使用了slot后，出现异常，具体表现为点击星星的图标，评分无反映或者分数不正常

### What is expected?
可以正确的显示评分

### What is actually happening?
评分无反映或者分数不正确

---
我这里有一个没有使用slot的版本，可以看到，是正确的https://jsfiddle.net/liuwei2017/4xh481cz/
不知道为什么？？
是我使用的问题还是vue的bug？

**Comment by posva** [comment]
This is working as intended: a slot with a name can only appear once (look at the console)
What you need to use is scoped slots (https://vuejs.org/v2/guide/components.html#Scoped-Slots) or pass down 2 components or render functions
