### ISSUE TITLE
Vue is not detected when JSP is loaded through struts

### ISSUE THREAD

**Issue by phanikiran** [vuejs/vue#6245]
### Version
2.4.0

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Steps to reproduce
```
<!DOCTYPE html>
 <html lang >
  <head>
         <script src="vue.min.js"></script>
  </head>
  <body>
    Sample heading
    <div class="container" id="mainDiv"> {{firstName}} </div>
  </body>
    <script type="text/javascript">

        Vue.config.devtools = true;

        var app = new Vue({
          el: '#mainDiv',
          data: {
            firstName: 'name',
            lastName: 'lName',
            description: 'desc'
          }
        });
    </script>
</html>
```

### What is expected?
The following options are tried :

    If the above file is executed using .html, it works as expected. Chrome Dev tools detects that its a Vue application
    If the above file is executed using .jsp, it works as expected. Chrome Dev tools detects that its a Vue application(http://localhost:8080/example.jsp)
    If the above file is executed using .jsp and the jsp is loaded through form submission like http://localhost:8080/example.do and the success is redirected to example.jsp, it doesn't work.

Output in case 1 and 2 :

Sample heading
name

### What is actually happening?
Output in case 3 :

Sample heading. 

---

    1. Ideally its supposed to display "name" as well.
    2. If we do inspect element, it shows "".
    3. In inspect element, If I select "app.firstName" I am able to see the value "name"
    4. lets say, if I add "<component ref='container' :is='something'></component>", Vue is still unable to display component's template. If I do app.$ref -- {} in case 3 and app.$ref -- {container:...} in case 1 and 2 

_vnode seems to be undefined and when we do inspect element and select "app" / Vue all its functions are visible. Vue is not registered. 

Have also tried using timeout function of one second delay for making sure if there are any aysnc problems.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
