### ISSUE TITLE
建议：模板或者绑定语法

### ISSUE THREAD

**Issue by kangning1206** [vuejs/vue#6247]
### What problem does this feature solve?
1. <comp some-prop="1"></comp> 传递类型是字符串；
2. <comp v-bind:some-prop="1"></comp> 传递的是number;

是否可以考虑类似react jsx 语法，遇到`{}` 中的按照js处理，这样{1}与{'1'}在数据类型上一目了然；

### What does the proposed API look like?
1. <comp some-prop={'1'}></comp> or   <comp some-prop="1"></comp> 
2. <comp v-bind:some-prop={1}></comp>

**Comment by yyx990803** [comment]
1. `<comp :some-prop="1">` vs. `<comp some-prop="1">` 分不清楚么？
2. 作为一个稳定版本，现阶段不可能随便引入这样的改动。
