### ISSUE TITLE
when i update vue to 2.4.2, got some errors

### ISSUE THREAD

**Issue by xiaogaofudao** [vuejs/vue#6248]
![tim 20170729102149](https://user-images.githubusercontent.com/9261849/28741403-f9c4ae98-7447-11e7-895f-474b844a6aa9.png)

need your help

**Comment by yyx990803** [comment]
Please read the warning message. It's telling you about a possible mistake that were not checked before.

**Comment by xiaogaofudao** [comment]
thanks, i found the problem that caused by a picker components from mint-ui.
https://github.com/ElemeFE/mint-ui/issues/1000
for more information
