### ISSUE TITLE
Null propagation for view model binding

### ISSUE THREAD

**Issue by kedrzu** [vuejs/vue#6250]
### What problem does this feature solve?
Decreases amount of bloat code like null checking for nested properties.

For example I need to bind to value `currentPage.name`, but it's ok for `currentPage` to be null. 

Now I need to introduce additional prop in my view model to return `currentPage ? currentPage.name : null` or write the same code in view.

### What does the proposed API look like?
It could look like null propagation in C#6, ie: `{{ currentPage?.name }}`.

All null checks would be done behind the scenes in compiled render function.

**Comment by nickmessing** [comment]
It's not likely for Vue to add aditional non-javascript syntax and [optional chaining](https://github.com/tc39/proposal-optional-chaining) is just in stage 1 so I don't think it can be considered yet.

**Comment by LinusBorg** [comment]
This is currenly a stage 1 proposal for ecmascript, actually: 

https://github.com/tc39/proposal-optional-chaining/blob/master/README.md

Similar functionality has been requested in the past, and out stance on this is this: 

* we will not extend temp late expressions witch non JavaScript syntax
* in case of a helper method that achieves this, there are already a multitude of options available like lodash's `get`.
* we will not add functionality to core that has been solved better by other libs already. 

So my advice would be to use lodash's `get` or sum thing similar and add it as a prototype helper or a filter to your instances.
