### ISSUE TITLE
Binding on undefined property produces unexpected results

### ISSUE THREAD

**Issue by kichik** [vuejs/vue#6258]
### Version
2.4.2

### Reproduction link
[https://codepen.io/anon/pen/QMyYVr](https://codepen.io/anon/pen/QMyYVr)

### Steps to reproduce
1. Define an object in `data` with one property (e.g. `data () { return { hello: { world: 'world' } } }`)
1. Create two `<input>` tags one bound on an existing property (e.g. `v-model="hello.world"`) and one on an undefined property (e.g. `v-model="hello.foo"`)
1. For easier debugging add your data to the template (e.g. `{{hello}}`)
1. Run in the browser and edit the text boxes
1. Notice that changing the box tied to the undefined property doesn't update the data until the box tied to the defined property is changed

### What is expected?
I expected changing both text boxes to immediately modify the data. Either that or a warning or an error in the console telling me binding to an undefined property is not allowed.

### What is actually happening?
Only changing the text box tied to the defined property modifies the data immediately. Changing the text box tied to the undefined property does nothing until the other text box is changed.

**Comment by nickmessing** [comment]
That is expected behaviour. `v-model` is just a syntactic sugar over `:value="hello.foo" @input="hello.foo = $event.target.value` so when you do `hello.foo = 'something'` and `hello.foo` is not a [reactive](vuejs.org/v2/guide/reactivity.html) property - vue doesn't know that something changed and doesn't render the component. That is a known [caveat](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) and there is no way around it. That is why Vue requires declaring all the data in `data` property of the component.

**Comment by kichik** [comment]
It would be really useful if there could be a warning in the console for that. I just wasted a few hours tracking this down while learning Vue.js.

**Comment by nickmessing** [comment]
@kichik, while we can track root-level methods/props that are used in template but not declared - we cannot do the same with nested ones (`v-model="foo"` triggers and error, `v-model="existingObject.foo"` doesn't) and there is no way of doing that in current reactivity system, when Vue will drop support for Internet Explorer and change to `Proxy` for reactivity - that will be possible. That is exactly why we have a specific [caveat](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) information in official tutorial.

**Comment by kichik** [comment]
I'm not familiar with the reactivity system yet. But if there's a solution for non IE, it'd still be useful to have it enabled in non-production builds for other browsers.

**Comment by nickmessing** [comment]
@kichik, that solution is a complete rewrite for reactivity system :smile: it's not considered unless we drop IE support.

**Comment by kichik** [comment]
Too bad :(
Thanks for thoroughly explaining this!
