### ISSUE TITLE
ssr现在坑太多

### ISSUE THREAD

**Issue by SteveCruise** [vuejs/vue#6260]
### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0)

### Steps to reproduce
no

### What is expected?
no

### What is actually happening?
主要是第三方库的问题：

有的用了import，在node下报错（比如vue-awesome）；

有的用了window和document变量，同样在node下报错；

有的用了.vue文件，这个通过拷贝出来暂时可以解决（比如vue-awesome、vue-echarts）。

上面两个问题没法自己解决，不知道vue的ssr（vue-hackernews-2.0）能不能在设计上考虑兼容这些第三方库。

**Comment by gebilaoxiong** [comment]
你好，非常感谢你提交的issue

涉及第三方类库的问题，需要到对应的仓库提交。

**Comment by SteveCruise** [comment]
@gebilaoxiong 这么简单粗暴的？

**Comment by cyij** [comment]
@SteveCruise 请教个问题，为什么第三方库中使用import会报错，而本地代码（如src目录）中使用import不会报错呢？
谢谢～
