### ISSUE TITLE
Vuex two way data binding

### ISSUE THREAD

**Issue by DavideCarvalho** [vuejs/vue#6261]
### Version
2.4.2

### Reproduction link
[https://github.com/DavideCarvalho/VueIssue](https://github.com/DavideCarvalho/VueIssue)

### Steps to reproduce
Go to ```https://cliniclin.herokuapp.com/medicas```, click on ```https://cliniclin.herokuapp.com/medicas``` then change the value on the input, this should change the value on the row as well.

### What is expected?
I have a store property
```
novaMedica: {
    id: null,
    nome_medica: null,
    area_medica: null,
    login: null,
    senha: null
  }
```
and my payload comes like this
```
payload: {
    id: 1,
    nome_medica: Roberta,
    area_medica: Nutricao,
    login: 123,
    senha: 123
  }
```
I expected that on my mutation, if I write state.novaMedica = payload, this should only change my state

### What is actually happening?
It binds the state to the last thing that is using this value, in this case, the row on my table, so if I change the value on the input after clicking on ```editar```, the value on the row also changes

---
To see the problem running, go to ```https://cliniclin.herokuapp.com/medicas```, click on ```editar``` then change the value on the input, this way you can see that the row value also changes. On my github repo, the mutation that is changing the value has a comment of the workaround that i've found, but I don't think that this is a good thing to do, thinking that if I have a field with 20 properties, this will be a bothersome work

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by DavideCarvalho** [comment]
So isn't this considerated a bug?

**Comment by posva** [comment]
No, because you shared your whole project and asked for help. There's no vuex two way binding. Furthermore, this is the vue repo, not vuex. If you want to report a bug, you need to send a concise reproduction
So, please, ask for help on any of the other channels I pointed you below and come back if it turns to be a bug, thanks!
