### ISSUE TITLE
Lazy slot loading?

### ISSUE THREAD

**Issue by jackysee** [vuejs/vue#6262]
### What problem does this feature solve?
Only render the slot when it will be rendered in the child context. Now it will render in parent first and then pass into child. For example:

Parent template
```
<child :target="obj">
    {{obj.name}}
</child>
```

Child template
```
<div>
   <div v-if="target === null"> 
        loading.... 
    </div>
   <div v-else>
        <slot></slot>
   </div>
</div>
```

This would result in exception if `obj` is null, as the parent is rendered first.

### What does the proposed API look like?
Maybe a lazy attribute at the slot?
```
    <slot lazy></slot>
```

**Comment by posva** [comment]
Unfortunately, it has to be rendered in the parent because the context it gets access to is different
