### ISSUE TITLE
input type="number" keyboard input does not work with Microsoft Edge

### ISSUE THREAD

**Issue by RobertBColton** [vuejs/vue#6264]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/50808/](https://jsfiddle.net/50wL7mdz/50808/)

### Steps to reproduce
Simply create a number input and use the up and down arrow keys on it in Microsoft Edge browser. v-model will not update the bidirectional value.

### What is expected?
The value on the Vue component/instance would be updated by the up/down arrow keys as it is in Chrome and Firefox.

### What is actually happening?
The value is not updated.

**Comment by jkzing** [comment]
This is likely an issue of MS Edge itself, and has nothing to do with vue.
Remove vue dependency, and you will get same behavior in Edge:
[https://jsfiddle.net/jingkaizhao/50wL7mdz/50817/](https://jsfiddle.net/jingkaizhao/50wL7mdz/50817/)

**Comment by RobertBColton** [comment]
Thanks, I can confirm your vue-less fiddle works in Firefox/Chrome but not Edge.

**Comment by posva** [comment]
Closing then 🙂

**Comment by RobertBColton** [comment]
Awesome, also it seems like this is already filed as a bug on Edge, didn't find it earlier because it was a little hard to search for.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10242461/

Cool beans!

**Comment by RobertBColton** [comment]
For further reference, a similar issue remains open on the AngularJS tracker as well:
https://github.com/angular/angular.js/issues/15366

**Comment by kimchristiansen** [comment]
Another workaround would be vue-autonumeric: https://www.npmjs.com/package/vue-autonumeric
