### ISSUE TITLE
My Canvas cannot be update

### ISSUE THREAD

**Issue by ascrutae** [vuejs/vue#6265]
Hi everybody:

I'm new for Vue, I want to draw picture by VueJS and found my canvas cannot be update when I 
remove the data.

Here is my example
[http://jsfiddle.net/ascrutae/6n4s4uan](http://jsfiddle.net/ascrutae/6n4s4uan)

Thanks

xin

**Comment by simplesmiler** [comment]
This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [discord](https://vue-land.js.org/). We try to use the issue tracker for bug reports and feature requests.

As for the question, you need to key your items: http://jsfiddle.net/6n4s4uan/5/

**Comment by javoski** [comment]
I think your demo just worked as expected.

**Comment by ascrutae** [comment]
Thanks for your response.
