### ISSUE TITLE
Error render client side dynamic component

### ISSUE THREAD

**Issue by wargt** [vuejs/vue#6268]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/50977/](https://jsfiddle.net/50wL7mdz/50977/)

### Steps to reproduce
in link reproduction - worked

I think not working on me because i use webpack - i dont now

I use nuxt js 

on server side - this good worked, but on the client-side i have error 

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

### What is expected?
i want no errors

### What is actually happening?
I have error and in browser not rendered myComponent

**Comment by nickmessing** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [official chat](http://chat.vuejs.org/), or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by wargt** [comment]
close
i found fix

in webpack config

resolve: {
    alias: {
        vue: 'vue/dist/vue.js'
    }
}
