### ISSUE TITLE
twitter、facebook、ins等embed  code出现的问题

### ISSUE THREAD

**Issue by liujinyang1994** [vuejs/vue#6271]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/51064/](https://jsfiddle.net/50wL7mdz/51064/)

### Steps to reproduce
我的情况是这样的。
数据内容是HTML，里面包含着twitter、facebook 、youtube等社交网站的embed code。

### What is expected?
可以显示twitter正常的样式。

### What is actually happening?
现在的情况是实现不全，查看网络，对应的js也没有加载。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The result is exactly the same with or without Vue...
