### ISSUE TITLE
Built-In Component component's prop IS can not receive async component factory function

### ISSUE THREAD

**Issue by changchengqin** [vuejs/vue#6272]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1.Use Built-in Component : component
2.Set an asynchronous component factory function for its is attribute

### What is expected?
doesn't render async component

### What is actually happening?
render async component normally

**Comment by posva** [comment]
It does work: https://jsfiddle.net/bn6904gz/
