### ISSUE TITLE
v-if breaks dependent selects logic

### ISSUE THREAD

**Issue by narek-t** [vuejs/vue#6276]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/8tvLvexL/3/](https://jsfiddle.net/8tvLvexL/3/)

### Steps to reproduce
Click Toggle !pickup and try to change District select and you'll see issue. You can also delete div with v-if="!cartPage.pickup" or change v-if to v-show, and you can see, everything is working..

### What is expected?
simple dependent selects logic. 3 select elements based on each other value.

### What is actually happening?
logic breaks.
It looks like some caching issue, because you can change problematic select.custom-select location in DOM, and it works! 
[https://jsfiddle.net/8tvLvexL/4/](https://jsfiddle.net/8tvLvexL/4/)

**Comment by LinusBorg** [comment]
Can you be a little bit more explicit about what *should* be happening? considering that v-ifs are supposed to show/ hide some stuff naturally and there's no errosrs, I'm forced to play detective to understand what part of the behaviour is intended and what is not.

**Comment by narek-t** [comment]
@LinusBorg Thank you for helping!
I recorded a video to make issue more clear.
Here is issue [http://take.ms/lVAFe](http://take.ms/lVAFe)
And if you open [jsfiddle link](https://jsfiddle.net/8tvLvexL/3/) you'll see the same. 
But if you open [another jsfiddle link](https://jsfiddle.net/8tvLvexL/4/) you'll se that everything is working fine, but I only changed `select.custom-select` location, nothing else [http://take.ms/J9hoN](screenshot)

**Comment by LinusBorg** [comment]
Ok I *think* I understand what you mean.

You probably should be keying the different elements, following this advice:

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

**Comment by narek-t** [comment]
Ok, this solves issue.
Thank you and all your team for great work and great framework!
