### ISSUE TITLE
[SSR]client side hydration mismatching : vdom generated some useless text vnode

### ISSUE THREAD

**Issue by etoah** [vuejs/vue#6278]
### Version
2.4.2

### Reproduction link
[https://codepen.io/etoah/pen/eEdGQV?editors=1010](https://codepen.io/etoah/pen/eEdGQV?editors=1010)

### Steps to reproduce
As shown in the codeopen case,

I wrote my own vue  ssr runtime(represent it in a static file in case) and still use vue  on the client, but when the if expression false,  dom will generate some useless text vnode , lead to [Mismatching childNodes vs. VNodes] warn.

when  `<li v-if="s"></li>` is removed , the program works.

### What is expected?
vdom no longer produces unwanted text tag vnode.

### What is actually happening?
vdom created useless text tag vnode.

![image](https://user-images.githubusercontent.com/7630567/28911894-a5724d20-7864-11e7-8613-4bfcc8a53aec.png)

**Comment by LinusBorg** [comment]
> I wrote my own vue ssr runtime

Then you should make sure that it behaves like Vue does.

In this case, you are using the unminified version of vue, which will render a comment node as a placeholder for elements that are currently not displayed.

This doesn't happen in production with the minified version, though. Your codepen can befixed by simply using
```html
<script src="https://unpkg.com/vue/dist/vue.min.js"></script>
```

If your renderer produces output different from what Vue would, then that's an issue to fix with your own renderer.

**Comment by nwallis** [comment]
Is that because it is fixed or because the production version silently re renders the entire application if there is a mismatch?
