### ISSUE TITLE
@click.native not work in 2.4.2

### ISSUE THREAD

**Issue by Intiligent** [vuejs/vue#6281]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/Intiligent89/0y64c3x6/4/](https://jsfiddle.net/Intiligent89/0y64c3x6/4/)

### Steps to reproduce
my code for example:
```
<ul class="tm-order-good-list" v-if="$store.state.goodList.items.length > 0">
    <li v-for="row in $store.state.goodList.items" :key="row.id" @click.native="onGoodSelect($event, row)">
        <div class="tm-photo"><img :src="row.img" :alt="row.title"></div>
        <div class="">
            <div class="tm-title">{{row.title}}</div>
            <div class="tm-code">{{row.code}}</div>
            <div class="tm-price">{{row.price}}</div>
        </div>
    </li>
</ul>
```

### What is expected?
expected get nativce event

### What is actually happening?
by click on `li` not generate event (None at all, even MouseEvent)
if remove `.native` we get event

**Comment by LinusBorg** [comment]
the `.native` modifier is only available (and only necessary) on components, not native elements,

**Comment by jameshulse** [comment]
I just ran in to this issue when copy pasting an event from a component to a native element. I think at the least there should be a warning generated when the `.native` modifier is used on a native element.

**Comment by olsonpm** [comment]
Yeah I've ran into this more than a few times when copy/pasting the click logic.  A warning would be nice, though admittedly a quick google leads me to the solution.
