### ISSUE TITLE
Better Error Message for v-for typo

### ISSUE THREAD

**Issue by stevekrouse** [vuejs/vue#6283]
### What problem does this feature solve?
I recently made an annoying mistake putting a colon in front of my v-for (:v-for="...") because I'm used to doing that as a v-bind shorthand. The error message complained about not recognizing the iteration variables which was super confusing because I expected the v-for to create those variables for me. 

### What does the proposed API look like?
Clearly, Vue was trying to interpolate the expression as a regular v-bind, when I think it should throw an error: "Please remove the colon before your v-for. You only need colons for v-binds."

**Comment by posva** [comment]
I think this is going way too far... There're tons of possible typos, if we accept handling one, we'll have to handle much more in the future.
Writing `:v-for` is the same as writing `v-bind:v-for` and nothing prevents the user from having a property called `vFor` in its `data` to make that binding valid
BTW the colon is the way to add arguments for directives

**Comment by posva** [comment]
This could be handled as a rule with eslint, though
