### ISSUE TITLE
Reactive Vue.delete equivalent for objects

### ISSUE THREAD

**Issue by OmerZfira** [vuejs/vue#6285]
### What problem does this feature solve?
Although it is not documented in the release notes for 2.2.0 and was only edited in the Docs 2 weeks ago (commit 
 bffedab6d824cc7983856b6f286e69f0d818c3a7) Vue.delete does not work anymore (since 2.2.0) on objects.
When I need to add/remove an item from an array it is as simple as using push/splice.
When I need to manipulate an object I have only Vue.set() to reactively add, but delete doesn't seem to have any built-in reactive solution.

If there's a built-in way of doing that I would like to know, if not - is it possible to implement one?

### What does the proposed API look like?
I'm not sure about the code, but an API which implements the javascript built-in delete operator (while maintaining reactivity) would be excellent.

**Comment by posva** [comment]
I'm not sure to understand, `Vue.delete` works with objects...

**Comment by sirlancelot** [comment]
When you use `Vue.delete` on the property of an object, you are telling Vue that you no longer wish to have reactivity on the property you are deleting. It's basically the same as the `delete` keyword. To bring back reactivity to that deleted property, you will need to use `Vue.set`.

If you want to delete an object property but still wish for it to remain reactive without needing to use `Vue.set`, try just setting the property to `null` or `undefined` instead.

**Comment by OmerZfira** [comment]
I lost reactivity when I used  Vue.delete, and when I checked the [API docs for Vue.delete](https://vuejs.org/v2/api/#Vue-delete) it says that Vue.delete works only for arrays:

> Vue.delete( target, key )
> 
> Arguments:
> 
> {Object | Array} target
> {string | number} key/index
> Only works with Array + index in 2.2.0+.

But if you guys say there's a mistake in the docs then there must have been another problem with my code that caused the issue, I will look into it again.

Thank you for the replies.

**Comment by nickmessing** [comment]
@OmerZfira, docs sat that **Array + index** is supported only starting with **2.2.0+**, what do you mean "I lost reactivity"? `Vue.delete` - deletes the property so it's no longer there, a property cannot be reactive if it doesn't exist.

If you do something like:
```js
Vue.delete(this.obj, 'key')
this.obj.key = 'something'
```
It is supposed to not work, `Vue.delete` reactively removes the property, but that property cannot be reactive after that since it doesn't exist.

**Comment by nickmessing** [comment]
By the way, since github issues are only for issues and not for questions I'll close this. You can ask questions on the [forum](http://forum.vuejs.org/), the [chat](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by dkjain** [comment]
@sirlancelot 
> If you want to delete an object property but still wish for it to remain reactive without needing to use `Vue.set`, try just setting the property to `null` or `undefined` instead.

What do you imply by `delete an object property but still wish for it to remain reactive` do you mean remove the value of the property or remove the property itself (`key` and `value`). Can you please give an example. 

Thanks
