### ISSUE TITLE
$index equivalent in Vue2

### ISSUE THREAD

**Issue by Flame2057** [vuejs/vue#6286]
### What problem does this feature solve?
Distinguishing elements that are generated from a list; useful for when an element is associated with a item in an array, so you can directly modify that list element from within a directive on that element.

### What does the proposed API look like?
an $index variable will be available within directives in elements generated from a list

**Comment by sirlancelot** [comment]
`<li v-for="(item, index) in listOfThings">`

https://vuejs.org/v2/guide/list.html#Basic-Usage

**Comment by ktsn** [comment]
As @sirlancelot described, you can declare it in `v-for` expression.
