### ISSUE TITLE
Iterating over list not working? 

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue#6288]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/51521/](https://jsfiddle.net/50wL7mdz/51521/)

### Steps to reproduce
This fiddle works: https://jsfiddle.net/50wL7mdz/51512/

But this one doesn't: https://jsfiddle.net/50wL7mdz/51521/

### What is expected?
I expect the second fiddle to show text on both sides of the `+` symbols similar to the first fiddle.

### What is actually happening?
Data is not being displayed, in the second fiddle.

---
Why might this be happening? Did I do something wrong in the second one? Perhaps Bootstrap code is messing it up?

**Comment by jkzing** [comment]
You just missed `{{country.name}} + {{country.code}}` in your `v-for`...

**Comment by javoski** [comment]
The second demo just works as expected too.

<img width="722" alt="2017-08-04 11 24 14" src="https://user-images.githubusercontent.com/5391892/28953000-b068189c-7907-11e7-9dc6-58e1da8ffb58.png">

As you can see, there is only a plus sign inside the template.

**Comment by trusktr** [comment]
I do have `{{country.name}} +{{country.code}}` in my code editor. Turns out I didn't realize the server-side Handlebars was interpolating it so the template code never made it to the client. In the fiddle I had pasted the view-source of the result without realizing. Thanks and sorry for wasting your time guys! - Joe
