### ISSUE TITLE
this.$props undefined within <template v-for="">

### ISSUE THREAD

**Issue by rohitpaulk** [vuejs/vue#6289]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/wdfyh9mm/1/](https://jsfiddle.net/wdfyh9mm/1/)

### Steps to reproduce
When using `<template>` with `v-for`, `this.$props` ends up undefined. 

```
const app = new Vue({
  el: '#app',
  props: {
    tasks: { default: function() { return [1, 2, 3]; } }
  },
  template: `
  	<div>
            Using this.$props outside 'template' works: {{ this.$props.tasks }} <br/>
            <template v-for="task in tasks">
              This doesn't: {{ this.$props.tasks }}
            </template>
        </div>
  `,
})
```

### What is expected?
I'd expect `this.$props.tasks` to be the same within and outside the `<template>` tag. 

### What is actually happening?
`this.$props` is undefined. 

---
I tried a few variations - using `v-if` on the `<template>` doesn't trigger this.

**Comment by andyklimczak** [comment]
try just `$props.tasks`

`this` is implied in templates, similar to how you use `data`

**Comment by rohitpaulk** [comment]
> this is implied in templates, similar to how you use a component's data

Gotcha. This is a whittled-down example, definitely not a kosher use case. I set it up like this specifically to highlight that fact that `this` is bound to the parent outside the `template` tag, but not inside. 

Is there a reason for `this` to not be bound to the parent within a `template` tag too? It just seemed non-intuitive to me, thought it's worth an ask :)

**Comment by posva** [comment]
You shouldn't use `this` inside of the template
