### ISSUE TITLE
Failed to mount component when using non Single File Component(SFC) inside SFC

### ISSUE THREAD

**Issue by sngeth** [vuejs/vue#6291]
### Version
2.4.2

### Reproduction link
[https://github.com/sngeth/vue_test](https://github.com/sngeth/vue_test)

### Steps to reproduce
Ran vue init browserify vue_test
Used full build with compiler in setup options
Converted Hello.vue to Hello.js non SFC 
```js
import Vue from 'vue'

Vue.component('hello', {
  template: `
    <div id="hello">
      <h1>{{ msg }}</h1>
    </div>
  `,
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
})
```
Changed App.vue to use Hello.js component
```js
<template>
  <div id="app">
    <hello></hello>
  </div>
</template>

<script>
import Hello from './components/Hello.js'
export default {
  name: 'app',
  components: {
    Hello
  }
}
</script>
```
Run npm run dev and goto localhost:8080

### What is expected?
Expect application to render Hello component successfully

### What is actually happening?
[Vue warn]: Failed to mount component: template or render function not defined.

**Comment by coolzjy** [comment]
https://vuejs.org/v2/guide/components.html#Registration
https://vuejs.org/v2/guide/components.html#Local-Registration

**Comment by ktsn** [comment]
This is expected because you are overwriting global `hello` component with local `Hello` component that is not have any options. You can't get any data from `Hello.js` since you are not exporting any data in it.

If you want to use globally registered components, you should just execute the `Hello.js`.

```vue
<script>
import from './components/Hello.js'

export default {
  name: 'app'
}
</scriot>
```
