### ISSUE TITLE
npm run lint error with couldn't find the plugin "eslint-plugin-html"

### ISSUE THREAD

**Issue by shengxinjing** [vuejs/vue#6294]
### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
1. git clone vue repo and checkout dev branch
2. excute npm install
3 exccute npm run lint with error

### What is expected?
lint success

### What is actually happening?

```
ESLint couldn't find the plugin "eslint-plugin-html". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-html is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-html@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by posva** [comment]
that plugin should be installed when installing eslint-plugin-vue-libs
Make sure you have an updated version of npm then delete the node_modules and do `npm install` again

**Comment by shengxinjing** [comment]
@posva thanks , update npm from 2.10 to 3.11 and works fine

**Comment by posva** [comment]
You should update to npm@5 btw 😄
3 is still quite old

**Comment by shengxinjing** [comment]
@posva I reinstall nodejs stable version with 6.11 and npm with 3.x, should i update nodejs to 8.0?
 I am trying to read and hope to contribute the source code

**Comment by posva** [comment]
It was more a personal thing that anything else. I think that node 8 comes with some major improvements
