### ISSUE TITLE
errorHandler is not called for custom events inside components

### ISSUE THREAD

**Issue by lucasm-iRonin** [vuejs/vue#6296]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/hhw8z2wy/](https://jsfiddle.net/hhw8z2wy/)

### Steps to reproduce
Assign custom error handler to `Vue.config.errorHandler` and throw error inside any even handler method in the component.

### What is expected?
When event throws error it should call custom handler that was assigned to `Vue.config.errorHandler`

### What is actually happening?
It throws error on global window object bypassing the `Vue.config.errorHandler`

**Comment by posva** [comment]
This is expected more information at: https://vuejs.org/v2/api/#errorHandler
