### ISSUE TITLE
Initialize object properties when binding to controls, if not initialized yet.

### ISSUE THREAD

**Issue by unirgy** [vuejs/vue#6297]
### Version
2.4.2

### Reproduction link
[https://stackoverflow.com/questions/45516930/array-reactivity-issues/45517070#45517070](https://stackoverflow.com/questions/45516930/array-reactivity-issues/45517070#45517070)

### Steps to reproduce
Bind HTML controls to unintialized object properties

### What is expected?
object properties are initialized and bound to controls

### What is actually happening?
they are not bound

---
I understand now that object properties need to be initialized before binding to controls, but sometimes it is not possible to know all properties that will be used. It would be nice it binding controls to properties would initialize them first, if they are not initialized yet.

**Comment by yyx990803** [comment]
If you know you are binding to `row.cells` in your template, then you **already know what fields should be there**. We've discussed this before and unfortunately the current behavior won't change, because allowing templates to dictate the data structure breaks the single source of truth.
