### ISSUE TITLE
ie下表单绑定使用扫码枪问题

### ISSUE THREAD

**Issue by sixiakun** [vuejs/vue#6298]
### Version
2.4.2

### Reproduction link
[https://cn.vuejs.org/v2/guide/forms.html](https://cn.vuejs.org/v2/guide/forms.html)

### Steps to reproduce
使用了v-model的input输入框，在ie下面使用扫码枪，扫描到的条码不全，去除v-model或者加上.lazy修饰符就会没有该问题，但在chrome下一切正常

### What is expected?
希望能够修复这个问题，在ie下面使用扫码枪输入的也能得到正确的条码

### What is actually happening?
无

**Comment by yyx990803** [comment]
这... 跟硬件相关的问题，更多可能是 IE 的 bug 而不是 Vue 的问题... 建议你用 `.lazy`...

**Comment by sixiakun** [comment]
尤大，如果只是硬件我就不会提了，没加v-model的输入框是没事的，.lazy是可以，不过扫码完毕的回车事件时，还拿不到绑定的值，我只好在回车事件时再手工blur一下，或者有没有更好地修饰符推荐再或者我的打开方式不对？

**Comment by yyx990803** [comment]
主要是这涉及扫码驱动对不同浏览器的处理方式，如果要 Vue 来对这些特例做适配是不现实的。你在回车时间里 `nextTick`，或者干脆不要用 `v-model` 也可以。
