### ISSUE TITLE
Vue component not work as expect

### ISSUE THREAD

**Issue by maple3142** [vuejs/vue#6299]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/maple3142/kc4s9x1p/](https://jsfiddle.net/maple3142/kc4s9x1p/)

### Steps to reproduce
1. click on "first" text
2. click on "second" text
3. click on "first" text
4. click on "first" text

### What is expected?
after the forth step "second" and "third" should be showed

### What is actually happening?
only "second" appear

**Comment by yyx990803** [comment]
This is working as expected. `v-if` destroys and recreates the toggled slot content, so the second `spoiler` component is re-created.
