### ISSUE TITLE
Provide a Typescript declaration file for `vue-server-renderer/client-plugin`

### ISSUE THREAD

**Issue by foisonocean** [vuejs/vue#6301]
### What problem does this feature solve?
Please provide a declaration file, thanks.

**Comment by posva** [comment]
ping @ktsn @kazupon @HerringtonDarkholme

**Comment by ktsn** [comment]
I thought about that when I wrote `vue-server-renderer`'s typings but I'm not sure its necessity since it's used in a webpack config.
Do you write your webpack config in TypeScript?

**Comment by HerringtonDarkholme** [comment]
Hi @foisonocean 

Would you mind provide more information? As far as I know client-plugin is for webpack. And I don't think many users use TS for webpack setup. (client-plugin contains almost nothing other than a `new` signature).

Also, it seems adding `declare module 'vue-server-render'` does not work in our vue-server-render's `index.d.ts`.

**Comment by foisonocean** [comment]
Yes, I am using Typescript to write webpack config.

**Comment by xiuxingdeshandaiwang** [comment]
woo

**Comment by ktsn** [comment]
Oh, I didn't know that webpack officially supports a config file written in TypeScript 😮 
https://webpack.js.org/configuration/configuration-languages/#typescript

I'll create the declaration of `client-plugin` (and of `server-plugin`)
