### ISSUE TITLE
beforeMount() not work on ie

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue#6309]
### Version
2.4.2

### Reproduction link
[https://codepen.io/lasthrun/pen/WERLZJ](https://codepen.io/lasthrun/pen/WERLZJ)

### Steps to reproduce
open on ie edge, i fount the beforeMount() not work.
the error information show : it should be have ':'

### What is expected?
the method 'tableonload' should work and change the table layout.

### What is actually happening?
nothing happen

**Comment by jkzing** [comment]
Your code works just fine in MS Edge.

If you mean IE instead of MS Edge, you should change your code to:

``` js
{
  beforeMount: function () {
  }
}
```

**Comment by lasthrun** [comment]
THX, it work now.
