### ISSUE TITLE
may be a bug of twoWay directive

### ISSUE THREAD

**Issue by suemi994** [vuejs/vue#631]
When I define a twoWay directive and use set function in bind, there is an error 'can't read property set of undefined' , my code follows.

``` javascript
Vue.directive('tags',{
    twoWay:true,
    bind: function () {
        var self=this;
        console.log(self);
        $(self.el).on('itemAdded',function(){
             self.set($(this).val());
        });
    },

    unbind:function(){
        $(this.el).off();
    }
});
```

**Comment by EmaileriMikko** [comment]
@yyx990803 This still doesn't work.

See [here](https://jsfiddle.net/v2g9o9j6/) for an example without `update` and [here](https://jsfiddle.net/v2g9o9j6/1/) for a directive with `update` method.

**Comment by simplesmiler** [comment]
@EmaileriMikko in Vue 2 directives no longer have `this`.
https://vuejs.org/v2/guide/migration.html#Custom-Directives-simplified
