### ISSUE TITLE
Whitespace problem on Chrome/Windows (latest)

### ISSUE THREAD

**Issue by sgehrman** [vuejs/vue#6315]
### Version
2.4.2

### Reproduction link
https://tripping.tech/ 
card titles and other text have a single space in front

### Steps to reproduce
Seems to render fine on Edge and Firefox, but Chrome for Windows (latest) puts a space in front like this...
(spaces also appear on Chrome/Android)

```
<div>
     hello <strong>world</strong>
<div>
```
output on screen is " hello world" rather than "hello world"

### What is expected?
no space in front of hello

### What is actually happening?
space in front of hello

---
doesn't happen on codepan, not sure why.

**Comment by nickmessing** [comment]
@sgehrman, that's because you use Carriage Return and Line Feed characters (CRLF aka `\r\n`) for new line. You should use `\n` only in web.

**Comment by sgehrman** [comment]
Note to Atom users, default is CRLF.  Change setting to LF.
