### ISSUE TITLE
`IE9` SCRIPT5007: 无法获取未定义或 null 引用的属性“split”

### ISSUE THREAD

**Issue by fengyun2** [vuejs/vue#6318]
### Version
2.4.2

### Reproduction link
[https://github.com/ly2011/vue2-elm](https://github.com/ly2011/vue2-elm)

### Steps to reproduce
```
$ npm run dev
```

### What is expected?
Compatible with `IE9`.

### What is actually happening?
No error in `IE9`.

---
`IE9` only under the error.

The function and location of the error：

```
function getTransitionInfo (el, expectedType) {
  var styles = window.getComputedStyle(el);
  var transitionDelays = styles[transitionProp   'Delay'].split(', '); // 这里报错了
  var transitionDurations = styles[transitionProp   'Duration'].split(', ');
  var transitionTimeout = getTimeout(transitionDelays, transitionDurations);
  var animationDelays = styles[animationProp   'Delay'].split(', ');
  var animationDurations = styles[animationProp   'Duration'].split(', ');
  var animationTimeout = getTimeout(animationDelays, animationDurations);
}
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Aiyibooo** [comment]
你好，请问问题解决了吗？

**Comment by Aiyibooo** [comment]
另外我发现，只要加了 <transition>这个标签，就会出现这个错误。

**Comment by yyx990803** [comment]
> ### 重现应当尽量精简
> 有些用户会直接给我们一整个项目的代码，然后希望我们帮忙找出问题所在。此类请求我们通常不予接受，因为：
>
> 你对你的项目的代码结构可能已经非常熟悉，但我们并不是。阅读、运行、分析一个完全陌生的项目是极其耗费时间和精力的。
>
> 由于涉及了大量业务代码，问题可能是你的代码错误，而不是 Vue 的 bug 所导致的。
>
> 一个最小化的重现意味着它精确地定位了 bug 本身 - 它应当只包含能够触发 bug 的最少量的代码。你应当尽可能地剔除任何跟该 bug 无关的部分。

**Comment by SmileLifeIven** [comment]
这个原因应该使项目代码问题，这里可以加一个判断去解决

`var transitionDelay = styles[transitionProp + 'Delay']
  var transitionDuration = styles[transitionProp + 'Duration']
  var animationDelay = styles[animationProp + 'Delay'];
  var animationDuration = styles[animationProp + 'Duration'];
  var transitionDelays = transitionDelay ? transitionDelay.split(', ') : [];
  var transitionDurations = transitionDuration ? transitionDuration.split(', ') : [];
  var transitionTimeout = getTimeout(transitionDelays, transitionDurations);
  var animationDelays = animationDelay ? animationDelay.split(', ') : [];
  var animationDurations = animationDuration ? animationDuration.split(', ') : [];
  var animationTimeout = getTimeout(animationDelays, animationDurations);`
