### ISSUE TITLE
Vuejs Keyup event has probability not triggered

### ISSUE THREAD

**Issue by qiaochangwei** [vuejs/vue#6319]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/kcat/ghq8fmrk/4/](https://jsfiddle.net/kcat/ghq8fmrk/4/)

### Steps to reproduce
The scene is like this: six input, The last two input are disabled, enter 0, and then the tab key key is switched to the next,Cycle like this, The last input might appear differently than the input above,It seems like vuejs Keyup doesn't work,but the JavaScript Keyup can be executed,Chances are very small. You may have to try several more times before you show up

### What is expected?
Vuejs Keyup can be used as normal as JavaScript

### What is actually happening?
You should try it several times
The last 0 is not red, and vuejs Keyup does not trigger

**Comment by javoski** [comment]
When the tab key was down (not up yet), the current input element will lose its focus and jump to next.

**Comment by qiaochangwei** [comment]
Is it a bug? After all, the JavaScript Keyup event works
What am I going to do about it?

**Comment by qiaochangwei** [comment]
Is it a bug? After all, the JavaScript Keyup event works
What am I going to do about it? @javoski

**Comment by javoski** [comment]
The demo just worked as expected to me.
I'm not sure what you really want and I don't know what does "the JavaScript Keyup event works" means, maybe you can use `keydown` instead of `keyup`.
