### ISSUE TITLE
watch监听array对象时，数组长度被unshift改变时，返回的oldValue和newValue相同。是缺陷还是bug，会修复吗

### ISSUE THREAD

**Issue by zuank** [vuejs/vue#6324]
### Version
2.4.2

### Reproduction link
[https://zuank.github.io/notes/vue/watchValue.html](https://zuank.github.io/notes/vue/watchValue.html)

### Steps to reproduce
（测试地址要打开控制台看log）
万金油是规避这个bug的操作

### What is expected?
返回正确的oldValue

### What is actually happening?
oldValue和newValue相同 都是newValue的内容

---
这个是bug还是缺陷 ，是否会被修复

**Comment by javoski** [comment]
>注意：在变异（不是替换）对象或数组时，旧值将与新值相同，因为它们的引用指向同一个对象/数组。Vue 不会保留变异之前值的副本。

[https://cn.vuejs.org/v2/api/#vm-watch-expOrFn-callback-options](https://cn.vuejs.org/v2/api/#vm-watch-expOrFn-callback-options)
