### ISSUE TITLE
Potential Issue on IE 11 and data object declaration as function 

### ISSUE THREAD

**Issue by jvilomar** [vuejs/vue#6326]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/jvilomar/gvsukfa3/1/](https://jsfiddle.net/jvilomar/gvsukfa3/1/)

### Steps to reproduce
1. Create a component
2. Declare the data option as a function inside the component, as especified by the docs.
3. Run on IE 11

### What is expected?
The component should render without any issue on IE 11.

### What is actually happening?
The component breake the code.  The error on the console said Invalid Character at the data declaration line.

---
I was just building some demos and by coincidence had to run the app on IE and suddenly the app stop working. 

Some Points:
1.  I don't use any transpiler, just a pure JS function and Loaded the vue.js library from the cdn.
2. Didn't tested on earlier IE version or Firefox.
3. Works perfectly on Chrome and Edge.

**Comment by LinusBorg** [comment]
The problem is more likely that your template definition uses template literals which don't work in IE11

**Comment by jvilomar** [comment]
Yes Sir.

Changed to normal string and It worked.  I think that I will have to use babel in orther to avoid some of that errors, since I have to rely heavily on IE for my customers.

Thanks for the reply.
