### ISSUE TITLE
我在二级路由下给子组件传数据报错，error in callback for watcher 'function(){return this._data.$$state}';Do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by WormGirl** [vuejs/vue#6329]
### Version
2.4.2

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
但是实际上我并没有去改变vuex里的state，如果把那个组件放到一级路由下却不报错，我很困惑问题出在哪？补充一下我用了作者写的vuex-router同步插件，但也不应该是路由的问题吧，去掉那个组件就不报错了，貌似props的原因，如果不给子组件传数据就不会报错了。

### What is expected?
asda

### What is actually happening?
fdafsdf

---
sdfsd

**Comment by HerringtonDarkholme** [comment]
Hi @WormGirl , thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

----

Note, reproduction link needs to be your minimal app or repo. Note a link to another website, thanks.
