### ISSUE TITLE
Sanitize v-html

### ISSUE THREAD

**Issue by krestaino** [vuejs/vue#6333]
### What problem does this feature solve?
I'm currently working on making a [blog](https://github.com/krestaino/nuepress) using the WordPress REST API as the back end. The API returns the article with HTML markup in it. I'm taking that [JSON response](https://wp.kmr.io/wp-json/wp/v2/posts/1178) and using `v-html` to render it into my Vue app. I understand there are cross-site scripting security risks here.

### What does the proposed API look like?
It would be great if `v-html` automatically sanitized the string to remove any `<script>` tags. For those needing script tags, for whatever reason, maybe `v-html-unsafe` can accomplish that.

I was recently made aware Angular 4 is doing this and think Vue.js would greatly benefit from this feature.

https://angular.io/guide/security#!#xss

**Comment by posva** [comment]
That would be a breaking change, what can be done instead is adding a `.safe` modifier that strips off the `<script>` tags.

This can be easily handled in a computed property or with a utility function

**Comment by krestaino** [comment]
Just to clarify, are you saying that changing the default behavior of `v-html` would be the breaking change?

I guess ideally it would be nice if `v-html` was sanitized by default, but your suggestion using a `.safe` modifier sounds great too. So would that look like `v-html.safe="data"`?

**Comment by rpkilby** [comment]
Hi. Just my two cents, but I would be -1 on this. It seems unnecessary for Vue to maintain its own html sanitizer, given that there are other libraries that already do this well. I'd argue that there are more appropriate places to perform sanitization and that also allow for better developer control. A few ideas:

- Sanitize the HTML before persisting it to the database or before returning the JSON response.
- Sanitize the HTML in a Vue computed property. This would be useful if you're unable to modify the WordPress backend. You might try calling [this](https://www.npmjs.com/package/sanitize-html) library in the property.

Also, worth mentioning that the docs have appropriate warnings in both the [guide](https://vuejs.org/v2/guide/syntax.html#Raw-HTML) and [reference](https://vuejs.org/v2/api/#v-html) sections.

**Comment by krestaino** [comment]
@rpkilby [sanitize-html](https://www.npmjs.com/package/sanitize-html) seems great and will work for me and my use case. I still think it would be nice if Vue did this automatically as an added security measure, but I absolutely hear your concerns.

Thanks for your input and that link.

**Comment by javoski** [comment]
I don't think it's a good idea for Vue to add a built-in html-sanitizer either.
How about introducing a new config (e.g. `Vue.config.htmlSanitizer = (html) => safeHtml` ) as a compromised way.

**Comment by yyx990803** [comment]
I agree with @rpkilby - shipping a built-in sanitizer would add extra bundle weight for a rare use case (when most use cases of `v-html` are for trusted content); it is also trivial to add `sanitize-html` by setting `Vue.prototype.$sanitize = sanitizeHTML` and then do `v-html="$sanitize(html)"`.

**Comment by Braunson** [comment]
@yyx990803 I know this is an older thread but setting `$sanitize` it throws Uncaught ReferenceError: sanitizeHTML is not defined`. I know sanitizeHTML is defined as I've previously imported it and used it (before Vue is called)

**Comment by 1c7** [comment]
```
npm install sanitize-html
```

```
import sanitizeHTML from 'sanitize-html';
Vue.prototype.$sanitize = sanitizeHTML
```

```
div(v-html='$sanitize(topic.content_html)')
```

**Comment by Anima-t3d** [comment]
I ended up using https://www.npmjs.com/package/vue-dompurify-html

**Comment by nolimitdev** [comment]
> I agree with @rpkilby - shipping a built-in sanitizer would add extra bundle weight for a rare use case (when most use cases of `v-html` are for trusted content); it is also trivial to add `sanitize-html` by setting `Vue.prototype.$sanitize = sanitizeHTML` and then do `v-html="$sanitize(html)"`.

Im wondered that most popular libraries to sanitize HTML string are extremely huge (each one is bigger that my whole Vue.js app bundle)...
  https://www.npmjs.com/package/sanitize-html
  https://www.npmjs.com/package/dompurify
  https://www.npmjs.com/package/xss
  https://www.npmjs.com/package/string-strip-html

I have created simple & fast solution without regex, but I know that it is more secure to use popular well-tested libs. But I would like to know your opinion to this solution https://jsfiddle.net/n10L6a5u/ It is Vue.js plugin for custom directive `v-html-safe` which removes just insecure XSS things like attributes starting "on*" (e.g.: onload, onerror, ...) and also attribute values starting "javascript:*" (e.g. href="javascript:alert(1)"). Do you see some potential issues there?

**Comment by HuberTRoy** [comment]
For the developers that intend to use `sanitize-html` solve this problem：

**Comment by Yc-Chen** [comment]
`sanitize-html` gives a lot of warnings with vite as it is more built for Node.js use. You can also do

```JavaScript
import { escapeHtml } from '@vue/shared'
Vue.prototype.$sanitize = escapeHtml
```

This is the function that vue itself uses when rendering `<span>{{ userContent }}</span>`. You don't need to do extra install with `@vue/shared` because it is definitely included. 

See source:
https://github.com/vuejs/core/blob/main/packages/shared/src/escapeHtml.ts

**Comment by nolimitdev** [comment]
@Yc-Chen I think you are wrong. Vue's escapeHtml is not alternative to https://www.npmjs.com/package/sanitize-html First one is just aimple/primitive escaping so html tags are converted to entities and displayed so any user provided input is safe. Second one enables html all/some tags to be rendered and removes XSS attacks and insecure code.
