### ISSUE TITLE
Prop isn't being passed via element attribute

### ISSUE THREAD

**Issue by drdaemos** [vuejs/vue#6334]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/f4L454a5/](https://jsfiddle.net/f4L454a5/)

### Steps to reproduce
1. Pass prop as element attribute like this: `<div id="app" some-prop="prop-value"></div>`
2. Declare prop in props field as `props: ['someProp']`
3. Render template with prop interpolation like: `{{ someProp }}`

### What is expected?
To see "prop-value" outputted in the resulting HTML

### What is actually happening?
Prop value is being ignored without any messages and stays 'undefined'

**Comment by Plasmatium** [comment]
Hi @drdaemos ,
Maybe you can use `propsData`,
[Here](https://forum.vuejs.org/t/passing-props-to-root-instances-in-2-0/244) is the relevant thread.
[jsfiddle](https://jsfiddle.net/Plasmatium/f4L454a5/3/)

Good luck.

**Comment by LinusBorg** [comment]
Yep, that's expected. As @Plasmatium explains, you have to use `propsData` if you want to pass props to a root instance (which should be rarely the case..)

**Comment by drdaemos** [comment]
Yeah, thanks. I can accept that and will use `propsData`.
I guess it would be helpful to add Vue warning on such usage.
