### ISSUE TITLE
fiddle在国内打不开能否把官方例子统一迁移到jsbin或codepen？

### ISSUE THREAD

**Issue by alenyu** [vuejs/vue#6339]
### Reproduction link
[https://cn.vuejs.org/v2/examples/modal.html](https://cn.vuejs.org/v2/examples/modal.html)

### Steps to reproduce
jsfiddle预览在国内无法访问

### What is expected?
希望vue官网所有例子能正确显示

### What is actually happening?
jsfiddle无法访问会损失大量准备用vue的潜在用户

---
希望尤大神重视此问题，我很看好vue的发展，加油

**Comment by yyx990803** [comment]
...你是哪里的，上海不翻墙访问正常。我第一次听说这问题，应该不是普遍现象。

**Comment by Jinjiang** [comment]
我这边的表现是一阵一阵的，codepen 相对稳定一些，jsbin 也偶尔打不开，基本都是 CDN 静态资源打不开或非常慢导致的。我会继续保持观察。

@yyx990803 还有一种可能是你电脑里 CDN 静态资源缓存过了所以感受不明显 - -

Translation: This issue is talking about jsfiddle sometimes blocked in China. I will keep an eye on this.
Thanks.

**Comment by xufei** [comment]
国内某些运营商的网络是会打不开 jsfiddle，以前碰到过，codepen 确实比较稳定

**Comment by shangxinbo** [comment]
翻墙依然打不开

**Comment by baby24007** [comment]
确实打不开。已翻墙。google什么的都秒开。但是jsfiddle打不开。官方的demo都看不到。

**Comment by gaoshijun1993** [comment]
遇到同样问题..

**Comment by parkeeers** [comment]
确实翻墙都经常打不开jsfiddle，不仅仅是看vue的demo，平时使用jsfiddle也是这个毛病。不知道是哪里姿势不对

**Comment by CodeDome** [comment]
我的也是一样，快速看打开Google，但就是打不开jsfiddle

**Comment by saifeiLee** [comment]
遇到同样问题，请问大家有什么解决办法吗？

**Comment by EdwardCave** [comment]
现在有没有一个解决方法？

**Comment by JsonLeex** [comment]
![Screenshot from 2019-03-09 17-10-12](https://user-images.githubusercontent.com/25883665/54069037-46ac5880-428e-11e9-91d8-b8c54cadd46d.png)

**Comment by hdmy** [comment]
同上，提了element的issue，也因为jsfiddle打不开无法编辑，被关掉了 :cry

**Comment by xsbchen** [comment]
从us的vps上可以访问，在国内电信网络下不通

**Comment by pymxb1991** [comment]
我们是电信的网，也是访问不通，很纠结

**Comment by cooper1x** [comment]
翻墙全局代理也打不开

**Comment by bugyangs** [comment]
同样遇到这个问题

**Comment by yhhwpp** [comment]
+1

**Comment by luxueyan** [comment]
jsfiddle.net 到底什么情况，翻墙不翻墙都访问不了

**Comment by cody1991** [comment]
+1 访问不了

**Comment by kuige** [comment]
翻墙，地区是美国，可以访问

**Comment by 016** [comment]
测试了一下 只有美国地区 翻墙后才能访问， HK 无法访问。。。 真心的。

**Comment by pruidong** [comment]
打不开，google打开没问题,jsfiddle.net打不开,无法访问,看这篇教程的时候:https://cn.vuejs.org/v2/guide/render-function.html#%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91 发现下面的例子没显示,才看到引用的是jsfiddle.net.推荐更换到codepen.io,codepen.io访问无异常.

**Comment by susan007** [comment]
已开启翻墙，同样打不开jsfiddle，请问大家都是怎么解决的？急。。。

**Comment by Jiarui-Zeng** [comment]
同打不开

**Comment by hewenyuann19930327** [comment]
打不开    (┬＿┬)

**Comment by davidzhu1989** [comment]
打不开。。。+1

**Comment by GuYueJiaJie** [comment]
有梯子，绕过局域网和大陆，Google一切正常，jsfiddle打不开，我记得几天前还可以的

**Comment by 016** [comment]
再更新一次。。。 换个梯子，服务器在美国的梯子可以打开，其他地区的梯子打不开， 我有2个ss服务器，HK的无法打开，换成美国的 秒开， 希望对上述各位有帮助

不要以google是否能打开作为评判标准。

**Comment by GuYueJiaJie** [comment]
> 再更新一次。。。 换个梯子，服务器在美国的梯子可以打开，其他地区的梯子打不开， 我有2个ss服务器，HK的无法打开，换成美国的 秒开， 希望对上述各位有帮助
> 
> 不要以google是否能打开作为评判标准。

我手机电脑挂的同样的VPN，谷歌云，台湾地区的，手机可以打开，电脑打不开。
换了美国服务器，还是打不开。
但我前两天电脑还可以打开。

**Comment by 016** [comment]
> > 再更新一次。。。 换个梯子，服务器在美国的梯子可以打开，其他地区的梯子打不开， 我有2个ss服务器，HK的无法打开，换成美国的 秒开， 希望对上述各位有帮助
> > 不要以google是否能打开作为评判标准。
> 
> 我手机电脑挂的同样的VPN，谷歌云，台湾地区的，手机可以打开，电脑打不开。
> 换了美国服务器，还是打不开。
> 但我前两天电脑还可以打开。

我刚试了还是这样，所以可能和线路有关吧，不好意思只能帮到这里了。

**Comment by Rackar** [comment]
看来不是我的问题。确实挂了hk的代理别的站都能开，就他打不开

**Comment by xsbchen** [comment]
> ...你是哪里的，上海不翻墙访问正常。我第一次听说这问题，应该不是普遍现象。

难道只有上海能访问？深圳无法访问，看样子挺普遍的

**Comment by xsbchen** [comment]
ElemeFE/element#14716

**Comment by XiaYuYing** [comment]
坐标杭州也打不开 用的shadowsocks代理，换jp,us,的服务器都打不开

**Comment by andyWHJ** [comment]
ss设置成全局可以访问

**Comment by JackFrankWen** [comment]
上海也不能访问

**Comment by fanglinghui** [comment]
我也打不开，请问大家有获取官方例子的其他途径吗？

**Comment by susan007** [comment]
这个问题官方就不能重视一下吗？？？到底怎么想的啊！！！能不能给出一个解决办法？？？

**Comment by goodwong** [comment]
> 测试了一下 只有美国地区 翻墙后才能访问， HK 无法访问。。。 真心的。

<img width="864" alt="image" src="https://user-images.githubusercontent.com/2283172/70846322-39627100-1e93-11ea-864f-1b601f68b35d.png">

突然无法打开后，做了以上测试，发现香港没法ping通jsfiddle，猜测是被网站方面屏蔽了。
应该是jsfiddle方面的原因。

**Comment by auiferj** [comment]
> ss设置成全局可以访问

你很优秀

**Comment by susiwen8** [comment]
> ss设置成全局可以访问

我用这样的方式打开了

**Comment by Jinjiang** [comment]
同步一下这个 thread，目前 Vue 官方文档中英文版本中的代码示例均已经全部从 JSFiddle 迁移到了 codesandbox。例如：https://cn.vuejs.org/v2/examples/
截至目前 codesandbox 在国内的访问应该还算稳定。我们会持续考虑更妥善的呈现和部署的方式。谢谢

**Comment by xzionx** [comment]
北方 确实很难打开 挂VPN 也没有

**Comment by ksky521** [comment]
北方联通表示：的确打不开jsfiddle.net 。。。

**Comment by CodeDome** [comment]
都2021年了，还打不开

**Comment by ambit-tsai** [comment]
2021-05-14，翻墙也不行。。。

**Comment by NortonLee** [comment]
2023年了，依旧打不开

**Comment by goodwong** [comment]
既然是IT工作者，搞点科学上网的工具应该不是难事。境外的服务器访问质量都不靠谱，就不必费心了，唯有邀请尤大肉身回国去通管局拍张照片写份保证书搞个备案开通境内网站，访问速度保证妥妥的。顺带再办个银行卡开通打赏二维码，也帮国人免去白嫖之嫌。
