### ISSUE TITLE
vue-server-renderer: entry-server.js init method

### ISSUE THREAD

**Issue by aliksend** [vuejs/vue#6340]
### What problem does this feature solve?
I propose to add ability to declare method (init) that will be called on server initialization (after server starting and recompilation). Then developer will have possibility to reload other services.

For now I creating vue frontend app with server-side rendering and I want to create backend api server. I want to bundle it together with vue ssr server – I can just import it in my `entry-server.js` (so it will be successfully bundled) and connect it to my express `app`, that I can provide via `context` param, but if I will add that route to my backend api server in `export default` method, route will be added every time when user requested some from server (and vue-server-renderer call my `entry-server.js` default export method). Also it will not added after server starting, but only after first request. 

While my backend api server is bundled I can transparently call it methods in server-side api provider (on client-side api provider I use axios to make HTTP-requests). Writing 'providers' I mean `create-api-*.js` files inside [vue-hackernews/src/api](https://github.com/vuejs/vue-hackernews-2.0/tree/master/src/api)

I think that it will be very useful.

### What does the proposed API look like?
Means code from [vue-hackernews template](https://github.com/vuejs/vue-hackernews-2.0)

```javascript
// server.js
...

const backendRouter = express.Router()
app.use(backendRouter)
renderer.init({ backendRouter })

...

app.get('*', isProd ? render : (req, res) => {
  readyPromise.then(() => render(req, res))
})

```

```javascript
// entry-server.js
const backendApi = require('../backend/api')

function init(context) {
  context.backendRouter.use(backendApi);
}

export { init };

export default context => {
  ...
}
```

**Comment by yyx990803** [comment]
I think the API feels a bit confusing (took me a few times to grasp what you are trying to do). In fact, I think it's easier to **externalize** your backend API from your bundle so that both your bundle and your server code can just require the same backend API directly.
