### ISSUE TITLE
Why element have the same font-size but display differently on two component?

### ISSUE THREAD

**Issue by gai-sama** [vuejs/vue#6341]
### Version
2.3.3

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
I use vue-cli to initialize my project
then add <meta name="viewport" content="width=750,maximum-scale=1.2,user-scalable=no"> in index.html,
then add

`
< div v-for="n in 10" >
     <p style="font-size: 24px">蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤蛤</p>
< /div >
`

both in App.vue and Hello.vue, if I add style overflow: auto; to Hello.vue 's root element, font-size in two components will display different

### What is expected?
One font size in one page have two appearance, it's too strange

### What is actually happening?
should display the same

---
if I use
<meta name="viewport" content="width=device-width,maximum-scale=1.2,user-scalable=no">
or remove 
overflow: auto
it can behave normally, but that is not what I want

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
