### ISSUE TITLE
use components with sync occurs a BUG?

### ISSUE THREAD

**Issue by Tzxhy** [vuejs/vue#6347]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/Tzxhy/1zvquo6q/4/](https://jsfiddle.net/Tzxhy/1zvquo6q/4/)

### Steps to reproduce
点击第一个修改按钮, 修改第一个组件中name属性(Vue会正常警告), name属性正常更新; 点击第二个修改按钮 , 修改第二个组件中name属性, 结果第一个组件中name属性收到影响.需要注意的是, 我在第二个组件中, 对name属性用了  .sync  描述符.
First i  clicked the first "modify" button, it's ok. but i clicked the second "modify" button, the first 'my-component''s name became "original value".  By the way , i used '.sync' on data "name" in the second 'my-component'.

### What is expected?
第二次点击修改后, 第一个组件不受影响
after second click "modify" button, the first 'my-component' won't change. 

### What is actually happening?
第一个组件受到第二个组件的点击事件, 感觉像是状态恢复到初始.
after second click "modify" button, the "name" data in first 'my-component' changed into "original value" which is original data I delivered. 

---
无, 谢谢. 
no, thanks

**Comment by posva** [comment]
This is working as expected, you cannot change a prop value (look at the console). 
What happens is that when you change th ename on the parent, the parent renders again and passes the static value of the name, thus overriding your changes.

To solve this, use a data property to save the current state of `name`

**Comment by Tzxhy** [comment]
@posva thanks, I use a data to refer to 'name', yes, it works. thanks!
