### ISSUE TITLE
About synchronize select v-model

### ISSUE THREAD

**Issue by liuqipeng417** [vuejs/vue#6348]
### Version
2.4.2

### Reproduction link
[https://gist.github.com/liuqipeng417/f910314c6549256ead8dc9556264966f](https://gist.github.com/liuqipeng417/f910314c6549256ead8dc9556264966f)

### Steps to reproduce
```javascript
<!DOCTYPE html>
<html>
<head>

</head>
<body>
  <div id="app">
    <select v-model= @change="test" @change()>
      <option v-for="z in o" :value="z">
        z
      </option>
    </select>
  </div>
  <script src="https://unpkg.com/vue@2.4.2"></script>
  <script>
    new Vue({
      el: '#app',
      data() {
        return {
          o: [],
          x: ''
        }
      },
      methods: {
        test() {
          console.log('change event');
        }
      },
      mounted() {
        setTimeout(() => {
          this.o = [1,2,3,4];
        }, 2000);
      }
    });
  </script>
</body>
</html>
```

### What is expected?
When i try above snippet, i find when the timer callback execute in 2s later, it will trigger the `change` event and change `vm.x` to undefined.

I read the vue source code, and i find this:

```javascript
  componentUpdated: function componentUpdated (el, binding, vnode) {
    if (vnode.tag === 'select') {
      setSelected(el, binding, vnode.context);
      // in case the options rendered by v-for have changed,
      // it's possible that the value is out-of-sync with the rendered options.
      // detect such cases and filter out values that no longer has a matching
      // option in the DOM.
      var prevOptions = el._vOptions;
      var curOptions = el._vOptions = [].map.call(el.options, getValue);
      if (curOptions.some(function (o, i) { return !looseEqual(o, prevOptions[i]); })) {
        trigger(el, 'change');
      }
    }
  }
```

I know vue is want to synchronize the select'value , but i think when there is no `option` is be selected, the `v-model` should be synchronized to `''`, not to be `undefined`, because the select's default value is `''`.

### What is actually happening?
When there is no `option` is be selected, the `v-model` should be synchronized to `''`, not to be `undefined`, because the select's default value is `''`.

**Comment by posva** [comment]
This is actually intended. As you said, if you try to set the value of a `select` input to something that is impossible, the value will be transformed into an empty string `''`, Vue is being consistent in that aspect to set it to something more js like. In HTML, all attributes are strings, so it makes sense to have `''` but in Vue, we can use `null` or `undefined` instead.
This would also be a breaking change
