### ISSUE TITLE
[SSR] context.styles is undefined when `runInNewContext !== true`

### ISSUE THREAD

**Issue by nekuz0r** [vuejs/vue#6353]
### Version
2.4.2

### Reproduction link
[https://github.com/nekuz0r/vuejs-ssr-styles-issue](https://github.com/nekuz0r/vuejs-ssr-styles-issue)

### Steps to reproduce
```shell
npm run build
npm run start
```

### What is expected?
`context.styles` to be defined

### What is actually happening?
`context.styles` is `undefined` when `runInNewContext` is equal `false` or `'once'`

---
context.styles getter is not set on the new context created when
`runInNewContext` is equal to `false` or `once`.

`vue-style-loader` is defining a getter for `context.styles` property
(https://github.com/vuejs/vue-style-loader/blob/master/lib/addStylesServer.js#L9)

When `runInNewContext` is `false` or `once`, VueJS is copying the `_styles`
property in `userContext` from `initialContext` but the `styles` getter is not.
(https://github.com/vuejs/vue/blob/8ff77a243cae0627a651fe852a6c07f7bcfce2a3/src/server/bundle-renderer/create-bundle-runner.js#L131)

Adding the following line after that one fixes the issue

```javascript
Object.defineProperty(userContext, 'styles',
  Object.getOwnPropertyDescriptor(initialContext, 'styles')
)
```

**Comment by JounQin** [comment]
It's a typo which makes `styles` not enumerable, it should be fixed after the PR merged.

**Comment by yyx990803** [comment]
@JounQin are you sure? Even if it's not enumerable it should still be present. (I haven't got time to properly investigate this issue yet)

**Comment by JounQin** [comment]
Ah, sorry I read it wrong, and as I know it should not be an issue here, I'll try to figure it later.
