### ISSUE TITLE
Async components

### ISSUE THREAD

**Issue by RSalo** [vuejs/vue#6354]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/mdk1qerk/](https://jsfiddle.net/mdk1qerk/)

### Steps to reproduce
Templates in async components doesn't work as i expected by manual https://vuejs.org/v2/guide/components.html#Advanced-Async-Components

### What is expected?
Output '<span>It doesn\'t work :-(</span>'

### What is actually happening?
Return empty template

**Comment by yyx990803** [comment]
1. You are specifying a `template` option which will overwrite whatever template you have in the DOM.

2. The `component` property in the advanced syntax needs to be **a Promise that resolves to the component itself**.
