### ISSUE TITLE
@ alias doesn't resolve correctly in style tag in .vue files

### ISSUE THREAD

**Issue by vivek-roy** [vuejs/vue#6356]
### What problem does this feature solve?
In webpack.base.config the @ alias is defined as:
```
...
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
         'vue$': 'vue/dist/vue.esm.js',
         '@': resolve(src)
    }
},
...
```
But when I use the @ alias in a style tag in a .vue file it doesn't seem to work.
```
<style lang="scss" scoped>
    @import "@/styles/variables";
    ...
</style>
```
I get the error
```File to import not found or unreadable: @/styles/variables.```

PS: I am using a src/styles/_variables.scss file to store sass variables which I am importing in every .vue file. I would love to know if there is some other way of importing the variables file in every component using sass-loader or style-loader.

Thanks

### What does the proposed API look like?
```
<style lang="scss" scoped>
    @import "@/styles/variables";
    ...
</style>
```

**Comment by Akryum** [comment]
Try `@import "~src/style/card"`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).


----


This has nothing to deal with vue itself
@Akryum was faster to give you an answer 🙂

**Comment by Akryum** [comment]
This is related to webpack indeed.

**Comment by LinusBorg** [comment]
@vivek-roy but this is the repositor for Vue.js, the library, not for the webpack template, and your problem is about webpack, not Vue.

You can find the template's repo here: http://github.com/vuejs-templates/webpack

**Comment by EastSun5566** [comment]
@thezealousfool 
Well... I just found you can use `@import "~@/styles/variables";`.
And it's just work!!!

**Comment by zhaoboxiang** [comment]
Thank you very much @EastSun5566 it work for me, Great!
