### ISSUE TITLE
Typescript experimental declarations feature

### ISSUE THREAD

**Issue by laputa523** [vuejs/vue#6368]
### What problem does this feature solve?
I would love to have Typescript recognize the fields defined in props and data directly, as demoed in this starter project: https://github.com/Microsoft/TypeScript-Vue-Starter. This solves the headache of declaring an interface for every component, and changing the interface whenever I change something in the component.

However, it uses a fork of Vue that I cannot directly leverage in my production code because it's far behind the latest release. Can I have a timeline when is this feature going to be released?

### What does the proposed API look like?
This looks like an experimental feature already implemented, and I'd like to know when it is going to be merged and released.

**Comment by HerringtonDarkholme** [comment]
Hi @laputa523 , I'm glad to hear Vue is used in Microsoft produciton! Thanks for reporting :)

Meanwhile, you can track the progress of improved typing in https://github.com/vuejs/vue/pull/5887.

The main blocker here is the blocking change in declaration. We need a transition plan to introduce the new change. Also https://github.com/Microsoft/TypeScript/issues/14400 can help the transition (by inferring optional generic type parameter, we can make a compatible API without losing precise inference.)

Let's first close this issue so we can concentrate discussion on the pull request. Thanks!
