### ISSUE TITLE
Data Leaks among multi instances of a component

### ISSUE THREAD

**Issue by Lahori-Jawan** [vuejs/vue#6370]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/Lahori/v0z02cna/5/](https://jsfiddle.net/Lahori/v0z02cna/5/)

### What is expected?
Removing an Instance of a component should remove all data it holds

### What is actually happening?
Removing an Instance of a component passes/leaks data to next sibling in a chain

**Comment by jkzing** [comment]
Two mistakes in your fiddle:
1. it should be `key` not `keys`, and shortland for `v-bind:key` shoud be `:key`.
2. you should use a unique key instead of using index

see fixed: [https://jsfiddle.net/v0z02cna/6/](https://jsfiddle.net/v0z02cna/6/)
