### ISSUE TITLE
cannot run in iphone 4 and iphone 5

### ISSUE THREAD

**Issue by badoet** [vuejs/vue#6376]
### Version
2.4.2

### Reproduction link
[https://blog.imajin.tech/](https://blog.imajin.tech/)

### Steps to reproduce
open in iphone 4 and iphone 5

### What is expected?
everything works

### What is actually happening?
v-model doesnt work

---
is vue 2 support iphone 4 and iphone 5 default web view?

**Comment by LinusBorg** [comment]
Would you kindly tell us where this "v-model" code is to be  found in the source of this website? I won'T search for it.

**Comment by badoet** [comment]
sorry false alarm
