### ISSUE TITLE
Both v-if and v-else true (Vue + .NET)

### ISSUE THREAD

**Issue by johnfercher** [vuejs/vue#6377]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
I created a project using this tutorial:   https://new-issue.vuejs.org/

### What is expected?
Or condition is true and the DOM shows the content inside v-if, Or condition if false and the DOM shows the content inside v-else.

### What is actually happening?
The DOM shows both content.

**Comment by sirlancelot** [comment]
Your repro link doesn't contain `v-if` or `v-else`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
