### ISSUE TITLE
Selected <select> option set by v-model not working in IE

### ISSUE THREAD

**Issue by isterkebab** [vuejs/vue#6378]
### Version
2.4.2

### Reproduction link
[http://jsfiddle.net/yMv7y/3267/](http://jsfiddle.net/yMv7y/3267/)

### Steps to reproduce
Set a select element's v-model to one of its options value objects in a component mounted callback.

### What is expected?
The selected option should match the <select> tags v-model value

### What is actually happening?
Dropdown value remains empty

**Comment by posva** [comment]
dup of #6209
