### ISSUE TITLE
v-model 取反值，无法正确处理

### ISSUE THREAD

**Issue by cloudcome** [vuejs/vue#638]
```
<label for="draft">
    <input type="checkbox" name="draft" id="draft" v-model="!object.isDisplay"/>
    保存为草稿
</label>
```

因为`isDisplay`表示是否在前端显示，因此草稿状态，其为`false`，`checked`为`true`。
但在测试发现，无论该 `checkbox` 是否 `checked`，`object.isDisplay` 一直为 `true`

**Comment by hasikii** [comment]
请教大大，如果在v-for里怎么写呢

**Comment by gloomyline** [comment]
@hasikii 同样可以使用计算属性来实现取反

**Comment by hasikii** [comment]
@gloomyline 对v-for的数组map一份新的数组吗，这么写的话，v-model的值改变了，但是原数组的值似乎没有被改变

**Comment by wsz7777** [comment]
@hasikii v-model是   : value="value"   和  @change="$ event. target. value=value"  的缩写。你可以试试

**Comment by hasikii** [comment]
@wsz7777 可以了！太感谢了！🙏🙏🙏

**Comment by fellowT** [comment]
我用computed发现不能传参，我循环出来的数据，比如1是true 0是false，我想用computed传参然后返回真假值发现不行，只能在循环之前先整理数据吗
