### ISSUE TITLE
String property escaping incorrectly?

### ISSUE THREAD

**Issue by TYoung86** [vuejs/vue#6381]
### Version
2.4.2

### Reproduction link
[http://jsfiddle.net/yMv7y/3274/](http://jsfiddle.net/yMv7y/3274/)

### Steps to reproduce
Pass some html-entity escaped string with an ampersand as a prop value to a control, try to display it.

E.g. &quot\;Example &amp\; stuff&quot\;

### What is expected?
"Example & stuff"

### What is actually happening?
"Example &amp\; stuff"

---
(Fiddle links to http://vuejs.org/js/vue.min.js instead of a specific version)

**Comment by ktsn** [comment]
Because you are writing `amp;` two times 

```
&quot;Banking &amp;**amp;** Financial Services&quot;
```

**Comment by TYoung86** [comment]
I see it but I don't believe it; I showed a colleague this before I submitted as a bug, didn't see &amp;amp; ... checking to make sure some copy-pasta didn't happen, but I still have this effect happening in my project, so maybe there's double-escaping there...
