### ISSUE TITLE
transition-group is not working on tables rows (tr)

### ISSUE THREAD

**Issue by mikadev** [vuejs/vue#6382]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/c8vqajb4/](https://jsfiddle.net/c8vqajb4/)

### Steps to reproduce
click the button no transition 

### What is expected?
transition on opacity property when the row appear

### What is actually happening?
no transition just appear

see also [https://stackoverflow.com/questions/45720175/vuejs-transition-on-table-rows/45720882?noredirect=1#comment78400529_45720882](https://stackoverflow.com/questions/45720175/vuejs-transition-on-table-rows/45720882?noredirect=1#comment78400529_45720882)

**Comment by javoski** [comment]
The tag `<transition>` is not allowed in `<table>` according to HTML spec, it will be stripped automatically by the browser, you can use template option, [https://jsfiddle.net/xujiongbo/c8vqajb4/7/](https://jsfiddle.net/xujiongbo/c8vqajb4/7/)
