### ISSUE TITLE
possible bug in handling of :key

### ISSUE THREAD

**Issue by iwebnaut** [vuejs/vue#6383]
### Version
2.4.2

### Reproduction link
[http://jsfiddle.net/xk5yL3h8/](http://jsfiddle.net/xk5yL3h8/)

### Steps to reproduce
create x number of child components that are more complex than just strings. Something like:
```
    	addRow() {
        	var row = new Object()
                row.uniqueId = 'row-'   this.rowCount
                row.text = 'row-' (this.rows.length)
        	this.rows.push(row)
                this.rowCount =  this.rowCount   1
        }
```

then do this: 

```
    <row-component :uniqueId="row.uniqueId" :row-data="row" :key="row.uniqueId"></row-component>
```

add some components inside child components, for example, some columns in this case.

```
      addColumn() {
      	  console.log
	  var column = new Object()
          column.uniqueId = this.uniqueId  '.col.'  this.columnCount
          this.columns.push(column)
          this.columnCount = this.columnCount   1
      }
```

### What is expected?
when deleting the first component, only that component should get deleted and not all of the components created after that component. Why? Because recreating all components kills any components that were inside of them.

### What is actually happening?
When deleting row components, what happens if we delete the first row is all subsequent rows also get deleted and then recreated so that all child-component inside of them get dropped and never recreated so we end up with empty rows, columns that were created are dropped. 

Watch the short video to see what is happening: http://maxniko.tinytake.com/sf/MTg3NTc2M182MDIyMzI5

---
I am creating row component where I can any number of columns. When I drop a row I want that exact row to be dropped and no other rows should be affected. While deleting rows I discovered that dropping a row all rows behind it would also get dropped and recreated but empty this time.

I also discovered that changing this:

```
<div v-for="(row, index) in rows">
      <row-component :uniqueId="row.uniqueId" :row-data="row" :key="row"></row-component>
      <button @click="deleteThisRow(index)">remove row</button>
</div> 
```

to this

```
<row-component v-for="(row, index) in rows" :uniqueId="row.uniqueId" :row-data="row" :key="row"></row-component>
```

works better but I need the remove button to be in the parent and not a child component so I wrapped v-for inside a div. Why is there a difference between these two ways?

First case it deletes all subsequent components and the second case just the component in question and the code is looking the same to me except for markup.

**Comment by javoski** [comment]
The `key` property is applied to **sibling** nodes, [https://vuejs.org/v2/guide/list.html#key](https://vuejs.org/v2/guide/list.html#key)
In your case, you can just move the `key` property to the `div` wrapper with `v-for`, [http://jsfiddle.net/xujiongbo/xk5yL3h8/2/](http://jsfiddle.net/xujiongbo/xk5yL3h8/2/)
