### ISSUE TITLE
Share state between hook functions for directives

### ISSUE THREAD

**Issue by andrewcourtice** [vuejs/vue#6385]
### What problem does this feature solve?
In some situations it is necessary to share state between hook functions on directives. This is particularly useful for directives that attach and detach event listeners on elements.

Consider the following example of a `v-drag` directive: [v-drag](https://jsfiddle.net/andrewcourtice/msahy1ge/2/).

The listener that gets attached to the element requires access to values provided in the `bind` hook (eg `element`, `modifiers` etc.). This in itself is not a problem until that same listener has to be removed from the element in the `unbind` hook. In order to remove the event listener from the element I need to ensure I can get a reference to it from the `unbind` hook. 

Perhaps I've gone about this the wrong way, but the only solution I could come up with is registering the listener against it's element in a persistent weakmap in `bind` and then finding the listener again in `unbind` using the element. 

This problem would be alleviated by simply attaching the listener to `this` in the `bind` hook and detaching in `unbind` by getting the listener from `this`.

### What does the proposed API look like?
Implement a `data` function on a directive to register (unreactive) state.

```javascript
Vue.directive("sample", {

    data() {
        return {
            dragEnterListener: null
        };
    },

    bind(element) {
        this.dragEnterListener = (event) => {};
        element.addEventListener("dragenter", this.dragEnterListener);
    },

    unbind(element) {
        element.removeEventListener("dragenter", this.dragEnterListener);
    }

});
```

**Comment by Naeemo** [comment]
This is nice and neat, 👍, considering all my data-* attributes and temporary variables outside 😂.

**Comment by sirlancelot** [comment]
Not sure I understand a need for that. Looking at your example, why not just wrap it in a component just handles drag events?

```
<template>
    <div @dragenter="dragHandler"><slot></slot></div>
</template>
<script>
export default {
    methods: {
        dragHandler($event) { debugger; }
    }
}
</script>

**Comment by posva** [comment]
The goto solution is to save state in the HTML element, but as @sirlancelot said, we want to keep directives simple and limit their responsibility. If they become more complex, using a component is the way to go

**Comment by LinusBorg** [comment]
Adding to what @posva said: Directive *had* this ability in Vue 1.0, and we deliberately removed it because essentially, custom directives in Vue 1.0 where too similar to components in their abilities, which made it unclear when to use what.

In Vue 2.0, we decided to make the destinction more clear: If you need state, you should generally use a component, not a directive. Directives' responsibilities are reduced to low-level DOM work. Higher level woirk should be done with components.

If the need for state in a directive arises in an edge case, you can use the element to store it as a workaround.

**Comment by sirlancelot** [comment]
If you want to manage some semi-complicated state in your directive, you could use a solution like this:

```javascript
const statefulDirective = (() => {
	const state = new WeakMap()
	return {
		bind(el) {
			const data = {}
			state.set(el, data)
		},
		update(el) {
			const data = state.get(el)
		},
		unbind(el) {
			state.delete(el)
		}
	}
})()
```

It's a slippery slope though so take care!

**Comment by cztomsik** [comment]
What about listeners or intervals/timeouts? It's not a state but we need to store them somehow so they could be cleared during unbind.

**Comment by LinusBorg** [comment]
You can either store it directly on the element or save it in a `Map`, using the element as the key.

**Comment by sirlancelot** [comment]
@cztomsik It's still on you to do cleanup, the code sample I provided only describes how to share a common state between different hook calls. You'll want to add your own cleanup during `unbind`.

**Comment by b4dnewz** [comment]
@sirlancelot simple, efficient and get the job done. thanks

**Comment by turbobuilt** [comment]
I'm running into this issue for a drag and drop directives as well.  The reason we don't want to use a component is because a component forces you to add another div around everything.  You can't have a component just be a <slot></slot>.  For example, if I have a <ul> and I want to be able to drag and drop <li> elements, creating a whole new component isn't a good idea because that component is going to have to have a div or something wrapping the <li> elements which will mess it up.

**Comment by Shamus03** [comment]
> creating a whole new component isn't a good idea because that component is going to have to have a div or something wrapping the `<li>` elements which will mess it up.

You can use the `component` tag and the `is` property:

```vue
// MyWrapper.vue
<template>
  <component :is="is">
    <slot />
  </component>
</template>

<script>
export default {
  props: {
    is: {
      type: String,
      default: 'div',
    },
  }
}
</script>

// Somewhere else
<template>
  <div>
    <MyWrapper is="ul">
      <li>some</li>
    </MyWrapper>
  </div>
</template>
```

> @sirlancelot solution doesn't work for me because I need a separate state for each instance of the directive.

The only case where that wouldn't work is if you had multiple instances of the directive on the same element.  If you need to have multiple instances of the directive on the same element, consider making a compound key using the element and some other property.

**Comment by yellow1912** [comment]
Component has isolated scope. That is a HUGE issue I don't know how you guys ignore that. Lets say you want to add simple drag and drop or some very generic feature, as soon as you create components for them you get into the scope mess. You now have to deal with all the props pass through and such. Directive IS the easy way to get around all that especially for features that should not have anything to do with scope. Otherwise, you should allow easy transparent component.

**Comment by dietergeerts** [comment]
> Component has isolated scope. That is a HUGE issue I don't know how you guys ignore that. Lets say you want to add simple drag and drop or some very generic feature, as soon as you create components for them you get into the scope mess. You now have to deal with all the props pass through and such. Directive IS the easy way to get around all that especially for features that should not have anything to do with scope. Otherwise, you should allow easy transparent component.

And this was the power of AngularJS. I currently have some problems with custom directives, where we want to make it easy to do form validation WITHOUT needing to add all these component wrappers. So if we could add a custom directive that handles it, it will be solved, self-contained, and very easy and clear to add to a form. I understand that the decision is partly based on the fact that by allowing this, directives could get hard, but it's up to the consumer to decide how far to go, no?

**Comment by tylik1** [comment]
Not sure this is the right way, but i've attached function directly to el

`Vue.directive('scroll', {
  inserted: (el, binding) => {
    el.fnc = evt => {
      binding.value(evt, el)
    }
    window.addEventListener('scroll', el.fnc, { passive: true })
  },
  unbind: el => {
    window.removeEventListener('scroll', el.fnc);
    delete el.fnc;
  },
})`

**Comment by Flamenco** [comment]
The ideal way to handle this is to use a `symbol` to store your state in the element.  That way you will avoid naming conflicts, your value will be encapsulated, and the entry will not get enumerated.

```js
const key = Symbol()

Vue.directive('scroll', {
  inserted: (el, binding) => {
      el[key] = { foo: 'bar' } // <--- your state here
  }
}
```

**Comment by mateusmento** [comment]
I think being able to declare state in directives can be useful for many applications. More so with composition api in mind. Directives can be used to appropriately assign  attributes and events to elements of a layout that should contain a specialized behavior. Although the behavior can be implemented by the composition api, there is still a work to assign the variables and functions to the elements in the template of components. Libraries react that uses hook to power components such as react-table are examples of this problem.

Having state in directives means that fine-grained behavior can be implemented and inserted seamlessly into elements with losing control over your layout, as it can happen with components.

Today composition api and directives can be used together to provide such behaviors but there is still a need to use both in client code, whereas directives could handle the work with state alone.

Imagine for example useful directives for implementing a behavior for multiselects, such as v-select, v-option, v-search-input. That way we would have control over the layout and facilities to include behavior.

**Comment by shamrin** [comment]
For comparison, Svelte directives are functions, and you can save state in a function closure.

For example, here is a directive for "click outside the element" event.
```js
// click_outside.js
export function clickOutside(node) {
  const handleClick = (event) => {
    if (!node.contains(event.target)) {
      node.dispatchEvent(new CustomEvent("outclick"));
    }
  };
  document.addEventListener("click", handleClick, true);
  return {
    destroy() {
      document.removeEventListener("click", handleClick, true);
    }
  };
}
```

Usage:

```svelte
<script>
  import { clickOutside } from "./click_outside.js";
  let showModal = true;
</script>

{#if showModal}
  <div class="box" use:clickOutside on:outclick={() => (showModal = false)}>
    Click outside me!
  </div>
{/if}
```

It makes directive code less straightforward then in Vue, but you don't need to stuck data into the DOM element.

https://svelte.dev/tutorial/actions

**Comment by csisy** [comment]
Adding it to the element sounds like a good idea, but if we want directives with specified generic parameters (like `HTMLElement`), we have to manually cast to `any` before adding/removing. Consider the following example:
```typescript
type Bindings = (width: number, height: number) => unknown;

const observerKey = Symbol('Key for ResizeObserver of the element');

export const vResized: Directive<HTMLElement, Bindings> = {
  mounted: (el, binding) => {
    const observer = new ResizeObserver((entries: ResizeObserverEntry[]) => {
      const rect = entries[0].contentRect;
      binding.value?.(rect.width, rect.height);
    });

    observer.observe(el);
    (el as any)[observerKey] = observer;
  },
  unmounted: (el) => {
    const element = el as any;
    const observer: ResizeObserver = element[observerKey];
    observer.disconnect();
    delete element[observerKey];
  }
};
```
We either have to cast from `HTMLElement` to `any` or use `any` instead of `HTMLElement`. Both kind of inconvenient.

As a side note, these kind of functionalities are better done by a directive instead of a component. As a mental model, directives are meant to be placed on elements, achieving easy composition. Can be worked around with components, but IMO directives are a better fit for these operations.

**Comment by ScopeyNZ** [comment]
Thanks @csisy - This was a really helpful comment.

Note that if you want to avoid the `as any` with TypeScript you can extend HTMLElement like so:

```ts
interface HasResizeObserver {
	[observerKey]?: InstanceType<typeof ResizeObserver>;
}

export const vResized: Directive<HTMLElement & HasResizeObserver, Bindings> = {
    // ...
}
```
