### ISSUE TITLE
TypeError: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by afshanaman** [vuejs/vue#6387]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/afshanaman81/50wL7mdz/54338/](https://jsfiddle.net/afshanaman81/50wL7mdz/54338/)

### Steps to reproduce
1. Create a method in vue, showMessage
2. Create an object  message: {show : false, text: 'any text'} in the data section
3. call showMessage from an HTML element using v-on:click='showMessage'
4. set the value of show to true using this.message.show = true
5. print the value of show using console.log(this.message.show)

### What is expected?
The value of 'show' should set to true without any error/warning

### What is actually happening?
I get a warning AND an error on the line:

this.message.show = true

as below:

[Vue warn]: Error in render function: "TypeError: Cannot read property 'toFixed' of undefined"

TypeError: Cannot read property 'toFixed' of undefined

However, the line console.log(this.message.show) prints correctly

---
The issue is not re-producible, when the same button is clicked under other circumstances. 

The expected behavior is as shown by the jsFiddle, but I dont see any error running it.

**Comment by posva** [comment]
If you want help with your project you can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). But when reporting a bug, we **need** a reproduction, so please, provide one

**Comment by afshanaman** [comment]
Ok, I will ask in SO. Thanks
