### ISSUE TITLE
跨<router-view>向上级DOM传递事件

### ISSUE THREAD

**Issue by rockan007** [vuejs/vue#6389]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/54358/](https://jsfiddle.net/50wL7mdz/54358/)

### Steps to reproduce
$emit的传递事件后的响应事件，错误

### What is expected?
能监听three事件，但是logthree事件一直报undefied

### What is actually happening?
能正确执行logthree方法

---
新手，vue有相关示例吗？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

`logthree` isn't defined where it should (look at the console for a better hint) https://jsfiddle.net/cm6844y6/
