### ISSUE TITLE
v-prop directive that pairs with .sync for stateless components

### ISSUE THREAD

**Issue by benirose** [vuejs/vue#6392]
### What problem does this feature solve?
Writing stateless components is confusing and under-documented, especially when the components contain UI elements the user interacts with. This gets even more complex when there are multiple UI elements in the component, and is particularly complex with elements like multiple select and checkboxes. Many people fall into the trap of [populating state from props](https://zhenyong.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html) and other anti-patterns. Much of Vue's documentation focuses on two-way data-binding to an internal state, but the community favors writing pure components without state that communicate changes back to the parent.

`v-bind.sync` provides a `v-model` like interface on the parent component, but still requires a lot of repeat code on the component, with more repetition for the more props you are trying to sync back to the parent. Additionally, while `v-model` will bind to the correct event based on the input type, as well as including "special care for some edge cases", this all has to be handled by the component author. This can lead to missing edge cases and other errors, and add significant complexity to the component.

### What does the proposed API look like?
Just as `v-model="foo"` is syntactic sugar for `:value="foo" @input="val => foo = val"` (and smartly binds to the correct event based on the field type), it would be great to have a similar directive for use in components, where we aren't keeping internal state, but simply want to emit an update event back to the parent. In this case `v-prop="foo"` could be syntactic sugar for `:value="foo" @input="$emit("update:foo", val)"` and would pair nicely with `:foo.sync="parentFoo"` on the parent.

**Comment by posva** [comment]
Thanks for the proposal. Right now, we're very lean on adding syntax sugar. The reason there's one for `v-model` is that it exists for inputs, and being able to use it in components, especially in UI components, makes the code more readable. But adding a new syntax for something that is already feasible and short, isn't the direction we want to go.

If, however, you think we can improve the docs, we'll happily take a PR for that at https://github.com/vuejs/vuejs.org 👍
