### ISSUE TITLE
Enhance v-else to work with v-for

### ISSUE THREAD

**Issue by silkcom** [vuejs/vue#6393]
### What problem does this feature solve?
In most cases that we use a v-for there is a v-if around it so that we can have a v-else to show a "No Results" element.  It seems like making v-else work directly with a v-for and output anytime the v-for (with a combined v-if if there is one) returns no results would enhance vue.

### What does the proposed API look like?
```
<div v-for="item in items">{{ item.name }}</div>
<div v-else>There are no items</div>
```

**Comment by posva** [comment]
Dup of #4174
