### ISSUE TITLE
style change of component when dynamic changes

### ISSUE THREAD

**Issue by oricou** [vuejs/vue#6394]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/oricou/qmnvd7xj/23/](https://jsfiddle.net/oricou/qmnvd7xj/23/)

### Steps to reproduce
Click on one of the cloud except the last one. 

### What is expected?
The cloud you click on should change to red and disappear.

### What is actually happening?
It turns red and disappear but then the cloud on the next row, takes it place but also turns red. It should not since it has not the right data-test attribute.

**Comment by posva** [comment]
Use a `key` attribute https://vuejs.org/v2/guide/list.html#key

**Comment by oricou** [comment]
Thanks and sorry for the trouble. I start Javascript, Vue, Django and I must say I have fun but it takes time to understand all details.

**Comment by posva** [comment]
No worries, I recommend you to check the [Discord server](https://vue-land.js.org/), you can get fast feedback 🙂
