### ISSUE TITLE
vue 和v-for循环相关的一个bug

### ISSUE THREAD

**Issue by hrbzcj** [vuejs/vue#6395]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/7usgLx4g/](https://jsfiddle.net/7usgLx4g/)

### Steps to reproduce
我模拟了一个分页来重现这个bug，选中分页中的复选框，然后点击下一页按钮（next page），就看到bug了。

临时解决的方法是loadData方法里被注释的那段。

### What is expected?
无

### What is actually happening?
无

**Comment by Jinjiang** [comment]
请描述更清楚一些你认为正常的结果是什么，以及在你那边实际看到的结果是什么，方便我们进一步讨论和定位
另外尽量用英文，这样会有更多人能够帮到你
谢谢

**Comment by jkzing** [comment]
`v-for`中要写`key`！[https://jsfiddle.net/7usgLx4g/1/](https://jsfiddle.net/7usgLx4g/1/)

 [https://cn.vuejs.org/v2/guide/list.html#key](https://cn.vuejs.org/v2/guide/list.html#key)

---
Your elements inside `v-for` should be keyed.

**Comment by javoski** [comment]
在你的例子里，当你切换分页的时候，Vue 会复用之前页面的元素以获取更好的性能，所以会看到 checkbox 的状态没有更新。
正常情况下，你应该把每个分页的 checkbox 的状态保存在 state 里，像[这样](https://jsfiddle.net/xujiongbo/7usgLx4g/2/)。

**Comment by hrbzcj** [comment]
谢谢大家
