### ISSUE TITLE
How do you make the flow chart in the document?

### ISSUE THREAD

**Issue by onlinelemon** [vuejs/vue#6396]
### What problem does this feature solve?
 flow chart

### What does the proposed API look like?
 flow chart

**Comment by javoski** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
