### ISSUE TITLE
Changing class of an input it's value bound to value resets to blank when class is updated

### ISSUE THREAD

**Issue by paulopmx** [vuejs/vue#6400]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/54531/](https://jsfiddle.net/50wL7mdz/54531/)

### Steps to reproduce
Enter value at first input box 1 it will change the class.
Enter value at second input box 2 it will not change class

Purpose of code, is to write a custom component. using the guide here
https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

### What is expected?
Not to reset the text when I change the class of the input box

### What is actually happening?
It's resetting the value to blank

---
It doesn't happen when the input box is not bound to a prop value. But the whole point of my task is to create a custom input component that can be bound, but I want to indicate there is an error and process the error handling display on the custom component.

**Comment by nickmessing** [comment]
@paulopmx, that's because you have `:value="value"` and `value` is `undefined` so when you change class you re-render it with new class **and** new value, you can just remove `:value="value"` to make it work (or use `v-model` instead).

**Comment by jkzing** [comment]
It's not **reseting input value to blank**. It just resets the input value to the bound `value` prop, which is always empty.

**Comment by paulopmx** [comment]
@nickmessing thanks for reply. I actually simplified the example, but it was actually bound to a defined prop from the parent, which is defined.

**Comment by nickmessing** [comment]
@paulopmx, no, it's not, `props` option has effect on components and doesn't have any effect on root app (`new Vue({props})` does nothing, `Vue.extend({props})` works)

**Comment by nickmessing** [comment]
@paulopmx, to check if `value` is defined you can just add `mounted () { console.log(this.value) }` and on every render your `input` will be reset to the value you see in the console.

**Comment by paulopmx** [comment]
Updated the code. https://jsfiddle.net/50wL7mdz/54609/ works

Yeah looks like your right, must have miss something in my bindings.
