### ISSUE TITLE
Just question about inject/provide

### ISSUE THREAD

**Issue by Elevista** [vuejs/vue#6402]
### What problem does this feature solve?
Is there any reason that can not inject provided value in itself?
I see that `initInjections(vm)`  is being called before `initProvide(vm)`
https://github.com/vuejs/vue/blob/3cac5c766fc7b75cacf0a51dbfe10269eb3caf6a/src/core/instance/init.js#L56
so I see it's not simple

### What does the proposed API look like?
```js
it('hope this can work', () => {
  const vm = new Vue({
    provide: { foo: 1 }
  })

  const child = new Vue({
    parent: vm,
    provide: { foo: 2 },
    inject: ['foo'],
  })

  expect(child.foo).toBe(2)
})
```
for same usage both parent and child
```js
import util from 'util'

const parent = new Vue({
  provide: { util },
  inject: ['util'],
  mounted(){
    this.util.sameCodeForUse()
  }
})

const child = new Vue({
  parent: parent,
  inject: ['util'],
  mounted(){
    this.util.sameCodeForUse()
  }
})
```
I'm using 
`computed: { util: () => util }`
but It looks ugly

**Comment by rayrutjes** [comment]
By having injected values resolved first, you can actually provide values based on them.

**Comment by Elevista** [comment]
@rayrutjes Sorry I can't understand. please explain in detail?

**Comment by rayrutjes** [comment]
Provided values should be able to rely on $data.
$data should be able to rely on injected values.
So the order must be:
1. inject
2. state
3. provide

**Comment by Elevista** [comment]
@rayrutjes oh, I saw in source code.
so it means provide to it self should not happen, right? 😢

**Comment by Elevista** [comment]
```js
import util from 'util'

const parent = new Vue({
  provide: { util },
  computedLike: { util },
  mounted(){
    this.util.sameCodeForUse()
  }
})

const child = new Vue({
  parent: parent,
  inject: ['util'],
  mounted(){
    this.util.sameCodeForUse()
  }
})
```
If there is some option like computed but without function just inject property to this without watch will nice..
