### ISSUE TITLE
A suggestion that function `Vue.use()` can receive a Array as a argument.

### ISSUE THREAD

**Issue by ReedSun** [vuejs/vue#6404]
### What problem does this feature solve?
First I want to thanks for this excellent framework. 

Sometimes when use many plugins in a component, I have to code like this:

```javascript
Vue.use(AjaxPlugin)
Vue.use(ToastPlugin)
Vue.use(LoadingPlugin)
Vue.use(AlertPlugin)
```

I think it will be a little troublesome. So I have a suggestion that function `Vue.use()` can receive a Array as a argument, then the code is like this: 

```javascript
Vue.use([AjaxPlugin, ToastPlugin, LoadingPlugin, AlertPlugin])
```

#### Vue.use( plugin )

- Arguments: 
  - {Object | Array | Function} plugin

#### example

```javascript
Vue.use([AjaxPlugin, ToastPlugin, LoadingPlugin, AlertPlugin])
```

**Comment by sirlancelot** [comment]
`[AjaxPlugin, ToastPlugin, LoadingPlugin, AlertPlugin].forEach(Vue.use, Vue)`

**Comment by ReedSun** [comment]
@sirlancelot oh! good idea. Thank you~
