### ISSUE TITLE
transition class not removed

### ISSUE THREAD

**Issue by zcoding** [vuejs/vue#6405]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/guwt89go/4/](https://jsfiddle.net/guwt89go/4/)

### Steps to reproduce
1. 打开上面的测试链接，等页面加载好
2. 马上切到浏览器的其他标签页
3. 等至少 8 秒（等动画都执行完）再回到测试页面

### What is expected?
回到测试页面时 "test" 应该显示出来

### What is actually happening?
"test" 没有显示出来，点一次 toggle 还是没出来，再点一次才出来

---
浏览器：Chrome 最新
操作系统：macOS

最后的状态应该是 `this.show === true` 没错，但是似乎 `shit-leave-to` 这个类没有移除？

**Comment by jkzing** [comment]
It' seems this edge case related to [https://github.com/vuejs/vue/issues/6024](https://github.com/vuejs/vue/issues/6024), and tracked in [https://github.com/vuejs/vue/issues/5800](https://github.com/vuejs/vue/issues/5800).

**Comment by posva** [comment]
Thanks for looking it up @jkzing 👍 
Closing as dup of #5800
