### ISSUE TITLE
inline-template should be default if no any template or render properties are passed into options on components.

### ISSUE THREAD

**Issue by neyaoz** [vuejs/vue#6406]
### What problem does this feature solve?
Just like the behavior of new vue instance, inline-template should be default on components. Because vue components are just printing `<!--function (e,n,r,i){return ee(t,e,n,r,i,!0)}-->` if there is no one of the template or render properties on the its own options.

Btw, if you have concerns about the isolation between parent and child (component) scopes, it is under the responsibility of the developer, just like under the inline-templates prop.

### What does the proposed API look like?
```js
Vue.component('example', {
    data: function () {
        return {
            message: 'Hello World';
        }
    }
})
```

```html
<example>
    {{ message }}
</example>
```

**Comment by rayrutjes** [comment]
Wouldn't this conflict with the default slot?

**Comment by neyaoz** [comment]
@rayrutjes, slots makes sense only when you have a template property or render function, right?

**Comment by neyaoz** [comment]
@rayrutjes And, what about this?

```js
Vue.component('example', {
  data: function () {
    return {
      message: 'Hello World'
    }
  },
  render: function (createElement) {
    return createElement(
      'div',
      this.$scopedSlots.default ? this.$scopedSlots.default(this) : this.$slots.default
    );
  }
});
```

```html
<example>
    <template scope="example">
        {{ example.message }}
    </template>
</example>
```

**Comment by yyx990803** [comment]
This conflicts with the default API. More importantly, the template behavior should be consistent by inspecting the parent template alone, the behavior should not vary based on the definition of the child component. This was an intentional design decision from the beginning and it's not going to change.
