### ISSUE TITLE
Vuejs render api calls with ssr

### ISSUE THREAD

**Issue by fabdelgado** [vuejs/vue#6408]
### What problem does this feature solve?
I was unable to render with vue ssr api call with javascript turned off. The documentation also does not explain how to do it.

### What does the proposed API look like?
If you can do document it if there is no possibility to create it.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This doc may help you: https://ssr.vuejs.org/
