### ISSUE TITLE
import 单文件组件之后 手动移除_Ctor 属性，store才能自动从根组件注入到子组件

### ISSUE THREAD

**Issue by twesix** [vuejs/vue#6409]
### Version
2.4.2

### Reproduction link
[https://github.com/twesix/vue-seed/tree/vuex-inject-problem](https://github.com/twesix/vue-seed/tree/vuex-inject-problem)

### Steps to reproduce
首先 npm install 安装依赖

然后

npm run page // 生成html

npm run server // 自动编译和模块热更新

open http://localhost:9000/example.html
在控制台应该可以看到渲染错误

### What is expected?
store实例应该从根组件注入到所有的子组件，并且在子组件的计算属性中可以访问到并且响应store的state发生的变化

我想知道为什么移除了导入的组件的_Ctor属性之后就可以了，我也不确定这是一个bug还是我哪里写的不对

### What is actually happening?
store实例无法注入到子组件，计算属性出现错误

**Comment by yyx990803** [comment]
抱歉，如果不确定是 bug，这个不属于 issues 的范畴。我们不能帮你 debug 整个项目。
