### ISSUE TITLE
vuex实例没有被注入到子组件

### ISSUE THREAD

**Issue by twesix** [vuejs/vue#6412]
### Version
2.4.2

### Reproduction link
[https://github.com/twesix/vue-seed/tree/vuex-inject-problem](https://github.com/twesix/vue-seed/tree/vuex-inject-problem)

### Steps to reproduce
// 依赖

npm install

// 构建

npm run page

---

// 热重载，如果没修改过代码这一步就不用了

npm run server

### What is expected?
在根实例中（Vue实例）中添加的store属性可以将 vuex实例被注入到子组件，并且可以在子组件的计算属性中访问到

### What is actually happening?
vuex实例没有被注入到子组件,无法在子组件的计算属性中访问到

---
这个repo就是个seed，并不是什么大的项目，只是把bug出现的情况写进去了，没有多余的东西，麻烦看一下，谢谢

**Comment by posva** [comment]
Please, if you want to report a bug, provide the reproduction, don't ask us to do it for you. Also you should be able to use this template to make it even easier: http://jsfiddle.net/posva/wsr78d2w/ 🙂

**Comment by twesix** [comment]
OK . Anyway , thanks.
