### ISSUE TITLE
 How to make router-view temporarily keep-alive?

### ISSUE THREAD

**Issue by tiger8888** [vuejs/vue#6413]
### What problem does this feature solve?
Hi guys:
I hava a hard problem:
A push into B ,then B push into C ,I need A and B to keep alive
C back to B,then B back to A, I need B to destroy

### What does the proposed API look like?
what I need is to keep A keep alive permanently, and keep B keep alive temporarily? Some Solutions? Thanks!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
