### ISSUE TITLE
Add a syntax sugar for v-bind

### ISSUE THREAD

**Issue by maple3142** [vuejs/vue#6416]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/Logqa8z5/](https://jsfiddle.net/Logqa8z5/)

### Steps to reproduce
Click run

### What is expected?
no

### What is actually happening?
no

---
I wish can make `<myspan :text="text"></span>` with shorter syntax like this `<myspan :text></myspan>`
When the prop name same as existing variable in parent, expand `:text` to `:text="text"`

**Comment by sqal** [comment]
It has been proposed many times in the past, please check https://github.com/vuejs/vue/issues/5835

**Comment by posva** [comment]
what @sqal said, dup of #5835
