### ISSUE TITLE
when I used ‘keep-alive’ and I want to switch users to log in my App, how can I clear the caches of the whole page. 

### ISSUE THREAD

**Issue by huziyang410** [vuejs/vue#6418]
### What problem does this feature solve?
when I used ‘keep-alive’ and I want to switch users to log in my App, how can I clear the caches of the whole page. 

### What does the proposed API look like?
load the whole page

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by posva** [comment]
To better handle bug reports and feature requests 😉

**Comment by huziyang410** [comment]
ok, thx
