### ISSUE TITLE
Render activator slot into default slot

### ISSUE THREAD

**Issue by Fl0pZz** [vuejs/vue#6420]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/y0bm33gt/5/](https://jsfiddle.net/y0bm33gt/5/)

### Steps to reproduce
Click run

### What is expected?
Expected render only "default slot" component

### What is actually happening?
Rendered both default and activator components

**Comment by yyx990803** [comment]
Your HOC is rendering `ctx.children` which includes everything, not the slots. Please doublecheck functional component slots API.

**Comment by Fl0pZz** [comment]
@yyx990803 Probably I did not correctly express my idea. I want the slots to be saved when using HOC component https://jsfiddle.net/y0bm33gt/6/
I have no idea how to do it at all
