### ISSUE TITLE
Template is not reacting to prop change

### ISSUE THREAD

**Issue by travisfisher** [vuejs/vue#6421]
### Version
2.4.2

### Reproduction link
[http://jsbin.com/huforaculu/edit?html,js,output](http://jsbin.com/huforaculu/edit?html,js,output)

### Steps to reproduce
Set up a prop that is an object and pass that prop down through all subsequent children. 

Have the child emit an update that gets passed up through to the root component, and have it react by changing the prop.

### What is expected?
Upon mutating the prop on the root component, I expected all template references to that prop to react to the change.

### What is actually happening?
Upon mutating the prop on the root component, all template references to that prop still show the initial value, even though a console.log() on the prop after the change is showing the updated value.

---
I was initially using:

`this.test.blah = 2`

Then I found the following caveat for reactivity:

https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

So I changed it to:

`this.$set(this.test, 'blah', 2)`

This change had no affect on the template rendering.

**Comment by posva** [comment]
As a note props are read-only, you should change the value where it is declared in `data`. In your example you don't have it, but you should have it because, what happens is that everytime the template re renders, the `test` object is reinitialized, and the change is ignored. so you **need** to save that object in `data`

**Comment by travisfisher** [comment]
This works, but I do get a warning in Vue when setting properties in "data" that represent props:

`The data property "test" is already declared as a prop. Use prop default value instead.`

If this is a common use-case, which maybe it isn't, maybe the warning should be re-evaluated?

**Comment by posva** [comment]
It has to be at the root so you can do:

```html
<foo :test="test"></foo>
```
