### ISSUE TITLE
How to make `Set` reactive?

### ISSUE THREAD

**Issue by boringer** [vuejs/vue#6422]
### Version
2.3.4

### Reproduction link
[https://codepen.io/anon/pen/gxzmML](https://codepen.io/anon/pen/gxzmML)

### Steps to reproduce
See the code pen please.

### What is expected?
When `Set#size` changes, computed data or view updates.

### What is actually happening?
When `Set#size` changes, Vue doesn't know.

**Comment by nickmessing** [comment]
@boringer, Unfortunately, `Set` is not reactive, just plain javascript objects, arrays and primitive types are supported. If you want to find a way around this limitation try asking in [chat](https://chat.vuejs.org) or in [forum](https://forum.vuejs.org). Github issues are only for bugs and feature requests but this is expected.
