### ISSUE TITLE
adding support for templateUrl as an optional

### ISSUE THREAD

**Issue by siddmegadeth** [vuejs/vue#6424]
### What problem does this feature solve?
Based on your blog regarding your view on template URL i support your purpose for not including
templateURL in vue.js

But given the complexity there are some project which requires templateURL and are web applications
which are not targeted towards performance. Such application which in vue.js requires a lot of Component written with in line html. given the complexity its a hard to debug at time. some teams do not have full stack people.
Requesting to provide support for templateURL in vue.js for making vue.js as a standard choice for creating large scale enterprise level application.

This is a feature request.

### What does the proposed API look like?
// Define a new component called todo-item
Vue.component('todo-item', {
  templateUrl : '<li>This is a todo</li>'
})

**Comment by posva** [comment]
This is actually already achievable in userland, and we'll probably keep it that way. Because components can be functions that return promises, you can handle fetching the template inside of that promise:

```js
const Home = async () => {
     const template = await fetch(templateUrl)
     return {
          template
    }
}
```

Here's a working example in a jsfiddle using promises: http://jsfiddle.net/z9f13t6m/

**Comment by siddmegadeth** [comment]
Thank you for this.The JSFiddle provided still fetches a inline html tag not a .html file.
But we are looking for out of the box solution just like AngularJS. This also does not work out
for our application.

**Comment by javoski** [comment]
For large-scale App, single file component `.vue` is recommended, and if you want to use external HTML file, you can import it in `.vue` file like:
```vue
<template src="component.html"></template>
```

**Comment by posva** [comment]
You only need to use axios or a similar lib to fetch the `HTML` file 😉 
You can ask more questions on the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/)

**Comment by Akryum** [comment]
> The JSFiddle provided still fetches a inline html tag not a .html file.

The fiddle is a fake fetch because you can't put an html file on jsfiddle. In your real project, you can absolutely make a request to your server to retrieve an html file. For example, with the standard [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) API, it's very easy as seen in @posva example:

```javascript
const Home = async () => {
  const template = await fetch('http://yourserver.com/templates/foo.html')
  return {
    template,
    // other component options...
  }
}
```

> But we are looking for out of the box solution just like AngularJS.

This works out-of-the-box and you don't need any additional library other than Vue.

> This also does not work out for our application.

There is no reason this shouldn't work.

**Comment by phplego** [comment]
In my view in is a bit opinionated to have only `template` but not `templateUrl`. I wrote many components using `templateUrl`. And now it's frustrating for me.
I don't care too much about speed or how many HTTP requests have been sent. Why the hell vue doesn't allow me to do what I want :)

**Comment by AccessViolator** [comment]
I agree with @phplego - let **US** choose.
I also suppose a template loaded this 'manual' way wouldn't be cached in a template cache, would it?
This should be reopened.
