### ISSUE TITLE
Class binding class name b--black or b--gray causes template compilation error

### ISSUE THREAD

**Issue by blackbetty** [vuejs/vue#6425]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Take any element and add 

v-bind:class="{ b--black: bool }"

to it.  Seems to happen with any class name that contains two hyphens in a row. This is a problem for people using Tachyons CSS

### What is expected?
That the b--black class (border = black) should be applied to the containing element

### What is actually happening?
a compilation error

---
I am using Tachyons CSS for styling and trying to conditionally change a border color.

https://github.com/tachyons-css/tachyons-border-colors

a double hyphen seems to be a legitimate class name to me.

**Comment by simplesmiler** [comment]
Hi!

Like you would do in Javascript, you need to wrap `b--black` in quotes, because it's not a valid JS identifier.
Demo: https://jsfiddle.net/50wL7mdz/55320/

**Comment by blackbetty** [comment]
D'oh, thank you!
