### ISSUE TITLE
Props not passed to $attrs from Route props

### ISSUE THREAD

**Issue by adi518** [vuejs/vue#6426]
### Version
2.4.2

### Reproduction link
[https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg](https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg)

### Steps to reproduce
Setup a wrapping component which proxies all props to its child using `v-bind="$attrs"`. Then try to pass props using `vue-router` API.

### What is expected?
To have all props from route passed to component.

### What is actually happening?
None is passed.

**Comment by posva** [comment]
You have to remove the prop name from the Hello.vue component for it to work

**Comment by lbogdan** [comment]
@posva The hierarchy is `<router-link>` -> `<HelloWrapper>` (no props) -> `<Hello>` (`name` prop).

**Comment by adi518** [comment]
This is a `vue-router` issue. Sorry for the confusion it may cause.

**Comment by posva** [comment]
Oh, right. Let's move this to vue-router, I'm doing it
