### ISSUE TITLE
vue can not get css style

### ISSUE THREAD

**Issue by xcodebin** [vuejs/vue#6427]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/xcodebin/50wL7mdz/55556/](https://jsfiddle.net/xcodebin/50wL7mdz/55556/)

### Steps to reproduce
在mounted函数里写了nextTixk后还是获取不到css的样式，但是可以获取到style的样式

### What is expected?
获取到css中的样式

### What is actually happening?
在mounted函数里写了nextTixk后还是获取不到css的样式，但是可以获取到style的样式

---
看例子就能明白我的疑问，希望作者可以处理一下。

**Comment by yyx990803** [comment]
用 css 设置的规则用 style 本来就取不到... 这跟 vue 一点关系也没有。
