### ISSUE TITLE
errorHandler does not catch uncaught exceptions

### ISSUE THREAD

**Issue by iamvitali** [vuejs/vue#6430]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/5tp9mm4p/2/](https://jsfiddle.net/5tp9mm4p/2/)

### Steps to reproduce
Use `errorHandler` to handle errors.
Create a `this.$http.get` request.
Throw an error within the request.

### What is expected?
`errorHandler` should catch the error

### What is actually happening?
`errorHandler` does not catch the error

**Comment by yyx990803** [comment]
`errorHandler` cannot catch errors thrown asynchronously, similar to how `try... catch` cannot do that. You are responsible for anything thrown from within a Promise chain.

**Comment by iamvitali** [comment]
I guess a very dirty hack would be something like this?:

```
window.addEventListener("unhandledrejection", (e) => {
	Vue.config.errorHandler.call(this, e.reason, this, e.type);
});
```
