### ISSUE TITLE
Consider feature detecting for browsers instead of UA sniffing

### ISSUE THREAD

**Issue by stowball** [vuejs/vue#6432]
### What problem does this feature solve?
[env.js](https://github.com/vuejs/vue/blob/dev/src/core/util/env.js) currently contains 6 user agent sniffing detections that can be faked, and may not always return what's expected.

For instance, `isAndroid = UA && UA.indexOf('android') > 0` will also detect Firefox on Android. Is the real intention to detect WebKit browsers on Android, because that would require also checking for `'WebkitAppearance' in document.documentElement.style` or `!'MozAppearance' in document.documentElement.style`?

Similarly, some Android devices use `iPhone` and `iPad` in their UAs to get around, ironically, bad UA sniffing. True iOS can be detected with `'webkitOverflowScrolling' in document.documentElement.style`.

Edge can be detected with `!!(window.CSS && window.CSS.supports('-ms-user-select', 'none'))`

IE can be detected with `('msScrollLimit' in document.documentElement.style || 'behavior' in document.documentElement.style) && !isEdge`

IE9 can be detected with `isIE && !'msUserSelect' in document.documentElement.style`

Chrome can be detected with `window.chrome && !isEdge`, which also returns true for Opera, and false for Chrome on iOS.

### What does the proposed API look like?
```
const htmlStyle = document.documentElement.style
export const isEdge = !!(window.CSS && window.CSS.supports('-ms-user-select', 'none'))
export const isIE = ('msScrollLimit' in htmlStyle || 'behavior' in htmlStyle) && !isEdge
export const isIE9 = isIE && !'msUserSelect' in htmlStyle
export const isAndroid = UA && UA.indexOf('android') > 0 && 'WebkitAppearance' in htmlStyle
export const isIOS = 'webkitOverflowScrolling' in htmlStyle
export const isChrome = window.chrome && !isEdge
```

**Comment by yyx990803** [comment]
To me vendor prefixed sniffing is even more unreliable. They are more likely to get removed/changed/deprecated in future versions of these browsers.

**Comment by stowball** [comment]
That's an interesting thought, but I feel it's unwarranted as the web platform prioritises backwards compatibility.

The IE & IE9 detections are locked down; they will never change as they'll never release new versions of these browsers.

The Chrome detection would break a lot of things if they removed `window.chrome`. A [GitHub search reveals 16,427,300 results](https://github.com/search?q=window.chrome&type=Code&utf8=%E2%9C%93).

`'WebkitAppearance` and `'MozAppearance` [have existed from Safari v3, Chrome v1 & Firefox v1](https://developer.mozilla.org/en/docs/Web/CSS/-moz-appearance). The existence of `'WebkitAppearance'` was deemed so important that Edge also implemented it for compatibility reasons. A GitHub search reveals 7,919,623 hits for `-webkit-appearance`, 1,507,796 for `-moz-appearance` and 510,663 and 115,429 for their `Webkit/Moz` equivalents. There are many millions more results for `appearance:`, which you'd assume are being auto-prefixed.

The iOS detection is less well known. There's also `'WebkitTouchCallout'` (which has more results in GitHub), but I'd be worried if a touch-screen Mac was released, this would also then exist in Safari there. We could also check for the absence of `'WebkitDashboardRegion'` which has [only existed in desktop Safari since v3](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266--webkit-dashboard-region).

Which leaves Edge. Here is a list of the `ms` prefixed properties that have existed since Edge launched (they haven't changed from 11 – 14):

```
msContentZoomChaining: ;
msContentZooming: ;
msContentZoomLimit: ;
msContentZoomLimitMax: ;
msContentZoomLimitMin: ;
msContentZoomSnap: ;
msContentZoomSnapPoints: ;
msContentZoomSnapType: ;
msFlowFrom: ;
msFlowInto: ;
msFontFeatureSettings: ;
msGridColumn: ;
msGridColumnAlign: ;
msGridColumns: ;
msGridColumnSpan: ;
msGridRow: ;
msGridRowAlign: ;
msGridRows: ;
msGridRowSpan: ;
msHighContrastAdjust: ;
msHyphenateLimitChars: ;
msHyphenateLimitLines: ;
msHyphenateLimitZone: ;
msHyphens: ;
msImeAlign: ;
msOverflowStyle: ;
msScrollChaining: ;
msScrollLimit: ;
msScrollLimitXMax: ;
msScrollLimitXMin: ;
msScrollLimitYMax: ;
msScrollLimitYMin: ;
msScrollRails: ;
msScrollSnapPointsX: ;
msScrollSnapPointsY: ;
msScrollSnapType: ;
msScrollSnapX: ;
msScrollSnapY: ;
msScrollTranslation: ;
msTextCombineHorizontal: ;
msTextSizeAdjust: ;
msTouchSelect: ;
msUserSelect: ;
msWrapFlow: ;
msWrapMargin: ;
msWrapThrough: ;
```

Perhaps testing for the `support` of `ms-high-contrast-adjust` would be better since it's a native OS accessibility feature?

FYI all of the supported CSS features I mention have been obtained via opening http://mattstow.com/style.html in each browser and comparing the output (since January 2013).

**Comment by yyx990803** [comment]
I personally think opting for these more esoteric techniques for platform sniffing just opens up a whole new can of worms and I'm honestly not sure if it's actually better or worth it. Unless we have concrete examples where the current sniffing strategies are leading to unintended behaviors on certain devices, I intend to keep them as is.

**Comment by stowball** [comment]
> Unless we have concrete examples where the current sniffing strategies are leading to unintended behaviors on certain devices, I intend to keep them as is.

Have you tested that Firefox on Android isn't behaving incorrectly with your `isAndroid` conditions in the codebase?
