### ISSUE TITLE
component-parse will report some error if we put a correct js string which containing '</script>' in script section

### ISSUE THREAD

**Issue by hccde** [vuejs/vue#6433]
### Version
2.4.2

### Reproduction link
[https://github.com/hccde/vue-bug.git](https://github.com/hccde/vue-bug.git)

### Steps to reproduce
# 1.cd repo/test-bug

# 2.npm install

# 3.npm run dev

# then you will see the error in terminal

### What is expected?
run correctly

### What is actually happening?
build error

---
a component can be split into 3 sections : **script** ,** style** and **script**. this bug happened in **script** section .when we have a js string like:

  ```
var testString = '</script>'

 ```
so it may appear like this:

```
<template>
    <div>
        test
    </div>
</template>

<script>
    var testString = '</script>'
</script>
<style>
</style>
```

in **script** section,we failed to build

**Comment by zxc0328** [comment]
It's a parse error in vue-loader. Please open an issue there https://github.com/vuejs/vue-loader/issues.

**Comment by hccde** [comment]
@zxc0328 hey,i'm reviewing the code now,i think it comes from  **vue-template-compiler** .but  **vue-template-compiler** is built by **vue/src compiler**.  so,i open an issue here.

**Comment by javoski** [comment]
You should add a backslash before slash to escape.
```js
var testString = '<\/script>'
```

**Comment by hccde** [comment]
@javoski  it works! But obviously it's **parse bug**.solve the problem uglily. i have found out why this bug happened.if have time,i will give a pr

**Comment by javoski** [comment]
Actually, the default HTML parser of most (maybe all) browser will interpret '</script>' within a javascript string as the end script tag, so I don't think Vue can do more on this.

**Comment by nickmessing** [comment]
@jakovski, that is right, that's a part of HTML spec, it doesn't parse javascript inside, it just looks for `</script>` so this is expected.
@hccde, you can check it with `htmlparser2` or `parse5` on [astexplorer](https://astexplorer.net/#/gist/f349b32e705bf46fc0161470754e4adc/8d4e23bb85c548f85333d6c0d93bc4a39346d506)

**Comment by hccde** [comment]
@javoski  @nickmessing  that's true. '</script>' in  **inline script** in **html** need to  be escaped,because browsers don't know it's a **js string **. but **Vue**,to be exact,**vue-template** can distinguish between **js string**  and **tag name**,because  a **.vue file** has only one **script** section . when we meet a **'</script>'**  string,don't take it as the close tag immediately but look behind （ not look ahead :) )，if we find another **'</script>'**,look behind again,utill we find this **'</script>'** is the last one ,then this is the correct close tag.as I mentioned above,Vue or Vue template can solve this problem elegantly.it can ,it shoud,and it do better. browsers can't do this,because it may have many **inline script** sections,like ：
```
<html>
 <script>
    console.log('section one')
</script>
 <script>
    console.log('section two')
</script>
</html>
```
so ,that's all.

**Comment by javoski** [comment]
These generated Javascript codes will eventually be embedded into HTML files, it's ok if these codes are in a separated js file, but it relies on the building process, I don't think that's a good idea.

**Comment by hccde** [comment]
@javoski thus this is not usual situation, considering this code may be embedded into HTML files,we should not do more. you are right.
