### ISSUE TITLE
@keyup.meta.enter

### ISSUE THREAD

**Issue by codeofsumit** [vuejs/vue#6435]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/55822/](https://jsfiddle.net/50wL7mdz/55822/)

### Steps to reproduce
As per the docs here:
https://vuejs.org/v2/guide/events.html#Modifier-Keys

the modifier key "meta" should work for apple keyboards "cmd" key but it doesn't work combined with enter.
It works fine with @keyup.ctrl.enter

### What is expected?
@keyup.meta.enter="myFunc()" fires myFunc() when cmd enter is pressed on mac.

### What is actually happening?
myFunc doesn't fire.

**Comment by posva** [comment]
This is actually the browser not firing the `keyup` event on inputs while the meta key is pressed. Try using `<input @keyup.enter="myFunc">` and try releasing enter with and without the meta key pressed
