### ISSUE TITLE
Use toString() to determine if Function prop has been modified

### ISSUE THREAD

**Issue by adamvleggett** [vuejs/vue#6443]
### What problem does this feature solve?
It can be very convenient to use pass an anonymous function to a component in a template in certain instances, for example to provide a formatting function when a slot feels like overkill. However, anonymous functions will always cause the child component to rerender when the parent component rerenders, because the function will be recreated.

I suggest that if the === comparison is false, then next try comparing .toString() and only rerender if that is also false. This is unlikely to have a noticeable negative performance impact, as Function props are not terribly common (and changing them on the fly even less so) and benchmarking Function.toString shows that 3M ops per second is pretty standard on my Windows/Chrome system regardless of function size.

### What does the proposed API look like?
Not proposing any API changes.

**Comment by posva** [comment]
You can already declare a function in data or as a computed to not recreate the function when the template renders again, and I'd say that is the recommended way, having functions floating in your template is too much js in the template

> This is unlikely to have a noticeable negative performance impact

Unfortunately, this is adding a check for **every** prop **everywhere**, so it may actually be noticeable

Tell me if I misunderstood something, but since this is already easily achievable we prefer not to introduce a new condition check that could lead to slower performance

**Comment by adamvleggett** [comment]
You are correct that this is easily achievable; however throwing an arrow function into a template is often a matter of a few characters and is convenient for our developers (who may not realize the performance impact). The reason we use Vue is the small learning curve and large ease of use. Regardless, I understand.

**Comment by yyx990803** [comment]
FYI `toString()` is also not 100% technically correct, because two functions may very well have the same string content but declared in different scopes, so invoking them would result in different results... probably very uncommon, but still possible.

**Comment by adamvleggett** [comment]
Great point.

I feel like the documentation should warn that using anonymous functions this way can be a performance hazard. The temptation is real when arrow functions can be so compact.

**Comment by adamvleggett** [comment]
It would even be possible to generate a warning about this in a development build of Vue. It is trivial to use .toString() to determine if a function is anonymous.
