### ISSUE TITLE
Weex code in same branch as main vue code

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [vuejs/vue#6445]
### What problem does this feature solve?
Weex related code should be added over into the core repo. This would allow better readability

### What does the proposed API look like?
vue/weex-vuejs
vue/vuejs

**Comment by yyx990803** [comment]
It already is, in src/platforms/weex.

**Comment by rahul-dutt-sharma** [comment]
Other files have some references to weex. Also is there a high level diagram i can read to understand the framework. Interested to contribute

________________________________

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#project-structure
