### ISSUE TITLE
用于typescript的d.ts文件bug

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6449]
### Version
2.4.2

### Reproduction link
[https://unpkg.com/vue/dist/vue.js](https://unpkg.com/vue/dist/vue.js)

### Steps to reproduce

如果我用script引入vue.js的方式 typescript非模块化来开发,这里的d.ts就无法使用

### What is expected?
null

### What is actually happening?
null

---
null

**Comment by yyx990803** [comment]
都用 TS 了为什么还要用 script 引入? 
Anyway, this is not a bug.

**Comment by yangdan8** [comment]
使用typescript但是不用webpack打包,直接用微软的tsc.exe编译生成的js文件,然后使用script标签引入
