### ISSUE TITLE
Img tag automatically adds an end tag

### ISSUE THREAD

**Issue by Sven-ybj** [vuejs/vue#6452]
### Version
2.4.2

### Reproduction link
[https://sven-ybj.github.io/index.html](https://sven-ybj.github.io/index.html)

### Steps to reproduce
```
<div id="app">
    use Vue
    <div>
        <img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png" />
        <p>Become a sub tag of img</p>
    </div>
</div>
```

### What is expected?
```
<div id="app">
    use Vue
    <div>
        <img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png" />
        <p>Become a sub tag of img</p>
    </div>
</div>
```

### What is actually happening?
```
<div id="app">
    use Vue
    <div>
        <img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png">
        	<p>Become a sub tag of img</p>
		</img>
    </div>
</div>
```

---
非常简单的代码， 见https://sven-ybj.github.io/index.html

**Comment by LinusBorg** [comment]
HTML 5 doesn't allow self-closing tags. Just 
```html
<!-- wrong -->
<img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png" />
<!-- right -->
<img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png">

**Comment by Sven-ybj** [comment]
@LinusBorg I modified <img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png" /> to <img src="https://assets-cdn.github.com/images/modules/site/universe-logo.png">，But still error .
see https://sven-ybj.github.io/index.html

**Comment by LinusBorg** [comment]
Hm, that's super-weird. Because here it works normally: https://jsfiddle.net/Linusborg/c1ubzLm3/

No idea what this could be ...

**Comment by LinusBorg** [comment]
Okay, found it. Your vue.js file is not an original vue.js file. Someone changed it.

Your file:
```
var isHTMLTag = makeMap(
  'html,body,base,head,link,meta,style,title,' +
  'address,article,aside,footer,header,h1,h2,h3,h4,h5,h6,hgroup,nav,section,' +
  'div,dd,dl,dt,figcaption,figure,picture,hr,image,li,main,ol,p,pre,ul,' +
```
Note that this contains `image`, not `img`

The real file:

https://github.com/vuejs/vue/blob/dev/dist/vue.js#L4784

This contains `img`, as expected.

If you did this, nice try.

If someone did this to you, find them and slap them :-P

**Comment by phanan** [comment]
> If someone did this to you, find them and slap them :-P

Don't, if that someone is your girlfriend.

**Comment by Sven-ybj** [comment]
@LinusBorg Thank you very much, I checked the svn record, really was modified，But did not tell me.
