### ISSUE TITLE
Better handling of recursion in computed values

### ISSUE THREAD

**Issue by HendrikJan** [vuejs/vue#6454]
### What problem does this feature solve?
Computed values (objects) that reference each other can cause a "too much recursion" error.
In some cases this is not needed because a recalculation is triggered by a change in a property on which the computation does not depend.

If computed values are only recalculated when properties change that the value depends on, less calculation is needed and less errors will occur. 

Example case:

    new Vue({
        el: "#vue",  
        computed: {
            first: function() {   
                return {
                    name: 'first',
                    second_name: this.second.name
                }
            },
            second: function() {
    	        return {
                    name: 'second',
                    first_name: this.first.name
                };
            }
        }
    })

The above code will cause a "too much recursion".
Better behavior would be for ```first``` to resolve to

    {
        name: "first",
        second_name: "second"
    }

and ```second``` to resolve to

    {
        name: "second",
        first_name: "first"
    } 

Fiddle causing "too much recursion": https://jsfiddle.net/haaiee/1397fcaj/6/

Fiddle with one dependency removed, no error: https://jsfiddle.net/haaiee/1397fcaj/5/

### What does the proposed API look like?
The API would not change.

**Comment by posva** [comment]
Unless I misunderstand something, this is not possible, you're basically doing this:

```js
function a() {
    return b()
}

function b() {
    return a()
}
```

The moment you call `a` or `b`, you enter an infinite loop

Even if the computation doesn't directly depend on the other computed property (eg an if statement), the computed property cannot know what changes, it's usually less expensive to just recompute

On top of that, having two computed properties depend on each other looks weird, so I'm interested in the factual case that leads you to that situation (as summarised and direct as possible 😛 )

**Comment by HendrikJan** [comment]
Thank you.
I hope I can make this request a bit clearer, because I think you misunderstood.

The current version of Vue tries to do something like this (infinite loop):

```JavaScript
function a() {
    return {
        name: 'A',
        other_name: b().name
    }
}

function b() {
    return {
        name: 'B',
        other_name: a().name
    }
}
```

My hope is that Vue can become a bit smarter, and under the hood do this:

```JavaScript
var a = {
    name: () => 'A',
    other_name: () => b.name()
}

var b = {
    name: () => 'B',
    other_name: () => a.name()
}
```

We have the following case that leads to the infinite loop (much simplified, look at the calculation of ```course.nr_of_students``` and ```classes[i].weighting_factor```):

```JavaScript
new Vue({
    data: {
        initial_course: {...} // imported via AJAX from elsewhere,
        initial_classes: [{ // example values, also included via AJAX
                nr_of_students: 10,
                // other properties of the class
            }, {
                nr_of_students: 40,
               // other properties of the class
            }];
    },
    computed: {
        course: function() {
            var course = _.clone(this.initial_course);
            course.nr_of_students: _.sumBy(this.classes, 'nr_of_students'); // <-- HERE
            return course;
        },
        classes: function() {
            var classes = this.initial_classes.map(_.clone);
            for (var i=0; i<classes.length; i++) {
                classes[i].weighting_factor = 
                    classes[i].nr_of_students / this.course.nr_of_students; // <-- HERE, example values will result in [0.2, 0.8]
            }

            return classes;
        }
    }
});
```

To get it to work, we have used the following workaround:


```JavaScript
new Vue({
    data: {
        initial_course: {...} // imported via AJAX from elsewhere,
        initial_classes: [{ // example values, also included via AJAX
                nr_of_students: 10,
                // other properties of the class
            }, {
                nr_of_students: 40,
               // other properties of the class
            }];
    },
    computed: {
        course: function() {
            var course = _.clone(this.initial_course);
            return course;
        },
        course_nr_of_students: function() {
            return _.sumBy(this.classes, 'nr_of_students');
        },
        classes: function() {
            var classes = this.initial_classes.map(_.clone);
            for (var i=0; i<classes.length; i++) {
                classes[i].weighting_factor = 
                    classes[i].nr_of_students / this.course_nr_of_students; // 0.2 and 0.8
            }

            return classes;
        }
    }
});
```

**Comment by posva** [comment]
I see, thanks for the clarification. It makes sense to create an intermediary computed property to prevent an infinite loop. I imagine you can also aggregate both `classes` and `courses` in one computed property and then extract both of them in two other computed properties

**Comment by HendrikJan** [comment]
Thank you; aggregation and extraction is an interesting suggestion.

I take it that my suggested solution of changing how dependency is tracked by Vue, is to much work, not doable or will use more resources or something, since you leave the issue closed.

I am asking this because I think it is technically possible and you are probably missing what I am trying to suggest. It would make some things so much easier if intermediate calculations were not needed.
Whatever the reason, I think Vue is amazing and you are all doing a terrific job! Thank you for all your time and I will leave it at this.
