### ISSUE TITLE
vm.$forceUpdate duplicates content when childs consist of a slot followed by text

### ISSUE THREAD

**Issue by nddery** [vuejs/vue#6455]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/5k4ptmqg/89/](https://jsfiddle.net/5k4ptmqg/89/)

### Steps to reproduce
In a component render function, return an element that contains a slot directly followed by raw text.

### What is expected?
New content completely replaces the old content on re-render.

### What is actually happening?
New content is appended to the old content on re-render.

---
Seems like this was fixed for render functions compiled from templates in [2.1.5](https://github.com/vuejs/vue/releases/tag/v2.1.5).

Release notes for that version says: 

> Small across-the-board performance improvement for render functions compiled from templates. They now skip the normalization of nested children arrays based on information inferred from the templates at compile time.

I couldn't reproduce this in `.vue` files in a project generated from `vue-cli` Webpack template. JSX is affected, as can be seen in [this issue](https://github.com/skyrpex/vue-jsx-hot-loader/issues/14) and, render functions, as seen in the linked fiddle.

**Comment by yyx990803** [comment]
This has (as a side-effect) been fixed in 0529040c17b8632032a43d142aac88386f6b4a1f
