### ISSUE TITLE
sync Modifier with Template String

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue#6459]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/56602/](https://jsfiddle.net/50wL7mdz/56602/)

### Steps to reproduce
<img :src.sync="`${picPath}100X100.jpg`">

### What is expected?
it work fine

### What is actually happening?
But report [Assigning to rvalue]

**Comment by nickmessing** [comment]
@yoyo837, this is basically impossible, `.sync` modifiers allows only valid `LVal` as expression. Looks like you didn't understand what `.sync` modifier is for. Please check the documentation and if you have any questions please use official [chat](https://chat.vuejs.org) or [forum](https://forum.vuejs.org) to ask questions.

**Comment by nesterone** [comment]
Also, as far as I see in docs https://vuejs.org/v2/guide/migration.html#once-and-sync-Modifiers-on-v-bind-removed, that functionality was removed during migration from 1.x to 2.x

**Comment by LinusBorg** [comment]
Yes and no. The `.sync` modifier was removed in 2.0, but it was re-introduced agaion later, although with a different mechanic:

https://vuejs.org/v2/guide/components.html#sync-Modifier
