### ISSUE TITLE
v-if don't call destroyed lifecycle into same component

### ISSUE THREAD

**Issue by 11joselu** [vuejs/vue#6463]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/56778/](https://jsfiddle.net/50wL7mdz/56778/)

### Steps to reproduce
Play with the select and look into the console, everytime user change the model, the view is updated but the component do not call destroyed event

### What is expected?
To call destroyed event

### What is actually happening?
Destroyed event is not called

---
this is a reproduction for a reusable table component into my app, only change type (make ajax call to router /myrouter/{type} [so change data too] and title)

**Comment by LinusBorg** [comment]
You have to use a `key`, otherwise Vue will re-use the `test` component instance for efficiency.
https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key
