### ISSUE TITLE
Add a comparison with moon

### ISSUE THREAD

**Issue by sametmax** [vuejs/vue#6464]
### What problem does this feature solve?
Lately, the moon framework (http://moonjs.ga/) has had some good PR, and is probably the most direct competitor to Vue has the syntax, size and perfs are very similar.

### What does the proposed API look like?
It would be nice to have an entry in https://vuejs.org/v2/guide/comparison.html about it.

**Comment by numfin** [comment]
try to compare ecosystem first lol

**Comment by romshark** [comment]
I believe it's Moon that needs to compare itself to Vue and not the other way around for obvious reasons.

**Comment by posva** [comment]
Please, can you move this to vuejs/vuejs.org ?
I don't know if anyone in the team knows Moon enough to make the comparison. As much as I like the idea of Moon, I don't think it's used enough to add an entry on the page... It's not about comparing to every possible framework but rather compare it to what people might be choosing to use in the same scenario.

My personal opinion is that Moon is to Vue what Preact is to React. I'd expect to see a comparison on Moon's github or website
