### ISSUE TITLE
v-for empty dom wrapper

### ISSUE THREAD

**Issue by teddyarmagedon** [vuejs/vue#6470]
### What problem does this feature solve?
i want to generate two objects of dom(```<tr>```) per single object

### What does the proposed API look like?
```
<v-for-empty v-for="(some,index) in ob" v-bind:key="index">
  <tr>
    <td>data 1</td>
    <td>data 2</td>
  </tr>
  <tr>
    <td colspan="2">
              other type of data
            </td>
  </tr>
</v-for-empty>
```

would render 
```
<tr>
            <td>data 1</td>
            <td>data 2</td>
          </tr>
          <tr>
            <td colspan="2">
              other type of data
            </td>
          </tr>
```

**Comment by sqal** [comment]
You can easily do it by using functional component - https://vuejs.org/v2/guide/render-function.html#Functional-Components

demo: https://jsfiddle.net/9qb8fgmw/

**Comment by javoski** [comment]
You can just use `<template>`.

**Comment by teddyarmagedon** [comment]
thanks a lot 👍

**Comment by teddyarmagedon** [comment]
i have same version as you vue v2.4.2
seems to work as expected if using one child (not what i want)
```

<div data-v-726bd678="">foo</div>
<div data-v-726bd678="">bar</div>

render (h, ctx) {
          const { props } = ctx
          const { data } = props
          return h('div', data.name)
        }
```
but can't get to work with multiple childs, i get:

```
"undefined"
"undefined"
```

```
TableRows: {

        functional: true,
        render (h, ctx) {
          const { props } = ctx
          const { data } = props
          return [h('div', data.name),h('div', data.name)]
        }
      }
```

**Comment by BinarySpike** [comment]
> You can just use `<template>`.

I'm using Vue 3 + Vue-cli and eslint is complaining that you can't `:key` `<template>`.

However, when ignoring the eslint issue, it works fine:
```vue
<template v-for="(a, i) in new Array(5)" :key="i">
  {{ i }} <br />
</template>
```
result:
```
0
1
2
3
4
```
