### ISSUE TITLE
Using Vue with es6 & es6 Modules

### ISSUE THREAD

**Issue by backspaces** [vuejs/vue#6472]
### Version
2.4.2

### Reproduction link
[https://github.com/backspaces/asx](https://github.com/backspaces/asx)

### Steps to reproduce
Search SO & Forum for modern browser/javascript usage. No modern browser/javascript usage is discussed. Posted questions on both with no answer. For example, the "simple" cli template could easily be used for minimal .vue file transpiling into es6 friendly output.

### What is expected?
Documentation. For example, if using the cli, how do I avoid babel transpiling to es5 and bundling to remove es6 module use.

### What is actually happening?
No luck so far, no answers to questions. Possibly this is simply a documentation issue? Or is es6/Modules use currently simply not possible with Vue

---
The url is simply my main repo and does not use Vue yet because it is:
- es6 & Module based with a temporary dual build for legacy (es5/bundling)
- My workflow is strictly npm run scripts and node scripts. They do call Rollup for example but are not built on a task manager.

See:
https://medium.com/@backspaces/es6-modules-part-1-migration-strategy-a48de0b7f112
https://medium.com/@backspaces/es6-modules-part-2-libs-wrap-em-up-8715e116d690

My documentation is Docsify based which I believe is built on Vue.
- http://backspaces.github.io/asx/#/

**Comment by yyx990803** [comment]
I'm sorry but I don't really understand your problem. The Vue ecosystem simply provides libraries distributed as NPM packages and a default workflow in our CLI templates (bundling ES6 code into ES5 for distribution).

If you want to avoid transpiling to es5, that is a Babel configuration question; if you want to use es6 modules directly in the browser, that is a generic workflow question (framework agnostic) and should not be reported here.

**Comment by LinusBorg** [comment]
For the record, we provide an esm build which is actually the default export of our npm package.

I'll go ahead and try to interpret what I think you are really asking: *"How can can I transform .vue files inso ES6 modules without having them bundled by webpack or browserify?"*

The answer would be `github.com/vuejs/rollup-plugin-vue`, for the most part.

**Comment by backspaces** [comment]
> I'm sorry but I don't really understand your problem. 

I want to be able to use Vue, transforming .vue files with no es5 transpiling and no bundling which removes Modules. I want to do this with the Vue cli without configuring webpack or babel.

> The Vue ecosystem simply provides libraries distributed as NPM packages and a default workflow in our CLI templates (bundling ES6 code into ES5 for distribution).

I do not *want* to use webpack or babel, at least not directly. I want the Vue cli to have options so that I can use just it with no webpack or babel .. except for .vue transformations. 

> If you want to avoid transpiling to es5, that is a Babel configuration question; if you want to use es6 modules directly in the browser, that is a generic workflow question (framework agnostic) and should not be reported here.

I do not think I'm asking for something unreasonable. I admit that I am ignorant of the details of how .vue files are eventually converted to vanilla html/css/js, but I want a very simple solution to their use in a modern browser (Chrome, Safari, Canary) which have native Modules and full es6/7 support with no need for unnecessary workflow.

**Comment by backspaces** [comment]
> How can can I transform .vue files into ES6 modules without having them bundled by webpack or browserify, so I can use them in my own build process?

Yup.
