### ISSUE TITLE
Unclear which unit test to run

### ISSUE THREAD

**Issue by nddery** [vuejs/vue#6475]
### Version
2.4.2

### Steps to reproduce
The contributing guide says to ensure tests passes before opening a PR. [npm run test](https://github.com/vuejs/vue/blob/dev/package.json#L26) runs the `test:cover` tests, while [npm run dev:test](https://github.com/vuejs/vue/blob/dev/package.json#L18) run the `test:unit` tests - the former passes correctly while the latter fails with a lof or errors - not sure which one should be run or if they should all pass - CircleCI seems to only run `npm run test` (so `test:cover`).

### What is expected?
Tests should be the same for both dev/watch command and running the whole suite.

### What is actually happening?
dev/watch loads a different Karma configuration file than when running the whole suite

**Comment by yyx990803** [comment]
They are the same tests, the only difference is which browser they are running in. Unfortunately when running in Chrome, there are some flakiness related to the launcher (e.g. if you switch the window after launching the test from the terminal, the launched Chrome is considered to be in background mode and throttles animations, thus causing some of the transition/animation tests to fail). In most cases, the default `npm test` is more stable and should be used as a reference.
