### ISSUE TITLE
麻烦问下，我用了select组件之后，选择切换option时无法切换元素，我看下了下，绑定的value值和key值是不一样的，麻烦大神解答下

### ISSUE THREAD

**Issue by jingleding** [vuejs/vue#6476]
### Version
2.2.6

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
<el-select class="sel-cate" v-model="order.category1Id" @change="getCategoryPubByParentIdAndSite(2, $event)">
                  <el-option
                      v-for="item in category1Obj"
                      :key="item.virtualId"
                      :label="item.virtualName"
                      :value="item.virtualId">
                  </el-option>
                </el-select>
                <el-select class="sel-cate" v-model="order.category2Id" @change="getCategoryPubByParentIdAndSite(3, $event)">
                  <el-option
                      v-for="item in category2Obj"
                      :key="item.categoryId"
                      :label="item.categoryName"
                      :value="item.categoryId">
                  </el-option>
                </el-select>
                <el-select class="sel-cate" v-model="order.category3Id">
                  <el-option
                      v-for="item in category3Obj"
                      :key="item.categoryId"
                      :label="item.categoryName"
                      :value="item.categoryId">
                  </el-option>
                </el-select>

### What is expected?
期望可以切换option

### What is actually happening?
无法切换，而且change事件也没有触发

---
上面的网址是随便写的，不好意思，因为没有上传到远程服务器

**Comment by Justineo** [comment]
1. 请遵守 issue 提交规范；
2. 你走错地方了，请去[这里](https://elementui.github.io/issue-generator)。

**Comment by Leopoldthecoder** [comment]
This is not a place for reporting Element issues. Please write an online demo and issue it at https://elementui.github.io/issue-generator

@posva Please close this one.
