### ISSUE TITLE
Routes are not working in production application.

### ISSUE THREAD

**Issue by naveen84123** [vuejs/vue#6481]
### Version
2.4.2

### Reproduction link
[https://github.com/naveen84123/univue](https://github.com/naveen84123/univue)

### Steps to reproduce
 {
            path: '/content',
            component: Content,
            meta: {
                title: 'Content',
            }
        },

### What is expected?
should redirect to content route 

### What is actually happening?
route is working when i am using development server.
but in production application route stops working with error. "cannot get /content"

**Comment by LinusBorg** [comment]
1. Please open an issue in vue-router's repository.
2. Please provide a minimal reproduction, not a complete application
3. Please descibe the situation of your deployment better - did you properly configure the server to work with history mode, as explained in vue-router'S documentation?
