### ISSUE TITLE
main.js再某些机型上未运行

### ISSUE THREAD

**Issue by okxiaoliang4** [vuejs/vue#6483]
### Version
2.4.2

### Reproduction link
[http://git.oschina.net/okxiaoliang4/distribution](http://git.oschina.net/okxiaoliang4/distribution)

### Steps to reproduce
启动dev server之后再iphone5上main.js未运行

### What is actually happening?
启动dev server之后再iphone5上main.js未运行

**Comment by yyx990803** [comment]
请不要直接丢一坨代码指望别人帮你改... 至少讲清楚你这坨代码怎么来的。
