### ISSUE TITLE
contenteditable problem

### ISSUE THREAD

**Issue by paksung** [vuejs/vue#6484]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/0anc0kko/](https://jsfiddle.net/0anc0kko/)

### Steps to reproduce
if you set an attribute contenteditable="plaintext-only",it will change to contenteditable="true"

### What is expected?
contenteditable="plaintext-only"

### What is actually happening?
contenteditable="true"

**Comment by posva** [comment]
`plaintext-only` is not a valid value for contenteditable, only `true` and `false` are valid: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
