### ISSUE TITLE
I'm writing in a template, watch to a function, But now need to unwatch  while leaving the component

### ISSUE THREAD

**Issue by jxZhangLi** [vuejs/vue#6485]
![image](https://user-images.githubusercontent.com/16809535/29917370-5ff42ae0-8e74-11e7-8c36-a73c182728c1.png)

**Comment by jxZhangLi** [comment]
I didn't find the relevant cancellation API in the document

**Comment by javoski** [comment]
Hi, you can use `vm.$watch` instead of option `watch` - [https://vuejs.org/v2/api/#vm-watch](https://vuejs.org/v2/api/#vm-watch).

**Comment by jxZhangLi** [comment]
@javoski   thank you

**Comment by jxZhangLi** [comment]
I want to ask, Many functions are monitored in each component, does this affect performance @javoski
