### ISSUE TITLE
There is no  'unwatch'  event in the server  write （template）

### ISSUE THREAD

**Issue by jxZhangLi** [vuejs/vue#6486]
### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue/issues/6485](https://github.com/vuejs/vue/issues/6485)

### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue/issues/6485](https://github.com/vuejs/vue/issues/6485)

### What is expected?
I'm writing in a template, watch to a function, But now need to unwatch while leaving the component

### What is actually happening?
I didn't find the relevant cancellation API in the document

**Comment by jxZhangLi** [comment]
我在template编写组件中监听了一个滚动的值，我需要在离开这个组件的时候，取消监听。不取消这样可能会消耗性能，我在每一个页面都监听了这个事件的。我在文档中没有看到template 服务端可以取消监听的方法。

**Comment by gebilaoxiong** [comment]
抱歉，这个问题不属于 issues 的范畴。
