### ISSUE TITLE
SSR   v-html   svg   default content => server/client mismatch

### ISSUE THREAD

**Issue by cjblomqvist** [vuejs/vue#6490]
### Version
2.4.2

### Reproduction link
[http://www.doesntexist.com](http://www.doesntexist.com)

### Steps to reproduce
```html
<span v-html="svg.logo">Some text</span>
```

Where svg.logo equals a SVG image

### What is expected?
server and client to be equal

### What is actually happening?
I get mismatch. Some error mentioning a text node.

---
When "Some text" is removed, it works fine. Using SSR, "Some text" is not needed, so it's a simple fix to remove it. However, it's a little bit strange it doesn't work and turn into a mismatch.

I unfortunately don't have time to create a proper repro and so forth. If you want to close this issue immediately, then that's fine. The purpose is more to inform you (and others who have the same issue) that this can happen with SSR.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by nickmessing** [comment]
Closing in favor of #6519, I see three potential solutions, need some feedback from core team to figure out which one is the best.

**Comment by cjblomqvist** [comment]
Agree #6519 is a much better issue than mine - glad you are picking it up from there!
