### ISSUE TITLE
VNode.child and VNode.children are undefined

### ISSUE THREAD

**Issue by truefusion** [vuejs/vue#6492]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/7u72L3r0/1/](https://jsfiddle.net/7u72L3r0/1/)

### Steps to reproduce
I could only reproduce this issue with nested children components, that is, with components that are deeper in the DOM than root > children. In other words, root > children > **[[children]]** are observed to be problematic.

### What is expected?
Either VNode.child or VNode.children or both to give me access to VueComponents or something that permits me access to VueComponents.

### What is actually happening?
Though the component has children, they are undefined in the returned VNode.

---
I see this as an issue because VNode does not appear to accurately represent DOM in regards to Vue components, and this creates difficulty in development. My project makes use of slots, therefore permitting for replaceable parts. My project also depends on the need to listen to events emitted by these replaceable parts and to be able to make calls to their methods, but the VNodes returned by the slots mechanism is not permitting me to access these VueComponents that I may listen to the events of those components and make method calls. If there is a way to fulfill my project goals, I am unaware of it.

**Comment by posva** [comment]
You have to give the slot a `name`:

```html
<template id="child">
  <div>
    <slot name="belly"></slot>
  </div>
</template>
```
