### ISSUE TITLE
Array no update

### ISSUE THREAD

**Issue by f1729** [vuejs/vue#6493]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/58103/](https://jsfiddle.net/50wL7mdz/58103/)

### Steps to reproduce
- Wait mounted aplication, no change array
- Not even when clicking
- The changes are not reflected in the DOM

### What is expected?
Should reflect changes in the DOM

### What is actually happening?
The changes are not reflected in the DOM

---
I am not sure if it is the correct way to reflect the changes, if so I would like to know the ideal way to do it, thank you very much.

**Comment by posva** [comment]
Hello,

This is working as intended. You'll find a better explanation [here](http://vuejs.org/guide/list.html#Caveats) :smile:
