### ISSUE TITLE
Can't restart data in component 

### ISSUE THREAD

**Issue by DenisLapi** [vuejs/vue#6495]
### Version
2.3.2

### Reproduction link
-/-

### Steps to reproduce
I have a problem to force a restart on new route

I have an route `/editor` but also `/editor?_id=dasd448846acsca`

- `/editor` is simple component with form with empty inputs
- `/editor?_id=dasd448846acsca` this component is the same as `/editor` but just with filled inputs from DB

I want to be able to open `/editor` component with empty inputs from component 
`/editor?_id=dasd448846acsca`

I used `this.$router.push('editor'); this.$forceUpdate();` in function and route is changed, but data in restarted (inputs are not empty)

### What is expected?
Data is not updated/restarted

### What is actually happening?
I expect when I'm on new route with no params to have data() restarted

---
I'm not able to provide code because its very complicate, sorry!

**Comment by LinusBorg** [comment]
1. This is the repository for Vue, but your question is about vue-router.
2. Issues are not for usage questions, we have forum.vuejs.org and chat.vuejs.org for that
4. your issue doesn't match the requirements as it's missing a reproduction.
