### ISSUE TITLE
Custom validation message for props

### ISSUE THREAD

**Issue by b4dnewz** [vuejs/vue#6496]
### What problem does this feature solve?
Let the developer (specially when using third party components/plugins) understand __why__ the error happen, in a more detailed, customizable and friendly way. Where the error came from is already known thanks to the code line dump (as in below example).

---

When validating a component property you have to return true or false in order to fulfill the validation, if it fails the console error looks like: 

```bash
"[Vue warn]: Invalid prop: custom validator check failed for prop "example"."
found in

---> <WordCount> at src/components/WordCount/WordCount.vue
       <App> at src/App.vue
         <Root>
```

I think is a very generic warning and also the line dump where the error came from, is very useful but a custom error message could be more useful, in my opinion.

Obviously since the validation function is custom and it may vary for every prop, is very difficult to predict or deduct which warning message to display based on the code, so let the developer do it if possible.

---

Mine proposal is to add a "message" or "whatever" field to the prop object properties, which can be used a validator function is called against the prop input and it fails, if no "message" property is provided than the generic warning will show up instead.

Documentation about component props.
https://vuejs.org/v2/guide/components.html#Prop-Validation

Validation requirements object:
```
{
 type: String,
 required: true,
 default: '',
 validator: (value) => /^[a-zA-Z]+$/.test(value),
 message: 'You can use only letters'   <-------------- new validation error message property
}
```

Another use-case example:

A component property must be a 4 digit string and the validation function is:
```
function(value) {
 return value.length === 4
}
```

The "message" property in this case would be "You must enter a 4 digit number", so if the developer use the component like this:
```html
<my-comp example="123"></my-comp>
```

The custom warning message shows up and the developer knows immediately which is the issue, this obviously work if the custom component developer used the "message" property to set a custom validation error message.

### What does the proposed API look like?
When a custom validation function is used and it fails, the custom property validation message shows up as warning to show to the developer what is wrong.

```javascript
props: {
    code: {
      type: String,
      validator(value) {
        return value.length === 4
      },
      message: 'You must enter a 4 digit number'
    }
}
```
What do you think about that?

I hope I didn't make a mess explaining this and is clear, if any doubt I will provide more details and use case example.

Many thanks in advance and many thanks for building Vue that is __simply awesome__.

**Comment by LinusBorg** [comment]
what is wrong with using the console youself?

**Comment by b4dnewz** [comment]
You mean like this?
```javascript
validator(value) {
   if( value.length !== 4 ) {
     console.warn('You must enter a 4 digit number')
     return false
   }
   return true
},
```
I didn't think about it, I guess it could be a solution.

But I can see two eventual problems, firstly most of the times vue comes with eslinting (like in vue init) and console messages are usually disabled, secondly this console message will be added to the existing one which will always output a generic error and it can cause confusion, compared to a message like this (as per the example above):

```bash
"[Vue warn]: Invalid prop: You must enter a 4 digit number for prop "example"."
found in

---> <WordCount> at src/components/WordCount/WordCount.vue
       <App> at src/App.vue
         <Root>
```

where the pattern may be (or something similar):
```bash
"[Vue warn]: Invalid prop: <message> for prop "<prop>"."
found in

---> <WordCount> at src/components/WordCount/WordCount.vue
       <App> at src/App.vue
         <Root>
```
if the developer wants to use a custom message it will be displayed, otherwise the default message `custom validator check failed for` is displayed like always.

**Comment by HerringtonDarkholme** [comment]
Note `validator` and `warn` is called synchronously. So when you call console.error in validator, it is immediately before Vue's builtin warning.

![screenshot from 2017-09-03 20-42-26](https://user-images.githubusercontent.com/2883231/30002937-70514442-90e8-11e7-87eb-43ed22157397.png)

This warning is good enough for me.

**Comment by b4dnewz** [comment]
@HerringtonDarkholme good point

**Comment by bitmage** [comment]
The built in message would be far more useful if it told me what the prop value was that was passed in.  That's obvious information to include IMO, and would fulfill probably 80% of people's need to have a custom message as indicated here.

**Comment by LittaPanda** [comment]
More than a console message, maybe a mechanism to handle the error would be useful for this case.
Some attribute in prop that can callback if validation returns an error.
Just my two cents.
Regards!

**Comment by AllanOricil** [comment]
@yyx990803 is there a way of achieving this? I have a use case which I have a prop of type Array, which all entries must be objects containing two specific keys (label and value). If the developer passes a wrong array I would like to show a better message. One that explains what his is actually missing. Should I throw an exception inside the `validator`  to implement it?

**Comment by lbzg** [comment]
It would be nice to have a way of creating a custom message, my current solution goes something like this. It allows me to define an error message for each validation error.

```
const propValidator = (config) => (input) => {
  const error = Object.entries(config).find((v) => v[1](input))?.[0];
  return error ? console.warn(error) : true;
};

export default {
  props: {
    hash: {
      type: String,
      validator: propValidator({
        "Hash should start with a '#' character": (input) => input[0] !== "#",
      }),
    },
  }
}
```

Is there any chance we can get a similar solution by default? It would be as simple as checking if validator exists and if its an object or a function.
If something similar is even worth implementing.
