### ISSUE TITLE
":class" removes classes added programmatically

### ISSUE THREAD

**Issue by igidas** [vuejs/vue#6497]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/g2annvu5/](https://jsfiddle.net/g2annvu5/)

### Steps to reproduce
Click "Change color" and inspect DOM

### What is expected?
Component "test" should have "redBg" and "blueTxt" classes.

### What is actually happening?
Component "test" has only "redBg" class.

---
I found this bug by using custom directive, which adds flex layout related classes to element. Classes added by directive were removed if element had ":class" defined in template.
If this is intentional, are there some workarounds to add/remove classes via native DOM methods?

**Comment by posva** [comment]
dup of #5677
