### ISSUE TITLE
组件在前后dom节点的v-if指令更新时导致组件也更新

### ISSUE THREAD

**Issue by chenfengjw163** [vuejs/vue#6499]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chenfeng/h2zcmwnm/6/](https://jsfiddle.net/chenfeng/h2zcmwnm/6/)

### Steps to reproduce
```

<div id="app">
  <div v-if="show">
    div1
  </div>
  <demo></demo>
  <div v-if="show">
    div2
  </div>
</div>
```
如上结构，show更新时会导致demo组件重新渲染

### What is expected?
demo组件和v-if指令无关时不能刷新

### What is actually happening?
show更新时会导致demo组件重新渲染

**Comment by yyx990803** [comment]
You are using an old version (2.2.6). This does not happen in latest version (2.4.2)
