### ISSUE TITLE
Add license settings on package.json when executing `vue-init`

### ISSUE THREAD

**Issue by shigemk2** [vuejs/vue#6500]
### What problem does this feature solve?
We can choose license on package.json when executing `vue-init`. 
We don't have settings when executing `vue init` with vuejs's official templates.

But I know it is not vuejs's issue directly, but all official templates don't have settings for license in package.json.
I want to pull-requests to meta.json/meta.js/package.json in all official templates.

### What does the proposed API look like?
None.

**Comment by yyx990803** [comment]
The difference is that projects created via `vue init` may be private and not intended for public use, so a license isn't necessary in those cases (it's about copyrights in those cases), and it doesn't make sense to require a license for every project. If you intend to make your code public, just add the license field yourself.
