### ISSUE TITLE
Ability for destructuring in template

### ISSUE THREAD

**Issue by doggerFrankXu** [vuejs/vue#6501]
### What problem does this feature solve?
having local variables in template and write little bit less code 

    computed: {
        originalProp () {
            return {
                propA: 'A',
                propB: 'B'
            }
        }
    }

if I want to use propA in template, then I shall write

    <template>
        <div>{{originalProp.propA}}</div>
    </template>

if we can do deconstruction in template, there would be less code like

    <template v-deconstruct:originalProp="{propA, propB}">
        <div>{{propA}}</div>
    </template>

and I find that the `scope` directive of `slot` already has the abitlity for deconstruction,
for exapmle

    <template slot="item" scope="{originalProp:[propA, propB]}">
        <div>{{propA}}</div>
    </template>

### What does the proposed API look like?
    <template v-deconstruct:originalProp="{propA, propB}">
        <div>{{propA}}</div>
    </template>

**Comment by yyx990803** [comment]
Thanks for the suggestion, but IMO this feature does not add significant benefits to warrant its addition. It's essentially "just so that we can write a little less code" vs. "yet another API to remember".
