### ISSUE TITLE
An optimization scheme for ssr

### ISSUE THREAD

**Issue by ErosZy** [vuejs/vue#6504]
### What problem does this feature solve?
I found a ui library named [marko](https://github.com/marko-js/marko), its ssr render is so fast. I looked under his source, it create ast firstly, and then compile to tpl engine(ssr env) or virtual dom(browser env). In my practical application, ssr's performance bottlenecks are limited by virtual dom, and it also causing some memory leaks.
vue's tpl grammar is a dsl, we can learn from  [marko](https://github.com/marko-js/marko)，using ast to compile to tpl engine or virtual dom，for the data, we create vue object without letting him generate virtual dom in ssr env.
I think this approach is logically feasible, but I do not know if there is some difficulty with the current vue version.

thanks.

### What does the proposed API look like?
none

**Comment by yyx990803** [comment]
See comment on your previous issue. Vue already implements similar optimizations in 2.4.
