### ISSUE TITLE
<a> tag is wrongly assumed to be in html namespace instead of svg

### ISSUE THREAD

**Issue by roblabla** [vuejs/vue#6506]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/4s3hj82k/](https://jsfiddle.net/4s3hj82k/)

### Steps to reproduce
1. Create a template using <a> as the root element

2. Try to use it in an <svg>

### What is expected?
I either expected vue to understand that the <a> is supposed to be an SVG a tag (and not an xhtml a tag), or a way for me to override vue's decision and give it the proper namespace (e.g. making <svg:a> work ?)

### What is actually happening?
Vue is creating the <a> tag as an xhtml:a tag, and so the browser doesn't render it.

You can make it render by wrapping it in an <svg>. This is undesirable however, for many reasons. Having a way to explicitly tell vue the namespace from which to create the element would be nice.

---
SVG &lt;a&gt; tag : https://developer.mozilla.org/fr/docs/Web/SVG/Element/a

**Comment by yyx990803** [comment]
Please provide an actual reproduction.

**Comment by roblabla** [comment]
What's wrong with the repro link @yyx990803 ?

**Comment by roblabla** [comment]
Woops, looks like I messed up the link copy pasting ? Anyway, trying to put one back up together.

**Comment by roblabla** [comment]
Here's the repro : https://jsfiddle.net/4s3hj82k/
