### ISSUE TITLE
Passing object as prop changes in parent component when changed in child without sync

### ISSUE THREAD

**Issue by revati** [vuejs/vue#6507]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/revati/xpopmjrg/1/](https://jsfiddle.net/revati/xpopmjrg/1/)

### Steps to reproduce
In jsfiddle there are simplest code 

### What is expected?
I were expceting that parent component wount change its data, as i werent passed .sync

### What is actually happening?
Parent component changed its value

---
Prop is treated as reference not as value as i can understand

**Comment by jkzing** [comment]
Yes, **it is** work in this way. You can read [https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow](https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow) for more information.

**Comment by yyx990803** [comment]
This is intended behavior. Please read the linked docs above for more details.

**Comment by revati** [comment]
Oh, thanks, didn't know that. 
What then is best practice to pass it as value. 
As i understand it should be cloned before passing to child component.
