### ISSUE TITLE
how to set template to scope or not

### ISSUE THREAD

**Issue by lerit** [vuejs/vue#6508]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/ofny2qmz/](https://jsfiddle.net/ofny2qmz/)

### Steps to reproduce
open the reproduction

### What is expected?
i want to  set template to a common template or used for distributed content,maybe control it by v-if or condition scope to a name or null

### What is actually happening?
i donnot know how to set or not set the scope prop dynamic

**Comment by lerit** [comment]
https://jsfiddle.net/ofny2qmz/2/
this work for me, but i must switch condition in el-table-column
i have large number props,i do not want copy it again

**Comment by yyx990803** [comment]
This doesn't make sense to me. A slot is either scoped or not. Also, this is a question, not a bug.
