### ISSUE TITLE
Expose API to manually create cachable computed properties

### ISSUE THREAD

**Issue by th0r** [vuejs/vue#6514]
### What problem does this feature solve?
I'm trying to create state management library that will look very similar to MobX but will use Vue's built-in reactivity engine. The problem is Vue doesn't expose enough API to implement it - I need at least `Watcher` and `Dep` constructors.

### What does the proposed API look like?
Here is an example of what I'm trying to achieve:

```js
// Reactive model that uses Vue's reactivity system under the hood. That way it can be used in component's `data` objects and they'll be update automatically on any changes:

class User {
    @observable firstName = '';
    @observable lastName = '';

    constructor(data) {
      Object.assign(this, data);
    }

    @computed get fullName() {
      return `${this.firstName} ${this.lastName}`;
    }
  }
```

And here is my current implementation of `observable` and `computed` decorators:

```js
function observable(target, name, descriptor) {
    descriptor.configurable = true;

    return {
      configurable: true,
      enumerable: true,
      get() {
        // Defining original property
        Object.defineProperty(this, name, descriptor);
        // Converting it to reactive
        Vue.util.defineReactive(this, name, descriptor.initializer());
        return this[name];
      },
      set(value) {
        // Defining original property
        Object.defineProperty(this, name, descriptor);
        // Converting it to reactive
        Vue.util.defineReactive(this, name, value);
      }
    };
  }

function computed(target, name, descriptor) {
    const getter = descriptor.get;

    if (!getter) {
      console.warn(
        `${target.constructor.name}#${name} is not a getter so it can't be used as computed property`
      );
      return;
    }

    if (!target.hasOwnProperty(computedWatchers)) {
      // Creating a list of computed property names
      target[computedWatchers] = [];

      // Overriding class constructor to automatically create computed watchers
      const ctor = target.constructor;
      target.constructor = function () {
        // Needed by Vue's `Watcher` constructor
        this._watchers = [];
        this[computedWatchers] = Object.create(null);

        ctor.apply(this, arguments);
      };
      target.constructor.name = ctor.name;
    }

    target[computedWatchers].push(name);

    return {
      configurable: true,
      enumerable: true,
      get() {
        let watcher = this[computedWatchers][name];

        if (!watcher) {
          // Lazily creating computed watcher
          watcher = this[computedWatchers][name] = new Watcher(this, getter || noop, noop, { lazy: true });
        }

        if (watcher.dirty) {
          watcher.evaluate();
        }

        if (Dep.target) {
          watcher.depend();
        }

        return watcher.value;
      }
    };
  }
```

As you can see I simply borrowed Vue's `computed` implementation, but I need `Watcher` and `Dep` in order for this to work.

**Comment by yyx990803** [comment]
I feel this is out of scope for what Vue is designed to do (i.e. exposing primitives for building an alternative reactivity system, especially with different syntax requirements).

In fact, you can easily just use unmounted Vue instances as reactive data sources, similar to MobX. It doesn't sound right to me to reconstruct it just for the sake of API similarity, while requiring Vue to expand its own API surface to accommodate that.

**Comment by th0r** [comment]
> In fact, you can easily just use unmounted Vue instances as reactive data sources

Yes, I thought about that but `Vue` constructor does a lot of unnecessary view-related stuff and usage of such models is not very optimal from the performance point of view.

**Comment by yyx990803** [comment]
If you never mount it, the view-related stuff will be very minimal (only some small overhead when creating the instance)

**Comment by th0r** [comment]
> only some small overhead when creating the instance

Yes, that's exactly what I'm talking about. I want to make model instantiation as cheap as possible because there may be a lot of them.

Why can't we just expose some more internals? After all, we already have `Vue.util` with some of them. Of course I'm not asking to make them a part of public API - it will just help people like me that are trying to develop more low-level tools.

**Comment by yyx990803** [comment]
The problem with "exposing them but not a part of public API" is that either:

- your library that depends on these APIs can break without notice, because we may change internal implementations while maintaining the same public API;
- or, we avoid breaking your stuff, but at the same time we are no longer able to make any big internal changes.

I suggest you benchmark the actual overhead before asserting it's going to be too expensive.
