### ISSUE TITLE
Small typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by palashmon** [vuejs/vue#6515]
### Version
2.4.2

### Reproduction link
[Typo](http://www.dictionary.com/browse/committing)

### Steps to reproduce
Small typo in CONTRIBUTING.md.

"Commiting" should be actually "Committing" with an extra **t**.

### What is expected?
Typo fix to "Committing"

### What is actually happening?
Typo right now

**Comment by yyx990803** [comment]
Please submit PRs directly...

**Comment by palashmon** [comment]
Sure. I am on it.
