### ISSUE TITLE
Vue SSR fails with innerHTML

### ISSUE THREAD

**Issue by nickmessing** [vuejs/vue#6519]
### Version
2.4.2

### Reproduction link
[https://github.com/nickmessing/vue-ssr-issue](https://github.com/nickmessing/vue-ssr-issue)

### Steps to reproduce
Use `domPropsInnerHTML` in JSX or `v-html` in Vue Template.

Or:
* Clone the repo
* `npm install`
* `npm run dev`
* Open http://localhost:3000 and http://localhost:3000/jsx

### What is expected?
No warning in console.

### What is actually happening?
DOM Mismatching error.

---
`v-html` works fine when there are no children, but fails if there are.

One option is to completely ignore `innerHTML` and `v-html` in vue-ssr. Basically commenting [this line](https://github.com/vuejs/vue/blob/dev/src/platforms/web/server/modules/dom-props.js#L27) solves the problem.

Another option is evaluating `innerHTML` before comparing DOM snapshots so you get value from `innerHTML` on static SSR-rendered website without DOM Mismatch.

Third option is ignoring children in `createElment` if there is `innerHTML` domProp. I think this one is the best.

**Comment by yyx990803** [comment]
Probably related to #6490?

**Comment by nickmessing** [comment]
@yyx990803, yes, it's same error.

**Comment by nickmessing** [comment]
@yyx990803, thank you, will check with JSX

**Comment by yyx990803** [comment]
@nickmessing should work JSX too since `v-html` is basically an alias for `domProps: innerHTML`. Feel free to PR for a JSX test case

**Comment by panganibanpj** [comment]
Still seeing an error if i replace the `<h1>Hey</h1>` in index.vue and `<h2>Hey</h2>` in jsx.vue with with `<svg><path/></svg>`
```
server innerHTML:  <svg><path/></svg>
client innerHTML:  <svg><path></path></svg>
```

**Comment by tmorehouse** [comment]
I ran into an issue in a functional component using innerHTML to render `&times;`

SSR renders the inner HTML as `&times;`, but the browser when using innerHTML converts some entities to actual UTF-8 characters (i.e. `&times;` is converted by the browser, via innerHTML  to `×`)

Ultimately this causes rehydration to bail and re-render the component (and spew error in dev mode)

**Comment by yyx990803** [comment]
@tmorehouse please open a separate issue.

**Comment by naimlatifi5** [comment]
Hi, 
I have an issue when working on transforming data that I receive from server. Let's say that server send data as string html  content: "<h1>Hi<h1>" I want then to do some transformation in this element and add a data attribute like content:"<h1 data-name="title">Hi with data attribue</h1>" and render that in component with data attribute and ssr support. 
Any idea how can I achieve this? 
I appreciate any help!

**Comment by Alinawaz-786** [comment]
I need your help when i was using the vue js get following error

app.js:106867 [Vue warn]: Error in v-on handler: "ReferenceError:
stripeResponseHandler is not defined"

found in

---> <MessagepackageslistComponent> at
resources/js/components/MessagePackagesList.vue
       <CreditdetailComponent> at
resources/js/components/CreditDetailComponent.vue
         <Root>
warn @ app.js:106867
logError @ app.js:108126
globalHandleError @ app.js:108121
handleError @ app.js:108081
invokeWithErrorHandling @ app.js:108104
invoker @ app.js:108421
original._wrapper @ app.js:113774
app.js:108130 ReferenceError: stripeResponseHandler is not defined
    at VueComponent.stripeResponse (app.js:4295)
    at invokeWithErrorHandling (app.js:108096)
    at HTMLFormElement.invoker (app.js:108421)
    at HTMLFormElement.original._wrapper (app.js:113774)
logError @ app.js:108130
globalHandleError @ app.js:108121
handleError @ app.js:108081
invokeWithErrorHandling @ app.js:108104
invoker @ app.js:108421
original._wrapper @ app.js:113774
(index):3 Uncaught Error: Your key is invalid, as it contains whitespace.
For more info, see https://stripe.com/docs/stripe.js
    at Function.b.validateKey ((index):3)
    at Function.b.create ((index):2)
    at Function.c.createToken ((index):2)
    at HTMLFormElement.<anonymous> (app.js:4222)
    at HTMLFormElement.dispatch (app.js:22950)
    at HTMLFormElement.elemData.handle (app.js:22757)


how to solved thie error
