### ISSUE TITLE
The parent component closes the child component capture 'removeEventListener' of null about TypeError

### ISSUE THREAD

**Issue by the-last** [vuejs/vue#6521]
### What problem does this feature solve?
Hello, every senior, thank you for watch my issue.

Issue: TypeError about Cannot read property 'removeEventListener' of null from VueComponent .beforeDestory.

Description: when i optioned the parent component button close child-component dialog, i will capture this warning about 'removeEventListener' of null when parent component close children component.

### What does the proposed API look like?
My opinion: i think the issue maybe threw by vue frame. my opinion that parent-component should have remove monitor when sub-component closed. Therefore, i want get the reason about this warning.

**Comment by yyx990803** [comment]
This is not a feature request. Please use the bug report format and provide a **reproduction**.

**Comment by the-last** [comment]
I will push/tip it again these days.  Thank your comment so so so much..
