### ISSUE TITLE
add the passive event decorator

### ISSUE THREAD

**Issue by marjune163** [vuejs/vue#6523]
### What problem does this feature solve?
we have event.capture now, what about add a event.passive ?
which means on the low level is: element.addEventListener('event', fn, {passive:true});

### What does the proposed API look like?
```
<div v-on:click.passive="onClick">...</div>
```

**Comment by javoski** [comment]
`.passive` modifier has been supported since v2.3.0+. [https://vuejs.org/v2/api/#v-on](https://vuejs.org/v2/api/#v-on)

**Comment by marjune163** [comment]
then please update the tutorial document, it doesn't contains the passive modifier:
https://vuejs.org/v2/guide/events.html#Event-Modifiers

**Comment by chrisvfritz** [comment]
Will add. 👍
