### ISSUE TITLE
Cannot disable productionTip when Vue is imported in multiple entry points

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#6528]
### Version
2.4.2

### Reproduction link
https://github.com/vuejs-templates/pwa

### Steps to reproduce

1. Clone official vue-pwa template
2. Add one more entry point in line [#L12](https://github.com/vuejs-templates/pwa/blob/master/template/build/webpack.base.conf.js#L12) which includes vue

```
entry: {
  app: './src/main.js',
  vendor: ['vue']
}
```

3. Run `npm run dev` and check console. You can see that although  `productionTip` option is disabled in `main.js`, the warning still appears in the console.

### What is expected?
`config.productionTip` to working properly

### What is actually happening?
When vue is imported in multiple entry points, it's impossible to disable productionTip.

**Comment by sqal** [comment]
Not sure what is missing :(

**Comment by yyx990803** [comment]
If I'm not mistaken, your above config creates a separate bundle which includes a duplicated copy of Vue, and both bundles are included, so you are loading two copies on Vue on your page. You are only disabling the warning for the copy in the main entry bundle.

See [webpack docs](https://webpack.js.org/plugins/commons-chunk-plugin/#explicit-vendor-chunk) for proper vendor chunk splitting.

**Comment by queensGambyte** [comment]
So, Using webpack's uglify js plugin is removing the dead code from if blocks using `"development" !== 'production'` flag. But, the same flag in productionTip and devtools in Vue.config are set to true(!0 to be precise). 

For now, I am using this to remove these annoying loggers 
`if(process.env.NODE_ENV === 'production') {
    Vue.config.productionTip = false;
    Vue.config.devtools = false;
}`


Shouldn't config props which are resolved from `"development" !== 'production'`, be added like this-
`Vue.config = { 
  productionTip: false,
  devtools: false
};
if("development" !== 'production') {
  Vue.config.productionTip = true;
  Vue.config.devtools = true;
}`

Or, Am I missing something in the uglify plugin?
