### ISSUE TITLE
Vue equivalent for Gatsbyjs in react

### ISSUE THREAD

**Issue by Thebigbignooby** [vuejs/vue#6529]
### What problem does this feature solve?
static site generator using vuejs like gatsby does with react

### What does the proposed API look like?
Not sure if this is the right place to ask about this, point me in the right place if it isn't.

**Comment by phanan** [comment]
> point me in the right place if it isn't.

That would be the [forum](https://forum.vuejs.org/).

**Comment by posva** [comment]
It is not the right place to ask this kind of things 😛 I don't know what would be the right place, Twitter, Discord, the Forum?

I'm sure people have created tools like that, there's probably a Nuxt plugin for that. I recommend you to look it up

**Comment by yyx990803** [comment]
You can use nuxt generate for that.
