### ISSUE TITLE
异步组件导致生命周期钩子函数执行顺序不正确

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6533]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/j0q12fsh/22/](https://jsfiddle.net/j0q12fsh/22/)

### Steps to reproduce
请先理解官方mounted钩子的注释:
注意 mounted 不会承诺所有的子组件也都一起被挂载。如果你希望等到整个视图都渲染完毕，可以用 vm.$nextTick 替换掉 mounted

### What is expected?
正常顺序应该1,2,3,4

### What is actually happening?
实际顺序显示为2,4,1,3

**Comment by yyx990803** [comment]
请先理解异步组件是干嘛的 - 异步的子组件不会影响父组件生命周期的触发时间。一旦异步了顺序就没有任何保证了。

**Comment by yangdan8** [comment]
我的建议是起码父组件应该要有一个类似非异步组件的$nextTick的东西或者事件,知道子组件已经渲染完成.

**Comment by yyx990803** [comment]
...子组件传个事件就行了

**Comment by yangdan8** [comment]
好的,谢谢!请关注另外一个由这个引起的兄弟组件通信问题
