### ISSUE TITLE
异步组件导致无法实现兄弟组件通信

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6534]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/j0q12fsh/23/](https://jsfiddle.net/j0q12fsh/23/)

### Steps to reproduce
执行运行代码看弹出信息

### What is expected?
正常弹出应该[object object]

### What is actually happening?
实际弹出为undefined

**Comment by yyx990803** [comment]
...这是预期行为。异步组件互相之间的 mounted hook 没有任何顺序上的保证。

**Comment by yangdan8** [comment]
我的建议是起码父组件应该要有一个类似非异步组件的$nextTick的东西或者事件,知道子组件已经渲染完成.

**Comment by yangdan8** [comment]
**前提：**父组件为P,有两个子异步组件S1和S2.
**问题：**S1在mounted后要操作S2的方法,而此时S2可能还未渲染,S1触发P的自定义事件也没有用。
**临时解决方案：** S1和S2在mounted后先在P中登记需要触发兄弟组件通信的事件E1写入异步事件队列DS,
之后触发P中的自定义事件E2登记"我已经渲染好了",
然后遍历出队异步事件队列DS执行触发,
而事件队列DS中的每一项自己去检测需要的子组件是否加载完成,
如果加载完成执行即可,没有加载完成重新入队。
**建议：**生命周期添加所有异步子组件渲染完成事件,期待更好的解决方案。

**Comment by yyx990803** [comment]
异步之间的事件流程管理不属于 Vue 的职责范畴，完全可以用第三方库比如 eventproxy 去解决。

**Comment by yangdan8** [comment]
好吧,谢谢了
