### ISSUE TITLE
Individual componenets could have @click

### ISSUE THREAD

**Issue by azurinko** [vuejs/vue#6539]
### What problem does this feature solve?
Making individual componenets having @click event as whole component, I tought that's some of the reasons it must be all wrapped in one tag, but it does not work...

Example:
test.vue: [
```
<template>
  <div>
    <anotherTest @click="a" />
  </div>
</template>
<script>
import anotherTest from './test/anotherTest'
export default {
  components: {
    component
  },
  name: 'test',
  methods: {
    a: function() {
      console.log("CLICKED")
    }
  }
}
</script>
<style>
</style>
```
]

'./test/anotherTest.vue': [ 
```
<template>
  <div>
    TEST,
    TEST,
    TEST
  </div>
</template>
<script>
export default {
  name: 'anotherComponent',
}
</script>
<style>
</style>
```
]

It could make workflow at certain places more reasonable.

### What does the proposed API look like?
Even vue components should have event handlers, and that handlers could be passed to main wrapping element of component template... See example above.

**Comment by yyx990803** [comment]
https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components
