### ISSUE TITLE
Wrong docs/default export for TypeScript

### ISSUE THREAD

**Issue by krenor** [vuejs/vue#6540]
### Version
2.4.2

### Reproduction link
[https://pastebin.com/DQQtdyBB](https://pastebin.com/DQQtdyBB)

### Steps to reproduce
1. Webpack the Typescript to javascript
2. Visit the site with the included javascript

### What is expected?
`console.dir()` should anything other than `undefined` to indicate that Vue is loaded and ready to use.

### What is actually happening?
`console.dir()`: `undefined`

With the following error:

```
app.js:83 Uncaught TypeError: vue_1.Vue is not a constructor
    at Object._toString (app.js:83)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:70)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66
```

---
You've stated on your website the following:

>In Vue 2.2.0  we introduced dist files exposed as ES modules, which will be used by default by webpack 2. Unfortunately, this introduced an unintentional breaking change because with TypeScript   webpack 2, import Vue = require('vue') will now return a synthetic ES module object instead of Vue itself.

However, even though the `allowSyntheticDefaultImports` setting was set to true (full settings: https://pastebin.com/4zASRxyr), I couldn't get it working with the import statement. Tried using the `import Vue = require("vue")` it works. Is this an error regarding the docs or an actual error because the default export is missing?

**Comment by ktsn** [comment]
Could you provide minimal/whole project that reproduces the error? I cannot find any problems in your code and tsconfig.

**Comment by krenor** [comment]
Seems to be rather be an issue with [laravel-mix](https://github.com/JeffreyWay/laravel-mix/issues/1178) than Vue itself.
