### ISSUE TITLE
Explicit name for default transition mode

### ISSUE THREAD

**Issue by ydnar** [vuejs/vue#6542]
### What problem does this feature solve?
There are currently 3 transition modes, default (unnamed), `in-out`, and `out-in`. There’s no documented method to programmatically specify the default transition mode. Current code warns if transition mode is set to any value other than `in-out` or `out-in`: https://github.com/vuejs/vue/blob/a43d66743be2bd62b2398090663e41eeaf0dc75f/src/platforms/web/runtime/components/transition.js#L110

Perhaps give it an explicit name like `default`?

### What does the proposed API look like?
```
<transition name="page" :mode="transitionMode">...</transition>
```

**Comment by posva** [comment]
dup of #6136 
Use an empty string or undefined 🙂
