### ISSUE TITLE
v-pre not working with slots

### ISSUE THREAD

**Issue by riophae** [vuejs/vue#6543]
### Version
2.4.2

### Reproduction link
[https://codepen.io/riophae/pen/xLzEob](https://codepen.io/riophae/pen/xLzEob)

### Steps to reproduce
See the CodePen link.

### What is expected?
"content" should be displayed.

### What is actually happening?
It shows "fallback".

**Comment by HerringtonDarkholme** [comment]
hmmm, I would rather argue it is by design. v-pre will ignore other directives, e.g. slot. 

If you need `v-pre` tag as slot, wrap it in a template should fix it.

https://codepen.io/anon/pen/rzEpzv

**Comment by riophae** [comment]
@HerringtonDarkholme Yeah, that works. However, according to the [docs](https://vuejs.org/v2/api/#v-pre), it says the purpose of `v-pre` is to allow displaying raw mustache tags, not to ignore other vue directives.

**Comment by HerringtonDarkholme** [comment]
The doc also says `Skip compilation for **this element** and all its children.` The example illustrates the main idea, not exact implementation. 

See updated example https://codepen.io/anon/pen/rzEpzv
