### ISSUE TITLE
Computed property/factory function for props

### ISSUE THREAD

**Issue by jlem** [vuejs/vue#6545]
### What problem does this feature solve?
I don't think I've ever worked on a Vue app where I haven't needed to pass in a complex object as a prop, and needed to define some default values for optional properties on that object.

For example, I have a table component that lets me define configuration like so:

```
config: {
   initialSortKey: 'name',
   rowSelection: {
       enabled: true,
       highlightSelections: false,
       filterSelections: true
       onSelectFn: ...
       onClearSelections: ...
       isSelectedFn: ...
   },
   columns: [...]
```

But `rowSelection` is entirely optional, so I don't want to have to define it for every instance where my table component is being used. Sometimes I just want to pass this in:

```
config: {
   initialSortKey: 'id',
   columns: [...]
```

However, every place that references `rowSelection` in the view model or the template, needs to be null checked first, which can get quite messy. OR, I have to use a contrived computed property like `computedConfig` where I do default merging and create a complete default config structure.

It would be nice if props provided some syntactic sugar that either allowed the `default` factory function to run every time, even if the prop is supplied, so that merge logic can be done, or if the prop had its own `computed` function where you could define this more complex behavior.

### What does the proposed API look like?
Either:

```
props: {
    config: {
        type: Object,
        alwaysApplyDefault: true,
        default: function (inputValue) {
            // merge your defaults with the inputValue and return
        }
}
```

OR

```
props: {
    config: {
        type: Object,
        computed: function (inputValue) {
            // merge your defaults with the inputValue and return
        }
}
```

**Comment by HerringtonDarkholme** [comment]
Can you list some objective benefit of computed props over computed methods? 

>  computed property like computedConfig

Neat solution, isn't it?

Also, computed props might add our API surface, get users confused about computed props and computed methods. Also see https://github.com/vuejs/vue/issues/6004#issuecomment-312404196 for more info.

**Comment by posva** [comment]
A default value that runs every time (needed) is exactly what you can already do with a computed property, so let's avoid adding API surface for something that is already doable in the very same way 🙂

```js
props: {
    config: Object,
},
computed: {
     myConfig () {
          return this.config || { defaultValue: 0 } 
    }
}
```

**Comment by jlem** [comment]
Unfortunately that solution is very inelegant because you're polluting the API of the component itself. You have both `config` and `myConfig` in your component's public API. It's almost like you're being forced to create a contrived name when all you really want is just to use `config` directly. 

Moreover, if you initially pass in just the prop and then later need to make it computed, you now have to update everything in your component that references that property to the computed property name. You can't change the prop name because then every place that references that component has to change it as well. 

It's just cleaner and more elegant to deal with *one* property in your component.
