### ISSUE TITLE
When I tried to bind an action on DIV,it bind on DIV's child element and bind two element.

### ISSUE THREAD

**Issue by janostudio** [vuejs/vue#6546]
### Version
2.3.3

### Reproduction link
[http://google.com/](http://google.com/)

### Steps to reproduce
The reality is described by title,code is here.And I use element-ui.

```
<div @click="hidePopup($event)">
       <el-row v-for="item in papers.theoryPapers" :key="item.id">
               <el-radio class="radio" v-model="paper.name" :label="item.name">{{item.name}}</el-radio>
       </el-row>
 </div>

hidePopup ($event) {
       console.log($event.target)
}

// and the result
<input type="radio" class="el-radio__original" value="试卷">
<span class="el-radio__label">试卷<!----></span>

```

### What is expected?
I just want to bind the action on div. 

### What is actually happening?
There is binding the action to the div's children element.

**Comment by javoski** [comment]
This is not a bug.
FYI, you can use `.self` modifier to make the event handler triggered only when event.target is the element itself.
```html
<div @click.self="hidePopup">
```
