### ISSUE TITLE
Skip empty text nodes in hydration

### ISSUE THREAD

**Issue by dmmikkel** [vuejs/vue#6548]
### What problem does this feature solve?
1. Allow SSR output to be human readable without causing hydration bailout
2. Make it easier to "fake" SSR in a template engine.

I have a simple vue app that I want to embed in a HTML-page. I want the app to come pre-rendered from the server, but I only have access to a simple templating language.

In other words I can't install any SSR tools. Instead I plan to fake SSR by having the template "render" the initial state of the vue app, without actually using Vue to render.

My problem is that I can't format the template without causing hydration to fail because the DOM-nodes contain text-nodes with whitespace, while the virtual DOM does not.

Here is a codepen of a simple app that fails hydration because of "empty" text nodes: https://codepen.io/dmmikkel/pen/ZJdMmR?editors=1001#0

EDIT: Hydration is only done in development. In production it will instead fail at rendering DOM saying "Failed to execute 'appendChild' on 'Node': This node type does not support this method." which is caused by trying to add a child to the TEXT-node. In my codepen example this can be testet by changing "vue.js" to "vue.min.js".

### What does the proposed API look like?
This does not change the api, unless you want to make skipping empty text nodes optional, in which case I propose a data-attribute on the root element, similar to data-server-rendered.

**Comment by dmmikkel** [comment]
I have decided that this should probably not be implemented into Vue. Instead I should run a script cleaning up the DOM before Vue initializes.

**Comment by outOFFspace** [comment]
@dmmikkel I have the same issue, and it happens occasionally. How can I reproduce in dev mode?
