### ISSUE TITLE
Directly modify VNode in directives

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#6550]
### What problem does this feature solve?
Directives receive the `vnode` parameter that Vue produced for the current element. The element's content can only be modified with `el.innerHTML`. If you call a slot inside the directive you get a VNode from the slot and have to transform the VNode manually to HTML.

See https://gist.github.com/johannes-z/62059e7a64c36e0dd70987738cba269a#file-customdirectives-js-L38 for use case.

*Side note: I tried using the Vue sources for rendering VNodes, but couldn't get that to work at all...*

### What does the proposed API look like?
```js
function customDirective (el, binding, vnode) {
  vnode = someOtherVNode // or use the returned VNode to render the directive, e.g., return someOtherVnode;
}
```

**Comment by posva** [comment]
Everything is read only (apart from the `el`), so modifying the vnode won't do anything. This is intentional to reduce the scope of directives. If you want to play around the vnode or modify the content of the HTML, you should use a component instead
