### ISSUE TITLE
在select控件中， 当value为0时不能正确显示 option

### ISSUE THREAD

**Issue by Joy1024** [vuejs/vue#6554]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/jay1024/swd4qwdn/4/](https://jsfiddle.net/jay1024/swd4qwdn/4/)

### Steps to reproduce
1、打开 https://jsfiddle.net/jay1024/swd4qwdn/4/
2、data.month 修改为1时，可以正常显示， 修改为0时则没有显示

### What is expected?
为：”1月“

### What is actually happening?
为：”“

**Comment by gsons** [comment]
are you sure? please email your issue to fuckyou@gmial.com

**Comment by posva** [comment]
FYI you should set the default value (1st option) to an empty String or to `null`/`undefined`. In your case, it's selecting the first option when selecting 1 because both have a similar value: `0` and `'0'` (which isn't normal), but this is just so you can fix it in your application 🙂

**Comment by yyx990803** [comment]
你的空选项 value 是 0，1 月的 value 也是 0，冲突了啊。选 1 月的时候 sync 为空选项了。

**Comment by Joy1024** [comment]
对的， 是我疏忽了。感谢你们的回答。
