### ISSUE TITLE
Add ability to reference component methods without needing $ref

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#6559]
### What problem does this feature solve?
Right now, in order to call a method from a custom component, you have to assign a $ref. Once assigned, you can reference the method by calling ```this.$refs.component.method()```.

The proposed change would allow for easiest access to internal methods.

### What does the proposed API look like?
Before:
```
<custom-component ref="component" @event="customMethod" />
```
Where custom method may be:
```
customMethod () {
  this.$refs.component.method()
}
```
After:
```
<custom-component @event="$this->method" />
```

**Comment by posva** [comment]
When is this actually useful? Usually, when listening to events on a component, you may want to trigger a method on **another** component but not in the same one

**Comment by yyx990803** [comment]
Why would you emit an event just so it triggers a method in the same component? Why not just call that method?

**Comment by johnleider** [comment]
I had a use-case for this, but I cannot find it atm. I'll re-open once I do, thank you.
