### ISSUE TITLE
SSR with Partial Prerendering

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [vuejs/vue#6560]
### What problem does this feature solve?
When creating an SSR Vue.js app, some of the pages don't change much, like a `Contact us` page.

Therefore, it'd probably be useful to come up with a more natural way of setting up SSR and [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin).

### What does the proposed API look like?
Some of the routes require SSR, while other are prerendered in advance.

**Comment by posva** [comment]
Vue gives you the power of setting up SSR but it's up to you to setup your project so it feels natural for you. If you want to prerender some pages instead of SSRing them, you'll have to setup the tooling for that but it's tooling not part of Vue core

**Comment by yyx990803** [comment]
I think there was some discussion regarding this in Nuxt.

**Comment by OlzhasAlexandrov** [comment]
I do think that in order to better differentiate Vue.js as a project comparing to React.js, for example, there should be even more amazing boilerplates (like vue-hackernews) and combining SSR with Prerendering, IMHO, is one of them.

@yyx990803 Thank you. However, when I was using nuxt.js, I remember looking at every message on Gitter and issue on GitHub, and I don't remember any examples/talks. I've also just tried searching for all logical keywords on Google and their repo, but with no result.
