### ISSUE TITLE
Support for android 5 ?

### ISSUE THREAD

**Issue by GiorgioMartini** [vuejs/vue#6567]
### What problem does this feature solve?
Hi, my company wants to switch to vue.js but are really concened regarding support for android 5...

In your site the lowest support for android is 6...

Does this means android 5 is not supported?

Can someone please confirm this?
Thanks

### What does the proposed API look like?
There would be no api, just regular support for android 5

**Comment by HerringtonDarkholme** [comment]
As far as I know, VueJS can support down to Android 4.4.

As for Android 5+, it uses separate web engine so android version doesn't matter. See the quote from caniuse

> Android browser/WebView version numbers through 4.4 refer to the version of Android OS. Support listed is for the Android core; it should be noted that many hardware vendors (Samsung, HTC, etc.) use altered version of their default browser which may include more/less/buggy support.

> Starting in Android 5, the web engine can be updated separately, so the latest Chromium version number is used instead.

**Comment by Nirazul** [comment]
> In your site the lowest support for android is 6...

Where is this written? I couldn't find any information about this. However what I've found is [this compatibility note](https://vuejs.org/v2/guide/installation.html#Compatibility-Note), stating that all ES5 compliant browsers are supported, so [this is a valid support table](http://caniuse.com/#feat=es5):

**Comment by yyx990803** [comment]
SauceLabs dropped support for Android 4.4 tests, that's why it no longer shows up. We do support all the way down to 4.4.

**Comment by GiorgioMartini** [comment]
Awesome! so i think we have greenlight to switch to vue :)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:40937 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1drPy6-000ls3-7x
	for greg@biomassiv.es; Mon, 11 Sep 2017 09:45:46 -0500
Date: Mon, 11 Sep 2017 07:45:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1505141105;
	bh=fd/60E3FGG9qukIcydZdbdPwMgR41xDix6/uBPbQHZ4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lMVAUR3hzSnmg0bWuGjh8xwddyCpdQtQUAa6u/q0cukNTG9347Stp6QcynBZ+rvBx
	 P6OMFLqy5gnmWbZu9BRxkLFvxU9hMVaAMiNrDJFbdNWPLfZx2K8kzEX9Ec7DW7BODZ
	 0lyMJPPWlqZ0psYNkxI23mUfVLyOblusGyTKr6N8=
