### ISSUE TITLE
Create an IIFE build of vue-template-compiler and add it to CDNjs

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue#6568]
### What problem does this feature solve?
Currently there is no browser runtime available over CDN for users.

vue-test-utils requires Vue and vue template compiler as globals, when it's run in the browser. Without an easily available browser friendly vue-template-compiler, users will not be able to use the full features of vue-test-utils.

If it's added, users will be able to run vue-test-utils in the browser

*Note: only a few features require the template compiler, an alternative to making it available on a CDN would be to warn browser users that certain features aren't available in the browser build*

### What does the proposed API look like?
Create a browser runtime that adds vueTemplateCompiler as a global variable.

**Comment by yyx990803** [comment]
closed via a5e5b314 (to be published in `vue-template-compiler@2.5`)
