### ISSUE TITLE
Extending bundled Typescript definitions for VueRx (or extending in general)

### ISSUE THREAD

**Issue by oliverw** [vuejs/vue#6569]
I'd like to use [VueRrx](https://github.com/vuejs/vue-rx) in a Typescript project.

VueRx extends the Vue prototype with several methods: https://github.com/vuejs/vue-rx#other-api-methods. Since VueRx does not ship with TS declarations, I would like to roll my own. Unfortunately I'm unable to come up with a way to extend the Vue declarations bundled with VueJs due to the way the declaration is written (classes rather than interfaces). Any suggestions?

**Comment by HerringtonDarkholme** [comment]
Sure, I can add it.
