### ISSUE TITLE
td template v-if not working on IE 10 & 11, IE 9 is OK

### ISSUE THREAD

**Issue by Jcay60** [vuejs/vue#6578]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/j4o16zzk/](https://jsfiddle.net/j4o16zzk/)

### Steps to reproduce
<tr>
	<th>123123</th>
	<td>123123</td>
	<template v-if="isShow">
		<td colspan="4">456</td>
	</template>
	<template v-else>
		<th>789</th>
		<td colspan="3">
			789
		</td>
	</template>
</tr>

### What is expected?
all IE version is ok

### What is actually happening?
IE9 OK
IE10,IE11 NG

---
Different permissions show different UI

**Comment by posva** [comment]
This is one of the limitations of in dom templates, due to browsers, see https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats for more 🙂
