### ISSUE TITLE
v-if and v-else are uncooperative with dom operate

### ISSUE THREAD

**Issue by rlsz** [vuejs/vue#6579]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/rlsz/buwyk0q3/](https://jsfiddle.net/rlsz/buwyk0q3/)

### Steps to reproduce
Run the jsfiddle example, read description then click the 'change show area' button twice.

### What is expected?
After first click, show-area shows 'hahahahaha' with green background color.
After second click, show-area shows '11111111' with yellow background color.

### What is actually happening?
After first click, show-area is correct.
After second click, show-area shows 'hahahahaha'(wrong) with yellow background color(right).

---
I guess v-if template and v-else template are stored in browser's memory as vue nodes.When I changed their children by operating dom directly, the vue nodes got unexpected changes.
My project is using echarts, which need to operate dom directly.

**Comment by yyx990803** [comment]
That's expected behavior. When you set `innerHTML` of the span, it replaces the inner TextNode. Vue is updating the original TextNode that was removed due to the operation. You can give the `<span>` a `key` to force it to be recreated: https://jsfiddle.net/yyx990803/buwyk0q3/7/

**Comment by rlsz** [comment]
There is another feature, which I just found. If the dom-operate affects some deep children, not the first child of the template, then all work fine without key. https://jsfiddle.net/m39t0h6u/
