### ISSUE TITLE
input tag use v-model="value"  input  special values cannot be monitored by watcher

### ISSUE THREAD

**Issue by keyus** [vuejs/vue#6580]
**I can't listen when I input '-'  string **,,,,so   stopedValue  function in watch Object   is not work.

<input v-model.number="stopedValue" min="1" type="number" >

data() {
        return {            
            stopedValue: 1,                
        };
    },

watch : {                
        stopedValue (val,oldval) {
            console.log(val,oldval)
        }
    },

**Comment by keyus** [comment]
please this  instence ;    when i input  '-'    number  value   is empty;   and vue watch   not work
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="body">
    <input type="number" v-model="number">
    {{number}}
</div>

<script src="vue.js"></script>
<script>
    new Vue({
        el : '.body',
        data () {
            return {
                number : 1
            }
        },
        watch : {
            number (val,oldval) {
                console.log(val,oldval)
            }
        }
    })
</script>
</body>
</html>
`

**Comment by afontcu** [comment]
Hi!

I don't think watch is supposed to work when you type just "-", it'll wait until you type the number as in "-3". As soon as you type the number the watch function is properly executed.
