### ISSUE TITLE
IOS10 Safari浏览器中select唤起后，点击完成无法选择当前项目。

### ISSUE THREAD

**Issue by x269147836** [vuejs/vue#6581]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/smpd16g0/](https://jsfiddle.net/smpd16g0/)

### Steps to reproduce
```
<select v-model="value">
        <option v-for="item in options" :value="item.value">{{item.name}}</option>
</select>
```

```
{
    value: null,
    options: [
        {name: '男', value: 1},
        {name: '女', value: 2},
        {name: '其他', value: 3}
    ]
}
```

在IOS Safari中点击下拉框，此时默认会选中第一个，随后点击完成按钮，select框没有选择任何数据。

### What is expected?
点击完成按钮后，第一项会选中。

### What is actually happening?
点击完成按钮后，未选择任何数据。必须滑动到其他选项再回到第一项才能选中。

**Comment by fritx** [comment]
Just met the same thing today!

```html
<select v-model="value">
  <option v-for="item in options" :value="item.value" :disabled="item.disabled">
    {{item.name}}
  </option>
</select>
```

```js
options.unshift({ name: '请选择', value: '', disabled: true })
// options.unshift({ name: 'pick one', value: '', disabled: true })
```

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:34581 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1drlib-004GLK-Lp
	for greg@biomassiv.es; Tue, 12 Sep 2017 08:59:13 -0500
Date: Tue, 12 Sep 2017 06:35:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1505223743;
	bh=ZMdD1/xxyc/uY0ySnEgRhSxC1w/XmyTS4bGf+7IF5/g=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xHz6XZt5xDjvTtd7qfWwfzn8op4qmwAgancM0TVo5DtYGGsjYVj99ssaYEqlqA5mt
	 BtphXWblr6ocubP5HMEU/620MwS4osTHZmgurMMZhb65Adrc+AffgN0PHArTDIWgRb
	 AfwOjFz95J05x+HaizDkw1mkKpRUMW7iPxNmzRcA=

**Comment by yyx990803** [comment]
This is a iOS system issue and we can't do much in Vue core. You have 2 workarounds:

1. Add a hidden optgroup before options: `<optgroup hidden="true" disabled></optgroup>`

2. Make sure to initialize the select with a default value that has a matching option.
