### ISSUE TITLE
动态创建的 component，第一次 activated 事件丢失

### ISSUE THREAD

**Issue by linfenpan** [vuejs/vue#6582]
### Version
2.4.1

### Reproduction link
[https://codepen.io/anon/pen/NaKJjL?editors=1111](https://codepen.io/anon/pen/NaKJjL?editors=1111)

### Steps to reproduce
keep-alive 嵌套的组件内，如果使用 component 动态加载另一个组件，
新加载的组件，将丢失一次 activated 事件。

留意例子的 console，点击按钮后，
按照正常情况，应该是要输出一个 "activated" 的，但实际没有

### What is expected?
动态创建的组件，应该也触发 activated 事件

### What is actually happening?
没有触发 activated

**Comment by yyx990803** [comment]
这是 expected behavior. `<keep-alive>` 作用于 `<loading>`，你 toggle 的时候 loading 并没有被 toggle，也就是说根本没有任何东西被 keep-alive，自然也不会有 activated.

**Comment by linfenpan** [comment]
上面的，是个例子。实际上，我们是用了 vue-router 的，keep-alive 中，缓存的是 router-view。
每一个页面，都是一个 component。

因为页面，都是异步加载回来的，为了让用户能更快的感受到操作，我们就添加了一层 loading 的组件。
让页面，在组件加载回来之前，先进入 loading 组件，加载完毕后，通过 loading 组件的 component 再加载正确的页面。

于是就遇到了上面类似的问题了。
现在我们的解决方案是，在加载组件后，遍历一次所有的 $children，触发一下 activated。

**Comment by yyx990803** [comment]
就是因为这层多出来的 loading 使得 keep-alive 感觉不到内部组件的变化。其实可以考虑用 https://vuejs.org/v2/guide/components.html#Advanced-Async-Components

**Comment by linfenpan** [comment]
好的，谢谢，我试试去
