### ISSUE TITLE
Sharepoint 2013 SP.UI.ModalDialog.showModalDialog error

### ISSUE THREAD

**Issue by Masanix** [vuejs/vue#6584]
### Version
2.4.2

### Reproduction link
[https://msdn.microsoft.com/en-us/library/office/ff410058(v=office.14).aspx](https://msdn.microsoft.com/en-us/library/office/ff410058(v=office.14).aspx)

### Steps to reproduce
I am using Vue with Sharepoint 2013.

Everything is all right except when I try to open a modal window with Sharepoint.

This is code

`methods: {`
`addNewProject: function () {`
`var options = {`
`title: 'Add a New Project',`
`width: 700,`
`height: 550,`
`url: '/sites/BLA/Lists/Projects/NewForm.aspx',`
`callback:function(dialogResult, returnValue) {`
`alert("Result=" dialogResult);`
`}`
`};`

SP.UI.ModalDialog.showModalDialog(options);

### What is expected?
A pop-up window appears

### What is actually happening?
Receive a message error

TypeError: window.self._dlgWndTop is not a function

PS Sorry does not work in JSFiddle

---
When it is executed not in a vue method  it works

Ex.
`$(document).ready(function() {`
`var options = { ... };`
`SP.UI.ModalDialog.showModalDialog(options);`
`});`

**Comment by yyx990803** [comment]
The error doesn't seem to relate to Vue. Calling it inside a Vue method shouldn't make any difference. Does it work outside a Vue method?

Unfortunately without a repro we cannot really help any further.

**Comment by Masanix** [comment]
Thanks Evan.

Yes it works outside a Vue method. 

I try to create a repro.

KR
Gio

**Comment by Masanix** [comment]
Hello,

Just to add the solution for others that could have the same problem.

Tha answer was in message error
`TypeError: window.self._dlgWndTop is not a function`

It seems that `self `is a keyword used by Sharepoint and creates problems.

Instead to use `self = this` use --> `itself = this`.

Very simple :+1:  

KR
Giovanni
