### ISSUE TITLE
Watch nested object's properties inside component

### ISSUE THREAD

**Issue by minhtruong92** [vuejs/vue#6586]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/minhshayne/fe2owuhL/](https://jsfiddle.net/minhshayne/fe2owuhL/)

### Steps to reproduce
- Set v-model = "input.name" to b-input component and v-model = "input.nameV" to input html
- After finish render HTML, input some value to "b-input" and native input HTML
- Click "Set input to empty"

### What is expected?
- b-input component must update value to text field like the input HTML updated

### What is actually happening?
- b-input component not update value to text field but the normal input HTML updated

---
b-input change value when we use $forceUpdate before we set object input to empty. I don't understand why I $emit new value to v-model (input) but it's not assign it to model.

**Comment by JounQin** [comment]
You should define properties of `input` on initialization.

https://jsfiddle.net/JounQin/fe2owuhL/8/

See also: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by minhtruong92** [comment]
@JounQin : Thank for your reply.

Do you have any solutions for this ? Because sometimes we can't define all properties in initialization, example : We define "customer = {} " , and we will bind all properties of customer object by ajax to server and get customer informations, so we will have a lot of properties need to be defined.

**Comment by yyx990803** [comment]
First: if you are binding to a property in the template, it means you already know this field should exists beforehand, and you should declare it beforehand.

By default `v-model` **does not create reactive properties for you**. However there's a trick to force it to add reactive properties by using the bracket syntax: `v-model="input['name']"`. See https://jsfiddle.net/yyx990803/fe2owuhL/10/

Still, I strongly recommend declaring properties beforehand and you will have an easier time debugging and maintaining the code in the long run.
