### ISSUE TITLE
重大改革方向

### ISSUE THREAD

**Issue by SteveCruise** [vuejs/vue#6590]
### What problem does this feature solve?
9.12晚，node放出[重磅更新](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.5.0)，自8.5起原生支持ES modules，入口文件需使用新后缀名.mjs。早些时候，chrome 61也宣告默认原生支持ES modules，需在script标签中增加type="module"。也就是说，自此开始，前后端均开始原生支持ES modules，这意味着babel不再必须。去掉babel的好处自不必说，出错更容易调试。对于后台管理类应用，可立即使用原生模块这一新特性。
后端已经可以拿掉babel了，但是前端要拿掉babel，还需要vue遵守新规范，适应新形势新变化。例如，原生模块只支持export default，并且import时不能进行解构。因此，store、router、filter统统要改，build后的index.html改成<script type="module" src="/dist/build.js">
无论如何，9.12是个划时代的日子。

### What does the proposed API look like?
面向原生模块

**Comment by yyx990803** [comment]
https://twitter.com/samccone/status/905875254693777409

**Comment by SteveCruise** [comment]
谢谢尤大的回复

**Comment by moonou** [comment]
我一直以为babel是转换新语法，webpack是处理模块的呢。

**Comment by SteveCruise** [comment]
@moonou 含义不一样，我说的模块是指ES modules，不是webpack打包的各类文件
