### ISSUE TITLE
Add boolean modifier to v-model

### ISSUE THREAD

**Issue by mariuszjamro** [vuejs/vue#6592]
### What problem does this feature solve?

There is a `.number` modifier for v-model which automatically parses the value as integer.

    <input v-model.number="age" type="number">

It would be useful to have a similar modifier for boolean values.

    <input v-model.bool="isActive" type="checkbox">

This way the checkbox will work when `isActive` value contains strings `"true"` and `"false"` instead of javascripts true/false. Currently the checkbox will be checked if `isActive` is `"false"`. With this modifier the code will work as it would handle boolean strings `"true"` and `"false"` as real booleans (`true` and `false`).

### What does the proposed API look like?

    <input v-model.bool="isActive" type="checkbox">

**Comment by yyx990803** [comment]
Modifiers are for mapping DOM values back to JavaScript values, not the other way around. You should just convert your strings to real booleans before initializing your app.

**Comment by Nozich** [comment]
You can use v-model="foo" as integer (1 or 0) when bar has boolean

```
data() {
  return {
    bar: true,
  };
},
computed: {
  foo: {
    set(val) {
      Vue.set(this, 'bar', !!val);
    },
    get() {
      return +this.bar;
    },
  },
}
```

**Comment by jjangga0214** [comment]
@mariuszjamro 
Alternatively, you can use `v-bind`. *v-binded* "true"/"false" will be real boolean true / false. 
```html
<input type="radio" :value="true" v-model="foo">yes
<input type="radio" :value="false" v-model="foo">no
```
```js
new Vue({
  ...
  data() {
    return {
      foo: false, // this will be boolean true or false, rather than "true" or "false".
    };
  },
  ...
});
```

This is because the value of *v-binded* attribute will be parsed as javascript code.
For example, `<input type="radio" :value="bar" v-model="foo">` this value will be the value of variable `bar` if there is data or prop named `bar`. If not, it will be the string "bar".
As there is no variable named `true`, `:value="true" ` would be javascript's pure boolean true.

**Comment by hburak** [comment]
How can you use the boolean field within v-if by passing it to another component with a submit event? I want to show a text based on a decision over this boolean field.

**Comment by nozich** [comment]
@hburak you can use [Vuex](https://github.com/vuejs/vuex) for realtime data based on all around the your Vue App

Component A:
```vue
<button @click.prevent="$store.commit('SET_DECISION', true)">Change Decision</button>
```

Component B:
```vue
<div v-if="Decision">BlueBox</div>
<div v-else>RedBox</div>
```
```javascript
import { mapState } from 'Vuex';
```
```javascript
computed: {
  ...mapState(['Decision'])
}
```

Vuex:
```javascript
state: {
  Decision: false
},
mutations: {
  SET_DECISION(state, Decision) {
    state.Decision = Decision;
  }
}
```

Dostum componentler arasında event'lar emit ederek ve alt componentlere prop'lar vererek iletişim sağlayabilirsin, ama vuex varken onlara hiç gerek yok.

Vuex, uygulama genelinde canlı olarak veri tutmanı sağlıyor, uygulama üzerinde canlı veritabanı olarak düşünebilirsin, sayfa geçişlerinde ve hangi componentte olursan ol mapState diyip bi data ya canlı olarak bağlanabiliyorsun.

**Comment by jwbats** [comment]
> Modifiers are for mapping DOM values back to JavaScript values.

This is precisely what I'm currently trying to do with a select box that has 2 options: 'yes' and 'no', with underlying values true and false.

The select box will properly reflect the property's value whether it is a boolean true/false or a string "true"/"false".

But when the select box options are chosen, the property value always becomes a string "true"/"false".

I don't understand why we can have a modifier for numbers, but not for booleans?
