### ISSUE TITLE
Directive association is incorrect when using v-if

### ISSUE THREAD

**Issue by fredarchimed** [vuejs/vue#6593]
### Version
2.4.3

### Reproduction link
[https://jsfiddle.net/24fj267q/4/](https://jsfiddle.net/24fj267q/4/)

### Steps to reproduce
- drag&drop red square : it works, the element has the v-drag directive.
- click on Toggle button to display blue square. Note that it doesn't have v-drag directive.
- you can drag the blue square

### What is expected?
You shouldn't be able to drag the blue square as there is no v-drag directive on it.

### What is actually happening?
Both squares can be dragged.

---
What I understand is the directive is binded to an element in the DOM using an index. When the DOM is updated with v-if, the index is not updated, so the directive binds on an other element.
It can be easily solved by using v-show instead of v-if.

**Comment by greabock** [comment]
This problem correlates with https://vuejs.org/v2/guide/list.html#key

[solution](https://jsfiddle.net/24fj267q/5/)

**Comment by posva** [comment]
What @greabock said 🙂
