### ISSUE TITLE
Should transition hooks be inside the component.vue file?

### ISSUE THREAD

**Issue by jeremenichelli** [vuejs/vue#6594]
While using the `<transition>` element I come to realize that the JavaScript transition hooks are scoped in the component's parent object:

_parent component_
```html
<template>
  <div class="parent">
    <transition v-on:enter="onChildEnter">
       <some-child></some-child>
    </transition>
  </div>
</template>

<script>
export default {
  methods: {
    onEnter(el, done) {}
  }
}
</script>
```

The issue with this is that it kinda breaks the single file component model because there are methods decribing the behavior of a component outside of it.

Also, the `onEnter` method will be generic to all child components that are render inside the `<transition>` tag.

These two points encourage dirty DOM checks:

- if the transition hook would be inside the child component instead of doing `el.querySelector('.element--inside--children')`, **refs** could be used.

- if you want two different animations for elements inside the transition tag, for example when animating routes entering with `<router-view>`, you have to do some dirty conditional check inside the transition method.

I could be missing some possible configuration or skipped in the docs. In case I didn't miss anything and there is no escape over this, I would suggest moving the transition hooks inside a `transition` property in the child component, similar to what **nuxt** does (https://nuxtjs.org/api/pages-transition#object).

The aprent and child components inside the transition tag would look something like that:

_parent component_
```html
<template>
  <div class="parent">
    <transition name="fade">
       <some-child></some-child>
    </transition>
  </div>
</template>

<script>
export default {
  methods: {
    onEnter(el, done) {}
  }
}
</script>
```

_child ccomponent_
```html
<template>
  <div class="child"></div>
</template>

<script>
export default {
  name: 'child',
  transition: {
    beforeEnter(el, done) {},
    onEnter(el, done) {},
    beforeLeave(el, done) {},
    onLeave(el, done) {},
  }
}
</script>
```

Alternatively we could use the name of the transition to identify the hooks:
```js
 transition: {
  fade: {
    beforeEnter(el, done) {},
    onEnter(el, done) {},
    beforeLeave(el, done) {},
    onLeave(el, done) {},
  },
  otherTransition: {}
}
```

This would allow developers to different animations in case the element is reused and wrapped in other parts of the app and need a different sequence.

What about common transition hooks like in the current Vue version? Well, that could be easily accomplished if the user creates a generic function, imports it in each component and reference it.

I repeat, if it was possible to define a transition hooks in children components and I missed it, sorry in advance for the noise :)

**Comment by MSCAU** [comment]
I don't want to report this issue, I just want the same answer as OP. Anyone?
