### ISSUE TITLE
How to append a vnode segments to the current Vue Instance?

### ISSUE THREAD

**Issue by AkatQuas** [vuejs/vue#6599]
### What problem does this feature solve?
In a normal Vue instance, click the button which will invoke a function that create a vnode by calling `this.$createElement` function.

            tryCreated() {
                let vm = this;
          
                let h1tag = vm.$createElement('h1', 'This is an h1 tag')
               
            }
 
How can I insert the `h1tag` into `this`?

 

### What does the proposed API look like?
`$createElement`, `Render Function`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
