### ISSUE TITLE
Scoped slot with "name" prop does not render

### ISSUE THREAD

**Issue by sntran** [vuejs/vue#6606]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/rf8zn6r1/](https://jsfiddle.net/rf8zn6r1/)

### Steps to reproduce
- Run the JSFiddle.
- Choose or drag-n-drop a file into the file input.

### What is expected?
The file's name is listed under the input

### What is actually happening?
Nothing is listed under the input

---
The issue only happens when I `:name="file.name"`. If I use other prop, such as `:other="file.name"`, the scoped slot is rendered.

Also, instead of binding individual props, using `v-bind="file"` works fine.

**Comment by sirlancelot** [comment]
As you said, you'll need to use `v-bind` if you want to have a `name` prop in your scoped values. This is because the slot tag already consumes the name attribute for internal purposes.

**Comment by sntran** [comment]
Right. But why would `v-bind` works with an object with `name` attribute, but not directly with `name` prop? Can we check the prop being bound that if it is a `name`, we just bind it?

What are the uses of `name` attribute when inside a named slot?

**Comment by sirlancelot** [comment]
It's completely valid to bind a dynamic slot name, which is what you've done in your first example. You've essentially written two `name` attributes in the `<slot>` tag; one being dynamic and the other static.

`v-bind` compiles to something completely different than hard-coding attributes. Use this live-compiler to see how Vue will compile your template: https://vuejs-tips.github.io/compiler/

**Comment by sntran** [comment]
> bind a dynamic slot name

This. Thank you for explaining. I forgot about that use.

**Comment by mikeevstropov** [comment]
I have the same problem.

```
<div id="app">
  
  <my-component>
    
    <template
      slot="name"
      slot-scope="scope">
      {{ scope.value }}
    </template>
    
  </my-component>
  
</script>
```

```
Vue.component('my-component', {
  template: '<div> <slot name="name" value="test"></slot> </div>'
});

new Vue({
  el: '#app',
});
```

https://codepen.io/anon/pen/xywWBO?editors=1010#0

**Comment by mikeevstropov** [comment]
@sirlancelot Thank you for reply! Codepen has updated, it works after upgrade vue from 2.3 to latest.
