### ISSUE TITLE
Deep watch syntax could be simplified

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue#6607]
### What problem does this feature solve?
Currently in order to watch object properties, you need to *deep watch* it, using:
```js
watch: {
  foo: {
     handler(val){
       // do stuff
     },
     deep: true,
  },
},
```

The problem is that this notation is 'hard' to decipher and add visual noise.

### What does the proposed API look like?
Given that you only want to watch the `foo.a` and `foo.b` properties of your data.
What if you wouldn't need to declare the `deep` nor `handler` attributes and clean that up by directly adding an object like so?:
```js
watch: {
    foo: {
      a() {},
      b() {},
    },
},
```
That way the `a` and `b` watch functions would exactly like if they were directly accessible from `this.a` and `this.b`. Bonus point for refactoring 👍

I imagine you could detect that `watch.foo` is not a function, and that each of its attribute `a` and `b` are functions.

From a user point of view, I do find this notation clearer to understand and parse.

As always, feel free to discuss that idea :)

**Comment by JounQin** [comment]
Just use like following:
``` js
watch: {
  'foo.a'() {},
  'foo.b'() {}
}
```

https://jsfiddle.net/JounQin/zr3a9svc/

**Comment by yyx990803** [comment]
I think the proposed syntax doesn't solve the problem with deep watching - what you want is specific paths instead of "this whole object/array has changed in some way".
