### ISSUE TITLE
对数组的 watch 在使用 push() 增加后无法得到符合预期的“当前值”及“更新前值”

### ISSUE THREAD

**Issue by ay86** [vuejs/vue#6608]
### Version
2.4.2

### Reproduction link
[https://jsbin.com/firujumohe/edit?html,js,console,output](https://jsbin.com/firujumohe/edit?html,js,console,output)

### Steps to reproduce
实例中对数组进行 watch，在对数组进行 push 操作后，watch 的两个参数“当前值”，“更新前值”并不能得到预期中的值。但是通过另外的“曲线”方式，如 concat 了一个新数组然后赋值给原来的数组则能正常得到值。但是我想，push 的问题应该是存在 bug 吧。具体见提供链接里。

### What is expected?
ids:[];
watch:{ids.....}
ids.push(0);
// [0], []

### What is actually happening?
ids:[];
watch:{ids.....}
ids.push(0);
// [0], [0]

---
ids:[];
ids=ids.concat([0]);
// [0], []

这是一种解决方案...

**Comment by JounQin** [comment]
push 操作本身就不改变数组本身啊，prev 和 curr 是指向是同一个数组，值当然一样了。

**Comment by javoski** [comment]
>注意：在变异 (不是替换) 对象或数组时，旧值将与新值相同，因为它们的引用指向同一个对象/数组。Vue 不会保留变异之前值的副本。


[https://cn.vuejs.org/v2/api/index.html#vm-watch](https://cn.vuejs.org/v2/api/index.html#vm-watch)
