### ISSUE TITLE
dev mode, mixin in sfc is merged before vue-router plugin install

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue#6609]
### Version
2.4.3

### Reproduction link
[https://github.com/Astray-git/vue-router-mixin-issue](https://github.com/Astray-git/vue-router-mixin-issue)

### Steps to reproduce
run project with `npm run dev` open console, navigate to /foo/bar.
refresh page see logs in console.

put a breakpoint in vue.esm.js's [`mergeOptions` function](https://github.com/vuejs/vue/blob/ef432c6e86d34d891034fd7668a85793be4a2607/dist/vue.esm.js#L1375). you can see vue merges the mixin before `Vue.use(vueRouter)` 

build with `npm run build` start the page with http-server, try same above, it works as expected.

### What is expected?
`beforeRouteEnter` from mixin get called after refresh

console:
```
mixin beforeRouteEnter
component beforeRouteEnter
mixin created
component created
component beforeRouteEnter next
mixin beforeRouteEnter next
```

### What is actually happening?
only `created` in mixin is called
console:
```
component beforeRouteEnter
mixin created
component created
component beforeRouteEnter next
```

---
vue-router version 2.7.0

in dev mode, router mixins are merged before vue-router strategies get isntalled.

**Comment by JounQin** [comment]
As I know, vue will just override your `beforeRouteEnter` mixin when you pass `beforeRouteEnter` manually, because it's not in Vue [LIFECYCLE_HOOKS](https://github.com/vuejs/vue/blob/master/dist/vue.esm.js#L317), so it is as expected.

https://github.com/vuejs/vue/blob/master/dist/vue.esm.js#L1393

**Comment by Astray-git** [comment]
You checkout vue-router code, they use the same strategy as `created` hook

https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.esm.js#L525

**Comment by JounQin** [comment]
@Astray-git I believe it's only related to `vue-loader` with ES module component after trying to run your reproduction.

I find several workarounds for now:
1. use commonjs to require `.vue` component: `require('Foo.vue')`
2. use async component like `() => import('Foo.vue')`
3. use `.js` to export a object directly

Maybe you should move this issue to [vue-loader](https://github.com/vuejs/vue-loader)

**Comment by JounQin** [comment]
After looking through the built assets, I can confirm your issue is related to difference between ES module and commonjs.

``` js
// ES module input
import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

import Foo from './Foo.vue'
// ...

// ES module output
const Vue = _require('vue')
const VueRouter = _require('vue-router')
const Foo = _require('./Foo.vue')

Vue.use(VueRouter)
```

What means ES module will resolve module first then run your own codes while commonjs will follow your codes' order, and at the same time `vue-loader` wrapps the `.vue` sfc into a Vue component already.
That's why exporting an object directly will resolve this problem.

So, I believe we can not fix this because it's not an issue.

**Comment by javoski** [comment]
Component mixins are not applied yet when the `beforeRouteEnter` guard function was called.
I'm not sure if this is expected, and if not, it's more like an issue of `vue-router`.

**Comment by javoski** [comment]
It's an issue of `vue-loader` connected with hot reloading.
A temporary workaround might be:
```js
import Vue from 'vue'
import App from './App.vue'
import Home from './Home.vue'
import Foo from './Foo.vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter);

if (process.env.NODE_ENV !== 'production') {
  Foo._Ctor = null
}
```
