### ISSUE TITLE
Hoisting-up vnode - infinite loop warning

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#6610]
### Version
2.4.4

### Reproduction link
[http://jsfiddle.net/vjvMp/2019/](http://jsfiddle.net/vjvMp/2019/)

### Steps to reproduce
The precise layout of the components are in the JSFiddle. The assembly of the components is for some reason very fragile which makes me think that this is a bug. For example, if I remove the top-most `layout` component that shouldn't affect the code, the warning disappears: http://jsfiddle.net/vjvMp/2020/

### What is expected?
For the slot on the Child to be hoisted up to the Parent and rendered above the Child without problem.

### What is actually happening?
The Child gets rendered but there is an infinite update loop warning.

**Comment by hirokiosame** [comment]
The code was [working at v2.4.2](http://jsfiddle.net/vjvMp/2021/); seems like it was introduced at v2.4.3.

**Comment by yyx990803** [comment]
- You are returning API from `data`, this makes the while `api` object reactive
- When you set the vnodes into the API that makes Vue attempt to convert the vnode
- In 2.4.3 slot nodes are now deep-cloned on re-render to fix some bugs, this makes the render function register the entire vnode to be reactive dependency, so mutating the vnode triggers a re-render.

For now your workaround could be either `Object.freeze` the vnode or do not make the api injection reactive.

**Comment by hirokiosame** [comment]
Fix works great! Thanks @yyx990803
