### ISSUE TITLE
Tables in SSR are causing warning The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by gwildu** [vuejs/vue#6612]
### Version
2.4.4

### Reproduction link
[https://github.com/gwildu/v-html](https://github.com/gwildu/v-html)
Table component: https://github.com/gwildu/v-html/blob/master/components/Table.vue

### Steps to reproduce
The git repo linked is a nuxt starter repo with additional table component. The data for rendering the table is static data.
* run yarn
* run yarn dev
* open the browser: http://localhost:3000
* open the console and check the Warnings / Errors

### What is expected?
The server-side rendered markup should match the client-side markup and no warning should be shown. The table should be rendered in the browser

### What is actually happening?
You get the following warnings / errors in the console: 
* Parent: table
* Mismatching childNodes vs. VNodes: NodeList  tbody 
* Vue warn: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup

The table gets not rendered when loading the page from server

---
Inside the table component (/components/Table.vue) I also added a list for comparison. When you remove the table, the list is rendering without warning, by adding the table you get the warning again.

**Comment by defcc** [comment]
Thanks @gwildu  please refer https://ssr.vuejs.org/en/hydration.html

You need to write `tbody`  in your template.
