### ISSUE TITLE
$slots don't show correct slots when using slot scope

### ISSUE THREAD

**Issue by lindesvard** [vuejs/vue#6615]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/036scaat/6/](https://jsfiddle.net/036scaat/6/)

### Steps to reproduce
Create a child component with two slots <slot> and <slot name="xxx">. 
If you now use the named slot with scope feature the child components $slots variable will only have the default.

### What is expected?
`Object.keys(this.$slots) === ["default", "xxx"]`
Removed `scope="props"` from template and it gives expected result --> https://jsfiddle.net/036scaat/8/

### What is actually happening?
`Object.keys(this.$slots) === ["default"]`

**Comment by yyx990803** [comment]
Scoped slots are stored in a different property: https://vuejs.org/v2/api/#vm-scopedSlots
