### ISSUE TITLE
Watcher on Object misfires on property addition to parent

### ISSUE THREAD

**Issue by falco467** [vuejs/vue#6616]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/5r56ff2u/](https://jsfiddle.net/5r56ff2u/)

### Steps to reproduce
Declare a watcher on a property containing an object. Then add a new property to the parent object with Vue.set( parent, 'newProp', 'x' )

### What is expected?
The watcher should only fire if the watched property is changed.

### What is actually happening?
The watcher also fires if new properties are added to the parent object, although the watched value does not change.

---
The misfire only happens if the watched value is a js object, not on primitive types.

**Comment by yyx990803** [comment]
This is a limitation of the watching mechanism. If the watched value is an object, the watcher may have been fired as a result of a new property added to that object itself, so we fire to to be safe. This is a tradeoff between correctness vs. over-firing.

In most cases, over-firing would be harmless unless you have extremely expensive callbacks. Alternatively, you can perform a custom check (e.g. shallow compare the properties) in your callback to avoid the "real" work.

This will unlikely change in 2.x, but will be fixed when we upgrade the reactivity system using Proxies.

**Comment by falco467** [comment]
Hi!
The Problem is not when adding a property to the watched object, firing could be expected, but rather when adding a property to a parent object.

    data: { parent: { child:{ name: 'x' } }
    watch: { 'parent.child' : ... }
    Vue.set( parent, 'name', 'y' ) // Here the watcher for the child fires

**Comment by yyx990803** [comment]
I know, I was explaining the possible scenario that we have to cater for which leads to the behavior you are seeing.

**Comment by falco467** [comment]
Thanks for your insight -- looking forward to the Proxy-Based system.

For others running into this: I've now written a small Plugin/Mixin so I can use "watchExact" as a custom option, it saves the original value and only fires the function if the new value differs :-)
