### ISSUE TITLE
Can't use a component called <filter>

### ISSUE THREAD

**Issue by stowball** [vuejs/vue#6617]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/stowball/uchcrwt0/](https://jsfiddle.net/stowball/uchcrwt0/)

### Steps to reproduce
1. Create a component called `'filter'`
2. Add it to a VM

Error in the console:

```
[Vue warn]: Do not use built-in or reserved HTML elements as component id: filter
```

```js
var app = new Vue({
   el: '#app',
   components: {
       'filter': {
           template: '<h1>:(</h1>'
       }
   }
});
```

```html
<div id="app">
    <filter />
</div>
```

### What is expected?
To be able to use any reasonable name for a component, of which `'filter'` is one, and have it render.

### What is actually happening?
The `'filter'` component is not rendered.

**Comment by javoski** [comment]
Just as what the warning message said, `<filter>` is a valid SVG element and is reserved, you should use another name instead of `filter`.

**Comment by stowball** [comment]
D'oh! I was like "but there is no filter HTML element". SVG didn't even occur to me. Sorry!

**Comment by oppiansteve** [comment]
I'm a bit surprised namespaces are ignored, but hey ho.
