### ISSUE TITLE
Seems value binding of <video> poster attribute leads to template compiling error

### ISSUE THREAD

**Issue by xekri** [vuejs/vue#6623]
### Version
2.4.4

### Reproduction link
[JSFiddle Reproduction Demo](https://jsfiddle.net/gar0ytq3/2/)

### Steps to reproduce
Uncomment the second `<video>` tag and you can see an error thrown by Vue.

By the way, it's unlike issue #2042, the poster attribute seems allowed to modified after first rendering. So I think it's maybe a vue template compiler's bug.

### What is expected?
dynamically binding `poster` attribute to the <video> element

### What is actually happening?
throw an Error when compiling template.

**Comment by posva** [comment]
You don't need a v-bind there: `<video poster="http://img.171u.com/image/1411/1809501657794.jpg" controls>`

**Comment by xekri** [comment]
@posva sorry, I made a mistake when creating the reproduction. 
https://jsfiddle.net/gar0ytq3/3/
Now, I used string but not worked either.

PS. there's need for me to use v-bind
