### ISSUE TITLE
$router.replace() don't replases History.replaceState()

### ISSUE THREAD

**Issue by evgencode** [vuejs/vue#6625]
### Version
2.4.4

### Reproduction link
[https://github.com/evgencode/routerbug](https://github.com/evgencode/routerbug)

### Steps to reproduce
I have a component:

`const Request = () =>  import('../components/request');`

And router:

```
const router = new VueRouter({
    { path: '/request/edit/:id', name: 'requestEdit', component: Request }
})

```
in component:

```
created : function() {
    this.init(this.$route);
    setTimeout(() => {
        // go to other router page after 2 sec.
        this.$router.replace('/request/edit/'   200);
    }, 2000);
},
beforeRouteUpdate : function(to, from, next) {
    this.init(to);
},
```

I'm trying to run site.com/request/edit/100.

### What is expected?
Will mount component with id=100, after 2 second it will mount again with id=200
And url have to change to a new: /request/edit/200.

### What is actually happening?
But this does not happen, the previos url (/request/edit/100) remains in ULR bar.
I suspect that the function History.replaceState() does not execute in this case.

---
Why url doesn't change?
If i'm using

`<router-link to="/request/edit/200">...</router-link>
`
in Request component the URL also does not change. Do I have to execute history.replaceState() by hands?

**Comment by posva** [comment]
you already opened the issue on vue-router
