### ISSUE TITLE
Vue.SSR bug on nodejs v8.x [About Async Promise Entrance]

### ISSUE THREAD

**Issue by cevio** [vuejs/vue#6629]
### Version
2.4.4

### Reproduction link
[https://github.com/vuejs/vue/issues/6628](https://github.com/vuejs/vue/issues/6628)

### Steps to reproduce
关于在nodejs@8.x环境下，不使用babel编译的情况下直接启动webpack-dev-server导致入口返回值类型是`[object Promise]`的情况下，无法正确解析而报错。

### What is expected?
在不使用babel编译async的情况下使用async 返回的对象能够修正处理

### What is actually happening?
normalizeRender函数报错`undefined`

---
Sorry, my english is poor!

> 我发现一个问题：关于在nodejs@8.x环境下，不使用babel编译的情况下直接启动webpack-dev-server导致入口返回值类型是`[object Promise]`的情况下，无法正确解析而报错。

### 描述

SSR要求启动文件**最终**返回一个VM对象。因为有一些情况下我们需要使用异步返回，当然我们首先考虑到的时候`Promise`。所以我直接返回了一个async的`promise`对象。自然地，程序应该等待这个异步对象结束返回值后再编译。

在一般情况下，都是通过`babel`去将`async Promise`编译，我们可以认为使用`co`模块去包裹，这样永远只会返回`[object Function]`类型。而现在，nodejs@8.x情况下，已经不需要编译`async Promise`了，所以在我这种特殊运行情况下，这个类型根本不是`[object Function]`。当然肯定是`[object Promise]`。

源码中是这样写的：

> 文件大概在`node_modules/vue-server-renderer/build.js:7791`。

```javascript
var res = evaluate(entry, createSandbox(userContext));
resolve(typeof res === 'function' ? res(userContext) : res);
```

当我们得到的res是一个promise对象的时候，这就直接报错了。

### 修正

我的修正方式是：

```javascript
var res = evaluate(entry, createSandbox(userContext));
 if (Object.prototype.toString.call(res) === '[object Promise]') {
     res.then(fn => resolve(typeof fn === 'function' ? fn(userContext) : fn));
 } else {
      resolve(typeof res === 'function' ? res(userContext) : res);
}
```

就是等到Promise结束后再resolve最终的结果。在nodejs@8.x情况下这个已经影响使用了，希望作者能够尽快修正发布版本。

**Comment by HerringtonDarkholme** [comment]
You should resolve a **promise of Vue instance** rather than a **promise of a function** returning Vue instance.

You proposed solution.

```js
     res.then(fn => resolve(typeof fn === 'function' ? fn(userContext) : fn));
```

implies you're returning a promise of function. This is wrong usage. You can call your function in the promise.

Current implementation

```js
resolve(typeof res === 'function' ? res(userContext) : res);
```

`resolve` will unwrap the promise returned by server entry code.

**Comment by cevio** [comment]
I'm sorry. I find another way to resolve this problem.
Thans!
