### ISSUE TITLE
v-bind:key behavior

### ISSUE THREAD

**Issue by maxorlovsky** [vuejs/vue#6633]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/worzuz0c/1/](https://jsfiddle.net/worzuz0c/1/)

### Steps to reproduce
make a v-for loop with bind:key
add input with model of the key, start typing, after initial type cursor move out of the field.

### What is expected?
Normal typing without cursor moving out

### What is actually happening?
After first letter was typed cursor move out. As if there is "on-key-up = return false" set up.

**Comment by wszerad** [comment]
For my it's normal behavior. Change of permission.key fire v-for and input is re-created. :key should be uniq and in this case isn't

**Comment by posva** [comment]
Oh, wow, my bad, I thought the key was bound to the index, thanks @wszerad !
The input changing the value that is used for the `key` attribute, the input is re-rendered and therefore gets out of focus. A solution would be to manually focus it when the key changes by using a watcher

**Comment by javoski** [comment]
Or you can use `.lazy` modifier.
