### ISSUE TITLE
How can use Vue.js in WebExtensions?

### ISSUE THREAD

**Issue by pea3nut** [vuejs/vue#6635]
### What problem does this feature solve?
I tried to build WebExtensions with Vue.js, but got this:

```
[Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.
```

I know WebExtensions has a lot of restrictions on security, but can Vue.js try to bypass these security restrictions?

### What does the proposed API look like?
Can run under WebExtensions context.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

https://vuejs.org/v2/guide/installation.html#CSP-environments

**Comment by pea3nut** [comment]
Okey~

I found [CSP version of Vue](https://github.com/vuejs/vue/tree/csp), It looks like only has 1.X version.

CSP version worked in WebExtensions, Should use 1.x doc
https://v1.vuejs.org/guide/installation.html#CSP-compliant-build

thx

**Comment by yyx990803** [comment]
Note that 2.x can also work with CSP, but you will need to pre-compile the templates with a build step.
