### ISSUE TITLE
[bug?] Seems like a template of mine isn't calling a computed property.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue#6639]
I've got a component that has something like this:

```js
export default {
  computed: {
    foo: function() {
      console.log('foo')
      return [1,2,3,4,5]
    }
  }
}
```

and my template has something like this (parts omitted or renamed for clarity):

```html
                        <motor-node
                            v-for="n in circle1Range"
                            :rotation="`0 0 ${n * 360/48}`"
                        >
                            <motor-node>
                                <motor-node
                                    :absolutesize="`10 ${16 * ((foo[n]-1) * 5 + 1)}`"
                                >
                                </motor-node>
                            </motor-node>
                        </motor-node>
```

It renders a 3D scene using [`infamous`](https://github.com/trusktr/infamous), but the absolutesize attribute isn't being animated, because the `foo` computed property method is never called.

Is that expression perhaps too complex, and Vue doesn't detect the property to call?

**Comment by trusktr** [comment]
Assume `circle1Range` is `[1,2,3,4,5]`.

**Comment by nickmessing** [comment]
@trusktr, it is called once and vue [caches](https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods) it afterwards. Please use [official chat](https://chat.vuejs.org) or [forum](https://forum.vuejs.org) to ask questions.

**Comment by trusktr** [comment]
Interesting, I was wondering about this, and this is indeed a good feature!

However, even so, "foo" is NEVER logged. Let me see what's going on...

Also, indeed, after I saw the boy's message I made a forum post instead.

Thanks!

**Comment by trusktr** [comment]
Sorry, I was wrong, I misread my output, it is indeed logged once. Thanks for the tip!

So, as a rule of thumb, I should only use computed properties if I expect every time they will be used is exactly every time one of their dependencies will have changed.

Question: how do we do this if the dependency is an array, and I don't want to make new arrays at 60fps when I'm animating? I am changing values in the array. Do you recommend simply just using a method in that case?

**Comment by trusktr** [comment]
Nevermind that, I'll ask in the forums, and delete the questions here.

**Comment by nickmessing** [comment]
@trusktr, you can change values with `Vue.set` instead of `this.arr[index] =`, check [known caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats)
