### ISSUE TITLE
Embed HTML into an HTML5 SVG fragment got wrong namespace in template

### ISSUE THREAD

**Issue by rrandom** [vuejs/vue#6642]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/sn7o1mm3/](https://jsfiddle.net/sn7o1mm3/)

### Steps to reproduce
Embed `<p  xmlns="http://www.w3.org/1999/xhtml">` in the svg <foreignObject> element 

### What is expected?
the `<p>` should be rendered as a htmlElment and show.

### What is actually happening?
`<p>` did not show

---
seems related to this https://github.com/vuejs/vue/issues/6506

**Comment by defcc** [comment]
Thanks @rrandom . An issue related with #6506

A svg namespace now is attached to the `p` element within `foreignObject`, so it gets an unexpected behavior.

I'm trying to fix it.

**Comment by javoski** [comment]
Seems that the tag parameter of method `createElementNS` is case-sensitive.
