### ISSUE TITLE
目前vue中有使用到react吗？是不是可以放心使用，不会增加附加协议

### ISSUE THREAD

**Issue by haojieguangxin** [vuejs/vue#6643]
### What problem does this feature solve?
如题，开源使用问题

### What does the proposed API look like?
无

**Comment by isLishude** [comment]
你这个提的，真有些人让人无语了。

Vue使用MIT协议，并且和React半毛钱没有。

**Comment by greenwichmt** [comment]
Please read the licence [MIT](https://opensource.org/licenses/MIT)

**Comment by yyx990803** [comment]
MIT 协议不存在类似问题。

**Comment by haojieguangxin** [comment]
我知道MIT协议没有这个问题，BSD同样是宽松的协议，但是fb还是给加了附加协议。我问的主要是Vue中有没有用到React的核心代码的一部分，因为好像Vue2.0中也增加了虚拟dom相关的部分，所以只是有点担心而已，可能对于vue还没有深入的了解，真是抱歉。不过谢谢尤雨溪的回复，非常感谢

**Comment by yyx990803** [comment]
没有，是完全不一样的实现。
