### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by nozhdelov** [vuejs/vue#6645]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/vmh5xm6z/](https://jsfiddle.net/vmh5xm6z/)

Async components can not be instantiated programmatically and manually mounted in the DOM

### Steps to reproduce

When I try to manually create an instance of the async component I must provide a resolve function in the constructor for the component to work. However I can not find any method that is exposed in Vue.js to do that

### What is expected?
the return constructor function after component registration should have the correct resolver inside supplied by Vue

### What is actually happening?
Vue.component just returns the function supplied in the component registration

**Comment by yyx990803** [comment]
That's expected behavior. How do you instantiate something that isn't even resolved yet?

**Comment by nozhdelov** [comment]
Yes, I want to instantiate a component that is not resolved yet. 
I think this is more of a feature suggestion  :). It would be nice if async components can be used the same way as the normal ones. 
Currently I can not find any way that Vue exposes to manually resolve the component.
