### ISSUE TITLE
Facilitate .extend logic in .vue files.

### ISSUE THREAD

**Issue by ajm5774** [vuejs/vue#6646]
### What problem does this feature solve?
Component extension in the .vue files makes components logic more encapsulated and its clear if a component is a subcomponent of another by only looking at the subcomponent file. Otherwise, coders have to decipher this from comments or from inspecting the registration file manually.

Right now registration looks like this:
```Javascript
// index.js
var baseCtor = Vue.extend(Base);
var subCtor = baseCtor.extend(Sub)
Vue.component(baseCtor.extendOptions.name, baseCtor);
Vue.component(subCtor.extendOptions.name, subCtor);
Vue.component(SubSub.name, subCtor.extend(SubSub));
```

Ideally sub components would have the name populated as the sub components name, but right now it defaults to "VueComponent". Therefore the name has to be pulled from the 'extendOptions' property.

### What does the proposed API look like?
Ideally, registration would look like this:
```Javascript
// index.js
Vue.component(Base.name, Base);
Vue.component(Sub.name, Sub);
Vue.component(SubSub.name, SubSub);
```

**Comment by yyx990803** [comment]
I'm not sure if I understand your issue. Are you aware of the [`extends` option](https://vuejs.org/v2/api/#extends)?

**Comment by yyx990803** [comment]
Re-read the issue, you can just do this:

``` js
// index.js
Vue.component(Base.options.name, Base);
Vue.component(Sub.options.name, Sub);
Vue.component(SubSub.options.name, SubSub);
```
