### ISSUE TITLE
Specifying $emits for automatic documentation and validation

### ISSUE THREAD

**Issue by coolcorey** [vuejs/vue#6647]
### What problem does this feature solve?
As it is, we can specify the props, their name, type, a validator, all that jazz. Some documenting tools take advantage of this in order to create documentation of the component. To make documentation more useful, I think adding an optional 'emits' specification would help better specify the ins and the outs of the component. I suppose that, validation could be added to this specification to ensure that $emit events don't emit payloads in an unspecified format, which would protect the parent from getting screwy data.

### What does the proposed API look like?
```javascript
emits: {
  formCompleted: {
    payload: {
      type: 'object',
      properties: {
        name: 'string',
        age: 'number',
        gunch: {
          type: 'number',
          validator: function(value) {
            return value < 5;
          }
        }
      }
    }
  },
  nameEntered: {
    payload: {
      type: 'string'
    }
  },
  buttonClicked: 'string' // or null since it doesn't have a payload?
}
```

**Comment by posva** [comment]
More or less dup of #6040 
Closing because of the comment https://github.com/vuejs/vue/issues/6040#issuecomment-313658773

About payload checks, That is something that can and should be handled with typings like Typescript
