### ISSUE TITLE
Support reactive properties on array and function

### ISSUE THREAD

**Issue by mokkabonna** [vuejs/vue#6648]
### What problem does this feature solve?

Enables simpler syntax and more consistent behaviour.

It would be nice if you could add reactive properties to a function or an array. Currently only object works.

See this fiddle for an example: https://jsfiddle.net/r64e77ge/4/
Notice how `b` and `c` does not update when the child value is toggled. (they do however update when a.value is toggled if they had been toggled first)

```html
<div id="app">
  a.value {{a.value}}<button @click="a.value = !a.value">Toggle</button><br>
  b.value {{b.value}}<button @click="b.value = !b.value">Toggle</button><br>
  c.value {{c.value}}<button @click="c.value = !c.value">Toggle</button><br>
</div>
```

```js
new Vue({
  el: '#app',
  data: function() {
    var a = {}
    var b = []
    var c = function(){}
    
    a.value = true
    b.value = true
    c.value = true
    
    return {
      a: a,
      b: b,
      c: c
    }
  }
})
````

My use case is this plugin:
https://github.com/mokkabonna/vue-async-methods

Functions and arrays are not treated as objects that can have their own child reactive properties even though they in fact can.

Because of this limitation I had to place the method itself on a child `fetchData.execute` property instead of `fetchData` itself.

This is especially clunky when calling the method from code: `this.fetchData.execute()` separates the async methods from normal methods that can be called with `this.fetchData()`

### What does the proposed API look like?
I see no technical challenges in treating functions and arrays as objects that can have their own reactive properties. And I suspect the change in the code is also just a small one.

The changes should be here:
https://github.com/vuejs/vue/blob/dev/src/core/observer/index.js#L108

and here:
https://github.com/vuejs/vue/blob/dev/src/core/observer/index.js#L117

A quick change to those lines makes my fiddle work as expected for function at least.

**Comment by posva** [comment]
mmh, I don't understand the point of your use case (your lib), is it to just have a component gather the errors?
To me, adding properties to arrays or functions (which are rarely in data, but can be) is for locally adding functionality but not adding it for the reactivity.

**Comment by HerringtonDarkholme** [comment]
@posva 
OP's lib allow users to declare asyncMethods on vm instance, say `fetchComments`. 
Then it will transform the async method and add corresponding data property, e.g. `comments`. 

Also, `fetchComments` itself will have special properties like `isResolved` to indicate if the async method has completed. 

OP can try `Vue.set` or `vm.$forceUpdate` to notify re-rendering. Or, vue-rx is also an alternative.

IMHO, Vue skip watching on non plain objects on intention.  https://vuejs.org/v2/api/#data
Supporting watching on Function/Array needs to handle many more edge cases.

**Comment by posva** [comment]
Thanks for the explanation @HerringtonDarkholme 🙂 

> Because of this limitation I had to place the method itself on a child fetchData.execute property instead of fetchData itself.
>
> This is especially clunky when calling the method from code: this.fetchData.execute() separates the async methods from normal methods that can be called with this.fetchData()

I understand it may feel clunky for your usecase. Using a different variable name can make things better: `this.dataFetcher.execute()`
Personally, I prefer to have serializable data on `data` and move that kind of state to a store + methods, to a component or, to the root instance

**Comment by mokkabonna** [comment]
Here are some code that illustrates the changes needed. As well as a couple of added tests. 
https://github.com/vuejs/vue/compare/dev...mokkabonna:dev

npm test runs 100% ok, no existing tests fail.

**Comment by noid2** [comment]
I'm new to Vue Js. 

Please check this fiddle [https://jsfiddle.net/noid20/z7ve1yud/](url)
it show that you can use reactivity with arrays and functions with a little trick.
please comment out the paragraph to see the effect that I dont understand in Vue Js

**Comment by mokkabonna** [comment]
I don't think that really makes it reactive, it just happens to update since another property also changes. So I suspect using b.value in a computed will not make the computed reevaluate if b.value changes.

**Comment by ascott18** [comment]
@HerringtonDarkholme If it is undesirable to add this functionality as a universal behavior, would it be possible to add it as an explicit operation instead? Something like `Vue.observeFunctionProps(func)` (and a `$vm` instance counterpart) that would be called in `mounted() {}`

I'm working on something quite similar to @mokkabonna's library - representing an async action as a function that will invoke the action with properties representing the state. This approach, if it were an option with Vue's reactivity system, lends itself to a really clean way to represent the state of async behavior in a UI (in my opinion, anyway). 

You end up with something like this:
``` js
export default {
  data: {
    fetchComments: new FetchCommentsEndpointState()
  }
}
```
``` html
<button @click="fetchComments()" :disabled="fetchComments.isLoading">
{{ fetchComments.isLoading ? "Loading..." : "Fetch Comments" }}
</button>
<div v-if="fetchComments.isLoaded">
<ul v-if="fetchComments.wasSuccessful">
  <li v-for="comment in fetchComments.result">{{comment.body}}</li>
</ul>
<h3 v-else class="error">
  {{ fetchComments.errorMessage }}
</h3>
</div>
```

**Comment by ascott18** [comment]
I'll add that I'm able to make this work with `Vue.util.defineReactive`, manually calling it on each property I want to be reactive.

**Comment by yyx990803** [comment]
I don't think we'd want to support arbitrary properties on non-Object types, at least not the default because this is a rare (and non-recommended) usage, with a performance overhead (need to do extra property enumerations on function and arrays on initial observation).

@ascott18 yes, explicitly calling `Vue.util.defineReactive` is the possible workaround.

**Comment by mokkabonna** [comment]
I don't know how I missed that, but calling `Vue.util.defineReactive` manually did the trick. My use case is solved, I have published a new npm version.
