### ISSUE TITLE
vue-html-loader在webpack2.0 如何配置

### ISSUE THREAD

**Issue by alenyu** [vuejs/vue#6650]
### Version
2.4.4

### Steps to reproduce
在webpack新版本中无法配置

### What is expected?
在.vue中的template中能够include外部html或vue的template片段

### What is actually happening?
在webpack新版本中无法配置

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
