### ISSUE TITLE
.sync modifier doesn't work as expected

### ISSUE THREAD

**Issue by mrg0lden** [vuejs/vue#6652]
### Version
2.4.3

### Reproduction link
[https://jsfiddle.net/q985s20b/3/](https://jsfiddle.net/q985s20b/3/)

### Steps to reproduce
1. Make a component that renders a list of elements, one of them has 'active' class.
1. Use @click to handle clicks on any of the rendered elements
1. if an element is clicked, a method is called
1. that method will get the index of the clickd element, remove the 'active' class from the current active element, and add it to the clicked element.

### What is expected?
:class would add '.active' to the clicked element no matter what it's order.

### What is actually happening?
:class doesn't react when changing from the first element to the last element

**Comment by posva** [comment]
You just forgot to add `active` to every element in the array: https://jsfiddle.net/63rykfwq/
