### ISSUE TITLE
Does vue have more event directives as it does in angular js 1

### ISSUE THREAD

**Issue by mithublue** [vuejs/vue#6653]
I have worked in angular js , and found that there are many directives in it. There were many event directive as well e.g: ng-click, ng-dblclick etc and many more. Does vuejs has all or more directives like angular. If you can bring them all, it will be a nice and exciting addition I guess.
List of directives on angular
https://www.w3schools.com/angular/angular_ref_directives.asp

**Comment by sirlancelot** [comment]
Vue supports all standard DOM events: https://vuejs.org/v2/guide/events.html
