### ISSUE TITLE
On click pb

### ISSUE THREAD

**Issue by nlefebvre1410** [vuejs/vue#6663]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/nlefebvre/50wL7mdz/63595/](https://jsfiddle.net/nlefebvre/50wL7mdz/63595/)

### Steps to reproduce
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <h2>Essential Links</h2>

    <div id="example-3">
      <button @click="say('hi')">Say hi</button>
      <button @click="say('what')">Say what</button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'hello',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  methodes: {
    say (message) {
      alert(message)
    }
  }
}
</script>

<style scoped>
h1, h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>

### What is expected?
hello help my please.
hi version 2.4.2 webpack

### What is actually happening?
vue.esm.js?65d7:476 [Vue warn]: Property or method "say" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

Uncaught TypeError: _vm.say is not a function
at click (Hello.vue?c7e1:16)
at HTMLButtonElement.invoker (vue.esm.js?65d7:1821)

**Comment by AlekseyPleshkov** [comment]
Hi. Rename 'methodes' to 'methods'.

`
methods: {
say: function (message) {
// ...
}
}
`

**Comment by nlefebvre1410** [comment]
sorry
thank you
