### ISSUE TITLE
@event.prevent doesn't work properly

### ISSUE THREAD

**Issue by Gotterbild** [vuejs/vue#6671]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/cto5Ljam/5/](https://jsfiddle.net/cto5Ljam/5/)

### Steps to reproduce
1. Open a fiddle in Chrome.
1.1. Try to scroll up/down while over green block (#child). 
   Scroll will occur as it should as it is NOT prevented.
1.2. Try to scroll up/down while over red block (#parent). 
   Scroll will NOT occur as it should as it IS prevented.

So, in Chrome works as expected.

2. Open a fiddle in Firefox.
2.1. Try to scroll up/down while over green block (#child). 
2.2. Try to scroll up/down while over red block (#parent). 

Scroll will occur in both cases, which is a bug.

Versions of browsers I used:
Chromium 60.0.3112.113 (64-bit)
Firefox 55.0.2 (64-bit)

My OS: Linux Ubuntu 16.04 with GNOME as desktop environment

### What is expected?
$event.prevent should preventDefault() in Firefox

### What is actually happening?
$event.prevent is not preventing

---
Maybe should add `return false`

**Comment by posva** [comment]
The problem is not related to Vue as it happens with plain js: https://jsfiddle.net/wnnrhcju/

**Comment by kyalha** [comment]
@posva  I have currently the same problem here, a child will get the scroll and I try to stop the event propagation to the parent but it does not work. You talk about plain JS, but is there any solution ?
