### ISSUE TITLE
Loss of jQuery event listening from v1.0.28 to 2.4.4

### ISSUE THREAD

**Issue by strider4560** [vuejs/vue#6673]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/63794/](https://jsfiddle.net/50wL7mdz/63794/)

### Steps to reproduce
In the attached JSFiddle example, you will see that using the plugin to modify the date does not trigger a change in "dateVal" -- however, if you comment out the line that imports Vue 2.4.4, and uncomment the line that imports Vue 1.0.28, you will see that the plugin does trigger the change in "dateVal".

### What is expected?
A change in the value triggered by jQuery should trigger the change event for the Vue object.

### What is actually happening?
The vue data does not update after a change in the value from jQuery.

---
I dug as best as I could into how Vue 1 and Vue 2 listen to events. From what I can tell, Vue 1 had a block of code that would listen for jQuery events as well, while Vue 2 only listens to native events. This block of code is lines 4900 - 4912 in the Vue 1.0.28 code base.

**Comment by yyx990803** [comment]
Vue 2 replaces the DOM element it is mounted to, so make sure to instantiate your jQuery plugin **after** mounting your Vue instance, preferably in the `mounted` hook.

**Comment by strider4560** [comment]
The still doesn't work. Here's a JSFiddle where you can initialize it by clicking a button. It initializes it, but still doesn't update the data field.

https://jsfiddle.net/50wL7mdz/63805/

Just for good measure, here's one with the initialize in mounted, which also doesn't work:
https://jsfiddle.net/50wL7mdz/63808/

Both work in Vue 1 (if you change "mounted" to "ready")

**Comment by yyx990803** [comment]
That's right, Vue 2 also dropped support for jQuery events... So you need to proxy your jQuery events to a real, native DOM event.
