### ISSUE TITLE
Please enhance Custom Directives

### ISSUE THREAD

**Issue by tochoromero** [vuejs/vue#6680]
### What problem does this feature solve?
Let me start by saying I love Vue. It is an awesome framework you guys have created, I enjoy using it, and it is at the very top of Frameworks of choice.

But from day one there has been one small area where I found Vue lacking, this is in the Custom Directives department.

I wasn't around for Vue 1, but from what I can gather a decision was made to "underpower" Custom Directives in favor of Components. And I agree, when you are developing applications Components is most likely all you need.

The problem starts when you want to create plugins, especially UI plugins. I have created UI plugins in other Frameworks, specifically a Bootstrap native implementation, I have several features that are implemented with Custom Directives, I like how clean they are that way. But when I tried to achieve the same thing with Vue, well I got frustrated very quickly.

Problem Number 1: We don't have a Vue instance. I wish we could create Custom Directives the Same way we create Custom Components. so we have an actual Vue Instance and we can use this. Right now you have to manually extract the directive bindings and store them in the in the element itself. It is not clean since I have to pass the el object around to have access to those properties. It is doable but not very clean.

Problem Number 2: The update hook function it is not being called consistently. For instance, I have this: v-myDirective={foo: bar}; when bar changes the update method is not called, only when something in the DOM changes then update is called. This is super frustrating because many times you want to control the state of your directive based off a property value, but you have no consistent way to know if its value has changed. This is a real problem because there are things that cannot be done without a consistent way to know if a binded property has changed. I wish I could have a Vue instance and have watch methods to react to changes accordingly.

I LOVE Vue, it is an awesome framework, I will continue to enjoy using it and to recommend it. But if this is improved I would have absolutely no reason to ever use any other framework.

Thanks for the hard work and love that goes into Vue.

### What does the proposed API look like?
The API will basically be the same one we have for Custom Components. The example is silly, but I would love to be able to do something like this:

```
Vue.directive('myDirective', {
  data: {
    el: null
  },
  props: ['foo', 'name'],
  bind (el, binding, vnode, oldVnode) {
    this.el = el
    //Bind
  },
  inserted (el, binding, vnode, oldVnode) {
    //Inserted
  },
  unbind (el, binding, vnode, oldVnode) {
    //Unbind
  },
  computed: {
    name () { return `My name is ${this.name}`}
  },
  watch: {
    name (value) { this.nameUpdated(value)}
  },
  methods: {
    nameUpdated (value) {
      this.$emit('nameUpdated', value)
    }
  }
})
```

**Comment by Akryum** [comment]
Why using directives and not components? The API you are suggesting is very close to what already exist for the components.

**Comment by posva** [comment]
>  I wish we could create Custom Directives the Same way we create Custom Components

I think that sentence says it all 😅

**Comment by tochoromero** [comment]
The API can be the same, but the usage is different.

**Comment by yyx990803** [comment]
I appreciate your support for Vue, but the proposed API is not something we would consider. Vue 1 used to have similar functionalities for directives but we end up duplicating **everything** between directives and components, and the concept becomes convoluted similar to Angular 1 directives (which is essentially a god concept that can do anything).

It was an intentional decision in Vue 2 to limit directives to one dedicated purpose: low level DOM manipulation and nothing else. Also, due to the rendering mechanism (vdom), directives do not have instances and thus component-like API is not feasible in the first place (no `this` to point to).

Most of the time what you want to achieve with directives can be achieved with components, and some of the functionalities can be simulated by leveraging `vnode.context` in directive hooks.

**Comment by tochoromero** [comment]
I understand the reasoning behind it, and it is cool. I have been able to do everything I need with a custom attribute but one thing.
If I have a binding like this `v-myDirective={foo: bar}` and let's say you click a button and the value of `bar` changes, the `update` hook function is not called. I haven't found a way to react to such changes. Any suggestions?

**Comment by yyx990803** [comment]
@tochoromero that sounds like a bug - please open a separate issue with a reproduction.

**Comment by tochoromero** [comment]
@yyx990803 That was actually my bad, there is no bug, trying to reproduce it with the bare minimum showed me my own bug. Thank you for taking the time to answer here, you rock :)
