### ISSUE TITLE
异步注册组件的require是否可以修改为import更合适

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6682]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/j0q12fsh/36/](https://jsfiddle.net/j0q12fsh/36/)

### Steps to reproduce
异步注册组件的require是否可以修改为import更合适.
因为可能我的vue文件是用ts写的,通过require会报错,
需要手动添加require到d.ts

### What is expected?
.

### What is actually happening?
.

---
.

**Comment by yangdan8** [comment]
![qq 20170925115412](https://user-images.githubusercontent.com/16515026/30791860-50489694-a1e8-11e7-851e-0d4f714da768.png)

**Comment by yangdan8** [comment]
![777777](https://user-images.githubusercontent.com/16515026/30791872-6c154b42-a1e8-11e7-840c-e1e822f1df91.gif)

**Comment by yyx990803** [comment]
You can already use `import` for async components. Please read the [docs](https://vuejs.org/v2/guide/components.html#Async-Components)
