### ISSUE TITLE
插件挂载有点问题

### ISSUE THREAD

**Issue by GoNtte** [vuejs/vue#6685]
### Version
2.4.2

### Reproduction link
[https://new-issue.vuejs.org/                                                                                                                                                 ](https://new-issue.vuejs.org/                                                                                                                                                 )

### Steps to reproduce
使用vue-cli创建的工程，vue版本2.4.2
```javascript
src/components/message/message.vue:

<template>
  <transition name="el-message-fade">
    <div v-show="visible" class="my-msg">{{message}}</div>
  </transition>
</template>
<script>
export default{
  data () {
    return {
      message: 'plugin',
      visible: true
    }
  }
}
</script>

src/components/message/message.js:

import Vue from 'vue'

let AlertConstructor = Vue.extend(require('./message.vue'))

let instance
let msg = function (options) {
  instance = new AlertConstructor()
  instance = instance.$mount(document.createElement('div'))
  document.body.appendChild(instance.$el)
  return instance
}

export default msg
```
在app.vue里,
import Message from './components/message/message.js'

### What is expected?
期望能像旧版本一样正常显示

### What is actually happening?
点击vue logo调用Message(),只有一个空的div在页面上，并没有出现message的内容
以上代码在vue2.3.4里运行正常

**Comment by yyx990803** [comment]
请按照要求好好给重现。

**Comment by MaySnow** [comment]
用 import message from './message.vue'  代替 require('./message.vue')

`import Vue from 'vue'
import message from './message.vue'
let AlertConstructor = Vue.extend(message)`

**Comment by MaySnow** [comment]
用 import message from './message.vue' 代替 require('./message.vue')

`import Vue from 'vue' 

import message from './message.vue' 

let AlertConstructor = Vue.extend(message)`

**Comment by skottiewang** [comment]
@MaySnow 我也出现了这个问题，用你的方法解决了，能解释下为啥吗？
查了下require与import，貌似用在这里没啥区别啊～
https://github.com/ElemeFE/mint-ui/blob/master/packages/toast/src/toast.js
mint的源码也这样写的

**Comment by GoNtte** [comment]
@skottiewang 
[对照这个issue看](https://github.com/vuejs/vue/issues/6693)

**Comment by MaySnow** [comment]
You can mix require and export. You can't mix import and module.exports.

https://github.com/webpack/webpack/issues/4039

2017-12-31 16:57 GMT+08:00 skottiewang <notifications@github.com>:
