### ISSUE TITLE
Allow multiple `template` definition

### ISSUE THREAD

**Issue by danilosampaio** [vuejs/vue#6688]
### What problem does this feature solve?
Re-use the component's logic for any visual framework (bootstrap, semantic-ui, material-design, etc.)
You may be thinking: can't this be achieved by using themes?
Not always. Most visual frameworks are not just CSSs, it also manipulates
DOM, so that just theming doesn't solve it.

Proposal: Allow multiple `template` definition, and through the global API, set the default template (User Interface).

### What does the proposed API look like?
Example:

```js
<!-- bootstrap template -->
<template ui="bootstrap">
	<ul class="list-group">
		<li v-for="i in items" class="list-group-item">
			{{i.name}}
		</li>
	</ul>
</template>

<!-- semantic-ui template -->
<template ui="semantic-ui">
	<div class="ui list">
		<div v-for="i in items" class="item">
			{{i.name}}
		</div>
	</div>
</template>

<!-- reusable component logic -->
<script type="text/javascript">
	export default {
		props: ['items'],
		mounted () {
			if (Vue.config.defaultTemplate == 'semantic-ui') {
				//Semantic-UI javascript boilerplate
			}
		}
	}
</script>
```

```js
//Main module

// set the default UI framework to Semantic-UI
Vue.config.defaultTemplate = 'semantic-ui'
```

**Comment by yyx990803** [comment]
Instead of an API like this, you can simply define two components with override:

``` js
const BaseLogic = { ... }

const BootstrapVersion = {
  ...BaseLogic,
  template: '#bootstrap'
}

const SemanticUIVersion = {
  ...BaseLogic,
  template: '#semantic-ui'
}
```

**Comment by danilosampaio** [comment]
Thanks @yyx990803
