### ISSUE TITLE
$mount not work properly in the plugin

### ISSUE THREAD

**Issue by GoNtte** [vuejs/vue#6693]
### Version
2.4.2

### Reproduction link
[https://github.com/GoNtte/plugin](https://github.com/GoNtte/plugin)

### Steps to reproduce
run the project, click vue logo.
Click the method call the message plugin

### What is expected?
in the page should show text: vue plugin

### What is actually happening?
plugin message don't show up properly, only show a empty div node

---
The code works fine in vue2.3.4

**Comment by yyx990803** [comment]
`vue-loader` 13+ exports an ES module now, so you need to do:

``` js
let MessageConstructor = Vue.extend(require('./message.vue').default)
```

**Comment by jamesXG** [comment]
why do this
