### ISSUE TITLE
Transition enter hook is unexpectedly triggered when v-show="false"

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#6695]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/co8pqyah/](https://jsfiddle.net/co8pqyah/)

### Steps to reproduce
just open the JSFiddle example.

### What is expected?
will not alert.

### What is actually happening?
alerted.

---
It's only occurred when wrap `<transition appear>`  on component, and use `v-show` to control the display of the child component.

**Comment by LinusBorg** [comment]
That's expected, I think. `v-show` renders the controlled content, it just hides it with `display: none;`.

So on initial render, your modal *is* rendered, and accordingly, because you defined `appear`, the transition is triggered and the `enter` hook is called.

I understand that you expect the transition not to run since you defined `v-show` with a `false` value in the parent component - but the child component can't know of this.

Solution: use `v-if` instead.

**Comment by fenivana** [comment]
For some reason I can't use `v-if`. I have a transition in transition design, if the outer container use `v-if` to control the display, the inner transition won't trigger when "show" set to false.

Modal.vue:
```vue
<template>
<transition appear> <!-- appear is the culprit -->
  <div v-show="show" class="modal" v-on="$listeners">
    <slot />
  </div>
</transition>
</template>
```

Component uses Modal:
```vue
<template>
  <modal v-show="show" class="confirm-popup"> <!-- HERE -->
    <fade-transition appear>
      <card class="container" v-show="show">  <!-- AND HERE -->
        <header class="title">
          <h3>{{ title }}</h3>
        </header>
        <div class="content">
          {{ content }}
        </div>
        <div class="btn-group">
          <v-button @click="confirm(false)" class="secondary">Cancel</v-button>
          <v-button @click="confirm(true)">{{ confirmText || 'OK'}}</v-button>
        </div>
      </card>
    </fade-transition>
  </modal>
</template>

<script>
  import Card from 'src/components/Card'
  import FadeTransition from 'src/components/FadeTransition'
  import Modal from 'src/components/Modal'
  import VButton from 'src/components/Button'

  export default {
    name: 'confirm-popup',
    components: { Card, FadeTransition, Modal, VButton },

    props: ['title', 'content', 'confirmText', 'resolve'],

    data: () => ({
      show: true
    }),

    created() {
      document.body.appendChild(this.$mount().$el)
    },

    methods: {
      confirm(bool) {
        this.show = false
        this.resolve(bool)

        setTimeout(() => {
          this.$destroy()
          document.body.removeChild(this.$el)
        }, 300)
      }
    }
  }
</script>
```

The only way I can do is to remove the `appear` prop and simulate the `appear` feature as:
```vue
<template>
<transition>
  <div v-show="show_" class="modal" v-on="$listeners">
    <slot />
  </div>
</transition>
</template>

<script>
  export default {
    props: ['show'],
    data: {
      show_: false
    },

    mounted() {
      this.$nextTick(() => this.show_ = this.show) // simulate the "appear" feature
    }
  }
</script>
```

**Comment by yyx990803** [comment]
This is expected behavior because `<transition>` is applied to the `<div>` wrapping your slot content. Whether the modal is shown is not its concern.
