### ISSUE TITLE
Fonts fail to load with @font-face url with sass

### ISSUE THREAD

**Issue by maziarz** [vuejs/vue#6699]
### Version
2.4.4

### Reproduction link
[https://github.com/maziarz/vue-pwa-font-test](https://github.com/maziarz/vue-pwa-font-test)

### Steps to reproduce
Simply pull the repository, `npm install` and `npm run dev`. 

### What is expected?
I expect that url-loader will handle the fonts.

### What is actually happening?
The font is not found.

```
This dependency was not found:

* assets/fonts/DIN/din_alternate_bold_1-webfont.ttf in ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7abf646a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"includePaths":["./src/assets/scss"],"data":"@import /"base.scss/";","sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Hello.vue

To install it, you can run: npm install --save assets/fonts/DIN/din_alternate_bold_1-webfont.ttf

```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is not related to vue, but you can put the font in the `/static` folder and refer to it as `/static/my-font`

**Comment by maziarz** [comment]
@posva, thanks for the reply, it felt a bit like a grey zone, i will try the forum and SO instead :-) Cheers.
