### ISSUE TITLE
Idea .:. Comment Block

### ISSUE THREAD

**Issue by jdriesen** [vuejs/vue#6706]
### What problem does this feature solve?
Hi,

Situation...
We're working with several persons on the same project.
We're searching for 'the best way' to comment our .vue files in the file itself.
We know we can use the normal HTML comment tags in our components (e.g. on top in the section.

We are wondering if this is the best and recommended solution....

Or ...
Wouldn't it be an idea to have a `<comment>` block available (like we have `<template>`, `<script>` and `<style>`) where we can type 'free' (meaning, non HTML) text
(and of course, this block is completely skipped during 'compile')

Thanks in advance for any reply or suggestion...

Kind regards,
Johnny

### What does the proposed API look like?
`<comment>`
This is some general information about this .vue file.
Text here can be FREE (ascii) text
`</comment>`

**Comment by posva** [comment]
> We know we can use the normal HTML comment tags in our components (e.g. on top in the section.
> 
> We are wondering if this is the best and recommended solution....

Yes. Not in JS, you can use `//` and `/*`

**Comment by jdriesen** [comment]
Hi,

I don't want to comment the code itself per line. (HTML or JS)
The question is in fact:
How can I 'describe' my components in a general way...

Grtz,
Johnny

**Comment by posva** [comment]
you can do that in many ways. Using comments at the top of the script tag would be my go. But generally, just comment your component as you would comment code

**Comment by pandemm** [comment]
I think the question was about a new block on single-file templates. Custom blocks are already possible and vue-loader has documentation regarding them here: https://vue-loader.vuejs.org/en/configurations/custom-blocks.html

So you can already use a <comment> block and it will be ignored by vue-loader

**Comment by jdriesen** [comment]
Thanks everybody for your time to reply.

@pandemm 
Indeed, a 'Custom block' will do the trick. (I didn't know about their existence)
Thank you for the link, and pointing me in the right direction.

Kind regards

**Comment by chriswaweru70** [comment]
how can i comment a block of code in vue.js
