### ISSUE TITLE
Can I use `appear-name` for <transition> component?

### ISSUE THREAD

**Issue by mjpclab** [vuejs/vue#6708]
### What problem does this feature solve?
I found the `appear-name` attribute works for <transition> component, which is not mentioned in API document: https://vuejs.org/v2/api/#transition
Since it is quite convenient, will it be supported officially?

Current example:
```html
<transition appear appear-class="fade" appear-to-class="fade-to" appear-active-class="fade-active">
```

Convenient way:
```html
<transition appear appear-name="fade">
```

### What does the proposed API look like?
```html
<transition appear appear-name="fade">
```

**Comment by yyx990803** [comment]
You can easily do this in userland by creating your own higher-order transition component:

``` js
Vue.component('enhanced-transition', {
  functional: true,
  render (h, { props, children }) {
    return h('transition', {
      props: {
         ...props,
         // expand props.appearName into appropriate classes here
      }
    }, children)
  }
})
```
