### ISSUE TITLE
add {{ }} analog for plain html

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue#6711]
### What problem does this feature solve?
by now we use v-html = "computed_property" directive
This is very uncomfortable because we need to add one computed property for every user input value in every component. 

Mixin method is not good for this because as I can understand from manual mixin function executes every time when any input. So mixin function for markdown will slow app very much.

### What does the proposed API look like?
It would be good if we have {{}} analog for plain html {{{ }}}
if so we can implement markdown filter inside mixin and use it as 
{{{ user_input_data_variable | markdown_filter_from_mixin }}}

thanks!

**Comment by yyx990803** [comment]
You can just use a method: `v-html="markdown(content)"`

**Comment by alexey2baranov** [comment]
markdown(content) will execute hundreds times per second and sliw down app. Computed property executed only once. Isnt it?

**Comment by yyx990803** [comment]
If you use `{{{ foo | filter }}}` that would execute multiple times the same way, so if you want caching you need to use a computed anyway.
