### ISSUE TITLE
multiple spaces in select/option won't go into v-model correctly

### ISSUE THREAD

**Issue by Liu233w** [vuejs/vue#6722]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/erqoxvr2/2/](https://jsfiddle.net/erqoxvr2/2/)

### Steps to reproduce
select `two spaces` or `three spaces`

### What is expected?
multiple spaces in the `<p>` tag, see jquery's behavior in http://jsfiddle.net/a3LwW/4/

### What is actually happening?
Only one space in the html.

Actually the variable `val` only have one space.

**Comment by KKSzymanowski** [comment]
How about storing the options on the Vue instance?
I know it doesn't fix the issue, but it might be a temporary workaround:
https://jsfiddle.net/mx80edg8/2/

**Comment by posva** [comment]
This is just how HTML works: it removes the spaces from the text of the `options`. So Vue gets the text with only one space. You can specify the value with spaces directly into the `option` element and it will yield the result you expect:

`<option value="hi   ho">hi ho</option>`

**Comment by yyx990803** [comment]
FYI:

``` js
var o = document.createElement('option')
o.textContent = 'many          spaces'
console.log(o.value) // 'many spaces'
```

In general you should never rely on multiple whitespaces in HTML text; use explicit `value` bindings.

**Comment by Liu233w** [comment]
Thank you for your replys, it solved my problem.
