### ISSUE TITLE
Typescript: augmenting ComponentOptions?

### ISSUE THREAD

**Issue by impworks** [vuejs/vue#6723]
Is it possible to augment the type definition for `ComponentOptions`?

I am using the [vue-inject](https://github.com/jpex-js/vue-inject) plugin which allows specifying the `dependencies` section in a component definition. Unfortunately, I can't get it to work the right way.

My `vue-augmented.d.ts` looks like this:

```
import Vue from "vue";

declare module "vue" {
    export type ComponentOptions<T> = {
        dependencies?: string | string[] | { [key: string]: string };
    }
}
```

Typescript throws an error:

```
[ts] Duplicate identifier 'ComponentOptions'.
```

P.S. It does work as expected if you hack the original `options.d.ts` file provided by Vue, but this solution is unacceptable :(

**Comment by HerringtonDarkholme** [comment]
https://vuejs.org/v2/guide/typescript.html#Declaring-Types-of-Vue-Plugins

**Comment by impworks** [comment]
@HerringtonDarkholme thanks!
