### ISSUE TITLE
Vue.js cannot use Axios wrapped in external function

### ISSUE THREAD

**Issue by taozhaolib** [vuejs/vue#6724]
The code:

export default {
    data: function() {
        return {
            tableData: [],
            tableColumns: [
                {show: 'firstName', label: 'First Name', dataType: ''},
                {show: 'lastName', label: 'Last Name', dataType: ''},
            ],
            showFilter: true,
        }
    },
    beforeMount: function(){
        this.tableData = Utils.getUserList()
    },
    components: {
        VueDataTable,
    },
}

In the Utils.js, the function getUserList:

export function getUserList(data) {
    axios({
        method: 'get',
        url: '/api/admin/users',
        dataType: 'json',
        headers: {'X-Requested-With': 'XMLHttpRequest'},
    })
    .then( (response) => {
        var status = response.status;
        if(status == 200 || status == "200"){
            console.log(response.data)
            data = response.data
        }
        else{
            alert("not 200");
            return;
        }                                   
    })
    .catch( (error) => {
        console.log(error);
    });
}

During runtime, I could not get the returned response.data for 'data = response.data', although the 'console.log(response.data)' does print out the data returned.

**Comment by taozhaolib** [comment]
Probably it is kind of out-of-sync issue but I am not sure how to solve this.

**Comment by sqal** [comment]
@taozhaolib 

1. You don't return anything  from `getUserList` function
2. This function is asynchronous so you can't just assign it to some variable like `this.tableData = Utils.getUserList()`

correct usage:

```js
export function getUserList() {
  // return promise
  return axios({
    method: 'get',
    url: '/api/admin/users',
    dataType: 'json',
    headers: {
      'X-Requested-With': 'XMLHttpRequest'
    },
  })
  .then(response => response.data)
}
```

and in your component:

```js
Utils.getUserList()
.then((data) => {
  this.tableData = data;
})
.catch((err) => {
  // oops, something happened
  // handle error here
});
```
