### ISSUE TITLE
Plugin global property cannot be used in computed

### ISSUE THREAD

**Issue by ventaquil** [vuejs/vue#6726]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/0epfuvja/3/](https://jsfiddle.net/0epfuvja/3/)

### Steps to reproduce
* Define global `Vue` property in custom plugin.
* Define instance property which reads data from global property.
* Load plugin.
* In application declare computed property which reads data from plugin instance's propety.
* Create application.
* Change global `Vue` property.
* Watch computed property.

### What is expected?
Computed property result new value.

### What is actually happening?
Computed property doesn't change. Vue also not do template re-render.

**Comment by posva** [comment]
That's normal, vue makes things added onto data reactive, but if you add something to `Vue` that won't be reactive. Here you have an example doing what you want: https://jsfiddle.net/gd11d31y/ by creating a new Vue instance with some data

**Comment by ventaquil** [comment]
@posva so how can I create reactive properties in plugin? Is it possible?

**Comment by posva** [comment]
look at the fiddle. You can also look at other plugins like vuex to see how they achieve reactivity
