### ISSUE TITLE
Watcher makes original object reactive

### ISSUE THREAD

**Issue by ndabAP** [vuejs/vue#6728]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/cckLd9te/198/](https://jsfiddle.net/cckLd9te/198/)

### Steps to reproduce
This may be related: https://github.com/vuejs/vue/issues/6616

```js
  data () {
    return {
      someData: [{
        id: 1
      }, {
      	id: 2
      }, {
      	id: 3
      }],
      
      emptyData: [],
      
      trigger: false
    }
  },
  
  watch: {
    trigger () {
      this.$set(this, 'emptyData', this.someData)
    }
  },
  
  methods: {
    setEmptyData (parameter) {
      this.$set(this.emptyData[2], 'id', parameter)
    }
  }
```

1. Set data from an existing data source through a watcher with Vues `$set` method
2. Mutate the set data
3. The original data used inside the watcher get's mutated, too

### What is expected?
Only the set data should be mutated.

### What is actually happening?
The originally and the newly set data are mutated.

---
Cloning at the watcher helps to prevent this. But I thought I'm on the safe side when I use `Vue.set`. I know that Vue can't detect property/array index changes/additions but I don't add/change the property/array index from the original data.

**Comment by yyx990803** [comment]
This is expected because it's just how JavaScript works. You are sharing the same object by reference. `Vue.set` has nothing to do with that. Cloning is the correct solution.

**Comment by ndabAP** [comment]
Thanks!
