### ISSUE TITLE
Make directives available to all components within a render tree

### ISSUE THREAD

**Issue by trainiac** [vuejs/vue#6732]
### What problem does this feature solve?
If you have a directive that relies on a piece of user data (e.g. language), in server side rendering you need to be able to create a new directive per request.  

```javascript
const getTranslateDirective = lang => ( {
  bind () {
    // access to lang
  },
  update () {
    // access to lang
  }
})

const translate = getTranslateDirective(() => parsedLangHeader.language)

// PROBLEM - this sets translate a directive globally across reqeusts
Vue.directive('translate', translate)
```

However this is a problem because when you call Vue.directive('translate', translate) this changes the translate directive across ALL requests. 

### What does the proposed API look like?
 What is needed is a way to make directives available to a component and all of  it's children components

```js
const getTranslateDirective = lang => ( {
  bind () {
    // access to lang
  },
  update () {
    // access to lang
  }
})

const translate = getTranslateDirective(() => parsedLangHeader.language)

new Vue({
  directives: {
    translate: {
      module: translate,
      provide: true // Makes the directive available to this component and all of it's children.
    }
  }
})
```

**Comment by yyx990803** [comment]
FYI directives on the server needs to be implemented in a completely different fashion (as VNode transforms) because there's no DOM access: https://ssr.vuejs.org/en/api.html#directives

Also, I don't see the point of creating fresh directive instances for each request. You should somehow inject `parsedLangHeader.language` into your app as a piece of application state so it can be accessed across the app instance for that request.

**Comment by trainiac** [comment]
@yyx990803 Thanks for taking the time to review this.  When you say

> You should somehow inject parsedLangHeader.language into your app as a piece of application state so it can be accessed across the app instance for that request.

I think for most cases that is appropriate but consider this example.  

A desired translation directed would be

```html
<div v-translate>Hello</div>
```
I could do this instead

```html
<div v-translate='$store.state.language'>Hello</div>
```
But this feels very verbose to have to do all over the application. 

Given Vue's exsiting API I dont see how you can avoid this.
