### ISSUE TITLE
Error During Build

### ISSUE THREAD

**Issue by Splode** [vuejs/vue#6733]
### Version
2.4.2

### Reproduction link
[https://github.com/Splode/lww-test](https://github.com/Splode/lww-test)

### Steps to reproduce
1. In CLI, `npm run build`

### What is expected?
Expected a Vue build without errors.

### What is actually happening?
Build process exits incomplete, with an error. Error seems to occur after CSS optimization process: 

```
| building for production...
Starting to optimize CSS...
Processing static/css/app.8e679f67219356a9327dea38c0984880.css...
Processed static/css/app.8e679f67219356a9327dea38c0984880.css, before: 38178, after: 38110, ratio: 99.82%
(node:12596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cyclic dependency: "[object Object]"
(node:12596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
 a non-zero exit code.
```

---
Dev server will run as expected with both `npm run dev` and `npm run start`.

Vue-CLI is version 2.9.1

**Comment by yyx990803** [comment]
This should be posted to [here](https://github.com/vuejs-templates/webpack)

Also, make sure to specify what changes you made after a fresh scaffold. Your repro has no commit history that we can look into.
