### ISSUE TITLE
Select v-model addEventListener('change') not firing

### ISSUE THREAD

**Issue by brianvoe** [vuejs/vue#6738]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/3q4wmuu4/3/](https://jsfiddle.net/3q4wmuu4/3/)

### Steps to reproduce
Just hit run

### What is expected?
Should expect the addEventListener change function to be triggered and update data value.

### What is actually happening?
Its not triggering select change event

---
I added an event listener to a select element and expect a change event to fire when the data the v-model is bound to changes.

I came across this because the package i built is an advanced select dropdown(slimselectjs.com) and i have an event listener attached to the main select element and it would be an extremely easy integration for people who added v-model to the select they are using instead for having to write code for change handlers and such.

Vuejs expect a trigger change on inputs to let the reactivity system know when somethings changed. Just curious as to why this isn't the other way around.

Thanks and keep up the good job!

**Comment by yyx990803** [comment]
This is expected behavior. Data changes only updates the DOM, but does **not** trigger events. Events are only triggered if the change came from user interaction.

If you have control, you should use a watcher instead of a DOM event listener; otherwise you'd have to manually dispatch a synthetic event from a watcher.

**Comment by brianvoe** [comment]
Are you referring to using watch()?

From the docs they say to not use it.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

If this isnt what you are referring to can you suggest something i can add via javascript that doesnt require me to do anything in vuejs that i can use to listen out for changes to the select that the v-model makes?

Thanks for you feedback and once again huge fan of vuejs I really appreciate this amazing framework you have built.

**Comment by LinusBorg** [comment]
No, he's talking abbout [Vue's Watchers](https://vuejs.org/v2/guide/computed.html#Watchers) which have nothing to do with those you linked to.
