### ISSUE TITLE
Using methods that mutates reactive properties from the DOM may cause infinite loops

### ISSUE THREAD

**Issue by Frondor** [vuejs/vue#6743]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/bpeq966a/](https://jsfiddle.net/bpeq966a/)

### Steps to reproduce
Create a method that updates a counter inside `data()`, use it to dynamically create HTML layouts, for example, calling it inside `v-class` to display a specific class depending on state.

### What is expected?
Vue should be smart enough to detect this behavior in methods.

### What is actually happening?
 Every time the counter updates, looks like Vue will re-render the component.
> [Vue warn]: You may have an infinite update loop in a component render function.

---
If this is working as intended, I'd like to know the best practice or alternative to this kind of issues.

**Comment by yyx990803** [comment]
This is expected behavior. Do this in `beforeUpdate` hook instead.
