### ISSUE TITLE
Improve docs for lodash throttle/debounce with watch

### ISSUE THREAD

**Issue by joshribakoff** [vuejs/vue#6754]
### What problem does this feature solve?
Components may need to render less often than the state updates, for example you may have a realtime chart accompanied by a numerical display of the latest value, which should update less often than the chart. There may be multiple such components on the page at once.

In the docs here https://vuejs.org/v2/guide/computed.html#Watchers it shows how to debounce a method improperly. Try creating a simple timer component & put multiple on the page, there are race conditions the same as if you forgot to wrap data in a function. If you follow the examples in the docs, the components interfere with each other. Only one timer updates per second, instead of all timers updating every second.
```
getAnswer: _.debounce(function() { 
} )
```
### What does the proposed API look like?
Change the docs to show proper usage of debouncing a vue.js method, which is wrapping in a function, just like the data object. If you do this, multiple components on the page no longer interfere with each other.
```
computed: {
        tick: function () {
            return _.throttle(() => {
                this.time =  new Date()
            },1000)
        }
    }
```

In your watch method, you then have to call `this.tick()`. This is not intuitive & the docs instruct you to create an app with race conditions instead. Ideally we could use some sort of syntactic sugar or something rxJS like instead of lodash & thunks which are verbose & clumsy.

Furthermore, the user has to put the throttled method in the computed property instead of the methods property, which is also not documented & not intuitive.

**Comment by yyx990803** [comment]
Please open a pull request at vuejs/vuejs.org instead of a feature request here.
