### ISSUE TITLE
微软已经出了一个vue ts的demo是否考虑修改vue.d.ts更合适？

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6756]
### Version
2.4.4

### Reproduction link
[https://github.com/Microsoft/TypeScript-Vue-Starter](https://github.com/Microsoft/TypeScript-Vue-Starter)

### Steps to reproduce
vue.d.ts没有使用默认导出，是否考虑修改为微软推荐的？

### What is expected?
vue.d.ts没有使用默认导出

### What is actually happening?
没有使用默认导出

---
是否考虑修改为微软推荐的

![qq 20170924214206](https://user-images.githubusercontent.com/16515026/31315107-bef7e94a-ac43-11e7-831a-78bd210bdb67.png)

**Comment by yyx990803** [comment]
已经 merge 了
