### ISSUE TITLE
你确定这么写js没有错误?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#6757]
### Version
2.4.4

### Reproduction link
[https://github.com/vuejs/vue-router/blob/dev/src/index.js](https://github.com/vuejs/vue-router/blob/dev/src/index.js)

### Steps to reproduce
这么写法是ts才有的,而且import是错误的

### What is expected?
这么写法是ts才有的,而且import是错误的

### What is actually happening?
这么写法是ts才有的,而且import是错误的

---
这么写法是ts才有的,而且import是错误的

![qq 20171008230944](https://user-images.githubusercontent.com/16515026/31318055-805ff5de-ac7e-11e7-923b-05b19099846d.png)

**Comment by galenyuan** [comment]
https://github.com/vuejs/vue-router/blob/dev/build/build.js#L70
https://flow.org/blog/2015/02/18/Import-Types/

**Comment by fnlctrl** [comment]
这是flow的写法，见galenyuan的回复

**Comment by yangdan8** [comment]
谢谢!简单的东西弄复杂了,现在打个包能成功,无法运行,提示router为undefined
