### ISSUE TITLE
Element id encapsulation [Feature Request]

### ISSUE THREAD

**Issue by alshdavid** [vuejs/vue#6762]
Hi, first off really like Vue.

I have some minor gripes with the component system. I feel it should be more encapsulating and flexible as Vue is more of a drag/drop lib than a platform and the components act more like html imports than web components.

![image](https://user-images.githubusercontent.com/12656294/31364944-a510ae9a-adc4-11e7-92d0-84bc0bee04d6.png)

That example isn't proper code, but a general illustration.

Would be cool if we could do something like this:

![image](https://user-images.githubusercontent.com/12656294/31364969-cecf82ce-adc4-11e7-9632-8da9aa4419bf.png)

This way I could bootstrap an external library within a component without side effects

**Comment by sirlancelot** [comment]
Use `v-ref`
