### ISSUE TITLE
A way to inspect scoped slot value

### ISSUE THREAD

**Issue by maple3142** [vuejs/vue#6765]
### What problem does this feature solve?
When I don't know what properties does a scoped slot have, I can log it to console.

[current approach](https://jsfiddle.net/dqfsx232/)

### What does the proposed API look like?
Add a function like `inspect()` `log()`... to print value in template.

**Comment by posva** [comment]
I don't think you should console.log in your template. As you saw, this is easily doable in userland.
You can also add `Vue.prototype.$log = console.log` and then call `$log` in the template
