### ISSUE TITLE
I can't use 'npm install vue-template-compiler',It report error.

### ISSUE THREAD

**Issue by janostudio** [vuejs/vue#6772]
### Version
2.4.4

### Reproduction link
[https://google.com](https://google.com)

### Steps to reproduce
I use 'npm install vue-template-compiler',but it callback an error.And I can't install the plugins.
ERROR INFO:
silly fetchPackageMetaData sum":"d7aba6375c8f4ac4242a7e874d30a10cfdf199bd","size":43532,"noattac
3188 silly fetchPackageMetaData                                                                      ^
3189 verbose stack SyntaxError: Unexpected end of input at 1:19455
3189 verbose stack sum":"d7aba6375c8f4ac4242a7e874d30a10cfdf199bd","size":43532,"noattac

### What is expected?
Just install vue-template-compiler

### What is actually happening?
ERROR INFO:
silly fetchPackageMetaData sum":"d7aba6375c8f4ac4242a7e874d30a10cfdf199bd","size":43532,"noattac
3188 silly fetchPackageMetaData                                                                      ^
3189 verbose stack SyntaxError: Unexpected end of input at 1:19455
3189 verbose stack sum":"d7aba6375c8f4ac4242a7e874d30a10cfdf199bd","size":43532,"noattac

---
node v8.4.0 npm v5.3.0

**Comment by yyx990803** [comment]
That's either NPM or your network's problem.
