### ISSUE TITLE
路由replace到另一个路由的时候，如果使用了next转跳，则后续页面历史回退有误

### ISSUE THREAD

**Issue by Alphmega** [vuejs/vue#6773]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/50wL7mdz/67938/](https://jsfiddle.net/50wL7mdz/67938/)

### Steps to reproduce
1. 从页面 /home 跳到另一个页面 /page1
2. page1 需要登录并 replace 转跳到 /login，
3. login只定义了beforeEnter来转跳到另一个页面 /real-login，
4. 然而从real-login回退，则不会跳到 /home，而是跳掉 /page1，

然后循环到步骤 2

### What is expected?
得到正确的结果

### What is actually happening?
通过replace到一个路由，而该路由使用了beforeEnter的next到另一个路由的情况，实际上history不是执行replace，而是执行了push

**Comment by yyx990803** [comment]
请把 issue 开到正确的仓库。
