### ISSUE TITLE
Performance issue on CPU

### ISSUE THREAD

**Issue by dwcy** [vuejs/vue#6775]
### Version
2.3.3

### Reproduction link
[https://quasar-admin.firebaseapp.com/?ref=madewithvuejs.com#/](https://quasar-admin.firebaseapp.com/?ref=madewithvuejs.com#/)

### Steps to reproduce
1 Open resource monitor to see CPU usage
2. Open Chrome (All browsers have performance issues but Chrome is the worst)
3. Go to URL and first issue that page when idle process eat more CPU than normal
4. Scroll in the list to create a larger list (might be a v-for issue?)
5. my CPU ticks 1% each 10 records until 25%

### What is expected?
CPU to chill!

### What is actually happening?
CPU is doing lot of work.

---
I use this admin site as an example, since the CPU usage issues are reproduced as in my project.Making me thing that it is vue related.

Difference is that my project have multiple updates going on, and CPU are sometimes hitting 100% in Chrome, Edge: 50% and firefox 20%.
Still 20% seems to high. 

I am using the latest  i7 SSD and 16gb of Ram, so computer should not be the bottleneck.

**Comment by LinusBorg** [comment]
Hi @dwcy 

I'm sorry that Quasar is not perfoming the way you expect it to, but this is not a topuic for the Vue issue tracker.

I understand that you *think* this *might*  have *something* to do with Vue itself, but we can't and won't analyse a whole Quasar app for performance issues. You should adress that in the Quasar community.

If you find a specific  behaviour of Vue, which you can reproduce with a small example (not with Quasar), 
 like unuusual CPU spikes or memory leaks feel free to open an issue, here again, though.

**Comment by dwcy** [comment]
The issue was actually a CSS @keyframes animation not working well with multiple updates. 
Found that after I noticed Chrome Rendering feature exists and are turned it on with paint flashing and FPS meter. Not directly an Vue problem so I will close.
