### ISSUE TITLE
App wide component plugin.

### ISSUE THREAD

**Issue by nmihaica** [vuejs/vue#6776]
### Version
2.4.4

### Reproduction link
[https://codesandbox.io/s/7w32yv4q4x](https://codesandbox.io/s/7w32yv4q4x)

### Steps to reproduce
Minimal reproduction link.

### What is expected?
Component functionality to be accessible app-wide.

### What is actually happening?
Methods get called and executed, but functionality cannot rely on data.

---
Goal to improve documentation with working examples how to setup plugins and recommended install procedures with common gotchas like it's explained with the other features of Vue and guides how to correctly access component functionality globally.

**Comment by posva** [comment]
This belongs to vuejs/vuejs.org but it's something that we'll probably add to the cookbook
A pull request to start the discussion with some initial material is even more appreciated 🙂

**Comment by yyx990803** [comment]
You need understand the difference between a **Component definition** and a **component instance**. You are trying to call the method directly on the definition, so it won't have any instance to point `this` to.
