### ISSUE TITLE
view is not changed with modern Data changed

### ISSUE THREAD

**Issue by cyzeng-Luca** [vuejs/vue#6779]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/while_own/nwvr7wut/6/](https://jsfiddle.net/while_own/nwvr7wut/6/)

### Steps to reproduce
1. change the price 30.25680-30.25689(i keep four decimal);
2. the 30.25680-30.25684 is not work, the 30.25685-30.25689 is normal;
3. i debugger it, i find the modern data is changed,but it is not work when i input 30.25680-30.25684;
4. i try to use vm.$forceUpdate ,but it is not work;

### What is expected?
the same as i input 30.25685-30.25689

### What is actually happening?
change to 30.25680-30.25684,not work

**Comment by yyx990803** [comment]
This involves a 3rd party library, please either provide a clean repo using just plain Vue, or open your issue at element-ui's repo instead.
