### ISSUE TITLE
递归组件中变量不共享

### ISSUE THREAD

**Issue by K-walker** [vuejs/vue#6780]
### Version
2.4.4

### Reproduction link
[https://codepen.io/anon/pen/PJBqbL?editors=1011](https://codepen.io/anon/pen/PJBqbL?editors=1011)

### Steps to reproduce
点击 菜单1-2-1 和 菜单1-2-2 背景色可以切换，而点击其他不同层级下的叶子结点，背景色没有切换，因为我通过改变activeId的值来动态设置class

### What is expected?
activeId可以再不同层级下是唯一的，就是无论点击那个层级的叶子结点菜单，改变的都是同一个activeId

### What is actually happening?
每个层级有单独activeId

**Comment by posva** [comment]
You're purposely not setting the `activeId` variable:

```js
methods:{
    handleClick:function (obj) {
      if(obj.children.length == 0) {
        this.activeId = obj.id ;
      }
    }
  }
```
