### ISSUE TITLE
热部署开发情况下,当仅仅调整vue文件Template中相邻两个不同类型vue组件位置时, vue运行时对象vueComponent的顺序并未同步调整

### ISSUE THREAD

**Issue by weiweiwei256** [vuejs/vue#6783]
### Reproduction link
[https://codesandbox.io/s/q938y6q0xj](https://codesandbox.io/s/q938y6q0xj)

### Steps to reproduce
例如:
<template>
	<div>
    <world1></world1>
    <world2></world2>
  </div>
</template>
将world2移动到world1之前
<template>
	<div>
    <world2></world2>
    <world1></world1>
  </div>
</template>
  保存后,页面显示正常 但是输出运行时vue对象时,  vueCompoent顺序未发生改变
  $children[0] 的vueComponent对应的是world1
  $children[1] 的vueComponent对应的是world2

备注:当同类型vue组件标签调整位置时删除,新增,父子关系调整时,   vueComponent的数据时对应同步的

### What is expected?
热部署开发情况下,Template中相邻两个不同类型vue组件位置时,运行时vueCompoent的位置信息可以对应改变

### What is actually happening?
热部署开发情况下,Template中相邻两个不同类型vue组件位置时,运行时vueCompoent的位置信息未发生改变

**Comment by yyx990803** [comment]
如文档所说 `$children` 不保证任何顺序。

**Comment by weiweiwei256** [comment]
不好意思 我还得追问一句 在运行时 $children确实 不需要保证顺序  但是刚刚启动完成时 顺序是对的  我觉得  在热部署状态下  应该和新启动状态保持一致    ps：我这边在依赖这种机制在开发一个vue文件的可视化编辑器 很依赖现在的热部署机制   当然通过服务端渲染也应该能达到效果 但是资源有限还是希望热部署可以支持类似初始化时正确的顺序
