### ISSUE TITLE
Click Event Fires Twice?

### ISSUE THREAD

**Issue by BrianMoreno1994** [vuejs/vue#6786]
Hi everyone, so I'm having a bit of trouble using Axios with VueJS (I'm using the [Quasar Framework](https://github.com/quasarframework/quasar)). I'm making a very simple e-commerce website. I have a button when the user opens the product page that allows the user to insert that product to the cart.

```
<q-btn
     @click="addToCart()"
>
    Agregar Al Carrito
</q-btn>
```
When the user clicks the button I want to execute the `addToCart()` method:

```
methods: {
  addToCart () {
      axios.post(this.getRootURL + 'app/actions/add_to_cart.php', {
        product_id: this.$route.params.product_id,
        quantity: this.quantity,
        user_id: LocalStorage.get.item('user_id')
      }).then(response => {
        console.log("Product added...")
      }).catch(e => {
        console.log("Error... ")
    }
  }
}
```
However, I'm facing a problem. It's as if the data gets inserted twice. The first row gets a null `user_id` and the second row get the correct `user_id` ([See image](https://ibb.co/kRzCiw)).

I'm sure I'm doing something wrong with VueJS or Axios because when using Postman and sending a request directly to the file, the data only gets inserted once correctly. 

Can anyone help? Why Is this happening? :/

**Comment by andyklimczak** [comment]
try `<q-btn @click="addToCart">`
remove the extra ()

look at the [example in the docs](https://vuejs.org/v2/guide/events.html#Method-Event-Handlers)
