### ISSUE TITLE
the page sometimes can rendering, sometimes not can rendering.

### ISSUE THREAD

**Issue by SeanBurt** [vuejs/vue#6789]
### Version
2.3.3

### Reproduction link
[http://wwwsg.teld3.top/#/JoinUs/JoinUs](http://wwwsg.teld3.top/#/JoinUs/JoinUs)

### Steps to reproduce
click the tab, sometimes v-for can render api response data, sometimes can not render the data.

### What is expected?
click the tab, sometimes v-for can render api response data, sometimes can not render the data.

### What is actually happening?
click the tab, sometimes v-for can render api response data, sometimes can not render the data.

**Comment by SeanBurt** [comment]
### Source Code
GetList: function() {
    $("#main").html('');
    var _this = this;
    getDataAsync(_api_.JoinUs + "&categoryID=" + _this.categoryID, "GET", null,
    function(Data) {
        if (Data.state == "1") {
            _this.dataJoin.splice(0);
            _this.dataJoin = _this.dataJoin.concat(Data.data);
            //                            _this.dataJoin = Data.data;
            _this.$nextTick(function() {
                $("#main").removeClass("gaodu");
            })
        } else {
            alert("数据请求失败");
        }
    });
}

**Comment by yyx990803** [comment]
This is not a valid reproduction.
