### ISSUE TITLE
希望props传值能够使用扩展运算符 ... 

### ISSUE THREAD

**Issue by wanglei8381** [vuejs/vue#6791]
### What problem does this feature solve?

Hello组件接受data属性
```
<component is="Hello" :data="{...obj1, ...obj2, e: 5}"></component>


{
  data () {
    return {
      obj1: {a: 1, b: 2},
      obj2: {b: 3, d: 4}
    }
  }
}
```

Hello组件data属性最终组合成的对象是 {a: 1, b: 3, d: 4, e: 5}

**Comment by maicss** [comment]
https://github.com/vuejs/vue/issues/4962

不会先搜一下吗

**Comment by posva** [comment]
Use `v-bind`

**Comment by Justineo** [comment]
Actually I think it's more like #6307.
