### ISSUE TITLE
v-for loop with empty data returning 'undefined' text

### ISSUE THREAD

**Issue by timenz** [vuejs/vue#6797]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/jqLskfh7/3/](https://jsfiddle.net/jqLskfh7/3/)

### Steps to reproduce
Cek on reproduction link, if cars has data v-for working fine, but if cars empty, v-for printing 'undefined' text

### What is expected?
nothing displayed

### What is actually happening?
display 'undefined' text

**Comment by posva** [comment]
dup of #4581

**Comment by lydtclydtc** [comment]
Yes, I have met this issue too, and it may cause some unexpected behavior in element-ui which may uses array props to control widgets
