### ISSUE TITLE
2.5 breaks functional components that renders nested empty `children` array

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue#6798]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/jbugrk6f/1/](https://jsfiddle.net/jbugrk6f/1/)

### Steps to reproduce
A jsx functional component: 
```jsx
const Foo = {
  render: (h, {children}) => <div>{children}</div>
}
```
that gets transpiled by `babel-plugin-transform-vue-jsx` to 
```jsx
const Foo = {
  render: (h, {children}) => h('div', {}, [children])
}
```
was working fine with vue 2.4.4 and before, but with 2.5 it renders 'undefined' if `Foo` is used without children as `<Foo/>` (which is `h(Foo, [])` after transformation)

Details and comparisons inside repro link.

Second thought: Maybe `babel-plugin-transform-vue-jsx` should not pass an empty array as children, if the jsx element is used without children? Runtime performance should be slightly better without this empty array.

### What is expected?
Renders nothing

### What is actually happening?
Renders 'undefined'

---
Vue 2.4.4 was working fine:
https://jsfiddle.net/L2c9ujg2/

**Comment by posva** [comment]
@fnlctrl Isn't this a dup of #6797 (and many others) 😆

**Comment by fnlctrl** [comment]
:joy::joy::joy: Looks like it is.. I'll just close this and wait for the release 😆
