### ISSUE TITLE
v-for renders 'undefined' if it's empty and in another v-for loop 

### ISSUE THREAD

**Issue by forclan** [vuejs/vue#6804]
### Version
2.5.0

### Reproduction link
[https://codepen.io/anon/pen/MEqbYg](https://codepen.io/anon/pen/MEqbYg)

### Steps to reproduce
https://codepen.io/anon/pen/MEqbYg

### What is expected?
render:
1
2

### What is actually happening?
the result renders
1 undefined
2 undefined

**Comment by posva** [comment]
dup #6790
