### ISSUE TITLE
v-for on empty array prints string "undefined"

### ISSUE THREAD

**Issue by dmmikkel** [vuejs/vue#6807]
### Version
2.5.0

### Reproduction link
[https://codepen.io/dmmikkel/pen/XePMKG](https://codepen.io/dmmikkel/pen/XePMKG)

### Steps to reproduce
Use v-for to iterate over empty array

### What is expected?
Nothing to render

### What is actually happening?
Renders string 'undefined'

**Comment by posva** [comment]
dup of #6808
