### ISSUE TITLE
Running `v-for` on template with an empty array inserts `undefined` into DOM [regression]

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vue#6808]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/wyau52rv/](https://jsfiddle.net/wyau52rv/)

### Steps to reproduce
Just run the demo

### What is expected?
I should see nothing as in 2.4.x versions.

### What is actually happening?
`undefined` in injected into DOM as a string

**Comment by posva** [comment]
Please check the closed issues before opening new ones
dup of #6804

**Comment by vinigfer** [comment]
Also facing this issue. I've been using vue from https://unpkg.com/vue (local dev environment), but on production we use a minified version, which is 2.4.0.
On that version this issue doesn't happen.

**Comment by Lorempn2** [comment]
Facing the same issue. How to fix?
