### ISSUE TITLE
"Undefined" as text if v-for array is empty

### ISSUE THREAD

**Issue by exodusanto** [vuejs/vue#6809]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/L6y9sb0s/3/](https://jsfiddle.net/L6y9sb0s/3/)

### Steps to reproduce
If I use v-for and the array is empty and element have a sibling or basic text, the result of v-for is "undefined"

### What is expected?
Nothing

### What is actually happening?
undefined as text

**Comment by posva** [comment]
dup of #6790
