### ISSUE TITLE
Change event isn't triggered with input type="file" on UC Browser Android Version 11.0.5.850

### ISSUE THREAD

**Issue by ahmadmilzam** [vuejs/vue#6812]
### Version
2.4.4

### Reproduction link
[https://codepen.io/ahmadmilzam/pen/eGLJYP](https://codepen.io/ahmadmilzam/pen/eGLJYP)

### Steps to reproduce
Open with UC Browser on android, and click / tap the custom input file.

### What is expected?
A popup menu contain gallery, camera showed up like I expected, and let me select a file or take a photo. After the file is selected, the handler with toggle `has-file` class to the custom input and render the name of selected file/photo to input label.

### What is actually happening?
But when a file selected or photo is taken, on change event is not triggered. 

It works fine on UC browser for iOS only and there is no problem on Android version of UC browser if I user jquery on method `$element.on('change', handler);` not with vue `@change="handler"`.

**Comment by yyx990803** [comment]
I doubt this is Vue's problem because `@change` simply attaches a native event listener. If you believe this is caused by Vue, please reduce the reproduction. It involves too much unrelated logic and a 3rd party library.

**Comment by ahmadmilzam** [comment]
Hi @yyx990803, I've updated the codepen, remove the third party library and other unrelated logic. Just click and change handler.

Thank you very much

**Comment by yyx990803** [comment]
This seems to be a browser behavior quirk: calling `.click()` on the input does not trigger a native change event. jQuery probably has some compatibility hacks to cater to that, but that's not really Vue's responsibility.

**Comment by ahmadmilzam** [comment]
Ooh i see, btw do you have any suggestion on how to make it works on vue? I'll try to wrap the input with label tag, and remove the click handler. I hope that will trigger the native event.

Thank you very much
