### ISSUE TITLE
Intermittent net::ERR_CONTENT_LENGTH_MISMATCH on Amazon EC2

### ISSUE THREAD

**Issue by johnfercher** [vuejs/vue#6818]
### Version
2.4.4

### Reproduction link
[https://github.com/vuejs-templates/webpack](https://github.com/vuejs-templates/webpack)

### Steps to reproduce
Notice: This issue doesn't need a sample of code.

1 - Create a Ubuntu 16.04 Server on Amazon EC2 machine and access via SSH.
2 - Install Node.JS (I've tried v6, v7 and v8) and Vue-Cli
3 - Run (vue init webpack project_test)
3.1 - Install Runtime Compiler
3.2 - install Vue-Router
3.3 - Skip ESLint installation
3.4 - Install Karma
3.5 - Skip Nightwatch
4 - Run npm install
5 - Run npm run dev
6 - Open the port 8080 for inbound rules
7 - Access the public DNS:8080 on your browser

### What is expected?
Should open the example screen

### What is actually happening?
The screen won't load, the title gonna load and in console will appear the error: net::ERR_CONTENT_LENGTH_MISMATCH

---
The error always appears between 6 and 7 seconds after the GET request.

The following message always appears:
(node:5517) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:5517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I've tried Vue 2.4.4 and Vue 2.5.2, both have the same issue. I tried other templates too.

Notice, sometimes the error occurs just after run (npm run dev), sometimes the page loads and after a while, the error occurs again.

**Comment by posva** [comment]
This has nothing to do with vue. I don't see why you would run a development server in a production environment anyway
