### ISSUE TITLE
object模板数据获取下一层时报undefined

### ISSUE THREAD

**Issue by ToWorkit** [vuejs/vue#6823]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
代码： <p>{{item['order_success']}}</p>
模板展示： { "pay_flag": 3, "order_total": 5, "pay_money": 28800 }

报错操作：
代码： <p>{{item['order_success']['pay_money']}}</p>
报错： [Vue warn]: Error in render: "TypeError: Cannot read property 'pay_money' of undefined"

### What is expected?
28800·

### What is actually happening?
报错

---
测试链接中的模拟数据是可以出来的，不清楚原因所以发issue，希望可以得到解答，谢谢

**Comment by ToWorkit** [comment]
这是上周已经测试待上线的代码，当时并没有加v-if对父级层数据做处理，数据显示也同样没有问题，这周来再测试代码就报出了undefined的错误，问过后端同事并没有修改过后端的数据代码，因为父级数据是可以正常显示的，通常就会误解为已经是有数据了，但应该是vue在处理子级层数据时还会对父级数据再次获取所以就造成了undefined的错误，以后再代码方面需要注意了，也希望大家可以以此为戒

**Comment by Tian-Hun** [comment]
什么意思
