### ISSUE TITLE
E2E Test for VueJS Application:  Automatically Wait for AJAX with Capybara

### ISSUE THREAD

**Issue by wenbo** [vuejs/vue#6824]
### What problem does this feature solve?
just as in following article, there is method called 'jQuery.active' to judge whether http request is finished,  in the condition of VueJS,  is there similar solution. 

https://robots.thoughtbot.com/automatically-wait-for-ajax-with-capybara

### What does the proposed API look like?
 page.evaluate_script('VueJS.active').zero?

**Comment by LinusBorg** [comment]
I'm sorry but I don't understand what you are requesting.

**Comment by posva** [comment]
Pretty much what @LinusBorg said, you would have to do the proper modification on jquery or axios side. But there's nothing that can be done in vue.js core for that
