### ISSUE TITLE
v-once within component template makes all component instances static

### ISSUE THREAD

**Issue by kasperisager** [vuejs/vue#6826]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/8L92f8Lm/](https://jsfiddle.net/8L92f8Lm/)

### Steps to reproduce
1. Create component that uses `v-once` within its template and renders dynamic content
2. Render component multiple times with different content

### What is expected?
Each instance of the component renders its associated content

### What is actually happening?
All instances of the component render the same content

---
This seems to be a regression from 2.4.4 as witnessed by https://jsfiddle.net/8L92f8Lm/1/.

**Comment by miccycn** [comment]
I met the same problem!!!

**Comment by yyx990803** [comment]
close via #6837

**Comment by paglias** [comment]
@yyx990803 hi, do you know when a new release that includes this fix will be released approximately?

thanks for the awesome project :)
