### ISSUE TITLE
Ref doesn't work on functional components.

### ISSUE THREAD

**Issue by HakurouKen** [vuejs/vue#6829]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/d2pj7wuo/](https://jsfiddle.net/d2pj7wuo/)

### Steps to reproduce
Open the JSFiddle link, then check the console.

### What is expected?
The child functional component can be attached by `this.$refs` , or give a warning in development environment when attribute `ref` is set on a functional component.

### What is actually happening?
`this.$refs` of parent componet is an empty object.

---
There's a [similar issues for React stateless components](https://github.com/facebook/react/issues/4936). A functional component will not actually generate a VueComponent instance, instead of attaching the dom element directly, a warn or an error thrown may be a better choice.

**Comment by shyn0121** [comment]
我只是克隆你的vue, git在我的本地电脑，然后发出一个错误。I did'n remember The details about the error

**Comment by shyn0121** [comment]
win10+ github client+right mouse key+git clone=I get vue but show an error,and nothing changed about vue source

**Comment by shyn0121** [comment]
am I clearly say

**Comment by shyn0121** [comment]
god i just smal lsource  code

**Comment by alejandroiglesias** [comment]
@sqal how about using a functional component without a render function? That's also not working for me.
