### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by fracasula** [vuejs/vue#6830]
### Version
2.5.2

### Reproduction link
[https://github.com/fracasula/vuejs-test](https://github.com/fracasula/vuejs-test)

### Steps to reproduce
1. `make dbuild` to build the Docker image (based on `node:slim`)
2. `make install` to run `npm install` through the Docker container
3. `make wbuild` to create the webpack `/dist/build.js`
4. `make ssr` to run a server (that uses ssr) that will listen on http://localhost:8080

### What is expected?
To get some output.

### What is actually happening?
I'm getting the "The client-side rendered virtual DOM tree is not matching server-rendered content" error with an empty DOM.

---
If you want the client version just do make wbuild run and there you got the webpack dev server on http://localhost:8080.

(as a sidenote hot reloads don't work, still haven't figured out why, just kill the server and re-run the make command, sorry about that)

**Comment by posva** [comment]
Can you please strip off the nonrelated packages like vue-bootstrap and move the project out of the container image so we don't need to build an image to test?

**Comment by LinusBorg** [comment]
Your setup for SSR doesn't follow the guidelines laid out in our SSR guide, really:

**Comment by shyn0121** [comment]
everything ok now

**Comment by shyn0121** [comment]
when I git clone to my local disk space,it show an error,but I do nothing others

**Comment by shyn0121** [comment]
I follow ssr Iam going to sleeping

**Comment by shyn0121** [comment]
我压根不懂你们 说啥

**Comment by shyn0121** [comment]
哈哈哈哈

**Comment by LinusBorg** [comment]
I have no idea why you are commenting here and what you are saying.

**Comment by fracasula** [comment]
Will try like you said, thanks for your help @LinusBorg
