### ISSUE TITLE
Regarding Documentation of API reference -> Router constructor options 

### ISSUE THREAD

**Issue by meetzaveri** [vuejs/vue#6836]
### Version
2.5.2

### Reproduction link
[https://router.vuejs.org/en/api/options.html#routes](https://router.vuejs.org/en/api/options.html#routes)

### Steps to reproduce
In https://router.vuejs.org/en/api/options.html#routes , when I click provided link as "right arrow" ( > ) on right side of website, nothing redirects to "#routes" only and it doesn't processes to any other pages. In fact when viewing any other api reference such as mode or base then also it redirects to #routes. Also "left arrow" ( < ) is working fine when I visit The Router instance or The router object. But only right arrow is pointing to the first api reference in particular section

### What is expected?
Should redirect to provided source.

### What is actually happening?
Its redirecting to '#routes' section 

---
If its mean to redirecting to routes api reference, then arrow should be pointing upwards.

**Comment by yyx990803** [comment]
The arrow is auto-generated by Gitbook to link to the next item in the menu on the right. Either way this issue does not belong here.

**Comment by meetzaveri** [comment]
Okay , thanks for flagging! @yyx990803
