### ISSUE TITLE
button get focus unexpectedly

### ISSUE THREAD

**Issue by lxjwlt** [vuejs/vue#6840]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/lxjwlt/ffnrch4f/](https://jsfiddle.net/lxjwlt/ffnrch4f/)

### Steps to reproduce
1. click "next" button, and look at current focused element 
2. click "prev" button, and look at current focused element 

### What is expected?
1. when click "next" button and it has been hidden, there is not focused element
2. when click "prev" button and it has been hidden, there is not focused element

### What is actually happening?
1. "cancel" button get focus
2. "cancel" button get focus

---
if there is 'key' set to each button, it has no problem: https://jsfiddle.net/lxjwlt/y0exLedx/

it seems Vue reuses the button dom and hasn't reset its focus state

**Comment by phanan** [comment]
You said it yourself: if there is 'key' set to each button, it has no problem. This is due to Vue using an "in-place patch" strategy, as [explained in the doc](https://vuejs.org/v2/guide/list.html#key).

**Comment by lxjwlt** [comment]
Hi @phanan "in-place patch" is great, but if vue patch element in-place, it should reset all status completely, including event bindings, classes, `readonly`, `disabled`, etc. so why not reset focus status?

**Comment by yyx990803** [comment]
Because focus status is not part of the node's "state". There are two possibilities in this case:

- you want to change the button's text while maintaining focus;
- you want to replace the button while resetting the focus.

There's simply no way for Vue to tell which is your intention, unless you use a key.
