### ISSUE TITLE
[Question] How the slot is passed to the slot

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue#6842]
### What problem does this feature solve?
el-card.vue:
```html
<template>
  <div class="el-card">
    <div class="el-card__header" v-if="$slots.header || header">
      <slot name="header">{{ header }}</slot>
    </div>
    <div class="el-card__body" :style="bodyStyle">
      <slot></slot>
    </div>
  </div>
</template>
```
I use an `el-card` component to encapsulate another component named `Card`

Card.vue:
```html
  <el-card>
    <slot slot="header" name="header"></slot>
    <slot></slot>
  </el-card>
```

use：

```html
    <Card>
      <div slot="header">333</div>
      <div>123</div>
    </Card>
```

### What does the proposed API look like?
How the slot is passed to the slot? If not support, whether it will consider supporting it?

**Comment by yyx990803** [comment]
We explicitly stated that we do not take questions here.
