### ISSUE TITLE
The order of `updated` is unexpected

### ISSUE THREAD

**Issue by zhiquan-yu** [vuejs/vue#6843]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/__jelly__/xt1nbwpv/1/](https://jsfiddle.net/__jelly__/xt1nbwpv/1/)

### Steps to reproduce
Please open your Console.

It will print:
render 0
render 1
render 2

after 1s, it will print:
render 3
render 4
render 5
updated,  5
updated,  4
updated,  3

### What is expected?
the order of updated should be 3,4,5

### What is actually happening?
the order of updated is 5,4,3

**Comment by yyx990803** [comment]
There's no guarantee about hook order for components in an Array.
