### ISSUE TITLE
vue项目，生成环境运行正常，打包app之后部分手机正常，部分手机显示空白（目前华为手机出现空白）

### ISSUE THREAD

**Issue by Apache-Ra** [vuejs/vue#6844]
webpack打包的vue项目，在cordova打包的apk中部分机型显示空白：

华为手机显示为空白。

**Comment by LinusBorg** [comment]
Hello @Apache-Ra 

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.
