### ISSUE TITLE
Missing VueConstructor in TypeScript typings when creating plugins

### ISSUE THREAD

**Issue by kedrzu** [vuejs/vue#6848]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/d3cfrtbn/4/](https://jsfiddle.net/d3cfrtbn/4/)

### Steps to reproduce
1. Try to create a vue plugin using TypeScript in most expected way
2. Wonder how to make a workaround :)

### What is expected?
You should be able to define a plugin in TS just as you would in plain JS: as a function, with a parameter to be a global Vue object, that is well typed.

### What is actually happening?
I could not find any possible way to declare a type to the Vue parameter inside plugin, because the type of global Vue object (VueConstructor) is not exported. It is only visible as an exported Vue variable.

---
I guess one solution is to simply export VueConstructor as a type, that could be imported in these rare cases.

**Comment by silkentrance** [comment]
@ktsn Last I checked, typeof Vue by definition returns a string or is there some magic going on behind closed doors? And where would you use the typeof Vue in the provided repro?

**Comment by silkentrance** [comment]
@ktsn according to vue.d.ts, there is a const export Vue : VueConstructor.

**Comment by SreeChandan** [comment]
came across this myself. Solved it by doing the following.
import { VueConstructor} from "vue";
const plugin= { options: (VueInstance: VueConstructor, options: any) ={ // })

**Comment by domenicomonaco** [comment]
I solved with

`import VueConstructor from "vue";`
