### ISSUE TITLE
Component data doesn't change

### ISSUE THREAD

**Issue by 50l3r** [vuejs/vue#6849]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/wu0gjz2r/](https://jsfiddle.net/wu0gjz2r/)

### Steps to reproduce
Hi guys, i have a shopping cart made in vue2. 

Two components (food & cart) are inside the main but "items" doesn change.

When i spect the console the data exist: https://gyazo.com/adb04628e21ac3c87625f2b223064679

But computed properties and data doesnt update.

### What is expected?
Component data change

### What is actually happening?
Component data doesnt change

---
	const bus = new Vue();

	Vue.component('food',{
		props: ['menu'],
		template: `
			<div>
				<div class="food-item" v-bind:class="replaceSpaces(item.cat)" v-for="(item,index) in menu">
					<div class="food-item-wrap clearfix">
						<div class="food-name">
							<h3>{{item.name}}</h3>
						</div>
						<div class="food-detail">
							{{item.text}}
						</div>
						<div class="food-price">
							<span>{{item.price}}€</span>
							<a class="add-cart" v-on:click="addToCart(item, index)">Añadir al carro</a>
						</div>
					</div>
				</div>
			</div>
		`,
		methods: {
			addToCart(item, index){
				bus.$emit('añadir', item, index);
			},
			replaceSpaces(cat){
		    	return cat.split(" ").join("_").toLowerCase();
		    },
		}
	});

	Vue.component('cart',{
		template: `
			<div>
				<div class="cart-head">
		            (<strong>{{productCount}}</strong>) productos por <strong>{{total}} €</strong>
		        </div>
		        <ul class="cart-sub">
		            <li v-for="(item,index) in items">
		                <a href="#">{{item.name}} {{item.price}} €</a>
		                <span class="remove-cart"><a href="#" v-on:click="delToCart(item, index)"><i class="fa fa-close"></i></a></span>
		            </li>
		        </ul>
	        </div>
		`,
		data() {
			return {
				items: []
			}
		},
		computed: {
		    productCount(){
		    	if(Object.size(this.items)>0){
		    		return this.items.length();
	    		}else{
	    			return 0.00;
	    		}	      
		    },
		    total(){
		    	return 0;
		    }
	  	},
		created(){
			var data = sessionStorage.getItem('cart');

			if(data){
				var json = JSON.parse(data);
			}

			bus.$on("añadir", (item, index) => {
				if (typeof this.items[index] === "undefined") {
					this.items[index] = item;
					this.items[index].quantity = 1;
				}else{
					this.items[index].quantity  ;
				}
			});

			bus.$on("eliminar", (item, index) => {
				if ($(this).items.indexOf(index) > -1) {
					this.items.splice(index)
				}
			});
		},
		methods: {
			delToCart(item){
				item = JSON.parse(item);

				bus.$emit('eliminar', item);
			}
		}
	});

	new Vue({
	    el: 'main',
	    mounted: function(){
			$(document).ready(function(){
				setTimeout(function(){
					$(".food-filter li a[data-filter='.hamburguesas_especiales']").click()
				},1000);
			})
			
	  	},
	    data:{
			menu: JSON.parse(food_menu)
		}
	});

**Comment by yyx990803** [comment]
This is not a [minimal reproduction](https://github.com/vuejs/vue-issue-helper/blob/master/src/i18n/locales/en/repro-modal.md).
