### ISSUE TITLE
Class attribute added to functional child component is not added to child component root element

### ISSUE THREAD

**Issue by rssfrncs** [vuejs/vue#6851]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/qvz167jn0q](https://codesandbox.io/s/qvz167jn0q)

### Steps to reproduce
- Import a functional component and add to template or render function
- Add a class attribute to the functional component e.g. <FunctionalComp class='test' />
- Observe how the class is ignored and not applied

### What is expected?
Class is applied to functional component root element?

### What is actually happening?
Class is ignored?

**Comment by yyx990803** [comment]
This is expected behavior. Functional components do not merge class from parent because they may return more than one nodes. You need to explicitly bind `context.data.class` yourself.

**Comment by rssfrncs** [comment]
@yyx990803 thanks for the info, is this discussed anywhere in the docs? I did look before posting an issue but couldn't find anything.
