### ISSUE TITLE
Vue2.x transition elelment jump to origin unexpected

### ISSUE THREAD

**Issue by xiaoguifly** [vuejs/vue#6853]
### Version
2.5.2

### Reproduction link
[https://codepen.io/xiaoguifly/pen/NaoRQd](https://codepen.io/xiaoguifly/pen/NaoRQd)

### Steps to reproduce
1. click the bottom area to change the list appear or disappear
2. when  isShow = true,the list  should be animated from 0px to 50px on x-axis
3. when isShow =false,the list should be animated from 50px to 0px on x-axis

### What is expected?
when isShow = true,the list should be animated from 0px to 50px on x-axis,when isShow=false,it should be animated from 50px to 0px

### What is actually happening?
when isShow=true,the list animated from 0px to 50px,then jumps to its origin(0px)

**Comment by yyx990803** [comment]
`fade-enter-to` is removed after the transition is finished. It is your responsibility to ensure that the element in its default state is in the correct position.
