### ISSUE TITLE
elementUI 日期选择控件无法正常使用.

### ISSUE THREAD

**Issue by zsedcbm** [vuejs/vue#6854]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/e6jvgge8/4/](https://jsfiddle.net/e6jvgge8/4/)

### Steps to reproduce
页面中如果引用的是 //unpkg.com/vue/dist/vue.js ,日期选择范围不能正常工作,无法选择日期
如果引用的是 //unpkg.com/vue@2.4.2/dist/vue.js, 日期选择范围能够正常工作,可以选择日期
除了elementUI 外,同时使用了iview组件,发现里面的日期选择范围插件也不能正常工作,因此我怀疑是vue本身的bug导致的.

### What is expected?
日期选择范围不能正常工作

### What is actually happening?
可以正常选择日期范围

**Comment by yyx990803** [comment]
怀疑没有用，请先到对应项目确认。

**Comment by zsedcbm** [comment]
上面的例子就是最好的证明.
2.4.2 和 2.4.4 版本都能正常使用
2.5以上的版本都不能正常使用.

除了vue版本修改过以外,其他的都没有变过,
elementUI 和 iView 两个组件的日期选择控件都受同样的影响

**Comment by feichao** [comment]
@zsedcbm 我这边测试没问题, 具体是什么问题?
![1508406913215](https://user-images.githubusercontent.com/11988943/31765351-aeee6e50-b4f6-11e7-9b7c-13b7fbf925a2.jpg)

**Comment by zsedcbm** [comment]
@feichao 
360极速浏览器(chrome 内核55.0.2883.87)中
使用新版的vue 日期无法选中,使用vue2.4.2版本的时候可以正常选择.
后来使用了chrome 61的浏览器,两个版本的vue都可以正常使用.
![360](https://user-images.githubusercontent.com/5986396/31800727-78869a5c-b575-11e7-9347-dc3f39b43dcb.gif)

奇怪的一点是,我在 devtools中,下断点的时候,vue新版本也是能够正常运行的.去除断点,又出现问题了,不知道是浏览器内核版本低的问题,还是vue的问题.
![default](https://user-images.githubusercontent.com/5986396/31800835-45e27926-b576-11e7-809d-20c5e0d0b880.png)

**Comment by zsedcbm** [comment]
@feichao 
这两个也是反映的同样的问题
https://github.com/ElemeFE/element/issues/7539
https://github.com/iview/iview/issues/2122

**Comment by yyx990803** [comment]
Most likely related to https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#internals-change-for-nexttick

**Comment by yyx990803** [comment]
看了下似乎只有在旧版本的 Chrome 里面有这个问题，在最新版本的浏览器里都没有问题的话，Vue 这边没有办法，需要库的作者去处理了。

**Comment by ben-wong** [comment]
最新的85版的Chrome也遇到这个问题了
