### ISSUE TITLE
Is that possible to mix vue template and JSX

### ISSUE THREAD

**Issue by DonToShergon** [vuejs/vue#6862]
### What problem does this feature solve?
Create vue template is fixed and it can only using some switch or if to exclude what I don't want to display. I am thinking using JSX inside the vue template to make the vue template more flexible to for other developer to code. In this case, I can pass the JSX as data to the component base to display what I want. 

For example I have 3 file.

A, Call the template base.

B, Base template for display.

C, template for display on the base template.

In this case, A will import B and C, A pass C to B by using prop. 
This syntax, will make B do not need to import all the file and not much coding I need to deal with.
C will contain all of the coding for display. B is a place to load all coding.

### What does the proposed API look like?
.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It's probably better to use a component for that purpose (let the dev pass components) or use slots. That also allows you to combine jsx and templates in one project
