### ISSUE TITLE
transition child event bugs

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue#6863]
### Version
2.5.2

### Reproduction link
[https://codepen.io/lasthrun/pen/qPvbJy](https://codepen.io/lasthrun/pen/qPvbJy)

### Steps to reproduce
focus input, and click "hello".

### What is expected?
"hello" click event should be call

### What is actually happening?
nothing happen

**Comment by jkzing** [comment]
Isn't it because input blur event fires first so that "hello" is not being clicked actually...

**Comment by lasthrun** [comment]
so, how to make the click first?
