### ISSUE TITLE
IOS component issue

### ISSUE THREAD

**Issue by K-walker** [vuejs/vue#6866]
### Version
2.3.4

### Reproduction link
[https://codepen.io/anon/pen/vePxav?editors=0010](https://codepen.io/anon/pen/vePxav?editors=0010)

### Steps to reproduce
点击菜单展开子菜单，然后再次点击关闭子菜单，然后再次，子菜单无法展开

### What is expected?
再次点击菜单，子菜单可以展开

### What is actually happening?
子菜单无法展开

---
此问题只出现在 IOS PAD 的chrome和safari上出现过，PC 和 Android 是正常的，我使用的IPAD 系统版本是：10.3.1 其他版本的也存在问题

**Comment by K-walker** [comment]
@yyx990803 请问一下，我上面出现的这个问题目前有什么解决方案没？这个问题应该是真实存在的，不是偶然现象吧

**Comment by yyx990803** [comment]
去掉 css 就正常了，貌似是 Safari/iOS 的 CSS bug...

**Comment by K-walker** [comment]
总算找到了原因 是这个  `display:inline-flex` 属性在IOS系统的safari和chrome中不支持，只要去掉就可以了，真的是坑
