### ISSUE TITLE
Tree View: Inconsistent behavior

### ISSUE THREAD

**Issue by nimcho** [vuejs/vue#6870]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/3p0j5sgy/1138/](https://jsfiddle.net/3p0j5sgy/1138/)

### Steps to reproduce
Only a slight modification of the offical Tree View Example.

I moved the treeData (a simple JSON object) directly into the template.  One can no longer add new nodes to the tree.

### What is expected?
It is expected to behave the same way as the original script provided at:

 - https://vuejs.org/v2/examples/tree-view.html

 - or at JSFiddle: https://jsfiddle.net/yyx990803/3p0j5sgy/

### What is actually happening?
When you put the JSON data directly to the template -- the tree displays correctly, no exceptions raised, but you can no longer add new nodes to the tree.

---
According to the documentation, "props" should not be modified at all.

However, it is being modified in the offical example from VueJS website.  Moreover, it is hard to imagine a meaningful implementation of an interactive tree structure without modifying "props" data. :(

**Comment by gebilaoxiong** [comment]
Because the data in template is not observerable

or you can do it like this: https://jsfiddle.net/3p0j5sgy/1140/
