### ISSUE TITLE
TypeSystem not actually works in SFC

### ISSUE THREAD

**Issue by galenyuan** [vuejs/vue#6873]
### Version
2.5.2

### Reproduction link
[https://github.com/galenyuan/vuex-repo/blob/master/src/App.vue#L14](https://github.com/galenyuan/vuex-repo/blob/master/src/App.vue#L14)

### Steps to reproduce
1. clone this repo
2. npm i
3. npm run dev

### What is expected?
should throw a compile error

### What is actually happening?
build success

![image](https://user-images.githubusercontent.com/10335062/31852033-69874f62-b636-11e7-8657-02fabdf622d5.png)

---
Not sure it's a issue of vue or ts (maybe I use it in a wrong way :P)

**Comment by ktsn** [comment]
This is because your `tsconfig.json` does not have `noImplicitThis` flag. `this` in component methods are always `any` type unless you enable it.

I'll make a PR to docs later to mention about that.

**Comment by galenyuan** [comment]
@ktsn thanks!

**Comment by galenyuan** [comment]
@ktsn I think you'd better mention `export default Vue.extend({})` is also required :P
