### ISSUE TITLE
inline-template delimiters

### ISSUE THREAD

**Issue by pnelson** [vuejs/vue#6879]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/70983/](https://jsfiddle.net/50wL7mdz/70983/)

### Steps to reproduce
Observe results in bottom-right frame.

### What is expected?
Display 'foo.jpg'.

### What is actually happening?
Display '[[ filename ]]'.

---
I'm using Vue to jazz up sections of my non-SPA server-rendered Go application.

**Comment by yyx990803** [comment]
That's not possible because inline templates are compiled as part of parent's tree.
