### ISSUE TITLE
关于rules检验多层json疑问

### ISSUE THREAD

**Issue by zhangmeichun** [vuejs/vue#6881]
### What problem does this feature solve?
您好：
有一个问题在目前开发中遇到，想请问一下，加入现在的数据是以下格式
{ "form": { "name": "BeJson", "url": "http://www.bejson.com", "page": 88, "isNonProfit": true, "address": { "street": "科技园路.", "city": "江苏苏州", "country": "中国" }, "links": [ { "name": "Google", "url": "http://www.google.com" }, { "name": "Baidu", "url": "http://www.baidu.com" }, { "name": "SoSo", "url": "http://www.SoSo.com" } ] } }
那我如何能验证到form中的links里面的name属性呢？目前尝试的话，好像只能验证到form中的name着一层的。

### What does the proposed API look like?
像官方文档一样

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
