### ISSUE TITLE
Strange behaviour with $watch an Object

### ISSUE THREAD

**Issue by netstuff** [vuejs/vue#6883]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/netstuff/Le5v1dm9/8/](https://jsfiddle.net/netstuff/Le5v1dm9/8/)

### Steps to reproduce
1. Define object with some attributes in data section;
2. Place HTML select object, binded to one of defined object attribute;
2. Define prop watcher for one of an attribute ("myObject.attr1");
3. Define API watcher for defined object entirely (with "deep" option);
4. Initiate v-model changing by select any value;
5. Compare "curr" and "prev" values in the both watchers.

### What is expected?
It is expected that the "curr" and "prev" variables in both watchers will not be the same

### What is actually happening?
The "curr" and "prev" variables are the same in API watcher (abnormal), but in prop watcher its different (normal)

---
Is this normal behaviour?

**Comment by javoski** [comment]
>Note: when mutating (rather than replacing) an Object or an Array, the old value will be the same as new value because they reference the same Object/Array. Vue doesn’t keep a copy of the pre-mutate value.

See [https://vuejs.org/v2/api/#vm-watch](https://vuejs.org/v2/api/#vm-watch)
