### ISSUE TITLE
event.target doesn't always point to the same element

### ISSUE THREAD

**Issue by pimski** [vuejs/vue#6884]
### Version
2.5.2

### Reproduction link
[https://codepen.io/pimski/pen/oGRbww](https://codepen.io/pimski/pen/oGRbww)

### Steps to reproduce
First click on the icon (in the button).
Next, click on the edge of the button (not on the icon).

### What is expected?
You'd expect that event.target is the button in both cases (since the event handler is declared on the button)

### What is actually happening?
The event.target depends on the location you click. Something I didn't expect

---
Haven't used Vue in live projects yet, but love what I'm seeing so far!

**Comment by zsalzbank** [comment]
You want `currentTarget`: https://codepen.io/anon/pen/vewGYV

**Comment by pimski** [comment]
Aha. Thanks!
