### ISSUE TITLE
Inconsistency with 2.4.4: the behavior of v-model + v-on on the same element

### ISSUE THREAD

**Issue by campugnatus** [vuejs/vue#6888]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/8gorckx3/](https://jsfiddle.net/8gorckx3/)

### Steps to reproduce
Click the checkbox once (or several times, no matter)

### What is expected?
Properties "on" and "ison" to end up having the same value

### What is actually happening?
Properties "on" and "ison" end up having the opposite values

---
In vue@2.4.4 (at least) the same experiment results in values of "on" and "ison" being the same, which seems more natural to me, as the new state of checkbox is exactly what I'm interested in inside the event handler.

This seems like a trivial use case so I'm not sure if this is a regression bug or a feature :) Either way, the fact that backward compatibility with 2.4.4 is broken is surely a bad thing, especially since npm installs 2.5.2 when given "^2.4.4" version range.

**Comment by yyx990803** [comment]
This is an intentional change to fix a couple bugs caused by event firing orders. In fact if you try 2.4.4 in Firefox, you will see that it has the behavior of 2.5.x in Chrome.

2.5.x has consistent behavior in all browsers, so this is considered a fix.
