### ISSUE TITLE
Support warnings about potential accessibility issues with Vue components.

### ISSUE THREAD

**Issue by joshikeerti** [vuejs/vue#6889]
### What problem does this feature solve?
This will help point out any accessibility flaws with vue components during development. This may not be a core library feature, it could be a set of eslint rules that the CLI generates during scaffold.

### What does the proposed API look like?
Could be an eslint plugin, or a different module similar to react-a11y

**Comment by yyx990803** [comment]
We only keep core feature requests here - I'd suggest moving this to eslint-plugin-vue instead.
