### ISSUE TITLE
Object destructuring in v-bind

### ISSUE THREAD

**Issue by maurop123** [vuejs/vue#6893]
### What problem does this feature solve?
This came up in a case where the parent component was using a getter to pass the props to a child component. It looked like this.
```
<template>
  <puppy v-bind="dogLikeQualities" />
</template>
...
export default {
  computed: {
    ...mapGetters('dogLikeQualities')
  }
}
```
So far so good, because one teammate could manage the store to make sure much of the necessary data was supplied on the getter data, and another teammate could specify on the child component which props to accept.

But then the child component needed another prop that didn't come from the getter data and didn't make sense including in the getter data because it wasn't semantic. To make things work, the props had to be declared like this.
```
<puppy v-bind="dogLikeQualities" :owner="owner" />
```
It would be great to not have to sacrifice the object literal shorthand syntax in both cases to keep the API as DRY as can be :)

### What does the proposed API look like?
```
<puppy v-bind="{ ...dogLikeQualities, owner }"></puppy>
```

**Comment by posva** [comment]
That already works: http://jsfiddle.net/76a41a80/
But it will work only on browsers that support the feature natively or if you use webpack to transpile your js

**Comment by maurop123** [comment]
Man @posva ! That was quick!

So I see that the syntax is supported (which is great), but it doesn't work when I make a new project from vuejs-templates/webpack, as shown here: https://github.com/maurop123/object-destructure

I'll understand if you tell me to post my question there instead, but since I got your attention, thought I'd try asking.

**Comment by LinusBorg** [comment]
Hm, that's probably because the object-rest-spread operator is not stage 2 anymore, it's stage 3.

We only included the stage-2 preset, and we only did so for that operator. Would you be so kind and open an issue in the template repo so we can track this an fix it when we find the time?

Meanwhile, installing babel-preset-stage-3 and adding  it to your babel fonfig (instead of stage 2) should fix it for you.

**Comment by maurop123** [comment]
Thanks for the reply @LinusBorg . Here's the new issue: https://github.com/vuejs-templates/webpack/issues/1005

Just tried using stage-3, but no dice. I made those changes in the dev branch of the same repo. In any case, we can continue this convo on that issue.
