### ISSUE TITLE
Component with slot rerenders even if the slot or component data has not changed

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/vue#6898]
### Version
2.5.2

### Reproduction link
[https://codepen.io/anon/pen/NaVVpW?editors=1011](https://codepen.io/anon/pen/NaVVpW?editors=1011)

### Steps to reproduce
Type something in the input

### What is expected?
`render` method of the Test component shouldn't be called

### What is actually happening?
`render` method of the Test component is called

---
It is an serious performance issue if the component is complicated, it's rerendered even if nothing changes

**Comment by LinusBorg** [comment]
Well, it has to re-render to see **if** anything changed, or not.  I understand that you may think "we could simply diff th new vnodes in the parent, and not pass them to the child when there's no diff"

Unfortunately that doesn't take into account all possible edge cases, so there's no easy way around that in the current architecture . 

Also, assuming we *could* go this route, this would have a performance trade-off: As we would still have to diff he vnodes in the child, we diff the same vnodes two times now - which means that for components that are light themselves and receive *large* slot contents, the performance would worsen.

And I think that large slot trees are pretty common, as they are even nested quite often.

Converning your situation: If you are encountering performance issues, there are other options to optimize, most useful here are probably:

* extracting the heavy part into another child component which doesn't receive the slot, 
* using `v-once` if you have large node trees that only need to render once during the component's lifecycle.

**Comment by LinusBorg** [comment]
Hm, so I just took a look at the issues you mentioned this one in. Indeed sub-optimal.

@yyx990803 Can you share some insight?

**Comment by yyx990803** [comment]
There is already plan to improve and is tracked in #6351

**Comment by jacekkarczmarczyk** [comment]
Thank you!

**Comment by LinusBorg** [comment]
Wow, that's a weird feeling seeing my own answer in #6351 and seeing how it's almost verbatim the same I gave here, but I have no recollection of that other reply :D

Glad that this will be improved though.

**Comment by KaelWD** [comment]
Turns out john came across the same thing a few months ago: #5155

**Comment by Phlow2001** [comment]
I haven't looked deeply at the whole update/render pipeline, so speaking conceptually, I'm curious why dependency changes alone can't determine if a component/slot should re-render?
