### ISSUE TITLE
Limit input to number only without using number type

### ISSUE THREAD

**Issue by natezerk** [vuejs/vue#6902]
### What problem does this feature solve?
Is there any way to limit inputs to numbers only while still using `type='text'`.

Reasons for not using `type='number'` are:

* Does not allow 0's in first digit
* Does not accept minlength and maxlength
* Adds crappy up and down component in web browser

### What does the proposed API look like?
Adding `number` directive on input should limit to only numbers

**Comment by yyx990803** [comment]
That's a breaking change and is not going to happen. You can simply do this yourself by adding a `@keypress` listener, check the event key and call `event.preventDefault()` to filter input chars.

**Comment by natezerk** [comment]
@yyx990803 yes that is what I am doing, but would be a nice little inclusion (directive) to add this. Or at least allow directives to have a function that calls before the model is updated to check these things?
