### ISSUE TITLE
Functional components that use render slots and have slot-scope attr do not render

### ISSUE THREAD

**Issue by doman412** [vuejs/vue#6904]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/Lx5jr5o5/](https://jsfiddle.net/Lx5jr5o5/)

### Steps to reproduce
The jsfiddle should show the first `test-child` element not rendering when having `slot-scope` applied. 

### What is expected?
The functional component should render with the `slot-scope` attr. 

### What is actually happening?
When applying `slot-scope` to a functional component that renders a `slot` element, it never renders.

---
I would also like to see the ability (if possible) to access the `slot-scope` data from within the functional component's context, either as a prop or something like `context.slotScope`.

**Comment by yyx990803** [comment]
Slot name is extracted at compile time for scoped slots, and we might do that for normal slots as well in the future. Slot name really should be in the parent context to make sense, this means it's not recommended to dynamically add slot names directly to `context.data`.
