### ISSUE TITLE
Computed property setter on component other than "this" not called when updating v-model

### ISSUE THREAD

**Issue by wcoene** [vuejs/vue#6908]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/pLvn7o95/](http://jsfiddle.net/pLvn7o95/)

### Steps to reproduce
1. Declare a computed property on a parent component, with a setter
2. In a child component, pass the computed property as a v-model
3. Attempt to update the property via the v-model binding

### What is expected?
The computed property setter is called.

### What is actually happening?
The computed property setter is not called and the following message appears in the JavaScript console:

[Vue warn]: Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option.

---
This appears to be a regression in Vue 2.5.0, as changing the Vue version in the provided jsFiddle to 2.4.0 fixes the bug. The optimisation applied earlier in the 2.x-series to declare computed properties on the component's prototype appears to interfere with the call to hasOwn in function set (in observer/index).

**Comment by wcoene** [comment]
I've found a [change in parseModel](https://github.com/vuejs/vue/commit/e1da0d585c797860533d6cb10ea3d09c7fb711fc#diff-b5b98a176ffb68cecbc51791f29c5c65R74) which might be the culprit. Prior to this change, v-model bindings in the form 'foo.bar' would not be rewritten to '$set(foo, 'bar', $$v)'.

Relevant issues: #5932 and #6734.

**Comment by yyx990803** [comment]
Either way using `v-model` like this (directly on `$parent`) is not recommended...

**Comment by wcoene** [comment]
I understand. However, my reproducible isn't really reflective of what I'm trying to accomplish.

I have written a simple data grid, which accepts arbitrary Vue template strings to render column contents with. For the header column, I'm rendering a checkbox whose data is to be bound to a computed property on the containing component (the one that instantiates the data grid). This checkbox reflect the selected state of all rows in the grid, and changing should update the underlying selection flags on each of the rows.

I've implemented this by declaring a method findParent via a global mixin, which looks for the offending parent component, and then accessing the computed property:

`<checkbox-field v-model="findParent('planning').allesGeselecteerd" :disabled="!findParent('planning').canEdit" />`

Prior to 2.5.0 this worked nicely; however, when updating to 2.5.2 this code broke.

I do have a workaround: turning the computed property in question into a data property, and using a watch to sync its value with the individual selection flags. But that's hardly ideal.

**Comment by yyx990803** [comment]
This is coincidentally fixed in 83ed9260
