### ISSUE TITLE
Able to use `render` and `template` at the same time

### ISSUE THREAD

**Issue by yaodingyd** [vuejs/vue#6911]
### What problem does this feature solve?
Currently for mixins there is no way to distribute reusable template that can be extended in component. If there is a render function, it would also be ignored if component has template. There are some ways for this but it requires `vue.extend` and pug to do templating. Say I want to write a mixin and I don't want to limit my user's templating option, and this mixin would have a wrapper `div` for common styling.

### What does the proposed API look like?
Template and render would both be processed and in render function template can be access with $template or so.

If this proposal is too dumb, is there a better way to handle this scenario? thanks!

**Comment by posva** [comment]
To distribute content you can use slots but template and render are incompatible, you can only have one, or to be more precise, there's only `render` (and `staticRender`), the template is compiled into a _render function_ and placed under the `render` property
As a side note, a mixin with a template or a render function is quite strange, it makes more sense to put that into a component and extend it
