### ISSUE TITLE
Typescript problem: Lifecycle hooks with no this: V extends Vue

### ISSUE THREAD

**Issue by rcranjos** [vuejs/vue#6912]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/54rr1w0mzk](https://codesandbox.io/s/54rr1w0mzk)

### Steps to reproduce
In the link, AddItem component is using created hook just to show the issue.

Just user created hook and try use this inside it, when creating a ComponentOptions<V extends Vue> instance.

### What is expected?
I expected be able to use my V interface inside hook using "this" variable.

### What is actually happening?
"this" was referencing ComponentOptions instead V instance, although in runtime this is actually referencing the instance implemented from my V interface.

---
This issue happens just for advanced typescript users, does not affect the execution or Javascript users.

**Comment by victorfrancax1** [comment]
I`m having the same issue. "this" is only available for beforeCreated hook, although "this" is available for every hook in 2.4.4 version.

At the ComponentOptions<V> interface, we have:

beforeCreate?(this: V): void;
created?(): void;
beforeDestroy?(): void;
destroyed?(): void;
beforeMount?(): void;
mounted?(): void;
beforeUpdate?(): void;
updated?(): void;
activated?(): void;
deactivated?(): void;
errorCaptured?(): boolean | void;

**Comment by ktsn** [comment]
See: https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08

Since v2.5, we recommend to use `Vue.extend` to enable better `this` type inference .

If you prefer the object literal style, you need to explicitly add `this` type for each hook.

```js
export default {
  created(this: AddItem) {
    // ...
  }
}
```

**Comment by victorfrancax1** [comment]
One point that still does not make sense to me is: why only beforeCreate() has it?

**Comment by ktsn** [comment]
Because you cannot use your data in beforeCreate as it does not create them at the moment.
We annotate `this` type of `beforeCreate` to prevent to infer it as wrong type (default contextual `this` type of `ThisTypedComponentOptions`).
It's same as `data` hook. https://github.com/vuejs/vue/blob/dev/types/options.d.ts#L50

**Comment by rcranjos** [comment]
if the the data isn't created in beforeCreate, a beforeCreate?(this: null): void; declaration says explicitly that there is no "this" in beforeCreate hook.

**Comment by ktsn** [comment]
`this` type in beforeCreate is not `null`. It just does not have user defined data.
