### ISSUE TITLE
v-if / v-else not working with :type + v-model

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#6918]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/71931/](https://jsfiddle.net/50wL7mdz/71931/)

### Steps to reproduce
run the jsfiddle example

### What is expected?
`v-else` to work

### What is actually happening?
`v-else` seems to have no effect

---
maybe related/duplicate with issue #6917 or issue #6907

**Comment by misoguy** [comment]
I'd like a take a look at this if no one is on it yet :)

**Comment by FranckFreiburger** [comment]
This seems to be strongly related to the dynamic type `:type="'text'"`

**Comment by gebilaoxiong** [comment]
It seems that we need to add a pre condition

in https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/modules/model.js#L31

**Comment by gebilaoxiong** [comment]
@misoguy OK, you come first 😭

**Comment by gebilaoxiong** [comment]
We also need to consider `v-else-if` ...

**Comment by misoguy** [comment]
I've been digging into this issue for a while and realized that it's not that simple.
I have a roughly implemented working code for
`<div v-if="ok">haha</div><input v-else :type="type" v-model="test">`
but I think I need to write test for
```
<div v-if="ok">haha</div>
<input v-else-if="test==='b'" :type="type" v-model="test">
<input v-else :type="type" v-model="test">
```
and make this case to work as well. I'll work on this and send a PR :)

**Comment by misoguy** [comment]
@gebilaoxiong My browser didn't refresh and didn't see your comment and PR before commenting :( I guess this issue is closed then?

**Comment by gebilaoxiong** [comment]
@misoguy 

I thought no one was in the process of it, so it is repaired

I don't know to still have other problems

**Comment by misoguy** [comment]
@gebilaoxiong I should have commented that I was gonna work on it during the weekends.
My bad :( I tried out your code and tested it with 
```
<div v-if="foo">text</div>
<input v-else-if="bar" :type="type" v-model="test">
<input v-else :type="type" v-model="test">
```
as well. I don't think there is any more problem regarding this issue 👍

**Comment by gebilaoxiong** [comment]
@misoguy 

you can open a PR with your code  

I will merge my code with yours

**Comment by misoguy** [comment]
@gebilaoxiong Would that be ok? But your implementation and test code seems much better than mine! :) I'll open a PR as you suggested and let you decide whether or not to merge yours with mine :)

**Comment by misoguy** [comment]
@gebilaoxiong I have opened a PR as you suggested and only included the code to check `v-else` since I didn't want to get the credit for your work regarding `v-else-if` :)
It would be nice to contribute for the first time on `vue.js`!

By the way, while implementing my first PR on `vue.js`, I found that it was wonderfully maintained with all the test codes that were written! Great library! 👍

**Comment by gebilaoxiong** [comment]
@misoguy have a nice day.

**Comment by misoguy** [comment]
Thank you!
