### ISSUE TITLE
处理websocket数据，被认为是无限渲染组件You may have an infinite update loop in a component render function

### ISSUE THREAD

**Issue by jasmineY** [vuejs/vue#6928]
### Version
2.5.2

### Reproduction link
[http://no](http://no)

### Steps to reproduce
 1. create websocket connection,when the socket`forex` data change,continue the custom method `setPrice(item.varietyType)`

2. I want to set the `forex[m]`  to three port into the `<div class="wave_left"></div>`,
like the `<div class="wave_left"><span>first<em>second</em>third</span></div>`

#### data
```
{
   ...
  html:'<span>--</span>'
   ...
}
```
#### template
```
...
<div class="variety_right" v-if="forex[item.varietyType]">
         <div class="wave_left" v-html="html">{{setPrice(item.varietyType)}}</div>
</div>
...
```
#### methods
```
...
setPrice(m){
   if(this.forex[m]){
      var d = this.forex[m].split(',');
       this.html = d[0] '<em class="big-txt">' d[1] '</em>' d[2]
   }
}
...
```

#### error message
```
   vue.runtime.esm.js:430 [Vue warn]: You may have an infinite update loop in a component render function.
```
So, how to solve the problem?

### What is expected?
希望能够将socket返回的数据利用v-html指令插入在html标签中，而且不会被认为是无限渲染组件

### What is actually happening?
被认为是无限渲染组件

---
1.建立websocket连接并且处理websocket的返回数据
2.每次接收到websocket消息的时候都会进行dom的render
3.在渲染过程中对数据重新处理，想要将一个返回字段分割成三部分并且插入html标签中
4.对接收到的数据重新处理的过程中被认为是无限循环渲染组件

**Comment by yyx990803** [comment]
Please read our requirements carefully. This is not a runnable reproduction, nor is it minimal. It's a usage question.
