### ISSUE TITLE
`props` attribute supports the mix using of string and object

### ISSUE THREAD

**Issue by JasonKid** [vuejs/vue#6930]
### What problem does this feature solve?
`props` attribute only support one of an array of string and a object. But I think it will be more convenient if vue support to use both of them in one `props` attribute.

### What does the proposed API look like?
```javascript
    module.exports = {
        props: ['icon', 'title', 'subtitle', 'location', 'datetime', {
            locationIcon: {
                type: Boolean,
                default: true
            },
            locationAlign: {
                type: String,
                default: 'left'
            }
        }]
    }
```

**Comment by yyx990803** [comment]
Just do `{ foo: null, bar: { ... }}` - I don't think it's worth it to complicate the options even further.
