### ISSUE TITLE
Provide ES2015  bundle?

### ISSUE THREAD

**Issue by myst729** [vuejs/vue#6937]
### What problem does this feature solve?
Recently I'm working on a project that attempts to deploy ES2015 code to production. The idea was inspired by Philip Walton's [post](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/).

I hacked [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack) to [output dual bundles with feature detection to downgrade](https://github.com/myst729/es2015). The benefit is significant: ES2015 script execution time is only about 55% of ES5! And the bundle size reduces too. If vue (as well as vue-router, vuex, etc.) could provide ES2015 bundles, the performance boost can be even more significant.

According to the [es6 compatibility table](https://kangax.github.io/compat-table/es6/), ES2015 compatible browsers have got a lot of market shares. Although vue relies on ES5 feature `Object.defineProperty`, I think it is still meaningful to provide ES2015 bundle as an option.

### What does the proposed API look like?
This request is not about some particular APIs.

**Comment by felixbuenemann** [comment]
I believe PR #7110 tackles this issue.

**Comment by felixbuenemann** [comment]
To clarify: The ESM build also disables `buble` ES6 to ES5 transpilation in addition to allowing direct import in the browser as a module.
