### ISSUE TITLE
Transition 和 Flip 一起用的时候，有时候会出现 v-enter-to 不消失

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#6946]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/w3jj7tc3/3/](https://jsfiddle.net/w3jj7tc3/3/)

### Steps to reproduce
1.  列表过度使用 `transition-group`, 
2. 列表过度使用`Flip`
3. 页面中同时存在一个`并行`的 `css transition`.

结果：进入动画没有出现，`list-enter-to` 没有消失， 例子：https://jsfiddle.net/w3jj7tc3/5/

不管是去掉并行的过度： https://jsfiddle.net/w3jj7tc3/6/
```css
setTimeout(function() {
   //this.loading = false;
}.bind(this));
```

还是不用 `Flip`:  https://jsfiddle.net/w3jj7tc3/7/
```
.list-move {
  //transition: transform 1s;
}
```

都能正常工作。

### What is expected?
正确执行新增进入动画

### What is actually happening?

所以结论应该是：列表存在并行的过度，同时用`Flip`, 进入动画失效。

**Comment by yyx990803** [comment]
这个是因为同一组件在 flip 过程中重新渲染了，这会重置所有进行中的 flip 动画。由于 flip 的实现限制这个没有办法直接修复，解决办法是把列表拆分到一个子组件里面，这样就不会收到 loading 状态变化的影响了。
