### ISSUE TITLE
Class 绑定时 无法使用带有 - 的 class 样式命名。

### ISSUE THREAD

**Issue by zouchunxu** [vuejs/vue#6947]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
<script src="https://unpkg.com/vue"></script>

<div id="app">
  <ul>
    <li v-for="item in items" :class="{ item-right: item.isRight }">
      {{ item.name }}
    </li>
  </ul>
</div>

new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!',
    items: [
    	{name: 'zhangsan', isRight: true },
      {name: 'wangwu', isRight: false }
    ]
  }
})

### What is expected?
可以绑定 含命名空间 - 的 class 样式命名

### What is actually happening?
无法正确解析

---
测试了下 含 - 的 class 样式命名则无法绑定成功，去掉 - 则可以

**Comment by yyx990803** [comment]
You need to quote key names - it's JavaScript. Also, learn to actually make a repro, don't be lazy.
