### ISSUE TITLE
Error compiling template log - tweak log message order

### ISSUE THREAD

**Issue by lewishowles** [vuejs/vue#6950]
### What problem does this feature solve?
Firefox caps the length of an individual console log, which in the case of an 'Error compiling template' message could lead to the actual message being trimmed.

There is *supposed* to be an about:config option to change the limit, but this doesn't seem to have any effect.

My proposal is to move the message up to beside the 'error compiling template' message - example below. This would also make the error more skimmable.

### What does the proposed API look like?
[Vue warn]: Error compiling template: "Inline-template components must have exactly one child element."

<div id="app" data-icon-path="/build/img/app.svg">
	...

**Comment by yyx990803** [comment]
That seems to be an arbitrary and pointless limitation on Firefox's side, and I think that makes the error messages less useful. Long warnings are also pretty rare, or I'd suggest debug using a different browser.

**Comment by lewishowles** [comment]
I see my example didn't come out correctly as I forgot to wrap it in code blocks. I suggest leaving the code output there, just putting the actual message at the start.
