### ISSUE TITLE
Vue removes tab character from spans

### ISSUE THREAD

**Issue by nova-ind** [vuejs/vue#6951]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/72614/](https://jsfiddle.net/50wL7mdz/72614/)

### Steps to reproduce
Add a span element containing a tab character somewhere inside the app element, like inside a paragraph, before the text to be indented.

### What is expected?
The tab character should be left alone, thus being able to indent a given line.

### What is actually happening?
Vue strips out the tab character from the span.

---
I am using https://yabwe.github.io/medium-editor/ to edit content for my posts. When pasting in some code, it will contain tab indentations, which are transformed into `<span style="white-space: pre;">[TAB]</span>`. Upon viewing what was saved, I came to find out Vue removes the tab characters from inside the aforementioned span tags, thus the code I pasted in loses all indentation.

**Comment by yyx990803** [comment]
That's not Vue - that's just how HTML works. Any continuous whitespaces are displayed as a single whitespace. You probably need to learn about `<pre>` tags.

**Comment by nova-ind** [comment]
Hi Evan,

Thanks for your answer. However, it is in fact due to Vue, not HTML. You can see that in the fiddle provided. If you comment out the Vue instantiation, the output code will be displayed with indentations.

**Comment by yyx990803** [comment]
I'm talking about HTML pre tags, not v-pre.
