### ISSUE TITLE
router-link  点击下一页面再返回 白屏

### ISSUE THREAD

**Issue by xiaomao155** [vuejs/vue#6954]
### Version
2.5.2

### Steps to reproduce
router-link 使用时  会出现 在当前页面滚动一下然后点击进入下一页面，再返回出现白屏，滚动下才会 出现内容，怎么处理呢？

### What is expected?
解决白屏，现在的页面代码把router-line 换成了a，所以避免这个问题，如果不换呢

### What is actually happening?
会出现 在当前页面滚动一下然后点击进入下一页面，再返回出现白屏，滚动下才会 出现内容，怎么处理呢？

**Comment by yyx990803** [comment]
Missing reproduction.

**Comment by ganyusheng520** [comment]
the same as https://github.com/vuejs/vue/issues/5533
