### ISSUE TITLE
v-once in component with v-for cause a performance error

### ISSUE THREAD

**Issue by Leesson** [vuejs/vue#6956]
### Version
2.5.2

### Reproduction link
[https://codepen.io/Leesson/pen/bYbmZJ?editors=1010](https://codepen.io/Leesson/pen/bYbmZJ?editors=1010)

### Steps to reproduce
the link displays that component did not perform as its data source. but if you change the vue's version to 2.4.x, it does. 

### What is expected?
the list perform as its data source

### What is actually happening?
the list's price are all same

**Comment by yyx990803** [comment]
This is already fixed and will be released soon.

**Comment by Leesson** [comment]
reply so soon, efficiently, thx
