### ISSUE TITLE
调用$destroy后，组件生命周期出现异常。

### ISSUE THREAD

**Issue by Jack-93** [vuejs/vue#6961]
### Version
2.5.2

### Reproduction link
[https://github.com/Jack-93/vue-destroy-](https://github.com/Jack-93/vue-destroy-)

### Steps to reproduce
1、打开a,b选项卡
2、关闭一个，然后重新打开
3、切换tab选项卡，在vuetools中看到手动destroy的组件每次都会重新生成。

### What is expected?
手动destroy后的组件，再次重复打开，不会反复create

### What is actually happening?
手动destroy后的组件，再次重复打开，反复create

---
例子主要涉及几个技术点，
使用了keep-alive缓存组件，
通过router-view动态展示子组件
在点关闭时，手动destroy了router-view的当前组件，然后再次打开组件，或者切换tab，手动destroy过的组件每次都会create

**Comment by Jack-93** [comment]
没有destroy前，切换正常，说明vue的判断机制能准确识别组件已存在，并且复用。
调用destroy后，切换异常，是否是destroy破坏了识别组件已存在复用的判断机制。所以每次切换都判定为组件不存在，每次都会生成新的子组件。

**Comment by yyx990803** [comment]
由父组件管理生命周期的组件不支持手动销毁。

**Comment by lizijins** [comment]
@yyx990803 我用的component动态展示子组件，$destroy销毁后也是遇到这样的问题。
看了下include属性，目前只支持匹配组件的name或注册名。但是我现在的场景是，不同的页面可能会使用同一个组件，这样使用include时，就不能区分这些页面了。

**Comment by chenliang-dragon** [comment]
@lizijins 你好，请问你这个问题解决了吗？

**Comment by chenliang-dragon** [comment]
@yyx990803 我需要加载多个同名组件，用keep-alive的include无法实现，该怎么弄？

**Comment by zhijunw** [comment]
> @yyx990803 我需要加载多个同名组件，用keep-alive的include无法实现，该怎么弄？

请问您现在有解决方案吗 我也是碰到 多个路由用同一个 组件   name一样 缓存不了
