### ISSUE TITLE
The input enter event in the IE10 environment is invalid

### ISSUE THREAD

**Issue by Cydmi** [vuejs/vue#6962]
### Version
2.4.4

### Reproduction link
[https://fiddle.jshell.net/oeeu4jz0/4/](https://fiddle.jshell.net/oeeu4jz0/4/)

### Steps to reproduce
Use IE10 test.

### What is expected?
Press enter to return 1,not 2

### What is actually happening?
Press enter to return 2,not 1.

---
I tried the modifier(`stop`,`prevent`,`self `), but it didn't work！why?

**Comment by LinusBorg** [comment]
This is not a Vue issue. When pressing enter, IE10 will issue a"submit" event, which will trigger the next button's `click` event - it seems IE10 implicitly assumes a `<button>` without a `tye` to be of `type="submit`.

By declaring `type="button"`, the problem can be resolved:

https://fiddle.jshell.net/oeeu4jz0/6/

And just as a demo of the problem without Vue:

https://fiddle.jshell.net/ve8uoz7r/2/

**Comment by Cydmi** [comment]
@LinusBorg Thank you! 😀
