### ISSUE TITLE
Malformed HTML in a <slot> breaking app

### ISSUE THREAD

**Issue by andosteinmetz** [vuejs/vue#6970]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/72963/](https://jsfiddle.net/50wL7mdz/72963/)

### Steps to reproduce
1) Create a Vue app with the following HTML inserted into a `<slot>`: 

`<a href="/example/search?search=Example%20Example"  title="Search for J. <a href="/example/search?search=Example%20Example"  title="Search for Example Example"  nofollow="nofollow" >Example Example</a>"  nofollow="nofollow" >J. <a href="/example/search?search=Example%20Example"  title="Search for Example Example"  nofollow="nofollow" >Example Example</a></a>`  

2) Notice that Vue breaks down and throws the error: `Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'search?search' is not a valid attribute name. `

### What is expected?
Vue will catch the error and issue a warning, skipping over the malformed tag.

### What is actually happening?
An uncaught exception is breaking the app.

---
What's creating this bad HTML is that we have a regex on our back end that links chosen search terms throughout an article, and it has been prone to errors if an editor links one term that contains another such as "Prince" and "Prince William".  

Clearly, the code that's generating such a bad link in the first place should be fixed, but it seems brittle that if malformed HTML is entered into a `<slot>` it will break the whole app.   

I imagine a try/catch block in the right place could solve the problem. I'll take a look and see if I can find where in the source this might happen, but thought I'd mention it here before digging in.  

Thanks!

**Comment by andosteinmetz** [comment]
Here's where the error is being thrown:
https://github.com/vuejs/vue/blob/c64f9ae1649175ee8cac1c7ecf3283897c948202/src/platforms/web/runtime/modules/attrs.js#L61

**Comment by yyx990803** [comment]
There's nothing we can do about it if the template to compile is malformed - we can't magically make syntax errors right. This also leads to another point: we strongly recommend against using dynamic/user-generated content as part of your template, because that's a security bad practice and can lead to XSS.

**Comment by andosteinmetz** [comment]
@yyx990803 fair enough. i thought maybe the error could be contained and the element containing the error could be skipped and create a warning rather than throwing an uncaught error.

to clarify re: XSS, the content in the app is being generated by our CMS, accessible only to logged-in editors.
