### ISSUE TITLE
Support local directives in functional components

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#6974]
### What problem does this feature solve?
There are directives meant to assist a component behavior and not to be declared globally, which works fine for components and the directives option, but that doesn't work for functional components.

I have tried declaring the directives in the data, passing by the def, name and raw name and still, it doesn't work. Knowing that globally declared directives do work on functional components I would like to request a way to use them locally as well.

**Comment by yyx990803** [comment]
Gonna track this under https://github.com/vuejs/vue/issues/6872
