### ISSUE TITLE
Unicode naming for methods seems unsupported. Some warning will be appreciated.

### ISSUE THREAD

**Issue by nobodxbodon** [vuejs/vue#6975]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/p48cLbe3/2/](http://jsfiddle.net/p48cLbe3/2/)

### Steps to reproduce
```
    <script src="https://unpkg.com/vue"></script>
    <div id="元素id5">
      <p>{{ 问好 }}</p>
      <button v-on:click="改口">改口</button>
    </div>
```
```
var 应用5 = new Vue({
  el: '#元素id5',
  data: {
    问好: '你好'
  },
  methods: {
    改口: function () {
      this.问好 = '吃了么'
    }
  }
})
```

### What is expected?
Excuse me if this is closer to feature request.

It'll be great if method can support unicode naming. Otherwise it may be better to provide some feedback.

Thanks for your efforts.

### What is actually happening?
I'm guessing validation passes because the method does exist, but somehow invoking method fails.

**Comment by javoski** [comment]
You can try
```html
```

**Comment by nobodxbodon** [comment]
@javoski thanks. As I'm new to Vue, may I ask what's the difference between these two ways?

**Comment by posva** [comment]
It's just a workaround
by default Vue will call the method passing `$event` to it if you pass the function instead of calling it: `@click="doIt"` -> `@click="doIt($event)"`

**Comment by HerringtonDarkholme** [comment]
I don't think we can afford warning in runtime build, thoug :/

https://stackoverflow.com/a/9392578/2198656

> if you were to summarize all these (variable naming) rules in a single ASCII-only regular expression for JavaScript, it would be 11,236 characters long (for ECMAScript 5.1 / Unicode 6.1.0)

**Comment by nobodxbodon** [comment]
As the alternative method suggested [above](https://github.com/vuejs/vue/issues/6975#issuecomment-340695407) does work, it just occurred to me that `v-on:click="改口()"` might work, and as I just tried it does work! While `v-on:click="改口"` doesn't.

**Comment by 9percent** [comment]
It did treat the Unicode names differently behind the scene, while the method name is like "doIt", button click invokes the "boundFn" directly, but when the method name is an Unicode name, the button invokes something like a "click event handler" instead:
```
on: {
    "click": function($event) {
        改口
    }
}
```

**Comment by yyx990803** [comment]
In order to use the method name directly it needs to be a alphanumeric identifier. Adding the check, as @HerringtonDarkholme has pointed out, is too expensive and not worth it.

**Comment by nobodxbodon** [comment]
Thanks for addressing this. Still, I wonder if some feedback could be provided in this case, maybe something like "You used a non-alphanumeric identifier. If it's intended, add () as a workaround."?

**Comment by yyx990803** [comment]
The problem it's too expensive to detect "a non-alphanumeric identifier (maybe a unicode identifier)" from "a full expression"

**Comment by nobodxbodon** [comment]
Excuse me if I miss something obvious. I realize it's too expensive to decide if an identifier is legit unicode identifier, as pointed out [above](https://github.com/vuejs/vue/issues/6975#issuecomment-341301258). However I thought detecting if an identifier is non-alphanumeric is easier, like checking if it matches `/[A-Za-z_$][\w$]*/`. That would require developer to check if it's legit unicode identifier, but having some feedback would be better than none, I suppose?
Anyways, as unicode naming is not at all in wide use, plus it does have alternative solution(with `()`), thanks to the community support, I'd totally understand if this edge case has too low priority to be picked up in any time soon. 
Thanks again for your patience and time!
