### ISSUE TITLE
shorter import of vue component with separation of concern

### ISSUE THREAD

**Issue by ytbryan** [vuejs/vue#6976]
### What problem does this feature solve?
It's great that vue components can be separated into js and css via [separation of concern](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns)

It will be greater if I can import nested vue component, this way: 

`import app from './a_vue_component' `

instead of 

`import app from './a_vue_component/a_vue_component.vue' `

The nested vue component has the same name as its directory. Will you consider support nested Vue component to be imported this way? Thank you! 

### What does the proposed API look like?
```
import app from './a_vue_component' // contains a nested a_vue_component.vue 

//instead of 

import app from './a_vue_component/a_vue_component.vue' 

```

**Comment by posva** [comment]
Unfortunately, this is unrelated to Vue. You can however, add an `index.js` file and do something like this:

```js
// avuecomp/index.js
export app from './avuecomp.vue'
```

```js
// app.js
import { app } from './avuecomp'
```
