### ISSUE TITLE
suggest component namespace 建议增加组件的命名空间功能

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#6978]
### What problem does this feature solve? 这个功能解决了什么问题？

For third-party components lib mix using, to avoid conflict which is difficult to solve in the coder's level without rebuild source, and easy to batch import.
在多个第三方组件库混合使用时，可以避免不重新编译第三方源码就无法在编程层面解决的命名冲突问题，并便于第三方组件库的批量导入。

### What does the proposed API look like? 你期望的 API 是怎样的？

```js

thirdComponents = {

    abc:{ template:"<div><scope:def /></div>" },

    def:{ template:"<div />" }

};

Vue.namespace('third',thirdComponents);

Vue.namespace('fourth',fourthComponents);

new Vue( {

    el: "...",

    template:`
        <div>
            <third:abc />
            <x:abc />
            <ele:abc />
            <amazon:abc />
            <my-component-a />
            <my-component-b />
        </div>
    `,

    components:{

        x: "fourth",

        ele: eleComponents,

        amazon: amazonComponents,

        myComponentA:{ template:"<div />" },

        myComponentB:{ template:"<parent:my-component-a />" },

    }

});

```

**Comment by posva** [comment]
You can already name the components with a namespace, you have to generate it yourself, though
But this is achievable in userland with a plugin that checks for nested objects and transforms the `components` property in a `befoeCreate` hook.

Keep in mind that most libs already namespace their components: for example vuetify does `v-button`

**Comment by LongTengDao** [comment]
@posva 
Thank you, that's a feasible way indeed. `Vue` had supported the basic use of namespace, this I didn't notice before, thank for hint.
谢谢，这确实……是个办法。不过现在的 `Vue` 组件名已经支持基本的命名空间符号了，这点我之前没有发现，谢谢提醒。
