### ISSUE TITLE
checkbox not responding to v-model changes

### ISSUE THREAD

**Issue by shaunc869** [vuejs/vue#6979]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/shaunc869/1Ly7mL6n/17/](https://jsfiddle.net/shaunc869/1Ly7mL6n/17/)

### Steps to reproduce
Please see the JSFiddle, but basically I am trying to get a checkbox to change based on an underlying change to the v-model that maps to it, but initiating this change via the "Set Taxable" link vs check the box directly.

### What is expected?
The checkbox should toggle checked/unchecked.

### What is actually happening?
Nothing :-)

**Comment by posva** [comment]
This is more like a question so I recommend you to ask it on the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/)

What is happening is that you change a computed property which is a clone from a prop. I encourage you to take a look at https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events
You need to modify the original variable to make it change 🙂

**Comment by shaunc869** [comment]
In this case the reason the clone is occurring is that this.item is coming from vuex and I don't want to mutate the data outside of the store. So how do I handle this situation? Also it's confusing to think that if you clone and create a new variable that you can't that use that separately from the original variable?

**Comment by posva** [comment]
You probably want to use a computed with a setter like in https://vuex.vuejs.org/en/forms.html
