### ISSUE TITLE
destroy hook is called before transition finishes

### ISSUE THREAD

**Issue by autumnwoodberry** [vuejs/vue#6983]
### Version
2.5.2

### Reproduction link
[https://codepen.io/autumnwoodberry/pen/yPNdRB](https://codepen.io/autumnwoodberry/pen/yPNdRB)

### Steps to reproduce
- Click the "toggle" button.
- Notice that the "destroyed" hook of the transitioning component has been executed before the transition is complete.

### What is expected?
destroyed hook is not executed until after the transition is complete

### What is actually happening?
destroyed hook is executed before transition is complete

---
https://forum.vuejs.org/t/vue-destroys-components-on-a-page-when-they-are-still-needed/20560/4

**Comment by yyx990803** [comment]
This is expected behavior. Think of it the other way around: the leave transition is triggered by the removal of the element. Transition state is ephemeral and does not reflect Virtual DOM state - in the virtual DOM the element is considered to be already destroyed.

If you want to do something when the element is finally removed in real DOM, use transition hooks instead.

**Comment by plashenkov** [comment]
@yyx990803 
How to incapsulate destroying or "garbage collecting" inside components?
What hook inside components to use to destroy components _after_ transition of the parent page finishes?
Here is the screencast: http://take.ms/70FsB

**Comment by autumnwoodberry** [comment]
@plashenkov https://codepen.io/autumnwoodberry/pen/RjWoWb?editors=1111

**Comment by plashenkov** [comment]
@autumnwoodberry Thanks, but this is a kind of a workaround though. For example, if a transition is not used, then `transitionend` is not triggered. And in your example transition is applied directly to a component, not to a parent component (a page, for example). Component shouldn't know the parent container uses a transition or not. I believe, some strong and straightforward event needed, which will help us to detect the last moment when the component really is not needed anymore and we can destroy it.

**Comment by pSchaub** [comment]
Is there a known "best practice" how to wait for the transitions to finish?

Example: I need to wait for the page transitions. See https://github.com/staskjs/vue-slick/issues/56

**Comment by diachedelic** [comment]
I made a mixin to work around this issue: https://www.npmjs.com/package/vue-removed-hook-mixin

**Comment by philoozushi** [comment]
Another side problem is that :

When using with router-view 
```html
<transition mode="out-in">
  <router-view ref="page"/>
</transition>
```

If the `<router-view>` contains any `<router-link>` (which is very likely), then when the transition starts, by destroying the view, it also destroys the children links, so they don't work as expected anymore and don't get the active CSS classes applied, whereas the router-view is still visible in the screen.
Which leads to a transition with no style for the active links (= bad when you want that to be styled).

A workaround is to fix the links manually on all router-views :
```js
{
    ...
    beforeRouteLeave(to, from, next) {
        for (let link of this.$el.querySelectorAll(`a[href="${to.path}"]`))
            link.classList.add('router-link-exact-active')
        next()
    }
}
```
Not clean for a Vue app, but if someone has a better solution...
