### ISSUE TITLE
Regression bug in 2.5.2

### ISSUE THREAD

**Issue by bokub** [vuejs/vue#6984]
### Version
2.5.2

### Reproduction link
[Working jsFiddle, 2.5.1](https://jsfiddle.net/6d62j3jc)
[Broken jsFiddle, 2.5.2](https://jsfiddle.net/6d62j3jc/1/)

### Steps to reproduce
In the first jsFiddle, you can check / uncheck the box without problem. The vue version is 2.5.1

The second jsFiddle is exactly the same one with vue 2.5.2, and the checkbox cannot be checked anymore!

### What is expected?
A checkable checkbox

### What is actually happening?
The checkbox stays unchecked

---
I think the bug is linked to the `v-if` / `v-else` syntax, but I don't know how to investigate any further.

The code may seem dirty (using the onchange attribute for example) but that is only a small portion of my app where I cannot bind my checkbox value with vue.

**Comment by yyx990803** [comment]
It's because you are using `onchange` instead of Vue's own `v-on:change`: https://jsfiddle.net/6d62j3jc/2/

2.5.2 adjusts event firing order by prioritizing correct behavior for Vue's own event listeners. Behavior of external listeners that mutates application state cannot be guaranteed.

**Comment by bokub** [comment]
All right, thanks :+1:
