### ISSUE TITLE
Nested <template> tag doesn't support v-text

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vue#6988]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/ybb37jr4/](https://jsfiddle.net/ybb37jr4/)

### Steps to reproduce
Create a template where a certain condition directive must only emit text, and therefore the developer must use `<template v-else>` rather than `<span v-else>` or similar. That nested template tag will only work with `{{ text }}` but not with `v-text="text"`.

For example:

```vue
<p v-if="!message">No message...</p>
<template v-else v-text="message"/>
```

### What is expected?
Both nested `<template v-text="text"/>` and `<template>{{ text }}</template>` emit text from the variable.

### What is actually happening?
Nested `<template v-text="text"/>` does not emit anything.

---
Interestingly, `<template v-text="text"/>` actually works in SSR, but immediately crashes once the client-side Vue inits, with:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.
```

**Comment by posva** [comment]
`v-text` should be used on real nodes as it sets the inner text of an element. So it cannot be used with a template
We can however, add a warning for this

**Comment by yyx990803** [comment]
This is expected: `<template>` itself doesn't produce any visible content.

**Comment by IlyaSemenov** [comment]
@yyx990803 But in my example it **is** combined with a structural directive (`v-else`).

@posva But it **does** work in SSR:

```js
const Vue = require('vue')
const app = new Vue({
  template: '<div><p v-if="!foo">No foo</p><template v-else v-text="foo"/></div>',
  data: { foo: 'Hello' },
})

const renderer = require('vue-server-renderer').createRenderer()

renderer.renderToString(app, (err, html) => {
  if (err) throw err
  console.log(html)
})
```

this emits:

```html
<div data-server-rendered="true">Hello</div>
```

- exactly as expected.

The same code does not work in the browser, however (see the jsfiddle). Isn't this inconsistency a problem?

**Comment by yyx990803** [comment]
Let's put it this way: `v-text` is the equivalent of setting `textContent` property of a node. This is why it doesn't work on a `<template>` node. The fact that it works in SSR it coincidental and we will probably fix it to maintain consistency with client-side behavior, so you should not rely on it.
