### ISSUE TITLE
Execute a list move transition when the leave transition hook callback is called with `true`

### ISSUE THREAD

**Issue by Shiva127** [vuejs/vue#6989]
### What problem does this feature solve?
For the moment, it's not possible to execute a [list move transition (`v-move`)](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions) after a leaving transition (in CSS because it's not possible to delay `display = none` with `transition` or in a [transition JavaScript hook](https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks) because Vue do not watch `el.style.display = 'none'` when it's in a callback).

### What does the proposed API look like?
The solution could be to add a parameter in the leave hook callback to ask Vue to hide the element and play the list move transition (`v-move`).

```javascript
methods: {
  leave (el, done) {
    // Play a long animation
    Velocity(el, { translateX: '15px', rotateZ: '50deg' }, { duration: 600 })
    Velocity(el, { rotateZ: '100deg' }, { loop: 2 })
    Velocity(el, {
      rotateZ: '45deg',
      translateY: '30px',
      translateX: '30px',
      opacity: 0
    }, { complete: () => {
      // Use true to indicate that Vue must hide the element
      // and play the list move transition (v-move)
      done(true) // <---
    }})
  }
}
```

**Comment by posva** [comment]
Why would you move the element once it's not there anymore?

**Comment by yyx990803** [comment]
I think I understand what you are asking for, unfortunately properly implementing that introduces many unresolved questions - e.g. what if the list changes again during a leave transition, and what if it changes during a move? These brings the complexity to a whole different level and we'd rather tackle it as a standalone package, not in core.

**Comment by Shiva127** [comment]
@yyx990803 Sorry to insist and to waste your time but I do not understand where is the problem.

> What if the list changes again during a leave transition, and what if it changes during a move?

Don't change the actual behavior. You can already make a shuffle in the middle of a leave hook. Just make another move transition when the callback is called (like when you press multiple time on shuffle in [the list move transition example](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions)).

Sorry if my assumptions are wrong, I don't know how FLIP is implemented and I don't have the big picture of the problem like you.

If I'm wrong, can you point me in the right direction to implement a Vue package for that?

@posva I don't want to move the element itself but the rest of the list (the other elements), rearrange the list if you prefer.

Try this example:
```
<template>
  <div>
    <button @click="shuffle">Shuffle</button>
    <button @click="add">Add</button>
    <button @click="remove">Remove</button>
    <transition-group name="list-complete" tag="p" @leave="leave">
      <span v-for="item in items" :key="item" class="list-complete-item">{{ item }}</span>
    </transition-group>
  </div>
</template>

<script>
import _ from 'lodash'

export default {
  data () {
    return {
      items: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      nextNum: 10
    }
  },
  methods: {
    randomIndex () {
      return Math.floor(Math.random() * this.items.length)
    },
    add () {
      this.items.splice(this.randomIndex(), 0, this.nextNum++)
    },
    remove () {
      this.items.splice(this.randomIndex(), 1)
    },
    shuffle () {
      this.items = _.shuffle(this.items)
    },
    leave (el, next) {
      setTimeout(() => {
        el.style.display = 'none' // Not working cause Vue do not watch `el.style.display = 'none'`
        next()                    // So replace these who lines with `next(true)`
      }, 2000)
    }
  }
}
</script>

<style>
p {
  display: flex;
  flex-flow: row wrap;
}

span {
  flex: 0 0 auto;
  width: 4em;
  margin: .2em;
  background-color: tomato;
  text-align: center
}

.list-complete-move {
  transition: transform 2s;
}

.list-complete-enter-active {
  transition: opacity 2s 2s;
}

.list-complete-enter,
.list-complete-leave-to {
  opacity: 0;
}

.list-complete-leave-active {
  transition: opacity 2s;
}
</style>
```
