### ISSUE TITLE
[Practice] Together with data() and beforeCreate() to define a property start with $.

### ISSUE THREAD

**Issue by lichaozhy** [vuejs/vue#6993]
### What problem does this feature solve?
The property that start with _ or $ will CAN be proxied on the Vue instance by this way.

I've known below: 
>Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.

But I really need define a property that start with $ to register to each VM instance, and make it also reactive like ``this.$store.state[any]`` in Vuex.

Does vue encourage this method?

Is it correct?

Whether I can always use this way in the future?

### What does the proposed API look like?
In plugin.js

```js
export default {
	install(Vue, options) {
		Vue.mixin({
			data() {
				return {
					$myData: window.storage
				};
			},
			beforeCreate() {
				this.$myData= window.storage;
			}
		});
	}
};
```

In a component

```vue
<template>
    <div>
        {{$myData}}
    </div>  
</template>

<script>
export default {
}
</script>
```

In global

``` js
window.storage = {
	test: 0
};

setInterval(() => storage.test = Date.now(), 500);
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Define it in the `prototype` so it's accessible everywhere:
```js
 Vue.prototype.$myMethod = function (methodOptions) {
    // something logic ...
  }
```
or use defineProperty (prevents overwrite from the user):
```js
Object.defineProperty(Vue.prototype, '$route', {
    get () { return this._routerRoot._route }
  })
```

If you need data to be reactive, you can use `Vue.util.defineReactive` like [in vue-router](https://github.com/vuejs/vue-router/blob/dev/src/install.js#L27)
```js
Vue.util.defineReactive(this, '_route', this._router.history.current)
```

In your case doing this seems to be enough:

```js
Vue.prototype.$myData = window.store
```

**Comment by lichaozhy** [comment]
OK. Thanks again. I promise I will ask questions in forum in the future.

But just extending prototype does not work. I have tried.

Using defineReactive resolve my problem gracefully. But this method is not be writen in any docs? I had read the code in vue-router before. I'm just not sure if that's the right way because I know vue-router is an official module.

**Comment by posva** [comment]
It's true, that relying on `defineReactive` is not fully secure because the api may change in the future without notice. [Here's an example with defineReactive](http://jsfiddle.net/69yq3g4q/)

Here's an example using another Vue instance for the reactivity: http://jsfiddle.net/7er8ptoy/ This version is only using public api 🙂
