### ISSUE TITLE
[TypeScript] Default export of the module has or is using private name 'VueConstructor'

### ISSUE THREAD

**Issue by gluons** [vuejs/vue#6999]
### Version
2.5.3

### Reproduction link
[https://github.com/gluons/vue-typescript-export-issue](https://github.com/gluons/vue-typescript-export-issue)

### Steps to reproduce
- Export some object that contain `Vue` or `typeof Vue` types.
- Set `compilerOptions` -> `declaration` to `true`

### What is expected?
Able to build without error.

It should be able to export plugin/library with TypeScript declaration.

### What is actually happening?
`Default export of the module has or is using private name 'VueConstructor'` happened when built it.

---
I'm developing **Vue** component with **TypeScript**.  
I also need TypeScript to generate declaration for other TypeScript developer (And also JavaScript with **Vetur** 🙂).  
But I face this error. 😢

> Thanks [bbuchanan](https://forum.vuejs.org/u/bbuchanan) for the [cause](https://forum.vuejs.org/t/default-export-of-the-module-has-or-is-using-private-name-vueconstructor/19624/5).

**Comment by ktsn** [comment]
I've made a PR to expose `VueConstructor` #7002
In the meantime, you can manually annotate the `install` function by `PluginFunction`

```ts
export default {
  install: install as PluginFunction<void>
}
```

**Comment by relign** [comment]
Version
2.5.13
![image](https://user-images.githubusercontent.com/13749042/34462328-86e3b0d6-ee7c-11e7-8651-97be6ad74453.png)
I try vue@2.5.13, when set `compilerOptions.declaration = true` in `tsconfig.json`,it export error
`Default export of the module has or is using private name 'VueConstructor'.`
![image](https://user-images.githubusercontent.com/13749042/34462342-feb155fa-ee7c-11e7-9412-052d710262c8.png)

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
