### ISSUE TITLE
Better slot syntax with v-slot and v-fallback

### ISSUE THREAD

**Issue by Kinrany** [vuejs/vue#7000]
### What problem does this feature solve?
I want to write a component that wraps or doesn't wrap one piece of HTML using another piece of HTML depending on a condition supplied by a prop. Usage would look like this:

```html
<my-conditional-wrap-component :condition="is_selected">
    <p v-slot="content">
        content
    </p>
    <b v-slot="wrapper">
        <v-slot />
    </b>
</my-conditional-wrap-component>
```

It would render as either (in case `is_selected` is true) this:
```html
<b>
    <p> content </p>
</b>
```
or (in case `is_selected` is false) this:
```html
<p> content </p>
```

As far as I know with current `<slot>` syntax this is impossible because the children of `<slot>` are used as a fallback. (Which, if I understand the rationale correctly, is done to be consistent with web-components' slots. Unfortunately it's also inconsistent with Vue's components, whose children are used as content for their slots.)

With `<v-slot>` the component's source would look like this:
```html
<template id="my-conditional-wrap-component-template">
    <template v-if="condition">
        <v-slot name="wrapper">
            <v-slot name="content" />
        </v-slot>
    </template>
    <template v-else>
        <v-slot name="content" />
    </template>
</template>
```

### What does the proposed API look like?
The proposed API is the same as the current API for `<slot>`, with two differences:

1. Currently `<slot>`'s children are used as a fallback. `<v-slot>'s children will be used to fill nested slots instead, as if the piece of HTML inserted in place of `<v-slot>` was a component with it's own slots.
2. `v-fallback` directive will be used similar to `v-else` to provide a fallback instead of `<slot>`'s children.

Component: 

```html
<template id="my-component">
    <v-slot name="first">
        <v-slot name="second">
            <p> Hello world! </p>
        </v-slot>
    </v-slot>
</template>
```

Usage:

```html
<my-component>
    <template v-slot="first">
        <p> first begins </p>
        <v-slot />
        <p> first ends </p>
    </template>
    <template v-slot="second">
        <p> second begins </p>
        <v-slot />
        <p> second ends </p>
    </template>
</my-component>
```

Rendered:

```html
<p> first begins </p>
<p> second begins </p>
<p> Hello world! </p>
<p> second ends </p>
<p> first ends </p>
```

`v-fallback` example:
```html
<template id="my-component">
    <v-slot />
    <p v-fallback> Empty slot! </v-fallback>
</template>
```

`v-fallback` could also be used in other situations where an element might fail in any way, like `<component>`:
```html
<component :is="my_component" />
<p v-fallback> {{my_component}} is not a valid component name! </v-fallback>
```

**Comment by posva** [comment]
If you want to wrap a slot, it's better to let the component user do so because the intention is clearer:

```html
// foo.vue
<template>
     <slot >
         <div class="fallback wrapper">
               <slot name="content">
                   <p>Content</p>
               </slot>
         </div>
    </slot>
</template>
```

so the user can write

```html
<foo>
    <wrapper>
        <content/>
    </wrapper>
</foo>
<foo>
    <content slot="content"/>
</foo>
```

which clearly shows how things are put together.

Related: #5401 and #6811

**Comment by Kinrany** [comment]
If I understood your approach correctly, your solution to the problem I described would be this:
```html
<my-conditional-wrap-component>
    <p v-if="!is_selected">
        content
    </p>
    <b slot="wrapper">
        <p>
            content
        </p>
    </b>
</my-conditional-wrap-component>
```

Which means I have to either repeat myself or create a separate component and write extra boilerplate. Both seem suboptimal.

And I might as well just write this instead:
```html
<b v-if="is_selected">
    <p>
        content
    </p>
</b>
<p v-else>
    content
</p>
```

I took a look at the other two issues and I'm not sure in what way they are related. Please expand?

**Comment by yyx990803** [comment]
Thanks for the suggestion - however, having parallel mechanisms that solve similar problems, but each with its own complexity is a big no-go in terms of API consistency. So this will not be something that we can consider in core, but you are welcome to try to implement this in userland.

**Comment by Kinrany** [comment]
All right, thanks for the answer.

Is this something you can consider as a replacement for `<slot>` for Vue 3.x?
