### ISSUE TITLE
$refs是否应该改为统一的返回数组更为合适?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#7003]
### What problem does this feature solve?
$refs有时候返回对象有时候返回数组,我测试了一下应该是v-for中的就返回数组,其他的返回对象,是否应该统一改为返回数组更为合适,否则每次取回还得判断下是否数组。

### What does the proposed API look like?
https://cn.vuejs.org/v2/api/#ref

**Comment by javoski** [comment]
你好，`ref`  是否在 `v-for` 中是**明确**的，一般情况下不存在每次都要判断的情况。
如果你遇到了这种情况，可以举个例子。

**Comment by yangdan8** [comment]
只是在v-for中返回数组?如果一个页面上有两个相同的ref返回数组还是对象?我觉得这里很模糊,api也没有讲

**Comment by yangdan8** [comment]
请看这里的例子,如果ref同名child无法获取第二个,因为返回的是对象,
而v-for中的可以,因为返回的是数组,
这会导致将v-for修改为正常的非html内容,将会导致修改js获取$refs这块的代码
https://codepen.io/yangdan8/pen/MOebVJ
