### ISSUE TITLE
Image extension sensitive with upper case

### ISSUE THREAD

**Issue by leapit** [vuejs/vue#7007]
### Version
2.5.3

### Reproduction link
Please see below error shot

### Steps to reproduce
Follow this step,

1. Use vue_cli create a default project
2. Change the logo.png extension with upper case,`mv src/assets/logo.png src/assets/logo.PNG`
3. Also change code in App.vue `<img src="./assets/logo.PNG">`

then you will got an error with bowser,
<img width="748" alt="wx20171106-135104 2x" src="https://user-images.githubusercontent.com/1665671/32427201-d166ec78-c284-11e7-806f-c7cabc4b56aa.png">

### What is expected?
Should with no error

### What is actually happening?
Go an error

**Comment by posva** [comment]
Keep in mind Windows and OS X are case insensitive by default. However, this is not related to vue but rather to one of the loaders used by the webpack template which doesn't handle uppercased extensions by default. You can add it yourself if you want by adding an `i` (case insensitive) to the regex used by url-loader (line 41)

```js
test: /\.(png|jpe?g|gif|svg)(\?.*)?$/i,
```
