### ISSUE TITLE
vue使用iframe嵌入另外一个vue页面 不加载body head

### ISSUE THREAD

**Issue by gecaitao** [vuejs/vue#7010]
### Version
2.5.3

### Reproduction link
[https://内网，无法提供，任意vue页面可重现](https://内网，无法提供，任意vue页面可重现)

### Steps to reproduce
1、父页面写入iframe；src为另外一个vue页面。 或者直接在dom上修改
2、google打开正常，IE9、10、11打开 iframe内容空白不加载

### What is expected?
IE正常显示

### What is actually happening?
IE内容空白

**Comment by yyx990803** [comment]
重现是必须的，本来就不接受整个项目作为重现。

**Comment by gecaitao** [comment]
没太理解什么意思，是vue本身就不支持这样实现吗

**Comment by gecaitao** [comment]
尤大是不是理解错了我的问题，我是说任意页面都可以重现的，不是不能重现， 不过现在是内网地址 无法提供给其他人重现，其他人可以用自己的vue页面进行重现

**Comment by zjxpcyc** [comment]
我也遇到这个问题了，不知道怎么搞的。

我这边现象是，昨天还可以。然后今天一早上班就不行了。完全懵逼了，不知道啥原因，鼓弄了马上一天了，也不知道什么原因。唉~

本来以为是我这边有死循环，或者嵌套执行之类的问题导致的。我把 代码精简到 只有一个 iframe 标签，都不行。

**Comment by gecaitao** [comment]
@zjxpcyc   我最后在自己工程内容重新copy了一遍代码

**Comment by zjscy666** [comment]
我也遇到了，不过应该是第二层iframe因为同域，没有发请求，如果是单层的iframe，其实也一样，第一次好的，第二次是在iframe中触发，通过jq修改iframe的src，避免嵌套，也是不行，好像只要是iframe中触发的都不行，我太难了

**Comment by weixingqi** [comment]
> 我也遇到了，不过应该是第二层iframe因为同域，没有发请求，如果是单层的iframe，其实也一样，第一次好的，第二次是在iframe中触发，通过jq修改iframe的src，避免嵌套，也是不行，好像只要是iframe中触发的都不行，我太难了

第二层iframe同域不发请求这个问题，产生的原因是什么。浏览器限制吗，有没有办法解决啊

**Comment by libaofeng** [comment]
不是同域问题，应该是浏览器缓存问题。给里层的url拼个时间戳就可以了。

**Comment by weixingqi** [comment]
> 

路由是hash模式的，哈希值本身就不同，用history就不会有问题了，哈希加时间戳没意义呀

**Comment by guo-xu** [comment]
> > 
> 
> 路由是hash模式的，哈希值本身就不同，用history就不会有问题了，哈希加时间戳没意义呀

请问解决了么？我也遇到同样问题了

**Comment by zoloadang** [comment]
> > > 
> > 
> > 
> > 路由是hash模式的，哈希值本身就不同，用history就不会有问题了，哈希加时间戳没意义呀
> 
> 请问解决了么？我也遇到同样问题了

可以试试将查询参数提到 hash 井号之前，例如 /?type=abc#/linkUrl
