### ISSUE TITLE
vue使用iframe嵌入另外一个vue页面 不加载body head

### ISSUE THREAD

**Issue by gecaitao** [vuejs/vue#7012]
### Version
2.5.3

### Reproduction link
[https://all](https://all)

### Steps to reproduce
1、父页面写入iframe；src为另外一个vue页面。 或者直接在dom上修改
2、google打开正常，IE9、10、11打开 iframe内容空白不加载

问题描述：
在一个VUE页面中的template标签内增加一个iframe，iframe的src指向了同域下的另一个路由页面。即在"http://localhost.abc.com/#/page"中用iframe载入"http://localhost.abc.com/#/iframePage"时，除IE浏览器为空白，其他浏览器正常

### What is expected?
各个浏览器都正常

### What is actually happening?
除IE浏览器空白外 其他正常

---
是否vue本身就不支持这样实现功能？或者需要安装其他第三方插件来实现？

**Comment by posva** [comment]
By reproduction, we mean an isolated and boiled down example reproducing the problem so we can check it 🙂 
You can use [this fiddle](http://jsfiddle.net/posva/wsr78d2w/) or provide a simple HTML file to create such reproduction

**Comment by gecaitao** [comment]
vue page1:
    <template><iframe src="vue page2"/></template>
<script></srcript>

**Comment by yyx990803** [comment]
<img width="599" alt="screen shot 2017-11-09 at 11 50 10 am" src="https://user-images.githubusercontent.com/499550/32617871-2ca06170-c544-11e7-9f4d-ac983148f53e.png">

**Comment by hyisboy** [comment]
我也出现过这样的问题， 是因为iframe 跨域引起的，你是不是 用了sessionStore.getItem() 之类的api，你可以直接try{...}catch(e){} 查看一下报错的日志， 我是直接在拦截器那里try 发现的错误日志
