### ISSUE TITLE
Watch提供更高级的语法糖

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#7014]
### What problem does this feature solve?
watch里面对于多个属性进行监听，只有给每一个属性都写一个watch

### What does the proposed API look like?
能不能写到一起啊?用逗号分割指向同一个处理函数,逗号呢作为key是肯定不会出现的,刚好拿来作为分隔符
'a,b':{
  handler:function(){
  }
}
https://www.zhihu.com/question/52432905
![v2-9261c17b9a04faf6cfa21eac44e0ff9a_hd](https://user-images.githubusercontent.com/16515026/32477713-ffbb3f70-c3ba-11e7-9a0f-6e63ec65b181.jpg)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can already do that with `$watch` 🙂 
You can check some examples at https://vuejs.org/v2/api/#vm-watch

**Comment by javady** [comment]
Do you want to hire a programmer for you?

**Comment by kitkimwong** [comment]
要不要业务逻辑也帮你写好呀……
