### ISSUE TITLE
Mission type Vue.util in typescript

### ISSUE THREAD

**Issue by Qquanwei** [vuejs/vue#7018]
### Version
2.5.3

### Reproduction link
[https://codesandbox.io/s/94rp09wjrw](https://codesandbox.io/s/94rp09wjrw)

### Steps to reproduce
webpack-dev-server using ts-loader

### What is expected?
No Warnning

### What is actually happening?
util not exists on Vue

**Comment by eshimischi** [comment]
@Qquanwei Vue 2.0 doen't have Util method, it was deprecated from Vue 1..

**Comment by ktsn** [comment]
`Vue.util` is undocumented/internal API. So we won't declare it in d.ts and you should not use it.

**Comment by jgauffin** [comment]
@ktsn  Vue util contains `Vue.util.extend` which is useful outside the internal API.  Maybe move it somewhere else then?

**Comment by TheCelavi** [comment]
+1

**Comment by JounQin** [comment]
You guys can just extend the types in your own projects on your own risk.
