### ISSUE TITLE
SVG Children in Component template not parsed correctly

### ISSUE THREAD

**Issue by j6s** [vuejs/vue#7019]
### Version
2.5.3

### Reproduction link
[https://codepen.io/thephpjo/pen/yPVbMm](https://codepen.io/thephpjo/pen/yPVbMm)

### Steps to reproduce
1. Create a new component
2. Use a `<svg>` element in that component

### What is expected?
The SVG should be rendered the same way it is rendered, if there was no component.

### What is actually happening?
The SVG is not rendered correctly - in the example the size of the circle seems to be disconnected from the viewbox of the svg element.

---
In the codepen, I also managed to reproduce the issue when generating the SVG from Javascript. I assume that this is the same issue, as Vue templates will likely be parsed in a similar fashion.

**Comment by javoski** [comment]
The `viewBox` attribute is case-sensitive, see [https://codepen.io/xujiongbo/pen/VrPZBM](https://codepen.io/xujiongbo/pen/VrPZBM)

**Comment by yyx990803** [comment]
^ what @javoski said
