### ISSUE TITLE
@keyup.meta.enter not work

### ISSUE THREAD

**Issue by yesvods** [vuejs/vue#7029]
### Version
2.5.3

### Reproduction link
[http://jsfiddle.net/yyx990803/yMv7y/](http://jsfiddle.net/yyx990803/yMv7y/)

### Steps to reproduce
用@keydown.meta.enter是可以的，@keyup.meta.enter就触发不到事件了。

### What is expected?
echo todo

### What is actually happening?
nothing happen

**Comment by yyx990803** [comment]
`event.metaKey` 对于 `keyup` 来说不存在，原生事件就是这样的。
