### ISSUE TITLE
Mixin methods are not called before compontent's ones

### ISSUE THREAD

**Issue by MattCz** [vuejs/vue#7032]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/5kx51bo4/](https://jsfiddle.net/5kx51bo4/)

### Steps to reproduce
1. Create a mixin with a method named "example" 
2. Create a component with a method named "example" as well and created() function. Call mixin method inside of that function.
3. Include the mixin in the component

### What is expected?
Mixin method should be called before component's method.

### What is actually happening?
Only component method is being called.

**Comment by yyx990803** [comment]
Unlike hooks, methods are not merged because they can have return values.
