### ISSUE TITLE
v-model with computed

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue#7034]
### Version
2.3.4

### Reproduction link
[https://codepen.io/lasthrun/pen/EbWaEd](https://codepen.io/lasthrun/pen/EbWaEd)

### Steps to reproduce
I am trying to change a input value with a prop data. but my question is, if we using a computed property in v-model. when i input 'something' into the <input>, i wanna get that 'something' from the @change event. but i always get the same thing. because it does not change the computed property listening data.
but if we don't use that. i need to set watch and mounted to make the value update with prop data. is there any   good solution?

### What is expected?
@change should give the data that i input

### What is actually happening?
@change always give the default data

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Using a computed setter allows you to emit an event or do anything you want 😉  https://vuejs.org/v2/guide/computed.html#Computed-Setter
