### ISSUE TITLE
Vue dynamic component transition issue

### ISSUE THREAD

**Issue by connected** [vuejs/vue#7036]
### Version
2.5.3

### Reproduction link
[https://codepen.io/madhamster/pen/POpZEZ](https://codepen.io/madhamster/pen/POpZEZ)

### Steps to reproduce
Click show modal button

### What is expected?
When page is loaded for the first time and we hit "show modal" button, overlay component should fade in with transition.

### What is actually happening?
Overlay component enters without transition. 
If you hit hide modal or show modal after the initial appearance, transition works fine.

---
This can be fixed by changing "modalVisible" state prop. inside setTimeout(..., 0), but it is an obvious hack.

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render
