### ISSUE TITLE
How do I get Vue directives to work in an inserted HTML code piece?

### ISSUE THREAD

**Issue by afuno** [vuejs/vue#7037]
### What problem does this feature solve?
There is a .vue file. It has a function described in methods. This function is called from mounted.

This function prepares HTML code and inserts it into the main template of the .vue file.

```javascript
let element = document.getElementById('js-container')
element.innerHTML = '<div><!-- HTML code with components and Vue directives --></div>'
Vue.compile(element.innerHTML)
```

The problem is that now all Vue directives or components in the inserted piece of code do not work. They look in the source code of the browser as usual tags and attributes of HTML code. Vue compilation does not work.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Inside of the directive function, you get access to the element as the first argument
