### ISSUE TITLE
Would it be more efficient to use requestAnimationFrame first in nextTick

### ISSUE THREAD

**Issue by teazean** [vuejs/vue#7038]
### What problem does this feature solve?
it could be a copy of [2708](https://github.com/vuejs/vue/issues/2708), but i think issue-2708 is for vue1 which has no vdom.

i read an artile recently which relates to rIC & rAF & vdom [links](https://developers.google.com/web/updates/2015/08/using-requestidlecallback#using_requestidlecallback_to_make_dom_changes). let's leave rIC firstly and i think it would be a great efficiency improvement only if comparing vnodes、updating dom in rAF phase and updating state in other phases.

### What does the proposed API look like?
i just want to discuss this issue...

**Comment by yyx990803** [comment]
Please use the forum for open ended discussions. The short answer is: no, we have investigated this and rIC or rAF are not what we want, because nextTick exists primarily for scheduling rather than deferring work. What we want is microtasks as much as possible.

**Comment by teazean** [comment]
Thanks for your answer.
