### ISSUE TITLE
Method for filtering array of objects throws warning

### ISSUE THREAD

**Issue by marcomansilla** [vuejs/vue#7040]
### Version
2.4.2

### Reproduction link
[https://codepen.io/mmansilla/pen/KyWZKM](https://codepen.io/mmansilla/pen/KyWZKM)

### Steps to reproduce
As you can see in the code example, everything seems to be OK, but when I run  the exact same code on my local machine get a warning.

### What is expected?
As you can see, the function getClan() returns a single element and it gets rendered in the clan column of the table, but when it reaches the end of the array Vue returns a warning.

### What is actually happening?
the filter function inside getClan() seems to try to loop over the last element of the array and get
    
     [Vue warn]: Error in render function: "TypeError: this.clans.filter(...)[0] is undefined"

---
I have also tried in the view

    <td>{{ clans.filter(character.clan)[0].name }}</td>

even I know this shouldn't be done in the view, but did just for testing and has same result, it works but when reaches the las element of the array throws a warning.

**Comment by yyx990803** [comment]
Sorry but we can't help you if the error only happens on your machine... please try to provide a production that we can actually look into.

**Comment by marcomansilla** [comment]
Hi Evan, thank you for your quick answer. I should try another service that doesn't encapsulate the console output as codepen seems to do, but if you copy and paste the code to run it locally it stills happens.
