### ISSUE TITLE
Mixin data merge problem

### ISSUE THREAD

**Issue by ReevesSher** [vuejs/vue#7043]
### Version
2.5.3

### Reproduction link
[https://github.com/vuejs/vue/blob/2acc12c9edb03329c4d9cddcca26e46c672a77bc/dist/vue.common.js#L1106](https://github.com/vuejs/vue/blob/2acc12c9edb03329c4d9cddcca26e46c672a77bc/dist/vue.common.js#L1106)

### Steps to reproduce
1、create a mixin with data option
2、Vue.use this mixin

### What is expected?
nothing wrong

### What is actually happening?
cannot read property from undefind

---
I guess this happens when mixin data option do the merging, and if the params 'to' of the mergeData function is undefined and then to[from] throw out error 'cannot read property of undefined'

**Comment by ReevesSher** [comment]
![mixin](https://user-images.githubusercontent.com/18300790/32689150-f1bb2a04-c719-11e7-9938-d9f0392c1f4b.png)
i dunno know if it`s necessary to check the params 'to' is defined or not

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal [JSFiddle](http://jsfiddle.net/posva/wsr78d2w/) and a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by yyx990803** [comment]
Sorry, but link to source code is not a valid repro.

**Comment by tristanp2** [comment]
I realize this is pretty old, but I thought I'd mention that I was having the exact same issue after I added a typescript vue package (vue-golden-layout) to my js based project. Another dev had added a small mixin in main.js using Vue.mixin. For some reason, this was causing this error when Vue tried to mount any golden layout components. Once I removed that mixin, I had no further issues.

**Comment by l-portet** [comment]
Just had this old issue, I realized it was caused by my component which didn't return any object in the data function
