### ISSUE TITLE
Importing as ES6 module without build step

### ISSUE THREAD

**Issue by mleg** [vuejs/vue#7044]
### What problem does this feature solve?
As ES6 module support is finally shipped in Chrome without flags, many of us may consider getting rid of a build step in development stage.  
And Vue.js is almost there being shipped with `vue.esm.js` bundle among other options. But unfortunately this module doesn't work out of the box when we `import` it and try to use avoiding webpack build step. Just only because `process.env.NODE_ENV` present.
If I try to manually add something like this
```javascript
const process = {
  env: {
      NODE_ENV: "development"
  }
};
```
at the top of the module, it seems like everything works as expected.

### What does the proposed API look like?
As such setup is only relevant in development, maybe consider adding one more bundle like `vue.esm.dev.js`?

**Comment by yyx990803** [comment]
We've got this request before - the short answer is not for now.

- Shipping pure ESM directly to production is still a no-go for the foreseeable future, and it also lack support for the recommended toolchains. This means the build would only be useful for prototyping.
- However for prototyping, you can just include Vue via `<script src>` and it doesn't make much difference and is not worth the complexity in adding yet another dist format.
