### ISSUE TITLE
Document does not explain several parameters about $watch

### ISSUE THREAD

**Issue by kitkimwong** [vuejs/vue#7047]
### What problem does this feature solve?
https://vuejs.org/v2/api/#vm-watch

About $watch, the document just mention the options about deep and immediate.

But after review the source code, there are four options about ```$watch``` :

1. deep
2. user
3. lazy
4. sync

```
  // options
  if (options) {
    this.deep = !!options.deep;
    this.user = !!options.user;
    this.lazy = !!options.lazy;
    this.sync = !!options.sync;
  } else {
    this.deep = this.user = this.lazy = this.sync = false;
  }
```

### What does the proposed API look like?
Document must talk more about ```sync``` and ```user```

**Comment by yyx990803** [comment]
Some options are intentionally omitted because they are not part of the public API.
