### ISSUE TITLE
v-model 能否支持object 传入

### ISSUE THREAD

**Issue by Fangty1** [vuejs/vue#7049]
### What problem does this feature solve?
试想如下业务场景：

一个管理系统中，管理很多数据对象。 系统为各种数据对象定义了了展示'卡片'，即一个vue组件。不同的业务场景都可以调用这个组件，来显示一个，比如 员工信息。 不同的业务场景通过传入不同的'员工信息'，可以看到同样的显示风格。

也就是说，需要在父组件获取'员工信息'，并传递给子组件。

vue v-model 不支持object传入。 自定义组件功能受局限。

Best wishes

### What does the proposed API look like?
无变化

**Comment by CJ921008** [comment]
父子 组件传递数据 文档里不是很详细吗

**Comment by javoski** [comment]
你需要的应该是 [props](https://cn.vuejs.org/v2/guide/components.html#Prop), 还有自定义组件的 `v-model` 是支持 object 的。

**Comment by Fangty1** [comment]
是我的代码有问题。
我代码中把 value对象定义到了 export default 的 data () 中。 导致父组件的object没有传到子组件。
将value 对象放到 export default 的 props 中，就可以了。

但是有个问题有点奇怪：

父对象通过 v-model 传递对象到子对象， 如果子对象没有定义 props { value :{} }， vue会报错，这个容易理解。 但是如果子组件的value对象定义到了 data() 中， vue不会报错，但是无法从父对象传递object， 话说这个是不是应该报个错更合适些呢？

谢谢！
