### ISSUE TITLE
Parent's v-on is working, but this.$on isn't, for the same child's event triggered

### ISSUE THREAD

**Issue by shine-on** [vuejs/vue#7051]
### Version
2.5.3

### Reproduction link
[https://codepen.io/anon/pen/NwgWbL](https://codepen.io/anon/pen/NwgWbL)

### Steps to reproduce
Please run codepen provided and observe console output 

### What is expected?
buzzNoted should be invoked TWICE per run: first for v-on: directive, second for manually installed this.$on listener.

### What is actually happening?
buzzNoted invoked only ONCE per run (for v-on: directive). this.$on listener doesn't work.

**Comment by yyx990803** [comment]
Listeners attached via `v-on` are added to the **child instance**, not the parent. There is no propagation, the event is emitted on the child and captured on the child. So the `$on` should be on the child instead of the parent.

For the child and parent to communicate purely in JavaScript you need an explicit event bus imported by both.

**Comment by shine-on** [comment]
Thanks for explanation. However, your statement above

"Listeners attached via v-on are added to the child instance, not the parent"

is clearly a missing piece of the statement from documentation at https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events

"In addition, a parent component can listen to the events emitted from a child component using v-on directly in the template where the child component is used"

While now I see a warning note down below, explaining the fact why $on can't be used, I think documentation can be improved: "listeners added to child, there's no propagation" is self explaining, "parent can listen to child" doesn't exclude propagation (and if so, why $on can't be used).

**Comment by yyx990803** [comment]
Feel free to propose a PR at the docs repo.
