### ISSUE TITLE
vue-template-compiler 支持 deindent 开关

### ISSUE THREAD

**Issue by kyriosli** [vuejs/vue#7054]
### What problem does this feature solve?
在`parseComponent`中，会对`script`进行`de-indent`，导致生成`sourceMap`时无法根据`script`的`sourceMap`计算`vue`文件中的位置。或许我们应该支持可选的`de-indent`或在block中输出具体去掉了多少的空白？

### What does the proposed API look like?
vue_template_compiler.parseComponent(vue, {deindent: false})

**Comment by cc-man** [comment]
你的头像好六

**Comment by yyx990803** [comment]
Closed via #7215
