### ISSUE TITLE
data.on & listeners in functional components are not consistent

### ISSUE THREAD

**Issue by wxsms** [vuejs/vue#7055]
### Version
2.5.3

### Reproduction link
[https://codepen.io/wxsm/pen/RjgYPy](https://codepen.io/wxsm/pen/RjgYPy)

### Steps to reproduce
Just check out the codepen.

### What is expected?
As the doc said: `listeners`: (2.3.0 ) An object containing parent-registered event listeners. This is an alias to `data.on`.

Then they should be accurately the same thing.

### What is actually happening?
They are not the same in this case.

**Comment by fnlctrl** [comment]
Hi, thanks for filling the issue.

The only difference between `listeners` and `data.on` is that `listeners` is an empty object `{}` when `data.on` is undefined.

The reason `listeners` is added is that in practice `data.on` could often be `undefined`, making it very verbose to access,  e.g.
```js
// before 2.3, you'll need to write checks for `data.on` everywhere
if (data.on && data.on.foo) {
  // do something
}
```
so we now use the `listeners` shorthand to simplify the above to
```
// after 2.3
if (listeners.foo) {
 // do something
}
```

**Comment by wxsms** [comment]
Interesting. 

Then you should not use the word **alias**, which means exactly the same, but have what you said pointed out in the doc.

Because, when people use `listeners` in before and found that it only supported by 2.3+, going to make it compatible with 2.0+, they will get confuse with the errors and the doc. (yes that's me)
