### ISSUE TITLE
关于 v-if v-show 的不足

### ISSUE THREAD

**Issue by wcldyx** [vuejs/vue#7062]
### What problem does this feature solve?
我一个tab页，里面有很多个选项卡，每个选项卡有ajax请求，那么问题来了
如果用 v-show，就会在页面一打开产生很多ajax请求，会有些卡顿
如果用 v-if，就会在用户每次切换ajax会重新请求一遍，然后之前的浏览记录也没了

### What does the proposed API look like?
希望提供一个类似 v-show 或 v-if 的指令
在没有“显示过”时不渲染组件
在“显示过后” 再次切换“显示或隐藏”不重复安装组件

**Comment by yyx990803** [comment]
<keep-alive>
