### ISSUE TITLE
Can't use multiple mustaches on different paragraphs in a template 

### ISSUE THREAD

**Issue by FabioBuono** [vuejs/vue#7065]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/fabiobuono/qn0pfmd1/](https://jsfiddle.net/fabiobuono/qn0pfmd1/)

### Steps to reproduce
just run, the code is very short and straightforward, no input is required.

 

### What is expected?
all the code in every <p> tag are be showed

### What is actually happening?
The template doesn't work with multiple <p> tags.

**Comment by EmilyRosina** [comment]
As far as I am aware vue only allows 1 element (essentially a wrapper within template's). This is not an error, nor a bug - it is just how it works.

**Comment by FabioBuono** [comment]
Thank you for you mail.Best regards from Italy   :) Fabio Buono Il 16 nov 2017 1:00 AM, EmilyRosina <notifications@github.com> ha scritto:As far as I am aware vue only allows 1 element (essentially a wrapper within template's). This is not an error, nor a bug - it is just how it works.

**Comment by yyx990803** [comment]
If you open your console, there is a warning telling you about the problem. Make sure to check warnings before opening issues.
