### ISSUE TITLE
scoped attribute make to modify css difficulty or unreasonable

### ISSUE THREAD

**Issue by 2ue** [vuejs/vue#7067]
### Version
2.5.3

### Reproduction link
[https://codesandbox.io/s/ql3nvkv489](https://codesandbox.io/s/ql3nvkv489)

### Steps to reproduce
A.vue and B.vue, they all set a scoped arrtibute for style tag,
then A import B and I want to modify B's style in A，
but I found it not work

### What is expected?
I hope can modify the style of B in A, even if A and B have scoped attribute.
maybe it what adds a attribute-selector in the start of every css selector sentence can solve this problem

### What is actually happening?
vue add a attribute-selector in the end of every css selector sentence, so it not work

**Comment by yyx990803** [comment]
That's how it's designed to be: scoped CSS means the CSS is scoped to the current component only, not its parent, not its children.

**Comment by xue163** [comment]
Regarding the bug of scoped, when I introduce js from the outside to manipulate elements to add corresponding sub-elements to elements, at this time, the newly added sub-elements are not in the design style, but the scoped is removed, which can be used normally.

**Comment by Justineo** [comment]
You shouldn’t manipulate elements manually in this case. You should only do this to encapsulate really low-level DOM operations, like in directives.

**Comment by 2943785277** [comment]
If you change the B style string in A, scoped is limited to the current component, which I personally think is good。
