### ISSUE TITLE
Show warning if emitting event with invalid name

### ISSUE THREAD

**Issue by j6s** [vuejs/vue#7071]
### What problem does this feature solve?
Recently I tried to namespace events (poorly admittedly) by using dots to emit events `gallery.share` and `gallery.success`. Of course these event names are invalid, as they cannot be used in event listeners, since dots are used to indicate modifiers.

It would be nice, if the `$emit` Method would print a warning to the console when using invalid event names.

### What does the proposed API look like?
(There are no API Changes needed)

**Comment by yyx990803** [comment]
Technically they are not invalid though, because you can listen to them in JavaScript with `$on('gallery.share')`. But I suppose we can add a note in the docs.
