### ISSUE TITLE
如何实现一个类似于v-if的指令（angularjs中的结构型指令）

### ISSUE THREAD

**Issue by jaune162** [vuejs/vue#7073]
### What problem does this feature solve?
貌似Vue当前不支持这样的指令，如果通过display或者visibility来控制，显然是达不到要求的。
v-if的实现是把元素替换成了注释，文档中并没有说明如何实现这一点。

### What does the proposed API look like?
Vue.directive

**Comment by yyx990803** [comment]
Vue 2 不支持自定义结构指令。，自定义指令在 Vue 2 仅用于对单个元素的直接 DOM 操作。结构性的操作抽象通常通过组件进行。
