### ISSUE TITLE
Vue 2.5的新特性errorCaptured不能捕获到异步错误，例如发送一个ajax请求，在ajax内抛出一个Error,

### ISSUE THREAD

**Issue by h330894169** [vuejs/vue#7074]
### Version
2.5.2

### Reproduction link
[https://vuejs.org/v2/examples/](https://vuejs.org/v2/examples/)

### Steps to reproduce
在created回调方法里面写一个setTimeout 模拟，抛出error，errorCaptured无法捕捉，如果是同步throw new Error()  就能捕获

### What is expected?
errorCaptured能捕获异步promise内部抛出的错误，

### What is actually happening?
不能捕获error

**Comment by yyx990803** [comment]
文档明确写了异步错误无法捕捉，要你自己处理。这是 js 的语言机制决定的。
