### ISSUE TITLE
Property or method "_staticTrees" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue#7075]
### Version
2.5.4

### Reproduction link
[https://github.com/yoyo837/vue-2.5.4-bug-report](https://github.com/yoyo837/vue-2.5.4-bug-report)

### Steps to reproduce
When I delete the following code, it works fine, but in 2.5.3 it does not have this problem.

https://github.com/yoyo837/vue-2.5.4-bug-report-pages/blob/cf8565a94b00d9a469026c6c1a15609a72f4c81d/order/_id.vue#L6
```html
    <div class="clip-section">
      <div class="clip-gap clip-gap-left"></div>
      <div class="clip-line"></div>
      <div class="clip-line"></div>
      <div class="clip-gap clip-gap-right"></div>
    </div>
```

### What is expected?
No report error

### What is actually happening?
It report:
[Vue warn]: Property or method "_staticTrees" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

**Comment by kuoruan** [comment]
+1 我今天也遇到了，刚升级的 2.5.4

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a **minimal** JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by yoyo837** [comment]
OK, I'll prepare one and provide later.
