### ISSUE TITLE
vue 结合 bootstrap-table  使用了jquery  不能像angular那样使用scope.apply 告知jquery dom发生了变化  从而试jquery可以重新渲染dom

### ISSUE THREAD

**Issue by Blackloser** [vuejs/vue#7077]
### What problem does this feature solve?
解决了使用jquery时  不能动态的更新dom的问题

代码

'$store.state.socket.priceArray': function (val) {
        val.forEach((item, index) => {
          this.$set(this.data, index, item)
        }) 
        $('.table').bootstrapTable({
          columns: this.columns,
          data: this.data
        });
      }

![image](https://user-images.githubusercontent.com/26319882/32937910-4e5a9b7e-cbb5-11e7-8b33-8922d9dd7392.png)

### What does the proposed API look like?
期望能加一个想angular那样的scope.apply

**Comment by Blackloser** [comment]
This problem has been solved in bootstring-table but still wants to provide jquery refreshing dom

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Blackloser** [comment]
But this is a requirement problem and vue doesn't have a way to refresh the dom for jquery @posva

**Comment by posva** [comment]
The problem is not related directly to Vue but rather to how to integrate third party libraries with Vue. There're a lot of resources on how to integrate jquery with vue. And in any case, it's a usage question, so please, use the proper channels (forum or chat) for it) 🙂
