### ISSUE TITLE
current component cannot use other component's  css

### ISSUE THREAD

**Issue by aeolusheath** [vuejs/vue#7079]
### Version
2.5.2

### Reproduction link
[https://github.com/aeolusheath/vue-router-project](https://github.com/aeolusheath/vue-router-project)

### Steps to reproduce
I declare css in Test.vue 

```
<style lang="scss">
.kevin {
  .k a {
    color: red;
  }
}
</style>
```

and no `scoped`。

and I use the style in App.vue 

```
     <div class="k">
        <a> kkk</a>
      </div>
```
 when I go to index Page(the page didn't load Test.vue). the text ` kkk` color is black, not red. 

 

### What is expected?
expected broswer will load all component's css in style tag.  

### What is actually happening?
sorry actually I don't know if this is a problem.

/admins   it go to a page contains component 'Admin.vue'   and does not contain component 'User.vue'

how to let Admin.vue can get the css in User.vue (in style tag).

recently I just update web app. before this upgrading.  Broswer will always load css in style tag of all components although some component is not loaded in current page.

sry I m not clear if this is the problem is about vue, may be webpack.

and it's the normal action?

project is created by vue-cli

**Comment by yyx990803** [comment]
You should not rely on cross component styles unless you know they are going to be rendered together.
