### ISSUE TITLE
binding with a not exist method should be an error, not warn.

### ISSUE THREAD

**Issue by miaulightouch** [vuejs/vue#7083]
### Version
2.5.5

### Reproduction link
[https://jsbin.com/fihinimuxe/1/edit?html,js,console,output](https://jsbin.com/fihinimuxe/1/edit?html,js,console,output)

### Steps to reproduce
element binding with a not exist method

### What is expected?
show `[vue error]`

### What is actually happening?
show `[vue warn]`

---
warn means it can be ignored, but actually it break vue and affect other dom.

**Comment by yyx990803** [comment]
No warnings can be ignored. Every warning should be fixed.
