### ISSUE TITLE
After calling $destroy (), @ click binding events still exist

### ISSUE THREAD

**Issue by git8023** [vuejs/vue#7086]
### Version
2.5.1

### Reproduction link
[https://gitee.com/osby/learn-js/blob/master/vue/example/9/vue.live.html](https://gitee.com/osby/learn-js/blob/master/vue/example/9/vue.live.html)
http://jsfiddle.net/0bxfga8q/

### Steps to reproduce
```html
<div id="app">
    <p>{{result}}</p>
    <p>
        <button @click="change">Change</button>
        <button @click="destroy">Destroy</button>
    </p>
</div>
```
```javascript
    var app = new Vue({
        el: "#app",
        data: {
            message: "Hello World",
            result: ""
        },
        methods: {
            change: function () {
                this.result = this.message   " - "   new Date().toLocaleString();
                throw "123";
            },
            destroy: function () {
                this.$destroy();
            }
        });
```

Click button:Destroy, and click button:Change.

### What is expected?
Hope in the calling $destroy(), remove the DOM event object. To prevent invalid Ajax requests. 
thanks very much.

### What is actually happening?
The console output information: Uncaught 123

---
Asynchronous validation event in the form.

**Comment by posva** [comment]
I provided an editable repro
For the moment, `$destroy` get rids of event listeners setup on the component only.
But, it looks like there're still some references to the events because if the element is removed, the event listeners are not freed
I do agree, event listeners on native elements should be removed when the instance is destroyed

**Comment by yyx990803** [comment]
This is intended behavior. When a vm is destroyed, its associated piece of DOM is considered discarded. When managed by Vue itself, the DOM will be detached and garbage collected, and all modern browsers correctly discards event listeners in the process as well.

It is usually not recommended to call `$destroy()` imperatively, and once you call that, the DOM that's left behind should not be reused. Calling `$destroy(true)` removes the DOM at the same time.

**Comment by amorphius** [comment]
I've tried `$destroy(true)` but DOM stays the same

**Comment by abhimatta** [comment]
> I've tried `$destroy(true)` but DOM stays the same

Have you got any idea now how to remove/destroy it from DOM as well?
