### ISSUE TITLE
vue-cli2.9.2 ie9-ie10 in dev cannot see page

### ISSUE THREAD

**Issue by huoyuhengCat** [vuejs/vue#7091]
### What problem does this feature solve?
but after build ie9-10 can see page,i just want to test page in dev!

### What does the proposed API look like?
no

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
