### ISSUE TITLE
Global component will cover local components & Only the first successful local component

### ISSUE THREAD

**Issue by git8023** [vuejs/vue#7092]
### Version
2.5.7

### Reproduction link
[https://gitee.com/osby/learn-js/blob/master/vue/example/11/vue.component.html](https://gitee.com/osby/learn-js/blob/master/vue/example/11/vue.component.html)

### Steps to reproduce
```html
<div id="app">
    <div>Global component</div>
    <global-com/>
    <div>Local components</div>
    <local-com1/>
    <local-com2/>
</div>
```
```javascript
Vue.component("global-com", {
    template: "<p style='color:#F00;'>global</p>"
});
var app = new Vue({
    el: "#app",
    components: {
        "local-com1": {
            template: "<p style='color:#F00;'>local-1</p>"
        },
        "local-com2": {
            template: "<p style='color:#0FF;'>local-2</p>"
        }
    }
});
```
You just need to run the page.

===================

### What is expected?
Global components should be as a backup, Local components not covered, refer to the definition of a global component.

### What is actually happening?
Only <global-com/> a work, If exchange definition (global & local) after the order, only the first local components effectively.

---

```javascript
// vue.js
function mergeOptions (
  parent,
  child,
  vm
) {
  ...
  // line number: 1449
  for (key in child) {
    // ====================================
    // ==  This is just my suggestion
    // ====================================
    var 
      val = parent[key],
      objType = val && (val instanceof Object)  && !(val instanceof Function );
    if (objType) {
      var parentVal = val;
      depthClone(child, key, parentVal);
      continue;
    }
    // ====================================
    
    // Shallow cloning is a bit too arbitrary?
    // Or is there any other meaning here?
    if (!hasOwn(parent, key)) {
      mergeField(key);
    }
  }
  ...
}
```

**Comment by posva** [comment]
That's already the case: local components take precedence over global ones.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
