### ISSUE TITLE
window.print(); after content changed

### ISSUE THREAD

**Issue by youyi1314** [vuejs/vue#7094]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/50wL7mdz/77812/](https://jsfiddle.net/50wL7mdz/77812/)

### Steps to reproduce
Click the print link

### What is expected?
i want to print "Print Me"

### What is actually happening?
it will need to click second time only it change the content

**Comment by anhulife** [comment]
change data don't update DOM immediately, you need execute `window.print` like this:

```javascript
printNow(value){
  this.print = value;
      
  this.$nextTick(() => {
    window.print();
  });
}
```

**Comment by posva** [comment]
What @anhulife said 🙂

**Comment by Frank-Dell** [comment]
> change data don't update DOM immediately, you need execute `window.print` like this:
> 
> ```js
> printNow(value){
>   this.print = value;
>       
>   this.$nextTick(() => {
>     window.print();
>   });
> }
> ```

It works!!!!!!!!
