### ISSUE TITLE
Backers page do not load properly

### ISSUE THREAD

**Issue by k30v1n** [vuejs/vue#7099]
### Version
2.5.8

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/BACKERS.md](https://github.com/vuejs/vue/blob/dev/BACKERS.md)

### Steps to reproduce
Open the page

### What is expected?
See the backers images

### What is actually happening?
It is not possible to see the images

---
This is happening on the repository on github. 

https://github.com/vuejs/vue/blob/dev/BACKERS.md

**Comment by denjaland** [comment]
Works for me!

**Comment by k30v1n** [comment]
For me is showing in that way

![image](https://user-images.githubusercontent.com/10376375/33091401-26a38862-cede-11e7-91ab-fc01aa3e5230.png)
![image](https://user-images.githubusercontent.com/10376375/33091450-53abd8c8-cede-11e7-85b9-45d7b285f2e6.png)

Some images are not loading.
I opened on Chrome and there the image dont show as well but dont crash. 
Those prints were taken with Firefox.

**Comment by posva** [comment]
I think they just don't have a logo, look at https://opencollective.com/vuejs
It would be nice if they displayed the default icon but it's not something we can fix on our end 😞

**Comment by k30v1n** [comment]
Oh, get it. Thans for taking time to investigate this :)
