### ISSUE TITLE
vue路由切换：从A页面切到B页面时，怎么把A页面的js都卸载掉，不要再执行A页面未执行完的js代码呢？

### ISSUE THREAD

**Issue by lemontizz** [vuejs/vue#7114]
### What problem does this feature solve?
vue路由切换：从A页面切到B页面时，怎么把A页面的js都卸载掉，不要再执行A页面未执行完的js代码呢？

### What does the proposed API look like?
在router配置的地方,添加一个字段判断是否需要卸载

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
