### ISSUE TITLE
版本更新以后运行npm run dev后内网机器无法访问

### ISSUE THREAD

**Issue by wizhwai** [vuejs/vue#7117]
### Version
2.5.8

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Steps to reproduce
  旧版本(2.5.2)时候用webpack建立的项目运行npm run dev 内网可以正常访问.(http://localhost:8080正常,但是内网其他机器http://192.168.x.x:8080访问也正常)

  但是升级最新版以后用webpack新创建的项目都无法用内网ip访问(http://localhost:8080正常,但是内网其他机器http://192.168.x.x:8080访问不了)

### What is expected?
新项目能通过内网机器访问调试

### What is actually happening?
旧项目可以正常内网调试,但是新项目无法内网访问

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
