### ISSUE TITLE
v-if="statusPId==12 && statusId==111" 不能正常解析,出现500错误

### ISSUE THREAD

**Issue by chengwei426** [vuejs/vue#7119]
![image](https://user-images.githubusercontent.com/33225699/33174683-ff7fae70-d093-11e7-99d4-ab93dc72dcc6.png)
我通过props向子组件传递了statusPId和statusId,这两个字段用来判断表单的某个输入框在某种条件下是否显示,但是v-if中使用&&进行组合出现500错误, 但是我删除&&和其中任何一个条件都会显示,同时我将&&换成'||'却也能正常解析,这是为什么?实在找不出解决办法!!! ((statusPId和statusId两个字段是我的树结构的id和父id,通过单击来传递某个表单输入框是否显示,,并且我没使用webpack)

**Comment by kindy** [comment]
@chengwei426 
please create a computed prop and use in `v-if`.
this is not vue issue, it's your web severs' logic.
