### ISSUE TITLE
Slot-scope bind in child; bind back in parrent, the object doesnt have intance method

### ISSUE THREAD

**Issue by Danchev1** [vuejs/vue#7122]
Im haveing a wrapper component where i bind a list from a vuex getter

`<grid-review-component v-bind:reviewResults="customerReviewResults">
        <grid-cell-component
         slot="cell"
         slot-scope="result" v-bind:label="result.getValue()"  v-bind:value="result.getValue">
        </grid-cell-component>
      </grid-review-component>`
 

And in my grid-review-component i for loop and bind result

`<div class="columns">
     <div class="column" v-for="result in reviewResults" :key="result.id">
       <slot name="cell" v-bind="result"></slot>
     </div>
    </div>`
    
The slot-scope binding works but getLabel() and getValue() are undefined; They are instance methods of a class; 
Not sure the reason for this, if i bind normaly(paren to child intance gives me the correct values) but not this way. In this example err is they are not a function. What am i missing?

**Comment by kindy** [comment]
@Danchev1 try this:

```
<grid-review-component v-bind:reviewResults="customerReviewResults"> <grid-cell-component slot="cell" slot-scope="data" v-bind:label="data.result.getValue()" v-bind:value="data.result.getValue"> </grid-cell-component> </grid-review-component>
```

```
<div class="columns"> <div class="column" v-for="result in reviewResults" :key="result.id"> <slot name="cell" :result="result"></slot> </div> </div>
```

**Comment by Danchev1** [comment]
Thanks for the reply, tried that but ot didnt work. I found the reason thow, when binding to slot in the component result gets copied.
