### ISSUE TITLE
当组件使用v-if控制显示利用bus进行赋值将赋值失效

### ISSUE THREAD

**Issue by uliian** [vuejs/vue#7123]
### Version
2.5.8

### Reproduction link
[https://jsfiddle.net/50wL7mdz/78588/](https://jsfiddle.net/50wL7mdz/78588/)

### Steps to reproduce
如果同时使用v-if和bus配合，则bus的赋值无效

### What is expected?
能够正常赋值

### What is actually happening?
没有正常赋值

**Comment by HerringtonDarkholme** [comment]
`mounted` is executed after `notify`, so event is emitted before listening. 

You can use `keep-alive` to preserve the component. https://jsfiddle.net/xxto0pu5/

Or you can use `nextTick` to emit event after `mount`.  https://jsfiddle.net/ybs7mvg8/

Please consider using forum / vueland / stackoverflow for questions.
