### ISSUE TITLE
vue-router in transition-group crashes on quick page changes

### ISSUE THREAD

**Issue by FyiurAmron** [vuejs/vue#7125]
### Version
2.5.8

### Steps to reproduce
Have a proper `<transition-group>` containing properly keyed `<router-view>` . Add any transition effect. Change the route quickly a couple of times.

### What is expected?
Router transitions properly.

### What is actually happening?
Vue crashes with `[Vue warn]: Error in render: "TypeError: c$1.elm.getBoundingClientRect is not a function"` and further errors.

---
crash dump at https://gist.github.com/FyiurAmron/80abc0f47237df649d6a1080b715e1d9 . Note that changing `<transition-group>` to `<transition>` fixes this behaviour. By inspecting internal Vue code, is seems it tries to process a `<!-- -->` element that is present in the group when the router is not rendered, and fails, because the empty comment element hasn't got the required methods or properties (getBoundingClientRect, getAttribute, style.display, getComputedStyle etc.) enabled.

Note: I wasn't able to consistently reproduce this outside of my current application, and I'm bound by legal contract not to share it nor it parts. Still, I think the case description is clear enough; don't hesitate to ask me for any additional details if they are needed, though.

**Comment by yyx990803** [comment]
Missing reproduction.
