### ISSUE TITLE
About w3c validation

### ISSUE THREAD

**Issue by dmitry-lavrik** [vuejs/vue#7129]
### What problem does this feature solve?
Hi!

Many people asked about the W3C validation - https://validator.w3.org/

Vue.js directives is invalid for W3C. So, i created very small library for valid data-attributes:

https://github.com/dmitry-lavrik/vue-w3c-valid
https://www.npmjs.com/package/vue-w3c-valid

I wanted to give a link in the previous discussion, but it's closed.

It works before Vue.js and replace tag names ans attributes.

As sample https://jsfiddle.net/oe6ezzh2/

Maybe someone has thoughts on how to integrate this into "Vue.js" at the level of the "beforeCreate" hook?

### What does the proposed API look like?
new VueW3CValid({
	el: '.directivesValid'
});

and than new Vue({
     el: '.directivesValid'
    ....
});

**Comment by posva** [comment]
Your eventual markup is w3c compliant. Keep in mind, most SPA applications do not have any HTML template in production, so they pass the validator test.
You can see more info at #2415 and #273

Closing because this is a question

**Comment by devovercome** [comment]
@posva Hi! You are talking about SPA, but I found Vue.js as the best rapid client-side behavior programming for classic round-trip environment in ASP.NET. 

To be more specific - I render partial view (on server side), which has vue directives inside. This is incredible fast and easy way and also (AFAIK) the **only** framework which suites for that just perfect. 

So its really sad that Vue.config removed, and so happy that Dmitri provided solution which really helped me out.

**Comment by andreymal** [comment]
vuejs.org is also not valid

![](https://i.imgur.com/vY0GJeW.png)

**Comment by yyx990803** [comment]
"Valid" as in **can be properly parsed by all major browsers". W3C validation is pretty much pointless.
