### ISSUE TITLE
v-show导致数据刷新后部分数据不显示

### ISSUE THREAD

**Issue by no-simple** [vuejs/vue#7133]
### Version
2.5.8

### Reproduction link
[https://new-issue.vuejs.org/](https://new-issue.vuejs.org/)

### Steps to reproduce
使用v-show切换table状态的编辑与显示状态。在table数据刷新以后，使用v-show的某列数据或部分数据会不显示出来。使用v-if则没有这种问题

### What is expected?
什么原因导致的？

### What is actually happening?
刷新table数据后发现数据部分丢失

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
