### ISSUE TITLE
CSS Transitions & Animations - Some examples from the doc seem broken

### ISSUE THREAD

**Issue by katydatt** [vuejs/vue#7134]
### Version
2.5.8

### Reproduction link
[https://vuejs.org/v2/guide/transitions.html#CSS-Transitions](https://vuejs.org/v2/guide/transitions.html#CSS-Transitions)

### Steps to reproduce
After facing some issue with CSS transitions and animations using `<transition>` on Vue 2.5.8, I've noticed that some css transition properties were not applied correctly and the same issues are present on some examples of the official Vue.js documentation.

In the example below, we can see that the css animation properties are not applied during the transitions:

https://vuejs.org/v2/guide/transitions.html#CSS-Transitions
=> translateX and opacity animations are not applied.

https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components
=> opacity animation are not applied.

### What is expected?
A transition on the animation should have been applied to the elements as per described (opacity or translateX).

### What is actually happening?
There is no transition on the animation been applied.

**Comment by posva** [comment]
Hi, it works perfectly fine for me, we need more details like your web browser

**Comment by katydatt** [comment]
Hi, thanks for your reply. However, after some investigation with my company IT, the problem seemed related to an issue with my machine CPU. My apologies for this. Closing the issue now.
