### ISSUE TITLE
Click handler from invisible element didn't get cleared

### ISSUE THREAD

**Issue by denego** [vuejs/vue#7137]
### Version
2.5.8

### Reproduction link
[https://jsfiddle.net/denego/ragxepy0/1/](https://jsfiddle.net/denego/ragxepy0/1/)

### Steps to reproduce
Button0 click handler shows new '0' character.
Button1 click handler shows new '1' character.

1. Click Button0: new '0' appeared. OK
2. Click Toggle to hide Button0 and show Button1. OK
3. Click Button1: new '1' appeared. OK
4. Click Toggle to hide Button1 and show Button0. OK
5. Click Button0: new '1' and '0' appeared. That means both click handlers from visible and hidden elements get called. NOT OK

### What is expected?
Handler from hidden Button1 not get called by click on Button0.

### What is actually happening?
Both handlers from Button0 and Button1 get called.

**Comment by LinusBorg** [comment]
This happens because Vue re-uses the element to optimize rendering.

You have to control that behaviour with keys:

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key
