### ISSUE TITLE
IE11 fires "input" event on textarea if a placeholder is set

### ISSUE THREAD

**Issue by oberhamsi** [vuejs/vue#7138]
### Version
2.5.8

### Reproduction link
[https://jsfiddle.net/50wL7mdz/79205/](https://jsfiddle.net/50wL7mdz/79205/)

### Steps to reproduce
Opening the page in IE11 will display the message "Foo is no longer null".

In modern FF, Chrome and Edge the message does not show up and foo remains null until the user actually inputs something.

IE11 does not fire an input event if no placeholder is set as show with the second textarea.

### What is expected?
No input event should fire and thus foo should remain null

### What is actually happening?
IE fires an input event if the textarea has a placeholder

---
There was a similar issue in angular https://github.com/angular/angular.js/issues/2614

**Comment by posva** [comment]
Unfortunately, this is an IE bug (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/). IE shouldn't fire an input event

I thought we already closed an issue with this but I couldn't find it, must be my imagination 😄

**Comment by oberhamsi** [comment]
Found this on the old bug tracker and last comment from MS: no fix

https://connect.microsoft.com/IE/feedback/details/856700/ie11-ie10-send-input-events-at-times-when-it-is-not-appropriate

**Comment by yyx990803** [comment]
Note: I assume you want to preserve the `null` state to determine whether an input field is dirty or not. The patch only fixes the initial rendering - subsequent change to `placeholder` (if a dynamic binding is used) will still trigger `input` events in IE, and it happens to `<input>` tags as well. That we consider a wontfix as it involves significantly more complex workarounds for marginal benefits.

**Comment by oberhamsi** [comment]
thanks!
