### ISSUE TITLE
vue-cli创建项目，在iOS下打开会报错ReferenceError: Can't find variable: SockJS

### ISSUE THREAD

**Issue by chemandy** [vuejs/vue#7146]
### Version
2.5.9

### Reproduction link
[https://ws3.sinaimg.cn/large/006tKfTcgy1fly0eo5ognj309m019gle.jpg](https://ws3.sinaimg.cn/large/006tKfTcgy1fly0eo5ognj309m019gle.jpg)

### Steps to reproduce
cli版本 2.9.1
vue版本 2.5.2

在iOS下打开会报错ReferenceError: Can't find variable: SockJS，且白屏无任何显示
在pc端下打开没有异常，能正常加载并出现页面

### What is expected?
能正常加载页面

### What is actually happening?
iOS端打开白屏

**Comment by JounQin** [comment]
你这信息没一点儿意义，靠猜？
