### ISSUE TITLE
Ability to trigger events from directives

### ISSUE THREAD

**Issue by elijahiuu** [vuejs/vue#7147]
### What problem does this feature solve?
Currently there is no way to trigger an event from inside a `directive`'s bind function. I have to resort to inspecting `vnode.data.on['my-custom-event-name']` and executing it directly:  `vnode.data.on['my-custom-event-name'](data)`

Looking into examples from other projects, I found this usage: `vnode.context.$emit()`, but that's not the right scope/target of where I need events to go.

some stackoverflow [discussion](https://stackoverflow.com/questions/40655333/vue-js-emit-event-from-directive)

### What does the proposed API look like?
usage:
```javascript
<input v-my-directive="{inParam: obj}" @my-custom-event-name="handlerFn()"/>
```

bind:
```javascript
  Vue.directive('my-directive', {
    bind: function(el, binding, vnode) {
      el.addEventListener('input', function(e) {
         var inputValidationLogicFail = true;
         vnode.NEED_SOMETHING_HERE.$emit('my-custom-event-name', {event: e, outVal: inputValidationLogicFail});
      });
```

Why I do not choose component for this - I thought there would have to be a lot of boiler plating of propagating all the attributes down to `<INPUT>` field if it was inside a component. 

I looked at how [vee-validate](https://github.com/baianat/vee-validate/blob/60872e97b226fe95ef3607020c31b6526e8ac918/src/directive.js#L20) handled this communication. They used an object, an errorsBag to pass around between vnode.context and directive.  
[Bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue/blob/7f7eba1f814202ad3200653d7f252a3ab100a0f8/src/directives/toggle/toggle.js#L24) used this mechanism: `vnode.context.$root.$emit(EVENT_TOGGLE, target)` This is what i mentioned earlier.

**Comment by yyx990803** [comment]
The handler is simply registered as a native DOM event listener on the element, so you can just create and dispatch a DOM event using the native APIs: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by hclj37** [comment]
> The handler is simply registered as a native DOM event listener on the element, so you can just create and dispatch a DOM event using the native APIs: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

Thank you @yyx990803,

Don't forget to set `bubbles` to `true`:

```js
const event = new InputEvent('input', { bubbles: true })
el.dispatchEvent(event)
```

**Comment by Knogobert** [comment]
And if you want to pass along any parameters, use the [vanilla JS CustomEvent](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent):

```js[directive.js]
const payload = 'anything';
const myEvent = new CustomEvent('my-event', { detail: payload });
el.dispatchEvent(myEvent)
```

may then be consumed as:
```html[component.vue]
<div v-my-directive @my-event="handlerFn()">
  ...
</div>
```
