### ISSUE TITLE
为 firefox57 开发的使用 vuejs 的插件，没通过安全审核

### ISSUE THREAD

**Issue by huoxy** [vuejs/vue#7148]
### What problem does this feature solve?
我的 firefox 的 CSP 内容如下：

  "content_security_policy": "script-src 'self' 'unsafe-eval' https://api.coinmarketcap.com https://deals99.com; object-src 'self'"

mozilla 给我发的邮件内容如下：

----------------------------------------
Hello,

Your add-on Cryptocurrency Price Tracker - Bitcoin, Ethereum has been reviewed and one or more of of its versions have been disabled due to critical issues discovered.

Details:
This version did not pass the review because of the following issues:

1) The use of &#39;unsafe-eval&#39; is not allowed in the manifest.json&#39;s CSP as it can cause major security issues.

2) Your custom CSP allows remote-script injection which is not allowed.

Please fix them and submit again. Thank you.

是因为我的 CSP 里声明了使用 unsafe-eval 导致的，请问这该怎么解决？

### What does the proposed API look like?
Vue.dont_use_eval();

**Comment by fnlctrl** [comment]
你好，请使用不带模板编译器的vue(vue.runtime.js)+预编译的模板，来避免vue使用eval。
具体参见：https://vue-loader.vuejs.org/zh-cn/，需要使用webpack+vue-loader。

**Comment by huoxy** [comment]
@fnlctrl 你好，现在改造成了 webpack + vue-loader 的模式，请问“不带模板编译器的vue(vue.runtime.js)+预编译的模板“ 怎么解释？

```node
import Vue from "../../node_modules/vue/dist/vue.runtime.js"
```

这样么？

另外，预编译的模板，应该搜什么资料？

**Comment by fnlctrl** [comment]
这样可以工作，但推荐使用
https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
下webpack条目的配法。使用vue-loader就意味着模板是预编译的了，不需要别的配置。

**Comment by huoxy** [comment]
@fnlctrl 还是没正常工作，应该是我哪里配置出了问题。

详细描述下：
1. webpack + vue-loader 已经配置好
    * webpack.config.js: `alias: {"vue$": 'vue/dist/vue.runtime.js' }`
    * 有一个单独的 component.vue 文件

2. index.html 类似下面内容，并在 `<header>` 里引入编译后的 app.js 文件
```html
<div id="main_wrapper">
  <Comp></Comp>
</div>
````

3. app.js(编译前的 js 文件）
```node
import Vue from "vue"
import Comp from "../vue/component.vue"
var vm = new Vue({
    el: "#main_wrapper", 
});
```

现在编译是可以通过的，但是会提示：
```
popup.js:11732 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

**Comment by huoxy** [comment]
@fnlctrl 我猜测，是在 app.js 里，直接调用：
```node
new Vue({
  el: '#main_wrapper',
  compolents: {
    Comp
  }
})
```
这里出现了问题？

**Comment by fnlctrl** [comment]
Index.html里只能写一个空的div，Comp要写在根实例的模板里。报错是因为vue的纯运行时版本不能编译出现在HTML里的模板（`<Comp/>`）。可参考
https://github.com/vuejs-templates/webpack-simple里的写法。

**Comment by huoxy** [comment]
@fenduru 十分感谢，已经能 work 了。

一个加密货币行情插件，可以试用下：

https://chrome.google.com/webstore/detail/cryptocurrency-price-trac/ogikkjdnpheackljfelfkgbgdpmpjpfl

**Comment by huoxy** [comment]
@fnlctrl 十分感谢，已经能 work 了。

一个加密货币行情插件，可以试用下：

https://chrome.google.com/webstore/detail/cryptocurrency-price-trac/ogikkjdnpheackljfelfkgbgdpmpjpfl
