### ISSUE TITLE
use `this` in vue template

### ISSUE THREAD

**Issue by magicdawn** [vuejs/vue#7155]
### What problem does this feature solve?
for custom event, if there are multiple child component and the top component listens to them like

```
<!-- parent.vue -->
<child
  v-for='item in array'
  @event='eventHandler'
/>
```

for eventHandler, there is no way to identity which `child` emits this event.
So use the event arg

```vue
<!-- child.vue -->
<button @click='$emit('event', this)'></button>
```

but the compiled code looks like

```
on: {
  click: function($event) {
    _vm.$emit("event", this)
  }
}
```

and `this` is null, maybe `this` can be replaced with `_vm`

### What does the proposed API look like?
I know `this` can be accessed in JavaScript methods. but it would be nice to use in template.
Or a better way to solve what said above?

**Comment by yyx990803** [comment]
You can use `$emit('foo', _self)`, however that's considered a private API - use it at your own risk. I'd recommend just using a method for that purpose.
