### ISSUE TITLE
npm install --global vue-cli

### ISSUE THREAD

**Issue by lihua123569** [vuejs/vue#7161]
What problem does this feature solve?

[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

symbol is primitive value and very suitable as key.

What does the proposed API look like?
npm install --global vue-cli
no warnings with symbol
![image](https://user-images.githubusercontent.com/8295524/33426450-d0e40bd8-d5fc-11e7-8927-037c8527608e.png)

**Comment by posva** [comment]
hey @lihua123569 Please stop spamming new issues, this doesn't help us, everything is explained at https://github.com/vuejs/vue-cli/issues/655#issuecomment-348159794
