### ISSUE TITLE
v-show/v-if fails to update when using Map collection

### ISSUE THREAD

**Issue by Nic0tiN** [vuejs/vue#7162]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/w0d3cdj7/](https://jsfiddle.net/w0d3cdj7/)

### Steps to reproduce
1. In JSFiddle, click on "Fill My Array", the label "My v_myArray is filled" shows up.
2. Click on "Fill My Map", the label should appear but is not.
3. If you click again on "Fill My Array", both label will appear.

### What is expected?
On step 2, The label "My v_myMap is filled" should appear when clicking on the button "Fill my Map"

### What is actually happening?
The label "My v_myMap is filled" is not appearing.

---
I didn't try but you should expect Set collection to act the same.

**Comment by yyx990803** [comment]
Currently Vue does not support reactivity on `Map/Set/WeakMap`. This will be supported in an upcoming version that targets only modern browsers.
