### ISSUE TITLE
Vue.js integrated into Angular fails to work 100% at second time

### ISSUE THREAD

**Issue by brunollopes** [vuejs/vue#7168]
### Version
2.1.8

### Reproduction link
[https://stackoverflow.com/questions/47499567/vue-js-integrated-into-angular-fails-to-work-100-at-second-time#](https://stackoverflow.com/questions/47499567/vue-js-integrated-into-angular-fails-to-work-100-at-second-time#)

### Steps to reproduce
Please check the details of the reported issue at 

https://stackoverflow.com/questions/47499567/vue-js-integrated-into-angular-fails-to-work-100-at-second-time#

Thanks

### What is expected?
normal behaviour, on click buttons to change slide to work as expected

### What is actually happening?
on click nothing happens

---
Please check:

https://stackoverflow.com/questions/47499567/vue-js-integrated-into-angular-fails-to-work-100-at-second-time#

Thanks

**Comment by yyx990803** [comment]
Sorry but a StackOverflow question is not a valid bug or reproduction.
