### ISSUE TITLE
vue method support async/await or not ?

### ISSUE THREAD

**Issue by guixue** [vuejs/vue#7170]
.babelrc :  es2017 
Vue: 2.2.6

`
methods: {
    async getTaskList(){
      let data = await this.$store.dispatch('TaskList', tid)
      console.log("TaskList", data);
    }
  },

mounted() {
    this.getTaskList();
}
`
But I got the error in chrome console:

> vue.esm.js?65d7:479 [Vue warn]: Error in mounted hook: "ReferenceError: regeneratorRuntime is not defined"

**Comment by guixue** [comment]
I find the solution:
1. 

`npm install --save-dev babel-plugin-transform-runtime`

2. modify .babelrc

`{
  "presets": [
    "es2017", ["env", "commonjs"],
    "stage-2"
  ],
  "plugins": [["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]]
}`

**Comment by JounQin** [comment]
You should just include [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime) or `babel-polyfill` by yourself rather than use `babel-plugin-transform-runtime` which will increase your bundle size.
