### ISSUE TITLE
Virtual DOM replacement with template literals library (viperHTML/hyperHTML)

### ISSUE THREAD

**Issue by janat08** [vuejs/vue#7181]
### What problem does this feature solve?
Ease of manual DOM manipulation, performance, and console errors

### What does the proposed API look like?
Usage of https://github.com/WebReflection/viperHTML library.

**Comment by posva** [comment]
It's not the first time you troll around in Vue issues. It looks like you're projecting your anger again here.
We understood you don't like Vue template syntax but If you really want to feel better, ask questions on the forums, on the discord chat. There's plenty of people enjoying coding with Vue and probably willing to help other people feel that way as well 🙂

**Comment by janat08** [comment]
Yes it's ridiculous how virtual dom is slower than viperHTML while preventing direct DOM manipulation and helpful console errors, and I don't take issue with that.
