### ISSUE TITLE
希望提供slot的扩展特性

### ISSUE THREAD

**Issue by Alphmega** [vuejs/vue#7182]
### What problem does this feature solve?
```vue
<action-bar>
    <navigation-btn icon="<"/>
    <action-item icon="A" position="left"/>
    <action-item icon="B" position="right"/>
</action-bar>
```
一些组件内的子组件，没有显式定义slot的位置，例如这三个子组件需要插入不同的slot里边，希望能提供类似如下API，可以通过子组件的属性，计算出具体的slotName

### What does the proposed API look like?
```vue
<template>
    <div class="action-bar">
        <slot name="left"></slot>
        {{ title }}
        <slot name="right"></slot>
    </div>
</template>
<script>
// action-bar 组件
export default {
    props: {
        title: String
    }
}
</script>
```
```javascript
// navigation-btn 组件
export default {
    // 当不明确设置slot的时候，slot的值为left
    slot: 'left'
}
```
```javascript
// action-item 组件
export default {
   props: {
       position: String
   },
   // 也可以是function
    slot() {
       return this.position
    }
}
```

**Comment by posva** [comment]
Having the component control its slot is not explicit and is less flexible than the current solution which is explicit.
IMO controlling the position of the slot is quite an advanced usage and is doable in render functions
You should also be able to add a `slot` prop to reuse that value

**Comment by Alphmega** [comment]
@posva 
Although this may become less flexible, it is quite difficult to write some custom components with the current solution, such as `table`,` thead` and `tbody` need to be inserted into different slots without slot attr define

**Comment by posva** [comment]
Is it difficult because you have to specify a slot attribute?

**Comment by Alphmega** [comment]
In fact, the above code is an example copy from https://docs.nativescript.org/ui/action-bar

**Comment by Alphmega** [comment]
@posva 
Specify a slot attribute is not difficult, but `thead` and `tbody` just the sub component of `table`. 
I think the slot attribute is nothing but redundancy. For example:
```vue
<my-component>
    <my-component-left slot="left"></my-component-left>
    <my-component-right slot="right"></my-component-right>
<my-component>
```
It looks silly

**Comment by posva** [comment]
Imagine writing

```html
<my-component>
    <my-component-left></my-component-left>
    <my-component-right></my-component-right>
<my-component>
```

and ending up with 

```html
<my-component>
    <my-component-right></my-component-right>
    <my-component-left></my-component-left>
<my-component>
```

If it's redundant, you can use the slots and place them in the same order they are written by the user

**Comment by yyx990803** [comment]
IMO it's better to use explicit slots, so this will not be added to core.

However, it's possible to implement this yourself with render functions. Just inspect `this.$slots.default` and resolve the slot VNodes with some custom logic.

**Comment by Alphmega** [comment]
@yyx990803 Thanks for providing a viable solution
