### ISSUE TITLE
Client side hydration works in development but fails in production

### ISSUE THREAD

**Issue by iloginow** [vuejs/vue#7183]
### Version
2.5.9

### Reproduction link
[https://github.com/iloginow/vue-base-template](https://github.com/iloginow/vue-base-template)

### Steps to reproduce
* Install the template:

``` bash
vue init iloginow/vue-base-template my-debug
cd my-debug
npm install
```

* Run the dev-server and make sure the app works just fine:

``` bash
npm run dev
```

* Build for production and run to see client-side hydration fail:

``` bash
npm run build
npm start
```

### What is expected?
The app is expected to behave the same way in production as it does in the development environment.

### What is actually happening?
The app works perfectly on dev-server but in production, it appears to be totally dead as client-side hydration somehow fails.

---
I decided to build my own Vue SSR [template](https://github.com/iloginow/vue-base-template) that I could use for my projects. It's partially based on [this example](https://github.com/vuejs/vue-hackernews-2.0). Everything was fine and worked as expected. And it still does on the dev-server) But when I'd built the app for production I suddenly discovered that it was totally dead. I got no errors, no warnings, no other signs that could point out the direction where I should search for the answers whatsoever... And it's just blowing my mind! 

I'm not sure if it's a Vue bug really... It's probably not, it might be something else... Or maybe I'm just stupid enough to miss something very simple here. I just don't know. I spent so much time trying to solve this... But found nothing, and I feel pretty helpless. So any help would be appreciated!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If it turns out to be a bug and you manage to boil it down to only the necessary, open an issue again with it 🙂
