### ISSUE TITLE
组建中写<style src="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css"> </style>打包报错

### ISSUE THREAD

**Issue by liucun1986** [vuejs/vue#7187]
### Version
undefined

### Steps to reproduce
打包

### What is expected?
怎么解决？

### What is actually happening?
必现

---
组件中这样写打包会报错<style src="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css">
</style>
ERROR in ./src/App.vue
Module not found: Error: Can't resolve 'https://cdn.bootcss.com/bootstrap/3.3.7/
css/bootstrap.css' in 'D:\vuewebpack\webpacksimple\src'
 @ ./src/App.vue 3:2-246
 @ ./src/main.js

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
