### ISSUE TITLE
SSR value hydration for elements with render function

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue#7188]
### What problem does this feature solve?
When using JSX/Render functions with inputs, setting default rendered value in SSR, requires so specialist understanding about the VNode API.

```
{
  render(h) {
     const Input = h('input')
     if (process.env.VUE_ENV === 'server') {
       data.attrs.value = this.model
     }
     return input
  }
}
```

Currently when binding the value to an input `<input :value="aValue" />` you will get the rendered html as `<input>`. This works client side as we are mutating the `InputElement.value`. Thus you can set an initial value.

Elements such as `input` may have `value` / `checked` attributes ect. On the server we should be rendering as `<input value="email@example.com">` to pre-define the initial value. Or `<input checked="checked">` for checkbox/radio for example.

React has an API called `defaultValue` for setting the initial value: https://zhenyong.github.io/react/docs/forms.html#default-value

## Note: 

We do this with `VUE_ENV` as on the client the value is updated via the `checked` / `value` on the Element itself, as we do not want to cause an attribute change each time.

### What does the proposed API look like?
A solution could be to follow the defaultValue API but that doesn't really work for `checked`. Thus internally handling input types to correctly render the default value via attribute for SSR content will simplify setting the initial display value for inputs.

**Comment by yyx990803** [comment]
Are you sure? The following renders the value as expected:

``` js
render (h) {
   return h('input', { domProps: { value: this.foo } })
}
```

Renders:

``` html
<input data-server-rendered="true" value="bar">
```

If it's not rendering the value then there's probably something wrong and we will need a bug report with reproduction.

**Comment by blake-newman** [comment]
Nice, cheers makes sense.
