### ISSUE TITLE
Separate namespace for computed, props, and data variables within templates and scripts

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue#7189]
### What problem does this feature solve?
I love everything about Vue, and this request is certainly not a gripe. I also realize it's quite a paradigm shift and only suited for a _major release_, but I wanted to get it out there to get other's opinions on the matter.

Currently, a Vue instances hangs all member variables – regardless of props, computed, or data – off of the same instance; they all share the same namespace. This works nicely for very small components and I always strive to write components to be as small as possible. However, a continuing struggle I have when explaining the first part to new developers is _why_ these different variable constructs are smashed together and I never had a great explanation that satisfied me or my padawan.

I imagine in my ideal world that all of these constructs would be in their own namespace, not solely to avoid naming collisions (though that would be an extra benefit), but to make it easier to identify _where_ the source of the variable lies.

### What does the proposed API look like?
In templates:

```
<template>
    <ul>
        <li>{{ data.userName }}</li>
        <li>{{ prop.show }}</li>
        <li>{{ computed.firstAndLasName }}</li>
    </ul>
</template>
```

The definition of each structure remains unchanged, but I think this will help to clarify where a particular value originated from in order to help new users as well as old user who might be taking over a new codebase. Thoughts?

**Comment by yyx990803** [comment]
Well, we already have `$data` and `$props`, and it should be possible to write a plugin that creates a `$computed` object that simply proxies the fields to the Vue instance itself, so this seems already achievable today (although without getting rid of the name conflict).

**Comment by sirlancelot** [comment]
Oh right I'd forgotten about the `$props` recent addition! Thanks for that, I may write a small plugin to create a `$computed` object then I can crafts templates unambiguously.
