### ISSUE TITLE
got warn when accessing vm in data method

### ISSUE THREAD

**Issue by coolzjy** [vuejs/vue#7190]
### Version
2.5.9

### Reproduction link
[https://codepen.io/cool_zjy/pen/KyLpve](https://codepen.io/cool_zjy/pen/KyLpve)

### Steps to reproduce
run the reproduction and check console panel.

### What is expected?
works fine

### What is actually happening?
[Vue warn]: Property or method "outerHTML" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Foo>
       <Root>

**Comment by Nirazul** [comment]
Funny, when you log `typeof vm`, there's no error.

**Comment by Akryum** [comment]
Accessing the instance [is working fine](https://codepen.io/Akryum/pen/Bmeopq), what is the use-case of doing a `console.log` on it in the `data` hook? (Also, the `vm` argument is unecessary in your example.)

**Comment by Akryum** [comment]
[I can't reproduce it with JSFiddle](https://jsfiddle.net/Akryum/mfjta4ba/), so it may be an issue related to CodePen.
