### ISSUE TITLE
When pushing to previously empty array, it doesn't update the dom.

### ISSUE THREAD

**Issue by kobimilan995** [vuejs/vue#7195]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/kobimilan995/50wL7mdz/81519/](https://jsfiddle.net/kobimilan995/50wL7mdz/81519/)

### Steps to reproduce
I'm using vue with laravel, and i have an array of statuses. On button click i want to push new status and update the DOM dynamically. If the array is initially empty nothing happens. DOM doesnt update, but statuses are there. If i declare an array like this: statuses: [' '], or any other element in it, it works fine. 

### What is expected?
I m expecting DOM update when i push to empty array. 

### What is actually happening?
Nothing is happening. No DOM updates.

**Comment by LinusBorg** [comment]
Your jsfiddle works fine for me, can't reproduce.

**Comment by kobimilan995** [comment]
Yes. But exactly the same scenario wont work in my laravel-vue project.  I'm using vue 2.4.4

**Comment by LinusBorg** [comment]
Well, I'm not sure how we should evaluate a possible bug without a reproduction.

You likely made some other mistake, I suggest you ask on the forums or chat.

* forum.vuejs.org
* chat.vuejs.org

If you can provide a (runnable, minimal) reproduction of the problem, we can re-open this issue.
