### ISSUE TITLE
服务端渲染完成之后 如何关闭dom校验

### ISSUE THREAD

**Issue by crazyhuoshan** [vuejs/vue#7196]
### What problem does this feature solve?
在开发模式下，Vue 将推断客户端生成的虚拟 DOM 树 (virtual DOM tree)，是否与从服务器渲染的 DOM 结构 (DOM structure)匹配。如果无法匹配，它将退出混合模式，丢弃现有的 DOM 并从头开始渲染。在生产模式下，此检测会被跳过，以避免性能损耗。

生产模式下会自动跳过DOM的匹配么？

我现在有个需求就是 我要在vue逻辑执行之前 在客户端对服务端返回的dom进行一些修改(修改操作是外部js处理的，为了让这个操作更快 所以让他在vue代码执行之前执行) ，处理完之后发现vue 校验了dom 然后dom出现了问题

### What does the proposed API look like?
如上

**Comment by yyx990803** [comment]
这不算 feature request。
