### ISSUE TITLE
Input checkbox multiple-choices not working in mobile browser for nested object

### ISSUE THREAD

**Issue by GuroKung** [vuejs/vue#7202]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1. Having nested object variable and want to assign multiple checkboxes, bound to the same array
e.g. data: {
            subscription: {
                category: []
            }
        }
2. try using with form in IOS and Android browser 
3. it's value will be just true or false

### What is expected?
Suppose to be working perfectly
value should be ['D','M','Y']

### What is actually happening?
value just only is true or false

---
1. Input assigned with multiple checkboxes, bound to the same array has lots of bug, especially in Android browser. Sometimes it trigger all multiple-checkbox, sometimes it trigger another checkbox.

2. Everything working fine in normal web browser

PS. what I'm working with it's within another application's web-view not a normal browser

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

When opening bug reports, please provide a repro and if it only happens on specific browsers, the list of browsers to test it on
