### ISSUE TITLE
vue 多层数据变化不更新的问题

### ISSUE THREAD

**Issue by QylinFly** [vuejs/vue#7203]
### Version
2.2.2

### Reproduction link
[https://segmentfault.com/q/1010000008726983](https://segmentfault.com/q/1010000008726983)

### Steps to reproduce
详细参见
https://segmentfault.com/q/1010000008726983

### What is expected?
https://segmentfault.com/q/1010000008726983

### What is actually happening?
https://segmentfault.com/q/1010000008726983

---
https://segmentfault.com/q/1010000008726983

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
