### ISSUE TITLE
the author have know the vuejs can not refresh the view,why did not fix the bug?

### ISSUE THREAD

**Issue by Chasen-Zhang** [vuejs/vue#7205]
### Version
2.5.9

### Reproduction link
[https://jsbin.com/](https://jsbin.com/)

### Steps to reproduce
the author have know the vuejs can not refresh the view,why did not fix the bug? I am so puzzeld,i am the vuejs fan,but i intolerability!!!!!!

### What is expected?
the author have know the vuejs can not refresh the view,why did not fix the bug? I am so puzzeld,i am the vuejs fan,but i intolerability!!!!!!

### What is actually happening?
the author have know the vuejs can not refresh the view,why did not fix the bug? I am so puzzeld,i am the vuejs fan,but i intolerability!!!!!!

---
the author have know the vuejs can not refresh the view,why did not fix the bug? I am so puzzeld,i am the vuejs fan,but i intolerability!!!!!!

**Comment by Chasen-Zhang** [comment]
I hope the author fix it

**Comment by posva** [comment]
Please, follow the contributing guidelines when opening a bug report: that is not a repro (and of course, we will also need steps to reproduce).

**Comment by gebilaoxiong** [comment]
Hi, please describe your problem

I mean...  `Link to minimal reproduction`
