### ISSUE TITLE
vnode reference to original component

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#7213]
### What problem does this feature solve?
I have two components that are meant to be used *together*, parent and child. Meaning, the only components allowed in the default slot of the Parent component is the Child component.

I was originally enforcing this check with the following code, after importing the Child component to `ChildComponent`:

```
beforeCreate() {
	this.$slots.default.forEach((vnode) => {
		if (
			vnode.componentOptions &&
			vnode.componentOptions.Ctor.extendOptions !== ChildComponent
		) {
			throw new Error('...');
		}
	});
}
```

This typically works fine, however, I've noticed that it doesn't in the context of my Karma test. `vnode.componentOptions.Ctor.extendOptions` evaluates to a copy of the component where the main difference seems to be the additional property of `_Ctor: { 1: ƒ VueComponent(options) }`. (There are other minor differences too, eg. my `inject: { name: key }` is converted to `inject: { name: { from: key } }`). I am looking for a _for sure_ way (ideally via strict equality of object references) to ensure that the children of the Parent component are the Child component.

I used BFS to check if the vnode had any other references to `ChildComponent` but it did not.

### What does the proposed API look like?
I'm not opinionated about the API but some sort of reference to the original component accessible from `vnode`.

**Comment by sqal** [comment]
Why not giving your component a name and then check if it's a component with that name?

example https://jsfiddle.net/a0eudrj6/

**Comment by hirokiosame** [comment]
@sqal 
Because strings aren't unique.

Like I said in my post, I'm looking for a "for sure way (ideally via strict equality of object references)". We're working on components used by 2nd and 3rd parties so we don't want to risk name collision and also not concern ourselves with it all the time.

**Comment by znck** [comment]
You can use custom logic to verify correct component is used in the slot.

Following snippet demos an approach to ensure the type of child components.

```
// component-types.js
export const ListItemType = Symbol('ListItem)
```

```vue
// ListItem.vue
<script>
import { ListItemType } from './component-types'

export default {
  group: ListItemType
}
</script>
```

```vue
// List.vue
<script>
import { ListItemType } from './component-types'

export default {
    render (h) {
  	const children = this.$slots.default
  	return h('div', {}, children.map(vnode => {      
	  if (!vnode.componentOptions || !vnode.componentOptions.Ctor) return vnode
          if (vnode.componentOptions.Ctor.extendOptions.group === ListItemType) return vnode 
      
          console.log(`[Vue Warn]: Invalid use of ${vnode.componentOptions.tag || 'child'} component in Comp.`)
      
      
           return vnode
    }))
  }
}
</script>
```

Working demo: https://jsfiddle.net/znck/7dss4m7k/

**Comment by hirokiosame** [comment]
@znck 

This can definitely be achieved in the user-land, and the issue wasn't opened as a question to find a custom solution. The point of the feature request was to request official support.

**Comment by znck** [comment]
I feel that it would increase vue API surface with no additional benefit.

If you think, it should be added to vue, I can reopen the issue.

**Comment by hirokiosame** [comment]
I think that an extra property to reference the original component will offer a credible and convenient way to confirm the identity and hence integrity of the Vnode at question. If the cost is one property added to the Vnode to gain an official way to assure that the right component is being passed into a Vnode, I think it's a good deal.

**Comment by znck** [comment]
@vuejs/collaborators comments on this!

**Comment by LinusBorg** [comment]
@znck You might want to reopen this if you want a discussion with collaborators. A closed issue in a sea of notifications will be drowned out.

Personally I can't say too much as I don't understand the original problem enough (why the check didn't work in karma etc.) at the moment.

**Comment by hirokiosame** [comment]
Might be worth noting that the problem occurred when using vue-test-utils v1.0.0-beta.7. However, I'm not filing this as a bug, but as a FR on supporting a way to accurately identify the component of a vnode.

**Comment by yyx990803** [comment]
This should work by checking `vnode.componentOptions.Ctor !== Vue.extend(ChildComponent)`

`Vue.extend` caches constructors created from raw options.

IMO this use case is too low-level and too specific to create dedicated API for.

**Comment by hirokiosame** [comment]
@yyx990803 
How would you recommend that I identify a vnode's component? Surely, reading into the slot vnodes isn't uncommon, and being able to tell what kind of vnode it is would be useful.

Not sure what you mean with that code snippet as `Vue.extend(TableCol)` returns a constructor function and `vnode.componentOptions.Ctor.extendOptions` references an Object -- they would never equal each other.


In my example below, `TableCol` is `ChildComponent`.
![screen shot 2017-12-12 at 4 35 01 pm](https://user-images.githubusercontent.com/1075694/33915890-d992db80-df5a-11e7-9e6e-f0397e907adb.png)

`> Vue.extend(TableCol)`
![screen shot 2017-12-12 at 4 36 55 pm](https://user-images.githubusercontent.com/1075694/33915880-b9c88250-df5a-11e7-90e6-58621decab09.png)

I guessed you may have meant `vnode.componentOptions.Ctor.extendOptions._Ctor['1'] === Vue.extend(TableCol)` but that didn't evaluate to true when expected either.

**Comment by hirokiosame** [comment]
FYI, I believe I wasn't able to do a strict equality because of the [deep clone in vue-test-utils](https://github.com/vuejs/vue-test-utils/blob/dev/src/mount.js#L17)

Turned off cloning with [`clone: false`](https://vue-test-utils.vuejs.org/en/api/options.html#clone).
