### ISSUE TITLE
Vue和Vue-router搭配使用，在使用路由切换的时候，加了transition切换动画的问题，

### ISSUE THREAD

**Issue by h330894169** [vuejs/vue#7219]
### Version
2.5.9

### Reproduction link
[https://cn.vuejs.org/v2/api/#transition](https://cn.vuejs.org/v2/api/#transition)

### Steps to reproduce
IOS下，可以向左向右滑动来改变浏览器的history，返回上一页，这个时候，如果加了transition切换动画，切换上一页下一页的时候，会出现非常明显的页面跳动，产品体验过后，不能接受，想知道有什么解决办法能解决这一问题，目前我只能为了体验，把transition干掉了，干掉的话，体验很流畅，。希望作者能有一个好的解决方案，或者，提供一个开关，用来开关transition。

### What is expected?
希望作者能有一个好的解决方案，或者，提供一个开关，用来开关transition。

### What is actually happening?
IOS页面滑动切换至上一页的时候，会出现很明显的闪动

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

There are some [examples](https://github.com/vuejs/vue-router/tree/dev/examples) in the vue-router repo that you may find useful 🙂

**Comment by h330894169** [comment]
@posva 我这是给你们提功能需求

**Comment by niceue** [comment]
@h330894169 我遇到了同样的问题，感觉像是 <transition> 组件的问题，你这里解决了吗

**Comment by h330894169** [comment]
@niceue没有，， 你解决了吗？

**Comment by niceue** [comment]
@h330894169 
网上的解决办法都不行，经过我无数次尝试，发现满足两个关键点可以解决这个问题：

1、设置 `animation-delay` 一个很小的值
```stylus
.page-forward,
.page-back {
  .app-page {
      animation-timing-function: cubic-bezier(0.4,0.6,0.2,1);
      animation-duration: .3s;
      animation-delay: .01s;
      backface-visibility: hidden;
  }
}
```
2、给 `.slide-enter` 初始 `transform` （保持和动画 %0 的 transform 一致）
```stylus
// 前进动画
.page-forward {
  .slide-enter {
    transform: translate3d(100%, 0, 0);
  }
  .slide-enter-active {
    animation-name: slide-left-enter;
  }
  .slide-leave-active {
    animation-name: slide-left-leave;
  }
}
@keyframes slide-left-enter {
  0% {
    transform: translate3d(100%, 0, 0);
  }
  100% {
    transform: translate3d(0, 0, 0);
  }
}
```

以上两点缺一不可

**Comment by h330894169** [comment]
可以把完整的代码贴出来吗？。我想看你的transition怎么配置的。 @niceue

**Comment by Dowgen** [comment]
我没加transition也遇到你这个问题...而且只有一个页面会出现，其他都不会....

**Comment by ycycorona** [comment]
同样有此问题，有些页面之间会跳动，有些就不会 ps:我已经通过判断，使ios左滑返回时<transition>的name为空，可以抑制部分跳动，但还是会跳！

**Comment by pengxiang-git** [comment]
ios上，A页面很长拉到最后，pushState跳转到B页面，这个时候会有一帧闪烁。接下来就神奇了：点击浏览器回退按钮，没有任何异常，再点击前进按钮，任然没有任何异常。这个问题咋解决啊，无力回天啊

**Comment by pengxiang-git** [comment]
同上求解，ios上，A页面很长拉动屏幕到最后，router.pushState跳转到B页面，这个时候会有一帧闪烁。点击浏览器回退按钮，然后再点击前进按钮，这样却没有闪烁的效果。在pc上一切正常，不知道有没有人遇到这个问题？求解，效果可以用微信扫一扫看下
![Uploading image.png…]()
