### ISSUE TITLE
Better JSX examples

### ISSUE THREAD

**Issue by pixelass** [vuejs/vue#7222]
Can you please suggest a better resource for Vue JSX ? Maybe a working JSX example?

**Comment by pixelass** [comment]
O M G

**Comment by posva** [comment]
The docs is the place you want to go. If you go to the [Discord server](https://vue-land.js.org/) somebody will probably give you some examples.
If you have improvements proposals, the docs repo is at https://github.com/vuejs/vuejs.org 🙂

**Comment by pixelass** [comment]
OK. thx. I won't create a discord account though. I'm really just building an integration and don't want to have to create new accounts to understand how an open-source library works.

I guess I'll just play around until I understand.

Thank you anyways. 

Since I don't use vue and have no intention in doing so I most probably won't contribute here, sorry. 
If my project goes as expected I might rethink.
