### ISSUE TITLE
Add dist/vue.esm.d.ts

### ISSUE THREAD

**Issue by plantain-00** [vuejs/vue#7225]
### What problem does this feature solve?
Typescript error for following code:
```ts
import Vue from "vue/dist/vue.esm.js";
```

### What does the proposed API look like?
The file content can be:
```ts
export * from "vue";
import Vue from "vue";
export default Vue;
```

### Environment

+ parcel: doesn't support webpack alias(https://github.com/parcel-bundler/parcel/issues/25) and doesn't support `import Vue from "vue";`

**Comment by LinusBorg** [comment]
> Typescript error for following code:

Please clarify:

1. What kind of error is happening?
2. Is that error only happening with parcel?

**Comment by plantain-00** [comment]
1. The error is `error TS7016: Could not find a declaration file for module 'vue/dist/vue.esm.js'`
2. The error is not only happening with parcel(parcel just want me to use the esm release)

I'm going to wait parcel to support alias, so I can use `import Vue from "vue";`

**Comment by LinusBorg** [comment]
Wouldnt typescript's path mapping allow for the same thing? 

https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by LinusBorg** [comment]
As this is a feature of typescript working essentially the same as babel's `plugin-module-resolver` and webpack's `alias`, I wouldn't call this a temporary solution, really.

**Comment by joevandyk** [comment]
I'm getting this error: 
```
Could not find a declaration file for module 'vue/dist/vue.esm.js'.
```
on this line:
```
import Vue from 'vue/dist/vue.esm.js';
```
Is the fix to use typescript's path mapping? If so, exactly how do I use it?

**Comment by Taytay** [comment]
I am unclear how to use Typescript's path mapping, and would still appreciate a pointer on that if anyone else stumbles across this issue, but I was able to work around this with Webpack/Webpacker by telling it to map Vue to vue.esm.js:


From:
https://stackoverflow.com/a/52140906/544130

```
const { environment } = require('@rails/webpacker');
const vue =  require('./loaders/vue');

environment.loaders.append('vue', vue);
environment.config.resolve.alias = { 'vue$': 'vue/dist/vue.esm.js' }; // <- add alias
module.exports = environment
```
