### ISSUE TITLE
Watch immediate=true has no effect when declared in component options

### ISSUE THREAD

**Issue by Toilal** [vuejs/vue#7226]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/Toilal/q976rqrw/](https://jsfiddle.net/Toilal/q976rqrw/)

### Steps to reproduce
Open JSFiddle and see

### What is expected?
Handler from component options should be invoked immediatly like handler from $watch method

### What is actually happening?
Handler from component options is not invoked initially

**Comment by javoski** [comment]
For watch option:
```js
watch: {
  message: {
    immediate: true,
    handler: function () {
      ...
    }
  }
}
```
[https://jsfiddle.net/q976rqrw/4/](https://jsfiddle.net/q976rqrw/4/)

**Comment by Toilal** [comment]
Oups sorry for noise. Strange that TypeScript didn't cached this though.
