### ISSUE TITLE
Warn misused singular option name

### ISSUE THREAD

**Issue by hibiyasleep** [vuejs/vue#7227]
### What problem does this feature solve?
```
export default {
  // ...
  mixin: [ // missing 's'
    onlyOneMixin
  ],
  prop: { // missing 's'...
    dinner: Object
  },
  component: { // missing 's' again
    MyComponent
  },
  method: { // missing 's', again and again
    eat: _ => ...
  },
  filter: { // again!!!
    ...
  }
}
```

This might be confusing, but it's hard to realize what's wrong - especially for beginners.

### What does the proposed API look like?
```
[Vue warn] possible typo in component option 'component' - did you mean 'components'?
```

**Comment by samayo** [comment]
This definitely can help to the very few who make the initial mistake. But I don't believe it is worth fattening the Vue src to handle such a trivial mishap. You only make such mistakes once. So, imho it doesn't seem essential to me.

**Comment by LinusBorg** [comment]
That's a job for a linter. See [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue)
