### ISSUE TITLE
does not select correct option after render and syntax sugar

### ISSUE THREAD

**Issue by wakame-isono** [vuejs/vue#7228]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/wakame_isono_/ag47vg4b/](https://jsfiddle.net/wakame_isono_/ag47vg4b/)

### Steps to reproduce
Use syntax sugar and after render option for select 

### What is expected?
select option selected

### What is actually happening?
select option is not selected

**Comment by yyx990803** [comment]
This is expected behavior. `v-model` has special logic for handling changed options. When using direct bindings, you need to add `selected` bindings to the options instead: https://jsfiddle.net/ag47vg4b/2/
