### ISSUE TITLE
force watcher

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue#7231]
### What problem does this feature solve?
computed v-model. 

if i have a input using computed v-model with prop(default:'') and using trim() on the return value. if user input something, it will be emit to the parent to handle, and will be prop back at last.

example: https://codepen.io/lasthrun/pen/qpEZwK

the case is when i just input ' ' in the input, the return value will always be ''. but actually, the input filed is look like '       '. these two value is not be match. because the return value is always be ''. it will not active the watcher to update the input field.

if we have this feature. the v-model will always be match the return value.

### What does the proposed API look like?
value: {
  handler: function (val, oldVal) { /* ... */ },
  force: true
},

**Comment by yyx990803** [comment]
I have trouble understanding what you want because your code isn't even runnable. But I assume you are looking for a way to force trim the input even when the user is typing. In that case, you can call `this.$forceUpdate()` right after `this.$emit` in the input component.
