### ISSUE TITLE
服务端渲染并发测试后内存保持高点一段时间之后才开始下降

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#7232]
### Version
2.5.10

### Reproduction link
[https://github.com/Jokcy/vue-server-render-issure](https://github.com/Jokcy/vue-server-render-issure)

### Steps to reproduce
启动服务，进行压力测试，我测试的时候用的是jmeter，200并发循环200次。启动服务内存20左右，并发期间大致到70，然后保持70内存几分钟（这个服务大致1-2分钟），如果更复杂一点会更久，正式项目测试当内存达到最大值左右会导致相应很慢（猜测是因为新的请求进来要先释放内存）

### What is expected?
并发完成后内存马上下降

### What is actually happening?
并发完成后内存没有马上下降

**Comment by yyx990803** [comment]
这不算 bug 吧，内存回收本来就是由引擎决定什么时候进行的。可以试试用 `--expose-gc` 启动 node 然后手动 `global.gc()`
