### ISSUE TITLE
ios9.x this.route.go(-1)方法执行后页面没有后退

### ISSUE THREAD

**Issue by kathieLeung** [vuejs/vue#7234]
### What problem does this feature solve?
在ios9.x系统下，this.$router.go(-1)方法不生效，点击返回键没有后退，停留在当前页面，控制台也没报错，在ios10、ios8都可以正常后退。

### What does the proposed API look like?
<template>
  <div class="rank-head container">
    <a class="rank-head-back" @click="routerBack">返回</a>
  </div>
</template>

<script>
  export default {
    methods:{
      routerBack(){
        this.$router.go(-1);
      }
    }
  }
</script>

**Comment by yyx990803** [comment]
Please read the requirements and make a proper bug report.
