### ISSUE TITLE
not working with IE 11

### ISSUE THREAD

**Issue by akahen** [vuejs/vue#7241]
### Version
2.5.9

### Reproduction link
[http://beta.cvoptical.com/app_portal_template_V2/revo_rewards_vue/](http://beta.cvoptical.com/app_portal_template_V2/revo_rewards_vue/)

### Steps to reproduce
none

### What is expected?
a simple form as shown in any other browser

### What is actually happening?
html in template is not showing
computed item in html within {{}} is not rendering

---
pulled in Vue via CDN, and not using any transcribe utility (i.e. babel)
by default, the site uses bootstrap and jquery, yet pulling Vue at the very end.
thanks

**Comment by yyx990803** [comment]
The repro requirements clearly stated that we expect **minimal reproductions**, and it must have inspectable source code, not full apps.

**Comment by akahen** [comment]
updated link to jsfiddle, https://jsfiddle.net/2dwrr91q/ thanks
