### ISSUE TITLE
template tag for multiple element looping doesn't work in IE11

### ISSUE THREAD

**Issue by nflswxay** [vuejs/vue#7243]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/50wL7mdz/83227/](https://jsfiddle.net/50wL7mdz/83227/)

### Steps to reproduce
Run the fiddle in IE, you'll see it does not render. Same code runs fine in chrome and firefox

### What is expected?
It should show a table with info of cars run horizontally. In my actual project, the length of cars is unknown, so looping is unavoidable.

### What is actually happening?
IE does not render, and the error in dev tool says "car is undefined".

**Comment by yyx990803** [comment]
This is a known limitation when using DOM-based templates because IE11 simply does not allow `<template>` to be placed inside `<tr>`.

To work around this you need to use string-based templates instead.

**Comment by nflswxay** [comment]
I tried implementing this with string based templates but having no luck since multiple root elements is also not allowed in a template. Since this is on multiple tds I can't really wrap it up with a div. Any ideas?
