### ISSUE TITLE
v2.5.11 gets clobbered by uglifyjs-webpack-plugin run through webpack

### ISSUE THREAD

**Issue by threesided** [vuejs/vue#7245]
### Version
2.5.11

### Reproduction link
N/A

### Steps to reproduce
While running UglifyJS Webpack Plugin (https://www.npmjs.com/package/uglifyjs-webpack-plugin), there is an error thrown for a function in vue. The error reads `Uncaught TypeError: s is not a function`. In this instance `s` is referring to the `isPlainObject` function, found in the `normalizeInject` method.

### What is expected?
Uglify should be able to correctly minify Vue

### What is actually happening?
Vue 2.5.11 should be successfully minified by webpack

---
Locking our build back to 2.5.10 fixed the uglify issue

**Comment by yyx990803** [comment]
Just tried a fresh build from `vue-cli` with 2.5.11 and everything seems to work fine. Please provide a reproduction if possible.
