### ISSUE TITLE
Input event for dropdown do not fire in IE11

### ISSUE THREAD

**Issue by beholdr** [vuejs/vue#7248]
### Version
2.5.11

### Reproduction link
[http://jsbin.com/zicevezani/edit?html,js,output](http://jsbin.com/zicevezani/edit?html,js,output)

### Steps to reproduce
Select option in dropdown in IE11

### What is expected?
In console should appear record about triggered event 'processInput', data updates

### What is actually happening?
No record appears in console, 'input' event not triggered, data updates

---
When I change text in textfield, event 'input' triggered correctly, but for select element it's not.
In Firefox/Safari/Chrome everything is working (both textfield and select list).

**Comment by andreiglingeanu** [comment]
Use `@change` event for `<select>` tags

**Comment by beholdr** [comment]
Oh, thank you. `@input` event used in [vue-json-schema](https://github.com/demsking/vue-json-schema) library and it's not working in IE. So I should open issue there if this is IE problem. Sorry, should have checked MDN first.

**Comment by yyx990803** [comment]
^ what @andreiglingeanu said - I don't think Vue can do anything about this.

**Comment by phil-w** [comment]
You're 100% correct on all points. That is: 

1. @input doesn't work on even Polyfilled IE11 (a problem I just hit)
2. Replacing it with @change solves the issue, so this issue saved me a ton of time, thanks.

**Comment by codebymick** [comment]
great solve.  saved me a great deal of headaches after searching every other possibility

**Comment by bovisp** [comment]
This solution saved me! I was having the same issue. @input worked on all browsers except IE11/Edge. Changing to @change solved it.

**Comment by sirlancelot** [comment]
How many notifications do you think the users @input & @change get from Vue & related projects? 😂

**Comment by bovisp** [comment]
Oh my bad @sirlancelot . I totally missed that. But yeah, poor devils!

**Comment by choonggg** [comment]
FYI, changing `@change` breaks Android Chrome, bounced around a bit and ended up using both. `@change` and `@input`
