### ISSUE TITLE
can we have option for set document 

### ISSUE THREAD

**Issue by bluelovers** [vuejs/vue#7250]
### What problem does this feature solve?
希望能有選項可以讓我們自訂 Vue 所使用的 document 而不需要去將 document 設定為 global var
並且支援讓 document 可以在導入 vue 之後 才建立

hope can have option set document that vuejs use
so we didn't need set document to global if we didn't have
or can make us set document "** after import vue **"

### What does the proposed API look like?
`Vue.options.document = (a document like object we wanna use)`

`Vue.document = Vue.options.document || document;`

---

```
function createTextNode (text) {
  return document.createTextNode(text)
}
```

to

```
function createTextNode (text) {
  return Vue.document.createTextNode(text)
}
```

**Comment by yyx990803** [comment]
Your proposal only describes what you want but doesn't explain why you want it. You need to provide the full context and use case on why you need it.

I'll assume you are trying to implement something like a custom renderer, which already has a feature request (#7005). If you are actually looking for something different, please follow up with more details.

**Comment by bluelovers** [comment]
### TypeError: Cannot read property 'innerHTML' of undefined

```javascript
console.log(vm.$el.innerHTML);
                   ^
```

```javascript
import loader from '..';
import tsLoader from '../lib/plugin/ts';
import * as Vue from 'vue/dist/vue';

// create jsdom document
loader.register();
loader.use(tsLoader);

console.log(Vue);

import { options } from './temp/test.vue';

const vm = new Vue(options).$mount();
console.log('= vm.$el.innerHTML =');
console.log(vm.$el.innerHTML);
console.log('= document.documentElement.innerHTML =');
console.log(document.documentElement.innerHTML);
```

### work

```javascript
import loader from '..';
import tsLoader from '../lib/plugin/ts';

// create jsdom document
loader.register();
loader.use(tsLoader);

import * as Vue from 'vue/dist/vue';
console.log(Vue);

import { options } from './temp/test.vue';

const vm = new Vue(options).$mount();

console.log('= vm.$el.innerHTML =');
console.log(vm.$el.innerHTML);
console.log('= document.documentElement.innerHTML =');
console.log(document.documentElement.innerHTML);
```
