### ISSUE TITLE
<template> v-if is not compatible IE 

### ISSUE THREAD

**Issue by github-amazingboy** [vuejs/vue#7254]
### Version
2.5.11

### Reproduction link
[ https://jsfiddle.net/amazingzhang/obfst2c2/ ]( https://jsfiddle.net/amazingzhang/obfst2c2/ )

### Steps to reproduce
open it with IE.

### What is expected?
Hide the table data  <tr> : 'no data'

### What is actually happening?
but it is still here.

**Comment by JounQin** [comment]
https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats

Please read document carefully first.

**Comment by github-amazingboy** [comment]
hello, as the page , we should not use other tag inner table ul ol, so the below code  how to be less and clean
<ul>
<li v-if="area == ‘Europe’">English</li>
<li v-if="area == ‘Europe’">French</li>
<li v-if="area !='Europe'">China</li>
<li v-if="area !='Europe'">Japan</li>
</ul>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you use a template string, you won't be limited by the DOM limitations 🙂
