### ISSUE TITLE
Hoped that the onscroll event can be bound to the component

### ISSUE THREAD

**Issue by vueZZ** [vuejs/vue#7256]
### What problem does this feature solve?
      <textarea v-on:onscroll="this.scroll()" name="" id="" cols="30" rows="10">
        onscroll 事件在元素滚动条在滚动时触发。
      </textarea>
for app to handle onscroll event

### What does the proposed API look like?
 v-on:onscroll

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

it's `v-on:scroll`
