### ISSUE TITLE
列表过渡效果的小bug

### ISSUE THREAD

**Issue by mikoshu** [vuejs/vue#7259]
列表过渡时，如果列表的循环里 (value,index) in arr 列表的key值是 :key="index",这样加的move动画效果是无效的，就是添加和删除有动画，但是数组位置对换没有过渡效果，需要自己去生成key值才可以

**Comment by damnright** [comment]
我也发现了这个bug

**Comment by mikoshu** [comment]
我的错，之前对vue还不太了解，其实不算bug吧，因为vue是根据key值判断元素是否是新的，如果元素的key值包含了index 那实际上key值是改变的，会让vue以为是新的元素，不会复用旧元素，因此无法实现过度效果   所以 这个key值还是让每个元素固定的好，不要包含变量，除非你要更新这个元素

**Comment by zhangzhengyi12** [comment]
我的理解是 列表过渡需要在前后两个阶段（进入和离开）的过程中对列表的每个项目进行追踪 但是两个列表绑定了Index并且如果只是shuffle一下 那么vue会认为并没元素更改 因为两个列表的Index是不会变得，所以需要绑定item元素的唯一标识，也就是类似ID的东西，这才能让Vue得知谁是谁 以及谁去了哪

另外希望大家能够遵循issus规范
