### ISSUE TITLE
"Valid" HTML breaks Vue

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue#7260]
### Version
2.4.4

### Reproduction link
[https://codepen.io/anon/pen/baVjbZ?editors=1010](https://codepen.io/anon/pen/baVjbZ?editors=1010)

### Steps to reproduce
In this pen, the comment within the attributes leaks into the content, and the element is not outputted to the DOM:

https://codepen.io/anon/pen/baVjbZ?editors=1010

when using a DOM-based template, the behavior is different, and error thrown and the original template stays in the DOM so that we see the supposed-to-be-interpolated `{{txt}}` variables on the screen:

https://codepen.io/anon/pen/wpKxGZ?editors=1010

### What is expected?
The "comment" sort of thing should be handled similarly to how plain HTML handles it.

### What is actually happening?
Vue errors out.

---
It might be "invalid" to put a `// comment` in HTML like that, but technically it is valid because all browsers accept this format and convert the comments into a bunch of attributes.

I know, ideally people shouldn't put content in there like that, but I think that Vue should gracefully work just like regular HTML does.

This makes it possible for a developer to, for example, take HTML that may be handed over from a designer who designed it in non-Vue environment, and for it to work without hassle, for the dev to be able to get to working on the data stuff.

**Comment by yyx990803** [comment]
I wouldn't say it's even "technically valid", it's just HTML parsers and Vue's template parsers have different levels of error tolerance. Most HTML parsers as implemented are intentionally tolerant to syntax errors - in fact, **they never explicitly fail**. I personally think it's a bad idea for Vue's parser to mirror that level of error tolerance, as it potentially leads to other types of mistakes being implicitly ignored.

So - this is a wontfix.

**Comment by trusktr** [comment]
I understand your pov, but it's also just an annoyance to have to figure out why some HTML was working then why it wasn't when we added Vue to it.

**Comment by trusktr** [comment]
Also worth noting, it's not like React where people are writing HTML inside JS, but opposite: with Vue people are likely to write regular HTML then apply Vue to it. It's more designer-friendly that way.
