### ISSUE TITLE
remove global variable `self`?

### ISSUE THREAD

**Issue by lzl124631x** [vuejs/vue#7262]
### What problem does this feature solve?
A library should use as less global variables as possible.

One time, I copy & pasted code from one function to another and forgot to change `self` back to `this`. The code  could run but only after a while I was shocked that this `self` is actually pointing to `window`, not my viewmodel. Global variables, especially one with this common name, might cause confusion and should be renamed.

### What does the proposed API look like?
not applicable

**Comment by ktsn** [comment]
Vue does not have `self` as a global variable but `window` has in default. https://developer.mozilla.org/en-US/docs/Web/API/Window/self

**Comment by lzl124631x** [comment]
Oh thanks @ktsn That's embarrassing. I didn't know that.
