### ISSUE TITLE
vue-model.stage keep data before complete all operations

### ISSUE THREAD

**Issue by andyyou** [vuejs/vue#7263]
### What problem does this feature solve?
Although two way binding is quite convenient and useful. But for UI/UX requirements sometimes we hope Vue just help to keep data temporarily before user complete entire operations. To those simple actions that `v-bind:value` with `@change` can implement that easily, but for those complex operations such as cancel behavior of wizard I have a idea if `v-model` support stage(cache) ability then after call `this.$stage.commit('dataProp')` then react automatically to views.

### What does the proposed API look like?
```html
<input v-model.stage="name">
```

```js
vm.$stage.commit('dataProp')
vm.$stage.create({
  prop: newValue
})
vm.$stage.reset('dataProp')
```

**Comment by yyx990803** [comment]
Are you aware of the lazy modifier?

**Comment by andyyou** [comment]
Yes but situation should wait for multiple input finished. 
After think in detail I think I can custom directive or implement with emit

**Comment by Akryum** [comment]
You can use data props to temporarily store de data

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:12848)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1eQdAh-001vrh-H3
	for greg@biomassiv.es; Sun, 17 Dec 2017 11:56:19 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YLBgD6vSxUfJtMifbBWBpBihhak=; b=u+4IWAfICm2e7YaW
	c2mzW/+NfDc07daH73vJHLJRkDanT/JpHXCEc0sffErhCNTz5B+gY9UjIhG4Alah
	Nim5PTCruFW97frP937EFQetzuJTrkl/zCDPNpzdGTcp6NueKOEVVOQcCAAGIt07
	Je3U+8o0116f7/Jt85youkvXp10=
Received: by filter0113p1las1.sendgrid.net with SMTP id filter0113p1las1-27970-5A36AF9A-10
        2017-12-17 17:55:38.870720322 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id E5FeY35rQdyqz9tSNr2fkQ
	for <greg@biomassiv.es>; Sun, 17 Dec 2017 17:55:38.665 +0000 (UTC)
Date: Sun, 17 Dec 2017 17:55:38 +0000 (UTC)
