### ISSUE TITLE
Validate nested props

### ISSUE THREAD

**Issue by zollero** [vuejs/vue#7265]
### Version
2.5.11

### Reproduction link
[https://codepen.io/zollero/pen/opbxXX](https://codepen.io/zollero/pen/opbxXX)

### Steps to reproduce
Prop validate in v2.5.11, does not allow the key of prop to be one out of `['type', 'default', 'required', 'validator']`, and throw a warning error. 

This happens  when the `prop` is an array of object. And I must validate the key of the element object.

For example:

```
export default {
  props: {
    forms: {
      type: Array,
      required: true,
      prop: {
        type: String,
        required: true
      },
      label: String,
      editable: {
        type: Boolean,
        default: false
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/8801894/34087867-c8a8ae3c-e3e0-11e7-8820-bfe5ef989bbf.png)

### What is expected?
Expect the key out of ['type', 'default', 'required', 'validator'] can be valid.

### What is actually happening?
The key out of ['type', 'default', 'required', 'validator'] is invalid.

**Comment by JounQin** [comment]
This is as expected, nested keys are not recognized as validator for your `forms`, you can try to change `editable` to a string and use other Vue version, it will not warn about that.

The warning message is just telling you that you are using incorrect way of prop validator.

If you want to validate `forms`, you need to define your own `validator`.

**Comment by zollero** [comment]
@JounQin I think using `validator` to validate key of `object in array`. If the config above works, it will be very simply to define prop of array with object elements.

**Comment by JounQin** [comment]
It is *not a bug* but a *feature request*.

**Comment by yyx990803** [comment]
There are many potential problems with this syntax - should it require the exact shape (length of keys) of the object? How deep should it go? What if your object happens to contains one of these built-in keys? This all can be done by writing a custom validator factory function and reuse it in your project.

**Comment by Axure** [comment]
The crucial defect of this syntax is that type info about props of `Object` type is permanently lost in the standard Vue component definition syntax. It's impossible even for libraries like [vue-tsx-support](https://www.npmjs.com/package/vue-tsx-support) to recover the TypeScript definition, unless you wrap your own syntax over the simple object definition, as is done in [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator).
