### ISSUE TITLE
How to write a type declaration(TypeScript DefinitelyTyped/d.ts) for a Vue component

### ISSUE THREAD

**Issue by linkFly6** [vuejs/vue#7267]
### What problem does this feature solve?
With vue support for typescript getting better, we want to be able to get some of our older vue components( and SFC) to support typescript declarations(DefinitelyTyped/d.ts).

But I didn't find the information, so I came here to ask for help.

Does the Vue development team have any future development plans for the typescript type declaration?

### What does the proposed API look like?
Create a type declaration file for a Vue component( or SFC)

```typescript
import { VNode } from 'vue'

interface MyComponentOptions<V extends VNode> {
  data?: {
    value: number;
    name: string;
  };
  props?: {
    defaultValue: number;
    defaultName: string;
  };
  event?: {
    changeValue: (value: number) => void
    changeName: (name: string) => void
  }
}

export = MyComponentOptions
```

**Comment by ktsn** [comment]
We already support it officially. https://vuejs.org/v2/guide/typescript

**Comment by linkFly6** [comment]
I'm talking about how to write typescript DefinitelyTyped(d.ts) for Vue SFC written using JavaScript.

Rather than how to support typescript.

**Comment by ktsn** [comment]
Then, you should ask your question in [the official forum](https://forum.vuejs.org/), [chat room](https://discordapp.com/invite/HBherRA) or StackOverflow as the issue list is exclusively reserved for bug reports and feature request 😄
