### ISSUE TITLE
使用 VSCode 时, Vue.component 中的 this 类型 在 .ts 中是正确的, 但在 .js 文件却是 any 类型

### ISSUE THREAD

**Issue by shynome** [vuejs/vue#7281]
### Version
2.5.12

### Reproduction link
[https://github.com/shynome/typescript-vue-component-this-type-lost-in-js-sandbox](https://github.com/shynome/typescript-vue-component-this-type-lost-in-js-sandbox)

### Steps to reproduce
- git clone https://github.com/shynome/typescript-vue-component-this-type-lost-in-js-sandbox vue-sandbox

- cd vue-sandbox

- npm i 

- npm t

### What is expected?
src/test1.ts(6,10): error TS2540: Cannot assign to 'x' because it is a constant or a read-only property.

src/tes21.js(6,10): error TS2540: Cannot assign to 'x' because it is a constant or a read-only property.

### What is actually happening?
src/test1.ts(6,10): error TS2540: Cannot assign to 'x' because it is a constant or a read-only property.

---
使用 vscode 查看就会看到, 在 .js 文件中 this 的类型为 any 类型, 明明是同样的内容,但类型检查的结果却不一样, 让人感觉奇怪

**Comment by yyx990803** [comment]
这个不属于 core 管的范畴了，请去社区提问。
