### ISSUE TITLE
Provide/Inject fails with polyfilled Symbol

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#7284]
### Version
2.5.12

### Reproduction link
[https://jsfiddle.net/hirokiosame/dronjdzm/16/](https://jsfiddle.net/hirokiosame/dronjdzm/16/)

### Steps to reproduce
Run code in IE11.

Either remove the `<wrapper>` from the `Parent` component on L25 or change the Symbol into a String on L9 and it will work fine.

### What is expected?
For it to print "Message from parent: Hello World from Parent"

### What is actually happening?
Doesn't receive the injection.
<img width="901" alt="screen shot 2017-12-20 at 2 49 51 am" src="https://user-images.githubusercontent.com/1075694/34171110-8abd07e8-e530-11e7-9737-aa3c95e93fb3.png">

**Comment by yyx990803** [comment]
Symbol isn't even supported in IE11. Are you using a polyfill?

**Comment by hirokiosame** [comment]
@yyx990803 
Yeah, checkout the Externals section; it's using babel-polyfill 6.26.0

**Comment by hirokiosame** [comment]
I'm hesitant to say that it's an issue with the Symbol polyfill specifically since it works when I change the `<wrapper>` from the Parent component on L25 to a `<div>`.
