### ISSUE TITLE
"npm run dev" is taking too long (Laravel webpack)

### ISSUE THREAD

**Issue by tareqtms** [vuejs/vue#7293]
### Version
2.5.11

### Reproduction link
[http://v2.restosupply.com](http://v2.restosupply.com)

### Steps to reproduce
I am using Vue with Laravel, as it is there by default. I have 18 vue components and 4 JS files (for separate vue instances) and 4 css files to be processed by webpack. Previously, "npm run dev" took a few seconds to create the js files, but "npm run prod" was taking like over a minute. But recently I updated vue to latest version (2.5.11) and it started taking too long for "npm run dev", it's taking like around 2 minutes for each run. Even "npm run prod" is taking lower time than it.

### What is expected?
"npm run dev" should take a few seconds

### What is actually happening?
"npm run dev" is taking too long

**Comment by yyx990803** [comment]
This most likely has nothing to do with Vue's version number, please investigate this in the build tool chain (starting from mix).
