### ISSUE TITLE
custom event emit by the v-if component yet trigger the v-else component listener

### ISSUE THREAD

**Issue by mqli** [vuejs/vue#7294]
### Version
2.5.13

### Reproduction link
[https://codepen.io/posva/pen/baeJzd?editors=1111](https://codepen.io/posva/pen/baeJzd?editors=1111)

### Steps to reproduce
  define a custom component witch emit custom event;
  use v-if v-else create 2 component instances;
  on first instance use v-on listen the custom event, the second DONOT;
  toggle the v-if condition;
  emit the custom event on the second instance

### What is expected?
the listener on the first instance not been triggered

### What is actually happening?
the listener on the first instance been triggered

**Comment by posva** [comment]
Replaced the repro with a correct one (use the non minified version it warns you about problems)
As a workaround for the moment, add a `key` attribute on the button 🙂
