### ISSUE TITLE
Computed property maybe a bug or my misunderstanding

### ISSUE THREAD

**Issue by sergeyMelentyev** [vuejs/vue#7297]
### Version
2.4.2

### Reproduction link
[https://github.com/sergeyMelentyev/Vue_Prime/blob/master/question.vue](https://github.com/sergeyMelentyev/Vue_Prime/blob/master/question.vue)

### Steps to reproduce
Hello!
Please check my small report, maybe it will be helpful.
I have a component, that receive an array of objects as a props.
I have two computed property (sortedByMetro and sortedByAvailable) in order to display two results to the user.
Inside each computed property I take this.stores from props and sort it.
As you can see in my example, I add "const temp" constant in order to make shallow copy of incoming props. In this case everything works great and I receive results I was looking for.
BUT if I take away "const temp" from each computed property and try to sort array of objects from props itself (this.stores.sort()) I end up with crush in vue dev tools and browser stop responding, no console error is visible.

vue 2.4.2.
Chrome Version 64.0.3282.24 (Official Build) beta (64-bit)

Maybe it will be usefull, maybe not.
Best regards.

### What is expected?
Hello!
Please check my small report, maybe it will be helpful.
I have a component, that receive an array of objects as a props.
I have two computed property (sortedByMetro and sortedByAvailable) in order to display two results to the user.
Inside each computed property I take this.stores from props and sort it.
As you can see in my example, I add "const temp" constant in order to make shallow copy of incoming props. In this case everything works great and I receive results I was looking for.
BUT if I take away "const temp" from each computed property and try to sort array of objects from props itself (this.stores.sort()) I end up with crush in vue dev tools and browser stop responding, no console error is visible.

vue 2.4.2.
Chrome Version 64.0.3282.24 (Official Build) beta (64-bit)

Maybe it will be usefull, maybe not.
Best regards.

### What is actually happening?
Hello!
Please check my small report, maybe it will be helpful.
I have a component, that receive an array of objects as a props.
I have two computed property (sortedByMetro and sortedByAvailable) in order to display two results to the user.
Inside each computed property I take this.stores from props and sort it.
As you can see in my example, I add "const temp" constant in order to make shallow copy of incoming props. In this case everything works great and I receive results I was looking for.
BUT if I take away "const temp" from each computed property and try to sort array of objects from props itself (this.stores.sort()) I end up with crush in vue dev tools and browser stop responding, no console error is visible.

vue 2.4.2.
Chrome Version 64.0.3282.24 (Official Build) beta (64-bit)

Maybe it will be usefull, maybe not.
Best regards.

**Comment by sergeyMelentyev** [comment]
I am deal with 200 objects inside incoming props array. Each object have about 10 keys and 3 steps deep at it maximum.

**Comment by diego-lipinski-de-castro** [comment]
Props are not mutable, the recommended approach is to clone your props to your data when you need to change it. Far from that, I dont know what makes the browser crash, tbh I dont even know what is happening after that but in anyway it should just give an error in the console, and this should be a problaly a bug.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by sergeyMelentyev** [comment]
Hello, Diego! Thank you for your answer.
I know that props should stay untouched and I should not mutate it.
Until now I thought that Array.prototype.sort() is confirmed to pure function approach and will return new sorted array without mutating the first one.
My bad, because Array.prototype.sort() will mutate an input array.
And I dont know why, but two or more computed properties with Array.prototype.sort() method inside will crush you browser and vue dev tool.

As I sad before, no console error is given in this way, browser is just stop responsing.

**Comment by sergeyMelentyev** [comment]
![error](https://user-images.githubusercontent.com/11035478/34253037-0172b3b6-e657-11e7-9c32-481ee0531c93.jpg)

**Comment by sergeyMelentyev** [comment]
System memory usage skyrocketed to almost 95% while trying to reproduce this issue, than browser crashed and memory is freed up. You can check blue line on my screen print.
![memory](https://user-images.githubusercontent.com/11035478/34253486-da7075ee-e658-11e7-890b-2d06450ff2f9.jpg)

**Comment by diego-lipinski-de-castro** [comment]
This happen when the program run into an incoming infinite loop, pretty sure, happened to me sometimes

**Comment by sergeyMelentyev** [comment]
I wonder why this could happen?
As far as I can judge computed properties should act like everything is JS - run to completion. First of all one computed property should be evaluated, and then another one. Why do I have an infinite loop in my case, I can not figure it out.

**Comment by diego-lipinski-de-castro** [comment]
No idea, put your computed into a method and test, its easier to debug, and also, return void 0 looks weird to me, isnt that causing it? Maybe return false would maybe be better, not sure

**Comment by sergeyMelentyev** [comment]
Check this out, will be helpful:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

**Comment by sergeyMelentyev** [comment]
I rewrite my component logic using method calls for sorting data instead of computed props, and my result pass all tests, works great even if I stupidly trying to mutate props or if I wisely make a shallow copy of incoming array from props and sort the result.
Now I have to figeout why everyone using VUE.JS cannot use two or more computed property that mutate props and why it is trying to destroy all my system memory.

**Comment by Akryum** [comment]
> My first computed prop mutate props

You really shouldn't do that. Computed properties shouldn't have any side effects. There is [an ESLint rule](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-side-effects-in-computed-properties.md) to help you prevent that from happening in your code.

**Comment by sergeyMelentyev** [comment]
I always was aware that props must be treated immutable from inside of child component point of view and make this exact case just by mistake.
From official docs "... you should not attempt to mutate a prop inside a child component. If you do, Vue will warn you in the console."
All I am trying to say is "Vue will warn" is not working if props are reference type (Array) and more to say your browser is going to crash from infitite looop with tons of memory leack if there are 2+ computed properties that depand on same props. Just maybe you should add more red warnings in docs for this case.

**Comment by sergeyMelentyev** [comment]
thanks to everyone for doing this great vue-job :)

**Comment by diego-lipinski-de-castro** [comment]
Yeah, that's happening because V8 canno't say while compiling either while interpreting that a infinite loop is going to happen.
