### ISSUE TITLE
filter的适用场景是什么，和直接用methods有什么区别

### ISSUE THREAD

**Issue by Qunc** [vuejs/vue#7305]
### What problem does this feature solve?
比如说我现在要将后端传来的时间戳转换成北京时间，我应该用filter还是methods写方法？有什么区别吗，比如说在性能上的区别？

### What does the proposed API look like?
无

**Comment by javoski** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
