### ISSUE TITLE
Allow to reference registered components in 'extends' property

### ISSUE THREAD

**Issue by steffans** [vuejs/vue#7310]
### What problem does this feature solve?
A registered component could be referenced by its identifier when using the `extends` property. Currently it only works if you set a component directly, so in order to get a registered component it would look like this:

```
{
  extends: Vue.component('myComponent') 
}
```

### What does the proposed API look like?
However a shorter syntax could be by just using a string to reference a previously registered component.

```
{
  extends: 'myComponent'
}
```

**Comment by yyx990803** [comment]
I think this may lead to subtle issues regarding the timing when a component is defined/extended vs. when the global one is registered. I prefer to keep it explicit as it is now.
