### ISSUE TITLE
Vuejs $event target return undefined and the wrong html node

### ISSUE THREAD

**Issue by YounesKeraressi** [vuejs/vue#7316]
### Version
2.5.13

### Reproduction link
[https://gist.github.com/YounesKeraressi/0ad9cb960f34861b59995995d41d6e5c](https://gist.github.com/YounesKeraressi/0ad9cb960f34861b59995995d41d6e5c)

### Steps to reproduce
try to figured out the problem in the $event.target , i think it lag

### What is expected?
return the id on the clicked element form $event.target , is there a way to use Vuejs function's inside javascript onclick not v-on:click event like this , onclick="VueFn(this.id);" // wanted to receive the current clicked id without the $event, its says that VueFn not define. thx in advance

### What is actually happening?
it works but when i click faster it return empty id and the wrong tag

---
when i click on tabs slowly it works just fine but when i click little bit faster in the app.vue at line 39 is returning an empty id and the line 40 it excepted to return the a element but it return the i tag

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

BTW, you can just write `@click="swap"`. Vue will pass the `$event` for you

**Comment by YounesKeraressi** [comment]
@posva  thx for y response , but if $event.target.id not returning clicked id every time when i clicking fast on the tabs , so if this is not a bug what we'll call it then? like the $event.target not event catch the target node in a giving time, anyway thx for your answer i ll try another way to do it

**Comment by posva** [comment]
Keep in mind `$event` is just a native event, so the problem you're having is probably not related to Vue here

**Comment by YounesKeraressi** [comment]
@posva  thx , yeah got ya but when i used onclick="console.log(this.id)"  not "v-on:click" it work even with fast clicks but when using $event.target.id or $event.toElement or $event.srcElement  its not working most of the times when i fast click its looks like the DOM didn't existed in the mean time,  its probably Vuejs's doing inner stuffs then couldn't catch the id $event.target ,hope y got this, so yeah thx for your time
