### ISSUE TITLE
vue.js - recursive components doesn't get updated when using nested array from raw json

### ISSUE THREAD

**Issue by ueharajohji** [vuejs/vue#7317]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/znedj1ao/9/](https://jsfiddle.net/znedj1ao/9/)

### Steps to reproduce
I am trying to create a tree with add function using computed data. I used the tree-view example in vuejs official homepage and combine it with the computed function that I created but found no luck in implementing it. I've been trying to solve this for 4 days already and still no luck so I am here trying to look for help.

### What is expected?
When you click the add symbol  in the end of the list it will call the addChild function and it will successfully append the data.

### What is actually happening?
the data gets appended but the recursive component is not reactive

**Comment by yyx990803** [comment]
As we stated in the issue helper instructions, the issue list is not the place to seek help. Please use the forum or the Discord chat.
