### ISSUE TITLE
'Duplicate keys detected: ...' error with same keyed children inside a v-fored template

### ISSUE THREAD

**Issue by mathieumure** [vuejs/vue#7323]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/56zfwbe5/1/](https://jsfiddle.net/56zfwbe5/1/)

### Steps to reproduce
- Open the [jsfiddle  demo](https://jsfiddle.net/56zfwbe5/1/)
- Open your console
- Run the demo
- now you should see an error like this: [Vue warn]: Duplicate keys detected: 

### What is expected?
Children inside a repeated `<template>` should share the same keys as they should both re-render if the target element changes.

### What is actually happening?
Errors are raised with the message : [Vue warn]: Duplicate keys detected is raised.

---
## Cause

This behavior is linked to [this PR](https://github.com/vuejs/vue/pull/7200) and was also references in [this issue](https://github.com/vuejs/vue/issues/3810#issuecomment-351361476)

## Workaround
You could avoid this error by adding some prefix / suffix
```html
<template v-for="it in items">
    <li :key="it.id   '-label'">{{it.label}}</li>
    <li :key="it.id   '-separator'" class="separator">&gt;</li>
</template>
```

**Comment by posva** [comment]
Unfortunately, this is expected, both elements being at the same level (under `ul`) you're telling Vue they're the same. As you said, you need to add a suffix or prefix to let Vue treat them differently
You may think it was working pre 2.5.10 because there was no warning but [it was not always working](https://github.com/vuejs/vue/issues/7199), the warning was simply missing

**Comment by mathieumure** [comment]
Thanks for the quick reply :clap:

It makes perfectly sense (now that I know `<template>` is not considered as an anonymous component by Vue) but I think a word on template and key in the doc could help others, especially when the doc said that `<template>`  "serves as an invisible wrapper." :smile:

**Comment by posva** [comment]
Contributions to docs are always welcome but I think _invisible wrapper_ is accurate and if you try to use `key` on template you also get an error, so, to me it looks we are covered but ofc open a PR on the docs if you found some case not covered 🙂

**Comment by rccoder** [comment]
@posva  Thx to Reply. It is a hard to find mistake

**Comment by KyleMit** [comment]
Borrowing from the solution here [Duplicate keys detected: { key }. This may cause an update error](https://github.com/hejianxian/vddl/issues/23),

You can include the index as part of your v-for directive and then make a composite key including that:

```
<div v-for="(item, i) in items"
     :key="`${i}-${item.id}`"></div>
```

**Comment by YeisonTapia** [comment]
Hello, this is the solution I found while finding a better way, or the core of vue solves it:

```
<component 
	:key="index+10"
	v-for="(item, index) in items">
</component>
```

The key must unique, therefore in larger arrangements a more complex mathematical operation can be done and thus prevent the keys from duplicating.

**Comment by posva** [comment]
Using a number could be problematic and still show collisions, using a string as the comment above shows is the most secure way. I'm locking this issue as it was resolved and solutions are still very visible :)
