### ISSUE TITLE
Vue template compiler modifies viewBox attribute name

### ISSUE THREAD

**Issue by sandrosc** [vuejs/vue#7324]
### Version
2.5.13

### Reproduction link
[https://runkit.com/embed/93570emvc6gl](https://runkit.com/embed/93570emvc6gl)

### Steps to reproduce
1. Get a SVG file in HTML format
2. Call vueTemplateCompiler.compile('<svg>...</svg>')
3. Inspect resulting element, viewBox has been changed to viewbox

### What is expected?
the SVG element has an attribute where name equals 'viewBox'.

### What is actually happening?
the SVG element has an attribute where name equals 'viewbox'.

---
Reference issue in nuxt.js:
https://github.com/nuxt/nuxt.js/issues/2456

**Comment by yyx990803** [comment]
You sure? Your raw template is using `viewbox` in lowercase. If changed to `viewBox` it is properly preserved in the generated render function.

**Comment by sandrosc** [comment]
Oh right, my bad. Thanks :)
