### ISSUE TITLE
how to Support more collection data types in v-for

### ISSUE THREAD

**Issue by zDream** [vuejs/vue#7328]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/2yxxk9jkp](https://codesandbox.io/s/2yxxk9jkp)

### Steps to reproduce
for example

var map = new Map()
map.set('key1','Test1')
map.set('key2','Test2')
How do I write the v-for statement?

### What is expected?
Test1
Test2

### What is actually happening?
The result is empty

**Comment by yyx990803** [comment]
`Map` or `Set` is currently not supported, including reactivity and `v-for`. They will be supported in the new version coming early 2018.

**Comment by philBrown** [comment]
@yyx990803 not seeing reactivity support for `Map`. Is this still coming in Vue 2? 

I understand it should be possible in Vue 3 using `value`
