### ISSUE TITLE
Component reuse, but events have not been cleared

### ISSUE THREAD

**Issue by lzxb** [vuejs/vue#7329]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/lzxb/j22z2kav/](https://jsfiddle.net/lzxb/j22z2kav/)

### Steps to reproduce
- click button【Bind click】
   `count++`
- click button【Switch show】
   show button 【Not bind click】
- click button【Not bind click】
   `count++`

### What is expected?
click button【Not bind click】
`not count++`  

### What is actually happening?
click button【Not bind click】
`count++`

**Comment by schoonc** [comment]
Maybe that's applicable here https://vuejs.org/v2/style-guide/#v-if-v-if-else-v-else-without-key-use-with-caution

**Comment by lzxb** [comment]
It is now to use key to avoid component reuse

**Comment by HerringtonDarkholme** [comment]
As @schoonc has said, a key is needed to avoid component reuse.
