### ISSUE TITLE
How to support an array of objects

### ISSUE THREAD

**Issue by zDream** [vuejs/vue#7335]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/2yxxk9jkp](https://codesandbox.io/s/2yxxk9jkp)

### Steps to reproduce
<button @click="test1">Modify the properties</button>
    <div v-for="value in dataArray">
        <div class="file-size">{{value.name}}</div>
        <div>{{percent}}</div>
    </div>

<script>
  let map = []
  let data = []
  data.arr=[1,2,3]
  data.name = 'test'
  map.push(data)
  export default {
    name: 'app',
    data(){
      return{
        dataArray:map
      }
    },
    computed :{
      percent: function(){
        return map[0].arr.length;
      }
    },
    methods: {
      test1: function(){
        console.log(map[0].arr)
        map[0].arr.splice(0,1)
        console.log(map[0].arr)
    
      }
    }
  }
</script>

### What is expected?
test
2

### What is actually happening?
test3

---
why

**Comment by lyh2668** [comment]
@zDream [点这里查看文档](https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B)
1. 这个文档里面有说明，请不要直接用下标的方式操作数组
2. issues不是提问的地方...这种issues会被大佬忽略的...

**Comment by zDream** [comment]
@lyh2668 都看过了，还是解决不了，不用下标，那我如果要获取数据，而不想删除怎么做，

**Comment by wangrongkang** [comment]
`map[0].arr.splice(0,1)`
这个函数返回一个新的数组，原来`map[0].arr`的数组并没有变化
这里要改变应该这样`map[0].arr=map[0].arr.splice(0,1)`
以后别犯这种低级错误了

**Comment by LinusBorg** [comment]
properties on arrays are not reactive.

**Comment by yyx990803** [comment]
你的 `data` 是个数组不是对象，数组上的非下标自定义属性是不能触发更新的。
