### ISSUE TITLE
Allow using js constants in template event attributes.

### ISSUE THREAD

**Issue by slimee** [vuejs/vue#7341]
### What problem does this feature solve?
Remove redundant values between actions names and template attributes events.

I often use the same values for actions names and component event methods, so this will allow simplicity.

### What does the proposed API look like?
Make the following code valid. 
Currently it's impossible to reference On.UPDATE_SEARCH_TERM from @input.
A valid code will clone the constant value in the template instead of reference it.

```
<template>
    <v-text-field @input="On.UPDATE_SEARCH_TERM"/>
</template>

<script>
    import {mapActions} from 'vuex';
    import * as On from "../store/actionKeys";
    
    export default {
        name: 'minimal-exemple',
        methods: {
            ...mapActions([On.UPDATE_SEARCH_TERM])
        }
    }
    
</script>
```

**Comment by yyx990803** [comment]
``` js
created () {
  this.On = On
}
```

**Comment by LinusBorg** [comment]
Assuming `On` was available in the template like you showed here, the result would be:
```html
<v-text-field @input=" 'someStringActionName' "/>
```

Which of course is not a valid callback, so making constants avaliable in templates whatever way won't solve your problem.

**Comment by slimee** [comment]
Thanks you both

**Comment by slimee** [comment]
So I use this now:

```
<template>
        <v-text-field @input="termInputChanged" />
</template>

<script>
    import {mapActions} from 'vuex';
    import {On} from "../store/keys";

    export default {
        name: 'minimal-test',
        methods: {
            ...mapActions({
                'termInputChanged': On.UPDATE_SEARCH_TERM
            })
        }
    }
</script>
```
