### ISSUE TITLE
Time value not syncing when having empty values

### ISSUE THREAD

**Issue by evertramos** [vuejs/vue#7343]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/evertramos/jce7057g/3/](https://jsfiddle.net/evertramos/jce7057g/3/)

### Steps to reproduce
use input with type 'time', step="2" to have seconds and fill only minutes and seconds.

### What is expected?
sync the minutes and seconds I think... or even fill hour with zeros, maybe?

### What is actually happening?
not syncing

---
Not sure it´s a bug of vue or some how the browsers in general I have tested the new chrome and new firefox, old browsers seems to work fine.

Thanks for all the good work!

**Comment by kasselTrankos** [comment]
hi,
Under:
Debian 9
Chrome Versión 63.0.3239.84 (Build oficial) (64 bits)

In my console get this error:
vue.js:584 [Vue warn]: Property or method "timeValue" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.js:584

**Comment by bingo-lumity** [comment]
This has to do with how browsers emit partially-filled input[type=time] as values. If the input field is only partially-filled, its value will be a blank string. So it's agnostic to any JavaScript framework. To my knowledge there's no way of obtaining the value of a partially-filled time/date/datetime field.

**Comment by evertramos** [comment]
Thanks for the comments @kasselTrankos and @bingo-lumity.

The point is that I would like to have only minutes and seconds, no need for hours... and in this case I would rather avoid the need of forcing the user to always set '00' for hours... which can break the app.

**Comment by posva** [comment]
You'll have to create a custom component for that (or use an existing one) as this is just how browsers work. You would see the same behaviour using vanilla javascript (try getting the value in the console and you will see it's just an empty string)
