### ISSUE TITLE
V-bind bug 

### ISSUE THREAD

**Issue by ramazan793** [vuejs/vue#7353]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/86636/](https://jsfiddle.net/50wL7mdz/86636/)

### Steps to reproduce
You need to click 'Next img' and look at this border around img. Also don't forget to read explanation of bug below img.

### What is expected?
Expected nothing(Empty img, cause src=' ')

### What is actually happening?
Appearance of a gray border

**Comment by wujunchuan** [comment]
https://jsfiddle.net/50wL7mdz/86637/

the data.cards array items should be `''`, but not `' '`

**Comment by ramazan793** [comment]
The problem was not solved. As @wujunchuan said, I used '' instead ' '. Look:
https://jsfiddle.net/50wL7mdz/86647/
That's exactly my case(I try to use ajax-loader for loading images)

**Comment by javoski** [comment]
This is expected, please use `v-if`.

**Comment by ramazan793** [comment]
@javoski no, I want to use ajax-loader for temporary empty images( It's alright for my project). But this border - how can I remove it?

**Comment by javoski** [comment]
@ramazan793 This is not an issue related to Vue, you can ask questions on StackOverflow or other forums.
