### ISSUE TITLE
外链返回Vue触发事件

### ISSUE THREAD

**Issue by 961900832** [vuejs/vue#7358]
### What problem does this feature solve?
当从外链返回Vue时，可以触发相应事件对页面进行更新。例如H5支付场景，从Vue中跳转到支付宝H5页面，支付完成后，返回Vue，这时需要检查支付是否完成，这个时候需要调用一个事件来确认是否支付成功

### What does the proposed API look like?
做为生命周期事件，当从外链返回Vue时，触发相应事件

**Comment by HerringtonDarkholme** [comment]
This is a special use case where application developers should design a nofitication event. 

We are sorry but a framework cannot and should not handle this for you.
