### ISSUE TITLE
Why using isAndroid check when adding composition event listener in v-model?

### ISSUE THREAD

**Issue by LeuisKen** [vuejs/vue#7361]
### What problem does this feature solve?
The code I'm talking about is https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/directives/model.js#L42

This isAndroid check is added in this commit: https://github.com/vuejs/vue/blob/6e9d332737419501ec7a40a4d300b06cd28b35a1/src/runtime/directives/model.js

Since this event listener added when `isAndroid === false`, it will enabled when the device is PC, I wonder why vue need to do this.

Or I think if a `window.CompositionEvent` check is enough？

### What does the proposed API look like?
None.

**Comment by yyx990803** [comment]
Don't use feature requests to ask questions.

**Comment by LeuisKen** [comment]
Ok，that's my fault。But since there is only two types provided by your issue tools....
