### ISSUE TITLE
Improve the compiler's rendering of boolean attributes

### ISSUE THREAD

**Issue by Edensan** [vuejs/vue#7362]
### What problem does this feature solve?
My issue is related to the previously discussed problem here: https://github.com/vuejs/vue/issues/981

As of now, the way the compiler deals with boolean attributes is quite counter-intuitive,
https://jsfiddle.net/50wL7mdz/86806/

When enabled, attributes get different treatments, both quite hard to make sense of to be honest:
- There is a list of pre-registered booleans that will render as { "key": "key" }
- Other, "unknown" booleans will render as { "key": "" }

Which means that:
- Custom attributes are expected to consider an empty string as a "true" statement (hard to reason about since no language/library will actually cast an empty string to a "true" statement, making is quite an implicit behaviour)
- Pre-registered boolean attributes will behave differently from unknown ones, which is quite unexpected

I believe it would be quite simple/common for an inexperience developer to be confused as to why the boolean attribute is so hard to differentiate from a normal string attribute (can't be checked for "false" or "true"), and thus the only reliable way right now would be to manually declare booleans as strings with hardcoded (user-declared) accepted values (myBoolean="true | 1 | false | 0" instead of the more elegant standard boolean) which just promotes more unstable/unreliable code.

### What does the proposed API look like?
For the sake of user-friendliness, code stability and overall safety I would suggest this to be changed in the future.

My proposal would be to just handle all booleans the same (unless they require a documented custom default value for the sake of compatibility?):
- If a boolean attribute is declared, render is as ( "key": "true" } or even better { "key": true } for improved performance when passing it to the native implementation
- If not declared, don't need to render it

**Comment by posva** [comment]
> My proposal would be to just handle all booleans the same (unless they require a documented custom default value for the sake of compatibility?

That's what Vue does at the moment. Some attributes need to have explicit values for some browsers to work (probably IE). At the end both [syntaxes are valid](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes)

> If a boolean attribute is declared, render is as ( "key": "true" } or even better { "key": true } for improved performance when passing it to the native implementation

Unfortunately, that is just how the browser works, attributes are always stored as strings.

> If not declared, don't need to render it

That's what happens right now.

To put it in a nutshell: we cannot remove current behaviour of adding values as it would break browser support but we should not make attributes always have a string value because that would differ with native HTML attribute handling

PS: make sure to use a lowercase attribute in the HTML, as the browser with convert it anyway (`my-boolean`)

**Comment by Edensan** [comment]
Reading from the spec,

> A boolean attribute without a value assigned to it (e.g. checked) is implicitly equivalent to one that has the empty string assigned to it (i.e. checked=""). As a consequence, it represents the true value.

> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

Those two points absolutely blow my mind. Implicit behaviors... Yuck.
If no choice, then no choice.

Anyway, that helped me understand the inner logic better, thanks.
