### ISSUE TITLE
Using .async and watch at the same time can cause a dead cycle error

### ISSUE THREAD

**Issue by chenweiqun** [vuejs/vue#7365]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/61l2w1zjwk](https://codesandbox.io/s/61l2w1zjwk)

### Steps to reproduce
Using .async and watch at the same time

### What is expected?
Execute once

### What is actually happening?
Repeat execution

**Comment by JounQin** [comment]
That's because your prop `queryParams` which is created in template and changed every time remoteData updated, then it will trigger `queryParams` watcher again and again.

**Comment by yyx990803** [comment]
As @JounQin explained, using a object literal in prop binding causes the child component to think the prop has changed on every render.

This behavior will likely be improved in the future, but for now what you can do is manually compare new and old values in your watcher to avoid unnecessary updates.
