### ISSUE TITLE
`v-model` did not handle CompositionEvent on Android

### ISSUE THREAD

**Issue by LeuisKen** [vuejs/vue#7367]
### Version
2.5.13

### Reproduction link
[https://codepen.io/LeuisKen/pen/ZvydmK?editors=1010](https://codepen.io/LeuisKen/pen/ZvydmK?editors=1010)

### Steps to reproduce
1、Chrome 63 on Android, select the input tag;
2、Use IME, such as Google Japanese in example;
3、Inputing contents.

![screenrecorder-2018-01-03-11-22-53-570](https://user-images.githubusercontent.com/7701575/34508361-4a714380-f079-11e7-8ebb-e38fa8c6125f.gif)

### What is expected?
Update data only when compositionend event fired, according to issue:
https://github.com/vuejs/vue/issues/5158#issuecomment-286133373

### What is actually happening?
See the screen shot in `Steps to reproduce`, v-model sync the input data when compositionend not fired.

---
**Suggestion:** Replacing `isAndroid` check in code https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/directives/model.js#L42 with `window.CompositionEvent`.

**Comment by LeuisKen** [comment]
针对修复建议，给出了pr：https://github.com/vuejs/vue/pull/7368

**Comment by HerringtonDarkholme** [comment]
Thanks, it sounds reasonable. Any suggestion? @ktsn @kazupon ? OP suggests that v-model should only update value after `CompositionEnd` if composition happens, as discussed in https://github.com/vuejs/vue/issues/5158#issuecomment-286133373. This especially affects Japanese Input on Android, other IME like Google Chinese input doesn't exhibit the problem at all.

The Android check dates back long ago. It looks like we just leave it untouched in the code base.

**Comment by LeuisKen** [comment]
Translate to English for more extensive discussion.
Thank you for your reasonable reply and respect.

**Comment by b-jan** [comment]
Hi there, 

I am actually developing an application (in Nuxt.js) where I need the exact behaviour you reported.

My application has not the expected behaviour on Android. I need the v-model binding to behave when composing on Android keyboard. On Iphone, everything is working. How can we fix that?

Thank you :)
