### ISSUE TITLE
手势

### ISSUE THREAD

**Issue by wsygdiv** [vuejs/vue#7371]
### Version
2.5.13

### Reproduction link
[https://github.com/wsygdiv/vue2.0-m/src/components/demo/details/demoDetailsBigImage.vue](https://github.com/wsygdiv/vue2.0-m/src/components/demo/details/demoDetailsBigImage.vue)

### Steps to reproduce
vue2.0可用那些手势库，vue-touch讲解看不懂

### What is expected?
提供解答

### What is actually happening?
提供可用手势库

**Comment by yyx990803** [comment]
看不懂请好好学英语

**Comment by wsygdiv** [comment]
I just want to know what the Gesture library i can use
