### ISSUE TITLE
the Gesture library

### ISSUE THREAD

**Issue by wsygdiv** [vuejs/vue#7372]
### Version
2.5.13

### Reproduction link
[https://github.com/vuejs/vue/issues/](https://github.com/vuejs/vue/issues/)

### Steps to reproduce
I just want to know what the Gesture library i can use.

### What is expected?
recommend more the Gesture library

### What is actually happening?
my project need the  Gesture library

---
i can't understand the methods of vue-touch

**Comment by javoski** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by lovetingyuan** [comment]
It is not related to the vue project, you need just read the document of popular gesture libs carefully
