### ISSUE TITLE
It would be better add an alias elem to el

### ISSUE THREAD

**Issue by xtuer** [vuejs/vue#7377]
### Version
2.5.13

### Reproduction link
[http://google.com/no-link](http://google.com/no-link)

### Steps to reproduce
var vm = new Vue({
    el: '#app', // 这里比较喜欢用 elem，el 短了些，能否给 el 加一个别名 elem?
    data: {}
});

### What is expected?
var vm = new Vue({
    elem: '#app', // 这里比较喜欢用 elem，el 短了些，能否给 el 加一个别名 elem?
    data: {}
});

### What is actually happening?
el > elem

**Comment by yyx990803** [comment]
说实话，这没有什么意义...

**Comment by xtuer** [comment]
相对于 el 来说只是个人更喜欢 elem，意义针对于不同的人不一样。

**Comment by JounQin** [comment]
自己喜欢加个 mixin 就好了啊
https://jsfiddle.net/fb8yn393/

**Comment by yyx990803** [comment]
添加一个 api 需要对大部分用户产生实际价值，不是说就因为一个人喜欢就要加 api 的。
