### ISSUE TITLE
Support module in methods options

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue#7378]
### What problem does this feature solve?
As the app is growing bigger and bigger , we can divide the method option into small modules , and each module can do their own things, this can help us do work more clear.

### What does the proposed API look like?
```javascript
....
mounted: {
 this.init.initUI();
},
methods: {
   init: {
    initUI() {
   //do some work
}
   },

}
...
```

**Comment by yyx990803** [comment]
As the app grows bigger, you should split into more components instead of cramming more methods into the same component.
