### ISSUE TITLE
使用provide / inject ，组件使用多次时，后被添加的子组件，inject值错乱

### ISSUE THREAD

**Issue by sunzongzheng** [vuejs/vue#7380]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/sunzongzheng/6xe4mtc2/9/](https://jsfiddle.net/sunzongzheng/6xe4mtc2/9/)

### Steps to reproduce
请看jsfiddle的demo。
页面上显示的值为子组件的inject的值，初始值是正确的。
点击add后，各添加了一个子组件，inject的值是都是最后一个provide的值

### What is expected?
inject的值正常

### What is actually happening?
后被添加的子组件，inject的值不正常

**Comment by jkzing** [comment]
应该用function作为provide的值:

``` js
Vue.component('parent', {
  name: 'parent',
  template: `<div><slot></slot></div>`,
  provide() {
    return {
      eventBus: null
    }
  }
})
```

原因类似[data-Must-Be-a-Function](https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function)

**Comment by sunzongzheng** [comment]
thanks
