### ISSUE TITLE
value bindings and $event.target.value

### ISSUE THREAD

**Issue by corbosman** [vuejs/vue#7384]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/corbosman/nx23b239/1/](https://jsfiddle.net/corbosman/nx23b239/1/)

### Steps to reproduce
Run the jsfiddle, select the value in the select box, check the console. The event value is a string, not an object.

### What is expected?
$event.target.value to be the selected object

### What is actually happening?
It is a string saying [object ,object]

---
Since vue2 supports objects as value bindings for select boxes, I was expecting the event to return an object.

**Comment by yyx990803** [comment]
This is expected behavior because DOM inout elements automatically stringifies anything set to its `value` property.
