### ISSUE TITLE
Generated style not passing through shadow root boundary.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue#7385]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/ppWdEX?editors=1010](https://codepen.io/anon/pen/ppWdEX?editors=1010)

### Steps to reproduce

Seems that Vue doesn't consider what happens when a Vue component is mounted inside of a shadow root.

The component's style gets placed into the `<head>` of the web app, and therefore the style is not able to style the elements generated by the Vue component that are inside the shadow root.

Here's a reproduction:

This pen works:

https://codepen.io/saawsan/pen/jayzeq

and this one doesn't:

https://codepen.io/anon/pen/ppWdEX

As you can see the app works (click the buttons) but nothing is styled.

### What is expected?
The app should be styled.

### What is actually happening?
It isn't because the styles are placed in the `<head>` and they don't propagate into the shadow root.

---

Is there a way to configure Vue to place the `<style>` element as a sibling of the rendered output, or somewhere else? I need the generated `style` to be placed inside the shadow root, otherwise it has no effect (`scoped` or not).

**Comment by trusktr** [comment]
If there is a way to configure `<style>` instances to be placed next to the DOM generated by the component instance, that would be sweeeeeeeeeeet.

It would mean that we could keep styles from cascading into child components using ShadowDOM: https://github.com/vuejs/vue-loader/issues/957 (see [comment](https://github.com/vuejs/vue-loader/issues/957#issuecomment-355460348)).

**Comment by trusktr** [comment]
Alright, I've thought of a workaround but haven't tried it yet:

1. Set vue-loader's `extractCSS` option to `true`.
1. Extract styles using `webpack-plugin-extract-text` to some location.
1. Knowing the filename, we can `<link>` it into our shadow roots. This duplicates the styles and each shadow root will have a bunch on unnecessary styles for other components, but at least it will work.

An official solution would be great. I've no idea yet what that could be.

**Comment by posva** [comment]
It's not that Vue doesn't consider it, it's that Shadow DOM is designed that way. Vue does not move your style around. It cannot know what to move anyways...
You can, however, insert the style right next to the element you mont to make it work like described in this [article](https://css-tricks.com/playing-shadow-dom/) https://codepen.io/posva/pen/opGMrq

And please, provide a smaller repro next time, that todo list was unnecessary to showcase the problem, it will save both of us time 😄 

As you said, it could also be handled at a bundler level, maybe with a loader on top of vue-loader

Closing since it's not something that can be solved in Vue core

**Comment by trusktr** [comment]
@posva Thanks for the insight! I'll make shorter pen next time.

The thing is, what I'm doing, is converting a Vue component into a Custom Element with SkateJS, [like this](https://github.com/skatejs/skatejs/issues/1289#issuecomment-355460128), so I don't have access to the style that was inside that SFC.

I looked at the imported component object, but I don't see the style content anywhere. Did I miss it?

That'd be super helpful because then my `VueElement` tool could easily just inject that into the shadow root. Any thought on Vue-loader adding that to the component spec that gets exported from a .vue file?

I do see the `_scopeID` in the imported object, so what I could do at runtime is extract those rules from the stylesheet based on the ID and inject only those styles in the ShadowDOM, but that's heavier.

**Comment by trusktr** [comment]
Ah, look at `styleElement.sheet.rules`, doesn't seem like it'll be too difficult! I'll give that a go.

**Comment by yyx990803** [comment]
Components generated with `vue-loader` are designed for non-shadow-dom usage for the moment. There will likely be an alternative loader that generates a web component directly.

**Comment by trusktr** [comment]
I got the styles working in the shadow roots. What I'm doing is I just copying the `CSSRule`s from the global `document.styleSheets` into a new `<style>` element inside the shadow roots. I only copy the rules that match with `_scopeIds` of components that are rendered inside a given shadow root.

What I implemented is [vue-web-component](https://github.com/trusktr/vue-web-component), which meets requirements that [vue-custom-element](https://github.com/karol-f/vue-custom-element) was [not able to](https://github.com/karol-f/vue-custom-element/issues/74):

1. Elements are instantiated only once
1. Elements are nestable and composable
1. Elements distribute as expected with ShadowDOM.
1. Elements generated from the tool otherwise work exactly as you'd expect from a Custom Element without knowing or caring that the internal implementation uses Vue.

**Comment by crx4** [comment]
Thanks for inspiration guys, I figured out a solution. 
Did seperate the Vue's style to a single sass file and then add an entry point for webpack as:
```
    entry: {
        'inject/app': './inject/App.scss',
    },
```
Finally add the compiled css to the shadow root via `link` tag.
```
    let link = document.createElement('link');
    link.type = 'text/css';
    link.rel = 'stylesheet';
    link.href = 'app.css';
    shadowRoot.appendChild(link);

    shadowRoot.appendChild(ankiContainer);
```
