### ISSUE TITLE
父组件中部分组件发生状态改变，会引发子slot组件render两次@2.5.13

### ISSUE THREAD

**Issue by chenfengjw163** [vuejs/vue#7386]
### Version
2.5.13

### Reproduction link
[https://codepen.io/chenfeng163/pen/VyMrQy](https://codepen.io/chenfeng163/pen/VyMrQy)

### Steps to reproduce
父组件中部分组件发生状态改变，会引发子slot组件render两次

### What is expected?
父组件其他组件状态更新的时候不要影响slot组件的render

### What is actually happening?
子组件渲染两次

**Comment by jkzing** [comment]
You may get your answer here [issuecomment-303677477](https://github.com/vuejs/vue/issues/5727#issuecomment-303677477).

**Comment by posva** [comment]
Duplicate of #5727
as said by @jkzing
