### ISSUE TITLE
`component is="input"` does not handle v-model bindings correctly

### ISSUE THREAD

**Issue by theoephraim** [vuejs/vue#7393]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/ccxub2Lu/](https://jsfiddle.net/ccxub2Lu/)

### Steps to reproduce
- Type in first input
- Type in second input
- Type in third input
- Type in first input again

### What is expected?
The 3rd input no longer updates its value after being used once.

### What is actually happening?
- First input is a regular input field using v-model.
- Second input is a custom component bound using `v-model` and inside has an input with `:value` and `@input`.
- Third input is same as second but uses a `component` with `is='input'`.

It seems some v-model related handling of inputs is not being applied to the `component is='input'` case

---
I am authoring some reusable form components for my application.
Ran into this while treating text inputs and textareas identically, and using a `component :is='tagType'`

From my application, it seems that the component is receiving the new `value` prop, but for some reason, it is not updating the actual value in the DOM.

I am happy to try to fix it, but would appreciate someone pointing me in the right direction, as I have not looked at the internal vue code at all yet.

**Comment by yyx990803** [comment]
With `<component :is>`, Vue doesn't know what element will end up being, so the `value` is bound as an **attribute** instead of a **property**. You need to explicitly bind it as a property using `:value.prop`.

**Comment by theoephraim** [comment]
Once again, when confronted with something strange, Vue to the rescue with a totally reasonable answer (and it's even in the docs)! Could be worth adding a note in the guide somewhere, but I'm not entirely sure where.

Thanks for the quick reply and for building Vue! You have given me a reason to enjoy front-end development again :)
