### ISSUE TITLE
Optionally allow scoped lots to behave like normal ones

### ISSUE THREAD

**Issue by Frondor** [vuejs/vue#7397]
### What problem does this feature solve?
I find myself creating a simple list component, where I want to be able to provide multiple entries for a single `<slot name="subtitle" :item="item" />`.
If I want to provide multiple "subtitle" elements (like have 2 subtitles in an item), I can write
```html
  <some-list>
    <div slot="subtitle">Something</div>
    <div slot="subtitle">Else</div>
  </some-list>
```
And this will work just fine, both subtitles are going to stack over each other, but what if I don't want them to be static, but use _scoped data_ instead? Yes, I can use *scoped slots* but no, they won't stack anymore, only last one will be rendered:
```html
  <some-list>
    <div slot="subtitle" slot-scope="props">{{ props.item.address }}</div>
    <div slot="subtitle" slot-scope="props">{{ props.item.phone}}</div> <!-- only this one shows up-->
  </some-list>
```

You can reproduce this problem here: **https://jsfiddle.net/mw0ng93s/5/** (uncomment that line)

And since `this.$scopedSlots.subtitle` returns a single vnode, I can't either use a render function to "manually" replicate normal slot stacking behavior for scoped ones.

### What does the proposed API look like?
Probably something like `<div slot="subtitle" slot-scope="props" slot-stack>`

**Comment by yyx990803** [comment]
You can just do

``` html
<some-list>
  <template slot="subtitle" slot-scope="props">
    <div></div>
    <div></div>
  </template>
</some-list>
```

I don't really see duplicated scoped slots with the same name being necessary or even a good idea.
