### ISSUE TITLE
Last webpack template update broke assets and routing

### ISSUE THREAD

**Issue by AlexAlabyev** [vuejs/vue#7398]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/XVzRJY](https://codepen.io/anon/pen/XVzRJY)

### Steps to reproduce
Run default installation to create a new project:

`vue init webpack projectName`

Run dev server:

`npm run dev`

Now webpack doesn't allow to put images in assets folder created by Vue CLI and you have to transfer all the images into "static" folder (which took me an hour to figure out. I would imagine it will confuse a lot of people)

It's not the only issue after the last update, I've created one more about routing:

https://github.com/vuejs/vue-router/issues/1965

### What is expected?
To not confuse people

### What is actually happening?
Confuses people and requires to transfer all the images from assets to static folder (on dev server `npm run dev`)

**Comment by yyx990803** [comment]
Please post template related issues to the [template repo](https://github.com/vuejs-templates/webpack).

**Comment by AlexAlabyev** [comment]
@yyx990803 sorry, my bad
