### ISSUE TITLE
No valid versions available for pinkie-promise

### ISSUE THREAD

**Issue by Ahren110** [vuejs/vue#7403]
### Version
2.5.13

### Reproduction link
[https://www.npmjs.com/package/pinkie-promise](https://www.npmjs.com/package/pinkie-promise)

### Steps to reproduce
npm install --global vue-cli   ||   cnpm install --global vue-cli

### What is expected?
Vue can work

### What is actually happening?
Vue cannot work

---
https://user-images.githubusercontent.com/22902717/34643953-76d5e1a0-f368-11e7-8387-4eec127ee541.png
https://user-images.githubusercontent.com/22902717/34643962-9404cd40-f368-11e7-8e9e-c8434509fe0c.png

**Comment by Akryum** [comment]
https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by Ahren110** [comment]
Thank you for your hard work

**Comment by Akryum** [comment]
vue-cli can be installed again. 🙌

**Comment by Ahren110** [comment]
![image](https://user-images.githubusercontent.com/22902717/34644199-c2396cbc-f36c-11e7-827d-6049ae003342.png)
![image](https://user-images.githubusercontent.com/22902717/34644200-c976e964-f36c-11e7-8d77-542fd2bd9699.png)

**Comment by Ahren110** [comment]
Do you have to reinitialize the existing project?
