### ISSUE TITLE
Dynamic input type no longer works with v-model and :value at the same time.

### ISSUE THREAD

**Issue by sourenaraya** [vuejs/vue#7404]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/KZyJyy](https://codepen.io/anon/pen/KZyJyy)

### Steps to reproduce
Open JS console and see `[Vue warn]: Error compiling template:

<div>                 <div  v-for="testitem in testlist" >                  <label>{{ testitem }}</label>                  <input :type="inputtype" :value="testitem" v-model="testvalue"/>                </div>                <pre>{{ testvalue }}</pre>            </div>

- :value="testitem" conflicts with v-model on the same element because the latter already expands to a value binding internally

(found in <Root>)`

### What is expected?
Template compiled without errors, just like in Vue 2.5.3

### What is actually happening?
Errors while template compilation. On codepen this still renders component, but webpack wont build bundle because of this error.

---
This code worked on 2.5.3, https://codepen.io/anon/pen/opomGr

**Comment by jkzing** [comment]
This warning message was added in [v2.5.5](https://github.com/vuejs/vue/releases/tag/v2.5.5), so that you were not able to see it on `v2.5.3`.

**Comment by sourenaraya** [comment]
Ok, what do we do about it? I want this dynamic input :type.

**Comment by Justineo** [comment]
Actually I think the warning shouldn't be emitted here. For inputs with dynamic type binding, we may just skip the conflict check because the actual `type` is not available yet in the compiler.

I made a PR to resolve this issue: #7406.
