### ISSUE TITLE
Document that v-model doesn't work with inheritAttrs

### ISSUE THREAD

**Issue by davidhewitt** [vuejs/vue#7407]
### What problem does this feature solve?
As per https://github.com/vuejs/vue/pull/6327 it sounds like a number of people are expecting v-model to work with inheritAttrs / $attrs / $listeners. I was also caught out by this and assumed a bug until I did further googling and found that rejected PR.

I didn't see anything in the docs that suggested to me that what I was trying wouldn't work.

Would it be possible to document that this isn't expected to work, maybe at https://vuejs.org/v2/api/#inheritAttrs ?

I would have made a PR but don't have time to do it right now, perhaps if you assign to me I might get a chance at the weekend.

Cheers,
David

### What does the proposed API look like?
N/A

**Comment by LinusBorg** [comment]
Issues concerning documentation should be opened in https://github.com/vuejs/vuejs.org
