### ISSUE TITLE
vue 组件销毁

### ISSUE THREAD

**Issue by yanlibo2013** [vuejs/vue#7410]
### What problem does this feature solve?
最近做了一个项目,技术栈vuejs,vue2.0,vuex,v-echarts,elementui,但是遇到的问题是，页面在切换的时候，耗时比较长，路由值会马上变过去，但是页面差不多需要差不多4秒，才可以切换过来，我仔细排查了一下，发现从使用v-echarts的页面，切换到不使用图表的页面时，才会出现这样的情况，并且这段时间间隔是出现在组件生命周期，beforeDestroy，destroyed，也就是组件在销毁开始，销毁结束会这个时间段回话3到4秒的时间，仅在使用v-echarts的页面会出现这样的情况,因此页面在切换的时候体验不是很好，我尝试解决的办法是给页面添加loading,具体做法是,在组件beforeDestroy这个函数开启loading,在下一个页面组件的mounted之后，关闭，但是我发现并没有出现自己想要的效果,具体是beforeDestroy，destroyed这两个函数期间，及时acion调用开启loading,也没有效果，这段时间仍无任何响应，请问这样的情况如何处理，有那些比较好的解决方案

### What does the proposed API look like?
无

**Comment by yyx990803** [comment]
这不是 feature request。规则写得很清楚，不要用 issue 问问题。

**Comment by yanlibo2013** [comment]
这样的问题应该在什么地方交流，多谢

**Comment by yanlibo2013** [comment]
确实遇到这样的问题，给我一个大概的方向也可以，多谢

**Comment by jkzing** [comment]
@yanlibo2013 [https://forum.vuejs.org/c/chinese](https://forum.vuejs.org/c/chinese)去这儿交流吧～

**Comment by yanlibo2013** [comment]
好，多谢
