### ISSUE TITLE
The extends option behavior is same with mixins

### ISSUE THREAD

**Issue by ustbhuangyi** [vuejs/vue#7412]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/x7non3yrj4](https://codesandbox.io/s/x7non3yrj4)

### Steps to reproduce
See the console

### What is expected?
CompB created

CompA created

### What is actually happening?
CompA created

CompB created

---
As the Doc says, `extends` option is similar to `mixins`, the difference being that the components own options takes higher priority than the source component being extended.
However, the fact is that the source component being extended has higher priority, which is same with mixins.

See the source code of Vue.js
``` js

export function mergeOptions (
  parent: Object,
  child: Object,
  vm?: Component
): Object {
  // ...
  const extendsFrom = child.extends
  if (extendsFrom) {
    parent = mergeOptions(parent, extendsFrom, vm)
  }
  if (child.mixins) {
    for (let i = 0, l = child.mixins.length; i < l; i  ) {
      parent = mergeOptions(parent, child.mixins[i], vm)
    }
  }
  // ...
}
```
I think the logic of `extends` and `mixins` is almost the same.

**Comment by HcySunYang** [comment]
I think that's correct, higher priority doesn't mean priority to calling. But the behavior of mixin and extends seems same.

**Comment by posva** [comment]
The order seems correct to me. Think about classes, you always call `super` right at the beginning.
It would also be a breaking change, so not feasible right now

**Comment by ustbhuangyi** [comment]
@posva , so what's the difference between `mixin` and `extends`? May be the Doc needs to be modified?

**Comment by posva** [comment]
Contributions to improving docs are always welcome 🙂 ! Make sure to open a PR there if you think it  could be clearer

**Comment by ArStah** [comment]
@posva, what is the reason to put two options, that do the same?

**Comment by ViYaYaYa** [comment]
maybe "mixins" takes higher priority than "extends" than the source?
