### ISSUE TITLE
Transition bug with multiple ul

### ISSUE THREAD

**Issue by stephanebressani** [vuejs/vue#7418]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/stephane86/50wL7mdz/88648/](https://jsfiddle.net/stephane86/50wL7mdz/88648/)

### Steps to reproduce
```
<transition name="fade">
    <div v-for="(item_ul, index_ul) in ul" :key="index_ul">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item" v-for="(item_li, index_li) in item_ul.ul" :key="index_li">
                <li-menu-gestion-pages :li="item_li"
                                       @event-child-collapse="mEventCollapse" />
            </li>
        </ul>
    </div>
</transition>
```

### What is expected?
Transition

### What is actually happening?
With this code, the transition is ok for the first element of array ul[0], but the second ul[1] is hidden (without <transition /> , it's work's)

---
Solved with :
```
    <transition name="fade">
        <ul class="nav nav-pills flex-column" v-if="ul[0]">
            <li class="nav-item" v-for="(item_li, index_li) in ul[0].ul" :key="index_li">
                <li-menu-gestion-pages :li="item_li"
                                       @event-child-collapse="mEventCollapse" />
            </li>
        </ul>
    </transition>

    <transition name="fade">
        <ul class="nav nav-pills flex-column" v-if="ul[1]">
            <li class="nav-item" v-for="(item_li, index_li) in ul[1].ul" :key="index_li">
                <li-menu-gestion-pages :li="item_li"
                                       @event-child-collapse="mEventCollapse" />
            </li>
        </ul>
    </transition>
```

**Comment by LinusBorg** [comment]
As documented `<transition>` can only have one child element. You should have a look at `<transition-group>`

**Comment by LinusBorg** [comment]
The transition only applies to the direct child, which is the div. You should rather use a transition group.

Also, your reproduction code is not functional, so this issue does not fullfil the requirements.

**Comment by stephanebressani** [comment]
Thank you ```<transition-group>``` solved the problem
