### ISSUE TITLE
The change of property in App.vue affect the property in vuex store

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue#7419]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/hej8Lax9/](https://jsfiddle.net/hej8Lax9/)

### Steps to reproduce
We suppose i have the below object in vuex store:

data : [
{ name: 'john', lname: 'doe'},
{ name: 'george', lname: 'doe'}
]

In App.vue i have the follow prop

data: this.getFetchedData //returns the prop of vuex store

but when i do the follow

this.data.splice(0,1)

### What is expected?
It is expected to remove the first element from data prop in App.vue.Only

### What is actually happening?
But besides that is also removed the first element from vuex store property

---
I think it is Javascript issue Or i dont know if i am doing something wrong.Check the jsfidlle link to understand what i mean

**Comment by sqal** [comment]
Just copy the array before modifying it:

`this.prov1 = this.prov2.slice()`

And next time, please ask this kind of questions on the [forum](http://forum.vuejs.org/), [Discord channel](https://vue-land.js.org/),or [StackOverflow](https://stackoverflow.com/tags/vue.js). :)

**Comment by Akryum** [comment]
https://stackoverflow.com/questions/518000/is-javascript-a-pass-by-reference-or-pass-by-value-language
