### ISSUE TITLE
Possibility pause <transition>

### ISSUE THREAD

**Issue by SzymonLisowiec** [vuejs/vue#7420]
### What problem does this feature solve?
An example of application is a timeout bar with pause on hover.

### What does the proposed API look like?
```
<template>
  <transition :pause="isPause">
    <div @mouseenter="isPause = true" @mouseleave="isPause = false"></div>
  </transition>
</template>

<style>
.div {
  width: 100%;
  height: 5px;
  background: #f00;
}

.v-enter-active {
  transition: width 5s;
}

.v-enter {
  width: 100%;
}

.v-enter-to {
  width: 0;
}
</style>
```

**Comment by LinusBorg** [comment]
You can't "pause" CSS transitions. 

If you use JS to do the transitions instead, it's certainly possible (depoending on the animation lib used), but outside of the scope of Vue - it has topbe solved by a 3rd party library or you, the developer.

**Comment by yyx990803** [comment]
Unfortunately I don't think this is even technically possible.
