### ISSUE TITLE
Allow unescaped attribute value

### ISSUE THREAD

**Issue by MrSlide** [vuejs/vue#7421]
### What problem does this feature solve?
In some situations it can be desirable to have HTML entities in the value of attributes. A good example would be obfuscating an email address from bots by replacing each character in the `href` attribute value with the unicode character entity for each character, so that something like `mailto:john.doe@example.com` would become `&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#106;&#111;&#104;&#110;&#46;&#100;&#111;&#101;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#99;&#111;&#109;`. Vue is escaping the `&` in each of the character entities, making the code invalid.

I've been trying to do this in user land with filters, directives, and even using the `v-html` directive. Only managed to get some success with the `v-html` directive by creating the whole element and children that needs the attribute value to be unescaped, but that is highly impractical, especially when there are child elements in the mix.

### What does the proposed API look like?
Use a modifier for the v-bind directive:

`v-bind.unescaped="rawValue"`

**Comment by posva** [comment]
The escaping you're using happens in HTML but if you put it in js it doesn't work: `document.getElementsByTagName('a').href = '&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#106;&#111;&#104;&#110;&#46;&#100;&#111;&#101;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#99;&#111;&#109'`. It's not Vue escaping it
That's why you found it working only with `v-html`

**Comment by MrSlide** [comment]
I see. Thanks for the clarification.

**Comment by drosendo** [comment]
You can use, a method to work:

```
    unicodeToText: function(string) {
    var txt = document.createElement("textarea");
    txt.innerHTML = string;
    return txt.value;
}
```
