### ISSUE TITLE
Add "cloneSlot" directive.

### ISSUE THREAD

**Issue by lliendo** [vuejs/vue#7423]
### What problem does this feature solve?
Take a child component (through the default slot) and recursively clone it allowing the user to define a child "sample" in a declarative way. Consider for example the following template declaration:

```javascript
<formset-manager>
  <formset-row>
    <formset-input name="aSampleInput"></formset-input>
    <formset-input name="anotherSampleInput"></formset-input>
  </formset-row>
</formset-manager>
```

The "formset-manager" component takes a "formset-row" definition as an "example". Internally it should clone as many "formset-row" components as the user demands (Note that not only a plain "formset-row" component should be cloned but its children as well, that means that the sample provided should be cloned recursively). I was unable to get or build a clean solution for this use case using scoped slots. I believe that the solution for this use case implies that the user needs to fully implement a the render function for the "formset-manager" component.

### What does the proposed API look like?
The proposed API could look something like this (for the following template also consider the previously described "formset-manager" template):

```javascript
const template = `
    <div>
        <div>        
            <cloneSlot v-for="(row, rowIndex) in rows"
                :initial-data="row"
                :row-index="rowIndex"
                :show-delete-row-button="showDeleteRowButton(rowIndex)"
                :formset-prefix="formsetPrefix"
            ></cloneSlot>
        </div>

        <button type="button" v-on:click="addRow()" v-if="showAddRowButton()">Add</button>
    </div>
`;
```

The key to the above example is the proposed "cloneSlot" directive. For the above shown example it takes a "formset-row" child and clones it an arbitrary number of times (in this case dictated by the v-for). The "rows" used in the "cloneSlot" is defined in "data" (so when "rows" changes the appropriate number of "formset-rows" are cloned/generated).

**Comment by LinusBorg** [comment]
I'm sorry, I 'm having difficulty understanding what part of this cannot be done with scoped slots. I'll try to explain what I assume that you want:

You are passing props to the "cloneSlot" component (not a directive), and I *think* you want those props passed on to each instance of the form-row component?

And the difference to doing this with `scoped-slots` is that you don't want to pass those props like this:
```html
<formset-manager>
  <formset-row 
     slot-scope="props" 
     :initial-data="props.initialData" 
     :row-index="rowIndex"
      //and so on...>
    <formset-input name="aSampleInput"></formset-input>
    <formset-input name="anotherSampleInput"></formset-input>
  </formset-row>
</formset-manager>
```
... what do you want to happen then? that the props are being passed kind of "in the background"?

Then you could use `provide/inject` for that.

**Comment by lliendo** [comment]
> ... what do you want to happen instead? that the props are being passed kind of "in the background"?

Exactly. Because all those props are generated by the "formset-manager". The user shouldn't need to specify the template as you did in the last example because the user knows nothing about those props at all. Note that "cloneSlot" doesn't exist (it was just the proposed way to clone the default slot N times rescursively, that's why I put that in the "What does the proposed API look like?" section). 

Maybe I haven't given enough context the problem I'm trying to solve. I'm trying to build a set of generic components in VueJS that handle Django formsets. For that purpose I have split the problem basically in three components with well defined responsibilities. 

The `formset-manager` is responsible of generating whatever the user provides as children to the "formset-manager" component (in the example the formset-manager would generate N "formset-row" components). Some properties are exclusively generated by the formset-manager and passed down to whatever was defined as its children (to be precise I need to pass: a row index, initial data, a prefix and a boolean value).

The `formset-row` component is in charge on just cloning/generating whatever was defined as its children (in this example just 2 inputs) and again there are some props that need to be passed down to its children and are generated by the "formset-row" component exclusively. Also "formset-row" is responsible for hiding/displaying its delete button accordingly and acts as a proxy component (or mediator) between the "formset-manager" and in this example with two "formset-input" components (but this functionality is irrelevant to what I'm trying to explain, I mention this not to think that "formset-row" just generates its children and nothing more).

The `formset-input` is just a regular text input field which notifies changes to its parent.

I'm still having difficulties understanding how a scoped slots solves this problem without doing this:

```javascript
<formset-manager>
  <formset-row 
     slot-scope="props" 
     :initial-data="props.initialData" 
     :row-index="props.rowIndex"
      //and so on...>
    <formset-input name="aSampleInput"></formset-input>
    <formset-input name="anotherSampleInput"></formset-input>
  </formset-row>
</formset-manager>
```

That is: **without** specifying `:initial-data="props.initialData"`, `:row-index="props.rowIndex"`, etc. in the above template. The above template should be:

```javascript
<formset-manager>
  <formset-row>
    <formset-input name="aSampleInput"></formset-input>
    <formset-input name="anotherSampleInput"></formset-input>
  </formset-row>
</formset-manager>
```

I've raised this issue because I've read other people's solutions to similar use case (in the VueJS forum, SO and other websites) and they all fall back on implementing a render function plus a custom JS function to clone vnodes (I've never seen something different, no scoped slots with provide/inject) so I assumed that that was the only why to go and I felt that this use case is simple enough yet there's no way to code it in a straightforward way.

Even implementing the render function (I'm currently experimenting this path) I got stuck on how to call "createElement" and pass custom props to this.$slots.default (which I think is not possible but correct me if I'm wrong).

If you still need me to provide you a more detailed implementation of what I'm trying to achieve I can set up a JSFiddle with a not-working implementation, comment everything in a detailed way and further discuss if what are you proposing (scoped-slot plus p/i) fits this use case.

Thanks for your time!

**Comment by LinusBorg** [comment]
Thanks for this detailed input, that's something to work with. I'Äm short on time right now, but will trx and answer in long form later today.

**Comment by yyx990803** [comment]
This is too niche a use case to add first-class template syntax for. It also risks making the slot syntax ambiguous (same usage outside, but different potential ways the consuming component can make use of the slot).

That said, this should be doable with render functions. You essentially treat `this.$slots.default` as meta data and construct new VNodes based on it (manually cloning then mutating the props as needed). It just requires you to become familiar with render functions and the VNode interface. However, further discussion on how exactly that can be done is out of the scope for issues.
