### ISSUE TITLE
methods | event is not defined | in Firefox

### ISSUE THREAD

**Issue by AlexAlabyev** [vuejs/vue#7427]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/MrVpgL?editors=1010](https://codepen.io/anon/pen/MrVpgL?editors=1010)

### Steps to reproduce
- open reproduction link in Chrome and Firefox

- click the image

- see console error in Firefox

### What is expected?
To work

### What is actually happening?
Throws and error in Firefox

**Comment by yyx990803** [comment]
Please open issues that involves 3rd party libs at their repos first.
