### ISSUE TITLE
Watchers aren't triggrered on nested changes

### ISSUE THREAD

**Issue by SiNEXiST** [vuejs/vue#7428]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/vpRZLB](https://codepen.io/anon/pen/vpRZLB)

### Steps to reproduce
Click the button in the reproducer.
The content is being passed to the child component corrrently. However, the watcher is never getting triggered even tho the value changed.

As a workaround you can delete the property and set it again (uncomment line 28).

### What is expected?
The watcher should get called as the value is changing.

### What is actually happening?
The watcher is not getting called as the object itself isn't changed.

**Comment by posva** [comment]
You need to use the option `deep`: https://vuejs.org/v2/api/#vm-watch
