### ISSUE TITLE
能否在底层支持谷歌推出的FlutterEngine，进而做一个Vue Native ？

### ISSUE THREAD

**Issue by qinyang1980** [vuejs/vue#7430]
### What problem does this feature solve?
Flutter Sdk(https://github.com/flutter/flutter)
是一个可以用单一代码base跨三个平台(Android, IOS, Fuchsia)的库，即write once，run everywhere。
但是可惜的是，语言是Dart，而且依赖包也是dart专有的。语言不熟悉，生态也很单薄。

Flutter的评价：
https://www.zhihu.com/question/50156415

### What does the proposed API look like?
我的建议是Vue可以在Flutter Engine（https://github.com/flutter/engine) 之上开发Vue Native，
这样大家就可以用Vue来写Native应用了，谢谢！

**Comment by buyuxing** [comment]
可以看看weeks，它就是一套基于vue的可以三端统一的库

发自我的vivo智能手机

"Andy.Qin" <notifications@github.com>编写：

**Comment by qinyang1980** [comment]
Flutter的实现机制跟RN和weex都不同。它依赖一个用C++写的FlutterEngine，从底层画出每一个控件。
而且经过GPU加速，跟RN和weex的performance不在一个级别。我已经试过了。

我觉得以FlutterEngine做底层，一套代码，即可以同时跨三端(未来可能更多)，并且性能更优。

**Comment by gubaojian** [comment]
好想法，希望启动能参与

**Comment by gubaojian** [comment]
Weex强烈推荐

**Comment by lenvonsam** [comment]
强力推荐vue-native

**Comment by denvey** [comment]
也有同样的想法，也许社区可以试试

**Comment by YourksChan** [comment]
好想法啊，那就可以通吃了，强烈要求！！

**Comment by fushilu06** [comment]
有计划吗

**Comment by nowind** [comment]
> 
> 
> > Flutter的实现机制跟RN和weex都不同。它依赖一个用C++写的FlutterEngine，从底层画出每一个控件。
> > 而且经过GPU加速，跟RN和weex的performance不在一个级别。我已经试过了。
> > 我觉得以FlutterEngine做底层，一套代码，即可以同时跨三端(未来可能更多)，并且性能更优。
> 
> QT了解下不？

qt太巨量了,各端体验也不一致,ui构建也不是申明式的,主c++语言,写起来吃力.Flutter只要底层支持绘制,无论你用啥图形库,都能将它生成可执行包

**Comment by chenxyzl** [comment]
强烈支持，配合dart x86 aot。前后端就真的完美了

**Comment by mcooly** [comment]
> vue-native
vue-native 是基于RN的，也证明了 vue-flutter的可行性

**Comment by xmsz** [comment]
目前有没有什么方案啊

**Comment by liyujiang-gzu** [comment]
> 目前有没有什么方案啊

阿里巴巴已经出了“Kraken(Flutter-like)”，基于 FlutterEngine + Rax.js，目前在集团内部使用，尚未开放。所以基于 FlutterEngine + Vue.js 实现跨端跨平台是完全可以的。

**Comment by liyujiang-gzu** [comment]
> 想法不错，但是现在没有资源去做这样的事。建议还是研究研究 weex 和 NativeScript 吧。

阿里巴巴集团内部已经推出“Kraken(Flutter-like)”，基于FlutterEngine + Rax.js 实现跨端跨平台，所以将Vue.js替换Rax.js就搞定了。VueJS威武，一统江湖。。。

**Comment by LiXunGuan** [comment]
刚看到阿里开源的 北海Kraken 已经支持 https://openkraken.com

**Comment by liyujiang-gzu** [comment]
> 刚看到阿里开源的 北海Kraken 已经支持 https://openkraken.com

阿里巴巴效率挺高德玛，才半年不关注`Kraken`都支持`Vue`和`React`了

**Comment by kobeng** [comment]
> > 刚看到阿里开源的 北海Kraken 已经支持 https://openkraken.com
> 
> 阿里巴巴效率挺高德玛，才半年不关注`Kraken`都支持`Vue`和`React`了

我最近试用了kraken vue上面的使用组件 在kraken都不支持渲染  离目标还是很远
