### ISSUE TITLE
能不能直接指定一个元素去渲染数据，而不是通过vue框架

### ISSUE THREAD

**Issue by ZiQiangWang** [vuejs/vue#7433]
### What problem does this feature solve?
我在开发一个新功能，需要50ms一次刷新数据，但是只是更新两个特定元素，在框架下进行数据更新的时候，效率非常低

### What does the proposed API look like?
使用指令的形式，比如v-special，可以直接设置对应元素的值

**Comment by yyx990803** [comment]
把这两个数据包在一个组件里就行了
