### ISSUE TITLE
V-model doesn't work properly with checkbox

### ISSUE THREAD

**Issue by AndreasCag** [vuejs/vue#7437]
### Version
2.5.13

### Reproduction link
[http://jsfiddle.net/503ucqL9/](http://jsfiddle.net/503ucqL9/)

### Steps to reproduce
1. Click to some checkbox.

### What is expected?
Only one checkbox is selected.

### What is actually happening?
Two checkboxes are selected.

---
It happens only when there are two or more element with same content.

**Comment by yyx990803** [comment]
When you bind value to objects, they are compared using shallow equality. You need to give each option a unique property so that they can be differentiated.
