### ISSUE TITLE
Custom errors for prop validators

### ISSUE THREAD

**Issue by tristan-shelton** [vuejs/vue#7438]
### What problem does this feature solve?
I'm loving the way that prop specification and validation works compared to React, but one thing I wish is that custom validator functions could explain *why* validation failed, so that you don't have to hunt down the validator function and follow its logic to check your data.

### What does the proposed API look like?
```javascript
props: {
  foobar: {
    type: Object,
    required: true,
    validator: function(value) {
      // Default error message
      if (!value.foo) return false;

      try {
        JSON.parse(value.foo);
      }
      catch (e) {
        // Custom message
        return 'foobar: foo property isn\'t valid JSON!';
      }

      // Validated
      return true;
    }
  }
}
```

**Comment by yyx990803** [comment]
Well you can just `console.error` yourself in your validator function...
It could be nicer if this can be sent to the built-in error/warn handler so you get the nice component trace, which is something we will likely add in 2.6.

**Comment by dietergeerts** [comment]
Any progress on when this will be added?
