### ISSUE TITLE
$emit passes arrays by reference

### ISSUE THREAD

**Issue by morficus** [vuejs/vue#7441]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/morficus/7f56ogLm/1/](https://jsfiddle.net/morficus/7f56ogLm/1/)

### Steps to reproduce
Once you open the JSFiddle link:

1. Mark some check boxes from with in the "child" container
2. Click the "notify parent" button - this will emit an event
3. Watch how the counter in the parent event updates
4. Now click the "Pop It!" button - this just does a ".pop" on the local data
5. Notice now the check-boxes in the child component are affected...

### What is expected?
When clicking the "Pop It!" button, the counter in the parent should go down with out affecting the child component selection.

### What is actually happening?
The child component selection is being affected.

---
It appears that when passing an array as an additional argument to `$emit` ... only a reference to the array is passed around. I tried doing the same with objects in place of arrays and was not able to create the issue.

I was expecting for a copy of the array to be passed with `$emit`, not a reference.

This seems like a way to "cheat" two-way binding between parent-child components :-p

**Comment by yyx990803** [comment]
This is just how JavaScript works. If you want to pass a copy, you need to copy it yourself.
