### ISSUE TITLE
Data passing bug

### ISSUE THREAD

**Issue by edwinwong90** [vuejs/vue#7446]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/edwindeveloper90/41fu2a9p/](https://jsfiddle.net/edwindeveloper90/41fu2a9p/)

### Steps to reproduce
fill in the modal setting form and save. the player component will display according to your settings. That still works fine, but second time editing the modal setting form input WITHOUT saving. the player component reacts immediately with the latest settings.

### What is expected?
everytime editing the modal setting the player component shouldn't react immediately until I save

### What is actually happening?
the child component (modal setting) is mutating parent component (score counter), even though the props is not object or array.

---
I do read this https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow, and also know that only object and array will auto mutate parent due to JavaScript are passed by reference. 

Therefore, in my reproduction source, you will see I use v-bind="settings" to the child component instead of v-bind:settings="settings". But, somehow still mutating parent data. Why?

**Comment by antonin-arquey** [comment]
It's coming from the object passed by reference.
If you change : 
```javascript
this.$emit('save', this.modalSetting)
```
By : 
```javascript
this.$emit('save', JSON.parse(JSON.stringify(this.modalSetting)))
```
where we deep copy the object via JSON.parse (you could do it via Object.assign or with an external library too), you can see that your code achieve the desired result. 
I don't know if there is a better method than making a deep copy in this case. You can take a look at VueX which is a way to store data between unrelated components.

**Comment by javoski** [comment]
Just as what @antonin-arquey said, this is not a bug.

**Comment by edwinwong90** [comment]
Alright, it works! Thanks
