### ISSUE TITLE
vue事件能否加上类似jquery的命名空间?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#7447]
### What problem does this feature solve?
vue事件能否加上类似jquery的命名空间?

### What does the proposed API look like?
vue事件能否加上类似jquery的命名空间?

**Comment by posva** [comment]
If you're referring to https://api.jquery.com/event.namespace/. You can already namespace events with `namespace:event`. Vue gives you a plain event so it's familiar to anyone who has already dealt with native events in js
