### ISSUE TITLE
$emit和$on能否加上同时绑定或者触发多个事件?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#7448]
### What problem does this feature solve?
$emit和$on能否加上同时绑定或者触发多个事件?

### What does the proposed API look like?
$emit和$on能否加上同时绑定或者触发多个事件?

**Comment by posva** [comment]
Please, be more precise when opening feature request. The FR is so short, translator gives me meaningless sentences. And you have done this multiple times before

**Comment by yyx990803** [comment]
`$on` 早就支持绑定多个了： https://vuejs.org/v2/api/#vm-on
