### ISSUE TITLE
watch多个属性指向到同一个函数能否更加简洁的写为一行代码?

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#7449]
### What problem does this feature solve?
watch多个属性指向到同一个函数能否更加简洁的写为一行代码?

### What does the proposed API look like?
watch多个属性指向到同一个函数能否更加简洁的写为一行代码?

**Comment by posva** [comment]
You receive the data that changed in the callback. If you watch multiple properties in one call, you will not know which one triggered the watcher
