### ISSUE TITLE
Why not embedding class interpretering to the render function's first parameter?

### ISSUE THREAD

**Issue by somarlyonks** [vuejs/vue#7455]
### What problem does this feature solve?
I may just want to add a class to the VNode, by now I have to draw it:
```Javascript
render: function (h) {
  return h(
    'div',
    {
      'class': 'my-class-name',
    },
    this.VNodeContent,
  )
}
```

I am supposing that a selector-like style `'div.my-class-name'` might helps a little?

Or is there any alternative methods?

### What does the proposed API look like?
```Javascript
render: fucntion (h) {
  return h(
    'div.my-class-name',
    this.VNodeContent,
  )
}
```

**Comment by LinusBorg** [comment]
I do't think we want to put additional logic into the tagname string, no.

**Comment by yyx990803** [comment]
That extra parsing hurts performance even if users do not use this feature. You can add your own h wrapper to do that though.
