### ISSUE TITLE
.vue文件的this指向问题

### ISSUE THREAD

**Issue by xuwenqing2014** [vuejs/vue#7457]
### Version
2.5.13

### Reproduction link
[https://github.com/xuwenqing2014/vue-issue/blob/master/src/components/HelloWorld.vue](https://github.com/xuwenqing2014/vue-issue/blob/master/src/components/HelloWorld.vue)

### Steps to reproduce
在.vue文件中import由webpack打包过的js，会报错，因为在打包好的js中，webpack添加了闭包代码：function() { return this; }()，这里面的this按道理是指向window的，但是在.vue文件中，这里的this是undefined，有什么解决方案么？

### What is expected?
function() { return this; }()这段代码的this指向window

### What is actually happening?
function() { return this; }()这段代码的this是undefined

**Comment by Kingwl** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Strict_mode

**Comment by xuwenqing2014** [comment]
你好，给我这个链接是什么意思啊？让我取消vue-cli的严格模式？这个不管用

**Comment by jkzing** [comment]
@xuwenqing2014 给你这个链接的意思是，在严格模式下，想用window就明确地写window，别写this...
