### ISSUE TITLE
VueSSRClientPlugin bug caused by CopyWebpackPlugin.

### ISSUE THREAD

**Issue by dbFlower** [vuejs/vue#7461]
### Version
2.5.13

### Reproduction link
[https://github.com/dbFlower/vue-hackernews-2.0](https://github.com/dbFlower/vue-hackernews-2.0)

### Steps to reproduce
Clone the repo, and then `npm i`, `npm run dev`.   view source code of `http://localhost:8080` . 
`/dist/static/test/for/plugin/bug/test-for-vue-ssr-bug.js` is prefetched by client plugin.

### What is expected?
All resources copied by CopyWebpackPlugin shouldn't be prefetched.

### What is actually happening?
Client plugin prefetches all the resources copied by CopyWebpackPlugin.

---
Just use ClientPlugin before CopyWebpackPlugin. [#L42](https://github.com/dbFlower/vue-hackernews-2.0/blob/solved/build/webpack.client.config.js#L42)。

```javascript
[  
    // other plugins.
    new VueSSRClientPlugin(),
    new CopyWebpackPlugin([{
      from: path.resolve(__dirname, '../static'),
      to: 'static/test/for/plugin/bug/'
    }]),
]
```

================================================

当我在同时使用VueSSRClientPlugin和CopyWebpackPlugin时，我发现SSR bundle出来的源码总是将CopyWebpackPlugin 所复制的资源全部prefetch了一遍。 后来发现是VueSSRClientPlugin在CopyWebpackPlugin之后调用所导致的。

现在我暂时将VueSSRClientPlugin放在CopyWebpackPlugin之前调用以解决这个问题。 希望VueSSRClientPlugin可以指定哪些资源预先加载，哪些资源不要预先加载。

我现在的应用场景是使用AMD加载monaco编辑器还有一些其他的资源。如果插件如此智能的帮我自动预获取的话，AMD就失去了意义。

**Comment by yyx990803** [comment]
https://ssr.vuejs.org/en/api.html#shouldpreload
