### ISSUE TITLE
VirtualDOM中，为什么可以往文本节点下插入子节点呢？？

### ISSUE THREAD

**Issue by berwin** [vuejs/vue#7470]
### Version
2.5.13

### Reproduction link
https://github.com/vuejs/vue/blob/f2b476d4f4f685d84b4957e6c805740597945cde/src/core/vdom/patch.js#L545-L546

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

---

大神您好，这行代码我没太看懂，如果 oldVnode.text 为 true 说明这可能是一颗文本节点。

为什么可以往文本节点下面插入子节点呢？

求大神解答疑惑。。。

**Comment by javoski** [comment]
下面的语句并没有在 `if` 里面。

Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
