### ISSUE TITLE
Parent component's styles will not leak into child components' SVG.

### ISSUE THREAD

**Issue by jenkey2011** [vuejs/vue#7474]
### Version
2.5.13

### Reproduction link
[https://github.com/jenkey2011/one-music](https://github.com/jenkey2011/one-music)

### Steps to reproduce
It  will always happen
I can't set the styles of svg in child component 

This the [  parent component ](https://github.com/jenkey2011/one-music/blob/master/src/components/player/player.vue#L525-L534) ,
this is the  [ child component ](https://github.com/jenkey2011/one-music/blob/master/src/base/progress-circle/progress-circle.vue#L3-L23)   

In the parent component , I set the style to SVG ， and in the page, you can see the relevant style,
as the picture shows. But it doesn't work at all!
![](https://raw.githubusercontent.com/jenkey2011/jenkey2011.github.io/master/image/Snipaste_2018-01-18_16-39-30.png)

But if i edit the current node in the browser development tools,  just hit the two spaces, it works!
as the picture shows. 
![](https://raw.githubusercontent.com/jenkey2011/jenkey2011.github.io/master/image/svg2.gif)

I also tried binding style, but it not OK，either

### What is expected?
NO expected!

### What is actually happening?
It  will always happen !

---
I can set other styles(eg. background) to the svg in child component, and it works ……
My English is not very good, the description may not be clear, you can go clone my projectand reproduce it.
Thank you！

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
Don't use your full project as a repro 😢 

---

Take a look at https://vue-loader.vuejs.org/en/features/scoped-css.html#deep-selectors
