### ISSUE TITLE
Ability to create a full and independent clone of Vue constructor

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#7475]
### What problem does this feature solve?
- multiple concurrent and independent applications (with clean independent Vue.prototype, ...)
- event bus / reactive data without global mixins/hooks pollution (eg. beforeCreate)
  - eg. vuex uses the global Vue: `this._watcherVM = new Vue()` that may be polluted by global mixins
- vue-based templating tools (server-side e-mail creation using vue template)

### What does the proposed API look like?
	Vue.cloneVue = function (Vue) {

		const clone = Vue.extend();
		clone.options._base = clone;
		clone.version = Vue.version;
		Object.defineProperty(clone, 'config', Object.getOwnPropertyDescriptor(Vue, 'config'));
		clone.util = Vue.util;
		clone.set = Vue.set;
		clone.delete = Vue.delete;
		clone.nextTick = Vue.nextTick;
		return clone;
	}

Currently `config` is kept common.

or:
```
clone = Object.setPrototypeOf(Vue.extend(), Vue);
clone.options._base = clone;
```
... but will not work on IE9

**Comment by JounQin** [comment]
Please implement it by yourself like https://github.com/vuejs/vue-test-utils/blob/dev/src/create-local-vue.js .

**Comment by posva** [comment]
This is an edge case that only a few people encounter and doesn't need to be added to Vue core since it can be extracted into a single function in a separate package.

**Comment by yyx990803** [comment]
If this can be done in userland then I don't see why it should be included by default.

**Comment by rhengles** [comment]
Why isn't this the default behaviour? What is the rationale for Vue sharing global state across VueComponents? Where can I read about this?
