### ISSUE TITLE
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.

### ISSUE THREAD

**Issue by jaubut** [vuejs/vue#7478]
### Version
2.5.13

### Reproduction link
[https://github.com/jaubut/cq2](https://github.com/jaubut/cq2)

### Steps to reproduce
yarn run dev

### What is expected?
Expect to see the facebook customer chat 

### What is actually happening?
The iframe is partially loaded.. the fb_dialog that seem to prevent the rest of the plugin to showed up

**Comment by LinusBorg** [comment]
Can you provide a little bit more background? Why do you think this is related to Vue at all?

**Comment by jaubut** [comment]
Ho, sorry maybe I should report it in the vue template.. Because I thought it would be in a config that I could allow facebook iframe to load on my site.

**Comment by LinusBorg** [comment]
I would ask the same question if you post it there. 

What makes you think that its related to the template?

**Comment by LinusBorg** [comment]
You should probably use our forum to aka for help with implementing a feature: 

https://forum.vuejs.org

**Comment by posva** [comment]
As @LinusBorg said, please, do not use your whole project as a repro. If you can boil it down into a repro, feel free to open a new issue with the repro
