### ISSUE TITLE
Template renderer and CSP

### ISSUE THREAD

**Issue by jbudz** [vuejs/vue#7479]
### What problem does this feature solve?
When context with state is provided to the template renderer an [inline script is created](https://github.com/vuejs/vue/blob/f2b476d4f4f685d84b4957e6c805740597945cde/src/server/template-renderer/index.js#L199).  It may be useful to provide a nonce that gets attached to the script tag so an unsafe-inline CSP doesn't have to be enabled.

### What does the proposed API look like?
```
renderer.renderToString({
  state: {},
  nonce: ''
})
```

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by yyx990803** [comment]
Closed via #8047
