### ISSUE TITLE
Vue SSR 渲染list 出现报错的情况

### ISSUE THREAD

**Issue by dufemeng** [vuejs/vue#7482]
### Version
2.5.9

### Reproduction link
[https://jsfiddle.net/dufemeng/d6L82txL/](https://jsfiddle.net/dufemeng/d6L82txL/)

### Steps to reproduce
这是在使用 Vue SSR 的时候出现的问题，ul 里面有两个内容几乎完全相同的li，但是上面那个会报错，错误信息如下：

`
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
`

但是第二个则不会报错，只需要在span标签后面加个空格或者换行就可以解决

### What is expected?
不会报错

### What is actually happening?
页面无法渲染

---
实际项目有些复杂，这是简化版，请谅解，我 Q 2314627598

**Comment by yyx990803** [comment]
重现不符合要求。
