### ISSUE TITLE
Add information about boolean props acting as flags to docs

### ISSUE THREAD

**Issue by VsevolodTrofimov** [vuejs/vue#7484]
### What problem does this feature solve? (this is DOCS request)
It is undocumented that if `my-component` has a boolean prop (say `my-flag`)
Writing `<my-component my-flag/>` will lead to `my-flag` being set to `true`
Which leads to 
- bugs due to `:my-flag="undefined"` being resolved as `true` 
- more verbose code by people who didn't stumble upon this fact.

### What does the proposed API look like?
Add it to the docs.

I can make a pull request for Russian and English docs, but I don't know what is the most appropriate place for this information. (maybe end of the props sections, near type validation)

**Comment by posva** [comment]
Feel free to open a PR on the docs repo https://github.com/vuejs/vuejs.org/ to propose an improvement 🙂
