### ISSUE TITLE
Multi-type props defined without value gets empty string, should be true [Boolean, String]

### ISSUE THREAD

**Issue by realcarbonneau** [vuejs/vue#7485]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/realcarbonneau/68w22cbo/](https://jsfiddle.net/realcarbonneau/68w22cbo/)

### Steps to reproduce
Define a multi-type Boolean and String Prop, call the component by specifying the prop name (without a value).

### What is expected?
Prop contains true (Boolean type)

### What is actually happening?
Prop contains an empty string

---
The sequence does not change the result, both `[Boolean, String]` and `[String, Boolean]` give the same result.  The version does not change the result either (vue version 1.0.12, 2.2.1, edge on jsfiddle)

**Comment by posva** [comment]
Hmm, looks like the PR #4539 didn't fix what it was supposed to fix. It's curious that this has been around for 1 year since 2.1.7
Also looks like #3885 didn't take into account the ordering on #3879. So ordering didn't have an impact

**Comment by alexgrozav** [comment]
Any progress on this? I'm experiencing this problem as well.
