### ISSUE TITLE
这可能是VirtualDOM中一个很隐蔽的bug

### ISSUE THREAD

**Issue by berwin** [vuejs/vue#7487]
### Version
2.5.13

### Reproduction link
https://github.com/vuejs/vue/blob/f2b476d4f4f685d84b4957e6c805740597945cde/src/core/vdom/patch.js#L545-L546

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

---

从逻辑上来看，vnode和oldVnode是同一颗节点，但vnode不是文本节点，那oldVnode也不能是文本节点，然后将vnode中的children插入到DOM中没有任何问题。

所以我判断这行代码

```javascript
if (isDef(oldVnode.text)) nodeOps.setTextContent(elm, '')
```
其实是一行永远都不会执行的代码。

如果这行代码在某些特殊情况下可以执行，那说明什么问题？？？

说明旧节点是一颗文本节点，而文本节点是没有子节点的，没有子节点把vnode的children插入到它的下面？？

所以无论从哪个方面来看，这都有可能是一个bug~

但我不敢直接提pull request，因为我不敢确定我的推断是否正确，希望提个issue来讨论一下这个问题~

**Comment by berwin** [comment]
@yyx990803 手动艾特大佬~ 😂😂😂

**Comment by yyx990803** [comment]
在 test coverage 中这一行是有被执行的。如果认为是 bug，不妨自己试着搞个重现。

**Comment by berwin** [comment]
@yyx990803 哦哦哦，我看到了这行代码，这确实不是bug，谢谢大佬指点。🤣🤣🤣

https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L292

**Comment by liaogn** [comment]
抱歉，打扰了！请教下前辈，我阅读源码的时候，读到这里也有同样的疑问，我跑单元测试test:cover 时确实能覆盖到 if (isDef(oldVnode.text)) nodeOps.setTextContent(elm, '') 这行代码，但是我看测试用例里面的vnode都是new VNode('div', {}, undefined, 'two') 这样的，tag是‘div’，同时text存在值，什么场景下存在这种情况呢，真心求教

**Comment by liaogn** [comment]
@berwin 手动艾特大佬~ 😂😂😂
