### ISSUE TITLE
Vue no rerender the view after array.splice

### ISSUE THREAD

**Issue by 13470012** [vuejs/vue#7489]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/91991/](https://jsfiddle.net/50wL7mdz/91991/)

### Steps to reproduce
When i use vue to try sort a nested array with this.data_prop.array.splice(index - 1, 0, this.data_prop.array.splice(index, 1)[0])

### What is expected?
Update in the data and view

### What is actually happening?
Only update in the data, the view is same to back step

**Comment by LinusBorg** [comment]
You are using the array index as the `key`, which doesnt' work because it changes and does *not** uniquely identify a distinct item in the array. Use a real id.

**Comment by lyh2668** [comment]
@LinusBorg Can I use like this, when I want to delete item in the array？
``` html
<div v-for="(item, index) of array" :key="item.__ob__.dep.id">
```

**Comment by LinusBorg** [comment]
1. I don't see what the `key` attribute would have to do with it. 
2. No, I jog course I can't recommend using an internal id for any

**Comment by lyh2668** [comment]
But when I loop through an array of objects, what should I use as the key value to allow me to delete an item in the array when the view is rendered in real time?
