### ISSUE TITLE
Async transformation of component spec is difficult to work with

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue#7494]
### What problem does this feature solve?
```vue
<!-- Foo.vue -->
<template><div></div></template>
<script>
  export default {
    props: [ 'bar' ]
  }
</script>
```

```js
import Foo from './Foo.vue'

console.log('props sync', Foo.props) // [ 'bar' ]

setTimeout(() =>
  console.log('props async', Foo.props) // { bar: { type: null } }
, 0)
```

The object is mutated. This is hard to work with. Can you make it constant?

Make it easy for library authors to consume and transform Vue specs synchronously.

### What does the proposed API look like?
The proposed API is to not mutate the component spec asynchronously.

**Comment by trusktr** [comment]
I bet the transformation of `props` can be done in vue-loader.

**Comment by trusktr** [comment]
This would be useful because library authors might use the spec to create other modules that do interesting things, for example a tool that generates Custom Elements from Vue components specs, where the internal rendering of the custom element content is rendered by the defined component.

People who may try to do this will want to map custom element attributes to object properties based on the `props` definition. They will need to define the standardized `observedAttributes` on the custom element classes.

The problem is, if the custom element class has to be defined asynchronously, this means that the library author can not simply export the class synchronously. They will have to provide a Promise or a callback for the end user to receive the class in order to use it. This would not be ideal.

**Comment by posva** [comment]
Foo (Component spec) is not mutated. I tested with your code samples (with poi) and it produces the same array of `props` in both logs.
Please make sure the error doesn't come from one of your dependencies/loader and provide a repro when opening a bug report

**Comment by trusktr** [comment]
I'm using vue-cli to make a basic app. The part of my code that I think triggers it is

```js
(new ( Vue.extend(Foo) ) ).$mount(target)
```

Let me push it when I get to desktop...

**Comment by trusktr** [comment]
Alright, I found what's causing it, it's simple to reproduce:

```vue
<!-- Foo.vue -->
<template><div></div></template>
<script>
  export default {
    props: [ 'bar' ]
  }
</script>
```

```js
import Foo from './Foo.vue'
import Vue from 'vue'

console.log('Foo props sync', Foo.props) // [ "bar" ]]

Vue.extend(Foo); // mutates it.

console.log('Foo props sync', Foo.props) // { bar: { type: null } }
```

**Comment by trusktr** [comment]
It's not async in this case, but it turns out that if someone is relying on a component spec, they may not have control of when someone else extends from it, therefore it becomes an async problem without a deterministic way to run logic after that's happened.

**Comment by posva** [comment]
Forgot to say but I passed on the message about `Vue.extend(Foo)` mutating the original component. I'll come back once I have a confirmation :)

**Comment by trusktr** [comment]
One solution can be to normalize the `props` in vue-loader so that the component definition is already in the normalized state when imported.

**Comment by trusktr** [comment]
I made a new issue over there: https://github.com/vuejs/vue-loader/issues/1138

**Comment by posva** [comment]
Closing this in favour of #7515
