### ISSUE TITLE
`nextTick` should return a Promise to support ES8's async/await

### ISSUE THREAD

**Issue by kogli** [vuejs/vue#7497]
### What problem does this feature solve?
There may be situations in which you have to use multiple `nextTick` calls in a single function. In this case, using ES8's async/await functionality is very useful, as it can prevent overly nested, unreadable code.

Right now, I have to use either this:

```JS
async myMethod() {

    // code before first nextTick call

    await new Promise(resolve => this.$nextTick(resolve));

    // code before second nextTick call

    await new Promise(resolve => this.$nextTick(resolve)); // ugly :(

    // code after
}
```

Or this:

```JS
myMethod() {

    // code before first nextTick call

    this.$nextTick(() => {
        // code before second nextTick call

        this.$nextTick(() => { // ugly nesting :(
            // code after
        });
    });
}
```

### What does the proposed API look like?
`nextTick` should return a Promise. It may also take a closure as a parameter for compatibility reasons.

You could then use all three variants:
```JS
    this.$nextTick(() => /* my code after */);
```

```JS
    this.$nextTick().then(() => /* my code after */);
```

```JS
    await this.$nextTick();
    /* my code after*/
```

**Comment by ktsn** [comment]
It already returns Promise when you does not specify a callback.
https://vuejs.org/v2/api/#vm-nextTick
