### ISSUE TITLE
 Does $refs have bug in Vue?

### ISSUE THREAD

**Issue by Jack-In** [vuejs/vue#7499]
### Version
2.5.13

### Reproduction link
[http://blog.jack-blog.cn/](http://blog.jack-blog.cn/)

### Steps to reproduce
<template>
    <div>
        {{count}}
        <div class="box" ref="reference">
            try
            <div class="btn">click me</div>
        </div>
    </div>
</template>
<script>
    export default {
        data(){
            return {
                
            }
        },
        mounted(){
            console.log(this.count)
            console.log(this.$refs.reference)
            this.demo()
        },
        computed:{
            count(){
                //该计算属性是直接被vuex挂载vue实例上边去的
                return this.$store.state.hi;
            }
        },
        methods:{
            demo(){
                this.$refs.reference.onclick=()=>{
                    console.log(111111111111111111222)
                }
            }
        }
    }
</script>
<style scoped>
    .box {
        width: 150px;
        height: 150px;
        border: 1px solid red;
        position: relative;
    }
    .btn {
        width: 50px;
        height: 50px;
        border: 1px solid yellow;
        background: #000;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%,-50%);
    }
</style>

### What is expected?
console.log(111111111111111110000)

### What is actually happening?
console.log(111111111111111111222)

---

Why is there a print inconsistency!

**Comment by javoski** [comment]
There's nothing to do with Vue, the number `111111111111111111222` is too big.
