### ISSUE TITLE
What about use puppeteer instead of phantomjs for e2e tests?

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [vuejs/vue#7500]
### What problem does this feature solve?
In my  [PR](https://github.com/vuejs/vue/pull/7491) I should check for existence `Function.bind`.

Does really we should carry `Function.bind` polyfill in production builds for phantomjs?

We have 2 solutions:
1. drop this code at build time
2. move e2e tests to https://github.com/GoogleChrome/puppeteer (i personally prefer this)

cons:
1. reduce vuejs size
2. better tests performance

### What does the proposed API look like?
...

**Comment by yyx990803** [comment]
This is not just about tests. Vue may need to run in PhantomJS based tools like scrapers. This is about backwards compatibility.

**Comment by dmitry-vakhnenko** [comment]
so strange `use case`. and it costs some bytes in every build.

So maybe support delete this code at building time? We rly dont need carry it for ALL users.

**Comment by dmitry-vakhnenko** [comment]
wait.

We carry polyfill for case when any vuejs site can be scrapped?
We increase bundle size for every build for ^ case?

I just didn't understood.

**Comment by LinusBorg** [comment]
As Evan said:

> This is about backwards compatibility.

It would be a breaking change, and we wont do a mjor release for this (or plan one in the near future, in general).

**Comment by posva** [comment]
FYI the extra size is small enough to be worth. It happens with multiple things that are also not supported by some browsers like Internet Explorer

**Comment by yyx990803** [comment]
Your site is built in Vue. A site scraper built with PhantomJS used to be able to scrape your site. Now with a patch update your site suddenly break in the scraper.

The tradeoff is not bytes vs. use case, it's about bytes vs. backwards compat.
