### ISSUE TITLE
Text Interplation only work for one time !! 

### ISSUE THREAD

**Issue by RezaPouya** [vuejs/vue#7503]
hi ... I have this simple component like this ... 
`Vue.component('look-up' , {
    props:{
        message:{
            type: String,
            required: false ,
        } ,
        messagetwo: String,
    },
    template:'#look-up-temp',
    data: function() {
        return {
            LableTitle: this.message,
            LableTitleTwo: this.messagetwo,
        }
    },
    
    methods: {
        
    },

    computed: {
    },

    created: function () {
       //alert(this.message);
       alert(this.messagetwo);
    }
})`

and this template : 

`  <script id="look-up-temp" type="text/x-template" >
                    <div>{{LableTitleTwo}}</div>
                    <div>{{LableTitle}}</div>
                </script> `

and my markup is like this 
`<look-up message="Component" messagetwo="C2">  
                        </look-up>`

but only first line interplation ` <div>{{LableTitleTwo}}</div>` is shown at time .... 

what's the pobolem !? 

ps : I just use vue script and I want to add extra functionality to my current project ...

**Comment by RezaPouya** [comment]
if I use this `<div>{{LableTitleTwo}} {{LableTitle}}</div>` both text are shown but if I put them in different tag , only first one will be shown ...

**Comment by leopiccionia** [comment]
One thing that can be causing this is the fact that Vue only renders one root node.

Try this:
```html
<script id="look-up-temp" type="text/x-template" >
    <div>
        <div>{{LableTitleTwo}}</div>
        <div>{{LableTitle}}</div>
    </div>
</script>
```
