### ISSUE TITLE
Unknown custom element - using Parcel, SFCs and TypeScript 

### ISSUE THREAD

**Issue by smutnyleszek** [vuejs/vue#7504]
### Version
2.5.13

### Reproduction link
[https://github.com/smutnyleszek/sicx](https://github.com/smutnyleszek/sicx)

### Steps to reproduce
1. `npm install`
2. `npm start`
3. open http://localhost:2038/

### What is expected?
Test custom element should be rendered.

### What is actually happening?
An error:
```
Unknown custom element: <test> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <App>
       <Root>
```

---
I am learning Vue, so I did rewrite this few times to try making it work. I tried lookin at all other "unknown custom element" issues here, but couldn't find any solution. I have "name" provided in children and I've put them in `components` object in parent SFC.

**Comment by yyx990803** [comment]
This is most likely an issue with Parcel's TS plugin and Vue plugin not working together properly, not a Vue core problem.

Please open the issues in those related projects instead.

**Comment by smutnyleszek** [comment]
Ok, opened issue at https://github.com/BoltDoggy/parcel-plugin-vue/issues/20 :)
