### ISSUE TITLE
computed property with getter and setter not handling camel to kebab case conversion

### ISSUE THREAD

**Issue by mcshaz** [vuejs/vue#7511]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/pf30L2fg/1/](https://jsfiddle.net/pf30L2fg/1/)

### Steps to reproduce
1. HTML contains kebab-case for e.g. as per jsfiddle: v-model="age-days"
2. Computed property defined in new vue uses camelCase, and has a getter and setter (ageDays in the jsfiddle)

### What is expected?
page loads without error

### What is actually happening?
Chrome 63 & Firefox (dev) 58 both unable to render with:
Failed to generate render function:
ReferenceError: invalid assignment left-hand side in ...

---
Changing to an all lowercase name for the html v-model attribute and the computed  property - in the case of the jsfiddle changing both to agedays fixes the problem.

**Comment by LinusBorg** [comment]
Vue doesn't handle kebap-case / camelCase in *attribute values* / *expressions*, only in *prop attribute names*,

And it doesn't do so because it makes no sense - attribute *values* are not forced lower case by the browser.
```

```
