### ISSUE TITLE
No [Vue warn] when mutating nested parent props

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue#7516]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/jbwxeunb/1/](https://jsfiddle.net/jbwxeunb/1/)

### Steps to reproduce
1. open console
2. click counter

### What is expected?
Show warning when mutating object prop

### What is actually happening?
Warning only shows up when mutating primitive props

**Comment by sqal** [comment]
https://github.com/vuejs/vue/issues/6103#issuecomment-315266712

**Comment by posva** [comment]
Duplicate of #6103
