### ISSUE TITLE
Async in templates

### ISSUE THREAD

**Issue by Radiergummi** [vuejs/vue#7520]
### What problem does this feature solve?
I'd like to propose adding async as a modifier to template directives and loops. [Svelte has this](https://svelte.technology/guide#await-blocks), and it is a breeze.  
Ideally, this would allow for using async in lists to wait for a promise to resolve before displaying the list item, and passing promises as component properties that delay rendering the component until all props have resolved.  

What problem does it solve? Well, first it would move a lot of promise complexity out of the components, keeping them lean.  
And instead of handling passed promises automatically, this would allow devs to do this manually if they need to and not break backwards compatibility.

### What does the proposed API look like?
```js
// Promised values in loops
<ul v-for="await foo in bar">
  // Use foo as expected
</ul>

// Promised props
<my-component v-bind.async:bar="foo">
```

**Comment by posva** [comment]
Adding this directly to templates would be a big overhead in template compilation but also at runtime to handle the async data. It's completely doable in userland with scoped slots though. I created a small package with basic functionality to showcase it: https://github.com/posva/vue-promise-blocks
