### ISSUE TITLE
The custom command v-focus can't be used on a mobile browser, but it can be on a PC browser.

### ISSUE THREAD

**Issue by aliceyi** [vuejs/vue#7525]
### What problem does this feature solve?
You can set the input box to get focus, in the mobile browser, the current PC browser solves this problem.

### What does the proposed API look like?
v-focus

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
