### ISSUE TITLE
Add a global config to show event handlers during development

### ISSUE THREAD

**Issue by smalllong** [vuejs/vue#7532]
### What problem does this feature solve?
During development, it's hard to find out what method is used to handle events on the element using browser's DOM inspector. If it's able to see the handler's name or content during development, it will be easier for the developer to locate the handler's code.

### What does the proposed API look like?
Set global config:
```javascript
Vue.config.showHandlers = true;
```
then the handlers can be seen in the DOM inspector:
```html
<div v-on:click='showHahaha' v-on:mouseenter='active = true'>hahaha</div>
```
since '@' is not valid in Element.setAttribute, I changed it to 'v-on:'

**Comment by posva** [comment]
Related answer: https://github.com/vuejs/vue/issues/2415#issuecomment-190494328

Personally, I think to add this only in development would potentially create other problems that would make debugging harder. It's also necessary to keep them in sync while updating the HTML which would take quite some effort for questionable gain.

Are you aware of [vue devtools](https://github.com/vuejs/vue-devtools/)? They make Vue apps debugging much easier

**Comment by smalllong** [comment]
@posva Actually, it's quite easy to add this feature, and I'm already using it during development. In function _createElement:
`if (process.env.NODE_ENV !== 'production' && isDef(data) && isDef(data.on)) {
	data.attrs = data.attrs || {};
	for (var i in data.on) {
		data.attrs['v-on:'+i] = data.on[i]._name
	}
  }`

**Comment by soanvig** [comment]
I see no point in implementing such a thing. Why?

1. There are dedicated devtools.
2. Because unit tests it is useless too: one should be testing if everything is executed as it should anyway.

**Comment by yyx990803** [comment]
This is not something that should be done by Vue. Chrome already gives you the ability to inspect listeners on arbitrary DOM elements.

**Comment by smalllong** [comment]
@yyx990803 However, I think the Chrome inspector's listeners shown in Vue apps are not readable.
