### ISSUE TITLE
Focus handler with v-model change cancels the selection of input's text on tab

### ISSUE THREAD

**Issue by rdy2018** [vuejs/vue#7533]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/64v1kumr/2/](https://jsfiddle.net/64v1kumr/2/)

### Steps to reproduce
1. Click on the results window of the JSFiddle.
2. Hit Tab. First input is selected and all text inside are highlighted.
3. Hit Tab again. 

### What is expected?
Second input is selected and all text inside are highlighted.

### What is actually happening?
Second input is selected but text inside are not highlighted. Cursor is in the end of the text.

---
I encountered this issue in Vue Numeric (https://github.com/kevinongko/vue-numeric) which formats the number on focus/blur. When tabbing on a number that the user needs to change, user needs to manually backspace or left arrow key instead of typing the number directly.

**Comment by sqal** [comment]
Example without Vue - https://jsfiddle.net/3hkxqbr4/. You need to call native `select()` method to select all the text. But in case of Vue, additionally you need to call this method in `$nextTick` handler (after the DOM has been updated) https://jsfiddle.net/qc112c4y/

**Comment by posva** [comment]
What @sqal said!
