### ISSUE TITLE
empty <video> props compile down to the wrong thing

### ISSUE THREAD

**Issue by makslevental** [vuejs/vue#7535]
### Version
2.5.3

### Reproduction link
[https://codesandbox.io/s/xjwx0o67zp](https://codesandbox.io/s/xjwx0o67zp)

### Steps to reproduce
	<video playsinline autoplay muted src='http://techslides.com/demos/sample-videos/small.mp4'></video>

### What is expected?
props compile down to playsinline='' autoplay='' and mute=''

### What is actually happening?
props compile down to playsinline='' autoplay='autoplay' and mute='mute'

---
`<video autoplay='' muted='' ...></video>` doesn't work either

this is a problem for things like webkit.org/blog/6784/new-video-policies-for-ios/

my hack solution is

```
            this.$refs.video.setAttribute('muted', '')
            this.$refs.video.setAttribute('playsinline', '')
            this.$refs.video.setAttribute('autoplay', '')
```

onload

**Comment by posva** [comment]
This is working as expected. Some of the attributes are set to their names on purpose so it works on older browsers

**Comment by makslevental** [comment]
@posva okay fine but why aren't `muted=''` and `autoplay=''`. are you really suggesting my solution is the appropriate one?

**Comment by posva** [comment]
It's the same reason for muted and autoplay, some browsers require them the value `muted="muted"`.
No, I don't.
Is something not working ? because when I tested on mobile and other browsers everything worked fine

**Comment by makslevental** [comment]
@posva safari on iphone doesn't recognize them and throws NotAllowedError

**Comment by posva** [comment]
I tested on safari and it worked correctly. Could you give more information, please? What versions, could you share a Stackstrace?

**Comment by makslevental** [comment]
@posva my actual use case is a navigator.mediaDevices.getUserMedia mediastream 

https://codesandbox.io/s/xjwx0o67zp

it's true that it does work on some ios devices (ipads in particular and some iphones) but i had iphone users all day telling me that that doesn't work

**Comment by posva** [comment]
In that case, it may probably be related to something else. Feel free to come back if you manage to get more information.
PS: no need to set up a codesandbox for such a simple repro, it will be much faster if you use [a jsfiddle](http://jsfiddle.net/m4L6jb4c/2/) 🙂
