### ISSUE TITLE
Vue component dont updating

### ISSUE THREAD

**Issue by RokkerRuslan** [vuejs/vue#7538]
### Version
2.5.13

### Reproduction link
[https://gitlab.com/rokkerruslan/minimal-reproduction](https://gitlab.com/rokkerruslan/minimal-reproduction)

### Steps to reproduce
yarn && yarn dev, then run the chrome and click on `up` button

### What is expected?
Current time replaced initial value

### What is actually happening?
Initial value not updated

**Comment by LinusBorg** [comment]
I can't run this right now, but in your code, where you write:

> console.log(this) // Print Vue component

Are you sure its the current component instance? The docs for vue-class-component state this does *not* work:

https://github.com/vuejs/vue-class-component#this-value-in-property

**Comment by posva** [comment]
Ran it and it's what @LinusBorg said, `this` is not the vue instance. Closing since this is something that need to be fixed in one of those libraries and we cannot fix anything in Vue core

**Comment by RokkerRuslan** [comment]
Oki

**Comment by LinusBorg** [comment]
>  something that need to be fixed in one of those libraries 

@posva I don't think there's a real "fix" for that, it's just how array functions behave in classes when assigned to class properties

**Comment by posva** [comment]
I was maybe thinking they can transform the code before passing it to other babel plugins and therefore do black magic 😆
