### ISSUE TITLE
父组件能不能直接传递所有来接收的props给子组件

### ISSUE THREAD

**Issue by ZiQiangWang** [vuejs/vue#7541]
### What problem does this feature solve?
避免重复代码，一个一个把属性接收，并向下传递
我有一个Base组件，在Base基础上扩展一些新的组件，比如Child组件。Child本身不对参数进行处理，只需要把接收到的属性全部传递给Base
注：没有使用vuex，也没有使用render函数

### What does the proposed API look like?
一个特殊属性的形式？？？？

**Comment by javoski** [comment]
可以看看 [`vm.$attrs`](https://cn.vuejs.org/v2/api/#vm-attrs).

**Comment by ZiQiangWang** [comment]
找了了，真的非常感谢

**Comment by ZiQiangWang** [comment]
@javoski 还有一个问题，vm.$attrs没有包含通过v-model传入的value

**Comment by javoski** [comment]
@ZiQiangWang 对 component 的 `v-model` 和 DOM 元素的 `v-model` 的处理是不同的，一起放 `vm.$attrs` 和 `vm.$listeners` 里可能会出现意料之外的情况。

**Comment by kokokele** [comment]
应该是  v-bind="$props"

**Comment by oudream** [comment]
v-bind="obj"

**Comment by kokokele** [comment]
v-bind="$attrs"
