### ISSUE TITLE
Set a variable in the component when it's created hook has finished

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue#7542]
### What problem does this feature solve?
I'd like to wait until the page is finished loading (i.e. when the `created` hook finishes running) to display certain elements. Unfortunately `v-cloak` doesn't work, because while it prevents mustache templates from appearing, it doesn't stop incomplete elements which are waiting for data from an API to be ready.

### What does the proposed API look like?
It would be good to have a variable available on the component like `this.$created` which is automatically set when the `created` hook finishes, so that we can use it in the template to hide elements or show loading spinners.

Currently I need to manually do this in every component, so I need to add a `created: false` to the `data`, then at the end of the created hook I set `this.created = true`. It would be good if this were handled automatically.

Or at least if there were a way to set a created hook **across all components** rather than needing to do it in each component. So a way to add that variable to `data` and set it in an after-created or mounted hook in all components so that it's done in one central place and all components can use it.

**Comment by rightaway** [comment]
Or even better, some way to intercept the `created` hooks of all components to do something like this. So I can set the function below in one place, and then it'll get called before/after all component's `created` hooks so that I can modify the Vuex store and then update the templates however I'd like to show loading progress.

```js
created() {
  // before the component's created hook
  Vue.store.dispatch('setLoading', true)
  created() // this is where the component's created hook gets called
  // after the component's created hook
  Vue.store.dispatch('setLoading', false)
}
```

**Comment by posva** [comment]
This is doable with a global mixin:

```js
Vue.mixin({
	data: () => ({ created: false }),
  created () {
  	this.created = true
  }
})
```

From that point on you can do anything you want (you can hook on `beforeCreate` as well and count)

**Comment by rightaway** [comment]
Is the `created` hook defined in `Vue.mixin` guaranteed to run after the `created` hooks in the individual components?

**Comment by posva** [comment]
They're called before: https://vuejs.org/v2/guide/mixins.html#Option-Merging

**Comment by rightaway** [comment]
In that case `created` would be set to false in `data` and then set to true before any of the component's initialization work is done, so if I rely on `this.created` in the templates, it would already be true even though the component's `created` hook hasn't completed. So this wouldn't work to solve the problem?

**Comment by posva** [comment]
You can use a different mixin to make it execute before:

```js
Vue.mixin({
  data: () => ({
    created: false
  }),
  beforeCreate() {
	this.$options.created = this.$options.created || []
    this.$options.created.unshift(function() {
      this.created = true
    })
  }
})
```

**Comment by rightaway** [comment]
This demonstrates the exact problem https://codepen.io/anon/pen/yvBywv. I want the `Value is something` to be hidden until the end, but `this.created` is set to true from the beginning even after using the mixin you suggested. It should be set to false at the beginning, and true once the `created` hook of the component is finished.

**Comment by posva** [comment]
oh, sorry I meant using `push` instead of `unshift` 😆  (I updated the snippet)
If you want to trigger it after a timeout you may consider using promises and waiting for them to finish before doing `this.created = true`. You should be able to achieve it with the method I showed you.
But, please, move the conversation to discord or the forums if you want more help

**Comment by rightaway** [comment]
If you try it in the codepen example it doesn't work with `push` either.

The timeout was only an example, it would normally be an async/await request but codepen doesn't support that (doesn't work for me locally with async/await either).

> you may consider using promises and waiting for them to finish before doing `this.created = true`

You mean in the component? This issue is about each component shouldn't have to set `this.created = true` itself but that Vue should set it in the global mixin which isn't working.
