### ISSUE TITLE
is 'loading'  is slot‘s props 

### ISSUE THREAD

**Issue by ddcouples** [vuejs/vue#7543]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
```
<div key="component">
      <slot :loading="loading"></slot>
  </div>
```
loading is true or false can control the slot  loading the source

### What is expected?
loading is the prop?

### What is actually happening?
loading is the prop?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you open a bug report, please add a repro and provide different versions of _what is expected_ vs _what is actually happening_
