### ISSUE TITLE
Method exec twice when use axios

### ISSUE THREAD

**Issue by leapit** [vuejs/vue#7551]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/94324/](https://jsfiddle.net/50wL7mdz/94324/)

### Steps to reproduce
1.Add a real exist url in http.get() method,any url would be ok just for test

2.Then run,the console will show result for "twice" "twice" 

### What is expected?
only one "twice" output

### What is actually happening?
it happen twice

Full code here,
<img width="408" alt="wx20180129-162351 2x" src="https://user-images.githubusercontent.com/1665671/35500261-e2ccfce0-0510-11e8-900b-a5c430dbb603.png">
Out put here
<img width="462" alt="wx20180129-161017 2x" src="https://user-images.githubusercontent.com/1665671/35500276-f3c0f51a-0510-11e8-98af-730d89dab946.png">

**Comment by JounQin** [comment]
Why not? template will be compiled into js codes as `render` function, and when `orderList` changed, `render` will be called again, so function `title` will be called again.

**Comment by leapit** [comment]
@JounQin when you delete the loop template fragment, you will see the console only happen once.
so,why orderList also changed,but the difference result.

the loop tempate has influence on other method,this is strange.

**Comment by JounQin** [comment]
If I'm not misunderstanding your question, when your removed `orderList` from template, Vue will not render again on its changes, because Vue knows there's no reference of `orderList` in template.

https://vuejs.org/v2/guide/reactivity.html#How-Changes-Are-Tracked

**Comment by posva** [comment]
This is expected, by calling a method in the template, Vue will call it every time it renders: This can also come in handy: https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods

**Comment by leapit** [comment]
@posva It seems no such behavior in react framework,some methods in `method` has no relationship with data model,each method recalled when a data model change,that is a little strange.

and if you change the title function with `computed` way,also console out twice.

**Comment by yyx990803** [comment]
...it will be exactly the same in React...

**Comment by leapit** [comment]
@yyx990803 yes,my mistakes,just did a test under React framework,the same behavior.and one more question,for this axios scenario,in fact i just want load data after a sync request,then render the response  to template one time,no need re-render the changed data,any idea for this?
