### ISSUE TITLE
Vue warn

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuejs/vue#7553]
### What problem does this feature solve?
The warnings in Vue looks like errors. This might be a little confusing, it would be better changing it from "console.error" to "console.warn". This will improve the convenience in the browser's console's filtering feature.

### What does the proposed API look like?
Replacing "console.error" to "console.warn" for warnings.

**Comment by posva** [comment]
I think this is intentional because no Vue warning should be skipped. In some other scenarios, we do use `warn` instead of `error` (eg vue-router)

**Comment by yyx990803** [comment]
Unfortunately warnings don't come with stack traces.
