### ISSUE TITLE
Remove attribute merging for functional components with no prop definition

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue#7557]
### What problem does this feature solve?
Currently when using functional components without `prop` definition, all attributes will be rendered when using [`JSX spread`](https://github.com/vuejs/babel-plugin-transform-vue-jsx#jsx-spread).  

This is because the `context.data.attrs` remain after they are merged. 

## Current

Usage:`<Example type="blue" fill={true} class="extra-class" aria-label="I'm a label" />`

Implementation: 
```
export default {
  functional: true,
  
  render({ data, props }) {
    const { type, fill } = props

    const buttonClass = {
      'button--fill': fill,
      [`button--${type}`]: !!type
    }

    <button {...data} class={buttonClass} >
  }
}
```

Output: `<button fill="true" type="blue" class="extra-class button--fill button--blue" aria-label="I'm a label" />`

### What does the proposed API look like?
It should be explicit what attributes to render to dom when using a functional component with no prop definition. 

[With fix `delete data.attrs`](https://github.com/vuejs/vue/blob/dev/src/core/vdom/create-functional-component.js#L81)

### Explicitly passing attributes

You can use spread notation to get all remaining `attrs`, and replacing the `data.attrs` object

Usage: `<Example type="blue" fill={true} class="extra-class" aria-label="I'm a label" />`

Implementation: 
```
export default {
  functional: true,
  
  render({ data, props }) {
    const { fill, type, ...attrs } = props
    data.attrs = attrs

    const buttonClass = {
      'button--fill': fill,
      [`button--${type}`]: !!type
    }

    <button {...data} class={buttonClass} >
  }
}
```

Output: `<button class="extra-class button--fill button--blue" aria-label="I'm a label" />`

### Explicitly passing attributes 2

Usage: `<Example  type="blue" fill={true} class="extra-class" formtarget="id" dummy-attr="lol" />`

Implementation: 
```
export default {
  functional: true,
  
  render({ data, props }) {
    const { fill, type, formtarget } = props

    const buttonClass = {
      'button--fill': fill,
      [`button--${type}`]: !!type
    }

    <button {...data} formtarget={formtarget} class={buttonClass} >
  }
}
```

Output: `<button class="extra-class button--fill button--blue" formtarget="id" />`

### Conclusion

Both examples show how the behaviour of the attributes should be left with the child when dictating what attributes shoud be rendered. You can either do a `and rest` approach or explcititly name attributes to pass onto element. 

The original all props/attrs will be rendered as attributes, which adds polution to the DOM especially with attributes that are array's/objects/functions/symbols.

**Comment by padcom** [comment]
I am curious though: how would you pass all actual attributes down to a component when it is a component that is expected to pass all its attributed down. A good example is the button that have been mentioned here. How would I pass the @click in this case? Will it work?
