### ISSUE TITLE
Component cached passed property in case of iterating by descending ordered array

### ISSUE THREAD

**Issue by FSou1** [vuejs/vue#7559]
### Version
2.5.13

### Steps to reproduce
Use a component for property display in a loop over ordered by descendant array

### What is expected?
An actual value

### What is actually happening?
Cached value of previous object is displaying

---
I'm new with Vuejs and probably my issue is a dummy one, but I've not still realized how to fix it.

**Situation**: I have a collection of objects which I've sorted with lodash:

```js
{
  computed: {
    sortedAlerts: function() {
      return _.orderBy(this.filteredAlerts, 'createdAtUtc', 'desc');
    }
  }
}
```

And iterating with `v-for="alert in sortedAlerts"`.

I also display one of the object property with the usage of Vuejs component:

```js
components: {
    'alert-title': {
        props: ['model'],
        computed: {
            indicatorTitle: function() {
                return this.alert.indicator.title.toLowerCase();
            },
            conditionTitle: function() {
                return this.alert.condition.title.toLowerCase();
            }
        },
        template:'<span><i>{{indicatorTitle}}</i> is {{conditionTitle}} {{alert.amount}}</span>',
        data: function() {
            return {
                alert: this.model
            }
        }
    }
}
```

like this `<span is="alert-title" v-bind:model="alert"></span>`.

Finally, when I add new objects into this array (which going to be the first elements in ordered array), the `alert-title` component do not display newly added object in a proper way (but continue to display the **previous one**, which now is actualty the second and duplicate).

Page refresh is fixing this situation, but I'm pretty sure that the code have an issue.

I know it's not too clear but I hope someone could figure out what's wrong with it.

Let me know if an example should also be provided.

Thank you.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Please, provide a minimal repro when reporting a bug
