### ISSUE TITLE
v-show display flickering with <transition> component on IOS 11.1.2 and 11.0.2

### ISSUE THREAD

**Issue by dxcqcv** [vuejs/vue#7561]
### Version
2.5.4

### Reproduction link
[https://jsfiddle.net/dxcqcv/hby2g9ja/](https://jsfiddle.net/dxcqcv/hby2g9ja/)

### Steps to reproduce
when v-show display, the opacity transition will flicker.

### What is expected?
show with opacity css animation 

### What is actually happening?
show with opacity css animation, but with flickering

---
In my test this case will recurrent on IOS 11.1.2 iPhone 8 plus and IOS 11.0.2 iPhone 6s.

And I record a [video about this bug](https://weibo.com/tv/v/G0MGYfcLm?fid=1034:29b27092d5c162a0d17ccd66f8e1dfc0)

**Comment by posva** [comment]
FYI: the video is not accessible

**Comment by dxcqcv** [comment]
that link is weibo link in China, I upload videos on VK,  [try this link](https://vk.com/feed?w=wall352021084_7&z=video352021084_456239017%2F3d318663355473a8f0%2Fpl_post_352021084_7)

@posva

**Comment by posva** [comment]
It's the same lol. In any case, I'll appreciate if somebody can test it, I don't have the devices

**Comment by endoplasmic** [comment]
I'm also seeing this in a WebView on Android. Transition finishes and quickly flickers once complete.

**Comment by dxcqcv** [comment]
I also upload the [video](https://vimeo.com/253545200) on vimeo, so try again @posva

**Comment by vinczedani** [comment]
Hi,
I have an IPhone SE with IOS 11.2.2 and the my vue transitions seems to work like this:
- Final state is displayed for a short time
- Then the transition plays as expected (maybe a bit faster)
I played the transitions on the official VueJS transition site, and they play in a strange way too.
The animation with animate.css@3.5.1 and velocity plays as expected on both iOS, Android and PC

VueJS version: ^2.5.13

**Comment by jkzing** [comment]
Tested in iOS11.2.5, didn't reproduce the issue. I guess it only appears on IOS 11.2.2...

![wechatsight13](https://user-images.githubusercontent.com/2851517/35859237-40fc6728-0b7a-11e8-95e5-648db4fba241.gif)

**Comment by posva** [comment]
I think the classes are not correctly applied because the original video is showing a custom application. Thanks for checking it @jkzing 👍

**Comment by endoplasmic** [comment]
I just wanted to update others who are also getting this problem (and the workaround).

I've narrowed it down to any transition that is setting the opacity. Once opacity reaches `1` you get the flicker, so I've instead changed it to `0.999` and the flicker is gone. I'm not sure which version of Chrome (on Android in my case) this happened in, but at least setting it to not be 1 works!
