### ISSUE TITLE
Use vNodes without DOM representation

### ISSUE THREAD

**Issue by BrainBacon** [vuejs/vue#7563]
### What problem does this feature solve?
There is a thread for this on the forum:
https://forum.vuejs.org/t/using-vue-without-dom-representation/17712/3

I'm attempting to use Vue in a manner similar to Aframe where the state in a 3d graphics engine is managed by vue components and template composition. There really isn't any need to have actual DOM nodes since the actual rendering is delegated to the underlying 3d framework. Right now I am able to represent scene state with custom components, but the only way I can actually have the components initialized is by rendering some empty DOM nodes. It seems unnecessary to add the overhead of actual DOM representation and leads to a strange cascading empty div structure in the document.

### What does the proposed API look like?
A component property that marks it as "virtual" or a vNode property that marks it as "virtualOnly".

**Comment by yyx990803** [comment]
What you are looking for is more like a custom renderer (#7005)

**Comment by BrainBacon** [comment]
@yyx990803 a couple of considerations if using a custom renderer is to be the resolution for this use case:
 - The API design should allow for nodes that do not have a analogue to XML tags e.g. rendered output not having a "tag name"
 - Having the possibility to run a custom renderer alongside the standard renderer e.g. using the standard Vue renderer to create a "canvas" element in the DOM and then use the custom one for the scene.
 - It would be great to be able to use the existing Vue devtools with a custom renderer

Otherwise, that's a fine suggestion as a future solution.
Thank you for your time.
