### ISSUE TITLE
关于计算属性定义的问题？

### ISSUE THREAD

**Issue by xfya** [vuejs/vue#7567]
### Version
2.5.13

### Reproduction link
[https://cn.vuejs.org/v2/guide/computed.html#%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7](https://cn.vuejs.org/v2/guide/computed.html#%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7)

### Steps to reproduce
关于计算属性  到底是指 computed  还是指computed  里面定义的 键值对

### What is expected?
关于计算属性  到底是指 computed  还是指computed  里面定义的 键值对

### What is actually happening?
关于计算属性  到底是指 computed  还是指computed  里面定义的 键值对

---
关于计算属性  到底是指 computed  还是指computed  里面定义的 键值对

**Comment by yyx990803** [comment]
不要用 issue 问问题。
