### ISSUE TITLE
v-model resets with a slot

### ISSUE THREAD

**Issue by trainorpj** [vuejs/vue#7568]
### Version
2.5.13

### Reproduction link
[https://codepen.io/pj_/pen/XZWOxO/](https://codepen.io/pj_/pen/XZWOxO/)

### Steps to reproduce
Type any input into the second `<input>` box

### What is expected?
That the second input component (bound to `q2`) will behave no differently than the first (bound to `q1`), i.e. that it behaves like an `<input>` tag

### What is actually happening?
Two things:

* second input box resets after short amount of time
* second input box seems to delete the end of the string, but `q2` is unchanged (try typing in two keys very quickly)

---
I discovered this when working on a custom input component; I'm using the slot as a way to put content next to an `<input>` box.  This seems like a common use-case, and I'm reporting it because I couldn't find the same issue in the docs/repo/forums.

**Comment by sirlancelot** [comment]
Your `query` prop is not getting set. Changing `query` to `value` in the definition and template fixes the issue.

https://codepen.io/sirlancelot/pen/gvbEeG?editors=1010

If you want, you can change Vue's `v-model` behavior to pass the prop `query`. See the [documentation for model](https://vuejs.org/v2/api/#model) for more information.

**Comment by trainorpj** [comment]
Thanks for answering! I really appreciate it 👍
