### ISSUE TITLE
Pitfalls of Vue dependency detection may cause redundant dependencies

### ISSUE THREAD

**Issue by xiaodemen** [vuejs/vue#7573]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/sbmLobvr/9/](https://jsfiddle.net/sbmLobvr/9/)

### Steps to reproduce
click the button，then App component will update twice！

### What is expected?
App component updates only once

### What is actually happening?
App component updates twice

---
When props used in child component initialization，they will be detected as dependencies of parent component, Is there possible to stop dependency detection when entering child component initialization。

**Comment by LinusBorg** [comment]
Hm, that's indeed odd.

For completeness, here's a version not using the prop in `data` - it only updates once: https://jsfiddle.net/sbmLobvr/10/

**Comment by posva** [comment]
@LinusBorg I don't think there's anything wrong going on: the `msg` prop is used in the template of the root instance, so it's normal for it to render again if it changes (no matter where the update comes from)

**Comment by LinusBorg** [comment]
Yeah, it's ok to update once, but twice in a row doesn't make sense to me.

**Comment by LinusBorg** [comment]
Especially since it only updates once if we don't access the prop in `data()` in the child (see my fiddle)

**Comment by posva** [comment]
Mmh, at some point it only showed up once or maybe I just didn't see it correctly, my bad

**Comment by xiaodemen** [comment]
@javoski I don‘t think this would be the best solution，not just data option，but the whole child component initialization.
And I think it should be reactive, but as dependency of child component ?

**Comment by javoski** [comment]
@xiaodemen Sorry about that there's an ambiguity in the PR's title, component props are **reactive**, but they shouldn't collect dependencies during initialization of data option.

**Comment by xiaodemen** [comment]
@javoski I know, but data option is NOT the only situation that shouldn't collect dependencies, e.g. component created hook, before mount hook and immediate watch ...

**Comment by javoski** [comment]
@xiaodemen Yes, you are right, didn't aware of that, and will try to figure out a better solution.
