### ISSUE TITLE
capture event can trigger before no capture event in the same element

### ISSUE THREAD

**Issue by pbdm** [vuejs/vue#7574]
### What problem does this feature solve?
users don't need to care about the order when bind both capture and no capture events, 
 `<button v-on:click="bub"  v-on:click.capture="cap">click</button>` and 
`<button  v-on:click.capture="cap" v-on:click="bub">click</button>` 
will got the same result(capture events will always trigger before no capture one when we click the button)

### What does the proposed API look like?
''

**Comment by yyx990803** [comment]
I don't understand what you want. If you are making a feature request, please make a proper one.

**Comment by pbdm** [comment]
#7575
