### ISSUE TITLE
capture event can always trigger before bubble event in the same element

### ISSUE THREAD

**Issue by pbdm** [vuejs/vue#7575]
### What problem does this feature solve?
see https://jsfiddle.net/e3j3o9o6/
I suggest that both these two buttons can trigger capture before bubble

similar in 微信小程序 https://mp.weixin.qq.com/debug/wxadoc/dev/framework/view/wxml/event.html -> 事件的捕获阶段.
```
<view id="outer" bind:touchstart="handleTap1" capture-bind:touchstart="handleTap2">
  outer view
  <view id="inner" bind:touchstart="handleTap3" capture-bind:touchstart="handleTap4">
    inner view
  </view>
</view>
```
with this example, handleTap4 is trigger before handleTap3 when click inner view

### What does the proposed API look like?
no need to change API with this feature

**Comment by LinusBorg** [comment]
You are misunderstanding `capture`. capturing an event only has any effect if you are interceptnig an event  that was triggered by a nested child element. if you use capture on the element that triggered the event, it has no real effect.

See MDN on this:

> or event listeners attached to the event target, the event is in the target phase, rather than the capturing and bubbling phases. Events in the target phase will trigger all listeners on an element in the order they were registered, regardless of the `useCapture` parameter.

So this is just how `capture` mode works in browsers. I don'T think we should  work around that behaviour, so this gets a "no" vote from me.
