### ISSUE TITLE
Listeners are not updated correctly on component reuse

### ISSUE THREAD

**Issue by xiaodemen** [vuejs/vue#7579]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/x78pz6u1/7/](https://jsfiddle.net/x78pz6u1/7/)

### Steps to reproduce
1. click emit1, alert something, no problem.
2. click switch.
3. click emit2, alert again, not expected!

### What is expected?
not alert when I click the button emit2

### What is actually happening?
alert when I click the button emit2

---
not considering the edge case: listeners are removed on component reuse.
perhaps a bug at line 260 in v2.5.13/src/core/instance/lifecycle.js

**Comment by posva** [comment]
Looks like the reused component is keeping the event listeners.
As a workaround for the moment, add a `key` attribute on one of the components

**Comment by posva** [comment]
Checking with git version, looks like it was already fixed. But thanks for reporting it 🙂
