### ISSUE TITLE
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "showIcon"

### ISSUE THREAD

**Issue by rawbin-** [vuejs/vue#7580]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/728nx8mrm0](https://codesandbox.io/s/728nx8mrm0)

### Steps to reproduce
pass .sync prop from parent to grandson through child

### What is expected?
no warning

### What is actually happening?
 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "showIcon"

**Comment by rawbin-** [comment]
the role of the Child component is just a component wrapper or sth like that

**Comment by posva** [comment]
You have to reemit in the Child that passes down a prop:

```vue
<grandson :showIcon="showIcon" @update:showIcon="v => $emit('update', v)></grandson>
```

Remember that `sync` is just [syntax sugar](https://vuejs.org/v2/guide/components.html#sync-Modifier)

**Comment by yyx990803** [comment]
Sync across multiple layers is a bad practice anyway, consider using a global state management solution.

**Comment by rawbin-** [comment]
@posva that make sense

**Comment by daGaiGuanYu** [comment]
@yyx990803 大佬，建议在文档里说明一下啊。[手动狗头][手动狗头][手动狗头][无意冒犯]

**Comment by marissagroves** [comment]
What is a global state management solution? 
![image](https://user-images.githubusercontent.com/23355055/82791848-0d670500-9ea1-11ea-83b0-204e60e1f4fc.png)
I put it in an object.
parent:
`       <MyDateModePicker :date="date"></MyDateModePicker>`
`      date: { D: '', W: '', M: '', mode: 'D' },`
child component:
`      {{ date.mode }} {{ date }} {{ date.W }}
      <el-radio-group v-model="date.mode" size="small">
        <el-radio-button label="D">日</el-radio-button>
        <el-radio-button label="W">周</el-radio-button>
        <el-radio-button label="M">月</el-radio-button>
      </el-radio-group>`
It worked...

**Comment by gaetansenn** [comment]
state management https://vuex.vuejs.org/
and it's normal that it is working for object as it is non primitive type like array
