### ISSUE TITLE
Document error or a trick

### ISSUE THREAD

**Issue by aykutkardas** [vuejs/vue#7581]
### Version
2.5.13

### Reproduction link
[https://jsbin.com/xusuziyeno/edit?html,js,output](https://jsbin.com/xusuziyeno/edit?html,js,output)

### Steps to reproduce
https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

### What is expected?
`vm.b` is NOT reactive

### What is actually happening?
`vm.b` is now reactive

**Comment by yyx990803** [comment]
It is not reactive, it's because changing `vm.a` caused a re-render, which happens to pull the latest value of b as well. Reactive means mutating the value itself will trigger a re-render.
