### ISSUE TITLE
$refs is lost when the component is re-rendered

### ISSUE THREAD

**Issue by wux5** [vuejs/vue#7585]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/0euprqpu/2/](https://jsfiddle.net/0euprqpu/2/)

### Steps to reproduce
1. Follow the jsfiddle link, click button1, you'll see refs is printed in console which is expected.
2. Click button2 to switch the if condition.
3. Click button1 again, you'll see in the console that $refs is now an empty array.

### What is expected?
The $refs should remain valid when the component is re-rendered.

### What is actually happening?
$refs is lost.

**Comment by sqal** [comment]
You have to wait until component is fully patched, so use $nextTick 
```js
this.$nextTick(() => {
  console.log(this.$refs)
});
```

**Comment by EliazTray** [comment]
https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue

**Comment by wux5** [comment]
I made a mistake in my code with complex event listening/binding, in a place I forgot to unregister the event listeners in beforeDestroy hook, hence the "this" was still the old context with empty $refs. It's now working. Thanks much for the help.
