### ISSUE TITLE
How can a functional component be used as a named slot of another component?

### ISSUE THREAD

**Issue by tyllo** [vuejs/vue#7587]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/tyllo/6mczkf2w/1/](https://jsfiddle.net/tyllo/6mczkf2w/1/)

### Steps to reproduce
ust run the demo

### What is expected?
Default slot fallback
[inner 2.5.13]

### What is actually happening?
[inner 2.5.13]
Named slot fallback

---
Like https://github.com/vuejs/vue/issues/3872

**Comment by posva** [comment]
What happens is that the functional component is taking a named slot `abc` but doing nothing with it. You need to pass it down to the child using `scopedSlots` (https://vuejs.org/v2/guide/render-function.html#Slots).
About what you expect, that would be quite problematic as it could produce unexpected side effects by having slots leaking into descendant children

In your specific example, the functional component should look like this:
```js
Vue.component('function-component', {
  functional:true,
  render(h, context) {
	context.data.scopedSlots = {
    	abc: () =>  context.slots().abc
    }
    return h('inner-component', context.data, context.slots().default);
  }
});
```
