### ISSUE TITLE
v-leave doesn't work correctly

### ISSUE THREAD

**Issue by kofon95** [vuejs/vue#7589]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/sagid/50wL7mdz/95525/](https://jsfiddle.net/sagid/50wL7mdz/95525/)

### Steps to reproduce
Click on "Toggle cond"

### What is expected?
Transition element _(text below the button)_ should become red first _(v-leave)_, and then slowly turn into green _(v-leave-to)_.

### What is actually happening?
Transition element do not become red in the first frame _(v-leave do nothing)_, but green background works fine.

---
You can change the version on the top of _html panel_ to **2.1.7** and watch **v-leave** worked _(since **v-leave-to** is not available in 2.1.7-)_.

P.S. _I am a beginner._

**Comment by kofon95** [comment]
I only added **font-size** in **v-leave** and **v-leave-to**.
https://jsfiddle.net/sagid/50wL7mdz/95534/
As a result, I expect transition **font-size** from **200%** to **100%**

**Comment by jkzing** [comment]
This is not relevant with vue, try this [fiddle](https://jsfiddle.net/50wL7mdz/95661/) which removes vue dependency.

When use web transition, you need to specify font-size explicitly, like [https://jsfiddle.net/50wL7mdz/95662/](https://jsfiddle.net/50wL7mdz/95662/).

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Maybe this is what you want: https://jsfiddle.net/m3rynag5/
The repro and your issue are not talking about the same properties 😛
