### ISSUE TITLE
Add "wrap" directive

### ISSUE THREAD

**Issue by xiaomingdexian** [vuejs/vue#7590]
### What problem does this feature solve?
Sometimes i need the "wraper" element but sometimes not,
So i should:
```
<div class="wraper" v-if="hasWraper">
    <p>title</p>
<div>
<p v-else>title</p>
```
    

### What does the proposed API look like?
I need  a directive like this:
```
<div class="wraper" v-wrap="hasWraper">
    <p>title</p>
<div>
```
when the value of "hasWraper" is false.
it perform as
``` 
<p>title></p>
```

**Comment by posva** [comment]
Hello, this can be achieved in userland with a component similar to:

```js
const Wrapper = {
  functional: true,
  render (h, context) {
    if (context.props.wrap) {
      return h(context.props.tag, context.data, context.children)
    } else {
      return context.children
    }
  }
}
```
(untested)

**Comment by xiaomingdexian** [comment]
thank u
