### ISSUE TITLE
v-else and v-for can't be used together

### ISSUE THREAD

**Issue by autumnLeaves0** [vuejs/vue#7592]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/95639/?utm_source=website&utm_medium=embed&utm_campaign=50wL7mdz](https://jsfiddle.net/50wL7mdz/95639/?utm_source=website&utm_medium=embed&utm_campaign=50wL7mdz)

### Steps to reproduce
v-else and v-for can't be used together

### What is expected?
Rendering results
<div>
<div><p>else-1</p></div>
<div><p>else-2</p></div>
<div><p>else-3</p></div>
<div><p>else-4</p></div>
<div><p>else-5</p></div>
<div><p>else-6</p></div>
<div><p>else-7</p></div>
<div><p>else-8</p></div>
<div><p>else-9</p></div>
<div><p>else-10</p></div>
</div>

### What is actually happening?
Rendering results
<div>undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined</div>

**Comment by Akryum** [comment]
This is expected. v-for has higher priority than conditionals like v-if or v-show. If you put one on the same element, it will be executed for each item in the v-for loop.

Use a template tag:

```html
<template v-else>
  <div v-for="b in 10">else-{{b}}</div>
</template>
```

https://vuejs.org/v2/style-guide/#Avoid-v-if-with-v-for-essential
