### ISSUE TITLE
SSR Component Cache doesn't cache Strings

### ISSUE THREAD

**Issue by MartinLG** [vuejs/vue#7593]
### Version
2.5.13

### Reproduction link
[https://github.com/MartinLG/issue-redis-component-cache](https://github.com/MartinLG/issue-redis-component-cache)

### Steps to reproduce
You need a running Redis server:
```bash
docker run --rm -p 6379:6379 -d redis
```

Then setup the project:

```bash
npm install
npm run dev
```

Load a page: [http://localhost:3000](http://localhost:3000) => It works

Reload the page: Error, the cache is wrong

### What is expected?
The variable passed to the Component Cache should be a String, as explained in the [documentation](https://github.com/vuejs/vue-ssr-docs/blob/master/en/api.md#cache).

### What is actually happening?
The variable passed to the Component Cache is a javascript object. I tried to JSON.stringify it (and parse it in the get method), but this object contains a Set of javascript functions, so I loose data when I stringify it.

---
This issue breaks any external cache possibility.
The only possible cache is in the process memory, like the LRUCache, but it seems impossible to scale processes and share a common cache.

Moreover, the documentation explain clearly that the cached value should be a string, and even provides a small Redis example implementation, that could just not work.

**Comment by posva** [comment]
Please, provide a minimal repro when opening an issue. For example, no redis, no nuxt
If the redis example is not working in the docs, please, open a PR there instead 🙂
