### ISSUE TITLE
万能的尤大大,请教一个关于环境的vue部署问题

### ISSUE THREAD

**Issue by 247163569** [vuejs/vue#7594]
### What problem does this feature solve?
我现在有这样一个问题,我们公司有多个环境,本地开发开发就不说了,什么内外测试,外网测试,正式环境等,我们使用的是homestead集成的laravel php,各种地址的baseUrl在每个环境中都不一样,如何才能做到上传打包之后的代码,自动切换baseUrl

### What does the proposed API look like?
...

**Comment by gebilaoxiong** [comment]
经验告诉我们。。。先试着尝试。。。再抛出问题

**Comment by 13947965133** [comment]
Советую использовать. Angular js, мы, чем vue также прочную основу.
Добро пожаловать в москве.

**Comment by AAChartModel** [comment]
这种谄媚的标题让人看着就来气,还指望有人愿意帮你?
