### ISSUE TITLE
when use a for loop in ios 9.3， 'for' will run twice

### ISSUE THREAD

**Issue by greedying** [vuejs/vue#7599]
### Version
2.5.13

### Reproduction link
[https://github.com/greedying/vue-for-bug-demo](https://github.com/greedying/vue-for-bug-demo)

### Steps to reproduce
let `vm = new Vue(params)`
`vm.$data.list` is a array;

when you do this, it is right:
```javascript
for(var i = 0; i < vm.$data.list.length; i++) {}
``` 

but this below  is wrong. it run twice, and I don't know why
```javascript
for(var i in vm.$data.list) {}
```
this is  only in ios 9.3

first, find an iphone with ios 9.3
second, open the bugs github demo
third, see the image or run the code in iphone，or view the demo url in README

### What is expected?
for-loop run only once 

### What is actually happening?
for-loop run twice

**Comment by leinue** [comment]
nice sample

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
`for...in` loops accesses properties on the prototype, so you'll need a [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) check. This is not related to Vue and is a common JavaScript pitfall with `for...in`.

**Comment by greedying** [comment]
hi~ in fact, only vue's property or computed property will run twice for-loop.
yes, it is about `hasOwnProperty`, so may Vue changed its own property, I doubt.
anty way, vue doest not have a similar  performance with common js 。

I add  the demo of common js in my github， you can see it if you want。

**Comment by greedying** [comment]
may I reopen it ?
