### ISSUE TITLE
Decrease FPS in Cesium.js because deep reactivity

### ISSUE THREAD

**Issue by ar53n** [vuejs/vue#7603]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/L2zegt23/](https://jsfiddle.net/L2zegt23/)

### Steps to reproduce
Need load array of computed position in Vue.js and run Cesium.js
or create deep object

### What is expected?
The array is reactivated, but inner object not.

### What is actually happening?
Array and object deep reactivated and when cesium.js used this object calling getter of an object and FPS decreased to 10-15 FPS

---
Maybe have cases when need deep set reactivity. But in my case not needed, only for array items
Forum help question: https://forum.vuejs.org/t/cesium-and-vue-js-data-getters/26928

**Comment by posva** [comment]
Use `Object.freeze` or [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to prevent Vue from picking up reactivity on large datasets
