### ISSUE TITLE
Using reserved keywords computed props but not inside template expressions

### ISSUE THREAD

**Issue by samayo** [vuejs/vue#7604]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/943bx5px/35/](https://jsfiddle.net/943bx5px/35/)

### Steps to reproduce
Check the error in console log.

### What is expected?
consistent behavior. (explained in additional comments)

### What is actually happening?
Vue throws the following error: 
> [Vue warn]: Error compiling template: Avoid using JavaScript keyword as property name: "default"..

---
If this is indeed something that needs to be fixed, I propose one of the following. 

- disallow the use of special keywords like default, do, while ... from being used to create a computed properties.
- (or) if we allow people to create computed props with those names, [as is the case now], then these computed props should be used inside template expressions

**Comment by yyx990803** [comment]
The check implies you should not define any reactive property using keywords, including computed properties. Adding extra check just for comouted seems redundant.

**Comment by samayo** [comment]
If the user defines a computed prop with `default: () => { x: 'y'}` (which is allowed) then they expect to use that in the template, but they can't. This is inconsistent behavior no?
