### ISSUE TITLE
Support `className` in render/createElement

### ISSUE THREAD

**Issue by snaptopixel** [vuejs/vue#7605]
### What problem does this feature solve?
The requirement to add quotes around `class` when using render functions is somewhat annoying, seems reasonable to support (and recommend) using `className` instead, so you don't need to quote the single oddball property.

### What does the proposed API look like?
```js
render(createElement) {
  createElement('div', {className: 'foo bar baz'}, …)
}
```

**Comment by LinusBorg** [comment]
> The requirement to add quotes around class when using render functions 

Hu? That would be news to me. Can you elaborate?

**Comment by yyx990803** [comment]
You don't have too when a keyword is used as a property key identifier.

**Comment by snaptopixel** [comment]
Ah, thanks @LinusBorg @yyx990803, the docs led me astray 😆 

https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

**Comment by LinusBorg** [comment]
That's actually a valid point about the docs, would you open an issue in the vuejs.org repository?
