### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: input

### ISSUE THREAD

**Issue by avivsalman** [vuejs/vue#7608]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
i dont have any example, i cant register any of component, please ignore the website example.

when i am runnig in dev mode with webpack, i get this error:
[Vue warn]: Do not use built-in or reserved HTML elements as component id: input

but the component name is dp-input:

import:
import dpInput from './../components/inputs/Input'

components: {
    dpInput
},

in template:
dp-input(v-model="data")

### What is expected?
No Error need to be here because its not saved html Element

### What is actually happening?
get an error

**Comment by psimyn** [comment]
does the component exported from `./../components/inputs/Input` have a `name` property of 'input'? Looks like it might have, e.g.

```
export default {
  name: 'input',
  ...
}
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
If your repro can't be put in jsfiddle, you can try using a github repo or https://codesandbox.io. Thanks!

**Comment by avivsalman** [comment]
Thank You, you right, I just changed the name 👍

**Comment by JounQin** [comment]
I'm also getting this warning when using name `Image`, which is marked as reserved tag name in `isSVG`(https://github.com/vuejs/vue/blob/master/src/platforms/web/util/element.js#L31), so why HTML tags are not transformed into lower case but SVG tags are?

@fnlctrl @yyx990803 Should they be consistent?

**Comment by sina-GitHub** [comment]
change the "name" of  the component to a non reserved HTML tag name in "export default" section,

a wrong exmaple :
```
export default {
  name: "div",// div is "not a valid" name, because it's a reserved HTML tag
};
```

a True exmaple :
```
export default {
  name: "valid_name",// OK
};
```

**Comment by abdessamadelhamdany** [comment]
Try giving it a capitalize name example will be

`name: "Header",` instead of `name: "header",`

**Comment by alexcroox** [comment]
capitalisation doesn't seem to matter for some names:

`name: 'Image'` =  `Do not use built-in or reserved HTML elements as component id: Image`
`name: 'Button'` = no error

**Comment by siolfyr** [comment]
`Do not use built-in or reserved HTML elements as component id: Image `

I had this message come up when I used a component called LazyImage. Confusing since it said 'Image' Instead of 'LazyImage', and didn't really tell me the component that had the problem.

**Comment by martianmartian** [comment]
`import { Switch as vswitch } from 'vant';`

**Comment by cuizhili** [comment]
Thank You, you right, I just changed the name 👍
