### ISSUE TITLE
Allow data binding inside comments

### ISSUE THREAD

**Issue by jpkleemans** [vuejs/vue#7612]
### What problem does this feature solve?
Data bindings inside html comments are being ignored, while sometimes they would be very useful. Especially when using conditional (IE) comments: https://jsfiddle.net/3p19d8jp/

### What does the proposed API look like?
Allow using the “Mustache” syntax inside html comments:
```html
<!--[if IE]><p>{{OldBrowserMessage}}</p><![endif]-->
```

**Comment by posva** [comment]
hhm, usually that goes in the header or outside of `html`. I don't think you should use it for content. You should use browser detection to include the scripts you want or even better: serve a different page based on the browser by using the User-agent. Using Vue inside of an IE comment looks like an overkill to me

**Comment by jpkleemans** [comment]
There are also conditional comments that don't go inside the head.
For example (for Outlook):
```html
<!--[if gte mso 9]>
<v:image src="{{imageUrl}}" />
<![endif]-->
```
(use case for this could be an e-mail editor UI)

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

Conditional comments gets translated by IE as soon as HTML is parsed to elements, therefore they cannot be manipulated. They're meant to be static and not to be manipulated by javascript.

 You can verify this behavior by going to https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx, open any example, say http://samples.msdn.microsoft.com/workshop/samples/author/misc/ccdh02.htm, open the IE inspector and you won't see any conditional comments in the DOM tree. Even if you add one manually by editing HTML, the comment gets transformed into real HTML elements and the comment itself cannot be seen or edited any more.

**Comment by posva** [comment]
I'll be easier to use a package like browser detect to toggle the content 🙂
