### ISSUE TITLE
'this' pointer in custom directive

### ISSUE THREAD

**Issue by sdouara13** [vuejs/vue#7615]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/96846/](https://jsfiddle.net/50wL7mdz/96846/)

### Steps to reproduce
First, created a directives,like:
Vue.directive('demo', {
	bind: ($el, binding, vnode) => {
    this.$el = $el;
  },
  update: ($el, binding, vnode) => {
    console.log(this.$el);
  }
})

Second, use more then one 'demo' directives, like
<div v-demo="{val:  variable}">1</div>
<div v-demo="{val:  variable}">2</div>
in same view

### What is expected?
When update the variable,the elements output on the console corresponds to the instruction it is bound to.
It should be two different elements.

### What is actually happening?
The elements output on the console  are the last one which has innerHTML as '2'

**Comment by fnlctrl** [comment]
Arrow functions doesn't have its own `this`. Please refer to
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Updated demo: https://jsfiddle.net/fh4qnvba/

**Comment by sqal** [comment]
@sdouara13 also:

> Directives no longer have instances. This means there’s no more this inside directive hooks. Instead, they receive everything they might need as arguments. If you really must persist state across hooks, you can do so on el.

**Comment by sdouara13** [comment]
@sqal I know and I has used this solution，but I don't think it is a good way because the child els may be removed,so I must write another data container to saved the child els' status. To avoid the conflict, The container was connected to the parent el，and it made more redundance or associate.For example,I should destroy the container when I destroy the directive manually.
