### ISSUE TITLE
build project doesn't request main.js

### ISSUE THREAD

**Issue by Maplesog** [vuejs/vue#7619]
### Version
2.5.2

### Reproduction link
[http://test.airspace.cn/](http://test.airspace.cn/)

### Steps to reproduce
1.Clear the browser cache
2.Enter url and dev-tool see if there is a blank page phenomenon. lt's because the main.js doesn't request.
3.Refresh the browser, lt's normal.
4.Open a new browser tab and enter the url, blank page will appear occasionally.

### What is expected?
can reach the site everytime

### What is actually happening?
blank page

main.js
```
import Vue from 'vue'
import Vuex from 'vuex'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '@/config/base'
import * as allFilters from '@/config/filter'
import { category } from '@/config/constant'
import App from '@/App'
import router from '@/router'
import store from '@/store/index'
import '@/directive'


Vue.config.productionTip = false

// Vue.use(Button)
Vue.use(Vuex)
Vue.use(ElementUI, { size: 'small' })

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})

Object.keys(allFilters).forEach((key) => {
  Vue.filter(key, allFilters[key])
})

store.dispatch('dispatchPlaneTypes')
store.dispatch('dispatchPlaneBrands')

process.env.NODE_ENV === 'development' ? console.log(category) : '' //eslint-disable-line

```

**Comment by Maplesog** [comment]
open a new tab and enter a url 
![image](https://user-images.githubusercontent.com/18155748/35951930-894c33a2-0cb8-11e8-92bf-06c409d8f0fd.png)

refresh again and again
![image](https://user-images.githubusercontent.com/18155748/35951949-a08367de-0cb8-11e8-8600-a135bc74fc11.png)

**Comment by yyx990803** [comment]
Sorry but this is not a bug report. We don't help you debug apps.
