### ISSUE TITLE
Using svg in template throws warning 'Do not use built-in or reserved HTML elements as component'

### ISSUE THREAD

**Issue by Cweili** [vuejs/vue#7623]
### Version
2.5.13

### Reproduction link
https://github.com/museui/muse-ui/blob/bdb360b7dfc55a17fa115709b6f2660b20c29b3c/src/circularProgress/circularProgress.vue#L7

### Steps to reproduce
Import this vue component.
See also (Chinese): https://github.com/museui/muse-ui/issues/824

### What is expected?
Working whitout warning.

### What is actually happening?
It throws warning `[Vue warn]: Do not use built-in or reserved HTML elements as component id: circle`.

**Comment by posva** [comment]
You're probably creating a component named `circle`. Couldn't reproduce in a jsfiddle. Next time, please take the time to provide a proper repro using one of the links provided in the vue issue helper, thanks!

**Comment by Cweili** [comment]
@posva It's my mistake. The component `circular.vue` named `circle`. Thanks very much.
