### ISSUE TITLE
Cannot bind checkbox state using v-binded type

### ISSUE THREAD

**Issue by dominikfiala** [vuejs/vue#7624]
### Version
2.5.13

### Reproduction link
[https://codepen.io/dominikfiala/pen/YeNyBL?editors=1010](https://codepen.io/dominikfiala/pen/YeNyBL?editors=1010)

### Steps to reproduce
Let Vue set attribute `[type=checbox]` of `input` element via `v-bind`

### What is expected?
The Vue state should be updated

### What is actually happening?
The Vue state is updated only if I set the input type to checkox explicitly

**Comment by gotraveltoworld** [comment]
You need to change the bind method from `v-bind="configItem.input"` to `v-bind:type="configItem.input.type"`

Copy from your example: https://codepen.io/gotraveltoworld/pen/aqpBRe?editors=1010

Reference: https://vuejs.org/v2/guide/syntax.html#Attributes

**Comment by dominikfiala** [comment]
Thanks @gotraveltoworld  for taking time to reply. This works as expected, but I'm still considering behaviour in my example buggy. 

The API Docs https://vuejs.org/v2/api/#v-bind states:

> When used without an argument, can be used to bind an object containing attribute name-value pairs. Note in this mode class and style does not support Array or Objects.

Example mentioned there:

```
<!-- binding an object of attributes -->
<div v-bind="{ id: someProp, 'other-attr': otherProp }"></div>
```

So whats wrong with my use case?

**Comment by dominikfiala** [comment]
So I altered my example and to my surprise, the solution is to bind `type` argument specifically and then use `v-bind` to bind the rest arguments. I dont understand this behavior.

Updated example: https://codepen.io/dominikfiala/pen/LQxoGa?editors=1010
