### ISSUE TITLE
尤大，不知道vue支不支持使用vue-cli时，html和js和css分文件

### ISSUE THREAD

**Issue by 1316346949** [vuejs/vue#7625]
比如说写了一个组件，并且为这个组件专门创建一个文件夹，在这个文件夹里3个文件分别是html，css，和js。在html(template)里，引入js和css，让每个部分都清晰一目了然。

因为我的一个组件写的比较多，样式比较丰富，html和js和css分为3个文件，让开发者可以分3屏去开发。

**Comment by yyx990803** [comment]
``` vue
<template src="./foo.html"/>
<style src="./foo.css"/>
```
