### ISSUE TITLE
We should access html elements from anywhere

### ISSUE THREAD

**Issue by rasimavci** [vuejs/vue#7627]
### What problem does this feature solve?
I have a vue application along with vuex for webrtcl calls.  In my application U need to use html elements for some JSL API functions, and I should be able to do that.

Due to callbacks from API, I have written most of the functions in my store.js, but from there I can not access to html elements..

I need to send html elements to some callback function but I can not access them.

I need to access html elements defined inside component template / modal template from different components,  but chrome gives me error.

### What does the proposed API look like?
We should access html elements from anywhere, like if I have an element, I should access it by getElementsById etc.

**Comment by posva** [comment]
Nothing prevents you from using getElementById in your code. You can also pass the elements around when dispatching actions
Closing since there's nothing in Vue preventing you to access the HTML elements, this looks more like a question: you should check the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions

**Comment by rasimavci** [comment]
Hey of course I already used getElementById but it gives me error. I already asked this on the forum but couldnt get an answer, please provide me a solution before closing this.

**Comment by rasimavci** [comment]
Are you sure I can pass an html element via action ? Those kind of things get lost when passing if you are working with a bundled code, I can prove that to you, please help me on this.

**Comment by posva** [comment]
You cannot just come and ask a question just because you didn't have an answer on the forum or the chat, we keep issues for bug reports and feature request, please respect that. Maybe\try sharing some code in the forum question. It's more likely for people to help you if you provide code 🙂

**Comment by rasimavci** [comment]
How you know that I did not share code ? so can you help me on that element problem, I realy realy need help from people that known vuejs very well.

**Comment by sirlancelot** [comment]
In your template, add `ref` tag and name it, then when you need to send it somewhere, pass it as an argument as usual. [`ref documentation](https://vuejs.org/v2/api/#ref)
