### ISSUE TITLE
Consider having an additional naming convention on single file component 

### ISSUE THREAD

**Issue by ytbryan** [vuejs/vue#7629]
### What problem does this feature solve?
Will you consider having an additional naming convention for single file component? Within the same directory, autoload the .js and .css that have the same file name as the .vue file? 

This will help those who use​ single file component with separation of concern to reduce code. 

### What does the proposed API look like?

```
<!— file.vue —>
<template> 
<div></div>
</template>

<!— Not required to write these due to naming convention —> 
<script src=“./file.js”></script>
<style href=“./file.css”></style>
```

**Comment by yyx990803** [comment]
I think it's better to be explicit than to be magical. This can IMO easily be made painless with an editor snippet.
