### ISSUE TITLE
VSCode ESLint按 airbnb 规范解析 vue 文件有误

### ISSUE THREAD

**Issue by wilfordw** [vuejs/vue#7630]
VSCode Version 1.20.0

Setting

```json
    "eslint.autoFixOnSave": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "html",
        "vue"
    ],
    "eslint.options": {
        "plugins": [
            "html"
        ]
    },
    "eslint.alwaysShowStatus": true,
```
.eslintrc.js
```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true,
  },
  // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
  // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
  extends: ['plugin:vue/essential', 'airbnb-base'],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // chec
```
配置完成后 js 文件可以正常验证 airbnb 规范
![image](https://user-images.githubusercontent.com/6120793/36008757-d6c154c0-0d83-11e8-9674-0e4e1542ae54.png)
但 vue 文件只能验证部分规范 
![image](https://user-images.githubusercontent.com/6120793/36008844-3cf07906-0d84-11e8-8bfe-115f34686377.png)
![image](https://user-images.githubusercontent.com/6120793/36008854-42fb56e0-0d84-11e8-9559-945e0517e5fa.png)
但像 Missing semicolon 这样的规范就无法识别
![image](https://user-images.githubusercontent.com/6120793/36008871-571d7fea-0d84-11e8-9044-0d5fadc7a186.png)

但运行`npm run dev` 是可以识别
![image](https://user-images.githubusercontent.com/6120793/36008906-8f643e7a-0d84-11e8-98bb-9a1790338e3e.png)

这让我很迷茫，到底问题是出在哪，求大神帮忙，网上能找的配置已经都试过了，都无法解决

**Comment by yyx990803** [comment]
https://github.com/vuejs/eslint-plugin-vue
