### ISSUE TITLE
warn when assignment in v-if in development mode

### ISSUE THREAD

**Issue by mu-yu** [vuejs/vue#7631]
### What problem does this feature solve?
this may fix errors made by misktake quickly.
e.g.:
there is a piece of code like `v-if="a=b"`, but what I want is `v-if="a===b"`

### What does the proposed API look like?
nothing here

**Comment by posva** [comment]
this is a **js** common pitfall for beginners, not Vue. It should be said on your editor by a linter (https://github.com/vuejs/eslint-plugin-vue)
