### ISSUE TITLE
The selector name  can't use special symbols.

### ISSUE THREAD

**Issue by NineSay** [vuejs/vue#7637]
### Version
2.5.13

### Reproduction link
[https://codepen.io/ninesay/pen/MQpRZb](https://codepen.io/ninesay/pen/MQpRZb)

### Steps to reproduce
The selector name cannot contain '-'.

### What is expected?
The selector name contain '-' can work

### What is actually happening?
The selector name contain '-' cannot work

---
No

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. This is due to the fact that JavaScript object literals cannot have `-` in its key. Please quote the key instead: 
```html
<button v-bind:class="{ 'text-red': isActive }">Click</button>
```
