### ISSUE TITLE
How to use webpack dllplugin in server side rendering scenario?

### ISSUE THREAD

**Issue by stoneChen** [vuejs/vue#7638]
### What problem does this feature solve?
Webpack dllPlugin can reduce build time.
The client build has been already done. But how can I write the code to use dllPlugin in server side rendering? Where should I put the vendor bundle in?

### What does the proposed API look like?
noop

**Comment by JounQin** [comment]
https://github.com/JounQin/Rubick/blob/master/server/dev.ts#L51

I'm doing like this.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by stoneChen** [comment]
@JounQin thank you for help, but my dll bundle is pre-built, and it is uploaded to cdn.
Later, I think it may be not necessary to write dll file into webpack mfs. Just use dllPlugin in webpack for server build. Because the  require statement in built app bundle is like `require('vue')`, which is a normal node require statement. So it will be fine.

**Comment by JounQin** [comment]
My sharing codes are only for development, you can simply add dll script into your template html like https://github.com/JounQin/Rubick/blob/master/server/template.pug#L16 and https://github.com/JounQin/Rubick/blob/master/server/index.ts#L216 .

**Comment by stoneChen** [comment]
Yeah, this script is necessary.
