### ISSUE TITLE
无法获取未定义或 null 引用的属性“split”

### ISSUE THREAD

**Issue by Mohaiyo** [vuejs/vue#7639]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/mohaiyo/50wL7mdz/97951/](https://jsfiddle.net/mohaiyo/50wL7mdz/97951/)

### Steps to reproduce
Step1: copy the code from jsfiddle to an index.html (I'm sorry but the jsfiddle don't support the IE9 document mode so you have to reproduce this bug this way)

Step2: open the index.html file by IE browser or 360 browser

Step3: F12 Open the debugger. Choose the userAgent IE10 or IE11(must be 360 browser ) by simulation tool

step4:click the datePicker component then you can see the error--无法获取未定义或 null 引用的属性“split”

### What is expected?
There is no error on IE when the browser mode(IE10 or IE11) incompatible with the document(IE9) mode .

I know this bug is caused by transition,but how can I fix it?

### What is actually happening?
There is an error "无法获取未定义或 null 引用的属性“split”" when js run!

---
can vue add an feature to remove tansition?

**Comment by yyx990803** [comment]
这是 Element UI 相关的问题，不要到 Vue 这里来报

**Comment by Mohaiyo** [comment]
Got it,thx1

**Comment by Mohaiyo** [comment]
Got it,Thx!
