### ISSUE TITLE
width/height/... without unit in style bindings should give a warning in dev. mode

### ISSUE THREAD

**Issue by spaceemotion** [vuejs/vue#7642]
### What problem does this feature solve?
I had this really bad brainfart today where I was trying to figure out why my elements weren't updating their width correctly. I eventually found out that I was missing the "px" in my bindings and everything was fine again.

Imo, It would be helpful to warn the author (at least in development mode) that the binding is just a pure number which might not be what the developer intended.

This could also be used for other properties like height, paddings and margins.

### What does the proposed API look like?
Not an API, just a warning: "The width/height/... is a pure number, maybe you're missing its unit?"

**Comment by posva** [comment]
This would mean we have to check for all properties that accept units (or do the opposite, checking no unit is provided) that a unit is provided. There're many possible units (%, em, rem, px, %, s, ms) as well, so people will probably expect that we check for the validity of these units (prevent typos like pb (depends on the keyboard))

If you try on a plain page to set the style of an element with just a number, you'll see that the browser doesn't print any warning or error, it doesn't even add it to the element, it just ignores it. So, to me, this is a browser problem that all front-end libraries suffer from. I'd rather see a warning in the browser console than a warning emitted by all the different front-end frameworks

IMO, this should not belong to Vue.

**Comment by spaceemotion** [comment]
While this is true, and also a good alternate behavior that would at least lead to/hint at the path of "discovering why it's not working"; Vue converted the number without a unit to a simple "0px" – which is not an invalid value at all.

**Comment by LinusBorg** [comment]
> Vue converted the number without a unit to a simple "0px" 

That would be strange. AFAIK Vue doesn't mess with the strings in style bindings in any way.

**Comment by posva** [comment]
Vue doesn't convert the unit. 0 in absolute, it works in all units, so it doesn't need one 🙂 
Try in the console `someElement.style.marginLeft = 50` and you will see **nothing happens**

**Comment by spaceemotion** [comment]
The following example is not updating the input's width correctly (stuck at 0px), unless I specifically add a "px" unit in the style binding: https://jsfiddle.net/4g72htct/7/

**Comment by Hanks10100** [comment]
I think warn about styles in the front-end framework is not a good idea. Style behaviors are defined by the specific platform, put warnings in a plugin is more appropriate. 

By the way, CSS length could be a number without any unit in [Weex](http://weex-project.io/guide/), it'll be seen as taking a default `px` unit. In another word, pass number to `width` or `height` could be valid when using Vue (on Weex).

**Comment by LinusBorg** [comment]
@spacemon Ys, that'S the expected behaviour - Just like the Guide shows, Vue doesn'T add `px` itself, you have to add it: 

https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles

As posva explained, validating CSS syntax even only in development is surely too complex to integrate.

**Comment by spaceemotion** [comment]
Alright, seeing as @Hanks10100 mentions this is even a feature in Weex and the guide has a section on it (must have missed that), this is fine as-is I guess. Just something to put on my "doesn't work? check this"-list :)
