### ISSUE TITLE
Different nested transitions not working as expected, only root transition gets applied

### ISSUE THREAD

**Issue by uikid** [vuejs/vue#7643]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/4kf9egr3/](https://jsfiddle.net/4kf9egr3/)

### Steps to reproduce
Create a transition inside a transition with different effects.

### What is expected?
Two different effects should be shown.

### What is actually happening?
Only the effect of the root transition is shown.

**Comment by posva** [comment]
You need to add `appear` to the nested one as it's just appearing so it doesn't apply the transition the first time is rendered 🙂

**Comment by uikid** [comment]
@posva thanks, but this is not working when used inside a single file component, same code.

Any ideas why?

**Comment by LinusBorg** [comment]
That should work just as well. Create a reprodiuction and open an issue if you can reproduce it.

**Comment by anuoua** [comment]
@posva @LinusBorg  Hi, i tried, and i found that leave transition is missing, just enter transition work with appear attribute, help please.

**Comment by posva** [comment]
yes, that is intended, you need to use the `appear` prop
