### ISSUE TITLE
filter is executed on route change

### ISSUE THREAD

**Issue by nikugogoi** [vuejs/vue#7644]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/99316/](https://jsfiddle.net/50wL7mdz/99316/)

### Steps to reproduce
alert pop up at start indicates filter being called
on route change alert pop ups again meaning filter executed again

### What is expected?
filter should not be called on route change?

### What is actually happening?
filter called on route change

---
is this behaviour normal?

**Comment by yyx990803** [comment]
This is expected behavior, router view is a functional component, so it registers the route as a dependency to the component that is using it.
