### ISSUE TITLE
v-on:keyup.enter does not work on Android

### ISSUE THREAD

**Issue by leonardo-sj** [vuejs/vue#7651]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/101586/](https://jsfiddle.net/50wL7mdz/101586/)

### Steps to reproduce
1. Open the link of minimal reproduction on Android Chrome Browser
2. Click in the second field (that contains the text "Hello Vue.js!")
3. Click at the enter key 

### What is expected?
An alert box with the message "Hello Vue.js!" should have been shown.

### What is actually happening?
Nothing. Apparently Android does not recognize the command v-on:keyup.enter and the focus is just changed to the next field.

---
Maybe it's something related to https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229 , but it may lead to errors in sites that use Vue when accessed via mobile.

**Comment by yyx990803** [comment]
When you use the `->` button on Android there is no `keyup` event at all. This is not something Vue can fix. When you need your site to work on mobile you should avoid relying on keyup events for submit logic.
