### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [vuejs/vue#7659]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by leopiccionia** [comment]
There's an WIP translation effort [here](https://github.com/vuejs-es/vuejs.org). I don't know if it's active or not, but I'd suggest to get in touch. Anyway, the correct repo for discussing documentation, including translations, is [vuejs/vuejs.org](https://github.com/vuejs-es/vuejs.org).
