### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [vuejs/vue#7660]
### What problem does this feature solve?
Hello, I would like to collaborate with the Spanish translation, is it done?

### What does the proposed API look like?
 I would like to collaborate with the Spanish translation, is it done?

**Comment by leopiccionia** [comment]
There's an WIP translation effort [here](https://github.com/vuejs-es/vuejs.org). I don't know if it's active or not, but I'd suggest to get in touch. Anyway, the correct repo for discussing documentation, including translations, is [vuejs/vuejs.org](https://github.com/vuejs-es/vuejs.org).

**Comment by CH19** [comment]
hi i want contribuite to spanish translation of the documentation, how i do this
