### ISSUE TITLE
动态切换transition的enter/leave-active-class与name属性导致动画效果无效

### ISSUE THREAD

**Issue by singlexyz** [vuejs/vue#7667]
### Version
2.5.13

### Reproduction link
[https://codepen.io/nayuxuohz/pen/wyyQzY](https://codepen.io/nayuxuohz/pen/wyyQzY)

### Steps to reproduce
1. 点击显示，显示动画。 
2. 点击切换再点显示动画不显示，会跳过动画直接出现或消失。点击还原。
3. 同2

### What is expected?
动态改变值后依旧显示动画

### What is actually happening?
动态改变值后跳过动画显示结果

---
当transition使用name属性的css transition用法时，动态切换值后动画不可用，但在切换回原本值后显示正常

**Comment by posva** [comment]
Translate may not be doing a good job but it looks to me that you want a way to abort a transition

**Comment by yaodingyd** [comment]
你的`animationSwitch`方法中模版字符串漏了`${}`:

```
animationSwitch (enter, leave) {
	this.enterClass = `animated ${enter}`
	this.leaveClass = `animated ${leave}`
}
```

**Comment by fnlctrl** [comment]
同@yaodingyd，是例子中写错了，修改以后正常工作：https://codepen.io/anon/pen/MQVyjG
