### ISSUE TITLE
Assign :ref to zero result in missing element in $refs

### ISSUE THREAD

**Issue by Nattapong-sir** [vuejs/vue#7669]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/hhu05cd2/18/](https://jsfiddle.net/hhu05cd2/18/)

### Steps to reproduce
Assign any element with ref to 0.
Such as <p :ref="0"></p>

### What is expected?
p exist in $refs

### What is actually happening?
p isn't in $refs

---
Workaround is to put additional char to :ref such as
<p :ref="a0"></p>

Now, that p will be in this.$refs.

Reference: https://forum.vuejs.org/t/element-with-ref-0-disappear-from-refs/27925

**Comment by sqal** [comment]
Looks like a bug. Probably [this check](https://github.com/vuejs/vue/blob/956756b1be7084daf8b6afb92ac0da7c24cde2a5/src/core/vdom/modules/ref.js#L22) should be replaced with `if (!isDef(key)) return`
