### ISSUE TITLE
Computed documentation does not mention lazy evaluation

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue#7672]
### What problem does this feature solve?
Truth is: Computed variables are evaluated lazily.

Documentation says: Computed props are evaluated any time the underlying data is changed.

Difference is, computed props are often not re-evaluated when underlying data changes (when in development for example, and no template yet consumes it, or, when hidden due to conditional rendering)

### What does the proposed API look like?
Please add a special note/caveat (red exclamation point), explaining the lazy evaluation of computed props, and suggest that a watcher be used if continuous evaluation is required.

**Comment by yyx990803** [comment]
https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods

**Comment by yyx990803** [comment]
@FEA5T if, as you described, computed properties "are often not re-evaluated when underlying data changes", then it's a bug, because we are not aware of such situations. In that case, you need to provide a bug report with reproductions.

**Comment by FEA5T** [comment]
@yyx990803  True or false:

If a computed property is not used in dom or anywhere else, it will not re-evaluate even when data changes.

**Comment by LinusBorg** [comment]
@yyx990803 I had a long discussion with FEA5T on the forums. What he mainly refers to is that computed props are only evaluated when they are accessed. until you access it (directly or indirectly in the render function, for example), there won't be a value in devtools, for example.

**Comment by FEA5T** [comment]
@LinusBorg Thanks for translating.

I do apologize for posting in the wrong repo, I didn't see that one initially, thanks for the tip.

**Comment by FEA5T** [comment]
This is related to the issue mentioned here as well: https://github.com/vuejs/vue-devtools/issues/393

User's do not understand why computed props are not updated before being accessed - which I think is critical to point out because otherwise it can be mistaken as a bug and be a source of frustration.
