### ISSUE TITLE
Better watcher syntax

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue#7673]
### What problem does this feature solve?
Multi dependency watchers scale poorly (exponentially poorly https://jsfiddle.net/5oepaa9o/120/).

While typically a computed function would be used, in many cases a user needs non-lazy evaluation, OR they need to cause side effects from a multi dependency watcher.  In these cases, current watcher syntax is too verbose (see fiddle above).

### What does the proposed API look like?
```
  watch: {
  	'x, y': function () {
    	    return this.x   this.y;
    }
  }
```

**Comment by yyx990803** [comment]
Use the imperative API:

``` js
```

**Comment by FEA5T** [comment]
The imperative api has to be called in a lifecycle hook, which to some degree defies the point of a watch as a simple, semantic convenience layer over these internal api's.  

Of course I could use the watch api, and I can solve the solution this way, but do you think it is worthwhile to give users a watch syntax that can track multiple dependencies from the beginning?  Or at least leaving it up to consideration/discussion vs closing prematurely?

**Comment by LinusBorg** [comment]
@FEA5T I thought a bit about this and you can easily build this yourself:
```Vue.mixin({
  beforeCreate() {
    // this.$options.watch gives you the watch definitions object. 
    // You can now check the keys of that object, and construct a valid watcher function from it:
    // i.e. turn 'x,y' into function () { return [this.x, this.y]}
    // then remove the original watcher and dynamically add a `created` hook to $options that uses the imperative API to add a watcher for it
  }
})

**Comment by FEA5T** [comment]
@LinusBorg I too thought about this, but in the end my number 1 priority is to keep components as clean as possible, and also consistent with documentation so that others can reuse and edit them.

So yes, I could add this code to my component, or even fork vue, doing the code you just mentioned on every component, but as soon as I cross that line, my code is no longer consistent and understandable.

I also do not know the internals very well yet which is why it is a lot easier to just yell at you guys
