### ISSUE TITLE
Vue does not warn when computed prop is never consumed anywhere

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue#7674]
### What problem does this feature solve?
Because computed props are lazily evaluated, a computed prop that is never consumed will only be evaluated once.  This is misleading because it has the appearance in chrome and vue devtools of a reactivity failure.  This is not the expected behavior that a developer would assume while writing computed props (possibly before they have consumed this prop in dom), and a console warning should appropriately explain this.  It is very natural to write computed props and inspect them before consuming (because consuming them depends on the prop being written).  As such this has for a very long time been a source of confusion and unpredictability.

### What does the proposed API look like?
```
> Computed property 'x' will not become reactive until it is consumed in a template/dom.
```

**Comment by yyx990803** [comment]
Please provide a proper reproduction if you believe this behavior is not correct or misleading. Jumping directly to feature requests makes it difficult to evaluate because there's not enough context.

**Comment by LinusBorg** [comment]
@FEA5T I thought about this a bit more and a warning like this doesn't make sense.

It's perfectly normal that a computed prop will not be collected as a dependency on initial render, if it's only used in a part of the template that's conditionally not rendered yet.

So this would create strange warnings for perfectly fine situations, and on the other hand, only be useful in very rare ones.

So While I think Evan misunderstood your request a bit, I would agree to keep it closed as it's not really doable in a way that's not creating unnecessary and misleading warnings.

**Comment by FEA5T** [comment]
@LinusBorg  I was thinking it would warn only if the computed prop is never consumed anywhere (including conditional logic, and other computed's).  This way there would be no extra warnings.  The idea is to warn for computed props that are legitimately unused, where there is no possibility of them ever being used in current logic.

**Comment by LinusBorg** [comment]
>  I was thinking it would warn only if the computed prop is never consumed anywhere 

That would require Vue to go meta on a component and analyse and understand its own code and data flow. That won't even be possible if we included Babel into Vue.

So generating a warning is out of the question. you could *maybe* write an eslint rule (for eslint-plugin-vue) that statically checks this, but I'm not sure eslint can be that clever.

**Comment by FEA5T** [comment]
I was afraid you would say that :)
