### ISSUE TITLE
@keypress.prevent not preventing caret on input from moving

### ISSUE THREAD

**Issue by VengadoraVG** [vuejs/vue#7675]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/xby1x7yy/3/](https://jsfiddle.net/xby1x7yy/3/)

### Steps to reproduce
1. click on the input
2. press up, right, down or left arrow.

### What is expected?
the caret on the input doesn't move.

### What is actually happening?
the caret on the input is moving.

**Comment by yyx990803** [comment]
Because you need to use `keydown` instead of `keypress` (even without Vue)
