### ISSUE TITLE
How to pass data/prop to root vue instance

### ISSUE THREAD

**Issue by rajjanorkar** [vuejs/vue#7677]
### Version
2.5.13

### Reproduction link
[https://vuejs.org/v2/guide/index.html](https://vuejs.org/v2/guide/index.html)

### Steps to reproduce

```
<div id="app">
  {{ message }}
</div>

var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```

This is one way data passing from vue to dom, how i can transfer from dom to vue e.g.

```
<div id="app" :data='My Data came from other part'>
  {{ message }}
</div>
```

please note this is not about sub component, this is about root node.

### What is expected?
Sometime other part of html doing some thing and that needs to be passed to vue root instance.

### What is actually happening?
I could not figure out how i can pass the data to root vue instance.

**Comment by sirlancelot** [comment]
The root Vue component is always created in JavaScript land so you would pass data to using standard JavaScript objects. If you want to query the DOM for your data that's up to you to do.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Maybe you're looking for `propsData`
