### ISSUE TITLE
Writable $isServer

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue#7684]
### What problem does this feature solve?
We've added a `renderToString` method in vue-test-utils, which is a wrapper around `vue-server-renderer` `renderToStrting`. This let's users test SSR code without a `window`.

Sometimes users will be running tests for SSR code and browser target code in the same process, where window will be defined. This means `$isServer` will be false, even though we're rendering with the server-renderer.

### What does the proposed API look like?
I'm unsure of the best way to do this.

One solution is to make `$isServer` writable

**Comment by eddyerburgh** [comment]
@yyx990803 Can we remove the `inBrowser` check from this line—https://github.com/vuejs/vue/blob/dev/src/core/util/env.js#L41?

**Comment by yyx990803** [comment]
@eddyerburgh is it for simulating SSR by mocking `global` in a browser environment?

**Comment by eddyerburgh** [comment]
No, it would be for running unit tests for server-side code in the same process as tests for client-side code. 

Vue Test Utils is now two packages—vue/test-utils and vue/server-test-utils. It would be great to run tests using both libraries in the same process, and have isServer set differently depending on the method used:

```html
<!-- TestComponent.vue -->
<template>
  <h1 v-if="$isServer">Yes</h1><h1 v-else>No</h1>
</template>
```
```js
import { renderToString } from '@vue/server-test-utils'
import { shallow } from '@vue/test-utils'

renderToString(TestComponent) // '<h1>Yes</h1>'
shallow(TestComponent).html() // '<h1>No</h1>'
```

**Comment by eddyerburgh** [comment]
I think we should leave it to users to run tests for SSR code in the correct environment. Making isServer writable makes it possible to write tests that pass, but fail in production.
