### ISSUE TITLE
Strange behavior with setInterval

### ISSUE THREAD

**Issue by jasedu** [vuejs/vue#7686]
### Version
2.5.13

### Reproduction link
(https://jsfiddle.net/pc9qa8yt/138/)

### Steps to reproduce
1) create a simple square of 100*100
2) v-model an input to  changethe width and height styling
3) create a method that, upon pressing enter stepwise undos the alteration of the width, reseting it back to 100

here is my HTML

```
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>

<div id ="app">
  <div class="demo" :style="myStyle"></div>
  <hr> 
  <p>
  {{dif}}
  </p>
  <input type="text" v-model="width" @keydown.enter="calculate()">
</div>
```
JS:

```
new Vue({
	el: '#app',
  data: {
   width: 100,
   dif: 0
  },
  computed: {
    myStyle: function(){
    	return {
    		width: this.width + 'px',
      	height: this.width + 'px',
      }     
    }
  },
  methods: {
    calculate: function() {
    	let vm = this;
      if (this.width > 100) this.dif=(-1);
      if (this.width < 100) this.dif=(1);
      if (this.width === 100) this.dif= 0;
      let calc = setInterval(function(){
      	if (vm.width !== 100) { vm.width+= vm.dif} else {
         clearInterval(calc);
         vm.width= 100;
         }      
      }, 1);
    }
  },
});
```
CSS:

```
.demo{
  width: 100px;
  height: 100px;
  background-color: gray;
  display: inline-block;
  margin: 10px;
}
```

### What is expected?
Following the function, I expect that block will reset  to 100px width after after an input; 

### What is actually happening?
the value of width becomes: width +  "dif", so
10 becomes 101 becomes 1011

---
Strange thing is, if I use:

    let calc = setInterval(function(){
      	if (vm.width !== 100) { vm.width-= vm.dif} else { 
         clearInterval(calc);
         vm.width= 100;
         }      
      }, 1);

and reverse the dif value for the 100> or 100< condition, it works fine

**Comment by javoski** [comment]
The value you got from `<input>` is a **String**, the `.number` modifier will be helpful.
```html
<input type="text" v-model.number="width" @keydown.enter="calculate()">
```

**Comment by jasedu** [comment]
Thanks for the quick reply, Works as a charm :)
