### ISSUE TITLE
Array properties are not reactives

### ISSUE THREAD

**Issue by frlinw** [vuejs/vue#7690]
### Version
2.5.13

### Reproduction link
[https://codepen.io/frlinw/pen/xYzWdv](https://codepen.io/frlinw/pen/xYzWdv)

### Steps to reproduce
- Click on the "Change array property" button: array `$test` property is not reactive
- Click on the "Change array property and push" button: an item is added to the array, the property `$test` is reactive

### What is expected?
array property should be reactive in both case

### What is actually happening?
array property is not reactive if the array does not change

---
- How to have reactivity on array properties even if the length of the array does not change ?
- Use of Proxies in 2.6-next will fix this issue ?

Use case: 
- init an array with $isLoading property set to true
- fetch the db:
-> X results from the db, add items to the array and set $isLoading to false -> reactive, great !
-> No result from the db, the array itself does not change, set $isLoading property to false -> no reactivity, stay in loading state.

**Comment by yyx990803** [comment]
This is not supported and it is intentional, because extra properties on Arrays are not JSON-encodable.

**Comment by frlinw** [comment]
So it won't work even with future v2.6-next?

**Comment by frlinw** [comment]
My point here is consistency:
1) reassign a different empty array:  extra properties are reactives
2) change array content: extra properties are reactives
3) change an extra property on the same array: extra properties are not reactives

Extra properties on array are not JSON-encodable, so it's impossible to get 3) to work ? or it is just you don't want to support it?

**Comment by yyx990803** [comment]
The property itself is never reactive. When you reassign or change the array's content, it triggers the component to rerender which accidentally pulls the latest value of that property, but **the update was not caused by that property**.

This is not a technical limitation, but a best-practice enforcement. If your state is not JSON-encodable, it leads to problems in debugging tools and server-side rendering.

**Comment by frlinw** [comment]
I know there are no getters/setters for array extra properties, I meant it feels like it's reactive and it is confusing.
So, to have reactives metadata on an array, you have to wrap it in an object, it's not a big deal but... well... arrays are objects

Thanks for the explaination about ssr & debug needs

**Comment by wenber** [comment]
use “new Proxy”  Instead  "Object.defineProperty"  can trigger getter method  。 eg:   
data() {return  {cities = ['UK', 'BK'];}}             when you   set   this.cities[0] =  'BJ';     so  why not use new Proxy ?

**Comment by frlinw** [comment]
@wenber Proxy will be used in Vue 3
Anyway the thread was about array properties, not array indexes
