### ISSUE TITLE
IE11 Internet explorer opens the white screen

### ISSUE THREAD

**Issue by ripeBoy** [vuejs/vue#7696]
### Version
2.5.13

### Reproduction link
[http://The project is more complex and has not been located to the specific problems.](http://The project is more complex and has not been located to the specific problems.)

### Steps to reproduce
Build with vue-cli. After the project development is completed, use chrome to open normal, and IE11 opens the white screen.

### What is expected?
Open and use applications normally.

### What is actually happening?
hang

---
Console error:  strict 模式下不允许一个属性有多个定义

**Comment by jangjoe** [comment]
I guess it's a problem of webpack-dev-server instead of vue. Try replace all `const` and `let` with `var` in your `node_modules/webpack-dev-server/client` directory. Because IE won't recognize them and babel won't work here. Anyway, that's how I solved mine, worth a try.

**Comment by posva** [comment]
We cannot do much without a minimal reproduction 🙂 
Consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to ask for help, but you will need to share some of your code if you want others to help you 😉
