### ISSUE TITLE
Contenteditable @input doesn't fire in IE11

### ISSUE THREAD

**Issue by Horsetoast** [vuejs/vue#7697]
### Version
2.5.13

### Reproduction link
[https://codepen.io/supraniti/pen/Lypobx](https://codepen.io/supraniti/pen/Lypobx)

### Steps to reproduce
Create a contenteditable with @input event binder and test in IE11 (Possibly happening with all IE9  according to my searches)

### What is expected?
It should fire the input event

### What is actually happening?
It doesn't fire the input event

---
The same problem found in medium-editor https://github.com/yabwe/medium-editor/issues/394 the issue contains a proposed fix(?)

**Comment by posva** [comment]
This is an ie problem not firing the input event, it happens without vue. You will have to listen to another event that is also emitted by ie
