### ISSUE TITLE
请问自定义指令支持绑定函数不自动执行吗？

### ISSUE THREAD

**Issue by DMQ** [vuejs/vue#7699]
### What problem does this feature solve?
```
<button v-test="test.bind(this, 'something')"></button>

-->

<button v-test="test('something')"></button>
```

### What does the proposed API look like?
```
<button v-test="test('something')"></button>
```

**Comment by JounQin** [comment]
Maybe are you meaning `v-test`?

**Comment by DMQ** [comment]
@JounQin Yeah! I changed the description.

**Comment by jangjoe** [comment]
Perhaps it means to behave like so. v-on works this way when something like `callSomeFunc(argA, argB)` passed to it, sure it shouldn't be executed when the template is parsed but when event is emitted.

**Comment by DMQ** [comment]
@jangjoe Exactly!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
