### ISSUE TITLE
Events with modifiers always return "undefined"

### ISSUE THREAD

**Issue by STUkh** [vuejs/vue#7705]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/ybr5s354/15/](https://jsfiddle.net/ybr5s354/15/)

### Steps to reproduce
1. Create event with any modifier
2. Create directive and get event instance from vnode.
3. Call event (maybe dummy event will required)

### What is expected?
Event with and without modifiers return function value

### What is actually happening?
Only event without modifier return value.
Events with modifiers always return undefined

---
Fixed in this PR: https://github.com/vuejs/vue/pull/7704

**Comment by STUkh** [comment]
#7704

**Comment by yyx990803** [comment]
Closed via #7704
