### ISSUE TITLE
Class change for transition not working in mounted lifecycle

### ISSUE THREAD

**Issue by kingofwhales** [vuejs/vue#7706]
### Version
2.5.13

### Reproduction link
[https://codepen.io/asiankingofwhales/pen/qxMZrp](https://codepen.io/asiankingofwhales/pen/qxMZrp)

### Steps to reproduce
1. After the component is mounted change the class to initiate the transition.
2. Not working because the element snaps from left to right without transition

### What is expected?
The element should gradually transition from left to right

### What is actually happening?
the element jumps from left to right.

---
Wrapping the class change in setTimeout would allow the transition effect to work. However, without the setTimeout, the element simply jumps from left to right. 

Same issue can be replicated in class binding too: https://codepen.io/asiankingofwhales/pen/LQJNvg

I apologize if this is not a bug but it's been a mystery for a while so i am posting here as a last resort.

p.s
https://stackoverflow.com/questions/48658868/class-change-in-mounted-not-triggering-transition-vuejs
https://forum.vuejs.org/t/class-change-in-mounted-not-triggering-transition-vuejs/27115/4

**Comment by posva** [comment]
If you add the class right after the element being added to the DOM, the browser will not be able to trigger a CSS transition because when the browser checks the transform it also check what transform was being applied before, which turns out to be none, therefore it skips the transition. That's why you need some `setTimeout` or `requestAnimationFrame` to make it work.
Here's a demo with no Vue 🙂 

```js
const a = document.createElement('div')
a.textContent = 'fa'
a.classList.add('test')
document.body.appendChild(a)
a.classList.add('loaded')
```

**Comment by kingofwhales** [comment]
From my previous understanding, transition doesn't work in the vanilla js example because event loop has to finish the task queue and clear the stack first before it can proceed to render queue. So in this case, when it first renders, it's already rendering the element with both "test" and "loaded" class, and thus no transition. (Possible reference:https://youtu.be/cCOL7MC4Pl0?t=11m12s . :pensive:)

However in the Vue case, I thought that Mounted means: only executing these code after component has already been mounted and RENDERED. So there should already be an initial transition state being rendered first?  It's different from the vanilla js case because that one's initial state is already an element with both "test" and "loaded" class?

**Comment by MartinMa** [comment]
What is the way to go here? I had to use a double `requestAnimationFrame` to make it work. But it feels dirty. 💩 

I have the same problem. I want to trigger a custom transition on one of the elements in my component when it is mounted by switching a css class.
