### ISSUE TITLE
can Vue get the new props data in hook activated ?

### ISSUE THREAD

**Issue by greedying** [vuejs/vue#7709]
### What problem does this feature solve?
Let suppose I have a component child, which have a prop id。
the child use keep-alive。
so I query data from server in the  activated。
but I found the prop id' s value is old。

I try to use `this.$nextTick` to get the new id, but not work
`setTimeout`  work, but I do not think it is a right way.

so, is there a way to get the right value of prop data in  activated？ 

### What does the proposed API look like?
just like  `this.$afterProp(function)`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by greedying** [comment]
emm， it is a feature request 。。。
I have some methods to resolve my problem。But vue should give a handsome  one。

**Comment by posva** [comment]
I actually sent the wrong reply.
Your issue looks more like a bug report so we would like to see a boiled down repro 🙂
