### ISSUE TITLE
HTML Keyboard Input element (<kbd>) is not supported

### ISSUE THREAD

**Issue by oanstein** [vuejs/vue#7711]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/128732/](https://jsfiddle.net/50wL7mdz/128732/)

### Steps to reproduce
Just add a `<kbd>` element

### What is expected?
Render `<kdb>` element correctly

### What is actually happening?
[Vue warn]: Unknown custom element: <kdb> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by yaodingyd** [comment]
Is this a valid issue? You misspelled `<kbd>` to `<kdb>`.

**Comment by oanstein** [comment]
@yaodingyd You are right, I misspelled it ...

**Comment by posva** [comment]
Ups, thanks, I didn't see the typo either
