### ISSUE TITLE
Incrementing a variable in a v-for loop increments hundred times more than expected

### ISSUE THREAD

**Issue by david-kiraly** [vuejs/vue#7714]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/us4mwkjv/19/](https://jsfiddle.net/us4mwkjv/19/)

### Steps to reproduce
Click on Run and notice the speed of rendering and the value of the variable "incr" after rendering

### What is expected?
I expect variable "incr" increases to 2 after v-for finishes.

### What is actually happening?
Variable "incr" increases to 306 after v-for finishes and for that my app works slow. I am also getting a Vue error of "may have an infinite update loop" in the console.
I just want to have id-s of 0, 1 and 2 in this example instead of 102, 204 and 306.

**Comment by posva** [comment]
By incrementing the value in the `for` attribute but also reading it, Vue is observing it and rerendering again everytime it changes, so it stops rendering after 300 times

A `v-for` in a template should not modify values. You should use the index of the iteration instead:

```vue
    <div v-for="(fruit, i) in fruits" >
      <input type="checkbox" :id="i">
      <label :for="i">{{ fruit }}</label>
    </div>
```

or some method to compute the value based on other parameters

**Comment by yyx990803** [comment]
Rule of thumb: **never produce side effects in your templates**.
