### ISSUE TITLE
.global or .window modifier for v-on listeners or new property listeners

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#7715]
### What problem does this feature solve?
this solves the issue for components

like keys not being called when it's not focused on the element which leads to doing this

window.addEventListener("keyup",this.event)

then on destroy

window.removeEventListener("keyup",this.event)

this will solve the issue for doing

beforeMount registering of events

and beforeDestroy

so it vue will handle this the Vue way

like handling keycodes

### What does the proposed API look like?
we can do the keyup event like this on an input

@keyup.global="close"

or

@keyup.window="close"

or maybe on the vue instance

listeners: {
  keyup: [this.event]
}

**Comment by posva** [comment]
This can be solved in userland and it actually already exist, we made it together with @shentao 😉 
https://github.com/shentao/vue-global-events
