### ISSUE TITLE
Warnings lead to different behavior between `vue.js` and `vue.min.js`

### ISSUE THREAD

**Issue by ryannhg** [vuejs/vue#7716]
### Version
2.5.13

### Reproduction link
[https://codepen.io/RyanNHG/pen/jZQWaz](https://codepen.io/RyanNHG/pen/jZQWaz)

### Steps to reproduce
Check out the working example (using minified Vue 2.5.13):
https://codepen.io/RyanNHG/pen/gvQPGg

And compare it to this failing example (using dev Vue 2.5.13):
https://codepen.io/RyanNHG/pen/jZQWaz

### What is expected?
I expect the minified and dev versions of Vue to result in the same outcome.

The `fromParent` property is defined on the parent, and I'd expect it to render in the child, even though it isn't explicitly defined on the `data` prop.

Preferably, VueJS warnings wouldn't lead to any components failing to compile.

### What is actually happening?
In the minified, production build, this code works as expected. But in the developer build, I am getting a warning that prevents the component from compiling.

---
I assume this is to prevent me from making a typo, or forgetting to add a data property to my child component.

These warning are super useful in general (thanks for taking the time to make them!)

Let me know if you need any more examples to help you with this issue. Thanks again!

**Comment by yyx990803** [comment]
This is expected behavior.  Inline template doesn't have access to parent scope. In fact, this is one of the reasons why we recommend against using inline templates at all.

**Comment by ryannhg** [comment]
Thanks Evan,

That was a pretty impressive response time!

I added in the code with inline templates because as a simple example. I didn't mean to draw your attention to that aspect of the Github issue.

To clarify, my main concern is that warning was causing the minified and unminified versions of Vue 2.5.13 to do different things.

That lead to my code **working in production**, but not in development. Because I chose to use the unminified version for development.

I've updated the issue name to make it more clear!

Thanks again,
Ryan

**Comment by posva** [comment]
It looks like the warning should no be displayed in that scenario

**Comment by yyx990803** [comment]
No, the warning **should** be displayed. The usage is wrong, so in development it breaks the app.

Since you should not be deploying an app that breaks in development to production, I don't think there's really a need to "fix" this behavior.

The behavior between dev and production is only guaranteed to be consistent when your app works properly in development. In production, a lot of runtime checks are removed because we assume you will fix them in development.

**Comment by posva** [comment]
Ups, sorry, I thought it was failing to parse the `fromChild` property, but I simply misread
