### ISSUE TITLE
怎样计算virtual dom 渲染的耗时

### ISSUE THREAD

**Issue by ireeoo** [vuejs/vue#7719]
### Version
2.5.13

### Reproduction link
[https://reeoo.me](https://reeoo.me)

### Steps to reproduce
比如
在mounted生命周期里面，通过一个方法获取一段数据，然后设置到一个list上，页面进行渲染，这个过程的背后，涉及到virtual dom的计算和渲染，如果我想统计这个计算和渲染的耗时，应该怎么做？

### What is expected?
这不是一个bug report

### What is actually happening?
但是没有合适的分类
具体说明见`Steps to reproduce`

---
上面的demo地址随便写的，因为不需要demo，但是issue模板必须要填。

Thx！

**Comment by coolzjy** [comment]
issue 不是用来问问题的！
issue 不是用来问问题的！
issue 不是用来问问题的！

**Comment by ireeoo** [comment]
@coolzjy issue不是用来探讨和解决问题的嘛？大佬

**Comment by coolzjy** [comment]
<img width="739" alt="2018-02-28 11 31 02" src="https://user-images.githubusercontent.com/3762377/36768644-2cef77d6-1c7b-11e8-9339-d8c9ae531a31.png">
请自行关闭这个 Issue

**Comment by ireeoo** [comment]
@coolzjy I konw了~

**Comment by yxuchen** [comment]
到forum.vuejs.org 用英文提问，core team member 会很高兴回答你，或者google 检索现有问题

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
