### ISSUE TITLE
Unable when passing props to a component to define in which order they should be 'treated'

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue#7723]
### Version
2.5.13

### Reproduction link
[https://codepen.io/AnotherLinuxUser/pen/YedNpv?editors=1010](https://codepen.io/AnotherLinuxUser/pen/YedNpv?editors=1010)

### Steps to reproduce
Given the following template:
```html
<vue-autonumeric
	:options="obj.options"
	v-model="obj.val"
/>
```

If you want to modify both `:value` and `:options` props at the same time, you would proceed by doing:
```js
this.obj = {
    options : 'percentageEU3dec',
    val     : 0.00123456,
};
```

### What is expected?
`options` should be first modified, before `val`.

### What is actually happening?
However, Vue is first taking into account the `obj.val`, **before** the `obj.options`, leading to the vue-autonumeric component to incorrectly update its internal *raw* value with `0.00` instead of `0.00123` (since the `percentageEU3dec` defines the number of allowed decimals to `5`, instead of the default `2`).

The order in which `options` and `val` are set is *super* important for that component, since if you first set the `value`, AutoNumeric will check how many decimal places it needs to keep (and by default it's `2`), which means it will convert the given `0.00123456` to `0.00` first, **before** having had the chance to take into account the `options` `'percentageEU3dec'` that modifies the allowed number of decimal places to `5`.
if it would have first set the `options`, then given the `0.00123456` value, it would have correctly kept 5 decimals `0.00123` which would allow displaying `0,123 %`.

---
So the question here is; is there a way when passing props to a component to define in which order they should be 'treated'?

For instance in the previous example using the `vue-autonumeric` component, I want to modify the `:value` **and** the `:options` at the same time using a single `obj` object, but I need to make sure the `:options` modification in done first before modifying the `value` (otherwise in this particular case the decimal places are dropped).
See [the example](https://codepen.io/AnotherLinuxUser/pen/YedNpv?editors=1010) where you can easily see that 'bug'.

So far, I can reliably get the correct result when I manually first change the `:options`, then change the `:value` in a `nextTick` block.
I was wondering how I could do that *automatically* inside the `vue-autonumeric` component and prevent the user to have to do that manually each time they want to update the options/value.

Some context for this issue: https://github.com/autoNumeric/vue-autoNumeric/issues/10

**Comment by yyx990803** [comment]
IMO this is a problem in the implementation of vue-autonumeric - from your description, the component is using separate watchers to imperatively produce side effects on changes of different values, when these two values are coupled and have order importance.

The correct implementation to get rid of this order dependence is to use a watcher that watches **both** values (watch with a getter function or an expression) and then produce desired side effects - or even better just use computed properties.
