### ISSUE TITLE
Template can't use v-text directive

### ISSUE THREAD

**Issue by lifeiscontent** [vuejs/vue#7726]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/8nq687ywn9](https://codesandbox.io/s/8nq687ywn9)

### Steps to reproduce
check the App.vue file to see that template is not working

### What is expected?
I would expect v-text to work on a template e.g. inject the text received from the data function

### What is actually happening?
it's throwing an error.

**Comment by maxirozay** [comment]
You can use the template tag to wrap elements but why would you use it to display text?

**Comment by yyx990803** [comment]
This is not supported because template is used as a container for structural directives. For text, use double mustaches.

**Comment by lifeiscontent** [comment]
@maxirozay so I don't have to worry about the white space that renders to screen between the tags.

e.g.

```
<template v-text="myData" />
```

vs

```
<template>

  {{myData}}

</template>
```

Working in large teams, this simplifies UI inconsistencies that white space introduces in HTML.

**Comment by lifeiscontent** [comment]
@yyx990803 I just gave you a valid reason why it should.

**Comment by maxirozay** [comment]
As @yyx990803 said use the double mustaches and there's no spaces.
```
<template>
  <div id="app">
    hello {{ hello }}
  </div>
</template>
```
It renders `<div id="app>hello world</div>`
You can also do something like `{{ 'hello ' + hello }}`
