### ISSUE TITLE
Problem when a v-model end with spaces

### ISSUE THREAD

**Issue by Leocardoso94** [vuejs/vue#7730]
### Version
2.5.13

### Reproduction link
[https://codepen.io/leocardoso/pen/OQqNYz?editors=1011](https://codepen.io/leocardoso/pen/OQqNYz?editors=1011)

### Steps to reproduce
Create an input with a v-model like  <input v-model="obj.value " />

And try to change its value

### What is expected?
The value of model change

### What is actually happening?
The value of model doesn't change and it creates a new property to the Object ended with space like obj['value ']

**Comment by pengliheng** [comment]
``

**Comment by yyx990803** [comment]
fixed via #7735 / #7737
