### ISSUE TITLE
components with init value

### ISSUE THREAD

**Issue by thinksource** [vuejs/vue#7732]
### What problem does this feature solve?
I have a dictionary object with certain value is dictionary.
I have arrary of items
items like:

provider:{ id:"", name:"", para:{"name": "what is name", ‘from’:‘beijing’} },

I have  a component to edit those item, when I try to edit para, I use another component.

my first level  of component is like:
```
<table>
  <tr for (v, k) in editDict :key="k">
    <td v-if ...> </td>
     <td  v-else-if="tof(editDict[k]) == 'Object'">
                 <DictInput :inputDict="editDict[k]"></DictInput>
      </td>
     
  </tr>
</table>
```
when the 2nd level of component show it give me error for ：

Property or method "inputDict" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
 See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

I think that is because the first level of Dict object is not determind yet. when it initiallize the secondary level of dictionary.

Can you set a initilal value for the components if it is not find the props value set?

### What does the proposed API look like?
```
export default {
  props:{},
  components:{
    DictInput:DictInput({inputDict:{ "key": "value", "key": "value"}})
  },

}
```
The {inputDict:{ "key": "value", "key": "value"}} as initial value of this component, if later rending, it will bind the value later on.

**Comment by posva** [comment]
You can also skip rendering by using a `v-if` the same way you stop going deeper in non-existant nested object in js:

```js
if (myobj && myobj.nested) {
}
```

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
