### ISSUE TITLE
Allow to override v-model callback

### ISSUE THREAD

**Issue by AndreKR** [vuejs/vue#7736]
### What problem does this feature solve?
`v-model` is great to bind form fields (and child components) to data fields. Unfortunately you cannot currently use it with component props because v-model is effectively `@input="newValue => field = newValue"` and if `field` is a prop it would change the prop, which is not allowed.

If it would be possible to change this `"newValue => field = newValue"` to a custom callback, then you could instead for example emit an event when the form field gets changed. This way you could directly use `v-model` with props and you don't need to copy props into data fields.

### What does the proposed API look like?
In the component whose template contains `v-model`, add a configuration option `modelCallback` that takes a function that will be called when the child component emits their model event:
```javascript
{
  modelCallback: function (modelName, newValue) {
    this.$emit('field_changed', modelName, newValue);
  }
}
```

See this complete example: https://jsfiddle.net/12py3s7n/
(Of course it throws warnings when changing data because `{modelCallback: ...}` isn't actually supported yet.)

**Comment by posva** [comment]
You can use a computed property with a setter (https://vuejs.org/v2/guide/computed.html#Computed-Setter) to emit the event

**Comment by AndreKR** [comment]
Do you mean that as an alternative to the proposed change or just for my information? I could also copy all props to data and use a deep watcher, but the proposed syntax seems still much cleaner. (Actually I don't know how I could implement this with a computed setter.)

See this example: https://jsfiddle.net/np7n0d72/
(Of course it throws warnings when changing data because `{model:{callback: ...}}` isn't actually supported yet.)

**Comment by javoski** [comment]
The [`model` option](https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model) is only for `v-model` on components, not `v-model` on form fields inside components.

**Comment by AndreKR** [comment]
Oh, you are right. `model` is supposed to be given in the child component while my new option is supposed to be given in the component that contains `v-model`. I renamed it to `modelCallback` and I have updated my proposal.

**Comment by posva** [comment]
Having a `modelCallback` isn't quite flexible as an api because `modelName` is just the expression of the v-model which may not be the _name_ of a prop.
On a second thought, this is something that shouldn't be solved with an extra property because it would apply to every v-model and it doesn't feel as intuitive as the rest of the API.

You have two choices, the first one is expanding the `v-model` into one `v-bind` and one `v-on`:

```vue
<input :value="foo" @input="e => $emit('update:foo', e.target.value)" type="text">
```

or to use computed properties with setters: https://jsfiddle.net/g6pp8d9d/
You could also create a helper function that generates those computed properties for you in a similar way to `mapGetters` from Vuex (https://vuex.vuejs.org/en/getters.html#the-mapgetters-helper)

**Comment by AndreKR** [comment]
If the application developer puts an expression (which currently would have to be assignable) in `v-model`, of course he also has to provide a callback that can handle that expression. I see no problem there.
Yes, the point of the new `modelCallback` option is to apply to every v-model in that component, exactly because the default `v => modelName = v` feels like an arbitrary choice and doesn't cover many important use cases.

Manually expanding `v-model` into `:value` and `@input` might work for components (but still less intuitive than `v-model`) but it doesn't work at all for checkboxes, radiobuttons and selects.

Sure, having something like `mapGetters` would be a workaround for the example problem, but it would still require listing all the modelNames and I don't understand why it should be better to force `v => modelName = v` and having the user catch that with a computed setter instead of allowing it to be changed in the first place.

**Comment by posva** [comment]
FYI checkboxes, radios and selects emit `change` events
