### ISSUE TITLE
Ability to disable the compilation of child nodes? 

### ISSUE THREAD

**Issue by vatson** [vuejs/vue#7742]
### Version
2.5.13

### Steps to reproduce
There is an option to disable the interpolation via `v-pre` directive. But there is no way to disable parsing and compiling of custom components. 

The most common case are `<pre>` or `<code>` tags that contain text with custom components:
```
<p> 
  How to use this component
  <pre>
     <my-best-component :class="awesome" blink></my-best-component>
  </pre>
</p>
```
I've tried a lot of options to reach the required functionality but still have nothing.

I would be grateful if you could introduce the way to do it. Thanks.

### What is expected?
The way to disable compilation of child nodes

### What is actually happening?
There is now clear way to do it

**Comment by posva** [comment]
Inside of `pre` and `code` tags you have to escape `<` and `>` yourself (like in regular HTML):

```html
<pre>
	&lt;foo&gt;&lt;/foo&gt;
</pre>
```

Even if Vue ignored that component (there is a config for that), you would still see nothing as HTML would be parsing it

**Comment by vatson** [comment]
@posva I implemented directive that can strip it automatically. But I can not use it because vue compiles it.

**Comment by vatson** [comment]
@posva btw, there is no way to ignore custom components if we are talking about Vue.config.ignoreElements. At first it's global. It ignores ignoring for vue custom components

**Comment by posva** [comment]
Oh, I thought those were not used in your code.
Anyways, as I said, you'll need to escape the caret character, like in regular HTML. If it comes from a string, you can use `v-html` too. If you're looking for a better workflow, you can put those code samples in files (html, vue or other) and use a custom webpack loader to handle the transformation into a string but that goes beyond Vue 🙂

**Comment by vatson** [comment]
@posva  It doesn't comes from string. Just imagine the page with demo of component and description how to use it. Something like this:

```
Toast:
<toast message="Hello" closable></toast>
How to use:
<pre v-raw v-highlight:html>
  <toast message="Hello" closable></toast>
</pre>
```
`v-raw` directive disables compilation of child nodes
`v-highlight:html` is custom directive that escape html code and highlight syntax.

Why not ;)
