### ISSUE TITLE
在360浏览器下IE兼容模式使用vue.min.js,报错InvalidCharacterError vue.min.js

### ISSUE THREAD

**Issue by momtboy** [vuejs/vue#7745]
### Version
2.5.13

### Reproduction link
[https://github.com/momtboy](https://github.com/momtboy)

### Steps to reproduce
在win10环境下 ie版本为ie11
360浏览器手动切换到兼容模式 会报InvalidCharacterError 错误 页面空白

### What is expected?
no error

### What is actually happening?
报错InvalidCharacterError

**Comment by leemove** [comment]
提供一下复现代码会比较好.

**Comment by posva** [comment]
Closing because the provided information is not enough and the error probably comes from your own code being ran on IE 11
