### ISSUE TITLE
Proposition for a better compatibility with jQuery and native events

### ISSUE THREAD

**Issue by GCorbel** [vuejs/vue#7748]
### What problem does this feature solve?
When we have this model this input :

    <input id="test-input" @input="changefoo"></input>

If we do `$('#test-input').val('123').trigger('input')` with jQuery it will not work.

This works :

    var event = new Event('input');
    $('#test-input').val('123')[0].dispatchEvent(event);

I checked in the internal of jQuery and it's looking for a method `element.oninput`.

This works : 

    mounted: function() {
      var self = this;

      $(this.$el).find('#test-input')[0].oninput = function(e) {
        self.foo = e.target.value;
       }
     }

I begin with VueJs so I suppose there is a better way to do the same and find automatically which function should be created.

A better integration with jQuery will simplify transition from and existing code and I suppose it will allow to have a better compatibility with jQuery plugins.

As I said, I begin with Vue so let me know if I'm wrong or if there is a better way.

### What does the proposed API look like?
I have no final code to propose but I think there is a way to add `on[event]` functions when Vue do the binding.

In all cases, I think Vue should have a section about jQuery on the documentation or somewhere else.

**Comment by yyx990803** [comment]
This is because jQuery `trigger` does not actually trigger native events.

Instead of adding logic to Vue to make it work specifically for jQuery, you should make sure you are indeed triggering native events.

https://stackoverflow.com/questions/21290775/jquery-el-triggerchange-doesnt-fire-native-listeners

**Comment by GCorbel** [comment]
It makes sense but what about `document.getElementById('test-input').oninput`. The function will be defined if we do : 

    <input id="test-input" oninput="console.log('blabla')"></input>

But not with : 

    <input id="test-input" oninput="console.log('blabla')"></input>

I think defining `element.oninput` is not provided by jQuery.

In general, what about adding something in the doc to explain how to trigger events and/or something about jQuery? It's a little confusing for new comers.

**Comment by yyx990803** [comment]
Yes, we should probably add a section regarding interop with jQuery. /cc @chrisvfritz

**Comment by GCorbel** [comment]
The best solution I found at the moment is to create a plugin with : 

    $.fn.triggerNative = function(type, options) {
      var event = new Event(type, options);
      this[0].dispatchEvent(event);
      return this;
    }

So we can do : 

    $('#advanced-search .id').val('123').triggerNative('input');

We can also create some helpers for tests, as we have with [Ember](https://github.com/emberjs/ember-test-helpers/blob/master/API.md).

I understand this is not 100% the scope of Vue so It's maybe better to create a Plugin. I will check if I have the time to do this and if it fits with my goals.

**Comment by chrisvfritz** [comment]
I think this would be something best covered in a specific cookbook example @sarah_edo. `dispatchEvent` _is_ good to know about, but at the same time, it's a JavaScript thing rather than a Vue thing. I do think jQuery should probably make note of the misleading behavior of `trigger` in their docs though.
