### ISSUE TITLE
File '@/components/HelloWorld/HelloWorld.vue' is not a module after refactoring the boilerplate when using @

### ISSUE THREAD

**Issue by AyushG3112** [vuejs/vue#7751]
### Version
2.5.13

### Reproduction link
[https://github.com/AyushG3112/vue-refactoring-error-repro](https://github.com/AyushG3112/vue-refactoring-error-repro)

### Steps to reproduce
1. Clone the repository.
2. Run `npm install`
3. Run `npm run serve`

### What is expected?
The dev run should start without errors

### What is actually happening?
File is not a module error

### EDIT 1:

Replacing

`import HelloWorld from '@/components/HelloWorld/HelloWorld.vue';` 
with
`import HelloWorld from '../src/components/HelloWorld/HelloWorld.vue';`

causes the error to go away, but this shouldn't happen as `@` is an alias to `src`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
