### ISSUE TITLE
Using ES6 Proxies instead of Getter/Setters

### ISSUE THREAD

**Issue by geekox86** [vuejs/vue#7757]
### What problem does this feature solve?
ES6 proxies allow for transparent reactivity (without the need for vue.set and vm.$set) and improved performance.

### What does the proposed API look like?
No changes to the existing API, except for deprecating vue.set and vm.$set. All are internal changes.

**Comment by yyx990803** [comment]
This is already planned.

**Comment by sqal** [comment]
https://github.com/vuejs/roadmap#2x-next

**Comment by geekox86** [comment]
Wow, that was a very prompt reply... thank you!

When is the expected release time for this update?
