### ISSUE TITLE
When using [Boolean, String] props, Boolean does not work properly

### ISSUE THREAD

**Issue by alexgrozav** [vuejs/vue#7763]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/165238/](https://jsfiddle.net/50wL7mdz/165238/)

### Steps to reproduce
Create a component property that has `[Boolean, String]` types. The HTML5-like attribute doesn't behave like a normal Boolean value anymore, instead it gets discarded as empty string.

### What is expected?
I would expect both the HTML5 attribute and the v-bind attribute to have the same output.

### What is actually happening?
When adding String as a prop type as well, the HTML5 attribute version is not working.

**Comment by alexgrozav** [comment]
Seems related to https://github.com/vuejs/vue/issues/3879

**Comment by posva** [comment]
Duplicate of #7485
