### ISSUE TITLE
Make the warning messages more explicit

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue#7764]
### What problem does this feature solve?
When seeing warning message like `[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, got String.`, it would be great if Vue could display the actual values it encountered.

For instance, immediately seeing `2` and `'2'` would speed up development.

### What does the proposed API look like?
No API changes

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by posva** [comment]
Of course!

**Comment by ajomadlabs** [comment]
@posuva Since this is first contribution, Can you tell me where to start-off

**Comment by phanan** [comment]
@ajomadlabs I'd suggest searching the string for the file and go from there. In this case `src/core/util/props.js`.

**Comment by ajomadlabs** [comment]
@posva Should I replace the 'value' with the actual value that it encountered ? Correct me if I am wrong

**Comment by AlexandreBonneau** [comment]
@ajomadlabs the goal here is to allow the dev to see which value generated that error.
The `"value"` is the name of the props that failed the test.

I'm guessing the string could be something like:
```js
warn(
      `Invalid prop: type check failed for prop "${name}".` +
      ` Expected ${expectedTypes.map(capitalize).join(', ')}` +
      `, got ${toRawType(value)} with value ${givenValue}.`,
      vm
)
```
...to be defined to be consistent with other Vue messages.

Also, be sure to display the 'type' of the value by adding quotes if it's a string like `'2'`, and no quotes when it's a number like `2`.

**Comment by ajomadlabs** [comment]
@AlexandreBonneau Thanks :+1:

**Comment by dczombera** [comment]
Since nothing has happened for 12 days I was wondering if I could taker over this one as my first contribution? 😊

**Comment by ajomadlabs** [comment]
@dczombera I am working on it but I am getting stuck in the middle

**Comment by AlexandreBonneau** [comment]
Do you need any particular help for getting unstuck @ajomadlabs ?
This feature is highly anticipated around here :)

**Comment by ajomadlabs** [comment]
@AlexandreBonneau I think I have found it

**Comment by AlexandreBonneau** [comment]
:+1:
:shipit:

**Comment by kotAPI** [comment]
Is this issue up for grab? seems like its been a while since any progress has been made.

**Comment by yuriyalekseyev** [comment]
@kotAPI, I created PR #7881 for this issue about 12 days ago and it was not closed yet, so I think we are waiting for further decisions of Vue team.

**Comment by pratheekhegde** [comment]
Folks any update on this PR? Would love to have it merged.
