### ISSUE TITLE
Add or Expose HTML attribute escape function

### ISSUE THREAD

**Issue by networkimprov** [vuejs/vue#7766]
### What problem does this feature solve?
To instantiate Vue components into Markdown or other runtime-generated HTML, the generated HTML provides a $mount point as `<component id="uid"></component>`. The uid must be properly attribute-escaped, and this is not trivial (see link below). If Vue already has an attribute-escape function, it should be exposed in the API, if not please consider adding one.

There are many use cases for Vue components in Markdown; in my case I'm extending markdown to support fillable forms generated from a schema external to the markdown.

### What does the proposed API look like?
Vue.attrEscape(string), returns string

Vue.attrUnescape(string), returns string

Much more on attribute escaping:  
https://stackoverflow.com/questions/7753448/how-do-i-escape-quotes-in-html-attribute-values

**Comment by yyx990803** [comment]
Vue is not a utility library. The utility functions are contained as private parts so that we can change, remove, or refactor them without worrying about breaking users code. In fact, in 2.x we intentionally removed a lot of utility functions that were exposed in 1.x.

It is perfectly fine to use a dedicated library for this purpose.

**Comment by networkimprov** [comment]
I recognize the maintenance benefits, but this philosophy also fosters dependency proliferation and code bloat in apps. If Javascript had a linker, I wouldn't say more, but alas...

Suppose Vue provided an "unstable" API section, wherein function signatures could change across M.x (but not M.N.x) releases? Many utilities, such as attribute-escape, are presumably highly stable.
