### ISSUE TITLE
webassembly ideas

### ISSUE THREAD

**Issue by Jack85** [vuejs/vue#7768]
### What problem does this feature solve?
webassembly integration, compilation, performance

### What does the proposed API look like?
Came across interesting project bringing webassembly .net core and jsworld together into browser
https://www.youtube.com/watch?v=MiLAE6HMr10&feature=youtu.be&t=31m45s

https://github.com/aspnet/Blazor

Just a brainstorm or future future inspiration , if could you imagine if this could work or be integrated with vue workflow logic (making a dll, plugin, fork etc.), components, layouts, vuex communication and so on. Creating some kind of integration package or whatever comes to your mind? Just bringing ideas how incrementally adoptable this could be, if we could use vue goodness there.
Thanks for feedback

```cs
<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button @onclick(IncrementCount)>Click me</button>

@functions {
    int currentCount = 0;

    void IncrementCount()
    {
        currentCount++ ;
    }
}
```

**Comment by posva** [comment]
Technically it could be possible to have an integration layer that does the connection between C# and the JS but it's not something we have planned yet.
I think this is something that the community is probably going to bring more than the team because we cannot just do every language that compiles to web assembly out there 😆 .
Also, web assembly support is still limited

**Comment by Jack85** [comment]
I personaly think, there is huge potential of further performance f.e.: 
https://read.acloud.guru/comparing-aws-lambda-performance-of-node-js-python-java-c-and-go-29c1163c2581
And gaining from it, to have any kind of integration, plus ecosystem advantages, plus adoption on early stages. However I know there might be more ways to come to similar results.

**Comment by yyx990803** [comment]
This is like building a completely new framework (with similar syntax) - definitely not something the core team is interested in / have bandwidth for, but I wouldn't discourage anyone interested to try.

**Comment by Jack85** [comment]
Ok, Thanks.
