### ISSUE TITLE
functional component can't render multiple root nodes if they are functional components too

### ISSUE THREAD

**Issue by senid231** [vuejs/vue#7772]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/senid231/cxuoxdme/24/](https://jsfiddle.net/senid231/cxuoxdme/24/)

### Steps to reproduce
just observe JSFiddle link

### What is expected?
To see `<span>Hi</span>` 32 times (2^^5)

### What is actually happening?
`undefinedundefined`

it renders `undefined` instead of each functional component

**Comment by senid231** [comment]
functional components can render multiple VNodes (according to https://github.com/vuejs/vue/issues/7088#issuecomment-345855657) 
but seems that it can't do that if VNode wrapped with another functional component

**Comment by yyx990803** [comment]
This has been fixed in 8335217cb4bd13fb07e08a76c07df0fceed6c197 (not released yet)

**Comment by ayumu-fujii** [comment]
I was in the process of writing composition as much as programming to send a request for this problem due to inadequate English skills. . .
very very very very great!!!
