### ISSUE TITLE
请问Vue实例中用$和_作为前缀的属性和方法有什么区别？

### ISSUE THREAD

**Issue by ilife5** [vuejs/vue#7775]
### What problem does this feature solve?
我在阅读Vue的源码，发现Vue实例上既有$前缀的方法，如$set，$delete，也有_前缀的方法，如_render。
请问这两种前缀在使用上有什么区别呢？

### What does the proposed API look like?
以上是我的一些疑问，恳请小伙伴们回答解惑。

**Comment by posva** [comment]
Things that start by `_` are internals, private api. Things that start with `$` are things that are public api but they start with a `$` so they don't collide with data, props, methods or computed properties added by the user
