### ISSUE TITLE
Cannot use functional components inside of transition-group

### ISSUE THREAD

**Issue by 1969290646** [vuejs/vue#7777]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/_MT_/qzLptLvs/10/](https://jsfiddle.net/_MT_/qzLptLvs/10/)

### What is expected?
```
[Vue warn]: <transition-group> children must be keyed: <element>
```

### What is actually happening?
渲染失败

**Comment by posva** [comment]
Seems to be a problem related to functional components and transition-group (changed the title)

**Comment by maxirozay** [comment]
The component doesn't get the `key`. You could wrap it like:
```
<transition-group tag="div" name="tag-list">
    <div v-for="index in 5" :key="index">
      <cpt-tag></cpt-tag>
    </div>
  </transition-group>
```

**Comment by 1969290646** [comment]
But why doesn't the function component get the key in the transition-group?

**Comment by maxirozay** [comment]
It seems to be not implemented.

**Comment by sqal** [comment]
You see the warning because you simply did not pass a `key` reference from the `context` object to the main element of the `Tag` component.

https://jsfiddle.net/7hy9sw7r/

**Comment by posva** [comment]
I'm so glad you're here sometimes @sqal 😉

**Comment by 1969290646** [comment]
pretty

**Comment by weotch** [comment]
> But how does a single file component bind context.data?

It's on the `data` object that the template receives: 

```vue
<template functional>
  <div :key='data.key' />
</template>
```
