### ISSUE TITLE
How does a single file component pass context.data?

### ISSUE THREAD

**Issue by 1969290646** [vuejs/vue#7778]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/rjjmpvwm4n/](https://codesandbox.io/s/rjjmpvwm4n/)

### Steps to reproduce
Just look at the codesandbox.

### What is expected?
[issues 7777](https://github.com/vuejs/vue/issues/7777)

### What is actually happening?
Error

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

```vue
<pre :key="data.key">span</pre>
```
Check https://vue-loader.vuejs.org/en/features/functional.html and https://vuejs.org/v2/guide/render-function.html#Functional-Components
