### ISSUE TITLE
Render lists of nested comments

### ISSUE THREAD

**Issue by italomoralesf** [vuejs/vue#7783]
### What problem does this feature solve?
I have a comment json with a field called parent_id, but I do not know how to structure them visually.

[{
"id":1,
"parent_id":0,
"user_id":1,
"comment":"Comment 1",
"since":"2 days ago",
},{
"id":2,
"parent_id":1,
"user_id":1,
"comment":"Comment 2",
"since":"3 days ago",
}]

How to render a nested list (dynamic) in vuejs.

### What does the proposed API look like?
https://github.com/Viima/jquery-comments

**Comment by yyx990803** [comment]
This is not a feature request.

**Comment by italomoralesf** [comment]
It's a request for help that I'm asking

**Comment by yyx990803** [comment]
Please use the forum or the chat room for help. It's been clearly stated that **the issue list is reserved exclusively for bug reports and feature requests**.

**Comment by italomoralesf** [comment]
Thanks
