### ISSUE TITLE
SSR - classes are not re-applied on hydration without a ref

### ISSUE THREAD

**Issue by KaelWD** [vuejs/vue#7787]
### Version
2.5.14

### Reproduction link
No ref: https://codepen.io/anon/pen/yKyBYZ
With ref: https://codepen.io/anon/pen/PRwYPO

### Steps to reproduce
Open the codepen

### What is expected?
`.has-padding` should be applied after 2sec

### What is actually happening?
Nothing changes on hydration unless the element has a ref

---
I opened a similar issue a while ago but for styles - #7063 

Same thing happens with custom attributes btw, I'd expect this to give a "mismatched nodes" error at the very least:

No ref: https://codepen.io/anon/pen/qoExmb?editors=1010
With ref: https://codepen.io/anon/pen/oqgEWL?editors=1010

Text is fine though: https://codepen.io/anon/pen/OvPQQv?editors=1010

**Comment by yyx990803** [comment]
You should do it in `mounted`. Mutating state in `created` will be affecting the output in SSR so it would have no effect.

**Comment by KaelWD** [comment]
Why does it work with a ref then? This is basically the same as #7063 but with a different attribute.

**Comment by johnleider** [comment]
Is there a particular reason that #7063 qualifies as a bug but this does not?

**Comment by iranagame** [comment]
This issue still exist and has no workaround expect adding a ref to every single element which is not very elegant way!
Any ideas!?

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
