### ISSUE TITLE
Radio button not working while using v-for

### ISSUE THREAD

**Issue by algates90** [vuejs/vue#7790]
### Version
2.5.14

### Reproduction link
[https://jsfiddle.net/t0gaf8ha/15/?utm_source=website&utm_medium=embed&utm_campaign=t0gaf8ha](https://jsfiddle.net/t0gaf8ha/15/?utm_source=website&utm_medium=embed&utm_campaign=t0gaf8ha)

### Steps to reproduce
Select first question answer (A1) and move to next question. After choosing the next answer (A4), if you go back to previous question, the chosen radio button is not checked.

### What is expected?
The first answered radio button must be  checked by default

### What is actually happening?
The first answered radio button is not checked

**Comment by Gudradain** [comment]
You need to put a :key="option.id" on your <input type="radio" /> element.

Fixed example: https://jsfiddle.net/t0gaf8ha/19/

**Comment by nviitala** [comment]
Seems weird that the key attribute isn't mentioned anywhere https://vuejs.org/v2/guide/forms.html when the documentation explains the radio buttons.

**Comment by mvocamargo** [comment]
> Seems weird that the key attribute isn't mentioned anywhere https://vuejs.org/v2/guide/forms.html when the documentation explains the radio buttons.

@nviitala actually the key attribute is not required to radio button, but everytime that you are using v-for.
