### ISSUE TITLE
Register the same component twice leads to a subtle bug

### ISSUE THREAD

**Issue by tanin47** [vuejs/vue#7795]
### Version
2.5.15

### Reproduction link
[https://jsfiddle.net/4qvjutqh/2/](https://jsfiddle.net/4qvjutqh/2/)

### Steps to reproduce
In the demo, when we click on the button, we can see that the parent element is being replaced with a new element.

For some reason, the replacement only occurs when the component's attribute is changed the first time. The second time it changes, the replacement doesn't occur.

### What is expected?
We should give out warning when there are redundant component registration.

### What is actually happening?

This leads a subtle bug. Here's what I encountered.

I have `input-text` which is a wrapper of `<input>`. I accidentally registered `input-text` twice into the same HTML tag (once in the main body, and another in the footer).

The subtle bug is that, when I type the first character, the focus is lost. But everything appears normal.

--------------

I wonder if we can print a warning on redundant registering of components in the dev mode. Polymer has this type of warning. It would be super helpful.

(I like Vue.js a lot. Thank you for making such a great framework.)

**Comment by posva** [comment]
It happens because the second component registration is after the first one. Shadowing components is a feature, so printing a warning is unfortunately not possible

**Comment by tanin47** [comment]
Thank you for your response.

This is a reproduction of the subtle bug that I described: https://jsfiddle.net/c6tnzLL7/6/

When typing the first letter, the focus is lost.

**Comment by posva** [comment]
It loses focus because the component gets replaced as soon as the template renders which happens when you type
