### ISSUE TITLE
Cannot read property 'components' of undefined"

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue#7804]
### Version
2.5.15

### Steps to reproduce

> I am importing in App.vue a component named Profile.vue.In Profile.vue also i import another component named ChangePassword.vue.Everything it works and worked fine.

But now i dont want anymore to import ChangaPassword in Profile.vue component.But when i delete the import,delete the component registration and delete the html tag of ChangePassword component i got a strange error.

### What is expected?
Expected this change to do not affect something in application and also to dont get error.

### What is actually happening?
But i got the follow error.

Error in render: "TypeError: Cannot read property 'components' of undefined"

found in

---> <App> at src\App.vue
       <Root>

vue.esm.js?efeb:1717 TypeError: Cannot read property 'components' of undefined
    at checkComponents (vue.esm.js?efeb:1315)
    at mergeOptions (vue.esm.js?efeb:1436)
    at mergeOptions (vue.esm.js?efeb:1452)
    at Function.Vue.extend (vue.esm.js?efeb:4733)
    at createComponent (vue.esm.js?efeb:4135)
    at _createElement (vue.esm.js?efeb:4363)
    at createElement (vue.esm.js?efeb:4300)
    at vm._c (vue.esm.js?efeb:4416)
    at Proxy.render (eval at ./node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-04c2046b","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue (app.js:1923), <anonymous>:50:27)
    at VueComponent.Vue._render (vue.esm.js?efeb:4474)

---
I think that i miss something but since i delete the import in Profile.vue and delete the components: {} section and also the html tag related to ChangePassword.vue everything should work fine.Idk why it isnt

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Rolanddoda** [comment]
But i think it is a bug

**Comment by posva** [comment]
For bugs you need to provide a minimal repro

**Comment by Rolanddoda** [comment]
But this bug occurs only in that situation.I cant do a repro.It is strange error.Anyway i am going to ask in the forum.

**Comment by Rolanddoda** [comment]
I solved it!If for someone gets the same error even if the code is right then make sure to have named your components.I named all my components and now i dont get this error again.

**Comment by fritx** [comment]
I met the same issue today, and after a long-time debugging, finally found the bug is from insistent filename (caseless) on git, which caused we mixin'd an `undefined` into a vue component.

https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Comment by bestickley** [comment]
I encountered this error and what solved it was changing a line in my components from:
```import getList from "../mixins.js"``` to ```import { getList } from "../mixins.js"```

**Comment by majorcool** [comment]
Another possible cause, your component depends on an non-existent mixin.

**Comment by jasonhartline** [comment]
I had the same error.  It was from writing the incorrect:

`import MixinName from './mixinfile'
`
Instead of the correct:

`import { MixinName } from './mixinfile'
`
The comment above about 'non-existent mixin' from @majorcool was a good tip for finding this error.

**Comment by u2ros** [comment]
I also stumbled upon this and it is almost always a result of some sloppiness on our part. In my case i copy paste a mixin, and made a named export, which when imported under a different name, of course didn't exist. It is maybe a shame some undefined import alert doesn't pop up

**Comment by hybridwebdev** [comment]
> I had the same error. It was from writing the incorrect:
> 
> `import MixinName from './mixinfile' `
> Instead of the correct:
> 
> `import { MixinName } from './mixinfile' `
> The comment above about 'non-existent mixin' from @majorcool was a good tip for finding this error.

Ran into this issue myself, and yup incorrect syntax when importing a mixin resulted in this issue. 

Objectively, the error message displayed should be less ambiguous as it's really hard to decipher what it's referring to.

**Comment by pascaldls** [comment]
I had the same error. for 3hrs try mostly everything 

Quick fix is to use require instead of import then it works fine .

**Comment by herivgs** [comment]
I was having this error over Laravel 5.4 and vue 2.5

I just solved changin the Mixin import line:
From: 
`import { MainMixin } from "./mixins/MainMixin";` 
To:
` import MainMixin from "./mixins/MainMixin";`

**Comment by hongquangraem** [comment]
I have the same isusse when mixing. My probem is naming the variable is *minxin*, so for the people later, do not name variable with special name

**Comment by marcelobbfonseca** [comment]
I had this issue by trying to import another js module to a mixin

**Comment by Taifunov** [comment]
I had same issue and the solving it's just in some of your components you didin't have decorator above export default class:
@Component({
  components : { }
})

you need just add empty decorator and issue will gone ;)

**Comment by okbuddy** [comment]
> I had this issue by trying to import another js module to a mixin

same error , my bug is because of a error of circular dependency like this [https://github.com/babel/babel/issues/4094#issuecomment-245410649](url)
for example:
1. A.vue import the mixins. 
2. mixins import the B.vue ( mixins export no mixin yet )
3. B.vue import { mixinA }  from '../mixins' ( **mixins still at the import step** , export no mixin yet )
so the mixinA is undefined in the B.vue
add the break point at the  **import { mixinA }  from '../mixins'**  will find the circular dependency. 
Solving the circular dependency will solve the error

**Comment by xgqfrms** [comment]
# solutions

> ESM export & import usage error

```js

// monitor mixins
// export modules & default export ❌
// import {
//     monitorAdsMixin,
//     autoGetModuleName,
// } from '@/mixins/monitor/tools-mixin.js';

// no default export ✅
import * as monitorMixin from '@/mixins/monitor/tools-mixin.js';

const {
    monitorAdsMixin,
    autoGetModuleName,
} = monitorMixin;

// default export ✅
// import monitorAdsMixin from '@/mixins/monitor/tools-mixin.js';

export default {
    // name: '',
    mixins: [monitorAdsMixin],
   //...
}


```

**Comment by fwiwDev** [comment]
From my experience, this can occur when you import the same mixin more than once from a parent component and a child component.

**Comment by ddulkevich-entrypoint** [comment]
I solve same problem just changing my code:
from
```
import component1 from '@/components/common/component1';
import component2 from '@/components/common/component2';
import component3 from '@/components/common/component3';

export default {
    components: {
        'component-1': component1,
        'component-2': component2,
        'component-3': component3
    }
}
```
to
```
export default {
    components: {
        'component-1': () => import('@/components/common/component1'),
        'component-2': () => import('@/components/common/component2'),
        'component-3': () => import('@/components/common/component3'),
    }
}
```

**Comment by ZadaWu** [comment]
> I met the same issue today, and after a long-time debugging, finally found the bug is from insistent filename (caseless) on git, which caused we mixin'd an `undefined` into a vue component.
> 
> https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

It happens several times. I tried to reboot/named my components/ Restart my mac...... I make no changes but It's bad in the afternoon when It's ok in the morning. It makes me crazy.
Thanks so much!  I see the link and run the command `git config core.ignorecase false`.
Then I delete all the dist folders, The last  step is to reboot the command `npm run dev`
