### ISSUE TITLE
v-for evaluated even if v-if statement is false

### ISSUE THREAD

**Issue by Morgitou** [vuejs/vue#7807]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/180948/](https://jsfiddle.net/50wL7mdz/180948/)

### Steps to reproduce
1) Make a variable in data (e.g. project), that is null (or undefined) because you will get it from your server later on.
2) Make a div with v-if="project" v-for="item in project.list"
3) Get your error even if v-if is evaluated to false...

### What is expected?
Nothing to append

### What is actually happening?
Error: Vue is trying to evaluate an empty variable

---
This is quite annoying, I have in this case to add an extra div to wrap the v-for statement. It should not evaluate the v-for if a v-if statement is false in the same html tag.
By the way, in this exemple, my project data is being  assigned later, after a request to the server.

**Comment by qkdreyer** [comment]
https://vuejs.org/v2/guide/list.html#v-for-with-v-if

**Comment by sqal** [comment]
```vue
<template v-if="project">
  <div v-for="(item, index) in project.list" v-bind:key="index">
    {{ item }}
  </div>
</template>
```

**Comment by posva** [comment]
Whan @qkdreyer said
