### ISSUE TITLE
Euler's number breaks v-model for numeric inputs

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vue#7808]
### Version
2.5.15

### Reproduction link
[https://jsfiddle.net/andreasvirkus/csxy3vsd/1/](https://jsfiddle.net/andreasvirkus/csxy3vsd/1/)

### Steps to reproduce
Set up a native input element with type set as number. Type in "e" wherever in your numeric value.

### What is expected?
The emitted value should include Euler's number (e.g. "10e2", "4e 0", etc.)

### What is actually happening?
The mapped v-model value becomes undefined

**Comment by posva** [comment]
This is working as expected, `10e3` in js becomes `10000` and `4e 0` isn't a valid number
