### ISSUE TITLE
beforeload placeholder for async component

### ISSUE THREAD

**Issue by yaodingyd** [vuejs/vue#7810]
### What problem does this feature solve?
My use case is that parent component needs to properly calculate the number of $children to render after parent is mounted, and some of the $children can be async component, so I need a beforeload component option.

### What does the proposed API look like?
```javascript
const AsyncComp = () => ({
  // The component to load. Should be a Promise
  component: import('./MyComp.vue'),
  // A component to use while the async component is loading
  loading: LoadingComp,
  // A component to use before loads
  beforeLoading: placeholder
  // A component to use if the load fails
  error: ErrorComp,
  // Delay before showing the loading component. Default: 200ms.
  delay: 200,
  // The error component will be displayed if a timeout is
  // provided and exceeded. Default: Infinity.
  timeout: 3000
})
```

**Comment by yyx990803** [comment]
I don't understand what you are asking for. Do you want some way to display a placeholder component until all nested async components are loaded?

**Comment by yaodingyd** [comment]
Yes! Sorry if my wording is confusing.

**Comment by yyx990803** [comment]
Unfortunately this is not something that can be easily done in Vue at the moment.

This is somewhat doable in userland if you know what components may be loaded down the tree, but can be tricky to get right. My suggestion is avoid over-splitting since nested async components will result in waterfall requests.
