### ISSUE TITLE
Performance Question:  v-html vs {{braces}}

### ISSUE THREAD

**Issue by ggedde** [vuejs/vue#7816]
I understand the difference they provide as far as escaping tags and data binding, but I don't know what the Vue Team sees as the preferred method and what performance differences they have.

For example, what is less work for the vue engine:
`<div>{{content_a}}</div>`
Or 
`<div v-html="content_a"></div>`

Especially at a large scale or used on repeaters, etc
I am more curious about this since both methods provide the same outcome.
I also prefer to not use braces unless absolutely necessary, but I don't want to hinder the performance by over-using v-html if it takes up more power then {{braces}}

Thanks

**Comment by leopiccionia** [comment]
* `v-html`: replaces element's whole `innerHTML`.
* `v-text`: replace element's whole `textContent`.
* `{{braces}}`: interpolates `textContent`. Useful when you want to mix it with literals.

**Comment by ggedde** [comment]
@leopiccionia 
Thanks for the additional info.
Still curious about performance.  Like which ones use less resources, etc
Are you suggesting that {{braces}} may use more resources as they will need to interpret mixed literals?
