### ISSUE TITLE
Provide a way to explicitly fill a (scoped) slot with nothing

### ISSUE THREAD

**Issue by Justineo** [vuejs/vue#7829]
### What problem does this feature solve?
See #7064 for some background information.

After providing an explicit way to declare that a slot is “empty”, we won't have to use props to control whether each slot is gonna be rendered or not.

### What does the proposed API look like?
```html
<v-component>
  <template slot="extra" empty></template>
</v-component>
```
or
```html
<v-component>
  <template slot="extra"><empty-slot/></template>
</v-component>
```

**Comment by posva** [comment]
what about creating a custom component in userland for this use case:

```js
const EmptySlot = {
  functional: true,
  render: (h, { props: slot }) => h('template', { slot }, '\u{200b}')
}
```

**Comment by Justineo** [comment]
@posva The problem here is that although the zero-width space is supposed to be “invisible”, it does produce an extra line box, which acts like a `margin-top` for following elements. It's slightly different with “nothing”.

The actual use case is that while creating a “layout” component, it's possible that different parts are optional, eg. I may have a `<v-alert>` component like this:

```vue
<template>
<div class="alert">
  <slot name="title"><header><slot name="title-content">Alert</slot></header></slot>
  <div class="content"><slot></slot></div>
</div>
</template>

<style scoped>
.content {
  border-top: 1px solid #ccc;
}

.content:first-child {
  border-top: none; /* only when slot "title" is empty */
}
</style>
```

And use it like this:

```html
<!-- default title -->
<v-alert>Something went wrong!</v-alert>

<!-- custom title -->
<v-alert>
  <slot name="title-content">Oops</slot>
  Something went wrong!
</v-alert>

<!-- no title -->
<v-alert>
  <slot name="title"><empty-slot/></slot>
  Something went wrong!
</v-alert>
```

Although I can use a prop to control the rendering of each optional slot (and it may be easier to type), providing a special syntax or component automatically makes all slots clearable. Otherwise component authors may provide different ways to handle this scenario:

```html
<v-alert show-title>...</v-alert>
<v-alert :slots="['default']">...</v-alert>
<v-alert :hide-slots="['title']">...</v-alert>
```

**Comment by posva** [comment]
The last comment is interesting. I tried out with an empty string and it seems to work as well (updated the comment above)

**Comment by Justineo** [comment]
@posva It actually inserts an HTML `<template>` element and makes selectors like `:first-child` doesn't work as expected.

**Comment by posva** [comment]
Damn, I only tested on Chrome 🙁

**Comment by Justineo** [comment]
I'm afraid it doesn't work even in Chrome...

In this case

![image](https://user-images.githubusercontent.com/1726061/37418177-93b4ae38-27ec-11e8-92c7-f345c4413da7.png)

The `<p>` element doesn't match `:first-child`.

**Comment by sirlancelot** [comment]
I'm kind of on the fence on whether Vue should allow clearing of a slot fallback in core. It seems a little hacky to me.

It's possible to get exactly what you want in Userland though, I created a sample here: https://codepen.io/sirlancelot/pen/oqxzMq?editors=1010

It borrows from @posva in that it uses a functional component. I added a directive which removes the generated node from the DOM so that CSS can match appropriately.

```javascript
Vue.component("my-empty", {
	functional: true,
	render: (h) => h("i", { directives: [
		{ name: "remove-node" }
	] })
})

Vue.directive("remove-node", {
	inserted: (el) => el.parentNode.removeChild(el)
})
```

**Comment by Justineo** [comment]
> Turns out if you don't use a functional component, then it just works!

Confirmed.

But now this feels like a real hack to me...A functional component that renders nothing behaves differently with a normal one, which may be unwanted consistency for Vue to handle slot contents.

Before `v2.5.3`, Vue did clear a slot if you just provide nothing for a slot, which was later considered as a bug and fixed. I cannot guarantee that in future versions it wouldn't happen to the hack above.

**Comment by Justineo** [comment]
@sirlancelot I've issued a bug report (#7841) for the current behavior (which I don't think is expected).

**Comment by plehnen** [comment]
> Before v2.5.3, Vue did clear a slot if you just provide nothing for a slot, which was later considered as a bug and fixed.

But that was a logical behaviour. I explicitly provide an empty slot, therefore I want to clear the default slot. This is the easiest and most logical solution. I don't get why this can't be the way to do it?
But anyhow, an explicit (and a little verbose) "empty"-keyword would be fine too, but at least provide a way to do it (please!).

**Comment by Justineo** [comment]
As #7841 is closed as a wontfix (https://github.com/vuejs/vue/issues/7841#issuecomment-401057800), we can rely on the current behavior so that this feature request can be stably worked aroud in userland (though still feels hacky to me). We can close this if we are not gonna implement this in core. @yyx990803
