### ISSUE TITLE
Hiding component with v-if results in NotFoundError: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue#7831]
### Version
2.5.15

### Reproduction link
[https://jsfiddle.net/Lwuxeqyc/](https://jsfiddle.net/Lwuxeqyc/)

### Steps to reproduce
Click "Hide Both" in the JSFiddle.

### What is expected?
The components actually hide. Or at least give a meaningful warning instead of erroring out.

### What is actually happening?
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by posva** [comment]
You shouldn't manually move the dom that is controlled by Vue.
I think you are looking for a portal implementation: https://github.com/LinusBorg/portal-vue 🙂

**Comment by nerdcave** [comment]
@posva Understood, but can't Vue give a warning/suggestion instead of breaking?

**Comment by posva** [comment]
It's not something users are supposed to do at all and it may be hard for Vue to detect such things but PRs for that kind of things are usually accepted if they do not impact other users (performance, undesired warnings). In this specific scenario it may be very difficult to find the right spot, so I don't think it is worth adding but I can be prooved wrong
