### ISSUE TITLE
Docs for propsData incomplete 

### ISSUE THREAD

**Issue by networkimprov** [vuejs/vue#7832]
### What problem does this feature solve?
The documentation for propsData omits:

1. the fact that props set via `propsData: { p: object_or_array[n] }` do not update when n's value changes.
2. any description of ways to simulate reactivity for props of programmatically instantiated components.

### What does the proposed API look like?
NA

**Comment by posva** [comment]
This is normal as long as the value is not an object.
I agree that a notice on the docs would be helpful but please directly open a PR in the docs repo 🙂

**Comment by networkimprov** [comment]
Will this trigger `watch: { p: { deep: true, handler: function(o) {...} } }`

for `propsData: { p: {k:0} }` 

If so you should certainly document that the object/array case works!
