### ISSUE TITLE
所有Vue的created方法执行某段代码，vue中要怎么做？（类似AOP编程）

### ISSUE THREAD

**Issue by snice** [vuejs/vue#7833]
### What problem does this feature solve?
1、提供AOP编程
2、可以提供类似面向对象的Base类。（我现在使用中需要所有Vue在指定生命周期钩子注册和反注册某个功能代码）

### What does the proposed API look like?
Vue.aop()
Vue.aopLifecycle()

**Comment by JounQin** [comment]
………… Please read document first. It is very simple.
https://vuejs.org/v2/guide/mixins.html

**Comment by olivewind** [comment]
https://cn.vuejs.org/v2/api/#Vue-mixin

**Comment by liuhongyi0101** [comment]
mixin

**Comment by snice** [comment]
Thanks
