### ISSUE TITLE
Transition mode="out-in" has one tick delay after out before in

### ISSUE THREAD

**Issue by pawelpanek81** [vuejs/vue#7838]
### Version
2.5.15

### Reproduction link
[https://vuejs.org/v2/guide/transitions.html](https://vuejs.org/v2/guide/transitions.html)

### Steps to reproduce
1. Find "Now let’s update the transition for our on/off buttons with out-in:" on the website.
2. Click the button "off", "on" below the code.
3. There is one tick while the text "With one attribute addition, we’ve fixed that original transition without having to add any special styling." jump up and immediately jumb down. Bug appears on browser: Firefox 59.0. On chrome works as expected.

### What is expected?
No one tick jump text under the button.

### What is actually happening?
The text jumps up and down on Firefox 59.0.

---
I realize that this may be a browser bug, but I'm not sure.

**Comment by posva** [comment]
Tested on Firefox Nightly and seems to be gone.
Here's a GIF from Firefox 59 that reflects what the OP is saying (it doesn't appear always)

![screenflow](https://user-images.githubusercontent.com/664177/37511344-c2c17e78-28fe-11e8-9874-df42b663f160.gif)
