### ISSUE TITLE
Add enum sugar for prop validators

### ISSUE THREAD

**Issue by Justineo** [vuejs/vue#7840]
### What problem does this feature solve?
For enum props, it's common to validate the given value against valid enum values like this:

```js
props: {
  position: {
    type: String,
    validator (val) {
      return ['top', 'right', 'bottom', 'left'].includes(val)
    }
  }
}
```

### What does the proposed API look like?
I think it'll be handy to provide extra convenience by supporting this:

```js
props: {
  position: {
    type: String,
    validator: ['top', 'right', 'bottom', 'left']
  }
}
```

**Comment by sirlancelot** [comment]
if you want a shorthand, just use an arrow function:

```javascript
props: {
  position: {
    type: String,
    validator: (val) => ['top', 'right', 'bottom', 'left'].includes(val)
  }
}
```

Less magic. It's Just JavaScript.

**Comment by posva** [comment]
I also think this is not necessary. As a note, prop validation is stripped off in production builds, so why not. Beware objects enum though

**Comment by Justineo** [comment]
> Less magic. It's Just JavaScript.

If you want “less magic”, maybe quite a few of Vue's current shorthand syntax would be “unnecessary”. Even in this case, `type` is a shorthand for a type checking `validator`. IMO this depends on whether folks think use array for a validator is clear enough that it's checking enum values.

BTW. `Array.prototype.includes` needs to be polyfilled or we have to write `[...].indexOf(val) !== -1`. Although this doesn't cost very much, it bothers quite a few developers to repeat this every single time.

> Beware objects enum though

In most cases enum values are primitive. We can just ignore object/array values or warn about this.

**Comment by yyx990803** [comment]
The implied behavior can indeed be ambiguous regarding how objects/arrays should be handled. I actually think it's better to be more explicit here...

**Comment by backbone87** [comment]
Why not just:
```js
props: {
  position: {
    type: [Number, 'top', 'right', 'bottom', 'left']
  }
}
```

This also feels a little bit like typescript :)

**Comment by dkushner** [comment]
@backbone87, that seems confusing and conflicts directly with the existing Vue interpretation of the `type` field.

**Comment by sirlancelot** [comment]
I just don't think this is a common enough problem to merit a solution in the core. You can easily create your own helper to do this for you:

```
const onlyValues = (values) => (str) => values.indexOf(str) !== -1

const props = {
    position: {
        type: String,
        validator: onlyValues(["top", "left", "bottom", "right"])
    }
}
```

Also, validators don't run in Production anyway, so this is just a development helper.

**Comment by backbone87** [comment]
@dkushner how does it conflict? the `type` field currently does not allow primitives, only constructors.

**Comment by verymuch** [comment]
How about this?

```
props: {
  position: {
    type: String,
    in: ['top', 'right', 'bottom', 'left']
  }
}
```

not conflict with `type` field, just add a `in` field

**Comment by owenallenaz** [comment]
If the goal is `enum`, maybe we should be explicit about it?

```
props: {
  position: {
    type: String,
    enum: ['top', 'right', 'bottom', 'left']
  }
}
```

It would only checks exact matches against the passed array. In example from graphQL https://graphql.org/learn/schema/#enumeration-types . From the docs it states two of the benefits.

* Validate that any arguments of this type are one of the allowed values
* Communicate through the type system that a field will always be one of a finite set of values

I think in this case, both apply to Vue, no?

**Comment by brunovcosta** [comment]
What about this?

```
props: {
  position: {
    type: String,
    validator: ['top', 'right', 'bottom', 'left'].includes
  }
}
```
