### ISSUE TITLE
`v-for` directive with integer range does not work with constant attribute but only works with binding

### ISSUE THREAD

**Issue by stephenmartindale** [vuejs/vue#7844]
I was confused by some strange behaviour related to the `v-for` directive (Vue 2.5) with integer ranges and I ended up posting [this stackoverflow question](https://stackoverflow.com/questions/49316942/vue-v-for-directive-with-integer-range-bound-to-component-property) about it. The question was promptly answered and I now understand my mistake but I think that this behaviour is either a bug or a failure in the documentation and so I am opening this issue anyway.

## Brief Summary

Here is a component:

```
let CounterComponent = Vue.extend({
    template: `
        <div>
            <h3>The counter is {{value}}</h3>
            <svg v-for="n in value" :key="n"
                 xmlns="http://www.w3.org/2000/svg" version="1.1"
                 xmlns:xlink="http://www.w3.org/1999/xlink"
                 viewBox="0 0 10 10">
                <circle cx="5" cy="5" r="5"></circle>
            </svg>
        </div>
    `,
    props: {
        value: Number
    }
})
```

Note the use of the `v-for` directive with an integer range bound to the `value` property.

If you use a `v-for` as in this [jsfiddle](https://jsfiddle.net/StephenM/vvj23rae/19/), it doesn't work at all:

    <counter-component value="14" />

However, the following both work: [jsfiddle](https://jsfiddle.net/StephenM/vvj23rae/39/), [jsfiddle](https://jsfiddle.net/StephenM/vvj23rae/33/)

    <counter-component v-bind:value="15" />
    <counter-component :value="16" />

## Source of Great Confusion™

I was fooled by the fact that the *interpolation* in the `h3` tag works in all three cases but the `v-for` directive only works in the latter two. I wasted hours trying various variants of the syntax because, while I will certainly use a binding in a live application, I was trying out the integer-range support in the `v-for` directive for the first time and had plonked multiple instances of the component I was building onto a page with different values of the `value` property, all set as constants.

## Suggested Resolution

I propose that either `v-for` is changed so that it works in all three cases *or* that the documentation (https://vuejs.org/v2/guide/list.html#v-for-with-a-Range) is updated to reflect this requirement that, if a component property is used as the range parameter, that property cannot be set to a literal and must be bound.

I am not sure how to phrase the latter but I guess that simply updating the docs would be the responsible course of action.

**Comment by yyx990803** [comment]
A literal prop is passed down as a string, not a number.

**Comment by stephenmartindale** [comment]
@yyx990803 Thank you for that information. It's very helpful and I understand the issue, now: with the literal prop, the string is passed as is, with the v-bind prop, it is somehow coerced. I still think that the documentation should make mention of this, however, because this is the obvious mistake to make and trying to use a prop for the range parameter is the immediately obvious thing to do with `v-for`.

I am not a technical editor but I'd add a paragraph saying something along these lines: "Note that the range-parameter of `v-for` may be a property of a component but that this property must be an integer." followed by an example of the mistake and an example of the working solution with `:` or `v-bind:`

Also, I didn't get a warning when I did this. Not in the jsfiddle, using the minified file, or in my real dev. environment which is using the full ESM and even shows other warnings, like the development-mode warning. Because I never saw a warning, my chances of discovering the cause and solution were basically nil.

**Comment by yyx990803** [comment]
It's not "coerced" - when you use a binding, whatever is between the quotes is evaluated as JavaScript. The difference is like 1 vs. "1" in JavaScript.

**Comment by yyx990803** [comment]
You did not get a warning because it is technically possible to iterate over a string with v-for as well.
