### ISSUE TITLE
`v-for` directive with integer range does not work with constant attribute but only works with binding

### ISSUE THREAD

**Issue by stephenmartindale** [vuejs/vue#7845]
### Version
2.5.15

### Reproduction link
[https://jsfiddle.net/StephenM/vvj23rae/19/](https://jsfiddle.net/StephenM/vvj23rae/19/)

### Steps to reproduce
Observe that the interpolation in the `h3` tag is working but that the `v-for="n in value"` is not working. Then open https://jsfiddle.net/StephenM/vvj23rae/39/ and https://jsfiddle.net/StephenM/vvj23rae/33/ and observe that that same `v-for` works just fine. The interpolation works in all three cases.

### What is expected?
I would expect that all three of these uses of the component work:

    <counter-component value="14" />
    <counter-component v-bind:value="15" />
    <counter-component :value="16" />

Or that the documentation (https://vuejs.org/v2/guide/list.html#v-for-with-a-Range) reflects the fact that only the latter two will work. That if a component property is used as the range parameter for `v-for`, that property cannot be set to a literal and must be bound.

### What is actually happening?
`v-for` only works with an integer range defined by a component property if that component has that property bound. However, interpolations work with component properties even if that property is set to a literal constant where the component is used.

---
I was fooled by the fact that the interpolation in the h3 tag works in all three cases but the v-for directive only works in the latter two. I wasted hours trying various variants of the syntax because, while I will certainly use a binding in a live application, I was trying out the integer-range support in the v-for directive for the first time and had plonked multiple instances of the component I was building onto a page with different values of the value property, all set as constants.

I ended up posting [this stackoverflow question](https://stackoverflow.com/questions/49316942/vue-v-for-directive-with-integer-range-bound-to-component-property) about it. The question was promptly answered and I now understand my mistake but I think that this behaviour is either a bug or a failure in the documentation and so I am opening this issue anyway.

**Comment by posva** [comment]
You're passing a string instead of a number, do `<counter-component :value="14" />`. There's usually a warning but you are using the minified version
