### ISSUE TITLE
Short syntax for v-bind attributes with the same names

### ISSUE THREAD

**Issue by davletovalmir** [vuejs/vue#7848]
### What problem does this feature solve?
Reduce amount of code and make code neater.

### What does the proposed API look like?
It looks like ES6 [destructuring assignment](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment): `... :foo ...` instead of `... :foo='foo' ...`.

Right now it doesn't work, since according with standards, such attributes are considered as [Boolean Attributes](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) and converted from  `... :foo ...` to `:foo=":foo"`. And I'm not even sure if it's not a bad practice to use them in proposed way (since if such attributes are called **Boolean Attributes**, they should represent boolean values). But having that feature would be really great!

**Comment by sqal** [comment]
This idea been proposed before

https://github.com/vuejs/vue/pull/2877
