### ISSUE TITLE
render state while on leave transition

### ISSUE THREAD

**Issue by ap-o** [vuejs/vue#7849]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/heyapo/bzor84a1/84/](http://jsfiddle.net/heyapo/bzor84a1/84/)

### Steps to reproduce
Click to toggle button, to show the label. Wait for a second or two. Then click again to hide the label.

Then click again to hide the label. 

Label is hiding succesfully, leave callbacks are indeed triggered, but the template won't respond.

### What is expected?
Label's text should update according to transition's status. On entere it should go from entering to entered. On leave it should change from entering ? will leave > leaving > exited (hidden)

### What is actually happening?
Transition callbacks are indeed triggered, but it won't render the changes.

**Comment by posva** [comment]
When the leaving callbacks trigger it is too late to change the template, it won't render anymore. If you need to display something different you need to delay the toggling one tick. You can do this by wrapping the transition in your component or by manually delaying the hiding: http://jsfiddle.net/jh93kqfp/. A hacky version would be to modify the element manually
The component is actually destroyed before the leaving transition happens
