### ISSUE TITLE
关于keep-alive的时候，两个父组件引用同类子组件导致emit事件被第二个父组件接收的情况

### ISSUE THREAD

**Issue by alicksnake22** [vuejs/vue#7850]
### Version
2.5.16

### Reproduction link
none

### Steps to reproduce
keepyalive router-view切换A和B，并且两者都引用了header子组件，通过@xxx绑定父子emit事件，A点击header按钮能正确触发A里面的事件，A跳到B，B点击header的按钮能正确触发B的事件，B返回A，然后A点击header上面的按钮

### What is expected?
理论上header的emit触发A的事件

### What is actually happening?
但是目前却是触发了B的事件，请问怎么做才能正确触发A？是我忽略了什么属性吗？

---
同时，如果不使用keepalive是正常的，因为A和B都重新加载了

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue and provide a repro when reporting a bug
Thanks!

**Comment by sjush** [comment]
我也遇到了这个问题，请问有合理的解释吗
