### ISSUE TITLE
<transiton-group> effect in dev-server (built with command 'npm start') looks different from production on my own server (built with command 'npm run build')

### ISSUE THREAD

**Issue by LC-Lin** [vuejs/vue#7851]
### Version
2.5.16

### Steps to reproduce
.content-list-item {
  transition: all 1s;
}

.content-list-move {
  transition: transform 1s;
}

.content-list-enter,
.content-list-leave-to {
  opacity: 0;
  transform: translateX(-100px);
}

.content-list-leave-active {
  position: absolute;
}

### What is expected?
The effect in dev-server is expected

### What is actually happening?
The effect in production mode is unexpected

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
