### ISSUE TITLE
component inline template v-for variable undefined one

### ISSUE THREAD

**Issue by lansi951** [vuejs/vue#7852]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/u3vy25gd/](https://jsfiddle.net/u3vy25gd/)

### Steps to reproduce
1. make component.
2. make inline-template
3. v-for component

### What is expected?
last component created print prop is undefined.

### What is actually happening?
`Property or method "v" is not defined on the instance but referenced during render.` error excepted.
but, use template: `<div>{{ v }}</div>` or `<script type="text/x-template" id="test-template">` is work well.

**Comment by posva** [comment]
You need to put the template outside of the #app template

```vue
<div id="app">
  <test v-for="(v, k) in test" :v="v" :key="k"></test>
  
</div>

<script text="text/x-template" id="test-template">
    <div>{{ v }}</div>
  </script>
```
