### ISSUE TITLE
Different vision for global variables in development and minified version.

### ISSUE THREAD

**Issue by Azperin** [vuejs/vue#7853]
### Version
2.5.16

### Reproduction link
[https://codepen.io/anon/pen/PRGvZy](https://codepen.io/anon/pen/PRGvZy)

### Steps to reproduce
Just change from vue.min.js to vue.js

### What is expected?
Showing global variable

### What is actually happening?
Error that variable is not defining

---
easy to reproduce test, so nothing additional

**Comment by posva** [comment]
You cannot rely on `bus` if it's not defined on the Vue instance. You need to add it to the root instance or to the prototype of Vue to have access to it everywhere:

```js
Vue.prototype.bus = bus.$data
```
