### ISSUE TITLE
Content Security Policy from Helmet prevent loading js

### ISSUE THREAD

**Issue by WangHansen** [vuejs/vue#7854]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/y0jmvrkpmz](https://codesandbox.io/s/y0jmvrkpmz)

### Steps to reproduce
I can't get it to build in the sandbox, but I will describe what happens:

I build the files and serve it with Expressjs static file serve function.
And in server.js, I use helmet to try to apply the content security policy.

The code looks like this:
```javascript
app.use(helmet.contentSecurityPolicy({
  directives: {
    scriptSrc: ["'self'", 'https://use.fontawesome.com'],
    fontSrc: ["'self'", 'https://use.fontawesome.com', 'data:'],
    connectSrc: ["'self'"],
    imgSrc: ["'self'", 'data:']
  }
}))
```
but it didn't work, no error messages in console, jus that the scripts are not loaded.
Then I tried this:
```javascript
app.use(helmet.contentSecurityPolicy({
  directives: {
    defaultSrc: ['*']
  }
}))
```
But it still doesn't work, the scripts such as 0.js, 1.js are not loaded.
And the web page is just blank

### What is expected?
The page to display proper information

### What is actually happening?
The page is blank

**Comment by posva** [comment]
Unfortunately, this is not related to Vue. You should be able to find an answer on Stackoverflow. You can also seek for help in the forums 🙂
