### ISSUE TITLE
v-show="true" possibly incorrect during SSR

### ISSUE THREAD

**Issue by brophdawg11** [vuejs/vue#7858]
### Version
2.5.16

### Reproduction link
[Gist](https://gist.github.com/brophdawg11/560ce5478ddebbb3a7f1aacc30fbbbc1)

### Steps to reproduce
* Download the above gist to an `index.js` file
* `npm install --save vue vue-server-renderer`
* `node index.js`

### What is expected?
I would expect an element rendered server side with `v-show="true"` to render in the same fashion as one without a `v-show` directive.   

### What is actually happening?
Elements with `v-show="true"` are rendered during SSR with a seemingly invalid style attribute: `style="display:;`, while those without any `v-show` directive do not contain a `style` attribute at all

---
I don't know that this causes any specific rendering issues at the moment, but I noticed it because chrome dev tools was complaining about the styles on my element.

**Comment by blake-newman** [comment]
I don't think this causes any issues during render, but you are correct it shouldn't be rendering as you mentioned. Add improvement label, as it is something that can be fixed but not a destructive bug

**Comment by curryz** [comment]
so do I, when I user SSR ,v-show cause the style can't be displayed
