### ISSUE TITLE
XSS when using HTML entities

### ISSUE THREAD

**Issue by rodrigopedra** [vuejs/vue#7860]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/s9783tq3/](https://jsfiddle.net/s9783tq3/)

### Steps to reproduce
Vue parses an expression even when enclosed by curly-braces using HTML entitties, example:

<div id="app">
  &amp;#123; &amp;#123; constructor.constructor(&amp;quot;alert(1)&amp;quot;)()  &amp;#125; &amp;#125;
</div>

### What is expected?
The expression rendered with HTML entities not to be parsed

### What is actually happening?
Vue is parsing it instead

---
After reading about XSS in vue, I wrote a helper in my PHP template engine to replace curly-braces in unsafe expressions by their HTML entity equivalent. I expected Vue to render only expressions written with actual curly-braces. Unfortunately it is not feasible to add the v-pre directive in every place where the project I am working on renders unsafe user input.

**Comment by yyx990803** [comment]
Vue security rule No.1: never ever feed untrusted content as template to be compiled by Vue, period. There's nothing Vue can do to save your from XSS if you do that.

**Comment by rodrigopedra** [comment]
@yyx990803 I understand your concern. But is Vue supposed to parse a template even using HTML entities as in the example? 

I would never feed a Vue component directly with such input, but in a server rendered page it is common to have server-rendered content that unfortunately goes inside the App root. Aside from using the `v-pre` directive how one is supposed to properly escape user input from server-rendered pages? Should I tailor every specific page to restrict Vue app root to only a strict safe context?

**Comment by rodrigopedra** [comment]
@yyx990803 believe me, I am not ranting, I am trying to solve a problem I believe many devs are worried based on what I was reading. Sorry for my poor English.

It is very common to have the Vue app root in a top level element and render generic server side content inside of it that should not interact with the vue app. Imagine a User profile where a malicious user changed his name to some CSS string.

So I had another idea: Is there a way to completely disable braces interpolation while allowing the usage of directives (`v-text` and `v-html`)? 

I know I can change delimiters for a Vue app to something esoteric, but if there is the option to completely disable braces interpolation and only allow render through directives I suppose the app would run faster and my problems would be solved.

I write most of my components using `v-text` and `v-html` so it wouldn't be difficult to migrate any braces usage.

Thanks in advance, and sorry again if I sounded rude in anyway.

**Comment by Akryum** [comment]
The problem is you are essentially telling Vue to compile a template which **has** user-generated content in the source. It's exactly like if the user had put content in a `.vue` file template part.

Add `console.log(document.querySelector('#app').innerHTML)` to see what the Vue compiler sees for your template.

To solve this, you could either put the escaped user content in a JS variable or replace double curly braces with something else.

**Comment by Akryum** [comment]
Here is an example: https://jsfiddle.net/453mac8b/2/

**Comment by rodrigopedra** [comment]
@Akryum  I tried replacing the double curly braces with their HTML entity equivalent (&amp;#123; and &amp;#125;) but it seems that when javascript read it from the DOM it cannot tell if it is a HTML entity or an actual curly brace.

I understand that I should never use user generated content inside a Vue component, and that is not I am doing, but imagine I am enhancing a existing traditional server-based app to slowly use more and more Vue components, it is a common approach, as far I could find in tutorials, to have the Vue app root in a element that encloses all the app content, and unfortunately as I am doing this enhancement approach there is user generated content that could fall inside the Vue app root.

If there is a way to disable double curly braces completely it would solve my problem, as I generally only use `v-text` and `v-html` to render content. I know I can change the delimiters to something esoteric, and that is what I am doing now to bypass the project I am working on limitation as there is no time to completely rewrite it to a SPA, but if it could be disabled I imagine the app would be faster as it would not have to check for such templates.

I was fiddling with the runtime-only version but I could not get it to work yet, and don't know if it will do I am asking for.

Thanks for the attention

**Comment by Akryum** [comment]
> @Akryum I tried replacing the double curly braces with their HTML entity equivalent (&#123; and &#125;) but it seems that when javascript read it from the DOM it cannot tell if it is a HTML entity or an actual curly brace.

HTML entities are that: entities to encode characters in HTML, so JavaScript will get the real decoded one.

> I was fiddling with the runtime-only version but I could not get it to work yet, and don't know if it will do I am asking for.

It won't help you because it doesn't have the template compilator.

I made it work be wrapping them with `span` tags: https://jsfiddle.net/oqw1fjkz/

**Comment by rodrigopedra** [comment]
@Akryum very clever solution, it worked flawlessly!

Thanks a lot!
