### ISSUE TITLE
[Suggestion] Custom proxy or prefix for component props

### ISSUE THREAD

**Issue by devistar** [vuejs/vue#7867]
### What problem does this feature solve?
When we define props in component, in general we give friendly and understandable props names. Given that they are proxied to this as well as data attributes, these friendly names can no longer be used. If I want to modify a prop, I will have to define a data attribute that can be modified but I can not use this friendly name that I gave to the prop.

It would be interesting to be able to proxy the props to an instance variable or to add a prefix without proxying to this. So we would have a public interface for props with friendly names that would be available for the data attributes in the component.

### What does the proposed API look like?
```javascript
Vue.component('select', {
  proxy: {
    // Here we can define proxy rules
  },
  props: ['items'],
  data: function() {
    return {
      items: [];
    }
  },
  created() {
    this.items = this.props.items;
    // or
    this.items = this.props_items;
  }
})
```

I think you understood the idea.

**Comment by yyx990803** [comment]
You can already do `return { localItems: this.$props.items }`, unless I didn't really understand what you mean.

**Comment by devistar** [comment]
I mean give a way to proxy props elsewhere than this to avoid data name conflict. 
But it is indeed possible to add the local prefix to a data attribute. It was just an idea. "items" is just an example, sometimes I would like to declare a data attribute with the same name as a prop but it's not possible.

Thanks for your quick reply.
