### ISSUE TITLE
Not correct width from DOM object

### ISSUE THREAD

**Issue by borodadada** [vuejs/vue#7870]
### What problem does this feature solve?
	mounted: function () {
		this.$nextTick(function () {

			this.width.one = this.$refs.refList.$children["0"].$el.children[1].clientWidth
		})
	},

I have div object, in this div put text, parameter width = auto
Size in browser inspector = 488px, in this.width.one = 356px
My clientWidth = offsetWidth
If i create static width for this div, all work correct!

### What does the proposed API look like?
this.width.one = 488px

**Comment by yyx990803** [comment]
This is not a feature request. If you want to report a bug, use the proper format.
