### ISSUE TITLE
关于typescript定义文件的一点建议

### ISSUE THREAD

**Issue by kangkang520** [vuejs/vue#7872]
### What problem does this feature solve?
因为项目中是通过cnd来使用vue的，而且项目使用的是typescript，希望.d.ts文件中增加一些全局的定义，以方便编码，而不是一定要import进来才能进行。
望采纳，谢谢！
（>_<）

### What does the proposed API look like?

```typescript
declare interface Vue{
    //...
}
//其他
```

**Comment by yyx990803** [comment]
你可以自己写一个文件 import 之后 declare 啊...
