### ISSUE TITLE
Incorrect "invalid prop" warning with prop of type Symbol

### ISSUE THREAD

**Issue by seanmcoleman** [vuejs/vue#7873]
### Version
2.5.16

### Reproduction link
[https://github.com/seanmcoleman/vuejs-bug](https://github.com/seanmcoleman/vuejs-bug)

### Steps to reproduce
Create simple component with a required prop of type Symbol. Pass a Symbol to this component. 

### What is expected?
No warnings.

### What is actually happening?
A warning is given:

[Vue warn]: Invalid prop: type check failed for prop "symbolProp". Expected , got Symbol.

---
The warning message itself is wrong. In the message "expected" type is empty (space before comma).

**Comment by jkzing** [comment]
Um...because in this case you are using Symbol polyfill, and vue did not recognize it properly during prop types checking.

**Comment by seanmcoleman** [comment]
@jkzing I didn't explicitly add a Symbol polyfill as this is a new, barebones Vuejs build. From my understanding of the documentation, Vuejs supports Symbol as a prop type out of the box. I can't seem to find any information on a different way to use Symbol prop types.

**Comment by yyx990803** [comment]
Seems to be working with native Symbol: https://jsfiddle.net/h7727urk/

When you use a build setup, `babel-preset-env` probably polyfills Symbol based on the browser targets you are targeting. It's typically sub-optimal to use Symbol polyfills, so if you are only targeting browsers that have native Symbols, make sure to tweak your browser target for `babel-preset-env` in `.babelrc`.

Either way, this is not a bug in Vue core, likely a setup issue for the vue-cli 2.x webpack template.

**Comment by seanmcoleman** [comment]
@yyx990803 sounds good, I will try that. Perhaps there is still a bug in how the warning message is generated though. 

`[Vue warn]: Invalid prop: type check failed for prop "symbolProp". Expected , got Symbol.` I think you can see that the "expected" prop type is is rendered blank (right before the comma).
