### ISSUE TITLE
VUE的SSR为什么既要打包server.bundle又要打包client.bundle两个文件？

### ISSUE THREAD

**Issue by cwc845982120** [vuejs/vue#7874]
不是应该服务端路由匹配后render domString 然后渲染页面，那client.bundle.js的作用是什么，为什么要打包client.bundle.js文件？

**Comment by JounQin** [comment]
…… SSR 只负责首屏渲染，页面打开后用户还要操作啊

**Comment by cwc845982120** [comment]
@JounQin 意思是除了首屏，用户接下来的操纵是和非SSR一致的，如果一致那SEO问题是如何解决的，如果不一致，那就没必要啊，有点不理解。
