### ISSUE TITLE
子组件也想使用组件的key

### ISSUE THREAD

**Issue by likyh** [vuejs/vue#7876]
### What problem does this feature solve?
子组件也想使用组件的key，有时候比如我的组件内部在循环产生多个的时候，也想要使用key，但现在定义一个名字为key的prop会报错，能否把这个报错取消掉，让key能顺利传入子组件呢？

### What does the proposed API look like?
定义名字为key的prop时不会报错，让key能顺利传入子组件

**Comment by posva** [comment]
The key is usually an attribute of the object passed down to the component. If it's not the case, you can still create a prop (not named key) and pass down the same property you use for the key
