### ISSUE TITLE
@keydown.escape does not work in Edge

### ISSUE THREAD

**Issue by salomvary** [vuejs/vue#7880]
### Version
2.5.16

### Reproduction link
[https://codepen.io/anon/pen/EEmBGm](https://codepen.io/anon/pen/EEmBGm)

### Steps to reproduce
- Open the  linked reproduction link in Microsoft Edge
- Open F12 developer tools console section
- Click inside the input field on the Codepen output
- Hit escape on the keyboard

### What is expected?
@keydown.escape and @keydown.esc handlers should be triggered (should log 'esc' and 'escape').

### What is actually happening?
@keydown.escape and @keydown.esc handlers are not triggered. Only the unfiltered @keydown handler and @keydown.27 are triggered.

---
Issue tested in Microsoft Edge 41.16299.15.0. Verified to be working as expected on latest Safari, Chrome and Firefox on macOS.

**Comment by posva** [comment]
Cannot test on Edge right now but this may be related to the name Edge is giving to the name. If it's actually failing this is a **good first issue**, the fix should be at https://github.com/vuejs/vue/blob/dev/src/compiler/codegen/events.js#L21 (I can be wrong about the fix, but if I'm not it will help someone to get a contribution 🙂 )
