### ISSUE TITLE
BUG: createElement not accepting first argument as function

### ISSUE THREAD

**Issue by manico** [vuejs/vue#7883]
### Version
2.5.13

### Reproduction link
[https://codepen.io/manico/pen/KoqRYq](https://codepen.io/manico/pen/KoqRYq)

### Steps to reproduce
Create render function with first argument as function that returns html tag.

### What is expected?
Element should render.
https://codepen.io/manico/pen/JLJvQw

### What is actually happening?
Element is not rendered.
https://codepen.io/manico/pen/KoqRYq

---
According to documentation (https://vuejs.org/v2/guide/render-function.html#createElement-Arguments), first argument of createElement function can be function that returns html tag name or component options. When we have function that returns html tag name this does not work.

As far as I can see (not sure if I'm looking in the right place https://github.com/vuejs/vue/blob/dev/src/core/vdom/create-element.js#L96) there is no handling of function for tag. So maybe documentation is out of date?

**Comment by HerringtonDarkholme** [comment]
I believe this is a documentation problem. `Function` should be a constructor of Vue subclass created by `Vue.extend`.

**Comment by javoski** [comment]
As the first argument of `createElement`, the function should be an async factory that will finally resolve a component definition, see [https://vuejs.org/v2/guide/components.html#Async-Components](https://vuejs.org/v2/guide/components.html#Async-Components)

**Comment by manico** [comment]
Maybe documentation should be changed as it clearly states: 
https://vuejs.org/v2/guide/render-function.html#createElement-Arguments

> HTML tag name, component options, or **function returning one of these**. Required.

**Comment by Jfs007** [comment]
I want to use function as first argument, this is my code 
![image](https://user-images.githubusercontent.com/20514800/45436264-f4c2b580-b6e4-11e8-8882-34bde079a278.png)
but it looks like it's going to cause an infinite loop  
and it's not working
![image](https://user-images.githubusercontent.com/20514800/45436295-0c9a3980-b6e5-11e8-868c-48e49668f37d.png)
