### ISSUE TITLE
a:href的问题

### ISSUE THREAD

**Issue by Chenjiajun92** [vuejs/vue#7885]
### Version
2.3.0

### Reproduction link
[https://github.com/Chenjiajun92](https://github.com/Chenjiajun92)

### Steps to reproduce
<ul data-role="listview" data-inset="true" class="lists_vue" v-for="(data, index) in listsData">
                <li class="f-s-14 w-s-initial">
                    <span :class="{'for-label-72':(gtype == 1 || gtype == 2),'for-label-52':(gtype == 3 || gtype == 4 || gtype == 5 || gtype == 6)}">
                        <b v-if="data.isread_health == 1">标题1</b>
                        <b v-if="data.isread_casehistory == 1">标题2</b>
                    </span>
                    <a v-bind:href="'__CONTROLLER__/user?gtype=<{$gtype}>&uid=' data.id '&ufrom=' data.user_from" rel="external">
                        <p class="f-s-16">
                            <span v-text="'姓名:' data.name"></span><span v-if="data.is_one_way == 1">(单向)</span>
                            <span v-if="gtype == 1" class="pull-right" v-text="'床号:' data.bednumber '床'"></span>
                        </p >
                        <p class="f-s-16">
                            <span v-text="'年龄:' data.age_show"></span>
                            <span v-text="'性别:' data.sex" class="pull-right"></span>
                        </p >
                        <p class="f-s-16" v-if="gtype == 1"><span v-text="'入院日期:' data.date"></span></p >
                        <p class="f-s-16" v-if="gtype == 2"><span v-text="'出院日期:' data.date"></span></p >
                    </ a>
                    <div class="ui-grid-a">
                        <a :class="{'ui-block-a':true,'ui-link':true,'ui-btn':true,'ui-btn-d':true,'ui-shadow':true,'ui-corner-all':true}" style="width: 49%;margin-right: 1%;padding: 8px;" :href="'__MODULE__/HealthRecord/recordTm?gtype=<{$gtype}>&tid=<{$doctor_team_id}>&uid=' data.id '&ufrom=1'" rel="external" ><span>按钮1</span></ a>
                        <span class="ui-block-b ui-link ui-btn ui-btn-e ui-shadow ui-corner-all" style="width: 49%;margin-left: 1%;padding: 8px;" href="" @click="alert(1)" rel="external"><span>按钮2</span></span>
                    </div>
                </li>
            </ul>

### What is expected?
a标签的都能显示

### What is actually happening?
所有的a标签都能点击而且成功跳转,但从第二个a标签开始的样式就没有了,要点击过才有样式出来!还有只有:href的链接只要填写内容都会导致该样式消失

**Comment by Chenjiajun92** [comment]
<ul data-role="listview" data-inset="true" class="lists_vue" v-for="(data, index) in listsData">
              <li class="f-s-14 w-s-initial">
                  <span :class="{'for-label-72':(gtype == 1 || gtype == 2),'for-label-52':(gtype == 3 || gtype == 4 || gtype == 5 || gtype == 6)}">
                      <b v-if="data.isread_health == 1">标题1</b>
                      <b v-if="data.isread_casehistory == 1">标题2</b>
                  </span>
                  <a v-bind:href="'__CONTROLLER__/user?gtype=<{$gtype}>&uid='+data.id+'&ufrom='+data.user_from" rel="external">
                      <p class="f-s-16">
                          <span v-text="'姓名:'+data.name"></span><span v-if="data.is_one_way == 1">(单向)</span>
                          <span v-if="gtype == 1" class="pull-right" v-text="'床号:'+data.bednumber+'床'"></span>
                      </p >
                      <p class="f-s-16">
                          <span v-text="'年龄:'+data.age_show"></span>
                          <span v-text="'性别:'+data.sex" class="pull-right"></span>
                      </p >
                      <p class="f-s-16" v-if="gtype == 1"><span v-text="'入院日期:'+data.date"></span></p >
                      <p class="f-s-16" v-if="gtype == 2"><span v-text="'出院日期:'+data.date"></span></p >
                  </ a>
                  <div class="ui-grid-a">
                      <a :class="{'ui-block-a':true,'ui-link':true,'ui-btn':true,'ui-btn-d':true,'ui-shadow':true,'ui-corner-all':true}" style="width: 49%;margin-right: 1%;padding: 8px;" :href="'__MODULE__/HealthRecord/recordTm?gtype=<{$gtype}>&tid=<{$doctor_team_id}>&uid='+data.id+'&ufrom=1'" rel="external" ><span>按钮1</span></ a>
                      <span class="ui-block-b ui-link ui-btn ui-btn-e ui-shadow ui-corner-all" style="width: 49%;margin-left: 1%;padding: 8px;" href="" @click="alert(1)" rel="external"><span>按钮2</span></span>
                  </div>
              </li>
          </ul>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
