### ISSUE TITLE
Issue with Recursive Component and event propagation

### ISSUE THREAD

**Issue by Codermar** [vuejs/vue#7889]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/Codermar/k0wL3kcv/21/](https://jsfiddle.net/Codermar/k0wL3kcv/21/)

### Steps to reproduce
In the provided fiddle link, click on a node to see errors.

### What is expected?
Recursive component should be able to stop propagation of events above the clicked node and pass the current node data.

### What is actually happening?
When I emit @toggled.stop I get:
 [Vue warn]: Error in event handler for “toggled”: “TypeError: $event.stopPropagation is not a function”
Note: If I pass the $event from the click to the $emit(), the error goes away but the event bubbles up without stop passing the whole tree of data

**Comment by javoski** [comment]
Hi, looks like you had mixed up custom component events with native DOM events, the `stop` modifier is for DOM events only.
Please check out the [revision of your demo](https://jsfiddle.net/k0wL3kcv/57/) to see whether it meets your expectation or not.

**Comment by Codermar** [comment]
I get the mixup on the modifiers now. However, In my expectation, @click.stop should fire only once on each node and not bubble up. If you see the console you will see that the event is bubbling up and I end up with the whole tree data instead of just the clicked node.

**Comment by posva** [comment]
the click event only fires once. the toggled event is manually being bubbled up. So everything looks fine here

**Comment by pranavkumar389** [comment]
Hi, with click event also the event bubbles up. Any solution?
