### ISSUE TITLE
Error in updateChildren if method not declared (Cannot read property '_withTask' of undefined)

### ISSUE THREAD

**Issue by mycoin** [vuejs/vue#7890]
### Version
2.5.16

### Reproduction link
[https://output.jsbin.com/zusikefaju](https://output.jsbin.com/zusikefaju)

### Steps to reproduce
if the method was not declared, once update the children, an error like "Cannot read property '_withTask' of undefined" will occur. 

although a warning like '[Vue warn]: Invalid handler for event "click": got undefined', but if developer disabled the warn, he will be difficult to resolve this problem.

### What is expected?
no error happen. and the rendering should be continued

### What is actually happening?
error occured

**Comment by PeachScript** [comment]
I think it is the responsibility of developers, not framework.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Developer should enable warnings in development.

**Comment by mycoin** [comment]
@fnlctrl Yes, you are right. it is the responsibility of developers

But my fucking project did not enable warnings and I can not access the repertory to setup the framework, it makes me wasting too much time to fixed all the problems like "Cannot read property '_withTask' of undefined".
