### ISSUE TITLE
Sync Modifier not working in Component

### ISSUE THREAD

**Issue by maheshshah196** [vuejs/vue#7894]
### Version
2.5.16

### Reproduction link
[https://codepen.io/maheshshah196/pen/wmryMa?editors=1010](https://codepen.io/maheshshah196/pen/wmryMa?editors=1010)

### Steps to reproduce
Just type in any text in input

### What is expected?
text in paragraph should change

### What is actually happening?
paragraph text is not changing.

---
Is there any other way to use sync modifier.

**Comment by PeachScript** [comment]
It is recommended to read the documentation carefully before create an issue:

> For the child component to update foo‘s value, it needs to explicitly emit an event instead of mutating the prop:
>
>```this.$emit('update:foo', newValue)```

From: https://vuejs.org/v2/guide/components.html#sync-Modifier

**Comment by maheshshah196** [comment]
Thanks. 

 This is solved by adding @input="$emit('update:input', input)" on textfield
