### ISSUE TITLE
innerHTML make the content of element lost in IE11

### ISSUE THREAD

**Issue by lxjwlt** [vuejs/vue#7903]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/lxjwlt/4uj9xu8s/](https://jsfiddle.net/lxjwlt/4uj9xu8s/)

### Steps to reproduce
1. click “click” button, it would execute `otherBox.innerHTML = '';`  to clear all the contents of `#other-box`
2. watch the `app.$el` is all right or not

### What is expected?
`app.$el` 's content is correct in all browsers.

### What is actually happening?
chrome: `app.$el` 's content is correct 

Firefox: `app.$el` 's content is correct 

IE11: `app.$el` 's content is empty

---
this bug would appear in IE11, but not in chrome、Firefox

**Comment by posva** [comment]
I cannot test on IE11 right now but this are you sure this does not happen without Vue?

**Comment by Gudradain** [comment]
Indeed the behavior is different in IE but it's not related to vue.js.

Here is a fiddle with the same problem without any vue.js code : https://jsfiddle.net/ods9x68w/4/

**Comment by lxjwlt** [comment]
but i found `app.$el` could not update any more, even if i invoke `app.$forceUpdate()` and modify its data: https://jsfiddle.net/lxjwlt/mp40q3fm/

**Comment by yyx990803** [comment]
This is not something Vue can fix if IE breaks DOM Nodes when they are replaced by innerHTML.
