### ISSUE TITLE
Cannot use slots on component with name Textarea

### ISSUE THREAD

**Issue by alexgrozav** [vuejs/vue#7908]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/238481/](https://jsfiddle.net/50wL7mdz/238481/)

### Steps to reproduce
Name component `Textarea` and add slots.

### What is expected?
Would expect the component to be rendered normally, with the slots distributed properly.

### What is actually happening?
The textarea itself is rendered without any slots other than the default one.

---
I'm building a Vue UI/UX framework at https://github.com/inkline/inkline and I've run into this bug. Can you guys let me know if you can fix it so I won't have to prefix my framework components? Thank you!

**Comment by leopiccionia** [comment]
You can't create a component whose kebab-case name is the name of a HTML tag, as [their names are reserved](https://github.com/vuejs/vue/blob/f76d16ed9507d4c2a90243ea3d77ccf00df29346/src/platforms/web/util/element.js#L11L23).

My suggestion: name it `TextArea` (kebab-cased as `text-area`).

**Comment by alexgrozav** [comment]
I know they are reserved, however vue handles them fine if you use the PascalCase making in your template. The Component replacing `Input` has slots and it's working properly, for example.

**Comment by posva** [comment]
as @leopiccionia said, don't name components with HTML tag names, it will be better for you to prefix the component
