### ISSUE TITLE
关于vue-server-renderer进行混合clientManifest时出现错误，修改源码可以正常混合

### ISSUE THREAD

**Issue by nathenchan** [vuejs/vue#7911]
### Version
2.5.16

### Reproduction link
[http://](http://www.nathendev.com)

### Steps to reproduce
const { createBundleRenderer } = require('vue-server-renderer')
const path = require('path')
const server = require('express')()
const serverBundle = path.join(__dirname,'./dist/vue-ssr-server-bundle.json')

const renderer = createBundleRenderer(serverBundle, {
  runInNewContext: false, // 推荐
  template: require('fs').readFileSync('./views/ssr2/index.html', 'utf-8'),
  clientManifest: path.join(__dirname,'./dist/vue-ssr-client-manifest.json')
})

server.get('*', (req, res) => {
  const context = { url: req.url }
  renderer.renderToString(context, (err, html) => {
    res.send(html)
  })
}).listen(8899)

### What is expected?
不使用clientManifest时，不会报错，但是进行clientManifest混合时会有问题，另外：server端和client端的打包都是正常输出文件的

### What is actually happening?
xxx/node_modules/.npminstall/vue-server-renderer/2.5.16/vue-server-renderer/build.js:7974
    this.publicPath = clientManifest.publicPath.replace(/\/$/, '');

---
修改一句代码可以解决，但具体发生原因不明，在build.js 的7971行左右
//var clientManifest = this.clientManifest = options.clientManifest;
var clientManifest = this.clientManifest = clientManifest = JSON.parse(require('fs').readFileSync(options.clientManifest, 'utf-8'));

**Comment by JounQin** [comment]
`clientManifest` should be an object rather than a path string, just read and parse it by yourself outside.

**Comment by nathenchan** [comment]
在api中确实说明了是对象，但是在https://ssr.vuejs.org/zh/build-config.html 中的代码， 是不是有误？看上去像是使用文件路径赋值即可

**Comment by JounQin** [comment]
`const clientManifest = require('/path/to/vue-ssr-client-manifest.json')` 并不是文件路径
