### ISSUE TITLE
setData() doesn't work correctly

### ISSUE THREAD

**Issue by Remeic** [vuejs/vue#7912]
### Version
2.5.16

### Reproduction link
[https://github.com/Remeic/vue-highlighter/tree/tests](https://github.com/Remeic/vue-highlighter/tree/tests)

### Steps to reproduce
Clone repository, checkout on tests branch and run yarn test

### What is expected?
wrapper.setData() change data of App correctly and directive can update the highlighted word

### What is actually happening?
setData doesn't update correctly the data and console print "Cannot read property 'split' of undefined", seems wrapper is not mounted, if i remove data from App.vue SFC error changes and it is "Avoid adding reactive properties to a Vue instance or its root $data at runtime - declare it upfront in the data option."

**Comment by yyx990803** [comment]
This should be reported to https://github.com/vuejs/vue-test-utils instead.
