### ISSUE TITLE
Prop changes do not always trigger $watch in IE11

### ISSUE THREAD

**Issue by fenduru** [vuejs/vue#7915]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/242700/](https://jsfiddle.net/50wL7mdz/242700/)

### Steps to reproduce
Open JSFiddle in IE11, and scroll the scrollbar up and down rapidly. Observe the console warns that occur when a prop update was missed

### What is expected?
The `$watch` should be fired for every scroll event

### What is actually happening?
Vue is handling subsequent scroll events before the watch is firing. In my use case we are integrating with another system, and it is important that we don't skip events.

---
This change is reproducible in versions >= 2.4.3 (you can change the version to 2.4.2 in the reproducer to see the correct behavior). Looking at the change log, it seems like [this commit](https://github.com/vuejs/vue/commit/844a540c647dfa93dc714540953524830dd3475a) is a likely culprit.

**Comment by posva** [comment]
it's indeed skipping some callbacks. Not sure if this is easily fixable without breaking something else 🤔

**Comment by fenduru** [comment]
@posva I'm actually able to reproduce the skipped events even in Chrome if I turn on 6x slowdown CPU throttling. Practically though this is mainly a problem in IE11 because falling back to `setTimeout` introduces a minimum of 10ms delay. Also, in the case of scroll events, it is triggering many layouts/paints before the prop is updated in Vue resulting in a huge lag in my app. I do not think it is correct to defer application updates in a setTimeout.

With 2.4.2:

![2-4-2](https://user-images.githubusercontent.com/1354771/38216000-7152f78c-3697-11e8-9569-107701c4a600.gif)

With 2.5.16

![2-5-16](https://user-images.githubusercontent.com/1354771/38216015-7bac8716-3697-11e8-976c-0b7b4e39e517.gif)

I'm happy to submit a PR once we have an idea of how we want to solve this.

I actually wonder if https://github.com/vuejs/vue/commit/844a540c647dfa93dc714540953524830dd3475a is just paving over a more fundamental problem

**Comment by fenduru** [comment]
@posva @yyx990803 and thoughts on how we want to approach this? I'm eager to start working on a PR because this is severely impacting my application

**Comment by posva** [comment]
I'm sorry, it's not something I know how to help you with 😞

**Comment by fenduru** [comment]
@posva what needs to be done in order to move this forward?

**Comment by fenduru** [comment]
@yyx990803 what needs to be done here? I'm more than happy to contribute

**Comment by fenduru** [comment]
@sodatea I'm willing to work on this, however I need a small amount of guidance on what the core team wants to see here (at a high level). In my opinion https://github.com/vuejs/vue/commit/844a540c647dfa93dc714540953524830dd3475a is incorrect and should be reverted, however I suspect that will not be well received.

**Comment by Justineo** [comment]
It’s likely to be reverted in 2.6 according to discussion under several related issues.

**Comment by fenduru** [comment]
@Justineo is there a specific issue tracking that discussion? Also could we label this with "nextTick related" label to make sure it is considered alongside the other nextTick issues?

**Comment by fenduru** [comment]
This is really hurting my app - we have a `v-model` that keeps track of scroll position and renders based on it. In IE, using setTimeout causes the scroll events to always "cut in line" before the setTimeout, resulting in the view never updating until you stop scrolling. Right now we are resorting to circumventing vue here for rendering and updating the scroll position, since it is just not shippable like this.

Are there any updates on the status of the 2.6 discussion regarding the $nextTick debacle? There seems to be some radio silence. Can this please labeled with `nextTick related` as well?

CC @Justineo @posva @yyx990803

**Comment by sirlancelot** [comment]
Does changing `macroTimerFunc` to use `requestAnimationFrame()` instead of `setTimeout` fix the issue? Does it open a different can of worms?

**Comment by fenduru** [comment]
Looks like #8450 will fix this
