### ISSUE TITLE
Vuejs deffered component misbehaves

### ISSUE THREAD

**Issue by McKabue** [vuejs/vue#7916]
i have created a component loader, between it gets a deferred component, it re-renders infinitely: here are two jsfiddles:

## [working as expected][1]

     Vue.component('create', Vue.extend({
            template: '<h1>HEADER</h1>'
        }));

    Vue.component('component-loader', function (resolve) {
            var model = Vue.extend({
                props: ['name'],
                watch: {
                    name: function (newValue, oldValue) {
                       alert(newValue);
                    }
                },
                render: function (createElement) {
                    var self = this;
                    alert(self.name);
                    var m = function (resolve) {
                            resolve({
                                template: '<component is="' + self.name + '"></component>'
                            });
                    };

                    return createElement(m);
                }
            });
            resolve(model);
        });
        
        
        var viewModel = new Vue({});

        viewModel.$mount('#app');

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.js"></script>

    <div id="app">
    <component-loader name="create"></component-loader>
    </div>

## [Not working][2]
this fiddle will fire after every **5 seconds**. it does also not render the component as the first one

     Vue.component('create', Vue.extend({
            template: '<h1>HEADER</h1>'
        }));

    Vue.component('component-loader', function (resolve) {
            var model = Vue.extend({
                props: ['name'],
                watch: {
                    name: function (newValue, oldValue) {
                       alert(newValue);
                    }
                },
                render: function (createElement) {
                    var self = this;
                    alert(self.name);
                    var m = function (resolve) {
                        setTimeout(function () {
                            resolve({
                                template: '<component is="' + self.name + '"></component>'
                            });
                        }, 5000);
                    };

                    return createElement(m);
                }
            });
            resolve(model);
        });
        
        
        var viewModel = new Vue({});

        viewModel.$mount('#app');

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.js"></script>

    <div id="app">
    <component-loader name="create"></component-loader>
    </div>

what could be the problem? the component loader creates a dynamic component and renders it by name...

  [1]: https://jsfiddle.net/mckabue/L90p565e/5/
  [2]: https://jsfiddle.net/mckabue/L90p565e/6/

**Comment by zllovesuki** [comment]
You might have a [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing) problem.

**Comment by McKabue** [comment]
@zllovesuki i dont think that could be the problem. i changed the variable names and the issue persists : https://github.com/vuejs/vue/issues/7921
