### ISSUE TITLE
after emit a event registe via $once, _events property still keep that as a empty array

### ISSUE THREAD

**Issue by vtejuf** [vuejs/vue#7917]
### Version
2.5.2

### Reproduction link
[https://codepen.io/vtejuf/project/editor/ZeYVKx](https://codepen.io/vtejuf/project/editor/ZeYVKx)

### Steps to reproduce
registe 10 event via $once , then $emit those event

### What is expected?
this._events property empty

### What is actually happening?
this._events keep those events as empty array

---
is that deliberately? if it is & why? thx a lot

**Comment by posva** [comment]
Well, it is empty 😆 . It should be an array from the beginning but having non-existant things is usually easier in js (classic `(a || a =[]).push(...)`)
`_events_ is an internal property anyway, we discourage you from using it in applications

**Comment by vtejuf** [comment]
@posva thanks for your answer.
in apidoc : 'vm.$once( event, callback ). Listen for a custom event, but only once. The listener will be removed once it triggers for the first time.'
i want to know what is 'removed' mean?

code like:
> beforeMount() {
    // register 10 events via $once
    for(let l=10;l>0;l--){
      var name = 'event_once_'+l
      this.$once( name, ()=>{} )
    }
    // this._events: {event_once_1: [func], event_once_2: [func], ...}
},
mounted() {     
    // emit all
    for(let l=10;l>0;l--){
      var name = 'event_once_'+l
      this.$emit(name, name+' done')
    }
    // this._events: {event_once_1: [], event_once_2: [], ...}
    // why not empty object {}
}

[demo on codepen](https://codepen.io/vtejuf/project/editor/ZeYVKx)

**Comment by posva** [comment]
it means removed _as a listener_. Same as with `removeListener` (for native events)

**Comment by vtejuf** [comment]
well, zero listener, but 'events' do not remove event array, that make me confused.
at least i get confirmed by official. 
thanks a lot again @posva
