### ISSUE TITLE
Vuejs deferred component misbehaves

### ISSUE THREAD

**Issue by McKabue** [vuejs/vue#7921]
### Version
2.2.1

### Reproduction link
[https://stackoverflow.com/questions/49544809/vuejs-deferred-component-misbehaves](https://stackoverflow.com/questions/49544809/vuejs-deferred-component-misbehaves)

### Steps to reproduce
here are two jsfiddles:

## [working as expected][1]

     Vue.component('create', Vue.extend({
            template: '<h1>HEADER</h1>'
        }));

    Vue.component('component-loader', function (resolve) {
            var model = Vue.extend({
                props: ['name'],
                watch: {
                    name: function (newValue, oldValue) {
                       alert(newValue);
                    }
                },
                render: function (createElement) {
                    var self = this;
                    alert(self.name);
                    var m = function (resolve) {
                            resolve({
                                template: '<component is="'   self.name   '"></component>'
                            });
                    };

                    return createElement(m);
                }
            });
            resolve(model);
        });
        
        
        var viewModel = new Vue({});

        viewModel.$mount('#app');

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.js"></script>

    <div id="app">
    <component-loader name="create"></component-loader>
    </div>

## [Not working][2]
this fiddle will fire after every **5 seconds**. it does also not render the component as the first one

     Vue.component('create', Vue.extend({
            template: '<h1>HEADER</h1>'
        }));

    Vue.component('component-loader', function (loaderResolve) {
            var model = Vue.extend({
                props: ['name'],
                watch: {
                    name: function (newValue, oldValue) {
                       alert(newValue);
                    }
                },
                render: function (createElement) {
                    var self = this;
                    alert(self.name);
                    var m = function (resolve) {
                        setTimeout(function () {
                            resolve({
                                template: '<component is="'   self.name   '"></component>'
                            });
                        }, 5000);
                    };

                    return createElement(m);
                }
            });
            loaderResolve(model);
        });
        
        
        var viewModel = new Vue({});

        viewModel.$mount('#app');

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.js"></script>

    <div id="app">
    <component-loader name="create"></component-loader>
    </div>

what could be the problem?

  [1]: https://jsfiddle.net/mckabue/L90p565e/7/
  [2]: https://jsfiddle.net/dL4puszo/2/

### What is expected?
return a resolved component

### What is actually happening?
this fires the main(parent) component infinitely  after resolving child component

**Comment by McKabue** [comment]
this also happens with the latest version of vuejs : https://jsfiddle.net/dL4puszo/4/

**Comment by LinusBorg** [comment]
Well, you should move the definition of the async component out of render, otherwise you will re-create it over and over.

Move it to `created` and save the component on the instance.

https://jsfiddle.net/Linusborg/3u3cLpt3/89/

**Comment by McKabue** [comment]
the issue is partially resolved: the end goal is to have some dynamic component creation asynchronously, exactly like this. https://jsfiddle.net/L90p565e/13/ but asynchronously... and addition, 
### why is the create being called twice here?

<pre>
<code>
<div id="app">
enter name of component (create, edit)
<input v-model="componentname" />
<component-loader :name="componentname"></component-loader>
</div>

 Vue.component('create', Vue.extend({
        template: '<h1>CREATE HEADER</h1>'
    }));
    
     Vue.component('edit', Vue.extend({
        template: '<h1>EDIT HEADER</h1>'
    }));

Vue.component('component-loader', function (resolve) {
        var model = Vue.extend({
            props: ['name'],
            watch: {
                name: function (newValue, oldValue) {
                   alert(newValue);
                }
            },
            render: function (createElement) {
                var self = this;
                alert(self.name);
                var m = function (resolve) {
                    
                        resolve({
                            template: '<component is="' + self.name + '"></component>'
                        });
                    
                };

                return createElement(m);
            }
        });
        resolve(model);
    });
    
    
    var viewModel = new Vue({
    data: {
    componentname: ''
    }
    });

    viewModel.$mount('#app');
</code>
</pre>

**Comment by LinusBorg** [comment]
You already opened a topic nun our forum, please ask additional questions there. 

This issue is resolved since no. Bug is present.

**Comment by McKabue** [comment]
@LinusBorg thanks. i replied in the forum
