### ISSUE TITLE
Mixin provide with Symbols don't get merged properly

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#7923]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/hirokiosame/38nzxq6c/26/](https://jsfiddle.net/hirokiosame/38nzxq6c/26/)

### Steps to reproduce
Run the code. The injected result will show `[undefined, "bar"]` in the console.

### What is expected?
For the merging to work properly. The expected result is `['foo', 'bar']`, which is what you'll see when you convert `keyA` and `keyB` into strings.

### What is actually happening?
Merging fails:  `[undefined, "bar"]`

**Comment by hirokiosame** [comment]
@posva Would you mind taking a look at this?

**Comment by jennivey2009** [comment]
WHAT IS THIS FOR???

**Comment by yyx990803** [comment]
Closed via #7926
