### ISSUE TITLE
<select> is broken when options values are bound to Dates

### ISSUE THREAD

**Issue by shameleo** [vuejs/vue#7928]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/azpxdt3a/1/](https://jsfiddle.net/azpxdt3a/1/)

### Steps to reproduce
Try select any item except first one.

### What is expected?
Item selected.

### What is actually happening?
<select> always shows first item. Once any item except first is selected, it's no more possible to select first one (actually, it's possible, as <select> shows correct selected item after the same item was selected twice in a row)

---
It seems the bug was introduced in ver 2.4.2. Does not reproduced with objects instead of dates: https://jsfiddle.net/pr847ek7/

**Comment by w3cj** [comment]
After looking into it, looseEqual does not handle dates correctly.

https://github.com/vuejs/vue/blob/dev/src/shared/util.js#L273

I added a check for dates in looseEqual, but not sure if this is the best way to go about it. Could use a second pair of eyes. 👀
