### ISSUE TITLE
@created: Strict mode code may not include a with(), OR how i can mix `this` to scopedSlot?

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#7932]
### Version
2.5.16

### Reproduction link
[https://vuejs.org/v2/guide/render-function.html#Slots](https://vuejs.org/v2/guide/render-function.html#Slots)

### Steps to reproduce
i'm trying mix custom scopedSlots to already loaded component.
It looks like this:
1. @created Object.defineProperty(this, '$scopedSlots', ...)
2. setter from $scopedSlots add custom slots to already existed slots
3. custom slots created from:
```
// template is string contained html code
(template, scopedSlots) => {
  let slotArgs = template.match(/slot-scope="(.+)"/)[1]
  let slotBody = Vue.compile(template).render.toString().match(/return. \)/)[0]
  
  scopedSlots[slotName] = eval(
    `(${slotArgs}) => {
      with(this)
      ${slotBody}
    }`
  )
}
```

### What is expected?
My mix scopedSlot must work.

### What is actually happening?
[Vue warn]: Error in created hook: "SyntaxError: Strict mode code may not include a with statement"
vue.esm.js?efeb:1741 SyntaxError: Strict mode code may not include a with statement

---
Now i use `let { _c, _e, _s, _v, $el, $refs, ... } = this` before `eval`
If i can use some helper for render, please help me.
Or please enable strict mode after @mounted

**Comment by leopiccionia** [comment]
1. The use of `with` statement is [discouraged](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with) and may result in forward-incompatible code.
2. `vm.$scopedSlots` is supposed to be [read-only](https://vuejs.org/v2/api/index.html#vm-scopedSlots).

**Comment by patriciussanctus** [comment]
@leopiccionia i known about `with`, but vue.js use it.
And... oh noo, my method works! But, i have problems with scope.

**Comment by wangyi7099** [comment]
use new Function instead of eval
```javascript
   "use strict";
       var code = `with(b){ console.log(a) }`
       var b = {
         a: 1
       }
       // success
       var func = new Function(code);
       func();
       // fail
       eval(
        `with(b){ console.log(a) }`
       )
```

**Comment by posva** [comment]
Closing as you didn't even provide a repro/playground and you are hacking your way around Vue. You should talk about this in the forum or chat instead and explain what you are trying to achieve
