### ISSUE TITLE
同一个vue动态生成的html标签，css不生效

### ISSUE THREAD

**Issue by Amoslb** [vuejs/vue#7945]
### Version
2.4.0

### Reproduction link
[https://github.com/amoslb](https://github.com/amoslb)

### Steps to reproduce
写的一个组件 两个i标签一个是动态生成的一个  直接写的dom  动态渲染的css最后没生效,打包出现问题

### What is expected?
 两个标签的css同时生效

### What is actually happening?
只有一个生效

---
我有两个i标签 并且 css为同一类名，放在了同一个vue组件下面  不同的是 一个是用js v-html动态渲染的 一个是写的dom ，最后打包的时候 动态生成的 标签的css没有效果，也代表着没有引入， 我最后把这个放在common.css解决的

**Comment by Justineo** [comment]
请提供可复现问题的代码，reproduction link 不要乱填，谢谢配合。不方便在一段代码里展现的话建议可以建一个 repo 并且提供最小的可复现环境。

**Comment by Amoslb** [comment]
<i v-html='spaceHtml'></i>
                                <i  class="ms-tree-space"></i>

          this.spaceHtml += "<i class='ms-tree-space'></i>" 当前vue中的ms-tree-space样式在一个i标签里面 没有生效。

**Comment by Amoslb** [comment]
<i v-html='spaceHtml'></i>
                            <i  class="ms-tree-space"></i>

      this.spaceHtml += "<i class='ms-tree-space'></i>" 当前vue中的ms-tree-space样式在第一个i标签里面 没有生效。

**Comment by posva** [comment]
As @Justineo said, please provide a repro. Instructions are in the https://new-issue.vuejs.org/?repo=vuejs/vue
Please open a new issue once you have a reproduction
