### ISSUE TITLE
The dynamically created input is associated with each other.

### ISSUE THREAD

**Issue by axl-axl** [vuejs/vue#7952]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/axl_axl/eywraw8t/8749/](https://jsfiddle.net/axl_axl/eywraw8t/8775/)

### Steps to reproduce
Create 2 radio by click add.
Click the third radio that changed the third and fourth radio.
I just want to change the third.

### What is expected?
Click the third change the third,click the fourth change the fourth.

### What is actually happening?
click the third changed the third and the foutth.

---
the first and the second is working well. the new radio is created by the add(), they work bad.

**Comment by indus** [comment]
You are pushing (a refernece of) the very same (!) object to the array multiple times. You should create new distinct objetcs to make you example it work, e.g.: 

```
xx.push(Object.assign({},this.addItem});
```

**Comment by axl-axl** [comment]
thanks. it's peculiarity of object....
