### ISSUE TITLE
slot-scope destructuring with alias does not seem to work

### ISSUE THREAD

**Issue by jronwesternvp** [vuejs/vue#7956]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/261895/](https://jsfiddle.net/50wL7mdz/261895/)

### Steps to reproduce
1.) We tried to v-bind the slot to an object
2.) On consuming the slot we used slot-scope with a deconstructed and aliased variable.
3.) It says "TypeError: Cannot read property 'title' of undefined"

### What is expected?
It should deconstruct the object correctly as it's okay without the alias

### What is actually happening?
the alias seems to be not working, returning an "undefined" value

**Comment by LinusBorg** [comment]
You mixed up the order. it's `oldname: newname`, not `newname: oldname`.

Working fiddle: https://jsfiddle.net/50wL7mdz/261938/

**Comment by jronwesternvp** [comment]
my bad. Thanks
