### ISSUE TITLE
.bubble event modifier to pass along events, especially for those with args

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue#7965]
### What problem does this feature solve?
Bubbling up an event from a deep child can be really cumbersome (without an event bus) because you have to emit the same event from every parent up the tree until it reaches its target. An event modifier like `.bubble` would be really nice.

### What does the proposed API look like?
This:
```vue
<child @hi.bubble/>
```

Instead of repeating this:
```vue
<child @hi="(...args) => $emit('hi', ...args)"/>

// or even:

<child @hi="$emit('hi')"/>
```

**Comment by yyx990803** [comment]
In general I'm against adding more syntax sugar, and this particular use case IMO is not common enough to warrant a new addition.

You can also simplify this a bit in userland:

``` js
Vue.prototype.$bubble = function (event) {
  return (...args) => { this.$emit(event, ...args) }
}
```
