### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected end of input at eval

### ISSUE THREAD

**Issue by yooouuri** [vuejs/vue#7967]
### Version
2.5.16

### Reproduction link
[https://gist.github.com/yooouuri/845d8b95d3343748ef698312ac5b12f3](https://gist.github.com/yooouuri/845d8b95d3343748ef698312ac5b12f3)

### Steps to reproduce
Using fetch() to post or get some data

### What is expected?
Get some json after a fetch

### What is actually happening?
`Home.vue?5584:89 Uncaught (in promise) SyntaxError: Unexpected end of input at eval (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/youri/PhpstormProjects/kwetter-web/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home.vue (app.js:2081)`

**Comment by fnlctrl** [comment]
This is probably related to your webpack settings (broken cache caused by cache-loader, etc.), try clearing the cache files.
The link you provided isn't a valid reproduction since it cannot be run, please provide a github repo in if the error persists.
