### ISSUE TITLE
[Some] HTML entity in template gets re-escaped [incorrectly] by vue.js

### ISSUE THREAD

**Issue by kidplug** [vuejs/vue#7969]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/270981/](https://jsfiddle.net/50wL7mdz/270981/)

### Steps to reproduce
In the html template, provide an html "title" attribute that contains an HTML entity using ascii codes. 

### What is expected?
Vue should not mess with or re-escape/entify the literal ampersand character in the HTML template.

### What is actually happening?
Vue sees the ampersand character in the html attribute and changes it to the HTML amp entity - resulting in a rendered ampersand character.

---
Trying to put a newline character into a title attribute within my template file.
Seems like Vue has some recognized entities (the named ones perhaps) which it leaves alone, but entities using ASCII codes get corrupted.
Entities using ASCII codes seem to behave fine when placed as content inside a tag - but not when placed into an HTML attribute.

**Comment by kidplug** [comment]
I guess its more accurate to say Unicode vs ascii codes above.

**Comment by posva** [comment]
HTML escapes are different from js escapes. Using that escape in js just doesn't work: https://jsfiddle.net/w85Lvwa6/

**Comment by kidplug** [comment]
Check out this example - the template is not a declared string in JS.  It is just raw chars pulled from a script tag template.
https://jsfiddle.net/50wL7mdz/271032/

Note the inconsistency by Vue in handling the good vs bad span title.

**Comment by kidplug** [comment]
@posva Are you seeing these comments?
