### ISSUE TITLE
Code-based HTML Entity improperly re-escaped by VUE when in HTML attribute.

### ISSUE THREAD

**Issue by kidplug** [vuejs/vue#7970]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/273361/](https://jsfiddle.net/50wL7mdz/273361/)

### Steps to reproduce
Use unicode-based HTML entities in an HTML attribute (eg title) in the template for a VUE.

### What is expected?
The ampersand character which is the leading character of the entity should NOT be re-escaped when inserted into the DOM.

### What is actually happening?
The leading ampersand character of the code-based HTML entity IS being re-escaped when being put into the DOM.

---
This is the same issue I reported on 7969 but it got closed.

**Comment by kidplug** [comment]
This example uses a script text/template as the HTML source, and puts it into the DOM using non-VUE direct insert and also using Vue.  The title on the resulting element in the DOM from VUE is corrupted but it's fine on the plain insert.

**Comment by posva** [comment]
As I said in #7969 it's not the same. Vue doesn't set the HTML like that (using `innerHTML`) is set it using `setAttribute` because you are setting `title`, and doing so in vanilla js yields the same result: https://jsfiddle.net/w85Lvwa6/

**Comment by kidplug** [comment]
@posva Your example is not comparable to Vue - see:
https://jsfiddle.net/w85Lvwa6/3/

**Comment by kidplug** [comment]
@posva You need to seek a second opinion on this one.

**Comment by kidplug** [comment]
@posva Also maybe you're looking at the problem at the wrong level / wrong step.
Perhaps the problem is how Vue is interpreting the characters from the template, not in how its being set into the DOM.

**Comment by kidplug** [comment]
@posva Look at this example:
https://jsfiddle.net/50wL7mdz/275739/

See how 4 of the entities ( lt, gt, quot, amp ) are rendered properly by Vue, but apos and the code-based entities are not. 

I think when parsing the template, perhaps Vue is only looking for those 4 named HTML entities inside attributes.

**Comment by kidplug** [comment]
@posva Aha - look at Vue source line: 8780
function decodeAttr 
and var decodingMap.  It only includes the four named entities plus (ironically) newline and tab.
But then there's a var:  shouldDecodeNewLines with some logic that is passing false when parsing the attribute value.

This whole approach of using the decodingMap is limited and naive.  ANY HTML Entity is valid inside an HTML attribute.

Maybe I should submit a new bug for the decodeAttr() function itself... ?

**Comment by qgates** [comment]
Is there any workaround to this without resorting to JS? Just stumbled on this trying to set newlines in the title attribute on a component template.

**Comment by mdr1384** [comment]
Me too - I need a newline (conditionally) in the title attribute...

**Comment by vladislav-ladicky** [comment]
Maybe this example helps:
<lang-switch-item lang="fr" :title="`Fran\u00E7aise`" />

**Comment by chessydk** [comment]
> @posva Aha - look at Vue source line: 8780
> function decodeAttr
> and var decodingMap. It only includes the four named entities plus (ironically) newline and tab.
> But then there's a var: shouldDecodeNewLines with some logic that is passing false when parsing the attribute value.
> 
> This whole approach of using the decodingMap is limited and naive. ANY HTML Entity is valid inside an HTML attribute.
> 
> Maybe I should submit a new bug for the decodeAttr() function itself... ?

Hi @kidplug - did you ever get to submit that bug ? I too think it's a bug that should be fixed. Apparently not too many affected by it, though...

**Comment by twogood** [comment]
Thank you @kidplug for raising this issue and #7994. Thank you @chessydk for the wonderful workaround :)
