### ISSUE TITLE
prop of component, in conditionally rendered slot, stops being reactive

### ISSUE THREAD

**Issue by honeroku** [vuejs/vue#7975]
### Version
2.5.14+

### Reproduction link
[https://jsfiddle.net/cLdbL2t2/22/](https://jsfiddle.net/cLdbL2t2/22/)

### Steps to reproduce
Clicking "update message" button adds dots after message.
Once "alter" button is clicked, the message is no longer updated.

### What is expected?
Updating message continues working even after slot is altered.

### What is actually happening?
Prop value stops being reactive, without error nor warning.

---
This behavior takes place after v2.5.14  including v2.5.17-beta.0.
Any version 2.5.13 and lower works as expected.

Unit test can be found in my github https://github.com/honeroku/vue-slot-investigate

I am understanding this is edge case and refactoring structure to avoid placing identical slot in conditional positions resolves my problem.
However, this behavior was not occurring in older versions and suddenly changed without error or warning,
so I am considering this is a bug and reporting to let you know.

**Comment by ustbhuangyi** [comment]
I have tried to find the difference between v2.5.13 and v2.5.14, finally find these commits  [956756b](https://github.com/vuejs/vue/commit/956756b1be7084daf8b6afb92ac0da7c24cde2a5#diff-5b337525bf69cfea5590728194e8d92f) may cause this bug.

**Comment by emanuelmutschlechner** [comment]
I think the problem here is that you have the same slot twice in your template. I modified your jsfiddle to show that conditional rendering of slots works as expected.

https://jsfiddle.net/5kcdcpr6/2/

Note: only the last slot is working

**Comment by sodatea** [comment]
As a workaround, you can attach the slot attribute to a `template` element instead of `div`.
