### ISSUE TITLE
Memory and node count increase when showing and hiding with v-if

### ISSUE THREAD

**Issue by timbarclay** [vuejs/vue#7976]
### Version
2.5.13

### Reproduction link
[https://codepen.io/timbarclay/pen/WzamJy](https://codepen.io/timbarclay/pen/WzamJy)

### Steps to reproduce
The link is to a codepen of a very simple Vue app that simply contains a button that shows/hides a basic component based on a boolean data property.
Open Chrome dev tools, go to the performance tab, tick the Memory checkbox and then click record.
Toggle the button a number of times and then stop recording.

### What is expected?
I would expect the Nodes count to rise when the component is shown and fall again when it is hidden, or potentially to rise the first time it is shown but then stay there.

### What is actually happening?
The Nodes, Listeners and JS Heap counts all rise each time the component is shown and don't go down.

---
Perhaps I shouldn't expect browsers to clear up nodes/heap objects/listeners straight away to prevent too much GC churn, but in my production app, I have a form that gets shown/hidden like this that seems to increase the Node count by a little over 13,000 every time it's opened, and I haven't yet seen it go down. Hopefully, I'm misinterpreting what I'm looking at, in which case I would be glad of the reassurance.

**Comment by posva** [comment]
Unfortunately, this is not something Vue can do anything about because the garbage collection is fully automatic and non-accessible in js land (except in debug builds). When forcing the garbage collection in the devtools, everything looks fine
