### ISSUE TITLE
Compilation of mustaches in mustaches expression doesn't work

### ISSUE THREAD

**Issue by xmeta** [vuejs/vue#7989]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/9bzw21no/33/](https://jsfiddle.net/9bzw21no/33/)

### Steps to reproduce
1. Use a string literal containing `}}` in the data binding

```html
{{ 'hello}}' + '{{world' }}
```

### What is expected?
`hello}}{{world`

### What is actually happening?
`hello)+""+_s(world`

---
I expected the same result as svelte.

- [svelte example](https://svelte.technology/repl?version=1.60.2&gist=35cef4e8c0ff85c17f948b5f4146b1f0)

**Comment by fnlctrl** [comment]
Please don't open duplicate issues. It's not an obligation for framework X to support the same behavior as framework Y.

**Comment by posva** [comment]
You can also use `v-text` or escape codes ('\x7b\x7b', '\x7d\x7d')

**Comment by xmeta** [comment]
I'm very disappointed

**Comment by yyx990803** [comment]
Just use `{{ '\}\}' }}`...

**Comment by carueda** [comment]
ha, allow me to express my surprise here, too. `'hello}}' + '{{world'` is a perfectly valid expression, just a string concatenation!  How come what looks like mustaches inside a string triggers bad parsing in the engine!  Don't get me wrong, I am and really hope to continue to be very a happy vue.js user, but couldn't help adding my 0.02 here.  Keep up the great work team.
