### ISSUE TITLE
V-if sets data when using '=' instead of '=='

### ISSUE THREAD

**Issue by wrrrn** [vuejs/vue#7992]
### Version
2.5.16

### Reproduction link
[https://gist.github.com/wrrrn/a1b6e4c25eed7bf2780f4d63bb9bdc82](https://gist.github.com/wrrrn/a1b6e4c25eed7bf2780f4d63bb9bdc82)

### Steps to reproduce
Open the console and click the 'select' dropdown.

### What is expected?
The `v-if` block will render only if `filter` is 1.

### What is actually happening?
You can see the `watch` will fire twice, once with the initial data you expected, then the `v-if` will reset the data to whatever it started out as (in this case: 1). 

---
I'm aware not using `==` or `===` is bad practice, but I also think it's odd that having a `v-if` statement set data within a template.

¯\_(ツ)_/¯

**Comment by posva** [comment]
Tried on a fiddle and couldn't repro: http://jsfiddle.net/dypjfng0/
Please, next time provide an actual repro on a fiddle (or similar)

**Comment by wrrrn** [comment]
Sorry about that. This is what I'm referring to:
http://jsfiddle.net/p2aqy0hg/

**Comment by sirlancelot** [comment]
That's a typo. It's exactly the same as if you were to try this inside JavaScript: `if (filter = 1) {}`. A linter will be able to catch this for you.
