### ISSUE TITLE
Access context in <script> tag of single file functional components

### ISSUE THREAD

**Issue by strychnide** [vuejs/vue#7995]
### What problem does this feature solve?
Currently, AFAIK, there is no way to access the context in SFC templates while using functional components.

### What does the proposed API look like?
I don't have any good idea, the simplest one I can think of is:
```javascript
export default (context) => {
    // component
} 
```
but I guess it would require an internal redesign of some sort

**Comment by posva** [comment]
You already have access to every property of the `context`: https://vue-loader.vuejs.org/en/features/functional.html

**Comment by strychnide** [comment]
yeah, I know I can access them in the <template>, I was talking about the <script> block, or am I missing something?

**Comment by posva** [comment]
you have access to the context in the render function but in that case, you cannot write a template

**Comment by strychnide** [comment]
yeah, I knew that as well, I was thinking it might be useful to access context in the script tag to (for example) access the vuex store while using SSR
if you don't deem it useful enough to be worth an issue I'll just close the conversation here, otherwise I can try a PR when I get a bit of spare time

**Comment by yyx990803** [comment]
If you need full JavaScript access... better off just use a render function.
