### ISSUE TITLE
Labeling a root instance

### ISSUE THREAD

**Issue by victornpb** [vuejs/vue#7998]
### What problem does this feature solve?
My app doesn't use vue as a base for the project, it is a backbone project, so I this backbone view create instances of vue views inside it and handles the lifecycle of the vue instance. But this means I have a lot of `<root>` instances which makes debugging a challenge. So what I want is a way to make `new Vue({ label: 'root-foo', ... })` or something like that so I can identify them.

### What does the proposed API look like?
```js
new Vue({
   name: 'root-bar', //or label or instanceName etc...
   // (...)
})

```

**Comment by yyx990803** [comment]
This should be a feature request to the devtools, not core.

**Comment by victornpb** [comment]
But the logs also show all user intatiated views as root, shouldn’t it just have a name just like any component?

**Comment by victornpb** [comment]
Idk exactly when this got implemented but I just checked and it is working 🎉

**Comment by victornpb** [comment]
You can close this issue now!
