### ISSUE TITLE
touchstart event will be executed twice when use breakpoint and debugger in chrome devlop

### ISSUE THREAD

**Issue by chnliquan** [vuejs/vue#8001]
### Version
2.5.16

### Reproduction link
[https://github.com/chnliquan/blog/blob/master/index.html](https://github.com/chnliquan/blog/blob/master/index.html)

### Steps to reproduce
open the chrome develop useing the mobile mode and click the 'touchstart' then notice the console

### What is expected?
‘touchstart’ should be printed once whether useing breakpoint and debugger

### What is actually happening?
Use breakpoints and debugg will print 'touchstart' twice and the program will stop at the second log and it will not stop for the first time

only print once when use breakpoint and debugging is not used

**Comment by posva** [comment]
This is not related to Vue as it happens without Vue as well:

```js
    document.querySelector('#app > div').addEventListener('touchstart', () => {
      console.count('touchstart')
      debugger
    })
```

It's probably a chrome bug, you should report it there 🙂
