### ISSUE TITLE
vue.js   android keyboard - the last typed word is missing on the model

### ISSUE THREAD

**Issue by MosheL** [vuejs/vue#8007]
### Version
2.5.16

### Reproduction link
[https://jsbin.com/hufopezumu](https://jsbin.com/hufopezumu)

### Steps to reproduce
I was tried  an Android keyboard with autosuggest enabled.
the  `input`  JS event isn't fired  when  I am typing. it  fired on space, blur or a click on the suggested word.

### What is expected?
model == input.value

### What is actually happening?
it did not updated.

---
workaround:

https://stackoverflow.com/questions/49791906/vue-js-android-keyboard-the-last-typed-word-is-missing-on-the-model

**Comment by posva** [comment]
This is a problem coming from the keyboard not emitting events, although I think it is intented. As you can imagine we cannot implement such workaround in Vue core, it would have a terrible impact
If you need it, you can still do the workaround (with a bigger delay) in that specific input
