### ISSUE TITLE
Using v-if/v-else on two v-model'ed select elements mixing value and :value in their option sets produces incorrect option values.

### ISSUE THREAD

**Issue by foxxyz** [vuejs/vue#8009]
### Version
2.5.17-beta.0

### Reproduction link
[https://jsfiddle.net/eywraw8t/33427/](https://jsfiddle.net/eywraw8t/33427/)

### Steps to reproduce
Click the `Toggle Field` button twice.

### What is expected?
The first `select` element should show with the "Left" value selected. Also, the current value of `bar` should remain `left`.

### What is actually happening?
The first `select` element shows no selected item and the value of `bar` has changed to an empty value.

---
If one looks at the values that are set when selecting a new value of `bar`, two of the three option values are now incorrectly taken from the `foo` select.

This bug seems to only happen when one `select` sets `option` values using the `value` attribute while another select sets `option` values using value binding with `:value` (or `v-bind:value`).

It also only happens if *both* `select` elements have `v-model` set.

**Comment by sqal** [comment]
Adding `key` to select elements (or just one of them) fixes the issue -> https://jsfiddle.net/x1zrkrhx/

https://vuejs.org/v2/guide/list.html#key

**Comment by yyx990803** [comment]
Use keys.
