### ISSUE TITLE
Deletion of elements using custom directives causes elements to not display properly

### ISSUE THREAD

**Issue by ddsomav8** [vuejs/vue#8011]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/h0y03tyf/7/](https://jsfiddle.net/h0y03tyf/7/)

### Steps to reproduce
````
// html 
<div id="app">
  <template v-if="isEdit">
    <button key="edit" v-has="1">修改</button>
  </template>
  <template v-else>
    <!-- <button key="other" v-has="1">其他</button> -->
    <button v-has="0" key="add">新增</button>
    <button key="back" v-has="1">返回</button>
  </template>
</div>

// js
directives: {
  has: {
    inserted (el, binding) {
        if (binding.value === 0) {
          el.parentNode.removeChild(el)
        }
      }
    }
  },

  mounted () {
  	setTimeout(() => {
    	   this.isEdit = !this.isEdit
       }, 2000)
  }    
````

### What is expected?
Normal display after status changes

### What is actually happening?
Cannot display normally after the status changes

---
When I cancel the above comment, the modify button can be displayed normally,

**Comment by ddsomav8** [comment]
This is probably the reason for the vnode update mechanism. Since I deleted the element and its parentNode was null, I could not successfully insert.

I made the following changes to my code, it shows normally

````
  <div v-if="isEdit" key="edit">
    <button v-has="1">修改</button>
  </div>
  <div v-else key="add">
    <!-- <button key="other" v-has="1">Qit</button> -->
    <button v-has="0">新增</button>
    <button v-has="1">返回</button>
  </div>
````

**Comment by posva** [comment]
Generally, it is a bad idea to remove elements in a directive where Vue also have the control.
In your specific example, it's basically a `v-if`
