### ISSUE TITLE
Component's `data` property must be function restriction

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vue#8012]
### What problem does this feature solve?
Take off this restriction would increase the consistency.

I understand that every component needs a copy of the `data` object.
But can't you just copy the `data` object under the hood? Are there any benefits by using a function instead?

### What does the proposed API look like?
```js
Vue.component('foo', {
    data: {
        foo: 'bar'
    }
});
```

**Comment by posva** [comment]
This is a technical restriction due to javascript

**Comment by posva** [comment]
It's because in js objects are references, please, ask questions on the forums or discord server 🙂

**Comment by fnlctrl** [comment]
> But can't you just copy the data object under the hood? Are there any benefits by using a function instead?
Deep cloning objects (copy the data object under the hood) causes 1). heavy performance overhead 2). bloated code for a deep clone implementation. So it's better to just use a function to create a fresh object every time.

**Comment by jacekkarczmarczyk** [comment]
`Object.assign` is not deep

**Comment by huanggm** [comment]
Why not Vue.component auto wrap data from object to function for us?
