### ISSUE TITLE
[Bug Report] Bug with animation

### ISSUE THREAD

**Issue by cawa-93** [vuejs/vue#8014]
### Version
2.5.16

### Reproduction link
[https://codepen.io/cawa-93/pen/XEwzQa](https://codepen.io/cawa-93/pen/XEwzQa)

### Steps to reproduce
Create `<transition-group>` and `unshift` items  to it

### What is expected?
The top element appears with the animation

### What is actually happening?
The top element appears without animation. Instead, the bottom element reappears with the animation

**Comment by KaelWD** [comment]
This isn't a bug, you're using the index as a key.

**Comment by cawa-93** [comment]
@KaelWD Hahaha! A few hours of life was lost because of such a trifle. Thanks
