### ISSUE TITLE
v-for directive inconsistency in Local and Production environment using Chrome

### ISSUE THREAD

**Issue by jeiman** [vuejs/vue#8018]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/utvmv87g/1/](https://jsfiddle.net/utvmv87g/1/)

### Steps to reproduce
1. Create a simple table.
2. Create a http request to retrieve a collection of data. I used `superagent` to do so.
3. Utilise the `v-for` directive to loop through that data on a table row.
4. You should not see any data being rendered, but the request is there (Chrome Tools > Network).

### What is expected?
`v-for` to render the collection of data

### What is actually happening?
Can't seem to render a collection of data using the `v-for` directive. The collection of data is coming from a http request. It works completely fine on my local machine but not on a production environment

---
Ran into this bug while deploying my application to a production environment. Seems to be happening on Chrome. I'm currently on the latest, 65.0.3325.181.

**Comment by TimotheeJeannin** [comment]
I get the following errors when I try your jsfiddle:
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at Vue.loadUsers ((index):77)
    at invoker (vue.js:2029)
    at HTMLAnchorElement.fn._withTask.fn._withTask (vue.js:1828)
```
Would be nice if you would fix it. :)

**Comment by TimotheeJeannin** [comment]
Also, in your line `this.users = data;`, `this` refers to the current `function`, not the current Vue instance.
Instead of 
```javascript
loadUsers: function() {
      this.$http.get('http://jsonplaceholder.typicode.com/users', function(data, status, request){
        if(status == 200)
        {
          this.users = data;
        }
      });
    }
```
you should write 
```javascript
loadUsers: function() {
      var self = this;
      this.$http.get('http://jsonplaceholder.typicode.com/users', function(data, status, request){
        if(status == 200)
        {
          self.users = data;
        }
      });
    }
```

**Comment by posva** [comment]
as @TimotheeJeannin said, you need to use an arrow function so `this` is valid

**Comment by jeiman** [comment]
My apologies @TimotheeJeannin @posva I am fairly new to Vuejs, so it's still a learning curve for me. My problem is not actually with the arrow function, it's actually with the `v-for` directive not rendering the data from my function that it utilising the `superagent` module to make a http request.

Just curious to know why it works in my local, but not in a production environment. I am doing something wrong ? Would love some insights on this.
