### ISSUE TITLE
Wrong style at an element

### ISSUE THREAD

**Issue by martin-badin** [vuejs/vue#8020]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/300834/](https://jsfiddle.net/50wL7mdz/300834/)

### Steps to reproduce
1. Add at some element the style as on the example { width: '203.672px' } or some other
2. Inspect this element
3. Chrome print this value as 203,672px with comma, not dot and as warning - see reproduction

### What is expected?
Expected is value with dot, not comma.

### What is actually happening?
The dot is transformed at comma

**Comment by yaodingyd** [comment]
This may be a chromium bug. [Preact had a similar issue before.](https://github.com/developit/preact/issues/1056)

**Comment by posva** [comment]
It works fine on my end. Closing as it looks very similar to what @yaodingyd shared
