### ISSUE TITLE
v-model has a bug in ie11

### ISSUE THREAD

**Issue by littlegrayss** [vuejs/vue#8026]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/301910/](https://jsfiddle.net/50wL7mdz/301910/)

### Steps to reproduce
run it in ie11, it will have a bug, it can't show correctly.

### What is expected?
can add a tips or warn or add .trim() ?

### What is actually happening?
Because the text in <option></option> has a space. But in other  browser  is correct, so I think it is a bug.

**Comment by posva** [comment]
The repro doesn't run on ie because of the function shorthand in objects but once that's fixed it runs properly on IE

**Comment by jimshell** [comment]
I can confirm that the whitespace in the options has `this.arr[this.time]` return `undefined` in IE11, whereas it  just works fine in Chrome for instance.
As @littlegrayss ask: should it be considered a bug and be handled by Vue?

Thank you

**Comment by fnlctrl** [comment]
It's the white space in `<option>` tag not being removed when used as option value
![image](https://user-images.githubusercontent.com/5557143/38930363-4385794e-4342-11e8-815c-ebd7152a8178.png)
Can't say if it's desirable for vue to enforce trimming the white space in `<option>` tag, so it's better to just not include it in the first place.
