### ISSUE TITLE
建议为数组添加一个 $apply 方法

### ISSUE THREAD

**Issue by acccco** [vuejs/vue#8031]
### What problem does this feature solve?
对数组进行操作的时候直接改索引值不是响应式的，就会造成大量的使用 $set 或是数组下变异的方法。
所以我想在数组下添加一个可以触发更新的方法
所以在 `src/observe/array.js` 中添加了一个方法
```
arrayMethods.$apply = function () {
    this.__ob__.observeArray(this)
    this.__ob__.dep.notify()
}
```
[具体的代码](https://github.com/acccco/aVue/blob/master/demo/step6/array.mjs)

测试代码在同目录的 test.mjs 中。

这样做会重新 observe 整个数组，但可以多次改变，一次更新，而不是一次更改一个更新（$set）

### What does the proposed API look like?
this.array.$apply()

**Comment by Justineo** [comment]
与其每次修改完都要记得 `$apply`，为什么不在每次改变的时候直接处理呢？由于暂时还无法可靠地利用 `Proxy`，所以我觉得简单记住“不允许直接用索引操作数组”对开发者来说心智负担更小，而不是“每次操作完不要忘记 `$apply`”。

> 就会造成大量的使用 $set 或是数组下变异的方法

这么做的问题是什么呢？使用 `push` 等操作具有更明确的语义，我反而觉得是更值得使用的方式。

**Comment by acccco** [comment]
嗯嗯，只是一个建议，就是直接改变数组索引的值方便的时候的一种处理吧。

比如开发的时候用数组存几个状态，数组内存的是一系列的 0 和 1，每个状态可能绑定一个 class 先显示与否。

而一次变动可能会改变多个状态，比如 [0,0,0,0,0] => [0,1,0,1,1]

显然用数组下的方法来实现会比较困难，直接修改索引对应的内容来的方便

而且如果用 $set 像上面这个例子需要调用3次 $set 触发3次视图的更新

当然也可以从新赋值，但修改不是在一个步骤里面，而在多个步骤里面，那么还是会触发3次视图的更新。

所以为什么不把这些变动一次给修改好，仅仅触发一次更新呢？

当然这样手动的去触发与其他的修改方式风格不一致，但是多一个选择，我觉得还是挺好的。

**Comment by yyx990803** [comment]
视图更新是异步的... 多次调用 $set 并不会造成额外的更新。

**Comment by acccco** [comment]
只是一个例子，好吧 视图更新是异步的，但 $set 还是会调用多次 Dep#notify 这个是肯定的。
而且不是讨论 $set 的，仅仅是想为数组对象添加一个 $apply 的方法，实现也就两行代码，方便直接修改数组索引值的情况下实现视图的更新，我觉得这种场景肯定是有的，可能例子举的不太对。

**Comment by Justineo** [comment]
Vue 的机制就是这样的，不然你改成手动 notify 的脏检查得了……

**Comment by yyx990803** [comment]
现阶段 Vue 的一个原则是除非有重大意义否则不添加新的 API。

**Comment by acccco** [comment]
嗯 只是个建议~
