### ISSUE TITLE
there is no clipping info for given tab

### ISSUE THREAD

**Issue by ddcouples** [vuejs/vue#8040]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
some compute(Win7 chrome 65.0.3325.181 or Ubuntu 16.04 chrome 64) will throw this question if they use vue@2.4.4 above! 
this error show this:
commons.js:1 Channel: Error in handleResponse {errorMessage: "There is no clipping info for given tab"}
log @ commons.js:1

### What is expected?
why show errorMessage: "There is no clipping info for given tab"
commons.js:1 Channel: Error in handleResponse {errorMessage: "There is no clipping info for given tab"}
log @ commons.js:1
loggers.forEach.n @ commons.js:1
invokeLoggers @ commons.js:1
error @ commons.js:1
_handleResponsePromise @ commons.js:1
_handleDispatchResponse @ commons.js:1
_handleMessage @ commons.js:1
_listener @ commons.js:1
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
messageListener @ VM1631 extensions::messaging:240
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnMessage @ VM1631 extensions::messaging:392
commons.js:1 Channel: Error in handleResponse {errorMessage: "There is no clipping info for given tab"}
log @ commons.js:1
loggers.forEach.n @ commons.js:1
invokeLoggers @ commons.js:1
error @ commons.js:1
_handleResponsePromise @ commons.js:1
_handleDispatchResponse @ commons.js:1
_handleMessage @ commons.js:1
_listener @ commons.js:1
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
messageListener @ VM1631 extensions::messaging:240
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnMessage @ VM1631 extensions::messaging:392
2commons.js:1 Uncaught (in promise) Error: There is no clipping info for given tab
    at E._handleResponsePromise (commons.js:1)
    at E._handleDispatchResponse (commons.js:1)
    at E._handleMessage (commons.js:1)
    at _listener (commons.js:1)
    at EventImpl.dispatchToListener (VM1471 extensions::event_bindings:403)
    at Event.publicClassPrototype.(/anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (VM1471 extensions::event_bindings:387)
    at EventImpl.dispatch (VM1471 extensions::event_bindings:409)
    at Event.publicClassPrototype.(/anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (VM1478 extensions::messaging:240)

### What is actually happening?
how to prevent this error?

**Comment by posva** [comment]
Please, follow the issue reporting guidelines
You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by sncer** [comment]
It's raised by Evernote Web Clipper, disable this extension will make chrome get rid of this error.
