### ISSUE TITLE
Binding. arg can not get the correct instruction parameters.

### ISSUE THREAD

**Issue by qilvnuanqingyou** [vuejs/vue#8045]
### Version
2.5.17-beta.0

### Reproduction link
[https://jsfiddle.net/qilvnuanqingyou/eywraw8t/46984/](https://jsfiddle.net/qilvnuanqingyou/eywraw8t/46984/)

### Steps to reproduce
The results have been printed out.

### What is expected?
goNext

### What is actually happening?
gonext

**Comment by posva** [comment]
This is an HTML limitation. Always use kebab-case attribute names to make sure your code works on DOM templates and vue SFC
