### ISSUE TITLE
Prop sanitization

### ISSUE THREAD

**Issue by e2o** [vuejs/vue#8049]
### What problem does this feature solve?
It would be an extensions of the props API that would allow us to sanitize a given value for a property **before** passing it onto the component instance. Right now there is no real way of doing this before the value is being set on the component.

### What does the proposed API look like?
This whould work very similarly to how validators for props work, by passing a sanitizer function in the prop definition.

```
Vue.component('my-component', {
  props: {
    title: {
      type: String,
      // Custom sanitization function
      sanitizer: function (value) {
        // The title must not have any leading or trailing whitespace
        return value.trim()
      }
    }
  }
})
```

**Comment by posva** [comment]
This was purposely removed (coerce) because it can be achieved with a computed property.
the sanitizer thing can actually be created as a plugin
You may find this FR to help: https://github.com/vuejs/vue/issues/7943

**Comment by posva** [comment]
I leveraged this behaviour in a small package: https://github.com/posva/vue-coerce-props in case you're interested 🙂
