### ISSUE TITLE
nextTick, use microtask before macrotask in one loop cause all task use microtask

### ISSUE THREAD

**Issue by hudk114** [vuejs/vue#8050]
### Version
2.5.2

### Reproduction link
[https://codepen.io/hudk114/pen/deyJRz?editors=1010](https://codepen.io/hudk114/pen/deyJRz?editors=1010)

### Steps to reproduce
open console

### What is expected?
在nextTick中如果有DOM操作则使用macrotask执行

### What is actually happening?
在同一次eventloop中，在当前task中先定义一个非DOM操作（microtask）再触发一次DOM操作，后者会被microtask而非macrotask执行

---
尤大您好。
刚开始啃源码，看到了https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js里nextTick的实现有些疑问。
注释中写到nextTick采用macrotask是为了处理一些不能像microtask那样优先级过高、执行过快的事件，其中注册的这一段

```
  if (!pending) {
    pending = true
    if (useMacroTask) {
      macroTimerFunc()
    } else {
      microTimerFunc()
    }
  }
```

我的理解是，pending保证了多个nextTick只会注册一个TimerFunc。那么，当macroTimeFunc先被调用时，所有的nextTick都会被推迟到下一个macrotask执行，这是符合文档里所说的DOM更新（我理解是DOM数据更新）完成后再执行的做法的；但是，如果是microTimeFunc先被调用，而在同一个task片内又紧接着调用了一个需要macrotask执行的nextTick（比如DOM操作），那后者也会被microtask执行，就如同demo里给出的那样。
这种情况下，DOM事件还是如同2.4之前那样被microtask执行，是否还会触发原本的问题呢？

在实验中我并没有试出#6566那样microtask在冒泡过程中执行的问题，所以我并不确定在这种情况下使用microtask对DOM操作是否会有影响。
这几天刚开始看源码，恶补了下这块和eventloop的知识，不是很确定我理解的正确。如果理解错了，还请尤大见谅。谢谢！

**Comment by yaodingyd** [comment]
You are programmatically invoke event and under this scenario, event dispatching and possible bubbling all happen synchronously so I think current nextTick implementation is right.

**Comment by sodatea** [comment]
[Jake Archibald: In The Loop - JSConf.Asia 2018](https://youtu.be/cCOL7MC4Pl0?t=1797)

**Comment by hudk114** [comment]
@yaodingyd  @sodatea  I see, thank you guys.
