### ISSUE TITLE
props验证出现错误，

### ISSUE THREAD

**Issue by xdw898618984** [vuejs/vue#8058]
### Version
2.5.14

### Reproduction link
[https://github.com/vuejs/vue/issues/new](https://github.com/vuejs/vue/issues/new)

### Steps to reproduce
  子组件： props:{
        dataInput: {
            type:Array,
            required: true
        }

    },

     父组件：  <three-input :dataInput='datas'></three-input>
报vue.esm.js?efeb:591 [Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Number, got Array.

### What is expected?
格式传递不正确

### What is actually happening?
格式传输错误

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
