### ISSUE TITLE
$refs are not correct when changed list order

### ISSUE THREAD

**Issue by dolymood** [vuejs/vue#8059]
### Version
2.5.17-beta.0

### Reproduction link
[https://codesandbox.io/s/m7q5pmyy1x](https://codesandbox.io/s/m7q5pmyy1x)

### Steps to reproduce
1. click `show one by one` button three times
2. click `Switch a & b` 
3. click `show one by one` button

### What is expected?
Show `b` first

### What is actually happening?
Show `b2` first

**Comment by posva** [comment]
Duplicated of #4952
