### ISSUE TITLE
Summernote 0.8.8 doesn't work on created's event on Vue.js

### ISSUE THREAD

**Issue by martinrios95** [vuejs/vue#8060]
### Version
2.5.16

### Reproduction link
[https://github.com/summernote/summernote/issues/2597](https://github.com/summernote/summernote/issues/2597)

### Steps to reproduce
1. Instantiate Summernote's element inside `created` event **on Vue.js**
2. Write text inside Summernote, you'll see the issue: Summernote's doesn't work on that area.
3. And, instantiate Summernote's element on console. You'll watch how a new Summernote is created again.

### What is expected?
To create a Summernote instance without issues.

### What is actually happening?
Summernote's doesn't work on that area created by created's method. If you instantiate Summernote's element on console, you'll watch how a new Summernote element is created again.

---
Am I thinking that Summernote doesn't work with Virtual DOM or I'm wrong?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by martinrios95** [comment]
I wrote this issue to make sure that this problem is or is not a bug. I'd asked IRC chats, Discord, Ventrilo, TS... But nobody answered me... So, I put this issue. By the way, thanks, somebody helped me with this issue.

**Comment by posva** [comment]
Glad you found the problem 🙂 
FYI, when reporting issues you have to make sure to provide a boiled down repro with no external dependencies as the problem can come from it
