### ISSUE TITLE
Properties not updating in realtime

### ISSUE THREAD

**Issue by vadi2** [vuejs/vue#8061]
### Version
2.5.17-beta.0

### Reproduction link
[https://transfer.sh/5SD7i/repo.tar.gz, https://transfer.sh/4TiwZ/nictiz.tgz, and https://transfer.sh/4QtUv/hl7.core.tgz](https://transfer.sh/5SD7i/repo.tar.gz, https://transfer.sh/4TiwZ/nictiz.tgz, and https://transfer.sh/4QtUv/hl7.core.tgz)

### Steps to reproduce
Unpack repo.tar.tz
yarn
yarn run dev
ctrl o
import either of the tarballs

### What is expected?
Profiles counter is updated in realtime as the files are processed

### What is actually happening?
Profiles counter only updates after all of the files are processed. If a smaller tarball is given, the updates seem to work realtime OK.

**Comment by posva** [comment]
Please, provide a repro using a jsfiddle http://jsfiddle.net/posva/wsr78d2w/ or a github repository, but make sure to provide a boiled down reproduction. I cannot download a file like that for security reasons. Closing until a valid repro is provided

**Comment by vadi2** [comment]
Okay, here is the boiled down reproduction in a github repository as requested: https://github.com/vuejs/vue/issues/8062
