### ISSUE TITLE
Property updates slow down significantly during lifetime of application

### ISSUE THREAD

**Issue by vadi2** [vuejs/vue#8062]
### Version
2.5.17-beta.0

### Reproduction link
[https://github.com/vadi2/vue-lagging-demo](https://github.com/vadi2/vue-lagging-demo)

### Steps to reproduce
1) yarn
2) yarn run dev
3) Ctrl O
4) Select https://transfer.sh/4QtUv/hl7.core.tgz to import, observe it imports OK the first time
5) Select the same file to import again a few times - observe how the application's performance significantly degrades to an unacceptable level

### What is expected?
Vue application stays as responsive as it is at launch

### What is actually happening?
Vue application slows down significantly to unacceptable levels

---
This variant of the demo already has a lot of workarounds to get Vue to even update the counter in realtime. Without the workarounds, the {{profilesCount}} is simply frozen until the end of the stream.

**Comment by posva** [comment]
That is still too much...
Please, take the time to boil it down to the strict minimum, no electron, no extra file to download. If it's about a leak, the best a simple HTML file.
I think you should use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first and you could find your answer.

**Comment by vadi2** [comment]
I've already had people in Discord look at the issue, they seemed quite
competent, and nobody can see an issue with my code which is a very small
case already.

You're just leading me on and not actually interested in looking at the
problem, happier to close issues than resolve them.

**Comment by posva** [comment]
If I wasn't interested in looking at the problem I wouldn't have asked you a smaller repro.
We have asked for smaller repros for repros that were way smaller than yours.
Your repro contains electron, 7 components, a router, a store with one module and, on top of that, you ask us to download an extra `tar.gz` file. **That is HUGE**, even more for a leak/speed issue

You are just looking for someone else to fix your problem (for free). **When people want to help an open source project, they spend the time to boil down the issue**, I see the difference very clearly every week.
On top of that, your attitude is clearly showing you are not willing to help as you're personally attacking me. That is not something we can tolerate...

**Comment by blake-newman** [comment]
Please also removes the current version you are using is a beta. Which clearly explained in release notes, that it could cause issues. 

If you were to supply some performance profile information, and some much simplier situation to reproduce it could be dealt with. Most likely this is not even a Vue issue. As I can forsee it is going to be a garbage collection issue, where your update cycle is blocked by GC.
