### ISSUE TITLE
input v-model on computed property with getter and setter

### ISSUE THREAD

**Issue by pourquoi** [vuejs/vue#8068]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/wmqj3est/14/](https://jsfiddle.net/wmqj3est/14/)

### Steps to reproduce
using the jsfiddle link
type some text in both inputs

### What is expected?
the vue instance data "_text" property should be updated on both inputs

### What is actually happening?
only this first input is working when using this.$data._text inside the setter

when using this._text the data is not updated

---

**Comment by posva** [comment]
This is expected, please see https://vuejs.org/v2/api/#data

**Comment by pourquoi** [comment]
thanks

> Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property
