### ISSUE TITLE
Access template in child level

### ISSUE THREAD

**Issue by eagle-design** [vuejs/vue#8069]
### Version
2.5.7

### Reproduction link
[https://jsfiddle.net/Eagle_Design/6ay0207u/](https://jsfiddle.net/Eagle_Design/6ay0207u/)

### Steps to reproduce
i want two show my custom template in List.vue 
i have did it with 2 layer but now i have triple 

my layout is here
```
<user> <listview> <list> ..

user:
<listview>
    <template slot-scope="props" slot='actions'>
        something
    </template>
</listview>


listview:
<list>
    <slot></slot>
</list>

list:
<slot name="actions"></slot>
```
### What is expected?
a way two show in third html tag

### What is actually happening?
Nothing is showing

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to correctly pass slots: https://jsfiddle.net/7fx3qfd0/

**Comment by eagle-design** [comment]
Oops and thanks about that
But, my listview is global and 
I don't want to set name in listview
