### ISSUE TITLE
v-html won't work for <template>

### ISSUE THREAD

**Issue by ycmjason** [vuejs/vue#8070]
### Version
2.5.17-beta.0

### Reproduction link
[https://codesandbox.io/s/2pq2knk470](https://codesandbox.io/s/2pq2knk470)

### Steps to reproduce
Use `<template v-html="content"></template>`

### What is expected?
`<template>` is replaced by the value evaluated from `content`

### What is actually happening?
nothing is replaced

---
Not sure if this is intentional?

**Comment by posva** [comment]
`v-html` works by setting `innerHTML` on an element, therefore, it cannot work with `template` because it doesn't produce any element
