### ISSUE TITLE
instance method do not work on functional component... i.e Can't use vue-i18n inside

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue#8074]
### What problem does this feature solve?
currently I can't use vue-i18n in functional components... 

```html
<div class="banner_dl columns">
          <a
            class="banner_dl_btn column is-narrow"
            href=""
            target="_blank"
            rel="noopener noreferrer">
            <img src="http://placehold.it/218x64" :alt="$t('buttons.download_android')">
          </a>
          <a
            class="banner_dl_btn column is-narrow"
            href=""
            target="_blank"
            rel="noopener noreferrer">
            <img src="http://placehold.it/218x64" :alt="$t('buttons.download_ios')">
          </a>
</div>
```

### What does the proposed API look like?
there's no API for that, it just have to work out-of-the-box

**Comment by yyx990803** [comment]
Use parent.$t

**Comment by kazupon** [comment]
@darkylmnx
Sorry vue-i18n poor documentation. 🙇
I will add about it later.

**Comment by darkylmnx** [comment]
@kazupon no prob, thanks

**Comment by darkylmnx** [comment]
@yyx990803 I'm not sure if I should open another issue for this so I'm asking here : 
Since functional components have no instance, is it possibile to use local components or we should absolutely defined components globally with `Vue.component` - this isn't said in the docs either.
