### ISSUE TITLE
different behavior between this['key'] and $data['key'] for v-model?

### ISSUE THREAD

**Issue by cj1205** [vuejs/vue#8080]
### Version
2.5.16

### Reproduction link
[https://stackoverflow.com/questions/50008446/what-are-the-differences-between-thiskey-and-datakey-for-v-model](https://stackoverflow.com/questions/50008446/what-are-the-differences-between-thiskey-and-datakey-for-v-model)

### Steps to reproduce
type in something in third input whose v-model="this['test 1']", then you will find this['test 1'] will not be updated.

### What is expected?
the behavior should be same as the second input whose v-model="$data['test 1']", when users type in something, the data property='test 1' will be updated.

### What is actually happening?
the data property='test 1' will not be updated

**Comment by posva** [comment]
You cannot use `this` in templates, it doesn't refer to the vue instance.

**Comment by cj1205** [comment]
but why `<h2>Name:<span>{{this['test 1']}}</span></h2>` get correct initial value?

**Comment by posva** [comment]
not sure, but don't use `this` in templates to access data

**Comment by yyx990803** [comment]
`this` will change in the compiled template depending on the function scope you are in.

**Comment by cj1205** [comment]
@yyx990803 
ohhh, palm my face. 
You are correct... I checked the source codes at [Vue GitHub for model.js](https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js), value will be converted to like one code to run, so context keyword=# this will be be changed at there.
