### ISSUE TITLE
Route switching increases memory consume

### ISSUE THREAD

**Issue by guarah** [vuejs/vue#8081]
### Version
2.5.13

### Reproduction link
[https://github.com/guarah/memory-leak](https://github.com/guarah/memory-leak)

### Steps to reproduce
1 - yarn install
2 - yarn serve
3 - select a main route
4 - switch multiple times between child routes
5 - check the memory consume

### What is expected?
Increasing memory when switching routes

### What is actually happening?
When switching between child routes multiple times, the memory consume increases a lot.

---
In our company we have an app with this basic setup, loading a few cards in kanban placed in child routes.
When switching from one kanban to another, the memory increases and take so long to decrease. 
Apparently the route components keeps in cache. Is there some way to destroy theese components?

**Comment by LinusBorg** [comment]
Why didn't you post this in the vue-router repository?

**Comment by posva** [comment]
Please, don't create duplicate issues and leave both open
