### ISSUE TITLE
Utilize Vue reactivity as a MobX like data store

### ISSUE THREAD

**Issue by jhoffner** [vuejs/vue#8082]
### What problem does this feature solve?
Its possible to simply use an unmounted Vue instance as a reactive store, however it inherits the view related functionality. Why not make a way to create a non-ui Vue instance? 

I personally haven't been able to understand why Vue (reactivity) makes so much sense for a view layer, and MobX (reactivity) makes so much sense for a store layer, yet Mobx is typically used on React (not reactive), and Vuex (reactive, but vastly different design when Mobx is so similar to Vue) is used for Vue. The mismatch creates a loss of symmetry when there seems to be a clear path towards a unified reactive view   store system. Not just unified in that they use the same framework, but unified in that they are matching concepts with matching APIs. 

As it is, you can use Mobx with Vue, but then you are dealing with two different reactive APIs, which again kills the symmetry and consistency.

I do get that a store layer is out of scope of Vue, which is meant to be a view layer - however if it was possible to create a clean non-ui Vue instance then it creates a base object which can be expanded on in a separate project.

### What does the proposed API look like?
```javascript
new Vue({
  ui: false,
  data: {}
});

// or optionally, create a lower level object which is used both by Vue instances internally and by a store
new VData({
 data: {}
});
```

**Comment by TonyPythoneer** [comment]
I don't understand this issue. Vue is able to do as same as MobX. You can just use Vue with hidden UI to control sub-components. I think it can work like your description.

**Comment by jhoffner** [comment]
Yeah after doing some testing (i've been evaluating a bunch of different frameworks and store combinations), its now not clear why someone would really even need MobX at all - since you could just set the store on a vue instance as a data/prop and it would become reactive. 

The very existence of the vue-mobx repo made this a bit more confusing. I'm closing. 

However one thing to note, maybe eventually providing a demo of Vue (by itself) vs React + Mobx would help clarify just how far the scope of Vue can really be.

**Comment by leopiccionia** [comment]
You can use Vue as a non-UI instance; it's actually the whole idea behind the [global bus](https://alligator.io/vuejs/global-event-bus/) pattern (or anti-pattern?).

By the way, a Vuex store is, actually, a wrapped Vue instance (see [here](https://github.com/vuejs/vuex/issues/849) for details), the wrapper providing some extra features.
