### ISSUE TITLE
properties used by the nested component is not omitted

### ISSUE THREAD

**Issue by kvet** [vuejs/vue#8083]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/f1mabd1s/1/](https://jsfiddle.net/f1mabd1s/1/)

### Steps to reproduce
Open the attached link and check generated HTML. You will find something similar to:

```
<div id="app"><div>
      Default component:
      <div><div style="text-decoration: underline;">
    	value
    </div></div>

      Custom component:
      <div><div prop="value" style="text-decoration: underline; color: red;">
    	value
    </div></div></div></div>
```

Note the there is following markup in the custom component: `prop="value"`.

### What is expected?
The Grid with a custom Cell component should be rendered without the `prop` HTML attribute.

### What is actually happening?
Redundant property `prop` is rendered.

---
We are working on a [Vue Grid](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-vue-grid) and want to provide users with great customization capabilities. But we run into a problem with bloated markup when creating high order components that extend the default components.

**Comment by posva** [comment]
This is expected, non-props are bound as attributes (it's actually a feature)
In your scenario, you can use a computed property to return an object adapted to the component, that should solve the problem 🙂

**Comment by kvet** [comment]
I am afraid that your answer is not completely clear.

I can't omit the property for a custom component as it will be passed to the component used within (look at the MyCell component implementation). Maybe I didn't understand your idea correctly?
