### ISSUE TITLE
While listening to blur events and Keyup enter events for input, when I trigger keyup enter events, the blur events also be triggered

### ISSUE THREAD

**Issue by essencemike** [vuejs/vue#8088]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/Lnqpqogb/1/](https://jsfiddle.net/Lnqpqogb/1/)

### Steps to reproduce
1. click the new tag button.
2. input something.
3. press return.
4. open the chrome devtools, you can see output 2 times the number 1.

### What is expected?
1. when I press return, only execute the kekup enter function.
2. when the focus is lost, only execute the loses focus function.

### What is actually happening?
1. when I press return, both execute the keyup enter function and the loses focus function.
2. when the focus is lost, only execute the loses focus function.

**Comment by LinusBorg** [comment]
The blur event is triggered because the input is removed when your `v-if` condition becomes "false". That's normal browser behaviour, Vue has nothing to do with it.
