### ISSUE TITLE
Defining variables containing other data seem to be a proxy to the original

### ISSUE THREAD

**Issue by dannysmc95** [vuejs/vue#8090]
### Version
2.5.13

### Reproduction link
[http://git.dannysmc.com/snippets/61](http://git.dannysmc.com/snippets/61)
https://dannysmc.com/vuejs-issue.html

### Steps to reproduce
Just go to the link, put it into a html file and load it in a browser, then look at the content, currently it is true or false (which is correct), then click save and you will see all the true and false switch to 1 or 0 respectively, even though I am not directly setting it.

### What is expected?
It should just update the data variable and not affect the someData, it should only update the data and that is it.

### What is actually happening?
It seems to be proxying the someData through the data variable, therefore you're unable to take variables from vue's data object and change them in a new variable, because they proxy back to the original place. 

---
I could be wrong and this could be expected behaviour in my eyes, these seems wrong, as that doesn't make sense as to why that happens. I have tested on 2.5.16 as well and the same happens. If this is not expected can this be fixed and why does it happen? and if it is expected, how do you create a separate variable containing the contents of a variable from the vue's data object?

I noticed it because I am using this issue within something I am building for my company as we are making extensive use of Vue for many reasons, but what I was doing is when I have a lot of data, I was preparing it and setting it to the correct values for the database before sending it up (using vue-resource) but when I try and prepare the data and update it, it was breaking the page because of this problem.

On looking I can see that me assigning the data like that means that the variable I assign the data to becomes an observer, but is there no way to not do this?

**Comment by pandemm** [comment]
This is a feature of JavaScript not related to Vue. Both variables have the same reference for the same object. Look up deep clone to solve the problem

**Comment by posva** [comment]
You're setting it in the `doSave` method. As @pandemm said, it's about references in javascript 🙂
