### ISSUE TITLE
Upgrade version of dependency to selenium-server

### ISSUE THREAD

**Issue by fsobanski** [vuejs/vue#8092]
### What problem does this feature solve?
Currently, the version of the dependency to selenium-server is ^2.53.1 as defined in package.json. Could you upgrade it to 3.x.x? I am asking because that dependency causes a version conflict in our application and breaks our tests. 

### What does the proposed API look like?
The Api of vue would stay the same.

**Comment by posva** [comment]
selenium is a devDependency, our version cannot affect yours
