### ISSUE TITLE
Render SIngle-File Components Without Wrapper Boilerplate

### ISSUE THREAD

**Issue by deckar01** [vuejs/vue#8094]
### What problem does this feature solve?
Each single-file Vue component that I treat as an "entry point" for rendering in the DOM requires a boilerplate script to bootstrap it:

```js
import Vue from 'vue';
import App from './app.vue';

export const view = new Vue({
  el: '#app',
  render: h => h(App),
});
```

This seems unnecessary, but there doesn't currently seem to be a way to compile a component as a self-rendering entry point.

### What does the proposed API look like?
```vue
<template>...</template>

<script>
  ...
  export default {
    el: '#app',
    ...
  }
</script>

...
```

Adding `el` would indicate that the component is meant to include its pre-compiled template into the DOM and initialize as soon as the generated script loads. Currently, single-file component do not support the `el` attribute.

**Comment by posva** [comment]
The benefits here are quite debatable as you add more things to the main.js file.
In any case this is something to be implemented as a loader or plugin, feel free to create it if you feel it can be useful to more people 🙂

**Comment by deckar01** [comment]
Debatable, but no debate. Thanks.

**Comment by posva** [comment]
As I said, **this is something to be implemented as a loader or plugin**, it cannot be added to Vue core...
Also, we prefer keeping things explicit in Vue.
And please, next time, keep that negativity away when opening and commenting because it's not appreciated
