### ISSUE TITLE
Feature Request - v-switch directive

### ISSUE THREAD

**Issue by chrisbell08** [vuejs/vue#8097]
### What problem does this feature solve?
Syntax sugar on several v-if, v-else-if, v-else-if etc

An example syntax could be: 

    <div class="wrapper" v-switch="headingType">
        <h1 v-case="big">Headline</h1>
        <h2 v-case="small">Headline</h2>
        <h3 v-case="smaller">Headline</h3>
    </div>

To do this in the current setup would be:

    <div class="wrapper">
        <h1 v-if="headingType === 'big'">Headline</h1>
        <h2 v-else-if="headingType === 'small'">Headline</h2>
        <h3 v-else-if="headingType === 'smaller'">Headline</h3>
    </div>

You can see how the switch statement would make the html markup so much cleaner 

### What does the proposed API look like?
    <div class="wrapper" v-switch="headingType">
        <h1 v-case="big">Headline</h1>
        <h2 v-case="small">Headline</h2>
        <h3 v-case="smaller">Headline</h3>
     </div>

**Comment by posva** [comment]
I'm pretty sure we had this feature request already but I couldn't find it...

Since we are in API freeze, I don't think we should add this because it doesn't feel as readable and explicit as v-if/v-else and has all the inconveniences of a switch statement. One of them being a code smell: adding too many if/else is harder than adding as many switch cases, while instead, you could probably refactor your code into multiple functions.

In templates, most of the time we don't have many v-if/v-else, and when you have, it's _sometimes_ easier to write a render function

**Comment by lmiller1990** [comment]
I agree that having a lot of logic inlined in templates like this is generally a code smell, and awkward to test - maybe computed property or method can be used instead.

That said, this feature would (probably) be not too difficult to implement. I had a brief look around but didn't see anything on npm - I'm looking for a small side project,  if you are interest I/we could work on it @chrisbell08 .

**Comment by chrisbell08** [comment]
I really don't have much free time (or the skills I don't think) to do this but i'd be interested just to see how it's done lol 

I think it would be valuable to a lot of people

**Comment by lmiller1990** [comment]
Might try give in a shot this week. There is one downside you need the extra outer div.

Anyway, this might be closed soon, but throw a link up if I come up with anything.

**Comment by chrisbell08** [comment]
Awesome happy to help out in any way I can (Testing etc)

**Comment by chrisbell08** [comment]
any updates?

**Comment by lmiller1990** [comment]
sorry! had a small hack but nothing usable yet, I'll try and get it to a working state this weekend. Thanks for the reminder.

**Comment by chrisbell08** [comment]
cool will give it a try now just in the middle of a perfect use case

**Comment by chrisbell08** [comment]
a v-default would be cool too

**Comment by lmiller1990** [comment]
Lmk how this is going for you, if it seems useful, I can add `v-default` pretty easily.

PS what is your use case?

**Comment by lmiller1990** [comment]
Cool. It this working for you as you expected in your application?

I can add `v-default` pretty easily, probably tonight (within 24h or so).

Maybe can you make an issue on repo, move discussion away from this issue :)

**Comment by jackmellis** [comment]
I was thinking about how I could implement a switch in Vue. My (completely untested) solution is to use components rather than directives:

https://gist.github.com/jackmellis/d3e34c0d9be592dc5ff244ba75bb9786

The benefit here is this doesn't render any additional html. The switch (and cases) are just render functions that bring in their child components.

**Comment by lmiller1990** [comment]
That is pretty neat - your vue-compose library looks cool as well, will check it out. Constantly learning new, neat things about Vue!

Either or works.  I personally think the directive API is a little more readable - that said, I think I'd be just as happy to just write a render function and use the regular `switch` statement from JS.

**Comment by posva** [comment]
Let's close this because we are on API freeze and this won't add enough benefits to be worth adding.
If you happen to have too many if/else conditions, you can refactor the code into multiple components and use a computed property to display only one at once or use a render function where you can either use a function to refactor the `switch` statement (which is also possible to directly write)

**Comment by brianberneker** [comment]
It's a shame I doesn't look like you will be adding this one. It's linguistically canonical, and can be very useful for readability of code.  Thanks out to @lmiller1990 for his implementation though.  At least with his contribution we can opt-in to such a feature by installing his NPM library.  Repo starred!

**Comment by nixxholas** [comment]
Come on guys! This really makes sense tho, for cases when we need to utilise our enums

**Comment by sirlancelot** [comment]
This could probably be done in userland with slots quite easily:

```vue
<!-- File: `v-switch.vue` -->
<script>
export default {
  functional: true,
  props: {
    value: { type: String, required: true }
  },
  render(h, { data, props, scopedSlots }) {
    const { value } = props
    const slotFn = value in scopedSlots ? scopedSlots[value] : scopedSlots.default

    return slotFn ? slotFn(data.attrs) : null
  }
}
</script>
```

Usage as follows:

```vue
<template>
  <div>
    <v-switch :value="headingType">
      <template #big>
        <h1>Headline</h1>
      </template>
      <template #small>
        <h2>Headline</h2>
      </template>
      <template #smaller>
        <h3>Headline</h3>
      </template>
      <!-- Optional: `<template #default></template>` -->
    </v-switch>
  </div>
</template>
```

**Comment by thopiddock** [comment]
> This could probably be done in userland with slots quite easily:
> 
> ```
> 
> <script>
> export default {
>   functional: true,
>   props: {
>     value: { type: [String, Number], required: true }
>   },
>   render(h, { data, props, scopedSlots }) {
>     const { value } = props
>     const slotFn = value in scopedSlots ? scopedSlots[value] : scopedSlots.default
> 
>     return slotFn ? slotFn(data.attrs) : null
>   }
> }
> </script>
> ```
> 
> Usage as follows:
> 
> ```
> <template>
>   <div>
>     <v-switch :value="headingType">
>       <template #big>
>         <h1>Headline</h1>
>       </template>
>       <template #small>
>         <h2>Headline</h2>
>       </template>
>       <template #smaller>
>         <h3>Headline</h3>
>       </template>
>       
>     </v-switch>
>   </div>
> </template>
> ```
> 
> Biggest benefit here over other solutions is that usage of the new `v-slot` syntax means only the selected case gets rendered vs. rendering all cases and discarding or hiding non-matched.

This works perfectly! Thank you.

**Comment by ThaDaVos** [comment]
@sirlancelot any idea on how to pass on the event listeners attached to the component?
For example:
```html
<v-switch :value="'a'" @click="doSomething" >
...cases
</v-switch>
```

**Comment by sirlancelot** [comment]
> @sirlancelot any idea on how to pass on the event listeners attached to the component?
> For example:
> 
> ```
> <v-switch :value="'a'" @click="doSomething" >
> ...cases
> </v-switch>
> ```

The `v-switch` component doesn't actually render a real DOM node on its own, so there's nothing to attach an event to, and since slots can be composed of multiple top-level nodes, it just wouldn't work. Instead, attach the your events to the node(s) within each slot.

**Comment by Papooch** [comment]
Here's the code for Vue 3

```html
<script>
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'VSwitch',
    props: {
        value: { type: [String, Number], required: true },
    },
    setup: (props, {attrs, slots}) => () => {
        const slotFn = slots[props.value] ?? slots.default;
        return slotFn ? slotFn(attrs) : null;
    },
});
</script>
```

**Comment by ThaDaVos** [comment]
I've done it as follows in Vue 3 with Typescript:
```html
<script lang="ts">
import {
  SetupContext, h, toRef, defineComponent, PropType,
} from 'vue';

export default defineComponent({
  props: {
    value: {
      type: [String, Number] as PropType<string | number | undefined>,
      default: undefined,
    },
  },
  setup(props, context: SetupContext) {
    const switchValue = toRef(props, 'value');

    const slotFn = switchValue.value && switchValue.value in context.slots
      ? context.slots[switchValue.value]
      : context.slots.default;

    return slotFn ? () => slotFn(context.attrs) : () => h('div', {}, ['']);
  },
});
</script>

```

**Comment by lmiller1990** [comment]
If you prefer a module I made one for npm with the above code (or my version, but very similar): https://www.npmjs.com/package/@lmiller1990/v-switch
