### ISSUE TITLE
GC v-for elements

### ISSUE THREAD

**Issue by SnosMe** [vuejs/vue#8100]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/2w1397zw70](https://codesandbox.io/s/2w1397zw70)

### Steps to reproduce
1. Open [https://2w1397zw70.codesandbox.io/#/gc](https://2w1397zw70.codesandbox.io/#/gc)
2. Open DevTools and watch DOM Nodes
3. Click on the "Add" button (don`t click "Clear")
4. Follow the "Go back" link
5. Collect garbage

### What is expected?
DOM Nodes are GC`ed

### What is actually happening?
Nothing

**Comment by fnlctrl** [comment]
I've just tested and captured an allocation timeline. There are no DOM nodes retained after pressing "Go back", which means they have been correctly GC-ed. 
![image](https://user-images.githubusercontent.com/5557143/39407923-ba102f34-4c00-11e8-9e81-2d3c515ee1e1.png)
Pressing "Collect garbage" won't have any effect if something is already GC-ed.

**Comment by SnosMe** [comment]
Oh, I'm sorry. I blindly trusted the Performance Monitor tab.

I've added @click for the Dummy component. All DOM nodes and JS event listeners were successfuly GC-ed. But this is only visible through taking a snapshot of the memory. It was a good lesson for me 😄 

![](https://user-images.githubusercontent.com/4292308/39408692-c78b8c62-4be2-11e8-9718-d402a8b5dcfa.png)

**Comment by a1ph** [comment]
Hmm... Cannot reproduce the issue. I opened the https://2w1397zw70.codesandbox.io/#/gc page and pressed Add button couple times. Are you sure you don't have other pages in the same renderer process?

![screenshot from 2018-04-30 11-46-46](https://user-images.githubusercontent.com/5192288/39444397-740c073a-4c6c-11e8-9d17-1fec6cc75e43.png)

**Comment by SnosMe** [comment]
@a1ph Here is video (56 s): [https://youtu.be/1-zwBCqAExk](https://youtu.be/1-zwBCqAExk)

> Are you sure you don't have other pages in the same renderer process

It was recorded with one tab open.
