### ISSUE TITLE
Functional component fails depending on the siblings around it

### ISSUE THREAD

**Issue by lykahb** [vuejs/vue#8101]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/lykahb/9grbbt4b/](https://jsfiddle.net/lykahb/9grbbt4b/)

### Steps to reproduce
1. Create a functional component that returns several root nodes
2. Use it with is binding, like `<div is='my-component'>` with no siblings around it
3. Render the template

### What is expected?
Renders correctly

### What is actually happening?
Renders a string "undefined" with no console errors

---
It is interesting that it may render successfully depending on the siblings around it. There are several examples in the link.

**Comment by posva** [comment]
Works using `component` instead of `div` though 🤔
