### ISSUE TITLE
Broken reactivity on class instance array property

### ISSUE THREAD

**Issue by baikunz** [vuejs/vue#8102]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/baikunz/rswxt9u6/2/](https://jsfiddle.net/baikunz/rswxt9u6/2/)

### Steps to reproduce
Wait 5 seconds, first array (the one replaced) is not redrawn, while the mutated array is redrawn

### What is expected?
Both arrays should be redrawn after 5 seconds

### What is actually happening?
Only the mutated array is being redrawn

---
Not sure if this is really a bug or something I'm doing wrong, but there is clearly something here.

**Comment by posva** [comment]
This is expected, in getUsers, it keeps the original value because you return in in a function then replaces the DB users array
