### ISSUE TITLE
Vue not rendering options from array

### ISSUE THREAD

**Issue by ereztdev** [vuejs/vue#8105]
### Version
2.5.2

### Reproduction link
[https://github.com/ereztdev/spoilMe](https://github.com/ereztdev/spoilMe)

### Steps to reproduce
pull my  repo: https://github.com/ereztdev/spoilMe

npm install

npm run dev

when you go to app, the created method is supposed to render the option list in the select element on load.

The backend that sends Vue the payload is a node express server that parses a large 28MB JSON, and sends this payload to the frontend.

You can pull it here so you will have the full stack:
https://github.com/ereztdev/node-express-city-parser

### What is expected?
render the cityNames array ( `$store.getters.cityNames` ) into the options dropdown list  that are coming from my state:

### What is actually happening?
State is populated correctly yet not rendering into options with v-for, no error either.

---
If you want to reproduce with backend, please pull my node repo here:
https://github.com/ereztdev/node-express-city-parser

**Comment by posva** [comment]
You misnamed your getter: `getCityNames` -> `cityNames`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ereztdev** [comment]
@posva Thanks for the reply. I made many changes to debug, so I missed that typo, in anycase, I changed it yet options are still not rendering.. 
http://prntscr.com/jbmocr
Please re-open.

**Comment by posva** [comment]
No sorry, besides from that, a repro cannot contain a full server. If you create a simple codesandbox and maybe fetch the data from the server (so there's no extra setup needed) I'll take a quick look 🙂
