### ISSUE TITLE
async component   loading cannot show

### ISSUE THREAD

**Issue by goodqd** [vuejs/vue#8108]
const AsyncComponent = () => ({
  // 需要加载的组件 (应该是一个 `Promise` 对象)
  component: import('./MyComponent.vue'),
  // 异步组件加载时使用的组件
  loading: LoadingComponent,
  // 加载失败时使用的组件
  error: ErrorComponent,
  // 展示加载时组件的延时时间。默认值是 200 (毫秒)
  delay: 200,
  // 如果提供了超时时间且组件加载也超时了，
  // 则使用加载失败时使用的组件。默认值是：`Infinity`
  timeout: 3000
})

I write a component     LoadingComponent  but not show
我写了一个加载动画组件 但是没有显示

我理解这个异步组件  当去加载的时候  LoadingComponent应该是一个加载的动画 ，他显示的位置应该默认是这个异步组件的位置，但是我写了放上面没有任何反应， 请问是不是我用错了， 有啥参考的写法没

**Comment by konglingwen94** [comment]
同问
