### ISSUE TITLE
Better documentation around array (nested object) reactivity

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue#8111]
### What problem does this feature solve?
A common occurrence within vue is getting a fresh array hot off the api.  I then replace an existing array with the fresh array.
```
data: {
   items: []
},
methods: {
    refresh: function () {
        var newArray = apiCall();
        this.items = newArray; // could use this.$set() as well
    }
}
```
My question is, what are the reactivity implications of replacing an array (or deep object) in vue?  Will this.items remain reactive?  Will this.items be diff'd and take advantage of performance optimizations?  Are the answers to these questions yes only if setters are used?  Does this object swap wipe out any watchers?

Can anyone clarify the expected outcome/offer guidance how to approach this common problem in the best way?

### What does the proposed API look like?
Re-observation of deeply nested objects

**Comment by posva** [comment]
setting the new array like you're doing is fine, I think it's actually in the docs.
Closing as this is a question and you know the rules 😉
