### ISSUE TITLE
Vue.mixin clearing Vue.options.components

### ISSUE THREAD

**Issue by mariolamacchia** [vuejs/vue#8118]
### Version
2.5.16

### Reproduction link
[http://jsbin.com/vegujagawe/1/edit?js,console](http://jsbin.com/vegujagawe/1/edit?js,console)

### Steps to reproduce
- Import Vue
- Register a global component (it will be added to `Vue.options.components`)
- Register any global mixin

### What is expected?
`Vue.options.components` shouldn't change

### What is actually happening?
All the global components registered before the mixins are removed from `Vue.options.components`

**Comment by yyx990803** [comment]
It's still there, just not an own property anymore.
