### ISSUE TITLE
V-for does not working in IE10 @Version 2.5.16: ‘invalid v-for alias “” in expression: v-for=“banner in bannerList”’

### ISSUE THREAD

**Issue by weijuer** [vuejs/vue#8122]
### Version
v2.5.16-v2.5.17-beta.0

### Reproduction link
[https://codepen.io/weijuer/pen/VxWKww](https://codepen.io/weijuer/pen/VxWKww)

### Steps to reproduce
IE10列表展示不了

### What is expected?
正常遍历列表

### What is actually happening?
IE10列表展示不了

---
请用IE10浏览器浏览，而非调试的兼容模式！

**Comment by posva** [comment]
Duplicated of #7946

**Comment by weijuer** [comment]
thx

**Comment by Allen-Wei** [comment]
https://cdn.jsdelivr.net/npm/vue@2.5.15/dist/vue.js    is ok
