### ISSUE TITLE
在Element属性中的转义字符在VUE单文件模板中没有生效

### ISSUE THREAD

**Issue by jackframework** [vuejs/vue#8123]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/jackframework/pn6jk62c/1/](https://jsfiddle.net/jackframework/pn6jk62c/1/)

### Steps to reproduce
在“VUE单文件组件”的template中插入带转义字符的属性 &lt;span content="&amp;#x41;"&gt;&lt;/span&gt;

### What is expected?
content 属性应该被转义成Unicode字符A

### What is actually happening?
content 属性被原样输出成了未转义的字符串

**Comment by fnlctrl** [comment]
见https://github.com/vuejs/vue/issues/7994#issuecomment-380136242
