### ISSUE TITLE
vm.slots.default has unexpected undefined tag vnode

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#8132]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/matiascx/9wmaxg4e/1/](https://jsfiddle.net/matiascx/9wmaxg4e/1/)

### Steps to reproduce
1. register a vue component with slot 
2. in html , the component wrap a named slot and default content
3. the console will show default
4. in the above slots.defaut, there will be un expected undefined tag vnode

### What is expected?
in slots.default, only the div exist. no any other

### What is actually happening?
there is additional undefined tag

---
0: VNode {tag: undefined, data: undefined, children: undefined, text: " ", elm: text, …}asyncFactory: undefinedasyncMeta: undefinedchildren: undefinedcomponentInstance: undefinedcomponentOptions: undefinedcontext: undefineddata: undefinedelm: textfnContext: undefinedfnOptions: undefinedfnScopeId: undefinedisAsyncPlaceholder: falseisCloned: falseisComment: falseisOnce: falseisRootInsert: falseisStatic: falsekey: undefinedns: undefinedparent: undefinedraw: falsetag: undefinedtext: " "child: (...)__proto__: Object1: VNode {tag: "div", data: {…}, children: Array(1), text: undefined, elm: div.default, …}_rendered: truelength: 2__proto__: Array(0)

**Comment by LinusBorg** [comment]
It's an entity text node, essentially preserving white space., I think.

**Comment by KaelWD** [comment]
#5329

**Comment by yyx990803** [comment]
That's expected, whitespace is preserved by default. If you don't want whitespace, filter it yourself or use 'preserveWhitespace: false' in vue-loader options.
