### ISSUE TITLE
Use VueJs as a templating engine to send emails

### ISSUE THREAD

**Issue by slaout** [vuejs/vue#8134]
### What problem does this feature solve?
I have a few VueJS components to show a dashboard.
I would like to reuse the components to send an email with the latest view of the dashboard.
My server-part is using SpringBoot.
For the moment, I'm forced to duplicate the VueJS components into Thymeleaf templates.
So I have to maintain both components and templates.
Would it be possible to achieve that?

### What does the proposed API look like?
I would like to ask a Vue tool to render one or more components by giving them data as parameters.
Either a command-line tool or, better, something that can be compiled in a Java tool or other languages and libraries...

**Comment by yyx990803** [comment]
This is not something we have interest in working on.
