### ISSUE TITLE
Development mode on official vue page

### ISSUE THREAD

**Issue by Fusseldieb** [vuejs/vue#8135]
### Version
2.5.17-beta.0

### Reproduction link
[https://vuejs.org/](https://vuejs.org/)

### Steps to reproduce
1. Open the official vuejs page
2. Press Ctrl Shift I or open Developer Tools on Chrome
3. Look at the logs

### What is expected?
The vuejs page is in a production environment, so the development mode should be disabled.

### What is actually happening?
The page is in development mode and the log states that it should be disabled in production.

---
I found this bug while playing around with the Chrome Development Tool to see how certain vue elements behave when clicking and stuff and that way I discovered this "issue". It isn't crucial, but I think it should be noted.

**Comment by sqal** [comment]
https://github.com/vuejs/vuejs.org/issues/1140
