### ISSUE TITLE
Add ability to access namespaced getters with dot notation

### ISSUE THREAD

**Issue by jmcooper** [vuejs/vue#8137]
### What problem does this feature solve?
When working with a namespaced module (e.g. a users module), you can access items on the user module's state like this: 
`this.$store.state.users.user`

However, you can't access getters in the same way.  This will return an error:
`this.$store.getters.users.newUsers`

Because `getters.users` is undefined. Instead you have to access it with bracket notation: `this.$store.getters['users/newUsers']`

Is there a reason why this isn't possible with getters? It would be nice if we could access namespaced getters in the same way we can with namespaced state.

### What does the proposed API look like?
Given a `users` namespaced module, add the ability to access getters with: `this.$store.getters.users....`

**Comment by posva** [comment]
This is not the right repo but it's something you can achieve on your own using a proxy or a custom plugin.

**Comment by jmcooper** [comment]
Oops, sorry, I should have put this in the vuex repository. @posva, can you elaborate a little more, though, on why you think this should be done as part of custom development instead of being supported natively? The built-in behaviour seems inconsistent.
