### ISSUE TITLE
Can't use compiler in strict mode

### ISSUE THREAD

**Issue by dborstelmann** [vuejs/vue#8145]
### What problem does this feature solve?
We cannot use the compiler in strict mode because it uses the `with` statement.

https://github.com/vuejs/vue/blob/master/src/compiler/codegen/index.js#L47

I have to compile templates in the browser at run time in strict mode.  Anybody have a solution for this?

### What does the proposed API look like?
Change all `with` statements to another solution.

**Comment by yyx990803** [comment]
The compiler works fine in strict mode. Or maybe you mean you have a strict CSP? Either way, you need to provide more information or a reproduction because the in-browser compilation works regardless of strict mode or not.

**Comment by dborstelmann** [comment]
@yyx990803  I posted this issue before seeing https://github.com/vuejs/vue/issues/3832.  That gave me much more clarity, and I did the hack that was suggested there which caused my code to work. However I did not try the new Function syntax, does that make strict mode work?

**Comment by dborstelmann** [comment]
I’m also working in salesforce on the same problem as described above in the other issue.   I am using run-time compilation.  I was getting the error because of the with keyword.   If I add `new Function` around the with keyword to the library will that work? And is there a better practice way to do this?

**Comment by dborstelmann** [comment]
@yyx990803 I changed the library to this:

```
return {
    render: new Function("with(this){ return " + code + "}"),
    staticRenderFns: state.staticRenderFns
  }
```

Salesforce still threw an error saying "Strict mode code may not include a with statement"
