### ISSUE TITLE
Unexpected behavior of "v-else" when used with "v-for" in the same tag.

### ISSUE THREAD

**Issue by Atuna** [vuejs/vue#8147]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/333894/](https://jsfiddle.net/50wL7mdz/333894/)

### Steps to reproduce
Nothing

### What is expected?
Tab 2 which has no directive "v-for", should have only one div.

### What is actually happening?
Tab 2 have three div due to previous "v-for".

**Comment by LinusBorg** [comment]
`v-for` has priority over v-if, so your v-if is wrong 3 times, hence the v-else is rendered 3 times.

See: https://vuejs.org/v2/guide/list.html#v-for-with-v-if

Correct usage: 

https://jsfiddle.net/Linusborg/50wL7mdz/333906/
