### ISSUE TITLE
text-align: justify;当使用这个属性时候，页面渲染出问题了。不能达到自己想要的样式。

### ISSUE THREAD

**Issue by flymie** [vuejs/vue#8148]
<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;title&gt;&lt;/title&gt;
        &lt;script src="https://cdn.jsdelivr.net/npm/vue"&gt;&lt;/script&gt;
        &lt;style type="text/css"&gt;
        	.justify{position: relative;width: 100%;height: 24px;text-align: justify;}
        	.justify .num{width: 24px;height:24px;line-height: 24px;display: inline-block;text-align: center;background: #fff;color: #333;border-radius: 50%;border:1px solid #333;cursor: pointer;transition: all .8s ease-in-out;}
        	.justify:after{content: '';display: inline-block;position: relative;top: -30px;height: 1px;line-height: 0;width: 100%;background: #333;z-index: -5;}
        &lt;/style&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div id="app"&gt;
                这是渲染的：
        	&lt;div class="justify"&gt;
        		&lt;div class="num"&gt;1&lt;/div&gt;
        		&lt;div class="num"&gt;1&lt;/div&gt;
        		&lt;div v-for="(list,index) in num" class="num"&gt;{{list}}&lt;/div&gt;
        		&lt;div class="num"&gt;11&lt;/div&gt;
        	&lt;/div&gt;
                  这是静态的：
    		&lt;div class="justify" style="margin-top: 50px;"&gt;
		  &lt;div class="num"&gt;1&lt;/div&gt;
		  &lt;div class="num"&gt;2&lt;/div&gt;
		  &lt;div class="num"&gt;3&lt;/div&gt;
		  &lt;div class="num"&gt;4&lt;/div&gt;
		  &lt;div class="num"&gt;5&lt;/div&gt;
		&lt;/div&gt;	
        &lt;/div&gt;
    &lt;/body&gt;
    &lt;script&gt;
        var vm = new Vue({
            el: '#app',
            data: {
            	num:[1,2,3,4,5],
            },
        })
    &lt;/script&gt;
&lt;/html&gt;
</pre>

**Comment by triunity** [comment]
我也碰到了这个问题。。。后来放弃了使用justify和inline-block，使用了flex

**Comment by xiak** [comment]
inline-block 之间需要有缝隙的话，必须在HTML中的<div style="inline-block"></div> 后加空格或则回车，而v-for 渲染后 <div>是没有空格和回车的
