### ISSUE TITLE
v-on:click does not work in IE 11

### ISSUE THREAD

**Issue by huukimit** [vuejs/vue#8150]
### Version
2.5.13

### Reproduction link
[https://codepen.io/huukimit/pen/wjyBEv?editors=1111](https://codepen.io/huukimit/pen/wjyBEv?editors=1111)

### Steps to reproduce
```
<a href="#" class="no-decoration-link" v-if="user === null" @click.prevent="showAuthDialog">
            <i class="fa fa-sign-in"></i> Sign In/Sign up
</a>
```
When we click `Signin/Signup` or something like that is using @click, an Auth modal will be displayed. Although It's working fine in other browsers, does not work in IE 11.

All component use @click does not work. :'(

I tried to fix it but I am stuck here. Anyone here help me, please.

### What is expected?
v-on:click will work as well at all

### What is actually happening?
I'm not sure, maybe IE is not supported

**Comment by fnlctrl** [comment]
IE 11 does not support ES6 object property shorthand. Use 
```
showAuthDialog: function () {}
```
instead of 
```
showAuthDialog() {}
```
