### ISSUE TITLE
[Help Needed/Feature Request] Custom Key needed in Vue's Export Default

### ISSUE THREAD

**Issue by IamManchanda** [vuejs/vue#8156]
### Important Note

I don't want this to happen in Vue, I just want to know how can I implement this in my projects.
If this can't be done right now ... Then this is a feature request of **CustomKey**
If this can already happen ... Then Please tell me how I can and happy to close!

---

### What problem does this feature solve?
Keeping things short

I want to duplicate this below stuff 

```js
export default {
  components: {
    ComponentAdam,
    ComponentMadam,
  },
};
```

and make something like this ... 

```js
export default {
  components: {
    ComponentAdam,
    ComponentMadam,
  },
  objects: {
    ObjectSierra,
    ObjectHotel,
    ObjectIndia,
    ObjectEcho,
    ObjectLima,
    ObjectDelta,
  },
};
```

---

### What does the proposed API look like?
Not exactly sure!

**Comment by IamManchanda** [comment]
cc @yyx990803

**Comment by fnlctrl** [comment]
What you need is probably [mixins](https://vuejs.org/v2/guide/mixins.html). If that is not the case, please provide more information about why you need this, what are the possible use cases etc.

**Comment by IamManchanda** [comment]
@fnlctrl I am looking for reply!

**Comment by yyx990803** [comment]
Honestly I find it hard to understand what you are trying to achieve. Custom fields e.g. `foo` can be accessed as `this.$options.foo`. Other than that, please note issues are only for well defined feature requests - if you don't know what you want, discuss it on the forum first.
