### ISSUE TITLE
不能访问 pc版 中文vue官网

### ISSUE THREAD

**Issue by 565784135** [vuejs/vue#8159]
### Version
2.5.17-beta.0

### Reproduction link
[https://cn.vuejs.org/](https://cn.vuejs.org/)

### Steps to reproduce
open url

### What is expected?
人人平等，无歧视

### What is actually happening?
国内外官网样式不一致，刻意给国内开发者增加障碍，对中国人不够友好！！！！
除中文以外的官网都有pc版。

---
中国人没地位啊

**Comment by yyx990803** [comment]
自卑才是没救的。
