### ISSUE TITLE
AJAX method fails in Firefox: fetch() works in created section but not methods section

### ISSUE THREAD

**Issue by andrewhu** [vuejs/vue#8160]
### Version
2.5.16

### Reproduction link
[https://tandonbooks.org/bms](https://tandonbooks.org/bms)

### Steps to reproduce
When I access a link on my site, e.g. https://tandonbooks.org/bms , the fetch call in the created() function works successfully. You can verify this by accessing the link https://api.tandonbooks.org/download_log, scrolling to the bottom and seeing that the value "createdworks" was successfully added. 
If you click on a link on any subpage (disclaimer: clicking on the link downloads a pdf file), you get a NetworkError from Firefox. The request works in Chrome, Safari, and Edge.

My simplified code for the page below (removed non-essential functions): 

```
<template>
  <div>
      <ul v-if="books" class="books">
        <li v-for="b of books">
          <a v-on:click="count">{link content here}</a>
        </li>
      </ul>
  </div>
</template>

<script>
  export default {
    created() {
      fetch('https://api.tandonbooks.org/count/createdworks' )
    },
    methods: {
      count: function(event) { 
        fetch('https://api.tandonbooks.org/count/methodsfails')
      }
    }
  }
</script>
```

### What is expected?
Fetch successfully makes a get request

### What is actually happening?
NetworkError from Firefox

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
