### ISSUE TITLE
how to prune keep-alive cache in my own logic code?

### ISSUE THREAD

**Issue by feifeipan** [vuejs/vue#8161]
### What problem does this feature solve?
I use keep-alive in router-view in such request "/detail/:id"
```
<keep-alive>
      <router-view></router-view>
</keep-alive>
```

there are about 100 different detail ids, and I need to remove the not-recently-used cache when leave the router(beforeRouterLeave)

I found some related issues in git (https://github.com/vuejs/vue/issues/6509) which didn't solve my problem.

By the way, keep-alive max props is good but I need to remove some cache in my own logic code.

### What does the proposed API look like?
vm.$pruneCache(cache)

**Comment by posva** [comment]
Hey, as discussed earlier in #6259 and others issues, this is not what we want to achieve with keep-alive. If what you want is to cache last x component rendered, you can actually create your own component basing yourself in keep-alive source code.
Exposing the `pruneCache` function will actually go against declarativity but in your scenario it looks like using the `max` prop will work
