### ISSUE TITLE
Watcher of hidden component not triggered when becoming visible

### ISSUE THREAD

**Issue by KammererTob** [vuejs/vue#8165]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/b843bmen/1/](https://jsfiddle.net/b843bmen/1/)

### Steps to reproduce
1. Press "Change Property"
2. Press "Show Component"
3. "propToWatch" watcher not triggered

### What is expected?
Watcher of the component should be notified about a changed property after it became visible

### What is actually happening?
The component is not notified about a changed property while it was invisible.

---
I am not sure if this is really a bug or intended behaviour. I understand that a invisible component is not active and is thus not notified while being invisible, but i feel that a component which becomes visible should be informed of changed properties, especially if they now differ from their initial default value (empty String in this example)

**Comment by posva** [comment]
This is intended, check the `immediate` option in the docs, I think that's what you're looking for:

```js
watch: {
	prop: {
		handler () { ...},
		immediate: true
	}
}
```
