### ISSUE TITLE
添加样式后js效果失效

### ISSUE THREAD

**Issue by is-liyiwei** [vuejs/vue#8169]
### Version
2.5.2

### Reproduction link
[https://github.com/is-liyiwei/im-vuer](https://github.com/is-liyiwei/im-vuer)

### Steps to reproduce
im-vuer\src\components\CityPicker\CityPickerItem.vue这个文件里面

3、4、5行上面添加了bug注释，这个是picker组件，但是添加了样式后无法触发js事件了

可以启动这个项目
然后进入http://localhost:8081/#/citypicker
然后在CityPickerItem.vue文件的注释的两个span标签测试下，会发现，添加了style的那个span标签会导致选择事件失效

### What is expected?
添加css样式后不影响js逻辑问题

### What is actually happening?
添加css后js无法触发事件

---
个人思考了很久，实在想不出问题所在，按理说css应该不会影响js的事件的吧，所以只能向vue团队请教了0.0

**Comment by javoski** [comment]
请不要在组件里面手动给 DOM 元素添加事件，而是使用 `v-on` 或者自定义指令

**Comment by is-liyiwei** [comment]
一开始我也考虑过这个问题，觉得操作DOM会和v-on指令冲突，接下来我也尝试下使用v-on去试试，但是在http://localhost:8081/#/picker这个组件中（im-vuer\src\components\Picker\PickerItem.vue）也使用了同样的方法却是没有问题的，所以这点让我无法理解

**Comment by fnlctrl** [comment]
同上，若手动给DOM元素绑定事件，则需要手动在其被销毁重建后重新绑定事件
