### ISSUE TITLE
v-if中的使用key管理可复用元素的疑问

### ISSUE THREAD

**Issue by xhxno36** [vuejs/vue#8170]
### Version
2.5.16

### Reproduction link
[http://jsbin.com/sulifoseba/edit?html,js,output](http://jsbin.com/sulifoseba/edit?html,js,output)

### Steps to reproduce
vue教程中的关于v-if使用key管理可复用元素的疑问（https://cn.vuejs.org/v2/guide/conditional.html#用-key-管理可复用的元素），当使用div包裹template模板里面的label和input之后，vue复用的特性就失效了，想知道是为什么

### What is expected?
能复用

### What is actually happening?
不能复用

---
我的理解，加上div后，实际复用的是div，而不是div里面的label和input，label和input还是需要重新渲染？

**Comment by yibuyisheng** [comment]
个人理解：

复用只会在同级兄弟节点之间发生。template 是特殊的标签，并不会产生新的层级。

**Comment by posva** [comment]
I don't see anything wrong with your repro...
If you want vue to keep using the same element you can use a `key` attribute but even in that case it would just be better to use another data property and bind to both inputs
