### ISSUE TITLE
SVG icons double-painted in latest Firefox (FF60) 

### ISSUE THREAD

**Issue by networkimprov** [vuejs/vue#8172]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eecd7bqd/](https://jsfiddle.net/eecd7bqd/)

### Steps to reproduce
Issue is apparent immediately.

### What is expected?
1 SVG icon

### What is actually happening?
2 SVG icons

---
Seen in FireFox 60 Win7 64bit. Not an issue in FF59.

Vue causes an SVG icon library (UIKit) to double-paint its icons.

**Comment by javoski** [comment]
This is not an issue related to Vue, I guess it is just how the uikit library works and this only happens when using in-DOM HTML template. Check this out - [https://jsfiddle.net/eecd7bqd/1/](https://jsfiddle.net/eecd7bqd/1/)
