### ISSUE TITLE
Chrome - sorting order of array changes after it gets reactive

### ISSUE THREAD

**Issue by janiek** [vuejs/vue#8174]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/kkk5p8n8yr](https://codesandbox.io/s/kkk5p8n8yr)

### Steps to reproduce
Open the sandbox in chrome. The main code is situated in the helloworld.vue.

Checkboxes are sorted by a default order (in this case the size). 
If you check a checkbox, the checked checkbox will appear on top and all the other results are sorted by the default order. 

You will see that the default sorting is interupted when you check a checkbox.

Additional information is logged to the console.

### What is expected?
To make the code work, a clone was mode of the original sorting. To do this cloning we used a json stringify and parsed the json again. (this was tested as well with other methods). 
Then the object gets reactive (getters and setters are added). The sorting order should stay the same.

### What is actually happening?
After this parsing the object gets reactive. Then the sorting order of the array changes in Chrome.

---
in other browsers (mozilla, internet explorer, edge) all works fine.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
I've checked the link and adding a log of the final state of `vm.sortedFacets` after clicking a checkbox. The array's order is correctly reflected in dom.
![image](https://user-images.githubusercontent.com/5557143/39938023-22bf7080-5584-11e8-8e5d-a49a901326c4.png)
So this is not a vue issue here. Please check your implementation.

**Comment by fnlctrl** [comment]
Updated the logging position.  Array order is not changed after it's assigned to vue instance.
![image](https://user-images.githubusercontent.com/5557143/39940742-deb6c2fe-558c-11e8-92fb-2f1b8545e949.png)
https://codesandbox.io/s/xo0wy12vmp
