### ISSUE TITLE
disable slot warning on duplicate presence

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue#8175]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/1jz3wrfc/](https://jsfiddle.net/1jz3wrfc/)

### Steps to reproduce
iterate a slot.

### What is expected?
I want to be able to use a separator slot in a v-for iteration.

### What is actually happening?
[Vue warn]: Duplicate presence of slot "separator"

**Comment by posva** [comment]
When using regular slots Vue reuses them, so the warning is important here.
If you use a scoped-slot, it generates different vnodes each time: https://jsfiddle.net/jnynnqqd/

**Comment by yozman** [comment]
@posva 
it shouldn't be a warning.
sometimes there is just for customize slot template without scope
