### ISSUE TITLE
到底是getter/setter还是访问器属性？？？

### ISSUE THREAD

**Issue by CoffeeandTea** [vuejs/vue#8176]
### Version
2.5.17-beta.0

### Reproduction link
[https://cn.vuejs.org/v2/guide/reactivity.html](https://cn.vuejs.org/v2/guide/reactivity.html)

### Steps to reproduce
只是一个不成熟的小疑问，就是在Vue文档‘深入响应式原理’ 一节中介绍的Vue底层实现原理中那一句 “当你把一个普通的 JavaScript 对象传给 Vue 实例的 data 选项，Vue 将遍历此对象所有的属性，并使用 Object.defineProperty 把这些属性全部转为 getter/setter。”    让我头疼很多天了，这句话想表达的意思是不是“Vue 将遍历此对象所有的（数据）属性，并使用 Object.defineProperty 把这些（数据）属性全部转为 访问器属性？”    getter/setter是访问器属性的两个特性或者说描述吧，除此之外访问器属性还有两个跟数据属性相同的特性：Configurable   Enumerable，    所以属性是属性，属性的特性是属性的特性，二者应该不是等同的吧。说把这些属性全部转为 getter/setter 感觉很莫名其妙怪怪的～

### What is expected?
以上只是我个人的一个不成熟的小疑问，很可能我的理解是有偏差的，如果是你们直接关闭issue就好了，如果Vue真的是把属性通过Object.defineProperty 定义为了访问器属性，希望能在文档中进一步说明一下下，使得像我一样的小白不会思想误入岐途

### What is actually happening?
nothing. everything works perfect !      Vue 最棒！

**Comment by fnlctrl** [comment]
请不要使用issue提问
