### ISSUE TITLE
给dom元素设置过id属性后， 就可以直接以id名的全局变量访问到这个元素 ,而不需要任何获取操作，如getElememtById

### ISSUE THREAD

**Issue by caijian1993** [vuejs/vue#8178]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/caijian/gns0xb0t/](https://jsfiddle.net/caijian/gns0xb0t/)

### Steps to reproduce
列如在app.vue中<div id="demo"></div> , 在所有组件内的mounted周期都可以直接当全局变量一样console.log（demo） , 访问到这个div元素 ，而不需要通过doucment.getElementById ，  不知道这个是bug还是故意为之 

### What is expected?
不知道这个是bug还是故意为之

### What is actually happening?
给过id属性的dom元素 ， 全局都能访问  ， 不需要任何获取操作

**Comment by posva** [comment]
This is a browser feature and has nothing to deal with Vue

**Comment by caijian1993** [comment]
@posva forget what im said , I dont konw that before TT
