### ISSUE TITLE
动态组件生成的js引入路径有问题

### ISSUE THREAD

**Issue by luo772435545** [vuejs/vue#8180]
### Version
2.5.2

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
vue在webpack生成多页面
比如index.html  login.html   products/productDetail.html
在productDetail.html  会存在 动态产生的js路径问题

### What is expected?
在productDetail.html  js路径引入正确

### What is actually happening?
vue在webpack生成多页面
比如index.html  login.html   products/productDetail.html
在productDetail.html  会存在 动态产生的js路径问题

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
