### ISSUE TITLE
export order bug

### ISSUE THREAD

**Issue by wim-put** [vuejs/vue#8181]
### Version
2.5.16

### Reproduction link
[https://github.com/wim-put/minimal-reproduction-vue-export-order-bug](https://github.com/wim-put/minimal-reproduction-vue-export-order-bug)

### Steps to reproduce
clone the project and, 'npm install' and 'npm run serve'

### What is expected?
to render App.vue's template when browsing to the localhost

### What is actually happening?
a warning is thrown, [Vue warn]: Unknown custom element

---
The problem does not occur when you change the order of the 2 exports in '/src/components/index.js', then the page is rendered as expected. I have the feeling there is a loose comparison going on in the background.

**Comment by posva** [comment]
As you import one of the component inside of the other, having the right order makes sense.
In any case, this is not Vue's concern but rather the bundle
