### ISSUE TITLE
Deep object returned by computed is not reactive?

### ISSUE THREAD

**Issue by slimee** [vuejs/vue#8183]
### Version
2.5.16

### Reproduction link
[https://github.com/BlueForestTrees/trees/blob/dev/web/src/main/vue/layout/Compare.vue](https://github.com/BlueForestTrees/trees/blob/dev/web/src/main/vue/layout/Compare.vue)

### Steps to reproduce
Create a component with props and a computed property.
Create a deep object from props values inside the computed property.
Use this object in the template.

### What is expected?
Any changes in the object should be reflected in the template.

### What is actually happening?
No changes

---
Does a computed property is allways fully reactive?

**Comment by phanan** [comment]
I don't think your link qualifies as a "reproduction." Do you have a fiddle of some sort?

**Comment by yyx990803** [comment]
That's expected behavior, computed properties are considered immutable and should never be mutated directly.
