### ISSUE TITLE
[DOCS] Vue CLI for TypeScript already there

### ISSUE THREAD

**Issue by IamManchanda** [vuejs/vue#8186]
### Version
2.5.0

### Reproduction link
[https://vuejs.org/v2/guide/typescript.html](https://vuejs.org/v2/guide/typescript.html)

### Steps to reproduce
`vue create sample` => manually => Check the TypeScript option

### What is expected?
This shouldn't be in docs... Am I missing something?

### What is actually happening?
This is in docs... Actually instead of this below content there should be an how to guide on how to use Vue CLI with TypeScript?

<img width="869" alt="screen shot 2018-05-14 at 7 39 18 pm" src="https://user-images.githubusercontent.com/4970624/40002720-24127982-57af-11e8-996e-a2840cf1a73d.png">

**Comment by yyx990803** [comment]
CLI 3 is not officially released yet, also, the docs has its own repo.

**Comment by IamManchanda** [comment]
@yyx990803 So should I repost this to docs or it isn't required?

**Comment by yyx990803** [comment]
Not required. We will update the docs when CLI 3 is officially released.
