### ISSUE TITLE
one way data flow problem?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [vuejs/vue#8189]
this works
```javascript
props: ['initialCounter'],
data: function () {
  return {
    counter: this.initialCounter
  }
}
```

this does not work
```javascript
props: ['initialCounter'],
data:  () => ({
  return {
    counter: this.initialCounter
  }
})
```

is this expected? I'm not sure about this

**Comment by diego-lipinski-de-castro** [comment]
closing to open other the right way

**Comment by posva** [comment]
@diego-lipinski-de-castro Please don't, you're falling into the fat arrow scope caveat. Search for it or ask in the Discord server, it's a well known JS caveat
