### ISSUE TITLE
one way data flow problem?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [vuejs/vue#8190]
### Version
2.5.16

### Reproduction link
[https://codepen.io/maxorhd/pen/ZoMvaj?editors=1111](https://codepen.io/maxorhd/pen/ZoMvaj?editors=1111)

### Steps to reproduce
pass props to a component and try to recover it as follows

```javascript
props: ['testProps'],
data:  () => ({
    test: this.testProps //test is undefined but testProps is not undefined
})
```

### What is expected?
variable to not be undefined

### What is actually happening?
variable is undefined

---
this works

```javascript
props: ['testProps'],
data: function () {
  return {
    test: this.testProps //test is = this.testProps
  }
}
```

also works
```javascript
props: ['testProps'],
data() {
  return {
    test: this.testProps //test is = this.testProps
  }
}
```

this does not work

```javascript
props: ['testProps'],
data:  () => ({
    props: this.testProps //props is undefined but this.testProps is not undefined
})
```

is this expected? I'm not sure about this

**Comment by fnlctrl** [comment]
> An arrow function expression has a shorter syntax than a function expression and does not have its own this

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by rossta** [comment]
There's a note in the Vue.js docs about this as well.

> Don’t use arrow functions on an options property or callback, such as created: () => console.log(this.a) or vm.$watch('a', newValue => this.myMethod()). Since arrow functions are bound to the parent context, this will not be the Vue instance as you’d expect, often resulting in errors such as Uncaught TypeError: Cannot read property of undefined or Uncaught TypeError: this.myMethod is not a function.

https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks

**Comment by diego-lipinski-de-castro** [comment]
so used to use arrow function that i forgot its basic. Shame, thank you guys

**Comment by sqal** [comment]
@diego-lipinski-de-castro you can use arrow functions in data definition, but you have to access component's data from the first argument passed to the function

```
data: vm => ({
  props: vm.testProps,
})
```

it's also in the docs :P https://vuejs.org/v2/api/#data
