### ISSUE TITLE
Nodes and Listeners don't remove when destroy Vue components by v-if

### ISSUE THREAD

**Issue by kosmos** [vuejs/vue#8195]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/vjkosmos/hbbb28ky/](https://jsfiddle.net/vjkosmos/hbbb28ky/)

### Steps to reproduce
1. Create project by vue cli
2. Change HelloWorld.vue to:
```
<template>
  <div class="hello">
    <button @click="show = !show">Show</button>
    <div v-if="show">
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
      <h2>{{msg}}</h2>
    </div>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',

  data () {
    return {
      show: false,
      msg: 'test',
    }
  },
}
</script>
```
3. Open Chrome Dev Tools > Performance monitor
4. Make fast clicks on button to show\destroy h2-s

### What is expected?
Vue should remove dom nodes

### What is actually happening?
The number of dom nodes increases and vue does not remove them.

---
On real projects it is a big problem. Within seconds you can get tens of thousands of "dom-zombies".

**Comment by posva** [comment]
Cannot check right now, but did you click the collect gc button? That's when they're removed

**Comment by kosmos** [comment]
@posva I don't understand about what button you say, but I have made next tests:

1) With dev tools (in chrome number of dom nodes increase)
2) Production version in chrome in incognito mode (in chrome number of dom nodes increase)
3) Production version in firefox (on memory snapshots you can see memory leaks)

**Comment by maxirozay** [comment]
I tried on firefox and you can see the memory increasing but if you wait a few seconds in goes back to normal which is 11.15/11.16 MB for me.

**Comment by kosmos** [comment]
@maxirozay I have other experience.
https://cdn.discordapp.com/attachments/325477692906536972/446563510093348885/unknown.png

After more then 10 minutes nothing changed.

And on in real app a have no time to wait minutes. For example with pagination you in seconds get +2000 dom nodes on each click and big problem with performance.

**Comment by maxirozay** [comment]
If your browser needs memory it will call the garbage collector directly and you won't need to wait. Maybe your browser is not calling the garbage collector.

I just tried on chrome 61.0.3163.91 (I'm on linux) and the memory doesn't increase like on firefox. The number of node is always 4 and the Vnodes are 6 when the v-show is false and 32 when it's true and the document DOM tree is always at 2340.

Someone else should try or you can try on another latop/OS/browser.

**Comment by kosmos** [comment]
@maxirozay There is no problem with v-show. Problem is with v-if.

**Comment by maxirozay** [comment]
Sorry I meant v-if ^^.

**Comment by posva** [comment]
Tested and this is normal behaviour for a browser. It waits before cleaning up memory

**Comment by yyx990803** [comment]
Look for the button that looks like a trash can... that's what you can use to force GC. Typically the engine won't do a GC unless it has to.
