### ISSUE TITLE
Additional lifecycle options for watchers (helps with SSR)

### ISSUE THREAD

**Issue by arpowers** [vuejs/vue#8196]
### What problem does this feature solve?
Less code, less bugs, improving a commonly faced issue

### What does the proposed API look like?
Background: 
I'm using SSR and frequently use watchers for loading in data in components. However, most of the components don't need to be rendered server-side (as debugging is harder this way and source becomes cluttered for SEO). 

This means we can't use the standard 'immediate: true' option that is already implemented with watchers, as that would initialize things on the server (like the "created" lifecycle hook)

Proposal: 
To solve this problem, I propose an additional 'initialize' option for the watcher API. This would work like the immediate hook, but would allow us to specify the point in the lifecycle when the "immediate" behavior should take place. 

```javascript
watch: {
  value: {
    handler: "setValue", 
    initialize: "mounted"
  }
}
```

**Comment by posva** [comment]
If you need to setup the watcher at a specific point, you can already do `this.$watch` in the lifecycle you want. We prefer not to bloat the API for this
