### ISSUE TITLE
vue中开发环境和生产环境的css前缀问题

### ISSUE THREAD

**Issue by fz-marchen** [vuejs/vue#8197]
`
在APP.vue添加
<style>
#app {
  display: flex;
}
</style>

使用npm run dev 命令后可以在浏览器查看到
<style>
#app {
   display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}
</style>

使用npm run build后,输出如下
<style>
#app {
  display: -ms-flexbox;
  display: flex
}
</style>
在build后会display: -webkit-box;这个前缀没有添加，我尝试过在package.json和.postcssrc.js文件里，使用更早的版本，但是打包出来后这个前缀还是没有添加。
谢谢
`

**Comment by yyx990803** [comment]
你的 package.json 里面的 browserslist 配置决定了这些前缀会不会被移除。
