### ISSUE TITLE
it lead the data can't be rendered in real time while v-for in items is a empty array

### ISSUE THREAD

**Issue by Flcwl** [vuejs/vue#8202]
### Version
2.5.2

### Reproduction link
[https://www.what.mean?](https://www.what.mean? I don't have it)

### Steps to reproduce

` <span v-for="(item, index) in dots" :key="item.id" :class="['dot', {active: currentIndex === index}]">
      </span>
{{currentIndex}}    
`

it lead the data(currentIndex...) can't be rendered in real time while items is a empty array. maybe the :key="item.id" make error.
remove the `:key="item.id" ` is OK.
how I can solve it?

`  data() {
    return {
      dots: [],
      currentIndex: 0
    }
  }, 
  mounted() {
    setTimeout(() => {
      this._initDots();  // length = 5
    }, 20);
  },
  methods: {
    _initDots(){
      this.dots = Array(this.children.length);
      // console.log(this.dots);
    },
}`

### What is expected?
{{currentIndex}} can change in real time
and for can iterate in right way

### What is actually happening?

` <span v-for="(item, index) in dots" :key="item.id" :class="['dot', {active: currentIndex === index}]">
      </span>
{{currentIndex}}    
`

it lead the data(currentIndex...) can't be rendered in real time while items is a empty array. maybe the :key="item.id" make error.
remove the `:key="item.id" ` is OK.
how I can solve it?

`  data() {
    return {
      dots: [],
      currentIndex: 0
    }
  }, 
  mounted() {
    setTimeout(() => {
      this._initDots();  // length = 5
    }, 20);
  },
  methods: {
    _initDots(){
      this.dots = Array(this.children.length);
      // console.log(this.dots);
    },
}`

**Comment by Justineo** [comment]
Reproduction link is essential for bug reports. Thanks.

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
