### ISSUE TITLE
在ie>9时候， 在table中使用templete 失效，怎么解决

### ISSUE THREAD

**Issue by fengxuemiao** [vuejs/vue#8203]
<tbody>
            <template v-for="item in arrList ">
                <tr v-for="(res,index) in item.list" >
                    <td :rowspan="item.list.length" v-if="index==0">{{item.created_name}}</td>
                    <td>{{res.no}}</td>
                    <td>{{res.cpname}}</td>
                    <td>{{res.time_name}}</td>
                    <td>{{res.type}}</td>
                    <td>{{res.speed}}</td>                           
                </tr>
            </template>
        </tbody>

**Comment by javoski** [comment]
[https://cn.vuejs.org/v2/guide/components.html#%E8%A7%A3%E6%9E%90-DOM-%E6%A8%A1%E6%9D%BF%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9](https://cn.vuejs.org/v2/guide/components.html#%E8%A7%A3%E6%9E%90-DOM-%E6%A8%A1%E6%9D%BF%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
