### ISSUE TITLE
Allow <template> block splitting in single-file-components, for organisational/readability purposes. (<template-block> ?)

### ISSUE THREAD

**Issue by hmexx** [vuejs/vue#8205]
### What problem does this feature solve?
I love Vuejs, and .vue SFCs. But occasionally I end up with an HTML template that's extremely large and hard to read. **I'm talking about components where all the sub-parts are tightly coupled and breaking them down into sub-components is not an obvious win**.

I could break them down anyway, but that's considerable amount of work considering the tight coupling. I'll either send a LOT of state down using props, or i'll have to move the state to Vuex, even though I'd prefer to keep that state local to that parent SFC.

A nice solution, would be to just allow something akin to template macros/splitting within Vue. See below for a random syntax example.

### What does the proposed API look like?
```javascript
<template>
    ... 5 lines of html ...
   <step1/>
   <step2/>
</template>

<step1> 
... 30 lines of html ...
</step1>

<step2>
... 40 lines of html...
</step2>

<script></script>
<style></style>
```

Because it's all in one file, and all the templates use the same script and style scope, you can just copy/paste things around, and organise. No props, no imports. It's basically just like macros. If I could have the IDE or an extension do this I wouldn't need for vue to do it.  Code folding has never really worked well for me.

**Comment by posva** [comment]
This is doable via a custom webpack loader but there's not much that can be done in vue actually.
If it's extremely long, you should split into multiple components. This will need to create new props to communicate between subcomponents or even use `$parent` if they're tightly coupled
