### ISSUE TITLE
index.vue template with unpredictable HTML elements

### ISSUE THREAD

**Issue by aebrs** [vuejs/vue#8208]
### What problem does this feature solve?
Hi,
Using vue.js I need to create an index.vue page for product and people, where number of text box and drop down list are not fixed, I mean some product has 5 props other may have 10.
I tried to add all html element using v-html, but it seems not a wise way.
Some offered to use components, it sounds little complicated or confusing.
I am looking for a sample or good example.
Thanks in advance.

### What does the proposed API look like?
I tried to add all html element using v-html, but it seems not a wise way.
Some offered to use components, it sounds little complicated or confusing.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by posva** [comment]
Using components should be fine, you should give the guide a read 😉  https://vuejs.org/guide/
