### ISSUE TITLE
Automatically populate component name from filename

### ISSUE THREAD

**Issue by dylanized** [vuejs/vue#8216]
### What problem does this feature solve?
Sometimes a .vue component doesn't have any script properties except for name. (Consider, for instance, a component that includes global components, or a very simple display-only component).  In this case, the script looks like this:

```
<script>
export default {
  name: 'ComponentName',
};
</script>
```

It would be helpful if this could be removed entirely, and the name be extracted from the component filename.

This would be especially helpful to beginners, who could now create simple components with just a <template> section

### What does the proposed API look like?
If no <script> tag in a .vue file, or no name property set in the script tag, then automatically extract the component's filename and set the name property.

**Comment by posva** [comment]
Keep in mind the name is optional. For devtools we already pick up the name.
This could be added behind a flag to vue-loader (that's where you should open the feature request)
