### ISSUE TITLE
vuejs.org documentation

### ISSUE THREAD

**Issue by larsmars** [vuejs/vue#8218]
### Version
2.5.16

### Reproduction link
[ https://012.vuejs.org/guide/custom-filter.html]( https://012.vuejs.org/guide/custom-filter.html)

### Steps to reproduce
Go to this link:

https://012.vuejs.org/guide/custom-filter.html

This is my top google hit when I search for vue.js custom filter.

### What is expected?
The two way filter guide is not working depricated, should be labeled removed/depricated/replaced and link to solution in documentation

### What is actually happening?
The two way filter guid is not working depricated, should be labeled removed/depricated/replaced and link to solution in documentation

---
The two way filter guid is not working depricated, should be labeled removed/depricated/replaced and link to solution in documentation

**Comment by LinusBorg** [comment]
1. ourt documenttion has its own repository: https://github.com/vuejs/vuejs.org
2. As the url indicates, you are looking at documentation for version 0.12

Feel free to open an issue in the right repository to ask if the team can make the version more appearant in those old docs.

**Comment by larsmars** [comment]
On the link provided, the only thing nearly indicating any version number is the text: _"Looking for 0.11 docs?"_

**Comment by LinusBorg** [comment]
...which is why I suggested you open an issue in the correct repository about this.
