### ISSUE TITLE
vue中photo数组的图片地址没变，源数据改变了，view视图没刷新

### ISSUE THREAD

**Issue by DengRiGuang** [vuejs/vue#8221]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/336166/?utm_source=website&utm_medium=embed&utm_campaign=50wL7mdz](https://jsfiddle.net/50wL7mdz/336166/?utm_source=website&utm_medium=embed&utm_campaign=50wL7mdz)

### Steps to reproduce
photo数组是图片的链接，然后调用更新图片接口，图片地址没变，图片的数据改变了。
updatePhoto() {
      API.template.updatephoto(this.changePhoto).then(res => {
        console.log("update");
        if(res.code===1){
          console.log('1')
          this.$nextTick(function(){
            this.photo.splice(this.tailoring.num, 1, this.userphoto);
            location.reload();
          })
        }else{
          this.uploadPhoto();
        }
      });
    },

### What is expected?
更新图片后，视图能够刷新，而不是要通过location.reload();刷新页面才能显示出来

### What is actually happening?
视图没有刷新要手动刷新才能展示出来

**Comment by Justineo** [comment]
你好，你提供的 reproduction URL 没有完整的功能，所以我们并不能重现你的问题，并无法确认这是 Vue 的 bug 还是你的业务逻辑本身导致的。

**Comment by DengRiGuang** [comment]
@Justineo 这个有点难复原，是这样的，就是数组中图片通过接口替换了那张图片，地址不变，视图看到的还是替换前的图片

**Comment by DengRiGuang** [comment]
@Justineo 拿那个地址在浏览器打开看到的是替换之后的图片

**Comment by Justineo** [comment]
请提供一个最小化的可复现场景，有必要的话对服务端进行 mock。无法复现的问题我们无法在这里给予帮助，谢谢理解。

**Comment by HarshOB** [comment]
Why don't you use English? So, everyone can understand.

**Comment by DengRiGuang** [comment]
@Justineo https://test3.goodinviter.com/uokobo6/#/pages/edit?orderid=152697762544104&type=update

**Comment by DengRiGuang** [comment]
@HarshOB 英语我不太行

**Comment by HOTAO** [comment]
可能是浏览器的缓存导致的。 你可以尝试一下在图片链接后面加上时间戳

**Comment by posva** [comment]
The repro is not working...
