### ISSUE TITLE
.trim modifier for every v-model and value in input like fields of form

### ISSUE THREAD

**Issue by zisuzon** [vuejs/vue#8222]
### What problem does this feature solve?
Our team was working on a project using NUXT and It is in production now. One thing we missed is to trim the input value. We know there is a modifier '.trim' which works with v-model. But in our app we used 'v-model' and in some special cases 'value' attribute of input tag. 

### What does the proposed API look like?
There are so many input fields in various pages and we thought it would be cool if there is an option by which all v-model will automatically trim the input value by-default instead of adding .trim in everywhere manually.

Also a modifier to trim the value attribute.

**Comment by posva** [comment]
You can call trim() on the value before binding it to the attribute value
Having a global trim option is more likely to add very hard to debug bugs and increase Vue size for something is already doable easily
