### ISSUE TITLE
Error in render: "ReferenceError: “sp”未定义"

### ISSUE THREAD

**Issue by windyflying** [vuejs/vue#8224]
##Vue.js version
2.5.16

##Reproduction Link
[codepen](https://codepen.io/windyflying/pen/JvzvRb)

Steps to reproduce
Please open the link in IE11 and inspect the console panel

##What is Expected?
![expected](https://user-images.githubusercontent.com/13942593/40357065-9bcca5ee-5ded-11e8-8043-df9341f15480.png)

##What is actually happening?
![real](https://user-images.githubusercontent.com/13942593/40356053-9ce8120e-5dea-11e8-9392-24d2ef49069f.png)

##More information
It works well in latest Chrome and Firefox and Edge
the generated code snippets:
normal:
![chorme](https://user-images.githubusercontent.com/13942593/40356663-51139e1e-5dec-11e8-9f35-d8ec40f579c0.png)
wrong:
![vue-parser-ie](https://user-images.githubusercontent.com/13942593/40356693-710a9254-5dec-11e8-86e3-fbb75f8772cb.png)

**Comment by Justineo** [comment]
You should use `sp in product.specs`.

**Comment by windyflying** [comment]
@Justineo I have tried.
![tried](https://user-images.githubusercontent.com/13942593/40357652-80840adc-5def-11e8-881e-373a8cde89b1.png)

**Comment by windyflying** [comment]
Please open the issue, thank you

**Comment by Justineo** [comment]
Please follow the instructions in the issue template, thank you.

**Comment by windyflying** [comment]
@Justineo 好的，多谢。我好好看下，太心急了。。。
