### ISSUE TITLE
Vue refs works differently in template vs render function

### ISSUE THREAD

**Issue by adalberth** [vuejs/vue#8225]
### Version
2.5.17-beta.0

### Reproduction link
[https://codepen.io/Stupid/pen/WJmgjm?editors=1010](https://codepen.io/Stupid/pen/WJmgjm?editors=1010)

### Steps to reproduce
Create ref within template and in render function, template returns array, render function returns latest item in loop.

### What is expected?
render functions should return an array of the "refs" (https://vuejs.org/v2/guide/render-function.html#v-if-and-v-for) 

### What is actually happening?
Of course it makes sense that the render function returns the last ref as JS should. But in vue shouldn't it return an array as the template do?

**Comment by sqal** [comment]
You need to add `refInFor` manually to the data object, here:

```
return createElement('li', {
  ref: 'list_a',
  refInFor: true
}, idx)
```

**Comment by adalberth** [comment]
Yep, that works! Thx! Shouldn't that in the docs?

**Comment by Igloczek** [comment]
It's listed at the end of the data object:
https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth
