### ISSUE TITLE
can't define `is` prop to functional component

### ISSUE THREAD

**Issue by yozman** [vuejs/vue#8232]
### Version
2.5.16

### Reproduction link
[https://codepen.io/yozman/pen/JvVygy](https://codepen.io/yozman/pen/JvVygy)

### Steps to reproduce
change `value` prop to `is` in component `Fragment`

### What is expected?
`is` works well like `value`

### What is actually happening?
```sh
[Vue warn]: Failed to mount component: template or render function not defined.
```

---
why `is` is not work? what's the key point?
or could u plz add feature for `{{ }}` can render `Vnode` & `Vnodes` ?

**Comment by posva** [comment]
is is a special attribute used by Vue. Maybe you could add a warning

**Comment by yozman** [comment]
@posva 
why not only special for `<component>`?

**Comment by Justineo** [comment]
@yozman 

`is` on element other than `<component>` is useful to work around limitations of in-DOM templates: https://vuejs.org/v2/api/#is

**Comment by yozman** [comment]
@Justineo

I think my case is different,
`Fragment` is not a `html dom tag`,
it's a functional component

**Comment by LinusBorg** [comment]
It's a reserved word, use something else. 

You want us to only treat it as a keyword if the element that you use it non is not a component. 

This is, to my knowledge, not verifiable reliably during compile time, so we would check during runtime, which is a bad idea.

**Comment by LinusBorg** [comment]
> where is roadmap for vue@3?

there is none yet. We haven'T started working on v3 nor have we finished plans for it.

> there must be a feature to render vnode or vnodes by `{{ $slots.default }}`

> and somecase we use `<slot>` as render function at react to define templates,
but there is an red warning can't use same slot more than once except `slot-scope`
it's should be fixed too

I don't understand what you are trying to say. you have normal slots and scoped slots for templates, , and you can use render functions. What exactly is he feature or functionality that you are missing?

**Comment by yyx990803** [comment]
Anything listed [here](https://vuejs.org/v2/api/#Special-Attributes) are reserved.
