### ISSUE TITLE
vue :style bug

### ISSUE THREAD

**Issue by luohanwen** [vuejs/vue#8234]
### Version
2.5.16

### Reproduction link
[https://codepen.io/haven-luo/pen/gzyexM](https://codepen.io/haven-luo/pen/gzyexM)

### Steps to reproduce
look the codepen html

### What is expected?
<ul :style="{'animationDuration':'1s'}">
渲染结果
<ul style="-webkit-animation-duration:1s">

### What is actually happening?
<ul :style="{'animationDuration':'1s'}">
渲染结果
<ul style="-webkit-animation:1s">

**Comment by Justineo** [comment]
This is not a qualified reproduction. Please provide something real, thanks.
