### ISSUE TITLE
v-text中绑定的多个连续空格无法正常显示

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#8235]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/rl37koz6wo](https://codesandbox.io/s/rl37koz6wo)

### Steps to reproduce
Indented.vue页面中的属性文本内容有多个空格

### What is expected?
连续的空格显示多个

### What is actually happening?
连续的只显示了一个

**Comment by troy351** [comment]
你可以需要学习一下html和css的基础知识
```css
white-space: pre;
```

**Comment by wenye123** [comment]
本来多个空格就只显示一个的。。。如果你要要显示多个，可以使用字符 &nbsp;

**Comment by sumaa007** [comment]
> 你可能需要学习一下html和css的基础知识。[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)
> 
> > normal
> > Sequences of whitespace are collapsed. Newline characters in the source are handled the same as other whitespace. Lines are broken as necessary to fill line boxes.
> 
> ```css
> white-space: pre;
> ```

再加上 white-space: pre-line;完美，万分感谢

**Comment by kybetter** [comment]
建议这样用：
```html
<span class="test" v-html="标&nbsp;&nbsp;&nbsp;&nbsp;题"></span>
```
