### ISSUE TITLE
Reordering elements in array

### ISSUE THREAD

**Issue by Kilgaloon** [vuejs/vue#8239]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/6smnvy7n/](https://jsfiddle.net/6smnvy7n/)

### Steps to reproduce
When fiddle is started console log will show proper order of elements in array.
Clicking on button will change places of those two elements and console log new array.
Items don't move on view, they stay same despite array elements changed places

### What is expected?
Elements need to change places in view

### What is actually happening?
Elements stay on same place in view

**Comment by galiazzi** [comment]
Vue wraps an observed array’s mutation methods so they will also trigger view updates.

https://vuejs.org/v2/guide/list.html#Mutation-Methods

Example: https://jsfiddle.net/6smnvy7n/1/

**Comment by sqal** [comment]
Please read https://vuejs.org/v2/guide/list.html#Caveats

You can also just do `this.media.data.reverse()`

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
