### ISSUE TITLE
:style bug animation-duration属性在需要添加webkit前缀环境中被渲染成了-webkit-animation

### ISSUE THREAD

**Issue by luohanwen** [vuejs/vue#8243]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/haven/k1uptbpw/](https://jsfiddle.net/haven/k1uptbpw/)

### Steps to reproduce
运行在 animation-duration属性需要添加webkit前缀的环境（手机或浏览器），本人是在mumu模拟器（android4.4）中试的

### What is expected?
渲染结果为 -webkit-animation-duration:4s

### What is actually happening?
渲染结果为 -webkit-animation:4s

**Comment by Justineo** [comment]
This seems to be a bug on Chrome's very old versions, like in your case (Android 4.4 was using Chrome 30 as I checked). I tested on Chrome 30 and got this:

![image](https://user-images.githubusercontent.com/1726061/40469007-c1610f00-5f61-11e8-886d-acd352026f44.png)

While on Chrome 42 (the last version that required prefixes for `animation` properties):

![image](https://user-images.githubusercontent.com/1726061/40469111-060f5954-5f62-11e8-9cc6-f9980af375be.png)

So I assume there's nothing we can do on Vue's side.

**Comment by luohanwen** [comment]
@Justineo  got it, thanks！
