### ISSUE TITLE
Add note on `.sync` camelCasing in documentation

### ISSUE THREAD

**Issue by robertjk** [vuejs/vue#8244]
### What problem does this feature solve?
The problem is that the documentation on [Custom Events: Event Names](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names) states:

> we recommend you always use kebab-case for event names.

With `.sync` modifier you must emit event `update:propertyName` with propertyName camelCased. With kebab-case it won't work. So it's not **always**: more like always unless you emit event for `.sync`.

### What does the proposed API look like?
You should add a note about that in [Custom Events: Event Names](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names).

Also in the documentation [Custom Events: `.sync` modifier](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier) I would change the example to use a property with multiple word name (now it's a single word `title`, which doesn't help with this problem) and/or add a note about this event name incosistency with previous recommendation on the same page ("always use kebab case").

**Comment by LinusBorg** [comment]
Sorry, this is still the wrong repository. 

You are looking for this one: 

https://github.com/vuejs/vuejs.org
