### ISSUE TITLE
Issue submission form - preview should open links in a new tab

### ISSUE THREAD

**Issue by shawnheide** [vuejs/vue#8245]
### Version
2.5.16

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
Fill out the form on this page (https://new-issue.vuejs.org/?repo=vuejs/vue). Click on the Preview button. Click on the link inside the preview window. 

### What is expected?
The link opens in a new tab. 

### What is actually happening?
The link opens in the current tab without submitting the issue. Going "back" in the browser results in an empty form. 

---
Sadly, I discovered this the hard way after trying to submit my first issue.

**Comment by ulivz** [comment]
Same to #8246, you should come to [vue-issue-helper](https://github.com/vuejs/vue-issue-helper) to open this issue.

**Comment by shawnheide** [comment]
Yep, thanks again for letting me know. I moved it there now and am closing the issue here.
