### ISSUE TITLE
Issue submission form - changing issue type deletes content

### ISSUE THREAD

**Issue by shawnheide** [vuejs/vue#8246]
### Version
2.5.16

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
Fill out the form on this page (https://new-issue.vuejs.org/?repo=vuejs/vue). Change the type from a Bug Report to a Feature Request. 

### What is expected?
The content in the fields persists. 

### What is actually happening?
The content in the fields is deleted. 

---
This is another small issue, but it really should be more user friendly since you are directing new users here to take the time to submit issues.

**Comment by ulivz** [comment]
It seems that you should come to [vue-issue-helper](https://github.com/vuejs/vue-issue-helper) to open this issue.

**Comment by shawnheide** [comment]
Yep, I wasn't aware of that repo yet. Thanks for letting me know. I moved it there now and am closing the issue here.
