### ISSUE TITLE
Vue SSR hydration error when <noscript> has a nested <img>

### ISSUE THREAD

**Issue by shawnheide** [vuejs/vue#8247]
### Version
2.5.16

### Reproduction link
[https://github.com/shawnheide/vue-hackernews-2.0](https://github.com/shawnheide/vue-hackernews-2.0)

### Steps to reproduce
I forked vue-hackernews-2.0 and added two `<noscript>` elements in [App.vue](https://github.com/shawnheide/vue-hackernews-2.0/blob/master/src/App.vue). One `<noscript>` just has text inside it and the other has a nested `<img>`. If you 'npm install' and 'npm run dev' with javascript enabled, you will see an error occurs in the browser console during hydration for the `<noscript>` element with the nested `<img>`. The `<noscript>` with text doesn't throw an error.

### What is expected?
The hydration process makes an exception for children of `<noscript>` elements, assuming nothing can be done about the server-side rendering of children of `<noscript>` tags (since it appears to be a common browser issue).

### What is actually happening?
The hydration bails early because the server-side `<noscript>` renders its children as a string and the client-side renders the children as an HTML element.

---
The error occurs in the `assertNodeMatch` function in [vue.runtime](https://github.com/vuejs/vue/blob/19552a82a636910f4595937141557305ab5d434e/dist/vue.runtime.esm.js#L6088) since `node.tagName` is undefined due to the fact that it is a string. 

Also, there is no issue when you disable javascript. The text and the image render just fine. Any thoughts or ideas on this are much appreciated. Thanks for your time.

**Comment by yyx990803** [comment]
Don't put `<nosciprt>` in Vue files... Put it in your HTML template.

**Comment by shawnheide** [comment]
Thanks for the quick response Evan, but unfortunately my actual use case doesn't allow me to add it the HTML template since the images are nested in a lower-level component. I've read through a lot of the docs but haven't seen anything on not having `<noscript>` in an SFC, did I miss something? Any chance you'd consider this issue further?

**Comment by shawnheide** [comment]
After looking into vue.runtime a bit more, it actually looks like there is no issue in production. So I guess I'll just deal with it for now, but it would be nice to not have console errors in development. Thanks again.
