### ISSUE TITLE
Allow a component to register its own subComponents

### ISSUE THREAD

**Issue by fjc0k** [vuejs/vue#8249]
### What problem does this feature solve?
When developing a component library, you will encounter the need to register subComponents. For example, the component `List` needs to register subComponents such as `ListItem` and `ListItemBrief`. In Vue, it is often necessary to register the full `List` component:

```js
import { List, ListItem, ListItemBrief } from './components'

Vue.component(List.name, List)
Vue.component(ListItem.name, ListItem)
Vue.component(ListItemBrief.name, ListItemBrief)

// List: <List />
// ListItem: <ListItem />
// ListItemBrief: <ListItemBrief />
```

In React, just:

```js
import { List } from './components'

// List: <List />
// ListItem: <List.Item />
// ListItemBrief: <List.Item.Brief />
```

It seems that Vue's approach is a bit more complicated, so I think it is possible to consider supporting components to register their subComponents.

### What does the proposed API look like?
```js
// List.vue
import ListItem from './ListItem.vue'

export default {
  name: 'List',
  subComponents: {
    Item: ListItem
  }
}
```

```js
// ListItem.vue
import ListItemBrief from './ListItemBrief.vue'

export default {
  name: 'ListItem',
  subComponents: {
    Brief: ListItemBrief
  }
}
```

```js
// main.js
import { List } from './components'

Vue.component(List.name, List)

// or, App.vue
import { List } from './components'

export default {
  name: 'App',
  components: {
    [List.name]: List
  }
}
```

This will register `${List.name}`, `${List.name}Item`, `${List.name}ItemBrief` once.

**Comment by Justineo** [comment]
You can write custom registration logic like this:

```js
function globalRegister ({ name, subComponents }) {
  Object.keys(subComponents).forEach(subName => {
    Vue.component(`${name}${subName}`, subComponents[subName])
  })
}
```

...and use like this:
```js
import { List } from './components'
globalRegister(List)
```

**Comment by fjc0k** [comment]
@Justineo 🌝 This is a good solution for global register, but sometimes we also need component-level register:

```js
// App.vue
import { List } from './components'

export default {
  name: 'App',
  components: {
    List
  }
}
```

Of course, we can make a helper function to extract full components:

```js
// App.vue
import { List } from './components'
import { extractComponents } from './utils'

export default {
  name: 'App',
  components: {
    ...extractComponents(List.name, List)
  }
}
```

But this will import extra codes and increase the cost of use.

**Comment by posva** [comment]
This is achievable in user land with a custom webpack loader or by directly specifying the sub components in the main component and overloading the vue component method and creating a global mixin. Feel free to create a library and reference it here :) . But we prefer to keep the explicit way in core

**Comment by fjc0k** [comment]
@Justineo @posva Thank you. I have published a plugin to implement this feature: https://github.com/fjc0k/vue-component-register
