### ISSUE TITLE
Server side render Maximum call stack size exceeded (vue 2.5.13)

### ISSUE THREAD

**Issue by slevp** [vuejs/vue#8253]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/mmx38qxw/](https://jsfiddle.net/mmx38qxw/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/6696585/40586625-3852fd70-61f7-11e8-89da-be1c178850d0.png)

![image](https://user-images.githubusercontent.com/6696585/40587022-73a946d6-61fc-11e8-9116-e90a991010a2.png)

vue: 2.5.13
element-ui: 2.3.3
nuxt: 1.4.0

I found some related issues（[Maximum call stack size exceeded](https://github.com/vuejs/vue/issues?utf8=%E2%9C%93&q=Maximum call stack size exceeded)）, i restored vue to 2.5.13 but still prudence.

The issue could not be produced with examples or demos on [jsfiddle](https://jsfiddle.net/mmx38qxw/), it will product during 2 days when our production servers restart, so i did not new it on issue-generator(https://elementui.github.io/issue-generator), pls undenstand -, -

### What is expected?
work regular

### What is actually happening?
not work

---
OS / Browser Version： Ubuntu 16.04 / IE9 
UA：Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; Tablet PC 2.0; .NET4.0E)

**Comment by Justineo** [comment]
Issues in this repo also require a valid reproduction link. And I think it's better to report and discuss this issue with Element UI team first.

**Comment by posva** [comment]
What @Justineo said, we need boiled down repros with no external libs te check bugs

**Comment by yyx990803** [comment]
Just looking at this, you probably have some code that is repeatedly calling `Vue.extend` on a component definition on each request. But without a minimal reproduction there's very little we can do.
