### ISSUE TITLE
中文文档在移动端和pc端不一致

### ISSUE THREAD

**Issue by Rockergmail** [vuejs/vue#8260]
### Version
2.5.16

### Reproduction link
[https://cn.vuejs.org/v2/guide/events.html#事件修饰符](https://cn.vuejs.org/v2/guide/events.html#事件修饰符)

### Steps to reproduce
1. pc端访问“事件处理”一章，没有.passive的解析，搜索提示有.passive，但是不能跳转显示
2. 移动端访问“事件处理”一章，有.passive的解析

### What is expected?
pc端和移动端访问“事件处理”一章，都有.passive的解析

### What is actually happening?
我估计是渲染出错了？

**Comment by yyx990803** [comment]
无法重现... 另外中文文档有自己的仓库 https://github.com/vuejs/cn.vuejs.org

**Comment by liyuhang1997** [comment]
https://github.com/vuejs/cn.vuejs.org/commit/abc7d7350340c77ddf075de3db731970d4db71af#diff-ff997e9caf8c34d0b9ecf3bdd9f2539eR176
