### ISSUE TITLE
v-show is not working for functional component

### ISSUE THREAD

**Issue by adoji92** [vuejs/vue#8261]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/3h7c204p/5/](https://jsfiddle.net/3h7c204p/5/)

### Steps to reproduce
simply put v-show="false" at functional component

### What is expected?
component not visible

### What is actually happening?
component still visible

---
wrapping it with additional div is workaround for now.
i guess this is not intended

**Comment by posva** [comment]
with functional components you need to pass down the `context.data` to `createElement`:
```js
  render: function(createElement, context) {
    console.log('Rendering Foo')
    return createElement({
      template: context.props.foo
    }, context.data)
```

**Comment by adoji92** [comment]
@posva Thank you for your answer
but, actually i used only `<template functaionl>`  and doesn't have render function in my code
so is this vue-loader related problem?

**Comment by posva** [comment]
yes

**Comment by atilacamurca** [comment]
Workaround: use `v-if` instead of `v-show`.

**Comment by smilingkite** [comment]
I use v-if in combination with the <keep-alive> component as a replacement for v-show - especially when there are potentially many of these components on the page.
