### ISSUE TITLE
v-bind doesn't work will with style

### ISSUE THREAD

**Issue by misakamaiyako** [vuejs/vue#8262]
### Version
2.5.17-beta.0

### Reproduction link
[http://jsbin.com/gireyuh/edit?html,js,output](http://jsbin.com/gireyuh/edit?html,js,output)

### Steps to reproduce
init vue

### What is expected?
the div will have a background image

### What is actually happening?
it doesn't;and the attribute disappeared

**Comment by Justineo** [comment]
You can't have parenthesis in your `url(...)` expression in CSS, it's just not a valid CSS property value and this has nothing to do with Vue.

**Comment by misakamaiyako** [comment]
thx, i missed it
