### ISSUE TITLE
Allow override of props validation when merging a mixin

### ISSUE THREAD

**Issue by wwwd3v** [vuejs/vue#8263]
### What problem does this feature solve?
Hi, 

in a mixin I have specified:
```
props: {
  value: {
    type: String,
    default: '',
  },
}
```

Then, in my component, I have tried to override it:
```
props: {
  value: {
    type: Boolean,
    default: false,
  },
}
```

However, that results in an error: `Invalid prop: type check failed for prop "value". Expected String, got Boolean.`

Is this a bug, and if not, do you think it would be a useful feature?

Thanks. I have a case when 90% of my components take a string value, but some need an override (different text inputs all take a string value, but checkboxes are true/false).

### What does the proposed API look like?
(keep the same API)

**Comment by posva** [comment]
Please provide a repro when reporting a bug

**Comment by javoski** [comment]
It works as normal according to my [test](https://jsfiddle.net/4n3y29we/), maybe you need to provide more info

**Comment by posva** [comment]
Closing until more info is provided
