### ISSUE TITLE
ios 9.3系统 数组下标重复问题

### ISSUE THREAD

**Issue by OSpoon** [vuejs/vue#8264]
### Version
2.4.2

### Reproduction link
[mitphone.sunlife-everbright.com:8010/com.ifp.ipartner/proposalShare/index.html?from=singlemessage&isappinstalled=0#/policy/electronics_share/672fb93da19e4cfa8366fe23a262e8c6/M110162485588088/24/-1/-1](mitphone.sunlife-everbright.com:8010/com.ifp.ipartner/proposalShare/index.html?from=singlemessage&isappinstalled=0#/policy/electronics_share/672fb93da19e4cfa8366fe23a262e8c6/M110162485588088/24/-1/-1)

### Steps to reproduce
现在程序中大约有2000个for循环,暂时还没总结出哪种写法存在问题,是否已有解决方案?可以便捷处理的方案?

### What is expected?
正常显示

### What is actually happening?
数据重复

**Comment by Justineo** [comment]
The reproduction is far beyond minimal. Sorry we can't locate the problem with a reproduction like this.
