### ISSUE TITLE
not work chenges params when change route 

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue#8268]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/L7hscd8h/9531/](http://jsfiddle.net/L7hscd8h/9531/)

### Steps to reproduce
delete {{$route.params.id}} in template

### What is expected?
Not works alerts when you click on buttons

### What is actually happening?
nothing

---
if I add {{$route.params.id}} in template, routes works, but if delete this string router not work

**Comment by ariran5** [comment]
on click url changed but params not changed if they are not in the template

**Comment by sqal** [comment]
Everything works fine here. $route object is reactive, which means when you change the route, `this.$route`  changes and this results in an update of the template -> updated hook is called. When you remove reactive property from the template (`{{ $route.params.id }}`) and change the route, then you don't update any reactive data that would update the template.  To fix this you can simply watch for changes of `$route` object and then update your article data -> http://jsfiddle.net/dbcosqpv/

**Comment by posva** [comment]
thanks @sqal !
