### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by b781rev** [vuejs/vue#8270]
### Version
2.5.16

### Reproduction link
[http://na.na](http://na.na)

### Steps to reproduce
npm run dev

### What is expected?
A compiled project.

### What is actually happening?
ERROR  Failed to compile with 1 errors                                 14:48:36

 error  in ./resources/assets/js/components/Home.vue

Syntax Error: Unexpected token, expected , (27:26)

  25 |     return {
  26 |       newPostTitle: "",
> 27 |       newPostDesc: "", Vue.component('home', require('./components/Home.vue'));
     |                                            ^
  28 |     }
  29 |   },
  30 |   created() {

 @ ./resources/assets/js/components/Home.vue 3:0-355 4:0-368
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

       Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.55 MB       0  [emitted]  [big]  /js/app
/css/app.css   196 kB    0, 0  [emitted]         /js/app, /js/app

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],"es2015"],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Home.vue
Module build failed: SyntaxError: Unexpected token, expected , (27:26)

  25 |     return {
  26 |       newPostTitle: "",
> 27 |       newPostDesc: "", Vue.component('home', require('./components/Home.vue'));
     |                                    ^
  28 |     }
  29 |   },
  30 |   created() {

 @ ./resources/assets/js/components/Home.vue 3:0-355 4:0-368
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by posva** [comment]
That's not a valid repro

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
