### ISSUE TITLE
Why doesn't work global functions in event handlers?

### ISSUE THREAD

**Issue by rekby** [vuejs/vue#8274]
for example:

```
<button @click='alert(123)'>asd</button> 
```

caught error:
_vm.alert is not a function

https://codesandbox.io/s/lxw6711y57

**Comment by leopiccionia** [comment]
According to the [docs](https://vuejs.org/v2/guide/syntax.html#Using-JavaScript-Expressions):
> Template expressions are sandboxed and only have access to a whitelist of globals such as `Math` and `Date`. You should not attempt to access user defined globals in template expressions.

Possible reasons for this behavior, I guess, is security and avoiding side-effects in template rendering.

A workaround for your case is creating an `alert` method, that calls global `alert` function.
