### ISSUE TITLE
Transition behavior is different when an uncalled done is provided in hook method

### ISSUE THREAD

**Issue by jackysee** [vuejs/vue#8275]
### Version
2.5.16

### Reproduction link
[http://jsbin.com/gakoreyoha/edit?html,css,js,output](http://jsbin.com/gakoreyoha/edit?html,css,js,output)

### Steps to reproduce
In the demo link, click toggle to show and hide element

### What is expected?
The two boxes are configured with `<transition>` with different `enter` and `leave` hook. One is called with `leave(el){ ... }` and the other one is called with `leave(el, done){ .... }`. Both function do the same thing and the `done` callback is not called. It is expected that the two boxes enter and leave the same way.

### What is actually happening?
The box hooked `leave(el)` hook has no leave transition.

**Comment by posva** [comment]
You forgot to listen the leave event on the transition component (you did it with enter)

**Comment by jackysee** [comment]
Sorry my bad. I have some cache problem with the demo bin. I shall create a new issue with a proper demo.
