### ISSUE TITLE
trouble with v-if/v-else-if ？？

### ISSUE THREAD

**Issue by haoyinag** [vuejs/vue#8276]
### Version
2.5.16

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
外层for，然后子项再次for，
子项循环的时候会根据一个status来显示，所以用到v-if v-else-if v-else
然后出现的问题是v-if没问题，v-else-if/v-else都加载了两 1次，就是本来length是3，实际加载出来是7条数据

### What is expected?
正常显示

### What is actually happening?
外层for，然后子项再次for，
子项循环的时候会根据一个status来显示，所以用到v-if v-else-if v-else
然后出现的问题是v-if没问题，v-else-if/v-else都加载了两 1次，就是本来length是3，实际加载出来是7条数据

**Comment by posva** [comment]
Please provide a valid repro when opening an issue.
Note you can ask questions in the dircord server or the forums 🙂
