### ISSUE TITLE
vuejs site running in development mode

### ISSUE THREAD

**Issue by mkastner** [vuejs/vue#8277]
![vue-js-dev-mode](https://user-images.githubusercontent.com/287486/40718051-e93d75ac-640e-11e8-8b34-b5240cb062ab.png)
### Version
2.5.16

### Reproduction link
[https://vuejs.org](https://vuejs.org)

### Steps to reproduce
enter https://vuejs.org in browser address bar, check console in browser development tools

### What is expected?
vuejs site running in production mode

### What is actually happening?
vuejs is running in development mode

---
Or is it supposed to run in development mode?

**Comment by ulivz** [comment]
It seems that you should go https://github.com/vuejs/vuejs.org to open this issue.

**Comment by mkastner** [comment]
I see, sorry!

**Comment by Justineo** [comment]
It’s intentional AFAIK.

**Comment by LinusBorg** [comment]
As mentioned: wrong repository, and yes, intentional.
