### ISSUE TITLE
Component name only allow first char to be uppercase

### ISSUE THREAD

**Issue by xboxeer** [vuejs/vue#8280]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/337695/](https://jsfiddle.net/50wL7mdz/337695/)

### Steps to reproduce
no special steps, change the componet name from MyTest to Mytest and &lt;MyTest>&lt;/MyTest> to &lt;Mytest>&lt;/Mytest> make it work, otherwise the componet just don't get rendered

### What is expected?
The component should be there with content 自定义组件! surrended by h1

### What is actually happening?
componet not there actually, if i change my componet name from MyTest to Mytest, the componet got rendered properly

---
I'm new to Vue so not quite sure if it is a bug or Vue component standard,

**Comment by posva** [comment]
This is because youre using an html template and everything gets converted to lowercase before Vue gets it.
It has been asked multiple times so you should be able to find any extra information necessary 🙂 there is also a section about this in the docs
