### ISSUE TITLE
Hot reload problem when use keep-alive wrap router-view with a dynamic key

### ISSUE THREAD

**Issue by hxlyd** [vuejs/vue#8282]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/vyy3yokjj0](https://codesandbox.io/s/vyy3yokjj0)

### Steps to reproduce
1.modify the code in the script tag of the Hello component

2.the router-view component disappear from the page

3.we can find the component is activated with devtools
 

### What is expected?
Hot reload normally

### What is actually happening?
Have to refresh the page manually each time modify the code

**Comment by posva** [comment]
Please open this issue in vue loader repo
