### ISSUE TITLE
Component data support for promise

### ISSUE THREAD

**Issue by Fenzland** [vuejs/vue#8283]
### What problem does this feature solve?
We want component data access a promise, show '' before promise, and auto update view when promise resolved.

### What does the proposed API look like?
```js
...
data(){
  return {
    foo: new Promise(/*...*/),
    bar: (async ()=>{/*...*/})(),
    baz: fetch( /*url*/ ),
  };
},
...
```

**Comment by posva** [comment]
This has to be done in userland because you may want to have a promise in data. You should give https://github.com/posva/vue-promised a try 🙂
