### ISSUE TITLE
Hook=componentUpdated of Vue directive seems not be called correctly

### ISSUE THREAD

**Issue by cj1205** [vuejs/vue#8288]
### Version
2.5.16

### Reproduction link
[https://stackoverflow.com/questions/50634762/hook-componentupdated-of-vue-directive-not-triggered](https://stackoverflow.com/questions/50634762/hook-componentupdated-of-vue-directive-not-triggered)

### Steps to reproduce
At the demo in **Reproduction link**, hit **Click Me!** button then you will see the hook=**componentUpdated** is not called.

Then when click **change data** (execute similar behavior with click me!, the difference is it changes the data at parent component), it will be trigger correctly.

### What is expected?
the hook 'componentUpdated' of the custome directive should be called after the containing component’s VNode and the VNodes of its children have updated. but it seems be `the VNodes of its children have been remounted, not updated`

### What is actually happening?
if one child component only update its own data, it will not trigger the hook=componentUpdated of the directive at the parent component.

**Comment by posva** [comment]
notice the *and* in the sentence. It won't trigger if only the child was updated

**Comment by cj1205** [comment]
All right, I got it.
So we have to build own observer for any Dom change of the containing component.
Is it possible Vue can support one hook like `updateDeep` to support child component update only? or based on current one way flow, it is not possible?

**Comment by posva** [comment]
you shouldn't be observing dom updates in most scenarios, but data instead
It is possible using a bus or a store, but there may be a better solution 🙂
