### ISSUE TITLE
children component not update when change Array props in parent

### ISSUE THREAD

**Issue by JJJJYYYY** [vuejs/vue#8295]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/jesse_y/obbL7s1k/](https://jsfiddle.net/jesse_y/obbL7s1k/)

### Steps to reproduce
1. click `change`, children component not update
2. click `update`, children component update

### What is expected?
click `change`, children component update

### What is actually happening?
children component not update

---
maybe not a bug, I test 2.* and 1.*(not all), it not work in those version.  
is it a bug? if not why?  
thanks for your time.

**Comment by Justineo** [comment]
```js
this.numbers[0]++
```

is equal to

```js
this.numbers[0] = this.numbers[0] + 1
```

which is already discussed in the [guide](https://vuejs.org/v2/guide/list.html#Caveats).

You should do this instead:

```js
this.$set(this.numbers, 0, this.numbers[0] + 1)
```

**Comment by JJJJYYYY** [comment]
@Justineo thanks!
