### ISSUE TITLE
watch -- Prevent data change

### ISSUE THREAD

**Issue by nicefan** [vuejs/vue#8298]
### What problem does this feature solve?
watch中，验证一个值的有效性，不通过则还原为oldValue,  watch还会再执行一次，如果oldValue开始就有问题，就会造成死循环，如果watch方法中能通过 return false 来阻止数据改变就好了。

### What does the proposed API look like?
```js
...
watch: {
   name (newValue, oldValue){
      if (validate(newValue)) {
        this.name = oldValue
      }
   }
},
...
```
like this:
```js
...
watch: {
   name (newValue, oldValue){
      if (validate(newValue)) {
        return oldValue  // or return false
      }
   }
},
...
```

**Comment by Justineo** [comment]
1. Why would `oldValue` be invalid in the first place?
2. You can validate `oldValue` in the watcher too, before you set the invalid value back to `oldValue`.

**Comment by guAnsunyata** [comment]
You can validate your data before you actually mutating the target.

**Comment by yyx990803** [comment]
启动的时候先 validate 一遍.

**Comment by nicefan** [comment]
解决办法是有很多，只是认为不管怎么样，在watch里更改watch的值，会多去执行一次handler，应该是没必要的，如果计算过多，比如重新计算大量树状结构向上累计的合计值的操作，有些资源浪费。

**Comment by Justineo** [comment]
既然没有必要，那更应该在修改之前就处理掉了。

**Comment by nicefan** [comment]
我的想法是监控数据变化也能阻止数据变化，否则的话重新赋旧值时，又会触发一次
________________________________
