### ISSUE TITLE
Allow bitwise OR in template expressions with numbers

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vue#8304]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/swLuey0f/](https://jsfiddle.net/swLuey0f/)

### Steps to reproduce
Pipes are used as bitwise OR operator. This was already noted here: https://github.com/vuejs/vue/issues/2422

I wanted to quickly round a number with `value | 0`. but I found that it didn't work. Only my knowledge of the rather unpopular filters feature in Vue helped me to realize why this does not work.

### What is expected?
My suggestion would be, to detect numbers for bitwise OR operations and strings for functions/filters. Since numbers can't be used for functions anyway. Or since filters are defined as properties within the `filters` object, we could at least scan if the filter exists.

> Vue.js actually supports the full power of JavaScript expressions inside all data bindings

This part of the documentation would be a lie otherwise. If you do not agree with the proposed change, I would at least document these exceptions there. But since the bitwise operator isn't that big in popularity, it may seem unconsiderable to bloat the documentation for this edge-case.

### What is actually happening?
bitwise operator does not get rendered

**Comment by MartinMuzatko** [comment]
Also important to note. TC39 is working on a standard to implement filters for javascript: https://github.com/tc39/proposal-pipeline-operator
Once this is a standard, we should adopt that, since this seems to be exactly what filters do in our context.
I see no clear documentation what benefits filters serve by the way. How are they different to methods applied with `{{ capitalize(value) }}` or with the new pipeline operator: `{{value |> capitalize}}`

**Comment by LinusBorg** [comment]
> I see no clear documentation what benefits filters serve by the way. How are they different to methods applied with {{ capitalize(value) }} or with the new pipeline operator: {{value |> capitalize}}

The benefit over normal methods is mainly that you don't have to pollute your component's / app's instance namespace with formatter methods. You can end up with quite a number of such formatters/filters that you need *"everywhere"*.

The benefit over the pipeline operator is that thje pipeline operator doesn't exist yet, but filters do.

**Comment by sodatea** [comment]
The proposed change would be a breaking change so it will not land in 2.x codebase.

But I do agree that the documentation could be improved by addressing the filter / bitwise OR issue. You can open an issue or submit a PR in https://github.com/vuejs/vuejs.org/
