### ISSUE TITLE
Key not working with functional component

### ISSUE THREAD

**Issue by DanSnow** [vuejs/vue#8306]
### Version
2.5.16

### Reproduction link
[https://codepen.io/dododavid006/pen/vrKgEv](https://codepen.io/dododavid006/pen/vrKgEv)

### Steps to reproduce
1. Type something into input so you can distinguish input
2.  Click the third remove button

gif:  https://imgur.com/I2Hqu6K

### What is expected?
It should keep the fourth input.

### What is actually happening?
The third input is keep.

**Comment by LinusBorg** [comment]
functional components don't have an instance,, so you can't key the component itself. rather, the functional component has to key its element(s) itself - because it could potentially return multiple elements, so Vue can't reliably decide on which to apply the key, if one was provided.

```javascript
render (h, {data, listeners: {remove}}) {
    return h(
      'div',
      { key: data.key },
      [
        h(
          'input',
```
