### ISSUE TITLE
keep-alive结合compontent使用，当切换的组件是多个页面共用时，include不能区分这些页面从而删掉缓存

### ISSUE THREAD

**Issue by lizijins** [vuejs/vue#8310]
### What problem does this feature solve?
利用keep-alive结合compontent，实现切换tab的效果。但是有多个tab用同一个组件的情况，我加了key做区分，如下：
 &lt;component :is="currentTabComponent" :key="moduleId" &gt;&lt;/component&gt;
这样，可以缓存这些使用同一个组件的tab。问题是，删除tab时，用include只能匹配组件的name或注册名，并不能区分使用相同组件的tab。
然后我用$desytoy销毁，再次创建时又会有组件不断created，缓存不了的现象。
有什么办法解决这种场景吗？

### What does the proposed API look like?
include中是否可以把key带进去，区分组件相同key不同的缓存实例

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue/issues/8028
