### ISSUE TITLE
async function instanceof Promise === false

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue#8311]
### Version
2.5.16

### Reproduction link
[ https://yadi.sk/i/kEgLN0O-3XFsi6]( https://yadi.sk/i/kEgLN0O-3XFsi6)

### Steps to reproduce

https://yadi.sk/i/kEgLN0O-3XFsi6

### What is expected?
What for?

I use vue-cli to install the initial version of the project

**Comment by yyx990803** [comment]
That's not a valid reproduction.

**Comment by ariran5** [comment]
Open project with vue and run code in console. Global promise polyfill not work with async await

**Comment by ariran5** [comment]
Sorry, its babel.
How to use
1) vue create testPromise
2) use new Promise in helloWorld file
3) open in chrome 66

https://yadi.sk/i/QsTMDQhT3XGvD7

**Comment by ariran5** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=830565

problem solved but Babel use custom Promise
