### ISSUE TITLE
why $off can't work similarly removeEventListener?

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#8313]
### Version
2.5.16

### Reproduction link
[vue event  listener removin](https://codepen.io/PatriciusSanctus/pen/VdjoZo)
[native event listener removin](https://codepen.io/PatriciusSanctus/pen/LrZKgM)

### What is expected?
It is expected that you can delete listeners by function

### What is actually happening?
all listeners deleted

---
$off function not compare function names. it is important 😱

**Comment by sqal** [comment]
What is stranger, binding just one event will increment both values :D

```js
this.$on('incr', this.oneIncr)
document.addEventListener('mousemove', () => {
  this.$emit('incr')
})
```

**Comment by sqal** [comment]
You're using variable 'one' in your template twice

**Comment by patriciussanctus** [comment]
ouph real, thx, I did not notice a big mistake in my code and send undefined method
