### ISSUE TITLE
web: transition-group warn Cannot convert 'r[Gi "Delay"]' to object in Android Opera

### ISSUE THREAD

**Issue by cxtom** [vuejs/vue#8314]
### Version
2.5.17-beta.0

### Reproduction link
[https://codepen.io/cxtom/pen/rKMWRL](https://codepen.io/cxtom/pen/rKMWRL)

### Steps to reproduce
1. use transition-group in Android Opera (Opera/9.80 (Android; Opera Mini/4.5.40312/79.13; U; zh) Presto/2.12.423 Version/12.16)
2. use css transition

### What is expected?
animation is correct

### What is actually happening?
warn Cannot convert 'r[Gi "Delay"]' to object

**Comment by sodatea** [comment]
According to  [Can I Use](https://caniuse.com/#feat=css-transitions), Opera Mini does not support CSS transitions, and:
> In most cases Opera Mini processing is done via Opera servers, which often prevents JS from working correctly.

BTW the `Gi` error message seems to be raised from a third-party js file imported by codepen.
