### ISSUE TITLE
vue SPA 部署问题？

### ISSUE THREAD

**Issue by wuzhuojun** [vuejs/vue#8316]
### Version
2.5.13

### Reproduction link
[https://dev.www.zimeishe.net](https://dev.www.zimeishe.net)

### Steps to reproduce
1.vue router 用 history 模式

2.webpack chunkhash 方式 打包

3.放到 Nginx 下

当第二次我修改某个文件之后，网站部署后，js文件命名更新了，用户在并没有刷新页面的情况下 怎么更新到新的文件呢？

若网站不刷新会显示异常。

webpack配置：
output: {
       path: config.build.assetsRoot,
       filename: utils.assetsPath('js/[name].[chunkhash].js'),
       chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
},

nginx配置：
        location / {
             #设置浏览器缓存,能保证 index.html 时刻保持最新的文件内容
             add_header Cache-Control no-cache;
             add_header Cache-Control private;
             try_files $uri $uri/ @router;
             index index.html;
        }
        location @router {
            rewrite ^.*$ /index.html last;
        }

### What is expected?
当第二次我修改某个文件之后，网站部署后，js文件命名更新了，用户在并没有刷新页面的情况下 怎么更新到新的文件呢？

### What is actually happening?
若网站不刷新会显示异常。

**Comment by sodatea** [comment]
考虑到代码热更新的复杂性，只建议在开发环境下使用。
生产环境的 SPA 一般是通过某种机制提示用户手动刷新页面。

可能的方案有：
1. 轮询 / WebSocket 查询后端接口，判断当前版本号是否最新，不是最新就提示用户刷新；
2. 切换路由时判断是否有版本更新，如果有更新就做一次全页面刷新；
3. 全局的错误处理函数中加上兜底代码，提示用户异常可能是因为页面过期，或者直接用代码 reload 页面。

**此类问题以后建议到[官方论坛](https://forum.vuejs.org/)或问答网站上提问。GitHub 的 issues 只用于 Bug 反馈和特性请求。**
