### ISSUE TITLE
Not possible to use $, _ or $_ as variable name prefix in a mixin

### ISSUE THREAD

**Issue by MatteoGabriele** [vuejs/vue#8317]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/eywraw8t/67444/](https://jsfiddle.net/eywraw8t/67444/)

### Steps to reproduce
Create a mixin and add some variable as illustrated in the reproduction link: only properties without $, _ or $_ will be rendered, the other will throw an error.

### What is expected?
I expect to be able to use all these 3 options as a prefix of my variables or at least the one suggested in the documentation: which is $_

### What is actually happening?
The application is throwing the vue warn for an undefined property during render

**Comment by Justineo** [comment]
> Properties that start with `_` or `$` will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as `vm.$data._property`.

Please check the official guide [here](https://vuejs.org/v2/api/#data). You can use any of those prefixes behind `$data`.

**Comment by MatteoGabriele** [comment]
hi @Justineo 
thanks for your suggestion, but isn't it a bit weird that only property coming from a mixin are not proxied, as the documentation says?
How to create a mixin with variable names that are less prone to be conflicting with Vue API and component properties?

**Comment by Justineo** [comment]
> but isn't it a bit weird that only properties coming from a mixin are not proxied, as the documentation says?

The rule is not limited to mixins as I understand.

**Comment by MatteoGabriele** [comment]
I just found out that it only works when you explicitly define such property but doesn't work out of the box in a component either

```js
export default {
  data () {
    return { 
      $$foo: [] // here is undefined
    }
  },
  created () {
    this.$$foo = [] // here is defined
  }
}
```

I will try to use other naming convention then
thanks

**Comment by Justineo** [comment]
Properties defined manually will not be reactive.
