### ISSUE TITLE
vue vue-router vuex 版本对应关系

### ISSUE THREAD

**Issue by Rich1e** [vuejs/vue#8319]
### Version
2.3.0

### Reproduction link
[https://b.pingan.com.cn/pacard/cordwood/30th-anniversary](https://b.pingan.com.cn/pacard/cordwood/30th-anniversary)

### Steps to reproduce
none

### What is expected?
vue vue-router vuex 版本太多了，能列出它们之间的对应关系吗？

e.g. vue2.3.0   vue-router 2.5.2   vuex 2.3.1

### What is actually happening?
如果不使用vue-cli，vue vue-router vuex之间的版本完全弄不清楚，导致开发过程中各种报错。

---
希望有详细的文档，描述清楚（vue，vue-router，vuex）之间的版本对应关系。

**Comment by fnlctrl** [comment]
vue/vuex/vue-router 2.x版本是互相兼容的。如果“开发过程中各种报错“，请给重现。
