### ISSUE TITLE
updated hook is triggered but data not change

### ISSUE THREAD

**Issue by grtan** [vuejs/vue#8320]
### Version
2.5.16

### Reproduction link
[https://codepen.io/greenhandTan/pen/NzRYZR](https://codepen.io/greenhandTan/pen/NzRYZR)

### Steps to reproduce
waitting 1s and then show a alert dialog

### What is expected?
updated hook should not be triggered

### What is actually happening?
updated hook is triggered

**Comment by posva** [comment]
I believe this is intended as it wouldn't be beneficial enough to check everything that has been set before updating.
In the other hand, if you have something expensive at every update, you can prevent it by setting the variable `message` only if it really changed.
