### ISSUE TITLE
where's jsx?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [vuejs/vue#8321]
### What problem does this feature solve?
So If I have the following:

```
<template>
  <div class="dropdown-container">
    <p>{{ selectedValue }}</p>
    <div class="dropdown-options">
      <div v-for="(option, optionIndex) in options" :key="optionIndex">
        {{ renderItem(option) }}
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'vue-dropdown',
  props: {
    options: {
      type: Array,
      default: new Array()
    },
    selectedValue: {
      type: String,
      default: ''
    },
    renderItem: Function
  }
};
</script>
```

The renderItem is a method on the parent component that looks like this:

```
renderItem (option) {
  return <p>hello!</p>;
}
```

Is this possible? so basically I want to call this method and I want it to return an element (jsx) that would be rendered inside the place where the function was called.

I couldn't find a resource about this online so I opened an issue here.

### What does the proposed API look like?
```
methods: {
  // ...
  renderItem (option) {
    return <p>hello!</p>;
  }
}
```

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/render-function.html

**Comment by yyx990803** [comment]
Use `this.$createElement` which is equivalent of the `h` that's passed to `render()`.
