### ISSUE TITLE
Did you plan to switch from vuejs to vuets?

### ISSUE THREAD

**Issue by luogeng2017** [vuejs/vue#8323]
### What problem does this feature solve?
just thinking ts is strict and security and haveing Code hints

### What does the proposed API look like?
 haveing Code hints

**Comment by yyx990803** [comment]
https://vuejs.org/v2/guide/typescript.html

**Comment by luogeng2017** [comment]
i know that **TypeScript Support**.i mean , do you have any idea to create a vuets write by  TypeScript，thank you
