### ISSUE TITLE
Feature Request - Add event modifier that distinguishes 'click' from 'drag'

### ISSUE THREAD

**Issue by p4773rn** [vuejs/vue#8324]
### What problem does this feature solve?
Allows highlighting the text inside of elements without triggering the function called on click. The common situation would be trying to highlight and copy some text inside of the table row, but clicking on this row shows the dialog with more information about its entry. With the suggested modifier the dialog would open only if the row is clicked without moving the mouse.

### What does the proposed API look like?
```
<table>
    <tr @click.stationary="showDetails">
        <td> Text I want to copy </td>
        <td> Another text </td>
    </tr>
</table>
```

**Comment by LinusBorg** [comment]
I think since this is very specific to one combination of events, this should be solved in userland...
