### ISSUE TITLE
Custom directive's `inserted` hook gets called when is not inserted

### ISSUE THREAD

**Issue by matrunchyk** [vuejs/vue#8327]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/7ko5jno700?expanddevtools=1](https://codesandbox.io/s/7ko5jno700?expanddevtools=1)

### Steps to reproduce
Please take a look at this code:  
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7ko5jno700?expanddevtools=1)

The key things here are `:key` attribute on the element and DOM manipulations in the `inserted` hook.

### What is expected?
Expected to have the element mounted (or at least have a parent node)

### What is actually happening?
No parent node

---
The documentation says the parent node is guaranteed: https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions.

**Comment by posva** [comment]
You shouln't manually move the content the dom that is handled by Vue because it relies on it to perform updates (Moving the `el` with ` wrapper.appendChild(el);`)
