### ISSUE TITLE
Sponsor links do not work.

### ISSUE THREAD

**Issue by mitomex** [vuejs/vue#8329]
### Version
2.5.17-beta.0

### Reproduction link
[https://github.com/vuejs/vue/blob/654e5f153dc88ee5fc853af6df178c4fc24abe98/README.md](https://github.com/vuejs/vue/blob/654e5f153dc88ee5fc853af6df178c4fc24abe98/README.md)

### Steps to reproduce
Open README.md

### What is expected?
Corporate websites are shown when I click the sponsor links.

### What is actually happening?
Sponsors via Open Collective's Gold links at [README.md](https://github.com/vuejs/vue/blob/654e5f153dc88ee5fc853af6df178c4fc24abe98/README.md) show me "not found" page. This also happens at [BACKERS.md](https://github.com/vuejs/vue/blob/654e5f153dc88ee5fc853af6df178c4fc24abe98/BACKERS.md).

**Comment by sodatea** [comment]
Might be a bug of Open Collective.
https://github.com/opencollective/opencollective/issues/1127

**Comment by yyx990803** [comment]
Closing to be resolved upstream.
