### ISSUE TITLE
keydown + shift +  enter isn't able to update v-model

### ISSUE THREAD

**Issue by martianmartian** [vuejs/vue#8330]
### Version
2.5.16

### Reproduction link
[https://codepen.io/martian2049/pen/ZRLxxQ](https://codepen.io/martian2049/pen/ZRLxxQ)

### Steps to reproduce
just open the link first.
pointer focus on SECOND input area, press "shift enter" at the same time. 
both input area are supposed to be reset, but  the second one doesn't get reset. 
if you pointer focus on FIRST input area, press "shift enter" at the same time, it will work

### What is expected?
i thought keydown should do mostly the same as keyup, except for the timing thing.

### What is actually happening?
keydown doesn't enable v-model to synch data

---
thanks for reading it.

**Comment by posva** [comment]
Add a `.prevent` to prevent the input from also adding a newline (which modifies the value as well)

**Comment by martianmartian** [comment]
that's kind of a hack... lol, but as long as it works.
