### ISSUE TITLE
父组件向子组件传值使用watch监听prop无响应

### ISSUE THREAD

**Issue by Mingscript** [vuejs/vue#8332]
### Version
2.5.2

### Reproduction link
[http://jsfiddle.net/n2rtkxew/](http://jsfiddle.net/n2rtkxew/)

### Steps to reproduce
因为异步的关系没有使用计算属性从而使用watch但是没有响应

### What is expected?
我需要在prop变化的时候，子组件可以监听到变化并调用函数

### What is actually happening?
但是在prop变化时，监听并没有变化，也没有调用函数

**Comment by Justineo** [comment]
Please provide an executable reproduction. Thanks.

**Comment by Mingscript** [comment]
There are too many things involved and it is not easy to copy. I wonder if there is any solution to this problem, namely watch and the value that cannot be heard from the parent component.
Thanks.
@Justineo

**Comment by ulivz** [comment]
> ...There are too many things involved and it is not easy to copy ...

Since you even aren't willing to **copy**, how do you want others to help you solve the problem?

**Comment by Mingscript** [comment]
不用了已经解决了，谢谢。
@Justineo @ulivz
