### ISSUE TITLE
vue init template cli is error!

### ISSUE THREAD

**Issue by warriorBrian** [vuejs/vue#8336]
### Version
2.5.17-beta.0

### Reproduction link
[https://cn.vuejs.org/](https://cn.vuejs.org/)

### Steps to reproduce
vue init webapck demo

### What is expected?
He should work normally

### What is actually happening?
vue-cli : Failed to download repo vuejs-templates/webapck: Response code 404 (Not
Found)

![_20180611230052](https://user-images.githubusercontent.com/28696399/41239852-b4ef7e28-6dcb-11e8-96c1-190a91c9d4ac.png)

**Comment by warriorBrian** [comment]
@yyx990803  请问这个该如何解决呢？

**Comment by sodatea** [comment]
typo.

webapck -> webpack
