### ISSUE TITLE
Component status can't be updated in the latest chrome browser

### ISSUE THREAD

**Issue by eschao** [vuejs/vue#8338]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eschao/eywraw8t/71555/](https://jsfiddle.net/eschao/eywraw8t/71555/)

### Steps to reproduce
Click button, the name of button can't be changed from **Modify** to **Cancel**

### What is expected?
It works in chromium 58.0.3015.0 and firefox 60.0.2, but can't work in latest chrome 67.0.3396.79

### What is actually happening?
The name of button can't be changed after click

---
I'm not sure if I misuse the vue command: **v-if** and **v-else**. If wrong, please correct me. If not, please take a look this issue

**Comment by eschao** [comment]
It also works in chromium: 69.0.3456.0

**Comment by Justineo** [comment]
I'm using Chrome `v67.0.3396.79` and your fiddle is working as expected.

**Comment by eschao** [comment]
@Justineo Ok, I think I need to try to restart browser or macos. That's really strange. Sigh!

**Comment by eschao** [comment]
@Justineo Have you tried it on macos with latest chrome? I still have such problem after restart system and browser. Anyone can help to double check? I will try it on my iMac tonight!

**Comment by eschao** [comment]
Anyway, I guess it is caused by some chrome extensions, I close most them and try it on incognito mode and it works. Sorry for bothering everyone.
