### ISSUE TITLE
针对需要事件代理的情况，有没有什么好的方案？

### ISSUE THREAD

**Issue by SBDavid** [vuejs/vue#8339]
### What problem does this feature solve?
尊敬的作者您好：基于页面性能的考虑，很多时候需要使用事件代理。在vue中使用事件代理我碰到两个问题。

1）事件代理需要读取event.nodeName（甚至是读取子节点等操作），这相当于对Dom进行一些操作，这有些违反vue的设计初衷。

2）即使读取了event.nodeName，也很难将它与组件状态联系起来，而且大多数时候需要在处理函数中修改状态。

有什么好的方案吗？vue框架中适合使用事件代理吗？

### What does the proposed API look like?
我没有想到如何解决这个问题 = =

**Comment by Justineo** [comment]
Issues are for bug reports and feature requests only, maybe you can discuss this on our [forum](https://forum.vuejs.org/) or [Discord](http://chat.vuejs.org/).
