### ISSUE TITLE
2.5.0 开始，微信内数据双向绑定无效

### ISSUE THREAD

**Issue by falstack** [vuejs/vue#8341]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/m99jmqsa/8/](https://jsfiddle.net/m99jmqsa/8/)

### Steps to reproduce
```
1. 打开 jsfiddle
2. 浏览器名称：微信 6.6.7.1321
3. 浏览器内核：Webkit 537.36
4. OS：Android 8.1.0
5. 硬件信息：ONEPLUS-A5010
6. 这个环境 jsfiddle 是 run 不起来的，得本地开个 server 复现，是必现的
```

### What is expected?
每次 click 的时候，页面上 text  1

### What is actually happening?
text 的 data   1 了，但是页面没有重新渲染

**Comment by fnlctrl** [comment]
> 这个环境 jsfiddle 是 run 不起来的
若这个环境中无法运行，请检查浏览器报错

以及请检查环境是否支持ES6对象属性简写
```javascript
    data () {}, //  试一下data: function () {} ，后同
```

**Comment by falstack** [comment]
@fnlctrl 我可能没有详细的讲清楚问题

1.  `Vue.Js 2.5.0` 开始双向绑定失效，意思就是`Vue.Js 2.4.4`及其之前都是 work 的，因此不是语法问题，是一个兼容性问题
2. **这个环境 jsfiddle 是 run 不起来的** 的意思是，jsfiddle 在我指定的那个环境里，jsfiddle.net 自己崩了，因此你要真实的环境去起个 server 打开静态页面去复现
3. 每次 click 的时候，data 都会变化，alert 也生效，意思就是说没有语法错误，但是数据没有更新，一次你我认为是`2.5.0`开始的大改动导致之后的所有版本在以上环境中都无法 work

能 reopen 吗？

**Comment by sodatea** [comment]
终于找到了一台 Android 手机测试……
用的华为 Mate 10，UA 为 Mozilla/5.0 (Linux; Android 8.0; ALP-AL00 Build/HUAWEIALP-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/044109 Mobile Safari/537.36 MicroMessenger/6.6.7.1321(0x26060737) NetType/WIFI Language/zh_CN
无法复现

你试过其他 Android 手机吗？是只有 ONEPLUS-A5010 有这个问题还是普遍现象？

**Comment by falstack** [comment]
@sodatea 我今天来尝试一下

**Comment by falstack** [comment]
刚才尝试了一下，同样的设备和同样的代码，这次 run 就是 OK 的
线上的产品也能正常使用了

感觉像是微信的热更新解决的，sorry
