### ISSUE TITLE
Combination of inputs with lazy model and :disabled causes odd behaviour

### ISSUE THREAD

**Issue by mlekoo** [vuejs/vue#8347]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/qbsjL3d0/6/](http://jsfiddle.net/qbsjL3d0/6/)

### Steps to reproduce
Create two inputs with lazy models being set to nulls.
Add @input/@key attribute in the first input with a function that makes a specific variable true/false depending on the live content of the field.
Set :disabled attribute in the second input with the variable mentioned above.

### What is expected?
Normal behaviour of the second input, keeping settings enlisted in reproduction and jsfiddle.

### What is actually happening?
Combining mentioned above options causes weird behaviour of the second input - first typed in character gets erased. Removing either :disabled, .lazy or making the data empty string instead of null makes the problem go away (please note, that removing only one of those options, no matter which fixes this issue), but still - I need to use this particular scenario.

---
Context: I use vuelidate plugin for form validation - I want the validation to happen on blur, so I use the lazy model. At the same time I want to disable/enable field based on the first input's content. Since both models are lazy I have to use @keyup/@input to check the current value, otherwise it requires taking the focus off to enable the second input. Note, that this issue occurs without the vuelidate plugin, I mentioned it only to show the background of how I ran into this.

**Comment by posva** [comment]
This is expected because you're triggering a rerender and because the value of `a` is not saved (because of lazy), Vue re applies the old value

**Comment by mlekoo** [comment]
How do you explain then the fact that changing the initial values to empty strings instead of nulls changes the behavior to the one that I expect. Shouldn’t it reapply the empty string then ?

**Comment by mlekoo** [comment]
@posva

**Comment by posva** [comment]
v-model is making things easier for you. You should initialise the value to an empty string btw
