### ISSUE TITLE
vue can not set css animation

### ISSUE THREAD

**Issue by weituotian** [vuejs/vue#8349]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/weituotian/48q2p19a/](https://jsfiddle.net/weituotian/48q2p19a/)

### Steps to reproduce
jsfiddle example: 
https://jsfiddle.net/weituotian/48q2p19a/

### What is expected?
set the style animation to the dom

### What is actually happening?
the attr do not render to the dom.
can not see the dom's style animation

---
so also below can not be render to the dom style

```
let animationCss={} 
animationCss["animation"] = "";
                animationCss["animation-name"] = "fadeIn";
                animationCss["animation-duration"] = "3s";
                animationCss["animation-timing-function"] = "linear";
                animationCss["animation-delay"] = "1s";
                animationCss["animation-iteration-count"] = "1";
```

**Comment by Justineo** [comment]
```js
new Vue({
  el: '#app',
  data () {
    return {
      boxCss: {
        color: 'red',
        animation: "fadeIn 1s ease 2.4s"
      }
    }
  },
  data: {
    message: 'Hello Vue.js!'
  }
})
```

You have a duplicated `data` key in the same object.

**Comment by weituotian** [comment]
@Justineo 
I had fix it, but the attr `animation` don't work too!

**Comment by sodatea** [comment]
The style binding has worked as expected.
Animation not showing up because the referenced keyframe `fadeIn` does not exist yet. You need to define that in your CSS markup first.
```html
<style>
@keyframes fadeIn {
    from { opacity: 0; }
    to   { opacity: 1; }
}
</style>
```

**Comment by weituotian** [comment]
@sodatea 
not solve yet! why close my issue？
i had animate.css in my project!
it not work!

**Comment by sodatea** [comment]
Works in the provided jsfiddle snippet.
https://jsfiddle.net/odzmcx74/

**Comment by weituotian** [comment]
@sodatea ok! it works! thanks for your great help!
