### ISSUE TITLE
Preserving multiple white spaces

### ISSUE THREAD

**Issue by hnviradiya** [vuejs/vue#8353]
### What problem does this feature solve?
Some data has multiple white spaces.

So sometimes user copies data from one element and uses to paste on another textbox for searching.

At that time if source tag has multiple spaces, the browser makes it single, so it will not search when used for exact comparison.

To avoid that we can give something like "\_{{ Some Data }}\_" (IMHO) when data is bound, when this sort of syntax found, it can replace all white spaces with "\&nbsp;" within that data to look exactly what it is.

So when someone copy-pastes that data, one will have all spaces preserved. I know this can be done using manual replacement or styling with "white-space: pre" or pre tag but that would be so much maintenance for all places.

### What does the proposed API look like?
\<span>Message: \_{{ msg with m  u  l  t  i  p  l  e white spaces }}\_\</span>

**Comment by Justineo** [comment]
The current behavior is just how HTML deals with white spaces. Using a [filter](https://vuejs.org/v2/guide/filters.html) (something like `{{ msg | keepSpaces }}`) would be better instead of inventing a new syntax for this.

**Comment by sodatea** [comment]
Thanks for your interest, but this issue has been raised several times before.
Generally, we don't add features that can be easily achieved in userland to avoid code bloat.
In your use cases, a custom filter would be sufficient.

**Comment by hnviradiya** [comment]
Oh. Great. I didnt know about that filter.
