### ISSUE TITLE
ProxyValueObserver

### ISSUE THREAD

**Issue by pecet86** [vuejs/vue#8354]
### What problem does this feature solve?
API OpenLayers 3/4 +  Vue
As I have in $data selectedFeature (ol.Feature) or selectedFeatures ([ol.Feature]), observer creates deep observation which is sometimes unnecessary and can frozen/lag the application

### What does the proposed API look like?
The solution may be Proxy which will only observe the changes of the first value.

Simple example:
https://jsfiddle.net/84eduf7n/10/

**Comment by posva** [comment]
if you need to stop Vue from observing deep nested data, you can `Object.freeze()` your objects, it's much easier 🙂

**Comment by pecet86** [comment]
@posva Ok, I will check

**Comment by pecet86** [comment]
@posva 
I checked and works but in a partial version. Why? It gives an example:
If you create:
```
base = {c: 'a'};
freez = Object.freeze (base);
```

then I will not be able to do:
```
base.d = 'd';
freez.e = 'e';
```

```
console.log (base) => {c: 'a'};
console.log (freez) => {c: 'a'};
```

It was more important for me to add the element in an intact form and later be able to get the element to change.

Once an object has been frozen there is no way to unfreeze it.
Not possibile added new fields :/

So he raises for reconsideration

**Comment by posva** [comment]
Yeah, that's the point, preventing Vue from observing changes, it has the limitation of not being able to add anything more. You can freeze nested objects though so not everything is left unchangeable
