### ISSUE TITLE
请问vue 什么时候能出一个类似react-native 原生的解决方案  虽然目前能实现打包 但是感觉有些地方还是没有原生APP体验那么流畅

### ISSUE THREAD

**Issue by yehoan** [vuejs/vue#8365]
### What problem does this feature solve?
一直都是vue框架的支持者  但是希望vue 能否有个原生的解决方案  目前用hbuild 打包vue 的apk 发现vuex 有时候会出现一些问题  有时候 点击无法生效 在 apk 里面 进而希望vue 社区能否来个类似react-native 的解决方案 现在阿里出了weex 我在社区看到发现很多问题  不知道以后能否有个更好的原生方案的出台 

### What does the proposed API look like?
vue 的原生解决方案

**Comment by yehoan** [comment]
一直都在用vue 里构建商城项目  效果很好  而且我们三个平台的站点都在用  现在随着js 在原生打包上的应用越来越多 想知道能否后期出一个类似react-native 这样的解决方案 全面支持原生这个方向  谢谢

**Comment by fnlctrl** [comment]
请参见[weex](https://weex.apache.org/cn/guide/)

**Comment by yyx990803** [comment]
Vue 官方不会开发此类项目。

**Comment by yehoan** [comment]
好的， 谢谢

**Comment by asika32764** [comment]
參見 https://vue-native.io/
