### ISSUE TITLE
Vue Becomes Really slow on large data even I am using pagination

### ISSUE THREAD

**Issue by Istanbouly** [vuejs/vue#8368]
Hello Guys I am building a social media website you can imagine it as Facebook currently supported feature on the website are basic things like (posting , commenting , replying etc ...)

I use Ajax to load most of my contents on the website surely the data is paginated Oh btw I use Laravel as Back-end now lets say I have a post that have 1000 comments in the database I am paginating comments 25 each time now the first 25 comments load fast like there is no problem when I click view more comments another 25 comments is loaded but a bit slower the third becomes even slower and so on lets say now 500 comments were loaded out of 1000 the rendering becomes really slow and any action that manipulate the DOM takes ages 

Is this a vue limitation or I am missing something here ?

Please help thanks in advance

**Comment by leopiccionia** [comment]
I guess you need something like [this](https://github.com/Akryum/vue-virtual-scroller).
