### ISSUE TITLE
npm Vue (node module) does not work in the standardized way

### ISSUE THREAD

**Issue by kenokabe** [vuejs/vue#8369]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
```HTML
    <div id="app">
      <p>{{ message }}</p>
    </div>
```

```js
  const Vue = require("vue");

  const app = new Vue({
    el: "#app",
    data: {
      message: "Hello Vue!"
    }
  });
```

### What is expected?
The native `npm`  or node module should work in a Browser-side JavaScript code such as in Electron environment.

### What is actually happening?
..myProject/node_modules/vue/dist/vue.runtime.common.js:589 [Vue warn]: 
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
warn @ /home/ken/p/markdown-editor/node_modules/vue/dist/vue.runtime.common.js:589

and the "Hello Vue!" does not work.

---
The reason of this issue is obviously,  `npm` module  `package.json` is as follows:

```
//...
 "main": "dist/vue.runtime.common.js", 
//...
```

The workaround is to change the client-js code to:

```js
  const Vue = require("./node_modules/vue/dist/vue.js");
`
  const app = new Vue({
    el: "#app",
    data: {
      message: "Hello Vue!"
    }
  });
```

I unserstand this is due to

https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

>CommonJS: CommonJS builds are intended for use with older bundlers like browserify or webpack 1. The default file for these bundlers (pkg.main) is the Runtime only CommonJS build (vue.runtime.common.js).

However, I think the standarized behavior of npm package is to run without browserify or webpack, and it's strange that 

"dist/vue.runtime.common.js" is the default module of the npm package.

It's should be

"dist/vue.js".

**Comment by posva** [comment]
Yes, if you want the template compilation, you need to use that version. If you want the template compiler for node, you have a dedicated package for it.
In any case, this would be a breaking change

**Comment by bradisbell** [comment]
@posva How can one `require()` or `import` Vue?

In my client-side script (which is compiled with Babel), I'll have something like this:

```
import Vue from 'vue';
```

This works on the surface, but with no way to specify a build, the "runtime-only" build is used, as @kenokabe said.  This (at least to me) doesn't make much sense.  Usually the module exported is a full build.  If someone wanted a scaled back build, they can get it out of `dist/`.

Is there any useful workaround?  Requiring out of `node_modules/` is not appropriate in my opinion... that directory can change.
