### ISSUE TITLE
.sync modifier doesn't work for deeply nested object in a v-for

### ISSUE THREAD

**Issue by jacobgoh101** [vuejs/vue#8373]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/jacobgoh101/g5bv0esd/1/](https://jsfiddle.net/jacobgoh101/g5bv0esd/1/)

### Steps to reproduce
Using .sync modifier for an array of objects in a v-for loop

### What is expected?
.sync modifier should update parent's data

### What is actually happening?
.sync modifier doesn't update parent's data

---
Manually adding events handler works. But .sync modifier doesn't.

**Comment by javoski** [comment]
It should be `$emit('update:itemAttribute', value)`, see [https://jsfiddle.net/g5bv0esd/5/](https://jsfiddle.net/g5bv0esd/5/)

**Comment by feliperaul** [comment]
@javoski Please consider re-opening. The [official guide, in the same section where the `.sync` is documented](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names), states: 

> ... we recommend you always use kebab-case for event names. 

This has bitten me as well. Either the docs needs fixing or the code does.

**Comment by sodatea** [comment]
@feliperaul https://github.com/vuejs/vuejs.org/issues/1648
