### ISSUE TITLE
使用v-for配合组件来构建bootstrap的一个table导致table样式不正确

### ISSUE THREAD

**Issue by ramwin** [vuejs/vue#8383]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/aohb8s76/](https://jsfiddle.net/aohb8s76/)

### Steps to reproduce
下载html代码  
$ wget https://raw.githubusercontent.com/ramwin/html-reference/master/test/vue-bootstrap-table.html  
然后用浏览器打开 vue-bootstrap-table.html

### What is expected?
根据vue里面的数据，显示出一张表格，并且表格的元素是左右对齐的。

### What is actually happening?
表格的body移到了thead的上面，并且左对齐了。

---
用户点击按钮，加载ajax数据，表格加载数据后，动态地更新表格里面的内容

**Comment by ramwin** [comment]
期待的效果：
![bootstrap-table.png](https://github.com/ramwin/netdisk/blob/master/bootstrap-table.png?raw=true)
实际的效果:
![vue-bootstrap-table.png](https://github.com/ramwin/netdisk/blob/master/vue-bootstrap-table.png?raw=true)

**Comment by sodatea** [comment]
https://cn.vuejs.org/v2/guide/components.html#解析-DOM-模板时的注意事项

**Comment by JounQin** [comment]
`<tr v-for="user in users" v-bind:user='user' is="user-tr"></tr>`
https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats

**Comment by ramwin** [comment]
谢谢，谢谢。我把这部分文档再看一遍。
