### ISSUE TITLE
Bound data value does not update as expected

### ISSUE THREAD

**Issue by monooso** [vuejs/vue#8387]
### Version
2.5.16

### Reproduction link
[https://codepen.io/experiencehq/pen/yEKMwv](https://codepen.io/experiencehq/pen/yEKMwv)

### Steps to reproduce
1. Create a new component, which expects a single property (in the example, `color`)
2. Create a `data` property, based on the bound property (`data-color`)
3. Create a `computed` property, based on the bound property (`computed-color`)
4. Note that the `data-color` and `computed-color` values are correct when the component is first loaded
5. Update the bound property value
6. Note that the `computed-color` value updates as expected, but **the `data-color` value does not update**

### What is expected?
The `data-color` value should change when the bound property upon which it is based changes, [as described in the documentation](https://vuejs.org/v2/guide/components-props.html):

> ...every time the parent component is updated, all props in the child component will be refreshed with the latest value.

### What is actually happening?
The `data-color` value does not change.

**Comment by zWingz** [comment]
'data-color' will not be synchronized with 'prop-color'

**Comment by ktsn** [comment]
The values specified in `data` is **initial** data, so it is expected the value will not be automatically updated. You should always use `computed` or manually update with `watch`ing `props` value.

**Comment by monooso** [comment]
@ktsn Thank you for the clarification. It may be worth updating the documentation to be more explicit regarding this limitation.
