### ISSUE TITLE
watch should add two more arguments to handler

### ISSUE THREAD

**Issue by simpleway2016** [vuejs/vue#8388]
### Version
2.5.16

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
data: {
    items:[]
},
watch: {
　　items: {
　　　　handler(newValue, oldValue) {
　　　　　　
　　　　},
　　　　deep: true
　　}
}

### What is expected?
i suggest add two arguments in handler, like this:

handler(newValue,  oldValue, propertyName, changedItemObject) {
　　　　　　
}

### What is actually happening?
when item's property changed,i can get the notify in handler,
but i don't know which property changed,which item's property changed

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue/issues/6640#issuecomment-330383928
