### ISSUE TITLE
Ternary operator misinterpretation in v-model attribute

### ISSUE THREAD

**Issue by bpstrngr** [vuejs/vue#8390]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/zmkt7ajy/178/](https://jsfiddle.net/zmkt7ajy/178/)

### Steps to reproduce
You can see how the ternary operator only evaluates to the 
"false" value for the v-model attribute, rendering the checkboxes 
"unwired" to the models in the "true" cases. 
Evaluating elsewhere, in a different attribute or inline 
(see checkbox labels and bottom `<span>` iteration) 
proves it's only an issue with the v-model's parser. 

### What is expected?
all checkboxes represent a model.

### What is actually happening?
"true" evaluations return no model entity. 

---
I have managed to insert a console logging for what the "true" evaluation returns, 
and it is as if the ternary operands were an object key-value pair. 
for example: 
`v-model="typeof item==='string'?model.strings:model.numbers" `
returns something like  `{model.strings:{numbers:[]}}` in case of "string" types.

also, in a previous stage of my actual code I could bypass this issue 
by varying the boolean expression (like checking for existence 
of property instead of type verification but after a heavy restructuring 
I can't reproduce it already. I went with separating the cases with v-if this time, but whatever). 
In a certain case then, the "true" operands were returned and referenced correctly.

**Comment by posva** [comment]
hmm, this would imply complexifying a lot the `parseModel` function and its usage in `compiler/directives/model` for a very specific use case that is against readability.

A more readable version would be to use `v-if`/`v-else` or create a component using a render function to handle it correctly:


```vue
    <div v-for="item in numbers.concat(strings)">
      <label>
        <input type="checkbox" v-if="typeof item === 'number'" :value="item" v-model="collection.numbers">
        <input type="checkbox" v-else :value="item" v-model="collection.strings">
        {{item}} ({{ typeof item }})
      </label>
    </div>
```

**Comment by posva** [comment]
As @znck told me, having an assignment with a ternary on the left-side is forbidden, which makes sense to disallow it in `v-model` as well:

```js
(true ? a : b) = 'value'
// Uncaught ReferenceError: Invalid left-hand side in assignment
```
