### ISSUE TITLE
Bubbled event

### ISSUE THREAD

**Issue by pal-software** [vuejs/vue#8392]
### What problem does this feature solve?
I think, that good idea (for many choices) to have separate method (or maybe parameter for $emit method) which generate bubbled events.
For very simple & quick example see code below (modified $emit). We can include this code to our javascript file & it will be work, but , i think good idea to have this method into vue...

..sorry for my bad English

### What does the proposed API look like?

Vue.prototype.$bubble_emit = function (event) {

    var vm = this;
    var args = toArray(arguments, 1);

    while ( vm && vm != null )
    {
        var cbs    = vm._events[event];

        if (cbs) {
            cbs = cbs.length > 1 ? toArray(cbs) : cbs;

            for (var i = 0, l = cbs.length; i < l; i  ) {
                try {
                    var result = cbs[i].apply(vm, args);

                    // if handler return `false`, then immediately exit
                    if ( result === false )
                    {
                        return this;
                    }

                } catch (e) {
                    handleError(e, vm, ("event handler for \""   event   "\""));
                }
            }
        }
        vm = vm.$parent;
    }
    return this;

    function toArray (list, start) {
        start = start || 0;
        var i = list.length - start;
        var ret = new Array(i);
        while (i--) {
          ret[i] = list[i   start];
        }
        return ret
      }
};

**Comment by posva** [comment]
This was removed on purpose because it makes things harder to track but it's doable on user land. I've seen a library for this But can't find it right now. I'll post it here is I find it

**Comment by pal-software** [comment]
very strange...  :)
you have $emit which make only one step to up & you can't to have method which make so steps to up how much developer to want.
i dont need library  i make it. (i include example to my post)
