### ISSUE TITLE
Ie11でメモリリークを解消したい（最小構成あり）

### ISSUE THREAD

**Issue by Ryuta-Yamaguchi** [vuejs/vue#8393]
以下の最小構成で、表示後に適当なinputタグに「111111」と入力し続けていくと、メモリ使用量が増加し続けます。
実際に運用している画面ではもっと複雑な構成としており、すぐに1GBに達してしまいます。
回避方法や改善は難しいでしょうか。

★入力前のメモリ状況
<img width="735" alt="default" src="https://user-images.githubusercontent.com/30860215/41725484-dfaa6542-75aa-11e8-8543-a68899293135.png">

★入力後のメモリ状況
<img width="737" alt="default" src="https://user-images.githubusercontent.com/30860215/41725501-ed7e7f14-75aa-11e8-8a29-ec7f72bc2470.png">

★入力状況
<img width="960" alt="default" src="https://user-images.githubusercontent.com/30860215/41725511-f58df306-75aa-11e8-8936-191fb7b967f5.png">

★最小構成HTML

    <!doctype html>
    <html class="no-js" lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>ﾒﾓﾘﾘｰｸ</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        <div id="test">
            <input type="text" v-model="test1">
            <input type="text" v-model="test2">
            <input type="text" v-model="test3">
            <input type="text" v-model="test4">
            <input type="text" v-model="test5">
            <input type="text" v-model="test6">
            <input type="text" v-model="test7">
            <input type="text" v-model="test8">
            <input type="text" v-model="test9">
            <input type="text" v-model="test10">
            ・・・test989まで続く
            <input type="text" v-model="test990">
            <input type="text" v-model="test991">
            <input type="text" v-model="test992">
            <input type="text" v-model="test993">
            <input type="text" v-model="test994">
            <input type="text" v-model="test995">
            <input type="text" v-model="test996">
            <input type="text" v-model="test997">
            <input type="text" v-model="test998">
            <input type="text" v-model="test999">
            <input type="text" v-model="test1000">
        </div>
        <script src="https://cdn.jsdelivr.net/npm/vue"></script>
        <script>
            let test = new Vue({
                el:     '#test',
                data:   {
                    test1:  null,
                    test2:  null,
                    test3:  null,
                    test4:  null,
                    test5:  null,
                    test6:  null,
                    test7:  null,
                    test8:  null,
                    test9:  null,
                    test10:  null,
                    ・・・test989まで続く
                    test990:  null,
                    test991:  null,
                    test992:  null,
                    test993:  null,
                    test994:  null,
                    test995:  null,
                    test996:  null,
                    test997:  null,
                    test998:  null,
                    test999:  null,
                    test1000:  null
                }
            });
        </script>
    </body>
    </html>

**Comment by kazupon** [comment]
@Ryuta-Yamaguchi
すいません。問題報告は、Issue helperからお願いできますか？

**Comment by kazupon** [comment]
@Ryuta-Yamaguchi
後、大変かもしれませんが、英語で問題内容報告頂きたいです。🙏
英語でコミュニケーションするのが基本なので。
