### ISSUE TITLE
 Ie 11 wants to eliminate memory leak

### ISSUE THREAD

**Issue by Ryuta-Yamaguchi** [vuejs/vue#8396]
### Version
2.5.16

### Reproduction link
[https://www.e-triad.co.jp/demo/vue](https://www.e-triad.co.jp/demo/vue)

### Steps to reproduce
As you continue typing "111111" into the appropriate input tag after display, the memory usage will continue to increase.

### What is expected?
Is it difficult to avoid or improve?

### What is actually happening?
In the actual operation screen, it has a more complicated configuration and it will reach 1 GB immediately.

---
I have not solved it.

Memory status before input
<img width="735" alt="default" src="https://user-images.githubusercontent.com/30860215/41750788-c57782e2-75f8-11e8-8723-57dacfc2c486.png">

Memory status after input
<img width="737" alt="default" src="https://user-images.githubusercontent.com/30860215/41750795-c9ef9d6e-75f8-11e8-91b3-5c6aa4036d04.png">

Input status
<img width="960" alt="default" src="https://user-images.githubusercontent.com/30860215/41750838-085a6336-75f9-11e8-8721-95ab5399f038.png">

**Comment by kazupon** [comment]
Thank you for your reporting!

Could you try to check with using Windows Performance Analyzer for two cases ?

###  About Windows Performance Analyzer
- English article: 
https://docs.microsoft.com/ja-jp/windows-hardware/test/wpt/windows-performance-analyzer
- Japanses article: 
https://blogs.msdn.microsoft.com/jpwdkblog/2014/11/28/windows-performance-analyzer/

### Cases
- case1: invoke developer tools
- case2: not invoke developer tools

It's breaking down the issue into tiny parts in order to find IE 11 developer tools is causing the memory leak.

**Comment by Ryuta-Yamaguchi** [comment]
I installed Windows Performance Analyzer.
But I do not know how to analyze. First try to use.

But look at the source of the URL being presented.
The memory leak is reproduced by merely increasing the number of items in the following minimum configuration.
I am thinking that I can manage somehow.

    <div id="test">
        <input type="text" v-model="test1">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script>
        let test = new Vue({
            el:     '#test',
            data:   {
                test1:  null
            }
        });
    </script>

**Comment by posva** [comment]
There is no leak in your demo... Maybe IE is waiting too long to release memory.

**Comment by Ryuta-Yamaguchi** [comment]
Thank you for confirmation.

We continued to identify leak points.
I modified the vue.js body and IE 11 was able to fix it to suppress memory expansion.

There is no problem in how to write vue.js, but it seems to be missing in IE11.
I recognized this as a bug in IE 11.

I will issue pullRequest for the first time, but I will organize and send the request.
Since I would like to use vue.js, it is good to integrate if you get confirmation.

**Comment by kazupon** [comment]
@Ryuta-Yamaguchi 
Thank you for your efforts.
We are waiting for your PR. :)

**Comment by marszoolong** [comment]
@Ryuta-Yamaguchi 
Hi man, did you push your PR?

I research the issue for a long time and i found the closures(computed items` get/set etc.) will make leak in IE11

**Comment by Ryuta-Yamaguchi** [comment]
I could not solve all the tests.
I do not do PR.
I banned the use of IE.
