### ISSUE TITLE
Cannot read property '$options' of undefined

### ISSUE THREAD

**Issue by falstack** [vuejs/vue#8398]
### Version
2.5.16

### Reproduction link
[https://sentry.io](https://sentry.io)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/16357724/41762256-c75c4dd4-762c-11e8-9a99-3defd5750138.png)

### What is expected?
no error

### What is actually happening?
error

### PS
1. 是非必现的，只在 sentry 上看到过，没有复现出来
2. 报错的都是 Android 设备，不排除 iOS 设备 crash 后无法上报的情况

**Comment by sodatea** [comment]
抱歉，不能复现的 bug 我们没有能力处理。

此类问题建议补充更多信息后到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

**Comment by dbFlower** [comment]
这两天sentry也在报这个问题， 突然就开始报了。 后续有找到解决方案吗？

**Comment by falstack** [comment]
@dbFlower 没有，ignore 了

**Comment by dbFlower** [comment]
@falstack  你是不是用了SSR 。 我用SSR ， 在 created 钩子里改了store的数据， 在HTML里用了v-if， 然后直接boom了。

**Comment by falstack** [comment]
@dbFlower 我在 App.vue 里设置了 i18n，并没有改变 store
``` javascript
  created() {
    this.$i18n.locale = this.$store.state.lang;
    if (this.$isServer) {
      return;
    }
    .... others
  },
```

**Comment by dbFlower** [comment]
@falstack  准确来说我是html里面用了store里的数据 

store 里： 
```js
{
   ...others,
   somethingVisible: true,
   ...others,
}
```
html 里
```vue
<a v-if="somethingVisible">some text</a>
```

created 钩子里

```js
export default {
  created() {
    this.$store.commit('app/setAppState', { somethingVisible: false }) // 假装更改了上方的store内数据
  }
}
```

加上SSR , 就产生了上述问题。
