### ISSUE TITLE
Is Vue development stale?

### ISSUE THREAD

**Issue by edwin-egalite** [vuejs/vue#8407]
### What problem does this feature solve?
The last beta version 2.5.17 was released more than 3 months ago and we've been using it in our production project ever since. We did not encounter issue thus far. However, it seems like the development of Vue js has become stale.

### What does the proposed API look like?
Would like to know the roadmap and future of this great project.

**Comment by Justineo** [comment]
See https://github.com/vuejs/roadmap.

**Comment by sodatea** [comment]
See also https://github.com/vuejs/vue/issues/8360#issuecomment-397558863

**Comment by edwin-egalite** [comment]
Noted with thanks.
