### ISSUE TITLE
v-if syntax enhancement

### ISSUE THREAD

**Issue by jialj** [vuejs/vue#8411]
### What problem does this feature solve?
I can add different events, attributes, etc. based on conditions on an element instead of writing multiple elements.

### What does the proposed API look like?
```html
<div v-if="condition"  @change="fun()" v-if-end  .....>...</div>
```

**Comment by posva** [comment]
Thanks for the proposal but this will rely on attribute order.
Instead, use a computed property and bind it with `v-bind="myComputedProperties"`. Same with events, an object of events bound with `v-on="myComputedEvents"`
