### ISSUE TITLE
Event hooks for components inside of transitions

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue#8412]
### What problem does this feature solve?
Please have a look at this jsfiddle:
https://jsfiddle.net/4m70p3hr/

In my project I have components inside of transitions. And I need to know inside of the component when the transition is done.

I've read somewhere else that "Reusable Transitions" might help, and it's actually working for this event approach I've implemented in the fiddle. Yet directly mutating the prop would be less code. But that gives me a warning "`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.`" when I try to directly access the prop of the slot. Meh.
Anyway: both approaches doesn't look nice to me.

So I wonder what's the best way to achieve this, or if it wouldn't be nice to have some dedicated hooks for that already inside the children components:

### What does the proposed API look like?
Inside of my-component just fire the transition events of the direct parent transition, so we can use `$on('afterEnter')`.

**Comment by posva** [comment]
This is doable in userland in a reusable transition by providing the state of the transition in a scoped slot, so you end up writing something like this:


```vue
<my-transition>
  <template slot-scope="{ finished }">
    <my-component v-if="finished"></my-component>
    <div v-else>Is loading...</div>
  </template>
</my-transition>
```
