### ISSUE TITLE
Updating the docs around scoped slots and the render function

### ISSUE THREAD

**Issue by kayandrae07** [vuejs/vue#8416]
### What problem does this feature solve?
I have been using scoped slots during development a lot lately and noticed that a lot is missing from the documentation regarding them.

For example, it's not immediately obvious you can name scoped slots. I'd also like to add more on working with the render function.

Should I go ahead and make a PR for this?

### What does the proposed API look like?
Well, i'll update the docs.

**Comment by posva** [comment]
You should check if there is any prs first and if there's not create a PR to start a discussion about the possible improvements (in the right repository 😉 )

**Comment by kayandrae07** [comment]
Oh right! My bad, thanks.
