### ISSUE TITLE
Use 'for loop' instead of 'forEach', maybe we can have better performance.

### ISSUE THREAD

**Issue by liuzeyafzy** [vuejs/vue#8417]
### What problem does this feature solve?
To increase performance. One order of magnitude or more.

See:
https://jsperf.com/fast-array-foreach
https://jsperf.com/loop-test-aamulumi/1

### What does the proposed API look like?
None of new API, just better performance

**Comment by posva** [comment]
We do use for loops in most places, specially perf critical places. If you find anywhere where switching to a for loop would increase the performance we are happy to review a pr with the corresponding perf benchmarks comparison  🙂
