### ISSUE TITLE
对存储了对象的数组使用 filter 方法，将结果赋值给数据属性，结果是深拷贝而不是浅拷贝

### ISSUE THREAD

**Issue by GurifYuanin** [vuejs/vue#8420]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/gurifyuanin/jh4pcey0/](https://jsfiddle.net/gurifyuanin/jh4pcey0/)

### Steps to reproduce
大致如链接， store.state.items 是一个对象集合的数组，比如 [{name: 'a'}, {name: 'b'}, {name: 'c'}]
dispatch('pop', item) 是使用 splice 方法将 store.state.items 弹出一个 item 元素

### What is expected?
当dispatch('pop', item) 时，只有 store.state.items 弹出一个元素，组件内的 this.items 没有弹出元素

### What is actually happening?
在组件内的 this.items 也应该同步更新，也弹出了一个元素

---
但是当对数据属性 items 不使用 filter(element => true) 而是直接赋值时
```
data () {
    return {
        items: this.$store.state.items
    }
}
```
响应正常，对 store.state.items 的操作对组件内的 this.items 也同样有效。

**Comment by yyx990803** [comment]
重现的要求是 **可以真的跑起来**，请别偷懒。

**Comment by GurifYuanin** [comment]
抱歉，已经按照要求更新了代码
[https://jsfiddle.net/gurifyuanin/o5n0dcx3/](url)

点击 li 删除 store.state 的 item，视图没有做出反应
只有当点击 update it 按钮，将 store.state.items 赋值给 vm.items 时才更新视图

**Comment by jacekkarczmarczyk** [comment]
corrected link: https://jsfiddle.net/gurifyuanin/o5n0dcx3/

**Comment by JounQin** [comment]
将 `data` 改为

``` js
computed: {
  items() {
    return store.state.items.filter(el => true)
  }
}
```

---

`filter` 后产生新数组，所以不是响应式的。

**Comment by GurifYuanin** [comment]
好的，已解决，感谢帮忙。
