### ISSUE TITLE
Private properties prefixed with `$_` (dollar underscore) are not available inside component

### ISSUE THREAD

**Issue by adriangoransson** [vuejs/vue#8432]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/jfyLx256/](https://jsfiddle.net/jfyLx256/)

### Steps to reproduce
Prefix a property with `$_` and try to reference it within the component or template.

### What is expected?
`$_` prefixed properties should be rendered in template and available within the component.

### What is actually happening?
`$_` props are undefined. Not rendered in template and `undefined` in component logic.

---
Private property names are described in the Vue style guide and the `$_` form is officially recommended. https://vuejs.org/v2/style-guide/#Private-property-names-essential.

I first noticed this in a project built with vue-cli@3.0.0-beta.16.

**Comment by posva** [comment]
This is expected: https://vuejs.org/v2/api/#data, You can access them with `$data.$_foo`

**Comment by posva** [comment]
@chrisvfritz do you think we should add a note about them not being proxied in the style guide?

**Comment by adriangoransson** [comment]
I definitely think this should be mentioned in the style guide. I've been using Vue for about six months now and until now didn't know about `$data` because I never needed to.

I can't recall any place in the documentation where it's actually used either, so I'd wager most people have forgot about it if they ever read it.

**Comment by adriangoransson** [comment]
Actually... Since these property names are recommended and at least according to the style guide guaranteed to not conflict with Vue, doesn't it make more sense to just proxy them?

**Comment by posva** [comment]
We had a discussion about this in a PR. Unfortunately, I don't remember which PR it was nor I remember the final outcome 😆

**Comment by trafium** [comment]
Encountered this behaviour because I just started to follow style guide more thoroughly. So now I seemingly should fill my mixins' methods/computed/hooks with messy stuff like `this.$data.$_mixinName_itemName` everywhere, which, in my opinion, unnecessarily hurts readability since, as @adriangoransson said, conflicts are not expected in this situation.

**Comment by Justineo** [comment]
@VitorLuizC

https://vuejs.org/v2/api/#data
