### ISSUE TITLE
V-html to replace containing element

### ISSUE THREAD

**Issue by dysol** [vuejs/vue#8437]
### What problem does this feature solve?
Redundant element in DOM

### What does the proposed API look like?
Right now v-html appends rawHTML into the container like this:
```
<div v-html="rawHTML" /> renders into - - - -> <div> <p> ... </p> </div>
```

How about an option to "replace" container instead of appending? Here's how it looks like:

```
<div v-html.replace="rawHTML"/> renders into ----> <p> ... </p>
```

Thoughts?

**Comment by posva** [comment]
This is because of the behaviour of v-html: setting `innerHTML`. Replacing the whole node could be problematic regarding current Vue limitation of one single root node
This should be doable in userland though (not reactive though)

```js
Vue.directive('replace-html', {
  inserted(el, {
    value
  }) {
    el.insertAdjacentHTML('afterend', value)
    el.parentElement.removeChild(el)
  }
})
```
