### ISSUE TITLE
Erro to import element-ui on vuejs jest test

### ISSUE THREAD

**Issue by valterbarros** [vuejs/vue#8439]
### Version
2.5.2

### Reproduction link
[https://github.com/valterbarros/trackthings](https://github.com/valterbarros/trackthings)

### Steps to reproduce
run yarn install and yarn test

### What is expected?
I'm trying to import element-ui inside my test to compile the template from my newlist component

### What is actually happening?
This error is happening

SyntaxError: Invalid or unexpected token

    > 1 | import { mount, shallowMount, createLocalVue } from '@vue/test-utils'
      2 | import Vue from 'vue'
      3 | import NewList from '@/components/NewList'
      4 | import ElementUI from 'element-ui'; 
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (test/unit/specs/NewLists.spec.js:1:116)

---
I tried a bunch of ways to solve this but without success, and I'm very new in vuejs ecosystem but with a good experience in javascript. I'm using the default webpack template from vuejs cli to build this project and jest to test.

This error only appear when I add Vue.use(ElementUI)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by valterbarros** [comment]
Problem solved with this https://github.com/ElemeFE/element/issues/11811
