### ISSUE TITLE
Client bundle script tag gets injected more than once when there are async components with Vue Router

### ISSUE THREAD

**Issue by gorkemkinik** [vuejs/vue#8440]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/kkrmo99l23](https://codesandbox.io/s/kkrmo99l23)

### Steps to reproduce
* Configure vue ssr with router and lazy loaded components.
* There should be at least one lazy loaded component, configured in routes
* Use client and server manifest generation.
* Client manifest looks like

  "all": [
    "about.js",
    "client.js",
    "register.js",
    "0.js",
    "1.js",
    "manifest.js",
    "index.html"
  ],
  "initial": [
    "client.js"
  ],`

### What is expected?
register.js is the lazy loaded bundle,
client.js is the client-entry bundle

Expected scripts tags in html are:

```
<script src="/client.js" defer></script>
<script src="/register.js" defer></script>
```

### What is actually happening?
```
<script src="/client.js" defer></script>
<script src="/register.js" defer></script>
<script type="text/javascript" src="/client.js"></script>
```

---

*The repro url does not reproduce the issue. Not sure how to setup server side script tag injection in a sandbox*

Other related module versions

"vue-server-renderer": "^2.5.16",
"vue-loader": "^15.2.4",
"vue-router": "^3.0.1",

node 8.11.2

**Comment by posva** [comment]
Please provide a repro in a github repository if that makes it easier 🙂 
Closing until a repro is provided
