### ISSUE TITLE
Sponsor URLs give a 404

### ISSUE THREAD

**Issue by mbarbine-r7** [vuejs/vue#8447]
### Version
2.5.17-beta.0

### Reproduction link
[https://opencollective.com/vuejs/tiers/platinum-sponsors/1/website](https://opencollective.com/vuejs/tiers/platinum-sponsors/1/website)

### Steps to reproduce
open chrome 
navigate to https://vuejs.org/ 
Click "Become a sponsor" 
which redirects to -  https://opencollective.com/vuejs/tiers/platinum-sponsors/1/website

### What is expected?
a way to become a sponsor

### What is actually happening?
404 not found

---
Same behavior for gold sponsor, but not patreon sponsors

**Comment by yyx990803** [comment]
This seems to be a bug on OpenCollective's side.

**Comment by yyx990803** [comment]
If you are interested in becoming a sponsor, you can do it either on [Patreon](https://www.patreon.com/evanyou) or at [OpenCollective](https://opencollective.com/vuejs).

**Comment by mbarbine-r7** [comment]
Thanks!


We are looking at incorporating Vue into some of our apps.

I’m not saying that it’s something I wouldn’t consider, but It was not something that I had planned. I happened to be poking around and notice the 404 (twice) and thought I would share that. This was the best way. No way to tell whether I would have busted out the amex and signed up right away at this point 😉

Also - Thanks for the fast response!



Michael Barbine
Rapid7 Managed Services
200 Daingerfield Rd, Suite 300
Alexandria, VA. 22314
540.671.1261
