### ISSUE TITLE
component rendered but methods are not working

### ISSUE THREAD

**Issue by jadvillafania** [vuejs/vue#8449]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/441137/](https://jsfiddle.net/50wL7mdz/441137/)

### Steps to reproduce
I am encountering a weird issue where the components are getting rendered but the methods are not triggering. I have the following set up

// default app.js from laravel
```
Vue.component('test', require('./components/test.vue'));
const app = new Vue({
    el: '#app'
});
```

//on my index.php
```
<div id="app">
<test></test>
</div>
```

//test.vue
```
<template>
	<div>
		<button @click="testclick">Click Me!</button>
	</div>
</template>
<script>
	export default {
		methods: {
			testclick() {
				alert('hello world');
			}
		}
	};
</script>
```

### What is expected?
Everything is as straight forward as that. However, the "testclick" function is not triggering at all. When I open the debug tool on Chrome, there is no 'test' component under the <Root>. On my other projects, other components are showing there.

### What is actually happening?
I first encountered the issue at version 2.5.7. I tried updating all npm packages but still not working as expected.

---
The provided JSFiddle is working properly, so I don't know where the real problem is.

**Comment by sodatea** [comment]
Please provide a valid reproduction when opening an issue.

Next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
