### ISSUE TITLE
Use typescriptin vue, when overide one method in child component, in this method cannot call parent method?

### ISSUE THREAD

**Issue by hesi726** [vuejs/vue#8452]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/443179/](https://jsfiddle.net/50wL7mdz/443179/)

### Steps to reproduce
a. setup vue-cli <br/>
b. create a typescript project <br/>
d. accord the https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/111 , create vue.config.js file and write content. <br/>
g. split HelloWorld.vue to HelloWorld.ts and HelloWorld.vue , <br/>
accord   https://jsfiddle.net/50wL7mdz/443279/    modify HelloWorld.ts and HelloWord.vue.<br/>

h. run yarn run serve, then access the http://localhost:8080, click the Test Button, you can find the error in console.

### What is expected?
console should log the "before_value_changed in base"

### What is actually happening?
some error happened.

---

I create two vue class , and one extends other and override one method, 
in this method of child vue class,  i use super.xxx  to call this method of parent class, 
it will error.
It works fine for typescript.  (followed code at http://www.typescriptlang.org/play/index.html,  ) 

class BaseComponent {    
    public before_value_changed() {
    }
    public on_value_changed() {
        this.before_value_changed();
        return "Hello, ";
    }
}

class HelloWorld extends BaseComponent {
    public before_value_changed() {
        console.log('beforeGreet');
        super.before_value_changed();        
    }
}
let hello = new HelloWorld();

let button = document.createElement('button');
button.textContent = "Say Hello";
button.onclick = function() {
    alert(hello.on_value_changed());
}
document.body.appendChild(button);

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-class-component/issues/93#issuecomment-299383043
