### ISSUE TITLE
how to create a recursive component use render function?

### ISSUE THREAD

**Issue by m430** [vuejs/vue#8454]
### What problem does this feature solve?
I want to create a `NestedTable` component use iview2 tables,  iview table define the columns that can use `render` function, but i want to render a `NestTable` in that `render` function. but I don't know how to do it. I think maybe vue.js can render a recursive component use render function, but I can't find anything for it.

### What does the proposed API look like?
```javascript
<template>
    <Table :columns="columns" :data="data"></Table>
</template>
<script>
export default {
  name: 'NestedTable',
  props: ['data'],
  data() {
    return {
      columns: [
        {
          type: "expand",
          width: 50,
          render: (h, params) => {
            let row = params.row;
            return (
               <NestedTable data={params.row.children}></NestedTable>
            );
          }
        }
      ]
    };
  }
};
}
</script>
```

**Comment by AfterThreeYears** [comment]
Recursive functions need stop conditions, but it looks like you have none.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
