### ISSUE TITLE
global is undefined

### ISSUE THREAD

**Issue by Arichy** [vuejs/vue#8455]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/449624/](https://jsfiddle.net/50wL7mdz/449624/)

### Steps to reproduce
When you open it, it will just alert the bug.
And I used `document.write` to show it on html, though it sometimes doesn't work.

### What is expected?
The code should run correctly

### What is actually happening?
TypeError happened.

---
I'm using ES6 syntax import to import Vue.js in Safari (script[type=module]) ,but it seems the module closure makes 'this' of top level point undefined so global becomes undefined rather than window.
In order to show the bug clearly, I used dynamic import instead of static import on JSFiddle.

**Comment by sqal** [comment]
https://github.com/vuejs/vue/pull/7110

**Comment by posva** [comment]
The browser module version is another one: https://unpkg.com/vue/dist/vue.esm.browser.js
But please, refer to https://github.com/vuejs/vue/pull/7110 to track this :slightly_smiling_face:
