### ISSUE TITLE
v-bind shorthand for equal property and attribute name

### ISSUE THREAD

**Issue by CyberAP** [vuejs/vue#8457]
### What problem does this feature solve?
Sometimes we're binding attributes to the props that have exactly the same name. So we could simplify `v-bind:attr="attr"` or `:attr="attr"` to just this: `:attr`.

### What does the proposed API look like?
```html
<Component :attr />
```
Equals to
```html
<Component :attr="attr" />
```
Equals to
```html
<Component v-bind:attr="attr" />
```

**Comment by JounQin** [comment]
https://github.com/vuejs/vue/pull/2877#issuecomment-226618510

**Comment by CyberAP** [comment]
Haven't found that in google results. Thanks.

**Comment by leopiccionia** [comment]
With ES6 syntax, you can write:
```vue
<Component v-bind="{ foo, bar, baz}" />
```
That's equivalent to:
```vue
<Component :foo="foo" :bar="bar" :baz="baz" />
```
More details on [Vue API docs](https://vuejs.org/v2/api/#v-bind).

**Comment by CyberAP** [comment]
@leopiccionia, thanks!

**Comment by Mouvedia** [comment]
@leopiccionia can you handle camelcase to kebabcase conversion automatically ?

**Comment by vis97c** [comment]
Vue 3.4 now supports this feature. See https://github.com/vuejs/core/pull/9451 or the [Announcement](https://blog.vuejs.org/posts/vue-3-4#v-bind-same-name-shorthand)
