### ISSUE TITLE
domProps innerHTML does not work with svgs in IE 11

### ISSUE THREAD

**Issue by jnields** [vuejs/vue#8459]
### Version
2.5.16

### Reproduction link
[https://codepen.io/anon/pen/vrqYEG](https://codepen.io/anon/pen/vrqYEG)

### Steps to reproduce
Set `domProps: { innerHTML }` of svg tag and it will not work in IE

### What is expected?
SVG should contain provided HTML

### What is actually happening?
SVG contains no HTML

---
React had the same issue a while ago
https://github.com/facebook/react/issues/10013

**Comment by posva** [comment]
innerhtml is not supposed to work with svg(per spec). See https://github.com/vuejs/vue/issues/5310#issuecomment-290006053
But apparently there is a shim that would allow you to set it when I did a quick search
