### ISSUE TITLE
hydrate method possible to allow clientside vuejs or specific components of a vue ssr page

### ISSUE THREAD

**Issue by Askoth** [vuejs/vue#8460]
### What problem does this feature solve?
I work in an e-commerce that does a lot of A/B test. Our css and js bundles tend to increase in size and we are always trying to reduce them.

We are now looking into some options for isomorphic templates in js and I think it's curious most of the other ones have a way to hydrate from the client js code.

What I'm looking for here is to send less code to client and only necessary code. Apart from bundle size I'm also considering https://medium.com/dev-channel/the-cost-of-javascript-84009f51e99e

If I use vuejs as framework to write all my templates in server side (code consistency, less time teaching developers multiple technologies and other benefits) I will end up with:
- some static pages (such as documentation or FAQ) 
- some very dynamic pages (search, e-commerce catalogs)
- some hybrid pages (might be such as a static page with a options for signup and search with some validation and/or autocomplete inside)

When I try to create js bundles to send to the customer I'm trying to keep only the necessary js code with tree shaking and import of modules based on components used.

From what I understood from https://ssr.vuejs.org/guide/hydration.html the attribute that will tell vuejs that this application needs to be hydrated is created in the ssr version and is only available in the wrapper element of the application. This means that the only way to do hydration is to send the whole page app (SPA isn't something possible in the following years). If I want to force hydration of specific components I'll have to manually add this attribute to each one myself (a hack that would increase risk of bad implementations).

I like the way [Reactjs has a .hydrate method](https://reactjs.org/docs/react-dom.html#hydrate) or how Svelte [has a hydration flag](https://svelte.technology/guide#hydration). This way I can just ship a small component as part of the js bundle and initialize in the way I want.

### What does the proposed API look like?
As it seems the clientside vuejs doesn't use any extra configuration and only read the attribute right now, I guess this could be done with a flag when creating the Vue instance.

```
var app = new Vue({
  hydrate: true,
  el: '#my-specific-component',
  data: {
    message: 'Hydrated!'
  }
})
```

or maybe this can be done in vue config (at least for my case).

```
Vue.config.hydrate = true;
```

**Comment by chrisvfritz** [comment]
This is possible by passing `true` to the `hydrating` argument of `$mount`, e.g.:

```js
app.$mount('#app', true)
```

Improving the [docs for this here](https://github.com/vuejs/vue-ssr-docs/). 🙂
