### ISSUE TITLE
v-model not working inside jquery steps plugin 

### ISSUE THREAD

**Issue by bedus-creation** [vuejs/vue#8470]
I have jquery steps and form input. I have used v-model to bind input to vue data. It works perfect if i don't initialize jquery steps plugin. But When i Initialize jquery steps plugin v-model cannot bind the input.

I think jquery steps is rerendering the html tags so that v-model could not access that input . But is there any way to bind v-model to input inside such plugin ??

**Comment by codebeginer** [comment]
> I have jquery steps and form input. I have used v-model to bind input to vue data. It works perfect if i don't initialize jquery steps plugin. But When i Initialize jquery steps plugin v-model cannot bind the input.
> 
> I think jquery steps is rerendering the html tags so that v-model could not access that input . But is there any way to bind v-model to input inside such plugin ??

You can check if vue app is initialise or not when steps get changes
`onStepChanged: function(event, currentIndex, priorIndex) {
				if(currentIndex == 3) {
					const mountPoint = document.querySelector("#selector");
					if (mountPoint && mountPoint.__vue_app__ === undefined) {
						// Vue app is not initialized, initialize it
						initVueApp();
					} else {
						// Vue app is already initialized
						console.log('Vue app is already initialized!');
					}
					
				}
			},`
