### ISSUE TITLE
keep-alive with router-view not working in my scene

### ISSUE THREAD

**Issue by leixu2txtek** [vuejs/vue#8471]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/leixu2txtek/e2vtyw5n/42/](https://jsfiddle.net/leixu2txtek/e2vtyw5n/42/)

### Steps to reproduce
1. click foo
2. click child
3. click foo (hi is print)
4. click bar
5. click foo (first show mounted and show hi after 300ms)
6. click child
7. click foo (should be hi but like step 5 )

### What is expected?
foo component render by cache

### What is actually happening?
foo component  render with full lifecycle

---
if I destroy component  with manually , keepAlive's cache not removed.

**Comment by leixu2txtek** [comment]
If in debugger mode , I remove cache[key] that be destroyed with console ,and that's ok for me .

**Comment by LinusBorg** [comment]
from the api docs:

> The match is first checked on the component’s own name option, then its local registration name (the key in the parent’s components option) if the name option is not available. **Anonymous components cannot be matched against**.

**Comment by leixu2txtek** [comment]
@LinusBorg  If i set the name on components , problem still there.

**Comment by LinusBorg** [comment]
Not for me: https://jsfiddle.net/e2vtyw5n/51/

**Comment by LinusBorg** [comment]
Okay, seeing the issue now.

**Comment by leixu2txtek** [comment]
@LinusBorg  Thanks for you reply ,  I tested https://jsfiddle.net/e2vtyw5n/51/. and problem still there..

Maybe you don't understand what I am faceing.

The **importrant** is step 4,5,6,7, and still call mounted

**Comment by LinusBorg** [comment]
Yeah got it now. I assume manually destroying a component from like that messes with the ache of keep-alive ....

**Comment by leixu2txtek** [comment]
If I use the debug mode to manually clear the destroyed component cache, it will be cached again, and all is ok.

so this problem caused by destroy but cache not be cleard ?

**Comment by LinusBorg** [comment]
That's what I suspect, yes

**Comment by leixu2txtek** [comment]
Example above 

from /foo/ to /foo/id/  the **Foo** component is cached by keep-alive.
then from /foo/ to /bar/  the **Foo** component is destroyed by mixin
then from /bar/ to /foo/ , the **Foo** component still cached by keep-alive 

Note the exclamation point below...

```javascript
function render () {
    var slot = this.$slots.default;
    var vnode = getFirstComponentChild(slot);
    var componentOptions = vnode && vnode.componentOptions;
    if (componentOptions) {
      // check pattern
      var name = getComponentName(componentOptions);
      var ref = this;
      var include = ref.include;
      var exclude = ref.exclude;
      if (
        // not included
        (include && (!name || !matches(include, name))) ||
        // excluded
        (exclude && name && matches(exclude, name))
      ) {
        return vnode
      }

      var ref$1 = this;
      var cache = ref$1.cache;
      var keys = ref$1.keys;
      var key = vnode.key == null
        // same constructor may get registered as different local components
        // so cid alone is not enough (#3269)
        ? componentOptions.Ctor.cid + (componentOptions.tag ? ("::" + (componentOptions.tag)) : '')
        : vnode.key;

// !!!!!!!delete cache[78] and go else!!!!!!!!
      if (cache[key]) {
        vnode.componentInstance = cache[key].componentInstance;
        // make current key freshest
        remove(keys, key);
        keys.push(key);
      } else {
        cache[key] = vnode;
        keys.push(key);
        // prune oldest entry
        if (this.max && keys.length > parseInt(this.max)) {
          pruneCacheEntry(cache, keys[0], keys, this._vnode);
        }
      }

      vnode.data.keepAlive = true;
    }
    return vnode || (slot && slot[0])
  }
```

**Comment by LinusBorg** [comment]
couldn't you use the `activated` hook to "simulate" what `mounted` does, so that you don't have to destroy the component at all?

**Comment by leixu2txtek** [comment]
Why I destroy component:

keep-alive will cached all component if no any condition eg. include/exclude/v-if ...

I destroyed component condition is 

/foo/ -> /foo/id   will not destroyed, because if i return (go(-1)) ,/foo/ need keep all status ;

/foo/ -> /bar/   should destroyed, because if i return (go(-1)), /foo/ need init all status;

Summary is

From the parent url to the subset url, there is no need to destroy the parent, because when returning from the subset, you need to keep the original state.

Ps: parent url, subset url similar to restful url

**Comment by leixu2txtek** [comment]
https://forum.vuejs.org/t/how-to-destroy-a-vuejs-component-that-is-being-cached-by-keep-alive/27132

**Comment by leixu2txtek** [comment]
@LinusBorg 

https://github.com/vuejs/vue/pull/7151/commits/ada25171af85a8d2e76e22a4cc61c06e9d9ab1f3

This PR commit failed ,but it's work for me .

Can you think about this PR in few minutes? Thanks a lot.

**Comment by posva** [comment]
You are asking for a way to prune cache in keep-alive like in #6509  and #8161 
You can check there for the reasons this is not possible

---

On top of @LinusBorg recommendation, you can also extract the state into a store, but I cannot tell without looking at your codebase and this becomes a question, which should be posted in the relevant channels (forum, discord, stackoverflow)

**Comment by Tech-Nomad** [comment]
It is not fully related to the question but as this page is among the first search-results on google when searching my problem, so I would like to add this note for others who have the same problem as I had: 
You have to use the :key directive to update a component using keep-alive and router-view together with params in the route path like  /blog/:slug

```
<keep-alive>
        <router-view :key="$route.fullPath"></router-view>
    </keep-alive>
```

With this Vue finally updates any new blog posts but caches the previously loaded. Otherwise only the first loaded blog post will be served even the blog/:slug changes all the time.

See also:
https://vuejs.org/v2/api/#key
https://stackoverflow.com/questions/52847979/what-is-router-view-key-route-fullpath

**Comment by posva** [comment]
@Tech-Nomad hey, that's not a good generic solution as it will **always** recreate router-view based on **any** change in the url, including query or hash. I hid it to prevent users from copy pasting what could be a harming solution in many cases
