### ISSUE TITLE
Actual use in v8js with ssr

### ISSUE THREAD

**Issue by AlexeyTcapaev** [vuejs/vue#8474]
### What problem does this feature solve?

At the moment when using SSR With V8JS it was possible to create an environment with working vue-router, vuex, vue-meta (no-ssr) and importing styles from components, as an example:
mix.options ({
    extractVueStyles: true
});
At the moment, there is a problem with vue-meta and lazy-load.

How much is it possible to use today?

### What does the proposed API look like?
just for me ,idk how it can be usable

**Comment by posva** [comment]
Take a look at https://github.com/vuejs/vue/issues/4101 Some people seem to made this work
If there is a problem with other libraries, you should tell them so they can make their libraries SSR compatible :smile:

**Comment by AlexeyTcapaev** [comment]
@posva ty)
