### ISSUE TITLE
Data access with dynamic components

### ISSUE THREAD

**Issue by graindeweb** [vuejs/vue#8475]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eywraw8t/151906/](https://jsfiddle.net/eywraw8t/151906/)

### Steps to reproduce
There are 2 dynamic components.
Click on the link "Switch to Table" to switch presentation from list component to table component

### What is expected?
Contact table should be filled with data from contacts object: "firstname", "lastname".
The contact's picture should be displayed too.

### What is actually happening?
Only data called inside html tags are available. Data called in mustache tags are empty.

{{contact.img_path}} does not show anything
whereas
<img :src="contact.img_path" /> works great

**Comment by sodatea** [comment]
Move the two `<script type="text-x-template">` blocks out of `<div id="app">` and everything works great.
