### ISSUE TITLE
Vue reactivity doesn't work with contenteditable elements 

### ISSUE THREAD

**Issue by MehrdadKhanzadeh** [vuejs/vue#8477]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/468838/](https://jsfiddle.net/50wL7mdz/468838/)

### Steps to reproduce
Edit the first div content.

### What is expected?
Because of reactivity, the "message" variable should update itself and we see the second div content changing.

### What is actually happening?
The "message" variable doesn't update, so the second div content not changing.

---
I don't if It's a bug or just something that is not a feature, but I saw that reactivity doesn't work this way.

**Comment by posva** [comment]
This is working as expected. You have to listen for events emitted by the contenteditable event. By default, the binding will be one way only
