### ISSUE TITLE
component inheritance problem

### ISSUE THREAD

**Issue by wahengchang** [vuejs/vue#8479]
I have searched most of the resource online, but did not found anything helps. 

I have a Base component, Base.vue

```js
//Base.component
<template>
  <div id="canvas-container" />
</template>
<script>
export default {
  created: function(){
    this.initCanvas()
  },
  methods: {
    initCanvas: function(){
        //...
    },
    drawing: function(sketch){
        //... this is the part need to be inherited
    }
  }
}
</script>
```

I got another component: Square.vue, which extend Base.vue

```js
//Base.component
<script>
import Base from './Base.vue';
export default {
  methods: {
    drawing: function(sketch){
        // overwrite Base.methods.drawing, or extend it
        // super.drawing()
    }
  }
}
</script>
```

Is it possible to implement in Vue? How ?

**Comment by zanedev** [comment]
@wahengchang use the mixins feature: https://vuejs.org/v2/guide/mixins.html

**Comment by wahengchang** [comment]
as all the research i did on line, i think mixin is the only one solution.

just feeling weird to a `react` user moving to `vue.js`, a class cant be extend, and the functions can not call `super.fun`
