### ISSUE TITLE
component inheritance problem

### ISSUE THREAD

**Issue by wahengchang** [vuejs/vue#8480]
### What problem does this feature solve?
component inheritance

### What does the proposed API look like?
```js
import ClassB from'./classB'

export default ClassA extend ClassB {
   method: {
      foo: function (param){
            doSomethingBefore()
            super.method.foo(param)
      }
   }
}
```

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue/issues/2371#issuecomment-186238466
Note: even with [vue-class-component](https://github.com/vuejs/vue-class-component/), we still prefer composition over inheritance, and there are some caveats calling parent methods from child class, as noted in https://github.com/vuejs/vue-class-component/issues/93#issuecomment-299383043
