### ISSUE TITLE
Vue component in v-for does not inject data properties to render method after array of v-for is updated

### ISSUE THREAD

**Issue by michalhlavka** [vuejs/vue#8483]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/21am3tc7/34/](https://jsfiddle.net/21am3tc7/34/)

### Steps to reproduce
Click on Add button

### What is expected?
The first component should have checked first option label on value = 0

### What is actually happening?
The first component has `data.type = 0` but no option label is checked after Add button is clicked

**Comment by posva** [comment]
Your problem comes from the radio buttons all having the same name. Try removing the attribute `name` 😉

**Comment by michalhlavka** [comment]
@posva thanks for fast response, you are absolutely right, I were blind. Thanks.
