### ISSUE TITLE
Vue wont update date-type input when it is disabled (only Firefox)

### ISSUE THREAD

**Issue by mu4ddi3** [vuejs/vue#8486]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/9jvk6mykwy?module=%2Fsrc%2Fcomponents%2FDateProblem.vue](https://codesandbox.io/s/9jvk6mykwy?module=%2Fsrc%2Fcomponents%2FDateProblem.vue)

### Steps to reproduce
Open code pararell in Chrome and FF. 

Take a fun with SET NOT EMPTY and SET EMPTY buttons.

Notice that in FF, when empty value is set for a date field - it wont update the view

### What is expected?
Should update view to "dd.mm.rrrr" state like in Chrome where it working good.

### What is actually happening?
In FF view is not updated when setting empty string to a disabled date-type field.

**Comment by posva** [comment]
Unfortunately, this is a problem coming from Firefox, setting the input value to an empty string doesn't reset the value when the input is disabled. You should file a bug in their bug tracker (if it doesn't exist already)

In the meantime you can workaround it by enabling it and directly setting the value:

```js
this.$refs.date.disabled = false
this.$refs.date.value = ''
this.date = ''
this.$refs.date.disabled = true
```

(I added a `ref="date"` to the date input)
