### ISSUE TITLE
Drag and Drop events not working in element ui

### ISSUE THREAD

**Issue by prasanthmaran1** [vuejs/vue#8487]
Hi folks,
i just working in the Vue.js, Vue events like (@drag , @dragstart ....) this type of events not working in the element ui components. and its working in the normal <div> HTML elements. 

Element ui ==> https://element.eleme.io/#/en-US

**Comment by Justineo** [comment]
@prasanthmaran1 [Binding Native Events to Components](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components)
