### ISSUE TITLE
SSR with third-part-plugin(vue-progressbar) but got "virtual DOM tree is not matching" waring

### ISSUE THREAD

**Issue by novay55555** [vuejs/vue#8503]
### Version
2.5.16

### Reproduction link
[https://github.com/novay55555/vue-ssr-startup](https://github.com/novay55555/vue-ssr-startup)

### Steps to reproduce
1. git clone reposition
2. install dependencies
3. npm start and visit http://localhost:3000

### What is expected?
No vue waring in the console

### What is actually happening?
There is a warning in the console "[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."

---
OS: win10 professional 17134.112

The third-part-plugin(vue-progressbar) only wraps a div, so I have no idae why warning happend

**Comment by Justineo** [comment]
> If not to use <vue-progress-bar /> in App.vue, this waring will not happen

I think you should report it to vue-progressbar first instead of directly filing a bug report here.

**Comment by posva** [comment]
Hello, if the plugin is not compatible with SSR, please report the bug to them. Thanks!

**Comment by novay55555** [comment]
Thanks for replying so soon.

Actually, I was just confused why some strange situations I mentioned in my
reposition happened. Maybe SSR is too early for me to use :P

Eduardo San Martin Morote <notifications@github.com> 于2018年7月17日周二 下午6:13写道：
