### ISSUE TITLE
keep-alive to cache focus state

### ISSUE THREAD

**Issue by pittkost** [vuejs/vue#8504]
### What problem does this feature solve?
It'd be especially useful for apps with spatial navigation, tab navigation and for accessibility issues in general. Let's consider this - assume you relay on the focus state when navigating through some application with vue-router (it might be TV app). It's irritating when you hit back button and your focus state is lost.

### What does the proposed API look like?
:cache-focus="(boolean)"

**Comment by posva** [comment]
This is not the goal of `keep-alive` and may be much more complicated than it looks like (because of edge cases). Nevertheless, it's something that should be implemented in userland. Feel free to post back your plugin if you create one 🙂
