### ISSUE TITLE
I can't render array of component instances

### ISSUE THREAD

**Issue by meowofficial** [vuejs/vue#8506]
### What problem does this feature solve?
I need to build list of dynamical components that I can group in group component. Then I need to send all information about builded components and groups.

I can use `<component v-for="componentName in myComponents" :is="componentName"></component>`, and get information about components using `this.$children.map(component => component.getInformation())`, but then I can't move some component to group component, because I have only component name not the component instance with data (it just render with default data).

I also can use this:  

```
    <template>
      <div ref="container"> </div>
    </template>
        
    <script>
      import someComponent from 'someComponent.vue'
      import Vue from 'vue'
    
      export default {
        data () {
    	  return {
    	    myComponents: []
    	  }
    	},
    	methods: {
    	  addSomeComponent () {
		let ComponentClass = Vue.extend(someComponent);
		let instance = new ComponentClass({});
		myComponents.push(instance);
		instance.$mount();
		this.$refs.container.appendChild(instance.$el)
	  },
          getInformation () {
            return this.myComponents.map(component => component.getInformation());
          }
    	}
      }
    </script>
```

But then I can't use reactivity, directives (e.g. directives for drag and drop), and it's not data driven pattern.

Any suggestions?

### What does the proposed API look like?
`<component v-for="componentInstance in myComponents" :is="componentInstance"></component>`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
