### ISSUE TITLE
Adding a Vue.helper() constructor

### ISSUE THREAD

**Issue by thecodechef** [vuejs/vue#8508]
### What problem does this feature solve?
Well, to be honest, the way Vue define the global dollar-sign helpers is quite cumbersome.
So I figured that this would be a better option

This is what we have now
```js
// vuepress - app.js

Vue.prototype.$withBase = function (path) {
  const base = this.$site.base
  if (path.charAt(0) === '/') {
    return base   path.slice(1)
  } else {
    return path
  }
}
```

### What does the proposed API look like?
```js
Vue.helper('withBase', (path) => {
  const base = this.$site.base
  if (path.charAt(0) === '/') {
    return base   path.slice(1)
  } else {
    return path
  }
}
```

**Comment by yyx990803** [comment]
I don't honestly see any practical benefit of this - a few less characters but being less explicit?
