### ISSUE TITLE
Instantiating new array inside renderList()

### ISSUE THREAD

**Issue by ridea-co** [vuejs/vue#8511]
### Version
2.5.13

### Reproduction link
[https://github.com/vuejs/vue/blob/5981529b497f5ef064b123aeb58eb9655172d6eb/src/core/instance/render-helpers/render-list.js](https://github.com/vuejs/vue/blob/5981529b497f5ef064b123aeb58eb9655172d6eb/src/core/instance/render-helpers/render-list.js)

### Steps to reproduce
When renderList(val, render) is called, passing NaN for 'val' as parameter.

Apologies for the "Reproduction link", but we cannot reproduce one since we have no clue what triggered that function:
https://github.com/vuejs/vue/blob/5981529b497f5ef064b123aeb58eb9655172d6eb/src/core/instance/render-helpers/render-list.js
on line 22.
But you can probably do a unit test using renderList(0/0, function(a, b) {})

### What is expected?
unable to instantiate new array

### What is actually happening?
code is not checking if given 'val' is NaN, which is a 'number'.  Thus trying to call new Array(NaN) throws exception

---
probably can check if the given val is greater or equal to 0 since if a negative value will also cause exception: new Array(-1)

instead of:
... else if (typeof val === 'number') {

}

use:
... else if (typeof val === 'number' && val >= 0) {

}

**Comment by LinusBorg** [comment]
> Apologies for the "Reproduction link", but we cannot reproduce one since we have no clue what triggered that function

Can you at last describe the scenario under which this happens? Giving zero context leaves us stepping in the dark a bit ...

> probably can check if the given val is greater or equal to 0 since if a negative value will also cause exception: new Array(-1)

Even if that makes sense, the real problem is most probably not this check is not performed, but that this function is called with `NaN for ` `val` - that generally should not happen I think.

So understanding what scenario triggered this is crucial in debugging it.

**Comment by posva** [comment]
Closing until repro is provided
