### ISSUE TITLE
Bug with imported components

### ISSUE THREAD

**Issue by TrueGameover** [vuejs/vue#8514]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/82oo6j6w8](https://codesandbox.io/s/82oo6j6w8)

### Steps to reproduce
just run

### What is expected?
Rendered component1 in component2

### What is actually happening?
Failed to mount component: template or render function not defined.

**Comment by yyx990803** [comment]
This is expected behavior when you have cyclic dependency between your components: https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components
