### ISSUE TITLE
$listeners are not updated if you use $on

### ISSUE THREAD

**Issue by chearon** [vuejs/vue#8515]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/eywraw8t/182246/](http://jsfiddle.net/eywraw8t/182246/)

### Steps to reproduce
Open fiddle and click on the text.

There is one component in the middle of 2 others that forwards events like the documentation example, with `v-on="$events"`. The `<h1>` component fires a mousedown and a mouseup, and the highest-level component registers one of those in the render function and one of them with `$on`.

### What is expected?
I would expect using `$on` to update `$listeners` which would update the listeners on the deepest component. If this is by design, could it be clarified in the documentation?

### What is actually happening?
`$on` doesn't update child components if `$listeners` is used in the render functions

---
I know it's unusual to use `$on` like this, but I'm working on an Angular application that's being slowly converted into Vue. In order to cross barriers we create Vue components and mount them into Angular directly

**Comment by lzy68187311** [comment]
$on just add an event on current instance~ will not update $listeners $listeners is readonly   initialized  by  vm.$options._parentListeners ~
