### ISSUE TITLE
Manually executing of a directive expression

### ISSUE THREAD

**Issue by Simonwep** [vuejs/vue#8517]
### What problem does this feature solve?
Let's assume  I have a custom directive which will be used like this: `v-my-directive:someargument.amodifier`.

Now I have JavaScript code as value like this:  `v-my-directive:someargument.amodifier="alert('Hello Vue!')"`.

The problem is, the value would be executed. How can I prevent this and execute it by myself, like `v-on` it does?

### What does the proposed API look like?
Maybe adding an option to the `Vue.directive` function would be helpful. Example:

```js
Vue.directive('my-directive', {
    parsing: false, // Default would be true
});
```

**Comment by riophae** [comment]
Personally I think it's better to simply use methods and bind the method to the directive. Introducting a new option to solve this problem is an overkill.

**Comment by Simonwep** [comment]
Thank's for the quick response!
Could you provide an example or what do you mean exactly?

**Comment by riophae** [comment]
@Simonwep I'm not a member of the Vue team. Just my personal opionon :)

Here is a example:

```vue
<template>
  <div v-my-directive:someargument.amodifier="handler">...</div>
</template>

<script>
  export default {
    methods: {
      handler() {
        alert('Hello Vue!')
      },
    },
  }
</script>
```

**Comment by Simonwep** [comment]
Ah, no problem, your opinion is equally worth :)
Oh, I see what you mean... yeah, that would be a solution. Thanks! 😄
