### ISSUE TITLE
Write a tutorial or documentation on how to porting an HTML5/JS UI Component to VueJS Component to build a Vue UI Framework

### ISSUE THREAD

**Issue by biapar** [vuejs/vue#8523]
### What problem does this feature solve?
Help the community to grow

**Comment by LinusBorg** [comment]
We maintain a cookbook with such recipes on the website. 

See vuejs/vuejs.org repository, you can post  it as a cookbook idea there

**Comment by douglasg14b** [comment]
Darn, got here from google looking for some pointers. RIP
