### ISSUE TITLE
vue对typescript支持现在已经成熟了么？

### ISSUE THREAD

**Issue by sunshixiong789** [vuejs/vue#8526]
### What problem does this feature solve?
我想用typescript来编写vue项目，不知道vue-cli生成得项目是否很好得支持typescript，更具我用了最新得3.0-rc5版本还是支持很好得，但是不知道会不会有坑，求指点！

### What does the proposed API look like?
我希望能够完全得支持typescript

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

------

目前 Vue 对 TypeScript 的支持非常好，可以放心在生产环境中使用。
[已知的一些小问题可以在 open issues 的 TypeScript 标签下看到](https://github.com/vuejs/vue/issues?q=is%3Aopen+is%3Aissue+label%3Atypescript)。这些问题基本不会影响实际使用，并且其中多数会在近期的版本更新中得到修复。
如果碰到 bug 的话欢迎到 GitHub issues 中提出。

**Comment by sunshixiong789** [comment]
好的
