### ISSUE TITLE
Crash when use v-bind with v-model on input element

### ISSUE THREAD

**Issue by novacoder** [vuejs/vue#8531]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/eywraw8t/190868/](http://jsfiddle.net/eywraw8t/190868/)

### Steps to reproduce
Bind undefined attributes prop on input element with v-model 

&lt;input v-bind="attributes" v-model="editingValue"&gt;

### What is expected?
Input element uses default "text" value for "type" attribute.

It works on vue 2.5.13

### What is actually happening?
Exception:

VM841 vue.js:1743 TypeError: Cannot read property 'type' of undefined
    at Proxy.eval (eval at createFunction (VM841 vue.js:10667), <anonymous>:3:116)
    at Vue._render (VM841 vue.js:4535)
    at Vue.updateComponent (VM841 vue.js:2788)
    at Watcher.get (VM841 vue.js:3140)
    at new Watcher (VM841 vue.js:3129)
    at mountComponent (VM841 vue.js:2795)
    at Vue.$mount (VM841 vue.js:8527)
    at Vue.$mount (VM841 vue.js:10926)
    at Vue._init (VM841 vue.js:4627)
    at new Vue (VM841 vue.js:4716)

---
It works when you: 

1. Add type attribute on input element
&lt;input type="text" v-bind="attributes" v-model="editingValue"&gt;

2. Return empty object for attributes property by default
...
props: {
  	attributes: {default: function() {return {}}} 
  }
...

**Comment by posva** [comment]
You need to move attributes to `data`.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by yyx990803** [comment]
This has nothing to do with `v-model`, you can't `v-bind` an undefined value.

**Comment by posva** [comment]
Or maybe you want to use propsData

**Comment by novacoder** [comment]
I created InputComponent vue component that has input element inside. This component has attributes property to be passed to input element. For example {type=“number; min=0}. But it is ok when i don’t pass any attributes to the component in its template. 
It worked in previous vue versions i used but it doesn’t after migration to v2.5.16 from v2.5.13
