### ISSUE TITLE
Passing a value attribute via to a select tag using $attrs should not set the select value without v-model

### ISSUE THREAD

**Issue by lee-chase** [vuejs/vue#8532]
### Version
2.5.16

### Reproduction link
[https://codepen.io/lee-chase/pen/cead98e32ada57abc99350be8331197f](https://codepen.io/lee-chase/pen/cead98e32ada57abc99350be8331197f)

### Steps to reproduce
Can be observed on opening the codepen.

### What is expected?
Passing a value to a select tag via $attrs should behave the same way setting the attribute in HTML does, that is it is ignored.

When using v-model it should behave as it currently does.

### What is actually happening?
The value overrides any selected attribute set on an option. This should only occur with v-model.

**Comment by xevops** [comment]
v-model it's just sugar on top of the input tag. Using v-model it's the same as use the :value prop and the @input event.
In this case the v-bind="$attrs" it's passed from the parent component the html attributes to the select, so it means that the value attribute is also set.
As far as I know it works as expected reading the documentation:
[https://vuejs.org/v2/api/#vm-attrs](https://vuejs.org/v2/api/#vm-attrs)

**Comment by lee-chase** [comment]
v-model works as expected and the current behaviour is equivalent to.

mounted() {
  // ref for select tag = select
  this.$refs.select.value = this.$attrs.value; // DOES set the selected option
}

However, attributes especially those such as value and checked that are copied from $attrs should behave like real attributes when no v-model is used e.g.

mounted() {
  // ref for select tag = select
  this.$refs.select.setAttribute('value', this.$attrs.value); // DOES NOT set the selected option
}

**Comment by sodatea** [comment]
Actually it works with `v-bind:value="'b'"`, because Vue use `domProps` for dynamic bindings and `attrs` for static attributes…

**Comment by posva** [comment]
Keep in mind `value` as an attribute is only taking into account uppon page load, that's why `setAttribute` is not working as you expect. Check out the `prop` modifiers in docs 🙂

**Comment by lee-chase** [comment]
Fair point on the setAttribute example, however, I was trying to point out that it's necessary to add extra code to make a custom select component will not work like a built-in select.
```html
 <!-- selected item is a -->
<select value="b"><opt value="a" selected>A</opt><opt value="b">B</opt></select>
```
I've managed to work around this, to produce what I think of as correct behaviour.

**Comment by posva** [comment]
FYI you need to use the selected attribute on the options elements
