### ISSUE TITLE
Why not $payload?

### ISSUE THREAD

**Issue by simaodeveloper** [vuejs/vue#8533]
### What problem does this feature solve?
Hello folks, How it going?

I want to start a discussion about parameter $event, when we use Custom Events to notify parent component about children changes, instead receive $ event we can receive $ payload, yes it's just semantic, but IMHO I think the $ payload name make much sense.

### What does the proposed API look like?
```
@:custom-event="text = $payload"
```

or
 
```
@:custom-event="drawSVG($payload)"
```

**Comment by posva** [comment]
Because we get the native event object when dealing with native objects and having `event` everywhere makes more sense. The `$` is to not overlap with user properties.
Using `event` is fairly reasonable and we are not going to introduce such a breaking change 😛

**Comment by simaodeveloper** [comment]
Thanks for all your atention guys!

I think these little things should be discussed, I understand the reasons for the current implementation and of course this is not a reason to break a version.

I just wanted to bring a discussion and listen to what you guys think about it.

In the future I will come back with more thoughts and more arguments to defend my views on what I believe is best for a team to work together.

But of course, I should have taken it to some forum: D hihi

Thank you again.
