### ISSUE TITLE
<button :click=...

### ISSUE THREAD

**Issue by pmarimuthu** [vuejs/vue#8539]
### Version
2.5.16

### Reproduction link
[https://codepen.io/pmarimuthu/pen/pZRZjN?editors=1010](https://codepen.io/pmarimuthu/pen/pZRZjN?editors=1010)

### Steps to reproduce
https://codepen.io/pmarimuthu/pen/pZRZjN?editors=1010

### What is expected?
Error message in console is expected

### What is actually happening?
Chrome: Page keep loading in Chrome.
Firefox: A web page is slowing down your browser. What would you like to do?

---
 Example Code:
         <button @click="faq.meta.likeCount =1"> favorite </button>      {{ faq.meta.favCount}}  |
          <button :click="faq.meta.likeCount =1">   copy      </button>     {{ faq.meta.copyCount}}

Comments:
By mistake if i use ":" instead of "@" then we are getting this issue.
Note sure, whether this error is already reported to the community.

Thank you.
Regards,
Maris

**Comment by sodatea** [comment]
This is because when you use `:`, the expression `onLike(this, faq)` gets evaluated immediately, which triggers an update due to this line: `faq.meta.likeCount+=1`, leading to an infinite loop.
I don't think there's anything we can do in Vue.

**Comment by pmarimuthu** [comment]
@sodatea 
Thank you for the quick response;
