### ISSUE TITLE
异步组件-处理加载状态在路由组件中使用无效（vue-router版本为2.8.1）

### ISSUE THREAD

**Issue by tangyuhui** [vuejs/vue#8542]
### Version
2.5.16

### Reproduction link
[https://jsbin.com/goduyol/1/edit?html,js,output](https://jsbin.com/goduyol/1/edit?html,js,output)

### Steps to reproduce
const test = () => ({
  component: new Promise((resolve, reject) => {
    setTimeout(() => {
      reject()
    }, 500)
  }),
  loading: { template: `<div>loading</div>` },
  error: { template: `<div>error</div>` },
  delay: 0,
  timeout: 10000
})

export default new Router({
  routes: [
    {
      path: '/test',
      name: 'test',
      component: test
    }
  ] 
})

1.定义上面所示的路由组件，希望能在报错时渲染出error组件（官方文档中有写到 `注意如果你希望在 Vue Router 的路由组件中使用上述语法的话，你必须使用 Vue Router 2.4.0  版本’    而我使用的是2.8.1，应该是符合这个条件了）

### What is expected?
在reject()后，界面能出现error组件

### What is actually happening?
未出现error组件，控制台报错
Error: Failed to resolve async component default: undefined
    at vue-router.esm.js:1767
    at vue-router.esm.js:1833

**Comment by Shyam-Chen** [comment]
請去看這個

https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-router/pull/2140
