### ISSUE TITLE
es6 function import() not working in function render()

### ISSUE THREAD

**Issue by kpeng2016** [vuejs/vue#8543]
### Version
2.5.16

### Reproduction link
[https://github.com/kpeng2016/testVueProject](https://github.com/kpeng2016/testVueProject)

### Steps to reproduce
1. git the testvueproject
2. start the project by "npm run dev"
3. open the project by browser

### What is expected?
show text "this is test page" in the page

### What is actually happening?
empty

---
I wish it will work if I use es6 import() in vue render() function to import dynamical file.
Thank you very much!

**Comment by Justineo** [comment]
`render` function is synchronous. You can't dynamically import something inside it.
