### ISSUE TITLE
Shorthand for false props

### ISSUE THREAD

**Issue by jameslkingsley** [vuejs/vue#8549]
### What problem does this feature solve?
There's already a nice shorthand for `true` props where you just add the prop name on its own, however there isn't an equivilent shorthand for `false` props. Below are a couple suggestions for that shorthand that would make writing/reading these props easier I think. It's a pretty minor feature request, but I think it would add to the already amazing developer experience of using Vue.

### What does the proposed API look like?
`<component !prevent />` translates to `<component :prevent="false" />`

`<component :not-prevent />` translates to `<component :prevent="false" />`

**Comment by sh7dm** [comment]
This is good idea, but API like `:not-prevent` isn't good, because it can cause some problems with existing components which have `not-*` props

**Comment by sodatea** [comment]
Boolean props defaults to `false`.

So if you define a component like this
```
...
{
  props: {
    prevent: Boolean
  }
}
...
```

You can set `prevent` to `false` by simply not passing it.

**Comment by simaotwx** [comment]
> You can set prevent to false by simply not passing it.

In the case that a component has a default of `true` this does not work.
