### ISSUE TITLE
IOS audio default styles are missing

### ISSUE THREAD

**Issue by CrazyProgrammer12138** [vuejs/vue#8552]
### Version
2.5.16

### Reproduction link
[https://texun.hulian120.com/activity/englishStudy](https://texun.hulian120.com/activity/englishStudy)

### Steps to reproduce
Audio is used in the vue component. The default style loss of audio is only a play button, but it can be displayed on WeChat, and the version of vue is 2.9.1

### What is expected?
Display the audio default style

### What is actually happening?
Default styles disappear

**Comment by fnlctrl** [comment]
That's not a valid reproduction. Also, vue isn't able to change default styles of elements, please check your own application code.

**Comment by CrazyProgrammer12138** [comment]
Is that why apple audio doesn't play automatically
