### ISSUE TITLE
为什么vue没有提供对数组属性的监听

### ISSUE THREAD

**Issue by hfhan** [vuejs/vue#8562]
### What problem does this feature solve?
在vue中，通过Object.defineProperty实现了对对象属性的监听，但是Object.defineProperty对数组已有元素也是实现监听的，那么为什么vue中没有提供这一功能，使得`arr[已有元素下标]=val`变成响应式？

具体分析：https://segmentfault.com/a/1190000015783546?_ea=4074035

### What does the proposed API look like?
```

```

**Comment by hfhanfei** [comment]
尤大，我想问下究竟是什么样的性能问题限制了这一功能呢？因为现代浏览器以及电脑配置都还不错，监测几万乃至几十万个属性应该还是可以的，如果数组长度被限制，是不是就可以使用这一功能了？

**Comment by yyx990803** [comment]
性能代价和获得的用户体验收益不成正比。

**Comment by hfhanfei** [comment]
谢谢尤大，明白了。(◦˙▽˙◦)
