### ISSUE TITLE
v-bind:class removes class added by other javascript module

### ISSUE THREAD

**Issue by drozdzynski** [vuejs/vue#8565]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/snedy94u/2/](https://jsfiddle.net/snedy94u/2/)

### Steps to reproduce
Use / Create plain Javascript module, class etc. which adding css class to the element which has v-bind:class

### What is expected?
CSS class added by module, class etc. should stay after a change of classes by v-bind:class

### What is actually happening?
CSS class added by module, class etc. is removed after a change of classes by v-bind:class

---
In reproduction when you run it and watch the class of div.test, after 5 seconds, css class "added" which was added by js class Test will be removed by the condition in v-bind:class.

**Comment by KaelWD** [comment]
That's just how VDOM works, you'll get the same thing with react, angular, or anything else.

**Comment by posva** [comment]
This is indeed expected behavior
