### ISSUE TITLE
CSS :first-child selector doesn't work with v-for

### ISSUE THREAD

**Issue by maxirozay** [vuejs/vue#8566]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eywraw8t/213640/](https://jsfiddle.net/eywraw8t/213640/)

### Steps to reproduce
Create a CSS class with the selector `:first-child` and apply it on an element with the directive `v-for`.

### What is expected?
The first element of the list should have the style of the `.class:first-child` class.

### What is actually happening?
The `.class:first-child` style is ignored.

**Comment by sodatea** [comment]
`:first-child` only selects the first element among its siblings.

See examples here:
https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child

You need to remove the first three `<div class="bg">` elements to make it work.

**Comment by maxirozay** [comment]
@sodatea yes that's my point. If you check my example I put 3 div next to each others and the `:first-child` works then I use a `v-for` that creates 3 div next to each others and the `:first-child` doesn't work.

The HTML produced by my example is:
```
<div class="bg">a</div>
<div class="bg">b</div>
<div class="bg">c</div>
<div class="bg-v-for">1</div>
<div class="bg-v-for">2</div>
<div class="bg-v-for">3</div>
```
So the HTML is the same and the CSS doesn't work the same way.
