### ISSUE TITLE
how to exports html in vue component?

### ISSUE THREAD

**Issue by zhangwei900808** [vuejs/vue#8570]
### What problem does this feature solve?
how to export html file in vue component?

### What does the proposed API look like?
how to export html file in vue component?

**Comment by sodatea** [comment]
感谢对 Vue 的关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

**Comment by zhangwei900808** [comment]
@sodatea 用vue component导出原生html不算特性请求吗

**Comment by Justineo** [comment]
@zhanwei900808 你自己看看你是如何填写 feature request 模板的。产品经理给你写一句话的需求你就做吗？

**Comment by zhangwei900808** [comment]
额，需求是：导出简历页面！而我的简历页面就是用vue组件写的，我现在的问题就是如何把这个组件以html形式导出

**Comment by zhangwei900808** [comment]
给个思路也好啊
