### ISSUE TITLE
Google Maps API “Custom Popups” Example Code Breaks in VueJS Single File Components

### ISSUE THREAD

**Issue by phao5814** [vuejs/vue#8571]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/74oylzrq36](https://codesandbox.io/s/74oylzrq36)

### Steps to reproduce
As you click and pan around the map, the popup remains in the centre of the view port. This only occurs when using a Vue Single File Component.

### What is expected?
The popup should be pinned to its respective location as demonstrated by this VueJS jsFiddle (https://jsfiddle.net/phao5814/eywraw8t/215503/), which contains identical code to the VueJS Single File Component (refer to sandbox link above).

### What is actually happening?
The popup is not pinned to its respective location.

---
The code I'm using has been copy/pasted from the Google Maps API documentation on Custom Popups (https://developers.google.com/maps/documentation/javascript/examples/overlay-popup). The example code provided in the documentation works perfectly in jsFiddle; however, the issues arose after pasting into a Single File Component.

**Comment by sodatea** [comment]
That's because you used scoped style in the SFC example. Remove the `scoped` attribute from `style` tag and everything's fine.
