### ISSUE TITLE
Enter a props to mixins

### ISSUE THREAD

**Issue by acidiney** [vuejs/vue#8572]
### What problem does this feature solve?
Reusable mixin with new data

If I have this mixin 
```
import data from "@/dictionary/test.json";
export let mixins = {
  computed: {
    dictionary: function() {
      let language = localStorage.getItem("language");
      return data[language];
    }
  }
};
```

This working but working only for a unique component test ... Now if I pass prop to my mixin this mixin is reusable with new data whenever... Like this

```
export let mixins = {
props: ["data"]
  computed: {
    dictionary: function() {
      let language = localStorage.getItem("language");
      return data[language];
    }
  }
};
```

So, I don't need to import a specific dictionary.

### What does the proposed API look like?
Like this.

```
export let mixins = {
props: ["data"]
  computed: {
    dictionary: function() {
      let language = localStorage.getItem("language");
      return data[language];
    }
  }
};
```

**Comment by sirlancelot** [comment]
Props are already mixed in to the component instance... I'm not sure what you're requesting.

**Comment by posva** [comment]
If you want parameters for mixins create functions that take those parameters and return the custom mixin
