### ISSUE TITLE
Error with import vue by es module 

### ISSUE THREAD

**Issue by lizheming** [vuejs/vue#8574]
### Version
2.5.17-beta.0

### Reproduction link
[https://jsbin.com/kizeyopoqa](https://jsbin.com/kizeyopoqa)

### Steps to reproduce
open url and you can see an error in dev tool.

### What is expected?
normal output console.log

### What is actually happening?
Uncaught ReferenceError: process is not defined

---
I think `process.env` should be compiled in build progress.

**Comment by JounQin** [comment]
There is already a PR https://github.com/vuejs/vue/pull/7110 tracking for it.

**Comment by lizheming** [comment]
OK, thank you very much. I have searched related question in issue but not pull request.
