### ISSUE TITLE
Single process webkit engine meet  .js   such as   <script type="text/javascript" src="static/js/vendor.c2df4baf.js">  </script>   will create a new thread to download ?

### ISSUE THREAD

**Issue by housenkui** [vuejs/vue#8577]
### Version
2.5.16

### Reproduction link
[https://cn.vuejs.org/](https://cn.vuejs.org/)

### Steps to reproduce
Single process webkit engine meet  .js   such as   <script type="text/javascript" src="static/js/vendor.c2df4baf.js">  </script>   will create a new thread to download ?

if the file     xxx.html include three  <script type="text/javascript" src="static/js/xxxx.js">  </script>  single process webkit engine will
create three thread ? ? 
Thanks very much !

### What is expected?
Single process webkit engine meet  .js   such as   <script type="text/javascript" src="static/js/vendor.c2df4baf.js">  </script>   will create a new thread to download ?

if the file     xxx.html include three  <script type="text/javascript" src="static/js/xxxx.js">  </script>  single process webkit engine will
create three thread ? ? 
Thanks very much !

### What is actually happening?
Single process webkit engine meet  .js   such as   <script type="text/javascript" src="static/js/vendor.c2df4baf.js">  </script>   will create a new thread to download ?

if the file     xxx.html include three  <script type="text/javascript" src="static/js/xxxx.js">  </script>  single process webkit engine will
create three thread ? ? 
Thanks very much !

---
Single process webkit engine meet  .js   such as   <script type="text/javascript" src="static/js/vendor.c2df4baf.js">  </script>   will create a new thread to download ?

if the file     xxx.html include three  <script type="text/javascript" src="static/js/xxxx.js">  </script>  single process webkit engine will
create three thread ? ? 
Thanks very much !

**Comment by sodatea** [comment]
感谢对 Vue 的关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。
