### ISSUE TITLE
get the code coverage of .vue files while running the project,  similar to istanbul

### ISSUE THREAD

**Issue by LYnnProspery** [vuejs/vue#8584]
### What problem does this feature solve?
Business vue code write unit tests is too inefficient, but the code needs coverage report。Using intanbul to get the coverage of the compiled js is ugly...wish to be supported

### What does the proposed API look like?
vue.toCoverageVersionCode = true;
//return the code which contains some extends code which add to get the coverage data

vue.prototype.getCoverageData = () => {//return the coverage data}

**Comment by sodatea** [comment]
Istanbul does support source map.

I don't think such utilities should be implemented in the core library.
