### ISSUE TITLE
Access Vue instance in another js file

### ISSUE THREAD

**Issue by alex83130** [vuejs/vue#8585]
### What problem does this feature solve?
I need to access at my instance Vue in another file.
By exemple we have a entrypoint.js which contains a new Instance of Vue :

```
export const vm = new Vue({
    router,
    wait: new VueWait({ registerComponents: false }),
    render: h => h(App),
}).$mount('#app-vue');
```

And i would like access at this vm instance in other.js.

```
import vm from './entrypoint'

window.onload = function () {
    console.log(vm)
}
```

But I have a error : 

[Vue warn]: Cannot find element: #app-vue

The reason for this request is to be able to execute a method of my view control from an external js with : 

` vm.$refs.mapUnity.test();`

### What does the proposed API look like?
I did'nt see in the documentation a solution for my problem..

**Comment by shentao** [comment]
Don’t use the `.$mount('#app-vue')` method right away. Then you can import the instance and mount it inside the `window.onload` function. 

Please go to the Vue forum (https://forum.vuejs.org/) or the Chat (chat.vuejs.org) when you need help.
Closing.
