### ISSUE TITLE
Define slot scope props in VM similar to props

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue#8588]
### What problem does this feature solve?
Access slot-scope props directly from the VM. Currently, you can't create computeds or watchers on a slot scope prop, and for the VM to access them you'd have to pass them around as arguments.

### What does the proposed API look like?
Say you have a list component:
```javascript
Vue.component('list', {
  render() {
    const items = [1,2,3,4,5]
    return this.$scopedSlots.default({items});
  },
})
```
Current usage (https://jsfiddle.net/wb6gc2ur/):
```javascript
<div id="app">
  <list>
    <div slot-scope="someProps">
      <p>evens: {{ evens(someProps.items) }}</p>
      <p>odds: {{ odds(someProps.items) }}</p>
    </div>
  </list>
</div>

new Vue({
  el: '#app',
  methods: {
    evens(items) {
      return items.filter(n => n % 2 === 0)
    },
    odds(items) {
      return items.filter(n => n % 2 !== 0)
    },
  },
})
```
Proposed API:
```javascript
<div id="app">
  <list>
    <div>
      <p>evens: {{ evens }}</p>
      <p>odds: {{ odds }}</p>
    </div>
  </list>
</div>

new Vue({
  el: '#app',
  slotScope: { // something like this
    default: {
      items: Array,
    }
  },
  computed: {
    slotItems() {
      return this.slotScope.default.items;
    },
    evens() {
      return this.slotItems.filter(n => n % 2 === 0)
    },
    odds() {
      return this.slotItems.filter(n => n % 2 !== 0)
    },
  },
})
```

**Comment by Justineo** [comment]
Scoped slots are functions. Their slot scope are filled with different arguments each time they are called. If you use multiple `<list>` component in the current component, which would you expect `this.slotScope.default` should point to? It's simply not possible.
