### ISSUE TITLE
Use Reusable Transitions in a Reusable Transitions not working

### ISSUE THREAD

**Issue by alex83130** [vuejs/vue#8593]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/wtpuevc6/1446/](https://jsfiddle.net/wtpuevc6/1446/)

### Steps to reproduce
1) Create a app with 2 parents routes components and a router-view 
2) In the first route component, create 2 children route component with a router-view
3) Create a reusable transition and apply this on parent router-view and childre router-view

### What is expected?
With a reusable transition I would like use a transition on the passage between parent routing.
And with the same reusable transition I would like another transition between children routing.

### What is actually happening?
Only one transition work : 
- If a add the reusable transition on the parent router-view, and the children router-view, so only the children transition work.
- if i remove the children transition, the parent transition work but I haven't transition to the children

---
I try to use a transition on a parent router-view and a children router-view without use a reusable transition (only the tag <transition name:'nom_page'></transition>) and in this case all work...

**Comment by sodatea** [comment]
```diff
-<reusable-transition :name="name_transition">
+<reusable-transition name_transition="page2">
    <router-view></router-view>
  </reusable-transition>
```
