### ISSUE TITLE
Scrolling fast on Android makes DOM content disappear

### ISSUE THREAD

**Issue by jcarnevale89** [vuejs/vue#8594]
### Version
2.5.2

### Reproduction link
[https://bumpercommander.com/p/iron-cross-hd-front-bumper-push-bar/](https://bumpercommander.com/p/iron-cross-hd-front-bumper-push-bar/)

### Steps to reproduce
This only happens on Android devices and its intermittent. Ive also tested in Browserstack and I couldn't reproduce, it was only happening on actual android devices. Once you load that page, if you scroll up and down really fast sometime pieces of the DOM or images disappear. If you scroll back up and then back down to where you just were the content might be there now.

### What is expected?
The DOM you see should be there constantly.

### What is actually happening?
The DOM is there but android isn't rendering it for some reason.

---
We have isolated it to be an Android OS issue only (Not having the problems on iOS or Desktop devices). We also tried to upgrade to the latest version of Vue, and removed 3rd party dependencies. At this point I don't know if its a Vue problem or something else but I figured I would submit a ticket so see if anyone else has reported an issue like this before.

**Comment by posva** [comment]
This is probably some delay in the rendering engine of the browser and definitely not related to Vue as it doesn't remove content from the page when you scroll down

**Comment by jcarnevale89** [comment]
@posva Thats what i figured too, just wanted to make sure I wasn't missing something. Thank you for the response
