### ISSUE TITLE
vue 中是用webGl会出现内存泄漏问题

### ISSUE THREAD

**Issue by guangshao** [vuejs/vue#8597]
### Version
2.5.2

### Reproduction link
[https://github.com/guangshao/hospital](https://github.com/guangshao/hospital)

### Steps to reproduce
打开 src\pages\home\map 下的initView.js里面的lazyCreateMode: true, 改为false.
或者直接切换多个楼层

### What is expected?
希望可以知道原因

### What is actually happening?
内存飙升到1个G

**Comment by Justineo** [comment]
请提供最小的复现场景，去除所有无关的代码，而非直接扔过来一个完整项目 URL，谢谢了。

**Comment by yyx990803** [comment]
@Justineo 以后不符合要求都直接关。
