### ISSUE TITLE
Vue.js to output different html than expected

### ISSUE THREAD

**Issue by y-nk** [vuejs/vue#8598]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/9gvturfq/](http://jsfiddle.net/9gvturfq/)

### Steps to reproduce
1. Create a `<select />`
2. add some divs with nested option tags inside.

### What is expected?
Vue.js should output the actual generated code, even if incorrect html.

### What is actually happening?
It corrects the invalid dom output, preventing the browser from doing it by itself

---
It seems un-natural, but since the output of Vue.js is different that the one from major browsers, I raise this issue knowing it could be easily closed.

**Comment by sodatea** [comment]
See https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats

**Comment by y-nk** [comment]
@sodatea 🙏
