### ISSUE TITLE
IE9 newline compiler error

### ISSUE THREAD

**Issue by wipphj** [vuejs/vue#8602]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/wipphj/r6v19dmx/](https://jsfiddle.net/wipphj/r6v19dmx/)

### Steps to reproduce
Copy to Single Html File       
open with IE9       
open dev console and see print err info

### What is expected?
show normally

### What is actually happening?
dev console showed error

---
IE9 uses Windows newlines ("\r\n"), while IE11 uses POSIX newlines ("\n").

**Comment by posva** [comment]
I tested the code after removing element ui and it worked fine on IE 9

**Comment by wipphj** [comment]
please see the  [Demo](https://jsfiddle.net/wipphj/5qxm190z/) and [Screenshot](http://p4.cdn.img9.top/ipfs/QmPVgpAWy32RBNJUUn5im6puc8tPQ85ixxPWbDbXGYyF97?4.png
)

**Comment by posva** [comment]
you keep sending jsfiddles but they don't work on IE9...

**Comment by wipphj** [comment]
yeah， I'm sorry ，but i don't know how to parse html code in the editor.so can you copy code to single HTML file then copy with IE9

**Comment by posva** [comment]
Ok, I did that, although I think there are other services that do work on IE9 😛 
My editor was removing the linefeeds when pasting.
I don't understand why would someone write an html file with linefeeds instead of regular `\n` but I'm also confused about why it only fails in IE9 as if IE9 was transforming the HTML before Vues gets to it

**Comment by wipphj** [comment]
Haha😛 Thank you, maybe just like issue 924 points.

i searched that: **IE9 uses Windows newlines ("\r\n"), while IE11 uses POSIX newlines ("\n").**

And i find another err with IE11  as  with `shouldDecodeNewlines ` got `undefined` in jsbin online environment .[demo](https://jsbin.com/miqopolefu/edit?html,js,output)
