### ISSUE TITLE
`inheritAttrs` option doesn't work with functional components

### ISSUE THREAD

**Issue by riophae** [vuejs/vue#8604]
### Version
2.5.17

### Reproduction link
[https://codepen.io/riophae/pen/VBdqvN](https://codepen.io/riophae/pen/VBdqvN)

### Steps to reproduce
Open the pen and see the logs in console.

### What is expected?
`context.data.attrs` should be an empty object.

### What is actually happening?
`context.data.attrs` is not empty.

![snipaste_2018-08-04_18-14-26](https://user-images.githubusercontent.com/1289884/43675170-45c88b54-9812-11e8-8a0b-22742524267a.png)

**Comment by posva** [comment]
This is how functional components work, you are supposed to pass all the attributes manually, `inheritAttrs` is not supported in functional components

**Comment by HaNdTriX** [comment]
Since Vue Version `3.3+` you can now use:

```js
defineOptions({
  inheritAttrs: false
})
```
