### ISSUE TITLE
动态组件渲染不生效

### ISSUE THREAD

**Issue by f2009** [vuejs/vue#8606]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
1. 引入一个公共组件；
2. 循环copy多个副本，每个副本设置一个不同的name；
3. 注入进components对象；
4. 设置is属性；

==== code如下 ====
import PageList from "~components/PageList";

const PAGE_LIST_TOTAL = 2; // 同一组件2个副本
const PAGE_LIST_TABS = []; // 动态组件引用名。如["T1", "T2"]
const PAGE_LIST_COMP = {}; // 多个组件对象。如{T1: {...pageList, {name:"T1"},}}

for (let i = 0; i < PAGE_LIST_TOTAL; i  ) {
  let compName = "MSG_TAB"   i;
  PAGE_LIST_TABS.push(compName);
  PAGE_LIST_COMP[compName] = { ...PageList, name: compName };
}

export default {
    components: { ...PAGE_LIST_COMP }
    ....
}

====template====
<component 
        :is="c_tab"
        :queryParams="queryParams"
        :options="queryOpts"
      >
</component>

### What is expected?
任何时候动态组件切换都能被正确渲染。

### What is actually happening?
多个组件动态切换，会有失灵的现象存在，只是这种情况非必现，多点几次切换再退出当前页面再进入页面，这样反复操作就会在某个时候一定会出现。

---
动态组件的生成是在当前页面组件初始化之前，曾经怀疑过组件异步加载原因造成代码异步。也就是页面组件初始化完毕，多个动态组件还没初始化完。

**Comment by fnlctrl** [comment]
请提供可运行的重现

**Comment by sodatea** [comment]
请提供一个可以运行的地方 demo。Reproduction link 不要乱填。

**Comment by f2009** [comment]
大佬好。真的是没有特定的重现环境。我也想通过重现找出问题的根源。
