### ISSUE TITLE
Select element: Binding initial value with :value and v-model causes different result

### ISSUE THREAD

**Issue by kevindaizj** [vuejs/vue#8607]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/573213/](https://jsfiddle.net/50wL7mdz/573213/)

### Steps to reproduce
When i use :value (v-bind:value) to bind initial value to select tag, it doesn't work. 
here is the code snippet: 
```
<!-- v-bind:value -->
  <div style="margin-top:10px;">
      <select :value="countryId" @input="countryId = $event.target.value">
         <option :value="null">Please Select</option>
         <option v-for="item in countryList" :value="item.id">{{item.name}}</option>
      </select>
  </div>

  <!-- v-model -->
  <div style="margin-top:10px;">
      <select v-model="vCountryId">
         <option :value="null">Please Select</option>
         <option v-for="item in countryList" :value="item.id">{{item.name}}</option>
      </select>
  </div>
```

```
new Vue({
  el: '#app',
  data: {
    countryId: 2,  //initial value binded by v-bind
    vCountryId: 2, //initial value binded by v-model
    countryList: []
  },
  mounted () {
    const $this = this;
    setTimeout(() => {
       $this.countryList = $this.getCountryList();
    }, 100);
  },
  methods: {
  	getCountryList() {
    	return [
           { id: 1, name: 'Vue' }, 
           { id: 2, name: 'React' }, 
           { id: 3, name: 'Angular' }
       ];
    }
  }
})
```

### What is expected?
Initial value binding with v-bind should be set properly, just as v-model binding

### What is actually happening?
Initial value binding with v-bind has not been set properly

**Comment by posva** [comment]
with `select`s element you have to actually set the `selected` attribute in the `option`s elements

**Comment by kevindaizj** [comment]
I really want to figure out, in my example, why v-model work perfectly but v-bind didn't. 
I think :value + @input is equal to v-model.

**Comment by posva** [comment]
> I think :value + @input is equal to v-model

That's only for components 😉 , for form elements, the behaviour is adapted. As I said, select elements are changed by setting the selected attribute in the options elements

You should use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions
