### ISSUE TITLE
how to disabled validate the type and format on <input type="number" />

### ISSUE THREAD

**Issue by shangxinbo** [vuejs/vue#8611]
### What problem does this feature solve?
I make a app page in mobile. And I want to get number type keybord so I set input type="number".But I want this input can input a number with blank, like this "213 43444 234". but vue tell me that is not a valid number and clear the input. the key point is 
1.I want to get number keyboard
2.I want to input number with formatter like '213 344345 345'

### What does the proposed API look like?
vue can options to valid input type

**Comment by shangxinbo** [comment]
the error throw like that
The specified value "123 " is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

**Comment by sodatea** [comment]
Please provide a runnable reproduction.

This message comes from the browser itself, so I'm not sure if it is related to Vue without a reproduction.

**Comment by shangxinbo** [comment]
sorry, I find it's the problem of browser.
