### ISSUE TITLE
Don't escape HTML char codes in mustache expressions

### ISSUE THREAD

**Issue by GabrielRatener** [vuejs/vue#8615]
### What problem does this feature solve?
Currently if you want to have html with unescaped char codes you must use the `v-html` directive since with regular mustache expressions all HTML gets escaped. Would it be possible to escape HTML tags and such, but retain char codes in mustache expressions? This would make the injected text secure while still allowing users to put in special characters. Then if need be those char codes could also be escaped through a filter. I find `v-html` to be very inelegant, especially since you can't use certain features (e.g. filters) in those directives.

### What does the proposed API look like?
I'm proposing for the next breaking release, this be added in Vue mustache expressions as default rendering, but until then it could be added as an option of some sort.

**Comment by posva** [comment]
If by HTML escape you are talking about `&#x1f469;&#x1f3ff;` and similar, keep in mind, it's not the same as js escapes `\u{1f469}`.
If you need to only unescape a specific set of characters, you can do that in a method and pass that to `v-html`

---


You may be interested in the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js), you can get faster answers there :)

**Comment by GabrielRatener** [comment]
@posva I know already know of `v-html`, it doesn't cut it for what I'm trying to do. I'm trying to keep my codebases clean and neat without using hacks or workarounds, and using `v-html` is highly inelegant, especially considering the lack of features when compared to mustache expressions.

Since I don't want to use `v-html` could you possibly point me to where in the codebase the HTML gets escaped? That way I can build my own version with my own escape function.
