### ISSUE TITLE
Duplicate dom in v-if's change duplicates select tag change in v-else/v-else-if/other v-if

### ISSUE THREAD

**Issue by jschatz1** [vuejs/vue#8616]
### Version
2.5.16

### Reproduction link
[JSFiddle](https://jsfiddle.net/vuo89gd4/)

### Steps to reproduce
1. Change select in "first" to "B".
1. Click the "second" tab. 
ER: the select in "second" will still have it's default value. 
AR: the select in "second" was changed to the index of the first select.

Furthermore:  
1. Change the input in "first" to anything
1. Click the "second" tab. 
ER: the input in "second" should be blank. 
AR: the input in "second" is not black, but contains the contents of the "first" tab. 

### What is expected?
The select in "second" will still have it's default value. 

### What is actually happening?
The select in "second" was changed to the index of the first select.

---
If you add an ID or a class to either container div to make them non identical, it won't happen.

**Comment by jschatz1** [comment]
If we add a `key` to each `div`, it is not reproducible. The reason I think it happens is because vue is trying to reuse the `select`, which it does reuse because it's the same, but then the selected property get's brought along with it.

**Comment by posva** [comment]
This is expected. It doesn't happen if you bind the `selected` attribute or use `v-model`.
You can also use a key if you don't need to host the variable
