### ISSUE TITLE
Doesn’t it support to use “$event” in custom vue event?

### ISSUE THREAD

**Issue by TonyLuo** [vuejs/vue#8617]
### Version
2.5.17

### Steps to reproduce
```
<my-component @my-event=“handleThis(123, $event)”>
```

### What is expected?
no warning

### What is actually happening?
[Vue warn]: Property or method "$event" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

---

when I use $event in custom component, it shows vue warning in chrome console

```
[Vue warn]: Property or method "$event" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

**Comment by posva** [comment]
This does work but you didn't provide a repro

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by TonyLuo** [comment]
it works , but it shows warning in chrome console

**Comment by TonyLuo** [comment]
![image](https://user-images.githubusercontent.com/3250305/43822112-b7c25b0a-9b1d-11e8-979c-8198f523fa83.png)

**Comment by jacekkarczmarczyk** [comment]
Screenshot of the error message is not a reproduction
https://stackoverflow.com/help/mcve

**Comment by TonyLuo** [comment]
i try to reproduce in jsfiddle, but behaves are difference in jsfiddle and in my local pc. 
it doesn't show warning info in jsfiddle

https://jsfiddle.net/mj3fu0gs/

**Comment by posva** [comment]
You probably have something different in your code 🙂 . Please use the forum or discord chat

**Comment by Ankit1q** [comment]
vue.esm.js?efeb:591 [Vue warn]: Property or method "info" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Application> at src/Application.vue
       <App> at src/App.vue
         <Root>

**Comment by rramo** [comment]
For info, I get the same issue when using "v-bind:click" instead of "v-on:click".
https://jsfiddle.net/Lvqznx9f/

**Comment by BonBonSlick** [comment]
Reproduction fiddle https://jsfiddle.net/sf2nwoyv/

**Comment by furryablack** [comment]
use @click or v-on:click syntax

пт, 10 янв. 2020 г. в 14:48, BonBonSlick <notifications@github.com>:
