### ISSUE TITLE
this is a optimize for Comment RegExp

### ISSUE THREAD

**Issue by minzhang2** [vuejs/vue#8619]
### Version
2.5.17

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/src/compiler/parser/html-parser.js#L26](https://github.com/vuejs/vue/blob/dev/src/compiler/parser/html-parser.js#L26)

### Steps to reproduce
I find the Comment RegExp has a '\', but i find this '\' is no use, so maybe can remove this. for \^

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue/issues/7298
