### ISSUE TITLE
Suggesion: Add support for rest parameters within v-for

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#8620]
### What problem does this feature solve?
I think it would make template composition a lot easier in many cases, particularly when using scoped slots via renderless componetns. For example, we could do:

```vue
<Form>
  <template slot-scope="{ value, events, handleSubmit, ...props }">
   <form @submit="handleSubmit">
      <!-- pass other props to the component -->
      <error v-bind="props"></error>

      <input :value="value" v-on="events" :class="{ 'is-valid': props.valid }">
      <button @click="handleSubmit" type="submit">Submit</button>
    </form>
  </template>
</Form>
```

Rather than:

```vue
<Form>
  <template slot-scope="props">
   <form @submit="props.handleSubmit">
      <error v-bind="getErrorProps(props)"></error>
      
      <input :value="props.value" v-on="props.events" :class="{ 'is-valid': props.valid }">
      <button @click="props.handleSubmit" type="submit">Submit</button>
    </form>
  </template>
</Form>
```

### What does the proposed API look like?
No changes to the api

**Comment by posva** [comment]
That already works: http://jsfiddle.net/qxnerfwu/ 🙂 
If what you are asking it vue-loader handling the transformation, that should be done in vue-loader, but I remember it was asked/added some time ago 🤔

**Comment by sqal** [comment]
@posva hmm i tried adding appropriate buble  `transforms in vue-loader's options` My config now looks like this, but still can't make it work 🤔 

```js
{
  loader: 'vue-loader',
  options: {
    compilerOptions: {
      preserveWhitespace: false
    },
    transpileOptions: {
      transforms: {
      destructuring: true,
      parameterDestructuring: true,
      spreadRest: true,
    }
  }
}
```

**Comment by sqal** [comment]
Hi @posva sorry for pinging you but you closed the topic so quickly and feel that I didn't get and I feels that I haven't got proper answer to my question. I spent half a day trying to solve this problem by tweaking vue-loader's config but without success. Can you tell me what I'm doing wrong here or if this functionality event supported in SFC? Apreciate your help and time in this matter :)

**Comment by sqal** [comment]
Hi @posva sorry for pinging you but you closed the topic so quickly and feel that I didn't get proper answer to my question. I spent half a day trying to solve this problem by tweaking vue-loader's config but without success. Can you tell me what I'm doing wrong here or if this functionality event supported in SFC? Apreciate your help and time in this matter :)

**Comment by posva** [comment]
If I recall correctly it wasn't transpiled from SFC, so it only works on browsers that support it but at the same time, I remember seeing the feature request in vue-loader, yet I couldn't find it...

**Comment by sqal** [comment]
Also can't find anything about this in vue-loader's repo :(. Can we move this discussions to vue-loader's repo and you will pin feature request label to it? :)
