### ISSUE TITLE
Locally registering components ignores "name" field in favor of the imported object reference name (in specific cases)

### ISSUE THREAD

**Issue by travislaynewilson** [vuejs/vue#8622]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/l55zm7z6yz](https://codesandbox.io/s/l55zm7z6yz)

### Steps to reproduce
Create a component with a name that includes a title-cased acronym (like `edit-tv-modal`). Locally register that component by importing it and naming the reference something like `EditTVModal` and including it in the `components` section.

### What is expected?
The component should register the imported component using the name defined within the component's definition.

### What is actually happening?
The component's defined name is ignored; instead, the name of the imported object reference to the component is used instead, which is converted into a name that doesn't match the component's defined name.

---
I'm aware that naming the imported reference something like `EditTvMode` works, but the concern is that the defined name itself is being ignored. This example demonstrates that.

**Comment by posva** [comment]
This is normal, the naming comes from what name you use in the `components` option. The `name` property is used in other places like the devtools
