### ISSUE TITLE
Bug with transition-group and indexed animation

### ISSUE THREAD

**Issue by GustavoFenilli** [vuejs/vue#8623]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/584489/](https://jsfiddle.net/50wL7mdz/584489/)

### Steps to reproduce
Run the JSfiddle, if the v-for :key is index, when you delete one item from the array it will animate the last item, if you change to :key error, it will work properly but give an Vue warn: Avoid using non-primitive value as key, use string/number value instead. 
Vue Warn: Duplicate keys detected: '[object Object]'. This may cause an update error.

### What is expected?
Expected to animate the item that is being removed like using error.

### What is actually happening?
animating only the last item of the loop when using index.

---
Trying to create one alert notification component.

**Comment by posva** [comment]
This is expected, you need to use some unique identifier as the `key` otherwise Vue will reuse different elements because the index change if you remove an element in the array: https://jsfiddle.net/nhqrzsyf/
