### ISSUE TITLE
Can not input any, if  input attribute change caused by keydown

### ISSUE THREAD

**Issue by 383514580** [vuejs/vue#8624]
### Version
2.5.16

### Reproduction link
[https://codepen.io/russell2015/pen/NBEXRJ](https://codepen.io/russell2015/pen/NBEXRJ)

### Steps to reproduce
device: mac chrome68
input text

### What is expected?
input text

### What is actually happening?
can not input text

**Comment by protos1000000** [comment]
It happens because your input bind to the text value, but text value never changes.

Change keydown method like this:

keydown(keyEvent) {
      this.text += keyEvent.key;
  }

**Comment by 383514580** [comment]
I guess attribute changes will  change invoke  'render' element, but i just wanted attribute  change, vue can not well done the demand

@protos1000000

**Comment by posva** [comment]
This is expected. You are changing a variable `hasWarning` that triggers a rerender and because the `value` passed to the input is the same as before, Vue will set it again when it renders. If you want to keep changes, use a `v-model` with another property
