### ISSUE TITLE
[Vue + Typescript] Property does not exist on type in computed function

### ISSUE THREAD

**Issue by zhuscat** [vuejs/vue#8625]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/10l5yrl9rq](https://codesandbox.io/s/10l5yrl9rq)

### Steps to reproduce
Codesandbox seems not support typescript code intelligense in `*.vue`, the file is `src/index.vue`

Here is the code:

```typescript
<script lang="ts">
import Vue from 'vue'

interface TestInterface {
  a: string
}

export default Vue.extend({
  props: {
    prop1: {
      type: Object as () => TestInterface,
    },
  },
  computed: {
    computed1() {
      return this.prop1.a
    }
  }
})
</script>
```

### What is expected?
Typescript compiler will not complaint

### What is actually happening?
Property 'prop1' does not exist on type '{ computed1(): any; }'.

Is there any way to solve this problem?

**Comment by ktsn** [comment]
Please read https://vuejs.org/v2/guide/typescript.html
You should do the following things to make type inference works.

- set `strict: true` or `noImplicitThis: true` for compiler option.
- annotate return type of computed properties.

**Comment by zhuscat** [comment]
Thank you!

**Comment by spaceemotion** [comment]
Sorry for the necro, but I am still getting this error when the computed property is not a function, but rather a get+set construct like this:

```js
interface Props {
  label: string,
}

export default Vue.extend({
  props: {
    value: {
      type: Object,
      required: true,
    } as Props,
  },

  computed: {
    label: {
      get() {
        // Property 'value' does not exist on type '{ get(): string; set(val: string): void; }'.
        return this.value.label;
      },
      set(val: string) {
        this.$emit('update:label', val);
      },
    },
  },
};
```

I am using the latest vue-cli typescript setup (just set it up this week), strict mode is enabled and I think I got the return types covered. Is there anything I'm missing? Thanks!

**Comment by wal0x** [comment]
> Sorry for the necro, but I am still getting this error when the computed property is not a function, but rather a get+set construct like this:
> 
> ```js
> interface Props {
>   label: string,
> }
> 
> export default Vue.extend({
>   props: {
>     value: {
>       type: Object,
>       required: true,
>     } as Props,
>   },
> 
>   computed: {
>     label: {
>       get() {
>         // Property 'value' does not exist on type '{ get(): string; set(val: string): void; }'.
>         return this.value.label;
>       },
>       set(val: string) {
>         this.$emit('update:label', val);
>       },
>     },
>   },
> };
> ```
> 
> I am using the latest vue-cli typescript setup (just set it up this week), strict mode is enabled and I think I got the return types covered. Is there anything I'm missing? Thanks!
> 
> Edit: It looks like I had a single computed property that was not documented, which caused this error. Seems to work now.

What does "having a single computed property that was not documented" means ?

**Comment by rndmerle** [comment]
Pretty sure he meant that one of its computed properties didn't have an explicitly return type.
```
get(): string {
```

**Comment by spaceemotion** [comment]
I was going to check out my code base but it looks like I can no longer find the place. If @rndmerle's suggestion does not help, just ping me again :)

**Comment by rehdie** [comment]
> ### Version
> 2.5.17
> 
> ### Reproduction link
> https://codesandbox.io/s/10l5yrl9rq
> 
> ### Steps to reproduce
> Codesandbox seems not support typescript code intelligense in `*.vue`, the file is `src/index.vue`
> 
> Here is the code:
> 
> ```ts
> <script lang="ts">
> import Vue from 'vue'
> 
> interface TestInterface {
>   a: string
> }
> 
> export default Vue.extend({
>   props: {
>     prop1: {
>       type: Object as () => TestInterface,
>     },
>   },
>   computed: {
>     computed1() {
>       return this.prop1.a
>     }
>   }
> })
> </script>
> ```
> 
> ### What is expected?
> Typescript compiler will not complaint
> 
> ### What is actually happening?
> Property 'prop1' does not exist on type '{ computed1(): any; }'.
> 
> Is there any way to solve this problem?

I had the same problem and used this workaround:

```
 computed: {
     computed1() {
       return this['prop1'].a
     }
   }
})

```

**Comment by truonghoangphuc** [comment]
I still facing this issue and none of solution above can work for me!

**Comment by Shinseiten** [comment]
> I still facing this issue and none of solution above can work for me!
> The warning Property 'xxx' does not exist on type '{ yyy(): String; }' showing but the site work correctly on DEV env. However it can't build as it stuck in this error.


Same problem here...

**Comment by truonghoangphuc** [comment]
> > I still facing this issue and none of solution above can work for me!
> > The warning Property 'xxx' does not exist on type '{ yyy(): String; }' showing but the site work correctly on DEV env. However it can't build as it stuck in this error.
> 
> Same problem here...

Fixed all.

**Comment by zhuqingguang** [comment]
> Please read https://vuejs.org/v2/guide/typescript.html
> You should do the following things to make type inference works.
> 
> * set `strict: true` or `noImplicitThis: true` for compiler option.
> * annotate return type of computed properties.

@ktsn  hi~it looks like that this method cannot work for `render` function. 

![image](https://user-images.githubusercontent.com/24694223/75764894-87439280-5d79-11ea-9252-c323a4fac5db.png)

**Comment by ktsn** [comment]
Please don't post a question to already closed issue for years ago. You can use [forum](https://forum.vuejs.org), [chat](https://chat.vuejs.org) or StackOverflow to ask your question.

---

You should write render function in class component to inter types.

**Comment by zhuqingguang** [comment]
Thank you very much for give me the resolution and sorry to bother you.

**Comment by stayacid** [comment]
Let me left a note for everyone who're confused as i am: annotate ALL return types of computed properties.

**Comment by GustavoFenilli** [comment]
This also happens on methods, vscode can find those at runtime, but at compile time it gives error in every 'this' used inside a method.

**Comment by scomma** [comment]
@GustavoFenilli how did you fix that? right now vue on typescript is giving me more pain than it's worth

**Comment by GustavoFenilli** [comment]
> @GustavoFenilli how did you fix that? right now vue on typescript is giving me more pain than it's worth
> 
> Edit: I already checked the forum and found [this question](https://forum.vuejs.org/t/typescript-property-xx-does-not-exist-on-type-vue/46118) asked in 2018 with 0 answers. The poster just worked around it by casting `(this as any)`.

Don't really remember what I did, we changed the project to not use typescript and class type components, we are using now vue 2.6 with vue composition and javascript.

**Comment by alexisjamet** [comment]
I had the same issue `Property 'sender' does not exist on type '(() => any) | ComputedOptions<any>'.
  Property 'sender' does not exist on type '() => any'.Vetur(2339)`

My code was like: 

```
props: {
    message: {
      type: Object as PropType<Message>,
      required: true,
    },
  },

computed: {
  isPostedByUser() {
    return this.message.sender.type === 'user'
  },
  isPostedByRobot() {
    return this.message.sender.type === 'robot'
  },  
etc...
```

In order to solve this issue, I just added a return type on **each** computed variable.

```
computed: {
  isPostedByUser(): boolean {
    return this.message.sender.type === 'user'
  },
  isPostedByRobot(): boolean {
    return this.message.sender.type === 'robot'
  },  
etc...
```

**Comment by Laerolf** [comment]
I had the same issue, and I know this issue has been closed for some time now but it could maybe help people who are also just starting  with TypeScript and Vue :)

My issue was that I got the error "**Property 'value' does not exist on type '(() => any) | ComputedOptions<any>'. Property 'value' does not exist on type '() => any'.ts(2339)**" for `return this.value` in the computed get of `computedValue`:

```
export default Vue.extend({

    props: {
        value: { type: Number, default: 0 }
    },

    computed: {
        computedValue: {
            get(): number {
                return this.value;
            },
            set(newValue) {
                this.$emit("input", newValue);
            }
        }
    },

    methods: {
        decreaseCounterValue() {
            this.computedValue -= 1;
        },
        increaseCounterValue() {
            this.computedValue += 1;
        }
    }
})
```

In order to resolve my issue, I added a type to the parameter of the computed set function:

```
export default Vue.extend({
    name: 'AbbeyCounter',

    props: {
        value: { type: Number, default: 0 }
    },

    computed: {
        computedValue: {
            get(): number {
                return this.value;
            },
            set(newValue: number) {
                this.$emit("input", newValue);
            }
        }
    },

    methods: {
        decreaseCounterValue() {
            this.computedValue -= 1;
        },
        increaseCounterValue() {
            this.computedValue += 1;
        }
    }
})
```

Hope this helps for other people :) Have a great day!

**Comment by benoitkopp** [comment]
```
props: {
    value: {
      type: Boolean,
      required: true,
    },
  },
  computed: {
    show: {
      get(): boolean {
        return this.value
      },
      set(show: boolean): void {
        this.$emit('input', show)
      },
    },
  },
```
Set all types for parameters and methods 👍

**Comment by mouday** [comment]
thank you

**Comment by skyshy0707** [comment]
> Please read https://vuejs.org/v2/guide/typescript.html You should do the following things to make type inference works.
> 
> * set `strict: true` or `noImplicitThis: true` for compiler option.
> * annotate return type of computed properties.

I did set all of this, but i still get this critical warning in my VSCode: Property '$emit' does not exist on type '{ selectContentType(event: any): void; }'.ts-plugin(2339)

```
<script lang="ts">

    import { defineComponent, PropType } from 'vue'
    import type LessonData from '../structures/annotations';

    export default defineComponent({
        props: {
            lesson: Object as PropType<LessonData>,
            isDisabled: Boolean,
            createLesson: Boolean
        },
        methods: {
            selectContentType(event: any): void {
                console.log(`Target: ${event.target.value}`)
            
                this.$emit('')
            }
        }
    })
</script>
```

If this feature related to specific typescript type recognition but code is working, could this warning to be ignored?

As documentation says: 

_If you're using Options API, you need to set compilerOptions.strict to true (or at least enable compilerOptions.noImplicitThis, which is a part of the strict flag) to leverage type checking of this in component options. **Otherwise this will be treated as any**_

It's just treated as any type only as i thought.
