### ISSUE TITLE
Self closing element wraps the following text-node

### ISSUE THREAD

**Issue by JrSchild** [vuejs/vue#8626]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/7cgsqt9h/](https://jsfiddle.net/7cgsqt9h/)

### Steps to reproduce
Run the fiddle

### What is expected?
A closing `i` element before the text-node.  
`<a href="#"><i class="fa"></i>Test</a>`

### What is actually happening?
The text-node is wrapped in the `i` element.  
`<a href="#"><i class="fa">Test</i></a>`

**Comment by sodatea** [comment]
1. Remove vue from the demo & you still get the same result.
2. There are no "self closing tags" in HTML5, it's an XHTML syntax which is now outdated and you should never use it. See http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5
