### ISSUE TITLE
<transition> doesn't work with v-show

### ISSUE THREAD

**Issue by matthewma7** [vuejs/vue#8631]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/tucyeg82/](https://jsfiddle.net/tucyeg82/)

### Steps to reproduce
Run the jsfiddle example

### What is expected?
The [documentation](https://vuejs.org/v2/guide/transitions.html#ad) for <transition> says it works with v-show, but only with a [single element](https://jsfiddle.net/x293b7yt/)

It is expected to works in a similar fashion as v-if like [this](https://jsfiddle.net/qcg7day5/)

### What is actually happening?
Error is thrown saying needs transition-group

**Comment by maxirozay** [comment]
It does work for me try to put 2 seconds to your transition to see it. But yes you can have only one element in the `transition` tag else you need to use `transition-group` that works the same way.

For your example you can bind the value to the element like:
```
<transition name="fade" mode="out-in">
  <p :key='flag'>{{ flag }}</p>
</transition>
```

or use `v-if ` and `v-else` instead of `v-show` because the v-if can't render the 2 elements at the same time while v-show technically can (even if it's never going to happen with your condition).

**Comment by posva** [comment]
What @maxirozay said

**Comment by matthewma7** [comment]
Hi, @maxirozay, @posva 

As it [stated ](https://vuejs.org/v2/guide/transitions.html#Transition-Modes) and observed, a <transition> is used with v-if, if no mode is specified, there is clearly a moment there is more than one element exists. 

The place I am trying to use v-show is with two different custom components, not as simple as my example.
Using transition-group has an apparent drawback of [layout clashing](https://vuejs.org/v2/guide/transitions.html#Transition-Modes) because the mode attribute is not supported.
The reason I am trying to use v-show is to use v-show to prevent the component from being destroyed to keep the component state. (I tried to use keep-alive, but seems keep-alive is not designed for my case)

So, does it make sense to have a feature request for support of <transtion> with v-show?
Or do you have some other suggestion for my keep-alive needs?

Sincerely,

**Comment by posva** [comment]
I don't see why keep-alive wouldn't work but that would rather be a discussion on the forum or the discord server 😄
I'm sure you will find your way 😉
