### ISSUE TITLE
Vue DevTools recommendation only shows for Chrome, not Firefox

### ISSUE THREAD

**Issue by digitarald** [vuejs/vue#8634]
### Version
2.5.17

### Reproduction link
[http://localhost:8080](http://localhost:8080) (any local dev setup)

### Steps to reproduce
- Run any dev build
- Open the page Firefox without vue devtools installed
- Open devtools console

### What is expected?
Devtools extension gets recommended

### What is actually happening?
Recommendation only shows for Chrome, not in Firefox

---
Logic is in https://github.com/vuejs/vue/blob/master/src/platforms/web/runtime/index.js#L51

Twist is that `isChrome` is only used in this one code; so maybe it could be changed to `hasCompatibleExtension` and include a Firefox UA detection. Alternatively UA detection can be dropped, so the link is always shown and users can figure out that they might switch browsers to use the devtools.

**Comment by posva** [comment]
I know we can show it for Firefox and Safari as well. @znck @Akryum is it possible to always display it once we have the remote devtools or does something else need to be changed?

**Comment by kotAPI** [comment]
Can I take this up? :)

**Comment by yyx990803** [comment]
Closed via #8638
