### ISSUE TITLE
2.5.17 === 2.5.16

### ISSUE THREAD

**Issue by DontShootMe** [vuejs/vue#8646]
### Version
2.5.17

### Reproduction link
[https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/](https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/)

### Steps to reproduce
the last release, from every CDN, is exaclty the same as the v2.5.16 !
The only thing that got changed / updated is the version value !

https://github.com/vuejs/vue/releases/tag/v2.5.17

### What is expected?
The v2.5.17 release being different from v2.5.16

### What is actually happening?
The v2.5.17 release is the same as v2.5.16

---
* [dist v2.5.16@jsdeliver](https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/)
* [dist v2.5.17@jsdeliver](https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/)

* [dist v2.5.16@unpkg](https://unpkg.com/vue@2.5.16/dist/)
* [dist v2.5.17@unpkg](https://unpkg.com/vue@2.5.17/dist/)

**Comment by posva** [comment]
This is normal, that release fixed a security bug that only affect SSR, thus not included in the client version of Vue

**Comment by DontShootMe** [comment]
ok thanks !
Sorry for the noise !
