### ISSUE TITLE
Event listener for "invalid" is not working

### ISSUE THREAD

**Issue by petr001** [vuejs/vue#8647]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/2p6zqqo75j](https://codesandbox.io/s/2p6zqqo75j)

### Steps to reproduce
When form is in invalid state no event handler is called

### What is expected?
v-on:invalid should run the handler function

### What is actually happening?
nothing

**Comment by LinusBorg** [comment]
Not Vue-related,

That event is fired in the input element, not the form element, and the event [doesn't bubble](https://developer.mozilla.org/en-US/docs/Web/Events/invalid).

So this works as expected:
```html
<template>
  <form ref="form" @submit.prevent="handleSubmit">
    <input @invalid="handleInvalid" required>
    <button type="submit">Submit</button>

    <p>{{ msg }}</p>
  </form>
</template>

<script>
export default {
  name: "HelloWorld",
  data: () => ({
    msg: 'Not validated yet'
  }),
  methods: {
    handleSubmit() {
      this.msg = 'submit event fired';
    },
    handleInvalid() {
      this.msg = 'invalid event fired';
    }
  }
};
</script>
```

**Comment by petr001** [comment]
Not true. If you manually bind invalid on <form> it works correctly!

**Comment by petr001** [comment]
This is link for vanilla and working javascript: https://codesandbox.io/s/3vl6rq4jmm
