### ISSUE TITLE
ASYNC Method called from Vue Template returns 'undefined'

### ISSUE THREAD

**Issue by fsaiyedOB** [vuejs/vue#8653]
### Version
^2.5.13

### Reproduction link
[https://jsfiddle.net/fsaiyed/ewgdh120/](https://jsfiddle.net/fsaiyed/ewgdh120/)

### Steps to reproduce
From the vue template, I'm calling a methods to render data as:

```
<td v-if="fieldNumber ==0">
         {{ getName(item.service) }}
     </td>
```

and in methods:

```
getName: async function (taskId) {
        taskId = await this.titleCase(taskId)
        let resultName = await deepRecord.deepRecord.getCurrentTraget(this.instanceId, taskId)
        let name = resultName.name
        console.log('Name: ', JSON.stringify(name))
        return name
      }
```

Here, in the console, I get the value, but it does not return to the template

### What is expected?
Methods should return value

### What is actually happening?
Method returns 'undefined'

**Comment by sodatea** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Return_value

Return value of async functions are `Promise` instances

**Comment by Justineo** [comment]
Hi. Return value of an async function is a `Promise` instance so you should not use it in the template.

I've modified your fiddle and this is how it suppose to work: https://jsfiddle.net/gcva5bk4/.

**Comment by fsaiyedOB** [comment]
Still doesn't work: https://jsfiddle.net/fsaiyed/ewgdh120/9/

**Comment by fsaiyedOB** [comment]
@Justineo , your code will work if my `str` is static, but as given in the about example, my data loops through `items`. So here, I cannot call method from mounted.

**Comment by fsaiyedOB** [comment]
@sodatea , Promise still returns empty object : https://jsfiddle.net/fsaiyed/ewgdh120/10/

**Comment by fsaiyedOB** [comment]
Any help, please?

**Comment by Justineo** [comment]
You were filing a bug report but it's actually the expected behavior so the issue is closed. Maintainers don't have to ask for permission to do this.

> @Justineo , your code will work if my str is static, but as given in the about example, my data loops through items. So here, I cannot call method from mounted.

Just loop through your `items` to make multiple network requests and maintain the resolved value in an local data array. This is not something Vue should take care of and you should decide how to organize your application logic yourself.

**Comment by Nabute** [comment]
@faizansaiyed, This kind of situation happens always, when you are implementing asynchronous operations. It can be solved using **promise chaining** which means 

> executing two or more asynchronous operations back to back, where each subsequent operation starts when the previous operation succeeds, with the result from the previous step.

`const promise = doSomething();`
`const promise2 = promise.then(successCallback, failureCallback);`

so here is the modified [JSFiddle](https://jsfiddle.net/20rmwtuh/8/)

I hope it's helpful.

Enjoy!

**Comment by Mel-honey7** [comment]
Cum4nPNl3qb5 Answer’s checked off
