### ISSUE TITLE
Something like v-bind, but also for other directives.

### ISSUE THREAD

**Issue by vladislav-ladicky** [vuejs/vue#8660]
### What problem does this feature solve?
Cleaner template code, especially with libs like Vuetify, heavily depending on bunch of props / directives.

### What does the proposed API look like?
    <template>
      <my-comp expand="attrs.myComp">
        <nested-comp expand="attrs.nested" />
      </my-comp>
    </template>

    <script>
    export default {
      computed: {
        attrs () {
          return {
            myComp: {
              'v-on:click': this.myCallback
              class: 'some css classes'
              // bunch of other props / directives
            },
            nested: {
              // same here
            }
          }
        }
      }
    }
    </script>

**Comment by posva** [comment]
you are probably looking for `v-bind` and `v-on` with no arguments: `v-bind="{ value: myValue, disabled: isDisabled }"`

**Comment by vladislav-ladicky** [comment]
Unfortunately, I'm not. As I said, I'm looking something like v-bind, not for v-bind. Because in v-bind you can use props only, not the directives too.

**Comment by posva** [comment]
If you need that much dynamicity, it's probably time to use render functions with js 🙂
