### ISSUE TITLE
Vue Component Cannot Support Self-Closing-Tag Well

### ISSUE THREAD

**Issue by LaiHuanMin** [vuejs/vue#8664]
### Version
2.5.16

### Reproduction link
[https://gist.github.com/LaiHuanMin/4f1485410fb5092a25712b755a25e20b](https://gist.github.com/LaiHuanMin/4f1485410fb5092a25712b755a25e20b)

### Steps to reproduce
Sorry the example code is not running on JSFiddle or JSBin, because it's very short and I cannot access those website quckly.   
The example code is a html file, it contains a cdn link for vue,  and Vue Component regist code, and Vue instance init code.   
You can put it into nginx or another web-server, and directly access this html, you could see the content below the component self-closing-tag is missed.  If you change the self-closing to a common close way, there's will no question like before.  
I always use vue by cdn, not with build, because there's some old project cannot support build way to develop;

### What is expected?
The content should be displayed which under auto-closing-tag

### What is actually happening?
The content is missing, and change auto-closing way  into common way, the question will be fixed

---
I'm running at chrome lastest version, not ie, not firefox, it's may not a compatible question.

**Comment by jacekkarczmarczyk** [comment]
https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

**Comment by posva** [comment]
this is an html5 limitation. put a debugger before new Vue and you will get to see what Vue receives as a template 😉 . This limitation doesn't exist with string templates or vue files

**Comment by LaiHuanMin** [comment]
@posva @jacekkarczmarczyk  Thanks! I understanded.
