### ISSUE TITLE
Auto bind `this` for object type v-on

### ISSUE THREAD

**Issue by jasonxia23** [vuejs/vue#8669]
### What problem does this feature solve?
```javascript
const clickObj = {
  click() {
    console.log(this) // this will be null or window, depent on the environment.
  }
}

new Vue({
  el: '#app',
  data() {
    return {
      clickObj,
    }
  },
  template: `<div v-on="{clickObj}">unbind this</div>`
})
```
Maybe it is better to bind `this` in `v-on` directive, so developer can get Vue instance without bind `this` themselves.

### What does the proposed API look like?
Auto bind  `this` in `v-on` directive

**Comment by posva** [comment]
Thanks for the proposal but usually, the functions come from methods or are arrow functions defined in a computed property. Having the function defined outside is quite uncommon, and we do not get that much less as it could be even achieved with a helper that adapt to your specific needs (as most of the times you want to use methods or fat arrows).
Besides that, we prefer explicit behaviours, so doing `bind` in the app is preferable
