### ISSUE TITLE
vue typescript 子组件的created方法没有效果

### ISSUE THREAD

**Issue by danny00lo** [vuejs/vue#8670]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/617477/](https://jsfiddle.net/50wL7mdz/617477/)

### Steps to reproduce
当父组件引入子组件中，created方法的 没有效果，但是设置其函数则会有效果

### What is expected?
打印console.log

### What is actually happening?
没有打印

**Comment by sodatea** [comment]
麻烦提供一个可以运行的 demo，比如一个附上复现步骤说明的 GitHub 仓库。

**Comment by posva** [comment]
You probably have a typo in `created`

**Comment by danny00lo** [comment]
@sodatea https://github.com/danny00lo/vueShake2
麻烦帮忙看一下 真的不知道为什么在子组件没有反应，但是在父组件是有反应

**Comment by sodatea** [comment]
Footer 类没有加 @Component 装饰器

**Comment by danny00lo** [comment]
@sodatea 还要加一个component?

**Comment by danny00lo** [comment]
@sodatea 我看看文档理解一下，是有反应了
