### ISSUE TITLE
weex + vue. I can't create :-(

### ISSUE THREAD

**Issue by cybermerlin** [vuejs/vue#8671]
Hey guys,
the command `weex create my-proj` finished but not create the project. 
I mean the my-proj was not created. 
What I doing wrong? 
I see only two line:
```
r:\>weex create my-proj
This command need to install weexpack. Installing...
? Project name my-proj
? Project description (A weex project)
r:\>
```

help me please

**Comment by cybermerlin** [comment]
if u not need my help, then I'll go to ReactNative side.
You should not ask me about rules for creating this issues

**Comment by yyx990803** [comment]
Weex and Vue are separate projects. Also feel free to use whatever you like - I don't really care.

**Comment by cybermerlin** [comment]
@yyx990803 are u sure? =)
somebody so bad knowing this proj 

https://github.com/vuejs/vue/blob/f319bef532dd0d3cae4302e7a6a038d45e7363ba/flow/weex.js

or search
https://github.com/vuejs/vue/search?utf8=%E2%9C%93&q=weex&type=

**Comment by Justineo** [comment]
https://github.com/apache/incubator-weex
