### ISSUE TITLE
Use v-bind:style bind inline style auto-prefixes is invalid

### ISSUE THREAD

**Issue by se7668790** [vuejs/vue#8672]
### Version
2.5.2

### Reproduction link
[http://lfyfly.gitee.io/vue-basic-components/live-demos/#/vue-carousel](http://lfyfly.gitee.io/vue-basic-components/live-demos/#/vue-carousel)

### Steps to reproduce
no

### What is expected?
width: 700%;-webkit-transform: translate(-71.4286%); transform: translate(-71.4286%); -webkit-transition: transform 0.5s;transition: transform 0.5s;

### What is actually happening?
width: 700%; transform: translate(-71.4286%); transition: transform 0.5s;

**Comment by posva** [comment]
the prefixes will apply when necessary 🙂 
Next time, please, do provide the steps to reproduce like what element to look at. Your repro is really complex
