### ISSUE TITLE
Make Calls to Backend REST Server part of Vue, please

### ISSUE THREAD

**Issue by BenHayat** [vuejs/vue#8674]
### What problem does this feature solve?
Could you please build the similar functionality of Axios or Vue-Resource as part of Vue framework, as most Vue usage being a "Client" framework, requires a backend to talk to, so being part of Vue is a natural place.
Secondly, one less third party to depend on for future updates and code reliability, as this is a critical part of Data transmission for performance, reliability and scalability.

And I'd like to take this opportunity to "Thank" the team for building such awesome framework (Vue.js). THANK YOU!
..Ben

### What does the proposed API look like?
I'd leave that to the team as they know this better to fit into their API structure.

**Comment by phanan** [comment]
@BenHayat Also, you can always make something "part of Vue" by adding it as an instance property. We even have an [official example](https://vuejs.org/v2/cookbook/adding-instance-properties.html#Real-World-Example-Replacing-Vue-Resource-with-Axios) where you can access axios as `this.$http`.
