### ISSUE TITLE
Offer option for synchronous server rendering

### ISSUE THREAD

**Issue by jnields** [vuejs/vue#8681]
### What problem does this feature solve?
What benefit does asynchronous server rendering offer? I argue that it's very little if any.

Making the `renderToString` function async guarantees that the oldest requests being processed aren't the highest priority (this is very bad!). It also leads to more memory usage: rendering eight requests asynchronously and simultaneously means that the non-blocking call requires all eight requests' resources be held in memory at once instead of just one at a time (this is also very bad!).

Offering a simpler API would not only be easier for developers, but it would guarantee requests are prioritized in order (don't use resources for the next request until we've finished the last request). It would also decrease memory usage (less overhead overall) and unnecessarily queueing tasks to the event loop (less overhead overall and per request).

### What does the proposed API look like?
```
import { createRenderer } from 'vue-server-renderer';

const renderer = createRenderer({ runInNewContext: false });

app.get('/', (req, res) => {
  const markup =  renderer.renderToStringSync(new Component());
  res.end(markup);
});
```

**Comment by LinusBorg** [comment]
> What benefit does asynchronous server rendering offer? I argue that it's very little if any.

The primary reason that it's async is that Vue's internal scheduler works async as well. And making this a completely synchronous process without altering the behaviour of the app isn't really possible (to my incomplete knowlde of all internals - I'm happy to be corrected).

> Making the renderToString function async guarantees that the oldest requests being processed aren't the highest priority (this is very bad!).

I freely admit that I' not an expert about HTTP request performance etc. what's so *very* bad about it?

**Comment by wojtask9** [comment]
it is possible. see https://github.com/vuejs/vue/pull/6651

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue/pull/6651#issuecomment-334024444
