### ISSUE TITLE
Linting error if props contains Array

### ISSUE THREAD

**Issue by numfin** [vuejs/vue#8684]
### Version
2.5.17

### Reproduction link
[https://jsbin.com/casiwowibe/edit?html,js,output](https://jsbin.com/casiwowibe/edit?html,js,output)

### Steps to reproduce
Typescript build   Array props item

```javascript
export default Vue.extend({
  props: {
    items: {
      type: Array,
    },
  },
  data() { return {hi: 'there'}; },
  methods: {
    boom() {
      this.hi;
    },
  },
});
```

### What is expected?
boom() not contain linting error

### What is actually happening?
property hi does not exist on type Vue
![image](https://user-images.githubusercontent.com/8134947/44387773-15a54a00-a52f-11e8-9046-89a59a0611db.png)

**Comment by phanan** [comment]
I believe this belongs to [vetur's repo](https://github.com/vuejs/vetur).

**Comment by davidlandais** [comment]
It's not a Vetur bug. I run into a similar problem right now using Vue 2.6 and typescript with a project scaffolded by the CLI. When using `foo: {type: Array }` in props. Typescript throw a `Property 'foo' does not exists on type 'Vue'` but if you define the type like `foo: { type: Array as Array<YourInterface | number | string | ...> }` Inference is working good. An article explain [how to use vue with typescript without vue-class-component](https://frontendsociety.com/using-a-typescript-interfaces-and-types-as-a-prop-type-in-vuejs-508ab3f83480). I hope this could help.
