### ISSUE TITLE
`Duplicate keys detected` in v-for if using a functional component

### ISSUE THREAD

**Issue by ivansieder** [vuejs/vue#8685]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/986x7y34v4?expanddevtools=1](https://codesandbox.io/s/986x7y34v4?expanddevtools=1)

### Steps to reproduce
First of all, this is the first Issue I've created on this project. So I'll take this opportunity to thank all of the contributors and maintainers for the awesome and astonishing work they do for Vue. THANKS!

Having a functional component and trying to use it inside a v-for produces a `Duplicate keys detected` error, even if using :key="<unique identifier>". It's fixable by just converting the component to a non-functional one.

According to my understanding of functional components and the way :key="" works, even functional components (without a state) should be :key-able, as that isn't related to the state of the component itself.

According to Chris Fritz (https://twitter.com/ivansieder/status/1030374407515058177) the issue is also present in earlier versions.

### What is expected?
The v-for renders the component without any error.

### What is actually happening?
The v-for renders the component with a `Duplicate keys detected` error.

**Comment by posva** [comment]
This has actually to deal with vue-loader because of the data (and more specifically the key) not being passed implicitly when doing a template. Could you open an issue there (if it doesn't exist yet).
When writing it in JS, you usually do:

```js
  render: (h, context) => h('div', context.data, ['Placeholder'])
```
and data contains the attribute `key` you passed from the parent
