### ISSUE TITLE
Global Error Handling in Vuejs Applcation

### ISSUE THREAD

**Issue by hamidh2** [vuejs/vue#8686]
Hi every one 
Im looking for a way to catching Errors globaly in vuejs application .
I mean when we use "axios" to  call some service we are using 'then' and 'catch' method normally
working with then and catch is  ok   if we work with one method 
but when we have some method (three or more) that we call these method  wirting catch method for every then method is somehow annoying for us.
so im looking for global Error Handling like global Error Handling that implented in agngulatr2+.

**Comment by leopiccionia** [comment]
@hamidh2 Vue currently provides `config.errorHandler`: https://vuejs.org/v2/api/#errorHandler

It has well-known limitations, some of them probably addressed in upcoming 2.6 release. See if it fits your needs.
