### ISSUE TITLE
Cannot install Vuex on subclass due to missing static properties

### ISSUE THREAD

**Issue by dcherman** [vuejs/vue#8690]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/n9jmu5v7/21025/](https://jsfiddle.net/n9jmu5v7/21025/)

### Steps to reproduce
Open the reproducer and look in the console to see the errors

### What is expected?
Vuex should successfully be installed on the Vue subclass

### What is actually happening?
Due to the dependency on static properties that are not copied, errors are thrown

---
We're attempting to use VueX in a component library without exposing it outside of the boundaries of our library and ran into this bug when attempting to install VueX globally on a subclass that would be specific to our library.

Based on the code, it seems like it's intended that one should be able to call `.use` on a subclass and have that plugin be isolated to the subclass.

I'm not sure exactly where this should be considered a bug or where a patch should be made.  VueX is using `Vue.version` and `Vue.config` internally which are both part of the public API, but are not copied to the subclass when doing `Vue.extend`.  We could also make VueX traverse the inheritance/prototype chain until it reaches the root Vue class and pull the properties from there.

**Comment by posva** [comment]
Vuex is meant for apps, not for libraries. You can use inject/provide or a shared object to sharing data in a lib

**Comment by dcherman** [comment]
@posva Thanks for the advice, but ultimately that is not what this issue is about.  I am using a plugin that depends on public API provided by Vue (`config`, `version`) and it does not successfully install on a subclass of Vue.

That the plugin happens to be Vuex doesn't matter for this discussion; it could be any plugin that maybe wants to silence logging if `Vue.config.silent` is set.

This is all public API and intended usage.  Here's a unit test from Vue to prove the point that you should be able to install a plugin on a subclass without polluting the root.

https://github.com/vuejs/vue/blob/dev/test/unit/features/global-api/use.spec.js#L30-L35

**Comment by posva** [comment]
I don't understand, you are explicitly talking about Vuex being the problem

**Comment by dcherman** [comment]
I am talking about the fact that `Vue.extend` does not properly subclass Vue by including static props, making it required to know implementation details of how a plugin is implemented in order to use it on subclasses of Vue.

Here's a simple reproducer using a hello world plugin that I made to demonstrate.

https://jsfiddle.net/1t7cgkjp/8/
