### ISSUE TITLE
Component update not updating other components

### ISSUE THREAD

**Issue by Sja91** [vuejs/vue#8691]
### Version
2.5.17

### Reproduction link
[https://codepen.io/anon/pen/BOyVWB?editors=1010](https://codepen.io/anon/pen/BOyVWB?editors=1010)

### Steps to reproduce
Begin typing into either of the first two input boxes, these are both components, the third is a simple vanilla input box.

### What is expected?
I would expect the v-model to update all of the components like it does the vanilla input.

### What is actually happening?
Updating either of the two components causes the label and the vanilla input to update, but not eachother.

---
Here I created a workaround, with a way I expected it to behave.
https://codepen.io/anon/pen/jvEKBq?editors=1010

However I feel like the v-model on each component should be updating it.
I had assumed it was a mistake on my part, until I looked at other examples of v-model on components, and simply copy pasted the component again in the html, I was surprised to find it was indeed doing the same thing as my own code. The codepens I provided were in fact from one of those other sources.

Thank you in advanced for your help.

**Comment by sodatea** [comment]
You didn't sync the inner `content` when 'value' prop updates.

See here for a correct example of using nested `v-model`s: https://codepen.io/sirlancelot/pen/gWBLEK
