### ISSUE TITLE
prop type array can accept null

### ISSUE THREAD

**Issue by alonesuperman** [vuejs/vue#8692]
### What problem does this feature solve?
father.vue
```
<template>
    <div>
        <child :foo="null" />
    </div>
</template>
<script>
import child from "./child.vue";

export default {
    components: {
        child,
    },
};
</script>
```
If I want child.vue accept the prop "foo" etiher Number or null
How could I do?

One solution may be like follow:
```
// child.vue
<script>
export default {
    props: {
        foo: {
            required: true,
            validator:function(val){
                return typeof val === "number" || val === null;
            }
        },
    },
};
</script>
```
**But** it looks too verbose. Can it be described simply like follow
```
// child.vue
<script>
export default {
    props: {
        foo: {
            required: true,
            // my imagination
            type:[Number,null]
        },
    },
};
</script>
```
It certainly failed. Because the function assertType of source code in vue/src/core/util/props.js  was:
```
const simpleCheckRE = /^(String|Number|Boolean|Function|Symbol)$/

function assertType (value: any, type: Function): {
  valid: boolean;
  expectedType: string;
} {
  let valid
  const expectedType = getType(type)
  if (simpleCheckRE.test(expectedType)) {
    const t = typeof value
    valid = t === expectedType.toLowerCase()
    // for primitive wrapper objects
    if (!valid && t === 'object') {
      valid = value instanceof type
    }
  } else if (expectedType === 'Object') {
    valid = isPlainObject(value)
  } else if (expectedType === 'Array') {
    valid = Array.isArray(value)
  } else {
    valid = value instanceof type
  }
  return {
    valid,
    expectedType
  }
}
```
When the first element(Number) of types array call this function , it worked well.
But the second element(null) of  types array call this function , it does not match expection.  
That's because the param "type" was not a function so that the getType function could not work.
![image](https://user-images.githubusercontent.com/21165139/44444801-2a5a0e80-a611-11e8-9197-0698d70dc51b.png)

So maybe the easiest way to solve this feature was do extra judge for null in the assertType function

### What does the proposed API look like?
```
export default {
    props: {
        foo: {
            required: true,
            type:[Number,null]
        }
    }
}
```

**Comment by 574495412** [comment]
一般用Boolean类型可以解决你的需求吧

**Comment by KaelWD** [comment]
`type: Number` already does accept null.

**Comment by posva** [comment]
If you want it to accept null, make it either non-required or use a validator 🙂 

PS: Next time take the time to create the small fiddle, it does help us

**Comment by alonesuperman** [comment]
@posva 
But if it must be required , I can only use a validator.
I had wrote I knew validator is one solution, but it's too verbose. So I think it's a feature request

**Comment by posva** [comment]
a validator is fine. Remeber prop validation only happens during development
