### ISSUE TITLE
Should get default value if perent send null in props.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [vuejs/vue#8695]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/j97btnex/35/](https://jsfiddle.net/j97btnex/35/)

### Steps to reproduce
Child component should use default value. When parent send null in props.

Parent
```
<child :data="some_data_that_give_null_value"
></child>
```

Child.
```
<script>
    export default {
        props: {
            data: {
                type: Number,
                default: 99,
            },
        },

        mounted() {
            console.log(data);
        },
    }
</script>
```

### What is expected?
```
99
```

### What is actually happening?
```
null
```

**Comment by KaelWD** [comment]
I imagine this would break quite a few things. If you want the default value, pass `undefined` instead.

**Comment by LinusBorg** [comment]
As @KaelWD said...

**Comment by Justineo** [comment]
Just convert `null` values to `undefined` before you pass them into the prop, or just don't produce nullable values before this.

**Comment by KaelWD** [comment]
https://jsfiddle.net/emn64yxz/

**Comment by ThunderBirdsX3** [comment]
@KaelWD Thank you so much.
