### ISSUE TITLE
new Vue() event bus doesn't delete _events keys on event removal

### ISSUE THREAD

**Issue by LaeticiaW** [vuejs/vue#8696]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Laeticia/mqo5fy7p/2/](https://jsfiddle.net/Laeticia/mqo5fy7p/2/)

### Steps to reproduce
Create global event bus (new Vue), add event listener using eventBus.$on, then remove the listener using eventBus.$off.  The eventBus._events object will still contain the event name with value null, rather than deleting the event name property.

In jsFiddle, click Add Event Listener and Remove Event Listener buttons.  The _events object is displayed in the jsfiddle and also in the javascript console after adding and removing listeners.

### What is expected?
After removing an event listener, I expect that event name to be removed from the global event bus (Vue) _events object.

### What is actually happening?
The event name is still in the _events object with value null.

---
When using a lot of unique event names, although the app tries to clean up the events via eventBus.$off, the event names are still in the _events object.  Unless these null properties get cleaned up at some point, it appears to be a memory leak.

**Comment by posva** [comment]
Thanks, but this is not a memory leak since properties are not arbitrarily added to that object, you are in control of what events are added to the bus.
BTW it can be cleanup by creating a new `_events` object

**Comment by LaeticiaW** [comment]
Hmm, isn't the issue that $off doesn't completely clean up what was created by $on?
