### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by microblue** [vuejs/vue#8697]
### Version
2.5.17

### Reproduction link
[http://void.com](http://void.com)

### Steps to reproduce
npm install web3 --save

Add line:
import Web3 from 'web3'

Add the code into Helloworld.vue  data() 
----
    var Web3 = require('web3')

    var w3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/PJvt2iaCmRWlE83VpqZk'))
    var abi_main = require('./abi_main.json')
    var contract_main = new w3.eth.Contract(abi_main,'0xA62142888ABa8370742bE823c1782D17A0389Da1')
    contract_main.methods.getCurrentRoundInfo().call().then (info => {
    	console.log(info)
    })
------

### What is expected?
Successful call a smart contract function.

### What is actually happening?
error at undefined process.versions.node  in xml-http-request.js.  

---
vue 2.0 work well, but vue 3.0 packed app has this error.

**Comment by fnlctrl** [comment]
This is not related to vue. Also there's no vue 3.0 at the moment.
