### ISSUE TITLE
Add support for optional components when using <component> tag

### ISSUE THREAD

**Issue by mariuszjamro** [vuejs/vue#8700]
### What problem does this feature solve?

Currently when using `<component is="foo"></component>` syntax and the component `foo` doesn't exist an warning is produced:

>  vue.common.js:593 [Vue warn]: Unknown custom element: &lt;foo&gt; - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I would like to propose an extension to allow optional components, which won't provide the warning if component doesn't exist.

### What does the proposed API look like?

1. Attribute which will prevent the warning:

       <component is="foo" optional></component>

2. Slot content rendered if component not found. This actually works, but is not documented. It would be nice to have it docs:

       <component is="foo" optional>Component not found</component>

**Comment by maxirozay** [comment]
You could also do:
```
<component v-if="foo" is="foo/>
<div v-else>Component not found</div>
```
It produce the same result.

**Comment by posva** [comment]
This is better achieved in userland with a render function. You could also make sure the component exists in a computed property returning a component fallback.
An example of this:

```js
const OptionalComponent = {
	props: ['render'],
  functional: true,
  render: (h, { children, props, parent }) => {
  	let Comp = (parent.$options.components && parent.$options.components[props.render]) || Vue.component(props.render)
  	return Comp ? h(Comp) : children
  }
}
```

```html
<OptionalComponent render="Foo">fallback content here</OptionalComponent>
```

Although I don't know what is your use-case behind this. It seems really weird to have a dynamic component use a non-existent component
