### ISSUE TITLE
Mark Functional components in DOM so thay can be displayed in vue developer console

### ISSUE THREAD

**Issue by 1099511627776** [vuejs/vue#8701]
### What problem does this feature solve?
Functional components will be displayable and debugable in vue developer console

### What does the proposed API look like?
1. Add additional property __vue_func__  to HTMLelement that contains object with basic information about functional component (e.g. context, props etc).
2. Property from 1 will be scanned with vue developer tools and displayed

**Comment by panstromek** [comment]
Support for functional components is already in the making AFAIK. It has been mentioned in Vue.js Sprint summary lately.

**Comment by posva** [comment]
I believe this is already tracked by @Akryum somewhere else. @Akryum reopen if you really want to track this in both sides 🙂

**Comment by Akryum** [comment]
In devtools 5.0 functional components are displayed. We just need to merge https://github.com/vuejs/vue/pull/8586 to be able to display their props.
