### ISSUE TITLE
Prop with type Boolean but no default will be set to false

### ISSUE THREAD

**Issue by ericcirone** [vuejs/vue#8704]
### Version
2.5.17

### Reproduction link
[https://codepen.io/ericcirone/pen/OoyKwz](https://codepen.io/ericcirone/pen/OoyKwz)

### Steps to reproduce
1. Make a prop and set it to be `Boolean` with no `default`

### What is expected?
The prop would be `undefined` if it was not set.

### What is actually happening?
The prop is `false`

---
Setting a prop to any other type and not setting a default value will result in `undefined`. A prop of type `Boolean` should act the same way.

**Comment by posva** [comment]
This is expected behaviour for convenience. If a prop is supposed to be a boolean, it's either present or absent, therefore true or false

**Comment by mesqueeb** [comment]
What about cases where you want to calculate if the prop should be `true` or `false` but only if it's `undefined`.
