### ISSUE TITLE
Modified options not added to extended component when mixin is applied to super component

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue#8710]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/hf817t54/](https://jsfiddle.net/hf817t54/)

### Steps to reproduce
Run the code with the console open. undefined is logged. Comment out the mixin, true is logged because the late option is persisted.

### What is expected?
Late option should be kept

### What is actually happening?
It's overwritten

---
The late option is [added to `extendOptions`](https://github.com/vuejs/vue/blob/dev/src/core/instance/init.js#L106), but `extendOptions` is a class function, so it should be added to extendOptions.options.

Merge options then uses `extendOptions.options`, so the late option is not included in the merge.

EDIT:

Here's a fix https://github.com/vuejs/vue/pull/8711

**Comment by yyx990803** [comment]
The usage is wrong: `Vue.extend()` was never designed to accept a constructor - it can only accept objects. This works by accident because the option merging logic handles constructors, but that was intended for using constructors as mixins, not for `Vue.extend()`.
