### ISSUE TITLE
<component is="input"> loosing reactivity

### ISSUE THREAD

**Issue by visualjerk** [vuejs/vue#8712]
### Version
2.5.17

### Reproduction link
[https://codepen.io/CharlyTheDog/pen/wEMZyq](https://codepen.io/CharlyTheDog/pen/wEMZyq)

### Steps to reproduce
1. Change the value in default input
1. Change the value in component input
1. Change the value in default input again

### What is expected?
Both inputs keep being reactive in each step

### What is actually happening?
The component input stops being reactive after step 2

---
I ran into this issue while trying to compose a generic form input component that can either be an "input" or "textarea". Wondering if this is just a general misuse of dynamic components? I found it to be pretty convenient, because both input and textarea share lots of styles, props and functionality. For now I will refactor this to use v-if instead.

**Comment by posva** [comment]
You need to use the `.prop` modifier on `value` as it is bound to a dynamic component (this is done automatically when binding on an input

**Comment by visualjerk** [comment]
Thanks for the clarification!
