### ISSUE TITLE
Pass component instance to async import

### ISSUE THREAD

**Issue by ssipos90** [vuejs/vue#8715]
### What problem does this feature solve?
In the context of a multi-tenant site, we import some templates based on the site (we have some site codes) for example:
```js
import config from 'Scripts/config.js';
const HomeSearch = site_code => () => import(`Components/sites/${site_code}/top-nav/home-search.vue` /* webpackChunkName: 'home-search' */);

export default {
  // other stuff
  components: {
    HomeSearch(config.site_code)
  }
}
```
and in a more complex scenario, reactivity would be awesome.

### What does the proposed API look like?
Since that config ends up in vuex at application boot, it would be nice instead of doing that, to do this:

```js
import { mapState } from 'vuex';
const HomeSearch = vm => import(`Components/sites/${vm.site_code}/top-nav/home-search.vue` /* webpackChunkName: 'home-search' */);

export default {
  // other stuff
  computed: {
    ...mapState({ site_code: state => state.config.site_code  }) // or use mapGetters
  },
  components: {
    HomeSearch
  }
}
```
AFAIK, when saying `() => import(...)` and passing it to the `components: {}`, it already receives a couple of arguments so I guess it would be easier if the `vm` arg would be the third one for backwards compatibility and the end feature request would look like:

```js
const HomeSearch = (a, b, vm) => import(`Components/sites/${vm.site_code}/top-nav/home-search.vue` /* webpackChunkName: 'home-search' */);
```
or we could define the function classically and bind the component context to it and use `this` like so:

```js
const HomeSearch = function() { return  import(`Components/sites/${this.site_code}/top-nav/home-search.vue` /* webpackChunkName: 'home' */) };
// or
function HomeBanner() { return  import(`Components/sites/${this.site_code}/content/home-banner.vue` /* webpackChunkName: 'home */) };
```

I know in my scenario, I could import the vuex store and do it like that, but in general, other vm props or data could be used in that import function.

**Comment by ssipos90** [comment]
I really don't have a preference for the implementation, though the arrow function would be cleanest. Maybe some splat operators could work, IDK.

**Comment by posva** [comment]
You can actually already do that with a computed property:


```js
asyncComponent() {
	return import(`Components/sites/${this.site_code}/top-nav/home-search.vue`)
}
```

and then use it in a `component`'s `is attribute:

```vue
<component :is="asyncComponent"/>
```

**Comment by ssipos90** [comment]
Awesome!!

**Comment by ssipos90** [comment]
@posva please update your code and add `() => ` at the return line

**Comment by posva** [comment]
no, that's intentional

**Comment by ssipos90** [comment]
Well, if I remove the arrow fn, I get errors:
```[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>```

**Comment by ssipos90** [comment]
`console.log` returns the object just fine, though:
```
_Ctor: Object [ VueComponent() ]
__file: "components/sites/snuk/nag-popup-content.vue"
beforeCreate: Array [ makeOptionsHot() ]
beforeDestroy: Array [ makeOptionsHot()]
methods: Object { showJoinUs: mappedAction() }
render: function render()
staticRenderFns: Array [ staticRenderFns() ]
<prototype>: Object { … }
```

**Comment by ssipos90** [comment]
It works without the arrow function if I declare the property as a method, not as a computed property.
