### ISSUE TITLE
Transition-group animates only last element if using index as the key

### ISSUE THREAD

**Issue by megacromulent** [vuejs/vue#8718]
### Version
2.5.17

### Reproduction link
[https://codepen.io/megacromulent/pen/gdMYLx?editors=1010](https://codepen.io/megacromulent/pen/gdMYLx?editors=1010)

### Steps to reproduce
1. Create vue app with items displaying in a list.
2. Add transition group with **v-for** with format like **v-for="(item, index) in items"**
3. Use "index" from v-for as the **v-bind:key** (like: v-bind:key="**index**" )
4. Add and remove items from the data.

### What is expected?
The item being removed/added should have the transition applied to it.

### What is actually happening?
The last item in the list gets the transition applied.

---
This may be an old bug, as I was hunting for a solution to my problem, I ran into this from May 2017:

https://stackoverflow.com/questions/43598308/vue-js-wrong-transition-group-animation-position

If this is the intended behavior using index as the key, then can their be at least a warning message in the dev version of Vue.js to explain this? Or perhaps searchable text in the documentation with something like "only last item in list is animating/transition applied" so a solution can be found without thinking there is a bug in Vue.js.

**Comment by posva** [comment]
This is expected, the key controls how Vue reuses elements/components and is therefore crucial for transition-group. You can read more about it in the guide 🙂

**Comment by posva** [comment]
Using the index as the key is the default behaviour. If you have propositions about notes to add to the docs, you should open a Pull Request with your proposal on the vuejs.org repository 🙂. Maybe a not on transition-group page is the right place
for the last example, all the keys are changing so Vue is replacing every single li.

Remember you can use the [forum](http://forum.vuejs.org/) and the [Discord server](https://vue-land.js.org/) to get quick feedback on questions 🙂

**Comment by Justineo** [comment]
From Vue's perspective, `key` is used to identify unique items in a list. 

Let me give you an example: assume we have `['a', 'b', 'c', 'd']` and rendered a list out of this array using `v-for` and keyed the items with their indexes. When you remove `'b'` from the list, you are telling Vue that item `1`(`key`) is now `'c'`, item `2` is now `'d'` and item `3` is now removed. As transition occurs when an element/component got added/removed/showed/hide from the view, only the last item will be transitioned out.

**Comment by megacromulent** [comment]
@Justineo 

Thanks for the explanation, that certainly clears up why the errors are happening. 

But the results (which look like errors) are not documented anywhere that I could find, and if they are, not easily found.

> ...open a Pull Request with your proposal on the vuejs.org repository...

I didn't even consider this idea, so I will do that. I've never done a PR before, so I hope I don't make more of a mess.

Thanks guys.

**Comment by davidgolden** [comment]
+1 Also experiencing this issue. Switched to different keys and it works. @megacromulent I've also never done a PR and would be interested in collaborating if you want a second pair of eyes.

**Comment by megacromulent** [comment]
Hey, thanks for the offer. The only thing I would do is put documentation
in, I don't have the JS skills to contribute to a library like Vue.js.
Thanks for the offer though.

**Comment by awacode21** [comment]
I am experiencing the same problem.
I understand, that each list element needs a key. That is super clear.
So i loop through my array (containing objects) and set the key with :key="index".
When i then remove one item of my array, the transition group always transitions the last element in list instead of the one i removed.
I think that is a bug with transition-group, isn't it? Any solution on that?

Example code:
https://jsfiddle.net/eywraw8t/427894/

**Comment by ggaabe** [comment]
Was getting this issue as well. I'm creating a dynamic list where every new item added is blank and so there are multiple duplicates. Tried using the item as the key but get a warning not to use non-primitives. The v-move transition works on creation but not deletion of items.

**Comment by NE-SmallTown** [comment]
This https://github.com/vuejs/vue/pull/8748 pr doesn't give any explaination which seems not standard. The problem is that the `key` rule/problem appears everywhere, not just `<transition-group>`, we should just give a **warning rather than error** because in some situations we will **not** change the order of the array/list. Just throw error like now is opinionated

**Comment by Rabbitzzc** [comment]
+1. This needs to be represented by a unique key. At the same time, when the data changes, can you ensure that the key is still unique after re-rendering.
