### ISSUE TITLE
使用eventBus的时候，在组件销毁时清除事件监听，再次进入页面$on 监听事件不起作用了

### ISSUE THREAD

**Issue by Polaris-z** [vuejs/vue#8720]
### Version
2.5.16

### Reproduction link
[http://localhost:8080/device/gnss](http://localhost:8080/device/gnss)

### Steps to reproduce
 我在组件内监听事件 ，销毁时清除。第一次进入组件监听成功
 第二次进入页面的时候 事件监听不会生效 
 在控制台输出 eventBus  _events字段 后面显示的是空对象
``` s
beforeDestroy () {
    window.$eventBus.$off()// 组件销毁时 移除自定义事件监听器
  },
  created () {
    this.getList()
    window.$eventBus.$on('handleSearch', target => {
      this.searchParams = target
      this.getList()
    })
    window.$eventBus.$on('handleCreate', target => {
      this.create(target)
    })
    window.$eventBus.$on('handleUpdate', target => {
      this.update(target)
    })
    window.$eventBus.$on('handleDelete', target => {
      this.onDelete(target)
    })
  }
```

### What is expected?
希望解决问题

### What is actually happening?
...

---
...

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue and provide a valid repro, you can use this: http://jsfiddle.net/posva/wsr78d2w/
Thanks!

**Comment by weiweibupt** [comment]
请问您找到原因了吗  原因是什么
