### ISSUE TITLE
Independent props validator

### ISSUE THREAD

**Issue by axetroy** [vuejs/vue#8725]
### What problem does this feature solve?
1. Reduce packet size

> not every component need it.

2. Reused validator

> If I want to validate the params. I don't need to introduce another validator

### What does the proposed API look like?
```javascript
const Vue = require('vue');

// defined customer validator
Vue.validator = function (schema, input){
  // 
}

// run validator
Vue.validate({
  name: {
    type: String,
  },
  age: {
    type: Number,
  },
});
```

**Comment by sodatea** [comment]
1. Removing a feature is a breaking change so we won't do it in 2.x.
2. It does not reduce much packet size, if any.
