### ISSUE TITLE
Improve prop validator API

### ISSUE THREAD

**Issue by znck** [vuejs/vue#8726]
### What problem does this feature solve?
- Allows to write validation logic depending on multiple props.
- Allows to provide custom validation messages.

### What does the proposed API look like?
``` ts
type Validator = (value: any, key: string, props: Object, warn: (message: string) => void) => boolean
```

Example:

``` js
export default {
  props: {
    foo: {
      validator(value, key, props, warn) {
        if ('bar' in props && 'foo' in props) warn('Foo and Bar cannot be used together.')
        return true
      }
....
```

**Comment by visualfanatic** [comment]
Should not the `warn` function be returned to stop the rest of the `validator` code from executing?

**Comment by kayandrae07** [comment]
I'm a fan of adding the prop as an argument. I think we can return a string from the validator function and let Vue treat that as an error.

My counter proposal is

```
type Validator = (value: any, key: string, props: Object) => boolean | string
```

**Comment by znck** [comment]
Closing in favor of #9467. Also, I think changing arguments of prop validator function would require an RFC now.

**Comment by dietergeerts** [comment]
@see https://github.com/vuejs/vue/issues/9467#issuecomment-465708425
