### ISSUE TITLE
Possible memory leak: list of dependencies grows in computed getter

### ISSUE THREAD

**Issue by cm-app** [vuejs/vue#8727]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/wo84dxjc/2/](https://jsfiddle.net/wo84dxjc/2/)

### Steps to reproduce
In the fiddle, click on the results window multiple times.

Notice that I modified vue.js as follows: 

```javascript
function createComputedGetter (key) {
  return function computedGetter () {
    var watcher = this._computedWatchers && this._computedWatchers[key];
    if (watcher) {
      if (watcher.dirty) {
        //modification:
        if(window.ipc > 2) {console.log(key, watcher.deps.length, watcher); }; 
		watcher.evaluate();
      }
      if (Dep.target) {
        watcher.depend();
      }
      return watcher.value
    }
  }
}
```

### What is expected?
Frontend: Console logs "update" twice: init and one data update.
Backend: dependency-array keeps size

### What is actually happening?
Frontend: Console logs "update" on every click.
Backend: dependency-array grows

---
In the fiddle, you will only notice the frontend effects. Not sure how I can provide my modified vue.js.

**Comment by posva** [comment]
I tested using the latest version of vue and the count of deps goes back to 2 when the array is emptied and there is no memory leak

**Comment by cm-app** [comment]
Oh ok. Sorry, I misinterpreted the deps array's purpose.
