### ISSUE TITLE
Drop special logic for “enumeratedAttrs”

### ISSUE THREAD

**Issue by Justineo** [vuejs/vue#8731]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/Justineo/upwrqm0z/](http://jsfiddle.net/Justineo/upwrqm0z/)

### Steps to reproduce
Bind `'plaintext-only'` or an unsupported value to `contenteditable` attribute.

### What is expected?
Rendering `contenteditable="plaintext-only"` for the element.

### What is actually happening?
`contenteditable="true"` is rendered.

---
For reference:

| `:contenteditable` | `contentEditable` in Vue | `contentEditable` in HTML ||
| -- | -- | -- | -- |
| `""` | `'true'` | `'true'` ||
| `"false"` | `'false'` | `'false'` ||
| `"true"` | `'true'` | `'true'` ||
| `"plaintext-only"` | `'true'` | `'plaintext-only'` | ❗️ |
| `"foo"` | `'true'` | `'inherit'` | ❗️ |
| `null` | `'false'` |||
| `undefined` | `'inherit'` |||
| `false` | `'false'` |||
| `true` | `'true'` |||

Vue currently treat `enumeratedAttrs` as enumerated attributes with only `'true'`/`'false'` values (boolean-like enumerated attributes) and this made them behave like boolean attribtues. While actually these attributes may have more than two states and are extensible for other values. For example, in HTML, `contenteditable`'s corresponding IDL attribute `contentEditable` resolves to `'inherit'` instead of `'false'` when `contenteditable` is not  present. And the latest W3C draft has also defined more possible values for it (`'plaintext-only'` is already accepted in Chrome) so we have to remove this logic, otherwise developers can't leverage these new features.

And if we drop the `enumeratedAttrs` thing and treat them like other ordinary attributes, there will be some influence on the following cases:

| `v-bind` | before | after |
| -- | -- | -- |
| `null` | `'false'` | / |
| `false` | `'false'` | / |

I'm not sure if we should regard this as breaking because we never documented this usage that binding `null`/`false` to `contenteditable`/`draggable`/`spellckeck` will be resolved as `'false'`.

**Comment by kayandrae07** [comment]
I came to open this issue too. Contenteditable has a couple states. [W3C Contenteditable](https://w3c.github.io/editing/contentEditable.html#editing-states) for reference

**Comment by Justineo** [comment]
The issue is already planned to be fixed in Vue 3. So close this one.
