### ISSUE TITLE
Option is not selected when custom select uses domProps

### ISSUE THREAD

**Issue by minhchu** [vuejs/vue#8742]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/6vzq6mqpok](https://codesandbox.io/s/6vzq6mqpok)

### Steps to reproduce
I create a custom `select` component with `domProps` as the docs [suggested](https://vuejs.org/v2/guide/render-function.html#v-model):
```
<script>
export default {
  render: function(h) {
    const self = this

    return h('select', {
      domProps: {
        value: self.value
      }
    }, self.$slots.default)
  }
}
</script>
```
Then I use that `select` in another component like this:
```
    <CustomSelect v-model="selected">
      <option
        v-for="(option, index) in options"
        :key="index"
        :value="option.value"
        :selected="option.value === selected"
      >
       {{ option.text }}
      </option>
    </CustomSelect>
```
However, no option is selected.

### What is expected?
An option must be selected

### What is actually happening?
No thing is selected

---
When `domProps` is removed  it works fine. I open this issue because it relates to https://github.com/styled-components/vue-styled-components/issues/53

**Comment by Justineo** [comment]
For custom components to support `v-model` bindings, you need to define both prop `value` and event handler for `input`, which are missing in your reproduction. i.e. You are not following the suggestions of the doc.

**Comment by minhchu** [comment]
Hi @Justineo 
I've added the `input` event handler in the sandbox above but it doesn't work.
You can check the sandbox again

**Comment by Justineo** [comment]
You also need to declare a `value` prop for your custom component.

**Comment by minhchu** [comment]
It doesn't work either :(

**Comment by Justineo** [comment]
https://codesandbox.io/s/q8m3551q6j

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/44948300-beb44480-ae4d-11e8-986c-0c2fc9c8e0af.png)

(Chrome 68.0.3440.106)

**Comment by minhchu** [comment]
Open in a private tab and it works. Thank you !
