### ISSUE TITLE
[Feature request] Snap package support 

### ISSUE THREAD

**Issue by Mikerr1111** [vuejs/vue#8744]
I was thinking the setup and install process for Fedora, Ubuntu, and other Linux distros could be improved by having a [Snap package](https://snapcraft.io/) version. 

[Creating a Snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Create snaps from your preferred programming language](https://docs.snapcraft.io/build-snaps/languages)

[Linux distros with Snap support](https://docs.snapcraft.io/core/install)
![snap](https://user-images.githubusercontent.com/18353476/43989596-ec564800-9d01-11e8-89e6-8e0af1434f62.png)

**Comment by lauraknight72** [comment]
I don't know what the fuck my issue even was.

**Comment by lauraknight72** [comment]
You guys are fucking messing with me. Making me feel crazy. STOP!

**Comment by SeedyROM** [comment]
Is `npm install vue-cli` too hard to type?
