### ISSUE TITLE
vuejs.org home page contains a broken img

### ISSUE THREAD

**Issue by JinXJinX** [vuejs/vue#8745]
### Version
2.5.17

### Reproduction link
[https://drive.google.com/file/d/1gZSOEXKtxtsbQd9UNDE2LafK7z-kCsNx/view?usp=sharing](https://drive.google.com/file/d/1gZSOEXKtxtsbQd9UNDE2LafK7z-kCsNx/view?usp=sharing)

### Steps to reproduce
1. open https://vuejs.org/
2. go to 'Platinum Sponsors'.

Here is a snapshot https://drive.google.com/file/d/1gZSOEXKtxtsbQd9UNDE2LafK7z-kCsNx/view?usp=sharing

### What is expected?
an available image link

### What is actually happening?
broken image. image src (https://opencollective.com/vuejs/tiers/platinum-sponsors/1/website) returns a 404 not found message

**Comment by yyx990803** [comment]
Please open this at the corresponding repo. Vuejs.org has its own repo.
