### ISSUE TITLE
these dependencies not found but it actually not dependencies

### ISSUE THREAD

**Issue by erwinwahyura** [vuejs/vue#8746]
### Version
2.5.17

### Steps to reproduce
i actually just git pull from other branch
and run yarn serve

### What is expected?
expected run well when try to yarn serve vue-project

### What is actually happening?
These dependencies were not found:

* @/views/warehouse/delivery/DeliveryDetail.vue in ./src/router/warehouse-delivery/index.js
* @/views/warehouse/delivery/DeliveryMain.vue in ./src/router/warehouse-delivery/index.js
* @/views/warehouse/delivery/DeliveryParent.vue in ./src/router/warehouse-delivery/index.js
* @/views/warehouse/label/LabelDetail.vue in ./src/router/label/index.js
* @/views/warehouse/label/LabelMain.vue in ./src/router/label/index.js
* @/views/warehouse/label/LabelParent.vue in ./src/router/label/index.js
* @/views/warehouse/order/OrderDetail.vue in ./src/router/warehouse-order/index.js
* @/views/warehouse/order/OrderMain.vue in ./src/router/warehouse-order/index.js
* @/views/warehouse/order/OrderParent.vue in ./src/router/warehouse-order/index.js

To install them, you can run: npm install --save @/views/warehouse/delivery/DeliveryDetail.vue @/views/warehouse/delivery/DeliveryMain.vue @/views/warehouse/delivery/DeliveryParent.vue @/views/warehouse/label/LabelDetail.vue @/views/warehouse/label/LabelMain.vue @/views/warehouse/label/LabelParent.vue @/views/warehouse/order/OrderDetail.vue @/views/warehouse/order/OrderMain.vue @/views/warehouse/order/OrderParent.vue

---
the error says these dependencies were not found, but actually is not a dependencies it just some router in my vue project
i dont have any clue.

**Comment by erwinwahyura** [comment]
i think i should make this issue on vue-cli. sorry.

**Comment by ajuxxcode** [comment]
Had a similar issue and realised that I didn't put a / in @/

**Comment by zhenizhui** [comment]
got the same problem in Windows but the same project works well in mac OS.
