### ISSUE TITLE
v-html  希望能支持解析组件

### ISSUE THREAD

**Issue by liuchihanxiang** [vuejs/vue#8750]
### What problem does this feature solve?
一些动态的html字符串中 需要用到一些封装好的组件  

### What does the proposed API look like?
v-html

**Comment by Justineo** [comment]
It's clearly stated in the doc:

> If you find yourself trying to compose templates using v-html, try to rethink the solution by using components instead.

And plus, this will be a breaking change and will not be considered at the moment.
