### ISSUE TITLE
Allow mutating props

### ISSUE THREAD

**Issue by mknx-io** [vuejs/vue#8754]
### What problem does this feature solve?
I am currently building a SandBox component that allows playing in a live demo with a Vue Component.
The problem is, I encountered this common error: `"Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders"`. I know that it is a security rule of Vue.js, and I am not used to do this. Yeah it's a bad practice.

The thing is, by its functionality, my SandBox comp. needs to access these properties and to update them, and the reactivity process must update those values in the child component itself (the SandBox is the parent component with a `<slot>` tag).

I precise that even with this error, the reactivity is still here, and my values are well updated.
I searched again and again on how to use a workaround for this (most on StackOverflow say I need to use computed propeties or data), but if I don't use prop. values directly, the reactivity is not present, so the child component will not be updated.

I'm here to ask for help, if somebody knows how to update props by keeping the reactivity system, it should be great!
(Or if the Vue.js devs can add an option or a flag to disable this error, maybe...).

Thanks in advance!

### What does the proposed API look like?
Maybe a thing like this? A simple flag or option to disable "avoid mutating props" error.

    new Vue({
        el: '...',
        components: { ... },
        options: {
            mutatePropsError: false
        }
    })

**Comment by mknx-io** [comment]
Note: If needed, I can put the source code of my SandBox component.

**Comment by posva** [comment]
You should never mutate props, no silencing the error message is definitely not something we want to allow.
If the parent component re renders, you will lose the modification. It may look like it works right now but it will break as soon as the parent component re renders

You can suppress all warnings with https://vuejs.org/v2/api/#silent

**Comment by mknx-io** [comment]
Yes I know I should avoid that.
But as I said above, my component is a Sandbox, so in that case it needs to update props.
I don't care about parent re-rendering (this will not append when the developer is live-testing a component).
Since the parent is only loaded once, this is not important.

Thank you for your answer.

**Comment by mknx-io** [comment]
Or maybe you have a better idea to do this? A workaround

Here is the render (SandBox to the left, with editable fields that must update the visible child component values, and the Child (test) component to the right, that needs to be updated by editing the SandBox fields).

![screenshot from 2018-09-04 17-44-01](https://user-images.githubusercontent.com/6039926/45042075-2515ae80-b06a-11e8-89fa-eba19d759e74.png)

**Comment by posva** [comment]
Mutating props is an antipattern so we are not going to add a warning to silence it
You can ignore it if it works in your very specific scenario though...
If you want to ask questions, please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) 🙂

**Comment by mknx-io** [comment]
Ok I'll find a way to do this. Thank you for your time. Cheers :beer:
