### ISSUE TITLE
scopeslot and slot

### ISSUE THREAD

**Issue by dkl520** [vuejs/vue#8758]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/681226/](https://jsfiddle.net/50wL7mdz/681226/)

### Steps to reproduce
```javascript
  <script>
  Vue.component("tb-heading", {
            template: `
            <div> 
                <slot></slot>
                  <ul> 
                    <li v-for="(v,i) in list">
                    <slot :row='v'>  hei</slot>
                    </li>
                   </ul> 
                 <slot name='a'></slot>
            </div>
              `,
            props: {
                list: {
                    type: Array,
                    default: () => []
                }
            },
            mounted() {
                console.log(this)
            }
        })

   new Vue({
            el: '#app',
            data() {
                return {
                    data: ['zhangsan', 'lisi', 'wanwu', 'zhaoliu', 'tianqi', 'xiaoba']
                }
            },
        });
    </script>
 ```
```html
 <div id="app">
        <tb-heading  :list="data">
            <template slot="a">
                <a href="#">hello world</a>
            </template>
            <p>HELLO worldSSS</p>
            <p>hello</p>
            <template slot-scope="scope">
                <h3>
                    {{scope.row}}
                </h3>
            </template>
        </tb-heading>
    </div>
```

### What is expected?
所有的slot标签都应该被渲染出来

### What is actually happening?
作用域插槽和具名插槽有被渲染 匿名插槽无法渲染出来，此问题只存在与template语法中 用render不存在该问题

**Comment by Justineo** [comment]
Actually we cannot have a slot and a scoped slot with the same name, in this case, `default`. When rendering slots/scoped slots from a template, Vue looks for scoped slot by the specified name first, and then slot. When providing both an anonymous slot and scoped slot, the slot won’t have a chance to render.

See [render-slot.js](https://github.com/vuejs/vue/blob/dev/src/core/instance/render-helpers/render-slot.js).

This caveat seems to be missing in the docs and I think we should add it. /cc @chrisvfritz

**Comment by dkl520** [comment]
emmmmm,    all right   but I have   render  and it is fine

**Comment by Justineo** [comment]
When you use render functions, you are actually picking the exact slot to render by yourself so it's working.
