### ISSUE TITLE
The strategy of merging mixins property is incorrect

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue#8760]
### Version
2.5.17

### Reproduction link
[https://codepen.io/wangyi7099/pen/QVgzYJ](https://codepen.io/wangyi7099/pen/QVgzYJ)

### Steps to reproduce
Open the reproduction link, and then open dev-tool you will see an error `TypeError: Cannot read property 'b' of null` . It means that `b` isn't set value in created hook and the `created` in component `a` dosen't trigger. 

1. We initialized a component, that's right
```javascript
   var a = Vue.component('test-a', {
      data() {
        return {
          a: null
        }
      },
      mounted() {
        console.log(this.a.b);
      },
      mixins: [
        {
          created() {
            this.a = { b: 1 }
          }
        }
      ],
      template: '<div></div>'
    });
```
 2 But when we use `a.mixin` to mix an option that also contians a `mixins` property.  The previous `mixins` will be overridden by the current `mixins` property. This may be cased by using the `default` merge strategy rather than use concat to concat two `mixins` proerty. See relevant code.

https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/core/util/options.js#L401

```javascript
    a.mixin({
      methods: {
        sayBye() {
          console.log('Bye!');
        }
      },
      mixins: [{
        mounted() {
          console.log('aaa');
        }
      }]
    })
```

3. And when we change the root options by :
```javascript
   Vue.mixin({
      created() {
        this.sayTest();
      },
      methods: {
        sayTest() {
          console.log('hello test!');
        }
      }
    })
```
4. The  root options has changed, and let's jump to the `init` component stage:
https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/core/instance/init.js#L108
We can see the `mixins` proerty in `Ctor.extendOptions` has been overrode.

5. And when we are trying to  print `a.b` occurs an error. 

### What is expected?
`1` should be output.

### What is actually happening?
 `TypeError: Cannot read property 'b' of null`

---
I will send a PR if I have time

**Comment by posva** [comment]
Where did you pick up `a.mixin`? that api doesn't exist 🤔 I don't even know why the function is available
You can do this:

```js

    a.options.mixins.push({
      methods: {
        sayBye() {
          console.log('Bye!');
        }
      },
      mixins: [{
        mounted() {
          console.log('aaa');
        }
      }]
    })
```

**Comment by wangyi7099** [comment]
@posva 
Hi I get the `mix` in the source code, here:
https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/core/global-api/extend.js#L57

Which inherits `Super` constructor's `use` and `mixin` api.

**Comment by leeezhou** [comment]
生命周期钩子函数默认合并策略不支持你这样的做法。不过你可以传一个数组来替代。
```
var a = Vue.component('test-a', {
     data() {
        return {
          a: null
       }
     },
     methods: {
        sayBye() {
          console.log('Bye!');
        },
        sayTest() {
          console.log('hello test!');
        }
     },
     mixins: [
	 {
	    created:[
	       function(){
	           this.a = { b: 1 }
	       },
	       function(){
	          this.sayTest();
	       }
	    ]
	 },{
	    mounted: [
	      function(){
	         console.log(this.a.b);
	      },
	      function(){
	         console.log('aaa');
	      }
	    ]
	 }
    ],
    template: '<div></div>'
 });

var vm = new Vue({
    el: '#app'
}); 
```
