### ISSUE TITLE
是否可以考虑添加 data 属性的自动注册功能

### ISSUE THREAD

**Issue by chenyuan8059** [vuejs/vue#8764]
### What problem does this feature solve?
是否可以考虑将模版中表达式添加自动注册的支持，
比如 {{ user.name }} 自动在 data 中注册 user 对象和属性 name
因为有时候在写代码时会出现类似 {{ a.b.c.d.name }} 表达式，需要在 data 属性中预先定义好不然会报错，而且这种书写比较麻烦

### What does the proposed API look like?
添加类似于 AngularJs 中那样的在模版中写的表达式 {{ user.name }} 在 scope 作用域自动生成相应的对象和属性

**Comment by posva** [comment]
This is intended, we prefer explicit things. It also allows Vue to setup the reactivity system
