### ISSUE TITLE
<component :is=".."> should not set attributes to the root html tag of the component automatically

### ISSUE THREAD

**Issue by NE-SmallTown** [vuejs/vue#8765]
### Version

2.5.2
### Reproduction link
[https://codesandbox.io/s/2oz1p5qpo0](https://codesandbox.io/s/2oz1p5qpo0)

### Steps to reproduce
Open the reproduction link:

1. Open the devtools
2. The element with the `id="foo"` will have the `propa` attribute

### What is expected?
The element with the `id="foo"` doesn't have the `propa` attribute

### What is actually happening?
It has.

---
I know the problem is that the Foo component doesn't declare the `props` fields(I comment in the Foo component), if it has, the element with the `id="foo"` will not have the `propa` attribute, but the **problem** here is that the variable passed to `is` to `<component :is="...">` it not determined, probably it is a component which don't need the `propA` field.

So, we should not set any attribute to the root html tag of the component automatically.

**Comment by posva** [comment]
Please check `inheritAttrs` in documentation
This is intended as it makes things easier but you can opt out with the option above :)

**Comment by NE-SmallTown** [comment]
Thanks for your reply, but I think the better way is the default inheritAttrs should be `false`. If you want to use the inheritance, set it to `true`. I think this is what explicit means, rather than current representation.

**Comment by Justineo** [comment]
IMO in most cases we need `inheritAttrs` to be `true`. When developing a reusable component, you certainly don't want to enumerate all possible HTML attributes manually with `$attrs`, eg. `id`, `title`, `hidden`, `draggable`, `aria-*`, `data-*`, etc. In most cases we want to transparently output these attributes into the root element. If `inheritAttrs` defaults to `false`, there's a large chance we would set it to `true`, or to loop through all properties in `$attrs` and output them to the root element, for each component.

---

BTW. You can also use a dynamic `v-bind` object based on the value of `is`.

**Comment by NE-SmallTown** [comment]
>  there's a large chance we would set it to true
Seems not correct, only the component which related to native tag(almost are about form, input/button/video/audio/select/form/table..) will need this feature, but these components are created by 3rd libraries(iview, element-ui.... or your internal teams). So, you just need set it to `true` when you develop these components.

But, the **more scenarios is** that the components we are developing is not about them in our applications/apps, so if the default behavior is `true`, that's a little bad because probably I need to set it to `false` for 90% components when use `<component>`.

> BTW. You can also use a dynamic v-bind object based on the value of is.

That's a workaround but seems not correct, it need us to add some judgement like `v-bind="is === Foo ? { prop: '...' } : {}"`, why I need to do this? It just use a problem to solve another problem.

**Comment by Justineo** [comment]
> Seems not correct, only the component which related to native tag(almost are about form like input/button/video/audio/select/form/table..) will need this feature

Actually there are a lot of HTML global attributes which need this feature which may need `inheritAttrs` to be `true`. For example, when you are making an accessible web app, the `aria-*` global attributes are essential and needs to be handcrafted differently in each scenario. It's impossible to encapsulate all A11Y annotation inside component libraries. 

> That's a workaround but seems not correct, it needs us to add some judgement like v-bind="is === Foo ? { prop: '...' } : {}", why I need to do this? It just use a problem to solve another problem.

You can pass a component’s options object into `is` and filter the `v-bind` object by checking if it has specific prop declared for the rendered component. See this sandbox: https://codesandbox.io/s/42zoo8m4o7.

**Comment by NE-SmallTown** [comment]
Ok, fine, just trade off, though seems the codesandbox is more fussy than just use `inheritAttrs` IMO
