### ISSUE TITLE
 Mixin's data isn't available during render

### ISSUE THREAD

**Issue by jason-chang** [vuejs/vue#8768]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/JasonChang/6kt70b5L/34/](https://jsfiddle.net/JasonChang/6kt70b5L/34/)

### Steps to reproduce
See the JSFiddle https://jsfiddle.net/JasonChang/6kt70b5L/34/

### What is expected?
    Show "instanceVarValue" and "$_mixinVarValue"

### What is actually happening?
Got:

    Show "instanceVarValue" and ""

And got console error like bllow
```
vue.js:597 [Vue warn]: Property or method "$_mixinVar" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <SomeView>
       <Root>
```

**Comment by ktsn** [comment]
This is expected. See https://vuejs.org/v2/api/#data

> Properties that start with _ or $ will not be proxied on the Vue instance because they may conflict with Vue’s internal properties and API methods. You will have to access them as vm.$data._property.

**Comment by jason-chang** [comment]
I found that if i remove the "$_" it will be available 

https://jsfiddle.net/JasonChang/6kt70b5L/37/

And i found these lines in the guile 
https://vuejs.org/v2/guide/instance.html#Data-and-Methods

```
In addition to data properties, Vue instances expose a number of useful instance properties and methods. These are prefixed with $ to differentiate them from user-defined properties. For example:
```

But i think isn't this rule conflict to the 《style-guide》？

https://vuejs.org/v2/style-guide/#Private-property-names-essential

**Comment by ktsn** [comment]
Why does that conflict with style guide? You still able to use `$_` prefixed reactive property via `this.$data`

**Comment by kindlyfire** [comment]
Spent a few hours trying to figure out why my mixin wasn't working. This is apparently the cause.

Basically, I have a `loader` mixin with a `$_loader_loading` in the data. I wanted to use that data inside the component using the mixin, but it wouldn't work.

```js
// Mixin code
export default {
    data() {
        return {
            $_loader_loading: true
        }
    },

    created() {
        // $_loader_loading never updates on component using mixin

        this.$_loader_loading = false
    }
}
```

So, what do I need to make this work ? Using `$data.$_loader_loading` everywhere is kinda annoying. Even more so because the style guide tells us to start mixin data and methods with `$_`, not telling us the problems with doing so.
