### ISSUE TITLE
Is it possible don't re-render dom when SSR at client side?

### ISSUE THREAD

**Issue by falstack** [vuejs/vue#8769]
### What problem does this feature solve?
best performance

### What does the proposed API look like?
nothing need change

**Comment by posva** [comment]
Hey, this is the 4th time you do this, please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions.

I guess you could not include Vue or something similar

**Comment by falstack** [comment]
4th time...? sorry about it 🤣
