### ISSUE TITLE
doument not  mentioned MUST define component NAME for .vue when it's self contained?

### ISSUE THREAD

**Issue by ZenLiuCN** [vuejs/vue#8770]
https://github.com/vuejs/vue-class-component/issues/267#issue-357654876

as this thing i found~~

**Comment by Justineo** [comment]
https://vuejs.org/v2/guide/components-edge-cases.html#Recursive-Components

Maybe a link to this piece in component name section would be helpful. You can open an issue for this in the documentation repo.
