### ISSUE TITLE
添加指令缓存自定义数据到元素dataset中

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue#8772]
### What problem does this feature solve?
在jquery年代，针对ul中的li要绑定相同的事件时，我们绑定的事件会放到ul上，之后增加li也无需再增加绑定事件到li上，大大提升了应用程序性能。而目前vue，angular，react采用的方式都是要求绑定到li上。目前我能采取的方式只能自定义一个my-index属性到li上，在ul上绑定事件，然后通过参数中的event.target获取到该元素，然后获取my-index属性的值，接着通过该my-index索引号去被遍历的数组中取得相关数据，感觉很绕，希望能增加一个v-data指令可以绑定自定义数据到li元素的dataSet属性上，然后可以通过冒泡的事件来取得绑定的数据，该指令绝对能独立创新领先于react和angular俩框架。

### What does the proposed API look like?
增加一个v-data指令可以绑定自定义数据到li元素的dataSet属性上，然后可以通过冒泡的事件来取得绑定的数据

**Comment by yangdan8** [comment]
希望尤大能看到给点意见 @yyx990803

**Comment by sodatea** [comment]
https://forum.vuejs.org/t/is-event-delegation-necessary/3701/4
https://blog.cloudboost.io/why-react-discourage-event-delegation-2b5fe3f52bea

**Comment by yangdan8** [comment]
这么回答的意思就是无解了，哎，谢谢啦
