### ISSUE TITLE
change data by javascript or by devtool not connected to data binding

### ISSUE THREAD

**Issue by medhamza911** [vuejs/vue#8773]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/689815/](https://jsfiddle.net/50wL7mdz/689815/)

### Steps to reproduce
the code explain it

### What is expected?
message variable change

### What is actually happening?
nothing

**Comment by sodatea** [comment]
Template interpolation in Vue is not two-way binding.
