### ISSUE TITLE
Strange behaviour concerning script-tag

### ISSUE THREAD

**Issue by untier** [vuejs/vue#8774]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/692983/](https://jsfiddle.net/50wL7mdz/692983/)

### Steps to reproduce
Include a script-tag with type "application/javascript" inside a vue-activated tag.

### What is expected?
Probably an error like:

Error compiling template:
...
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

### What is actually happening?
No error, but script tag is executed twice (see console in example)

---
I'm starting to convert a big web-application to more modern technologies like vue.js. We are searching for ways to do this step by step. Our jsp-code contains many script tags, which cannot be replaced at once, so I write vue-components (they contain no script tags) and try to use them in our legacy code. Unfortunately I ran into the "Templates should only be responsible for mapping the state to the UI"-warning, which I could avoid by setting the script-type to "application/javascript". This produced errors, as the embedded js is run twice. Feel free to give me a tip to avoid this problems.

**EDIT**
If there is no type given, the warning is shown, but script is only executed once.

**Comment by posva** [comment]
As the error says, you cannot place a script tag inside of a Vue template. You probably want to update your app by parts.

---

You can search or ask in the [forum](http://forum.vuejs.org/) and the [Discord server](https://vue-land.js.org/) for more help
