### ISSUE TITLE
different template in different enviorment 

### ISSUE THREAD

**Issue by vrwebdesign** [vuejs/vue#8777]
### What problem does this feature solve?
different template in different enviorment 

### What does the proposed API look like?
Hello I want to build a web app and mobile app for android and ios
I want to re use component in all platform
so I need different template in different environment
like this

```
 <template if="process.env.type===web">
    <div class="hello">
        <h1>from Web</h1>
        <h3>{{ msg }}</h3>
    </div>
</template>
```
```
 <template if="process.env.type===app">
    <div class="hello">
        <h1>from App</h1>
        <h3>{{ msg }}</h3>
    </div>
</template>
```
is it possible?
or different way to implement it

**Comment by posva** [comment]
See #7264

You can also implement it by having too components, putting the logic into a mixins and importing different components based on the environment variable

- MyComponent (folder)
  - MyComponentMobile.vue
  - MyComponentWeb.vue
  - index.js (takes the right component adds common logic and export it)

**Comment by vrwebdesign** [comment]
can you share some code for me?
I try to use this before but I can't do it.
