### ISSUE TITLE
Array in data remains the same when one component disappears and another component (the same type) shows up 

### ISSUE THREAD

**Issue by Sharzon** [vuejs/vue#8778]
### Version
2.5.17

### Reproduction link
[https://codepen.io/Sharzon/pen/xapjOY?editors=1011](https://codepen.io/Sharzon/pen/xapjOY?editors=1011)

### Steps to reproduce
1. Click some elements of the list
2. Click "Show second" button
3. Click some elements of the upper list
4. Click "Show first" button

### What is expected?
Upper list should contain [1,2,3] elements for clicking first button, [4,5,6] elements for the second button and nothing in the bottom list.

### What is actually happening?
Bottom list remains the same when we click another button.

---
I see Vue doesn't call mounted() when one component disappears and second shows up

**Comment by posva** [comment]
This is expected, Vue will reuse components. In your case you will have to use the attribute `key` on at least one of them to force Vue not to reuse them 🙂
