### ISSUE TITLE
For recursive components, make sure to provide the "name" option. But name is provided for all components.

### ISSUE THREAD

**Issue by vedmant** [vuejs/vue#8783]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/gjx1wvhk/ ](https://jsfiddle.net/gjx1wvhk/ )

### Steps to reproduce
Just run the code

### What is expected?
No error

### What is actually happening?
Shows error in console

---
Hi, I use *.vue components, and I have following error: "Unknown custom element: <comments-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option." for my component. However I provided names for all components.

Here is sample fiddle to reproduce this error: 
https://jsfiddle.net/gjx1wvhk/  (open developer console to see error)

There is small difference between fiddle and my code, I use *.vue components, import them relatively and add as components fields to my components:

```
import CommentsList from './CommentsList.vue'

export default {
  name: 'comments',

  components: {
    CommentsList,
  },
...
}

import CommentsList from './CommentsList.vue'

export default {
  name: 'comment',

  components: {
    CommentsList,
  },
...
}

import Comment from './Comment.vue'

export default {
  name: 'comments-list',

  components: {
    Comment,
  },
...
}
```

**Comment by posva** [comment]
This is because both of your components depend on each other. I'm not sure what was the right approach but I'm pretty sure I saw it documented. Maybe it's using a dynamic import in one of the components. cc @chrisvfritz

**Comment by KaelWD** [comment]
> did you register the component correctly?

The first argument to `Vue.component` must be a string: https://vuejs.org/v2/api/#Vue-component

**Comment by posva** [comment]
There we go: https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components

**Comment by vedmant** [comment]
@posva Thanks a lot!

@KaelWD Re: The first argument to Vue.component must be a string
That was just to make an example, I don't use Vue.component, I use modules with Webpack.

**Comment by KaelWD** [comment]
Yeah I kinda glossed over that bit lol, still an error in the repro though. [CodeSandbox](https://codesandbox.io/s/vue) is usually better for multi-component examples like that, especially when it's something caused by webpack.

**Comment by xianzhe18** [comment]
https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components
I had the same issue, but this saved me.
