### ISSUE TITLE
v-bind:class doesn't support class name with hyphen

### ISSUE THREAD

**Issue by shi-yan** [vuejs/vue#8786]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/706254/](https://jsfiddle.net/50wL7mdz/706254/)

### Steps to reproduce
create a v-bind:class, but the class' name contain a hyphen, for example  v-bind:class="{ blah-active: isActive }"

vue will fail to accept blah-active as a valid class name. but if I change it to blahactive, (remove the hyphen), it works.

### What is expected?
hyphen should be acceptable as part of the class name, or this needs to be documented.

since html supports hyphen in class name, vue should support it too.

### What is actually happening?
vue doesn't support class names with hyphen

---
no

**Comment by sqal** [comment]
That's how Javascript objects works. Object's key cannot contain hyphen unless it's inside quotes. `{ blah-active: true }` paste it in the Chrome's console and you will get SyntaxError.
