### ISSUE TITLE
v-if does not work on <template>

### ISSUE THREAD

**Issue by mhldtna** [vuejs/vue#8787]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/706545/](https://jsfiddle.net/50wL7mdz/706545/)

### Steps to reproduce
Define an element with "&lt;template v-if="false"\&gt;.  Or set the v-if to reference a data or computed property that returns false.  The template contents are rendered even though they should be skipped.

Workaround: put the v-if on a &lt;div&gt; within the &lt;template&gt;.

### What is expected?
Per https://vuejs.org/v2/guide/conditional.html, the template contents should not be rendered.

### What is actually happening?
The template contents are rendered.

---
I found this problem with a top-level &lt;template&gt; in a Vue component (.vue file).  But the jsfiddle shows that it happens for any &lt;template&gt;.

**Comment by tony19** [comment]
Your reproduction link is malformed; and the `template` needs to be inside the mount point.

**Comment by mhldtna** [comment]
Oh, sorry.  I've fixed that. Problem still exists.

**Comment by Justineo** [comment]
You’ve been putting the `<template>` outside the root element of your Vue app.

**Comment by tony19** [comment]
@mhldtna It doesn't look like your link is updated :)

In any case, the `v-if` still works with `<template>`:

```html
<div id="app">
  <button @click="check = !check">Toggle</button>
  <template v-if="check">
    <p>{{ message }}</p>
  </template>
</div>
```

https://jsfiddle.net/50wL7mdz/707450/
