### ISSUE TITLE
cannot pass a wrapped computed  to v-model

### ISSUE THREAD

**Issue by shishiv30** [vuejs/vue#8792]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/4pukLmnc/124/](http://jsfiddle.net/4pukLmnc/124/)

### Steps to reproduce
I want reorder an array which is use to generate a form called "formConfig"
but since I use computed as the params of v-model  it's not work and the sub-components are not original input
is there any solution?

http://jsfiddle.net/4pukLmnc/124/

### What is expected?
the  comupted  can be pass into v-model

### What is actually happening?
the computed cannot be passed into v-model

---
If it's by design. Is there any way to made the code work as my expected?
Tip: I have to use get set

**Comment by leeezhou** [comment]
计算属性可能是由多个属性拼接而成。例如：一个人的名字由姓和名组成，如果绑定到v-model，当输入框值发生变化，怎么把新的值拆成姓和名。

Computed properties may be made up of multiple attributes. For example, a person's name consists of  first name and last name, if bound to a v-model, how to split the new value into first name and last name when the input value changes.

**Comment by javoski** [comment]
The `data` option was initialized before `computed` option, so you couldn't access computed properties inside `data` option.

**Comment by shishiv30** [comment]
@jsvoski, I have try to made the formConfig to be a computed but still not working

**Comment by shishiv30** [comment]
anyway I have fixed the issue.  please see the code
http://jsfiddle.net/4pukLmnc/172/

so I just change the way to use origin setter getter, not computer. then the this will not missing
