### ISSUE TITLE
Problem with passing data to vue component using .sync

### ISSUE THREAD

**Issue by mr-jingles** [vuejs/vue#8794]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/eywraw8t/364640/](https://jsfiddle.net/eywraw8t/364640/)

### Steps to reproduce
Pass json data as html attribute to a component using .sync

### What is expected?
Data should be available as prop and can be used.

### What is actually happening?
JSON gets distorted and console throws error.

---
I am trying to pass data from a laravel blade view to the vue component. I am using sync to make the prop reactive. However this does not work. Passing the json as static data does work.

**Comment by leeezhou** [comment]
> Using v-bind.sync with a literal object, such as in v-bind.sync=”{ title: doc.title }”, will not work, because there are too many edge cases to consider in parsing a complex expression like this.

**Comment by mr-jingles** [comment]
A simple data object like v-bind.sync="{ mail: 'test@gmai.com '}" would also be falling into that criteria I guess? If that's the case - to get my prop reactive - best practice would be to reassign my data object within a created method to a reactive data object? Like: https://jsfiddle.net/0qmh4rvg/ ?
Thanks!

**Comment by maxirozay** [comment]
Just pass an object from your `data`, it is reactive.
```
data () {
  return {
    object: 'hi'
  }
}
```
Then pass it with `v-bind="object"`.

**Comment by mr-jingles** [comment]
Makes sense - however I am passing the data from a laravel blade template. The vue js logic is compiled in js files which are loaded at runtime. Passing the data directly into data like:
`
data () {
  return {
    object: <?php json_encode($dataobject) ?>
  }
}
`
won't work in my case. I need to go the longer route via passing the data as attribute in the html component and it should be reactive. 
Another option would be to assign my data within the blade template to the window object and then reassign it to data like:

blade template:
`
<script>
window.data =  <?php json_encode($dataobject) ?>
</script>
`

In my js file:
`
data () {
  return {
    object: window.data
  }
}
`
However this does also not feel like the most clean approach.

**Comment by posva** [comment]
You need to put it in data

**Comment by javoski** [comment]
@mr-jingles In your case, I'll suggest using regular events instead of `.sync`(in another way `update:` event)

**Comment by mr-jingles** [comment]
@javoski - thanks for you input. I will try that.. Till now I thought .sync is just syntactic sugar for the update event.

**Comment by Justineo** [comment]
> Till now I thought .sync is just syntactic sugar for the update event.

Exactly. So you cannot do something like `@update:mail="{ ... } = $event"`.

**Comment by mr-jingles** [comment]
Hmm ok - seems that I have no other choice than to choose from one of my suggested approaches.
Either reassign the data object within a created method or assign it globally to the window object within the blade template and then reassign it in the vue component. 
@all Thanks for your input!
