### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by cnyb-kwange** [vuejs/vue#8795]
### Version
2.5.17

### Reproduction link
[https://codepen.io/pen/](https://codepen.io/pen/)

### Steps to reproduce
why using vue-cli 3 created project occur "Uncaught SyntaxError: Unexpected identifier"?

1) create a vue project with vue-cli 3

2) npm run serve

3) open chrome devtools , can see webpack://src/main.js?2ee2 (router.js?6a39 , store.js?23a6) file first line "import Vue from 'vue';" throw out error -> Uncaught SyntaxError: Unexpected identifier.

but project is running well

package.json : 

"dependencies": {

    "vue": "^2.5.17",

    "vue-router": "^3.0.1",

    "vuex": "^3.0.1"

  },

  "devDependencies": {

    "@vue/cli-plugin-babel": "^3.0.0",

    "@vue/cli-plugin-eslint": "^3.0.0",

    "@vue/cli-service": "^3.0.0",

    "node-sass": "^4.9.0",

    "sass-loader": "^7.0.1",

    "vue-template-compiler": "^2.5.17"

  }

### What is expected?
fix this error

### What is actually happening?
Uncaught SyntaxError: Unexpected identifier

**Comment by maxirozay** [comment]
It looks like it doesn't know `import`. Make sure you're up to date with your tools (node, npm) and if you only create a project with vue-cli and run it it should work fine. If there's a problem with vue-cli you should go to https://github.com/vuejs/vue-cli so they can fix it.
(your CodePen is empty)

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
