### ISSUE TITLE
Why $listeners include input listener, but $attrs doesn't include value prop?

### ISSUE THREAD

**Issue by fjc0k** [vuejs/vue#8797]
### Version
2.5.17

### Reproduction link
[https://codepen.io/fjc0k/pen/KxBvbY?editors=1111](https://codepen.io/fjc0k/pen/KxBvbY?editors=1111)

### Steps to reproduce
1. open codepen url
2. open console

### What is expected?
$attrs:  `{ value: '' }`

$listeners: `{ input: () => {} }`

### What is actually happening?
$attrs:  `{}`

$listeners: `{ input: () => {} }`

**Comment by posva** [comment]
Duplicate of #8430
