### ISSUE TITLE
v-text not available through $slots

### ISSUE THREAD

**Issue by ChrisRM** [vuejs/vue#8800]
### Version
2.5.17

### Reproduction link
[http://not-able-to-reproduce.xo](http://not-able-to-reproduce.xo)

### Steps to reproduce
Hi, according to the docs, `<span v-text="msg"></span>` should be the same as `<span>{{msg}}</span>`, and by DOM result, it is. However, when trying to build a component like this:

```ts
get childMarkup(): VNode | null {
	return this.$slots.default ? <span>{this.$slots.default}</span> : null;
}
```
I'm running into a problem where `<span>{{msg}}</span>` works as it should, because it's added to the $slots collection, but using `<span v-text="msg"></span>` creates a problem, as it's not added to the $slots collection. I'm not sure whether this is intended or not, but what's the best way of solving this? 

I'm guessing I could just check for the innerText/Html of the element, but I'm hoping there's a better way.

### What is expected?
The same behaviour as described in the documentation.

### What is actually happening?
Not what I expected...

**Comment by posva** [comment]
the result is the same but the behaviour is slightly different as one is indeed setting an element property to modify the text. Check this: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%3Cspan%3E%7B%7B%20msg%20%7D%7D%3C%2Fspan%3E%0A%20%20%3Cspan%20v-text%3D%22msg%22%3E%3C%2Fspan%3E%0A%3C%2Fdiv%3E
