### ISSUE TITLE
vue 2.5.17下渲染svg maker元素的refx和refy属性无效，造成图像错位

### ISSUE THREAD

**Issue by BradHan** [vuejs/vue#8803]
### Version
2.5.17

### Reproduction link
[https://codepen.io/bradhan/pen/pOOOYq](https://codepen.io/bradhan/pen/pOOOYq)

### Steps to reproduce
v1.0.28 is ok: https://codepen.io/bradhan/pen/Wgggqg

v2.5.17 has bug: https://codepen.io/bradhan/pen/pOOOYq

### What is expected?
用组件方式渲染带marker元素的svg，由于refx和refy属性无效，造成图像错位

### What is actually happening?
用组件方式渲染带marker元素的svg，图像不错位

**Comment by KaelWD** [comment]
SVG is case-sensitive, you need to use `refX` and `refY`

**Comment by Justineo** [comment]
As @KaelWD said, use `refX` and `refY` instead should fix your problem.

**Comment by BradHan** [comment]
it works,thanks！
