### ISSUE TITLE
vue router lost meta config

### ISSUE THREAD

**Issue by lichenhao** [vuejs/vue#8806]
### Version
2.5.17

### Reproduction link
[https://jsbin.com/sazujuxoba/edit?html,output](https://jsbin.com/sazujuxoba/edit?html,output)

### Steps to reproduce
install vue@2.5.17
install vue-router@3.0.1
define a router with meta info
define the beforeEach callback and the to.meta is an empty object.

### What is expected?
to.meta should be the current definition object 

### What is actually happening?
it's an empty object here. 

---
and the beforeRouteEnter hook not trigger.

**Comment by javoski** [comment]
There's a typo in your reproduction link, it should be `routes`, not `routers`.
