### ISSUE TITLE
Disable observing for components hidden by v-show

### ISSUE THREAD

**Issue by Razenpok** [vuejs/vue#8808]
### What problem does this feature solve?
I have an app with several non-trivial component blocks, each one being constantly updating a lot of its inner components (my app is very dynamic). At any moment of the time, only one such block must be visible. I don't think using `v-if` or `is` is a good idea in my case, as recreating such blocks is rather expensive. I decided to use `v-show` instead, but I've noticed that inner components are still being updated on every block (even hidden). Even worse, some of these updates are very computational heavy, so my app is basically wasting CPU clocks on updating hidden elements.

Simplified example:

```js
<div id="test" v-show="visible"><p>Number {{ number }}<p></div>
```

```js
var vm = new Vue({
    el: '#test',
    data: {
        number: 0,
        visible: true
    }
});

setInterval(function() {
    vm.number  ;
}, 10);
```

Here `<p>` will still be updated even if `visible` is `false`.

### What does the proposed API look like?
Either make this behavior default or add some attribute to control it (something like `v-freeze`).

**Comment by posva** [comment]
Use `keep-alive` + `v-if`
