### ISSUE TITLE
vue-server-renderer | Webpack 4 deprecation warning for plugins

### ISSUE THREAD

**Issue by AlexDubok** [vuejs/vue#8810]
### What problem does this feature solve?
In webpack 4 there is a deprecation warning about the Tapable.plugin being deprecated.

### What does the proposed API look like?
Change compiler.plugin to compiler.hooks.[hookname] to support new tappable syntax.

The question is what is the preferred way to support new syntax while leaving Webpack 2-3 compatibility?

**Comment by jonaskuske** [comment]
Already fixed in [vuejs/vue#7839](https://github.com/vuejs/vue/pull/7839), will be merged into master as part of Vue v2.6 :)

**Comment by AlexDubok** [comment]
OK, thanks :)
