### ISSUE TITLE
Can Vue Support Clone Method For Each Instance?

### ISSUE THREAD

**Issue by LaiHuanMin** [vuejs/vue#8812]
### What problem does this feature solve?
Hello! I 'm develop vue project which using cdn link, not build way. I wanna know is there can clone all of vm instance attribute such as $data, $store,$router into a new vm instance, and when I change vm instance $data or invoke that vm instance method or push that vm content $router a new page, will never change the origin one.     
Because I wanna clone new vm instance which has current state,  and without dom render question, it's just about that vm instance data will be setter by method or vuex dispatch.      
Maybe clone method can without dom $refs and mounted method, only care about the data. 

### What does the proposed API look like?
var vm = new Vue({...});   
// after running a moment   
// i dont' wanna change data at crt vm instance, because change data will effect render question, so i make a clone method
var newvm = vm.clone({withoutDom: true});   
newvm.$data.tabledata = [];  
newvm.$data.invokeRequestData();

**Comment by posva** [comment]
Except for `$route` and `$store` which are read from from the route instance and store instance respectively, you can copy the data from one instance and put it into a new Vue instance.
What you are trying to do is not clear...
I will ask you to go to the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/) to ask questions first if you need to and come back with a more elaborated feature request regarding the use-case. Right now it's not clear at all

**Comment by posva** [comment]
It's not a stupid issue. It's missing information for a feature request, that's all 🙂
