### ISSUE TITLE
click event will be trigged twice for some situation

### ISSUE THREAD

**Issue by shirleyMHao** [vuejs/vue#8813]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/733707/](https://jsfiddle.net/50wL7mdz/733707/)

### Steps to reproduce
Click the text "Hello"

### What is expected?
the click event "handleClick" has been triggered twice.
you can see the console log or the message becomes "Hello add add"

### What is actually happening?
click event only run once.

---
FYI: If add the "for" attribute for the label, click event will only be triggered once.

**Comment by sodatea** [comment]
This is just how native DOM works.
http://jsfiddle.net/sodatea/89crzLto/4/
