### ISSUE TITLE
The computed property "SelectMany" is already defined in data.

### ISSUE THREAD

**Issue by AlexFree** [vuejs/vue#8818]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/740132/](https://jsfiddle.net/50wL7mdz/740132/)

### Steps to reproduce
i defined the following before instance new Vue:

Object.prototype.SelectMany = function () { ... }

and get:

[Vue warn]: The computed property "SelectMany" is already defined in data.

(found in <Root>)
warn	@	vue.js:597
initComputed	@	vue.js:3457
...

### What is expected?
no warning

### What is actually happening?
warning in the console

**Comment by posva** [comment]
Defining things in the prototype of `Object` is a very dangerous thing as pretty much everything is an object in js, which means the Vue instance has it and the object passed to data have it too. That's where the collision comes from.

Don't add things to the prototype of Object, really, it should be avoided at all cost in any js project
