### ISSUE TITLE
v-for iterating over v-else

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue#8826]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/hirokiosame/7mfcktv4/](https://jsfiddle.net/hirokiosame/7mfcktv4/)

### Steps to reproduce
Add a `v-for` and `v-if` to an element with a v-else sibling. If the v-if condition evaluates to be falsy, the iteration happens over the `v-else` element.

### What is expected?
For the v-for to not iterate over the v-else

### What is actually happening?
The v-for is iterating over the v-else

**Comment by KaelWD** [comment]
https://vuejs.org/v2/style-guide/#Avoid-v-if-with-v-for-essential

**Comment by hirokiosame** [comment]
Thank you -- I've read that from the [linter](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-use-v-if-with-v-for.md) but I'm not having trouble producing the result I need; I understand the v-for is happening first and the v-if/v-else happens per iteration.

I wanted to share a scenario where the v-for/v-if combination yielded a particularly unexpected behavior where the v-for would be applied to the v-else element.

**Comment by posva** [comment]
This is working as expected and is consistent with v-if being applied after v-for

**Comment by hirokiosame** [comment]
To be clear, the bug I'm reporting isn't that v-for is happening before v-if. It's that the v-for is being applied to code outside of the iteration.

What's happening:
```
<template v-for="i in 10">
	<div v-if="useDiv">
		Div: {{ i }}
	</div>
	<span v-else>
		Span
	</span>
</template>
```

Expected behavior:
```
<template v-for="i in 10">
	<div v-if="useDiv">
		Div: {{ i }}
	</div>
</template>
<span v-else>
	Span
</span>
```

**Comment by KaelWD** [comment]
The style guide explains why this should be avoided:
![image](https://user-images.githubusercontent.com/16421948/45924930-d2cffb00-bf4e-11e8-85da-a689b30b36d7.png)

The actual render function from your example:
```js
function anonymous(
) {
  with(this){return _c('div',[_l((10),function(i){return [(useDiv)?_c('div',[_v("Div: "+_s(i))]):_c('span',[_v("Span")])]})],2)}
}
```

**Comment by Hoishin** [comment]
It looks to me that, the reason the behaviour in original post is expected thanks to this "`v-for` then `v-if`" behaviour.

If the order was "`v-if` then `v-for`", it checks `useDiv` and
- if `true`, render 10 `div`
- if `false`, render the `span`

If the order was "`v-for` then `v-if`", it starts iterating the `div`. It says `v-if` so it checks `useDiv`, and
- if `true`, render `div`
- if `false`, render `span`

The pair of `v-if`/`v-else` happens 10 times. If it was `v-if` x10 then `v-else` x1, even more confusing behaviour would be introduced, that is `v-else` referencing last one of iterated `v-if` outside of iteration. (Imagine if it was `v-if="i % 2 === 0"` or something)

But yeah writing these above gives me headache. Someone who wrote the style guide must have experienced the same 😓

**Comment by KaelWD** [comment]
And if v-if was first then you wouldn't be able to use the current item from the v-for in it.

**Comment by hirokiosame** [comment]
I'm not confused or disputing that `v-if` should happen before `v-for`; `v-for` before `v-if` is fine.

> If it was v-if x10 then v-else x1, even more confusing behaviour would be introduced, that is v-else referencing last one of iterated v-if outside of iteration. (Imagine if it was v-if="i % 2 === 0" or something)

I actually think it would be less confusing since the `v-for` isn't syntactically referencing the element `v-else` is on. But doing this will probably require syntax like this to be supported, which I admit is confusing:
```
<template>
	<div v-if="false">
		div
	</div>
</template>
<span v-else>
	asdf
</span>
```

Perhaps all this confusion will be resolved if mutual exclusivity of `v-if` and `v-for` can be enforced by Vue.
