### ISSUE TITLE
CSS children selector don't work on elements in slot. 

### ISSUE THREAD

**Issue by vinciarts** [vuejs/vue#8827]
If there's a component A:

```
<template lang=""pug">
.root
  slot 
</template>

<style lamg="stylus" scoped>
.root > *
  position absolute
</style>
```
If I inserted some element under the instance of A, I suppose these elementshas such style: `position: absolute`, but it doesn't work.

**Comment by Justineo** [comment]
See [Deep Selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors).
