### ISSUE TITLE
Very async rendering with Vue

### ISSUE THREAD

**Issue by frederikhors** [vuejs/vue#8828]
### What problem does this feature solve?
Is there in the Vue's world like this in React's world? https://gist.github.com/acdlite/f31becd03e2f5feb9b4b22267a58bc1f

### What does the proposed API look like?
```js
const root = ReactDOM.unstable_createRoot(containerEl);
const work = root.prerender(<App />);
// ... other async work ...
work.commit();
```

![image](https://user-images.githubusercontent.com/6764957/38159817-c83f7b44-347e-11e8-9a65-92b4aa375e44.gif)

**Comment by posva** [comment]
Unfortunately not. As other features this was added in a full rewrite and would require huge changes in Vue that could even lead to breaking  changes. It's something that will be considered for next major version thought
