### ISSUE TITLE
Duplicate keys detected not warned

### ISSUE THREAD

**Issue by dejour** [vuejs/vue#8832]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/zwm20ozlym](https://codesandbox.io/s/zwm20ozlym)

### Steps to reproduce
check reproduction url

### What is expected?
Duplicate keys detected to be warned

### What is actually happening?
Duplicate keys detected not warned

---
when addVnodes is called, vnodes with same key are not warned

**Comment by DanielSanRocha** [comment]
Hi, may I try to make this improvement my first contribution? I have already had some situations with duplicated keys in which a warning would have helped.

**Comment by posva** [comment]
of course, nobody is working on this 🙂

**Comment by DanielSanRocha** [comment]
Added a pull request (#8881) with a new test case and a solution.
