### ISSUE TITLE
Vue's instance _events object with ids

### ISSUE THREAD

**Issue by p1pchenk0** [vuejs/vue#8833]
### What problem does this feature solve?
Currently `_events` object contains event names as keys and arrays of listeners as values.

Let's say we have `Component A`, `Component B`, `Component C`. Both `Component A` and `Component B` listen to `'some-event'` event, which is emitted by `Component C`. Also `Component A` listens to `'another-event'` event.

It would be good to pass also unique IDs, so then user can call smth like `this.$eventBus.$offAll()` inside `beforeDestroy()` hook of `Component A` and it will unsubscribe `Component A` from all events it listens to BUT saves `Component B` subscriptions.

### What does the proposed API look like?
`this.$eventBus.$offAll()` so we can save `this.$eventBus.$off()` functionality as it is now

**Comment by p1pchenk0** [comment]
I would happily help with implementation

**Comment by posva** [comment]
Even though Vue can be used as an Event Bus, it is not one. If you require a more flexible implementation of a Bus you can use many other packages out there or even create your own  🙂
