### ISSUE TITLE
"Multiple root nodes returned from render function" error with functional component

### ISSUE THREAD

**Issue by lebesnec** [vuejs/vue#8837]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/9mnqs3g2/](https://jsfiddle.net/9mnqs3g2/)

### Steps to reproduce
open the reproduction link and look at the JS console.

### What is expected?
You can have multiple root elements in functional components.

### What is actually happening?
"Multiple root nodes returned from render function. Render function should return a single root node." error in console, nothing render.

---
According to https://github.com/vuejs/vue/issues/7088#issuecomment-421510160 functional component are the way to go if you need more than one root element.

**Comment by sqal** [comment]
> functional component are the way to go if you need more than one root element.

Yes, but still, you can't have multiple root elements in a **regular**  component, and that is what you are doing in the provided example (`template: '<test/>'`). So in order to fix it, just wrap the template of your app in a single div `<div><test/></div>`  and the error will disappear.

**Comment by lebesnec** [comment]
I'm not sure I understand, there is only one root element `<test/>` in my template?

**Comment by posva** [comment]
test  becomes two elements 😄

**Comment by sqal** [comment]
@Skriptach Currently no. I don't know if the team plans to to introduce Fragments in Vue 2.x, but this feature will certainly land in 3.0

> Fragments & Portals: despite the size reduction, 3.0 comes with built-in support for Fragments (component returning multiple root nodes) and Portals (rendering a sub-tree in another part of the DOM, instead of inside the component).

Source: https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf

**Comment by MayurSorathiya** [comment]
.
