### ISSUE TITLE
Chrome DOM element not updating; Safari is fine

### ISSUE THREAD

**Issue by dochoss** [vuejs/vue#8838]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Lwy1sh9c/](https://jsfiddle.net/Lwy1sh9c/)

### Steps to reproduce
Repro shows fully functional version.  Not sure how to show a repro.  Application is not updating properly in Chrome.

### What is expected?
Reactive properties updating as expected

### What is actually happening?
"From" and "To" fields are not updating in Chrome browser.  Updates properly in Safari

---
Setting "selectedMessage" on Vuex store with a mutation.  It is a simple mutation and other properties update, but reactivity doesn't work properly for "From" and "To" fields in the DOM, but only on Chrome.  When loaded in Safari, the fields update as expected.

**Comment by posva** [comment]
It works correctly on Chrome for me 😅 
I would advise you to go to the forum or discord server with more details, there may be something in your full code causing the problem
