### ISSUE TITLE
comes error when using "in" as key in data props

### ISSUE THREAD

**Issue by bi-kai** [vuejs/vue#8840]
### Version
2.5.17

### Reproduction link
[http://no online example](http://no online example)

### Steps to reproduce
```html
   <div id="app">
        <input v-model="in">
        {{ in }}
    </div>
```

```javascript
new Vue({
    el: '#app',
    data: {
        visible: false,
        in: "cc"
    },
})
```

### What is expected?
"in" and "of" acts the same.

### What is actually happening?
if i use "in" as key in data props, comes error:
```
[Vue warn]: Error compiling template:

<div id="app">
        <input v-model="in">
        {{ in }}
    </div>

- invalid expression: Unexpected token in in

    in

  Raw expression: v-model="in"

- invalid expression: Unexpected token in in

    "\n        " _s(in) "\n    "

  Raw expression: {{ in }}



(found in <Root>)
```

but if i use "of" instead of "in", it's ok, this makes me confused, both "in" and "of" are key work in ES5/6, what makes this different?

**Comment by KaelWD** [comment]
`in` is a reserved keyword in JS, `of` isn't.

**Comment by Justineo** [comment]
As @KaelWD said. See [ECMAScript® 2018 Language Specification](https://www.ecma-international.org/ecma-262/9.0/index.html#prod-Keyword).

**Comment by bi-kai** [comment]
ok, i see.
I think `of` is also s key in es cause `for of`.
Thx, both of you.
