### ISSUE TITLE
Deep selector is broken in production mode

### ISSUE THREAD

**Issue by NE-SmallTown** [vuejs/vue#8841]
### Version
2.5.17

### Reproduction link
Sorry for too busy and this is a build issue, if needed, I will provide a repo this weekend **but probably doesn't need**

### Steps to reproduce
Although this maybe a `less.js` bug, but seems only vue-loader(exactly `@vue/component-compiler-utils` and maybe angular use but I'm not familiar with it) relays on this to do it's own work, and since vue-loader repo seems not active, so I will report here to let more users could find this(There were already many issues about deep selector so I think this won't be offensive)

Vue-loader depends on `@vue/component-compiler-utils` which could [process deep selector](https://github.com/vuejs/component-compiler-utils/blob/master/lib/stylePlugins/scoped.ts#L35-L44), but this needs `less-loader`(exactly `less.js`) to process the css correctly. But in production mode, the result css after processed by `less` is **wrong**, because:

1. The `/deep/` syntax will be [considered a combinator](https://github.com/less/less.js/blob/master/lib/less/parser/parser.js#L1242-L1253)

2. And then when [process a combinator](https://github.com/less/less.js/blob/master/lib/less/tree/combinator.js#L19-L22), when the `compress` flag(**in production it's `true` by default but in development is `false`**) is `true`, the result will be `''   combinator   ''`(i.e. `/deep/`), but it should be `' '  + combinator +  ' '`(i.e. " /deep/ "). I.e. there needs a space before and after the combinator. But in production mode it's not, so all deep selectors won't work in production mode. 

IMO, maybe `less.js` is right because combinators usually are '>', '+', '~', '^'...  **These combinators still work even there is no space before and after them.** On the other hand, `/deep/` is a 'feature' used by Vue rather than **pure CSS**, so `less.js` doesn't consider this is passable.

### What is expected?
`div { /deep/ a { color: red; } }` -> `div a {color: red;}`

### What is actually happening?
`div { /deep/ a { color: red; } }` -> `div/deep/a {color: red;}`

### Versions
less: 3.8.1
vue-loader: 15.4.1

**Comment by posva** [comment]
FYI the deep selector is part of vue-loader, but please wait until you have a repro to open the issue

**Comment by yyx990803** [comment]
Always provide a repro, there are no exceptions because we are busy too.

**Comment by melon** [comment]
Hello NE-SmallTown, I spent nearly 10 minutes to build a small demo and didn't reproduce the issue mentioned above. But I found that if I missed the `scoped` attribute in the <style> tag, I can reproduce  the issue. So you may double check your code first to see if you missed the `scoped` attribute.
