### ISSUE TITLE
相同的两个组件在使用v-if 切换时不会触发destroy 的hook

### ISSUE THREAD

**Issue by xbl** [vuejs/vue#8844]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/g2o7a4c1/16/](http://jsfiddle.net/g2o7a4c1/16/)

### Steps to reproduce
相同的两个组件在使用v-if 切换时不会触发destroy 的hook，diff 比对时复用了组件。

### What is expected?
比对时两个组件不同时需要触发destroy，然后在复用...

### What is actually happening?
相同的两个组件在使用v-if 切换时不会触发destroy 的hook

**Comment by Justineo** [comment]
添加唯一 `key` 即可。
