### ISSUE TITLE
Can't capture dot keypress

### ISSUE THREAD

**Issue by cesalberca** [vuejs/vue#8853]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/6nw68ox9p3](https://codesandbox.io/s/6nw68ox9p3)

### Steps to reproduce
Open in Chrome and press `.`. It should prompt an alert but in Firefox it doesn't. This is because in Firefox `keyCodes` are [not supported](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and most browser will probably drop support in the future. If you check the `main.js` file I set custom keyCodes:

```js
Vue.config.keyCodes = {
  dot: 46
};
```

I need to do this (to make it at least work on Chrome) because in directives I can't use the `.` as a modifier of the directive `@keypress` like so: `@keypress..="doSomething"`.

One could think that somehow I can capture the `.` key, as described [in the documentation](https://vuejs.org/v2/guide/events.html#Automatic-Key-Modifiers) with Automatic Key Modifiers, however I can't because Vue uses `Keyboard.key` instead of `Keyboard.code`.

I think using `KeyboardEvent` is a step in the right direction, however, using **KeyboardEvent.key instead of KeyboardEvent.code will open a whole ordeal of problems, like this issue**. You can check on this [online viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) the `KeyboardEvent.key` vs `KeyboardEvent.code`.

In the `App.vue` you can check all I've tried to capture the `.` key. Here is the documentation regarding [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code).

### What is expected?
The `.` key should be captured

### What is actually happening?
The `.` key is not being captured

**Comment by posva** [comment]
The keycode for `.` is 190. It works fine on Firefox when that is fixed 🙂

**Comment by posva** [comment]
Tye code is using a version that works up to ie 9
