### ISSUE TITLE
vuejs接入的sauceLabs最近为啥看不到浏览器兼容性了

### ISSUE THREAD

**Issue by luozhang002** [vuejs/vue#8858]
### Version
2.5.17

### Reproduction link
[http://www.xxx.com](http://www.xxx.com)

### Steps to reproduce
vuejs接入的sauceLabs最近为啥看不到浏览器兼容性了。readme.md

### What is expected?
期望看到浏览器的兼容性测试结果

### What is actually happening?
期望看到浏览器的兼容性测试结果

**Comment by posva** [comment]
Thanks for your interest, it looks like it's not working on SauceLabs: https://saucelabs.com/open_sauce/user/vuejs
Maybe they're updating the generation of svgs

**Comment by luozhang002** [comment]
thanks you very much
