### ISSUE TITLE
Add an API to create a one-time watcher easily

### ISSUE THREAD

**Issue by SilentDepth** [vuejs/vue#8859]
### What problem does this feature solve?
Assume a component who need to do something when an async state gets data, for only once (means the component doesn't need to do it again when the state changes). And there is a `vm.$watch()` can help to achieve this.

But the problem is, Vue fires the callback too fast. So a code like this doesn't work:

```js
const unwatch = vm.$watch('something', () => {
  unwatch()
  doSomething()
}, {immediate: true})
```

The `unwatch` is not defined or not a function at this time. I guess the `$watch()` block was not finished when the callback was fired.

A live demo: https://codesandbox.io/s/y6qp5lyp1

Sure there are ways to avoid this problem. But I think it's better to delay the callback execution a bit, or add a new API to do this work?

### What does the proposed API look like?
A `vm.$watchOnce()`, behaves like the normal `vm.$watch()` but automatically unwatch when the callback fired once (think about `.once` modifier of events).

**Comment by sqal** [comment]
https://github.com/vuejs/vue/issues/2276

**Comment by posva** [comment]
Unwatching in a nextTick should also work if you use `immediate` btw
