### ISSUE TITLE
Filter allows mutation of state

### ISSUE THREAD

**Issue by tesla3327** [vuejs/vue#8860]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/2wqm65lnxr](https://codesandbox.io/s/2wqm65lnxr)

### Steps to reproduce
Look at the value rendered.

### What is expected?
It is expected that filters are pure functions, and should not be allowed to mutate state in any way.

### What is actually happening?
The state is being mutated, because a reference to the reactive property is passed in.

---
It breaks the conceptual model of filters being pure functions. Most people use filters as a way of transforming what is displayed, without mutating the actual underlying state.

This would be a good safeguard against potential bugs/misuse of filters.

**Comment by posva** [comment]
You have to make filters pure functions, we cannot prevent you from not doing so. That being said, the filter you provided *is* a pure function
