### ISSUE TITLE
Optional Chaining Error with Babel

### ISSUE THREAD

**Issue by tkrause** [vuejs/vue#8861]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/m674vkw2j](https://codesandbox.io/s/m674vkw2j)

### Steps to reproduce
Use the optional chaining operator in a template:

{{ user?.id }}

### What is expected?
Output the users id in the template or blank for undefined

### What is actually happening?
- invalid expression: Unexpected token . in    "\n                " _s(user?.id) "\n            "  Raw expression: {{ user?.id }}

---
Optional chaining works just fine in the script section of a SFC Vue component but does not work in the template section.

For reference, this is in an Nuxt.js 2.0 project stock settings with the babel optional chaining plugin

Version is actually 15.4.2 with Vue 2.5.17

**Comment by posva** [comment]
Babel is actually not used for in-template strings: See https://github.com/vuejs/vue/issues/6307
Not sure if anything changed regarding this 🤔

**Comment by NMelis** [comment]
@yyx990803 Did you do it? :D
