### ISSUE TITLE
cannot watch unicode properties like  'a.中文' 

### ISSUE THREAD

**Issue by ensleep** [vuejs/vue#8862]
### Version
2.5.17

### Reproduction link
https://jsfiddle.net/k72f3Lon/

### Steps to reproduce
1.webpack project with vue .
2.add a component .
3.create instance of Vue .
4.add a property `data:function(){return {a:{中文:"",b:""}}}` to the instance.
5.add watch properties to the instance as `watch:{'a.b':function(val){},'a.中文':function(val){}}`
6.console show error that Watcher only accepts simple dot-delimited paths. 

### What is expected?
no error the code run continue

### What is actually happening?
the code seems stopped to run

**Comment by posva** [comment]
Next time take the time to add the repro (which I added)

**Comment by angelina999990** [comment]
https://jsfiddle.net/589yrg0s/

**Comment by lujiaxing** [comment]
Use chinese as a key is nonstandard. We strongly recommend that use <s>latin characters</s> english words as a key.

**Comment by Suwings** [comment]
But in some cases, we still need to use Chinese characters as keys. Such as username key-value pairs.

**Comment by zhibikanmohuakai** [comment]
> But in some cases, we still need to use Chinese characters as keys. Such as username key-value pairs.

why  use  {马云：23333} instead of {'马云'： 23333}?

**Comment by g-plane** [comment]
Though using Chinese as key is strange, as a framework/library, it must consider all edge cases. It's not related to best practices.

**Comment by ensleep** [comment]
Although I also think that characters other than the underscore of English data should not be used as attributes, sometimes the interface provided by the third party, in order to reduce the complexity of docking, will directly give the JSON format data whose attributes are named in Chinese. At the time of binding, there was trouble.

**Comment by posva** [comment]
Indeed, this was added there and should be on 2.6
Thanks for notifying us!
