### ISSUE TITLE
Separate vue component into : *.ts and *.html

### ISSUE THREAD

**Issue by redplane** [vuejs/vue#8864]
Hi,

I'm using `vue-cli 3` and typescript to make my own application.
Everything seemed to be fine until I separated my module into parts: `template file` and `logic file`.
I have a component like this:

- **master-layout.component.ts**

```
@Component({
    name: 'master-layout',
    template: require('html-loader!./master-layout.component.html')
})
export default class MasterLayoutComponent extends Vue {
}
```

- **master-layout.component.html**

```
<div>
    <router-view/>
</div>
```

Actually, when this component was combined into one `*.vue` file, it ran smoothly.
But I want to separate the module into 2 parts because in future, code can be longer and longer, therefore, it is hard to track the issue if available.

When I ran the application after changing my code like above, one error was thrown to me:

**You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.**

Can anyone help ?

Thanks,

**Comment by Justineo** [comment]
You should still use your `.vue` file as entry point of a component and include a script tag with `src` attribute pointing to the separated script file.

**Comment by viT-1** [comment]
@Justineo It is not true. Nowadays [we can testing](https://github.com/viT-1/systemjs-ts-es6-vue/commit/8b331d87657af1c0948d552a9be326a20470e238) vue components without .vue files but vue-class-component with imported template (by html-loader-jest not jest-transform-stub).

**Comment by rhengles** [comment]
For anyone else coming here from search to separate your components into script, template and style files, I have a working solution in this PR:

https://github.com/vuejs/vue/pull/8807

See also the rationale in this issue:

https://github.com/vuejs/vue/issues/8106
