### ISSUE TITLE
The "simple bind" does not actually seem to improve performance at all

### ISSUE THREAD

**Issue by baybal** [vuejs/vue#8866]
### What problem does this feature solve?
There is a helper function bundled in Vue.js:

/**
 * Simple bind, faster than native
 */
function bind (fn, ctx) {
  function boundFn (a) {
    const l = arguments.length;
    return l
      ? l > 1
        ? fn.apply(ctx, arguments)
        : fn.call(ctx, a)
      : fn.call(ctx)
  }
  // record original fn length
  boundFn._length = fn.length;
  return boundFn
}

The "bind is slow" myth has not been true for quite some time. Native bind should be faster on any any much recent browser. And arrow functions should be even faster as long as there is no need to reuse these functions somewhere else.

Please refer to the benchmark https://jsperf.com/bind-is-slow

I think there should be a bigger review of other helper functions, to see if the case for their use is still there in modern browses.

### What does the proposed API look like?
Can we replace "simple bind" with native bind?

**Comment by Justineo** [comment]
The code you provided seems to be out-dated. Actually Vue now prefers native bind already.

https://github.com/vuejs/vue/blob/79cabadeace0e01fb63aa9f220f41193c0ca93af/src/shared/util.js#L176-L205

See #7408.
