### ISSUE TITLE
Computed setter not triggered on reactive Array operations

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vuejs/vue#8867]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/v312ppp2kl](https://codesandbox.io/s/v312ppp2kl)

### Steps to reproduce
Click on the "Assignment" button and you will see the alert whereas clicking on the "Pushing" button won't. Clicking on "Manual Set" button will again trigger the alert.

### What is expected?
The alert in the computed setter should be triggered on array push since push, splice etc is supposed to be reactive according to https://vuejs.org/v2/guide/list.html#Array-Change-Detection

### What is actually happening?
Assignment to an array triggers the computed setter but `array.push` and other "reactive" array operations doesn't. The alert also gets triggered if a manual `$set` is done.

---
Is this behaviour expected?

**Comment by posva** [comment]
The setter is only applied when doing an assignment

**Comment by SayakMukhopadhyay** [comment]
Can application of the setter on a reactive array operation be considered as a feature in the future?

**Comment by posva** [comment]
I think it could, but for the moment just use a method and put the side effect there 🙂

**Comment by ThaDaVos** [comment]
Sorry for posting on an old issue - I'll create a new one if needed - but I'm running into the same issue as I'm using a computed property to convert from an array to a string and back automatically, is there any known fix?
```JavaScript
      array: {
          get() {
              if (this.value !== undefined && (typeof(this.value) === 'string' || this.value instanceof String)) return this.value.split(/[\s,\|;]+/);
              else return [];
          },
          set(val) {
              console.log(val);
              if (val !== undefined && val instanceof Array) this.$emit('input', val.join(','));
              else this.$emit('input', val.toString());
          }
      }
```
