### ISSUE TITLE
v-model.lazy doesn`t update input value when I press Enter

### ISSUE THREAD

**Issue by nikitaGetman** [vuejs/vue#8874]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/NikitaGetman/nrst6hf4/](https://jsfiddle.net/NikitaGetman/nrst6hf4/)

### Steps to reproduce
1. Open console
2. Type something in input and press Enter
3. data updated and getter called but value the same
4. Type something in input and change focus
5. It works well!

### What is expected?
When you press Enter value have to update too, like in previus version

### What is actually happening?
When you press Enter getter called but value the same

**Comment by posva** [comment]
It does work...
FYI, lazy change the event listener from input to change, it's not related to enter being pressed. Maybe the browser you are testing is not emitting that event. You should maybe use a form with submit event if you want to detect the enter

**Comment by nikitaGetman** [comment]
I mean input.value, not vue.data
vue.data updates well. But input.value still the same in spite of getter called
In vue 2.2.1 input updates when I press Enter

**Comment by nikitaGetman** [comment]
> It does work...
> FYI, lazy change the event listener from input to change, it's not related to enter being pressed. Maybe the browser you are testing is not emitting that event. You should maybe use a form with submit event if you want to detect the enter

I mean input.value, not vue.data
vue.data updates well. But input.value still the same in spite of getter called
In vue 2.2.1 input updates when I press Enter

**Comment by nikitaGetman** [comment]
@posva 
![image](https://user-images.githubusercontent.com/14196788/46261816-8b72dd00-c501-11e8-9bf0-176b3465ce0d.png)
