### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alexbazhin-alphaflightguru** [vuejs/vue#8879]
### What problem does this feature solve?
On the screen you can see the output of the Vue-component in the method destroyed. After destroy, the Vue-component continues to store a lot of data that remains in memory. This causes a memory leak.

![Image 1](https://cdn1.savepice.ru/uploads/2018/10/1/c5f452f83f2803f80fd6e221782d2340-full.jpg)

These screens show the amount of data that is stored in memory when the routing changes (I use vue-router - v.3.0.1). The number of Vue-components is constantly growing.

### Page 1

![Image 2](https://cdn1.savepice.ru/uploads/2018/10/1/f2cbf13281dcf74bfc227529f2663e74-full.jpg)

### Page 2

![Image 3](https://cdn1.savepice.ru/uploads/2018/10/1/6b9980aee1fc07c0cf25a5a9076f7b78-full.jpg)

### Page 3

![Image 4](https://cdn1.savepice.ru/uploads/2018/10/1/1986c133b3447ff152113aaa29386238-full.jpg)

**After that the memory usage goes up to 1Gb.**

### What does the proposed API look like?
Why is this happening?

**Comment by posva** [comment]
reports
