### ISSUE TITLE
Custom multiple select input does not work correctly

### ISSUE THREAD

**Issue by pengstrom** [vuejs/vue#8883]
### Version
2.5.17

### Reproduction link
[https://gitlab.com/pengstrom/vue-multi-select-bug/](https://gitlab.com/pengstrom/vue-multi-select-bug/)

### Steps to reproduce
Select multiple options in a custom select input. Compare with direct input.

### What is expected?
The model selection should be an array of selected options.

### What is actually happening?
Only one element is arbitrarily returned.

**Comment by posva** [comment]
that's how v-model works with components. Remember it's just syntax sugar around `:value="value" @input="value = $event"`
On inputs it, the v-model implementation handles that for you. You will have to either implement yourself. Or use `v-model` with a computed setter and `$emit` inside of the setter (which is the best option here 🙂 )
