### ISSUE TITLE
Vue custom module resolution doesn't seem to work

### ISSUE THREAD

**Issue by wizardnet972** [vuejs/vue#8886]
I create a new `vue` project via `vue/cli`: `vue create hello-world` (all the options he asks are selected).

Then I create a `index.ts` file in `hello-world/libs/test-lib` folder with the following content:

```
export const item = 1;
```
In main.ts and home.vue I imported this module to use them:
```
import {item} from '@libs/test-lib';

console.log('item', item);
```

and in my tsconfig.json I add:

```
 "@libs/*": [
   "libs/*"
  ]
```
My vscode is resolve this path. but when I try to run build or serve (npm run build) As a result, I am getting an error:
```
@libs/test-lib in ./src/main.ts, ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--13-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save @libs/test-lib
```

![image](https://user-images.githubusercontent.com/4997825/46329264-f6610880-c614-11e8-8808-9c12b746e6c5.png)

**Any help would be much appreciated.**

**Comment by leopiccionia** [comment]
You have to tell Webpack about your TypeScript aliases.

Insert a `vue.config.js` file in your project root with a content like this:
```js
const path = require('path');

function resolve(dir) {
  return path.join(__dirname, dir);
}

module.exports = {
    chainWebpack: config => {
        config.resolve.alias.set('@libs', resolve('libs'));
    }
}
```

You could obviously make it `vue.config.ts` as an exercise.

**Comment by wizardnet972** [comment]
@leopiccionia thank you!
