### ISSUE TITLE
Recent versions of Vue do not work with lazy (async) components with node and SSR

### ISSUE THREAD

**Issue by ilyaskorik** [vuejs/vue#8891]
### Version
2.5.17

### Reproduction link

I migrated the reference project vue-hackernews to Webpack 4 and the latest libraries

[https://github.com/ilyaskorik/vue-hackernews-3.0](https://github.com/ilyaskorik/vue-hackernews-3.0)

### Steps to reproduce
Build and run:

yarn install; yarn build; yarn start;

Open localhost:8080

### What is expected?
I expect the site to work with lazy components

### What is actually happening?
Nodejs does not finish import a component, Promise in vue-router never resolve itself

---
I tried to build a similar project using vue-cli, also failed. I tried node 8, node 10. It will be great to understand what the error is.

**Comment by geedew** [comment]
Do you happen to know ow what version of Node you are running this on? Node 8 for instance would have trouble with the 'import' syntax.

**Comment by posva** [comment]
A boiled down repro is necessary, thank you :)

**Comment by ilyaskorik** [comment]
> A boiled down repro is necessary, thank you :)

Why you close this?

**Comment by ilyaskorik** [comment]
> Do you happen to know ow what version of Node you are running this on? Node 8 for instance would have trouble with the 'import' syntax.

@geedew 8 and 10

**Comment by posva** [comment]
because a boiled down repro is necessary.

**Comment by ilyaskorik** [comment]
> because a boiled down repro is necessary.

https://github.com/ilyaskorik/vue-hackernews-3.0

???

**Comment by yyx990803** [comment]
**boiled down**

**Comment by ilyaskorik** [comment]
> A **boiled down** repo, not an entire project.

@posva How I can do it?
