### ISSUE TITLE
Can't set default selected value when v-model is defined

### ISSUE THREAD

**Issue by flytomek** [vuejs/vue#8893]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/50wL7mdz/756766/](http://jsfiddle.net/50wL7mdz/756766/)

### Steps to reproduce
1. Run the code, default selected value is empty (expected is "3")
2. Delete v-model="test" from select tag
3. Selected value is 3, as expected

### What is expected?
Selected default value of "3"

### What is actually happening?
Empty selected value

**Comment by posva** [comment]
You need to provide the initial value in the variable passed to v-model. Also, don't forget to set a `value` in every option 😀 (`:value="l.id"`)

**Comment by HerrBertling** [comment]
I translated @posva's answer into the fiddle :) http://jsfiddle.net/50wL7mdz/757433/

**Comment by flytomek** [comment]
Right, thank you!
