### ISSUE TITLE
Watcher does not fire immediately

### ISSUE THREAD

**Issue by NoRabbit** [vuejs/vue#8898]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Lmn0ehcs/8/](https://jsfiddle.net/Lmn0ehcs/8/)

### Steps to reproduce
Click on the "Update" button.

### What is expected?
The "property change watched" message should be in between the two other logs as the watcher should be fired right after the property has changed.

- increasing property
- property change watched 1 0
- property increased

### What is actually happening?
The "property change watched" message is dispatched after the two other logs, indicating that the second log was executed before the watcher while it should have executed after the property change.

- increasing property
- property increased
- property change watched 1 0

**Comment by sirlancelot** [comment]
Watchers don't fire immediately. This is by design. To prevent the watcher from firing multiple times in a single tick, they are queued and run later. If you need to wait until watchers are done firing, you can use `Vue.nextTick()` or `vm.$nextTick()`

https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue

**Comment by NoRabbit** [comment]
I have too many properties to "watch", I don't want to create a method for each one of them. The watch system of vue seemed to be a good fit as it s totally integrated into my app. It would have been extremelly useful to just use it as well for that.

Ok, too bad. I'll try to find another way. Thanks.

**Comment by sirlancelot** [comment]
Generally, watchers are for side-effects. If you have a lot of properties that depend on one another, you may have better results by leveraging computed properties. Computed properties are executed on-demand which sounds like what you want, just be careful not to use them for side-effects.

**Comment by NoRabbit** [comment]
Allright, I'll try that path, see if I can actually use it for my needs.
I saw a couple of techniques out there to use computed properties with watchers, I even set up a system to watch multiple properties with a single callback... but it seems too convoluted for my taste... I guess I'll create a custom system on top of vue...
Thanks a lot for your time !
