### ISSUE TITLE
SSR hydration issue

### ISSUE THREAD

**Issue by cslee** [vuejs/vue#8899]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/k3ln8nlmnr](https://codesandbox.io/s/k3ln8nlmnr)

### Steps to reproduce
This code causes hydration issue when run with SSR
```
<template>
  <div>{{ emptyString }}<i v-if="falsyValue">test</i></div>
</template>

<script>
export default {
  data () {
    return {
      emptyString: '',
      falsyValue: false
    }
  }
}
</script>
```

### What is expected?
No hydration issue

### What is actually happening?
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside `<p>`, or missing `<tbody>`. Bailing hydration and performing full client-side render.

**Comment by Justineo** [comment]
`<i>` is not a void element thus you should always include the end tag.

**Comment by cslee** [comment]
@Justineo Self closing tag is valid in vue template. Vue's eslint plugin even recommends self closing style.
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md

But it doesn't matter here. The hydration issue occurs with separate start and end tag too.

**Comment by Justineo** [comment]
The sandbox above doesn't seem to reflect the SSR issue, can you provide a configured repo in order to reproduce the problem?

**Comment by posva** [comment]
Closing until a repro is provided

**Comment by cslee** [comment]
Sorry that I can't find similar site that support SSR. But it's possible to see the issue by simply adding the snippet `<div>{{ '' }}<i v-if="false">test</i></div>` into any component in vue-hackernews-2.0.

By the way, it's found that there is no issue when there is a *space* next to the mustache.
Below cases don't cause hydration issue. So I could avoid the issue by myself even if the issue is not being fixed.
```
<div> {{ '' }}<i v-if="false">test</i></div>
```

```
<div>{{ '' }} <i v-if="false">test</i></div>
```

```
<div>
  {{ '' }}<i v-if="false">test</i>
</div>
```

**Comment by posva** [comment]
You can use this: https://ssr.vuejs.org/ 🙂
