### ISSUE TITLE
Array element in Template syntax is not updating(inside a component)

### ISSUE THREAD

**Issue by geongeorge** [vuejs/vue#8900]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/vmmz5mykr7](https://codesandbox.io/s/vmmz5mykr7)

### Steps to reproduce
Open the reproduction link and click on an option. It'll say if you're correct or not. 
Click next question. 
The DOM is not updated inside the component. 
log button will log what the array variable options[] contains.
each button in the question component contains one option.

### What is expected?
Each button in the result is supposed to have the corresponding option on it from the options[] array

### What is actually happening?
options array is updated while the button remains to contain the old value.
https://i.imgur.com/zDXrhvm.png

---
I believe this is a bug related to reactivity. I tried vm.$forceUpdate() and it seemed to work.

**Comment by Justineo** [comment]
It’s working as expected. See the [docs](https://vuejs.org/v2/guide/list.html#Caveats).

You need to manually set values in this case:

```js
this.$set(this.options, index, randomval);
```

**Comment by geongeorge** [comment]
Thank you! I had searched a lot for this.
