### ISSUE TITLE
input[type='date']的输入框,用v-model绑定数据报格式错误

### ISSUE THREAD

**Issue by GiantLiu** [vuejs/vue#8907]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/759474/](https://jsfiddle.net/50wL7mdz/759474/)

### Steps to reproduce
<input type="date" v-model="testDate">
 var productApp = new Vue({
            el: "#productApp",
            data: {
                testDate: "2018-10-09 00:00:00"
            }
});
如果testDate为“2018-10-09”这样的格式是可以的
但是如果后面多了时间，就不能绑定数据了

### What is expected?
我感觉要加上官方的日期过滤器，不然一些基础类型支持不好

### What is actually happening?
一般数据库保存的时间格式都是带时间信息的。只是在前端显示要做格式化而以，到前端转成标准的json就是有时间信息的

**Comment by posva** [comment]
the input with type date works...

**Comment by leeezhou** [comment]
> <input> elements of type date create input fields that let the user enter a date, either using a text box that automatically validates the content, or using a special date picker interface. The resulting value includes the year, month, and day, but not the time. 

> The HTML <input type="datetime"> was a control for entering a date and time (hour, minute, second, and fraction of a second) as well as a timezone.

[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime)
