### ISSUE TITLE
Unnecessary update caused by state change in parent component

### ISSUE THREAD

**Issue by Jovaage** [vuejs/vue#8909]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/zzq75rm38x](https://codesandbox.io/s/zzq75rm38x)

### Steps to reproduce
Create a component, A, which makes use of `$listeners` in the template somehow.
Create a component, B,  that includes component A, so that an instance of B is parent of an instance of A.
Attach an event listener to A in B.
Update state in component B somehow.

### What is expected?
Component B should update, and component A should be unaffected.

### What is actually happening?
Component A is updated. It is rendered again, and the update lifecycle hooks are triggered.

**Comment by posva** [comment]
This is because the inline function (`() => {}`) generates a new function every time App.vue renders, therefore changing `$listeners`

**Comment by Jovaage** [comment]
@posva 
I have now updated the sandbox to no longer use an inline function, but instead a method of the parent component.
It still has the unexpected behaviour.

**Comment by posva** [comment]
Duplicate of #7257
