### ISSUE TITLE
SonarQube Found 3 Critical Vulnerability Issues (owasp-a1)

### ISSUE THREAD

**Issue by monasdyas** [vuejs/vue#8910]
### What problem does this feature solve?
```javascript
function checkIdentifier (
  ident,
  type,
  text,
  errors
) {
  if (typeof ident === 'string') {
    try {
      new Function(("var "   ident   "=_"));
// Review this "Function" call and make sure its arguments are properly validated.
// L10636 Critical Vulnerability
    } catch (e) {
      errors.push(("invalid "   type   " \""   ident   "\" in expression: "   (text.trim())));
    }
  }
}
function checkExpression (exp, text, errors) {
  try {
    new Function(("return "   exp));
// Review this "Function" call and make sure its arguments are properly validated.
// L10645 Critical Vulnerability
  } catch (e) {
    var keywordMatch = exp.replace(stripStringRE, '').match(prohibitedKeywordRE);
    if (keywordMatch) {
      errors.push(
        "avoid using JavaScript keyword as property name: "  
        "\""   (keywordMatch[0])   "\"\n  Raw expression: "   (text.trim())
      );
    } else {
      errors.push(
        "invalid expression: "   (e.message)   " in\n\n"  
        "    "   exp   "\n\n"  
        "  Raw expression: "   (text.trim())   "\n"
      );
    }
  }
}
function createFunction (code, errors) {
  try {
    return new Function(code)
// Review this "Function" call and make sure its arguments are properly validated.
// L10667 Critical Vulnerability
  } catch (err) {
    errors.push({ err: err, code: code });
    return noop
  }
}
```

##### Function constructors should not be used

In addition to being obtuse from a syntax perspective, function constructors are also dangerous: their execution evaluates the constructor's string arguments similar to the way eval works, which could expose your program to random, unintended code which can be both slow and a security risk.

In general it is better to avoid it altogether, particularly when used to parse JSON data. You should use ECMAScript 5's built-in JSON functions or a dedicated library.

###### Noncompliant Code Example

	var obj =  new Function("return "   data)();  // Noncompliant
	
###### Compliant Solution

	var obj = JSON.parse(data);

###### Exceptions
Function calls where the argument is a string literal (e.g. `(Function('return this'))())` are ignored.

###### See
OWASP Top 10 2017 Category A1 - Injection

![sonarqube-vuejs-vulnerability-new_function](https://user-images.githubusercontent.com/17085689/46670874-0a3fd800-cbdc-11e8-834e-56c9d15bbbd9.png)

**Comment by posva** [comment]
These are necessary for the compiler to report some errors but are not present in the runtime version of Vue.
Also, keep in mind this could only be a problem if you compile templates coming from users which has tons of other problems

**Comment by THr725** [comment]
Can anyone tell solution for this??
