### ISSUE TITLE
SonarQube Found 5 Blocker Code Smell Issues

### ISSUE THREAD

**Issue by monasdyas** [vuejs/vue#8911]
#### 1.
```javascript
{
  strats.el = strats.propsData = function (parent, child, vm, key) {
    if (!vm) {
      warn(
        "option \""   key   "\" can only be used during instance "  
        'creation with the `new` keyword.'
      );
    }
    return defaultStrat(parent, child)
// Move the declaration of "defaultStrat" before this usage.
// L1127 Code Smell Blocker
  };
}
// Declaration L1326
var defaultStrat = function (parentVal, childVal) {
  return childVal === undefined
    ? parentVal
    : childVal
};
```

#### 2.
```javascript
new Watcher(vm, updateComponent, noop, null, true /* isRenderWatcher */);
// Move the declaration of "Watcher" before this usage.
// L2795 Code Smell Blocker
// Declaration L3082
var Watcher = function Watcher (
  vm,
  expOrFn,
  cb,
  options,
  isRenderWatcher
)
```

#### 3.
```javascript
var normalizedName = normalize(name);
// Move the declaration of "normalize" before this usage.
// L7275 Code Smell Blocker
// Declaration L7292
var normalize = cached(function (prop) {
```

#### 4.
```javascript
if (def.css !== false) {
	extend(res, autoCssTransition(def.name || 'v'));
// Move the declaration of "autoCssTransition" before this usage.
// L7427 Code Smell Blocker
}
// Declaration L7436
var autoCssTransition = cached(function (name) {
```

#### 5.
```javascript
var end = function () {
	el.removeEventListener(event, onEnd);
// Move the declaration of "onEnd" before this usage.
// L7513 Code Smell Blocker
	cb();
};
// Declaration L7515
var onEnd = function (e) {
	if (e.target === el) {
		if (  ended >= propCount) {
			end();
		}
	}
};
```

##### Variables should be declared before they are used  

Variables declared with var have the special property that regardless of where they're declared in a function they "float" to the top of the function and are available for use even before they're declared. That makes scoping confusing, especially for new coders. To keep confusion to a minimum, var declarations should happen before the variables they declare are used for the first time.

###### Noncompliant Code Example

	var x = 1;
	function fun(){
		alert(x); // Noncompliant as x is declared later in the same scope
		if(something) {
			var x = 42; // Declaration in function scope (not block scope!) shadows global variable
		}
	}
	fun(); // Unexpectedly alerts "undefined" instead of "1"

###### Compliant Solution

	var x = 1;
	function fun() {
		print(x);
		if (something) {
			x = 42;
		}
	}
	fun(); // Print "1"

![sonarqube-vuejs-blockers](https://user-images.githubusercontent.com/17085689/46671798-5ee45280-cbde-11e8-84d0-ac49f291d7e3.png)

**Comment by posva** [comment]
Please do not automatically open issues like this.
It's fine if you use a tool to get some guidance, but at least provide a repro illustrating the problem or do some summarising instead of just copy pasting the whole thing. Thank you
