### ISSUE TITLE
_scopeId missing on some slot elements when slot root element is the same as the one its replacing

### ISSUE THREAD

**Issue by lzhoucs** [vuejs/vue#8917]
### Version
2.5.17

### Reproduction link
[https://codepen.io/lzhoucs/pen/pxeaQq](https://codepen.io/lzhoucs/pen/pxeaQq)

### Steps to reproduce
Go to the provided codepen demo link, click on a group to expand, not all expanded items are in red. `_scopeId` is missing on some items. 

### What is expected?
All expanded items should be in red

### What is actually happening?
Not all expanded items are in red. `_scopeId` is missing on some items. 

---
It works when the root element (h2) of `item` scoped slot is different from the one it is replacing(h1). It doesn't work when they are the same(h1)

**Comment by Justineo** [comment]
It works by adding keys when you generate children inside a loop. See this [pen](https://codepen.io/Justineo/pen/zmZJJa).

**Comment by lzhoucs** [comment]
Thanks. It worked very well by adding keys.
