### ISSUE TITLE
/deep/深度选择器，部分情况下无法穿透成功

### ISSUE THREAD

**Issue by 3344567** [vuejs/vue#8918]
### Version
2.3.2

### Steps to reproduce
<el-form-item id="selectParent">
                            <el-input 
                                class="input-with-select" 
                                placeholder="请输入关键字" 
                                maxlength="50"
                                v-model="searchForm.keywords">
                                <el-select class="select"  slot="prepend" v-model="searchForm.typeName"
                                        placeholder="请选择">
                                    <el-option
                                        v-for="item in typeNameOptions"
                                        :key="item.value"
                                        :label="item.label"
                                        :value="item.value">
                                    </el-option>
                                </el-select>
                                <i slot="prefix" class="el-input__icon">|</i>
                                <i slot="suffix" @click="getAddressOptions()"
                                class="el-input__icon el-icon-search"></i>
                            </el-input>
                        </el-form-item>
<style scoped>
#selectParent /deep/ .el-input__suffix{
    right: 0;
}
</style>

### What is expected?
我想修改elementUI 部分样式时，用深度选择器，使本组件下的.el-input__suffix的right属性从默认的5px改成0

### What is actually happening?
结果el-input__suffix没有添加上data-**-****属性，导致未成功修改。把deep改成>>>，同样未成功

**Comment by Justineo** [comment]
This issue should be reported to Vue loader. Please file the issue in that repo with a boiled down runnable reproduction. Thanks.
