### ISSUE TITLE
Store list.length in a variable

### ISSUE THREAD

**Issue by p1pchenk0** [vuejs/vue#8922]
### What problem does this feature solve?
Increase performance during Vue preparations. During Vue initialization process there is a function `makeMap`, which splits string of items into array and then create Map-like object. But during for-loop every iteration it checks `list.length` value, which can be stored in separate variable before running for-loop. For arrays of 40  this can improve performance

### What does the proposed API look like?
```javascript
    function makeMap (str, expectsLowerCase) {
        var map = Object.create(null);
        var list = str.split(',');
        var listLength = list.length;  // <--  here it is

        for (var i = 0; i < listLength; i++) {
            map[list[i]] = true;
        }
        
        return expectsLowerCase ? function (val) { return map[val.toLowerCase()] } : function (val) { return map[val] }
  }
```

**Comment by p1pchenk0** [comment]
during exploring Vue source code I've found other places, too, where this length caching can be applied. I can create pull-request

**Comment by Justineo** [comment]
For code refactoring targeting performance, we need a benchmark to show the changes are worthwhile. And according to some [existing benchmarks](http://jsben.ch/y3SpC) I found the results are almost identical (sometimes the uncached version is even faster) on latest browsers.

**Comment by Justineo** [comment]
If you run the benchmark above multiple times you’ll see there is no clear winner here (at least on modern browsers).

**Comment by yyx990803** [comment]
Thanks for the suggestion - however, in general modern JavaScript engines are smart enough to notice static array lengths and in practice this does not result in noticeable differences - especially for cases like `makeMap` which is insignificant in terms of total startup cost.
