### ISSUE TITLE
setting object1 from another object (object2,)  object1 overwrites the original one (object2) when object1 is modified

### ISSUE THREAD

**Issue by OrbanMia** [vuejs/vue#8924]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/50wL7mdz/761079/](https://jsfiddle.net/50wL7mdz/761079/)

### Steps to reproduce
Make two variables with the same keys, call them obejct1 and object2.
If I write object1 = object2 anywhere in my code, after modifying object1's any values, objec2's value will be overwritten.
But if I write object1.key1 = objec2.key1 and object1.key2 = object2.key2 then I can modify anything in object1, object2 will not change.

### What is expected?
modifying object1 won't modify object2

### What is actually happening?
modifying object1 modifies object2

**Comment by yyx990803** [comment]
This is how JavaScript works. If you want to make a copy, you need to explicitly clone the object.
