### ISSUE TITLE
Child transitions are triggered when the parent element is hidden

### ISSUE THREAD

**Issue by BryceBarbara** [vuejs/vue#8926]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/BryceBarbara/kv7espnq/](https://jsfiddle.net/BryceBarbara/kv7espnq/)

### Steps to reproduce
1. Click the "Toggle Screen" button.
2. See that the first screen's content is faded out while the second screen's content is already visible.

### What is expected?
I would expect the transition to not trigger due to the fact that the parent has been hidden and does not have a transition on it.

### What is actually happening?
The child element on the first screen is faded out after the second screen's content is already visible.

---
I assume this is some sort of element re-use situation because adding a key to either the first or second screen elements fixes it. I'm reporting this mainly to call attention to something that doesn't _seem_ intentional and that has very little information on it.

**Comment by posva** [comment]
This is indeed a caveat related to element reuse. It's necessary to provide a key to the outer div. I'm not even sure if we could document this properly tbh :/

**Comment by reaysawa** [comment]
Could this be attempted to be solved with some conditional disposing code through updateChildren https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L405 or patchVnode https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L502? Perhaps a way to mark that the node should not have its own transition hooks triggered if the parent context has been replaced and/or is not part of the same transition group.

**Comment by benjialternate** [comment]
https://edricblubber53.github.io/entity42/



Look this direction for the answer
