### ISSUE TITLE
Ability to pass event listeners when creating components with the "new" keyword, like propsData does for props

### ISSUE THREAD

**Issue by jonaslm** [vuejs/vue#8937]
### What problem does this feature solve?
Vue already has the ability to pass props to components when creating them with the `new` keyword, using `propsData`. As far as I can tell it's not possible to do this with events, however.

Events *can* be added to the component, but only after creation. This means that any events that are emitted in the component `created` hook or on immediate watchers cannot be caught when creating components with the `new` keyword.

### What does the proposed API look like?
Something akin to `propsData` for props, but instead for event listeners:
```
new MyComponent({
  propsData: {
    myProp: this.myProp,
  },
  listeners: {
    myEvent: this.onMyEvent,
  }
});
```

**Comment by posva** [comment]
This can be created in user land through a mixing that attaches the events with `this.$on` on `created` and removes them on `destroyed`. Since we are in API freeze and this can be implemented in user land we will pass on this 🙂

**Comment by jonaslm** [comment]
Fair enough, hadn't thought of making a mixin for it! Thanks for the tip!
