### ISSUE TITLE
Vue is not compatible with ios8.x

### ISSUE THREAD

**Issue by zengyufang** [vuejs/vue#8938]
### Version
2.5.1

### Reproduction link
[http://www.ji-cn.com/longshan/t/index.html](http://www.ji-cn.com/longshan/t/index.html)

### Steps to reproduce
Our project use vue in this way: <script src="/js/vue.min.js"></script>,but our project not open in ios version with 8.x,
then I have a try to use babel in this way: <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>,
and declare that the type of script is text/babel,But the problem has not been solved

### What is expected?
can you help me?thanks!

### What is actually happening?
the problem has not been solved

**Comment by posva** [comment]
Please provide a boiled down repro
