### ISSUE TITLE
Scoped CSS not applied for programmatically append styles in head tag

### ISSUE THREAD

**Issue by dharmatv** [vuejs/vue#8940]
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/vb18hcnd/](https://jsfiddle.net/vb18hcnd/)

### Steps to reproduce
<script>
export default{
created(){
 var style = document.createElement('style');
        style.type = 'text/css';
        
        style.id = name;
        style.setAttribute("scoped", "");
        style.innerHTML = content;   //add styles for dynamically
        document.getElementsByTagName('head')[0].appendChild(style);
}
</script>

### What is expected?
solution for scoped is applied for styles

### What is actually happening?
scoped is not working for inner styles

---
I am trying to add /deep/ in my dynamically adding styles but it's not updated

**Comment by posva** [comment]
That's pretty much the point of scoped css, to not get applied outside of the component
