### ISSUE TITLE
v-model doesn't work as expected with hebrew on mobile phone

### ISSUE THREAD

**Issue by yakovyarmo** [vuejs/vue#8945]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/yakovyarmo/kw64ynt8/3/](https://jsfiddle.net/yakovyarmo/kw64ynt8/3/)

### Steps to reproduce
Start typing in the input using hebrew language on mobile device.

### What is expected?
The data should be update on every input.

### What is actually happening?
The data is updated some of the time and cause inconsistency.

---
I suspect that the issue occur becuse for some reason the browser treat hebrew with IME.
There has to be a way around it. maybe by a modifier that will trigger the update for native input.

**Comment by posva** [comment]
This is expected with IME indeed. You can listen to individual events like `input` and `compositionstart` if you need the values as they are typed

**Comment by posva** [comment]
what I'm saying is that v-model waits for the composition to be finished, if you want to get around that, you will have to use native events :)

**Comment by yakovyarmo** [comment]
why is that ok?
If the user left the field it will never emit compositionend.
That's a really big issue.
I don't think we need to sweep it under the rug.

**Comment by tmorehouse** [comment]
@posva  Maybe the v-model directive should clear the `evt.target.composing` flag on `blur`?

somehwere in this section: https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/directives/model.js#L34
