### ISSUE TITLE
Animation in childs is broken on latest Chrome

### ISSUE THREAD

**Issue by sombra2eternity** [vuejs/vue#8947]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Sjeiti/sqyoxs8d/](https://jsfiddle.net/Sjeiti/sqyoxs8d/)

### Steps to reproduce
The first browser is Chromium (69.0.3497.81 running on Ubuntu 16.04) but behave the same on Chrome (69.0.3497.100).
The latest browser where this works is Firefox (62.0.3)

https://youtu.be/cWU5JFXhF8A

### What is expected?
The 'world' word should turn red progressively

### What is actually happening?
The 'world' word turns red without progression

**Comment by yyx990803** [comment]
This is a wontfix, because this is more likely an implementation quirk of Chrome. You can workaround this by always giving the span a color transition.
