### ISSUE TITLE
Typescript: Property 'foo' does not exist on type 'Vue'.

### ISSUE THREAD

**Issue by fjc0k** [vuejs/vue#8954]
### Version
2.5.17

### Reproduction link
[https://stackblitz.com/edit/typescript-bc9ywj](https://stackblitz.com/edit/typescript-bc9ywj)

### Steps to reproduce
1. open `index.ts`, you will see:

![image](https://user-images.githubusercontent.com/13151189/46964731-6d010a00-d0db-11e8-92a3-4a0703ffa1a1.png)

2. change `x: [String, Number, Array]` to `x: [String, Number]`, then errors disappear:

![image](https://user-images.githubusercontent.com/13151189/46964828-b94c4a00-d0db-11e8-820a-85ff22ad39b3.png)

### What is expected?
no typing errors.

### What is actually happening?
typing errors exist.

**Comment by posva** [comment]
Check https://vuejs.org/v2/guide/typescript.html

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by fjc0k** [comment]
emm, this is not a bug. this will be ok:

```ts
x: [String, Number, Array as () => Array<string | number>]
```

**Comment by ITsolution-git** [comment]
I am experiencing the exact same issue. @fjc0k Can you please point me way out?

**Comment by fjc0k** [comment]
@ITsolution-git Sorry, I haven't used vue for a long time. Now, I prefer react, which works better with typescript.

**Comment by ITsolution-git** [comment]
```
export default Vue.extend({
    name: 'WebWhatsNew',
    data() {
        return {
            currentSlide: 0 as number
        };
    },
    methods: {
        nextSlide() {
            this.currentSlide += 1;
        },
    },
    computed: {
        internalOpen: {
            get(): boolean {
                return this.value;
            },
            set(val) {
                (this as any).$emit('input', false);
            },
        },
    },
});
```
I get this typing error with the code above.
![image](https://user-images.githubusercontent.com/24530559/76094739-1d9dd100-5f91-11ea-9efe-e8da4e2965bd.png)

When I remove 
```
            set(val) {
                (this as any).$emit('input', false);
            },
```
then the compile error is gone. 

Can anyone help

**Comment by ITsolution-git** [comment]
```
export default Vue.extend({
    name: 'WebWhatsNew',
    data() {
        return {
            currentSlide: 0 as number
        };
    },
    methods: {
        nextSlide() {
            this.currentSlide += 1;
        },
    },
    computed: {
        internalOpen: {
            get(): boolean {
                return this.value;
            },
            set(val) {
                (this as any).$emit('input', false);
            },
        },
    },
});
```
I get this typing error with the code above.
![image](https://user-images.githubusercontent.com/24530559/76094739-1d9dd100-5f91-11ea-9efe-e8da4e2965bd.png)

When I remove 
```
            set(val) {
                (this as any).$emit('input', false);
            },
```
then the compile error is gone. 

Can anyone help @posva @fjc0k

**Comment by azmatzuberi** [comment]
I have this problem too. Was banging my head on the wall until I read this thread

**Comment by jQrgen** [comment]
+1
