### ISSUE TITLE
click() won't trigger that call in watch

### ISSUE THREAD

**Issue by JJJYY** [vuejs/vue#8958]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/jesse_y/L9gjbcz7/39/](https://jsfiddle.net/jesse_y/L9gjbcz7/39/)

### Steps to reproduce
1. click `checkbox` won't show file window
2. exec script `MessageChannel = {}` before import `vue` script, ***click `Run`***
3. click `checkbox` show file window

### What is expected?
click `checkbox` show file window

### What is actually happening?
click `checkbox` won't show file window

---
I test in `Chrome v69` and `Safari v12`.

**Comment by posva** [comment]
The browser won't let you trigger the click outside of a user action: https://stackoverflow.com/questions/8595389/programmatically-trigger-select-file-dialog-box

**Comment by JJJYY** [comment]
@posva why it works when I exec `MessageChannel = {}` before import vue( nextTick with `setTimeout` )
and I test as you said, it wont trigger too
https://jsfiddle.net/jesse_y/L9gjbcz7/51/

Thanks for your time!
