### ISSUE TITLE
Remove element during preTransformNode

### ISSUE THREAD

**Issue by destructive-dragon** [vuejs/vue#8959]
### What problem does this feature solve?
We have a Mobile build and a Web build, and we want to add a directive `mobile` or `web` to components/elements so that they only get included into the bundle if they are built with the respective flags / env.

Currently we are doing this via a vue-cli plugin which executes `preprocess` on the template (using a custom loader). We tried using `directives` and `modules` in `compilerOptions` instead, as this seemed safer and more idiomatic, however we were unable to remove elements using any of the callbacks.

### What does the proposed API look like?
We tried returning `null` and `{}` and even `{ type: 3, text: "", isComment: true }` from `preTransformNode` (and `transformNode`), but it just resulted in various errors. We also tried changing `el.parent.children` which didn't yield any results.

I think having the element just be removed when returning `null` from `preTransformNode` would be great, if that is possible.

**Comment by posva** [comment]
Not completely sure about what you are asking, but it looks more like a tooling question about how to get your build working. People at Nativescript have got things like this working with multiple templates.
If you want a component to not appear or only appear on Mobile, I would recommend you use a component that does media queries: https://github.com/egoist/vue-media but I don't know if you have two builds or just one. Anyway, this should probably go into the forum or contain more details

**Comment by destructive-dragon** [comment]
@posva 

No, as stated in my post, this is not about components appearing and disappearing. This is about being able to transform the Template at build time. Nativescript obviously has nothing to do with this, and this is not a question either.

It's about Vue's build system, in particular it's `vue-template-compiler` not providing an option to remove elements (only to add them). This in turn limits what is possible with directives at build time.

We won't be using media queries as that would require us to almost duplicate the build size and severely worsen performance of both our mobile and our web app.

As I said in my post, we were using Preprocess in AngularJS, and now are looking for a way to do the same thing in a bit cleaner way. If that isn't supported, well, then bad luck and we have to manually parse the templates.

Please tell me what is unclear to you.

**Comment by KaelWD** [comment]
Looks like you might be able to do `el.if = 'false'`? Might also need to push to `el.ifConditions` though.

**Comment by adi-zz** [comment]
@destructive-dragon, if I am not wrong, something like this may work:
```
// nuxt.config.js of a nuxt 2 project
build:   {
  // ...
  extend(config, ctx) {
      ctx.loaders.vue.compilerOptions = { 
        modules: [{
          preTransformNode(astEl) {
            if(astEl.attrsMap.hasOwnProperty('data-remove-me')) { // some logic to know what to remove
              astEl.attrsList.push({name: 'v-if', value: 'false'})
              astEl.attrsMap['v-if'] = 'false'
            }
            return astEl
          },
        }],
      }
  }
}
```
If the element you try to remove is the root of a component, you may get some errors...

@posva, there may exist many reasons to close an issue, but you not understanding the questions is an exotic one.
