### ISSUE TITLE
preventDefault not working for Chinese like input method

### ISSUE THREAD

**Issue by xinpingwang** [vuejs/vue#8962]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/xinping_wang/zrmjk6cx/](https://jsfiddle.net/xinping_wang/zrmjk6cx/)

### Steps to reproduce
1. change IME(Input Method) to Chinese
2. type any content and press space key

### What is expected?
> the preventDefault should prevent the input

### What is actually happening?
 > content input to the input box

<img width="646" alt="screen shot 2018-10-17 at 5 03 56 pm" src="https://user-images.githubusercontent.com/41824968/47075232-b877fd00-d22e-11e8-96f3-465f94be7774.png">

**Comment by Justineo** [comment]
https://jsfiddle.net/Justineo/bnfa9edo/

It is just the native behavior and has nothing to do with Vue.
