### ISSUE TITLE
Scoped styles do not generate random scss number

### ISSUE THREAD

**Issue by llojkue** [vuejs/vue#8968]
### Version
2.5.17

### Reproduction link
[sandbox](https://codesandbox.io/s/5277yrwrzx)

### Steps to reproduce
Create a sass list of colors like: 
```
$colors: #FF3C11, #167FD9, #B595CE, #92CBB1, #F472CD, #ED1359,
  #07DEC4, #B0775A, #94B2E0, #E0D268, #BABABA, #DCDCDC;

```

Next, you want to randomly pick one color to use. For example:

```
.element {
  background: nth($colors, random(12))
}
```

Remember that these code is contained inside a component. So this component is reused many times in a for loop.

### What is expected?
The component even if reused should have different background color since you are using sass random().

### What is actually happening?
It seems that the component style is rendered only once and the random() function always pick up the same color.

**Comment by Justineo** [comment]
You are rendering the same component for multiple times so all component instance share the same style. You should apply different styles to instances yourself.
