### ISSUE TITLE
Typescript definition for FunctionalComponentOptions.render() does not allow to return undefined or VNode[]

### ISSUE THREAD

**Issue by destructive-dragon** [vuejs/vue#8971]
### Version
2.5.17

### Reproduction link
[https://github.com/destructive-dragon/vue-bug/blob/master/src/main.ts#L15](https://github.com/destructive-dragon/vue-bug/blob/master/src/main.ts#L15)

### Steps to reproduce
Try to return multiple VNode's or undefined from the render function of a functional component while using typescript.

It works, but it requires you to wrap it in `return xxx as unknown as VNode`. The Typescript definition should probably be updated to allow `VNode[]` and `null` or `undefined` as return value in a render function.

### What is expected?
Code should compile without needing to wrap it in `return xxx as unknown as VNode`

### What is actually happening?
Typescript error because the typescript definition for `render` does not allow `VNode[]` or `undefined` as a return value.

---
Likely not a priority because of the Vue 3.0 Typescript rewrite, but it should be very easy to fix by just extending the `FunctionalComponentOptions.render` function's typescript definition with the return values of `VNode | VNode[] | undefined`

**Comment by sqal** [comment]
https://github.com/vuejs/vue/pull/8192
