### ISSUE TITLE
Both move and leave triggered for removed transition-group item if transition-group has display: flex

### ISSUE THREAD

**Issue by dweerd** [vuejs/vue#8973]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/pcb17vq4/](https://jsfiddle.net/pcb17vq4/)

### Steps to reproduce
See Fiddle.

### What is expected?
Only a 'leave' is triggered when removing any item from the list displayed with display: flex.

### What is actually happening?
Both a 'leave' and a 'move' are triggered

**Comment by ericp3reira** [comment]
May I take this one?

**Comment by posva** [comment]
Go ahead!

**Comment by ericp3reira** [comment]
Great! Tonight I'm working on it.

**Comment by jkzing** [comment]
This should not be a bug, It's just the difference between `display: inline-block` + `position: absolute` and `display: flex` + `position: absolute`.

In your fiddle there is,
```css
.list-complete-leave-active {
  transition: all 1s;
  position: absolute;
}
```
Which sets the element to `position: absolute` when animating.

See the difference when `position: absolute` is added on element '4':

![image](https://user-images.githubusercontent.com/2851517/48049381-744a9d80-e1d9-11e8-9689-1bffaf04ec08.png)

Try it in this fiddle: [https://jsfiddle.net/pcb17vq4/1/](https://jsfiddle.net/pcb17vq4/1/)

**Comment by Justineo** [comment]
See @jkzing's fiddle above. Just remove `position: absolute` during transition and it will be working as expected.

**Comment by ericp3reira** [comment]
Thanks, @jkzing! I found out that, but was trying to find a workaround.

**Comment by dweerd** [comment]
Thanks for your efforts!
