### ISSUE TITLE
Unit tests within single file component

### ISSUE THREAD

**Issue by eiva** [vuejs/vue#8975]
### What problem does this feature solve?
I was so excited by single file components - it allows to see all related to a component in one place, almost all...
So I got a naive question about adding more to this file:

What do you think if single file component has the tag "tests", and js code inside used to perform unit tests for this particular component?

### What does the proposed API look like?

Something like this:
```
<template>
</template>
<script>
</script>
<tests>
import { mount } from '@vue/test-utils'
describe('Some name', () => {
  const wrapper = mount() // import default componet

  it('renders the correct markup', () => {
    expect(wrapper.html())....
  })
})
</tests>
```
What do you think about such proposal?

**Comment by Justineo** [comment]
You can already implement workflow for any custom block, including [custom blocks](https://vue-loader.vuejs.org/spec.html#custom-blocks).
