### ISSUE TITLE
vue组件中如何给div绑定keydown等键盘事件

### ISSUE THREAD

**Issue by sdlddr** [vuejs/vue#8980]
### What problem does this feature solve?
我需要给一个DIV绑定keydown事件，可是我在组件中对该DIV加了tabindex="0"属性后，依然无法成功使用addEventListener方法或者div.onkeydown=function(){……}的方式成功绑定。这是不是VUE的一个BUG？
如果是纯JS原生环境下，对DIV加入tabindex="0"属性，是可以绑定键盘事件的。

### What does the proposed API look like?
能在VUE下成功的对DIV,SPAN等元素绑定键盘事件。

**Comment by Justineo** [comment]
[`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) 了解一下。

**Comment by Justineo** [comment]
Please DO provide a valid reproduction.

BTW. You may want to use `v-on` to bind event listeners.

**Comment by sdlddr** [comment]
已经使用过v-on:keydown，还有v-on:keydown.native，但是仍然没有任何效果。

**Comment by sdlddr** [comment]
@Justineo 已经使用过v-on:keydown，还有v-on:keydown.native，但是仍然没有任何效果。

**Comment by angelina999990** [comment]
This is a working example. Hope that is what you want.
https://jsfiddle.net/angelina999990/06m97v3r/1/
