### ISSUE TITLE
vue组件中如何给div绑定keydown等键盘事件

### ISSUE THREAD

**Issue by sdlddr** [vuejs/vue#8981]
### What problem does this feature solve?
我需要给一个DIV绑定keydown事件，可是我在组件中对该DIV加了tabindex="0"属性后，依然无法成功使用addEventListener方法或者div.onkeydown=function(){……}的方式成功绑定。这是不是VUE的一个BUG？
如果是纯JS原生环境下，对DIV加入tabindex="0"属性，是可以绑定键盘事件的。
例子：
<template>
    <div style="width:100px;height:100px;background:#000" @keydown="renderKeydown($event)"></div>
</template>
……
renderKeydown(e){
    console.log('e.keyCode', e.keyCode);
},
////结果连'e.keyCode'字样都没有输出。
### What does the proposed API look like?
能在VUE下成功的对DIV,SPAN等元素绑定键盘事件。

**Comment by Justineo** [comment]
请不要开重复的 issue。

在 Vue 中可以正常绑定键盘事件，这个 feature request 不成立。如果要提交 bug 报告，请提供**可以在线运行的复现代码**（JSFiddle/JSbin/CodePen/CodeSandbox 等均可）。

**Comment by sdlddr** [comment]
请仔细看我说的，是在DIV上，而不是在input上，DIV在加了tabindex后仍然无法响应onkeydown事件。

**Comment by sodatea** [comment]
**请提供可以在线运行的复现代码**

**Comment by sdlddr** [comment]
@Justineo @sodatea https://jsfiddle.net/foolegg/2z0dm6wq/

**Comment by Justineo** [comment]
@sdlddr 你没有写 `tabindex`……

**Comment by sdlddr** [comment]
@Justineo   tabindex我刚才加上去了，仍然不响应啊

**Comment by sdlddr** [comment]
已经OK了，谢谢，原来tabindex要最后定义，而且我这里的JSFiddle有部分JS被墙了
