### ISSUE TITLE
关于页面回退、页面缓存、调用栈相关问题

### ISSUE THREAD

**Issue by jeely95** [vuejs/vue#8982]
### What problem does this feature solve?
背景：从列表页跳转到详情页，详情页返回时需要保留列表页原来的状态（页面不重载），这个需求困扰了我许久。

方案：目前 vue 官方提供了 keep-alive 和父子路由来实现，但实际项目中这两种方案并不太理想。
1. keep-alive 当缓存大列表或多页数据页面时，卡顿特别严重。
2. 父子路由的方式如果页面嵌套层级深时，同时有一些子页面是需要被多处复用的，导致很不好处理。
3. 若使用开启新页面的方式，就违背了SPA应用的初衷。

愿景：希望 vue/vue-router 能够像原生应用或小程序一样，支持页面调用栈

### What does the proposed API look like?
路由A 调用 router.push('B') 
调用栈 [A, B]，打开B时A不销毁，回退到A时只调用A前台显示相关钩子，不重载页面。
 
router.redirect('B')
...

**Comment by posva** [comment]
This is related to vue-router and there are already issues opened about the matter to provide better support to Nativescript

**Comment by jeely95** [comment]
Vue router don't consider support?
