### ISSUE TITLE
Display a page after all async call API are done and all dom is load

### ISSUE THREAD

**Issue by alex83130** [vuejs/vue#8984]
### What problem does this feature solve?
In website program in Vuejs, I would like display my page (with a transition) but only after that all API call (Axios and VueX) are done and all DOM (including images) is load.

### What does the proposed API look like?
I have already tested the mounted method with the nexttick inside but the render is'nt done fully at the end..

I look this post : https://stackoverflow.com/questions/46023920/cannot-find-a-way-to-wait-for-vue-js-async-function. But it is'nt resolve my problem, I need a way to know when all call API are finish and also all DOM is load (with images). And only after all is charged, I fade in my total page.

I create a CodeSandbox to illustrate this : https://codesandbox.io/s/m7vzy7134y

Actualy you see that the mounted appear before the finish of my simulate async API call..

Maybe you have a idea to resolve my problem ? Thanks in advance

**Comment by posva** [comment]
Please use the forum or discord chat to ask questions
