### ISSUE TITLE
Triggering object change with vue set does not work in laravel echo

### ISSUE THREAD

**Issue by sorasanin** [vuejs/vue#8985]
### Version
2.5.17

### Steps to reproduce
When I use vue ```this.set(obj, prop, val);``` inside laravel echo listen to change object, object do change by viewing directly with vue tools chrome extension but it does not trigger the change, I also tried using ```watch``` to alert on change but nothing happens and this is just inside laravel echo listen. When I do it from other method it triggers change on the page.

### What is expected?
Its expected to trigger change on the page.

### What is actually happening?
It is updating the object but not triggering the change on the page.

**Comment by sorasanin** [comment]
I came up with probably most stupidest solution, I added new array that also updated with useless data when object updates and I added v-for for that array next to v-for for object array and then changing array trigger change for object as well...........................................................................................................................................................

**Comment by posva** [comment]
When reporting a bug we require a minimal reproduction (no laravel either) but this is still at a question state so please use the forum or chat :)
