### ISSUE TITLE
Vue tries to load "img" :src for a hidden component (v-show="false")

### ISSUE THREAD

**Issue by Softknobs** [vuejs/vue#8986]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/v6fkz52y/](http://jsfiddle.net/v6fkz52y/)

### Steps to reproduce
1) Open provided jsfiddle in Chrome or IE (Firefox does not report the error)
2) Open developper tools (Ctrl-Shift-I on windows)
3) In developper tools select Console tab and click Clear console
4) Click "Run" in jsfiddle.net website

### What is expected?
The hidden image should not be loaded by Vue (v-show condition 1==2 on parent component)

### What is actually happening?
A 404 error appears for the image that is not supposed to be displayed at all (v-show condition is 1==2)

---
- Same behaviour if v-show is on the "img" tag

**Comment by LinusBorg** [comment]
v-show only adds a `style="display: false"`. Images load for hidden elements, that's how your browser works.

So this is expected behaviour.

If you don't want the image to load, don't just hide the component with `v-show`, don't render it by using `v-if`
