### ISSUE TITLE
Target component tag names with CSS selectors in single file components

### ISSUE THREAD

**Issue by RizziFrank** [vuejs/vue#8987]
### What problem does this feature solve?
When adding child components, the tag name that the component is mapped to is not available as a selector. This is understandable, since it's not actually in the output HTML. For example:
```
<template>
  <child-component></child-component>
  <child-component></child-component>
</template>
<style scoped>
child-component {
  border: 1px solid red;
}
</style>
```

### What does the proposed API look like?
My suggestion would be to replace the name in the CSS with the a "data-v-132fd456" type attribute:
Add a new one of them to the root element of all the matching components (in addition to what would already be there):
```
<div data-v-132fd456></div>
<div data-v-132fd456></div>
```
And the CSS:
```
[data-v-132fd456] {
  border: 1px solid red;
}
```
I didn't see a previous request for this, but I did see a stackoverflow post: https://stackoverflow.com/questions/48287567/vue-what-is-the-cleanest-way-to-select-a-component-via-css

**Comment by posva** [comment]
use a CSS class, that's what they are made for
