### ISSUE TITLE
Vue develop test failed in dev branch

### ISSUE THREAD

**Issue by ruojianll** [vuejs/vue#8992]
### Version
Latest dev branch
### Steps to reproduce
1.Fork vue repo.
2.Clone forked repo to local.
3.Run `sudo npm install`
4.Run `npm run test`

### What is expected?
All tests passed.

### What is actually happening?
test transition out-in on async component (resolve after leave complete) failed

**Comment by yyx990803** [comment]
The tests are passing on both CI and my local dev machine. This is likely a problem with your specific environment.
