### ISSUE TITLE
functional component can't get yourself direct DOM parent in rendered context 

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#8994]
### What problem does this feature solve?
i have chains of functional components in DOM.
and components can't knows where their placement in DOM. and i can't get direct parent element.

```context.parent.$el``` or ```context.parent.$vnode.elm``` - returns not direct nearest parent element

### What does the proposed API look like?
```
<functional-1 child-class="its-must-be-in-all-childs-as-class">
  <functional-2/>
  <functional-2/>
</functional-1>

export functional2 {
  render (h, context) {
    let parentClass = context.parentElm.getAttribute('child-class')
    if (parentClass) {
      context.data.class = (context.data.class || []).push(parentClass)
    }
    return h('div', context.data)
  }
}
```

**Comment by posva** [comment]
This is because functional component do not have instances. You can access the dom element through dom api though
