### ISSUE TITLE
Event Handling: keyboard events listener not works as expected

### ISSUE THREAD

**Issue by igorbuts** [vuejs/vue#8997]
### Version
2.5.7
2.5.17

### Reproduction link
[https://jsfiddle.net/igorbuts/50wL7mdz/772895/](https://jsfiddle.net/igorbuts/50wL7mdz/772895/)

### Steps to reproduce
- Open jsfiddle
- click arrowLeft or arrowRight

### What is expected?
The counter should decrease/increase.

### What is actually happening?
Counter stays the same.

---
Then if I click on any of these 2 buttons (one of them stays `:active`) and press arrows everything is OK and both event handlers work. But after I click somewhere else, event handlers don't work again.

Tried to attach these `keyup` listeners to other places of the template - didn't help.
Tried to use other keys - e.g - `arrowUp`, `arrowDown` - same bug.
Tried to use another event - e.g `keyDown` - same bug.

Does somebody know why is this working this way?

**Comment by Justineo** [comment]
It's how keyboard events work. Keyboard events only works on focusable elements and only when they contain current focused element. `<div>`s are not focusable by default. See [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex).
