### ISSUE TITLE
ES6 Arrow Functions where appropriate

### ISSUE THREAD

**Issue by rickhallett** [vuejs/vue#8998]
### What problem does this feature solve?
Moving Vue.js towards the incremental progress of JavaScript. Very open to feedback if this is a worthwhile improvement; I suppose I am primarily thinking along the lines of people who choose to read Vue source code. I think the deliberate use of arrow functions can *sometimes* make intentions/limitation with the 'this' keyword more explicit on a case by case basic. Thank you for your time in advance, and thank you for making such an excellent framework!

### What does the proposed API look like?
No breaking changes, but changing the vue core library to use arrow functions where 'this' is appropriate.

**Comment by posva** [comment]
Thanks for your concern! Yes, we try to use fat arrows when they improve upon readability. If you find places where readability could be improved by using a fat arrow, feel free to submit a pr 😄
