### ISSUE TITLE
A non-redundant way of importing component.

### ISSUE THREAD

**Issue by tanin47** [vuejs/vue#9001]
### What problem does this feature solve?
Currently, importing a component is somewhat verbose.

We can do: 

```
import SomeComponent from '../common/some-component.vue';
Vue.component('some-component', SomeComponent);
```

or

```
Vue.component('some-component', require('../common/some-component.vue').default);
```

There is redundancy in both ways. There is a shorter API that would reduce a lot of lines in my codebase.

See more dicussion here: https://forum.vuejs.org/t/how-can-i-make-the-component-importing-statement-shorter

### What does the proposed API look like?
Vue.component('../common/some-component.vue')

This might need a modification within vue-loader to support this special statement.

**Comment by posva** [comment]
This is a subjective matter as some people prefer to be explicit. That being said, it's something that could be handled in a custom webpack loader. Feel free to post the loader here if you write it :)
