### ISSUE TITLE
Can't use arguments with native event handlers

### ISSUE THREAD

**Issue by shrinisudi** [vuejs/vue#9005]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/91774v4l7o](https://codesandbox.io/s/91774v4l7o)

### Steps to reproduce
1. Open sandbox
2. Watch the browser as the page navigated to '/about' without any action
3. hit the back button and observe the console which gives the error `Invalid handler for event "click": got undefined`

### What is expected?
Wait until the user interacts and clicks the button to navigate to 'about' page

### What is actually happening?
The user is navigated without any action. If the user forces to go back tot he previous page the console error is thrown

---
Discovered this bug when creating navigation bar and wanted the logo to be a link to the home page using vue-router programmatic navigation. One solution that works is wrapping the event handler in a function as one of the following:
1. `<button onClick={() => this.$router.push("/about")}>Go to about page</button>` or  
2. `<button onClick={this.navigate}>Go to about page</button>` and in methods have a function that does the navigation.

I can't understand why 1. works and 2. is not ideal since we need one method for each link.

Abstracting 2. also produces the same error as the original sandbox. i.e  
`<button onClick={this.navigate("/about")}>Go to about page</button>` and in methods have:  
function (page) {
  this.$router.push(page)
}

**Comment by Justineo** [comment]
`onClick` should accept a function. You are calling `this.$router.push` directly inside a render function which will make your app redirect to `/about` every time `Home` is rendered.
