### ISSUE TITLE
Compiler like Svelte.js or Stencil.js

### ISSUE THREAD

**Issue by SamuelEarl** [vuejs/vue#9011]
### What problem does this feature solve?
I am not a framework expert, but supposedly using a compiler removes the app framework so the final app is lighter and faster, which is especially great for mobile users. Also, Stencil.js claims that their "framework" produces "standards-based Web Components" and that if you make components with their "framework", then those components will be compatible with any other framework. Apparently using a compiler also allows you to add any feature to your framework without adding extra bloat to the framework. I like Vue's design ideas more than either Svelte or Stencil and I think using a compiler would be really awesome for Vue! 

These might be some helpfult links to find out more: 
* https://svelte.technology/
* https://sapper.svelte.technology/
* https://www.infoworld.com/article/3146966/javascript/slim-speedy-svelte-framework-puts-javascript-on-a-diet.html
* https://stenciljs.com/.

### What does the proposed API look like?
I don't have any API proposals. I would love to help out on a project like this, but I wouldn't even know where to begin. If there is some way I can contribute, then please let me know.

**Comment by LinusBorg** [comment]
We're closely watching the exciting work that's happening in that area, talking with the people that work in these ideas and will see what we can draw as inspiration for Vue.

However, considering what we are currently planning for Vue 3, I don't think "compiling away" the Vue core is something we see as feasable or desirable at this point.

**Comment by SamuelTremain** [comment]
Sounds good. Do you have a link to a roadmap that discusses what is being considered for Vue 3? I would be interested in seeing some of the plans.

Thank you, @LinusBorg.

**Comment by yyx990803** [comment]
There are two aspects of this:

1. Compiling to standard web components: [this is already possible via Vue CLI](https://cli.vuejs.org/guide/build-targets.html#web-component), with the caveat of requiring the Vue runtime to be present on the page.

2. Using the compiler to only include features on demand in the final bundle. It is important to note that neither Svelte nor Stencil is completely "zero runtime": the more features you use, the more runtime support code you will end up including in your final bundle. This is a tradeoff between the baseline size (size of bundle when using only the minimum features) vs. size at scale (the size when you build an actual app, using most of the features and many components). Svelte optimizes for baseline size, which makes it nice for distributing small standard web components, but in exchange for a small baseline, it produces more verbose code for each component, so it doesn't necessarily have the same size advantage in large apps. Stencil has a slightly larger baseline size (it actually includes a vdom runtime) but results in a more efficient component/size ratio. Vue 3 in fact has a similar design where the baseline is controlled at around ~10kb, with optional features analyzed at compile time, imported on demand, and tree-shakable.
