### ISSUE TITLE
你好，请问template和jsx能不能混写在一个template里

### ISSUE THREAD

**Issue by 1316346949** [vuejs/vue#9014]
### What problem does this feature solve?
你好，请问template和jsx能不能混写在一个template里 v-jsx-xxx 的标签 代表了是jsx组件，这样在data或methods里定义一个方法，return一个jsx写法的标签模块，那么也会被填充到template里渲染成组件

### What does the proposed API look like?
<v-jsx />

**Comment by Justineo** [comment]
1. Mixing two syntax in one template causes chaos and I think we won't put efforts into this.
2. Feature requests require a proposed API.
