### ISSUE TITLE
child component property is not fully reactive

### ISSUE THREAD

**Issue by musicformellons** [vuejs/vue#9022]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/k0qv2vkjyo](https://codesandbox.io/s/k0qv2vkjyo)

### Steps to reproduce
Click 'ADD' and select an image file from your local machine. After selection a thumbnail (the `file.__img` property) should appear, but it doesn't. The same issue does not arise when not using a child component, see this codesandbox: https://codesandbox.io/s/jn0nj215zv

### What is expected?
The `file` property should exist in the child component at mount. 

### What is actually happening?
`file.__img` does not exist somehow.

---
For more details, you could check this stackoverflow question: https://stackoverflow.com/questions/53125604/vue-child-component-property-does-not-work (the codesandboxes there are same but with vue version 2.4.2).

**Comment by LinusBorg** [comment]
Can you reduce the boilerplate in that reproduction, i.e. drop all of the quasar dependencies etc? Or at least make it clear in the code which parts you have a problem with?

It's quite difficult to find the part that you actually mean in all of that surrounding code...

**Comment by musicformellons** [comment]
I added comments with !!! in front to make it more [clear here.](https://codesandbox.io/s/00j034vnkp)

**Comment by metalsadman** [comment]
@musicformellons 
I answered you in quasar forums https://forum.quasar-framework.org/topic/2892/why-does-child-property-not-work . https://codesandbox.io/s/n0xozovrql

**Comment by musicformellons** [comment]
@metalsadman Thanks, I found your answer. Your codesandbox added the mount in the child and shows that indeed `file` does mount at initial render of child, but from there on it is not reactive (i.e. `file.__img` does not come through) and the picture does not show like in the 'one component' solution.

**Comment by musicformellons** [comment]
BTW When in the parent I 'reassign' into reactive props for the child:
```
      <my-uploader-progress
        v-for="file in files"
        :file="file"
        :thumbnail="files.__img"
        :progress="file.__progress"
        :failed="files.__failed"
        :done-uploading="file.__doneUploading"
        :key="file.name"
        :hide-upload-progress="hideUploadProgress"
      >
      </my-uploader-progress>
```
and then in the child component use `thumbnail` instead of `file.__img` etc., things work 'as expected'. I just can not see why that is needed.

**Comment by posva** [comment]
Closing until a boiled down repro (no other frameworks) is provided
