### ISSUE TITLE
Multiple type prop and null

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue#9023]
### Version
2.5.17

### Reproduction link
[https://codepen.io/atilkan/pen/VVwGBb?editors=1111](https://codepen.io/atilkan/pen/VVwGBb?editors=1111)

### Steps to reproduce
On docs it says:
// Basic type check (`null` matches any type)
but if i use multiple type prop like propB: [String, Number] 
it throws error:
Expected Number, String, got Null.

### What is expected?
Accept the null value.

**Comment by afontcu** [comment]
Hi! 👋

I'm having a hard time trying to reproduce the issue (no errors in console). In this codesandbox everything is working as expected:

https://codesandbox.io/s/k9lkww2por

(meaning that I set the `propA` to be null while specifying `[Number, String]`, and no error was thrown).

It will throw an expected error if I add `required: true` to the prop definition. But again, that's what I'd expect.


Did that help?

**Comment by atilkan** [comment]
Hi, i also could not reproduce the error. Error disappeared after restarting serving. I reported with a hope if i miss something. I will check again and write it occurs. Thank you.
