### ISSUE TITLE
Hiding/Unhidding jQuery DataTables breaks column widths

### ISSUE THREAD

**Issue by RotateAt60MPH** [vuejs/vue#9024]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/cardinal177/m7bzjsag/3/](http://jsfiddle.net/cardinal177/m7bzjsag/3/)

### Steps to reproduce
Create a page with multiple jQuery DataTables that are hidden/shown via v-show to a vue data variable.  The initially 'shown' datatable looks fine.  When you switch to the second table, showing it, the column formats are all wrong.  If you change back to the originally working table, it's column widths are broken as well.  <table>.columns.adjust().draw() does not appear to fix this.

I know jQuery plugins are dicey, at best, but all of the DataTables work in done post-rendering of the page.  Don't know why vue.js would prevent this from working.

### What is expected?
The table column widths should be preserved.

### What is actually happening?
Columns widths on an unhidden table has widths all = 0px;

**Comment by Justineo** [comment]
You should try to force a layout recalculation of the plugin (something like `.adjust().draw()` as you mentioned only when the container is attached to DOM. You may want to put this in `this.$nextTick()`.
