### ISSUE TITLE
Keyboard event with modifiers and with alert in event handler will fire twice when user is using IME under IE

### ISSUE THREAD

**Issue by toBeTheLight** [vuejs/vue#9025]
### Version
2.5.14

### Reproduction link
[https://github.com/toBeTheLight/issue-20181104](https://github.com/toBeTheLight/issue-20181104)

### Steps to reproduce
1. Use IME
2. Type some letters
3. Press enter of the keyboard

### What is expected?
Event handler run only once, so alert window only show once

### What is actually happening?
Event handler run twice, so alert window show twice

---
In IE(9-11), after version of 2.5.14, keyboard event with modifiers and with alert (also window.open) in handler will fire twice when user is using IME.

I guess that interrupting javascript execution will cause this problem.

Maybe It is a system or browser bug, but i'm not sure.

![issue-2018-11-04](https://user-images.githubusercontent.com/23555178/47963571-f1a2d080-e068-11e8-852c-2467d1fa1365.gif)

**Comment by Justineo** [comment]
It's not caused by Vue. [This fiddle without Vue](http://jsfiddle.net/Justineo/s73jv9ae/embedded/result) shows the same result in IE11.
