### ISSUE TITLE
computed最终值没有改变的情况下组件重新渲染了

### ISSUE THREAD

**Issue by tmrcui** [vuejs/vue#9026]
### Version
2.5.17

### Reproduction link
[https://codepen.io/anon/pen/EOaXpd](https://codepen.io/anon/pen/EOaXpd)

### Steps to reproduce
1. 打开chrome dev tool
2. 点击页面的add按钮
3. 控制台会打印三个updated

### What is expected?
最终值没有改变的情况下组件不需要重新渲染

### What is actually happening?
最终值没有改变的情况下组件重新渲染了

---
2.5.17-beta已经没有这个问题了，什么时候会添加到正式版？

**Comment by Justineo** [comment]
Duplicate of #8540

**Comment by Justineo** [comment]
See also #7767 & #8751.
