### ISSUE TITLE
SVG Component not rendered in IE

### ISSUE THREAD

**Issue by janoszibrat** [vuejs/vue#9029]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/qer36jsy/](https://jsfiddle.net/qer36jsy/)

### Steps to reproduce
Open the minimal reproduction link in IE 11 or below.

### What is expected?
The component works in Chrome, Edge, ...but not in IE.

### What is actually happening?
Error in nextTick: "TypeError: Unable to set property 'overflow' of undefined or null reference".

**Comment by LinusBorg** [comment]
[IE doesn't support the `<ForeignObjet>` SVG element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject#Browser_compatibility), so I don't see how Vue could do anything about that.
