### ISSUE TITLE
slot with slot-scope cannot be accessed via $slots

### ISSUE THREAD

**Issue by Yuyz0112** [vuejs/vue#9030]
### Version
2.5.17

### Steps to reproduce
Create a component with slot
```
<template>
  <div>
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'TestComponent',
  created () {
    console.log(this.$slots.default)
  }
}
</script>
```

Use it with two slot components, one has `slot-scope` attribute and the other one do not
```
<template>
  <test-component>
    <p slot-scope="props">1</p>
    <p>2</p>
  </test-component>
</template>
```

Then will found `this.$slots.default` can only access the second VNode.

And if we removed `slot-scope` attribute from the first <p> element, both of them shows in `this.$slots.default`.

### What is expected?
I'm not sure whether this is the limitation of `slot-scope` and is there any other methods to get slot VNode with `slot-scope`?

### What is actually happening?
cannot access slot with `slot-scope`

**Comment by Justineo** [comment]
Scoped slots are exposed via `this.$scopedSlots`.

**Comment by Yuyz0112** [comment]
@Justineo 
Yes I see the `this.$scopedSlots`.

But it looks like I should access the scoped slot by passing all the scoped props?
```
this.$scopedSlots.default(props)
```

**Comment by Yuyz0112** [comment]
Okay, I found I can also passed an empty object as props Since I'm not going to render the VNode.

Is this the decent way?

**Comment by Justineo** [comment]
Can you describe your actual use case?

**Comment by Yuyz0112** [comment]
I passed a `loadFn` as props from parent to slot, after `loadFn` was called, the parent component will do some async tasks.
After the tasks were done, I would like it to trigger slot component's `load` event so I can handle the result in `@load`.

```
parent
  child slot-scope="{ loadFn }" @click="loadFn()" @load="doSomeThing()"
```

So I would like to get slot VNode when tasks were done in the parent component.

**Comment by Justineo** [comment]
You can just provide a callback function to `loadFn` in current context. There's no need to touch the child component itself.

```html
<v-parent>
  <v-child slot-scope="{ loadFn }" @click="loadFn(doSomething)"/>
</v-parent>
```

**Comment by Yuyz0112** [comment]
Yes, this is a good alternative I have already try, just trying to provide some more straightforward API.

Thanks a lot.
