### ISSUE TITLE
Allow mixed props array

### ISSUE THREAD

**Issue by p1pchenk0** [vuejs/vue#9033]
### What problem does this feature solve?
Let's say, developer has a component, which already has 5 props defined as an array of strings and it is totally fine for developer and his/her team to leave it as it is.

But then, one day, a new prop should be added with type and default value defined. Currently developer has to rewrite existing array of 5 props into object just for adding 1 new prop with default value.

What I would like to propose is using mixed array of strings and object for detailed props. I've already tested code below and it works just fine.

### What does the proposed API look like?
in vuejs repo there is a file *vue/src/core/util/options.js* with _normalizeProps_ function, which has to be slightly modified

```javascript
function normalizeProps (options: Object, vm: ?Component) {
  const props = options.props

  if (!props) return
  
  const res = {}
  let i, val, name
  
  if (Array.isArray(props)) {
    i = props.length
    
    while (i--) {
      val = props[i]
      
      if (typeof val === 'string') {
        name = camelize(val)
        res[name] = { type: null }
      } else if (isPlainObject(val)) {
        // this is new piece of code
        for (var key in val) {
            let objVal = val[key];
            name = camelize(key);
            res[name] = isPlainObject(objVal) ?
              objVal : {
                type: objVal
              };
          }
      } else if (process.env.NODE_ENV !== 'production') {
        warn('props must be strings when using array syntax.')
      }
    }
  } else if (isPlainObject(props)) {
    for (const key in props) {
      val = props[key]
      name = camelize(key)
      res[name] = isPlainObject(val)
        ? val
        : { type: val }
    }
  } else if (process.env.NODE_ENV !== 'production') {
    warn(
      `Invalid value for option "props": expected an Array or an Object, `  
      `but got ${toRawType(props)}.`,
      vm
    )
  }
  
  options.props = res
}
```

And now we can use this syntax:
```javascript
    export default {
        name: 'ChildComponent',
        props: [
            'first-property',
            'second-property',
            'third-property',
            {
                forth: { type: String, default: 'I am forth prop!' },
                fifth: { type: String, default: 'I am fifth prop!' } 
            }
        ]
    }
```

**Comment by p1pchenk0** [comment]
I would gladly create a plugin for that, but don't think it is possible to redeclare "private" Vue function

**Comment by posva** [comment]
This can be achieved with a global mixin that rewrites the props property in a `beforeCreate` hook. Since we are in API freeze and this is really uncommon and not recommended (object syntax is better), let's keep this in userland

**Comment by p1pchenk0** [comment]
This is achievable via plugin: https://www.npmjs.com/package/vue-mixed-props
