### ISSUE TITLE
Item added at the wrong position in a transition group

### ISSUE THREAD

**Issue by dweerd** [vuejs/vue#9035]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/o2vhqecg/1/](https://jsfiddle.net/o2vhqecg/1/)

### Steps to reproduce
Click the button in the JSFiddle

### What is expected?
The new item (199) is added to the left of the middle item (200), since the list is sorted numerically.

### What is actually happening?
The new item (199) is added to the _right_ of the middle item (200).

**Comment by Justineo** [comment]
It's not a bug. After `this.items.splice`, `200` is no longer in the list so it has nothing to do with the numeric order (`sorted` has already become `[100, 199, 300]`). It's just about Vue's patching strategy.

**Comment by dweerd** [comment]
OK, I understand. But since there will temporarily be 4 items in the DOM, is there any way to influence the order between 199 and 200?

**Comment by Justineo** [comment]
Maybe you can apply extra styles during transition yourself, if the elements are fixed-width.
