### ISSUE TITLE
When using conditional v-model, getting error: "Cannot use 'in' operator to search for <propertyName> in null"

### ISSUE THREAD

**Issue by akhoury** [vuejs/vue#9036]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/bentael/qzkvmoeb/](https://jsfiddle.net/bentael/qzkvmoeb/)

### Steps to reproduce
* open the fiddle
* open your dev console
* check the checkbox on the form
* type anything in the "mailing zipcode" text field
* notice the error in the console

### What is expected?
no error

### What is actually happening?
Error in the console

>>> Cannot use 'in' operator to search for 'zipcode' in null 

---
Notice that I am using a conditional v-model expression, is that allowed? This https://stackoverflow.com/a/44437096/493756 says Yes it is.

If you look at the screenshot below, in the sources tab in the dev console, it looks like the compiled conditional javascript is not exactly right, for the first argument for `$set()` should always be `client` in my case, and never `client.mailingZipcode`

```
  $set(client.differentMailingZipcode ? client.mailingZipcode : client, "zipcode", $event.target.value)
```

![screen shot 2018-11-06 at 4 45 09 pm](https://user-images.githubusercontent.com/1398375/48097133-fab9ac00-e1e6-11e8-9f49-204e170134bc.png)

Thanks

**Comment by LinusBorg** [comment]
I've never done this and wouldn't say that this is officially supported - there's no official docs or code using this approach, at least.

What you can do instead is use a computed property with a setter: 

https://jsfiddle.net/swo05cf1/

**Comment by akhoury** [comment]
yea i've done this before, i was trying to be extra lazy this time. thanks @LinusBorg
