### ISSUE TITLE
Missing content passed to a dynamic list of slots

### ISSUE THREAD

**Issue by revolter** [vuejs/vue#9037]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Lytuc02x/4/](https://jsfiddle.net/Lytuc02x/4/)

### Steps to reproduce
N/A

### What is expected?
The `#line-1` and `#line-2` elements should contain the `First line` and respectively `Second line` texts.

### What is actually happening?
The mentioned elements are empty.

**Comment by AngCosmin** [comment]
Do this:

`<slot :name="'line-' + index"></slot>`

**Comment by Justineo** [comment]
As @AngCosmin said. You need to use the binding syntax here.

**Comment by revolter** [comment]
But shouldn't it throw the `Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead.` error like it does for the `id` attribute for example?

**Comment by Justineo** [comment]
Because we used to support interpolating attributes with `{{` and `}}` so if such syntax is detected inside an attribute, we can assume that the user might be migrating from v1 to v2. But we never supported JS expressions inside an attribute without any binding syntax so it's not gonna be warned.

**Comment by revolter** [comment]
You misunderstood me. In the example I linked in the first post, I had `name="line-{{ index }}"` instead of `:name="'line-' + index"`.

So what I was trying to say was that vue should throw the `Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead.` for code like `<slot name="line-{{ index }}"></slot>` too.

**Comment by Justineo** [comment]
I see. I think this could be enhanced.

**Comment by revolter** [comment]
Should I open a new issue to track this change or could we re-open and use this one?

**Comment by Justineo** [comment]
A new feature request would be fine. 😄
