### ISSUE TITLE
prop did't produce right value 

### ISSUE THREAD

**Issue by yangjunjun** [vuejs/vue#9041]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/yangjunjun/eywraw8t/450799/](https://jsfiddle.net/yangjunjun/eywraw8t/450799/)

### Steps to reproduce
see the demo, it's simple 

### What is expected?
the first prop 'val' should be  empty string 

### What is actually happening?
the first prop 'val' is true

---
when I  create a checkbox-like component which  has a props "value" who accept  Boolean String type.  when an empty string was  assign to the "value" but the actual value  is "true", it's  weird.

**Comment by Justineo** [comment]
As you declared the prop as type `[Boolean, String]`, Vue would try to figure out it can be treated as a boolean value first. And for boolean props, as long as it exists it's regarded as truthy.

```html
<!-- the following declarations are equivalent -->
<input disabled>
<input disabled="">
<input disabled="whatever">
```

You can declare the type as `[String, Boolean]` if you want to regard the value as string first.

**Comment by yangjunjun** [comment]
It doesn't make sense. the order of props type should not affect the result. Anyway the official docs didn't mention this.

**Comment by KaelWD** [comment]
See #7485 and the linked issues
