### ISSUE TITLE
vue extends 问题

### ISSUE THREAD

**Issue by guohuihot** [vuejs/vue#9043]
// parent
```
<template>
    <div>
        <template name="btn">添加</template>


        你还可以 <btn></btn>


        ...<btn></btn>
    </div>
</template>

<script>

export default {
}
</script>

```
child

```
<template>
    <div>
        调用 <btn></btn>

        有需要又调用一次 <btn></btn>
    </div>
</template>

<script>
import Parent from 'Parent'

export default {
    extends: Parent
}
</script>
```

vue有没有这样的方法，这样的话，在extend这个功能上，就可以把部分模板通用起来

**Comment by hzsrc** [comment]
我也碰到这样的需求，方案是有的，
子组件这样用即可

    render(h) {
        var superRendered = this.$options.extends.render.apply(this, arguments)
        if (this.uiSet) {
            var button = <el-button>确定</el-button>
        }
        return <div>{superRendered}{button}</div>
    }
superRendered就是父组件模板渲染的结果！this.$options.extends.render.apply(this, arguments) 这句是关键。
