### ISSUE TITLE
After upgrading my Vue 2.0 project (a typescript project that uses vue-class-component) to Vue 2.5 and updating all npm dependencies, I get the following error:

### ISSUE THREAD

**Issue by cuiD2488** [vuejs/vue#9045]
ERROR in /myproject/node_modules/vue-class-component/lib/declarations.d.ts

(6,33): error TS2702: 'Vue' only refers to a type, 
but is being used as a namespace here.

**Comment by posva** [comment]
Please, consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
