### ISSUE TITLE
"TypeError: Cannot convert a Symbol value to a string" when using a Proxy

### ISSUE THREAD

**Issue by winkying** [vuejs/vue#9048]
### Version
2.5.9

### Reproduction link
[https://codepen.io/winkying/pen/jQrNpz?editors=1011](https://codepen.io/winkying/pen/jQrNpz?editors=1011)

### Steps to reproduce
click the reproduction link and check the console panel

### What is expected?
get the correct value

### What is actually happening?
throw an error "Cannot convert a Symbol value to a string

**Comment by Justineo** [comment]
It has nothing to do with Vue. The second argument of [`handler.get()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/get#Parameters) is a string or `Symbol` so you cannot simple concat it with a string using `+`.

**Comment by winkying** [comment]
Thx very much ;)
btw, why `let ar = this.getKey(obj)' is fine, while `this.arr =  this.getKey(obj)` doesn't work;
could u pls detail the reason
