### ISSUE TITLE
Scoped styles doesn't work correctly with transition-group

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#9051]
### Version
2.5.17-beta.0

### Reproduction link
[https://codesandbox.io/s/1zqlm5m6m7](https://codesandbox.io/s/1zqlm5m6m7)

### Steps to reproduce
just check the link and you'll see

### What is expected?
It must transition when using scoped on style 

using scoped slots

### What is actually happening?
It doesn't transition on the slot based

**Comment by posva** [comment]
This is working as expected, elements passed via slots do not get affected by scoped css in the child (otherwise it would be problematic)
You can either make the animation non scoped or use the deep selector (`>>>` more about it in the vue-loader docs)
