### ISSUE TITLE
Component name css selector

### ISSUE THREAD

**Issue by blenderskool** [vuejs/vue#9052]
### What problem does this feature solve?
In single file components, the styles section can possibly **allow selectors with the same name as components used**. Right now, if we need to style the component, it must be assigned to some class that may not be used elsewhere. Along with CSS scoping, I see this as a powerful solution of writing styles for nested components.

### What does the proposed API look like?
This is what I am suggesting,
```html
<template>
  <my-component />
</template>

<style>
  my-component {
    background-color: red;
  }
</style>
```

I am not really sure how the loader would convert this to plain CSS using standard selectors. :thinking:

**Comment by posva** [comment]
let's not reinvent the wheel, use a CSS class

**Comment by CallumWatkins** [comment]
+1
As we can already use the element selector...

```html
<template>
  <p>Hello World</p>
</template>

<style>
  p {
    color: red;
  }
</style>
```

... why are we unable to do the same with components? Surely this seems like a logical extension of the standard. I wouldn't call it reinventing the wheel.

**Comment by Justineo** [comment]
It’s easy to implement with Vue Loader but the compiled code will mess with selector specificity and lead to unexpected cascading result. Unless you output the root element of the component with an custom element, which works fine with semantic-less elements like `<div>`, while replacing other elements like `<button>` will change the actual behavior, which is also unacceptable.

**Comment by codywakeford** [comment]
I have created my own custom component library doing this sort of thing. For example

`<template>
    <div ref="reference" class="cflex">
        <slot />
    </div>
</template>

<script setup>
const attrs = useAttrs()
const reference = ref(null)

onMounted(() => {
    if (reference.value) {
        Object.keys(attrs).forEach((key) => {
            reference.value.style.setProperty(key, attrs[key])
        })
    }
})
</script>

<style scoped lang="sass">
.cflex
    display: flex
    flex-direction: column
</style>
`

if you give the slot container a class name you can use that when creating the component. This one i can select using .cflex without needing to declare this where im creating the component instance. Making for clean and maintainable code. It also makes it rapid to develop some complex webpages once you have built out the component lib.
