### ISSUE TITLE
这就是你们说最好的框架吗？

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [vuejs/vue#9053]
![image](https://user-images.githubusercontent.com/11493796/48313880-0fd67680-e5fd-11e8-91d4-39d2acddd079.png)

![image](https://user-images.githubusercontent.com/11493796/48313886-1a910b80-e5fd-11e8-8339-01bd86318cbb.png)

好像没有 ng 的做得好吧

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/48314180-bd975480-e600-11e8-965d-e22960b71101.png)
![image](https://user-images.githubusercontent.com/1726061/48314189-cbe57080-e600-11e8-8b54-ea04507605ff.png)

亲爱的用户：

1. 如您所见：Vue 提示您在模板或渲染函数中使用了未定义的 `stateSideLeft`，而您定义的是 `stateSideLeftState`：

    ```diff
    @@ -1 +1 @@
    -stateSideLeft
    +stateSideLeftState
    ```

2. Vue 团队从未自称「最好的框架」，而这个问题不管 NG 还是别的框架也都无法自动帮您修复；
3. 建议以后不要贴截图，节省他人的时间才能节省自己的时间。

嘲讽之前最好还是先确保自己没有犯错误，不然真的会很没有面子。
