### ISSUE TITLE
Object values on option elements are stringified when using slots

### ISSUE THREAD

**Issue by peterfox** [vuejs/vue#9057]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/SlyFoxy12/eywraw8t/456496/](https://jsfiddle.net/SlyFoxy12/eywraw8t/456496/)

### Steps to reproduce
Create a component with a slot which has select options passed to it that use objects. The options need objects applied for values, although I believe it will stringify the value no matter what is passed through.

### What is expected?
Making a custom select element using a component with a select and a slot for the options should work with objects instead of providing the string value "[object Object]" on change.

### What is actually happening?
Options passed to the component via a slot appear to get converted to a string when passed through a slot.

---
Example JS Fiddle shows behaviour with a normal select control and a custom select control as described when the options are passed through to the select as a slot.

As you will see the select box behaves fine but the custom component always produces a "[object Object]" value.

**Comment by posva** [comment]
It's because you're emitting the value from the event instead of the value hold by `v-model`

```js
this.$emit('change', this.selectedThing)
```

**Comment by peterfox** [comment]
@posva confirmed working now, thank you
