### ISSUE TITLE
Iframes are reloaded when Vue app is mounted

### ISSUE THREAD

**Issue by pdufour** [vuejs/vue#9064]
### Version
2.5.17

### Reproduction link
[https://codepen.io/pdufour/pen/yQMLJX](https://codepen.io/pdufour/pen/yQMLJX)

### Steps to reproduce
Insert an iframe somewhere within your div that will be your Vue app
`<iframe width="1" height="1" style="position: absolute; left: -9999em" src="https://placekitten.com/204/204"></iframe>`

### What is expected?
The iframe URL should load once.

### What is actually happening?
It loads once normally and then another time once the Vue app loads. If you filter network requests for `204` you can see this in action.

![image](https://user-images.githubusercontent.com/1239145/48454089-cefc7000-e76a-11e8-8f12-783fa13b9153.png)

---
Images seem to act the expected way, the src of them does not load twice in the example given above.

**Comment by posva** [comment]
This is normal as Vue is parsing the template and replacing the content. Should be Ok with string templates or by wrapping it into a component

**Comment by pdufour** [comment]
In the config I set `Vue.config.ignoredElements = ['iframe'];` so shouldn't it not touch the iframe?

**Comment by qngl** [comment]
render the iframe after the component is mounted. 
`mounted() {
    this.url = this.value;
  }
`
`
<iframe v-if="url" :src="url"></iframe>`
