### ISSUE TITLE
this is undiefind ... 搞笑的东西

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [vuejs/vue#9067]
![image](https://user-images.githubusercontent.com/11493796/48471939-01bc6c00-e830-11e8-847d-9d0a2c8dcda9.png)

![image](https://user-images.githubusercontent.com/11493796/48471951-0bde6a80-e830-11e8-92a4-f59c1c4dcd46.png)
![image](https://user-images.githubusercontent.com/11493796/48471960-139e0f00-e830-11e8-8517-ba6c82950d60.png)

大哥 你们是不是换了 router 的写个啊！ 文档没更新啊 搞死人啊？？

**Comment by sodatea** [comment]
文档写得非常清楚：

> 不要在选项属性或回调上使用[箭头函数](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions)，比如 `created: () => console.log(this.a)` 或 `vm.$watch('a', newValue => this.myMethod())`。因为箭头函数是和父级上下文绑定在一起的，`this` 不会是如你所预期的 Vue 实例，经常导致 `Uncaught TypeError: Cannot read property of undefined` 或 `Uncaught TypeError: this.myMethod is not a function` 之类的错误。

https://cn.vuejs.org/v2/guide/instance.html#%E5%AE%9E%E4%BE%8B%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90

很显然你没有吸取[上次](https://github.com/vuejs/vue/issues/9053)的教训。

**Comment by xxj95719** [comment]
笑出声

**Comment by rainbowMorelhahahah** [comment]
> 文档写得非常清楚：
> 
> > 不要在选项属性或回调上使用[箭头函数](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions)，比如 `created: () => console.log(this.a)` 或 `vm.$watch('a', newValue => this.myMethod())`。因为箭头函数是和父级上下文绑定在一起的，`this` 不会是如你所预期的 Vue 实例，经常导致 `Uncaught TypeError: Cannot read property of undefined` 或 `Uncaught TypeError: this.myMethod is not a function` 之类的错误。
> 
> https://cn.vuejs.org/v2/guide/instance.html#%E5%AE%9E%E4%BE%8B%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90
> 
> 很显然你没有吸取[上次](https://github.com/vuejs/vue/issues/9053)的教训。

React 用户 转过来 我都写 () => 写习惯了

**Comment by rainbowMorelhahahah** [comment]
> 文档写得非常清楚：
> 
> > 不要在选项属性或回调上使用[箭头函数](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions)，比如 `created: () => console.log(this.a)` 或 `vm.$watch('a', newValue => this.myMethod())`。因为箭头函数是和父级上下文绑定在一起的，`this` 不会是如你所预期的 Vue 实例，经常导致 `Uncaught TypeError: Cannot read property of undefined` 或 `Uncaught TypeError: this.myMethod is not a function` 之类的错误。
> 
> https://cn.vuejs.org/v2/guide/instance.html#%E5%AE%9E%E4%BE%8B%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90
> 
> 很显然你没有吸取[上次](https://github.com/vuejs/vue/issues/9053)的教训。

![image](https://user-images.githubusercontent.com/11493796/48476030-eefa6500-e838-11e8-8562-a5d39bff7671.png)
hai'yo还有如果不支持 为什么 Layout 里面data => 的东西 都可以出来？？

**Comment by sm00thCr1m1n4l** [comment]
铁憨憨一个

**Comment by whxaxes** [comment]
@rainbowMorelhahahah  你可以在 data 里面也用一下 this ，你就发现也出不来了。。。建议可以先看看 [文档](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions) 学学什么是箭头函数，再来想这个问题

**Comment by Nothing-Works** [comment]
这种问题 明显是自己 操作的问题啊，好好看看文档吧先。

**Comment by yyx990803** [comment]
已 block，走好不送。
