### ISSUE TITLE
IE11, console print: [Vue warn]: Error in nextTick: "Error: Invalid argument."

### ISSUE THREAD

**Issue by soxunyi** [vuejs/vue#9068]
IE11, console print: [Vue warn]: Error in nextTick: "Error: Invalid argument." But work well with chrome

**Comment by WebMarketers1** [comment]
Any solution of this issue?

**Comment by hermanndettmann** [comment]
I ran into this issue too so any help around this would be awesome!

**Comment by posva** [comment]
if you have this bug, please open a new issue with a boiled down repro
