### ISSUE TITLE
Vue should warn on missing closing script tag (parser check)

### ISSUE THREAD

**Issue by geri777** [vuejs/vue#9073]
### What problem does this feature solve?
If you create a Vue component you put your script withing <script> and </script>. 
It happened to me that I forgot to close the script tag. Vue then simply ignores the whole script part and you get errors like "property or method is not defined ...".
Vue has a good parser error handler, so it would be great if the parser detected this problem as well. Thank you!

### What does the proposed API look like?
no api

**Comment by LinusBorg** [comment]
This should be re-opened in vue-loader's repository.
