### ISSUE TITLE
Vue v-model.number You can still type "e".

### ISSUE THREAD

**Issue by huzedong2015** [vuejs/vue#9076]
### Version
2.5.17

### Reproduction link
undefined

### Steps to reproduce
`<input v-model="test" type="number">`

### What is expected?
You can only enter numbers.

### What is actually happening?
Can enter “e”

**Comment by JounQin** [comment]
https://vuejs.org/v2/guide/forms.html#number

modifier `number` only helps you to `parseFloat` for you, it is just a `number` input, no magic inside.

**Comment by paritosh149** [comment]
If non-number is entered in type=number, the type of value returned will be string. Whereas, if a number is entered in type=number, the type of value returned will be number.
So, in your case if "e" is entered, the string will be returned in value. Check the type of value and set up next steps.
