### ISSUE TITLE
Strange behavior of regex

### ISSUE THREAD

**Issue by stepanzin** [vuejs/vue#9087]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/eywraw8t/466635/](https://jsfiddle.net/eywraw8t/466635/)

### Steps to reproduce
Start to enter a valid email and the flag `isValid` takes the wrong value on a valid expression. For example, if you specify a regular expression in its pure form, then unexpected behavior is not noticed.

### What is expected?
It is expected that to validate a field, it will be possible to import rules that lie outside an instance or function.

### What is actually happening?
It has the form of a sequence: "true", "false", "true", etc. Dependent on the length of the string, since the veracity of the expression.

**Comment by Justineo** [comment]
It's not related to Vue. `RegExp`s in JavaScript can be stateful.

![image](https://user-images.githubusercontent.com/1726061/48692553-67826c80-ec11-11e8-984a-238890ebe07b.png)

You can learn more on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Description):

> `test()` called multiple times on the same global regular expression instance will advance past the previous match.
