### ISSUE TITLE
A Recommendation for the File Bundle System

### ISSUE THREAD

**Issue by vigilantee-seek** [vuejs/vue#9088]
### What problem does this feature solve?
The current mainstream front-end development frames like Vue, React and webpack would bundle all the CSS and JS files into a single HTML file for a one-page application. This is a feasible and good implementation for reduction of TCP requests as for HTTP 1.x with the HTTP pipeline closed (pipeline for HTTP 1.x is not a good practice as well due to its head-of-line blocking). However, as HTTP/2 becomes available and popular, the large bundled file will be a bottleneck of your product. Therefore, for lower latency of TCP requests in the HTTP/2 scenario, I think a more utility building approach is on demand.

### What does the proposed API look like?
Sorry that I'm not a professional in front-end development (I major in Internet and front-end development is my hobby), thus I could only provide my assumption and suggestion. Here I propose two possibly practical means. 
First, instead of a bundled file, you could divide the file into several smaller files and set the HTTP head with a sequence number for each of them to guarantee the correct order since the transportation of files with HTTP/2 is actually an "out-of-order outcome" structure. Besides, a gzip compression method is also recommended to diminish your bundled file. This way has some shortcomings that the server will be requested to decompress (this is viable) and reorganize (I am not sure whether there is some workable way) the divided files.
Second, instead of bundling the files, why not have a try just letting the static resources be (of course compression is always necessary)? I think with HTTP/2 and HTTP pipeline now usable things may totally change that bundling itself will become a worse practice.

**Comment by Demivan** [comment]
Webpack already has `maxSize` option in `SplitChunksPlugin` to split chunks into smaller parts https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-maxsize. You can use other options of `SplitChunksPlugin` to controll how Webpack splits and merges chunks.
And you can use https://github.com/webpack-contrib/mini-css-extract-plugin to extract and split css into multiple files too.

**Comment by vigilantee-seek** [comment]
Wow, this is awesome! So maybe the future developers will focus their attention on much smaller parts of bundled chunks for higher performance. Thank you for your reply and then I will close the issue.
