### ISSUE TITLE
ie下template无法获取v-for的index

### ISSUE THREAD

**Issue by zarte** [vuejs/vue#9089]
### Version
2.5.16

### Reproduction link
[https://codepen.io/zarte-the-bold/pen/MzEqoJ](https://codepen.io/zarte-the-bold/pen/MzEqoJ)

### Steps to reproduce
如下代码
<li v-for="(item, index) in list">
      <template v-if="index==(list.length-1)">
         {{item}}{{list.length}}
      </template>
       <template  v-else>
         {{item}}111
      </template>
    </li>
ie中无法正常渲染

### What is expected?
.

### What is actually happening?
[Vue warn]: Error when rendering root instance: 
 “index”未定义

**Comment by posva** [comment]
It works fine on IE
