### ISSUE TITLE
Expose withMacroTask

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#9094]
### What problem does this feature solve?
If one wants to define custom event handlers (like one on `document`) which interact with Vue instances or Vue reactive state, one should wrap it with `withMacroTask` to assure that any changes to the reactive state and flushing of the queue happens in the macro task and not micro task. Otherwise it can be possible that Vue starts changing DOM as a consequence of the reactive change even before the event propagates along original DOM tree.

The problem is that `withMacroTask` cannot be accessed currently.

### What does the proposed API look like?
`withMacroTask` could simply be exposed in a way that it can be imported. Or maybe made available at `Vue.withMacroTask`.

**Comment by yyx990803** [comment]
We are reverting back to microtasks everywhere and will remove `withMacroTask` entirely in 2.6.
