### ISSUE TITLE
ie下v-for使用在tr上时template无法使用index

### ISSUE THREAD

**Issue by zarte** [vuejs/vue#9096]
### Version
2.5.17

### Reproduction link
[https://codepen.io/zarte-the-bold/pen/qQpYYV](https://codepen.io/zarte-the-bold/pen/qQpYYV)

### Steps to reproduce
ie上以下会报错，目前只发现table的tr这样写会出错。
~~~html
 <tr v-for="(item, index) in list">
                <template v-if="index == (list.length-1)">
                    <td>{{item.name}}{{index}}</td><td>*****1</td>
                </template>
                <template v-else>
                    <span>{{item.name}}{{index}}</span><td>==1</td>
                </template>

            </tr>
~~~

### What is expected?
根据index判断显示不同模板

### What is actually happening?
[Vue warn]: Error in render: "ReferenceError: “index”未定义"  
[object Error]{description: "“index”未定义", message: "“index”未定义", name: "ReferenceEr...", number: -2146823279, stack: "ReferenceEr..."}

**Comment by ysj16** [comment]
ie几啊

**Comment by zarte** [comment]
> ie几啊

11

**Comment by posva** [comment]
This is probably because of the `template` tag (or other) which is stripped off by the IE inside of tables. It works well with a string template
