### ISSUE TITLE
Space character in label not working

### ISSUE THREAD

**Issue by approached** [vuejs/vue#9103]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/onbzk0m6/](https://jsfiddle.net/onbzk0m6/)

### Steps to reproduce
Just load the vue instance. See link to reproduction.

### What is expected?
whitespace character
`Text: "     Drehmaschinen"`

### What is actually happening?
a string with `&nbsp;`
`Text: "&nbsp;&nbsp;&nbsp;Drehmaschinen"`

---
If you remove the vuejs code or change the 'el' attribute, it will work.

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue/issues/8895
