### ISSUE TITLE
Css in library

### ISSUE THREAD

**Issue by mateo2181** [vuejs/vue#9105]
### Version
2.5.17

### Reproduction link
[https://github.com/mateo2181/vue-swappable](https://github.com/mateo2181/vue-swappable)

### Steps to reproduce
I built a lib but the css included in the components is not loading. I see the css file in dist folder but I would like that the css is included in the component when I use it. This is the project: https://github.com/mateo2181/vue-swappable

### What is expected?
Css is included in library

### What is actually happening?
The css is not included in my library

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
