### ISSUE TITLE
'toLowerCase' of undefined

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [vuejs/vue#9108]
### Version
2.5.17

### Reproduction link
[https://github.com/carvalhoviniciusluiz/vue-bug-toLowerCase](https://github.com/carvalhoviniciusluiz/vue-bug-toLowerCase)

### Steps to reproduce
// in any project vue cli, main.js file
import Vue from 'vue'
import App from './App'
import bug from './index.js'

Vue.use(bug)

new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})

### What is expected?
the project must run

### What is actually happening?
the project does not open and an error is shown from the console

**Comment by posva** [comment]
There is too much in your repro, it could come from your code.
Please use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for this kind of questions and come back once you get a boiled down repro 🙂
