### ISSUE TITLE
New gold OpenCollective sponsor doesn't show up in README.md

### ISSUE THREAD

**Issue by gustojs** [vuejs/vue#9115]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/yect7ohk/](https://jsfiddle.net/yect7ohk/) <- actually on this link it works, it only doesn't work on actual repository README

### Steps to reproduce
1. Go to https://github.com/vuejs/vue
2. Scroll down to Gold OpenCollective Sponsors
4. Notice that there is no blue bird icon (Getform.io logo)
5. If you click on `Become a Sponsor` image, you get redirected to Getform.io website

### What is expected?
There should be a Getform.io logo between `CodeFirst` and `Become a Sponsor` in the Gold OpenCollective sponsors section.

### What is actually happening?
Instead of Getform logo, it's a `Become a Sponsor` button that redirects to Getform website.

---

I've been notified on chat.vuejs.org that the logo of the new gold sponsor from OpenCollective is missing from README.md. I don't see it either, but I checked the source code and it is there: 

```
<a href="https://opencollective.com/vuejs/tiers/gold-sponsors/2/website" target="_blank" rel="noopener noreferrer"><img src="https://opencollective.com/vuejs/tiers/gold-sponsors/2/avatar.svg" height="60px"></a>
```

When I copy the same exact code over to the test environment, the logo shows up properly:

https://jsfiddle.net/yect7ohk/

It may be some weird caching issue related to the fact that the code itself wasn't changed.

**Comment by gustojs** [comment]
It started to show up a moment ago. Only the `Become a Sponsor` button is missing now.

**Comment by yyx990803** [comment]
Seems to be all working now.
