### ISSUE TITLE
Documentation on how to deploy VueJS app to GitHub Pages is wrong and incomplete

### ISSUE THREAD

**Issue by jedrekdomanski** [vuejs/vue#9118]
### Version
2.4.4

### Reproduction link
[https://jedrekdomanski.github.io/bikeramp-front/](https://jedrekdomanski.github.io/bikeramp-front/)

### Steps to reproduce
Follow the article https://cli.vuejs.org/guide/deployment.html#github-pages

### What is expected?
Deployment is successful

### What is actually happening?
GH Pages does not see dist/ folder, application does not work.

---
My repo: https://github.com/jedrekdomanski/bikeramp-front

**Comment by Justineo** [comment]
You should probably deploy your bundled files in the `gh-pages` branch. See [GitHub Pages' documentation](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

**Comment by jedrekdomanski** [comment]
That's waht I did. I have gh-pages branch with dist/ folder in it and I am building the app from gh-pages but it does not work.
https://github.com/jedrekdomanski/bikeramp-front/tree/gh-pages

module.exports = {
  baseUrl: process.env.NODE_ENV === 'production'
    ? '/bikeramp-front/'
    : '/'
}

I am getting `Failed to load resource: the server responded with a status of 404 () build.js`

**Comment by JounQin** [comment]
https://github.com/jedrekdomanski/bikeramp-front/blob/master/webpack.config.js#L8
`publicPath` in your webpack config is wrong, it should be `/bikeramp-front/` in your case.

**Comment by jedrekdomanski** [comment]
I've changed that and it still doesn't work.
https://github.com/jedrekdomanski/bikeramp-front/blob/gh-pages/webpack.config.js#L8

**Comment by JounQin** [comment]
@jedrekdomanski You are directly modify `gh-pages` branch instead of building App and running `deploy.sh` in `master` branch. Please read document about GitHub Pages by yourself.

And also, you are not using `vue-cli` at all, and it is your own usage problem which is not related to Vue core/cli at all.

**Comment by jedrekdomanski** [comment]
I've already tried the document-way, it did not work but I will try one one time.

**Comment by jedrekdomanski** [comment]
I've tried again and it still doesn't work.
https://jedrekdomanski.github.io/bikeramp-front/
https://github.com/jedrekdomanski/bikeramp-front/tree/gh-pages

So where should I raise this issue? This is related to the documentation which clearly is wrong.

**Comment by jedrekdomanski** [comment]
Thank you. It worked.

How did you know that? I did not read that on GitHub Pages docs.
