### ISSUE TITLE
Server rendered markup not recognized when hydrating

### ISSUE THREAD

**Issue by PierBover** [vuejs/vue#9120]
### Version
2.5.17

### Reproduction link
[https://codepen.io/anon/pen/GwYBgM](https://codepen.io/anon/pen/GwYBgM)

### Steps to reproduce
Run the repro and open the console.

### What is expected?
Vue should use the DOM nodes instead of recreating the DOM again when hydrating.

### What is actually happening?
The static markup is identical to what Vue would render, but I get the error:

> The client-side rendered virtual DOM tree is not matching server-rendered content

**Comment by zyxd** [comment]
Could you please try to remove newline characters and spaces from the "#list" and wrap "ul" with "div" in template? Something like:

```
<div id="list" data-server-rendered="true"><ul><li>Apple</li><li>Banana</li><li>Mango</li></ul></div>

<div id="list-template" style="display: none;">
  <div>
    <ul>
      <li v-for="fruit in fruits">{{fruit}}</li>
    </ul>
  </div>
</div>
```

**Comment by PierBover** [comment]
Yeah I tried that already.

https://codepen.io/anon/pen/GwYBgM

The virtual DOM most likely ignores whitespace.

**Comment by zyxd** [comment]
It is working with "div" wrapper in template.

https://codepen.io/anon/pen/ZmqPYN

**Comment by PierBover** [comment]
Oh of course!

Ah sorry I just saw you mentioned that in your previous comment, but I missed it.

**Comment by lee1994522** [comment]
> Could you please try to remove newline characters and spaces from the "#list" and wrap "ul" with "div" in template? Something like:
> 
> ```
> <div id="list" data-server-rendered="true"><ul><li>Apple</li><li>Banana</li><li>Mango</li></ul></div>
> 
> <div id="list-template" style="display: none;">
>   <div>
>     <ul>
>       <li v-for="fruit in fruits">{{fruit}}</li>
>     </ul>
>   </div>
> </div>
> ```

How does it work?Could you explain the reason?Thank you.
