### ISSUE TITLE
how to invoke methods in "OCX"

### ISSUE THREAD

**Issue by JeremeLau** [vuejs/vue#9123]
### What problem does this feature solve?
Invoke methods in "OCX" like 'usual' html does

### What does the proposed API look like?
<object classid="clsid:77ED27E1-CE66-XXXX-9F16-A3728D783964" id="TESTOCX" width="0" height="0">
    </object>
<script type="text/JavaScript" language="javascript"> 
 function show()
 {
    var ret = TESTOCX.OpenDevice();
    alert(ret);
 }
</script>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
