### ISSUE TITLE
一个vue页面中如何包含另一个前端项目的vue页面

### ISSUE THREAD

**Issue by VioletCzy** [vuejs/vue#9132]
### Version
2.5.18-beta.0

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1、打开一个vue页面
2、动态包含其他项目的vue页面

### What is expected?
可以动态的根据路由url包含页面 

### What is actually happening?
没有效果

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
