### ISSUE TITLE
移动端页面引入vue.js后，浏览器后退滚动条回到顶部

### ISSUE THREAD

**Issue by haodaking** [vuejs/vue#9133]
### Version
2.5.17

### Reproduction link
[https://haodaking.github.io/demos/vue/2.html](https://haodaking.github.io/demos/vue/2.html)

### Steps to reproduce
1、移动端浏览器打开[https://haodaking.github.io/demos/vue/2.html](https://haodaking.github.io/demos/vue/2.html)
2、页面滑动到底部点击“跳转”链接
3、点击浏览器后退按钮

### What is expected?
页面跳转后，浏览器后退，滚动条恢复原来位置。
正常页面：
[https://haodaking.github.io/demos/vue/1.html](https://haodaking.github.io/demos/vue/1.html)

### What is actually happening?
数据异步渲染，页面跳转后，浏览器后退，滚动条滑到了最顶部。

---
设备：iPhone XS；
系统：IOS 12.1；
浏览器：Safari；

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue/issues/8109
