### ISSUE TITLE
Slots that use the slot-scope attribute are not available in $slots

### ISSUE THREAD

**Issue by hstaniszewski** [vuejs/vue#9141]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/eywraw8t/489777/](http://jsfiddle.net/eywraw8t/489777/)

### Steps to reproduce
Just add `slot-scope="slot"` to the slot and `console.log(this.$slots)` in parent component.

### What is expected?
All slots should be available in `$slots`.

### What is actually happening?
Slots that use the `slot-scope` attribute are not available in `$slots`.

**Comment by Justineo** [comment]
They are available in [`$scopedSlots`](https://vuejs.org/v2/api/#vm-scopedSlots).
