### ISSUE TITLE
Cannot render component within v-for loop inside template tag

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#9142]
### Version
2.5.18-beta.0

### Reproduction link
https://jsfiddle.net/d4hv3seo/ - 2.5.18-beta.0
https://jsfiddle.net/Ly3091vw/ - 2.5.17 no issues

### Steps to reproduce
Open 2.5.18 reproduction fiddle and check console log

### What is expected?
Should render the template.

### What is actually happening?
Does not parse the template correctly when iterating over components inside `<template>` tag. If you change it to e.g. div then it's fine and renders the template again.

**Comment by sodatea** [comment]
Regression introduced by this commit: https://github.com/vuejs/vue/commit/d483a49c86874b2e75863b661f81feecd46ae721
