### ISSUE TITLE
Cannot read property '$vnode' of null'

### ISSUE THREAD

**Issue by blalan** [vuejs/vue#9149]
### Version
2.5.18-beta.0

### Reproduction link
[https://codesandbox.io/s/4l9xo6zz9](https://codesandbox.io/s/4l9xo6zz9)

### Steps to reproduce
Change hour in timepicker to a future hour, making the validation fail and error message to appear.

### What is expected?
Finish being able to select hour/minutes and see error on text-field

### What is actually happening?
Console error logged, app because non-responsive until manual refresh.

---
This is a regression, works fine in 2.5.17. @kaelwd thinks this has to do with the transition on the error message element. He referenced this commit: https://github.com/vuejs/vue/commit/f43ce3a5d8f73e273f2d03c9d86ea5662cda481a

**Comment by jvbianchi** [comment]
The same error happens in this issue: https://github.com/vuetifyjs/vuetify/issues/5819

**Comment by posva** [comment]
Please do not include other libraries when reporting bugs. We cannot dive in other libs. If you manage to boil it down without vuetify, please open a new issue

**Comment by jacekkarczmarczyk** [comment]
@posva https://codepen.io/anon/pen/xQoErB?editors=0010
