### ISSUE TITLE
Availability of instance properties in default or validator functions

### ISSUE THREAD

**Issue by christophfriedrich** [vuejs/vue#9153]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/christophfriedrich/gxrs6n0v/3/](https://jsfiddle.net/christophfriedrich/gxrs6n0v/3/)

### Steps to reproduce
1. Open fiddle
2. Click run

### What is expected?
In the default function, I access `this.$parent`, which [is listed as an an instance property](https://vuejs.org/v2/api/#Instance-Properties).

The [docs about default and validator functions](https://vuejs.org/v2/guide/components-props.html#Prop-Validation) say:

> Note that props are validated before a component instance is created, so instance properties (e.g. data, computed, etc) will not be available inside default or validator functions.

Therefore I expected my fiddle to fail.

### What is actually happening?
The fiddle works.

---

I highly appreciate that it works, because that solved [my question I posted on StackOverflow](https://stackoverflow.com/questions/53649690/set-vue-props-default-to-parents-options/53649772#53649772).

However, the docs are misleading. The way it's worded I thought that NO instance property would be available to a default function, but obviously at least `$parent` (I didn't test any other) IS available.

Please update the "default and validator function" doc section accordingly.

**Comment by posva** [comment]
Feel free to send a PR to vuejs docs in its repository 🙂 

PS: using `$parent` in a `default` looks like a very bad idea. I wonder why we can even access `this`

**Comment by christophfriedrich** [comment]
I don't feel confident to explain this myself (I too wonder why it even works...), so I added this as an issue here: vuejs/vuejs.org#1901 (I think that's the repo you meant? Add a link next time, it's easier for newbies who have no clue of how the Vue project is organised internally :slightly_smiling_face:)

I too think that it's a bad idea and woulnd't have designed this myself. But I had to make legacy code work that depends on passing via `$options` (see StackOverflow link) and nevertheless accept data via props in new code...
