### ISSUE TITLE
keep-alive can not cache two router-view

### ISSUE THREAD

**Issue by xuzpeng** [vuejs/vue#9159]
### Version
2.5.1

### Reproduction link
[https://github.com/xuzpeng/vue-sell.git](https://github.com/xuzpeng/vue-sell.git)

### Steps to reproduce
The order page and home page switch pages are not cached, or the home page -> find page -> order page -> home page still occurs.

### What is expected?
Order page and home page are cached

### What is actually happening?
not cached

**Comment by posva** [comment]
Please do not duplicate issues. Your repro is too big. If it concerns only vue make sure to boil it down to Vue only
