### ISSUE TITLE
vue 使用 pug 编译错误

### ISSUE THREAD

**Issue by cn-src** [vuejs/vue#9164]
### Version
2.5.18

### Reproduction link
[https://github.com/cn-src/vue-issue](https://github.com/cn-src/vue-issue)

### Steps to reproduce
1. 使用 vue cli 3 创建默认样例
2. 添加 `vue-cli-plugin-pug` 支持 pug
3. 修改 App.vue 添加简单的 pug 语法
```
<template lang="pug">
    div#app
</template>
```

### What is expected?
编译通过

### What is actually happening?
unexpected token "indent"

---
我是从一个已有的项目中升级依赖版本，2.5.17 重新安装依赖后实际版本是 2.5.18 出现的问题

**Comment by gxlmyacc** [comment]
我也遇到这个问题了，不过我写了一个一个插件解决了它，[https://www.npmjs.com/package/vue-indent-pug-loader](url)，你可以试下看行不行，用法就是把pug-plain-loader换成vue-indent-pug-loader就行了
