### ISSUE TITLE
inheritAttrs: false is not working as mentioned in documentation

### ISSUE THREAD

**Issue by nicholasnet** [vuejs/vue#9178]
### Version
2.5.17

### Reproduction link
[https://codepen.io/anon/pen/EGayYJ](https://codepen.io/anon/pen/EGayYJ)

### Steps to reproduce
Simply run the codepen. You will see class is injected in root element instead of input.

### What is expected?
Class should be injected in input not in root element.

### What is actually happening?
Class is injected in root element

**Comment by posva** [comment]
`class` and `style work differently (https://vuejs.org/v2/api/#inheritAttrs)
If you saw this in documentation, you should open a PR to fix it, that would be neat 🙌
