### ISSUE TITLE
 有2.5.20版本了，但是 vue-template-compiler 最高版本却是 2.5.18，导致构建报错：[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.  

### ISSUE THREAD

**Issue by sugarnut001** [vuejs/vue#9187]
### Version
2.5.20

### Reproduction link
[https://www.npmjs.com/package/vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler)

### Steps to reproduce
package.json 中写成 "vue": "^2.5.17", "vue-template-compiler": "^2.5.17", 这样的写法安装下来得到的 vue 的版本是 2.5.20，vue-template-compiler 的版本是2.5.18，这两个版本不一致了。

### What is expected?
https://www.npmjs.com/package/vue-template-compiler 这里的 tag 有 2.5.20。

### What is actually happening?
实际安装的过程中 vue-template-compiler 却是2.5.18，和最新的 vue 版本不一致。

**Comment by posva** [comment]
both are published

**Comment by yyx990803** [comment]
同时修改版本号，或者全部删了重装。
