### ISSUE TITLE
Adding inline-template to slots

### ISSUE THREAD

**Issue by nabab** [vuejs/vue#9195]
### What problem does this feature solve?
In my case I would like to use a slot as a template for a local component created dynamically in my main component. 

But I think a specific directive given (even on a slot) to prevent a container to compile its content could be useful in many cases. 

I am trying to find for a couple of days in which variable you hide a conditional content when the condition is false and I havent succeeded so far. If the feature cannot be added please feel free to tell me where I can find this uncompiled content :)

Many thanks, your library is an amazing work, I love it so much!

### What does the proposed API look like?
    Vue.component('my-cp', {
      template: `<div><slot inline-template></slot></div>',
      beforeMount(){
        let myTemplates = [];
        // In this case a single property with the content of the slot would be best
        // Otherwise
        for ( let i = 0; i < this.$slots.default.length; i++   ){
          myTemplates.push(this.$slots.default[i].innerHTML);
        }
        // Do what needs to be done
      }
    })

    <my-cp>
      
       <ul v-for="t in test">
           <li>{{t.text}}</li>
        </ul>
        <another-component/>
      </div>
    </my-cp>

**Comment by posva** [comment]
Thanks for the proposal but this is not clear enough. What are you trying to do that doesn't work right now? A small code sample would help

**Comment by nabab** [comment]
My case is for templates, but I think that in general a simple directive would be great

    <div ref="container" v-uncompiled>{{whatever}}</div>

So I can do whatever I please with '{{whatever}}', which is impossible to access otherwise

**Comment by posva** [comment]
there is `v-pre` for what you want but slots are not meant to be bound (or compiled) in the component they are inserted but rather where the code is actually written.
In your example `whatever` must come from the component containing the template you showed.
If you want to pass data up to the parent, you should check scoped slots

**Comment by nabab** [comment]
Oh, how did I miss this one? Sorry!

**Comment by nabab** [comment]
Sorry I am coming back to you on this because with v-pre `<span v-pre><my-cp></my-cp></span>`  my component `my-cp` is still compiled. Is it normal?
