### ISSUE TITLE
How can i get the vue instance through Dom element

### ISSUE THREAD

**Issue by wws19125** [vuejs/vue#9196]
### What problem does this feature solve?
项目中使用类似Jquery的load方法，动态 new 了一个Vue实例，想知道如何通过绑定的Dom元素（就是绑定的el）反向获取到创建的Vue实例，，注意是Vue实例，不是组件实例。因为是动态创建的，我需要获取到该实例，并调用$destroy销毁，否则会引起内存泄漏问题，谢谢

### What does the proposed API look like?
Vue.instance(el:xxxx)

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。

**Comment by wws19125** [comment]
就是看到你们没这个API啊，所以请求新增一个啊
