### ISSUE TITLE
[ssr] Add Vue function to render VNode to html string

### ISSUE THREAD

**Issue by DominusVilicus** [vuejs/vue#9205]
### What problem does this feature solve?
**Use case:**

I'm developing a Server-Side Renderer for Vue (which works with Express, Koa & etc. Will increase migration to Vue). For the SSR's head management to work, it needs a stable API to render `VNode`s to text.

**The way my Vue SSR package will function:**
`master.vue`
```html
<template>
    <div id="app">
        <slot name="content"></slot>
    </div>
</template>
<script>
export default {
    created: function(){
        if(this.$isServer){
            this.$ssrContext.head = "HEAD HERE" // Something needed like:  renderVNodesToString(this.$slots.head)
        }
    },
}
</script>
```

`home.vue`
```html
<template>
    <master>
        <template slot="content">
            Hello World
        </template>
        <template slot="head">
            <script src="https://unpkg.com/vue/dist/vue.js"></script>
            <title>Hello</title>
        </template>
    </master>
</template>
<script>
import master from "layouts/master.vue"

export default {
    components: {
        master
    }
}
</script>
```

My goal is getting `home.vue`'s `head` slot rendered into a string and injecting it into the `this.$ssrContext` so it can be read and injected on the server-side

in `master.vue`, I can access `this.$slots.head` with no issue, and it contains the correct `VNode`s

my question is, how can I render them into a string? a way to basically do:
```js
this.$ssrContext.head = renderVNodesToString(this.$slots.head)
```

From my research, I have been unable to find an easy way to do this.

---- 

**To understand how the renderer works**
```js
const renderer = createBundleRenderer(bundle.server, {
    runInNewContext: false,
    inject: false,
    template: `<!DOCTYPE html>
        <html>
            <head>
                {{{ head }}}
                {{{ renderResourceHints() }}}
                {{{ renderStyles() }}}
            </head>
            <body>
                <!--vue-ssr-outlet-->
                <script>${ bundle.client }</script>
            </body>
       </html>`
})
```
This is the code for the serverbundlerenderer

### What does the proposed API look like?
```js
/**
* @param {VNode}
* 
* @returns {string} - VNode rendered to a html string
*/
Vue.renderVNode = function(VNode){
    //...
}
```

**Comment by posva** [comment]
Technically, you should be able to do this by using a function that returns the vnode and render using what Vue already exports (https://ssr.vuejs.org/guide/#rendering-a-vue-instance).
Not sure of the utility of a feature like this.
FYI you can use https://ssr.vuejs.org/guide/#rendering-a-vue-instance 🙂

**Comment by DominusVilicus** [comment]
issue is, I can't pass the vnode to the server, besides by putting it in the template

```js
<head>
     {{{ head }}}
     {{{ renderResourceHints() }}}
     {{{ renderStyles() }}}
</head>
```

And I can't use complex functions there.

**Comment by DominusVilicus** [comment]
If I had access to the function, I would essentially be able to pass it very easily to the server via the `this.$ssrContext`
```html
<template>
    <div id="app">
        <slot name="content"></slot>
    </div>
</template>
<script>
export default {
    created: function(){
        if(this.$isServer){
            var VNodeArray = this.$slots.head
            var html = ""
            for(let i in VNodeArray){
                html += Vue.renderVNode(VNodeArray[i])
            }
            this.$ssrContext.head = html
        }
    }
}
</script>
```

**Comment by DominusVilicus** [comment]
And I understand the use-case is rare, but this is something that can and will increase server-side adoption, and would be even useful for Nuxt

**Comment by DominusVilicus** [comment]
@posva if it cannot be added to the core, there is an alternate place it could go:

https://ssr.vuejs.org/guide/build-config.html#client-config scroll to `Manual Asset Injection`

there should be a `context.renderVNode(vnode)` / `context.renderVNodes(vnodes)` in the context API.

This would allow:
```js
createBundleRenderer(bundle.server, { //research directives
            runInNewContext: false,
            inject: false,
            template: `<!DOCTYPE html>
            <html>
                <head>
                    {{{ renderVNodesToString(headObject) }}}
                    {{{ renderResourceHints() }}}
                    {{{ renderStyles() }}}
                </head>
                <body>
                    <!--vue-ssr-outlet-->
                    <script>${ bundle.client }</script>
                </body>
            </html>`
        })
```

where headObject is set by `this.$ssrContext.headObject` from within a .vue file

**Comment by DominusVilicus** [comment]
I'd be happy to implement an API with tests in `vue-server-renderer` package for rendering VNodes if given the all-clear.

**Proposed API**
```js
const { createBundleRenderer, renderVNodesToString } = require("vue-server-renderer")

var renderer = createBundleRenderer(serverBundle, {
            inject: false,
            template: `<!DOCTYPE html>
    <html>
        <head>
            {{{ renderVNodesToString(headVNodes) }}}
        </head>
        <body>
            <!--vue-ssr-outlet-->
        </body>
    </html>`
})

// headVNodes set by this.$ssrContext = this.$slots.head in vue file

renderer.renderToString({
    renderVNodesToString
})
```

This would allow for a far greater head management system for Vue that's based in the `<template>`, and would increase server-side adoption in the process. This API should add virtually no over-head to users who decide not to use it. Size increase would be minimal, and limited to the `vue-server-renderer` package.

**Comment by DominusVilicus** [comment]
My further findings show that if the function is provided, it would need to be either:
- Fully synchronous, so it could be included in the `template` of the bundle renderer
- Or, allowing async code in the  `{{{ ... }}}` syntax in the template so `await` may be used.

**Comment by DominusVilicus** [comment]
@yyx990803 I would be happy to try implement this.

It would involve making ssr `template` able to parse `await`s, and would add a new exposed API for rendering VNode(s)

**Comment by DominusVilicus** [comment]
Accidental close

**Comment by leopiccionia** [comment]
@yyx990803 I think that it was accidentally moved from **Todo** to **Done** in [2.6](https://github.com/vuejs/vue/projects/4) project, once @DominusVilicus accidentally closed the issue. I'm sorry if bothering.

**Comment by yyx990803** [comment]
I think I originally misunderstood the request when I added it to 2.6 - after looking at it in more details I think this can be done in userland.

There are a few things that I have concern about landing this in Vue itself:

- This method cannot be exposed on the `Vue` runtime, since it's a server only utility (and thus should not be included in the universal runtime)

- It's better exposed on `this.$ssrContext` as an injected helper. (This means you can implement it yourself)

- The `renderToString` exposed by `vue-server-renderer` can only be async because there may be async components or async data prefetch functions down the tree. We cannot expose a sync API because it will not work correctly in all cases. In comparison, it's much easier to write a simple VNode -> string render function that only handles predictable `<head>` content.

The use case also seems niche, so I think we'd be better off to test an implementation in userland first.

**Comment by DominusVilicus** [comment]
@yyx990803 

I'd be happy to implement this in userland, but the issue is that there is no exposed API that I could use to render VNodes to a string

It would be possible if there was an API exposed by `vue-server-renderer` to render `VNode`s, for example:


```js
const { createBundleRenderer, renderVNodesToString } = require("vue-server-renderer")

var renderer = createBundleRenderer(serverBundle, {
            inject: false,
            template: `<!DOCTYPE html>
    <html>
        <head>
            {{{ renderVNodesToString(headVNodes) }}}
        </head>
        <body>
            <!--vue-ssr-outlet-->
        </body>
    </html>`
})

//pass $ssrContext the VNode renderer
renderer.renderToString({
    renderVNodesToString
})
```

**Comment by DominusVilicus** [comment]
From studying the internals, it seems the two options are:

1. making the Lodash template compiler able to handle await (which would probably mean implementing a custom template compiler for the `template` setting
2. exposing a synchronous API for rendering VNodes in the `vue-server-renderer`

**Comment by DominusVilicus** [comment]
Awesome! I managed to create a custom VNode renderer for the specific task of head management (you can see it in #code-review in Vue Land)

I did make a working version with the function based template in #9324 but tests were failing for some reason.  It was a non-breaking change too (users could optionally still use the string template)

**Comment by mateuszgwozdz** [comment]
For me the `this.$ssrContext` inside a component is undefined. I am using v2.5.22 and the vue-hackernews-2.0 template. Based on what the documentation says, it should be exposed in the component automatically

**Comment by mateuszgwozdz** [comment]
Finally a working draft: 

```
Vue.mixin({
  created: function () {
    var title = this.$options.title
    if (title) {
      if(typeof document !== 'undefined')
        document.title = title;
      else
        this.$ssrContext.title = title
    }
  }
})

```

and inside a component:

```
  export default {
    name: 'home',
    title: 'hello!',
...
```

Now need to populte this with API data.

**Comment by DominusVilicus** [comment]
Have you had a look at https://github.com/futureaus/servue?

**Comment by alucidwolf** [comment]
@DominusVilicus I have the following task and am wondering if you are trying to accomplish something similar with this request.

Environment:
Dot Net Core 2.1

Task:
1. Fetch HTML string from API in serverPrefetch(). _This HTML can contain [PLACEHOLDERS]._
2. Replace `[PLACEHOLDERS]` with proper vue component, such as replacing `[MAIN_NAV]` placeholder with `<main-nav :code="navHtml" />` component.
3. Render updated string of HTML with newly added vue components on the server and deliver to browser with complete functionality for navigation.

Reading up on https://github.com/futureaus/servue now to see if this is a viable solution, but wanted to toss a note out to you for your feedback.

**Comment by DominusVilicus** [comment]
@alucidwolf What are you trying to accomplish? You shouldn't be rendering HTML code from a server, if you need a dynamic menu, send the menu data as the data, and let your .vue files render it

**Comment by alucidwolf** [comment]
@DominusVilicus I want to create different page layouts from this Html so it is not just data I need for the menu but also the Html structure for the page layout, which can be different.
