### ISSUE TITLE
i can't name the parameter with upperCase when i user $emit

### ISSUE THREAD

**Issue by gepengjun** [vuejs/vue#9206]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/gepengjun/108shofc/1/](https://jsfiddle.net/gepengjun/108shofc/1/)

### Steps to reproduce
click the button, it just run the method   enlargeTestHandler but doesn't run the method  onEnLargeText;
if i name the $emit parameter in lowerCase ,such as lagert,  it can run the method onEnLargeText

### What is expected?
the parent's method-'onEnLargeText' will run;

### What is actually happening?
the parent's method-'onEnLargeText' does not  run

---
have no;

**Comment by Justineo** [comment]
See the [docs](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names).
