### ISSUE TITLE
Laravel Vue Unknown custom component On production server

### ISSUE THREAD

**Issue by Magnificent-Big-J** [vuejs/vue#9214]
I am  using Laravel as Backend and Vue Js as my frontend.
On the development, components works fine. I added new components later, when I push the changes to the production server I get  [Vue warn]: Unknown custom element.  I don't understand what I am missing because everything is well on development while on production is not. I ran npm run dev on production to compile the app.js file but still.

I have registered most of my components global using Vue.component.
![image](https://user-images.githubusercontent.com/30896750/50100431-2f2e7800-0229-11e9-8b79-0baeec69c664.png)
app-accept-bill I added it after new changes were required, it fails on production

**Comment by arturcesarmelo** [comment]
Same here

**Comment by trig79** [comment]
I had the same issue, everything was fine locally but as soon as I pushed live it kept failing.

For me the issue was renaming the component file name, to align with the component name:

```
Orig:
import SearchDropdown from './components/Search.vue';  

app.use(VueAxios, axios)
app.component('search-dropdown', SearchDropdown)
    .mount('#app');

Changed to 
import SearchDropdown from './components/SearchDropdown.vue';  

app.use(VueAxios, axios)
app.component('search-dropdown', SearchDropdown)
    .mount('#app');
```
everything seems to be working fine now
