### ISSUE TITLE
webpack-dev-server运行后vue实例不显示

### ISSUE THREAD

**Issue by iOSQiao** [vuejs/vue#9220]
### Version
2.5.21

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn)

### Steps to reproduce
使用`webpack`工具创建`vue`的项目。所有的依赖都已经创建好了。
启动`webpack-dev-server --open`，页面自动加载了打包好后的`app.js`的文件，但是页面上并没有如期的显示结果，而是什么内容也没有。
但是使用`index.html`中注释的内容，直接打开`index.html`文件，是有“Hello World.”显示的。
`app.js`
```
import Vue from 'vue';

new Vue({
    el: '#app',
    data: {
        message: 'Hello World.'
    }
});
```
`index.html`
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vue demo</title>
</head>
<body>
    <div id="app">
        <p>{{ message }}</p>
        <p>this is a vue demo.</p>
    </div>
    <!-- <script src="../node_modules/vue/dist/vue.min.js"></script>
    <script>
        new Vue({
            el: '#app',
            data: {
                message: 'jkfljdlfkjdslfkjdlfkjaslfkdj'
            }
        })
    </script> -->
</body>
</html>
```
因为这是一个demo，所以使用了最简单的例子。

### What is expected?
启动`webpack-dev-server --open`，加载内存中打包后的`app.js`文件，页面中显示内容。

### What is actually happening?
启动`webpack-dev-server --open`，加载内存中打包后的`app.js`文件，页面中显示空白。

**Comment by iOSQiao** [comment]
I forgot the module parsing. The module path that `import Vue from 'vue';` actually needs to load is `'vue/dist/vue.esm.js';`. So in `webpack.config.js';` you need to add module parsing.
```
resolve: {
    alias: {
        'vue$': 'vue/dist/vue.esm.js'
    }
}
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
