### ISSUE TITLE
Warn when the type of a prop isn't a constructor 

### ISSUE THREAD

**Issue by shurfee** [vuejs/vue#9224]
### What problem does this feature solve?
It suppose better error handling for prop types errors.
Steps to reproduce error:
1. Set prop type equals to string ('String', not String):
```javascript
exampleProp: {
  type: 'String',
}
```

2. Run project and get an error:
```javascript
[Vue warn]: Error in nextTick: "TypeError: Right-hand side of 'instanceof' is not an object"
TypeError: Right-hand side of 'instanceof' is not an object
    at assertType (vue.esm.js:1668)
    at assertProp (vue.esm.js:1626)
    at validateProp (vue.esm.js:1560)
    at loop (vue.esm.js:3334)
    at initProps (vue.esm.js:3367)
    at initState (vue.esm.js:3308)
    at VueComponent.Vue._init (vue.esm.js:4628)
    at new VueComponent (vue.esm.js:4798)
    at createComponentInstanceForVnode (vue.esm.js:4310)
    at init (vue.esm.js:4131)
```

Error log is not evident and it is difficult to understand the source of problem (first time with this error anyway).

### What does the proposed API look like?
Error message in this case may look like:
```javascript
"Incorrect prop type 'exampleProp' at:123 (where 123 is example string position in the code)"
```

**Comment by cedric05** [comment]
can i work on this?

**Comment by posva** [comment]
Yes :)

**Comment by Zarad1993** [comment]
HI guys, I'm very interested with this project and I wanted to get started with a simple issue. @cedric05 takes the priority but I'd appreciate a review #9241. Thank you so much.

**Comment by JonathanDn** [comment]
Hey @posva I would love to aid with any good first issues in the future if needed :)

**Comment by Zarad1993** [comment]
@posva - Is there any chance #9241 can be considered a candidate PR for this issue?

**Comment by posva** [comment]
Yeah, it contains tests and looks better overall but I haven't checked it yet 🙂

**Comment by Zarad1993** [comment]
Gotcha, I'll keep my eye out there if it needs any modifications.

**Comment by huruji** [comment]
I had this error just now. how to fix?

**Comment by posva** [comment]
Use a constructor like Number, String, Function, etc. 
Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by AlekNiebla** [comment]
hey can I work on this first time issue? im new at working on Opensource projects and I would love to give it a try to this issue.

**Comment by Holgermueller** [comment]
Would it be okay for me to work on this issue?

**Comment by TobiTenno** [comment]
the "solution" doesn't help much with... `Invalid prop type: "[object Object]" is not a constructor`
