### ISSUE TITLE
Vue's unbind of custom directives provides unexpected 'el'

### ISSUE THREAD

**Issue by RuphiLau** [vuejs/vue#9225]
### Version
2.5.21

### Reproduction link
[https://codepen.io/RuphiLau/pen/NebaQB](https://codepen.io/RuphiLau/pen/NebaQB)

### Steps to reproduce
1. Click 'HIDE' to make 'show' set to false
2. See the output of console, and it prints 'b' and 'c'

### What is expected?
It should print 'a' and 'c'

### What is actually happening?
It prints 'b' and 'c'

---
If I add a key for each p tag, the problem disappeared, but that's inconvenience for such a non-list situation

**Comment by Justineo** [comment]
It is an expected behavior as I understand.

Actually `key`s are not bound to `v-for`. It offers hints each time Vue decides to reuse an existing element or not. This includes `v-if`.

Anyway, I think we do need to document this further. See https://github.com/vuejs/vuejs.org/issues/1248.
