### ISSUE TITLE
建议vue支持配置中心

### ISSUE THREAD

**Issue by weisiqian** [vuejs/vue#9226]
### What problem does this feature solve?
发布到线上后很有可能遇到后端接口地址发生变动的情况，而程序发布后修改配置是一件很麻烦的事情，尤其是访问量很高的情况下根本不可能停止线上程序来修改配置文件；此外当高可用情况下，修改集群内所有实例的配置文件更是一件麻烦的事情，希望vue能支持给正在飞行的飞机换零件，比如SpringCloud Config这种。

### What does the proposed API look like?
无

**Comment by yyx990803** [comment]
前端发布就是推新文件，配置都是构建时的，你这跟 Vue 没有什么关系...
