### ISSUE TITLE
Unpkg.com bare URL broken

### ISSUE THREAD

**Issue by jmotes** [vuejs/vue#9228]
### Version
2.5.21

### Reproduction link
[https://unpkg.com/vue](https://unpkg.com/vue)

### Steps to reproduce
Go to https://unpkg.com/vue

Observe redirect 

### What is expected?
Redirect to https://unpkg.com/vue@2.5.21/dist/vue.min.js

### What is actually happening?
Re-direct to https://unpkg.com/vue@2.5.21/index.js (404 error) from multiple locations in the US (see #need-help on Discord).

**Comment by Akryum** [comment]
I can't reproduce.

**Comment by Akryum** [comment]
I guess it's an issue with unpkg, and I don't think we can do something about it.

**Comment by jmotes** [comment]
Hmmm, ok. Thanks for the quick reply. I was hoping maybe a redeployment could help. I'll search around for someone to contact over there. Do you happen to know anyone?

**Comment by Akryum** [comment]
You can reach out to them here: https://twitter.com/unpkg

Anyway I think you should use the version URL instead, or your websites **will** break (imagine Vue 3.0 being release, it will be the new version redirected to).

**Comment by jmotes** [comment]
You're right. We're getting that changed pushed out now, but we have about 12 hours to go since we're using a CI/CD process for the deployments. I'll message them over there. Thanks so much!
