### ISSUE TITLE
V-For list source in VNode Children

### ISSUE THREAD

**Issue by Orimay** [vuejs/vue#9230]
### What problem does this feature solve?
This would make it possible for directives to look into list sources and apply manipulations to those. For instance, I'd love to create a drag directive, that will make it possible to target `v-for` source and apply changes directly without the need of additional array pass as an argument to the directive. There could possibly be many other uses, which I am not aware of, but this feature is easy to implement and wouldn't seem to hurt

### What does the proposed API look like?
I would use `vnode.children.list`. The only line needs to get added:

/vue/src/core/instance/render-helpers/render-list.js, after line 36

`(ret: any).list = val`

That's it! Thank you in advance

**Comment by posva** [comment]
Your FR is not clear and no use case is presented but sounds that you want to use directives for more than they can do. What you need is to use a component instead 🙂
