### ISSUE TITLE
provide and inject update question

### ISSUE THREAD

**Issue by yoonasy** [vuejs/vue#9237]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/yoonasy/gjyz307r/](https://jsfiddle.net/yoonasy/gjyz307r/)

### Steps to reproduce
Access is also required because there is no login in the project

Try the following bold moves

But you can't update provide

`$Watch` has tried

children component `inject: ['user']`
update vuex state to user after `this.$store.commit('userInfo/updateUser', {})`
Using injection in children component `this.user`
They don't get updated
The answer is the same

### app-component
```javascript
export default {
  provide () {
    return {
      user: this.user
    }
  },
  async beforeRouteEnter (to, from, next) {
    await store.dispatch('userInfo/getUserInfo')
    next()
  },
  computed: {
    ...mapState('userInfo', ['user'])
  }
}
```

### children-component
```javascript
export class {
  inject: ['user'],
  created () {
    this.user.isLogin && this.getMsgStatus()
    console.log(this.user)
    this.$store.commit('userInfo/updateUser', {})
    console.log(this.$store.state.userInfo.user) // new state value
    console.log(this.user) // Same value as before
  }
}
```

### What is expected?
i want to update the parent component's provide when the child component commits

### What is actually happening?
parentComponent's provide invariability

**Comment by yoonasy** [comment]
state `user` is Object

```
const state = {
  user: {},
  regScanFlag: false
}
```

**Comment by yoonasy** [comment]
childrenComponent
Currently, the traditional way`...mapState('userInfo', ['user'])`

But frequent use in projects can be cumbersome

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yoonasy** [comment]
@posva  thank you
