### ISSUE TITLE
El-form verification code input is Chinese input method, press enter to submit el-form

### ISSUE THREAD

**Issue by chengheai** [vuejs/vue#9238]
### What problem does this feature solve?
          <el-input type="text" v-model="loginForm.content" @keyup.enter.native ="submitForm('loginForm')"  autocomplete="off" placeholder="图形验证码">
            <template slot="prepend"><span class="fa fa-picture-o" style="width: 13px"></span></template>
          </el-input>

### What does the proposed API look like?
when  Chinese input keyup.enter not submit form

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
