### ISSUE TITLE
memory leak by dynamically sets keep-alive "include"

### ISSUE THREAD

**Issue by ruiyong-lee** [vuejs/vue#9240]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/a5qb0m8u/18/](https://jsfiddle.net/a5qb0m8u/18/)

### Steps to reproduce
1、click  “Go to Home” enter "Home"，create heap snapshot 1
![image](https://user-images.githubusercontent.com/12726826/50370297-35cd3e80-05df-11e9-9f02-eba3f0835736.png)

2、click  “Go to Table” enter "Page"

3、click  button “add Page to include”

4、click  “Go to Home” enter "Home"

5、click  button “remove Page from include”, create heap snapshot 2

Compare snapshot 1 with snapshot 2
![image](https://user-images.githubusercontent.com/12726826/50370300-42ea2d80-05df-11e9-9532-46d7d06ce1e3.png)

### What is expected?
No memory leak

### What is actually happening?
Memory leak

**Comment by posva** [comment]
When reporting memory leaks please, provide the minimal code with no extra dependencies. Thank you

**Comment by ruiyong-lee** [comment]
https://jsfiddle.net/a5qb0m8u/19/

**Comment by ruiyong-lee** [comment]
@posva OK! Thanks，this would be an issue coming from vue-router

**Comment by qq73927267** [comment]
I also encountered the same problem. I use keep-alive,when I upadte my data in activated,every trigger activated,it would lead Memory leak
