### ISSUE TITLE
This is a magic value

### ISSUE THREAD

**Issue by linG5821** [vuejs/vue#9244]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/linG5821/o0cn12fa/1/](https://jsfiddle.net/linG5821/o0cn12fa/1/)

### Steps to reproduce
<body>
  <div id="app">{{ num * 100 }}</div>
  <script>
      var vm = new Vue({
        el: '#app',
        data: {
          num: 0.07
        }
      })
  </script>
</body>

The result of the above code is shown as  7.000000000000001 
I don't know if this is a mistake, but this is not what I expected, is this a particular value?

### What is expected?
7

### What is actually happening?
Odd number

**Comment by yyx990803** [comment]
This is just [how JavaScript works](https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript)... nothing Vue can do.
