### ISSUE TITLE
Vue cli 3 hot reload not working windows 10

### ISSUE THREAD

**Issue by sirkif** [vuejs/vue#9245]
i was searched more in StackOverflow .. in Vue cli 3 hot reload not working windows 10.. i need to refresh Google Chrom Manually every time.. although i installed Live Serve Extension.. can you help me﻿

**Comment by smolinari** [comment]
@Adamkif - You don't need live server extension. You need to simply create a Vue app with the CLI 3, then run `yarn serve`. 

I also just tested and am seeing the same problem. It seems to be a general problem too, from the Facebook discussion. https://www.facebook.com/groups/vuejsdevelopers/permalink/576619366083417/

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: Not Found
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.21
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found

Scott
