### ISSUE TITLE
Component prop unexpectetly update on non-dependent Parent data changes

### ISSUE THREAD

**Issue by romanzipp** [vuejs/vue#9246]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/romanzipp/eywraw8t/517112/](https://jsfiddle.net/romanzipp/eywraw8t/517112/)

### Steps to reproduce
1. Create a component which recevies an Object prop with at least one element depending on the parent component
2. Change any other data attribute on the parent component
3. The partial component will receive an update on the prop

### What is expected?
The partial component prop should not get updated since any data received from the parent component is not changed.

### What is actually happening?
The partial component prop will be updated, regardless which parent data attribute is changed. The new and old prop Object is identical.

**Comment by posva** [comment]
This is expected because the object is passed inline in the template, creating a new instance every time the parent renders and therefore passing a new prop as well. Use a data or computed property instead if you need to pass an object
