### ISSUE TITLE
[WDS] Disconnected!

### ISSUE THREAD

**Issue by kangdawei** [vuejs/vue#9249]
vue 3.2.1
<img width="338" alt="76b82577e4f83d511a1632c5f35ceaff" src="https://user-images.githubusercontent.com/13482712/50395950-cf444e00-07a1-11e9-886b-e48f9ee2bc38.png">

**Comment by sodatea** [comment]
See: https://github.com/vuejs/vue-cli/issues/3173#issuecomment-449573901
