### ISSUE TITLE
data中获取不到props数据 [Pros data is not available in data]

### ISSUE THREAD

**Issue by ShszCraft** [vuejs/vue#9256]
### Version
2.5.20

### Reproduction link
[https://codesandbox.io/s/2wnx81r28y](https://codesandbox.io/s/2wnx81r28y)

### Steps to reproduce
我在在线网站 如：codesandbox 一切正常，但是我的环境中，就不正常了。

### File a.vue

```
<template>
    <div>
        <with-info :openData="withInfo"></with-info>
    </div>
</template>
<script>
import withInfo from 'b'
export default {
        data() {
            return {
                withInfo: {
                    name: 'name'
                }
            }
        },
        components: {
            'with-info': withInfo
        }
}
</script>
```

### File b.vue

```
<template>
    <div>
        <p>{{openDatas}}</p>
        <p>{{openData}}</p>
    </div>
</template>
<script>
export default {
        data() {
            return {
                openDatas: this.openData
            }
        },
        props: {
            openData: {  type: Object }
        }
}
</script>
```

运行结果：

```
{}

{name: 'name'}
```

## 问题：

就是 'openDatas: this.openData' 获取不到 'props' 的数据？但是在html中插入 ' {{ openData }}'  可以获取到 props 数据

问题出现于 刷新页面的时候获取不到.

但是每次修改代码，使页面刷新 就会正确显示结果。

我的环境中 我是这样操作的：

1. 如果数据没有显示出来，那我就在 'props.openData' 添加 'default: {}' 。然后 'openDatas' 他就出来了。刷新页面又消失了
2. 然后我接着删除 'default: {}' 又显示出来了，刷新页面。结果又消失了
3. 包括在 created里面 'thisopenDatas = this.openData' 不起作用， 不是不起作用，而是 'console.log('created', this.openData)' 获取不到 'props' 里面的数据？？？，包括 'mounted' 亦如此。同样得不到数据。
4. 在 'created mounted' 中，添加修改数据，使页面自动刷新，数据就获取到了
5. 唯一需要提到的是 html 中的 '{{ openData }}' 是有数据的

我也不知道这是怎么了。是我写代码写的走火入魔了？我是做后端的，前端也学了，不应该啊

## issue:

s 'openDatas: this.openData' unable to obtain 'props' data? But inserting '{{openData}}' in HTML can get props data

The problem arises when the page is refreshed.

But every time you change the code, the page refresh will display the results correctly.

This is how I operate in my environment:

1. If the data is not displayed, I add 'default: {}' to 'props.openData' . Then openDatas came out. The refresh page disappeared again
2. Then I deleted 'default: {}' and displayed it again, refreshing the page. The result disappeared again.
3. Including 'thisopenDatas = this.openData' in create does not work, not does it work, but 'console.log('created', this.openData)' can not get the data in 'props' ?? The same is true for 'mounted'. No data was available.
4. In 'created mounted', add modified data to make the page refresh automatically, and the data is obtained.
5. The only thing to mention is that '{{openData}}' in HTML has data

I don't know what happened. Was it me who wrote code that got into trouble? I do the back end, the front end also learned, should not ah

> Translation, may have problems with expression

```
C:\Users\mcshs>vue -V
2.9.6
```

### What is expected?
很简单，我只想 在data中可以获取到 props 数据

Simply, I just want to get props data in data.

### What is actually happening?
但是没有获取到，不知道是我的问题还是。。。。

But I didn't get it. I don't know if it's my problem or....

---
这个问题比较紧急，特急

This problem is urgent and urgent.

**Comment by posva** [comment]
you cannot name both, the prop and the data the same name.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by multics** [comment]
应该是你的环境问题：
1、浏览器端清一下缓存；
2、重新npm run serve；
3、关闭浏览器，重新开你的这个页面。
