### ISSUE TITLE
Add an easy way to import non-NPM third party libraries please

### ISSUE THREAD

**Issue by thammarith** [vuejs/vue#9257]
### What problem does this feature solve?
I'm trying to import a Google Maps API.

However, it comes with `<script>...</script>` tag version only. It doesn't provide a way to use client-side Google Maps API with NPM. So, I have to either, use `google-maps` API which isn't great for flexibility (I need synchronous loading), or put the `<script>...</script>` tag in the `index.html` myself which will load globally and not good programmatically.

So, please add an easy way to import non-NPM third party libraries please

### What does the proposed API look like?
```
import anOrdinaryLibraray from 'https://api.somewhere.io/library.js'
```

**Comment by Justineo** [comment]
I'm sorry but it's not a Vue issue. You should seek advice from your bundler, eg. webpack.
