### ISSUE TITLE
History Mode get 404 not found after refresh on some router

### ISSUE THREAD

**Issue by kpeng2016** [vuejs/vue#9260]
### Version
2.5.20

### Reproduction link
[https://github.com/kpeng2016/vuerouterissue](https://github.com/kpeng2016/vuerouterissue)

### Steps to reproduce
1. git the test project as link to minimal reproduction
2. npm install
3. npm run build
4. copy files under dist folder to nginx html folder
5. change configuration about nginx
    		location  / {
                    try_files $uri $uri/ /index.html;
                }
6. start nginx

### What is expected?
can visit the http://xxx.xxx.xxx.xxx/newrouter ( non root router)

### What is actually happening?
configure the nginx as the site https://router.vuejs.org/en/essentials/history-mode.html, start the nginx, and visit the http://xxx.xxx.xxx.xxx/newrouter , it show me 404 not found error, check the error.log of nginx, it give the message "open() "/usr/share/nginx/html/myHome" failed (2: No such file or directory)", and I try most solution from website, but nothing can solve this issue.

---
It crazy me sereral days, please help me how to solve this issue. thanks

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Discord chat](https://chat.vuejs.org),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
