### ISSUE TITLE
添加阻止视图更新的控制方法

### ISSUE THREAD

**Issue by gooqiao** [vuejs/vue#9263]
### What problem does this feature solve?
假设：有一对话框组件，父组件传进来的props会触发该组件若干的视图更新。
现象：当该对话框隐藏(display:none;)时，父组件传入的props依然会触发该组件的视图更新。
要求：如果我可以在beforeUpdate钩子中通过return false阻止此次视图更新，那么就可以避免不必要的视图更新带来的性能损耗。

### What does the proposed API look like?
通过beforeUpdate钩子return false 来阻止视图的更新
``` js
beforeUpdate() {
    if(this.show){
        return false
    }
    return true
}
```

**Comment by posva** [comment]
If you visually hide it, it's normal for it to update. Use `v-if` if you don't want to trigger any updates on it. You can wrap it with `keep-alive` it you need to preserve state

**Comment by gooqiao** [comment]
实际上，我已经尝试过v-if，但这个时候我在打开对话框时，我猜测由于视图更新太多，导致会有一点卡顿感。所以我想知道在此情况下有没有更好性能的方式。
