### ISSUE TITLE
$vm.$children seems not changed after changed the order of components

### ISSUE THREAD

**Issue by xmflswood** [vuejs/vue#9264]
### Version
2.5.21

### Reproduction link
[https://codepen.io/anon/pen/gZGPPL](https://codepen.io/anon/pen/gZGPPL)

### Steps to reproduce
1.change the components order
2.console.log the $children

### What is expected?
should change the $children order corretly

### What is actually happening?
$children order not changed

**Comment by posva** [comment]
Duplicate of #6702
