### ISSUE TITLE
Importing vue.min.js inside es6 module doesn't work

### ISSUE THREAD

**Issue by lucafabbian** [vuejs/vue#9273]
### Version
2.5.21

### Reproduction link
[https://codepen.io/lucafabbian/pen/EGbJQG?editors=1010](https://codepen.io/lucafabbian/pen/EGbJQG?editors=1010)

### Steps to reproduce
Simply import vue.min.js with es6 import instead of inside a script tag

### What is expected?
Vue should load as window.Vue and be available inside the page

### What is actually happening?
Since inside modules windows != this (this is undefined)  umd loading fails

---
This bug would be easily fixed replacing `this` with `this || self` in umd header.<br> 
Also refer to https://github.com/umdjs/umd/issues/124

**Comment by LinusBorg** [comment]
That build is not meant to be consumed in a module setup. 

Simply use the esm build. If you need Vue on `window`, assign it yourself.

**Comment by sqal** [comment]
Use esm build:

`import Vue from 'https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.21/vue.esm.browser.min.js'`

**Comment by yyx990803** [comment]
2.6 will include `dist/vue.esm.browser.min.js` which is meant for direct ES6 import.

**Comment by lucafabbian** [comment]
Hi!
Thanks for your answers.
I've already tried the `vue.esm.browser.min.js`, but it doesn't solve my problems either.
The same page works with the script tag and with with the "|| self" patch, but it doesn't with the browser es6 version: the page loads but reactivity is broken.
Exactly same code; the same issue happens both with source code and after rollup build.
Am I missing something or should I open a new issue?
I'll add a codepen as soon as possible.

**Comment by LinusBorg** [comment]
> it doesn't with the browser es6 version: the page loads but reactivity is broken.

Seems like a sparate issue.
