### ISSUE TITLE
Experimental Vue 3.0 branch

### ISSUE THREAD

**Issue by Smilebags** [vuejs/vue#9276]
### What problem does this feature solve?
Exposing a Vue 3.0 branch would allow developers interested in improving Vue 3.0's typescript integration and usability to test it before it is released and allow them to start work on building new sites with Vue 3.0 so that it can be used in production when it is released. It will benefit both users of Vue and developers since we will have better feedback and bug-reports on Vue 3.0 and will have a head start for people writing documentation for (for example) migrating to Vue 3.0, and developing standards for using TypeScript with Vue.

### What does the proposed API look like?
A Vue 3.0 branch in GitHub.

**Comment by Smilebags** [comment]
Thanks for the link, I looked for issues related to 3.0 but that didn't come up.

Understandably, if the project is still under daily changes then the added burden of PRs and issues would outweigh the benefit - I think my perception of 3.0 was that it seems to be reasonably sturdy at this point; maybe that isn't the case yet!

I look forward to when it is ready for community involvement.

**Comment by khendry** [comment]
So Q1 of 2019 has come and gone. As has Q2. I'm not aware of a 3.0 repo being made public to date. Is there an update to the project roadmap coming out with some some new information?

**Comment by LinusBorg** [comment]
Yes, we are working on an update for the roadmap. 

Since we dropped the class proposal a lot of things had to be re-done, which is a bi factor in the whole process will take more time than initially anticipated.

**Comment by ghulamhussain** [comment]
any update on this issue.

**Comment by awkj** [comment]
the alpha version should release on Q3, is delay?

**Comment by LinusBorg** [comment]
Slightly, yes

**Comment by awkj** [comment]
good loucky, vue 3.0, Evan You move alpha from Q3 to Q4

**Comment by trivikr** [comment]
vue-next code can be viewed at https://github.com/vuejs/vue-next
