### ISSUE TITLE
Allow users of Vue to start their own private variables with `_` as is the convention in numerous other languages

### ISSUE THREAD

**Issue by subdigit** [vuejs/vue#9277]
### What problem does this feature solve?
Internal Vue variables that previously used `_` can simply move to using `__` or something else to avoid conflicts.  Users from languages like Java have a tendency to start private variables with `_` and because of the conflict that occurs with Vue's usage of `_` starting variables, it can be a little mysterious as to why something is not working right.

### What does the proposed API look like?
Switch Vue's internal variables to start with something other than `_`.  End developers will not see a difference and will benefit from working code when they use semantics imported from other languages that typically use `_` as a starting character to indicate private variables.

**Comment by Justineo** [comment]
Precompiled render functions depends on render helpers start with `_`. ATM we cannot afford breaking existing code compiled by earlier versions of `vue-template-compiler`.

But you can still make this request once we start calling for RFC proposals for v3.0 some while later. Thanks.

**Comment by sirlancelot** [comment]
You are free to start variables with `_` or `$`. However, in order to access that variable, you need to go in to the `$data` object:

```
export default {
  data: () => ({
    _internal: "hello world"
  }),
  methods: {
    speak() {
        alert(this.$data._internal)
    }
  }
}
```
