### ISSUE TITLE
通过vue.use注册的插件在不同的组件里怎么给插件传不同的参数

### ISSUE THREAD

**Issue by jtpower12** [vuejs/vue#9278]
### What problem does this feature solve?
通过vue.use注册的插件在不同的组件里怎么给插件传不同的参数

### What does the proposed API look like?
vue.use

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
