### ISSUE TITLE
How to correrctly reference assets in development and deployment

### ISSUE THREAD

**Issue by SumNeuron** [vuejs/vue#9281]
### Version
2.5.21

### Reproduction link
[https://cli.vuejs.org/config/#baseurl](https://cli.vuejs.org/config/#baseurl)

### Steps to reproduce
use vue-cli to create an app

follow deployment guide https://cli.vuejs.org/config/#baseurl (make vue.config.js file with baseUrl)

import {baseUrl} and try to href/src=`${baseUrl}/assets/mything.ext`

### What is expected?
file / img / etc retrieved

### What is actually happening?
not found

---
this is for vue cli3

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

using `import imgURL from '@/assets/image.png'` or directly in the src attribute (no v-bind): `<img src="@/assets/image.png">`
