### ISSUE TITLE
Same slot content for multiple template slots

### ISSUE THREAD

**Issue by yamsellem** [vuejs/vue#9289]
### What problem does this feature solve?
I guess, this is a new feature; Is there a way to set the same content for multiple slots without copy pasting?

So this:

```vue
<base-layout>
  <template slot="option">
    <span :class="'flag-icon-'   props.option.toLowerCase()" />{{ countriesByCode[props.option] }}
  </template>

  <template slot="singleLabel">
    <span :class="'flag-icon-'   props.option.toLowerCase()" />{{ countriesByCode[props.option] }}
  </template>
</base-layout>
```

### What does the proposed API look like?
Could be written that way:

```vue
<base-layout>
  <template slot="['option', 'singleLabel']">
    <span :class="'flag-icon-'   props.option.toLowerCase()" />{{ countriesByCode[props.option] }}
  </template>
</base-layout>
```

Thanks a lot.

**Comment by Justineo** [comment]
Now you can either

1. define the repeated content as a component
2. or use render functions for more flexibility

**Comment by Justineo** [comment]
The solution you mentioned in https://github.com/shentao/vue-multiselect/issues/905#issuecomment-452317332 is interesting. I assume this could resolve this issue. 😄

**Comment by pmalek** [comment]
I guess I have a similar (more complicated) problem:

I have this:

```vue
            <template v-slot:cell(size)='item'>
                <Comp :value='item.value'></Comp>
            </template>

            <template v-slot:cell(weight)='item'>
                <Comp :value='item.value'></Comp>
            </template>
```

but I'd like to have something like:

```vue
            <template v-slot:cell(cellName)='item' v-for='cellName in ['size', 'weight']'>
                <Comp :value='item.value'></Comp>
            </template>
```

Can something like this can be achieved or do I have to stick with copy-paste?
