### ISSUE TITLE
_.debounce().cancel() is not working with Vue.js properly

### ISSUE THREAD

**Issue by KunHwanAhn** [vuejs/vue#9294]
### What problem does this feature solve?
I wanted to use the `_.debounce()` on the Vue.js, and it works. Unless I called the `cancel()` of it.

#### lodash Version
- v4.17.x

#### Vue.js Version
- v2.5.x

### Example Codes
```
new Vue(
  ...
  methods: {
    debounced: _.debounce(function() {doSomething()}, 1000),
    foo() {
      this.debounced()
    },
    cancelDebounced() {
      this.debounced.cancel()
    }
  }
  ...
)
```

### Guessed Reason
- Inside of the `initMethods` function
- [Code line of lodash](https://github.com/lodash/lodash/blob/master/debounce.js#L206)
- [Code line of Vue.js](https://github.com/vuejs/vue/blob/dev/dist/vue.js#L3655)

### Summary
I solved this issue by implementing feature with different way.
BUT, I think it is quite weird for me, that is reason why I created this issue.
I want to hear your(the commiter, organaizer etc...) opinion.
Do you think it is an issue for Vue.js?

### What does the proposed API look like?
I want you to consider handling methods of Function Object. I'm not sure whether my request is right or not.

**Comment by Justineo** [comment]
This doesn't seem to be a feature request.

If you are reporting a bug, please follow the instruction of the issue helper and provide a minimal reproduction of your problem. Thanks.
