### ISSUE TITLE
Refreshing Edge with checkboxes ignores v-model

### ISSUE THREAD

**Issue by andrewlongmore** [vuejs/vue#9298]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/andrewlongmore/50wL7mdz/821270/](https://jsfiddle.net/andrewlongmore/50wL7mdz/821270/)

### Steps to reproduce
Since you need to refresh in Edge, I suggest you create a .html and .js file from the code in https://jsfiddle.net/andrewlongmore/50wL7mdz/821270/.

### What is expected?
There are three check-boxes, with text "first", "second", "third".  The first two check-boxes are checked, the third one isn't.
The paragraph text shows that the selectedValues array is ["first","second"].
Refreshing the page doesn't change anything.

### What is actually happening?
On FireFox, this is what happens.
On Edge, refreshing the page causes the first two check-boxes to become unchecked.  This happens whether you do F5 or ctrl-F5.  Refreshing the page again causes the first two check-boxes to become checked again.  The paragraph text always shows that the selectedValues array is ["first","second"].

**Comment by posva** [comment]
Checked against latest Edge on Windows and OSX and cannot reproduce. It was probably a bug on Edge that got fixed

**Comment by andrewlongmore** [comment]
@posva please re-open.  I have just checked against latest Edge on Windows and the issue is still there.  To be clear, download test.zip attached above, unzip, and open test.html.  If you refresh the page in Edge, the first and second checkboxes become unchecked.  This should not happen.

**Comment by posva** [comment]
You are probably on an old version of Edge. The bug was present on Edge 15 but it's not on the Insiders build. As I said, it was probably a bug on Edged that got fixed

**Comment by andrewlongmore** [comment]
I am on the May 2019 Windows update, Microsoft Edge 44.18362.1.0, Microsoft EdgeHTML 18.18362, which is the current stable version, and the bug is still present.  However, I can imagine that the bug is fixed in the upcoming Chromium-based release of Edge.
