### ISSUE TITLE
在组件上使用decorator装饰器报错

### ISSUE THREAD

**Issue by NextBoy** [vuejs/vue#9301]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/8zyy211ky0](https://codesandbox.io/s/8zyy211ky0)

### Steps to reproduce
the code
```
export const withLogin = function (Component): any {
  return class ComponentWithLogin extends Component {
  }
}
```
```
<template>
  <div>123{{ login }}</div>
</template>
<script>
  import Vue from 'vue'
  import { withLogin } from '../decorator'
  @withLogin
  class Hello extends Vue {
    login = false
  }
</script>

```

### What is expected?
no error

### What is actually happening?
But it went wrong
```
vue-router.esm.js?8c4f:1897 TypeError: Cannot set property 'render' of undefined
    at normalizeComponent (componentNormalizer.js?2877:24)
    at eval (hello.vue?0739:8)
    at Module../src/views/hello.vue (1.js:59)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Not sure what you are trying to do by extending Vue class but you should check https://github.com/vuejs/vue-class-component
