### ISSUE TITLE
Inconsistent & Boilerplated Framework Approach with Binding Data Between Components

### ISSUE THREAD

**Issue by JonathanDn** [vuejs/vue#9307]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/pp1o41w6x0](https://codesandbox.io/s/pp1o41w6x0)

### Steps to reproduce
1. in App.vue file - create at least a 2-level hirearchy config object named "config" to be binded to the "rating-stars.vue' component. (shown in demo)
2. bind it with v-bind like so --> v-bind="config"
3. Try registering all the props in a flatten manner with defeault values and types
4. experience an error and recommendation to register your nested objects(from config obj) as data / computed properties

### What is expected?
I would expect a built in recursive javascript object flattner that will flat any level of nesting in binded object props and allow me to register all passed properties in one config obj inside the comp being binded to in the same flatten level
- e.g (in comp being binded to) propA propB propC etc... with default values & types

### What is actually happening?
A weird, inconsistent & unnatural way that is recommended by the framework to register some properties of a binded object as props and the others as data / computed.

---
- In my specific use-case I do not want to flatten the object before binding, I have experimented with doing so. But in my use-case I am building a Vue Compnent and I would like to allow the consumer-developer of the component to bind a sole config object that is divided to inner nested objects for example in my use-case a star rating mechanisem, its style property with its inner styles should be registeed like so --> config.style.color.

- I would like the framework to provide a built in way to bind through a nested object with ass many levels as wanted for maximum customization. 

- A possible solution would be to identify if there are nested objects in the binded object --> if so, run a js recursive flat function that will flatten everything so it could be properly registed as props in a consistent way within the binded component.

- Assuming some users of the framework wouldn't want this behavior as a default behavior, or would like to turn it off/on - I would suggest adding a way to toggle between flattening & disabling it - if that would seem a reasonable approach

- Assuming this issue would be accepted, I would love to help with providing a solution to the problem, discuss the trade-offs and help even with working on an other decided solution if so.

**Comment by Justineo** [comment]
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.
```

Vue warns about this not because you are defining a nested object as a prop, but because you are mutating the value a prop. It has nothing to do with flattening stuff. Your problem can be solved just in your component code:

1. Remove all your `style*` props
2. Initialize them in the `data` function with something `setNestedConfigStyles`.

**Comment by JonathanDn** [comment]
@Justineo This is exactly what I am talking about.
In my use-case I would like to allow a user that uses this component to bind the style nested object to the `props `- not to `data `function or `computed` , if I am passing an object of the following structure:
`config: {
        rating: 4.7,
        isIndicatorActive: true,
        starStyle: {
          fullStarColor: "goldenrod",
          emptyStarColor: "gray",
          starWidth: 100,
          starHeight: 100
        }
      }`

It does not seem logical/consistent/normal to me that rating & isIndicatorActive get to be registers as `props` and have default value, type etc.
While the style object and its inner properties have to be registered under `data `/ `computed` , do you see my point?

**Comment by JonathanDn** [comment]
@Justineo If I pass the nested object in `props` the default values do not change to the binded values. So you did not answer my question.

**Comment by Justineo** [comment]
It sounds like you want the ability to recursively define the schema of object prop values. So it's actually a feature request instead of a bug report. Vue's `props` isn't designed to cover this yet so you may need to create a feature request with a proposed API (if you have).

**Comment by JonathanDn** [comment]
I thought so, that this is a "bug in design" or a new feature request - but was not sure what exactly it is so I started by first filing the issue.

Ill create a feature request than and tag you if that alright, could you aid me in better defining it maybe Ill send you the draft via email, what do you suggest? 

- I would love to build a solution for this

**Comment by Justineo** [comment]
Let's just keep the discussion open to the community in the issues :)

**Comment by JonathanDn** [comment]
Alright, I just don't want to write an incorrect issue again - want it to be accurate as possible, anyway Ill write here then.

So About 1) **Title**
Ability to Recursively Define the Schema of Object Prop Values

Tag it as "feature request"

2) **Demo (link to minimal reproduction)**- is the demo i attched here a good enough example for the FR, or should I make a new one where I bind the data and register it in each prop in the binded comp - and show that the default values do not get altered?

* I would love any feedback in the Feature Request I open about the clarity of my message, so please aid me in giving feedback of how I should be clearer :) that would be appreciated
