### ISSUE TITLE
A way to sort an auto-generated object in (double) v-for

### ISSUE THREAD

**Issue by aurimus** [vuejs/vue#9308]
### What problem does this feature solve?
There are two connected problems:

1. In a situation where there is v-for inside v-for loop, in which case computed property cannot be used to sort for the nested lower loop auto-generated object, I want to be able to use something else but a custom method to sort this sub-object.

2.  [Object order is retained by newer browser](https://stackoverflow.com/questions/5467129/sort-javascript-object-by-key) but Vue v-for instead orders the object before render (so the object can't be pre-sorted before v-for)

My thinking is that Vue2 removal of orderBy was premature and more importantly was not replaced by anything usable. [According to Evan](https://stackoverflow.com/a/42829248/2190425):
> There is a special case where you want to compute something using a scope variable that is only available in the template (e.g. a v-for alias), in such cases it's okay to use "helper methods" so that you can compute something by passing it arguments.

But there is no place to put those helper methods afaik

### What does the proposed API look like?
1. I propose using `filters` to both format the view (currently) and be usable for sorting because it's essentially the same function. However I don't know if this is the best, I just know that there is this problem. I am currently using this workaround

```html
<div v-for="o in $options.filters.sortObj(obj)">{{o}}</div>
```
Instead it could be:
```html
<div v-for="o in obj | sortObj">{{o}}</div>
```

2. For objects to retain their sort order in v-for

**Comment by posva** [comment]
Filters were removed and this have been discussed many times already and it looks like you already searched about it.
Regarding the nested v for you can use components with props or something like https://github.com/posva/vue-local-scope

**Comment by aurimus** [comment]
Thanks, I created a bug report since you didn't mention anything about (2) https://github.com/vuejs/vue/issues/9310
