### ISSUE TITLE
vue 使用 jsx 怎么使用 <router-view /> ？

### ISSUE THREAD

**Issue by VanquisherMe** [vuejs/vue#9322]
### What problem does this feature solve?
业务统一由jsx 实现

### What does the proposed API look like?
this.$router.view

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
