### ISSUE TITLE
[feature] Allow unary slot tag

### ISSUE THREAD

**Issue by DominusVilicus** [vuejs/vue#9342]
### What problem does this feature solve?
I'm not sure if this would go against the HTML5 spec, but I think vue should allow `<slot></slot>` to just be `<slot>` or `<slot/>`. Often, users don't want to put any content inside the slot, and it becomes inconvenient to add a closing tag when there's no content inside

### What does the proposed API look like?
```html
<slot>
```

**Comment by thomassjogren** [comment]
@DominusVilicus This is actually already supported in Single File Components. If you are using Vue without build-step, you have to include a closing tag as HTML doesn't allow for custom self-closing tags.

Check out the [Vue.js Style Guide](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended) for more details and examples.

**Comment by yyx990803** [comment]
You can already use `<slot/>` in string templates. It also works for any tag.

In DOM templates it can't work because the way browser parses the content before Vue does.

**Comment by DominusVilicus** [comment]
my bad, I was using `<slot>` instead of `<slot/>`
