### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by AberSheeran** [vuejs/vue#9345]
### Version
2.5.22

### Reproduction link
[https://github.com/ChineseColor/ChineseColor.github.io](https://github.com/ChineseColor/ChineseColor.github.io)

### Steps to reproduce
打开[中国色](https://chinesecolor.github.io/)网站，不断地点击书页，可以重现Bug。

### What is expected?
我期望它在无论多高频率的点击情况下都能正常的运行。

### What is actually happening?
会抛出`TypeError: Cannot read property 'key' of undefined`的结果。

---
这个Bug是因为Vue内部变量还没来得及加载吗？ 希望有人能够解答这个困惑。

另外，我不能去除Key这个属性，因为我需要复用DOM来做到翻页效果。并且就算我去除了Key这个属性，也会出现`TypeError: Cannot read property 'code' of undefined`的问题。

**Comment by posva** [comment]
When opening bug reports please provide boiled down repros.

---

You can also use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by AberSheeran** [comment]
ha? I can't understand your mean. I provide all the code, as well as an environment where bugs can be reproduced. Why are you closing my issue? 
Don't you think the exception thrown by the render function inside Vue is a bug after a piece of correct code has been running for some time?

**Comment by Justineo** [comment]
See https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn#modal

> ##### 重现应当尽量精简
> 
> 有些用户会直接给我们一整个项目的代码，然后希望我们帮忙找出问题所在。此类请求我们通常不予接受，因为：
> 
> * 你对你的项目的代码结构可能已经非常熟悉，但我们并不是。阅读、运行、分析一个完全陌生的项目是极其耗费时间和精力的。
> 
> * 由于涉及了大量业务代码，问题可能是你的代码错误，而不是 Vue 的 bug 所导致的。
> 
> 一个最小化的重现意味着它精确地定位了 bug 本身 - 它应当只包含能够触发 bug 的最少量的代码。你应当尽可能地剔除任何跟该 bug 无关的部分。

**Comment by AberSheeran** [comment]
你看了那个库里的代码？里面仅一个.js文件，仅一个Vue对象，如果说这还不是最小化的重现，那我真的无法给出一个更小的重现环境，因为在此之前，我从未遇见过直接从r函数中抛出的问题。 @Justineo
