### ISSUE TITLE
What do you think of the https://github.com/Meituan-Dianping/mpvue  project? Can the Vue project add a plug-in-like function to improve this requirement?

### ISSUE THREAD

**Issue by vegetaandbulma** [vuejs/vue#9354]
### What problem does this feature solve?
What do you think of the https://github.com/Meituan-Dianping/mpvue  project? Can the Vue project add a plug-in-like function to improve this requirement?

### What does the proposed API look like?
What do you think of the https://github.com/Meituan-Dianping/mpvue  project? Can the Vue project add a plug-in-like function to improve this requirement?

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

BTW. In Vue 3.0 we'll add a custom renderer API so projects like mpvue won't need to fork Vue after that.
