### ISSUE TITLE
Clarify in documentation that "slot-scope" is named "slot" before 2.5.0

### ISSUE THREAD

**Issue by xak2000** [vuejs/vue#9359]
### What problem does this feature solve?
The [documentation](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) about Scoped Slots says:

> In 2.5.0 , `slot-scope` is no longer limited to the `<template>` element, but can instead be used on any element or component in the slot.

But it is not says, that until 2.5.0, `slot-scope` doesn't work at all, even inside `<template>` element. To make it work, It must be `scope` inside `<template>` element.

### What does the proposed API look like?
It will be good to mention in the same warning element in documentation, that `slot-scope` not works until 2.5.0 and `slot` must be used instead.

Something, like:

> Until 2.5.0, `slot-scope` was named `slot` and was limited to the `<template>` element.
> In 2.5.0 , `slot-scope` is no longer limited to the `<template>` element, but can instead be used on any element or component in the slot.

**Comment by posva** [comment]
`slot-scope` was always different from `slot`.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

Also, there is a repo where you can propose changes to doc: https://github.com/vuejs/vuejs.org

**Comment by xak2000** [comment]
No, @posva, you are not right.

`slot` in template element is different from usual `slot` in other elements. That was the reason why it was renamed to `slot-scope` int 2.5.0+.

**Comment by leopiccionia** [comment]
@xak2000 Perhaps you're confusing `slot`, that has existed since Vue slots were introduced, with `scope`, that was replaced by `slot-scope` in 2.5 ([and it's already noted in docs](https://vuejs.org/v2/api/#scope-replaced)).

**Comment by xak2000** [comment]
@leopiccionia Yes, this is what i meant. Sorry for confusion.

`slot-scope` in `<template>` not works until 2.5.0, and `scope` should be used instead.

Sorry.

**Comment by yyx990803** [comment]
Please send a PR to the [vuejs.org repo](https://github.com/vuejs/vuejs.org).

**Comment by xak2000** [comment]
@leopiccionia It's noted in the [API docs only](https://github.com/vuejs/vuejs.org/issues/1223). But [my issue](https://github.com/vuejs/vuejs.org/issues/1955) is about the guide, not API docs.

I'll opened PR. Thanks.
