### ISSUE TITLE
Variable is defined as number but on event v-model changes to string

### ISSUE THREAD

**Issue by k4rz4** [vuejs/vue#9360]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/48r5zeLy/2/](https://jsfiddle.net/48r5zeLy/2/)

### Steps to reproduce
v-model on input field converts variable from number to string.

### What is expected?
For instance i want to send some data to api and i have declared type of item in object as 'Number', should stay as number

### What is actually happening?
Var type is converted to 'String'

**Comment by posva** [comment]
Use the `.number` modifier on `v-model`

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by k4rz4** [comment]
Great! Thanks
