### ISSUE TITLE
Transition not triggering @appear when used as the root of a component with appear attr

### ISSUE THREAD

**Issue by badz0** [vuejs/vue#9364]
### Version
2.5.22

### Reproduction link
[https://codepen.io/bogdan-muranets/pen/ErjOXy](https://codepen.io/bogdan-muranets/pen/ErjOXy)

### Steps to reproduce
Open repro, click on the "show" button and note that "animated on enter" text appeared.

### What is expected?
To see a text "animated on appear" which has to be added by `@appear` hook.

### What is actually happening?
The `@enter` hook is called instead of `@appear`.

---
Important is that `transition` is moved to separate component. Also, everything works as expected if `transition` isn't a root element in a separate component or the component is `functional`.

**Comment by posva** [comment]
From my perspective, the behaviour is not consistent as the appear does trigger if the `transition` element is wrapped with a different element like a `div`

**Comment by yyx990803** [comment]
closed via #9668
