### ISSUE TITLE
Component with extends imported with import() breaks HMR when changing base component

### ISSUE THREAD

**Issue by mrodal** [vuejs/vue#9376]
### Version
2.5.22

### Reproduction link
[Here](https://github.com/mrodal/reported-issues/tree/vue-extended-comp-hmr)

### Steps to reproduce
- Have a Base and Extended component. 
- Extended extends Base
- Import Extended with dynamic import()
- Run site with HMR
- Change Base script

### What is expected?
Extended is rendered

### What is actually happening?
Base is being rendered

---
This doesnt happen with normal `import Extended from 'Extended.vue'`

**Edit:** I take that last thing back, now it seems to be happening with the normal import too

**Comment by posva** [comment]
Hi, this should be openend in vuejs/vue-loader instead. Thanks!
