### ISSUE TITLE
Add possibility to modify the URL in the browser status bar on hovering router-link

### ISSUE THREAD

**Issue by rominf** [vuejs/vue#9378]
### What problem does this feature solve?
I want to create something like a search engine. To count user clicks I use `<router-link>` instead of `<a>`. When the user clicks on a link (let say https://google.com/) Vue Router catches that it looks like an external link and `beforeEnter` hook counts this click and replaces `window.location` to an appropriate value.

The problem is that when the user hovers the link, he sees https://mysite.com/https://google.com/ instead of https://google.com/. I want to fix this.

There is a way to replace an URL, displayed in the status bar, used by Google and other search engines: https://stackoverflow.com/questions/2813648/how-do-google-and-yahoo-replace-the-url-in-the-browser-status-bar

I propose to implement this in `<router-link>` by adding an optional tag `external`.

### What does the proposed API look like?
`<router-link to="https://google.com/" external>Google</router-link>`

Probably, it would be worth to create a separate handler for external links in routes:
```javascipt
const routes = [
  {
    path: '*',
    external: true,
  }
]
```
which will catch all clicks of `<router-link>` with `external` tag and add:
```javascript
beforeEnter(to, from, next) {
  window.location = to.path.slice(1);
}
```
to redirect to external link.

**Comment by posva** [comment]
This is related to vue-router, but hovering it will display the right link. If you want to change it, change the actual url you want to go to

**Comment by rominf** [comment]
@posva, should I open this issue in the vue-router?
You misread my question. I want `<router-link>` to point to the https://mysite.com/https://google.com/ but show https://google.com/ in the browser status bar, as Google does.

**Comment by posva** [comment]
Change the url if you want your link to display a specific link and use an `@click` handler to call `$router.push()` by yourself. You will also have to handle `@click` while ctrl or cmd are clicked to open a link in a new window/tab

**Comment by Garito** [comment]
Sounds to me a very particular need to ask for a change here or in vue-router
am I missunderstanding something?
Sorry if so :)

**Comment by Justineo** [comment]
I think wrapping `<router-link>` in your own link component to implement this feature would be a better choice. And AFAIK Google is replacing the actual link href upon `mousedown`.
