### ISSUE TITLE
Vue整合Cesium开发出现FPS降低，同时内存撑爆的问题，如何解决？

### ISSUE THREAD

**Issue by myhnuhai** [vuejs/vue#9381]
### What problem does this feature solve?
Vue整合Cesium开发出现FPS降低，同时内存撑爆的问题，如何解决？

### What does the proposed API look like?
Vue整合Cesium开发出现FPS降低，同时内存撑爆的问题，如何解决？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
