### ISSUE TITLE
In IE 11 the first input event on a text input is blocked if placeholder is set and the model is initialised

### ISSUE THREAD

**Issue by spectrum128** [vuejs/vue#9383]
### Version
2.5.22

### Reproduction link
[https://jsbin.com/dobagokure/1/edit?html,js,output](https://jsbin.com/dobagokure/1/edit?html,js,output)

### Steps to reproduce
1. Open https://jsbin.com/dobagokure/1/edit?html,js,output in IE 11.

2. Enter a single character in the text input just after 'Hello Vue!'

3. Model will not be updated on the first character input but will be on subsequent inputs

*Note to reproduce a second time you will need to refresh the page.

### What is expected?
When a single character is entered the model should update

### What is actually happening?
The input event is blocked and the model does not update until a second character is entered.

---
I believe it could be related to a previous fix for an issue that IE11 is firing an input event when the placeholder is set:

https://github.com/lovelope/vue/commit/15e8fa59b99890268b9a06ff263a6db131e0aa63

Perhaps it should check if the value is set first before blocking the initial event?

Many Thanks,
Declan

**Comment by posva** [comment]
Related to #7138
