### ISSUE TITLE
Blank in the list in chrome 70+

### ISSUE THREAD

**Issue by luoxixi** [vuejs/vue#9384]
### Version
2.2.2

### Reproduction link
[http://blog.luoxixi.com/wp-content/uploads/2019/01/ertyu-1.gif](http://blog.luoxixi.com/wp-content/uploads/2019/01/ertyu-1.gif)

### Steps to reproduce
I am using vue2.2.2 in the development project. After upgrading the browser to 70  recently, I found that the list in some pages is blank. In fact, the HTML has been rendered, but the page is not displayed. This is a very strange problem. We didn't do any positioning and hierarchical relationships; when I tried to upgrade vue to 2.5 or downgrade the browser to below 69, the problem would automatically disappear, but I can't currently make this change in the project;

### What is expected?
I can't currently make this change in the project;I hope it will display properly.

### What is actually happening?
http://blog.luoxixi.com/wp-content/uploads/2019/01/%E8%AF%95%E5%9B%BE.png;

http://blog.luoxixi.com/wp-content/uploads/2019/01/347.png

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by posva** [comment]
Closing until one is provided

**Comment by luoxixi** [comment]
> 关闭直到提供一个

In fact, it doesn't happen to all pages. I don't know why only some pages exist instead of all. When I try to add a case test at jsfiddle.net, it can't be reproduced. . .

**Comment by luoxixi** [comment]
> 你好
> 
> 感谢您提交此问题！你能不能在jsfiddle.net上提供一个小的复制，所以我们可以调试这个而不试图自己复制它？
> 
> 那将是非常有帮助的，谢谢！

In fact, it doesn't happen to all pages. I don't know why only some pages exist instead of all. When I try to add a case test at jsfiddle.net, it can't be reproduced. . .

**Comment by luoxixi** [comment]
> Hi
> 
> Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`
> 
> That would be very helpful, thanks!

In fact, it doesn't happen to all pages. I don't know why only some pages exist instead of all. When I try to add a case test at jsfiddle.net, it can't be reproduced. . .

**Comment by posva** [comment]
Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions and get community support!

**Comment by Justineo** [comment]
I suspect it's actually a bug of Chrome. You can try in other browsers to confirm it.
