### ISSUE TITLE
使用mouseenter和mouseleave时，鼠标左键规律单击所选元素时，会偶尔触发mouseleave

### ISSUE THREAD

**Issue by ly1989abc** [vuejs/vue#9387]
### Version
2.5.16

### Reproduction link
[https://codepen.io/intotheprogram/pen/ZjxZdg](https://codepen.io/intotheprogram/pen/ZjxZdg)

### Steps to reproduce
首先将鼠标移向Hove Me按钮，然后鼠标左键匀速点击，大约十几次时会触发mouseleave。鼠标重新动一下，才会重新触发mouseenter。

### What is expected?
鼠标点击时，不应触发mouseleave

### What is actually happening?
鼠标点击时，偶尔触发mouseleave

**Comment by yyx990803** [comment]
1. 无法重现
2. Vue 只是添加原生的 event listener，这不太可能是因为 Vue 导致的。

**Comment by ly1989abc** [comment]
> 1. 无法重现
> 2. Vue 只是添加原生的 event listener，这不太可能是因为 Vue 导致的。

您好，我这边找别人试一下，也是可复现的。鼠标移到动Hover Me按钮上，出现Good提示；然后鼠标一直匀速点击，不要太快，中间过程Good会变成Hover Me，也就是触发了mouseleave。请耐心试一下，谢谢

**Comment by ly1989abc** [comment]
@yyx990803 @Justineo 
抱歉，新手不太懂，感谢两位的回答。以下是我的测试结果：

测试1：Vue（2.5.16）
- 浏览器：Google Chrome【70.0.3538.110（正式版本）（64 位）】
- 操作系统：Windows 10 专业版 1709（64位）
- 测试地址：[Vue.js | Mouseover & Mouseleave](https://codepen.io/intotheprogram/pen/ZjxZdg)
- 测试结果：鼠标单击100次时，mouseleave触发**1**次

测试2：Vue（2.5.16）
- 浏览器：Firefox 65.0b12 (64 位)
- 操作系统：Windows 10 专业版 1709（64位）
- 测试地址：[Vue.js | Mouseover & Mouseleave](https://codepen.io/intotheprogram/pen/ZjxZdg)
- 测试结果：鼠标单击100次时，mouseleave触发**0**次

测试3：jQuery（3.3.1）
- 浏览器：Google Chrome【70.0.3538.110（正式版本）（64 位）】
- 操作系统：Windows 10 专业版 1709（64位）
- 测试地址：[jQuery | mouseover&mouseleave](https://codepen.io/ly1989abc/pen/gqLxYM)
- 测试结果：鼠标单击100次时，mouseleave触发**1**次

测试4：jQuery（3.3.1）
- 浏览器：Firefox 65.0b12 (64 位)
- 操作系统：Windows 10 专业版 1709（64位）
- 测试地址：[jQuery | mouseover&mouseleave](https://codepen.io/ly1989abc/pen/gqLxYM)
- 测试结果：鼠标单击100次时，mouseleave触发**0**次
--------
**测试结论**：经测试发现，问题应该是出在谷歌浏览器。
另：刚发现这个问题的时候，触发较频繁，大约十几次会触发一次，现在测试时，100次才触发了1次，不知道是什么原因。让别人帮忙测试时，谷歌浏览器下也触发了mouseleave。
