### ISSUE TITLE
Unnecessary item update with directive

### ISSUE THREAD

**Issue by danyadev** [vuejs/vue#9389]
### Version
2.6.0-beta.2

### Reproduction link
[https://codepen.io/danyadev/pen/QYGmLb](https://codepen.io/danyadev/pen/QYGmLb)

### Steps to reproduce
1) Open the desired item using DevTools
2) Click the button

### What is expected?
The element with the directive does not update

### What is actually happening?
Element with directive updated

---
This happens ONLY when there is something in the component that changes the elements in the DOM.

**Comment by danyadev** [comment]
But this may affect performance ...

**Comment by posva** [comment]
Oh my bad, I read that it wasn't changing. The directive will still be called when updating, you can always save a cache if you need to prevent unnecessary function calls but some directives need to be updated in all cases

**Comment by danyadev** [comment]
Well, I just now continued to try to find the causes of lags in the application when switching to 2.6.0-beta.2 and 2.6.0-beta.1.
I added the line `if (el.innerHTML == binding.value) return;` to the beginning, but this did not help much. I will look for reasons further ...
