### ISSUE TITLE
v-for "Duplicate keys detected"

### ISSUE THREAD

**Issue by duszekmestre** [vuejs/vue#9390]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/hsac4jbq/](https://jsfiddle.net/hsac4jbq/)

### Steps to reproduce
Create two v-for on two different collection within the same parent HTML element.

### What is expected?
:key should be unique in one v-for not on two v-for with same parent HTML element

### What is actually happening?
In attached link I show that when we have two v-for with single parent HTML element on two different collection with similar data I have "Duplicate keys detected".

But when I created the same v-for with different parent HTML element then no error occured.

**Comment by posva** [comment]
This is expected behaviour. They key is for elements/components that can be reused by Vue

**Comment by duszekmestre** [comment]
But do you see that I iterate on two different collections? Two different collections can have similar ids.

**Comment by posva** [comment]
It doesn't matter, the key is set to an element or component. What you are writing is the same as 

```vue
<div key="1"/>
<div key="1"/>
```

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by duszekmestre** [comment]
OK. I understand. So documentation is not precise in this topic. But I understand now.
