### ISSUE TITLE
A better way to listen to events programatically

### ISSUE THREAD

**Issue by szmarczak** [vuejs/vue#9398]
### What problem does this feature solve?
```ts
import WrappedInput from './WrappedInput.vue'; // Assume `WrappedInput` is the example metioned below.

export default WrappedInput.extend({
	created() {
		this.$on('focus', function () {
			console.log('focus'); // Won't show up.
		});
	}
});
```

The way to fix this would be to use a custom `focus` handler like it's done here: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

It gets quite annoying while other events come to play, like `blur`, `click` etc.

### What does the proposed API look like?
Just `this.$on('focus', fn)` without the additional wrappers.

Anyway, there's a workaround here:
```js
this.$el.addEventListener('focus', function () {
	console.log('focus'); // Shows up.
})
```

**Comment by yyx990803** [comment]
this.$on listens to component custom events, not native DOM events. Your "workaround" us the correct way to do it...

**Comment by szmarczak** [comment]
@yyx990803 Thanks for the quick response, I really appreciate it! :)

Maybe it is worth to mention that in the documentation? I was really confused...
If you don't mind, I can send a PR.
