### ISSUE TITLE
Vue version 2.5.22 is missing vue.esm.browser.js in the dist folder.

### ISSUE THREAD

**Issue by Giwayume** [vuejs/vue#9401]
### Version
2.5.22

### Reproduction link
[https://repl.it/repls/CreepyStaticInstitute](https://repl.it/repls/CreepyStaticInstitute)

### Steps to reproduce
```
npm init
npm install vue@2.5.22
```

View the contents of node_modules/vue/dist. The file 'vue.esm.browser.js` is missing.

### What is expected?
'vue.esm.browser.js` should exist, like in version 2.5.21

### What is actually happening?
'vue.esm.browser.js` is missing.

**Comment by Justineo** [comment]
See https://github.com/vuejs/vue/pull/7110#issuecomment-453686795.
