### ISSUE TITLE
Add the ability to launch components in advance, as when using keep-alive, but immediately when you start the application.

### ISSUE THREAD

**Issue by RDMStreet** [vuejs/vue#9410]
### What problem does this feature solve?
I have a SPA consisting of several heavy main sections. And between them there is a transition animation. At the first transition to any section, a hang occurs due to which the animation is twitching. I would like to be able to run these sections at the very beginning in advance and keep them alive.

### What does the proposed API look like?
```html
<keep-alive :always-on="true">
    <router-view/>
</keep-alive>
```

**Comment by posva** [comment]
What you are looking for is not feasible by Vue because keep alive cannot guess all the possibilities to create the components before hand  and keep them alive. It would require you to pass an array of components and their props so Vue can mount them and then deactivate them. This would however make your application lag at the beginning

**Comment by LinusBorg** [comment]
Possibly wrap all of them in a functional component accepting a prop to decide which to show, then use this functional component of all of the routes, but pass a different prop to decide which one to `v-show`:
```javascript
{
  path: '/a',
  component: Wrapper,
  props: () => ({  show: 'a' })
},
{
  path: '/b',
  component: Wrapper,
  props: () => ({  show: 'b' })
}
```
```javascript
// Wrapper.js
import A from './A.vue'
import B from './A.vue'
export default {
  functional: true,
  props: ['show'],
  render: (h, {props}) => {
    const CompA = h(A, { style: { display: props.show === 'a'} })
    const CompB = h(B, { style: { display: props.show === 'b'} })
    return [CompA, CompB]
  }
}
```

Just an idea, not tested.

**Comment by yyx990803** [comment]
Theoretically the best solution to this is some kind of ability to "pre-render trees in the background, using low priority". This is something that Vue 3 will potentially look into, but not necessarily in the way it is proposed here.
