### ISSUE TITLE
Write a Vue plugin that installs components written in Typescript using vue-class-component

### ISSUE THREAD

**Issue by mattsteve** [vuejs/vue#9413]
### What problem does this feature solve?
There doesn't seem to be a way for UI component library authors to write their Vue components in Typescript with the @Component decorator when their compile target is a Vue plugin that's consumed by a 3rd party. It is possible for webpack to transpile these classes into ES5, but in the process of doing so you end up including the Vue source code into the plugin build file itself, which results in 2 instances of Vue running when the component library consumer imports Vue from a CDN on to the page in order to use the plugin (and a bunch of warnings in the console as a result).

### What does the proposed API look like?
Define the component decorator in a way in which the resulting class does not have to extend Vue. Possibly extend a support class such as VueComponent instead. Or make it so that Vue doesn't care that there's 2 instances on the page.

**Comment by yyx990803** [comment]
https://webpack.js.org/configuration/externals/

**Comment by mattsteve** [comment]
That works if Vue is defined first on the page, I guess it's an acceptable solution so long as the script tags aren't async.
