### ISSUE TITLE
v-for class with Symbol.iterator not working properly when return value is modified

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue#9414]
### Version
2.6.0-beta.3

### Reproduction link
[https://jsfiddle.net/vx1ygurm/](https://jsfiddle.net/vx1ygurm/)

### Steps to reproduce
Iterate with v-for on a class with Symbol.iterator (which does something with the returning value). See jsfiddle!

### What is expected?
since 2.6-beta1 it should support iterables in v-for (#8179) d40eb9c, (#8179)

I thought, great, let's try this with my footnote class and get rid of that verbose "getItems()" accessor and directly pass the class with a Symbol.iterator.

### What is actually happening?
But as soon as the values which should be iterated are mutated before they are returned (e.g. sort), it shows the Vue warn:
"You may have an infinite update loop in a component render function."

And the iterator gets called over 100  times.

---
Even worse, if you put this class in a vuex state. Then it complains that it cannot be mutated (even though I don't actually mutate it)

**Comment by yyx990803** [comment]
`.sort` **is** a mutating method, when you call it it mutates the original array.
