### ISSUE TITLE
Action event on loaded component Async

### ISSUE THREAD

**Issue by joaoeudes7** [vuejs/vue#9416]
### What problem does this feature solve?
**Reference:** https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State

**Current Issue:** We do not know when the async component was loaded, with this, the 'Ref' is also not recognized in the 'mounted()' father

### What does the proposed API look like?

**Feature Request:** Prop from 'created' in asynchronous component to go event

```js
const AsyncComponent = () => ({
  // The component to load (should be a Promise)
  component: import('./MyComponent.vue'),
  // A component to use while the async component is loading
  loading: LoadingComponent,
  // A component to use if the load fails
  error: ErrorComponent,
  // Delay before showing the loading component. Default: 200ms.
  delay: 200,
  // The error component will be displayed if a timeout is
  // provided and exceeded. Default: Infinity.
  timeout: 3000,
  created: () => something()
})
```

**Comment by yyx990803** [comment]
If something needs to happen after the component is loaded, it should be placed inside that component. If that doesn't suit your use case you need to provide more context instead of a single sentence that I can barely understand.

**Comment by joaoeudes7** [comment]
Sorry about my English.
I meant that it has no way of knowing when an asynchronous component was loaded.
The parent component does not recognize the role or property of the child component in the `mounted` method because the child component is asynchronous.

Example:
```vue
<template>
  <div>
    <ChildAsync ref="child"/>
  </div>
</template>

<script>
export default {
  name: "Example",
  components: {
    ChildAsync: () => import("./childExample")
  },
  mounted() {
    this.$refs.child.someFunction(); // *ERROR* -> undefined
  }
};
</script>

```

**Comment by yyx990803** [comment]
You can add a listener on the child component:

``` html
<ChildAsync @ready="doSomething"/>
```

Then in the child's `mounted` hook do `this.$emit('ready')`

**Comment by joaoeudes7** [comment]
All right, thank you!

**Comment by akccakcctw** [comment]
I found a cleaner way to do this (without modify child component):
```vue
<ChildAsync @hook:mounted="doSomething"/>
```
