### ISSUE TITLE
Warning when emitting custom event on template

### ISSUE THREAD

**Issue by henriqemalheiros** [vuejs/vue#9418]
### Version
2.6.0

### Reproduction link
[https://github.com/henriqemalheiros/vue-bug-report-event-emit-template](https://github.com/henriqemalheiros/vue-bug-report-event-emit-template)

### Steps to reproduce
- Clone the repo;
- Run `yarn install`;
- Run `yarn run serve`;
- Open `http://localhost:8080/`;
- Open browser console;
- Click on "Click me ($emit on method)";
- "custom click triggered" is printed on the console;
- Click on "Click me ($emit on template)";
- "custom click triggered" is printed on the console;
- "[Vue warn]: Property or method "then" is not defined on the instance but referenced during render." is also printed on the console.

### What is expected?
No warning should be thrown.

### What is actually happening?
A warning is thrown.

---
Maybe related to https://github.com/vuejs/vue/pull/8297.

**Comment by yyx990803** [comment]
Just a note - please avoid build setups when the bug can easily be reproduced using a simple jsfiddle or codepen.

**Comment by henriqemalheiros** [comment]
I tried, but the warning [wasn't reproducible](https://jsfiddle.net/qpbn0cd9/) without a build setup.

**Comment by jvbianchi** [comment]
There is a reproduction in https://github.com/vuejs/vue/issues/9419
