### ISSUE TITLE
Iterative rendering of data elements in computed property 

### ISSUE THREAD

**Issue by sahamnadeem** [vuejs/vue#9420]
### Version
2.6.0

### Reproduction link
[https://kamsham.com](https://kamsham.com)

### Steps to reproduce
If i create an http request in a computed property its it sends the request again and again that slowes down the performance of the framework itself...
And also the computed property does not compute before the system gets fully rendered, this delay should not bs there. And if i use a foreach loop in a computed property to return some specific objections it gives me the same list of objects iteratively and the lost goes on with infinite number or objects in it...  

### What is expected?
I need you to fixe that bug or if m not using it correctly then kindly inform me ghe right way to use it 

### What is actually happening?
If i create an http request in a computed property its it sends the request again and again that slowes down the performance of the framework itself...
And also the computed property does not compute before the system gets fully rendered, this delay should not bs there. And if i use a foreach loop in a computed property to return some specific objections it gives me the same list of objects iteratively and the lost goes on with infinite number or objects in it...

**Comment by yyx990803** [comment]
Please read the issue requirements and provide a valid reproduction.
