### ISSUE TITLE
v-slot broken

### ISSUE THREAD

**Issue by engblh** [vuejs/vue#9428]
Here is how slot is defined: 

            <slot name="dialog-title">
              Confirmation Title
            </slot>

here is how its being used:

      <template v-slot:dialog-title>
        <span>
          {{ this.dialogTitle }}
        </span>
      </template>

this.dialogTitle is local property on SFC. Its giving the error dialogTitle is not defined

**Comment by yyx990803** [comment]
Don't use this inside templates. It's not needed.
