### ISSUE TITLE
v-slot failed to render this.

### ISSUE THREAD

**Issue by engblh** [vuejs/vue#9429]
### Version
2.6.2

### Reproduction link
[https://codepen.io/engblh/pen/LqjqGg](https://codepen.io/engblh/pen/LqjqGg)

### Steps to reproduce
Here is how slot is defined: 

            <slot name="dialog-title">
              Confirmation Title
            </slot>

here is how its being used:

      <template v-slot:dialog-title>
        <span>
          {{ this.dialogTitle }}
        </span>
      </template>

this.dialogTitle is local property on SFC. Its giving the error dialogTitle is not defined

### What is expected?
in previous version (2.5.17), same code was working

### What is actually happening?
this.dialogTitle is local property on SFC. Its giving the error dialogTitle is not defined

**Comment by AlexandreBonaventure** [comment]
If you remove `this` it will work as expected. I don't think it is recommended to use `this` in the template syntax. It was never officially documented

**Comment by yyx990803** [comment]
Never use `this` inside templates.
