### ISSUE TITLE
<tel: xxxxxxxxx>  causing v-bind error

### ISSUE THREAD

**Issue by delta1186** [vuejs/vue#9433]
### Version
2.6.2

### Reproduction link
[https://jsfiddle.net/omfhgs24/](https://jsfiddle.net/omfhgs24/)

### Steps to reproduce
See the jsfiddle.  If the page has a tag of <tel:xxxxxxx> you will get a v-bind error.  <tel: is not even part of the Vue component and I am not sure why it is getting evaluated.

### What is expected?
The page should load with the included <tel:xxx tags

### What is actually happening?
see jsfiddle

---
Hopefully this is something I am overlooking.  I searched the web and wasn't finding anything related.

**Comment by delta1186** [comment]
I should also mention the tel: tag is rendered from a database row of a parsed email so it not something we can easily prevent.

**Comment by tony19** [comment]
Are you trying to use a [`tel:` **URL**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Creating_a_phone_link) (e.g., `<a href="tel:2052222222">Call me</a>`)? I don't believe `<tel:2052222222>` is a valid HTML tag.

**Comment by posva** [comment]
Use `v-pre` on the tag but I don't think you should use it either, it doesn't seem to be valid html

**Comment by delta1186** [comment]
Just to be clear the <tel: tag was auto generated by the email which came from MS Unified Messaging for voicemails. I know that’s not a valid tag. Guess Microsoft does not. Haha. I just ended up using a Laravel attribute mutator to remove those tags from the data. Thanks.
