### ISSUE TITLE
Can't use destructed slot variables on component with v-slot directive

### ISSUE THREAD

**Issue by karudo** [vuejs/vue#9434]
### Version
2.6.2

### Reproduction link
[https://jsfiddle.net/karudo/8u0epjyo/35/](https://jsfiddle.net/karudo/8u0epjyo/35/)

### Steps to reproduce
Run the fiddle

### What is expected?
"foo bar" in output window
No error should occur.

### What is actually happening?
empty output window
errors in console
[Vue warn]: Property or method "firstName" is not defined on the instance but referenced during render
[Vue warn]: Property or method "lastName" is not defined on the instance but referenced during render

---
can't user vars on same component (not on childs)
```
<user v-slot="{firstName, lastName}"
          :first-name="firstName"
          :last-name="lastName"
    />
```
with `slot-scope` parameter it was possible
```
<user slot-scope="{firstName, lastName}"
          :first-name="firstName"
          :last-name="lastName"
/>
```

**Comment by LinusBorg** [comment]
Well that s expecred because in the v-slot example, the user component is the component that's providing the slot props. 

Using them on itself doesn't make sense.

**Comment by posva** [comment]
I think we should add a tip in documentation saying that slot-scope cannot be added on the wrapper component as v-slot. I couldn't find the note there.

@karudo  It's a good opportunity to contribute to Vue Documentation 🙂
