### ISSUE TITLE
New slot syntax does not work with components if no default slot

### ISSUE THREAD

**Issue by karudo** [vuejs/vue#9435]
### Version
2.6.2

### Reproduction link
[https://jsfiddle.net/karudo/8u0epjyo/69/](https://jsfiddle.net/karudo/8u0epjyo/69/)

### Steps to reproduce
Run the fiddle

### What is expected?
`header` and `footer` tags content is presented

### What is actually happening?
only `header` tag content is presented, `footer` tag is empty

---
Looks like new syntax works with `template`, but does not work with components.
however, if the component `card` from example has default slot - everything works well, look the jsfiddle https://jsfiddle.net/karudo/8u0epjyo/70/

**Comment by smolinari** [comment]
Make sure you close all tags in jsfiddle. Self-closing tags don't jive well with it. 

I believe the new v-slot syntax reverts back to enforcing named slots being used in templates elements only. So if true, it's correct behavior. 

From the new docs:

> To provide content to named slots, we can use the slot attribute on a <template> element in the parent:

That might be reworded better as "we need to use the slot attribute on a <template> element in the parent:

https://jsfiddle.net/smolinari/0uzj1pgm/

Scott

**Comment by yyx990803** [comment]
This is expected. When used for named slots, `v-slot` **must** be on a template. This is an intentional restriction to avoid ambiguity, since it can also be used on a component to indicate the component's own slot.
