### ISSUE TITLE
cascade v-slot don't emit change of variables from scope

### ISSUE THREAD

**Issue by tcastelly** [vuejs/vue#9438]
### Version
2.6.2

### Reproduction link
[https://jsfiddle.net/cn09xg4k/](https://jsfiddle.net/cn09xg4k/)

### Steps to reproduce
There is a `card` component with `userName` and `lastName`. Each 200ms these variables are updated.
Between `user` and `card` components there is a wrapper, just to use a slot.

### What is expected?
Variables in `user` component should be refreshed

### What is actually happening?
These two variables are displayed only once and never updated

---
- If I remove the wrapper it works: https://jsfiddle.net/wh1L5c2g/
- If I use the previous syntax (slot/slot-scope) it works: https://jsfiddle.net/9f27h1ad/3/

**Comment by leopiccionia** [comment]
I'm not sure if the current spec allows putting the default slot inside `<template/>`, but it works without it: https://jsfiddle.net/leopiccionia/1097xjws/

**Comment by tcastelly** [comment]
I'm curious to know if spec allows, in fact I can't remove the slot name from my `wrapper` because in my application I've some thing like `header`, `footer`.

https://jsfiddle.net/2d6fc4Lx/

**Comment by leopiccionia** [comment]
It seems to be a bug. Uncomment the fifth line (adding a default slot) and it works: https://jsfiddle.net/leopiccionia/bjr340vo/

**Comment by tcastelly** [comment]
Correct ! :)
