### ISSUE TITLE
Chrome autofill triggers keyup event on render/load

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue#9441]
### Version
2.6.2

### Reproduction link
[https://codepen.io/anon/pen/jdGjZx](https://codepen.io/anon/pen/jdGjZx)

### Steps to reproduce
1) open the codepen
2) fill in username/password and force chrome to save them
3) reload the page
4) chrome will fill in the username/password
5) console.log will show "triggered" twice

### What is expected?
The autofill won't trigger the event listeners (worked in 2.5.22)

### What is actually happening?
chrome autofill triggers the event listeners on render/load

**Comment by Justineo** [comment]
Can't reproduce on my side...What's your Chrome version?

**Comment by jacekkarczmarczyk** [comment]
Confirming on Chrome 72 win10

**Comment by DRoet** [comment]
Using chrome 72.0.3626.81, however I'm also getting the trigger when I select/focus on the input in chrome 71

**Comment by aaaguirrep** [comment]
I have the same issue with a keyup event. I didn't have the issue with 2.5.22 version. The issue is just with chrome, my current chrome version is: 72.0.3626.96 (64 bits) on windows 10. I dont have the issue with firefox.

**Comment by grzegorztomasiak** [comment]
I can confirm the issue too on keyup and keydown. Exists in Vue 2.6.3 and the latest 2.6.5.
It just triggers that event when we click on item in autocomplete in Chrome and Opera. Firefox is fine.

**Comment by nghiepit** [comment]
I have the same issue

**Comment by grzegorztomasiak** [comment]
@yyx990803 Thanks Evan for this fix. Just updated Vue to 2.6.6. and it had fixed the issue but I noticed that autocomplete feature still triggers @keydown.esc="onEsc" event modifier (only with `esc` so far I see).

**Comment by qnp** [comment]
Thanks a lot. Keep up awsome work

**Comment by jwbats** [comment]
I'm currently experiencing this problem with VueJS 2.6.12 on Chrome 89.

Both KeyUp & KeyDown will fire on Chrome's autofill of email & password inputs.

KeyPress, thankfully, does not.
