### ISSUE TITLE
bind object to select options in custom component

### ISSUE THREAD

**Issue by tanner0101** [vuejs/vue#9442]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/2u3p5ec0/19](https://jsfiddle.net/2u3p5ec0/19)

### Steps to reproduce
Choose the same option in both select boxes.

### What is expected?
The result in each paragraph below is the same.

### What is actually happening?
The result for the custom box is [object Object] string instead of the actual object.

---
I would like to be able to re-create Vue.js's ability to bind objects to a select component in my custom component.

**Comment by yyx990803** [comment]
You will need to implement this yourself. This feature is only implemented for `v-model` on native `<select>` elements.

**Comment by tanner0101** [comment]
@yyx990803 ok, that makes sense, thanks! Could you point me to where Vue implements this on native select elements?
