### ISSUE TITLE
Junk props in $scopedSlots

### ISSUE THREAD

**Issue by IlyaKhD** [vuejs/vue#9443]
### Version
2.6.0

### Reproduction link
[https://codesandbox.io/s/5xx3jz48qn](https://codesandbox.io/s/5xx3jz48qn)

### Steps to reproduce
- follow the codesandbox link attached
- open the App.vue
- see lines 13, and 19
- see console output

### What is expected?
$scopedSlots contains slot functions only (or empty if there are no slots at all)

### What is actually happening?
$scopedSlots has **_normalized** and **$stable** fields

---
If these special props added to the $scopedSlots by intention - where can I find documentation on them?

**Comment by yyx990803** [comment]
Do you have a legit case where you need to dynamically inspect slots being passed in? These are internal/special flags used for optimizations.

**Comment by IlyaKhD** [comment]
Iterating through slots is used for integrating with 3rd-party libraries (here is an [example](https://github.com/DevExpress/devextreme-vue#custom-templates) of how slots are used to define 3rd-party templates)

So, as I got it - these props will remain and are for internal use only, right?

**Comment by yyx990803** [comment]
Yes, if you have control over the implementation you can simply ignore anything that is not a function.

**Comment by IlyaKhD** [comment]
Ok
Thank you for clarification.
