### ISSUE TITLE
Dynamic props not working with slots after 2.6x update.

### ISSUE THREAD

**Issue by DotNetGit** [vuejs/vue#9444]
### Version
2.6.2

### Reproduction link
no link

### Steps to reproduce
Create component with slot, add dynamic prop "itemName" to slot like this:

<slot :[itemName]="item" name="item-content" />

### What is expected?
Dynamic prop is binded to the slot.

### What is actually happening?
Dynamic prop is not binded to the slot.

---
I used the syntax below for a long time until the update 2.62:

`<slot :[itemName]="item" name="item-content" />`

After the update it is not working, I had to change it across all projects to the following:

`<slot v-bind="{ [itemName]: item }" name="item-content" />`

But the docs from [here](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0003-dynamic-directive-arguments.md#detailed-design) told that the first snippet has a valid syntax.

What is wrong with dynamic props or slots or maybe with them both or just this syntax do not work anymore?

Regards.

**Comment by posva** [comment]
Take the time to provide a boiled down repro thank you!

**Comment by yyx990803** [comment]
Able to reproduce... funny that this even worked in 2.5.x (when it shouldn't) and somehow broke in 2.6 (when it should)!

**Comment by DotNetGit** [comment]
@yyx990803 , Thanks a lot.
