### ISSUE TITLE
Re-throwing error within Vue.config.errorHanlder results in error thrown twice

### ISSUE THREAD

**Issue by brillout** [vuejs/vue#9445]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/h92m7pad/2/](https://jsfiddle.net/h92m7pad/2/)

### Steps to reproduce
 - Run the app
 - Look at the console

### What is expected?
The error is thrown once

### What is actually happening?
It is thrown twice

**Comment by yyx990803** [comment]
This is expected: it's possible that your code in the globalHandler itself has errors, and that error is thus reported as a potential error in your error handling code.

If you already have an error handler, you should not be throwing the error.

**Comment by brillout** [comment]
Yes, errors in the global handler should be thrown, but only once and not twice. Or am I missing something?

> If you already have an error handler, you should not be throwing the error.

If I don't throw the error then the error get's completely swallowed: https://jsfiddle.net/d6uqhk0r/

I'm wondering, why does Vue throw the error twice? Seems unnecessary form my point of view.

(Thanks for Vue, it's super impressive how much you achieved.)

**Comment by yyx990803** [comment]
This is now fixed - note that to avoid the error being logged twice, you need to throw the original error instead of `throw new Error(err)`.

**Comment by brillout** [comment]
Awesome thanks
