### ISSUE TITLE
cn.vuejs.org response blank page.

### ISSUE THREAD

**Issue by StephenChips** [vuejs/vue#9453]
### Version
2.6.3

### Reproduction link
[https://cn.vuejs.org/v2/guide/class-and-style.html](https://cn.vuejs.org/v2/guide/class-and-style.html)

### Steps to reproduce
Just to go the web page.

### What is expected?
Fix it.

### What is actually happening?
I cannot visit documents.

**Comment by yyx990803** [comment]
It's working.
