### ISSUE TITLE
nextTick and eventPropogation Issue

### ISSUE THREAD

**Issue by robertmoura** [vuejs/vue#9455]
### Version
2.6.3

### Reproduction link
[https://codesandbox.io/s/qx992r339j](https://codesandbox.io/s/qx992r339j)

### Steps to reproduce
Click the open modal button.

### What is expected?
The text should display. When you click anywhere other than the text it should be removed.

### What is actually happening?
The text flashes on and then off.

---
The nextTick edge case described in https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd doesn't seem to be completely fixed.

**Comment by posva** [comment]
as a workaround you can use `.stop` to stop the propagation of the event

**Comment by LinusBorg** [comment]
or add the listener later:
```javascript
    open() {
      this.showing = true
      window.setTimeout(() => {
        document.addEventListener('click', this.blur)
      }, 0)
    },
```

**Comment by yyx990803** [comment]
This is is because the handler is added manually by you, not by Vue. There is nothing we can do about this case.
