### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by inherithandle** [vuejs/vue#9456]
### Version
2.6.3

### Reproduction link
[https://github.com/inherithandle/vue-webpack-simple-project](https://github.com/inherithandle/vue-webpack-simple-project)

### Steps to reproduce
1. git clone https://github.com/inherithandle/vue-webpack-simple-project
2. run "npm install"
2. run "npm run build"
3. open ./dist/index.html

### What is expected?
I expected index.html to be rendered successfully.

### What is actually happening?
I get the error: "SyntaxError: invalid range in character class"

---
I think it is similar to the issue #2291.

**Comment by inherithandle** [comment]
it turns out there was a problem with `import` statement. not a bug.

**Comment by aizquier** [comment]
I have the same problem. The bug seems to have been introduced since the version 2.6.0.

**Comment by Justineo** [comment]
It seems to be caused by Terser.

You can workaround this as follows for now:

```js
const path = require('path');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  entry: './src/js/vue-first.js',
  output: {
    filename: 'todo.js',
    path: path.resolve(__dirname, 'dist')
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        cache: true,
        parallel: true,
        sourceMap: true,
        terserOptions: {
          output: {
            ascii_only: true // <- Add this to keep the regex valid
          }
        }
      }),
    ],
  }
};
```

**Comment by posva** [comment]
I'm taking a look at this

**Comment by posva** [comment]
I couldn't spend more time on this for now but it's weird since using raw terser with the regex at https://github.com/vuejs/vue/blob/dev/src/core/util/lang.js#L8, and more specifically `new RegExp('[^\uF900-\uFDCF]')` yields a valid result (the same we have in project with the CLI). It's as if the problem was with webpack. We cannot really expand the regex as it would be too much either

**Comment by sodatea** [comment]
It works with http, but not `file:///`

**Comment by sodatea** [comment]
Or with `charset="utf8"`.
So the issue is browser's auto charset detection.
Not sure how to fix it.

**Comment by sodatea** [comment]
So, as I tested out on https://xem.github.io/terser-online/, unicode sequences in strings (e.g. `'\uF900-\uFDCF'`) are compressed into single characters, while those in regexps aren't (e.g. `/\uF900-\uFDCF/`). It'll be an easy fix.

**Comment by dandelion1000** [comment]
this may be node version, just me try run  build or run dev in localhost, is ok, however,when i build it in server, just throw npm audit fix, Invalid regular expression ... so upgrade node --version ,is build success
