### ISSUE TITLE
Form submitted even though button type="button"

### ISSUE THREAD

**Issue by petternordholm** [vuejs/vue#9461]
### Version
2.6.3

### Reproduction link
[https://codesandbox.io/s/2zr485mw50](https://codesandbox.io/s/2zr485mw50)

### Steps to reproduce
Click on the button. The "click count" text should be 1 but instead it is 11. So, the form is submitted even though the original button has type="button"

### What is expected?
The form should not be submitted. Instead, only the button should change.

### What is actually happening?
Form is submitted. I guess it is due to the DOM button being reused.

---
The work-around is simple. Just add prevent.stop to the click event handler.

**Comment by Justineo** [comment]
Actually it's resulted from Vue's element reuse mechanism. When you have same type of elements in different `v-if` branches, you need to add a `key` to each of them.

**Comment by petternordholm** [comment]
@Justineo Good point. Adding stop.prevent also fixes the problem.

But, I think that this needs to be documented in the changelog since the behavior has changed since previous vue release (at least latest 2.5) and finding out why our wizards started to dis-function was non-trivial.

**Comment by Justineo** [comment]
I believe it's related to this: https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

**Comment by yyx990803** [comment]
This has been documented in the changelog under important internal changes, which links to the gist mentioned above with details. It's difficult to specify the exact cases this can affect though.

In your case, the event reaches the form element AFTER the button type has changed. Honestly not sure if there's anything we can do about this.

**Comment by petternordholm** [comment]
Thanks @yyx990803 . My example is kind of a corner case. So, I will close this issue. If someone runs into the same problem as we did, it is documented here together with several different workarounds.
