### ISSUE TITLE
Props description

### ISSUE THREAD

**Issue by SuperDJ** [vuejs/vue#9465]
### What problem does this feature solve?
I think it would be nice to be able to have some sort of description or documentation index for the props. This index can than also be displayed in the vue devtools. I think it would help other users using already build components. For example when using a framework like vuetify so they don't have to go back to the documentation of what a prop does.

### What does the proposed API look like?
    props: {
       message: {
        type: String,
        description: "Represents the the message of the notification"
      } 
    }

**Comment by SuperDJ** [comment]
#7186

**Comment by yyx990803** [comment]
I'll close this as a duplicate. Personally I don't think this should be a part of the runtime API since this will bloat your bundle size.

**Comment by tohagan** [comment]
But wouldn't a 'description' just get removed by the .vue webpack builder?
