### ISSUE TITLE
Resolve injected properties after the props initialization

### ISSUE THREAD

**Issue by smellyshovel** [vuejs/vue#9471]
### What problem does this feature solve?
It's [said in the API reference](https://vuejs.org/v2/api/#provide-inject) that below the version 2.2.1 injected properties actually *were* resolved after the props initialization. So it seems like I'm asking for a regression.

I tried to find what formed the basis for making such a decision (to resolve them before props and data) but I haven't been able to find any related issue.

I have a component `<tree-view>` that renders another component called `<tree-item>` inside. The `tree-item` may itself recursively render one or more `tree-view`s.

The `tree-view` accepts a number of options that I pass to it as props (let it be a sole option called "mode" for the sake of brevity):

```html
<tree-view
    mode="folders"
>
    ...
</tree-view>
```

The `tree-view` accepts it as a prop:

```javascript
props: {
    mode: {
        default: "all",
        validator: ...
    }
}
```

And I want to provide it to all the nested `tree-view`'s, so that I don't have to pass this option to the nested `tree-item` so that *only from there* it can be passed to the nested `tree-view`. But I can't do so because **the props since 2.2.1 are initialized after the injected properties**.

### What does the proposed API look like?
That is what I'm trying to achieve

```javascript
props: {
    mode: {
        default: "all"
    }
},

provide() {
    return {
        /*
            This one works OK, this.mode is taken from the `props`
        */
        mode: this.mode
    }
},

inject: {
    mode: {
        /*
            But this one doesn't since the `props` are not yet initialized
        */
        default: this.mode
    }
}
```

My point is that the root `tree-view` isn't provided with the `mode` injected property (because it's the root one obviously) so the warning "Injection "mode" not found" is thrown for each root `tree-view`. But all the nested `tree-view`'s *are* provided with the injected property "mode" so the provided value is taken instead of the `default` one.

May be (I'm not sure, just a guess) the proposed API will need to like something like

```javascript
inject() {
}
```

That's that the `injected` property can accept a function as its value instead of just an array or an object.

**Comment by LinusBorg** [comment]
> I tried to find what formed the basis for making such a decision (to resolve them before props and data) but I haven't been able to find any related issue.

The change was made to allow access to the injected values when `data()` runs - kind of the inverse of what you want to do:
```javascript
inject: {
  injectedMode: {
    from: 'mode',
    default: null
  }
},
data() {
  return {
    mode: this.injectedMode || 'default'
  }
}
```
Wouldn't be the above be a workable solution for your situation

Even if we did follow your wish for this regression, your code would still not work, because 

1. you can't have a prop and an inject called `mode`. The names have to be unique
2. `inject` would have to be a function for the default to work, which is also not supported right now (but maybe *that's* a good idea.)

Sidenote: the trigger for the change back in 2.2.1 was that you already could do the same with props and `data()` before, and the behaviour should be the same: 

```javascript
props: {
  mode: 'String'
}
data() {
  return {
    myMode: this.mode || 'default'
  }
}
```

**Comment by smellyshovel** [comment]
> The change was made to allow access to the injected values when `data()` runs - kind of the inverse of what you want to do

Well, seems like we have 2 different approaches each of which is suitable for some purpose. Though I'm not the one who decides which one must be chosen as default.

> Wouldn't be the above be a workable solution for your situation

If this is the question then I'm gonna check it out and will let you know later.

> 1. you can't have a prop and an inject called `mode`. The names have to be unique

Seems like you're wrong here. I **do** have the-same-named props and injects and everything works just fine (though perhaps not intended considering your words)

> 2. `inject` would have to be a function for the default to work, which is also not supported right now (but maybe _that's_ a good idea.)

I believe so as well because it might also help to standartize the API a bit. For example it might be hard to a newcomer (like me) to remember which one of `provide` and `inject` supports `function` as a value and which one doesn't.

### Some other thoughts

Now my code looks as follows:

```javascript
props: {
    mode: {
        type: String,
        default: "all",
        validator: value => ~["all", "folders", "files"].indexOf(value)
     }
},

provide() {
    return {
        mode: this.mode
    }
},

 inject: {
    mode: "mode"
},
```

And it actually works just great (even despite the fact that `injected` and `props` can't be named the same, as you say). But here's the only thing that drives me wild: the Vue warning in the console saying that injection for `mode` not found.

So considering that my code is working (though perhaps it isn't that nice and clean) can we just remove this stupid warning? I can open a new issue if needed.

My point is that we don't have warnings if a component expects some prop but it doesn't receive it, so why not do the same with injected? Even if the component expects (or rather it can accept) an injected doesn't yet mean that the injected will be provided.

So still my point is that if it's impossible (not desirable) to regress to the previous behavior then may be just remove these warnings?

Thank you for your response. Appreciate.

**Comment by smellyshovel** [comment]
And answering your question:

```javascript
inject: {
  injectedMode: {
    from: 'mode',
    default: null
  }
},
data() {
  return {
    mode: this.injectedMode || 'default'
  }
}

// Wouldn't be the above be a workable solution for your situation
```

**No**. As I said in the opening post I pass the `mode` as a props because it's an option for a current instance of `tree-view`. I have multiple `tree-view`s on the page and some of them receive one value for the `mode` and others - another.

I can't have "class"-wide default set in the data. Each instance must have its own which is provided to it as the prop.

**Comment by LinusBorg** [comment]
> I can't have "class"-wide default set in the data. Each instance must have its own which is provided to it as the prop.

Then use the prop instead of a static default: 

```javascript
data() {
  return {
    combinedMode: this.injectedMode || this.mode
  }
}
```

It's not as pretty as what you are asking, but it works. 

So not a good reason to introduce a breaking change evil rough a regression.

**Comment by smellyshovel** [comment]
@LinusBorg I prefer my current solution more tbh. But can consider yours as well (though - let's face it - it's ugly :face_with_head_bandage:).

Totally agree with "not a good reason to introduce a breaking change" though.

Anyway, what about warning messages then?

**Comment by LinusBorg** [comment]
> I assume that's because you use either / or. If you tried to have an inject *and* option ally overwrite it with a prop of the same name, that would not work - it's just logic: what should `this.mode` refer to, the prop or the inject? It can't be both.

**Comment by smellyshovel** [comment]
@LinusBorg just tried to provide both the prop *and* the injected - works just fine. Injected overwrites the prop :confused:

Let 's sum everything up:
1. My current approach works just fine. The root `tree-view` instance takes for the `mode` the value of the prop and it also provides the-same-named `mode` property (which points to `this.mode` (taken from the props)) for all its descendants so the nested (recursive) `tree-view`s could take `mode` from `injected` rather than from `props`.

1. The only thing that bothers me is the console warnings for the unresolved injected `mode` for the root `tree-view` (which is just OK since it's taken from the prop instead as I described above).

1. I totally agree that we don't have to introduce a breaking change cause seems like there're workarounds.

So there's the only question left: should we disable warnings for the cases when an injected property is expected but isn't provided? And if we should then should I open a new issue for it?

Thank you for your patience.

**Comment by LinusBorg** [comment]
> just tried to provide both the prop and the injected - works just fine. Injected overwrites the prop
Hats what I'm saying though. The inject is static - oncd it's added, it overrides the prop, wether that has a value or not. 

So there's no way to override an injected value with a (more specific, because local to this one component instance) prop of the same name.

**Comment by smellyshovel** [comment]
@LinusBorg can't default it to `null` because it must default to the `mode` prop :laughing:

OK, looks like nothing's gonna come of all it. Just gonna pass props from `tree-view` to `tree-item` to `tree-view` again as I did initially.

Anyway, thank you for your time.

**Comment by LinusBorg** [comment]
can't default it to null because it must default to the mode prop 

If the inject is `null`, use the prop. 

It's in my initial example.

**Comment by smellyshovel** [comment]
@LinusBorg 
```javascript
inject: {
    mode: {
        default: null || this.mode
    }
},
```

> Uncaught TypeError: Cannot read property 'mode' of undefined

That's why I need to be able to access props in injected.

Or otherwise I just don't understand what are you trying to say. The component is recursive. It must either take the `mode` value from the outside (in a form of prop) or take it from the injected if the prop isn't provided (i.e. when the component is rendered recursively).

`tree-view` (the root one) `provide`s the `mode` that is taken from the `props` to all the nested `tree-view`s. All the nested `tree-view`s use the injected `mode` that is `provide`d by the root `tree-view`. But the initial `mode` that's being `provide`d to the descendants must be taken from the `props`. But it can't be taken from there because (see the issue).

Totally confused by the misunderstanding between us.

**Comment by smellyshovel** [comment]
@LinusBorg I've finally made a simple [demo](https://jsfiddle.net/5qrue186/13/). You may need to click run multiple times so the tree would contain sub-trees.

It can be seen from the demo (if you open the console) that the `mode` is nicely passed to all the nested `tree-view`s, but the warning is thrown for the root one.

It can also be seen that the injected takes precedance over the props (take a look at the line 40).

**Comment by LinusBorg** [comment]
```javascript
props: ['mode'],
inject: {
  injectedMode: {
    from: 'mode',
    default: null
  }
},
data() {
  return {
    mode: this.injectedMode || this.mode
  }
}

```

I posted this already, but in two pieces, essentially. Above you find the whole thing. 

Default the inject to `null`, then construct a local data (or computed) from either her injected or, (if that's null) the prop. 

Result: no warnings, like  it want to.

**Comment by smellyshovel** [comment]
@LinusBorg **Yes**, finally it works! Though there's the error in your code: the prop must be of another name (bacause it can't be named as the data property). So I changed the prop name to be `propMode` and it actually does finally work! Thank you!

Btw, have you considered my demo? I guess it's much cleaner, except for the warning.
