### ISSUE TITLE
v-model doesn't always bind when using v-if

### ISSUE THREAD

**Issue by srchulo** [vuejs/vue#9472]
### Version
2.6.4

### Reproduction link
[https://jsfiddle.net/mu4q63db/1/](https://jsfiddle.net/mu4q63db/1/)

### Steps to reproduce
1. Select a period radio button
2. Hit Monthly and Daily back and forth
3. Sometimes maybe select a period radio button again

### What is expected?
the v-model for period should always select a radio button when being rendered

### What is actually happening?
Sometimes, no radio button will be selected even when the corresponding v-model variable (period_month) still has its previous value.

---
This is reproducible, but sometimes it can take a few clicks to get it to happen.

**Comment by Justineo** [comment]
This happens because of Vue's element reuse mechanism. You should add a unique `key` to each `v-if` branch.

/cc @chrisvfritz I think we really need some extra clarification on this topic in the docs (https://github.com/vuejs/vuejs.org/issues/1248).

**Comment by srchulo** [comment]
Thanks for letting me know. Unfortunately key doesn't seem to work on `<template>` or [vue-fragment](https://github.com/y-nk/vue-fragment) (I actually don't want a `div` around the content). At least now I know what's going on :)

**Comment by Justineo** [comment]
You don't have to bind `key` to a `<template>`. You only need `key`s when there are several stateful node sharing the same element/component type and an actual parent node (not `<template>`) and `v-if`/`v-for` may compare and rearrange them.

**Comment by srchulo** [comment]
Sorry if this isn't the right place for support, but I appreciate the follow up. If you don't mind, are you suggesting I put `v-if` on every element? In this case it would be `v-if` on six separate elements:


```
        <label><input type="radio" name="period_day" value="7" v-model="period_day">1 Wk</label>
        <label><input type="radio" name="period_day" value="14" v-model="period_day">2 Wks</label>
        <label><input type="radio" name="period_day" value="21" v-model="period_day">3 Wks</label>
```

And a different `v-if` condition here:

```
        <label><input type="radio" name="period_month" value="12" v-model="period_month">12 Mos</label>
        <label><input type="radio" name="period_month" value="6" v-model="period_month">6 Mos</label>
        <label><input type="radio" name="period_month" value="3" v-model="period_month">3 Mos</label>
```

I was hoping to wrap them both in a parent element so I only needed a `v-if` and a `v-else`, but maybe six different `v-if`s is correct here?

**Comment by srchulo** [comment]
In this situation the state also seems lost, so I guess I would need a key on each of them?

**Comment by Justineo** [comment]
`key`s are essential for elements/components who have their own local states so that Vue can distinguish them. In your case it seems that you can use `v-for` to reduce duplication.

**Comment by srchulo** [comment]
Sorry-- last question if you don't mind. Do you mean by storing the values such as `12`, `6`, `3`, in an array and then producing the html that way? I appreciate the help!
