### ISSUE TITLE
Deactive throw error when property not exists

### ISSUE THREAD

**Issue by metalfox6383** [vuejs/vue#9476]
### What problem does this feature solve?
Have the possibility of deactive the throw error in console when I use a property that not exists in data.

When execute in a navigator, the template render stops, even in jsfiddle, that not happen.
And in console throw an error "message2 is not defined".

https://jsfiddle.net/dzpLu0a2/

Some times, I get data from another servers and its structure is dynamic and is practical ignore missing information.

### What does the proposed API look like?
Have the possibility of deactive the throw error in console and stops render when I use a property or method that not exists in the object. Maybe like this:

```
let qwe = new Vue({
    //...
    omitErrorInTemplate: true,
    //...
})
```

**Comment by posva** [comment]
every property used in the template *must* be defined. You can however access data properties through `$data` like `$data.message2` and that would not throw an error

**Comment by metalfox6383** [comment]
Thanks!!!
