### ISSUE TITLE
Support namespaced events as Vue.prototype.$emit("evt:ns") / $on("evt:ns") / $off("evt:ns")

### ISSUE THREAD

**Issue by altmind** [vuejs/vue#9477]
### What problem does this feature solve?
Currently, you need to preserve locally the callback used in $on to propertly clean the event handler in view destroyed.

This is inconvenient if you dont want to save/expose the handler and prefer to use anonymous handler function.

```
    function onSidebarSaveEvent(){ /* this... */ }
    export default {
        created() {
            this.$root.$on("params-edit-sidebar-save", (arg) => {
                onSidebarSaveEvent.call(this);
            });
        }
		destroyed() {
			this.$off("params-edit-sidebar-save", /* no handle to unbind? */)
        },
}
```

I propose to pick the same convention jquery used for on()/off() - event names are namespaced so you can give the event handler name and unbind this specific name. 

on("click.thatNamespace") / off("click.thatNamespace")

the $emit("click") still triggers all on("click.*")  handlers. multiple namespaces are supported. http://api.jquery.com/on/#event-names

The choice of namespace separator is arbitrary - can use dot(already used by modifiers?) or colon.

### What does the proposed API look like?
Vue.prototype.$emit("event") to emit an event - no changes

Vue.prototype.$on("event:namespace") to attached namespaced handler. namespaces are optional, multiple allowed?.

Vue.prototype.$off("event:namespace") to remove namespaced handler (no explicit handler mention is required)

**Comment by posva** [comment]
the handler is still optional when removing event listeners. If you are namespacing it will remove all those events anyway.
If you want something more advanced for a bus event, you could use a more complex bus event too

**Comment by altmind** [comment]
> the handler is still optional when removing event listeners.

this removes all the handlers. in the case of this.$root - this removes the handlers even for the other components.

can you please give this feature request more consideration that just "we have it, if you want more - dont use vuejs" ?

**Comment by posva** [comment]
If you want it on the `$root`, you are using it as a Bus event, in which case, if you need more advanced features, you should use a proper Event Bus that fits your needs, but it's outside of Vue's scope

**Comment by louisameline** [comment]
I have written this library for anyone is interested: https://github.com/louisameline/vue-nsel

**Comment by xianshenglu** [comment]
Actually, you could do it by vue event bus as long as your team set a event naming notations. For example, `$emit(scopeName+':event-name')`. Though it's not a good idea. You could choose another lib like `eventemitter3`.
