### ISSUE TITLE
Restore state issue from external object (I'm saving the sate on my window object)

### ISSUE THREAD

**Issue by SoroTrestal** [vuejs/vue#9483]
### Version
2.6.6

### Reproduction link
[https://codesandbox.io/s/0qzn8pkykn](https://codesandbox.io/s/0qzn8pkykn)

### Steps to reproduce
I'm storing the state in this example on my window object, the reason is because we have popups which can be opened from our webapp (and therefor vue will reload and my store will reload, and my state will be cleared).

You can't really test it in the codesandbox because of the origin blocking (i'm calling window.opener to access my manager).

In the vue version of 2.5.5 this was working fine: vue and vuex reloaded, and my factory function which I used to restore my state would pull in the state object of my manager. (in my code example I have a user object in my state, and I print out the object in the component)
 
However if I try it with the version of 2.6.6 when the state is received, it just maps [object Object] instead of the property user.
(although the members of the object still exists).

This happend only when I use an object, if I use a numeric/string/bool value it does actually works.

My apologies for incorrect logging of this issue, it his hard for me to find topics about this particular case.

Thank you in advance

Regards.

### What is expected?
I should be able to save my state (customs object) out of the vuex store because i'm using popup to open up windows, the names should always be the same.

### What is actually happening?
property names are being mapped and renamed to [object Object] instead of the original property name

**Comment by posva** [comment]
This really looks more like a support question than an issue, so I will close it and remind you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

I still tried to give it a look but I don't get very well what you are saying. If you provide the steps to reproduce the problem you are facing, that would help others help you.

**Comment by SoroTrestal** [comment]
Ok thank you, then I will ask there.
This was working fine untill I updated to the latest vue version. So something must have  changed internally. And not something I am doing wrong. 

Regards

**Comment by SoroTrestal** [comment]
> Ok thank you, then I will ask there.
> This was working fine untill I updated to the latest vue version. So something must have changed internally. And not something I am doing wrong.
> 
> Regards

The issue is fixed when I put my object in an array in my state object.

```
this.state = {
            counter: 0,
            user: [{
                firstName: "foo",
                lastName: "bar"
            }]
        }
```
