### ISSUE TITLE
mac 按键码不生效

### ISSUE THREAD

**Issue by weijiyang** [vuejs/vue#9486]
### Version
2.5.22

### Reproduction link
[https://cn.vuejs.org/v2/guide/events.html#%E6%8C%89%E9%94%AE%E7%A0%81](https://cn.vuejs.org/v2/guide/events.html#%E6%8C%89%E9%94%AE%E7%A0%81)

### Steps to reproduce

<div @click.ctrl="doSomething">Do something</div> 无法生效

### What is expected?
应该是需要长按ctrl 再点击然后执行doSomething

### What is actually happening?
 但是mac只是弹出系统弹窗 类似鼠标右键出来的系统弹窗

**Comment by Justineo** [comment]
Please provide a valid reproduction. Thanks.
