### ISSUE TITLE
console.log() doesn't show accurate line number

### ISSUE THREAD

**Issue by Even-Lau** [vuejs/vue#9493]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mz/](https://jsfiddle.net/chrisvfritz/50wL7mz/)

### Steps to reproduce
no description

### What is expected?
no description

### What is actually happening?
no description

---
ig. I call log funccion at line 30 in my IDE,but  the debugger shows at line 25

**Comment by Even-Lau** [comment]
![image](https://user-images.githubusercontent.com/23427420/52769749-2f51c500-306c-11e9-9f2d-8e09d06fbdbc.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
