### ISSUE TITLE
Complex Recursive Problems

### ISSUE THREAD

**Issue by wuyaoxing** [vuejs/vue#9495]
### Version
2.6.6

### Reproduction link
[https://github.com/wuyaoxing/vue-question](https://github.com/wuyaoxing/vue-question)

### Steps to reproduce
**重现**

clone代码，在本地运行，打开控制台即有报错。

**相关文件**

1. 路由 `/test` ，组件在 `views/Test.vue`。
2. 递归组件 `components/Recurision.vue`。
3. 问题组件 `components/Question.vue`。

**问题**

在递归组件  `Recurision.vue` 中渲染 `Question.vue`，同时又在 `Question.vue`中渲染 `Recurision.vue`，递归未正确解析。

错误提示 未注册 Recurision component ，但是已经在 `Question.vue` 中注册过了。

### What is expected?
正确解析递归

### What is actually happening?
复杂递归解析错误

**Comment by Justineo** [comment]
See [“组件之间的循环引用”](https://cn.vuejs.org/v2/guide/components-edge-cases.html#%E7%BB%84%E4%BB%B6%E4%B9%8B%E9%97%B4%E7%9A%84%E5%BE%AA%E7%8E%AF%E5%BC%95%E7%94%A8).
