### ISSUE TITLE
Provide onInvalidate to register callbacks to call when Watcher gets updated (invalidated)

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#9497]
### What problem does this feature solve?
Sometimes inside a Vue reactive context (`Watcher`) you have to read data from an external source. You might have to manage resource consumption of that external source so a way to know when is current has been notified of an update in a dependency is useful because you could cancel the external source. If current watcher is already pending a run there is no point in waiting for an external source to notify as well.

I have encountered this problem when I was implementing a [reactive time formatting functions](https://www.npmjs.com/package/@tozd/vue-format-time). In that case I setup a timeout until the next update to the formatted string (if currently timestamp is displayed as `1 hour ago` the next update is in one hour to display `2 hours ago`). But if something else triggers an update (like timestmap changing in the source) there is no point in that timeout to still be around. So ideally, that timeout should be cleared. But there is no way for that currently.

I could implement this with a reactive data source which I would modify every second and then in the formatting function use the data source  to compute the formatted string. But that would be very inefficient because it would rerun that formatting function every second when it would have to be rerun only in an hour. I could design it so that every formatting call registers its own data source which is updated only at a particular interval, but managing that would be very complex because it would not really be at regular intervals but the interval changes (for example, when string gets changed from `59 minutes ago` to `1 hour ago`).

### What does the proposed API look like?
I would suggest `Watcher` gets a concept of `invalidated` state. That state would be set to `true` on the first `update()` on the watcher and reset back to `false` on the first next `get()`. If `update()` is called multiple times before `get()` is called, watcher continues to be in `invalidated==true` state.

Having that concept, I would suggest `Vue.util.onInvalidate(callback)` function which would register a callback for the current watcher context (`Dep.target`). That callback would be called when watcher gets invalidated (the first time  `update()` is called). If during `onInvalidate` is called on a watcher which is already invalidated, the callback would be called immediately.

Any `callback` is called only once. You have to re-register them by calling `onInvalidate` again if you want to get it called again.

Moreover, on watcher teardown, any pending `onInvalidate` callbacks would be called as well.

I have implemented this API inside [this package](https://www.npmjs.com/package/@tozd/vue-observer-utils), but I would prefer if it was added to the official API.

**Comment by yyx990803** [comment]
I think this is easier to just let the watcher callback return a function to be called on invalidation.

**Comment by mitar** [comment]
Can you elaborate? Not sure if I get your idea.

**Comment by yyx990803** [comment]
e.g.
``` js
this.$watch('foo', value => {
  const token = doSomethingAsync()
  return () => {
    // invalidated
    token.cancel()
  }
})
```

**Comment by mitar** [comment]
I see. So that would be an extension of API that returned callback can be used to invalidate and it would be called by the `Watcher`. I think this cold work, but it is very simplistic and hard to compose. If I have to cancel something deep inside `doSomethingAsync` I would have to propagate it all over to the top for be able to return. This makes it hard to compose reactive functions/data sources which I believe is one of the main advantages of this reactive approach. It gets similar to callback hell problem, no?

**Comment by mitar** [comment]
One other problem with the approach of returning an "invalidation callback" is that it is really hard to extend this in the future. If you want to go this roue maybe returning `{onInvalidate: () => token.cancel()}` would be better.

**Comment by yyx990803** [comment]
I would avoid providing an overly complicated API just so that we can cater to cases where the majority of users probably won't ever encounter, especially when you've managed to implement it in userland. If you believe the API you are proposing does solve a common problem that the return callback API cannot deal with, I'd recommend writing a proper [RFC](https://github.com/vuejs/rfcs) for it.

**Comment by mitar** [comment]
> I would avoid providing an overly complicated API just so that we can cater to cases where the majority of users probably won't ever encounter, especially when you've managed to implement it in userland.

I managed to implement it by monkey-patching Vue. I do not think this is very nice.

**Comment by yyx990803** [comment]
It's not - will probably be in the next minor
