### ISSUE TITLE
Computed property "post" was assigned to but it has no setter.

### ISSUE THREAD

**Issue by bosens-China** [vuejs/vue#9498]
### Version
2.5.21

### Reproduction link
[https://codesandbox.io/s/r7rn9j75vn](https://codesandbox.io/s/r7rn9j75vn)

### Steps to reproduce
I've mixed in a computational property post globally, but this property seems to conflict. Modifying the post will cause the code to need to be modified again. I want to know what's the right way to do it.

### What is expected?
Not in conflict with the attributes I defined

### What is actually happening?
[Vue warn]: Computed property "post" was assigned to but it has no setter.

found in

---> <AjaxUploader>

       <Upload>

         <AUpload>

           <ACol>

             <ARow>

               <AFormItem>

                 <AForm>

                   <App> at /src/App.vue

                     <Root>

**Comment by Justineo** [comment]
It is an expected behavior. You need to ensure you don't have naming conflicts yourself. eg. prefixing your global mixin.
