### ISSUE TITLE
Vue.observable on an array does not really work

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#9499]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/9L5ymbv7/](https://jsfiddle.net/9L5ymbv7/)

### Steps to reproduce
If I do `const todos = Vue.observable([]);` and try to use it inside reactive context, it does not really work. For example, observing the length of the `todos` does not trigger re-run if I push to `todos`.

### What is expected?
That observed array would be fully reactive.

### What is actually happening?
There is no reactivity.

**Comment by Justineo** [comment]
`Vue.observable` accepts an object, like what `data` functions return.

See https://vuejs.org/v2/api/#Vue-observable.

**Comment by mitar** [comment]
Ehm, arrays are objects, no?

Should I make a feature request then for arrays to be supported as well?

**Comment by Justineo** [comment]
> Ehm, arrays are objects, no?

Technically they are. But in Vue's API docs `Object` basically refers to plain object.

**Comment by mitar** [comment]
I opened feature request: #9500

**Comment by cotin18** [comment]
@Justineo just do like this: 

`window.state = Vue.observable({
	arr: []
});`
or 
`const state = Vue.observable({
	arr: []
});`

state.arr.push('test');

Works like a charm for me :)
