### ISSUE TITLE
Make it possible to teardown a $watch when immediate is set

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#9501]
### What problem does this feature solve?
I use the following pattern to wait for a condition to hold:

```js
const unwatch = this.$watch(function () {
  return this.queue.find((element) => element.shown === false);
}, function (newValue, oldValue) {
  unwatch();

  // There is an element in the queue with shown === false.
});
```

The problem is that this pattern is not possible to use if I also want callback to be called if the condition holds already when $watch is called. This is done by setting `immediate` to `true`. But then `unwatch` is not yet set because `$watch` has not returned.

I could be checking if the condition holds before creating `$watch` but this makes the code more complicated and in parts duplicated.

### What does the proposed API look like?
In Meteor's Tracker this is solved by providing access to current computation as an argument to the callback function. Maybe Vue could do the same and provide `unwatch` as the third argument to the callback `(newValue, oldValue, unwatch)`.

**Comment by posva** [comment]
If you use `immediate` there is no point in using a watcher that you want to run once as it will be called right away, so instead call the function yourself. That would be way more straight forward 🙂

**Comment by mitar** [comment]
Yes, but I do not know if I have to use the watcher or not. The code becomes much simpler if I can always call the watcher.

**Comment by mitar** [comment]
I think this is much cleaner:

```js
this.$watch(function () {
  return this.queue.find((element) => element.shown === false);
}, function (newValue, oldValue, unwatch) {
  unwatch();

  // There is an element in the queue with shown === false.
}, {
  immediate: true,
});
```

Then this (which is currently required):

```js
function getElement() {
  return this.queue.find((element) => element.shown === false);
}

function doSomethingWithElement(element) {
  // There is an element in the queue with shown === false.
}

const element = getElement();
if (element) {
  doSomethingWithElement(element);
}
else {
  const unwatch = this.$watch(function () {
    return getElement();
  }, function (newValue, oldValue) {
    unwatch();

    doSomethingWithElement(newValue);
  });
}
```

**Comment by mitar** [comment]
@posva I see that I made a mistake in the original code snippet. Please check it again (there was a missing `if` in the callback).

**Comment by LinusBorg** [comment]
Sure it would be cleaner, but in your proposed better version you have he `unwatch` function apper out of nowhere.

In other words: the current API won't allow to insert it in any way. And we won't break the API.

We also won't increase the API with a new API for such an edge case.

**Comment by mitar** [comment]
What do you mean out of nowhere? It would be a third argument to the callback. And this API change is completely backwards compatible. No breaking of API happens here?

**Comment by mitar** [comment]
The implementation is also very easy. Currently there is:

```js
    const watcher = new Watcher(vm, expOrFn, cb, options)
    if (options.immediate) {
      try {
        cb.call(vm, watcher.value)
      } catch (error) {
        handleError(error, vm, `callback for immediate watcher "${watcher.expression}"`)
      }
    }
    return function unwatchFn () {
      watcher.teardown()
    }
```

And in my proposal would be:

```js
    const watcher = new Watcher(vm, expOrFn, cb, options)
    function unwatchFn () {
      watcher.teardown()
    }
    if (options.immediate) {
      try {
        cb.call(vm, watcher.value, undefined, unwatchFn)
      } catch (error) {
        handleError(error, vm, `callback for immediate watcher "${watcher.expression}"`)
      }
    }
    return unwatchFn
```

Where is this breaking any API anywhere?

**Comment by mitar** [comment]
Also, without this change, `expOrFn` has to be called twice. Once to check if it holds to or to not create `$watch`, and if it does not hold, then is called again by `$watch`, unnecessarily.

**Comment by Glandos** [comment]
I have to say that I was hit with the same issue. Now my code looks like:
```typescript
        const condition = () => vxm.isOk(vxm.cameraPaths.paths) && this.sequences.length > 0
        if (condition()) {
          // See https://github.com/vuejs/vue/issues/9501
          this.setNextCameras(true)
        } else {
          const unwatch = this.$watch(condition, (allLoaded, oldLoaded) => {
            this.setNextCameras(allLoaded, oldLoaded, unwatch)
          })
        }
 ```
And it's not really self-explaining on why I must execute the condition manually first. **Extending** the API of the watch function should break it, as mentionned.

**Comment by nietonfir** [comment]
Came across the same issue. Ironically, in Vue 3.0.11 `immediate: true` works, but only for the first component creation. On subsequent component creations the same code fails with "vue unwatch is not a function Proxy.unwatch.$watch.immediate":

```javascript
  computed: {
    ...mapState(["toBeWatchedArray"]),
  },

  created() {
    if (this.toBeWatchedArray.length) {
      this.doSomething();
    } else {
      const unwatch = this.$watch(
        () => this.toBeWatchedArray,
        (newValue) => {
          if (newValue.length) {
            this.doSomething();

            unwatch();
          }
        },
        // see https://github.com/vuejs/vue/issues/9501 on why immediate does not work
        // { immediate: true }
      );
    }
  },
```
