### ISSUE TITLE
Error in execution of function repeat$1 (str, n) when n < 0

### ISSUE THREAD

**Issue by spmbt** [vuejs/vue#9504]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/spmbt/6f489mdr/11/](https://jsfiddle.net/spmbt/6f489mdr/11/)

### Steps to reproduce
Run function repeat$1 (str, n)
in vue-template-compiler/build.js or vue-template-compiler/browser.js
with negative second parameter, for example, -1. Executing will fails with "RangeError: Invalid string length".

In some build of bundles (I built big application on the CentOS Linux 7 with nodeJs v/10.7, but same build on the desktop Ubuntu 18.04 give OK) negative parameter is present in this minimized package. I'm not investigate causes. This effect give white list in browser due to this error.

### What is expected?
No errors

### What is actually happening?
RangeError: Invalid string length

---
I fix this bug by code

function repeat$1 (str, n) {
  var result = '';
  while (true) { // eslint-disable-line
    // if (n & 1) { result  = str; }
    // n >>>= 1;
    // if (n <= 0) { break }
    if(str.length >280 || (n && (result  = str), (n >>>= 1) <= 0)) break;
    str  = str;
  }
  return result
}

If you run this function with 2nd negative parameter, it will execute without errors (maybe, constant 280 need change to another).

**Comment by posva** [comment]
Please provide a real problem that showcases the error, not just running the function with a parameter that shouldn't be passed

**Comment by spmbt** [comment]
(Sorry I lose bit operator '&' in example, this is better: https://jsfiddle.net/spmbt/6f489mdr/16/ )
[posva]: real problem is deploy of big e-shop (bundle is 1.5 MB) on the remote server. I may not give access to command line with start of 'npm run build', but this error is caused really if I open a page of this shop (test version). I found similar [description of same problem here](https://ru.stackoverflow.com/questions/944084/%d0%9e%d1%88%d0%b8%d0%b1%d0%ba%d0%b0-%d0%bf%d1%80%d0%b8-%d1%81%d0%be%d0%b7%d0%b4%d0%b0%d0%bd%d0%b8%d0%b8-vue-%d0%bf%d1%80%d0%b8%d0%bb%d0%be%d0%b6%d0%b5%d0%bd%d0%b8%d1%8f/945266#945266) (in Russian) which posted 2 days ago. I show this error in versions 2.6.6 and 2.5.17 some days ago.

But, as I wrote, deploy on the my local comp with Ubuntu and with same NodeJS not get error.

**Comment by spmbt** [comment]
@posva : 
I write conditional breakpoint in the obfuscated bundle code:
    if(g < 0) debugger;
and stop execution when parameter g (length) was negated, before error. View screenshot, please:
![breakpoint before error](https://habrastorage.org/webt/ex/ti/ok/extioktjju1dgspojjthyjyik8q.png)

**Comment by joelworsham** [comment]
I'm also getting this error all of the sudden

**Comment by yyx990803** [comment]
This is handled in 7a8de91cd, but I'm more interested about the source template that eventually led to a negative repeat length...

**Comment by jacekkarczmarczyk** [comment]
Not sure if this is the same issue, but the error message appears in this codepen https://codepen.io/anon/pen/LqKpQL?editors=1000

**Comment by machack666** [comment]
I had this same issue; it turned out to be related to using a keyword ("super") as the variable name in a `v-for` loop; i.e., ```<ul v-for="super in supersets">...</ul>```.

**Comment by AeonFr** [comment]
I'm having this error and my template is the simplest stuff there is... I can't wrapp my head against the issue...

I posted the related code in this stackoverflow question: https://stackoverflow.com/questions/55705330/invalid-string-length-at-repeat1-vuejs

**Comment by machack666** [comment]
Yes, any sort of syntax error (keyword usage etc) reports as this instead of a more specific message. It would be nice to be able to report syntax errors inside attributes.

**Comment by ivankarpey** [comment]
Also, get this issue. But unfortunately for me after updating Vue js to the latest version - now page just completely stuck in some endless cycle until chrome eventually doesn't kill it.
