### ISSUE TITLE
Hyphenation of camelCase doesn't work (as intended) with consecutive Capitals

### ISSUE THREAD

**Issue by schwarmco** [vuejs/vue#9505]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/rpnh58zx/](https://jsfiddle.net/rpnh58zx/)

### Steps to reproduce
When defining a Prop with consecutive uppercase letters (e.g.: labelHTML, shadowDOM, customerID)

### What is expected?
when i want to give it to a component, i expected it to work like this:
```<component label-html="html" customer-id="1">```

### What is actually happening?
it's required to split by each capital letter, like this:
```<component label-h-t-m-l="html" customer-i-d="1">```

---
I'm working with Vue-Bootstrap right now, which seems to have this problem with it's "table" component (https://bootstrap-vue.js.org/docs/components/table)

The corresponding function sits here: 
https://github.com/vuejs/vue/blob/0948d999f2fddf9f90991956493f976273c5da1f/src/shared/util.js#L167-L170

**Comment by sirlancelot** [comment]
It is working as intended. Converting camelCase to kebab-case (or hyphenating) works by putting a hyphen before capital letters. The identifiers `labelHTML`, `shadowDOM`, and `customerID` are not camcelCase.

**Comment by sirlancelot** [comment]
It looks like Bootstrap is improperly defining props, I added a comment to the repo explaining and linking back to here.

**Comment by schwarmco** [comment]
thanks for that @sirlancelot

**Comment by yyx990803** [comment]
They are converted from kebab-case to camelCase, not the other way around. Based on the kebab-case `label-html` there is no way to tell you expect `HTML` to be all in uppercase.
