### ISSUE TITLE
Is Vue filter support in JSX and Typescript?

### ISSUE THREAD

**Issue by chiaweilee** [vuejs/vue#9507]
### What problem does this feature solve?
Use Vue filter with JSX in Typescript.

### What does the proposed API look like?
Is Vue filter work in JSX and Typescript(both exsit)?

**Comment by yyx990803** [comment]
There's no concept of "filter" in JSX. Just use a function.

**Comment by Kasopej** [comment]
Just in case someone checks here for info:
I believe there is support for this now
Just use `this.$options.filters["yourFilterName"]`

Thanks, vue team!
