### ISSUE TITLE
Vue.config.errorHandler called twice when I return a rejected Promise from a handler of a component event

### ISSUE THREAD

**Issue by jfgodoy** [vuejs/vue#9511]
### Version
2.6.6

### Reproduction link
[https://codepen.io/anon/pen/qgQYra?editors=1011](https://codepen.io/anon/pen/qgQYra?editors=1011)

### Steps to reproduce
The problem seems to happen when I handle an event emitted from a component and return a rejected promise. To see the problem in action, open the codepen link, click the button and you will see in the console two logs of the same error, which means the Vue.config.errorHandler was called twice.

### What is expected?
I expect the errrorHandler called once.

### What is actually happening?
the errorHandler function is called twice.

**Comment by marcus-hiles** [comment]
@jfgodoy try using the async keyword with the promise, and lets see if it works for you. 
I have another alternative if it doesn't work though

**Comment by jfgodoy** [comment]
hi @marcus-hiles, with async I have the same problem. Only a synchronous throw works
