### ISSUE TITLE
vue.js for循环里用组件，怎么通过props给子组件传值

### ISSUE THREAD

**Issue by antiai1** [vuejs/vue#9513]
### Version
2.6.2

### Reproduction link
[Hhttps://www.jianshu.com/p/df61c04c97f6)

### Steps to reproduce
NULL

### What is expected?
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自定义指令</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <script src="js/flexible.js"></script>
    <link rel="stylesheet" href="./css/index.css">
</head>
<body>
<div id="app">
    <div class="questions">
        <div v-for="(item,index) in qtArr">
            <question :qtObj="item"></question>
        </div>
    </div>
    
    <handler :page="page"></handler>
</div>
<script src="js/vue.min.js"></script>
<script>
    // component handler
    Vue.component('handler', {
        props: {
            page: {
                type: Number,
                required: true
            }
        },
        template: `
            <div class="handler">
            <button v-if="this.currentPage !== 1">上一页</button>
             <button>重置</button>
            <button v-if="this.currentPage !== 3">下一页</button>
    </div>
        `,
        data() {
            return {
                currentPage: this.page,
            }
        },
    })
    //question component
    Vue.component('question', {
        props:{
            qtObj:{
                type:String,
                required: true
            }
        },
        template: `
            <div class="qt">

            </div>
        `,
        data() {
            return {
                dataObj: this.qtObj
            }
        },
        mounted(){
            console.log(this.qtObj);  //打印出来一直是undefined 请大神指教
        }

    })
    var app = new Vue({
        el: '#app',
        data: {
            page: 1,
            qtArr: [
                {
                    num: 1,
                    type: 'radio',
                    title: '请问你的性别是？',
                    options: ["男", "女"],
                    name: 'sex',
                },
                {
                    num: 2,
                    type: 'checkbox',
                    title: '你喜欢的水果有哪些？',
                    options: ["apple", "pear", "banner", "strawberry "],
                    name: 'Fruit'
                },
                {
                    num: 3,
                    type: 'text',
                    title: '简单介绍一下你自己吧!',
                    options: [],
                    name: 'intro'
                }
            ],

        },

    })
</script>
</body>
</html>

### What is actually happening?
question 组件中通过props传递进来的值是undefined

**Comment by Justineo** [comment]
请阅读 issue helper 最上面的“在你开始之前……”说明，谢谢。

> 其次，Vue 的 issue 列表只接受 bug 报告或是新功能请求 (feature requests)。这意味着**我们不接受用法问题**。如果你开的 issue 不符合规定，它将会被**立刻关闭**。

Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
