### ISSUE TITLE
nested components rerender issue

### ISSUE THREAD

**Issue by askart** [vuejs/vue#9520]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/pjyj620q97?module=%2Fsrc%2FApp.vue](https://codesandbox.io/s/pjyj620q97?module=%2Fsrc%2FApp.vue)

### Steps to reproduce
1st table is troublesome, 2nd table is expected behavior. toggle checkboxes in select (Columns). in 1st table columns from a to e is ok except c. by clicking c1 or c2 or c3 column e will disappear.

### What is expected?
if you click c1 then c1 should disappear

### What is actually happening?
by clicking c1 disappears e

---
i've searched and read about HOCs in vue over the internet (github, stackoverflow, forum.vuejs.org, etc.), found nothing that can help solve this issue and decided to create this issue.
got implementation of HOC from https://github.com/vuejs/vue/issues/6201#issuecomment-317762527.
I don't know how to implement actual v-if inside render, I've read about it in the documentation render section. But I think the problem is that component renders as component and as a slot inside component.

**Comment by yyx990803** [comment]
I'm sorry but your reproduction is far from **minimal**. We have no context on how you wrote your code, it not practical for us to dig into all these implementation details to figure out what is wrong for you, since the error may be in **your** code. Please try to strip away anything that is not related and reopen with an actual minimal reproduction.

**Comment by askart** [comment]
ok

**Comment by askart** [comment]
> I'm sorry but your reproduction is far from **minimal**. We have no context on how you wrote your code, it is simply not practical for us to dig into all these implementation details to figure out what is wrong for you, since the error may be in **your** code. Please try to strip away anything that is not related and reopen with an actual minimal reproduction.

https://github.com/vuejs/vue/issues/9522#issue-411733063
added minimal reproduction
