### ISSUE TITLE
Vue 2.6 breaks Cleave.js formatting when v-model is used

### ISSUE THREAD

**Issue by lfkwtz** [vuejs/vue#9521]
### Version
2.6.6

### Reproduction link
[https://codepen.io/lfkwtz/pen/GzzjmW](https://codepen.io/lfkwtz/pen/GzzjmW)

### Steps to reproduce
1. See last input auto-formatting
2. Update codepen to Vue 2.6x
3. See last input no longer auto-formatting

### What is expected?
The attached codepen comes from https://buefy.org/extensions/cleavejs

In Vue 2.5.x and below, the last example (where the input utilizes v-model) works as expected.

### What is actually happening?
When you update the codepen to Vue 2.6x, that input no longer auto-formats

**Comment by posva** [comment]
hi, this is too much for a repro. Please remove any external dependency when reporting a bug.
Since it was working in 2.5, this is probably related to nextTick changes (explained in releases notes) maybe checking that helps you find the source of your problem

**Comment by yxngl** [comment]
@lfkwtz Solved here https://github.com/buefy/buefy/issues/1246
