### ISSUE TITLE
Nested components update/rerender issue

### ISSUE THREAD

**Issue by askart** [vuejs/vue#9522]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/00v11z0z3n?module=%2Fsrc%2Fbase-table-column.js](https://codesandbox.io/s/00v11z0z3n?module=%2Fsrc%2Fbase-table-column.js)

### Steps to reproduce
Toggle checkboxes to see changes. In 1st table columns from a to e is ok except c. by clicking c1 or c2 column e will disappear.

### What is expected?
if you click c1 then c1 should disappear

### What is actually happening?
by clicking c1 disappears e

---
Added link to minimal reproduction.
html code inside App.vue, main logic occurs in base-table-column.js file

i've searched and read about HOCs in vue over the internet (github, stackoverflow, forum.vuejs.org, etc.), found nothing that can help solve this issue and decided to create this issue.
got implementation of HOC from [#6201 (comment)](https://github.com/vuejs/vue/issues/6201#issuecomment-317762527).
I don't know how to implement actual v-if inside render, I've read about it in the documentation render section. But I think the problem is that component renders as component and as a slot inside component.

**Comment by posva** [comment]
Hi, please make sure to provide boiled down repro when reporting bugs, with no external libs. thank you

**Comment by askart** [comment]
> Hi, please make sure to provide boiled down repro when reporting bugs, with no external libs. thank you

i need to remove element-ui and create table and table-column components myself, or something similar?
if i create my own components without external libs just vue and simple <table> <tr> <th> <td>,
will it be ok?

**Comment by posva** [comment]
something as boiled down as possible meant to show the nested component problem you are referring. Please, don't copy paste element-ui source code though

**Comment by askart** [comment]
> something as boiled down as possible meant to show the nested component problem you are referring. Please, don't copy paste element-ui source code though

https://codesandbox.io/s/6l083pqk1n?module=%2Fsrc%2Fbase-row.vue
if the simple component i've made is ok, then there is no issue with vue, but element-ui
