### ISSUE TITLE
Korean official website doesn't redirect to the corresponding english page when switching to English from Korean.

### ISSUE THREAD

**Issue by inherithandle** [vuejs/vue#9524]
### Version
2.6.6

### Reproduction link
[https://kr.vuejs.org/v2/guide/index.html](https://kr.vuejs.org/v2/guide/index.html)

### Steps to reproduce
1. Go to https://kr.vuejs.org/v2/guide/index.html
2. Click on "다른 언어로 보기" on the upper right of the page.
3. See the unexpected result.

### What is expected?
I expected to get the corresponding english page.

### What is actually happening?
it redirected me to https://vuejs.org/

---
switching from English to Korean works, not vice versa.

**Comment by Justineo** [comment]
Please file an issue at [vuejs-kr/kr.vuejs.org](https://github.com/vuejs-kr/kr.vuejs.org). This repo is for the core lib only. Thanks!
