### ISSUE TITLE
When execute app.$destroy(), the dom element of app.$el didn't be removed

### ISSUE THREAD

**Issue by skyline0705** [vuejs/vue#9529]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/xayduwf0/](https://jsfiddle.net/xayduwf0/)

### Steps to reproduce
open the link and run

### What is expected?
there should no html in the result window

### What is actually happening?
the result shows all the rendered html

---
I'm not sure it is by design or a bug……
The scene I can think of the use of is, if someone use Vue.js in an progressive web page, they maybe need to control the app by themself, like call $destroy by them self, now if they want to clean the document, they need to execute
```javasscript
app.$destroy();
app.$el.parentNode.removeChild(app.$el);
```

**Comment by posva** [comment]
Duplicate of #3534

**Comment by skyline0705** [comment]
Got it, Thanks~
