### ISSUE TITLE
How to use namespace defined at 'd.ts' in '.vue'?

### ISSUE THREAD

**Issue by seonggukchoi** [vuejs/vue#9532]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/m9zk5njm3x](https://codesandbox.io/s/m9zk5njm3x)

### Steps to reproduce
```typescript
// src/components/my-component.vue

<template>
...
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component()
export default class MyComponent extends Vue {
	private foo: MyComponent.MyEnumType;
//                   ^^^^^^^^^^^
//                   'MyComponent' only refers to a type, but is being used as a namespace here.
	constructor() { super(); }
}
</script>
```

```typescript
// src/types/components/my-component.d.ts

declare namespace MyComponent {
	type MyEnumType: "foo" | "bar";
}
```

```json
{
	...
	"typeRoots": ["node_modules/@types", "src/types"]
	...
}
```

### What is expected?
Has to not exist error.

### What is actually happening?
'MyComponent' only refers to a type, but is being used as a namespace here.

---
I'm using Vue.js 2 with TypeScript 3.3 at work, I experience a problem while defining namespace.

`'MyComponent' only refers to a type, but is being used as a namespace here.`
I can't understand why occurrences this problem.
If I separating part of TypeScript to `.ts`, then not exists any errors in there, but I want to use a first way.

**Comment by posva** [comment]
Using it in vue file should be the same as using it in a ts file. I'm closing this because it's a question, but pinging @ktsn in case he wants to chime in to answer.
