### ISSUE TITLE
When switching between two of the same components with slot using v-else, I get a render error

### ISSUE THREAD

**Issue by cypressious** [vuejs/vue#9534]
### Version
2.6.6

### Reproduction link
[https://codesandbox.io/s/4l3wn6r3nx](https://codesandbox.io/s/4l3wn6r3nx)

### Steps to reproduce
Check the checkbox to trigger the error

### What is expected?
The value "2" should be rendered

### What is actually happening?
```
[Vue warn]: Error in render: "TypeError: item.a is undefined"

found in

---> <HelloWorld> at /src/components/HelloWorld.vue
       <App> at /src/App.vue
         <Root>
```

and "1" is still being rendered.

---
I have two of the same components next to each other and switch between them using `v-else`.

This used to work in earlier versions of Vue but in 2.6.6 I get this unexpected render error. It appears as if component 1 is being rendered with the properties of component 2.

**Comment by LinusBorg** [comment]
Since you didn't key the two component instances, the same instance will be re-used, and that's fine in itself.

But it seems that the optimizations for (scoped) slots that we introduced in 2.6 have an unwanted side-effect here, namely that also the scoped slot is re-used / cached.
