### ISSUE TITLE
Named Slot in Render Function not Registering

### ISSUE THREAD

**Issue by robertmoura** [vuejs/vue#9540]
### Version
2.6.6

### Reproduction link
[https://codesandbox.io/s/wkyokr97m7](https://codesandbox.io/s/wkyokr97m7)

### Steps to reproduce
Don't need to do anything.

### What is expected?
The content slot text should be displayed ("This is a content slot").

### What is actually happening?
The content slot is not being recognized ("No content slot" is displayed).

**Comment by f3ltron** [comment]
Your slot is actually undefined

**Comment by LinusBorg** [comment]
That seems to be a bug on codesandbox, they probably use an older version of themplate-compiler to compile vue files?

It works on jsfiddle, for example: https://jsfiddle.net/Linusborg/os2qeup9/

**Comment by skyline0705** [comment]
It seems to be a bug  on codesandbox……

**Comment by f3ltron** [comment]
@LinusBorg they use vue template compiler 2.5.21 so yeah :S

**Comment by tony19** [comment]
Related: https://github.com/CompuIves/codesandbox-client/issues/1545

**Comment by robertmoura** [comment]
@LinusBorg Yeah the code sandbox used an old version of the vue-template-compiler. Though I'm still getting the same issue with the latest version.

**Comment by yyx990803** [comment]
@robertmoura cannot reproduce (btw you don't need CodeSandbox for this case): https://jsfiddle.net/yyx990803/q963m1t8/
