### ISSUE TITLE
dynamic attribute names are not recognized as described in the Vue.js docs

### ISSUE THREAD

**Issue by procyclinsur** [vuejs/vue#9548]
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/ferpzqvx/2/](https://jsfiddle.net/ferpzqvx/2/)

### Steps to reproduce
* Create a Vue app with data property `attrName` with a value of `href`
* Create an `<a>` HTML tag with the following attribute bind `v-bind:[attrName]=some-link`

### What is expected?
I was expecting the DOM to produce output similar to the following, as per expectations set [here](https://vuejs.org/v2/guide/syntax.html#Dynamic-Arguments)
```html
<a href="www.google.com">Website</a>
```
OR

I could expect that the documents should be fixed so as to not show a camel case example.

### What is actually happening?
The above will fail with the console saying that `attrname` does not exist. 

`attrname` in lowecase being nowhere in the code written.

**Comment by posva** [comment]
Damn, this should be indeed updated in docs.we cannot use va el case variables in html templates, we should reflect that via a note. It will only works on Vue files and strong templates. Could you check if the issue exists on vuejs.org repo and if it doesn't, open a new one please? If you feel like creating a pull request instead that would also be good

**Comment by procyclinsur** [comment]
@posva thank you, and yes, I will check vuejs.org repo and open a new issue there if the issue is not fixed there.

**Comment by yyx990803** [comment]
Added a note in https://github.com/vuejs/vuejs.org/commit/50589c52d89e06a4ee14c950d550c6f235125940
