### ISSUE TITLE
v-model radio button issue

### ISSUE THREAD

**Issue by DenysPavlenko** [vuejs/vue#9556]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/DenysPavlenko/7x8fw41n/](https://jsfiddle.net/DenysPavlenko/7x8fw41n/)

### Steps to reproduce
I am trying to get a current value of checked radio button in methods. But I get a previous value. You can see it in console. When I check the first radio button, I am getting a value of previous one.

### What is expected?
get the same value in console and in declarated data

### What is actually happening?
values is different

**Comment by yyx990803** [comment]
In Chrome, `click` event fires before `change`, so the state change isn't reflected yet when the click handler is fired. You should use a watcher to watch `this.selected` instead.
