### ISSUE TITLE
IE 11 Event Handling inside button tag not fired.

### ISSUE THREAD

**Issue by timtnleeProject** [vuejs/vue#9557]
### Version
2.6.7

### Reproduction link
[https://jsbin.com/hezicepana/1/edit?html,output](https://jsbin.com/hezicepana/1/edit?html,output)

### Steps to reproduce
There are two elements with ` v-on:click`, the first one is wrapped inside a button tag and the second one is wrapped inside a div tag. 
Open it on IE11, clicking both elements to see the results.

### What is expected?
Expect both elements trigger the callback and alert the text.

### What is actually happening?
The first one does not trigger the callback whereas the second one works fine.

---
Don't know what causes this.
Not sure whether this happens only to the button tag.

**Comment by Justineo** [comment]
Is there any reason for not listening to the click event on the button itself? According to HTML spec, you shouldn’t put an interactive element inside a button.

**Comment by timtnleeProject** [comment]
@Justineo you're right!
I shouldn’t put an interactive element inside a button.
Still, I want to inform others who might come over this issue on IE.
So I think this issue can be closed?

**Comment by Justineo** [comment]
Yes I'm closing it now. Thanks for reporting your problem.
