### ISSUE TITLE
vue watch中使用短路运算符&&的问题

### ISSUE THREAD

**Issue by lizhongzhen11** [vuejs/vue#9565]
### Version
2.5.17

### Reproduction link
[https://github.com/lizhongzhen11/dailyGain/issues/27](https://github.com/lizhongzhen11/dailyGain/issues/27)

### Steps to reproduce
```js
watch: {
  cityLevel (val) {
    console.log('9999999999', val,  this.campaignType)
    if ( this.campaignType === 1) {
      console.log('666666666')
    }
     this.campaignType === 1 && console.log('888888888')
  }
}
```

### What is expected?
最近项目中突然发现，父组件传递一个computed属性`campaignType `给子组件，子组件通过选择checkbox改变值并判断` this.campaignType === 1`来执行相应的代码。
预期` this.campaignType === 1 && console.log('888888888')`能正常执行。

### What is actually happening?
但是很奇怪的是，`console.log('9999999999', val,  this.campaignType)`能正常打印出来， this.campaignType === 1 && console.log('888888888')却不行，然后我改成用`if()`来判断却能执行了。虽然问题解决了，但是为什么会出现这种情况呢？我百思不得其解，大致翻了下watch相关的issue，貌似都没我这个问题，想请教下尤大或者其他大佬，为什么会出现我这样的问题？
感谢各位前来解惑！

**Comment by Justineo** [comment]
你的问题大概率与 Vue 无关，watcher 的逻辑只是普通的 JavaScript，请检查自己的程序。如果发现的确是 Vue 的问题，请提供一个可以运行的最小复现，谢谢。

**Comment by lizhongzhen11** [comment]
我今天在项目中又试了下，发现加上`()`就没问题了！！！<br>
```js
true && console.log('555555555555');
(+this.campaignType === 1) && this.setBidMomentRule(val);
(+this.campaignType === 1) && console.log('888888888')
```
都怪自己菜，就是不知道为什么。。。
