### ISSUE TITLE
When monitoring an Array with 'watch', the callback function takes the same arguments and points to new data

### ISSUE THREAD

**Issue by ModernFarmer** [vuejs/vue#9568]
### Version
2.6.7

### Reproduction link
[https://github.com/ModernFarmer/test/blob/master/reappear.js](https://github.com/ModernFarmer/test/blob/master/reappear.js)

### Steps to reproduce
1.   Download the latest version of vue-cli

2.   Follow the code in the 'reppear.js' to listen for an Array

### What is expected?
newData : [1,2,3,4,5,6] , oldData : [1,2,3,4,5]

### What is actually happening?
newData : [1,2,3,4,5,6] , oldData : [1,2,3,4,5,6]

---
The root of the problem: two arguments to the callback function point to the same array

**Comment by posva** [comment]
This is working as expected due to Vue reactivity system being based on objects being mutated

**Comment by ModernFarmer** [comment]
I get it, thank you!

But do I think it would be better to change The data mechanism of The parameter 'oldData' to 'JSON.parse (JSON.stringify ([The old data])'), because in some projects I might encounter The need to determine what I should do next based on The length of The old and new Arrays, without affecting The mutagenicity of The parameter newData

**Comment by posva** [comment]
if you need to have different arrays, you have to make sure to replace the whole array instead of mutating it

**Comment by ModernFarmer** [comment]
I get it, thank you!
