### ISSUE TITLE
echart图表动态创建的html怎么绑定VUE事件代码请看详情

### ISSUE THREAD

**Issue by 531431988** [vuejs/vue#9569]
### Version
2.6.7

### Reproduction link
[https://codepen.io/anon/pen/KEPeqa](https://codepen.io/anon/pen/KEPeqa)

### Steps to reproduce
echart 图表 js 动态创建html时如何绑定事件

tooltip: {
          trigger: 'axis',
          formatter: params => {
            return `<a href="/?id=123" target="_blank"  onclick="事件">查看详情</a>`
          }
｝

### What is expected?
如何绑定VUE事件？

### What is actually happening?
如何绑定VUE事件？

**Comment by posva** [comment]
Please open the issue in the relevant repo
