### ISSUE TITLE
New slot syntax issue with events and 'this'

### ISSUE THREAD

**Issue by dmcknight26** [vuejs/vue#9574]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/5qc8zh20/](https://jsfiddle.net/5qc8zh20/)

### Steps to reproduce
Focus on the text field and then TAB or click out of it.  

### What is expected?
You should see text indicating that you blurred out.

### What is actually happening?
Nothing.

---
Here is a link to a working version with the old syntax -- https://jsfiddle.net/w8mreqa1/

All that is different is the usage of the slot, i.e. `template #header` vs `template slot="header"` yet now the inline handler no longer works (in fact it throws an error in my application).  I'm not sure if this is intended behavior going forward but I have existing code that breaks because of this situation when I attempt to use the new syntax.

I should also note the following workarounds I discovered: 1) if you omit the `this` keyword it appears to work 2) if you extract the inline method out and place it into `methods` it will also work.

**Comment by posva** [comment]
Never use `this` inside templates
