### ISSUE TITLE
Vue transition-group not working with slots?

### ISSUE THREAD

**Issue by gmanish** [vuejs/vue#9578]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/gmanish/L3y8j57s/](https://jsfiddle.net/gmanish/L3y8j57s/)

### Steps to reproduce
See that there's a <slot> within an opening/closing transition-group tags in the `tabs` component template.
Click on the tab headers to switch between tabs. 

### What is expected?
Expected to see the transition between tabs happening with the specified transition `out-left`. 

### What is actually happening?
While the tab contents switch as expected, the transition-group seems to have no effect. The transitions are not rendered.

---
Similar flattened code, i.e. without the components and slots, works just fine. 
I ran into this issue while trying to create a carousel slide component with transitions left-out/right-out transitions depending on whether we're moving to the next/previous slide.

**Comment by posva** [comment]
transition-group are for lists of elements but you are displaying only one at a time. I imagine you saw a warning on the console upon initial render telling you to switch to transition-group and that's what you changed it to it but your use case needs a transition component as only one view is visible at a time.
The approach you are using is very hacky, relying on the `$children` is very fragile. Here is another approach using named slots: https://jsfiddle.net/er45s0ag/ (you can use transition-group too), you can automate more things like setting the key if you use render functions and have selected state in tab using inject/provide

Your issue reminded me of https://github.com/vuejs/vue/issues/5661#issuecomment-301078575 btw

**Comment by gmanish** [comment]
The referenced comment above, seems to indicate that transition-group doesn't work with v-show. However, I have a working example here:
https://codesandbox.io/s/lp4yo72q39?fontsize=14

The structure is essentially the same, except there are no components and slots. This works just fine. 

Btw, the `$shildren` logic was picked up from [laracasts.com](https://laracasts.com/series/learn-vue-2-step-by-step/episodes/11), which I thought was a reliable place to learn Vue through screencasts.
