### ISSUE TITLE
'key' property in render data object seems to have no effect in the rendered component

### ISSUE THREAD

**Issue by cicsolutions** [vuejs/vue#9579]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/cicsolutions/qzkdew80/52/](https://jsfiddle.net/cicsolutions/qzkdew80/52/)

### Steps to reproduce
Create a main component that is a wrapper for a `<transition-group>` component, in which the default slot of our wrapper component becomes the separate items in the transition group.  Each item in the transition group is another Vue component, each with their own render function.  Because each item in the transition group needs to be have a unique key, the only approach I can think of to set that key on slot content would be to use a render function and set a unique key in the data object of the render function.

### What is expected?
A unique key would be applied to Vnode so that each item/component in the transition group has it's own unique key.

I've attempted setting the 'ref' value in the data object, and it does create the ref as expected.  I'm not sure why supplying a unique key in the data object does not give the component a key.

### What is actually happening?
Setting the 'key' property of the data object in a render function does not apply the provided key to the rendered component.  By using the console to inspect the component in the example fiddle above, you'll note the error related to transition group children requiring keys.

---
While it is certainly possible to manually provide a component key, my aim is to create an open source component that others can use, in which case, I do not want to require them to add the key to each component in the default slot.  I would prefer to programmatically add the key through the render function or any other approach.  Seems like the 'key' property in the data object was intended for this type of approach, but I'm sill learning!

**Comment by yyx990803** [comment]
The vnode the `transition-group` is seeing is the vnode that represents the `<card-title>` component, not the actual root node of `<card-title>`. The key you set on the child component's root node does not matter.

Put it another way: a component cannot decide its own key in the parent context. That's the responsibility of the parent.

In your case, your `<card>` component is responsible for providing keys that are visible to `<transition-group>`.

**Comment by cicsolutions** [comment]
Thank you so much for clarifying this for me!  You are the man!
