### ISSUE TITLE
New v-slot directive format has the 'elm' property in the slot node as 'undefined'

### ISSUE THREAD

**Issue by cicsolutions** [vuejs/vue#9580]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/cicsolutions/9trsg8nm/38/](https://jsfiddle.net/cicsolutions/9trsg8nm/38/)

### Steps to reproduce
In the fiddle, you'll see two approaches to slotting content (1) using the old slot syntax and (2) using the new v-slot directive.  In the console, you'll see a log for each slot and the contents of the slot node 'elm' property.  With the old slot syntax, the slot[0].elm is set as the slot div element, whereas with the new directive syntax, the slot[0].elm property is 'undefined'.

### What is expected?
I was expecting the new slot directive to behave in the same manner as the old approach to slotting content.  This may not be the case, given that v-slot is a directive.  However, if the old syntax for slots will be deprecated in the future, how would one go about getting their hands on the 'elm' property using the new v-slot directive?

### What is actually happening?
the new v-slot directive returns the slot node with the 'elm' property 'undefined'

**Comment by KaelWD** [comment]
Scoped slots return a different VNode each time you access them, so the one from `mounted` isn't the same one that's actually *been* mounted. 

https://jsfiddle.net/4txsdmp7/

**Comment by posva** [comment]
I would say accessing the element of a slot from a child component is a bad pattern and should be avoided (on top of KaelWD's point) and what you were trying to do with slots `elm` was not supposed to work in the first place. I will wait for Evan's answer on this though

**Comment by cicsolutions** [comment]
Thank you so much.  I really appreciate your feedback!  I'm still learning Vue, and your input is really helping me understand things better.
