### ISSUE TITLE
组件命名为Title时会警告

### ISSUE THREAD

**Issue by github923665892** [vuejs/vue#9581]
### Version
2.6.7

### Reproduction link
[https://new-issue.vuejs.org/](https://new-issue.vuejs.org/)

### Steps to reproduce
组件命名为Title时会警告
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

### What is expected?
null

### What is actually happening?
100%

**Comment by Justineo** [comment]
请按模板认真填写对应的信息，并提供对应的重现，不要胡乱填写一个链接。
