### ISSUE TITLE
Suggest that you get rid of this bug

### ISSUE THREAD

**Issue by duuliy** [vuejs/vue#9582]
### What problem does this feature solve?
When I test with unit jest and e2e, I report errors：localStorage is not available for opaque origins。
The configuration file is jsdom by default，Suggestion to change to node。
 "jest": {
    "verbose": true,
    "testURL": "http://localhost/"
  }

### What does the proposed API look like?
When I initialize the project, I can use it directly instead of reporting errors.thanks

**Comment by posva** [comment]
I'm pretty sure we already added that option to our cli plugin
