### ISSUE TITLE
Directive empty modifiers object is shared between instances

### ISSUE THREAD

**Issue by wsd-msp** [vuejs/vue#9583]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/62spywer/1/](https://jsfiddle.net/62spywer/1/)

### Steps to reproduce
Check the console.log and open the outputted objects

### What is expected?
The objects from the first 2 instances of the directive should contain it's own value.
The first object should be {foo: "test"} and the second object should be {foo: "test2"}

### What is actually happening?
The first 2 instances shares the modifier object, hence the second instance overrides the first instances value.
Both the first and second object is {foo: "test2"}

---
The third instance is just to show that it's only a problem if no modifiers are passed in the HTML.

I think it's because of: https://github.com/vuejs/vue/blob/4c98f9de39e18703ec3dbd05b596a1bbc3d0c8e3/src/core/vdom/modules/directives.js#L82,L105

**Comment by posva** [comment]
Mmh, I'm not sure about this because you shouldn't modify the modifiers object in the first place and creating a new object for **all** directives could increase memory print
