### ISSUE TITLE
Props` validator doesn't work in webpack production mode but works in dev|watch mode

### ISSUE THREAD

**Issue by waspar** [vuejs/vue#9584]
Perhaps this is a stupid issue, but I did not expect the validation of the parameters to be worked out only in the "watch" mode.

Everything I found in the documentation is - 

> Note that props are validated before a component instance is created, so instance properties (e.g. data, computed, etc) will not be available inside default or validator functions.

But in my opinion there is no explicit warning about the difference in operating modes.

```
resolve: {
...
	alias: {
		// vue
		'vue': 'vue/dist/vue.esm.js' // Use the full build
```

```
field: {
	type: Object,
	required: true,
	validator: function (prop) {
		alert('validator field');
```

node - 8.14.1
webpack - 4.29.2
vue - 3.4.0
- "vue-html-loader": "1.2.4",
- "vue-loader": "15.6.4",
- "vue-style-loader": "4.1.2",
- "vue-template-compiler": "2.6.7"

**Comment by posva** [comment]
validators are dev only indeed. 
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by leopiccionia** [comment]
> Everything I found in the documentation is -
>
> > Note that props are validated before a component instance is created, so instance properties (e.g. data, computed, etc) will not be available inside default or validator functions.

@waspar Notice that the previous paragraph states that it' doesn't work in production (a similar note appears in API documentation).
> When prop validation fails, Vue will produce a console warning (if using the development build).

If you think the wording could be improved here, please consider opening an issue on Vue [docs repo](https://github.com/vuejs/vuejs.org).
