### ISSUE TITLE
empty v-bind:value not removed on checkbox and radios

### ISSUE THREAD

**Issue by leevigraham** [vuejs/vue#9586]
### Version
2.6.7

### Reproduction link
[https://codepen.io/leevigraham/pen/OqVbeK](https://codepen.io/leevigraham/pen/OqVbeK)

### Steps to reproduce
Inspect the checkbox and radio elements.

### What is expected?
checkbox and input shouldn't have an empty value attribute

### What is actually happening?
checkbox and input have an empty value attribute

---
The documentation says:

> If isButtonDisabled has the value of null, undefined, or false, the disabled attribute will not even be included in the rendered element.

https://vuejs.org/v2/guide/syntax.html#Attributes

**Comment by posva** [comment]
`value` is different for radios and checkbox because they can have a value with null whereas the others don't. If we completely remove the value attribute, the default value will become `on` instead
