### ISSUE TITLE
There is a delay in communication between the parent and child components

### ISSUE THREAD

**Issue by qinkaiyuan** [vuejs/vue#9590]
### Version
2.6.7

### Reproduction link
[https://output.jsbin.com/nejugupaxo/1](https://output.jsbin.com/nejugupaxo/1)

### Steps to reproduce
父组件传入age
子组件接收age
父组件改变age
父组件调用子组件的printAge方法输出age，发现子组件的age值未改变

click change age button, then please see console log

### What is expected?
There is no delay in passing the value of the parent and child components.

### What is actually happening?
Delayed

**Comment by maitysubhasis** [comment]
Replacing 
```js
this.$refs.age.printChildAge()
```
with 
```js
this.$nextTick(this.$refs.age.printChildAge)
```

will give you an appropriate result.

For more details have a look at this [link](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue)

**Comment by posva** [comment]
This is working as expected because Vue needs one tick to pass down the updated values
