### ISSUE TITLE
Setting max-height with scrollHeight in before-leave transistion fails

### ISSUE THREAD

**Issue by ziaxdk** [vuejs/vue#9593]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/oovq6y1k36](https://codesandbox.io/s/oovq6y1k36)

### Steps to reproduce
Click on "This is a header" and it animates to open
Click again and it doesn't animates
Enable hack in line 47 in App.Vue and repeat and it works

### What is expected?
This transition should work without the "read" hack

### What is actually happening?
It just collapses without transition

**Comment by posva** [comment]
This is unrelated to vue, it's about CSS transitions, probably related to using max-height instead of height in your case

**Comment by ziaxdk** [comment]
But it's the same with height

**Comment by posva** [comment]
it works with height (don't forget to update transition for height too) but it's unrelated to Vue, this is CSS

**Comment by ziaxdk** [comment]
Nope https://codesandbox.io/s/23ww9nqo6y

**Comment by Justineo** [comment]
https://github.com/vuejs/vue/blob/0b16927c9d382b9cf134b131b898350340c2ee41/src/platforms/web/runtime/modules/transition.js#L257-L275

As you can see, `beforeLeave` and `leave` are called synchronously in a single task so there's no chance for browsers to actually update the layout. It's the same as:

```js
el.style.height = '1px'; // this value will be disposed
el.style.height = 'auto';
```

When you request for `scrollHeight` browsers will force-update the layout to retrieve the latest value so next time you update the value it starts the transition. Maybe calling `leave` hook in `nextFrame` (double raf) can make this out-of-the-box.

/cc @yyx990803

**Comment by ziaxdk** [comment]
Ok, thanks for the explanation. But if the two hooks are called in in a single task, and the browsers dispose the before-leave value, what it's the point with the hook?
