### ISSUE TITLE
Odd behaviour with setTimeout.

### ISSUE THREAD

**Issue by sustained** [vuejs/vue#9597]
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/sustained/zody8sf4/](https://jsfiddle.net/sustained/zody8sf4/)

### Steps to reproduce
Just look at the code/result for the `test-3` component.

### What is expected?
I'd personally expect `test-3` to work, if `test-2` and `test-1` do.

And I honestly have no idea why `test-5` works at all, especially if `test-3` doesn't.

Something seems a bit weird here.

### What is actually happening?
It doesn't.

**Comment by sirlancelot** [comment]
The `created()` hook is called before `render()` so even though the property `test.foo`  is not reactive, it exists by the time the component is rendered except when deferred via `setTimeout()`.

Hopefully this explains the inconsistency you're seeing. The best practice has always been to use `Vue.set()` or `vm.$set()` when creating new properties as shown in the [Change Detection Caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) section of the guide.
