### ISSUE TITLE
Vue.extend prototype

### ISSUE THREAD

**Issue by Ti-webdev** [vuejs/vue#9602]
### Version
2.6.7

### Reproduction link
[https://repl.it/@Ti_webdev/Vue-extend](https://repl.it/@Ti_webdev/Vue-extend)

### Steps to reproduce
```javascript
const Vue2 = Vue.extend({})
Vue.prototype.$foo = 'bar'

const Child = {
  render (h) {
    return h('h1', 'Hello Vue.extend! '   this.$foo)
  }
}

new Vue2({
  render (h) {
    return h(Child)
  },
  el: "#app"
}).$mount()
```
### What is expected?
Hello Vue.extend! bar

### What is actually happening?
Hello Vue.extend! undefined

**Comment by posva** [comment]
It does work http://jsfiddle.net/vc9k6dog/
next time please provide a runable repro

**Comment by Ti-webdev** [comment]
http://jsfiddle.net/nLega0h5/

**Comment by Ti-webdev** [comment]
@posva please re-open

**Comment by Ti-webdev** [comment]
`Vue2.prototype.$foo = 'bar'`

**Comment by posva** [comment]
that's normal, Child is also extending Vue, you can make it extend Vue2 though:

```js
const Child = Vue2.extend({
  render (h) {
    return h('h1', 'Hello Vue.extend! ' +  this.$foo)
  }
})
```

**Comment by Ti-webdev** [comment]
Nice

**Comment by Ti-webdev** [comment]
Unfortunately I have more complicated case where your way does not work :(
I want to isolate third-party library with code like in the example http://jsfiddle.net/vg8y5n34/3/
