### ISSUE TITLE
Unmatched version of dependencies when using npm to install

### ISSUE THREAD

**Issue by DaKoala** [vuejs/vue#9606]
### What problem does this feature solve?
First contributors may have problem running test scripts if they install dependencies using `npm`. 

According to the [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md):
```bash
git clone https://github.com/vuejs/vue.git
npm install
npm run test
```

An error is raised. The version of `vue` and the version of `web-server-renderer` are not matched.

When I switched to yarn to install dependencies and run the test script, everything was fine. However, this may confuse some starting contributors.

### What does the proposed API look like?
No API changes.

**Comment by yyx990803** [comment]
Can't reproduce.
