### ISSUE TITLE
Keep similar functions written the same way

### ISSUE THREAD

**Issue by Cuixote** [vuejs/vue#9608]
### What problem does this feature solve?
When I read the source code, I found that function  `normalizeProps` and `normalizeInject` similar, but not the same writing.

The file path: `vue/src/core/util/options.js`

```js
function normalizeProps (options, vm) {
    var props = options.props;
    if (!props) { return }
    var res = {};
    ...
          res[name] = { type: null };
    ...
        res[name] = isPlainObject(val)
          ? val
          : { type: val };
   ...
    options.props = res;
  }
```

```js
function normalizeInject (options, vm) {
    var inject = options.inject;
    if (!inject) { return }
    var normalized = options.inject = {};
    ...
        normalized[inject[i]] = { from: inject[i] };
    ...
        normalized[key] = isPlainObject(val)
          ? extend({ from: key }, val)
          : { from: val };
  }
```

Temporary variables( `res` and `normalized`) are used, Why not use the same writing method?

### What does the proposed API look like?
I prefer the way `normalizeInject` is written. I hope `var res = {}; options.props = res; ` in `normalizeProps` could rewrite link ` var res = options.props = {};`.

This is a small problem, but I think it will make it less confusing for beginners to read the source code

**Comment by posva** [comment]
Thanks for raising concern. However, different functions are still different functions. Creating more functions will have the opposite effect: making it harder to read for beginners.
On top of that, there are much more other concerns like performance that cannot be ignored in some places, so it's not that simple.
Cheers,
