### ISSUE TITLE
Catching events of sibling components

### ISSUE THREAD

**Issue by omerciftcibasi** [vuejs/vue#9609]
### What problem does this feature solve?
Components are emitting events to parents and parents sends props to child components, If a sibling component's event trigger change its brothers; parents will catch the event and than send the change to the other children.

If vue can implement a design for cathcing events  between siblings it would be make the communication between sibling components more efficiently.

### What does the proposed API look like?
a special chareacter can declare for events to catch inside components for example:

<child-component @on-change-from-component="parent-method" [SpecialChar(₺)][event-name-to-catch]="child-component-method"  />

**Comment by posva** [comment]
It already exists! 😄 

You can either use an Event Bus (as in Vue docs) or Vuex

**Comment by omerciftcibasi** [comment]
Thanks for the feed back.
I was looking for more straightforward way than state, and event bus solution meets my needs.
