### ISSUE TITLE
TodoMVC Example: SVG image of checkboxes are not shown in Chrome 72.0

### ISSUE THREAD

**Issue by FumioNonaka** [vuejs/vue#9610]
### Version
2.6.5

### Reproduction link
[https://vuejs.org/v2/examples/todomvc.html](https://vuejs.org/v2/examples/todomvc.html)

### Steps to reproduce
1. Just input a todo item in the recent version of Chrome.
2. The checkbox image of SVG which should be placed in the front of the item will not be shown.

### What is expected?
Checkboxes for each items are shown.

### What is actually happening?
Nothing appears at the place.

---
Convert any hash (#) characters in the url() functions for SVG in index.css to %23.

```
.todo-list li .toggle:after {
	content: url('data:image/svg xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="%23ededed" stroke-width="3"/></svg>');
}

.todo-list li .toggle:checked:after {
	content: url('data:image/svg xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="%23bddad5" stroke-width="3"/><path fill="%235dc2af" d="M72 25L42 71 27 56l-4 4 20 20 34-52z"/></svg>');
}
```

**Comment by JoolsMcFly** [comment]
Same issue with Firefox.

Can you make a PR to fix it?

**Comment by FumioNonaka** [comment]
[`index.css`](https://unpkg.com/todomvc-app-css@2.0.4/index.css) is loaded from unpkg.com.  How can I make a pull request?

See: [`vue/examples/todomvc/index.html` line 6](https://github.com/vuejs/vue/blob/dev/examples/todomvc/index.html#L6)

**Comment by Justineo** [comment]
`todomvc-app-css` fixed the issue [two years ago](https://github.com/tastejs/todomvc-app-css/commit/808217fab49a5e2da2d5e52aee417c62807cec28). We just need Evan to update the [fiddle](https://jsfiddle.net/yyx990803/4dr2fLb7/).

/ping @yyx990803

**Comment by yyx990803** [comment]
Updated.

**Comment by FumioNonaka** [comment]
The checkbox of toggle-all class is disappeared then.

**Comment by Justineo** [comment]
It seems that `todmvc-app-css` introduced a breaking change that required an extra `<label>` element for the `toggle-all` button now.

**Comment by yyx990803** [comment]
Updated again!
