### ISSUE TITLE
官方使用手册问题

### ISSUE THREAD

**Issue by weijiyang** [vuejs/vue#9611]
### Version
2.6.8

### Reproduction link
[https://codepen.io/TangShao/project/editor/AnekwQ](https://codepen.io/TangShao/project/editor/AnekwQ)

### Steps to reproduce
https://cn.vuejs.org/v2/guide/components-slots.html#%E5%85%B6%E5%AE%83%E7%A4%BA%E4%BE%8B
深入了解组件-插槽-其他示例 代码案例错误

### What is expected?
没有注明slot name属性

### What is actually happening?
父组件将无法拿到相应子组件的属性

**Comment by xixifeng** [comment]
https://cn.vuejs.org/v2/guide/components-slots.html#%E5%85%B6%E5%AE%83%E7%A4%BA%E4%BE%8B
深入了解组件-插槽-其他示例 也没搞清楚,望知道的大神指点,谢谢.

**Comment by Justineo** [comment]
是官方文档遗漏了。

See https://github.com/vuejs/cn.vuejs.org/pull/870.
