### ISSUE TITLE
v-slot 要替代 slot scope-slot ，但 v-slot 似乎并不支持直接在html元素上使用，这个在文档中没有说明，是已经取消了，还是不支持？

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue#9612]
### What problem does this feature solve?
保持和 slot scope-slot 的兼容

### What does the proposed API look like?
v-slot 可以直接用在html原生元素上

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/53717307-b7b8ce00-3e92-11e9-888e-8de636ba59a9.png)

**Comment by jiankafei** [comment]
@Justineo 文档我看了，你说的大家都知道，我只想知道 v-slot 之后，是不是就不能直接使用到 html 元素上了，希望都说明，不然会给开发者留下疑惑

**Comment by Justineo** [comment]
“**只能**添加在 `<template>` 上”呀，自然不能用在其它元素（包括组件）上。
