### ISSUE TITLE
v-bind href in <a> tag doesn't work with complicated setup

### ISSUE THREAD

**Issue by WangHansen** [vuejs/vue#9613]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/khydf31a/](https://jsfiddle.net/khydf31a/)

### Steps to reproduce
Put the ```href``` with subject and content for ```<a> tag``` in a data and use``` :href``` instead

### What is expected?
For <a> tag to open email client with prefilled content and title, ```v-bind:href``` should return the same result as just using ```href```

### What is actually happening?
When using v-bind, content of email is ignored

---
Same issue with ```sms:?&body=something```

**Comment by WangHansen** [comment]
maybe because #6828

**Comment by Justineo** [comment]
HTML encoding is only required if you literal values in HTML directly. You don't have to encode the value in JavaScript. Make the following changes and it should work.

```diff
- mailto:?subject=test subject&amp;body=test content
+ mailto:?subject=test subject&body=test content
```
