### ISSUE TITLE
unconsistent behavior between render() and template

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#9614]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/q62znvg3/1/](https://jsfiddle.net/q62znvg3/1/)

### Steps to reproduce
just run

### What is expected?
```
 render(): <div class="bar foo"></div>
 template: <div class="bar foo"></div>
```

### What is actually happening?
```
 render(): <div class="foo"></div>
 template: <div class="bar foo"></div>
```
---
Using template, `:class` and `class` are merged. using render(), `:class` overwrites `class`.

**Comment by posva** [comment]
You need to use `staticClass` in render functions, which doesn't seem to be documented

**Comment by FranckFreiburger** [comment]
Thanks for the trick.

**Comment by yyx990803** [comment]
`<div class="foo">` in templates are not compiled into an attribute, but `staticClass` instead. In render functions `attrs: { class: 'foo' }}` means you want to force overwrite the entire attribute to just `foo`.
