### ISSUE TITLE
能否追加show的钩子函数

### ISSUE THREAD

**Issue by cykcykcykcyk** [vuejs/vue#9618]
### What problem does this feature solve?
因为dom隐藏下，其宽度或者高度为0，但是偏偏有些组件需要用到这个高度宽度，比如自定义的滚动条，轮播等等。
这类的组件一般都有自己的refresh的方法。
为开发过程中为了追求更快的渲染速度使用的是v-show的方案，虽然可以通过v-show对应data的watch去监听 但是这就要组件对外暴露对应的refresh方法，而不能从组件内部的show钩子去实现刷新，这似乎并不怎么优雅。
综上，我希望可以增加show或者hide钩子函数，或者有其他替代方案也是可以的

### What does the proposed API look like?
如同钩子函数一样，或者类似的插件也是可以的

**Comment by Justineo** [comment]
Duplicate of #7033
