### ISSUE TITLE
Docs are displayed without style after they are updated (caching problem)

### ISSUE THREAD

**Issue by Kjir** [vuejs/vue#9626]
### Version
2.6.8

### Reproduction link
[https://ssr.vuejs.org/guide/build-config.html](https://ssr.vuejs.org/guide/build-config.html)

### Steps to reproduce
1. Load the Vue docs
2. Wait for an update to the docs to happen
3. Reload the page

### What is expected?
The docs should be displayed complete with styles

### What is actually happening?
The HTML appears to be cached locally and point to CSS files that don't exist anymore. The page is unstyled.

**Comment by Kjir** [comment]
I had a screenshot, but I lost it :disappointed: 
As soon as it happens again I'll attach it

**Comment by Kjir** [comment]
Here is what happens in the dev tools. The first load is a refresh with the cached HTML in the service worker. The 404s are the reason why the docs appear unstyled.
After that I did a refresh without cache which redownloads the HTML from the server and has the links to the correct styles.

![image](https://user-images.githubusercontent.com/64094/53804601-476c8400-3f48-11e9-8678-2f9a2e479728.png)

**Comment by posva** [comment]
This could be a problem with vuepress. If you can reproduce it, you should open an issue there
