### ISSUE TITLE
transition-group surrounding span changeable

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue#9627]
### What problem does this feature solve?
When you have a `<ol>` list with `<li>` items which are animated with transition-group, the generated DOM is invalid, because a `<span>` tag is between `<ol>` and `<li>`. (see https://jsfiddle.net/m9gxd13e/)

It should be possible to override the default `<span>` with a different tag name

### What does the proposed API look like?
`<transition-group name="group-fade" mode="out-in" tag="ol" class="breadcrumb" appear>`

... should create an `<ol>` insteat of `<span>` and adds all attributes (e.g. `class="breadcrumb"`) to this tag.

**Comment by posva** [comment]
the `tag` prop already works

**Comment by Justineo** [comment]
`<transition-group>` has a `tag` prop already. See https://vuejs.org/v2/api/#transition-group.
