### ISSUE TITLE
Vue template compiler/loader should generate source maps for template blocks

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue#9629]
### What problem does this feature solve?
Vue should be able to generate source maps for `<template>` blocks. We can enable source maps today, but when an error occurs in a template, it's not entirely helpful:

![image](https://user-images.githubusercontent.com/12532733/53834321-50615380-3f50-11e9-8a98-c3d387d692c6.png)

There should be a way to enable source maps via `vue.config.js` that would signal the template compiler to generate source maps (if possible?) in raw markup.

**Comment by posva** [comment]
You can create a feature request if it doesn't exist already in vue-loader repo

**Comment by yyx990803** [comment]
This is something we are working on for v3.
