### ISSUE TITLE
Uncaught TypeError: Cannot read property 'recordClickType' of undefined at HTMLDocument.onClick

### ISSUE THREAD

**Issue by cwhsu1984** [vuejs/vue#9631]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
vue create helloworld
yarn serve
open the dev server link and click anywhere except the links on the page

### What is expected?
no errors in console

### What is actually happening?
click on the page, and it throws error in console.
Same errors show in console even in jsfiddle.

---
errors in console:

Uncaught TypeError: Cannot read property 'recordClickType' of undefined
    at HTMLDocument.onClick (content_script.js:623)
onClick @ content_script.js:623

**Comment by yyx990803** [comment]
Invalid reproduction.

**Comment by Justineo** [comment]
> content_script.js

It clearly comes from your browser extension.

**Comment by cwhsu1984** [comment]
> > content_script.js
> 
> It clearly comes from your browser extension.

You guys are right! The errors are from an extension called "Kantu Browser Automation". When I disable the extension, everything works fine. Thanks!

**Comment by A9T9** [comment]
Owner of the Kantu [RPA software](https://ui.vision/) here :) 

Sorry about that false alarm due to our extension. Meanwhile, we fixed the issue with the V5.3.7 update.

**Comment by sagearbor** [comment]
I can confirm that was my issue but also am unable to update manually in chrome using developer mode as it gets stuck in "Updating..." which has been reported as a known chrome bug over 6 months ago.  I'm not sure why my chrome hasnt autoupdated Kantu RPA, so in the short term I just tight-clicked on the UI.Kantu extension icon next the search bar and then clicked "This can read and change site data" - "When you click the extension".

![image](https://user-images.githubusercontent.com/8879032/71009187-d43b9500-20b7-11ea-8576-3714da2efd34.png)
