### ISSUE TITLE
Transition-group component child node immediately triggers the dragend event after dragstart

### ISSUE THREAD

**Issue by sunzongzheng** [vuejs/vue#9633]
### Version
2.6.0

### Reproduction link
[https://jsfiddle.net/sunzongzheng/ybmp6t1w/16/](https://jsfiddle.net/sunzongzheng/ybmp6t1w/16/)

### Steps to reproduce
I made two examples of jsfiddler.

When I use version 2.5.22, everything works fine. Please look at this: https://jsfiddle.net/sunzongzheng/ybmp6t1w/15/

But when I use version 2.6.0 and above, I can not drag anymore. Please look at this: https://jsfiddle.net/sunzongzheng/ybmp6t1w/16/

Please just drag any block, you can see the differences.

### What is expected?
I can drag the block normally

### What is actually happening?
It does not work fine.

**Comment by sunzongzheng** [comment]
I find out that it was caused by the nextTick's changes

**Comment by posva** [comment]
you are removing the element right away (with v-if/v-else) when the drag start, so it's normal for it to also trigger the dragend event
I would recommend you to keep one wrapper element and modifiy things inside instead, something like this: https://jsfiddle.net/yxh0esb7/
