### ISSUE TITLE
Custom Directives Cannot Use Capital Letters

### ISSUE THREAD

**Issue by glv1at118** [vuejs/vue#9639]
### Version
2.6.7

### Reproduction link
[https://github.com/glv1at118/vue-s-possilbe-bug](https://github.com/glv1at118/vue-s-possilbe-bug)

### Steps to reproduce
Below is where I discovered the bug, code is simple. When I customized a vue directive "myFocus" to make the input element auto-focus, it does not work and console is reporting a warning. However when using a customized directive "myfocus", it works well. The only difference is whether the directive is in lower or upper case. I am not really sure if this is a bug in vue, as I am new to vue. Please kindly take a minute to check.

<body>
    <div id="area">
        User's input: <input type="text" v-myFocus>
    </div>

    
    
    <script>
        /* Custom directve "myFocus" does not work */
        // Message from console: [Vue warn]: Failed to resolve directive: myfocus
        Vue.directive("myFocus", {
            inserted: function(el){
                el.focus();
            }
        });

        /* Custom directive "myfocus" works normally */
        // Vue.directive("myfocus", {
        //     inserted: function(el){
        //         el.focus();
        //     }
        // });

        var vm = new Vue({
            el: "#area",
            data: {}
        });
    </script>
</body>

### What is expected?
In both scenarios, the input element should get focus automatically upon page load.

### What is actually happening?
The custom directive with capitalized letter will not work. However the one without capitalized letter works.

---
Please kindly see my code in the Steps to reproduce area, also I've linked a repo to demonstrate the bug.
The version 2.6.7 vue.js is also in the repo.

**Comment by posva** [comment]
When using capital letters, make sure to use the kebab version in templates: `v-my-focus` for `myFocus`

**Comment by glv1at118** [comment]
Thanks!
