### ISSUE TITLE
about keep-alive nest use 

### ISSUE THREAD

**Issue by pingmouren** [vuejs/vue#9642]
### Version
2.6.8

### Reproduction link
[http://localhost:8080/#/sorryihavenot](http://localhost:8080/#/sorryihavenot)

### Steps to reproduce
router-view i use the keep-alive and the view i use keep-alive too
like this
<keep-alive :max="10">
      <component
        :is="currentView"
        :part-info="partInfo"
        @to-gantt="toGantt"
        @to-monitoring="toMonitoring"/>
    </keep-alive>

### What is expected?
i expected the two is keep alive

### What is actually happening?
the component can not show the right view

---
when keep-alive interior keep-alive, will appear unpredictable phenomena

**Comment by posva** [comment]
Always provide a boiled down repro for bug reports. Thank you
