### ISSUE TITLE
Resolving nested async functional components is broken

### ISSUE THREAD

**Issue by derz** [vuejs/vue#9643]
### Version
2.6.8

### Reproduction link
[https://codesandbox.io/s/l07lp5vom](https://codesandbox.io/s/l07lp5vom)

### Steps to reproduce
As already quickly mentioned in here https://github.com/vuejs/vue/commit/03c13de38e883636917800a283ebcb338bbfbdc3 nested functional components are broken since 2.6.8
1.) I have 2 functional components in the repro (`Logo.vue` / `LogoWrapper.vue`)
2.) The components are registered globally as async components (doesn't really make sense in this case.. but you should get the point :-)). Check `components/_globals.js`
3.) Using one of the component in the other (Logo inside LogoWrapper) breaks with the errormessage "Cannot read property '$on' of null" - this was working prior to 2.6.8

### What is expected?
Components are renderer, no error message.

### What is actually happening?
TypeError
Cannot read property '$on' of null

**Comment by yyx990803** [comment]
I can't reproduce this locally. Can you manage to provide a repro without Nuxt or any build system involved?

**Comment by dejour** [comment]
After looked source code, I guess this can only happen with SSR.

**Comment by derz** [comment]
yes, as mentioned by @dejour the bug only happens with SSR. Should I still add another repro without nuxt?
