### ISSUE TITLE
Dynamic arguments should work with modifiers

### ISSUE THREAD

**Issue by alexpennells** [vuejs/vue#9645]
### What problem does this feature solve?
Related to: https://github.com/vuejs/vue/issues/9417

Since Vue 2.6, using dynamic arguments I can conditionally add a keydown event:
```
@[keydownEvent]="handleKeydown"
```

What I'm unable to do is attach a keydown event with modifiers, since they do not appear to be working with dynamic arguments in Vue 2.6.6. To restrict the example above to just Enter keydown events, I have to write the logic into the handler instead of using the existing Vue modifiers:

```
@[keydownEvent]="keydownMods($event, handleKeydown)"

methods: {
    keydownMods(e, callback) {
      if (e.code === 'Enter') {
        e.preventDefault();
        callback();
      }
    }
}
```

### What does the proposed API look like?
Allow for the existing v-on modifiers to be used with dynamic arguments:

```
@[keydownEvent].enter.prevent="handleKeydown"
```

**Comment by posva** [comment]
This already works http://jsfiddle.net/q2xrs1dh/
Next time, please provide a repro

**Comment by alexpennells** [comment]
Turns out this was related to having multiple keydown events assigned. Works fine with `.enter` unless you also have a `.space`.
http://jsfiddle.net/78e5cvpf/

**Comment by posva** [comment]
yeah because they are all applied so it will never trigger because the keyup event can only have one key
