### ISSUE TITLE
建议 $slots 中增加 slot 的顺序索引

### ISSUE THREAD

**Issue by treenew** [vuejs/vue#9655]
### What problem does this feature solve?
比如说以下代码：
```html
                <i-button><icon name="home" slot="icon" />default A</i-button>
                <i-button>default B <icon name="home" slot="icon" /></i-button>
```
生成的时候，可以根据 slot 的顺序，去将图标应用到按钮的左侧还是右侧。

### What does the proposed API look like?
vnode增加 index 属性

**Comment by posva** [comment]
if you want to preserve order use the default slot altogether
