### ISSUE TITLE
npm run build gets killed (errno 137)

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue#9664]
### Version
2.6.8

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
I have the code below which works fine.

```
let imports = []

function importAll(filePaths) {
  filePaths.keys().forEach(filePath => {
    const path = filePath.replace('.', '')
    imports.push(require(`@/modules${path}`).default)
  })
  return imports
}

export const importAllRoutes = () =>
  importAll(require.context('@/modules/', true, /routes.js/))

```

When I do `npm run build` locally works perfectly fine. But when I do `npm run build` on the server (to deploy) the build process gets killed.

### What is expected?
This is supposed to work but the build process gets killed.

### What is actually happening?
My guess is that is a RAM issue but I am not sure.

---
Sorry but I can't provide Link to minimal reproduction. Also I am not sure that is a vue.js issue, a npm one or webpack. But if I remove the code snippet above, everything works fine.

**Comment by posva** [comment]
Hey, please do not open issues without providing repros or to ask questions, this is not the first time you it so please stop doing it. 
Remember you can and should use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by Rolanddoda** [comment]
There is no a way to provide repro. I thought this is an issue since the build process gets killed that's why I opened an issue. But anyway thanks. I will use the forum.
