### ISSUE TITLE
$mount programmatically does not work with nested $slots.default components.

### ISSUE THREAD

**Issue by lrembacz** [vuejs/vue#9666]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/202mnp7q40](https://codesandbox.io/s/202mnp7q40)

### Steps to reproduce
Drag Test4 element and drop it on the red box. Then after that just Drag'n Drop given box with 3 elements inside into the first yellow box. Element $mounted programatically will disappear from the element.

Is there a problem with $mount()? Why is $slots.default not updated when we are mounting dynamically? Is there a workaround for the issue?

### What is expected?
Element should be transfered correctly into second Box.

### What is actually happening?
$mounting does not work correctly for nested components in $slots.default

---
I am working on new version of my draggable grid layout component. I have made many new features to it and now I got the issue with mounting nested elements programatically. I know that there is a way to just v-model on array of elements, but I don't want to use it. I just want to have my source of true from just DOM (mounted components) in slots and to give user a flexible way to just nest as many parents/children as it needs actually.

**Comment by posva** [comment]
Hey thanks for the report but this is too much, could you please boil it down to the strict minimum, no ts, no drag & drop (you should be able to reproduce the problem with v-if, v-for and other vue directives). This would really help us, thank you 🙂
