### ISSUE TITLE
$mount programmatically does not work with nested $slots.default components

### ISSUE THREAD

**Issue by lrembacz** [vuejs/vue#9670]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/kxw0xn61jo](https://codesandbox.io/s/kxw0xn61jo)

### Steps to reproduce
Just wait and watch.

### What is expected?
Element should be transfered correctly into second Box.

### What is actually happening?
$mounting does not work correctly for nested components in $slots.default

---
Elements disapear if they are mounted with $mount() method manually. It is example changed for @posva https://github.com/vuejs/vue/issues/9666.

**Comment by posva** [comment]
Hey, this is still not enough for a bug report either, you are giving no information about where to look at with still quite some code. I still gave it a look and checked the `moveChild` function. You are manually plugging things into Vue and expect it to pick them up, that won't work. For example, you shouldn't change `$slots` nor `appendChild` as Vue will rewrite things on top on next render. 
Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
