### ISSUE TITLE
Template support property binding

### ISSUE THREAD

**Issue by mantou132** [vuejs/vue#9672]
### What problem does this feature solve?
bind js object to webcomponents.

### What does the proposed API look like?
```html
<web-component v-property-bind="{a: 1}"></web-component>
<web-component .property="{a: 1}"></web-component>
```

**Comment by Justineo** [comment]
You can use the `.prop` modifier of `v-bind`, see [our docs](https://vuejs.org/v2/api/#v-bind).

**Comment by yyx990803** [comment]
There's also an active RFC: https://github.com/vuejs/rfcs/pull/18
