### ISSUE TITLE
Space keydown event issue on Windows Firefox

### ISSUE THREAD

**Issue by yxngl** [vuejs/vue#9678]
### Version
2.6.8

### Reproduction link
[https://codepen.io/yxngl/pen/VRzoMJ?editors=1011#0](https://codepen.io/yxngl/pen/VRzoMJ?editors=1011#0)

### Steps to reproduce
Tab to focus on the label and checkbox, then press space key.

### What is expected?
Checkbox should be checked.

### What is actually happening?
In Firefox developer edition on Windows, the check flashes and disappears. It works fine on Mac and Chrome and Edge.

---
Extracted from a UI library. Pressing Enter key always works. Looks like the input receive the space keydown event somehow? Not sure if it is only a browser quirk or the design should be improved. Thanks.

**Comment by posva** [comment]
Cannot reproduce on Firefox on Mac. It may be due to the order of events (inherent to browsers) causing the checkbox to be checked twice in a very small gap of time, going back to initial state, does it also happen with other keys, like <key>`a`</key>?

**Comment by yxngl** [comment]
Yeah, it works in Firefox on Mac. I think it is only for space key. The demo also binds the enter key.  It works and I have just tried others. I thought it may be related to that native checkbox can be checked with space.

**Comment by posva** [comment]
I managed to test now on Firefox. This is indeed related to the order that differs between browsers. As space also triggers selecting the checkbox so it ends up selected twice. This is something you should avoid in general because of the reason mentioned aboved
