### ISSUE TITLE
Get the default $scopedSlots even if I do not set the slot-scope attribute

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue#9682]
### Version
2.6.1

### Reproduction link
[https://jsfiddle.net/Lw83ej0p/1/](https://jsfiddle.net/Lw83ej0p/1/)

### Steps to reproduce
1. Generate component using render function
2. Put some elements to the component
3. Check $scopedSlots of the component

You can see that $scopedSlots has a default function which returns all nested elements. 
The attached example illustrates this behavior (open DevTools).

### What is expected?
I expect $scopedSlots.default when I set slot-scope attribute

### What is actually happening?
I get $scopedSlots.default even if I do not set the slot-scope attribute

**Comment by posva** [comment]
That already works with latest Vue

**Comment by dxvladislavvolkov** [comment]
@posva Which version? I get the same result with vue 2.6.8.
I also discovered that if I set slot-scope for one element I get only it.

**Comment by posva** [comment]
Oh, you want `default` to not be there! The title made it look the other way around. This is intentional and we cannot introduce such a breaking change anyway

**Comment by dxvladislavvolkov** [comment]
@posva How can I check this default? I mean if I set slot-scope attribute or not. Because I need to use an element with this attribute only.

**Comment by dxvladislavvolkov** [comment]
@posva In the older version (2.5.7) I get elements only with slot-scope. You can see an example here https://jsfiddle.net/d20qho1y/ . In the example, I get an error because elements don't have the attribute.  After updated vue, I got some problem.

**Comment by posva** [comment]
It's part of the slot/scoped slot unification and it was part of v2.6 release: https://github.com/vuejs/vue/releases/tag/v2.6.0
you shouldn't be using slots and scoped slots with the same name for different purposes
