### ISSUE TITLE
Docs Suggestion - Update method definitions to use ECMAScript 2015 shorter syntax

### ISSUE THREAD

**Issue by rdhelms** [vuejs/vue#9683]
### What problem does this feature solve?
Currently in the Vue docs, methods are defined using the `methodName: function () {}` syntax, such as for the `data` method below:

**Current Example**: https://vuejs.org/v2/guide/components.html
```
// Define a new component called button-counter
Vue.component('button-counter', {
  data: function () {
    return {
      count: 0
    }
  },
  template: '<button v-on:click="count  ">You clicked me {{ count }} times.</button>'
})
```

But it is very common in tutorials, articles, and other Vue apps to use the shorter method definition syntax, described by MDN here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

It would improve readability and minimize context-switching if the Vue docs could also use this newer syntax. Outside of the Vue documentation, it seems more and more rare to find methods with the older syntax.

### What does the proposed API look like?
**Proposed Example**:
```
// Define a new component called button-counter
Vue.component('button-counter', {
  data () {
    return {
      count: 0
    }
  },
  template: '<button v-on:click="count  ">You clicked me {{ count }} times.</button>'
})
```

**Comment by posva** [comment]
This is intentional to keep docs approachable to everyone but we might include multiple versions in future versions of the docs. BTW, the docs are at vuejs/vuejs.org repo 🙂
