### ISSUE TITLE
Custom instructions are normal in version 2.5.17 and abnormal in 2.6.8.

### ISSUE THREAD

**Issue by lzq920** [vuejs/vue#9685]
### Version
2.6.8

### Reproduction link
[https://codepen.io/lzq920/full/OqOZPG](https://codepen.io/lzq920/full/OqOZPG)

### Steps to reproduce
open the menu

### What is expected?
If you do not have permissions, the menu does not display

### What is actually happening?
all menu display

---
control permission

**Comment by yyx990803** [comment]
如果不能提供不包含 element-ui 的重现，请先到 element-ui 那边去开 issue。
