### ISSUE TITLE
fail to resolve vue directive"v-shortkey" on the component

### ISSUE THREAD

**Issue by madhuadbanker** [vuejs/vue#9686]
### Version
2.5.13

### Steps to reproduce
1 install vue-shortkey
2 created vue-shortkey.js in plugins as per nuxt documentation and added path 
3 build appliaction in nodejs command prompt
4 open apllication in browser and specific component gives vue warn

### What is expected?
to use combination keys E.g: ctrl   s and have one listner

### What is actually happening?
getting vue warn: failed to resolve directive: shortkey

---
I am using vue application ssr with nuxt. I have added the plugin as mentioned in nuxt documentation in 2 ways .

create pligins/vue-shortkey.js and given path in nuxt.config.js ...i got vue warning failed to resolve directive-shortkey
another way..my plugin in node_modules so given in build option of nuxt.config.js as transpile:['vue-shortkey'] but didnt create plugins/vue-shortkey.js...here also same error
another way i tried by give Vue.use(require('vue-shortkey'))in app.ts ..here i got document not found

**Comment by yyx990803** [comment]
1. Please make sure to provide proper reproduction
2. This could be either a problem in `vue-shortkey` itself or with Nuxt - either way it should not be reported here.

**Comment by leopiccionia** [comment]
@madhuadbanker The `document not found` error makes me believe that the plugin is not SSR-compatible. Telling Nuxt to just install the plugin on client-side, like [this example](https://nuxtjs.org/guide/plugins/#client-side-only), maybe solves your problem.

**Comment by madhuadbanker** [comment]
@leopiccionia thank you I have implemented as shown in that nuxt documentation client side only, it works by giving ssr:false

**Comment by AlanRezende** [comment]
@madhuadbanker can you share the `vue-shortkey.js` plugin code?
