### ISSUE TITLE
I write directive ，I want to use a attribute in  update，this attribute is create bind

### ISSUE THREAD

**Issue by shiqian123** [vuejs/vue#9690]
### Version
2.5.20

### Reproduction link
[https://jsfiddle.net/9ag4xtvu/12/](https://jsfiddle.net/9ag4xtvu/12/)

### Steps to reproduce
I want to get an initialized value for comparison。
Vue.directive('diff', {
  inserted: function (el,bind,vnode) {
    bind.initData = bind.value
    console.log(vnode)
  },
  update:function(el,bind,vnode){
    console.log(bind.initData)
  }
})

### What is expected?
in update, bind.initdata will have value

### What is actually happening?
bind.initdata  is undefined

**Comment by posva** [comment]
if you want to add data, add it to the element itself

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!

**Comment by shiqian123** [comment]
I want to get an initialized value for subsequent comparisons
