### ISSUE TITLE
self-closed HTML tag with v-html does not work correctly

### ISSUE THREAD

**Issue by ttlg** [vuejs/vue#9695]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/k6hxzmjc/5/](https://jsfiddle.net/k6hxzmjc/5/)

### Steps to reproduce
render  `<div style="background-color:red;" /><div>bar</div>` with v-html become `<div style="background-color:red;"><div>bar</div></div>`

### What is expected?
We want:
`<div style="background-color:red;"></div><div>bar</div>`

Not this:
`<div style="background-color:red;"><div>bar</div></div>`

### What is actually happening?
self closed tag wraps subordinate tags

**Comment by Justineo** [comment]
`<div style="background-color:red;" />` is not valid HTML. `v-html` uses `.innerHTML` under the hood so it's never expected to work.

**Comment by ttlg** [comment]
thank you for your comment!
