### ISSUE TITLE
Bootstrap dropdown not closed if class is assigned

### ISSUE THREAD

**Issue by j3ca** [vuejs/vue#9696]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/j3ca/yjzh12kg/6/](https://jsfiddle.net/j3ca/yjzh12kg/6/)

### Steps to reproduce
- Create a simple bootstrap dropdown
- On the .dropdown element include v-bind:class{'some-class': condition}
- Add a @click event to .dropdown-item, and then set condition to true
- Dropdown breaks and it won't close anymore (it does add the class "some-class" but it won't close)

### What is expected?
Dropdown closes when a class is added to .dropdown element

### What is actually happening?
Since the version 2.6.0 the dropdown gets "stuck" where the class "show" is removed from the .dropdown element, but not from the .dropdown-menu

---
This is with the version 2.6.8: https://jsfiddle.net/j3ca/yjzh12kg/6/

If you remove that version and use any <2.6.0 (e.g. https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.22/vue.js) it will work.

**Comment by posva** [comment]
Sorry but this is too much for a repro, it shouldn't contain any bootstrap code yet you have jquery, bootstrap and popper. Come back if you manage to reproduce the problem without those dependencies

It may be linked to https://github.com/vuejs/vue/issues/9340 or https://github.com/vuejs/vue/issues/9615
