### ISSUE TITLE
How to catch $emit event in javascrit

### ISSUE THREAD

**Issue by ShravanMweb** [vuejs/vue#9704]

**Comment by ShravanMweb** [comment]
### Version
2.6.2

### Reproduction link
[https://stackoverflow.com/users/10901207/shravan-sangishetti](https://stackoverflow.com/users/10901207/shravan-sangishetti)







### Steps to reproduce
How to catch $emit event with v-on: in JavaScript. while doing
import MyGrid from 'MyGridcomponemt.vue'
import Vue from 'vue'
var myDynamicGrid = Vue.extend(MyGrid)
var instance = new myDynamicGrid({
propsData: { columns: this.columns,rowsperpage:this.rowsperpage,etc..}
})
instance.$mount() // pass nothing
//Will append to required place
this.$refs.container.appendChild(instance.$el)
Here I am able to pass prosData to MyGrid component but how do I catch those $emit events which will trigger by MyGrid component..


### What is expected?
Can we catch $emit event in  javascript??

How to catch $emit event with v-on: in JavaScript??
My code..
import MyGrid from 'MyGridcomponemt.vue'
import Vue from 'vue'
var myDynamicGrid = Vue.extend(MyGrid)
var instance = new myDynamicGrid({
propsData: { columns: this.columns,rowsperpage:this.rowsperpage,etc..}
})
instance.$mount() // pass nothing
//Will append to required place
this.$refs.container.appendChild(instance.$el)
Here I am able to pass prosData to MyGrid component but how do I catch those $emit events which will trigger by MyGrid component..


### What is actually happening?
How to catch $emit event with v-on: in JavaScript. Dollowing is My code..
import MyGrid from 'MyGridcomponemt.vue'
import Vue from 'vue'
var myDynamicGrid = Vue.extend(MyGrid)
var instance = new myDynamicGrid({
propsData: { columns: this.columns,rowsperpage:this.rowsperpage,etc..}
})
instance.$mount() // pass nothing
//Will append to required place
this.$refs.container.appendChild(instance.$el)
Here I am able to pass prosData to MyGrid component but how do I catch those $emit events which will trigger by MyGrid component..


---
We are appending MyGrid component to its parent grid multiple times(to make subgrid) here parent  gridcomponemt also the same component (MyGrid component). That has been done perfectly but while doing that we can pass only propsData but how to receive $emit event.. please see the following code


How to catch $emit event with v-on: in JavaScript. while doing

import MyGrid from 'MyGridcomponemt.vue'
import Vue from 'vue'
var myDynamicGrid = Vue.extend(MyGrid)
var instance = new myDynamicGrid({
propsData: { columns: this.columns,rowsperpage:this.rowsperpage,etc..}
})
instance.$mount() // pass nothing
//Will append to required place
this.$refs.container.appendChild(instance.$el)
Here I am able to pass prosData to MyGrid component but how do I catch those $emit events which will trigger by MyGrid component..

**Comment by leopiccionia** [comment]
@ShravanMweb https://vuejs.org/v2/api/#vm-on
