### ISSUE TITLE
不被keepAlive  include  包含的组件。在其他组件无name字段的时候  打包后，自动变成缓存组件。

### ISSUE THREAD

**Issue by 672064406zerui** [vuejs/vue#9705]
### Version
2.5.2

### Steps to reproduce
 keep-alive :include='keepAliveComponents'
=》keepAliveComponents=['a','b']
c组件 name=""
本地的时候一切正常，打包后。c组件变成缓存组件，并触发activaed生命周期

### What is expected?
本地和打包后 状态一致

### What is actually happening?
本地和打包后 状态分歧

---
希望vue 可以越来越好

**Comment by Justineo** [comment]
请提供一个有效的重现环境，谢谢。可以参考 issue helper 中的说明。
