### ISSUE TITLE
v-for can access 'this' key word

### ISSUE THREAD

**Issue by zhangenming** [vuejs/vue#9708]
### Version
2.6.8

### Reproduction link
[https://codepen.io/zhangenming/pen/Ygaqjb](https://codepen.io/zhangenming/pen/Ygaqjb)

### Steps to reproduce
open

### What is expected?
v-for can't access 'this' key word

### What is actually happening?
v-for can access 'this' key word

**Comment by posva** [comment]
Don't use this in templates

**Comment by zhangenming** [comment]
> Don't use this in templates

so is it a bug?

**Comment by posva** [comment]
no, never use `this` in templates. You can check existing issues about it if you want more info but to summarize it is not guaranteed to work

**Comment by Justineo** [comment]
F.Y.I. You can use `eslint-plugin-vue` to help you prevent using `this` in templates. See: https://eslint.vuejs.org/rules/this-in-template.html
