### ISSUE TITLE
v-bind only if child is expecting a prop

### ISSUE THREAD

**Issue by pdcmoreira** [vuejs/vue#9712]
### What problem does this feature solve?
Let's say we're using dynamic components to switch between tabs. Each tab is a component.
In the parent component, we have a bunch of data that might or might not be useful/required to the children, so we just go ahead and pass all that data as props to the children.
Each child declares some of those props, but less props than the parent is passing, which means that the props the child is not taking are being attached to the DOM as attributes.

My proposal is a modifier for `v-bind` that tells Vue that it should only consider the `v-bind` if the child is expecting it, so that data doesn't leak to the DOM.

### What does the proposed API look like?
Since `.prop` is already taken, I can't think of a good modifier name right now. `.ifexpected` comes to mind.

**Comment by posva** [comment]
use `inheritAttrs: false`
