### ISSUE TITLE
使用vue,js前端输入框，输入中文带字母 比如输入 “我的“ 显示 ”wd我的”

### ISSUE THREAD

**Issue by youliang999** [vuejs/vue#9716]
### What problem does this feature solve?
使用vue,js前端输入框，输入中文带字母 比如输入 “我的“ 显示 ”wd我的”

### What does the proposed API look like?
使用vue,js前端输入框，输入中文带字母 比如输入 “我的“ 显示 ”wd我的”

**Comment by posva** [comment]
Stop opening issues without following the reporting guidelines or we will have to block you. Thanks

**Comment by Justineo** [comment]
@youliang999 

在创建 issue 时请仔细阅读说明并填写必要的内容。不要随意填写语焉不详的内容，帮助节约别人的时间才更可能得到别人的帮助，谢谢。

[传送门&rarr;](https://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn)
