### ISSUE TITLE
Why does computed change trigger filters?

### ISSUE THREAD

**Issue by GreenMashimaro** [vuejs/vue#9722]
### Version
2.6.8

### Reproduction link
[https://codepen.io/GreenMashimaro/pen/qvYNGE?editors=1111](https://codepen.io/GreenMashimaro/pen/qvYNGE?editors=1111)

### Steps to reproduce
Create a new timer, add a computed, and the computed change triggers the filter change

### What is expected?
filters:flt. It will only be triggered once

My understanding is that filters will only be triggered once, because there is no correlation between myself. step_count and cpt_val.

### What is actually happening?
Computed change trigger filters.

**Comment by LinusBorg** [comment]
> My understanding is that filters will only be triggered once, because there is no correlation between myself. step_count and cpt_val.

You are mistaken. The whole template is re-evaluated whenever a dependency changes, which means the filter runs each time as well.
