### ISSUE TITLE
<noscript> -> The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by MichaelJCole** [vuejs/vue#9724]
### Version
2.6.8

### Reproduction link
[https://stackoverflow.com/a/49202327/1483977](https://stackoverflow.com/a/49202327/1483977)

### Steps to reproduce
Facebook pixel is an analytics tracking pixel.  The code includes a <noscript> backup tag.  

When my default layout template includes this noscript tag I get an error like this one:
  
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

### What is expected?
No warnings

### What is actually happening?
Unnecessary warnings (Vue doesn't render noscript tags) or a bug (Vue does render noscript tags)

vue.runtime.esm.js:587 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

---
This is using Vue bundled in Nuxt 1.0

**Comment by posva** [comment]
For analytics, you probably want to avoid rendering during ssr with no ssr component or client only plugins in nuxt 

Please, next time ask questions on forums or discord. Hwne reporting a bug, make sure to provide a minimal runable repro

**Comment by MichaelJCole** [comment]
@posva Please re-read the issue.  "Unnecessary warnings (Vue doesn't render noscript tags) or a bug (Vue does render noscript tags)"

This is either a bug rendering <noscript> or a warning message bug that <noscript> won't be rendered.
