### ISSUE TITLE
v-model not working inside scoped slots

### ISSUE THREAD

**Issue by panayotov** [vuejs/vue#9726]
### Version
2.6.8

### Reproduction link
[https://codepen.io/bassta/pen/vPrYdY](https://codepen.io/bassta/pen/vPrYdY)

### Steps to reproduce
1. Create new component, add slot to it, bind some data to the slot
2. Create new instance of the component, add input inside slot, bind v-model to it.

### What is expected?
Component data, bind to v-model to change

### What is actually happening?
Nothing, doesn't throw error

---
Showing data works, binding v-model to data does not.

**Comment by posva** [comment]
you are not supposed to modify the data you pass to a slot, pretty much like a prop.
You should pass a method instead to change tha value. You can always pass an object and modify a property (like a prop) but it's also not recommended

**Comment by rjurado01** [comment]
Is this recommendation still valid with Vue 3?

I have tested that binding works with object properties: https://jsfiddle.net/rjurado/un3sdqte/4/

**Comment by InToSSH** [comment]
I would like to know this too. I am currently using this with object properties for my form component. It is all working, just one quirk I found is that if you use the DevTools extension it will not autoupdate and you have to click the refresh button to see the value of object props.
