### ISSUE TITLE
vue 2.6.9, the click event can't bubble on some browsers such as UC browser on all android 8.x, part android 6.x or 9.x

### ISSUE THREAD

**Issue by kobe990** [vuejs/vue#9729]
### Version
2.6.9

### Reproduction link
[https://github.com/kobe990/testVue](https://github.com/kobe990/testVue)

### Steps to reproduce
1. clone the repository from https://github.com/kobe990/testVue
2. npm i (including the vue 2.6.9)
3. npm run dev
4. use the latest UC browser on android 8.x to open this server URL
5. we will see two div (one is a parent div, another is a child)
6. we bind a click event on the parent div
7. when We click the child div, the click event won't be triggered. If we change the vue version to 2.6.8, It is all right.

### What is expected?
the click event can bubble correctly

### What is actually happening?
the click event can't bubble correctly in the  vue router render page.

**Comment by yyx990803** [comment]
Cannot reproduce on Android 9. Is this only for Android 8? Does it affect a specific version of UC browser?

**Comment by kobe990** [comment]
Thanks for reply. I have tested some mobile phone. currently I find this issue on any UC version on all android 8.x , part of Android 6.x and part of android 9.x. Due to some app also use the js core engine from UC, so the issue also happen in these apps.

**Comment by yyx990803** [comment]
This is probably related to this commit: https://github.com/vuejs/vue/commit/7591b9dc6dde314f2d32dcd7a8355f696a330979

Can you modify your local Vue.js in `node_modules` and check what the value of `e.timeStamp` is in your test case?

**Comment by kobe990** [comment]
I also find a strange thing:
if I render the page by the vue-router(<router-view  />), This issue happen.
if I don't use the vue-router, it is ok ( in my sample project, If I copy the file 'src/view/mobile/ddbindcard/ddbindcard.vue'  to the file 'src/view/mobile/index.vue'), this issue will disappear. So strange.

**Comment by kobe990** [comment]
test it on the mobile phone where the issue happen, some result is blow:
attachedTimestamp is very big, such as: 1552906521442
e.timeStamp is normal, such as:  30791

I think the attachedTimestamp is a little Suspicious, because it's value is small on the normal device

**Comment by kobe990** [comment]
I debug the node_moudles, I think this is related to this commit: https://github.com/vuejs/vue/commit/ef2a380c6eb6bd1a7ff516c357dafa717e75a745

I change it back to before. All things are right

**Comment by baiyaaaaa** [comment]
I trigger this bug too.

**Comment by felixbuenemann** [comment]
@yyx990803 JSDOM also has low-res timestamps on events, so I think your fix can break on JSDOM.

It would be interesting to find out why this breaks in UC browser.

**Comment by felixbuenemann** [comment]
Also this switches from feature detection to user agent detection, which is usually not a good idea.

**Comment by felixbuenemann** [comment]
@kobe990 I can't reproduce with UC Browser for windows, it seems to be based on Chromium.

What exact version did you use? Can I test with the Java-Version on a PC/Mac?
