### ISSUE TITLE
Vue not preserving background-related inline styles after component redraw

### ISSUE THREAD

**Issue by petrnagy** [vuejs/vue#9730]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/5x81bd6z/](https://jsfiddle.net/5x81bd6z/)

### Steps to reproduce
Just wait 10s for the setTimeout to kick in.

The problem is that after the component is redraw, only the background: url(img) is preserved, but the other background-related inline styles are ignored. For example "background-size: cover".

You will see that after 10s, not only the order of < li > elements will change, but the backgrounds will change too.

### What is expected?
Change the order of < li > elements and preserve all inline styles.

### What is actually happening?
Only part of the inline styles of < li > are preserved after component redraw.

**Comment by yyx990803** [comment]
`background` is a shorthand property, when set it overwrites all other background related properties. Using an object, iteration order is not guaranteed (depends on browser), so the behavior cannot be consistent.
Use `background-image` instead.

**Comment by petrnagy** [comment]
@yyx990803 I think you are addressing slightly different problem.

This part of code is generated by vue template upon the component mount
`<div style="background: url("https://images.freeimages.com/images/large-previews/675/fruit-1328048.jpg") center center / cover no-repeat; min-height: 50px; padding: 10px; color: white;">`

This is the same part after changing the value of instance property (array `stuff` in the example)
`<div style="background: url("https://images.freeimages.com/images/large-previews/675/fruit-1328048.jpg"); min-height: 50px; padding: 10px; color: white;">`

After the partial redraw, some of the inline css properties are missing for no reason.
