### ISSUE TITLE
[2.6.9] Transition enter broken

### ISSUE THREAD

**Issue by frlinw** [vuejs/vue#9735]
### Version
2.6.9

### Reproduction link
[https://codepen.io/frlinw/pen/zbLOZq](https://codepen.io/frlinw/pen/zbLOZq)

### Steps to reproduce
click the "click me" zone

### What is expected?
the red block should fade in

### What is actually happening?
the enter transition is ignored

**Comment by frlinw** [comment]
Probably related to https://github.com/vuejs/vue/commit/4de4649d9637262a9b007720b59f80ac72a5620c

It works if I add `appear` to te transition tag.

But to me it look like a breaking change

**Comment by posva** [comment]
You need the appear as you are toggling the transition component itself instead of the inner content

**Comment by frlinw** [comment]
@posva yes, I figured out but is it not what we can call a breaking change as it break the existing ? (and there is no notes about it, except the doc itself which does not specify it was introduced in 2.6.9)

**Comment by posva** [comment]
no, it was wrong before when it shouldn't have

**Comment by yyx990803** [comment]
It is indeed different behavior, but the old behavior is "wrong" so it's considered a fix.

**Comment by frlinw** [comment]
@yyx990803 Of course and now I can see how inconsistent was the previous behavior (even if It was exactly what I wanted).

You are right when you say it's a bugfix, but it is only in the library perspective. 
it's a 2,5 years old bug (or even older) that means lot of people started to use Vue as if this issue was the normal behavior and in usage, for a lot of people, it will be a breaking change.

I didn't know about `appear` before then (because it worked without it) and I didn't know something was wrong with it, there are plenty of guides/examples/tuto which does not talk about `appear` even in the vue example https://vuejs.org/v2/examples/modal.html

**Comment by yyx990803** [comment]
@frlinw yes, but the behavior is indeed incorrect based on how `<transition>` is supposed to work.
