### ISSUE TITLE
event bus between dynamic sibling component

### ISSUE THREAD

**Issue by umi-soft** [vuejs/vue#9740]
### What problem does this feature solve?
Component A has two children dynamic sibling components， B and C。
how to use event bus？
when component C change to B， C want to change the state of B

### What does the proposed API look like?
I have no idea about event bus between dynamic sibling component

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
