### ISSUE TITLE
Access to data from slot's component

### ISSUE THREAD

**Issue by gbiorczyk** [vuejs/vue#9743]
Hi,

I have a problem with accessing data from the component using slots.

Here's my code:
https://codepen.io/anon/pen/BbOEZz/

I want the line:
`<p slot="desc">{{ desc_01 }}</p>`

It started working and at the slot in the template displayed the value with date.

Can anyone help me with this matter?

**Comment by pikax** [comment]
```vue
<div id="app">
  <layout>
    <p slot="desc">{{ desc_01 }} </p>
  </layout>
</div>
```
This slot is using vue instance not the `layout` component.

if you add the data to your vue instance it works as expected.
```js
new Vue({
  el: "#app",
  data() {
     return {
       desc_01: 'app description'
     }
  }
});
```
check the https://codepen.io/anon/pen/RdYXpb
