### ISSUE TITLE
能否在v-html加个xss修饰符防止xss攻击

### ISSUE THREAD

**Issue by qqcbqqkcel** [vuejs/vue#9746]
### What problem does this feature solve?
通过过滤掉xss攻击代码来解决v-html容易导致的xss攻击

### What does the proposed API look like?
v-html.xss

**Comment by Justineo** [comment]
Duplicate of #6333

This can be implemented in userland. eg. You can define a plugin like:

```js
Vue.prototype.$sanitize = function (html) {
  // return sanitized HTML
}
```

And then use it in `v-html`:

```html
<article v-html="$sanitize(rawContent)"></article>
```

**Comment by qqcbqqkcel** [comment]
这种够不优雅
