### ISSUE TITLE
slot-scope cannot be written on <slot> tag after version 2.6.x

### ISSUE THREAD

**Issue by xpal7512** [vuejs/vue#9748]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/GewZMr?editors=1010](https://codepen.io/anon/pen/GewZMr?editors=1010)

### Steps to reproduce

2.5.22 demo1 : https://codepen.io/anon/pen/moQEmx （Ignoring the text on the \<h2\> tag, the actual Vue version referenced is 2.5.22）
![image](https://user-images.githubusercontent.com/20216981/54761399-fbe6f500-4c2c-11e9-8abd-d46813a58c19.png)

===========================

2.6.x demo2: https://codepen.io/anon/pen/GewZMr?editors=1010 
![image](https://user-images.githubusercontent.com/20216981/54761278-c3dfb200-4c2c-11e9-9763-bf7b665e265f.png)

### What is expected?
display normailly

what’s the different between demo1 and demo2？

### What is actually happening?
```
<slot slot-scope="props">
  <a>123</a>
</slot>
```
this part can't display on the page

**Comment by posva** [comment]
The workaround would be to use a `template`. As we move to the `v-slot` syntax to unify normal and scoped slots I'm not sure it is worth to support this

**Comment by yyx990803** [comment]
I don't think we ever intended to support this. The semantics is quite vague and I think it's better to not work at all.
