### ISSUE TITLE
vue template es2015 compiler can allow 'Error'  as global variable in Vue render functions?

### ISSUE THREAD

**Issue by newdefence** [vuejs/vue#9750]
### What problem does this feature solve?
在后台系统里，经常会做很多自定义输入验证，在写验证函数的时候，经常需要抛出Error来表示用户输入不合理；
常用的类库有 https://github.com/yiminghe/async-validator
但是如果直接 new Error('Error Message') 抛出错误，则会提示 Error 未定义，目前解决方案是：Vue.prototype.Error = Error;
如果作者觉得此类场景太小众，或者不符合 Vue 代码规范风格，可以直接关闭此 Feature；
涉及到的源码在 src/core/instance/proxy.js

### What does the proposed API look like?
// allowed globals in Vue render functions.
// same as in src/core/instance/proxy.js
var names = 'Infinity,undefined,NaN,isFinite,isNaN,'  
  'parseFloat,parseInt,decodeURI,decodeURIComponent,encodeURI,encodeURIComponent,'  
  'Math,Number,Date,Array,Object,Boolean,String,RegExp,Map,Set,JSON,Intl,'  
  'require,'   // for webpack
  'arguments,'   // parsed as identifier but is a special keyword...
  '_h,_c'; // cached to save property access (_c for ^2.1.5)

添加一个 Error

**Comment by yyx990803** [comment]
Don't do this in templates... just use a method.
