### ISSUE TITLE
How do I identify whether the V-for node is done with DOM rendering?

### ISSUE THREAD

**Issue by wangqipov** [vuejs/vue#9752]
Hello, I want to perform some methods when the V-for rendering page is finished after the data update. How do I identify whether the V-for node is done with DOM rendering?

**Comment by Justineo** [comment]
bot 的回复能不能阅读一下呢？

---
PS.

Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
