### ISSUE TITLE
"checked" property not being properly set on checkbox inputs in latest Chrome & Firefox

### ISSUE THREAD

**Issue by JonathonAshworth** [vuejs/vue#9753]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/boilerplate/vue](https://jsfiddle.net/boilerplate/vue)

### Steps to reproduce
Open the VueJS boilerplate on JSFiddle, toggle the checkboxes, and look in the console to see whether the "checked" property is being set when the checkboxes are checked

### What is expected?
`<input type="checkbox" checked="checked" />`

### What is actually happening?
`<input type="checkbox" />`

---
Just in case it's OS or other environment related, here's a video of it happening to me on Chrome 71/macOS 10.14

https://gfycat.com/forthrightacademichammerheadbird

It also happens on Firefox 65.

I'm also not 100% sure on the version since JSFiddle doesn't seem to mention which version it is running (other than 'edge').

**Comment by yyx990803** [comment]
When using dynamic binding, `checked` is bound as a DOM property instead of an attribute. The attribute only applies to the initial value.
