### ISSUE TITLE
this.$root.$off unsubscribes all instances of component from event

### ISSUE THREAD

**Issue by rreckonerr** [vuejs/vue#9755]
### Version
2.5.21

### Reproduction link
[https://codesandbox.io/s/lrk25l907l](https://codesandbox.io/s/lrk25l907l)

### Steps to reproduce
Click buttons in the following order: Step 1 => Step 2 => Step 3

### What is expected?
It is expected that only one instance of multiple components will get unsubscribed from event on destroy. 

### What is actually happening?
All components get unsubscribed instead.

---
https://stackoverflow.com/questions/55297461/vue-this-root-off-unsubscribes-all-instances-of-the-component-from-the-glob

**Comment by posva** [comment]
You need to pass a function to not remove all event listeners:

```js
mounted() {
    this.fn = () => {
      this.toggleWarning();
    }
    this.$root.$on("triggerChildComponents", this.fn);
  },
  beforeDestroy() {
    this.$root.$off("triggerChildComponents", this.fn);
  },
```

**Comment by jetlej** [comment]
What if you need to grab a parameter from the $emit function and pass it to the callback function?
