### ISSUE TITLE
new Vue can return promise from mounted event?

### ISSUE THREAD

**Issue by powerbilayeredmap** [vuejs/vue#9762]
### What problem does this feature solve?
restarting the discussion of #7209 - I would like to do the following

console.log(1);
var v = await new Vue({
mounted:async function(){
await $.get('somescript');
console.log(2);
}
})
console.log(3);

and have console log 1,2,3.

Currently I need to wrap Vue loading into a new Promise(resolve,reject), and its not as nice.

### What does the proposed API look like?
console.log(1);
var v = await new Vue({
mounted:async function(){
await $.get('somescript');
console.log(2);
}
})
console.log(3);

**Comment by posva** [comment]
For Vue created an instance, you would instead do the promise first and then mount the instance. It would also be a bad idea to support this for new Vue only
