### ISSUE TITLE
在data里某个字段初始化为0，但是mounted使用的时候突然变成1，但在created中没有问题

### ISSUE THREAD

**Issue by objcxiaobai** [vuejs/vue#9763]
### Version
2.5.22

### Reproduction link
[https://jsbin.com/?html,js](https://jsbin.com/?html,js)

### Steps to reproduce
```
data (){
        return {
          pageNo: 0
        }
  },
  mounted: function () {
    this.xxxx()
  },
  methods:{
   xxxx(){
   const self = this;
  //此时self.pageNo变为1
  axios.get('/xxx/xxx/xxxx', { parame: { page: self.pageNo, size: 10 } })
          //xxx
 	}
 }
```

### What is expected?
解决变1的问题

### What is actually happening?
变为1

---
没有

**Comment by Justineo** [comment]
Please provide a valid reproduction. Thanks.
