### ISSUE TITLE
Vue does not support set custom indexer on custom iterable types

### ISSUE THREAD

**Issue by lianzhao** [vuejs/vue#9766]
### Version
2.6.10

### Reproduction link
[https://github.com/lianzhao/vue-iterable-indexer](https://github.com/lianzhao/vue-iterable-indexer)

### Steps to reproduce
click the button on UI

### What is expected?
Prints `10, 3, 4, 5` on UI

### What is actually happening?
Prints `2, 3, 4, 5`
![image](https://user-images.githubusercontent.com/536786/54867943-d0e1da00-4dc1-11e9-93a0-743027b8d361.png)

---
I implemented `CircularBuffer` which implements `Iterable`. It also implements get/set indexers by `Object.defineProperty`.

But `this.$set(this.items, 0, 10)` was not working. What can I do to except waiting for Vue 3.0?

**Comment by Justineo** [comment]
This is an expected behavior. Vue only supports reactive `Array` and `Object`.

**Comment by lianzhao** [comment]
OK, I found a solution.

In `circularBuffer.ts`, instead of `this.items[this.getIndex(index)] = element`, I should `Vue.set(this.items, this.getIndex(index), element)`
```typescript
  public setEelementAt(index: number, element: T) {
    if (this.size === 0) {
      throw new Error('Index out of range');
    }
    // this.items[this.getIndex(index)] = element;
    Vue.set(this.items, this.getIndex(index), element);
  }
```

But it just feels so wrong to `import Vue` in my `circularBuffer.ts`...

**Comment by Justineo** [comment]
Yeah if you implementation uses plain `Array` under the hood, you shall always ensure reactivity yourself.
