### ISSUE TITLE
Layout overlapping while having multiple layouts

### ISSUE THREAD

**Issue by techyaura** [vuejs/vue#9767]
### Version
2.6.10

### Reproduction link
[https://vuetify-template.netlify.com/login](https://vuetify-template.netlify.com/login)

### Steps to reproduce
1. Go to https://vuetify-template.netlify.com
2. Refresh  hard refresh the app
3. While refreshing, one can see  fluctuating effect of the default layout.

### What is expected?
Default layout appears for some moment while refreshing th login page which belong to login layout.

### What is actually happening?
NO fluctuation or calling of the default layout should be appeared.

---
Github code link: https://github.com/techyaura/vuetify-template

**Comment by posva** [comment]
Hey, this is way too much for a repro. There is not even a thing as layouts in Vue. If you want to reporta hug please provide a boiled down repro with no extra dependencies (no vuetify)
