### ISSUE TITLE
Cannot escape quotes in String

### ISSUE THREAD

**Issue by woothu** [vuejs/vue#9768]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/zbbaEp?editors=1010](https://codepen.io/anon/pen/zbbaEp?editors=1010)

### Steps to reproduce
Click on the link.

### What is expected?
Quote escaping works the same both in template and javascript.

### What is actually happening?
Quote escaping doesn't work in templates.

**Comment by posva** [comment]
HTML escaping is different from JS, you must use `  <div v-text="'<div style=&quot;background-color:red;&quot;>Red block</div>'">`

Note this isn't related to Vue though

**Comment by woothu** [comment]
Ok, thank you ;)
