### ISSUE TITLE
v-for stops video tag when array of videos is updating

### ISSUE THREAD

**Issue by Trunst** [vuejs/vue#9770]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/w95tp610/3/](https://jsfiddle.net/w95tp610/3/)

### Steps to reproduce
This is a small test for keeping a object in a list of videos. When clicking on "Keep" on any of the videos then the others will be removed.

Click on "Keep" for video with id 2. It works fine for id 1 and 3 (start and last element in array) but not for anything in the middle

### What is expected?
That the video continues playing.

### What is actually happening?
The video freezes

---
This issue occurs for me in chrome (62.0) but works as expected in firefox

**Comment by posva** [comment]
I would say this is coming from that version of Chrome, it works fine on the current version, it's probably pausing it
You may be interested in https://github.com/vuejs/vue/issues/4362

**Comment by Trunst** [comment]
Thanks, issue was solved after upgrading chrome

**Comment by Trunst** [comment]
@posva 
Hi again, not sure if this is related but I have similar issue now but with transition

https://jsfiddle.net/bah2jqxo/

When I click on "keep" on Title 2, then the css transition wont be run. However it works fine for Title 1 and 3. Is this an issue or should I be using something else for this type of behavior?
