### ISSUE TITLE
Can't `v-for` be used for Set data types?

### ISSUE THREAD

**Issue by longzhangtong** [vuejs/vue#9780]
### What problem does this feature solve?
```
"vue": "^2.6.6",
```
Try to use the `v-for` to traverse the Set data type, but it doesn't work.

### What does the proposed API look like?
Traversing the Set data type using `v-for`

**Comment by Justineo** [comment]
It works. https://jsfiddle.net/Justineo/a9tbpoen/

But `Set` data won't be reactive due to current limitations. This will be addressed and solved in Vue 3.

**Comment by longzhangtong** [comment]
Thank you

GU Yiling <notifications@github.com> 于2019年3月27日周三 下午12:29写道：
