### ISSUE TITLE
Load first SPA settings internally while being set by the user from a UI

### ISSUE THREAD

**Issue by FreddyCrugger** [vuejs/vue#9783]
### What problem does this feature solve?
Hello,

At the moment when I write an app and have an area in my UI that let's the user set his own settings(ie: show newsletter, home page title , keywords and so on), I have load all from an API and save it all to local storage which takes time.
If vue had some kind of read/write possibility to a settings file we could then set all these settings internally while being written by the users themselves from the admin panel UI. Will these ever be possible in the future? Or perhaps is it already? I cannot find any docs on this. Thanks.

### What does the proposed API look like?
Having some logic that enables use to read/write to an internal file

**Comment by posva** [comment]
Thanks for your interest but this is outside of Vue range and should be included in a library
