### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by antonstsk** [vuejs/vue#9790]
Hey every one, just wanted to ask.
Is there some reason to name a function as variable in JavaScript?

(I mean using `Dep` two times. Just was crawling in Vue.js and found this)

´´´javascript
var Dep = function Dep () {
    this.id = uid++;
    this.subs = [];
  };
´´´

Just say yes/no, don't bother to explain, I'll search it by myself.
Thanks!

**Comment by posva** [comment]
Anonymous vs non Anonymous functions, stack traces and variable hoisting. Looking these up should help you

**Comment by multics** [comment]
yes
