### ISSUE TITLE
vm._data.__ob__  is used less often than dep:{ id, deps } which is created in defineReactive.

### ISSUE THREAD

**Issue by lxx2013** [vuejs/vue#9792]
### Version
2.6.10

### Reproduction link
[https://codepen.io/lxx2013/pen/bJbzVr?editors=1010#0](https://codepen.io/lxx2013/pen/bJbzVr?editors=1010#0)

### Steps to reproduce
Actually I am reading Vue's source code recently. 
- I noticed that **`vm._data.__ob__` might never be used**. 
- In contrast, the `const dep = new Dep( )` in closure of `defineReactive` is often used when data changes.

In my code , I add some logs to Dep.prototype:
```js
//...
  window.deps = []
  window.depsInOb = []
  var Dep = function Dep () {
    this.id = uid  ;
    this.subs = [];
    window.deps.push(this)
  };
//...
Dep.prototype.notify = function notify () {
    var str = window.depsInOb.indexOf(this) == -1 ? "Closure Dep":"vm._data.__ob__.dep"
    console.log(`Dep notify: id:${this.id}, type:${str}, watchers:`,this.subs)
    //...
}
function Observer (value) {
    this.value = value;
    this.dep = new Dep();
    window.depsInOb.push(this.dep);
    this.vmCount = 0;
    def(value, '__ob__', this);
    //...
}
```

### What is expected?
For example, when the value of `vm._data.text` has changed, it will notify watchers in its `subs`, which is easy to find in `vm._data.__ob__` or other `__ob__`  in Nested Objects from `vm.$data`.

### What is actually happening?
- The `subs` (or we can call its constructor's name -- `Dep`) in `__ob__` will be less often used. 
- Even sometimes it has 3 watchers, but it won't be `notify` when data changes. 
- Instead, the `Dep` which was created like `const dep = new Dep()` in `function defineReactive()` is mostly used when data changes.

---
The follow image is an example from Chrome's console. 
![](https://i.loli.net/2019/03/30/5c9f73d8a674f.png)
In this example , vue created **6** `Dep`, but only `3,4,5` is useful, while `0,1,2` is useless( because vue don't allow to change the root data object --- `vm.$data`), and `0,1,2` has no watchers to depend them. 

These `__ob__` will not affect page rendering. Maybe some parts do have functions I haven't found yet, but **it's undeniable that some of them inevitably cause extra memory waste**.

I hope Vue can make full use of every memory it requires. And if deps in `__ob__` **(instead of deps in closures)** can show mores useful infos in console, it would be even better.

**Comment by yyx990803** [comment]
The root data object of one component may be used in another component's data as a nested object, so its `__ob__` is still necessary. Special casing it to save minor memory usage without benchmarks showing it being the bottleneck seems to be over-optimization.
