### ISSUE TITLE
Please add an "abandon 996" badge (not a clause) to support us

### ISSUE THREAD

**Issue by bofeiw** [vuejs/vue#9793]
### What problem does this feature solve?
[Chinese software engineers are protesting against the country ’ s 996 work schedule.](https://996.icu/#/en_US)
An unleagal work schedule (9a.m. ~ 9p.m., 6 days a week) .

Add a badge
---
Add a badge to your awesome project by pasting this line in your README.md.

```html
<a href="https://996.icu"><img src="https://img.shields.io/badge/link-996.icu-red.svg"></a>
```
<a href="https://996.icu"><img src="https://img.shields.io/badge/link-996.icu-red.svg"></a>

### What does the proposed API look like?
no API

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue/issues/9791#issuecomment-478250030
