### ISSUE TITLE
unbind of custom directives dispatched wrong DOM event flow

### ISSUE THREAD

**Issue by schaoss** [vuejs/vue#9794]
### Version
2.6.10

### Reproduction link
[https://codepen.io/GaryChu/pen/EJYRKz?editors=1011](https://codepen.io/GaryChu/pen/EJYRKz?editors=1011)

### Steps to reproduce
1. Click text.
2. Click again
3. Check the output of console

### What is expected?
It should print:
- bind
- unbind
- \>\>\> bubbling
- \>\>\> capturing

or

- bind
- unbind

### What is actually happening?
It prints:
- bind
- unbind
- \>\>\> capturing

---

according to [W3C event model](https://www.w3.org/TR/DOM-Level-3-Events/#event-flow) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener):

> Events in the target phase will trigger all listeners on an element regardless of the useCapture parameter.

unbind of custom directives should remove all event listener, or trigger all event listener include both capture's and bubble's

**Comment by Justineo** [comment]
I don't think it's a bug. It's just because the event handler of bubbling phase is removed before it has a chance to be triggered. See: https://codepen.io/anon/pen/yrLVJj?editors=1011
