### ISSUE TITLE
how to remove vue meta

### ISSUE THREAD

**Issue by farhanrahmadi** [vuejs/vue#9795]
### Version
2.6.10

### Reproduction link
[https://togiri.herokuapp.com/](https://togiri.herokuapp.com/)

### Steps to reproduce
just see the source ctrl   u

### What is expected?
theme should be #183650
favicon shoudl be there 
favicon not show in another route

### What is actually happening?
theme #4DBA87
favicon still using default vue

---
my guess is because vue override his own meta

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
