### ISSUE TITLE
Proposal: slotted attributes

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/vue#9796]
### What problem does this feature solve?
Often times, I have a situation where I have a reusable component that I've built, but I want to expose one of the child nodes as a "target" of sorts where attributes can be added to or modified. Now, I could add a property or event-listener on the parent specifically to be used by the child, but often times its difficult to think of the different attributes the end user of the component might want to modify, or the events they'd like to listen to on this target child. I COULD add a large set of optional properties, prefixed by some descriptor to indicate what sub-part of the component they will be applied to (e.g `$props = {  bodyClass,  footerClass, menuClass }, $listeners =  { footerClicked, headerFieldChanged}`... etc), but this has a few drawbacks:

  - its inelegant
  - its very verbose
  - its utility is limited by my ability to think of all the attributes on a child target that I or someone using this component might want to modify or extend, and that doesn't even touch on if the consumer wanted to add a directive.

And so, my proposal is that Vue add a new feature, which I admittedly couldn't think of a good name for, so I went with `slotted-attributes` for now. Mostly because I think the cleanest implementation would be an extension of slots. I realize this name has good deal baggage that could confuse users, though, so I'm not attached to this name or the slots approach inherently, mostly just the feature, in some form or fashion.

### What does the proposed API look like?
I have a suspicion this will be seen as a convolution of the API, but to me, most intuitive way to implement this would simply be to add a `attrs` modifier to the `v-slot` directive. For example:

_Template using the the slotted attributes_
```html
<template>
  <base-layout>
    <!-- Seems weird to use the "template" tag for this, but I was just trying to be consistent with other slots -->
    <template #header.attrs @click="headerClicked" class="header-class" title="headerText"/>
    <template #body>
      /*slot stuff*/
    </template>
    <template #footer>
      /* slot stuff */
    </template>
  </base-layout>
</template
```

_Component template_
```html
<div>
  <!-- Some header component that takes a `title` prop, I admittedly struggled to think of a good way for the slot-consuming component to indicate the node the attributes should go to -->
  <HeaderComponent attrs-slot="header" />
  <div class="body">
    <slot name="body"/>
  </div>
  <div class="footer">
    <slot name="footer"/>
  </div>
</div>
```

**Comment by posva** [comment]
This seems like a convoluted way of passing props to me

**Comment by Aaron-Pool** [comment]
@posva First of all, I acknowledge that it's convoluted. I personally couldn't think of a more elegant alternative.

Secondly, it's not _just_ for props. The idea is that it could be anything on the vnode `data` object. Listeners, directives, attributes, etc. My desire was for there to be a way, in a reusable component, that I could give the consumer of the component a way to augment the attributes/directives/listeners on one or _multiple_ target children nodes. I think it provides a more extensible api for creating components that can be consumed by single file components. This is actually something I could do fairly easily in a render function. Unfortunately, most of my team it used to single file components, and expects the components I write to be something easily used withing the constraints of SFCs. Thus this proposal.

**Comment by yyx990803** [comment]
Why not just use a single prop which is an object? It could be any format you wish without having to go through a convoluted API. Most importantly this definitely should not be the concern of Vue core.

**Comment by Aaron-Pool** [comment]
@yyx990803 That unfortunately requires developer knowledge of the vnode interface and data object, which makes it difficult for developers who are newer to the framework to wrap their heads around it.. My hope was for there to be a more template-style api for this.

But cool, I get it. Thanks for giving it a read, in any case. 👍

**Comment by lianulloa** [comment]
Hello @Aaron-Pool 
I needed to be able augment the attributes/directives/listeners for a generic component. I am not sure it is the same case you need it for. I was using the [*component*](https://vuejs.org/v2/guide/components-dynamic-async.html) that vue docs shows to use dynamic components. I was using it like this:

`<component  :is="body" v-bind="bodyConfig" />`

That way I could pass some props to the *body* component. But I couldn't control the content inside *body's* slots neither its on handlers and so on.

I doubt you still need a way to do this, but maybe somebody can get to this issue as I did. So this is what I did

```javascript
export default {
  name: "component-extended",
  inheritAttrs: false,
  props: {
    component: {
      type: Object,
      default: () => null
    }
  },
  render(h) {
    return h(
      this.component,
      {
        // // Same API as `v-bind:class`, accepting either
        // // a string, object, or array of strings and objects.
        class: this.$attrs.class,
        // // Same API as `v-bind:style`, accepting either
        // // a string, object, or array of objects.
        style: this.$attrs.style,
        // // Normal HTML attributes
        attrs: this.$attrs.attrs,
        // // Component props
        props: this.$attrs.props,
        // // DOM properties
        domProps: this.$attrs.domProps,
        // Event handlers are nested under `on`, though
        // modifiers such as in `v-on:keyup.enter` are not
        // supported. You'll have to manually check the
        // keyCode in the handler instead.
        on: this.$attrs.on,
        // // For components only. Allows you to listen to
        // // native events, rather than events emitted from
        // // the component using `vm.$emit`.
        nativeOn: this.$attrs.nativeOn,
        // // Custom directives. Note that the `binding`'s
        // // `oldValue` cannot be set, as Vue keeps track
        // // of it for you.
        directives: this.$attrs.directives,
        // Scoped slots in the form of
        // { name: props => VNode | Array<VNode> }
        scopedSlots: this.$attrs.scopedSlots,
        // The name of the slot, if this component is the
        // child of another component
        slot: this.$attrs.slot,
        // // Other special top-level properties
        key: this.$attrs.key,
        ref: this.$attrs.ref,
        // // If you are applying the same ref name to multiple
        // // elements in the render function. This will make `$refs.myRef` become an
        // // array
        refInFor: this.$attrs.refInFor
      },
      this.$attrs.children
    )
  }
}
```

And the use it like this:

`<sm-component-extended :component="body" v-bind="bodyConfig" />`

```javascript
bodyConfig: {
  children: "Button Text",
  on: {
    click: () => alert('Modal button clicked')
  }
}
```

Hope this can help anybody
