### ISSUE TITLE
Proxy issue between two vue apps when created with vue-cli3

### ISSUE THREAD

**Issue by srchulo** [vuejs/vue#9797]
### Version
2.6.6

### Reproduction link
[https://github.com/srchulo/vue-cli3-proxy-error](https://github.com/srchulo/vue-cli3-proxy-error)

### Steps to reproduce
1. Go into public app and type "yarn serve".

2. Go into app/ and type "yarn serve"

3. Go to http://localhost:8080

4. Open the developer console.

5. Click "Go to App" link in the top right.

6. Observe the console (web socket connection closes before it is established, and failed requests show).

7. Make a change to app/, observe that hot reload will not occur.

### What is expected?
Websockets should successfully be proxied to the Vue app on port 8081 and hot reload for the app on 8081 should work.

### What is actually happening?
The websockets never connect, there are many failed requests, and hot reload does not work.

---

I did not have this issue when my project was on vue-cli2-- it was once I upgraded to vue-cli3 that I saw this issue.

These are some of the errors that I observe:

WebSocket connection to 'ws://localhost:8080/app/sockjs-node/946/btaua0jf/websocket' failed: WebSocket is closed before the connection is established.

POST http://localhost:8080/app/sockjs-node/946/2f03xsro/xhr_streaming?t=1554071918837 404 (Not Found)

GET http://localhost:8080/app/sockjs-node/946/a5xm1iat/eventsource 404 (Not Found)

GET http://localhost:8080/app/sockjs-node/139/crmbubvo/eventsource 404 (Not Found)

**Comment by srchulo** [comment]
Additional error that shows from jsonp?c=_jp.aemoxtb:1:

Uncaught SyntaxError: Unexpected token <

**Comment by srchulo** [comment]
After leaving both servers open long enough and having the page opened to /app, then this error will show in the terminal for the public app:

`Proxy error: Could not proxy request /app/sockjs-node/266/vz0ie5cy/websocket from localhost:8080 to http://localhost:8081.                                                                                          See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).`

**Comment by yyx990803** [comment]
This should reported to `vue-cli` repo instead.

**Comment by srchulo** [comment]
Sorry about that-- I wasn't sure which one to file it under. I will refile. Thanks!
