### ISSUE TITLE
input  number 类型，输入多个 -----后，v-model 失效，取不到值

### ISSUE THREAD

**Issue by chenkanqin** [vuejs/vue#9798]
### Version
2.6.9

### Reproduction link
[https://jsfiddle.net/ser2pnkt/3/](https://jsfiddle.net/ser2pnkt/3/)

### Steps to reproduce
input  number 类型，输入多个 -----后，v-model 失效

### What is expected?
希望能获取得到正确的负数值

### What is actually happening?
input  number 类型，输入多个 -----后，v-model 失效，取不到值

**Comment by posva** [comment]
Only one - will work. BTW you can use the number modifier for v model to get a number back
