### ISSUE TITLE
CSS transition in list is not executed when elements in the middle of a v-for is kept

### ISSUE THREAD

**Issue by Trunst** [vuejs/vue#9799]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/bah2jqxo/](https://jsfiddle.net/bah2jqxo/)

### Steps to reproduce
1. Go to jsfiddle
2. Press "keep" on the second item
3. Try again and press keep on first/last item.

### What is expected?
That the css transition is being applied to all elements regardless of order in the list

### What is actually happening?
The css transition is not running on list elements that is in the middle when everything else is being removed

---
I get this in both chrome (Version 73.0.3683.86) and firefox.

Maybe there is a better way to achieve this with use of transition-group but I tried that but couldn't really understand how I could tweak it to match this case.

**Comment by Justineo** [comment]
You need to use the built-in [`<transition-group>`](https://vuejs.org/v2/api/#transition-group) component for list transitions.
