### ISSUE TITLE
Scoped CSS specificity problem

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue#9801]
### What problem does this feature solve?
Vue achieves scoped css by combining classnames with randomly generated attributes. This increases the specificity of the selectors, making it hard to combine with other CSS libraries.

### What does the proposed API look like?
This is a feature request for scoped css through classnames with a hash, without using attribute selectors.

`.my-class-j04ckg578h`

There should be a way to configure this option on a project level

**Comment by sodatea** [comment]
Have you tried [CSS Modules](https://vue-loader.vuejs.org/guide/css-modules.html)?

**Comment by franciscolourenco** [comment]
@sodatea CSS Modules in Vue have an inferior developer experience since they require you do use this syntax: `:class="$style.red">`.

**Comment by sodatea** [comment]
I think that's a design tradeoff.
Writing `class="my-class"` while transforming it to `class="my-class-j04ckg578h"` is quite misleading - users may expect `.my-class` is also able to target this element.

**Comment by posva** [comment]
What other css libraries? The only classes I find myself using that are supposed to take precedence are utility classes and they usually have an important to make sure they override things. If using something like tailwind, you **want** your scoped CSS to have higher specificity.

I guess an option to customize could make sense but this should go in vue-loader

**Comment by franciscolourenco** [comment]
@sodatea not if the user is aware of the way it works and opted in into the behaviour. This should be an option.

@posva You wrote 2 things which contradict. Tailwind is made of utility classes and it has an option to enable `!important`, to be able to override css which has been written with high specificity. So what you **actually want**, is your utility classes to override the css by default, which they do, as long as you don't use `scoped`.

The reason you want to avoid enabling `!important` in tailwind, and have the lowest possible level of specificity in your code, is to be able to override tailwind by increasing specificity, for instance in media queries, without having to use `!important` all over the place.

Forwarding to vue-loader.

**Comment by franciscolourenco** [comment]
@sodatea also the example you gave could be used to make the opposite argument. Hashed classnames would prevent elements from being accidentally targeted by unscoped css.

**Comment by Justineo** [comment]
Vue Loader’s scoped styles implementation works not only for class selectors. Scoped styles allow any selector so generating hashed class names is not enough.

**Comment by franciscolourenco** [comment]
@Justineo That is a good point, no feature parity. At the same time I have no interest in that feature whatsoever. Can you think of an example where that would actually be a good practice?
