### ISSUE TITLE
ESLint Parsing error: Export 'SimpleSet' is not defined

### ISSUE THREAD

**Issue by rhengles** [vuejs/vue#9803]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
```
npm run lint


vue@2.6.10 lint /mnt/c/vue
> eslint src scripts test


/mnt/c/vue/src/core/util/env.js
  97:15  error  Parsing error: Export 'SimpleSet' is not defined

  95 | 
  96 | export { _Set }
> 97 | export type { SimpleSet }
     |               ^
  98 | 

✖ 1 problem (1 error, 0 warnings)
```

### What is expected?
Test suite run successfully

### What is actually happening?
Test suite doesn't even run because eslint has parse error

**Comment by yyx990803** [comment]
1. Invalid reproduction
2. Wrong repository

**Comment by rhengles** [comment]
@yyx990803 

I honestly don't know of a better reproduction link. If you run this:

```
$ git clone https://github.com/vuejs/vue.git

$ cd vue

$ npm install

$ npm run lint
```

Then the error occurs. It's impossible to even make a commit, because the git commit hook runs `eslint` on the code, which is failing. There is no other source, it's the own Vue codebase and its dependencies. Maybe eslint needs to be updated, maybe Typescript, but I simply don't know how to solve this yet.

One thing I can guarantee is that this has absolutely nothing to do with vue-cli. This errors occurs in this repository.

Thank you and have a great day. I hope everything is going well with you.

**Comment by yyx990803** [comment]
Oh looks like this is caused by some dependency update. (Please specify the exact steps in the original issue because it was confusing)

**Comment by swordrain** [comment]
Oh, I met exactly the same problem.
![image](https://user-images.githubusercontent.com/7844708/56074726-e5762880-5de9-11e9-84f3-e692eb37a2f6.png)

@yyx990803 , Is this information enough?

**Comment by mitar** [comment]
I also hit the same problem. Using node v11.15.0. Doing more or less what people wrote above. Clone, npm install, npm test.

**Comment by mitar** [comment]
It happened even in CI for me: https://circleci.com/gh/meteor-vue/vue/151
