### ISSUE TITLE
use $refs to change element css(example left)  do not work under ie9

### ISSUE THREAD

**Issue by fuguxu** [vuejs/vue#9807]
### Version
2.4.2

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
this.$refs.colorLine.style.left='300px' 

### What is expected?
this.$refs.colorLine.style.left='300px'  work well

### What is actually happening?
this.$refs.colorLine.style.left='300px' do not work

---
在ie9下如上修改元素样式不生效

**Comment by yyx990803** [comment]
请提供符合要求的重现。再乱填 repro link 你会被 block。

**Comment by yyx990803** [comment]
顺便提醒你，直接修改 DOM 元素的操作基本上跟 Vue 无关，这很可能是 IE9 本身的行为不一致。
