### ISSUE TITLE
是否支持es6 class 语法定义组件

### ISSUE THREAD

**Issue by yulei745** [vuejs/vue#9815]
### What problem does this feature solve?
是否支持es6 class 语法定义组件

### What does the proposed API look like?
```
class MyComponent {
   render() {
   }
}
```
类似这种形式的。

**Comment by Justineo** [comment]
Issue 仅接受 bug 报告与新特性请求，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。

**Comment by Justineo** [comment]
F.Y.I. https://github.com/vuejs/vue-class-component/
