### ISSUE TITLE
Issue binding namespaced actions with @click

### ISSUE THREAD

**Issue by aarongeorge** [vuejs/vue#9816]
### Version
2.6.10

### Reproduction link
[https://codepen.io/AaronGeorge/pen/KYdvaL?editors=1010](https://codepen.io/AaronGeorge/pen/KYdvaL?editors=1010)

### Steps to reproduce
I have two buttons, one is labelled "Working todoToggle" the other "Broken todoToggle"

Clicking "Working todoToggle" will toggle the first item in the store, however clicking "Broken todoToggle" throws an error in console.

### What is expected?
Binding a namespaced action with `@click="namespace/action"` should call the action

### What is actually happening?
Binding a namespaced action with `@click="namespace/action"` is throwing an error

---
I know that I can call a namespaced action, but it requires passing the namespace to `mapActions` and I am wondering why I can't actually include the namespace in the `@click` handler.

**Comment by posva** [comment]
This is expected. The slash cannot be added to the name of a method without escaping (this is just js). You should be able to wrap the method of you need to keep the name space and slash. Maybe even wrapping the name between quotes works

**Comment by aarongeorge** [comment]
@posva would you be able to post some code actually showcasing this. I have tried the below and none of them work.

- Single Quotes: `<button @click="'todo/TOGGLE_TODO(1)'">Broken toggleTodo</button>`
- Escaping the slash: `<button @click="todo\/TOGGLE_TODO(1)">Broken toggleTodo</button>`
- Both of the above: `<button @click="'todo\/TOGGLE_TODO(1)'">Broken toggleTodo</button>`

**Comment by Justineo** [comment]
```html
<button @click="this['todo/TOGGLE_TODO'](1)">Broken toggleTodo</button>
```

This would work, but I think it's not recommended. And IMO having namespaced methods probably means you have to many logic inside a single component and maybe you should consider to separate it into several smaller components.

**Comment by aarongeorge** [comment]
It turns out that changing the `methods` to the following allows it to work as intended (Which is actually how my working example is done but I didn't test it with the namespace on the click too...)

```javascript
const MyBrokenComponent = {
    'computed': {...Vuex.mapState(['todo'])},
    'methods': {...Vuex.mapActions('todo', ['TOGGLE_TODO'])},
    'template':
        `<div>
            <button @click="todo/TOGGLE_TODO(1)">Broken toggleTodo</button>
            <div>{{todo.todos}}</div>
        </div>`
};
```

@Justineo your recommendation doesn't work in this case as using `this` inside of the `template` property references the `Window` object. Thanks for your input though
