### ISSUE TITLE
Vue removing <style> tags, but not <script> tags

### ISSUE THREAD

**Issue by theianjohnson** [vuejs/vue#9817]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/RObpZb](https://codepen.io/anon/pen/RObpZb)

### Steps to reproduce
You may need to delete/retype a character to trigger the CodePen to refresh the console

### What is expected?
The text color should be orange (because Vue shouldn't be stripping the <style> tag out)

### What is actually happening?
The text color is black

---
We ran into this bug while converting an enterprise SaaS app to Vue - it's a slow migration with tons of old inline <script> and <style> tags, and while I understand it's bad practice (and Vue complains about that) it seems like Vue should at least be consistent in not _removing_ <style> tags just as it doesn't remove <script> tags

**Comment by posva** [comment]
when using the non-minified version you will see the error in the console. both are ignored it's just that the script gets the time to be executed before Vue gets to read it

**Comment by theianjohnson** [comment]
@posva Is there no way to _not_ ignore or remove them? I understand it's bad practice, but we're migrating an already existing app that comes with inline scripts and styles.

We have this pattern running in production (so no console error) and all the <script> runs just fine. Would be great to have an alternative here, especially since it seems pretty unnecessary.
