### ISSUE TITLE
how to add Css and template dynamically from string with vue.comonent

### ISSUE THREAD

**Issue by sumancholleti** [vuejs/vue#9820]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/nbkhqvf9/](https://jsfiddle.net/nbkhqvf9/)

### Steps to reproduce
let cssCode =`My css which is coming from backend api as a string`
 var MyComponent = Vue.extend({
            template: `<div>My HTML CODE</div>`,
           
          })

          Vue.component('my-component', MyComponent);

### What is expected?
My style should get appended to mycomponent

### What is actually happening?
style doesn't get applied

---
How do i add <style tag scoped> with my css to mycomponent

**Comment by Justineo** [comment]
`<style scoped>` is only available when you use Vue Loader. Adding a `style` property in component objects is never meant to work so this is not a valid bug report.

Rewriting scoped styles isn't trivial so I don't think we would provide runtime support for this. If you want applying global styles dynamically, you can do it totally in userland:

```js
const style = document.createElement('style')
style.innerHTML = cssCode
document.head.appendChild(style)
```
