### ISSUE TITLE
props is available just in <template>

### ISSUE THREAD

**Issue by ehsanbagherzadegan** [vuejs/vue#9821]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/boilerplate/vue](https://jsfiddle.net/boilerplate/vue)

### Steps to reproduce
parent  :

<child-comp :user="user"></child-comp>

child :
props:['user']
<template>
{{user}}  ----->work correctly
</template>
<script>
methods:{
x(){
     console.log(this.user); ---->dont work
   }
}
mounted(){
       console.log(this.user); ---->dont work
   },
created(){
      console.log(this.user); ---->dont work
}
}
</script>

### What is expected?
i pass data from parent component into child component and its available in template by {{}} but when i try use this props in methods or created or mounted this props is undifined its not really useable if just props available by {{}} in template i think it must available in created mounted and any methods

parent  :

>  child-comp :user='user'  /child-comp   

child :
props:['user']
<template>
{{user}}  ----->work correctly
</template>
<script>
methods:{
x(){
     console.log(this.user); ---->dont work
   }
}
mounted(){
       console.log(this.user); ---->dont work
   },
created(){
      console.log(this.user); ---->dont work
}
}
</script>

best regards

### What is actually happening?
props just available by {{}} and just into <template>

**Comment by posva** [comment]
When reporting a bug, a boiled down repro is mandatory

---

Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
