### ISSUE TITLE
Option tag with v-for causing DOM nodes memory leak

### ISSUE THREAD

**Issue by nathnolt** [vuejs/vue#9823]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/rcmo2Lwx/1/](https://jsfiddle.net/rcmo2Lwx/1/)

### Steps to reproduce
Press the toggle button.

### What is expected?
That the garbage collector clears all the nodes

### What is actually happening?
Not all nodes are cleared

---
How to see the garbage collection
Open the fiddle in  https://fiddle.jshell.net/rcmo2Lwx/1/show/light/ (single view of the jsFiddle, so you can open devtools)

Open dev tools -> performance tab->record

Press toggle a bunch of times (or hold enter to keep activating it)

Stop recording

Keyed version
https://fiddle.jshell.net/rcmo2Lwx/2/
https://fiddle.jshell.net/rcmo2Lwx/2/show/light/

The same issue is still happening

**Comment by posva** [comment]
Seems to happen with vanilla JS too in latest chrome. I will check a bit more

**Comment by Justineo** [comment]
As I understand browsers will schedule GC at appropriate time and we don't have control over that.

**Comment by posva** [comment]
But shouldn't we be able to still force the garbage collection? I opened https://bugs.chromium.org/p/chromium/issues/detail?id=949587 for the moment

**Comment by posva** [comment]
Forgot to close this. It's a bug in Chrome
