### ISSUE TITLE
v-bind disabled boolean not reactive

### ISSUE THREAD

**Issue by andrewgorpenko** [vuejs/vue#9824]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/dcmyr724/](https://jsfiddle.net/dcmyr724/)

### Steps to reproduce
Create the input with the type "number" and the button. Add disabled prop to the button with the check (if number === 1).

### What is expected?
The button must be disabled is the input equals 1. Note that the value can be changed by the num-pad, arrow keys or input scroll buttons.

### What is actually happening?
The button is disabled only when the page is loaded. Further changes do not add disabled prop to the button.

**Comment by posva** [comment]
the vaule coming from the input is a string, make sure to cast it in `changeNumber`

**Comment by sirlancelot** [comment]
```js
function changeNumber(event, index) {
  this.rows[index].number = Number(event.target.value)
}
```
