### ISSUE TITLE
Object prop watcher with ES6 syntax (cannot reach vue instance)

### ISSUE THREAD

**Issue by berkansivri** [vuejs/vue#9825]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/8rdwvute/](https://jsfiddle.net/8rdwvute/)

### Steps to reproduce
I'm newbie in vue (love it) and also js world. I realized a bug (if it is) when I try to watch my object's property.

I could not reach my vue instance in watcher, in ES6 syntax.

```
watch:{
    "obj.foo": function() {
    	console.log(this.obj)   //No problem
    },
    "obj.bar": () => {
    	console.log(this.obj)  //Undefined
    },
},

```

### What is expected?
Reach to vue instance

### What is actually happening?
Vue instance undefined

**Comment by Justineo** [comment]
https://vuejs.org/v2/api/#watch

> Note that **you should not use an arrow function to define a watcher** (e.g. `searchQuery: newValue => this.updateAutocomplete(newValue)`). The reason is arrow functions bind the parent context, so `this` will not be the Vue instance as you expect and `this.updateAutocomplete` will be undefined.
