### ISSUE TITLE
跨平台解决方案

### ISSUE THREAD

**Issue by luneice** [vuejs/vue#9826]
### What problem does this feature solve?
有没有一个基于Vue的框架可以做到专注于前端的开发，但同时可以生成小程序的代码？

### What does the proposed API look like?
比如滴滴开源的变色龙框架

**Comment by Justineo** [comment]
目前没有小程序方面的支持，也不在我们的计划中。

不过 Vue 3.0 将会支持自定义渲染器，预计第三方可以更方便地开发不同端的解决方案。

**Comment by fanzhengshao** [comment]
uni-app你值得拥有

**Comment by fanzhengshao** [comment]
uni-app 是一个使用 Vue.js 开发跨平台应用的前端框架，开发者编写一套代码，可编译到iOS、Android、H5、小程序等多个平台。

**Comment by luneice** [comment]
@fanzhengshao 感谢您的推荐，我去尝试看看。
