### ISSUE TITLE
Property or method "_isBuffer" is not defined on the instance but referenced during render. 

### ISSUE THREAD

**Issue by carlos00027** [vuejs/vue#9830]
vue.common.dev.js?e87b:630 [Vue warn]: Property or method "_isBuffer" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

this happened today suddenly, only when in debug mode I enter the VUE tab, the rest is ok, I use laravel + npm run watch with modular vue

**Comment by yxngl** [comment]
https://github.com/vuejs/vue-devtools/issues/955
