### ISSUE TITLE
npm Install Failed

### ISSUE THREAD

**Issue by jwanggggg** [vuejs/vue#9831]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
```
$ git clone https://github.com/vuejs/vue.git

$ cd vue

$ npm install

$ npm test

  97:15  error  Parsing error: Export 'SimpleSet' is not defined

  95 | 
  96 | export { _Set }
> 97 | export type { SimpleSet }
     |               ^
  98 | 

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue@2.6.10 lint: `eslint src scripts test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue@2.6.10 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### What is expected?
Tests complete successfully.

### What is actually happening?
Tests fail due to Export 'SimpleSet' not being defined.

**Comment by posva** [comment]
thank you for your concern but we use yarn for development

**Comment by jwanggggg** [comment]
I see. I managed to install the development environment using Yarn, but I noticed that the CONTRIBUTING.md file [here](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) says that npm should be used. Maybe this could be fixed for clarity.

**Comment by posva** [comment]
updated
