### ISSUE TITLE
Firefox context menu event also fires click handler.

### ISSUE THREAD

**Issue by patrickdavey** [vuejs/vue#9832]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/v63jz95o37](https://codesandbox.io/s/v63jz95o37)

### Steps to reproduce
In the sandbox link, using Firefox, right click on the text, you'll see both the `contextmenu` click handler called, and the body `click` handler setup in the mounted hook.

### What is expected?
It is expected that only the `contextmenu` handler should be called.

### What is actually happening?
The contextmenu _and_ body "click" handler are called. This only happens in Firefox.

---
There is a bug listed against Mozilla for this -> https://bugzilla.mozilla.org/show_bug.cgi?id=184051 but, it's 17 years old so perhaps it's a hard one to fix.  Other frameworks (I looked at Rails -> https://github.com/rails/rails/pull/34573 and Inferno -> https://github.com/infernojs/inferno/issues/1273 ) seem to have put a fix in place for this behavior.

Totally fair enough if this is a "won't fix" as it really is a Firefox issue, but, if Vue could prevent it somehow, that would be great!

I ran into this bug as I was creating a contexemenu component and I attached a click handler to the body to dismiss the contexemenu, unfortunately, in Firefox, this meant that the menu was shown and then immediately hidden again as the click handler was fired on the document.

**Comment by Justineo** [comment]
It seems that no `click` event handler won't be triggered when you attach it to `document.documentElement`:

```js
document.documentElement.addEventListener('click', e => {
  // won't trigger on right clicks
})
```

See this [modified sandbox](https://codesandbox.io/s/54wo0zvn6p).

**Comment by patrickdavey** [comment]
Thanks @Justineo . I'll close this issue as, like I said above, it's not _really_ a vue issue anyway.
