### ISSUE TITLE
Class based component with JSX causes TS2322 error

### ISSUE THREAD

**Issue by joakimbugge** [vuejs/vue#9833]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/b5z23ohp/1/](https://jsfiddle.net/b5z23ohp/1/)

### Steps to reproduce
1) Create a new project using @vue/cli, choose class based components and enable Typescript.
2) Create a simple component using JSX, e.g.

```
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Button extends Vue {
  public render() {
    return <button class="button" type="button">{this.$slots.default}</button>;
  }
}
```

3) Create another component and import the first component

```
import { Component, Vue } from 'vue-property-decorator';
import Button from './Button';

@Component
export default class PrimaryButton extends Vue {
  public render() {
    return <Button class="primary-button">{this.$slots.default}</Button>;
  }
}
```

### What is expected?
No errors

### What is actually happening?
Typescript reports error TS2322. Any property will cause this error, event built-in properties like `class` and `style`.

```
 Type '{ class: string; }' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Property 'class' does not exist on type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
```

![image](https://user-images.githubusercontent.com/2697311/55657068-608f7b80-57f9-11e9-9b4d-44f840b96502.png)

---
* TypeScript: v3.4.1
* Vue: v2.6.10

**Comment by yyx990803** [comment]
There is currently no built-in TSX support for Vue 2.x (but there will be in 3.0). For 2.x you can check out community solutions like https://github.com/wonderful-panda/vue-tsx-support or https://github.com/nickmessing/vue-tsx

**Comment by GennCai** [comment]
You need  a single d.st file to declare miss fields  

`
import Vue from 'vue';

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    style?: { [key: string]: string };
    class?: string | string[];
  }
}
`

**Comment by GennCai** [comment]
You need a single d.st file to declare miss fields

`import Vue from 'vue';

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    style?: { [key: string]: string };
    class?: string | string[];
  }
}`

**Comment by GennCai** [comment]
`c`

**Comment by GennCai** [comment]
`import Vue from 'vue';

declare module 'vue/types/options' {
interface ComponentOptions {
style?: { [key: string]: string };
class?: string | string[];
}
}`

You need a single d.st file to declare miss fields

**Comment by GennCai** [comment]
`import Vue from 'vue';

declare module 'vue/types/options' {
interface ComponentOptions {
style?: { [key: string]: string };
class?: string | string[];
}
}`

**Comment by GennCai** [comment]
You need a single d.st file to declare miss fields

```
import Vue from 'vue';

declare module 'vue/types/options' 
{ 
   interface ComponentOptions {
     style?: { [key: string]: string }; 
    class?: string | string[]; 
  } 
} 
```
