### ISSUE TITLE
Is any possible to add mounted access in beforeMount ?

### ISSUE THREAD

**Issue by unickhow** [vuejs/vue#9835]
### What problem does this feature solve?
I fetch api mostly in 'created' hook, but sometimes it took times while the DOM has already rendered, therefore I have to set a boolean data to determine whether the promise done (and v-if on the DOM ofc), so I wonder is there any way like vue router doning the beforeEach method, I have to next() once I set the beforeEach, otherwise I can't enter the router, just curious is there any concern or side effect this way ?

### What does the proposed API look like?
without beforeMount: 
created (fetch api) => mounted (no matter if the api done)

with beforeMount: 
created (do something else but fetch api) => beforeMount (fetch api and then call a function something like next()) => mounted (start render DOM after the promise done)

**Comment by yyx990803** [comment]
This is not possible. The mount process is synchronous by design. Using `v-if` is the proper way and it also allows you to render arbitrary content while the data is still loading.
