### ISSUE TITLE
document.activeElement is wrong

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue#9836]
### Version
2.6.0

### Reproduction link
[https://jsfiddle.net/ktsLp3n0/](https://jsfiddle.net/ktsLp3n0/)

### Steps to reproduce
Go to the fiddle and open the console, and click between the form inputs and the page body.

### What is expected?
Anytime the blur event happens the console will show which element is active by printing `A` or `B` for the two form fields or `nothing` when the page body is active. The fiddle shows correct behavior because it's using Vue 2.5.22

### What is actually happening?
Change 2.5.22 to 2.6.0 in the `script` tag and you'll see the console always prints `nothing` which is incorrect.

**Comment by yyx990803** [comment]
The behavior of `nextTick` has been adjusted in 2.6. This is documented in the release note: https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd

**Comment by rightaway** [comment]
Even using 2.5.22 you really never see `A` or `B` logged? I've tried it in the latest firefox and chrome and it's definitely working that way in both.

**Comment by LinusBorg** [comment]
The demo does what you say it does, for me at least.

Nonetheless, Evan's statement is correct. $nextTick changed for reasons outlined in the linked notes.

The solution to your problem would be to use a `setTimeout` instead.
