### ISSUE TITLE
Shallow $watch()

### ISSUE THREAD

**Issue by d-ph** [vuejs/vue#9837]
### What problem does this feature solve?
Hi,

I'd like to request a new option for the $watch() function: `shallow: boolean;`. This option would make watch callback function fire only if any of the first level values in an Array (a tuple) or on Object change. This would offer an alternative to the current behaviour of always calling the watch callback when watching a non-primitive variable (as per [the following comment](https://github.com/vuejs/vue/blob/4f111f9225f938f7a2456d341626dbdfd210ff0c/src/core/observer/watcher.js#L184)). It would also be a natural expansion of the `deep: boolean;` option.

Moreover, the first level properties of the watched Arrays and Objects would _always_ be compared used strict equality comparison `===`, regardless of whether they are primitive values or Arrays/Objects. This is so that the same instances of a class would not trigger the watch callback, as nothing has changed (the use case is: observing an immutable value object).

Use case 1: Watching a tuple, aka. watching many variables and having a single callback when any of the variables change. With the `shallow: true` option, it would be a very clean solution to current necessity of having to hash the tuple somehow (the easiest way is to `.join(',')` the tuple to produce a string, but not all tuples are made of primitive values, so that's not always this easy). Two tuples should evaluate equal, when all indexes of the old tuple are set to the same values in the new tuple, under the same indexes. It'd be a simple for-each loop that short-circuits on the first inequality in the old and the new tuple.

Use case 2: Watching all keys in an Object. This is a very common use case and using `deep: true` for it is very often not ideal (especially, if the values in the watched Object are also Objects). As in use case 1, here the old and the new Objects would evaluate unequal (and therefore trigger the watch callback), when any of the keys in the old Object doesn't strict-equal the same key in the new Object. Also, if keys are missing or there are extra keys in the new Object, this should also be treated as a change and therefore trigger the watch callback. A common context for this use case is when the watched Object is a hashmap behaving as a "form", whose keys are form keys and values are either primitive variables or value objects. Watching such a hashmap with the proposed `shallow: true` option would be _a massive_ convenience (e.g. to run validation on every change in the form and enable/disable the submit button).

In angular 1, this feature is called [$watchCollection](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchCollection).

Thank you.

### What does the proposed API look like?
```javascript
class Person {
  constructor(name) {
    this.name = name;
  }
}

const vm = new Vue({
  data: {
    dataHashmap: {
      bartender: new Person('Phil'),
      bouncer: new Person('Rob'),
      janitor: new Person('Tom'),
    }
  }
});

vm.$watch(
  'dataHashmap', 
  () => { console.log(vm.dataHashmap); }, 
  { shallow: true }
);

vm.$watch(
  (vm) => { return [vm.dataHashmap.bartender, vm.dataHashmap.janitor]; }, 
  () => { console.log(vm.dataHashmap); }, 
  { shallow: true }
);
```

**Comment by posva** [comment]
this is already achievable by checking the old value against the new value in the watcher:


```js
watch: {
  dataHashmap (val, old) {
    if (val !== old) return // the whole object changed
    // do something
  }
}
```

**Comment by d-ph** [comment]
Hi,

Although the solution you suggested doesn't solve the problem described by this ticket, I see what you meant and indeed I could do that in my watch callbacks (i.e. I can manually for-each the old and new value and find first index that doesn't equal the other + I could find any added/removed keys in the new value). 

Even though I can do that in my code, I'd need to do it in many places (i.e. in the places where I want to shallow-watch a hashmap/array). I'll most likely end up with a helper function that I can run from all these places to reduce code duplication. Now think about other devs that also needs this kind of functionality and how they also will end up creating a similar helper in their code. Count the time spent by each dev on finding out that shallow watching isn't possible out-of-the-box, googling the solution, finding this ticket, realising that they need to reinvent the wheel, then reinvent the wheel and swallow the bitterness that all of this could _just be_ offered by the framework with a simple boolean option on the watcher.

Don't get me wrong. I really enjoy working with the framework and I like how it just works in demo apps, small apps and large apps. I would, though, appreciate it more if it offered the requested convenience option.

Thank you for reading the feature request and responding.

**Comment by posva** [comment]
As this is really a niche cache, it's okay for you to repeat it. Furthermore, you can implemente a global mixin that adds the shallow option and prevents you to write the boilerplate necessary. However, this is something you will have to write yourself, and if you need help, you can use the appropriate channels to ask. Cheers

**Comment by yyx990803** [comment]
FYI: if something is 1. not very commonly used and 2. can be done in userland, we most likely won't add a convenience API for it. If we add something for every request we'd bloat the API with hundreds of convenience options that no one can remember.
