### ISSUE TITLE
Please support "productionTip" in vue.config.js too

### ISSUE THREAD

**Issue by fancydev18** [vuejs/vue#9839]
### What problem does this feature solve?
 Please support "productionTip" in vue.config.js too. Now it gives:

 ERROR  Invalid options in vue.config.js: "productionTip" is not allowed

Related issue: https://github.com/vuejs/vue/issues/7562

### What does the proposed API look like?
vue.config.js new property

**Comment by posva** [comment]
I think it's not worth adding but you may ask in vue cli repo
