### ISSUE TITLE
Memory leak when using "transition" and "keep-alive"

### ISSUE THREAD

**Issue by Aaron-Bird** [vuejs/vue#9840]
Why are some "Vue Component" not cleared when using "transition" and "keep-alive"?

I wrote a demo:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>demo</title>
  </head>
  <body>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>

    <div id="app">
      <transition>
        <keep-alive include="foo">
          <router-view></router-view>
        </keep-alive>
      </transition>
    </div>
    <script>
      const Foo = {
        name: "foo",
        template: `<div><router-link to="/bar">Go to Bar</router-link></div>`
      };
      const Bar = {
        name: "bar",
        template: `<div><router-link to="/foo">Go to Foo</router-link></div>`
      };
      const routes = [
        { path: "/foo", component: Foo, alias: "/" },
        { path: "/bar", component: Bar }
      ];
      const router = new VueRouter({
        routes
      });
      const app = new Vue({
        router
      }).$mount("#app");
    </script>
  </body>
</html>
```
The debugging process is as follows:  
1 Click "Collect garbage" and "take heap snapshot"(snapshot 1)  
2 Click the routing button on the left 10 times, then click "Collect garbage" and "take heap snapshot"(snapshot 2)  
3 Click the routing button on the left 10 times, then click "Collect garbage" and "take heap snapshot"(snapshot 3)  
![](https://i.imgur.com/Kk8LhAK.gif)  

The generated "snapshot" is as follows:

snapshot 1:
![](https://i.imgur.com/9iO7gqD.png)  
snapshot 2:
![](https://i.imgur.com/CvkAGS6.png)  
snapshot 3:
![](https://i.imgur.com/HURrvNz.png)  

VueComponent is not being recycled, is this a bug?

**Comment by posva** [comment]
If you open a new issue again, please remove vue-router. There is already an open bug on vue router about keep-alive + transition

**Comment by Aaron-Bird** [comment]
@posva 
Could you  delete this issue?

**Comment by posva** [comment]
it doesn't matter
