### ISSUE TITLE
Style not getting updated after computed property is called next time

### ISSUE THREAD

**Issue by adityaraval** [vuejs/vue#9841]
We want the background-image of a cover to be updated after an api call.

Below is the code for template :

`<div class="hero-image" v-bind:style="{ 'background-image': 'url(' + getPhotoUrl + ')' }">
      <div class="trailer" v-if="movie.TrailerLink">
        <a href>
          <img src="static/images/trailer-btn.png" alt>
        </a>
      </div>
      <div class="image-overlay"></div>
    </div>`

Below is the code for computed api and computed :

`import instance from "../../api/axios-config";
import axios from "axios";
export default {
  name: "Details",
  data() {
    return {
      imageUrl: null,
      movie: {
        PeopleInMovies: []
      },
      index: 0,
      selected: {}
    };
  },

  computed: { 
    getPhotoUrl() {
        let result = this.movie && this.movie.Photos ? this.GOOGLE_BUCKET_ENDPOINT + this.movie.Photos[0] : '';
        return result
    }
  },

  created() {
    instance
      .get("api/getmovie/?movieId=" + this.$route.params.id)
      .then(movie => {
        this.movie = movie.data;
      });
  }
};`

Even computed is called after api call but the result is not getting reflected in dom and background-image isn't set.

**Comment by sharvilak11** [comment]
+1

**Comment by le0l1** [comment]
+1

**Comment by Justineo** [comment]
Please do not +1 in a closed issue which doesn't conform to our issue requirements. If you do have a similar issue, please open a new issue with valid reproduction. Thanks.
