### ISSUE TITLE
Memory leak when using "transition" and "keep-alive"

### ISSUE THREAD

**Issue by Aaron-Bird** [vuejs/vue#9842]
### Version
2.6.10

### Reproduction link
[https://codepen.io/aaronbird/pen/JVRKwa](https://codepen.io/aaronbird/pen/JVRKwa)

### Steps to reproduce
I wrote a demo:  
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>demo</title>
    <style>
      .link {
        cursor: pointer;
        user-select: none;
      }
    </style>
  </head>
  <body>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>

    <div id="app">
      <transition>
        <keep-alive include="foo">
          <component :is="target" @change="onChange"></component>
        </keep-alive>
      </transition>
    </div>
    <script>
      const Foo = {
        name: "foo",
        template: `<div class="link" @click="$emit('change', 'bar')">Go to Bar</div>`
      };
      const Bar = {
        name: "bar",
        template: `<div class="link" @click="$emit('change', 'foo')">Go to Foo</div>`
      };
      Vue.component("foo", Foo);
      Vue.component("bar", Bar);
      const app = new Vue({
        data: {
          target: "foo"
        },
        methods: {
          onChange(target) {
            this.target = target;
          }
        }
      }).$mount("#app");
    </script>
  </body>
</html>
```

The debugging process is as follows:  
1 Click "Collect garbage" and "Take heap snapshot"(snapshot 1)  
2 Click the routing button on the left 10 times, then click "Collect garbage" and "Take heap snapshot"(snapshot 2)   
3 Click the routing button on the left 10 times, then click "Collect garbage" and "Take heap snapshot"(snapshot 3)   
![](https://i.imgur.com/FCe40P6.gif)  

The generated "snapshot" is as follows:

snapshot 1:
![](https://i.imgur.com/S49oSJo.png)  
snapshot 2:
![](https://i.imgur.com/X1bbOgU.png)  
snapshot 3:
![](https://i.imgur.com/lLD8z7Y.png)
After clicking 100 times:  
![](https://i.imgur.com/E0bjppJ.png)  

VueComponent is not being recycled, is this a bug?  

### What is expected?
Why is this happening, is this a bug?

### What is actually happening?
Component will not be cleared when switching components.

**Comment by dejour** [comment]
I will take a look this.

**Comment by dejour** [comment]
All component is retained by cached vnode’s parent，if we delete parent. then components are recycled.Will digg more

**Comment by hunson1990** [comment]
888

**Comment by sprocket99** [comment]
I also have a memory leak issue, please see : https://github.com/bootstrap-vue/bootstrap-vue/issues/4214

I tried to make a jsfiddle but not sure how to replicate the caching behaviour.

**Comment by sky8ez** [comment]
Hey, is there any news? is this updates already merged to master branch ? I have the same problem.

**Comment by kadet1090** [comment]
I'd really love to see any update on this issue - there is PR but it seems dead?

**Comment by lvjiaxuan** [comment]
It didn't fixed. Oh m g.
