### ISSUE TITLE
Passed attributes without a value should have undefined value in $attrs

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue#9843]
### What problem does this feature solve?
Right now, Vue `$attrs` does not differentiate if you pass an attribute with a value or without. For example all of these three options `<some-component checked checked="" :checked="''"/>` provide the same `$attrs` object: `{ "checked": "" }`. This makes it impossible for higher order components to differentiate between an attribute that's supposed to have a value, and an attribute that simple acts like a switch (e.g. disabled or checked). 

See the repro: https://codesandbox.io/s/130p8ry4nj

### What does the proposed API look like?
Instead of assigning a default value, `""` to it, the value should simply be `undefined` (`null` wouldn't work, since non-required props can be passed `null` to).

Edit: I know that per definition there is no way of determining if an attribute is a boolean attribute or not.  Maybe this would have to be done by the vue compiler?

**Comment by posva** [comment]
having undefined would cause many other problems like being considered as non-existant, it would be a breaking change.
`checked checked="" :checked="''"` **are** the same from an attribute perspective. From a prop perspective, it would become true if declared as a prop.

**Comment by johannes-z** [comment]
@posva I understand, but this means you **have** to declare a prop. This becomes impossible though when you have a higher order component that doesn't know anything about the props it's going to receive.  Is there a way to solve this as of now? 

Why this is interesting in the first place: In a typescript application, you usually define all the props via an interface. Vue doesn't handle those too well, so my idea was to create an object on the component, set `inheritAttrs` to `false` and add the attributes to this object. The problem is, as I mentioned, that this breaks boolean attributes, as their value is just `""`. I could of course use `:checked="true"`, but when writing UI libraries, this is a **big** caveat.

**Comment by yyx990803** [comment]
If your HOC expects `checked` itself, then it should declare it. If it simply passes the `{ checked: '' }` value to the inner component which does declare `checked` as a boolean prop, it will handle it as expected.

Having `<foo checked />` where `checked` has an `undefined` value seems rather counter-intuitive to me.

**Comment by johannes-z** [comment]
@yyx990803 Thanks for your comment! This only works if the HOC is not generic and knows about the inner component's props. The reason why it is a problem that boolean attributes are not being differentiate is because of the dynamic/generic nature of the HOC. As of know, using typescript interfaces you have to have an interface definition **and** the prop definition (so all I'm doing now is map compile time types to runtime types). 

`$attrs` is a way to work around this. 
(Offtopic: In this case you don't need runtime checking either, because any error is going to be detected at compile time).
Since the vue compiler would have to parse the attributes anyway (to pass the value as a prop and type checking, etc.) why is there no way of providing meta information about the attributes? Maybe this is the wrong take on tackling the generic HOC approach, but this is the only I'm familiar with.
