### ISSUE TITLE
assetsPath config option ignored when building with --watch 

### ISSUE THREAD

**Issue by halfpastfive** [vuejs/vue#9844]
### Version
2.6.10

### Reproduction link
[https://github.com/halfpastfive/assetspath](https://github.com/halfpastfive/assetspath)

### Steps to reproduce
in the example project, outputDir and assetsDir are defined in vue.config.js

1. build the project with `npm run build` and browse the `web` directory:  js files are copied in the `assets/` subdirectory

2. build the project with `npm run watch` (which is only an alias for `vue-cli-service build --watch` in the package.json)  and browse the `web` directory: js files are copied at the root of the directory, ignoring the `assetsPath` option of the vue.config.js 

### What is expected?
assets are copied in the directory defined by the `assetsPath` option from the vue.config.js file

### What is actually happening?
assets are copied in the directory defined by the outputPath directory, ignoring the `assetsPath` option

---
In my real-world use case, the html files are templates for a server-side application. In this application, assets need to be in a subfolder in order to be considered as assets by our server. 

Without it, I need to build for production, making debugging more difficult.

**Comment by posva** [comment]
Open the issue in the vue-cli repository please
