### ISSUE TITLE
template compiler ignores pug whitespace control?

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#9849]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/825v44246j](https://codesandbox.io/s/825v44246j)

### Steps to reproduce
i want in markup ```<span>1</span> <span>2</span>``` in pug

### What is expected?
expected whitespaces appear in DOM

### What is actually happening?
my markup sticks together

---
compiler ignores pug recommended solutions of whitespace control https://pugjs.org/language/plain-text.html#whitespace-control

**Comment by posva** [comment]
In the doc it tells you to use multiple `|` to have a space:

```pug
      span
      | text
      |
```

Take a look at the compiler options: https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options
