### ISSUE TITLE
@keydown.enter在中文输入法输入字母出现候选字时按enter键会触发keydown事件，原生的.onkeydown此时并不会触发

### ISSUE THREAD

**Issue by shoung6** [vuejs/vue#9850]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/c6gufhno/](https://jsfiddle.net/c6gufhno/)

### Steps to reproduce
1.光标聚焦在input1里，确保切换到中文输入法，随便输入几个字母出现中文候选字。此时按enter键把字母直接输入表单，会触发绑定的keydown事件
2.同样步骤在input2里，不会触发keydown事件

### What is expected?
用vue的@keydown.enter表现与原生的绑定事件方式的表现一致

### What is actually happening?
不一致

---
vue2.5.13并不会出现这个情况。
业务场景：表单有按enter键提交的功能。如果在中文输入法下输入了字母，然后想用enter键把字母输入到表单里，就会出现直接提交表单的情况。用户实际只是想把字母输入到表单里，并不想提交表单。

**Comment by posva** [comment]
The check done by Vue is checking other keys that contain the word `enter` using `key` and `keyCode`

**Comment by Jannchie** [comment]
I have encountered the same problem. On Mac, pressing enter in the input method triggers keydown.enter event, but not on Windows.
