### ISSUE TITLE
Typings for $refs should also include Component | Component[]

### ISSUE THREAD

**Issue by terrymun** [vuejs/vue#9854]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/p7krpry9vm](https://codesandbox.io/s/p7krpry9vm)

### Steps to reproduce
1. Assign a component a `ref` attribute, say, `<my-component ref="myComponent" />`
2. Import the typings for component  from vue, i.e. `import { Component as VueComponent } from 'vue';` (the aliasing is needed because I am also using `vue-property-decorator`'s `Component` module, but that is not relevant to the question)
3. Declare the types for `$refs` when composing a component, i.e. `public readonly $refs!: { myComponent: VueComponent }`

### What is expected?
I expect the `Component` type to be accepted in the `$refs` definition.

### What is actually happening?
I get a message that the type of `this.$refs.myComponent` is incompatible with the pre-existing type declared for `this.$refs.<key>`.

Here is a screenshot of the actual error I am getting in production code:

![Code_2019-04-10_09-16-25](https://user-images.githubusercontent.com/5593067/55858998-5f4fad00-5b71-11e9-9e5a-d2806b67d4ef.png)

---
This issue came across because I need to access a nested element within a Vue component when writing in TypeScript. In native JS, I can simply query the DOM of the Vue component using `this.$refs.myComponent.$el.querySelector(...)` without an issue. However, in TypeScript, I get a warning because I need to pre-declare the typings for `$refs` at the top of the component, i.e.:

```
public readonly $refs!: {
  myComponent: VueComponent
}
```

When you log `this.$refs.myComponent` when the parent/consuming component is mounted to the console, you will see that it returns a Vue component instance. This is incompatible with the pre-existing typings for `$refs`, which only allows the following types: `Vue | Element | Vue[] | Element[]`. 

I propose that the typings for `$refs` by extended to:

```
{ [key: string]: Vue | Element | Component | Vue[] | Element[] | Component[] }
```

**Comment by underfin** [comment]
I think its rigorous, public readonly $refs!: { myComponent: MyComponent }

**Comment by terrymun** [comment]
@underfin That will work, but only in cases where the ref actually points to an actual named component (which is my case, so your suggestion works 100% for me) :) however, what if somebody has this in their app?

```
<component
  v-bind:is="componentToUse"
  v-ref="myComponent" />
```

**Comment by underfin** [comment]
@terrymun  
`@Component({
  name: 'MyComponent'
})`
`export default class MyComponent extends Vue { }` 
MyComponent is extends `Vue`, so can use `$refs!: { myComponent: Vue } ` with generic type.

**Comment by HerringtonDarkholme** [comment]
I believe `$refs` contains either dom element(s) or component instance(s). `Component` in Vue's typing is actually the component configuration object or component class, not the component instance itself.

You typing should be `$refs: { myComponent: Vue}`  IMHO

**Comment by KaelWD** [comment]
:point_up:

`myComponent: Vue` or `myComponent: InstanceType<typeof MyComponent>`

**Comment by terrymun** [comment]
Thanks for all your help! I've learned that:

- If the component is defined already, we can just assign its own class as its type, e.g. `myComponent: MyButtonComponent` if I'm importing it as `import MyButtonComponent from <...>;`
- If the component is indeterminate, assigning it a generic type of `Vue` works
