### ISSUE TITLE
Make something like :class for dataset

### ISSUE THREAD

**Issue by trenyture** [vuejs/vue#9855]
### What problem does this feature solve?
I am using a lot the dataset of html and I know I could use :data-something="value" to bind value on the HTML element. But, as you cannot make a `for` inside the html element (for example to iterate the keys of an object and put it in datas), it could be great to use the same as `:class` to put datas in the HTML element...

### What does the proposed API look like?
For example, you could do something like this : 

```html
<div :data="{id: 2, userId: 5, :userName: 'John Doe', userAge: null}">
```

Would render in pure HTML like this :

```html
<div data-id="2" data-user-id="5" data-user-name="John Doe">
```

And so you can access this datas in the `.dataset` of JavaScript or `.data()` of jQuery.

**Comment by posva** [comment]
mmh, I would say this would be a custom directive

**Comment by Justineo** [comment]
I think this is basically a sub-feature of #8767 and let's close this in favor of that one.

**Comment by trenyture** [comment]
Ok, thanks for the custom directive idea ... I made it ;)
For those looking on the same idea this is my directive : 

```
Vue.directive('datas', function (el, binding, vnode) {
	let d = binding.value;
	if(d != null && d instanceof Object && typeof d == 'object') {
		let idx = Object.keys(d);
		for(let i = 0, len = idx.length; i < len; i++){
			if(d[idx[i]] != null){
				//Here we are going to transform the string in camelCase because of dataset
				el.dataset[idx[i].replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())] = d[idx[i]];
			}
		}
	}
});
```
And then you could use it like this : `<div v-datas="{user-id: 5, user-pseudo: 'trenyture'}">`
