### ISSUE TITLE
Using factory function and type assertion with props causes type error

### ISSUE THREAD

**Issue by wakame-isono** [vuejs/vue#9861]
### Version
2.6.8

### Reproduction link
[https://github.com/wakame-isono/vue-typescript-issue](https://github.com/wakame-isono/vue-typescript-issue)

### Steps to reproduce
1. Use vue-cli init with TypeScript without using class-style.
1. Add code to src/components/HelloWorld.vue as follow.

```
<script lang="ts">
import Vue, { PropType } from 'vue'

interface Test {
  a: string;
}

export default Vue.extend({
  name: 'HelloWorld',

  props: {
    msg: String,
    test: {
      type: Object as PropType<Test>,
      default: () => ({})
    }
  },

  created () {
    console.log(this.test)
  }
})
</script>
```

### What is expected?
Type errors does not occur.

### What is actually happening?
Property 'test' does not exist on type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.

---
It did not occur version 2.5.17.

**Comment by underfin** [comment]
@wakame-isono 
The `props` should use in blew. In your case, `props` will be a property in `data`, should use with `this.props.test`.
`import { Component, Prop, Vue } from "vue-property-decorator";`

`@Component`
`export default class HelloWorld extends Vue {`
  `@Prop() private msg!: string;`
`}`

**Comment by wakame-isono** [comment]
Thank you for advice.
I am confused...I should use `this.props.test`?

In this state, even I try to add data, computed and method and access these, the same error occurs for each of these properties. And I founded the following pattern also occors the same error.
```
props: {
    msg: String,
    test: {
      type: Array,
      default: () => []
    }
  },
```

**Comment by underfin** [comment]
@wakame-isono 
https://github.com/vuejs/vue-class-component
https://github.com/kaorun343/vue-property-decorator
You can use `data`  `computed` `method ` `props` with the above packages, learn it, please.

**Comment by chrislentz** [comment]
> **FullStory Session:** https://www.fullstory.com/

**Comment by chrislentz** [comment]
> **FullStory Session:** [https://www.fullstory.com/](https://www.fullstory.com/)

**Comment by chrislentz** [comment]
> **FullStory Session:** [https://www.fullstory.com/](https://www.fullstory.com/)

**Comment by chrislentz** [comment]
> **FullStory Session:** [undefined](undefined)

**Comment by chrislentz** [comment]
> **FullStory Session:** [https://www.fullstory.com/](https://www.fullstory.com/)

**Comment by yyx990803** [comment]
@chrislentz please stop spamming or I'll have to block you.

**Comment by wakame-isono** [comment]
I have used with Vue + TypeScript without using class-style since ver 2.5.
If possible, I would like to get solutions to this problem without using these packages 😢

**Comment by underfin** [comment]
I see. It works with follow code.
` props: {`
  `  msg: String,`
    `test: {`
     ` type: Object as PropType<Test>,`
   `   default: () => ({} as Test)`
 `   }`
  `}`
`PropOptions` `default` return type only `T | null | undefined`.
`export interface PropOptions<T=any> {`
       `  type?: PropType<T>;`
      ` required?: boolean;`
     `default?: T | null | undefined | (() => T | null | undefined);`
       ` validator?(value: T): boolean;`
`}`

**Comment by wakame-isono** [comment]
Thank you very much for help 🙇‍♀️ 🙏 🙏
It works!! I defined incorrect an association type and missed that defined type was changed 😫💦

Thank you for sparing your precious time for this issue and I will close the issue🙇‍♀️ 🙏 🙏
