### ISSUE TITLE
Vue global component registration is broken with vue-devtools on

### ISSUE THREAD

**Issue by shawwwn** [vuejs/vue#9865]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/myen70g1/6/](https://jsfiddle.net/myen70g1/6/)

### Steps to reproduce
1. Copy the code in jsfiddle and save it to a html.
2. Enable `vue-devtools` in chrome.
3. Open the html we saved in step 1 in chrome, notice 'Hello World!' should be displayed after 1s.
4. Inspect the page, switch to **Vue** tab by `vue-devtools`.
5. Reload the page, no more 'Hello World!' will be displayed.

From now on, you may refresh the page however you want, no message will be displayed.

### What is expected?
'Hello World!' even with `vue-devtools` on

### What is actually happening?
No 'Hello World!', not happy!

---
It seems dev tool is breaking the prototyping between Vue.option.components and vm.$option.components.

**Comment by posva** [comment]
Could you open the issue on the devtools repository? thanks!
