### ISSUE TITLE
$sync to update .sync props

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#9869]
### What problem does this feature solve?
this will give us an internal api to use for updating sync props 
$emit('update:nameOfPropToSync', val)

This will allow new users to have a certain structure for $sync and $emit so they will know that the prop is using the .sync modifier for the prop.
### What does the proposed API look like?
```html
<template>
  <modal modal.sync="modal" />
</template>
```

```js
function sync(key, ...args) {
  this.$emit(`update:${key}`, ...args);
}
Vue.prototype.$sync = sync;

// using in a component

this.$sync('modal', false)
```

**Comment by posva** [comment]
I think it's better to not create an extra api that hides the original behavior. On top of that it's doable in userland
