### ISSUE TITLE
component content unexpectedly rendered

### ISSUE THREAD

**Issue by FranckFreiburger** [vuejs/vue#9877]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/r0gkjw1p/1/](https://jsfiddle.net/r0gkjw1p/1/)

### Steps to reproduce
just run the fiddle demo

### What is expected?
Since parent component (`<foo>`) renders nothing,
I expect `bar()` to not be called.

### What is actually happening?
bar() is unexpectedly called

---
This is a simplified test case.
This situation is much more annoying when using SSR + browser-only-library + vue-no-ssr.
This ends up with JS code designed for client-side to be called server-side despite of using no-ssr mechanism

**Comment by posva** [comment]
as you are using a regular slot, this one is rendered in the parent template then passed to the component, using a scoped slot would prevent it as it won't be rendered if it isn't used inside the component. Wrapping it in a `<template v-slot></template>popp` or putting `v-slot` in the `foo` component will prevent it from eagerly render.

This probably won't be a problem for v3 though as slots will be unified but not evaluating the content would remove the `$slot.default` property access, and that would be a breaking change

**Comment by FranckFreiburger** [comment]
Thank you for this clarification.
