### ISSUE TITLE
Slide-enter animations are broken although slide-leave are working well

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [vuejs/vue#9878]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/w2v9oz1xml](https://codesandbox.io/s/w2v9oz1xml)

### Steps to reproduce
- Run example
- Check Panel.vue component
- Click Open Panel button to open panel
- Click Open Panel button once again to close the panel

### What is expected?
Panel opens from the side with animation that lasts 1 second

### What is actually happening?
Panel opens instantly without animation although animation is present when panel is closing. Presumably transition enter classes do not apply

**Comment by posva** [comment]
you need to use the `enter` prop on the transition component

**Comment by AndrewBogdanovTSS** [comment]
@posva that worked, thank you
