### ISSUE TITLE
SVG viewbox does't scale

### ISSUE THREAD

**Issue by LouisWT** [vuejs/vue#9879]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/bJaEQa](https://codepen.io/anon/pen/bJaEQa)

### Steps to reproduce
1. svg in template doesn't scale like normal html
2. Vue: https://codepen.io/anon/pen/bJaEQa
3. HTML: https://codepen.io/anon/pen/EJoKjx

### What is expected?
svg scale according to width & height

### What is actually happening?
svg changed, but viewbox in the svg does't scale

**Comment by posva** [comment]
it's `viewBox`
