### ISSUE TITLE
Events hooks doesn't work on transition-group

### ISSUE THREAD

**Issue by superboss224** [vuejs/vue#9882]
### Version
2.6.9

### Reproduction link
[https://jsfiddle.net/abc222/fo81x9vj/1/](https://jsfiddle.net/abc222/fo81x9vj/1/)

### Steps to reproduce
When you use an event hook like scroll or click on a transition-group element, it doesn't work and the callback is not called, which forces the user to listen from mounted and using a ref or querySelector over the transition-group element.

### What is expected?
The hook callback should be called

### What is actually happening?
The hook callback is not called

**Comment by posva** [comment]
use the `.native` modifier on `@scroll`
