### ISSUE TITLE
Bug with blur behavior

### ISSUE THREAD

**Issue by Zeyder** [vuejs/vue#9888]
### Version
2.6.10

### Reproduction link
[https://github.com/Zeyder/vue_bug_2.6.10](https://github.com/Zeyder/vue_bug_2.6.10)

### Steps to reproduce
In this repository presented working version of component. After update Vue version until latest (2.6.10) component won't work.

### What is expected?
When component is active, we can see dropdown block with buttons which don't lost focus from main input. Also after added input we can enter any value to input

### What is actually happening?
Component loses focus via any click on dropdown block

---
I have several similar components with similar behavior which worked in previous Vue versions until 2.6.*

**Comment by posva** [comment]
Hey, your repro isn't boiled down at all and we need something smaller to check but this is probably related to the changes of micro/macro tasks introduced in v2.6. You can check another issue at https://github.com/vuejs/vue/issues/9340

If it's not the case, please open another issue but with a completely boiled down reprop, you can also use jsfiddle or codesandbox to provide repros btw 🙂
