### ISSUE TITLE
Wrapping Vue.observeable() in a proxy breaks it

### ISSUE THREAD

**Issue by DominusVilicus** [vuejs/vue#9889]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/w2my2j2w8?codemirror=1](https://codesandbox.io/embed/w2my2j2w8?codemirror=1)

### Steps to reproduce
Wrapping an observeable in a proxy to capture `set` operations so you can do `Vue.set()` prevents the observer from working, and correctly passing global state via a global mixin

### What is expected?
Vue.observable() to work correctly

### What is actually happening?
Not working, state isn’t reflected on observer deps

**Comment by yyx990803** [comment]
This... just won't work because you are returning recursive proxies - and Vue 2's getter/setter overwrite via `Object.defineProperty` doesn't work on actual proxies.

hint: if it is that easy we would have already done it in Vue 2.

**Comment by DominusVilicus** [comment]
Okay, thanks for the quick reply.

Keen for Vue 3 then.
