### ISSUE TITLE
Vue transition-group is waiting for browser tab to be selected, before executing

### ISSUE THREAD

**Issue by MagicKriss** [vuejs/vue#9890]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/to3f51kc/](https://jsfiddle.net/to3f51kc/)

### Steps to reproduce
1. open a tab with Vue application with transition-group for dynamically generated content ( e.g. https://jsfiddle.net/to3f51kc/)
2. open another tab in a browser and wait for a minute.
3. switch back to the tab where Vue application was opened.

### What is expected?
After switching back to the tab with the Vue app, the only animations executed are those that were triggered only after the browser pane was selected.

### What is actually happening?
After switching back to the tab with the Vue app, some "leave transitions" that were triggered while different tab was active in the browser, get executed.

---

A list is generated in a v-for loop. Wrapped around it is a transition-group like so:
```
<transition-group name="list">
    <span v-for="item in items" v-bind:key="item" class="list-item">
      {{ item }}
    </span>
</transition-group>
```

A transition ( in css) on element deletion and creation is set:
```
.list-enter-active, .list-leave-active {
    transition: all 0.5s;
}

.list-enter {
    background-color: green;
}

.list-leave-to {
    background-color: red;
}
```
(Flash red before removing from the list. Flash green after inserting into the list)

The problem is that, if another tab on the browser is selected, and update on a list is made, the transition waits for the tab where Vue is to be selected. And only then transition gets executed.

The issue was noticed on:
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
and
Firefox Quantum 66.0.3 (64-bit)

While the issue can be seen on both Firefox and Chrome, it's more noticeable on Chrome

**Comment by posva** [comment]
Unfortunately, this is due to how browsers trigger the `transitionend` events when tabs are inactive.

If this is problematic for the kind of animation you are doing, you should switch instead to something that uses JS instead of CSS animations. That way, you can end the animation calling the `done` callback with js hooks: https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

**Comment by sanjacob** [comment]
Use :class instead and css transition.
