### ISSUE TITLE
Checked attribute doesnt work properly

### ISSUE THREAD

**Issue by skavorodka** [vuejs/vue#9891]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/skav/moks07y2/4/](https://jsfiddle.net/skav/moks07y2/4/)

### Steps to reproduce
Check a checkbox

### What is expected?
Label and attribute are the same as state

### What is actually happening?
Label is the same as actual state, but checked attribute doesnt change at all

---
It works perfectly on 2.5.x versions, but brokes in 2.6.x (and below 2.5)

**Comment by posva** [comment]
by adding .prevent you are preventing the browser to change the visual state at the same time as Vue renders. This was due to the change in macro/micro tasks described in release notes
