### ISSUE TITLE
Wrong order transition hooks

### ISSUE THREAD

**Issue by victor-AA** [vuejs/vue#9896]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/738vwq5nz1](https://codesandbox.io/s/738vwq5nz1)

### Steps to reproduce
1. Add transition hooks @after-enter and @after-leave on transition component
2. Add router-view inside transition component
3. Add css for transition component
4. Add methods for after-enter and after-leave hooks
5.  Hooks called in  wrong order.

### What is expected?
Hooks called first @after-leave then @after-enter

### What is actually happening?
Hooks called first @after-enter then @after-leave

**Comment by posva** [comment]
There isn't such guarantee in the default mode when both transitions happen at the same time.

What made you think it had to be a specific order?

**Comment by jwanggggg** [comment]
There was a similar discussion previously regarding before-leave transition hooks; you may find the discussion and workaround [in this issue](https://github.com/vuejs/vue/issues/9573) useful.
