### ISSUE TITLE
Functional Single File Components fail to compile v-model

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#9898]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/r58jr04jlo](https://codesandbox.io/s/r58jr04jlo)

### Steps to reproduce
Click on the checkbox.

### What is expected?
The checkbox should be selected without throwing js errors.

### What is actually happening?
It's issuing an error becasue the compiled js code assumes it's a stateful component and tries to use `_vm.$set()`.

**Comment by posva** [comment]
Hey, can you move this to vue-loader repo, please?

**Comment by miljan-aleksic** [comment]
Ups, ok!
