### ISSUE TITLE
Vue.extend subclass `version` property

### ISSUE THREAD

**Issue by julienzakaib** [vuejs/vue#9901]
### What problem does this feature solve?
Currently, the `Vue.extend` function returns a subclass and copies over many properties from the parent unto the subclass constructor.

```
//  vue/src/core/global-api/extend.js 
// allow further extension/mixin/plugin usage
Sub.extend = Super.extend
Sub.mixin = Super.mixin
Sub.use = Super.use
```

However, the `version` property is not copied over. Is there a reason for this? Or is the client expected to go up the class hierarchy using the `super` property in order to get the version of the root Vue constructor?

### What does the proposed API look like?
 Sub.version = Super.version

**Comment by yyx990803** [comment]
This is intentional. `Vue.version` is a true global, it's not meant to be exposed anywhere else.
