### ISSUE TITLE
destoryed钩子函数可以无障碍访问data和methods

### ISSUE THREAD

**Issue by liuzemei** [vuejs/vue#9904]
### Version
2.6.10

### Reproduction link
[https://github.com/liuzemei/helloworld](https://github.com/liuzemei/helloworld)

### Steps to reproduce
npm install
npm run serve

然后有打开控制台，到console，然后点击两次showHello

### What is expected?
在created()的生命钩子中，我打印了“这个组件创建了”，然后再destroyed()的生命钩子中，我打印了“这个组件被销毁了”，然后同时访问并修改了data里的数据并打印，也访问了一个printHello的methods方法，

如果说整个组件被销毁，应该是所有的内容都被销毁，包括data和methods里的变量以及变量值。

这个时候，我访问data应该给我提示报错  xxx is not defined。
我访问 methods 应该给我提示报错 xxx is not function 

### What is actually happening?
但是我却访问且修改成功了...这样的话，如果我在其他函数里设置一个递归的计时器，然后在destroyed时，清除这个计时器就会无效，因为settimeout是一个异步函数，destroyed会优先执行，再执行settimeout里面的函数，如果里面的变量和函数又都能访问到，那么这个计时器将不会被销毁。

---
期望在destoryed这个生命函数内，就直接把所有的变量及变量值全部销毁。

或者说我理解错了销毁的意思？

**Comment by Justineo** [comment]
> 这样的话，如果我在其他函数里设置一个递归的计时器，然后在destroyed时，清除这个计时器就会无效，因为settimeout是一个异步函数，destroyed会优先执行，再执行settimeout里面的函数，如果里面的变量和函数又都能访问到，那么这个计时器将不会被销毁。

我理解这是你想反映的更真实的 use case，所以请针对这个 case 给出一个可以运行的复现，谢谢。我理解你的问题和 build 过程无关，所以最好使用 CodeSandbox/CodePen/JSFiddle 等在线工具给出。

**Comment by yyx990803** [comment]
你对“销毁” 的理解确实不对。destroyed 只是指这个组件已经被从渲染树中移除，组件本身依然存在，只是之后会被垃圾回收。你给出的 ”重现“ 是预期行为。关于清除 setTimeout，这个其实才是你的问题重点，然而你的描述很模糊，也没有给出具体代码，恕我无法理解你到底在表达什么，因为 setTimeout 如果在触发前被 clearTimeout，回调是不会触发的。
