### ISSUE TITLE
collect watchers' effects and flush after watchers' update

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue#9908]
### What problem does this feature solve?
Recently, I try to implement the vue version of `react-flip-toolkit`. But there is no suitable place to get the dom snapshots. Of course, I can use the hook `beforeUpdate`, but there are some problems for it. Because the flip context should cache the state for all its related doms' snapshots (the dom may be a portal, which isn't the descendant of the flip context), and currently the schedule strategy for updating watchers may make the snapshot not reliable.

For example, the flip context includes componentA and componentB, and componentB is neighbor of componentA. When componentA and componentB both need to update, the scheduler will update componentA's watcher, and then componentB's.
In componentA's `beforeUpdate` hook, we cache its dom's snapshot, then updating its view, .e.g, its height. Then in componentB's `beforeUpdate` hook, we cache a WRONG snapshot, because a layout reflow will be triggered by previous componentA's update, affecting componentB's bounding rect (and here an unnecessary layout reflow is triggered).

To handle this case, we can do something like React, which updates watchers without updating dom, but collects their side effects (dom updates), and until the all states are stable. Then trigger watchers' some api like `getSnapshotBeforeUpdate()`, and finally flush all side effects.

### What does the proposed API look like?
`getSnapshotBeforeUpdate()`, triggered after all watchers' updated, and before flushing all side effects (dom updates).

**Comment by yyx990803** [comment]
3.0 will behave similar to this, but I don't think we will be able to do this in 2.x due to the complexity of this feature.
