### ISSUE TITLE
Remove useless parameter to the function removeVnodes

### ISSUE THREAD

**Issue by hanzichi** [vuejs/vue#9910]
### What problem does this feature solve?
The first parameter of function `removeVnodes` is useless, remove it to cut down the code 

the function is <https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L361>

### What does the proposed API look like?
Remove the first parameter `parentElm` of the function [removeVnodes](https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L361), and remove the place which calls the function as well

**Comment by raphaelkieling-egsys** [comment]
It's true, but strange... on all calls has a `parentElm` different

**Comment by raphaelkieling** [comment]
It's true, but strange... on all calls has a parentElm different

**Comment by hanzichi** [comment]
@raphaelkieling I wonder if all of them are useless .. or in another use?
