### ISSUE TITLE
Expose high level API for rendering dynamic templates

### ISSUE THREAD

**Issue by PeterMarinov** [vuejs/vue#9911]
#### Background

I am coming from the background of server side and full stack development. Vue is a relatively new passion for me, so please excuse me if this request does not fit well in the Vue's log term vision or if the proposed solution lacks completeness. I have read all GitHub issues that might touch upon the same problem, but none of them was described well or was adding useful business context. 

#### Problem

The business case is that I want to use Vue in the context of a multipage application, where the components used on the page are not known at build time. The decision is taken by content editors via a CMS page builder, which will generate dynamic HTML pages on the fly using the Vue components signatures corresponding to the Props they have modified at Page design time.

As a developer, I want to be able to provide extensibility points on top of Vue, that will allow content editors to choose between different set of predefiend templates for any Vue component that I have provided as a building block for the pages they will manage.

Vue already supports dynamic template compilation and static render functions for performance optimisations. This is part of its core and absolutely love the performance optimisations part of the VNode compilation analysis. The problem is that the internals of Vue that process this functionality are not well documented and or easy to use, so it took me couple of days of digging to find the solution (below).

My goal with reporting this issue is to improve the discoverability of that aspect of Vue, so it becomes a preferred choice for developers building various frameworks on top of Vue. I think, this will also help people develop better UI libraries on top of Vue, such as Vuetify, Bootstrap Vue and etc.. My feeling is that most developers did not found how to enable their UI components to support dynamic templates and improve the extensibility of their UI libraries. 

Here is the code that I developed to deal with it:

``` JavaScript
    export default {
        name: "Error",
        props: {
            templateId: {
                type: String  // templateId gives the address of the template to be used in the form of script tag Id
            },
            heading: {
                type: String
            },
            message: {
                type: String
            }
        },
        render: function (h) {
            let template = document.getElementById(this.templateId);
            if (typeof this.templateId === 'undefined' || template === null)
                return this.renderDefaultTemplate();

            const compiled = Vue.compile(template.innerHTML.trim());
            this.$options.staticRenderFns = [];
            this._staticTrees = [];
            compiled.staticRenderFns.map(fn => (this.$options.staticRenderFns.push(fn)));

            return compiled.render.call(this);
        },
        methods: {
            renderDefaultTemplate: function () {
                // template generated with https://vuejs-tips.github.io/compiler/
                const staticRender = new Function(`with (this) {
            return _c('div', {
                staticClass: "error-message-box"
            }, [_c('div', {
                staticClass: "error-header"
            }, [_c('p', [_v(_s(heading))])]), _c('div', {
                staticClass: "error-main-message"
            }, [_c('p', [_v(_s(message))])])])
        }`);
                return staticRender.call(this);
            }
        }
    };

```

### What does the proposed API look like?
I see 3 possible directions for solution

**Option 1:** if you think that the existing API is adequate, I would love to participate in improving the documentation for the render aspect of Vue.

**Option 2:**  If you like the idea of refactoring current compilation functions in order to expose an easy-to-consume API function for developers, I would love to contribute too.

I am thinking of something that will transform the following lines:

```
  const compiled = Vue.compile(template.innerHTML.trim());
            this.$options.staticRenderFns = [];
            this._staticTrees = [];
            compiled.staticRenderFns.map(fn => (this.$options.staticRenderFns.push(fn)));

            return compiled.render.call(this);
```

to the following lines:

```
            const compiledCode = Vue.compile(template.innerHTML.trim());
            return compiledCode.toVirualNodes(options);
```

**Option 3:** . If you consider this to be more suitable for Vue 3, I would love to contribute there too.

Just let me know on your thoughts of the relevance and value of this for the community and the project and I would love to make it happen!

**Comment by Justineo** [comment]
You can just create a new component on the fly with a plain object: https://jsfiddle.net/Justineo/foh7u56m/

**Comment by posva** [comment]
Hey, thanks for the insights on this but I don't get what you are trying to solve. To me, it looks like you are either rendering a component with a template written somewhere on a component or allowing the user to specify a template to be rendered inside like @Justineo pointed out

What are you achieving with this?

```js
const compiled = Vue.compile(template.innerHTML.trim());
            this.$options.staticRenderFns = [];
            this._staticTrees = [];
            compiled.staticRenderFns.map(fn => (this.$options.staticRenderFns.push(fn)));
```

**Comment by PeterMarinov** [comment]
Hey guys,

thank you all for the quick responses and the spot on suggestions/questions.

@posva - Technically speaking, my goal is to achieve exactly the same functionality, which @Justineo has demonstrated in his JsFiddle - decouple the business logic of the component from the template, so that template can be selected at runtime.  I am only doing those extra lines of code to resolve the initial issues I have found with data binding and usage of attributes. To better answer the question of what I was trying to solve, I have modified the sample of @Justineo to demonstrate the type of issues I have faced  (check template `bar`) and the solution I have come up with (check the `vuecan` template). Here is the modified JsFiddle - [https://jsfiddle.net/9t5ajowu/](https://jsfiddle.net/9t5ajowu/). Please let me know on your thoughts

I am not an expert, so maybe there is a better way of doing this, in which case I will feel a bit embarrassed, but maybe there is an opportunity to improve the official documentation, on which I will be happy assisting too.

**Comment by Justineo** [comment]
https://jsfiddle.net/Justineo/y239e76m/

I don't think it's necessary to expose the compiler as you can define any component with a template on the fly.
