### ISSUE TITLE
Update value in a custom directive inside v-for

### ISSUE THREAD

**Issue by metalfox6383** [vuejs/vue#9913]
### What problem does this feature solve?
Hi:
I want to update the value of my object from my custom directive. For example:

```
<div v-for="itemVal in values">
 <any-element v-test="itemVal"></any-element>
</div>
```

Any-element permit to the user update data and this data must save in itemVal.

Before, I used v-model with my custom directive:

```
<div v-for="itemVal in values">
 <any-element v-test v-model="itemVal"></any-element>
</div>
```

```
Vue.directive('test', {
	bind: function (el, binding, vnode) {
                //code
		vnode.data.model.callback(newValue);
                //code
	}
});
```

But it seems that this option is no longer available.

What can I do for update that value.

### What does the proposed API look like?
Update reference value.

**Comment by posva** [comment]
To update the original data, you have to bind it to the array instead. You can do so by using the index. I'm closing this as it is a question and it should be asked in the forum or discord chat :)
