### ISSUE TITLE
this.$nextTick is no longer work in Vue 2.6.10

### ISSUE THREAD

**Issue by FinauKaufusi** [vuejs/vue#9918]
### Version
2.6.10

### Reproduction link
[https://stackoverflow.com/questions/48913579/vue-js-keyup-keydown-events-one-character-behind](https://stackoverflow.com/questions/48913579/vue-js-keyup-keydown-events-one-character-behind)

### Browser and OS info
IOS 

### Steps to reproduce
I have a form input field, which I count the number of characters when @keydown event execute.  From my console log, it's obviously show the characters counter is behind by 1 characters.

### What is expected?
When I enter the first characters in my form field, it should tell me the counter is 1 instead of 0.

### What is actually happening?
When I entered the first characters the counter is still show 0 length.  It suppose to show 1 in length.

**Comment by LinusBorg** [comment]
This is likely related to the necessary nextTick change in 2.6.

Is there a specific reason for using `keyup` instead of `input`? The latter works reliably as its the same event that v-model uses.

**Comment by posva** [comment]
Hi, this is likely to be what @linusborg said but please, correctly follow the steps for reproduction link when opening an issue
