### ISSUE TITLE
Pluggable validators for props

### ISSUE THREAD

**Issue by mariuszjamro** [vuejs/vue#9923]
### What problem does this feature solve?
Currently `required`, `type` and `validator` properties can be used to validate a prop. I propose an extension that will accept list of validators and possible refactoring of `required` and `type` parameters to simplify the implementation. This way will allow easy reuse of validation logic between components, as you'll be able to easily pass pluggable validators to the prop.

### What does the proposed API look like?

Current way:
    
    Vue.component('my-component', {
      props: {
        propA: {
            type: [Number],
            required: true,
            validator: function(value){
                //Validation logic
                return value > 0;
            }
        }
    })
    
Proposed way:

    function myCustomValidator(){
        //Validation logic
        return (value) => value > 0;
    }

    Vue.component('my-component', {
      props: {
        propA: {
           validators: [
                requiredType([String, Number]),  // Equivalent of `type: [String, Number]`
                isRequired(),                    // Equivalent of `required: true`
                myCustomValidator(),             // Custom validator
          ]
        } 
      }
    })

**Comment by Justineo** [comment]
This can be easily implemented in userland:

```js
import { createValidator, requiredType, isRequired } from 'my-vue-validate-utils'

function myCustomValidator(){
    //Validation logic
    return (value) => value > 0;
}

Vue.component('my-component', {
  props: {
    propA: {
      validator: createValidator([
        requiredType([String, Number]),  // Equivalent of `type: [String, Number]`
        isRequired(),                    // Equivalent of `required: true`
        myCustomValidator(),             // Custom validator
     ])
    } 
  }
})
```
