### ISSUE TITLE
Passing props object to property validator

### ISSUE THREAD

**Issue by freearhey** [vuejs/vue#9925]
### What problem does this feature solve?
This feature will allow to do validation based on the value of other properties.

### What does the proposed API look like?
```js
Vue.component('my-component', {
  props: {
    propA: 'String',
    propB: {
      validator(value, props) {
        switch(props.propA) {
          case 'email':
            return validEmail(value)
          case 'tel':
            return validTel(value)
          default:
            return true
        }
      }
    } 
  }
})
```

**Comment by posva** [comment]
Thanks for your interest. This is a technical limitation right now and is being discussed in another issue regarding props validation. I'm struggling to find it on phone
Closing as a duplicate
