### ISSUE TITLE
Number Input Does Not Accept Decimals While Using Firefox

### ISSUE THREAD

**Issue by ilhansubasi** [vuejs/vue#9927]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/618c7pe5/](https://jsfiddle.net/618c7pe5/)

### Steps to reproduce
Start USA English 64-bit Firefox 66.0.3 on USA English Windows 10. Visit https://jsfiddle.net/618c7pe5/ and then enter 1 to "km" field (it is the first number field).

### What is expected?
The mil (second number field) should not have been red in Firefox. It should have accepted "0.621371" or "0,621371" as valid input.

### What is actually happening?
In Firefox the "mil" (second number field) becomes red. It says "Please select a valid value. The two nearest valid values are 0 and 1". It doesn't like "0,621371".

---
Google Chrome and Firefox are USA English. Their preferred first language is USA English. Windows 10 is USA English. The HTML code in https://jsfiddle.net/618c7pe5/ indicates that the page is Turkish. I am located in Turkey. I think my location settings are "like in USA" because in Calculator 10 decimal numbers are like "3.1415".

**Comment by posva** [comment]
Hey, as I said, this is not related to Vue. Also you still didn't provide a repro

**Comment by yxngl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values

**Comment by ilhansubasi** [comment]
It has been solved with `step="any"` https://stackoverflow.com/questions/36031499/firefox-does-not-allow-decimals-in-inputtype-number#comment94061330_36031715
