### ISSUE TITLE
Scoped styling isn't applied to the first node in a nested functional SFC

### ISSUE THREAD

**Issue by rkomiyama** [vuejs/vue#9928]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/my8338v6xj](https://codesandbox.io/s/my8338v6xj)

### Steps to reproduce
Create a functional SFC, and then create a functional child SFC within it. Create scoped styling for both parent and child functional SFCs.

### What is expected?
Scoped styling should work in the functional child SFC for all of its nodes.

### What is actually happening?
The scoped styling for the child functional SFC is not being applied to the first node. The styling will only work when `scoped` is removed from the child's style tag.

**Comment by posva** [comment]
Hey, thanks for filling the issue. Can you open it in Vue loader repo please?
