### ISSUE TITLE
"else-clause" for v-show: v-show / v-or-show / v-hide

### ISSUE THREAD

**Issue by masi** [vuejs/vue#9929]
### What problem does this feature solve?
Unlike v-if there are no directives to chain expressions (v-else-if) or negate the expression (v-else). Adding two new directives will make v-show on par with v-if.

### What does the proposed API look like?
A v-show directive may be followed by optional v-or-show directives with expressions and a single v-hide directive without expression.

eg.
```
<div v-show="state == 0">...</div>
<div v-or-show="state > 0">...</div>
<div v-hide>...</div>
```

**Comment by sirlancelot** [comment]
`v-show` simply toggles the CSS `display` property, meaning it doesn't need the optimizations provided by `v-if`/`v-else-if`/`v-else` whereby the vdom of unmatched branches isn't rendered.

In your example you don't need new directives. You should write them as `v-show` expressions. After that, if the logic gets too complicated to be in the template, then make a computed property for the logic.

**Comment by posva** [comment]
I think @sirlancelot explanation is really good. But yeah v show doesn't really need an else directive

**Comment by smalllong** [comment]
It's a pity vue doesn't have an else directive for v-show, which makes changing between v-if and v-show complicated, and implicitly urging developers to always use v-if than v-show, resulting in higher toggle costs

**Comment by sirlancelot** [comment]
@smalllong My standard practice is to always start with `v-if`. The _only_ scenario in which I've needed `v-show` is when I'm using a transition and I never need an "else"-like construct for that scenario. Hopefully that helps!
