### ISSUE TITLE
window.getSelection is not function

### ISSUE THREAD

**Issue by Hufe921** [vuejs/vue#9936]
### Version
2.5.21

### Reproduction link
[https://jsfiddle.net/soLtbp02/](https://jsfiddle.net/soLtbp02/)

### Steps to reproduce
 mounted() {
    console.log(window.getSelection()); // demo:1

    let selection = window.getSeletion(); // demo:2
    console.log(selection);
  }

demo2 is error： TypeError: window.getSeletion is not a function

### What is expected?
window.getSelection  is right

### What is actually happening?
window.getSelection is not function

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is not related to Vue

**Comment by Justineo** [comment]
You typed `getSeletion` instead of `getSelection`.
