### ISSUE TITLE
Performance issues with d3.js

### ISSUE THREAD

**Issue by yzw7489757** [vuejs/vue#9940]
### Version
2.6.4

### Reproduction link
[https://codepen.io/Floyd_seven/pen/NmJNxa](https://codepen.io/Floyd_seven/pen/NmJNxa)

### Steps to reproduce
in mounted hook

### What is expected?
Good rendering process

### What is actually happening?
Using a canvas won't cause a stuck but using svg will

---
There undefineds no problem with fewer charts, and canvas works well, but when you use d3.js to render multiple svg charts and add some animations, cpu is too burdensome to render Smooth, and I want to know how to do it better.

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

PS. Your reproduction is not runnable.
