### ISSUE TITLE
Inline CSS properties into the style attribute in an html file. Useful for emails.

### ISSUE THREAD

**Issue by gauseen** [vuejs/vue#9941]
### What problem does this feature solve?
获取 this.$el.outerHTML 字符串模板，并带有内联 css。  
可解决我的打印机设备，样式显示问题

### What does the proposed API look like?
none

**Comment by Justineo** [comment]
提交新功能请求请详细阐述遇到问题和期望的解决办法，不要随便两句话就提需求。谢谢。
