### ISSUE TITLE
keep-alive 包含router-view 使用include功能问题

### ISSUE THREAD

**Issue by freeloopmko687** [vuejs/vue#9942]
使用keep-alive 结合router-view 实现页面缓存时，给router-view 添加key,在keep-alive使用include。include内容为key数组，想通过这种方式实现同个页面多份缓存的功能，但是include功能不能生效，到底是什么原因呢？

![1556446644785](https://user-images.githubusercontent.com/8393200/56862861-f0cc7500-69e1-11e9-8700-5fd9e65fda8f.jpg)
![1556446652706](https://user-images.githubusercontent.com/8393200/56862863-f4f89280-69e1-11e9-9147-e14faa67f9ec.jpg)
![1556446660930](https://user-images.githubusercontent.com/8393200/56862866-f7f38300-69e1-11e9-9249-603de2c564ce.jpg)

**Comment by ileadall42** [comment]
请问你解决了吗？我include 传的值根本没有传过去~
