### ISSUE TITLE
Infinite loop when using dynamic import to lazy load component inside the root render function

### ISSUE THREAD

**Issue by unlocomqx** [vuejs/vue#9943]
### Version
2.6.10

### Reproduction link
[https://github.com/unlocomqx/vue-loop-reproduction](https://github.com/unlocomqx/vue-loop-reproduction)

### Steps to reproduce
- npm install
- npm run serve
- open http://localhost:8080
- the tab should freeze because of the infinite loop

### What is expected?
The list component should be injected in #list showing List 123

### What is actually happening?
The tab freezes and mem consumption increases continually

```
  // this works fine
  let factory = () => import(`@/components/async/List.vue`);
  new Vue({
    store,
    render: h => h(factory),
    el: `#list`,
  });

  // this get caught in infinite loop
  new Vue({
    store,
    render: h => h(() => import(`@/components/async/List.vue`)),
    el: `#list`,
  });
```

---
When using a variable to store the import function, the code works fine but when using the import function directly in the render function, the code bugs

**Comment by posva** [comment]
it's indeed creating a loop but lazy loading the root component doesn't make sense as you need it right away. The variable allows us to track whether the component is loaded or not, that's why it differs.

**Comment by unlocomqx** [comment]
Hi @posva, It was just a contrived reproduction example to show the bug.
Anyway, I wanted to report it so someone else wouldn't fall for it and go crazy
PS: In the real scenario, I intend to lazily inject vue components in a legacy app
