### ISSUE TITLE
keep-alive 结合 router-view 缓存问题

### ISSUE THREAD

**Issue by freeloopmko687** [vuejs/vue#9944]
### What problem does this feature solve?
使用keep-alive 结合router-view 实现页面缓存时，给router-view 添加key,在keep-alive使用include。include内容为key数组，想通过这种方式实现同个页面多份缓存的功能，但是include功能不能生效，到底是什么原因呢？

### What does the proposed API look like?
<keep-alive :include="cachePages">
          <router-view :key="$route.fullPath">
            
          </router-view>
        </keep-alive>

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
