### ISSUE TITLE
Component with slot render not own nested component

### ISSUE THREAD

**Issue by pumano** [vuejs/vue#9948]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/jzzr8nnn3](https://codesandbox.io/s/jzzr8nnn3)

### Steps to reproduce
1) Create component with ```<slot></slot>```

2) Use that component for set nested component to that slot

3) After import third component, that third component override current nested component

### What is expected?
Only exact component set to slot should be rendered

### What is actually happening?
rendered any some random component

---
That behaviour I found with TypeScript with *.vue components   vue class components / vue property decorator

**Comment by posva** [comment]
You are missing the `@Component`:

```ts
import { Vue, Component } from "vue-property-decorator";

@Component
export default class FirstForm extends Vue {}
```

See https://github.com/kaorun343/vue-property-decorator#usage

**Comment by pumano** [comment]
@posva thank you for fast response, yes, looks like im forget to add. It solve my issue, but looks like we don't have any error about that? Maybe good to have error, when someone forget to add @Component decorator?
