### ISSUE TITLE
Parent mounting happens before child mounting using async and vue router

### ISSUE THREAD

**Issue by TheInvoker** [vuejs/vue#9951]
### Version
2.6.10

### Reproduction link
[https://jsbin.com/nikiroboxa/edit?html,output](https://jsbin.com/nikiroboxa/edit?html,output)

### Steps to reproduce
I'm using vue/vue-router to load a website. This is the code that demonstrates the issue.

    <!DOCTYPE html>
    <html>
        <head>
            <title>Title of the document</title>
            <script src="https://unpkg.com/vue"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/vue-router/3.0.6/vue-router.min.js"></script>
        </head>
        <body>
            <div id="app">
                <router-view></router-view>
            </div>
            <script>
                Vue.component('a-a', function(resolve, reject) {
                    setTimeout(function() {
                        resolve({
                            template : "<div>A</div>",
                            mounted : function() {
                                alert(1);
                            }
                        });
                    }, 2000);
                });
                new Vue({
                    el: '#app',
                    router : new VueRouter({
                        mode: 'history',
                        routes: [
                            { path: '/foo', component: Vue.component("a-a") }
                        ]
                    }),
                    mounted : function() {
                        alert(2);
                    }
                });
            </script>
        </body>
    </html>

I modified IIS to allow REST style links to return the above page like this

    <rewrite>
      <rules>
        <rule name="SPA Routes" stopProcessing="true">
          
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            
            
            
            <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
            
          </conditions>
          
          <action type="Rewrite" url="App/test2.html" />
        </rule>
      </rules>
    </rewrite>

When I visit the page, I use the link `/App/test2.html/foo`, and it returns the page above.

What I then expect is vue-router to load the component based on the url path, then async load the component, waiting on the resolve function, then run the mounted function on the child, then finally run the mounted function on the parent. So basically alert 1, then 2. But the parent alerts first, so it does 2, then 1.

How can I get the child to mount first?

Thanks

### What is expected?
Alert 1, then Alert 2

### What is actually happening?
Alert 2, then Alert 1

---
The jsbin doesn't work so well with vue router, so you could just save as a file and use node.js or IIS to make rest links return the page.

**Comment by posva** [comment]
This is expected behaviour in both regular vue and vue-router: the parent can mount while waiting for the child async components to mount. It's usually what we want too

**Comment by TheInvoker** [comment]
Then how could I modify the code so the child mounts first?
