### ISSUE TITLE
当keep-alive的页面在某种情况下调用了$destroy后，再次进入这个页面，这个页面也不会再被缓存

### ISSUE THREAD

**Issue by calmchang** [vuejs/vue#9952]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/llo55mv08q](https://codesandbox.io/s/llo55mv08q)

### Steps to reproduce
1、打开页面
2、在输入框内输入一些字符串
3、点击 click to next page 跳转到下一页
4、点击 click go back 返回前一页
5、可以看见输入框内的文字是之前输入的内容
6、点击 click to next page and $destroy this page
7、点击 click go back 
8、此时由于之前页面被释放，所以输入框内的文字恢复到默认状态
9、再次在输入框内输入一些文字
10、点击 click to next page
11、点击 click go back
12、此时回到页面后发现页面并没有被缓存下来，输入框内的文字恢复到默认状态

### What is expected?
期望第12步的时候页面被缓存了下来

### What is actually happening?
未缓存

---
问题导致的原因是：当页面调用$destroy后，这个页面从此就再也不会被keep-alive了，有什么办法能恢复keep-alive的效果？

**Comment by yyx990803** [comment]
正常的应用逻辑下没有理由手动  $destroy，办法就是不要手动使用 $destroy

**Comment by calmchang** [comment]
那如果我在某些情况下需要将keep-alive的页面全部重新加载渲染一遍的话，建议用什么方法来控制比较好

**Comment by calmchang** [comment]
> 正常的应用逻辑下没有理由手动 $destroy，办法就是不要手动使用 $destroy

那如果我在某些情况下需要将keep-alive的页面全部重新加载渲染一遍的话，建议用什么方法来控制比较好
