### ISSUE TITLE
【keep-alive 发现一种情况内失效】需求繁多，奇葩布局也多

### ISSUE THREAD

**Issue by LaoCheng-cjs** [vuejs/vue#9953]
### Version
2.6.10

### Reproduction link
[http://没有.com](http://没有.com)

### 第一步：

> 做个中间自适应高度且可以滚动（需求部分省略），使用 solt 进行将 <keep-alive><component :is="keepC"></component></keep-alive> 包进去，哈哈哈，懒人真好

> 下面是scroll-y代码

```html
<template >
    <div class="scroll-wrap">
        <slot slot="top"></slot>
        <div class="scroll" >
            <div :class="{'scroll-y':scrolled}" @scroll="$emit('on-scroll')">
                <slot></slot>
            </div>
        </div>
        <slot name="bottom"></slot>
    </div>
</template>
```

> 下面是在首页使用到 scroll-y 的组件了，哈哈哈哈

```html
<template>
    <scroll-y>
         <!-- 内容 -->
        <keep-alive>
            <component :is="keepC"></component>
        </keep-alive> 
     <!-- 导航部分 -->
       <nav solt="bottom">
         <!-- 代码块，手敲好累，还不能按tab，按了跑下面去了，卧槽勒 --->
      </nav>
   </scroll-y>
</template>
```

### What is expected?
这个是因为什么？？

### What is actually happening?
这个是因为什么？？

**Comment by LaoCheng-cjs** [comment]
```
<!-- 第二步的标题上这标签没显示出来：-->
<template data-v-6b244841=""></template>
```

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue: Provide a boiled down repro when reporting a bug
Thanks!
