### ISSUE TITLE
"Failed to mount component: template or render function not defined" while building CLI Hello World TS app with webpack

### ISSUE THREAD

**Issue by crisz** [vuejs/vue#9954]
### Version
2.6.10

### Reproduction link
[https://github.com/crisz/example-vue-ts-app](https://github.com/crisz/example-vue-ts-app)

### Steps to reproduce
- open a terminal
- type the command: `git clone https://github.com/crisz/example-vue-ts-app.git`
- install dependencies: `npm install`
- run the script: `npm run dev:build`
- open the **build/index.html** file

### What is expected?
The "Hello World" application to appear

### What is actually happening?
The page is blank and there is the following error in the console:
Failed to mount component: template or render function not defined

---
What I did was just copying the src folder from the @vue/cli ts default "Hello World" application to try to build it on my own with webpack, but after a lot of attempts and days spent, nothing seems working.
 
I have an existing typescript application which I've built on top of webpack, and I'd like to add vue in the chain (in this case vue is just one of many widgets, so it would make no sense to use the cli). However, when I went out from the vue/cli environment nothing worked and I'd like to understand why.

I'm sorry if this is not a real bug report, but I could have chosen only between "bug report" and "feature request" (this is not probably a bug but just a lack of documentation).

I've already asked on StackOverflow (link here: https://stackoverflow.com/questions/55892964/vue-ts-application-in-webpack-shows-failed-to-mount-component-template-or-rend) but it had no luck, and googling around looks like there are no many that tried this configuration.

Here is my webpack configuration:

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
require('file-loader');

module.exports = {
  entry: './src/main.ts',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'main.bundle.js'
  },
  module: {
      rules: [
          {
              test: /\.ts$/,
              use: 'ts-loader'
          },
          {
            test: /\.vue$/,
            use: [{loader: 'vue-loader', options: {loaders: {}, esModule: false}}, {loader: 'ts-loader'}]
          },
          {
            test: /\.css$/,
            use: [{ loader: 'style-loader' }, { loader: 'css-loader' }]
          },
          {
            test: /\.(png|jpg|gif)$/,
            loader: 'file-loader',
            query: {
              name: '[name].[ext]?[hash]',
              useRelativePath: true
            }
          }
      ]
  },
  plugins: [
    new HtmlWebpackPlugin({template: './index.html'}),
    new VueLoaderPlugin()
  ],
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.js' // I tried all of these...
    },
    extensions: ['.vue', '.ts', '.js', '.json']
  },
};
```

**Comment by posva** [comment]
The cli template folder isn't meant to be copied like that.
The error seems to say you are using a string template somewhere instead of using Vue SFC.

Closing because this is a usage question and should be kept in appropriate channels 🙂

**Comment by crisz** [comment]
Hi posva, thank you for fast (almost immediate) clarification. I don't know any other appropriate channel (otherwise I didn't open the issue :) I'm aware this is not the correct place). Could you advise one? Is there some official?

Thank you
