### ISSUE TITLE
Using replaceChild instead of inserting the updated node and removing the old one.

### ISSUE THREAD

**Issue by SiddharthBose-Codeware** [vuejs/vue#9959]
### What problem does this feature solve?
For example, I have `<div id="app> {{ info }} </div>` and it will be attached to the Vue object. Let's assume we have info in our data with the value 'Hello'. Now, Vue renders the updated node with the info value inside it which is `<div id="app">Hello</div>` in this case , and removes the one with the curly braces. Now, what happens is our app gets two elements with the same id if it is even for a split second. Here, we can use `replaceChild` function to replace the old node with the new node. `replaceChild` is not supported by IE8, but still Vue does not supports it.

### What does the proposed API look like?
`nodeOps.replaceChild(oldNodeWithBraces, newNodeWithActualData)`

**Comment by Justineo** [comment]
> Now, what happens is our app gets two elements with the same id if it is even for a split second.

As I understand you are reporting a bug (or at least unexpected behavior). So please do provide a runnable reproduction for your case, as suggested by the [issue helper](https://new-issue.vuejs.org/). Thanks!
