### ISSUE TITLE
v-bind updates bound data after vm.$on() fires, so the handler works with obsolete data

### ISSUE THREAD

**Issue by Ser5** [vuejs/vue#9960]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/epzkrs6c/](https://jsfiddle.net/epzkrs6c/)

### Steps to reproduce
- Open browser console.
- Click "Item 2"
- Click "Item 2" again

#### First click

In console:

    Already switched to Item 2
    Doing calculations with Item 2

In browser:   
**I'm Item 2!**

#### Second click

In console:

    Already switched to Item 2
    Doing calculations with Item 2

In browser:   
**I'm Item 2!**

#### First click

In console:

    Already switched to Item 2
    Doing calculations with Item 1

In browser:   
**I'm Item 2!**

#### Second click

In console:

    Already switched to Item 2
    Doing calculations with Item 2

In browser:   
**I'm Item 2!**

---
After the first click it seems like component `c-item` already works with actual data, as it says "**I'm Item 2!**", but in fact the event handler operates with obsolete data, producing wrong results.

**Comment by posva** [comment]
This is expected: you are reading from a prop which haven't been updated yet because it takes a tick to update. That way Vue also prevents unecessary rerenders. You can wait for a tick with `$nextTick`
