### ISSUE TITLE
Vue app gets two elements having the same id

### ISSUE THREAD

**Issue by SiddharthBose-Codeware** [vuejs/vue#9961]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/gupvmj5x/](https://jsfiddle.net/gupvmj5x/)

### Steps to reproduce
Create `<div id="app">{{ info }}</div>` in the HTML, Create a new Vue instance by attaching the div. Add info as a data entry with a value, say 'Hello'. Run the app. To see the problem in action, pause the debugger at line 5873 in the Vue source file which is `nodeOps.removeChild(parent, el);`. In the Elements tab, there will be two divs with the same id.

### What is expected?
The first div with the curly braces is replaced with the new div containing the info data.

### What is actually happening?
The new div with the data is appended to the parent of the first div with the curly braces. Later the first div is removed which happens at line 5873.

---
There should a new function in `nodeOps` called `replaceChild` and should be used to perform the action which is expected. `replaceChild` is not present in IE8 but since Vue does not target IE8 we don't care.

**Comment by posva** [comment]
your repro is incomplete but if you include two divs with the same id, Vue cannot prevent that.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by SiddharthBose-Codeware** [comment]
The reproduction can be seen in the chrome debugger if you pause it at line 5873 in the Vue source file.

> if you include two divs with the same id, Vue cannot prevent that.

Vue is adding the duplicate id div.

**Comment by Justineo** [comment]
This is happening within a single task and won't affect the rendered result. There might be potential improvement here but switching to `replaceChild` isn't a drop-in replacement here but instead it need some refactoring of our current patching logic.

**Comment by SiddharthBose-Codeware** [comment]
Thanks for the reply!
