### ISSUE TITLE
Dependency not found while installed

### ISSUE THREAD

**Issue by jdorel** [vuejs/vue#9963]
### Version
2.6.10

### Reproduction link
[https://github.com/jdorel/vue-bug](https://github.com/jdorel/vue-bug)

### Steps to reproduce
I am trying to import a module created using the openapi-generator tool for javascript.

* Create  an new project (`vue create project`) with the default configuration
* Change directory to the project
* Install my local dependency (`npm install ../api/custom_api_javascript --save`)
* Call the dependency (`var CustomApi = require('custom_api')`) in `src/components/HelloWorld.vue` 
* Add webpack configuration according to module () in `vue.config.js`:
```
module: {
  rules: [
    {
      parser: {
        amd: false
      }
    }
  ]
}
```
* Run the development server (`npm run serve`)

PS: I also tried without the amd parser: false, but the result is the same.

### What is expected?
The dependency is found

### What is actually happening?
This dependency was not found:
```
* custom_api in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/home.vue?vue&type=script&lang=js&
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. This seems to be a question related to webpack. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by jdorel** [comment]
It appears to me to be a bug in the `vue create` process (that might be related to webpack, but that should be explicited as such).

**Comment by LinusBorg** [comment]
1. vue-cli has its own reporistory: https://github.com/vuejs/vue-cli
2. your reporistory link doesn't contain a vue-cli project.

**Comment by jdorel** [comment]
>     1. vue-cli has its own reporistory: https://github.com/vuejs/vue-cli
Sorry about that. Should I reopen I reopen the issue there, or would you prefer to just [transfer it](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) ? Or is it a webpack issue and have nothing to do with vue-cli ?

>     2. your reporistory link doesn't contain a vue-cli project.
My bad, because of the .git folder, it was added as a submodule. I corrected it.

**Comment by LinusBorg** [comment]
1. the webpack config you added is invalid. you copied the snippet from their README but it's not a valid piece of config in the way they show it.
2. did you build the ouput for that custom_api? it's not mentioned in your reproduction steps, and the package.json of that package points to `/dist/index`, which at least in the git repor doesn't exist:

https://github.com/jdorel/vue-bug/blob/master/api/custom_api_javascript/package.json#L6
