### ISSUE TITLE
activated/deactivated will trigger even there is no keep-alive

### ISSUE THREAD

**Issue by Yalhu** [vuejs/vue#9964]
### Version
2.6.10

### Reproduction link
[http://code at the end.vue](http://code at the end.vue)

### Steps to reproduce
Activated/Deactivated triggerd when jump to another route, while current route does't had keep-alive.
If jump to /contentList from /article, it will trigger article deactivated.
If jump to acticle, it will trigger activated.

It made lifecycle confused and I don't know in which lifecycle to request data or destory the instance built by UEditor(a third library of Rich Text Editing).

### What is expected?
I try to reuse the component:aricle when create a new article ,create a new component:article when change the old article. But failed.

### What is actually happening?
When jump to the route:article, there will not create a new one. It  is still the old 'article' .

---
```javascrit
const routes = [
  { path: '/contentList', component: ContentList},
  { path: '/publish', component: Publish ,
    children:[
      {path:'video',  components:{publish:Video},alias:'/video',meta:{keepAlive:true}},
      // {path:'article', name:'article', components:{publish:Article},alias:'/article',meta:{keepAlive:true}},
      {path:'article', name:'article', components:{publish:Article},alias:'/article',meta:{keepAlive:false}},

      {path:'video/:contentId', props:true,components:{publish:Video},alias:'/video/:contentId'},
      {path:'article/:contentId', props:true,components:{publish:Article},alias:'/article/:contentId'},
      
    ],
]
```
```html
// router-view: publish/article
<keep-alive>
        <router-view  v-if="$route.meta.keepAlive" name="publish" ref="form"></router-view>
</keep-alive>
<router-view v-if="!$route.meta.keepAlive" name="publish" ref="form" ></router-view>

// router-view:contentList,publish
<keep-alive exclude="Home">
       <router-view></router-view>
</keep-alive>
```

**Comment by posva** [comment]
You didn't provide any runnable repro, right now this looks more like an usage question and I will appreciate if you use the right channels to ask questions :)

Keep in mind that if a component is inside of a keep-alive, it will trigger the activated/deactivated (https://vuejs.org/v2/api/#keep-alive)

**Comment by Yalhu** [comment]
It's a great help! I'm sorry for omitting it.
That confused me a lot . Thanks your help!

Does it mean the code below is actually not working?Or does it still works, the only diffirence is there are activated/deactivated lifycycle?
```javascript
<router-view v-if="!$route.meta.keepAlive" name="publish" ref="form" ></router-view>
```

**Comment by posva** [comment]
I don't know what you want to do exactly, but keep-alive has an option called `include` that does what you seem to be looking for. You need to name your components though (not the same as a route name). But as I said, this should go in the appropriate channels 😉
