### ISSUE TITLE
How to ignore template tag?

### ISSUE THREAD

**Issue by SpinyMan** [vuejs/vue#9968]
### What problem does this feature solve?
Is there the ability to ignore `template` tag? Example: I use standard vue component that contains own `template` and other logic. But in the same time on the page other `template` tag exists and vue tries to parse it... How to avoid it?
```
<div id="app">
    <template class="bla-bla">
        <div><h1></h1></div>
    </template>
    <my-component></my-component>
</div>
```

### What does the proposed API look like?
`<template v-ignore>...</template>`

**Comment by posva** [comment]
you should put those templates outside of vue div instead but you can also do 

```html
<template v-pre type="text/x-template">hey {{ foo }}</template>
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by SpinyMan** [comment]
> you should put those templates outside of vue div instead but you can also do
> <template v-pre type="text/x-template">hey {{ foo }}</template>
> 
> Please, next time consider using the forum, the Discord server or StackOverflow for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

Sorry man, but this doesn't work as needed: it removes `template` tag... :(

**Comment by posva** [comment]
updated the comment with a demo but you should put the template outside

**Comment by SpinyMan** [comment]
> updated the comment with a demo but you should put the template outside

It's not the way... I see the problem still exists not only for me... Maybe someone will make the `template` tag ignored by `v-pre`. Still waiting. And please reopen this issue.

**Comment by sirlancelot** [comment]
I'm not certain on a good use-case for this. When the root Vue component is mounted, there's an expectation that it will control everything within the node that it is attached to. Why do you want to break that convention? If there's a strong use-case I'm sure the maintainers would be inclined to re-open the issue. As it is now though, this seems unnecessary.

**Comment by SpinyMan** [comment]
`<template v-pre>` compiles into [see screenshot](https://yadi.sk/i/sUeYOz9F6WZxTw)
Is it ok that `tr` tag is not a child of `#document-fragment`. So I just want you fix it OR gimme any solution to resolve it.

**Comment by sirlancelot** [comment]
That appears to be a proper bug. The node isn't getting attached to the document fragment.

**Comment by SpinyMan** [comment]
And now will you reopen this issue? Or you think there is my fault?

**Comment by SpinyMan** [comment]
> That appears to be a proper bug. The node isn't getting attached to the document fragment.

So, will you help me?

**Comment by yyx990803** [comment]
`<template>` is used as a special construct in Vue template syntax - it serves as a generic logic container for `v-if`, `v-for` and slots.

As @posva suggested: the solution is moving your `<template>` outside of the parts controlled by Vue, which seems easy enough.

**Comment by SpinyMan** [comment]
> which seems easy enough

Sorry but nope... I try to use laravel-admin with vue. And there no any way to move `template` tag outside... You have to fix vue src code for better work with `<template v-pre>`. I saw (on your forum) this problem is actual not only for me...

**Comment by stephantabor** [comment]
Here's my use case which lead me to this issue

I'm using a web component in vue, since it's allegedly compatible with web components

I have a template like this

```html
<custom-element-table>
  <template>
    <thead>
      <!-- table head stuff-->
    </thead>
    <tbody>
      <!-- table body stuff-->
    </tbody>
  </template>
</custom-element-table>
```

from which i would expect DOM like this:

```html
<custom-element-table>
  #shadow-root
  <template> <!-- in slot -->
    #document-fragment
      <thead>
        <!-- table head stuff-->
      </thead>
      <tbody>
        <!-- table body stuff-->
      </tbody>
  </template>
</custom-element-table>
```

but i get DOM like this, and a non functioning webcomponent:

```html
<custom-element-table>
  #shadow-root
  <thead> <!-- in slot -->
    <!-- table head stuff-->
  </thead>
  <tbody>
    <!-- table body stuff-->
  </tbody>
</custom-element-table>
```

**Comment by stephantabor** [comment]
related #9427

**Comment by ukaaa** [comment]
I have the same use case. My own custom element relies on template tags. And now I can't use it at all.

```
<tt-table>
    <template name="Column 1"></template>
    <template name="Column 2"></template>
</tt-table>
```

**Comment by stephantabor** [comment]
@ukaaa no i didn't, i ended up reimplementing it in vue. It seems that none of the major/popular front end frameworks can handle this at the moment (as you can see here: https://github.com/webcomponents/custom-elements-everywhere/issues/234)

**Comment by ukaaa** [comment]
@stephantabor Too bad. I might look at creating my own template-like element or something. But it will never have the true benefits of a `<template>`, so I guess I could just make it _any_ other element.

**Comment by projct1** [comment]
Same problem with Vue 3.
Cant use `template`-tag:
```html
<body>
    ... some html
    <template id="calendar">
        <div class="flex gap-1 items-center">
            <x-icon name="calendar" />
            ...
        </div>
    </template>
    ... some html
</body>
```
```javascript
createApp({
    mounted() {
        let tpl = document.getElementById('calendar')

        document.body.append(tpl.content.cloneNode(true)) //its not working
    }
}).mount(document.body)

document.addEventListener('DOMContentLoaded', () => {
    let tpl = document.getElementById('calendar')

    document.body.append(tpl.content.cloneNode(true)) //works fine
})
```
So nasty behaviour of Vue. How can disable it? Help me plz :)
