### ISSUE TITLE
v-bind with v-model not working

### ISSUE THREAD

**Issue by tanhs** [vuejs/vue#9969]
### Version
2.6.7

### Reproduction link
[https://codepen.io/tan-hai-shi/pen/KYjEXR](https://codepen.io/tan-hai-shi/pen/KYjEXR)

### Steps to reproduce
Row.vue
        <control-item v-for="(control, index) in row.controls"
                      :control="control"
                      :key="control.name"
                      :list="list"
                      >
        </control-item>

ControlItem.vue
...
                <input :name="control.fieldName" 
                       v-bind= "getFieldName"
                       ></input>

....
export default...
        computed: {
            getFieldName(){
                return {
                    'v-model': "list." this.control.fieldName

                    
                }                
            },

### What is expected?
I expect each of the input will have a dynamic v-model eg.
list.abc
list.def  etc

### What is actually happening?
list is blank

**Comment by posva** [comment]
`v-model` is a directive, not a prop/attribute, it cannot be _added_ with `v-bind`. BTW, your repro is outputting many more errors, make sure to use the non-minified version of Vue, it will help you during development!

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
