### ISSUE TITLE
Access to component data in style block

### ISSUE THREAD

**Issue by wolandec** [vuejs/vue#9971]
### What problem does this feature solve?
It is useful to pass style information into component instance in runtime. There is a computed style attribute approach, but the code using that way is not really clean while style information could be really big.

### What does the proposed API look like?
```
<template>

    <div>{{ display }}</div>

</template>


<script>

    export default {
        data(){
            return { display: 'block' }
        }
    }

</script>


<style>
    body {
        display: {{ display }}
    }
</style>
```

**Comment by posva** [comment]
This should go to vue-loader repository instead.
However, I recommend you using CSS variables instead and set them through a `style` binding on the element.

**Comment by wolandec** [comment]
This is not about loader, I want to style be changed in runtime. I know about style attribute and using it in runtime, but the code is not really clear and concise in that case, so is there any global problems which appears when we would get access to component data inside style element?

**Comment by LinusBorg** [comment]
> This is not about loader

It is. Your example code shows that you want to change the Single File Component format to somehow allow injecting stuff into the CSS part at rutime.

Single File component logic is primarily located in vue-loader (and some utils repos), and not át all in this core repo.

> , so is there any global problems which appears when we would get access to component data inside style element?

Yes. This will be technically impossible to to in the context of webpack, as CSS is static, and it is compiled and build time, so you can't (reasonably) manipulate it at runtime.

That's what CSS Variables are good for (but lack IE support)

**Comment by wolandec** [comment]
I see, thank you!
