### ISSUE TITLE
arrow function in string template to work in old browser (android 6.0) 

### ISSUE THREAD

**Issue by omkardusane** [vuejs/vue#9973]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/omkardusane/m36tvz8w/24/ 1](https://jsfiddle.net/omkardusane/m36tvz8w/24/ 1)

### Steps to reproduce

https://jsfiddle.net/omkardusane/m36tvz8w/24/ 1

### What is expected?
This should work in android's 6.0

### What is actually happening?
Doesnt work due to arrow function doesn't get compiled in backward compatible if it is in stringified template

---
I am trying to achieve this without the arrow function in the stringified component template.

**Comment by posva** [comment]
Hi, this is not related to Vue, it's related to usinng modern js in older browsers. We provide a version that works on older browsers but we cannot control the code you write.

---
Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by Justineo** [comment]
If you want to use arrow functions and ship code for older browsers, you need to introduce a build step to transpile them. (Try [Vue Loader](https://vue-loader.vuejs.org/) with webpack.)

**Comment by omkardusane** [comment]
I understand that reading this issue might lead you to think it is not a vue issue, agreeing on that, I would still like to point out that the snippet I have put up is highlighting a major lack in Vue to be able to return an event handler in the component's template while the template is being mounted, which we can achieve in react, hence it is intuitive. Can we start a discussion somewhere (any preferred medium where I can seek your attention to convey this issue). Please beleive me it can be a good thing once adressed properly. Currently the problem is unsolvable to me, transpilers do not work inside stringified templates.

**Comment by posva** [comment]
As indicated in the issue helper and my comment, use the forum or the chat, thank you.

The problem of arrow function support is **completely** unrelated to whatever framework you use, if you need to support older browsers without using a build step, then write js code that is supported by all browsers. This is valid in Vue, React and any other framework
