### ISSUE TITLE
export 'default' (imported as 'store') was not found in '@/store'

### ISSUE THREAD

**Issue by PakTo** [vuejs/vue#9976]
### Version
2.5.22

### Reproduction link
[https://stackoverflow.com/questions/46836956/importing-store-into-a-lib-js-while-using-vuex-with-ssr](https://stackoverflow.com/questions/46836956/importing-store-into-a-lib-js-while-using-vuex-with-ssr)

### Steps to reproduce
In Vue SSR, I can't not import store to commit. How can I import store in my plugins or controllers?

### What is expected?
In other JS modules, import store successfully.

### What is actually happening?
export 'default' (imported as 'store') was not found in '@/store'

---
https://stackoverflow.com/questions/46836956/importing-store-into-a-lib-js-while-using-vuex-with-ssr

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Discord chat](https://chat.vuejs.org),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
