### ISSUE TITLE
Outdated version of growl susceptible to command injection

### ISSUE THREAD

**Issue by nucleausllc** [vuejs/vue#9977]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
Inspect JS dependencies

### What is expected?
Latest version of growl

### What is actually happening?
Outdated version of growl

---
Scanned with [Nucleaus](https://nucleaus.com/?ref=github) code scan

**Comment by posva** [comment]
Thank you for your concern, however, Vue has no dependencies, this is all in dependencies of dev dependencies or dev dependencies directly. We will check this and fix it :)
