### ISSUE TITLE
Where is the vue 3 branch

### ISSUE THREAD

**Issue by martinoppitz** [vuejs/vue#9978]
What can we do?

**Comment by yyx990803** [comment]
We will open source it when it reaches relatively stable status (i.e. no more big overhauls / refactors) to avoid potential confusion.

**Comment by martinoppitz** [comment]
@yyx990803 thank for you info

**Comment by mustafaekim** [comment]
I am quite stuck and I try to made a decision. Our project is using typescript (commonjs modules) and vuejs. And dynamic imports does not seem to work with commonjs modules. Should I move to esnext somehow (I am getting a lots of errors when I try it) or will dynamic imports work in Vue 3 with commonjs?

**Comment by brokenthorn** [comment]
> We will open source it when it reaches relatively stable status (i.e. no more big overhauls / refactors). It is kept private for now to avoid potential confusion.

I was interested as well mainly because I wanted to know the tslint config.
