### ISSUE TITLE
Outdated version of randomatic uses cryptographically weak PRNG

### ISSUE THREAD

**Issue by nucleausllc** [vuejs/vue#9979]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
Inspect JS dependencies

### What is expected?
Latest version of **randomatic**

### What is actually happening?
Outdated version of **randomatic**

---
**Overview**
Affected versions of randomatic generate random values using a cryptographically weak psuedo-random number generator. This may result in predictable values instead of random values as intended.

**Remediation**
Update to version 3.0.0 or later.

Scanned with [Nucleaus](https://nucleaus.com/?ref=github) code scan

**Comment by posva** [comment]
Thank you for your concern, however, Vue has no dependencies, this is all in dependencies of dev dependencies or dev dependencies directly. We will check this and fix it :)
