### ISSUE TITLE
Outdated version of js-yaml susceptible to code injection

### ISSUE THREAD

**Issue by nucleausllc** [vuejs/vue#9980]
### Version
2.6.10

### Reproduction link
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)

### Steps to reproduce
Inspect JS dependencies

### What is expected?
Latest version of **js-yaml**

### What is actually happening?
Outdated version of **js-yaml**

---
**Overview**
Versions of js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file. Objects that have toString as key, JavaScript code as value and are used as explicit mapping keys allow attackers to execute the supplied code through the load() function. The safeLoad() function is unaffected.

An example payload is { toString: !&lt;tag:yaml.org,2002:js/function&gt; 'function (){return Date.now()}' } : 1 which returns the object { "1553107949161": 1 }

**Remediation**
Upgrade to version 3.13.1.

Scanned with [Nucleaus](https://nucleaus.com?ref=github) code scan

**Comment by posva** [comment]
Thank you for your concern, however, Vue has no dependencies, this is all in dependencies of dev dependencies or dev dependencies directly. We will check this and fix it :)
