### ISSUE TITLE
Cannot read property '_normalized' of undefined

### ISSUE THREAD

**Issue by bolosea** [vuejs/vue#9982]
I have a data article like this: {a:{name:'aa'},id:1}
When I write this <span >{{article.a.name}}</span>
The page will report 'Cannot read property name with undefined'
But this a does have data, so I used {{article.a&&article.a.name}} and reported Cannot read property '_normalized' of undefined
Why is this happening? 。。。

**Comment by notflip** [comment]
@bolosea Did you find a solution to this?

**Comment by Dagge1** [comment]
As of Feb 2020 Error is still unresolved

**Comment by MirzaeiDev** [comment]
Hello my friend . I'm not very good at English. This error is due to the fact that your data has not yet been read to the line where you left the article.
You can fix this error by setting "if".
result =>
```
<elemnt>
  {{article ? article.a.name : '' }}
</elemnt>
```

**Comment by befkaduBelete** [comment]
This error happens when  we use   <nuxt-link> </ nuxt-link> without  **to**  parm
