### ISSUE TITLE
Vue can't work fine with Safari History Gesture

### ISSUE THREAD

**Issue by skyfore** [vuejs/vue#9983]
### Version
2.5.22

### Reproduction link
[https://github.com/skyfore/vue-safari-gesture-minirepo](https://github.com/skyfore/vue-safari-gesture-minirepo)

### Steps to reproduce
1. npm run start
2. Open in safari
3. Click "Go to Hello"
4. Use History Gesture to Back

————
1. 运行项目
2. 在 IOS safari 打开地址
3. 点击 "Go to Hello"
4. 使用左侧右滑返回

### What is expected?
emit "hello" page beforeRouteLeave hook and stay in "hello" page

————
触发 vue-router 的 beforeRouteLevel 钩子停留在当前页面

### What is actually happening?
back to "Go to Hello" page

————
返回上个页面，过了大约2s后才回退到 “Hello” 页面

---
IOS Safari 12

**Comment by posva** [comment]
I tested and it works. It displays the old page but that's because Safari displays an old screenshot of the website.
BTW this should have been reported in vue-router instead

**Comment by skyfore** [comment]
@posva  Could you give me some link information?

**Comment by VictorWuSH** [comment]
我也遇到了一样的问题；
1.如果在beforeEach中返回next(false)阻止回退，会先显示上一个页面，然后在突然显示本页面；
2.如果在beforeEach中返回next(true),会返回上一个页面，但是也页面会有一个短暂卡死状态
