### ISSUE TITLE
Callback funtion not being called (mathjax-node)

### ISSUE THREAD

**Issue by Argetan** [vuejs/vue#9985]
### Version
2.6.10

### Reproduction link
[https://github.com/Argetan/rubber](https://github.com/Argetan/rubber)

### Steps to reproduce
Clone my repository and run `yarn`.

After doing so run `node mj-test.js`, this is the expected result. Running the Vue project (`yarn run dev`) will run the exact same code in a component but somehow the callback function is not being called.

### What is expected?
As is the case with `mj-test.js` I expect the callback function to be called which will print the data provided by MathJax.

### What is actually happening?
Running the exact same code from a component (`src/main/renderer/component/Renderer.vue` by using `yarn run dev`) will not call the callback function (for clarity sake I added multiple `console.log()` calls so that it's clear what is being run and what not).

---
I'm not sure if this is an issue with MathJax or with Vue, but since it is working as a standalone file I assume it's an issue with Vue, but maybe I'm missing something very obvious here.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you were to report a bug, please provide a minimal repro with no dependencies to showcase the problem
