### ISSUE TITLE
Assigning dynamic array to v-model

### ISSUE THREAD

**Issue by tanhs** [vuejs/vue#9989]
### Version
2.6.7

### Reproduction link
[https://codepen.io/tan-hai-shi/pen/dEbKQj?editors=1011](https://codepen.io/tan-hai-shi/pen/dEbKQj?editors=1011)

### Steps to reproduce
I am  trying to use dynamic array to assign as v-model but not able get it working.
I have tried :v-model or v-model, both doesn't work.

### What is expected?
formdata: ['t1', 't2', 't3']

### What is actually happening?
formdata no value with :v-model, if i use v-model(without ":") all 3 checkbox will checked when i click one checkbox only and formdata also not showing anything

**Comment by Justineo** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
