### ISSUE TITLE
<textarea> behavior is different from the document

### ISSUE THREAD

**Issue by taichiro** [vuejs/vue#9996]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/ll67l7p68z](https://codesandbox.io/embed/ll67l7p68z)

### Steps to reproduce
1. Input text to `<input type="text" v-model="text" />`
2. Text is displayed in `<textarea>{{text}}</textarea>`

### What is expected?
The document has the following note:
> Interpolation on textareas (`<textarea>{{text}}</textarea>`) won't work.
Use v-model instead.

https://vuejs.org/v2/guide/forms.html#Multiline-text

### What is actually happening?
The following code actually works.
```html
<textarea>{{text}}</textarea>
```

---
Is this the intended behavior of Vue?
Also, what is the reason for recommended v-model?
I see `<textarea>{{text}}</textarea>` is the correct Vue template.

**Comment by posva** [comment]
v-model is to have two-way binding. If you have a recommendation for the docs, you can send your recommendation as an issue or pr in vuejs.org repo 🙂

**Comment by taichiro** [comment]
@posva thanks for reply.
